### ISSUE TITLE
Lazy load cart items from session/DB

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#10705]
https://trello.com/c/9cGVYoga/22-lazy-load-cart-items-from-session-db-cart-item-class-5252

To improve performance when product classes are not accessed.

**Comment by DuckDagobert** [comment]
It would be even faster, if you set the cart content as a fragment and call it via ajax (when used with a permanent object_cache even a minimalist ajax, as admin-ajax is way too heavy) => this is especially interesting with full page cache plugins, as this is a emulation of the behavior e.g. Facebook has with Bigpipe.

**Comment by addedlovely** [comment]
Came across this VIP article today, thought it might be of interest. See the custom endpoints section. 

> You can create http://example.com/ajax/my_frontend_ajax_function/parameter_1/ to make ajax requests that are cached for 5 minutes for all users with batcache. This will make request time go down often 100 folds! Note that the ajax rewrites are to index.php and not to admin-ajax.php. You are creating a new endpoint that will call your PHP function, not rewriting the query to pass to admin-ajax.php

[https://vip.wordpress.com/documentation/wp_rewrite/](https://vip.wordpress.com/documentation/wp_rewrite/)

**Comment by BurlesonBrad** [comment]
@addedlovely That's **SMOKIN' HOT!**
 _#always-be-learning_

**Comment by mikejolley** [comment]
Requires a massive refactor of the cart - let's review during #12006 which is doing just that.
