### ISSUE TITLE
Click to edit image details in gallery meta box

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#10791]
https://wordpress.org/support/topic/clickable-product-gallery-thumbnails-in-admin?replies=1

**Comment by Lewiscowles1986** [comment]
Would it be possible to store the product gallery in a different format for this?

`_product_gallery_%i`

My thinking is this. Right now any logic around the gallery has to be accomplished in PHP. I've just migrated a client site and it was easier to delete the image gallery meta than migrate the images, which meant a bit more setup than if each image id was in it's own meta (in which case I could get MySQL to do the leg-work for me).

**Comment by Lewiscowles1986** [comment]
Also on this, even if exporting all attachments via WXR and plugin, ID's wouldn't match. One alternative to these living in meta I suppose could be a table just for product images. It would offload a bit more from meta

**Comment by mikejolley** [comment]
Punting. Not essential for this release.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/13071
