### ISSUE TITLE
Password managers are identifying/storing wrong username field when creating a user account

### ISSUE THREAD

**Issue by SukcesStrony** [woocommerce/woocommerce#11016]
## EXPLANATION OF THE ISSUE

Browsers' password managers (checked on latest Firefox & Chrome) fill out and save the incorrect login when creating an account during checkout. This is because browsers find the password input field and assume the field above it will be the login field, when in fact they should store the e-mail field or a dynamically generated login (which I assume WooCommerce generates somehow, or it uses the full e-mail address for a login - I don't know).
This exact same issue was detected, explained and discussed on Drupal: https://www.drupal.org/node/2191785
## STEPS TO REPRODUCE THE ISSUE
1. Make sure you're logged out
2. Add a product to the cart
3. Continue to checkout
4. If you have a login/password stored for this page, the login will be pushed by the browser into the field directly above the password field (so into City). If you don't have this data stored, try to create an account and see the prompt - it will try to remember the wrong login field.
## SOLUTIONS
1. Changing the order of the input fields so that e-mail is above the password field.
2. Making a hidden input field above the password field with the proper value (doesn't sound great, especially when JavaScript is off).
3. Other ideas - submit below.

**Comment by mikejolley** [comment]
Part of #10672

**Comment by mikejolley** [comment]
Annoyingly 1password also ignores autocomplete properties, even if you name one 'username'. Without a way to specify what fields are what, I don't think there is much we can do here. Moving the fields into an order it can handle is a horrible workaround tbh. It may be part of #10672 as I said, but that design should not need to work around 1password.

**Comment by SukcesStrony** [comment]
I didn't mention 1password here, just the native browsers' password storage services which work on Chrome & Firefox. Did you perhaps check that adding those autocomplete properties fixes this issue for those native password managers?

If it doesn't, we still have the majority of users having the wrong password field saved in their browser, which leads to problems with logging in. This looks like a problem big enough to change the order of the form fields - even if it's not a great workaround. It would work and would not introduce other issues.

**Comment by mikejolley** [comment]
My password manager didn't trigger for chrome so no, I just checked 1password which stored the postcode...

> If it doesn't, we still have the majority of users having the wrong password field saved in their browser, which leads to problems with logging in

If it were the password yes, but I think you'll notice the wrong user? This has happened to me on other sites.

**Comment by SukcesStrony** [comment]
Um yes, I agree - the incorrect login will be remembered, not password. While users might notice this right away after the first error, this makes the password managers useless for over 50% (browser market share) of users, at least until they update it. I think it's worth fixing - the form won't look as pretty when the username is next to the checkbox, but at least it will fix the problem and it will provide some sense (having a username next to the password field).

That said, when the username is generated automatically (which is set in the WooCommerce settings), the password checkbox & password field should be right next to the email address. This would push the telephone number down, if not using CSS floating (which seems like a bad idea). So, a rework of the form in this regard would be needed.
