### ISSUE TITLE
WC 2.6 - Recurring customer cannot change payment method on checkout w/ WooCommerce Germanized enabled

### ISSUE THREAD

**Issue by chriskapffer** [woocommerce/woocommerce#11207]
The issue is definitely triggered by WooCommerce Germanized, however, I think that the bug itself comes from woocommerce. 

## STEPS TO REPRODUCE THE ISSUE

1. Download and activate [WooCommerce Germanized](https://wordpress.org/plugins/woocommerce-germanized/)
2. Login as an existing customer, who has made a purchase before
3. Add a product to the cart and go to checkout page.
4. Try to select another payment method than the one previously selected
5. Watch how WooCommerce Germanized makes an ajax call to `update_order_review`
6. Notice that after the ajax is done, the previous payment method is selected again, thus making it impossible for the customer to change it.

## EXPLANATION OF THE ISSUE

WooCommerce Gemanized adds following js to the checkout page:
`$( document ).on( 'change', '.payment_methods input[name="payment_method"]', function() {
    $( 'body' ).trigger( 'update_checkout' );
});`
I guess they do it to calculate some additional fees upon selected payment method.
This triggers the `update_order_review` ajax handler, which calls the `woocommerce_checkout_payment` template function, which calls `set_current_gateway` of class `WC_Payment_Gateways`. So in /woocommerce/includes/class-wc-payment-gateways.php line 186 it reads:
`$current = ( isset( $default_token_gateway ) ? $default_token_gateway : WC()->session->get( 'chosen_payment_method' ) );`
With this line the default gateway will always be chosen, no matter what the session gateway is (which gets set to the value selected by the customer in /woocommerce/includes/class-wc-ajax.php line 310).

## POSSIBLE FIX

Replace /woocommerce/includes/class-wc-payment-gateways.php line 186 with

`		$current = WC()->session->get( 'chosen_payment_method' );
		if ( empty($current) && isset( $default_token_gateway ) ) {
			$current = $default_token_gateway;
		}`

Without knowing what else is affected by that change, it does fix the issue at hand and enables the customer to change the payment method.

This might also fix issue #10764

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: https://matthewbjarne-mirror
Site URL: https://matthewbjarne-mirror
WC Version: 2.6.1
Log Directory Writable: ✔
WP Version: 4.5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE_formal

### Server Environment ###

Server Info: Apache/2.4.20 (Unix) PHP/7.0.6 mod_wsgi/3.5 Python/3.5.1 OpenSSL/1.0.1p
PHP Version: 7.0.6
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/1.0.1p

SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.1
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (3) ###

WooCommerce Stripe Gateway: von Automattic – 3.0.2
WooCommerce Germanized: von Vendidero – 1.6.8
WooCommerce: von WooThemes – 2.6.1

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop-Basis: #773 - /produkte/
Warenkorb: #774 - /warenkorb/
Kasse: #775 - /kasse/
Mein Konto: #776 - /mein-konto/

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)


### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – Wenn Sie WooCommerce oder ein Parent Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie Sie ein Child Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by claudiosmweb** [comment]
> The issue is definitely triggered by WooCommerce Germanized, however, I think that the bug itself comes from woocommerce. 

Check with the author of WooCommerce Germanized first.

**Comment by codingChris** [comment]
I dont't mean to be rude, but did you read past that first few lines? Sure, the ajax method `update_order_review` might not be designed to be called on checkout, but in woocommerce 2.5 `set_current_gateway` (which gets called along the way) does exactly what it says, setting the current gateway to what is stored in the session. But in 2.6 it clearly favors `$default_token_gateway` over the session content, which I think should be the other way around.
WooCommerce Germanized won't change their js script, since they depend on it to recalculate additional fees dynamically. For me (who depends on both plugins), I am left with this issue and whould like to get at least an explanation on why I am wrong with my intepreation. Your comment seems as if you didn't even consider that there might be a bug in woocommerce, regardless of what woocommerce Germanized does. Maybe @mikejolley would like to weigh in here?

**Comment by mikejolley** [comment]
If they cannot do something, why have they not suggested a PR? We don't fix third party plugins but will happily review changes if it does not affect core negatively.

**Comment by mikejolley** [comment]
Also I'm afk so cannot review the code, but in general PRs are better :)

**Comment by tommyshellberg** [comment]
@codingChris I tried your fix and it appears to resolve this. I would submit a PR for this. :)

**Comment by chrillo** [comment]
I have the same issue - @mikejolley would a accept a PR with @codingChris fix then I'll submit it, the fixing it self being simple enough. I also agree with @codingChris that the issue seems to be on the WooCommerce side of things as the way the current paymentToken handling is implemented it makes it impossible to change the payment method when a paymentToken is available.

**Comment by mdmoore** [comment]
This issue is coming up with any extension that calls `update_checkout` on payment method change.  @chriskapffer @chrillo How about that PR?

**Comment by mikejolley** [comment]
@chriskapffer Want to send that as a PR?

**Comment by chriskapffer** [comment]
@mikejolley I did that a few days ago (see #11997), but it was (rightfully) rejected. 

@justinshreve gave following explanation:

> If I have "Gateway A" as my default and I make an order using "Gateway B" -- I don't want my next order to be "Gateway B" --- otherwise I would go update my default method.

> There is already some JS to make sure that update_checkout keeps the users payment selection while viewing the form. Germanized might be doing something too late.

**Comment by mikejolley** [comment]
Ah Ok, I missed that. The PR didn't link here.

https://github.com/woocommerce/woocommerce/pull/11997

For future ref:

```
There is already some JS to make sure that update_checkout keeps the users payment selection while viewing the form. Germanized might be doing something too late.
```
