### ISSUE TITLE
Introduce backorder stock status + automatic assignments

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#11259]
Right now backorders are a bit weak. We add meta data to orders when a backorder is made, and we keep the item 'in stock'.

I propose having a new 'on-backorder' status.

This would mean you could for one thing, filter products by backorder status to see what is currently on backorder.

It would also simplify the availability class code.

And to keep the stock status easier to use and to reduce likelihood of status/stock level conflict, I suggest we hide the stock status field **if stock management is enabled** and set it automatically.
- Stock level < Out of stock threshold (no backorders) - set out of stock
- Stock level < Out of stock threshold (with backorders) - set on backorder
- Stock level > Out of stock threshold - set in stock

TODOS:

- [ ] Register new stock status named on-backorder
- [ ] Update data stores to accept backorder status
- [ ] Set on-backorder status based on stock and backorder setting criteria as outlined above
- [ ] Update product displays to use the new status
- [ ] Update routines to set correct status after the update

**Comment by jameskoster** [comment]
> And to keep the stock status easier to use and to reduce likelihood of status/stock level conflict, I suggest we hide the stock status field if stock management is enabled and set it automatically.

Big +1!

**Comment by franticpsyx** [comment]
@mikejolley +1. Always felt that a `on-backorder` status would make more sense. Also this will resolve various quirks / confusion, for instance:

- Setting a positive stock when a product stock status is Out Of Stock switches the status to In Stock (?!). Makes sense but creates confusion in some cases.
- When a product status is Out Of Stock but backorders are allowed, the status is ignored.

>And to keep the stock status easier to use and to reduce likelihood of status/stock level conflict, I suggest we hide the stock status field if stock management is enabled and set it automatically.

The only issue I see with this is that we won't be able to set a product as Out Of Stock without changing the inventory count. In some cases, this is a very welcome feature. After the change, the shop manager will need to remember the remaining stock count in order to change back the stock status to In Stock.

**Comment by claudiosmweb** [comment]
> I suggest we hide the stock status field if stock management is enabled and set it automatically.

And how about when you have a product in stock, but you need set the stock as "Out of Stock", for some reason like, to hold the items for a customer that you are selling by phone or wherever?
Since if you set as "Out of Stock" will stop people to buy from the frontend, but you can still create an order in the admin and reduce the stock... I saw a few people doing it.

I'm not against of remove it, just saying something we can consider... But I like the idea :smile:

**Comment by Osimiso** [comment]
I agree with Mike. Backorders are like half done to me.
In my shop I sell most of the goods with backorder allowed(hundreds of products). To be able to manage it I added some new meta data fields fields and created a small plugin. Here I'm listing how many goods needs to be ordered, and how many are already on the road.  
So have a new stock status 'on-backorder' is a step to right direction for me. It doesn't have to be complex solution at the beginning. But I would prefer to have it as a core functionality.

@claudiosanches I would say that products with backorder enabled could never trigger "Out of Stock" message. They are virtually On Stock always. If you want to hide product just change visibility.

**Comment by svenm73** [comment]
first thanks to Mike for pointing me to this threat.

just to give me 2 cents - I totally agree - the current backorder handling is not correct and does not work when you have an ERP System in the background. When a product is physically out of stock but available on backorder, the user needs to be able to add it to the cart - but still needs to see on the frontend that the product is only available on backorder.

kind regards
Sven

**Comment by aurora** [comment]
I totally agree with Sven on this.

**Comment by puregraphx** [comment]
+1 @svenm73 
We have a different message next to the add to cart button for in stock and out of stock status indicating the delivery time (2 days vs 2 weeks for backorders). So, when we have to set a product to In Stock in order for the Backorders to work, people are misinformed by the In Stock message.

To sum up: Out of Stock + Allow Backorder should allow customer to place an order.

**Comment by mickand** [comment]
Totally agree with puregraphx

Out of Stock + Allow Backorder should allow customer to place an order.

**Comment by thomasmery** [comment]
FWIW

seconding: Out of Stock + Allow Backorder should allow customer to place an order

at the moment  it's, imho, really counter-intuitive to have to set a Product as 'In stock' just to allow backorders

I have the feeling that some might argue that 'In Stock' means either actual 'In Stock' or 'Can be ordered' (if Allow Backorder is true)

but is it not more straight fwd to consider 'In stock' as 'We have the product ... In Stock ... and thus don't need to order it for you'

but maybe I'm just confused :)

and hoping Mike's proposal goes fwd as it seems a good solution to clear the confusion

**Comment by UserName011** [comment]
I think this can be a bit wider.
If we also consider this:
https://github.com/woocommerce/woocommerce/issues/12596

Item could be not in stock but still get orders which will be fulfilled when stock is available (if store owner allow this).
It is possible to give a more flexible approach to handle this.

**Comment by tquadra** [comment]
I asked about that in woocommerce.com support ticket 487434 and got an answer that the current behavior was intended for "broader convenience". I don't understand why the more logic approach suggested here would have negative effects, but I accepted the answer. 

I am glad to see the improvement is been handled and I support the request to allow Out of Stock + Allow Backorder should allow customer to place an order. A 3rd status 'in backorder' would work as well.

Is there anything we can do to have that change in a minor release or anyone interested in crowfunding a custom development to change that behavior while we wait for the next major release?

**Comment by mikejolley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [A new backorder stock status](https://trello.com/c/1Z4IqZBO/108-a-new-backorder-stock-status)

**Comment by bjonespro** [comment]
I would like to see verbiage added in the cart stating the number of items that are being back ordered.  For instance: a customer orders 7 of an item when only 5 are currently in stock and the other 2 can be delivered shortly after.  This is allowed but not shown in the cart.  The cart makes it appear that all 7 are being shipped immediately.  Is this something that could be addressed?

**Comment by surferking** [comment]
@bjonespro we use these plugins to address the use-case you describe:

This one creates a Custom Post Type called 'Order Shipments' to show below Orders on the My Account page:
https://woocommerce.com/products/shipping-multiple-addresses/

And this creates the connections between Shipment & Order Lines:
https://wordpress.org/plugins/packages-configuration-for-woocommerce/

That gives you the data structure you need - but you'll need to do your own theme custom stuff to display that data.

Googling "Woocommerce Partial Orders" may yield a plugin option for you to communicate that too. (not sure if I am allowed to link to non-WooTheme commercial plugs?)

I'd have posted on the #13097 but it's closed. I'll sign-up to the forum and add the same there.

HTHs

**Comment by claudiulodro** [comment]
The ability to set 'onbackorder' stock status through the API for products that don't have stock management enabled is going to be in API v3. See: https://github.com/woocommerce/wc-api-dev/issues/75
