### ISSUE TITLE
Cache and refactoring Api Keys functions

### ISSUE THREAD

**Issue by igmoweb** [woocommerce/woocommerce#11592]
The functions that insert, delete and update API Keys in woocommerce_api_keys table needs to cache their results. Sites with a huge amount of users making use of the API could introduce big performance penalties when authenticating users.

Additionally, a good refactoring of these functions would keep some kittens alive.

These functions are spread into five different files/classes:

**includes/api/class-wc-rest-authentication.php**
- `get_user_data_by_consumer_key( $consumer_key )`. It should cache the results
- `update_last_access( $key_id )`: It updates last_access column but this value is not cached in the previous function.
- `check_oauth_timestamp_and_nonce( $user, $timestamp, $nonce )`: It should update the cached values in `get_user_data_by_consumer_key` function (only nonces are updated in this function

**includes/class-wc-ajax.php**
- `update_api_key()`: If an existing API Key is updated, it should invalidate the cache for that consumer Key. If a new record is added, it should cache the data by consumer Key

**includes/class-wc-auth.php**
- `create_keys( $app_name, $app_user_id, $scope )`: This function is redundant, see`WC_AJAX::update_api_key()`
- `maybe_delete_key( $key )`: It should invalidate cache.

**includes/admin/class-wc-admin-api-keys-table-list.php**
- `prepare_items()`: makes two queries: first get all API keys, paginated. Second gets a count for the API Keys rows. Would be nice to save one query in that operation and cache results too.

**includes/admin/class-wc-admin-api-keys.php**
- `remove_key( $key_id )`: Again, redundant code, see`WC_Auth:maybe_delete_key( $key_id )`
## So, here's what I have in mind:
1. Refactor the code and move all those CRUD queries to a single class, could be WC_Auth or a complete new class. 
2. Add cache to those functions.
3. Write some unit tests.

Here's a list of functions that I can think about at first thought:
- `get_api_keys( $args = array() )` It could allow to pass per_page, offset and count arguments. It would also cache the results.
- `get_api_key_data( $key_id_or_consumer_key )` It returns the API Key data given the Key ID or an unhashed Consumer Key. It would cache the results by $key_id and also by **hashed** Consumer Key
- `update_api_key_data( $key_id, $args = array() )` It should update API Key data and also invalidate or update caches by key_id and hashed consumer_key
- `delete_api_key( $key_id )` Invalidate cache based on key_id and hashed consumer_key. For that, an extra query is needed to get the api key data and extract the hashed consumer key.
- `clear_api_key_cache( $key_id )` Invalidates cache for a given Key ID but it also needs to get the API Key Data and invalidate cache based on hashed Consumer Key.

Any insert, delete or update function will also invalidate the `get_api_keys()` cached results.

I can make a PR and work on this but I'd like to start a conversation before putting my hands on it.

Thanks.

**Comment by claudiosmweb** [comment]
Feel free to submit a Pull Request.

**Comment by igmoweb** [comment]
@claudiosmweb 
PR sent.

Cheers.

**Comment by mikejolley** [comment]
Closed in favour of #11616
