### ISSUE TITLE
CRUD - Products

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#11602]

**Comment by kieranbarnes** [comment]
@claudiosmweb Is this the issue you are referring to here https://github.com/woocommerce/woocommerce/issues/11913#issuecomment-246834037?

If so, is there any more info at this stage? We deal with a lot of WC sites crippled by postmeta bloat.
EAV/Horizontal meta sounds great but I don't see any info on the roadmap for this.

**Comment by claudiosmweb** [comment]
@kieranbarnes not on roadmap for 2.7. But once we have this CRUD done it's easy to have EAV/Horizontal meta sounds.

**Comment by mikejolley** [comment]
Closed in favour of #12065 which has the last remaining items listed inside.
