### ISSUE TITLE
Products API - More filters/search

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#11610]
- [ ] sort by stock status
- [ ] top rated

**Comment by mikejolley** [comment]
@coderkevin Can you add in here what extra search/filter criteria you think you'll need?

**Comment by coderkevin** [comment]
Sorry, I must have overlooked this with all the other notifications. Let's talk about this.

**Comment by mikejolley** [comment]
https://teamxthings.wordpress.com/2016/09/02/product-filters/

**Comment by mikejolley** [comment]
Use POST to a new endpoint, `/products/search`, which takes a set of search params. These would need to be predefined in the schema to show supported search fields.

**Comment by claudiosmweb** [comment]
Why "POST" for a endpoint to "GET" things?
And it's the same than `GET /products`, we only need new parameters for it.

**Comment by mikejolley** [comment]
@claudiosmweb you're posting the search params. Also as shown by SKU, query string is not reliable for some data.

**Comment by claudiosmweb** [comment]
Closed in favor of #12057

**Comment by claudiosmweb** [comment]
Talked with @mikejolley today and don't have any problems with SKU or any kind of data that is coming from query string.
SKU should be a problem if we are trying to use as an endpoint like `GET /products/sku/#bar*&$`.

And don't have problems with long request URI, at least we can use 4,000 characters:
https://www.w3.org/2001/tag/doc/get7#myths
