### ISSUE TITLE
Theming: Remove product images size settings and allow themes to specify their own sizes

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#11666]
Our image dimension settings have been a cause for confusion for a long time. 
1. People don't know and worry about what size to use
2. They expect the dimensions they input to be exactly the size the images display
3. But the _actual_ size the images are displayed at rarely (never) matches the settings - themes ultimately control this

The best way to remove the confusion? Just remove the settings, but give themes a simple way to overrule the defaults.

So, we set the defaults to an appropriate size that covers default themes. Then offer a filter or something like the `$content_width` var in core to allow themes to specify which size images WooCommerce should create. 

In the image settings, if the theme specifies something different to the default display the regen thumbs notice.

Keep the hard crop option.

Make sense? Thoughts?

**Comment by mikejolley** [comment]
Since core supports srcset, are multiple predefined sizes even needed any more?

**Comment by jameskoster** [comment]
Good point, perhaps not. 

We will need a way for users to specify the aspect ratio though.

**Comment by jameskoster** [comment]
Just did some reading on responsive images. We still need the defined sizes as wp uses this to populate the `size` attribute on each `img`.

Enabling users to control the aspect ratio is going to be tricky though. If we applied the suggestion above, users would be forced to use the themes suggested image size which might not always be appropriate. Struggling to think of a way to allow this without simply having the width/height inputs as we have now :<

**Comment by mikejolley** [comment]
Is this something which should go out with the new galleries?

**Comment by jameskoster** [comment]
Suppose it'd make sense thematically. If we can't think of a solution to the aspect ratio problem, it might be safer to just leave it as-is though.

**Comment by mikejolley** [comment]
Let's keep the options visible for non-wc supported themes, or add a new theme support variable to control this.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/17557
