### ISSUE TITLE
Add variations endpoint to REST API

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#11775]
Currently, the /products/ endpoint allows variations to be returned and updated, however this is buggy because the schemas differ.

New endpoint:

```
/products/<product_id>/variations/<id>
```

Functions: list, delete, create, update, batch

For anyone encountering this issue, don't update variations directly. Update the parent like this:

```
{
  "variations": [
    {
      "id": "41",
      "weight": "3.0"
    }
  ]
}
```

This example updates variation ID 41's weight.

**Comment by lawkwok** [comment]
I'm glad this issue got pinned down. Awesome new profile pic btw!

**Comment by lawkwok** [comment]
Another issue is that when updating a single variation, the updated variation jumps to the top of the list in the edit product page.

The current workaround is to send data for all variations.

**Comment by justinshreve** [comment]
Once we have these endpoints we should make sure to disable editing them via the normal product endpoints.

**Comment by danielhuesken** [comment]
@justinshreve i think that is in moment not a good idea. Because there are some serveices there use them actualy.

**Comment by justinshreve** [comment]
@danielhuesken Do you mean the method above (passing a `variations` array to the parent) or updating the variation via `/products/<variation_id>`? I meant the latter.

@mikejolley Didn't you mention it doesn't work? Or does it work and is just buggy? We'll have to make a ticket for removing for a future version of the API if thats the case.

**Comment by danielhuesken** [comment]
@justinshreve i mean "passing a variations array to the parent".

**Comment by justinshreve** [comment]
Okay cool - yeah, we'll keep that until the API is versioned at some point in the future.

**Comment by atandrauser** [comment]
Updating variant stock quantity via API v2 still does not work - following suggestions above.
I have woocommerce Version 3.0.6

Sending request to THIS url as per suggestions above
https://shoplasunandsport.com/wp-json/wc/v2/products/1728/variations/2073?consumer_key=ck_f30ef9630f46bd6b2b5a0477a7402c081c2f8e3b&consumer_secret=XYZ

The productID and variant ID is correct - https://www.screencast.com/t/Ct7M9CZx32

We do get a response back but the field stock_quantity  for the variant 2073 is not updated. The response still shows    "stock_quantity":0

Please help. Below is response back from API call to update varaint


{  
   "id":2073,
   "date_created":"2017-02-27T23:03:08",
   "date_created_gmt":"2017-02-27T23:03:08",
   "date_modified":"2017-05-12T14:52:49",
   "date_modified_gmt":"2017-05-12T14:52:49",
   "description":"",
   "permalink":"https:\/\/shoplasunandsport.com\/product\/lanai-bia-tube-halter\/?attribute_pa_color=blk-taupe&attribute_pa_size=large",
   "sku":"018-508-L",
   "price":"105",
   "regular_price":"105",
   "sale_price":"",
   "date_on_sale_from":null,
   "date_on_sale_from_gmt":null,
   "date_on_sale_to":null,
   "date_on_sale_to_gmt":null,
   "on_sale":false,
   "visible":false,
   "purchasable":true,
   "virtual":false,
   "downloadable":false,
   "downloads":[  

   ],
   "download_limit":-1,
   "download_expiry":-1,
   "tax_status":"taxable",
   "tax_class":"",
   "manage_stock":true,
   "stock_quantity":0,
   "in_stock":false,
   "backorders":"no",
   "backorders_allowed":false,
   "backordered":false,
   "weight":"",
   "dimensions":{  
      "length":"",
      "width":"",
      "height":""
   },
   "shipping_class":"",
   "shipping_class_id":0,
   "image":{  
      "id":0,
      "date_created":"2017-05-12T15:30:56",
      "date_created_gmt":"2017-05-12T15:30:56",
      "date_modified":"2017-05-12T15:30:56",
      "date_modified_gmt":"2017-05-12T15:30:56",
      "src":"https:\/\/shoplasunandsport.com\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png",
      "name":"Placeholder",
      "alt":"Placeholder",
      "position":0
   },
   "attributes":[  
      {  
         "id":1,
         "name":"Color",
         "option":"BLK\/TAUPE"
      },
      {  
         "id":2,
         "name":"Size",
         "option":"LARGE"
      }
   ],
   "menu_order":0,
   "meta_data":[  
      {  
         "id":21503,
         "key":"_upsell_skus",
         "value":[  

         ]
      },
      {  
         "id":21504,
         "key":"_crosssell_skus",
         "value":[  

         ]
      },
      {  
         "id":21507,
         "key":"_min_variation_price",
         "value":""
      },
      {  
         "id":21508,
         "key":"_max_variation_price",
         "value":""
      },
      {  
         "id":21509,
         "key":"_min_variation_regular_price",
         "value":""
      },
      {  
         "id":21510,
         "key":"_max_variation_regular_price",
         "value":""
      },
      {  
         "id":21511,
         "key":"_min_variation_sale_price",
         "value":""
      },
      {  
         "id":21512,
         "key":"_max_variation_sale_price",
         "value":""
      },
      {  
         "id":21514,
         "key":"_file_path",
         "value":""
      },
      {  
         "id":21518,
         "key":"_product_url",
         "value":""
      },
      {  
         "id":21519,
         "key":"_button_text",
         "value":""
      }
   ],
   "_links":{  
      "self":[  
         {  
            "href":"https:\/\/shoplasunandsport.com\/wp-json\/wc\/v2\/products\/1728\/variations\/2073"
         }
      ],
      "collection":[  
         {  
            "href":"https:\/\/shoplasunandsport.com\/wp-json\/wc\/v2\/products\/1728\/variations"
         }
      ],
      "up":[  
         {  
            "href":"https:\/\/shoplasunandsport.com\/wp-json\/wc\/v2\/products\/1728"
         }
      ]
   }
}

**Comment by strarsis** [comment]
Related issue: https://github.com/woocommerce/wc-api-php/issues/157
