### ISSUE TITLE
Inconsistency with actions on order pages

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#11784]
The Thank you page markup is all over the place:

<img width="698" alt="screen shot 2016-08-26 at 16 36 01" src="https://cloud.githubusercontent.com/assets/1001935/18009122/3628f89a-6bab-11e6-8b5f-2653d7e768c7.png">

This section goes from `p` to  `h2`, `header` then a `table`? No separation of sections, no targetable classes. There should be more actions before and after all of the sections for orders ( and all places of woocommerce ) to be able to customise these pages.

An example – how do you wrap this file in a div? `woocommerce/templates/order/order-details-customer.php`

**Comment by mikejolley** [comment]
What do you mean 'actions'? If you'd like to submit a PR with markup improvements by all means go ahead; @jay is on vacation this week.

**Comment by mikejolley** [comment]
Assigning to @jameskoster. Maybe we can make the headings etc more consistent, or at least wrap the thanks page content in a div with the new class name structure.
