### ISSUE TITLE
Add support for up-selling specific product variations

### ISSUE THREAD

**Issue by mattyza** [woocommerce/woocommerce#11818]
## EXPLANATION OF THE ISSUE

Currently, WooCommerce doesn't support up-selling of specific variations of a product. This can be useful when a specific variation of a bag, or accessory, goes well with a particular product.
## STEPS TO REPRODUCE THE ISSUE

When attempting to select a specific variation in the "Up-sells" search field inside the "Product Data" meta box, only the top-level products are returned.
## NEXT STEPS

I've gone ahead and [started off a branch](https://github.com/woothemes/woocommerce/tree/upsell-variations) to add variation support to up-sells and cross-sells. I've adjusted the WP Admin product search forms, and have begun adjusting the `up-sells.php` template file. Currently, the Meta_Query is interfering with returning the variations, although the Meta_Query is also important here.

Instead of adding a second query (not cool) specific to the variations, I figured it best to post here instead, and discuss how best to achieve this scenario.

**Comment by mikejolley** [comment]
Can you explain more about the feature, e.g. what the user sees when a variation is upsold? Since variations do not have their own single pages and often need user input.

**Comment by mattyza** [comment]
Sure.

An example use case is being able to up-sell a specific bag, for example, which goes really well with a camera lens, or a specific variation of a camera lens which goes particularly well with a certain camera (for example, a specific 35mm variation of a lens).

The mods in the [upsell-variations](https://github.com/woothemes/woocommerce/tree/upsell-variations) branch are able to show a specific variation as an up-sell, at the expense of needing to disable the meta_query, currently.

If this is better suited as a plugin, there would be a few hooks required in order to enable variation searching in the "up-sells" and "cross-sells" product search fields in WP Admin. Other than that, it's a template override, really.

Would be nice to have in core, though, if it's not too resource intensive.

**Comment by mattyza** [comment]
> what the user sees when a variation is upsold?
They see the same output as if a simple product was being up-sold, although instead of a "select options" button (for the variable product), they see the standard "add to cart" button, with the variation URL already inputted (tested, and it works like a charm).

**Comment by mikejolley** [comment]
See #12470
