### ISSUE TITLE
Too many similar translation strings

### ISSUE THREAD

**Issue by ramiy** [woocommerce/woocommerce#11905]
## THE ISSUE

With over 4500 translation strings it's very hard to [translate the plugin to other languages](https://translate.wordpress.org/projects/wp-plugins/woocommerce). Seems like the plugin have tons of similar translation strings. Many times the same sentence can be found in lowercase and in upper cases, other times we only miss a period. Also I found wrong use of `_x()` functions.

## EXAMPLES

![woocommerce-strings-1](https://cloud.githubusercontent.com/assets/576623/18442199/89247694-7918-11e6-9ae4-8b364a1ba1f6.png)

![woocommerce-strings-2](https://cloud.githubusercontent.com/assets/576623/18442204/8d3a607c-7918-11e6-9f46-048ee47caea4.png)

![woocommerce-strings-3](https://cloud.githubusercontent.com/assets/576623/18442207/8f71a602-7918-11e6-9bfd-328c879edd56.png)

![woocommerce-strings-4](https://cloud.githubusercontent.com/assets/576623/18442210/9185917e-7918-11e6-84b9-2a76fa4d54cf.png)

![woocommerce-strings-5](https://cloud.githubusercontent.com/assets/576623/18442422/578586cc-7919-11e6-9082-cf440e6e36fa.png)

![woocommerce-strings-6](https://cloud.githubusercontent.com/assets/576623/18442426/5b41e080-7919-11e6-9b89-4080bde4d028.png)

![woocommerce-strings-7](https://cloud.githubusercontent.com/assets/576623/18442498/aa5ff648-7919-11e6-9f95-014e3d216c17.png)

![woocommerce-strings-8](https://cloud.githubusercontent.com/assets/576623/18442686/5fcd0f66-791a-11e6-84fe-321fae853a7f.png)

## SOLUTION

The plugin needs an **i18n review** like we did in WordPress core.

I think we can reduce the total strings count by 5%-10%.

**Comment by claudiosmweb** [comment]
Good part is because the new REST API.
This should be improved when we remove the legacy APIs.
But I have plans to improve this strings in 2.7.

**Comment by ramiy** [comment]
@claudiosmweb, It's not an easy task. We did the same review in WordPress Core over 5 major versions. And we haven't finished yet. It's an ongoing process.

The i18n review should also include adding translators-comments, avoid using HTML tags in translation strings, unifying messages, and proper use of context functions.

**Comment by ramiy** [comment]
@mikejolley @claudiosmweb Any chance the PR will be merged to milestone 2.7 ?

**Comment by claudiosmweb** [comment]
@ramiy yes.
@mikejolley I see no problem to merge this last Pull Request.

**Comment by mikejolley** [comment]
See #12058
