### ISSUE TITLE
URL Rewrite on product category AND filter color issue.

### ISSUE THREAD

**Issue by AurelienBarbier** [woocommerce/woocommerce#11929]
## EXPLANATION OF THE ISSUE

If you have an url like : 
http://domain.com/product-category/watches-for-men/

when you try to filter by color, you are redirected on shop page, with color filter but you loose your product_cat filter like : 
http://domain.com/shop/?min_price=21&max_price=811&filter_color=black-2

## Possible reason.
I have a look in WC_Widget_Layered_Nav class and in get_page_base_url there are a serie of test to retrieve the current url.

In my case, I should enter in this test : elseif ( is_product_category() ) {
but i can't cause of the test juste before : elseif ( is_post_type_archive( 'product' ) || is_page( wc_get_page_id( 'shop' ) ) ) .
is that it should not be a AND and not a OR ?

Or the two test should not be reverse ?

**Comment by mikejolley** [comment]
Tested locally and didn't have the same issue. Something must be messing with your conditionals (plugin or theme). The shop page IS NOT a category archive. It is correct to be OR.

For me it just appends like this:

`
http://local.wordpress.dev/product-category/clothing/hoodies/?filter_color=blue&query_type_color=or
`
