### ISSUE TITLE
WooCommerce Function to be able to define the correct filters for single and variable in add to cart

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce#11936]
So in the current add to cart template only woocommerce_product_add_to_cart_url is applied as the filter.
But it you use woocommerce_variable_add_to_cart as the applied filter then you can display product variations by dropdown, granted this is of use when you have a low product level and not very many product variations, so a user can select the variation from shop instead of single page.

https://docs.woocommerce.com/wc-apidocs/source-class-WC_Product_Simple.html#31-40
https://docs.woocommerce.com/wc-apidocs/source-class-WC_Product_Variable.html#36-46

So there should be a function can be used so if a store has a mix of single and variable products, then woocommerce_variable_add_to_cart filter will be used on variable products but woocommerce_product_add_to_cart_url  will be used on single products all within the shop loop.

I think a function which could be defined would help a lot of user with this issue.

**Comment by mikejolley** [comment]
I'm not 100% certain what you're asking for here, but if you're using any of those filters you're passed the product object (`$this`) so it's not difficult to identify the product type in your own function. New filters are not needed for each type.
