### ISSUE TITLE
Success message even if there are errors in WC_Integration

### ISSUE THREAD

**Issue by Dartui** [woocommerce/woocommerce#11952]
## EXPLANATION OF THE ISSUE
I have created my own Integration for WooCommerce and I am triyng to handle errors (for example when API Key for application is bad). My Integration class is based on [this tutorial](https://docs.woocommerce.com/document/implementing-wc-integration/), but no error messages are shown. I discovered, that `display_errors` method is never used, and is hard to find hook after validation (dynamic method: `validate_api_key_field`). To display messages I overrided `admin_option` method by this one:
```
public function admin_options() {
	$this->display_errors();
	echo '<table class="form-table">' . $this->generate_settings_html( $this->get_form_fields(), false ) . '</table>';
}
```
This is working like a charm, but all the time I have got message `Your settings have been saved`, because of this part of code in `class-wc-admin-settings.php`:
```
public static function save() {
	...
	self::add_message( __( 'Your settings have been saved.', 'woocommerce' ) );
	...
}
``` 
 `messages` property is private, so I cannot delete this message. Any suggestions?

**Comment by claudiosmweb** [comment]
Works just fine but the tutorial is outdated.

You can change:

```php
/**
 * Validate the API key
 * @see validate_settings_fields()
 */
public function validate_api_key_field( $key ) {
	// get the posted value
	$value = $_POST[ $this->plugin_id . $this->id . '_' . $key ];

	// check if the API key is longer than 20 characters. Our imaginary API doesn't create keys that large so something must be wrong. Throw an error which will prevent the user from saving.
	if ( isset( $value ) &&
		 20 < strlen( $value ) ) {
		$this->errors[] = $key;
	}
	return $value;
}
```

To:

```php
public function validate_api_key_field( $key, $value ) {
	if ( isset( $value ) && 20 < strlen( $value ) ) {
		WC_Admin_Settings::add_error( sprintf( esc_html__( 'Looks like you made a mistake with the API Key field. Make sure it isn&apos;t longer than 20 characters', 'woocommerce-integration-demo' ) ) );
	}

	return $value;
}
```
