### ISSUE TITLE
(2.6.4) Layered Nav filtering with an attribute & OR works with a list layout, but is broken with a dropdown option

### ISSUE THREAD

**Issue by RicaNeaga** [woocommerce/woocommerce#11970]
## EXPLANATION OF THE ISSUE

I try to use a filter widget in the sidebar, latest 2.6.4 build and everything else up to date (three different websites with different configuration), with the OR and dropdown menu for the attribute.

OR is working like AND when using a dropdown menu, but if using a list, I can use multiple filters from that attribute. So OR option is working with the list display option, but is broken with the dropdown display option.
## STEPS TO REPRODUCE THE ISSUE

See above :)
## SYSTEM STATUS REPORT

```
Don't think it's necessary - I've reproduced it in at least threee installations, so you can easily reproduce it. If not, I'll come back with a system report
```

**Comment by mikejolley** [comment]
It's not 'broken' per se, this is simply a limitation of dropdowns. You cannot select multiple items within that type of input. Lists of checkboxes are more flexible here for this use case.

Multi-selects could be used instead, but they introduce their own UX issues (without scripts like Chosen/SELECT2) and that would not be a dropdown field anyway :)

**Comment by mikejolley** [comment]
@jameskoster hide the query type option in this case, or use a different input type?

**Comment by jameskoster** [comment]
A multi-select is essentially the same thing as a list so doesn't seem to fit. 

How about after you've made a selection a new dropdown is added with a label "Or" or "And" based on the filter type.

![layered-nav](https://cldup.com/xOLI3S3nkx-2000x2000.png)

**Comment by RicaNeaga** [comment]
Thank you very much for considering to solve this. I agree, something that looks similar to a dropdown is also needed for the OR option.

The reason is that some stores have many options for a filter, so it's better to hide all of them by default., and the customer to choose only the ones that are needed.

Also, for the previous reply, **if an option (blue) is chosen, can there be shown only the other filters for the OR options?** For that example, ''any color'' and ''blue'' options are redundant, only ''orange'' and ''red'' I think should be offered as alternatives.

Thank you again.

**Comment by jameskoster** [comment]
> Also, for the previous reply, if an option (blue) is chosen, can there be shown only the other filters for the OR options? For that example, ''any color'' and ''blue'' options are redundant, only ''orange'' and ''red'' I think should be offered as alternatives.

Totally agree. That screenshot was just a quick mockup in the Inspector xD

**Comment by mikejolley** [comment]
@jameskoster This still feels like an odd clunky solution to me vs the lists. Why do we need to support dropdowns for OR? Dropdowns are not suitable IMO.

**Comment by jameskoster** [comment]
> Why do we need to support dropdowns for OR?

We don't need to. I agree they're not a good fit for this use case. We can remove it, so long as there's an explanation and it doesn't just vanish. Something like;

![dropdown](https://cldup.com/GRVUPqzB9s-3000x3000.png)

**Comment by RicaNeaga** [comment]
My clients (website owners), that sell products with attributes and want advanced filters, almost all expressed their need for this.

Also, I saw this ticket was also requested by many other people here in the past (you've answered almost everytime it's not a bug, it's as designed). So the need is there and very real.

If it's so hard to implement, and you don't want to, then that's that. But it would be a pity... aka install other plugins that do this kind of filtering by default.

**Comment by mikejolley** [comment]
@RicaNeaga Use a list - the functionality exists. Why force a dropdown on people.

**Comment by jameskoster** [comment]
If there's a large amount of attributes / terms the list(s) could be very long / ugly. 

Sure, you can fix that with CSS, but I'm guessing that's the main reason folks will opt for dropdowns.

**Comment by mikejolley** [comment]
And dropdowns allow 1 selection :) So that should be known/accepted. 

We can use select2 here though instead and it would be much easier to implement..

**Comment by mikejolley** [comment]
Replaced with https://github.com/woocommerce/woocommerce/issues/13189
