### ISSUE TITLE
Allow custom sort order when applying coupon to a limited amount of products

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#11973]
When creating a coupon we can use the following limitation: `Limit usage to X items`

This can be useful if we want to give 1 free product (100% product discount coupon), and limit the coupon to be applied to a specific category or list of products.

To reproduce this I created a coupon with the following settings:
Discount type: Product % Discount
Coupon amount: 100
Usage Restriction > Products: List of three specific products
Usage Limits > Limit usage to X items: 1

When I use this coupon and add several products from the list, the coupon is applied to the most expensive product. In my scenario I would like the coupon to be applied to the cheapest product.

In the cart the following code is applied before calculating the discounted prices:

```
// Order cart items by price so coupon logic is 'fair' for customers and not based on order added to cart.
uasort( $cart, array( $this, 'sort_by_subtotal' ) );
```

The `sort_by_subtotal` function sorts the cart items from highest to lowest and doesn't seem to offer any way to override the sorting method.

I have tried manually changing the sort order in the code and this seems to work correctly. The coupon is applied to the cheapest product. Would this sort order be something which should be customizable using a filter? Or is there something else which could cause calculations to go wrong if this sort order is customized?

**Comment by mikejolley** [comment]
Cannot be customised.
