### ISSUE TITLE
Different Tax Rates with the same tax name mess up

### ISSUE THREAD

**Issue by apermo** [woocommerce/woocommerce#11976]
## EXPLANATION OF THE ISSUE

I had 2 different tax rates, a standard 19% and a reduced 9%.
As both are labeled MwSt in short according to german law, and I had the numbers given in the frontend I had given both the same label.
This leads to the issue that WC()->cart->calculate_totals() will put both taxes into the same sum.
Leading to an incorrect cart, checkout and so on.

## STEPS TO REPRODUCE THE ISSUE

1. Create a standard Tax with tax-name 'test'
2. Create a reduced tax with tax-name 'test'
3. create two products, each with one of the corresponding tax-rates
4. put both into the cart.

Was tested on a fresh install with latest WordPress and WooCommerce and no other Plugins.

**Comment by mikejolley** [comment]
Tax rate totals with the same name are merged. If you want them displayed on separate lines just append the rate to the name, e.g. `MwSt (9%)`. This will stop them being merged.

**Comment by danielhuesken** [comment]
@mikejolley I think that is not good. When adding the percentage to the name it will be displayed twice. In the name an bevor the name. The there a reason, why they will be merged by name? And what for a percentage did i have than?

**Comment by apermo** [comment]
The sum will be correct, the displayed tax rate depends on which tax rate is first/last in the cart. 

Yet I agree with Daniel, if there are technical reasons, why not add a warning if someone adds same labels for different rates.

**Comment by mikejolley** [comment]
@danielhuesken No it won't. We don't display the actual % on the frontend. 

@apermo I don't think thats right either. If you have 2 tax rates active for your cart, you'll get 2 lines. e.g. using the name I suggested you'd get:

Subtotal: X
MwSt (19%): X
MwSt (9%): X
etc...

**Comment by apermo** [comment]
That is only true if the two rates have distinct labels.

If both have the label "MwSt" without the numbers. It will display the sum in one row. 
As most themes especially the ones specialized for the German market display it like "Label (rate%)" it will display a summed tax rate with a single tax rate and label. 

Give it a try, i reproduced it when I tried to figure out it happened. At least a warning would have saved me hours

**Comment by mikejolley** [comment]
Right that's what I suggested. Core does not show percent by default - see if it can be disabled in your plugin?

**Comment by mikejolley** [comment]
It's merged by name so you can have a single line if desired, if for instance you have rates across different tax classes.
