### ISSUE TITLE
REST API docs link in README.md leads to a 404 Not Found

### ISSUE THREAD

**Issue by tcort** [woocommerce/woocommerce#11982]
## EXPLANATION OF THE ISSUE

I can't access the REST API documentation. I get "404 There isn't a GitHub Pages site here." All of the Google results for the REST API docs lead to the same place.

## STEPS TO REPRODUCE THE ISSUE

1. Visit https://github.com/woocommerce/woocommerce#documentation
2. Click [WooCommerce REST API Docs](https://woothemes.github.io/woocommerce-rest-api-docs/)

## SYSTEM STATUS REPORT

I'm not running WooCommerce. I just want to look at the REST API documentation.

**Comment by claudiosmweb** [comment]
We just renamed https://woocommerce.github.io/woocommerce-rest-api-docs/
