### ISSUE TITLE
Coupon Issues with 2.7

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#11988]
I ran into some issues with 2.7 (that are NOT present in 2.6.4) with coupon codes. Most definitely related to all of the CRUD and core changes (though I swear these all worked when testing those..)

Two issues I've noticed so far:

* If you don't set a date in wp-admin, `1970-01-01` is prefilled as the coupon date.
* Product % and Product Amount doesn't seem to apply. The coupon gets "applied" (shows up on the cart) but it doesn't subtract any value. 

There might be others.. so in addition to fixing these, we should make sure everything works as it should.

**Comment by willhives** [comment]
Morning Justin,

Does this issue encompass the issue we have been experiencing?
https://github.com/woocommerce/woocommerce/issues/11984

Cheers Will

**Comment by justinshreve** [comment]
@willhives Nope - separate issue on code that hasn't been released yet :).
