### ISSUE TITLE
New Attributes not selectable in Variations

### ISSUE THREAD

**Issue by iannich** [woocommerce/woocommerce#11983]
## EXPLANATION OF THE ISSUE

Woocommerce 2.6.4
WordPress 4.5.4
Storefront Version: 2.0.4 (+ my own Child Theme)

I think I have found a bug when adding a new Attribute Variation to woocommerce products.

The issue appeared when trying to add a new Attribute (defined in Woocommerce / attributes) to existing products. If I carry out the following steps:

## STEPS TO REPRODUCE THE ISSUE

- Add the new Global Attribute (height) on the product's Attributes tab
- Check "Use for Variations"
- Check "view on product page" (Not required for my purposes but will discuss below)
- Select all values
- Click "save attributes"
- Navigate to Variations tab
- Confirm that the new Attributes were added to existing variations with value "any Height"
- Click "update" button under WP Publish panel 

When I view the product on the front end the new attribute select fields are present but do not have any options (other than "choose an option")

If i view the "additional Information" section under the product, I can see the list of available options that should appear in the select element. The woocommerce "view on product page" option allows me to see that the information is being saved, at least somewhere.

In order to force the options to appear I need to:

- navigate to the product's Variations tab
- Make and then undo a change within a variation. (This enables the "Save Changes" button)
- Click the "Save Changes" button

The options now appear in the select field for the product.

Hope I have been clear enough with my description?

Regards, Ian.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by justinshreve** [comment]
Confirmed, thanks. I just saw the same thing following your steps.

It seems like selecting "Used for variations" and clicking save attributes should go ahead and save the "Any <Attribute>" option as well.. I think right now the UI just gets updated but the 'any' choice isn't saved.
