### ISSUE TITLE
Translations in german partly not working since update to WooCommerce 2.6.4

### ISSUE THREAD

**Issue by ad-on-is** [woocommerce/woocommerce#11989]
Hi,

since updating to WooCommerce 2.6.4 some translations are not working.
The first sentence of the registration confirmation email is not translated tough everything else is.

![image](https://cloud.githubusercontent.com/assets/9553253/18972613/3ab9a08a-869a-11e6-8064-13fa1dbe4ca4.png)

What I found out so far is:

/wp-content/plugins/woocommerce-de_DE.po looks correct

```
#: templates/emails/customer-new-account.php:27
#: templates/emails/plain/customer-new-account.php:25
msgid "Thanks for creating an account on %s. Your username is <strong>%s</strong>"
msgstr "Danke, dass du ein Konto bei %s erstellt hast. Dein Benutzername ist <strong>%s</strong>"
```

wp-content/themes/mytheme/woocommerce/emails/customer-new-account.php also looks good.
```
<p><?php printf( __( "Thanks for creating an account on %s. Your username is <strong>%s</strong>.", 'woocommerce' ), esc_html( $blogname ), esc_html( $user_login ) ); ?></p>
```

If I try to put the printf()-line somewhere in my theme, I also get only the english string and not the german one.

**Comment by opportus** [comment]
Hi @ad-on-is 

The translatable string in your template is missing the final dot '**.**'.

**Comment by ad-on-is** [comment]
@opportus Thanks man.

The dot was removed in the woocommerce-de_DE.po-file.

**Comment by opportus** [comment]
And in the last WC release, just update your template :)
