### ISSUE TITLE
Improve checkout configuration page

### ISSUE THREAD

**Issue by scrobbleme** [woocommerce/woocommerce#11987]
## EXPLANATION OF THE ISSUE

When using multiple payment provider plugins, the settings page menu get's a little overloaded.

For instance: I need PayPal Express and am using the [PayPal for WooCommerce](https://de.wordpress.org/plugins/paypal-for-woocommerce/) plugin. This plugins offers many PayPal methods I never use.

## STEPS TO REPRODUCE THE ISSUE

Install [PayPal for WooCommerce](https://de.wordpress.org/plugins/paypal-for-woocommerce/)

## My suggestion

Refactor the page like this:

- add a edit link to the overview pages list (where it is also possible to sort the payment methods)
  - I know, it is already possible to click the title there, but an explizit link would be more obvious
- in the menu only show links to enabled methods.

![image](https://cloud.githubusercontent.com/assets/504835/18947275/ad0d49a6-8632-11e6-89a9-2e3a64b946ab.png)

**Comment by claudiosmweb** [comment]
You can disable what you not using.
And we are already improving this interface for next versions.
