### ISSUE TITLE
wp_woocommerce_sessions table missing

### ISSUE THREAD

**Issue by IDzOR** [woocommerce/woocommerce#11999]
## EXPLANATION OF THE ISSUE

Once you are using "SQLite Integration" plugin (I am using version 1.8.1) for SQLite database, one and only wp_woocommerce_sessions table is not created within WooCommerce installation. Installation into MySQL database is proceeded as expected.
If the wp_woocommerce_sessions table is missing it is affecting features such as Coupons subtraction.
Message shows coupon is "applied" (shows up on the cart) but it doesn't subtract any value. 
Once I added wp_woocommerce_sessions table manually into SQLite database, functions are working like a charm.

I've tried 2.6.4 version automatic installation, and 2.6.3 manual plugin addition, but no success

## STEPS TO REPRODUCE THE ISSUE

1. SQLite Integration manually incorporated into WP
2. WP installation.
3. WooCommerce plugin installation

**Comment by IDzOR** [comment]
I found out where the issue is and I'm asking you for the fix.

Problem is in the file "class-wc-install.php" row 435 & 436.
You need to request creation of PRIMARY KEY just before UNIQUE KEY.

Create table request should look like piece I added down below.
I have tested it and it's working fine now.

Thanks.

CREATE TABLE {$wpdb->prefix}woocommerce_sessions (
  session_id bigint(20) NOT NULL AUTO_INCREMENT,
  session_key char(32) NOT NULL,
  session_value longtext NOT NULL,
  session_expiry bigint(20) NOT NULL,
  PRIMARY KEY  (session_key),
  UNIQUE KEY session_id (session_id)
) $collate;

**Comment by justinshreve** [comment]
Even though we don't support SQLite out of the box, this seems like an easy enough fix to make. Thanks for posting a solution.

**Comment by chrislam** [comment]
Hi,

I too am using SQLite Integration 1.8.1 with WooCommerce 2.6.8 but I'm still having issues with this sessions table.

My investigations found that SQLite will make the column marked `autoincrement` also the primary key. SQLite Integration enforces this in it's translation layer to improve compatibility but the end result is that multiple sessions are created, confusing WooCommerce.

I have tried removing this column (and its associated `UNIQUE KEY`) to properly restore the `PRIMARY KEY` to the `session_key` column with success in resolving my issues and without any apparent side effects.

If the `session_id` column is not being used anywhere, would you consider removing it?

The updated statement would be:
```
CREATE TABLE {$wpdb->prefix}woocommerce_sessions (
  session_key char(32) NOT NULL,
  session_value longtext NOT NULL,
  session_expiry bigint(20) NOT NULL,
  PRIMARY KEY (session_key)
) $collate;
```
