### ISSUE TITLE
Variations/Swatches are displaying all variations instead of only the ones that are available

### ISSUE THREAD

**Issue by mariannag7282** [woocommerce/woocommerce#11993]
I created a product with a "Base Color" and an "Accent Color".  I set up all the available variations. eI am using the swatches plugin to display the actual colors.   When a base color and an accent color combination is selected that doesn't exist, I get an error "Sorry, no products matched your selection. Please choose a different combination."   Instead I would like it to NOT display the Accent Colors that aren't available.  

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiosmweb** [comment]
We don't have Swatches on WooCommerce core.
If you are using the "WooCommerce Variation Swatches and Photos" plugin, you should contact the plugin support in https://woocommerce.com/my-account/create-a-ticket/

**Comment by mariannag7282** [comment]
I see that an issue with Variation/Swatches was addressed here https://github.com/woocommerce/woocommerce/issues/10272

**Comment by claudiosmweb** [comment]
@mariannag7282 here is only for WooCommerce core issues, so please open a ticket on the WooCommerce support.

**Comment by mariannag7282** [comment]
Would you please link me to that page?

**Comment by claudiosmweb** [comment]
@mariannag7282 https://woocommerce.com/my-account/create-a-ticket/
