### ISSUE TITLE
Webhook (order.created) works like a cron

### ISSUE THREAD

**Issue by royzer** [woocommerce/woocommerce#11991]
## EXPLANATION OF THE ISSUE

When orders are placed, the 'Create Order' webhook is not fired immediately. There is a delay of 10 to 120 minutes, and webhooks for the orders placed in that time period are fired simultaneously.

## STEPS TO REPRODUCE THE ISSUE

1. In Settings -> API -> Webhooks, create a new Webhook with the options (Topic = Order Created, status=Active)
2. Click on 'Save Webhook' and make sure the save is success fl (should get 'Webhook Activated' message at the top of screen)
3. Make an order.

Expected : Webhook should be fired immediately
Actual : The webhook is fired, in batch, after a delay

Searched the existing tickets - could not find any other instance of this same issue. Kindly excuse if this is a duplicate.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://www.mobiefit.com/store
Site URL: http://www.mobiefit.com/store
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.17 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: N/A
SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (32) ###

Templatemela Custom Post: by Templatemela – 1.0
Templatemela Meta Box: by Templatemela – 1.0
Templatemela Shortcode: by Templatemela – 1.0
WooCommerce Advanced Notifications: by WooThemes – 1.1.19
WooCommerce Ship to Multiple Addresses: by 75nineteen Media LLC – 3.3.12
Akismet: by Automattic – 3.2
Black Studio TinyMCE Widget: by Black Studio – 2.2.12
Color and Image Swatches for Variable Product Attributes: by Phoeniixx – 1.2.1
Contact Form DB: by Michael Simpson – 2.10.24
Contact Form 7: by Takayuki Miyoshi – 4.5.1
Duplicator: by LifeInTheGrid – 1.1.16
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.18
Jetpack by WordPress.com: by Automattic – 4.3.1
Newsletter: by Stefano Lissa & The Newsletter Team – 4.6.0
WooCommerce paytm gateway: by Varun – 0.1
Slider Revolution: by ThemePunch – 5.1.3
Page Builder by SiteOrigin: by SiteOrigin – 2.4.16
WC Custom Thank You: by Nicola Mustone – 1.0.0
Widget Logic: by Alan Trewartha – 0.57
WooCommerce Grid / List toggle: by jameskoster – 1.0.0
WooCommerce PayU India (PayUmoney & PayUbiz): by _KDC-Labs – 2.0.10
WooCommerce: by WooThemes – 2.6.4
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.1
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 3.6
WP Custom CSS: by Johnibom – 1.1
WP htaccess Control: by António Andrade – 3.5.1
WP-Mail-SMTP: by Callum Macdonald – 0.9.5
YITH WooCommerce Quick View: by YITHEMES – 1.1.2
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.21

### Settings ###

Force SSL: –
Currency: INR (₹)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page ID is set
but the page does not exist

Cart: #8 - /index.php/cart/
Checkout: #9 - /index.php/checkout/
My Account: #10 - /index.php/my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: WCM010024-homedecor
Version: 1.0
Author URL: http://www.templatemela.com
Child Theme: ✔
Parent Theme Name: harveststore
Parent Theme Version: 2.1
Parent Theme Author URL: http://www.templatemela.com
WooCommerce Support: ✔

### Templates ###

Overrides: harveststore/woocommerce/archive-product.php
harveststore/woocommerce/content-product.php
harveststore/woocommerce/global/wrapper-start.php
harveststore/woocommerce/single-product.php

`

**Comment by claudiosmweb** [comment]
Because it uses cron to fire things in background.
All webhooks uses cron.

**Comment by royzer** [comment]
@claudiosmweb : Thanks for the clarification. I'd raised this because it behaved differently when I ran it on my local system (fired instantaneously), than the server in EC2. I might have missed something.

**Comment by johnknoop** [comment]
This is really unfortunate. E-mail notifications are sent right away, so one can't help but wonder how hard it could be to implement delivery of webhooks without much delay.

**Comment by claudiosanches** [comment]
@johnknoop email notification don't use cron, will start use in 3.0.
