### ISSUE TITLE
[API v1] Accessing meta data, limit, pagination

### ISSUE THREAD

**Issue by amjad0** [woocommerce/woocommerce#11996]
1. With the legacy v3, I was able to access custom fields using the parameter **filter[meta]=true**. With the new v1, this does not work. What is the change to be done here? 

2. Also with legacy v3, I was able to pull all products, categories, orders, etc with parameter **filter[limit]=-1**. With the new v1, I can see in the docs that we need to use per_page. However this only has a limit of 100. How can I make this fetch everything? 

3. Pagination - According to the documentation: Requests that return multiple items will be paginated to 10 items by default. **_This default can be changed by the site administrator by changing the posts_per_page option._** Alternatively the items per page can be specified with the ?per_page parameter. 

Where and how can I change the post_per_page option?

**Comment by justinshreve** [comment]
> I was able to access custom fields using the parameter filter[meta]=true. With the new v1, this does not work. What is the change to be done here?

You can filter for specific values using `?filter[meta_key]=_hello&filter[meta_value]=world`. This is in the format of WP_Query. However we are not returning meta values / fields on the API. Depending on the use case, it might make sense for a new endpoint. https://github.com/WP-API/wp-api-meta-endpoints might be useful too -- but I have not tested it or used it with things like products.

> However this only has a limit of 100. How can I make this fetch everything?

There is no way to fetch more than 100 products. WP-API caps it (see code link below). Your script should be able to loop through and use the pagination to get all the products.

> Where and how can I change the post_per_page option?

That setting is under Settings > Reading (`/wp-admin/options-reading.php`) -- however it looks like our docs our wrong, and you can only override the setting by using `?per_page`. The default is pulled from WP-API (https://github.com/WP-API/WP-API/blob/4d523098062f8ccd5ca5d6bb12e246fc77de0db3/lib/endpoints/class-wp-rest-controller.php#L255). cc @claudiosmweb we should update the docs -- WP-API does not use that setting.

**Comment by amjad0** [comment]
@justinshreve So basically, the new API has a lot of limitations now because of this. The v3 was much much better being able to access meta fields for products / orders as such. I hope you do not phase v3 out.

**Comment by indextwo** [comment]
I haven't gotten as far as dealing with pagination, although adding a standard `posts_per_page` parameter (the same as a regular `WP_Query`) helped (in my case I was using the [PHP API wrapper](https://github.com/woocommerce/wc-api-php) ).

With regards to meta: I needed to be able to grab a _ton_ of meta information that had been added to orders (regardless of value, so filtering by specific keys and values didn't help, because it still didn't actually _output_ those meta fields); but couldn't find any way of doing this with the new v1 API. In trying to cobble something together with the WP REST API, I realised I could use `register_rest_field` with the WC API to add as many meta fields to the response as I needed:
	
	function vnmWooExtend_apiAddFields() {
		
		//	Array of post_meta fields to retrieve
		
		$customMetaArray = array(
			'order-reason',
			'custom-meta-1',
			'custom-meta-2',
			'custom-meta-3',
			//	etc.
		);
		
		foreach($customMetaArray as $customMeta) {
			register_rest_field('shop_order',	//	Post type
				$customMeta,	//	post_meta key
				array(
					'get_callback'		=> 'vnmWooExtend_apiGetMetaField',
					'update_callback'	=> null,
					'schema'			=> null,
				)
			);
		}
	}
	
	add_action('rest_api_init', 'vnmWooExtend_apiAddFields');
	
	//	Function to return meta fields
	
	function vnmWooExtend_apiGetMetaField($object, $field_name, $request) {
		
		//	$object = Post object
		//	$field_name = Name of field
		//	$request  = WP_REST_Request
		
		return get_post_meta($object['id'], $field_name, true);
	}

**Comment by amjad0** [comment]
That's one way. I still wish it was as easy as using a filter to fetch all meta and be able to add meta back to the orders via the API. I will continue to use v3 for now.

**Comment by mathieug** [comment]
@amjad0 How do you switch from new v1 to legacy v3? Thanks.

**Comment by amjad0** [comment]
Not having direct read/write access to an order's or product's custom fields is a big drawback of the new API v1.

**Comment by larssn** [comment]
@justinshreve You **can** get more than 100 elements from WP REST like so:
`/wc/v1/orders?filter[posts_per_page]=-1`

**Comment by claudiosanches** [comment]
@larssn `filter` is deprecated and will be removed soon.

**Comment by amjad0** [comment]
what is alternate to filter?

**Comment by claudiosanches** [comment]
None.

**Comment by amjad0** [comment]
So how are we supposed to perform those API calls that require filter now?

**Comment by claudiosanches** [comment]
@amjad0 Good questions, but will be removed because WP-API is removing too.

**Comment by amjad0** [comment]
So no more filters in v3 api?

**Comment by amjad0** [comment]
@claudiosanches So will you remove filters in v3 legacy API?

**Comment by larssn** [comment]
@claudiosanches I hope you aren't planning on making this change to the /wc/v1/ endpoint, because that would be a huge breaking change.

If you want to remove filter, it must be removed in /wc/v2/ instead.

**Comment by amjad0** [comment]
I agree, please don't remove filters.

**Comment by justinshreve** [comment]
@amjad0 No they won't be removed from `/wc-api/v3/` or any other legacy endpoint. @claudiosanches was talking about `/wc-json/wc/v1`, which is powered by WP-API. 

However, @claudiosanches -- I don't think we should remove filter from our already released API. @larssn is correct. This is a filter present in a public API that we documented. We should never remove anything from the APIs without versioning. We need to shim around it if WP-API is dropping the code for it, and add it to the list to drop in v2 of the WP-API powered API.

**Comment by claudiosanches** [comment]
@justinshreve not removed, starting as deprecated, since WordPress does the same.

**Comment by Magnetize** [comment]
Hello!
So, I was looking through the code and found that it should be possible to update order custom meta fields by looking at line 1055 in 'class-wc-rest-orders-controller'.
However, I am using a .NET-wrapper that itself does not support this due to meta_data not being mentioned in the API docs, but if I rewrote it, it would be possible, correct?
