### ISSUE TITLE
Downloadable Products: add order_item_id to database table

### ISSUE THREAD

**Issue by tohvanah** [woocommerce/woocommerce#11998]
Having a reference to the order item for downloadable product entries would allow for access to specific metadata increasing the ability to customize the downloadable products.

**Comment by mikejolley** [comment]
Core doesn't have a use case for this one so I don't think we'll add it. It would be possible without a core table change though to track this data elsewhere. You have the download_id and can map extra data to that through your own meta table or option.

**Comment by tohvanah** [comment]
The download_id is not unique to each purchase, just to each file/product combination.

My use case involves meta data attached to the order item, allowing the sale of thousands of photograph downloads with only 1-3 WooCommerce products.

**Comment by mikejolley** [comment]
Yes, but you can store the download_id <> order item link elsewhere when the download is generated via the hooks no?

**Comment by tohvanah** [comment]
Because download_id is not unique, that link is fairly useless. Modifying the download_id on commit causes it to be omitted by later calls. Using the table index "permission_id" could be ok, but these can be lost during admin updates to the downloadable products.
