### ISSUE TITLE
Change sidebar position on DOM HTML tree

### ISSUE THREAD

**Issue by joaosaragossa** [woocommerce/woocommerce#12007]
## EXPLANATION OF THE ISSUE

I'm working on integration of WooCommerce with my Wordpress theme through the [hook method](https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/#section-2). Here the snipet of the hook on my `functions.php` file:

```
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10);
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10);

add_action('woocommerce_before_main_content', 'cardfight_wrapper_start', 10);
add_action('woocommerce_after_main_content', 'cardfight_wrapper_end', 10);

function cardfight_wrapper_start() {
  echo '<main id="main" class="wrapper clearfix"><section class="clearfix products-list">';
}

function cardfight_wrapper_end() {
  echo '</section></main>';
}
```

My `page.php`, witch I suppose is used as a template to the hook action:

```
<?php get_header(); ?>
<main id="main" class="wrapper clearfix">
  <section class="clearfix">
  </section>
</main>
<?php get_footer(); ?>
```

From what I understand, the hook looks for this markup and output the WC content inside the `<section>`.
In the HTML output, my sidebar is placed after the `<main>` tag:

![image](https://cloud.githubusercontent.com/assets/6151234/19056992/2686331a-89a3-11e6-9b3d-79cd7557a25b.png)

But I need that this sidebar be after the `<section>` inside `<main>`, like this:

![image](https://cloud.githubusercontent.com/assets/6151234/19057135/28225176-89a4-11e6-8b94-5fc09ad79309.png)

Taking into account that I am not working in a WC child theme, how can I place my sidebar where I want?

**Comment by claudiosmweb** [comment]
I don't see any issue here.
Looks like you are looking for support.

>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://woocommerce.com/my-account/tickets/ for premium plugin support
