### ISSUE TITLE
highest number not visible

### ISSUE THREAD

**Issue by zegenrijk** [woocommerce/woocommerce#12003]
Hello,

See this report here: https://wordpress.org/support/topic/highest-number-not-visible/

The developer said it's from the core of Woocommerce.

Regards Michel

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/11933

**Comment by zegenrijk** [comment]
Ok, you a refering to 11933, but that ticket is closed too. Is there taken any action to solve?

Regards Michel

**Comment by mikejolley** [comment]
There was a patch. Next release.
