### ISSUE TITLE
Unable to override single-product-review.php 

### ISSUE THREAD

**Issue by ashbryant** [woocommerce/woocommerce#12009]
## EXPLANATION OF THE ISSUE

Copying single-product-review.php  to theme templates directory does not override the file. All changes are ignored.

## STEPS TO REPRODUCE THE ISSUE

Copy single-product-review.php to theme directory (as with all other override files that do work)

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://localhost/allgood
Site URL: http://localhost/allgood
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.12 (Unix) PHP/5.6.9 mod_wsgi/3.5 Python/2.7.9 OpenSSL/1.0.1j
PHP Version: 5.6.9
PHP Post Max Size: 1 GB
PHP Time Limit: 900
PHP Max Input Vars: 10000
cURL Version: 7.35.0
OpenSSL/1.0.1j

SUHOSIN Installed: –
MySQL Version: 5.6.24
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (54) ###

Gravity Forms: by rocketgenius – 2.0.7
Advanced Custom Fields: Dynamic Table Field: by Geet Jacobs – 1.0.1
Advanced Custom Fields: Divider: by Kreshnik Hasanaj – 1.0.0
ACF Accordion: by Bogdan Dragomir – 1.1.1
Advanced Custom Fields: Button: by Matt Cromwell – 1.0.0
Advanced Custom Fields: Field Selector: by Daniel Pataki – 4.0.0
ACF Fold Flexible Content: by Urban Sanden – 1.4.1
Advanced Custom Fields: Hidden Field: by erictr1ck – 1.0.0
Advanced Custom Fields: Image Crop Add-on: by Anders Thorborg – 1.4.9
Advanced Custom Fields: PayPal Field: by Michael Rodriguez – 2.0.0
Admin Color Schemes: by WordPress Core Team – 2.2
Advanced Custom Fields Repeater Collapser: by Mark Root-Wiley – 1.4.3
Advanced Custom Fields: Code Area: by Taylor Mitchell-St.Joseph – 1.0.1
Advanced Custom Fields: Component Field: by Alan Chen – 1.0.11
Advanced Custom Fields: Field Snitch: by Stupid Studio – 1.0.3
Advanced Custom Fields: Font Awesome: by Matt Keys – 1.7.2
Advanced Custom Fields: Leaflet Field: by Jens Nilsson – 1.2.1
Advanced Custom Fields: Limiter: by Atomic Smash - David Darke – 1.1.1
Advanced Custom Fields: Nav Menu Field: by Faison Zutavern – 2.0.0
Advanced Custom Fields: Number Slider: by Q Studio – 0.4.2
Advanced Custom Fields PRO: by Elliot Condon – 5.4.6
Advanced Custom Fields: Table Field: by Johann Heyne – 1.1.13
Advanced Custom Fields Viewer: by Joseph Fusco – 1.2.1
Advanced Custom Fields: Widget Area Field: by Dustin Filippini – 1.0.0
Advanced Custom Fields: Widget: by Direct Basing – 1.0.2
Advanced Custom Fields: Auto-generated value: by Kindly – 1.0.0
Beautiful taxonomy filter: by Jonathan de Jong – 2.1.0
Admin Columns: by AdminColumns.com – 2.5.6.3
Custom Post Type UI: by WebDevStudios – 1.4.2
Enable Media Replace: by Måns Jonasson – 3.0.4
Gravity Forms Campaign Monitor Add-On: by rocketgenius – 3.4.1
Gravity Forms Signature Add-On: by Rocketgenius – 3.2
Gravity Forms User Registration Add-On: by rocketgenius – 3.4
Jetpack by WordPress.com: by Automattic – 4.3.1
ACF QuickEdit Fields: by Jörn Lund – 1.0.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Soil: by Roots – 3.7.0
HTML5 Boilerplate .htaccess: by Roots –
Simple Custom Post Order: by Sameer Humagain – 2.3
Simple Image Sizes: by Rahe – 3.1.1
Slash Edit: by ronalfy – 1.1.1
Advanced Custom Fields: Gravity Forms Field: by @adam_pope of @stormuk – 1.1.0
Advanced Custom Fields: Reusable Field Group: by Tyler Bruffy – 1.0.2
User Switching: by John Blackbourn – 1.0.9
WooCommerce Grid / List toggle: by jameskoster – 1.0.0
WooCommerce Sequential Order Numbers: by SkyVerge – 1.7.0
WooCommerce: by WooThemes – 2.6.4
WooSidebars: by WooThemes – 1.4.3
WooThemes Helper: by WooThemes – 1.3.0
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 3.6.1
WP All Import Pro: by Soflyy – 4.3.2
WPFront User Role Editor: by Syam Mohan – 2.12.4
Yoast SEO: ACF Analysis: by Marcus Forsberg & Team Yoast – 1.2.0

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Starter Theme 2016
Version: 9.0.0
Author URL: http://c9dd.com/ash
Child Theme: ✔
Parent Theme Name: Starter Theme 2016
Parent Theme Version: 9.0.0
Parent Theme Author URL: http://c9dd.com/ash
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by claudiosmweb** [comment]
> Copying single-product-review.php to theme templates directory does not override the file. All changes are ignored.

Test and works just fine.
But the "theme templates directory" need to be called as "woocommerce".
