### ISSUE TITLE
Woocommerce api custom tabs and product_brand doesnt work when creating a product 

### ISSUE THREAD

**Issue by surajrajjak** [woocommerce/woocommerce#12015]
**Issue 1** : is i created custom tabs in woocommerce and added some products with inputing text in it and then I tried getting the products through api using
**wcapi.get("products?filter[meta]=true")**

and in response i got this

u'product_meta': {u'product_editor_1932_tab_title': u'Items Needed To Complete', u'minmax_category_group_of_exclude': u'no', u'product_editor_1667_tab_sticky_width': u'pw-content-1', u'product_editor_1667_tab_enabled': u'yes', u'product_editor_1667_tab_title': u'More Info', u'minmax_cart_exclude': u'no', u'total_sales': u'0', u'group_of_quantity': u'', u'product_editor_1932_tab_sticky_height': u'1', u'product_editor_1667_tab_sticky_height': u'1', u'wptr_hide_title': u'0', u'product_editor_1932_tab_sticky_width': u'pw-content-1', u'minmax_do_not_count': u'no', u'product_editor_1932_tab_sticky_position': u'pw-left-stick', u'product_editor_1932_tab_enabled': u'yes', u'minimum_allowed_quantity': u'', u'woocommerce_waitlist': [], u'product_editor_1667_tab_sticky_position': u'pw-left-stick', u'maximum_allowed_quantity': u''},

so i tried passing the same while creating new product

data = {
                            "product": {
                                "title": prod.name,
                                "type": "simple",
                                "reviews_allowed": True,
                                "purchaseable": True,
                                "description": desc5,
                                "short_description":  prod.woocom_short_desc,
                                "enable_html_description":  True,
                                "enable_product_brand": True,
                                "product_brand": [59,60]  
                            }
                        }
 **meta = {
                'product_editor_1667_tab_enabled': 'yes',
                 'product_editor_1667_tab_content_changed': 'yes', 
                 'product_editor_1667_tab_content': 'test-my product content',
                  }**
data["product"].update({"product_meta" : meta})
wcapi.post("products",data)

but it doesnt update in product page.so can anyone help me on how to pass the values for custom tabs?

**Issue2** : I have installed a plugin name product brand in my woocommerce so when i tried creating a product passing this**"product_brand": [59,60]** in the request   and value as id (59,60) but it seems it doesnt work the way am doing,any help would be of great help.

**Comment by claudiosmweb** [comment]
`product_meta` isn't a valid property and the REST API don't allow to save any kind of meta data.
See more details in the REST API docs: https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by surajrajjak** [comment]
ok so can you help me with the product_brand issue,how to pass the value for it so that it displays in it 
![tttt](https://cloud.githubusercontent.com/assets/22621737/19090399/d1700758-8a9b-11e6-8066-2aa5b140387f.png)

I have installed this plugin WooCommerce Brands and its documents states _**https://docs.woocommerce.com/document/wc-brands/**_ that it supports api access,can you tell me a way do this?

**Comment by claudiosmweb** [comment]
We don't have "Brands" on WooCommerce core and here is only for WooCommerce core issues.

>BEFORE POSTING YOUR ISSUE
>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://woocommerce.com/my-account/tickets/ for premium plugin support

**Comment by surajrajjak** [comment]
ok fine! the last one ,am passing the
 'attributes': [{'name': u'Brands', 'options': [u'Zenoah'], 'visible': False, 'position': 0,  'slug': 'brands'}]
and its updating too
![tttt](https://cloud.githubusercontent.com/assets/22621737/19091217/43ac13cc-8a9f-11e6-8fd5-2065534ff377.png)
but when i try to see the filter it doesnt show in it 
![3333](https://cloud.githubusercontent.com/assets/22621737/19091260/8152fff6-8a9f-11e6-9f1c-49ea4b16d2cb.png)
any help???

**Comment by claudiosmweb** [comment]
@surajrajjak as I said, here is not a support channel:

>BEFORE POSTING YOUR ISSUE
>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://woocommerce.com/my-account/tickets/ for premium plugin support

**Comment by surajrajjak** [comment]
Ok thankyou for your service,... Good day

**Comment by surajrajjak** [comment]
Ok thanks for your service.. Good day
