### ISSUE TITLE
Taxes aren't calculated for base postcodes when tax tables use wildcards.

### ISSUE THREAD

**Issue by timlenz** [woocommerce/woocommerce#12016]
## EXPLANATION OF THE ISSUE

Taxes aren't being calculated for postcodes entered in the tax tables with a trailing wildcard (e.g., 94706*) when a postcode matching the base entry is entered on checkout. WooCommerce 2.6.4

## STEPS TO REPRODUCE THE ISSUE

1. Manually enter tax table with wildcard on postcode:

US	CA	94706*		10	Albany CA Tax	1	0	0	

2. Enter an address on checkout including California and the zip of 94706. (If you enter a ZIP+4, the tax calculates correctly).

3. Watch as tax doesn't update on AJAX refresh of cart.

Issue is with the wc_get_wildcard_postcodes function in /includes/wc-core-functions.php, line 1238. The function only matches from the entered zipcode and does not check for the zip plus wildcard (*).

To fix, simply append a wildcard to the first entry in the $postcodes array in line 1238:

$postcodes[]     = $postcode . '*';

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://staging.isothrive.com
Site URL: http://staging.isothrive.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.19 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (20) ###

Query Monitor: by John Blackbourn – 2.13.1
AffiliateWP - Recurring Referrals: by Pippin Williamson and Andrew Munro – 1.5.8
AffiliateWP: by AffiliateWP
LLC – 1.9.2

AfterShip - WooCommerce Tracking: by AfterShip – 1.6.3
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

mobble: by Scott Evans – 1.5
PHP Compatibility Checker: by WP Engine – 1.2.1
Sitemap: by webvitaly – 4.3
Varnish HTTP Purge: by Mika Epstein – 3.9.2
WooCommerce Conditional Shipping and Payments: by WooThemes – 1.2.1
WooCommerce Customer/Order CSV Export: by WooThemes / SkyVerge – 4.0.7
Follow-Up Emails: by WooThemes – 4.4.16
WooCommerce Force Sells: by WooThemes – 1.1.9
WooCommerce Braintree Gateway: by WooThemes / SkyVerge – 3.3.2
WooCommerce Product Bundles: by WooThemes – 4.14.7
WooCommerce FedEx Shipping: by WooThemes – 3.3.7
WooCommerce Subscribe to Newsletter: by WooThemes – 2.3.4
WooCommerce Subscriptions: by Prospress Inc. – 2.0.20
WooCommerce: by WooThemes – 2.6.4
WooCommerce Helper: by WooCommerce – 1.7.1

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #619 - /buy/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: ISOThrive
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Twenty Fourteen
Parent Theme Version: 1.8
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: isothrive/woocommerce/archive-product.php
isothrive/woocommerce/cart/cart-totals.php
isothrive/woocommerce/cart/cart.php
isothrive/woocommerce/cart/proceed-to-checkout-button.php
isothrive/woocommerce/checkout/form-billing.php
isothrive/woocommerce/checkout/form-checkout.php
isothrive/woocommerce/checkout/form-login.php
isothrive/woocommerce/checkout/form-shipping.php
isothrive/woocommerce/checkout/payment.php
isothrive/woocommerce/checkout/review-order.php
isothrive/woocommerce/checkout/thankyou.php
isothrive/woocommerce/content-product.php
isothrive/woocommerce/content-single-product.php
isothrive/woocommerce/emails/customer-completed-order.php
isothrive/woocommerce/emails/customer-reset-password.php
isothrive/woocommerce/emails/email-header.php
isothrive/woocommerce/global/wrapper-end.php
isothrive/woocommerce/loop/add-to-cart.php
isothrive/woocommerce/loop/price.php
isothrive/woocommerce/loop/result-count.php
isothrive/woocommerce/loop/sale-flash.php
isothrive/woocommerce/myaccount/dashboard.php
isothrive/woocommerce/notices/notice.php
isothrive/woocommerce/notices/success.php
isothrive/woocommerce/order/order-details-customer.php
isothrive/woocommerce/order/order-details-item.php
isothrive/woocommerce/order/order-details.php
isothrive/woocommerce/single-product/add-to-cart/simple.php
isothrive/woocommerce/single-product/meta.php
isothrive/woocommerce/single-product/product-image.php
isothrive/woocommerce/single-product/product-thumbnails.php
isothrive/woocommerce/single-product/sale-flash.php
isothrive/woocommerce/single-product/tabs/description.php
isothrive/woocommerce/single-product/up-sells.php
isothrive/woocommerce/single-product.php

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled

### Braintree (Credit Card) ###

Environment: Sandbox
Tokenization Enabled: ✔
`

**Comment by shudocan** [comment]
Hi, could you please post some BRIEF instructions on where to go to implement this fix? I can make my way thru cpanel somewhat...

I am a small business website and this is the exact issue I am experiencing and the tax payments are coming out of my pocket because the customers aren't paying!

**Comment by shudocan** [comment]
Update: I did a search for the filename in cPanel, I opened the file in the code editor, I carefully found that line and CAREFULLY copied and pasted the snippet.  IT WORKS!!!!  Thank you so much!

**Comment by mikejolley** [comment]
94706* is saying 94706+something else. It won't match 94706 exactly. So use 94706 and 94706* in your rule.

**Comment by timlenz** [comment]
I completely disagree. 

Taxes calculated just fine using 94706* to match 94706 - prior to Woocommerce 2.6.

Why should I need to double the number of entries in my tax table because of this new function? That's certainly not efficient.

And if that's the case, why wasn't there any mention made of that in the release notes? That's a pretty significant change that caused me a bunch of headaches.

Your statement "I don't think the longer zips are officially supported or widely used." is complete nonsense. ZIP+4 is the standard used by the USPS. We absolutely need to be able to match against them.

This issue should not be closed.

**Comment by mikejolley** [comment]
USPS API used to allow a 5 digit zipcode. Looks like it may support both now, but split (5 + 4 in separate fields, not in a single lump). 

> Your statement "I don't think the longer zips are officially supported or widely used." is complete nonsense.

For you maybe but not for customers. Do you use +4 when shopping online?

9 digit was not supported in core. The patch for supporting the formatting of 9 digits is here: https://github.com/woocommerce/woocommerce/pull/11890 This is not in stable yet so won't work.

> Taxes calculated just fine using 94706* to match 94706 - prior to Woocommerce 2.6.

If thats the case it was undocumented. I suppose we could support any chars or empty string without breaking other use-cases but I want feedback from others first.

@justinshreve @claudiosmweb ^

**Comment by timlenz** [comment]
Thanks for re-opening.

ZIP+4 is pretty much standard format when using any type of automated
address verification.

There's no harm in my fix, and it is certainly way more efficient than
doubling the size of the tax rates table.

FYI, the current code returns an array for $postcodes with redundant
values, e.g.:

(
    [0] => 95448
    [1] => 95448
    [2] => 9544*
    [3] => 954*
    [4] => 95*
    [5] => 9*
    [6] => *
)

Regardless of the support for longer post codes, this is not right.

The fix I added generates an array that makes more sense:

(
    [0] => 95448*
    [1] => 9544*
    [2] => 954*
    [3] => 95*
    [4] => 9*
    [5] => *
)
