### ISSUE TITLE
Incorrect Product taxonomies label in WP Tag Cloud widget

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#12011]
Not able to determine Product categories or tags in WordPress default Tag Cloud Widget. We might need to disable by `show_tagcloud` arguments while registering taxonomy or need to change label :)
![capture](https://cloud.githubusercontent.com/assets/3774827/19081281/766c6bac-8a79-11e6-8c37-2f5865b8407a.PNG)

**Comment by claudiosmweb** [comment]
Closed in favor of #12014
Thanks for report it.
