### ISSUE TITLE
Website is not displaying all the products inside categories.

### ISSUE THREAD

**Issue by dinamicore** [woocommerce/woocommerce#12017]
## EXPLANATION OF THE ISSUE

Website is not displaying all the products inside categories. Here https://www.redecx.com/prueba/?page_id=917

For example, the first category inside this page is “Colección Otoño 2016” that displays the number 20, for 20 products inside it.

Nevertheless, in the backend, the number of products inside the category are 64. (Attach image66.png)
![64](https://cloud.githubusercontent.com/assets/5693583/19096180/2bc8b2ae-8a60-11e6-8922-fe4172b5e5a3.png)

All the categories have this difference.

Using WordPress version 4.6.1. Expecting Front Page shop display to have the same products as the backend.

## STEPS TO REPRODUCE THE ISSUE

All the plugins expect Woo Commerce are deactivated. In addition, using the Theme Twenty Twelve.

I have posted this issue in https://wordpress.org/support/topic/category-missing-most-products/#post-8253102 for general support, without any response.

**I can provide admin access if needed.**

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it `
### WordPress Environment ###

Home URL: https://www.redecx.com/prueba
Site URL: https://www.redecx.com/prueba
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.24
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - Recomendamos como versión mínima de MySQL la 5.6. Ver: Requisitos de WordPress
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Publicación remota: ✔
Obtención remota: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: por WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Base de la tienda: #489 - /?page_id=489
Carrito: #46 - /?page_id=46
Finalizar compra: #47 - /?page_id=47
Mi cuenta: #48 - /?page_id=48

### Taxonomies ###

Product Types: auction (auction)
external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Twelve
Version: 2.1
Author URL: https://es.wordpress.org/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: : Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –
`.
```

**Comment by claudiosmweb** [comment]
> For example, the first category inside this page is “Colección Otoño 2016” that displays the number 20, for 20 products inside it.

You can have 64, but only is visible and purchasable, since you can hide products from the frontend using the Catalog Visibility option of even hide products out of stock.

**Comment by dinamicore** [comment]
In the Publish panel, the customer set the catalog visibility for the (invisible) products to "hidden" and later on he forgot it. 

Your advice was a great help to find the configuration issue.

Thanks

**Comment by mikejolley** [comment]
@dinamicore so you got an answer but still felt the need to leave this? https://wordpress.org/support/topic/very-bad-support-7/ Thats pretty bad - you received a quick reply after all. Doesn't matter if that reply comes here or on the forum, the same people are dealing with it... Not sure why you're rating just support anyway, and not the plugin. Do you find no value at all?

**Comment by dinamicore** [comment]
@mikejolley; be receptive to constructive criticism.

As a professional developer and IT consultant, I always offer the best software and services to my customers.

I am new to Woo commerce, but old to WP and other CMS. 

Woo commerce is considered and advertised as an excellent plugin. Moreover, it sure might be so.

Nevertheless, a great plugin must be backed up with great support.

When my customer made the mistake of hiding the visualization of the categories and later on forgot it, he got nervous. I told him “Woo commerce is considered among the best, an it´s the most used shopping cart plugin in the World, so I am pretty sure they will come up with a quick en effective solution.

No matter it´s is a great software, a car, a mobile phone, etc. in order to be great and remain great, it also has to provide an outstanding support. 

This is all about my comment.

Thanks.

**Comment by mikejolley** [comment]
@dinamicore You did get a reply though - you had "support", and <3 days. Not sure why thats 'bad' but you're using free forums so I'm not sure what you expected. Cannot bode well for future questions though ¯\_(ツ)_/¯
