### ISSUE TITLE
REQUEST Paypal Gateway add item name filter

### ISSUE THREAD

**Issue by florianbepunkt** [woocommerce/woocommerce#12022]
Hi,

I would suggest to add a filter to WC_Gateway_Paypal_Request class, to change the line item title that is sent to PayPal.

This is would be beneficial especially for Product Variations. Right now the main product title is sent to Paypal. So only the main (parent) product title shows up in the confirmation emails Paypal sends to customers. Since this title often is not very descriptive or useful when it comes to Variable Products, we would like to send the Product Variation description as item name to Paypal.

Right now we can only modify the core as there is no filter for this atm. Since you guys trim the title to the max char amount later, adding a filter for the name shouldn't break anything.

Thanks,
Florian

EDIT: To be more precise - filter would need to go to these methods inside the class:
get_order_item_names()
get_order_item_name()

**Comment by mikejolley** [comment]
PayPal does have a limit for that description length so adding full variation data might push you over. The limit is 127 chars.

https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/

I'd be happy to review a Pull Request if you want to submit this change,  but you may need to reconsider because of that limit. The full details are inside the WC order email anyway.

Closing and will await PR.

**Comment by florianbepunkt** [comment]
I can submit a PR and trim the variation title to max 127 chars. But I guess people use varuation description differently, not everyone use them merely as a title as we do. The underlying issue IMO is that there is no descriptive variation title. Though your post naming of variations makes perfectly sense,  it might be useful to add something like a variation_display_title. Not only when it comes to PayPal but to handling product variations in general. If the title is set WC could default to this title as product title.

If you have a variable product like a t-shirt for example there are a lot of places thorughout WC where it would make sense, not to display the product title (t-shirt), but a descriptive title like 'T-Shirt (S) blue' or 'T-Shirt with the awesome logo'.

**Comment by mikejolley** [comment]
I guess the variation titles could store something more description, but that won't work in all cases e.g. when you use 'any' type attributes for a variation. You simply don't know the type of variation without user input in those cases.

**Comment by florianbepunkt** [comment]
You're right, but in this case it makes no sense to declare a variation title. So if no variation title is declared, the product title should be handled as it is right now.

**Comment by mikejolley** [comment]
So we're talking about storing it as post title rather than adding a filter, correct?

**Comment by florianbepunkt** [comment]
Sorry for not being more precise. Neither. I'm talking about an additional field (just like variation_description) with the name variation_display_title.

The posts title of the Product_Variation itself stays as it is.

If a variation_display_title is specified this could be used in a lot of places where a descriptive title would make sense, for example my Paypal case, where you would send the variation_display_title insteaf of the parent post title of the variation (status quo).

If no variation_display_title is declared for a variation, status quo could be the fallback.

Hope this makes it clearer.

**Comment by mikejolley** [comment]
Ok, I don't think adding a new field is ideal, so I'll add a filter and send something more meaningful by default.
