### ISSUE TITLE
Hide free shipping for whole card when a product has flat rate shipping class set?

### ISSUE THREAD

**Issue by zkvvoob** [woocommerce/woocommerce#12020]
Hello,

I found a few snippets around that show how to hide flat rate shipping options when free shipping is available. However, I'd like to achieve the opposite: if a product is shipped for free on its own, but is added to the card with another product which has a flat-rate shipping class, hide the free shipping for the whole cart.

    /**
     * woocommerce_package_rates is a 2.1+ hook
     */
    add_filter( 'woocommerce_package_rates', 'hide_shipping_when_free_is_available', 10, 2 );
     
    /**
     * Hide shipping rates when free shipping is available
     *
     * @param array $rates Array of rates found for the package
     * @param array $package The package array/object being shipped
     * @return array of modified rates
     */
    function hide_shipping_when_free_is_available( $rates, $package ) {
      
      // Only modify rates if free_shipping is present
        if ( isset( $rates['flat_rate'] ) ) {
        
          // To unset a single rate/method, do the following. This example unsets flat_rate shipping
          //unset( $rates['free_shipping'] );
    	  
    	  // To unset all methods except for free_shipping, do the following
          $flat_rate          = $rates['flat_rate'];
              $rates                  = array();
          $rates['flat_rate'] = $flat_rate;
      }
      
      return $rates;
    }

This is what I've modified, but it doesn't work. Could you help me, please?

Thank you!

**Comment by claudiosmweb** [comment]
Here is not a support channel, this is only for WooCommerce core issues.
If you have questions, you always can use our support forum on wp.org: https://wordpress.org/support/plugin/woocommerce
