### ISSUE TITLE
WC_Product_Variation->get_variation_description() shouldn't return any formatting included

### ISSUE THREAD

**Issue by florianbepunkt** [woocommerce/woocommerce#12023]
WC_Product_Variation->get_variation_description() returns the variation description inside <p> </p> tags. Is there a specific reason for this? As far as I see it should return an unformatted value or there should be two methods exposed for formatted and raw value.

**Comment by justinshreve** [comment]
It filters the description through do_shortcode so its a string that can contain HTML/formatted text. If you want just the raw variation (without any tags around it) you can pull from the meta:

`get_post_meta( $variation_id, '_variation_description', true )`.

**Comment by claudiosmweb** [comment]
For now you can use `WC_Product_Variation->variation_description` if you don't any kind of formatting.
This is being reviewed now for our new Products Crud.
