### ISSUE TITLE
Layered Nav "Any %s" translation

### ISSUE THREAD

**Issue by neonics** [woocommerce/woocommerce#12025]
The Layered Nav dropdown uses a translation of `Any %s` ([see here](https://github.com/woocommerce/woocommerce/blob/master/includes/widgets/class-wc-widget-layered-nav.php#L224)) which is too simplistic for languages that take gender into consideration. Some examples:
```
English         Dutch                              German
"Any price"     "Elke prijs" (masculine)           "jeder Preis" (masculine)
"Any size"      "Elke grootte" (feminine)          "jede Größe" (feminine)
"Any theme"     "Elk thema" (neutral)              "jedes Thema" (neutral)
```

The code doesn't leave much room for customisation:

`echo '<option value="">' . sprintf( __( 'Any %s', 'woocommerce' ), wc_attribute_label( $taxonomy ) ) . '</option>';`

In this case, the translation of `Any` depends on what `%s` is, so unfortunately this cannot be handled by hooking into the 'gettext' filter.

Is it possible, for instance, to wrap `sprintf` in an `apply_filters` call so bad translations can be fixed?

Thanks!

**Comment by claudiosmweb** [comment]
Closed in favor of #12026
