### ISSUE TITLE
XSendfile / X-Accel-Redirect Does Not really redirect with Nginx

### ISSUE THREAD

**Issue by godowsky** [woocommerce/woocommerce#12021]
## EXPLANATION OF THE ISSUE

Having some troubles setting up nginx for X-Accel-Redirect zip files downloads. I added and then removed line `location ~* ^/(wp-content)/(.*?)\.([B]zip[/B]|gz|tar|bzip2|7z)$ { deny all; }` from domain.com.conf because this was not letting nginx accessing the zip files. Now X-Accel-Redirect is serving the downloads but anyone can access the files in "wp-content/uploads/woocommerce_uploads". Is X-Accel-Redirect really redirecting in this case? 
How do I protect the storage folder "wp-content/uploads/woocommerce_uploads"? Thanks for your help.

## SYSTEM STATUS REPORT

Server Info:		nginx/1.11.4
PHP Version:		7.0.11
PHP Post Max Size:		256 MB
PHP Time Limit:		60
PHP Max Input Vars:		10000
cURL Version:		7.29.0, NSS/3.19.1 Basic ECC
SUHOSIN Installed:		–
Max Upload Size:		256 MB
Default Timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte String:		
Remote Post:		
Remote Get:		
Database
WC Database Version:		2.6.4
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta

**Comment by mikejolley** [comment]
http://serverfault.com/questions/137907/how-to-restrict-access-to-directory-and-subdirs

**Comment by ottok** [comment]
You cannot use the 'deny' in the Serverfault answer, as it also denies the Nginx internal redirects. The correct solution is to make the directories **internal**:
```
        location /wp-content/uploads/woocommerce_uploads/ {
                internal;
        }
```
