### ISSUE TITLE
Japanese iOS users can't enter credit card info

### ISSUE THREAD

**Issue by netplus** [woocommerce/woocommerce#12037]
The default credit card page uses jquery-payment. This causes credit card numbers to scramble while using the default Japanese iOS keyboard.

Please see following bug demo video.
https://www.youtube.com/watch?v=MEpelmggcsE
I've typed 424242 but 4244242422 has appeared

## Expected behaviour
Entered card number should appear in field as entered

## Actual behaviour
When a space is entered by jquery.payment of the 4th character it breaks the last character off the Japanese IME into the field then continues input with the IME

## Steps to reproduce
Enter a card number using the default Japanese keyboard on iOS

## Problem code
jquery.payment.js l:240

**Comment by netplus** [comment]
Looking at the official Stripe docs:
https://stripe.com/docs/checkout/tutorial

When you open the payment gateway on iOS / Android they are changing the field type to TEL to avoid these issues. Perhaps we should implement that into the default payment form?

**Comment by claudiosmweb** [comment]
Closed in favor of #12045
