### ISSUE TITLE
When updating a product description the inventory is reset to the original level

### ISSUE THREAD

**Issue by KevinACrider** [woocommerce/woocommerce#12031]
## EXPLANATION OF THE ISSUE

When updating a products details the inventory level is reset to the original value and doesn't maintain the existing level.

## STEPS TO REPRODUCE THE ISSUE

Add a product, set the inventory level to 50. After orders are placed for that item, update the product description. The inventory is reset to 50 and doesn't reflect the current inventory.

## SYSTEM STATUS REPORT

Grab the system status report from WooCommerce > System Status and paste it here.

**Comment by tommyshellberg** [comment]
@KevinACrider I can't replicate this in any way. Are you able to replicate this with *just* WooCommerce active? Also a silly question, but are you leaving the product editor tab open while testing this? If the inventory value is still set at 50 in the editor when you update the product(after placing the order), it would explain why it's going back to 50...

**Comment by mikejolley** [comment]
Not happening here. Would have to be extension or an update via the Rest API from elsewhere.
