### ISSUE TITLE
REST API: Delete only the variations

### ISSUE THREAD

**Issue by jstrobel** [woocommerce/woocommerce#12036]
I thought i can delete all variations of a product with a call like this:
$woo->put('products/88', array('attributes' => $attributes, 'variations' => array()));
But it didn't work.

I have read some closed issues but couldn't find a answer. Is this not implemented or is this the wrong call? I don't want to delete the product, just the variations.

Thanks.

**Comment by claudiosmweb** [comment]
Not suppose to delete variations in this way.
You can use batch delete endpoint to delete all variations at the same time too.
But in the next version we'll have a endpoint especially for product variations.

**Comment by jstrobel** [comment]
Thanks for the Info.
