### ISSUE TITLE
Sub category not displayed in top header category dropdown

### ISSUE THREAD

**Issue by josephanit** [woocommerce/woocommerce#12033]
Great product! Works extremely well for my projects.

I'm also some issues. 
1. Shows only parent categories in top header widget. i wants to display all subcategories in search category dropdown.
2. there is no option for checking  "Only show children for the current category" box  in the widget, all category and subcategories diplay in product page and other pages.

Any chance this will be addressed ?

Using WooCommerce 2.6.4

**Comment by justinshreve** [comment]
Issue 1 should already be possible with the "Show hierarchy" option.

@mikejolley  It looks like there is some history behind the show children category box (#5028) -- so it looks like the way it functions now is intended? The behavior of only showing hierarchy for the current category but still showing all other top levels seems odd. The way I would expect that setting to work is to only show the parent category & it's subs. Showing every single top level category makes it seem like that checkbox is broken.

**Comment by mikejolley** [comment]
It is correct as-is as far as intent goes. The option is labelled:

`Only show children of the current category`

The top levels are children of nothing. Showing them allows you to change your search without going back to the top level or shop page, and I personally feel thats much more desirable. That also actually matches the display of children; when you drill down, the siblings of sub-categories are shown too.
