### ISSUE TITLE
Full Page Template Doesn't Work on Shop Page

### ISSUE THREAD

**Issue by BFTrick** [woocommerce/woocommerce#12034]
## THE ISSUE

The Full width template doesn't seem to work on the Shop page. It works with regular pages just not the shop page.

It it's not supposed to do anything it shouldn't be visible on the shop page - and if it is supposed to do something then that needs to be fixed.

Screencast: http://d.pr/i/njqU

Using only Storefront & WooCommerce

## Proposed solution

. @jameskoster and I had some discussion about this on the [Storefront repo](https://github.com/woocommerce/storefront/issues/487#issuecomment-251915797).

I think this is the best solution:

> I'm torn on this one. As a compromise, perhaps we display the meta box, but add a notice explaining why it doesn't work, with a link to docs explaining further. That's something we should do in WooCommerce core though.

**Comment by justinshreve** [comment]
Hey Patrick! I agree that we should fix it since it's confusing but I'm definitely torn on how. If we go with the proposed solution, I think we should throw a `disabled` attribute on the dropdown too.

**Comment by BFTrick** [comment]
Sure - can definitely do that.

What do you think about hiding the template area entirely?

Maybe go that route first and if we get tickets then disable it with some sort of notice?

**Comment by justinshreve** [comment]
I think hiding it entirely instead of having it disabled with a link is a lot cleaner. I'm not sure how many people go to the page in the first place so that works if it wouldn't lead to a lot of tickets. My initial gut feeling is that it wouldn't be a huge deal (as stated on the other thread, a lot of people probably don't touch these after the wizard).

**Comment by jameskoster** [comment]
The main concern with flat out removing it is;

a. Folks who create the page manually will see it initially (we can't hide it if we don't know whic page is the shop page, right?)
b. Folks will wonder where it is. "I can apply a template to any other page, why not the shop page?" I can see people posting in support about that.

**Comment by justinshreve** [comment]
Is it a large number of people creating it manually? Or if they are creating it manually are they following some sort of a help doc we could mention it in?

**Comment by jameskoster** [comment]
I doubt it's very many at all. The second point is the bigger issue I think.

**Comment by BFTrick** [comment]
If we removed the option and pushed this out with 2.7 we could track how many people have issues. If it's above X then in 2.8 we could add a disabled option with a link to a help doc.

My gut says that few people will create tickets for this. Less than 20 before 2.8 comes out.

**Comment by webmandesign** [comment]
Hey guys,

I'm not sure whether this is a happy solution.

In my opinion **if a theme claims compatibility with WooCommerce, it should integrate support for Shop page templates as well or remove the templates itself on Shop page edit screen**. Page templates are mostly a territory of themes anyway. Page template selector should not be removed by WooCommerce I think.

As this way it seems like themes without proper support for WooCommerce are in favor here.

Maybe a sample code about how to remove page templates for WC Shop page at https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/ would be enough. Such as:

```
function prefix_hide_shop_page_temp_templates( $page_templates ) {
	if ( function_exists( 'wc_get_page_id' ) && wc_get_page_id( 'shop' ) === get_the_ID() ) {
		$page_templates = array();
	}

	return $page_templates;
}

add_filter( 'theme_page_templates', 'prefix_hide_shop_page_temp_templates' );
```

Wouldn't it do?

**Comment by mikejolley** [comment]
Better to unhide it because I think it's more likely that themes don't know or notice that shop is not a real page, so that would lead to broken functionality.
