### ISSUE TITLE
Orders Duplicated on import 

### ISSUE THREAD

**Issue by smanunta** [woocommerce/woocommerce#12035]
## EXPLANATION OF THE ISSUE

I have a site that was moved from WP to another WP installation. I exported the woocommerce data in a CSV and imported again into the new instance with the WP importer. On import all the orders were imported twice. So now i have a ton of duplicates in my history which is causing reporting issues.

The issue only happened during the import, new orders come in fine, only issue is the current duplicate orders which are screwing up reporting.

Is there a way to easily target and remove Duplicate orders?
currently running WP 4.6.1

**Comment by claudiosmweb** [comment]
Don't looks like an issue with WooCommerce. Need to try to import it again using other importer.
