### ISSUE TITLE
Issues with pricing display with decimals

### ISSUE THREAD

**Issue by highacid** [woocommerce/woocommerce#12043]
This might be a bug, anyhow is an issue for me. I work with a program that is located locally in the shop, this has the ability to send it's prices to woocommerce. The issue works as follows, the program adds for ex a product pricing at 123 USD, yet the product in woocommerce is displayed as 123.0000 I have all decimals turned off in Woocommerce. Now if I add a discount to this very same product say 100 USD, and i do not add .0000 after 100 the discount is simply not working to be displayed correctly in site. In other words, if price is with 4 decimals, so must be discount price. Anyone any idea on this? Regards.

Here is the system report:

`
### WordPress Environment ###

Home URL: https://www.xxxx
Site URL: https://www.xxxx
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: cs_CZ

### Server Environment ###

Server Info: Apache/2.2.15 (CentOS)
PHP Version: 5.6.26
PHP Post Max Size: 512 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.7.15
Max Upload Size: 0 B
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Vzdálená metoda Post: ✔
Vzdálená metoda Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (27) ###

Ninja Popups: o ArsCode – 4.4.0
České služby pro WordPress: o Pavel Hejn – 0.5
Contact Form 7: o Takayuki Miyoshi – 4.5.1
Fancy Product Designer: o Rafael Dery | radykal.de – 3.3.1
FG Magento to WooCommerce Premium: o Frédéric GILLES – 2.14.0
Nextend Facebook Connect: o Roland Soos – 1.5.9
Nextend Google Connect: o Roland Soos
Jamie Bainbridge – 1.6.0

OPcache Dashboard: o Daisuke Takahashi(Extend Wings) – 0.3.1
Regenerate Thumbnails: o Alex Mills (Viper007Bond) – 2.2.6
WPML Multilingual CMS: o OnTheGoSystems – 3.5.3.1
Tawk.to Live Chat: o Tawkto – 0.2.1
UHL - Allow HTML in Category and Taxonomy Description: o UHL Hosting & MultiSys.Ro – 1.0
WooCommerce Category Description Product Tab: o MultiSys.Ro & UHL Hosting – 1.0
WooCommerce Poisonbite Custom Order Email: o MultiSys.Ro & UHL Hosting – 1.0
Woo Doprava: o Vladislav Musílek – 1.3.8
Woo Import Export: o VJInfotech – 2.0.2
Woocommerce Advanced Bulk Edit: o George Iron – 4.0.4
WooCommerce Multilingual: o OnTheGoSystems – 3.9
WooCommerce: o WooThemes – 2.6.4
WooSidebars: o WooThemes – 1.4.3
WP-DBManager: o Lester 'GaMerZ' Chan – 2.78
WPML CMS Nav: o OnTheGoSystems – 1.4.19
WPML Media: o OnTheGoSystems – 2.1.23
WPML Sticky Links: o OnTheGoSystems – 1.4.0
WPML String Translation: o OnTheGoSystems – 2.4.2.1
WPML Translation Management: o OnTheGoSystems – 2.2.4.1
YITH WooCommerce Wishlist: o YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Sídlo obchodu: #1 - /obchod/
Košík: #2 - /kosik/
Pokladna: #3 - /pokladna/
Můj účet: #4 - /muj-ucet/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome Child
Version: 3.2
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.1.6
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome-child/woocommerce/emails/customer-completed-order.php
flatsome-child/woocommerce/emails/customer-on-hold-order.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php verze - je neaktuální. Aktuální verze jádra je 2.5.0
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome-child/woocommerce/single-product.php

: Naučit se jak aktualizovat zastaralé šablony
`

**Comment by mikejolley** [comment]
WC formats it's prices on the frontend according to your currency settings. Plugins like WPML can change currency settings so be sure to check those. This is a plugin issue.
