### ISSUE TITLE
addable/repeatable options for Woocommerce plugin

### ISSUE THREAD

**Issue by sandrodz** [woocommerce/woocommerce#12046]
I  need to give user addable/repeatable option via Woo settings API (inside my plugin). I read through the docs and it doesn't seem to be possible.

Is there a workaround? Or do I have to implement it myself?

**Comment by mikejolley** [comment]
This is not needed by core and thus won't be added any time soon. You can add custom setting field types and output via the filters/actions etc. We do this in some of our extensions which have custom setting fields.

**Comment by sandrodz** [comment]
in case someone ends up here via G search.

I implemented it this way: https://github.com/wearede/woo-tbc-payment-gateway/blob/master/woo-tbc-payment-gateway.php check method `generate_merchant_accounts_html`

**Comment by sandrodz** [comment]
@mikejolley great, can you direct me to the extension that has this functionality?
