### ISSUE TITLE
New REST API filter for completed_at_min and completed_at_max

### ISSUE THREAD

**Issue by Babelfisch** [woocommerce/woocommerce#12048]
Especially for prepay orders the `completed_at` date is important for statistics. But is seems that only `created_at_min/_max` and `updated_at_min` works as filter in REST-API-calls.

Is it possible to add `completed_at` as additional filter?

**Comment by mikejolley** [comment]
I don't think the WP API supports the 'filter' arg any longer - this can be used though https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-orders-controller.php#L56 We'll be bulking out the order search capabilities in future versions.

**Comment by amjad** [comment]
Is `completed_at_min` and max possible with legacy v3? Where is the code for this?
