### ISSUE TITLE
Pay order page CC fields not showing and hiding

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce#12047]
## EXPLANATION OF THE ISSUE

WC Master - With a payment method that has at least one saved CC.

When you have an order that is pending payment, you go to "My Account -> Orders" and click "Pay" on the order that is pending payment. Then if you try to click on "Use new card" and back to the saved card, you will see the credit card form remains visible when it should toggle hiding/showing.

![](http://cld.wthms.co/kVjJ/2gyqZyIr+)

The JS responsible for showing and hiding the form is in the `tokenization-form.js` however because on the pay order page, the "updated_checkout" event doesn't exists on that page, the implementation is never triggered.

https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/tokenization-form.js#L77

**Comment by claudiosmweb** [comment]
> the "updated_checkout" event doesn't exists on that page, the implementation is never triggered.

Showing some error on the browser console?
