### ISSUE TITLE
V2 API Exception

### ISSUE THREAD

**Issue by mjjanusa** [woocommerce/woocommerce#12049]
## EXPLANATION OF THE ISSUE

Get a 500 response when calling V2 api with printful.  

Following error from the logs: 
PHP Fatal error: Cannot redeclare class WC_API_Exception in {...}/wp-content/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-exception.php on line 48

I was able to fix this locally by changing class-wc-legacy-api.php to remove the include_once( 'api/legacy/v2/class-wc-api-exception.php' ); from handle_v2_rest_api_request() as the v3 version included in includes() is identical. Seems like these two classes need to be combined. 

## STEPS TO REPRODUCE THE ISSUE

Setup printful with latest woo commerce plugin (https://www.theprintful.com).  Printful returns error that api had 500 response.  Suspect this would reproduce with any v2 api calls, but not familiar enough with woocommerce to know for sure. 

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

`
### WordPress Environment ###

Home URL: http://micdofficial.com
Site URL: http://micdofficial.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.20 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (15) ###

Gravity Forms: by rocketgenius – 2.0.7
Black Studio TinyMCE Widget: by Black Studio – 2.2.8
Mailgun: by Mailgun – 1.4
Menu Social Icons: by Paul Clark – 1.3.10
Slider Revolution: by ThemePunch – 5.1.6
Page Builder by SiteOrigin: by SiteOrigin – 2.4.2
SiteOrigin Widgets Bundle: by SiteOrigin – 1.5.9
tagDiv Woo Invoice: by tagDiv – 1.0
tagDiv Woo Label: by tagDiv – 1.0
WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce Square: by Automattic – 1.0.9
WooCommerce: by WooThemes – 2.6.4
WooCommerce Helper: by WooCommerce – 1.7.1
WordPress Importer: by wordpressdotorg – 0.6.3
YITH WooCommerce Color and Label Variations Premium: by Yithemes – 1.0.7

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #2004 - /shoppe2/
Cart: #601 - /cart/
Checkout: #602 - /checkout/
My Account: #603 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Create
Version: 1.1.0
Author URL: http://themetrust.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: themetrust-create/woocommerce/archive-product.php version - is out of date. The core version is 2.0.0
themetrust-create/woocommerce/content-single-product.php
themetrust-create/woocommerce/global/form-login.php
themetrust-create/woocommerce/global/sidebar.php version - is out of date. The core version is 1.6.4
themetrust-create/woocommerce/single-product/related.php
themetrust-create/woocommerce/single-product.php

: Learn how to update outdated templates
`

**Comment by claudiosmweb** [comment]
I just tested all versions of our REST API and in WooCommerce core we don't declare this class more than one time.
https://github.com/woocommerce/woocommerce/blob/release/2.6/includes/class-wc-legacy-api.php#L97-L103
The code does not allow load more than once.

> I was able to fix this locally by changing class-wc-legacy-api.php to remove the include_once( 'api/legacy/v2/class-wc-api-exception.php' ); from handle_v2_rest_api_request() as the v3 version included in includes() is identical. Seems like these two classes need to be combined. 

All classes from the legacy REST API v1, v2 and v3 have the same names, so if it had problems declaring the `WC_API_Exception` class, so must have the same problem for all other REST API classes too and not only with one class.

I believe that this error is caused by some other plugin that is trying to load this class.
