### ISSUE TITLE
Local Pickup Displays Shipping Address

### ISSUE THREAD

**Issue by DustinHartzler** [woocommerce/woocommerce#12054]
## EXPLANATION OF THE ISSUE

In WooCommerce latest version 2.6.4, the displayed text on the New Customer Order emails notification contents has changed.

The shipping address should only be added to the new customer order email if customer select shipping option, BUT this is not happening. Shipping address is being added to the new customer order email notification in any way even customer choose Local Pickup or Local Delivery.

Here's a screenshot on WooCommerce 2.5.5:
![2016-10-10 at 3 01 pm](https://cloud.githubusercontent.com/assets/2293077/19247750/ab8ca7d6-8efa-11e6-8317-63c14f3fe982.png)

Here's a screenshot on WooCommerce 2.6.4:
![2016-10-10 at 3 02 pm](https://cloud.githubusercontent.com/assets/2293077/19247739/a25f54ce-8efa-11e6-8d64-25ec882b22c3.png)

**Comment by claudiosmweb** [comment]
Already fixed in #11552
Waiting for a new release.
cc @mikejolley
