### ISSUE TITLE
Trigger order create webhooks when an order is created on the admin panel

### ISSUE THREAD

**Issue by achadee** [woocommerce/woocommerce#12060]
## EXPLANATION OF THE ISSUE

Currently it looks like order update webhooks are the only webhooks being created on the admin panel

## STEPS TO REPRODUCE THE ISSUE

1. create order on admin panel
2. observe incoming webhooks

let me know if im doing something wrong!

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/11686
