### ISSUE TITLE
Contribution guidelines links 404

### ISSUE THREAD

**Issue by jamesjonesphoenix** [woocommerce/woocommerce#12089]
## EXPLANATION OF THE ISSUE

Links to WooCommerce guidelines page are 404ing. Where are they?
## STEPS TO REPRODUCE THE ISSUE

Go to https://github.com/woocommerce/woocommerce/blob/master/CONTRIBUTING.md . Get 404 page.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md

**Comment by jamesjonesphoenix** [comment]
Cheers for that
