### ISSUE TITLE
Fixed bugs go unfixed if they are not released

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce#12083]
3 months since the last bugfix release. There's been many bugfixes in between, two alone that I reported (#11772, #11832) and which are important for my site. It's nice that bugs are fixed on github in a timely manner, but the bugs are not fixed on websites for real unless a new version is released. Please, please do so. Release fast, release often - and keep up the good work. Appreciated :)

**Comment by mikejolley** [comment]
We're aware of this, no need to open non-issues about it :)
