### ISSUE TITLE
Order confirmation page visible to unauthorized users

### ISSUE THREAD

**Issue by whizzoo** [woocommerce/woocommerce#12084]
I've noticed with Woocommerce 2.6.4 that the order confirmation page is visible to anyone.
The url to an order confirmation page looks like this: http://www.example.com/checkout/order-received/{_ordernumber_}/?key=wc_order_{_key_}. This page can be viewed by anyone who has this url, and it will display the items ordered, order price, payment method and **customer information**. Without the key, customer information is absent but order information is still displayed. I have tried appending the url from /checkout/ onward to random webshops using WooCommerce and all of them display the order confirmation page. It shouldn't be too hard to whip up a script that generates random order numbers, allowing third parties to access information about orders.

In my opinion, the order confirmation page should only be visible after an order has been placed and should return an error message when accessed at other times. Not even admins need access to this page, as they can access order information straight from the dashboard. Presently, this bug poses a substantial threat to the safeguarding of data by e-commerce websites.

My apologies if this issue has been reported before. I was unable to find anything here on Github or by googling.

**Comment by mikejolley** [comment]
Customer information is hidden as of 2.6 unless the user is logged in. Otherwise it shows just ordered items. The URL itself uses randomly generated keys - it's not guessable, so it's not really a risk.

**Comment by whizzoo** [comment]
Hi Mike,

Thanks for the follow-up. I'm glad the user information is not visible to outsiders. I'm not sure why the same is not the case for the ordered items, payment method and order amount though? It's information that's only ours and the respective customer's business. I would really prefer to hide it from the general public.

**Comment by mikejolley** [comment]
It is hidden from general public. The URL cannot be guessed.

**Comment by NickMackerel** [comment]
Hi Mike, sorry to raise something from a year ago however I believe there is an important issue around the confirmation page.

If a site owner is passing data to an Analytics package or advertising tracking system (as is very common), each time one of these URLs is visited, the information is re-sent to the Analytics tool, creating duplicate data. We have experienced one such URL being revisited 10 times, which we are guessing has happened as a customer has left a browser tab open on their device. We are also observing the page as available _without_ login on WC 3.2.5, with customer details.

This causes a few issues:

1. Recorded Revenue is inflated in Google Analytics, overstating the effectiveness of certain ad spend
2. Recorded Revenue is inflated in Google AdWords, overstating the effectiveness of certain ad spend
3. The confirmation URL is passed to Analytics, meaning anyone with access to the Analytics account can see each confirmation URL, and visit it. Further, some other tools extract data from Analytics, meaning these URLs can be seeded externally. In our view this might pose a data protection risk.

**Comment by mikejolley** [comment]
Sounds like something that should be tackled in the Analytics implementation, rather than hiding data from the customer who has cause to see it.

Also 3 is not an issue because sensitive data is hidden unless you're logged in as the user who placed the order.

**Comment by NickMackerel** [comment]
Agreed it would be preferable that Analytics tools handled this but with Google Analytics it's non-trivial to solve unless you amend behaviour Woo-side, or use a tag management solution to deploy the tracking code to your site, then implement a bit of a hack. Thus, I would guess many many Woo+GA users experience this issue, perhaps unbeknownst.

3 - we are able to view Customer Name, Email, last 4 digits of card, Billing Address, Delivery Address, full cart contents, without being logged in. Is there something we are doing wrong?

**Comment by mikejolley** [comment]
Core cannot really make the decision for you whether to include or exclude tracking code so I don't know what to suggest there.

r/e 3, see handling in https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/thankyou.php#L55

**Comment by tiago-123** [comment]
Hello,

I'm using WooCommerce v5.1.0 and I'm observing the same problem reported by other users previously. The URL for the order confirmation (which contains sensitive customer data!!) is visible to anyone with the URL address.

You can reproduce the issue by opening an incognito tab and pasting the URL there. It will promptly show the order confirmation and all the customer data.
