### ISSUE TITLE
Coupon form not visible in checkout if coupon already applied

### ISSUE THREAD

**Issue by lawkwok** [woocommerce/woocommerce#12082]
## EXPLANATION OF THE ISSUE

When a coupon is applied in the cart, the coupon form on the checkout page will be missing.

## STEPS TO REPRODUCE THE ISSUE

1. Apply a coupon code on the cart page.
2. Go to the checkout page.

## SYSTEM STATUS REPORT

Tested on WC 2.6.4 using Storefront Theme with only WooCommerce activated.

**Comment by mikejolley** [comment]
This was an intentional change if I recall - once you've input your coupon it's not really needed. The full coupon form is on the cart page.

**Comment by lawkwok** [comment]
I think it is more confusing than helpful to have a part of the UI disappear. It is that uncommon customers enter more than one coupon code? 

Also, WooCommerce's Points and Rewards plugin uses coupon codes in the backend to apply a discount. Sometimes customers who apply their loyalty points are not able to apply a coupon which is confusing.

**Comment by dgtlprphcy** [comment]
mikejolley, 

What is the simplest way to allow multiple coupons to be added? I don't want the coupon entry to be removed from checkout...
