### ISSUE TITLE
Make it easier to extend Cash on Delivery payment gateway class

### ISSUE THREAD

**Issue by attiladonath** [woocommerce/woocommerce#12085]
## EXPLANATION OF THE ISSUE

I need to create two Cash on Delivery style payment options for a webshop.
One would be "pay with cash on delivery" and the other would be "pay with credit card on delivery".
It makes sense to me to simply create a minimal module and use the `WC_Gateway_COD` as the base for the new payment method.

The plugin looks like this right now, it includes quite a lot of code duplications: https://gist.github.com/attiladonath/c8e53a650e081b45776ed8dfcedbc495

These duplications could be prevented by some simple refactoring, I'll create a pull request in a minute.

## STEPS TO REPRODUCE THE ISSUE

It is just a refactoring idea.

## SYSTEM STATUS REPORT

Does not really make sense here.

**Comment by claudiosmweb** [comment]
Closed by #12086
