### ISSUE TITLE
Customers API endpoint slow because of last order query

### ISSUE THREAD

**Issue by bryceadams** [woocommerce/woocommerce#12080]
## EXPLANATION OF THE ISSUE

This is has been tested with a 100k order/100k customer store.

When a request is made to the `customers` index endpoint, it can be very slow due to 3 bits of data being returned:

* total spent
* order count
* last order

Total spent and order count are manageable, as they're stored in meta and technically can be filtered if you didn't want them to be calculated.

But **last order** is not cached and is very slow.

Some of my tests:

1. With last order - `GET customers?per_page=10&page=57`- 106 seconds
2. Without last order - `GET customers?per_page=10&page=57` - 9 seconds

Note that the order count / total spent was not being calculated in either of those tests.

I propose we remove last order from the customers API endpoint completely as it can be gotten with a separate query to the orders endpoint, filtered for that customer.

Otherwise we could add a filter so plugin authors can ignore it.

I'll create a PR to remove it if we decide to take that route.

**Comment by claudiosmweb** [comment]
@mikejolley I think we can start save in cache `total spent` and `order count`.
And I don't see a problem of removing `last order` since it's possible filter orders by customer using `GET /wc-json/wc/v1/orders?=customer=1`

**Comment by bryceadams** [comment]
`total spent` and `order count` are stored in the customer's user meta so I don't think you need to add anything from those. What do you both think about adding a param for **not** getting them (it can still get them by default though, so no breaking change)?

**Comment by claudiosmweb** [comment]
@bryceadams look again: https://github.com/woocommerce/woocommerce/blob/dec792b731dbbea6d34aa3ddcd6a3bf05bf43077/includes/class-wc-customer.php#L252-L296
Requires a query each time.

**Comment by bryceadams** [comment]
ah @claudiosmweb, I must have been thinking of an earlier version.
