### ISSUE TITLE
Process Email when Fullfillment off site. 

### ISSUE THREAD

**Issue by robertdall** [woocommerce/woocommerce#12095]
In WooCommerce 2.6.4

If you have a product that is offered for free or a coupon for a free product, the web store will not send any user notification as the processing email is turned off and we do our fulfillment offsite.

But if the item that was purchased for free the offsite fulfillment system doesn't give an email either because no transaction has been made.

Yet if we turn on processing emails then the customers who did pay for a product get duplicate email. One from the web store and one from the offsite fulfillment system.

While my client has decided for the duplicated email system. I wanted to note this here as Customer Invoice default is set manually and Processing Email sound a lot like the email is with in processing of the charge of the invoice. A fair bit of confusion occurred and it wasn't until a lot of testing went into play that is was discovered that the processing email was also the website receipt email. We realize that the word processing could also mean the processing or the order after the fact. 

Maybe a name change of the actual email?  As webstore reciept and webstore processing email sound completely different and could mean very different things.

**Comment by mikejolley** [comment]
I don't feel we need to rename emails - processing indicates that the order is ready for processing/accepted, not that a payment has been made. The introduction of external fulfilment emails is not something core should accommodate by default. It would be possible for you to add a code-based customisation to check order total and send if needed, or the reverse. 

See this filter https://github.com/woocommerce/woocommerce/blob/master/includes/emails/class-wc-email.php#L356

**Comment by robertdall** [comment]
Thanks for the feedback @mikejolley much appreciate you sharing your valuable time.
