### ISSUE TITLE
Does anyone have issue with new orders sometimes

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#12098]
## EXPLANATION OF THE ISSUE

WooCommerce version 2.6.4.

I got some problem with orders via paypal. The orders went through order-received, paypal captured the money. However, the paypal doesn't send api sigh to Woo or woo doesn't catch it. Then, the order was set to Pending.

wp_remote_post() failed. PayPal IPN won't work with your server. Contact your hosting provider. Error: cURL error 6: Could not resolve host: www.paypal.com

My OpenSSL 1.0.1t  3 May 2016

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
``

**Comment by mikejolley** [comment]
https://docs.woocommerce.com/document/paypal-standard/#section-9

You can enable PDT too https://docs.woocommerce.com/document/paypal-standard/#why-dont-customers-see-the-link-to-download-products-after-paying-and-getting-redirected-back-to-my-website.

Server issue so closing here. Enable logging if you need to debug further for yourself.
