### ISSUE TITLE
How to Get "On Sale" Product using REST API ?

### ISSUE THREAD

**Issue by billyriantono** [woocommerce/woocommerce#12093]
Hi Team,
I am on using Woocommerce rest api, when i am try to get all on sale product using endpoint /products in current version Woocommerce rest api ( v1) and add filter['on_sale']=true it's doesn't give me the correct result.

anyone can help me to do this ?

Thanks

**Comment by mikejolley** [comment]
There is no 'on_sale' filter in the API. This is not documented either.

@claudiosmweb worth adding to new search api?

**Comment by billyriantono** [comment]
so what i can use to get on sale product ? because in web there is shortcode [sale product] but it's really hard to get using rest API 😄

**Comment by claudiosmweb** [comment]
@billyriantono right now, you can't and don't have anything to filter only on sale products in the REST API. I'll include it into a new release.
