### ISSUE TITLE
Unable to send post request to the REST API using postman

### ISSUE THREAD

**Issue by merhawifissehaye** [woocommerce/woocommerce#12092]
## EXPLANATION OF THE ISSUE
I can send get requests to all endpoints using postman. I am using OAuth1.0 authorization method. I provided the consumer key and consumer secret, signature method HMAC-SHA1. But when I send post request by supplying the required parameters and using the same authorization method, I get the following error:
```
{
  "code": "json_oauth1_missing_parameter",
  "message": "Missing OAuth parameter oauth_token",
  "data": {
    "status": 401
  }
}
```

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://192.168.0.105/lomistore
Site URL: http://192.168.0.105/lomistore
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.9 (Win32) PHP/5.5.12
PHP Version: ❌ 5.5.12 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 3 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.36.0
OpenSSL/1.0.1g

SUHOSIN Installed: –
MySQL Version: 5.6.17
Max Upload Size: 3 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (6) ###

WP REST API - OAuth 1.0a Server: by WP REST API Team – 0.3.0
WP REST API: by WP REST API Team – 2.0-beta15
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce Stripe Gateway: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.4
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

Force SSL: –
Currency: ETB (Br)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Shopping
Version: 0.3.0 – 0.4.3 is available
Author URL: http://www.themehall.com
Child Theme: ✔
Parent Theme Name: Omega
Parent Theme Version: 1.3.0
Parent Theme Author URL: https://themehall.com
WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`
```

**Comment by mikejolley** [comment]
You're not using our auth, you're using "WP REST API - OAuth 1.0a Server: by WP REST API Team – 0.3.0", so WC is not throwing this warning. Our auth methods are listed here: http://woocommerce.github.io/woocommerce-rest-api-docs/#authentication

**Comment by merhawifissehaye** [comment]
@mikejolley would you please explain in a little more detail. For all I know, I am using WooCommerce authentication method (specifically authentication over HTTP) as explained [here](http://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http).

Why is it working for the GET requests and not working for the POST requests?
Thank you

**Comment by mikejolley** [comment]
This error:

`"message": "Missing OAuth parameter oauth_token",`

Is not coming from our code. We don't check for oauth_token. I think its the REST API plugin you're running.

**Comment by merhawifissehaye** [comment]
You were right. I had OAuth1 plugin installed. Thanks.

**Comment by michaelveloso** [comment]
@merhawifissehaye I'm running into a similar issue -- GET works but POST doesn't when using Postman with OAuth 1.0. Would you mind letting me know what you did to fix it?

**Comment by merhawifissehaye** [comment]
If you are using http:// instead of https:// 

set the authorization option to OAuth1.0. Enter your consumer key and consumer secret. Choose the Encode OAuth signature checkbox. In the body tab: choose the raw radio button and change Text to JSON (application/json) and enter your data as:

`{
	"email": "somerandomeemail@email.com",
	"password": "password"
}`

**Comment by michaelveloso** [comment]
That worked, thanks! It was the "Add params to header" checkbox that I was missing.

**Comment by HarounOujihi** [comment]
Hi, i use woocommerce api on ionic app
(using nodejs module https://www.npmjs.com/package/woocommerce-api )
**# and all GET  works but POST dosen't !!**
i've tried :

```
wc.postAsync('products', data).then((data) =>  {
       ...
}, (err) => { console.log('Error : ', err);  });
```

and i get 401 error
my you help me to fix that ?
thanks :)

**Comment by sudipta-pran** [comment]
@mfissehaye I am having problems making a demo order from POSTMAN. I see you're sending username and password in the BODY. If thats the case where should we pass the actual order data? Is it required to get a user logged-in in the third party app to make an order?
