### ISSUE TITLE
Error-message issue when disabling the field label text

### ISSUE THREAD

**Issue by sepi2048** [woocommerce/woocommerce#12090]
## EXPLANATION OF THE ISSUE

When using Woocommerce 2.6.4 the field name of required fields are not shown in the error-msg when the field label text is disabled. 

## STEPS TO REPRODUCE THE ISSUE

```
add_filter( 'woocommerce_checkout_fields' , 'custom_wc_checkout_fields' );

function custom_wc_checkout_fields( $fields ) {

    // Remove Label text
    $fields['billing']['billing_first_name']['label'] = false;

    return $fields;
}
```

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
This is to be expected; the label text is the displayed label for that field. If you're hiding them, use CSS, not PHP.

**Comment by sepi2048** [comment]
If wanting to customize the error msg like this:

```
add_action('woocommerce_checkout_process', 'my_custom_checkout_field_process'); 

function my_custom_checkout_field_process() { 
    // Check if set, if its not set add an error. 
    if ( ! $_POST['billing_first_name'] ) wc_add_notice( __( '<li>Must have <strong>First Name</strong>
} 

```
How can I hide/disable the original "Billing First Name is required" error msg?

**Comment by mikejolley** [comment]
Why not translate the original message? Also there are template to control notice html.

**Comment by sepi2048** [comment]
I would like to remove the "Billing" prefix from the error-msg, ex. "**Billing** First Name is required", will this be possible if using i.e. loco translate plugin?

**Comment by mikejolley** [comment]
Should be yes.
