### ISSUE TITLE
Translation typo. Zero instead of o

### ISSUE THREAD

**Issue by AndreasFurster** [woocommerce/woocommerce#12094]
## EXPLANATION OF THE ISSUE

Version: 2.6.4

In the dutch translation at the add-on page there is this sentence:
"We bevelen Storefront aan, het **0**fficiële WooCommerce thema."

The o in Official is a zero.

**Comment by mikejolley** [comment]
This can be fixed on https://translate.wordpress.org/projects/wp-plugins/woocommerce - we don't host the translations in this repo :)
