### ISSUE TITLE
Special "Flat Rate" for Cash On Delivery payment option is missing.

### ISSUE THREAD

**Issue by zbostanoglu** [woocommerce/woocommerce#12097]
## EXPLANATION OF THE ISSUE

Version  2.6.4: When COD payment is selected in our country cargo is calculated as Cargo cost + Cash withdrawal fee = COD cargo cost.

This was possible in previous version of cargo section.

Another issue; when check out option is selected by the customer, payment method shall be asked first then cargo cost shall be calculated as per relevant payment method.

For instance if payment with credit card is selected then standard flat rate shall be added or
if COD is selected COD cargo rate shall be added to the product(s) total.
Please consider this issue when updating cargo section.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
This has never been a feature of COD. COD is a payment method, so it doesn't affect shipping costs and never has done. Maybe you're confusing it with an extension.
