### ISSUE TITLE
The list of shipping methods at the checkout doesn't refresh on updating post code

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce#12104]
## EXPLANATION OF THE ISSUE

Reference: 478981-zd-woothemes

WordPress 4.6.1
WooCommerce 2.6.4

I've defined a special shipping zone for local pickup. For this zone, I've set the region (`Guernsey`) and ZIP code (`GY1*`)

![Screenshot](http://cld.wthms.co/1d8Vd+) 

Now when a user provides their address on the checkout, they select the country first, and then the post code. When they first choose the country (Guernsey), the local pickup is not available yet, as they haven't provided required post code. However, when I add the proper post code the shipping methods don't refresh, so I can still see only the global Flat Rate:

![Screenshot](http://cld.wthms.co/zMNQ+) 

To load the proper shipping methods available for this zone I have to provide the zip code, change the country, and then change it back again to let the shipping methods refresh:

![Screenshot](http://cld.wthms.co/15XiY+) 

If there are shipping zones defined through their post codes, it would be really helpful to reload related information when the post code is updated.

## STEPS TO REPRODUCE THE ISSUE

1. Add a local shipping zone with a region (`Guernsey`) and ZIP code (`GY1*`).
2. Add a shipping method to this zone (e.g. local pickup).
3. Add a product to cart, and proceed to checkout.
4. Select Guernsey from the country list and observe only global shipping methods are available (correct).
5. Add a zip code matching the local range and observe the shipping methods don't update.
6. Change the country to a different one, then back to Guernsey and see the correct shipping method was loaded this time.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://localhost/woodevsite
Site URL: http://localhost/woodevsite
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache/2.2.31 (Win32) DAV/2 mod_ssl/2.2.31 OpenSSL/1.0.2e mod_fcgid/2.3.9 mod_wsgi/3.4 Python/2.7.6 PHP/7.0.6 mod_perl/2.0.8 Perl/v5.16.3
PHP Version: 7.0.6
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/1.0.2e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.4

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #190 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Storefront
Version: 2.1.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

```

**Comment by mikejolley** [comment]
@madeincosmos  Shipping does not refresh unless you provide all required shipping fields first. You didn't have a town or state. The only reason you see a refresh after country change is so that the address fields can be updated/changed/removed based on that selection.

**Comment by madeincosmos** [comment]
Thanks! Refeshed for me after completing all of these fields. Must be something else then :)
