### ISSUE TITLE
2.6.4: "Sales by Product" report missing critical details when compared to "Sales by Date" report

### ISSUE THREAD

**Issue by lkraav** [woocommerce/woocommerce#12103]
GOAL
Get a breakdown of **net sales** (excluding taxes) of a specific product in a specific time period.

PROBLEM
"Sales by Date" report has all relevant information, but can't be filtered to a specific product.
"Sales by Product" report is missing majority of the information "Sales by Date" report has.

SOLUTION
Let's drop the neutered "Sales by Product" altogether and merge it's one key filtering feature into "Sales by Date", which has much more useful information available. Biggest challenge is probably designing the UX to include relevant controls. Date filtering bar has free space available for a product dropdown.

Your thoughts?

**Comment by mikejolley** [comment]
The biggest challenge is actually narrowing down the dataset, since sales by products looks at line items and sales by date looks at order totals. This won't be done until we introduce new order tables.

**Comment by lkraav** [comment]
Mmhm OK. I've also come to realize that "Sales by Product" may already do exactly what I wanted - simply tally up the "net total" without taxes. But I'm sort of internally scared to draw conclusions on this report alone, because I could use mental assurance on a "gross sales with taxes" total next to it, so I could cross-reference.

So all in all, issue is probably still valid. "Sales by Date" is a better === more detailed and helpful report.

**Comment by mikejolley** [comment]
Closed in favour of #13094
