### ISSUE TITLE
paypal order processing issues

### ISSUE THREAD

**Issue by nattlyharris** [woocommerce/woocommerce#12107]
## EXPLANATION OF THE ISSUE
Dear woo commerce /github,

I have a couple of issues with my online shop - please could you help? The first issue is the most important one, as customers are not receiving their emails  and order note instructions automatically. I have checked my php mail function and all is working normally. 

http://www.starplannersastrology.com
wc version 2.6.4
wp version 4.6.1

First issue:
customer order showing Paypal payment as 'pending' despite payment going through, hence no customer or admin emails are being generated for orders. Customer emails are generated after I manually update the order from 'pending' to 'processing', but this is not ideal for virtual products, or any products!

Second issue:
orders being automatically cancelled after an hour if I enable stock control, generating an admin email saying order cancelled, even through payment has gone through. I have disabled stock control and this has stopped the problem, but I would like stock control!

third issue:
using paypal express checkout was causing a problem with enabling shipping calculations on basket page - error message shows that 'you must enter a shipping address' after payment has gone through. I have corrected this by disabling shipping calculations on basket page but I would like this feature!

## STEPS TO REPRODUCE THE ISSUE

Buy a Trilogy of Astrological Energies Module at http://www.starplannersastrology.com/product/trilogy-astrological-energies-session/

Complete checkout

Wait and receive no customer emails without manually updating order status to processing.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://www.starplannersastrology.com
Site URL: http://www.starplannersastrology.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.26
PHP Post Max Size: 64 MB
PHP Time Limit: 50000
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.50 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (23) ###

Contact Bank Lite Edition: by Tech Banker – 2.1.29
Cookie Notice: by dFactory – 1.2.36.1
Custom CSS: by FRESHFACE – 1.3.4
Custom Facebook Feed: by Smash Balloon – 2.4.5
Custom Style: by Wolfgang Häfelinger – 1.0
Easy WP SMTP: by wpecommerce – 1.2.3
Google Analytics by MonsterInsights: by MonsterInsights – 5.5.3
MailChimp for WordPress: by ibericode – 4.0.6
Maintenance: by fruitfulcode – 3.1.1
Meta Slider: by Matcha Labs – 3.3.7
Monkeyman Rewrite Analyzer: by Jan Fabry – 1.0
Quest Plus: by Pace Themes – 1.4.9
Rewrite: by takien – 0.2.1
Testimonial Rotator: by Hal Gatewood – 2.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.23

Very Simple Custom Style: by Guido van der Leest – 2.4
Widget Shortcode: by Hassan Derakhshandeh – 0.2.8
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce: by WooThemes – 2.6.4
Yoast SEO: by Team Yoast – 3.7.0
WP Fastest Cache: by Emre Vona – 0.8.6.1
Wp Mail Bank: by Tech Banker – 1.47
WP Smush: by WPMU DEV – 2.4.5

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #6574 - /shop/
Basket: #2109 - /basket/
Checkout: #2110 - /checkout/
My Account: #2111 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Quest
Version: 1.4.9
Author URL: http://pacethemes.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by mikejolley** [comment]
See https://docs.woocommerce.com/document/paypal-standard/#section-9 about your order pending issues and note you can also enable PDT:

https://docs.woocommerce.com/document/paypal-standard/#why-dont-customers-see-the-link-to-download-products-after-paying-and-getting-redirected-back-to-my-website

PDT is a fallback if IPN does not work on your server. But thats a server issue.
