### ISSUE TITLE
Minimum price filter widget showing products with lower than minimum price

### ISSUE THREAD

**Issue by lukeliasi** [woocommerce/woocommerce#12110]
## EXPLANATION OF THE ISSUE

When I have a product with a decimal price, eg: £9.55 it still shows up if the minimum price filter is set to £10.

## STEPS TO REPRODUCE THE ISSUE

Create two products in a category with two different prices, for example £9.55 and £12. Set the minimum filter price to £10 and the £9.55 product will still show. All decimals more than 9.5 will be rounded up to the nearest decimal place (in this case £10). I think they should be rounded down? Especially considering if you have smaller valued products at say 1.55 and 2.50 - with 1.55 being rounded up to 2 that product is being classified as 0.45 more which is 29% of it's value.

I have tested this on Storefront theme with default WooCommerce price filter widget.

May be related to: #11791

**Comment by mikejolley** [comment]
Is related, and will be in next update.
