### ISSUE TITLE
API :: Refunds :: Gateway error

### ISSUE THREAD

**Issue by eric239** [woocommerce/woocommerce#12115]
## EXPLANATION OF THE ISSUE

Trying to programmatically create a refund without explicitly setting `api_refund` parameter to `false` consistently fails with `500` error. Refunding the same order via Woo Dashboard promptly triggers Stripe refund.

## STEPS TO REPRODUCE THE ISSUE

```
curl -X "POST" "https://ensorings.com/wp-json/wc/v1/orders/37863/refunds" \
     -H "Content-Type: application/json; charset=utf-8" \
     -d "{\"amount\":\"1.00\",\"reason\":\"test\"}"
```
responds with
```
HTTP/1.1 500 Internal Server Error

{"code":"woocommerce_rest_create_order_refund_api_failed","message":"An error occurred while attempting to create the refund using the payment gateway API.","data":500}
```

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://woogarda.com
Site URL: http://woogarda.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.24
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (6) ###

Jetpack by WordPress.com: by Automattic – 4.3.2
MOJO Marketplace: by Mike Hansen – 1.0.4
WooCommerce PayPal Powered by Braintree Gateway: by WooThemes – 1.2.5
WooCommerce Stripe Gateway: by Automattic – 3.0.5
WooCommerce: by WooThemes – 2.6.4
WooCommerce Helper: by WooCommerce – 1.7.1

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront
Version: 2.1.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by mikejolley** [comment]
Provide the error log entry related to this.

**Comment by eric239** [comment]
@mikejolley please help me with "log entry" as I'm new to WooCommerce and not sure which log(s) we're talking about.
My instance is hosted by BlueHost. In `WooCommerce -> Settings -> Logs` I have two choices:
* `test-log.log`  -- completely empty (confirmed the actual file on disk is empty as well)
* `woocommerce-gateway-stripe-<guid>.log` -- this doesn't show anything for failed requests presumably due to the very issue being discussed; it does show records for successful charges and refunds made via admin UI.

I also checked apache access log
```
a.b.c.d - - [18/Oct/2016:09:39:50 -0600] "POST /wp-json/wc/v1/orders/46/refunds HTTP/1.1" 500 6122 "-" "Paw/3.0.12 (Macintosh; OS X/10.10.5) GCDHTTPRequest"
```
-- nothing interesting, as well as apache error log which had nothing for that request.

So I'm baffled as to where should I look for the relevant logging data.

**Comment by mikejolley** [comment]
PHP error logs. You had an error 500.

**Comment by eric239** [comment]
@mikejolley -- well I certainly know I had `500` error.

The PHP error log (up to the best of my knowledge -- the file path is `$site_home/public_html/error_log`) doesn't contain anything seemingly relevant, just the below repeated several times (and on different date)
```
[11-Oct-2016 12:57:32 America/Denver] PHP Warning:  copy(/tmp/wp-cli-cacert.pem): failed to open stream: Permission denied in phar:///usr/local/bin/wp/php/utils.php on line 26
```

So still baffling...

**Comment by mikejolley** [comment]
Enable WP_DEBUG (https://codex.wordpress.org/Debugging_in_WordPress) and trigger the error again, then look again at the error log. It may be in wp-content/ directory. Error 500 usually hides the 'real' fatal error.

**Comment by mikejolley** [comment]
Ok, I found that the API triggers error 500 if the gateway cannot refund the amount for any reason. I did my own test using Stripe (sandbox) with just api_refund and amount and it worked correctly without error. Did the test with WC 2.6 and master - no issues on either.

Enable your gateways logging function if it has one (stripe does) for more details if it were a gateway API error. Closing as it seems the API itself has no issue here.

**Comment by eric239** [comment]
@mikejolley please re-open the issue. I re-ran the test with WP_DEBUG set, and got this response from refund creation API:
```
<b>Notice</b>:  Undefined variable: order_id in <b>/home3/woogarda/public_html/wp-content/plugins/woocommerce/includes/api/class-wc-rest-order-refunds-controller.php</b> on line <b>303</b><br />
{"code":"woocommerce_rest_create_order_refund_api_failed","message":"An error occurred while attempting to create the refund using the payment gateway API.","data":500}
```

**Comment by claudiosmweb** [comment]
@eric239 looks related to this other issue: https://github.com/woocommerce/woocommerce/issues/12102#issuecomment-254790763

**Comment by claudiosmweb** [comment]
@eric239 sorry, already fixed in https://github.com/woocommerce/woocommerce/commit/74484c70093bb59f71dbc13c3247080341f5ec32
Will be included into 2.6.5

**Comment by eric239** [comment]
I see, thanks @claudiosmweb 

Do you guys have an ETA for 2.6.5 release?

**Comment by mikejolley** [comment]
Today probabaly.
