### ISSUE TITLE
Rest API: Product Category Images cannot be deleted

### ISSUE THREAD

**Issue by danielhuesken** [woocommerce/woocommerce#12119]
We cannot delete product Category Images over the Rest API.

Post empty 'image' will not work and set image['id'] = 0 also not work.

**Comment by mikejolley** [comment]
Confirmed - adding to 2.7 @claudiosmweb. Maybe this should support `null`.

**Comment by danielhuesken** [comment]
Ich habe das ähnliche Problem beim Löschen von Produktbildern. A attachemtn_id of 0 will not delete or unset the image.
