### ISSUE TITLE
Incorrect data returned by WooCommerce 2.6 API

### ISSUE THREAD

**Issue by mjulapalli** [woocommerce/woocommerce#12114]
## EXPLANATION OF THE ISSUE

Since https://richardsonwesternwear.com upgraded to WooCommerce version 2.6 (currently on 2.6.4), we are no longer able to programmatically change the "manage_stock" flag on the product level ("Enable stock management at product level"). 

## STEPS TO REPRODUCE THE ISSUE

GET request to https://richardsonwesternwear.com/wp-json/wc/v1/products/228 produces the following JSON (please note, in particular, `"manage_stock"=>false`):

```javascript
{
  "id"=>228,
  "name"=>"Test by Sku IQ",
  "slug"=>"test-by-sku-iq",
  "permalink"=>"https://richardsonwesternwear.com/product/test-by-sku-iq/",
  "date_created"=>"2016-10-14T00:40:12",
  "date_modified"=>"2016-10-17T22:55:02",
  "type"=>"simple",
  "status"=>"private",
  "featured"=>false,
  "catalog_visibility"=>"visible",
  "description"=>"<p>This is a test.</p>\n",
  "short_description"=>"",
  "sku"=>"0054702000",
  "price"=>"1",
  "regular_price"=>"1",
  "sale_price"=>"",
  "date_on_sale_from"=>"",
  "date_on_sale_to"=>"",
  "price_html"=>"<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>1.00</span>",
  "on_sale"=>false,
  "purchasable"=>true,
  "total_sales"=>0,
  "virtual"=>false,
  "downloadable"=>false,
  "downloads"=>[
    
  ],
  "download_limit"=>-1,
  "download_expiry"=>-1,
  "download_type"=>"standard",
  "external_url"=>"",
  "button_text"=>"",
  "tax_status"=>"taxable",
  "tax_class"=>"",
  "manage_stock"=>false,
  "stock_quantity"=>nil,
  "in_stock"=>true,
  "backorders"=>"no",
  "backorders_allowed"=>false,
  "backordered"=>false,
  "sold_individually"=>false,
  "weight"=>"",
  "dimensions"=>{
    "length"=>"",
    "width"=>"",
    "height"=>""
  },
  "shipping_required"=>true,
  "shipping_taxable"=>true,
  "shipping_class"=>"",
  "shipping_class_id"=>0,
  "reviews_allowed"=>true,
  "average_rating"=>"0.00",
  "rating_count"=>0,
  "related_ids"=>[
    
  ],
  "upsell_ids"=>[
    
  ],
  "cross_sell_ids"=>[
    
  ],
  "parent_id"=>0,
  "purchase_note"=>"",
  "categories"=>[
    
  ],
  "tags"=>[
    
  ],
  "images"=>[
    {
      "id"=>0,
      "date_created"=>"2016-10-17T17:55:49",
      "date_modified"=>"2016-10-17T17:55:49",
      "src"=>"https://richardsonwesternwear.com/wp-content/plugins/woocommerce/assets/images/placeholder.png",
      "name"=>"Placeholder",
      "alt"=>"Placeholder",
      "position"=>0
    }
  ],
  "attributes"=>[
    
  ],
  "default_attributes"=>[
    
  ],
  "variations"=>[
    
  ],
  "grouped_products"=>[
    
  ],
  "menu_order"=>0,
  "_links"=>{
    "self"=>[
      {
        "href"=>"https://richardsonwesternwear.com/wp-json/wc/v1/products/228"
      }
    ],
    "collection"=>[
      {
        "href"=>"https://richardsonwesternwear.com/wp-json/wc/v1/products"
      }
    ]
  }
}
```

PUT request to https://richardsonwesternwear.com/wp-json/wc/v1/products/228 with the parameters `{"regular_price":5,"manage_stock":true}` produces the following JSON:

```javascript
{
  "id"=>228,
  "name"=>"Test by Sku IQ",
  "slug"=>"test-by-sku-iq",
  "permalink"=>"https://richardsonwesternwear.com/product/test-by-sku-iq/",
  "date_created"=>"2016-10-14T00:40:12",
  "date_modified"=>"2016-10-17T23:04:53",
  "type"=>"simple",
  "status"=>"private",
  "featured"=>false,
  "catalog_visibility"=>"visible",
  "description"=>"<p>This is a test.</p>\n",
  "short_description"=>"",
  "sku"=>"0054702000",
  "price"=>"5",
  "regular_price"=>"5",
  "sale_price"=>"",
  "date_on_sale_from"=>"",
  "date_on_sale_to"=>"",
  "price_html"=>"<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>5.00</span>",
  "on_sale"=>false,
  "purchasable"=>true,
  "total_sales"=>0,
  "virtual"=>false,
  "downloadable"=>false,
  "downloads"=>[
    
  ],
  "download_limit"=>-1,
  "download_expiry"=>-1,
  "download_type"=>"standard",
  "external_url"=>"",
  "button_text"=>"",
  "tax_status"=>"taxable",
  "tax_class"=>"",
  "manage_stock"=>false,
  "stock_quantity"=>nil,
  "in_stock"=>true,
  "backorders"=>"no",
  "backorders_allowed"=>false,
  "backordered"=>false,
  "sold_individually"=>false,
  "weight"=>"",
  "dimensions"=>{
    "length"=>"",
    "width"=>"",
    "height"=>""
  },
  "shipping_required"=>true,
  "shipping_taxable"=>true,
  "shipping_class"=>"",
  "shipping_class_id"=>0,
  "reviews_allowed"=>true,
  "average_rating"=>"0.00",
  "rating_count"=>0,
  "related_ids"=>[
    
  ],
  "upsell_ids"=>[
    
  ],
  "cross_sell_ids"=>[
    
  ],
  "parent_id"=>0,
  "purchase_note"=>"",
  "categories"=>[
    
  ],
  "tags"=>[
    
  ],
  "images"=>[
    {
      "id"=>0,
      "date_created"=>"2016-10-17T18:04:53",
      "date_modified"=>"2016-10-17T18:04:53",
      "src"=>"https://richardsonwesternwear.com/wp-content/plugins/woocommerce/assets/images/placeholder.png",
      "name"=>"Placeholder",
      "alt"=>"Placeholder",
      "position"=>0
    }
  ],
  "attributes"=>[
    
  ],
  "default_attributes"=>[
    
  ],
  "variations"=>[
    
  ],
  "grouped_products"=>[
    
  ],
  "menu_order"=>0,
  "_links"=>{
    "self"=>[
      {
        "href"=>"https://richardsonwesternwear.com/wp-json/wc/v1/products/228"
      }
    ],
    "collection"=>[
      {
        "href"=>"https://richardsonwesternwear.com/wp-json/wc/v1/products"
      }
    ]
  }
}
```

You'll notice the price has been changed (showing that the request and credentials are valid), but `manage_stock` has not flipped.

**Comment by claudiosmweb** [comment]
Have you enabled the "Manage stock" option?
Because is all based if you have enabled or not this option: https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L1178-L1187

**Comment by mjulapalli** [comment]
Yes, it's enabled:

<img width="667" alt="image 2016-10-17 at 8 58 25 pm" src="https://cloud.githubusercontent.com/assets/3740181/19463894/a9075ed6-94ac-11e6-8305-bc441ba63392.png">

**Comment by mikejolley** [comment]
I've tested this POST on master, 2.6.4 and 2.6.5 - the issue doesn't occur on any and manage_stock updates as it should. I'm testing with [Insomnia](https://insomnia.rest/) client. This is a clean install with no extensions - I'd suggest you debug your API issue by disabling extensions and checking if other products are affected, and maybe adding some logging of your own to see whats being posted.

I am closing this as I'm unable to replicate under any version.

**Comment by mjulapalli** [comment]
Hi Mike,

To give you some background, we (http://www.skuiq.com) link eCommerce data to POS.  We've been using the WooCommerce API for a while now.  The jump to version 2.6 seems to have broken calls for other clients as well (but not all clients; it's nondeterministic).  Was hoping there is something simple going on.  If you could try the call with the specific website referenced in the ticket (https://richardsonwesternwear.com) and the specific product (ID: 228).  This website and product are representative of others we are seeing.  

Mohith

**Comment by mikejolley** [comment]
@mjulapalli I don't see anything obvious in the code, other than the setting @claudiosmweb pointed out.

**Comment by mjulapalli** [comment]
@mikejolley Hoping you can take another look at this.  Happy to provide examples from other clients.  If we can't make updating inventory work, we're going to lose clients over this (https://twitter.com/oobdigital/status/788406352590745602).

**Comment by mikejolley** [comment]
@mjulapalli I don't know if you're aware or not, but we don't have access to client sites - they are self hosted. It would be good to test your calls (just POST to the endpoint with manage_stock only) with another client just to rule out your app code as the problem. As I said, I did test this on several versions of WC without issue and see nothing else in core that would block it being updated.
