### ISSUE TITLE
Not sending mail after order when payment is under review of paypal.

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#12117]
Normally when customer make an order woocommerece send an email. This works fine.

I had a unique case where after customer payed in Paypal - the payment was marked underreview and WC changed the order to ON HOLD. Now (a month later), the IPN is completed after paypal got the money - the the order changed to processing but no email was sent to the customer 

![12](https://cloud.githubusercontent.com/assets/22069599/19474833/15f80652-953a-11e6-909d-304fe2f33876.png)

I know that email was not sent because I receieve a copy of the email sent to the customer... and in this time i didn't receive anything. Also, I have WP Mail Log installed and it doesn't show an email for this order.

This looks like a bug.

**EDIT:**
I checked the log... an email was sent at 2016-09-07  notifying the order was cancelled. That is OK because it was canceled at start.
But why it doesn't send a new email with order confirmation if the IPN is updated?!

**Comment by mikejolley** [comment]
Without context or system status report there is no way for me to replicate this.

**Comment by UserName011** [comment]
@mikejolley tell me what do you need?
I also see something that I never saw before.. The order has a lock on it:
![12](https://cloud.githubusercontent.com/assets/22069599/19475635/d2f22b36-953d-11e6-9cd6-5b70e5014018.png)

not sure if it's related.

**Comment by mikejolley** [comment]
Show me email settings so I can see whats on/off?

**Comment by UserName011** [comment]
@mikejolley 
Here:
![455](https://cloud.githubusercontent.com/assets/22069599/19476045/d78bc86c-953f-11e6-8b7c-9028263c624d.png)

Let me say again that the email on the cancellation was sent as it should. The change of IPN happend more than a month later. Maybe there is a limit to send only one email?

**Comment by mikejolley** [comment]
There is no transition/event for onhold to processing right now https://github.com/woocommerce/woocommerce/blob/2.6.4/includes/emails/class-wc-email-customer-processing-order.php#L36

**Comment by UserName011** [comment]
Thank you mike,
Why the events are related to previous status?

If The order is changed to 'completed' from any status it should send the notification as defined in the settings for 'completed'. Same for any other status... 
This is what a user expect when he defines it in the Email Settings.

If you leave it as it is now and bind the event between previous status and current status than you should change the Email Setting screen so that the user will understand this definition.. meaning that he will know that the email will be sent only in specific cases (Could be a note in the window opened after clicking configure per status).
