### ISSUE TITLE
I can't publish images and can't edit..

### ISSUE THREAD

**Issue by Usamawp** [woocommerce/woocommerce#12124]
Sir/Madam,
                I can't edit the products that was I added earlier.  If I clicked on "Edit"(Screenshot 1) It will directly goes to the website (Screenshot 2) 
I can't add the product. If I clicked on "save" or "publish" (Screenshot 3) It will directly goes to the website (Screenshot 4) 
 how can I resolve this.. I am in big trouble, Please help me to relolve this.. 
(1)
![1](https://cloud.githubusercontent.com/assets/22919270/19490508/10576564-958d-11e6-8d7b-afdb83da27a3.jpg)
(2)
![2](https://cloud.githubusercontent.com/assets/22919270/19490518/1556a5ac-958d-11e6-9276-8ddb2e6ba35b.jpg)
(3)
![3](https://cloud.githubusercontent.com/assets/22919270/19490531/1c7ce3be-958d-11e6-9ae6-0e3a86b4e907.jpg)
(4)
![4](https://cloud.githubusercontent.com/assets/22919270/19490539/28740242-958d-11e6-8933-dde294fb86db.jpg)

**Comment by mikejolley** [comment]
This isn't something reproducible so I'd recommend disabling all plugins and installing woocommerce again via FTP in case files are missing (I notice missing icons in backend). The publish/save button on product pages is powered by WordPress itself and is identical to the page/post screens.

**Comment by Usamawp** [comment]
Problem Resolved sir, Uninstalled and Installed again.. now its working good... thank you.. :)

**Comment by Usamawp** [comment]
Problem Resolved sir, Uninstalled and Installed again.. now its working good... thank you.. :)
