### ISSUE TITLE
Invalid emails accepted on /my-account/edit-account/

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#12126]
## EXPLANATION OF THE ISSUE

It appears that if the tld is left off of the domain on an email address on the Account Details page (like test@test), the form accepts this as valid, somewhat. 
## STEPS TO REPRODUCE THE ISSUE
1. Go to `/my-account/edit-account/`
2. Enter your email address as `test@test`
3. Submit the form
4. Receive no error.

This appears to be due to `sanitize_email` being used [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L181), which will return an empty string if the email address is invalid. This causes [this test](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L207) to be skipped.

Since the test at like 207 is skipped, the email is never actually updated even though a success notice is displayed.

Tested in most recent versions of Chrome, FireFox and Safari on El Capitan, all allow `test@test` as a valid email to be passed for the field.
## SYSTEM STATUS REPORT

```
WC Version: 2.6.4
WP Version: 4.6.1
```

Reported in 482165-zd-woothemes.

**Comment by RiaanKnoetze** [comment]
Running WC 2.6.7 and WP 4.6.1, I'm still seeing the same thing on local. Here's a screencast: http://cld.wthms.co/Syp3/fahWOdCv

**Comment by mikejolley** [comment]
Re-applied for next fix release.
