### ISSUE TITLE
On Product pages there is no page options tab ( I dont want the side bar to show up and I want to hide the page title) also the footer appearance Hide show list isn't functioning the same as all the other pages in the theme.  

### ISSUE THREAD

**Issue by Infinite222** [woocommerce/woocommerce#12122]
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by Infinite222** [comment]
Hey,  I noticed that there is no page options tab in the products pages. Its a woo commerce store in the Themify ultra theme. 
also in the footer the hide and show menu is not responding the same way as the rest of the theme. I have checked hide site logo and it is showing up as text anyway. 
Thanks, have a great day

**Comment by mikejolley** [comment]
Products are not pages - so you won't see the page meta box. Handle sidebars/templates via the theme or css.
