### ISSUE TITLE
WC_Abstract_Order::calculate_totals() ignores any taxes applied to fee line items

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/woocommerce#12128]
https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L1267-L1269

This issue only becomes a apparent when trying to add a fee to an order after it has been created, normal orders processed via checkout are calculated correctly as the totals calculations seem to be done in WC_Cart

**Comment by mikejolley** [comment]
The function you linked to does the taxes prior - see https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L1134

But it looks like the tax totals are not included in the final calc.

**Comment by mikejolley** [comment]
False alarm, it's all totalled up fine here https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L1207-L1212
