### ISSUE TITLE
Error on the product edit page

### ISSUE THREAD

**Issue by 33Evgenyy33** [woocommerce/woocommerce#12139]
## EXPLANATION OF THE ISSUE

wordpress 4.6.1
woocommerce 2.6.5

Fatal error: Call to a member function get_method_id() on array in /var/www/euroroaming.ru/htdocs/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 1352

https://euroroaming.ru/wp-content/uploads/2016/10/Screenshot_4.jpg

## STEPS TO REPRODUCE THE ISSUE

Error after update plugin
 
## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://euroroaming.ru
Site URL: https://euroroaming.ru
WC Version: 2.6.5
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU

### Server Environment ###

Server Info: nginx/1.9.13
PHP Version: 5.6.17-1~dotdeb+7.1
PHP Post Max Size: 32 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.26.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ❌ Временная зона по умолчанию Europe/London — должна быть UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Удалить запись: ✔
Удалённое получение: ✔

### Database ###

WC Database Version: 2.6.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (40) ###

Gravity Forms: от rocketgenius – 2.0.7.13
AffiliateWP: от AffiliateWP
LLC – 1.9.3.1

Ultimate Addons for Visual Composer: от Brainstorm Force – 3.16.7
Admin Columns Pro: от AdminColumns.com – 3.8.8
Advanced Categories Widget: от Darrin Boutote – 1.2
AffiliateWP - Affiliate Info: от Pippin Williamson and Andrew Munro – 1.0.3
AffiliateWP - Affiliate Product Rates: от Pippin Williamson and Andrew Munro – 1.0.4
AffiliateWP - Show Affiliate Coupons: от Pippin Williamson and Andrew Munro – 1.0.4
BackupBuddy: от iThemes – 7.2.0.6
Admin Columns - WooCommerce add-on: от Codepress – 1.4
Category Sticky Post: от Tom McFarlin – 2.9.0
Cyr to Lat enhanced: от Sol
Sergey Biryukov
Nikolay Karev
Dmitri Gogelia – 3.5

Duplicate Page: от mndpsingh287 – 2.1
Easy Theme and Plugin Upgrades: от Chris Jean – 2.0.0
Go Pricing - WordPress Responsive Pricing Tables: от Granth – 3.3.3
Image Widget: от Modern Tribe
Inc. – 4.2.2

WPBakery Visual Composer: от Michael M - WPBakery.com – 4.12.1
Members: от Justin Tadlock – 1.1.2
My SMTP WP: от Valerio Souza – 1.3.2
Slider Revolution: от ThemePunch – 5.2.6
Sabai Discuss: от onokazu – 1.3.34
Sabai: от onokazu – 1.3.34
TinyMCE Advanced: от Andrew Ozz – 4.4.1
UpSolution Header Builder: от UpSolution – 1.0
User Switching: от John Blackbourn – 1.0.9
Woo Checkout for Digital Goods: от Multidots – 7
Woocommerce Advanced Shipping: от Jeroen Sormani – 1.0.10
WooCommerce Checkout Add-Ons: от WooThemes / SkyVerge – 1.8.2 – 1.8.3 доступно
WooCommerce Checkout Field Editor: от WooThemes – 1.5.1
WooCommerce Direct Checkout: от Terry Tsang – 1.1.2
WooCommerce Google Analytics Pro: от WooThemes / SkyVerge – 1.1.4
WooCommerce Order Status Manager: от WooThemes / SkyVerge – 1.6.2 – 1.6.3 доступно
WooCommerce PayTravel: от Deligence Technologies Pvt Ltd. – 1.0.0
WooCommerce Point of Sale: от Actuality Extensions – 3.1.6.5
WooCommerce Local Pickup Plus: от WooThemes / SkyVerge – 1.13.2
WooCommerce: от WooThemes – 2.6.5
Yoast SEO Premium: от Команда Yoast – 3.7.1
WP Store Locator: от Tijmen Smit – 2.2.4
WP Super Cache: от Automattic – 1.4.8
Яндекс.Касса для WooCommerce: от Yandex.Money – 2.3.1

### Settings ###

Force SSL: –
Currency: RUB (₽)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Ссылка магазина: #18397 - /shop/
Корзина: #18398 - /cart/
Оформление заказа: #18399 - /checkout/
Мой аккаунт: ❌ Страница не содержит шорткода: [woocommerce_my_account]

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Zephyr Child
Version: 1.0
Author URL: http://us-themes.com/
Child Theme: ✔
Parent Theme Name: Zephyr
Parent Theme Version: 3.7
Parent Theme Author URL: http://us-themes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: Zephyr-child/woocommerce/archive-product.php
Zephyr-child/woocommerce/checkout/thankyou.php
Zephyr-child/woocommerce/content-single-product.php
Zephyr-child/woocommerce/emails/admin-cancelled-order.php
Zephyr-child/woocommerce/emails/admin-failed-order.php
Zephyr-child/woocommerce/emails/admin-new-order.php
Zephyr-child/woocommerce/emails/customer-completed-order.php
Zephyr-child/woocommerce/emails/customer-invoice.php
Zephyr-child/woocommerce/emails/customer-new-account.php
Zephyr-child/woocommerce/emails/customer-note.php
Zephyr-child/woocommerce/emails/customer-processing-order.php
Zephyr-child/woocommerce/emails/customer-refunded-order.php
Zephyr-child/woocommerce/emails/customer-reset-password.php
Zephyr-child/woocommerce/emails/email-addresses.php
Zephyr-child/woocommerce/emails/email-customer-details.php
Zephyr-child/woocommerce/emails/email-footer.php
Zephyr-child/woocommerce/emails/email-header.php
Zephyr-child/woocommerce/emails/email-order-details.php
Zephyr-child/woocommerce/emails/email-order-items.php
Zephyr-child/woocommerce/emails/email-styles.php
Zephyr-child/woocommerce/emails/plain/admin-cancelled-order.php
Zephyr-child/woocommerce/emails/plain/admin-failed-order.php
Zephyr-child/woocommerce/emails/plain/admin-new-order.php
Zephyr-child/woocommerce/emails/plain/customer-completed-order.php
Zephyr-child/woocommerce/emails/plain/customer-invoice.php
Zephyr-child/woocommerce/emails/plain/customer-new-account.php
Zephyr-child/woocommerce/emails/plain/customer-note.php
Zephyr-child/woocommerce/emails/plain/customer-processing-order.php
Zephyr-child/woocommerce/emails/plain/customer-refunded-order.php
Zephyr-child/woocommerce/emails/plain/customer-reset-password.php
Zephyr-child/woocommerce/emails/plain/email-addresses.php
Zephyr-child/woocommerce/emails/plain/email-customer-details.php
Zephyr-child/woocommerce/emails/plain/email-order-details.php
Zephyr-child/woocommerce/emails/plain/email-order-items.php
Zephyr-child/woocommerce/myaccount/navigation.php
Zephyr-child/woocommerce/single-product.php

`

**Comment by zsitro** [comment]
I can't believe I actually run into this problem an hour ago and there's already a release so I can update 👍
