### ISSUE TITLE
How do I get download links from the REST API

### ISSUE THREAD

**Issue by merhawifissehaye** [woocommerce/woocommerce#12130]
I am writing an Android client that fetches data from a woocommerce powered web backend.
Once I put order (sending POST request with endpoint `/wp/v1/orders/<id>...` how can I get the temporary/expiring download links to the products in the order?

I searched a lot on the web and I couldn't get anything relevant. The only option I have seems to me that I need to reproduce whatever WooCommerce is trying to do in the core code to generate temporary link to downloadable products.

Any suggestions please?

**Comment by mikejolley** [comment]
You can obtain customer downloads with this endpoint http://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-customer-downloads, not for a specific order currently.

**Comment by merhawifissehaye** [comment]
The customer-downloads endpoint only returns the downloads previously made by the customer on the web. My case is a little different. I am creating the order using rest-api. When I try to get customer-downloads using the customer id from the order info I created using rest-api, it returns an empty array.

Even the download links you get from product details is denied access. It throws 403 Forbidden error. As I dig into wocommerce core, I learned that it does some more stuff to secure download links and generate expiring links.

**Comment by mikejolley** [comment]
Order statuses can have an effect - maybe they are not generated yet?

**Comment by merhawifissehaye** [comment]
I don't understand @mikejolley do I generate them manually? Or are they automatically generated when I update the status of the order?

**Comment by mikejolley** [comment]
Auto on status change. Processing/complete I believe.

**Comment by merhawifissehaye** [comment]
I changed the status to completed. But I am not getting the temporary links. I couldn't believe this is not a common issue. I couldn't find anything similar on the web

**Comment by mikejolley** [comment]
Have you checked admin backend for the links?

**Comment by merhawifissehaye** [comment]
The link in the product page gives 403 Forbidden error. And there are no product links in the orders page

**Comment by mikejolley** [comment]
Orders screen has a permissions meta box. Look there.
