### ISSUE TITLE
customer login for mobile app

### ISSUE THREAD

**Issue by rameshvoltella** [woocommerce/woocommerce#12131]
How to make a login module for created customers using woocommerce for native mobile app (Android/ios) ?

Hi am using latest woocommerce plugin

i follow [woocommerce-rest-api-docs](http://woocommerce.github.io/woocommerce-rest-api-docs/?shell#introduction)

API Version - v1
WC Version - 2.6.x or later
WP Version - 4.4 or later

All the api call was successful (Product,category,review,create customer etc)

Now am stuck at a portion where i need to login a existing customer. but i don't find any end point of login module to solve this issue. While researching i find issue  [#6816](https://github.com/woocommerce/woocommerce/issues/6816), [#6126](https://github.com/woocommerce/woocommerce/issues/6126)and [#6133](https://github.com/woocommerce/woocommerce/pull/6133) but did not provided a efficient way to login a customer.Noting is documented on [woocommerce-rest-api-docs](http://woocommerce.github.io/woocommerce-rest-api-docs/?shell#introduction) for login module.

Am developing android application shopping site is in **http**.  The  oauth (1.0 one legged) all are working fine i just want to find a method to login a existing customer to the app.

if i miss any thing please help me how to fix the issue

**Comment by mikejolley** [comment]
User login is not something our API is intended for. It does not facilitate this in any way. You'd need your own endpoints to do this.

**Comment by rameshvoltella** [comment]
ok so if login module is not handled how the user chekout a product without any credentials

**Comment by rameshvoltella** [comment]
@mikejolley  ok so if login module is not handled how the user checkout a product without any credentials ? woocommerce currently doesnot support these features?.

one of api for  [retrieve-a-customer](http://woocommerce.github.io/woocommerce-rest-api-docs/?shell#retrieve-a-customer) with id or email so the entire detail of user is been fetched. is this a good way. Any one can access if they know the email address of a user.

**Comment by mikejolley** [comment]
The API is not for cart/checkout/user login. The api is for order and customer creation and editing.
