### ISSUE TITLE
Cart.js hijacking forms when used with WOOCOMMERCE_CART constant

### ISSUE THREAD

**Issue by SukcesStrony** [woocommerce/woocommerce#12138]
## EXPLANATION OF THE ISSUE

Some plugins (especially the ones which change the prices of products) require recalculating the cart contents. In order to run `WC()->cart->calculate_totals();` they need to first `define('WOOCOMMERCE_CART', true);`, which is also done in the WC core. The code to recalculate the cart becomes:
```
if(!defined('WOOCOMMERCE_CART')){
	define('WOOCOMMERCE_CART', true);
}
WC()->cart->calculate_totals();
```

Setting the `WOOCOMMERCE_CART` constant to true means, that `is_cart()` will return true. This enqueues the `cart.js` file. Let's say we're not on the Cart page (for example it's a "my account" page, because we've just logged in and the plugin changes the prices for logged in users).

The problem is, `cart.js` hijacks all form submissions, no matter if that form is actually the cart form or any other form. So, if we're on the "Edit billing address" page or even on the Cart page itself but there are other forms present, the `cart.js` will prevent any forms from submitting (excluding the cart form of course).

## HOW TO FIX THE ISSUE

The main culprit is in https://github.com/woocommerce/woocommerce/blob/c1d989df2ce62e154ca16d85e1385229739d0d12/assets/js/frontend/cart.js#L292
The selector needs to be `div.woocommerce-cart:not(.widget_product_search) > form` in order to be sure we're actually on the cart page, and in order to ensure we're targeting the proper form, it should target the `.cart` class, which is a child of the form element. This would require either adding a class for the form element (like `.cart-form`) or selecting the form element as a parent of `.cart` with jQuery (the 1st option seems a lot better).
`Cart.js` has a few other hijacks, like hijacking the Return key. This should be reviewed and scoped to include only the actual cart form, not any form there is on the page.

## WORKAROUND FOR DEVELOPERS
We just check if we're actually on the Cart page before setting the constant and later on we dequeue the `Cart.js` file if we're not actually on the Cart page.
```
$is_really_a_cart_page = false; // We assume we're not on the Cart page
if(is_cart()){ // We check if we're on the Cart page
	$is_really_a_cart_page = true;
}
if(!defined('WOOCOMMERCE_CART')){ // We set this constant to true to enable calculating totals in the cart
	define('WOOCOMMERCE_CART', true);
}
WC()->cart->calculate_totals();
if(!$is_really_a_cart_page){ // If we're not on the Cart page, the cart.js file would hijack form submissions
	function dequeue_wc_cart_js(){
		wp_dequeue_script('wc-cart');// We dequeue the cart.js file
	}
	add_action('wp_enqueue_scripts', 'dequeue_wc_cart_js', 15); // We dequeue the file with a lower priority than when it is enqueued
}
```

**Comment by mikejolley** [comment]
Have you tested this on master/2.6.5 yet? That cart js code was updated.

**Comment by SukcesStrony** [comment]
Yes, the problem still occurs in 2.6.5. They code which targets the cart form wasn't changed as far as I see.

**Comment by mikejolley** [comment]
Since this requires a template mod (to add the class) which we cannot ensure will be there, this should be done in 2.7.

**Comment by mikejolley** [comment]
@coderkevin Would changing those `div.woocommerce form` selectors to `.form.woocommerce-cart` and adding a class in the template file break anything else I don't see?

@jameskoster `form.woocommerce-cart` naming ok?

**Comment by SukcesStrony** [comment]
As far as I see the "woocommerce-cart" class is already applied to the body tag on the cart pages, so it would cause conflicts. I think `.cart-form` would be okay, but it's your call. Also, please note the dot in front of "form" in your reply, which shouldn't be there or in the code when you change it :)

**Comment by jameskoster** [comment]
Conflicting with the class on the body will cause issues. How irksome.

`.woocommerce-cart-form` works I suppose.

**Comment by coderkevin** [comment]
When I originally put this in, it was with the goal of not modifying the template. But if we're okay with adding a class to the template for the selector, I'm fine with it.

**Comment by AshiqRono** [comment]
Dear Sir,
even after changing the selector in cart.js file like this 
'div.woocommerce-cart:not(.widget_product_search) > form.cart-form' 
does not work after adding the '.cart-form' class in the 'cart.php' file in the <form> element. It only works if I change the cart.min.js file with this
'div.woocommerce-cart:not(.widget_product_search) > form.cart-form'
Hope this helps others facing the same problem.
Thank you

**Comment by SukcesStrony** [comment]
So what you're saying is that the minified version of the cart.js was not rebuilt in the latest version of WooCommerce. I checked and can confirm this.
@mikejolley ping
