### ISSUE TITLE
REST Api: Webhook for product categories 

### ISSUE THREAD

**Issue by MGxpwr** [woocommerce/woocommerce#12133]
I'm at Woocommerce verision 2.6.4 and Wordpress version 4.6.1. I'm trying to add webhooks to Woocommerce via the REST api. It all works fine for products but not for categories. 

I tried to add a webhook for when a category gets updated. But that's not possible. After some digging i found out that I'm limited to `action.woocommerce_` and `action.wc_` only.

At the moment there is no action which is called on category add/update or delete that i can use as a webhook action?

Is it possible to remove this restriction or a topics to the webhook topics for this?

**Comment by mikejolley** [comment]
@claudiosanches Do we need to add this?

**Comment by claudiosanches** [comment]
@mikejolley well we don't have any action on it, we can add some action, but it's not hard create a custom one like:

```php
add_action( 'edit_term', function( $term_id, $tt_id = '', $taxonomy = '' ) {
    if ( 'product_cat' === $taxonomy ) {
        do_action( 'woocommerce_admin_product_cat_updated', $term_id );
    }
}, 10, 3 );
```

**Comment by mikejolley** [comment]
Worth adding to core somewhere, or handling edit_term?

**Comment by claudiosanches** [comment]
@mikejolley custom actions are limited to `action.woocommerce_` and `action.wc_`, so not possible do handle using `edit_term`, and we can add a new hook inside `WC_Admin_Taxonomies::save_category_fields()` but will be an action inside other action only for it...

**Comment by mikejolley** [comment]
Ok lets leave it. @MGxpwr if there is a valid use case, maybe submit on http://ideas.woocommerce.com/forums/133476-woocommerce But you can use the solution above to apply this on your site if you need it.

Thanks @claudiosanches

**Comment by MGxpwr** [comment]
@claudiosanches Thanks for the example, however im trying to implement a `worker` between my shop and a Woocommerce one. So i don't have access to the source code of the Wordpress website. So i'll try to submit a use case to the link @mikejolley suggested.

Thanks to the both of you

**Comment by mikejolley** [comment]
Post the link here if you do.

**Comment by ThomasVeld** [comment]
Bump
