### ISSUE TITLE
Variable product stock status not showing accurately consistently

### ISSUE THREAD

**Issue by jas8522** [woocommerce/woocommerce#12147]
WooCommerce 2.6.6 // WordPress 4.6.1 // Issue pertains to Back orders and stock status

I have a variable product configured with Stock Management enabled at the product level. Stock quantity is set to 0 at product level with the idea that it'll be controlled on a per-variation basis. Most variations have the stock quantity set to 0. But two variations do not:

Large-Black (Stock set to 1)
Large-Charcol Mix (Stock set to 2)

Both of those variations have backorders set to "Allow, but notify customer".

During an order, when I select those particular variations (Size and Color dropdowns), the async loading occurs, then it sometimes tells me:

"Available on backorder" indicating that it's not in stock. What's odd is that some of the time it will load correctly and say the following (which is what I expected and is accurate):

2 in stock (also available on backorder) [large charcoal mix], or
1 in stock (also available on backorder) [large black]

But the majority of the time it does not. 

Steps to reproduce are:

 1. Set up variable product with two dimensions of variability and a few options within each, such as 4 size options and 4 color options.
 2. Ensure stock management is enabled and configured at the variation level to allow backorders and notify customer.
 3. Set most variations to a stock of 0 (should be default), then set two particular ones to stock levels of 1 and 2 for testing.
 4. Visit the product on the front-end and switch between variations repeatedly. Sometimes it will show the right value and others it will not. 

My only guess is that it's occasionally returning the parent product stock level of 0 rather than the specific variation stock level.

I've tried disabling all plugins and switching to the twentyfifteen theme (sorry twenty twelve was removed). I've tried Chrome and Safari with the same inconsistencies exhibited.

One thing to note is that the occasions when it shows the correct value it seems to load for about 1/2 second longer than the times it shows the wrong value.

**Comment by mikejolley** [comment]
Open and screenshot your variations so we can see how its setup @jas8522

**Comment by jas8522** [comment]
In case someone else comes upon this issue: this occurred because there was a 'blank' entry in the attributes list (ex: red|yellow|blue| ) and when the user linked all attributes to variations, the blank entry was attributed as well. This meant that when a particular size and colour was selected, apparently the blank option was being returned as well intermittently as far as I can tell.

While this ended up being a user issue, I have to wonder why WooComm would allow a blank attribute to be used as a variation at all! Perhaps better parsing is in order?

**Comment by cajustus** [comment]
Hi 
I am trying to make the stock status visible for my sale products, I have installed the plugin Woo Custom Stock Status and have activated but don't know what to do from there. It is visible in the individual products, please excuse my ignorance how do I get the stock qty to show in the front end? Is there something else I'm meant to do?Even in the settings products inventory I've clicked always show stock eg 12 in stock but that does not work either. I have wordpress my theme is shopkeeper. Please Help
regards
Caroline

**Comment by jas8522** [comment]
Hi Caroline,

I don't think this is exactly the same issue, and probably isn't relevant for this particular bug report, however you might be able to get help for this from the theme dev or by submitting a help request to [WooCommerce here](https://www.woocommerce.com/my-account/tickets/). 

Failing that, my company, [Websavers](https://websavers.ca), might be able to help you further diagnose this.

**Comment by cajustus** [comment]
ok thank you
