### ISSUE TITLE
Woocommerce dimensions appear in a wrong way with the Arabic style.

### ISSUE THREAD

**Issue by ahmedibrahim890** [woocommerce/woocommerce#12144]
## EXPLANATION OF THE ISSUE

This happened because Woocommerce uses the letter ( x ) instead of using the mark ( * ), so to resolve this I suggested the user to go to : content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php: line 1504, then exchange the letter ( x  ) with the mark ( * ) to be like this 
    
$dimensions = implode( ' * ', array_filter( array(
    
## STEPS TO REPRODUCE THE ISSUE

-  Install Woocommerce with WPML
 - Add a Product with dimensions (you can add the dimensions from the shipping tab at the product Edit page)
-  Translate the product into Arabic
 - Visit the front end then the additional info and you will find dimensions appear wrong for the Arabic language, it should appear like (40 x 40 ) but it appears as ( x 40 40).

**Comment by amitkvint** [comment]
my guess would be that this is a general RTL issue

**Comment by mikejolley** [comment]
`but it appears as ( x 40 40).`

How is that even possible - language does not affect PHP functions like implode. Regardless of character, the 'x' must appear in-between each measurement.

**Comment by mikejolley** [comment]
#12170
