### ISSUE TITLE
blockUI on checkout submit breaks depending upon CSS

### ISSUE THREAD

**Issue by johnmontfx** [woocommerce/woocommerce#12152]
## EXPLANATION OF THE ISSUE

Utilizing Twenty Fifteen theme with Woocommerce activated, a simple CSS change will break the blockUI functionality on the checkout page, making it incredibly confusing for customers hit the button and not see an indicator of activity while waiting for payment transaction to clear.

imho, a fairly simple CSS change (I think _float_ is the issue), shouldn't break this functionality.

## STEPS TO REPRODUCE THE ISSUE

1. Disable off all plugins
2. Enable Woocommerce
3. Switch to Twenty Fifteen  theme
4. Add the following code to the Twenty Fifteen theme .css at the end:

```
.woocommerce-checkout .col2-set {
    float: left;
    width: 48%;
}

#order_review_heading,
.woocommerce-checkout-review-order {
    float: right;
    width: 48%;
}

```

5. Add a product to a cart and attempt to make a transaction.

There is no blockUI or ajax load indicator.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://dev.fxphd
Site URL: https://dev.fxphd/wp
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.26 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 500 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/0.9.8zd

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.42 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() failed. The WooCommerce plugin updater won't work with your server. Contact your hosting provider. Error: cURL error 51: SSL: no alternative certificate subject name matches target host name 'woocommerce.com'

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (3) ###

Redux Framework: by Team Redux – 3.5.8.1
Groups: by itthinx – 1.13.1
WooCommerce: by WooThemes – 2.6.4

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #2267 - /store/
Cart: #4528 - /cart/
Checkout: #4529 - /checkout/
My Account: #4530 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Twenty Fifteen
Version: 1.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: twentyfifteen/.DS_Store
`

**Comment by mikejolley** [comment]
> imho, a fairly simple CSS change (I think float is the issue), shouldn't break this functionality.

Without a clearfix, parents of floated elements will collapse. In this case thats the form (.checkout) and thats also the element which blockui applies. If that has 0 height due to floats it stands to reason those blockuis will be hidden.

https://dl.dropboxusercontent.com/s/xm6sjncm9s87ky6/2016-10-24%20at%2008.01.png

It would be impossible for WC to prevent all custom CSS affecting how elements are displayed. If you're theming with custom CSS like this you should at least understand how floats work and how to apply a clearfix. See https://css-tricks.com/snippets/css/clear-fix/ for example.

**Comment by Adplabscode** [comment]
any possible solution
