### ISSUE TITLE
Partial Refund Unable to be sorted by price

### ISSUE THREAD

**Issue by worldtravlr** [woocommerce/woocommerce#12153]
## EXPLANATION OF THE ISSUE
If a partial refund is made and then the desire to search for and/or find that order I am not sure how to do that as the order is still completed (not refunded), but sorting by price does not put that order higher that other orders of the original price.

## STEPS TO REPRODUCE THE ISSUE
Make a partial refund.  Sort order ascending or descending.  For example, lets say you have one item you sell for $100, but some customer had some issues, so they received a partial refund of $10, so now their total is only $90.  Then when you sort by price that order will not show in order of its new value.

### WordPress Environment ###

Home URL: https://5daydeal.com
Site URL: https://5daydeal.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.2
PHP Version: 7.0.8-4+deb.sury.org~xenial+1
PHP Post Max Size: 100 MB
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.6.10
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (46) ###

VaultPress: by Automattic – 1.8.5
Gravity Forms: by rocketgenius – 2.0.7
ActiveCampaign: by ActiveCampaign – 6.25
AffiliateWP: by AffiliateWP
LLC – 1.9.3.1

AffiliateWP - Affiliate Area Shortcodes: by Pippin Williamson and Andrew Munro – 1.1.4
AffiliateWP - Allow Own Referrals: by AffiliateWP
LLC – 1.0.2

AffiliateWP - Order Details For Affiliates: by Pippin Williamson and Andrew Munro – 1.1.2
AffiliateWP Referral Export Addon: by Tunbosun Ayinla – 4.0.1
AffiliateWP - WooCommerce Redirect Affiliates: by Pippin Williamson and Andrew Munro – 1.0
WP Offload S3: by Delicious Brains – 1.2
Amazon Web Services: by Delicious Brains – 1.0
Beaver Builder Plugin (Pro Version): by The Beaver Builder Team – 1.8.7
Foundry - WP Offload S3 - WooCommerce Addon: by Anand Shah
Performance Foundry – 1.0.1

Foundry Buy Buttons: by Performance Foundry – 1.0.0
Foundry Contributor Center: by Yuriy Vasilyev
Ricardo Correia
Performance Foundry – 0.1.0

Foundry Countdown Timers: by Performance Foundry – 0.0.3
Foundry PHP7 Plugin Fix: by Performance Foundry – 0.0.1
Foundry Facebook Conversion Pixel: by Performance Foundry – 1.3
Foundry Giveaway Form: by Performance Foundry – 1.0.0
Foundry Monarch Fake Counts: by Performance Foundry
Elegant Themes – 2.1.1

Foundry Stop non .org Plugins Update Checks: by Performance Foundry – 0.0.1
Foundry Testimonials: by Performance Foundry – 1.1
Gravity Slider Fields (Foundry Edition): by UaMV – 0.8
Gravity Forms Survey Add-On: by Rocketgenius – 3.1
Happiness Reports for Help Scout: by Andrew Munro
Sumobi – 1.0.0

Help Scout Desk: by Sprout Apps – 3.2
Multi-License Manager: by Paul Menard
Isaac Oyelowo – 0.9.0.1

OptinMonster API: by Thomas Griffin – 1.1.5.6
PayPal for WooCommerce: by Angell EYE – 1.2.4
Post Types Order: by Nsp Code – 1.9
WP REST API: by WP REST API Team – 2.0-beta15
Simple Sales Tax: by Simple Sales Tax – 4.9
SVG Support: by Benbodhi – 2.2.3.2
User Switching: by John Blackbourn – 1.0.9
WooCommerce Checkout Field Editor: by WooThemes – 1.5.1
WooCommerce Customer/Order CSV Export: by WooThemes / SkyVerge – 4.0.7
WooCommerce Email Validation: by Hugh Lashbrooke – 2.0
WooCommerce Google Analytics Pro: by WooThemes / SkyVerge – 1.1.4
WooCommerce PDF Invoices (Foundry Edit): by Bas Elbers – 2.4.10
WooCommerce Terms & Conditions Popup: by Patrick Rauland – 1.0.3
WooCommerce: by WooThemes – 2.6.4
Yoast SEO: by Team Yoast – 3.7.0
WP Better Emails: by Nicolas Lemoine – 0.3
WP Fusion: by Very Good Plugins – 2.7
Logooos Wordpress plugin: by husamrayan – 2.0
wpMandrill: by Mandrill – 1.33

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #52263 - /shop/
Cart: ❌ Page visibility should be public
Checkout: #52265 - /checkout/
My Account: #52266 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: 5 Day Deal 2016
Version: 1.0
Author URL: http://performancefoundry.com
Child Theme: ✔
Parent Theme Name: Beaver Builder Theme
Parent Theme Version: 1.5.2
Parent Theme Author URL: http://www.wpbeaverbuilder.com/?utm_medium=bb-pro&utm_source=bb-theme&utm_campaign=themes-admin-page
WooCommerce Support: ✔

### Templates ###

Overrides: bb-theme-5dd/woocommerce/checkout/form-billing.php
bb-theme-5dd/woocommerce/checkout/form-checkout.php
bb-theme-5dd/woocommerce/checkout/form-login.php
bb-theme-5dd/woocommerce/checkout/form-shipping.php
bb-theme-5dd/woocommerce/checkout/review-order.php
bb-theme-5dd/woocommerce/checkout/thankyou.php
bb-theme-5dd/woocommerce/emails/customer-completed-order.php
bb-theme-5dd/woocommerce/emails/customer-reset-password.php
bb-theme-5dd/woocommerce/emails/email-order-items.php
bb-theme-5dd/woocommerce/myaccount/dashboard.php
bb-theme-5dd/woocommerce/myaccount/downloads.php
bb-theme-5dd/woocommerce/myaccount/my-account.php

### Customer/Order CSV Export ###

Order Export Format: import
Customer Export Format: import
Automatically Export Orders: disabled
Automatically Export Customers: disabled

**Comment by mikejolley** [comment]
The original order total is not adjusted after partial refund (refund is a separate object), so sorting will never work like that without complex SQL code (something which would be difficult to add, and non performant in the admin area). Due to that this I would consider this a #wontfix.

However, I'd be curious to learn more about your use case to see if we can offer an alternative view for refunds in the future, and to know why you'd need to search manually vs. knowing which order you're looking for? Outputting a list of refunds elsewhere would be fairly simple.

**Comment by worldtravlr** [comment]
Thanks Mike.  My issue is I have 16,000 orders so when I partially refund a few I am not sure of ay easy way to find them other than by order number as they won't sort to the top by new order value and they of course don't have a refunded status.  Thanks for you help and any solutions you can offer.  Maybe add a partially refunded/adjusted area/order status?

**Comment by mikejolley** [comment]
@worldtravlr Can't change status because you would lose track of the previous real order status. We will split payment/shipping status in the distant future but for now it's not viable.

**Comment by worldtravlr** [comment]
Thanks @mikejolley.  Just to clarify I am not looking for a payment/shipping status that I know.  We only sell digital products.  I am looking for some way to easily see and find via sort or filter partially refunded orders without having to know the order number of each.  Hope that helps and thanks so much.
