### ISSUE TITLE
WP CLI Woocommerce featured image on creating product

### ISSUE THREAD

**Issue by dsgnr** [woocommerce/woocommerce#12158]
I am trying to automate uploading a few thousand products using wp-cli and the wc tags. I am able to add images to the product gallery using WP Cli, but is there a way to add a featured image? 

I am currently using --images.0.src="" which adds the image to the gallery but I can't see anywhere that talks about the featured image. Am I missing something?

Thanks in advance

**Comment by mikejolley** [comment]
The image at position 0 is the featured image.

CLI is being rewritten here so you're aware https://github.com/woocommerce/woocommerce/issues/11611
