### ISSUE TITLE
Product with variation not correctly deletetd on CLI

### ISSUE THREAD

**Issue by danielhuesken** [woocommerce/woocommerce#12157]
If you delete products with wp-cli or on frontend the variations and so on will not correctly delete.

That is because the actions here https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-post-types.php#L74-L79 will only done in admin area.

The rest api has it own implementation for that deletion that will be not needed if you have this generell.

**Comment by mikejolley** [comment]
Soon to be irrelevant https://github.com/woocommerce/woocommerce/issues/11611
