### ISSUE TITLE
Our update messages still says WooThemes, twice. 

### ISSUE THREAD

**Issue by californiakat** [woocommerce/woocommerce#12165]
## EXPLANATION OF THE ISSUE

In WooCommerce core and all of our plugins, the update message shown to users still says WooThemes subscription and WooThemes Helper. Everything should say WooCommerce.

## STEPS TO REPRODUCE THE ISSUE

There are no steps. When there's a new release, the message appears on a store/site.

Here's a screenshot

<img width="1020" alt="screen shot 2016-10-24 at 19 56 15" src="https://cloud.githubusercontent.com/assets/6988393/19657384/4d5f573c-9a24-11e6-9f98-53474a2dfdf2.png">

*If this is the wrong place to post, apologies in advance.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woothemes-updater/issues/156
