### ISSUE TITLE
Conflict with Bootstrap 3

### ISSUE THREAD

**Issue by paulcanning** [woocommerce/woocommerce#12164]
I am experiencing a conflict with BS3 when trying to view the Product Data info (inventory, attributes etc)

The divs have a class of "hidden" which is being picked up by BS3 and keeping the content hidden, despite clicking the appropriate link that should unhide the div.

The "hidden" class is being included by BS3's response-utilities LESS file.

Is there anything I can do to stop this conflict?

I'm using WooCommerce 2.6.6 on WP 4.5.4.

BS is 3.3.6 (also tried 3.3.7)

**Comment by jameskoster** [comment]
You mean on the backend? Why are you including bootstrap in wp-admin?

The `hidden` class is removed when the panel should be visible so I'm not sure why you're having this issue.

Please post more info :)

**Comment by paulcanning** [comment]
We are developing a plugin that connects with WooCommerce, and has it's own admin pages for various things and we are using BS3 to layout the pages.

**Comment by mikejolley** [comment]
WordPress itself uses .hidden in places, if you look through https://github.com/WordPress/WordPress/search?utf8=%E2%9C%93&q=hidden&type=Code

Generally, you can enqueue CSS/JS only on your own admin screens to prevent issues such as this. Or better yet, use native WordPress CSS styles and avoid bootstrap altogether :)
