### ISSUE TITLE
No Stock and Low Stock Notifications

### ISSUE THREAD

**Issue by pablinos** [woocommerce/woocommerce#12163]
This is more of a request for information than an 'issue' which I originally posted on the forums at WordPress.org, but thought I would try here as it's related more to development rather than support. Apologies for the cross-posting and if this isn't appropriate!

I’m looking to find out how the Low (and No) stock notifications are going to work in future. I was using a clone of the latest code in the GitHub repository to test an extension I’m working on, and discovered I wasn’t receiving these notifications.

In the latest official release of the code it’s relatively easy to trace the hooks back to `woocommerce_low_stock` which gets triggered in the `send_notifications` methods of `abstract-wc-order.php`. However, in the latest code this has been deprecated and the whole class moved to `abstract-wc-legacy-order.php`. There’s also a comment about it not needing to be explicitly called. In the `class-wc-order.php` file there’s the payment_complete method that’s documented as having the stock levels being reduced, but I can’t see where that happens either!

Searching the entire code base I can’t find any reference to the `woocommerce_notify_low_stock` and `woocommerce_notify_no_stock` settings apart from in the reports and for displaying the product availability text.

As my extension needs to hook in to these notifications I’d like to make sure that I’m doing it in a future-proof way, or at least I’m aware of how to fix it when 2.7 is released. I’m sure I’m just being dumb or code blind, but can someone let me know where these notifications are triggered?

Thanks in advance!

**Comment by mikejolley** [comment]
The product crud is not complete, this will be part of that.  #12065

**Comment by mikejolley** [comment]
Taken care of.
