### ISSUE TITLE
Varation sync in rest api

### ISSUE THREAD

**Issue by danielhuesken** [woocommerce/woocommerce#12162]
Can we not do this 
https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L1739-L1748
generally after variations are set.

In moment it will be done on every variation.
https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L1634

In the variation endpoint it must be done every time i think.

Can be improved a bit off performance.

**Comment by claudiosanches** [comment]
Not sure if you understand this code... But need to sync the variations when update a variable product and don't update the variations, and that is the case, this is trigged only when you submit a variable product without any variation.
