### ISSUE TITLE
Variable Products Added to Cart when I Click Select Options Button

### ISSUE THREAD

**Issue by thehung2224** [woocommerce/woocommerce#12169]
## EXPLANATION OF THE ISSUE

I just noticed some odd behavior with the latest WC update. On the category page, when I hit the Select Options button on a variable product, instead of going to the product page, it just adds the variable product to the cart. What’s really strange is when I hover over the button I can see it’s linking to the product page. Yet it’s still just putting the product in the cart and staying on the catalog page.

**Comment by mikejolley** [comment]
Sounds like your theme is customising the CSS classes on the add to cart buttons - if it adds the ajax add to cart class, this will happen. It's not happening on 2.6.6 and default theme - just tested.

**Comment by thehung2224** [comment]
Hi @mikejolley ,

Here’s what I found digging around in the theme files…

wp-content\themes\dione\woocommerce\add-to-cart.php:

```
global $product;

$class = 'button product_type_simple add_to_cart_button ajax_add_to_cart add-to-cart-button btn btn-border-black';

echo '<div class="product-button">';
echo apply_filters( 'woocommerce_loop_add_to_cart_link',
	sprintf( '<a rel="nofollow" href="%s" data-quantity="%s" data-product_id="%s" data-product_sku="%s" class="%s">%s</a>',
		esc_url( $product->add_to_cart_url() ),
		esc_attr( isset( $quantity ) ? $quantity : 1 ),
		esc_attr( $product->id ),
		esc_attr( $product->get_sku() ),
		esc_attr( isset( $class ) ? $class : 'btn btn-border-black' ),
		esc_html( $product->add_to_cart_text() )
	),
	$product );

echo '<a href="' . get_the_permalink() . '" class="product-review btn btn-border-black">' . esc_html( 'view item', 'tm-dione' ) . '<span class="pe-7s-search"></span></a>';
echo '</div>';
```

**Comment by mikejolley** [comment]
> ajax_add_to_cart

**Comment by thehung2224** [comment]
@mikejolley 

I don't understand your mean.

**Comment by mikejolley** [comment]
Thats the class. Compare that file to our core version.
