### ISSUE TITLE
Adjust nag notification on 'PayPal Express Checkout' plugin

### ISSUE THREAD

**Issue by simonrcodrington** [woocommerce/woocommerce#12160]
Hey guys,

When you run the Woocommerce setup and you choose to add your payment gateways. The '**WooCommerce PayPal Express Checkout Gateway**' plugin adds an undismissable nag notification saying "**PayPal Express Checkout is almost ready. To get started, connect your PayPal account.**" so long as the plugin is installed.

![paypal_woocommerce_nag](https://cloud.githubusercontent.com/assets/12083338/19630884/dc7cea56-99de-11e6-8cff-f13354b1469d.jpg)
That nag notification makes sense when you have the plugin installed **and** activated, however when I just want the plugin activated so I can configure it when I'm ready, it gets in the way on every page. 

Where the notification is defined, it would be great if you guys could set it to be dismissed.  

When I create plugins with conditional important settings; I check to see if the settings have been adjusted and then re-show any applicable notifications. 

Regards

**Comment by mikejolley** [comment]
I'll pass on your feedback to @roykho / @gedex since that is hosted in a separate repository, but just to point out it **is both** activated and installed after setup wizard. You do not have to activate the plugin later as that would be an extra step.

**Comment by gedex** [comment]
Moved to https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/192

**Comment by simonrcodrington** [comment]
Thanks for that guys. I'll chase it up in that thread
