### ISSUE TITLE
Input credit card number on smartphone

### ISSUE THREAD

**Issue by WataruTamanaha** [woocommerce/woocommerce#12161]
## EXPLANATION OF THE ISSUE

My store is targeting Japanese consumers and few customers send me issues that input cursor slips when they typing credit card numbers so they can not proceed checkouts. they were smartphone users.
I found out that their input keyboard had been set as Japanese one and it makes the problem.

## STEPS TO REPRODUCE THE ISSUE

1. Use Smartphone EX. iPhone,  and set default keyboard as Japanese.
2. On checkout page, try to type credit card information.

## SUGGESTION

It works fine if I replace `<input type="text">` with `<input type="tel">` on line 61 of
/includes/gatewaysclass-wc-payment-gateway-cc.php

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/12037

@claudiosanches apply to 2.6?

**Comment by claudiosanches** [comment]
@mikejolley I see no problem in apply it to 2.6.

**Comment by claudiosanches** [comment]
Done.
