### ISSUE TITLE
Can't import Tax csv into secondary tax rates

### ISSUE THREAD

**Issue by garrett-eclipse** [woocommerce/woocommerce#12175]
## EXPLANATION OF THE ISSUE

I have a tax csv I want to import into the secondary Tax Rates labeled 'Reduced Rate Rates', when I navigate to the Tax table for 'Reduced Rate Rates' at the bottom there's an Import CSV button. This takes me to the Import Tax Rates tool (/wp-admin/admin.php?import=woocommerce_tax_rate_csv) and allows me to import my csv. However once imported if I got back into my Tax Rates I find the import updated the primary 'Standard Rates' table rather than the 'Reduced Rate Rates' table.

It seems the imported doesn't have the ability to import into any other table than the primary 'Standard Rates', this feels broken especially since each secondary Tax table has the Import/Export buttons at the bottom (screen). 
http://i.imgur.com/JpWUYOB.png
## STEPS TO REPRODUCE THE ISSUE
1. Navigate to Tax Settings
2. Select a secondary Tax Rate such as 'Reduced Rate'
3. Click Import CSV in bottom right of table.
4. Import your csv file.
5. Navigate to 'Reduced Rate' tax rate
   *You'll notice it hasn't changed.
6. Navigate to 'Standard' tax rate
   *You'll find the imported tax rates here.
## SYSTEM STATUS REPORT

`
### WordPress Environment

Home URL: http://caffefantastico.eclipsedev.tk
Site URL: http://caffefantastico.eclipsedev.tk
WC Version: 2.6.6
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_CA
### Server Environment

Server Info: Apache
PHP Version: 5.6.26
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
### Database

WC Database Version: 2.6.6
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔
### Active Plugins (18)

Gravity Forms: by rocketgenius – 2.0.7
Advanced Custom Fields PRO: by Elliot Condon – 5.4.8
Comet Cache Pro: by WebSharks
Inc. – 160917

Disable Comments: by Samir Shah – 1.5.2
Duplicate Post: by Enrico Battocchi – 3.0.2
Easy FancyBox: by RavanH – 1.5.7
Instagram Feed: by Smash Balloon – 1.4.8
Intuitive Custom Post Order: by hijiri – 3.0.7
Popups - WordPress Popup: by Damian Logghe – 1.6.0.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Simple Image Sizes: by Rahe – 3.1.1
Soil: by Roots – 3.4.0
The Events Calendar: by Modern Tribe
Inc. – 4.3.1.1

Thumbnail Upscale: by Stanislav Khromov – 1.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 2.12.23.22

WooCommerce: by WooThemes – 2.6.6
Wordfence Security: by Wordfence – 6.2.2
WP Migrate DB Pro: by Delicious Brains – 1.6.1
### Settings

Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
### API

API Enabled: ✔
### WC Pages

Shop Base: #10 - /shop/
Cart: #37 - /cart/
Checkout: #38 - /checkout/
My Account: #39 - /my-account/
### Taxonomies

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
### Theme

Name: Gromf 8.x
Version: 8.2.1
Author URL: https://simenschi.no/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔
### Templates

Overrides: fantastico-gromf/woocommerce/archive-product.php
fantastico-gromf/woocommerce/cart/cart.php
fantastico-gromf/woocommerce/content-product.php
fantastico-gromf/woocommerce/global/quantity-input.php
fantastico-gromf/woocommerce/loop/loop-end.php
fantastico-gromf/woocommerce/loop/loop-start.php
fantastico-gromf/woocommerce/single-product/add-to-cart/simple.php
fantastico-gromf/woocommerce/single-product/price.php
fantastico-gromf/woocommerce/taxonomy-product_cat.php
fantastico-gromf/woocommerce/taxonomy-product_tag.php

`

**Comment by mikejolley** [comment]
It's controlled by a column in your CSV. The import button links to the same importer regardless. Look at the sample CSV. We can make this clearer, but it's not an immediate concern.

**Comment by garrett-eclipse** [comment]
Thanks @mikejolley I appreciate the information.

It's definitely not overly intuitive when you're trying to migrate tax records from one rate table to another as going through that process I didn't even think to open the exported csv. I'll keep that in mind for future.

Would be handy if the importer allows you to select the destination table or at least provide a notice about how to change the destination by editing the import csv.

Cheers

**Comment by mikejolley** [comment]
This works so no changes are **required**, but we can look at using the same interface as the product importer in 3.1 in future updates.
