### ISSUE TITLE
Variation SKU cannot be re-used when a product type is changed from variable to another type

### ISSUE THREAD

**Issue by paulwilde** [woocommerce/woocommerce#12173]
When you have a product that is set as a Variable product with any number of variations that contain SKUs and then change the product to be another type (such as Simple, or External), you cannot re-use the variation SKUs that already exist as the `_sku` meta key still exists, despite those variations no longer being used.

The only workaround I've found is to manually delete the `_sku` meta keys for those variations which are no longer used. 

Ideally the code that checks if a SKU is unique should exclude any variation SKU that is no longer being used, such as those in this scenario where the product type has been changed after the product initially being a variable product, or better yet remove the variations when the product type is changed.

**Comment by claudiosanches** [comment]
Because you need to delete the variations in the product before you change to Simple or External.

**Comment by paulwilde** [comment]
Wouldn't this be considered a bug though? As when you change it back from Simple/External to Variable, the variations are no longer accessible to be deleted if you didn't do so prior to changing the product type.  The only way to delete them from that point is to actually do so manually in the database, which isn't feasible in my clients case.

**Comment by claudiosanches** [comment]
@paulwilde we display a message saying that things can go wrong if you do it and you should delete first.

**Comment by claudiosanches** [comment]
And we are adding an option to remove all orphan variations in 2.7.
