### ISSUE TITLE
Retrieve orders based on date in new API

### ISSUE THREAD

**Issue by santhoshatandra** [woocommerce/woocommerce#12187]
Hi all,

I am working windows based .Net application that interacts with New REST API. i am following oauthentication for http clients. i am able to retrieve order info by orderID. but i need orders based on date.

If i  add "after" parameter in signature generation process, i am getting " Signature Invalid" error. I am sending ISO8601 compliant date only.

Here sample request and response,

GET http://demosite.com/wp-json/wc/v1/orders?oauth_consumer_key=xxxxxxxxxx&oauth_nonce=2612278&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1477487167&after=2016-10-26T13%3A06%3A07&per_page=25&page=1&oauth_signature=GiV0CbNLSnYivJfiwvgcwNw3hKg= 

Response :

HTTP/1.1 401 Unauthorized
Date: Wed, 26 Oct 2016 13:06:22 GMT
Server: Apache/2.4.23
X-Powered-By: PHP/5.4.45
P3P: CP="NOI"
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-Frame-Options: SAMEORIGIN
X-Robots-Tag: noindex
Link: <http://demosite.com/wp-json/>; rel="https://api.w.org/"
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization
Set-Cookie: PHPSESSID=93a567445aea2b6d9604b5e3640e92e6; path=/
Vary: Accept-Encoding,User-Agent
Keep-Alive: timeout=5
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: application/json; charset=UTF-8

89
{"code":"woocommerce_rest_authentication_error","message":"Invalid Signature - provided signature does not match.","data":{"status":401}}
0

Please let me know anything missing while signature generation?

**Comment by claudiosanches** [comment]
> If i add "after" parameter in signature generation process, i am getting " Signature Invalid" error. I am sending ISO8601 compliant date only.

Please read the REST API docs:
https://woocommerce.github.io/woocommerce-rest-api-docs/#index

Here what you are missing:
> Sort the list of parameters alphabetically by encoded key.

This does not seem to be sorted alphabetically:

> oauth_consumer_key=xxxxxxxxxx&oauth_nonce=2612278&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1477487167&**after=2016-10-26T13**%3A06%3A07&per_page=25&page=1&oauth_signature=GiV0CbNLSnYivJfiwvgcwNw3hKg=
