### ISSUE TITLE
Inconsistant placing of checkboxes for product_type booleans in backend

### ISSUE THREAD

**Issue by apermo** [woocommerce/woocommerce#12183]
## EXPLANATION OF THE ISSUE

**Checkboxes for a simple product**
![image](https://cloud.githubusercontent.com/assets/4695889/19721783/0f9d9bb0-9b74-11e6-872b-05d05d6e2bfd.png)

Scheme is:
Label: [ ]

**Checkboxes for a single variation of a variable product**
![image](https://cloud.githubusercontent.com/assets/4695889/19721772/039a9822-9b74-11e6-8015-a87eb14d5cfa.png)

Scheme is
[ ] Label

Both Checkboxes have partially the same content and function, so this is possibly misleading, that they change their order. It gets far more confusing when additional checkboxes are added beyond the default which is depicted in the screenshots above.

My solution would be to either decide to put checkboxes on the same side in both cases. Yet this would lead to new confusion for existing users. Or give them an optical connection, something like a frame or a background, or a bigger margin between 2 options, to make the connection more clearly.

**Comment by claudiosanches** [comment]
@jameskoster can you choose?

**Comment by jameskoster** [comment]
Checkboxes should be on the left.

- [ ] Label

**Comment by claudiosanches** [comment]
Closed in favor of #12199
