### ISSUE TITLE
Free shipping if total cost is higher than...

### ISSUE THREAD

**Issue by Tklaversma** [woocommerce/woocommerce#12186]
Hi,

I would like to make the fixed shipping costs zero, if the total costs of the products is equal or higher than 650. Does anyone now how to accomplish this? Can't seem to find anything about this specific problem on the Internet.

_Note: I use the latest WordPress with the latest WooCommerce version._

Thanks in advance!

Regards,
TK

**Comment by claudiosanches** [comment]
Please note that this GitHub is only for issues with WooCommerce and not for support.

If you have questions, use the either:
- https://wordpress.org/support/plugin/woocommerce for general support
- https://woocommerce.com/my-account/tickets/ for premium plugin support

![screenshot from 2016-10-26 12-21-48](https://cloud.githubusercontent.com/assets/1264099/19729766/d920f2be-9b76-11e6-8279-43b521f5fccd.png)
