### ISSUE TITLE
can't navigate through product tab

### ISSUE THREAD

**Issue by jemesmain** [woocommerce/woocommerce#12194]
## EXPLANATION OF THE ISSUE

when i'm on product page i cannot go to stock or other tab... the first tab stays on on my chrome browser.

the only way to go partly through thi is to do product quick modification on the all product page.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
This sounds like a javascript conflict. In chrome open View > Developer > Javascript console, view the error, and remove the problem plugin/theme/code.

**Comment by jemesmain** [comment]
on the console

it is this point

https://www.bicyclopresto.fr/wp-content/plugins/woocommerce/assets/js/admin/wc-enhanced-select.min.js?ver=2.6.7

and

it says

Uncaught TypeError: Cannot read property 'split' of null

what's wrong?

Jean-Eric MESMAIN

111 avenue la BRUYERE
38100 GRENOBLE
Tel: 06 63 95 71 56

**Comment by mikejolley** [comment]
Wrong jquery version.

**Comment by jemesmain** [comment]
Hello

It was tool set type extension in wp which was conflicted..

Cordially

Jean-Eric MESMAIN

111 avenue la BRUYERE
38100 GRENOBLE
Tel: 06 63 95 71 56

**Comment by jemesmain** [comment]
Sorry, to bother you  again

but I'm a newbies... how do I update it?

Settings from my webhosting?

what is at last the correct version?

Thanks anyway for your help ;-)

Jean-Eric MESMAIN

111 avenue la BRUYERE
38100 GRENOBLE
Tel: 06 63 95 71 56

**Comment by mikejolley** [comment]
You have a bad plugin or theme enqueueing their own version probably... You shouldn't need to touch it.
