### ISSUE TITLE
Order total box shows "/year" for shipping of non-recurring item

### ISSUE THREAD

**Issue by zachd** [woocommerce/woocommerce#12192]
When a recurring subscription without shipping and a non-recurring item _with_ shipping are both added to the cart, the Woocommerce order total box shows "/year" in the shipping total field. This happens even when the shipping applies only to the non-recurring item. Expected behaviour is that the shipping row shows "Standard: €4.99 now" and not "/ year".

Shown in screenshot below. Woocommerce version 2.6.6, Wordpress version 4.6.1.

![image](https://cloud.githubusercontent.com/assets/1366937/19735473/90e27a7c-9ba3-11e6-8429-52836be8ecc4.png)

**Comment by mikejolley** [comment]
@zachd can you send this to the subscriptions plugin developer you're using? If this is woo, please use the helpdesk. WC core does not control the 'year' string.
