### ISSUE TITLE
mysql query of _wc_term_recount is super slow

### ISSUE THREAD

**Issue by eHtmlu** [woocommerce/woocommerce#12197]
## EXPLANATION OF THE ISSUE

Using WC 2.6.4

These days I write a plugin to import products. When I use the wordpress function `wp_set_object_terms` to register a product to categories, this takes very long (about 2 to 6 Seconds). All the other things all together are much faster. So I have explored which part takes so much time and I landed at the mysql query in the `_wc_term_recount` function. I have measured this query separatly and it really takes up to 6 seconds. Tested on my local machine (quad core i7 and ssd).
This query alone makes my whole import process at least ten times slower. I can't believe that there is no faster way to do the same.

Here is one example of my tested queries which takes about 5 to 6 seconds:

```
SELECT COUNT( DISTINCT posts.ID ) FROM wp_posts as posts
LEFT JOIN wp_postmeta AS meta_visibility ON posts.ID = meta_visibility.post_id
LEFT JOIN wp_term_relationships AS rel ON posts.ID=rel.object_ID
LEFT JOIN wp_term_taxonomy AS tax USING( term_taxonomy_id )
LEFT JOIN wp_terms AS term USING( term_id )
LEFT JOIN wp_postmeta AS postmeta ON posts.ID = postmeta.post_id

WHERE   post_status = 'publish'
AND     post_type   = 'product'
AND     meta_visibility.meta_key = '_visibility'
AND     meta_visibility.meta_value IN ( 'visible', 'catalog' )

AND term_id IN ( 235,236,302,253 )
```

Here is one example which takes about 2 to 3 seconds:

```
SELECT COUNT( DISTINCT posts.ID ) FROM wp_posts as posts
LEFT JOIN wp_postmeta AS meta_visibility ON posts.ID = meta_visibility.post_id
LEFT JOIN wp_term_relationships AS rel ON posts.ID=rel.object_ID
LEFT JOIN wp_term_taxonomy AS tax USING( term_taxonomy_id )
LEFT JOIN wp_terms AS term USING( term_id )
LEFT JOIN wp_postmeta AS postmeta ON posts.ID = postmeta.post_id

WHERE   post_status = 'publish'
AND     post_type   = 'product'
AND     meta_visibility.meta_key = '_visibility'
AND     meta_visibility.meta_value IN ( 'visible', 'catalog' )

AND term_id IN ( 302 )
```
## STEPS TO REPRODUCE THE ISSUE

just try this:

```
$post_id = 1; // please insert your own value
$categoryIds = array(1, 2, 3); // please insert your own values

$start = time();
wp_set_object_terms($post_id, $categoryIds, 'product_cat' );
$end = time();

echo $end - $start;
```
## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://localhost/...
Site URL: http://localhost/...
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.6.12
PHP Version: 5.6.12
PHP Post Max Size: 80 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.42.1
OpenSSL/1.0.1p

SUHOSIN Installed: –
MySQL Version: 5.6.26
Max Upload Size: 80 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (21) ###

Redux Framework: von Team Redux – 3.6.2
AMP: von Automattic – 0.3.3
Contact Form 7: von Takayuki Miyoshi – 4.5
WPBakery Visual Composer: von Michael M - WPBakery.com – 4.12.1
MailChimp für WordPress: von ibericode – 4.0.4
Persicaner Product Import: von Helmut Wandl – 1.0.0
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 2.2.6
Remove XMLRPC Pingback Ping: von Brad Vincent – 1.0.0
Slider Revolution: von ThemePunch – 5.2.6
SI CAPTCHA Anti-Spam: von Mike Challis – 2.7.7.7
Unicase Extensions: von Ibrahim Ibn Dawood – 1.2.4
WooCommerce Dynamic Pricing: von Lucas Stark – 2.11.6
WooCommerce Min/Max Quantities: von Automattic – 2.3.14
WooCommerce Remove All Products: von Gabriel Reguly – 1.0.4
WooCommerce: von WooThemes – 2.6.4
WordPress Importer: von wordpressdotorg – 0.6.3
WP All Import Pro: von Soflyy – 4.3.2
Aktualisierungsalarm: von Scott Cariss – 1.4.4
WP All Import - WooCommerce Add-On Pro: von Soflyy – 2.3.1
YITH WooCommerce Compare: von YITHEMES – 2.0.9
YITH WooCommerce Wishlist: von YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop-Basis: #21 - /?page_id=21
Warenkorb: #22 - /?page_id=22
Kasse: #23 - /?page_id=23
Mein Konto: #24 - /?page_id=24

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Unicase
Version: 1.2.4
Author URL: http://www.transvelo.com
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: unicase/woocommerce/content-widget-product.php Version - ist veraltet. Die Hauptversion ist 2.5.0
: Erfahre
wie du veraltete Templates aktualisierst

`
```

**Comment by mikejolley** [comment]
> I can't believe that there is no faster way to do the same.

You're writing an import plugin so you should be able to see what the query is doing. I don't see a way to optimise that do you? It's the join to postmeta.

**Comment by eHtmlu** [comment]
I haven't analysed the query until now (I'm not a mysql specialist). Usually I solve such things with php and multiple very simple queries (which can be much faster if the coder don't know how to make high performant mysql queries, like me). Maybe I can make tests the next weeks.

**Comment by rob1001** [comment]
From what i've seen WooCommerce database is very anemic. It's basically just tables.

Specifically here, COUNT(*)  works better when there are  column indexes. Adding indexes correctly will help considerably not only for this query but it will also effect the general performance of the database.

Other ways to improve efficiency:
1. Check if you really need LEFT JOIN. Maybe INNER JOIN can work as well?
2. Alter your query to work with  GROUP BY, it can reduce the time of COUNT(DISTINCT field) query as noted here: http://stackoverflow.com/questions/5584093/best-approach-to-getting-count-of-distinct-values-in-mysql

If you will run the query with the ANALYZE tool, it will be easier to know what really happens with this query. My guess is that the optimizer fails to do anything other than 'FULL TABLE SCAN' which is extremely slow.

Personally I think the wp_postmeta  table slows everything. It's design is not of how table should be structured in RDB and while it is tolerable for audit or history tables which are rarely accessed. It's very bad when it's a core table.

**Comment by leewillis77** [comment]
Just looking at this, and based on the SQL queries posted here (I've not looked at the code that generates them), there's a couple of changes I'd suggest. 

Firstly - there's a join onto postmeta (`LEFT JOIN wp_postmeta AS postmeta ON posts.ID = postmeta.post_id`) that isn't being used for anything and could be removed?

There's also no need for the join onto wp_terms - it's not being used. The term ID that the `where` clause applies to is already present on wp_term_taxonomy. 

So - you'd end up with the following, which should be better.
```
SELECT COUNT( DISTINCT posts.ID ) FROM wp_posts as posts
LEFT JOIN wp_postmeta AS meta_visibility ON posts.ID = meta_visibility.post_id
LEFT JOIN wp_term_relationships AS rel ON posts.ID=rel.object_ID
LEFT JOIN wp_term_taxonomy AS tax USING( term_taxonomy_id )
WHERE   post_status = 'publish'
AND     post_type   = 'product'
AND     meta_visibility.meta_key = '_visibility'
AND     meta_visibility.meta_value IN ( 'visible', 'catalog' )
AND term_id IN ( 235,236,302,253 )
```

Looking at an `EXPLAIN` of the query on my local box I suspect that a composite index on (post_id, meta_key) on wp_postmeta would improve things as well, but it really depends on what data you have. 

If the amended query above still runs slowly for you, can you post the output of 
```
EXPLAIN SELECT COUNT( DISTINCT posts.ID ) FROM wp_posts as posts
LEFT JOIN wp_postmeta AS meta_visibility ON posts.ID = meta_visibility.post_id
LEFT JOIN wp_term_relationships AS rel ON posts.ID=rel.object_ID
LEFT JOIN wp_term_taxonomy AS tax USING( term_taxonomy_id )
WHERE   post_status = 'publish'
AND     post_type   = 'product'
AND     meta_visibility.meta_key = '_visibility'
AND     meta_visibility.meta_value IN ( 'visible', 'catalog' )
AND term_id IN ( 235,236,302,253 )
```

**Comment by leewillis77** [comment]
The attached PR removes the tables from the query. It's difficult for me to verify that this works since I don't have enough data - the test script runs in 0.005s either way.

**Comment by danielhuesken** [comment]
You can do `wp_defer_term_counting( true );` when the import starts and on the end `wp_defer_term_counting( false );` to do the count for all at once.

But we have the same problem on massive products import over the Rest API. We have solved it in moment that we disabled the counting on Rest API and do it in a cron job one time at night. 
But a optimization will be helpful i think.

**Comment by andrewlreeve** [comment]
We were seeing the same issue, but with Tradegecko making API calls. Tradegecko peridocly updates/ reviews stock causing 502 errors on slow queries - 11+ seconds.

We modified the querry with the changes from @leewillis77 and we're not getting any more 502 errors. Will wait to update WC with this merged.

**Comment by kevin25** [comment]
The same issue for me. No traffic website but at lot of queries like this. It's killing my server with up to 500% CPU.

**Comment by leewillis77** [comment]
@kevin25 This issue was closed as addressed a long time ago. If you're seeing something similar with recent versions of WooCommerce then you're probably better off opening a new issue with as much information as you can.
