### ISSUE TITLE
Need style tweaks for product gallaries lightbox

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#12200]
When a product galleries are open in lightbox, seems like some actions button at top left of lightbox needs styling tweaks? As I see white box which is shown in below screenshot ;)

![untitled](https://cloud.githubusercontent.com/assets/3774827/19780250/0b74f9e4-9ca4-11e6-91ff-32fcd39fa837.png)

 CC @jameskoster

**Comment by jameskoster** [comment]
Which theme @shivapoudel ?

The lightbox uses `button` elements which some themes apply global styles too. Maybe we need stricter resets.

**Comment by shivapoudel** [comment]
@jameskoster I was on Twenty Twelve :)

**Comment by jameskoster** [comment]
Interesting, should have covered that one. I'll check it out.

**Comment by shivapoudel** [comment]
@jameskoster I also seeing that those action button are hidden on hover in Twenty Sixteen. You're right since some themes apply global styles. This conflict can be ruleout like this, so need stricter resets for background elements.

**Twenty Twelve:**
![capture](https://cloud.githubusercontent.com/assets/3774827/19806433/98151604-9d3a-11e6-993f-49d2c404aee0.PNG)

**Twenty Sixteen:**
![capture](https://cloud.githubusercontent.com/assets/3774827/19806540/67508e9e-9d3b-11e6-94fb-b15278983549.PNG)

**Comment by jameskoster** [comment]
It's working fine for me in Twenty Twelve. Which browser? The background image should be set; https://cloudup.com/c8Y0I-_nL4R

I suppose we can make that `!important`.

**Comment by shivapoudel** [comment]
@jameskoster I am on Chrome and also gotta know that your's is working because it utilizes this bit of styles as your have index in above screenshot:
https://github.com/woocommerce/woocommerce/blob/master/assets/css/photoswipe/default-skin/default-skin.css#L60-L68

But in my cases this is not the scenerio as it loads this bit of style and need to fix:
https://github.com/woocommerce/woocommerce/blob/master/assets/css/photoswipe/default-skin/default-skin.css#L52-L58

**Comment by jameskoster** [comment]
Makes sense. Commented on your PR.
