### ISSUE TITLE
stock quantity will not update for variable product ID

### ISSUE THREAD

**Issue by jeffreythompson70** [woocommerce/woocommerce#12201]
In API testing, the stock quantity updates flawlessly for simple products. However, the stock quantities will not update for variable (child) products. When any quantity is called via API, it comes back as the "number" that is already entered in the  - generally by default it is "0".

The settings are as follows in our Woocommerce admin area:

Stock management is enabled in Woocommerce > Settings > Products > Inventory.
Stock management is not enabled at the parent product level.
Stock management is enabled at the child (variation) level.

Each of the variable products we have tested contains the following variable products:
1. Downloadable product - with Enabled, Downloadable, Virtual all checked; Manage stock unchecked.
2. Physical product - with Enabled, Manage stock checked; Downloadable, Virtual unchecked.

We are trying to update stock quantity only on the Physical product. Here is a link to screenshots of our settings in our Woocommerce admin area.

https://www.dropbox.com/sh/fzluibjqufixwr9/AAA6GYMKPqoNeouZbzvUA8WTa?dl=0## 

Here is the API Request and Response:

'
HTTP request: PUT
Header set: “content-type: application/json”
JSON sent: “{"stock_quantity": 5}”

Response: {"id":3609,"name":"Consecrated Contemplative Prayer Study Guide - by James W. Goll","slug":"wbccp","permalink":"https:\/\/www.godencounters.com\/product\/wbccp\/?attribute_pa_format=study-guide","date_created":"2016-10-06T19:41:11","date_modified":"2016-10-27T15:21:43","type":"variation","status":"publish","featured":false,"catalog_visibility":"visible","description":"<p>Do you want to grow in intimacy with God? These 12 lessons in the <em>Consecrated Contemplative Prayer Study Guide\u00a0<\/em>have helped hundreds come into a deeper communion with their heavenly Father.<\/p>\n<p>James W. Goll brings understanding from the truths of Christian mystics of the past and builds on it with lessons from his own walk with the Lord. Topics include:\u00a0<i>The Ministry of Fasting<\/i>,\u00a0<i>Contemplative Prayer<\/i>,\u00a0<i>Quieting Our Souls Before God<\/i>, and much more. If you want to know God in the deep places of your heart, then take a journey through these enriching pages.<\/p>\n<p>This study guide is great for individual study in your own home, with a small group, or in a classroom setting. It also serves as part of the curriculum for the\u00a0<a href=\"https:\/\/www.godencounters.com\/classes\/consecrated-contemplative-prayer\/\">Consecrated Contemplative Prayer\u00a0class<\/a> with God Encounters Ministries. At the end of each detailed lesson are questions for your reflection and review. As you work through these lessons and apply them to your life, you will find yourself more in love with God than ever before!<\/p>\n<p><strong>Choose Format:<\/strong>\u00a0Softcover Study Guide, PDF Download<\/p>\n<hr \/>\n<p>Bulk Pricing is available for\u00a0the\u00a0<em>Consecrated Contemplative Prayer<\/em>\u00a0<em>Study Guide<\/em>\u00a0as follows:<\/p>\n<p>Buy 10 or more - Save 10%<br \/>\nBuy 20 or more - Save 20%<br \/>\nBuy 30 or more - Save 30%<\/p>\n<p>*Discount available for Softcover Study Guide only.<\/p>\n","short_description":"<p><strong>Choose Format:<\/strong>\u00a0Softcover Study Guide, PDF Download<\/p>\n<p>Do you want to grow in intimacy with God? These 12 lessons in the\u00a0<em>Consecrated Contemplative Prayer Study Guide\u00a0<\/em>have helped hundreds come into a deeper communion with their heavenly Father.<\/p>\n","sku":"SGCCPEN","price":20,"regular_price":"20.00","sale_price":"","date_on_sale_from":"","date_on_sale_to":"","price_html":"<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>20.00<\/span>","on_sale":false,"purchasable":true,"total_sales":4,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"download_type":"standard","external_url":"","button_text":"","tax_status":"taxable","tax_class":"","manage_stock":true,"stock_quantity":1,"in_stock":true,"backorders":"notify","backorders_allowed":true,"backordered":false,"sold_individually":false,"weight":"0.97","dimensions":{"length":"11.0","width":"8.5","height":"0.375"},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":0,"reviews_allowed":true,"average_rating":"0.00","rating_count":0,"related_ids":[2649,2641,16,2428,2640],"upsell_ids":[3198,757,3807],"cross_sell_ids":[2653,3636,3977,3880],"parent_id":3608,"purchase_note":"","categories":[{"id":49,"name":"Consecrated Contemplative Prayer Curriculum","slug":"consecrated-contemplative-prayer-curriculum"},{"id":7,"name":"Curriculum","slug":"curriculum"},{"id":8,"name":"Study Guides","slug":"study-guides"},{"id":106,"name":"Study Guides - PDF","slug":"study-guides-pdf"}],"tags":[{"id":241,"name":"Christian mystics","slug":"christian-mystics"},{"id":123,"name":"contemplative prayer","slug":"contemplative-prayer"},{"id":182,"name":"fasting","slug":"fasting"},{"id":240,"name":"spiritual journey","slug":"spiritual-journey"}],"images":[{"id":3612,"date_created":"2016-10-06T19:40:23","date_modified":"2016-10-26T20:53:47","src":"https:\/\/i2.wp.com\/www.godencounters.com\/wp-content\/uploads\/2016\/10\/SGCCPEN_500.png?fit=500%2C500&ssl=1","name":"SGCCPEN_500","alt":"consecrated contemplative prayer study guide","position":0}],"attributes":[{"id":1,"name":"Format","option":"Study Guide"}],"default_attributes":[],"variations":[],"grouped_products":[],"menu_order":1,"_links":{"self":[{"href":"https:\/\/www.godencounters.com\/wp-json\/wc\/v1\/products\/3608"}],"collection":[{"href":"https:\/\/www.godencounters.com\/wp-json\/wc\/v1\/products"}],"up":[{"href":"https:\/\/www.godencounters.com\/wp-json\/wc\/v1\/products\/3608"}]}}
'
## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: https://www.godencounters.com
Site URL: https://www.godencounters.com
WC Version: 2.6.7
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.21
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 3060
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.7
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (53) ###

VaultPress: by Automattic – 1.8.5
LayerSlider WP: by Kreatura Media – 5.6.6
Akismet: by Automattic – 3.2
Contact Form 7: by Takayuki Miyoshi – 4.5.1
CSS & JavaScript Toolbox: by Wipeout Media – 8.3.1
Duplicate Post: by Enrico Battocchi – 3.0.2
DZS Video Gallery: by Digital Zoom Studio – 9.36
Fusion Core: by ThemeFusion – 2.0.3
Give - Authorize.net Gateway: by WordImpress – 1.2.1
Give - Form Field Manager: by WordImpress – 1.1.1
Give - MailChimp: by WordImpress – 1.3.2
Give - Manual Donations: by WordImpress – 1.0.2
Give - PDF Receipts: by WordImpress – 2.0.3
Give - Recurring Donations: by WordImpress – 1.2.2
Give - Donation Plugin: by WordImpress – 1.6.3
IgniteWoo Updater: by Ignition – 2.1.7
Jetpack by WordPress.com: by Automattic – 4.3.2
KingSumo Giveaways: by KingSumo – 1.4.3
MOJO Marketplace: by Mike Hansen – 1.0.4
Nav Menu Roles + WooCommerce Memberships Bridge: by Kathy Darling – 1.0.0
Nav Menu Roles: by Kathy Darling – 1.8.3
PayPal for WooCommerce: by Angell EYE – 1.2.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.2.5
S3 Media Maestro: by Fly Plugins – 2.0.1
Search Exclude: by Roman Pronskiy – 1.2.2
SumoMe: by SumoMe – 1.21
The Events Calendar: by Modern Tribe
Inc. – 4.3.1.1

User Switching: by John Blackbourn – 1.0.9
Velvet Blues Update URLs: by VelvetBlues.com – 3.2.7
Vextras: by Ryan Hungate – 1.0.4
WooChimp: by RightPress – 2.2.1
WooCommerce Composite Products - Conditional Components: by SomewhereWarm – 1.1.1
WooCommerce Composite Products: by WooThemes – 3.6.10
WooCommerce Dynamic Pricing: by Lucas Stark – 2.11.6
Follow-Up Emails: by WooThemes – 4.4.16
WooCommerce Stacked Add-to-Cart Product Forms: by franticpsyx
SomewhereWarm – 1.1.1

WooCommerce Authorize.Net CIM Gateway: by WooThemes / SkyVerge – 2.4.0 – 2.4.1 is available
WooCommerce Phone Orders & Manual Orders: by IgniteWoo.com – 2.4.9
WooCommerce Memberships: by WooThemes / SkyVerge – 1.7.1 – 1.7.2 is available
WooCommerce Name Your Price: by Kathy Darling – 2.4.1
WooCommerce Product Bundles: by WooThemes – 4.14.7
WooCommerce Product Fees & Cart Fees: by IgniteWoo – 2.3.3
WooCommerce Canada Post Shipping: by Automattic – 2.5.0
WooCommerce FedEx Shipping: by Automattic – 3.4.1
WooCommerce UPS Shipping: by Automattic – 3.2.0
WooCommerce USPS Shipping: by Automattic – 4.4.0
WooCommerce Subscriptions: by Prospress Inc. – 2.0.20
WooCommerce: by WooThemes – 2.6.7
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.1
Yoast SEO: by Team Yoast – 3.7.1
WP-Optimize: by Ruhani Rabin – 1.9.1

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #12 - /store/
Cart: #13 - /cart/
Checkout: #14 - /checkout/
My Account: #15 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Avada Child
Version: – 0 is available
Author URL: http://godencounters.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 4.0.3
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/product-image.php
Avada/woocommerce/single-product/product-thumbnails.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php


### Authorize.Net CIM ###

Environment: Production
Tokenization Enabled: 

### Authorize.Net CIM eCheck ###

Environment: Production
Tokenization Enabled: 
`
```

**Comment by jeffreythompson70** [comment]
In reading the following issue thread it seems our issue is almost identical to this one. Though I never saw a resolution: https://github.com/woocommerce/woocommerce/issues/11736.

**Comment by mikejolley** [comment]
To update a variation stock level, it needs to be done as part of the variations prop of a **parent product.**

http://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

There is an error in the current API which allows **variations** to be accessed via the **products** endpoint which is a mistake. Variations are not products.

We're introducing variation endpoints in 2.7 https://github.com/woocommerce/woocommerce/issues/11775

@justinshreve @claudiosanches I think it might be missing, but should the products endpoint error if you send a variation ID instead of product ID? I think it should - would be clearer going forward.

**Comment by jeffreythompson70** [comment]
Thanks Mike. That did the trick. I appreciate the help.

**Comment by justinshreve** [comment]
> @justinshreve @claudiosanches I think it might be missing, but should the products endpoint error if you send a variation ID instead of product ID? I think it should - would be clearer going forward.

I think so too. And when we version the endpoints, the variations array should be totally removed and all variations should go through the separate endpoints.

**Comment by mikejolley** [comment]
@claudiosanches can you take care of that?

**Comment by claudiosanches** [comment]
#12255

**Comment by whpcreative** [comment]
We're trying to do the same, add a product with variations.
But none of the stock levels or stock settings are set for the variations.

What we are sending to the api

'name' => 'Variable Test',
    'type' => 'variable',
	'manage_stock' => true,
    'description' => 'The example from the documentation with attribute id 6 changed to 3',
    'short_description' => 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    'categories' => [
        [
            'id' => 9
        ],
        [
            'id' => 14
        ]
    ],
    'images' => [
        [
            'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_4_front.jpg',
            'position' => 0
        ],
        [
            'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_4_back.jpg',
            'position' => 1
        ],
        [
            'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_3_front.jpg',
            'position' => 2
        ],
        [
            'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_3_back.jpg',
            'position' => 3
        ]
    ],
    'attributes' => [
        [
            'id' => 3,
            'position' => 0,
            'visible' => false,
            'variation' => true,			
            'options' => [
                'Black',
                'Green'
            ]
        ],
        [
            'name' => 'Size',
            'position' => 0,
            'visible' => true,
            'variation' => true,
            'options' => [
                'S',
                'M'
            ]
        ]
    ],
    'default_attributes' => [
        [
            'id' => 3,
            'option' => 'Black'
        ],
        [
            'name' => 'Size',
            'option' => 'S'
        ]
    ],
    'variations' => [
        [
            'regular_price' => '19.99',
			'manage_stock' =>true, 
			'stock_quantity'=>33,
			'in_stock'=>true,
            'image' => [
                [
                    'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_4_front.jpg',
                    'position' => 0
                ]
            ],
            'attributes' => [
                [
                    'id' => 3,
                    'option' => 'black'
                ],
                [
                    'name' => 'Size',
                    'option' => 'S'
                ]
            ]
        ],
        [
            'regular_price' => '19.99',
			'manage_stock' =>true, 
			'stock_quantity'=>99,
			'in_stock'=>true,
            'image' => [
                [
                    'src' => 'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_3_front.jpg',
                    'position' => 0
                ]
            ],
            'attributes' => [
                [
                    'id' => 3,
                    'option' => 'green'
                ],
                [
                    'name' => 'Size',
                    'option' => 'M'
                ]
            ]
        ]
    ]

Is it not posible to set the stock levels in this way?
