### ISSUE TITLE
Suggestion to improve emails customization: filter on texts

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#12207]
I suggest that, in all customer and admin emails, there's a filter applied to the texts right after the email header (the ones that are different on each email template).

It's true that the template can just be copied over and changed on the child theme, but it's also true that that method is less update/future-proof.

My experience implementing WooCommerce for clients has shown me that almost all of them want to customize this texts. I've even made a small private-use plugin that uses one global email template for all the order status and then just changes this texts based on the order status and text defined by the shop owner: https://snag.gy/EalWVo.jpg

I do think this is completely unnecessary if we have the right filters in place.

**customer-on-hold-order.php example:**
`<p><?php _e( "Your order is on-hold until we confirm payment has been received. Your order details are shown below for your reference:", 'woocommerce' ); ?></p>`
would become something like:
`<?php echo apply_filters( 'woocommerce_email_text_costumer-on-hold', '<p>'.__( "Your order is on-hold until we confirm payment has been received. Your order details are shown below for your reference:", 'woocommerce' ).'</p>' ); ?>`

**Comment by webdados** [comment]
This could also be achieved with actions.

On that scenario WooCommerce would have a default text/function hooked on the email text and then each developer could just unhook that function and hook his own text/function.

**Comment by mikejolley** [comment]
There are global WP filters you can use - gettext filter for instance. This applies to all localised text. Wrapping all strings in more custom filters seems a little overkill, and these email templates may be editable in the admin area in the future anyway meaning we'd have more legacy filters to support needlessly.

**Comment by webdados** [comment]
The gettext filter is the real overkill, because you then would have to test each and every string, just to try and find these ones and change them.

If the email templates are going to be editable in the admin area in the future, cool, that would solve it.

I just don't get why everything that goes into email templates is hook based, and these intro texts can't be. It just doesn't make sense to me.

**Comment by mikejolley** [comment]
Ideally all email content would be in settings. I'd rather that than yet more filters.

Gettext or Say what plugin are both viable for now.

**Comment by webdados** [comment]
"Ideally all email content would be in settings."

With that in mind, maybe we can ditch the different email templates and have a single one, and just having something like this to define each order status text: https://snag.gy/EalWVo.jpg

**Comment by mikejolley** [comment]
We have an issue open to redesign emails - so this can come around that time I think.
