### ISSUE TITLE
Discount coupon issue and a new cool feature 

### ISSUE THREAD

**Issue by AngeloLazzari** [woocommerce/woocommerce#12206]
## EXPLANATION OF THE ISSUE

When you create a discount that is NOT applicable to "on sale" products or to a few products, after you apply it to the cart, if you put one of the "no discount" products in that cart, woocommerce removes the coupon from the cart, completely. This is the actual logic but, as commented in this link to woocommerce support (https://wordpress.org/support/topic/potencial-bug-in-coupon-section-of-the-last-woocommerce-version/#post-8364613) a new logic that make a lot of sense can be added.

So, the new logic would be: if you have on sale products, or no discountable product, the coupon is not removed BUT is only applied to the product not on sale and not included in the "no discount" product coupon list.

Hope i explained it clearly! if not please contact me!

**Comment by mikejolley** [comment]
Change coupon type from cart to product.

**Comment by AngeloLazzari** [comment]
Hi Mike, i didn't understand the comment, please can you explain a bit more? Thank you very much!

**Comment by mikejolley** [comment]
Product coupons act how you described.

**Comment by AngeloLazzari** [comment]
ouch! i'm sorry i didn't know that (but even your customer support too... :/ ). So thank you very much!!!

**Comment by mikejolley** [comment]
@AngeloLazzari Just be aware the coupon discount amount will be applied to each product. if its % based it won't matter.

**Comment by AngeloLazzari** [comment]
ok thanks!
