### ISSUE TITLE
Errors while altering columns in db on install

### ISSUE THREAD

**Issue by Dartui** [woocommerce/woocommerce#12204]
## EXPLANATION OF THE ISSUE

I wanted to test version from github with new CRUD classes, so I cloned master branch and replaced it with latests stable version of WooCommerce. After that I received two errors:
![DB Errors](http://screenshooterusnortheu.blob.core.windows.net/engine4files/qelldpeniilzklflbvxzeibgoiklprsimjosupelpksvrfqzfcsphbrgptroltyyqqhfufgydirdrvrvrwzvsurwbjxojfhhspdw)

After refresh there is no errors.

### WordPress Environment ###

Home URL: http://localhost/localizations
Site URL: http://localhost/localizations
WC Version: 2.6.3
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pl_PL

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.12-1+deb.sury.org~xenial+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.16
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Twój serwer nie ma włączonej obsługi SoapClient - niektóre bramki płatności
które używają SOAP mogą nie działać poprawnie.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (5) ###

Query Monitor: przez John Blackbourn – 2.13.1
Contact Form 7: przez Takayuki Miyoshi – 4.5.1
Stars Rating: przez  – 1.0
WooCommerce Lokalizacje: przez Krzysztof Grabania – 1.0
WooCommerce: przez WooThemes – 2.7.0-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /index.php/sklep/
Koszyk: #5 - /index.php/koszyk/
Zamówienie: #6 - /index.php/zamowienie/
My account: #7 - /index.php/moje-konto/

### Theme ###

Name: Storefront
Version: 2.1.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Known issue (bug in WP core, trac ticket logged). Can be ignored.
