### ISSUE TITLE
Error Failed to load resource: the server responded with a status of 500 ()

### ISSUE THREAD

**Issue by Samia713** [woocommerce/woocommerce#12216]
When trying to checkout with COD payment option, the order is sent but shows an empty error message to the customer. "Like the order isn't placed" but I actually I receive a confirmation email!
Error message : 
<img width="709" alt="err1" src="https://cloud.githubusercontent.com/assets/23129132/19823941/60982f24-9d74-11e6-94cf-8869a4af497a.png">

I tried to deactivate some plugins but didn't work, I uploaded "Server IP & Memory Usage Display" plugin to check my memory space but it seems just fine! "Memory: 78.43 of 768 MB (10%) | WP LIMIT: 128 MB | PHP 5.6.27 @64BitOS "

**Comment by mikejolley** [comment]
https://terazza.sa/checkout/?wc-ajax=checkout is behind a coming soon page, so it cannot work as-is.
