### ISSUE TITLE
Stop translating REST error messages or add error codes

### ISSUE THREAD

**Issue by veisis** [woocommerce/woocommerce#12211]
It is weary bad idea to translate rest error messages.
There are no error codes for rest messages. 
How rest client application is supposed to handle errors in French if application is built to parse errors in English only?
Most of the time there are no need to expose the REST errors to the client. They tend to be too technical for average user.

**Comment by mikejolley** [comment]
There are codes - see the example in http://woocommerce.github.io/woocommerce-rest-api-docs/#errors

e.g. 

```
{
  "code": "woocommerce_rest_term_invalid",
  "message": "Resource doesn't exist.",
  "data": {
    "status": 404
  }
}
```

The code is never translated. If you spot a missing code, raise a PR or issue about that specifically.
