### ISSUE TITLE
Add Woocommerce shipping calculator in the mini-cart

### ISSUE THREAD

**Issue by bahiirwa** [woocommerce/woocommerce#12218]
## EXPLANATION OF THE ISSUE

Enhancement of the plugin. In the minicart we would like the to show the subtotal and the delivery cost depending on what shipping form is chosen then out put the total prior to going to check out page.

Thanks

**Comment by mikejolley** [comment]
We don't have immediate plans to implements this. The shipping forms are not shown until cart, same for shipping methods. In some cases, the default address (geolocation) will be wrong so shipping may be incorrect anyway.

If you need it, you can create a custom widget based on ours with more details. You'll need a developer for this.

You can also log this on http://ideas.woocommerce.com/forums/133476-woocommerce
