### ISSUE TITLE
Variation Expired Coupon

### ISSUE THREAD

**Issue by DustinHartzler** [woocommerce/woocommerce#12223]
## EXPLANATION OF THE ISSUE

In a variable product, when a sale price expires, it's still shows the sale price on the product page, but when added to the cart, it shows the regular price. When the product is saved by hitting the blue update button, the regular price begins displaying again.

## Sale Has Expired
<img width="744" alt="screen shot 2016-10-31 at 3 35 06 pm" src="https://cloud.githubusercontent.com/assets/2293077/19868851/438d423a-9f80-11e6-994a-68fdc8d4b551.png">

## Still Showing Sale Price
<img width="850" alt="screen shot 2016-10-31 at 3 34 49 pm" src="https://cloud.githubusercontent.com/assets/2293077/19868855/486d007e-9f80-11e6-8c91-c8f8603bba75.png">

## Regular price displayed in Cart
<img width="817" alt="screen shot 2016-10-31 at 3 35 30 pm" src="https://cloud.githubusercontent.com/assets/2293077/19868859/4ccddc06-9f80-11e6-8304-a4f7a0cd4068.png">

## STEPS TO REPRODUCE THE ISSUE

1. Give a variable product a sale price for a set schedule
2. Let the sale expire
3. View the product page and see the product still on sale
4. Add item to cart, view cart and see the item's regular price.

**Comment by claudiosanches** [comment]
Needs update the cache when the sale price expire.
Better check it after finish the Product CRUD.

**Comment by mikejolley** [comment]
This is taken care of in 2.7 and CRUD - caches are cleared on save.
