### ISSUE TITLE
How to auth over local (SSL for localhost)

### ISSUE THREAD

**Issue by AymanEG** [woocommerce/woocommerce#12229]
I am working on a local copy of wordpress/woocommerce , I am trying to use the REST API and cannot figure it out how to auth over local since its not SSL and HTTP (one legged) dont work for me so far

I have seen this issue : https://github.com/woocommerce/woocommerce/issues/8106 , and this solution did not work either since you changed everything in the REST API

Can any one provide a working example like this : https://github.com/helpforfitness/WooCommerce-REST-API-Client-Library-v2/blob/master/example/example.php

Regards
Ayman

**Comment by mikejolley** [comment]
Some of the libs allow you to define sslverify to false, then you can setup your local install to use HTTPS. You may have a browser warning but you can ignore.

Some clients also allow this, such as Insomnia client. I use that myself for testing.

**Comment by AymanEG** [comment]
Thanks I will try this out

What about a straight example for this oAuth 1.0 ?! The whole internet dont have one thats works

It will be awesome if you can explain one any where !
Kindly feel free to tag me at this tutorial or drop the link here

regards
Ayman

**Comment by mikejolley** [comment]
Isn't there one in rest api docs?

**Comment by AymanEG** [comment]
Really ?!In case I miss it then where ?! Actually I spent last week searching for one tutorial with an example and all other websites just skip this point also. All just point to the wiki or something with no reference to php library or something and I can not build it from scratch I am not that pro :(

I will appreciate a little help :-)

regards
Ayman

**Comment by mikejolley** [comment]
http://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

**Comment by AymanEG** [comment]
#Solved  ,Thanks for your time 

for future references thats how I solve it over local development (I use Bitnami WP stack by the way) : 

I edit the woocommerce plugin files to go for Basic auth over HTTP , its a simple if loop thats check if the website is ssl or no , and did the same with the official php client library and also edit the client options to make ssl_verify always false because the default is true

so now I can get it working providing the customer_key and secret over
1- Post man with Basic Auth only (you can find some scrernshots over other issues)
2- Insomnia  Client just cancel ssl verify from options
3- PHP script with the following code :

```
<?php

require __DIR__ . '/vendor/autoload.php';
use Automattic\WooCommerce\Client;

$woocommerce = new Client(  //Local keys so good luck with them :)
    'http://woo.dev',
    'ck_d707886e3a45ee4901399729cecdf180229d47b7',
    'cs_680eb2f7ee9ffbd6a7ee4c1b250584bc9e620fff',
    [
        'wp_api' => true,
        'version' => 'wc/v1',
    ]
);
//var_dump($woocommerce);		//Debug
use Automattic\WooCommerce\HttpClient\HttpClientException;
try {
    print_r($woocommerce->get('products'));

   /* Uncomment this section for debug
    $results = $woocommerce->get('products');
    // Last request data.
    $lastRequest = $woocommerce->http->getRequest();
    $lastRequest->getUrl(); // Requested URL (string).
    $lastRequest->getMethod(); // Request method (string).
    $lastRequest->getParameters(); // Request parameters (array).
    $lastRequest->getHeaders(); // Request headers (array).
    $lastRequest->getBody(); // Request body (JSON).

    // Last response data.
    $lastResponse = $woocommerce->http->getResponse();
    $lastResponse->getCode(); // Response code (int).
    $lastResponse->getHeaders(); // Response headers (array).
    $lastResponse->getBody(); // Response body (JSON).
    var_dump($results);
    var_dump($lastRequest);
    var_dump($lastResponse);
}catch (HttpClientException $e) {
    var_dump($e->getMessage()); // Error message.
    var_dump($e->getRequest()); // Last request data.
    var_dump($e->getResponse()); // Last response data.
*/
}
?>
```

Happy coding

regards
Ayman

**Comment by RupamShaw** [comment]
we can access ssl enabled server from localhost
 https://www.youtube.com/watch?v=886Pea2ljm0   
https://www.freecodecamp.org/news/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec/
hope this can be helpful.

**Comment by kyk0416** [comment]
https://www.damiencarbery.com/2019/07/disable-woocommerce-rest-api-authentication/

**Comment by IfhamHaider** [comment]
> #Solved ,Thanks for your time
> 
> for future references thats how I solve it over local development (I use Bitnami WP stack by the way) :
> 
> I edit the woocommerce plugin files to go for Basic auth over HTTP , its a simple if loop thats check if the website is ssl or no , and did the same with the official php client library and also edit the client options to make ssl_verify always false because the default is true
> 
> so now I can get it working providing the customer_key and secret over
> 1- Post man with Basic Auth only (you can find some scrernshots over other issues)
> 2- Insomnia Client just cancel ssl verify from options
> 3- PHP script with the following code :
> 
> ```
> <?php
> 
> require __DIR__ . '/vendor/autoload.php';
> use Automattic\WooCommerce\Client;
> 
> $woocommerce = new Client(  //Local keys so good luck with them :)
>     'http://woo.dev',
>     'ck_d707886e3a45ee4901399729cecdf180229d47b7',
>     'cs_680eb2f7ee9ffbd6a7ee4c1b250584bc9e620fff',
>     [
>         'wp_api' => true,
>         'version' => 'wc/v1',
>     ]
> );
> //var_dump($woocommerce);       //Debug
> use Automattic\WooCommerce\HttpClient\HttpClientException;
> try {
>     print_r($woocommerce->get('products'));
> 
>    /* Uncomment this section for debug
>     $results = $woocommerce->get('products');
>     // Last request data.
>     $lastRequest = $woocommerce->http->getRequest();
>     $lastRequest->getUrl(); // Requested URL (string).
>     $lastRequest->getMethod(); // Request method (string).
>     $lastRequest->getParameters(); // Request parameters (array).
>     $lastRequest->getHeaders(); // Request headers (array).
>     $lastRequest->getBody(); // Request body (JSON).
> 
>     // Last response data.
>     $lastResponse = $woocommerce->http->getResponse();
>     $lastResponse->getCode(); // Response code (int).
>     $lastResponse->getHeaders(); // Response headers (array).
>     $lastResponse->getBody(); // Response body (JSON).
>     var_dump($results);
>     var_dump($lastRequest);
>     var_dump($lastResponse);
> }catch (HttpClientException $e) {
>     var_dump($e->getMessage()); // Error message.
>     var_dump($e->getRequest()); // Last request data.
>     var_dump($e->getResponse()); // Last response data.
> */
> }
> ?>
> ```
> 
> Happy coding
> 
> regards
> Ayman

im stucking with the same issue :(

**Comment by gregg-cbs** [comment]
What file does this go into?
