### ISSUE TITLE
WordPress database error – Duplicate key name

### ISSUE THREAD

**Issue by decarvalhoaa** [woocommerce/woocommerce#12222]
## EXPLANATION OF THE ISSUE

I have notice during the upgrade of both Version 2.6.6 and 2.6.7 the following PHP notice in my logs, with debug on.

```
[28-Oct-2016 15:16:41 UTC] WordPress database error Duplicate key name 'location_type_code' for query ALTER TABLE wp_woocommerce_tax_rate_locations ADD KEY 'location_type_code' ('location_type'(40),'location_code'(90)) made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), call_user_func_array, WC_Install::check_version, WC_Install::install, WC_Install::create_tables, dbDelta
[28-Oct-2016 15:16:41 UTC] WordPress database error Duplicate key name 'location_type_code' for query ALTER TABLE wp_woocommerce_shipping_zone_locations ADD KEY 'location_type_code' ('location_type'(40),'location_code'(90)) made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), call_user_func_array, WC_Install::check_version, WC_Install::install, WC_Install::create_tables, dbDelta
```
It only happens during the update. During normal operations, there is no issue, but I don’t know whether this can have side effects.
Can this be reproduce at your end?

## STEPS TO REPRODUCE THE ISSUE

Upgrade WooCommerce from 2.6.5 to 2.6.6 or from 2.6.6 to 2.6.7 at  Admin > Dashboard > Updates

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://virtualbox-mageia.carvalho-pc/wordpress
Site URL: https://virtualbox-mageia.carvalho-pc/wordpress
WC Version: 2.6.7
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.10 (Mageia) OpenSSL/1.0.2j PHP/5.6.27
PHP Version: 5.6.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.40.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.7
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (33) ###

Polylang: by Frédéric Demarle – 2.0.7
All In One SEO Pack: by Michael Torbert – 2.3.10.2
ALO EasyMail Newsletter: by Alessandro Massasso – 2.9.3
WP Offload S3 Lite: by Delicious Brains – 1.1.1
Amazon Web Services: by Delicious Brains – 1.0
Autoptimize: by Frank Goossens (futtta) – 2.1.0
BackWPup: by Inpsyde GmbH – 3.3.4
Contact Form 7: by Takayuki Miyoshi – 4.5.1
Cookie Notice: by dFactory – 1.2.36.1
Events Maker: by dFactory – 1.6.12
Homepage Control: by WooThemes – 2.0.2
Loco Translate: by Tim Whitlock – 2.0.9
Maintenance Page: by ThemeGrill – 1.0.8
Postman SMTP: by Jason Hendriks – 1.7.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Remove query strings from static resources: by Your WP Expert – 1.3.1
Shariff Wrapper: by Jan-Peter Lambeck & 3UU – 4.3.0
Storefront Footer Bar: by WooThemes – 1.0.3
Storefront Parallax Hero Polylang Integration: by Antonio de Carvalho – 1.0.0
Storefront Parallax Hero: by WooThemes – 1.5.3
Storefront Reviews: by WooThemes – 1.0.2
Tipu Scroll To Top: by Zubair Mushtaq – 2.6
Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 0.30 (Not released)
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.37
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 1.4.6
WooCommerce Product SKU Generator: by SkyVerge – 2.2.0
WooCommerce Sequential Order Numbers: by SkyVerge – 1.7.0
WooCommerce Shipping Estimates: by SkyVerge – 2.0.0
WooCommerce: by WooThemes – 2.6.7
WooCommerce Helper: by WooCommerce – 1.7.1
WP-Lister Lite for eBay: by Matthias Krok – 2.0.13
WP Smush: by WPMU DEV – 2.4.5
WP Overnight Sidekick: by Jeremiah Prummer – 1.0.1

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #8 - /en/shop/
Basket: #9 - /en/cart/
Checkout: #10 - /en/checkout/
My Account: #11 - /en/my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Storefront Child Theme
Version: 1.1.0
Author URL: https://github.com/decarvalhoaa
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child-theme-master/woocommerce/checkout/terms.php
`

**Comment by hemnathmouli** [comment]
Happened also to me. When you uninstall and reinstall woocommerce in 2.6.7, this happens! I see this in error.log

`WordPress database error Duplicate key name 'location_type_code' for query ALTER TABLE wp_woocommerce_tax_rate_locations ADD KEY 'location_type_code' ('location_type'(40),'location_code'(90)) made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), call_user_func_array, WC_Install::check_version, WC_Install::install, WC_Install::create_tables, dbDelta`

**Comment by mikejolley** [comment]
Please search issues before, we've closed this numerous times. It's a WP core bug and doesn't affect your install https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+Duplicate+key+name+is%3Aclosed

**Comment by decarvalhoaa** [comment]
Sorry. You are right. I only searched on the open issues.
