### ISSUE TITLE
woocommerce_product_subcategories_hide_empty filter hook has the opposite result than expected

### ISSUE THREAD

**Issue by zachop** [woocommerce/woocommerce#12233]
## EXPLANATION OF THE ISSUE

I noticed that in WooCommerce v2.6.7, the `woocommerce_product_subcategories_hide_empty` hook behaves the opposite way than one would expect.

In the implementation of `woocommerce_product_subcategories` at `woocommerce/includes/wc-template-functions.php:1641` there's this conditional, to filter-out empty categories:

```
if ( ! apply_filters( 'woocommerce_product_subcategories_hide_empty', false ) ) {
	$product_categories = wp_list_filter( $product_categories, array( 'count' => 0 ), 'NOT' );
}
```

The hook's name implies that the empty categories will be hidden if the filtered value is `true`, but what happens is the exact opposite.

**Comment by mikejolley** [comment]
`apply_filters( 'woocommerce_product_subcategories_hide_empty', false )` is either false or true.

If hide empty is true, the logic does not execute.

if hide empty is false (default) the logic does. wp_list_filter removes any term with count 0. Looks correct to me.

**Comment by mikejolley** [comment]
Maybe you can show your filter, or check it without using any code?

**Comment by zachop** [comment]
> If hide empty is true, the logic does not execute.

That's the issue, precisely: if hide empty is true, the logic **should** execute, to filter-out the empty categories.
