### ISSUE TITLE
Free shipping calculation based on pre and post tax amounts. 

### ISSUE THREAD

**Issue by slash1andy** [woocommerce/woocommerce#12235]
## EXPLANATION OF THE ISSUE

Currently how you have your prices displayed in the cart/checkout determines if the Free shipping (based on spend) is applied to the total of the cart pre or post tax.

I don't think this is right, and should be either a setting itself, or just something that is decided and filterable for people disagreeing. 

If you have your prices excluding tax, and displaying excluding tax, it calculates if they qualify for Free Shipping based on the pre-tax total.

If your prices are excluding tax and showing the price on checkout including tax, then the qualification is calculated based on the post-tax amount.

If you price inclusive and display inclusive, it's post-tax.

If you price inclusive and display exclusive, it's pre-tax.

It would be confusing to the customer if it's like this, as otherwise as you wouldn’t know that you are only going over the limit including tax.

How the price is displayed in the cart shouldn't affect the total, it should just be consistently either post or pre tax.

## STEPS TO REPRODUCE THE ISSUE

Set up Free Shipping based on amount. Make a product that amount, then change the settings as mentioned earlier.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://104.131.116.80/andreww
Site URL: http://104.131.116.80/andreww
WC Version: 2.6.7
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu) mod_fcgid/2.3.9 PHP/5.5.9-1ubuntu4.9 OpenSSL/1.0.1f
PHP Version: ❌ 5.5.9-1ubuntu4.9 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 42 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.43 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.7
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (8) ###

Email Log: by Sudar – 1.9.1
Storefront Powerpack: by WooThemes – 1.2.0
WooCommerce Authorize.Net CIM Gateway: by WooThemes / SkyVerge – 2.4.1
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce PayPal Powered by Braintree Gateway: by WooThemes – 1.2.5
WooCommerce Stripe Gateway: by Automattic – 3.0.5
WooCommerce: by WooThemes – 2.6.7
WooCommerce Helper: by WooCommerce – 1.7.2

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Storefront
Version: 2.1.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Authorize.Net CIM ###

Environment: Test
Tokenization Enabled: 
````

**Comment by mikejolley** [comment]
> How the price is displayed in the cart shouldn't affect the total, it should just be consistently either post or pre tax.

As a customer, these are the only figures you can see. Basing the amount on a value you cannot actually see would be wrong. Thats why it changes.

Imagine saying to your customers "spend £10 to get free shipping" and then this not matching with the totals you can actually see.

**Comment by slash1andy** [comment]
Well that's the point though. If the display in the shop is including tax, but cart isn't then it's 2 different values from the customer's point of view.

**Comment by mikejolley** [comment]
Discounts are added on the cart page, not in the shop.

**Comment by slash1andy** [comment]
Not sure what discounts have to do with this?

**Comment by mikejolley** [comment]
Ok. Coupons which enable free shipping, and _shipping methods themselves_ are only shown on the cart page.

**Comment by mikejolley** [comment]
> filterable for people disagreeing.

`woocommerce_shipping_free_shipping_is_available` filter can be used to add or change the logic determining if free shipping is available.

**Comment by slash1andy** [comment]
Right. I replicated this with Free Shipping based on cart amount, and that's where the discrepancies showed up. 

It's switching how the Free Shipping is calculated based only on the display in the cart, not how it's displayed in the shop, or how prices are entered, as you mentioned above. 

I think it's really an issue when the displays are different between the shop and cart, and then when the way prices are entered in the backend. I'm not sure how to make all of it jive with each other.

**Comment by mikejolley** [comment]
Like I said, the prices in the shop are not visible when the shipping methods are.. When you're looking at shipping you're on the cart or checkout pages - both of those places show the prices which the shipping rules act on.

Even if you flip the logic, you're still going to have different results depending on what price you look at. There is no solution to make it "jive" if you're showing different prices in different places.

**Comment by mikejolley** [comment]
Since there has been no further comment or feedback on this I'm closing it out - I think we're correct to reflect the prices on the actual cart page where the calculations happen.

**Comment by nhui77777777** [comment]
Hello mike
I am have somewhat same thing. Free shipping requires... | Free shipping Minimum order amount so  why it calculates it on tax amount too.for shipping i used action and was able to get it.Thanks
