### ISSUE TITLE
Customer total spend is improperly calculated when order is completed

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#12237]
Using WooCommerce / WP latest, `wc_get_customer_total_spent()` almost never returns the expected result when hooked into an order status change (as you typically want to check this when the order is paid for). I *think* I've got a handle on why, here's what I'm seeing.

### To replicate 

Hook into `woocommerce_order_status_completed` and log `wc_get_customer_total_spent()`

 ```
function sv_test_customer_ltv( $order_id ) {

	$user_id = wc_get_order( $order_id )->get_user_id();
	error_log( wc_get_customer_total_spent( $user_id ) );
}
add_action( 'woocommerce_order_status_completed', 'sv_test_customer_ltv', 99 );
```

This will **always** return the value of the current order, never the total spent by the customer overall.

### What I think is happening

 1. [`wc_paying_customer()` is hooked into the same action](https://github.com/woocommerce/woocommerce/blob/2.6.7/includes/wc-user-functions.php#L172-L192) as my test snippet, and it is trying to update the `_money_spent` meta. However, this meta never exists right now, so it's only ever giving you the current order's total.

 2. The reason this never exists is because of `wc_delete_shop_order_transients( $order_id )`. Now, the order status change actions are run prior to `wc_delete_shop_order_transients( $order_id )` being called, so we shouldn't have an issue. 

 **However**, this was already called **when the order was created**, as the status is [updated from pending -> whatever]((https://github.com/woocommerce/woocommerce/blob/2.6.7/includes/abstracts/abstract-wc-order.php#L2346-L2439)).

This means that the following process happens:

1. Order is created, goes from pending to processing, on hold, etc.
2. When the status moves from pending to something else, the `update_status()` method calls `wc_delete_shop_order_transients( $order_id )` -- this [deletes the `_money_spent` user meta](https://github.com/woocommerce/woocommerce/blob/2.6.7/includes/wc-order-functions.php#L749-L788)
3. This user meta doesn't exist now; when the order is completed, `wc_paying_customer()` tries to update it; however, it only looks at the meta key (which is now gone), so the `_money_spent` meta is now only ever equal to the current order's value.

This makes it impossible to hook into an order status change and determine the customer's total LTV, as the `_money_spent` meta is not updated until the next time `wc_get_customer_total_spent()` is called (ie when viewing a report, so you never _see_ that it's wrong).

To allow developers to access `wc_get_customer_total_spent()` as part of the order lifecycle, I think you'd want to use call `wc_get_customer_total_spent()` when updating the total with `wc_paying_customer()` instead of accessing the meta directly, but I'm not sure if this is the best solution, so I haven't submitted a PR. 

Would love some feedback here on that as a proposed fix @mikejolley @claudiosanches to be sure I'm not overlooking something. The need to delete that meta in the first place while clearing order transients is also a point of consideration. thanks!

**Comment by danielbitzer** [comment]
I have also encountered this issue. A possible solution could be to add another action at the end of the update_status() method `woocommerce_after_order_status_changed`

**Comment by mikejolley** [comment]
Looks like this won't be a problem in 2.7.

The transient is cleared by the time the transition occurs. Then calls to functions like `wc_get_customer_order_count()` will get the correct total count via the new data stores :)
