### ISSUE TITLE
What is the proper way to use the Free Shipping Method?

### ISSUE THREAD

**Issue by krmagnaye** [woocommerce/woocommerce#12231]
## EXPLANATION OF THE ISSUE
What will happen if the customer didnt spend in a minimum order amount?
My aim is if the customer didnt spend in a minimum order amount, the customer will automatically pay the shipping rate of dkk 39.00

I tried to order lower amount then the shipping details says that "There are no shipping methods available. Please double check your address, or contact us if you need any help."

What should I do in the Free Shipping Method?

Woocommerce Version 2.6.4

## STEPS TO REPRODUCE THE ISSUE
If the customer spend DKK 499 and up the customer will have a free shipping (OKAY, THERE'S NO ISSUE HERE)
![sf1](https://cloud.githubusercontent.com/assets/19465728/19923230/671f257c-a121-11e6-940c-954658ca4502.JPG)

But If the customer will spend lower than DKK 499 it should be automatically have shipping fee rate of DKK 39 

It says that "There are no shipping methods available. Please double check your address, or contact us if you need any help."
![sf](https://cloud.githubusercontent.com/assets/19465728/19923156/16731bec-a121-11e6-89dc-a045f4d5bea6.JPG)

Is there any solution for this?
Thank you for your usual assistance!

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://www.kosko.dk
Site URL: http://www.kosko.dk
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.12
PHP Post Max Size: 96 MB
PHP Time Limit: 50
PHP Max Input Vars: 5000
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 96 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (32) ###

Contact Form 7: by Takayuki Miyoshi – 4.5.1
Custom Login: by Austin Passy – 3.2.5
Duplicator: by LifeInTheGrid – 1.1.18
Envato Market: by Derek Herman – 1.0.0-RC2
My Private Site: by David Gewirtz – 2.14.1
Kirki Toolkit: by Aristeides Stathopoulos – 2.3.6
Lingotek Translation: by Lingotek and Frédéric Demarle – 1.2.4
MailChimp for WordPress: by ibericode – 4.0.6
Multilingual Tools: by WPML Compatibility Team – 1.2
One Click Demo Import: by ProteusThemes – 1.3.0
Primrose: SiteOrigin Widgets: by SingleStroke – 1.2.1
SingleStroke: Post Formats: by SingleStroke – 1.1.0
Page Builder by SiteOrigin: by SiteOrigin – 2.4.16
WPML Multilingual CMS: by OnTheGoSystems – 3.5.3.1
SiteOrigin CSS: by SiteOrigin – 1.1.1
SiteOrigin Widgets Bundle: by SiteOrigin – 1.6.5
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce Stripe Gateway: by Automattic – 3.0.5
WooCommerce Gateways Country Limiter: by OnTheGoSystems – 1.4
WooCommerce QuickPay: by Perfect Solution – 4.5.6
WooCommerce: by WooThemes – 2.6.4
WP All Import: by Soflyy – 3.3.8
WP Editor: by Benjamin Rojas – 1.2.6.3
WP Instagram Widget: by Scott Evans – 1.9.8
WP Live Chat Support: by WP-LiveChat – 6.2.09
WP Rollback: by WordImpress – 1.4
WPML All Import: by OnTheGoSystems – 2.0.2
WPML CMS Nav: by OnTheGoSystems – 1.4.19
WPML Media: by OnTheGoSystems – 2.1.23
WPML Sticky Links: by OnTheGoSystems – 1.4.0
WPML String Translation: by OnTheGoSystems – 2.4.2.1
WPML Translation Management: by OnTheGoSystems – 2.2.4.1

### Settings ###

Force SSL: –
Currency: DKK (DKK)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #1129 - /butik/
Cart: #1130 - /kurv/
Checkout: #1131 - /kassen/
My Account: #1132 - /my-account/

### Taxonomies ###

Product Types: simple (simple-da)
variable (variable-da)

### Theme ###

Name: Primrose
Version: 1.2.4
Author URL: http://singlestroke.io/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
You need to add both a paid flat rate, and your free shipping rate with min spend rule, to a single zone. Either both will display, or just flat rate.
