### ISSUE TITLE
Remove product > Undo product message > Translantion partially not available 

### ISSUE THREAD

**Issue by preliot** [woocommerce/woocommerce#12249]
Expect a translation for the 'undo message' when an article is removed, however the word **undo** is never translated. Found this issue in dutch translation files.

**Problem area**

includes\class-wc-form-handler.php > line 500

`$removed_notice .= ' <a href="' . esc_url( WC()->cart->get_undo_url( $cart_item_key ) ) . '">' . __( 'Undo?', 'woocommerce' ) . '</a>';
`				

**Suggested fix**

Add **undo?** to the translation files or keep the question mark out of the string. (**Undo** is available in the translation files)

**Comment by claudiosanches** [comment]
WAT?

https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/nl/default?filters[status]=either&filters[original_id]=2964461&filters[translation_id]=43577402

Looks available in Dutch for me.

**Comment by preliot** [comment]
You are absolutely right. Turns out, i did not update the translation files, so i only found 'Undo'. Thanks for the effort!
