### ISSUE TITLE
Undefined variable: pattern in quantity-input.php on line 24

### ISSUE THREAD

**Issue by infomast** [woocommerce/woocommerce#12241]
Hi,
I found this, very often, in my log:
Undefined variable: pattern in /wp-content/plugins/woocommerce/templates/global/quantity-input.php on line 24
Undefined variable: inputmode in /wp-content/plugins/woocommerce/templates/global/quantity-input.php on line 24
Thanks.

**Comment by mikejolley** [comment]
That means the theme(?) or plugin is calling the quantity-input.php template file without providing those values. See https://github.com/woocommerce/woocommerce/blob/5605d2cc48c6f772bf7255dfa03abfff5de67051/includes/wc-template-functions.php#L1048-L1049

**Comment by gitFrank** [comment]
Hi, have the same message in my error.log again and again, every day.
What can be the reason and what the solution?

**Comment by mikejolley** [comment]
^ says above, I can't give a solution for code I don't control.

**Comment by gitFrank** [comment]
Ok. You can't solve the problem, understood.
Maybe a developer can this ala "if no value do nothing"?
