### ISSUE TITLE
Product thumbnail column filter does not work for v2.7?

### ISSUE THREAD

**Issue by WPDevHQ** [woocommerce/woocommerce#12253]
With the current version of WooCommerce I use the following code to filter the number of columns for the image gallery and it works fine.
`function genwoo_first_born_change_gallery_columns() {
	global $post, $product;	
	return 1;	
}
add_filter ( 'woocommerce_product_thumbnails_columns', 'genwoo_first_born_change_gallery_columns' );`

For v2.7 the above code does not work

I've copied the `product-image.php` to my theme and changed this line
`$columns           = apply_filters( 'woocommerce_product_thumbnails_columns', 1 );` to no effect

What am I doing wrong or what is the best way to achieve this for v2.7?

Here's what I'm trying to achieve:
![verticlethumbnails](https://cloud.githubusercontent.com/assets/16872407/20014576/753bca4a-a2af-11e6-8a63-8c2d1806df76.png)

**Comment by claudiosanches** [comment]
2.7 is still under development and much can change before a beta or RC version.

**Comment by WPDevHQ** [comment]
I understand that.

The whole point of raising the issue is so that we work in backward compatibility to avoid breaking designs going forward.

As long as you guys take that into consideration then it's all good.

**Comment by wpexplorer** [comment]
In the released 3.0 version the filter still doesn't "technically" work. The woocommerce_product_thumbnails_columns filter will change the classnames but the CSS is set to always display the thumbnails at 25%. Is the filter in place only for development purposes where the end user still has to write their own CSS for the columns? Or is the intention to have the filter actually alter the front-end in the future?
