### ISSUE TITLE
Unable to proceed with auth in "Deny | Approve" screen

### ISSUE THREAD

**Issue by dciccale** [woocommerce/woocommerce#12262]
## EXPLANATION OF THE ISSUE

Wordpress Version 4.6.1
WooCommerce Version 2.6.7
woocommerce-api Version 1.4.1

I made a link to get permissions to woocommerce users of our app which is as specified in the documentation `http://example.com/index.php/wc-auth/v1/authorize?app_name=....`

Notice that in my case I have to include "index.php" otherwise it will give a 404 and won't work. The problem is that when I'm taken to the "Deny | Approve" screen the "Approve" link has this href `http://example.com/wc-auth/v1/access_granted?app_name=....` it does NOT include "index.php" so it fails with a 404 and I can't proceed with the signing and redirection to my callback.

So I see that this url is being constructed here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-auth.php#L360

But I don't think there is anything wrong with that per-se. However I do think it should be able to construct the url from the actual path.

How can I get rid of "index.php" in my path, or fix it somehow?

## STEPS TO REPRODUCE THE ISSUE

- Create new droplet in DO with pre-installed latest wordpress
- install woocommerce plugin
- enable the api + post name permalink
- go to http://your-digital-ocean-ip.com/wp-json/wc/v1/orders

You will get a 404. But if you append "index.php" like so http://your-digital-ocean-ip.com/index.php/wp-json/wc/v1/orders it will give you a 401 which is normal because we are not passing credentials, but that is the endpoint that works for calling the api overall.

## SYSTEM STATUS REPORT

If needed I can provide it.

**Comment by claudiosanches** [comment]
> Notice that in my case I have to include "index.php" otherwise it will give a 404 and won't work.

Not true, you can configure WordPress anywhere without need to include any `index.php` in the URL.
It's very easy to do it and you can find a lot of tutorials about it.

> t does NOT include "index.php" so it fails with a 404 and I can't proceed with the signing and redirection to my callback.

Well, not sure about it, because if you are using a customized URL including `index.php` you should already know about that you need to apply it on all URLs on your WordPress...

For example almost all URLs on WordPress are formatted using `home_url()` and if you need to display the index URL will generally be used as `home_url( '/' )`. So I wander why you are not using the `home_url` filter to apply this extra `index.php`... Even more that every theme, plugin and anything on WordPress will use `home_url( '/' )`....

**Comment by dciccale** [comment]
I haven't configured the url anywhere. I just did the steps mentioned to reproduce the issue which I suppose is a default installation. I actually found that the path would work by appending index.php just by trying otherwise it was giving 404.

I am 100% sure you'll get the same result by reproducing the issue.

However, as I mentioned, I know it may not be an issue of woocommerce.

Could you point me in the right direction? on how/where to configure this?

thanks in advance

**Comment by dciccale** [comment]
When the url path is generated for the "approve" link, it should include the path from where it is being rendered.

So in my case it works appending index.php, now way arround it.. unless there is a way without having to do weird things like changing .htaccess or something like that.

Is basically stripping out part of the path which includes `index.php` so the generated link should include it as well. it is basically NOT working for me, I am able to get to the "Deny | Approve" screen but that's it, the "Approve" link is broken and should work.

I don't understand why the issue is being closed when no resolution was given

**Comment by claudiosanches** [comment]
> I am 100% sure you'll get the same result by reproducing the issue.

I'm sure too, but this don't makes your installation correct.

> Could you point me in the right direction? on how/where to configure this?

I already did it.

> So in my case it works appending index.php, no way arround it.. unless there is a way without having to do weird things like changing .htaccess or something like that.

I already said two things that you can do, but this is a issue with your WordPress installation and not WooCommerce, or you will contact each plugin and theme developer when someone is using `home_url( '/' )`?

> I don't understand why the issue is being closed when no resolution was given

Because is not an issue with WooCommerce, it's an issue with your WordPress installation and I already give you some alternatives.

**Comment by dciccale** [comment]
> but this is a issue with your WordPress installation

I just installed the default thing, as it is., and I am not using any customized url as you said before.

>  you can configure WordPress anywhere without need to include any index.php in the URL.
It's very easy to do it and you can find a lot of tutorials about it.

My wordpress is installed and running, what do I need to configure? is all set up and with woocommerce installed, everything works perfect except that for using the API urñs I have to append `index.php`. Otherwise it does not work, you can reproduce the issue. Just by following the steps.
If there should be an easy answer please tell me. Cause I can't find any easy tutorial online on how to get rid of this.

**Comment by claudiosanches** [comment]
> I just installed the default thing, as it is., and I am not using any customized url as you said before.

A default WordPress installation don't include any `index.php` on the URL.
Sorry but you keep pushing this and this is going to a wrong way.
Not that here is not a support channel for questions related to WordPress or WordPress installation.
That's why I'm locking it.
