### ISSUE TITLE
add-to-cart shortcode renders incorrectly when used in variation description

### ISSUE THREAD

**Issue by chbichsel** [woocommerce/woocommerce#12264]
## EXPLANATION OF THE ISSUE

When adding the [add-to-cart] shortcode to a Variation Description  then the page renders incorrectly. Add to cart button missing / replaced with "select options button". Price renders outside the box (when using storefront theme) 
## STEPS TO REPRODUCE THE ISSUE

1. Create a variational product
2. Add [add-to-cart id=""] shortcode to one of the variational description
3. Open product page and select variation above

**Comment by claudiosanches** [comment]
Why are you using `[add-to-cart]` inside a description of a product?

![Inception](http://i.giphy.com/aImJnc9F8Omzu.gif)

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/3apbmnd7tq3x2vl/2016-11-08%20at%2015.34.png does not render here, and shouldn't.
