### ISSUE TITLE
Include shop URL in callback_url payload after approving connection

### ISSUE THREAD

**Issue by dciccale** [woocommerce/woocommerce#12269]
## EXPLANATION OF THE ISSUE

Wordpress Version 4.6.1
WooCommerce Version 2.6.7
woocommerce-api Version 1.4.1

After approving the connection between a user's woocommerce shop and an app, [credentials are posted to a callback_url](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-auth.php#L373).
The issue is that this payload does not include the shop url of the user. Being quite useless when you receive the credentials.
Why? Because for making use of the credentials, the shop url is **required** so a middle step is needed to save partial credentials in the step where the user input the shop url to start the app approval process, and later save the other part of the credentials configurations from the `callback_url` payload. Not to mention that if the user denies the connection, then the partial credentials have to be removed. I would not consider saving this in localstorage/cookies/session, given that this information could potentially be not available, removed, or replaced from other clients.
It can be done this way, but I think it would make much more sense to receive the full credentials configuration in the `callback_url` payload to be able to save and use right away. This is how shopify does it, also seoshop and many other services.
Please consider this as a potential feature since the credentials are already sent to a secure server, the shop url could also be included.

## STEPS TO REPRODUCE THE ISSUE

[Follow the docs](http://woocommerce.github.io/woocommerce-rest-api-docs/#auto-generating-api-keys-using-our-application-authentication-endpoint)

## SYSTEM STATUS REPORT

Not needed.

**Comment by claudiosanches** [comment]
You should already collect the shop URL when you are creating the user on your system before you generate the auth URL. And when you receive the callback you are getting your user ID back too, so you can query for your user account and save the keys.

**Comment by dciccale** [comment]
Yes that's exactly what I'm doing. But i was wondering about passing all details already in that query. as many other ecommerce platforms do. Could you add it? or open a possible feature request?

**Comment by dciccale** [comment]
Also the problem with that solution is that if the user denies the connection, you have to know do an operation for removing the previously stored url. Why not just sending it all together upon sucessfull connection was approved? any logical reason?

**Comment by claudiosanches** [comment]
> Yes that's exactly what I'm doing

Ok, you are then doing this right.

> But i was wondering about passing all details already in that query. as many other ecommerce platforms do. Could you add it? or open a possible feature request?

As I said, no need to it, since requests a pre-register on your side. Note that this is not something to speed up registrations, this requires that you already have an user account in your side.
Not to mention that one user can have more than one shop in most of the cases, so in your side you should create a registration for stores too where you should collect the shop URL.

> Also the problem with that solution is that if the user denies the connection, you have to know do an operation for removing the previously stored url

Ok not a problem too, since when denied, will return the `success` as `0/false` and the `user_id` that you passed.

And the `user_id` is anything that you want to use, you can use the `user_id` generating by some hash referring your user account + your store ID in your app side. Or you can even pass your `user_id` as `1|test.com`.

**Comment by dciccale** [comment]
OK thx!
