### ISSUE TITLE
Product API should be more flexible around tags

### ISSUE THREAD

**Issue by achadee** [woocommerce/woocommerce#12267]
Currently the only way an app can make alterations to tags on a product is if we know the Woocommerce id of the tag. This means that we have to store a record on our side just to update tags on products. This seems to be overkill. A much nicer way would be to implement tags the way shopify does it - so that a product takes an array of names and slugs and updates / creates them accordingly.

**Comment by claudiosanches** [comment]
> This means that we have to store a record on our side just to update tags on products

This means that you can just use the `products/tags` endpoint to query for the product tags.
And all categories and tags on the product response returns `id`, `name` and `slug` what makes easy to query and edit the tag on `products/tags` endpoint.

Not to mention that `wp_set_object_terms()` don't really works good when you mix IDs and slugs.
And using ID is more reliable and you make sure that is unique, no mistakes about slugs that contains numbers, something that was a common problem in the past.

**Comment by achadee** [comment]
I understand what you are saying, but I shouldn't need to make 2 requests to update a single product. This will be an issue if you guys decide to implement rate limiting in the future.

Anyway thanks for the suggestion :)

**Comment by claudiosanches** [comment]
> This will be an issue if you guys decide to implement rate limiting in the future.

We never will implement something like it, even more than now we are deprecated our legacy REST API to only use the WP REST API.
