### ISSUE TITLE
Product Attributes Helper Functions

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#12273]
Already have a table for product attributes and a helper for it will help us and third party developers.

**Comment by UserName011** [comment]
Do you need help with database programming?

**Comment by claudiosanches** [comment]
@UserName011 nop. I'm saying that already have the table in the database and now it's easy to create a CRUD for it using the `WC_Data` class.

**Comment by nimmolo** [comment]
@claudiosanches metaquestion here.

Does it really make sense that product attributes are separate **taxonomies**? 

It just seems bonkers to have an extensible list of taxonomies, where the only way to find them is to search for the string "pa_" in the name, when they could all be classed under the same taxonomy and have their data so much more easily found and formatted.

Taking a step back it seems to me attributes would be able to take better advantage of core functions and hooks, not to mention REST API functions, if attributes were **terms** of a single taxonomy "product-att". The properties of each attribute would then be term meta for that term.

**Comment by claudiosanches** [comment]
Missing apply the functions now.
