### ISSUE TITLE
Shipping cache is not reset on enabling/disabling shipping method 

### ISSUE THREAD

**Issue by dangoodman** [woocommerce/woocommerce#12276]
## EXPLANATION OF THE ISSUE
On Woocommerce 2.6.7, after enabling a previously disabled shipping method in the Shipping Zones table it does not appear in the list of shipping options until the cache invalidates. It's also true for disabling an enabled method — it's not removed from the list of shipping options.

## STEPS TO REPRODUCE THE ISSUE

1. Go to the Shipping Zones -> Rest of the World.
2. Add a Free Shipping method and save.
3. Add an item to the cart and go to the cart page. Notice Free Shipping is there.
4. Disable the Free Shipping method by clicking to the Enable check mark image, save.
5. Refresh the cart page and notice Free Shipping is still there.
6. Increase quantity of the item in the cart to invalidate the shipping cache. Notice, no Free Shipping there.
7. Enable the Free Shipping method by clicking to the Disable X-mark image, save.
8. Refresh the cart page and notice Free Shipping is not there.

Screenshot:
http://image.prntscr.com/image/4119bd0843784ffbbe1366c3bfbaae6b.png.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://wp.loc
Site URL: http://wp.loc
WC Version: 2.6.7
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 5.6.26
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.15
Max Upload Size: 4 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() failed. The WooCommerce plugin updater won't work with your server. Contact your hosting provider. Error: cURL error 28: Resolving timed out after 5514 milliseconds

### Database ###

WC Database Version: 2.6.7
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (4) ###

WooCommerce: by WooThemes – 2.6.7

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My Account: #7 - /?page_id=7

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Templates ###

Overrides: –
`

**Comment by claudiosanches** [comment]
Works just fine: 

https://cloudup.com/c3R4pMthUyl

**Comment by dangoodman** [comment]
No, it doesn't.

Just installed a fresh clean WP + Woocommerce with a single product and done exactly same scenario as on your screencast. And it works like I described initially.

**Comment by dangoodman** [comment]
@claudiosanches It also doesn't work for shipping method removal and sorting. It just can't work b/c `shipping_zone_methods_save_changes()` doesn't update the transient. And it works for method addition since `shipping_zone_add_method()` clearly resets the cache.

**Comment by dangoodman** [comment]
@mikejolley Could you check that but with shipping debug disabled, which @claudiosanches apparently not able to achieve.

**Comment by claudiosanches** [comment]
Ohh yeah, shipping debug enabled, but still already fixed in 2.7.

**Comment by dangoodman** [comment]
Oh my god. No, it's not. Moreover, it's still the issue in 2.8.

I'm not sure you know that, but shipping debug mode disables shipping caching. That's why you can't reproduce the issue.

**Comment by claudiosanches** [comment]
@dangoodman https://github.com/woocommerce/woocommerce/blob/2de494e105ba88b135ebf6ba9767c9f6a9299fce/includes/class-wc-ajax.php#L2935-L3031

https://github.com/woocommerce/woocommerce/blob/e53be9501905b6e9bc6a3a14e0d98c2a9dfdc685/includes/class-wc-shipping-zone.php#L121-L142

And you don't need to be a rude, just saying about the I had forget about the shipping debug are enough.
