### ISSUE TITLE
allow to disable all emails in one button

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#12270]
In Email Notifications there is a list of 10 email configurations.
If I want to disable all emails I need to do the same operation 10 times in each of the individual setting.
This is extremely uncomfortable.

I upload backups of WooCommerce data for my test environment, every time I have to retrace these steps to avoid a case that WooCommerce  will send emails when I'm doing tests.

Please add a button\option on the email screen that if marked it will Disable/Enable all notifications.
![33](https://cloud.githubusercontent.com/assets/22069599/20051075/b22210d6-a4d5-11e6-93be-5825f5a57cc1.png)

Also, when clicking on "Save Changes" you should redirect back to the Email Screen. Staying on the same screen is pointless... once you save changes it is most likely that you wish to processed to the next one..

**Comment by claudiosanches** [comment]
No real need for batch enable or disable emails, even more than not all emails can be disabled (plugins and integrations can create emails by defaul always enabled).
And when save should always stay on the same page, the user still may change some more settings before need to leave the page.
Thanks for your input, but works just fine in the way that is today.
