### ISSUE TITLE
Requesting advice on Nginx Redis Caching, Geolocation, ...

### ISSUE THREAD

**Issue by NicoJuicy** [woocommerce/woocommerce#12285]
## EXPLANATION OF THE ISSUE
Slow ajax calls is the main driver for this issue, some plugins made it worse ( a lot)

I installed Woocommerce through EasyEngine on Nginx and Redis cache. I also use PHP 5.7 for speed improvements.

I seem to have some slow pages when enabling:
- GeoIP, disabling it makes the ajax calls faster ( but not fast enough for ajax..)
- Yoast SEO Plugin (this plugin makes it twice as worse)

All of my ajax calls seem to be very slow. Some pages i have noticed:

- ?wc-ajax=get_refreshed_fragments  (the first one i noticed)
- ?remove_item
- ?removed_item

I noticed the first issue when running pingdom: https://tools.pingdom.com/#!/bpFQIk/www.blindevis.be through Sweden (for my shop www.blindevis.be ). 

Go to:
- File Requests
- Sort By : Load Time

https://www.blindevis.be/?wc-ajax=get_refreshed_fragments seems to be the slowest page on my site ( it's twice as bad with GeoIP enabled), with 310 ms to load 1.2 kB.

## STEPS TO REPRODUCE THE ISSUE

Use pingdom and load blindevis.be or (not sure) EasyEngine on a fresh container and install:
- Wordpress with Redis Cache, letsencrypt and PHP5.7
- Install WooCommerce

## What did i check
- I did change to Twenty Twelve theme and checked the ajax call on remove item, it took 600 seconds x 3
- I found a pattern between GeoIP and Premium SEO, which led me to believe it's some sort of caching issue. ( Premium SEO made the problem 2 x as worse if GeoIP on client is enabled)

Any advice on what i should do to reduce the load time on ?wc-ajax=get_refreshed_fragments and or the ajax calls?

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: https://www.blindevis.be
Site URL: https://www.blindevis.be
WC Version: 2.6.6
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: nginx/1.10.0
PHP Version: 7.0.12-1+deb.sury.org~xenial+1
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - Wij adviseren een minimum PHP-versie 5.6. Bekijk: WordPress Benodigheden
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.6
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (33) ###

Better WordPress Minify: door Khang Minh – 1.3.3
Cloudflare: door John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.0.6

Contact Form 7 Modules: Hidden Fields: door Katz Web Services
Inc. – 2.0

Contact Form 7 Modules: Send All Fields: door Katz Web Services
Inc. – 2.0

Contact Form 7: door Takayuki Miyoshi – 4.5.1
Envato Market: door Derek Herman – 1.0.0-RC2
Mollie Payments for WooCommerce: door Mollie – 2.4.1
Nginx Helper: door rtCamp – 1.9.8
Ninja Forms: door De WP Ninjas – 3.0.14
One-Click Child Theme: door tychay – 1.6
PO/MO Editor: door Doug Wollison – 1.1.0
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 2.2.6
Sendy Widget: door Aman Saini – 1.0
WPML Multilingual CMS: door OnTheGoSystems – 3.5.3.2-b.1
TechSarathy Sendy CF7 Integration: door Rahul Taiwala – 1.1.1
Abandoned Cart Lite for WooCommerce: door Tyche Softwares – 3.2
WooCommerce DYMO Print: door bpluijms
wpfortune – 1.3.0

WooCommerce EU VAT Compliance (Free): door David Anderson – 1.10.26
Follow-Up Emails: door WooThemes – 4.4.15 – 4.4.16 is beschikbaar
WooCommerce Google Analytics Integration: door WooThemes – 1.4.0
WooCommerce Multilingual: door OnTheGoSystems – 3.9.2
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 1.5.37
WooCommerce: door WooThemes – 2.6.6
WooSidebars: door WooThemes – 1.4.3
WooCommerce Helper: door WooCommerce – 1.7.1
Yoast SEO Premium: door Team Yoast – 3.4
WP Product Feed Manager: door Michel Jongbloed – 1.2.1
WPML CMS Nav: door OnTheGoSystems – 1.4.19
WPML Media: door OnTheGoSystems – 2.1.23
WPML String Translation: door OnTheGoSystems – 2.4.2.1
WPML Translation Management: door OnTheGoSystems – 2.2.4.1
YITH WooCommerce Ajax Search: door YITHEMES – 1.4.1
YITH WooCommerce Wishlist: door YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Winkelbasis: #47 - /shop/
Winkelmand: #2704 - /winkelwagen/
Afrekenen: #2705 - /checkout/
Mijn account: #2706 - /mijn-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Blinde Vis
Version: – 0 is beschikbaar
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.1.6
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php versie - is verlopen. De core versie is 2.5.0
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

: Meer informatie over het bijwerken van verouderde templates
`

**Comment by mikejolley** [comment]
This endpoint cannot be cached by it's nature.. have you compared it's loading time to another non-cached page on your site, or without caching at all?

**Comment by ramonfincken** [comment]
Please note: that is it NOT your endpoint that is slow, it is your whole website when logged in the wp-admin or when having something in cart.

We wrote some articles about this , they are still accurate these days https://www.managedwphosting.nl/tag/ajax/
