### ISSUE TITLE
WC 2.7 - adding custom fields to billing and shipping fields

### ISSUE THREAD

**Issue by Dartui** [woocommerce/woocommerce#12282]
## EXPLANATION OF THE ISSUE
In checkout I have added custom fields to billing array and now I want to allow admin to manage that fields in order page in Billing Details section. WC 2.6 is getting value for this fields by magic __get function. As of 2.7 this is replaced by check if `$order` class has callable method and then call that method, because of CRUD I guess.
So here is my question - for what are filters that allows to edit billing and shipping fields in checkout, my account page and order page if the only way to get values of custom fields is method in order class? I know that this could be used for edit appereance of default fields, but in my opinion there should be some fallback for this, or maybe there is a way to extend order class with custom methods?
Thanks in advance for response!

**Comment by claudiosanches** [comment]
2.7 is still under development and when we start releasing RC versions we'll update our docs too.
But there is already a fallback for it that will works for now.

**Comment by renoovodesign** [comment]
Where is the documentation for accessing custom checkout fields?
I was hoping to find it here: https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-2.7.x-Developer-Migration-Notes.
