### ISSUE TITLE
Download array not returning variation id

### ISSUE THREAD

**Issue by dare-devil-arrives** [woocommerce/woocommerce#12286]
## EXPLANATION OF THE ISSUE

Till WooCommerce v2.6.4, for variable products, download array used to return values:
`$download : Array`
`(`
    `[download_url] => http://www.abc.com/?download_file=443&order=wc_order_581081e58c191&email=abc@abc.com&key=e06b8e8fcf158e518e2443bdb6eba5e7`
    `[download_id] => e06b8e8fcf158e518e2443bdb6eba5e7`
    `[product_id] => 443`
    `[download_name] => Serial Key - Variable &ndash; SKV-Black`
    `[order_id] => 700`
    `[order_key] => wc_order_581081e58c191`
    `[downloads_remaining] => `
    `[access_expires] => 2016-10-27 00:00:00`
    `[file] => Array`
        `(`
            `[name] => SKV-Black`
            `[file] => http://www.abc.com/wp-content/uploads/woocommerce_uploads/2016/06/Key-2.jpg`
        `)`
`)`

Here `[product_id] => 443` is actually variation id whose parent (variable) product id is **440**.

But from WooCommerce v2.6.5 onwards, for variable products, download array now returns values: 
`$download : Array`
`(`
   `[download_url] => http://www.abc.com/?download_file=443&order=wc_order_581081e58c191&email=abc@abc.com&key=e06b8e8fcf158e518e2443bdb6eba5e7`
    `[download_id] => e06b8e8fcf158e518e2443bdb6eba5e7`
    `[product_id] => 440`
    `[download_name] => Serial Key - Variable &ndash; SKV-Black`
    `[order_id] => 700`
    `[order_key] => wc_order_581081e58c191`
    `[downloads_remaining] => `
    `[access_expires] => 2016-10-27 00:00:00`
    `[file] => Array`
        `(`
            `[name] => SKV-Black`
            `[file] => http://www.abc.com/wp-content/uploads/woocommerce_uploads/2016/06/Key-2.jpg`
        `)`
`)`

Now here, `[product_id] => 440` is actually variable product's id.
Meaning, there is no way I have variation id of the product in the array.

I have a custom plugin which fetches variation id & order id from the download array and shows results. Now since there is no variation id in the array, it fails.

Was there any reason to remove variation id from the array?

**Comment by dare-devil-arrives** [comment]
@mikejolley @claudiosanches

**Comment by mikejolley** [comment]
Traced back to https://github.com/woocommerce/woocommerce/issues/11699

@claudiosanches Do we need to support both, or should it be product ID? Do we need variation ID in addition?

**Comment by claudiosanches** [comment]
Well, we need to start support both then, because if we redo it, will have problems with for the link in the frontend.

**Comment by mikejolley** [comment]
#12469
