### ISSUE TITLE
Paypal Standard ignores following fees when an empty fee has been added.

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#12291]
When creating an order manually in the backend and adding fees manually. If I add a fee without setting the amount. The placeholder of the fee amount shows a 0 and the fee total is calculated as 0 but the actual amount value is NULL.

However since the Fee amount is empty it is passed to PayPal as a NULL value. This causes Paypal to ignore any following fees.

I tested this with the following fees:
Custom Labor Fee €0.00
Packaging & Handling Fee €14.00

If I create a manual order with both those fees and enter a 0 in the Custom Labor Fee field I get the following when I go to Paypal:

![Setting 0](https://cloudup.com/cYAWu91GOu0+)
Image link: https://cloudup.com/cYAWu91GOu0

If I create a manual order with both those fees and do not enter any value in the Custom Labor Fee field then I get the following when I go to Paypal:

![Not setting 0](https://cloudup.com/c_3lIEfpkTD+)
Image link: https://cloudup.com/c_3lIEfpkTD

The line items which are passed to Paypal in this case are:

```
array(12) {
  ["item_name_1"]=> string(3) "One"
  ["quantity_1"]=> string(1) "1"
  ["amount_1"]=> string(5) "10.00"
  ["item_number_1"]=> string(0) ""
  ["item_name_2"]=> string(16) "Custom Labor Fee"
  ["quantity_2"]=> int(1)
  ["amount_2"]=> NULL
  ["item_number_2"]=> string(0) ""
  ["item_name_3"]=> string(24) "Packaging & Handling Fee"
  ["quantity_3"]=> int(1)
  ["amount_3"]=> string(5) "14.00"
  ["item_number_3"]=> string(0) ""
}
```

The amount_2 value is NULL. Either this line item should be ignored or the NULL value should be converted to a 0.

I tested this by adding the following to the function add_line_item in includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php

```
		if ( is_null( $amount ) ) {
			$amount = 0;
		}
```

When doing so the fees are correctly added in PayPal.

**Comment by claudiosanches** [comment]
I think that is better just try for as float.

```
wp> (float) null
=> float(0)
```

**Comment by claudiosanches** [comment]
Closing in favor of #12293
