### ISSUE TITLE
Product CRUD changes create excess "meta" queries

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce#12290]
## EXPLANATION OF THE ISSUE

I'm working on moving the WooCommerce Product Feed extension to use `wc_get_products()` instead of `get_posts`. I've come across a number of improvements for my use case (See #12289 and #12288). However, I'm still looking at my test site running an increased number of SQL queries. After looking into it, the additional queries are all of the form:

```
SELECT meta_id, meta_key, meta_value FROM wp_postmeta WHERE post_id=358 AND meta_key NOT LIKE 'wp\_%' ORDER BY meta_id
```

These are being generated by `read_meta_data()` in `abstract-wc-data.php`. My first observation is that the `WC_Product` class doesn't have a `cache_group` set, so no caching is done of the meta fetched by this function.

However - I still don't think that would solve the issues I'm seeing, since the product is only loaded once in my cache. it does seem though that this function always runs a SQL query, without checking the WordPress object cache for the data.

In my case, the post meta has already been loaded by `WP_Query`, so should be in the object cache already, and shouldn't need a DB query to retrieve it. 

## STEPS TO REPRODUCE THE ISSUE

After applying the changes in #12289 observe that calling:

```
$args = array(
	'status'      => array( 'publish' ),
	'limit'       => 1,
	'offset'      => 0,
	'return'      => 'objects',
);
wc_get_products($args);
```

results in the following queries (amongst others):

```
SELECT post_id, meta_key, meta_value FROM wp_postmeta WHERE post_id IN (360) ORDER BY meta_id ASC
```

```
SELECT meta_id, meta_key, meta_value
				FROM wp_postmeta
				WHERE post_id=360 AND meta_key NOT LIKE 'wp\_%' ORDER BY meta_id
```

The first query is run as a result of the `WP_Query` created by `wc_get_products()`. The second query is run when creating a `WC_Product` instance from the retrieved post. The query should be redundant since everything fetched by that query is already available in the object cache without having to query it again.

**Comment by leewillis77** [comment]
I'm currently running a patched version with the following changes:
https://gist.github.com/leewillis77/3f2f0e125c2bee24244c7a3235ed6aa3

It's probably not the *right* solution (it doesn't exclude meta with keys starting 'wp_' - not sure why that's required?). However, it's useful in that it does confirm that the queries can be eliminated.

**Comment by leewillis77** [comment]
Hi; 

Can this be re-opened? The changes in #12381 don't remove the duplicated queries, the test script I posted still results in the same queries I identified.

**Comment by mikejolley** [comment]
We're looking into lazy loading but your assessment of them being duplicates were wrong; WP does not cache the meta_id which we need.

**Comment by leewillis77** [comment]
Understood, but from the consumer's point of view - it's information that's already fetched.

For the product feed plugin this creates a (potentially significant) number of additional DB queries compared to WC 2.6. If it's not fixable in WC core, I'll see if I can work around it.
