### ISSUE TITLE
Filter "woocommerce_order_formatted_billing_address" does not work properly

### ISSUE THREAD

**Issue by gonzalesc** [woocommerce/woocommerce#12296]
Hi.

I want to add a value to "email template" and "the order detail", this value must be part of the address.

I used the filter : 

```
<?php
add_filter('woocommerce_order_formatted_billing_address','gowoo_add_billing_address',10,2);

function gowoo_add_billing_address($array_address,$order) {

	$array_address['test1'] = 'test2';

	return $array_address;
}
?>
```

This doesn't send nothing, the $array_address['test1'] variable is lost.

Reviewing the filter, I see that this call to the function **get_formatted_address()** in **class-wc-countries.php**:

```
<?php
//Line 456
public function get_formatted_address( $args = array() ) {
		$default_args = array(
			'first_name' => '',
			'last_name'  => '',
			'company'    => '',
			'address_1'  => '',
			'address_2'  => '',
			'city'       => '',
			'state'      => '',
			'postcode'   => '',
			'country'    => '',
		);
		$args = array_map( 'trim', wp_parse_args( $args, $default_args ) );
		extract( $args );
....
?>
```

Then, here it use "wp_parse_args" and is there where the value of $array_address['test1'] is lost, because the result of $args is:

```
<?php
$args = array(
			'first_name' => 'Example Name',
			'last_name'  => 'Example Lastname',
			'company'    => '',
			'address_1'  => 'Av Rep Panamá N67',
			'address_2'  => '',
			'city'       => 'Lima',
			'state'      => 'LMA',
			'postcode'   => '051',
			'country'    => 'PE',
			'test1'        => 
		);
?>
```

As you can see, the test1 variable is empty.

I was thinking use the filters "woocommerce_localisation_address_formats" and "woocommerce_formatted_address_replacements" but these don't have the $order_id as parameter.

Regards

**Comment by claudiosanches** [comment]
> I was thinking use the filters "woocommerce_localisation_address_formats" and "woocommerce_formatted_address_replacements" but these don't have the $order_id as parameter.

Yes, you need to use both and no need for `$order_id`.

Here an example of one of my plugins:

https://github.com/claudiosanches/woocommerce-extra-checkout-fields-for-brazil/blob/master/includes/class-wc-ecfb-front-end.php#L31-L34

**Comment by gonzalesc** [comment]
Hi.
I forgot to mention that I do need the $order_id. It turns out that this extra field, which is part of the address, is only considered if the customer chose a particular shipping method.

Then If I had the $order_id I would do it this way:

```
<?php
add_filter( 'woocommerce_formatted_address_replacements', formatted_address_replacements' ,10, 2);
public function formatted_address_replacements( $replacements, $order_id ) {
	
	$order = new WC_Order($order_id);

	foreach($order->get_items( 'shipping' ) as $el){
  		$order_shipping_method = $el['method_id'] ;
	}

	$array_method_id = explode(':',$order_shipping_method);

	if( $array_method_id[0] == 'custom_shipping' ) {

		$replacements['{number}']       = $number;
		$replacements['{neighborhood}'] = $neighborhood;r
	}
	
	return $replacements;
}
?>
```


But in these filter, I don't have the $order_id
Regards

**Comment by claudiosanches** [comment]
@gonzalesc you don't need and this not should be conditional. You can even let some fields empty.

**Comment by gonzalesc** [comment]
Ok.
I followed your example, I had to use 4 filter.

It works! Thanks!

**Comment by seldimi** [comment]
The example leads to 404, can you please share a working example?
