### ISSUE TITLE
Shipping tax rate based on products in cart setting is not predictable 

### ISSUE THREAD

**Issue by TeemuMuikku** [woocommerce/woocommerce#12300]
## EXPLANATION OF THE ISSUE
The setting of shipping tax rate "Shipping tax class based on cart items" depends on the order of input lines in setting field "Additional Tax Classes" instead of selecting an actual highest tax class rate found on cart items. 

In the source WC_Tax::get_shipping_tax_rates() there is comment that says that the highest tax rate in cart items is used for the shipping tax but the WC_Tax class doesn't do sorting of tax classes. The shipping tax rate ends up being the first matching found in "Additional Tax Classes" setting instead.

Snippet from WC_Tax::get_shipping_tax_rates()
```
// This will be per order shipping - **loop through the order and find the highest tax class rate**
$cart_tax_classes = WC()->cart->get_cart_item_tax_classes();

// If multiple classes are found, use the first one. Don't bother with standard rate, we can get that later.
if ( sizeof( $cart_tax_classes ) > 1 && ! in_array( '', $cart_tax_classes ) ) {
	**$tax_classes = self::get_tax_classes();**

	foreach ( $tax_classes as $tax_class ) {
		$tax_class = sanitize_title( $tax_class );
		if ( in_array( $tax_class, $cart_tax_classes ) ) {
			$matched_tax_rates = self::find_shipping_rates( array(
				'country' 	=> $country,
				'state' 	=> $state,
				'postcode' 	=> $postcode,
				'city' 		=> $city,
				'tax_class' => $tax_class
			) );
			break;
		}
	}
...
```

## STEPS TO REPRODUCE THE ISSUE
Set the shipping tax setting to "Shipping tax class based on cart items".
Add products having different tax classes to cart.
Change order of Tax classes in the field "Additional Tax Classes" and see how the shipping tax varies.

I'm using Woocommerce 2.6.7

**Comment by mikejolley** [comment]
It isn't possible to know which tax rate is 'highest' due to the nature of taxes. Knowing would involve calculating all tax rates in advance and comparing them before doing the 'real' calculation. That would impact performance. I'll change the comment so it's clear that it's the first listed, unless standard is present.

**Comment by TeemuMuikku** [comment]
Ok, predictable enough :) 

FYI
By highest I meant the tax rate with highest percentage value. Isn't this available in the options table since it is part of the setting? I'm not sure what is the intent with the "Shipping tax class based on cart items" option.

Our client wants shipping VAT be related to the cart contents:
There are several VAT classes, 0%, 10%, 14% and 24% for different kinds of sellable products (in Finland).
This particular client happens to cover them all with their product catalog.
They wanted that the shipping cost will have the highest VAT percentage of the cart items.

If customer adds 0% VAT product to cart, shipping VAT should be 0%.
If there are mixed products in cart and some of them have for example 24% VAT, the shipping should be with 24% VAT as well.

**Comment by mikejolley** [comment]
Yeah, since products can have multiple tax rates apply from a single table based on country and other things, using the percentage isn't really viable.

**Comment by TeemuMuikku** [comment]
Oh yeah, thanks!
