### ISSUE TITLE
Product title tag in loop

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce#12306]
Hi,

## ISSUE DESCRIPTION:

Recently I've noticed changes in product title tag in loops (in master branch, not in any publicly released version of the plugin). You went from H3 to conditional H2/3 change.

```
if ( ! function_exists( 'woocommerce_template_loop_product_title' ) ) {
	/**
	 * Show the product title in the product loop. By default this is an H3.
	 */
	function woocommerce_template_loop_product_title() {
		$tag = is_product_taxonomy() || is_shop() ? 'h2' : 'h3';
		echo '<' . $tag . ' class="woocommerce-loop-product__title">' . get_the_title() . '</' . $tag . '>';
	}
}
```

I'd like to ask whether it wouldn't be better to control this using a filter hook? 

The thing is that what if a theme counts on using a H3 tag as of current default and applies a H2 heading on the actual loop list for accessibility purposes, so to get a heading structure like this:
```
H1: Shop page title
  ...Whatever optional shop page content here...
  H2: Products list title
    H3: Product 1 title
    H3: Product 2 title
    H3: Product 3 title
    ...
```

## POSSIBLE SOLUTION:

Wouldn't it be better for backwards compatibility to use code such as:
```
if ( ! function_exists( 'woocommerce_template_loop_product_title' ) ) {
	/**
	 * Show the product title in the product loop. By default this is an H3.
	 */
	function woocommerce_template_loop_product_title() {
		$tag = apply_filters( 'woocommerce_template_loop_product_title_tag', 'h3' );
		echo '<' . tag_escape( $tag ) . ' class="woocommerce-loop-product__title">' . get_the_title() . '</' . tag_escape( $tag ) . '>';
	}
}

if ( ! function_exists( 'woocommerce_template_loop_product_title_h2' ) ) {
	/**
	 * Modifies product title to H2 in the shop and product taxonomy loop.
	 */
	function woocommerce_template_loop_product_title_h2( $tag ) {
		if ( is_product_taxonomy() || is_shop() ) {
			$tag = 'h2';
		}
		return $tag;
	}
	add_filter( 'woocommerce_template_loop_product_title_tag', 'woocommerce_template_loop_product_title_h2' );
}
```

That way it is only a matter of removing the tag modification filter in the theme to keep the code backwards compatible.

## CONCLUSION:

Surely, this is just a suggested solution, but I really think the heading tag should be controllable somehow.

Thank you for consideration!

Regards,

Oliver

**Comment by claudiosanches** [comment]
This is already a pluggable function, so you are free to override it in your theme.
Not to mention about the filter that you can use too like your example.

**Comment by jodyshop** [comment]
I have get warning from SEO reports about the repeated H2 tags too many time due to this loop:
**Your page contains many H2 tags.**

So how i can change the default H2 loop to H3?

**Comment by tara2** [comment]
I also have an ENORMOUS problem with the "You might also be interested in...."  titles - they look really awful!   How can we address this please??
