### ISSUE TITLE
CSV Suite wipes pricing when merging with parent varient product

### ISSUE THREAD

**Issue by rcojoe** [woocommerce/woocommerce#12307]
## EXPLANATION OF THE ISSUE

When I update a product,  the price no longer shows in the category until I update the _price custom field.

## STEPS TO REPRODUCE THE ISSUE

update menu_order by using the postid,  merge the changes.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://www.rockcreek.com
Site URL: https://www.rockcreek.com/gear
WC Version: 2.6.7
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.8-0ubuntu0.16.04.3
PHP Post Max Size: 8 MB
PHP Time Limit: -1
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.16
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.7
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (42) ###

Akismet: by Automattic – 3.2
Categories in Hierarchical Order: by Amit Sonkhiya
Kamal Agrawal – 1.0

Child Theme Configurator: by Lilaea Media – 2.1.2
Admin Columns: by AdminColumns.com – 2.5.6.3
Dave's WordPress Live Search: by Dave Ross – 4.5
Display Categories Widget: by Suresh Baskaran – 2.1
Display Widgets: by Strategy11 – 2.05
Disqus Comment System: by Disqus  – 2.86
Google Tag Manager for Wordpress: by Thomas Geiger – 1.4
FacetWP - Cache: by FacetWP
LLC – 1.3.2

FacetWP - Relevanssi integration: by FacetWP
LLC – 0.5

FacetWP: by FacetWP
LLC – 2.6.5

Get The Image: by Justin Tadlock – 1.0.1
KingSumo Giveaways: by KingSumo – 1.4.3
Lucky Orange | Chat, heatmaps, polls, visitor recordings, live analytics.: by LuckyOrange.com – 1.96
Max Mega Menu - StoreFront Integration: by Tom Hemsley – 0.1
Max Mega Menu: by Tom Hemsley – 2.3
Meta Slider: by Matcha Labs – 3.3.7
Page Links To: by Mark Jaquith – 2.9.6
Relevanssi: by Mikko Saari – 3.5.6.1
RootsRated Compass: by  – 1.2.1
Simple Social Icons: by Nathan Rice – 1.0.13
Title Toggle for Storefront Theme: by Wooassist – 1.2.2
SumoMe: by SumoMe – 1.21
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.23.1

WC Duplicate Order: by Jamie Gill – 1.0
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 3.2
WooCommerce Amazon Payments Advanced Gateway: by WooThemes – 1.6.2
WooCommerce CyberSource SA SOP Gateway: by WooThemes / SkyVerge – 2.6.0
WooCommerce Product CSV Import Suite: by Automattic – 1.10.12
WooCommerce ShippingEasy Integration: by WooThemes – 3.4.1
WooCommerce: by WooThemes – 2.6.7
WooCommerce Helper: by WooCommerce – 1.7.2
Yoast SEO: by Team Yoast – 3.7.1
WP All Export: by Soflyy – 1.0.9
WP All Import Pro: by Soflyy – 4.3.2
WP-Mail-SMTP: by Callum Macdonald – 0.9.5
WP Super Cache: by Automattic – 1.4.8
WP Tiles: by Mike Martel – 1.1.2
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.1
YouTube: by EmbedPlus Team – 11.5
YouTube Embed WpDevArt: by wpdevart – 1.6.6

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #26557 - /shop
Cart: #26558 - /cart
Checkout: #26559 - /checkout
My Account: #26560 - /my-account

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Storefront Child
Version: 2.1.0.1476111885
Author URL: https://woocommerce.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/archive-product.php
storefront-child/woocommerce/content-product.php

### CyberSource SA SOP ###

Environment: Live
`

**Comment by mikejolley** [comment]
Please ensure this is reported on the woothemes support site (access via your account). This issue tracker is for core only. I have notified @roykho anyhow in case it's already known.
