### ISSUE TITLE
Add button to copy billing address to shipping address.

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#12304]
when inserting order manually in the admin dashboard we require to insert both billing and shipping address.

Issues:
1. The woocommerce has a setting where shipping address could be disabled. If this setting is activated shipping address will always be as billing address. My suggestion is that once the billing address was saved (manually) then woocommerce will check the setting and if it is activated it will auto copied from billing address to shipping address. This is in fact the behavior expected as defined in the setting. (If the admin would like to change it later, he can.. same as now) but the default should be the same.
2. please add button/ability to copy the whole address from billing to shipping. In most cases its the same address and it is annoying to enter it twice.

**Comment by mikejolley** [comment]
Click this https://dl.dropboxusercontent.com/s/62taiysudxh0jny/2016-11-10%20at%2015.42.png

**Comment by UserName011** [comment]
@mikejolley please consider changing the icon. Arrow icon doesn't imply any sort of copy data action.

**Comment by shivapoudel** [comment]
@jameskoster can you please add some impressive copy icon rather than arrow :)

**Comment by jameskoster** [comment]
The icon/button to load the address from the customer profile needs work too. Let's open a new issue for this.

**Comment by shivapoudel** [comment]
Try this extension if this feature needed in frontend checkout page: https://codecanyon.net/item/woocommerce-copy-billing-details/18836341
