### ISSUE TITLE
Unable to remove actions declared by WC_Admin_Menus

### ISSUE THREAD

**Issue by fakeartist** [woocommerce/woocommerce#12303]
Version 2.6.4 of Woocommerce, Version 4.6.1 of Wordpress

Simple task as it sounds, it is not. I try to remove the action 

add_action( 'admin_menu', array( $this, 'status_menu' ), 60 );

at line 30.

But due to the class architecture I cannot. Shouldn't this be fixed?

Changing this through css is not an option.

**Comment by mikejolley** [comment]
Accessing core menus is not really something I think should be do-able, also not sure why since the entire plugin relies on those pages, as well as 3rd parties...

You can use admin_menu hook anyhow - if you use a later priority you can add and remove existing menus as you please after our functions have ran.

**Comment by fakeartist** [comment]
Thanks for you response. Allow me to disagree. I think woocommerce should give full customization options to the developers. Why not? For example, in my case, I want to remove the System status menu button and page completely for shop managers. Not just the menu button. I also want to block access to the page complete. The easy way would be to just remove the hooks. Just the usual remove_action functions. But I cannot. It seems a little strange to me the logic "once you hook something, you cannot unhook for certain classes".

**Comment by mikejolley** [comment]
> You can use admin_menu hook anyhow - if you use a later priority you can add and remove existing menus as you please after our functions have ran.

You have full customisation via the WP api. We don't need to provide you with dedicated hooks, especially for something in so little demand.

**Comment by mikejolley** [comment]
https://codex.wordpress.org/Function_Reference/remove_submenu_page

**Comment by fakeartist** [comment]
That works great! Thank you!
