### ISSUE TITLE
Password strength meter is not loaded on lost password page

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#12314]
The two scripts for password-strength-meter.js are not always loaded on the lost password page after the user goes to reset their password.

This seems to be influenced by a setting in WooCommerce > Settings > Accounts > Account Creation:
Automatically generate customer password

When this setting is enabled the password strength meter no longer shows up when resetting the password through the lost password method.

The conditions when this script are loaded are defined as follows in class-wc-frontend-scripts.php:

```
if ( is_checkout() || is_account_page() ) {
	self::enqueue_script( 'select2' );
	self::enqueue_style( 'select2', $assets_path . 'css/select2.css' );
	// Password strength meter.
	// Load in checkout, account login and edit account page.
	if ( ( 'no' === get_option( 'woocommerce_registration_generate_password' ) && ! is_user_logged_in() ) || is_edit_account_page() ) {
		self::enqueue_script( 'wc-password-strength-meter' );
	}
}
```

It seems that these conditions need to be adjusted or a new condition needs to be added for when they are on the lost password reset form.

**Comment by claudiosanches** [comment]
Solved in #12319
