### ISSUE TITLE
Preformance optimization for getting terms

### ISSUE THREAD

**Issue by danielhuesken** [woocommerce/woocommerce#12312]
An an big shop we have had trouble with many double get term queries in frontend that can be simple resolved.

All occurrence of `wp_get_post_terms()` and `wp_get_object_terms()` schould be replaced by `get_the_terms()`, because `get_the_terms()` is **cached** and the other not.

See: https://codex.wordpress.org/Function_Reference/wp_get_object_terms

**Comment by claudiosanches** [comment]
Closed in favor of #12388
Thanks.
