### ISSUE TITLE
Multisite Subdirectory - cart products taken

### ISSUE THREAD

**Issue by danielhuesken** [woocommerce/woocommerce#12311]
We have big problems with the cart in a multisite install. When we add products to the cart in site a we have the same products (ID) in the cart on site b.

This happen only on sites on a multisite with thjis configuration:

- domain.com <- Webpage
- domain.com/shop <- B2C Shop
- domain.com/wholesale <- B2B Shop

That has to with the session and cart cookies and the cart-fragments.js.

The session and cart cookies uses the `COOKIEPATH` constant that is in that installation always `/` taken from the network "Main" site. That means all the sites has the same cookies for cart and session.

The cart-fragments.js uses the Browser session and web storage that is domain wide too. This js takes the cart from shop to wholesale and reversed.

WooCommerce 2.6.7 ist only on sites activated where it will be needed.

**Comment by mikejolley** [comment]
This isn't a WC problem, this is your config for COOKIEPATH. It needs to use a different set of cookies per site to work.

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-session-handler.php#L45

If you share cookies between all 3 sites, yes the cart cookie will be set across all 3..

> The session and cart cookies uses the COOKIEPATH constant that is in that installation always / taken from the network "Main" site. That means all the sites has the same cookies for cart and session.

Blank cookiepath means it uses the current domain, which on your install is the same on all 3 sites. It has nothing to do with the main site.

**Comment by danielhuesken** [comment]
@mikejolley with the COOKIEHASH you has point me to the right direction. The problem is only that wordpress points to the site url. See https://core.trac.wordpress.org/browser/trunk/src/wp-includes/default-constants.php#L203.
Wenn i do a littel plugin that uses the home url for the COOKIEHASH it will work, but the user must login on every sub directoy site and that schould not be.

**Comment by danielhuesken** [comment]
@mikejolley the setting of the COOKIEHASH do not fix that problem, i say bevore. The Problem is that In the Browser session the 'wc_fragments' and 'wc_cart_created' ar not prefixed with the cart id! That is why they will be used for all shops with the same domain. The Session storage not  depends on cookie path! We have many trobble on our Client about this and i think that should work out of the box on multisites with WooCommerce.

**Comment by mikejolley** [comment]
Append cookie hash? If you submit a PR I'll review, busy today.

**Comment by danielhuesken** [comment]
@mikejolley Sory if have delete the comment bevore. 

The problems happens only, if you switch the blogs in the same browser tab. Because the stored fragments in the sessionstorage. We can improve it by doing
`add_filter( 'woocommerce_cart_fragment_name', function ( $name ) { return "$name-" . get_current_blog_id();} );`

The 'wc_cart_created' we can't filter so that carts of other blogs can be longer hold as wished.

The rest i thing we must do with COOKIEHASH, COOKIE_DOMAIN and COOKIEPATH that will be set in WordPress core to the network and not to a blog.

The woocommerce_cart_hash cookie has the same hash for all sites if you not do the changes to the cookie consts. 

Sorry i can't do a PR beacuse in moment i don't see all side effects.
