### ISSUE TITLE
Fixed wc_trim_zeros function

### ISSUE THREAD

**Issue by 70599** [woocommerce/woocommerce#12318]
Original outputs:
- 0.01
- 19.00
- 14.90
----
Default wc_hide_trailing_zeros : true, `wc_trim_zeros` outputs:
- 0.01
- 19
- 14.90
----
Fixed `wc_trim_zeros` outputs:
- 0.01
- 19
- 14.9
----
Default `wc_trim_zeros` function:
```php
function wc_trim_zeros( $price ) {
	return preg_replace( '/' . preg_quote( wc_get_price_decimal_separator(), '/' ) . '0++$/', '', $price );
}
```
----
Fixed `wc_trim_zeros` function:
```php
function wc_trim_zeros( $price ) {
	return preg_replace( '/' . preg_quote( wc_get_price_decimal_separator(), '/' ) . '*(0+)$/', '', $price );
}
```
----
Sorry I do not know how to create a pull request.

**Comment by mikejolley** [comment]
Sorry this isn't how the function is supposed to work. It's to remove .00 only so rounded prices are shown. We still want the entire cent figure to show (.90) if thats what the cost is.

**Comment by 70599** [comment]
Thanks for reply.

May I ask how to apply this fix by functions.php?
I need this fix, but I have to edit woocommerce source code now.

**Comment by mikejolley** [comment]
It's not a fix. There are filters if you want to change how prices display.

**Comment by 70599** [comment]
May I ask how to use filters to make the prices shows like below, without editting woocommerce source code?

- 0.01
- 19
- 14.9

Thank you.

**Comment by mikejolley** [comment]
Look at get_price_html filters and wc_get_price function.
