### ISSUE TITLE
Take cart between devices/browsers for loggtin users

### ISSUE THREAD

**Issue by danielhuesken** [woocommerce/woocommerce#12313]
This will work if you follow the steps, that you first login and then fill the cart.

But when you first fill the cart and then login it will not work! That happens because the session key is not changed to the customer id.

I now that the problem is what should we do when they already a session exists for that user.

WooCommerce: 2.6.7

**Comment by mikejolley** [comment]
Just tested in master.

1. Opened Safari.
2. Added to cart.
3. Logged in.
4. Opened Chrome (already logged in). Cart showed Safari items.

Seems fine to me. You had multisite session issues - maybe its related.
