### ISSUE TITLE
Unable to create Rest API keys from external app [Auto generating API keys using our Application Authentication Endpoint]

### ISSUE THREAD

**Issue by santhoshatandra** [woocommerce/woocommerce#12310]
Hi Everyone,

I am following this document and trying to generate API keys from my app, unfortunately its not working.

http://woocommerce.github.io/woocommerce-rest-api-docs/#introduction

I am trying to generate Rest API keys in automated flow and getting different errors for different client websites.For one client website getting app_name parameter missing, even though i adding that parameter in authorize url.

For some some clients "Invalid url" error in browser after clicking approve button from authorization page.

This is sample url .
https://demosite.com/wc-auth/v1/authorize?app_name=DEMOAPP&scope=read_write&user_id=xxxx&return_url=https://mysite.com:600/Oauth2/AuthSuccess&callback_url=https://mysite.com:600/Oauth2/WooCommerceCallback

Should i use live url?

Any help greatly appreciated.

**Comment by mikejolley** [comment]
> I am trying to generate Rest API keys in automated flow and getting different errors for different client websites.For one client website getting app_name parameter missing, even though i adding that parameter in authorize url.

NGINX site? Some servers are incorrectly configured to ignore the query string part when using permalinks. We've seen this on sites in the past and it affects much more than just the API - it also affects the frontend of the store and checkout etc.

https://codex.wordpress.org/Nginx

Sadly if the server config breaks querystring, there is nothing we can do from our side.
