### ISSUE TITLE
Latest build on wordpress.org is different to the code in this repo

### ISSUE THREAD

**Issue by dangoodman** [woocommerce/woocommerce#12330]
## EXPLANATION OF THE ISSUE
Compare `shipping_zone_methods_save_changes()`:
- Github: https://github.com/woocommerce/woocommerce/blob/2de494e105ba88b135ebf6ba9767c9f6a9299fce/includes/class-wc-ajax.php#L2935-L3031
- Wp.org: https://plugins.trac.wordpress.org/browser/woocommerce/trunk/includes/class-wc-ajax.php#L3220

Diff: https://gist.github.com/dangoodman/565d5d26dff0bbfde2ee6850dc101d32

The file isn't updated for 4 months so far.

That's probably the case for other files and previous releases too.

Originally, came from #12276.

**Comment by claudiosanches** [comment]
Yep, because as I said, this changes are to 2.7.
