### ISSUE TITLE
Toggle downloadable and toggle virtual does not work in variation bulk action

### ISSUE THREAD

**Issue by sabbir1991** [woocommerce/woocommerce#12333]
## EXPLANATION OF THE ISSUE

After some creating variations when I apply "Toggle Downloadable" or "Toggle Virtual" from variation bulk actions, it does not working. 

## STEPS TO REPRODUCE THE ISSUE

1. Create some variations
2. Change variation bulk action to "Toggle Downloadable" or "Toggle Virtual" and Apply those actions
3. Nothing changes in variations.

**Comment by claudiosanches** [comment]
Closed in #12334
