### ISSUE TITLE
Unable to remove products at the cart page

### ISSUE THREAD

**Issue by mayasl** [woocommerce/woocommerce#12332]
I have 2 issues in my woocommerce website

**Issue #1**. Please check the image below.
https://s13.postimg.org/54wimywxz/aed771a7_e2fe_4d10_4caf_231fb1b9eb41.png

_After removing wp-content/plugins/woocommerce/assets/js/frontend/checkout.min.js, it reverted back to normal state._
https://s13.postimg.org/5gdyzqddz/8579dbe0_ef26_473d_5c07_7b579ece0898.png

**Issue #2.** Unable to remove products from the cart page. I tried everything I came across in the net, but I couldn’t fix it. So, seeking help in here.

Server specs :
CentOS 6.8 (Final) , nginx/1.10.2, PHP 5.6.27 (fpm-fcgi), 5.7.16 MySQL Community Server

Other modules installed :
Memcached, OPCache

nginx.conf

```
user nginx; 
worker_processes 12;

error_log /var/log/nginx/error.log warn;

pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    		     '$status $body_bytes_sent "$http_referer" '
    		     '"$http_user_agent" "$http_x_forwarded_for"'; 

    #access_log logs/access.log main;

    sendfile on;
    tcp_nopush on; 
    tcp_nodelay on;

    keepalive_timeout 2;
    
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_buffers 32 8k;
    gzip_http_version 1.1;
    gzip_min_length 1000;
    gzip_types text/plain text/css text/js application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript application/x-font-ttf font/opentype image/svg+xml image/x-icon;
   
    server {
    	listen 80;
    	listen 443 default_server ssl;
    
    	server_name www.qtari.com;

    	if ($scheme = http) {
    	return 301 https://www.qtari.com$request_uri;
    	}
	
	client_max_body_size 32M;

	ssl_certificate /etc/nginx/ssl/qtari_bundle.crt;
        ssl_certificate_key /etc/nginx/ssl/qtari_dec.key;
        ssl_dhparam /etc/pki/tls/certs/dhparam.pem;

	add_header Strict-Transport-Security "max-age=31536000";
	
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	ssl_prefer_server_ciphers on;
   	ssl_ciphers 'ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5';
        ssl_session_cache shared:SSL:20m;
        ssl_session_timeout 10m;

	client_body_buffer_size 16k;
	
	fastcgi_buffering on;
	fastcgi_buffers 8 8k;
	fastcgi_buffer_size 8k;

  
    location / {
		try_files $uri $uri/ /index.php$args;
		root /usr/share/nginx/html/www;
		index index.php index.html index.htm;
    }
	
    error_page 404 /404.html;
		location = /404.html {
		root /usr/share/nginx/html/www;
    }
	
    error_page 500 502 503 504 /50x.html;
		location = /50x.html {
		root /usr/share/nginx/html/www;
    }

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ \.php$ {
		root /usr/share/nginx/html/www;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
    }
  }
```

**Steps I tried so far**,
1. Deactivated all plugins except WooCommerce and switched back to Twenty Sixteen theme – No luck!
2. Deactivated WooCommerce and removed all related tables from the database and reinstalled WooCoommerce – No change!
3. Cleared memory cache and OPcache [using OPcache plugin] – Nothing happened!
4. If I change the permalink to “Plain” from “Post Name”, then the things are fine.
5. I am able to remove the products by changing quantity to "0"

PS : All were working fine till I install W3 Total Cache plugin.

Please let me know if anymore details are needed.

**Comment by mayasl** [comment]
Error #1 is back after updating to WoCoomerce 2.6.8. Changing permalink setting from "Post name" to "Plain" resolves the issues.

**Comment by dougaitken** [comment]
Reading through your reproduction steps you can pinpoint the issue - you deactivated everything, and also reinstalled everything but the issue still persisted, therefore not an issue with WooCommerce. 

> PS : All were working fine till I install W3 Total Cache plugin.

This, I believe, is your issue. 

Have a look at this - https://docs.woocommerce.com/document/configuring-caching-plugins/ there are many reported issues with W3 Total Cache & WooCommerce.

**Comment by mayasl** [comment]
Don't I have a come back?

**Comment by mikejolley** [comment]
I didn't steal your keyboard. Type away! Closed due to non-replication and no updates.

**Comment by mikejolley** [comment]
FYI this is almost always a cache or theme issue.

**Comment by mayasl** [comment]
Sorry mate! I didn't reply since I didn't get any replies that solve my issue. I already read the post which dougaitken referred, before staring this thread.
I understood that the issue was caused by those caching plugins. I removed all those and cleared all cache. Even after I changed the theme to default, the issue persists.
Please help me to get rid of this, as I have to launch the website as soon as possible. My client is waiting... I am lost.
Currently, setting the permalink to "Plain" is the only solution that works.

**Comment by mikejolley** [comment]
Even disabling caching plugins may not be enough. Re enable it and turn it off in its settings, followed by flush.

**Comment by mayasl** [comment]
I will try it and come back with the result as soon as possible.

Thanks @mikejolley

**Comment by mayasl** [comment]
I tried your suggestion. But no luck!

**Comment by mikejolley** [comment]
What about resaving permalinks settings? Need a link.

**Comment by mayasl** [comment]
When the plugin was activated, but all the caching options were disabled [as per your suggestion] I tried switching the permalink settings. That made no differences. Again I tried the same, after deactivating the plugin. Still no changes.
Do you want to access my website admin panel?

**Comment by mayasl** [comment]
Fixed the issue :)
Thanks for the support @mikejolley

**Comment by Dhruvjha** [comment]
@mayasl Please let me know how you resolve the issue..

**Comment by Dhruvjha** [comment]
@mikejolley I'm having the same problem
Unable to remove the products from cart

**Comment by tkristis** [comment]
I have a problem as well. After changing a permalink to plain it solves the issue. 
But with custom permalink - (/%category%/%postname%/) it not working.

**Comment by RobertMPop** [comment]
@mayasl, so how did you fix it more precisely?

**Comment by Dhruvjha** [comment]
I changed the hosting and it works...
Let me know if you are interested to know the name of hosting company....
