### ISSUE TITLE
Variables not working in variable products page

### ISSUE THREAD

**Issue by MMaKenZi** [woocommerce/woocommerce#12335]
## EXPLANATION OF THE ISSUE
Variables not working in variable products page

I just updated my woocommerce to 2.6.8 and after this I saw that the variables frozen and not working

## STEPS TO REPRODUCE THE ISSUE
Just see a variable product and check the variables

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://#
Site URL: http://#
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.13
PHP Post Max Size: 64 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.12
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. PayPal IPN won't work with your server. Contact your hosting provider. Status code: 403
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (39) ###

Advanced Access Manager: by Vasyl Martyniuk  – 3.9.2.1
Advanced noCaptcha reCaptcha: by Shamim – 2.3
Ajax Search Pro: by Ernest Marcinko – 4.9.8
AJAX Thumbnail Rebuild: by junkcoder – 1.12
Aparat: by Nima Saberi – 1.3
Contact Form 7: by Takayuki Miyoshi – 4.5.1
Email Subscribers & Newsletters: by Icegram – 3.2.3
Envato WordPress Toolkit: by Envato – 1.7.3
Google Maps Easy: by supsystic.com – 1.6.5
Gravity Forms No CAPTCHA reCAPTCHA: by John Parks - Folkhack Studios – 1.0.7
Rainmaker- The Best Readymade WP Forms Plugin: by icegram – 0.15
Import Users from CSV: by Ulrich Sossou – 1.0.0
JC WooCommerce Advanced Attributes: by James Collings – 1.5.6
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12.1
Max Mega Menu: by Tom Hemsley – 2.3
Merge + Minify + Refresh: by Launch Interactive – 1.6.12
Mobile Address Bar Changer: by Anshul Labs – 2.0
Postman SMTP: by Jason Hendriks – 1.7.2
WooCommerce Product Filter: by Mihajlovic Nenad – 5.9.3
WP Real Media Library: by Matthias Günter – 2.6.3
Slider Revolution: by ThemePunch – 5.3.0.2
Secondary Title: by Kolja Nolte – 1.9.1
TinyMCE Advanced: by Andrew Ozz – 4.4.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com DavidAnderson – 2.12.25.22
WC Product Tabs Plus: by WooNinjas – 1.0.0
WC Vendors: by WC Vendors – 1.9.6
Widget Data - Setting Import/Export Plugin: by Voce Communications - Kevin Langley Sean McCafferty Mark Parolisi – 1.5.0
WooCommerce Product SKU Generator: by SkyVerge – 2.2.0
WooCommerce: by WooThemes – 2.6.8
WordPress Importer: by wordpressdotorg – 0.6.3
WP Rocket: by WP Media – 2.8.23
WP Scripts & Styles Optimizer: by Hendrik Lersch – 0.4.0
YITH WooCommerce Compare: by YITHEMES – 2.1.0
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #37202 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
variation (variation)

### Theme ###

Name: HandyStore
Version: 4.14 (see readme.txt for detailed changelog)
Author URL: http://themes.zone
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: handystore/woocommerce/archive-product.php
handystore/woocommerce/cart/cart.php
handystore/woocommerce/checkout/review-order.php
handystore/woocommerce/content-product.php
handystore/woocommerce/content-widget-product.php
handystore/woocommerce/loop/add-to-cart.php
handystore/woocommerce/loop/loop-start.php
handystore/woocommerce/single-product/product-image.php
handystore/woocommerce/single-product/rating.php

**Comment by MMaKenZi** [comment]
My mistake!
It was related to a conflict

**Comment by santuritanha** [comment]
You put your plugins
Until the issue is resolved
