### ISSUE TITLE
API issues with fulfillment

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#12342]
## EXPLANATION OF THE ISSUE

I'm using WordPress 4.6.1 with WC version 2.6.8.

My site connects to the remote fulfillment app from other company. Once the customer places an order, WC will send order to the Fulfillment app. 

The problem we have is that some orders aren't sent to Fulfillment App. That means WC doesn't send anything to it. We tried to debug but no luck. How can I find the bottleneck, fix or workaround?

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

`
### WordPress Environment ###

WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.2
PHP Version: 5.6.99-hhvm
PHP Post Max Size: 
PHP Time Limit: 0
PHP Max Input Vars: 
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 0 B
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (21) ###

Contact Form 7: by Takayuki Miyoshi – 4.5.1
Google Authenticator: by Henrik Schack – 0.48
Jetpack by WordPress.com: by Automattic – 4.3.2
McAfee SECURE: by McAfeeSECURE – 1.6.3
Ninja Forms: by The WP Ninjas – 3.0.11
PixelYourSite PRO: by PixelYourSite – 4.0.4
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.0.2
Recover Abandoned Cart: by Fantastic Plugins – 14.1
Redirection: by John Godley – 2.4.5
Redis Object Cache: by Till Krüss – 1.3.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SEO Optimized Images: by priyanshu.mittal – 1.6.2
WooSwatches - Woocommerce Color or Image Variation Swatches: by parbat chaudhari – 2.2.8
WooCommerce Stripe Gateway: by Automattic – 3.0.6
WooCommerce MailChimp Subscribe: by SeedProd – 1.0.8
WooCommerce Table Rate Shipping: by Bolder Elements – 3.6.6
WooCommerce: by WooThemes – 2.6.8
Yoast SEO: by Team Yoast – 3.7.1
WP Rocket: by WP Media – 2.8.23
Yoast WooCommerce SEO: by Team Yoast – 3.0
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome 3.1.6
Version: 3.1.6
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome-new/woocommerce/archive-product.php
flatsome-new/woocommerce/cart/cart-empty.php
flatsome-new/woocommerce/cart/cart.php
flatsome-new/woocommerce/checkout/form-checkout.php
flatsome-new/woocommerce/checkout/form-coupon.php
flatsome-new/woocommerce/checkout/thankyou.php
flatsome-new/woocommerce/content-product.php
flatsome-new/woocommerce/content-product_cat.php
flatsome-new/woocommerce/content-single-product.php
flatsome-new/woocommerce/global/breadcrumb.php
flatsome-new/woocommerce/global/quantity-input.php
flatsome-new/woocommerce/global/wrapper-end.php
flatsome-new/woocommerce/global/wrapper-start.php
flatsome-new/woocommerce/loop/loop-end.php
flatsome-new/woocommerce/loop/loop-start.php
flatsome-new/woocommerce/loop/orderby.php
flatsome-new/woocommerce/loop/pagination.php
flatsome-new/woocommerce/loop/result-count.php
flatsome-new/woocommerce/loop/sale-flash.php
flatsome-new/woocommerce/myaccount/form-login.php
flatsome-new/woocommerce/myaccount/navigation.php
flatsome-new/woocommerce/notices/error.php
flatsome-new/woocommerce/notices/notice.php
flatsome-new/woocommerce/notices/success.php
flatsome-new/product-searchform.php version - is out of date. The core version is 2.5.0
flatsome-new/woocommerce/single-product/price.php
flatsome-new/woocommerce/single-product/product-image.php
flatsome-new/woocommerce/single-product/product-thumbnails.php
flatsome-new/woocommerce/single-product/related.php
flatsome-new/woocommerce/single-product/review.php
flatsome-new/woocommerce/single-product/sale-flash.php
flatsome-new/woocommerce/single-product/short-description.php
flatsome-new/woocommerce/single-product/tabs/tabs.php
flatsome-new/woocommerce/single-product/title.php
flatsome-new/woocommerce/single-product/up-sells.php
flatsome-new/woocommerce/single-product-reviews.php
flatsome-new/woocommerce/single-product.php

: Learn how to update outdated templates
`

**Comment by claudiosanches** [comment]
> My site connects to the remote fulfillment app from other company. How can I find the bottleneck, fix or workaround?

How since this Fulfillment App is not from WooCommerce core?
It's best you contact the support your "Fulfillment App" from other company, since it's not a WooCommerce issue.
