### ISSUE TITLE
Improve tax list usability (filtering)

### ISSUE THREAD

**Issue by scrobbleme** [woocommerce/woocommerce#12347]
## EXPLANATION OF THE ISSUE

We have a very large tax list (~6000 entries), as we imported tax rates from TaxRates.com

The problem is/was that we still hat a generic fallback somewhere within the list. Using the standard search it wasn't possible to find this. Also paging through all 50+ pages isn't really an option.

My workaround: removing the entry through the database.

## STEPS TO REPRODUCE THE ISSUE

Just import a lot from taxrates.com and try to find the generic rule
Here is an export, which can be imported into WooCommerce: [tax_rates.txt](https://github.com/woocommerce/woocommerce/files/589186/tax_rates.txt)

## Suggestion

Add more filter options like in other views:

- (my personal favorite) Select box for Country Code and State (which could contain all values)
- Specific search boxes for postal code, country, tax
- Filter for shipping/compound: yes/no

**Comment by mikejolley** [comment]
@scrobbleme I don't think we'll be introducing search in the current incarnation, but we're going to be working on a new interface in the future powered by React. This is a future item. cc @jameskoster Worth keeping open, or close for s9n?

**Comment by scrobbleme** [comment]
@mikejolley Thank you for your response. Any improvement helps.

Another idea I had while thinking about this issue, is to do something like "tax zones", similar to shipping zones:

- Every tax zone can be bound to one or more country (US, Germany, EU ...) -> So a first simple grouping
- and there is always a zone "Rest of World" with the lowest priority
- Within each tax zone one or multiple "tax methods" can be added
  - The current one is available by default
  - Developer could add custom ones, for instance to automatically receives tax rates from some online service

**Comment by jameskoster** [comment]
@mikejolley Entirely up to you. We've already accounted for this in s9n.

Seems like a nice enhancement for core. Depends how much work it is?

**Comment by mikejolley** [comment]
> We've already accounted for this in s9n.

We'll leave it for that project; making the screen twice makes no sense at this point.
