### ISSUE TITLE
Allow to choose which encoding to set.

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#12341]
Currently the owner of the store has no say of what encoding woocommerce accept.
For example if I want only English letters I can't force it on the user..
This cause entrance of data which I can not understand and my printer can not print.
![4566](https://cloud.githubusercontent.com/assets/22069599/20257004/8c43ef54-aa4f-11e6-8260-31ae165e88a1.png)

**Comment by claudiosanches** [comment]
You need to set the encoding on WordPress. Not on WooCommerce.

**Comment by UserName011** [comment]
@claudiosanches  where exactly?

**Comment by mikejolley** [comment]
https://codex.wordpress.org/Editing_wp-config.php#Database_character_set

**Comment by UserName011** [comment]
@mikejolley  I'm aware that it is possible to change the database itself.. However this won't reflect on what the user is typing. There should be a mechanism where the user won't be able to type unsupported characters... 

With this way of changing the database encoding the user will still be able to type other chars and only when data is trying to be inserted the data base will raise error. This is not a good solution.

Where can I send a feature request to Word Press?

**Comment by mikejolley** [comment]
You can customise checkout fields and add validation rules in that case. This doesn't sound like something WordPress should do.
