### ISSUE TITLE
Inaccurate comments count due to webhook logs (webhook_delivery comment type)

### ISSUE THREAD

**Issue by mdorchain** [woocommerce/woocommerce#12344]
Hi,

There is a missing exclusion of the webhook logs (webhook_delivery) in the comment count. 
They don't show in the comments but they are still counted.
Currently only the order_note comment_type is excluded from the count.
I think the comment type webhook_delivery should also be excluded in wp_count_comment().

For reference:
https://docs.woocommerce.com/wc-apidocs/source-class-WC_Comments.html#258

Thank you

Michael

**Comment by claudiosanches** [comment]
Closed in favor of #12368, thanks for report it.
