### ISSUE TITLE
Child products with catalog visibility: search not linked from parent

### ISSUE THREAD

**Issue by oceaness** [woocommerce/woocommerce#12350]
## EXPLANATION OF THE ISSUE

Products appearing under a grouped product do not automatically get an `a href` link to the specific product page when catalog visibility is set to search or hidden.

A customer can still get directly to the child page via the search function if the catalog visibility is set to search, so it seems illogical not to place that same link on the grouped product page.

Also to consider; even if the Catalog visibility is set to hidden there may be specific descriptions/images on the child product page that are not visible from the parent product, so a link may still be desired or even required.

## STEPS TO REPRODUCE THE ISSUE

Tested under WP 4.6.1 with WC 2.6.8 using default Twenty Sixteen and Storefront themes with no customisation.

1. Create "0 Test Parent" grouped product with SKU 0TP
2. Create "1 Test Child" simple product linked to 0TP parent with Catalog visibility: Catalog/search
3. Create "2 Test Child" simple product linked to 0TP parent with Catalog visibility: Search
4. First child will have an `a href` link to it's own product page, second child will not:

![1](https://cloud.githubusercontent.com/assets/11654752/20269572/ab42dde4-aa7b-11e6-9b84-56eae53f5472.png)

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://fairalls.uk
Site URL: http://fairalls.uk
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: nginx/1.11.5
PHP Version: 5.6.27-1~dotdeb+7.1
PHP Post Max Size: 20 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: N/A
SUHOSIN Installed: –
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.8

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #3 - /
Basket: #4 - /shop/cart/
Checkout: #8 - /shop/checkout/
My Account: #6 - /shop/my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront
Version: 2.1.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by claudiosanches** [comment]
By design only visibly products have permalinks on group products.
The idea is to the group be the entire product, if you need links you can put all members of the group as public.

**Comment by claudiosanches** [comment]
But feel free to do it in your own store removing the `$product->is_visible()` from: https://github.com/woocommerce/woocommerce/blob/release/2.6/templates/single-product/add-to-cart/grouped.php#L64

**Comment by oceaness** [comment]
In our use case we want the members of the group to be linked so customers can get information specific to that particular member of the group, but don't want the individual members visible in the catalog or search pages. With your code amendment it now works with visibility set to hidden or search as well.
Thanks very much for your help.

For reference in case anyone else ever sees this and wants to do the same, you also need to remove the OR at the end of the line 64.

Copy:
`/wp-content/plugins/woocommerce/templates/single-product/add-to-cart/grouped.php`
To:
`/wp-content/themes/YOUR-CHILD-THEME/woocommerce/single-product/add-to-cart/grouped.php`
Change the following line from:
`<?php echo $product->is_visible() ? '<a href="' . esc_url( apply_filters( 'woocommerce_grouped_product_list_link', get_permalink(), $product_id ) ) . '">' . get_the_title() . '</a>' : get_the_title(); ?>`
To:
`<?php echo '<a href="' . esc_url( apply_filters( 'woocommerce_grouped_product_list_link', get_permalink(), $product_id ) ) . '">' . get_the_title() . '</a>' ; ?>`
