### ISSUE TITLE
get products limit per_page 100

### ISSUE THREAD

**Issue by WaldenStew** [woocommerce/woocommerce#12355]
On API, I would like to get all products by 
woo->get("products") 
but I only have 10 by default;

If i use parameter 'per_page'), I increase the result to 100.(max)
There is a solution to get all the products ??

Woocommerce 2.6.4 
 WP 4.5.4

Thx

**Comment by mikejolley** [comment]
100 is the max. You can get more using multiple requests and the pagination. Unlimited in 1 request could overload the server.

**Comment by ikramsyakir** [comment]
hey @mikejolley can i change the limit to get all products?

**Comment by mikejolley** [comment]
> 100 is the max
