### ISSUE TITLE
multiselect list box not working in modal dialog

### ISSUE THREAD

**Issue by bobbingwide** [woocommerce/woocommerce#12352]
## EXPLANATION OF THE ISSUE

I'm developing an enhancement to my WooCommerce shipping extension, adding a multiselect list box to the instance_form_fields

'allowed_shipping_classes' => array(
'title' => __( 'Allowed shipping classes', 'oik-weight-zone-shipping-pro' ),
'type' => 'multiselect',
'description' => __( 'Choose the allowed shipping classes when Restrict shipping classes is checked.', 'oik-weight-zone-shipping-pro' ),
'default' => '',
'options' => $product_shipping_classes
)

When displayed in the normal settings page ( page=wc-settings&tab=shipping&instance_id=1)  you can select the Shipping classes and they are correctly saved.
![image](https://cloud.githubusercontent.com/assets/2474435/20272260/4ce32b96-aa85-11e6-9cde-a7834026295a.png)

If I add `'class' => 'wc-enhanced-select',` to the field definition it also works fine on the normal page. 

When these settings are displayed in the modal dialog they are shown correctly, but when you save them they are all deselected. 

The AJAX request appears to be badly formed
It passes a single value for the field. The last item selected. 

` [woocommerce_oik_weight_zone_shipping_allowed_shipping_classes[] => 8`

I believe it should be passing an array
  `  [woocommerce_oik_weight_zone_shipping_allowed_shipping_classes] => Array
        (
            [0] => 8
            [1] => 10
        )`

## STEPS TO REPRODUCE THE ISSUE

You can easily reproduce the problem by changing the Flat Rate method's Tax status field to multiselect.
```
'tax_status' => array(
'title' 		=> __( 'Tax Status', 'woocommerce' ),
'type' 			=> 'multiselect',
'class'         => 'wc-enhanced-select',
'default' 		=> 'taxable',
'options'		=> array(
	'taxable' 	=> __( 'Taxable', 'woocommerce' ),
	'none' 		=> _x( 'None', 'Tax status', 'woocommerce' )
)
```

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://qw/src
Site URL: http://qw/src
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.7-beta2-39142-src
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.18 (Win64) OpenSSL/1.0.2e PHP/7.0.7
PHP Version: 7.0.7
PHP Post Max Size: 25 MB
PHP Time Limit: 121
PHP Max Input Vars: 1000
cURL Version: 7.47.1
OpenSSL/1.0.2e

SUHOSIN Installed: –
MySQL Version: 5.6.15
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (3) ###

oik bwtrace: by bobbingwide – 2.0.12
oik weight zone shipping pro: by bobbingwide – 0.1.0
WooCommerce: by WooThemes – 2.6.8

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #109 - /shop/
Cart: #110 - /cart/
Checkout: #111 - /checkout/
My Account: #112 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Twelve
Version: 2.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by bobbingwide** [comment]
Ah, I've determined that this is a duplicate of #11703 and that the fix for that works for my multiple select list.

**Comment by bobbingwide** [comment]
Note: The text in the issue does not match the screenshot. 
In the fixed version the server sees
```
            [woocommerce_oik_weight_zone_shipping_allowed_shipping_classes] => Array
                (
                    [0] => 8
                    [1] => 10
                )
```

As expected.

**Comment by bobbingwide** [comment]
Ah, I closed it too quickly. The solution doesn't work when only one item is selected.

**Comment by bobbingwide** [comment]
When there's only one item selected in the multi select list it's not passed to the server as an array. Looks like we need to makearray the first time we see the square brackets.

**Comment by mikejolley** [comment]
@bobbingwide This is not a bug.

Go stick this on a page and var dump the posted value:

```
<form method="POST">
	<select name="test_multiple[]" multiple="multiple">
		<option value="1">test</option>
		<option value="2">test 2</option>
	</select>
	<input type="submit" />
</form>
```

It's a string if you post 1 option. Not an array.

**Comment by bobbingwide** [comment]
Don't close it yet, the round trip does not work.

**Comment by mikejolley** [comment]
? It's standard multiselect behavior.

**Comment by bobbingwide** [comment]
Hi Mike, that's not what I'm seeing with the Flat rate method modified so that Tax status is multiselect. 
It works in the normal settings ( wp-admin/admin.php?page=wc-settings&tab=shipping&instance_id=3 ) but not in the modal dialog ( wp-admin/admin-ajax.php?action=woocommerce_shipping_zone_methods_save_settings )

From the wc-settings page, with one item selected
```
<select multiple="multiple" class="multiselect " name="woocommerce_flat_rate_tax_status[]"
 id="woocommerce_flat_rate_tax_status" style=""> 
 <option value="taxable" selected="selected">Taxable</option>
 <option value="none">None</option>
 <option value="other">Other</option>
</select>
```

```
_REQUEST Array
(
    [page] => wc-settings
    [tab] => shipping
    [instance_id] => 3
    [woocommerce_flat_rate_title] => Flat Rate
    [woocommerce_flat_rate_tax_status] => Array
        (
            [0] => taxable
        )

    [woocommerce_flat_rate_cost] => 0
    [woocommerce_flat_rate_class_cost_62] => 
    [woocommerce_flat_rate_class_cost_63] => 
    [woocommerce_flat_rate_no_class_cost] => 
    [woocommerce_flat_rate_type] => class
    [save] => Save changes
    [_wpnonce] => 1fdd545ac9
    [_wp_http_referer] => /wp44/wp-admin/admin.php?page=wc-settings&tab=shipping&instance_id=3
)
```

From the modal dialog HTML is the same
but the request is
```
_REQUEST Array
(
    [action] => woocommerce_shipping_zone_methods_save_settings
    [wc_shipping_zones_nonce] => 08be4b3b4f
    [instance_id] => 3
    [data] => Array
        (
            [woocommerce_flat_rate_title] => Flat Rate
            [woocommerce_flat_rate_tax_status] => taxable
            [woocommerce_flat_rate_cost] => 0
            [woocommerce_flat_rate_class_cost_62] => 
            [woocommerce_flat_rate_class_cost_63] => 
            [woocommerce_flat_rate_no_class_cost] => 
            [woocommerce_flat_rate_type] => class
            [instance_id] => 3
        )

)
```

The round trip doesn't work. On redisplay there are no items selected in Tax Status.

**Comment by bobbingwide** [comment]
Before
![image](https://cloud.githubusercontent.com/assets/2474435/20455023/e333aa96-ae48-11e6-9ac0-80e08241dead.png)
After
![image](https://cloud.githubusercontent.com/assets/2474435/20455026/f3c6406c-ae48-11e6-8fca-277b781f9095.png)

3 items selected ( after screenshot only )
![image](https://cloud.githubusercontent.com/assets/2474435/20455033/1403d222-ae49-11e6-8c33-b34785ae0ca5.png)

**Comment by bobbingwide** [comment]
```
if ( item.name.indexOf( '[]' ) != -1 ) {
  item.name = item.name.replace( '[]', '' );
  data[ item.name ] = $.makeArray( data[ item.name ] );
  data[ item.name ].push( item.value );
} else {
  data[ item.name ] = item.value;
}
```

**Comment by mikejolley** [comment]
@bobbingwide I think you're either missing your point or I don't understand your issue. 

https://github.com/woocommerce/woocommerce/issues/12352#issuecomment-261646106

This form, in a regular page, post it and var dump the value. Multiselects only post as arrays when multiple values are selected. Our code does not and should not change this.

**Comment by bobbingwide** [comment]
Hi Mike. In my experience the var_dump() always shows it as an array when one or more items is selected. Add `<?php var_dump( $_POST );` to your form. 

This is the evidence from the print_r() output shown for the modified Flat rate method.

So, to restate the problem.

When a multiselect list box is used in a modal dialog and only one item is selected by the user, then the server treats this as if no items were selected. This problem occurs when the request is the AJAX request. 



Method | Items selected | Server sees
--------- | --------------- | ----------------
page=wc_settings&tab=shipping | n | array of n items
page=wc_settings&tab=shipping | 1 | array of 1 item
action=woocommerce_shipping_zone_methods_save_settings | n | array of n items
action=woocommerce_shipping_zone_methods_save_settings | 1 | string

The modified JavaScript for `backbone-modal.js` resolved the problem when only 1 item is selected
as passes an array of 1 item.

**Comment by mikejolley** [comment]
> Hi Mike. In my experience the var_dump() always shows it as an array when one or more items is selected. Add <?php var_dump( $_POST ); to your form.

Test again. This gives a string when one item is chosen.

```
var_dump( $_POST['test_multiple'] );
```

**Comment by bobbingwide** [comment]
![image](https://cloud.githubusercontent.com/assets/2474435/20476930/4db41670-afcb-11e6-8e58-20af50cfe4c9.png)

That's on Chrome. Same on Firefox. 
What do you get? 
Are you sure you're not misreading the var_dump output? 
Have you tried changing `woocommerce\includes\shipping\flat-rate\includes>vs settings-flat-rate.php` to reproduce the problem?

**Comment by mikejolley** [comment]
Maybe I left off square brackets.

**Comment by bobbingwide** [comment]
Hi Mike, it was hard work finding official documentation to confirm how data for a multiple select list is expected to be passed. Stackoverflow suggested that PHP has a lot to do with the square bracket method. 
I'll generate the PR.

**Comment by malviyaritesh** [comment]
The issue is still there and can be reproduced as mentioned in this SO [question](https://stackoverflow.com/questions/49857005/multiselect-not-displaying-correctly-inside-instance-settings-modal-woocommerc).

**Comment by artprojectgroup** [comment]
Any update for this old bug that remains uncorrected?

Best regards.
