### ISSUE TITLE
Tweak icon used to load the address from the customer profile

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#12357]
![2016-11-10 at 15 42](https://cloud.githubusercontent.com/assets/3774827/20303531/e78d1106-ab53-11e6-8caa-e34d91911ffe.png)

@jameskoster Since this arrow icon don't seem accurate for copy can this icon be tweak :)

**Comment by jameskoster** [comment]
Already created an issue [here](https://github.com/woocommerce/woocommerce/issues/12356) xD
