### ISSUE TITLE
woocommerce_placeholder_img filter hook is not working

### ISSUE THREAD

**Issue by GitHub-Mike** [woocommerce/woocommerce#12358]
Hello,

I would like to report a bug.

The woocommerce_placeholder_img filter hook is not working.

```
function custom_fix_thumbnail() {
  function custom_wc_placeholder_img( $img, $size, $dimensions ) {
    return '<img src="' . wc_placeholder_img_src() . '" alt="test_alt" title="test_title">';
  }
  add_filter('woocommerce_placeholder_img', 'custom_wc_placeholder_img');
}
add_action( 'init', 'custom_fix_thumbnail' );
```

The filter hook is not called.

I can remove the function wc_placeholder_img() in wp_product_functions.php (296-300) and get no error after that.

On the other hand the woocommerce_placeholder_img_src filter hook works without issues.

I use WooCommerce 2.6.7 with WordPress 4.6.1

**Comment by GitHub-Mike** [comment]
Sorry,

it is a issue with the single-product/product-image.php Template.

Line 47:

`echo apply_filters( 'woocommerce_single_product_image_html', sprintf( '<img src="%s" alt="%s" />', wc_placeholder_img_src(), __( 'Placeholder', 'woocommerce' ) ), $post->ID );`

Why "$product->get_image()" is not used?

'woocommerce_single_product_image_html' filter hook would not really be necessary

**Comment by mikejolley** [comment]
wc_placeholder_img_src has a filter. This is changing in 2.7 anyway so no need to change the template right now - there are other filters available.
