### ISSUE TITLE
Wrong Order Currency

### ISSUE THREAD

**Issue by saschametz** [woocommerce/woocommerce#12366]
## EXPLANATION OF THE ISSUE

I have a multi currency store where every order can have a different currency.
For Example: My base currency is **€**
Now i have an order in **£**
In the Back-End it shows every value in the order in **£** except the Custom Fee

## STEPS TO REPRODUCE THE ISSUE

1. Create new order
2. Add product, shipping and fee
3. Change the order currency (Database: wp_postmeta ->  _order_currency)

Order with base curreny:

![005](https://cloud.githubusercontent.com/assets/23498536/20344371/c6691fd4-abf2-11e6-8745-b5fd7da188e4.png)

Order with different currency:

![006](https://cloud.githubusercontent.com/assets/23498536/20344376/c9c37e86-abf2-11e6-906a-2aa4b9e098fa.png)

**Comment by claudiosanches** [comment]
Closed in favor of #12372
Thanks for report it.
