### ISSUE TITLE
Export CSV button missing in IE11 on Win7

### ISSUE THREAD

**Issue by geeklore** [woocommerce/woocommerce#12362]
## EXPLANATION OF THE ISSUE

When viewing the reports, I expect to be able to export via CSV. Using Windows 7 and IE11, the button is not there. On Edge it's there but does nothing.

## STEPS TO REPRODUCE THE ISSUE

1.  Navigate to Reports in WooCommerce and look for the Export CSV button on Windows 7 IE11 or Edge.

When viewing the source it looks like the button has display:none?

```/woocommerce/assets/js/admin/reports.js```

```
var a = document.createElement( 'a' );

    if ( typeof a.download === 'undefined' ) {
        $( '.export_csv' ).hide();
    }
```

For some reason it's undefined.

**Comment by mikejolley** [comment]
Since this is JS based it's not supported on IE https://github.com/woocommerce/woocommerce/issues/9520

We may build a php based exporter in the future, but for now it's a wontfix.
