### ISSUE TITLE
Coupon form removed from checkout page on page load

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce#12361]
## EXPLANATION OF THE ISSUE

WooCommerce supports applying multiple coupons using the forms posting via Ajax.  However, if a coupon has been applied on the cart page and the customer moves on the the checkout page, the coupon form is no longer present.  Furthermore, removing coupons via Ajax on the checkout page doesn't update the page, so the coupon form isn't re rendered.  The page must be refreshed before the coupon form appears. 

## STEPS TO REPRODUCE THE ISSUE

1. Add a coupon on the cart page and proceed to checkout
2. Notice the coupon form isn't there
3. While on the checkout page, remove the coupon
4. The coupon form doesn't return
5. Refresh the page and the coupon form returns

**Comment by WPprodigy** [comment]
The coupon form on the checkout page is intentionally removed if a coupon was added in the cart.

I suppose it could return though if all coupons are removed on the checkout page.

**Comment by mdmoore** [comment]
>The coupon form on the checkout page is intentionally removed if a coupon was added in the cart.

Is there a reason?  Why would the coupon form ever need to be removed?

**Comment by claudiosanches** [comment]
@mikejolley do you know the reason?

But I think that we can close this issue since we are already reviewing the checkout flow in #10672.

@mdmoore for now you can always display the coupon message, just need to change this template:
https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/form-coupon.php#L27

**Comment by WPprodigy** [comment]
Here is the history of why: https://github.com/woocommerce/woocommerce/issues/9099

**Comment by claudiosanches** [comment]
So it's your fault @WPprodigy  :stuck_out_tongue_closed_eyes:
But to be honest I think that the coupon message/input should be inside or before the "Your order" section, should be always there too.
But this is something better to think about while reviewing the checkout flow, so I'm closing it for now.
