### ISSUE TITLE
Woo Commerce REST API issue on  placing Order.

### ISSUE THREAD

**Issue by pkhutal** [woocommerce/woocommerce#12360]
I am using Woo Commerce REST API to place order from Mobile App to website. But after placing order from App using REST API, it automatically adds the TAX to order total  but same is not case with website. Its works fine on website.

**Below is setting of TAX in Woo Commerce  dashboard:**
![dd](https://cloud.githubusercontent.com/assets/15122702/20318719/5cb3faa2-ab91-11e6-9cc7-1dc6ece08c10.png)

Here are the 2 screenshot of order receipt when same product is purchased from REST API and from Website.

 **1. When order is placed from Mobile App using REST API:**

![image](https://cloud.githubusercontent.com/assets/15122702/20318801/c78dce2a-ab91-11e6-865e-c3b92bfb56d2.png)

**2. When Order is placed from Website:**

![image](https://cloud.githubusercontent.com/assets/15122702/20318912/4862eca6-ab92-11e6-9feb-131a5cff0cb9.png)

Could you please tell me what thing i am missing while placing order from Mobile App using REST API so that App and Website will work in sync.

Thank you.

**Comment by claudiosanches** [comment]
What Mobile App?

**Comment by pkhutal** [comment]
Mobile App POST and GET Data using REST API.

**Comment by claudiosanches** [comment]
But what "Mobile App"?

**Comment by claudiosanches** [comment]
How are you creating the order?
Show me the JSON submitted in the POST request.

**Comment by pkhutal** [comment]
Its Native Mobile App that uses REST API.

Here is the oder json that i am posting 
{
  "order": {
    "customer_id": 3,
    "billing_address": {
      "first_name": "Shrimati",
      "last_name": "Fure ji",
      "address_1": "Dgfg",
      "address_2": "Dgcf",
      "city": "kjhklk",
      "state": "AP",
      "postcode": "guvvigviybiy",
      "country": "IN",
      "email": "fure@gmail.com",
      "phone": "2580"
    },
    "shipping_address": {
      "first_name": "Shrimati",
      "last_name": "Fure ji",
      "address_1": "Dgfg",
      "address_2": "Dgcf",
      "city": "kjhklk",
      "state": "AP",
      "postcode": "guvvigviybiy",
      "country": "IN"
    },
    "line_items": [
      {
        "product_id": 441,
        "quantity": 1,
        "subtotal": 500,
        "total": 500
      }
    ],
    "total_discount": 250,
    "fee_lines": [
      {
        "title": "Extra Fee",
        "total": 100
      }
    ],
    "shipping_lines": [
      {
        "method_id": "free_shipping",
        "method_title": "Free Shipping",
        "total": 0
      }
    ]
  }
}

**Comment by pkhutal** [comment]
Could anyone please help me out for this ?

**Comment by mikejolley** [comment]
@claudiosanches were you able to replicate?

**Comment by pkhutal** [comment]
Hello team,

Could you please help us resolve this issue asap as VAT calculation is sensitive in some countries and could become a legal issue. 

Thank you for considering this ticket on priority.

Regards,
Pallavi

**Comment by claudiosanches** [comment]
@mikejolley no luck do replicate it.

**Comment by mikejolley** [comment]
@claudiosanches @pkhutal I think the issue is how you're sending line totals. Orders created in admin and via the API should be sent excluding tax, regardless of the website setting. 

Make sure you send line item costs excluding tax. Thats where I think your extra tax is coming from - taxing the inclusive tax amount you sent.

Let me know if you have any questions but I don't think this is a bug.

**Comment by pkhutal** [comment]
@mikejolley @claudiosanches thank you for your effort and patience. Will check and get back to you.

**Comment by lanceomni** [comment]
I'm having the same issue.  Tax is being calculated on my shipping_lines even though the only tax rate explicitly excludes shipping.  Works fine on website orders, but adding orders through the API are calculating incorrectly.

**Comment by pkhutal** [comment]
While creating order add “is_vat_exempt”: true to order JSON. 
This will not include extra TAX after order is placed.

**Comment by praneetchandra** [comment]
Hi Team, For me tax is not getting added to the order. I am only sending total before tax. P.S. I am using it in conjunction with Woocommerce Booking

**Comment by peterfabian** [comment]
Hi @praneetchandra, 

Please contact support via https://woocommerce.com/contact-us/.
If you find an bug in the WooCommerce core, please create a new one.

Thanks.
