### ISSUE TITLE
Remove install notice and update product images options

### ISSUE THREAD

**Issue by nicolas92** [woocommerce/woocommerce#12365]
Hello,

I need a little help, it is not really in direct relation with WooCommerce but I hope you will be able to help me, I explain.
I created a theme with several demos, some of which use WooCommerce. I want to create a one click demo install with the plugin "One Click Demo Import".
To assign pages Shop, My Account, Cart, etc, I use the following code that works fine:

```
$woopages = array(
	'woocommerce_shop_page_id' 				=> 'Shop',
	'woocommerce_cart_page_id' 				=> 'Cart',
	'woocommerce_checkout_page_id' 			=> 'Checkout',
	'woocommerce_pay_page_id' 				=> 'Checkout &#8594; Pay',
	'woocommerce_thanks_page_id' 			=> 'Order Received',
	'woocommerce_myaccount_page_id' 		=> 'My Account',
	'woocommerce_edit_address_page_id' 		=> 'Edit My Address',
	'woocommerce_view_order_page_id' 		=> 'View Order',
	'woocommerce_change_password_page_id' 	=> 'Change Password',
	'woocommerce_logout_page_id' 			=> 'Logout',
	'woocommerce_lost_password_page_id' 	=> 'Lost Password'
);

foreach ( $woopages as $woo_page_name => $woo_page_title ) {

	$woopage = get_page_by_title( $woo_page_title );
	if ( isset( $woopage ) && $woopage->ID ) {
		update_option( $woo_page_name, $woopage->ID );
	}

}
```

But I would like to remove the install notice. I tried the following code but it does not work:

```
// Remove install notice
delete_option( 'woocommerce_admin_notice_install' );
```

Also, is it possible to update the Catalog Images, Single Product Image and Product Thumbnails options?
I think it's with the "update_option" function, but I have not found how to do it.

Can you help me with his two small problems?

Thank you a lot.

**Comment by Dartui** [comment]
Probably this is not place for support, you should use forum for that. Anyway you could try this:
```php
add_filter('woocommerce_show_admin_notice', 'hide_install_notice', 10, 2);

function hide_install_notice($bool, $notice) {
	if ('install' == $notice) {
		return false;
	}
	
	return $bool;
}
```

**Comment by nicolas92** [comment]
Hello, thank you very much :)

**Comment by claudiosanches** [comment]
Sorry, but here is not a support channel.

- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - **https://wordpress.org/support/plugin/woocommerce for general support**
  - **https://woocommerce.com/my-account/tickets/ for premium plugin support**
