### ISSUE TITLE
Trying to update stock on variant updates the parent instead.

### ISSUE THREAD

**Issue by ChrisOneSaas** [woocommerce/woocommerce#12377]
## EXPLANATION OF THE ISSUE

I created a variant product with two children, they all have their own unique SKUs.  I had manage stock set on both children but not the parent.  When I attempt to push a product stock update to one of the children it instead updates the stock on the parent and sets the manage stock flag to true.

## STEPS TO REPRODUCE THE ISSUE

1. Create a variant product, set manage stock on the children but not the parent product.
2. Send an update of stock through the API using a child ID. 
 _example of the json body sent:_
{"manage_stock":true,"stock_quantity":"10.000000","in_stock":true,"id":"356"}

Expected result:  Child product stock (with ID 356) is updated
Actual result:  Child product is not updated, parent is updated and manage stock flag set to true.

The return result came back with the child's stock.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://xtesting.onesaas.com/wordpress441
Site URL: http://xtesting.onesaas.com/wordpress441
WC Version: 2.6.7
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.28
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.7
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (3) ###

Jetpack by WordPress.com: by Automattic – 4.3.2
SG CachePress: by SiteGround – 2.3.11
WooCommerce: by WooThemes – 2.6.7

### Settings ###

Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.1 – 1.3 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
I answered this exact issue last week - did you search?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/12201

**Comment by ChrisOneSaas** [comment]
When searching for variant or variable or even stock in the issues section,
12201 does not appear at all, so yes I did do a search before creating the
ticket.

**Comment by mikejolley** [comment]
Make sure you're not just searching open issues. I found it :p
