### ISSUE TITLE
Updating bulk actions to use new filters

### ISSUE THREAD

**Issue by luukdv** [woocommerce/woocommerce#12379]
Right now, bulk actions are done with JS: https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-post-types.php#L1452

The mentioned issue has been resolved and registering custom bulk actions will be possible from 4.7 (https://make.wordpress.org/core/2016/10/04/custom-bulk-actions/). Just a heads-up!

**Comment by claudiosanches** [comment]
Closed in favor of #12391
Thanks for report it.
