### ISSUE TITLE
Try to check and update customer_email of Coupons in cart process

### ISSUE THREAD

**Issue by skmohammadi** [woocommerce/woocommerce#12378]
Hi. I have generated bulk coupons and give that coupons to our attendant in a conference.
Its may that any coupon can be used only by first one who entered the code?

In other words, its need to update `customer_email` meta field in first use of that coupon.

**Comment by mikejolley** [comment]
If you have unique codes set usage limit to 1? This sounds custom anyhow - not a bug.
