### ISSUE TITLE
issue with wc_product_dropdown_categories 

### ISSUE THREAD

**Issue by PrafullaKumarSahu** [woocommerce/woocommerce#12382]
wc_product_dropdown_categories() function displaying categories having out of stock products, as woo-commerce hides these products from shop and category page, it is meaning less to visit category having only one product which is out of stock or having all out of stock products .as that page will be blank. so why we are displaying that category in dropdown.

**Comment by claudiosanches** [comment]
`wc_product_dropdown_categories()` only query for categories.
It's to heavy to query for all categories plus products and plus product meta to check if all products are available. Will generate a big performance issue, that's why don't makes sense try it.

**Comment by PrafullaKumarSahu** [comment]
You are saying something like this

```
$terms = get_terms( 'product_cat', apply_filters( 'wc_product_dropdown_categories_get_terms_args', $args ) );

	if ( empty( $terms ) ) {
		return;
	}
	  $terms = apply_filters( 'wc_exclude_category_having_only_out_of_stock_products', $terms );
```

and using  wc_exclude_category_having_only_out_of_stock_products 

```
add_filter( 'wc_exclude_category_having_only_out_of_stock_products', 'exclude_empty_product_categories' );
function exclude_empty_product_categories( $terms ){
    $non_empty_categories = array();
    foreach ( $terms as $term ){
        $products = get_products_from_category_by_ID( $term );
        if ( ! $products->have_post() ){
            $non_empty_categories[] = $term;
        }
    }

    return $non_empty_categories;
}



function get_products_from_category_by_ID( $category ) {

    $products_IDs = new WP_Query( array(
        'post_type' => 'product',
        'post_status' => 'publish',
        'fields' => 'ids',
        'tax_query' => array(
            array(
                'taxonomy' => 'product_cat',
                'field' => 'term_id',
                'terms' => array( $category->term_id ),
                'operator' => 'IN',
            )
        )
    ) );
    var_dump( $products_IDs );
    wp_reset_postdata();
    return $products_IDs;
}
```

Yes there will an extra loop executing  WP_Query for each query . but can we make it by using join I mean instead of using get_terms, we can make a custom query there . Do you think that makes sense ?

I even tried the above but there seems to be some issue with this code get_products_from_category_by_ID() returning WP_Query objects and not ids of products, I was expecting arrays of product ids .

**Comment by claudiosanches** [comment]
Yes, really bad doing a lot of queries in all pages only to remove a few items from the category dropdown.

If you really thinks that is necessary create this excess of queries you can extend the `WC_Widget_Product_Categories` and create you own widget.

**Comment by PrafullaKumarSahu** [comment]
@claudiosanches thank you so much for your reply, just looking into the class you have referred.

**Comment by PrafullaKumarSahu** [comment]
@claudiosanches My code is not running on every page I am using that dropdown to create a custom  search widget for my site and there only it is executing as I have said I have defined my own dropdown by copying wc_product_dropdown_category() . I am on WC_Widget_Product_Categories class and I think here to I need to check for every category, just one thing I can do is for top level if I will remove the unneeded categories the number of categories for their $direct_children will be less and so on, but in that case I will miss categories which  are  having out of stock products but having sub-categories which are having products with stock, so It seems in this custom widget I am making extending the class too, I need to traversed through each category, sadly as you have said it is an inefficient work, but would like to know if I can do it in best possible way, may be using code or creating complex JOIN queries .

**Comment by claudiosanches** [comment]
@PrafullaKumarSahu I'm looking forward for you create a plugin for this new widget and put on wp.org.

**Comment by PrafullaKumarSahu** [comment]
never thought about creating plugin and putting it to wp.org, I can not provide support and a lot of things to be done like updates etc, my employer will not allow me to spend time on those things, better to focus on finishing tasks every day, yes, I can upload a plugin on github for sure . And will invite you to check it may be your input can make it usable to every woocommerce user.
