### ISSUE TITLE
Feature Request: Add media/file upload field to WC_Settings_API

### ISSUE THREAD

**Issue by davetgreen** [woocommerce/woocommerce#12384]
It would be nice to have the ability to natively upload media/files when creating settings. I see that the `WC_Settings_API` class has support for all the standard form inputs, but nothing for uploads.

In my specific case, I'm writing a payment gateway for a client, and need to introduce a means of them having a custom logo next to the payment method at the checkout. I'm currently implementing this via the Customizer, but it makes sense to have this on the settings page itself rather than the user having to leave the settings page.

I feel this would be useful for plugin authors. :)

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/11831
