### ISSUE TITLE
Bug with select in product variations in Mozilla Firefox

### ISSUE THREAD

**Issue by kisonic** [woocommerce/woocommerce#12383]
Open this page on Mozilla Firefox (I used version 50.0):
http://demo.woothemes.com/storefront/product/small-mp3-player-pro/

And try to change option "Storage Size". Every time when you will click on select it will reset to "Choose an option".

That how it works in Firefox:
![firefox](https://cloud.githubusercontent.com/assets/7009699/20391451/79ee123e-ace4-11e6-9fae-e4de486f0936.gif)

That how it must work:
![safari](https://cloud.githubusercontent.com/assets/7009699/20391476/9b6c9f8e-ace4-11e6-8dda-f48ff355666c.gif)

**Comment by claudiosanches** [comment]
Closed in favor of #12387
Thanks for report it.
