### ISSUE TITLE
get_title() difference from 2.6.8 to master

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce#12398]
## EXPLANATION OF THE ISSUE

Running `get_title()` against a variation product (`WC_Product_Variation`) on v2.6.8 gives the product title as per the parent product. On master, it gives the string "Variation #%d of %s" where %d is the variation ID, and %s is the parent prouct title. 
 
## STEPS TO REPRODUCE THE ISSUE

Run the following script with wp-cli on v2.6.8, then on master:

```php
<?php

$variation_id = 257; // Add your own variation ID here.
$factory = new WC_Product_Factory();
$variation_product = $factory->get_product( $variation_id );
var_dump($variation_product->get_title());
```

**2.6.8**
```
$ wp eval-file /tmp/get_title.php
string(25) "Differently sized product"
```

**Master**
```
$ wp eval-file /tmp/get_title.php
string(43) "Variation #257 of Differently sized product"
```

**Comment by claudiosanches** [comment]
Closed in favor of #12427. Thanks.
