### ISSUE TITLE
"Layered Nav Filters" widget based on OR query can lead to 404

### ISSUE THREAD

**Issue by opportus** [woocommerce/woocommerce#12394]
## STEPS TO REPRODUCE THE ISSUE

1. Select 2 or more attributes of the same tax in layered nav widget (eg: color) to make products fill at least 2 pages.
2. Go to the last archive page, eg: http://example.com/product-category/category/page/2/?filter_color=black%2Cred%2Cwhite
3. Remove in **Layered Nav Filters** widget an attribute so products should fill only 1 page.
4. You're on 404.

## EXPLANATION OF THE ISSUE

In these circunstances, the `page/2/` part of the "Layered Nav Filters" widget items links should be removed...

**Comment by opportus** [comment]
@mikejolley, thank you !

**Comment by opportus** [comment]
@mikejolley, will there be another minor release including last bug fixes as this one before 2.7 release ?

**Comment by mikejolley** [comment]
Yeah
