### ISSUE TITLE
Change WooCommerce string

### ISSUE THREAD

**Issue by Datibus** [woocommerce/woocommerce#12399]
Hi guys,

I'm trying to change the "Addresses" string which appears in the menu of My Account page. I have been searching for it for a long time but I didn't success, its a little bit frustrating, please, can anyone tell me how to modify it?

Thanks in advance!

Raquel

**Comment by claudiosanches** [comment]
You can use this plugin to change strings: https://wordpress.org/plugins/say-what/

**Comment by Datibus** [comment]
Thank you Claudio!

I have seen some plugins to do it, but I am avoiding this solution (installing another plugin) because the site have too much plugins and I think adding another one is not a good idea, I would like to override this text in my child theme, is it possible?

**Comment by claudiosanches** [comment]
In this case you can use the `woocommerce_account_menu_items` filter to change the menu label.

**Comment by Datibus** [comment]
Thanks Claudio, that was exactly what I need. I write here the code, I think it could help someone:

function my_custom_my_account_menu_items( $items ) {
	$items['edit-address']="Registration details";
    return $items;
}
add_filter( 'woocommerce_account_menu_items', 'my_custom_my_account_menu_items' );
