### ISSUE TITLE
Making checkout billing address field non-required issue

### ISSUE THREAD

**Issue by mechanicalpie** [woocommerce/woocommerce#12409]
## EXPLANATION OF THE ISSUE
I have used a custom hook into 'woocommerce_billing_fields' to make billing address a non-required field on WooCommerce checkout form.
However, input field's `<p>` wrapper on the front-end still has the following CSS classes after hook was added to theme's functions.php:
validate-required
woocommerce-invalid
woocommerce-invalid-required-field
If I make other billing fields (e.g. country and zip code) non-required by writing a similar hook in functions.php,  those CSS classes are removed from the `<p>` wrapper of input element on the front-end. On the back-end, billing address field is not validated after I have added my hook.
 Also, as expected, after I have added my hook,  WC shows no error if this field is empty.

## STEPS TO REPRODUCE THE ISSUE

1. Insert the following hook into functions.php file of your active theme
```
add_filter( 'woocommerce_billing_fields', 'wc_optional_billing_fields', 10, 1 );
function wc_optional_billing_fields( $address_fields ) {
    $address_fields['billing_address_1']['required'] = false;
    $address_fields['billing_address_2']['required'] = false;
    return $address_fields;
}

```
2. Add any product to cart
3. Proceed to checkout
4. Billing address1 field will still have the following CSS classes:
validate-required
woocommerce-invalid
woocommerce-invalid-required-field
and `<abbr class="required>` element next to input label element.
At the same time, the billing address1 field validation on backend is not performed and it can be empty, WooCommerce will not add an error. It means that the hook works as expected on the backend. 

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://karparauto.test-depot.info
Site URL: http://karparauto.test-depot.info
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 5 GB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.14 - Мы рекомендуем как минимум PHP версии 5.6. Смотрите: Как обновить версию PHP
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 2000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.44 - Мы рекомендуем MySQL версии не меньше 5.6. Читайте: Требования WordPress
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Удалить запись: ✔
Удалённое получение: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (27) ###

Advanced Custom Fields: Rus-To-Lat: от Andrey Pavluk  – 1.0.0
Adminer: от Frank Bültge – 1.4.5
Advanced Custom Fields: от Elliot Condon – 4.4.11
Cyr to Lat enhanced: от Sol
Sergey Biryukov
Nikolay Karev
Dmitri Gogelia – 3.5

Ultimate WooCommerce Expandable Categories: от MagniumThemes – 1.1
Link Master: от Brett Rutecky – 1.5
Place Login: от Catherine Lebastard – 1.1.2
Мета слайдер: от Matcha Labs – 3.3.7
Orbisius Child Theme Creator: от Svetoslav Marinov (Slavi) – 1.3.4
Regenerate Thumbnails: от Alex Mills (Viper007Bond) – 2.2.6
Page Builder от SiteOrigin: от SiteOrigin – 2.4.18
SiteOrigin CSS: от SiteOrigin – 1.1.2
SiteOrigin Бандл Виджетов: от SiteOrigin – 1.7.2
Taxonomy Switcher: от WebDevStudios – 1.0.2
WooCommerce Accordions: от Magnigenie – 1.0
WooCommerce Bulk Edit Product Variations: от matterico_themes – 2.6
Advanced Flat Rate Shipping Method WooCommerce: от Multidots – 2.1
WooCommerce Remove All Products: от Gabriel Reguly – 1.0.4
WooCommerce: от WooThemes – 2.6.8
WOOF - WooCommerce Products Filter: от realmag777 – 2.1.3.4
Yoast SEO: от Команда Yoast – 3.8
WP All Import Pro: от Soflyy – 4.3.2
WP All Import - User Import Add-On: от Soflyy – 1.0.7
WP All Import - WooCommerce Add-On Pro: от Soflyy – 2.3.1
WPB Accordion Menu or Category: от wpbean – 1.04
YITH WooCommerce Bulk Product Editing: от YITHEMES – 1.0.11
WP All Import - Yoast WordPress SEO Add-On: от Soflyy – 1.1.4

### Settings ###

Force SSL: –
Currency: RUB (₽)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Ссылка магазина: #4 - /shop/
Корзина: #5 - /cart/
Оформление заказа: #6 - /checkout/
Мой аккаунт: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Karpar_auto (Vantage-based)
Version: 1.5.6
Author URL: 
Child Theme: ✔
Parent Theme Name: Vantage
Parent Theme Version: 1.5.6 – 1.5.7 доступно
Parent Theme Author URL: https://siteorigin.com/
WooCommerce Support: ✔

### Templates ###

Overrides: vantage/woocommerce/archive-product.php
vantage/woocommerce/auth/form-login.php
vantage/woocommerce/content-product.php
vantage/woocommerce/global/form-login.php
vantage/woocommerce/loop/add-to-cart.php
vantage/woocommerce/single-product/related.php

`
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
For now, I have written a temporary JS solution
```
<script type="text/javascript">
jQuery( document ).ajaxComplete(function() {
	jQuery("#billing_address_1_field").removeClass('woocommerce-invalid-required-field');
	jQuery("#billing_address_1_field").removeClass('woocommerce-invalid');
	jQuery("#billing_address_1_field").removeClass('validate-required');
	jQuery("#billing_address_1_field > label > abbr").remove();
	});
</script>
```

**Comment by mikejolley** [comment]
Filter woocommerce_default_address_fields - the default or country locale will always override any direct changes to billing/shipping depending on country selection. I'm adding a note inline to the docs.

**Comment by tony2nite** [comment]
So the only way to override is to set the one default which seems to be share for both billing and shipping. If I'm reading this right then it currently not possible to have different values between the two groups of addresses, right? Specific use case, I want the billing postcode as 'required' and the shipping postcode as not 'required', also wanting labels different between the two sets.

**Comment by neonkowy** [comment]
Hey @mikejolley ,

Thanks for checking this out. Unfortunately I'm still experiencing this issue when I'm using woocommerce_billing_fields filter. HTML is produced correctly, but then JS (address-i18n.js) is messing all those fields up.

Is @tony2nite right, and the only solution is to ovverride locale defaults, no matter what you do in filters? Looks to me like something really wrong in design.

**Comment by isaaclubow** [comment]
It seems like `address-i18n.js` is rewriting all my required fields to "Optional" (on the checkout page). I'm using the `woocommerce_checkout_fields` filter to set each billing field to "required" and I can confirm they are appearing that way in the page source, but `address-i18n.js` is rewriting them despite the fact that, independent of locale, our gateway requires the fields we're showing.

What's the preferred way of preventing this? @tony2nite I'm intrigued - how do you override a locale default?

**Comment by orangutangle** [comment]
In my tests, the woocommerce_default_address_fields filter had no permanent effect on the required status of address fields. However, setting the locale defaults does work. For example, to make UK county (billing_state/shipping_state) required, use:
```
add_filter( 'woocommerce_get_country_locale', 'mp_change_locale_field_defaults');

function mp_change_locale_field_defaults($countries) {
	$countries['GB']['state']['required'] = true;
	return $countries;
}
```
