### ISSUE TITLE
Product variations store doesn't set attributes correctly.

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#12401]
Logging this here so we don't forget to fix.

`set_attributes` for product variations seems to just be setting a simple key => value pair:
`$product->set_attributes( wc_get_product_variation_attributes( $product->get_id() ) );`

WC_Cart's `get_item_data` expects something different so we end up getting a display like so:

<img width="413" alt="screen shot 2016-11-18 at 4 09 44 am" src="https://cloud.githubusercontent.com/assets/689165/20429651/dd13310e-ad44-11e6-83bf-36ab856a8f61.png">

and it should match:

<img width="456" alt="screen shot 2016-11-18 at 4 11 24 am" src="https://cloud.githubusercontent.com/assets/689165/20429688/164790dc-ad45-11e6-8b18-c18adfe43a0f.png">

Normal products are returning an array of `WC_Product_Attribute`s. I assume variations needs to match that?

**Comment by mikejolley** [comment]
Looks like this is actually caused by #12416
