### ISSUE TITLE
Is there a field like ‘order_status_changed_by’ in the ‘shop_order’ ?

### ISSUE THREAD

**Issue by 70599** [woocommerce/woocommerce#12400]
My store has more than one shop mangers.
I would like to know who changed order status.

Is there a field like ‘order_status_changed_by’ with the value ‘user_id’ in the ‘shop_order’ ?

Or please consider add this key to the woocommerce core source code ?

**Comment by claudiosanches** [comment]
Don't have any.
There is a few plugins that already can save logs about user activities.
But not hard for you include it in your installation, since you can save this info using the `save_post` action.

**Comment by 70599** [comment]
Thanks for reply.

Resolved by the code below:
```php
add_action('save_post','order_status_updated_by');
function order_status_updated_by($post_id) {
	$post_type = get_post_type($post_id);
	if ($post_type != 'shop_order') return;
	update_post_meta($post_id,'_order_status_changed_by',get_current_user_id());
}
```
