### ISSUE TITLE
customer.updated webhook doesn't return the updated_at timestamp

### ISSUE THREAD

**Issue by udayapitchika** [woocommerce/woocommerce#12406]
## EXPLANATION OF THE ISSUE
`customer.updated` webhook doesn't return the `updated_at` timestamp in the payload. It returns only the `created_at` and there is no way to know when exactly the customer was updated through the webhook. We would have to make an api call again to the customers endpoint `/wp-json/wc/v1/customers/<id>` to retrieve the updated_at timestamp which is inefficient.

Whereas the  `order.updated` webhook returns the `updated_at` timestamp in the payload. It would be great to see the same working in the customers.updated webhook too. 

Below is an example customer.updated webhook with only created_at timestamp -
`{"customer":{"id":40,"created_at":"2016-10-24T12:08:08Z","email":"example@test.com","first_name":"Test","last_name":"Test","username":"card1595","role":"customer","last_order_id":"2319","last_order_date":"2016-10-25T07:11:50Z","orders_count":1,"total_spent":"0.00","avatar_url":"http:\/\/0.gravatar.com\/avatar\/ad516503a11cd5ca435acc9bb6523536?s=96","billing_address":{"first_name":"updated","last_name":"","company":"","address_1":"","address_2":"","city":"Test","state":"Ohio","postcode":"11111","country":"","email":"","phone":""},"shipping_address":{"first_name":"updated","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":""}}}`

### WordPress Environment ###
WC Version: 2.3.7
WC Database Version: 2.3.7
WP Version: 4.1.13

**Comment by mikejolley** [comment]
2.3.7?

**Comment by claudiosanches** [comment]
2.3.7 don't have `/wp-json/wc/v1/customers/<id>` or our legacy API v3, so don't have anything to save any `updated_at` fields.
You need update your installation.
