### ISSUE TITLE
Shipping Method API (2.6) - can't make global/instance only settings

### ISSUE THREAD

**Issue by jezmck** [woocommerce/woocommerce#12405]
## EXPLANATION OF THE ISSUE

It's not possible to have
- a global setting (e.g. the title) which applies to all instances and can't be overridden individually.
- an instance setting (e.g. available dates) which can only be set per instance.

**Comment by jezmck** [comment]
I hoped to be able to conditionally add to `$this->instance_form_fields` dependant on the `instance_id`, but this appears to be set to a number even when editing the global settings.

**Comment by mikejolley** [comment]
What do you mean? If you don't define a field in instance_form_fields, it won't show. Global options are defined separately.

**Comment by jezmck** [comment]
Where are the global options defined?

https://github.com/woocommerce/woocommerce/wiki/Shipping-Method-API-(2.6) doesn't say and I can't see an example which does.

**Comment by mikejolley** [comment]
Old way - get_form_fields https://github.com/woocommerce/woocommerce/blob/657c312caeef7345b225ffb899da6dbb84692936/includes/abstracts/abstract-wc-settings-api.php#L55

**Comment by jezmck** [comment]
So I _do_ define them in `->form_fields`?

**Comment by jezmck** [comment]
> Instances inherit the global settings, but can then have their own settings which take priority.

I read this to mean that the settings would be repeated in the instance's settings, but I guess that's not the case.

**Comment by mikejolley** [comment]
They inherit the *values* but not the fields.

**Comment by jezmck** [comment]
Okay, thanks. I'll try again when I'm back in the office on Monday.

**Comment by mikejolley** [comment]
If you have access to our USPS extension, I *think* it makes use of a global setting for API.

**Comment by mikejolley** [comment]
Closing issue however as this isn't a bug, possible just an issue with my documentation :)

**Comment by jezmck** [comment]
I've discovered that my confusion was all down to a bug with a 3rd party plugin, WooCommerce Hide Checkout Shipping Address, and I'll let them know. It replaces the global settings with the instance settings.
