### ISSUE TITLE
Show in stock products first and out of stock products last

### ISSUE THREAD

**Issue by MMaKenZi** [woocommerce/woocommerce#12414]
## EXPLANATION OF THE ISSUE
I think the most important thing for a shop is the availability of products
you may think that out of stock products are not important too
but actually they are
because some users for example know an outdated model of a product and they search it in google, so if the product will be visible, your site will be in google results, and the user open website and see that the product is out of stock for any reason and he can choose another product

this was just one of cases that out of stock products are needed to be visible

another example, it happened sometimes that whole products of a category are out of stock, by the only option provided by woocommerce, they all will be hidden, so if a user try to browse site by categories menu, he will just see "no products found!" and say what a stupid shop is this that created some empty categories!

but if the user be able to see the out of stock products, can contact admin for some other products and don't think about the stupidity of the shop anymore :D 

so I think the best option is this:
first in stock products be visible and after them out of stock products 
I searched alot for any instances to do this, but none of them worked correctly
so pls consider to do this in version 2.7

## STEPS TO REPRODUCE THE ISSUE

Just try to visit a woocommerce shop that is working for a long time
you may see lots of out of stock products  are in index!
or you may see lots of empty categories :)
there isn't any other option between this twos

**Comment by MMaKenZi** [comment]
I hope see this in 2.7 after all the complicated things that are already done

**Comment by MMaKenZi** [comment]
and it's growing so fast!
<img src="http://lioncomputer.ir/uppic/images/497w1c7rnpd949wismlo.jpg" alt="example of google">

**Comment by mikejolley** [comment]
@MMaKenZi they are hidden from the catalog, not from the single product pages!

**Comment by MMaKenZi** [comment]
@mikejolley that's true, but just for products, not for other urls
like this :
product-category/category-name/page/2/ and similar ones
will get error 404 
and that's because previously the products was visible so the pagination has been created and indexed in google and after being out of stock and hidden the url will be equal to error 404 in google crawl status

thank you anyway

**Comment by mikejolley** [comment]
Is there any benefit to having those indexed I wonder? The product pages are the important ones, not the archives.

**Comment by MMaKenZi** [comment]
the urls that are important for indexing as you said are visible by direct url and we have no problem in this section
but for 404 error, google will not show the urls I mentioned in it's result
but will consider them as 404 not found error
the importance of what I said became lower in comparison when I thought even direct link to products will not work anymore while it's out of stock
but still it's important

thank you

**Comment by mikejolley** [comment]
Part of #13072

**Comment by dilipsam123** [comment]
> Is there any benefit to having those indexed I wonder? The product pages are the important ones, not the archives.

> 

There are instances where the product page is not necessary, especially in external affiliate sites
