### ISSUE TITLE
Add new checkout hook for after payment has been processed.

### ISSUE THREAD

**Issue by seb86** [woocommerce/woocommerce#12410]
## EXPLANATION OF REQUEST

I am working on a custom subscription method for a client where the customer adds the subscription product of £40 and then the customer can add items up to that value before checking out.

This means that I have to set the prices of the items to ZERO in order for the total of the cart to remain just £40 which I have done.

The client also wants to show the original price of the items added as part of the subscription which I have also done. However, when the order is placed, the order of all items except for the subscription product are set as £0 which is correct but I need to show the original item prices in the order once payment has been processed and in order to do that I need a new action hook so that I can filter the order before it redirects to the thank you page.

This is the action hook I had in mind to be added after [line 664](https://github.com/woocommerce/woocommerce/blob/2.6.8/includes/class-wc-checkout.php#L664).

`do_action( 'woocommerce_checkout_order_processed_after_payment', $order_id, $this->posted );`

or

`do_action( 'woocommerce_checkout_order_payment_processed', $order_id, $this->posted );`

This action hook needs to be placed there so that the order status is not changed before I have altered the order. Otherwise, the customer email will be sent first with the items showing as £0.

Is this possible to be added there? What do you think?

Please discuss with me your thoughts before closing this.

Thank you.

**Comment by mikejolley** [comment]
This isn't going to help your situation. Order status changes occur inside the process_payment() methods. An action hook after this is called would be too late.

You need to use the order status change hooks like the emails do, e.g. from new order email:

```
add_action( 'woocommerce_order_status_pending_to_processing_notification', array( $this, 'trigger' ) );
		add_action( 'woocommerce_order_status_pending_to_completed_notification', array( $this, 'trigger' ) );
		add_action( 'woocommerce_order_status_pending_to_on-hold_notification', array( $this, 'trigger' ) );
		add_action( 'woocommerce_order_status_failed_to_processing_notification', array( $this, 'trigger' ) );
		add_action( 'woocommerce_order_status_failed_to_completed_notification', array( $this, 'trigger' ) );
		add_action( 'woocommerce_order_status_failed_to_on-hold_notification', array( $this, 'trigger' ) );
```

Just ensure your code has an earlier priority than 10 when hooking in so you can make the change and save before they get sent. This is the best you can get because we don't control a gateways process_payment method.
