### ISSUE TITLE
Add a non supported field using the WC_Settings_API class

### ISSUE THREAD

**Issue by digitalchild** [woocommerce/woocommerce#12415]
I would like to be able to hook into the WC_Settings_API class and inject a field type that is currently not provided by the class.

In the generate_settings_html function it would be useful if there was an action provided after the creation of every field so that you can inject your own field or other code into the form.

**Comment by mikejolley** [comment]
Whats wrong with adding the field to your subclass with a new method? `generate_X_field`

**Comment by digitalchild** [comment]
Because I did not know this could be done. I shall take this approach, thanks!
