### ISSUE TITLE
Using Custom Post Type as Product in Woocommerce

### ISSUE THREAD

**Issue by AikawaKai** [woocommerce/woocommerce#12422]
## EXPLANATION OF THE ISSUE

By now it's not possible to import\use an already created custom post type as product in woocommerce

## WHY IT'S NEEDED 

There are a lot of users of woocommerce which found difficult to create\add a custom post type as product on woocommerce. But by now there isn't a clear solution to this problem, except for a not free plugin

## SYSTEM STATUS REPORT

--

**Comment by mikejolley** [comment]
Products **_are_** a custom post type... You'd need to switch it's type and format the data in our format. Core won't handle this - an importer will.

**Comment by AikawaKai** [comment]
It is possibile to do this maintaining the same layout used  in my the custom post type?

**Comment by mikejolley** [comment]
With customisation, since in theory it should use the same template hierarchy as our post type. But you'll need to do some work to make it read data in our format and use our functions.
