### ISSUE TITLE
Reports: Incorrect Net Value after refund

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce#12425]
## EXPLANATION OF THE ISSUE

When I do a refund, the "net sales in this period" reports an incorrect number, IF my Order had a shipping charge. 

Example: I make a purchase of $105, $5 of that is shipping.  I do a full refund of $105 for that order.  Reports will now show a Net Sales of -$5.  

## STEPS TO REPRODUCE THE ISSUE

1. Make a purchase on a test site and make sure to have some kind of shipping charge
2. Refund that order (all of it)
3. Take a look at the reports for just that day
4. You'll see that the "Net Sales in this period" shows a negative number.

This bug was introduced in 2.5.1 - before that the net sales would correctly show at $0.

**Comment by jnarciso** [comment]
I should mention this happened with my instance using **WooCommerce UPS Shipping** module. Not sure if that is a factor.

**Comment by mikejolley** [comment]
See #12453
