### ISSUE TITLE
I have woo commerce linked to lightspeed. When I sync the SKU I have entered in inventory disappears

### ISSUE THREAD

**Issue by cliver23** [woocommerce/woocommerce#12426]
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
This https://woocommerce.com/products/woocommerce-lightspeed-pos/ ?

Please login to your WooThemes/WooCommerce account and log a support ticket - someone can assist you there.
