### ISSUE TITLE
Woocommerce_product_title does not apply to the_title function

### ISSUE THREAD

**Issue by Dartui** [woocommerce/woocommerce#12420]
## EXPLANATION OF THE ISSUE
For now (2.6.8) `woocommerce_product_title` does not apply to `the_title()` function, but only for `$product->get_title()` method. This causes problems, because on template pages, for example on `/templates/single-product/title.php`, product title is not filtered.

I could filter title using `the_title` filter, but it will not affect `$product->get_title()` method, because it uses raw `$product->post->post_title`

To solve this I have to create one filter to two hooks and every time check if given object ID is ID of product:
```php
add_filter('woocommerce_product_title', 'product_title', 10, 2);
add_filter('the_title', 'product_title', 10, 2);

function product_title($title, $the_product) {
	$product = wc_get_product($the_product);
	if (!$product) {
		return $title;
	}
	
	// safe for making changes
	
	return $title;
}
```

**Comment by mikejolley** [comment]
`the_title` is a tempalte function. `the_title` is used in title.php template file, but it would be wrong to apply it everywhere else e.g. just getting product data from the class.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/title.php

**Comment by Dartui** [comment]
Thanks for reply. 
Maybe first I should give some example to show where is the problem for me. I wanted to add suffix to product name which will be show in every place, but I don't want to put it in product title on edit page, because it is the same on each product. For now I have to create two hooks to one function to do this like in example above.

**Comment by mikejolley** [comment]
Correct you will have to - but that does not justify using a template function/filter in all places. 2.7 CRUD has a standard filter for getting this data at a higher level you will be able to use instead.
