### ISSUE TITLE
Lost password form not submit data

### ISSUE THREAD

**Issue by denisus** [woocommerce/woocommerce#12433]
## EXPLANATION OF THE ISSUE

woocommerce
lost password form just freez and do not submit data

## STEPS TO REPRODUCE THE ISSUE

http://screencast.com/t/rDkzZr3CA
This happen if form tag first child of .woocommerce div
and cart.js script do not allow submit form.

this can be resolwed, if wrap form with div tag

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://pistilflowers.com/
Site URL: http://pistilflowers.com/
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Unix) OpenSSL/1.0.2g
PHP Version: 5.6.28
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.16
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (29) ###

LayerSlider WP: by Kreatura Media – 5.6.9
Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.7
Admin Menu Editor: by Janis Elsts – 1.7.2
Admin Columns: by AdminColumns.com – 2.5.6.3
Delivery Cut-off dates manager: by Convergine.com – 3.0
DHVC Form: by Sitesao – 1.4.13
Easy Heads Up Bar: by Greenweb – 2.1.7
Easy Tables (vc): by WPBakery – 1.0.10
Intense: by Intense Visions – 2.8.0
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.2.6
Mobile Redirect: by Ozette Plugins – 1.7
Page Builder by SiteOrigin: by SiteOrigin – 2.4.18
SiteOrigin Widgets Bundle: by SiteOrigin – 1.7.2
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.4.8
TinyMCE Advanced: by Andrew Ozz – 4.4.1
Toolset Types: by OnTheGoSystems – 2.2.3
Uji Countdown: by Wpmanage.com – 2.0.7
Wonder Loops: by Ultimatum Theme – 2.1.3
WooCommerce Moneris Gateway: by WooThemes / SkyVerge – 2.6.0 – 2.6.2 is available
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce Stripe Gateway: by Automattic – 3.0.6
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.38
WooCommerce Table Rate Shipping: by WooThemes – 3.0.1 – 3.0.2 is available
WooCommerce: by WooThemes – 2.6.8
YITH WooCommerce Multi-step Checkout: by YITHEMES – 1.3.6
YITH WooCommerce Quick View: by YITHEMES – 1.1.2
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

### Theme ###

Name: Pistil Flowers
Version: 0.1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Ultimatum
Parent Theme Version: 2.9.0.1
Parent Theme Author URL: https://ultimatumtheme.com
WooCommerce Support: ✔

### Templates ###

Overrides: pistil-flowers/woocommerce/archive-product.php
pistil-flowers/woocommerce/cart/cart.php
pistil-flowers/woocommerce/cart/mini-cart.php
pistil-flowers/woocommerce/cart/proceed-to-checkout-button.php
pistil-flowers/woocommerce/cart/shipping-calculator.php
pistil-flowers/woocommerce/checkout/form-checkout.php
pistil-flowers/woocommerce/content-product.php
pistil-flowers/woocommerce/content-single-product.php
pistil-flowers/woocommerce/emails/customer-invoice.php
pistil-flowers/woocommerce/emails/customer-processing-order.php
pistil-flowers/woocommerce/emails/email-footer.php
pistil-flowers/woocommerce/emails/email-header.php
pistil-flowers/woocommerce/emails/email-styles.php
pistil-flowers/woocommerce/global/quantity-input.php
pistil-flowers/woocommerce/loop/loop-end.php
pistil-flowers/woocommerce/loop/loop-start.php
pistil-flowers/woocommerce/myaccount/form-login.php
pistil-flowers/woocommerce/myaccount/form-lost-password.php
pistil-flowers/woocommerce/single-product/add-to-cart/simple.php
pistil-flowers/woocommerce/single-product/add-to-cart/variable.php
pistil-flowers/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
pistil-flowers/woocommerce/single-product/meta.php
pistil-flowers/woocommerce/single-product/price.php
pistil-flowers/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 2.6.3
pistil-flowers/woocommerce/single-product/product-thumbnails.php
pistil-flowers/woocommerce/single-product.php

: Learn how to update outdated templates

### Moneris ###

Environment: Sandbox
Tokenization Enabled: –
`

**Comment by mikejolley** [comment]
Fix here https://github.com/woocommerce/woocommerce/commit/3ef9cb4352dbc300fe275210272589ede9553796

**Comment by denisus** [comment]
Thanks
