### ISSUE TITLE
Webhooks - add an option to choose data format/api version

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#12437]
Allow Webhooks to use legacy API or new API. Default to new.

**Comment by claudiosanches** [comment]
Solved in #12448

**Comment by LeCoupa** [comment]
How wan we ask our webhooks to use the new API data format?

My webhooks seem to use the legacy API. They answer for instance with "date_created" and "date_modified" instead of "created_at" and "updated_at".

**Comment by claudiosanches** [comment]
@LeCoupa will have an option for it on WooCommerce 2.7
