### ISSUE TITLE
[Functionality Proposal] Product's image switch depending on layered nav chosen attributes

### ISSUE THREAD

**Issue by opportus** [woocommerce/woocommerce#12443]
On single product page, when we select attributes that match a variation, the **main product**'s image changes for the **variation** image.

Now, wouldn't make it sense if we follow the same logic in product categories when, in layered nav widgets, we select attributes that match a variation ?

**By default**, this would for example avoid visitors to think the site is bugged when they select for example **Red** products and the products on images stay **Black**... This really leads them to confusion 100% of the time from my experiences.

I have not found plugins doing that... Does anybody know one ?

Shouldn't this be a core functionality anyway ?

This is the code I have to come up with on my sites. Just adds some lines to the default template function `woocommerce_get_product_thumbnail()`.

```php
function woocommerce_get_product_thumbnail( $size = 'shop_catalog', $deprecated1 = 0, $deprecated2 = 0 ) {
        global $product;

        $chosen_attributes = WC_Query::get_layered_nav_chosen_attributes();
        $product_id        = $product->id;
        $image_size        = apply_filters( 'single_product_archive_thumbnail_size', $size );

        if ( $chosen_attributes && $product->is_type( 'variable' ) ) {
                $variations               = $product->get_available_variations();
                $corresponding_variations = array();

                foreach ( $variations as $variation ) {
                        $variation_id             = $variation['variation_id'];
                        $variation_attributes     = wc_get_product_variation_attributes( $variation_id );
                        $corresponding_attributes = array();

                        foreach ( $chosen_attributes as $chosen_attributes_taxonomy => $chosen_attributes_data ) {
                                $corresponding_attributes += array_intersect( $variation_attributes, $chosen_attributes_data['terms'] );
                        }

                        if ( $corresponding_attributes ) {
                                $corresponding_variations[ count( $corresponding_attributes ) ] = $variation_id;
                        }
                }

                if ( $corresponding_variations ) {
                        ksort( $corresponding_variations, SORT_NUMERIC );

                        $corresponding_variations = array_reverse( $corresponding_variations );

                        if ( has_post_thumbnail( $corresponding_variations[0] ) ) {
                                $product_id = $corresponding_variations[0];
                        }
                }
        }

        if ( has_post_thumbnail( $product_id ) ) {
                $props = wc_get_product_attachment_props( get_post_thumbnail_id(), $product_id );
                echo get_the_post_thumbnail( $product_id, $image_size, array(
                        'title'  => $props['title'],
                        'alt'    => $props['alt'],
                ) );
        } elseif ( wc_placeholder_img_src() ) {
                echo wc_placeholder_img( $image_size );
        }
}
```

Although, this "basic" approach leads to a particular behavior.

Take for example a product which has a variation defined by 2 attribute taxonomies, eg, **Color** and **Size** which have respectively the **Red** and **XL** terms.
To put things in context, for this variation, the admin has set an image representating the product in its **Red** color. In the product category, this product is shown with its main image which represents a **Black** product.

Here's the functionality's behavior for the 3 possible actions of the visitor.

1. The visitor selects in layered nav the **Red** term. The **variation image** (the **Red** product image) show up, no problem.
But note that the **Red** term is not fully representative of the variation which is also definied by another term, **XL**.

2. The visitor selects both the **Red** and **XL** terms, the product will still show up its **variation image**.

3. The visitor selects **only** **XL** term. By default, the image which representing the variation with the highest number of corresponding terms will show up...

That's just one approach, which is the most simple and straightforward. Thought I personally don't see better behavior keeping this approach.

**Comment by mikejolley** [comment]
Whilst I appreciate it would be a neat feature, with our current data structures this just isn't workable.

To work you'd need to:

- Loop over all layered nav props
- For all products in view, get all variations
- Over each set of variations, get all attributes and match attributes against nav
- Then get the image if it even exists.

You can imagine, this would be a performance nightmare for catalog pages... Just looking at the code you posted you should be able to see what I mean. How much load does that add to your pages?

Please log this on ideas.woocommerce.com - we can revisit if it gains traction. If we ever did do this, I imagine we'd have to overhaul how variations and attributes work, or find a way to map images to attributes directly, so it's not a short term thing and we have more pressing things to add first :)

**Comment by opportus** [comment]
Thanks for your feedback @mikejolley :)

Yep, that's a problem that crossed my mind when I was implementing this temporary solution.

> How much load does that add to your pages?

In my specific cases (on little stores), that's fine enough for example when choosing 1 color attribute:

- 12 products per page (4 pages)
- Average 6 variations per product defined by 2 attributes
- PHP7
- Disabled browser and server cache

The additionnal workload is not noticeable.

> Please log this on ideas.woocommerce.com - we can revisit if it gains traction.

OK !
