### ISSUE TITLE
Unset parts of REST API

### ISSUE THREAD

**Issue by mattiasghodsian** [woocommerce/woocommerce#12447]
I would like to unset/hide stuff from the rest api, im currently only interested in products in the api and would like to turn off/hide the rest, i dont wanna share users,order etc

Anyone have a snippet for this ?

**Comment by claudiosanches** [comment]
We register our routes using `register_rest_route()` https://developer.wordpress.org/reference/functions/register_rest_route/ (for our new WP REST API integration).
But for now WordPress don't allows unregister routes.

However our legacy API allows you remove endpoints using the filter `woocommerce_api_classes`.
