### ISSUE TITLE
Add support for bulk editing product variations regular and sale prices

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#12446]
Currently (WooCommerce version 2.6.8) bulk editing is allowed for products themselves only. Add support for bulk editing product variations regular / sale prices and possibly other variations settings.

**Comment by pau1phi11ips** [comment]
The  WooCommerce Stock Manager plugin does that pretty well
https://en-gb.wordpress.org/plugins/woocommerce-stock-manager/

**Comment by claudiosanches** [comment]
We support bulk editing variations when you go edit the variable product, but not on the product table screen. Would a very large impact on performance if we try do it.

**Comment by juliaamosova** [comment]
Thanks for sharing the link to the plugin @pau1phi11ips. Thanks for your input @claudiosanches.
