### ISSUE TITLE
Request to Add filter to downloadable file hash generation

### ISSUE THREAD

**Issue by dcelsey** [woocommerce/woocommerce#12444]
## EXPLANATION OF THE ISSUE

If the downloadable file for a product is updated and the filename changes e.g.:

from
.../wp-content/uploads/woocommerce_uploads/2013/07/Coaching-Tools-and-Exercises-MEGAPack-v2.zip
to
.../wp-content/uploads/woocommerce_uploads/2013/07/Coaching-Tools-and-Exercises-MEGAPack-v3.zip

This generates a new file hash which updates the download permissions on existing orders and invalidates the download links in previously sent order confirmation emails.

This default behavior makes sense. However for our business when we update products it leads to a spike in customer support emails  from people trying to (re)download their purchase from emails that predate the update (unless we keep the file path/name identical but this is clumsy and prevents us from versioning the file name).

I have a code modification that works better for our business process where the file hash is left unchanged if we update the downloadable file (rather than deleting/adding a new one). To minimize the changes to core I updated line 1156 (wc 2.6.4) of class-wc-meta-box-product-data.php as follows:

//$file_hash = md5( $file_url );
$file_hash = apply_filters('woocommerce_downloadable_file_hash',md5( $file_url ), $post_id, $file_name ,$file_url, $i);

Would love to see this included in a future release so that there is option of modifying the default file hashing if necessary. It is transparent unless someone uses the new filter.

## STEPS TO REPRODUCE THE ISSUE

1. Create a downloadable product
2. Add a download file (eg. download.pdf)
3. Make a test purchase
4. Check order confirmation email download link
5. Update the download file to a new version with a different file name (e.g. to download_v1.pdf)
6. Check order confirmation email download link - this will now be invalid as the file hash has changed

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://www.tctcbundle.bytesizedwebsites.com
Site URL: http://www.tctcbundle.bytesizedwebsites.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (45) ###

Gravity Forms: by rocketgenius – 2.0.7
WP Affiliate Manager: by wp.insider
wpaffiliatemgr – 2.3.5

Categories Images: by Muhammad Said El Zahlan – 2.5.3
Collapsing Categories: by Robert Felty – 2.0.8
Crazyegg-Heatmap-Tracking: by Crazyegg – 1.1
Cubell Themes - Functionality: by Cubell – 3.2
FacetWP: by FacetWP
LLC – 2.6.3

Image Widget: by Modern Tribe
Inc. – 4.2.2

WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12.1
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Maintenance: by fruitfulcode – 3.1
Magic Thumb for WooCommerce: by Magic Toolbox – 6.0.45
Per page head: by Erik von Asmuth – 1.3
Post Duplicator: by Metaphor Creations – 2.17
Posts 2 Posts: by scribu – 1.6.5
Raw HTML Snippets: by theandystratton – 1.1.3
Relevanssi: by Mikko Saari – 3.5.4
Simple Share Buttons Plus: by Simple Share Buttons – 1.1.5
Social Media Widget: by Noah Kagan – 4.0.5
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri
INC – 1.8.1

Category Order and Taxonomy Terms Order: by Nsp-Code – 1.4.8
TCTC List category posts: by Fernando Briano mod DCE – 0.18.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.21.22

User Switching: by John Blackbourn – 1.0.9
WCK - Custom Fields and Custom Post Types Creator: by Cozmoslabs
Madalin Ungureanu
Cristian Antohe – 2.0.0

WooCommerce Extended Coupon Features: by Jos Koenis – 2.3.6
WooCommerce AWeber Newsletter Subscription: by WooThemes – 1.0.12
WooCommerce Customer/Order CSV Export: by WooThemes / SkyVerge – 4.0.6 – 4.1.1 is available
WooCommerce Filter Orders by Product: by Md. Kowsar Hossain – 2.0.5
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooThemes – 4.4.3
WooCommerce Google Analytics Pro: by WooThemes / SkyVerge – 1.1.4 – 1.1.5 is available
WooCommerce Grid / List toggle: by jameskoster – 1.0.0
WooCommerce Product CSV Import Suite: by Automattic – 1.10.11
WooCommerce - Display Products by Custom Tax: by Elvis Morales – 1.5
WooCommerce: by WooThemes – 2.6.4
WooCommerce Helper: by WooCommerce – 1.7.1
Yoast SEO: by Team Yoast – 3.5
wp-category-meta: by josecoelho
Randy Hoyt
steveclarkcouk
Vitaliy Kukin
Eric Le Bail
Tom Ransom – 1.2.8

WP Edit: by Josh Lobe – 3.9
WP Menu Cart Pro: by Jeremiah Prummer
Ewout Fernhout – 2.5.7

WP-Optimize: by Ruhani Rabin – 1.9.1
WP-reCAPTCHA: by  – 4.1
wpMandrill: by Mandrill – 1.33
WP Overnight Sidekick: by Jeremiah Prummer – 1.0.1
YITH WooCommerce Added to Cart Popup Premium: by YITHEMES – 1.0.7

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #1171 - /coaching-tools-catalogue/
Cart: #12776 - /cart/
Checkout: #12777 - /checkout/
My Account: ❌ Page does not contain the shortcode: [woocommerce_my_account]

### Taxonomies ###

Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

### Theme ###

Name: Valenti Child
Version: 1.0
Author URL: http://themeforest.net/user/cubell
Child Theme: ✔
Parent Theme Name: Valenti
Parent Theme Version: 3.2
Parent Theme Author URL: http://themeforest.net/user/cubell
WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: valenti-child/woocommerce/cart/cart.php
valenti-child/woocommerce/checkout/form-checkout.php
valenti-child/woocommerce/checkout/form-coupon.php
valenti-child/woocommerce/checkout/payment.php
valenti-child/woocommerce/checkout/review-order.php
valenti-child/woocommerce/content-widget-product.php
valenti-child/woocommerce/emails/customer-completed-order.php
valenti-child/woocommerce/emails/customer-note.php
valenti-child/woocommerce/emails/customer-refunded-order.php
valenti-child/woocommerce/emails/email-header.php
valenti-child/woocommerce/emails/email-order-details.php
valenti-child/woocommerce/emails/email-order-items.php
valenti-child/woocommerce/emails/email-styles.php
valenti-child/woocommerce/loop/loop-end.php
valenti-child/woocommerce/loop/loop-start.php
valenti-child/woocommerce/loop/result-count.php
valenti-child/woocommerce/notices/success.php
valenti-child/woocommerce/order/order-details-item.php
valenti-child/woocommerce/order/order-details.php
valenti-child/woocommerce/single-product/add-to-cart/simple.php
valenti-child/woocommerce/single-product/related.php
valenti-child/woocommerce/single-product/tabs/tabs.php

### Customer/Order CSV Export ###

Order Export Format: default_one_row_per_item
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled

**Comment by mikejolley** [comment]
I've added a filter to the new CRUD with I think enough information for you to use.

This is a stopgap measure until #12517 is built.
