### ISSUE TITLE
tabs.php class names correct? 

### ISSUE THREAD

**Issue by learning2** [woocommerce/woocommerce#12445]
/single-product/tabs/tabs.php

On the tabs.php file, are the classes named correctly on line 42? Also, should there be 2 '-' at the end of this run too?

Start of Line 42:
	<div class="woocommerce-Tabs-panel woocommerce-Tabs-panel--<

**Comment by claudiosanches** [comment]
All correct, and the last one uses the `$key` to generate the name, that's why have 2 `-`.
