### ISSUE TITLE
"Calculate Total" on manual orders is not mandatory

### ISSUE THREAD

**Issue by ValeDeOro** [woocommerce/woocommerce#12458]
## EXPLANATION OF THE ISSUE
Shop owners inadvertently create manual orders with the order amount of $0.00 or inferior to the real amount of the products, as they forget to click "Calculate total" after clicking "save" (thinking that "save" - as usual - is the end of the process.

## STEPS TO REPRODUCE THE ISSUE

The expected workflow to create a manual order is this: 

1. WooCommerce >> Add order
2. Fill in the Customer details
3. Click Add item
![](https://cloudup.com/cHCJzsbzYPr+)
Link to screenshot: https://cloudup.com/cHCJzsbzYPr

4. Click what you'd like to add to the order (e.g. Products)
![](http://cld.wthms.co/ZI1O/3C8QkT32+)
Link to screenshot: http://cld.wthms.co/ZI1O/3C8QkT32

5. Search and add the product
![](https://cloudup.com/cwh_vOOFbqH+)
Link to screenshot: https://cloudup.com/cwh_vOOFbqH

6. Click save
![](http://cld.wthms.co/1lP7/5dWMowtA+)
Link to screenshot: http://cld.wthms.co/1lP7/5dWMowtA

Many shop owners think they are done now and proceed direction to Order Actions >> Sent Customer Invoice, **failing to realise that they need to "Calculcate Total" first!!!** 
As Calculate total is also on the opposite site of the screen then the previous "Save", this adds to the confusion

![](http://cld.wthms.co/wHZk/5qWPXQSB+)
Link to screenshot: http://cld.wthms.co/wHZk/5qWPXQSB

**If they fail to calculate total, the order total will not take into account the products just added**

If the user invoice is sent for $0.00, the payment link will not work, and the customer ends up with an error message. 
If the user invoice is sent out with the wrong amount (e.g. some products were not included in the calculation), the shop owner looses out on a lot of money. 

## Solution

Change button text "Save" to "Confirm Product" or "Save Changes"
Change button text "Calculate Total" to "Calculate Order Total"

OR (preferred solution)
Create a warning message "Have you calculated the order total yet?" (Yes / No, go back) when clicking on "Save Order" - instead of directly triggering the Order action: 

![](http://cld.wthms.co/VFZk/fsrBbTjQ+)
Link to screenshot: http://cld.wthms.co/VFZk/fsrBbTjQ

**Comment by Dartui** [comment]
Why not just calculate totals and taxes on Save click? This would be the simplest way to achieve that without any popups and confirmations

**Comment by dixitadusara** [comment]
@mikejolley ,

I have pushed the code for fixes and did pull request # https://github.com/woocommerce/woocommerce/pull/13947 please review it and let us know your thoughts for the same.

Thanks,
Dixita

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/14500
