### ISSUE TITLE
No shipping options offered to the client at checkout

### ISSUE THREAD

**Issue by evelinevinet** [woocommerce/woocommerce#12457]
## EXPLANATION OF THE ISSUE

I entered different shipping options depending on the postal code (which is a mix of digits and letters, with a space in between (ex.   X1X 1X1). According to the distance, we wanted to set a different price for delivery and a different threshold for free delivery. Instore pickup is always an option. Only instore pickup is displayed in the Order Confirmation tab. Which is even more confusing for the customer is that the previous tab ask for the delivery address, if it is or not the same as the billing address. 

## STEPS TO REPRODUCE THE ISSUE

Go to http://servicestraiteur.ca/valleyfield/cafe/boutique/
Put something in the cart
Get to the Checkout page
Last tab (Review and Payment "Confirmation de la commande en cours"), no option is available. 

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://servicestraiteur.ca/valleyfield
Site URL: http://servicestraiteur.ca/valleyfield
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache/2.4.23
PHP Version: ❌ 5.4.45 - Nous recommandons PHP version 5.6 minimum. Voir : Comment mettre à jour votre version de PHP ?
PHP Post Max Size: 128 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 3 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (6) ###

Contact Form 7: par Takayuki Miyoshi – 4.5.1
Fusion Builder: par ThemeFusion – 1.0.5
Fusion Core: par ThemeFusion – 3.0.5
Limiter les tentatives de connexion: par Johan Eenfeldt – 1.7.1
Woocommerce Catalog: par Leonidas Maroulis – 1.2.5
WooCommerce Stripe Gateway: par Automattic – 3.0.6
Importateur WordPress: par wordpressdotorg – 0.6.3
Yoast SEO: par L’équipe Yoast – 3.8
Akismet: par Automattic – 3.2
WooCommerce Multistore: par Lykke Media AS – 1.4.8
WooCommerce Google Analytics Integration: par WooThemes – 1.4.0
WooCommerce: par WooThemes – 2.6.8
LayerSlider WP: par Kreatura Media – 5.6.6
WooCommerce Stripe Gateway: par Automattic – 3.0.6
WP Customer Area: par MarvinLabs – 7.0.8
YITH Composite Products for WooCommerce Premium: par YITHEMES – 1.0.3
YITH WooCommerce Delivery Date Premium: par YITHEMES – 1.0.4
YITH WooCommerce Minimum Maximum Quantity Premium: par YITHEMES – 1.1.9
YITH WooCommerce Catalog Mode Premium: par YITHEMES – 1.4.6
YITH WooCommerce Product Add-Ons Premium: par YITHEMES – 1.2.0.5
YITH WooCommerce Category Accordion Premium: par YITHEMES – 1.0.13

### Settings ###

Force SSL: –
Currency: CAD ($)
Currency Position: right
Thousand Separator: '
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Base Boutique: #288 - /cafe/boutique/
Panier: #289 - /panier/
Commande: #290 - /commande/
Mon Compte: #291 - /mon-compte/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)
yith-composite (yith-composite)


### Theme ###

Name: Avada enfant
Version: 0.1.0
Author URL: http://Les%20Moulins%20La%20Fayette
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.0.5
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada_child/woocommerce/cart/cart-empty.php
Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/product-image.php
Avada/woocommerce/single-product/product-thumbnails.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

`
```

<!--

- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

**Comment by mikejolley** [comment]
Setup issue in your zones no doubt. Please remember a customer can only match one zone, so I suspect you've setup one zone for local pickup and more for the other methods. Don't do this; add all methods you want to each individual zone.

**Comment by evelinevinet** [comment]
<img width="1280" alt="each shipping zone has different shipping methods" src="https://cloud.githubusercontent.com/assets/17929676/20603044/a1ec0b44-b22d-11e6-96da-07bc40abc359.png">
Is the issue related to the fact that zip codes are constituted of letters and numbers in Canada?
Can I use spaces as it should be written like J6S 6C3. Either way, it does not work as it should yet.

**Comment by mikejolley** [comment]
Do your zone rules overlap?

**Comment by evelinevinet** [comment]
Double checked. I see nothing that could overlap. No postal code is in two zones. Zones do have rules to either deliver for free (for more than x amount purchased, x depending on the zone itself), have it delivered at a certain rate or in-store pickup. Where else could there be overlap?

**Comment by mikejolley** [comment]
Do the zones have countries assigned or just postcodes? Might be that?

**Comment by evelinevinet** [comment]
As it's a catering service, everything is delivered within the same region. The different pricing is based on the fact that the owner's car have to travel 30 minutes or 10 minutes. 
Is it possible to only ask for the postcode only at the checkout (and not the country nor the province)? I would not know how to define zones otherwise than with postcodes in that case...?

**Comment by mikejolley** [comment]
Add Canada country to your zones and then test.

**Comment by evelinevinet** [comment]
Tried:
Canada above postcodes (without space)
Canada above postcodes (with space as it should between the 3 first caracters and the 3 last ones)
Canada and Quebec above postcodes (with and without space)
Quebec only above postcodes (with and without space)
It still offers only instore pickup... which is the only option available for "the rest of the world".
So I added another option to "the rest of the world" and options are offered.
Please advise.

**Comment by mikejolley** [comment]
> So I added another option to "the rest of the world" and options are offered.

That means that your zones are just not matching...

You need to have a country set.

Postcodes need to be entered one per line.

**Comment by evelinevinet** [comment]
It works! It works! One postcode per line. Canada above.
You saved my project!
You are quite a Jedi, Mike.
Thanks!
