### ISSUE TITLE
Change Woocommerce Email Template Text

### ISSUE THREAD

**Issue by tonio88s** [woocommerce/woocommerce#12450]
Hi,

I have some email from woocommerce order like this

https://i.stack.imgur.com/UuxPO.png

I want to change Billing address text into Delivery address where could I change that text ?

Thank you.

**Comment by pau1phi11ips** [comment]
You might be better asking the question here: https://wordpress.org/support/plugin/woocommerce

(instead of raising an issue with the code)

**Comment by mikejolley** [comment]
You can edit email templates or use https://wordpress.org/plugins/say-what/ to translate text.
