### ISSUE TITLE
"0" and "0.0" handled differently in product dimensions

### ISSUE THREAD

**Issue by nabsul** [woocommerce/woocommerce#12455]
The issue is (at least) occurring int `WC_Product`: `get_height()`, `get_width()`, `get_length()`, and `get_weight()`.

Specifically the following expression: `$this->height ? $this->height : ''`

If the value of `height` is set to "0.0", the boolean is true and "0.0" is returned. However, if the value is "0", the boolean evaluates to false and an empty string is returned.

I'm not sure if a dimension of zero is valid (I'm leaning towards allowing it), but either way, the treatment of  "0" and "0.0" should be the same.

For our plugin, we are casting the results of these functions using `floatval()`. Though casting these values from a string to float might break compatibility if it were done directly in Core.

**Comment by mikejolley** [comment]
@nabsul Is this on Master or 2.6.x do you know?

**Comment by coderkevin** [comment]
Actually, this still happens on master, maybe the metabox updates are still treating these things like strings?

**Comment by nabsul** [comment]
@mikejolley I found the issue on 2.6.8.

**Comment by mikejolley** [comment]
Master uses:

`
$this->set_prop( 'height', '' === $height ? '' : wc_format_decimal( $height ) );
`

So looks as though only 2.6 is affected.
