### ISSUE TITLE
How to upload files by API

### ISSUE THREAD

**Issue by WaldenStew** [woocommerce/woocommerce#12459]
I'd like to upload a file by the API into the media library ... [seems like the image upload process (it works)] 
The url is correctly save in the backoffice 'downloadable file' field
But, the file is never integrated in the media library... is there an issue to do this or is it impossible ?

I use this code 

$dataDownloads[] = 
[
'id' =>'',
'name' => $display_filename,
'file' => $url_file
]
$data =
[
'update' =>
[
 'id' => $idPdt,
'downloads' => $dataDownloads 
 ]
 ]
 ];

$wooCommerce->post('products/batch', $data);

WP version 4.6.1
WooCommerce version 2.6.8

Thx

**Comment by mikejolley** [comment]
This is not supported, you need a public link to the resource to send to the API. Downloads just store the link you provide. Downloads do not need to be in media library either.
