### ISSUE TITLE
Batch products tags API endpoint not available

### ISSUE THREAD

**Issue by AggressiveSneeze** [woocommerce/woocommerce#12451]
Hi there!

Pretty sure the batch tags endpoint either isn't implemented or is malfunctioning.

This is what happens when you try make a post request:

```
2.1.2 :037 > woo_api.post("products/tags/batch",{}).parsed_response
 => {"errors"=>[{"code"=>"woocommerce_api_no_route", "message"=>"No route was found matching the URL and request method"}]} 

```
Also happens if you provide some data instead of an empty hash.

**Comment by claudiosanches** [comment]
Don't have any batch route for our legacy API, only for our new WP REST API integration. And you are trying to use the legacy one.
