### ISSUE TITLE
API - role field not returned from wp/v1 version - customers endpoint

### ISSUE THREAD

**Issue by babinos87** [woocommerce/woocommerce#12468]
Hi,

We use WooCommerce API to pull data from our client's e-shop. Recently, they have upgraded to a newer version that supports the WP v1 version (latest). So far we used to pull their data from Legacy v3 API. 

In Legacy V3 API, we could get a 'role' field for the customers, when we were retrieving customers. From the new API (wc/v1) it seems that this field is no longer there. 

Is this expected or is it a bug? If this was done in purpose, is there any chance that you can put that field back on the customers endpoint? We used to match this field to identify a customer type. Was quite useful for this purpose. If you could restore this field to be available to the latest WooCommerce API version, it would be fantastic.

Regards,
Babis

**Comment by babinos87** [comment]
This is great, thank you very much!

**Comment by babinos87** [comment]
Is this included in new 2.6.9 version?

**Comment by mikejolley** [comment]
No, it will be in 2.7
