### ISSUE TITLE
'product.deleted' webhook gets called when coupon gets deleted

### ISSUE THREAD

**Issue by colthreepv** [woocommerce/woocommerce#12461]
## EXPLANATION OF THE ISSUE
WooCommerce 2.6.8
Wordpress 4.6.1
Apache 2
PHP 7

## STEPS TO REPRODUCE THE ISSUE
  * Create a webhook via REST API specifying that you want to be notified for `product.deleted`
  * In the woocommerce panel, delete a coupon
  * Look at your webhook gets fired (with the coupon id!)

**Comment by mikejolley** [comment]
See #12466
