### ISSUE TITLE
product and add product menu of admin panel (backend area) very slow work !

### ISSUE THREAD

**Issue by yasko88** [woocommerce/woocommerce#12471]
I try a multivendor website with woocommerce and I need about 4000 categories. I opened about 4000 categories and products and add products menus worked very slowly. Other admin menus or pages were very fast. 
Then I deleted mywebsite and reinstall everything . And I opened now 1953 categories and I noticed again that Products and add products menus work now very slow !

This is a big issue. I can not solve problem. Perhaps woocommerce have some limits. Because mywebsite is very fast and I dont have any products yet. It is not about my hosting.

I hope somebody help me.
Thank you

**Comment by mikejolley** [comment]
Have you looked into what is outputting categories then? Is it your multivendor plugin?

**Comment by yasko88** [comment]
Thank you @mikejolley for your reply.
No my plugin. I am not developer only wordpress , joomla etc. user. I will use wc vendor or wc marketplace. But now testing Wc vendor plugin. And I can not understand 'outputting categories' ... My english is not very good. And google can not translate this good..
I send today you an email from  (my mail adress @gmail) to (yourname@me.com) .... I got a video my admin panel and I tested woocommerce and wordpress menues. So you can see slow and fast menues.
Sorry But I can not share here video link. I send you already.
Thank you very much! I hope we can solve this problem.
Have a great day!

**Comment by mikejolley** [comment]
Please do a test with the vendors plugin and other plugins disabled. See if one of those are causing slowdown.To my knowledge, WC does not output all categories anywhere which would cause slow down.

**Comment by yasko88** [comment]
Yes, I tested All plugin and I find a problem with Yoast Seo plugin ... When deactive yoast 'product add menu' is faster but when active it 'product add menu' is very slowly.... We solved 'add product menu'.

But still there is a problem 'product menu'. It is still slowly.
The link :   wp-admin/edit.php?post_type=product      ...... And I have add about 1000 categories. I hope it will no again. 

Really I want to thank you millions of times... Because it is very boring problem. I hope we can solve product menu ,too... I am looking forward to another suggestion. Thank you so much!
Have a great day !

**Comment by yasko88** [comment]
@mikejolley , I install new wordpress and no install any plugin, themes or codes. Only wordpress and woocommerce. And I opened a lot of meaningless categories quickly. And again product menus is slowly.

This is not vendor plugin or different plugin problem. This is only woocommerce problem. And I write woocommerce support. They only said me write wordpress forum. Authors will see it. You know any authors dont help usually there. Only sometimes. Only help us @lorro and somebody.

How can solve this slow queries problem ?

Thank you

**Comment by mikejolley** [comment]
Here is a test for you. Open up a whole bunch of POST categories instead of product categories and look at your menus. Same slow down?

**Comment by yasko88** [comment]
okay. I will test it but I need a few day. because it no be quickly. Thank you !

**Comment by yasko88** [comment]
I delete prodcut cateories in my test website now (wordpress 2) and you can notice easily difference. It is now very fast load. I changed my mind again. I will use it like this because I am tired of reinstall and open categories again and again. Anyway. We can understand easily there is a problem in wordpress or woocommerce.

**Comment by mikejolley** [comment]
Maybe we can add caching to our wc_product_dropdown_categories function.

**Comment by yasko88** [comment]
Ok. Thank you. I hope you will solve this problem !

Have a nice day!

**Comment by mikejolley** [comment]
Closed in favour of #12773
