### ISSUE TITLE
Variations Issue: 

### ISSUE THREAD

**Issue by Ben7217** [woocommerce/woocommerce#12484]
I am having an issue with the variations. I can't "see" my variations in order to edit them: 

![screen shot 2016-11-28 at 5 41 03 pm](https://cloud.githubusercontent.com/assets/19725234/20692511/c0fede2e-b595-11e6-8781-f54fa13f8a93.png)

I have everything updated to the newest versions. Very strange. 

`
### WordPress Environment ###

Home URL: http://www.modernconjurer.com
Site URL: http://www.modernconjurer.com
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en

### Server Environment ###

Server Info: Apache/2.4.23
PHP Version: 5.6.25
PHP Post Max Size: 300 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (16) ###

Coming Soon wp: by dazzlersoft – 1.3
Contact Form 7: by Takayuki Miyoshi – 4.5.1
Image Rotator Widget: by Douglas Karr
Stephen Coley – 1.2.1

WP FullScreen Slider: by Alex Ilie – 1.0.0
Google Analytics: by Kevin Sylvestre – 1.0.7
IgniteUp: by Ceylon Systems – 3.2
Jetpack by WordPress.com: by Automattic – 4.4.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.11.1
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Go Daddy Quick Setup: by GoDaddy.com
LLC – 1.04

Seo Wizard: by theseowizards – 4.0.2
Smart Slider 3: by Nextend – 3.1.2
Smart Social Media Widget: by Alexander Tchernitchenko – 2.0.0
Virtue / Pinnacle ToolKit: by Kadence Themes – 3.6
WooCommerce: by WooThemes – 2.6.8
Clef: by Clef – 2.6.1

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #18 - /shop/
Cart: #19 - /cart/
Checkout: #20 - /checkout/
My Account: #21 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Lensa
Version: 2.0.9
Author URL: https://colorlabsproject.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: lensa/woocommerce/archive-product.php
lensa/woocommerce/cart/cart.php
lensa/woocommerce/checkout/form-checkout.php
lensa/woocommerce/checkout/form-coupon.php
lensa/woocommerce/checkout/form-login.php
lensa/woocommerce/checkout/form-shipping.php
lensa/woocommerce/checkout/review-order.php
lensa/woocommerce/checkout/thankyou.php
lensa/woocommerce/content-product.php
lensa/woocommerce/content-product_cat.php
lensa/woocommerce/content-single-product.php
lensa/woocommerce/global/breadcrumb.php
lensa/woocommerce/global/wrapper-end.php
lensa/woocommerce/global/wrapper-start.php
lensa/woocommerce/loop/loop-start.php
lensa/woocommerce/loop/pagination.php
lensa/woocommerce/myaccount/form-login.php
lensa/woocommerce/myaccount/form-lost-password.php
lensa/woocommerce/myaccount/my-address.php
lensa/woocommerce/myaccount/my-downloads.php
lensa/woocommerce/myaccount/my-orders.php
lensa/woocommerce/single-product/add-to-cart/external.php
lensa/woocommerce/single-product/add-to-cart/grouped.php
lensa/woocommerce/single-product/add-to-cart/simple.php
lensa/woocommerce/single-product/add-to-cart/variable.php
lensa/woocommerce/single-product/meta.php
lensa/woocommerce/single-product/product-image.php
lensa/woocommerce/single-product/product-thumbnails.php
lensa/woocommerce/single-product/related.php
lensa/woocommerce/single-product/review.php
lensa/woocommerce/single-product/short-description.php
lensa/woocommerce/single-product/tabs/additional-information.php
lensa/woocommerce/single-product/tabs/description.php
lensa/woocommerce/single-product/tabs/tabs.php
lensa/woocommerce/single-product.php

**Comment by justinshreve** [comment]
What browser and operating system are you using?

**Comment by Ben7217** [comment]
Thanks for the response but it was a plug-in issue.
