### ISSUE TITLE
Free shipping does not include fees

### ISSUE THREAD

**Issue by mikldk** [woocommerce/woocommerce#12482]
Setting a minimum order amount for allowing free shipping does not include order fees in the calculations.

This is desired as negative fees are sometimes used for simple discounts, but these discounts can result in the order total being less than the amount required, but free shipping is still available.

## STEPS TO REPRODUCE THE ISSUE

Any call to cart's add_fee is disregarded when check if an order is eligible for free shipping.

**Comment by mikejolley** [comment]
Fees are added after shipping is calculated. Fees themselves are never 'shippable'.

Your use case of negative fees is also not something I see as being officially supported. There is a discount/coupon system already in place for that.
