### ISSUE TITLE
Variation select box breaks on chrome when show_option_none is false

### ISSUE THREAD

**Issue by innocuo** [woocommerce/woocommerce#12485]
## EXPLANATION OF THE ISSUE

If you hide the "Choose an Option" option in a variable by setting show_option_none to false, the variant select box will act strangely: after you select a variant, you click on the select box again to choose a different one, and will notice the last option is selected, regardless of what variation you had previously selected. This prevents users to select the last option (as the select box thinks the last option is already selected).

I tested this issue on OSX on Chrome v54.0.2840.98 and Firefox v50.0 with the twentytwelve theme and flatsome theme. It seems to work ok on Safari. The bug happens on woocommerce v2.6.8. I tested on v2.6.4 and it works ok.

It seems the source of the issue is in woocommerce/assets/js/frontend/add-to-cart-variation.js, 
in the 'variations select' handler (line 333 on v2.6.8). This is triggered when you click on the variation select box, and seems to remove all the options from the dom and then appends them again. 

The jquery selector used is 
`current_attr_select.find( 'option' + option_gt_filter )`

option_gt_filter is '' when "show_option_none" is set to false, and it is ":gt(0)" when "show_option_none" is set to any other value.

This means, that the bug occurs when the js removes all options from the variation select box, but not when at least one option remains in the select box.

v2.6.4 works ok, because the jquery selector is always 
`current_attr_select.find( 'option:gt(0)' )`
It also works ok when show_option_none is not modified, because it'll always leave the "Choose an option" option.

## STEPS TO REPRODUCE THE ISSUE

1. add the following to your theme's functions.php:
`
add_filter( 'woocommerce_dropdown_variation_attribute_options_args', 'change_show_option', 10, 1 );
function change_show_option( $args = array() ) {
   $args['show_option_none'] = '';
   return $args;
}
`

2. go to a variable product and play with the variable select box on chrome of firefox.

**Comment by franticpsyx** [comment]
>I tested on v2.6.4 and it works ok.

I remember there was a script error associated with this condition that was fixed in https://github.com/woocommerce/woocommerce/pull/11944

I will try to replicate this and submit a fix. At some point it would be a good idea to re-write that script to eliminate all this DOM fiddling (of course in a backwards compatible manner).
