### ISSUE TITLE
Can't get product variation in a specific language

### ISSUE THREAD

**Issue by Daaaaad** [woocommerce/woocommerce#12496]
Hello,

When working with the WooCommerce API and LocoTranslate (as advised in the documentation 😉) I'm encountering a problem trying to get a product variation in a specific language :

```
$product = $woocommerce->get('products', [
    'sku' => $sku,
    'filter' => [
        'lang' => 'en'
    ]
]);
```

This code works perfectly with a (parent) product SKU, but when it comes to a variation the lang filter is a problem and the method returns an empty result 😢

**Comment by mikejolley** [comment]
The issue may be that this endpoint is for products only, not variations. 2.7.x will have a dedicated variations endpoint you can use.

You would need to get the parent and look at it's 'variations' property to get at the data.
