### ISSUE TITLE
REST API GET products with parameters are not working

### ISSUE THREAD

**Issue by jcaluminga** [woocommerce/woocommerce#12498]
## EXPLANATION OF THE ISSUE

When i am using the normal get method (wp-json/wc/v1/products) it works fine but when i add a parameter for example (wp-json/wc/v1/products?category=11) it returns an error which is "Invalid Signature - provided signature does not match".

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://customadesign.info/klassickutz
Site URL: http://customadesign.info/klassickutz
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.28
PHP Post Max Size: 1 GB
PHP Time Limit: 0
PHP Max Input Vars: 1000000
cURL Version: 7.38.0
OpenSSL/1.0.0

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. PayPal IPN won't work with your server. Contact your hosting provider. Error: Unsupported SSL protocol version
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (12) ###

Gravity Forms: by rocketgenius – 2.1.1
Envira Gallery Lite: by Thomas Griffin – 1.5.0.7
Global Gateway e4 | Payeezy Gateway | Clover Gateway: by DonnellC – 2.0
Gravity Forms Authorize.Net Add-On: by rocketgenius – 2.3
JSON API User: by Ali Qureshi – 2.5
JSON API: by Dan Phiffer – 1.1.1
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
WP REST API - OAuth 1.0a Server: by WP REST API Team – 0.3.0
WooCommerce Direct Checkout: by Terry Tsang – 1.1.2
WooCommerce PayPal Express Checkout Gateway: by Automattic/WooCommerce – 1.0.4
WooCommerce: by WooThemes – 2.6.4
WP Responsive Menu: by MagniGenie – 2.0.7

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #14 - /shop/
Cart: #55 - /cart/
Checkout: #56 - /checkout/
My Account: #57 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: CAD WP Base Theme
Version: 3.0.0
Author URL: http://marcelbadua.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: klassickutz/woocommerce/content-product.php
`

**Comment by mikejolley** [comment]
Difficult to advise without seeing the API requests/code. When you add query string variables, those need to be added to the signature generation too - see the rest api docs. http://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http
