### ISSUE TITLE
Listing wrong Prices

### ISSUE THREAD

**Issue by artiisan** [woocommerce/woocommerce#12491]
## EXPLANATION OF THE ISSUE

 Version 2.6.8 Is listing the wrong prices on the frontside of my clients website but only on 2 products.

## STEPS TO REPRODUCE THE ISSUE

I've had no luck in replicating it
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
Not sure how to grab the status report

**Comment by mikejolley** [comment]
Without providing steps to reproduce this there is nothing our team can do here; based on that fact it also indicates that it could simply be a mistake or plugin conflict on your clients site only. If this is a product you're imported, re-save it and make sure all caches are cleared.
