### ISSUE TITLE
woocommerce_pay_order_before_submit not working

### ISSUE THREAD

**Issue by DawidUrbanski** [woocommerce/woocommerce#12506]
Not sure is this a bug, but for sure it's not working. I can't figure why.

```
add_action('woocommerce_pay_order_before_submit', function(){
    echo 'test';
});
```
Fresh clean installation. WP 4.6.1, Woo 2.6.8, fully updated Twenty Twelve. PHP 7.0.13. No other plugins installed. No customization.

**Comment by mikejolley** [comment]
The pay page is not the same as the checkout page. You're probably just looking in wrong place. Try `woocommerce_review_order_before_submit`
