### ISSUE TITLE
How to generate oauth_timestamp,oauth_nonce ,oauth_signature for react native

### ISSUE THREAD

**Issue by mjet08** [woocommerce/woocommerce#12505]
I am working on react native app. I want to connect my app to woocommerce api, for that I need to pass consumer key,time stamp, auth signature while making network requests. So My url should be as shown below:

`http://quflip.com/wp-json/wc/v1/products?oauth_consumer_key=ck_75a6b3f5cf97e03a2bd42c8e4dffaefe07538bfb&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1480656796&oauth_nonce=2qL1ca&oauth_version=1.0&oauth_signature=6AJyrlsjcm2BxlMS1HSo3b0TTek=`

So , how can acheive the url request as shown above ?

**Comment by mikejolley** [comment]
We cannot help you custom code your API handlers here sorry. This tells you how to generate a signature, you just need to apply it to your language http://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

**Comment by mjet08** [comment]
I do not want to modify apis , I just want to know how to pass those
parameters in android app or react native app

**Comment by mikejolley** [comment]
Authentication with an API is not modifying the API... I'm not an Android developer so I cannot really help you out there. Surely there are examples for apps which use other APIs which can be adapted?
