### ISSUE TITLE
Styles aren't applied on Pay for Order page?

### ISSUE THREAD

**Issue by dominic-p** [woocommerce/woocommerce#12504]
Possibly a theme issue, but when I look at a Pay for Order page, some of the front end styles aren't applied (especially to the payment method selection area).

Looking at the selectors, it looks like they use: `.woocommerce-checkout #payment`, and on the Pay for Order page there is no parent element with the `.woocommerce-checkout` class. That class is assigned to the main `<form>` element on the checkout page, but the [form element on the Pay page](https://github.com/woocommerce/woocommerce/blob/2.6.8/templates/checkout/form-pay.php#L24) has no class.

Should the `.woocommerce-checkout` class be added to the `<form>` for the Pay for Order page?

**Comment by mikejolley** [comment]
Core uses `.woocommerce, .woocommerce-page {` as the parent selectors for `#payment` so yeah, I think it's a theme issue.

**Comment by dominic-p** [comment]
Thanks for getting back to me. At the risk of embarrassing myself, isn't this where the [parent selector](https://github.com/woocommerce/woocommerce/blob/2.6.8/assets/css/woocommerce.scss#L1612-L1614) is defined?

I'm guessing you were referring to the woocommerce-layout.css file [selector here](https://github.com/woocommerce/woocommerce/blob/2.6.8/assets/css/woocommerce-layout.scss#L16). But, it looks like most of the styles are applied by the woocommerce.css file linked above.

Am I missing something?

**Comment by mikejolley** [comment]
Oops my bad :) Order pay does have the woocommerce-checkout class though. https://dl.dropboxusercontent.com/s/k1wei38484n256h/2016-12-05%20at%2022.20.png

**Comment by dominic-p** [comment]
Yep, it was a theme issue (the body class wasn't being added). Sorry to waste your time, and thanks for pointing me in the right direction.
