### ISSUE TITLE
"sale" badge still there, even if sale ended

### ISSUE THREAD

**Issue by scrobbleme** [woocommerce/woocommerce#12501]
## EXPLANATION OF THE ISSUE

A customer reported this to me. 
She did a sale with a scheduled end date. 

After the sale ended:

- prices are okay
- products still have the "sale" badge

## STEPS TO REPRODUCE THE ISSUE

Create a scheduled sale, and wait until it ends

(Workaround: remove the sale manually)

**Comment by mikejolley** [comment]
Cannot seem to replicate this one - prices are updated, and thats what the is_on_sale check uses so I cannot see where this would fail.. Is it variable? If so it's cache and we fixed in master/2.7. No bug exists with simple products though.
