### ISSUE TITLE
Drag/drop sorting of variations sets incorrect menu order

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#12503]
## EXPLANATION OF THE ISSUE

When there is more than one page of variations under a variable product, the drag/drop sorting sets a menu order for the variations. The problem is that when using the drag/drop, it will only add the menu order for the current page. 

This means that if there are 3 pages that all have the default of 0 or 1 as the menu order, and the first page has an order change, then that first page will now have been ordered 1-15. Once saved, the items on the first page are now pushed to the last page because their priority is lower than the rest of the items that have their default at 0/1. 

## STEPS TO REPRODUCE THE ISSUE

Create new variable product and add the attributes below (these don't actually matter, but this gives you a starting point):

Color: 
```
Black | Blue | Dark Orange | Exorcist Green | Green | Light Blue | Orange | Pale Green | Purple | Red | Teal | White | Yellow
```
Size:
```
Extra Large | Large | Medium | Small | XX Large
```

Next, create variations from all attributes:
![screen shot on 2016-12-01 at 09 3a36 3a00](https://cloud.githubusercontent.com/assets/4634416/20799278/ae0606f0-b7af-11e6-9cfb-30b17d3b1fa1.png)

And then drag/drop to sort the first page and then save, this will push the items on the first page to the last page:
![screen capture on 2016-12-01 at 09-38-24](https://cloud.githubusercontent.com/assets/4634416/20799329/ced00228-b7af-11e6-97af-1c3456316cd6.gif)

I did notice that if you start at later pages, they are correctly numbered according to what page you are on.  Page 2 is numbered 16-30, page 3 is 31-45, etc.

**Comment by mikejolley** [comment]
Let's fix this in the CRUD with a single query if possible.

**Comment by mikejolley** [comment]
See #12547
