### ISSUE TITLE
Make product attributes link through to archives

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#12518]
If archives are enabled for a product attribute, make the attributes listed on the product pages link through to these archives.

**Comment by claudiulodro** [comment]
Can you please clarify whether I'm picking up what you're putting down?

On this page: https://demo.woothemes.com/storefront/product/blue-shoes/
Under "Additional Information" there is "Color" -> "Blue". You want the word "Blue" to link to the archive page with all the blue stuff on it, correct?

**Comment by mikejolley** [comment]
That's what I had in mind yes. Archives can be enabled or disabled per global attribute. See in admin products > attributes.
