### ISSUE TITLE
Endless loading checkout page

### ISSUE THREAD

**Issue by Ziusz** [woocommerce/woocommerce#12514]
Checkout page on my site loads very slow when the rest of the site runs fast. All things like WooCommerce, WooCommerce Helper and MyStile are updated and run on the newest stable versions. The rest of plugins is turned off. It's a server configuration problem on 100% because It's also on fresh installed woocommerce with new database. I don't have any error in browser's js console.

URL: http://komisarzorlowska.pl
System status: http://i.imgur.com/YBMgWMW.png

**Comment by mikejolley** [comment]
It's not loading slow for me - the ajax update was < 1 sec. Please use Github for bug reports only anyhow as it states in the new issue form. Thanks.
