### ISSUE TITLE
Shipping not applicable for backorders

### ISSUE THREAD

**Issue by krisveejay** [woocommerce/woocommerce#12516]
## EXPLANATION OF THE ISSUE

Currently using WordPress 4.5.4 with Woocomemrce Version 2.6.3 the theme Storefront . One of our customers have ordered a product which is in backorder. But the shipping was not enabled to him so the payment was made without shipping. How can we enable general shipping even if the  backordered product is ordered.

## STEPS TO REPRODUCE THE ISSUE

1. Backorder was allowed and the product came from 0 to -1 when customer ordered.
![image](https://cloud.githubusercontent.com/assets/24386321/20882162/f306a240-badf-11e6-83e6-6abe37f74ed4.png)
2. When customer selected the product alone shipping is not enabled.
![image](https://cloud.githubusercontent.com/assets/24386321/20882269/65f33174-bae0-11e6-9dea-93174190e17f.png)

3. In normal case when the product is available in stock shipping is shown.
![image](https://cloud.githubusercontent.com/assets/24386321/20882318/9fb57ab6-bae0-11e6-9c12-5c22d50a9fbd.png)

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://www.smartchoice.se
Site URL: http://www.smartchoice.se
WC Version: 2.6.3
Log Directory Writable: ✔
WP Version: 4.5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.3
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (29) ###

Add Logo to Admin: of c.bavota - 1.6.2
Share Buttons by AddThis: av The AddThis Team – 5.3.4
BAW Login/Logout menu: of Juliobox - 1.3.3
Google Tag Manager for Wordpress: by Thomas Geiger - 1.4
Embed Google Map: av Petteri Kivimäki - 3.2
Google Language Translator: by Rob Myrick - 5.0.20
Google Site Verification plugin using Meta Tag: Period Himanshu - 1.0
Hello Dolly: by Matt Mullenweg - 1.6
Homepage Control: by WooThemes - 2.0.2
Loco Translate: by Tim Whitlock - 2.0.7
Meta Slider: of Matcha Labs - 3.3.7
My Custom Functions: by Arthur Gareginyan - 3.3
WooCommerce - Now In Store Catalog Builder: av Now In Store Inc. – 2.0.1
PDF Product Catalog 2 for WooCommerce: av Kyriakos Ktorides - 2.0.2
Storefront Extension - Align Menu Right: of PootlePress - 1.0.0
Social Media Widget: by Noah Kagan - 4.0.5
Stock Export and Import for WooCommerce: of Potent Plugins - 1.0.2
Storefront Site Logo: of Wooassist - 1.2.1
WA Activation: of - v1.0.1
WooCommerce EU VAT Compliance (Free): by David Anderson - 1:10:26
WooCommerce - Store Exporter: by Visser Labs - 1.8.6
WooCommerce PayEx Payments Gateway: av strokes Team - 2.0.4
WooCommerce Payment Gateway - Inspire: the inner fire - 1.7.6
WooCommerce PDF Invoices & Packing Slips: av Ewout Fernhout - 05/01/37
WooCommerce Pricefiles: by Peter Elmered - 0.1.11
WooCommerce: by WooThemes - 2.6.3
WordApp - Wordpress to Mobile App plugin for WooCommerce & BuddyPress: of App-Developers.biz - 1.16.13
Yoast SEO: by Team Yoast - 3.7.0
We WooCommerce Zoom Magnifier: av YITHEMES - 1.2.22

### Settings ###

Force SSL: –
Currency: SEK (kr)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Butikbas: #122 - /shop/
Varukorg: #335 - /cart/
Kassan: #123 - /checkout/
Mitt konto: #124 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Storefront
Version: 2.0.6 - 2.1.6 is available
Author URL: https://woocommerce.com/
Child Theme: ❌- If you modify WooCommerce a parent theme you have not built
so we recommend that you use a child theme instead. Learn: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Virtual = no shipping.
