### ISSUE TITLE
Woocommerce not sending emails after checkout

### ISSUE THREAD

**Issue by andresamuels1** [woocommerce/woocommerce#12513]
Hi  no totally given up.  When checking out of the site using payment method BACS everything all received emails admin and customer works 100%.

Problem is when user uses payfast option to check out, just no  work. Did  much reading and tried different settings without much luck.

Using plugin postmaster mail for wp via sendgrid API.

Hope you can help.

Site is aquariumstoreonline.co.za

**Comment by andresamuels1** [comment]
Anyone?

**Comment by mikejolley** [comment]
If it affects one gateway, it stands to reason the gateway is having problems either not updating the order, or not handling the order correctly after payment. Check logs of that gateway to find out more or ask the author for support directly.

Use mail logging plugins to ensure it's not just spam/unrelated. If it's logged, it's "sent".

This is not a support forum so I'm closing this report.
