### ISSUE TITLE
API Request Logging

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#12519]
Log API requests somewhere for later review.

@claudiosanches can you list what is needed here?

**Comment by danielhuesken** [comment]
I have already written a logging for REST-API requests. If you would have a look, feel free to ask me.

**Comment by mikejolley** [comment]
https://en-gb.wordpress.org/plugins/wp-rest-api-log/

**Comment by Ciantic** [comment]
@danielhuesken how did you log them? I'm trying that wp-rest-api-log, but it doesn't mention it works with WooCommerce.
