### ISSUE TITLE
Lost Password and Logout endpoints do not default back to WP defaults when empty

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#12526]
## EXPLANATION OF THE ISSUE

If **Lost Password** and **Logout** fields are left blank to disable the endpoints, they do not fall back to the default WordPress URLs to complete the action.

## STEPS TO REPRODUCE THE ISSUE

1. Navigate to **WooCommerce > Settings > Accounts**
2. Remove empty **Lost Password** and **Logout** fields.

<img width="300" alt="screen shot 2016-12-06 at 3 03 01 pm" src="https://cloud.githubusercontent.com/assets/2876178/20943480/3468ca84-bbc5-11e6-9048-0f2a43b803b8.png">

3. Attempt to logout from My Account page.
4. Attempt to use Lost Password? option while logged out.

**Comment by mikejolley** [comment]
See #12535
