### ISSUE TITLE
date_paid missing timezone indicator

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/woocommerce#12528]
User writes:

----

The Orders endpoint have some date-time fields don't return the timezone indicator. For example here are 4 dates:

```
"date_completed": "2016-12-02T14:55:21", 
"date_created": "2016-12-02T03:55:21", 
"date_modified": "2016-12-02T03:55:21", 
"date_paid": "2016-12-02 14:55:22",
```

You can see all the dates except for the ```date_paid``` include a timezone indicator. Is this by design or should the ```date_paid``` be returning a timezone indicator.

----

Reference: 503423-zd-woothemes

**Comment by mikejolley** [comment]
Checked and this is fixed in master (2.7). It will be part of that release :)
