### ISSUE TITLE
Page_Style Not Supported on New Paypal Interface

### ISSUE THREAD

**Issue by hstar7** [woocommerce/woocommerce#12523]
## EXPLANATION OF THE ISSUE
Page_style is currently not supported in Paypal new interface. When I specify a page_style on the Advanced options in WooCommerce Settings, the expected page_style is not used. 

I raised the issue with Paypal and this was their response 

Thank you for contacting PayPal Merchant Technical Support.
Please be informed that "page_style" variable is not being currently supported on our new interface. This clarifies as to why you are not able to see the custom page on the checkout page.
As the workaround, please remove the page_style variable and use image_url instead. For more details, please have a look on following documentation:-

Notice they said workaround is to use image_url. I have tried this and works correctly with image_url. I'm not sure if Paypal will enable page_style wihtin their new interface and I don't know what they mean when they say new interace. 

I have manually added image_url to paypal request class as a temporary workaround for now which works but wanted to raise issue.

## STEPS TO REPRODUCE THE ISSUE

1. Add page style under Woo Commerce->Settings->Checkout->Paypal->Page Style
2. Test your paypal checkout -> Default checkout is used instead of custom page specified with page_style

You may have different result depending on which Paypal interface version you're using

## SYSTEM STATUS REPORT

WC Version:		2.6.8
WP Version:		4.6.1
Server Info:		Apache
PHP Version:		5.6.28
PHP Post Max Size:		64 MB
PHP Time Limit:		300
PHP Max Input Vars:		1000
cURL Version:		7.38.0, OpenSSL/1.0.1e
WC Database Version:		2.6.8

**Comment by mikejolley** [comment]
We'd have to add image_url in addition - since both are documented https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/

**Comment by mikejolley** [comment]
See #12546
