### ISSUE TITLE
Persistent cart storage is not multisite aware

### ISSUE THREAD

**Issue by dnaber-de** [woocommerce/woocommerce#12534]
## EXPLANATION OF THE ISSUE

I'm running a WordPress multisite install to serve a web shop to different regions (different languages in different countries) and different customer groups (B2B and B2C). (See »Steps to reproduce« for an example setup.) Users are allowed, however to purchase in different shops with their network wide unique profile (default multisite feature of shared accounts).

A customer reported that she discovered products in her cart that she didn't placed there. After some investigation I found that the persistent cart storage is not multisite aware as the cart is stored as a user meta without any relation to the current blog ID.

It all happens in `WP_Cart::get_session_from_cart()`:

```php
public function get_cart_from_session() {
	// Load cart session data from session
	foreach ( $this->cart_session_data as $key => $default ) {
		$this->$key = WC()->session->get( $key, $default );
	}

	$update_cart_session         = false;
	$this->removed_cart_contents = array_filter( WC()->session->get( 'removed_cart_contents', array() ) );
	$this->applied_coupons       = array_filter( WC()->session->get( 'applied_coupons', array() ) );

	/**
	 * Load the cart object. This defaults to the persistent cart if null.
	 */
	$cart = WC()->session->get( 'cart', null );

	if ( is_null( $cart ) && ( $saved_cart = get_user_meta( get_current_user_id(), '_woocommerce_persistent_cart', true ) ) ) {
		$cart                = $saved_cart['cart'];
		$update_cart_session = true;
	} elseif ( is_null( $cart ) ) {
		$cart = array();
	}

	/* … */
}
```

If there's no `cart` key in the WooCommerce session, it falls back to the user meta which might contains a cart from a different shop site. (See »Steps to reproduce«.)

To make this feature mutlisite aware, it somehow has to relate to the site ID the cart were stored for. A suffixed meta key (e.g. `_woocommerce_persistent_cart_<BLOG_ID>`) would be the preferred method in my opinion (instead of structuring the serialized content within `_woocommerce_persistent_cart`). However, I found two functions `woocommerce_load_persistent_cart` and `wc_load_persistent_cart` which are both marked as deprecated. Actually it would be a good thing to »un-depricate« `wc_load_persistent_cart` and implement it in the business logic of `WC_Cart` instead of directly referring to the user meta each and every time.

## STEPS TO REPRODUCE THE ISSUE

<ol>
<li>
 Create a multisite with the following setup:
<pre><code>my-site.local/     (Site A, COOKIEPAHT = /)
my-site.local/b2c/ (Site B, COOKIEPATH = /b2c/, WooCommerce activated)
my-site.local/b2b/ (Site C, COOKIEPATH = /b2b/, WooCommerce activated)
</code></pre>
It doesn't matter whether you use sub-directories or sub-domains. I uses the latter one to be more flexible and just adapted the RewriteRules a bit so I can combine both, sub-domains and sub-directories.
</li>
<li>Create some products in SITE B and SITE C, make sure at least one product share the same ID on each site.</li>
<li>Open a browser and login to the network. Add a product with a overlapping ID in your cart on Site B.</li>
<li>Open <em>another browser</em> and browse to my-site.local/ and log in. Now browse to SITE C and find a product in your Cart. It's important that there's no session cookie or session in the database stored related to your user, otherwise it would restore the cart from this session instead of the user meta.</li>

The use case is, that a user fills their cart on Site B for a personal use and later, from another device maybe, they want to purchase something with the same account on another shop.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://my-project.dev/B2B
Site URL: http://my-project.dev/B2B
WC Version: 2.6.7
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: 7.0.13-1+deb.sury.org~trusty+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.7
:
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (22) ###

Contact Form 7 - Dynamic Text Extension: by Chris Mavricos
SevenSpark – 2.0.1

Contact Form DB: by Michael Simpson – 2.10.25
Contact Form 7: by Takayuki Miyoshi – 4.5.1
Cookie Law Info: by Richard Ashby – 1.5.3
ElasticPress: by Taylor Lovett
Matt Gross
Aaron Holbrook
10up – 2.1.1

Shortcodes Ultimate: by Vladimir Anokhin – 4.9.9
Storefront Footer Bar: by WooThemes – 1.0.3
Storefront Mega Menus: by WooThemes – 1.3.0
Storefront Product Hero: by WooThemes – 1.2.7
Storefront Sticky Add to Cart: by WooThemes – 1.1.4

WooCommerce Cart Add-Ons: by 75nineteen Media LLC – 1.5.11 – 1.5.12 is available
WooCommerce Checkout Add-Ons: by WooThemes / SkyVerge – 1.8.1 – 1.9.0 is available
WooCommerce Heidelpay Gateway: by Hinnerk Altenburg – 1.0.0
WooCommerce Germanized Pro: by Vendidero – 1.5.7
WooCommerce Germanized: by Vendidero – 1.7.0
WooCommerce Google Analytics Pro: by WooThemes / SkyVerge – 1.1.4.1 – 1.1.5 is available
WooCommerce Instagram: by WooThemes – 1.0.10
WooCommerce Recommendation Engine: by Lucas Stark – 3.1.1
WooCommerce: by WooThemes – 2.6.7
WordPress Importer: by wordpressdotorg – 0.6.3
Query Monitor: by John Blackbourn – 2.13.1
Remove woothemes' install notice: by Inpsyde GmbH – 1.0.2

MultilingualPress: by Inpsyde GmbH – 2.4.8
Elastic Facets: by Inpsyde GmbH – 1.0.0-alpha1
Rewrite Rules Inspector: by Daniel Bachhuber
Automattic – 1.2.1

Inpsyde Menu Cache: by Inpsyde GmbH
*****
***** – 1.0.0

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #7 - /
Cart: #8 - /****/
Checkout: #9 - /***/
My Account: #10 - /*****/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Little Storefront
Version: 2.5
Author URL:
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.0 – 2.1.6 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: my-theme/woocommerce/archive-product.php
my-theme/woocommerce/cart/cart-empty.php
my-theme/woocommerce/cart/cart.php
my-theme/woocommerce/content-product.php
my-theme/woocommerce/content-single-product.php
my-theme/woocommerce/emails/email-order-details.php
my-theme/woocommerce/emails/email-order-items.php
my-theme/woocommerce/emails/email-styles.php
my-theme/woocommerce/global/breadcrumb.php
my-theme/woocommerce/myaccount/dashboard.php
my-theme/woocommerce/order/order-details-item.php
my-theme/woocommerce/order/order-details.php
my-theme/woocommerce/single-product/product-image.php
my-theme/woocommerce/single-product/product-thumbnails.php
my-theme/woocommerce/single-product/related.php
my-theme/woocommerce/single-product/tabs/tabs.php
my-theme/woocommerce/single-product/up-sells.php
my-theme/woocommerce/single-product.php
```

If appreciated I would prepare a PR that:
 * Either remove the `@deprecated` annotation from `wc_load_persistent_cart` or create a new function, whatever you prefer. 
 * Create a counterpart to `wc_load_persistent_cart`: `wc_save_persistent_cart` (if nothing like that already exists, didn't look into that right now)
 * Implement both functions across `WC_Cart`
 * Provide a solution with suffixed (or prefixed) user meta keys with a backward compatible fall back to the existing meta key within these two functions.
 * Writing/Updating tests according to the necessary changes.

**Comment by mikejolley** [comment]
If this is just about the user meta, adding a suffix is all that's needed here? Why all the additional methods? I don't think saved carts are mission critical enough to warren BW compat handling either?

**Comment by dnaber-de** [comment]
In first place, it is all about the suffix of the meta key, yes. BW compat or not, I thought one could take the occasion to clean up the code a bit.

**Comment by mikejolley** [comment]
If the code is called in multiple places, but I don't think thats the case?

**Comment by mikejolley** [comment]
At this point we should just fix the issue by including the blog_id if possible.

**Comment by danielhuesken** [comment]
I think the wpdb prefix schould be used like other things in WordPress.

**Comment by dnaber-de** [comment]
Why the DB-Prefix? The site ID (blog ID) is the identifier for a site in the network.
This [hotfix plugin](https://github.com/inpsyde/woocommerce-multisite-persistent-cart) uses the meta key `_woocommerce_persistent_cart_<SITE_ID>` which is what Mike suggested if I understand him correctly.

**Comment by danielhuesken** [comment]
The DB-Prefix is different for every blog and includes the site ID. WordPress uses it itself for prefixing the rights user meta for example. IF there some migration scripts or similar they can find and handel this user meta easier.

**Comment by dnaber-de** [comment]
If you don't include the table prefix, you wouldn't need any migration script at all. Is there a situation where the site ID (formerly known as blog ID) might collide in some way with another?

**Comment by kovshenin** [comment]
Just a quick note, which is sort of related. The wc_fragments session/local storage key will persist across two different WooCommerce installs if they share the same domain name, probably in a subdirectory-mode Multisite install too.

For example a US store on example.org with US-centric products and USD as the currency, and example.org/canada with a different set of products and CAD. Adding something to the cart on the latter will then "leak" the minicart HTML to the former because both share `wc_fragments`.

A workaround, currently, is to create a unique name for `wc_fragments` using the `woocommerce_cart_fragment_name` filter.
