### ISSUE TITLE
WP REST API v1 - No Parent Property in 'Product Attribute Terms'

### ISSUE THREAD

**Issue by Qle63** [woocommerce/woocommerce#12530]
Using the Rest API to create Attribute Terms, its seems you can not set the parent as it is simply not available in the Attribute term properties.
please refer document: http://woocommerce.github.io/woocommerce-rest-api-docs/#product-attribute-terms (it does not show a parent property)

But, Using the Web WP-ADMIN tool the parent property **is** accessible!
(Using the API It is also visible in the 'List all attribute terms')

This was confirmed by Woocommerce general support, who recommend i post the issue here.

Best Regards
Lee.

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
It may be visible in admin, but it shouldn't be. Attribute do not support hierarchy.

**Comment by Qle63** [comment]
well thats that i guess.
Thank you very much for your prompt reply

Lee.
