### ISSUE TITLE
REST API and WP 4.7 problem type array

### ISSUE THREAD

**Issue by danielhuesken** [woocommerce/woocommerce#12532]
In WordPress 4.7 i think the validation of the rest api schema has changed. That is why now with WooCommerce 2.6 i get the error message:
`{"code":"rest_invalid_param","message":"Invalid` parameter(s): billing, shipping","data":{"status":400,"params":{"billing":"billing is not of type array.","shipping":"shipping is not of type array."}}}`

The definition as array https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-customers-controller.php#L679 is now that it must be a numberd indexed array!

I think that the type should be changed to 'object'. See http://json-schema.org/latest/json-schema-core.html#rfc.section.4.2

In moment i don't know if there more places where it must be changed.

**Comment by mikejolley** [comment]
I'm on it.

**Comment by mikejolley** [comment]
See and discuss in #12533
