### ISSUE TITLE
duplicate future posts

### ISSUE THREAD

**Issue by WGlenat** [woocommerce/woocommerce#12538]
## EXPLANATION OF THE ISSUE

When duplicate future posts, post_date is not  preserve

## STEPS TO REPRODUCE THE ISSUE

Create post width date in future 
clic planed
clic on "duplicate in new darft"
post_date is not preserve

i suggest this or add a hook

```
	public function duplicate_product( $post, $parent = 0, $post_status = '' ) {
		global $wpdb;

		$new_post_author    = wp_get_current_user();
		$new_post_date      = current_time( 'mysql' );
		$new_post_date_gmt  = get_gmt_from_date( $new_post_date );
		
		//if post is planed
		if ($post->post_status== 'future') {
				$new_post_date =$post->post_date;
				$new_post_date_gmt  = get_gmt_from_date( $new_post_date );
		}
...
```

## SYSTEM STATUS REPORT

`

**Comment by mikejolley** [comment]
This is not needed. When you duplicate to a new draft, the draft is not published. When you press publish, the post_date is replaced with the current date and time.

Future posts also have future status - your duplicate is again a draft, not a future post.

**Comment by WGlenat** [comment]
thanks for your quick return
you are right « Future posts also have future status - your duplicate is again a draft, not a future post. »

but with my code, my duplicate is a draft with a Scheduled date.

Then the draft button becomes « Schedule»  and not « publish » and then I can quickly schedule my article without changing the date again.

Maybe it is a specific need but it forces me to change the wordpress code with each update.

Matthieu Nicolas
www.glenat.com<http://www.glenat.com/>

De : Mike Jolley [mailto:notifications@github.com]
Envoyé : mercredi 7 décembre 2016 15:31
À : woocommerce/woocommerce <woocommerce@noreply.github.com>
Cc : Matthieu NICOLAS <Matthieu.NICOLAS@glenat.com>; Author <author@noreply.github.com>
Objet : Re: [woocommerce/woocommerce] duplicate future posts (#12538)


This is not needed. When you duplicate to a new draft, the draft is not published. When you press publish, the post_date is replaced with the current date and time.

Future posts also have future status - your duplicate is again a draft, not a future post.
