### ISSUE TITLE
Replace 0$ price with 'Free!' for free products

### ISSUE THREAD

**Issue by skmohammadi** [woocommerce/woocommerce#12531]
Hi. I know that Woocommerce must show '**Free!**' instead of **0$** for free products but this not work for me!
Maybe help me?

**Comment by mikejolley** [comment]
Version? Master does not.

**Comment by mikejolley** [comment]
FYI we're not going to show free as of 2.7 so prices are more consistent across product types. It can be added back with a small code snippet + filter.

**Comment by skmohammadi** [comment]
I am using woocommerce 2.6.4.

**Comment by mikejolley** [comment]
Then free is shown for you - unless you theme changes it :)

**Comment by skmohammadi** [comment]
But i sure that my theme is not do any changes.

**Comment by mikejolley** [comment]
Something must be, because it's working my side and there have been no other reports.
