### ISSUE TITLE
product price filter widget not display !

### ISSUE THREAD

**Issue by yasko88** [woocommerce/woocommerce#12537]
Hi,

There is a lot of topic on internet about that. And now my product filter widget not display, too.. I tried all plugin deactive except for woocommerce and different theme and delete all widget except for price filter widget but still not a solving and still no display. 
how can solve this problem ????? What is problem ?????
Because price filter widget and product category widget are best important widgets.
you can check www.fabrika-satis.com  ....

Thank you so much!
Have a nice day!

**Comment by mikejolley** [comment]
The new issue submission form lists things we need for a github issue to be raised, and has links to the forum you can use instead. This is not a support forum. The price filter widget is working on our test installs.
