### ISSUE TITLE
_usort_terms_by_ID is deprecated in WordPress 4.7

### ISSUE THREAD

**Issue by SunnyJohal** [woocommerce/woocommerce#12539]
## EXPLANATION OF THE ISSUE

The cart throws an error when wp debug log is enabled because of a deprecated function.

## STEPS TO REPRODUCE THE ISSUE

Enable WP_DEBUG and WP_DEBUG_LOG and add a product to the cart to see the error in the cart widget.

## HOW TO FIX

Replace line 231 `includes/wc-product-functions.php` from:

`usort( $terms, '_usort_terms_by_ID' ); // order by ID`

to:

`$terms = wp_list_sort( $terms, 'ID' );`

**Comment by mikejolley** [comment]
Please search :) https://github.com/woocommerce/woocommerce/issues/12525
