### ISSUE TITLE
API not working after update of WP + WC

### ISSUE THREAD

**Issue by dandersson79** [woocommerce/woocommerce#12548]
## EXPLANATION OF THE ISSUE

I can no longer access the API properly after updating my WordPress (to 4.7) and WooCommerce (to 2.6.9) this morning.
For every call I make to the API, I get an error back saying "rest_invalid_json". Normally I use a .NET wrapper for the API calls, so the answer I get seems a bit incomplete. I tried digging further by issuing a curl call from CLI and then I get an html-response saying "The document has moved":
<!DOCTYPE html>
<html>
<head><title>Found</title></head>
<body><p>The document has moved <a href="http://foodiemarket.be/wp-json/wc/v1/products/111">here</a></p></body>
</html>

The URL in the href above is the exact URL of the curl call I made.
When I do the same call on my testserver (with the same WC + WP versions and the same theme), it works just fine

I take it something has gone horribly wrong in my WP installation (I also had an inexplicable issue with a plugin this morning, which was resolved by updating the WP version, after which this issue appeared). I don't however know where to start looking. Any help would be much appreciated
## STEPS TO REPRODUCE THE ISSUE

Make a GET call to the API, eg retrieve orders or retrieve product
I can provide you with API keys for testing 

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://foodiemarket.be
Site URL: http://foodiemarket.be/wordpress
WC Version: 2.6.9
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.8-0ubuntu0.16.04.3
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.13
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.9
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (19) ###

Advanced Custom Fields PRO: door Elliot Condon – 5.3.9.2
Akismet: door Automattic – 3.2
bpost shipping: door Antidot – 2.2.1
Contact Form 7: door Takayuki Miyoshi – 4.5.1
Cookie Bar: door Brontobytes – 1.5
Duplicator: door LifeInTheGrid – 1.1.14
Faq CPT Foodiemarket: door Wubdesign – 1.2
FoodieMarket Producent: door Stefan de Groot – 1.0
Loco Translate: door Tim Whitlock – 2.0.9
Password Strength for WooCommerce: door Potent Plugins – 1.0.1
Post Duplicator: door Metaphor Creations – 2.17
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 2.2.6
Europabank MPI: door Europabank NV. – 1.0
WooCommerce Measurement Price Calculator: door WooThemes / SkyVerge – 3.8.1 – 3.10.1 is beschikbaar
WooCommerce: door WooThemes – 2.6.9
WordPress Database Reset: door Chris Berthe – 3.0.2
Yoast SEO: door Team Yoast – 3.7.1
WP-Mail-SMTP: door Callum Macdonald – 0.9.5
YITH WooCommerce Social Login: door Yithemes – 1.0.9

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Winkelbasis: #24 - /winkel/
Winkelmand: #25 - /winkelmand/
Afrekenen: #26 - /afrekenen/
Mijn account: #27 - /mijn-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Foodiemarket custom theme
Version: 1.2.0
Author URL: https://wubdesign.nl
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een subthema aan. Zie: Hoe maak je een subthema

WooCommerce Support: ✔

### Templates ###

Overrides: Jouw thema heeft een woocommerce.php bestand. Je zal het woocommerce/archive-product.php template niet kunnen overschrijven omdat woocommerce.php prioriteit heeft over archive-product.php. Dit is bedoeld om weergave-problemen te voorkomen.
Overrides: fm/woocommerce/archive-product.php
fm/woocommerce/cart/cart.php
fm/woocommerce/checkout/form-checkout.php
fm/woocommerce/content-product.php
fm/woocommerce/content-single-product.php
fm/woocommerce/global/quantity-input.php
fm/woocommerce/loop/add-to-cart.php
fm/woocommerce/loop/loop-start.php
fm/woocommerce/loop/orderby.php
fm/woocommerce/myaccount/form-login.php

**Comment by mikejolley** [comment]
Read here, it's the same issue. https://github.com/woocommerce/wc-api-php/issues/68#issuecomment-265740555

4.7.1 will have a workaround too.

**Comment by dandersson79** [comment]
Thanks for pointing that out to me!
