### ISSUE TITLE
Support for WP 4.7 Post Type Template

### ISSUE THREAD

**Issue by a3rev** [woocommerce/woocommerce#12544]
## EXPLANATION OF THE ISSUE

Have just look through the code for support for new WordPress 4.7.0 Post Type template. 

In fact I see here /woocomerce/includes/admin/class-wc-admin-meta-boxes.php at line 137

This code that removes the new Post Attribute Meta box?

remove_meta_box( 'pageparentdiv', 'product', 'side' );

Is there a reason for this that is not immediately obvious? It prevents theme developers from offering users a choice of product page templates on a product by product basis.

Can that be removed and released in the next update? Seems strange that it is a big feature of WP 4.7.0 but actively blocked in WC?

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Yes there is a reason; to stop the 'parent' select box being visible.

**Comment by a3rev** [comment]
Ok so that means it is not possible for theme developers to add template options for the product page? - we were excited about being able to add a "Splash Page' optional template that admin could select for certain products. 

But you are saying you won't allow  a core function of WordPress in WooCommerce?

Don't understand why that would be? Is there a technical reason or just your preference?

**Comment by mikejolley** [comment]
Core won't use it because it doesn't really have control over single page templates unless it's a real WC theme. @jameskoster preference?

This won't be supported until 2.7 anyhow. The other options in that meta box will need to be hidden some other way.

BTW just because of absence of that select box, doesn't mean you cannot set it through other means.

**Comment by a3rev** [comment]
Thanks for the feedback - have a few questions about that 

1. Will it be in WC 2.7 ?
2. When is the release date scheduled for that

Because if it is a while then we would 'make another means to show it' but if WC 2.7 is close then would wait.

Still not comfortable with the idea of having to make a hack to show something that is core WP because of WooCommerce code - would seem that something is not as it should be there ?

**Comment by jameskoster** [comment]
This is a pretty exciting feature, we should definitely allow theme developers to create page templates for products.

> The other options in that meta box will need to be hidden some other way.

Hopefully there's a simple way to do that?

**Comment by a3rev** [comment]
Can you add full support for Post Type template as a 2.7 milestone please?

**Comment by mikejolley** [comment]
@jameskoster What do you need? just reveal the box and hide other options?

**Comment by jameskoster** [comment]
That's all we need, yeah.

**Comment by mikejolley** [comment]
@jameskoster by default with a theme that does not support it, this is what we get:

https://dl.dropboxusercontent.com/s/ilszlexbrxg408x/2016-12-12%20at%2013.05.png

No great to have that at all times really. Can we detect theme support for it do you think? Or can we add it to advanced tab instead?

**Comment by a3rev** [comment]
I think it would be very good  UX if it was possible to show it by detecting theme support not so good if have to activate it on the Product Data meta for each product

**Comment by a3rev** [comment]
thank you @mikejolley
