### ISSUE TITLE
address-i18n.js causing address order problems for JP users

### ISSUE THREAD

**Issue by netplus** [woocommerce/woocommerce#12553]
address-i18n.js L45 ( Re-order postcode / city ) forces the postcode to come either before the city or after the state depending on 'postcode_before_city' locale setting.

For Japanese users the postcode should come before both the city and the state.
The order should be Postcode -> State -> City

However the JS makes this impossible without a core hack.

I would suggest moving any address re-ordering to occur in PHP before filters are applied so users have the chance to override.

**Comment by mikejolley** [comment]
> I would suggest moving any address re-ordering to occur in PHP before filters are applied so users have the chance to override.

This would stop the address fields changing after switching from Japan to US for example.

**Comment by mikejolley** [comment]
See #12577
