### ISSUE TITLE
per_page attribute in product shortcodes ignored - always displays 5.

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#12557]
## EXPLANATION OF THE ISSUE

Add a shortcode, IE `recent_products` and specify a value for the `per_page` attribute.

## STEPS TO REPRODUCE THE ISSUE

Add `[recent_products per_page=7]`  to a page. Expect to see 7 products, see 5.

Latest WooCommerce + WordPress 4.7.

**Comment by mikejolley** [comment]
This is due to it being cached in a transient. Save a product to clear said cache. We can add the limit to the transient name in 2.7
