### ISSUE TITLE
Can we reopen issue#4072 ? Add Stars to Backend Edit Review Screen #4072

### ISSUE THREAD

**Issue by raykai** [woocommerce/woocommerce#12563]
Can we reopen issue https://github.com/woocommerce/woocommerce/issues/4072 ?
i cant seam to find an option to ask to reopen it.
https://github.com/woocommerce/woocommerce/issues/4072

It would seam that the edit comment stars on the backend was included in core, but @mikejolley removed it from one of the last versions. 

We are wandering if there an explanation as to why it was removed and if @claudiosanches or @mikejolley could add the code back.

**Comment by mikejolley** [comment]
I don't recall why it was removed, but maybe you can explain why it's needed vs posting a new comment via frontend anyway? Unless you're posting fake reviews 🤓

**Comment by raykai** [comment]
to start with customers have no way to edit their own star reviews ones they posted.
some people changes their mind for product reviews for better or worse after some time.

i have some ppl that ask me to chang there star ratings and well i cant as we have no option to edit it.

Tho have the power to edit everything in woocomers but the stars ratings... 

Do admins only edit comments just to post fake comments reviews ?

No but seriously why not just add it back ?

**Comment by alaric1** [comment]
I would need the edit star review as i used it some times too as my customers requested to change the ratings that they did.

so as @raykai say this option was useful.

**Comment by mikejolley** [comment]
> to start with customers have no way to edit their own star reviews ones they posted.
some people changes their mind for product reviews for better or worse after some time. 

Comments cannot be edited in WP. So allowing this doesn't make sense in our case. I'll look at adding the panel back.

**Comment by OpNop** [comment]
Glad to see this getting added back in. Just to give a real use case for this. Its nice to see the rating before making it public so that if there is a bad review you can contact the customer and try to resolve the issue and see if they want to change their review.

**Comment by dax702** [comment]
Comments (reviews) on products can be edited, but I don't see a way to add/edit the star rating of a product review. Is this possible?

**Comment by andrewsum** [comment]
It's not possible in the back end at present.

If it's important for you in the immediate future, you can always edit the database directly if you know what you're doing.

If the review is lacking a star rating entirely, then you just need to insert a line into the wp_commentmeta table for it.

You'll need to find the relevant comment_id from the wp_comments but this is straightforward enough.
