### ISSUE TITLE
[2.6/2.7] Variation attribute value constraints not honored by script

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#12565]
### EXPLANATION OF THE ISSUE

The logic of the current variations script does not work correctly with multiple dependent attributes.

As discussed in https://github.com/woocommerce/woocommerce/issues/12487, a properly working "locking" UX should work as follows when changing an attribute value:

- Iterate all attributes.
- When updating the options of the n-th attribute, calculate the matched variations based on all attributes **preceding and following** n, excluding n.

In other words, the constraints of the n-th attribute **should be shaped by the values of all attributes other than n**.

Currently, the script calculates the matched variations for all attributes and then uses the result to update the state of all attributes, which results in errors.

Additionally, the state of attributes in the DOM is currently updated when focusing, which means that the DOM state is not consistent with the current configuration.

### STEPS TO REPRODUCE THE ISSUE

- Create the following attributes:

![image 2016-12-10 at 4 20 22 pm](https://cloud.githubusercontent.com/assets/1783726/21073915/9b05cc42-bef4-11e6-976c-5fb9d9889782.png)

- Define the following attribute dependencies using variations, and make sure that the default combination is A1-B1-C1:

![image 2016-12-10 at 4 21 21 pm](https://cloud.githubusercontent.com/assets/1783726/21073920/b5d76fb2-bef4-11e6-9a13-3be8cb814c80.png)

- Fire up the script. Notice that:

a) Attributes are not initially rendered in the DOM due to a logical flaw around https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js#L291 (if all variation attributes are selected, `update_variation_values` is not triggered.

b) Once the attributes are reset (by choosing an invalid combination or clicking Clear), the constraints that result from variation definitions are not honored: i) Choosing a value in **Attribute A** "locks up" the selection while it shouldn't and ii) The same is observed later when **Attribute A** is reset and a value is chosen in **Attribute B**.

https://cl.ly/0M1Z1d2Q421n

### PROPOSED SOLUTION

- Refresh the DOM every time a new selection is made. Do not touch the DOM on focusin/touchstart.
- Always refresh the DOM, no matter how many attributes are "non-empty".
- Revise the `update_variation_values` handler to correctly calculate matching variations for each attribute.

PR incoming.

**Comment by mikejolley** [comment]
This is a #wontfix for 2.6 due to the nature of the script.

Let's close in favour of #12566 and work on the solution there - there are 3 threads going on about the same thing. What you've done looks good at first glance but needs a full audit.
