### ISSUE TITLE
Certain Hosting Configs Allow Deleting Post Meta Upon Publishing a Variable Product

### ISSUE THREAD

**Issue by BFTrick** [woocommerce/woocommerce#12561]
## EXPLANATION OF THE ISSUE

On one of my test sites when I publish a new variable product it deletes post meta (including order details such as shipping address & order total).

Video: https://www.youtube.com/watch?v=lMMwWjiFZyI

I'm sure this isn't a wide spread issue. I've tried reproducing it on my local test site and I can't. So it's likely dependent on some hosting configuration or maybe a setting within WooCommerce.

I'm using the latest stable version of WooCommerce & Twenty Sixteen.

I've already reached out to WPEngine (ticket number: 785578) and they ruled out caching.

> I thought it might have been object caching but i'm not seeing the file in the staging site so it wasn't that
I'm not sure what is causing that to happen when you save the product as draft or when you publish	
I created another product and enabled the debug log to see what shows there.	
the only thing that shows there is the purge varnish cache failing.
This will automatically fail because this is the staging site.	
I've also checked the woocommerce articles but haven't found what this could be.

I have no idea what sort of settings (either in WooCommerce or hosting settings) could be causing this. I assume since post meta is being deleted that it is something that can be prevented WordPress side.

## STEPS TO REPRODUCE THE ISSUE

1. Create new variable product
1. Create at least two attributes
1. Save attributes
3. Create two variations
4. Save variations
5. Publish product
6. Order meta destroyed. :(

![orders](https://cloud.githubusercontent.com/assets/1065372/21062798/ad3025d8-be0f-11e6-87ad-78c49274ef12.jpg)

I'm happy to give site creds for testing if you want to DM on Twitter / WooCommerce Slack / WordPress Slack.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: **removed**
Site URL: **removed**
WC Version: 2.6.9
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.20 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.9
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.9

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #11 - /shop/
Cart: #47 - /cart/
Checkout: #52 - /pay/
My Account: #48 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by mikejolley** [comment]
Can you check your database structure and ensure all the meta tables have auto increment ID columns?

**Comment by roadwarriorwp** [comment]
@mikejolley - just checked the database.  I'm not sure that every single table does.  There are ~65 tables.  I looked quickly at wp_posts and wp_postmeta.  wp_posts has an id that is auto increment, but the meta_id in the postmeta table doesn't say auto increment.  Could this be the problem?

**Comment by BFTrick** [comment]
Just confirmed that the columns for the postmeta table are not set to auto-increment.

(You would see `AUTO_INCREMENT` under `Extra` if it were enabled)

![phpmyadmin_wpengine_com___wp_engine___snapshot_hpspiceco___wp_postmeta___phpmyadmin_4_6_5_2](https://cloud.githubusercontent.com/assets/1065372/21081787/3a2cf0de-bf8b-11e6-88a2-727f11ae2d4f.jpg)

So `meta_id` should be set to auto-increment?

**Comment by mikejolley** [comment]
Yes sir. WC wouldn't change this table, it's core WordPress :) Installation fault?

**Comment by BFTrick** [comment]
I just wanted to update this issue so anyone else who has this issue have a bit of information to fix the problem.

As per the screenshot above I found a few tables that didn't have a primary key nor a column that had auto-increment.

## Solution

1. Find all of the tables that don't have a primary key or auto increment.
1. First add a primary key to the table (you'll need to do this to add auto increment)
1. Add auto-increment to the table

Now one of the hiccups is that you can't add a primary key if there's already duplicate entries in the primary key column. Meaning if there are two entries with the `meta_id` set to `0`. You can't add a primary key.

I exported ALL of the duplicate entries. The vast majority had a value of 0 so they were easy to find.

Then after adding auto-increment I added all of the entries back in with a SQL statement. This way they auto incremented correctly and I kept all of my data.

I recommend disabling your store, do all of this on a test site, confirm it works, update the database for the live site, and finally reenable your store.

It took me 2.5 hours to figure this out, make backups, get _all_ of the data out, make the changes, reimport the data, and then make the site live again.

**Comment by mikejolley** [comment]
@BFTrick you have any idea what caused it?

**Comment by BFTrick** [comment]
This site was imported from another host - I won't mention them by name - but they were one of those bargain hosts. It's likely this somehow happened during the migration.

So if you do a migration make sure you check your primary keys afterwards and you can save your self a lot of debugging.

**Comment by mikejolley** [comment]
Well, you get what you pay for eh :D
