### ISSUE TITLE
Variations not displaying when name has a capital letter

### ISSUE THREAD

**Issue by tigerstrikemedia** [woocommerce/woocommerce#12564]
## EXPLANATION OF THE ISSUE

WC version 2.6.9

When a product attribute has a name with a capital letter (EG 'White') line 388 of add-to-cart-variations.js is looking for the option that has a value of `White`, when the option value is actually `white`

`current_attr_select.find( 'option[value="' + attr_val + '"]' ).addClass( 'attached ' + variation_active );`

This causing the option to be missed as attached and stripped out later in the code when there is a valid variation.

**Comment by mikejolley** [comment]
Are you sure that this isn't theme related? Custom attributes are not made lowercase afaik and it's working for me locally.

**Comment by tigerstrikemedia** [comment]
@mikejolley 

Just reverted back to twentyseventeen in a local install, same issue.
![screen shot 2016-12-10 at 10 23 40 pm](https://cloud.githubusercontent.com/assets/1908481/21073487/608667a6-bf27-11e6-86ea-dad554debfae.jpg)

**Comment by tigerstrikemedia** [comment]
@mikejolley 

Actually after messing with and re-saving the variations they are saved, displayed and behave correctly, I will do some more investigation in the morning.

Cheers
Ben

**Comment by tigerstrikemedia** [comment]
@mikejolley 

Turns out the theme was using sanitise_title, which lowercase's the string.... Problem solvered. Ticket closing....
