### ISSUE TITLE
Skip Single Product Site

### ISSUE THREAD

**Issue by marcsuuuup** [woocommerce/woocommerce#12562]
## EXPLANATION OF THE ISSUE
Hey there,

i am trying to skip the single product site in my woocommerce store. When the visitor clicks on the product picture in the product archive loop, I want directly the “product picture pop up” showing up instead of leaving the loop site and going to the single product site. I didn’t find a solution yet and need urguntly a good advice. Any ideas?

Thanks and best regards!

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by marcsuuuup** [comment]
Maybe to clearify it a bit: Going from the loop (pic 1) directly to the piv overlay (pic 2):

[https://s27.postimg.org/3lnhbcsyb/loop.jpg](url)
[https://s27.postimg.org/51yzthvv5/prettyphoto.jpg](url)

**Comment by mikejolley** [comment]
Core does not support this out of the box. You'd need to customise your template files heavily to include lightboxes there instead of single product pages. I don't have code snippets handy to do this for you..
