### ISSUE TITLE
Hierarchy support for product attributes for brand/product (make/model) relationships

### ISSUE THREAD

**Issue by stl99** [woocommerce/woocommerce#12571]
It would be great to have hierarchy support for product attributes. The main benefit would be the ability to provide a layered navigation filter for brand-product (make-model) relationships.

Example:

Brand I
– Brand I car model
— Brand I car model specific version
— …
Brand II
– Brand II car model
— Brand II car model specific version
— …

Cheers,
Thomas

**Comment by mikejolley** [comment]
Product attributes are used for things like variable products where hierarchy would not make sense. Really, your best bet is categories which fit this structure better, and still have archives you can narrow down to a version.

**Comment by stl99** [comment]
I see, makes sense. Maybe there's room for a third type though? Depending on the product type (cars, bikes, tools etc) the category could inflate enormously. I just bought the brand extension, cloning or extending that to work for different types of data (e.g. via being able to set a custom title, slug, widget setting etc.) might be a feasible solution... I know that others have requested hierarchical attributes (or something similar) in the past too...

**Comment by mikejolley** [comment]
If you did need a new custom taxonomy, you could register it.

**Comment by stl99** [comment]
I will use a regular product attribute for the model filter now but - without hierarchy - this will become rather crowded at some point. Also, it won't enable users to (easily) filter either by make, model and/or specific model version (e.g. "BMW", "3 Series", "3 Series 320i" "3 Series 320i Sedan" )

Make/model is a rather common use case when it comes to products (especially vehicles like cars, bikes and bicycles) so I hope you reconsider adding something in that aspect at some point. Being able to use the product_cat widget for any custom taxonomy (for facetted search) would be nice too.

**Comment by nikolaimikkelsen** [comment]
By modifying the woocommerce code and setting Edit /wp-content/plugins/woocommerce/includes/class-wc-post-types.php line 214 from "false" to "true" you can achieve what you are looking to do. Then use Thomas Depole's wordpress-child-plugin-tool to make a child of the woocommerce plugin so in the event of an update it does not get overwritten. 

I am using the above in conjunction with WOOF filter to create a hierarchy of attributes as the way that I require filtering to work will not work with categories. I can get in to it more but it appears it is the only way that I can achieve what I need. 

Links below for references.

https://stackoverflow.com/questions/44271444/woocommerce-product-attributes-with-hierarchy-like-categories

https://github.com/ThomasDepole/wordpress-child-plugin-tool#updating-the-parent-plugin

**Comment by ingramleedy** [comment]
> By modifying the woocommerce code and setting Edit /wp-content/plugins/woocommerce/includes/class-wc-post-types.php line 214 from "false" to "true" you can achieve what you are looking to do. Then use Thomas Depole's wordpress-child-plugin-tool to make a child of the woocommerce plugin so in the event of an update it does not get overwritten.

> Links below for references.
> 
> https://stackoverflow.com/questions/44271444/woocommerce-product-attributes-with-hierarchy-like-categories

I made these changes, but I didn't see any changes, should the Attributes page have an interface to add/change parent?

**Comment by nikolaimikkelsen** [comment]
You need to create an attribute, then create terms. The terms can the be set as a child of another term. So the top level attribute needs to be created first. You should see under the edit terms the ability to assign a new one to a parent or if you edit one of your terms.

![parent](https://user-images.githubusercontent.com/60589783/106497435-a6fca280-6483-11eb-92b1-d76a1ab23618.JPG)

**Comment by khiloc** [comment]
don't know if this fit but i found this plugin who have now a feature that allow to enable attributes hierarchy support right from woocommerce without touching a line of code

https://woocommercebulkattributes.com/

**Comment by iamabhishekgarg** [comment]
> You need to create an attribute, then create terms. The terms can the be set as a child of another term. So the top level attribute needs to be created first. You should see under the edit terms the ability to assign a new one to a parent or if you edit one of your terms.
> 
> ![parent](https://user-images.githubusercontent.com/60589783/106497435-a6fca280-6483-11eb-92b1-d76a1ab23618.JPG)

plz help how to make parents for attributes

**Comment by milad-jfr** [comment]
> By modifying the woocommerce code and setting Edit /wp-content/plugins/woocommerce/includes/class-wc-post-types.php line 214 from "false" to "true" you can achieve what you are looking to do. Then use Thomas Depole's wordpress-child-plugin-tool to make a child of the woocommerce plugin so in the event of an update it does not get overwritten.
> 
> I am using the above in conjunction with WOOF filter to create a hierarchy of attributes as the way that I require filtering to work will not work with categories. I can get in to it more but it appears it is the only way that I can achieve what I need.
> 
> Links below for references.
> 
> https://stackoverflow.com/questions/44271444/woocommerce-product-attributes-with-hierarchy-like-categories
> 
> https://github.com/ThomasDepole/wordpress-child-plugin-tool#updating-the-parent-plugin

Thank You ,
 This solution is working but if you don't want to edit the plugin directly and be not worry about losing the edits when comes to update the wocommerce ( remove second step ( Plugin Child Tool ) you can simply use code below as an Snippet :

```
function so44271444_woocommerce_taxonomy_args_pa_color ($data)
{
    $data['hierarchical'] = true;

    return $data;
}

add_filter('woocommerce_taxonomy_args_pa_color', 'so44271444_woocommerce_taxonomy_args_pa_color');
```


This code comes from [Stackoverflow](https://stackoverflow.com/questions/44271444/woocommerce-product-attributes-with-hierarchy-like-categories)

So in this way edits does not disappear during WOOCOMMERCE update and also the other benefit is that you can apply it just to specific attribute

as you see on the code you must point to the specific attribute to make the code work ,
in the above example the attribute is "pa_color",
you must change this with you own attribute in all the code.
and for their not know how get this attribute name just go to attribute page and see the attribute link
