### ISSUE TITLE
add variable to url by selecting variation from drop down

### ISSUE THREAD

**Issue by MMaKenZi** [woocommerce/woocommerce#12576]
Is it possible, or is already any function present which can add variation slug to url lively after we select any variation from drop down menu of a variable product?

===================================
for example:
Product name: 
Phone

Product Variations(color):
Blue
Red

Product URL:
http://www.example.com/product/phone
===================================
and when I select Variation Blue the url changes automatically to:
http://www.example.com/product/phone/blue
or 
http://www.example.com/product/phone/?pa_color=blue

so is this possible?

**Comment by mikejolley** [comment]
Not as it stands. I think you'd have to get data about the selected variation id to do this via ajax, or insert it as part of the variation data on the screen. We only use these variation URLs from the cart page.

Possible with custom code I'm sure.

**Comment by jeffceriello** [comment]
Hi, could you please explain how to do that via ajax or by inserting it as part of the variation data on the screen?

Thanks

**Comment by dbieling** [comment]
@jeffceriello Did you find a solution to your problem. I am searching for the same function.

**Comment by benrich** [comment]
I've done limited testing but...

```
const onAttributeChange = function () {
	if ('URLSearchParams' in window) {
		const searchParams = new URLSearchParams(window.location.search)
		const param = $(this).attr('name')
		const value = $(this).val()

		searchParams.set(param, value)

		const newRelativePathQuery = window.location.pathname + '?' + searchParams.toString() + window.location.hash
		history.replaceState(null, '', newRelativePathQuery)
	}
}

$('.variations [name^=attribute_pa]').on('change', onAttributeChange)
```

inspired by https://stackoverflow.com/a/41542008/1283640

Note: I changed history.pushState() to history.replaceState().  Otherwise the history (back/forward buttons) records an instance for each time a variation changes.  That doesn't feel like great UX.
