### ISSUE TITLE
Selecting a default attribute prevents other attributes showing in the dropdown

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#12582]
Create a variable product with 2 attributes. Link all variations/set prices etc.

Now set 1 default attribute.

Go to frontend, try to change the pre-selected value. You cannot unless you clear first.

https://wordpress.org/support/topic/unable-to-select-size-variation/

**Comment by franticpsyx** [comment]
Described in https://github.com/woocommerce/woocommerce/issues/12565 - should be resolved in https://github.com/woocommerce/woocommerce/pull/12566

**Comment by mikejolley** [comment]
@franticpsyx this did not used to happen. Your patch is a bit large for a fix release..

**Comment by franticpsyx** [comment]
@mikejolley Hmmm, not sure when it broke exactly (probably after the AJAX refactor?) but if you look at the code it is easy to see why this is happening. #12565 describes the cause so it might be useful anyway. 

I remember the script used to recalculate the matching variations when re-rendering attributes, but it was unnecessarily passing `exclude` and `focus` params, while the right thing to do IMO would be to simply re-render the attributes on change, not on focus (as in the fix).

**Comment by mikejolley** [comment]
@franticpsyx it broke since 2.6.8

**Comment by mikejolley** [comment]
From here I think https://github.com/woocommerce/woocommerce/commit/b279727bca0a95847900d61bd7f87597dbaa087b

**Comment by mikejolley** [comment]
Proposed fix in #12585
