### ISSUE TITLE
Unclear product postmeta schema

### ISSUE THREAD

**Issue by dorkster100** [woocommerce/woocommerce#12581]
## EXPLANATION OF THE ISSUE
Hello!
I built a plugin that uses SHORTINIT constant for ajax calls. The perfomance for my ajax calls was a real issue, so we decided to use a custom query  without loading wp core and any plugins to get information about the products that we need. The ajax call works fine ALMOST for every product, however there seem to be some products that do not have some post meta fields set. I was trying to search in the documentation for information regarding these fields but to no avail. For example i have a variable product with multiple variations, but no _min_price_variation_id postmeta is set.  Also as i saw many of the post meta fields are not used anymore, is it possible to get the list of the currently used post meta fields or at least some file that i could refer to.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L21 Or export an product via Tools > Export and look at meta.
