### ISSUE TITLE
Confusion around the sale price option for bulk edit.

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#12586]
Step 1) Don't previously have sale prices set for a couple products.
Step 2) Select and bulk edit them.
Step 3) See the "Decrease by (fixed amount or %)" option for sale price. Both myself and a user assumed that this would set the sale price to a certain % of the regular price. Nope, you have to select the "Decrease regular price" option.

I have two issues with this. The "Decrease regular price" option is a bit confusing. You are not decreasing the regular price. You are setting a sale price BASED on the regular price. The second issue is, if you have no sale price set, the first option does nothing.

Can we clear up the language around these to make it clearer?

**Comment by mikejolley** [comment]
See #12599
