### ISSUE TITLE
Check cart coupons shows incorrect error message

### ISSUE THREAD

**Issue by DavidBrunow** [woocommerce/woocommerce#12584]
## EXPLANATION OF THE ISSUE

After applying a coupon that does not affect any of the products in the cart and going to the checkout page, the error message "Sorry, it seems the coupon "COUPON_CODE" is invalid - it has now been removed from your order." is shown when the message should be "Sorry, this coupon is not applicable to your cart contents.". The message that is shown is hardcoded and doesn't change based upon the error generated in $coupon->is_valid().

## STEPS TO REPRODUCE THE ISSUE

1. Add a coupon to the cart on a page other than checkout
2. Only add products that that coupon does not apply to on a page other than checkout
3. Go to the checkout page
4. See the "Sorry, it seems the coupon "COUPON_CODE" is invalid - it has now been removed from your order." error message displayed

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: LOCAL ENVIRONMENT
Site URL: LOCAL ENVIRONMENT
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.12 PHP/5.6.27 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 5.6.27
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.50.3
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #80566 - /shop/
Cart: #80568 - /checkout/
Checkout: #80568 - /checkout/
My Account: #80569 - /my-account/

### Taxonomies ###

Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### IRRELEVANT/SENSITIVE INFORMATION REMOVED ###
`
```

**Comment by mikejolley** [comment]
> ### IRRELEVANT/SENSITIVE INFORMATION REMOVED ###

How do you know it's irrelevant? The plugins section is pretty relevant...

With a cart coupon with product usage restriction named coupon_code, you cannot apply it in cart. 

![2016-12-13 at 17 50](https://cloud.githubusercontent.com/assets/90977/21152063/b85b4dac-c15c-11e6-9873-37385f97a9ac.png)

Same for product coupons. 

_Coupons with usage restriction cannot be applied from the cart page unless applicable._

If you edited a coupon after being applied and went to checkout, yes you're see that message because it's being removed, not applied. There is a different message shown when a coupon get removed. Doesn't look like a bug.

**Comment by DavidBrunow** [comment]
Those details are not relevant when the code shows a hardcoded value:

```
/**
 * Check cart coupons for errors.
 */
public function check_cart_coupons() {
	foreach ( $this->applied_coupons as $code ) {
		$coupon = new WC_Coupon( $code );

		if ( ! $coupon->is_valid() ) {
			// Error message
			$coupon->add_coupon_message( WC_Coupon::E_WC_COUPON_INVALID_REMOVED );

			// Remove the coupon
			$this->remove_coupon( $code );

			// Flag totals for refresh
			WC()->session->set( 'refresh_totals', true );
		}
	}
}
```

Our workflow is probably different than what you expect – the user is able to add a coupon before adding any products so the validation doesn't happen until the user gets to checkout.

**Comment by mikejolley** [comment]
If you're applying a coupon in your own special way, then yes, you will see a different notice. Stating this would have been relevant because it would be impossible to replicate with core only..

When checkout validation kicks in it's job is to remove anything invalid and show whatever message E_WC_COUPON_INVALID_REMOVED is. It has it's own error code so you can see this was intentional.

**Comment by mikejolley** [comment]
I wonder if the wording of the other notices would make less sense at this point too since they are applied already in your case...

**Comment by DavidBrunow** [comment]
My current fix to display the message I need to display, which involves changing the `WC_Cart` class which I know is very bad, is to set the error code on the coupon when validation fails (in addition to the error message which is currently being set on the coupon) and use that error code to display the relevant message. 

I don't know of a great way of doing this without changing the `WC_Cart` class – maybe I could clear all coupon messages and perform the validation manually.

Here is how I'm handling in case it is helpful to considering the issue:

`class-wc-cart.php line 42`
```
/**
 * Check cart coupons for errors.
 */
public function check_cart_coupons() {
    foreach ( $this->applied_coupons as $code ) {
        $coupon = new WC_Coupon( $code );

        if ( ! $coupon->is_valid() ) {
            // Error message
            $coupon->add_coupon_message( $coupon->get_error_code() );

            // Remove the coupon
            $this->remove_coupon( $code );

            // Flag totals for refresh
            WC()->session->set( 'refresh_totals', true );
        }
    }
}
```

`class-wc-coupon.php line 598`
```
/**
 * Check if a coupon is valid.
 *
 * @return boolean validity
 * @throws Exception
 */
public function is_valid() {
    try {
        $this->validate_exists();
        $this->validate_usage_limit();
        $this->validate_user_usage_limit();
        $this->validate_expiry_date();
        $this->validate_minimum_amount();
        $this->validate_maximum_amount();
        $this->validate_product_ids();
        $this->validate_product_categories();
        $this->validate_sale_items();
        $this->validate_excluded_items();
        $this->validate_cart_excluded_items();

        if ( ! apply_filters( 'woocommerce_coupon_is_valid', true, $this ) ) {
            throw new Exception( self::E_WC_COUPON_INVALID_FILTERED );
        }
    } catch ( Exception $e ) {
        $this->error_message = $this->get_coupon_error( $e->getMessage() );
        $this->error_code = $e->getMessage();
        return false;
    }

    return true;
}
```

Thanks for your time in discussing this.

**Comment by mikejolley** [comment]
check_cart_coupons is something we hook in - you could hook in a function earlier to do the removal + messages and then you would not need to override classes?

**Comment by DavidBrunow** [comment]
I'll go down that path. Thanks for the help and sorry for making this into a support ticket.
