### ISSUE TITLE
Add support for lead time.

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#12596]
Hello,
In some cases the item the customer is buying is not in Stock.
In such case there should be an option to indicate the lead time on the product page.
It should also allow to choose the lead time measurements (days,weeks,months)

meaning there should be an integer value and a measurement value.
The customer should see : 4 Days, 3 Weeks  etc..

This information should be also in the emails that are sent to the customer. This is part of the product definition.

Please allow this feature.

**Comment by mikejolley** [comment]
I don't see much (any) demand for this on http://ideas.woocommerce.com/forums/133476-woocommerce?query=lead%20time - you can log it there though.

I wonder if this is similar and can be part of https://github.com/woocommerce/woocommerce/issues/11259 when we look at that.

For now you can add your lead times to the short description and/or a custom field to display on your pages. I don't think that would be overly complex.

**Comment by UserName011** [comment]
@mikejolley  For me the lead time isn't just a text to shown to the customer.
I draw information from the WooCommerce database to my other systems.
I need a way to be able to set the lead time in WooCommerce and retrieve it.

Lets try to look at this from a wider angle..
Is it possible to allow to define more parameters per product and choose if these parameters will be visible in the product page?

**Comment by mikejolley** [comment]
> I draw information from the WooCommerce database to my other systems.

Then a core solution won't help anyway? Add some code to query it to your product templates.

**Comment by UserName011** [comment]
@mikejolley 
Why it won't help?
If you define property then I can draw the information easily.
What I'm asking for seems simple to me (correct me if i'm wrong)
Like any product have Price property, any product can have Lead Time property.
It's just a small property it doesn't effect anything.

It's only adding a row to wp_woocommerce_order_itemmeta  with meta_key leadtime and meta value which ever the store defines, and present it in dashboard and product page (present in product page only if meta value >0.

Am I wrong?

**Comment by mikejolley** [comment]
Use a custom field IMO. Then you can draw it elsewhere from meta, and output it to your template files wherever. 

https://github.com/woocommerce/woocommerce/issues/11259 is similar to what you're asking for here so thats planned for the future.

**Comment by UserName011** [comment]
@mikejolley it's not the same as this apply for cases where stock management is active.
In my case it's not active. There is no stock, the product is manufacture per demand.

If I understood you this is what I need:
http://www.remicorson.com/mastering-woocommerce-products-custom-fields/

I think it would be valuable if it 'Lead Time' would be integrated in WooCommerce itself. This is something that is well known for merchants and often being used (even if no one has asked for it before).  Considering the simplicity of this feature I hope that it would be integrated with the following releases. 

Please reconsider.

**Comment by mikejolley** [comment]
Why not add it to the ideas board? There is no demand for this feature right now (just you) so it doesn't really make sense to prioritise it above other requests :)

**Comment by UserName011** [comment]
@mikejolley Already added but I don't think many store owners know how to address feature request.
I understand the idea of developing high demands features however what I'm asking for is very small and doesn't require much time.  I guarantee that if you will ask store owners about lead time function most of them will tell you it's a needed functionality.

I don't request to priorities it over other tasks just want to see it on the to do list... Even if it will be for 3.0 version. At the moment it doesn't seem like you think this is a good idea and on the other hand this thing is too small for a separated add-on... that's why I urge you to reconsider.

I think this is a very good first feature for new developer who is looking to contribute to WooCommerce project. If I was a PHP developer I would have done it myself.  Maybe you should allow this to go on the to do list and just leave it for new developer?

**Comment by mikejolley** [comment]
If it's on the ideas board, it has visibility. Any dev can see those. I disagree that it's a small quick task as you insinuate though. It's also niche.

**Comment by UserName011** [comment]
@corsonr  Is it possible that you will implement your code for a lead time field per product? http://www.remicorson.com/mastering-woocommerce-products-custom-fields/

**Comment by corsonr** [comment]
@UserName011 you can create custom fields as explained at the end of my post. If you combine the creation of a custom field with jQuery UI you should be able to parse the field result to get time and date using one single field.

**Comment by UserName011** [comment]
@corsonr  Lead Time isn't just a caprice. It is an important value for merchants. I assume that many WooCommerce store simply sell "On Shelf Stock" But that is not always the case.
Any plugin that wants to allow any kind of store to use it must have this feature build in.

I still think that this property should be implemented in WooCommrce itself and not by any user who needs it. This is a core concept for merchants.

**Comment by corsonr** [comment]
Hey @UserName011, I think that for now the best way to proceed is to create the field using the method provided in my tutorial and in the future we will monitor this idea here http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/17427502-lead-time-for-non-stock-product and we'll see how popular it gets.

**Comment by UserName011** [comment]
@corsonr as you wish. This won't get popular as many of woocommerce users are actually unaware of this idea panel.

If you want to know how popular this is you should read about it...
http://blog.teikametrics.com/2012/09/how-important-is-lead-time.html#
This is an article that compares stores software based on many parameters (including lead time)
https://www.nchannel.com/blog/real-time-inventory-availability/

I can find many more...

As I said any merchant that sells items which are not in stock need this option. Maybe (just a thought) you won't see many votes as the merchants who needs it didn't choose WooCommerce as you don't have this option.

**Comment by Joseffb** [comment]
I think I'll make a plugin for this.

**Comment by UserName011** [comment]
@Joseffb Excellent!

**Comment by UserName011** [comment]
@Joseffb Hi, any news?

**Comment by Joseffb** [comment]
It's pretty simple to add the new fields question is then what?

Feel free to reach out to me on gmail at joseffb78 to discuss exactly what's intended.

**Comment by tthomas1consultant** [comment]
MikeJolly There is a demand for this. not all products are walmart t-shirts. As manufactures of high ticket items which are made on demand (think riding lawn mowers, cars, custom made clothing..) we need to show an item available but with a lead time of x days. ideally this is something we like added at cart level. I have seen it on large retailer sites but as a small business we do not have budget for custom design or its maintenance.

**Comment by mikejolley** [comment]
Please use the ideas board then - ideas.woocommerce.com. If there is demand, it could be looked at.

**Comment by UserName011** [comment]
@mikejolley  @Joseffb  there is demand:
http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/17427502-lead-time-for-non-stock-product

many users ask for it, and everyone claims it's simple to implement...

**Comment by alexdenning** [comment]
Hi all, if you're still looking for a solution to this then [WooCommerce Lead Time](https://barn2.co.uk/wordpress-plugins/woocommerce-lead-time/) by Barn2 can do this  nicely.
