### ISSUE TITLE
API Order Create/Update webhook line items should return variant id as well as product id

### ISSUE THREAD

**Issue by achadee** [woocommerce/woocommerce#12592]
Currently we have to do an extra query to determine if the line item is a variant or product. Some of our customers have absolute Potatos for their wordpress instances, meaning that orders coming into our system can take up to a few seconds rather than instantly process.

**Comment by achadee** [comment]
also maybe call it parent_product_id to avoid breaking current webhooks

**Comment by mikejolley** [comment]
2.7 will allow you to switch webhooks to our new API rather than the legacy API. The new API includes both fields http://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties
