### ISSUE TITLE
Product Webhook variant attributes name is returning the slug instead of the name on global attributes

### ISSUE THREAD

**Issue by achadee** [woocommerce/woocommerce#12595]
When creating products in woocommerce using global attributes, the webhook response returns the slug as the "name" field on the variant attributes array

**Comment by mikejolley** [comment]
This is another which will be resolved in 2.7 and the new API for webhooks. Example response https://dl.dropboxusercontent.com/s/roh3lhy6q9k15bl/2016-12-14%20at%2011.51.png
