### ISSUE TITLE
Wrong calculation of order total due to a rounding bug

### ISSUE THREAD

**Issue by saschametz** [woocommerce/woocommerce#12607]
## EXPLANATION OF THE ISSUE

If you enter your net prices with 3 decimals WooCommerce calculates in some cases the wrong order total.

42,44 + 2,35 is **44,79**
WooCommerce says it's **44,78**

So the customers pays 1 cent less. If you have 10.000 orders this is already 100€ loss.

### Cart:
![1](https://cloud.githubusercontent.com/assets/23498536/21224124/da5ef2fe-c2ca-11e6-8e19-f6b9fb927b44.png)

### Order:
![2](https://cloud.githubusercontent.com/assets/23498536/21224125/da5f10f4-c2ca-11e6-96c9-819d03994e1b.png)

## STEPS TO REPRODUCE THE ISSUE

1. Tax Settings: "**No, I will enter prices exclusive of tax**"
2. Use **27%** for "Standard" Tax Rates
3. Create "Product 1" with Net Price **33,415**
4. Create "Product 2" with Net Price **1,848**
5. Buy both products together and you will see the bug immediately

## POSSIBLE CAUSE OF THE ERROR

I think this problem is caused by a rounding issue:

For example, if you add up the both product net prices:

Version 1:
`echo round(33.415, 2) + round(1.848, 2); => Result: 35.27`

Version 2:
`echo round(33.415 + 1.848, 2); => Result: 35.26`

**Comment by mikejolley** [comment]
> If you enter your net prices with 3 decimals WooCommerce calculates in some cases the wrong order total.

If you enter prices with 3 decimals, you need to display the prices with 3 decimals too, otherwise rounding will of course occur when it uses that decimal setting to round prices.

You cannot charge a user half cent, so don't define prices half cent IMO. I don't think we can fix this one without adding odd rounding rules which would of course look wrong to the end user who doesn't care how you input your prices.

**Comment by saschametz** [comment]
Thanks for the quick response and the explanation.
I don't think it's good that you ignore the problem and mark it as "Won't fix".

I'm not the only one using more than 2 decimals for the net prices and display only 2 decimals.

Here is an example why it's not possible to use 2 decimals in some cases:

VAT 19%
and I want the gross price 14,00

Net Price (2 decimals):
```
11,76 => 13,99
11,77 => 14,01
```

Net Price (3 decimals):
`11,764 => 14,00

**Comment by mikejolley** [comment]
Thats why we offer tax inclusive prices.

**Comment by saschametz** [comment]
I know this would fix the problem. But I wanted to draw attention to the problem, because I think both versions should work or the other solution - it shouldn't be possible to make this kind of mistake.

Maybe you could add a hint or limit the decimals with javascript when you enter the price. I can't imagine I'm the only one who didn't know that only 2 decimals places are allowed if you use the settings above.
