### ISSUE TITLE
No order notifications sent after order cancelled due to IPN delay

### ISSUE THREAD

**Issue by BHEADRICK** [woocommerce/woocommerce#12603]
A customer checked out via paypal. 

The order notes show "cancelled by user" at 9:56am and then "IPN payment completed" at 9:57, followed by an immediate "Order status changed from Cancelled to Processing."

But no emails regarding this order were ever sent out (I have an Email Log plugin installed so I know what emails are sent regardless of whether there's a problem in transit)

This occurred on 12/13/16, and at the time, we were on the latest Version 2.6.9. 

I've seen notes from mikejolley indicating that orders cancelled by the user cannot be updated, so I assume that's the reason for this problem, but I would suggest this business logic be reevaluated. 

Yes, I know that I can use PDT instead of IPN to avoid this situation and I intend to do this, but the simple fact is that this behavior serves no practical benefit, and it would make a lot more sense to either change your criteria of what is considered "user cancelled" so that an IPN delay is not included in that or simply allow the expected workflow to continue even if an order is cancelled. 

Note that I only installed woocommerce deposits after the incident took place.`

### WordPress Environment ###

Home URL: https://www.poolwarehouse.com
Site URL: https://www.poolwarehouse.com
WC Version: 2.6.9
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.1
PHP Version: 5.6.99-hhvm
PHP Post Max Size: 
PHP Time Limit: 0
PHP Max Input Vars: 
cURL Version: 7.40.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 0 B
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.9
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (73) ###

Gravity Forms: by rocketgenius – 2.1.1
Advanced Custom Fields: Repeater Field: by Elliot Condon – 1.1.1
Advanced Custom Fields: by Elliot Condon – 4.4.11
Advanced TinyMCE Configuration: by Andrew Ozz – 1.3
All In One WP Security: by Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.2.4

AMP: by Automattic – 0.4.2
Call Now Button: by Jerry Rietveld – 0.1.3
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

CMB2: by WebDevStudios – 2.2.3.1
Columns for Bootstrap: by CWRU
CAS IT Group – 1.01

Cart Product Feed Additional Product Fields: by ShoppingCartProductFeed; Remi Corson & Harsha Venkatesh – 1.1.3
Disable Emojis: by Ryan Hellyer – 1.5.2
Duplicate Page And Post: by Zeeshan Aslam Durrani – 1.1
Email Log: by Sudar – 1.9.1
Google Analytics by MonsterInsights eCommerce tracking addon: by The MonsterInsights Team – 5.5.3
Gallery Lightbox Lite: by GhozyLab
Inc. – 1.0.0.29

Glue for Yoast SEO & AMP: by Joost de Valk – 0.3.3
Google Analytics by MonsterInsights: by MonsterInsights – 5.5.4
IgniteWoo Updater: by IgniteWoo.com – 2.1.9
Imagify: by WP Media – 1.6.2
Manual Image Crop: by Tomasz Sita – 1.12
Page Views Count: by A3 Revolution – 1.4.0
PMR | Add Image Dimensions Columns: by Paul Riley – 1.0
Preserved HTML Editor Markup Plus: by Marcus E. Pope
marcuspope
Jason Rosenbaum
J-Ro – 1.5.3

ExportFeed - Create Product Feeds For 40+ Merchants: by ExportFeed.com – 3.1.6.8
Quote System: by Adam Ayres – 1.0
Redirect After Login: by marcelotorres – 0.1.5
Redirection: by John Godley – 2.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Replace Image: by Potent Plugins – 1.1.4
Require Featured Image: by Press Up – 1.2.3
Responsive Slider: by AlienWP – 0.1.9
Schema App Structured Data: by Hunch Manifest – 1.3.3
SendGrid: by SendGrid – 1.10.2
Simple Image Sizes: by Rahe – 3.1.1
Smart Manager: by Store Apps – 3.9.19
SSL Insecure Content Fixer: by WebAware – 2.2.1
Toolset Access: by OnTheGoSystems – 2.2.2
Toolset Types: by OnTheGoSystems – 2.2.5
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.27.22

User Switching: by John Blackbourn – 1.0.9
WooCommerce Catalog Product: by Catman Studios – 1.0.0
WooCommerce Colors: by WooThemes – 1.0.6
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Deposits: by Automattic – 1.1.10
WooCommerce - Embed Videos To Product Image Gallery: by ZealousWeb Technologies – 1.2
WooCommerce Free Shipping Pro: by IgniteWoo.com – 2.2.21
WooCommerce Authorize.Net AIM Gateway: by WooThemes / SkyVerge – 3.10.0
WooCommerce Google Trusted Stores Integration: by enollo – 1.0.0
WooCommerce - Gravity Forms Product Add-Ons: by WooThemes – 2.10.10
WooCommerce Insightly Integration: by Bryan Headrick – 1.0.0
WooCommerce MailChimp: by Saint Systems – 2.0.19
WooCommerce Multi-Shipment Tracking: by Bryan Headrick – 1.0.0
WooCommerce Product Add-ons: by Automattic – 2.7.25
WooCommerce Product Bundles: by WooThemes – 5.0.2
WooCommerce Sequential Order Numbers: by SkyVerge – 1.7.0
WooCommerce: by WooThemes – 2.6.9
WooDojo: by WooThemes – 1.5.4
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.0
WP All Export Pro: by Soflyy – 1.4.2
WP All Import Pro: by Soflyy – 4.4.0
WP Google Authenticator: by Julien Liabeuf – 1.1.0
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.0.1

WP Responsive Menu: by MagniGenie – 2.0.7
WP Rocket: by WP Media – 2.8.23
WP Security Audit Log: by WP White Security – 2.5.8
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.2

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #9 - /shop/
Cart: #10 - /pool-kit-shopping-cart/
Checkout: #11 - /pool-kit-checkout/
My Account: #13 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: PW
Version: 2.3.1
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: pw/woocommerce/emails/customer-invoice.php
pw/woocommerce/emails/email-addresses.php
pw/woocommerce/order/order-details-customer.php
pw/woocommerce/single-product/price.php

### Authorize.Net AIM ###

Environment: Production
`

**Comment by UserName011** [comment]
Why do you think canceled orders can't be updated? 
here is an example:
https://github.com/woocommerce/woocommerce/issues/12117

**Comment by BHEADRICK** [comment]
Based on Mike's comment in this issue, granted, this was 2yrs ago, so it may no longer be the case, but there seems to be a distinction between cancelled due to timeout and "user cancelled" which is what the order note describes

https://github.com/woocommerce/woocommerce/issues/5686
<img width="282" alt="user_cancelled" src="https://cloud.githubusercontent.com/assets/876009/21226240/964ae0b4-c2a2-11e6-8eb1-3805d58e6e28.png">

**Comment by mikejolley** [comment]
> I've seen notes from mikejolley indicating that orders cancelled by the user cannot be updated, so I assume that's the reason for this problem, but I would suggest this business logic be reevaluated.

Cannot be updated by the customer. Cancellation is permanent. HOWEVER in this case I think it's the best call - the payment was not cancelled, as evident by the IPN updating the order.

So looks like we just need to add a case so admin is notified.
