### ISSUE TITLE
Create / Add Review

### ISSUE THREAD

**Issue by gilbert-mjp** [woocommerce/woocommerce#12601]
Hi
Is there any way to add a review programmatically to a product via this API?

**Comment by claudiosanches** [comment]
Not right now, but will be possible in WooCommerce 2.7.

**Comment by gilbert-mjp** [comment]
thanks for the quick response. 
can you help point me to ..an alternate soln?

**Comment by claudiosanches** [comment]
Alternative is you create a custom endpoint for it.
Here how to create custom endpoints in the WordPress REST API: http://v2.wp-api.org/extending/adding/

**Comment by gilbert-mjp** [comment]
thanks. will look into it
