### ISSUE TITLE
Compatibility issue - Properties like $id and $variation_id became "protected"

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#12619]
**Issue introduced in WooCommerce 2.7**
There is a potentially serious issue with how the product classes are structured in WC 2.7. Properties like `$product->id` and `$product->variation_id` have historically been `public`. It's common practice, for the visibility of object properties, to be "one way only": properties are introduced as `protected`, then they may become `public`, but don't go back to `protected`. This is a reasonable assumption, which holds true in (almost) all project I've ever worked on.

In WC 2.7, properties like `$id` and `$variation_id` became `protected`, and that will cause issues with plugins that expect them to be accessible (i.e. quite a large amount of them).
I do understand that PHP doesn't provide a mechanism to have read-only public properties, and that the new abstraction layer might need that type of protection, but, in my opinion, properties like `$product->id`, `$order->id` and so on should be at least "soft deprecated" and left public for the moment. This will make it easier to switch to the new methods `WC_Product::get_id()` and `WC_Order::get_id()`, by keeping backward compatibility with WC 2.6 and without having to litter the code with "if WC version" (`WC_Order::get_id()` doesn't exist in WC 2.6 and earlier, only the product classes had that method).

**Comment by daigo75** [comment]
Correction: as @mikejolley pointed out, the `__get()` methods would allow to access the `$id` property, although they would raise a warning (this is also something that, in my opinion, could be improved, as PHP warnings are too "alarming" to the average Joe). The issue will arise if a protected `$id` is being written (unless there is a `__set()` method that I haven't spotted).

The question is: would anyone need to alter the `$id` property? Maybe. I remember that I wrote some code that does that, in the past, which was in my "to refactor" list, but there might be some use cases in which a writable `$id` might be needed. 

Perhaps it could be a good idea to write about the "read-only" change in the next announcement (just a suggestion). I will also think of a way to make the deprecated notices more "palatable".

**Comment by mikejolley** [comment]
> Correction: as @mikejolley pointed out, the __get() methods would allow to access the $id property, although they would raise a warning (this is also something that, in my opinion, could be improved, as PHP warnings are too "alarming" to the average Joe).

Alarming or not, not telling developers something is deprecated and will be removed is dangerous and just shifts the issue further into the future. We did toy with the idea of hiding notices, but decided against.

**Comment by daigo75** [comment]
I'm  not suggesting to hide notices, just to make them visible to developers, as clear "developer notes", rather than generic messages that appear to end users (they are a developer tool, after all).

The reason is that soft deprecations, in most cases, don't actually cause any immediate issue. Their purpose is to tell developers that "you should better look at this soon", and that's good. What's not so good is that the average end user considers notices and warnings the same as critical errors (also because they can cause side effects, if they are displayed on screen). The result is that even a soft deprecation causes the same level of concern as a fatal error.
The issue is exacerbated by the fact that a good percentage WooCommerce users completely ignore the big red note saying "don't upgrade without testing first", and blindly click on the update button.

**In my opinion**, it would be great to have the "soft deprecation" notices treated differently from standard warnings, and possibly displayed only when some sort of "developer mode" is enabled. This would allow end users to keep running their sites, while the plugin and theme developers work on improving their products. Hard deprecations are a different story, of course, as they will cause errors.

**Comment by mikejolley** [comment]
@daigo75 End users won't see these notices UNLESS WP_DEBUG is enabled. We've confirmed this. We'll be writing a post on this topic soon (basically advising no live/production site runs with WP_DEBUG and that these notices are nothing to panic about).

**Comment by mikejolley** [comment]
> Correction: as @mikejolley pointed out, the __get() methods would allow to access the $id property, although they would raise a warning (this is also something that, in my opinion, could be improved, as PHP warnings are too "alarming" to the average Joe). The issue will arise if a protected $id is being written (unless there is a __set() method that I haven't spotted).
>
> The question is: would anyone need to alter the $id property? Maybe. I remember that I wrote some code that does that, in the past, which was in my "to refactor" list, but there might be some use cases in which a writable $id might be needed.

The `set_id()` method is public, so this is allowable and CRUD will know of the change :)

There are other benefits to this change btw. I don't know if you noticed, but in legacy we made a real mess of variation ids. ->id was the parent id. With the new `get_id`/`get_parent_id` this is resolved.

Since we offer getters and setters for IDs I don't think we have a serious issue here. I'll certainly do that post on deprecation notices, and perhaps make a wiki entry too which we can link to from our warnings  - I think that would be useful for non-devs running WP_DEBUG by mistake.
