### ISSUE TITLE
B2B transactions support

### ISSUE THREAD

**Issue by msaggiorato** [woocommerce/woocommerce#12610]
**Overview**

At SAU/CAL, the company I work for, we have met lately with large companies that want to use WooCommerce as an eCommerce platform, but since it lacks support for B2B transactions, they are discouraged to take the step.

Taking advantage of the approach that’s cooking in the WC team about refactoring, we thought to do something similar to implement this feature in a very scalable way without affecting the core significantly.

Our approach basically consists in a couple things:

1. Separate customers from users (which will be stored in a separate table, for better indexability, posts are not very good for large stores).
2. Customers can be of 2 types: individuals, and companies.
    * Each of these will be linked to one or more users, and when several users are linked, each one will have a specific role for that customer/company (purchase manager for example).
3. Addresses will be saved in a separate table, to allow complex address keeping for companies (several shipping addresses for example, but we'll still use only one per order).

**Open to suggestions**

As said above, we intend to have this implemented as a plugin first, but hopefully do it in a nice way so that it can be considered for merging with WC Core at some point.

For this reason, even tho we haven't started working on this yet, we're open to any suggestions to improve this.

We've already been discussing this briefly with Mike Jolley, but he suggested that we bring it up here to have more people involved.

We appretiate any input. Thanks.

**Comment by danielhuesken** [comment]
We have allready done a plugin, for a client, there needs "multible addreses" (Amazon like) for B2B customer. In that case the user can not change the billing address too. But he can change the shipping address. If more than one address, than the cutsomer can seelect the address that will be used. I thnik the points above will make that easyer.

As second we need customer groups. So we can make special prices for a group. We already have a plugin for this too. But i think Grouping is interesting for all and for other awesome things.

I think that the tables for thes thinks above, must be hold global on a multisite. So you can use the addrese and so on on every store. In moment we use multisite stores for multilingual/currency and B2C/B2B seperated stores.

**Comment by mikejolley** [comment]
@msaggiorato You should post your proposed schema here too so it's easier to give feedback on.

**Comment by bekarice** [comment]
for posterity, lots of discussion around this point: https://github.com/woocommerce/woocommerce/issues/4064

**Comment by msaggiorato** [comment]
Ok @mikejolley, thanks for the advice. Here are the tables that we have in mind so far

## wc_customers

- customer_id
- customer_type (this will tell if the customer is an individual or a bussiness)
- name

This table will hold any absolute cricital information for a customer, which right now would be only the name, and the customer type.

## wc_customermeta

The structure of this table will be similar to any other meta table in WP, and will be used to store some specific information for the customer (settings, extra info, etc).

One use i can think for this table, is to store the default billing and shipping address used for a customer. This would allow us to only use one row in the wc_addresses table (mentioned below) and use that same row for both billing and shipping.

## wc_addresses

- address_id
- customer_id
- street_line1
- street_line2
- etc

## wc_customers_users_relationship

- customer_id
- user_id
- role

This would link a user to his individual customer, and also to any company he might be allowed to make purchases for.

-----------------------

We believe this structure will help address several cases:

- People being able to use the same user to make personal purchases, or purchases on behalf of the company they work for.
- Having different roles, will allow having people in a company be allowed to submit an order, but not be able to pay for it, for which there could be another role in charge of approving orders and paying for them.
- Having the address table will allow better indexability (and potentially improve reporting, or add new report types that work faster).
- The address table will also allow customers to keep an address book (which is not very related to B2B transactions on its own, but we thought it would be nice to work on it since we're basically revamping the customer data structure with this).
- This data structure will allow customers to exist without a user, which could be useful for people doing sales offline (via phone for example), and they'd be able to keep their sales records in WC.

-----------------------

Hey @danielhuesken , nice that you brought up multisite here, we didn't think of multisite cases yet. Just giving some thought to it now, and I wonder if we should have customers separated by site.

In our structure, customers will be linked to users, and users are global to the install. Should we store duplicate information for the same person buying in different language or currencies? Seems unnecesary to me, but maybe i'm missing something.

-----------------------

Thanks @bekarice for pointing out that issue, i've read through it to see some cases mentioned there that our idea might solve aswell.

**Comment by UserName011** [comment]
Please not the difference between customer and customer contact.
For example..
If Microsoft Inc buys from your store than the customer is Microsoft Inc and not the "John John" who works for Microsoft and did the transaction. If in the future you would like to see a report of all Microsoft orders you won't be able to do that if orders were registered under the contact.

**Comment by msaggiorato** [comment]
@UserName011 , in our proposed structure your example would work as you expect (unless i'm missing something):

- "Jhon Jhon" would be the user that makes the purchase.
- He would belong to the "Microsoft Inc" customer (which is going to be a bussiness customer)
- In reports, the customer would show up as a "Microsoft Inc" purchase, even tho the user that made it is "Jhon Jhon" which is also going to be stored.

Plus, beside that, the same user "Jhon Jhon" would be able to purchase something for his own if he so desires as an individual, without affecting "Microsoft Inc" purchase history.

**Comment by UserName011** [comment]
@msaggiorato I understand that this is what you mean but I don't understand how it is possible from the suggested database scheme. "He would belong to the "Microsoft Inc" customer (which is going to be a bussiness customer)"  - Can you show how this data "sits" in the database scheme?
If I read it right you will need two rows in wc_customers. One for the person and one for the company - This can cause problems...

**Comment by msaggiorato** [comment]
Every user will get an individual customer created upon sign up... Which will be the most common way of purchasing...

In practice this individual customer would serve the same purpose as the user currently does in WC... But here were separating the user from the customer...

Additionally... Every user can belong to one or more company (or business) customers... For which they can purchase as aswell...

So by default every user will get a wc_customer entry on sign up... And then depending on the companies he creates... Additional entries will be added...

In the case of a user just belonging to a company... Simply a relationship will be created... No company duplicate...

**Comment by UserName011** [comment]
@msaggiorato So by this definition user Jack can create 'Microsoft Inc' and user Jill can create another 'Microsoft Inc' and these two Microsofts are not the same... How can  'Microsoft Inc' itself control over their users? 

It could be that it happens to have two companies with same name so they are distinguished but they can also be the same company. Once the company is created the control over which user is allowed to make purchases for it should be within the company itself.

How would company associate users to it's account? will you give it an option to see all users?

**Comment by msaggiorato** [comment]
That's one of the ideas of our proposal. To have the creator of the company, be able to manage their users, and maybe even have some kind of permission levels to allow other people to add more users to the company. Or something like that.

All these relationships will be stored in **wc_customers_users_relationship**.

Two companies with the same name can exist with no problem, they're treated as different customers if that happens. Same thing that would happen if the same "Jhon Doe" creates 2 accounts to purchase. It's not something that needs to be restricted.

**Comment by mikejolley** [comment]
Is this still planned as a feature plugin? Is an issue still needed/more discussion?

**Comment by msaggiorato** [comment]
So far it's still in our plans to work on this. We posted it here to see the opinion of the community on our approach.

It'll definitely be a feature plugin at first, but hopefully at some point you'd be willing to merge this into core.

Not sure if further discussion is needed for now, but after we build it we will share it here and continue discussion on it.

**Comment by mikejolley** [comment]
👍 Ok then. Let's reopen this when thats ready for core consideration since it doesn't fall into our current roadmaps.

**Comment by rgeis** [comment]
I have gone through the pain of developing a system from scratch to support wholesale, retail and B2B in the same system.  We went through a lot of growing pains to make it happen.  One of the things that ended up being unexpected was the need for one user to have access to multiple companies. Basically a sales person would represent multiple locations, and each of the locations needed separate billing.

We are currently running a WordPress Woocommerce site for retail, and I was just starting down the road again for the need to support a single company with multiple users.  I represent six distinct operations that have a need for B2B and retail.  I know there is a need for a Woocommerce and B2B solution.

**Comment by brandomeniconi** [comment]
Sorry for bringing up this topic again but I've tried to search many sources but haven't found a plugin or core feature that allows WooCommerce to establish a many-to-many relation between Users and Customers. I need users to make purchases for different Customers and access the orders made for all of them.

I've seen that steps are been made after #4046 with the `WC_Customer` class and the ability to create 'guest' orders not linked to a user account, but there is no actual UI feature that let users see orders made by other users from the same 'Customer group' right? 

Thanks a lot.

**Comment by msaggiorato** [comment]
@brandomeniconi, currently there's a bunch of work that needs to be done to start working on this as a feature plugin.

We need the customer data store to be improved a bit to be able to decouple it from a WP_User, and allow a WC_Customer to be something other than just a user. After that (and maybe a couple other things that would be made evident after somebody starts working on this), there would need to be a structure similar to what we have proposed above to allow many to many relations.

**Comment by fdolin** [comment]
any idea how to best handle this issue before this feature plugin is launched...? thanks !

**Comment by spyesx** [comment]
Hello everyone. Is there somewhere a roadmap we can visit to have news from a B2B support?
Thank you :)
