### ISSUE TITLE
Broken Link in Documentation

### ISSUE THREAD

**Issue by webnard** [woocommerce/woocommerce#12612]
## EXPLANATION OF THE ISSUE

Broken link in documentation

## STEPS TO REPRODUCE THE ISSUE

1. Go to https://docs.woocommerce.com/wc-apidocs/package-WooCommerce.html
2. Click on the WooCommerce class
3. Get sent to a missing URL (should be https://docs.woocommerce.com/wc-apidocs/class-Woocommerce.html)

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Should be fixed.
