### ISSUE TITLE
Woocommerce shop page

### ISSUE THREAD

**Issue by antondrob** [woocommerce/woocommerce#12615]
## EXPLANATION OF THE ISSUE

I checked hide out of stock in admin.
I display 24 products per page by hook filter loop_shop_per_page.
But on some pages it can display 19 or 21 or 23 or 22.
## STEPS TO REPRODUCE THE ISSUE

1) Create lots of variable products (in stock, out of stock)
2) Check hide out of stock in admin
3) Go at shop page an look different pages on pagination
## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://obuvmart.pro
Site URL: https://obuvmart.pro
WC Version: 2.6.9
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU

### Server Environment ###

Server Info: Apache/2.2.22 (Debian)
PHP Version: 5.6.9
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.26.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Удалить запись: ✔
Удалённое получение: ✔

### Database ###

WC Database Version: 2.6.9
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (14) ###

Contact Form 7: от Takayuki Miyoshi – 4.6
Custom Taxonomy Order NE: от Marcel Pol – 2.8.2
Cyr to Lat enhanced: от Sol
Sergey Biryukov
Nikolay Karev
Dmitri Gogelia – 3.5

Extensions for Obuvmart.pro: от Anton Drobyshev – 1.0
Popup Maker: от WP Popup Maker – 1.4.21
Theme Customisations: от WooThemes – 1.0.0
Widget Logic: от Alan Trewartha – 0.57
WooCommerce and 1C:Enterprise/1С:Предприятие Data Exchange: от Данил Семеленов – 0.7
WOOF - WooCommerce Products Filter: от realmag777 – 2.1.6
WooCommerce: от WooThemes – 2.6.9
WordPress HTTPS: от Mike Ems – 3.3.6
Yoast SEO: от Команда Yoast – 4.0
WP Encrypt: от Felix Arntz – 1.0.0-beta.7
YITH WooCommerce Dynamic Pricing and Discounts Premium: от YITHEMES – 1.1.6

### Settings ###

Force SSL: ✔
Currency: RUB ( руб.)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Ссылка магазина: #4 - /shop/
Корзина: #5091 - /cart/
Оформление заказа: #6 - /checkout/
Мой аккаунт: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Storefront
Version: 2.1.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – Если вы модифицируете элементы WooCommerce в теме WordPress
которую вы не разрабатывали самостоятельно
рекомендуется использовать дочернюю тему. Читайте: Как создать дочернюю тему

WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/emails/email-order-details.php
`

**Comment by mikejolley** [comment]
Please look into your filter plugins which may change how queries work. WC has a filter to hide the out of stock products before display which keeps per page correct. This is still working my side.

**Comment by antondrob** [comment]
I deactivated all plugins except woocommerce, but the problem isn't solved. E.g. https://obuvmart.pro/shop/page/3/. There sould be 12 products, but i see only 10

**Comment by mikejolley** [comment]
Save those out of stock products again and see if the counts change.

**Comment by antondrob** [comment]
Thanks for the answer.
Did it as you sad. The problem didn't disapper. I am afraid it's a system error.
The same error I have on aour another web site https://obuvmart.ru/ There I have another theme

**Comment by mikejolley** [comment]
Still did you look at plugins? You have filter plugins which mess with queries.

**Comment by antondrob** [comment]
Yes, I did...
I can describe what i'm doing more precise
I deacivate all plugins except WC. Then I count the products. I have 259 pages and 12 products per page. 258*12+2=**3098**. But WC counts **3099**. Where could an extra product appear from? But the most interesting thing is that on some pages there are less than 12 product (page 3: 10 products, page 4: 10 products, page 6: 11 products). That means that the total product quantity is much less than 3099 which counts WC. This happens even when I have only one Woocommerce and theme Storefront.

Now I activate all plugins and I have 24 products per page. The problem is similar. WC counts **3099**. Total number of pages - 130. 129*24+2=**3098**. But again on some pages there are less than 24 product (page 2: 20 products, page 3: 23 products, page 4: 22 products).
So the system behavior without plugins and with plugins is similar. That is why I except plugins errors. 

Maybe my conclusion is wrong? In this case can you please provide me some guide how it can be checked? But I am sure that it is WC error which apeares with huge products database.

I'm looking forward to hearing from you soon. Thanks.

**Comment by mikejolley** [comment]
I mentioned we use a query to hide out of stock products; if your plugin has affected what data is stored, those queries may fail. I have no issues on other installs.

**Comment by antondrob** [comment]
I caught smth)
It happens with some out of stock products, not all. It's weird because normal and abnormal products don't differ with each other. They somehow set in the query...moreover woocommerce result count also counts it. I just clicked on update and these 2 products disappeared from woocommerce result count. What do you think can be the reason? 
P.s. all stock is managed by crm. When we sell some product the crm system send xml, plugin reads it and manages the stock.

**Comment by mikejolley** [comment]
Sounds like the plugin you're using to sync is not setting the correct stock_status meta on the products, nor is it clearing caches.

**Comment by antondrob** [comment]
Checked one out of stock product in mysql. Yes, stock_status is instock. Thanks very much!

**Comment by antondrob** [comment]
Hi mikejolley!
Thanks for you help, I solved my previous problem with sync plugin.
I also have a problem with wc count result on some pages (it shows that it has found just a single result)
e.g. this link https://obuvmart.ru/pa_gruppa-obuvi/botinki-polusapozhki-sapozhki/
on a very similar page it shows normal count https://obuvmart.ru/pa_gruppa-obuvi/valenki/
And in some time on a page with a single result it can show normal count.
What can be the reason of this?
