### ISSUE TITLE
2.7beta1 contains some British English

### ISSUE THREAD

**Issue by webaware** [woocommerce/woocommerce#12627]
Working through the new translations for the 2.7 beta, and I can see a few instances of British English (i.e. English for everyone except USA). Search the codebase for `colour` and `cancelled` and you'll find them.

(Base language is always en-US, because translations can't supply en-US and the toolsets all pretty much expect all base strings to be in en-US)

**Comment by mikejolley** [comment]
🇬🇧

**Comment by mikejolley** [comment]
`cancelled` is used in order statuses so cannot be changed..

**Comment by mikejolley** [comment]
> In American English, the verb cancel is usually inflected canceled and canceling—with one l. This is not a rule, however, and exceptions are easily found.

Interesting that schema.org uses two ll's http://schema.org/OrderCancelled

Going to leave as-is.

**Comment by webaware** [comment]
@mikejolley you've made changes to code here, not just strings. I think this is a bad idea -- changing data element names (e.g. `chart_colours` to chart_colors`) can break backwards compatibility for anyone extending WooCommerce. Only strings need to change here.

FWIW, I reckon it's OK to leave comments in en-GB too -- they don't affect anyone -- but I can understand the desire for consistency.
