### ISSUE TITLE
Undesired behavior when shipping packages contain virtual-only items

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#12628]
This is both a question and likely an issue report.

While working together with @ChaseWiseman, we stumbled upon issues arising from the fact that virtual cart items are added to the initial shipping package along with physical ones: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart.php#L1470

The issue also relates to the fact that WC decides whether shipping is required at cart-level -- https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart.php#L1497-L1515

One implication of the current logic is that if you have multiple shipping packages and one of them contains virtual-only products (possibly a result of cherry-picking physical items and placing them in "additional" shipping packages according to a rule), WC will attempt to calculate a shipping cost for the virtual-only package as well.

The obvious question is why virtual products are added to shipping packages in the first place? Is there a reason behind this, or is it something that can be improved -- e.g. construct the initial shipping package by looping through cart contents and picking physical products.

Also it seems more logical that `needs_shipping` should operate at package level -- e.g. check if at least one shipping package exists (provided that shipping packages contain physical items only).

**Comment by franticpsyx** [comment]
PS: Looking at https://github.com/woocommerce/woocommerce/tree/discount-calc-class this is fixed there, so we might consider fixing this in 2.7 as well.

**Comment by mikejolley** [comment]
I'll roll in the code from that branch.
