### ISSUE TITLE
Dynamic URL via AJAX

### ISSUE THREAD

**Issue by MMaKenZi** [woocommerce/woocommerce#12629]
## EXPLANATION OF THE ISSUE
Previously I asked a question in #12576 
I think it will be so good to have dynamic url, what I mean?
I mean when we select our preferred combination of a variable product, as we select any variation, it's slug add to url via ajax
so finally when we chosen our best combination of variable product, we have a link that can share it with whoever we want and wherever we want, because it will point directly to the product We already want

but right now, we should say : 
as example:
open "sample product 1"
"choose first one of the first variation and third one of the second variation and this the product I was talking to you about"
You know, this is somehow unprofessional

In fact by variable products, we put some products in one, I mean we probably have 1000 product, but by using variable products, it seems that we have for example 500 produt or less (what many of online shopping do)
so if we provide direct url to variable products, maybe google indexed variable products too

**Comment by mikejolley** [comment]
You can link through to a variation (see the cart page, click on a variation link once added to cart) but we do not support dedicated pages per variation.

In code, you can get the permalink of a variation using the product class get_permalink function.
