### ISSUE TITLE
woocommerce_downloadable_file_allowed_mime_types

### ISSUE THREAD

**Issue by nuvoPoint** [woocommerce/woocommerce#12633]
Hey,
the filter woocommerce_downloadable_file_allowed_mime_types is not respected on variable products variations.

Please modify: woocommerce\includes\admin\meta-boxes\class-wc-meta-box-product-data.php line 1405

From:
$allowed_file_types = get_allowed_mime_types();

To:
$allowed_file_types = apply_filters( 'woocommerce_downloadable_file_allowed_mime_types', get_allowed_mime_types() );

**Comment by mikejolley** [comment]
This is resolved in 2.7
