### ISSUE TITLE
2.7 CRUD - getting and setting custom order fields

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#12634]
## EXPLANATION OF THE ISSUE

From 2.7 if we use $order->billing_customfield we get a "Order properties should not be accessed directly." warning. On the other hand, we cannot use the get_address_prop() function, used by the new CRUD methods, because it's protected.

Am I missing something here, our we're missing getters and setters for custom fields?

Also, it seems like fields added by the 'woocommerce_billing_fields' filter are not being saved into the order meta, but I'll have to test this further. Anyone else noticing this?

## SYSTEM STATUS REPORT
WooCommerce 2.7
WordPress 4.7

**Comment by webdados** [comment]
After setting up two WordPress fresh installs, one with the stable WooCommerce version 2.6.9 and another with 2.7, I can confirm that if we add a new address field via the 'woocommerce_billing_fields' or 'woocommerce_shipping_fields', the following happens:

WooCommerce 2.6.9:
- The field shows up on both the My Account / Addresses and Checkout forms;
- The field is correctly saved to the user meta on the My Account / Addresses forms;
- The current user meta value is correctly loaded into the Checkout field when it exists already;
- After the checkout is completed the custom field value is correctly saved/updated into both the order and user meta;

WooCommerce 2.7:
- The field shows up on both the My Account / Addresses and Checkout forms;
- The field is correctly saved to the user meta on the My Account / Addresses form;
- The current user meta value is **NOT loaded** into the Checkout field even if it exists already;
- After the checkout is completed the custom field value is **NOT saved/updated** into neither the order or user meta data;

This can potentially break a huge amount of plugins that create custom address fields.
I'm willing to make more tests on request or provide more details on how this was tested.

**Comment by webdados** [comment]
Thanks for the fix for the custom fields on the checkout.

What about getters and setters for custom fields, when not in the checkout?

**Comment by mikejolley** [comment]
@webdados Not possible to define getters and setters for unknown fields - use get and set meta methods.

**Comment by webdados** [comment]
So: `$order->get_meta($key)`, `$order-> update_meta_data($key, $value)`, right?

Thanks!

**Comment by Magnetize** [comment]
@webdados did you get the get_meta and update_meta_data functions to work?
I am trying it now on a testsite but if I do $order->update_meta_data("test", "testing"); and then tries to display it, it doesn't work unless I set the value right before presenting it.
I.E. this works:
 `$order->update_meta_data("test", "testing");
echo $order->get_meta("test");`
This does not work:
`$echo $order->get_meta("test");`

Also trying to find the data in the database, but did not find it yet.

**Comment by Magnetize** [comment]
Sorry @webdados , thought it was semi-related to your question about custom fields. Thanks, and doh, missed the save()-part. :)

**Comment by vyskoczilova** [comment]
@webdados Hi guys, I stumbled upon this discussion while trying to fix my plugin which adds VAT and other custom fields to billing address and I still didn't make it work correctly for WC 3.0, could you help?

I tried that one, but the meta is not loaded.

```
add_filter( 'woocommerce_order_formatted_billing_address', 'woolab_icdic_order_formatted_billing_address', 10, 
function woolab_icdic_order_formatted_billing_address($address, $order) {
	
	if ( version_compare( WC_VERSION, '2.7', '<' )) { 
		return $address += array(
				'billing_ic'	=> $order->billing_ic,
				'billing_dic'	=> $order->billing_dic
				);
	} else { 
		return $address += array(
				'billing_ic'	=> $order->get_meta('billing_ic'),
				'billing_dic'	=> $order->get_meta('billing_dic')
				);
	} 

}
```

**Comment by claudiosanches** [comment]
@vyskoczilova do not work because it's missing an `_`.

Change to:

```php
				'billing_ic'	=> $order->get_meta('_billing_ic'),
				'billing_dic'	=> $order->get_meta('_billing_dic')
```

**Comment by vyskoczilova** [comment]
@claudiosanches thanks a lot! Worked out well. Could I have another little question? How to load the saved value while editing the billing field in admin? I tried to fix it same time and found this one, but it doesn't look like working solution (for the new WC):

```
add_filter( 'woocommerce_ajax_get_customer_details', 'woolab_icdic_ajax_get_customer_details', 10, 3 );
function woolab_icdic_ajax_get_customer_details($data, $customer, $user_id){
	$data['billing_ic'] = get_user_meta( $user_id, 'billing_ic', true );
	$data['billing_dic'] = get_user_meta( $user_id, 'billing_ic', true );
	return $data;
}
```

**Comment by claudiosanches** [comment]
Looks like the same problem.
Still here is not a support channel, that's why I'm closing it.
