### ISSUE TITLE
2.7 missing meta data for single product

### ISSUE THREAD

**Issue by komarovartem** [woocommerce/woocommerce#12630]
## EXPLANATION OF THE ISSUE

Hi. The categories and tags are not displayed for single-product/meta.php

I guess, the ID of product as a first argument is missing for wc_get_product_category_list() and wc_get_product_tag_list() methods.

Regards

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/commit/4394f243260f6695d56869fdb37dba8db98d6794
