### ISSUE TITLE
False Positive in System Status "Table does not exist"

### ISSUE THREAD

**Issue by silicondales** [woocommerce/woocommerce#12635]
## EXPLANATION OF THE ISSUE

Client site, on checking WC status page reads:

"Table does not exist" for every table

Tables exist.

Also saw this here which sounds similar https://wordpress.org/support/topic/database-table-does-not-exist-1/

## STEPS TO REPRODUCE THE ISSUE

Tentatively ... that there's a non wp_ db prefix, but this is surely not our issue !?
Also - is Microsoft / IIS server the problem?

## SYSTEM STATUS REPORT

Note - all the tables do exist. The issue here is that this is a false positive. Finding out why is the question... (I know this client has outdated templates... that's one for me to fix :) )
`
### WordPress Environment ###

Home URL: https://kooima.com
Site URL: https://kooima.com
WC Version: 2.6.9
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Microsoft-IIS/8.5
PHP Version: 5.6.27
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.50.3
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.9
: 
woocommerce_sessions: ❌ Table does not exist
woocommerce_api_keys: ❌ Table does not exist
woocommerce_attribute_taxonomies: ❌ Table does not exist
woocommerce_downloadable_product_permissions: ❌ Table does not exist
woocommerce_order_items: ❌ Table does not exist
woocommerce_order_itemmeta: ❌ Table does not exist
woocommerce_tax_rates: ❌ Table does not exist
woocommerce_tax_rate_locations: ❌ Table does not exist
woocommerce_shipping_zones: ❌ Table does not exist
woocommerce_shipping_zone_locations: ❌ Table does not exist
woocommerce_shipping_zone_methods: ❌ Table does not exist
woocommerce_payment_tokens: ❌ Table does not exist
woocommerce_payment_tokenmeta: ❌ Table does not exist

### Active Plugins (38) ###

Add Admin CSS: by Scott Reilly – 1.4
Admin Columns Pro: by AdminColumns.com – 3.8.9
Advanced Custom Fields PRO: by Elliot Condon – 5.5.2
BackupBuddy: by iThemes – 7.2.1.1
WooCommerce Custom Order Status & Actions: by Actuality Extensions – 1.6.8
Contact Form 7: by Takayuki Miyoshi – 4.6
FooBox HTML & Media Lightbox: by FooPlugins – 2.3.2.39
Google Analytics by MonsterInsights: by MonsterInsights – 5.5.4
Google Language Translator: by Rob Myrick – 5.0.29
Google No CAPTCHA reCAPTCHA by WisdmLabs: by WisdmLabs – 4.0.5
IgniteWoo Updater: by IgniteWoo.com – 2.1.9
Kooima Canada Freight Custom WooCommerce Shipping Method: by Matt Van Rys – 1.0.0
Kooima Custom New Order Email: by Matt Van Rys – 1.0.0
Kooima Disable Emails: by Matt Van Rys – 1.0.0
Kooima Domestic Freight Custom WooCommerce Shipping Method: by Matt Van Rys – 1.0.0
Kooima Farm Account Custom WooCommerce Payment Gateway: by Matt Van Rys – 1.0.0
Kooima International Freight Custom WooCommerce Shipping Method: by Matt Van Rys – 1.0.0
Kooima Search Order: by Sixto Santos – 1.3
Real 3D Flipbook: by zlac – 2.6.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Relevanssi: by Mikko Saari – 3.5.6.1
Sidebar Login: by Mike Jolley – 2.7.3
Sorting WooCommerce Pro: by Galal Aly – 3.1
WooMedia WooCommerce UPS: by WooMedia Inc. – 2.2.4
Admin Theme: by Matt Van Rys – 1.0
Theme My Login: by Jeff Farthing – 6.4.6
Use Google Libraries: by Jason Penney – 1.6.2.1
WooCommerce Cancelled Order Email: by SkyVerge – 0.1
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooThemes – 4.4.3
WooCommerce - Watermark: by David Baker – 1.1.1
WooCommerce Tiered Pricing: by IgniteWoo.com – 2.4.13
WooCommerce - Custom Users Meta Extra Search: by Remi Corson – 1.0
WooCommerce: by WooThemes – 2.6.9
WooCommerce Helper: by WooCommerce – 1.7.2
WordPress HTTPS: by Mike Ems – 3.3.6
Yoast SEO: by Team Yoast – 4.0
WP Database Backup: by Prashant Walke – 4.3.7
WP-Mail-SMTP: by Callum Macdonald – 0.9.5

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #9 - /shop/
Cart: #10 - /cart/
Checkout: #11 - /checkout/
My Account: #12 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Kooima Company
Version: 1.0
Author URL: http://mattvanrys.com/
Child Theme: ✔
Parent Theme Name: kooima-base
Parent Theme Version: 1.0
Parent Theme Author URL: http://underscores.me/
WooCommerce Support: ✔

### Templates ###

Overrides: kooima/woocommerce/archive-product.php
kooima/woocommerce/cart\cart-empty.php
kooima/woocommerce/cart\cart-shipping.php
kooima/woocommerce/cart\cart.php
kooima/woocommerce/checkout\cart-errors.php
kooima/woocommerce/checkout\form-checkout.php
kooima/woocommerce/content-product.php version 2.5.0 is out of date. The core version is 2.6.1
kooima/woocommerce/content-product_cat.php version 2.5.2 is out of date. The core version is 2.6.1
kooima/woocommerce/content-single-product.php
kooima/woocommerce/emails\admin-new-order.php
kooima/woocommerce/emails\customer-completed-order.php
kooima/woocommerce/emails\email-order-details.php
kooima/woocommerce/emails\plain\customer-completed-order.php version 2.0.0 is out of date. The core version is 2.5.0
kooima/woocommerce/global\wrapper-end.php
kooima/woocommerce/global\wrapper-start.php
kooima/woocommerce/myaccount\view-order.php version 2.2.0 is out of date. The core version is 2.6.0
kooima/product-searchform.php version - is out of date. The core version is 2.5.0
kooima/woocommerce/single-product.php
kooima/woocommerce/taxonomy-product_cat.php

**Comment by silicondales** [comment]
I can only replicate in the client's setup as it is IIS and... well who would do that ! 

I may initiate a transfer of hosting and see if that resolves this and some other issues currently being experienced.

**Comment by mikejolley** [comment]
It's not the prefix. We don't hardcode prefixes :)

**Comment by mikejolley** [comment]
`$wpdb->prepare( "SHOW TABLES LIKE %s;", $wpdb->prefix . $table )`

That SQL code is perfectly fine. This also mirrors how WP core does it https://github.com/WordPress/WordPress/blob/4cf5550d8d7f227d760f779f250a8fb2cfa2c8c9/wp-admin/install.php#L95

I think this is a config issue on your IIS server. Either this is not supported for some odd reason, or your user does not have the correct privileges to list or view all tables.

**Comment by silicondales** [comment]
Can confirm this is a IIS peculiarity.

**Comment by KrolFERNANDES** [comment]
Hello, I had the same problem, I contacted the hosting server and they solved some of the errors, however I was told that the errors referring to the table, are at the programming level. You can check with your developer or plugin support.

How should I proceed?

`
### WordPress Environment ###

Home URL: http://vitta3d.com/vitta
Site URL: http://vitta3d.com/vitta
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR

### Server Environment ###

Server Info: Microsoft-IIS/8.0
PHP Version: 7.0.23
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.55.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: ❌ 5.1.73 - Nós recomendamos utilizar pelo menos a versão 5.6 do MySQL. Mais informações: Requerimentos do WordPress
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ O seu servidor não possui a classe SoapClient ativada - alguns métodos de pagamento que usam SOAP podem não funcionar como esperado.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: jH3
woocommerce_sessions: ❌ Esta tabela não existe
woocommerce_api_keys: ❌ Esta tabela não existe
woocommerce_attribute_taxonomies: ❌ Esta tabela não existe
woocommerce_downloadable_product_permissions: ❌ Esta tabela não existe
woocommerce_order_items: ❌ Esta tabela não existe
woocommerce_order_itemmeta: ❌ Esta tabela não existe
woocommerce_tax_rates: ❌ Esta tabela não existe
woocommerce_tax_rate_locations: ❌ Esta tabela não existe
woocommerce_shipping_zones: ❌ Esta tabela não existe
woocommerce_shipping_zone_locations: ❌ Esta tabela não existe
woocommerce_shipping_zone_methods: ❌ Esta tabela não existe
woocommerce_payment_tokens: ❌ Esta tabela não existe
woocommerce_payment_tokenmeta: ❌ Esta tabela não existe
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Sua loja não está usando HTTPS. Saiba mais sobre HTTPS e certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (18) ###

LayerSlider WP: por Kreatura Media – 6.5.5
Akismet Anti-Spam: por Automattic – 4.0
bbPress: por A comunidade bbPress – 2.5.14
Contact Form 7 Database: por NinjaTeam – 1.3
Contact Form 7: por Takayuki Miyoshi – 4.9
Fusion Builder: por ThemeFusion – 1.2.2
Fusion Core: por ThemeFusion – 3.2.2
GF Upload to Email Attachment: por Greg Whitehead – 2.2
Lockdown WP Admin: por Sean Fisher – 2.3.2
Multifile Upload Field for Contact Form 7: por Spyros Vlachopoulos – 1.0.1
Woo File Dropzone: por Murtaza Bhurgri – 1.1.6
WooCommerce PayPal Express Checkout Gateway: por WooCommerce – 1.4.4
Portal do Stripe para WooCommerce: por WooCommerce – 3.2.3
WooCommerce PagSeguro: por Claudio Sanches – 2.12.5
WooCommerce: por Automattic – 3.1.2
WP eCommerce: por WP eCommerce – 3.12.4
WP Mail SMTP Plugin by Mail Bank: por Tech Banker – 3.0.18
WP-Optimize: por David Anderson
Ruhani Rabin
Team Updraft – 2.1.1


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base da loja: #140 - /loja/
Carrinho: #141 - /carrinho/
Finalizar compra: #142 - /finalizar-compra/
Minha conta: #143 - /minha-conta/

### Theme ###

Name: Avada
Version: 5.2.2
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema pai. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart\cart.php
Avada/woocommerce/checkout\form-pay.php
Avada/woocommerce/checkout\review-order.php
Avada/woocommerce/checkout\thankyou.php
Avada/woocommerce/loop\loop-start.php
Avada/woocommerce/single-product\add-to-cart\variable.php
Avada/woocommerce/single-product\add-to-cart\variation-add-to-cart-button.php
Avada/woocommerce/single-product\short-description.php
Avada/woocommerce/single-product\tabs\additional-information.php
Avada/woocommerce/single-product\tabs\description.php

`

**Comment by DirkWolthuis** [comment]
I have the same issue with a Docker setup, with a link to a mariaDB container.

**Comment by klipitkas** [comment]
I experience this too (this is not a new wordpress setup, it was an existing and I just updated it), docker setup with MariaDB (mysql  Ver 15.1 Distrib 10.2.10-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2). The default tables are not getting created, I have tried removing the plugin with the ``define( 'WC_REMOVE_ALL_DATA', true);``` line in my wp-config.php as well, it does not work. Also tried with mysql 5.7 (mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper) and does not work there either. My issue is related with this and possibly #11912.

**Comment by vankampenp** [comment]
I have this too, on IIS, all tables are reported not existing with the prefix in capitals:
E4J0Y7Xv_woocommerce_sessions

The same table is also reported existing, with the prefix in lower case:
e4j0y7xv_woocommerce_sessions

**Comment by MojoCreator** [comment]
I have the exact same problem, the tables actually do exist and there are no errors associated with the tables.  This was an upgrade to WooCommerce DB 3.5.1.  This is on Apache 2.4 running PHP 7.2. All theme templates are updated. The only errors on the status page are the "Table does not exist" errors.

I was also able to "Clear Sessions" using the Tools>Clear Sessions button and it showed that the sessions table was cleared. I checked the woocommerce_sessions table and sure enough, all sessions were cleared.

**WooCommerce Table Status:** https://www.screencast.com/t/Ab4PoWnOs
**WooCommerce Clear Sessions:** https://www.screencast.com/t/byvxYvFinp
**WooCommerce Collation:** https://www.screencast.com/t/qgDvfiYA

**Comment by RavanH** [comment]
Ran into the same today. Status page says all tables are missing but they are all present. Going back through the error log, I do notice one related error:

> [07-Nov-2018 14:14:03 UTC] Erreur de la base de données WordPress Can't create table `xxxxx_xx`.`#sql-6b77_2277a5` (errno: 121 "Duplicate key on write or update") pour la requête 
> 					ALTER TABLE `xxx_wc_download_log`
> 					ADD CONSTRAINT `fk_wc_download_log_permission_id`
> 					FOREIGN KEY (`permission_id`)
> 					REFERENCES `xxx_woocommerce_downloadable_product_permissions` (`permission_id`) ON DELETE CASCADE;
> 				 faite par activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::install, WC_Install::create_tables
> 

The table xxx_wc_download_log is present but what is that part `fk_wc_download_log_permission_id` there? The fk_ is not my DB prefix... De/reactivating Woocommerce will cause the same error message.

**Comment by RavanH** [comment]
This open issue seems related https://github.com/woocommerce/woocommerce/issues/21657

**Comment by rrennick** [comment]
> I do notice one related error:

This was fixed in #21940.

**Comment by ChemistryTeacher** [comment]
> I have the same issue with a Docker setup, with a link to a mariaDB container.
> 
> Edit: It had to do with linux permissions of the db files. Fixed now.

How do I do that? I work with PLESK in Windows. How can I get Linux permissions?
