### ISSUE TITLE
Minor Tweak for Variations of Variable product

### ISSUE THREAD

**Issue by MMaKenZi** [woocommerce/woocommerce#12638]
## EXPLANATION OF THE ISSUE

If we want to edit a variation of a variable product, we should first open it's slide and then try to edit
we can save so many time with adding two checkboxes to the variation closed row that will be visible while mouse hover on it

this two option which can save so many time are, enable and out of stock checkbox
specially if you have so many variations in a product, this way we can do basic stuff faster

<img src="http://lioncomputer.ir/uppic/images/9oct81vkkbk04qlkxwj4.jpg" alt="what I mean">

**Comment by mikejolley** [comment]
This is a subjective change. This may speed up your workflow, but other store owners may use other settings more commonly, and then if they ask for more fields there we may as well not collapse at all :)

You can expand all using the links on the far right, then edit all rows.
