### ISSUE TITLE
woocommerce_my_account_my_orders_query custom args are ignored

### ISSUE THREAD

**Issue by decarvalhoaa** [woocommerce/woocommerce#12643]
I need your guidance on how to proceed with a PR to resolve the following issue.

Before 2.6.0, the customer orders in the my_account/my_orders.php template were retrieved with `get_posts() `function. It was possible to pass a custom argument through the filter _woocommerce_my_account_my_orders_query_ that where pass downstream to the WP_Query args.

My use-case: I have been using Polylang and Hyyan WooCommerce Polylang Integration plugins to enable multi-language support on my store. The Hyyan WooCommerce Polylang Integration plugin uses the _woocommerce_my_account_my_orders_query_ filter to pass a custom language argument, `array( lang => 'en,de' )`, to display all orders created by a customer regardless of the current display language.

With 2.6.x, the customer orders are no longer retrieved with `get_posts()`, but rather with `wc_get_orders()` wrapper function that still has the args filtered with _woocommerce_my_account_my_orders_query_ filter.
Within the `wc_get_orders()` function, the orders are fetch from the DB using 

`$orders = new WP_Query( $wp_query_args )`

The way `$wp_query_args` is build ignores any custom args passed by the filter. I wanted to make a PR to copy custom args passed by the filter to the `$wp_query_args` by adding the below code just before the WP_Query instance is instantiated. 

```
// Copy custom args to the WP_Query args
$exclude_args = array( 'status', 'type', 'parent', 'customer', 'email', 'limit', 'offset', 'page', 'exclude', 'return', 'paginate' );

foreach ( $args as $key => $value ) {
	if ( ! isset( $wp_query_args[ $key ] ) && ! in_array( $key, $exclude_args ) ) {
		$wp_query_args[ $key ] = $value;
	}
}

// Get results.
$orders = new WP_Query( $wp_query_args );
```

The issue is I'm not sure against what release - 2.6.9 or 2.7.0 (master) - I should do the PR, since in 2.6.9 the change would affect the includes/wc-order-functions.php file and in 2.7.0 the code needed to by added to the includes/data-stores/class-wc-order-data-store-cpt.php file.

Can you please indicate, whether I should go ahead with the PR (perhaps there is a more elegant way to achieve what I need), and if yes, against which code base shall it be done. Thanks in advance.

PS: sorry for the long text.

**Comment by mikejolley** [comment]
I think we need a new filter in the new data crud for the query. I'll add one.
