### ISSUE TITLE
Fetch images of products in an Order

### ISSUE THREAD

**Issue by dipeshparashar** [woocommerce/woocommerce#12647]
When getting an order details. It lists line_items without image of the product. If a order has 5 items, how can the images for each product received.

**Comment by mikejolley** [comment]
Line items will return product ids, which you can then lookup from the /product/ endpoint.

**Comment by dipeshparashar** [comment]
Would it take 5 different calls or is there any way to to get products/filter[id]=id1,id2... to get specific 5 products in a single call?

**Comment by mikejolley** [comment]
You could filter http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

**Comment by dipeshparashar** [comment]
Tried filter[id] = [id1, id2 ..]. Its the same with SKU. It still returns all the products. Could you please suggest an example or the apt syntax.

**Comment by mikejolley** [comment]
Filter is part of the WP Rest API. https://code.tutsplus.com/tutorials/wp-rest-api-retrieving-data--cms-24694 Pretty sure it supports WP_Query args and values. id is not one of those https://codex.wordpress.org/Class_Reference/WP_Query

**Comment by dipeshparashar** [comment]
Doesn't seem to work. Its not elegant to make multiple calls for each product.

**Comment by mikejolley** [comment]
post__in?

**Comment by dipeshparashar** [comment]
I guess there is no post__in parameter for product. The only unique would be id, sku . There is search parameter for products https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products but not syntax is provided for it. If products can be searched that would do the trick.

**Comment by mikejolley** [comment]
Products are posts..
