### ISSUE TITLE
[2.7] CRUD hooks for adding/updating/deleting object meta (and props) before save

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#12648]
When re-writing existing code to utilize the CRUD classes, a re-occurring scenario is the requirement to add/update/delete a meta field when a CRUD object is created/updated/deleted.

Until 2.6 we used `'woocommerce_process_' . $post->post_type . '_meta'` for this.

2 simple examples:

- Add/update/delete a meta field when a Product is created/updated from the Dashboard depending on its type, props and/or posted fields (e.g. write "Cost of Goods" plugin meta data when saving the product).
- Update type-specific props when a Product is created/updated from the Dashboard.

The obvious way to do it would be to use the existing hooks, such as `woocommerce_process_product_meta` at a later priority than WC core, call `wc_get_product`, then add/update/delete meta on the object and finally `save()`.

However, this is not a sustainable approach if, say, you have 10 plugins installed and each needs to save it own product meta. It would be nice to have a way to do it on the object, before it gets saved/deleted. 

I guess this would need to happen in data stores (products, orders, coupons, etc)?

Existing hooks in datastore classes either:

1. Do not pass the object as argument; or
2. Are not consistently fired before or after saving to the DB -- compare https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-order-data-store-cpt.php#L78 with https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L101 (one fires after saving to the DB, the other half way, and none can be used to modify the actual object before the saving process starts)

I am a bit confused as to what's the expected way to add/modify (meta) data in CRUD objects.

**Comment by mikejolley** [comment]
See #12649
