### ISSUE TITLE
Feature Request: insert order status in my account table row

### ISSUE THREAD

**Issue by nicmare** [woocommerce/woocommerce#12658]
## EXPLANATION OF THE ISSUE

Can we please insert "order status" classes in "my account" order table row?
This way i can fadeout some old, finished orders or can highlight important orders which are not payed via css.

## STEPS TO REPRODUCE THE ISSUE

go to myaccount -> orders -> table row classes or "templates/myaccount/orders.php" line 43 where you find <tr class="order">. simply insert the escaped order status as css classname here.

**Comment by mikejolley** [comment]
@jameskoster Can we add this and also sort out class naming in order.php? Want to follow https://github.com/woocommerce/woocommerce/wiki/CSS-SASS-coding-guidelines-and-naming-conventions but it's a bit of a mess right now.

**Comment by jaydeeprami** [comment]
Hello @mikejolley , @jameskoster ,

I have made a pull request for above issue. Please review from your end and do let me know if any other change.

Below is my pull request URL:
https://github.com/woocommerce/woocommerce/pull/12691

Thanks,
