### ISSUE TITLE
2.7 - JSON changes on Ajax get_customer_details

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#12654]
## EXPLANATION OF THE ISSUE

When loading the client details on the "Load billing address" or "Load shipping address" link on the order screen, before 2.7 the array returned to the `woocommerce_found_customer_details` filter on the `get_customer_details` function would have each field on `$customer_data['billing_field']` or `$customer_data['shipping_field']` keys. From 2.7 the array structure has changed and is now organized in a multidimensional array like `$customer_data['billing']['field'].

This can break any plugin that hooks into the `woocommerce_found_customer_details` filter to add their own custom user meta.

The hability to add custom meta to this array/json object was introduced here: https://github.com/woothemes/woocommerce/commit/5c43b340027fc9dea78e15825f12191768f7d2ed

This change should be documented or, even better, create a new filter and throw a deprecated message on the old one (but still ensure it keeps working by manipulating and feeding it the array with the old structure).

## SYSTEM STATUS REPORT

WooCommerce 2.7 beta 1
WordPress 4.7

**Comment by mikejolley** [comment]
Supporting both is not an option as the JS has to loop this passed data.

**Comment by webdados** [comment]
So we should use the new `woocommerce_ajax_get_customer_details` from 2.7 on, right?

Thanks for the fix.

**Comment by mikejolley** [comment]
Yeah thats correct.
