### ISSUE TITLE
Missing decimal values in Price Filter widget.

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/woocommerce#12652]
Ticket: 509457

When using the WooCommerce Price Filter widget, it's not showing the decimal values of the price at all. Is this by design?

![image](https://cloud.githubusercontent.com/assets/13743465/21337748/a894eb5a-c678-11e6-8fa6-f92b5d9a90c2.png)

(Source: http://cld.wthms.co/blkU/5ko2WS7J)

**Comment by mikejolley** [comment]
Yes. It does not filter by cents, thus does not need to show cents. It rounds to the nearest dollar.

Can you use slack for questions like this unless it's actually confirmed to be a bug please?
