### ISSUE TITLE
Wrong number of products on shop page

### ISSUE THREAD

**Issue by qpidcock** [woocommerce/woocommerce#12657]
TIhe site that I am working with is www.adulttoyoverstock.com (shop page)  The problem is that anytime the page loads it has a random number of products. Ranging from 1 - 22 (most and least I have seen).  That being said I have tried adjusting the product counts time and time again but have had no success.

To reproduce this issue all you need to do is open adulttoyoverstock.com/shop

I am also having some issue with the import settings for product details to filter but I am working on that and doesn't seem to be much of an issue.

**Comment by mikejolley** [comment]
If you're importing products, you've likely imported something incorrectly.

 The 'hide out of stock' setting is very strict when it comes to naming the meta values. Only products with stock_status set to 'outofstock' can be hidden by the actual query.

Check your imported data, or resave products which are hidden on page, but not by the query (if you have less results on a page, you know there is a product affected by this).

Or turn off the 'hide out of stock products' setting.
