### ISSUE TITLE
Coupon with 0 discount gets applied to cart

### ISSUE THREAD

**Issue by dare-devil-arrives** [woocommerce/woocommerce#12655]
## EXPLANATION OF THE ISSUE

When core coupons has 0 discount, than also coupon gets applied on cart page with the success notice. Check here - [https://cl.ly/iV9Y/WC-core-coupon.png](https://cl.ly/iV9Y/WC-core-coupon.png)

Now obviously, no one will create a core coupon with 0 as discount but this affects behaviour of Smart Coupons plugin.
Smart Coupons adds a new discount type as Store Credit. If store credit amount becomes 0, than credit (coupon) is not applied. However, core shows a message of successfully applied coupon.
This causes confusion amongst customers as dual notice appears. Check here - [https://cl.ly/iVyK/WC-smart-coupons.png](https://cl.ly/iVyK/WC-smart-coupons.png)

WooCommerce core should handle 0 discount case. Then I think it will automatically get fixed in Smart Coupons.

## STEPS TO REPRODUCE THE ISSUE

1. Create any core discount coupon with 0 as discount and then try applying that coupon.

2. Create any store credit coupon (Smart Coupons di) with 0 balance and try pp

## BEFORE POSTING YOUR ISSUE

Tested with only latest versions of WooCommerce & Smart Coupons and default WP theme.

**Comment by mikejolley** [comment]
This should not be fixed. Users/developers can use coupon codes for other logic e.g. free gift, which is still technically a 0 value coupon. Blocking this would break such functionality.
