### ISSUE TITLE
REST wc/v1: OAuth signature calculation bug

### ISSUE THREAD

**Issue by neonics** [woocommerce/woocommerce#12660]
I was looking to fetch orders (via the wc/v1 REST endpoint) using the modification date rather than the creation date (which is specified with the 'before' and 'after' parameters), and found out that I can [pass the date_query structure via the 'filter' parameter](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-rest-posts-controller.php#L328):

    [    
        'filter' => [ 'date_query' => [ [
            'column' => 'post_modified',
            'after' => date( 'Y-m-d H:i:s', time() - 3600*24 ),
        ] ] ],
        'page' => $page,
        'per_page' => 20,
    ]

This works just fine. 

However, the OAuth signature check code doesn't handle arrays with more than 1 level of nesting, and a "PHP Notice:  Array to string conversion in" is emitted at [includes/api/class-wc-rest-authentication.php on line 231](https://github.com/woocommerce/woocommerce/blob/2.6.9/includes/api/class-wc-rest-authentication.php#L231) in v2.6.9 (which would be [line 350 in master](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-authentication.php#L350)).
This results in the following string to be used as part of the signature calculation:

    filter%255Bdate_query%255D%3DArray

rather than the strings

    filter%255Bdate_query%255D%255B0%255D%255Bafter%255D%3D2016-12-19%252019%253A31%253A51
    filter%255Bdate_query%255D%255B0%255D%255Bcolumn%255D%3Dpost_modified

**Comment by mikejolley** [comment]
Will review #12661 thanks

**Comment by claudiosanches** [comment]
The `filter` is deprecated, will be removed from WP core and from WooCommerce 2.7 too.

**Comment by neonics** [comment]
What will take it's place? I really need to be able to get posts/orders based on modification time.

**Comment by claudiosanches** [comment]
@neonics anything, will not be available anymore. still you can create custom query params using filters, like you can do using the WP REST API.

**Comment by neonics** [comment]
note: this was finally fixed in #15395
