### ISSUE TITLE
[2.7] Question: Uncaught exceptions thrown when setting object properties

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#12669]
This is more a question regarding a design decision that could have issues in the long run, rather than an "issue" in itself.

Some object property setters are designed to throw exceptions that are only meaningful when:

1) Attempting to save.
2) Caught, of course.

I noticed this while working with a piece of code that does this harmless operation:

`$obj->set_sku( apply_filters( 'xxx', $obj->get_sku( 'edit' ), $a, $b ) );`

The result was a fatal error, at a rather unpredictable place (and for no real reason, since I didn't attempt to save).

I find that a safer pattern would be to store errors somewhere on the object, or validate its props when attempting to save and throw an exception (or return an error object) at that point. 

So perhaps `validate_props()` could return something, or throw the exception? Or `save()` could return an error object obtained by `validate_props()`?

**Comment by mikejolley** [comment]
Thumbs up so I'm assuming thats accepted :)
