### ISSUE TITLE
[2.7] Single order API endpoint doesn't return line item product ID and other values

### ISSUE THREAD

**Issue by bryceadams** [woocommerce/woocommerce#12673]
## EXPLANATION OF THE ISSUE

The product ID in a line item is always `0`.

## STEPS TO REPRODUCE THE ISSUE

1. 2.7
2. Make an API call to a single order
3. See a line item's `product_id` value

I haven't confirmed but presume the same with the `variation_id` column.

Now that I'm looking at it, it seems like most of the values are 0, like `total`, `subtotal`. Here's a line item response on my end:

```
"line_items" => [
       [
         "id" => 4390,
         "name" => "Go Tell It On The Mountain By James Baldwin",
         "product_id" => 0,
         "variation_id" => 0,
         "quantity" => 1,
         "tax_class" => "",
         "subtotal" => "0.00",
         "subtotal_tax" => "0.00",
         "total" => "0.00",
         "total_tax" => "0.00",
         "taxes" => [],
         "meta_data" => [],
         "sku" => "GOTEL56288",
         "price" => 124.4,
         "meta" => [],
       ],
     ],
```

**Comment by mikejolley** [comment]
@bryceadams I replicated your last one, but this report looks invalid. I tried both an order from 2.6 and 2.7 and both returned valid data:

https://dl.dropboxusercontent.com/s/xb33azcl3cl1eyh/2016-12-22%20at%2014.57.png

Can you grab master? It may have been related to https://github.com/woocommerce/woocommerce/pull/12674/files if you created the order through API.

**Comment by bryceadams** [comment]
Cheers :) Seems like a beta-1 issue as it works with master. The order/product/etc. wasn't created through the API though.
