### ISSUE TITLE
CRUD search helpers for orders, coupons and products

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#12677]
## EXPLANATION OF THE ISSUE

With the introduction of the CRUD functions, WooCommerce is preparing itself for database abstraction and, at least at the orders level, it is already decided that sooner or later it will move out from the posts / postmeta tables.

Until now, if we need to get some order based on a meta value, we can use plain SQL or WP_Query (slower) and it works. We will still be able to use that until the orders move out from these tables, but when the change occurs, we'll have to change the SQL queries to match the new tables, and because this new CRUD functions will, on remote scenarios, allow to move the orders/products/etc... out of the WordPress database , a plugin that needs to retrieve orders/products/etc... based on meta values will not be able to do it.

Specific example:
I have a payment gateway that gives the client a "entity", a "reference" and a "value" (order total) that he can use on portuguese ATM machines to pay for the order. Immediately after the order is paid, the portuguese banking system, based on the "entity" and "reference" will make a GET call on a endpoint of the website containing these 3 details plus a secret key.
The plugin will then search the orders for the one that has that "entity", "reference" and after finding it then test the order total and secret key in order to make sure that order should, indeed, be set as paid. Neither the "entity" or "reference" have the order_id on it. These are (and must be) random generated and unique values.

Even if it's not very scalable, I think WooCommerce 2.7 should have the ability to search orders/products/... based on meta values, so we can really abstract our plugins and NOT use SQL and WP_Query on something that can change tables sooner or later.

## SYSTEM STATUS REPORT

WooCommerce 2.7 beta 1
WordPress 4.7

**Comment by TheCrucible** [comment]
I have similar issue. Using the Gravity Forms Product Add On our customer enter a unique serial_number (custom field) with each order (subscription in this case). The value is added as meta_value in SQL but when searching order in dashboard the query won't find the order. It would be hugely helpful if search included meta values. For now we have to use SQL and it's pain in neck.

**Comment by webdados** [comment]
@TheCrucible 

This issue is not about searching an order by meta_value on the dashboard. That you can achieve today if you use the `woocommerce_shop_order_search_fields` filter and add you own field name to the array. (Maybe you won't in the future, but you can today)
Example: https://nicola.blog/2015/03/19/search-orders-by-transaction-id/

This issue is about not being able to, programmatically via php code, get orders based on meta_key/meta_value with the new CRUD functions. We can still use SQL while the orders are stored as post/post_meta but when the data is abstracted completely will lose that ability.

If this is not taken into consideration, a lot of plugins that need to search orders based on a custom field will break.
Example: As I stated on my initial comment, there are offline payment gateways that store specific IDs on the order to be able to identify them later when the payment is really made and some callback URL with that specific ID is called to set the order as paid.

**Comment by mikejolley** [comment]
@justinshreve One you'd like to tackle? I think we'd need a more powerful search method in the data store which takes an array of props - kinda like what we talked about with @coderkevin a while back for the API/s9n. In this data store implementation, it would allow any prop or meta key to be searched on I think.

Overall not sure how viable this is, or how non-performant, but it could probably be done with custom SQL or advanced WP Queries.

Let me know your thoughts and I'll add to next sprint if we want to do it.

**Comment by webdados** [comment]
@mikejolley 

Let me just contribute a little more to this issue:

We all know this will never have a good performance, but nowadays, we can search orders by meta key / value. With the new functions we won't be able to do it. Of course we can still do direct SQL, but if we are abstracting data on WooCommerce, this should be provided by the abstraction layer and not force the developers to go around it.

Thanks for your time.

**Comment by justinshreve** [comment]
@mikejolley Sure, I can tackle this as part of our next sprint.

I think it's a good idea. It might be slower on larger sites, but if we abstracted it out and use it in core, that can allow users to use something like ElasticSearch through a plugin.

**Comment by webdados** [comment]
@justinshreve @mikejolley happy to beta test anything that you might need to be tested, or to further give input on this.

**Comment by justinshreve** [comment]
@mikejolley

After sitting on it for a couple days and giving the "layer on top of WP_Query" route a chance, I'm not totally happy with the implementation -- and there were a few issues since I couldn't touch the underlying SQL.

For a good long term implementation, I think I would rather see a set of well documented classes (not just a search function in the data store) like `WC_Order_Query` and `WC_Product_Query` that could be swapped out if the data is stored somewhere else. Something well defined would let us define the operations that make sense for each prop, and WP_Meta_Query could still be used for a good portion of it (like how WP_User_Query uses Meta_Query for roles as well as custom user meta).

It'll require a bit more work, but long term I think it makes the most sense.

**Comment by webdados** [comment]
@justinshreve 

> that could be swapped out if the data is stored somewhere else

That's exactly one of the reasons the "search by meta" needs to be on the WooCommerce core.

> Something well defined would let us define the operations that make sense for each prop

Please don't forget custom meta data

**Comment by justinshreve** [comment]
After some discussion, we are going to punt this ticket to 2.8 and focus on a more robust set of classes. In the meantime, `wc_get_orders` and `wc_get_products` can be used for some queries, and `WP_Query` can be used for more complex queries (including custom meta). We can document moving from `WP_Query` calls to `WC_*_Query` calls in the future.

**Comment by webdados** [comment]
I just hope this is done before the orders move from post/post_meta to their own custom tables, so the developers have the time to move from WP_Query to WooCoomerce functions/methods.

**Comment by mikejolley** [comment]
This issue has been split into smaller parts spanning a few releases.
