### ISSUE TITLE
Add custom tabs with custom product create hide issues

### ISSUE THREAD

**Issue by Mte90** [woocommerce/woocommerce#12681]
User story: I need a new product type with a specific new product tabs but maintain the General tab available with the pricing fields.

## STEPS TO REPRODUCE THE ISSUE

* Follow that tutorial: http://jeroensormani.com/adding-a-custom-woocommerce-product-type

If you omit the js hack you can see that the general tab is missing in all the product types, in the new one but also in the oldests like the simple product.  
After a bit I discovered that also in the `woocommerce_product_data_tabs` if you change the general tab, adding a new class as example, you need to add `show_if_simple` to put it back when someone change the product type.  
If you look on https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L82 you can see that `show_if_simple` doesn't exist.

So to get working the General tab when someone change the type you need to do:
```php
$tabs['general']['class'] = array( 'show_if_simple','show_if_your_product_type', 'hide_if_grouped' );
```
In that way the General it's working again in the simple product!  

But now we have the problem of the get that available on our product type and you need an improved js hack (respect the tutorial ones):
```javascript
jQuery( '.options_group.pricing' ).removeClass('hidden').addClass( 'show_if_your_product_type' ).addClass('hidden');
```
In that way we can add the `show` also on the general fields but moving the hidden class at the end remove any issues with the cascading order of classes.

As I can see from the original code it's not possible to have actually a filter for the existing tabs and add our custom classes on the fields so the js way is the only available. This is not very good at all because is an hack.

**Comment by Mte90** [comment]
Also when you open the product saved with the product types in the backend this fix also the missing General tab:
```javascript
if(jQuery('#product-type :selected').val() === 'simple_ticket') {
	jQuery('#general_product_data, .general_tab').show()
}
```

**Comment by mikejolley** [comment]
hide_if_x will reveal all existing types and hide the one specified. It's handled here https://github.com/woocommerce/woocommerce/blob/dec792b731dbbea6d34aa3ddcd6a3bf05bf43077/assets/js/admin/meta-boxes-product.js#L136-L139

You just need to ensure the product type term exists (create it on install).

**Comment by Mte90** [comment]
the product type terms exist in `plugins_loaded` so I don't understand what means `on install`.

**Comment by mikejolley** [comment]
If the terms exist, they will be accounted for in our script. By "On install" I meant during plugin activation. Insert the term so it exists and is ready for use.

**Comment by Mte90** [comment]
I am following that tutorial and as you can see use the `plugins_loaded` but I have the problem mentioned and this is the only way that I find to fix it.

**Comment by mikejolley** [comment]
That registers the type but it does not create a term. I didn't write the tutorial.

**Comment by Mte90** [comment]
Uhm so it's missing a step in that tutorial?

**Comment by mikejolley** [comment]
I guess so? Not my tutorial :p

**Comment by Mte90** [comment]
Ok I looked on internet and I don't find the missing part about "insert the term", there is a better documentation about it?
