### ISSUE TITLE
Warning when not set product price

### ISSUE THREAD

**Issue by puleeno** [woocommerce/woocommerce#12686]
![screen shot 2016-12-23 at 3 51 34 pm](https://cloud.githubusercontent.com/assets/3768206/21450280/f66d7836-c927-11e6-9c33-7d467cd7f486.png)

I use woocommerce 2.6.11 but it has some warning in image above, please fix it, thanks so much.

**Comment by mikejolley** [comment]
Hide notices in production in that case. Products cannot be sold without a price. I'll add a workaround but it might not be released until 2.7.
