### ISSUE TITLE
variation selection problem

### ISSUE THREAD

**Issue by mjYin** [woocommerce/woocommerce#12684]
## STEPS TO REPRODUCE THE ISSUE

it's from new woo 2.6.10 version (2.6.9 was good, no problem)
go to the shop page for product with variations(eg, small, medium, big), select the variation other than the default one, you can see price changed, but the variation name not changed.(if default is medium, if you click to choose small, it won't change to small, stay as the default value).

I debugged the problem, it's caused by woocommerce/assets/js/frontend/add-to-cart-variation.js file
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Theme? Might be using a script to make them "pretty" which will need a tweak. No away around this - old version was broken in Firefox.

**Comment by mikejolley** [comment]
So I just tested Divi and a theme with a pretty select box (WooStore) and both functioned perfectly. This has to be a theme issue - maybe they are doing something custom and didn't anticipate the change. Happy to look but without a link I can do squat.

You (and they) can see our notes in https://woocommerce.wordpress.com/2016/12/22/woocommerce-2-6-10-fix-release-notes/ for the reasoning behind the changes.

Since I can not replicate in any of our themes or default themes I'll be closing this, but by all means provide those extra details and I'll look at your site/theme in the morning :)

**Comment by mjYin** [comment]
We're using our custom theme, and old version 2.6.9 is good, no problem, 
new version 2.6.10 got the problem for selecting the variation. and I 
tried to use the add-to-cart-variation.js from 2.6.9 then all good.

**Comment by mikejolley** [comment]
@mjYin still no link? Attributes contain quote characters?

**Comment by mjYin** [comment]
I tested 2.6.10  from my local server, you can't reach it, it won't work 
even from my local, so I didn't put it to our staging server. our live 
site https://www.novosbed.com is using woo 2.6.9, and working fine 
except once a while we got one order missing firmness for our The 
Novosbed mattress, and it only happened after I updated it to 2.6.9.

**Comment by mikejolley** [comment]
You have a 'simpleselect' script which is likely not compatible. I cannot fix anything without seeing a broken instance. Need to see staging.

**Comment by mikejolley** [comment]
Found it. It's not us it's you. SimpleSelect **does not** work with 2.6.9 either. You have some custom code handling the update and calling simpleselect's refreshContents event. You just need to tweak that code to run on the event `woocommerce_update_variation_values`

**Comment by mjYin** [comment]
thanks lot, I am on vacation now, I will look at it when I come back.

**Comment by mjYin** [comment]
thanks agian, it's really SimpleSelect caused the problem, it worked fine with woo version 2.6.9 and earlier.
