### ISSUE TITLE
2.7 Warnings: undefined indexes on saving product meta box

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#12697]
Currently at 539099c7d75e5d54217e069559a4822b31e1b7e0 and seeing the following when saving a product:

> [26-Dec-2016 22:14:29 UTC] PHP Notice:  Undefined index: upsell_ids in D:\Websites\www.sandbox.dev\wp-content\plugins\woocommerce\includes\admin\meta-boxes\class-wc-meta-box-product-data.php on line 280
> [26-Dec-2016 22:14:29 UTC] PHP Notice:  Undefined index: crosssell_ids in D:\Websites\www.sandbox.dev\wp-content\plugins\woocommerce\includes\admin\meta-boxes\class-wc-meta-box-product-data.php on line 281

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/12737
