### ISSUE TITLE
Fatal error : register_setting() with WP 4.6.1

### ISSUE THREAD

**Issue by telilbo** [woocommerce/woocommerce#12699]
## EXPLANATION OF THE ISSUE

Tested WP 4.6.1
Tested WC 2.6.4 and WC 2.6.11

When i update WC, wordpress say's fatal error like this. 
and all wp-admin cannot access. 
error message is like this.

================================
[27-Dec-2016 01:00:49 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function register_setting() in /var/www/vhosts/aaa.com/httpdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php:98
Stack trace:
#0 /var/www/vhosts/aaa.com/httpdocs/wp-includes/plugin.php(524): WC_Admin_Menus->status_menu('')
#1 /var/www/vhosts/aaa.com/httpdocs/wp-admin/includes/menu.php(149): do_action('admin_menu', '')
#2 /var/www/vhosts/aaa.com/httpdocs/wp-admin/menu.php(282): require_once('/var/www/vhosts...')
#3 /var/www/vhosts/aaa.com/httpdocs/wp-admin/admin.php(138): require('/var/www/vhosts...')
#4 /var/www/vhosts/aaa.com/httpdocs/wp-admin/index.php(10): require_once('/var/www/vhosts...')
#5 {main}
  thrown in /var/www/vhosts/aaa.com/httpdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php on line 98
================================

so, i find register_setting()  function. 
but, it's wordpress function since 4.7.
i cannot find register_setting() function 4.6.1.

and also find WC 4.6.7 and WC 4.6.11 
stil use register_setting() in WC. 

BUT github source is different release file like this.

CODE( in status_menu() ) : https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-menus.php

==========================================
	public function status_menu() {
		add_submenu_page( 'woocommerce', __( 'WooCommerce status', 'woocommerce' ),  __( 'System status', 'woocommerce' ) , 'manage_woocommerce', 'wc-status', array( $this, 'status_page' ) );
	}
==========================================

BUT download WC 2.6.11 same code position.

==========================================
	public function status_menu() {
		add_submenu_page( 'woocommerce', __( 'WooCommerce Status', 'woocommerce' ),  __( 'System Status', 'woocommerce' ) , 'manage_woocommerce', 'wc-status', array( $this, 'status_page' ) );
		register_setting( 'woocommerce_status_settings_fields', 'woocommerce_status_options' );
	}
==========================================

register_setting() function is WP 4.7 only. 
could you check this? what source is is collect?

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

========================================
this problem is cannot access wp-admin all page. 
so, cannot find system status menu.
========================================

**Comment by claudiosanches** [comment]
> register_setting() function is WP 4.7 only.

Check this please: https://developer.wordpress.org/reference/functions/register_setting/

`register_settings()` has been introduced in WP 2.7...
So looks like you have a corrupted installation.

**Comment by telilbo** [comment]
Hello.

i know it's since 2.7, but https://wordpress.org/wordpress-4.6.1.zip this file isn't found register_settings() function.

download that link and i check wp-includes/option.php file. 
register_settings() function not found.
i think it's wordpress release mistake.

anyway, okay thanks.

**Comment by claudiosanches** [comment]
This has been introduced since 2013 on WooCommerce and always worked: https://github.com/woocommerce/woocommerce/commit/9c9bfe1f4cc7902f01dc68884484afc646ad8d59
Need to check the package, maybe something missing, still suppose to be part of WordPress since version 2.7.
