### ISSUE TITLE
Unable to get the product price

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#12693]
The WooCommerce Data Base is extremely unfriendly.
I am importing records from the data base to my own system.

I use wp_woocommerce_order_items and wp_woocommerce_order_itemmeta
sadly I can't find anywhere the value of each item.
There is _line_total, and _line_subtotal which both contains the same value.

Why don't you save the price per 1 unit?

What is the difference between _line_subtotal  and _line_total ? 
It doesn't say anything about these in:
https://github.com/woocommerce/woocommerce/wiki/Database-Description

Is it possible to add _item_price which will contain the base price per 1 unit?
For example my products aren't regular, I use plugins to add more options and each option costs some money. I can not trace the price backwards and using division operation ( _line_total / _qty ) gives false results in the cents.

I saw that you are now working on separating the order items to it's own table which is awesome! please consider this issue with it. It is better to save basic price and qty which allows to calculate the "line total" other than what woo commerce is doing now.

**Comment by mikejolley** [comment]
This is not really an 'issue' report is it :) I'll answer your question though.

_line_total = Total cost for the line after discounts.
_line_subtotal = Total cost for the line before discounts.

> Why don't you save the price per 1 unit?

Because thats extra data to keep in sync. And we do rounding per line, not per unit.

Get that by dividing line total by qty.

**Comment by UserName011** [comment]
@mikejolley  there is nothing to sync.. It's just saving the price.
For a very simple query like "what was the price in date X" Woocommerce can not answer.

The more I learn about WooCommerce the more I see that the system isn't functioning like information system. You should save simple data and with data calculate "complected data" not the other way around. You are now working on Orders + Order Items tables - This is something you should take into account.

**Comment by mikejolley** [comment]
> there is nothing to sync.. It's just saving the price.

If you edit an order, or have things recalculated, thats something that needs to be kept in sync, not left as is.
