### ISSUE TITLE
[2.6.11]warning A non-numeric value abstract-wc-product.php on line 940

### ISSUE THREAD

**Issue by MMaKenZi** [woocommerce/woocommerce#12690]
## EXPLANATION OF THE ISSUE
I have a simple product which I didn't enter any price for it, and this error is in products listing below to price column for this product

Warning: A non-numeric value encountered in /home/admin/domains/mysite/public_html/test/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php on line 940 Warning: A non-numeric value encountered in /home/admin/domains/mysite/public_html/test/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php on line 940 –

## STEPS TO REPRODUCE THE ISSUE
Just create a simple product, leave it's price blank, and check whats showing in price field when you are seeing the product in products tab

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://mysite
Site URL: http://mysite
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.1.0
PHP Post Max Size: 64 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.12
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (36) ###

Aparat: توسط Nima Saberi – 1.3
Contact Form 7: توسط Takayuki Miyoshi – 4.6
Email Subscribers & Newsletters: توسط Icegram – 3.2.4
Google Maps Easy: توسط supsystic.com – 1.6.6
Rainmaker- The Best Readymade WP Forms Plugin: توسط icegram – 0.16.1
JC WooCommerce Advanced Attributes: توسط James Collings – 1.5.6
WPBakery Visual Composer: توسط Michael M - WPBakery.com – 5.0
Max Mega Menu: توسط Tom Hemsley – 2.3.2
Merge + Minify + Refresh: توسط Launch Interactive – 1.6.12
Mobile Address Bar Changer: توسط Anshul Labs – 2.0
Postman SMTP: توسط Jason Hendriks – 1.7.2
WooCommerce Product Filter: توسط Mihajlovic Nenad – 6.0.2
WP Real Media Library: توسط Matthias Günter – 2.7
Relevanssi: توسط Mikko Saari – 3.5.6.1
Slider Revolution: توسط ThemePunch – 5.3.1
Secondary Title: توسط Kolja Nolte – 1.9.1
SKT Skill Bar: توسط SKT Themes – 1.4
TinyMCE Advanced: توسط Andrew Ozz – 4.4.3
UpdraftPlus - Backup/Restore: توسط UpdraftPlus.Com
DavidAnderson – 2.12.27.22
WC Product Tabs Plus: توسط WooNinjas – 1.0.0
Custom Price Labels for WooCommerce: توسط Algoritmika Ltd – 2.1.0
WooCommerce Product SKU Generator: توسط SkyVerge – 2.2.0
WooCommerce Wholesale Prices Premium: توسط Rymera Web Co – 1.12.3
WooCommerce Wholesale Prices: توسط Rymera Web Co – 1.2.8
ووکامرس: توسط ووکامرس – 2.6.11
WP-Persian: توسط Siavash Salemi – 2.1.3
WP Rocket: توسط WP Media – 2.9
YITH WooCommerce Compare: توسط YITHEMES – 2.1.0
YITH WooCommerce Wishlist: توسط YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

پایگاه فروشگاه: #37202 - /product/
سبد خرید: #5 - /cart/
تسویه حساب: #6 - /checkout/
حساب کاربری من: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
variation (variation)

### Theme ###

Name: HandyStore
Version: 4.15 (see readme.txt for detailed changelog)
Author URL: http://themes.zone
Child Theme: ❌ – 
WooCommerce Support: ✔

### Templates ###

Overrides: handystore/woocommerce/archive-product.php
handystore/woocommerce/cart/cart.php
handystore/woocommerce/checkout/review-order.php
handystore/woocommerce/content-product.php
handystore/woocommerce/content-widget-product.php
handystore/woocommerce/loop/add-to-cart.php
handystore/woocommerce/loop/loop-start.php
handystore/woocommerce/single-product/product-image.php
handystore/woocommerce/single-product/rating.php

`

**Comment by doubleedesign** [comment]
Seems to be PHP 7.1 related - switching to 7.0.x fixed it for me (7.0.14 in my case) which could be an appropriate workaround for most people for now.

**Comment by MMaKenZi** [comment]
yes, it seems to
I had to back to php 7.0.14 due to some incompatibility between woocommerce, my theme and PHP 7.1

**Comment by bekarice** [comment]
@mikejolley @claudiosanches ran into this one with a couple plugins already -- non-numeric strings are no longer coerced as an integer in PHP 7.1 + warnings are added ([see PHP manual](http://php.net/manual/en/migration71.other-changes.php)) so empty strings / null values must either be cast as `(float)` or checked for `! empty()` before being used in math operations.

**Comment by BackuPs** [comment]
The issue also arrises on shortcodes in wordpress that initiate variable like this

		'paddingtopbottom' =>'5',
		'paddingleftright' =>'15',


If you then try to do something like this

$height=10;
$height=$height+(2*$paddingtopbottom);

You get the same warning.  Now all hasto be changed to

$height=$height+(2*intval($paddingtopbottom));

But shortcodes are build like this [shortcodename paddingtopbottom="10"]  so it will be string all the time.

This is a huge impact on all plugins developers and theme developer.

**Comment by Wanita11** [comment]
I am having the same issue. wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php on line 923. No prices in the product. 
This is the line I have to change. 			$price = $price * $qty;
Any help appreciated.

**Comment by peterfabian** [comment]
@Wanita11 please create a new issue, if you can reproduce this with the latest WooCommerce version and include all the relevant information as outlined in the [self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/).

I cannot see `$price = $price * $qty;` on line 923 in abstract-wc-product.php.

**Comment by OpJePl44tsm4n** [comment]
Got the same error in Woocommerce Version 3.4.5: 

Although this bug needs to be fixed make sure you don't use a productprice like 12,50 but use 12.50
