### ISSUE TITLE
Woocommerce Error (when customer selects a color item)

### ISSUE THREAD

**Issue by FlywebMedia** [woocommerce/woocommerce#12709]
This just started happening yesterday. I changed my price and now when a customer selects a color item, this pops up underneath the item. 

It doesn't prevent the customer from ordering, but it looks horrible right underneath the product when they are about to proceed to the checkout. 

Any information would be helpful. 

{{{+data.variation.variation_description+}}}{{{+data.variation.price_html+}}}{{{+data.variation.availability_html+}}}

Here is a link to the product. Choose Either black, or white and you will see this code above pop up underneath the product. 
Thanks

https://sparkslide.com/product/iphone-66s/

**Comment by mikejolley** [comment]
Looks like someone has messed with one of the template files? Those + should not be there. Unless its a minification plugin.

Not happening now on your site. And it doesn't affect other users so it's site specific.
