### ISSUE TITLE
[2.6.11]warning call_user_func() expects parameter 1 to be a valid callback, no array or string given in  tabs.php on line 43 

### ISSUE THREAD

**Issue by MMaKenZi** [woocommerce/woocommerce#12701]
## EXPLANATION OF THE ISSUE
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, no array or string given in /home/admin/domains/mysite/public_html/wp-content/plugins/woocommerce/templates/single-product/tabs/tabs.php on line 43

## STEPS TO REPRODUCE THE ISSUE
I don't know what exactly repoduce this error, I just saw that in error log

### WordPress Environment ###

Home URL: http://mysite
Site URL: http://mysite
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.14
PHP Post Max Size: 64 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.12
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (36) ###

Aparat: توسط Nima Saberi – 1.3
Contact Form 7: توسط Takayuki Miyoshi – 4.6
Email Subscribers & Newsletters: توسط Icegram – 3.2.4
Google Maps Easy: توسط supsystic.com – 1.6.6
Rainmaker- The Best Readymade WP Forms Plugin: توسط icegram – 0.16.1
JC WooCommerce Advanced Attributes: توسط James Collings – 1.5.6
WPBakery Visual Composer: توسط Michael M - WPBakery.com – 5.0
Max Mega Menu: توسط Tom Hemsley – 2.3.2
Merge + Minify + Refresh: توسط Launch Interactive – 1.6.12
Mobile Address Bar Changer: توسط Anshul Labs – 2.0
Postman SMTP: توسط Jason Hendriks – 1.7.2
WooCommerce Product Filter: توسط Mihajlovic Nenad – 6.0.2
WP Real Media Library: توسط Matthias Günter – 2.7
Relevanssi: توسط Mikko Saari – 3.5.6.1
Slider Revolution: توسط ThemePunch – 5.3.1
Secondary Title: توسط Kolja Nolte – 1.9.1
SKT Skill Bar: توسط SKT Themes – 1.4
TinyMCE Advanced: توسط Andrew Ozz – 4.4.3
UpdraftPlus - Backup/Restore: توسط UpdraftPlus.Com
DavidAnderson – 2.12.27.22
WC Product Tabs Plus: توسط WooNinjas – 1.0.0
Custom Price Labels for WooCommerce: توسط Algoritmika Ltd – 2.1.0
WooCommerce Product SKU Generator: توسط SkyVerge – 2.2.0
WooCommerce Wholesale Prices Premium: توسط Rymera Web Co – 1.12.3
WooCommerce Wholesale Prices: توسط Rymera Web Co – 1.2.8
ووکامرس: توسط ووکامرس – 2.6.11
WP-Persian: توسط Siavash Salemi – 2.1.3
WP Rocket: توسط WP Media – 2.9
YITH WooCommerce Compare: توسط YITHEMES – 2.1.0
YITH WooCommerce Wishlist: توسط YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

پایگاه فروشگاه: #37202 - /product/
سبد خرید: #5 - /cart/
تسویه حساب: #6 - /checkout/
حساب کاربری من: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
variation (variation)

### Theme ###

Name: HandyStore
Version: 4.15 (see readme.txt for detailed changelog)
Author URL: http://themes.zone
Child Theme: ❌ – 
WooCommerce Support: ✔

### Templates ###

Overrides: handystore/woocommerce/archive-product.php
handystore/woocommerce/cart/cart.php
handystore/woocommerce/checkout/review-order.php
handystore/woocommerce/content-product.php
handystore/woocommerce/content-widget-product.php
handystore/woocommerce/loop/add-to-cart.php
handystore/woocommerce/loop/loop-start.php
handystore/woocommerce/single-product/product-image.php
handystore/woocommerce/single-product/rating.php

**Comment by mikejolley** [comment]
Sounds like there is a plugin adding a custom tab to your product pages, but it has setup an invalid or non-existant function callback to display the tab's content. Not a core issue.

> WC Product Tabs Plus: توسط WooNinjas – 1.0.0

**Comment by bestslopedesigns** [comment]
I had the same error, as I was just testing Variable Product settings (T-Shirt sizes...), and I simply left the Description fields blank. Once I entered a description, the error was resolved. Hope that helps.

**Comment by vricop** [comment]
@bestslopedesigns You just saved my day, I'm very grateful, thanks a lot. 🎉🎉🎉🎉🎉

**Comment by bestslopedesigns** [comment]
So glad I could help, @vricop ! It's always nice when it's an easy fix :)

**Comment by itdeed** [comment]
Thanks!! Its save me.
