### ISSUE TITLE
Enhancement: Add filter for required account details fields (account_first_name, etc.)

### ISSUE THREAD

**Issue by florianbepunkt** [woocommerce/woocommerce#12702]
This is a feature suggestion rather than an issue report. But I'll describe my use case for context:

Use case:
I need to change the my account form, so that only the password fields remain. Removing the fields is no problem, but account_first_name, account_last_name and account_email are required fields, so teh validator gives back an error.

I found no hook in the docs to override these fields like there is for the checkout fields.

I can manually remove the validation in https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L194

But a hook would be the preferred approach to this. There seems to be a hook for all manipulating all user data fields except for these account fields. Is this by design / any specific reason for this? Or have I overlooked an existing hook in code and docs?

**Comment by mikejolley** [comment]
Erm you just linked to a filter called `woocommerce_save_account_details_required_fields` which *is* the hook you're requesting :p Use that to remove validation.
