### ISSUE TITLE
[2.7] Variation post titles not synced with parent post title

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#12707]
### EXPLANATION OF THE ISSUE

The output of `WC_Product_Variation::get_name()` can be out of sync with the current parent name / post title.

### STEPS TO REPLICATE

- Create a Variable Product with some variations.
- Save.
- Change the parent product post title and save.
- Call `WC_Product_Variation::get_name()` for one of its children after the change.

Note that `WC_Product_Variation::get_title()` returns the correct, up-to-date parent title.

This affects the accuracy of search results obtained using `WC_AJAX::search_products`.

**Comment by mikejolley** [comment]
See #12754
