### ISSUE TITLE
[2.7] Create variations from all attributes doesn't create any product variations

### ISSUE THREAD

**Issue by decarvalhoaa** [woocommerce/woocommerce#12718]
## EXPLANATION OF THE ISSUE

I'm using the current master, fetched and merged at 29.12 @ 14:00 CET, and WP 4.7. When creating a Variable product - **that was not been saved (Save Draft) or Published** - the _Create variations from all attributes_ doesn't create any product variations

## STEPS TO REPRODUCE THE ISSUE

1. create new variable product.
2. add/create a new custom attribute or select an existing attribute.
3. add 1 or more terms to the attribute.
4. go to Variations tab and choose to "create variations from all attributes"
5. confirm the javascript message that returns 'No variations added'.

If the Product has a saved draft or has been published, this issue is not present.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: https://virtualbox-mageia.carvalho-pc/tlc-dev
Site URL: https://virtualbox-mageia.carvalho-pc/tlc-dev
WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.10 (Mageia) OpenSSL/1.0.2j PHP/5.6.27
PHP Version: 5.6.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.40.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

ALO EasyMail Newsletter: by Alessandro Massasso – 2.9.3
WP Offload S3 Lite: by Delicious Brains – 1.1.4
Amazon Web Services: by Delicious Brains – 1.0.1
Autoptimize: by Frank Goossens (futtta) – 2.1.0
BackWPup: by Inpsyde GmbH – 3.3.4
Contact Form 7: by Takayuki Miyoshi – 4.6
Cookie Notice: by dFactory – 1.2.37
Events Maker: by dFactory – 1.6.12
Homepage Control: by WooThemes – 2.0.2
Loco Translate: by Tim Whitlock – 2.0.10
Maintenance Page: by ThemeGrill – 1.0.8
Polylang: by Frédéric Demarle – 2.0.11
Postman SMTP: by Jason Hendriks – 1.7.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Remove query strings from static resources: by Your WP Expert – 1.3.1
Shariff Wrapper: by Jan-Peter Lambeck & 3UU – 4.3.0
Storefront Parallax Hero Polylang Integration: by Antonio de Carvalho – 1.0.0
Storefront Parallax Hero: by WooThemes – 1.5.4
Storefront Reviews: by WooThemes – 1.0.2
Tipu Scroll To Top: by Zubair Mushtaq – 3.0
WooCommerce: by WooThemes – 2.7.0-beta-1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WP Smush: by WPMU DEV – 2.5.2
WP Overnight Sidekick: by Jeremiah Prummer – 1.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #8 - /en/shop/
Basket: #9 - /en/cart/
Checkout: #10 - /en/checkout/
My account: #11 - /en/my-account/

### Theme ###

Name: Storefront Child Theme
Version: 1.1.0
Author URL: https://github.com/decarvalhoaa
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.6
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child-theme-master/woocommerce/checkout/terms.php
```

**Comment by mikejolley** [comment]
Confirmed.

**Comment by justinshreve** [comment]
I don't have a proper fix yet, but I found the problem @mikejolley. 

In 2.6 you could pass in an array of arguments to wc_get_product and those arguments would get passed to the class. The link variations function did this and passed the product type: https://github.com/woocommerce/woocommerce/blob/5fc88694d211e2e176bded16d7fb95cf6285249e/includes/class-wc-ajax.php#L925

Since `$post_id` at this point is just an auto-draft, 'simple' gets returned without that override. We totally deprecated that override functionality in 2.7. I imagine this could break some other things as well.

We can fix this specific bug by changing the `if ( $product->is_type( 'variable' ) ) {` check in `link_all_variations` to also work if the current post status is "auto-draft".

But we should probably ALSO reintroduce that override behavior. I still think we should deprecate it (and return a notice) -- but it should at least function the same for 2.7 since extensions might be doing this too.

Thoughts?

**Comment by mikejolley** [comment]
Hmm, @justinshreve is it something we should be supporting? I mean, we could just pass that to set_props. The object would remain 'dirty' until saved though.

**Comment by justinshreve** [comment]
I don't like supporting it, but it was supported previously so it depends if we are okay potentially breaking similar use cases. I'm not sure how else that was used except for passing the type.

**Comment by mikejolley** [comment]
See #12762
