### ISSUE TITLE
regular and discounted unit price for ‘form-pay.php’ template

### ISSUE THREAD

**Issue by flaggz** [woocommerce/woocommerce#12715]
## EXPLANATION OF THE ISSUE

Woocommerce version 2.6.11
It is not possible to see regular and discounted unit price for ‘form-pay.php’ template (order manually created in admin page).
Displays as intended in admin 'create order' page but not form-pay.php page

## STEPS TO REPRODUCE THE ISSUE

– Create order in admin page
– Add products
– Change price of one or more row lower than the regular
– Click “Customer payment page ->”
– It is only displayed the discount of the total amount but this way is not clear which product is reduced in price and the client gets confused.
I managed to add the ‘unit price’ column but no way to show the actual ‘paying’ price in ‘form-pay.php’ template.

**Comment by mikejolley** [comment]
The cart/checkout/pay pages do not show pre-discounted prices anywhere. Only the discounted unit price, and total discount for all items.

You'll need to modify our templates to add extra data if needed. This isn't something we wish to add to core.
