### ISSUE TITLE
Order by items on custom field in downloads under my accounts

### ISSUE THREAD

**Issue by genexweb** [woocommerce/woocommerce#12714]
Hi Team Woocommerce,

Is there any Hook/Filter available or any other way to sort items available in downloads in my accounts (logged in user, My Accounts --> Downloads(items visible here)).

Update: I want to show all downloadable items order by custom field (date stored) created for that product not its default order by.

Thanks in advance.

**Comment by mikejolley** [comment]
Not out of the box, but you could always query the downloads yourself and do any such sorting via your own code.
