### ISSUE TITLE
Triggering update_checkout resets credit card fields

### ISSUE THREAD

**Issue by jaschaio** [woocommerce/woocommerce#12713]
## EXPLANATION OF THE ISSUE

I am using the Taxamo Extension, which uses `jQuery( 'body' ).trigger( 'update_checkout' );` upon selecting the Billing Country, entering a VAT number or self declaring the location.

Unfortunately this resets the payment fields (Credit Card Number, Expiration, CVC).

It doesn't matter which Payment Gateway I use, the form fields always get reseted upon triggering `update_checkout`. This is not unique to the Taxamo Extension, as I can deactivate it and just type `jQuery( 'body' ).trigger( 'update_checkout' );` into the Webdeveloper console to reset the fields as well.

## STEPS TO REPRODUCE THE ISSUE

Use Woocommerce with a Payment Gateway that allows Credit Cards (such as Stripe or Braintree), add something to your Cart and go to the Checkout Page.

Once you choose your Payment Method and fill in your Details, trigger `jQuery( 'body' ).trigger( 'update_checkout' );` within the Web Developer Console.

**Comment by jaschaio** [comment]
I tried to solve the problem with the following JavaScript:

    var tmp_card_number;
    var tmp_card_expiry;
    var tmp_card_cvc;

    jQuery(document.body).bind('update_checkout', function () {
        tmp_card_number = jQuery(".wc-credit-card-form-card-number").val();
        tmp_card_expiry = jQuery(".wc-credit-card-form-card-expiry").val();
        tmp_card_cvc    = jQuery(".wc-credit-card-form-card-cvc").val();
    });

    jQuery(document.body).bind('updated_checkout', function () {
        jQuery(".wc-credit-card-form-card-number").val( tmp_card_number );
        jQuery(".wc-credit-card-form-card-expiry").val( tmp_card_expiry );
        jQuery(".wc-credit-card-form-card-cvc").val( tmp_card_cvc );
    });

Not sure if this is a valid and secure way to handle it

**Comment by mikejolley** [comment]
I guess it could be solved with javascript. As long as nothing touches the server it's acceptable.

**Comment by WPprodigy** [comment]
May be worth exploring a deeper solution for this. Gateways can have more than just those three fields (like the save card option). And some other plugin's could be adding fields around there as well (like Mailchimp subscribe).

The shipping selection and T&C's checkbox are remaining saved throughout the refresh so that could be a good place to start. It may be saving to a session though, which wouldn't work for this.

**Comment by mikejolley** [comment]
Closed in favour of #12821 which needs review.
