### ISSUE TITLE
Retrieve a customer's details by email api

### ISSUE THREAD

**Issue by Mwassef** [woocommerce/woocommerce#12711]
## EXPLANATION OF THE ISSUE

 Retrieve a customer's details by (email or search) parameters through api 
returns a null array

## STEPS TO REPRODUCE THE ISSUE

  $Para=['email' => 'example@googlemail.com'];
        print_r($woocommerce->get('customers',$Para));

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
2.7 has an 'args' param which accepts email.

**Comment by Mwassef** [comment]
Sorry for bothering you bit how can i use 2.7 then?

**Comment by mikejolley** [comment]
You cannot until it's released in a month or so.

**Comment by Mwassef** [comment]
Thanks a lot
