### ISSUE TITLE
[2.6.11]Constant Error 500 while updating,Creating and trashing product

### ISSUE THREAD

**Issue by MMaKenZi** [woocommerce/woocommerce#12729]
## EXPLANATION OF THE ISSUE
while I want to update a product, after I do my changes and click on update, it take 2 or 3 seconds and after that it show error 500!
the changed infoes not saved too

I checked server error log but there isn't anything about error 500 in that error log, so i think something is wrong with woocommerce
This is happening also while trying to create new product 
and in some rare cases, it's ok with no error

## STEPS TO REPRODUCE THE ISSUE
Just try to create a product or try to update a product details and click publish or update

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://mysite
Site URL: http://mysite
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.14
PHP Post Max Size: 64 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.12
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. PayPal IPN won't work with your server. Contact your hosting provider. Status code: 403
Remote Get: ❌ wp_remote_get() failed. The WooCommerce plugin updater won't work with your server. Contact your hosting provider. Error: cURL error 6: name lookup timed out

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (39) ###

Advanced Access Manager: by Vasyl Martyniuk  – 3.9.3
Aparat: by Nima Saberi – 1.3
Contact Form 7: by Takayuki Miyoshi – 4.6
Email Subscribers & Newsletters: by Icegram – 3.2.4
Google Maps Easy: by supsystic.com – 1.6.6
Rainmaker - The Best Readymade WP Forms Plugin: by icegram – 0.17
JC WooCommerce Advanced Attributes: by James Collings – 1.5.6
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.0
Max Mega Menu: by Tom Hemsley – 2.3.3
درگاه پرداخت بانک ملت افزونه ووکامرس: by ووکامرس فارسی – 4.0.2
Merge + Minify + Refresh: by Launch Interactive – 1.6.12
Mobile Address Bar Changer: by Anshul Labs – 2.0
Omega Instant Search For WooCommerce: by Omega Commerce LLC – 1.0
Persian Woocommerce Shipping: by MahdiY – 0.8.6
ووکامرس پارسی: by ووکامرس فارسی – 2.6.11
Postman SMTP: by Jason Hendriks – 1.7.2
WooCommerce Product Filter: by Mihajlovic Nenad – 6.0.2
WP Real Media Library: by Matthias Günter – 2.7.2
Slider Revolution: by ThemePunch – 5.3.1
Secondary Title: by Kolja Nolte – 1.9.1
SKT Skill Bar: by SKT Themes – 1.4
TinyMCE Advanced: by Andrew Ozz – 4.4.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.30.22
WC Product Tabs Plus: by WooNinjas – 1.0.0
Custom Price Labels for WooCommerce: by Algoritmika Ltd – 2.1.0
WooCommerce Google Product Feed: by Lee Willis – 6.8.1
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.12.4
WooCommerce Wholesale Prices: by Rymera Web Co – 1.2.8
WooCommerce: by WooThemes – 2.6.11
WP-DBManager: by Lester 'GaMerZ' Chan – 2.78.1
WP-Persian: by Siavash Salemi – 2.1.3
WP Rocket: by WP Media – 2.9.1
YITH WooCommerce Compare: by YITHEMES – 2.1.0
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #37202 - /product/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
variation (variation)

### Theme ###

Name: HandyStore
Version: 4.15 (see readme.txt for detailed changelog)
Author URL: http://themes.zone
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: handystore/woocommerce/archive-product.php
handystore/woocommerce/cart/cart.php
handystore/woocommerce/checkout/review-order.php
handystore/woocommerce/content-product.php
handystore/woocommerce/content-widget-product.php
handystore/woocommerce/loop/add-to-cart.php
handystore/woocommerce/loop/loop-start.php
handystore/woocommerce/single-product/product-image.php
handystore/woocommerce/single-product/rating.php

`

**Comment by mikejolley** [comment]
The error log won't say 'error 500'. It will probably say 'fatal error'. Look for those in order to get a workable error message. Simply not enough information for us to act on this report alone - updates via API and admin are working my side and this is the only report I see.
