### ISSUE TITLE
create variable product rest api does not create all variations, sometimes none variations

### ISSUE THREAD

**Issue by yukuan1988** [woocommerce/woocommerce#12727]
## EXPLANATION OF THE ISSUE

I was trying to publish 20 products in a batch using NodeJS library, all of which are variable. After successful posting, some products has incomplete variations, some products has no variations and thus becomes simple product.

## STEPS TO REPRODUCE THE ISSUE

my request:
{"name":"test product","type":"variable","description":"omitted","attributes":[{"name":"internal_id","visible":false,"options":["12345"]},{"name":"Size","visible":true,"variation":true,"options":["16x20 inch No Frame","A3 30X42Cm No Frame","A4 21X30Cm No Frame","50x70Cm No Frame","8X10 inch No Frame","11X14 inch No Frame","12X16 inch No Frame"]},{"name":"Color","visible":true,"variation":true,"options":["undefined"]}],"images":[{"position":0,"src":"http://mycdn/a.jpg","alt":"test product"},{"position":1,"src":"http://mycdn/a.jpg","alt":"test product"},{"position":2,"src":"http://mycdn/a.jpg","alt":"test product"},{"position":3,"src":"http://mycdn/a.jpg","alt":"test product"},{"position":4,"src":"http://mycdn/a.jpg","alt":"test product"},{"position":5,"src":"http://mycdn/a.jpg","alt":"test product"}],"variations":[{"regular_price":"13.50","on_sale":false,"attributes":[{"name":"Size","option":"16x20 inch No Frame"},{"name":"Color"}]},{"regular_price":"9.75","on_sale":false,"attributes":[{"name":"Size","option":"A3 30X42Cm No Frame"},{"name":"Color"}]},{"regular_price":"7.95","on_sale":false,"attributes":[{"name":"Size","option":"A4 21X30Cm No Frame"},{"name":"Color"}]},{"regular_price":"18.50","on_sale":false,"attributes":[{"name":"Size","option":"50x70Cm No Frame"},{"name":"Color"}]},{"regular_price":"7.50","on_sale":false,"attributes":[{"name":"Size","option":"8X10 inch No Frame"},{"name":"Color"}]},{"regular_price":"8.50","on_sale":false,"attributes":[{"name":"Size","option":"11X14 inch No Frame"},{"name":"Color"}]},{"regular_price":"9.50","on_sale":false,"attributes":[{"name":"Size","option":"12X16 inch No Frame"},{"name":"Color"}]}]}
some information omitted
this product turns to be simple product without any variations

another product:
{"name":"test-a","type":"variable","description":"omitted","attributes":[{"name":"internal_id","visible":false,"options":["31654"]},{"name":"Size","visible":true,"variation":true,"options":["40X50Cm No Frame","50X70Cm No Frame","60X90Cm No Frame","15X20Cm  No Frame","20X25Cm No Frame","A4 21X30Cm No Frame","28X36Cm No Frame","30X40Cm No Frame","A3 30X42Cm No Frame"]},{"name":"Color","visible":true,"variation":true,"options":["Pattern 2","Pattern 3","Full Set","Pattern 1"]}],"images":[{"position":0,"src":"http://mycdn/kf/a.jpg","alt":"test-a"},{"position":1,"src":"http://mycdn/kf/a.jpg","alt":"test-a"},{"position":2,"src":"http://mycdn/kf/a.jpg","alt":"test-a"}],"variations":[{"regular_price":"14.50","on_sale":false,"attributes":[{"name":"Size","option":"40X50Cm No Frame"},{"name":"Color","option":"Pattern 2"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"14.50","on_sale":false,"attributes":[{"name":"Size","option":"40X50Cm No Frame"},{"name":"Color","option":"Pattern 3"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"41.95","on_sale":false,"attributes":[{"name":"Size","option":"40X50Cm No Frame"},{"name":"Color","option":"Full Set"}]},{"regular_price":"18.50","on_sale":false,"attributes":[{"name":"Size","option":"50X70Cm No Frame"},{"name":"Color","option":"Pattern 1"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"18.50","on_sale":false,"attributes":[{"name":"Size","option":"50X70Cm No Frame"},{"name":"Color","option":"Pattern 2"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"18.50","on_sale":false,"attributes":[{"name":"Size","option":"50X70Cm No Frame"},{"name":"Color","option":"Pattern 3"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"53.95","on_sale":false,"attributes":[{"name":"Size","option":"50X70Cm No Frame"},{"name":"Color","option":"Full Set"}]},{"regular_price":"25.50","on_sale":false,"attributes":[{"name":"Size","option":"60X90Cm No Frame"},{"name":"Color","option":"Pattern 1"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"25.50","on_sale":false,"attributes":[{"name":"Size","option":"60X90Cm No Frame"},{"name":"Color","option":"Pattern 2"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"25.50","on_sale":false,"attributes":[{"name":"Size","option":"60X90Cm No Frame"},{"name":"Color","option":"Pattern 3"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"59.00","on_sale":false,"attributes":[{"name":"Size","option":"60X90Cm No Frame"},{"name":"Color","option":"Full Set"}]},{"regular_price":"6.75","on_sale":false,"attributes":[{"name":"Size","option":"15X20Cm  No Frame"},{"name":"Color","option":"Pattern 1"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"6.75","on_sale":false,"attributes":[{"name":"Size","option":"15X20Cm  No Frame"},{"name":"Color","option":"Pattern 2"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"6.75","on_sale":false,"attributes":[{"name":"Size","option":"15X20Cm  No Frame"},{"name":"Color","option":"Pattern 3"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"18.50","on_sale":false,"attributes":[{"name":"Size","option":"15X20Cm  No Frame"},{"name":"Color","option":"Full Set"}]},{"regular_price":"7.50","on_sale":false,"attributes":[{"name":"Size","option":"20X25Cm No Frame"},{"name":"Color","option":"Pattern 1"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"7.50","on_sale":false,"attributes":[{"name":"Size","option":"20X25Cm No Frame"},{"name":"Color","option":"Pattern 2"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"7.50","on_sale":false,"attributes":[{"name":"Size","option":"20X25Cm No Frame"},{"name":"Color","option":"Pattern 3"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"20.95","on_sale":false,"attributes":[{"name":"Size","option":"20X25Cm No Frame"},{"name":"Color","option":"Full Set"}]},{"regular_price":"7.95","on_sale":false,"attributes":[{"name":"Size","option":"A4 21X30Cm No Frame"},{"name":"Color","option":"Pattern 1"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"7.95","on_sale":false,"attributes":[{"name":"Size","option":"A4 21X30Cm No Frame"},{"name":"Color","option":"Pattern 2"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"7.95","on_sale":false,"attributes":[{"name":"Size","option":"A4 21X30Cm No Frame"},{"name":"Color","option":"Pattern 3"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"21.95","on_sale":false,"attributes":[{"name":"Size","option":"A4 21X30Cm No Frame"},{"name":"Color","option":"Full Set"}]},{"regular_price":"8.95","on_sale":false,"attributes":[{"name":"Size","option":"28X36Cm No Frame"},{"name":"Color","option":"Pattern 1"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"8.95","on_sale":false,"attributes":[{"name":"Size","option":"28X36Cm No Frame"},{"name":"Color","option":"Pattern 2"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"8.95","on_sale":false,"attributes":[{"name":"Size","option":"28X36Cm No Frame"},{"name":"Color","option":"Pattern 3"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"24.95","on_sale":false,"attributes":[{"name":"Size","option":"28X36Cm No Frame"},{"name":"Color","option":"Full Set"}]},{"regular_price":"9.50","on_sale":false,"attributes":[{"name":"Size","option":"30X40Cm No Frame"},{"name":"Color","option":"Pattern 1"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"9.50","on_sale":false,"attributes":[{"name":"Size","option":"30X40Cm No Frame"},{"name":"Color","option":"Pattern 2"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"9.50","on_sale":false,"attributes":[{"name":"Size","option":"30X40Cm No Frame"},{"name":"Color","option":"Pattern 3"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"26.95","on_sale":false,"attributes":[{"name":"Size","option":"30X40Cm No Frame"},{"name":"Color","option":"Full Set"}]},{"regular_price":"9.75","on_sale":false,"attributes":[{"name":"Size","option":"A3 30X42Cm No Frame"},{"name":"Color","option":"Pattern 1"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"9.75","on_sale":false,"attributes":[{"name":"Size","option":"A3 30X42Cm No Frame"},{"name":"Color","option":"Pattern 2"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"9.75","on_sale":false,"attributes":[{"name":"Size","option":"A3 30X42Cm No Frame"},{"name":"Color","option":"Pattern 3"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]},{"regular_price":"27.50","on_sale":false,"attributes":[{"name":"Size","option":"A3 30X42Cm No Frame"},{"name":"Color","option":"Full Set"}]},{"regular_price":"14.50","on_sale":false,"attributes":[{"name":"Size","option":"40X50Cm No Frame"},{"name":"Color","option":"Pattern 1"}],"image":[{"src":"http://mycdn/kf/a.jpg","position":0}]}]}

this product is supposed to have 36 variations, only 10 variations remain.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://www.omitted.com
Site URL: http://www.omitted.com
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.24
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (30) ###

Adding CSS: by iLen – 1.0
SMTP by BestWebSoft: by BestWebSoft – 1.0.7
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

CKEditor for WordPress: by CKSource – 4.5.3.3
Contact Form by BestWebSoft: by BestWebSoft – 4.0.2
Enhanced Media Library: by wpUXsolutions – 2.3.1
Footer Putter: by Russell Jamieson – 1.14.1
Google Captcha (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.26
Homepage Control: by WooThemes – 2.0.2
miniOrange 2 Factor Authentication: by miniOrange – 4.2.10
WooCommerce Order Export and More: by JEM Plugins – 1.2.4
Pin It Button for Pinterest: by Pinterest – 1.0
WP REST API - filter fields: by Stephan van Rooij – 1.0.1
Text Blocks: by Hal Gatewood – 1.5.1
Simple Page Sidebars: by Cedaro – 1.2.0
WooCommerce Direct Checkout: by Terry Tsang – 1.1.2
WooCommerce - Store Exporter: by Visser Labs – 1.8.6
Woocommerce featured product categories: by Lamvt - Vu Thanh Lam – 3.9.1
WooCommerce Grid / List toggle: by jameskoster – 1.0.0
Booster for WooCommerce: by Algoritmika Ltd – 2.5.5
WooCommerce Order Notes Window: by Rene Puchinger – 1.0.1
Woocommerce Products Designer: by ORION – 2.2
WOOF - WooCommerce Products Filter: by realmag777 – 1.1.5.1
WooCommerce Simply Order Export: by Ankit Gade – 2.0.7
WooCommerce Social Buttons: by Vivacity Infotech Pvt. Ltd. – 1.0.3
WooCommerce: by WooThemes – 2.6.11
WP Log Viewer: by Maxwell Berkel – 1.0.7
WP REST API Log: by Pete Nelson – 1.2.0
WPB WooCommerce Product slider: by wpbean – 2.0
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)


### Theme ###

Name: Shop Isle
Version: 1.1.6.4 – 1.1.6.15 is available
Author URL: http://themeisle.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

when i retry one of the failed products, it would succeed. All variations are created without any error.

**Comment by claudiosanches** [comment]
Without the entire JSON it's hard to say what is wrong.
Like:

```json
    {
      "name": "Color",
      "visible": true,
      "variation": true,
      "options": [
        "undefined"
      ]
    }
```

This for sure will generate wrong results.

But you should try enable the WP_DEBUG and log: https://codex.wordpress.org/Debugging_in_WordPress#Example_wp-config.php_for_Debugging
So you can check if some warning or fatal error is happening and stopping to create all variations.

But from my tests looks that works fine.
