### ISSUE TITLE
[2.7] Select2 doesn't POST empty arrays

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#12725]
## EXPLANATION OF THE ISSUE

Due to the Select2 change to remove hidden inputs, the `initSelection` is no longer used. As a result, if the ajax product search is blank / empty, this means it's not posting an empty array to include an initial value for that field in the `$_POST` data.

This results in `Undefined index` notices being thrown anywhere the ajax product search is used.

## STEPS TO REPRODUCE THE ISSUE

1. Go to edit a coupon. 
2. Ensure the product IDs / exclude IDs fields are blank
3. Save the coupon; note undefined index errors for these values (I wasn't able to see why, everything I saw indicated `name` prop has to be set, which is done correctly).
4. Now go to edit a product.
5. Ensure cross sells / upsells are empty.
6. Save and see similar notices for this $_POST data not being set.

I thought to add `isset()` checks to the POSTed data before saving, but I think this should be an option we set on the product search select2 itself since it's a departure from previous behavior and used a fair bit in extensions a well. Not familiar enough with the new select2 update to do this one myself :)

## SYSTEM STATUS REPORT

On new WC install with PHP 7.1 and Twenty Seventeen, no other plugins besides a dev helper.

**Comment by mikejolley** [comment]
This cannot be helped without outputting extra dummy elements. Hidden inputs post an empty string value, but multi-select elements only POST when something is selected. This is not something specific to select2, but to multi-select boxes.

The correct way to deal with this is to have an isset in your code handling the POST and to then set the value as an empty array if not set. [I'll add to our notes](https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-2.7.x-Developer-Migration-Notes).

**Comment by franticpsyx** [comment]
@mikejolley Undefined PHP notices still need fixing in WC core, though.

**Comment by bekarice** [comment]
@franticpsyx @mikejolley i had them fixed on my end already, about to submit a PR

**Comment by mikejolley** [comment]
I missed those. I'll wait for PR :)
