### ISSUE TITLE
Able to add variable product to cart without any variation selected.

### ISSUE THREAD

**Issue by kartikparmar** [woocommerce/woocommerce#12721]
Created variable product with two attributes and its values.
Screenshot: http://screencast.com/t/CnGv0YGJTa2X

On the front end of the product, Add to Cart button is disabled and even though I can click on it and product(without any variations) will get added to the cart.
Screenshot: http://screencast.com/t/AtQ8kda0e
Screenshot: http://screencast.com/t/OyTz6xyhK18

**Comment by mikejolley** [comment]
Confirmed. It's clickable after attributes are cleared too.
