### ISSUE TITLE
Syncing Error

### ISSUE THREAD

**Issue by TouchMeDeeply** [woocommerce/woocommerce#12724]
## EXPLANATION OF THE ISSUE

I am receiving a Sync error via ThePrintful - Received error: You do not have permission to read the orders count. I have contacted them and they think the error is via WooCommerce permission settings. I'm not seeing any permission settings. We have done a test order via our site. The order is not submitted to ThePrintful after placing order. 
`
### WordPress Environment ###

Home URL: http://www.rainbowrevolution.co
Site URL: http://www.rainbowrevolution.co
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.8-0ubuntu0.16.04.3
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (16) ###

Admin Menu Tree Page View: by Pär Thernström – 2.6.9
Code Snippets: by Shea Bunge – 2.7.2
Contact Form 7: by Takayuki Miyoshi – 4.5.1
Custom Login: by Austin Passy – 3.2.5
Multiple Themes: by David Gewirtz – 7.1.1
Login LockDown: by Michael VanDeMar – v1.7.1
MailChimp for WordPress: by ibericode – 4.0.7
Patreon Button, Widgets and Plugin by CodeBard: by CodeBard – 1.0.5
Stripe Payment Gateway for WooCommerce ( Basic ): by ExtensionHawk – 1.0.8
PHP Compatibility Checker: by WP Engine – 1.3.1
Post Type Switcher: by John James Jacoby – 3.0.0
Printful Integration for WooCommerce: by Printful – 1.2.6
Instagram Feed WD: by WebDorado – 1.1.16
WooCommerce: by WooThemes – 2.6.8
Yoast SEO: by Team Yoast – 3.8
WP Instagram Widget: by Scott Evans – 1.9.8

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #51 - /
Cart: #59 - /cart/
Checkout: #60 - /checkout/
My Account: #61 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Storefront
Version: 2.1.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
I think they may be referring to your API user/keys. There is no error here I can see - API endpoints are working on my sites.
