### ISSUE TITLE
wc_let_to_num() seems broken

### ISSUE THREAD

**Issue by AnthonyIacono** [woocommerce/woocommerce#12726]
## EXPLANATION OF THE ISSUE

If you look at the implementation of wc_let_to_num(), you will notice that the function is supposed to convert a PHP.ini value representing a size (ie: 2M, 2G, or 2P) into the number of bytes it represents. The values used for each of the possible cases (ie: 'M', 'P', 'G', 'T') do not seem to be correct.

## STEPS TO REPRODUCE THE ISSUE

Simply set a value of 2G inside your PHP.ini for memory_limit, and Woocommerce will produce the incorrect value for wc_let_to_num().

## SYSTEM STATUS REPORT

I don't think this is necessary.

**Comment by mikejolley** [comment]
Have you looked at test_wc_let_to_num? Unit tests pass.

2G comes back as 2147483648

Check that using http://www.matisse.net/bitcalc/?input_amount=2147483648&input_units=bytes&notation=legacy
