### ISSUE TITLE
Can't remove_action For Membership Restrictions Message

### ISSUE THREAD

**Issue by strategicmedia** [woocommerce/woocommerce#12723]
## EXPLANATION OF THE ISSUE
To begin: Great plugin and extensions! My company uses WooCommerce for all of our eCommerce websites and we encourage new clients to switch to your platform when we sign them up!

I have a Membership preventing a product from being purchased until the membership is granted manually. I am attempting to move the restriction message further up on the page. Right now, the message appears at the bottom of the "short description" (below "Add to Cart).

I am wanting this message to appear just above OR just below the product title. I know that I need to remove the action associated with populating this message, but I can't seem to accomplish this because it's in a class Function.

This is the function used to create this message:
```
class WC_Memberships_Restrictions {
	public function __construct() {

        // show product purchasing restriction message
	add_action( 'woocommerce_single_product_summary', array( $this, 'single_product_purchasing_restricted_message' ), 30 );
	}
}
```

This is what I've been working on based on tips I've seem around GitHub and StackExchange:
```
function removeit(){
$my_class = new WC_Memberships_Restrictions();
global $my_class;
remove_action( 'woocommerce_single_product_summary', array( $my_class, 'single_product_purchasing_restricted_message' ), 30 );
}
```
What am I missing here?

**Comment by mikejolley** [comment]
`$my_class` is a different instance to the main WC_Memberships_Restrictions class. See if Memberships has a global you can use instead? e.g. (not tested)

`
wc_memberships()->restrictions
`

instead of $my_class

You should post to the support area anyhow if you need further help - this is the core issue tracker.
