### ISSUE TITLE
Shipping shows on checkout before address entered

### ISSUE THREAD

**Issue by jas8522** [woocommerce/woocommerce#12735]
## EXPLANATION OF THE ISSUE

As the title states, despite "Hide shipping costs until an address is entered" being checked.

Please see my comment on closed issue #11650 

I think this one should be closed and that one re-opened as it has more information about the issue. But I'll leave that to the mods. I've detailed exactly how the issue came about and why I think either the setting needs to have a name change or there should be a change in behaviour.

**Comment by claudiosanches** [comment]
Please don't open issues just to bump another issue.
