### ISSUE TITLE
Backorders not working how they should - Variable products

### ISSUE THREAD

**Issue by jzmwebdevelopment** [woocommerce/woocommerce#12731]
I have a product that is set up as per the screenshots however it seems that it can still be ordered.  Why?  Everything is set up correctly

1. https://www.dropbox.com/s/dyr4al8slswclup/Screenshot%202017-01-02%2018.50.57.png?dl=1
2.https://www.dropbox.com/s/yvtuzq2j77q91p8/Screenshot%202017-01-02%2018.51.44.png?dl=1

System Report:

WordPress Environment
Home URL:		http://domain.co.nz
Site URL:		http://domain.co.nz
WC Version:		2.6.11
Log Directory Writable:		 /home/website/public_html/wp-content/uploads/wc-logs/
WP Version:		4.7
WP Multisite:		–
WP Memory Limit:		256 MB
WP Debug Mode:		–
WP Cron:		
Language:		en_US
Server Environment
Server Info:		Apache/2.2.31 (Unix) mod_ssl/2.2.31 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version:		5.6.28
PHP Post Max Size:		8 MB
PHP Time Limit:		30
PHP Max Input Vars:		1000
cURL Version:		7.36.0, OpenSSL/1.0.1e
SUHOSIN Installed:		–
Max Upload Size:		2 MB
Default Timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte String:		
Remote Post:		
Remote Get:		
Database
WC Database Version:		2.6.11
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
Active Plugins (27)
Analytics Tracker	 	by Valeriu Tihai – 1.0.5
BackWPup	 	by Inpsyde GmbH – 3.3.4
Simple Custom CSS and JS	 	by Diana Burduja – 2.9
Disable Comments	 	by Samir Shah – 1.6
Heartbeat Control	 	by Jeff Matson – 1.0.3
WPBakery Visual Composer	 	by Michael M - WPBakery.com – 4.11.2.1
LEE Framework	 	by Derry Vu – 1.1
Ninja Forms	 	by The WP Ninjas – 3.0.20
Products Purchase Price for Woocommerce	 	by Softedge – 1.0.4
Regenerate Thumbnails	 	by Alex Mills (Viper007Bond) – 2.2.6
Taxonomy Metadata	 	by mitcho (Michael Yoshitaka Erlewine), sirzooro – 0.5
Category Order and Taxonomy Terms Order	 	by Nsp-Code – 1.4.9
Woo Checkout Field Editor Pro	 	by ThemeHiGH – 1.1.3
WooCommerce - Country Based Payments	 	by Ivan Paulin – 1.1.5
WooCommerce Payment Express Gateway	 	by OPMC – 2.2
WooCommerce PDF Invoices & Packing Slips	 	by Ewout Fernhout – 1.5.38
WooCommerce Points and Rewards	 	by WooThemes – 1.5.13
WooCommerce Smart Coupons	 	by WooThemes – 3.1.7 – 3.1.8 is available
WooCommerce	 	by WooThemes – 2.6.11
WooSidebars	 	by WooThemes – 1.4.3
WooCommerce Helper	 	by WooCommerce – 1.7.2
Yoast SEO	 	by Team Yoast – 4.0.2
WP Instagram Widget	 	by Scott Evans – 1.9.8
WP Migrate DB	 	by Delicious Brains – 0.9.2
WP Staging	 	by WP-Staging, René Hermenau – 1.1.2
YITH WooCommerce Custom Order Status	 	by YITHEMES – 1.0.8
YITH WooCommerce Wishlist	 	by YITHEMES – 2.0.16
Settings
Force SSL:		–
Currency		NZD ($)
Currency Position		left
Thousand Separator		,
Decimal Separator		.
Number of Decimals		2
API
API Enabled:		
WC Pages
Shop Base:		#7458 - /shop/
Cart:		#7454 - /shopping-cart/
Checkout:		#7452 - /checkout/
My Account:		#7442 - /my-account/
Taxonomies
Product Types:	 	simple (simple), grouped (grouped), variable (variable), external (external)
Theme
Name:		Nation
Version:		1.2
Author URL:		http://themeforest.net/user/raybreaker
Child Theme:		
Parent Theme Name:		Nation
Parent Theme Version:		1.2
Parent Theme Author URL:		http://themeforest.net/user/raybreaker
WooCommerce Support:		
Templates
Overrides (WooCommerce):	 	altotheme/woocommerce/archive-product.php, 
altotheme/woocommerce/cart/cart-totals.php, 
altotheme/woocommerce/cart/cart.php, 
altotheme/woocommerce/cart/cross-sells.php, 
altotheme/woocommerce/checkout/form-checkout.php, 
altotheme/woocommerce/content-product.php, 
altotheme/woocommerce/content-product_cat.php, 
altotheme/woocommerce/content-single-product.php, 
altotheme/woocommerce/content-widget-product.php, 
altotheme/woocommerce/global/breadcrumb.php, 
altotheme/woocommerce/global/quantity-input.php, 
altotheme/woocommerce/global/wrapper-end.php, 
altotheme/woocommerce/global/wrapper-start.php, 
altotheme/woocommerce/loop/loop-end.php, 
altotheme/woocommerce/loop/loop-start.php, 
altotheme/woocommerce/loop/orderby.php, 
altotheme/woocommerce/loop/pagination.php, 
altotheme/woocommerce/loop/rating.php, 
altotheme/woocommerce/loop/sale-flash.php, 
altotheme/woocommerce/myaccount/form-login.php, 
altotheme/woocommerce/notices/error.php, 
altotheme/woocommerce/notices/success.php, 
altotheme/woocommerce/single-product/add-to-cart/grouped.php, 
altotheme/woocommerce/single-product/add-to-cart/simple.php, 
altotheme/woocommerce/single-product/add-to-cart/variable.php, 
altotheme/woocommerce/single-product/price.php, 
altotheme/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 2.6.3, 
altotheme/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 2.6.3, 
altotheme/woocommerce/single-product/related.php, 
altotheme/woocommerce/single-product/review.php, 
altotheme/woocommerce/single-product/sale-flash.php, 
altotheme/woocommerce/single-product/share.php, 
altotheme/woocommerce/single-product/short-description.php, 
altotheme/woocommerce/single-product/tabs/additional-information.php, 
altotheme/woocommerce/single-product/tabs/description.php, 
altotheme/woocommerce/single-product/tabs/tabs.php, 
altotheme/woocommerce/single-product/title.php, 
altotheme/woocommerce/single-product-reviews.php, 
altotheme/woocommerce/single-product.php
 	 	Learn how to update outdated templates

**Comment by mikejolley** [comment]
> Everything is set up correctly

How can you be sure? For one thing, if you're managing stock at variation level, you don't need to enabled at product level.

I tested based on your screenshots and I could not add the variation to cart. It's unavailable.

I suspect 1 of 2 things;

1. You are actually matching a different variation that does have stock or backorders
2. You have an extension bypassing the validation ran during cart/checkout.

Closing this as I was unable to replicate an issue. Feel free to reply anyhow.
