### ISSUE TITLE
[2.7] Featured Extensions Listing needs price updates

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#12739]
The extension prices listed on the "Extensions" page are pulled from `https://d3t0oesq8995hv.cloudfront.net/add-ons/featured.json` and are incorrect, that file needs to be updated. 

Here are the correct prices: http://cloud.skyver.ge/2C44430q3T31

**Comment by warrendholmes** [comment]
@bekarice I've regenerated the file -- it might take some time to get to cloudfront. Will check in a while to see if its updated correctly.

**Comment by warrendholmes** [comment]
Doesn't look like regenerating this helped ... I've opened an issue on our repo about this.

**Comment by mikejolley** [comment]
Thanks @warrendholmes 👍

**Comment by belcherj** [comment]
This has been fixed. Let me know if the issue is still not resolved.
