### ISSUE TITLE
[2.7] PHP 7.1 Compatibility issues

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#12748]
Related to #12690, there are different places in 2.7 that need fixed too. I thought a solution for 2.7 would be to cast amounts and such to float when returning from `get_` functions, but I think we check for empty strings in certain areas -- so we need to track them down. 

I get some errors on the order details screen, or when applying a coupon.

**Comment by franticpsyx** [comment]
Not sure if this is what is implied, but casting all decimal/empty-value `get_` functions to `float` and disallowing an empty string may cause issues in cases where an empty string is a valid (expected) value. Product weight and price are 2 examples. No defined weight is different than 0.0, and similarly no defined price (product not purchasable) is different than 0.0.

(Apologies if I'm just trolling here.)

**Comment by justinshreve** [comment]
No worries, that's what I meant 😄. There are quite a few places where we expect an empty string which is different then 0 .

**Comment by justinshreve** [comment]
I've submitted a PR fixing the ones I've found so far. I did some testing this morning to try to uncover errors. We should probably keep this issue open during further core and extension testing since we might come across more.

**Comment by mikejolley** [comment]
I've enabled 7.1 code coverage on Travis to check this. It was allowed to fail before.
