### ISSUE TITLE
Cart skipped when Simple and Subscription products not allowed together

### ISSUE THREAD

**Issue by TheCrucible** [woocommerce/woocommerce#12740]
Repeatable bug. Under Settings tab and Subscriptions settings, there is a checkbox to allow or disallow purchase of subscriptions and physical products together, when the box us un-checked, the CART page is skipped during checkout. When the box is checked (allowing both to be purchased) works just fine. Watch this video I show you exact steps.

http://www.screencast.com/t/P6Kgin0PZ

The visitor should have chance to review and amend the cart before going to checkout page in both cases.

Version: 2.6.11

**Comment by claudiosanches** [comment]
Looks like a Subscriptions bug, please open a ticket in: https://woocommerce.com/my-account/tickets/
