### ISSUE TITLE
Possible wrong context in has_enough_stock()

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#12755]
I was talking to @mattyza about my suffix issue and came across the `has_enough_stock()` method in the product class. Should `get_stock_quantity()` be the default "view" context here? Or should it be "edit"? 

```
public function has_enough_stock( $quantity ) {
        return ! $this->managing_stock() || $this->backorders_allowed() || $this->get_stock_quantity() >= $quantity;
    }
```

**Comment by mikejolley** [comment]
View is correct context here because it then allows the value to be filtered by devs, if you for example want that based on a custom amount rather than the stored amount.

**Comment by mattyza** [comment]
@mikejolley - I believe the use case is when one wants to filter only the displayed value, or to filter the non-display value (ie: the raw number). The latter isn't really catered for, from what I can see.

In the code snippet above, the value defaults to "view" which could create issues if filtering that value to add extra text in front or behind it, for example. The logic in the `get_stock_quantity()` method assumes that only an integer or float would ever be output.

@helgatheviking

**Comment by mikejolley** [comment]
@mattyza not an acceptable use case tbh. Other checks expect it to be numeric. See answer in https://github.com/woocommerce/woocommerce/issues/12753

**Comment by mattyza** [comment]
@mikejolley sure. Perhaps it's worth having an easy way to filter all the areas where it would be displayed. @helgatheviking - do you have a list of where you're looking to output a modified quantity string?

**Comment by helgatheviking** [comment]
@mattyza not a full list, but the cart error messages are my primary interest. See my [PR](https://github.com/woocommerce/woocommerce/pull/12756)
