### ISSUE TITLE
Create/Update of product tags is not working

### ISSUE THREAD

**Issue by digitalsecure** [woocommerce/woocommerce#12752]
## EXPLANATION OF THE ISSUE

Version information:

~$ wp --info
PHP binary:	/usr/bin/php7.0
PHP version:	7.0.8-0ubuntu0.16.04.3
php.ini used:	/etc/php/7.0/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/home/usera/.wp-cli/packages/
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	1.1.0-alpha-623eb9b

## STEPS TO REPRODUCE THE ISSUE

wp wc product create --path=/path/to/wp --title="Test Product" --tags="Test Tag1"

The product "Test Product" is created successfully.
However, the tag was not generated along with the product when viewed using the Wordpress dashboard --> Woocommerce --> Products --> Products

I have to manually add the tags "Test Tag1" to the product edit page, update and when I perform the wp wc product list --fields=id,tags the tag shows up in the output.

Is this a known bug and will there be a fix soon?

Thank you.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.0.8-0ubuntu0.16.04.3
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.16
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (9) ###

Breadcrumb NavXT: by John Havlik – 5.6.0
Contact Form 7: by Takayuki Miyoshi – 4.6
Neighborhood Demo Content: by Swift Ideas – 2.1
oAuth Twitter Feed for Developers: by Storm Consultancy (Liam Gladdy) – 2.2.1
Slider Revolution: by ThemePunch – 5.3.1
Fast Secure Contact Form: by Mike Challis
Ken Carlson – 4.0.45

Woocommerce CSV Import: by Allaerd Mensonides – 3.3.0
WooCommerce: by WooThemes – 2.6.11
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My Account: #10 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Neighborhood Child Theme
Version: 1.0
Author URL: http://www.swiftideas.net
Child Theme: ✔
Parent Theme Name: Neighborhood
Parent Theme Version: 3.4.31
Parent Theme Author URL: http://www.swiftideas.net
WooCommerce Support: ✔

### Templates ###

Overrides: neighborhood/woocommerce/archive-product.php
neighborhood/woocommerce/cart/cart-empty.php
neighborhood/woocommerce/cart/cart-totals.php
neighborhood/woocommerce/cart/cart.php
neighborhood/woocommerce/cart/cross-sells.php
neighborhood/woocommerce/checkout/form-billing.php
neighborhood/woocommerce/checkout/form-checkout.php
neighborhood/woocommerce/checkout/form-shipping.php
neighborhood/woocommerce/checkout/thankyou.php
neighborhood/woocommerce/content-product.php
neighborhood/woocommerce/content-product_cat.php
neighborhood/woocommerce/content-single-product.php
neighborhood/woocommerce/global/quantity-input.php
neighborhood/woocommerce/loop/loop-end.php
neighborhood/woocommerce/loop/loop-start.php
neighborhood/woocommerce/loop/result-count.php
neighborhood/woocommerce/myaccount/form-login.php
neighborhood/woocommerce/single-product/meta.php
neighborhood/woocommerce/single-product/price.php
neighborhood/woocommerce/single-product/product-image.php
neighborhood/woocommerce/single-product/product-thumbnails.php
neighborhood/woocommerce/single-product/related.php
neighborhood/woocommerce/single-product/tabs/additional-information.php
neighborhood/woocommerce/single-product/tabs/description.php
neighborhood/woocommerce/single-product/tabs/tabs.php
neighborhood/woocommerce/single-product/up-sells.php
neighborhood/woocommerce/single-product.php
neighborhood/woocommerce/taxonomy-product_cat.php
neighborhood/woocommerce/taxonomy-product_tag.php

`

**Comment by mikejolley** [comment]
Looking at the old CLI code, it expects a comma separated list of tag IDs, not words. No plans to fix or change that in 2.6, because 2.7 has a new CLI https://woocommerce.wordpress.com/2016/12/12/2-7-a-new-cli-for-woocommerce/
