### ISSUE TITLE
Possibility to add a "suffix" to stock quantity

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#12753]
Specifically, in the art to cart validation messages, I have a use case where it would be helpful to have the error message read "You only have 4oz" in stock. That number is derived from `$product->get_stock_quantity()` which can be filtered, but if I filter in a suffix string (like oz) then it breaks any calculations that use `get_stock_quantity()` such as `has_enough_stock()`. Is there a way to to distinguish between calculations and front-end string display, such as an additional context?

**Comment by mikejolley** [comment]
This would break other functions too as it's expected to be numeric. See `wc_format_stock_for_display` function for example. 

You should use a filter such as `woocommerce_get_availability_text` to adjust those strings if needed. I think this is the way you'd do it in 2.6 too :)

Let me know if unclear.

**Comment by helgatheviking** [comment]
`wc_format_stock_for_display()` is not used in the [add to cart validation](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart.php#L939) though if it were, and it had a filter, it might be sufficient. 

`get_availability_text()` would produce the wrong text in the cart errors.

**Comment by mikejolley** [comment]
@helgatheviking even in that example, it has a second variable for the quantity already in cart, and **that** is also numeric (it's added up) so 'oz' would break things there too. 

Sounds like what you really need is a display wrapper around stocks in notices, but thats not something we've ever supported?

**Comment by helgatheviking** [comment]
A display wrapper would work, or a filter for the cart errors?

**Comment by mikejolley** [comment]
What is preferred? Or do you want to submit a PR?

**Comment by helgatheviking** [comment]
I think I'd prefer the display wrapper. 

What about something like:

```
/**
 * Format the stock quantity ready for display.
 * @since  2.7.0
 * @param  int  $stock_quantity
 * @return string
 */
function wc_format_stock_quantity_for_display( $stock_quantity ) {
	return apply_filters( 'woocommerce_format_stock_quantity', $stock_quantity );
}
```
