### ISSUE TITLE
Search Woocommerce products by menu order

### ISSUE THREAD

**Issue by someone91** [woocommerce/woocommerce#12766]
Hi,
Is it possible to implement this for everyone?
http://stackoverflow.com/questions/41188277/wordpress-search-woocommerce-products-by-menu-order

I had the exact same issue.. would be nice if it would be implenented... save trouble for others.. especialy when the solution is already given.

**Comment by mikejolley** [comment]
'default' sort order in WooCommerce IS menu order.
