### ISSUE TITLE
Allow linking products to other non WooCommerce shopping websites

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#12763]
In Woocommerce customer can add items to cart and buy from within the website.

However some stores sell items in many channels (In their website, In Amazon, etc..)
It would be nice to have the ability to add option in each product page to be forwarded to order the item in other sites (Like Amazon). This is useful as it might eventually bring more orders for the store (some prefer to buy from well known channels or difference in shipping rates etc).

For example:
https://www.oscarmike.org/product/om-freedom-tee-vintage-blue/

near "add to cart"... a new button with "Order From Amazon".
The button text will be selected from the user.
Each product that this property is activated for it will also get definition of the exact URL in the other site and when user click on it he will be forwarded to this site.

**Comment by mikejolley** [comment]
You mean like...an external product :) It's possible right now. If you want it in addition to your regular add to cart link, add a button to the description.

**Comment by UserName011** [comment]
@mikejolley  I mean an internal product which can also be bought from other websites.

**Comment by mikejolley** [comment]
Or you can add a link to the description, or look into the product retailers extension.

Really, requests like this should not be logged on Github. Please use the ideas board. http://ideas.woocommerce.com/forums/133476-woocommerce
