### ISSUE TITLE
I need to use over 15k categories, when I add over 10k update products times out: Support ticket ID 514916

### ISSUE THREAD

**Issue by mikehancoski** [woocommerce/woocommerce#12769]
## EXPLANATION OF THE ISSUE

I have a woocommerce store currently in testing that has ~20k categories.

When I import these categories and add a them to product(s) then hit the product update button takes over 30 seconds to load even if you change nothing.

I expect it to take less then 10 seconds or at least an amount of time that will not cause my load balance  server to time out

## STEPS TO REPRODUCE THE ISSUE

The test site currently does not have the all categories imported, but it has enough to replicate the issue.

http://www.xcitestage1.com.php56-9.dfw3-2.websitetestlink.com/

See support ticket for login info
STEPS:

Add a few products

Add 20,000 categories that are nested 3 deep

500 PARENTS -> 10 Children each -> 4 sub children of each of the 10

OR

500 manufacturer names -> 10 Model names for each manufacturer -> 4 years for each model 

This should get you 20,000 categories

Add 5 categories to any product

Try to update that product

The load time will not be over 30 seconds

I have contacted support hey send me here ticket ID 514916

I assumed this was fixed by 

https://github.com/woocommerce/woocommerce/issues/4644

it appears to not be fixed

I have tried disabling all plugins and the theme this did not change the issue

If you would like you can login to the test server above with the credentials from the support ticket and disable switch anything you want I have backups of everything

Also I can replicate this on a much simpler install and launch that on a testing site, if needed.

**Comment by mikehancoski** [comment]
Sorry I gave you my local system status file the real one is in the support ticket and here

`
### WordPress Environment ###

Home URL: http://www.xcitestage1.com.php56-9.dfw3-2.websitetestlink.com
Site URL: http://www.xcitestage1.com.php56-9.dfw3-2.websitetestlink.com/wp
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 5.6.24-0+deb8u1
PHP Post Max Size: 512 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (7) ###

Advanced Custom Fields: by Elliot Condon – 4.4.11
Category Checklist Tree: by scribu – 1.3.2
Import pluigin: by hanco – 0.2
Slider WD: by WebDorado – 1.1.48
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.2
WooCommerce: by WooThemes – 2.6.11
WordPress Importer: by wordpressdotorg – 0.6.1

### Settings ###

Force SSL: –
Currency: USD (USD $)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #8 - /checkout/
My Account: #9 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: derailleurhanger
Version: 1.0
Author URL: http://johnsonwebconsulting.com
Child Theme: ✔
Parent Theme Name: Mystile
Parent Theme Version: 1.3.17
Parent Theme Author URL: http://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: mystile-child/woocommerce/archive-product.php
mystile-child/woocommerce/content-product.php version 1.6.4 is out of date. The core version is 2.6.1
mystile-child/woocommerce/emails/admin-new-order.php version 2.0.0 is out of date. The core version is 2.5.0
mystile-child/woocommerce/emails/customer-reset-password.php
mystile-child/woocommerce/single-product/meta.php
mystile-child/woocommerce/single-product/price.php
mystile-child/woocommerce/single-product.php

: Learn how to update outdated templates
`

**Comment by mikejolley** [comment]
I don't think we can do anything about this one directly - the category meta box lists them all:

![2017-01-06 at 10 51](https://cloud.githubusercontent.com/assets/90977/21715788/734006ea-d3fe-11e6-8572-38e5539d7ab9.png)

So that will be grabbing all 20k on load. This meta box is not controlled by WooCommerce - categories are a taxonomy, and WordPress handles them entirely. I expect you'll see an identical slowdown if creating 20k post categories.

I'll log a separate issue to consolidate all issues caused by that. Short term you'll need to consider using your own taxonomy, making them tags instead, or hiding the metabox.
