### ISSUE TITLE
woocommerce_return_to_shop_redirect filter not applied in some pages

### ISSUE THREAD

**Issue by Tyrianad** [woocommerce/woocommerce#12760]
## EXPLANATION OF THE ISSUE

Some urls do not change when a woocommerce_return_to_shop filter is added to functions.php. Woocommerce 2.6.11

## STEPS TO REPRODUCE THE ISSUE

As an example:
1- Buy a product and proceed to checkout.
2- Pay the product and stop at the order complete page.
3- Go back with the browser "back" button, this way you will get a session expired message.
4- The "go to shop" url is not filtered

As an example, in class-wc-checkout.php:

`if ( WC()->cart->is_empty() )
{
     throw new Exception( sprintf( __( 'Sorry, your session has expired. <a href="%s" class="wc-backward">Return to shop</a>', 'woocommerce' ), esc_url( apply_filters( 'woocommerce_return_to_shop_redirect', wc_get_page_permalink( 'shop' ) ) ) ) );
}`

**Comment by justinshreve** [comment]
See #12761.
