### ISSUE TITLE
Variations remain published when variable product trashed.

### ISSUE THREAD

**Issue by reidbiztech** [woocommerce/woocommerce#12774]
## EXPLANATION OF THE ISSUE

When a variable product is trashed (post_status = 'trash') the post status of the variations remains published (post_status = 'publish').

WordPress: 4.7
WooCommerce: 2.6.11
mysqld 10.1.18-MariaDB
Apache/2.4.23 (Win64)
PHP: 7.0.12
Zend OPcache v7.0.12

## STEPS TO REPRODUCE THE ISSUE

Create a variable product, add some variations, publish the product, then trash the product, then observe the post status of the variations in the wp_posts table.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://127.0.0.1/
Site URL: http://127.0.0.1/
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Win64) mod_fcgid/2.3.9
PHP Version: 7.0.12
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.50.3
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.11

### Settings ###

Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My Account: #13 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

This is complicating my development work significantly right now. It would be great if variations are trashed when the parent product is trashed. Just makes sense.

Thanks

**Comment by reidbiztech** [comment]
Here is my hacky fix for it. (But I'll still need to address the case of products trashed before my plugin is installed, or while it is inactive - with an activation hook.)

```php
<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

class XYZ_Variable_Product_Trash {
	
	public static function init() {
		
		// after post is trashed
		add_action( 'trashed_post', array( __CLASS__, 'trashed' ) );
		
		// before post is untrashed
		add_action( 'untrash_post', array( __CLASS__, 'untrash' ) );
		
	}
	
	public static function trashed( $post_id ) {
		
		global $wpdb;
		
		$wpdb->update( 
			$wpdb->posts,
			array( 'post_status' => 'trash' ),
			array( 
				'post_type' => 'product_variation',
				'post_parent' => $post_id
			)
		);
		
	}
	
	public static function untrashed( $post_id ) {
		
		global $wpdb;
		
		$wpdb->update( 
			$wpdb->posts,
			array( 'post_status' => 'publish' ),
			array( 
				'post_type' => 'product_variation',
				'post_parent' => $post_id
			)
		);
		
	}

}

XYZ_Variable_Product_Trash::init();
```

Note that the WP Core post trash hooks are inconsistently named:

Before trashed: 'wp_trash_post' (this one is the exception)
After trashed: 'trashed_post'

Before untrashed: 'untrash_post'
After untrashed: 'untrashed_post'

**Comment by WPprodigy** [comment]
I'm curious how this is causing you to run into some trouble? Couldn't you just check the parent product's post status instead of needing to check on the variation status?

I'm also wondering if maybe inherit would be better all around for variations: https://codex.wordpress.org/Post_Status#Inherit. That would cover trash, draft, future, etc.

**Comment by reidbiztech** [comment]
It is causing me troubles because I am using a WP_List_Table class to display and interact with both products and product variations optionally filtered by taxonomy and product custom fields (post metas) where the filters selected may apply to a variation but not to the parent product. Complicated.

**Comment by reidbiztech** [comment]
So, after the weekend's rest and some fresh thinking this morning prompted by WPprodigy's question/suggestion, I have come up with a better workaround by first querying for trashed products then adding a 'post_parent__not_in' parameter to the main WP_Query() I'm using to fill my list table.

This approach makes my original complaint irrelevant, but I think it still stands on principle. If a parent product is in the 'trash', then the product variations should not remain 'publish'ed.

**Comment by mikejolley** [comment]
See #12798
