### ISSUE TITLE
"view wishlist" leads to 404 error

### ISSUE THREAD

**Issue by samthegrizzly** [woocommerce/woocommerce#12771]
## EXPLANATION OF THE ISSUE

YITH WooCommerce Wishlist Version 2.0.16 - When I click on "browse wishlist" after adding a product to the wishlist, it displays a 404 Error since the URL displays **thegrizz.ca/wishlist/view** instead of **thegrizz.ca/wishlist**

## STEPS TO REPRODUCE THE ISSUE

1) using Zerif Lite theme

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://thegrizz.ca
Site URL: https://thegrizz.ca
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (18) ###

WP Affiliate Manager: by wp.insider
wpaffiliatemgr – 2.3.6

Canada Post (BASIC) WooCommerce Extension: by WooForce – 1.2.4
Contact Widgets: by GoDaddy – 1.3.4
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.5
Jetpack by WordPress.com: by Automattic – 4.4.2
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
MailChimp for WordPress: by ibericode – 4.0.11
Popup by Supsystic: by supsystic.com – 1.8.4
Shortcodes Ultimate: by Vladimir Anokhin – 4.9.9
ThemeIsle Companion: by Themeisle – 1.0.0
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce: by WooThemes – 2.6.11
Yoast SEO: by Team Yoast – 4.0.2
WP Content Copy Protection & No Right Click: by wp-buy – 1.6
WP Product Feed Manager: by Michel Jongbloed – 1.3.1
WP Super Cache: by Automattic – 1.4.8
YITH WooCommerce Badge Management: by YITHEMES – 1.2.12
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #152 - /shop/
Cart: #153 - /cart/
Checkout: #154 - /checkout/
My Account: #155 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Zerif Lite
Version: 1.8.5.6
Author URL: http://themeisle.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`

**Comment by mikejolley** [comment]
This is not a bug tracker for YITH WooCommerce Wishlist Version. Use YITH support.
