### ISSUE TITLE
Stock is not reduced, when order is placed using REST API.

### ISSUE THREAD

**Issue by pkhutal** [woocommerce/woocommerce#12772]
Hello,

I am using WooCommerce REST API to place order and order is successfully placed but the problem is stock quantity of product is not deducted even on completion of order.

Here is JSON response after order is placed:

`{
	order = {
		"billing_address" = {
			"address_1" = "Test Address 1";
			"address_2" = sdgfgsdfg;
			city = Patna;
			company = "";
			country = IN;
			email = "fure@gmail.com";
			"first_name" = Fure;
			"last_name" = Ji;
			phone = 1234567890;
			postcode = 452001;
			state = BR;
		};
		"cart_tax" = "3.00";
		"completed_at" = "2017-01-06T06:48:49Z";
		"coupon_lines" = ();
		"created_at" = "2017-01-06T06:48:46Z";
		currency = INR;
		customer = {
			"avatar_url" = "http://2.gravatar.com/avatar/?s=96";
			"billing_address" = {
				"address_1" = "Test Address 1";
				"address_2" = sdgfgsdfg;
				city = Patna;
				company = "";
				country = IN;
				email = "fure@gmail.com";
				"first_name" = Fure;
				"last_name" = Ji;
				phone = 1234567890;
				postcode = 452001;
				state = BR;
			};
			"created_at" = "2016-05-24T08:00:51Z";
			email = "fure@gmail.com";
			"first_name" = fure;
			id = 3;
			"last_name" = ji;
			"last_order_date" = "2017-01-06T06:48:46Z";
			"last_order_id" = 280;
			"orders_count" = 1;
			role = subscriber;
			"shipping_address" = {
				"address_1" = "Test Address 1";
				"address_2" = sdgfgsdfg;
				city = Patna;
				company = "";
				country = IN;
				"first_name" = Fure;
				"last_name" = Ji;
				postcode = 452001;
				state = BR;
			};
			"total_spent" = "0.00";
			username = "fure@gmail.com";
		};
		"customer_id" = 3;
		"customer_ip" = "111.93.247.174";
		"customer_user_agent" = "Mozilla/5.0 (iPad; CPU OS 9_3_3 like Mac OS X)     AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13G34";
		"fee_lines" = ();
		id = 280;
		"line_items" = ({
			id = 229;
			meta = ();
			name = "Woo Logo";
			price = "15.00";
			"product_id" = 79;
			quantity = 1;
			sku = "";
			subtotal = "15.00";
			"subtotal_tax" = "3.00";
			"tax_class" = "reduced-rate";
			total = "15.00";
			"total_tax" = "3.00";
		});
		note = "";
		"order_key" = "wc_order_586f3dce5b030";
		"order_number" = 280;
		"payment_details" = {
			"method_id" = cheque;
			"method_title" = "Cheque Payment";
			paid = 0;
		};
		"shipping_address" = {
			"address_1" = "Test Address 1";
			"address_2" = sdgfgsdfg;
			city = Patna;
			company = "";
			country = IN;
			"first_name" = Fure;
			"last_name" = Ji;
			postcode = 452001;
			state = BR;
		};
		"shipping_lines" = ({
			id = 230;
			"method_id" = "free_shipping";
			"method_title" = "Free Shipping";
			total = "0.00";
		});
		"shipping_methods" = "Free Shipping";
		"shipping_tax" = "0.00";
		status = "on-hold";
		subtotal = "15.00";
		"tax_lines" = ({
			code = "REDUCED RATE-1";
			compound = 0;
			id = 231;
			"rate_id" = 2;
			title = "Reduced Rate";
			total = "3.00";
		}, {
			code = "STANDARD-1";
			compound = 0;
			id = 232;
			"rate_id" = 1;
			title = Standard;
			total = "0.00";
		});
		total = "18.00";
		"total_discount" = "0.00";
		"total_line_items_quantity" = 1;
		"total_shipping" = "0.00";
		"total_tax" = "3.00";
		"updated_at" = "2017-01-06T06:48:49Z";
		"view_order_url" = "http://baseurl/my-account/view-order/280";
	};
}`

Could you please tell me what thing i am missing while placing order from REST API due to which stock is not deducting.

Thank you.

**Comment by mikejolley** [comment]
Use the set_paid flag. http://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

**Comment by pkhutal** [comment]
Thanks for your quick response @mikejolley

**Comment by tarang777** [comment]
Hi pkhutal Can you please tell me how to create order using rest api in android, i am unable to create order and getting error as unauthorized ie 401 error even after passing all the parameters.
Can you please mail me about the process to create order using rest api in android app my mail id is vtarang93@gmail.com.
