### ISSUE TITLE
woocommerce

### ISSUE THREAD

**Issue by weblookfresh** [woocommerce/woocommerce#12770]
I have woocommerce installed at wordpress. Everytime I log in to my wordpress I do not see the woocommerce tab. To see the woocommerce tab i have to un-activate woocommerce through the plugins and activate it again. 
I have version 2.6.11 woocommerce installed
And I have wordpress 4.7

**Comment by mikejolley** [comment]
Could be a plugin conflict i.e. a plugin taking it's spot on the menu. Not seen any other reports on this (at all), so I cannot see how it is a core WC bug. See what else you have installed on your site - you'll need to investigate yourself.

Closing as this is not reproducible.
