### ISSUE TITLE
WooCommerce Too Many Products Error

### ISSUE THREAD

**Issue by rlasater** [woocommerce/woocommerce#12780]
We have about 5000 grouped products. When it reaches around 3000 grouped products, the grouped products search on the simple products stop working. There must be some query limitation.

If we changed the products back to simple products it works again. When we start adding back grouped products, somewhere close to 3000, the search function in the linked products tab on the simple product tab starts returning no results. Is very weird issue. 

Do you have an idea why this happens?

**Comment by rlasater** [comment]
Could this be related to this?
https://github.com/woocommerce/woocommerce/issues/12773

**Comment by mikejolley** [comment]
I'd only expect that if it were rendering them all at once, which it does not. Can you check the server error logs?

**Comment by rlasater** [comment]
Hi Mike, 
Thanks for the reply. Here is the error in the log.
KILLED QUERY (16909 characters long generated in /nas/content/staging/spiritvoyage1/wp-content/plugins/woocommerce/includes/class-wc-ajax.php:1896): SELECT wp_5_posts.ID FROM wp_5_posts WHERE 1=1 AND wp_5_posts.ID IN (3100,5909,5910,5911,5912,5913,5914, etc....  There is a list of thousands of post IDs. Didn't want to paste them all here.

**Comment by rlasater** [comment]
I tested this scenario on a separate site and got the same error.

**Comment by mikejolley** [comment]
Got it. This one is already fixed in 2.7 - we've changed how you associate products with groups (you now search from the grouped product instead of from children).

**Comment by rlasater** [comment]
Do you have an estimated release date for 2.7?

**Comment by mikejolley** [comment]
Follow the dev blog https://woocommerce.wordpress.com/
