### ISSUE TITLE
Improvement - Extra arguments for "woocommerce_layered_nav_link" filter

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#12788]
Filter `woocommerce_layered_nav_link` currently passes only the link as a parameter. Without further information about the context in which the link was generated, such as term and taxonomy, a filter would not be able to do much. 

My proposes solution is, simply, to add current term and taxonomy to the filter, as both are readily available.

Pull request following shortly.

**Comment by claudiosanches** [comment]
Solved by #12789
Thanks.
