### ISSUE TITLE
Sorting on custom date field

### ISSUE THREAD

**Issue by keyurpatel30** [woocommerce/woocommerce#12781]
Hello,

Is there any way at the moment to sort the list of orders based on a meta value (a custom field for date)?
In my case, I would like to sort the orders based on a custom (date) field and then use pagination, since by default it uses order number.

Using the old v3, I was able to sort them correctly, but on the new version, I can't seem to figure out how to sort on a custom meta value.

**Comment by mikejolley** [comment]
Supported values:

`
"date",
"id",
"include",
"title",
"slug"
`

Since we use WP Rest API, you can filter the allowed values and supported values to add the ability to sort by other things such as custom fields. I saw some examples in https://github.com/WP-API/WP-API/issues/2308
