### ISSUE TITLE
New products don't appear in the shop

### ISSUE THREAD

**Issue by navasis** [woocommerce/woocommerce#12782]
Hi guys,

So I've been using WC for a long time now and had no problems at all. It's just recently I noticed that when I add new products to my shop, they don't appear in the catalog as it used to. However, whats interesting, they do appear in wp-admin product list and you can view each product on its product inner page. BUT not in the catalog!

WooCommerce version: 2.6.3
WordPress: 4.5.4

Also, I'm using a customised Storefront template. However, only the styling details have been changed and some custom functionalities that don't affect the core functions or the product display.

Storefront: 2.1.6

Furthermore, the shop is not using any cache plugin or anything similar. So I'd like to hear some suggestions or tips on how to solve the issue.

Best regards

**Comment by mikejolley** [comment]
There are not enough details here to give direct advice, and this is not affecting others from what I can see, so I'd expect you either have a plugin which is changing the front-end queries, some kind of server level caching you may not be aware of, or the products are missing meta data.

Most likely conflict with plugin or custom code in the theme  - you can test that yourself through trial and error.

**Comment by navasis** [comment]
I understand, but the thing is that switching themes nor deactivating plugins helps. And I'm aware of the settings in wp-admin when editing product, there are visibility options, but they're OK.

**Comment by mikejolley** [comment]
Look into server level cache in that case, or cloudfront.
