### ISSUE TITLE
Replace use of `get_post` or `get_post_status` in the REST API.

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#12796]
The REST API calls `get_post` in a few places, going against our CRUD abstraction. See the coupons controller for an example. Some of these are to check the post type, which can easily be replaced by loading WC_Coupon or the other data objects and catching the invalid exception (see #12795).

In other places, it is passed to `update_additional_fields_for_object` which is part of WP-API. Do we have to pass a get_post response to that?

cc @claudiosanches

**Comment by claudiosanches** [comment]
Well, this is another reason that I prefer start a version `v2` of our REST API.
Since for sure start passing `WP_Post` objects will change a lot all filters and actions.

**Comment by mikejolley** [comment]
I defer to @claudiosanches for this. What do you think we need to do for 2.7 if anything, or does this wait for future version and v2 api?

**Comment by justinshreve** [comment]
I think we can leave as is for now and do a fix when we can change the filters. It's starting to sound like we should target v2 for 2.8 though. There are a number of things that can be done already.

**Comment by mikejolley** [comment]
Closed in favour of #13070
