### ISSUE TITLE
[2.7] Database error when bulk editing variable products

### ISSUE THREAD

**Issue by Chrystll** [woocommerce/woocommerce#12793]
WordPress : 4.7
Plugins activated : Only WooCommerce 2.7 beta1 (master)
Theme : StoreFront 2.1.6

To reproduce:
Go to Products > Add new > select ‘Variable product’ > Save Draft (don’t create variations)
Go back to the products list, select the product just created, bulk edit it > Update

I get this error message :
WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 for query SELECT COUNT( post_id ) FROM wp_postmeta WHERE meta_key = '_stock_status' AND meta_value = 'instock' AND post_id IN (  ) made by bulk_edit_posts, wp_update_post, wp_insert_post, do_action('save_post'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Admin_Post_Types->bulk_and_quick_edit_hook, do_action('woocommerce_product_bulk_and_quick_edit'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Admin_Post_Types->bulk_and_quick_edit_save_post, WC_Admin_Post_Types->bulk_edit_save, WC_Product_Variable::sync, WC_Data_Store->__call, WC_Product_Variable_Data_Store_CPT->sync_stock_status, WC_Product_Variable->child_is_in_stock, WC_Data_Store->__call, WC_Product_Variable_Data_Store_CPT->child_is_in_stock

**Comment by mikejolley** [comment]
I saw this too and fixed it in #12798
