### ISSUE TITLE
Shipping Zones > Rest of the World Styles a Bit Borked

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#12805]
## EXPLANATION OF THE ISSUE

Styles are borked on Shipping Zones > Rest of the World on a brand new, fresh install of master on fresh install of WordPress 4.7.1. Tested with Chrome on OSX.

## STEPS TO REPRODUCE THE ISSUE

Activate WooCommerce
(No other plugins are installed other than Akismet and Hello Dolly)
Set up for United States - Washington + I will be shipping products
Go to wp-admin > WooCommerce > Settings > Shipping and click on Rest of the World
See this:

<img width="1272" alt="screen shot 2017-01-12 at 10 44 31 am" src="https://cloud.githubusercontent.com/assets/1595739/21903287/267aaee0-d8b4-11e6-808c-957a9b79903b.png">

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
@jameskoster This is referring to the shift right and column headers. Other zones are not affected as they have fields (name and location). Ideas? Allen suggested having read only fields for clarity.

@allendav

**Comment by jameskoster** [comment]
Hm, don't you think we should just hide the column headers when no methods are present?

**Comment by mikejolley** [comment]
@jameskoster yeah but they would need to appear magically on clicking add. What about the left side?

**Comment by jameskoster** [comment]
Given how the interface looks when methods are added I don't think it's such a big deal.
