### ISSUE TITLE
in_stock not being updated due to auto conversion (boolean->string)

### ISSUE THREAD

**Issue by NizarBlond** [woocommerce/woocommerce#12800]
I send "in_stock" as boolean, as per documentation of products/batch function

http://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

Then, in the file "class-wc-rest-products-controller.php" has

```
    // Stock status.
    if ( isset( $request['in_stock'] ) ) {
        // gettype($request['in_stock'] is string
        $stock_status = true === $request['in_stock'] ? 'instock' : 'outofstock';
    } else {
        $stock_status = get_post_meta( $product->id, '_stock_status', true );

        if ( '' === $stock_status ) {
            $stock_status = 'instock';
        }
    }
```

ideas?

**Comment by mikejolley** [comment]
Store status is _stored_ as a string. The conversion is correct. It converts your `true` or `false` into the strings `instock` or `outofstock`.

Tested and working.

**Comment by NizarBlond** [comment]
But the ajax doesn't allow me to send boolean, http is a text protocol. How do you expect me to use /products/batch API and update in_stock to true? 

again, $request['in_stock'] will be "true" or "false"

**Comment by mikejolley** [comment]
I'm using a client to send a boolean. WP Rest API itself uses booleans so I wasn't aware it was a problem. What are you making requests with? @claudiosanches

**Comment by NizarBlond** [comment]
a normal jQuery ajax request.

```
$.ajax({ 
url: '..',
data: {
   ..
   in_stock: true
  ..
}
});
```

**Comment by mikejolley** [comment]
Ok well @claudiosanches can look into that but I have to ask, if you're doing this with jQuery, you don't have your keys visible on the web page do you...?

**Comment by NizarBlond** [comment]
what do you mean?

I can print the request params using console.log - I'm sure of what I send. You just need to consider that the request should be "true" as string instead of boolean or find another way of updating.

**Comment by mikejolley** [comment]
I mean, under what environment are you using jQuery ajax calls? Where? This is unrelated to your bool issue, I'm just curious.

**Comment by NizarBlond** [comment]
Chrome browser.
Sails JS (client side node.js)

Cheers

**Comment by NizarBlond** [comment]
any news? not sure why you mark this closed.

**Comment by claudiosanches** [comment]
Works just fine with WordPress 4.7 and WooCommerce 2.6.13.
Since WordPress 4.7 applies `rest_sanitize_boolean()` it will never be a problem.
If you did not updated your WordPress version I recommend you to do it as soon as possible.

**Comment by NizarBlond** [comment]
I use the same environment and I just tested it. I removed my DB, installed fresh WC, fresh WP 4.7.1. I even added prints inside rest_sanitize_boolean() and rest_sanitize_request_arg() and it doesn't even consider the in_stock, it doesn't get to that point.

Please add:

print_r("IN STOCK TYPE: ".gettype($request['in_stock'])); 
    if ( isset( $request['in_stock'] ) ) {

You will see that the value is string. 

Use the batch API call and see yourself

![image](https://cloud.githubusercontent.com/assets/2389428/22241985/4b46052e-e22a-11e6-8eac-cd5b7940cb8e.png)
