### ISSUE TITLE
[2.7] Creating an Order Exponentially Slower

### ISSUE THREAD

**Issue by spencerfinnell** [woocommerce/woocommerce#12802]
## EXPLANATION OF THE ISSUE

Creating an order with a large number of products is vastly slower in WooCommerce 2.7-beta (master). 

## STEPS TO REPRODUCE THE ISSUE

1. Add ~100 products to your cart:
  https://gist.github.com/spencerfinnell/c9cf17aedf03c57a2e8f681215408ec1 
  Visit `http://yoursite.com?add-products` to add 100 items.
2. Visit the checkout page and complete the order. 
3. Check out the `release/2.6` branch and repeat. 

## SYSTEM STATUS REPORT

https://gist.github.com/spencerfinnell/509cb4a95330774b1d3ef77792f59774

**Comment by spencerfinnell** [comment]
I think the bulk of the slowdown is coming from the `read_items()` method in the Order datastore.

**Comment by jakecaputo** [comment]
Adding to this: we're experiencing a "Time Out Error" seemingly with orders larger than 50 products. The order still goes through, but the frontend just shows the error and no order emails are sent, so the user tries to submit it again. Last night we had a user submit a 106 item $389 order twice, and another submitted a 134 item $524.99 order three times.

We've spoke to our host, Flywheel, and have been told:

> We'd be happy to help, but I'm afraid it looks like we're already doing just about everything we can from our end. I made a slight reconfiguration more as a hail Mary than anything, but if you don't see any changes after another retry, I'm afraid things are already bumped as high as we can get them, so it looks like it's up to WooCommerce at this point.

**Comment by mikejolley** [comment]
See #13044

**Comment by spencerfinnell** [comment]
Thanks @mikejolley those changes look good -- however I'm still seeing a massive difference between a clean install with `master` vs `release/2.6` on sites with a large number of products and large carts.

Are you able to test with ~5000 products and 100 in the cart?

**Comment by mikejolley** [comment]
@spencerfinnell there will be some difference because you're dealing with objects, not just data directly in the meta table. Each cart object has to be read, and is kept in memory. I did this testing with ~100 and found the emails to be the largest bottleneck (3s to 1s, 2.6 was ~1.5-2)

**Comment by spencerfinnell** [comment]
@mikejolley There is a noticeable difference if you short-circuit the `update()` method in the datastore. 

The change from singular direct updates to updating the entire object definitely slows it down like you said; but seems like there should be a way to determine if processing a checkout and not make so many updates.

**Comment by spencerfinnell** [comment]
Not allowing the `update()` method to do anything reduces it by about 50% (~5.5s to 2.5s)

**Comment by mikejolley** [comment]
Where are you talking about?

**Comment by spencerfinnell** [comment]
Sorry, edited my original post. 

https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L143-L172

**Comment by mikejolley** [comment]
Hmm why would product be updated...

**Comment by spencerfinnell** [comment]
Do stock quantities get adjusted at all during the initial checkout? Or only when an order status changes?

**Comment by mikejolley** [comment]
Not sure; investigating now. If it's that, we can do a direct update via data store instead if thats more efficient.

**Comment by mikejolley** [comment]
`wc_update_total_sales_counts`

**Comment by spencerfinnell** [comment]
https://github.com/woocommerce/woocommerce/blob/4e653139b6dea4a18ac1399cae93a352ec3810c8/includes/wc-order-functions.php#L742

**Comment by spencerfinnell** [comment]
Got me! Yeah that's what I found. So in this scenario all aspects of 100 products are being updated instead of just the stock.

**Comment by mikejolley** [comment]
Not stock, sales count. I wonder if there is a better way of getting that data vs storing in products.

**Comment by spencerfinnell** [comment]
I think it needs to be dealt with at a higher level. This will happen with any prop update anywhere on the site. 

It will likely cause issues when doing a large bulk edit, but other seemingly simple tasks become very taxing when all those updates happen when really only one prop changed.

**Comment by mikejolley** [comment]
This is only a problem with post types really because of the post object. It can maybe be improved by implementing the 'changed' logic, however this case can be fixed via data store by mirroring how stock works. PR incoming

**Comment by mikejolley** [comment]
^ see above PR

**Comment by spencerfinnell** [comment]
But doesn't that only account for that one piece of meta. if I do

```php
for( $i =; $i <= 100; $i++ ) {
  $product = get_product( $i );
  $product->set_props( array(
    'weight' => 10
  ) );
  $product->save();
}
```

`wp_update_post()` still gets called 100 times when nothing related to the post object has changed.

**Comment by mikejolley** [comment]
Of course, but this is a separate issue. There is already logic to detect changes; this just needs to be applied to the product class.

**Comment by spencerfinnell** [comment]
I know it's not this exact scenario but it seems like something that will popup pretty frequently.

**Comment by spencerfinnell** [comment]
👍 I'll make a separate issue.

**Comment by mikejolley** [comment]
@spencerfinnell I'm off to bed, but if you decide to have a crack at it look at `$changed_props   = $object->get_changes();`. That returns all the prop names which have been changed since last save. this can be applied to the update() code in the data store :)
