### ISSUE TITLE
The attributes of variations return the slug instead of the name of the product

### ISSUE THREAD

**Issue by JuhG** [woocommerce/woocommerce#12804]
## EXPLANATION OF THE ISSUE

The value of the `name` in the attributes list is different for the variations as for the base product. For the product, under the `name` key it's actually the name of the product, but inside the variations, with the same structure under the `name` key we can find the slug of the product instead.

The same issue was mentioned in this thread:
https://github.com/woocommerce/wc-api-php/issues/77
I hope this time it's the right place for this question.

Attributes on the base product:

```php
[attributes] => Array
    (
        [0] => Array
            (
                [id] => 0
                [name] => Átmérő
                [position] => 0
                [visible] => 1
                [variation] => 1
                [options] => Array
                    (
                        [0] => 120
                        [1] => 130
                        [2] => 150
                    )

            )

        [1] => Array
            (
                [id] => 0
                [name] => Hossz
                [position] => 1
                [visible] => 1
                [variation] => 1
                [options] => Array
                    (
                        [0] => 250
                        [1] => 400
                        [2] => 800
                        [3] => 1000
                    )

            )

    )
```

Attributes on the variations:

```php
[attributes] => Array
    (
        [0] => Array
            (
                [id] => 0
                [name] => atmero
                [option] => 150
            )

        [1] => Array
            (
                [id] => 0
                [name] => hossz
                [option] => 1000
            )

    )
```

This seems inconsistent. Can you confirm that this is a bug?

**Comment by mikejolley** [comment]
This is inconsistent I agree, however it reflects how the data is stored and cannot be changed at this point. With text based attributes, at product level 'name' will be the name as typed. In your case `Átmérő`.

For variations, this is sanitized to `atmero`.

@claudiosanches Should we convert or leave?

**Comment by claudiosanches** [comment]
@mikejolley the correct is `Átmérő` since it's a custom product attribute, but variations change to slug by default.

**Comment by mikejolley** [comment]
@claudiosanches Yep - should we convert back for the API return value?

**Comment by claudiosanches** [comment]
@mikejolley yes, better solution since it's a custom product attribute.

**Comment by JuhG** [comment]
The interesting part is, like you said, it's only for custom attributes. The ones created in the Attributes menu have the correct name. Which makes it even more consistent.

I'm not sure how hard is it to change it, maybe renaming it to slug would make it better. But that could break existing code.
(Actually that was my concern, I patched it over in my code for my needs, I was mostly curious if you're planning to change it, which could later break my solution.)

**Comment by GeppieNL** [comment]
I would suggest to return both name and slug (and/or (meta)attribute-id?) if possible. 
At least the attribute(-name) on the variation should match the attribute(-name) on the product attributes; since the variations are created based on the parent product.

**Comment by claudiosanches** [comment]
@GeppieNL custom product attribute don't have both. We did it in the past and only generated more confusion.

**Comment by mikejolley** [comment]
This needs to go into the v2 wp rest api. Moving to 2.8 milestone.
