### ISSUE TITLE
[2.7] Performance Issues with structured data of Variable products

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#12811]
### EXPLANATION OF THE ISSUE

1. Calling `get_available_variations` at https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-structured-data.php#L185 seems as unnecessary and likely to cause performance issues if the intent is to get the variation IDs.

2. Even replacing `get_available_variations` with `get_children` will not remedy the performance issues here. Eventually, instantiating 1000s of variations in a single page load will be problematic.

Remember that performance issues with calling `get_available_variations` and creating thousands of variation objects have made it necessary in the past to use AJAX in the single-product pages of variable products. Doing the same in shop archives could potentially bring back the same issue, but multiplied in magnitude.

Perhaps we could use a different schema based on the min/max variation prices when the number of variations exceeds a certain threshold, e.g. use a single offer and replace `price` with `priceSpecification` to define range? Not sure if it's properly supported by Google though -- the information I've been able to gather is not conclusive.

EDIT: Looked at `AggregateOffer` as well -- however, seems to be intended for aggregating multiple offers of the same item from different sellers.

CC @opportus @claudiosanches

**Comment by opportus** [comment]
Hi @franticpsyx 

> Remember that performance issues with calling get_available_variations and creating thousands of variation objects have made it necessary in the past to use AJAX in the single-product pages of variable products. Doing the same in shop archives could potentially bring back the same issue, but multiplied in magnitude.

By default, it doesn't call `get_available_variations` on archive pages, only on single product page.
But there **might** be a better solution which would allow to include it by default... That's maybe what you mean here ?

About single product page, currently without  better solution, the admin can still disable the variations feature for products with exeptionally large amount of variations...

CC @leewillis77, thought ?

**Comment by franticpsyx** [comment]
Thanks @opportus -- just noticed there's some logic above that exits the method when called in archives.

>But there might be a better solution which would allow to include it by default... That's maybe what you mean here.

Improving the logic for single-product pages is necessary, I think -- see points (1) and (2). 
While (2) is an improvement over (1), neither will cut it when displaying products with 000s variations.

Note that variation prices can be obtained using `WC_Product_Variable::get_variation_prices`, which does not require all variations to be instantiated, however there is no cached/fast way to get all variation titles/excerpts straight from the DB ( @claudiosanches ? ).

If there's no way to add an `Offer` for each variation, then perhaps we might beed to use a fallback schema to represent variable products that have above 30 variations? That's the threshold used in https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L997 -- a reasonable one, IMO.

E.g. add a single offer and use `priceSpecification` to represent the price range between the min/max variation price?

**Comment by opportus** [comment]
> However there is no cached/fast way to get all variation titles/excerpts straight from the DB ( @claudiosanches ? ).

Wouldn't this be anyway a **globally** better solution for API ?
Especially that as you already mentioned, you've got the same kind of problem already. This confirms the fact that a more optimized tool is needed to fetch variations data. Is it possible in first place ?

**Comment by leewillis77** [comment]
> By default, it doesn't call get_available_variations on archive pages, only on single product page.
But there might be a better solution which would allow to include it by default... That's maybe what you mean here ?
> About single product page, currently without better solution, the admin can still disable the variations feature for products with exeptionally large amount of variations...

I don't think there's any need to get all of the variation info on archive pages at all - at least as far as I'm aware.

> If we find a fast solution for single-product pages, I guess there will not be any reason to "trim" the data in archives anymore.

I still wouldn't add it to the archive pages to avoid bloating the HTML produced.

> If there's no performant way to add an Offer for each variation, then perhaps we might need to use a fallback schema to represent variable products that have above 30 variations? That's the threshold used in https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L997 -- a reasonable one, IMO.

I agree here (purely for the sake of performance). My original PR for adding variation data (pre the move to JSON-LD) honoured woocommerce_ajax_variation_threshold, and I think we should do so here. The caveat is that for those customers we may end up back with the original product ads issue where Google can't validate the on-page price against the price in the feed. 

Given the lack of information about that though I think priceSpecification / minPrice / maxPrice would be a sensible compromise.

**Comment by mikejolley** [comment]
Should be resolved in #13115
