### ISSUE TITLE
[2.7] Deprecated filter woocommerce_get_children in WC_Product_Variable

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#12812]
## EXPLANATION OF THE ISSUE

In 2.7 and in the class WC_Product_Variable, the filter woocommerce_get_children ist deprecated and the new filters woocommerce_product_get_children or woocommerce_product_get_visible_children should be used. Unfortunately, the new filters are never called, so the only solution is to still call the "old" filter woocommerce_get_children and to get a deprecated notice.

**Comment by Chunkford** [comment]
I've just noticed if a product has a mixture of attributes used for variations, and on the front end, if one of the options is selected, the other options aren't being updated in the drop downs to reflect what's available.
Would this be the ajax call not calling these new functions?
