### ISSUE TITLE
[2.6.12] Variations problem

### ISSUE THREAD

**Issue by hoangc7** [woocommerce/woocommerce#12817]
This problem occurs in WooCommerce 2.6.12. I tried to check it several times with fresh WordPress installation and the default theme (2017), with only WooCommerce plugin activated.

The dropdown always shows the wrong combination. For example:

I setup a variable product with 2 attributes: Color and Size and add following combinations:

Black - Small
Black - Medium
Black - Large
Blue - Medium

When I pick color Blue, the size attribute still shows 3 sizes for select. It is wrong. In previous version, it only shows Medium size only.

Then, even I clear all selections, it only show 1 option in the dropdown.  I have to refresh the page to see other options.

**Comment by Chunkford** [comment]
Yes, I'm having the same issue. Posted here but it was for a different version - https://github.com/woocommerce/woocommerce/issues/12812#issuecomment-272524885

**Comment by WPprodigy** [comment]
Can replicate. Seems to be caused by https://github.com/woocommerce/woocommerce/commit/b8d19b40aeee696573f0cca89415e4fa285f0500

**Comment by RicaNeaga** [comment]
Can you please make a qucik 2.6.x branch update to fix this? Otherwise, we're stuck with the 2.6.11 version for now.

Thanks for the link, btw (two posts above).

**Comment by WPprodigy** [comment]
@RicaNeaga You can hotfix version 2.6.12 w/ the above patch. I zipped up the js file and it's minified counterpart for you and attached it below. Just use them to replace the same files found in woocommerce/assets/js/frontend

[fix.zip](https://github.com/woocommerce/woocommerce/files/708937/fix.zip)

**Comment by drakus72** [comment]
@WPprodigy can confirm your fix fixed it!

Thank you!

**Comment by whereskarlo** [comment]
Thank you, the fixed worked for me as well.

**Comment by UranusCEO** [comment]
I copy and paste the fix but it didn't resolve the issue.

**Comment by claudiosanches** [comment]
@UranusCEO copied and pasted in the correct place? And after you pasted you used Uglify to minify the JS file into `ssets/js/frontend/add-to-cart-variation.min.js `?

**Comment by JeemySBG** [comment]
Hi,

Sorry to be a pain. I am desperate to get this fixed. I've copied both items into the correct folder.

I have not used Uglify to minify the JS - I would not know how - hasn't mikejolley already done this for the fix?

The code in my functions.php reads:

function custom_wc_ajax_variation_threshold( $qty, $product ) {
return 5000;
}

add_filter( ‘woocommerce_ajax_variation_threshold’, ‘custom_wc_ajax_variation_threshold’, 1000, 2 );

**Comment by WPprodigy** [comment]
That snippet is something different than this issue.

Update to version 2.6.13 for the fix to this issue.

**Comment by JeemySBG** [comment]
Hi.

That snippet allows the behaviour above a certain limit. So while its not necessary to be present to fix the issue in the OP with 4 product variations, for me I have to have it there too.

2.6.13 has fixed it. Thanks so much, I did not know this update had come and really needed this fix tonight so I could finalise some orders for clients.

Thanks so so much.

**Comment by claudiosanches** [comment]
@JeemySBG thanks for confirm that 2.6.13 fixed it.

**Comment by UranusCEO** [comment]
Confirm 2.6.13 fixed it! Great Job~!

**Comment by nicholas-chen** [comment]
I updated to 2.6.13 but am still see all the product variables. If I keep the variables to 30 or less it will filter the options but once I go over 30 it shows all product variables again. Please help.

**Comment by WPprodigy** [comment]
@nicholas-chen that's how it is supposed to work for performance reasons, see: https://woocommerce.wordpress.com/2015/07/13/improving-the-variations-interface-in-2-4/

You can use the `woocommerce_ajax_variation_threshold` filter to increase the number from 30 to something higher if you need too.
