### ISSUE TITLE
wc_add_to_cart_message - quantity

### ISSUE THREAD

**Issue by landsman** [woocommerce/woocommerce#12824]
I need override "add to cart" message.

I was found filter "wc_add_to_cart_message" but his parameters are: $message, ~product_id and I need know quantity of posted to cart for plural message. Is possible add third parameter with $quantity or second param $product_id change for $products array??

Thank you

**Comment by mikejolley** [comment]
Looks like an error but we need to check how it was defined in previous versions before multiple products were posted to the function.

**Comment by landsman** [comment]
Thank you @mikejolley!
