### ISSUE TITLE
Wrong currency on Installer for Romania

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#12826]
## EXPLANATION OF THE ISSUE

When running the installer in Romania, the default currency selected is Pounds, but it should be Romanian Leu

![](http://cld.wthms.co/vWLz/O2WELtqy+)

## STEPS TO REPRODUCE THE ISSUE

Install WooCommerce, activate it and run the wizard. I guess you have to proxy as if you were in Romania.

**Comment by claudiosanches** [comment]
@SiR-DanieL can you help fill the follow fields?

```php
	'RO' => array(
		'currency_code'  => 'RON',
		'currency_pos'   => 'left',
		'thousand_sep'   => ',',
		'decimal_sep'    => '.',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'RO',
					'state'    => '',
					'rate'     => '7.0000',
					'name'     => 'VAT',
					'shipping' => true,
				),
			),
		),
	),
```

No idea what weight and dimensions unit use, VAT and currency position.

**Comment by RicaNeaga** [comment]
VAT value is 19% right now. Also curency position is right with space.

Everything else is ok - kg, cm, ron 👍

**Comment by claudiosanches** [comment]
@RicaNeaga this is the correct now?

```php
	'RO' => array(
		'currency_code'  => 'RON',
		'currency_pos'   => 'right_space',
		'thousand_sep'   => '.',
		'decimal_sep'    => ',',
		'num_decimals'   => 2,
		'weight_unit'    => 'kg',
		'dimension_unit' => 'cm',
		'tax_rates'      => array(
			'' => array(
				array(
					'country'  => 'RO',
					'state'    => '',
					'rate'     => '19.0000',
					'name'     => 'VAT',
					'shipping' => true,
				),
			),
		),
	),
```

Thanks a lot for your help :)

**Comment by RicaNeaga** [comment]
Yep. Also VAT translation is ''TVA'', so you can use that instead of VAT :)

Hope Daniel also agrees with me ;)

**Comment by claudiosanches** [comment]
Thanks :)
