### ISSUE TITLE
[2.7] Missing + icon for adding shipping methods

### ISSUE THREAD

**Issue by rspublishing** [woocommerce/woocommerce#12828]
The `+` icon used for adding shipping methods are no longer visible on `admin.php?page=wc-settings&tab=shipping` screen.

Checked under the following conditions (several browsers): 

WooCommerce 2.7.0-beta-1 | WordPress 4.7.1 | Storefront 2.1.6 (fresh install) 

Results: 

<img width="1296" alt="screen shot 2017-01-16 at 12 55 30 pm" src="https://cloud.githubusercontent.com/assets/6198774/21980405/e10b6c88-dbeb-11e6-8a80-8d17e37de00c.png">

It works in WooCommerce 2.6.12 | WordPress 4.7.1 | Storefront 2.1.6 as seen here: 

<img width="1296" alt="screen shot 2017-01-16 at 12 57 15 pm" src="https://cloud.githubusercontent.com/assets/6198774/21980421/fa0d6b28-dbeb-11e6-9e7c-d1608aa27fd2.png">

Cheers!

**Comment by WPprodigy** [comment]
This is on purpose :). https://github.com/woocommerce/woocommerce/issues/11639
