### ISSUE TITLE
change capabilities class-wc-admin-profile.php

### ISSUE THREAD

**Issue by 1ucay** [woocommerce/woocommerce#12827]
Hi, it is possible change capabilities for changing shipping and billing address?

In #148 there is 
if ( ! current_user_can( 'manage_woocommerce' ) ) {

Can be please
if ( ! current_user_can( 'manage_woocommerce_user' ) ) {

**Comment by mikejolley** [comment]
I think this cap makes sense tbh - if you can manage woocommerce and orders, it makes sense you can edit addresses too (because you can in other places).

**Comment by 1ucay** [comment]
...Because we have clients of website, which dont go to settings in WordPress and Woocommerce. They need change customers address. So website client dont have "administrator" role, but for example "editor". They can change all settings in products and orders. They can add new users with address, also can edit users. BUT They can change for example currency on eshop, email template, behavior of stock etc...

apply_filters would be too great! :) Thank you very much!
