### ISSUE TITLE
Renamed wp-content - no pricing, wc not working

### ISSUE THREAD

**Issue by gwgw** [woocommerce/woocommerce#12823]
## EXPLANATION OF THE ISSUE
I renamed sucesfully wp-content dir to content,
in wp-config.php defined new paths for content dir, and plugin dir, also uploads dir
Everything works fine until updating WooCommerce to newest version.

Now when i'm login into dashboard > wc > products i don't see any price values inside products table
When i'm trying to edit product data attributes accordion don't work - i cant open any 
tab content
On single product page there is no price, or add to cart buttons.

I know its not my theme/plugins problem, beacose i delete theme, and switched to default twenty sixteen theme + only WC installed

## STEPS TO REPRODUCE THE ISSUE

Before installing wordpress, try to define new paths in wp-config and rename
wp-content to content
Install wp, and woocommerce add example product, see if adding price with accordion will work.

Why my paths to renamed wp-content dir stopped working???
Is something changed inside WC paths?
Are you using absolute paths ?

**Comment by mikejolley** [comment]
I suggest you look at the source of your pages and ensure ALL scripts src are correct.

https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-assets.php#L96

`WC()->plugin_url()` uses https://codex.wordpress.org/Function_Reference/plugins_url which uses constants such as WP_PLUGIN_URL.

Opening up your inspector (view > developer > js console in chrome) can also reveal any errors after your changes.

**Comment by gwgw** [comment]
Hi, thank you for respond,
as i mention earlier, i turned off all my plugins,
so i only have woocommerce active, then i change theme do default
twenty sixteen, later to storefront
In both cases WC don't work properly, in admin accordion dont work,
in theme - no pricing buttons.
That was weird, when i first renamed wp-content to content,
and setup new urls in wp-config.php my theme and all plugins works fine.
Sorry for the problem, i don't know whats happen, but i will stick with
not renaming folders.
Kind regards,
Gabrielle
