### ISSUE TITLE
Rest API doesn't contain manufacturer field

### ISSUE THREAD

**Issue by etoykan** [woocommerce/woocommerce#12834]
Hello,

WooCommerce supports manufacturer field for products on UI but doesn't return it in Products request.

http://woocommerce.github.io/woocommerce-rest-api-docs/#products

**Comment by justinshreve** [comment]
You must be using a plugin for a manufacturer/brand field -- WooCommerce Core doesn't support that.

Are you using [WooCommerce Brands](https://docs.woocommerce.com/document/wc-brands/)? If so, there [endpoints](https://docs.woocommerce.com/document/wc-brands/#section-14). If not, you will need to contact the author of whatever plugin you are using.

**Comment by etoykan** [comment]
Thanks for the reply!

I am  not using any plugin  but there is the manufacturer field:

![image](https://cloud.githubusercontent.com/assets/3639468/22014011/6ef0186a-dca4-11e6-8a30-3058a1bf12fb.png)

**Comment by justinshreve** [comment]
That looks like a taxonomy added by custom code or a plugin. WooCommerce doesn't contain any code for that. 

https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=manufacturer
https://github.com/woocommerce/woocommerce/blob/7873a328ce871668143465f605df93b1683b0795/includes/class-wc-post-types.php#L35
