### ISSUE TITLE
Download Link not showing in customer e-mail - although woocommerce_downloadable_product_permissions and permission_id there

### ISSUE THREAD

**Issue by ufphoto** [woocommerce/woocommerce#12833]
I am currently setting up a woocommerce product - it's a pdf file that can be purchased and downloaded. When I go through the purchase process and finalize it, everything seems fine. The order appears in the order list on my backend and the download link is also visible. But in the e-mail, there is no download link. I've looked around the web for possible solutions. The one with the table prefix issue doesn't do the trick. All necessary tables and columns are there. Changing the download method doesn't help either. What else did I miss?

## SYSTEM STATUS REPORT
WordPress environment
Home URL:		http://priceless-marketing.com
Site URL:		http://priceless-marketing.com
WC version:		2.7.0
Log directory writable:		 /homepages/46/d618078716/htdocs/clickandbuilds/PricelessMarketing/wp-content/uploads/wc-logs/
WP version:		4.7.1
WP multisite:		–
WP memory limit:		96 MB
WP debug mode:		–
WP cron:		
Sprache:		de_DE
Server environment
Server info:		Apache
PHP version:		7.0.14
PHP post max size:		6 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.38.0, OpenSSL/1.0.1t
SUHOSIN installed:		–
MySQL version:		 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max upload size:		64 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Datenbank
WC database version:		2.7.0
Database prefix	 	FeEMQAiN
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 /homepages/46/d618078716/htdocs/clickandbuilds/PricelessMarketing/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (21)
Akismet Anti-Spam	 	von Automattic – 3.3a1
All in One SEO Pack	 	von Michael Torbert – 2.3.11.1
Magalone	 	von soft-evolution GmbH & Co. KG – 1.0
Contact Form 7	 	von Takayuki Miyoshi – 4.6
Cornerstone	 	von Themeco – 1.3.3
EWWW Image Optimizer	 	von Shane Bishop – 3.2.2
FooEvents for WooCommerce	 	von Grenade – 1.2.16
Loco Translate	 	von Tim Whitlock – 2.0.11
Maintenance	 	von fruitfulcode – 3.2
Medien-Assistent	 	von David Lingren, Fair Trade Judaica – 2.41
Regenerate Thumbnails	 	von Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution	 	von ThemePunch – 5.3.1.5
The Grid	 	von Themeone – 2.2.0
UpdraftPlus - Backup/Restore	 	von UpdraftPlus.Com, DavidAnderson – 1.12.30
WooCommerce	 	von WooThemes – 2.7.0-beta-1
WP Dashboard Notes	 	von Jeroen Sormani – 1.0.8.2
WP-Optimize	 	von David Anderson, Ruhani Rabin, Team Updraft – 2.1.0
X – Custom 404	 	von Themeco – 1.1.1
X – Smooth Scroll	 	von Themeco – 1.0.2
X – Under Construction	 	von Themeco – 1.2.0
X – White Label	 	von Themeco – 1.3.0
Einstellungen
API enabled:		
SSL erzwingen:		–
Währung		EUR (€)
Currency position		right_space
Thousand separator		.
Decimal separator		,
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
WC pages
Shop base:		#209 - /shop
Warenkorb:		#14 - /warenkorb
Kasse:		#15 - /kasse
My account:		#16 - /mein-konto
Theme
Name:		X – Child Theme
Version:		1.0.0
URL des Autors:		http://theme.co/
Child theme:		
Parent theme name:		X
Parent theme version:		4.6.4
Parent theme author URL:		http://theme.co/
WooCommerce support:		
Templates
Archive template:	 	Dein Theme hat eine woocommerce.php-Datei, was dazu führt, dass du das Template woocommerce/archive-product.php nicht überschreibenk annst, da woocommerce.php höher gewichtet wird als archive-product.php. Das ist beabsichtigt, um Darstellungsprobleme zu verhindern.
Überschrieben	 	x/woocommerce/cart/cart-empty.php, 
x/woocommerce/cart/cross-sells.php, 
x/woocommerce/loop/loop-end.php, 
x/woocommerce/loop/loop-start.php, 
x/woocommerce/loop/pagination.php, 
x/woocommerce/notices/error.php, 
x/woocommerce/notices/notice.php, 
x/woocommerce/notices/success.php, 
x/woocommerce/single-product/product-image.php, 
x/woocommerce/single-product/product-thumbnails.php, 
x/woocommerce/single-product/related.php, 
x/woocommerce/single-product/tabs/tabs.php, 
x/woocommerce/single-product/up-sells.php, 
x/woocommerce/single-product-reviews.php

**Comment by WPprodigy** [comment]
Customers will only get the download link in the email if the order is processing or completed (pending your settings).

If you set the product to virtual/downloadable and test purchase it, do you see the download link in the email?

**Comment by ufphoto** [comment]
I set it to not send the link until payment is completed...but no. Even if the order status is completed, I don't get the link. I do get the e-mail where the link should be but no link. The product is virtual and downloadable and all file links are correct. I do however get the link in the admin order overview.

**Comment by mikejolley** [comment]
Screenshot of the email?

**Comment by ufphoto** [comment]
![email_woocommerce](https://cloud.githubusercontent.com/assets/25153932/21994271/2f7d3846-dc1f-11e6-8d72-3fa18d9fb340.jpg)

**Comment by mikejolley** [comment]
Is this 2.7.0 beta 1?

**Comment by ufphoto** [comment]
Yes it is

**Comment by mikejolley** [comment]
This has been fixed since then. Either await beta 2, or use master.

**Comment by ufphoto** [comment]
I have't freaking chosen to use the beta - it somehow got installed from my themeco theme and I have no idea how to get it back to the version that worked fine!

**Comment by mikejolley** [comment]
Install stable 2.6.x from https://wordpress.org/plugins/woocommerce/ then. We have not deployed the beta/2.7 publicly as a stable version so there is nothing in WordPress itself which would allow that. If you believe themeco has somehow done it, report it to themeco so they can correct things.

**Comment by ufphoto** [comment]
I just wrote them. Somehow they are pulling the beta version in their extensions - and I have no clue why. Do I have to do something to the database in order to make the 2.6 version work? And is there anything else to keep in mind?

**Comment by mikejolley** [comment]
AFAIK no it should work, you may just be prompted for a DB update.

They may be pulling trunk from wordpress.org which is the beta for translation.

**Comment by ufphoto** [comment]
Well I hope they fix it. I've lost a hole day messing around with something that simply can't work. Thank you though for your help and pointing me at the problem.

**Comment by ufphoto** [comment]
Just so you know - it didn't work. I was able to delete the beta and upload the 2.6.12 but the product pages don't show up anymore...so back to the start and wait for the theme author to respond. It's really frustrating right now!

**Comment by mikejolley** [comment]
@ufphoto Try going to settings > Permalinks and resaving.

**Comment by ufphoto** [comment]
I don't think it's that - the page does show up but with only the product image showing. No price, no description, even the footer of the page is not there. It's totally messed up

**Comment by mikejolley** [comment]
Wait for a reply from Themeco then - I'd hope they don't require 2.7.x just yet as it's not stable.

**Comment by ufphoto** [comment]
Yeah - I hope so too. :-( Thanks again - I appreciate it!
