### ISSUE TITLE
[2.7] Payment method title missing in order listing

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#12830]
## EXPLANATION OF THE ISSUE

On the order listing page, the indication of the payment method ( for example: "via bacs" ) is missing now. On the order edit page, the indication of the payment method of the order is still present. 

In the first case, $the_order->get_payment_method_title() ( in file class-wc-admin-post-types.php ) is called and seems to be empty. In the second case, $payment_gateways[ $payment_method ]->get_title() ( in file class-wc-meta-box-order-data.php ) is calledand return the payment method title.

**Comment by WPprodigy** [comment]
I'm not to sure how the current structure all works together, but this could work:

```
$payment_gateways = WC()->payment_gateways->payment_gateways();
$payment_method = $payment_gateways[ $data['payment_method'] ];
$order->set_payment_method_title( $payment_method->get_title() );
```

Here: https://github.com/woocommerce/woocommerce/blob/451199a3884423f8dedd0643b8b4fc98b80495e2/includes/class-wc-checkout.php#L320

**Comment by WPprodigy** [comment]
@mikejolley Just curious, but is passing the full object 'deprecated'? https://github.com/woocommerce/woocommerce/blob/2cdf95096326008cb18214fe0586310bf9bea9cc/includes/class-wc-order.php#L1067

**Comment by mikejolley** [comment]
No, there is no deprecation notice here either so I think it's fine.
