### ISSUE TITLE
After upgrade to 2.6.12 Multi-Variation Dropdowns Broken

### ISSUE THREAD

**Issue by kirillminiaev** [woocommerce/woocommerce#12843]
## EXPLANATION OF THE ISSUE

After updating to the latest WooCommerce version (2.6.12), the variation dropdowns seem to be broken. In short, when variating on multiple attributes (e.g. flavor & size), the size dropdown doesn't show correct values for selected flavor

## STEPS TO REPRODUCE THE ISSUE

1. Navigate to a product that has multiple variation selections (for me I have two: **flavor** & **size**)
2. Note: not all flavors have same sizes.
3. When selecting a **flavor**, sizes that don't apply DO NOT get removed from **size** dropdown.
4. Selecting a **size** that DOES NOT EXIST for this **flavor** produced an alert which indicates that the **flavor/size** combo doesn't exist.  Closing the alert resets the variation selectors, but now the selectors no longer show all the options, and the options that do show up, are a combination that doesn't exist in the system.
5. Now stuck in a loop of non-existent products until I refresh the page.

I have disabled all plugins (except for WooCommerce) and reverted to **Twenty Twelve** to identify this issue in WooCommerce core.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: https://ghius.karunaconsulting.com
Site URL: https://ghius.karunaconsulting.com
WC Version: 2.6.12
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.0
PHP Version: 7.0.8-0ubuntu0.16.04.3
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.12
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.12

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #3694 - /shop/
Cart: #3695 - /cart/
Checkout: #3696 - /checkout/
My Account: #3697 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Twelve
Version: 2.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by kirillminiaev** [comment]
Issue identified in #12817

**Comment by drakus72** [comment]
And a hotfix here https://github.com/woocommerce/woocommerce/issues/12817#issuecomment-272908267

**Comment by claudiosanches** [comment]
Duplicated of #12817
