### ISSUE TITLE
Attribute Sorting not working

### ISSUE THREAD

**Issue by anphira** [woocommerce/woocommerce#12847]
## EXPLANATION OF THE ISSUE

WordPress : 4.7.1
Plugins activated : Only WooCommerce 2.6.12
Theme : StoreFront 2.1.6

## STEPS TO REPRODUCE THE ISSUE

I have a store with a product attribute "Size". It's of type "Select" and it has a few hundred terms in it. 

When adding a new product or editing an existing product and I go to Product Data > Attributes the list is in the order the items were added. It doesn't matter what I select for the ordering in of the Size attribute, it's always in this order. So it's ignoring the settings of order by. The behavior is stuck on "custom order", regardless of what ordering I select. 

I've switched to default Storefront theme & deactivated all plugins except for WooCommerce and I have this version on a testing URL if you need access. 

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://www.staging2.xxxx.com
Site URL: https://www.staging2.xxxx.com
WC Version: 2.6.12
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.12
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.12

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #8 - /art/
Basket: #54 - /cart/
Checkout: #55 - /checkout/
My Account: ❌ Page ID is set
but the page does not exist

### Taxonomies ###

Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Storefront
Version: 2.1.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by WPprodigy** [comment]
Can replicate w/ 2.7. Global Attributes aren't going by the correct sort order:

- http://cld.wthms.co/XJEN/5jmPuqcO
- http://cld.wthms.co/GYQK/20FdQcAy
- http://cld.wthms.co/KywV/3fsCeaOc

**Comment by WPprodigy** [comment]
Shouldn't this use `wc_get_product_terms()`: 

https://github.com/woocommerce/woocommerce/blob/0da2f70e13532ef050d4d17d4fa9029e507f05f5/includes/wc-template-functions.php#L2191 ?
