### ISSUE TITLE
Report product WC id on a woocommerce_rest_product_sku_already_exists error

### ISSUE THREAD

**Issue by leandroguimaraes** [woocommerce/woocommerce#12840]
## Problem

When syncing data between an ERP and WooCommerce, during a products batch insert, if I have a "woocommerce_rest_product_sku_already_exists" error, the error info doesn't return the product WooCommerce id. So, if I need to take some action based on this id, I need to call "products" endpoint, with "sku" filter, to get this info. The problem is: if I have lots of products on this situation (I'm on a batch insert), I'll need to do lots of calls to "products" endpoint.

## Proposed solution

On a "woocommerce_rest_product_sku_already_exists" error, server could return the product WooCommerce id as a "conflict_item_id" in something like this:

{
  "create":[
    {
      "id":0,
      "error": {
        "code": "woocommerce_rest_product_sku_already_exists",
        "message": "O REF j\\u00e1 existe em outro produto.",
        "data": {
            "status":400,
            "conflict_item_id": 12345
          }
      }
    }
  ]
}

**Comment by claudiosanches** [comment]
> The problem is: if I have lots of products on this situation (I'm on a batch insert), I'll need to do lots of calls to "products" endpoint.

So there is an easy way to fix it, we can allow search by multiple SKUs.
More easy than generate new data and create conditional code where should works for all classes.

**Comment by claudiosanches** [comment]
This will allow search by multiple SKUs: #12851

**Comment by leandroguimaraes** [comment]
It will demand another API call, another server effort, and lots of data returning from server (full products info), where only an id supposed to be enough...
