### ISSUE TITLE
Cannot select multiple items from media library when adding to product gallery

### ISSUE THREAD

**Issue by avishai** [woocommerce/woocommerce#12856]
## EXPLANATION OF THE ISSUE

It's not possible to add multiple images from the media library to the product image gallery. This modal should allow multiple selection; the current single-selection mode makes it necessarily lengthy to add photos to the gallery.
<img width="1244" alt="7d2d1a72-c2c8-11e6-8dd8-df958d4c5f4d" src="https://cloud.githubusercontent.com/assets/13284/22017287/0470658e-dcaa-11e6-8a5e-e00cab8f3beb.png">

## STEPS TO REPRODUCE THE ISSUE

1. Edit or create a product
1. Click "add images to gallery"
1. Try selecting multiple images

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

`
### WordPress Environment ###

WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.4.6
PHP Version: 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (57) ###

CloudFlare Flexible SSL: by iControlWP – 1.2.2
WP Affiliate Manager: by wp.insider
wpaffiliatemgr – 2.3.6

AfterShip - WooCommerce Tracking: by AfterShip – 1.6.6
Ajax Search for WooCommerce: by Damian Góra – 1.1
WP Offload S3 Lite: by Delicious Brains – 1.1.4
Amazon Web Services: by Delicious Brains – 1.0.1
Better Font Awesome: by MIGHTYminnow & Mickey Kay – 1.6.0
Boxzilla: by ibericode – 3.1.8
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.1.1

Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.4
Crop Thumbnails: by Volkmar Kantor – 0.10.12
Duplicate Post: by Enrico Battocchi – 3.0.3
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.18
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Open Graph Meta Tags by Heateor: by Team Heateor – 1.1.5
WooThumbs - Awesome Product Imagery: by Iconic – 4.6.1
Instagram Feed: by Smash Balloon – 1.4.8
Instock Email Alert for Woocommerce: by Laszlo Kruchio – 1.1.2
WooCommerce Quickview: by Iconic – 3.4.2
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12
MailChimp for WordPress: by ibericode – 4.0.11
MailChimp for WordPress - Top Bar: by ibericode – 1.2.15
WP Menu Cart Pro: by Jeremiah Prummer
Ewout Fernhout – 2.5.7

Ninja Forms: by The WP Ninjas – 3.0.16
Packages Configuration for WooCommerce: by Jason Judge jason@academe.co.uk – 1.2.5
Slider Revolution: by ThemePunch – 5.2.6
Rollbar: by flowdee – 1.0.3
Woocommerce Shipping Calculator On Product Page: by Magerips – 1.4
SendGrid: by SendGrid – 1.10.2
SSL Insecure Content Fixer: by WebAware – 2.2.1
Super Socializer: by Team Heateor – 7.8.7
TinyMCE Advanced: by Andrew Ozz – 4.4.1
WC Vendors Pro: by WC Vendors – 1.3.7
WC Vendors: by WC Vendors – 1.9.5
Widget Importer & Exporter: by churchthemes.com – 1.3.2
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.1.3
Woo Stickers by Webline: by Weblineindia – 1.0.4
Booster Plus for WooCommerce: by Algoritmika Ltd – 1.0.6
WooCommerce Customizer: by SkyVerge – 2.3.1
WooCommerce Stripe Gateway: by Automattic – 3.0.6
Booster for WooCommerce: by Algoritmika Ltd – 2.5.7
WooCommerce Pretty Emails: by MB Création – 1.7
WooCommerce Product Bundles: by WooThemes – 4.14.7
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.10 – 1.10.12 is available
WooCommerce Product Reviews Pro: by WooThemes / SkyVerge – 1.6.4 – 1.6.5 is available
WooCommerce Social Login: by WooThemes / SkyVerge – 2.0.2 – 2.0.4 is available
WooWaitlist: by WPCream.com – 4.0.0
WooCommerce Warranty Requests: by WooThemes – 1.8.5
WooCommerce: by WooThemes – 2.6.8
Post Meta Revisions: by Adam Silverstein - code developed with others – 0.2.2
YITH Infinite Scrolling: by YITHEMES – 1.0.7
YITH WooCommerce Best Sellers: by YITHEMES – 1.0.4
YITH WooCommerce Customer History Premium: by YITHEMES – 1.0.4
YITH WooCommerce Customize My Account Page: by YITHEMES – 1.1.1
YITH WooCommerce Product Bundles: by YITHEMES – 1.0.18
YITH WooCommerce Product Slider Carousel Premium: by YITHEMES – 1.0.13
YITH WooCommerce Save for Later Premium: by YITHEMES – 1.0.5

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #62 - /shop/
Cart: #72 - /cart/
Checkout: #82 - /checkout/
My Account: #92 - /my-account/

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

### Theme ###

Name: MyTheme
Version: 1.0.0
Author URL: http://avishaiweiss.net
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: mytheme/woocommerce/archive-product.php
mytheme/woocommerce/auth/footer.php
mytheme/woocommerce/auth/form-grant-access.php
mytheme/woocommerce/auth/form-login.php
mytheme/woocommerce/auth/header.php
mytheme/woocommerce/cart/cart-empty.php
mytheme/woocommerce/cart/cart-item-data.php
mytheme/woocommerce/cart/cart-shipping.php
mytheme/woocommerce/cart/cart-totals.php
mytheme/woocommerce/cart/cart.php
mytheme/woocommerce/cart/cross-sells.php
mytheme/woocommerce/cart/mini-cart.php
mytheme/woocommerce/cart/proceed-to-checkout-button.php
mytheme/woocommerce/cart/shipping-calculator.php
mytheme/woocommerce/checkout/cart-errors.php
mytheme/woocommerce/checkout/form-billing.php
mytheme/woocommerce/checkout/form-checkout.php
mytheme/woocommerce/checkout/form-coupon.php
mytheme/woocommerce/checkout/form-login.php
mytheme/woocommerce/checkout/form-pay.php
mytheme/woocommerce/checkout/form-shipping.php
mytheme/woocommerce/checkout/payment-method.php
mytheme/woocommerce/checkout/payment.php
mytheme/woocommerce/checkout/review-order.php
mytheme/woocommerce/checkout/terms.php
mytheme/woocommerce/checkout/thankyou.php
mytheme/woocommerce/content-product.php
mytheme/woocommerce/content-product_cat.php
mytheme/woocommerce/content-single-product.php
mytheme/woocommerce/content-widget-product.php
mytheme/woocommerce/emails/admin-cancelled-order.php
mytheme/woocommerce/emails/admin-failed-order.php
mytheme/woocommerce/emails/admin-new-order.php
mytheme/woocommerce/emails/customer-completed-order.php
mytheme/woocommerce/emails/customer-invoice.php
mytheme/woocommerce/emails/customer-new-account.php
mytheme/woocommerce/emails/customer-note.php
mytheme/woocommerce/emails/customer-on-hold-order.php
mytheme/woocommerce/emails/customer-processing-order.php
mytheme/woocommerce/emails/customer-refunded-order.php
mytheme/woocommerce/emails/customer-reset-password.php
mytheme/woocommerce/emails/email-addresses.php
mytheme/woocommerce/emails/email-customer-details.php
mytheme/woocommerce/emails/email-footer.php
mytheme/woocommerce/emails/email-header.php
mytheme/woocommerce/emails/email-order-details.php
mytheme/woocommerce/emails/email-order-items.php
mytheme/woocommerce/emails/email-styles.php
mytheme/woocommerce/emails/plain/admin-cancelled-order.php
mytheme/woocommerce/emails/plain/admin-failed-order.php
mytheme/woocommerce/emails/plain/admin-new-order.php
mytheme/woocommerce/emails/plain/customer-completed-order.php
mytheme/woocommerce/emails/plain/customer-invoice.php
mytheme/woocommerce/emails/plain/customer-new-account.php
mytheme/woocommerce/emails/plain/customer-note.php
mytheme/woocommerce/emails/plain/customer-on-hold-order.php
mytheme/woocommerce/emails/plain/customer-processing-order.php
mytheme/woocommerce/emails/plain/customer-refunded-order.php
mytheme/woocommerce/emails/plain/customer-reset-password.php
mytheme/woocommerce/emails/plain/email-addresses.php
mytheme/woocommerce/emails/plain/email-customer-details.php
mytheme/woocommerce/emails/plain/email-order-details.php
mytheme/woocommerce/emails/plain/email-order-items.php
mytheme/woocommerce/global/breadcrumb.php
mytheme/woocommerce/global/form-login.php
mytheme/woocommerce/global/quantity-input.php
mytheme/woocommerce/global/sidebar.php
mytheme/woocommerce/global/wrapper-end.php
mytheme/woocommerce/global/wrapper-start.php
mytheme/woocommerce/loop/add-to-cart.php
mytheme/woocommerce/loop/loop-end.php
mytheme/woocommerce/loop/loop-start.php
mytheme/woocommerce/loop/no-products-found.php
mytheme/woocommerce/loop/orderby.php
mytheme/woocommerce/loop/pagination.php
mytheme/woocommerce/loop/price.php
mytheme/woocommerce/loop/rating.php
mytheme/woocommerce/loop/result-count.php
mytheme/woocommerce/loop/sale-flash.php
mytheme/woocommerce/myaccount/dashboard.php
mytheme/woocommerce/myaccount/downloads.php
mytheme/woocommerce/myaccount/form-add-payment-method.php
mytheme/woocommerce/myaccount/form-edit-account.php
mytheme/woocommerce/myaccount/form-edit-address.php
mytheme/woocommerce/myaccount/form-login.php
mytheme/woocommerce/myaccount/form-lost-password.php
mytheme/woocommerce/myaccount/form-reset-password.php
mytheme/woocommerce/myaccount/lost-password-confirmation.php
mytheme/woocommerce/myaccount/my-account.php
mytheme/woocommerce/myaccount/my-address.php
mytheme/woocommerce/myaccount/my-downloads.php
mytheme/woocommerce/myaccount/my-orders.php
mytheme/woocommerce/myaccount/navigation.php
mytheme/woocommerce/myaccount/orders.php
mytheme/woocommerce/myaccount/payment-methods.php
mytheme/woocommerce/myaccount/view-order.php
mytheme/woocommerce/notices/error.php
mytheme/woocommerce/notices/notice.php
mytheme/woocommerce/notices/success.php
mytheme/woocommerce/order/form-tracking.php
mytheme/woocommerce/order/order-again.php
mytheme/woocommerce/order/order-details-customer.php
mytheme/woocommerce/order/order-details-item.php
mytheme/woocommerce/order/order-details.php
mytheme/woocommerce/order/tracking.php
mytheme/woocommerce/product-searchform.php
mytheme/woocommerce/single-product/add-to-cart/external.php
mytheme/woocommerce/single-product/add-to-cart/grouped.php
mytheme/woocommerce/single-product/add-to-cart/simple.php
mytheme/woocommerce/single-product/add-to-cart/variable.php
mytheme/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
mytheme/woocommerce/single-product/add-to-cart/variation.php
mytheme/woocommerce/single-product/meta.php
mytheme/woocommerce/single-product/price.php
mytheme/woocommerce/single-product/product-attributes.php
mytheme/woocommerce/single-product/product-image.php
mytheme/woocommerce/single-product/product-thumbnails.php
mytheme/woocommerce/single-product/rating.php
mytheme/woocommerce/single-product/related.php
mytheme/woocommerce/single-product/review-meta.php
mytheme/woocommerce/single-product/review-rating.php
mytheme/woocommerce/single-product/review.php
mytheme/woocommerce/single-product/sale-flash.php
mytheme/woocommerce/single-product/share.php
mytheme/woocommerce/single-product/short-description.php
mytheme/woocommerce/single-product/tabs/additional-information.php
mytheme/woocommerce/single-product/tabs/description.php
mytheme/woocommerce/single-product/tabs/tabs.php
mytheme/woocommerce/single-product/title.php
mytheme/woocommerce/single-product/up-sells.php
mytheme/woocommerce/single-product-reviews.php
mytheme/woocommerce/single-product.php
mytheme/woocommerce/taxonomy-product_cat.php
mytheme/woocommerce/taxonomy-product_tag.php

### WC Vendors Pro ###

Theme Compatability: -
Pro Dashboard Page: - #32
Feedback form page: - #13411
Vendor Shop Permalink: - smiths

### Templates ###

Overrides: mytheme/wc-vendors/dashboard/dashboard.php
mytheme/wc-vendors/dashboard/nav.php
mytheme/wc-vendors/dashboard/product-edit.php
mytheme/wc-vendors/dashboard/reports/overview.php
mytheme/wc-vendors/dashboard/reports/reports.php
mytheme/wc-vendors/dashboard/store-settings.php version 1.3.3 is out of date. The core version is 1.3.7
mytheme/wc-vendors/front/pro-vendor-list.php
mytheme/wc-vendors/store/store-header.php
mytheme/wc-vendors/store/store-ratings.php
mytheme/wc-vendors/store/store-vacation-message.php

: Learn how to update outdated templates
`

**Comment by mikejolley** [comment]
Shift click.. https://dl.dropboxusercontent.com/s/p4piw7vnu31cm83/2017-01-17%20at%2010.52.png
