### ISSUE TITLE
Possible string error in DEV (as per Jan 16 2017)

### ISSUE THREAD

**Issue by tobifjellner** [woocommerce/woocommerce#12855]
## EXPLANATION OF THE ISSUE

Hi,
While checking translations of the DEV branch of WooCommerce, I noted a string that may have incorrect placeholders. (2$ is missing…)

https://plugins.trac.wordpress.org/browser/woocommerce/trunk/templates/emails/plain/customer-invoice.php#L26
An order has been created for you on %1$s. To pay for this order please use the following link: %3$s

**Comment by mikejolley** [comment]
Thanks for the heads up. it's fixed in our master branch.
