### ISSUE TITLE
Automatically Removeing tag from database by removing it from product page

### ISSUE THREAD

**Issue by MMaKenZi** [woocommerce/woocommerce#12858]
## EXPLANATION OF THE ISSUE
I think one of problematic queries is wp-terms
if we add more than thousand products and each one with at least five tags, we have a huge wp-term query

however this is unavoidable
but right now the problem is that if we remove any product which have some tags, it's tags still remain in database 

isn't it possible that by removing product it's tags also removed from database?

**Comment by mikejolley** [comment]
No, WordPress does not work this way.

You can use something like https://en-gb.wordpress.org/plugins/wp-sweep/
