### ISSUE TITLE
[2.7-master] Flexslider single product WC onload height is wrong until resize

### ISSUE THREAD

**Issue by carasmo** [woocommerce/woocommerce#12868]
## EXPLANATION OF THE ISSUE

WooCommerce 2.7-master, FireFox

## STEPS TO REPRODUCE THE ISSUE

Visit single product with or without thumbnails and the height is wrong until resize of the page. 

Incidentally, I used to use FlexSlider and this happened all the time unless I used window.load and not document ready. I use SlickSlider for all slider stuff these days.

Anyway, it looks nice when it works, here is a photo of it not working. It happens with and without my CSS and php.

![screen shot 2017-01-17 at 7 00 40 pm](https://cloud.githubusercontent.com/assets/1124594/22045360/b7fb6c24-dce7-11e6-8ed6-4dc879885d69.png)

**Comment by carasmo** [comment]
See https://github.com/woocommerce/FlexSlider/issues/1320

**Comment by carasmo** [comment]
Here is the same issue from 2012.

https://github.com/woocommerce/FlexSlider/issues/278

Consider removing Flexslider but keep the awesome lightbox.

**Comment by mikejolley** [comment]
See #13009

**Comment by carasmo** [comment]
Thanks! It's fantastic.
