### ISSUE TITLE
Messed up form on Checkout page 2.7-beta

### ISSUE THREAD

**Issue by carasmo** [woocommerce/woocommerce#12867]
## EXPLANATION OF THE ISSUE

WooCommerce 2.7-beta1

## STEPS TO REPRODUCE THE ISSUE

Visit Checkout page

See the bottom of this screen shot, puts email field at the bottom looks horrible. 

Turned off all my custom CSS and functions and it still does this.

![woo-checkout-2 7-beta-messedup](https://cloud.githubusercontent.com/assets/1124594/22042933/4ca8a9de-dcdb-11e6-8a39-b82f1682060f.png)

Version 2.6 works fine
![woo-checkout-2 6 x-working-fine](https://cloud.githubusercontent.com/assets/1124594/22042934/4caf2962-dcdb-11e6-9943-704b2bcb1edc.png)

**Comment by mbgrafik** [comment]
i have the same experience. The dropdown "Returning Customer" also does not work.  (WC 2.7 beta1)

**Comment by mikejolley** [comment]
Are you using a checkout field customiser?

**Comment by carasmo** [comment]
Nope. I also un-comment my css and my woocommerce functions include into and it still happens.

**Comment by carasmo** [comment]
All custom styles and functions removed, it still happens:
![woocommerce-css-and-functions-removed](https://cloud.githubusercontent.com/assets/1124594/22046057/37e21c2c-dcec-11e6-8d17-e43e9f225ab6.png)

No theme style.css just WooCommerce.css, still wonky.
![no-theme-styles-just-woo-styles](https://cloud.githubusercontent.com/assets/1124594/22046058/37e364ce-dcec-11e6-9969-3f34d8190fa0.png)

**Comment by mikejolley** [comment]
Can you grab master instead of beta 1. This does look familiar and may have been patched already.

**Comment by carasmo** [comment]
Fixed with -master. sorry.

**Comment by mbgrafik** [comment]
<p class="form-row validate-required woocommerce-invalid woocommerce-invalid-required-field" id="account_password_field" data-sort="" style="
/* clear: both; */">

/* clear: both; */ ? maybe uncomment? :) 
Dropdown also solved with latest master

**Comment by carasmo** [comment]
This particular issue is resolved with the master, however it was the lack of "form-row-last" on the paragraph that was the issue.

**Comment by mbgrafik** [comment]
Sorry, i'm new to github. Should i open a new issue?
