### ISSUE TITLE
Possible site-wide notice bug for Twenty Seventeen

### ISSUE THREAD

**Issue by seb86** [woocommerce/woocommerce#12860]
## EXPLANATION OF THE ISSUE

All I did was enable the store wide notice and entered my message to promote a special day and press save. I was expecting to see a purple bar at the top on the homepage but nothing was showing. I looked further down the page and still no bar. I have WP Rocket installed so I made sure my site cache was cleared and my browser cache but still no bar was showing.

I looked on another page. Still no bar at the top, however, when I go to the bottom of that page there was the store notice only it was not styled. I inspected the element and found that there was no CSS loaded for it. I suspect this is because maybe you have not put any CSS for the store notice globally and the WooCommerce CSS are not loaded on standard pages, only the WooCommerce pages, and single products.

But I'm just guessing here. I have not looked further into the matter.

Is it just my site and if so what do you think could of caused this?

## STEPS TO REPRODUCE THE ISSUE

Have Twenty Seventeen activated first then follow these steps.

1. Go to WooCommerce Settings
2. Enable the Store Notice
3. Enter any Store Notice Text
4. Save Settings
5. View Homepage and see results.

### WordPress Environment ###

Home URL: https://autoloadnextpost.com
Site URL: https://autoloadnextpost.com
WC Version: 2.6.12
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.14
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.26
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.12
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (36) ###

A2 Optimized WP: by A2 Hosting – 2.0.5
Akismet: by Automattic – 3.2
WP Offload S3 Lite: by Delicious Brains – 1.1.5
Amazon Web Services: by Delicious Brains – 1.0.1
AMP: by Automattic – 0.4.2
Attachment Slug: by Sébastien Dumont – 0.0.1
Auto Load Next Post: by Sébastien Dumont – 1.4.9
Chatra live chat software: by Chatra – 1.0.2
Easy Plugin Stats: by Nick Diego – 1.0.0
Glue for Yoast SEO & AMP: by Joost de Valk – 0.3.3
Google Analytics by MonsterInsights: by MonsterInsights – 5.5.4
Hotjar Connecticator: by Blue Medicine Labs – 1.1.1
Imagify: by WP Media – 1.6.3
Jetpack by WordPress.com: by Automattic – 4.4.2
MailChimp for WordPress: by ibericode – 4.0.12
MailChimp Activity: by ibericode – 1.0.5
No Self Pings: by Michael D. Adams – 0.2
SearchWP Diagnostics: by Jonathan Christopher – 1.4.1
SearchWP Live Ajax Search: by Jonathan Christopher – 1.1.8
SearchWP WooCommerce Integration: by SearchWP LLC – 1.1.10
SearchWP: by SearchWP LLC – 2.8.6
SecuPress — WordPress Security: by WP Media – 1.2
Shortcodes in Sidebar: by BigBrother – 2.0
WooCommerce Cart Reports: by WPBackOffice – 1.1.13
WooCommerce Stripe Gateway: by WooCommerce – 3.0.7
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Mixpanel: by WooThemes / SkyVerge – 1.9.3
WooCommerce Name Your Price: by Kathy Darling – 2.4.2
WooCommerce Product Add-ons: by Automattic – 2.7.22
WooCommerce: by WooThemes – 2.6.12
WooCommerce Helper: by WooCommerce – 1.7.2
Yoast SEO: by Team Yoast – 4.1
WP Offload S3 Filter Image File Types: by Sebastien Dumont – 0.0.1
WP Rocket: by WP Media – 2.9.2
WP Time Capsule: by Revmakx – 1.6.1
WPForms Lite: by WPForms – 1.3.1.2

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: –

### WC Pages ###

Shop Base: #30 - /shop/
Basket: #31 - /cart/
Checkout: #32 - /checkout/
My Account: #33 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Fixed in #12863.

2.7 unaffected.

**Comment by seb86** [comment]
@mikejolley Great. 👍
