### ISSUE TITLE
Change automatic cancelation event time

### ISSUE THREAD

**Issue by lidya1859** [woocommerce/woocommerce#12872]
I have read this problem here in https://github.com/woocommerce/woocommerce/issues/3367 before, but it doesn't really help me.
In my case, I want a different hold stock time and cron event time. I want to check hourly if the unpaid order was being paid in 24 hours. So I try to add this function in my theme.
http://pastebin.com/LU68Wb1i
I have check it in WP-Cron event list, the event already exists. But it doesn't re-create a new event after running. And I need to save inventory setting first to re-create the event. Anyway, the cancelation works fine.
I'm using WC 2.6.7 WP 4.7.1

**Comment by mikejolley** [comment]
Don't schedule a single event, schedule a recurring one. https://codex.wordpress.org/Function_Reference/wp_schedule_event
