### ISSUE TITLE
Let themes recommend image sizes

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#12878]
Problem: People don't know what thumbnail sizes to set. This can lead to thumbnails that are too big = wasted bandwidth. Or worse, thumbnails that are too small which = blurry distorted images. This is made worse by the fact that the actual display of the images controlled by the theme and can differ from one to the next.

Something like this could be nice;

```
add_theme_support( 'woocommerce', array(
				'catalog_image_width'    => '500',
				'catalog_image_height'   => '500',
				'single_image_width'     => '800',
				'single_image_height'    => '800',
				'thumbnail_image_width'  => '200',
				'thumbnail_image_height' => '200',
			) );
```

Core could then pull that data into the display settings screen, notify the user of the recommended sizes and alert them if their current settings are too small. 

To reduce user-interaction with these confusing settings further, we could even just update the settings automatically, based on the theme recommended dimensions, on theme switch. Then all we'd need to do is prompt thumbnail regeneration.

**Comment by seb86** [comment]
If the theme already has the sizes preset, is the user still able to change them after or will the fields be disabled?

**Comment by jameskoster** [comment]
@seb86 they'd still be able to change them. We should be mindful of the fact that someone could customise the theme in a way that impacts the frontend image display and subsequently need to  change the settings.

**Comment by mbgrafik** [comment]
"Something like this could be nice; ......."
i like this idea

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/17557
