### ISSUE TITLE
Display/function issue with product variations

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce#12870]
## EXPLANATION OF THE ISSUE
WooCommerce Version 2.6.12 

When using very limited product variations, drop down selection menus do no perform correctly.

## STEPS TO REPRODUCE THE ISSUE

- Create a variable product

- Add two Attributes to be used as variations (eg. Size & Color)

- On the product variations, add each attribute only once
Eg. If using Size: Small, Medium, Large  and Color: Blue, Red, Green, you would have 3 product variations that look something like this:

Small - Blue
Medium - Red
Large - Green
![](http://cld.wthms.co/J6pd/1sN3gUQU+)
Image Link: http://cld.wthms.co/J6pd/1sN3gUQU

- Save your product

- From the front end use the drop down menus to select a combination of the variations

**##Expected Results**

When making a selection in one drop down, the other drop down restricts to the only available option. So if you choose "Small" as your first attribute, the only option for the second attribute in our example should be "Blue"

**##Actual Results**

After selecting your first attribute, you still have the ability to select any of the second attributes.

If you select an invalid combination, you receive a warning and then the both attribute drop downs will limit themselves to results that cannot be used in combination with each other. 

Your first attribute drop down will now only show the matching option to what you originally chose as the second attribute.
Your second attribute will now only show the matching option to what you originally chose as the first attribute.

Because of this, you can no long make any valid selection even after "clearing" the selections:

![](http://cld.wthms.co/fySl/DmWLLCJj+)
Image Link: http://cld.wthms.co/fySl/DmWLLCJj

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: https://example.com
Site URL: https://example.com
WC Version: 2.6.12
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.14
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.51.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.12
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (3) ###

WooCommerce Stripe Gateway: by WooCommerce – 3.0.7
WooCommerce Square: by WooCommerce – 1.0.12
WooCommerce: by WooThemes – 2.6.12

### Settings ###

Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #104 - /shop/
Cart: #105 - /cart/
Checkout: #106 - /checkout/
My Account: #107 - /my-account/

### Taxonomies ###

Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
photography (photography)
shopify (shopify)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Storefront
Version: 2.1.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/12817

**Comment by SpnsAlopez** [comment]
This exact issue reappeared to me after upgrading to 3.2.3. Basically, after setting up variations if you select an option from the first variable drop down, the second variable drop down never refresh with the corresponding variation's options instead it remains with all options displayed

**Comment by evanscottgray** [comment]
Seeing the same issue with 3.2.4 it seems.

Selection of a variable drop down appears to have no bearing on the variables in a second drop down. All options are displayed at all times.

**Comment by mikejolley** [comment]
That expected if there are > 30 variations. https://iconicwp.com/blog/modify-ajax-variation-threshold/
