### ISSUE TITLE
Issue with selecting variations on the frontend

### ISSUE THREAD

**Issue by c9dd** [woocommerce/woocommerce#12879]
https://github.com/woocommerce/woocommerce/issues/12817

## EXPLANATION OF THE ISSUE

Select fields on products with variations will not allow the user to select those varations as the options on the select fields are set to disabled.

Looked to be a issue that was addressed here https://github.com/woocommerce/woocommerce/issues/12817 but the 'fix' does not fix the issue.

Tried rolling back to .11 and that allows the select fields to be selected for the first time, but when the user completes the selection the fields then become disabled and do not allow for any changes as the fields are once again set to disabled.

## STEPS TO REPRODUCE THE ISSUE

Create a variable product

Add two Attributes to be used as variations (eg. Size & Color)

On the product variations, add each attribute only once
Eg. If using Size: Small, Medium, Large and Color: Blue, Red, Green, you would have 3 product variations that look something like this:

Small - Blue
Medium - Red
Large - Green

Image Link: http://cld.wthms.co/J6pd/1sN3gUQU

Save your product

From the front end use the drop down menus to select a combination of the variations

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://dev.allgood.co.uk
Site URL: http://dev.allgood.co.uk
WC Version: 2.6.12
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.14-1~dotdeb+8.1
PHP Post Max Size: 10 MB
PHP Time Limit: 60
PHP Max Input Vars: 6500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.12
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (60) ###

Advanced Custom Fields: Dynamic Table Field: by Geet Jacobs – 1.0.1
Advanced Custom Fields: Divider: by Kreshnik Hasanaj – 1.0.0
ACF Accordion: by Bogdan Dragomir – 1.1.1
Advanced Custom Fields: Button: by Matt Cromwell – 1.0.0
Advanced Custom Fields: Field Selector: by Daniel Pataki – 4.0.0
ACF Fold Flexible Content: by Urban Sanden – 1.4.1
Advanced Custom Fields: Hidden Field: by erictr1ck – 1.0.0
Advanced Custom Fields: Image Crop Add-on: by Anders Thorborg – 1.4.9
Advanced Custom Fields: PayPal Field: by Michael Rodriguez – 2.0.0
Admin Color Schemes: by WordPress Core Team – 2.2
Advanced Custom Fields Repeater Collapser: by Mark Root-Wiley – 1.4.3
Advanced Custom Fields: Code Area: by Taylor Mitchell-St.Joseph – 1.0.1
Advanced Custom Fields: Component Field: by Alan Chen – 1.0.11
Advanced Custom Fields: Field Snitch: by Stupid Studio – 1.0.3
Advanced Custom Fields: Font Awesome: by Matt Keys – 1.7.3
Advanced Custom Fields: Leaflet Field: by Jens Nilsson – 1.2.1
Advanced Custom Fields: Limiter: by Atomic Smash - David Darke – 1.1.1
Advanced Custom Fields: Nav Menu Field: by Faison Zutavern – 2.0.0
Advanced Custom Fields: Number Slider: by Q Studio – 0.4.2
Advanced Custom Fields PRO: by Elliot Condon – 5.5.4
Advanced Custom Fields: Table Field: by Johann Heyne – 1.1.13
Advanced Custom Fields: Widget Area Field: by Dustin Filippini – 1.0.0
Advanced Custom Fields: Widget: by Direct Basing – 1.0.2
Advanced Custom Fields: Auto-generated value: by Kindly – 1.0.0
Beautiful taxonomy filter: by Jonathan de Jong – 2.1.0
Admin Columns: by AdminColumns.com – 2.5.6.4
Custom Post Type UI: by WebDevStudios – 1.5.1
Duplicate Post: by Enrico Battocchi – 3.1.2
Enable Media Replace: by Måns Jonasson – 3.0.5
Gravity Forms: by rocketgenius – 2.1.2
Gravity Forms Campaign Monitor Add-On: by rocketgenius – 3.4.1
Gravity Forms User Registration Add-On: by rocketgenius – 3.6
Jetpack by WordPress.com: by Automattic – 4.5
ACF QuickEdit Fields: by Jörn Lund – 1.0.0
My Eyes Are Up Here: by interconnect/it – 1.1.8
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Relevanssi: by Mikko Saari – 3.5.6.1
Soil: by Roots – 3.7.0
HTML5 Boilerplate .htaccess: by Roots –
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1
Simple Custom Post Order: by Sameer Humagain – 2.3
Simple Image Sizes: by Rahe – 3.1.1
Simple Local Avatars: by Jake Goldman
10up – 2.0

Slash Edit: by ronalfy – 1.1.1
Advanced Custom Fields: Gravity Forms Field: by @adam_pope of @stormuk – 1.1.0
Stream: by XWP – 3.1.1
Advanced Custom Fields: Reusable Field Group: by Tyler Bruffy – 1.0.2
User Switching: by John Blackbourn – 1.0.9
W3 Total Cache: by Frederick Townes – 0.9.5.2
WooCommerce Grid / List toggle: by jameskoster – 1.1.0
WooCommerce: by WooThemes – 2.6.12
WooSidebars: by WooThemes – 1.4.3
WooThemes Helper: by WooThemes – 1.3.0
Wordfence Security: by Wordfence – 6.2.9
Yoast SEO: by Team Yoast – 4.1
WordPress Access Areas: by Jörn Lund – 1.5.1
WP All Import Pro: by Soflyy – 4.4.1
WP Smush: by WPMU DEV – 2.5.3
WPFront User Role Editor: by Syam Mohan – 2.13
Yoast SEO: ACF Analysis: by Marcus Forsberg & Team Yoast – 1.2.0

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /products/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Overrides: –
`

**Comment by mikejolley** [comment]
Please search the closed issues, this has been dealt with multiple times and will be fixed in the next point release.

**Comment by c9dd** [comment]
I did, but the solutions didn't seem to help. Thought my feedback would be a good thing.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/12817 resolves it. If the fields are disabled, especially in older versions, it's likely the variations themselves either being disabled in status, or without prices defined.

**Comment by mikejolley** [comment]
Working example proof post-patch https://dl.dropboxusercontent.com/s/a85gfpdzwvdymst/2017-01-18%20at%2015.10.png

**Comment by c9dd** [comment]
Hi Mike, I'm not trying to be difficult or waste your time. I'm testing it out locally too with Woo dummy data and it's not fixing the issue. I thought you might want to know.

![screen shot 2017-01-18 at 15 11 41](https://cloud.githubusercontent.com/assets/2241437/22069478/79e258d6-dd90-11e6-9e04-20b37e9f57b7.png)

**Comment by mikejolley** [comment]
Without being able to reproduce it there isn't much I can do my side. I suggest you ensure those variations have prices and the 'enabled' checkbox on, and resave. That is not dummy data either.

Also, there is some kind of custom select box there.

**Comment by c9dd** [comment]
I've made a quick video to demo the issue https://screencast.com/t/ooH2O5l5r63

**Comment by c9dd** [comment]
There is a custom select box, but it has been fine in the past

**Comment by mikejolley** [comment]
> There is a custom select box, but it has been fine in the past

Can you test another theme? Custom select boxes need custom handling or they won't work. See notes in https://woocommerce.wordpress.com/2016/12/22/woocommerce-2-6-10-fix-release-notes/

**Comment by c9dd** [comment]
Hmm... I will investigate

**Comment by c9dd** [comment]
Just encase this helps anyone else, I've narrowed this down to something happening here 

`Uncaught TypeError: Cannot read property 'length' of undefined`

`<script>
    jQuery(document).ready(function(e){function t(e,t){var r=[];for(var i=0;i<e.length;i++){var s=e[i],o=s.variation_id;n(s.attributes,t)&&r.push(s)}return r}function n(e,t){var n=!0;for(attr_name in e){var r=e[attr_name],i=t[attr_name];r!==undefined&&i!==undefined&&r.length!=0&&i.length!=0&&r!=i&&(n=!1)}return n}e("form.variations_form").on("click",".reset_variations",function(t){e(this).closest("form.variations_form").find(".variations select").val("").change();return!1}).on("change",".variations select",function(t){$variation_form=e(this).closest("form.variations_form");$variation_form.find("input[name=variation_id]").val("").change();$variation_form.trigger("woocommerce_variation_select_change").trigger("check_variations",["",!1]);e(this).blur();e().uniform&&e.isFunction(e.uniform.update)&&e.uniform.update()}).on("focusin",".variations select",function(t){$variation_form=e(this).closest("form.variations_form");$variation_form.trigger("woocommerce_variation_select_focusin").trigger("check_variations",[e(this).attr("name"),!0])}).on("check_variations",function(n,r,i){var s=!0,o=!1,u=!1,a={},f=e(this),l=f.find(".reset_variations");f.find(".variations select").each(function(){e(this).val().length==0?s=!1:o=!0;if(r&&e(this).attr("name")==r){s=!1;a[e(this).attr("name")]=""}else{value=e(this).val().replace(/&/g,"&").replace(/"/g,'"').replace(/'/g,"'").replace(/</g,"<").replace(/>/g,">");a[e(this).attr("name")]=value}});var c=parseInt(f.attr("data-product_id")),h=window["product_variations_"+c];h||(h=window.product_variations);var p=t(h,a);if(s){var d=p.pop();if(d){f.find("input[name=variation_id]").val(d.variation_id).change();f.trigger("found_variation",[d])}else{f.find(".variations select").val("");i||f.trigger("reset_image")}}else{f.trigger("update_variation_values",[p]);i||f.trigger("reset_image");r||f.find(".single_variation_wrap").slideUp("200")}o?l.css("visibility")=="hidden"&&l.css("visibility","visible").hide().fadeIn():l.css("visibility","hidden")}).on("reset_image",function(t){var n=e(this).closest(".product"),r=n.find("div.images img:eq(0)"),i=n.find("div.images a.zoom:eq(0)"),s=r.attr("data-o_src"),o=r.attr("data-o_title"),u=i.attr("data-o_href");if(s&&u&&o){r.attr("src",s).attr("alt",o).attr("title",o);i.attr("href",u)}}).on("update_variation_values",function(t,n){$variation_form=e(this).closest("form.variations_form");$variation_form.find(".variations select").each(function(t,r){current_attr_select=e(r);current_attr_select.find("option:gt(0)").attr("disabled","disabled");var i=current_attr_select.attr("name");for(num in n){var s=n[num].attributes;for(attr_name in s){var o=s[attr_name];if(attr_name==i)if(o){o=e("<div/>").html(o).text();o=o.replace(/'/g,"\\'");o=o.replace(/"/g,'\\"');current_attr_select.find('option[value="'+o+'"]').removeAttr("disabled")}else current_attr_select.find("option").removeAttr("disabled")}}});$variation_form.trigger("woocommerce_update_variation_values")}).on("found_variation",function(t,n){var r=e(this),i=e(this).closest(".product"),s=i.find("div.images img:eq(0)"),o=i.find("div.images a.zoom:eq(0)"),u=s.attr("data-o_src"),a=s.attr("data-o_title"),f=o.attr("data-o_href"),l=n.image_src,c=n.image_link,h=n.image_title;r.find(".variations_button").show();r.find(".single_variation").html(n.price_html+n.availability_html);if(!u){u=s.attr("src")?s.attr("src"):"";s.attr("data-o_src",u)}if(!f){f=o.attr("href")?o.attr("href"):"";o.attr("data-o_href",f)}if(!a){a=s.attr("title")?s.attr("title"):"";s.attr("data-o_title",a)}if(l&&l.length>1){s.attr("src",l).attr("alt",h).attr("title",h);o.attr("href",c)}else{s.attr("src",u).attr("alt",a).attr("title",a);o.attr("href",f)}var p=r.find(".single_variation_wrap");n.sku?i.find(".product_meta").find(".sku").text(n.sku):i.find(".product_meta").find(".sku").text("");p.find(".quantity").show();!n.is_in_stock&&!n.backorders_allowed&&r.find(".variations_button").hide();n.min_qty?p.find("input[name=quantity]").attr("data-min",n.min_qty).val(n.min_qty):p.find("input[name=quantity]").removeAttr("data-min");n.max_qty?p.find("input[name=quantity]").attr("data-max",n.max_qty):p.find("input[name=quantity]").removeAttr("data-max");if(n.is_sold_individually=="yes"){p.find("input[name=quantity]").val("1");p.find(".quantity").hide()}p.slideDown("200").trigger("show_variation",[n])});e("form.variations_form .variations select").change()});
    </script>`

**Comment by mikejolley** [comment]
https://codex.wordpress.org/Debugging_in_WordPress#SCRIPT_DEBUG
