### ISSUE TITLE
Extra Filter for Variation Selection on Product Backendpage

### ISSUE THREAD

**Issue by sebuchy1991** [woocommerce/woocommerce#12875]
I added some custom "product_data_panels" and copied the functionality of the "attributes_panel" to manage some "custom_attribute_types". I need this to cluster the attributes, cause they are simply too much to handle.

The Problem is that i cannot filter the "attributes" that i can add my "custom_attributes" to be shown at Variation Selection Tab.

/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#line_602

It would help me a lot if you can add a filter, before rendering the attributes.

**Comment by mikejolley** [comment]
You could enhance the select box so it includes search instead perhaps? But if you need a filter, please submit a PR proposal so we can see where/what for and we'll consider merging it.

https://help.github.com/articles/creating-a-pull-request/
