### ISSUE TITLE
Squashed menu on 2017 theme. DESKTOP ONLY

### ISSUE THREAD

**Issue by seb86** [woocommerce/woocommerce#12871]
## EXPLANATION OF THE ISSUE

Another issue with theme 2017 with the navigation menu. I think it might be the page wrapper as the sidebar is also a little squashed too compared to other pages.

What a full menu looks like on standard pages or posts.

![Full Menu on 2017](https://cldup.com/qsBHVaTCr4.png)

What a full menu looks like on any WooCommerce page including single products.

![Full Menu on 2017](https://cldup.com/AryYD0DjQr.png)

Have you seen this before?

**Comment by mikejolley** [comment]
Identical with or without woocommerce on my side. Also inspected the page and the wrapper UL has identical width.

**Comment by seb86** [comment]
Weird. Maybe you already fixed it for the 2.7 release. I'm currently using the latest release of WooCommerce and 2017 theme. No modifications made.

**Comment by mikejolley** [comment]
I tested 2.6 too.

**Comment by seb86** [comment]
I will look into the matter further on my end then.
