### ISSUE TITLE
Display settings screen - install regenerate thumbnails inline

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#12880]
Kind of linked to #12878 (improving image size UX).

As we all know, changing image dimension settings in WooCommerce requires the user to install and run Regenerate Thumbnails for those changes to take effect.

Currently, we do not make that process very user friendly. We link to the Regenerate Thumbnails plugin page on .org and then let the user figure things out for themselves.

Let's install the plugin inline, in one click. Then, if they change the settings, alert them to regenerate the thumbnails.

**Comment by mikejolley** [comment]
Plan: Track defined image sizes.

When defined image sizes change, queue a notice.

Notice shows something along the lines of:

`Your store image size settings have been changed. To apply these changes to all existing images, please regenerate thumbnails`.

Notice must be dismissible. And dismissed once the action has been taken.

If plugin exists, jump to the regen thumbnails screen. 

If plugin does not exist, we have 3 options:

1. Bundle something very similar and use our background processing to do the resizing without a plugin.
2. Install regen thumbnails inline
3. Link to regen thumbnails plugin in plugin browser.

**Comment by mikejolley** [comment]
If we can get this running auto in the background that would trump all suggestions.
