### ISSUE TITLE
Unable to Add Variant Attributes

### ISSUE THREAD

**Issue by wildedesigns** [woocommerce/woocommerce#12882]
## EXPLANATION OF THE ISSUE

I am new to WooCommerce and am running the most recent version of both it and all plugins. I can go to my Attributes section and build a set of attributes. When I go into a product, I can even add the attributes in to be used as variants (shown below). 

<img width="567" alt="screen shot 2017-01-18 at 10 14 11 am" src="https://cloud.githubusercontent.com/assets/25204610/22072282/7a55b7c8-dd67-11e6-92be-7069c03e6564.png">

It shows that it is saving the attributes. Also good.

<img width="556" alt="screen shot 2017-01-18 at 10 14 15 am" src="https://cloud.githubusercontent.com/assets/25204610/22072334/ad8e2be8-dd67-11e6-9681-3ad306475620.png">

Unfortunately, after updating the item, everything seems to be cleared, and I get this message again.

<img width="752" alt="screen shot 2017-01-18 at 10 14 50 am" src="https://cloud.githubusercontent.com/assets/25204610/22072354/b7d0009a-dd67-11e6-95e2-3d8ae1a1a421.png">

Have any of you run into this? Any tips? I'm excited to get my new shop set up, but I have a lot of items with variants, so that's a definite "must" feature for me.

## STEPS TO REPRODUCE THE ISSUE

1. Create a set set of options under Attributes and save them.
2. Go to or create a new product and visit the Attributes section of the product after setting the product type to variant.
3. Load the attributes you wish to add and set them to also be listed as variants.
4. Save.
5. Update the product.
6. Cry a little because it happened again.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: https://wildehandmade.com
Site URL: https://wildehandmade.com
WC Version: 2.6.12
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.12
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (8) ###

Share Buttons by AddThis: by The AddThis Team – 5.3.4
Amazon Associates Link Builder: by Amazon Associates Program – 1.4
Intergeo - Google Maps Plugin: by Themeisle – 2.1.0
Free & Simple Contact Form Plugin - PirateForms: by Themeisle – 1.1.3
Printful Integration for WooCommerce: by Printful – 1.2.7
WooCommerce PayPal Powered by Braintree Gateway: by WooThemes – 1.2.6
WooCommerce Stripe Gateway: by WooCommerce – 3.0.7
WooCommerce: by WooThemes – 2.6.12

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Shop Isle
Version: 1.1.6.15
Author URL: http://themeisle.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by mikejolley** [comment]
In your screenshot you're not actually adding any options to the attribute?

**Comment by wildedesigns** [comment]
Do I need to add them again after I've already added them in the Attributes section (I find it stupidly confusing to name the section the same way on the item page and on the page where you create the thing, but maybe that's just me)? My understanding from other users and the workflow here was that you created the variants in the main Attributes section, then you loaded that option in the Attributes section of the product. Is that incorrect?

**Comment by mikejolley** [comment]
Add some values to the 'attributes' section first, then save. Then you can start adding variations which map to said attributes.

**Comment by wildedesigns** [comment]
<img width="505" alt="screen shot 2017-01-18 at 10 31 38 am" src="https://cloud.githubusercontent.com/assets/25204610/22072872/55cd222c-dd69-11e6-9034-81939d0296f8.png">

Okay, I had done this - but I'm guessing that I may be carrying some assumptions over from my days on NOPcommerce where this was then the set of variants. So whether you add terms for the Attribute on the Attributes page or not, you still have to add them under Attributes in the Product Data?

**Comment by wildedesigns** [comment]
Thank you for your help on this! I seem to have added the variants, and it now insists that the products are not in stock, though the stock quantity clearly says otherwise. 

<img width="437" alt="screen shot 2017-01-18 at 10 42 37 am" src="https://cloud.githubusercontent.com/assets/25204610/22073438/f76db960-dd6a-11e6-843e-28e36045b96c.png">

<img width="494" alt="screen shot 2017-01-18 at 10 42 29 am" src="https://cloud.githubusercontent.com/assets/25204610/22073495/13ce09c0-dd6b-11e6-994c-61486d5bbe6e.png">

**Comment by claudiosanches** [comment]
@wildedesigns looks better you try our videos first: https://docs.woocommerce.com/document/woocommerce-guided-tour-videos/#section-4 since this is just settings issues and not a bug on WooCommerce. Thanks.

**Comment by mikejolley** [comment]
Yep, you're missing prices. Those are required.

**Comment by wildedesigns** [comment]
Thank you, @mikejolley! I appreciate the help and patience. Sorry to frustrate you, @claudiosanches. I did say I was new at this, and there are many aspects that, even if you watch the videos, are somewhat counterintuitive. Throughout this process I was working with another friend who's been using the software for significantly more time and she was having similar issues. While this may not be a bug, I do think it's fair to note that some of the design aspects may be poor.

**Comment by claudiosanches** [comment]
@wildedesigns great, so please fell free to submit Pull Request and help us to improve all aspects of the design that bothers you.

**Comment by mikejolley** [comment]
>  I do think it's fair to note that some of the design aspects may be poor

Agreed. We're working on a new UI but it's a long way off. Variations are tricky tbh - they are inherently complex, so unless you lose functionality it's always going to be less than straightforward. If the docs and videos don't help, submit a doc report and someone can update them.
