### ISSUE TITLE
Coupon calculation

### ISSUE THREAD

**Issue by okawarix** [woocommerce/woocommerce#12886]
I need to know how can I set up a coupon which will discount the total amount on the cart and not the subtotal.

Example:
**Product 1** costs 20.00$
**Shipping cost**: 2.86$

**Product 2** costs 5.87
**Shipping cost**: FREE

Coupon used: 100 (**100% off)**
Total to be paid: **2.86$** _**(shipping of Product 1)**_

How can I make the coupon to deduct 100% of the total so the costumer will 'pay' nothing?

See picture from the cart: http://imgur.com/sIDwLF9 

Thanks

**Comment by mikejolley** [comment]
Coupons cannot discount shipping costs. If you need shipping to be free, you'll need to enable it conditionally with code (if cart value is 0).

**Comment by okawarix** [comment]
How can I do that?

**Comment by mikejolley** [comment]
I don't have a snippet for you, but there is an 'availability' filter in each shipping method for devs to hook into.
