### ISSUE TITLE
Can't access wp_get_attachment_metadata for downloadable files

### ISSUE THREAD

**Issue by digitalchild** [woocommerce/woocommerce#12892]
Downloadable files no longer have the attachment_id stored in the _downloadable_files meta key so we can't use the built in meta data function to get more information about the file. Only has the name and file url with the md5 of the file as the array index. 

How can we get all the metadata stored for files uploaded such as dimensions now there is no apparent link between woocommerce downloadable files and the wp_media uploader file.

**Comment by mikejolley** [comment]
Well, it seems you cannot :) Media library upload is purely there for convenience - there was never an intention to be able to link products to media library items in this manner, nor to store extra data outside of the downloads array. We just re-use it for a simple upload modal.

Downloads can be pure URLs (pasted) and don't require a link to an attachment (the URL can even be off-site), so it doesn't make sense to maintain an association in core.

If you want to force the use of attachments AND prevent any URL being input for this purpose, I'd suggest adding a meta box or similar to manage those links (similar to our gallery meta box maybe?). The downloadable files for a product are ran through filters so you can filter the core ones out for your replacements.

Alternatively, you could look up the data by comparing the URL of the download to meta library items.

Hope this clarifies things.
