### ISSUE TITLE
API - Product Variations Upload Not Setting In Stock Status Correctly

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#12895]
Using WooCommerce Version 2.6.13 and WordPress v 4.7.1 and making a PUT request to update a Product with multiple variations. If I set the In Stock flag for the individual variations like this:

"variations": [
    {
      "attributes": [
        {
          "id": 1, 
          "name": "color", 
          "option": "Green"
        }, 
        {
          "id": 2, 
          "name": "Size", 
          "option": "Medium"
        }
      ], 
      "backorders": "yes", 
      "date_on_sale_from": "", 
      "date_on_sale_to": "", 
      "dimensions": {
        "height": "60", 
        "length": "100", 
        "width": "50"
      }, 
      "download_expiry": -1, 
      "download_limit": -1, 
      "downloadable": "false", 
      "downloads": [], 
      "id": "3352", 
      "images": [
        {
          "alt": "", 
          "id": 71, 
          "name": "poster_2_up", 
          "position": 0, 
          "src": "https://website.com/wp-content/uploads/2013/06/poster_2_up.jpg"
        }
      ], 
      "in_stock": "true", 
      "manage_stock": "false", 
      "regular_price": "10", 
      "sale_price": "", 
      "shipping_class": "standard", 
      "stock_quantity": 0, 
      "tax_class": "", 
      "tax_status": "taxable", 
      "virtual": "false", 
      "visible": "true", 
      "weight": "2"
    }, 

The In Stock status will remain set in WooCommerce as "Out of stock" and the response will show this hasn't been updated:

"variations": [{
		"id": 3352,
		"date_created": "2017-01-19T12:06:59",
		"date_modified": "2017-01-19T12:51:43",
		"permalink": "https:\/\/website.com\/product\/flying-ninja\/?attribute_pa_color=green&attribute_pa_size=medium",
		"sku": "FNJ",
		"price": "10",
		"regular_price": "10",
		"sale_price": "",
		"date_on_sale_from": "",
		"date_on_sale_to": "",
		"on_sale": false,
		"purchasable": true,
		"visible": true,
		"virtual": false,
		"downloadable": false,
		"downloads": [],
		"download_limit": -1,
		"download_expiry": -1,
		"tax_status": "taxable",
		"tax_class": "",
		"manage_stock": false,
		"stock_quantity": null,
		"in_stock": false,
		"backorders": "yes",
		"backorders_allowed": true,
		"backordered": false,
		"weight": "2",
		"dimensions": {
			"length": "100",
			"width": "50",
			"height": "60"
		},

`
### WordPress Environment ###

Home URL: https://website.com
Site URL: https://website.com
WC Version: 2.6.13
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.29
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.13
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (5) ###

Akismet: by Automattic – 3.2
MailChimp for WooCommerce: by MailChimp – 1.0.70
WooCommerce eWAY Payment Gateway: by WooThemes – 3.1.10 – 3.1.12 is available
WooCommerce: by WooThemes – 2.6.13
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Enfold
Version: 3.8.4
Author URL: http://www.kriesi.at
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
With just that 1 request I cannot tell you your exact problem (it works my side) but you should go into admin and look at the parent. If the parent product is stock managed, and has no stock, ALL variations which are not specifically stock managed will be out of stock too. This is not API dependent.

Closing as I cannot replicate this as an actual bug.

**Comment by waveyouat** [comment]
I'm having a similar problem.

a PUT request over a variable product that only has Title, Description and SKU, and no variants nor attributes:

{  "type": "simple",
  "regular_price": "#{_('data.foreach.foreach.variants.first.price')}",
  "sku": "#{_('data.foreach.foreach.variants.first.sku')}",
  "manage_stock": true,
  "stock_quantity": 900,
  "in_stock": true,
"images":[  
      {  
         "src":"#{_('data.utility.log_message1.message')}",
         "position": 0
      }
   ]
}

No way to show it as in stock even omitting "manage_stock" and "stock_quantity" flags.


WordPress Environment
Home URL:		https://chunkychains.com
Site URL:		https://chunkychains.com
WC Version:		2.6.14
Log Directory Writable:		 /home/chunkychains/public_html/wp-content/uploads/wc-logs/
WP Version:		4.7.2
WP Multisite:		–
WP Memory Limit:		168 MB
WP Debug Mode:		–
WP Cron:		
Language:		en_US
Server Environment
Server Info:		Apache
PHP Version:		 5.3.29 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size:		32 MB
PHP Time Limit:		60
PHP Max Input Vars:		1000
cURL Version:		7.37.1, OpenSSL/1.0.1e
SUHOSIN Installed:		
MySQL Version:		 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size:		32 MB
Default Timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte String:		
Remote Post:		
Remote Get:		
Database
WC Database Version:		2.6.14
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP Database:		 /home/chunkychains/public_html/wp-content/uploads/GeoIP.dat
Active Plugins (10)
Advanced Tag Rule	 	by Anton Shulga – 1.1.2
Tag Miner	 	by Fossura Computational Linguistics – 2.1.3
Loginizer	 	by Raj Kothari – 1.3.2
Shortcodes Ultimate	 	by Vladimir Anokhin – 4.9.9
Tags To Keywords	 	by CheGevara – 0.9.3
Title to Tags	 	by Thomas J. Belknap – 3.3
WooCommerce Display Products by Tags	 	by Sebs Studio – 1.0.0
WooCommerce PayPal Express Checkout Gateway	 	by Automattic – 1.1.2
WooCommerce Image Zoom	 	by wpbean – 1.01
WooCommerce	 	by WooThemes – 2.6.14
Settings
Force SSL:		–
Currency		GBP (£)
Currency Position		right_space
Thousand Separator		,
Decimal Separator		.
Number of Decimals		2
API
API Enabled:		
WC Pages
Shop Base:		#4 - /shop/
Cart:		#5 - /cart/
Checkout:		#6 - /checkout/
My Account:		#7 - /my-account/
Taxonomies
Product Types:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name:		Shopstar
Version:		1.0.12
Author URL:		http://www.outtheboxthemes.com/
Child Theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce Support:		
Templates
Overrides:	 	–

**Comment by mikejolley** [comment]
That is a simple product request.

**Comment by waveyouat** [comment]
Right, but why it doesn't change the stock to in stock?

I cannot find any reference online that mentions that as a bug.

**Comment by mikejolley** [comment]
There was a case which is fixed in 2.7 when you swap types, but you should maybe try making it simple first.
