### ISSUE TITLE
Mixed Backend Translations with formal german language file

### ISSUE THREAD

**Issue by nicmare** [woocommerce/woocommerce#12898]
## EXPLANATION OF THE ISSUE

The wp-admin shows me two different languages: english and formal german

## STEPS TO REPRODUCE THE ISSUE

1. Get de_DE_formal from https://translate.wordpress.org/projects/wp-plugins/woocommerce . Put it to wp-content/languages/woocommerce/woocommerce-de_DE_formal.mo (and wp-content/languages/de_DE_formal.mo for general WP formal german)
2. Set de_DE_formal in Wordpress Settings so that WC is also in formal german. Everything works fine as long as you leave the wp-admin to german interface. 
3. BUT if you set the admin-language of your profile to english (en_US), then everything is in english except Woocommerce. I would expect that everything is in english. If i choose regular "de_DE" in WP-Settings, and set wp-admin to en_US, everything is in english. 
4. If i rename woocommerce-de_DE_formal to woocommerec-de_DE (pretending it is regular german), then i got the same mixed up wp-admin languages. So there seems something wrong with the formal language pack. But po-edit and my phpstorm editor don't show any errors.

Some interesting screenshots:
- WP general settings:
![screenshot 2017-01-19 15 00 00](https://cloud.githubusercontent.com/assets/898582/22109678/06558e28-de59-11e6-9e66-1eb3d05bb42f.png)
- Profile settings:
![screenshot 2017-01-19 15 02 43](https://cloud.githubusercontent.com/assets/898582/22109662/f62c64e0-de58-11e6-92de-978a17287b48.png)
- Mixed up wp-admin:
![screenshot 2017-01-19 15 01 06](https://cloud.githubusercontent.com/assets/898582/22109674/fdda57a6-de58-11e6-96ca-8399b7a621b9.png)

nothing changes if i deactivate polylang or all other plugins.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://localhost/molitor
Site URL: http://localhost/molitor
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE_formal

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.25
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.50.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (39) ###

Polylang: von Frédéric Demarle – 2.0.12
Advanced Custom Fields: Image Crop Add-on: von Anders Thorborg – 1.4.9
Advanced Custom Fields: Link: von Corey Worrell
EMRL – 1.1.4

Admin Columns Pro: von AdminColumns.com – 3.8.9
Admin Menu Editor Pro: von Janis Elsts – 2.4.2
Advanced Cron Manager: von Kuba Mikita – 1.4.4
Advanced Custom Fields PRO: von Elliot Condon – 5.5.3
All 404 Redirect  to Homepage: von Fakhri Alsadi – 1.7
Admin Columns - Advanced Custom Fields add-on: von Codepress – 1.3.5.2
Admin Columns - WooCommerce add-on: von Codepress – 1.4
Clean Image Filenames: von Upperdog – 1.1.1
Disable Users: von Jared Atchison – 1.0.5
Enable Media Replace: von Måns Jonasson – 3.0.5
Force Regenerate Thumbnails: von Pedro Elsner – 2.0.6
Formidable Bootstrap: von Strategy11 – 1.02
Formidable Polylang: von Strategy11 – 1.06
Formidable Registration: von Strategy11 – 1.11.09
Formidable Forms: von Strategy11 – 2.02.13
Imsanity: von Shane Bishop – 2.3.8
Language Fallback: von Bernhard Kau – 1.0.3
Media Library Assistant: von David Lingren
Fair Trade Judaica – 2.41

Members: von Justin Tadlock – 1.1.2
Password Protected: von Ben Huson – 2.0.3
Postman SMTP: von Jason Hendriks – 1.7.2
Simple Custom Post Order: von Sameer Humagain – 2.3
Simple History: von Pär Thernström – 2.13
Simply Show Hooks: von  – 1.2.1
User Switching: von John Blackbourn – 1.0.9
Vendidero Helper: von Vendidero – 1.1.3
Hyyan WooCommerce Polylang Integration: von Hyyan Abo Fakher – 0.29
WooCommerce Customer Manager: von Ewout Fernhout – 1.2.5
WooCommerce Dynamic Pricing: von Lucas Stark – 2.12.2
WooCommerce Germanized Pro: von Vendidero – 1.5.8
WooCommerce Germanized: von Vendidero – 1.7.4
WooCommerce Sequential Order Numbers Pro: von WooThemes / SkyVerge – 1.10.1
WooCommerce: von WooThemes – 2.6.11
WooCommerce Helper: von WooCommerce – 1.7.2
WP Migrate DB Pro Media Files: von Delicious Brains – 1.4.7
WP Migrate DB Pro: von Delicious Brains – 1.7.1

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop-Basis: #179 - /shop/
Warenkorb: #180 - /warenkorb/
Kasse: #181 - /kasse/
Mein Konto: #182 - /mein-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: 
Version: – 0 ist verfügbar
Author URL: 
Child Theme: ❌ – Wenn Sie WooCommerce oder ein Parent Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie Sie ein Child Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: molitor/.DS_Store
`
```

**Comment by mikejolley** [comment]
Hi there,

Please contribute here if you spot things incorrect: https://translate.wordpress.org/projects/wp-plugins/woocommerce We don't translate via Github.

**Comment by benjamindahl** [comment]
hey Mike, did you read carefully? This issue is not about the translation itself and badly translated strings but about how the translation file is handled. The file actually seems to be correct and without errors.

**Comment by mikejolley** [comment]
You said there was a mix, which means incomplete translation files, not non-translated strings in core.

**Comment by benjamindahl** [comment]
Yes, but the language file from here [https://translate.wordpress.org/projects/wp-plugins/woocommerce/language-packs](https://translate.wordpress.org/projects/wp-plugins/woocommerce/language-packs) is completely (100%) translated. 
 So it is core problem.

**Comment by benjamindahl** [comment]
Just a question, why need woocommerce language files to be installed in wp-content/languages/woocommerce and not in wp-content/languages/plugins where other plugins put their translations, too?

**Comment by benjamindahl** [comment]
One more clue. The issue appears for a User with language set to English where German translation strings appear – which shouldn't. Not vice versa.

**Comment by mikejolley** [comment]
Since WP handles the download of translation files it doesn't really make a different to most users.

> So it is core problem.

Find me a string in core that is untranslated and I'll believe you. I'm 99% certain it's a problem with your language files, or another plugin is rendering those strings and not WooCommerce :) 

If it were a core plugin, ALL translations would break in the same way.

**Comment by benjamindahl** [comment]
Yes, that's what we first thought. A problem with the language file since the de_DE (not the formal one) works fine. So how can it be that another plugin is rendering those strings?

**Comment by mikejolley** [comment]
Can you find the string on translate.wordpress.org?

**Comment by benjamindahl** [comment]
One String for Example is simply 'Reports' 

`#: includes/admin/class-wc-admin-help.php:133
#: includes/admin/class-wc-admin-menus.php:70
msgid "Reports"
msgstr "Berichte"`

It's correctly Translated into 'Berichte' in the German admin panel. But it also appears as 'Berichte' in the English admin panel. 
I searched all other installed plugin .po files for that string. No other plugin uses that. 

When you look at the screenshot, you'll see, that it uses the German translation, allthough the language is set to English.

![bildschirmfoto 2017-01-20 um 22 48 17](https://cloud.githubusercontent.com/assets/2698024/22166709/bd072122-df62-11e6-8105-6c0bbe7dc62a.png)

**Comment by benjamindahl** [comment]
https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/de/formal?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=577704&filters%5Btranslation_id%5D=24214771

**Comment by nicmare** [comment]
FYI: i disabled all plugins except woocommerce. Then i switched to theme Twenty Sixteen. The Problem remains. No matter if i set regular german, formal german or event dutch as site language!

**Comment by nicmare** [comment]
After spending hours with the problem and with workarounds i finally found the problem (i guess). In the [Woocommerce-Docs](https://docs.woocommerce.com/document/woocommerce-localization/#section-9) is this paragraph:

> **Making your translation upgrade safe**
> WooCommerce keeps translations in wp-content/languages/plugins, like all other plugins. But if you wish to include a custom translation, you can use the directory wp-content/languages/woocommerce, …

As soon as you copy over your language files to that subfolder named "woocommerce", it causes the problem. when you put it into /plugins/ like every other plugins lang files, it works as expected. You should update the docs. I am not sure if this is the intended behaviour of the subfolder?!

**Comment by mikejolley** [comment]
The subfolder is essentially an override. If you have for example a custom translation which you don't want overridden by real translations.

**Comment by Twanneman** [comment]
Hi @mikejolley, I noticed the same problem with the  **Dutch formal** translations. 

When I setup WordPress to work with the default dutch translation (nl_NL) WooCommerce works fine and shows the back-end with the proper dutch translations. 
But when I setup WordPress with the dutch formal translation (nl_NL_formal). WooCommerce shows a back-end with mixed (english and dutch) translations.

**Comment by fishheadcode** [comment]
Also got that error with german formal. 
I am doing everything like always, so in WP6.0 and with (or without) Loco this issue still exists.
@mikejolley why are you closing this issue? There seems to be a lot of people having issues with that. 
There are not much using formal language, but it does also affect them.

I am currently compiling new mo and po (where the translations are definitely contained) and there are still translations missing. A part of the cart is translated in the frontend, another one is not. 

But in Loco everything is translated. Also the file is 100%.
So, how is this not a woocommerce problem?

**Comment by theSCHAPPY** [comment]
I can confirm the problem running Wordpress 6.7.2, WooCommerce 9.6.2, WooCommerce-Germanized 3.18.7 with the system wide locale de_DE_formal as well as the locale set for the current admin backend user. Before updating to WP 6.7.x everything worked fine here. I suspect it is connected to changes introduced to the Wordpress core on how to handle translations as mentioned here:  https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/ 

For example, in the Woocommerce backend menu I see "Returns" while other items are correctly translated, e.g. "Bestellungen" (orders). When looking at woocommerce-de_DE_formal.po and woocommerce-de_DE_formal.l10n.php both contain proper entries for  
`
msgid "Returns"
msgstr "Retouren"
`.

Any help is appreciated.
