### ISSUE TITLE
[2.7-master] featured_products shortcode not working

### ISSUE THREAD

**Issue by carasmo** [woocommerce/woocommerce#12891]
## EXPLANATION OF THE ISSUE
[featured_products per_page="4" columns="4"]

Doesn't work.  Nothing prints out in the parsed html.

recent_products does work.

**Please Close if this is because of not upgrading the database since I'm testing 2.7 but want to keep 2.6 for the time being.**

**Comment by claudiosanches** [comment]
This requires a database update, because now we have a new taxonomy called `product_visibility` and we don't use the `_featured` post meta anymore.
