### ISSUE TITLE
CLI inconsistent with product tags

### ISSUE THREAD

**Issue by pjv** [woocommerce/woocommerce#12894]
If you want to update tags for a product using the CLI, you have to specify the integer ID of the tag you want to use (which I had to determine by reading the source code of the CLI - there is no mention of this on the [CLI wiki page](https://github.com/woocommerce/woocommerce/wiki/WP-CLI-commands)). E.g.
`wp wc product update 56140 --tags=731`
`Success: Updated product 56140.`

However, if you do a get on a product and include the `tags` field, it responds with the tag slug strings. E.g.
`wp wc product get 56140 --field=tags`
`test1, test2`

This makes it impossible (or at least unduly cumbersome) to use `wp wc product update` to add a tag to a product without overwriting all the existing tags since there is no `get` that gives you the list of existing tag ID's.

It seems like it would be better if the treatment of the `tags` field was consistent between `get` and `update` and if we can vote on it, I think it would be far more usable if we could stick to the tag slugs (i.e., the way that `get` does it) and not have to manually look up the ID's.

I didn't check, but I'm guessing that the same issue exists for categories.

**Comment by mikejolley** [comment]
It's being replaced so does not require patching in 2.6.x https://woocommerce.wordpress.com/2016/12/12/2-7-a-new-cli-for-woocommerce/

**Comment by pjv** [comment]
Sweet. Thanks.
