### ISSUE TITLE
Admin Add Order - Set Default Billing / Shipping Address Country & State

### ISSUE THREAD

**Issue by silicondales** [woocommerce/woocommerce#12899]
WooCommerce latest release - 2.6.4
Store base location set to USA - Illinois
Default customer location = shop base address
Go to WooCommerce > Orders > Add New
(/wp-admin/post-new.php?post_type=shop_order )
Enter billing address or shipping address

Expected behaviour: the billing address country & state default to the store base settings (as in checkout)

What happens: these have to be manually selected.

This is an enhancement requested by a client who regularly adds orders. Feels like if its set to default to that on customer side... why not on admin!

This is not major, it is minor and an enhancement IMO!!

**Comment by jaydeeprami** [comment]
Hello @mikejolley ,

I have resolved the issue as per mentioned above. I have sent pull request for the same. Below is my pull request.

https://github.com/woocommerce/woocommerce/pull/12964/

Please review and do let me know if any suggestion for the same.

Thanks,

**Comment by silicondales** [comment]
Testing this later this week. This is a reminder mainly for myself. Please ignore if following.

**Comment by jaydeeprami** [comment]
Hello @mikejolley and @silicondales ,

I have fixed issue with all cases. Please review from your end.
Below is my PR:
https://github.com/woocommerce/woocommerce/pull/13061

Thanks,

**Comment by silicondales** [comment]
Hi @jaydeeprami,

Will check it out... have my beta store open right now for a bunch of stuff (including this).

Robin

**Comment by jaydeeprami** [comment]
Thank you @silicondales . Please let me know if there is any improvement.

**Comment by silicondales** [comment]
Tested and works for me in latest master copy php 7.0.15. Looks like some false positives on those automatic tests on your PR to me?

This one https://travis-ci.org/woocommerce/woocommerce/jobs/197982163

The 2 errors aren't related to stuff you touched (1 file).

**Comment by jaydeeprami** [comment]
Thank you @silicondales for testing. Is there anything that I need to do here?

Please advise.

**Comment by silicondales** [comment]
I don't think so, but @mikejolley may be able to shed more light on that one! I just saw that flag on #13061 and it looks like its not related (though it could be).

**Comment by jaydeeprami** [comment]
Thanks @silicondales, I will wait for @mikejolley response.

**Comment by silicondales** [comment]
but it does work, and no errors on my install.

**Comment by bobteree** [comment]
I would like to set the default country for admin-created orders in WooCommerce (for bill to and ship to addresses). I have done this on the front-end for new users, but would like the same default in the admin order form. thx
