### ISSUE TITLE
[REST API] Set standard tax_class on product clears tax

### ISSUE THREAD

**Issue by kallewallin** [woocommerce/woocommerce#12896]
## EXPLANATION OF THE ISSUE

When creating or updating a product you can supply a "tax_class" and we use the classes listed under 

GET [url]/wc-api/v3/taxes

`
{
"taxes": [
{
"rate": "25.0000",
"class": "25-moms"
},
{
"rate": "25.0000",
"class": "standard"
}
]}
`

setting tax_class to "" or "25-moms" will work but "standard" will clear the products tax(at least when viewing it in the shop)

## STEPS TO REPRODUCE THE ISSUE

If I then updates a product using 

POST [url]/wc-api/v3/products/[id]

`{"product": {"tax_class": "standard"}}`

Then the product will loose it's tax in the front end

If you instead updates using 

`{"product": {"tax_class": "25-moms"}}`

then the product will get tax

this will also work:

`{"product": {"tax_class": ""}}`

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

`
### WordPress Environment ###

Home URL: http://woocom-26.svbint.com
Site URL: http://woocom-26.svbint.com
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache/2.2.22 (Debian)
PHP Version: 5.6.25-1~dotdeb.7.1
PHP Post Max Size: 123 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.23
Max Upload Size: 123 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (11) ###

WPML Multilingual CMS: av OnTheGoSystems – 3.5.1.1
WooCommerce EU VAT Number: av WooThemes – 2.1.12 – 2.1.13 finns tillgänglig
WooCommerce Multilingual: av OnTheGoSystems – 3.8.5
WooCommerce: av WooThemes – 2.6.8
WPML All Import: av OnTheGoSystems – 2.0.2
WPML CMS Nav: av OnTheGoSystems – 1.4.19
WPML Media: av OnTheGoSystems – 2.1.22
WPML Sticky Links: av OnTheGoSystems – 1.4.0
WPML String Translation: av OnTheGoSystems – 2.4.1.1
WPML Translation Management: av OnTheGoSystems – 2.2.2
WPML Widgets: av Jeroen Sormani – 1.0.4

### Settings ###

Force SSL: ✔
Currency: SEK (kr)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Butikbas: #19 - /butik/
Varukorg: #20 - /varukorg/
Till kassan: #21 - /kassan/
Mitt konto: #22 - /mitt-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Leave the string blank for 'standard'. Standard is essentially no tax class.

@claudiosanches can we change this automatically?
