### ISSUE TITLE
Delete order item using API

### ISSUE THREAD

**Issue by hamdallah90** [woocommerce/woocommerce#12901]
Is there any way to remove order item or update order item?

**Comment by amjad** [comment]
yes, using line item id

**Comment by mikejolley** [comment]
https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties
https://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order

**Comment by hamdallah90** [comment]
Yes but if you check the delete order item 

**class-wc-rest-orders-controller.php** function **item_is_null**

here the function check if one of these keys are null but in ajax request no way to send null value

**Comment by bitsnaps** [comment]
Hi, @mikejolley there is no route to delete a specific item:
```
/orders/(?P<order_id>[\\d]+)/notes
/orders/(?P<order_id>[\\d]+)/notes/(?P<id>[\\d]+)
/orders/(?P<order_id>[\\d]+)/refunds
/orders/(?P<order_id>[\\d]+)/refunds/(?P<id>[\\d]+)
/orders
/orders/(?P<id>[\\d]+)
/orders/batch
```
I tried to update an order making `"line_items"` empty `[]` by sending a `PUT` request, but it did't work, I checked all the links:
```
/wc-api/v3/
/wp-json/wc/v3/
/wp-json/wc/v2/
```
Any ideas?

**Comment by amjad** [comment]
@bitsnaps update the order by sending the line item id as whatever it is and product id as null

**Comment by bitsnaps** [comment]
@amjad Thanks! finally got it, I had to send something like:
```
{
   "order":{
      "line_items":[
         {
            "id":19,
            "product_id":null
         }
      ]
   }
}
```
to url: `/orders/47` with `PUT` request, where 47 is the id of order and 19 is the id of the line item in that order.

**Comment by amjad** [comment]
@bitsnaps yes, that’s exactly how I meant it. you’re welcome :)

**Comment by KennyChan94** [comment]
@amjad @bitsnaps do you guys still able to remove one of the line_items? i tried a few methods on my side but i cant do it. 
what i did: 
url: `/{site_name}/online/wp-json/wc/v1/subscriptions/{order_id || subsription_id}` with `PUT`
url: `/{site_name}/online/wp-json/wc/v3/orders/{order_id || subsription_id}` with `PUT`
P.S. my wordpress site is using prospress as my site is selling services as subscription.

**Comment by bitsnaps** [comment]
@KennyChan94 The last example worked for me, here [is](https://github.com/bitsnaps/WooAndroid/blob/master/app/src/main/java/com/designwall/moosell/activity/card/CardListAdapter.java) an example from Android client, any error msg?
