### ISSUE TITLE
Tests bootstrap calls deprecated function

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#12916]
On the latest master branch of WooCommerce in `WC_Unit_Tests_Bootstrap:: install_wc`, `WP_Roles::reinit` is called. This function was deprecated in WP 4.7 and throws a deprecated function notice when PHPUnit is run. 

To fix this we should probably do something like:

`$GLOBALS['wp_roles'] = null;`
`wp_roles();`

**Comment by mikejolley** [comment]
@claudiosanches

**Comment by claudiosanches** [comment]
Closed in favor of #12943
