### ISSUE TITLE
wc_get_wildcard_postcodes() produces invalid strings

### ISSUE THREAD

**Issue by sybrenstuvel** [woocommerce/woocommerce#12910]
## EXPLANATION OF THE ISSUE

When passing "GIJóN" as location to wc_get_wildcard_postcodes(), it produces the following result:

`'GIJóN','GIJó*','GIJ�*','GIJ*','GI*','G*','*'`

As you can see, it shortens the string byte-for-byte, and not per character.

This was shown in the Apache error log as follows:

 97 [Wed Jan 11 16:36:02.802764 2017] [:error] [pid 14029:tid 34749906944] [client 90.163.154.158:50570] WordPress database error Illegal mix of collations for operation ' IN ' for query \n\t\t\tSELECT             tax_rates.*\n\t\t\tFROM wp_woocommerce_tax_rates as tax_rates\n\t\t\tLEFT OUTER JOIN wp_woocommerce_tax_rate_locations as locations ON tax_rates.tax_rate_id = locations.tax_rate_id\n\t\t\tLEFT OUTER JOIN       wp_woocommerce_tax_rate_locations as locations2 ON tax_rates.tax_rate_id = locations2.tax_rate_id\n\t\t\tWHERE 1=1 AND tax_rate_country IN ( 'ES', '' ) AND tax_rate_state IN ( 'O', '' ) AND tax_rate_class      = 'digital-goods' AND ( ( locations.location_type IS NULL ) OR ( \n\t\t\tlocations.location_type = 'postcode' AND locations.location_code IN ('GIJ\xc3\xb3N','GIJ\xc3\xb3*','GIJ\xc3*','GIJ*','GI*','G*','*       ')\n\t\t\tAND (\n\t\t\t\t( locations2.location_type = 'city' AND locations2.location_code = '33202' )\n\t\t\t\tOR NOT EXISTS (\n\t\t\t\t\tSELECT sub.tax_rate_id FROM wp_woocommerce_tax_rate_locations as        sub\n\t\t\t\t\tWHERE sub.location_type = 'city'\n\t\t\t\t\tAND sub.tax_rate_id = tax_rates.tax_rate_id\n\t\t\t\t)\n\t\t\t)\n\t\t ) OR ( \n\t\t\tlocations.location_type = 'city' AND locations.location_code      = '33202'\n\t\t\tAND NOT EXISTS (\n\t\t\t\tSELECT sub.tax_rate_id FROM wp_woocommerce_tax_rate_locations as sub\n\t\t\t\tWHERE sub.location_type = 'postcode'\n\t\t\t\tAND sub.tax_rate_id = tax_rates.           tax_rate_id\n\t\t\t)\n\t\t ) )\n\t\t\tGROUP BY tax_rate_id\n\t\t\tORDER BY tax_rate_priority, tax_rate_order\n\t\t made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'),        do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::do_wc_ajax, do_action('wc_ajax_update_order_review'), WP_Hook->do_action, WP_Hook->apply_filters,      call_user_func_array, WC_AJAX::update_order_review, WC_Cart->calculate_totals, WC_Tax::get_base_tax_rates, WC_Tax::find_rates, WC_Tax::get_matched_tax_rates, referer: https://store.blender.org/checkout/ 

## STEPS TO REPRODUCE THE ISSUE

1. Go to the checkout page
2. Type "GIJóN" (or any string with a non-ASCII character in it) in the Postcode/ZIP field
3. See the error in the error log

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://store.blender.org
Site URL: https://store.blender.org
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (22) ###

LayerSlider WP: by Kreatura Media – 5.6.8
WooCommerce Currency Switcher - Subscriptions Integration: by Diego Zanella – 1.3.0.160617
Bitcoin Payments for WooCommerce: by BitcoinWay – 4.11
Blender Plugin Tweaks: by Nerd Inc & Sybren A. Stüvel – 1.1
A bag of tweaks: by Bart Veldhuizen –
External Database Authentication Reloaded: by Joshua Parker – 1.2.3
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Stag Custom Sidebars: by Ram Ratan Maurya – 1.2
StagTools: by Ram Ratan Maurya – 2.1.3
User Switching: by John Blackbourn – 1.0.9
Aelia Foundation Classes for WooCommerce: by Aelia – 1.7.5.160722
Aelia Currency Switcher for WooCommerce: by Aelia – 3.9.8.160530
WooCommerce Direct Variation Link: by WP BackOffice – 1.0.3
WooCommerce EU VAT Number: by WooThemes – 2.1.13
WooCommerce Braintree Gateway: by WooThemes / SkyVerge – 3.3.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.38
WooCommerce Sequential Order Numbers Pro: by WooThemes / SkyVerge – 1.10.1
WooCommerce Subscriptions: by Prospress Inc. – 2.1.2
Aelia Tax Display by Country for WooCommerce: by Aelia (Diego Zanella) – 1.7.0.150109
WooCommerce: by WooThemes – 2.6.11
WooCommerce Helper: by WooCommerce – 1.7.2
WP Crontrol: by John Blackbourn & Edward Dale – 1.4

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: –

### WC Pages ###

Shop Base: #4 - /4-2/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Blender Store
Version: 1.0
Author URL: https://store.blender.org/
Child Theme: ✔
Parent Theme Name: Crux
Parent Theme Version: 1.6.3
Parent Theme Author URL: https://codestag.com
WooCommerce Support: ✔

### Templates ###

Overrides: crux/woocommerce/archive-product.php
blender-crux/woocommerce/checkout/form-checkout.php
crux/woocommerce/content-product.php
crux/woocommerce/content-product_cat.php
crux/woocommerce/content-single-product.php
blender-crux/woocommerce/myaccount/form-edit-account.php
blender-crux/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 2.6.0
blender-crux/woocommerce/myaccount/form-lost-password.php
crux/product-searchform.php

: Learn how to update outdated templates

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: 

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: 
`

**Comment by mikejolley** [comment]
See  #12926
