### ISSUE TITLE
Export .csv for Reports Date Range

### ISSUE THREAD

**Issue by truckstoptrixy** [woocommerce/woocommerce#12919]
## EXPLANATION OF THE ISSUE

Export of reports in woo "reports" area.  When a date range is chosen and then the ".csv export" button in the right top hand corner does not work.

## STEPS TO REPRODUCE THE ISSUE

under woo > reports >date range > export .csv the button is not working and download function is non responsive.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: https://katusaresearch.com
Site URL: https://katusaresearch.com
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9
PHP Version: 5.6.28
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (25) ###

404page - your smart custom 404 error page: by Peter's Plugins
smartware.cc – 2.2

AffiliateWP: by AffiliateWP
LLC – 1.9.4

Cyfe: by Cyfe
Inc – 1.3

Divi Builder: by Elegant Themes – 1.3.10
MailChimp for WordPress: by ibericode – 3.1.10
MailChimp User Sync: by ibericode – 1.5.2
Manual Image Crop: by Tomasz Sita – 1.12
MailChimp for WordPress - Premium: by ibericode – 3.3.1
Meta Slider: by Matcha Labs – 3.3.7
OptinMonster API: by Thomas Griffin – 1.1.5.8
Opt-In Panda | BizPanda: by OnePress – 1.4.1
Print Friendly and PDF: by Print Friendly – 3.5.4
TinyMCE Advanced: by Andrew Ozz – 4.4.1
True Mailchimp Custom: by Misha Rudrastyh – 1.0
User Switching: by John Blackbourn – 1.0.9
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.1.3
WooCommerce Customer/Order CSV Export: by WooThemes / SkyVerge – 4.1.3
WooCommerce Customizer: by SkyVerge – 2.3.1
WooCommerce Email Customizer: by cxThemes – 2.37
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooThemes – 4.4.3 – 4.4.4 is available
WooCommerce Memberships: by WooThemes / SkyVerge – 1.7.2 – 1.7.4 is available
WooCommerce Subscriptions: by Prospress Inc. – 2.1.0
WooCommerce: by WooThemes – 2.6.8
WooCommerce Helper: by WooCommerce – 1.7.2
Yoast SEO: by Team Yoast – 3.8

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page not set
Cart: ❌ Page does not contain the shortcode: [woocommerce_cart]
Checkout: #2554 - /page-checkout/
My Account: #2319 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Katusa Research for Woo
Version: 11.1
Author URL: http://rudrastyh.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: krwoo/woocommerce/checkout/form-login.php
krwoo/woocommerce/checkout/review-order.php
krwoo/woocommerce/content-single-product.php
krwoo/woocommerce/emails/customer-completed-order.php
krwoo/woocommerce/emails/customer-invoice.php
krwoo/woocommerce/emails/customer-new-account.php
krwoo/woocommerce/global/wrapper-start.php
krwoo/woocommerce/single-product.php


### Customer/Order CSV Export ###

Order Export Format: default
Customer Export Format: import
Automatically Export Orders: disabled
Automatically Export Customers: disabled
`
```

**Comment by mikejolley** [comment]
What browser? Requires support for the download HTML5 attribute. 

http://www.w3schools.com/TAgs/att_a_download.asp

**Comment by mikejolley** [comment]
Closed due to lack of updates.

**Comment by E-VANCE** [comment]
Same here – tested in both Firefox 51.0.1 and Chrome 56.0.2924.87. Not limited to custom date range, also unresponsive in the regular tabs... 

System log:

`
### WordPress Environment ###

Home URL: https://www.holzspielwaren-ackermann.de
Site URL: https://www.holzspielwaren-ackermann.de
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.16
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.22.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.47 - Wir empfehlen mindestens MySQL-Version 5.6. Siehe: WordPress-Anforderungen
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (40) ###

Advanced Post Types Order: von Nsp Code – 3.9.3
Antispam Bee: von pluginkollektiv – 2.7.0
BackupBuddy: von iThemes – 7.2.2.0
Bugsnag Error Monitoring: von Bugsnag Inc. – 1.3.0
Cookie Law Info: von Richard Ashby – 1.5.3
Disable Emojis: von Ryan Hellyer – 1.5.3
Disable New User Notifications: von Thomas Griffin – 1.0.2
Enhanced Text Widget: von Boston Dell-Vandenberg – 1.4.5
EWWW Image Optimizer: von Shane Bishop – 3.2.6
Foobar Notification Bars v2: von Brad Vincent – 2.5.7
Login Logo: von Mark Jaquith – 0.7
Redirection: von John Godley – 2.5
Reveal IDs: von Oliver Schlöbe – 1.5.1
RICG Responsive Images: von The RICG – 3.1.1
SearchWP LIKE Terms: von Jonathan Christopher – 2.4.4.1
SearchWP Live Ajax Search: von Jonathan Christopher – 1.1.8
SearchWP German Stemmer: von Jonathan Christopher – 1.0.1
SearchWP Term Highlight: von Jonathan Christopher – 2.0.13
SearchWP WooCommerce Integration: von SearchWP
LLC – 1.1.10

SearchWP: von SearchWP
LLC – 2.8.6

W3 Total Cache (Fixed): von Frederick Townes – 0.9.4.5
Widget CSS Classes: von C.M. Kendrick – 1.4.0
Widget Logic: von wpchefgadget
alanft – 5.7.2

Woocommerce Category Permalink Extension: von Liam Bailey (Webby Scots Wordpress - WSWP) – 1.0.0
WooCommerce Conversion Tracking: von Tareq Hasan – 1.2.2
WooCommerce EU VAT Number: von WooThemes – 2.1.14
Follow-Up Emails: von WooThemes – 4.4.18
WooCommerce Google Analytics Integration: von WooThemes – 1.4.0
WooCommerce Order Status Manager: von WooThemes / SkyVerge – 1.6.3
WooCommerce Print Invoices/Packing Lists: von WooThemes / SkyVerge – 3.1.7
WooCommerce Prices By User Role: von Festi-Team – 3.0
WooCommerce Sequential Order Numbers Pro: von WooThemes / SkyVerge – 1.10.1
WooCommerce Shipment Tracking: von WooCommerce – 1.6.3
WooCommerce: von WooThemes – 2.6.14
WooCommerce Helper: von WooCommerce – 1.7.2
Yoast SEO: von Team Yoast – 4.3
WP Javascript Detect: von DaddyDesign – 1.0
WP Maintenance Mode: von Designmodo – 2.0.9
WP Remote: von Human Made Limited – 2.7.6
YITH WooCommerce Zoom Magnifier: von YITHEMES – 1.2.23

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: –

### WC Pages ###

Shop-Basis: #977 - /shop
Warenkorb: #7 - /warenkorb
Kasse: #8 - /kasse
Mein Konto: #10 - /kundenkonto

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Cheope Child
Version: 2.5.1
Author URL: http://www.e-vance.net
Child Theme: ✔
Parent Theme Name: Cheope
Parent Theme Version: 2.5.1
Parent Theme Author URL: http://yithemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: cheope-child/woocommerce/archive-product.php
cheope-child/woocommerce/cart/cart-empty.php
cheope/woocommerce/cart/cart-shipping.php
cheope-child/woocommerce/cart/cart-totals.php
cheope-child/woocommerce/cart/cart.php
cheope/woocommerce/cart/cross-sells.php
cheope/woocommerce/cart/mini-cart.php
cheope/woocommerce/checkout/cart-errors.php
cheope-child/woocommerce/checkout/form-billing.php
cheope-child/woocommerce/checkout/form-checkout.php
cheope/woocommerce/checkout/form-coupon.php
cheope-child/woocommerce/checkout/form-login.php
cheope-child/woocommerce/checkout/form-shipping.php
cheope-child/woocommerce/checkout/payment.php
cheope/woocommerce/checkout/review-order.php
cheope-child/woocommerce/checkout/thankyou.php
cheope/woocommerce/content-product.php
cheope-child/woocommerce/content-product_cat.php
cheope/woocommerce/content-single-product.php
cheope-child/woocommerce/emails/customer-on-hold-order.php
cheope/woocommerce/global/breadcrumb.php
cheope-child/woocommerce/global/form-login.php
cheope/woocommerce/global/sidebar.php
cheope/woocommerce/global/wrapper-end.php
cheope-child/woocommerce/global/wrapper-start.php
cheope/woocommerce/loop/add-to-cart.php
cheope/woocommerce/loop/pagination.php
cheope/woocommerce/loop/price.php
cheope-child/woocommerce/loop/sale-flash.php
cheope/woocommerce/order/form-tracking.php
cheope/woocommerce/order/tracking.php
cheope-child/woocommerce/product-searchform.php
cheope/woocommerce/single-product/add-to-cart/external.php
cheope/woocommerce/single-product/add-to-cart/grouped.php
cheope/woocommerce/single-product/add-to-cart/simple.php
cheope-child/woocommerce/single-product/add-to-cart/variable.php
cheope/woocommerce/single-product/meta.php
cheope-child/woocommerce/single-product/price.php
cheope/woocommerce/single-product/product-image.php Version 2.0.14 ist veraltet. Die Hauptversion ist 2.6.3
cheope/woocommerce/single-product/product-thumbnails.php Version 2.3.0 ist veraltet. Die Hauptversion ist 2.6.3
cheope/woocommerce/single-product/related.php
cheope-child/woocommerce/single-product/sale-flash.php
cheope/woocommerce/single-product/share.php
cheope/woocommerce/single-product/short-description.php
cheope/woocommerce/single-product/tabs/description.php
cheope/woocommerce/single-product/tabs/tabs.php
cheope/woocommerce/single-product/title.php
cheope-child/woocommerce/single-product/up-sells.php
cheope/woocommerce/single-product-reviews.php
cheope/woocommerce/single-product.php
cheope/woocommerce/taxonomy-product_cat.php
cheope/woocommerce/taxonomy-product_tag.php

: Erfahre
wie du veraltete Templates aktualisierst

`

**Comment by mikejolley** [comment]
View your javascript console for errors. In chrome, View > Developer > Javascript console

**Comment by E-VANCE** [comment]
No errors there but I just noticed something:

The export works fine when accessing the sales_by_date report but is broken for sales_by_product!

**Comment by E-VANCE** [comment]
This bug is still present and should be re-opened!

**Comment by mikejolley** [comment]
It won't do anything until you select a produce to report on...

**Comment by E-VANCE** [comment]
OK, gotcha – but then this is a UX-issue:

- I am expecting to see a functionality here with the link being active... Couldn't it be disabled / hidden when not functional?
- I thought I would get a breakdown of sales by all products in this report-tab with the optional selection of specific products, maybe that should be made clearer in wording?

**Comment by mikejolley** [comment]
It could be hidden yes,  but I think all reports are do for a refactor at some point anyway. A breakdown of ALL products would be too resource intensive to generate with current data structures.

**Comment by E-VANCE** [comment]
Allright, thanks for the info!

For others: There is a [free plugin](https://wordpress.org/plugins/product-sales-report-for-woocommerce/) available to generate such a report.
