### ISSUE TITLE
Possible to add variable product without selecting variation

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#12928]
## EXPLANATION OF THE ISSUE
I was able to add a variable product to cart without selecting variation in 2.7-beta1. JS/AJAX doesn't prevent this.

Side effects are that in /cart/ page I see title like "Product title -" and nothing after the dash. And I can proceed to checkout with such product without any error messages.

2.7-beta1: Issue exists.
22 Jan 2017 version: Issue doesn't exist.

However, I'm reporting this because perhaps PHP still allows this even if it's fixed in JS on front-end? I don't know. Maybe this bug report invalid. But it definitely was there. PHP should not allow such product to be added server-side.

**Comment by justinshreve** [comment]
Hi @manake,

I wasn't able to reproduce with 2.7 beta-1 or master. The JS/AJAX prevented this on both with an `Please select some product options before adding this product to your cart.` alert. I then enabled the "Add to cart" button so I could test the PHP validation and that also returned an error on the front end `Please choose product options…`. https://github.com/woocommerce/woocommerce/blob/76b32c9aa52ebac70fe5a60a8d56351218760471/includes/class-wc-form-handler.php#L808

If you are able to reproduce the code with the current code in master (or the upcoming beta-2 we will be releasing soon) can you reopen this issue with some more details, like your product configuration?
