### ISSUE TITLE
Disabling specific variations.

### ISSUE THREAD

**Issue by Phiph** [woocommerce/woocommerce#12920]
## EXPLANATION OF THE ISSUE

I have a variable product with 5 attributes listed below with their attribute count

- Flavours (6)
- Wrapper Colour (20)
- Inner Foil Colour (5)
- Print Colour (26)
 - Quantity (14)

The only difference between the product price is the quantity. There is a reason why it had to be an attribute!

Anyway for this 1 product we currently have just 14 variations with Any Flavour, Any Colour, Any Inner Foil, {chosen quantity} each with its own price. 

However we'd like the ability to disable the ordering of certain combinations, for example if we ran out of Mint Flavour we'd like the shop manager to easily add the variation for:

**Mint Flavour, any colour, any foil, any quantity** -  mark that out of stock making it unavailable to order, so in the list there would be just 15 variations, then just remove that one when back in stock. 

The issue is at present WooCommerce is only taking note of the **Any Flavour, Any Colour, Any Inner Foil, {chosen quantity}** variation rather then the specific match for attributes. 

I hope this is just a bug, as I can't imagine a better way to manage that amount of variations.

If anyone can point me into the function to pay attention to I'd be happy to contribute too!

**Comment by mikejolley** [comment]
You just need to reorder them (drag and drop). I think it's first matched :)

**Comment by Phiph** [comment]
I have put the disabled variations at the top of the list, but it still pulls the Any/Any/Any Quantity variations which are lower down the list.

**Comment by mikejolley** [comment]
I'm afk. Try the bottom of the list - I forget which way gets priority off top of head.

**Comment by Phiph** [comment]
Yeah that's a bit annoying, I think I've tried at the bottom too and that hasn't worked. I'd of hoped it would be at the top, as that's where new variations get added.

When you're back on a puter do you mind letting me know which function I should look at, I am a web developer.

**Comment by mikejolley** [comment]
It's top to bottom.

Out of stock : https://dl.dropboxusercontent.com/s/9n4s1nw1md8casu/2017-01-23%20at%2012.02.png

Variations: https://dl.dropboxusercontent.com/s/xmj9lgvdkqtqptf/2017-01-23%20at%2012.02%20%281%29.png

**Comment by Phiph** [comment]
Yeah, that probably works in your scenario, but see attached as I am not getting the out of stock message, and I'm able to add the product to the basket.  just a FYI the price won't show, as that has been removed in my custom template, as its showing somewhere else on the page. 

https://1drv.ms/f/s!AnBG5zHyGhDqgcIMyBc5KfQb_CrtlQ

Please may you reopen this issue?

**Comment by mikejolley** [comment]
> Yeah, that probably works in your scenario, but see attached

It's the same setup.. so I'm guessing your top variation thats not matching is either missing data (price) or not enabled (checkbox). Screenshot that?

I'll only reopen this if I confirm a bug, which I have not been able to do with the given information.

**Comment by Phiph** [comment]
Updated folder with AdminExpanded.png

**Comment by Phiph** [comment]
I've also added a price in the variation - but it still allows me to order the product.

**Comment by mikejolley** [comment]
The price field is empty. No price field = the variation is ignored.

> It's the same setup.. so I'm guessing your top variation thats not matching is either missing data (price) or not enabled (checkbox). Screenshot that?

**Comment by Phiph** [comment]
Please read my comment... even with a price it does not work.

**Comment by mikejolley** [comment]
Send a link to the page.

**Comment by Phiph** [comment]
http://staging.delvauxchocolates.com/shop/chocolates/neapolitan/

I have also updated the onedrive with the updated variation screenshot.

**Comment by mikejolley** [comment]
You're not making this easy :P In your screenshot the ID of the variation is 11360, which doesn't even exist on the page. Is that screenshot from another server or product?

And this is still empty in your screenshot so checking you understood which price I meant https://dl.dropboxusercontent.com/s/0h40inak7h5orwh/2017-01-23%20at%2018.25.png

**Comment by Phiph** [comment]
Yeah I've added a new variation see CaptureStagingAdminUpdatedValues.PNG

**Comment by mikejolley** [comment]
That image is not there. Just give me the ID number of the variation you're trying to override it with on that 1 product.

add-to-cart-variations.js script handles selection.

**Comment by Phiph** [comment]
11409

**Comment by mikejolley** [comment]
11409 does not exist on the page http://staging.delvauxchocolates.com/shop/chocolates/neapolitan/ so it's either not enabled, it has no price, your page is being cached somehow, or you have the setting enabled to hide out of stock products from the catalog. If it were working, it would be in the huge array of variations on the form. Look into that please.

**Comment by Phiph** [comment]
@mikejolley you're right - catalogue setting for hide out of stock products was enabled. 

personally knowing the function that built the array would of helped, but thanks for assisting.

**Comment by mikejolley** [comment]
👍

**Comment by Phiph** [comment]
Although - this isn't relevant for us but maybe for others. 

What if we did have a simple product that we didn't want to show out of stock, but as our example disable certain variations - is there a feature or function that could be altered?

**Comment by mikejolley** [comment]
Thats not supported as of now. Variations are on our refactor list but more medium term.
