### ISSUE TITLE
New gallery zoom feature

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#12923]
## EXPLANATION OF THE ISSUE

I have my column for product images set to about 590px in width but I upload images of about 600px to account for browser inconsistencies in calculating widths.

This new zoom feature gets triggered unnecessarily in this situation and thus produces visual glitches.

Furthermore, I have some small images there as well (100px in width) and it also works for too small images when there is no need to do that.

**Comment by carasmo** [comment]
The hover zoom? Yeah, I don't like it either.

Use wp_dequeue_script to remove it, works great:

Use a functions plugin or WPClips instead of adding this php to functions.php

```

/** 
 *
 * Remove the Zoom from images as smaller images look messed up on hover
 *
 */	
function yourchildprefix_wp_dequeue_wc_zoom() {

	if ( ! class_exists( 'WooCommerce' ) ) return; //* exit early if WooCommerce not active/installed

		wp_dequeue_script( 'zoom' );
	
}
add_action( 'wp_enqueue_scripts', 'yourchildprefix_wp_dequeue_wc_zoom', 99 );

```

**Comment by carasmo** [comment]
Just a note. End users generally and hardly ever have the right sized images so they just upload whatever they have and the way WP works, as we know, if the size meets the height and width requirements, it will crop. I personally don't have any hard crop for the single product image as many people want to upload different orientations and don't want a square. It'd be awfully cool if there was a settings option to not use the Zoom and the Flex slider and just use the new PhotoSwipe (which is great!)

**Comment by mikejolley** [comment]
See #13009
