### ISSUE TITLE
Out of stock on updating

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#12925]
## EXPLANATION OF THE ISSUE

1. AJAX hangs with 403 server error on variation update occasionally and requires page reload.

2. On updating variation and setting up price the product becomes "out of stock" often (but not always) for me in 21 Jan 2017 version (today).

"Sorry, no products matched your selection. Please choose a different combination." appears in alert on front-end and the message is "This product is currently out of stock and unavailable." instead of the add to cart button.

I found no way to fix that inside the admin panel.

I never encountered this issue before 2.7 beta.

**Comment by justinshreve** [comment]
I ran into the out of stock problem before I fixed #12839, #12837, and I think #12950. I haven't seen it updating since. Can you try the latest code in master (or the upcoming beta-2) and report back if you are still having the same issue?

**Comment by manake** [comment]
26 Jan 2017 version

1. I tried to re-save the product which previously became irreversibly "Out of stock". I didn't change anything. It's still out of stock on front-end.

2. I deleted all variations for that product and re-created them and it didn't help.

3. I switched that product back to "simple product" and re-saved and it also doesn't work when it's a simple product. On the front-end "Product name – has been removed from your cart because it can no longer be purchased. Please contact us if you need assistance." appeared twice (same message duplicated) but only on first front-end entrance (perhaps it got removed from my cart once and the message didn't appear again).

4. Switched back to variable product, I had to recreate the single variation I had (because it got deleted when it became "simple product") and it still doesn't work with the same error like 5 days ago.

------

So, now I'm leaving that product and entering one that I created in 2.6.11 version. I'll be trying to update its price:

1. The product works on front-end when I start.

2. I add the second attribute (the one that will be used for variations - "size") and save. Everything works.

3. I switch it to be a variable product and select that attribute as "used for variations". Then I add one variation (called "any size...") and set the price. Re-save. It doesn't work. It broke to permanent "out of stock" status. I still didn't find any way to restore these product to normal status.

Testing on two themes: 2017 and a custom one.
In all cases stock is set to "in stock" in all drop-downs.
