### ISSUE TITLE
Order API not working

### ISSUE THREAD

**Issue by NizarBlond** [woocommerce/woocommerce#12927]
## EXPLANATION OF THE ISSUE

**PHP Version:**
PHP 5.6.22 (cli) (built: May 27 2016 12:20:55) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**WP Version**
4.7.1

**WC Version**
2.6.13

The WC API works perfectly for all routes but the order.

e.g. 
http://mysite.com/wp-json/wc/v1/products returns products.

http://mysite.com/wp-json/wc/v1/orders returns empty set

The Order API is returned by WC_REST_Posts_Controller::get_items() (which is inherited by Orders_Controller)

Line 351 apparently has the problem

                print_r($query_args);
		$posts_query = new WP_Query();
		$query_result = $posts_query->query( $query_args )

**The output** 

(
    [paged] => 1
    [order] => desc
    [orderby] => date
    [post_type] => shop_order
    [date_query] => Array
        (
        )

    [post__in] => Array
        (
        )

    [post__not_in] => Array
        (
        )

    [posts_per_page] => 10
    [ignore_sticky_posts] => 1
)

Any idea?

I tried to remove all fields and leave "post_type" it works perfectly:

 $posts_query->query( ["post_type"=>"shop_order"] )

**Comment by claudiosanches** [comment]
Tested with WordPress 4.7.1 and WooCommerce 2.6.13 and works just fine.

And testing the output by WP CLI works fine too:

```php
$ wp shell
wp> $GLOBALS['wp_version']
=> string(5) "4.7.1"
wp> WC_VERSION
=> string(6) "2.6.13"
wp> $posts_query = new WP_Query();
=> object(WP_Query)#1892 (53) {
...
}
wp> $query_result = $posts_query->query( array( 'paged' => true, 'order' => 'desc', 'orderby' => 'date', 'post_type' => 'shop_order', 'posts_per_page' => 10, 'post_status' => 'any', 'post__in' => array(), 'post__not_in' => array(), 'date_query' => array(), 'ignore_sticky_posts' => true ) )
=> array(10) {
  [0]=>
  object(WP_Post)#1936 (24) {
    ["ID"]=>
    int(566)
    ["post_author"]=>
    string(1) "1"
    ["post_date"]=>
    string(19) "2017-01-18 15:12:57"
    ["post_date_gmt"]=>
    string(19) "2017-01-18 17:12:57"
    ["post_content"]=>
    string(0) ""
    ["post_title"]=>
    string(41) "Order &ndash; January 18, 2017 @ 03:12 PM"
    ["post_excerpt"]=>
    string(0) ""
    ["post_status"]=>
    string(10) "wc-on-hold"
    ["comment_status"]=>
    string(4) "open"
    ["ping_status"]=>
    string(6) "closed"
    ["post_password"]=>
    string(19) "order_587fa21925c5a"
    ["post_name"]=>
    string(25) "order-jan-18-2017-0512-pm"
    ["to_ping"]=>
    string(0) ""
    ["pinged"]=>
    string(0) ""
    ["post_modified"]=>
    string(19) "2017-01-18 15:17:06"
    ["post_modified_gmt"]=>
    string(19) "2017-01-18 17:17:06"
    ["post_content_filtered"]=>
    string(0) ""
    ["post_parent"]=>
    int(0)
    ["guid"]=>
    string(47) "http://woo.dev/?post_type=shop_order&#038;p=566"
    ["menu_order"]=>
    int(0)
    ["post_type"]=>
    string(10) "shop_order"
    ["post_mime_type"]=>
    string(0) ""
    ["comment_count"]=>
    string(1) "1"
    ["filter"]=>
    string(3) "raw"
  }
...
}

```

> Any idea?

Maybe you are debugging in the wrong place. Maybe some plugin causing it.
