### ISSUE TITLE
add-to-cart-variation.js problem when upgrading from 2.6.9

### ISSUE THREAD

**Issue by peixotorms** [woocommerce/woocommerce#12929]
Hi,

I have a client using woocommerce and he has a few products where you can choose a variation before adding to cart. For example, you can buy a packet of 4 or a packet of 8 for different prices.

The problem we have is that when we run woocommerce 2.6.9 it works fine, while as soon as we upgrade to 2.6.10+ (tested up to 2.6.13) this functionality breaks.

When we upgrade, what happens is that you select the radio button for the packet of 8 and click the "add to cart", however when you see the cart the first variation on the list (the packet of 4) has been added instead.

I've traced the problem to the add-to-cart-variation.js file (and the min.js version, obviously) so by upgrading to 2.6.13 and then, replacing those 2 files with the backup from 2.6.9 fixes the issue and the variations work fine again.

I haven't dig deeper, but is anyone else having this issue?

Thanks,

`
### WordPress Environment ###

Home URL: https://kava.com
Site URL: https://kava.com
WC Version: 2.6.13
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.8
PHP Version: 7.0.15-1~dotdeb+8.1
PHP Post Max Size: 1 GB
PHP Time Limit: 14400
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.13
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (42) ###

Advanced Custom Fields: Repeater Field: by Elliot Condon – 1.1.1
Advanced Code Editor: by BaInternet – 2.2.7
Advanced Custom Fields: by Elliot Condon – 4.4.11
Akismet: by Automattic – 3.2
Bloom: by Elegant Themes – 100.2
Contact Form 7 Skins: by Neil Murray – 1.2
Contact Form 7: by Takayuki Miyoshi – 4.6
Cart Product Feed Additional Product Fields: by ShoppingCartProductFeed; Remi Corson & Harsha Venkatesh – 1.1.3
Divi Builder: by Elegant Themes – 1.3.10
Elegant Themes Updater: by Elegant Themes – 1.2
IgniteWoo Updater: by IgniteWoo.com – 2.1.9
InfusedWoo Pro: by Mark Joseph – 3.2.2
KC Mods: by Keith Cleversley – 1.0
Nginx Helper: by rtCamp – 1.9.9
Post Duplicator: by Metaphor Creations – 2.19
Postman SMTP: by Jason Hendriks – 1.7.2
ExportFeed - Create Product Feeds For 40+ Merchants: by ExportFeed.com – 3.1.7.0
Resize Image After Upload: by iamphilrae – 1.7.2
Smart Manager: by Store Apps – 3.9.20
WooCommerce Brands: by WooThemes – 1.5.0
WooCommerce Conversion Tracking: by Tareq Hasan – 1.2.1
WooCommerce Customer/Order CSV Export: by WooThemes / SkyVerge – 4.1.3
Follow-Up Emails: by WooThemes – 4.4.17
WooCommerce USA ePay Gateway: by WooThemes / SkyVerge – 1.7.1
WooCommerce Instagram: by WooThemes – 1.0.10
WooCommerce Print Invoices/Packing Lists: by WooThemes / SkyVerge – 3.1.7
WooCommerce Points and Rewards: by WooThemes – 1.5.9
WooCommerce Product Reviews Pro: by WooThemes / SkyVerge – 1.6.5
WooCommerce Product Search: by itthinx – 1.8.1
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2
WooCommerce Restrict Shipping: by IgniteWoo – 1.7.4
WooCommerce Sequential Order Numbers Pro: by WooThemes / SkyVerge – 1.10.1
WooCommerce Shipment Tracking: by WooCommerce – 1.6.3
WooCommerce FedEx Shipping: by Automattic – 3.4.4
WooCommerce USPS Shipping: by WooCommerce – 4.4.3
WooCommerce ShipWorks Integration: by IgniteWoo.com – 1.5.5
WooCommerce Social Login: by WooThemes / SkyVerge – 2.0.4
WooCommerce Table Rate Shipping: by Automattic – 3.0.2
WooCommerce URL Coupons: by WooThemes / SkyVerge – 2.4.1
WooCommerce: by WooThemes – 2.6.13
WooCommerce Helper: by WooCommerce – 1.7.2
Yoast SEO Premium: by Team Yoast – 4.1

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #1144 - /shop/
Cart: #1145 - /cart/
Checkout: #1146 - /checkout/
My Account: #1147 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Kava Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.29
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: kava-child/woocommerce/archive-product.php
kava-child/woocommerce/auth/footer.php
kava-child/woocommerce/auth/form-grant-access.php
kava-child/woocommerce/auth/form-login.php
kava-child/woocommerce/auth/header.php
kava-child/woocommerce/cart/cart-empty.php
kava-child/woocommerce/cart/cart-item-data.php
kava-child/woocommerce/cart/cart-shipping.php
kava-child/woocommerce/cart/cart-totals.php
kava-child/woocommerce/cart/cart.php
kava-child/woocommerce/cart/cross-sells.php
kava-child/woocommerce/cart/mini-cart.php
kava-child/woocommerce/cart/proceed-to-checkout-button.php
kava-child/woocommerce/cart/shipping-calculator.php
kava-child/woocommerce/checkout/cart-errors.php
kava-child/woocommerce/checkout/form-billing.php
kava-child/woocommerce/checkout/form-checkout.php
kava-child/woocommerce/checkout/form-coupon.php
kava-child/woocommerce/checkout/form-login.php
kava-child/woocommerce/checkout/form-pay.php
kava-child/woocommerce/checkout/form-shipping.php
kava-child/woocommerce/checkout/payment-method.php
kava-child/woocommerce/checkout/payment.php
kava-child/woocommerce/checkout/review-order.php
kava-child/woocommerce/checkout/terms.php
kava-child/woocommerce/checkout/thankyou.php
kava-child/woocommerce/content-product.php
kava-child/woocommerce/content-product_cat.php
kava-child/woocommerce/content-single-product.php
kava-child/woocommerce/content-widget-product.php
kava-child/woocommerce/emails/admin-cancelled-order.php
kava-child/woocommerce/emails/admin-failed-order.php
kava-child/woocommerce/emails/admin-new-order.php
kava-child/woocommerce/emails/customer-completed-order.php
kava-child/woocommerce/emails/customer-invoice.php
kava-child/woocommerce/emails/customer-new-account.php
kava-child/woocommerce/emails/customer-note.php
kava-child/woocommerce/emails/customer-processing-order.php
kava-child/woocommerce/emails/customer-refunded-order.php
kava-child/woocommerce/emails/customer-reset-password.php
kava-child/woocommerce/emails/email-addresses.php
kava-child/woocommerce/emails/email-customer-details.php
kava-child/woocommerce/emails/email-footer.php
kava-child/woocommerce/emails/email-header.php
kava-child/woocommerce/emails/email-order-details.php
kava-child/woocommerce/emails/email-order-items.php
kava-child/woocommerce/emails/email-styles.php
kava-child/woocommerce/emails/plain/admin-cancelled-order.php
kava-child/woocommerce/emails/plain/admin-failed-order.php
kava-child/woocommerce/emails/plain/admin-new-order.php
kava-child/woocommerce/emails/plain/customer-completed-order.php
kava-child/woocommerce/emails/plain/customer-invoice.php
kava-child/woocommerce/emails/plain/customer-new-account.php
kava-child/woocommerce/emails/plain/customer-note.php
kava-child/woocommerce/emails/plain/customer-processing-order.php
kava-child/woocommerce/emails/plain/customer-refunded-order.php
kava-child/woocommerce/emails/plain/customer-reset-password.php
kava-child/woocommerce/emails/plain/email-addresses.php
kava-child/woocommerce/emails/plain/email-customer-details.php
kava-child/woocommerce/emails/plain/email-order-details.php
kava-child/woocommerce/emails/plain/email-order-items.php
kava-child/woocommerce/global/breadcrumb.php
kava-child/woocommerce/global/form-login.php
kava-child/woocommerce/global/quantity-input.php
kava-child/woocommerce/global/sidebar.php
kava-child/woocommerce/global/wrapper-end.php
kava-child/woocommerce/global/wrapper-start.php
kava-child/woocommerce/loop/add-to-cart.php
kava-child/woocommerce/loop/loop-end.php
kava-child/woocommerce/loop/loop-start.php
kava-child/woocommerce/loop/no-products-found.php
kava-child/woocommerce/loop/orderby.php
kava-child/woocommerce/loop/pagination.php
kava-child/woocommerce/loop/price.php
kava-child/woocommerce/loop/rating.php
kava-child/woocommerce/loop/result-count.php
kava-child/woocommerce/loop/sale-flash.php
kava-child/woocommerce/myaccount/form-add-payment-method.php
kava-child/woocommerce/myaccount/form-edit-account.php
kava-child/woocommerce/myaccount/form-edit-address.php
kava-child/woocommerce/myaccount/form-login.php
kava-child/woocommerce/myaccount/form-lost-password.php
kava-child/woocommerce/myaccount/my-account.php
kava-child/woocommerce/myaccount/my-address.php
kava-child/woocommerce/myaccount/my-downloads.php
kava-child/woocommerce/myaccount/my-orders.php
kava-child/woocommerce/myaccount/view-order.php
kava-child/woocommerce/notices/error.php
kava-child/woocommerce/notices/notice.php
kava-child/woocommerce/notices/success.php
kava-child/woocommerce/order/form-tracking.php
kava-child/woocommerce/order/order-again.php
kava-child/woocommerce/order/order-details-customer.php
kava-child/woocommerce/order/order-details-item.php
kava-child/woocommerce/order/order-details.php
kava-child/woocommerce/order/tracking.php
kava-child/woocommerce/product-searchform.php
kava-child/woocommerce/single-product/add-to-cart/external.php
kava-child/woocommerce/single-product/add-to-cart/grouped.php
kava-child/woocommerce/single-product/add-to-cart/simple.php
kava-child/woocommerce/single-product/add-to-cart/variable.php
kava-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
kava-child/woocommerce/single-product/add-to-cart/variation.php
kava-child/woocommerce/single-product/meta.php
kava-child/woocommerce/single-product/price.php
kava-child/woocommerce/single-product/product-attributes.php
kava-child/woocommerce/single-product/product-image.php
kava-child/woocommerce/single-product/product-thumbnails.php
kava-child/woocommerce/single-product/rating.php
kava-child/woocommerce/single-product/related.php
kava-child/woocommerce/single-product/review.php
kava-child/woocommerce/single-product/sale-flash.php
kava-child/woocommerce/single-product/share.php
kava-child/woocommerce/single-product/short-description.php
kava-child/woocommerce/single-product/tabs/additional-information.php
kava-child/woocommerce/single-product/tabs/description.php
kava-child/woocommerce/single-product/tabs/tabs.php
kava-child/woocommerce/single-product/title.php
kava-child/woocommerce/single-product/up-sells.php
kava-child/woocommerce/single-product-reviews.php
kava-child/woocommerce/single-product.php
kava-child/woocommerce/taxonomy-product_cat.php
kava-child/woocommerce/taxonomy-product_tag.php

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled
`

**Comment by mikejolley** [comment]
See https://woocommerce.wordpress.com/2016/12/22/woocommerce-2-6-10-fix-release-notes/ - there were some event changes. Your radio button script likely needs some adjustments.

**Comment by peixotorms** [comment]
This are not "my" radio buttons, but from what you said, this is at least something that has been custom made by someone else to the client. In that case it makes sense. Thanks for the feedback and link. Will see what I can do.

**Comment by chearon** [comment]
I had this happen to a website too, and about 20 orders did not have T-shirt sizes on them because of it. The company had to personally contact each one of those people to get the sizes!

In my opinion, the events in add-to-cart.js should be bound to classes, not strictly to an element name (in this case `select`). Otherwise, I have to override the whole file or make the select invisible or something nasty like that.

@mikejolley does that sound reasonable and would that PR be considered?

**Comment by mikejolley** [comment]
Could do,  but it might be wasted effort when https://github.com/woocommerce/woocommerce/issues/13086 is done.

**Comment by lkraav** [comment]
Ouch, just hit this when upgrading a slow-mode client 2.5 -> 2.6.14.

With the variation `<select>` output like below, this re-factored JS force-selects only the top `<option>` regardless of which one the user clicks on:

```html
<select id="pa_asukoht" name="attribute_pa_asukoht" data-attribute_name="attribute_pa_asukoht">
    <option value="">Choose an option…</option>
    <option value="1101-3" data-variation-id="10804" class="attached enabled">2019, Mar 11 — Tallinn</option>
    <option value="1101-3" data-variation-id="10803" class="attached enabled">2019, Apr 29 — Tallinn</option>
    <option value="1101-3" data-variation-id="4516" class="attached enabled">2019, May 6 — Tallinn</option>
</select>
```

**Comment by lkraav** [comment]
Here's a workaround for operating on variation selection based on your customer dimension other than `value` attribute, in a mostly upstream-compatible way:

https://gist.github.com/lkraav/6558e260480925ff419d79360d9468e5
