### ISSUE TITLE
Doesn't work with ACF - select2 compatibility issue

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#12924]
Current version from today 21 January 2017 doesn't work with ACF.

2.7-beta1 works with ACF.

select2.min.js?ver=3.5.2:21 Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.

**Comment by spencerfinnell** [comment]
@mikejolley That won't matter if ACF's version of select2 is loaded/enqueued first. 

Check out https://github.com/select2/select2/issues/3942

It's definitely something that will come up a lot as a lot of plugins use older versions. Hopefully WooCommerce updating will prompt others to as well.

**Comment by mikejolley** [comment]
Ref on ZD 359480, cc @mattyza

**Comment by elliotcondon** [comment]
Hi guys

Thanks for the topic.
I've made ACF PRO compatible with both Select2 v3 and v4.
There is logic to detect which library is running, and then use different 'initialize' logic.

Is this JS error coming from ACF or WC elements?

Let me do some testing and get back to you.

Thanks
E

**Comment by mikejolley** [comment]
@elliotcondon I'm not certain but his error has `select2.min.js?ver=3.5.2:21` - the WC version would have `ver=4...x`

**Comment by manake** [comment]
The file is /wp-content/plugins/advanced-custom-fields-pro/assets/inc/select2/3/select2.min.js?ver=3.5.2

ACF Pro is version 5.5.5.
WordPress is version 4.7.2.

It happens on a product editing page where (I believe) ACF technically doesn't have to load that library.

**Comment by mikejolley** [comment]
If the library is named 'select2' when registered like the one in WC, WC loading select2 will load whatever was registered.

**Comment by mikejolley** [comment]
@elliotcondon find anything?

**Comment by elliotcondon** [comment]
Hi guys

I've just done some testing with good results.
Both ACF PRO and WC are using the 'admin_enqueue_scripts' action to include the Select2 library. 
Because ACF PRO is included before WC (alphabetically), it is ACF's select2 library that is enqueued first.

I had intended for ACF's 'admin_enqueue_scripts' action to run later (priority of 20) to prevent this exact issue, but looks like my $priority was not working as expected.

I'm able to fix this from my end, and am happy to. I just need to do some testing with earlier versions of WP to make sure there are no issues with adding actions within the same action tag (recent work has been done to the way actions / filters are handled).

ACF PRO is able to work with Select2 v4, so this is a successful solution.

@mikejolley - what is the estimated release date for WC 4.7? It would be great to have some time to include this in an update - a few weeks would be ideal, but not sure if this fits with your schedule.

**Comment by elliotcondon** [comment]
Also, for any ACF devs reading, please use the `acf/setting` "select2_version" to include Select2 v4
http://www.advancedcustomfields.com/resources/acfsettings/

```
function my_acf_init() {
	
	acf_update_setting('select2_version', 4);
	
}

add_action('acf/init', 'my_acf_init');
```

**Comment by mikejolley** [comment]
@elliotcondon Thanks - 27th Feb so you have a few weeks :)

**Comment by cfxd** [comment]
I'm still experiencing issues with this, specifically the admin appearance and behavior of the Taxonomy ACF field.

The most glaring issue is that it's impossible to drag and drop a multi-select enabled field.

The styles are also definitely off—some strange focus, shadow, and borders.

**Comment by elliotcondon** [comment]
Hi @cfxd 

Shockingly, Select2 v4 does not support drag/drop reorder. This is the main reason I use v3 in my ACF. I am aware of the CSS issues and will be fixing these soon

**Comment by cfxd** [comment]
@elliotcondon thank you for the quick reply!

Unfortunately setting the ACF select2 version to `3` still doesn't allow me to drag and drop the multi-select Taxonomy field items :-/

**Comment by elliotcondon** [comment]
Hi @cfxd 

Thanks for the reply. If WooCommerce is active, it will not be possible to include Select2 v3 using the 'setting' I have mentioned above.

WooCommerce enqueues this script before ACF, so you would need to write some custom code to enqueue your own 'select2' V3 as early as possible (before WC does).

Select2 v3 and v4 look very different, you will know when v3 is active (select2 items have a gradient silver look).

If you can confirm you are having drag/drop issues with Select2 v3, please create a support ticket with WP login details so I can take a look: http://support.advancedcustomfields.com/new-ticket/

**Comment by cfxd** [comment]
@elliotcondon no issues whatsoever with Select2 v3—when I disable WooCommerce all is as it should be (that's why I'm posting here instead of ACF ;-) ).

**Comment by elliotcondon** [comment]
@cfxd All good. I'll hope to get those CSS issues sorted soon, and also hope that Select2 v4 add in drag/drop soon too

**Comment by mikejolley** [comment]
@elliotcondon they already said it was never intended to stay in the order defined so it won't support it. 

You can enhance v4 with drag drop via sortable js. See our wc-enhanced-select.js. We support it.

**Comment by cfxd** [comment]
Yes, I was able to figure this out thanks to https://github.com/select2/select2/issues/3004#issuecomment-240434765.

It would be great if there was a way to simply add my field IDs to a filtered list of elements, but for now I've just enqueued an additional .js file in my admin. Final file looks like this:

````javascript
jQuery(function($) {
  var sortableId = '#acf-field_58f9a5f61baf4';

  $(sortableId).addClass('enhanced');

  var $select = $(sortableId);
  var $list   = $(sortableId).next('.select2-container').find('ul.select2-selection__rendered');

  $list.sortable({
    placeholder : 'ui-state-highlight select2-selection__choice',
    forcePlaceholderSize: true,
    items       : 'li:not(.select2-search__field)',
    tolerance   : 'pointer',
    stop: function() {
      $($list.find('.select2-selection__choice').get().reverse()).each(function() {
        var id     = $(this).data('data').id;
        var option = $select.find('option[value="'+id+'"]')[0];
        $select.prepend(option);
      });
    }
  });
});
````

Thanks to @elliotcondon @ambroiseRabier @mikejolley.

**Comment by elliotcondon** [comment]
@mikejolley @cfxd thanks guys! I relay appreciate the info, links and snippets.
This is definitely something I will get fixed over the next few versions!
Thanks again

**Comment by elliotcondon** [comment]
Good news! I've been working on ACF + Select2v4 JS and have successfully added in the missing 'sortable' (drag/drop) compatibility.

@cfxd - thanks for your prompts mate! You will find the latest code in the acf pro 'develop' branch if you feel like testing it out.

@mikejolley - thanks for pointing me in the right direction!

Glad to have this issue sorted!

**Comment by robwatson-intechra** [comment]
Thanks! Is this now part of the latest downloadable version?

**Comment by elliotcondon** [comment]
Hi @robwatson-intechra - yes, I have added the missing 'sortable' functionality for Select2 v4 in the latest version of ACF PRO 5.5.13

**Comment by Harshart** [comment]
Hi guys sorry to intrude,

I got the same issue mentioned above with ACF (need to desactivate it otherwise the product variations doesnt load but I need ACF plugin) so I updated all my plugins and themes but I still got the issue and when I looked into my theme files I found this which means that I got select v4 no ? 

Thanks for any help,
Thomas

![screenshot 2017-07-13 at 09 53 19](https://user-images.githubusercontent.com/16083003/28156179-f81d7f2c-67b1-11e7-8337-ede2375064c7.png)
![screenshot 2017-07-13 at 09 53 16](https://user-images.githubusercontent.com/16083003/28156181-f82864b4-67b1-11e7-82e3-7a34172a480a.png)
![screenshot 2017-07-13 at 09 53 13](https://user-images.githubusercontent.com/16083003/28156180-f81e22ba-67b1-11e7-987e-9d4935328be3.png)

**Comment by elliotcondon** [comment]
Hi @Harshart 

Can you please open an ACF support ticket via the link below. Please be sure to include as much info about the issue as possible and ask for me, Elliot.
http://support.advancedcustomfields.com/new-ticket/

**Comment by Harshart** [comment]
Thanks for your answer @elliotcondon, just started a new topic on ACF support ticket as u said

https://support.advancedcustomfields.com/forums/topic/variation-products-doesnt-load-if-desactive-plugin-it-loads-but-site-full-ofbug/

Have a nice day

**Comment by elliotcondon** [comment]
Hi @Harshart 
Looks like you opened a discussion on the community forums instead of a support ticket... Can you please use the link I provided to open a support ticket?

**Comment by Harshart** [comment]
I'm sorry I was pretty sure I did use ur link, sorry. Otherwise a few days
ago, I opened a support ticket, here is the link:
https://support.advancedcustomfields.com/forums/topic/variation-products-doesnt-load-if-desactive-plugin-it-loads-but-site-full-ofbug/

Thanks for answering

**Comment by luvstuss** [comment]
@Harshart Did you get the solution for your issue? If yes, can you share it?

@elliotcondon

**Comment by ketanumretiya030** [comment]
I have used ACF Pro and The Event Calendar but in admin ACF editor tab not working. 
it will show below error if any solution please help me.
select2.min.js?ver=4.0.3:1 Uncaught Error: No select2/compat/dropdownCss
    at j (select2.min.js?ver=4.0.3:1)
    at n (select2.min.js?ver=4.0.3:1)
    at select2.min.js?ver=4.0.3:1
    at D.apply (select2.min.js?ver=4.0.3:2)
    at new e (select2.min.js?ver=4.0.3:2)
    at new e (select2.min.js?ver=4.0.3:2)
    at HTMLSelectElement.<anonymous> (select2.min.js?ver=4.0.3:3)
    at Function.each (jquery.js?ver=1.12.4:2)
    at jQuery.fn.init.each (jquery.js?ver=1.12.4:2)
    at jQuery.fn.init.a.fn.select2 (select2.min.js?ver=4.0.3:3)

**Comment by ketanumretiya030** [comment]
I have resolve above problem with below code. for conflict on the event calender plugin and ACF pro
/*============================================================================================================
Use for resolve admin select2 error for acf editor view and text not workin
==============================================================================================================*/
function enqueue_select2_jquery() {
    wp_register_style( 'select2css', '//cdnjs.cloudflare.com/ajax/libs/select2/3.4.8/select2.css', false, '1.0', 'all' );
    wp_register_script( 'select2', '//cdnjs.cloudflare.com/ajax/libs/select2/3.4.8/select2.js', array( 'jquery' ), '1.0', true );
    wp_enqueue_style( 'select2css' );
    wp_enqueue_script( 'select2' );
}
add_action( 'admin_enqueue_scripts', 'enqueue_select2_jquery' );
add_action('admin_head', 'my_admin_ket');
function my_admin_ket() {
  echo '
  <script type="text/javascript">
  jQuery(document).ready(function($) {
      jQuery(".option-tree-ui-select").select2();
  });
</script>
  ';
}

**Comment by aayzee-tech** [comment]
> I have resolve above problem with below code. for conflict on the event calender plugin and ACF pro
> /_============================================================================================================ Use for resolve admin select2 error for acf editor view and text not workin ==============================================================================================================_/
> function enqueue_select2_jquery() {
> wp_register_style( 'select2css', '//cdnjs.cloudflare.com/ajax/libs/select2/3.4.8/select2.css', false, '1.0', 'all' );
> wp_register_script( 'select2', '//cdnjs.cloudflare.com/ajax/libs/select2/3.4.8/select2.js', array( 'jquery' ), '1.0', true );
> wp_enqueue_style( 'select2css' );
> wp_enqueue_script( 'select2' );
> }
> add_action( 'admin_enqueue_scripts', 'enqueue_select2_jquery' );
> add_action('admin_head', 'my_admin_ket');
> function my_admin_ket() {
> echo '
> 
> <script type="text/javascript"> jQuery(document).ready(function($) { jQuery(".option-tree-ui-select").select2(); }); </script>
> ';
> }

You solution worked for me! Thanks a lot.
