### ISSUE TITLE
New gallery jumping

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#12922]
## EXPLANATION OF THE ISSUE

The new gallery displays one big image and thumbnails below. The thumbnail allow switching the big image.

When images are not of equal height (e.g. one is 500px tall and another in the gallery is 100px tall) it becomes irritating when I click a thumbnail and everything jumps (reduces height from 500px to 100px abruptly).

What should happen instead is the container should get fixed height (e.g. fixed to the height of the tallest image or to 1/2 of screen) in this case and all smaller images should be centered inside vertically and horizontally.

## EXAMPLES
Virtually every single shop doesn't have this issue and they fix it by doing one of the following:

1. Thumbnails are on the side in fixed position (so that after clicking one they don't ever move up or down or to sides). Example: https://www.amazon.com/AmazonBasics-USB-2-0-Cable-Male/dp/B00BCWALHM/ref=sr_1_1?s=digital-text&ie=UTF8&qid=1485018882&sr=8-1&keywords=usb+cable

2. Or when thumbnails are below the image then the container is fixed ~500px (1/2 of screen) height and all smaller images are centered vertically and horizontally and all images taller than 500px are restricted to max-height: 500px (and thus their width reduces). Example: http://www.apple.com/shop/product/MMEF2AM/A/airpods?fnode=06489225da7d69f9bbd6e59c34fb8c42906eb47bcd6ff5253e6610a952100d738e8dbc34f6734e100f3fb5ba7c5a72f722721ad22426a5d814ed74cb427b3dd015e00304793e2bc723cddd48e44747f8602b622025a8fb4d4b9d28164519c2fb (thumbnails never change their position regardless of what size is the image).

**Comment by mikejolley** [comment]
Closed in favour of #12956
