### ISSUE TITLE
woocommerce_add_to_cart_validation not called when item is re-added to cart

### ISSUE THREAD

**Issue by adal-io** [woocommerce/woocommerce#12921]
## EXPLANATION OF THE ISSUE

When a user adds an item to their cart, woocommerce_add_to_cart_validation is called as expected. However if the user removes the item from the cart and then clicks the "Undo" link, the item will be added back to their cart without first validating.

## STEPS TO REPRODUCE THE ISSUE

1. Add item to cart - woocommerce_add_to_cart_validation will be called.
2. Navigate to cart & remove the item from the cart.
3. When the cart page loads with the removal notification, click "Undo?" The product will not be validated and will automatically be re-added to the cart.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://www.outdoorclubusa.com
Site URL: https://www.outdoorclubusa.com
WC Version: 2.6.11
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.20 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 200 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.11
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (28) ###

Contact Us Form: by Kenmore Design LLC – 1.2
Cornerstone: by Themeco – 1.3.3
Custom Meta Widget: by bitacre – 1.4.8
IgniteWoo Updater: by Ignition – 2.1.7
Jetpack by WordPress.com: by Automattic – 4.4.2
OCU LoggedIn LoggedOut Shortcode: by  – 1.0
OCU WC Memberships Customizations: by  – 1.0
Outdoor Club FFLH Manager: by adal.io – 0.1
Outdoor Club Order Processing: by adal.io – 0.1
Packages Configuration for WooCommerce: by Jason Judge jason@academe.co.uk – 1.2.5
Pie Register: by Genetech Solutions – 2.0.21
Scripts n Styles: by unFocus Projects – 3.3.1
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.2.5

WooCommerce Conditional Shipping and Payments: by WooThemes – 1.2.2
eProcessing Network - WooCommerce Gateway: by Big Cloud Media – 1.0.2
WooCommerce Memberships: by WooThemes / SkyVerge – 1.7.2 – 1.7.5 is available
WooCommerce Product Archive Customiser: by jameskoster – 1.0.4
WooCommerce Product CSV Import Suite: by Automattic – 1.10.12
WOOF - WooCommerce Products Filter: by realmag777 – 1.1.6.1
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2
WooCommerce Predictive Search PRO: by A3 Revolution – 4.0.2
WooCommerce UPS Shipping: by Automattic – 3.2.1
WooCommerce Table Rate Shipping: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.11
WP All Import Pro: by Soflyy – 4.4.1
WP Fastest Cache: by Emre Vona – 0.8.6.3
WP Migrate DB: by Delicious Brains – 0.9.2
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.3

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: X
Version: 4.6.4
Author URL: http://theme.co/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: x/woocommerce/cart/cart-empty.php
x/woocommerce/cart/cross-sells.php
x/woocommerce/loop/loop-end.php
x/woocommerce/loop/loop-start.php
x/woocommerce/loop/pagination.php
x/woocommerce/notices/error.php
x/woocommerce/notices/notice.php
x/woocommerce/notices/success.php
x/woocommerce/single-product/product-image.php
x/woocommerce/single-product/product-thumbnails.php
x/woocommerce/single-product/related.php
x/woocommerce/single-product/tabs/tabs.php
x/woocommerce/single-product/up-sells.php
x/woocommerce/single-product-reviews.php

`

**Comment by mikejolley** [comment]
Why is this a problem? It's undo - not another cart button. I don't see any need to re-run it at that point - validation is ran again when you checkout anyhow.

**Comment by adal-io** [comment]
If orders can only have products from category A or category B, the user can add an item from category A, open a new tab with a product from category B, remove the A product in their cart in the first tab, add the B product, and then "Undo" the removal of the A product, allowing both A and B products in the cart.

**Comment by mikejolley** [comment]
Ok, so if you did have this kind of logic via a plugin, wouldn't the plugin need to run validation on the CART validation hooks too? Just running logic on add to cart is not enough.
