### ISSUE TITLE
Mail to customer are sent in admin user  language and not in site language

### ISSUE THREAD

**Issue by quasel** [woocommerce/woocommerce#12931]
## EXPLANATION OF THE ISSUE

If an "Admin" switches his language using https://make.wordpress.org/core/2016/11/07/user-admin-languages-and-locale-switching-in-4-7/ all Mails he triggers are sent in his language instead 

## STEPS TO REPRODUCE THE ISSUE

Switch "Admin" User Language to one different from the "Site" 

WC Version: 2.6.13

**Comment by mikejolley** [comment]
Potentially use https://github.com/WordPress/WordPress/blob/2328e7b17a7627d16275a145ad6d1a484529e583/wp-includes/l10n.php#L1273

**Comment by quasel** [comment]
Or maybe even consider using the "locale" of the "customer" if appropriate
