### ISSUE TITLE
using woocommerce_calculated_total to round gives incorrect tax

### ISSUE THREAD

**Issue by stupidchief** [woocommerce/woocommerce#12932]
## EXPLANATION OF THE ISSUE

Shop total is e.g. 740.46 (includes €138.46 Tax)
I then round the total using woocommerce_calculated_total
Shop total is now : 740 (includes €138.46 Tax)
The tax value does not change. This is wrong.
Tax rate is 23% so correct tax is (740 / 123) * 23 = €138.**37**

## STEPS TO REPRODUCE THE ISSUE

function filter_calculate_totals($round)
{
    return round($round, 0, PHP_ROUND_HALF_UP);
}
add_filter('woocommerce_calculated_total', 'filter_calculate_totals');

**Comment by mikejolley** [comment]
You're just changing the rounding on the main total for display purposes, not the original stored and calculated values for everything that it is calculated from. It would be impossible to work out how much of your new value came off of which other values (is the missing .46 tax? cart items? shipping?)

 If you don't want cents, don't round to 2 dp. Changing taxes and totals like this is fundamental wrong IMO.

**Comment by stupidchief** [comment]
It is a requirement by the revenue service that final tax rate includes exact cents.
However my client does not want to deal with cents so wants to round the final total.

So this filter is for display purposes only and doesn't change values. This seems strange to me.

**Comment by mikejolley** [comment]
It's not strange because if you stored display values, future sums and rounding would be wrong.
