### ISSUE TITLE
[2.7] Allow replace flexslider for image gallery

### ISSUE THREAD

**Issue by seriusokhatsky** [woocommerce/woocommerce#12934]
## EXPLANATION OF THE ISSUE

Please, add the ability to disable flexslider for `.woocommerce-product-gallery`. We can `dequeue` the Flexslider library, but if some plugin or custom code will enqueue it again then this code will enable flexslider for the gallery 

`			if ( $.isFunction( $.fn.flexslider ) ) {
				this.init_flexslider();
			}
`

Is it possible to disable flexslider completely without changing HTML structure and class names?

Also, we don't see any usage of the `is_touch_device ` method in `wc_product_gallery` class. Why do you need to keep it?

**Comment by mikejolley** [comment]
> Please, add the ability to disable flexslider for .woocommerce-product-gallery. We can dequeue the Flexslider library, but if some plugin or custom code will enqueue it again then this code will enable flexslider for the gallery

If you're enqueuing multiple lightbox scripts on one site that is terribly wasteful. Just saying.

**Comment by seriusokhatsky** [comment]
I'm not talking about lightbox script, we don't use multiple lightboxes. 

Flexslider is a slider for product images and we want remove it completely and be able to add another one (owlCarousel for example). 

And we are talking about WP theme so if some user will activate any plugin with flexslider library enqueued then `init_flexslider()` will be hired and may conflict with owl.

Thank you for getting back to me

**Comment by mikejolley** [comment]
See #13009
