### ISSUE TITLE
Extremely inconsistent variation price

### ISSUE THREAD

**Issue by lucasstark** [woocommerce/woocommerce#12936]
It's very inconsistent to get the price for a WC_Product_Variation.   Sometimes get_price() will return the price of the variation, other times it returns an empty string.   

This inconsistency will cause unexpected behavior if you need to reliably get the variation price, for example when applying a discount. 

 To reproduce create a function which calls get price on a variation at multiple points during a wc page load.  

An example is listed below.   

```
add_filter( 'woocommerce_product_is_on_sale', 'test_is_on_sale', 10, 2 );
function test_is_on_sale( $is_on_sale, $product ) {

	if ( $product->is_type( 'variation' ) ) {
		$price = $product->get_price( 'view' );

		file_put_contents ( __DIR__ . '/price-debug.txt' , 'Product ID: ' . $product->get_id() . ' - ' . $price . PHP_EOL, FILE_APPEND);

	}

	return $is_on_sale;
}
```

Look in the price-debug.txt file after you add that filter to your functions file or elsewhere and you will see that sometimes the price is associated with the variation and other times it is not.

**Comment by franticpsyx** [comment]
@mikejolley Looks like all these calls should be in `edit` context: https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L194-L198

Also I don't understand why the variation price is not read directly from the post meta there -- compare against https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L234

Is there a reason for this?

**Comment by thebestbradley1** [comment]
I am also having a problem with variation pricing. I have a client that has a dinner plate with two sides. I add new sides from time to time, I create the new variations with the upcharge price. The variations show up but when selected only a handful actually update the price. Any help would be appreciated. The site can be found at www.nutritionsolutionsonline.com

**Comment by mikejolley** [comment]
@franticpsyx hmm I guess to ensure it's always accurate. But using the correct context should resolve anyway.

@thebestbradley1 your comment was unreleased to this issue with 2.7. This is not a support site. Use the forums. I've deleted your comment to reduce noise.
