### ISSUE TITLE
product image option not showing any more

### ISSUE THREAD

**Issue by jinjindf98** [woocommerce/woocommerce#12930]
## EXPLANATION OF THE ISSUE

Go to add new product and there is no longer PRODUCT IMAGE, only Product Gallery. I go to screen options and all the boxes are ticked and there is no product image there any way. 
Just want to be able to add images to new products for our website.
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Themes can disable featured image support. It's likely that as no one else has reported the issue, and it's working here.

Switch themes/rule out plugins. It should come back after switching, then you can look at their code.
