### ISSUE TITLE
get_price_including_tax() does not work when DOING_CRON

### ISSUE THREAD

**Issue by pavelevap** [woocommerce/woocommerce#12935]
I am using custom function to export all of my products with prices once a day (by WP cron) for other usage. But `get_price_including_tax()` returns price without tax, which is wrong and it is caused by following circumstances:

Function `get_price_including_tax()` is [using](https://github.com/woocommerce/woocommerce/blob/4d155a1f28c3f21e123ff2e45c568510db40a6d1/includes/abstracts/abstract-wc-product.php#L880) function `WC_Tax::get_rates()` when `woocommerce_prices_include_tax` is set to `no`.

And `get_rates()` is [using](https://github.com/woocommerce/woocommerce/blob/4d155a1f28c3f21e123ff2e45c568510db40a6d1/includes/class-wc-tax.php#L397) function `get_tax_location()` which [works](https://github.com/woocommerce/woocommerce/blob/4d155a1f28c3f21e123ff2e45c568510db40a6d1/includes/class-wc-tax.php#L376) with `WC()->customer`.

But in my case `WC()->customer` is `NULL` because `WC_Customer` class is not instatiated because of following [check](https://github.com/woocommerce/woocommerce/blob/4d155a1f28c3f21e123ff2e45c568510db40a6d1/woocommerce.php#L346): `if ( $this->is_request( 'frontend' ) ) {`

Why? `frontend` case is [checking](https://github.com/woocommerce/woocommerce/blob/4d155a1f28c3f21e123ff2e45c568510db40a6d1/woocommerce.php#L219) for `defined( 'DOING_CRON' )` which is `true` in this case.

In the case of empty `WC()->customer`, there is another [condition](https://github.com/woocommerce/woocommerce/blob/4d155a1f28c3f21e123ff2e45c568510db40a6d1/includes/class-wc-tax.php#L378): `elseif ( wc_prices_include_tax() || 'base' === get_option( 'woocommerce_default_customer_address' ) || 'base' === get_option( 'woocommerce_tax_based_on' ) )` to get some default country.

But `wc_prices_include_tax()` is `false` because we are using `woocommerce_prices_include_tax` set to `no`. And other conditions are working only in default `base` cases. But shop owners can set `woocommerce_tax_based_on` as `billing` or `shipping` and `woocommerce_default_customer_address` as `geolocation`. In these cases it will not work because when `get_tax_location()` is empty in the end, following [check](https://github.com/woocommerce/woocommerce/blob/4d155a1f28c3f21e123ff2e45c568510db40a6d1/includes/class-wc-tax.php#L400) will not work, `get_rates()` will be also empty and that is why `get_price_including_tax()` will return price without any tax :-( Even if there is only one tax rate for all countries.

I am not sure if/where this should be fixed? If there should be condition to load `WC_Customer` when using cron or checks inside `get_tax_location()`?

**Summary:**

1) When I export the same product data into custom `.xml` file, `get_price_including_tax()` **does not work** correctly. But when I use `/?feed=data` with the help of `add_feed()` WP function, `get_price_including_tax()` **works** and the only difference is in `DOING_CRON` check which is strange...

2) When there is only one tax rate for all countries (usual in European union), there is no need to check customer country or geolocate IP, I guess, and we can use this rate by default?

Related to #7183.

**Comment by mikejolley** [comment]
This IMO should not be changed. If you're exporting data, using geolocation or customer address/billing/shipping is wrong..it would vary based on the person doing the export. Why not hardcode it (the option I mean) to use store base address during export so it's consistent. Or better yet, export real/stored prices, not inc/ex prices specifically.

1. All down to where customers are loaded. I don't think loading customers where they are not needed (cron) to workaround an edge base like this is needed. It would just cause un-needed load for 99% of users.

2. So you can disable the geolocation setting and simply the settings on the store itself.

Hope this makes sense.
