### ISSUE TITLE
On sale variations do not show price with original struck out

### ISSUE THREAD

**Issue by lucasstark** [woocommerce/woocommerce#12933]
Create a variable product, create two ( or more ) variations with different prices.  Set one of the variations to be on sale.   The shop, single product and cart no longer display the sale price.  The struck though price only appears when you select the variation on the single product page which is on sale.   

If this is the intended behavior I think it needs to be very clear in the documentation that this is an intended change, otherwise there will be bug reports for any plugin which creates discounts or otherwise modifies the prices of variations where the reporter will think the extension is causing the issue.  

The reason this occurs is the WC_Product_Variable::get_price_html() function no longer checks anything regarding sale prices.

**Comment by mikejolley** [comment]
@lucasstark This was intentional actually. Striked out prices combined with ranges looks awful, confusing, and long. We opted to just show the basic range for variables (sale prices still show for variations after selection).

I can explicitly add to readme if thats enough?

**Comment by lucasstark** [comment]
@mikejolley Sounds good to me, just wanted to make sure so that when we get tickets for things like Dynamic Pricing not showing a struck out price anymore I can point them in the right direction.  I could always add it back in myself in the extension, but I agree it never looked very good.

**Comment by ilyanim** [comment]
hi @lucasstark I would like to get the original price strike out back (for variable items), can you please help me? (they're gone after I updated Woocommerce and my theme, so I am not sure what caused it).
