### ISSUE TITLE
[REST API] Get product total

### ISSUE THREAD

**Issue by dunets** [woocommerce/woocommerce#12948]
After analysing [documentation](http://woocommerce.github.io/woocommerce-rest-api-docs/#pagination)
I found that there are no information about how to get, for example, a total number of products.
It's important to have it, when we need to create a simple paginator...

The problem is that `per_page` attribute, has a limit of 100, so there we need a way to obtain OR total number of products OR total number of pages.

**Comment by claudiosanches** [comment]
> After analysing documentation
> I found that there are no information about how to get, for example, a total number of products.
> It's important to have it, when we need to create a simple paginator...

![screenshot from 2017-01-23 17-41-16](https://cloud.githubusercontent.com/assets/1264099/22219750/31dffbae-e193-11e6-9f20-cb5f32af97cf.png)

Looks like you missed the note about `X-WP-Total` and `X-WP-TotalPages`.

**Comment by dunets** [comment]
@claudiosanches ok... but can explain me please how to get these headers?
I need a simple function that returns products total... I have no idea how to get these headers... these code return only JSON
![image](https://cloud.githubusercontent.com/assets/6217617/22221581/a1e40b30-e1ab-11e6-854e-f7657bf475ea.png)

**Comment by claudiosanches** [comment]
@dunets how you get any header from a request using PHP or cURL or anything?

**Comment by dunets** [comment]
@claudiosanches  well... first I need a URL :)
but it's does not work
![image](https://cloud.githubusercontent.com/assets/6217617/22223100/7c3a0a00-e1b1-11e6-9d85-d675efac6b3a.png)
![image](https://cloud.githubusercontent.com/assets/6217617/22223211/f1367b72-e1b1-11e6-8ea4-0fc2b4677361.png)

**Comment by claudiosanches** [comment]
@dunets better you learn first how to do requests on PHP.

**Comment by dunets** [comment]
Well I make a request like this:
![image](https://cloud.githubusercontent.com/assets/6217617/22430949/c913e1ba-e707-11e6-8280-4b3895002273.png)

and I get these result... with status `401` ...
You can't just help me to construct that function? It's for my school project and it's the last thing I need to do... And I can't spend more time on studying all the things because of a deadline....

**Comment by claudiosanches** [comment]
@dunets but under HTTP it's not allowed Basic Authentication... You can only use Basic Authentication under HTTPS.
