### ISSUE TITLE
PrettyPhoto - changing to blueimp - problem with scripts

### ISSUE THREAD

**Issue by gwgw** [woocommerce/woocommerce#12946]
## EXPLANATION OF THE ISSUE

Hi, i'm working on linux + localhost + custom WP theme,
after customizing WC Scripts output, i sucessfully removed
css and js for prettyPhoto.
On my WordPress single post and pages i'm usinge blueimp gallery,
it works fine.
To customize single product gallery i hook into actions:
before and after single product summary, to add proper html 
container wrapper for blueimp gallery.
This don't work, so i fork in quick and dirty way original WC template
for single product(meta.php.) Just copy and pasted my images gallery here.
Its still don't work.

My scripts load on every WC and WP page in footer, and works, only on WC pages
gallery don't work.
Do i need to remove/reorder my/WC script to use my gallery?
Do i need hook into another actions and change default WC content, to make this gallery work?
Sorry for my English

**Comment by mikejolley** [comment]
Hard for us to say from that information tbh. We don't support customisations here, but I reckon you need to look at the Javascript developer console in your browser to see what errors your new script is generating. It may be that prettyphoto is still enqueued or you're missing a dependency for example.

**Comment by gwgw** [comment]
Thank you for respond, my console don't output any errors, and all 
galleries from blueimp
works fine on default wordpress single posts/pages.
I'm familiar enough with WooCommerce to edit html content with hook, like:
remove action(name, name)
add action(name, myname) -> here editing content

I added my default blog pagination before and after main shop loop with 
this,
and remove default WC pagination, also added my own css styles,
and everything  works fine, so i'am familiar enough to do some 
customization.

I know i shouldn't ask with label error, but please, could anyone with 
WC could
answer me this:
- Is it possible to run WC pages without jQuery at all??
I want pure vanilla js website, only wc adds so many scripts, i'm not 
trying to be
mean, i love WC flexibility, but i'm that no-jquery-type.

Sorry for my poor English, i hope it make sense,
kind regards,
Gabrielle
