### ISSUE TITLE
WC Settings API Limitation with Multi-Dimensional Arrays

### ISSUE THREAD

**Issue by mjke87** [woocommerce/woocommerce#12941]
Hi,

While implementing an extension for WooCommerce I stumbled upon a limitation which disallowed me from loading multi-dimensional arrays as setting values using the WC Settings API.

The limitation lies in the following code:

```
class WC_Admin_Settings {

	...

	public static function get_option( $option_name, $default = '' ) {

		...

		if ( is_array( $option_value ) ) {
			$option_value = array_map( 'stripslashes', $option_value );
		} elseif ( ! is_null( $option_value ) ) {
			$option_value = stripslashes( $option_value );
		}
		return $option_value === null ? $default : $option_value;
	}

	...

}
```
"Stripslashing" a multi-dimensional array will simply result in an array of `NULL`s. 

There's two possible and straightforward solutions for this:
1. Introduce a new filter call in the final return statement of the function `get_option`.
2. Implement a recursive stripslash function, similiar to the example on [PHP.net](http://php.net/manual/en/function.stripslashes.php#example-5496)

Please let me know if this is a potential extension for WooCommerce, and which of the two solutions would be appropriate. I'll gladly provide the necessary code if needed. 

Thank you and kind regards,
Mike

**Comment by claudiosanches** [comment]
> storing/loading multi-dimensional serialized arrays

Sending an array or serialized data?

**Comment by mjke87** [comment]
Saving data works as it should. Just loading a multi-dimensional array doesn't. The unserializing part of the loading works fine too, since it is already handled by WordPress' `get_option` function. It really narrows down to this `stripslashes` problem that I mentioned.

**Comment by claudiosanches** [comment]
@mjke87 can you test it for me?

Change:

```php
		if ( is_array( $option_value ) ) {
			$option_value = array_map( 'stripslashes', $option_value );
		} elseif ( ! is_null( $option_value ) ) {
			$option_value = stripslashes( $option_value );
		}
```
to

```php
			$option_value = wp_unslash( $option_value );
```

**Comment by mjke87** [comment]
@claudiosanches Nice find with the `wp_unslash` function. I'll test it tomorrow morning. I have no access to the project at the moment. I'll let you know about the result asap.

**Comment by mjke87** [comment]
@claudiosanches I tested it with `wp_unslash` and it works nicely. I get the correct results now. However, I stumbled upon a second hurdle in the same function, which in effect is the same problem.

Once I retrieve the values I want to render the fields using the function `WC_Admin_Settings::output_fields` which in turn calls the function `WC_Admin_Settings::get_option` again for each field in the passed array.

The function works fine for simple arrays. For example if the field key is `some_field[3]`, the function will correctly fetch all `some_field` values and return the value at index `3`.

However, when using multi-dimensional arrays, the function does not work correctly. For example if the field key is `some_field[3][first_name]`, function will again fetch all `some_field` values and return the value at index `3`, which in this case is an array, ignoring the `[first_name]` part of the name.

Both, the `parse_str` and WP's `get_option` functions work correctly, but the logic after the getting the option value needs elaboration:

```
class WC_Admin_Settings {

	...

	public static function get_option( $option_name, $default = '' ) {

		...
		// Option name is first key --> WORKS CORRECTLY
		$option_name = current( array_keys( $option_array ) );

		// Get value --> WORKS CORRECTLY
		$option_values = get_option( $option_name, '' );

		// WORKS CORRECTLY for simple arrays, but ignores any sub-indexes
		$key = key( $option_array[ $option_name ] );

		if ( isset( $option_values[ $key ] ) ) {
			$option_value = $option_values[ $key ];
		} else {
			$option_value = null;
		} 
	}

	...

}
```

I guess we need to develop some kind of recursive algorithm for fetching the correct value. Let me know what you think. Meanwhile, I'll be testing some different implementations that best solve this problem.

Regards, Mike

**Comment by mjke87** [comment]
Hi @claudiosanches 

The following non-recursive approach seems to work so far:

Replace
```
$key = key( $option_array[ $option_name ] );

if ( isset( $option_values[ $key ] ) ) {
    $option_value = $option_values[ $key ];
} else {
    $option_value = null;
} 
```

With
```
while ( is_array( $option_array[ $option_name ] ) ) {
    $option_array  = $option_array[ $option_name ];
    $option_name   = key( $option_array );
    $option_values = $option_values[ $option_name ];
}

$option_value = $option_values;
```

Kind regards,
Mike

**Comment by mikejolley** [comment]
@claudiosanches do we actually want to support this?

**Comment by mikejolley** [comment]
@mjke87 although it may 'seem' like it's a quick fix, I'm concerned this may have implications for both the UI (how to show these fields?), future UI projects, and how to represent and support these fields in the REST API.  If we made this change, it would be our responsibility to maintain support for it forever, even though _core_ does not currently have a need for it.

An alternative approach which works now would be to use the actions and filters to add a new input type for your (I assume) repeating set of fields. It's what we've done in the past with extensions such as table rate shipping - when you make a custom field type you can control the POST and storage of the field data.

If however you were up for putting together a working PR which passes tests, and works with the Settings REST API in 2.7, we'd certainly like to review the code and consider merging it. I'll leave that up to you :)

Take a look here for reference https://github.com/woocommerce/woocommerce/wiki/Settings-API

For now I'm closing this as a won't fix but as I said, I'd be open to a PR.
