### ISSUE TITLE
Add a WYSWYG type to the WC Settings API

### ISSUE THREAD

**Issue by asalkey** [woocommerce/woocommerce#12957]
## EXPLANATION OF THE ISSUE

I created a new custom email. Within the email settings page for my custom email I would like to have a wyswyg but there is no option do so.

My custom email page looks similar to this:
![screen shot 2017-01-23 at 5 10 54 pm](https://cloud.githubusercontent.com/assets/1271601/22229835/03fb1a88-e18f-11e6-972c-b46a80700b03.png)

## STEPS TO REPRODUCE THE ISSUE
1. Create a custom email class
2. Within the init_form_fields function if you attempt to add a wyswyg it will obviously not work because there is no option for it within the WC Settings API Class.
```
           $this->form_fields = array(
            'body' => array(
                'title'       => 'Email Body',
                'type'        => 'wyswyg',
                'description' => sprintf( __( 'This controls the body within the email notification. Leave blank to use the default body: <code>%s</code>.' ), $this->body ),
                'placeholder' => '',
                'default'     => ''
            )
        );

```

I looked in the **woocommerce/includes/abstracts/abstract-wc-settings-api.php** file and there is no filter or way to add the wyswyg option currently

**Comment by mikejolley** [comment]
This isn't something we want to support in WC core right now since core has no use for it. You can register custom field types using the actions/filters, or apply a simple wyswyg with JavaScript. It's possible right now by doing that :)
