### ISSUE TITLE
REST API Update Product - Converting Simple Product to Variable Does Not Create Variations

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#12955]
WC Version:		2.6.13
WP Version:		4.7.1

I'm updating a product to a variable product with 2 variations with the following request:

{
  "attributes": [
    {
      "id": 1, 
      "name": "color", 
      "options": [
        "Black", 
        "Blue"
      ], 
      "position": 1, 
      "variation": "true", 
      "visible": "true"
    }, 
    {
      "id": 2, 
      "name": "Size", 
      "options": [
        "Medium", 
        "Small"
      ], 
      "position": 2, 
      "variation": "true", 
      "visible": "true"
    }
  ], 
  "backorders": "no", 
  "button_text": "", 
  "catalog_visibility": "catalog", 
  "categories": [
    {
      "id": 9
    }, 
    {
      "id": 11
    }
  ], 
  "cross_sell_ids": [
    70, 
    31, 
    104
  ], 
  "date_on_sale_from": "", 
  "date_on_sale_to": "", 
  "description": "<p>Beautifully designed 500ml water bottles available in a range of sizes and colours</p>\n", 
  "dimensions": {
    "height": "50", 
    "length": "100", 
    "width": "200"
  }, 
  "download_expiry": -1, 
  "download_limit": -1, 
  "download_type": "standard", 
  "downloadable": "false", 
  "downloads": [], 
  "external_url": "", 
  "featured": "true", 
  "id": "3291", 
  "images": [
    {
      "alt": "Water Bottles", 
      "id": 3292, 
      "name": "Bottled Water", 
      "position": 0, 
      "src": "https://mywebsite.com/wp-content/uploads/2016/12/woda.jpg"
    }, 
    {
      "alt": "Main Picture", 
      "id": 3293, 
      "name": "Water Bottle", 
      "position": 1, 
      "src": "https://mywebsite.com/wp-content/uploads/2016/12/water-1760521_640.png"
    }
  ], 
  "in_stock": "false", 
  "manage_stock": "false", 
  "menu_order": 2, 
  "name": "Water Bottles", 
  "parent_id": 0, 
  "purchase_note": "<p>Please call for password to unlock - thanks!</p>\n", 
  "regular_price": "", 
  "reviews_allowed": "true", 
  "sale_price": "", 
  "shipping_class": "standard", 
  "short_description": "<p>Standard 500ml water bottles</p>\n", 
  "sku": "PD885536", 
  "sold_individually": "false", 
  "status": "publish", 
  "stock_quantity": 0, 
  "tags": [
    {
      "id": 51
    }, 
    {
      "id": 46
    }
  ], 
  "tax_class": "", 
  "tax_status": "taxable", 
  "type": "variable", 
  "upsell_ids": [
    53, 
    56
  ], 
  "variations": [
    {
      "attributes": [
        {
          "id": 1, 
          "name": "color", 
          "option": "Black"
        }, 
        {
          "id": 2, 
          "name": "Size", 
          "option": "Medium"
        }
      ], 
      "backorders": "", 
      "date_on_sale_from": "", 
      "date_on_sale_to": "", 
      "dimensions": {
        "height": "", 
        "length": "", 
        "width": ""
      }, 
      "download_expiry": 0, 
      "download_limit": 0, 
      "downloadable": "false", 
      "downloads": [], 
      "images": [], 
      "in_stock": "false", 
      "manage_stock": "false", 
      "regular_price": "16", 
      "sale_price": "", 
      "shipping_class": "", 
      "stock_quantity": 0, 
      "tax_class": "", 
      "tax_status": "", 
      "virtual": "false", 
      "visible": "false", 
      "weight": ""
    }, 
    {
      "attributes": [
        {
          "id": 1, 
          "name": "color", 
          "option": "Black"
        }, 
        {
          "id": 2, 
          "name": "Size", 
          "option": "Small"
        }
      ], 
      "backorders": "", 
      "date_on_sale_from": "", 
      "date_on_sale_to": "", 
      "dimensions": {
        "height": "", 
        "length": "", 
        "width": ""
      }, 
      "download_expiry": 0, 
      "download_limit": 0, 
      "downloadable": "false", 
      "downloads": [], 
      "images": [], 
      "in_stock": "false", 
      "manage_stock": "false", 
      "regular_price": "", 
      "sale_price": "", 
      "shipping_class": "", 
      "stock_quantity": 0, 
      "tax_class": "", 
      "tax_status": "", 
      "virtual": "false", 
      "visible": "false", 
      "weight": ""
    }
  ], 
  "virtual": "false", 
  "weight": "25"
}

The product variations are not being created - here's the response that I get:

{
  "_links": {
    "collection": [
      {
        "href": "https://mywebsite.com/wp-json/wc/v1/products"
      }
    ], 
    "self": [
      {
        "href": "https://mywebsite.com/wp-json/wc/v1/products/3291"
      }
    ]
  }, 
  "attributes": [
    {
      "id": 1, 
      "name": "color", 
      "options": [
        "Black", 
        "Blue"
      ], 
      "position": 1, 
      "variation": true, 
      "visible": true
    }, 
    {
      "id": 2, 
      "name": "Size", 
      "options": [
        "Medium", 
        "Small"
      ], 
      "position": 2, 
      "variation": true, 
      "visible": true
    }
  ], 
  "average_rating": "0.00", 
  "backordered": false, 
  "backorders": "no", 
  "backorders_allowed": false, 
  "button_text": "", 
  "catalog_visibility": "catalog", 
  "categories": [
    {
      "id": 9, 
      "name": "Clothing", 
      "slug": "clothing"
    }, 
    {
      "id": 11, 
      "name": "Music", 
      "slug": "music"
    }
  ], 
  "cross_sell_ids": [
    70, 
    31, 
    104
  ], 
  "date_created": "2016-12-14T02:46:36", 
  "date_modified": "2017-01-23T22:26:44", 
  "date_on_sale_from": "", 
  "date_on_sale_to": "", 
  "default_attributes": [], 
  "description": "<p>Beautifully designed 500ml water bottles available in a range of sizes and colours</p>\n", 
  "dimensions": {
    "height": "50", 
    "length": "100", 
    "width": "200"
  }, 
  "download_expiry": -1, 
  "download_limit": -1, 
  "download_type": "standard", 
  "downloadable": false, 
  "downloads": [], 
  "external_url": "", 
  "featured": true, 
  "grouped_products": [], 
  "id": 3291, 
  "images": [
    {
      "alt": "Water Bottles", 
      "date_created": "2016-12-14T02:46:38", 
      "date_modified": "2017-01-23T22:26:45", 
      "id": 3292, 
      "name": "Bottled Water", 
      "position": 0, 
      "src": "https://mywebsite.com/wp-content/uploads/2016/12/woda.jpg"
    }, 
    {
      "alt": "Main Picture", 
      "date_created": "2016-12-14T02:46:50", 
      "date_modified": "2017-01-23T22:26:45", 
      "id": 3293, 
      "name": "Water Bottle", 
      "position": 1, 
      "src": "https://mywebsite.com/wp-content/uploads/2016/12/water-1760521_640.png"
    }
  ], 
  "in_stock": false, 
  "manage_stock": false, 
  "menu_order": 2, 
  "name": "Water Bottles", 
  "on_sale": false, 
  "parent_id": 0, 
  "permalink": "https://mywebsite.com/product/water-bottles/", 
  "price": "", 
  "price_html": "", 
  "purchasable": false, 
  "purchase_note": "<p>Please call for password to unlock - thanks!</p>\n", 
  "rating_count": 0, 
  "regular_price": "", 
  "related_ids": [
    99, 
    102, 
    83, 
    60, 
    31
  ], 
  "reviews_allowed": true, 
  "sale_price": "", 
  "shipping_class": "standard", 
  "shipping_class_id": 45, 
  "shipping_required": true, 
  "shipping_taxable": true, 
  "short_description": "<p>Standard 500ml water bottles</p>\n", 
  "sku": "PD885536", 
  "slug": "water-bottles", 
  "sold_individually": false, 
  "status": "publish", 
  "stock_quantity": null, 
  "tags": [
    {
      "id": 51, 
      "name": "Awesome", 
      "slug": "awesome"
    }, 
    {
      "id": 46, 
      "name": "Trendy", 
      "slug": "trendy"
    }
  ], 
  "tax_class": "", 
  "tax_status": "taxable", 
  "total_sales": 3, 
  "type": "variable", 
  "upsell_ids": [
    53, 
    56
  ], 
  "variations": [], 
  "virtual": false, 
  "weight": "25"
}

If I send the exact same request a 2nd time it usually does create the variations - here's the response I get for the 2nd request:

{
  "_links": {
    "collection": [
      {
        "href": "https://mywebsite.com/wp-json/wc/v1/products"
      }
    ], 
    "self": [
      {
        "href": "https://mywebsite.com/wp-json/wc/v1/products/3291"
      }
    ]
  }, 
  "attributes": [
    {
      "id": 1, 
      "name": "color", 
      "options": [
        "Black", 
        "Blue"
      ], 
      "position": 1, 
      "variation": true, 
      "visible": true
    }, 
    {
      "id": 2, 
      "name": "Size", 
      "options": [
        "Medium", 
        "Small"
      ], 
      "position": 2, 
      "variation": true, 
      "visible": true
    }
  ], 
  "average_rating": "0.00", 
  "backordered": false, 
  "backorders": "no", 
  "backorders_allowed": false, 
  "button_text": "", 
  "catalog_visibility": "catalog", 
  "categories": [
    {
      "id": 9, 
      "name": "Clothing", 
      "slug": "clothing"
    }, 
    {
      "id": 11, 
      "name": "Music", 
      "slug": "music"
    }
  ], 
  "cross_sell_ids": [
    70, 
    31, 
    104
  ], 
  "date_created": "2016-12-14T02:46:36", 
  "date_modified": "2017-01-23T22:39:09", 
  "date_on_sale_from": "", 
  "date_on_sale_to": "", 
  "default_attributes": [], 
  "description": "<p>Beautifully designed 500ml water bottles available in a range of sizes and colours</p>\n", 
  "dimensions": {
    "height": "50", 
    "length": "100", 
    "width": "200"
  }, 
  "download_expiry": -1, 
  "download_limit": -1, 
  "download_type": "standard", 
  "downloadable": false, 
  "downloads": [], 
  "external_url": "", 
  "featured": true, 
  "grouped_products": [], 
  "id": 3291, 
  "images": [
    {
      "alt": "Water Bottles", 
      "date_created": "2016-12-14T02:46:38", 
      "date_modified": "2017-01-23T22:39:10", 
      "id": 3292, 
      "name": "Bottled Water", 
      "position": 0, 
      "src": "https://mywebsite.com/wp-content/uploads/2016/12/woda.jpg"
    }, 
    {
      "alt": "Main Picture", 
      "date_created": "2016-12-14T02:46:50", 
      "date_modified": "2017-01-23T22:39:10", 
      "id": 3293, 
      "name": "Water Bottle", 
      "position": 1, 
      "src": "https://mywebsite.com/wp-content/uploads/2016/12/water-1760521_640.png"
    }
  ], 
  "in_stock": false, 
  "manage_stock": false, 
  "menu_order": 2, 
  "name": "Water Bottles", 
  "on_sale": false, 
  "parent_id": 0, 
  "permalink": "https://mywebsite.com/product/water-bottles/", 
  "price": "16", 
  "price_html": "<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>16.00</span>", 
  "purchasable": true, 
  "purchase_note": "<p>Please call for password to unlock - thanks!</p>\n", 
  "rating_count": 0, 
  "regular_price": "", 
  "related_ids": [
    83, 
    102, 
    47, 
    37, 
    87
  ], 
  "reviews_allowed": true, 
  "sale_price": "", 
  "shipping_class": "standard", 
  "shipping_class_id": 45, 
  "shipping_required": true, 
  "shipping_taxable": true, 
  "short_description": "<p>Standard 500ml water bottles</p>\n", 
  "sku": "PD885536", 
  "slug": "water-bottles", 
  "sold_individually": false, 
  "status": "publish", 
  "stock_quantity": null, 
  "tags": [
    {
      "id": 51, 
      "name": "Awesome", 
      "slug": "awesome"
    }, 
    {
      "id": 46, 
      "name": "Trendy", 
      "slug": "trendy"
    }
  ], 
  "tax_class": "", 
  "tax_status": "taxable", 
  "total_sales": 3, 
  "type": "variable", 
  "upsell_ids": [
    53, 
    56
  ], 
  "variations": [
    {
      "attributes": [
        {
          "id": 1, 
          "name": "color", 
          "option": "Black"
        }, 
        {
          "id": 2, 
          "name": "Size", 
          "option": "Medium"
        }
      ], 
      "backordered": false, 
      "backorders": "no", 
      "backorders_allowed": false, 
      "date_created": "2017-01-23T22:39:10", 
      "date_modified": "2017-01-23T22:39:10", 
      "date_on_sale_from": "", 
      "date_on_sale_to": "", 
      "dimensions": {
        "height": "50", 
        "length": "100", 
        "width": "200"
      }, 
      "download_expiry": -1, 
      "download_limit": -1, 
      "downloadable": false, 
      "downloads": [], 
      "id": 3402, 
      "image": [
        {
          "alt": "Water Bottles", 
          "date_created": "2016-12-14T02:46:38", 
          "date_modified": "2017-01-23T22:39:10", 
          "id": 3292, 
          "name": "Bottled Water", 
          "position": 0, 
          "src": "https://mywebsite.com/wp-content/uploads/2016/12/woda.jpg"
        }
      ], 
      "in_stock": false, 
      "manage_stock": false, 
      "on_sale": false, 
      "permalink": "https://mywebsite.com/product/water-bottles/?attribute_pa_color=black&attribute_pa_size=medium", 
      "price": "16", 
      "purchasable": true, 
      "regular_price": "16", 
      "sale_price": "", 
      "shipping_class": "standard", 
      "shipping_class_id": 45, 
      "sku": "PD885536", 
      "stock_quantity": null, 
      "tax_class": "", 
      "tax_status": "taxable", 
      "virtual": false, 
      "visible": true, 
      "weight": "25"
    }, 
    {
      "attributes": [
        {
          "id": 1, 
          "name": "color", 
          "option": "Black"
        }, 
        {
          "id": 2, 
          "name": "Size", 
          "option": "Small"
        }
      ], 
      "backordered": false, 
      "backorders": "no", 
      "backorders_allowed": false, 
      "date_created": "2017-01-23T22:39:10", 
      "date_modified": "2017-01-23T22:39:10", 
      "date_on_sale_from": "", 
      "date_on_sale_to": "", 
      "dimensions": {
        "height": "50", 
        "length": "100", 
        "width": "200"
      }, 
      "download_expiry": -1, 
      "download_limit": -1, 
      "downloadable": false, 
      "downloads": [], 
      "id": 3403, 
      "image": [
        {
          "alt": "Water Bottles", 
          "date_created": "2016-12-14T02:46:38", 
          "date_modified": "2017-01-23T22:39:10", 
          "id": 3292, 
          "name": "Bottled Water", 
          "position": 0, 
          "src": "https://mywebsite.com/wp-content/uploads/2016/12/woda.jpg"
        }
      ], 
      "in_stock": false, 
      "manage_stock": false, 
      "on_sale": false, 
      "permalink": "https://mywebsite.com/product/water-bottles/?attribute_pa_color=black&attribute_pa_size=small", 
      "price": "", 
      "purchasable": false, 
      "regular_price": "", 
      "sale_price": "", 
      "shipping_class": "standard", 
      "shipping_class_id": 45, 
      "sku": "PD885536", 
      "stock_quantity": null, 
      "tax_class": "", 
      "tax_status": "taxable", 
      "virtual": false, 
      "visible": true, 
      "weight": "25"
    }
  ], 
  "virtual": false, 
  "weight": "25"
}

I haven't been able to find the reason why the first request fails to create the variations but the second request does, given they are the same request.

**Comment by prettyboymp** [comment]
I've been able to reproduce this on 2.6.13 and even on 2.7-beta.  Though on 2.7-beta, it wasn't even updating the product type.

**Comment by prettyboymp** [comment]
Steps to reproduce:

### Create the Simple Product
`POST /wp-json/wc/v1/products`
```
{
  "name": "Premium Quality",
  "type": "simple",
  "regular_price": "21.99",
  "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
  "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
  "categories": [
    {
      "id": 9
    },
    {
      "id": 14
    }
  ],
  "images": [
    {
      "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_front.jpg",
      "position": 0
    },
    {
      "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_back.jpg",
      "position": 1
    }
  ]
}
```

### Update the Product to a Variable Product with Variations
` PATCH /wp-json/wc/v1/products/{id}`
```
{
   "attributes":[
      {
         "name":"Size",
         "position":0,
         "visible":true,
         "variation":true,
         "options":[
            "S",
            "M",
            "L"
         ]
      }
   ],
   "type":"variable",
   "variations":[
      {
         "price":"12",
         "regular_price":"12",
         "attributes":[
            {
               "name":"size",
               "option":"L"
            }
         ]
      },
      {
         "price":"11",
         "regular_price":"11",
         "attributes":[
            {
               "name":"size",
               "option":"M"
            }
         ]
      },
      {
         "price":"10",
         "regular_price":"10",
         "attributes":[
            {
               "name":"size",
               "option":"S"
            }
         ]
      }
   ]
}
```

In 2.6.13, the product type updates, but none of the variations are added until a second PATCH request is sent.

**Comment by mikejolley** [comment]
@claudiosanches Need to update/get type before setting data?

**Comment by mikejolley** [comment]
See #13118
