### ISSUE TITLE
TGM issue with WC: Call to undefine function wc_get_screen_ids()

### ISSUE THREAD

**Issue by codehaiku** [woocommerce/woocommerce#12969]
On the latest version of WordPress and WooCommerce
PHP Version: 7.0.1
WP_DEBUG TRUE

<img width="1109" alt="screen shot 2017-01-25 at 5 34 29 am" src="https://cloud.githubusercontent.com/assets/4960876/22267918/8aef7836-e2c0-11e6-9e79-e7e9f063f259.png">

Thanks!

**Comment by codehaiku** [comment]
This is happening when I install and activate WooCommerce via [TGM](http://tgmpluginactivation.com/).

**Comment by shivapoudel** [comment]
Already solved by #11796
