### ISSUE TITLE
Translation issue on Cart page

### ISSUE THREAD

**Issue by Marcoevich** [woocommerce/woocommerce#12960]
## EXPLANATION OF THE ISSUE

In the shopping cart, many sentences cannot be translated. Not with po/mo files, not with plugins. This happens in WooCommerce versione 2.6.13 with Twenty-Seventeen theme and all other plugins disabled.

## STEPS TO REPRODUCE THE ISSUE

Install WooCommerce 2.6.13. Translate the strings below using the included translation files, or with the Loco Translate plugin. Translation status = 100% translated, yet the translations do not show up, even with Twenty Seventeen theme. Image of the issue:

![image](https://cloud.githubusercontent.com/assets/1243033/22250082/ec10b61e-e245-11e6-9c11-5497b71dc82d.png)

The untranslatable sentences I have found so far are:

CART:

- You have cancelled your payment. Please complete your order with a different payment method
- %product name% has been added to your cart.
- Continue shopping
- %product name% removed. Undo?

I'll add more to this issue, if I come across any.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

`
### WordPress Environment ###

Home URL: https://www.appkunda.nl
Site URL: https://www.appkunda.nl
WC Version: 2.6.13
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.14
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 10000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.13
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (1) ###

WooCommerce: door WooThemes – 2.6.13

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Winkelbasis: #68 - /shop/
Winkelmand: #70 - /cart/
Afrekenen: #72 - /checkout/
Mijn account: #74 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: AppKunda Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.0.6
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides:

`

**Comment by mikejolley** [comment]
Those strings are translatable. Perhaps your editor cannot handle `_n`? That does not make this a bug though.

https://github.com/woocommerce/woocommerce/blob/2.6.13/includes/wc-cart-functions.php#L109

And the translation on translate.wordpress.org: https://dl.dropboxusercontent.com/s/vpl71koefkci0x3/2017-01-24%20at%2014.22.png

And it working on my store with the translation file from .org:
https://dl.dropboxusercontent.com/s/034qlrx9l4901ea/2017-01-24%20at%2014.23.png
