### ISSUE TITLE
Product Permalinks broken when saving as a User with a different language set (WP 4.7+)

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce#12962]
## EXPLANATION OF THE ISSUE

When you have a user with a different language than the site default set in their user profile, and you save Permalinks AS that user, and you use the Default Product Permalinks, it breaks the links to the Product Permalinks.

## STEPS TO REPRODUCE THE ISSUE

1. My site is in Español
2. My main user account is in English
3. Currently my products have the default product base in Spanish `/producto/libro/`
4. When I view the page as an English user, the permalinks are now in English!  `product` instead of `producto`.
5. If I save these settings, the new Product Permalinks are now in English!
6. When I visit a product, I get a 404 because the products actually still live in their Spanish URLs, but I'm being taken to an English product base.

Tested on 2.6.13, also happens on 2.7 latest Master.

**Comment by tanthammar** [comment]
Thank you for your help today :)

**Comment by bullpillaren** [comment]
+1. 
We have a multilingual multisite with WooCommerce where every site has a different language. This bug feels very critical.

**Comment by mikejolley** [comment]
Can base on https://github.com/woocommerce/woocommerce/issues/12931

**Comment by mikejolley** [comment]
See #13107

**Comment by roopemerikukka** [comment]
Im experiencing this issue, @mikejolley can it be that these changes you made have been removed? I have site which language is set to Finnish but the admin user language is English and saving the permalinks saves them to the English ones while those should be in Finnish.
