### ISSUE TITLE
Cart does not display items when forwarding domain with cloaking in IE11 on Windows 8.1

### ISSUE THREAD

**Issue by VladimirP99** [woocommerce/woocommerce#12979]
## EXPLANATION OF THE ISSUE

Shopping cart is displayed as empty even though some items are present in the cart. This happens when navigating to a site through domain forwarding with cloaking in IE11  (v. 11.0.9600.18538) on Windows 8.1. There is no problem if Google Chrome is used or in IE11 (v. 11.576.14393.0) on Windows 10 (v. 10.0.14393.447). 

## STEPS TO REPRODUCE THE ISSUE

Navigate to http://schoolwristbands.com/ in IE11-> Click on Shop menu item -> Click on the Add to Cart link -> Click on the Cart menu item -> Cart page says your cart is currently empty -> Right click on the page ->Select Properties menu item-> Copy/paste http://advantagesx.com/wp/swbug/cart/ into the browser address bar and press enter -> Cart page shows 1 item
This is a brand new twenty seventeen installation with woocommerce with all default settings. I did not test other IE versions.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://advantagesx.com/wp/swbug
Site URL: http://advantagesx.com/wp/swbug
WC Version: 2.6.13
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.14
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.13
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (4) ###

Jetpack by WordPress.com: by Automattic – 4.5
SG CachePress: by SiteGround – 2.3.11
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce: by WooThemes – 2.6.13

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
This will be an issue with your Cookies/cookie domain. I know IE has a setting to block 3rd party cookies..

**Comment by VladimirP99** [comment]
You are right, allowing third party cookies solves the problem. Thank you very much.
