### ISSUE TITLE
Woocommerce Return Product Variations with hyphens

### ISSUE THREAD

**Issue by shehrozsheikh** [woocommerce/woocommerce#12975]
## EXPLANATION OF THE ISSUE

I'm using

$product->get_available_variations();

to get Product Variations in WooCommerce, but I'm getting results with hyphens, see this screenshot.

https://i.stack.imgur.com/L9zbE.png

How can I get results without hyphens?

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/12804
