### ISSUE TITLE
Rest API Refund endpoint not changing status of orders that are fully refunded

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce#12973]
When using the Rest API `POST /orders/{id}/refunds` on the latest master branch, i'm noticing that the order status is never changed to refunded when refunding the total orders amount.

I'm wondering if the [`$order->update_status()`](https://github.com/woocommerce/woocommerce/blob/3a104df5bd15c5306c13633b2ac1af05fa508ab0/includes/class-wc-ajax.php#L1427) used for processing refunds on the admin page was forgotten about in [`WC_REST_Order_Refunds_Controller::create_item()`](https://github.com/woocommerce/woocommerce/blob/3a104df5bd15c5306c13633b2ac1af05fa508ab0/includes/api/class-wc-rest-order-refunds-controller.php#L223)

Steps i'm using to replicate.
1. Pull orders using `GET orders/`
1. For each `$order` make a new `POST /orders/{$order->id}/refunds?amount={$order->total}` request
1. check the order has been fully refunded but the status is still completed or processing.

I'm on the latest WC 2.7 master branch with just stripe gateway installed

**Comment by mattallan** [comment]
I'm happy to push up a PR if this behaviour isn't intended

**Comment by mikejolley** [comment]
Looks like it was forgotten, but I wonder if this logic should move to the refund CRUD so it's ran regardless of where the refund comes from.

**Comment by mikejolley** [comment]
See #13117
