### ISSUE TITLE
Video SRTs project link in CONTRIBUTING.md leads to a 404

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce#12978]
In [contributing.md](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md), the **Video SRTs project** link leads to a 404.

![](http://cld.wthms.co/LzO8/4gKl1IHQ+)

**Comment by justinshreve** [comment]
Fixed by https://github.com/woocommerce/woocommerce/pull/12984.
