### ISSUE TITLE
Rest API. How to remove items from the order

### ISSUE THREAD

**Issue by vguns** [woocommerce/woocommerce#12974]
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by vguns** [comment]
Update an Order, 'line_items' add items to order and how to remove the item or reduce the quantity

**Comment by claudiosanches** [comment]
Submit a PUT request using quantity as `0`.

**Comment by michael-lynch** [comment]
I tried adding a product with a quantity of `0` and got:

`Error: Product quantity must be a positive float.`
