### ISSUE TITLE
Typo in coupon tooltip text on Usage limit per user

### ISSUE THREAD

**Issue by joelwills** [woocommerce/woocommerce#12986]
https://github.com/woocommerce/woocommerce/blob/022d4fdac4b02cde6e26faceddf0b7d29e74b383/includes/admin/meta-boxes/class-wc-meta-box-coupon-data.php#L231

Individual is spelled incorrectly:

`'description'       => __( 'How many times this coupon can be used by an invidual user. Uses billing email for guests, and user ID for logged in users.',`

Should be

`'description'       => __( 'How many times this coupon can be used by an individual user. Uses billing email for guests, and user ID for logged in users.',`

**Comment by jaydeeprami** [comment]
@mikejolley , I have resolved an issue.
My pull request is: 
https://github.com/woocommerce/woocommerce/pull/12964

Thanks,

**Comment by mikejolley** [comment]
@jaydeeprami These should be separate pull requests, not one PR to do multiple different things.

**Comment by jaydeeprami** [comment]
Thanks @mikejolley, I will send separate PR.

**Comment by jaydeeprami** [comment]
@mikejolley , I have sent separate PR.

https://github.com/woocommerce/woocommerce/pull/12993

Thank you
