### ISSUE TITLE
wc_update_product_stock bug in 2.6

### ISSUE THREAD

**Issue by Nils-Fredrik** [woocommerce/woocommerce#12989]
Hi,

Not sure how to do the pull request for this thing since its in the 2.6 branch: https://github.com/Nils-Fredrik/woocommerce/commit/f1bdf0dc528b6f89a55b4af60e90ff3783924607 

Not tested on 2.7. 

Shall I just proceed and do a regular pull request?

**Comment by mikejolley** [comment]
Apply to master if the code still exists and we'll cherry pick.

**Comment by Nils-Fredrik** [comment]
@mikejolley will there be any 2.6 releases?

**Comment by mikejolley** [comment]
Yes next week.

**Comment by henstercoza** [comment]
Hi guys sorry to bug you ,, is this related to the same issue i'm having ?

https://wordpress.org/support/topic/stock-levels-not-deducting/#post-8717165
