### ISSUE TITLE
Order Received Endpoint in Arabic is not working correctly

### ISSUE THREAD

**Issue by andreas-pa** [woocommerce/woocommerce#12988]
## THE PROBLEM

When the endpoint  "order-received" is changed to  "تم استقبال الطلب" in Arabic - after checkout you are redirected to a notice page instead of the correct endpoint. The order is being created.

![image](https://cloud.githubusercontent.com/assets/16132937/22331116/5facf1ea-e3d2-11e6-82c1-2f8d08339394.png)

## STEPS TO REPRODUCE THE ISSUE

1. Install WP in Arabic language
2. Install WC 
3. Translate order-received endpoint to  "تم استقبال الطلب"
4. Add a product and translate it
5. Purchase product in Arabic
6. Notice error from the screenshot

## TESTED VERSION

- **WP Latest stable**
- **WC Latest stable**

**Comment by mikejolley** [comment]
Works with just "الطلب". Take the spaces out - that is invalid in a URL. Pretty sure thats what is causing it.
