### ISSUE TITLE
Remove product images via API

### ISSUE THREAD

**Issue by spopov** [woocommerce/woocommerce#12985]
Remove product images via API

I have sent images = null and expected images is removed, but I've got an error.

## STEPS TO REPRODUCE THE ISSUE

Send images = null via API

product images parameter is Array type
when it goes through class-wp-rest-request it converts to array with one element 0 by this method:

rest.api:1117
/**
 * Sanitize a value based on a schema.
 *
 * @param mixed $value The value to sanitize.
 * @param array $args  Schema array to use for sanitization.
 * @return true|WP_Error
 */
function rest_sanitize_value_from_schema( $value, $args ) {

and I have got array with one 0 element and when it tries to save images there is checking:
protected function save_product_images( $product_id, $images ) {
		if ( is_array( $images ) ) {
then I have exception that I send wrong id = 0

P.S. Value anyway converts to array

Thanks

----------------------------------

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: 
Site URL: 
WC Version: 2.6.13
Log Directory Writable: ✔
WP Version: 4.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.13
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.13
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (3) ###

SSL Insecure Content Fixer: by WebAware – 2.2.2
WooCommerce: by WooThemes – 2.6.13
WordPress HTTPS: by Mike Ems – 3.3.6

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

**Comment by justinshreve** [comment]
Hi @spopov. I am able to delete images by just passing an empty value (not 0). There is an else statement after `if ( is_array( $images ) ) {` that will hit and delete the image from the product for you.

**Comment by vinigarcia87** [comment]
I have sent images = null and expected images to be removed, but I've got an error.
I have sent images = empty array and expected images to be removed, but no image is removed.
I have remove a image from images list and again, nothing happens.
Anyone now why this behaviour?
