### ISSUE TITLE
Error with subtotal sum

### ISSUE THREAD

**Issue by G3R4RD9** [woocommerce/woocommerce#12987]
## EXPLANATION OF THE ISSUE

When i apply for example, 10% off on my products, the result some times is for example 6.955, woocomerce round up my product price to 6.96 but in the checkout page the subtotal price is the sum of the products with 3 decimals. Ergo, if i have two products:

Product 1  with discount and 3 decimals: 6.255€
Product 2 with discount and 3 decimals: 19.755€

Woocommerce round up  my 2 products to 6.26€ and 19.76€ but in the checkout page, the subtotal price is equal to the sum of the 2 products with 3 decimals, 24.01€ but if i sum 2 rounded prices should be 24.02€.

## STEPS TO REPRODUCE THE ISSUE

1.- Use a plugin for calculate a percentatge of product or put manually the normally price with discount. Like 19.755€ and 6.255€.

2.- Sum the prices with 3 decimals and sum the prices with rounded prices and check de difference in the subtotal field in the checkout page

## SYSTEM STATUS REPORT

URL ﻿de la página de inicio:		https://minutusshop.com
URL del sitio:		https://minutusshop.com
Versión de WC:		2.6.13
Directorio de registros con permiso de escritura:		 /var/www/vhosts/minutusshop.com/httpdocs/wp-content/uploads/wc-logs/
Versión de WP:		4.7.1
WordPress Multisitio:		–
Límite de memoria WP:		256 MB
WP Debug Mode:		–
WP Cron:		
Idioma:		es_ES
Entorno del servidor
Información del servidor:		Apache
Versión de PHP:		 5.5.9-1ubuntu4.16 - Recomendamos como mínimo la versión PHP 5.6. Ver: Cómo actualizar tu versión de PHP
PHP Post Max Size:		8 MB
PHP Time Limit:		60
PHP Max Input Vars:		1000
Versión cURL:		7.35.0, OpenSSL/1.0.1f
SUHOSIN Instalado:		–
Versión de MySQL:		 5.5.49 - Recomendamos como versión mínima de MySQL la 5.6. Ver: Requisitos de WordPress
Tamaño máximo de subida:		8 MB
Por defecto la zona horaria es GMT:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte String:		
Publicación remota:		
Obtención remota:		
Base de datos
Versión de la base de datos de WC:		2.6.13
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
Base de datos GeoIP de MaxMind:		 /var/www/vhosts/minutusshop.com/httpdocs/wp-content/uploads/GeoIP.dat
Plugins activos (30)
Akismet	 	por Automattic – 3.2
All 404 Redirect to Homepage	 	por Fakhri Alsadi – 1.7
Asesor de Cookies	 	por Carlos Doral Pérez – 0.21
Check and Enable GZIP compression	 	por Richard's Toolbox – 1.1.6
Contact Form 7	 	por Takayuki Miyoshi – 4.6
Desactivar Comentarios	 	por Samir Shah – 1.6
JanStudio Addons	 	por JanStudio – 1.0.3
WPBakery Visual Composer	 	por Michael M - WPBakery.com – 5.0.1
Loco Translate	 	por Tim Whitlock – 2.0.11
MailChimp para WordPress	 	por ibericode – 4.0.12
Meta Slider	 	por Matcha Labs – 3.4.1
Open Swatch - Woocommerce Attributes Swatch	 	por janstudio.net@gmail.com – 2.0.2
PixelYourSite	 	por PixelYourSite – 5.0.0
Regenerate Thumbnails	 	por Alex Mills (Viper007Bond) – 2.2.6
Shortcoder	 	por Aakash Chakravarthy – 3.4.1
Stripe WooCommerce Addon	 	por Syed Nazrul Hassan – 1.0.8
WC Gift Packaging	 	por Johannes Grandy – 1.0
Woocommerce All Discounts	 	por ORION – 0.8
WooCommerce PDF Invoices & Packing Slips	 	por Ewout Fernhout – 1.5.38
WP All Import - WooCommerce Add-On	 	por Soflyy – 1.3.1
WooCommerce	 	por WooThemes – 2.6.13
Yoast SEO	 	por Equipo Yoast – 4.1
WP All Import	 	por Soflyy – 3.4.0
WP Htaccess Editor	 	por Lukenzi – 1.3.0
WP Super Cache	 	por Automattic – 1.4.8
WPide	 	por Simon @ WPsites – 2.4.0
Custom Product Tabs para WooCommerce	 	por YIKES Inc – 1.5.2
YITH WooCommerce Ajax Product Filter	 	por YITHEMES – 3.1.2
YITH WooCommerce Popup	 	por YITHEMES – 1.0.4
YITH WooCommerce Wishlist	 	por YITHEMES – 2.0.16
Ajustes
Forzar SSL:		
Moneda		EUR (€)
Ubicación de la moneda		right_space
Separador de miles		,
Separador decimal		.
Número de decimales		2
API
API activada:		
WC Páginas
Base de la tienda:		#4 - /tienda/
Carrito:		#5 - /carrito/
Finalizar compra:		#6 - /checkout/
Mi cuenta:		#7 - /mi-cuenta/
Taxonomías
Tipos de productos:	 	external (external), grouped (grouped), simple (simple), variable (variable)
Tema
Nombre:		
Versión:		– 0 está disponible
URL del autor:		
Tema hijo:		
Nombre del tema padre:		
Versión del tema padre:		– 0 está disponible
URL del autor del tema padre:		
Soporte WooCommerce:		
Plantillas
Plantilla de archivo:	 	Tu tema tiene un archivo woocommerce.php, no podrás sobreescribir la plantilla personalizada woocommerce/archive-product.php ya que woocommerce.php tiene prioridad sobre archive-product.php. Esto es intencionado para prevenir problemas de visualización.
Anulaciones (WooCommerce):	 	gecko-child/woocommerce/emails/admin-new-order.php

**Comment by mikejolley** [comment]
We don't display prices to 3dp, so you'll see a 'rounded up' value per line, but the subtotal itself takes the real, unrounded, version into account for it's sums and for taxes. I think thats correct - 26.01 is the correct subtotal in the case you're presenting (hard to work out without real examples btw).
