### ISSUE TITLE
[2.7] Are there actions and filters triggered when meta is set or updated?

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#13007]
Quite often, I find myself having to intercept the meta value for specific products or orders, and do something with it as it's updated. For example, if an order total changes in the meta, I might need to use the new value to set some other meta.

With current `update_post_meta()` approach, even if there aren't dedicated filters for a specific meta, it's possible, in extreme cases, to intercept a meta value with a low level filter for the `update_post_metadata` hook, and save custom meta in one go. Is there an equivalent hook in WC 2.7 to intercept changes in meta values for a given entity, that will work when the `update_post_meta()` (and similar) will no longer be used?

Example
--
~~~
$order = wg_get_order(123);
$order->set_total(1000); // How can we intercept this change?
~~~

**Comment by mikejolley** [comment]
@daigo75 So the set_total doesn't need intercepting in this way because this is a set, not a save. When save is called you have a few options.

Before the object gets updated/created, data objects fire a hook which passes the object https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L179 This passes by reference so you can call extra gets/sets there.

After saving to the database, we fire an action listing the names of changed props https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/abstract-wc-order-data-store-cpt.php#L233 This lets you fire more logic conditionally based on what was updated.

The main mindset shift is that you need to fire your logic on save, not set. Set is not persistent unless saved.

Hope that makes sense.

**Comment by daigo75** [comment]
Yes, my intention is precisely to fire custom code on save (I assumed that "set" would be the equivalent of "save"). An event that tells what was changed is coming in handy.

Based on your description, do you reckon that this work as I would expect?
~~~
add_action('woocommerce_order_object_updated_props', function($order, $updated_props) {
  // Some properties to process (example, the names may not be accurate)
  $props_to_process = array(
    'total',
    'subtotal',
    'shipping_total'
  );
  
  foreach($updated_props as $prop_name) {
    // Process the properties that should be "intercepted", if they changed
    if(in_array($prop_name, $props_to_process)) {
      // Get the value of the property that was just saved
      $prop_value = $order->{"get_$prop"}();
      
      // Process the property, using the latest value
      my_custom_processing($prop_name, $prop_value);
    }
  }
}, 10, 2);
~~~

**Comment by mikejolley** [comment]
Yes that looks about right.

**Comment by daigo75** [comment]
Thanks, it's great news. This raises one question that might be simpler to answer: how would you suggest to handle the update of custom properties? For example, in my case I need to update order meta X when meta Y changes (where X is a value that depends on on Y). Every time X is set, then Y is updated. 

The `woocommerce_order_object_updated_props` hook will allow to find out when Y, and other properties that require action, change. Since this happens **after** the properties have been saved to the database, what would be the recommended approach to save the custom ones?

This would work, but it would still depend on the `update_post_meta()` call:

~~~
add_action('woocommerce_order_object_updated_props', function($order, $updated_props) {
  // Some properties to process (example, the names may not be accurate)
  $props_to_process = array(
    'total',
    'subtotal',
    'shipping_total'
  );
  
  foreach($updated_props as $prop_name) {
    // Process the properties that should be "intercepted", if they changed
    if(in_array($prop_name, $props_to_process)) {
      // Get the value of the property that was just saved
      $prop_value = $order->{"get_$prop_name"}();

      // Get my custom property value
      $custom_prop_value = my_custom_processing($prop_name, $prop_value);
     
      // Save the property value
      update_post_meta($order->get_id(), 'custom_' . $prop_name, $custom_prop_value);
    }
  }
}, 10, 2);
~~~

If there is a more elegant way to do it, using the new methods exposed by the classes, I will be happy to do it. :smile:
