### ISSUE TITLE
Product Attribute data structure meta-issue

### ISSUE THREAD

**Issue by nimmolo** [woocommerce/woocommerce#13000]
@claudiosanches @mikejolley Does it make sense going forward, that product attributes are separate taxonomies? 

maybe it's too late to fix, i'm sure it comes from the days before wordpress term meta. but it seems bonkers to have attributes be a hacky extensible list of taxonomies, where the only way to find them is to query for string "pa_" in the name, when they could be moved to being **terms** classed under the same taxonomy "product-att" and have their data more easily found and formatted as **term meta**.

i.e., better able to take advantage of core functions and hooks, core REST API functions, etc

**Comment by mikejolley** [comment]
Keeping all terms in one taxonomy is worse. How would you distinguish them? How would you query one set e.g color or size?

**Comment by nimmolo** [comment]
taxonomy->product_att
term->color
term_meta->name, description, instructions, color options etc

**Comment by nimmolo** [comment]
@mikejolley like this?

taxonomy->product_att
term->color_set_1
term_meta->name, description, instructions, color_set_1 options etc

taxonomy->product_att
term->color_set_2
term_meta->name, description, instructions, color_set_2 options etc

taxonomy->product_att
term->size
term_meta->name, description, instructions, size options etc

At least, this is how i use attributes

**Comment by mikejolley** [comment]
This would make it impossible to do things like filters on layered nav I think. Meta doesn't scale - we are learning this the hard way :)

**Comment by nimmolo** [comment]
ok got it. yeah @biont had mentioned to me that term meta was rough on the server, didn't know it was that big an issue
