### ISSUE TITLE
Related Products CSS

### ISSUE THREAD

**Issue by psychoize** [woocommerce/woocommerce#13006]
I am using the latest Woocommerce and Divi builder. So far I made a lot of progress, but there is something that really bugs me out, about the white hover overlay on Related Products and when I load a category of products. I was able to remove the hovers over the Featured Products and Shop modul. I know I can achieve this with CSS but not sure where exactly should I look for it...

**Comment by carasmo** [comment]
Please ask in the Divi support. This is for issues and feature requests for WooCommerce core.

**Comment by psychoize** [comment]
It has nothing to do with Divi, because its an hover overlay that is added by Woocommerce

**Comment by mikejolley** [comment]
> It has nothing to do with Divi, because its an hover overlay that is added by Woocommerce

Styling can come from DIVI, WC or any other plugin you have installed. It doesn't matter who adds the feature..

I suggest you learn how to use the browser's DOM inspector (right click page > inspect in chrome). This shows you all styles applied to an element and where they are from so you can apply extra CSS rules to correct it. That should help you solve your customisation problem.
