### ISSUE TITLE
wc_notice_nonce breaks every admin page

### ISSUE THREAD

**Issue by Firfi** [woocommerce/woocommerce#13004]
## EXPLANATION OF THE ISSUE

When wc_notice_nonce is present in the query, after some time admin pages become inaccessible with message 'Action failed. Please refresh the page and retry.'

## STEPS TO REPRODUCE THE ISSUE

1) Woo Commerce notice should be present on the admin page (my was the notice about plugin license soon expiration)

2) wc_notice_nonce parameter should be present in the query. With the notice it would be. Example: _wc_notice_nonce=a6d2f447bc

3) wait one day

4) the page becomes unaccessible on refresh (due to old nonce I suppose)

**Comment by claudiosanches** [comment]
Every page on WordPress that have a nonce will become unaccessible after one day.

**Comment by claudiosanches** [comment]
And it should be become unaccessible after one day for security reasons, mostly to avoid CSRF attacks.

**Comment by Firfi** [comment]
It should indeed, but there's two peculiarities in current implementation:

1) It will block any admin page, even non-related to woocommerce

2) If I remove the nonce param from the url, the pages simply getting accessible. Makes me think that CSRF attacker could do the same.
