### ISSUE TITLE
Setup Wizard does not use detected location to set currency

### ISSUE THREAD

**Issue by damiencarbery** [woocommerce/woocommerce#13018]
The Store Locale Setup page of the setup wizard detects the user's (or is it server's) IP address and this is used to set the store location.

Unfortunately this info is not used to set the store currency, currency position, thousands separator, decimal separator, number of decimals, weight unit or dimensions unit. All of these are set to hard coded defaults (for UK it seems).

Can you please add an array of country => currency (and the other items) to aid in the setup of the store locale?

(I might work on this - I am adding this issue to attach a PR to).

**Comment by mikejolley** [comment]
This already happens if the information is in https://github.com/woocommerce/woocommerce/blob/master/i18n/locale-info.php. if it's missing for your locale, just add yours there :)
