### ISSUE TITLE
Error with virtual/downloadable products

### ISSUE THREAD

**Issue by yarivkohn** [woocommerce/woocommerce#13017]
## EXPLANATION OF THE ISSUE

I have virtual product in my shop.
After purchase of these products I expect the status to be "completed", However status is "processing".
I'm using WC v2.6.13, with new Payment method that I'm currently developing. 
If you take a look at file "abstruct-wc-order.php" line 2478 you will see the following line of code:

$virtual_downloadable_item = $_product->is_downloadable() **&&** $_product->is_virtual();

I think it was meant to be:
$virtual_downloadable_item = $_product->is_downloadable() **||** $_product->is_virtual();

## STEPS TO REPRODUCE THE ISSUE

Create a virtual product or downloadable product.
Place an order with the created product.
Status will be "processing" 

According to the above code only if the product is both virtual and downloadable it will get status "completed".
I assume product can't be both :)

**Comment by bekarice** [comment]
@yarivkohn @emgk this is the intended behavior. A product can be both virtual **and** downloadable.

A **downloadable** product could also require shipping; the download could be attached as a bonus, such as offering a course that would require one to mail an introduction packet but also offer downloadable content in the account section. Therefore, a product that is solely downloadable should not auto complete the order.

A **virtual** product can also have steps in between accepting payment and completing the order. For example, if selling a service, this would be a virtual product, but merchants may not want to complete the order until the service has been rendered or scheduled.

Only virtual + downloadable products can make a safe assumption that the majority of people selling this product will have orders that require no other action, as marking a product as both indicates that likely the download is the entirety of the purchase.

The current set up errs on being more permissive for workflows that don't sell solely downloadable goods. There are several tutorials showing how to autocomplete a virtual order ([like this one](http://imdev.in/woocommerce-mark-virtual-orders-as-complete/)) if that's what your workflow requires, or you could [use a plugin instead](https://woocommerce.com/products/woocommerce-order-status-control/) if you don't want to maintain / update a snippet.

**Comment by BurlesonBrad** [comment]
{reading, reading, reading, thinks "Man I should suggest a plugin for @yarivkohn to use that would really take care of this for him, reading, reading, almost done, ......smirks}

> or you could [use a plugin instead](https://woocommerce.com/products/woocommerce-order-status-control/) if you don't want to maintain / update a snippet.

Well played Sensei @bekarice 😜

**Comment by yarivkohn** [comment]
Hey,
Thank you for the quick and detailed response.

**Comment by yarivkohn** [comment]
Thanks :)
