### ISSUE TITLE
[2.7] get_shipping_class_id() is empty on a variation managed by parent

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#13015]
In 2.6, calling get_shipping_class_id() on a product variation returned the shipping class id of the variation if set and if not the one of the parent. In admin, the shipping class of the variation can be saved as "same as parent" and is then empty.

In 2.7, calling the same function on a product variation doesn't do the check of the parent, if the variation was set as "same as parent", and return 0. Is it now my duty to check when calling get_shipping_class_id() on a product if I'm dealing with a variation which can be managed by the parent or should rather the function get_shipping_class_id() been adapted to do the check on its own as before?

I'm fine with both way, but a quick clarification would be really cool so I know if I have to screen my code for the get_shipping_class_id() with the new behavior or if I can wait for an update.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/13104
