### ISSUE TITLE
I want to insert item meta in in order through rest API in WooCommerce

### ISSUE THREAD

**Issue by mohammadfurqanofficial** [woocommerce/woocommerce#13024]
I created one text field through WC Field Factory with the name of "Camper Name"

Showing in this product

http://campstore.myworkdemo.com/product/woo-album-2/

Now the problem is when I'm filling this field from frontend and placing order this field show in Woocommerce Order API when I'm retriving data but when I'm trying to insert meta through creating Order API then not going in order and when I'm retreiving order show "meta"[] empty. can anyone help to resolve this issue..

thanks in advance

**Comment by iamjawadshah** [comment]
I checked this but it is not working #mohammadfurqanofficial here Please reply

**Comment by WPprodigy** [comment]
Hi @mohammadfurqanofficial,

I'm sorry, but this is not the place to ask for support. Github is for bug reports in WooCommerce core, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

You can use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or perhaps use one of the already existing plugins that can help you do this: https://woocommerce.com/products/product-add-ons/
