### ISSUE TITLE
Hide Out Of Stock Products on AJAX

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#13023]
Hello,

I’m a theme author. Recently, my customer reports a bug which relates to your plugin. If he goes to **WooCommerce > Settings > Products > Inventory** and check the **Out Of Stock Visibility** option, our product shortcodes which use **AJAX** will not work correctly. I know you have checked this option when loading product. But it does not work with AJAX ( is_admin() == true ). Nowadays, a lot of themes, plugins use AJAX to load product. Please check this option when using AJAX.

Thank you!

**Comment by mikejolley** [comment]
Are you passing support requests to us without confirming or testing things for yourself first? At least confirm the issue first...especially if it's a combination of WC and your own custom code (which loading products via AJAX is). 

Look at the logs, if there is an error, add it to your issue report. 

Also note "Nowadays, a lot of themes, plugins use AJAX to load product" - you're the only one to report an issue so if thats the case it could very likely be due to your code no?

Feel free to reply when you have more details. I don't have your theme to test.

**Comment by stormit** [comment]
Hi Mike,

I have made an example for you. I use the **Twenty Seventeen** theme and only activate your WooCommerce plugin.

Below is my PHP code. I create a function which loads products by using ajax

`add_action('wp_ajax_load_product_by_using_ajax', 'load_product_by_using_ajax');
function load_product_by_using_ajax(){
	$args = array(
		'post_type'				=> 'product'
		,'post_status' 			=> 'publish'
		,'ignore_sticky_posts'	=> 1
		,'posts_per_page' 		=> 4
		,'orderby' 				=> 'date'
		,'order' 				=> 'desc'
		,'meta_query' => array(
			array(
				'key' => '_visibility'
				,'value' => array('catalog', 'visible')
				,'compare' => 'IN'
			)
		)
	);
	
	ob_start();
	
	$products = new WP_Query( $args );
	if( $products->have_posts() ){
		woocommerce_product_loop_start();

		while( $products->have_posts() ){
			$products->the_post();
			wc_get_template_part( 'content', 'product' );
		}

		woocommerce_product_loop_end();
	}
	
	wp_reset_postdata();
	
	wp_die( ob_get_clean() );
}`

I create an empty page and add the html below

`<button class="button" id="load-product-button">Load Product</button>
<div id="product-container" class="woocommerce columns-4"></div>`

Then, I add the js code which will load product when I click on the button

`jQuery(document).ready(function($){
	$('#load-product-button').on('click', function(){
		$.ajax({
			type : 'POST',
			url : wc_add_to_cart_params.ajax_url,
			data : {action: 'load_product_by_using_ajax'},
			success: function(response) {
				$('#product-container').html( response );
			}
		});
	});
});`

We have 19 products [http://prnt.sc/e2yecw](url)

It works correctly [http://prnt.sc/e2yeq0](url) if first 4 products are in stock.

But when I set one of first 4 products to Out of stock and enable the **Out Of Stock Visibility** option in **WooCommerce > Settings > Products > Inventory**, there are only 3 products which are loaded [http://prnt.sc/e2yf8n](url).

Best regards,

**Comment by mikejolley** [comment]
This is because you're doing the WP_QUERY yourself and doing your own version of the meta_query. The out of stock products are therefore still returned, but filtered out on display. Your query should handle excluding them so they are not returned by the WP_Query.
