### ISSUE TITLE
how to get a full stock/inventory list with SKU?

### ISSUE THREAD

**Issue by raykai** [woocommerce/woocommerce#13022]
## EXPLANATION OF THE ISSUE

Looking for a way to get a full list of woocommerce stock/inventory a must have when running business.
would be nice having this in the core 

**Some useful info it could give:**
It could output a full list of the products by category with the products  SKU, Stock levels, and Price, download as a csv would be a good plus.

it would be useful to compare the amount of real stock on hand.

**Comment by mikejolley** [comment]
There are extensions for this - bulk stock manager for instance.

You can also see a report in admin.php?page=wc-reports&tab=stock

Or you can write your own custom one :)
