### ISSUE TITLE
Can't Reset Password if setup is skipped when WooCommerce is installed 

### ISSUE THREAD

**Issue by BandonRandon** [woocommerce/woocommerce#13027]
## EXPLANATION OF THE ISSUE
When WooCommerce is installed the Lost Password endpoint is set to `lost-password` under Settings > Account.

![screenshot_30-01-2017-18 37 46](https://cloud.githubusercontent.com/assets/150348/22450891/d4eaec10-e71e-11e6-9f5a-f6cd408e1319.png)

When the setup wizard is skipped the My Account page which this endpoint relies on never gets created. This leads to a 404 when trying to reset the password after logging out. 

If you click the Reset Password link you'll be taken to `example.com/lost-password` after running the setup creating the My Account page the URL will be `example.com/my-account/lost-password`

## STEPS TO REPRODUCE THE ISSUE
1. Install WooCommerce for the first time. 
2. Skip the Setup Wizard then log out. 
3. Visit example.com/wp-login.com and click "Lost Password?"
4. Note the 404 page and http://example.com/lost-password URL.
![screenshot_30-01-2017-19 10 25](https://cloud.githubusercontent.com/assets/150348/22451098/718c55d0-e720-11e6-8ccb-5f94970ef3f5.png)
5. Log back in
6. Run setup, creating the My Account page
7. Visit example.com/wp-login.com and click "Lost Password?"
8. Note the reset password page and http://example.com/my-account/lost-password

A few options I can think of to resolve this are:
- Since #12526 was fixed in 2.6.9+ not setting a `lost-password` endpoint on install but setting it when the wizard is run. 
- Check for the `my-account` page prior to overwriting the lost password URL. 
- Create the My-Account page on Install not at Setup.

**Comment by WPprodigy** [comment]
WC defaults to get_home_url() in wc_get_page_permalink() if the account page setting is empty: https://github.com/woocommerce/woocommerce/blob/b2b42600cdf76cc44d336ade796fbdea8ea1a356/includes/wc-page-functions.php#L72

So `false !== $wc_password_reset_url` doesn't fail here: https://github.com/woocommerce/woocommerce/blob/07932b443284edaefaecada9c2519a15a7ea5314/includes/wc-account-functions.php#L28
