### ISSUE TITLE
Extra data for product object can't be mapped to a specific post meta key

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#13034]
The [`class-wc-product-data-store-cpt.php`](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L469) provides for the automatic saving of product properties defined as `$extra_data`. However, the data store class automatically maps the keys to the post meta key `_$key` when saving, which isn't always convenient for non-core product types and doesn't allow for the same flexibility of the `$meta_key_to_props` array. Because it can't be mapped to an existing DB key, it saves an extra/unused meta key in the DB via the default case of the [switch statement](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L435). 

It looks like the extra keys are meant to be handled later [here](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L462-L474) but, again, since the meta keys aren't mapped correctly in the `$meta_key_to_props` parameter they are skipped because the extra keys don't show up in  `get_props_to_update()` result.

I'm not sure yet what I would propose as a solution.

**Comment by mikejolley** [comment]
There is no extra mapping for 'extra data'. If you want to take advantage of this they need to be the same, if not you need to handle the save/get yourself in your data-store. Ill post my bookings example next week where I had to do this.

cc @justinshreve for your ref. I think we talked about this before.
