### ISSUE TITLE
[2.7] WC_Order order_date replacement get_date_created unexpectedly returns integer

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#13039]
## EXPLANATION OF THE ISSUE

get_date_created returns an integer, but the direct class member it replaces (order_date) used to return a YYYY-MM-DD HH:MM:SS formatted string. This breaks extensions that expected the direct accessor to continue to be a YYYY-MM-DD string.

Ref https://github.com/woocommerce/woocommerce/blob/429b7534bbf2b680e40d77ea3e126d9dceb0291e/includes/abstracts/abstract-wc-legacy-order.php#L411

## STEPS TO REPRODUCE THE ISSUE

Get order_date directly under 2.7 and notice that it is an integer, not the expected formatted string.

## SYSTEM STATUS REPORT

N/A

**Comment by bor0** [comment]
Related comment: https://github.com/woocommerce/woocommerce/pull/13032#issuecomment-276413640

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/13042

**Comment by bor0** [comment]
@mikejolley do we want to re-add `strtotime` to https://github.com/woocommerce/woocommerce/pull/13032#issuecomment-276413640?

**Comment by mikejolley** [comment]
@bor0 No, CRUD still returns a timestamp as it should. Direct access (for backwards compatibility) returns the string. We should always use timestamps in the crud system.
