### ISSUE TITLE
Ghost Variations in case if posting product with variations that have the same SKU  via API

### ISSUE THREAD

**Issue by spopov** [woocommerce/woocommerce#13033]
## EXPLANATION OF THE ISSUE

Ghost Variations in case if posting product with variations that have the same SKU via API

## STEPS TO REPRODUCE THE ISSUE

- use API
- try to create a product with three variations last two have the same sku
- wooCommerce return an error "SKU should be unique"
- there no product created
- there are records in wp_post for variations linked to parent post that doesn't exist
- there are records in _sku for variations
- after I can't create any product with sku that I have tried create before

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://dev.woocommerce.fits.cloud
Site URL: https://dev.woocommerce.fits.cloud
WC Version: 2.6.13
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.31 (Amazon)
PHP Version: 7.0.11
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.1
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.13
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (4) ###

HTTP / HTTPS Remover: by Marius Bolik (CONDACORE) – 1.3.1
SSL Insecure Content Fixer: by WebAware – 2.2.2
WooCommerce PayPal Powered by Braintree Gateway: by WooThemes – 1.2.7
WooCommerce: by WooThemes – 2.6.13

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
This should be resolved in 2.7 since the CRUD system validates the SKU before anything is written to the database.

ref @claudiosanches
