### ISSUE TITLE
Feature: Allow global attribute labels to be edited at the product level

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#13038]
![](http://cld.wthms.co/rXXF/5AKm6q6b+)

## Problem: 
Had a use case where the shop had many color terms for a global attribute, and they were all set and linked to swatches. Each product that used this attribute needed to have a slightly different label though that is shown to the customer. Such as "Border Color", or "Monogram Color", or "Heart Color".

It isn't possible to "duplicate" attributes at the moment, so as is this would require a lot of work. And upkeep would be nearly impossible when colors needed to be changed, as you would need to do it across multiple attributes.

The solution was to use the `woocommerce_attribute_label` filter to conditionally change the label on the frontend.

## Solution:
We could make the label field editable at the product level, even for global attributes. If left blank or unedited, it will fallback to the global attribute's default label. This could help simplify a few attribute/variation use cases that I can think of.

Another possible solution would be to make attributes easily duplicated, though I don't see why we couldn't do both :)

**Comment by mikejolley** [comment]
This comes into the larger variation redesign we're speccing out this week and in s9n. We're on this - we don't need a dedicated issue :-)
