### ISSUE TITLE
Hide Out Of Stock Products on AJAX

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#13049]
Hi Mike,

I have made an example for you. I use the **Twenty Seventeen** theme and only activate your WooCommerce plugin.

Below is my PHP code. I create a function which loads products by using ajax

```php
add_action('wp_ajax_load_product_by_using_ajax', 'load_product_by_using_ajax');
function load_product_by_using_ajax(){
	$args = array(
		'post_type'				=> 'product'
		,'post_status' 			=> 'publish'
		,'ignore_sticky_posts'	=> 1
		,'posts_per_page' 		=> 4
		,'orderby' 				=> 'date'
		,'order' 				=> 'desc'
		,'meta_query' => array(
			array(
				'key' => '_visibility'
				,'value' => array('catalog', 'visible')
				,'compare' => 'IN'
			)
		)
	);

	ob_start();
	
	$products = new WP_Query( $args );
	if( $products->have_posts() ){
		woocommerce_product_loop_start();

		while( $products->have_posts() ){
			$products->the_post();
			wc_get_template_part( 'content', 'product' );
		}

		woocommerce_product_loop_end();
	}
	
	wp_reset_postdata();
	
	wp_die( ob_get_clean() );
}
```

I create an empty page and add the html below
```html
<button class="button" id="load-product-button">Load Product</button>
<div id="product-container" class="woocommerce columns-4"></div>
```

Then, I add the js code which will load product when I click on the button
```javascript
jQuery(document).ready(function($){
	$('#load-product-button').on('click', function(){
		$.ajax({
			type : 'POST',
			url : wc_add_to_cart_params.ajax_url,
			data : {action: 'load_product_by_using_ajax'},
			success: function(response) {
				$('#product-container').html( response );
			}
		});
	});
});
```

We have 19 products [http://prnt.sc/e2yecw](http://prnt.sc/e2yecw)

It works correctly [http://prnt.sc/e2yeq0](http://prnt.sc/e2yeq0) if first 4 products are in stock.

But when I set one of first 4 products to Out of stock and enable the **Out Of Stock Visibility** option in **WooCommerce > Settings > Products > Inventory**, there are only 3 products which are loaded [http://prnt.sc/e2yf8n](http://prnt.sc/e2yf8n).

Best regards,

**Comment by mikejolley** [comment]
Don't log duplicates.

#13023
