### ISSUE TITLE
Cash on delivery: Enable for shipping methods empty

### ISSUE THREAD

**Issue by gr08** [woocommerce/woocommerce#13045]
Just like in the issue linked below, I can't select anything in "Enable for shipping methods" because it's empty, exactly like in the attachment of the case.
https://github.com/woocommerce/woocommerce/issues/11482

Status report:

### WordPress Environment ###

Home URL: https://eshop.zivakultura.cz
Site URL: https://eshop.zivakultura.cz
WC Version: 2.6.13
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: cs_CZ

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 20000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.13
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (6) ###

HTTP header improved security: by Carl Conrad – 1.10.3
Really Simple SSL: by Rogier Lankhorst – 2.4.3
Woo iDoklad: by Vladislav Musílek – 1.1.6
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
Woocommerce Zásilkovna: by Vladislav Musílek – 1.3.6
WooCommerce: by WooThemes – 2.6.13

### Settings ###

Force SSL: ✔
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: 
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /
Cart: #5 - /kosik/
Checkout: #6 - /pokladna/
My Account: #7 - /muj-ucet/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Storefront
Version: 2.1.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/emails/admin-new-order.php
`

**Comment by mikejolley** [comment]
The issue with the missing titles was resolved a while back: https://dl.dropboxusercontent.com/s/lefc8qga7s70ufj/2017-02-02%20at%2009.00.png

If it's 'empty' you may not have any enabled valid shipping methods setup in your zones. I cannot see any other issues with the stable release here. Please look at your zones.

**Comment by gr08** [comment]
I do have valid shipping methods set up (see attachment). Yet I receive an empty list under Enable for shipping methods. Maybe the problem could be in my usage of zones?
![2017-02-02_150716](https://cloud.githubusercontent.com/assets/25490218/22552720/620dbbe4-e95a-11e6-97a5-2aea8d3cc674.png)

As for this I just wasn't able to switch it into English (I would prefer it myself) so just to give you a hint - "Platba na ucet" = Cash on delivery
![2017-02-02_150813](https://cloud.githubusercontent.com/assets/25490218/22552719/620ce778-e95a-11e6-9b2f-957e0005bd44.png)

**Comment by mikejolley** [comment]
We have no such field in core. Must be extension?

**Comment by gr08** [comment]
Probably. I will investigate on that. In any case thanks for the quick response.

**Comment by gr08** [comment]
So you were right. The guilty plugin was woocommerce-zasilkovna. Their problem was this:
https://github.com/woocommerce/woocommerce/commit/fce7771d82eb5f7a4e15d606e266fbd88460e6fc
I will notify the author.
