### ISSUE TITLE
[2.7] Variable products not purchasable

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#13043]
Not sure if this is the intended behavior but it was introduced by a recent commit (and it's not consistent with WC 2.6).

`is_purchasable()` now always return `false` for variable products, since `get_price()` returns an empty string. 

I can't find the exact commit where this broke at the moment, but it was caused by a recent change to the data stores.

Note that in 2.6, `is_purchasable()` would return `false` when no purchasable/visible variation existed, which I think made more sense. The `_price` of a variable product was empty if:

1) all variations had undefined prices or 
2) all were invisible/disabled, for instance if all variations were out of stock and out-of-stock products were set to be hidden.

**Comment by franticpsyx** [comment]
Noticed that this was caused by `_price` meta fields being empty in the database, so for some reason variation prices were not saved correctly.

Pulled master, changed a variation price and saved parent -- problem solved.

I suspect this might have been caused by an earlier commit, but I can no longer replicate on `master`.

**Comment by WillBrubaker** [comment]
Re-opening b/c `is_purchasable` seems to return false if one variation exists without a price.

1. Variable product exists - it has two variations.
2. One variation does not have a price set (blank), the other variation does.
3. On an archive page, the button text is "Read More" when the expectation is that it would say "Select Options"

Further to this, if one removes the variation which does not have a price set, `is_purchasable` still returns false and will until some sort of change is made to the remaining variation and the product updated.

**Comment by charlieryan** [comment]
@mikejolley Is there any way to I can retrofit this fix onto 2.6.14? (which doesn't have the data-store classes).

**Comment by LukeAbell** [comment]
@mikejolley @WillBrubaker @franticpsyx We're having this issue when trying to upgrade a WooCommerce install from 2.6.14 to 3.3.3. What's the solve here to fix the bad data?
