### ISSUE TITLE
[Question] WC 2.7 -  How can to get the properties of an order, or another object, without triggering the full initialisation?

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#13054]
**Scenario**
Need to retrieve the order currency, to determine the appropriate decimal separator, thousand separator and format to use, before they are used. The new classes don't allow that, as they load **all** order properties as soon as a class is initialised (i.e. too early).

**Implementation, showing the issue**
~~~
/* Load order. This triggers a whole load of initialisation steps, which are 
 * premature at this stage. For example, it triggers the following:
 * - WC_Abstract_Order::set_discount_total()
 * - WC_Abstract_Order::set_discount_tax()
 * - WC_Abstract_Order::set_shipping_total()
 * All the above call function wc_format_decimal(), which looks for the decimal
 * separator and decimals digits. These cannot be determined now, because they
 * depend on the order currency, which is retrieved at a later stage.
 */
$order = wc_get_order(123);

/* Get the order currency, to determine the decimal separator, decimals, etc.
 * Now it's too late, as the class already decided to use the default values, which
 * are potentially incorrect.
 */
$order_currency = $order->get_currency();
~~~

In WC 2.6, this was not an issue, as an order currency could be fetched using `get_post_meta()`, before initialising the order. With the new WC 2.7 logic, that should be not be done, but the new classes don't seem to allow an alternative approach.

**Comment by mikejolley** [comment]
Looking at the code, `wc_format_decimal` does not use anything from the order. That function is independent. It does not rely on the order at all - https://github.com/woocommerce/woocommerce/blob/09123c9fc8a1410e9a314c7713205d50ea2f027a/includes/wc-formatting-functions.php#L252

The purpose of wc_format_decimal is to remove all formatting/locale/currency formatting so the values are stored within the CRUD class in a consistent manner. Therefore this should not affect you.

If there is a legitimate reason to need to get the currency independently of the order object I'd suggest raising a PR which:

1. Adds a get currency method to the ORDER DATA STORE
2. Adds the get currency method to the ORDER DATA STORE INTERFACE

Then if the data store is extended or replaced by future code, it will handle the retrieval of currency too (because the interface will force developers to implement this).

Hope this makes sense again :)

**Comment by daigo75** [comment]
> ooking at the code, wc_format_decimal does not use anything from the order. That function is independent. It does not rely on the order at all 

That's precisely the issue I need to address. When an order is loaded, it calls `wc_format_decimal()` to format some amounts. The format to use for those amount may depend on the currency used for the order (very common in a multi-currency store, where different currencies have different formats). This boils down to the following
* Load order
  * Load data
  * Format data. Call `wc_format_decimal()`
    * Before formatting the data, determine the correct format (decimals, separators, etc). We are loading an order, so we must use the currency in which the order was saved.
      * Load the order from the currency. For this, we need to load the order. This brings us back to to the top, in an an endless loop.

**Comment by daigo75** [comment]
**Correction to my note**
I noticed that the risk of an endless loop seems to occur mainly when an order is created, as that's when `WC_Abstract_Order::set_discount_total()`, `WC_Abstract_Order::set_discount_tax()` and `WC_Abstract_Order::set_shipping_total()` are called (unless I missed them elsewhere). I will think of a workaround for that.

**Comment by mikejolley** [comment]
@daigo75 

```
The expected result, in a MC environment, is that order amounts will appear like this on the order list, or on the order edit page:

Order 1 - $123,456.78 (USD, two decimals, comma for thousands, point for decimals)
Order 2 - €123.456,78 (EUR, two decimals, point for thousands, comma for decimals)
Order 3 - ¥123,456 (JPY, no decimals, comma for thousands)
```

Why do you have values like this in the first place? They should be normalised if they are stored in the database already. Sounds like an issue higher up...

**Comment by daigo75** [comment]
That's not an issue. Values are stored by WooCommerce as usual, as raw numbers. The example was just to shows how they should be formatted when displayed in the Order List page. That is:

**Order 1**
- Order total (from DB):  123456.78
- Order currency: USD
- Formatted total: $123,456.78

**Order 2**
- Order total (from DB):  123456.78
- Order currency: EUR
- Formatted total: €123.456,78

**Order 3**
- Order total (from DB):  123456.00 (Japanese Yen has no decimals)
- Order currency: JPY
- Formatted total: ¥123,456

**Comment by mikejolley** [comment]
It sounds like you still have full control over that. The raw values are what is stored in the CRUD object.
