### ISSUE TITLE
[2.7] 'wc_get_price_from_prefix' function is not defined

### ISSUE THREAD

**Issue by akash-dhawade** [woocommerce/woocommerce#13059]
## EXPLANATION OF THE ISSUE

While testing our plugin with 2.7 beta 1 i got the error 'The WC_Product::get_price_html_from_text function is deprecated since version 2.7.Replace with wc_get_price_from_prefix'.

After some debugging i found out that 'wc_get_price_from_prefix' function is not defined. Is there any other way to access this function or is it a bug?

**Comment by franticpsyx** [comment]
See `wc_get_price_html_from_text`.

**Comment by mikejolley** [comment]
Was a typo, fixed in master.
