### ISSUE TITLE
connect woocommerce api with ionic 2

### ISSUE THREAD

**Issue by phattira** [woocommerce/woocommerce#13053]
**I have a problem connect woocommerce api 
But error cannot file name oauthSignature
I'm not sure ,I write code authentication right or wrong**

 **Code :**
 var d = new Date();
    var httpMethod = 'GET',
     url = 'http://localhost:8080/wordpress/wp-json/wc/v1/orders',
     ck = 'ck_xxx',
     cs = 'cs_xxx',
     sm = 'HMAC-SHA1',
     nc = this.nonceGen(),
     timestamp = Math.floor(d.getTime()/ 1000),
     parameters = {
         oauth_consumer_key : ck,
         oauth_timestamp : timestamp,
         oauth_nonce : nc,
         oauth_signature_method : sm
     },
     encodedSignature = oauthSignature.generate(httpMethod, url, parameters, cs,{encodeSignature: true });
  this.http.get(
     url + '?oauth_consumer_key='+ck+'&oauth_signature_method='+sm+'&oauth_timestamp='+timestamp
     +'&oauth_nonce='+nc+'&oauth_version=1.0'+'&oauth_signature='+encodedSignature+'&oauth_consumer_secret='+cs
 ).subscribe(data => {
     console.log('fetched');
     console.log(data);
 });
  }

  public nonceGen() {
      let length = 32;
      let text = "";
      let possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
      for(let i = 0; i < length; i++) {
          text += possible.charAt(Math.floor(Math.random() * possible.length));
      }
      return text; 

Thank you

**Comment by mikejolley** [comment]
https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http states how fields should be ordered etc (alphabetically) before generating the signature. Yours are not ordered.

Use HTTPS auth instead if you don't want to deal with it.

**Comment by Zilleabbas10** [comment]
I am getting oauth signature issue in it 

{
  "code": "woocommerce_rest_authentication_error",
  "message": "Invalid signature - signature has already been used.",
  "data": {
    "status": 401
  }
}

Even it is re-generated everytime
