### ISSUE TITLE
shipping address missing from order email in certain situation

### ISSUE THREAD

**Issue by imprison** [woocommerce/woocommerce#13055]
I think there are one circumstances the email do not show shipping address. Which is a completely new customer never check out before OR first time visit use guest check out. They go to the checkout page, no touch "Ship to a different address?" just quickly finish checkout. and when they receive the email with no shipping address showing.

**Comment by mikejolley** [comment]
Not in my testing. The only case I can get the shipping hidden is if there are no shipping methods or if the order does not require shipping e.g. an order containing only virtual products. 

Try testing other payment methods/see if shipping is selected on checkout. Post back if you can narrow down the issue - I'm closing it for now as I cannot replicate it.
