### ISSUE TITLE
Cancelled should be Canceled throughout

### ISSUE THREAD

**Issue by garrett-eclipse** [woocommerce/woocommerce#13062]
## EXPLANATION OF THE ISSUE

While translating en_CA I noticed that some strings have cancelled in the source. I assume source is written in American english correct? If so cancelled is the Canadian spelling and canceled is the American spelling.

Example of this here;
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/en-ca/default?filters%5Boriginal_id%5D=3783953

Cheers

**Comment by DavidAnderson684** [comment]
Relevant: https://github.com/woocommerce/woocommerce/issues/12627

**Comment by mikejolley** [comment]
Yeah, see that issue ^

**Comment by garrett-eclipse** [comment]
Thanks @DavidAnderson684 and @mikejolley I fully appreciate that and understand why you wouldn't want to change in code. Cheers
