### ISSUE TITLE
Schema markup stripped from emails

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#13066]
## EXPLANATION OF THE ISSUE
Schema/microdata added here https://github.com/woocommerce/woocommerce/blob/release/2.6/includes/class-wc-emails.php#L280-L379 and then stripped out by the emogrifier here https://github.com/woocommerce/woocommerce/blob/release/2.6/includes/libraries/class-emogrifier.php#L326-L333

## STEPS TO REPRODUCE THE ISSUE
1. Take any action that sends an order email
2. See that the HTML code of the email lacks the microdata

would `visibility:hidden` be a better choice than `display:none;` ?

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by claudiulodro** [comment]
The 2.7 release gets rid of the hidden div wrapping the structured data, so this specific problem will be resolved. :-)

@mikejolley the WC_Structured_Data class doesn't get instantiated on the backend. This means e-mails sent using the "Order Actions" admin metabox won't have structured data, but e-mails sent from the front-end will. It doesn't look like instantiating WC_Structured_Data on both ends will have any unintended side-effects, so I'm going to make a pull request for it.

**Comment by mikejolley** [comment]
@claudiulodro Thanks. Don't forget to link PRs to issues like this if related for tracking. Just mention the issue number in your description.
