### ISSUE TITLE
[2.7] Previously-working product selector stopped working

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#13065]
## EXPLANATION OF THE ISSUE

I have an extension that allows users to select which products to apply an option to, using a drop-down selector. To accomplish this, it adds the screen to the list of WooCommerce screen IDs (which causes loading of WC JS - this is still working), and adds an input tag.

On WC 2.7, the pre-selected items are not shown, and all searches for products turn up no results.

I have managed to resolve this by changing from a hidden input field to a select, in the style used in WC 2.7 in includes/admin/meta-boxes/views/html-product-data-linked-products.php . However, I had not seen any documentation about the change, and do not know if the breakage is intentional or not.

## STEPS TO REPRODUCE THE ISSUE

Here's the field I was outputting (`$product_ids` is an array of numeric product IDs):

```
<input type="hidden" class="wc-product-search" data-multiple="true" style="width: 50%;" name="linked_woocommerce_products[]" data-placeholder="<?php _e( 'Search for a product&hellip;', 'woocommerce' ); ?>" data-action="woocommerce_json_search_products_and_variations" data-selected="<?php

					$json_ids    = array();

					foreach ( $product_ids as $product_id ) {
						$product = wc_get_product( $product_id );
						$json_ids[ $product_id ] = wp_kses_post( $product->get_formatted_name() );
					}

					echo esc_attr( json_encode( $json_ids ) );
				?>" value="<?php echo implode( ',', array_keys( $json_ids ) ); ?>" />
```

includes/admin/meta-boxes/views/html-product-data-linked-products.php in WC 2.7 does it differently - it uses a select tag. But as I say, I do not know if all extension authors are required to change, or not; I've not found any info on it.

Using today's Git master for WC 2.7, WP 4.7.3-alpha-40018, PHP 7.0.15, TwentySixteen 1.3.

There are no JavaScript errors logged in the JavaScript console, or PHP notices in the PHP log.

**Comment by DavidAnderson684** [comment]
WooCommerce 2.6:

![wc-26](https://cloud.githubusercontent.com/assets/1962275/22618149/621f10c8-eacd-11e6-8863-9ec5ac30f143.png)

WooCommerce 2.7 (identical site):

![wc-27](https://cloud.githubusercontent.com/assets/1962275/22618150/66d49b06-eacd-11e6-84d2-5a79060fdea6.png)

Searching on WooCommerce 2.7:

![wc-27-notfound](https://cloud.githubusercontent.com/assets/1962275/22618151/698e8492-eacd-11e6-8050-35cd44b860a6.png)

**Comment by mikejolley** [comment]
Select2 v4 requires select boxes. See the notes and instructions in https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-2.7.x-Developer-Migration-Notes to make it compatible.
