### ISSUE TITLE
Improved SKU search on front and backend

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13074]
Make sure products can be searched by SKU and other important fields and make it more prominent.

**Comment by mikejolley** [comment]
On re-review it seems our search handles this flawlessly on both front and back. There is no dev needed.

**Comment by tlaverdure** [comment]
@mikejolley, should searching for a product by SKU work out-the-box ob the front end? I'm currently not able to do so on a fresh install of WooCommerce.
