### ISSUE TITLE
Product Admin UI Revisions

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13071]
- [ ] Move short description above main
- [ ] Move gallery meta boxes to top of screen (custom box?)
- [ ] Move SKU near title
- [ ] Move product type selector near title
- [ ] Move prices near title
- [ ] Gallery image trigger https://github.com/woocommerce/woocommerce/issues/10791
- [ ] User testing to validate changes

**Comment by BurlesonBrad** [comment]
Move short description above main 👍 💯 🥇 
 Move gallery meta boxes to top of screen (custom box?) 🤔 
 Move SKU near title 🤔 
 Move product type selector near title 🤔 
 Move prices near title 🤔 

Remember this UX test? https://www.youtube.com/watch?v=7iWRBLCP-l0
They did this at a MeetUp and the results were incredibly insightful as to _"how"_ the folks were cognitively looking at the screen and accomplishing a task.  

So, can we / I / we / me / Nicole / WC MeetUp groups / _*"whomever-else-we-can-think-of"*_ / take some of these "concepts" for a spin first, watch+listen to feedback, then retest another layout, watch+listen to the feedback, lather rinse repeat?

Switching `product descriptions` layout is something the whole WC team & every store owner knows is probably long overdue, and it'd be universally and warmly welcomed. 

But.... the rest of those line items? It would _"indeed"_ make absolute sense *IF* that's what folks are needing.  Not _"maybe needing or wanting"_, but rather *_"we-have-empirical-and-objective-tests"_* which are indicative that these layout changes *will* be beneficial.

So.... how can I help?

**Comment by seb86** [comment]
If you moved the price fields, how would it affect other product types?

**Comment by NTShop** [comment]
My advice is don't make changes because you think it'd be better. Get ample (plenty of) feedback from daily users of WooCommerce and do what the majority tell you - assuming you get enough actual daily users to give feedback. If you don't then be 1000 times more hesitant to change anything. Take the WP approach that is tried and proven for over a decade:Proceed VERY carefully and VERY slowly over a LONG period of time. Don't shock the daily users. They are not UX experts and they don't care much what that means, they're not experts with WP or Web sites, they are store operators in to make money. That's all that matters for the most part.  Don't mess up their revenue stream by introducing frustrating for them by making store operators re-learn stuff that was changed when they didn't tell you it needed to be "fixed." Keep in mind that a megaton of these store operators have staff/personnel that operate their store - it costs them time and money to retrain when things changes, and it costs them time and money when their clerks mess stuff up due to things suddenly being different.

**Comment by NTShop** [comment]
Moving the price field or any of the product data is probably a bad idea. Think like a product manager running a real store: The line of thought is typically: My product is called ABC, it does XYZ, it costs this much money. You can see that via expert marketers that run their TV commercials in that line of thinking.

**Comment by claudiosanches** [comment]
@NTShop 

> Moving the price field or any of the product data is probably a bad idea. 

Even to make easy for product managers find and change?

**Comment by NTShop** [comment]
@claudiosanches - I think maybe you're assuming nobody uses custom pricing software that affects pricing fields, or custom products that have their own pricing field, or field related directly to pricing. Moving price stuff up to the title might make a huge mess of things. I've seen countless sites that do all sorts of odd things related to pricing and if the price fields are move (regular and sale) then that disconnects fields that may not fit by a title.

**Comment by claudiosanches** [comment]
@NTShop so the currently for it's perfect for any user and no need to be improved. Thanks for you input.

**Comment by kieranbarnes** [comment]
I think the big issue currently here is we (devs outside of the core) need a better understanding of how this proposal will affect users, custom plugins and how it will affect product types.

Whats the reason behind this change and are we allowed to know the reasons why?

My initial reaction is _how does moving the price and SKU to the top work with variable products?_
Does moving the product type selector affect the same? Does the entire product data meta box move to the top also?
The product meta box, especially the variables can get super long and ugly with just a few plugins or custom code - I am not sure I'd like that at the top.

I am sure you have thought about this much more than we have before opening the issue, however more clarity to help us decide if this is a good idea or not.

You may find most people just drag it down below the description at least, if not further down.
Opposingly, I see customers move the current product data meta box to the very top of the page.

We are on the front line of store development, I hate nothing more than a frustrated store manager calling me asking me why things have moved in his/her product admin page or why some functionality has changed. We can only spin the _"change == progress"_ excuse a few times!

Maybe consider staging the changes as to not shock the users and upsetting your indirect users (Not us devs, but the store owners). 

I agree with @NTShop store managers are not UX experts, nor do most of them care, many of them pay good money to move things around the product admin page to save time or add extra functionality that works for them or their business - those changes would probably make a UX'er quite upset. 

He summarises the dis-join between core devs <-> devs <-> store managers quite well.

Maybe some screen shots? Or a beta plugin that moves the fields around for devs / store managers to test before rolling this out to everyone?

**Comment by mikejolley** [comment]
> Whats the reason behind this change and are we allowed to know the reasons why?

Past user tests. Perfect example, I've seen both a user test and a "technical user" (not familiar with WordPress) try to add a featured image to a product by adding media to the content area. This is a perfect example of why some kind of rejig is needed. We'll allow for additional user testing before shipping changes.

Testing these changes on trains/existing users isn't really going to fly. This is to improve the nux, because getting lost creating your first product is not great.

- SKUs we need to enforce, also for technical reasons. Moving to the title and having them auto-generate would be a good step.
- Product type is important because it affects all other fields.
- Gallery, see my example above.
- Short description makes no sense to be below main. Personally, I'd like to combine them somehow, but if thats not possible short term, moving up works for me (see coupons screen).

Price is the most difficult due to plugins.

**Comment by renatonascalves** [comment]
I see the change as important, as there are room for improvements.

Recently I had a problem where the short description was being added in the main content and the client was not aware of the difference, questioning me why he added the content and it wasn't being shown (the front-end main content was purposefully removed).

The current "layout" causes some confusion for a non experienced user with WooCommerce. Another area that causes confusion is the gallery versus main image.

I think the current implied thinking is important. Moving SKU to the top will "force" people to add it. Also adding the description and pricing will facilitate when filling it.

Also somehow make it more clear the main content is the description in the front-end tabs.

**Comment by mikejolley** [comment]
![edit screen concept](https://cloud.githubusercontent.com/assets/90977/25390976/f9a1f26a-29cc-11e7-813e-36ebbf9cf49c.png)

Rough not 100% functional concept showing the type of thing we can do.

**Comment by kieranbarnes** [comment]
I like it.

Whats the plan for variable products?

**Comment by seb86** [comment]
@mikejolley I assume that if a sale price is entered the date fields will then appear below which would move the short description further down. Would it not be better to have the short description on it's own row so it stays consistent?

**Comment by mikejolley** [comment]
@seb86 TBH I wanted to keep those fields in the panel, but it could become 2 side by side fields below the price fields..

**Comment by bekarice** [comment]
echoing some of the notes in the [core Slack chat](https://woocommercecommunity.slack.com/archives/C4TNYTR28/p1493136667317419), if this isn't intended to be an area that extensions hook into, I don't see how price fields can be there. There are numerous plugins, like Subscriptions, that need to be able to essentially override these fields. I imagine Bookings is the same way.

Some others off the top of my head that either affect price or need to output their own fields next to / below price: Cost of Goods, Measurement Price Calculator, Minimum Advertised Price

**Comment by rafsuntaskin** [comment]
We are already using this kind of UX in our **Dokan** plugin. It would be great to see something like this in Core.
![new-product](https://cloud.githubusercontent.com/assets/7523321/25425110/9cadba10-2a8c-11e7-9f69-b9b763a1fd96.gif)

**Comment by rkhoury82** [comment]
as an end user [merchant with multiple stores] I agree with @mikejolley comments about the UI and the need for the changes in the first post. Especially the gallery changes and movement of the description boxes !

The mock up's look like a step in the right direction.

It would be great to have the ability to "arrange" the images via drag and drop if possible. Including the setting of the featured image.

I can't speak re technical issues - but as a merchant simplifying that addition and maintenance of products would be a huge win.

**Comment by squill** [comment]
I saw the post on DevChat about the suggested interface and have come here to comment. Will the proposed changes affect the ability to use the WooCommerce Advanced Product Quantities plugin https://wordpress.org/plugins/woocommerce-incremental-product-quantities/ and the overrides on a per-product basis? I cannot run my business without the ability to set these parameters.

Maybe I got the wrong end of the stick but are you talking about auto-generating SKUs? Is so, why?

**Comment by mikejolley** [comment]
I think we're going to need to spend a little longer on this to get a prototype up and feedback - 3.1 was a little optimistic.

I'm increasing effort points and moving to 3.2. We can work on it beforehand, but I don't want to rush it.

**Comment by mikejolley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Simplify the edit product screen](https://trello.com/c/Vwp2cUPo/103-simplify-the-edit-product-screen)

**Comment by robin-scott** [comment]
Any movement on this stuff likely? I got some really non technical end-users on a project or two and we moved a lot of stuff around for this. Can add some insight if there's usability testing happening?

**Comment by mikejolley** [comment]
No movement on this.

We're looking internally how the future of products and other sections should look, and since Gutenberg is coming, everything in this issue is on hold. Hence for that reason I'm closing it. Making design changes at this stage would be wasted effort for the dev team.

cc @warrendholmes

**Comment by KoolPal** [comment]
How can an end user accomplish the above using Gutenberg?

**Comment by warrendholmes** [comment]
@KoolPal That's not possible right now. We're hoping to start exploring that work this year.
