### ISSUE TITLE
Remove the products "Menu Order" options

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13072]
To address #5468.

The menu order system does not make sense to end-users. It's a confusing and convoluted option and should really be extension territory.

The drag and drop to sort is also hidden/not well known, and clunky (imagine sorting a product catalog manually < 100 products!).

- [ ] Remove the menu order option
- [ ] Remove the sorting options
- [ ] Introduce a better set of built in automatic sorting options
- [ ] Ensure (working) extension based solution exists for those who need it

**Comment by larssn** [comment]
Do you have any extensions in the pipeline then, that will replace it?

**Comment by mikejolley** [comment]
We'll have a better default sorting order. Custom ordering really isn't that useful if you have a large store. But yes, I imagine it will move to an extension if there is demand.

**Comment by dominic-p** [comment]
Sad to see this leaving the core. We use custom sorting extensively, and while the drag and drop is clunky it's better than trying to get some automated sorting method to yield the results you want.

Even if the UI for sorting is removed, couldn't the built in WordPress Menu Order (available on the Advanced tab on the product edit page) still be respected?

**Comment by mikejolley** [comment]
It could be; it could also be added back pretty easily by an extension.

Why do you prefer to sort them manually? What do you use the sorting for?

**Comment by dominic-p** [comment]
Gotcha. We use manual sorting for 2 main things:

1. We like to manually curate at least the first couple pages of the "All products" page to show a good mix of products from a variety of categories.

2. For special events we will use shortcodes to show products from certain categories elsewhere on the site, but we want to control how the products appear there and the menu order is the only user friendly way I can think of to do that.

To expand on number 2 there which is the most important use case for us. We use a custom shortcode to grab products based on attributes or categories and show them on landing pages. We will only want to display a handful of these products on the landing page, but which ones? With custom sorting we can easily choose which ones show and which ones don't. Without it, the only thing I can think of would be hard coding product IDs into the shortcode which is time consuming, error prone, and leads to rot (IDs tend to change over time).

**Comment by larssn** [comment]
We've built a custom frontend in angular 2, and communicate with WC via REST. We use sorting a lot as well, and are sad to see it go. We're in the hostel business, and our customers need very specific ordering of certain products.

**Comment by zmart-sen** [comment]
Seems like folks are missing this vital point:

# If sorting gets removed, it will be available as a plugin / extension

**Comment by dominic-p** [comment]
@zmart-sen maybe I'm missing something but

> I imagine it will move to an extension if there is demand

doesn't sound like a guarantee to me. If the Woo team does plan to maintain an extension for this functionality going forward, I would, of course, have no issue with it leaving core.

**Comment by zmart-sen** [comment]
> if there is demand
This appears to evaluate to true.

I volunteer to create a lite replacement plugin if this change goes through and the Woo team decides not to author the plugin themselves.

**Comment by hellosubscription** [comment]
There was at one time a plugin that used rules to sort products. That would be great, but mine personally would depend on what taxonomy they are in etc (we use taxonomies instead of fields for some items for a variety of reasons, including google friendliness). I have a very large WC instance that is due to be profiled on the WC site and I would be happy to show a core developer how we do things. Unfortunately we do need to set items manually and the lack of the menu order is really glaring. It's on my developers' list to put back in for me.  I doubt that the people that decided to remove this feature really understand the different ways that WC is used. Ours is probably quite fringe, but incredibly useful to us to be on the WC base. 

fwiw the menu order system makes perfect sense to everyone begging for it to be put back. i don't have any need for dimensions in my shop but i wouldn't ask for it to be removed...

**Comment by mikejolley** [comment]
I'm going to close this one out. We should avoid changing too much of the UI until a full redesign is done. If this is part of that redesign fine. We can make an informed design there with user feedback groups.
