### ISSUE TITLE
REST API v2

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13070]
Updates to the API which require a version bump.

- [x] Replace use of `get_post` or `get_post_status` in the REST API
- [x] Remove the variations data from products endpoint
- [x] Review schemas to be fully compatible with CRUD objects
- [x] Deprecate filters and actions that expect WP_Post

**Comment by mikejolley** [comment]
@bryceadams Nothing breaking; Claudio is going to bump the API version to 2. v1 will be left alone.

**Comment by bryceadams** [comment]
So only v2 will have the date fixes (timezone related) and order meta?

**Comment by mikejolley** [comment]
@claudiosanches ^ fixes will be right?

**Comment by bryceadams** [comment]
I think makes sense to include order meta, as it's already in there and a
small change with no breaking changes to those conusming v1 API already.

**Comment by mikejolley** [comment]
@bryceadams This was Claudios argument - if the API is not bumped to v1, how do you know a client supports it?

**Comment by bryceadams** [comment]
Personally I just check the WC version and especially with meta, irrelevant
as can just see the if the meta index exists and act accordingly. Feel like
it would do more harm than good bumping (makes sense for removing
variations, but such a small change just for a whole new version that needs
to be supported).

**Comment by claudiosanches** [comment]
@bryceadams new actions, new filters, new data, changing data and so on, we need remove a few actions and filters for performance too and now we have several new endpoints... It's a new version.
Not to mention that is confuse saying "This is available on v1, but only in WooCommerce 2.7+".
And we can include now the timezone change too, of course.

**Comment by bryceadams** [comment]
I agree with @claudiosanches after hearing more about what is in v2. One thing we discussed was that date fixes probably shouldn't go into v1 but only v2 since any code using v1 will be broken. So if the v1 stays as is and everything new goes in v2, nothing breaks.

Off the top of my head, the dates that should stay as is (using the store timezone instead of UTC) were date paid, date completed, and the refund created date.

**Comment by claudiosanches** [comment]
See #13206 and #13225
