### ISSUE TITLE
Design Import/Export data schema

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13077]
Design the schema for the CSV file for import and export. This can be based on the CRUD, but needs to work well for fields which contain multiple values, and deal with variations. We need a plan for both column names and field formatting.

Variations and products should be imported in the same sheet.

Just a note, @jameskoster's initial designs show an interface where non-schema matching fields can be mapped.

**Comment by mikejolley** [comment]
I've added the basic idea to https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

I'm going to make a same CSV from this plan but if you could send feedback that would be great.

@claudiosanches @gedex @claudiulodro @justinshreve 

Main things I'm worried about are mapping IDs to IDs and attributes for variations.

**Comment by claudiosanches** [comment]
> Images need to be pre-uploaded or online; only URLs are supported. To prevent duplication, imported images should store the source URL in meta.

Can we have ID too?
Like `image_url` and `image_id`, so we can prefer ID when is filled.
This is what we do on REST API.

**Comment by mikejolley** [comment]
@claudiosanches IDs are hard to work with. I would really like to make this ID-less if we can. In my notes I said we should store the 'source' URL in product image meta data - that will prevent duplicates like CSV Import suite causes.

**Comment by claudiosanches** [comment]
@mikejolley even when first time I upload using dropbox and then update the product using the image from WordPress media gallery?

**Comment by mikejolley** [comment]
@claudiosanches So you're going to sit there looking up 100s of image IDs in the gallery :)?

**Comment by claudiosanches** [comment]
@mikejolley you can return `url` and `id` or both in the same field, like `image` = `123|http://example.com/image.png`.

**Comment by mikejolley** [comment]
I guess we can support it, but I don't think it will be used :) We shouldn't export IDs thats for certain - URLs only.

**Comment by claudiosanches** [comment]
And what I'm saying about update later with the image from WordPress media gallery is when you export to import again... When you export you will get the links from WordPress media gallery, you can just update a few fields and then import again with new source for the links.

**Comment by claudiulodro** [comment]
> Arrays of fields use commas to separate values.

Won't this dramatically complicate parsing, since everything is separated by a comma in a CSV? It'd be way easier to use a `|` or something IMO

**Comment by mikejolley** [comment]
@claudiosanches @claudiulodro CSV/spreadsheet editors can deal with commas in fields. Fields are wrapped in quotes and values escaped. What you're saying would mean no one can use commas in their data, which is not the case.

We've had feedback about pipes in the past about them not being very easy to use, especially on non-english keyboards.

> And what I'm saying about update later with the image from WordPress media gallery is when you export to import again... When you export you will get the links from WordPress media gallery, you can just update a few fields and then import again with new source for the links.

Not sure what you mean?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema updated and ready. I'll add a link to next weeks tasks.
