### ISSUE TITLE
Built in Product Importer/Exporter

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13083]
New product import/export solution which imports from any CSV, handles mapping, and uses the CRUD system or API to create products in the database.

Primary focus is on initial import, but will support merging.

⚡️ Sprint 2 will be out the importer itself.
⚡️ Sprint 3 will add support for common CSV formats, and build the export portion.

_Notes:_

- For Sprint 2, focus on functionality - we can improve appearance in Sprint 3.
- Importer should be exposed in `Tools > Import `
- `Import` should also be a submenu item under the `Products` menu. This will be the primary location.
- `Export` can be available on the main products list at the top somewhere (button or link).
- Batching is important to scale. After the initial dev work is done we will be testing large exports and imports on a variety of hosting environments.
- After the sprints we'll create a sample CSV to replace our existing CSV files in dummy_data.

**Comment by abdiaskalim** [comment]
Urban Clothing, rave gear, edgy shirts

**Comment by EgbertJan** [comment]
Development is good. Please try to leave the product import CSV plugin functionality as it is. It is essential for our sites to be able to read a CSV from a local directory (webroot), We create such a CSV from our external product database (on the same server) with some PHP code for 8000+ products and use the Import prod CSV plugin to merge/import updated or new products. TNX! Egbert Jan, NL
