### ISSUE TITLE
Themes step in Wizard

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13088]
@jameskoster can you add more details here?

**Comment by jameskoster** [comment]
Basically, if they're using a wp default theme, or any other theme that doesn't support wc let's display a Storefront recommendation with a 1-click install button.

Some benefits we can list with our recommendation;

* Quick setup
* Theme design tailored to WC
* Design options to 'make it your own'
* Deep integration with a number of wc extensions
* Shop specific homepage template
* Platform for growth (child themes / extensions)

Happy to design this step if required.

**Comment by mikejolley** [comment]
> Happy to design this step if required.

@jameskoster yes please. If you can have this ready by the time we do this sprint that would be great.

**Comment by jameskoster** [comment]
@mikejolley what's the due date?

**Comment by mikejolley** [comment]
Undecided; we'll add dates to this milestone. Won't be for ~ month at least I doubt.

**Comment by mikejolley** [comment]
@jameskoster I know you're busy with current projects. If this was to be built end of the month, could you have a design ready in time?

**Comment by jameskoster** [comment]
Design here: https://www.dropbox.com/s/fx6u3t7atq2ol1n/wc-wizard-theme.sketch?dl=0

(Unfinished)

**Comment by mikejolley** [comment]
@jameskoster Have a finished version yet?

**Comment by jameskoster** [comment]
Would next week be OK?

**Comment by mikejolley** [comment]
@jameskoster Possibly otherwise we'll just push it back to 3.2 to keep on track if we don't have time this cycle.

**Comment by jameskoster** [comment]
Here we go

![themes](https://cldup.com/QXayLIyyLs.png)

**Comment by mikejolley** [comment]
@jameskoster is the intention to only show this step if NOT using a theme which declares support for WC?

**Comment by jameskoster** [comment]
That or a default theme.

**Comment by avivapinchas** [comment]
Suggested [copy here](https://docs.google.com/document/d/14GATHwMeI3-M134Nret2F-U20kuEzvDQui0fNDp0C8w/edit#). Moving forward, would be good to have some kind of relationship between what's happening on the product page on woo.com and what's pulling in here - would be good to be able to update the copy in one spot and have it feed to both. 

cc: @warrendholmes

**Comment by jameskoster** [comment]
Thanks. Updated design;

![updated-theme-step](https://cldup.com/8EN4YXZJeF.png)

**Comment by avivapinchas** [comment]
Two minor notes on this: 
- The headline copy isn't updated - should read: 
> Choose a theme to kickstart your store: Storefront is our free WordPress theme, built and maintained by the makers of WooCommerce. 
- I suggest bolding the beginning of each bullet, the bit before ':' to make it more scannable.

**Comment by jameskoster** [comment]
Good suggestions. I'll update.

Yeah I was concentrating on lining the bullets up.
