### ISSUE TITLE
Variations admin UI design

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13084]
Design work; no development.

**Comment by vvp242424** [comment]
This would involve both. but we need to have the reports be usable. Or be able to dive into the data. Right now I pull up the reports and see that 6 renewal orders worked and 32 retry attempts failed. Would very much like to click into the 6 that worked and see who they are and why they worked to see if something needs to be tweaked. Or another example is that 1 sub switched in the past 7 days. Tracking who that one switch was,  is currently not possible without doing a bunch of work arounds.  Let me know if this is not the right area for this feature recommendation.

**Comment by avishai** [comment]
For the UI, I would suggest something along the line of Shopify's variant UI. It's very clean and clear to understand what's going on, unlike the current WC variations setup, which requires first creating attributes, and then switching to a new panel and creating each variation based on the attributes. 

![image](https://cloud.githubusercontent.com/assets/13284/23671230/24f12920-0373-11e7-9a54-5298894b2abe.png)

Etsy's store manager also has a very good, clear UI for managing product variations. (They call attributes options). 

<img width="1173" alt="screen shot 2017-03-07 at 8 22 14 pm" src="https://cloud.githubusercontent.com/assets/13284/23671439/e8b3c03e-0373-11e7-8d19-386bc83f1393.png">
<img width="781" alt="screen shot 2017-03-07 at 8 22 07 pm" src="https://cloud.githubusercontent.com/assets/13284/23671440/e8e74c4c-0373-11e7-95b9-ac6392b88bc7.png">

**Comment by rocketeer76** [comment]
There's a very interesting checkbox in the Etsy store manager. "SKUs vary for each fabric". Will WooCommerce handle different SKU's for the attributes in the future? As of now, if I remember correctly attributes inherit the SKU of the parent.

**Comment by jameskoster** [comment]
> WooCommerce handle different SKU's for the attributes in the future? As of now, if I remember correctly attributes inherit the SKU of the parent.

If by 'attributes' you mean variations; WooCommerce currently allows different SKUs per variation.

**Comment by rocketeer76** [comment]
Yes @jameskoster I mean variations (not attributes) as discussed earlier here:
https://github.com/woocommerce/woocommerce/issues/7944

And also here:
http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/8795116-variation-level-attributes

Perhaps I misunderstood what was discussed earlier in this thread!? @mikejolley calles it variation-level attributes. Is it currently allowed by WooCommerce now?

**Comment by jameskoster** [comment]
Ah, no that is not possible.

But if it were, I can't imagine it changing the way SKUs work. They'd still be applied to the variation. Attributes + SKUs aren't really linked. Variations + SKUs are.

**Comment by mikejolley** [comment]
Being done in Calypso.

**Comment by kellychoffman** [comment]
To clarify, this is the design issue and the implementation issue is here: https://github.com/woocommerce/woocommerce/issues/13085

**Comment by llermaly** [comment]
I'm facing a similar problem. I have a customizable product (printed tshirt) so stock between "printings" is shared, in opencart this was easy to solve, just select "Manages Stock" on "Size" attribute. But here in woocomercce I face some problems.

If I select "Any printing" - Size L ,  I can manage stock , but I can't set an image per printing.

If I select "Any size" - Printing Lion . I can set the image to printings but I can't manage stock per size

Selecting all possible combinations (Lion S, M, L .. Dog S,M,L...etc) separates the stock when in reality "Lion S" , and "Dog S" are the same blank t-shirt S sized.

Any workaround ?
