### ISSUE TITLE
Product Importer; Import mapped and parsed data

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13082]
#The actual import process which needs to deal with lots of rows and ensure timeouts do not happen.

With CSV Import suite it uses javascript triggered events for each batch. Maybe something like that can work here too?

This is a prerequisite for https://github.com/woocommerce/woocommerce/issues/14717

- [ ] Handle products, variations
- [ ] Actions for 3rd parties to handle columns

**Comment by claudiulodro** [comment]
[Here's a good article series I found about writing CSV importers for WordPress](https://tommcfarlin.com/importing-csv-files-into-wordpress-preventing-timeouts/). He even covers the PHP timeout issue. :)

**Comment by mikejolley** [comment]
Might be good to support addition/removal from stock rather than setting.

**Comment by claudiulodro** [comment]
I'm not sure how that would work. 

Given this situation:
Existing product, ID=12, stock=10
Imported product, ID=12, stock=8

What should happen?

**Comment by mikejolley** [comment]
You could support some additional syntax to indicate an addition/removal vs a set.

**Comment by mikejolley** [comment]
This issue is addressed. The other issues address the remaining parts.
