### ISSUE TITLE
negative number in menu sort breaks related products on main shop page. 

### ISSUE THREAD

**Issue by ninjamonkno1** [woocommerce/woocommerce#13098]
## EXPLANATION OF THE ISSUE

I had an issue when a shop admin at put -2 into the menu order for a product and the related products on the shop page stopped working. Default Product sorting was set to Custom ordering + name. 

## STEPS TO REPRODUCE THE ISSUE

Go to settings -> Products -> Display 

make sure you have Default Product Sorting value set to Default sorting (Custom ordering + name)

then

Select a product and go to advanced tab and enter -2 and update the product.

Now go to the shop you will notice no related products are shown. deleting the -2 from the product restores the related products.

**Comment by mikejolley** [comment]
Unable to replicate this one, makes no difference. The related products queries also don't use menu_order in any of the queries. The order is just random (using PHP `shuffle` function).

**Comment by ninjamonkno1** [comment]
Ok, it's an odd one that exists on a client site. I will test it on a fresh install and report back if it still does it for me. I can literally turn on and off the related products on the shops home page by adding -2
