### ISSUE TITLE
RESTFUL API - Delete or update product images doesn't work

### ISSUE THREAD

**Issue by itphil** [woocommerce/woocommerce#13091]
## EXPLANATION OF THE ISSUE

Version 2.6.14

I try to update images with:
{
  "product": {
	"id": 431,
    "images": [{"id":281,"position":0}]
  }
}

It doesn't work. I always get the following old "images" in the answer:
"images":[{"id":401,"date_created":"2017-02-06T09:56:31","date_modified":"2017-02-06T09:56:31","src":"\/wp-content\/uploads\/2017\/02\/art_f5d2fd16-5bed-4a08-8037-fd56ead376fd-6.jpg","name":"art_f5d2fd16-5bed-4a08-8037-fd56ead376fd.jpg","alt":"","position":0}]

Also I can't delete product images with:
{
  "product": {
    "images": ""
  }
}

**Comment by mikejolley** [comment]
The JSON in those requests look invalid... Look at https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties again.

Example: https://dl.dropboxusercontent.com/s/7j571usxy5x0fyr/2017-02-06%20at%2015.27.png

**Comment by itphil** [comment]
Still it doesn't work:

{
      "images": 
	  {
	  "id":0,
	  "src":"/wp-content/uploads/2017/02/art_abf419a0-9db9-4852-a851-cba49ef1f0c4.jpg",
	  "position":0
	  }
  
}


Error:
{"code":"woocommerce_product_invalid_image_id","message":"#0 ist eine ung\u00fcltige Bild ID.","data":{"status":400}}

**Comment by itphil** [comment]
Sorry, I forgot [ ... ]

But how can I delete all assigned product images?

**Comment by itphil** [comment]
Thanks, now it work delete, too. Probably the my mistake was assiging the images via id and not src.
