### ISSUE TITLE
Partial shipment and backorder order management

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13097]
Allow orders to be partially shipped. Include shipment tracking?

**Comment by amjad** [comment]
@mikejolley, similar to Amazon?

**Comment by MattyLB** [comment]
This would definitely help me out when a customer orders items I fulfill and dropship/other vendor items in one purchase! I've been trying to find a workaround but having this option in core would save a few hairs I was about to pull out, lol.

Thanks for looking into this!

**Comment by carylwills** [comment]
I'd like to see this in core - I have the same issue, shipping some items from my warehouse and others being drop shipped by the manufacturer. I also need to handle back-orders.

**Comment by taikuli** [comment]
I'd also like to see this in core.
I'd like to see:
- Ask the user for partial or complete shipment at checkout (ship every item once it is available or ship all when all items are available) and have the option to add additional shipping cost for (every) partial shipment
- A customer friendly way to handle payments for items that not available right now (pay on availability vs pay in advance for all items)
- Option to add tracking details for every shipment

**Comment by UserName011** [comment]
In addition to @taikuli notes... I would be great if the user can select different shipping methods.
For example: Item A - Shipping method X 
                     Item B - Shipping method Y

**Comment by mikejolley** [comment]
It seems this issue was mixed up and confused with https://github.com/woocommerce/woocommerce/issues/11259 <-- We do intend on doing that one (new backorder stock status).

But as for partial order fulfilment we need some more feedback before tackling this in core and on WordPress.com. I don't have an ETA for inclusion and this issue has no planning or scope, so should be closed.

I believe the idea is here: http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/2946359-partial-shipment-with-backorder

If you'd like something like this, please vote there and add details about what would be needed. If we see enough demand and know what is needed we can revisit this in a future release and open a proper issue with everything involved.

Thanks everyone.
