### ISSUE TITLE
Sales scheduled for wrong time

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#13105]
## EXPLANATION OF THE ISSUE
If the WordPress timezone is set to any timezone in UTC+ the scheduled sales are scheduled for the wrong time.

## STEPS TO REPRODUCE THE ISSUE
1. Set the WordPress timezone to any timezone in UTC+ (Berlin in my testing)
2. Deactivate and then reactivate WooCommerce.
3. Using something like wp-crontrol, see that the `woocommerce_scheduled_sales` hook is scheduled not for midnight as expected, but rather 2:00AM

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://staging.hetwenshuisje.be
Site URL: http://staging.hetwenshuisje.be
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.13-0ubuntu0.16.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (5) ###

WooCommerce Composite Products: by WooThemes – 3.8.3
WooCommerce EU VAT Number: by WooThemes – 2.1.14
WooCommerce: by WooThemes – 2.6.14
Yoast SEO: by Team Yoast – 4.2.1
WP Crontrol: by John Blackbourn & Edward Dale – 1.4

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #2670 - /producten/
Cart: #5 - /winkelmandje/
Checkout: #6 - /afrekenen/
My Account: #7 - /mijn-account/

### Taxonomies ###

Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront
Version: 2.1.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

```

**Comment by mikejolley** [comment]
@WillBrubaker Not sure if you realise, but cron jobs run on server time. So the 2am you see in the cron view plugin is probably correct if Berlin time is 2 hours off your server time.

See here where GMT offset is accounted for https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-install.php#L295-L297

**Comment by gevasi** [comment]
@mikejolley Hi, I'm the one who noticed the issue and reported it to @WillBrubaker .
All my sites (staging and live) have this issue. 
The servers run on UTC time and timezone is +1 in winter and +2 in daylight savings time.
And the cronjobs only run at 2AM if I don't adjust the time with WP Crontrol. When I update woocommerce or deactivate and reactivate it gets set to 2AM again.
I asked if this was ment to be like that and he answered it should run at midnight in the timezone of the blog.
WPCrontrol also gives the time according to blog time, not UTC.
So when I leave it as is and check at 1:59 AM blogtime/my timezone nothing happened and at 2:01AM the cronjob did it's task which it was supposed to do at midnight blogtime.

I just ran a test on my staging site:
Setting blogtime to +4: cronjob sheduled at 8AM
Setting blogtime to +6: cronjob sheduled at 12PM
Setting blogtime to +7: cronjob sheduled at 2PM (14:00)
Setting blogtime to -1: cronjob sheduled at 0AM
Setting blogtime to -5: cronjob sheduled at 0AM

When the timezone is +UTC it always offsets the time with 2 times the UTC offset.

**Comment by MillerMedia** [comment]
Yes this is the function that sets up the scheduled sale:

wp_schedule_event( strtotime( '00:00 tomorrow ' . $ve . get_option( 'gmt_offset' ) . ' HOURS' ), 'daily', 'woocommerce_scheduled_sales' );

As you can see, it schedules the event to update the sale price to 12:00AM tomorrow for whatever timezone is set. It's 12AM to the timezone that's set the next day so you technically wouldn't be able to schedule a sale to start later in the same day.

**Comment by gevasi** [comment]
@MillerMedia : This issue was an actual bug in the code which only occured in GMT + timezones.
It was resolved by simply switching a + and a -
After this I haven't had any issues with the cronjobs anymore

**Comment by MillerMedia** [comment]
@gevasi What do you mean exactly by 'switching a + and a -', I'm not following?

**Comment by gevasi** [comment]
Well, this issue has been closed by Mike jolley and [here](https://github.com/woocommerce/woocommerce/commit/dd70417758b2f8f778ea4339017f5bd7a2836c43) you can see the fix that was implemented to solve it.

**Comment by MillerMedia** [comment]
This appears to have broken the - timezones though. We have done a bunch of research. I will open a new issue (or we can re-open this one). We have isolated it down to that exact line of code.

**Comment by MillerMedia** [comment]
This commit fixed the issue for the +GMT values but broke the scheduled sales for -GMT values. I would recommend it re-opened based on our research. Here are our notes so far:

A simple way to recreate:
• Set timezone to Los Angeles (-7 GMT)
• Deactivate WooCommerce (if it's active) and re-activate
• Check the value of when the scheduled sale will run next in the 'cron' option in wp_options (the action being woocommerce_scheduled_sales). You will find that the Unix timestamp will hold a value of 5PM today (if you've performed this before 5PM Los Angeles time).

What this is doing is actually taking midnight UTC time tomorrow and SUBTRACTING 7 hours to get 5PM today. This is wrong. We want it to run on midnight Los Angeles time which would mean taking midnight tomorrow UTC and adding 7 hours so it runs at UTC 7AM.

We switch the + and - back in the core to test and it worked great but presumably would break any +GMT values.

**Comment by MillerMedia** [comment]
I've updated the code and submitted a pull request here:
https://github.com/woocommerce/woocommerce/pull/16612

The fix appears to be that if we use an absolute value, it will properly evaluate. Details being:

In the event that you choose a -GMT value, the values are incorrect in some instances. For examples, if we choose a -7 GMT value, the gmt_offset will evaluate to '-7'.

On line 309, $ve will equal '+'.

On line 312, previously, $ve . get_option( 'gmt_offset' ) would evalute to '+-7'.
