### ISSUE TITLE
order totals are all 0.00

### ISSUE THREAD

**Issue by michael-lynch** [woocommerce/woocommerce#13111]
I created an order with a single line item using the API.

```
$order = $woocommerce->post('orders', [
    'line_items' => [
        [
            'product_id' => $productID,
            'quantity' => 1
        ]
    ]
]);
```

When I `get` the order, I can see the line item with the price I set in the dashboard, but the `total` is `0.00`. What am I missing?

**Comment by amjad** [comment]
try setting a status for the order as well. I think your totals are not being calculated.

**Comment by michael-lynch** [comment]
@amjad Yes, the `status` was required. Setting it to `pending` calculated the `total` and `total_tax`. Thanks for your help!

```
$order = $woocommerce->post('orders', [
    'line_items' => [
        [
            'status' => 'pending',
            'product_id' => $productID,
            'quantity' => 1
        ]
    ]
]);
```

**Comment by amjad** [comment]
👍🏻
