### ISSUE TITLE
Should Tax Price Display Suffix be displayed on tax free items?

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#13119]
## EXPLANATION OF THE ISSUE

I have a (Tax) Price Display Suffix of "inc. GST" set for my store. (WooCommerce > Settings > Tax > Tax Options)

I have a product with Tax status "None" -- and I expected the "inc. GST" suffix would NOT appear for that product, yet it still does.  This seems incorrect to me.

<img width="253" alt="screen shot 2017-02-08 at 11 15 44 am" src="https://cloud.githubusercontent.com/assets/1595739/22753156/fc310b92-edef-11e6-961f-1c99d402ec65.png">

## STEPS TO REPRODUCE THE ISSUE

Set WooCommerce > Settings > Tax > Tax Options > Price Display Suffix to "inc. GST"
Create a Product with Tax status of None
View that Product in the front end

## SYSTEM STATUS REPORT

N/A

**Comment by mikejolley** [comment]
I've always gone by this:

> Zero-rated means that the goods are still VAT-taxable but the rate of VAT you must charge your customers is 0%. You still have to record them in your VAT accounts and report them on your VAT Return.

https://www.gov.uk/vat-businesses/vat-rates

The $10 does include GST, at 0%. To me this makes it clear that further tax won't be added on later during checkout.

**Comment by allendav** [comment]
> Zero-rated means that the goods are still VAT-taxable but the rate of VAT you must charge your customers is 0%.

Wow. That's interesting logic the UK gov has there :)  Australia has GST, but they refer to non-taxable items (like some foodstuffs, for example) as "GST-Free"

https://www.ato.gov.au/Business/GST/In-detail/Your-industry/Food/GST-food-guide/

**Comment by mikejolley** [comment]
@allendav Thats not really a use case this can account for, because how would it know which tax class is 'free of vat'? Or how would it know thats a food item?

**Comment by allendav** [comment]
I meant not showing the suffix if is_taxable is false for the product

**Comment by mikejolley** [comment]
See #13158
