### ISSUE TITLE
Variable Product Drop Down on Front-End Auto-Loads in Alphabetical

### ISSUE THREAD

**Issue by ajarea10labs** [woocommerce/woocommerce#13110]
## EXPLANATION OF THE ISSUE

Currently building demo site for client to eventually transfer to current site. WordPress 4.7.2, Shopkeeper Theme 1.9.2, and WooCommerce 2.7.0.

I have set up products with attributes as Type- Text, Ordering - Custom Ordering, as in screenshot below: 
![image](https://cloud.githubusercontent.com/assets/25619563/22706618/91b10eda-ed35-11e6-8c99-78200c7414fc.png)

I have the variable terms configured in the order I would like them to appear in the drop-down on the front end, as in the screenshot below:
![image](https://cloud.githubusercontent.com/assets/25619563/22706681/c12daf10-ed35-11e6-9e6c-12cc1063b1f2.png)

I have the attributes set up in the order I would like them in the Product data, as in the screenshot below:
![image](https://cloud.githubusercontent.com/assets/25619563/22706730/f8e24d44-ed35-11e6-878c-5a6b089f0d6d.png)

They are configured properly in the Variations portion, as in....yep! the screenshot below:
![image](https://cloud.githubusercontent.com/assets/25619563/22706762/1c873962-ed36-11e6-88ad-02b8594454cc.png)

Yet they are ordered Alphabetically on the front-end:
![image](https://cloud.githubusercontent.com/assets/25619563/22706793/371c2a3a-ed36-11e6-8014-c300c10f986d.png)

I'm seriously confused, and probably missed something seriously simple somewhere. Any help is greatly appreciated! 

This is my first day with a GitHub account, and I'm just beginning in web design, so disclaimer on any noob problems. I'm not sure if it's a bug, or something I did. Might be a theme/WooCommerce issue?

**Comment by mikejolley** [comment]
@ajarea10labs Do a quick test on a default theme.

The order of the variations themselves does not affect the display on frontend. Ignore that.

The order of the ATTRIBUTES however does. So this should be it https://cloud.githubusercontent.com/assets/25619563/22706681/c12daf10-ed35-11e6-9e6c-12cc1063b1f2.png Drag and drop to reorder.

**Comment by mikejolley** [comment]
Please update this when you get a chance to test; I'm unable to replicate an issue myself.
