### ISSUE TITLE
Rest API server messing _GET content

### ISSUE THREAD

**Issue by hersoncruz** [woocommerce/woocommerce#13129]
## EXPLANATION OF THE ISSUE

Intermittently I'm getting one of two messages:

`Error: Sorry, you cannot list resources. [woocommerce_rest_cannot_view]`

or

`Syntax error`

If copy the url client code generates on request and paste it on browser's address bar, sometimes I get first message and sometimes get actual data from customers endpoint.

After struggling a lot trying to fix this on client side, started to debug server code and found that includes/api/class-wc-rest-authentication.php is messing around with $_GET content, specifically on perform_oauth_authentication function. Printing out $_GET content in that function I get:

`[oauth_consumer_key] => ck_373ca8e178c812c52007b1eade09c3eb61e64565`
`[amp;oauth_nonce] => 3d5fe4541e6edacd652d927f31857624c8448aaa`
`[amp;oauth_signature] => i3rGt15ZPpFq8migSZYeAlYHwFM2idH8bLxsVCGE/Pg=`
`[amp;oauth_signature_method] => HMAC-SHA256`
`[amp;oauth_timestamp] => 1486659987`
`[amp;role] => all`

And that function always returns false. Obviously the the 'amp;' string is making 

`if ( empty( $_GET[ $param ] ) ) {`

always true and inside that, there's a return false.

Question is: How can I prevent $_GET indexes getting 'amp;' at first?

Thanks for your help!

## STEPS TO REPRODUCE THE ISSUE

1. Setup customer_key and secret generated on Woocommerce -> Settings -> API.
2. Set credentials on client side. (I'm using Automattic\WooCommerce\Client from https://github.com/woocommerce/wc-api-php)
3. Write test client code to consume customers endpoint:

`
require_once(__DIR__ . '/vendor/autoload.php');
use Automattic\WooCommerce\Client;
		$options = array(
		'wp_api' => true,
	        'version' => 'wc/v1',
	        'ssl_verify'      => false,
	        'wp_api_prefix' => '/wp-json/',
	        'query_string_auth' => true,
		);
		
		try{
	        $this->wooClient = new Client(
		        $this->config->url,
		        $this->config->consumer_key,
		        $this->config->consumer_secret,
				$options
	        );
        } catch (HttpClientException $e) {
	        echo("<pre>");
	        echo($e->getMessage());
	        echo($e->getCode());
	        
	        if ($e instanceof HttpClientException ) {
		        print_r($e->getRequest());
				print_r($e->getResponse());
	        }
	        
	        exit;
        }

       return $this->wooClient->get('customers', array('role' => 'all'));
`

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://<site_name>.dev
Site URL: http://<site_name>.dev
WC Version: 2.6.13
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Unix) PHP/5.6.29
PHP Version: 5.6.29
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.51.0
SecureTransport

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging

### Database ###

WC Database Version: 2.6.13
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (26) ###

Gravity Forms: by rocketgenius – 2.1.2
Advanced Custom Fields PRO: by Elliot Condon – 5.5.5
Cornerstone: by Themeco – 1.3.3
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Google Analytics by MonsterInsights: by MonsterInsights – 5.5.4
Gravity Forms MailChimp Add-On: by rocketgenius – 4.1
Hide YouTube Related Videos: by SparkWeb Interactive
Inc. – 1.4.2

Jetpack by WordPress.com: by Automattic – 4.5
Log Error: by  –
Nav Menu Roles: by Kathy Darling – 1.8.6
OptinMonster API: by Thomas Griffin – 1.1.6.1
Page Links To: by Mark Jaquith – 2.9.6
Post Duplicator: by Metaphor Creations – 2.19
Simple 301 Redirects: by Scott Nellé – 1.07
Simple History: by Pär Thernström – 2.13
Soil: by Roots – 3.5.0
Wiild Cornerstone: by Wiild Interactive – 0.1.0
WooCommerce - Autocomplete Orders: by Serious Plugins – 1.1.4
WooCommerce Checkout Field Editor: by WooThemes – 1.5.1 – 1.5.2 is available
WooCommerce Dynamic Pricing: by Lucas Stark – 2.12.0 – 2.12.2 is available
WooCommerce Subscriptions: by Prospress Inc. – 2.1.1
WooCommerce: by WooThemes – 2.6.13
Sensei: by WooThemes – 1.9.11
WooCommerce Helper: by WooCommerce – 1.7.2
Yoast SEO: by Team Yoast – 4.1
WP Migrate DB Pro: by Delicious Brains – 1.7.1

### Settings ###

Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #6 - /programs/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My Account: #9 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### Theme ###

Name: Theme name
Version: 1.0.0
Author URL: http://example.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: sitename/woocommerce/global/quantity-input.php
sitename/woocommerce/global/wrapper-end.php version - is out of date. The core version is 1.6.4
sitename/woocommerce/global/wrapper-start.php version - is out of date. The core version is 1.6.4
sitename/woocommerce/single-product/product-image.php
sitename/woocommerce/single-product/tabs/tabs.php

: Learn how to update outdated templates
```

**Comment by claudiosanches** [comment]
You have two options.

1. stop encoding `&` into `&amp;`
2. make your server replace `&amp;` to `&`.

Note that this is not an issue on WooCommerce, it's an issue on your server.

**Comment by hersoncruz** [comment]
Thing is I'm not doing anything to encode those parameters, just using Woocommerce Rest API server and client code provided here: https://github.com/woocommerce/wc-api-php.
Do you have a clean way to: 

> make your server replace &amp; to &.

Regards,
