### ISSUE TITLE
Duplicate order_number

### ISSUE THREAD

**Issue by mathieug** [woocommerce/woocommerce#13122]
We received two orders at the same time, both orders has the same order_number.
We don't use any plugin for order numbers.

**Comment by mikejolley** [comment]
@mathieug if both orders are in the backend, you must be because it would be impossible for 2 posts (orders) to have the same ID in the database.

**Comment by mikejolley** [comment]
This issue needs more details and feedback before confirming if there is a bug. If the two orders do not exist in the DB (not clear from the report) it could have something to do with https://github.com/woocommerce/woocommerce/issues/12467 which will be dealt with separately. Feel free to respond here -you can still comment.

**Comment by mathieug** [comment]
It happens pretty often now, it seems to happen when the checkout are proceeded at the same time.

**Comment by mathieug** [comment]
Each time it happens, the ID (post) are different but the order number are the same.

**Comment by mikejolley** [comment]
Order number is not generated by WooCommerce. Order number is identical to order ID on a clean install.
