### ISSUE TITLE
Send an email to admin when a user registers via /my-account

### ISSUE THREAD

**Issue by ValeDeOro** [woocommerce/woocommerce#13125]
## EXPLANATION OF THE ISSUE

When a new user is created via Users >> Add new in the dashboard, an email is sent to both the new user and the store owner. 

When a store allows users to sign up independently from buying a product, via /my-account then the only email sent out is the one for the user. The store owner does not receive an email. 

## STEPS TO REPRODUCE THE ISSUE

Enable registration on the "My Account" page: 

![](http://cld.wthms.co/AiXJ/5U2UOfLW+)
Link to screenshot: http://cld.wthms.co/AiXJ/5U2UOfLW

Register as a user from the /my-account page

![](http://cld.wthms.co/jDzK/SaMj0yXN+)
Link to screenshot: http://cld.wthms.co/jDzK/SaMj0yXN

Check the email log:

![](http://cld.wthms.co/O5aM/1I1M6CHz+)
Link to screenshot: http://cld.wthms.co/O5aM/1I1M6CHz

**Comment by mikejolley** [comment]
I imagine this one could get pretty spammy on busy stores. I don't think it will be desired for majority - it's good to know when an order comes in of course, but not an account...

Here is a snippet anyhow - it's simple to implement if needed https://gist.github.com/mikejolley/4173a34fa7a6bd93d67f5a343886388e
