### ISSUE TITLE
[2.7] wc_get_products() with custom taxonomy

### ISSUE THREAD

**Issue by NTShop** [woocommerce/woocommerce#13138]
The wc_get_products() function is great, however it doesn't allow any way to query based on a custom taxonomy. That functionality should be added - before release if possible please.

**Comment by mikejolley** [comment]
I disagree with this. if you're registering a taxonomy in WordPress you are making a decision about a) the data, and b) the storage of that data. Terms are a WordPress thing. You're assuming that "products" will always be posts which may or may not be the case going forward.

If products every moved to a custom table for example, that link with "TERMS" would break - WooCommerce would not be managing that relationship nor handling the data.

Therefore this does not belong in wc_get_products which only covers data managed in the product data-store.

You could use the `include` param and pass product IDs you wish to retrieve, although this would involve pre-querying those relationships.

Anyhow, this is related to https://github.com/woocommerce/woocommerce/issues/12677 where we can access. This won't be in 2.7.

@justinshreve

**Comment by NTShop** [comment]
So in your case, since if I remember right you wrote the WC Brands plugin, how do you intend to handle that particular plugin's evolution since it's a custom taxonomy use case?

**Comment by NTShop** [comment]
As an example, there a site on Los Angeles that sells approximately 12,000 drums and drum parts to musicians all over the place. They use the brands taxonomy to let shoppers look at specific products based on maker. They use the regular product categories as way for organizing types, styles, materials, kits, hardware, etc. And they had all this built probably 3 years ago before any one said anything about possible disconnecting WC from CPTs and taxonomies. They're going to need a path forward (having alreaady spent thousands of bux on their existing site). That's just one site, how many have downloaded WC Brands to date (something to consider) and then there's a thousands that use custom taxonomies for various purposes.

Any suggestions for us developers who are bound to be hit with a lot of questions about this situation?

**Comment by mikejolley** [comment]
Brands could potentially be rolled into core or use attributes (@mattyza) but it is not going to break until products are moved to custom tables if that happens.

But even if you were ever forced to switch to regular categories for this, literally everything you just mentioned is still possible.

**Comment by NTShop** [comment]
Brands was only a minor simple example. Rolling brands into the core helps you since you have direct control over core, but it doesn't help others who now use custom taxonomies because of these reasons: Blends easily and naturally into the WP architecture, They lend themselves to searches easily, They lend themselves to custom page templates easily via WP template hierarchy, They lend themselves to diverse types of organizing products for various uses cases - in other words it's a complete leveraging of the WP content management system (that big "selling" point of WP in general). So what I was asking is how you'd suggest people address that issue (custom taxonomy use) given that countless sites were custom built around the concept of products being a WP CPT and all of its benefits long before anyone mentioned that products may become architected some other way? (In other words, they aren't to blame for using custom taxonomies, they were sold on it by developers who might possibly be blind-sided in upcoming versions of WC).

**Comment by mikejolley** [comment]
You're talking about distant future now - clearly if the decision was made to move them out of posts, some WordPress things like taxonomies and templates would not work in the same way. That would be a drawback. But it depends whats more important..that or performance. These options would be weighed against each other before things change.

Products would need built in 'taxonomies' that would be supported even after that - categories, maybe tags, attributes. How they would be stored I cannot say but they would need to stick around since they are important parts of the product system.

Continue to use taxonomies for now. You'll have plenty of time to deal with the above if it happens. Personally, for products specifically I'm swaying towards a 'flat meta' approach so that posts are still used, but meta data is more performant. With that outcome, taxonomies stick around.

The issue I referenced is also related, so you can track how that progresses.

**Comment by NTShop** [comment]
I think what you suggested would be a good approach - leave the products as a CPT and move the meta out of postmeta (which is notoriously slow when there are a lot of records, or any one particular record has a huge amount of data in the value field).
