### ISSUE TITLE
[2.7] No Backward Compatibility for Many Deprecated Hooks

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#13132]
## EXPLANATION OF THE ISSUE

There are many deprecated hooks in WC 2.7 that will no longer be triggered, breaking backward compatibility with any code that has not been updated to use new 2.7 hooks.

Any hooks called in a deprecated function are affected, because the deprecated function still needs to be called in order for the hook to be triggered. Core doesn't call these functions anymore, nor will 3rd party code which has been updated for 2.7, meaning the hooks won't be triggered.

For example:

1. the `WC_Abstract_Order::add_shipping()` method has been deprecated in favour of using `WC_Abstract_Order::add_item()`
2. `add_shipping()` triggers the `'woocommerce_order_add_shipping'` hook
3. Although `WC_Abstract_Legacy_Order::add_shipping()` will make sure `'woocommerce_order_add_shipping'` is still triggered, it will only do so when `add_shipping()` is actually called on an instance of `WC_Order`
4. Neither core nor updated 3rd party code will ever call `add_shipping()`
5. The `'woocommerce_order_add_shipping'` hook will never be triggered
6. Any 3rd party code attached to the `'woocommerce_order_add_shipping'` hook will never run
7. The deprecated hook notice also won't be displayed, meaning the 3rd party code won't even know it's using the wrong hook. It will just silently fail.

That's just one of many examples of broken hooks.

Not triggering these hooks has the potential to break a huge amount of functionality from 3rd party code. Silently failing will make diagnosing the cause very difficult, and time consuming, for support ninjas and developers.

#### EXAMPLE SOLUTION

We faced a similar issue when we deprecated a lot of hooks with Subscriptions 2.0. We mapped old hooks to new ones via a base [hook deprecator class](https://github.com/Prospress/woocommerce-subscriptions/blob/master/includes/abstracts/abstract-wcs-hook-deprecator.php) that was extended for different types of hooks, like [filters](https://github.com/Prospress/woocommerce-subscriptions/blob/master/includes/deprecated/class-wcs-filter-deprecator.php) and even [actions with variable names](https://github.com/Prospress/woocommerce-subscriptions/blob/master/includes/deprecated/class-wcs-dynamic-action-deprecator.php). That way, the old functions didn't need to be called for the old hook to also be called and a deprecated notice to be logged or displayed.

Manually mapping all the old hooks to new ones takes a lot of work, but it saves breaking stores running code that hadn't been updated. The number of stores running WooCommerce is an order of magnitude higher than Subscriptions, making the impact of this issue in WC core far worse than it was in Subscriptions, and the work required to address it far more worthwhile.

## STEPS TO REPRODUCE THE ISSUE

On a store running WooCommerce < 2.7:

1. Copy & paste the snippet below somewhere to run on the site
1. Go to **WooCommerce > Edit Order**
1. Click **Add Item(s)**
1. Click **Add Shipping Cost**
1. Notice that an entry is added to the error log

Repeat these steps on a site with WC 2.7 active. No entry is added to the error log, because `'woocommerce_order_add_shipping` is never triggered.

Test snippet: 

```
function eg_log_shipping_hook( $order_id, $item_id, $shipping_rate ) {
	error_log( 'In ' . __METHOD__ . '() for order ' . $order_id . ' with item ' . $item_id . ' $shipping_rate = ' . print_r( $shipping_rate, true ) );
}
add_action( 'woocommerce_order_add_shipping', 'eg_log_shipping_hook', 10, 3 );
```

**Comment by mikejolley** [comment]
@thenbrent Are you suggesting we move the calls to the deprecated hooks to the replacement methods (add item) and somehow generate the 'old' args passed to the older hooks?

**Comment by thenbrent** [comment]
> move the calls to the deprecated hooks to the replacement methods (add item)

@mikejolley That's not necessary. The calls to deprecated hooks can be triggered from a callback attached to the new hooks instead. That's [what we did with Subscriptions 2.0](https://github.com/Prospress/woocommerce-subscriptions/blob/master/includes/abstracts/abstract-wcs-hook-deprecator.php#L28:L32). That avoids littering the new code with legacy/deprecated hooks, but still maintains backward compatibility (assuming there is a new hook that is triggered at equivalent time to the old hook).

> somehow generate the 'old' args passed to the older hooks?

Yeah, that's (one of) the hard parts. The old and new args needs to be mapped. Which in the case of WC 2.7 & CRUD, where often IDs aren't available on the new hooks, that will be at best tricky to do, and at worst impossible to do if the hook is called at the same time.

I can help with this once I get Subscriptions 2.7 compatibility committed. It's not easy or fun work, but it helps maintain backward compatibility.

**Comment by DavidAnderson684** [comment]
Related: there appear to be hooks which have kept the same names, but changed arguments. It'd be great if a list of these was catalogued somewhere, so that developers can pro-actively fix them, instead of guessing / waiting for weird failures etc.

WC 2.7:

`do_action( 'woocommerce_checkout_order_processed', $order, $posted_data );`

WC 2.6:

`do_action( 'woocommerce_checkout_order_processed', $order_id, $this->posted );`

**Comment by mikejolley** [comment]
I think we can fire those actions manually during SAVE rather than add, like we did for the add item meta hooks. These ones must have just been overlooked when we did the migration to `add_item`

@DavidAnderson684 I'll look at that one separately thanks.
