### ISSUE TITLE
wc_get_coupons() in wc-coupon-functions.php

### ISSUE THREAD

**Issue by NTShop** [woocommerce/woocommerce#13137]
We need a way to query coupons similar to the wc_get_orders() - including the ability to use query args related to standard "postmeta" (property) keys as well as custom keys.  In WC 2.6 and prior this isn't an issue since WP_Query can be used directly, however in prepping for the future, in WC 2.7 there's no such function wrapper. 

Certainly extension devs could write our own code, but it seems far more sensible to have it in the WC core so that devs don't have to go back and rewrite their plugin code later.

**Comment by mikejolley** [comment]
This is another relating to https://github.com/woocommerce/woocommerce/issues/12677

Coupons are a little different because of the way they work, typically getting a list of coupons is not required. It's not like we display them anywhere in list format.

We do support retrieval by code and ID https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-coupon-data-store-cpt.php#L276-L305 and they can be listed using the REST API.

> Certainly extension devs could write our own code, but it seems far more sensible to have it in the WC core so that devs don't have to go back and rewrite their plugin code later.

Actual use case?

**Comment by NTShop** [comment]
We've built several custom coupon plugins for WC sites that use them for automatic coupon creation/issuance for people who earn them sort of like loyalty stuff, and those coupons get listed on various  customer's My Account page. There's usually custom meta associated with a coupon like that (tracking the order # that triggered a need to issue the coupon) so for example if someone's purchase is later refunded or put on hold (dispute) etc then there may be a need to temporarily or permanently remove the coupon depending on the situation. There's also another use case where certain people create those coupons via the front end (custom form) and then use for various marketing purposes - again those are tracked with some custom meta and listed on the front end. There are some other use cases as well - for example custom tools that export all coupons or a subset of coupons in to CSV for offline use in 3rd party marketing/analysis packages, and other cases.

**Comment by mikejolley** [comment]
Coupons support meta data - perhaps the REST API is a good way forward since that data is standard and separate from storage?

**Comment by NTShop** [comment]
Are you saying coupons can be queried based on meta data via the API ? The docs aren't clear about that. 

https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#retrieve-a-coupon

**Comment by mikejolley** [comment]
Meta won't be supported until the next release.

**Comment by mikejolley** [comment]
Part of https://github.com/woocommerce/woocommerce/issues/13137
