### ISSUE TITLE
Reports are missing values

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#13143]
## EXPLANATION OF THE ISSUE

Here are all the orders for the 3rd of February 2017

![image](https://cloud.githubusercontent.com/assets/1001935/22822850/5e9da9ec-ef81-11e6-82bb-039c647a9482.png)

When I add all these orders together, we reach the total of **27380**

![image](https://cloud.githubusercontent.com/assets/1001935/22822778/10ca504e-ef81-11e6-89da-75445c155440.png)

When I go to reports and narrow it down to the 3rd of February 2017, the order total for this day is only **26976**

There is, ironically, 404,- missing from the report.

![image](https://cloud.githubusercontent.com/assets/1001935/22822897/a688b12a-ef81-11e6-8963-e2c55cb758fb.png)

Any idea where this value could get lost?

**Comment by mikejolley** [comment]
Order status? Refunds? Narrow your result set or look at the values it's getting in the report class (disable cache, log the sql query results).

**Comment by yratof** [comment]
You can see all the orders from that day though in the screenshot, it covers all refunds, zero orders, everything – and it doesn't add up at all

**Comment by mikejolley** [comment]
I cannot see statuses, and I cannot see what type of refunds i.e full or partial.

**Comment by yratof** [comment]
Full refund for the 1 refund (report says 2 though) and all say complete... is there a method that I can use to show you this information without releasing customer details on a public forum?

**Comment by mikejolley** [comment]
How were the refunds performed? Try saving the orders again to clear caches. And make sure if the status is refunded, there are refund lines showing the correct totals.

**Comment by mikejolley** [comment]
Open issues like this bug me. @yratof any feedback?

**Comment by yratof** [comment]
Klarna performs the refund & changes the status for the orders:

Looking deeper into this, i've gone through all the orders to check what madness is going on.

The order list, listed by date, gives all orders when they started their life. However, the reports give reports based on what happened on a certain day. I think this is where the problem can be highlighted.

Refunds for the 3rd on the report show 1 783,- which when filtering refunds by that date, I only get a total of 1199,-. Checking the different gives me 584,- missing – searching through the orders for a refund of this amount and I find an order for that amount:

![image](https://cloud.githubusercontent.com/assets/1001935/22883558/04c39f18-f1f1-11e6-9bb7-61b7e6b9246c.png)

Looking at the order notes for this order and we can see that the refund took place on the 3rd, which the report has managed to see:

![image](https://cloud.githubusercontent.com/assets/1001935/22883593/2870f44c-f1f1-11e6-92e2-b7ed1a09ab2c.png)

This means that the product list doesn't take into consideration events that happen to orders, hence, when a refund is given, the order can still remain 4 months ago etc.

Thinking of a solution, if it's not the reports that are wrong, it's the order list. When the report says "There were two refunds on this date" and I search for that date, all the information mis-matches, how do I find those two refunds without having to go through every order refund looking for values and dates. Luckily, there's only two refunds on this example, but I can imagine if there are 10-20 refunds, it becomes so much harder to trace

### Scenario to recreate
I look a the report for 03feb and it shows "There were 2 refunds" – Lets check what those refunds where: 

![image](https://cloud.githubusercontent.com/assets/1001935/22883376/47e3cd3c-f1f0-11e6-8cb3-5b2227f43796.png)

Client then thinks – "Ok, so the filter for the order in refund shows only one product?? Has there been a mistake or error by our system? Has a customer been refunded without us knowing?!"

**Comment by mikejolley** [comment]
Ah of course. Reports only add up refunds and orders from your date_rate so the correct values are shown in your period.

The order list shows the total overall, not for your custom date range. The order list date filter does not filter out refunds from other periods, that wouldn't make much sense because you're a) filtering a list of orders, not doing reports, and b) we have no display for JUST refunds.

So bug this is not, but if you have ideas for somewhere to 'say' this (reports page?) I'm happy to add some text.

**Comment by yratof** [comment]
Hmm ok, I'd still say that if an order is refunded, it's still an order & a significant event for your shop. 

Clicking "Refunds" on the orders page filters by order_status refund, I'd say that was the display for refunds – Is there a filter to change the order date to status change date? Or add a column for date the status last changed that can toggle or something similar?

Which brings me to the current build of WC, what's the solution for finding out the 2 refunds for that date without any modification to core? Is it just a case of "you can't see those items"?

**Comment by mikejolley** [comment]
> Clicking "Refunds" on the orders page filters by order_status refund,

Note this will only show orders fully refunded. Partial refunds are not represented.

> Which brings me to the current build of WC, what's the solution for finding out the 2 refunds for that date without any modification to core? Is it just a case of "you can't see those items"?

Since there is no dedicated view for refunds, you cannot get that kind of view.
