### ISSUE TITLE
Don't rtlcss the select2.css file

### ISSUE THREAD

**Issue by rellect** [woocommerce/woocommerce#13148]
## EXPLANATION OF THE ISSUE

The grunt rtlcss task is needlessly processing the select2.css file. The select2.css is already rtl ready, so running the rtlcss on it actually causes to bugs. (the built-in rtl css being flipped to ltr css)
Tested on wc2.7.0 beta2

**Comment by claudiulodro** [comment]
See #13150.

**Comment by rellect** [comment]
Hi,
The issue still exists, but this is due to another thing about how select2 being used. I'll open a separate issue for that.
