### ISSUE TITLE
Insecure script been loaded on SSL

### ISSUE THREAD

**Issue by leandrosunrise** [woocommerce/woocommerce#13149]
## EXPLANATION OF THE ISSUE

what happened : javascript stops execution so all the javascript on the website because unresponsive
version : I tested on version 2.5 and the latest version 2.6.14
conditions: accessing the website through ssl the browser reports that it has blocked insecure content insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.

## STEPS TO REPRODUCE THE ISSUE

      This happens when accessing a website through ssl 

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: http://aws.sunriseintegration.com/wordpress
Site URL: http://aws.sunriseintegration.com/wordpress
WC Version: 2.5.5
Log Directory Writable: ✕ To allow logging
make /var/www/html/wordpress/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.16 (Amazon) OpenSSL/1.0.1k-fips PHP/5.6.21
PHP Version: 5.6.21
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (3) ###

Form Maker: by WebDorado – 1.9.10
Campaign Monitor: by Campaign Monitor – 2.5.1
WooCommerce: by WooThemes – 2.5.5

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #4 - /index.php/shop/
Cart: #5 - /index.php/cart/
Checkout: #6 - /index.php/checkout/
My Account: #7 - /index.php/my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Sixteen
Version: 1.2 – 1.3 is available
Author URL: https://wordpress.org/
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Not a WooCommerce issue. You have a hardcoded jquery script in your site's header going to google apis.

Remove this ideally and use the WordPress version of jquery, or update the URL to https. Also, it's best to serve the entire site over https IMO and change the site/general URLs.

**Comment by leandrosunrise** [comment]
Nope! the website I tested doesnt have any plugins and when I deactivate the plugin everything works fine

**Comment by mikejolley** [comment]
Well I can see 'form maker' plugin is enabled so try again :)

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/oi4nzp11vhnsopo/2017-02-10%20at%2018.19.png

**Comment by leandrosunrise** [comment]
`
### WordPress Environment ###

Home URL: http://aws.sunriseintegration.com/wordpress
Site URL: http://aws.sunriseintegration.com/wordpress
WC Version: 2.6.14
Log Directory Writable: ❌ To allow logging
make /var/www/html/wordpress/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 4.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.16 (Amazon) OpenSSL/1.0.1k-fips PHP/5.6.21
PHP Version: 5.6.21
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.40.0
NSS/3.19.1 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (2) ###

Campaign Monitor: by Campaign Monitor – 2.5.1
WooCommerce: by WooThemes – 2.6.14

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /index.php/shop/
Cart: #5 - /index.php/cart/
Checkout: #6 - /index.php/checkout/
My Account: #7 - /index.php/my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Sixteen
Version: 1.2 – 1.3 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by leandrosunrise** [comment]
I installed the new version and let one plugin enable when I disabled woocomerce all works fine

**Comment by leandrosunrise** [comment]
it seem like something in your plugin is trying to add some google map but it only happens when other plugins are enable

**Comment by mikejolley** [comment]
WooCommerce does not use jquery from googleapis or google maps. Perhaps you have an extension or code which detects and only runs when WooCommerce is on.

**Comment by mikejolley** [comment]
Here is your proof https://dl.dropboxusercontent.com/s/ttfa9bpeuuhhurl/2017-02-10%20at%2018.28.png

**Comment by leandrosunrise** [comment]
I see is that form plugin. Thanks
