### ISSUE TITLE
$product->product_type returns "simple" for variable product

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce#13142]
## EXPLANATION OF THE ISSUE

On the current master branch, accessing the `product_type` property gives different results from calling `get_type()` for variable products. 

## STEPS TO REPRODUCE THE ISSUE

Replace 496 with a variable product ID from your test system. 

```bash
$ wp shell
wp> $p = wc_get_product(496);
=> object(WC_Product_Variable)#11716 (16) {
[Output trimmed out]
}
wp> $p->product_type
=> string(6) "simple"
wp> $p->get_type()
=> string(8) "variable"
```

Confirmed in beta-1, beta-2 and current MASTER branch.

**Comment by mikejolley** [comment]
See #13177
