### ISSUE TITLE
I'am using WooCommerce 2.6.14 and I'am having issues with the category image border/container dimensions. The dimensions of one product  height is a few pixels greater than the the product height of the other. Can someone help with this issue?

### ISSUE THREAD

**Issue by VictorJMcCoy** [woocommerce/woocommerce#13154]
## EXPLANATION OF THE ISSUE

I'am using WooCommerce 2.6.14 and I'am having issues with the category image border/container dimensions. The dimensions of one product height is a few pixels greater than the the product height of the other. Can someone help with this issue?

## STEPS TO REPRODUCE THE ISSUE

When I add an image to the product section it looks correct. When it is displayed along with a group of products the dimensions are not correct.

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://stonemountainltd.com
Site URL: http://stonemountainltd.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (24) ###

LayerSlider WP: by Kreatura Media – 5.6.6
Banner Management for WooCommerce: by Multidots – 1.0.3
Contact Form 7: by Takayuki Miyoshi – 4.6.1
cPanel & WHM® Site Software: by cPanel
Inc. – 1.0

Customize Woocommerce Shop: by RepUPress.com – 6.0
Fusion Core: by ThemeFusion – 2.0.3
GTranslate: by Edvard Ananyan – 2.8.10
Landing Pages: by Inbound Now – 2.4.3
MailChimp for WooCommerce: by MailChimp – 1.0.9
Product CSV Import Export (BASIC): by HikeForce – 1.2.3
Slider Revolution: by ThemePunch – 5.2.5
Typekit Fonts for WordPress: by OM4 – 1.8.3
WC Simple Product Badge: by Designs 4 The Web – 1.1
Woo Shop Hover Effects: by Rameez – 2.0
WooCommerce Product Custom Options Pro: by Phoeniixx Team – 2.1.3
Woocommerce Image Zoom: by wpbean – 1.01
WooCommerce Product Categories Selection: by PluginForage.com – 2.0
WooCommerce: by WooThemes – 2.6.14
WooCommerce Custom Tab Manager premium: by Phoeniixx Team – 1.5
WP All Import: by Soflyy – 3.4.0
WP Edit: by Josh Lobe – 4.0
WP Google Fonts: by Noah Kagan – v3.1.4
WP Overlays: by flippercode – 1.0.1
Zendesk Chat Widget: by Zopim – 1.4.6

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #366 - /shop/
Cart: #367 - /cart/
Checkout: #368 - /checkout/
My Account: #369 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Avada
Version: 4.0.3
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 2.6.3
Avada/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 2.6.3
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

: Learn how to update outdated templates
`
```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
They need to be hard cropped to be the same size in the catalog.

Please have a read of https://docs.woocommerce.com/document/adding-product-images-and-galleries/#section-6 since this isn't a bug in WooCommerce, but an issue with your images.

**Comment by VictorJMcCoy** [comment]
Thanks you!

 

Victor
