### ISSUE TITLE
Lazy Update Products

### ISSUE THREAD

**Issue by spencerfinnell** [woocommerce/woocommerce#13157]
## EXPLANATION OF THE ISSUE

Updating a single aspect of a product causes the entire product update routine to run.

## STEPS TO REPRODUCE THE ISSUE

```php
$product = wc_get_product( 1 );
$product->set_props( array(
  'weight' => 2
) );
$product->save();
```

### Discussion

Related #12802

https://github.com/woocommerce/woocommerce/issues/12802#issuecomment-279097454

This was dealt with partially with https://github.com/woocommerce/woocommerce/blob/094b86c92b8d483c288fa7c0f2c50c1b403417c5/includes/data-stores/class-wc-data-store-wp.php#L174 which only updates props that have changed.

However a similar implementation needs to be done for the post object (to avoid `wp_update_post()` calls when undeeded), as well as various term changes. 

Perhaps some `get_term_changes()`, `get_object_changes()`, etc for datastores that extend the `WC_Data_Store_WP` so the actual update calls are only used when needed.

**Comment by mikejolley** [comment]
See #13164
