### ISSUE TITLE
select2.css shouldn't be bundled inside admin.scss

### ISSUE THREAD

**Issue by rellect** [woocommerce/woocommerce#13153]
## EXPLANATION OF THE ISSUE

Currently select2.css is bundled inside admin.scss, which is wrong.
```
/**
 * Imports
 */
@import 'bourbon';
@import 'mixins';
@import 'variables';
@import 'animation';
@import 'select2';
@import 'fonts';
```

This causes bugs regarding select2 in rtl, because admin.css is processed in rtlcss task (see #13148).

Tested in wc2.7.0 beta2

**Comment by claudiulodro** [comment]
Good call. See #13155.
