### ISSUE TITLE
'Orders' do not fire calculate_fees() like 'Carts' do

### ISSUE THREAD

**Issue by gmo81** [woocommerce/woocommerce#13166]
### ISSUE
When using a 'Cart', there is an opportunity for developers, at checkout, to calculate specific fees, based for example, on payment type.

As an example, if someone pays by credit card, an additional fee may need to be added.

There may also be discounts for paying by certain methods, to encourage customers to use a certain preferred payment method.

This works well with various plugins, when the user is adding items to their own cart, and checking out. We have tried several plugins for this capability.

However, we found that when we create a manual order (and we have some reasons we need to do this from time to time), we have found these payment fees or discounts are not applied by ANY of these plugins that we have tried.

Drilling down on this further... we started looking at the code for these plugins and WooCommerce itself (and further investigation may be necessary) - but what we first see is this...

The plugins seem to rely on ‘calculate_fees()’ being fired by WooCommerce, which happens when a regular cart is used, per:

https://docs.woocommerce.com/wc-apidocs/class-WC_Cart.html

However, if someone adds an ‘order’ to WooCommerce, as an administrator, with custom pricing that a customer can then go and pay for (in their orders -> pay), these plugins don’t work at checkout.

I believe a key reason is that WC-Order comes down to there being no calculate_fees() method for orders, and therefore said plugins do not get triggered to do any final fee calculation for a cart (including things like adding for example a 1.5% extra for paying by credit card), as this code never fires in the instance of an 'order' being paid.

You can see there is no calculate_fees() in your docs - https://docs.woocommerce.com/wc-apidocs/class-WC_Order.html

Given there is no calculation of fees fired for orders made in this way, and effects multiple plugins - it seems to me that this might come down to a fundamental woocommerce issue that, if solved, would fix many plugins that break (as they depend on calculate_fees() firing).

## VERSION
WooCommerce 2.6.14

## STEPS TO REPRODUCE THE ISSUE
Add a plugin for calculating fees based on payment, for example  "WooCommerce discounts Per Payment Method" (https://en-au.wordpress.org/plugins/woocommerce-payment-discounts/), or "Payment Gateway Based Fees and Discounts for WooCommerce" (https://en-au.wordpress.org/plugins/checkout-fees-for-woocommerce/) - or any other similar plugin.

Create an order, add some item, calculate taxes, totals, assign it to a customer and save the order

Login as the customer, click on your account -> Orders

On the specific order, click "Pay"

Checkout, choose a payment method with a fee or discount - and you will note the price does not update.

### EXPECTATION

Fee or discount, due to payment method at checkout, is applied, the same way it is when a user creates their own cart of items.

### WordPress Environment ###

Home URL: http://[hidden]
Site URL: http://[hidden]
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (24) ###

BackWPup: by Inpsyde GmbH – 3.3.4
CB Change Mail Sender: by Md Abul Bashar – 1.1
Contact Form 7: by Takayuki Miyoshi – 4.6.1
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
Easy Twitter Feed Widget: by DesignOrbital.com – 0.6
Edwiser Bridge Single Sign On: by WisdmLabs – 1.2
Edwiser Bridge - WordPress Moodle LMS Integration: by WisdmLabs – 1.2.1
Bulk Purchase: by WisdmLabs
India – 1.0.2

Insert Pages: by Paul Ryan – 3.1.8
Minimum Password Strength: by Will Anderson and Tony Ferrell – 1.2.0
Meta Slider: by Matcha Labs – 3.4.1
MOJO Marketplace: by Mike Hansen – 1.1.0
Password Strength for WooCommerce: by Potent Plugins – 1.0.1
Selective Synchronization: by WisdmLabs – 1.1.0
ShortCode Redirect: by Cartpauj – 1.0.02
Sign Me Up: by Jaromy Russo – 1.5.1
Smart Manager: by StoreApps – 3.9.21
Stripe WooCommerce Addon: by Syed Nazrul Hassan – 1.0.8
Woo Payment Discounts: by WPCodelibrary – 1.0.2
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce Integration: by WisdmLabs – 1.1.3
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.39
WooCommerce: by WooThemes – 2.6.14
WP Fastest Cache: by Emre Vona – 0.8.6.5

### Settings ###

Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #8 - /index.php/shop/
Cart: #9 - /index.php/cart/
Checkout: #10 - /index.php/checkout/
My Account: #11 - /index.php/account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Vogue
Version: 10.2.8
Author URL: https://kairaweb.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by fmendoza** [comment]
Same here. Any help please?

**Comment by mikejolley** [comment]
calculate_fees is a cart only function. For orders, fees can be added directly as they are just a type of line item. This can be done with code (hook into the actions for creating orders), via the REST API, or manually.

As for the pay page, this currently does not work the same way as the 'cart'. This won't be resolved until https://github.com/woocommerce/woocommerce/issues/10672 - there is already an item in this issue about making the pay page use the regular checkout page which is what you're asking for here.

**Comment by gmo81** [comment]
Correct, calculate_fees is a cart only option.

That's precisely the problem.

Yes you can create fees, manually - at order creation time, or perhaps even automated at order creation time.

But - you cannot determine how a customer will pay at that time, and therefore you cannot calculate fees based on their decision - you have no control over that decision they make right as they are making the payment itself.

Although I agree that a long term fix is to make the checkout identical for an order as it is a cart, it seems that is being treated as an epic issue, and has been bumped from 2.7 to WooCommerce 3.0, but from my reading, I'm not sure that work has commenced on that, or any idea of timeframe for when that may become available.

As such, is there a shorter term solution to enable fee calculation, for orders, at checkout that can be put together? Otherwise we are doing things manually and relying on the honour system.

**Comment by mikejolley** [comment]
Not really, the pay page does not allow it in the current form, and it doesn't make much sense to redo that before the other future changes (we'll have to do it twice then).
