### ISSUE TITLE
Hook performance issue / deprecated hook check

### ISSUE THREAD

**Issue by ricemann** [woocommerce/woocommerce#13163]
I have noticed that woocommerce source code checks every single filter if it has a wrong name to raise a deprecated notice. You handle this in a more efficient way. 

With a small site it is no problem but when you have a lot of trafic it's bad. Maybe it only runs during debug (i am not sure). 

And when doing development with a step debugger - it is pain to step out each time - the code enters a hook. 

But if you just search for woocommerce if this sting is present you can start doing your check or leave early. 
I hope you will handle this matter.

Best Regards Thomas Riis

**Comment by mikejolley** [comment]
What code are you talking about @ricemann? Surely if you're checking the name for 'woocommerce' that will run in the same place as checking against a list of names, so that code will still run on every hook?

**Comment by mikejolley** [comment]
What you describe does not exist. The deprecated filters handler does not hook into ALL filters, just those which ARE deprecated.

https://github.com/woocommerce/woocommerce/blob/master/includes/wc-deprecated-functions.php#L616-L618
