### ISSUE TITLE
Superfluous index on wp_woocommerce_tax_rate_locations table

### ISSUE THREAD

**Issue by arjenlentz** [woocommerce/woocommerce#13162]
## EXPLANATION OF THE ISSUE

The current definition of the woocommerce tax rate locations table (in the 2.7 master branch) is:

CREATE TABLE {$wpdb->prefix}woocommerce_tax_rate_locations (
  location_id bigint(20) NOT NULL auto_increment,
  location_code varchar(255) NOT NULL,
  tax_rate_id bigint(20) NOT NULL,
  location_type varchar(40) NOT NULL,
  PRIMARY KEY  (location_id),
  KEY tax_rate_id (tax_rate_id),
  KEY location_type (location_type),
  KEY location_type_code (location_type(40),location_code(90))
) $collate;

We see that location_type is the first column in two indexes. Admittedly the second instance is technically a prefix index (only the first 40 characters are indexed), but the actual column definition is also VARCHAR(40) so actually that 40 character prefix is the entire column length.
Either way, the location_type index is superfluous. It can be removed without any impact other than saving some disk space.

Note that even if the column definition was longer, the 40 long prefix would be quite selective already and thus work as well as the separate index. The server would just use either index arbitrarily, and always pick the location_type_code indexes if the location_code column were specified in the WHERE clause.
Naturally, the story would be different if location_type were UNIQUE. Then it would serve a purpose. But that's not what we want here.

**Comment by mikejolley** [comment]
See #13176
