### ISSUE TITLE
Change from BIGINT to BIGINT UNSIGNED

### ISSUE THREAD

**Issue by arjenlentz** [woocommerce/woocommerce#13160]
## EXPLANATION OF THE ISSUE

From conversation with Matty Cohen, a selection of structural improvement suggestions, for performance and future-proofing.

INTEGER (INT, BIGINT) columns should be defined as UNSIGNED, unless negative values are required. Unfortunately the SQL standard defaults to SIGNED.

Having an auto-inc column signed halves its range. Granted the BIGINT range is massive, however in multi-master and Galera clustered environments we may see a much more rapid increase in used auto-increment values anyhow. It'll be good to prepare for this. And just because it's good practice.

Change /includes/class-wc-install.php to use BIGINT UNSIGNED for all auto-inc columns rather than BIGINT(20).
Please note also that the (20) is meaningless; yes the server will add some value for that, but it doesn't actually serve a practical purpose - it used to define output width for a certain text console interface, but it does nothing in the server or when using the usual client library (or PHP/mysqlng).

Mind that when doing joins, only matching column types are able to use indexed lookups, so it's important that all foreign key references to auto-inc columns are also changed to BIGINT UNSIGNED.

Recent versions of MySQL and MariaDB have "fast" ALTER TABLE, which allows us to modify aspects of column types in-place: the server will only change the schema frm file and InnoDB dictionary, it does not have to copy/rewrite the entire table. Changes such as signed to unsigned can be done with this fast logic, so if an upgrade function checks for the existing column types used in the schema on the server, it can actually do ALTER TABLE (if necessary) without causing grief even on a server that has lots of data.

**Comment by mikejolley** [comment]
Pretty sure dbdelta will update this for us if we simply switch it out, but I'll do some testing local to make sure it happens.

**Comment by mikejolley** [comment]
See #13176
