### ISSUE TITLE
"Sorry, no products matched your selection" popup after adding variations dropdown directly on shop page.

### ISSUE THREAD

**Issue by ThoughtPhotography** [woocommerce/woocommerce#13165]
All of my products have one variation (weight), and requiring customers to navigate to individual pages is an unnecessary step I really want to avoid (this seems to be a very common request going back years).

I was able to achieve the desired result by adding the following two lines to my child themes functions.php file, but now I get a very annoying modal popup saying "Sorry, no products matched your selection. Please choose a different combination.".
```

/* Add variations dropdown to shop page  */

remove_action( 'woocommerce_after_shop_loop_item', 'woocommerce_template_loop_add_to_cart', 10 );
add_action( 'woocommerce_after_shop_loop_item', 'woocommerce_template_single_add_to_cart', 30 );
```

I believe this is occurring because not every product is in stock. I'd love to find a way to remove this popup entirely, as aside from being a nuisance it prevents proper page loading (CSS animations etc.) until clicked.

Does anyone know a way to fix this?

Thanks, 
Ryan

P.S.There's not a user in the world that likes his or her whole browser hijacked by a popup. My specific issue aside, this is a terrible solution to a minor issue, and would be far better solved with a simple text notice in the product description.

Also, if a long-standing feature request can be achieved with 2 lines of code, why the hesitation to allow the option (even if it's not appropriate for every store)? This is basic e-commerce functionality that's been around since the '90s...

**Comment by mikejolley** [comment]
The popup will appear if you try to select an invalid variation attribute on the frontend. This can only happen if the attributes select box is pre-filled either by passing query string values, or by selecting 'default attributes' in the backend. After the popup, the select box is reset to default state. If you don't prefill the attribute select box, this will never show.

Yes the popup sucks. We're revising the entire system in https://github.com/woocommerce/woocommerce/issues/13086

**Comment by dallasprice** [comment]
@mikejolley I'm currently experiencing this problem on a product with many variations, descriptions and pricing differences. It was working fine but, when I finished up the one product and went to look on the front it just started it (the box looks way better than the OP's though.)

**Comment by dallasprice** [comment]
I think I found the answer for my issue on StackExchange. Thanks guys.

The default limit of variations is only 30. For more variations you have to modify them with `/**
 * Ensure variation combinations are working properly - standard limit is 30
 * 
 */

function woo_custom_ajax_variation_threshold( $qty, $product ) {
    return 50;
}       
add_filter( 'woocommerce_ajax_variation_threshold', 'woo_custom_ajax_variation_threshold', 10, 2 );`

**Comment by daliya27** [comment]
Hi,

I have tired by trying all these I stuck with this error and I have finished with the entire theme customization and product addition. I can not select a variant option, Which causes this error.
Appreciate If anyone can help."Sorry, no products matched your selection. Please choose a different combination."
