### ISSUE TITLE
Issue with WooCommerce Product Category Widget

### ISSUE THREAD

**Issue by jmfonseca** [woocommerce/woocommerce#13170]
## EXPLANATION OF THE ISSUE

When selecting the box "Hide empty categories" its not hiding categories with products that have a "Draft"status and are in that category.

## STEPS TO REPRODUCE THE ISSUE

Only have products with "Draft" Status with a specific category.

**Comment by mikejolley** [comment]
Just tested this and it doesn't appear to be an issue. I had a category with only 1 product inside. Once I set the product to be a draft, it vanished. 

Bare in mind, if the category has children with products in it, it's still shown.
