### ISSUE TITLE
Add filter for `$this->query_vars` in `init_query_vars()` method

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#13178]
In trying to add a custom endpoint to the my account area, I can add the settings to the admin, but without a filter for the query vars, the `is_wc_endpoint_url()` always returns `false` for a custom endpoint and I can't take advantage of the filter in `get_endpoint_title()`, so I have to duplicate the `the_title` filter and the `add_rewrite_endpoint` functionality.

**Comment by mikejolley** [comment]
@claudiulodro related reading :) https://github.com/woocommerce/woocommerce/wiki/Customising-%22My-Account%22-tabs

**Comment by claudiosanches** [comment]
> so I have to duplicate the the_title filter and the add_rewrite_endpoint functionality.

@mikejolley @helgatheviking but that is the idea, so not allow people to remove our endpoints and still some plugins can hook to late, that's why I did it, so you can use `add_rewrite_endpoint()`.

**Comment by claudiosanches** [comment]
Checking here, we can include a filter into `is_wc_endpoint_url()`, so we can use the https://github.com/woocommerce/woocommerce/blob/1cee800b4e8640397d1a2455c73b21dbbb991eea/includes/class-wc-query.php#L132 to change the titles without trouble.

**Comment by helgatheviking** [comment]
@claudiosanches filtering `is_wc_endpoint_url()` will work too.

**Comment by helgatheviking** [comment]
Relatedly, `$endpoint = WC()->query->get_current_endpoint();` will always be null for custom endpoints so so it'll only pass a null value to `wc_page_endpoint_title()` so you still can't filter the page via `'woocommerce_endpoint_' . $endpoint . '_title'`

**Comment by helgatheviking** [comment]
filtering the results of the `get_query_vars()` method solves a lot of the above issues with duplication, but I guess that does open you up to someone removing an endpoint.

`return apply_filters( 'woocommerce_get_query_vars', $this->query_vars );`

However, if you don't change the `$this->query_vars` in:

```
	/**
	 * Add endpoints for query vars.
	 */
	public function add_endpoints() {
		$mask = $this->get_endpoints_mask();

		foreach ( $this->query_vars as $key => $var ) {
			if ( ! empty( $var ) ) {
				add_rewrite_endpoint( $var, $mask );
			}
		}
	}
```

to `$this->get_query_vars()` then the default endpoints cannot be removed.
