### ISSUE TITLE
Ajaxify the cart widget

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#13171]
I think it'd be a nice enhancement for visitors to be able to remove items from their cart via the widget without a full page refresh. Just like on the main cart page.

**Comment by MattyLB** [comment]
+1 on this enhancement with a request to also consider allowing a customer to change an item's qty and variables such as size, etc via Ajax in both the widget and the cart page.

I've seen it work very well with the Extra Product Options plugin on Envato, so adding this to core would lighten the load on third party plugin/theme devs and considerably improve the user experience for customers needing to make a simple adjustment before checking out.

Thanks for considering. :)

**Comment by TheZoker** [comment]
+1

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16107
