### ISSUE TITLE
Woocommer search order not working

### ISSUE THREAD

**Issue by Ngzhihan93** [woocommerce/woocommerce#13172]
Using Woocommerce version 2.6.14 here, the search orders function in the orders page is not working when the order number is keyed in. It returns no orders found. I have tried searching for similar issues online and modifying the source code wc_order_search to no avail. Anyone with the same issue?

SYSTEM STATUS REPORT

Active Plugins (12)
Instagram Feed 	  	by Smash Balloon – 1.3.1
WPBakery Visual Composer 	  	by Michael M - WPBakery.com – 4.1.3
Revolution Slider 	  	by ThemePunch – 4.6.0
WooCommerce Table Rate Shipping by Mangohour 	  	by mangohour – 1.2.1
Taxonomy Metadata 	  	by mitcho (Michael Yoshitaka Erlewine), sirzooro – 0.5
Visual Form Builder Pro 	  	by Matthew Muro – 2.5.1
WooCommerce Auto Restore Stock 	  	by Gerhard Potgieter – 1.0.1
WooCommerce Pretty Emails 	  	by MB Création – 1.4
WooCommerce Quick Export Plugin 	  	by – 2.1.2
WooCommerce Sequential Order Numbers 	  	by SkyVerge – 1.7.0
WooCommerce 	  	by WooThemes – 2.6.14
YITH WooCommerce Ajax Search 	  	by YITHEMES – 1.4.1

Theme
Name: 		Flatsome
Version: 		2.1
Author URL: 		http://www.uxthemes.com/

Overrides (WooCommerce): 	  	
flatsome_2.1/flatsome/woocommerce/archive-product.php,
flatsome_2.1/flatsome/woocommerce/cart/cart.php version 2.1.0,
flatsome_2.1/flatsome/woocommerce/cart/shipping-calculator.php,
flatsome_2.1/flatsome/woocommerce/checkout/form-checkout.php version 2.0.0 
flatsome_2.1/flatsome/woocommerce/content-product.php version 1.6.4 
flatsome_2.1/flatsome/woocommerce/content-product_cat.php version 1.6.4 
flatsome_2.1/flatsome/woocommerce/content-single-product.php,
flatsome_2.1/flatsome/woocommerce/emails/customer-invoice.php version 2.2.0 
flatsome_2.1/flatsome/woocommerce/global/breadcrumb.php version 2.2.0
flatsome_2.1/flatsome/woocommerce/global/wrapper-end.php,
flatsome_2.1/flatsome/woocommerce/global/wrapper-start.php,
flatsome_2.1/flatsome/woocommerce/loop/loop-end.php,
flatsome_2.1/flatsome/woocommerce/loop/loop-start.php,
flatsome_2.1/flatsome/woocommerce/loop/orderby.php,
flatsome_2.1/flatsome/woocommerce/loop/pagination.php,
flatsome_2.1/flatsome/woocommerce/loop/result-count.php,
flatsome_2.1/flatsome/woocommerce/loop/sale-flash.php,
flatsome_2.1/flatsome/woocommerce/myaccount/form-login.php version 2.2.6 
flatsome_2.1/flatsome/woocommerce/notices/error.php,
flatsome_2.1/flatsome/woocommerce/notices/success.php,
flatsome_2.1/flatsome/product-searchform.php version - is out of date. The core version is 2.5.0,
flatsome_2.1/flatsome/woocommerce/single-product/add-to-cart/grouped.php,
flatsome_2.1/flatsome/woocommerce/single-product/add-to-cart/simple.php,
flatsome_2.1/flatsome/woocommerce/single-product/add-to-cart/variable.php version 2.1.0
flatsome_2.1/flatsome/woocommerce/single-product/price.php version 1.6.4 
flatsome_2.1/flatsome/woocommerce/single-product/product-image.php version 2.0.14 
flatsome_2.1/flatsome/woocommerce/single-product/related.php,
flatsome_2.1/flatsome/woocommerce/single-product/review.php version 2.1.0 
flatsome_2.1/flatsome/woocommerce/single-product/sale-flash.php,
flatsome_2.1/flatsome/woocommerce/single-product/share.php,
flatsome_2.1/flatsome/woocommerce/single-product/short-description.php,
flatsome_2.1/flatsome/woocommerce/single-product/tabs/additional-information.php,
flatsome_2.1/flatsome/woocommerce/single-product/tabs/description.php,
flatsome_2.1/flatsome/woocommerce/single-product/tabs/tabs.php version 2.0.0 
flatsome_2.1/flatsome/woocommerce/single-product/title.php,
flatsome_2.1/flatsome/woocommerce/single-product/up-sells.php,
flatsome_2.1/flatsome/woocommerce/single-product-reviews.php version 2.1.0 
flatsome_2.1/flatsome/woocommerce/single-product.php

**Comment by mikejolley** [comment]
Order number search is added by the sequencial numbers plugin - use the helpdesk on https://docs.woocommerce.com/

**Comment by bekarice** [comment]
@Ngzhihan93 that will be fixed in the next release :) in the meantime, you could [download the master branch with the fix here](https://github.com/skyverge/woocommerce-sequential-order-numbers) and replace the plugin files with the updated ones.

**Comment by Ngzhihan93** [comment]
Thank you so much, i was about to mention that i tested it without the equential search order plugin. Much appreciated :)
