### ISSUE TITLE
Paypal - Cart not empty after success paiement

### ISSUE THREAD

**Issue by Kundun12** [woocommerce/woocommerce#13175]
Dear woo commerce /github,

I have an issues with my online shop - please could you help me ? 

I use Wordpress 4.7.2 and woocommerce 2.6.14. And for the moment I'm using paypal sandbox. 

The issue is after payment processed on paypal platform, 

1- I come back to my online shop, with link provided by paypal, on page checkout/order-received/....... 
2- The order is well registered and my stock is updated
3- and when I go to my cart. It is not empty. I have always my order

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://www.re7.blog.estampille-paris.fr.
Site URL: http://www.re7.blog.estampille-paris.fr.
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.25
PHP Post Max Size: 64 MB
PHP Time Limit: 0
PHP Max Input Vars: 16000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.53 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (10) ###

AddToAny Share Buttons: par AddToAny – 1.7.7
BackUpWordPress: par Human Made Limited – 3.6.3.1
Colissimo Delivery Integration: par Harasse – 1.18.1
Responsive Lightbox: par dFactory – 1.6.12
FAQ: par Etoile Web Design – 1.5.22
WooCommerce Cart Tab: par jameskoster – 1.1.0
WooCommerce: par WooThemes – 2.6.14
Yoast SEO: par L’équipe Yoast – 4.2.1
WP Slick Slider and Image Carousel: par WP Online Support – 1.2.6
MailPoet Newsletters: par MailPoet – 2.7.7

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Base Boutique: ❌ Page non définie
Panier: #110 - /cart/
Commande: #111 - /checkout/
Mon Compte: #112 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Estampille
Version: 0.1.0
Author URL: https://www.wpserveur.net
Child Theme: ✔
Parent Theme Name: Twenty Sixteen
Parent Theme Version: 1.3
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: estampille_child/woocommerce/archive-product.php
estampille_child/woocommerce/auth/footer.php
estampille_child/woocommerce/auth/form-grant-access.php
estampille_child/woocommerce/auth/form-login.php
estampille_child/woocommerce/auth/header.php
estampille_child/woocommerce/cart/cart-empty.php
estampille_child/woocommerce/cart/cart-item-data.php
estampille_child/woocommerce/cart/cart-shipping.php
estampille_child/woocommerce/cart/cart-totals.php
estampille_child/woocommerce/cart/cart.php
estampille_child/woocommerce/cart/cross-sells.php
estampille_child/woocommerce/cart/mini-cart.php
estampille_child/woocommerce/cart/proceed-to-checkout-button.php
estampille_child/woocommerce/cart/shipping-calculator.php
estampille_child/woocommerce/checkout/cart-errors.php
estampille_child/woocommerce/checkout/form-billing.php
estampille_child/woocommerce/checkout/form-checkout.php
estampille_child/woocommerce/checkout/form-coupon.php
estampille_child/woocommerce/checkout/form-login.php
estampille_child/woocommerce/checkout/form-pay.php
estampille_child/woocommerce/checkout/form-shipping.php
estampille_child/woocommerce/checkout/payment-method.php
estampille_child/woocommerce/checkout/payment.php
estampille_child/woocommerce/checkout/review-order.php
estampille_child/woocommerce/checkout/terms.php
estampille_child/woocommerce/checkout/thankyou.php
estampille_child/woocommerce/content-product.php
estampille_child/woocommerce/content-product_cat.php
estampille_child/woocommerce/content-single-product.php
estampille_child/woocommerce/content-widget-product.php
estampille_child/woocommerce/emails/admin-cancelled-order.php
estampille_child/woocommerce/emails/admin-failed-order.php
estampille_child/woocommerce/emails/admin-new-order.php
estampille_child/woocommerce/emails/customer-completed-order.php
estampille_child/woocommerce/emails/customer-invoice.php
estampille_child/woocommerce/emails/customer-new-account.php
estampille_child/woocommerce/emails/customer-note.php
estampille_child/woocommerce/emails/customer-on-hold-order.php
estampille_child/woocommerce/emails/customer-processing-order.php
estampille_child/woocommerce/emails/customer-refunded-order.php
estampille_child/woocommerce/emails/customer-reset-password.php
estampille_child/woocommerce/emails/email-addresses.php
estampille_child/woocommerce/emails/email-customer-details.php
estampille_child/woocommerce/emails/email-footer.php
estampille_child/woocommerce/emails/email-header.php
estampille_child/woocommerce/emails/email-order-details.php
estampille_child/woocommerce/emails/email-order-items.php
estampille_child/woocommerce/emails/email-styles.php
estampille_child/woocommerce/emails/plain/admin-cancelled-order.php
estampille_child/woocommerce/emails/plain/admin-failed-order.php
estampille_child/woocommerce/emails/plain/admin-new-order.php
estampille_child/woocommerce/emails/plain/customer-completed-order.php
estampille_child/woocommerce/emails/plain/customer-invoice.php
estampille_child/woocommerce/emails/plain/customer-new-account.php
estampille_child/woocommerce/emails/plain/customer-note.php
estampille_child/woocommerce/emails/plain/customer-on-hold-order.php
estampille_child/woocommerce/emails/plain/customer-processing-order.php
estampille_child/woocommerce/emails/plain/customer-refunded-order.php
estampille_child/woocommerce/emails/plain/customer-reset-password.php
estampille_child/woocommerce/emails/plain/email-addresses.php
estampille_child/woocommerce/emails/plain/email-customer-details.php
estampille_child/woocommerce/emails/plain/email-order-details.php
estampille_child/woocommerce/emails/plain/email-order-items.php
estampille_child/woocommerce/global/breadcrumb.php
estampille_child/woocommerce/global/form-login.php
estampille_child/woocommerce/global/quantity-input.php
estampille_child/woocommerce/global/sidebar.php
estampille_child/woocommerce/global/wrapper-end.php
estampille_child/woocommerce/global/wrapper-start.php
estampille_child/woocommerce/loop/add-to-cart.php
estampille_child/woocommerce/loop/loop-end.php
estampille_child/woocommerce/loop/loop-start.php
estampille_child/woocommerce/loop/no-products-found.php
estampille_child/woocommerce/loop/orderby.php
estampille_child/woocommerce/loop/pagination.php
estampille_child/woocommerce/loop/price.php
estampille_child/woocommerce/loop/rating.php
estampille_child/woocommerce/loop/result-count.php
estampille_child/woocommerce/loop/sale-flash.php
estampille_child/woocommerce/myaccount/dashboard.php
estampille_child/woocommerce/myaccount/downloads.php
estampille_child/woocommerce/myaccount/form-add-payment-method.php
estampille_child/woocommerce/myaccount/form-edit-account.php
estampille_child/woocommerce/myaccount/form-edit-address.php
estampille_child/woocommerce/myaccount/form-login.php
estampille_child/woocommerce/myaccount/form-lost-password.php
estampille_child/woocommerce/myaccount/form-reset-password.php
estampille_child/woocommerce/myaccount/lost-password-confirmation.php
estampille_child/woocommerce/myaccount/my-account.php
estampille_child/woocommerce/myaccount/my-address.php
estampille_child/woocommerce/myaccount/my-downloads.php
estampille_child/woocommerce/myaccount/my-orders.php
estampille_child/woocommerce/myaccount/navigation.php
estampille_child/woocommerce/myaccount/orders.php
estampille_child/woocommerce/myaccount/payment-methods.php
estampille_child/woocommerce/myaccount/view-order.php
estampille_child/woocommerce/notices/error.php
estampille_child/woocommerce/notices/notice.php
estampille_child/woocommerce/notices/success.php
estampille_child/woocommerce/order/form-tracking.php
estampille_child/woocommerce/order/order-again.php
estampille_child/woocommerce/order/order-details-customer.php
estampille_child/woocommerce/order/order-details-item.php
estampille_child/woocommerce/order/order-details.php
estampille_child/woocommerce/order/tracking.php
estampille_child/woocommerce/product-searchform.php
estampille_child/woocommerce/single-product/add-to-cart/external.php
estampille_child/woocommerce/single-product/add-to-cart/grouped.php
estampille_child/woocommerce/single-product/add-to-cart/simple.php
estampille_child/woocommerce/single-product/add-to-cart/variable.php
estampille_child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
estampille_child/woocommerce/single-product/add-to-cart/variation.php
estampille_child/woocommerce/single-product/meta.php
estampille_child/woocommerce/single-product/price.php
estampille_child/woocommerce/single-product/product-attributes.php
estampille_child/woocommerce/single-product/product-image.php
estampille_child/woocommerce/single-product/product-thumbnails.php
estampille_child/woocommerce/single-product/rating.php
estampille_child/woocommerce/single-product/related.php
estampille_child/woocommerce/single-product/review-meta.php
estampille_child/woocommerce/single-product/review-rating.php
estampille_child/woocommerce/single-product/review.php
estampille_child/woocommerce/single-product/sale-flash.php
estampille_child/woocommerce/single-product/share.php
estampille_child/woocommerce/single-product/short-description.php
estampille_child/woocommerce/single-product/tabs/additional-information.php
estampille_child/woocommerce/single-product/tabs/description.php
estampille_child/woocommerce/single-product/tabs/tabs.php
estampille_child/woocommerce/single-product/title.php
estampille_child/woocommerce/single-product/up-sells.php
estampille_child/woocommerce/single-product-reviews.php
estampille_child/woocommerce/single-product.php version - est obsolète. La version du coeur est 1.6.4
estampille_child/woocommerce/taxonomy-product_cat.php
estampille_child/woocommerce/taxonomy-product_tag.php

**Comment by mikejolley** [comment]
The IPN may be delayed. Enable https://docs.woocommerce.com/document/paypal-standard/#section-27 so the order gets updated when the user gets back.
