### ISSUE TITLE
Product Duplication: no more filter to exclude post meta

### ISSUE THREAD

**Issue by jeherve** [woocommerce/woocommerce#13180]
There used to be a `woocommerce_duplicate_product_exclude_meta` filter in WooCommerce that would allow to exclude specific post meta when duplicating a product, but it looks like that filter was removed in 10d3e2d580cc7ad815eddf32ca486f5c5fb2d26c. 

That filter was useful with other plugins like Jetpack, where it allowed site owners to exclude specific post meta (e.g. post meta controlling whether a product should be publicized or not) from being duplicated alongside a product.

Is there a better way to control what's duplicated by WooCommerce now?

P.S.: it looks like `woocommerce_duplicate_product_exclude_taxonomies` was also removed.

**Comment by mikejolley** [comment]
@jeherve Are you talking specifically about 2.7 beta right now? These were removed simply because it's more efficient to just duplicate the entire object without worrying about 'meta' at all.

**Comment by jeherve** [comment]
> Are you talking specifically about 2.7 beta right now?

Yes, I believe so since the changes haven't made it to an official release yet.

> These were removed simply because it's more efficient to just duplicate the entire object without worrying about 'meta' at all.

Does that mean one would need to delete post meta differently, after the product has been duplicated, before it's published? Any idea how I'd go about this?

**Comment by MattyLB** [comment]
I strongly agree with @jeherve on this and I was about to post a similar issue regarding data from other add-ons like SEO, Google Feed, theme templates etc also getting copied over in the current versions - which makes for more steps we need to check to prevent the wrong product data from going to the copy.

One last point on this, and maybe I'm asking for too much but I've seen other shopping cart systems ask for the new product's TITLE and SKU before creating a copy and inserting those two key pieces. Made a lot of sense and saved a lot of time but if this is a limitation with WP's post duplication process, I'll take the issue up with them.

Thanks for considering our ideas and concerns on this! :)
