### ISSUE TITLE
Product Add-Ons: woocommerce_order_item_display_meta_value returns empty value

### ISSUE THREAD

**Issue by mattiamerlini** [woocommerce/woocommerce#13186]
# EXPLANATION OF THE ISSUE

The attributes added by Product Add-Ons plugin failed to show in front view order detail list. Keys are displayed but values remains empty . Problems seems in class-wc-order-item-meta.php in line with
$formatted_meta[ $meta_id ] = array(
'key' => $meta->key,
'label' => wc_attribute_label( $attribute_key, $this->product ),
'value' =>**apply_filters( 'woocommerce_order_item_display_meta_value', $meta->value )**,
);

Removing the apply_filters(...) and leaving only $meta->value solved the problem, but it's not update safe

# STEPS TO REPRODUCE THE ISSUE

Install Add Ons plugin
Add multiplier through addon
Order that product in front end
Check the order detail and multiplier value keeps missing in email order detail but not in order view in admin area.

**Comment by mikejolley** [comment]
This doesn't mean there is a bug -this means something on _your_ site is filtering `woocommerce_order_item_display_meta_value` to be empty. I don't see any code which would do that in the addons extension itself, so rule out conflicts before contacting the help desk please (Github is for core issues only).
