### ISSUE TITLE
Main stock not updated when using variable products

### ISSUE THREAD

**Issue by udarts** [woocommerce/woocommerce#13194]
Hi Guys,

I am using the latest version of WC, and I am running into an issue.

Using variable products on the website, for example:

I am selling paint, and for a product I have several variables (colors): Yellow, green, etc.
When I select Yellow, the main stock is not being updated, only the variable stock.
The main stock should also be updated.

Both the manage stock on product and variable are checked.

Is this done on purpose or is this a bug.

Cheers,
Stephan

**Comment by jezmck** [comment]
I suspect this is the expected behaviour - t-shirts of different sizes for example would have their own stock.

I imagine your case, presumably white paint stock with dye added when ordered, is unusual.

Even if this _is_ the expected behaviour, it's not clear what should be, and that fact can be addressed here also.

**Comment by udarts** [comment]
The reason why I asked, is that for example with the t-shirts:

There is only 1 in the main stock, and there are 3 different variable t-shirt to choose from. So when a choice has been made from the variable t-shirts, the main stock should be set to 0, meaning only 1 variable could have been chosen.

I hope this makes sense.

**Comment by mikejolley** [comment]
This is how it is intended. The main product stock is only used if the variation has no stock of it's own. It's so you can have products which share stock e.g. made to order tshirts where you choose a logo as the variation.

I will point out this is likely to be simplified in https://github.com/woocommerce/woocommerce/issues/13086
