### ISSUE TITLE
Shipping information is not captured when customer purchased simple virtual product

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#13193]
## EXPLANATION OF THE ISSUE

Please note that this might be the expected behaviour of virtual product per 2.7. In that case, feel free to close this.

In WC 2.6, if customer purchased simple virtual product using built-in payment method (e.g. COD), shipping information from customer is captured in order. This is displayed in order admin screen. However, it's not captured in 2.7-beta.

## STEPS TO REPRODUCE THE ISSUE

1. Create simple product
2. Proceed to checkout
3. There's no shipping information on the order screens. Verified in order meta too.

With 2.6.14 shipping info is captured into order meta.

**Comment by mikejolley** [comment]
This is expected behavior. Virtual orders do not ship and do not gather shipping addresses or methods.
