### ISSUE TITLE
[REST API] Variation delete bug

### ISSUE THREAD

**Issue by imbeingfollowed** [woocommerce/woocommerce#13197]
Hi,

REST API: 1.1.4
Woo: 2.6.14

I have tested both 'products/batch' and 'delete' calls and neither will correctly delete a variation. The variation appears to be removed, but after executing it will break further GET 'products' calls (Returns a 500 error: Error: []). The only way to correct this is to edit the offending product in the backend and save it again.

Please investigate,

Cheers

**Comment by mikejolley** [comment]
Variations cannot be updated via the products endpoint since they are not products. You can set the 'variations' property of the product itself to change them.

We'll have a new variations endpoint in 2.7.
