### ISSUE TITLE
Mini Cart/Cart Removal UX

### ISSUE THREAD

**Issue by CHEWX** [woocommerce/woocommerce#13196]
Hi,

## EXPLANATION OF THE ISSUE

Mini cart refreshes the page on the removal of an item. I would expect this to use ajax like the normal cart. It seems inconsistent and bad UX.

Although the cart essentially has the same issue as you have to wait for the ajax callback to complete before you can remove another item at least you don't have to endure a full page reload which is completely unnecessary with a note that says you have removed an item... I know I have removed an item as I have just initiated a remove.

## STEPS TO REPRODUCE THE ISSUE

1. Add 3 items to cart
2. Remove 3 items — Remove
3. Refresh
4. Remove
5. Refresh
6. Remove
7. Refresh

## Recap

Essentially 2 issues here. But the main one being making the mini-cart more consistent with the full page cart. The second issue is allowing the user to continue removing products asynchronously instead of sequentially.

Be good to hear your thoughts on both.

Thanks,
Tom

**Comment by mikejolley** [comment]
This was logged a few days ago already ;) https://github.com/woocommerce/woocommerce/issues/13171

**Comment by CHEWX** [comment]
Ah, what are the chances!
