### ISSUE TITLE
Page / Post Links Not Visible on all WP Generated Menus until after Login

### ISSUE THREAD

**Issue by dblodorn** [woocommerce/woocommerce#13204]
## EXPLANATION OF THE ISSUE

Basically before I log in as a customer to my wordpress site, any item that is a page link in any menu created within wordpress -> appearence -> menus will not display, custom links are not effected, just page & post links. After Logging in as registered woocommerce customer all my menus show as expected.

## STEPS TO REPRODUCE THE ISSUE

Unfortunately I cannot represent the chain of events that lead to this, as I am not the person who made changes to the database in between the last time i checked the site and now.

But basically if i turn off the woocommerce plugin all my menu items display - if i turn it on, they disappear until I log in to my account.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://kitchen-nation.dev
Site URL: http://kitchen-nation.dev
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.5
PHP Version: 7.0.12-1+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.53 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (10) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.7
Ninja Forms: by The WP Ninjas – 3.0.27
User Role Editor: by Vladimir Garagulya – 4.31.1
WooCommerce: by WooThemes – 2.6.14
WP-Markdown: by Stephen Harris – 1.5.1
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.7
WP Migrate DB Pro Tweaks: by Delicious Brains – 0.1
WP Migrate DB Pro: by Delicious Brains – 1.7.1
WP PHP Console: by Fulvio Notarstefano – 1.5.0
Easy Forms for MailChimp: by YIKES
Inc. – 6.3.5

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: –

### WC Pages ###

Shop Base: #606 - /shop/
Cart: #607 - /cart/
Checkout: #608 - /checkout/
My Account: #609 - /my-account/

### Taxonomies ###

Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Kitchen-Nation
Version: 1.0
Author URL: http://14-forty.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Not much I can do for you here - it's not reproducible on other sites so I can only presume it's the result of a database migration (I see you have WP Migrate DB Pro on). 

Sounds like there is a problem with the pages themselves e.g. private/draft, or corrupt. Maybe it's time to re-make them?

What about caching? Page caching could be on for guests.

This is the only menu code I know of https://github.com/woocommerce/woocommerce/blob/b2b42600cdf76cc44d336ade796fbdea8ea1a356/includes/wc-page-functions.php#L117 and that should on remove log out links. Maybe the logout endpoint has been set in admin to something which matches all page URLs?

**Comment by dblodorn** [comment]
Thanks @mikejolley for your response - we were actually able to replicate the issue, and I felt it was worth bringing to your attention. Under WooCommerce > Settings > Accounts if the logout link is set as: / the all the page links in wp generated menus dissapear until login, seems to be fine with other links ie. /blog/

Maybe this is what the link you included is referring to.

-- Strange. Thanks again.

**Comment by mikejolley** [comment]
Ah yeah, setting to / would mean all pages are considered log out endpoints :)

**Comment by dblodorn** [comment]
So super basic question then @mikejolley - If we want the user to get kicked back to the landing page what the url be? thanks for your time!

**Comment by mikejolley** [comment]
What do you mean? The setting determines what the logout link will be, not where it will redirect to.

**Comment by dblodorn** [comment]
Got it - we we're under the impression that setting was for setting the redirect - providing one place to dynamically set all instances of the logout redirect.
