### ISSUE TITLE
Refund returned with error still deduct order total

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#13200]
## EXPLANATION OF THE ISSUE

When trying to refund an order via payment method which supports refund and the `process_refund` from payment method returns `WP_Error` or `false`, WC still deduct the order total.

## STEPS TO REPRODUCE THE ISSUE

Use `master` branch or 2.7-beta.

1. Purchase a product with PayPal standard
2. Make a refund from the order via PayPal with error from API response. This can be achieved by setting the refunded amount higher than order total
3. Got dialog showing the error but order still deducted

**Comment by linahammad** [comment]
Hi, how does your fix resolve the issue??

**Comment by mikejolley** [comment]
It resolves the issue by deleting right away; no trash.

**Comment by linahammad** [comment]
can you please explain more, I didn't understand?

**Comment by mikejolley** [comment]
I'm not really sure what you mean. The issue above and fix is all done internally; you don't have to call anything.

**Comment by gedex** [comment]
> my case is: when I call process_refund the amount is deducted even before calling the gateway and if we return an exception, the full amount is deducted.

@linahammad I assume you're implementing a payment method with refund support. Please take a look at following examples on how refund is handled:

* [PayPal standard](https://github.com/woocommerce/woocommerce/blob/master/includes/gateways/paypal/class-wc-gateway-paypal.php#L283-L311)
* [Stripe](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/23d8d4baaa60881d3a94fc5fd6b1ddf0efd4e201/includes/class-wc-gateway-stripe.php#L935-L967)

**Comment by linahammad** [comment]
Exactly gedex , that's what I am trying to do, ok i will check them,, thanks a lot
