### ISSUE TITLE
Order by Featured first + price asc

### ISSUE THREAD

**Issue by uzyrnet** [woocommerce/woocommerce#13201]
Hi, This is more of a question than bug.
How do i order featured first + price asc on product archives,
Basically i want to display a specific product on top regardless of price asc or dsc

**Comment by mikejolley** [comment]
This one is not supported by default, but you could look into filtering our default sorting to add this. We'll look at making this possible out of the box in https://github.com/woocommerce/woocommerce/issues/13072

**Comment by LuckiesTom** [comment]
'Posted a possible solution here: 
https://stackoverflow.com/questions/60494185/promote-featured-products-to-top-of-category-in-woocommerce/60494186#60494186

This solution uses date as the secondary order, but that can be easily changed to price by adjusting the default ordering for the "Recommended" order type within the code linked above.
