### ISSUE TITLE
Out Of Stock Visibility option triggers alert on variations if all variations are out of stock

### ISSUE THREAD

**Issue by conschneider** [woocommerce/woocommerce#13216]
#### Summary

Activating the Out Of Stock Visibility option under Settings -> Products ->Inventory triggers an alert pop up error message on a variable product "Sorry no products matched your selection" if all variations are set to out of stock.

#### STEPS TO REPRODUCE THE ISSUE

Activate Out Of Stock Visibility at `/wp-admin/admin.php?page=wc-settings&tab=products&section=inventory` 

![](https://cldup.com/Zqkt-ViYHt.png)

Create a variable product and set all its variation to out of stock. 

Visit the product and be harassed by this ;) 

![](https://cldup.com/Y1WhEkLpyG.png)

#### SYSTEM STATUS REPORT

WC Version:		2.6.14
WP Version:		4.7.2

Rolling back to WooCommerce 2.6.8 solves the issue. 
Is this intended behaviour?

Cheerio,

**Comment by mikejolley** [comment]
This will only happen if you set a 'default' because it tries to select it. Ill add a workaround in 2.7

**Comment by conschneider** [comment]
Gracias for the fix. 
On a side note: it does happen to me when there is no default variation set.
