### ISSUE TITLE
[2.7]  Fatal error when trying to set a product image.

### ISSUE THREAD

**Issue by Chrystll** [woocommerce/woocommerce#13210]
WordPress : 4.7.2
Plugins activated : Only WooCommerce 2.7 beta2 (master)
Theme : StoreFront 2.1.7

To reproduce, create or edit a product. Then set a product image from the Media Library : the Media library is empty.

Then I get this fatal error :
PHP Fatal error:  Uncaught Error: Call to a member function get_permalink() on boolean in (…)/woocommerce/includes/class-wc-post-data.php:65

**Comment by mikejolley** [comment]
I cannot reproduce this but I can add a check to ensure the product object is retrieved.
