### ISSUE TITLE
List of Products order change in Rest API

### ISSUE THREAD

**Issue by basanthalluri** [woocommerce/woocommerce#13212]
Hi 

Is it possible to change the order of the products in the admin? 

If Yes, does the order effect in the list of products in [REST API.](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products)

Please suggest me.

Thanks

**Comment by mikejolley** [comment]
Click on a column header on the products screen. That method does not affect API.

**Comment by basanthalluri** [comment]
Yes..I know clicking on column header of the products in admin screen will change the order of the products.

I need the to how we can sort the order in Rest API. When i change the order of the products is there a way to effect the order in Rest API

I have seen the rest API it has orderby parameter but is not reflecting for me.

Please suggest me.

**Comment by mikejolley** [comment]
```
Sort collection by object attribute. Default is date, Options: date, id, include, title and slug.
```

https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

**Comment by basanthalluri** [comment]
Hi Mike,

Here is the sort orderby i am passing but not getting results.

http://www.bunksuppliesandbeyond.com:4500/api/products?orderby=id&order=desc

Here is the API code i am using to get all products.

app.get('/api/products',function(req,res){

  WooCommerce.get('products/?per_page=50',function(err, data, res1) {
    var json=JSON.parse(res1)
    res.send(json)
  });
})

**Comment by mikejolley** [comment]
Thats not the correct API endpoint.

**Comment by basanthalluri** [comment]
Can you suggest me the correct API endpoint? Let me know where i am doing wrong.

http://www.bunksuppliesandbeyond.com:4500/api/products

**Comment by mikejolley** [comment]
Please review the docs. /api/products does not exist?

**Comment by basanthalluri** [comment]
I kept all the api in single folder called as "api". I am getting all the products using get.

Do we still need to follow the same folder structure like document?

/wp-json/wc/v1/products

**Comment by mikejolley** [comment]
Thats where are endpoints are so I would expect so.

**Comment by claudiosanches** [comment]
@basanthalluri if you changed the structure from `wp-json` to something else, then you need to set it on the REST API lib that you are using.
