### ISSUE TITLE
[2.7] Download of files under my account is broken

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#13217]
Under my account, files to download can not be downloaded anymore due to a  ##wrong user id returned by WC_Customer_Download.

**Comment by mikejolley** [comment]
@pierrebuet are you raising a PR against our repo?

**Comment by pierrebuet** [comment]
sorry for that. I'm completely lost with where and how to send pr's. Briefly, in the file wc-user-functions.php around line 298, $download->user_id should be changed in $download->get_user_id().

Sorry again for all the trouble.

**Comment by mikejolley** [comment]
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by pierrebuet** [comment]
aaaah. I promise to be less rude in future.
