### ISSUE TITLE
wordpress and Woocomerce  problem

### ISSUE THREAD

**Issue by daniel-bios** [woocommerce/woocommerce#13215]
I have a website in wordpress and Woocomerce and I have got 95000 products on it
I have installed it on a VPS server cpu 4core and 3 GB RAM.
until I had 75000 products, the website was working very good
then it started running much slower
I did an upgarde to the server into 8cores and 8 gb ram , but again , when i do actions such as editing or adding new products using csv import , the cpu usage goes to 90-100 %, and the server runs very slowly.
Which it didnt happen a case like this, when i had 75000 products.
How can this issue be solved ?

Thank you

**Comment by mikejolley** [comment]
CSV import is doing a lot of stuff; parsing products, creating records in the DB etc so yes, CPU usage will be greater when this is taking place.

We're working on abstracting orders/products to move data to more performant structures. I'd suggest reading https://woocommerce.wordpress.com/

**Comment by daniel-bios** [comment]
Not only at the csv import , but even when you edit one product , the cpu usage raises up to 90-100  %
where as before i coul edit 7-10 edting of products  simulatneously without having this problem

**Comment by mikejolley** [comment]
As I said ^ 2.7 release might work better as it only updates what needs to be updated, rather than all meta data.

**Comment by daniel-bios** [comment]
Helllo again.

Even after transferring from a vps server to a dedicated one , with 8core 2 ghz xeon processor , 12 GB RAM ,, it still exists the problem when I edit products in the WOOcomerce.
If , when I had  the range of 75000 products , editing would last approximately 30 seconds, now that I have 95000 products , editing of a product would last around 3 minutes , and also appears the message Connetion lost.

And also the CPU usage and the RAM jump at 70-80 %.
How can this issue be solved?

**Comment by daniel-bios** [comment]
Tuning MySQL Server Settings

[root@lnx-vps01 ~]# perl mysqltuner.pl
 >>  MySQLTuner 1.6.20 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
Please enter your MySQL administrative login: root
Please enter your MySQL administrative password:
[OK] Currently running supported MySQL version 10.1.20-MariaDB
[OK] Operating on 64-bit architecture

-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +Aria +CSV +InnoDB +MEMORY +MRG_MyISAM +MyISAM +PERFORMANCE_SCHEMA +SEQUENCE

[--] Data in MyISAM tables: 961M (Tables: 194)
[--] Data in InnoDB tables: 19M (Tables: 71)
[OK] Total fragmented tables: 0



-------- CVE Security Recommendations --------------------------------------------------------------
[--] Skipped due to --cvefile option undefined

-------- Performance Metrics -----------------------------------------------------------------------
[--] Up for: 45s (558 q [12.400 qps], 17 conn, TX: 4M, RX: 129K)
[--] Reads / Writes: 96% / 4%
[--] Binary logging is disabled
[--] Physical Memory     : 11.6G
[--] Max MySQL memory    : 10.3G
[--] Other process memory: 643.0M
[--] Total buffers: 9.7G global + 2.9M per thread (200 max threads)
[--] P_S Max memory usage: 0B
[--] Galera GCache Max memory usage: 0B
[OK] Maximum reached memory usage: 9.7G (83.73% of installed RAM)
[!!] Maximum possible memory usage: 10.3G (88.59% of installed RAM)
[OK] Overall possible memory usage with other process is compatible with memory available
[OK] Slow queries: 0% (0/558)
[OK] Highest usage of available connections: 1% (2/200)
[!!] Aborted connections: 5.88%  (1/17)
[OK] Query cache efficiency: 24.0% (145 cached / 604 selects)
[OK] Query cache prunes per day: 0
[OK] Sorts requiring temporary tables: 0% (0 temp sorts / 43 sorts)
[OK] No joins without indexes
[!!] Temporary tables created on disk: 83% (54 on disk / 65 total)
[OK] Thread cache hit rate: 88% (2 created / 17 connections)
[OK] Table cache hit rate: 88% (45 open / 51 opened)
[OK] Open file limit used: 0% (69/16K)
[OK] Table locks acquired immediately: 100% (397 immediate / 397 locks)

-------- Performance schema ------------------------------------------------------------------------
[--] Performance schema is disabled.

-------- ThreadPool Metrics ------------------------------------------------------------------------
[--] ThreadPool stat is enabled.
[--] Thread Pool Size: 8 thread(s).
[--] Using default value is good enough for your version (10.1.20-MariaDB)

-------- MyISAM Metrics ----------------------------------------------------------------------------
[!!] Key buffer used: 28.8% (154M used / 536M cache)
[OK] Key buffer size / total MyISAM indexes: 512.0M/320.7M
[!!] Read Key buffer hit rate: 92.4% (734K cached / 55K reads)

-------- AriaDB Metrics ----------------------------------------------------------------------------
[--] AriaDB is enabled.
[OK] Aria pagecache size / total Aria indexes: 128.0M/1B
[!!] Aria pagecache hit rate: 89.4% (417 cached / 44 reads)

-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[OK] InnoDB buffer pool / data size: 8.0G/19.5M
[OK] InnoDB buffer pool instances: 8
[--] InnoDB Buffer Pool Chunk Size not used or defined in your version
[OK] InnoDB Read buffer efficiency: 96.07% (11745 hits/ 12226 total)
[!!] InnoDB Write Log efficiency: 50% (3 hits/ 6 total)
[OK] InnoDB log waits: 0.00% (0 waits / 9 writes)

-------- TokuDB Metrics ----------------------------------------------------------------------------
[--] TokuDB is disabled.

-------- Galera Metrics ----------------------------------------------------------------------------
[--] Galera is disabled.

-------- Replication Metrics -----------------------------------------------------------------------
[--] Galera Synchronous replication: NO
[--] No replication slave(s) for this server.
[--] This is a standalone server.

-------- Recommendations ---------------------------------------------------------------------------
General recommendations:
   
    MySQL started within last 24 hours - recommendations may be inaccurate
    Reduce your overall MySQL memory footprint for system stability
    Reduce or eliminate unclosed connections and network issues
    Temporary table size is already large - reduce result set size
    Reduce your SELECT DISTINCT queries without LIMIT clauses
