### ISSUE TITLE
trouble with woocommerce_add_order_item_meta and wc_add_order_item_meta

### ISSUE THREAD

**Issue by GitHub-Mike** [woocommerce/woocommerce#13228]
WordPress Version: 4.7.2
WooCommerce Version: 2.6.13

wc_add_order_item_meta function is not working inside woocommerce_add_order_item_meta Hook.

add_post_meta instead of wc_add_order_item_meta function is working very good. But only with static POST ID.

What's the problem? A bug?

    add_action( 'woocommerce_add_order_item_meta',
        function( $itemId, $values, $key ) {
            if ( isset( $values['custom_form_data'] ) ) { // custom_form_data is a array!
                // test
                add_post_meta( 202, 'itemId', $itemId ); // is not equal POST ID and $itemId!?
                add_post_meta( 202, 'custom_form_data', $values['custom_form_data'] ); // is working!
                add_post_meta( $itemId, '_custom_form_data', $values['custom_form_data'] ); // not working!
                wc_add_order_item_meta( 202, '__custom_form_data', $values['custom_form_data'] ); // not working!
                wc_add_order_item_meta( $itemId, '___custom_form_data', $values['custom_form_data'] ); // not working!
            }
        }
    , 10, 3 );

**Comment by mikejolley** [comment]
> add_post_meta( 202, 'custom_form_data', $values['custom_form_data'] ); // is working!

How can it be working; ITEMs are not posts. Sounds like you're looking in the wrong place for the meta data. The functions and actions work - we use them in core.

**Comment by GitHub-Mike** [comment]
But it seems to be working.
[see here in github](http://stackoverflow.com/questions/25188365/how-to-retrieve-cart-item-data-with-woocommerce?answertab=votes#tab-top)

And yes, ITEMs are not POSTs.
But what is the correct hook to save custom ITEM meta data as postmeta in db?

[LINE 248 in WC_Checkout](https://docs.woocommerce.com/wc-apidocs/source-class-WC_Checkout.html#248)
    // Allow plugins to add order item meta
    do_action( 'woocommerce_add_order_item_meta', $item_id, $values, $cart_item_key );

**Comment by mikejolley** [comment]
Items are not posts, so it's impossible for add_post_meta to work, unless you're getting your IDs mixed up.

**Comment by GitHub-Mike** [comment]
add_post_meta was a test because wc_add_order_item_meta don't work and dont't get a return value from this function!

I don't understand.
A order is a post with post_type "shop_order".
And the order meta data are saved in wp_postmeta.
wp_postmeta.post_id = wp_posts.ID

The question is:
How can I debug wc_add_order_item_meta and save item meta with wc_add_order_item_meta function?
OR
How can I get the POST ID from Order in woocommerce_add_order_item_meta Hook? Is the order already exists in woocommerce_add_order_item_meta Hook?

**Comment by mikejolley** [comment]
I don't know what you're asking tbh :D It's working everywhere else. You can use add_metadata directly if you want. https://codex.wordpress.org/Function_Reference/add_metadata It's the same though - our function is simply a wrapper for it. Ensure your item id is valid.

**Comment by GitHub-Mike** [comment]
Hi Mike,

sorry for the trouble, was my problem.

I mixed up orders and order items. But I understand the system now.
- a order is a post with post_type "shop_order"
- order meta data are saved in wp_postmeta
- order items are saved in woocommerce_order_items
- order item meta data are saved in woocommerce_order_itemmeta

wc_add_order_item_meta works correct. The data are in woocommerce_order_itemmeta and not in wp_postmeta.

Nice weekend!

Mike
