### ISSUE TITLE
Checkout Page - Zip Code Field Auto-Populated with Username by Browser

### ISSUE THREAD

**Issue by sghartman** [woocommerce/woocommerce#13223]
## EXPLANATION OF THE ISSUE
When users land at the Checkout page, the zip code field is auto-populated with their username by their browser. See screenshot here: http://imgur.com/W9Ejlry. 

This is default browser behavior because Google Chrome assumes that the form field immediately preceding ANY password field is a username field; regardless of field name, title, or whatever. It then “autofills” that field with a saved username (if available). In the case of the WooCommerce checkout page, because we allow registration on the Checkout page, this means that the zip code field gets auto-populated with their username.

This is problematic for several reasons:
1) User confusion in response to the weirdness of seeing their username on a potentially unfamiliar checkout page
2) If they're trusting auto-fill to populate their checkout page (which they should be able to do), if they attempt to submit the page it will obviously error out
3) If they catch the auto-population and update the Zip code field properly, when they submit they will be presented with a prompt from their browser to "save your password for this site?" and they will actually be saving their zip code. See here: http://imgur.com/eGpFPVH. This is very confusing and has resulted in many phone calls to our customer service team.

Could an alternate field arrangement fix this issue? We were also directed here by a helpful user at WP.com:
http://stackoverflow.com/questions/15738259/disabling-chrome-autofill

**Comment by mikejolley** [comment]
Already resolved in master/2.7
