### ISSUE TITLE
[2.7] Negative order fees are converted to absolute values in order edit screen

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/woocommerce#13224]
Also it seems to be impossible to add a negative fee via the admin interface, they are also become absolute values

**Comment by mikejolley** [comment]
Negative fees are not supported. If they 'worked' in 2.6 it was not purposely done, and undocumented.

**Comment by mikejolley** [comment]
#12482 - same, not supported
#10365 - last comment indicates that he expected discount to be > 0 when using negative fees, but like I said, it's not supported and shouldn't be used for discounts.
#8500 - Bugs trying to use negative fees

cc @justinshreve @claudiulodro @claudiosanches 

Use discounts instead if possible, or modify totals via actions and filters. The fee system should be used to add costs only.

**Comment by mikejolley** [comment]
^ Added a notice to discourage this in future.
