### ISSUE TITLE
Multipart Email | New Order

### ISSUE THREAD

**Issue by mbgrafik** [woocommerce/woocommerce#13236]
## EXPLANATION OF THE ISSUE

The plain text in both E-Mails (Admin + Customer) is identical. HTML View is different. Is this the expected behaviour?

Both E-Mails Plain Text:

= New customer order =

You have received an order from xxx.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

ORDER NUMBER: 570
18th February 2017
= New customer order =

You have received an order from XXX.

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

ORDER NUMBER: 570
18th February 2017

xxx (#xxx-16-001)
Quantity: 1
Cost: 300,00 .

==========

Subtotal:        300,00 .
Shipping:        Free Shipping
Payment Method:  Check Payments
Total:   300,00 . (includes 50,00 . VAT)

View order: https://xxx/wp-admin/post.php?post=570&action=edit

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

CUSTOMER DETAILS

Email: xxx
Tel: 123456

BILLING ADDRESS

xxx

SHIPPING ADDRESS

xxx

## STEPS TO REPRODUCE THE ISSUE

1. Set New Order to Multipart E-Mail
2. Do an order
3. See E-Mail send to Customer compare to E-Mail send to Admin/Shopmanager

-----------------------------------------------------

Latest WordPress | Twentysixteen + WooCommerce (Version 2.6.14) active
Same behaviour with WooCommerce 2.7 Beta3

**Comment by mikejolley** [comment]
I've confirmed both emails are different. In multipart mode:

_Customer_

HTML: https://dl.dropboxusercontent.com/s/1h4w6xeuzknfv4x/2017-02-20%20at%2011.27%20%281%29.png
Plain: https://dl.dropboxusercontent.com/s/xykolfjpsgz93ww/2017-02-20%20at%2011.27.png

_New order_

HTML: https://dl.dropboxusercontent.com/s/hljtpvpua5ckkzs/2017-02-20%20at%2011.28.png
Plain: https://dl.dropboxusercontent.com/s/caapyr1a92930xr/2017-02-20%20at%2011.28%20%281%29.png

These were caught with mail catcher. I'd guess you're either mistaken or have template overrides handling email contents. I cannot see any issue here.

**Comment by mbgrafik** [comment]
I can NOT confirm that. I just set up a clean installation.
[http://cleanwp.mbgrafik.de/__wc/new_order-01.jpg](http://cleanwp.mbgrafik.de/__wc/new_order-01.jpg)
[http://cleanwp.mbgrafik.de/__wc/new_order-01.jpg](http://cleanwp.mbgrafik.de/__wc/new_order-01.jpg)

**Comment by mbgrafik** [comment]
``
### WordPress Environment ###

Home URL: http://cleanwp.mbgrafik.de
Site URL: http://cleanwp.mbgrafik.de
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.14-nmm1
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.15
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (1) ###

WooCommerce: by WooThemes – 2.6.14

### Settings ###

Force SSL: –
Currency: BGN (лв.)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
``

**Comment by mikejolley** [comment]
Send it manually via the order admin panel. Thats where I'm testing and it's not doing this.

**Comment by mbgrafik** [comment]
When i manually send the New Order Email again, it is send to the shop-admin. The problem is, that the customer get's an automatic mail. And this contains the plain text from the admin mail (html and plain-text is different)
Feel free to do an order on the site to see it.

**Comment by mikejolley** [comment]
You can resend the 'processing' email too. Do that.

**Comment by mbgrafik** [comment]
i did. The manually send processing mail was ok. That does not solve the problem, since the order confirmation mail is send automatically to the customer, after the order is made. And this mail contains different content.

**Comment by mikejolley** [comment]
If you send plain only versions, what happens?

**Comment by mbgrafik** [comment]
Then everything is correct. 

[http://cleanwp.mbgrafik.de/__wc/plain-01.jpg](http://cleanwp.mbgrafik.de/__wc/plain-01.jpg)
[http://cleanwp.mbgrafik.de/__wc/plain-02.jpg](http://cleanwp.mbgrafik.de/__wc/plain-02.jpg)

**Comment by mbgrafik** [comment]
ok, here's what i did the last hour.

on the fresh install (WP 4.72 + WC 2.614) i installed WC via plugin install at wp backend.
With this fresh install the multipart-emails were messed up (as i wrote before, see screenshots)

Then i deleted WC 2.614 via ftp and replaced it with WC 2.64 -> did an order -> E-Mails where ok!
Then i deleted WC 2.64 via ftp and replaced it with WC 2.612 -> did an order -> E-Mails where ok!
Then i deleted WC 2.612 via ftp and replaced it with WC 2.614 -> did an order -> NOW - E-Mails where ok!

Do you have any idea, what went wrong here?

**Comment by mikejolley** [comment]
Nope unless a template had been changed in the WooCommerce folder.
