### ISSUE TITLE
Message only has text/html MIME parts. low delivery rate.

### ISSUE THREAD

**Issue by Tobias-Conrad** [woocommerce/woocommerce#13234]
## EXPLANATION OF THE ISSUE

https://www.mail-tester.com/web-rukav
in the "SpamAssassin thinks you can improve" shows this message:
MIME_HTML_ONLY
Message only has text/html MIME parts
You should also include a text version of your message (text/plain)

But i activated multipart email to sent on cmpleting order.

## STEPS TO REPRODUCE THE ISSUE

add the https://www.mail-tester.com/ random email address to the woocommerce order and complete order you will get your own status report.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://www.santegra-international.com
Site URL: https://www.santegra-international.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE_formal

### Server Environment ###

Server Info: nginx/1.10.2
PHP Version: 7.0.9
PHP Post Max Size: 100 MB
PHP Time Limit: 1200
PHP Max Input Vars: 3000
cURL Version: 7.47.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (59) ###

Advanced Database Cleaner: von Younes JFR. – 2.0.0
ARVE Advanced Responsive Video Embedder: von Nicolas Jonas – 8.0.5
Antispam Bee: von pluginkollektiv – 2.7.0
BackupBuddy: von iThemes – 7.2.2.4
Bring Back the Get Shortlink Button: von Thorsten Frommen – 1.1.0
Cachify: von pluginkollektiv – 2.3.0-dev
WP Comment List Builder: von Tobias B. Conrad – 3.6.2
Duplicate Post: von Enrico Battocchi – 3.1.2
Easy FancyBox - Pro extension: von RavanH – 1.5.3
Easy FancyBox: von RavanH – 1.5.8.2
Easy Theme and Plugin Upgrades: von Chris Jean – 2.0.0
Email Tracker: von Prashant Baldha – 0.4
Envato Market: von Derek Herman – 1.0.0-RC2
IgniteWoo Updater: von IgniteWoo.com – 2.1.9
Language Fallback: von Bernhard Kau – 1.0.3
Layered Popups: von Halfdata
Inc. – 6.02

Notely: von Michael Ott – 1.3
WooCommerce Product Filter: von Mihajlovic Nenad – 6.1.1
Pretty Link Pro: von Blair Williams – 2.0.4
Redirect Post to URL: von Stefan Böttcher – 1.0
Redirect to URL: von Marcel Fagas – 1.1.2
Schema Creator by Raven: von Raven Internet Marketing Tools – 1.1.1
Suchen & Ersetzen: von Inpsyde GmbH – 3.1.2
SearchWP Exclude UI: von Jonathan Christopher – 1.0.1
SearchWP Fuzzy Matches: von Jonathan Christopher – 1.4
SearchWP LIKE Terms: von Jonathan Christopher – 2.4.4.1
SearchWP German Stemmer: von Jonathan Christopher – 1.0.1
SearchWP Term Highlight: von Jonathan Christopher – 2.0.9
SearchWP Term Synonyms: von SearchWP
LLC – 2.4.9

SearchWP WooCommerce Integration: von SearchWP
LLC – 1.1.10

SearchWP Xpdf Integration: von Jonathan Christopher – 1.1.1
SearchWP: von SearchWP
LLC – 2.8.7

Simple Facebook Page Plugin: von Dylan Ryan – 1.4.15
Simple Page Tester Premium: von Simple Page Tester – 1.4.2
Simple Page Tester: von Simple Page Tester – 1.4.4
Simple Tooltips: von Justin Saad – 2.1.3
SEO by SQUIRRLY: von calinvingan
florinmuresan
nagy.sorel – 6.3.0

Tawk.to Live Chat: von Tawkto – 0.2.5
Timed Content: von K. Tough – 2.6
TinyMCE Advanced: von Andrew Ozz – 4.4.3
Vendidero Helper: von Vendidero – 1.1.3
WooCommerce Checkout Field Editor Pro: von ThemeHiGH – 2.5.3
WooCommerce Klarna Gateway: von WooThemes – 2.2.6
WooCommerce Germanized Pro: von Vendidero – 1.6.3
WooCommerce Germanized: von Vendidero – 1.8.1
WooCommerce Google Analytics Pro: von WooThemes / SkyVerge – 1.1.7
WooCommerce Quick Order Form: von IgniteWoo.com – 2.1.9
WooCommerce Sequential Order Numbers Pro: von WooThemes / SkyVerge – 1.10.1
WooCommerce Shipment Tracking: von WooThemes – 1.6.3
WooCommerce URL Coupons: von WooThemes / SkyVerge – 2.4.1
WooCommerce: von WooThemes – 2.6.14
WooCommerce Helper: von WooCommerce – 1.7.2
WP-Optimize: von David Anderson
Ruhani Rabin
Team Updraft – 2.1.0

Wordpress Rankie: von Atef – 1.6.2
WP SEO Structured Data Schema: von kcseopro – 2.0
WP Sitemap Page: von Tony Archambeau – 1.6
WooCommerce & WP Email Marketing Integration: von Tobias B. Conrad – 3.6.2
WpZeroBounce V2 DEV - unlimited: von Forcespark – 2
YITH WooCommerce Wishlist: von YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop-Basis: #1013 - /shop/
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /checkout/
Mein Konto: #9 - /mein-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome Child
Version: 3.0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.2.5
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome-child/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: Eid not set Secret key not set Checkout URL not set
Norway: Eid not set Secret key not set Checkout URL not set
Finland: Eid not set Secret key not set Checkout URL not set
Germany: ✔
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Terms Page: ✔
`

**Comment by Tobias-Conrad** [comment]
Anyone with the same issue (low WOO Mail delivery rate)? @bhubbard @pixeltrix @alepane21 @frozzare @cena

**Comment by mikejolley** [comment]
Not sure what is sending emails on your system, but I've confirmed multipart does send both plain and HTML versions.

You can see my screenshots in https://github.com/woocommerce/woocommerce/issues/13236 - I used mail catcher to display both parts. This is standard WP Mail and PHP Mail function sending the content (my local server does not send out to real addresses).

Adding those SPF/DKIM records will help you, as would using a decent mail delivery service such as Mandrill, Sendgrid etc. Those are much less likely to be marked as spam. I've heard of some hosts not sending HTML or multipart mail correctly and in those cases switching to a service resolves the issues. TBH, you should't use your own server if you're sending out a lot of mails anyway, especially on shared hosting where 'spammyness' is affected by other sites on the same server.

The only issue I did find, in 2.7 our plain versions contain JSON-LD markup which is not needed. I'm patching that now.

**Comment by deanoakley** [comment]
We are also having deliverability issues and came across the warning about MIME_HTML_ONLY ( how I found this issue ) which was fixed by changing it to multipart. 
Shouldn't multipart be the default setting?
