### ISSUE TITLE
"Dashboard" on My Account menu is linked to the wrong page.

### ISSUE THREAD

**Issue by raspberrysmile** [woocommerce/woocommerce#13232]
Hi,

I'm currently using Woocommerce version 2.6.14.

When I click on the "Dashboard" link from the "My Account" menu, it leads me to a 404 page error. This link wasn't created and doesn't exist in the menus, it seems to be generated by Woocommerce. How can I remove this link?

Thanks in advance.

![shicara](https://cloud.githubusercontent.com/assets/6565327/23094437/d2c6a0e0-f633-11e6-9e35-f52b6f177953.png)

**Comment by mikejolley** [comment]
WooCommerce does not generate links. If it's not in Appearance > Menus, your theme might be outputting it manually.
