### ISSUE TITLE
[2.7] Plugins displayed in wrong locale on admin

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#13248]
WP: 4.7.2
WC: latest master
Theme: Storefront 2.1.8
No other plugin activated.

To reproduce the issue, set the site locale to one language (say German). Set the user locale to a different language (say French) => The WooCommerce admin interface is displayed in English (while WordPress strings are kept in French as expected).

This also breaks the translation of every other plugins if I activate other plugins.
The issue is specif to 2.7 branch and not reproduced in 2.6.14

**Comment by mikejolley** [comment]
Just means you're missing a valid french translation. WordPress downloads these after updates, it's not handled by WooCommerce specifically.

**Comment by Chouby** [comment]
@mikejolley I was not saying that a few strings are not translated due to translations not updated yet.

I am reporting that WooCommerce unloads all plugins translations when the user locale is different from the site locale. Translations are correctly loaded if the user locale matches the site locale. It used to work correctly with WooCommerce 2.7-beta1. It does not work in 2.7-beta2.

Please test.

**Comment by Chouby** [comment]
Thanks :)
