### ISSUE TITLE
[2.7] Tax rate name changed when saving an order form admin 

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#13249]
WP: 4.7.2
WC: latest master
Theme: Storefront 2.1.8
No other plugin activated.

Create a Tax rate and assign it a tax name. Let say: "VAT"
Place an order.
Go in WooCommerce > Orders and edit the last order.
The order item correctly displays the tax rate name as "VAT" as expected.
Save the order.
The order item now displays the tax rate name as "VAT-1"

I do not reproduced this issue in 2.6.14.

**Comment by claudiulodro** [comment]
See #13253
