### ISSUE TITLE
[2.7] Inconsistent display of variation attributes

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#13244]
### EXPLANATION OF THE ISSUE

Chosen variation attributes are displayed inconsistently in the cart/checkout/order templates (and possibly other places).

Attribute definition example (mix of term-based / text): 
https://cl.ly/363s030v0N0G

Cart: 
https://cl.ly/3B1a3b1J2W1T

Order details: 
https://cl.ly/0X39203j3Z0Q

**Comment by mikejolley** [comment]
@franticpsyx Need to see your variation setup to check this. if this product has been used since earlier betas, save the variations first.
