### ISSUE TITLE
User Not Found after moved hosting

### ISSUE THREAD

**Issue by shaboyagan** [woocommerce/woocommerce#13251]
## EXPLANATION OF THE ISSUE

We have been using WooCommerce for a while and all has been running smoothly. We just moved hosting to a new company and when everything went back up last night I went in and needed to update a product. When I clicked update I got this error message below. I also see this error message in the back end Woo section in the Quickbooks tab where in says Generate Webconnector File. Below that I also get this error.

Now when we moved hosting and I created a new database, I couldn’t just use the same username and database name as I had at the previous host. New host attaches your id to the database name and user name so those are different now. I mention this because in the error the username (that is x out) that it references that doesn’t exist is the name of the new wordpress database I created.

Fatal error: Error Num.: 1146 Error Msg.:Table ‘xxxxxxxx_xxxxxxxxxxxxxxx.quickbooks_user’ doesn’t exist SQL: SELECT qb_username FROM quickbooks_user WHERE status = ‘e’ LIMIT 1 in /home2/l9w3k8s4/public_html/wp-content/plugins/woocommerce-quickbooks/QuickBooks/Driver/Sql/Mysql.php on line 376

## STEPS TO REPRODUCE THE ISSUE

When I clicked update on a woo product I got the error message above. I also see this error message in the back end Woo section in the Quickbooks tab where in says Generate Webconnector File.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://www.whiddengunworks.com
Site URL: http://www.whiddengunworks.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (26) ###

Akismet: by Automattic – 3.2
BackWPup: by Inpsyde GmbH – 3.3.6
Beaver Builder Plugin (Standard Version): by The Beaver Builder Team – 1.9.4
Black Studio TinyMCE Widget: by Black Studio – 2.3.1
Child Theme Configurator: by Lilaea Media – 2.2.4.1
Spam Protection by CleanTalk: by СleanTalk  – 5.58.2
Contact Form 7: by Takayuki Miyoshi – 4.6.1
Embed PDF: by Pat Hawks – 1.0.6
Export Users to CSV: by Ulrich Sossou – 1.0.0
HeadSpace2: by John Godley – 3.6.41
Insert PHP: by Will Bontrager Software
LLC  – 1.3

Jetpack by WordPress.com: by Automattic – 4.6
MailMunch - Increase your Email Subscribers by over 500%: by MailMunch – 2.0.4
Meta Slider: by Matcha Labs – 3.4.1
Responsive Photo Gallery: by Weblizar – 3.3.4
Scriptless Social Sharing: by Robin Cornett – 1.5.2
Simple Full Screen Background Image: by Pippin Williamson – 1.2
Simple Image Sizes: by Rahe – 3.1.1
SiteOrigin CSS: by SiteOrigin – 1.1.3
SiteOrigin Widgets Bundle: by SiteOrigin – 1.8.1
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri
Inc – 1.8.3

WC Password Strength Settings: by Daniel Santoro – 1.0.0
WooCommerce - Autocomplete Orders: by Serious Plugins – 1.1.4
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.5.8.1

SOD QuickBooks Connector for WooCommerce: by 61 Extensions – 1.3.15
WooCommerce: by WooThemes – 2.6.14

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #85 - /shop/
Cart: #87 - /cart/
Checkout: #89 - /checkout/
My Account: #91 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Vantage Premium Child
Version: 2.5.4.1473146928
Author URL: https://siteorigin.com/
Child Theme: ✔
Parent Theme Name: Vantage Premium
Parent Theme Version: 2.5.4
Parent Theme Author URL: https://siteorigin.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by mikejolley** [comment]
Firstly, this is an error coming from `SOD QuickBooks Connector for WooCommerce` not WooCommerce itself.

2nd, your migration may have led to new IDs for users etc. I'm not sure how you migrated, but you should migrate all tables without modifying contents. Ensure the user IDs match after migration.

Final, make sure this was changed to match the new database after migration https://codex.wordpress.org/Editing_wp-config.php#table_prefix
