### ISSUE TITLE
[2.7 Beta 3 - v1 API] Date paid is a timestamp

### ISSUE THREAD

**Issue by bryceadams** [woocommerce/woocommerce#13255]
## EXPLANATION OF THE ISSUE

Since beta 3, the `date_paid` attribute for an **order** is a timestamp. Previously it was a date time like `2017-01-01T17:22:08`. Is it intended?

cc @claudiosanches

**Comment by bryceadams** [comment]
On a similar note, and I want to check before creating issues for it, but the dates for orders in v1 of the API are now **all** in the store's timezone rather than UTC.

**Comment by claudiosanches** [comment]
@bryceadams we'll do store's timezone as a fix, since make more sense for most of people, that's why.
I'll check `date_paid`, thanks :)

**Comment by claudiosanches** [comment]
In 2.6.14 `date_paid` already returns a timestamp and in this case we'll keep, since change it will impact in change how should be handled.

**Comment by bryceadams** [comment]
hey @claudiosanches - just checked and `date_paid` is still a date time and not a timestamp in 2.6.14. I don't mind that much since if they are running 2.7+ and have the v2 api, that should be used, but still worth noting that existing code may break because of it.

with the timezones, i guess that makes sense but also may break some code.

going forward with the v2 API, all dates will always be UTC?

**Comment by claudiosanches** [comment]
@bryceadams in 2.6.14 is a timestamp https://github.com/woocommerce/woocommerce/blob/release/2.6/includes/api/class-wc-rest-orders-controller.php#L162 and not a date time.

**Comment by claudiosanches** [comment]
@bryceadams we could fix, but for sure will be hard for people that already is using the API to handle.

**Comment by thenbrent** [comment]
> @bryceadams in 2.6.14 is a timestamp https://github.com/woocommerce/woocommerce/blob/release/2.6/includes/api/class-wc-rest-orders-controller.php#L162 and not a date time.

@claudiosan `$order->paid_date` is a date time string. It maps to `WC_Abstract_Order::__get()`, which calls [`get_post_meta()` to get the `_paid_date` value](https://github.com/woocommerce/woocommerce/blob/release/2.6/includes/abstracts/abstract-wc-order.php#L1006) value, which is [set using `current_time( 'mysql' )`](https://github.com/woocommerce/woocommerce/blob/release/2.6/includes/abstracts/abstract-wc-order.php#L2493).
