### ISSUE TITLE
Rest API list all products - limit by attribute

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#13266]
## EXPLANATION OF THE ISSUE

WC-Version: 2.6.14
WP-Version 4.7.2

```
let requestData = {
      url: this.url+'wp-json/wc/v1/products/?attribute=pa_test',
      method: 'GET'
    };
```

Does return all products, also those not containing pa_test. (pa_test is the attribute slug)

This way I cant limit by attribute as needed.

**The documentation says it should work:**

> attribute	string	Limit result set to products with a specific attribute, e.g. ?attribute=pa_color.

But it doesnt. I know the slug is only named 'test' in woocommerce attribute backend, but when I request all attributes with api I get name: slug and slug: pa_test, so I tried with both test and pa_test with no luck. I also did try to change attribute to attributes, but does neither work. Also the function filter[attribute]=pa_test does not work.

Please look at it, I really need this.

## STEPS TO REPRODUCE THE ISSUE

**Having the given attribute:**

`[{"id":2,"name":"test","slug":"pa_test","type":"select","order_by":"menu_order","has_archives":false,"_links":{"self":[{"href":"http:\/\/store.output.one\/wp-json\/wc\/v1\/products\/attributes\/2"}],"collection":[{"href":"http:\/\/store.output.one\/wp-json\/wc\/v1\/products\/attributes"}]}}]`

Call get request to  /wp-json/wc/v1/products?attribute=pa_test&(authentication credentials...)

or

Call get request to  /wp-json/wc/v1/products?attribute=test&(authentication credentials...)

or

Call get request to  /wp-json/wc/v1/products?filter[attribute]=pa_test&(authentication credentials...)

or

Call get request to  /wp-json/wc/v1/products?filter[attribute]=test&(authentication credentials...)

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://store.output.one
Site URL: http://store.output.one
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: ❌ 51 MB - Vi anbefaler at du bruker minst 64MB minne. Se: Øke minne allokert for PHP
WP Debug Mode: –
WP Cron: ✔
Language: nb_NO

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.1
PHP Post Max Size: 96 MB
PHP Time Limit: 50
PHP Max Input Vars: 5000
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 96 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Fjernt innlegg: ✔
Fjernt 'Get': ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ MaxMind GeoIP Databasen finnes ikke - Geolocation vil ikke fungere. Du kan leste ned og installere manualt fra http://dev.maxmind.com/geoip/legacy/geolite/ til stien: . Skroll ned til \"Downloads\" og last ned \"Binary / gzip\" filen ved siden av \"GeoLite Country\"

### Active Plugins (4) ###

Coming Soon Page & Maintenance Mode by SeedProd: av SeedProd – 5.0.7
WooCommerce PayPal Express Checkout Gateway: av Automattic – 1.1.2
WOOF - WooCommerce Products Filter: av realmag777 – 1.1.6.1
WooCommerce: av Woothemes – 2.6.14

### Settings ###

Force SSL: ✔
Currency: NOK (kr)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Butikkbase: #53 - /
Handlekurv: #54 - /handlekurv/
Til kassen: #55 - /kassen/
Min konto: #56 - /min-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Storefront
Version: 2.1.7 – 2.1.8 er tilgjengelig
Author URL: https://woocommerce.com/
Child Theme: ❌ – Hvis du endrer WooCommerce eller et foreldertema du selv ikke bygget
anbefaler vi å bruke et dattertema. Se: Hvordan lage et dattertema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by claudiosanches** [comment]
You need to limit by attribute and term at the same time.

Example:

```
 /wp-json/wc/v1/products?attribute=pa_test&attribute_term=26
```

**Comment by steffanhalv** [comment]
@claudiosanches I think I already tried all available combinations with the attribute=pa_test&attribute_term=test (test = attribute value for attribute in product, stored in an object called options in the attribute returned by the api. I also tried to switch test with the number 3 which is the id of attribute with value test in one specific product. As far as I know, the actual 'term/value' doesnt have an id. ) This returns no results, but should return 1.

Where is the attribute term stored/where is your number 26 located?

 I still cant get it to work. Pleace explain and document this better, attribute_term is also not required from the docs.

**Comment by steffanhalv** [comment]
Also I tried all available attribute types

**Comment by claudiosanches** [comment]
@steffanhalv there is not `attribute=pa_test&attribute_term=test`, since `attribute_term` requires an ID and not a slug.

**Comment by steffanhalv** [comment]
Oh sorry, my fault. Now I got it working by first retrieve all attributes with api, then select id from one attribute to get all of its terms, then select all products limited by the given attribute slug and term id.

It would be nice if this for example was placed in the unit tests, so we better know how to use it. But thanks for help @claudiosanches
