### ISSUE TITLE
[2.7] Saving an order on admin side overwrites the existing tax rate label

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#13264]
On front, we can modify the tax rate label thanks to the filter `woocommerce_rate_label`. When we place an order, the filtered value of the label is stored in an order meta to be reused for example in emails.

If I place an order with a modified value of the tax rate label and then go to WooCommerce > Orders, edit and save the order (with no changes), this overwrites the value of the tax rate label previously stored (with the original label stored in the woocommerce_tax_rates table).

This is specific to the 2.7 branch as in 2.6.14 the label was kept unchanged when saving the order on admin side.

**Comment by mikejolley** [comment]
@Chouby can you grab master, not beta 3. There was a related patch earlier.

**Comment by Chouby** [comment]
Sorry I did not specify the test conditions. It was done with an up to date master branch, not beta 3.

If you are referring to #13253, the issue a bit different. Previously, the tax rate label was modified with the the rate code added. That's fixed.
 
But the PR does not fix the issue that the tax rate label is overwritten with a value different from the label originally saved with the order.

**Comment by mikejolley** [comment]
Got it. cc @claudiulodro

**Comment by mikejolley** [comment]
I'm filtering this and it's not changing after save. https://dl.dropboxusercontent.com/s/ngnmyzskb3vfexg/2017-02-22%20at%2014.00.png Keeps 'fish' as it's name :)

```
add_filter( 'woocommerce_rate_label', 'test_woocommerce_rate_label' );

function test_woocommerce_rate_label() {
	return 'fish';
}
```

**Comment by Chouby** [comment]
@mikejolley I was probably not clear enough. Sorry.

Try with: 

```php
add_filter( 'woocommerce_rate_label', 'test_woocommerce_rate_label' );

function test_woocommerce_rate_label( $label ) {
	return is_admin() ? $label : 'fish';
}
```

Place an order. The tax rate label is saved as 'fish' as expected. Edit the order on admin. It displays 'fish' as expected. Save the order. It does not display 'fish' anymore but the original unfiltered label.

Do the same in v2.6.14 and the tax rate label won't be modified.

That's because in 2.7, the tax rate label is resaved on admin while it was kept unchanged in 2.6.14. For me, that's a backward compatibility issue.

**Comment by mikejolley** [comment]
@Chouby Why would you want to not filter all labels? Why would one order be different to any other with the same rate?

**Comment by Chouby** [comment]
For multilingual websites, the tax rate label is depending on the language used by the customer when the order was placed.

**Comment by mikejolley** [comment]
@Chouby but you can see the problem with manual orders and adjusting orders right? If you add taxes or recalculate taxes, your label previously used is lost. It would be better to translate this via filter on the fly and store the language to the order meta.

**Comment by mikejolley** [comment]
Just like labels such as "total:" "shipping:" get translated as needed.

**Comment by Chouby** [comment]
I was working on the topic as the same time as you. I found a workaround even if I don't like it much. It uses the `woocommerce_rate_label` filter as suggested, reading the order id from `$_POST` and switches the locale to the order language to return the label in the right language. Switching the locale always comes with a performance impact, so if your PR is ok, that's better for me.  

NB1: "shipping" or "total" are much different because they are translated at output as usual for internationalized strings. So they are always in the correct language. The rate label is stored in DB. And the filter acts before the value is saved in DB. As far as I could see there is no filter at output for admin and emails. It causes some glitch on admin as it is displayed in the customer's language instead of the admin locale, but that's much better than displaying a label in the wrong language in emails to the customer.

NB2: I don't store the language as a meta but I use a taxonomy. You know why since you changed the product visibility from a meta to a taxonomy. How much did you wrote? 94%? ;-)
