### ISSUE TITLE
Different decimal separator in Spanish version in price and weight

### ISSUE THREAD

**Issue by carazo** [woocommerce/woocommerce#13268]
Good evening,

I am a WooCommerce user and plugin developer.

In Spanish version I have noticed that the decimal separator is different in price and weight.

- In prices WooCommerce asks for use commas as decimal separator (as it use to be in Spanish)
- In weight asks for use dots (as it is saved in database)

This is a little detail in which you can take care to improve Spanish users usability.

**Comment by mikejolley** [comment]
I thought it just depended on your browser's language. @claudiosanches?

**Comment by carazo** [comment]
Yes maybe, but the problem is that users are confused about what separator use in two fields that are inside the same metabox.

**Comment by mikejolley** [comment]
Does the placeholder not show this? Some locales treat decimals and currency differently.

**Comment by carazo** [comment]
Yes, the validation message says:
* Price: this is a monetary format use "," to separate...
* Weight: more or less same message but telling to use "."

**Comment by mikejolley** [comment]
I've checked it and it uses the server locale which can be changed with http://php.net/manual/en/function.setlocale.php

Prices work because you input those characters in settings. We don't collect other locale settings, we just use whatever is on the server.

**Comment by carazo** [comment]
Ok Mike perfect, thank you!

Maybe in a future, it would be a good idea to use the "locale" set in the installation in all the fields.

**Comment by kmmcita** [comment]
@mikejolley 
Hi, my server locale is it_IT.utf8, but weight still needs dots. Why? i've spent dozen of hours trying to get it working...
