### ISSUE TITLE
[2.7] Product gallery lightbox always opens the first image

### ISSUE THREAD

**Issue by dennyf** [woocommerce/woocommerce#13279]
## EXPLANATION OF THE ISSUE

With the **slider and zoom options enabled** in the product gallery, when you try to open any image in a lightbox, it always shows the first image in the lightbox.

## STEPS TO REPRODUCE THE ISSUE

1. Enable lightbox, zoom and gallery support
```
add_theme_support( 'wc-product-gallery-zoom' );
add_theme_support( 'wc-product-gallery-lightbox' );
add_theme_support( 'wc-product-gallery-slider' );
```
2. In the product gallery click on the last image for example and then click on the magnifying icon to open the lightbox
![img1](https://cloud.githubusercontent.com/assets/901213/23198535/6294a812-f91c-11e6-9be2-c5435a45b3ca.jpg)
3. The lightbox opens the first image instead of the selected image:
![img2](https://cloud.githubusercontent.com/assets/901213/23198549/7643e04e-f91c-11e6-8659-6db8bb54ce6a.jpg)

This issue happens with WooCommerce 2.7 beta 3, with any theme (including TwentySixteen)

**Comment by mikejolley** [comment]
This was fixed in master a few days back.
