### ISSUE TITLE
1 Cent tax is missing in total sum [2.6.14]

### ISSUE THREAD

**Issue by Bubelbub** [woocommerce/woocommerce#13272]
## EXPLANATION OF THE ISSUE

WooCommerce count the total amount on wrong way.

**This is shown in WooCommerce:**
![Shown in order details](https://cloud.githubusercontent.com/assets/319352/23190797/6134b3ea-f89a-11e6-8e31-f109d9b06275.png)

**Manually calculated total:**
**+** 21,18 € (Product)
**+** 2,02 € (Shipping / DHL)
**+** 4,41 € (Tax)
**= 27,61 €**
(WooCommerce shows 27,60 € that means -0,01 €)

## STEPS TO REPRODUCE THE ISSUE

Create product which cost 28 €. (with tax)
Create coupon which is 10 % per product.
Create shipping for 2,02 € (without tax).
Order it.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: https://bemarvelous.com
Site URL: https://bemarvelous.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.16
PHP Post Max Size: 512 MB
PHP Time Limit: 0
PHP Max Input Vars: 4000
cURL Version: 7.35.0
OpenSSL/1.0.1f

### Database ###

WC Database Version: 2.6.14:
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (5) ###
German Market: von MarketPress – 3.2.1
WooCommerce Google Analytics Integration: von WooThemes – 1.4.0
WooCommerce Multilingual: von OnTheGoSystems – 4.0.4
WooCommerce Sequential Order Numbers: von SkyVerge – 9.9.9
WooCommerce: von WooThemes – 2.6.14

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
```

Thanks in Advance for help 👍

**Comment by mikejolley** [comment]
I think you're just adding up rounded values. If you edit the line items you'll see some of them are .5 which is where your discrepancy comes from. We round for display, but the actual total calculation during checkout does not round prior. This prevents issues with things like discounts and taxes which are half-cent.
