### ISSUE TITLE
[2.7] Inconsistent Gallery Zoom

### ISSUE THREAD

**Issue by dennyf** [woocommerce/woocommerce#13278]
## EXPLANATION OF THE ISSUE

It looks like the gallery zoom feature depends on the first image size and it might not work depending on the image arrangement.

**To clarify, here is my setup using WC 2.7 beta 3 and TwentySixteen theme:**
* gallery element width: 380px
* img1 width: 300px
* img2 width: 600px

When img1 is set as main product image, the zoom doesn't work for any of the images.
When img2 is set as main product image, the zoom works for both images. For the smaller image (img1) it loads the original (not cropped) image when zooming, which works fine.

So it looks like  the zoom is either globally enabled or globally disabled for all the product images, only depending on the first image size.
You can see in [the code](https://github.com/woocommerce/woocommerce/blob/b0bf69aa014fa53f917cb2af964a34dac8e0b01f/assets/js/frontend/single-product.js#L143) that it compares the first image width with the gallery element width and when it's bigger, it enables the zoom for all the images.

Maybe the zoom should be enabled/disabled per image depending on the current image size instead of the first image size?

**Comment by mikejolley** [comment]
Zoom has to be init once, not init per image. So we only have the choice of on/off. It makes more sense to base this on the main product image than supporting gallery images IMO.

It's not hard to fix from the store owners size; use consistent product images :)
