### ISSUE TITLE
Pagination with filter parameter returns 404 error

### ISSUE THREAD

**Issue by pyodor** [woocommerce/woocommerce#13270]
## EXPLANATION OF THE ISSUE

Take a look the following filters:

**Working tested in 2.4.x, 2.5.x & 2.6.x**
/cabinets/?filter_color=20
/cabinets/page/2

**Working tested in 2.4.x & 2.5.x**
/cabinets/page/2/?filter_color=20

**Returns 404 error in 2.6.x** 
/cabinets/page/2/?filter_color=20

Tested it with any default themes but last filter above is very consistent to return 404 in 2.6.x, is there any explanation to this or a bug perhaps?

Thanks!

**Comment by mikejolley** [comment]
Not that I can see. I tested in 2.7 without issue: https://dl.dropboxusercontent.com/s/sqs1ae8yz0yeb3v/2017-02-23%20at%2013.04.png

Same on 2.6.x, I just switched and still had no 404. I can only presume it's a conflict with a plugin or something else with your category structure. It's not clear from your issue if you're doing something such as removing permalink base - this would cause issues with this and other endpoints.
