### ISSUE TITLE
[2.7] WC_Order::$post_status returns incorrect value

### ISSUE THREAD

**Issue by maxrice** [woocommerce/woocommerce#13273]
## EXPLANATION OF THE ISSUE

In 2.7, accessing `WC_Order::$post_status` returns the WC order status, not the status of the underlying post object as it was in previous versions. While accessing these properties is now deprecated and throws a notice, the value returned should be consistent between versions.

## STEPS TO REPRODUCE THE ISSUE

- Hook into `woocommerce_order_number` and add an admin order
- Calling `$order->post_status` in 2.7 returns `wc-pending`, whereas 2.6 returns `auto-draft`

## Resolution

I think that [this line](https://github.com/woocommerce/woocommerce/blob/2.7.0-beta-3/includes/legacy/abstract-wc-legacy-order.php#L420) should be changed to return the post status which matches how [2.6 and below handled it](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/abstracts/abstract-wc-order.php#L965).

**Comment by thenbrent** [comment]
While dealing with this, the `trash` status could be addressed too. There is no such thing as a `trash`ed order status, but it's an important post status that has no equivalent in 2.7.
