### ISSUE TITLE
[2.7] Should array access to return results from functions that no longer return arrays fire a deprecation notice?

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#13287]
There appear to be a number of methods in WC 2.7 (testing on beta 3) which in WC 2.6 returned arrays, but now return objects that implement array access.

This can lead to silent failure. If the developer has checked the data returned from the function with is_array(), in accordance with what's expected from the WC 2.6 function signature, then this check now fails, with no way for the developer to find out, other than by bissecting his code.

e.g. WC_Order::get_taxes() used to return an array; now returns a WC_Order_Item_Tax object. So, existing code that did an is_array() check on the result fails.

I see no obvious solution to this, and perhaps there isn't one. But it might at least be worth mentioning on a porting example on the blog - I've not seen it mentioned anywhere I've looked. Apologies if I missed something.

**Comment by DavidAnderson684** [comment]
Sorry - the above example is slightly wrong. WC_Order::get_taxes() used to return an array of arrays; now it returns an array of WC_Order_Item_Tax objects. The code example I was looking at did an is_array() check on these second-level objects.

**Comment by mikejolley** [comment]
This one isn't fixable because `is_array` explicitly checks the type. I'll list this in https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-2.7.x-Developer-Migration-Notes

**Comment by DavidAnderson684** [comment]
Thanks. A list of places where this potentially applies would be useful, as these sorts of issues are particularly nasty to track down.

**Comment by DavidAnderson684** [comment]
Are the WC 2.7 WC_Order_Item_Tax objects meant to have any sort of backwards-compatibility with the the arrays that were returned in WC 2.6?

For example, I'm doing this (simplified):

```
$total = 0;
$taxes = $order->get_taxes();
foreach ($taxes as $tax) {
  $total += $tax['tax_amount'];
}
```

That doesn't work on WC 2.7, because `$tax['tax_amount']` is undefined/null.

**Comment by mikejolley** [comment]
Yeah, can you try https://github.com/woocommerce/woocommerce/pull/13284

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-2.7.x-Developer-Migration-Notes#array-return-values-being-swapped-out-with-objects-implementing-arrayaccess

**Comment by DavidAnderson684** [comment]
Just to confirm that #13284 worked for me.

**Comment by DavidAnderson684** [comment]
That was premature... it doesn't work. I can now access some of the values. But not all. I will open a new issue.
