### ISSUE TITLE
How does WooCommerce perform IPN verification with PayPal?

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#13280]
Does WooCommerce force use of TLS 1.2 and HTTP/1.1 ?
https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1914&viewlocale=en_US

I'm asking because the email said to check with the software provider :)

This is the email received from PayPal:

As a leading payment provider, security is our number one priority and PayPal continually invests and innovates to deliver the strongest protection possible.  In some instances, this means adapting to our environments and upgrading merchant integrations to the current industry standards, like those set by the Payment Card Industry (PCI) Security Standards Council. We appreciate your patience and support of protecting our customers and their payments.

To better assist customers with these security updates, we’ve created the following materials to further clarify this technical update:

[2016-2017 Merchant Security Roadmap](http://links.mkt2944.com/ctt?kn=8&ms=NTM0NzAwNjkS1&r=MjE0NDg0MzQyMzM3S0&b=0&j=MTEwMzUwMTY0NQS2&mt=1&rt=0)

[TLS 1.2 and HTTP/1.1 Upgrade Roadmap](http://links.mkt2944.com/ctt?kn=17&ms=NTM0NzAwNjkS1&r=MjE0NDg0MzQyMzM3S0&b=0&j=MTEwMzUwMTY0NQS2&mt=1&rt=0)

[PayPal security guidelines and best practices](http://links.mkt2944.com/ctt?kn=6&ms=NTM0NzAwNjkS1&r=MjE0NDg0MzQyMzM3S0&b=0&j=MTEwMzUwMTY0NQS2&mt=1&rt=0)

We also encourage you to speak with your web hosting company, **e-commerce software provider** or in-house web programmer/system administrator for further assistance in implementing these changes, if needed.

Scheduled change dates provided in this email and on the TLS 1.2 and HTTP/1.1 Upgrade Microsite are subject to change. Please monitor our TLS 1.2 and HTTP/1.1 Upgrade Microsite for the most up-to-date information.

Below are a few key points concerning security updates we will begin implementing after June 30, 2017 and we strongly recommend your systems be compatible to ensure your business is not disrupted:

The PayPal Sandbox, or testing environment, has been upgraded to allow only TLS 1.2 and HTTP/1.1 connections.

All  production endpoints will be updated to accept only TLS 1.2 and HTTP/1.1 connections after June 30, 2017.  Please note that if you haven’t made the necessary upgrades to your systems to become compliant, your business will be unable to accept payments with PayPal until the required changes have been made.

A  verification endpoint is available, which can be found at https://tlstest.paypal.com and has the latest security standards so customers can quickly check if their systems are ready to accept transactions after June 30, 2017.

There are four remaining areas that our security upgrades will impact and we’ve identified the areas that need your attention. The chart below shows whether you’ll need to make changes, or if your business is already compliant or doesn’t use that functionality:

TLS 1.2 and HTTP/1.1 Upgrade – Complete by June 30, 2017
Update Needed: Yes

IPN Verification Postback to HTTPS – Complete by June 30, 2017
Update Needed: No

Discontinue Use of GET Method for Classic NVP/SOAP API’s – Complete by June 30, 2017
Update Needed: No

Merchant API Certificate Credentials Upgrade – Complete by January 1, 2018
Please note that this may be completed earlier based on the expiration date of your certificate
Update Needed: No

**Comment by mikejolley** [comment]
Yes it's forced and should be handled :)
