### ISSUE TITLE
got JSON object result in POSTMAN but in browser it is showing “Consumer Key is invalid”

### ISSUE THREAD

**Issue by pramod1k** [woocommerce/woocommerce#13291]
Issue with Woocommerce REST API, OAuth 1.0a server {"code":"woocommerce_rest_authentication_error","message":"Consumer Key is invalid.","data":{"status":401}}

To generate JSON Objects for iOS and Android development I used json-api, REST API and OAuth 1.0a server for authentication. The issue here is I am getting objects in POSTMAN but not in Browser. Please help me out of this problem, wait is this an issue? 
Anyone faced this issue pl support me.

![snashot2](https://cloud.githubusercontent.com/assets/25957041/23217814/7eccb578-f940-11e6-8526-6aa780fbe327.png)

![snapshot1](https://cloud.githubusercontent.com/assets/25957041/23217848/917192ac-f940-11e6-8040-366249e1495f.png)

Thanks

**Comment by mikejolley** [comment]
We've fixed this in 2.7. WordPress auth conflicts when you're logged in. https://github.com/woocommerce/woocommerce/issues/13134

**Comment by pramod1k** [comment]
So I have to wait until 2.7 release date or I have to install Beta version. 
Let me ask you one thing, can I have any possible resolution with my current version i.e., 2.6.12 version.

Thanks.

**Comment by claudiosanches** [comment]
@pramod1k 2.7 beta is only for testing and not should be used in live sites. So pleae wait until 2.7 release date.
