### ISSUE TITLE
International endpoints for edit-address/billing and edit-address/shipping

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#13293]
This functionality was added a while ago: https://github.com/woocommerce/woocommerce/issues/4820

This allows the edit-address/billing and edit-address/shipping to be translated to a localized string. But it seems this only works when the edit-address endpoint is defined as edit-address. When it is changed to a localized string the /billing /shipping endpoints no longer translate correctly.

This is because in the function `wc_get_endpoint_url` it does the following comparison:

```
$value = ( 'edit-address' == $endpoint ) ? wc_edit_address_i18n( $value ) : $value;
```

This means it will only run the wc_edit_address_i18n function if the endpoint is actually called `edit-address`. I would suggest to change it to something like this:

```
$value = ( get_option( 'woocommerce_myaccount_edit_address_endpoint', 'edit-address' ) == $endpoint ) ? wc_edit_address_i18n( $value ) : $value;
```

I have tested this on a basic install of WooCommerce and switching to the Spanish language. After this change I'm able to change the edit-address endpoint.
Which gives me the following URL when editing the shipping address:
`/mi-cuenta/direcciones/facturacion/`

**Comment by losingle** [comment]
```php
$value = ( get_option( 'woocommerce_myaccount_edit_address_endpoint', 'edit-address' ) == $endpoint ) ? wc_edit_address_i18n( $value ) : $value;
```
If you do this, it will result in an incorrect link address in Chinese character.
eg. my-account/edit-address/账单/ 
In China, we do not recommend including Chinese character in the link address.
