### ISSUE TITLE
[2.7] State Selector at Checkout - Accessibility Decreased

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#13300]
## EXPLANATION OF THE ISSUE

When using checkout, the state / province select will use an enhanced select. In previous versions, you could tab to this field from the city field, then begin typing, and it would search for state automatically.

In 2.7 the new select2 makes it much more difficult to use keyboard shortcuts to tab over to this field, then to resume checking out after using it.

## STEPS TO REPRODUCE THE ISSUE

1. Go to the checkout page
1. Begin filling in a billing address, **only** tabbing to go from one field to the next.
1. Tab to the "state" selector and start typing.

You'll see this doesn't start to immediately search the choices in the dropdown, while older versions will do so.

1. You'll need to hit "space", then the field is focused / searchable.
1. Begin typing your state to search for it.
1. Select the state by hitting "enter"

Now you'll see that your tab order is entirely reset on the page rather than taking you to the next field.

So to recap, in WC < 2.6, it's possible to tab seamlessly between fields. Tabbing _to_ an enhanced select will automatically let you search, then you can tab over to make a selection / go to the next field. Hitting enter or space isn't necessary.

In WC 2.7, you can tab _to_ the field, but must (1) hit "space" to search, (2) search for your value, and (3) hit enter to select the value, which now resets the tab order and forces you to tab through all fields again to keep filling out the checkout form.

So this means anyone using keyboard shortcuts for accessibility to navigate a checkout form has just almost doubled the amount of time it takes them to check out due to the need to figure out that you have to focus the field, then reset the tab index to get back to the same spot (then obviously you need to do this for each enhanced select if there are shipping fields or other options at checkout).

**Comment by BurlesonBrad** [comment]
I don't _(personally)_ have accessibility needs and I tab-the-forms **all the time!**
So, I went back to some recorded heatmaps running WC Beta on 3 staging.wpe.com sites & found users bouncing back and forth in those fields @bekarice mentioned.
Consequently this should be seen as a _**"universal"**_ & not just an _"accessibility / opinion / subjective"_ issue.
If the jquery is left unfixed before ~2/27~ 3/7 push, I can see this being a conversion killer contributor.

**Comment by mikejolley** [comment]
Let's not compare this to select v3. V3 has it's own set of accessibility issues so downgrading is not an option here. Comparing to REAL select boxes:

- Typing does nothing when in focus
- Spacebar expands the options

Select2 v4 is consistent with this. In addition, enter also expands the options. 

Tabbing is the only issue we should look at fixing here.

**Comment by mikejolley** [comment]
https://github.com/select2/select2/issues/4384
