### ISSUE TITLE
error filter

### ISSUE THREAD

**Issue by Max1991max** [woocommerce/woocommerce#13308]
in the settings you show products in price order and the site all on the contrary

![2017-02-23 13-41-45](https://cloud.githubusercontent.com/assets/25979017/23255780/e495491e-f9cd-11e6-8cda-1399ee1284f3.png)
![2017-02-23 13-33-39](https://cloud.githubusercontent.com/assets/25979017/23255800/f2e71380-f9cd-11e6-9043-91e8aa297758.png)

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Not sure what your reporting here?

**Comment by mikejolley** [comment]
Price ordering doesn't appear broken.
