### ISSUE TITLE
[WC 2.7 beta 3] get_manage_stock() never returns 'parent' for variations.

### ISSUE THREAD

**Issue by reidbiztech** [woocommerce/woocommerce#13315]
Create a variable product with two variations. Set it to manage stock at product level, and enable stock management for one of the variations but not the other.

For the variation without stock management enabled, get_manage_stock() returns true, not 'parent' as it would appear is intended in the code.

If I can figure out where the issue is, I'll let you know, but the new product/variation class structure is so radically different in WC 2.7 it may take me a few weeks to grok it.

**Comment by mikejolley** [comment]
@reidbiztech default context? Where is `get_manage_stock` being called and how? Please reference the calling code.

**Comment by reidbiztech** [comment]
From within a WP_List_Table class extension populated with a WP_Query very similar to that in:
https://woocommerce.com/products/bulk-stock-management/
(which is going to need a major re-write for WC 2.7, along with other significant extensions such as Square and Subscriptions, none of which show any signs of work for WC 2.7 yet)

Except my implementation makes allowances for orphaned variations in WC =< 2.6 and other quirks not accounted for in Bulk Stock Management

So in my WP_List_Table class column_default function for the manage_stock case I currently have

```php
switch( $column_name ) {
...
	case 'manage_stock' :
		if ( WBS_WC_Versions_Compat::is_wc_version_gte( '2.7' ) ) { // WC >= 2.7
			switch ( $product->get_manage_stock() ) {
				case true:
					return '<mark class="yes">' . esc_html__( 'Yes', 'wbs-supply-management' ) . '</mark>';
					break;
				case false:
					return '<span class="na">&ndash;</span>';
					break;
				case 'parent':
					return '<mark class="yes">' . esc_html__( 'Parent', 'wbs-supply-management' ) . '</mark>';
					break;
			}
		} else { // WC < 2.7
			if ( $product->is_type( 'variation' ) && $product->managing_stock() && $product->__get('manage_stock') == 'no' ) {
				return '<mark class="yes">' . esc_html__( 'Parent', 'wbs-supply-management' ) . '</mark>';
			} else {
				return ( $product->managing_stock() ) ? '<mark class="yes">' . esc_html__( 'Yes', 'wbs-supply-management' ) . '</mark>' : '<span class="na">&ndash;</span>';
			}
		}
```

I think I may see the problem... it looks like in Bulk Stock Management (and my adaptation of it) that the WP_List_Table class prepare_items function that the products/variations are not being instantiated as woo products...?

**Comment by reidbiztech** [comment]
Trying to wrap my head around this 2.7 code:

```php
	protected function get_prop( $prop, $context = 'view' ) {
		$value = null;

		if ( array_key_exists( $prop, $this->data ) ) {
			$value = isset( $this->changes[ $prop ] ) ? $this->changes[ $prop ] : $this->data[ $prop ];

			if ( 'view' === $context ) {
				$value = apply_filters( $this->get_hook_prefix() . $prop, $value, $this );
			}
		}
		return $value;
	}
```

I guess we need to figure out how the WC_Data object is linked to a WC_Product object in order to determine how it relates to the WC_Product object properties? Then determine how the get_hook_prefix() comes into play when determining a WC_Product object's properties?

I'll keep slogging through the new code to see if I can figure out how it is intended to work...

**Comment by mikejolley** [comment]
@reidbiztech `get_manage_stock` when called on a variation, without any args, will return `parent`. If you however call it in `edit` context (used for saving the value to the database) it will not return `parent`.

Is `$product` in your example a variation or variable product?

**Comment by reidbiztech** [comment]
As described above, the $product in my example is a variation of a variable product where the parent variable product has stock management enabled, and the variation in question does not.

I think you may need to look at the WooCommerce authored Bulk Stock Management extension to see how some (many actually) extensions need to process both simple, variable and variations all in one place.

The $context, as far as I can tell, is the default ('view') - still trying to figure out exactly what that means.

**Comment by reidbiztech** [comment]
>@reidbiztech get_manage_stock when called on a variation, without any args, will return parent. If you however call it in edit context (used for saving the value to the database) it will not return parent.

I see that, as present in:
```php
	/**
	 * Return if product manage stock.
	 *
	 * @since 2.7.0
	 * @param  string $context
	 * @return boolean|string true, false, or parent.
	 */
	public function get_manage_stock( $context = 'view' ) {
		$value = $this->get_prop( 'manage_stock', $context );

		// Inherit value from parent.
		if ( 'view' === $context && false === $value && true === wc_string_to_bool( $this->parent_data['manage_stock'] ) ) {
			$value = 'parent';
		}
		return $value;
	}
```

And that is what you would expect. But have you actually tested this? I'm telling you I have, and it does not behave as expected.

I suspect what is happening is that somewhere along the line, the first get_prop call is picking up the parent setting, so the variation version of the get_manage_stock will never be false and then look to the parent...

But I am having some trouble trying to track down where this actually happens given the major rewrite of WC we are looking at in 2.7...

**Comment by reidbiztech** [comment]
So, continuing my analysis at the WC_Product_Variable_Data_Store_CPT class, I see:

```php
	/**
	 * Stock managed at the parent level - update children being managed by this product.
	 * This sync function syncs downwards (from parent to child) when the variable product is saved.
	 *
	 * @param WC_Product
	 * @since 2.7.0
	 */
	public function sync_managed_variation_stock_status( &$product ) {
		global $wpdb;

		if ( $product->get_manage_stock() ) {
			$status           = $product->get_stock_status();
			$children         = $product->get_children();
			$managed_children = $children ? array_unique( $wpdb->get_col( "SELECT post_id FROM $wpdb->postmeta WHERE meta_key = '_manage_stock' AND meta_value != 'yes' AND post_id IN ( " . implode( ',', array_map( 'absint', $children ) ) . " )" ) ) : array();
			$changed          = false;
			foreach ( $managed_children as $managed_child ) {
				if ( update_post_meta( $managed_child, '_stock_status', $status ) ) {
					$changed = true;
				}
			}
			if ( $changed ) {
				$children = $this->read_children( $product, true );
				$product->set_children( $children['all'] );
				$product->set_visible_children( $children['visible'] );
			}
		}
	}
```

Lets look at this carefully, that prefix "sync" has me concerned....

**Comment by mikejolley** [comment]
You should be able to test this out of the scope of the list table. Use `wc_get_product` on the variation ID and then see what the value returns. I'll test my side shortly.

**Comment by reidbiztech** [comment]
Thanks for the suggestion, the same occurred to me, and I already tried that, as noted in an edit above:

>nope, that's not it... creating a new WC_Product with wc_get_product() for the Woo 2.7 code blocks makes no difference - same result.

**Comment by mikejolley** [comment]
I just tried myself. 

Variable product with manage stock ON.
Variation with manage stock OFF.

Variation ID is 184.

`
$variation = wc_get_product( 184 );

echo '<pre>';
echo 'ID:';
echo $variation->get_id();
echo '<br />Type:';
echo $variation->get_type();
echo '<br />Manage stock:';
var_dump($variation->get_manage_stock());
echo '<br />Manage stock edit context:';
var_dump($variation->get_manage_stock( 'edit' ));
echo '</pre>';
`

![2017-02-23 at 18 16](https://cloud.githubusercontent.com/assets/90977/23272714/3e3d522e-f9f4-11e6-972a-08d041f3611f.png)

**Comment by reidbiztech** [comment]
Thanks for testing! That is what I would expect to happen.

I wonder what is different in my install... did you test that on trunk or the beta 3 tag?

I will make a new test completely separate from my list class and see what I get, and then test trunk vs beta 3 and see what I get.

Thanks for the responses, much appreciated!

**Comment by mikejolley** [comment]
I always run master, but I don't recall any changes with this code in particular.

Are you sure it's not a logic error in your code? Your switch statement... true. 'parent' IS true if you convert to bool.

**Comment by reidbiztech** [comment]
I'm an idiot.

>Are you sure it's not a logic error in your code? Your switch statement... true. 'parent' IS true if you convert to bool.

Bingo. Rearranging the switch...:

```php
switch ( $product->get_manage_stock() ) {
	case 'parent':
		return '<mark class="yes">' . esc_html__( 'Parent', 'wbs-supply-management' ) . '</mark>';
		break;
	case true:
		return '<mark class="yes">' . esc_html__( 'Yes', 'wbs-supply-management' ) . '</mark>';
		break;
	case false:
		return '<span class="na">&ndash;</span>';
		break;
}
```

...and I get what I would expect. So sorry to have wasted your time. Thanks for your insight.

That'll teach me to be lazy and use switch instead of full curly braced ifs. Though I guess ifs would be vulnerable to this too. Guess I just have to be more careful with mixed type returns like this.

**Comment by reidbiztech** [comment]
So now my full 'manage_stock' case:

```php
case 'manage_stock' :

	if ( WBS_WC_Versions_Compat::is_wc_version_gte( '2.7' ) ) { // WC >= 2.7
			$product_is_managing_stock = $product->get_manage_stock();
			if ( is_bool( $product_is_managing_stock ) === true ) {
				if ( $product_is_managing_stock === true ) {
					return '<mark class="yes">' . esc_html__( 'Yes', 'wbs-supply-management' ) . '</mark>';
				}
				if ( $product_is_managing_stock === false ) {
					return '<span class="na">&ndash;</span>';
				}
			} else if ( $product_is_managing_stock == 'parent' ) {
				return '<mark class="yes">' . esc_html__( 'Parent', 'wbs-supply-management' ) . '</mark>';
			}
	} else { // WC < 2.7
		if ( $product->is_type( 'variation' ) && $product->managing_stock() && $product->__get('manage_stock') == 'no' ) {
			return '<mark class="yes">' . esc_html__( 'Parent', 'wbs-supply-management' ) . '</mark>';
		} else {
			return ( $product->managing_stock() ) ? '<mark class="yes">' . esc_html__( 'Yes', 'wbs-supply-management' ) . '</mark>' : '<span class="na">&ndash;</span>';
		}
	}

break;
```

Lesson learned. The hard way.
