### ISSUE TITLE
woocommerce_form_field() + type='password'

### ISSUE THREAD

**Issue by apermo** [woocommerce/woocommerce#13312]
## EXPLANATION OF THE ISSUE
When adding a custom field to the checkout with type='password', the default behavior seems to be that, once saved, to return the password as value for the input field.

https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L1994

I think this is not desirable. 
In my opinion the default should be:

```
case 'text' :
case 'email' :
case 'tel' :
case 'number' :
$output_value = $value;

case 'password' :

$field .= '<input type="' . esc_attr( $args['type'] ) . '" class="input-text ' . esc_attr( implode( ' ', $args['input_class'] ) ) . '" name="' . esc_attr( $key ) . '" id="' . esc_attr( $args['id'] ) . '" placeholder="' . esc_attr( $args['placeholder'] ) . '"  value="' . esc_attr( $output_value ) . '" ' . implode( ' ', $custom_attributes ) . ' />';
break;
```

Or something alike, this way it would be default not to return a password to plain html, while keeping $value intact.
That way it's possible to put the $value back into the output using

`$field = apply_filters( 'woocommerce_form_field_' . $args['type'], $field, $key, $args, $value );`
https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L2060

**Comment by mikejolley** [comment]
Why and for what use case? It's still stored as plain text - not anything sensitive is it?

**Comment by apermo** [comment]
I needed a password field for a login to get credentials for single sign on of our company, and I want to get these as late as possible, so I asked for it in the checkout.

I can't tell for sure if it ever would get returned anyway, but just looking at that line of code, it would be returned if it had been stored before. And returning a password as value is something that I learned is bad practice. So instead of having this as default with the filter as option to remove it, it should be other way round. At least that's my opinion.

Probably should be at least discussed.

**Comment by mikejolley** [comment]
> And returning a password as value is something that I learned is bad practice

A password field does not protect the contents. You can view it in the DOM. You can view it in the database. You can view it in the API. Adding password field support to backend does not make this any safer.

**Comment by mikejolley** [comment]
Looking at the code it is handled correctly; value passed to 'password' input field. If you need to keep this private, don't add via our fields API. Store it elsewhere/not at all.
