### ISSUE TITLE
[2.7] How to correctly disable scheduled email notifications

### ISSUE THREAD

**Issue by vendidero** [woocommerce/woocommerce#13318]
Hi there.

I'm currently doing some tests to ensure WC 2.7 compatibility.

Seems like transactional emails are now being queued with `wp_schedule_event` which leads to my question: How is it possible to disable sending a specific transactional email / notification on runtime? 

Example: Under certain circumstances I do not want to (re)send transactional emails for orders e.g. when the order status changes. This is how I achieved that within WC 2.6:

```php
$statuses = array(
	'woocommerce_order_status_' . $default_status . '_to_processing',
	'woocommerce_order_status_' . $default_status . '_to_completed',
	'woocommerce_order_status_' . $default_status . '_to_cancelled',
	'woocommerce_order_status_' . $default_status . '_to_on-hold',
);

// Temporarily remove all notifications		
foreach ( $statuses as $status )
	remove_all_actions( $status . '_notification' );

// Update to default
$order->update_status( $default_status );
```

Unfortunately this doesn't work in 2.7 - Removing the actions has no effect because the scheduled event executes on a new pageload. 

I've now tried to unschedule the event right after WooCommerce schedules the event for the transactional email - but this seems more like a hack to me..

Cheers

**Comment by mikejolley** [comment]
Using remove_all_actions is still possible - the same hooks are ran, just later on the schedule.

**Comment by vendidero** [comment]
Hi there,

hm, I tried - but it doesn't work. Emails still get sent. It actually can't work as far as I understand it:

1. `remove_all_actions` -> removes the notification
2. `$order->update_status()` is called
3. Emails get scheduled
4. Schedule executes (new page load) -> Notifications are being reset to default because `remove_all_actions` is not executed
5. Transactional email is being sent

The above code is only called once when the order is being saved (or a new order is being generated or whatever) - that's why `remove_all_actions` has no effect within the scheduled event.

**Comment by mikejolley** [comment]
You know how remove_all_actions works? It removes actions after they have been added. You need to make sure they are removed after the actions are enqueued when the cron job runs.

**Comment by vendidero** [comment]
Hi there,

yes, I think I know how it works. This is actually quite fiddly because I will need to temporarily flag the specific order with some meta field to make sure hooks get removed when the scheduled event executes. Seems like scheduling the emails will lead to some compatibility problems.

**Comment by mikejolley** [comment]
If you send a PR as I'm leaving shortly, you could add a conditional around the code which schedules the event, passing the event and args. This could then be used to stop it scheduling.

This way is way more performant during checkout so I'd be reluctant to revert.

**Comment by claudiulodro** [comment]
@vendidero you can prevent the scheduling of the e-mails using the [woocommerce_email_actions](https://github.com/woocommerce/woocommerce/blob/e97d30859c10b14dfd4c4be66dc4af69f0bd4df3/includes/class-wc-emails.php#L64) or [schedule_event](https://codex.wordpress.org/Plugin_API/Filter_Reference/schedule_event) filters.

e.g.
```
if ( $turn_email_scheduling_off ) {
    add_filter( 'woocommerce_email_actions', function( $actions ) {
        return array();
    } );
}
```
or:
```
if ( $turn_email_scheduling_off ) {
    add_filter( 'schedule_event', function( $event ) {
        if ( 'woocommerce_send_queued_transactional_email' == $event->hook ) {
            return false;
        }
        return $event;
    } );
}
```
or you can just remove email scheduling action from any of the `'woocommerce_order_status_*' actions:
```
remove_action( 'woocommerce_order_status_pending_to_processing', array( WC_Emails, 'queue_transactional_email' ) );
```

**Comment by vendidero** [comment]
Hi there,

the first two approaches came to my mind as well but I think that they aren't the ideal solution.
The last approach seems pretty good to go, I'll try an implementation and if everything works out, we won't need a conditional. The "trick" is to actually remove the actions while hooking into: 

´´´php
do_action( 'woocommerce_order_status_' . $this->status_transition['to'], $this->get_id(), $this );
´´´

that way we have access to the specific order data and can conditionally remove transactional emails.

Thanks!

**Comment by mikejolley** [comment]
I still think a dedicated hook would be simpler going forward so I'll add that too if it's possible.

**Comment by krbvroc1** [comment]
@mikejolley This issue was referenced in the 2.x -> 3.0 migration guide. What about those of us who have disabled WP_Cron. How are email notifications going to work? Now we have to run system cron at much more frequent intervals to handle email notifications?

**Comment by mikejolley** [comment]
@krbvroc1 Well, you could always send it with a filter and do it right now instead of via cron, but thats your decision to disable the cron. We're only making use of an API in WordPress.

**Comment by krbvroc1** [comment]
@mikejolley It is also a feature/API unpopular enough that there is a supported DISABLE_WP_CRON in the wp config. A better design would have been to POST back to your self so that the notifications were sent in a separate server request and it would have been backwards compatible.

**Comment by claudiosanches** [comment]
Still if you have have you server configured to trigger CRON every 5 minutes, all emails will be sent in max of 5 minutes.

**Comment by krbvroc1** [comment]
@claudiosanches I currently have it disabled and run wp-cron via an actual cron job every 24 hours. So if someone wants responsive emails sent for order transactions, including transactional email including links to purchased content, you will need to run this frequently. 5 minutes is probably too long to wait for those emails. Of course people on hosts that do not provide system level cron, will have to wait for additional http request to hit their server before the wp-cron even runs. That is fine on a busy site, but during idle periods everything will be queued and delayed until the next site visitor.

**Comment by claudiosanches** [comment]
@krbvroc1 I'm not a fan of wp-cron and I prefer just use crontab, still 24 hours it's something that is really going wrong, even for a blog, this is a problem with webhooks, sale prices and serveral other things on WooCommerce and WordPress. So it's clear that you already doing something wrong now and it will not change after you update to 3.0.

> 5 minutes is probably too long to wait for those emails.

This depend on the payment gateway, some payment gateways will just leave the order as pending and will not trigger any email, triggering only after by IPN, sometimes more than 5 minutes, but depends on the payment gateway.

**Comment by claudiosanches** [comment]
@krbvroc1 what do you prefer? 1 minute to place an order because your server is sending an email or delay an email for 5 minutes?

**Comment by mikejolley** [comment]
@krbvroc1 

>  It is also a feature/API unpopular enough

Why are you assuming that because something can be disabled it's unpopular? You can disable our emails, are they unpopular? :p 

I think it can be disabled and replaced because some sites have issues with reliability. If you disable it, make sure they run frequent enough for your use case.

**Comment by krbvroc1** [comment]
@mikejolley It is unpopular because it has long been known to be a poor design and create performance issues. Running queued wp-cron entries in the context of a subsequent possibly unrelated visitor at an in-deterministic time is poor design. However it is the only option for some people depending on their hosting environment. 

>what do you prefer? 1 minute to place an order because your server is sending an email or delay an email for 5 minutes?

What about the next guy who visits your site and has to wait that 1 minute to send the email of the previous visitor? That seems the worst of all worlds. At least the first person knew the delay was due to their 'order being processed'. The next visitor has no clue.

@claudiosanches - Depending on the site design there is no issue whatsoever running wp-cron every 24 hours or even completely disabling it. For a site that doesn't have sale prices or rely on a payment gateway that uses wp-cron, it is a non-issue, especially if your payment gateway runs recurring payments on a nightly schedule via a system cron. About the only thing really needed is a daily clean up of transients / sessions. Not sure about your webhook comment. Webhooks would have been the best method to handle email generation and solves the issue with immediate triggering of an event. For potentially time consuming operations, I frequently use a webhook (or POST back to my own server) to execute code in a thread outside the user.

**Comment by claudiosanches** [comment]
> What about the next guy who visits your site and has to wait that 1 minute to send the email of the previous visitor?
Not really what happens, don't generate a delay like that for the next visitor.

> Not sure about your webhook comment.

WooCommerce webhooks that works with CRON too.

Other things that uses cron:

- Attributes permalinks after create or change an attribute.
- Product syncing (for groups and variations).
- Upgrade routine
- Hold stock in minutes routine to check and cancel orders.

Cron only once a day for sure will break upgrade routine when you update to 3.0.

> if your payment gateway runs recurring payments on a nightly schedule via a system cron

If you are talking about WooCommerce Subscriptions, it depends on CRON too and for sure 24 it's not correct.

**Comment by krbvroc1** [comment]
> Not really what happens, don't generate a delay like that for the next visitor.

All those pending events gets spawned and use server resources and create a burst of high server load during that visit, potentially slowing down the current visitor.

> If you are talking about WooCommerce Subscriptions, it depends on CRON too and for sure 24 it's not correct.

Not in my case, I override the WCS scheduler with a custom scheduler. My custom payment gateway stores events in a separate database table that I process nightly at 1am. (Other than the obvious upgrade routine, I don't use any of those other features you mention like variations, hold stock, product syncing, etc)

Arguments aside about whether or not my site design has been working for the past 4 years or not. WC 3.0 still creates a newer requirement that was not there in 2.x related to both wp-cron need and more importantly frequency. It could have been done differently in a backwards compatible way via a POST without introducing delays.

**Comment by claudiosanches** [comment]
@krbvroc1 good point "WC 3.0 still creates a newer requirement that was not there in 2.x", that's why is a major release.
Now we are only a few days from the release date and it's too late to make this kind of change too.

>  It could have been done differently in a backwards compatible way via a POST without introducing delays.

Fell free to submit a Pull Request, so we can introduce it to 3.1 or 4.0.
Thanks.

**Comment by mikejolley** [comment]
> All those pending events gets spawned and use server resources and create a burst of high server load during that visit, potentially slowing down the current visitor.

Doesn't this happen at the end of the request? I.e. after the page has loaded, so there is no visible slow down.

The email sending on checkout was noticeably slow - deferring this helps. If you don't have WP Cron, set the interval to 5 mins or something - thats still reasonable, the customer has a visual confirmation on checkout anyway.

**Comment by krbvroc1** [comment]
So is #14035 added yesterday to address concerns of people like me? I guess I wasn't the only one complaining ;)
