### ISSUE TITLE
[2.7] Notice when adding a Downloadable file in a variation

### ISSUE THREAD

**Issue by Chrystll** [woocommerce/woocommerce#13322]
WordPress : 4.7.2
Plugins activated : Only WooCommerce 2.7 beta3 (master)
Theme : StoreFront 2.1.8

To reproduce, edit a variable product > Variations tab > edit a variation > check ‘Downloadable’ > add a file by the ‘Choose file’ button  > hit the 'Save changes' button: I get the notice below.

PHP Notice:  Undefined offset: 0 in /home/christelle/Documents/git/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php on line 156
PHP Stack trace:
PHP   1. {main}() /home/christelle/Documents/sites/wp-trunk/wp-admin/admin-ajax.php:0
PHP   2. do_action() /home/christelle/Documents/sites/wp-trunk/wp-admin/admin-ajax.php:91
PHP   3. WP_Hook->do_action() /home/christelle/Documents/sites/wp-trunk/wp-includes/plugin.php:453
PHP   4. WP_Hook->apply_filters() /home/christelle/Documents/sites/wp-trunk/wp-includes/class-wp-hook.php:323
PHP   5. WC_AJAX::save_variations() /home/christelle/Documents/sites/wp-trunk/wp-includes/class-wp-hook.php:298
PHP   6. WC_Meta_Box_Product_Data::save_variations() /home/christelle/Documents/git/woocommerce/includes/class-wc-ajax.php:1581
PHP   7. WC_Meta_Box_Product_Data::prepare_downloads() /home/christelle/Documents/git/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php:356

**Comment by claudiulodro** [comment]
Need to do a check in `WC_Meta_Box_Product_Data::prepare_downloads` to make sure `$file_hashes[ $i ]` is present before assigning it as a `previous_hash`.
