### ISSUE TITLE
[2.7] WC_Order_Item_Tax object has lost at least one value when accessed as an array

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#13321]
## EXPLANATION OF THE ISSUE

Related: https://github.com/woocommerce/woocommerce/issues/13287 (note that I am now testing on a version with the change mentioned there merged - the problem still exists).

After calling WC_Order::get_taxes() , and then looping over the resulting array, the individual items (which are now WC_Order_Item_Tax, instead of arrays), do not have a `tax_amount` value when accessed as an array. This is a change in behaviour from WC 2.6, and a silent/undocumented failure.

i.e. This (simplified) fragment will silently fail, with `$tax['tax_amount']` being null each time:

```
$total = 0;
$taxes = $order->get_taxes();
foreach ($taxes as $tax) {
  $total += $tax['tax_amount'];
}
```

Verified with the current Github master - a5752f9 . Also the same result on beta3 plus the pull requested mentioned in the above thread.

**Comment by claudiulodro** [comment]
There were a couple that needed to be mapped. See #13327.
