### ISSUE TITLE
Revert negative fee removal

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13325]
Remove the notice and make them save correctly in backend. This should be prevented with notices when the discount API is in place.

**Comment by claudiosanches** [comment]
See #13325

**Comment by WPprodigy** [comment]
:trollface: ;p

**Comment by mikejolley** [comment]
Nice @claudiosanches  :D

**Comment by mikejolley** [comment]
@claudiosanches Do you think #13328 is still too much? We're throwing notices but given the comments in the PR which removed support, it seems people need a robust replacement first.

I think we should:

- note in the code via a comment that it's not advisable
- Fix it so they save correctly again in admin
- Show no notices

But then when discount API is included, then we add the doing_it_wrong stuff.

Thoughts? @justinshreve

**Comment by claudiosanches** [comment]
Fixed in #13344 and #13345
