### ISSUE TITLE
Shipping Zones Zip Code Locator/Checker Form - Feature Request

### ISSUE THREAD

**Issue by monecchi** [woocommerce/woocommerce#13323]
## Why would users benefit of a Shipping Zones Locator/Checker Form?

Because after creating hundreds of Shipping Zones entries, it simply makes sense not to waste these only in the cart or checkout pages, where they act transparently. I wish I could let my customers check their zip codes against all the site's available Shipping Zones.

If WooCommerce had a function to output a Shipping Zones Locator Form, I'd expect as a response a confirmation message stating that the user's zip code (zone/location) is valid and that it is within the store's shipping reach. Also I'd expect something as the zone name, the country/state, the method title and the cost returned. All the returned data could be optional or modified through a filter.

WooCommerce's usage scope is broad and I'm sure users would benefit a lot from a Shipping Zones Locator/Checker. I'm sure there are a few plugins out there which offer similar functionality, but those require the data (zip codes) to be manually saved in their settings, which again is a waste of time, having to duplicate almost the same data that was already saved in the Shipping Zones settings.

I'd really appreciate any concerns regarding this functionality.

**Comment by mikejolley** [comment]
Shipping zones match against an address and can cover a wide area of places. Having these selectable does not help us capture for example a full shipping address so I'm not sure the use case fits.

By all means post this on ideas.woocommerce.com but I don't think we should pursue this without more feedback. 

> I wish I could let my customers check their zip codes against all the site's available Shipping Zones.

It would be possible to query and list zones if needed, we just don't offer that in core out of the box.

**Comment by monecchi** [comment]
Yeah I got it. But let's say the customer would like to know before hand (not in the cart or checkout pages) if the store delivers or offers any kind of shipping to his address, so he would simple check for his zip code and get a response with the available shipping methods and the cost.

 I can't see a more helpful stuff than this. One would have to wait until he fills up the checkout form in order to get some info about the shipping. That's not fair.

**Comment by mikejolley** [comment]
What's wrong with the calculator on the cart page?

**Comment by monecchi** [comment]
Well, it is the cart page to start with.

I believe customers should be able to check for the shipping availability before they start adding items in the cart just to find out their zip code (location) is not serviced by the store.

I can think about thousands of WooCommerce powered shops that are focused on some sort of local delivery and that would like to have their customers to be able to check for the shipping availability in their shops front page.

**Comment by mikejolley** [comment]
There are non-code ways to tell users where you offer shipping, it does not need to be a form does it?

**Comment by monecchi** [comment]
But when you have spent a satisfactory amount of time feeding up the Shipping Zones with lots of data and they're already set up, it makes sense to have an easy way to output that data and make the most of it.

I'm not an expert developer, if I was I had already coded it myself. The way Shipping Zones exists in WooCommerce makes it almost unpractical to be accessed. One would have to create a complex custom function in order to get anything from its extensive array data structure.

If there were such functions or filters in the core to facilitate the access to the Shipping Zones data, ordinary non programming people could be using it in a lot of helpful ways.

**Comment by monecchi** [comment]
I really appreciate your opinion on that matter, I'll no longer advocate on it as it seems something that will not be considered in any ways. Although Woocommerce is great, it still lacks cool stuff that an online shop should have, such as the shipping zones checker, but for now that is limited to my opinion I think.

I've been trying to create it myself, not sure I'll be able successfully make it though. As I've said, it turns out to be incredibly hard to access the shipping zones data to create such a functionality, at least for me.

![captura de tela 2017-02-24 as 12 39 30](https://cloud.githubusercontent.com/assets/5252519/23309842/041b4038-fa8f-11e6-87ad-5bd652000549.png)

**Comment by mikejolley** [comment]
@monecchi Can you maybe show an example of this on an existing store i.e. how you think it should look?

**Comment by monecchi** [comment]
@mikejolley Fine. The following are plugins that display the zip code locator/checker on the product page, but both have shortcodes and functions so the user can display the zip code checker anywhere.

**Do you deliver plugin** - Use the zip code 10023 for checking the shipping availability 
https://codecanyon.net/item/woocommerce-do-you-deliver/9513943

**WOOCOMMERCE CHECK PINCODE/ZIPCODE FOR SHIPPING plugin**
https://www.phoeniixx.com/product/woocommerce-check-pincodezipcode-for-shipping-and-cod/

Both plugins require the user to add zip codes on their own settings, they don't make use of WooCommerce's **Shipping Zones data**, and that's where the problem relies I think.

I would like to be able to get a lot out of what WooCommerce already has, which is the Shipping Zones data. If I had thousands of shipping zones entries which I manually have set, what's the point of using another plugin after all?

And that's where a zip code checker form would come in handy, to make use of the data Already set in WooCommerce.

I hope that helps. Anyway, thanks for keeping up with the discussion. Have a nice weekend!

**Comment by mikejolley** [comment]
@monecchi What about on live stores? Not necessarily WC stores?

Did you add this to the ideas board?

**Comment by monecchi** [comment]
@mikejolley Yes, I've just added it. - Here's the link: http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/19342603-frontend-shipping-zones-form-locator-checker
