### ISSUE TITLE
[2.7] Applying coupon on cart results in infinite spinner

### ISSUE THREAD

**Issue by dare-devil-arrives** [woocommerce/woocommerce#13334]
## EXPLANATION OF THE ISSUE

WooCommerce beta 3. When you try applying a core coupon on cart page, the spinner infinitely spins and console throws an error 'Uncaught ReferenceError: coupon is not defined'.

![Coupon Error](https://cl.ly/jIbn/WC-beta-3-error.png)

## STEPS TO REPRODUCE THE ISSUE

1. Create a coupon
2. Try applying it on Cart page
3. You'll see infinite spinner on page with error in the console.

**Comment by mikejolley** [comment]
Fixed in master.
