### ISSUE TITLE
[2.7] Improve Schema.org Markup

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#13331]
## EXPLANATION OF THE ISSUE

In WooCommerce 2.7, product markup switched to using the `Review` object type for all review items rather than setting these as nested properties of the `Product` object instead.

From the [review snippet guidelines](https://developers.google.com/search/docs/data-types/reviews#review-snippet-guidelines):

> **Refer clearly to a specific product or service**. Do this by **nesting the review or ratings** within the markup of another schema.org type—such as schema.org/Book or schema.org/LocalBusiness —or by using that schema.org typed element as a value for the `itemReviewed` property.

However, if nested, then the `itemReviewed` property is no longer needed: https://developers.google.com/search/docs/data-types/reviews#review_type_definition

Now while the current implementation looks to use `itemReviewed` rather than nesting, Google [seems to indicate that nesting is the more appropriate method](https://developers.google.com/search/docs/data-types/products#type_definitions):

> Review, recommended
>
> A nested Review of the product.

EDIT: Also see the "embedded review" sample JSON [in the second tab here](https://developers.google.com/search/docs/data-types/reviews#review-snippet-examples).

As such, the review should probably be nested as a property of the Product object, not as a standalone object on the page, which would also be consistent with previous behavior:

 - WC 2.6 validation: http://cloud.skyver.ge/3O343S0I2k3i -- Notice "Product", which as reviews nested within that object.
 - WC 2.7 validation: http://cloud.skyver.ge/3g2R1C0a280z -- Notice "Reviews" are now added as standalone objects when the review objects should be set as item properties. 

The [Product schema.org docs](https://schema.org/Product) also seem to suggest nesting should be done.

### Associated Issue:

There are also errors in 2.7 from `ratingValue` being empty due to some of these being regular comments from the admin in response to customer reviews. These should not attempt to add the `reviewRating` markup on the comment if there is no rating available.

**Comment by unfulvio** [comment]
I also noticed that replies to reviews are marked as reviews - I believe they should be nested in the original review and be of a different schema type

**Comment by mikejolley** [comment]
We can fix up ratingValue, and I think we can hide non-review replies to reviews.

As for nesting, this would be a large large. The way in which the data is generated it's done per-item as the review or product gets output to the page. This is efficient. To nest as part of the product, we'd have to get the comments + reviews separately.

Given that the docs state:

> —or by using that schema.org typed element as a value for the itemReviewed property.

I don't think this is a requirement. Yes it states `Review, recommended`, but `itemReviewed` is also labelled as a required field so we can take this with a pinch of salt unless explicitly documented.
