### ISSUE TITLE
Double stock removal on edit order with payment method change?

### ISSUE THREAD

**Issue by drosendo** [woocommerce/woocommerce#13349]
Hi,

So I am having a issue where the same order gets stock removed 2 or more times.

Scenario example:

1. Client checkout out simple product and chooses Bank Transfer and finnish.
2. Order goes "on-hold" and stock is removed
3. Client requests new payment method or If by chance I proceed again with bank transfer 
4. I go to edit the order and have the  option "go to client payment page" above the "order status" select
5. I go to "client payment page" select new method or same and proceed.
6. New payment details are created, and again **stock gets removed for the same order**...

Somehting wrong here, aint there a condition in "reduce_order_stock()" that when called before reducing the stock checks if:

1.  Stock for item has already been removed for that order being edited
2. if stock same has before edit than dont do nothing
3. if stock diferent then **add back previous removed stock** and then **remove stock for with the new value**

I didnt find the condition in the programing for this... maybe i missed.

Thanks for the feedback.

![image](https://cloud.githubusercontent.com/assets/884585/23325145/ee142c1c-faea-11e6-834e-6434534357e4.png)

`
### WordPress Environment ###

WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: pt_PT

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Post Remoto: ✔
Get Remoto: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (34) ###

iThemes Security: por iThemes – 6.1.1
Breadcrumb NavXT: por John Havlik – 5.6.0
Contact Form 7: por Takayuki Miyoshi – 4.6.1
createIT Waitlist Plugin: por createIT – 1.7
WPBakery Visual Composer: por Michael M - WPBakery.com – 5.0.1
MagniFinance Invoice System: por WebDS – 1.0
MEO Wallet Gateway de pagamento: por WebDS – 2.0.1
Products Purchase Price for Woocommerce: por Softedge – 1.0.4
Slider Revolution: por ThemePunch – 5.2.6
WooCommerce Advanced Shipping: por Jeroen Sormani – 1.0.12
WooCommerce - Country Based Payments: por Ivan Paulin – 1.1.6.1
WooCommerce - Store Exporter: por Visser Labs – 1.8.8
WooCommerce POS: por kilbot – 0.4.6
WooCommerce: por WooThemes – 2.6.14
Importador do WordPress: por wordpressdotorg – 0.6.3
Yoast SEO: por Team Yoast – 4.3
WP-Mail-SMTP: por Callum Macdonald – 0.10.1
MailPoet Newsletters: por MailPoet – 2.7.7
YITH WooCommerce Ajax Search: por YITHEMES – 1.4.1
YITH WooCommerce Wishlist: por YITHEMES – 2.0.16
Zendesk Chat Widget: por Zopim – 1.4.6

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Loja base: #1818 - /shop/
Carrinho: #2070 - /cart/
Finalizar compras: #2828 - /checkout/
Minha conta: #2829 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Oxy Child
Version: 1.0
Author URL: http://www.smartdatasoft.com
Child Theme: ✔
Parent Theme Name: OXY
Parent Theme Version: 2.9
Parent Theme Author URL: http://www.smartdatasoft.com/
WooCommerce Support: ✔

**Comment by WPprodigy** [comment]
I can reproduce. Not sure if it's the exact same steps as mentioned above, but here is what I did:

1) Create order w/ BACS that it set to on-hold and stock is reduced.
2) Edit order and set to pending payment.
3) Go to the customer payment page and checkout again, with Cheque or even BACs again: http://cld.wthms.co/FmYe/4SyfLCKz
4) Look how the stock reduced twice: http://cld.wthms.co/7Kae/1LncxdRm

What should/could happen:

- Stock could maybe be put back when the order status goes back to pending payment? Then reduced again depending on how the customer pays.
- Stock is left alone, but not reduced again.

**Comment by drosendo** [comment]
Hi,

What you did is correct...

My approach would maybe not be on that function. I don't think there is a need for new metas.

Remove stock should always happen independently of how the order goes (expect canceled). This way the stock keeps reserved for the client for some period (should be defined).

What I would do is a very simple:

- if generating new payment method on same order, don't run wc_reduce_stock_levels() (condition).

There would be a condition where wc_reduce_stock_levels() would run on generating new payment method on same order:

1. Admin changed order items (stock increase/decrease, remove), and save order. This would create a meta (XPTO) with object of previous items stored.
2. admin generates new payment, wc_reduce_stock_levels() will run if previous meta (XPTO) has object.

I hope im explain myself...

**Comment by mikejolley** [comment]
We'll look at this as part of https://github.com/woocommerce/woocommerce/issues/13359

**Comment by claudiosanches** [comment]
> Order goes "on-hold" and stock is removed

By default stock is reduced only when order goes to "processing", so looks like you are forcing to reduce stock every time an order is made, but forgetting to let WooCommerce know about it, that why are reducing twice.

For it you need to do:

```php
update_post_meta( $order_id, '_order_stock_reduced', 'yes' );
```

This will solve the problem of your custom implementation.

**Comment by drosendo** [comment]
Hi @claudiosanches ,

There is no custom implementation...

You can see that BACS (WooCommerce native) removes stock "on-hold" not on "processing"

```

	/**
	 * Process the payment and return the result.
	 *
	 * @param int $order_id
	 * @return array
	 */
	public function process_payment( $order_id ) {

		$order = wc_get_order( $order_id );

		// Mark as on-hold (we're awaiting the payment)
		$order->update_status( 'on-hold', __( 'Awaiting BACS payment', 'woocommerce' ) );

		// Reduce stock levels
		$order->reduce_order_stock();

		// Remove cart
		WC()->cart->empty_cart();

		// Return thankyou redirect
		return array(
			'result'    => 'success',
			'redirect'  => $this->get_return_url( $order )
		);

	}
```

WooCommerce need to handle this better.

**Comment by mikejolley** [comment]
> We'll look at this as part of #13359

**Comment by GennCamp** [comment]
hi anyone could give me the function to copy and paste in functuon.php? to eliminate this bug? Ihave the same problem.
