### ISSUE TITLE
WP-CLI product variant attributes are seperated into multiple attributes if a comma is used in the name

### ISSUE THREAD

**Issue by rcojoe** [woocommerce/woocommerce#13342]
WC:2.6.14
WP:4.7.2

I have pants that I have sized like this:
28, Long
28, Reg
28, Short

In woocommerce admin,  they represent 3 attributes, but when I pull the attribute field using WP-CLI,  using 
a command line like this `wp wc product get 46432 --field=attributes --format=json`
(all format methods return similar results so its further up the chain)
I get a json repsonse like this:
"options":["28","Long","28","Reg","28","Short"]
The correct output should be:
"options":["28, Long","28, Reg","28, Short"]

I'm using PHP 7, running Ubuntu 16
Below is a screenshot showing the attributes in woocommerce and the output from wp-cli

![edit product rock creek outfitters wordpress](https://cloud.githubusercontent.com/assets/11729742/23311261/79c2616a-fa83-11e6-9346-f7fef2b455c3.png)

`
$ wp wc product get 46432 --field=attributes
[{"name":"Color","slug":"color","position":3,"visible":true,"variation":true,"options":["Black","Carbon","Gun Metal"]},{"name":"Size","slug":"size","position":4,"visible":true,"variation":true,"options":["28","Short","28","Reg","30","Short","30","Reg","30","Long","31","Short","31","Reg","31","Long","32","Short","32","Reg","32","Long","33","Short","33","Reg","33","Long","34","Short","34","Reg","34","Long","35","Short","35","Reg","35","Long","36","Short","36","Reg","36","Long","38","Short","38","Reg","38","Long","40","Short","40","Reg","40","Long"]}]
`

**Comment by mikejolley** [comment]
This will be fixed in the new CLI with 2.7. I've confirmed it's working.

The old CLI you're using now will not be maintained.

https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Overview
https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Commands
