### ISSUE TITLE
Woo Commerce with SagePay Form Gateway for WooCommerce

### ISSUE THREAD

**Issue by mgilberties** [woocommerce/woocommerce#13348]
## EXPLANATION OF THE ISSUE
I am experiencing an issue when using WordPress 4.7.2 with WooCommerce Plugin for accepting payment through SagePay Form Gateway. - Version 1.4.1 By PatSaTECH and WooCommerce Version 2.6.14. I am struggling to identify if the issue is WooCommerce or the SagePay Form Gateway plugin. The page returns -1 instead if redirecting to the order confirmation page.

## STEPS TO REPRODUCE THE ISSUE
1. Add product to cart
2. Checkout
3. Complete details and be forwarded to the SagePay page
4. Complete payment and be redirected to the website.
5 Stuck on the api page: http://www.liquorandallsorts.com/wc-api/woocommerce_sagepayform?crypt=@[massive-guids-here-removed-for-brevity]
Blank white page with -1 at the top left

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://www.liquorandallsorts.com
Site URL: http://www.liquorandallsorts.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.3.29 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 512 MB
PHP Time Limit: 90
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.0

SUHOSIN Installed: ✔
MySQL Version: 5.6.35
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. PayPal IPN won't work with your server. Contact your hosting provider. Error: cURL error 35: Unsupported SSL protocol version
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (16) ###

WooCommerce Bookings: by WooThemes – 1.4.9
Automatic Page Publish / Expire: by Harpinder Singh – 1.0
Checkfront Online Booking System: by Checkfront Inc. – 3.2
Contact Form 7: by Takayuki Miyoshi – 4.6.1
Duplicate Page: by mndpsingh287 – 2.2
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.11.2.1
SagePay Form Gateway for WooCommerce: by PatSaTECH – 1.4.1
TweetScroll Widget: by Pixel Industry – 1.3.7
URL Redirect: by Ninja Press – 1.3
WooCommerce Email Customizer: by cxThemes – 2.37
WooCommerce WooCart Popup Lite: by Festi – 1.1
WooCommerce: by WooThemes – 2.6.14
Yoast SEO: by Team Yoast – 4.3
WP Crontrol: by John Blackbourn & Edward Dale – 1.4
WP Server Stats: by Saumya Majumder – 1.5.2
WP Smush: by WPMU DEV – 2.5.3

### Settings ###

Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #553 - /shop/
Basket: #87 - /cart/
Checkout: #88 - /checkout/
My Account: #89 - /my-account/

### Taxonomies ###

Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Bridge
Version: 6.0
Author URL: http://www.qodethemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: bridge/woocommerce/cart/cart-empty.php
bridge/woocommerce/cart/cart.php version 2.1.0 is out of date. The core version is 2.3.8
bridge/woocommerce/cart/shipping-calculator.php
bridge/woocommerce/checkout/form-coupon.php
bridge/woocommerce/checkout/form-login.php
bridge/woocommerce/checkout/thankyou.php
bridge/woocommerce/content-product.php version 1.6.4 is out of date. The core version is 2.6.1
bridge/woocommerce/content-single-product.php
bridge/woocommerce/global/form-login.php
bridge/woocommerce/global/quantity-input.php version 2.1.0 is out of date. The core version is 2.5.0
bridge/woocommerce/loop/add-to-cart.php version 2.1.0 is out of date. The core version is 2.5.0
bridge/woocommerce/loop/loop-start.php
bridge/woocommerce/loop/pagination.php
bridge/woocommerce/loop/rating.php
bridge/woocommerce/loop/result-count.php
bridge/woocommerce/loop/sale-flash.php
bridge/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 2.6.0
bridge/woocommerce/myaccount/form-lost-password.php version 2.0.0 is out of date. The core version is 2.6.0
bridge/woocommerce/myaccount/my-address.php version 2.2.0 is out of date. The core version is 2.6.0
bridge/woocommerce/myaccount/my-orders.php
bridge/woocommerce/single-product/add-to-cart/external.php
bridge/woocommerce/single-product/add-to-cart/grouped.php
bridge/woocommerce/single-product/add-to-cart/simple.php
bridge/woocommerce/single-product/add-to-cart/variable.php version 2.1.0 is out of date. The core version is 2.5.0
bridge/woocommerce/single-product/related.php
bridge/woocommerce/single-product/sale-flash.php
bridge/woocommerce/single-product/tabs/additional-information.php
bridge/woocommerce/single-product/tabs/description.php
bridge/woocommerce/single-product/tabs/tabs.php version 2.0.0 is out of date. The core version is 2.4.0
bridge/woocommerce/single-product/up-sells.php

: Learn how to update outdated templates
`

**Comment by WPprodigy** [comment]
Hi @mgilberties,

The issue is very likely coming from the Payment Gateway and isn't a problem with WooCommerce core. You should start by contacting the plugin authors for your SagePay plugin.

**Comment by mgilberties** [comment]
Hi @WPprodigy,

Thanks for your response. I will contact the plugin developer and close this issue.
