### ISSUE TITLE
 changes to variable products shown before pressing update

### ISSUE THREAD

**Issue by ekuk** [woocommerce/woocommerce#13351]
don't know if this is a bug but my client certainly does and I don't
recall it doing this before.

If you have woocommerce installed and have a
published variable product, then you go to edit that product and make
changes to the attributes or variations and press save attribute or save
on the variations, these changes are shown instantly on the front end
rather than as you would expect when you press update on the product
itself. 

Tried it on two different sites, they both do the same.

wordpress 4.7.2, woocommerce 2.6.14

`
### WordPress Environment ###

Home URL: http://www.lawtontools.co.uk/en
Site URL: http://www.lawtontools.co.uk/en
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.23 (Unix) OpenSSL/1.0.2h
PHP Version: 7.0.7
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 1720
cURL Version: 7.29.0
NSS/3.19.1 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.29
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (25) ###

Add Meta Tags: by George Notaras – 2.11.3
Ajax Search Pro: by Ernest Marcinko – 4.9.8
Attachments UI: by Jonathan Christopher – 1.0.3
Attachments: by Jonathan Christopher – 3.5.7
Cookie Law Info: by Richard Ashby – 1.5.3
Force Strong Passwords: by Jason Cosper – 1.7
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Image Widget: by Modern Tribe
Inc. – 4.3

WPBakery Visual Composer: by Michael M - WPBakery.com – 5.0.1
Loginizer: by Raj Kothari – 1.3.2
MCE Table Buttons: by Jake Goldman
10up
Oomph – 3.2

Max Mega Menu: by Tom Hemsley – 2.3.4
Slider Revolution: by ThemePunch – 5.3.1.5
RiverTheme Core: by RIT – 2.0.3
Vafpress Post Formats UI: by vafpress – 1.5
Woocommerce Variations Table - Grid: by Spyros Vlachopoulos – 1.2.0
WooCommerce Dynamic Gallery LITE: by a3rev Software – 2.3.3
WooCommerce Extra Product Sorting Options: by SkyVerge – 2.5.0
WooCommerce: by WooThemes – 2.6.14
Wordfence Security: by Wordfence – 6.3.2
WP Fastest Cache: by Emre Vona – 0.8.6.1
WP Lightbox 2: by Syed Balkhi – 3.0.6.2
Custom Product Tabs for WooCommerce: by YIKES
Inc – 1.5.5

YITH WooCommerce Catalog Mode: by YITHEMES – 1.4.0
YITH WooCommerce Quick View: by YITHEMES – 1.1.4

### Settings ###

Force SSL: –
Currency: ()
Currency Position: 
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #8 - /products/
Basket: #9 - /cart/
Checkout: #10 - /checkout/
My Account: #11 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: RI Colias Child Theme
Version: 1.1.0
Author URL: https://rivertheme.com
Child Theme: ✔
Parent Theme Name: Ri Colias
Parent Theme Version: 1.2.4
Parent Theme Author URL: http://www.zootemplate.com/
WooCommerce Support: ✔

### Templates ###

Overrides: ri-colias/woocommerce/archive-product.php
ri-colias/woocommerce/cart/cart-totals.php
ri-colias/woocommerce/cart/cart.php
ri-colias/woocommerce/cart/cross-sells.php
ri-colias/woocommerce/cart/mini-cart.php
ri-colias/woocommerce/cart/proceed-to-checkout-button.php
ri-colias/woocommerce/cart/shipping-calculator.php
ri-colias/woocommerce/checkout/form-billing.php
ri-colias/woocommerce/checkout/form-checkout.php
ri-colias/woocommerce/checkout/form-coupon.php
ri-colias/woocommerce/checkout/form-pay.php
ri-colias/woocommerce/checkout/payment.php
ri-colias/woocommerce/checkout/review-order.php
ri-colias/woocommerce/checkout/thankyou.php
ri-colias/woocommerce/content-product.php version 2.5.0 is out of date. The core version is 2.6.1
ri-colias/woocommerce/content-product_cat.php version 2.5.2 is out of date. The core version is 2.6.1
ri-colias-child/woocommerce/content-single-product.php
ri-colias/woocommerce/content-widget-product.php
ri-colias-child/woocommerce/global/breadcrumb.php
ri-colias/woocommerce/global/form-login.php
ri-colias/woocommerce/global/quantity-input.php
ri-colias/woocommerce/loop/loop-end.php
ri-colias/woocommerce/loop/loop-start.php
ri-colias/woocommerce/loop/orderby.php
ri-colias/woocommerce/loop/pagination.php
ri-colias/woocommerce/loop/rating.php
ri-colias/woocommerce/loop/sale-flash.php
ri-colias/woocommerce/myaccount/dashboard.php
ri-colias/woocommerce/myaccount/form-add-payment-method.php
ri-colias/woocommerce/myaccount/form-edit-account.php
ri-colias/woocommerce/myaccount/form-edit-address.php
ri-colias/woocommerce/myaccount/form-login.php
ri-colias/woocommerce/myaccount/form-lost-password.php
ri-colias/woocommerce/myaccount/my-account.php
ri-colias/woocommerce/myaccount/my-address.php
ri-colias/woocommerce/myaccount/my-orders.php
ri-colias/woocommerce/myaccount/view-order.php
ri-colias/woocommerce/notices/error.php
ri-colias/woocommerce/notices/notice.php
ri-colias/woocommerce/notices/success.php
ri-colias/woocommerce/order/order-details-customer.php
ri-colias/woocommerce/order/order-details.php
ri-colias/woocommerce/product-searchform.php
ri-colias/woocommerce/single-product/add-to-cart/external.php
ri-colias/woocommerce/single-product/add-to-cart/grouped.php
ri-colias/woocommerce/single-product/add-to-cart/simple.php
ri-colias/woocommerce/single-product/product-attributes.php
ri-colias/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 2.6.3
ri-colias/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 2.6.3
ri-colias/woocommerce/single-product/rating.php
ri-colias/woocommerce/single-product/related.php
ri-colias/woocommerce/single-product/share.php
ri-colias/woocommerce/single-product/short-description.php
ri-colias/woocommerce/single-product/tabs/tabs.php
ri-colias/woocommerce/single-product/title.php
ri-colias-child/woocommerce/single-product/up-sells.php
ri-colias/woocommerce/single-product-reviews.php
ri-colias-child/woocommerce/single-product.php

: Learn how to update outdated templates
`

**Comment by WPprodigy** [comment]
Hi @ekuk,

This isn't a bug. Those save button are meant to save the product with ajax. Attributes need to be saved before variations can be created.  And there is no way to store temporary data.

This could possibly be addressed in https://github.com/woocommerce/woocommerce/issues/13086 though.

**Comment by lawkwok** [comment]
Yes, I've never understood why there is a separate Save Changes button on the variations page.

It's a minor idiosyncrasy for those familiar with WooCommerce, but it's another point of friction for clients :(

**Comment by mikejolley** [comment]
See #13086
