### ISSUE TITLE
get_is_paying_customer returns true after order is deleted

### ISSUE THREAD

**Issue by devinsays** [woocommerce/woocommerce#13353]
## EXPLANATION OF THE ISSUE

get_is_paying_customer returns true even after orders with payments are deleted.

## STEPS TO REPRODUCE THE ISSUE

* Add a product to the cart
* Checkout as a new customer and create a new customer account
* As an admin approve the order

Viewing with the new customer account, this should now return true.

```
$current_user = wp_get_current_user();
$customer = new WC_Customer( $current_user->ID );
echo $customer->get_is_paying_customer(); // outputs true
```

If the order is then deleted by the admin, this customer should not longer be a paying customer, but $customer->get_is_paying_customer() still returns true.

I've run through this a few times, but if someone else could verify that would be great.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://woocommerce.dev
Site URL: http://woocommerce.dev
WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.10
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/0.9.8zd

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.42 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 35: Unsupported SSL protocol version
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. 200

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Coupon Restrictions: by DevPress – 1.1.0
WooCommerce: by Automattic – 2.7.0-beta-4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront
Version: 2.1.7 – 2.1.8 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by WPprodigy** [comment]
Haven't tried replicating, but a quick look makes me think this is indeed a bug. 

The `paying_customer` user meta is updated to `true / 1`, but is never set back to `false / 0`. So if all of the customer's orders are permanently deleted, they would still remain "paying".

Trigger something like `wc_update_new_customer_past_orders()` after an order is deleting could help, though there will need to be an else statement that sets it meta to false if no orders are found.

**Comment by mikejolley** [comment]
Recalculating this on events would add a lot of overhead. This meta is set once and left after they have 'paid' something. It could possibly be linked to order counts, but I don't think this is a high priority issue.
