### ISSUE TITLE
[2.7] Refund Handling Forces Order Status change

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#13357]
## EXPLANATION OF THE ISSUE

In WC 2.6 and lower, `wc_create_refund()` created refund data, but didn't manipulate anything outside of the refund. The order object is left untouched.

WC 2.7+ now also manipulates the order object as well. If an order is fully refunded, it's forced to "refunded" order status without a way to block this transition.

This is problematic for situations in which the order status should be something other than refunded -- in my case, "cancelled", due to a fully voided order rather than a refunded one. As there's no other way to void a transaction outside the refund method, this is what we've used to process a void / order cancellation automatically via the gateway.

## STEPS TO REPRODUCE THE ISSUE

In my case, I'm using CSV Import to import an order and the status I'm trying to set is consistently ignored (even when filtering the fully refunded status, the order just gets set to pending instead of cancelled). 

Is there a way to separate this or have an action to fire a status change? That way programmatic changes of the order such as external uses of the refund mechanism can then remove the action to set the intended data on the order.

**Comment by mikejolley** [comment]
This actually sounds like a flaw in 2.6. Refunded status is correct for a fully refunded order. Why not target the order updated actions or status transition action?

**Comment by mikejolley** [comment]
Ok, so we really should keep this around as it keeps orders and refunds in sync. Having fully refunded orders that are not refunded status can upset the reporting. 

^ I've adjusted the filter `woocommerce_order_fully_refunded_status` so that it will only do a status change if the status is set. It defaults to `refunded` but could be replaced with a `__return_false` callback. This will stop the transition occurring. 

I still don't fully understand why you'd use refunds for voids since they are different events, or why these would be registered as refunds, but that should at least make it possible without listening for events.

**Comment by bekarice** [comment]
> ^ I've adjusted the filter woocommerce_order_fully_refunded_status so that it will only do a status change if the status is set. It defaults to refunded but could be replaced with a __return_false callback. This will stop the transition occurring.

Thanks for the follow up! Will check this out.

> I still don't fully understand why you'd use refunds for voids since they are different events, or why these would be registered as refunds, but that should at least make it possible without listening for events.

The reason we do this is because the merchant shouldn't necessarily need to know the difference, or take different paths to processing them. To know void vs refund, they have to know whether payment was captured or not and which gateway was used. When, in reality, it should be as simple as them returning the line items in the order to stop an order or give back money if necessary.

As a result, the gateway can handle this transparently without them needing to know what status the payment itself is in, just by following the same procedure. Something that separating fulfillment and payment status in the future helps out with as well 😸 

In this case, we moreso ran into this on creating or updating the order via import, as to import refund / void data, `wc_create_refund()` is the most appropriate method for us to use, but we couldn't get around that status change vs what was in the import file.
