### ISSUE TITLE
Update customer not working Woocommerce API

### ISSUE THREAD

**Issue by aditya1027** [woocommerce/woocommerce#13358]
```
var data = {
        customer: {
          first_name: 'James',
          billing: {
            first_name: 'James'
          },
          shipping: {
            first_name: 'James'
          }
        }
      };
WooCommerce.put('customers/21', data, function(err, data, res) {
        console.log(res);
      });
```
Returning result but not updating customer details.

**Comment by HenkeJohansson** [comment]
I got the same problem but but with this error (and I'm using the php-version):

"exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: illegal parameters: billing, shipping [rest_invalid_param]' in /Users/henke/Git/angular/pelote-intern-orders/php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:324
Stack trace:
#0 /Users/henke/Git/angular/pelote-intern-orders/php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(343): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Array)
#1 /Users/henke/Git/angular/pelote-intern-orders/php/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(379): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#2 /Users/henke/Git/angular/pelote-intern-orders/php/vendor/automattic/woocommerce/src/WooCommerce/Client.php(69): Automattic\WooCommerce\HttpClient\HttpClient->request('customers/4', 'PUT', Array)
#3 /Users/henke/Git/angular/pelote-intern-orders/php/wc_updateBilling.php(69): Automattic\WooCommerce\Client->put('customers/4', Array)
#4 {main}"

And my data object is like this:
`$data = [
    'first_name' => (string)$first_name,
	'last_name' => (string)$last_name,
	'email' => (string)$email,
    'billing' => [
		'first_name' => (string)$billing_first_name,
		'last_name' => (string)$billing_last_name,
		'adress_1' => (string)$billing_adress_1,
		'adress_2' => (string)$billing_adress_2,
		'city' => (string)$billing_city,
		'postcode' => (string)$billing_postcode,
		'phone' => (string)$billing_phone,
		'email' => (string)$billing_email
    ],
    'shipping' => [
        'first_name' => (string)'James'
    ]
];
$woocommerce->put("customers/$customerID", $data);
`

**Comment by mikejolley** [comment]
@aditya1027 you're sending invalid JSON. The `customer:` part is not needed. Validate your JSON first. There is nothing wrong with the core API here.

And Henke, I don't think thats how you should format the request. Use a JSON string with objects rather than arrays. 

Basic working request example:

```
$data = '{ "billing" : { "first_name": "James" } }';
```

**Comment by aditya1027** [comment]
@mikejolley i have also tried with
```
var data = {
          first_name: 'James',
          billing: {
            first_name: 'James'
          },
          shipping: {
            first_name: 'James'
          }
      };
```

but getting error of no customer data.

**Comment by mikejolley** [comment]
Test in a different client.

**Comment by ruedada** [comment]
Didn't result the update, the service responds OK 200, but the data is the same always
