### ISSUE TITLE
Ireland listed under wrong country name

### ISSUE THREAD

**Issue by bdetail** [woocommerce/woocommerce#13352]
Ireland is listed as "Republic of Ireland", which is not the name of the state. It should be just "Ireland".

This causes problems because many Irish shoppers will automatically look for "Ireland" in the list and then complain because they can't find it. It is not normal to have the country listed as "Republic of Ireland" in any online store or registration form because it's not the official name of the country. Shoppers in Northern Ireland will always select United Kingdom so there is no ambiguity. This is the long accepted standard.

I know I can manually change it to Ireland now, but that should be the default name on installation.

https://www.cia.gov/library/publications/the-world-factbook/geos/ei.html

https://en.wikipedia.org/wiki/Names_of_the_Irish_state

**Comment by bdetail** [comment]
For any other Irish developers coming across this problem, seems someone has already created a function to correct the country name to Ireland until there's a permanent fix.

https://docs.woocommerce.com/document/rename-a-country-in-woocommerce/

```
// Rename 'Republic of Ireland' to 'Ireland'
add_filter( 'woocommerce_countries', 'rename_ireland' );
    function rename_ireland( $countries ) {
    $countries['IE'] = 'Ireland';
    return $countries;
}
```
Add that to your functions.php file.

**Comment by UserName011** [comment]
According to the United Nations the official name is indeed Ireland
https://www.un.int/protocol/sites/www.un.int/files/Protocol%20and%20Liaison%20Service/officialnamesofcountries.pdf

Croatia official name is 'Republic of Croatia' but in WooCommerce it's just Croatia. So why not changing 'Republic of Ireland' to  'Ireland' ?

**Comment by Chunkford** [comment]
I'm presuming the country was once called just Ireland as in the [countries.php](woocommerce/i18n/countries.php#L124) file it's in alphabetical order and Republic of Ireland is amongst the the I's.

Also looking at the wiki article you posted it says:

> The terms Republic of Ireland (ROI), the Republic or the South are often used when there is a need to distinguish the state from the island or when Northern Ireland (NI or the North) is being discussed.

Which is probably why it changed.

**Comment by bdetail** [comment]
Here's a few examples from major websites

Amazon.com: http://i.imgur.com/uU0wgwi.png
Google: http://i.imgur.com/UEm7ZOA.png
Apple:  http://i.imgur.com/13G4orr.png
eBay: http://i.imgur.com/hj8ulSP.png

None of them say "Republic of Ireland" because it would lead to complaints and loss of sales. This is exactly what happened to my client's new Woocommerce store - customers were complaining that Ireland wasn't in the list. 

Listing Ireland under 'R'  goes against standard practise and will simply lead to confusion. As I said before, Chunkford, people in Northern Ireland always choose United Kingdom as the country so there is no ambiguity - they know "Ireland" refers to the independent state.

**Comment by Chunkford** [comment]
Not disputing it, just merely pointing out as to maybe why Ireland is listed as the Republic of Ireland.

**Comment by mikejolley** [comment]
If someone files an issue after 2.7 and asks for it to be changed back to "Republic of Ireland" I'm going to send them here to argue :)
