### ISSUE TITLE
[2.7] get_order_item_totals on refunds

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#13365]
Executing `$refund->get_order_item_totals()` throws a fatal error:

Call to undefined method WC_Order_Refund::get_payment_method_title()

`get_payment_method_title()` is not defined in the abstract but if it's used there it should be defined there too (or made conditional with `method_exists`).

Same for `$refund->get_refunds()`.

**Comment by mikejolley** [comment]
@Spreeuw Is there a use case here or was this found accidentally? `get_refunds` on a refund makes no sense, so really we should either move the method to the `WC_Order` class or have an empty method in the abstract.

**Comment by Spreeuw** [comment]
No this is done in the same `$refund->get_order_item_totals` method.
