### ISSUE TITLE
[2.7] Refund taxes: tax code shown instead of tax label

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#13366]
Taxes returned from `$refund->get_tax_totals` don't have the same label as in the original order. Instead of the user defined label, the internal rate code is used.

**Comment by mikejolley** [comment]
This data is not stored at refund level nor passed across. Refunds are never displayed independently so doing so would lead to a lot of unnecessary code. Only totals get passed to the refund objects.

**Comment by Spreeuw** [comment]
I use the refund order to create a credit invoice/credit note. This _has_ to be displayed independently, because refunds cannot be included in invoices. Therefor the refund order should be able to stand on its own.

**Comment by mikejolley** [comment]
Is this code public? Hard to patch something core has no use for.

**Comment by Spreeuw** [comment]
No it's not public, unfortunately. But I don't see why a refund order object should be any different in this aspect from a regular order object. Otherwise, what's the point in creating a separate object for it anyway?

**Comment by mikejolley** [comment]
Orders and refunds have similarities but not the full data set. e.g. a refund doesn't need a billing address.

**Comment by Spreeuw** [comment]
> This data is not stored at refund level nor passed across

I don't think this is true. `$refund->get_taxes()` does return an array of taxes but they are not correct. Non-compound taxes are set to compound and as mentioned above, the label is replaced by the rate code.

**Comment by mikejolley** [comment]
This is from a refund: 
![2017-02-27 at 16 39](https://cloud.githubusercontent.com/assets/90977/23370063/610f44e6-fd0b-11e6-8c1f-612d7d7a5ee7.png) Those are labels.

**Comment by mikejolley** [comment]
Yeah this one appears invalid. I can see in the refund creation code we use `->update_taxes`. This actually gets the label etc from the rate ID. The only way I can see this failing would be if a) the label was set via filter for the original order creation or b) the tax rate ID was not valid and thus the record could not be read to set the tax totals.

Your other issue is valid and I'm looking for ways to structure those orders better.

**Comment by Spreeuw** [comment]
Yes this is a strange issue. I cannot get the labels to show in regular order totals either. I have deactivated all plugins except WC itself. I have resaved each tax class settings. Created a new order and when doing 'calculate taxes' it now gives me the label. Is this a known issue with Beta 3?

**Comment by mikejolley** [comment]
No, try master though.

**Comment by Spreeuw** [comment]
tax rate settings:
![schermafbeelding 2017-02-27 om 17 58 33](https://cloud.githubusercontent.com/assets/3217773/23370885/6d2479bc-fd16-11e6-8a67-ed1c67da6019.png)
![schermafbeelding 2017-02-27 om 17 58 47](https://cloud.githubusercontent.com/assets/3217773/23370888/708bddca-fd16-11e6-9b0c-f204b20b0cec.png)

and the order (even after 'calculate taxes'):
![schermafbeelding 2017-02-27 om 17 57 29](https://cloud.githubusercontent.com/assets/3217773/23370838/4828b3b2-fd16-11e6-8412-753c64fb8389.png)

**Comment by Spreeuw** [comment]
No issues with master, apologies for not testing this before posting the issue.
