### ISSUE TITLE
[2.7] "Auto Draft" in variation title 

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#13363]
Create a variable product. But **keep the title empty**.
Create attributes and variations.
Once variations are created, fill in the title of the variable product (for example 'Test") and publish.
Go on front and select a variation: You get for example: "Auto Draft – Red" as variation title in the cart, instead of the expected "Test – Red".

**Comment by faisal-alvi** [comment]
I have checked twice above points and created test variation product but the title is displaying correctly,
![image](https://cloud.githubusercontent.com/assets/25176325/23364142/c8e3f338-fd23-11e6-9790-1eb937497642.png)

**Comment by mikejolley** [comment]
This issue is a) about 2.7 and b) talking about the title in the cart after adding it to the cart.
