### ISSUE TITLE
Product View Counter

### ISSUE THREAD

**Issue by MMaKenZi** [woocommerce/woocommerce#13368]
Hi

I think one of the most needed tool that currently isn't available is product view counter, 
which show how many times a product viewed by users

and the ability to see the counter on admin menu, and optionally in frontend

this is the most simplest statistical number that can help store owner for making a product better or for focusing on certain products or categories

at least I think it works this way

**Comment by mikejolley** [comment]
Google Analytics is way more powerful and does the same thing pretty much...

ideas.woocommerce.com please for feature requests so ideas can be validated.
