### ISSUE TITLE
Paypal orders are still in pending status though they have been successfully paid

### ISSUE THREAD

**Issue by keyur-padalia** [woocommerce/woocommerce#13364]
## EXPLANATION OF THE ISSUE

I am using Paypal standard which comes with the WooCommerce. Normally orders paid using paypal are changing status to processing, but occasionally there are some orders which are still in pending status although they have paid on paypal successfully.

Also in this [Documentation](https://docs.woocommerce.com/document/paypal-standard/) page it asks to use this IPN URL
http://example.com/?wc-api=WC_Gateway_Paypal
and in my Woo Payal debug log the URLs are
Notify URL: https://www.justonline.co.uk/wc-api/WC_Gateway_Paypal/

So I don't know if this URL makes any difference. There were many online discussion on disabling iTheme security and Wordfence plugin, But again if these plugins are making any problems for paypal IPN then it should be all the orders as it's not the case.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://www.justonline.co.uk
Site URL: http://www.justonline.co.uk/shop
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.3.3 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 10 MB
PHP Time Limit: 700
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: ❌ 5.1.73 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (20) ###

Akismet: by Automattic – 3.2
iThemes Security: by iThemes – 6.1.1
Bloom: by Elegant Themes – 1.1.8
Divi Builder: by Elegant Themes – 1.3.10
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.1
Magic Zoom for WooCommerce: by Magic Toolbox – 6.0.46
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Smart Reporter for e-commerce: by StoreApps – 2.9.16
SSH SFTP Updater Support: by TerraFrost – 0.7.1
WooCommerce Conversion Tracking: by Tareq Hasan – 1.2.2
WooCommerce CardSave Redirect Gateway: by CardSave Online – 2.4
WooCommerce MailChimp Integration: by WooThemes – 1.0.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.39
WooCommerce Google Product Feed: by Lee Willis – 7.0.2
WooCommerce Remove All Products: by Gabriel Reguly – 1.0.4
WooCommerce Table Rate Shipping: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
Wordfence Security: by Wordfence – 6.3.1
Yoast SEO: by Team Yoast – 4.2.1

### Settings ###

Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: JustOnline
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.34
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/woocommerce/archive-product.php
Divi-child/woocommerce/cart/mini-cart.php
Divi-child/woocommerce/product-searchform.php
Divi-child/woocommerce/single-product/add-to-cart/simple.php
Divi-child/woocommerce/single-product/related.php

`

**Comment by mikejolley** [comment]
Do you not think it prudent to test:

> But again if these plugins are making any problems for paypal IPN then it should be all the orders as it's not the case.

before posting here? Disable them and retest? Security plugins and sever firewalls can block external requests if they want to and if that happens, nothing we do our side can help.

There is a history page to see if requests are being blocked on PayPal side I believe https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNOperations/

Enable logging in PayPal standard. View the order notes for anything relating to PayPal. Follow the troubleshooting steps in the help doc https://docs.woocommerce.com/document/paypal-standard/#section-19

And remember PDT can be used as a fallback.

Reply here if you have reproducible steps and an actual bug in core so we can look into it. 99% sure it will be blocked by something in your install though.
