### ISSUE TITLE
Product categories with backslashes in the title don't show up in API search results

### ISSUE THREAD

**Issue by slukin1** [woocommerce/woocommerce#13373]
wcapi.get("products/categories?search=%s" % (u'Системы Linux \Unix')).json()
not return existed result
Escaping u'Система Linux \\Unix' not return existed result,
urllib.quote_plus(u'Система Linux \\Unix') not return existed result
quote(u'Система Linux \\Unix') not return existed result

**Comment by claudiulodro** [comment]
Is this in WooCommerce 2.6.* or the 2.7 beta?

**Comment by claudiulodro** [comment]
I have success with 
```
curl https://example.com/wp-json/wc/v1/products/categories?search="Системы Linux \\Unix" -u ck_KEY:cs_SECRET
```
and it also works on v2 of the API, so the WooCommerce API isn't to blame.

The name for that category is:
```\u0421\u0438\u0441\u0442\u0435\u043c\u044b Linux \\Unix``` 

You can also just use the category slug in the search, which shouldn't need any extra escaping or anything.

If this is an issue only with the Python wrapper, you can file a ticket at https://github.com/woocommerce/wc-api-python

**Comment by slukin1** [comment]
Name of category with one backslash: 'Система Linux \Unix', not with two like in Your curl request.
Also problem if name of category with forward slash, example category name: '/n software' and if ampersand in category name, example: 'Tools&Comps'

**Comment by claudiulodro** [comment]
@slukin1 you have to escape the backslash with an extra backslash, and escape `\n` as `\\n`, etc.

See table 10.1: https://dev.mysql.com/doc/refman/5.7/en/string-literals.html
