### ISSUE TITLE
Verbiage - Incorrect use of 'apologise' should be 'apologize'

### ISSUE THREAD

**Issue by garrett-eclipse** [woocommerce/woocommerce#13371]
## EXPLANATION OF THE ISSUE

In this string - https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=574030&filters%5Btranslation_id%5D=42710778
The word used is **apologise** and should be **apologize**

In North America we use the z where as in britain and australia it's with the s. See explanation here;
http://grammarist.com/spelling/apologise-apologize/

## STEPS TO REPRODUCE THE ISSUE

View incorrect spelling here - http://grammarist.com/spelling/apologise-apologize/

**Comment by garrett-eclipse** [comment]
There's other instances here;
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=574031&filters%5Btranslation_id%5D=42710780
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=574031&filters%5Btranslation_id%5D=23836355
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=574030&filters%5Btranslation_id%5D=42710778
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=574030&filters%5Btranslation_id%5D=23836351
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=574029&filters%5Btranslation_id%5D=42710775
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=574029&filters%5Btranslation_id%5D=23836347

**Comment by mikejolley** [comment]
Isn't this identical to https://github.com/woocommerce/woocommerce/issues/13370 ?

**Comment by garrett-eclipse** [comment]
That it is that it is, thanks @mikejolley sorry I didn't catch that other ticket. Seems to already be handled so guess it'll just take a bit to percolate into translate.wordpress.org. Closing
