### ISSUE TITLE
In default (American English) spelling should be Check and not Cheque

### ISSUE THREAD

**Issue by garrett-eclipse** [woocommerce/woocommerce#13378]
## EXPLANATION OF THE ISSUE

Found a source verbiage using Cheque rather than Check, should be updated to Check for American english.
Source - https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable-readme/en-ca/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=3925097&filters%5Btranslation_id%5D=48019778

**Comment by claudiulodro** [comment]
See #13379 for this and the other word issues.

**Comment by garrett-eclipse** [comment]
Thanks @claudiulodro
