### ISSUE TITLE
Custom permalink structure broken by anything other than default product permalink structure

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#13374]
## EXPLANATION OF THE ISSUE
Pages/posts - 404 using a custom permalink structure and anything other than default product permalink structure as seen in ticket: 538113-zd-woothemes

## STEPS TO REPRODUCE THE ISSUE
1. Set permalinks to this:
![see screen shot](http://cld.wthms.co/Db9N/3mb1tIgx+)
2. Set product permalink to this:
![see screen shot](http://cld.wthms.co/agdY/eobuCorl+)
3. Navigate to a post or page and witness the 404 sadness.

Perhaps related to #11570

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: https://twoguyswithballs.com
Site URL: https://twoguyswithballs.com/balls
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.12
PHP Post Max Size: 128 MB
PHP Time Limit: 60
PHP Max Input Vars: 4000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (27) ###

AfterShip - WooCommerce Tracking: by AfterShip – 1.6.7
AG Custom Admin: by WAP – 5.7.1
BackupBuddy: by iThemes – 7.2.2.0
Easy WP SMTP: by wpecommerce – 1.2.4
Elegant Themes Support: by Elegant Themes – 1.0
iThemes Security Pro: by iThemes – 3.6.2
Jetpack by WordPress.com: by Automattic – 4.6
MailChimp for WordPress: by ibericode – 4.0.13
Ninja Forms: by The WP Ninjas – 3.0.29
W3 Total Cache: by Frederick Townes – 0.9.5.2
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 3.4
WooCommerce Brands: by WooThemes – 1.5.0
WooCommerce Amazon Payments Advanced Gateway: by WooCommerce – 1.6.4
WooCommerce Stripe Gateway: by WooCommerce – 3.0.7
WooCommerce AdWords Conversion Tracking: by Wolf+Bär GmbH – 1.3.5
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce MailChimp: by Saint Systems – 2.0.20
WooCommerce Memberships: by WooThemes / SkyVerge – 1.7.5
WooCommerce Product Search: by itthinx – 1.8.1
WooCommerce Stock Manager: by Vladislav Musílek – 1.1.3
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
Yoast SEO: by Team Yoast – 4.3
WP Hummingbird: by WPMU DEV – 1.4.1
WP Smush Pro: by WPMU DEV – 2.5.3
WP Staging: by WP-Staging
René Hermenau – 1.1.4

WPMU DEV Dashboard: by WPMU DEV – 4.3

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #73 - /shop/
Cart: #74 - /cart/
Checkout: #75 - /checkout/
My Account: #76 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: balls
Version: 0.1.0
Author URL: https://thenetstuff.com/
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.34
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by mikejolley** [comment]
As stated in the other issue we need to prevent this being set. This will happen in 2.7 (found an issue with the slash which I'm now fixing though).

The user needs to prefix the category name. .e.g `/shop/%product_cat%/`

**Comment by twoguyswithballs** [comment]
Not quite sure preventing this is the right solution. I am assuming for most ecommerce stores having an additional level such as /shop/ in the url is redundant and unnecessary. This is also an issue for existing sites out there (such as mine) where the product URL's have already been set and changing URL's at this point is not a good option.

Appreciate if this issue can be fixed with the combination of permalink settings shown above. I had posted this on user support forum prior to contacting woo support and somebody had suggested _"most likely it's related to "flushing rewriting rules"._". Not sure what it means, but mentioning in case it helps.

Thanks for the support on this issue.

**Comment by mikejolley** [comment]
> Not quite sure preventing this is the right solution

The rewrite API in WordPress - without a base you introduce conflicts so WP doesn't know what type of post is being shown hence 404

**Comment by twoguyswithballs** [comment]
Are there any workaround that you can suggest for this? Anything custom that I can do? I have 2 level product category structure and adding /shop is going to make the URL too long for google ads and other purposes. Appreciate any suggestions that you may have... thanks

**Comment by DarrylYust** [comment]
Was there ever a better resolution to this? I think I'm hitting the same issue as the OP.  My specific symptom is that with Custom Structure=/%product_cat%/, navigating to pages resolved via shortcode (eg [woocommerce_cart], [woocommerce_checkout]) results in 404.  Yes, I've disabled all plugins, reverted to twentyseventeen theme, deleted .htaccess, and re-saved from the Permalinks page - still repros. Switching back to Plain fixes the issue.

Breaking the Custom Structure feature without warning or a migration plan seems terrible - not only does this break internal linkage (fixable, with some effort), but worse it invalidates any search engine URLs out in the wild and degrades our search-friendliness - which is the whole point of Permalinks in the first place, right?  

Please help me understand.

**Comment by mikejolley** [comment]
> Breaking the Custom Structure feature without warning or a migration plan seems terrible

This has never worked correctly for he reasons above - conflicts with other post types.

**Comment by twoguyswithballs** [comment]
Unfortunately I had to change my product and category base which was a bit of work to say the least. Had to do 301 redirects and change internal links. In addition I had change from a multi level product category heirarchy to a single flat level.

Here's an example of a product page which has the "shop" base (i.e. /shop/%product_cat%/)
https://twoguyswithballs.com/shop/used-golf-balls/titleist-pro-v1/

Example of blog post with "blog" base (i.e. /blog/%postname%/)
https://twoguyswithballs.com/blog/titleist-prov1-vs-v1x/

**Comment by DarrylYust** [comment]
"never worked correctly"? My previously functional website begs to differ with this assessment.

Thanks for the update, TwoGuys!

**Comment by mikejolley** [comment]
Whether thats the case or not, we cannot support a feature which works for some, not for others, and has known issues. Permalinks need to be unique or conflicts will arise eventually.
