### ISSUE TITLE
default language file for English US uses incorrect spelling of apologize

### ISSUE THREAD

**Issue by smtibor** [woocommerce/woocommerce#13370]
## EXPLANATION OF THE ISSUE

the word apologize is misspelled in the EN-US localization file in 3 places. it is currently written as apologise. Lines 15703, 15709, and 15717 are affected.

## STEPS TO REPRODUCE THE ISSUE

Generate any out of stock error message. The word is spelled incorrectly in the woocommerce.pot file.
 
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://www.teamsoulsports.com
Site URL: https://www.teamsoulsports.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: ❌ 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 205 MB
PHP Time Limit: 500
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: 5.6.25
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (26) ###

Gravity Forms: by rocketgenius – 2.1.3
All In One SEO Pack: by Michael Torbert – 2.3.11.4
BAW Login/Logout menu: by Juliobox – 1.3.3
Contact Form 7: by Takayuki Miyoshi – 4.6.1
Disable Comments: by Samir Shah – 1.6
Duplicate Post: by Enrico Battocchi – 3.1.2
Google Tag Manager for Wordpress: by Thomas Geiger – 1.5.1
Enable Media Replace: by Måns Jonasson – 3.0.6
Envato WordPress Toolkit: by Envato – 1.7.3
Simple Calendar: by Moonstone Media – 3.1.9
Gravity Forms User Registration Add-On: by rocketgenius – 3.7
Instagram Feed: by Smash Balloon – 1.4.8
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12.1
Nav Menu Roles: by Kathy Darling – 1.8.6
Slider Revolution: by ThemePunch – 5.2.5.1
Templatera: by WPBakery – 1.1.10
Varnish HTTP Purge: by Mika Epstein – 4.0.2
Veented Twitter: by Michael Strong – 1.1.0
Waxom Core: by Veented – 1.1.4
WooCommerce Braintree Gateway: by WooThemes / SkyVerge – 3.3.2
WooCommerce PayPal Powered by Braintree Gateway: by WooThemes – 1.2.7
WooCommerce Memberships: by WooThemes / SkyVerge – 1.7.5
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.5.8.1

WooCommerce Subscriptions: by Prospress Inc. – 2.1.3
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #1037 - /all-products-and-services/
Cart: #740 - /cart/
Checkout: #741 - /checkout/
My Account: #742 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Waxom Child
Version: 1.0.0
Author URL: http://themeforest.net/user/Veented
Child Theme: ✔
Parent Theme Name: Waxom
Parent Theme Version: 1.2.5
Parent Theme Author URL: http://themeforest.net/user/Veented
WooCommerce Support: ✔

### Templates ###

Overrides: waxom/woocommerce/archive-product.php
waxom/woocommerce/single-product.php

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: 

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: 
`

**Comment by mikejolley** [comment]
![7eb9b9ec3bf01237e3faf175d5a7035a8310e8a9f9daf025c5e442ac2ea389d3](https://cloud.githubusercontent.com/assets/90977/23372418/78131fb6-fd13-11e6-8ab8-db01ad55a6db.jpg)

**Comment by smtibor** [comment]
*  Sean Tibor*

  Founder / Principal Consultant

  sean@redreefdigital.com
  +1.561.475.1647 <+15614751647>

 Schedule a meeting with me <https://calendly.com/seantibor>

<http://www.redreefdigital.com/>

www.redreefdigital.com
<http://www.redreefdigital.com/?utm_source=email_signatures&utm_medium=email&utm_content=sean&utm_campaign=Corporate%20Branding>

**Comment by smtibor** [comment]
![image](https://cloud.githubusercontent.com/assets/9659717/23372527/f6e6ed88-fce9-11e6-8828-99346a2ba392.png)

Thank you!
