### ISSUE TITLE
[2.7] Order date no longer updated when payment completed

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#13380]
In WC prior to 2.7, `WC_Abstract_Order::payment_complete()` would update the order's `post_date` and `post_date_gmt` columns to the time the payment was completed. In WC 2.7+, these columns are not updated. Only the order's paid date is updated.

While that seems like the correct approach, it is a major breaking change.

With WC < 2.7, it was possible to use an order's date as the date the payment was actually processed. That's no longer possible, and instead, the paid date needs to be used. Unfortunately, with WC < 2.7, the paid date wasn't always set, meaning it can't be relied upon to exist for orders created with WC < 2.7.

In theory, it would be possible to look at the order's version and take that into account to use different logic for different order versions. However, WC 2.7 also updates the version whenever order data is updated (see #13381), meaning if some unrelated part of the order is updated, like the totals, when WC 2.7+ is running, then the version number will also be increased on the order, even though its paid date would still be determined using the logic from WC < 2.7.

This makes it impossible to determine in a version compatible way when an order was actually paid. 

I suspect this will have a lot of flow on consequences that cause issues for stores. For example, it causes major issues for something like recurring payments, where next payment dates are calculated based on the last payment date.

**Comment by mikejolley** [comment]
@thenbrent In 2.6, we have:

```
if ( 'pending' === $old_status && ! $manual ) {
			$update_post_data[ 'post_date' ]     = current_time( 'mysql', 0 );
			$update_post_data[ 'post_date_gmt' ] = current_time( 'mysql', 1 );
}
```

This is almost identical to the code you pointed our as being erroneous in https://github.com/woocommerce/woocommerce/issues/13376

As you said in 13376,

> The problem with this is that it makes the paid date property ambiguous. In many cases, it won't refer to the date on which the order was paid. By extension, it also doesn't mean the order has actually been paid, it just means the order isn't pending anymore. Finally, it creates inconsistencies with logic in WC_Order::needs_payment().

I don't think this can reliable be used for what you're suggesting, even if we continued to update these dates in 2.7.x. I will add this to the update notes in the WIKI so there is record of it.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-2.7.x-Developer-Migration-Notes#order-post-dates

**Comment by mikejolley** [comment]
Will adjust #13375 accordingly to help with "This makes it impossible to determine in a version compatible way when an order was actually paid.".
