### ISSUE TITLE
WC REST API - category resource IDs invalid after creation.

### ISSUE THREAD

**Issue by maximumver** [woocommerce/woocommerce#13386]
## EXPLANATION OF THE ISSUE

Hi, 
i was building some import program, 
that should import/port categories & 
products from one particular source with really weird hierarchy to woocommerce,
i've decided to make it with woocommerce WC REST API first(i thought it would be faster & cleaner).

But i've encountered something, which makes me think its a bug.
And to go further in my work i must do some workarounds.

Example:
I create categories via "batch update" -> "create"
I do have categories that have similar names, but different parents. So must be ok.

When i do this for the first time REST API response is good.
Categories are created, they have different ids & different parents ids.

But when i do "batch update: create" for the 2nd time ->  with same categories.
Or even if i try to create separately with "create a product category"

I expect that WC REST API will return that both categories already exist 
code:"term_exists" & 
i could see their ids under
"data" -> "resource_id"

But instead of seeing 2 different ids of two different existing categories i see two objects with the same resource_id, even if their parents are different.

## STEPS TO REPRODUCE THE ISSUE

1. 
Create 2 categories in any way( one by one or batch) with equal name but different parents. 
As a response you will receive 2 obj, where you can find their ids. 
Two different cats two different ids. OK!

2.
Create them again! NOT UPDATE! CREATE. SO REPEAT STUFF DONE ABOVE WITHOUT CHANGING A THING.
As a response you will receive 2 error objects.
BUT under data->resource_id  we see the SAME ID. // NOT OK
They must be different!
Two different categories. 2 different ids.

Everything is latest, WP latest, WC latest. 
Please, fix it, stuff i've done already depends very much on this response.
This forces me to create unexpected workarounds to entire design.

THANK YOU!

**Comment by mikejolley** [comment]
CALM :)

**Comment by mikejolley** [comment]
See https://core.trac.wordpress.org/ticket/39984#comment:1 - this is an issue with the `wp_insert_term` function, not the API.

**Comment by maximumver** [comment]
Hello again,
other 2 bugs:

1.
when i am creating via batch same product twice, 
the error response doesn't contain id of existing product.
I mean "error->data->resource_id" == 0.
But when i do the same with categories, "resource_id" contains "id" of existing category.
With products its always 0.
So if i try to create same product twice i don't get id of existing product.
Yes i get an error about its existence, but thats all.
In my work while importing i am creating & updating & saving id maps, because of very different hierarchy of source from which i am importign products. 
And this bug is bad for me, forces me to create workarounds....

2.
And another bug.
When i am creating products via batch, by chunks of 100 products at time, sometimes i don't get response from server, products are created, but response is empty.
Can't create any id map in such situation.
Can't think about workaround here, even if it's possible, too tired lol.
However i've thought it would be right to report these issues.

Thank you.

**Comment by claudiosanches** [comment]
>when i am creating via batch by chunks same product twice,
>the error response doesn't contain id of existing product.
>I mean "error->data->resource_id" == 0.
>But when i do the same with categories, "resource_id" contains "id" of existing category.
>With products its always 0.

`wp_insert_term()` returns errors when try create a term with the same slug, but `wp_insert_post()` don't returns any error and just create a new slug with a `-2` suffix.
We can do the same for categories, check if already exists and then create a new one with `-2` suffix, it's not a problem.

> When i am creating products via batch, by chunks of 100 products at time, sometimes i don't get response from server, products are created, but response is empty.

Need to turn on the `WP_DEBUG` on your site and test it, for sure using too many memory or something else that is stopping to send back any message.

**Comment by maximumver** [comment]
`wp_insert_term() returns errors when try create a term with the same slug, but wp_insert_post() don't returns any error and just create a new slug with a -2 suffix. This behavior is from WordPress.
We can do the same for categories, check if already exists and then create a new one with -2 su`

Hi, thx for quick response,  but i'm not sure if we understood each other :)
Error on existing product is OK ! I need it.
Don't need to create duplicates with -2 suffix.
I need that error & when you work with categories that error returns ID of the category if that category already exists.
1. I try to create already existing category -> got an error:  "error->data->resource_id" contains ID of this existing category ! OK.
2. I try to create already existing product -> got an error: products exists. OK, but "error->data->resource_id" == 0. Always equal 0. I need ID of that product like with the categories.

Since "category exists error" returns ID of that existing category i've thought that same will happen when i'll try to create existing product -> i'll get an error & its ID.
Because the structure of error object is the same.
Sorry if i was wrong & this wasn't default behaviour.


`Need to turn on the WP_DEBUG on your site and test it, for sure using too many memory or something else that is stopping to send back any message.`

Yeah you probably right! I thought about memory issue too.
Will look into that WP_DEBUG thing, not very familiar with wordpress debugging,
thats first time i am doing something that "big" for WP, thats why decided to use REST API.

**Comment by claudiosanches** [comment]
@maximumver but there is no `product exists` error, only if you try POST some product with an ID.

**Comment by maximumver** [comment]
@claudiosanches sorry, today i'm not working on this, but if i remember well it returns the error because the product with that "sku" exists already.

**Comment by maximumver** [comment]
and in this case it would be great to get that product id back; since API responds that product with that sku exists.

**Comment by claudiosanches** [comment]
@maximumver so it's already solved in WooCommerce 2.7, now we include the ID when the `sku` already exists.

**Comment by maximumver** [comment]
@claudiosanches oh, didn't know it's solved, used 2.6.14 version from wordpress internal plugin storage.  Didn't check last version on github, my bad.
 So remains the problem when sometimes there is no response(probably memory issue, will look into)

Thank you!

**Comment by maximumver** [comment]
@claudiosanches 
Hi, i've downloaded the last version of WC RC
And enabled debug.
However i got no errors inside log.

How i can check memory usage?

**Comment by claudiosanches** [comment]
The last RC it's not a final version and we are still fixing bugs.
