### ISSUE TITLE
Allow use of a specific instance of a data store

### ISSUE THREAD

**Issue by prettyboymp** [woocommerce/woocommerce#13393]
The constructor in `WC_Data_Store` always creates a new instance of the underlying data store, https://github.com/woocommerce/woocommerce/blob/7a86ca23610add14a9a8e4cd702fbf0827fa3198/includes/class-wc-data-store.php#L78.  It would be helpful if plugins using the `woocommerce_data_stores` or `woocommerce_' . $object_type . '_data_store` filters could return a specific object instance instead of the class name.  

This would be helpful in cases where the data store needs to be singleton or specific properties need to be passed to the data store before it is used, e.g. giving it a custom instance of `\wpdb`.

**Comment by mikejolley** [comment]
@prettyboymp are you sending that as a PR?
