### ISSUE TITLE
Fatal error - Syntax error in WooCommerce 2.7 RC1

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#13396]
File `class-wc-data-store.php`, line 75

The following check is not valid:
~~~
if ( ! class_implements( $store, WC_Object_Data_Store_Interface::class ) ) {
  // Code...
}
~~~

The correct implementation, based on an educated guess about its purpose, should be the following:
~~~
$implements = class_implements( get_class($store) );
if ( ! in_array( 'WC_Object_Data_Store_Interface', $implements ) ) {
  // Code...
}
~~~

**Comment by mikejolley** [comment]
@daigo75 what triggers that error? I'm not seeing it anywhere and tests are passing.

**Comment by daigo75** [comment]
Simply enabling WooCommerce triggers the error (I'm using the master branch of the repository). 

The line that triggers the error is indeed incorrect. * Function class_implements() cannot be called that way. It returns all the interfaces implemented by a class, it's not used to check if a class implements a specific interface. 
* WC_Object_Data_Store_Interface::class is an incorrect statement. WC_Object_Data_Store_Interface is already a class, which doesn't have a "class" property.

**Comment by claudiulodro** [comment]
See #13408.
