### ISSUE TITLE
WC 2.7 RC1 | srcset is missing for gallery control nav images

### ISSUE THREAD

**Issue by komarovartem** [woocommerce/woocommerce#13404]
If gallery takes the width of 600px or more control nav images will look pixelated. 

I'm not sure if you need this but the fast fix is to add a srcset attr to control nav image in jquery.flexslider.js. 

line 240

`var srcset = ( undefined !== slide.find('img').attr( 'srcset' ) ) ? srcset = ' srcset="' + slide.find('img').attr( 'srcset' ) + '"' : '';
              item = (slider.vars.controlNav === "thumbnails") ? '<img src="' + slide.attr( 'data-thumb' ) + '"' + altText + srcset + '/>' : '<a href="#">' + j + '</a>';`

**Comment by mikejolley** [comment]
I don't think this is necessary - you can control the size of thumbnails in settings or from your theme which has always been the case. Just increase it from the default. We shouldn't modify a script as that would mean we have to run a custom version.

**Comment by komarovartem** [comment]
Thanks for response. I get your point but increasing size of shop thumbnails is not a good solution. Let me explain. Currently, thumbnails is 150x150 and it is works perfectly for retina because of srcset. But if the image has no srcset attr and it takes container width of 150px (like with slider control nav) on retina display images look not so great. If you increase the size of thumbnails in two times for retina just for thumbnails of control nav it will be mean increasing all thumbnail images (cart, widgets and etc) for all display types and resolutions. Which will mean a frontend performance issue (increasing the size of the page and etc).  Also, css or html scaled images has hight priority for page speed scores like gtmetrix.com.

**Comment by jameskoster** [comment]
@jeffikus possible addition to Flexslider ? :)
