### ISSUE TITLE
Fatal error on activation

### ISSUE THREAD

**Issue by absoluteweb** [woocommerce/woocommerce#13406]
## EXPLANATION OF THE ISSUE

The extension could not be activated because it triggered a fatal error.

Parse error: syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in /home/xxxxx/www/wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 75 

## STEPS TO REPRODUCE THE ISSUE

Activate WooCommerce 2.7 RC1.

## SYSTEM STATUS REPORT

PHP 5.3.3

**Comment by mikejolley** [comment]
It's this - https://github.com/woocommerce/woocommerce/issues/13396 It's a PHP 5.5+ thing. We'll fix before release but to test you'll want a better version of PHP.
