### ISSUE TITLE
WC 2.7 RC1 | Variation image does not swipe after choosing

### ISSUE THREAD

**Issue by komarovartem** [woocommerce/woocommerce#13402]
Gallery in a variable product does not work as it was presented in a video https://youtu.be/ialMKuaVHm8 

After choosing the variation the image is added to gallery nav but the gallery does not swipe to it. To make it clear, please check the video https://cloudup.com/c9K01HV2YGT
 
Tested on the last ver. of WP and Storefront

**Comment by claudiulodro** [comment]
See #13416.
