### ISSUE TITLE
WP e-Commerce user and you have had issues with users getting corrupted or damaged download

### ISSUE THREAD

**Issue by daniel-bios** [woocommerce/woocommerce#13407]
if you are a WP e-Commerce user and you have had issues with users getting corrupted or damaged download files than this post if for you.

I have a website in Wordpress with Woo comerce integrated , where there are downloadable files.There have been a couple of days, that when users download files , most of them are damaged. These files are not downloaded with the correct size.
In the server , the file sizes are correct.
for example a 3 MB file in the server , when is downloaded from the user , it appears to be 44 KB, and not 3 MB.
All the damaged files dowloaded from the users , have a standard size of 44 KB.

Is there any way to solve this issue?

**Comment by mikejolley** [comment]
Are you talking about WP e-Commerce or WooCommerce - they are not the same..

**Comment by daniel-bios** [comment]
my mistake  At the WooCommerce plugin

**Comment by mikejolley** [comment]
Change the download method in settings. What is it set to now? WC > Settings > Products > Downloadable products

**Comment by daniel-bios** [comment]
thank you a lot for your help

i just solve the problem using your asssistance

**Comment by mikejolley** [comment]
What was it set to?

**Comment by daniel-bios** [comment]
It was Force Download
I changed it to Redirect only

**Comment by mikejolley** [comment]
Ok; some servers can have trouble with force. Depends on the setup and file itself.
