### ISSUE TITLE
WC 2.7 RC1 API issue

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#13405]
## STEPS TO REPRODUCE THE ISSUE

I tried to import products printful via API but got 500 error:

52.52.37.39 - - [01/Mar/2017:14:22:20 +0000] "POST /wc-api/v2/products?consumer_key=**remove**&consumer_secret=**remove**&_rand=30466510 HTTP/1.1" 500 5 "-" "Printful WooCommerce Integration"

## SYSTEM STATUS REPORT
WooCommerce 2.7.0
WordPress 4.7.2
PHP 7.1.1
Theme Storefront 2.1.8
```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Look at the server error logs or we have nothing to work with.

**Comment by kevin25** [comment]
Here is what i got from error log


> 2017/03/01 14:57:55 [error] 18349#0: *87404 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method WC_Product_Variable::create() in /home/language/public/wp-content/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-products.php:267
> Stack trace:
> #0 /public/wp-content/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-server.php(372): WC_API_Products->create_product(Array)
> #1 /public/wp-content/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-server.php(223): WC_API_Server->dispatch()
> #2 /public/wp-content/plugins/woocommerce/includes/class-wc-legacy-api.php(269): WC_API_Server->serve_request()
> #3 /public/wp-content/plugins/woocommerce/includes/class-wc-legacy-api.php(101): WC_Legacy_API->handle_v2_rest_api_request()
> #4 /public/wp-includes/class-wp-hook.php(298): WC_Legacy_API->handle_rest_api_requests(Object(WP))
> #5 /public/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
> #6 /public/wp-includes/p"

**Comment by mikejolley** [comment]
Thanks

**Comment by kevin25** [comment]
@mikejolley It's my pleasure. Any idea about it?

**Comment by mikejolley** [comment]
Looks like the old API is using some non existing functions. @claudiosanches @claudiulodro

**Comment by kevin25** [comment]
I pulled the latest pull and it didn't work.

216.51.130.154 - - [03/Mar/2017:07:26:17 +0000] "GET /wc-api/v3/products/categories?fields=name,id HTTP/1.1" 401 111 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
216.51.130.154 - ck_deleted [03/Mar/2017:07:26:17 +0000] "GET /wc-api/v3/products/categories?fields=name,id HTTP/1.1" 200 36 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
216.51.130.154 - - [03/Mar/2017:07:26:31 +0000] "POST /wc-api/v3/products HTTP/1.1" 401 111 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"
216.51.130.154 - ck_deleted [03/Mar/2017:07:26:38 +0000] "POST /wc-api/v3/products HTTP/1.1" 500 5 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"

**Comment by claudiulodro** [comment]
It looks like you're getting `HTTP Error 401 - Unauthorized: Access is denied due to invalid credentials` errors, which happens when you're not using the correct key/secret pair or not authenticating properly.

**Comment by kevin25** [comment]
@claudiulodro Nope. The key/secret is correct. We used the remote app connect to Woo via api. At the first time we authorized the access. Look at the third and the fourth lines: 500 Error status. It should be something wrong. Is there changes on API? @claudiosanches  @mikejolley

**Comment by kevin25** [comment]
I found out that the error happened while creating variant products only.

`curl -X POST https://example.com/wc-api/v3/products \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "product": {
    "title": "Ship Your Idea",
    "type": "variable",
    "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "categories": [
      9,
      14
    ],
    "images": [
      {
        "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-black-front.jpg",
        "position": 0
      },
      {
        "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-black-back.jpg",
        "position": 1
      },
      {
        "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-green-front.jpg",
        "position": 2
      },
      {
        "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-green-back.jpg",
        "position": 3
      }
    ],
    "attributes": [
      {
        "name": "Color",
        "slug": "color",
        "position": "0",
        "visible": false,
        "variation": true,
        "options": [
          "Black",
          "Green"
        ]
      }
    ],
    "default_attributes": [
      {
        "name": "Color",
        "slug": "color",
        "option": "Black"
      }
    ],
    "variations": [
      {
        "regular_price": "19.99",
        "image": [
          {
            "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-black-front.jpg",
            "position": 0
          }
        ],
        "attributes": [
          {
            "name": "Color",
            "slug": "color",
            "option": "black"
          }
        ]
      },
      {
        "regular_price": "19.99",
        "image": [
          {
            "src": "http://example.com/wp-content/uploads/2015/01/ship-your-idea-green-front.jpg",
            "position": 0
          }
        ],
        "attributes": [
          {
            "name": "Color",
            "slug": "color",
            "option": "green"
          }
        ]
      }
    ]
  }
}'`

**Comment by claudiulodro** [comment]
^ That request gives the following errors:
```
<b>Notice</b>:  Undefined variable: data in <b>/srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php</b> on line <b>1821</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Cannot use object of type WC_Product_Variation as array in /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php:1884
Stack trace:
#0 /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php(340): WC_API_Products-&gt;save_variations(Object(WC_Product_Variable), Array)
#1 /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-server.php(372): WC_API_Products-&gt;create_product(Array)
#2 /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-server.php(223): WC_API_Server-&gt;dispatch()
#3 /srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce/includes/class-wc-legacy-api.php(111): WC_API_Server-&gt;serve_request()
#4 /srv/www/wordpress-default/public_html/wp-includes/class-wp-hook.php(298): WC_Legacy_API-&gt;handle_rest_api_requests(Object(WP))
#5 /srv/www/wordpress-def in <b>/srv/www/wordpress-default/public_html/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php</b> on line <b>1884</b><br />
```

**Comment by kevin25** [comment]
@claudiulodro can you fix it today?

**Comment by claudiulodro** [comment]
@kevin25 I have a pull request open with the fix, but it likely won't get merged into master until Monday morning. You can check out the woocommerce/fix-13405-2 branch, which has the changes in it, if it's getting in the way of your compatibility testing.

**Comment by kevin25** [comment]
@claudiulodro  I tested it with three remote apps and just one worked for me. I posted the above deprecated api code. Here is the latest one. Can you check it? I still got 401 status but at least i can put products to my store. 

http://woocommerce.github.io/woocommerce-rest-api-docs/?shell#create-a-product

> curl -X POST https://example.com/wp-json/wc/v1/products \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "name": "Ship Your Idea",
  "type": "variable",
  "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
  "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
  "categories": [
    {
      "id": 9
    },
    {
      "id": 14
    }
  ],
  "images": [
    {
      "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_4_front.jpg",
      "position": 0
    },
    {
      "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_4_back.jpg",
      "position": 1
    },
    {
      "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_3_front.jpg",
      "position": 2
    },
    {
      "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_3_back.jpg",
      "position": 3
    }
  ],
  "attributes": [
    {
      "id": 6,
      "position": 0,
      "visible": false,
      "variation": true,
      "options": [
        "Black",
        "Green"
      ]
    },
    {
      "name": "Size",
      "position": 0,
      "visible": true,
      "variation": true,
      "options": [
        "S",
        "M"
      ]
    }
  ],
  "default_attributes": [
    {
      "id": 6,
      "option": "Black"
    },
    {
      "name": "Size",
      "option": "S"
    }
  ],
  "variations": [
    {
      "regular_price": "19.99",
      "image": [
        {
          "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_4_front.jpg",
          "position": 0
        }
      ],
      "attributes": [
        {
          "id": 6,
          "option": "black"
        },
        {
          "name": "Size",
          "option": "S"
        }
      ]
    },
    {
      "regular_price": "19.99",
      "image": [
        {
          "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_3_front.jpg",
          "position": 0
        }
      ],
      "attributes": [
        {
          "id": 6,
          "option": "green"
        },
        {
          "name": "Size",
          "option": "M"
        }
      ]
    }
  ]
}'


> [04/Mar/2017:02:31:44 +0000] "POST /wc-api/v3/products HTTP/1.1" 401 111 "-" "Mozilla/4.0 (compatible; Win32; WinHttp.WinHttpRequest.5)"

**Comment by claudiosanches** [comment]
See #13466

**Comment by kevin25** [comment]
So which one should i pull now?

**Comment by claudiosanches** [comment]
@kevin25 just pull from master.

**Comment by kevin25** [comment]
Thank you. I pulled it some mins ago and tested it but it was till the same. I still got 500 status.

> PUT /wc-api/v3/products/bulk?oauth_timestamp=1488635847&oauth_signature_method=HMAC%2DSHA256&oauth_consumer_key=DELETED&oauth_nonce=00022D5F98C10721079449432110970D&oauth_signature=xCUpOxLqKTsvehkk5GHVGZQ5Hr3rDxkMb%2FiCagjO4nk%3D HTTP/1.1" 500 5 "-" "ColdFusion"

**Comment by claudiosanches** [comment]
@kevin25 please enable the WP_DEBUG: https://codex.wordpress.org/Debugging_in_WordPress 
Put this into your `wp-config.php`:

```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );
```

This will generate a `wp-content/debug.log` file that will describe better if have any error.

**Comment by kevin25** [comment]
Here is what i got from log:

> [04-Mar-2017 15:02:55 UTC] PHP Notice:  Undefined variable: id in /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php on line 2144
[04-Mar-2017 15:03:01 UTC] PHP Notice:  Undefined variable: id in /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php on line 2144
[04-Mar-2017 15:03:02 UTC] PHP Notice:  Undefined variable: id in /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php on line 2144
[04-Mar-2017 15:03:13 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_name() on integer in /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php:1130
Stack trace:
#0 /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php(202): WC_API_Products->get_product_data(1382)
#1 /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php(450): WC_API_Products->get_product(1387)
#2 /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php(3095): WC_API_Products->edit_product(1387, Array)
#3 /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-server.php(372): WC_API_Products->bulk(Array)
#4 /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-server.php(223): WC_API_Server->dispatch()
#5 /path/to/web/wp-content/plugins/woocommerce/includes/class-wc-legacy-api.php(111): WC_API_Server->se in /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php on line 1130
[04-Mar-2017 15:03:17 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_name() on integer in /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php:1130
Stack trace:
#0 /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php(202): WC_API_Products->get_product_data(1382)
#1 /path/to/web/wp-content/plugins/woocommerce/includes/class-wc-webhook.php(265): WC_API_Products->get_product(1387)
#2 /path/to/web/wp-content/plugins/woocommerce/includes/class-wc-webhook.php(355): WC_Webhook->get_legacy_api_payload('product', 1387, 'updated')
#3 /path/to/web/wp-content/plugins/woocommerce/includes/class-wc-webhook.php(195): WC_Webhook->build_payload(1387)
#4 /path/to/web/wp-content/plugins/woocommerce/includes/wc-core-functions.php(913): WC_Webhook->deliver(1387)
#5 /path/to/web/wp-includes/class-wp-hook.php(298): wc_deliver_webhook_async(10, 1387)
#6 /path/to/web/wp-includes/class-wp-hook.php(323): WP_H in /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php on line 1130

**Comment by claudiosanches** [comment]
@kevin25 what data is are you using? Can you show me your JSON?
I'm using the same that you pasted where, that is the same of the REST API docs and works just fine.

**Comment by claudiosanches** [comment]
@kevin25 try pull again and check if is working now.

**Comment by kevin25** [comment]
I'm using fulfillment service from some companies. I don't really have JSON then. Here it is http://www.customcat.com/. You have to connect to your store before importing products.

Updated: I just pulled it and still the same issue.

**Comment by kevin25** [comment]
Any update on this @claudiulodro  @claudiosanches

**Comment by mikejolley** [comment]
If you pulled the updated code there is no way it could be the same issue because the `$id` variable was swapped out... @claudiulodro you reopened this - did you spot something else?

**Comment by claudiulodro** [comment]
I just wanted to check on the second error in the wall of stack traces and make sure it had been adressed: ```[04-Mar-2017 15:03:17 UTC] PHP Fatal error: Uncaught Error: Call to a member function get_name() on integer in /path/to/web/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php:1130
``` If that one looks good, also, I'll re-close it.
