### ISSUE TITLE
How to customize single product page

### ISSUE THREAD

**Issue by marcx00** [woocommerce/woocommerce#13412]
How can one add credit card images under add to cart button?

Would it go something like this?
These are where the images are located,

`// Custom Credit Card Icons
add_filter ?
custom_woocommerce_icons() {
    $icon  = '<img src="' . trailingslashit( get_template_directory_uri() ) . 'images/build/svg/visa.svg' . '" alt="Visa" />';
    $icon .= '<img src="' . trailingslashit( get_template_directory_uri() ) . 'images/build/svg/mastercard.svg' . '" alt="Mastercard" />';
    $icon .= '<img src="' . trailingslashit( get_template_directory_uri() ) . 'images/build/svg/amex.svg' . '" alt="American Express" />';
    $icon .= '<img src="' . trailingslashit( get_template_directory_uri() ) . 'images/build/svg/discover.svg' . '" alt="Discover" />';
    $icon .= '<img src="' . trailingslashit( get_template_directory_uri() ) . 'images/build/svg/jcb.svg' . '" alt="JCB" />';
    $icon .= '<img src="' . trailingslashit( get_template_directory_uri() ) . 'images/build/svg/diners.svg' . '" alt="Diners Club" />';`

And how to adjust the spacing?

**Comment by mikejolley** [comment]
> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://woocommerce.com/my-account/tickets/ for premium plugin support

Or the facebook groups. Please use Github for bug reports only.
