### ISSUE TITLE
parent_id not set properly on grouped child products

### ISSUE THREAD

**Issue by michael-lynch** [woocommerce/woocommerce#13417]
## EXPLANATION OF THE ISSUE

Using the new 2.7 RC, I added a _Grouped_ Product that houses multiple _Simple_ products. When I `get` the products, the `parent_id` property isn't set properly on the child products.

## STEPS TO REPRODUCE THE ISSUE

Add a Grouped product with a Simple Product in `Linked Products > Grouped Products` and then `get` the products:

```
$woocommerce->get('products', []);
```

**Comment by mikejolley** [comment]
Parent IDs are no longer used for this.

**Comment by michael-lynch** [comment]
Ah, ok. I just noticed the new `grouped_products` array on the product object. I presume that is what is used to determine if a product has grouped products. Is there any way to determine if a product _is_ part of a group (i.e. a child product)?

**Comment by mikejolley** [comment]
With SQL. Not really necessary for core. Products can now be in multiple groups.
