### ISSUE TITLE
Not triggering woocommerce_order_status_changed action

### ISSUE THREAD

**Issue by gigashiro** [woocommerce/woocommerce#13411]
## EXPLANATION OF THE ISSUE

When I change order status in admin page, the action **woocommerce_order_status_changed** was not triggered at file includes/abstracts/abstract-wc-order.php:2393 $new_status is always the same as $old_status, because WP saves the post before it been retrieved by WC.

## STEPS TO REPRODUCE THE ISSUE

Add programatically a hook:
add_action('woocommerce_order_status_changed', function ($id, $old_status, $new_status) {
die(var_dump([$id, $old_status, $new_status)]));
});

On /wp-admin/edit.php?post_type=shop_order (Order admin page)
 - Select one order
 - Change "Order status" field
 - Click on "Save order"
When functional, expects a died page dumping post ID, old post status and new post status.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://aprova.dev.convergetecnologia.com.br
Site URL: http://aprova.dev.convergetecnologia.com.br
WC Version: 2.6.9
Log Directory Writable: ✔
WP Version: 4.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_BR

### Server Environment ###

Server Info: nginx/1.4.6
PHP Version: 5.6.30-1+deb.sury.org~trusty+1
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ O seu servidor não possui a classe SoapClient ativada - alguns métodos de pagamento que usam SOAP podem não funcionar como esperado.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Post Remoto: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.9
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (20) ###

WP Offload S3 Lite: por Delicious Brains – 1.1.4
Amazon Web Services: por Delicious Brains – 1.0.1
WPBakery Visual Composer: por Michael M - WPBakery.com – 4.12
NotifyPOP: por Carlos Shirasawa – 2.0.0
Slider Revolution: por ThemePunch – 5.2.5
Saraiva API: por 2013-2016 Equipe NightCoders (Shiro) – 0.0.1
Saraiva Serviços: por Carlos Shirasawa (Shiro) – 3.0.0
Saraiva Login: por Carlos Shirasawa (Shiro) – 3.0.0
Saraiva Mail (AWS): por Carlos Shirasawa – 1.0.2
SOMOS - Integração RDStation: por Equipe Nightcoders (Shiro) – 0.0.5
SOMOS Educação: por Equipe NightCoders (Shiro) – 0.0.2
Google Analytics: por WebDorado – 1.0.12
WooCommerce Direct Checkout: por Terry Tsang – 1.1.2
WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.4.5
WooCommerce PayPal Express Checkout Gateway: por Automattic – 1.1.2
WooCommerce PagSeguro: por Claudio Sanches – 2.11.4
WooCommerce Piwik integration: por Piwik PRO – 2.1.3
WooCommerce: por WooThemes – 2.6.9
WP-Piwik: por http://www.braekling.de – 1.0.14
YITH WooCommerce Product Bundles: por YITHEMES – 1.0.18

### Settings ###

Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Base da loja: ❌ O ID da página foi definido
mas a página não existe.

Carrinho: #7 - /carrinho/
Finalizar compra: #8 - /finalizar-compra/
Minha conta: #9 - /minha-conta/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

### Theme ###

Name: Saraiva Aprova
Version: 1.0
Author URL: 
Child Theme: ❌ – Caso você esteja personalizando o WooCommerce em um tema pai que você não desenvolveu
então recomendamos utilizar um tema filho. Veja como criar um tema filho

WooCommerce Support: ✔

### Templates ###

Overrides: O seu tema tem um arquivo woocommerce.php
você não será capaz de sobrescrever o arquivo woocommerce/archive-product.php
desde que a prioridade é para o arquivo woocommerce.php. Este aviso destina-se apenas a prevenir problemas de exibição.

Overrides: site-saraivaaprova/woocommerce/checkout/form-checkout.php
`

**Comment by claudiulodro** [comment]
This problem is fixed in 2.7.*

**Comment by gigashiro** [comment]
Thanks guys, you are amazing!
