### ISSUE TITLE
Taxes not handled correctly when using Taxamo plugin for EU compliance

### ISSUE THREAD

**Issue by AdriOosterwijk** [woocommerce/woocommerce#13429]
Hi,

In the site I'm developing I'm using the WooCommerce Taxamo plugin for EU Compliant handling of the VAT etc.

In the Beta 3 version the VAT is not shown on the order details page, nor are they printed on the invoice. The label for the VAT however is the correct on, invoked by Taxamo. In my account at Taxamo the VAT amount is shown correctly. I hope it is clear to you.

Please investigate and fix.

Good luck.

see screenshots
![screenshot_edit_order_no tax](https://cloud.githubusercontent.com/assets/10272269/23504687/ebf85fb6-ff40-11e6-8d47-0395b2492935.png)

![screenshot_label_on_invoice_correct](https://cloud.githubusercontent.com/assets/10272269/23504706/f9bbfea0-ff40-11e6-9376-2b8cc956d5d1.png)
![screenshot_from_taxamo_account_correct_vat](https://cloud.githubusercontent.com/assets/10272269/23504756/27993ed2-ff41-11e6-920e-9493c59ce79d.png)

**Comment by mikejolley** [comment]
This isn't core, but I'll let the extension devs know so it can be looked into. 

cc @roykho @gedex @bor0

**Comment by AdriOosterwijk** [comment]
Great, thanks
