### ISSUE TITLE
adding meta to a line item using API doesn't work

### ISSUE THREAD

**Issue by michael-lynch** [woocommerce/woocommerce#13422]
## EXPLANATION OF THE ISSUE

Using the API in 2.6, I tried to add some meta values to a line item when I created an order, but I was told the current v1 of the API doesn't support this, but that 2.7 would.

[#13108](https://github.com/woocommerce/woocommerce/issues/13108)

I installed the 2.7 RC this morning and I tried adding some meta values to a line item but I can't get it to work. Either I'm missing something or this is a bug.

## STEPS TO REPRODUCE THE ISSUE

Try adding meta fields to a line item when creating an order:

```
$woocommerce->post('orders', [
    'status' => 'pending',
    'line_items' => [
        'product_id' => $productID,
	'quantity' => 1,
	'meta' => [
            [
	        'label' => 'Color',
                'key' => 'color',
	        'value' => 'Blue'
	    ]
        ]
    ]
]);
```

The product will be added to the order, but without the `meta`.

**Comment by claudiulodro** [comment]
You'd want to use `meta_data` instead of `meta` and provide `key`, `value` and an optional `id`. [Here's the schema.](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-orders-controller.php#L1126)

**Comment by michael-lynch** [comment]
I tried that, but that didn't work.

```
$woocommerce->post('orders', [
    'status' => 'pending',
    'line_items' => [
        'product_id' => $productID,
	'quantity' => 1,
	'meta_data' => [
            [
                'key' => 'color',
	        'value' => 'Blue'
	    ]
        ]
    ]
]);
```

**Comment by mikejolley** [comment]
It's meta_data and only available on rest api v2. Docs will be up next week.

https://github.com/woocommerce/woocommerce/blob/e8d5da5c05cbcd2d0b33100542ebf818e93033e5/includes/api/class-wc-rest-orders-controller.php#L1126-L1151

Confirmed working:

![2017-03-02 at 14 17](https://cloud.githubusercontent.com/assets/90977/23510861/161f0904-ff53-11e6-8a0e-f95b4557cb4f.png)

**Comment by mikejolley** [comment]
I think I've already said before, attributes do not associate with line items. When you have line items, you have meta. My screenshot above shows meta data working in 2.7.

**Comment by michael-lynch** [comment]
If attributes aren't `meta`, how do you add them to an order if they aren't used as a variation?

I have a product with three attributes (style, color, fabric), none of which change the price, so I don't have any variations. Would I not use `meta` to add them to the line item?

**Comment by mikejolley** [comment]
If you're creating the order no, you'd specify the relevant variation ID and include meta if needed for future reference.

**Comment by michael-lynch** [comment]
I don't have any variations. I have a Simple product with three attributes. None of them change the price.

**Comment by mikejolley** [comment]
Simple products don't work in that way outside of the API, but like I said, you can add any meta to a line item using keys and values. Not sure what's not clear.

**Comment by michael-lynch** [comment]
I know this issue is closed, but I just want to provide some closure in case anyone else reads this. In regards to product attributes and meta, I was completely confused.

Seeing as product attributes are returned as `meta` when you `get` the order, I assumed they were `meta` when you `post` an order, but I now realize that **you need to use variations for any and all options, even if the attributes don't change the price of the product**, which means there is no need to `post` attributes at all.

I have refactored my code to only `post` variations and everything is working now. Sorry for the confusion.

```
$woocommerce->post('orders', [
    'status' => 'pending',
    'line_items' => [
        'product_id' => $productID,
	'quantity' => 1,
	'variation_id' => $variationID
    ]
]);
```
