### ISSUE TITLE
[2.7] Return value of WC_Data::get_meta() with single parameter set to false 

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#13427]
The 2nd parameter for `WC_Data::get_meta()` is a boolean flag for `$single`.

When set to `false`:

1. when there is meta data matching the the `$key` parameter, and _array_ is returned
2. when there is _no_ meta data matching the the `$key` parameter, an empty string is returned - `''`

For the 2nd case, an empty array would make the return value more consistent. It would also:

1. make it possible to use the return value directly in `foreach` statements without having to first check if it's not an array.
1. match the default return value of [`get_post_meta()`](https://developer.wordpress.org/reference/functions/get_post_meta/) when `$single` is set to `false`

In addition to inconsistent return values, I'm also not sure if the return value for the 1st case is the intended value. The `$single` parameter to me appeared to be based on the parameter of the same name for [`get_post_meta()`](https://developer.wordpress.org/reference/functions/get_post_meta/), making me think it would return a similar value to `get_post_meta()` - an array of values. However, it returns an array of `stdClass` objects objects with id, key & value properties. That's certainly more useful. I just wanted to point it out in case it's unintended. AFAICS, the `$single` flag is never set to `false` in WC core.

**Comment by mikejolley** [comment]
I believe `$single` determines if we return a single item of meta, or multiple if they happen to have the same $keys. stdClass is correct to represent our meta data so we can support the above.

I agree with the return type issue.

@claudiulodro want to give this a shot? Could do with unit tests.
