### ISSUE TITLE
`woocommerce_loaded` action can fire before extension plugins load

### ISSUE THREAD

**Issue by webaware** [woocommerce/woocommerce#13426]
`woocommerce_loaded` action is fired once the `WooCommerce` object is created and initialised. This happens as soon as the plugin loader file is executed, which means that it can happen before some extension plugins have hooked this action.

This is true at least as far back as WooCommerce version 2.0, and up to version 2.7RC1.

Recommendation: this action should not be fired before the `plugins_loaded` action.

**Comment by DavidAnderson684** [comment]
If you want plugins_loaded, then use plugins_loaded. Otherwise, there's https://codex.wordpress.org/Function_Reference/did_action

**Comment by mikejolley** [comment]
^ agreed. Moving the filter now would be a breaking change. Using `plugins_loaded` makes way more sense.

**Comment by webaware** [comment]
I think perhaps you misunderstand me. Actually, I am using `plugins_loaded` myself... and am unaffected by `woocommerce_loaded` firing before some plugins load anyway, because my plugins have names that mean that they load before WooCommerce does.

@mikejolley my point is that `woocommerce_loaded` is not guaranteed to fire for all WooCommerce extensions, because it fires as soon as WooCommerce loads and before some other plugins load. Currently (WordPress v4.7.2) WordPress sorts the active plugins list, and loads active plugins in order, so any plugins that sort after WooCommerce can never catch that hook when it fires.

Here's some example (totally made up) names for extensions that will never catch that hook:

* woocommerceexample (but woocommerce-example will catch the hook)
* wyalla-surf-shop
* xavier-college-website
* yams-for-woocommerce
* zebra-discounts

Here's a sample plugin that exhibits the problem:

https://gist.github.com/webaware/7d04f336633a3d150ded8501c2a32b4e

At minimum, it needs to be documented that `woocommerce_loaded` isn't reliable and what the known restrictions are. e.g. a comment above the `do_action()` call where developers might see it.

Better would be to execute the hook after `plugins_loaded` so that it's reliable. Maybe in v2.8?

**Comment by mikejolley** [comment]
I know it may execute early, but thats why you should use `plugins_loaded`. It might make sense to remove it in the future, but for bw compat it needs to stick around and not move.

**Comment by webaware** [comment]
So you'll be documenting that?

**Comment by mikejolley** [comment]
It's not new so I don't think so. We haven't documented it saying it's ok to use either, and if you find it in the codebase it's clear where/when it's triggered.

**Comment by helgatheviking** [comment]
Related: https://github.com/woocommerce/woocommerce/pull/22536
