### ISSUE TITLE
List all taxes

### ISSUE THREAD

**Issue by ced600f** [woocommerce/woocommerce#13428]
Hello

I'm trying to get the list of all taxes via the rest API. I'm using the WooCommerce-REST-API-Client-Library to connect to webservices with php.
It works well for products, orders, coupons... but not for taxes.
I got an error: No route matching the requested URL [woocommerce_api_no_route] 404 for the url:

http://wootest.tiaris.info/wc-api/v2/taxes?oauth_consumer_key=ck_299dc2dd4f2838c681f470610a19589d15599c79&oauth_timestamp=1488448426&oauth_nonce=e46ecc0f66ecdcaa3916ca927517e51317f227c0&oauth_signature_method=HMAC-SHA256&oauth_signature=4qijRCe5gXjnM7CxI7W%2Fbw85say1x4wi71MZobGAxCg%3D

When I change taxes with products and relaunch the request, it works...

Any idea ?

Wordpress 4.7.2
Woocommerce 2.6.14
php 5.4.41

When you ask for http://wootest.tiaris.info/wc-api/v2/, you get exposed functions but I can't find taxes method...

{"store":{"name":"Wootest","description":"Un site utilisant WordPress","URL":"http:\/\/wootest.tiaris.info","wc_version":"2.6.14","routes":{"\/":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/"}},"\/customers":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/customers"},"accepts_data":true},"\/customers\/count":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/customers\/count"}},"\/customers\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/customers\/email\/<email>":{"supports":["HEAD","GET"]},"\/customers\/<id>\/orders":{"supports":["HEAD","GET"]},"\/customers\/<id>\/downloads":{"supports":["HEAD","GET"]},"\/customers\/bulk":{"accepts_data":true,"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/customers\/bulk"},"supports":["POST","PUT","PATCH"]},"\/orders":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/orders"},"accepts_data":true},"\/orders\/count":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/orders\/count"}},"\/orders\/statuses":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/orders\/statuses"}},"\/orders\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/orders\/<order_id>\/notes":{"supports":["HEAD","GET","POST"],"accepts_data":true},"\/orders\/<order_id>\/notes\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/orders\/<order_id>\/refunds":{"supports":["HEAD","GET","POST"],"accepts_data":true},"\/orders\/<order_id>\/refunds\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/orders\/bulk":{"accepts_data":true,"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/orders\/bulk"},"supports":["POST","PUT","PATCH"]},"\/products":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/products"},"accepts_data":true},"\/products\/count":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/products\/count"}},"\/products\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/products\/<id>\/reviews":{"supports":["HEAD","GET"]},"\/products\/<id>\/orders":{"supports":["HEAD","GET"]},"\/products\/categories":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/products\/categories"}},"\/products\/categories\/<id>":{"supports":["HEAD","GET"]},"\/products\/attributes":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/products\/attributes"},"accepts_data":true},"\/products\/attributes\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/products\/sku\/<sku>":{"supports":["HEAD","GET"]},"\/products\/bulk":{"accepts_data":true,"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/products\/bulk"},"supports":["POST","PUT","PATCH"]},"\/coupons":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/coupons"},"accepts_data":true},"\/coupons\/count":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/coupons\/count"}},"\/coupons\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/coupons\/code\/<code>":{"supports":["HEAD","GET"]},"\/coupons\/bulk":{"accepts_data":true,"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/coupons\/bulk"},"supports":["POST","PUT","PATCH"]},"\/reports":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/reports"}},"\/reports\/sales":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/reports\/sales"}},"\/reports\/sales\/top_sellers":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/reports\/sales\/top_sellers"}},"\/webhooks":{"supports":["HEAD","GET","POST"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/webhooks"},"accepts_data":true},"\/webhooks\/count":{"supports":["HEAD","GET"],"meta":{"self":"http:\/\/wootest.tiaris.info\/wc-api\/v2\/webhooks\/count"}},"\/webhooks\/<id>":{"supports":["HEAD","GET","POST","PUT","PATCH","DELETE"],"accepts_data":true},"\/webhooks\/<webhook_id>\/deliveries":{"supports":["HEAD","GET"]},"\/webhooks\/<webhook_id>\/deliveries\/<id>":{"supports":["HEAD","GET"]}},"meta":{"timezone":"Europe\/Paris","currency":"EUR","currency_format":"&euro;","currency_position":"right","thousand_separator":"","decimal_separator":",","price_num_decimals":2,"tax_included":false,"weight_unit":"kg","dimension_unit":"cm","ssl_enabled":false,"permalinks_enabled":true,"generate_password":false,"links":{"help":"https:\/\/woothemes.github.io\/woocommerce-rest-api-docs\/"}}}}

Regards

Cedric Scheyder

**Comment by mikejolley** [comment]
You're using an old version of the API which doesn't list taxes https://woocommerce.github.io/woocommerce-rest-api-docs/v2.html#index-properties
