### ISSUE TITLE
[2.7.0 RC 1] Can't change upsells `posts_per_page`

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce#13436]
## EXPLANATION OF THE ISSUE

In WC 2.7.0 RC1 hooking onto `woocommerce_upsell_display_args` doesn't seem to change anything.

## STEPS TO REPRODUCE THE ISSUE

I've tried to reduce the number of displayed products in upsells to 3 with this code:

```
function upsells_args( $args ) {
  $args['posts_per_page'] = 3;
  return $args;
}
add_filter( 'woocommerce_upsell_display_args', 'upsells_args' );
```

With WC 2.6.x everything works as it should. Also, when passing the above function into `woocommerce_output_related_products_args` filter for related posts, those are working fine. **It only affects upsells.**

## MY SETUP

* **WordPress**: 4.7.2
* **Theme**: TwentySeventeen
* **WooCommerce**: 2.7.0 RC1

**Comment by mikejolley** [comment]
These no longer do a full wasteful WP query so that will no longer be honoured.

**Comment by webmandesign** [comment]
So, there is nothing I can do about that? I can't display just 3 upsell items since WC2.7?

**Comment by mikejolley** [comment]
^ there is a filter, and I put in another PR to keep it working with the old filter.

**Comment by webmandesign** [comment]
OK, now it works, thanks.

However, this rises a few questions:

1. Does this mean the legacy `woocommerce_upsell_display_args` filter will be removed in the future in favor of `woocommerce_upsells_columns`, `woocommerce_upsells_orderby` and `woocommerce_upsells_total`?
2. What about `woocommerce_output_related_products_args` filter then? Will it follow the example of `woocommerce_upsell_display_args` becoming legacy to keep the approach consistent?

**Comment by mikejolley** [comment]
Uncertain right now; the change was made to avoid a WP Query. Look at the code in question to understand the change.

**Comment by Uriel1339** [comment]
add_filter( 'woocommerce_upsells_total', 'jn_upsell_display', 10, 1 );		
function jn_upsell_display( $args ) {
	$limit = '12';
}

We struggled so much with hardcoding the template file I finally had enough and dove into the hook documentation. I found this in the reference:

woocommerce_upsells_total | filter | wc-template-functions.php
