### ISSUE TITLE
[2.7 RC1] meta data not reloaded after $order->save_meta_data

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#13439]
When loading an order for a second time (in a separate process), meta data saved earlier via `$order->save_meta_data` doesn't seem to be loaded.

Simple test:
``` php
$order = wc_get_order( 133 );
$order->update_meta_data( 'test', '123' );
$order->save_meta_data();
printf( "from the original object:<br>%s<br><br>", var_export( $order->get_meta( 'test', true, 'edit' ), true ) ); // outputs '123'
$order = wc_get_order( 133 );
printf( "from a new object:<br>%s<br><br>", var_export( $order->get_meta( 'test', true, 'edit' ), true ) ); // outputs ''
```

When I add `$order->save()` before the second `wc_get_order()` call, the meta data is properly loaded from the new object too. I was under the impression that this would not be necessary when `save_meta_data()` is run, especially considering that when I do this a in a second run, the meta is available.
Moreover, if for example the meta is an array and I add an element to this array, not only is the meta not updated, it returns empty rather than the old value.

Seems to be a caching issue...

The test above is greatly simplified, but in my process I can't pass the `$order` object.

**Comment by mikejolley** [comment]
Why would you call that vs ->save()?

**Comment by Spreeuw** [comment]
Good one :)
I assumed `save_meta_data()` would be lighter and more appropriate if only meta data is added.

To give a bit more background here: I need to be backwards compatible so I implemented a wrapper similar to what SkyVerge / @ChaseWiseman  do in their [plugin framework](https://github.com/skyverge/wc-plugin-framework/blob/0561fe4b1eeaa2c96f71274b40a89a43f12f1879/woocommerce/compatibility/abstract-sv-wc-data-compatibility.php#L171-L185).

**Comment by mikejolley** [comment]
I think `save_meta_data` is only public out of necessity for data stores. It would probably be possible to add cache flushing, but really, `->save()` should always be used.

**Comment by Spreeuw** [comment]
Is there any difference performance wise? With backwards compatibility in mind it's much more difficult to do the `save()` at the end of a process rather than per meta, so I'd like to keep the action as light as possible. @ChaseWiseman any ideas?
