### ISSUE TITLE
[2.7 RC1] Different behaviour for "Ship to a different address?" on 2 installs

### ISSUE THREAD

**Issue by vishalck** [woocommerce/woocommerce#13430]
## EXPLANATION OF THE ISSUE

I setup 2.7.0 RC-1 on two local installations. I removed the current 'woocommerce' folder in plugins & replaced that with the new one. I have run the DB updater as well on both.

On both installs, I created a Simple product. After adding that product to cart, when I go to checkout page, the below is seen:

On Local Install 1, I see the option of "Ship to a different address?" - https://screencast.com/t/muVdguPy . 

This is the "Your Order" table: https://screencast.com/t/o15HuEqiJzxA 

On Local Install 2, I don't see the option of "Ship to a different address?" - https://screencast.com/t/9bIQI8Ykkfa . Instead, it directly shows me the "Order Notes" field. 

This is the "Your Order" table: https://screencast.com/t/MXOYnEElL0S8 .

## STEPS TO REPRODUCE THE ISSUE

Here are the Shipping Settings for Local Install 1: 

Settings -> General: https://screencast.com/t/EL8XVTptDE
Settings -> Shipping -> Shipping zones: https://screencast.com/t/54hE7QBqdO
Settings -> Shipping -> Shipping options: https://screencast.com/t/UJpFz98uzc

Here are the Shipping Settings for Local Install 2: 

Settings -> General: https://screencast.com/t/xcgnVYUUV
Settings -> Shipping -> Shipping zones: https://screencast.com/t/EDxG37rTR
Settings -> Shipping -> Shipping options: https://screencast.com/t/Jh4dA1Hy6Id

Am I missing something here? It should be showing the same behaviour for both installs. In 2.6.14, I am seeing the behaviour as replicated in Local Install 1.

## SYSTEM STATUS REPORT FOR LOCAL INSTALL 1
`
### WordPress Environment ###

Home URL: http://localhost:8888/bookings
Site URL: http://localhost:8888/bookings
WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version: 5.6.10
PHP Post Max Size: 500 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/0.9.8zd

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.42 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 35: Unsupported SSL protocol version
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. 200

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 2.7.0-RC1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.2 – 1.3 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

## SYSTEM STATUS REPORT FOR LOCAL INSTALL 2
`
### WordPress Environment ###

Home URL: http://localhost:8888/woocommerce
Site URL: http://localhost:8888/woocommerce
WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version: 5.6.10
PHP Post Max Size: 500 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/0.9.8zd

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.42 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 35: Unsupported SSL protocol version
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. 200

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Overwrite Product Review Comment form: by Vishal Kothari – 1.0
WooCommerce: by Automattic – 2.7.0-RC1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.2 – 1.3 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
If there are no shipping methods defined, it just disables shipping because the store owner has not set it up. This is intentional.

**Comment by vishalck** [comment]
I understand. How / Why would it display different behaviours on 2 different installs? In both cases above, Shipping is not set. In one case, it will allow the order to go through. Whereas in another case, it will not allow the order to be placed.

**Comment by mikejolley** [comment]
It may have a shipping method, or legacy shipping method. The installs are clearly not identical.
