### ISSUE TITLE
Max width of .woocommerce-message p

### ISSUE THREAD

**Issue by Dartui** [woocommerce/woocommerce#13431]
## EXPLANATION OF THE ISSUE
Version: WC 2.7-RC1

[This commit](https://github.com/woocommerce/woocommerce/commit/c0ec85cd847fc2cc28c65912b07a0459edbdb14d#diff-1ed79a3ac728be07384db8f781413ac7R18)  added max width to `p` in `.woocommerce-message`. For now all messages in admin screen are stretched to 700px width and looks like this on larger screen: 
![Preview](http://screenshot.sh/p/screen/102674758/fafrpjrhl)

**Comment by mikejolley** [comment]
I believe it's intended; extra long lines of text are not easy to read.
