### ISSUE TITLE
Use is_numeric on sanitize_term_ids()

### ISSUE THREAD

**Issue by spencerfinnell** [woocommerce/woocommerce#13446]
## EXPLANATION OF THE ISSUE

`wp_insert_term()` will return an array of `term_id` and `term_taxonomy_id` as a string instead of an int (though `term_exists()` returns properly cast ints), which will cause unexpected behavior via `sanitize_term_ids()` when creating a term on the fly and assigning to a product.

## STEPS TO REPRODUCE THE ISSUE

```
$term = wp_insert_term( 'Test', 'product_cat' );

$product = wc_get_product();
$product->set_props( array(
  'category_ids' => $term[ 'term_id' ]
) );
$product->save();

**Comment by spencerfinnell** [comment]
This can be avoided by using `absint()` before setting the prop but could definitely trip people up who do not know the inconsistency between `wp_insert_term()` and `term_exists()` returns.

**Comment by claudiosanches** [comment]
This is not correct, since expects an array and not just and integer or string.

```
'category_ids' => $term[ 'term_id' ]
```

**Comment by spencerfinnell** [comment]
You're right, my sample code is incorrect but the idea still applies.

```
$product->set_props( array(
  'category_ids' => array( "22" )
) );
```

Will look for a term by the name of 22 instead of using it as the ID.

https://github.com/woocommerce/woocommerce/blob/542fea3d85eed231dde91ecf9233fe149537a135/includes/abstracts/abstract-wc-product.php#L1268

`term_exists()` returns a value cast as a string not an integer. There might not be a right answer though, because obviously a category can have a numeric name as well.

Might be something to take in Core.

**Comment by claudiosanches** [comment]
@spencerfinnell still this is not solved by my Pull Request, since now:

```
$ wp shell
wp> is_integer( "22" )
=> bool(false)
```

**Comment by spencerfinnell** [comment]
To me the most common scenario will be:

```
$term = term_exists( 'some_term', 'product_cat' );

if ( ! is_array( $term ) ) {
  $term = wp_insert_term( 'some_term', 'product_cat );
}

// set prop
```

If the term *does not previously exist* then everything is fine because `wp_insert_term()` will return 

```
array(2) {
  'term_id' =>
  int(218)
  'term_taxonomy_id' =>
  int(218)
}
```

and `is_integer` will catch it.

If the term *does previously exist* then the following is returned:

```
array(2) {
  'term_id' =>
  string(3) "218"
  'term_taxonomy_id' =>
  string(3) "218"
}
```

and sanitization will "fail" because it will default to looking up a term with a name of `218` (since it's a string). This will not find any terms and `category_ids` will not be updated with any terms.

So it needs to be decided if any array value passed as a *number* is expected to be the term ID or if it can be the name as well.

**Comment by mikejolley** [comment]
Is this logged on WP trac?

**Comment by spencerfinnell** [comment]
https://core.trac.wordpress.org/ticket/16101

**Comment by spencerfinnell** [comment]
Another angle would be to be less lenient on the sanitization. The props are pretty explicit with `*_ids` so it's pretty fair to assume you should be passing the actual IDs of the terms and nothing else.

**Comment by mikejolley** [comment]
6 years :D 

Yeah setting as ids is an option since it matches naming and I think core usage. @claudiosanches 

Maybe that handling is legacy?

**Comment by claudiosanches** [comment]
@mikejolley it's a new method and I agree, should accept only IDs.
