### ISSUE TITLE
[2.7 RC 1] Twenty Seventeen styles

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#13441]
## EXPLANATION OF THE ISSUE

There are no buttons in the Twenty Seventeen styles. I wasn't sure if this was intentional, so I am reporting it. `woocommerce.css` is removed in favor of `twentyseventeen.css` which doesn't seem to have any rules for `.woocommerce #respond input#submit, .woocommerce a.button, .woocommerce button.button, .woocommerce input.button`. 

![image](https://cloud.githubusercontent.com/assets/507025/23513906/46d3fa46-ff2b-11e6-89af-fd6093b49c3b.png)

and the mini-cart: 
![image](https://cloud.githubusercontent.com/assets/507025/23513871/2e52009e-ff2b-11e6-8434-daf86df46e13.png)

## STEPS TO REPRODUCE THE ISSUE

Enable Twenty Seventeen theme

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: https://wc27-helgatheviking.c9users.io
Site URL: https://wc27-helgatheviking.c9users.io
WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.9 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.43 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Plugin Toggle: by Cedaro – 1.3.1
Postman SMTP: by Jason Hendriks – 1.7.2
Workshop Attendee Details: by Kathy Darling – 0.1.0
WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0
WooCommerce Free Gift Coupons: by Kathy Darling – 1.2.0
WooCommerce Stripe Gateway: by WooCommerce – 3.0.7
WooCommerce Mix and Match: by WooThemes – 1.2.0
WooCommerce: by Automattic – 2.7.0-RC1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### WC Pages ###

Shop base: #103 - /shop/
Cart: #104 - /cart/
Checkout: #105 - /checkout/
My account: #106 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by mikejolley** [comment]
Same in 2.6.x - this is (afaik) an intentional design decision. @jameskoster can confirm but this is not new in 2.7.

**Comment by jameskoster** [comment]
Twenty Seventeen doesn't provide button styles iirc. I spoke with Mel (2017 designer) about the WC integration and we're both happy with this direction.

**Comment by helgatheviking** [comment]
@jameskoster Thanks for the reply, but it seems that Twenty Seventeen *does* have [button styles](https://github.com/WordPress/twentyseventeen/blob/master/style.css#L985-L1005) for:

```
button,
input[type="button"],
input[type="submit"]
```

But not the WC class `<a class="button">button link</a>` that has been used for buttons on the archive pages for a long time.  There are buttons in the cart, checkout, and single product pages pages, so their *absence* on the archive page is very noticeable to me. 

WC 2.6.14 cart
![image](https://cloud.githubusercontent.com/assets/507025/23551383/ea17a9e0-ffdb-11e6-8e8c-9e659497cfe0.png)

WC 2.7 RC1 cart
![image](https://cloud.githubusercontent.com/assets/507025/23551343/a7d839be-ffdb-11e6-8d45-2d72dd5047f2.png)

**Comment by jameskoster** [comment]
Oh yeah, that was it. I remember. Sorry for the confusion.

We still decided to go with the text links for product archives as we felt they were more stylistically consistent with the rest of the theme.
