### ISSUE TITLE
WC 2.7 API - Refunded Item Id

### ISSUE THREAD

**Issue by luiscoutinh** [woocommerce/woocommerce#13447]
Hi,

The refunded_item_id was forgotten in the refunds and without this info is impossible associate a refund to an order line. (We can validate the product_id and varation_id, however if we have more than one line with the same product...)

So, the request is to add the refunded_item_id to the refunds as soon as possiblem, because it's essential.

Thanks.

**Comment by mikejolley** [comment]
In 2.7+ and the v2 API, this will be returned as part of the `meta_data` since it's not in the schema itself.
