### ISSUE TITLE
Feature Request - Please apply the woocommerce_order_item_name filter to the Admin Order or maybe a new woocommerce_admin_order_item_name filter

### ISSUE THREAD

**Issue by garrett-eclipse** [woocommerce/woocommerce#13467]
## EXPLANATION OF THE ISSUE

I tied into the woocommerce_order_item_name filter to add course dates onto my course products which worked great for the customers View Order and Order Email views. However when I went into the Admin view of the order I realized this filter wasn't applied.
Diving into the code I found the Admin Order items view is controlled by woocommerce/includes/admin/meta-boxes/views/html-order-item.php

It would be nice if the woocommerce_order_item filters are applied to the admin order items. Or a new woocommerce_admin_order_item set of filters is implemented so that the same type of filters can be applied to admin as customer views.

So for the following existing code found on line 26 of html-order-item.php
`echo $product_link ? '<a href="' . esc_url( $product_link ) . '" class="wc-order-item-name">' .  esc_html( $item['name'] ) . '</a>' : '<div class="class="wc-order-item-name"">' . esc_html( $item['name'] ) . '</div>';`

Would become something like;
echo apply_filters( 'woocommerce_admin_order_item_name', $product_link ? sprintf( '<a href="%s">%s</a>', $product_link, $item['name'] ) : $item['name'], $item, $is_visible );
*DON"T USE THIS THOUGH it's an example and doesn't take into acconut when product_link is empty as it should switch to use the div (<div class="class="wc-order-item-name"">) rather than link.

## STEPS TO REPRODUCE THE ISSUE

1. Create a filter function for woocommerce_order_item_name
2. As a Customer make an order and note the change of item_name that your filter makes on the Order Email and View Order.
3. Login as Admin to view Customers Order and see the same item_name update applied to the customer views isn't applied to the Admin view.

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: https://missa.ca
Site URL: https://missa.ca
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_CA

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.29.0
NSS/3.21.3 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (41) ###

Advanced Custom Fields: Restrict Color Picker Options: by Vital – 1.1
Advanced Custom Fields: User Role Selector: by Daniel Pataki – 3.0.2
Admin Actions: by Eclipse Creative – 1.0.0
Advanced Custom Fields PRO: by Elliot Condon – 5.5.9
Bootstrap Shortcodes: by Kevin Attfield – 3.4.0
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.38
Contact Form 7 - Success Page Redirects: by Ryan Nevius – 1.2.0
Contact Form DB: by Michael Simpson – 2.10.28
Contact Form 7: by Takayuki Miyoshi – 4.7
Disable Comments: by Samir Shah – 1.6
Easy FancyBox: by RavanH – 1.5.8.2
Featured Image Admin Thumb: by Sean Hayes – 1.4.1
Font Awesome 4 Menus: by New Nine Media – 4.7.0
Maps Builder: by WordImpress – 2.1.1
Groups 404 Redirect: by itthinx – 1.2.4
Groups WooCommerce: by itthinx – 1.10.0
Groups: by itthinx – 2.0.2
Hide Related Products in WooCommerce: by Basit Ansari – 1.0
TinyMCE Color Grid: by Anagarika Daniel – 1.7.2
MailChimp for WordPress: by ibericode – 4.0.13
Manage Notification E-mails: by Virgial Berveling – 1.3.0
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Relevanssi: by Mikko Saari – 3.5.8
Responsive Menu: by Peter Featherstone – 3.0.18
Title Toggle for Storefront Theme: by Wooassist – 1.2.2
TinyMCE Advanced: by Andrew Ozz – 4.4.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 2.12.34.22

User Switching: by John Blackbourn – 1.0.9
WooCommerce Checkout Add-Ons: by WooThemes / SkyVerge – 1.9.1
WooCommerce Checkout Manager: by Visser Labs – 4.1
WooCommerce Customizer: by SkyVerge – 2.3.1
WooCommerce Direct Checkout: by Terry Tsang – 1.1.2
WooCommerce MailChimp: by Saint Systems – 2.0.20
WooCommerce My Account Widget: by Bart Pluijms – 0.5.0
WooCommerce One Page Checkout: by Prospress Inc. – 1.3.2
WooCommerce Subscriptions: by Prospress Inc. – 2.1.3
WooCommerce TM Extra Product Options: by themecomplete – 4.4.1.1
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
Wordpress Countdown Timer: by Jordan Calder – 100.0.0
WP Migrate DB Pro: by Delicious Brains – 1.7.1

### Settings ###

Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #354 - /shop/
Cart: #355 - /cart/
Checkout: #356 - /checkout/
My Account: #357 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: MISSA 2017
Version: 1.01
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.6 – 2.1.8 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: storefront-child/woocommerce/archive-product.php
storefront-child/woocommerce/checkout/form-billing.php
storefront-child/woocommerce/checkout/form-checkout.php
storefront-child/woocommerce/content-product.php
storefront-child/woocommerce/content-single-product.php
storefront-child/woocommerce/global/form-login.php
storefront-child/woocommerce/loop/price.php
storefront-child/woocommerce/single-product/add-to-cart/variable.php
storefront-child/woocommerce/single-product/product-image.php
storefront-child/woocommerce/single-product/product-thumbnails.php
storefront-child/woocommerce/single-product/tabs/tabs.php

`

**Comment by mikejolley** [comment]
2.7 CRUD classes have filters on all return values (in view context) so these can be used. `woocommerce_order_item_name` should work with that update.

**Comment by garrett-eclipse** [comment]
Thanks @mikejolley I'll check it out once 2.7 has been released. Cheers
