### ISSUE TITLE
Product -> Get Children doesn't return all variations

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#13469]
## EXPLANATION OF THE ISSUE

When attempting to get all variations for a given product, you have no way to get all variations at a given time, as only those in stock will ever be returned.

`$product->get_children()` will eventually lead you here:
https://github.com/woocommerce/woocommerce/blob/7ab0b99afef6dc0e886613a766b84080a80c25e8/includes/data-stores/class-wc-product-variable-data-store-cpt.php#L49-L56

(This is functionally similar to previous versions.)

Notice the post status is set to `publish`, which means that any out of stock variations are not included, as they have a post status set to `private`: 
https://github.com/woocommerce/woocommerce/blob/7ab0b99afef6dc0e886613a766b84080a80c25e8/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L342

While this would be expected with `$product->get_available_variations()`, I don't think a developer new to WooCommerce would expect `$product->get_children()` to return a filtered list of the child variations (I definitely didn't for the plugin I'm updating), especially when the param is set to "all".

This means the only way I see to get all variations is to manually to a `get_posts()` query, setting post status to `'any'` or `array( 'publish', 'private' )`.

Since this was the previous behavior for at least the past few WC versions, I wasn't sure if changing the behavior of the "all" flag for getting children was desired. 

Personally, I think "all" should get published and private variations, then the `$visible_only_args` should include "publish" as the post status instead if the query is only looking for visible products. However, not sure if another flag or helper instead would be preferable.

Happy to submit a PR if y'all are okay with changing the "all" query to include 'private' posts as well.

**Comment by mikejolley** [comment]
Not quite.

> Notice the post status is set to publish, which means that any out of stock variations are not included, as they have a post status set to private

These are not out of stock variations. These are variations where the user has intentionally turned off the 'enabled' checkbox here: 

![2017-03-06 at 15 00](https://cloud.githubusercontent.com/assets/90977/23615230/9d52ce4c-027d-11e7-8d49-0e47f5cfb732.png)

Many parts of core expect these to be ignored e.g. when setting stock statuses. So for now this should not change and should match 2.6.x

We should definitely revisit during #13086 because I'd personally like to do away with that option entirely.
