### ISSUE TITLE
woocommerce_get_settings_shipping is not called on custom setting sections

### ISSUE THREAD

**Issue by ThisIsHughYoung** [woocommerce/woocommerce#13461]
Hi there, new to PHP/Wordpress/WooCommerce development, please go easy on me. I tried to research this to the best of my ability. If this is a wontfix hopefully someone who runs into my issue in the future will see it and not waste as many hours as I did trying to figure this out. :)

## EXPLANATION OF THE ISSUE

I'm trying to write a new section into the Shipping tab of my WooCommerce admin page. However, while I can create the section itself, I cannot populate it with form data. My filter hook is never called.

The problem is WC_Settings_Shipping::output() - The else block (lines 149-152 of class-wc-settings-shipping.php) contains a foreach loop that checks if $current_section is in the list of shipping methods **but doesn't have a catch-all clause when it's not found.**

Because of this, **woocommerce_get_settings_shipping does not run for custom setting sections**. The filter only gets called in section 'options'. It also means that the filter's $current_section parameter is omitted, leading to an API inconsistency.

**EDIT:** For now, current plugin writers could write their settings into the options tab but I don't think this is ideal. As a newcomer this was very confusing to me. **/EDIT**

Proper behaviour would something like the following: 

```
....
} else {
  $is_shipping_method = false;
  foreach (.... ...) { ... 
    if ( section is shipping method) {
      $is_shipping_method = true
      WC_Shipping_Method_x::admin_options();
    }
  }

  // Adding these lines below would solve the bulk of this issue
  if (!$is_shipping_mehod) {
    $settings = apply_filters( 'woocommerce_get_settings_' . $this->id, '' );
    WC_Admin_Settings::output_fields( $settings );
  }
}

//EDIT: WC_Settings_Shipping::save() needs a similar fix too 
```

**Caveats:**

- Is access shipping methods by the section GET parameter done for plugin compatibility? Is there a risk of a shipping method name colliding with a section name?

- I suspect the missing $current_section parameter on woocommerce_get_settings_shipping can't be fixed since that would break existing plugins, correct? If so, plugins would probably have to resort to global $current_section to filter out their option pages correctly. (not ideal)

## STEPS TO REPRODUCE THE ISSUE

add_filter( 'woocommerce_get_sections_shipping', ... );
add_filter( 'woocommerce_get_settings_shipping', ... );

Filter is not run when using a custom section added by filter woocommerce_get_sections_shipping

### WordPress Environment ###

```
Home URL: 
Site URL: 
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.16-3+0~20170222101552.24+jessie~1.gbpb3eec3
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔
```

**Sorry for the many edits,** I realized I posted this before I fully understood the architecture but now I still think was worth the post

**Comment by ThisIsHughYoung** [comment]
#13463 

Once again this is my first time doing all of this. Let me know if I'm doing anything wrong / following proper etiquette. Thanks!

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/13463
