### ISSUE TITLE
Coupon not visually removed

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#13476]
## EXPLANATION OF THE ISSUE
A coupon exists which grants free shipping and is restricted to a particular email address. If a customer applies that code on the cart, it validates and applies as expected. Entering an email address on checkout that does not match the restriction results in "Sorry, it seems the coupon "some coupon code" is not yours - it has now been removed from your order. As expected, but, "Free shipping" is still selected. Coupon code is still displayed in the cart table.

## STEPS TO REPRODUCE THE ISSUE
1. Free shipping is enabled and requires a coupon
2. Coupon code exists which is restricted to a particular email address
3. Apply that coupon code while on the cart page
4. Proceed to checkout. Enter an email address that does not match the restriction for the above coupon code.
5. Place Order.
6. See something like:
![see screen shot](http://cld.wthms.co/7oP3/4fGegsf2+)

Pressing "Place Order" again will place the order defaulted to the next available shipping method.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://versiontesting.woo
Site URL: http://versiontesting.woo
WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: nginx/1.11.8
PHP Version: 7.0.14-2+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.53 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 2.7.0-RC1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by WPprodigy** [comment]
I can replicate on 2.7rc1. This doesn't seem to be doing what it's supposed to: https://github.com/woocommerce/woocommerce/blob/790dd57933ab74facd1dcfe5608e2cce159a28ea/includes/class-wc-cart.php#L1658

**Comment by WillBrubaker** [comment]
@claudiulodro Thanks for the fix, however, there is no visual notification concerning the invalidity of the coupon as there was previously.

**Comment by mikejolley** [comment]
@WillBrubaker yes there is... https://dl.dropboxusercontent.com/s/8y7tf04yk7qulif/2017-03-07%20at%2019.29.png I see the notice still.

**Comment by WillBrubaker** [comment]
Sure enough...not sure what happened in my earlier test :(

**Comment by WillBrubaker** [comment]
@mikejolley @claudiulodro - With Stripe enabled and selected as the payment method, no notice is given. Screencast http://cld.wthms.co/b4zh/4JsR3Pe9

**Comment by mikejolley** [comment]
@WillBrubaker I don't think this is 2.7 related at all - look here: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/assets/js/stripe.js#L115

**Comment by claudiulodro** [comment]
Yep. I commented out the error-message-removing from stripe.js and the error message hangs around. Good catch @mikejolley!

**Comment by WillBrubaker** [comment]
Got it...will open an issue on the Stripe repo. Thanks y'all.
