### ISSUE TITLE
Cash on delivery: How to select specific name of some delivery type

### ISSUE THREAD

**Issue by qaywsxedcrfvtgb** [woocommerce/woocommerce#13472]
I have multiple rows in one delivery zone, these rows are the same type (the type is: "Flat rate"), but they have different names.

So the question is: On page "cash on delivery" how can I select that specific name in the field for delivery option?

There is only "Free Shipping" and "Local delivery" and "Flat rate", but I would like to select specific name of option "Flat rate".

How can I do that?

**Comment by mikejolley** [comment]
Huh? You can give each flat rate a name - https://dl.dropboxusercontent.com/s/j31y4f7h6fjvy40/2017-03-06%20at%2011.30.png Just do this for all of them in the same zone and all names will be listed.

Please don't use our bug tracker for support questions in future.

**Comment by qaywsxedcrfvtgb** [comment]
Yes, I can give each flat rate a different name and I have that.
But if I have multiple different flat rates (different names of flat
rates), I would like to select only one of them in "Cash on delivery"
payment option.
http://imgur.com/rwC4Kcs
So I tought It is a bug because I can select only all of the Flat rates,
there is no option to select only specific name of flat rate.
Or is there some way to select only the specific name of flat rate?

2017-03-06 12:31 GMT+01:00 Mike Jolley <notifications@github.com>:

**Comment by mikejolley** [comment]
Does not seem possible - they are linked at method level, not instance level.
