### ISSUE TITLE
Checkout Internal Server Error

### ISSUE THREAD

**Issue by YasserHossam90** [woocommerce/woocommerce#13473]
Hello,
I'm new to WordPress and woocommerece, I've used theme called Massimos, And the checkout was working perfectly. But it is now not working I don't know why !

I've checked the "checkout?wc-ajax=checkout" and here is the result:
`{"result":"failure","messages":"<div class=\"alert alert-danger clearfix wow fadeInDown container\" data-wow-duration=\"400ms\">\r\n\t<div class=\"row\">\r\n\t\t\t<div class=\"woocommerce-notice col-xs-12\">We were unable to process your order, please try again.<\/div>\r\n\t\t<\/div>\r\n<\/div>","refresh":"true","reload":"false"}`

And I've checked the log file and there are no any log added to it !

Anyone faced the same issue?

**Comment by mikejolley** [comment]
Could be the gateway; you need to check the server error logs to find the real error message and act on it accordingly. 

You can also try another payment gateway/shipping method/both to see if those are breaking. But checking the logs is better.

I'm closing this as it does not sound like a core bug and there are no steps to reproduce on clean installs.
