### ISSUE TITLE
Create order endpoint

### ISSUE THREAD

**Issue by mathieug** [woocommerce/woocommerce#13482]
When I call the endpoint for creating an order, the order is well created but nothing happens with the stock quantity of the product.
Also, the user has a stripe token (https://woocommerce.com/products/stripe/), and same, nothing happens. Whatever the status I set in the creation, no payment happens.

**Comment by mikejolley** [comment]
The API creates orders but it does not take payments. Not many gateways support tokens right now. Could be interesting in the future, but right now it's not in scope and not mentioned in the docs either https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order

Stock will reduce when you call `set_paid`. See https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

**Comment by claudiosanches** [comment]
@mathieug you should process the payment in your app after create an order and after is paid you can update the order to paid on the REST API too.

**Comment by mathieug** [comment]
@mikejolley thanks, it works for the stock.

@claudiosanches How do I process the payment separately in my app? The card of the user is tokenized into a stripe token thru WooCommerce (and its Stripe plugin). I need to access to this token or to automatize the payment when an order is created in WooCommerce.

**Comment by claudiosanches** [comment]
@mathieug creating your own checkout flow, since there is no endpoint it for payment tokens.
