### ISSUE TITLE
Negative taxes in order fees not calculated properly

### ISSUE THREAD

**Issue by MChaban47** [woocommerce/woocommerce#13481]
## EXPLANATION OF THE ISSUE

When I add fee, using function $order->add_fee($fee), order totals not calculated properly, when I amount is negative and fee is taxable. I use "add_fee" to make a discount, so taxes should be discounted too. But they not.

## STEPS TO REPRODUCE THE ISSUE

In my project I used WooCommerce Subscription plugin, so I needed to make a taxable discount on renewal order. I use this code:
```
function _ca_wcs_new_order_created($new_order){
    $fee            = new stdClass();
    $fee->name      = 'Example Product Fee';
    $fee->tax_class = 'My tax';
    $fee->taxable   = $fee->tax_class !== '0';
    $fee->amount    = -10.0;
    $new_order->add_fee($fee);
    $new_order->calculate_shipping();
    $new_order->calculate_totals();
    return $new_order;
}
add_filter('wcs_new_order_created','_ca_wcs_new_order_created');
```

Also I found this in "abstract-wc-order.php" on 739-740 lines:
```
$line_subtotal_tax   = max( 0, array_sum( $line_subtotal_taxes ) );
$line_tax            = max( 0, array_sum( $line_taxes ) );
```
As you see, negative taxes will never be calculated right.
So, I changed it to:

```
$line_subtotal_tax   = array_sum( $line_subtotal_taxes );
$line_tax            = array_sum( $line_taxes );
```
and now everything works fine, so you can check and fix it too.

**Comment by mikejolley** [comment]
This will be fixed, but as we've stated in other issues, officially negative taxes are not supported and they will be prevented in future versions once a robust discount API is added.

**Comment by mikejolley** [comment]
This code no longer exists in 2.7 so looks to be a non-issue.
