### ISSUE TITLE
order total and taxes not updating when order is updated

### ISSUE THREAD

**Issue by michael-lynch** [woocommerce/woocommerce#13489]
## EXPLANATION OF THE ISSUE

I'm using the new 2.7 RC and API to create and update an order. When I create the order, the total is correct. However, when I update the order, the total and taxes stay the same - they aren't updated to reflect the new item, even though the line item was successfully added to the order.

## STEPS TO REPRODUCE THE ISSUE

Create an order:

```
$data = [
    'status' => 'pending',
    'customer_id' => $customerID,
    'line_items' => $lineItems
];

$woocommerce->post('orders', $data);
```

Then update it:

```
$data = [
    'line_items' => $lineItemsNew
];

$woocommerce->put('orders/'.$orderID, $data);
```

The line items are added and updated correctly but the total and taxes are not. What am I missing?

**Comment by claudiosanches** [comment]
Are you trying with code from master?

**Comment by claudiulodro** [comment]
Also which version of the orders API are you using? The new v2?

**Comment by michael-lynch** [comment]
No, I'm not using master. I'm using [2.7.0 RC 1](https://github.com/woocommerce/woocommerce/releases/tag/2.7.0-RC1) with the most recent, stable `v1` version (and the [PHP Wrapper](https://github.com/woocommerce/wc-api-php)). Should I be using v2? Is v2 instantiated the same way?

```
$woocommerce = new Client(
    'http://example.com', 
    'ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 
    'cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    [
        'wp_api' => true,
        'version' => 'wc/v1',
    ]
);
```

**Comment by mikejolley** [comment]
I see the issue.
