### ISSUE TITLE
Customer can't access their account and don't receive the "reset password" mail.

### ISSUE THREAD

**Issue by typhonp** [woocommerce/woocommerce#13490]
## EXPLANATION OF THE ISSUE

I recently received many mails from clients who can't connect to their account. They have an error saying "the password or user name is incorrect". They don't receive the "reset password" mail, even in their spam.
I checked, and they're writing to me with the same address they filled up when creating their account, so the mail addresses are correct.

## STEPS TO REPRODUCE THE ISSUE

I tried logging out and in, clicking the "send me a new password" link on the "my account" page, and it works fine for me. It works on my hotmail address, my sfr address and my gmail address. So I can't reproduce this issue, still I receive many complains from customers who don't receive any email and can't connect.

### WordPress Environment ###

Home URL: http://www.candysanbox.com
Site URL: http://www.candysanbox.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.14 - Nous recommandons PHP version 5.6 minimum. Voir : Comment mettre à jour votre version de PHP ?
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.37 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ Non
Subscriptions Mode: ✔ En ligne

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (16) ###

Polylang: par Frédéric Demarle – 2.1.1
Advanced Custom Fields: par Elliot Condon – 4.4.11
Akismet Anti-Spam: par Automattic – 3.3
Open Currency Converter: par David Artiss – 1.4.1
Helios Solutions WooCommerce Hide Price and Add to Cart button: par heliossolutions – 1.0
Instagram image gallery: par Iconosquare – 1.0.8
Loco Translate: par Tim Whitlock – 2.0.11
String Locator: par Clorith – 2.1.2
Uji Countdown: par Wpmanage.com – 2.0.7
WooCommerce Cart Count Shortcode: par Pronto Tools – 1.0.1
Hyyan WooCommerce Polylang Integration: par Hyyan Abo Fakher – 0.29.1
WooCommerce Currency Switcher: par realmag777 – 1.1.8
WooCommerce Subscriptions - Do Not Reduce Stock on Renewal: par Prospress Inc. –
Abonnements WooCommerce: par Prospress Inc. – 2.1.2
WooCommerce: par WooThemes – 2.6.14
Yoast SEO: par L’équipe Yoast – 4.4

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Base Boutique: #4 - /en/shop/
Panier: #5 - /panier/
Commande: #6 - /passer-commande/
Mon Compte: #7 - /mon-compte/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Vogue Child
Version: 1.3.01
Author URL: 
Child Theme: ✔
Parent Theme Name: Vogue
Parent Theme Version: 1.3.02 – 1.3.04 est disponible
Parent Theme Author URL: https://kairaweb.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by WPprodigy** [comment]
Probably an issue with the email servers w/ the web host.

WooCommerce just uses the built-in wp_mail function from WordPress to send out emails. This uses your web servers email system to send emails out to your email address.

You can test your servers email using a plugin like Check Email:
https://wordpress.org/plugins/check-email/

If Check Email says your server is working fine, it's probably an issue with your email filtering out our emails. If the test emails don't work, then your server might be having an issue sending them out. I would suggest trying out an alternative email service in that case.

___

This is not the place to ask for support though. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooCommerce Support](https://docs.woocommerce.com/) page.

**Comment by mikejolley** [comment]
^ To add, this is also an email which WordPress sends out not WooCommerce. Use a mail logging plugin, or something like SendGrid which is much more reliable that mail on your server.
