### ISSUE TITLE
Infinite loop on Subscriptions extension when trying to add new sub

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce#13496]
## EXPLANATION OF THE ISSUE
When you try to add a new subscription, an infinite loop happens.

Setup: Latest master, WP 4.7.3, [Prospress subscriptions](https://github.com/prospress/woocommerce-subscriptions).

Investigation: After reverting https://github.com/woocommerce/woocommerce/pull/13444 locally, this doesn't happen.

## STEPS TO REPRODUCE THE ISSUE
1. Activate plugin WC using latest master
2. Activate extension Subscriptions from Prospress (using their `wc_27_compatibility` branch)
3. Navigate to WooCommerce > Subscriptions
4. Click on `Add Subscription`
Expected: Form shows properly
Actual:
![screen shot 2017-03-07 at 15 11 20 pm](https://cloud.githubusercontent.com/assets/1620929/23660012/581be3b0-0348-11e7-81c1-fa48b44e04d4.png)

**Comment by bor0** [comment]
Ping @mikejolley

**Comment by mikejolley** [comment]
Looks like one of the functions subs has filtered into `woocommerce_payment_complete_order_status`. Looking. cc @thenbrent

**Comment by bor0** [comment]
[This causes it in Subscriptions](https://github.com/Prospress/woocommerce-subscriptions/blob/master/includes/class-wc-subscriptions-order.php#L1035), but we also have [this in bookings](https://github.com/woocommerce/woocommerce-bookings/blob/master/includes/class-wc-booking-order-manager.php#L294).

I'd imagine most extensions that hook on that use `wc_get_order` using the id.

**Comment by mikejolley** [comment]
See PR comment from brent

**Comment by tivnet** [comment]
@mikejolley Same issue when just clicking on "Orders" or "Subscriptions" - see #13547
