### ISSUE TITLE
Need to customize line_items meta field

### ISSUE THREAD

**Issue by el-k3rry** [woocommerce/woocommerce#13492]
When using a plugin for exporting the products (tours in this case) in cvs i would like to display just some "parts" of the line_items

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://dev.enroma.com
Site URL: http://dev.enroma.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache/2.4.6
PHP Version: 7.0.16
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Publicación remota: ✔
Obtención remota: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (25) ###

Addons for Visual Composer: por Livemesh – 1.4
Data types for Adventure Tours theme: por Themedelight – 2.1.9
Contact Form 7: por Takayuki Miyoshi – 4.6.1
Duplicator: por Snap Creek – 1.1.34
f(x) Editor: por David Chandra Purnama – 1.4.0
jQuery Vertical Accordion Menu: por Lee Chestnutt – 3.1.2
WPBakery Visual Composer: por Michael M - WPBakery.com – 5.0.1
Order Delivery Date for WooCommerce (Lite version): por Tyche Softwares – 2.7
Post Meta Inspector: por Daniel Bachhuber
Automattic – 1.1.1

Product Delivery Date for WooCommerce - Lite: por Tyche Softwares – 1.3
Slider Revolution: por ThemePunch – 5.3.1.5
TinyMCE Advanced: por Andrew Ozz – 4.4.3
Widget Importer & Exporter: por churchthemes.com – 1.4.4
WooCommerce Admin Custom Order Fields: por WooThemes / SkyVerge – 1.7.1
WooCommerce Extended Coupon Features: por Soft79 – 2.3.7.4
WooCommerce Bookings: por Automattic – 1.9.12
WooCommerce Customer/Order CSV Export: por WooThemes / SkyVerge – 4.1.4
WooCommerce Dynamic Pricing: por Lucas Stark – 2.12.2
Follow-Up Emails: por WooThemes – 4.4.18
WooCommerce Frontend Shop Manager - Free Version: por Mihajlovic Nenad – 1.0.3
WooCommerce PayPal Express Checkout Gateway: por Automattic – 1.1.2
WooCommerce: por WooThemes – 2.6.14
Importador de WordPress: por wordpresspuntoorg – 0.6.3
Yoast SEO: por Equipo Yoast – 4.4
Easy Forms for MailChimp: por YIKES
Inc. – 6.3.6

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Base de la tienda: #5640 - /compra/
Carrito: #5641 - /carrito/
Finalizar compra: #5642 - /checkout/
Mi cuenta: #5643 - /mio-account/

### Taxonomies ###

Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
tour (tour)
variable (variable)
wcpb (wcpb)

### Theme ###

Name: Adventure Tours Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Adventure Tours
Parent Theme Version: 2.4.0
Parent Theme Author URL: http://themeforest.net/user/themedelight
WooCommerce Support: ✔

### Templates ###

Overrides: adventure-tours/woocommerce/archive-product.php
adventure-tours/woocommerce/cart/cart-empty.php
adventure-tours/woocommerce/cart/cart-totals.php
adventure-tours/woocommerce/cart/cart.php
adventure-tours/woocommerce/cart/cross-sells.php
adventure-tours/woocommerce/cart/mini-cart.php
adventure-tours/woocommerce/checkout/form-checkout.php
adventure-tours/woocommerce/checkout/review-order.php
adventure-tours/woocommerce/checkout/thankyou.php
adventure-tours/woocommerce/content-product.php
adventure-tours/woocommerce/content-product_cat.php
adventure-tours/woocommerce/content-single-product.php
adventure-tours/woocommerce/content-widget-product.php
adventure-tours-child/woocommerce/emails/admin-new-order.php
adventure-tours-child/woocommerce/emails/customer-completed-order.php
adventure-tours-child/woocommerce/emails/customer-invoice.php
adventure-tours-child/woocommerce/emails/customer-new-account.php
adventure-tours-child/woocommerce/emails/customer-on-hold-order.php
adventure-tours-child/woocommerce/emails/customer-processing-order.php
adventure-tours-child/woocommerce/emails/plain/customer-completed-order.php
adventure-tours-child/woocommerce/emails/plain/customer-invoice.php
adventure-tours-child/woocommerce/emails/plain/customer-on-hold-order.php
adventure-tours-child/woocommerce/emails/plain/customer-processing-order.php
adventure-tours/woocommerce/global/sidebar.php
adventure-tours/woocommerce/global/wrapper-end.php
adventure-tours/woocommerce/global/wrapper-start.php
adventure-tours/woocommerce/loop/loop-end.php
adventure-tours/woocommerce/loop/loop-start.php
adventure-tours/woocommerce/loop/pagination.php
adventure-tours/woocommerce/myaccount/form-login.php
adventure-tours/woocommerce/notices/error.php
adventure-tours/woocommerce/notices/notice.php
adventure-tours/woocommerce/notices/success.php
adventure-tours/woocommerce/order/order-details-customer.php
adventure-tours/woocommerce/order/order-details-item.php
adventure-tours/woocommerce/single-product/add-to-cart/variable.php
adventure-tours/woocommerce/single-product/meta.php
adventure-tours/woocommerce/single-product/price.php
adventure-tours/woocommerce/single-product/product-image.php
adventure-tours/woocommerce/single-product/product-thumbnails.php
adventure-tours/woocommerce/single-product/rating.php
adventure-tours/woocommerce/single-product/related.php
adventure-tours/woocommerce/single-product/review.php
adventure-tours/woocommerce/single-product/tabs/description.php
adventure-tours/woocommerce/single-product/tabs/tabs.php
adventure-tours/woocommerce/single-product/title.php
adventure-tours/woocommerce/single-product/up-sells.php
adventure-tours/woocommerce/single-product-reviews.php
adventure-tours/woocommerce/single-product.php
adventure-tours/woocommerce/taxonomy-product_cat.php

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled
`

**Comment by mikejolley** [comment]
Order/CSV export is an extension not core. This is our core bug tracker. Use the helpdesk please, or feature requests to ideas.woocommerce.com.
