### ISSUE TITLE
woocoomerce api error rest no route 404

### ISSUE THREAD

**Issue by reng92** [woocommerce/woocommerce#13504]
i have a problem, i created a woocommerce website, now a team of developer have to create a woocomerce app so they need this, they sent me this : https://www.example.com/wp-json/wc/v1/products/ -u consumerkey:consumersecret

but they are getting a 404 error rest no route with this url, they can't estabilish a connection, there is a valid ssl certificate, i tried to solve the problem but there is always that problem, what could be the problem? they said maybe it's because the website is running on nginx on a shared hosting, but the hosting said they tried also with an apache server but there is always that error no route was found 404...
i can't provide url o ftp, sorry
the wordpress version is the latest, php 5.6
i tried disabling all the puglins, switching to default wordpress theme with no success
the woocommerce website is in test so there are 10 products and some categories but it's not online for the clients yet
thanks in advance for the help.

**Comment by mikejolley** [comment]
Without even a link to the site nothing we can even suggest; this works on our tests sites and others so it's specific to your install. Maybe try accessing the WP Rest API first, which ours builds upon.
