### ISSUE TITLE
Coupon usage count is incorrect

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#13505]
## EXPLANATION OF THE ISSUE
When multiple orders are coming in at the same time, the coupon usage doesn't update properly.

We've recently had a large promotion where hundreds of users were buying products at the same time.

We had a coupon set to expire when it was used 1000 times, however we had to manually disable it after we reached more than 1500 times. The counter was still showing 700 uses.

## STEPS TO REPRODUCE THE ISSUE

1. Create a coupon. Usage will be 0
2. Set a usage limit (optional)
3. Have multiple (>100 in our case) users placing orders at the same time (preferrably at the same second).
4. Check the coupon usage.

## Possible cause
On class WC_Coupon line 278 you've got function inc_usage_count that increases the usage_count meta field of the coupon. This function gets the current usage_count, increases it and then writes it on the SQL.

In the miliseconds between read and write, it's possible that another process will have read the same number and will update to the same number.

Process A: Reads count as 0
Process B: Reads count as 0
Process A: Increases count to 1
Process B: Increases count to 1
Process A: Writes count as 1
Process B: Writes count as 1

Total orders 2
Reported usage count 1

## Possible solution
Replace line 278 & 279 on class WC_Coupon with the following query
`UPDATE wp_postmeta
SET meta_value = meta_value + 1
WHERE
post_id = '".$this->id."'
AND meta_key = 'usage_count'`

**Comment by claudiulodro** [comment]
These sorts of problems will be solved fully when we implement a fix for #12467.

@mikejolley how do you feel about including a fix for this specific problem in 2.7 with the new MYSQL statement @glagonikas recommends? Or should we wait until the whole concurrent checkout problem is tackled?

**Comment by mikejolley** [comment]
@claudiulodro Could be a good quick fix - data-store, increase_usage_count method.
