### ISSUE TITLE
updating shipping lines with API adds new line, not replace

### ISSUE THREAD

**Issue by michael-lynch** [woocommerce/woocommerce#13515]
## EXPLANATION OF THE ISSUE

I am using 2.7 RC and the `v1` API. I add an item to an order and calculate the shipping. Then I add another item to the order so I update the shipping line total. Rather than update the existing shipping line, another line is added, and the shipping total is multiplied.

## STEPS TO REPRODUCE THE ISSUE

Create an order:

```
$order = $woocommerce->post('orders/', [
    'status' => 'pending',
    'line_items' => $lineItems,
    'shipping_lines' => [
        [
            'method_title' => 'USPS',
             'method_id' => 'flat_rate',
            'total' => $shippingTotal
        ]
    ]
]);
```

Update an order:

```
$orderUpdated = $woocommerce->put('orders/'.$orderID, [
    'shipping_lines' => [
        [
            'method_title' => 'USPS',
             'method_id' => 'flat_rate',
            'total' => $shippingTotalNew
        ]
    ]
]);
```

The next time I `get` the order, there are two items in the `shipping_lines` array and the `shipping_total` is the sum.

**Comment by mikejolley** [comment]
@claudiosanches can confirm but it looks like you're missing an `id` on the line which is required to edit.

**Comment by claudiulodro** [comment]
@mikejolley is correct. [You need the id to edit otherwise it creates a new one](https://github.com/woocommerce/woocommerce/blob/1e576133b18a37107945243f71bee38618dde917/includes/api/v1/class-wc-rest-orders-controller.php#L681).

**Comment by michael-lynch** [comment]
Ah, yes, you are right. I thought the `method_id` was all that was needed, but adding the `id` value did the trick.
