### ISSUE TITLE
[2.7] Product attributes in cart is not wrapped in a list (or similar)

### ISSUE THREAD

**Issue by transbetacism** [woocommerce/woocommerce#13513]
## EXPLANATION OF THE ISSUE
When showing the product in the cart, the products attributes is not formatted.

### DETAILS ###
In version 2.3.8 of `templates/cart/cart.php` (previous version before 2.7), `get_title` was used to retrieve the product name:
<pre>if ( ! $product_permalink ) {
  echo apply_filters( 'woocommerce_cart_item_name', $_product->get_title(), $cart_item, $cart_item_key ) . '&nbsp;';
} else {
  echo apply_filters( 'woocommerce_cart_item_name', sprintf( '<a href="%s">%s</a>', esc_url( $product_permalink ), $_product->get_title() ), $cart_item, $cart_item_key );
}
</pre>

This returned the product name with the selected attributes (notice `dl` with attributes):

    <a href="...">Branded Paper</a>
      <dl class="variation">
        <dt class="variation-PaperSize">Paper Size:</dt>
        <dd class="variation-PaperSize"><p>A3</p></dd>
        <dt class="variation-Finish">Finish:</dt>
      <dd class="variation-Finish"><p>Glossy</p></dd>
    </dl>

Since 2.7 (I think), `get_title` only returns the product name without the attributes. `templates/cart/cart.php`uses the `get_name` from version 2.7:

    if ( ! $product_permalink ) {
      echo apply_filters( 'woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key ) . '&nbsp;';
    } else {
      echo apply_filters( 'woocommerce_cart_item_name', sprintf( '<a href="%s">%s</a>', esc_url( $product_permalink ), $_product->get_name() ), $cart_item, $cart_item_key );
    }

This returns the product name with the attributes, but **the problem** is that the attributes is not returned in a way that they can be styled in the cart. They will have the same styling as the name.

    <a href="http://localhost:8888/scandinavian/shop/branded-paper/?attribute_pa_paper-size=a3&amp;attribute_pa_finish=glossy">Branded Paper – Paper Size: A3, Finish: Glossy</a>

See this image of how the product name (Branded Paper) with the attributes (Paper Size and Finish) in the Storefront theme. Before, the attributes would be in a `dl`
![image](http://share.hellodetail.com/jTWg/Image%202017-03-08%20at%208.59.37%20em.png)

## STEPS TO REPRODUCE THE ISSUE

Add a product to the cart which has different variations. Try to style the attributes... This was possible before but not any longer as I can see it...

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by WPprodigy** [comment]
This was done on purpose here: https://github.com/woocommerce/woocommerce/pull/13136

Depending on how long/how many attributes there are, it can be displayed in "short form".

**Comment by claudiulodro** [comment]
As @WPprodigy stated, this was done on purpose. The new way gives variations a clear, helpful name and eliminates the need for a big list of attributes explaining what it is you're buying.
