### ISSUE TITLE
Woo2.7 doesn't work with woocommerce-sequential-order-numbers-pro plugin

### ISSUE THREAD

**Issue by russellclow** [woocommerce/woocommerce#13518]
## EXPLANATION OF THE ISSUE

Updated Woocommerce to 2.7 RC - and after it was done, we ran into this issue:

Fatal error: Uncaught Error: Call to undefined function is_ajax() in /nas/content/staging/tulaforlife/wp-content/plugins/woocommerce-sequential-order-numbers-pro/lib/skyverge/woocommerce/class-sv-wc-framework-bootstrap.php:176 Stack trace: #0 [internal function]: SV_WC_Framework_Bootstrap->load_framework_plugins('') #1 /nas/content/staging/tulaforlife/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #2 /nas/content/staging/tulaforlife/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #3 /nas/content/staging/tulaforlife/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /nas/content/staging/tulaforlife/wp-settings.php(326): do_action('plugins_loaded') #5 /nas/content/staging/tulaforlife/wp-config.php(138): require_once('/nas/content/st...') #6 /nas/content/staging/tulaforlife/wp-load.php(37): require_once('/nas/content/st...') #7 /nas/content/staging/tulaforlife/wp-admin/admin.php(31): require_once('/nas/content/st...') #8 /nas/content/staging/tulaforlife/wp-admin/update-c in /nas/content/staging/tulaforlife/wp-content/plugins/woocommerce-sequential-order-numbers-pro/lib/skyverge/woocommerce/class-sv-wc-framework-bootstrap.php on line 176

## STEPS TO REPRODUCE THE ISSUE

As above

## SYSTEM STATUS REPORT

No can do, can't access anything now :/

**Comment by mikejolley** [comment]
is_ajax still exists in WC - I presume it was just called before WC was loaded, or whilst WC was updating. Paging @bekarice and @maxrice

**Comment by mikejolley** [comment]
@russellclow To get site back, use FTP to delete the woocommerce-sequential-order-numbers-pro plugin from wp-content/plugins/. That will deactivate it.

**Comment by russellclow** [comment]
Well that doesn't solve the issue - as we need that plugin ;)

**Comment by mikejolley** [comment]
It will get your site up :) I've pinged the team who maintain it - they may already have a fix ready to go.

**Comment by bekarice** [comment]
@russellclow please keep an eye on the changelog, as the release version of Sequential Order Numbers Pro is not WooCommerce 2.7 compatible yet, and do not use WC 2.7 on a live site. We always add a note to the extension changelog when we've added compatibility for a major WooCommerce version.

Compatibility for the plugin is done, but we held all compat releases due to #13498 on Tuesday and will release them instead after we have a chance to account for that change.
