### ISSUE TITLE
Order status not updated after payment was made using PayFast plugin.

### ISSUE THREAD

**Issue by francdore** [woocommerce/woocommerce#13521]
## EXPLANATION OF THE ISSUE

I have the latest WooCommerce version installed. I accept credit card payments using the PayFast plugin and when a user makes a successful payment, it used to set the order status to processing when the payment was successful. It doesn't do that anymore. The payment goes through and after the payment gateway payment it redirects back to my online shop with no problem. But the order status stays as "Waiting for payment." I've already contacted the Payment Gateway and they say the issue isn't on their side.

## STEPS TO REPRODUCE THE ISSUE

Install PayFast with the merchant ID and merchant key.
Place an order by adding it to your cart, checkout and make the payment and get redirected to the order complete page.
Check the order status in the back end and notice that it still says "Awaiting payment".

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://www.joburgbeardcompany.co.za
Site URL: https://www.joburgbeardcompany.co.za
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: ❌ 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (29) ###

Advanced Custom Fields: Repeater Field: by Elliot Condon – 1.1.1
Advanced Custom Fields: by Elliot Condon – 4.4.11
AfterShip - WooCommerce Tracking: by AfterShip – 1.6.7
All In One SEO Pack: by Michael Torbert – 2.3.12
All In One WP Security: by Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.2.5

Bootstrap for Contact Form 7: by Felix Arntz – 1.4.2
ChimpMate - WordPress MailChimp Assistant: by Voltroid – 1.2.10
Contact Form 7: by Takayuki Miyoshi – 4.7
Google Tag Manager for Wordpress: by Thomas Geiger – 1.5.1
Facebook Likebox Widget & Shortcode: by A WP Life – 0.4.8
WooCommerce - Gift Cards: by WP Ronin – 2.5.6
Google XML Sitemaps: by Arne Brachhold – 4.0.8
MailChimp for WordPress: by ibericode – 4.0.13
Redirection: by John Godley – 2.5
Compress JPEG & PNG images: by TinyPNG – 2.2.2
Video Thumbnails: by Sutherland Boswell – 2.12.3
W3 Total Cache: by Frederick Townes – 0.9.5.2
WC Cancel Order: by Vikram Singh – 2.0
Facebook Open Graph, Google+ and Twitter Card Tags: by Webdados – 2.0.7
WooCommerce PayFast Gateway: by WooThemes – 1.4.0
WooCommerce SnapScan Gateway: by SnapScan – 1.0.1
WooCommerce AdWords Conversion Tracking: by Wolf+Bär GmbH – 1.3.5
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.5.39
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
WP Product Feed Manager: by Michel Jongbloed – 1.4.3
WP Store Locator: by Tijmen Smit – 2.2.7
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.25
Zapper Payments for WooCommerce: by Zapper Development – 1.2.1

### Settings ###

Force SSL: ✔
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My Account: #7 - /my-account/

### Taxonomies ###

Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Joburg Beard Company 2017
Version: 1.0
Author URL: http://www.mustache.co.za/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: joburgbeardcompany/woocommerce/archive-product.php
joburgbeardcompany/woocommerce/cart/cart-empty.php
joburgbeardcompany/woocommerce/cart/cart-item-data.php
joburgbeardcompany/woocommerce/cart/cart-shipping.php
joburgbeardcompany/woocommerce/cart/cart-totals.php
joburgbeardcompany/woocommerce/cart/cart.php
joburgbeardcompany/woocommerce/cart/cross-sells.php
joburgbeardcompany/woocommerce/cart/mini-cart.php
joburgbeardcompany/woocommerce/cart/proceed-to-checkout-button.php
joburgbeardcompany/woocommerce/cart/shipping-calculator.php
joburgbeardcompany/woocommerce/checkout/cart-errors.php
joburgbeardcompany/woocommerce/checkout/form-billing.php
joburgbeardcompany/woocommerce/checkout/form-checkout.php
joburgbeardcompany/woocommerce/checkout/form-coupon.php
joburgbeardcompany/woocommerce/checkout/form-login.php
joburgbeardcompany/woocommerce/checkout/form-pay.php
joburgbeardcompany/woocommerce/checkout/form-shipping.php
joburgbeardcompany/woocommerce/checkout/payment-method.php
joburgbeardcompany/woocommerce/checkout/payment.php
joburgbeardcompany/woocommerce/checkout/review-order.php
joburgbeardcompany/woocommerce/checkout/terms.php
joburgbeardcompany/woocommerce/checkout/thankyou.php
joburgbeardcompany/woocommerce/content-product.php
joburgbeardcompany/woocommerce/content-product_cat.php
joburgbeardcompany/woocommerce/content-single-product.php
joburgbeardcompany/woocommerce/content-widget-product.php
joburgbeardcompany/woocommerce/global/breadcrumb.php
joburgbeardcompany/woocommerce/global/form-login.php
joburgbeardcompany/woocommerce/global/quantity-input.php
joburgbeardcompany/woocommerce/global/sidebar.php
joburgbeardcompany/woocommerce/global/wrapper-end.php
joburgbeardcompany/woocommerce/global/wrapper-start.php
joburgbeardcompany/woocommerce/loop/add-to-cart.php
joburgbeardcompany/woocommerce/loop/loop-end.php
joburgbeardcompany/woocommerce/loop/loop-start.php
joburgbeardcompany/woocommerce/loop/no-products-found.php
joburgbeardcompany/woocommerce/loop/orderby.php
joburgbeardcompany/woocommerce/loop/pagination.php
joburgbeardcompany/woocommerce/loop/price.php
joburgbeardcompany/woocommerce/loop/rating.php
joburgbeardcompany/woocommerce/loop/result-count.php
joburgbeardcompany/woocommerce/loop/sale-flash.php
joburgbeardcompany/woocommerce/myaccount/dashboard.php
joburgbeardcompany/woocommerce/myaccount/downloads.php
joburgbeardcompany/woocommerce/myaccount/form-add-payment-method.php
joburgbeardcompany/woocommerce/myaccount/form-edit-account.php
joburgbeardcompany/woocommerce/myaccount/form-edit-address.php
joburgbeardcompany/woocommerce/myaccount/form-login.php
joburgbeardcompany/woocommerce/myaccount/form-lost-password.php
joburgbeardcompany/woocommerce/myaccount/form-reset-password.php
joburgbeardcompany/woocommerce/myaccount/lost-password-confirmation.php
joburgbeardcompany/woocommerce/myaccount/my-account.php
joburgbeardcompany/woocommerce/myaccount/my-address.php
joburgbeardcompany/woocommerce/myaccount/my-downloads.php
joburgbeardcompany/woocommerce/myaccount/my-orders.php
joburgbeardcompany/woocommerce/myaccount/navigation.php
joburgbeardcompany/woocommerce/myaccount/orders.php
joburgbeardcompany/woocommerce/myaccount/payment-methods.php
joburgbeardcompany/woocommerce/myaccount/view-order.php
joburgbeardcompany/woocommerce/order/form-tracking.php
joburgbeardcompany/woocommerce/order/order-again.php
joburgbeardcompany/woocommerce/order/order-details-customer.php
joburgbeardcompany/woocommerce/order/order-details-item.php
joburgbeardcompany/woocommerce/order/order-details.php
joburgbeardcompany/woocommerce/order/tracking.php
joburgbeardcompany/woocommerce/product-searchform.php
joburgbeardcompany/woocommerce/single-product/add-to-cart/external.php
joburgbeardcompany/woocommerce/single-product/add-to-cart/grouped.php
joburgbeardcompany/woocommerce/single-product/add-to-cart/simple.php
joburgbeardcompany/woocommerce/single-product/add-to-cart/variable.php
joburgbeardcompany/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
joburgbeardcompany/woocommerce/single-product/add-to-cart/variation.php
joburgbeardcompany/woocommerce/single-product/meta.php
joburgbeardcompany/woocommerce/single-product/price.php
joburgbeardcompany/woocommerce/single-product/product-attributes.php
joburgbeardcompany/woocommerce/single-product/product-image.php
joburgbeardcompany/woocommerce/single-product/product-thumbnails.php
joburgbeardcompany/woocommerce/single-product/rating.php
joburgbeardcompany/woocommerce/single-product/related.php
joburgbeardcompany/woocommerce/single-product/review-meta.php
joburgbeardcompany/woocommerce/single-product/review-rating.php
joburgbeardcompany/woocommerce/single-product/review.php
joburgbeardcompany/woocommerce/single-product/sale-flash.php
joburgbeardcompany/woocommerce/single-product/share.php
joburgbeardcompany/woocommerce/single-product/short-description.php
joburgbeardcompany/woocommerce/single-product/tabs/additional-information.php
joburgbeardcompany/woocommerce/single-product/tabs/description.php
joburgbeardcompany/woocommerce/single-product/tabs/tabs.php
joburgbeardcompany/woocommerce/single-product/title.php
joburgbeardcompany/woocommerce/single-product/up-sells.php
joburgbeardcompany/woocommerce/single-product-reviews.php
joburgbeardcompany/woocommerce/single-product.php
joburgbeardcompany/woocommerce/taxonomy-product_cat.php
joburgbeardcompany/woocommerce/taxonomy-product_tag.php

**Comment by mikejolley** [comment]
Please use the helpdesk so this can be investigated. This is the core issue tracker.

https://woocommerce.com/my-account/tickets/

**Comment by Anthonipples** [comment]
was this ever resolved - I am facing this issue currently

**Comment by francdore** [comment]
Hi,

Yes! There's a setting in W3 Total cache that you need to add.

You must add _wc_session_ to the "Ignored Query Strings" option in W3TC
settings

[image: Inline image 1]

**Comment by francdore** [comment]
![image](https://cloud.githubusercontent.com/assets/2630949/26203419/69890c2e-3bdb-11e7-8378-0a5cd44d55f1.png)

**Comment by Anthonipples** [comment]
Unforunately I am not using w3 total cache :( is there any other way to
trouble shoot this?

**Comment by francdore** [comment]
What plugins do you have installed?

**Comment by Anthonipples** [comment]
Here is a screen shot of all the plugins installed
![plugins](https://cloud.githubusercontent.com/assets/22741576/26203646/5a8b1586-3bdc-11e7-8d7d-74f1dee2f84c.PNG)

**Comment by francdore** [comment]
Maybe you should do an update and see if that fixes it first.

**Comment by Anthonipples** [comment]
Updating all plugins worked - I suspect it was the shipping plugin

**Comment by francdore** [comment]
Awesome!

**Comment by jacealbert** [comment]
Erectile dysfunction has been a problem to me for years,my wife always get disappointed with me when ever will are in bed,i don’t last for up to two minute,during sex, i have taking different medication but to no solution,then i went on the net for a solution on how to enlarge my penis and i got contact of DR SALATO who help in cure erection and ejaculation problem with his product and also help to enlarge penis,i got in touch with him through is email drsalatosolutiontemple@gmail.com and i got the product. which i took for just a week and my ejaculation is now normal and my erection is hard and my
penis got bigger than before and now i can last long in bed. now 10.5 inches long on erection and off course very large round. I am very happy for this Penis Enlargement experience there is no side effect . He can help with all kinds of cure you may need as flows: 
Penis Enlargement 
Low sperm count 
Weak Erection
Love spell 
Herpes spell
HIV spell 
Pregnancy spell 
Marriage for spell
cancer
watering sperm
womb fertilization
penis erection
witch craft attack
s t d diseases
internal heat
rashes
dairy
long time sickness
kidney,heart,lungs,problem
with DR SALATO  you are in safe hands your healing is assured
Email:drsalatosolutiontemple@gmail.com for his whatsapp or Call : +2348103629945

**Comment by italodr** [comment]
Hi,

I've made the changes in W3 Total Cache and does not update my payment status. 
I'm using a [Redsys Woocommerce](http://www.redsys.es/#descargas) plugin

Here is the list of plugins I use

![plugins](https://user-images.githubusercontent.com/2691320/32997250-637c3a10-cd8d-11e7-846e-8be221ac8c74.png)
