### ISSUE TITLE
Customer Downloads: Update date functions

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13527]
- [x] access_granted
- [x] access_expires
- [x] Data store read/write
- [x] Match 2.6.x meta value schema
- [x] Update usage in admin
- [x] Update usage in API WP v2
- [x] Update usage in API WP v1
- [x] Update usage in Legacy API v1
- [x] Update usage in Legacy API v2
- [x] Update usage in Legacy API v3
- [x] Update schema in WIKI

**Comment by claudiosanches** [comment]
@mikejolley no fixed required in WP API v2 or v1, and there is no schema in WIKI for downloads.
