### ISSUE TITLE
[2.7.0-RC1] - Undefined index _shipping_country on edit order shipping details

### ISSUE THREAD

**Issue by andreagrillo** [woocommerce/woocommerce#13529]
## EXPLANATION OF THE ISSUE

With latest 2.7.0-RC1 master when you edit the shipping address a php notice appear:

`PHP Notice:  Undefined index: _shipping_country in /srv/www/wc_2_7/htdocs/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php on line 498`

## STEPS TO REPRODUCE THE ISSUE

Before testing open the file wp-config and enable the debug.log with define( 'WP_DEBUG_LOG', true );

1. Login to admin dashboard 
2. Go to WooCommerce > Orders and edit an order. 
3. Click on "pencil" to edit the shipping details
4.  Edit the information 
5. save the order. 
6. Open the debug.log file to see the notice

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://wc_2_7.dev
Site URL: http://wc_2_7.dev
WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7.3-alpha-40119
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.7
PHP Version: 7.0.14-2+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

User Switching: by John Blackbourn – 1.0.9
WooCommerce: by Automattic – 2.7.0-RC1
WordPress Importer: by wordpressdotorg – 0.6.3
YITH WooCommerce Multi Vendor Premium: by YITHEMES – 1.12.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by claudiulodro** [comment]
I'm unable to reproduce this issue.

The `Undefined index: _shipping_country` error would mean that there is no `$_POST['_shipping_country']` in the request, but that is the shipping country select dropdown input which is definitely there. Everything looks good as far as I can tell.

Can you give me a little information about what country you selected or anything else that may help me reproduce it?

**Comment by andreagrillo** [comment]
Hi @claudiulodro 

thanks for your time. 
I deactivate all plugins and try it again with only WooCommerce enabled and I have the same issue. 
I record a screencast for you, I hope this can help you to reproduce the issue.

You can see the video here: https://nimbus.everhelper.me/client/notes/share/806146/av8gwgy5y366ccgggh5e

About the Country:

after your reply I tested it and I can't set any kind of country, look this screencast:
https://nimbus.everhelper.me/client/notes/share/806152/dcs984gds6u8tv35peb4

I check the XHR request, but seems that no ajax call was fired....this is ver ystrange.
However, if you need more information I'm here :-) 
Have a nice day 

AG

**Comment by claudiulodro** [comment]
@andreagrillo, it looks like you probably have "Sell to specific countries" in your settings with no specific countries selected. That is why you don't get anything in the country selector. See #13571

**Comment by andreagrillo** [comment]
Hi @claudiulodro 

I check this and I'll let you know. 
Thanks for your reporting.
