### ISSUE TITLE
Customer: Update `date_` functions

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13526]
- [x] date_created
- [x] date_modified
- [x] Data store read/write
- [x] Match 2.6.x meta value schema
- [x] Update usage in admin
- [x] Update usage in API WP v2
- [x] Update usage in API WP v1
- [x] Update usage in Legacy API v1
- [x] Update usage in Legacy API v2
- [x] Update usage in Legacy API v3
- [x] Update schema in WIKI

**Comment by claudiosanches** [comment]
For "Data store read/write" we `wp_user->user_registered` for it:
https://github.com/woocommerce/woocommerce/blob/16b0aa9a52ddfcb57cee321ca9e591ad321bf42c/includes/data-stores/class-wc-customer-data-store.php#L107

And the custom meta field `last_update` already uses timestamp in UTC+0:
https://github.com/woocommerce/woocommerce/blob/ce6c4a736f5041ccdc3709a5b267f49a41aac8d7/includes/wc-user-functions.php#L517-L567

If the `date_default_timezone_set()` is UTC.

**Comment by mikejolley** [comment]
👍 So data store needs no adjustments if thats correct.

**Comment by claudiosanches** [comment]
@mikejolley the only adjustment has been on #13539, just to make sure that uses the same as WordPress does when set `user_registered`: https://github.com/WordPress/WordPress/blob/4548b08236fa2fdc8d9443ed70e8b53f7057a151/wp-includes/user.php#L1607
