### ISSUE TITLE
Uncaught TypeError: a(...).fadeTo(...).block is not a function

### ISSUE THREAD

**Issue by sayedrabbi** [woocommerce/woocommerce#13522]
## EXPLANATION OF THE ISSUE

My error is:
Uncaught TypeError: a(...).fadeTo(...).block is not a function
    at Object.success (add-to-cart.min.js?ver=2.6.14:4)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at y (jquery.js?ver=1.12.4:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4:4)

and My site link is [](http://giovanni.themeseller.net/)

## STEPS TO REPRODUCE THE ISSUE

I don't know Why that happening.. plz have a look this problem..

## SYSTEM STATUS REPORT
My status report [](http://themeseller.net/2017-03-09_165435.png)
plz have a look...
```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
Usually caused by loading two instances of jquery on the page - no link though so I cannot check.

**Comment by sayedrabbi** [comment]
This is website link 
http://giovanni.themeseller.net
and this is status report
http://themeseller.net/2017-03-09_165435.png

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/ttjy07lq14nepmk/2017-03-09%20at%2011.21.png Not an issue in WC, an issue in your theme.

**Comment by sayedrabbi** [comment]
ok.. thank you
