### ISSUE TITLE
Update Price - REST API

### ISSUE THREAD

**Issue by jmawebtech** [woocommerce/woocommerce#13536]
Hi,

I am unsure if this is a support issue or a coding problem. I apologize in advance, if I am posting in the wrong place. I am trying to update the regular price of a product in WooCommerce. The solution works with simple products, but it fails with variants. 

PUT https://www.XX.com/wp-json/wc/v1/products/59675?stock_quantity=1&consumer_key=XX&consumer_secret=XX HTTP/1.1
Authorization: Basic X
Content-Type: application/json
Host: www.xx.com
Content-Length: 41
Expect: 100-continue
Connection: Keep-Alive

{"stock_quantity":1,"regular_price":"79"}

Response:

{
   "id": 59674,
   "name": "Glassy Johnson",
   "slug": "glassy-johnson",
   "permalink": "https://www.fairmans.com/?post_type=product&p=59674",
   "date_created": "2017-02-11T23:42:18",
   "date_modified": "2017-03-09T23:11:55",
   "type": "variable",
   "status": "draft",
   "featured": false,
   "catalog_visibility": "visible",
   "description": "<div>The Marc Johnson signature sunglasses are designed on the frame of a Leonard that is made from <strong>100% real wood<\/strong>. The lenses are polarized with glare reduction and enhanced clarity for the best possible image, while being 100% UVA and UVB resistant to block your eyes from the harmful rays of the sun. The hinges are made from a durable metal with a spring hinge so you can bend the&nbsp;arms outward for an additional 30 degrees for the best possible comfort. The wood is extremely lightweight and you can feel the quality the moment you pick it up.&nbsp;<\/div>\n<div>&nbsp;<\/div>\n<div>\n<div><strong>Dimensions:&nbsp;<\/strong><\/div>\n<div>\n<div><strong>Lens Width/Height:&nbsp;<\/strong>51 x 39mm&nbsp;&nbsp;<\/div>\n<div><strong>Bridge<\/strong><strong>:<\/strong>&nbsp;23mm<strong>&nbsp;<\/strong>&nbsp;&nbsp;<\/div>\n<div><strong>Arm Length<\/strong><b>:&nbsp;<\/b>140mm<b>&nbsp;<\/b><\/div>\n<div><b>Frame Width:&nbsp;<\/b>145mm<\/div>\n<\/div>\n<\/div>\n",
   "short_description": "<div>The Marc Johnson signature sunglasses are designed on the frame of a Leonard that is made from <strong>100% real wood<\/strong>. The lenses are polarized with glare reduction and enhanced clarity for the best possible image, while being 100% UVA and UVB resistant to block your eyes from the harmful rays of the sun. The hinges are made from a durable metal with a spring hinge so you can bend the&nbsp;arms outward for an additional 30 degrees for the best possible comfort. The wood is extremely lightweight and you can feel the quality the moment you pick it up.&nbsp;<\/div>\n<div>&nbsp;<\/div>\n",
   "sku": "8274",
   "price": "80",
   "regular_price": "",
   "sale_price": "",
   "date_on_sale_from": "",
   "date_on_sale_to": "",
   "price_html": "<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>80.00<\/span>",
   "on_sale": false,
   "purchasable": true,
   "total_sales": 0,
   "virtual": false,
   "downloadable": false,
   "downloads": [],
   "download_limit": -1,
   "download_expiry": -1,
   "download_type": "standard",
   "external_url": "",
   "button_text": "",
   "tax_status": "taxable",
   "tax_class": "",
   "manage_stock": true,
   "stock_quantity": 1,
   "in_stock": true,
   "backorders": "no",
   "backorders_allowed": false,
   "backordered": false,
   "sold_individually": true,
   "weight": "0",
   "dimensions": {
      "length": "0",
      "width": "0",
      "height": "0"
   },
   "shipping_required": true,
   "shipping_taxable": true,
   "shipping_class": "",
   "shipping_class_id": 0,
   "reviews_allowed": true,
   "average_rating": "0.00",
   "rating_count": 0,
   "related_ids": [
      59666,
      59720,
      59737,
      59747,
      59744
   ],
   "upsell_ids": [],
   "cross_sell_ids": [],
   "parent_id": 0,
   "purchase_note": "",
   "categories": [
      {
         "id": 8819,
         "name": "Accessories",
         "slug": "accessories"
      },
      {
         "id": 9525,
         "name": "Sunglasses",
         "slug": "sunglasses"
      }
   ],
   "tags": [
      {
         "id": 8723,
         "name": "Glassy",
         "slug": "glassy"
      }
   ],
   "images": [
      {
         "id": 68372,
         "date_created": "2017-03-01T19:12:31",
         "date_modified": "2017-03-01T19:12:31",
         "src": "https://www.fairmans.com/wp-content/uploads/2017/02/8274.jpg",
         "name": "8274",
         "alt": "",
         "position": 0
      }
   ],
   "attributes": [
      {
         "id": 8,
         "name": "Color",
         "position": 0,
         "visible": false,
         "variation": true,
         "options": [
            "Wood"
         ]
      }
   ],
   "default_attributes": [
      {
         "id": 8,
         "name": "Color",
         "option": "wood"
      }
   ],
   "variations": [
      {
         "id": 59675,
         "date_created": "2017-02-11T16:54:12",
         "date_modified": "2017-03-01T19:12:48",
         "permalink": "https://www.fairmans.com/?post_type=product&p=59674&attribute_pa_color=wood",
         "sku": "8274",
         "price": "80",
         "regular_price": "80",
         "sale_price": "",
         "date_on_sale_from": "",
         "date_on_sale_to": "",
         "on_sale": false,
         "purchasable": true,
         "visible": true,
         "virtual": false,
         "downloadable": false,
         "downloads": [],
         "download_limit": -1,
         "download_expiry": -1,
         "tax_status": "taxable",
         "tax_class": "",
         "manage_stock": true,
         "stock_quantity": 1,
         "in_stock": true,
         "backorders": "no",
         "backorders_allowed": false,
         "backordered": false,
         "weight": "1",
         "dimensions": {
            "length": "0",
            "width": "0",
            "height": "0"
         },
         "shipping_class": "",
         "shipping_class_id": 0,
         "image": [
            {
               "id": 68372,
               "date_created": "2017-03-01T19:12:31",
               "date_modified": "2017-03-01T19:12:31",
               "src": "https://www.fairmans.com/wp-content/uploads/2017/02/8274.jpg",
               "name": "8274",
               "alt": "",
               "position": 0
            }
         ],
         "attributes": [
            {
               "id": 8,
               "name": "Color",
               "option": "Wood"
            }
         ]
      }
   ],
   "grouped_products": [],
   "menu_order": 2,
   "_links": {
      "self": [
         {
            "href": "https://www.fairmans.com/wp-json/wc/v1/products/59674"
         }
      ],
      "collection": [
         {
            "href": "https://www.fairmans.com/wp-json/wc/v1/products"
         }
      ]
   }
}

**Comment by claudiosanches** [comment]
It a variable product, so you need to update the `regular_price` inside each variation.
That's why it's not working.
