### ISSUE TITLE
[2.7] Order item meta data overwritten by another instance of object without data set

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#13533]
## EXPLANATION OF THE ISSUE

Some `WC_Data` objects delete meta data set in the database but not set on the instance of the object. Or to put it another way, when a `WC_Data` object's `save()` method is called, it appears for some objects to overwrite all other data.

I've been able to reproduce this with order items. It doesn't occur with orders. That leads me to suspect it may relate to the data store.

This may be by design, to make sure the saved version of the object is identical to the instantiated version after saving it, but it leads to some major potential issues when data is set in:

1. a function which does not take the current instance of the object as a method
1. a callback on a hook which passes just the object ID, which was very common with pre-CRUD code

It's quite hard to explain the issue, it may be easiest to review some code to reproduce it here: https://gist.github.com/thenbrent/28195bcbc739afda622f8792febf3bf5#file-wc-27-crud-overwrite-demo-php

I've tried to comment that sufficiently to explain what's happening.

I also included example log entries on that gist:

1. one for order items where the additional meta data disappears ([example log](https://gist.github.com/thenbrent/28195bcbc739afda622f8792febf3bf5#file-example-log-output-for-order-items-txt))
1. one for orders, where the additional meta data persists ([example log](https://gist.github.com/thenbrent/28195bcbc739afda622f8792febf3bf5#file-example-log-output-for-order-txt))

Given I'm seeing this with order item meta but not orders, I thought this may be related to #13532, so I tested with both current `master` and `fix/order-item-meta-cache` branch. The log entries offer the same result.

I haven't tested with products, coupons or other `WC_Data` objects either.

## STEPS TO REPRODUCE THE ISSUE

1. Download this gist: https://gist.github.com/thenbrent/28195bcbc739afda622f8792febf3bf5
1. Install as a WP plugin
1. Change the `EG_ITEM_ID` & `EG_ORDER_ID` constants to be valid order item and order IDs
1. Load a page
1. Review the error log
1. Notice that the meta data `'random_other'` and `'random_other_pre_crud'` meta data disappears from the order item's meta
1. Uncomment [this line](https://gist.github.com/thenbrent/28195bcbc739afda622f8792febf3bf5#file-wc-27-crud-overwrite-demo-php-L142) and comment out [this line](https://gist.github.com/thenbrent/28195bcbc739afda622f8792febf3bf5#file-wc-27-crud-overwrite-demo-php-L90)
1. Repeat steps 4 & 5
1. Notice that the meta data `'random_other'` and `'random_other_pre_crud'` meta data _still exists_ in the order meta

Props @crodas for discovering the issue.

**Comment by mikejolley** [comment]
@thenbrent there is a logic error in the gist. 

https://gist.github.com/thenbrent/28195bcbc739afda622f8792febf3bf5#file-wc-27-crud-overwrite-demo-php-L85

This is not using the `$new_item`. This may be the problem, but to be sure I'm converting your code into a runnable unit test.

**Comment by thenbrent** [comment]
> This is not using the $new_item. This may be the problem

🤦‍♂️ 

I chatted to @Crodas about the original issue to see if it existed, but that was a combination of misunderstanding whether the same piece of data should be overwritten in a separate request (it makes sense that it should be) and that `add_meta_data()` allowed multiple keys by default instead of updating an existing one (he was [testing with `get_meta()`](https://gist.github.com/crodas/c9a86df3b46c7e6094c286e9aae70fed#file-demo-php-L44) instead of `get_meta_data()` and seeing the same old key).

I'll close this now as I think it's a false report. Sorry for the trouble!
