### ISSUE TITLE
REST API: batch create products returns empty response.

### ISSUE THREAD

**Issue by maximumver** [woocommerce/woocommerce#13540]
## EXPLANATION OF THE ISSUE

I had this issue on latest stable version from WP plugin storage.
Then i've installed latest RC WC version and still got this problem.

I do import large amount of products via batch create.
Products are created! but i got no response.
I need that response really bad in order to build id map.
I've checked memory usage, it seems to be ok.

WP_DEBUG log is clean.
Server logs too.

Where i'm failing guys?

## STEPS TO REPRODUCE THE ISSUE

code i use to do requests(i don't actually keeping it alive, for now i am just trying to get it work):

`    public static function HTTP_REQUEST_KEEP_ALIVE(
      $con, $site_url, $consumer_key, $consumer_secret, $endpoint, $json = true, $method = 'GET', $data = []
    ) {
      if (function_exists('curl_init'))
      {
        $url = $site_url . '/wp-json/wc/v1/';

        $headers = [
          'Accept: application/json',
          'Content-Type: application/json;charset=utf-8'
        ];

        $params = http_build_query([
          'consumer_key'    => $consumer_key,
          'consumer_secret' => $consumer_secret
        ]);

        $url .= $endpoint . '?' . $params;

        $body = !empty($data) ? json_encode($data) : '';

        $is_custom_request = in_array($method, ['PUT', 'DELETE', 'OPTIONS']) ? 1 : 0;

        curl_setopt($con, CURLOPT_URL, $url);
        curl_setopt($con, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($con, CURLOPT_POSTFIELDS, !empty($body) ? $body : '');
        curl_setopt(
          $con,
          $is_custom_request ? CURLOPT_CUSTOMREQUEST : CURLOPT_POST,
          $is_custom_request ? $method : ($method == 'POST' ? 1 : 0)
        );
        curl_setopt($con, CURLOPT_HEADER, false);
        curl_setopt($con, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($con, CURLOPT_SSL_VERIFYPEER, true); 
        curl_setopt($con, CURLOPT_SSL_VERIFYHOST, true);
        curl_setopt($con, CURLOPT_CONNECTTIMEOUT, 30);
        curl_setopt($con, CURLOPT_TIMEOUT, 30);

        $res_curl = $json ? curl_exec($con) : json_decode(curl_exec($con)); // execution, load page

        return $res_curl;
      }

      else
      {
        return false;
      }
    }`

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.24
PHP Post Max Size: 256 MB
PHP Time Limit: 720
PHP Max Input Vars: 10000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ 
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Query Monitor: by John Blackbourn – 2.13.3
JSON Basic Authentication: by WordPress API Team – 0.1
WooCommerce: by Automattic – 2.7.0-RC1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – 

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
I'd guess the issue is in your actual code - it could be invalid JSON due to a notice however.

I'd recommend testing the same call in an API client such as postman or Insomnia. Then you can see if the issue is related to your code :) No issues my side. 

![2017-03-10 at 12 53](https://cloud.githubusercontent.com/assets/90977/23796050/9d0abb14-0590-11e7-9ded-b7a720258a3b.png)
