### ISSUE TITLE
Order objects now always in status transition after #13530

### ISSUE THREAD

**Issue by JDGrimes** [woocommerce/woocommerce#13552]
## EXPLANATION OF THE ISSUE

I have found a new bug in `master` introduced by #13530, I was able to track it down to 9427eb048d3e6055ef1a58fb093a9908015cbd00 specifically. This issue was brought to my attention by some unit tests for a plugin integrating with WooCommerce, when those tests suddenly started failing today.

The crux of the problem is that order objects now always believe that they are in a state of status transition after they have been given a status other than pending. 

Specifically, my code was doing this:

```php
		$order = WC_Helper_Order::create_order( $this->factory->user->create() );

		$order->payment_complete();

		$order->update_status( 'completed' );
```

Then later elsewhere, it was retrieving the order as you normally would:

```php
		$order = wc_get_order( $order_id );
```

In the first bit of code, the order status has been transitioned from `pending` to `completed`. There are two steps to the transition performed by `update_status()`: 

1. The new status is set with `set_status()`, which causes the `$status_transition` property to be set.
2. Then, the order is `save()`'ed which causes `status_transition()` to fir the actions that need to be fired, based on the value of the `$status_transition` property. The property value is then set to `false`, to signal that the status transition has been completed.

The value of the status in the database is now `completed`, and the value returned by the order object in the first bit of code will be `completed`, and  the `$status_transition` property will be `false`.

*However*, it is the second bit of code where things get interesting. Whenever we come back and retrieve that same order again, the `$status_transition` property will be set. This is because when the value is read from the database and the `set_status()` method is called to set the status, after 9427eb048d3e6055ef1a58fb093a9908015cbd00 the order will now believe that it is in transition. It thinks this because within `WC_Order::set_status()`, the `parent::set_status()` is called, which will get the existing status with `get_status()`. *But*, the status has not been set yet, because it is just now being initially set to the value that is read from the database. The code is therefore designed not to detect a status transition when the old status is empty. But since 9427eb048d3e6055ef1a58fb093a9908015cbd00, the status returned by `get_status()` is no longer empty in this case, it is `pending`. Which causes the `status_transition` property to be set up as if the order object is actually in the process of being transitioned from `pending` to `completed`, even though it is actually already `completed`.

This was causing me issues when I was trying to transition the status again a little later in the code. Because the order object thought that it was in transition from `pending`, `status_transition()` was triggering the actions for a transition from `pending`, instead of from `completed`. This caused my code that previously worked find to begin failing, and I pulled out a lot of hair trying to find the problem. :-)

## STEPS TO REPRODUCE THE ISSUE

- Create an order.
- Transition the status to something other than `pending`, like `completed`.
- Retrieve the same order again.
- Transition the status again to something else.

The result will be that the status is transitions from `pending` instead of from `completed`.

Admittedly, this isn't a flow that is as likely in production code as it is in tests, but the bug might end up causing other production issues as well.

**Comment by mikejolley** [comment]
This was resolved in https://github.com/woocommerce/woocommerce/pull/13550
