### ISSUE TITLE
PayPal Issue

### ISSUE THREAD

**Issue by madhousematers** [woocommerce/woocommerce#13553]
people can not check out using PayPal through Woocommerce. They get an error saying username and password is incorrect when that's not true. Several people have tried and received same error. I even tried myself and received the same error so it doesn't allow me to make the purchase.

Add a product to your cart, checkout via PayPal.

**Comment by claudiosanches** [comment]
Tested now and works just fine.

**Comment by mikejolley** [comment]
There is no issue; ensure you don't have sandbox enabled. Thats for testing accounts only.
