### ISSUE TITLE
WC_Order_Item::get_formatted_meta_data doesn’t handle meta values that are arrays correctly

### ISSUE THREAD

**Issue by lhopkins** [woocommerce/woocommerce#13556]
## EXPLANATION OF THE ISSUE

In **Version 2.7.0-RC1**, `WC_Order_Item::get_formatted_meta_data()` assumes all meta values are strings (`line 195`), or serialized arrays (`line 190`), yet `WC_Data::read_meta_data()` unserializes serialized arrays. Thus, an array stored as order item meta will always be passed as an unserialized array, resulting in a PHP array to string conversion notice on `line 195`.

I would expect `WC_Order_Item::get_formatted_meta_data()` to also check `is_array()` on the meta value on `line 190`. The `is_serialized()` check also seems unnecessary as `WC_Data::read_meta_data()` has already unserialized the meta values.

## STEPS TO REPRODUCE THE ISSUE

1. Add/update order item meta using `wc_add_order_item_meta()` or `wc_update_order_item_meta()` with an array as the value.
2. Call `WC_Order_Item::get_formatted_meta_data()` on that order item object. Will result in PHP array to string conversion notice.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://stringking.dev
Site URL: http://stringking.dev
WC Version: 2.7.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.0
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.7.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.10
StringKing Theme Support: by StringKing – 1.0
WooCommerce Additional Variation Images: by WooCommerce – 1.7.4
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5.1
WooCommerce Stripe Gateway: by WooCommerce – 3.0.7
WooCommerce: by Automattic – 2.7.0-RC1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WP Migrate DB Pro: by Delicious Brains – 1.7.1
WP SendGrid: by Will Anderson – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #7 - /store/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /account/

### Theme ###

Name: StringKing
Version: 1.0
Author URL: http://lhopkins.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: stringking/woocommerce/archive-product.php
stringking/woocommerce/cart/cart-empty.php
stringking/woocommerce/cart/cart-shipping.php
stringking/woocommerce/cart/cart-totals.php
stringking/woocommerce/cart/cart.php
stringking/woocommerce/cart/proceed-to-checkout-button.php
stringking/woocommerce/checkout/form-billing.php
stringking/woocommerce/checkout/form-checkout.php
stringking/woocommerce/checkout/form-coupon.php
stringking/woocommerce/checkout/form-shipping.php
stringking/woocommerce/checkout/payment-method.php
stringking/woocommerce/checkout/payment.php
stringking/woocommerce/checkout/review-order.php
stringking/woocommerce/checkout/thankyou.php
stringking/woocommerce/content-product.php
stringking/woocommerce/content-single-product.php
stringking/woocommerce/emails/customer-completed-order.php
stringking/woocommerce/emails/email-order-items.php
stringking/woocommerce/global/form-login.php
stringking/woocommerce/global/quantity-input.php
stringking/woocommerce/loop/no-products-found.php
stringking/woocommerce/myaccount/dashboard.php
stringking/woocommerce/myaccount/form-edit-account.php
stringking/woocommerce/myaccount/form-edit-address.php
stringking/woocommerce/myaccount/form-login.php
stringking/woocommerce/myaccount/form-lost-password.php
stringking/woocommerce/myaccount/form-reset-password.php
stringking/woocommerce/myaccount/lost-password-confirmation.php
stringking/woocommerce/myaccount/my-account.php
stringking/woocommerce/myaccount/my-address.php
stringking/woocommerce/myaccount/my-orders.php
stringking/woocommerce/myaccount/payment-methods.php
stringking/woocommerce/myaccount/view-order.php
stringking/woocommerce/notices/error.php
stringking/woocommerce/notices/success.php
stringking/woocommerce/order/order-details-customer.php
stringking/woocommerce/order/order-details-item.php
stringking/woocommerce/order/order-details.php
stringking/woocommerce/single-product/add-to-cart/simple.php
stringking/woocommerce/single-product/add-to-cart/variable.php
stringking/woocommerce/single-product/price.php
stringking/woocommerce/single-product.php
stringking/woocommerce/taxonomy-product_cat.php
`

**Comment by unfulvio** [comment]
I too noticed this issue when working at Local Pickup Plus compatibility. Seems like past orders who had some item meta set as an array now they are all producing an array to string conversion PHP error.
