### ISSUE TITLE
REST api error: 401 Unauthorized

### ISSUE THREAD

**Issue by ddhara** [woocommerce/woocommerce#13559]
Hello,

I am using Woocommerce REST api for android app but getting

`{"errors":[{"code":"woocommerce_api_authentication_error","message":"Invalid Signature - provided signature does not match"}]}`

I have tried many different libraries in android but facing same issue.

I tried `PHP Client Library` provided in `REST api Documnets` and it's working good and getting all products, orders etc.

Can you please suggest us that what we missing?

**Comment by mikejolley** [comment]
Do it over https instead and see http://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-https

**Comment by ddhara** [comment]
SSL is not enabled in my server.

**Comment by mikejolley** [comment]
Then you need to follow the instructions to generate a valid signature.
