### ISSUE TITLE
[Feature Request] "meta_data" support for line_items via REST

### ISSUE THREAD

**Issue by larssn** [woocommerce/woocommerce#13569]
## EXPLANATION OF THE ISSUE
Feature request, not an issue.

So I see there's support for meta_data on created orders, as long as it is primitives.
I'd like to request the same be possible for line_items.

There are no actions or filters for incoming orders via REST, in regards to line_items.

**Comment by mikejolley** [comment]
Part of the next major release.

**Comment by suruchibabbar1** [comment]
https://stackoverflow.com/questions/47266013/woocommerce-rest-api-issue-unable-to-add-order-item-meta-data


kindly help me with this query.

**Comment by suruchibabbar1** [comment]
@mikejolley

**Comment by suruchibabbar1** [comment]
@larssn

**Comment by themevan** [comment]
Does this feature available in WooCommerce 3.0+?
I just want to add the product featured image to each item in line_items.
