### ISSUE TITLE
PRODUCT APPEAR IN STOCK BUT VARIATIONS ARE UNAVAILABLE TO SELL

### ISSUE THREAD

**Issue by LONGUETU** [woocommerce/woocommerce#13563]
## EXPLANATION OF THE ISSUE

Product variations appear to be unavailable

## STEPS TO REPRODUCE THE ISSUE

TESTED WITH ALL COMBINAISONS OF POSSIBLE OPTIONS

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://xn--rencontresdumasculinsacr-yfc.com
Site URL: http://xn--rencontresdumasculinsacr-yfc.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.15
PHP Post Max Size: 64 MB
PHP Time Limit: 0
PHP Max Input Vars: 16000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ La base de données GeoIP MaxMind n’existe pas - La géolocalisation ne fonctionnera pas. Vous pouvez la télécharger et l’installer manuellement depuis http://dev.maxmind.com/geoip/legacy/geolite/ dans ce chemin : . Faites défiler vers le bas jusqu’à \"Downloads\" et téléchargez le fichier \"Binary / gzip\" à coté de \"GeoLite Country\"

### Active Plugins (8) ###

LayerSlider WP: par Kreatura Media – 6.1.6
Artbees Themes Captcha: par Jose Rodriguez  – 1.0
WPBakery Visual Composer (Modified Version): par Michael M - WPBakery.com – 5.0.2
Master Slider Pro: par averta – 3.1.1
Slider Revolution: par ThemePunch – 5.3.1.5
Site maintenance mode: par Nikolay Samoylov – 0.1.3
WooCommerce: par WooThemes – 2.6.14
Importateur WordPress: par wordpressdotorg – 0.6.3

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Base Boutique: #10455 - /boutique/
Panier: #10456 - /panier/
Commande: #10457 - /commande/
Mon Compte: #10458 - /mon-compte/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Jupiter
Version: 5.7
Author URL: http://themeforest.net/user/artbees
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: jupiter/woocommerce/archive-product.php
jupiter/woocommerce/cart/cart-empty.php
jupiter/woocommerce/cart/cart.php
jupiter/woocommerce/cart/mini-cart.php
jupiter/woocommerce/cart/shipping-calculator.php
jupiter/woocommerce/checkout/cart-errors.php
jupiter/woocommerce/checkout/form-coupon.php
jupiter/woocommerce/checkout/review-order.php
jupiter/woocommerce/content-product.php
jupiter/woocommerce/content-product_cat.php
jupiter/woocommerce/content-single-product.php
jupiter/woocommerce/global/form-login.php
jupiter/woocommerce/global/quantity-input.php
jupiter/woocommerce/loop/add-to-cart.php
jupiter/woocommerce/loop/loop-end.php
jupiter/woocommerce/loop/loop-start.php
jupiter/woocommerce/loop/no-products-found.php
jupiter/woocommerce/loop/orderby.php
jupiter/woocommerce/loop/pagination.php
jupiter/woocommerce/loop/price.php
jupiter/woocommerce/loop/rating.php
jupiter/woocommerce/loop/result-count.php
jupiter/woocommerce/loop/sale-flash.php
jupiter/woocommerce/myaccount/form-edit-account.php
jupiter/woocommerce/myaccount/form-edit-address.php
jupiter/woocommerce/myaccount/form-login.php
jupiter/woocommerce/myaccount/form-lost-password.php
jupiter/woocommerce/notices/error.php
jupiter/woocommerce/notices/notice.php
jupiter/woocommerce/notices/success.php
jupiter/woocommerce/order/form-tracking.php
jupiter/woocommerce/single-product/add-to-cart/external.php
jupiter/woocommerce/single-product/add-to-cart/grouped.php
jupiter/woocommerce/single-product/add-to-cart/simple.php
jupiter/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
jupiter/woocommerce/single-product/meta.php
jupiter/woocommerce/single-product/price.php
jupiter/woocommerce/single-product/product-image.php
jupiter/woocommerce/single-product/product-thumbnails.php
jupiter/woocommerce/single-product/rating.php
jupiter/woocommerce/single-product/related.php
jupiter/woocommerce/single-product/sale-flash.php
jupiter/woocommerce/single-product/share.php
jupiter/woocommerce/single-product/short-description.php
jupiter/woocommerce/single-product/tabs/additional-information.php
jupiter/woocommerce/single-product/tabs/description.php
jupiter/woocommerce/single-product/tabs/tabs.php
jupiter/woocommerce/single-product/title.php
jupiter/woocommerce/single-product/up-sells.php

`

**Comment by mikejolley** [comment]
Usually due to either overlapping options with missing data, or missing regular prices. Check that and save the product again. If there is a missing price, the variation will be unavailable.

This is not a support forum however, so please see https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md for future reference.
