### ISSUE TITLE
Blank checkout and cart pages on RTL languages in chrome android, until scrolled

### ISSUE THREAD

**Issue by talburi** [woocommerce/woocommerce#13561]
checkout and cart pages are blank, until touching the screen to scroll down the page.  the issue is not consistent (happens 20-30% of the times "proceed to checkout" or cart pages are clicked)
happens ONLY on:
1. wordpress, woocommerce and storefront on RTL mode, hebrew language (changing to left-to-right resolves the issue)
2. only on mobile android devices 
3. only on chrome (issue does not happen in firefox for android). was replicated on several different android phones and android versions. 
was replicated wordpress 4.7.3, woocommerce 2.6.14, storefront 2.1.8, all other plugins disabled
latest chrome for android version: 56.60.2924.87

steps to replicate:
1. add a product cart
2. go to cart
3. proceed to checkout
4. press back and jump between cart and checkout pages until a blank screen shows
I saw the issue discussed on #12170 in one of the comments.

**Comment by mikejolley** [comment]
This still happens for me with RTL tester in Chrome, backend WC section.

**Comment by claudiulodro** [comment]
I don't think this is specifically a WooCommerce problem. I can reproduce the problem on WP with no plugins other than RTL tester active. 

@talburi are you using the RTL Tester plugin for this, or is it a naturally RTL site?

**Comment by mikejolley** [comment]
I've just reproduced this with NO plugins (no WooCommerce) and an RTL language on http://local.wordpress.dev/wp-admin/nav-menus.php. Seems this is not a WC problem, but it's an odd one. Not sure what to suggest. I think it must be one of the jquery libraries (sortable? UI?).

**Comment by claudiulodro** [comment]
I've opened a ticket with WP trac: https://core.trac.wordpress.org/ticket/40147

**Comment by talburi** [comment]
the guys at wordpress core does not seem to have a solution. they suggest a workaround at http://stackoverflow.com/q/34184377/3507335 which I tried and doesn't work.
even if this is a WP issue, this can be a major bug for an RTL woocommerce store. chrome on android is a very large % of total traffic, and seeing a blank page on the checkout page can be very bad for conversion. mabye someone can suggest a workaround (snippet to do an automatic scroll on checkout / cart page) so those of us with RTL sites will have a solution?

**Comment by claudiosanches** [comment]
@talburi don't works because need to write the jQuery for WordPress:

```js
jQuery(document).ready(function($){
    $(window).load(function() {
        $( "body" ).animate({
            scrollTop: 1
        });
    });
});
```

**Comment by talburi** [comment]
@claudiulodro 
the code itself works (every page on the site is scrolled a bit) but that doesn't resolve the issue. mabye the "load" event is not good enough? or mabye the action of manual scrolling is not good enough?

**Comment by MMaKenZi** [comment]
Hi

I tested same situation, but it didn't happen for me

However I have a scrolling problem on checkout page when I tried to check terms and conditions checkbox
which I fixed by changing CSS code
but I couldn't reproduce problem discussed in this topic

**Comment by AmZaf** [comment]
@talburi  
I had a similar problem to yours with a Joomla template. My site showed fine until it was manually refreshed on Android phones, after which the page would go blank. 

First, I applied a fixed positioning rule to the body,

body { position: fixed; }

Then, I reverted the positioning on page load using jQuery,

jQuery(window).load(function() {
    jQuery('body').css('position','static');
 });
