### ISSUE TITLE
Is it possible to add custom note in cart page, per product?

### ISSUE THREAD

**Issue by z3cr3t** [woocommerce/woocommerce#13562]
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

Hello I would like to ask if how or is it possible to add custom note in the cart page? and can update the custom note in the cart page?

**Comment by faisal-alvi** [comment]
Hi, I want to ask have you tried to do what you have asked and check whether woocommerce provide such functionality or or not?

**Comment by mikejolley** [comment]
This is not a support forum, so please see https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md for future reference.
