### ISSUE TITLE
id-less meta added using WC_Order_Item->offsetSet() causes notices when rendered by WC_Order_Item::get_formatted_meta_data()

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#13578]
## EXPLANATION OF THE ISSUE

Observed with today's master.  If you do something like the following to set an order line item meta:

```
$items[ $item_id ]['line_subtotal_tax'] = $item_tax_subtotal;
```

then `WC_Order_Item_Product->offsetSet()` gets used to set the meta.  The meta that gets added by `WC_Data->add_meta_data()` has no `id`

Unfortunately, then when WC_Order_Item::get_formatted_meta_data renders the meta, you get notices for each meta thus added, like the following:

```
Notice: Undefined property: stdClass::$id in /Users/allendav/Sites/localhost/wc27_us/wp-content/plugins/woocommerce/includes/class-wc-order-item.php on line 215
```

<img width="811" alt="screen shot 2017-03-13 at 1 14 12 pm" src="https://cloud.githubusercontent.com/assets/1595739/23873376/11e9c35c-07ef-11e7-93f6-eba2e4acccc9.png">

## STEPS TO REPRODUCE THE ISSUE

* WP_DEBUG true
* Use `WC_Order_Item_Product->offsetSet()` to set `line_subtotal_tax`for a product order item
* Complete checkout

**Comment by bor0** [comment]
Investigation shows that we used to treat it as an array in 2.6:
```
                                $this->_meta_data[] = (object) array(
                                        'key'     => $meta->meta_key,
                                        'value'   => $meta->meta_value,
                                        'meta_id' => $meta->{ $db_info['meta_id_field'] },
                                );
```
(`meta_id` got later changed to `id`), but now it's a hash thus the issue.

I think it's safe to say that `meta_id` (`id`) was required even in 2.6, but it wasn't crashing if it wasn't supplied.
