### ISSUE TITLE
[3.0] Adding Order Item Meta from Checkout Values

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#13579]
## EXPLANATION OF THE ISSUE

In pre-~~2.7~~ 3.0 the `woocommerce_add_order_item_meta` hook could be used to add meta to order items. This hook [passed in the checkout values](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/class-wc-checkout.php#L247-L248) associated with an item as the order is created (and the cart item key if there's cart data you need to use). This made it very straight-forward to take checkout data and convert it to line item meta on the order object.

In WC ~~2.7~~ 3.0, this system has changed entirely with the migration to CRUD methods (along with other methods like `woocommerce_add_order_fee_meta` and `woocommerce_add_shipping_order_item`). All of these are deprecated in favor of `woocommerce_new_order_item`. 

However, the cart, checkout, or package information is lost with this hook since `woocommerce_new_order_item` is fired by all CRUD methods. Instead, devs need to retrieve it by other means; in this case, there's a `legacy` key added to the item with values here, but this indicates it will deprecated. If so, where are we going to retrieve this information and how do we set meta properly on the item? This is our biggest concern at present, as we don't know if this legacy data is safe to depend on.

In the case of packages for example, previously we just added the package key to the package array while filtering the packages themselves -- and, until ~~2.7~~ 3.0 we were expecting to retrieve this key in subsequent hooks in the checkout flow (like in `woocommerce_add_shipping_order_item`, by looking at the package index) -- we could look into the session for the matching key (same with fees). Now that key isn't available in the recommended new hook.

We've come up with some varied responses to what the ideal solution is on our team, so curious as to suggested behavior and future plans for handling line items 😸 

**Option 1**: This is the most promising one to us and what we've tended to use thus far. We've targeted `woocommerce_checkout_create_order_*_item` hooks as most promising, as these have access to the checkout values and the cart item key. Using this, you can set some proprietary property on the item, such as `$item->_sv_data = $checkout_data` -- then, use `woocommerce_new_order_item` to check if the `$item` has this property and use it.

However, this feels hack-y for a couple reasons.   
 1. You're attaching your own property the item object, and while it's unlikely it would override existing data, there's no guarantee it won't.
 2. The `woocommerce_checkout_create_order_*_item` hooks are fired before the order item is saved; this means that if your code has a need of the order item ID, this work around is not possible as the save methods haven't been triggered yet.
 3. Because the hook in which you set data isn't fired yet, you're not 100% guaranteed something after you doesn't mess up the item or save process, thereby losing your data. Saving it on the order item directly is a more fool-proof method of transferring your data since you're setting it on the _order_ record directly, not taking a gamble that your custom property makes it from cart item data to order item meta hopefully.

**Option 2**: Not possible, but a consideration:

 1. In `woocommerce_checkout_create_order_*_item`, set a property using `$item->set_prop()`
 2. in `woocommerce_new_order_item` do `$item->get_prop()`

However, the `set_prop()` method only works for hard-coded properties, not custom ones, so this is out.

**Option 3**: Adding item meta data directly

 1. in `woocommerce_checkout_create_order_*_item` hooks, set the item checkout values on the item with `$item->add_meta_data()`
 2. in `woocommerce_new_order_item` do `$item->get_meta_data()` to check if the checkout values are there

But this will persist the checkout data to the database before `woocommerce_new_order_item` is fired, and we were concerned with storing raw checkout data in the DB.

**Option 4**: Setters / getters for checkout values for an item

1. We could consider a method like `$item->set_checkout_values( $values );` 
2. and then a getter `$item->get_checkout_values()` paired with `$item->has_checkout_values()`
3. The first one would be called in core checkout class before doing `$order->add_item( $item )` and the getter could be used in the `woocommerce_new_order_item` hook

We're not 100% sure if this would help with packages though since we didn't test it with the shipping item hooks.

-----

Basically, the main issue comes down to a couple points:

 - To add order item meta from the cart / checkout values, you want a hook that has access to both the item and the values / cart key / fee key / etc.

   While the existing  `woocommerce_checkout_create_order_*_item` hooks have the values and the item, as this item hasn't been persisted to the DB yet, this can cause issues if you need access to the order item's ID, while also causing concerns about data persistence since the item hasn't been saved yet.

 - To add order item meta when the order / line item is already created the `woocommerce_new_order_item` hook is viable to use. However, you can't transfer data from a cart / checkout / session to this since those values are not available.

There's no sufficient hook for adding item meta from the cart while also being guaranteed it will be saved properly, accessible in the future, and will have the data your code needs to interact with the item.

Curious about plans for both the legacy values on the cart item and if there's insight we can gain here on which approach(es) would be the safest route for future. I think others like @thenbrent or @franticpsyx have likely wrangled with this as well since this data transfer from order -> checkout doesn't translate 1:1 from previous versions.

EDITED: fixed WC version ref

**Comment by mikejolley** [comment]
@bekarice Those legacy props are purely there for backwards compatibility, and yes, relying on them is not a good idea.

The hooks you mentioned are the replacement https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L371

They have access to cart.

Yes it's done before save. This is intentional. If you add meta using the CRUD objects WooCommerce will handle the save, and when possible WC will be able to do a bulk insert for performance (this has not shipped yet). Having no ID should be no problem if using the CRUD.

`$item` is passed by reference. Add or change whatever you want.

**Comment by franticpsyx** [comment]
I remember chatting about this with @mikejolley a few months ago -- the new hooks should be sufficient for transferring cart line/fee item data to the corresponding order item, as long as you don't need the ID of the yet-to-be-stored item.

You can add new meta on the object and these will be saved when the object is persisted.

However, if you want to do something that requires the order item ID, you may need to hook into a downstream action and use the data you already saved on the object -- or perhaps save early?

@bekarice -- do you have an example where you need the order item ID at the same time you want to copy cart/fee/pkg data into the object?

You will notice the same "limitation" with other hooks as well, e.g. `woocommerce_admin_process_product_object`.

**Comment by bekarice** [comment]
@mikejolley sorry looks like i mixed up some of the feedback we'd aggregated in Slack -- the Q about the checkout values was directed at the new order item hook (which is marked as the replacement in the deprecation notice), while the saving was a concern with the `create_order_*_item` hooks, so 2 separate concerns / areas there. However, I think you've answered that with:

> Yes it's done before save. This is intentional. ...

@franticpsyx we had use cases for it, but these can be worked around as you've outlined. One that comes to mind was checking cart values for PDF vouchers to see if a voucher record should be generated, then adding the order item meta for it if so. This requires the order item ID, so now instead we'd just need to separately set meta, then downstream check for this meta once we have an order item ID to generate the voucher from.

My major concern with having to set data before item save (and why were looking for any way to avoid it) is that I can very easily see the item object getting overwritten now that it's passed by reference to other code either: modifying the object improperly before it gets to us, getting rid of / overwriting our data downstream, or throwing an error that breaks the save process and loses data downstream before saving. Hook into `pre_get_posts` in an environment with lots of plugins using it and you'll get a feel for what can go wrong 😄  

I don't know that anything can / should change here later, was just hoping for a more direct way to add data to the order items than passing them into the existing stream to create our own moat around our plugin's data and save some potential troubleshooting headaches down the road.

**Comment by franticpsyx** [comment]
@bekarice I hear ya -- it's a similar situation with post meta though, isn't it? My point is that if we are talking about meta then overwriting/losing your data while it's still on the way to be saved is better than suffering the same thing at the database layer directly, because now at least you have a chance to know someone else is messing with your data.

Again if it's meta we are talking about, then using prefixed names "still" makes sense.

**Comment by mikejolley** [comment]
I think as Manos points out, whether it's before or after save makes little difference - any 3rd party code can change objects and edit data.

**Comment by SoLoGHoST** [comment]
I am seeing this deprecation as well, states "The "woocommerce_add_order_item_meta" hook uses out of date data structures and function is deprecated since version 3.0.8. Replace with woocommerce_new_order_item."  But I don't see anything online on how exactly to convert the variables from this hook into the new hook.  And doing research on this leaves me even more confused.  On another note, I realise you folks are trying to keep up with flexibility, but I've seen some of the most ridiculous changes in actions that make no sense at all.  Like changes in parameters that remove status text, or product ids from them.  Or even replacing a product id with a product name in a parameter from a hook, so that now, any plugins created have to be changed to reflect that.  But this change seems much more complicated than that to me.
