### ISSUE TITLE
[2.7] No replacement for woocommerce_get_shop_coupon_data hook

### ISSUE THREAD

**Issue by unfulvio** [woocommerce/woocommerce#13576]
## EXPLANATION OF THE ISSUE

WC 2.7 has deprecated `woocommerce_get_shop_coupon_data` hook https://github.com/woocommerce/woocommerce/blob/2.7.0-RC1/includes/class-wc-coupon.php#L86 but there's no direct replacement of it. 

This hook was used for example in Local Pickup Plus to generate a coupon code on the fly to apply a discount when shop customers select local pickup plus as shipping method.

However, as of WC 2.7, there's no way to dynamically generate a discount when in cart/checkout context. 

The deprecation warning says to pass an instance of WC_Coupon but you can't add a coupon class instance as a discount, you must pass a code. 

Since WC lacks of a discounts API, I can't see another way to create discounts dynamically. 

While looking for alternatives, we also considered using the shipping rate to set a discount since currently you can set a negative fee when adding a rate. While this is nice to have, it has a different behaviour, especially in regards of taxes: it's a fee applied on the shipping item and not on the whole cart / order line items, as a coupon would be.

I'd suggest to keep the ability to keep a negative shipping rate but I'd also recommend to reintroduce some mean to dynamically add discounts using coupons via action hook as `woocommerce_get_shop_coupon_data` allowed to.

**Comment by bekarice** [comment]
Points and Rewards seems to [use this hook as well](https://github.com/woocommerce/woocommerce-points-and-rewards/blob/master/includes/class-wc-points-rewards-discount.php#L31)

**Comment by mikejolley** [comment]
Please check master, it was undeprecated.
