### ISSUE TITLE
[3.0] Small bug on the checkout page

### ISSUE THREAD

**Issue by oceanwp** [woocommerce/woocommerce#13583]
## EXPLANATION OF THE ISSUE

Hello, I think I found a small bug in the checkout page, the divs with the "clear" class are at the top of the forms, so if you use a float, the "Company name" field overlap, look at the screenshot :
![screenshot](https://cloud.githubusercontent.com/assets/22959941/23879669/c70c5218-084e-11e7-949d-963b8f06afca.png)

## STEPS TO REPRODUCE THE ISSUE

Go to the checkout page and click on Inspect Element

**Comment by claudiosanches** [comment]
You don't should just use CSS on the Company field.
It's required to change the fields classes before, so will properly handle this kind of issues.

Here instructions to change: https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/

Example of code:

```php
function my_wc_custom_billing_fields( $fields ) {
	$fields['billing_company']['class'] = array( 'form-row-first' );

	return $fields;
}

add_filter( 'woocommerce_billing_fields', 'my_wc_custom_billing_fields' );
```

![screenshot from 2017-03-13 21-35-21](https://cloud.githubusercontent.com/assets/1264099/23880821/fa00bd90-0834-11e7-8a62-3ee6ede2d977.png)

**Comment by oceanwp** [comment]
Hi, thank you for your reply, I do not use css for the "Company name" field, I use a float left for the "first name" and "last name" fields and because the clear divs are in the wrong place company field overlap on the other fields.

**Comment by claudiosanches** [comment]
@oceanwp so you should change the first and last name fields, as I said and not the CSS.
Still by default we don't have any issue with HTML like you are saying, looks like some other change has been made in your store.

**Comment by oceanwp** [comment]
Ok but there is a problem with the divs clear, I just activated twenty seventeen and all the clear divs are at the top of the forms.

**Comment by claudiosanches** [comment]
@oceanwp with only WooCommerce activated?

**Comment by oceanwp** [comment]
Yes, I just disable all my other plugins and the problem is still present.

**Comment by claudiosanches** [comment]
@oceanwp sorry, it's really a bug.

@mikejolley missed it in the JS sorting.

**Comment by oceanwp** [comment]
No problem :)
And thanks to you because I found another way to solve my problem.

**Comment by mikejolley** [comment]
@oceanwp You need to use a clear left on the next field to prevent this - using clear divs is not recommend nor necessary.

**Comment by oceanwp** [comment]
Hi @mikejolley, yes my problem is fixed :)

**Comment by claudiosanches** [comment]
Solved in #13593

**Comment by currybun** [comment]
I'm having an issue with my site: https://honeycarrot.com/
On mobile only, the id="billing_company_field" overlaps the last name field so the user can't input their last name. I tried deactivating plugins and my theme does not overwrite the woocommerce checkout template.

**Comment by currybun** [comment]
![screen shot 2017-11-29 at 7 03 03 am](https://user-images.githubusercontent.com/22899039/33375843-45394798-d4d9-11e7-9f6a-baa158e42358.png)

**Comment by currybun** [comment]
I'm running WC 3.2.5 on WP 4.9 Theme is Weston

**Comment by currybun** [comment]
Thanks, we already found the issue – The WooCommerce Paypal plugin (to do paypal express checkout) was the reason why the divs were overlapping. After deactivating the plugin the form worked properly in mobile.
