### ISSUE TITLE
[3.0] Default return values for WC_Data:get_meta()

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#13581]
A very small issue: when no meta value is found, the `WC_Data:get_meta()` returns:

1. an empty string (i.e. `''`) if `$single` is `true`
2. an empty array (i.e. `array()`) if `$single` is `false`

With these return values, I can't see a way to determine if they were returned because that is the value set in the object's meta, or because no meta exists other than manually checking if the meta key is in the array of objects returned by `WC_Data::get_meta_data()`. This makes it difficult to determine whether to use a default value or not when the allowed set of expected return values isn't known.

For example, if we want to create a generic wrapper to get meta data from a product, we could create a method something like this:

```
/**
 * Get a piece of product meta data in a version compatible way.
 *
 * @param WC_Product $product
 * @param string $meta_key The string key for the meta data
 * @param mixed $default The value to return if the meta does not exist
 * @return float The value of the meta data
 */
function eg_get_meta_data( $product, $meta_key, $default_value ) {

	$meta_value = $default_value;

	if ( is_callable( array( $product, 'get_meta' ) ) ) { // WC 2.7+
		$meta_value = $product->get_meta( '_' . $meta_key, true );
		// WC_Data::get_meta() will return an empty string as the default value, but sometimes
		if ( '' === $meta_value && '' !== $default_value ) {
			$meta_value = $default_value; // Or should it be left unchanged because the value is actually ''?
		}

	} elseif ( isset( $product->{$meta_key} ) ) { // WC < 2.7
		$meta_value = $product->{$meta_key};
	}

	return $meta_value;
}
```

As per the inline comment, the trouble with that code is we don't know whether to set `$meta_value` to the default value or whether the `''` value is the current value of the meta data.

This could be addressed in the above function with an additional param specifying set of allowable return values, but I suspect there will be other examples where this causes issues.

### Possible Solutions

It's probably too late to change the default return values to use `null`, similar to `get_prop()`, and I'm not sure how to handle the case of `$single === false` with that anyway, so some other possible solutions:

1. add a new `WC_Data::has_meta( $meta_key )` method, which is just a convenience wrapper for `array_key_exists( $meta_key, $this->meta_data )`
1. add a new `WC_Data::get_meta_keys()` method similar to the existing `WC_Data::get_data_keys()` and `WC_Data::get_extra_data_keys()` methods, again, just a convenience wrapper for `array_keys( $this->meta_data )`
1. tell people to quit bellyaching and work with what they got - `in_array( $meta_key, wp_list_pluck( $product->get_meta_data(), 'key' ) )`. 🙂 

Related to #13449 / #13427 (I wish I identified it when reporting #13427).

**Comment by claudiosanches** [comment]
We are doing like WordPress `get_post_meta()` since it uses this function, see:

```php
wp shell
wp> get_post_meta( 1, '_foo_bar_12312312', true )
=> string(0) ""
wp> get_post_meta( 1, '_foo_bar_12312312', false )
=> array(0) {
}
```

> It's probably too late to change the default return values to use null

Maybe, but don't need to be a big change.
We could just include more one argument or use the `$content` as `edit` to return null if doesn't exist.

Still I prefer the idea of `WC_Data::has_meta( $meta_key )`.

**Comment by thenbrent** [comment]
> We are doing like WordPress get_post_meta() since it uses this function

Ah yes, that's right. That's good to keep it consistent.

> Still I prefer the idea of WC_Data::has_meta( $meta_key ).

Same. WP provides the `metadata_exists()` method, which is what you would use in this situation, so adding `WC_Data::has_meta()` is equivalent (it could also be named `WC_Data::meta_exists()`).
