### ISSUE TITLE
Address can NOT contain letters "curl" - checkout breaks

### ISSUE THREAD

**Issue by Polinet** [woocommerce/woocommerce#13588]
## EXPLANATION OF THE ISSUE

WC Version:		2.6.14
WP Version:		4.7.2
Standard Shipping zomes > flat rate shipping method.

When someone enters letters "curl" into address fields checkout breaks with server error 403:
Failed to load resource: the server responded with a status of 403 (): https://www.kidslifestyle.com.au/checkout/?wc-ajax=update_order_review

Tested by entering into fields address 1 and suburb.

In Australia there is a suburb called "Curl Curl" so customer from that suburb can not checkout without modifying the suburb name to by pass this bug.

I expect that the system should allow entering of ANYTHING into the address fields even if its code word "cURL".

## STEPS TO REPRODUCE THE ISSUE

Define at least one shipping zone and choose Flat rate shipping method for it. Make it taxable.
Go to front end and put anything into cart.
Go to checkout and enter curl into address or suburb field. If "ship to different address is ticked" put it into shipping address. If not ticked put it into billing address.
Checkout total and payment method on the left completely hangs with a white semin transparent box over it. Console shows an error stated above.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: http://www.kidslifestyle.com.au
Site URL: http://www.kidslifestyle.com.au
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 100 MB
PHP Time Limit: 900
PHP Max Input Vars: 5000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (36) ###

Akismet: by Automattic – 3.2
Contact Form 7 - Campaign Monitor Addon: by Joshua Bettigole – 1.06
Contact Form 7: by Takayuki Miyoshi – 4.6.1
Disable WordPress Core Update Email: by Alex Moss – 1.0
Google Tag Manager for Wordpress: by Thomas Geiger – 1.5.1
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
Envato WordPress Toolkit: by Envato – 1.7.3
eWAY Payment Gateway: by WebAware – 3.7.0
EWWW Image Optimizer: by Shane Bishop – 3.2.6
Media from FTP: by Katsushi Kawamori – 9.61
Fix Media Library Plus Folders: by Max Foundry – 3.2.2
Media Library Plus: by Max Foundry – 3.2.2
Media Library Plus Reset: by Max Foundry – 3.2.2
Nextend Facebook Connect: by Roland Soos – 1.5.9
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

PW WooCommerce Bulk Edit: by Pimwick
LLC – 1.26

Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Say What?: by Lee Willis – 1.9.0
Smart Reporter for e-commerce: by StoreApps – 2.9.16
Ultimate Category Excluder: by Marios Alexandrou – 1.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.32

Wholesale Market: by CedCommerce  – 2.0.4
Woocommerce Campaign Monitor Signup: by Danyo Borg – 1.2
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.10 – 1.10.12 is available
WooCommerce Wholesale Prices: by Rymera Web Co – 1.2.10
WooCommerce: by WooThemes – 2.6.14
WooSidebars: by WooThemes – 1.4.3
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.3
WP Instagram Widget: by Scott Evans – 1.9.8
YITH Infinite Scrolling: by YITHEMES – 1.0.7
YITH WooCommerce Ajax Search: by YITHEMES – 1.4.1
YITH WooCommerce Brands Add-on: by Yithemes – 1.0.8
YITH WooCommerce Bulk Product Editing: by YITHEMES – 1.1.0
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page not set
Basket: #11 - /cart/
Checkout: #12 - /checkout/
My Account: #13 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome Child Theme
Version: 2.5
Author URL: http:%20//www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.2.5
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome-child/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome-child/woocommerce/emails/customer-new-account.php
flatsome-child/woocommerce/emails/customer-processing-order.php
flatsome-child/woocommerce/emails/email-order-details.php
flatsome-child/woocommerce/emails/email-styles.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
This is a mod security rule on your hosting not allowing certain strings to be posted. Contact the hosting provider.
