### ISSUE TITLE
Create a new product by api

### ISSUE THREAD

**Issue by devahernandez** [woocommerce/woocommerce#13597]
Hi guys I am consuming the api of woocommerce in WordPress and I had a problem when creating a new product through the api.
I'm using the woocommerce api v2

Api [post]
Wordpress.com/wc-api/v2/products

This is the error i get
{
   "Errors": [
     {
       "Code": "woocommerce_api_authentication_error",
       "Message": "Invalid Signature - provided signature does not match"
     }
   ]
}
this are the arguments 
/wc-api/v1/products?oauth_consumer_key=xxxxxx
&oauth_token=xxxxx
&oauth_signature_method=HMAC-SHA1
&oauth_timestamp=xxxx
&oauth_nonce=DpfyUy+
&oauth_version=1.0
&oauth_signature=xxxxxxx=
* I have enabled writing and reading mode in woocommerce
Maybe they can advise me thanks.

**Comment by mikejolley** [comment]
Signature generation requires a few things such as alphabetical args before the hash is calculated. it's covered here http://woocommerce.github.io/woocommerce-rest-api-docs/#authentication

You can avoid it by using HTTPS which is better for many reasons, security being one.
