### ISSUE TITLE
Custom Coupons using the 'woocommerce_get_shop_coupon_data' hook don't exist

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce#13599]
## EXPLANATION OF THE ISSUE

Custom coupons added to the cart by third party plugins which use the `woocommerce_get_shop_coupon_data` hook don't "exist". 

## STEPS TO REPRODUCE THE ISSUE

I've written a mini plugin you can use for testing. You can find it here: https://gist.github.com/james-allan/d1d39af1b8012cc2bfdfe284e4c28f7c

The plugin is a pretty basic example -- all it does is apply a coupon when any product is added to the cart.

**WC 2.6.14**

![screen shot 2017-03-15 at 10 13 36 am](https://cloud.githubusercontent.com/assets/8490476/23927861/18de63dc-0968-11e7-83ad-55165d9934eb.png)

**WC `master` branch**

![screen shot 2017-03-15 at 10 10 33 am](https://cloud.githubusercontent.com/assets/8490476/23927796/b0c3d96c-0967-11e7-8294-1cfe0078fe07.png)

The issue seems to be that prior to WC 3.0, a coupon created via the `woocommerce_get_shop_coupon_data` hook set the `exists` property to true ([here](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/class-wc-coupon.php#L129-L132) and [here](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/class-wc-coupon.php#L73)). However, in 3.0 `exists` is now determined if the coupon has an ID.

If you want these type of plugins to go down the route of storing these coupons in the database then there will be other changes needed because these coupons don't have a `data_store` (the constructor exits before the datastore is set ([here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-coupon.php#L87)) and so cannot be saved/created/updated). Preferably these coupons could bypass the exists check or have another workaround which honours how they use to work in the past.

I'm open to alternatives/workarounds if you've got them 😃

**Comment by unfulvio** [comment]
try passing `id => true` to `$data` returned to filter

**Comment by james-allan** [comment]
@unfulvio that's worked. Thanks heaps for the tip. 😄 

I'll close this one now.
