### ISSUE TITLE
Checkout Fields / Adress Fields Filter

### ISSUE THREAD

**Issue by mbgrafik** [woocommerce/woocommerce#13603]
## EXPLANATION OF THE ISSUE

There are filters to customize checkout and adress fields. I need to add a simple extra class to those fields and need to use this filter "woocommerce_default_address_fields" since this "woocommerce_checkout_fields" won't work in the My-Account Section . 

But in the Edit-Billing-Adress Section (My-Account -> Adresses -> Edit Billing Adress" two more fields are available "Phone" and "E-Mail" those fields should be available to filter too, but they are not.

"In specific cases you need to use the woocommerce_default_address_fields filter. This filter is applied to all billing and shipping default fields:

    country
    first_name
    last_name
    company
    address_1
    address_2
    city
    state
    postcode
"
So to me it would make sense to add "phone" and "email" to the woocommerce_default_address_fields filter.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/3f7c1c708740f3e5b7f87499c161ef570fa8a59c/includes/class-wc-countries.php#L1104

**Comment by mbgrafik** [comment]
Oh sorry :(
