### ISSUE TITLE
New Tax Class import data incorrectly are all put into the  

### ISSUE THREAD

**Issue by client-site** [woocommerce/woocommerce#13617]
This bug occurs while I am following one of the WooCommerce Getting Start Video:

https://docs.woocommerce.com/document/setting-up-eu-vat-rates-for-digital-products/

*The bug occurs when I am importing the - Here are the above rates in CSV format: tax_rates.csv

All the imported rows went to the Standard Rates instead of the newly created Digit Good Rates.

**Comment by mikejolley** [comment]
The tax class name in the CSV does not match the tax class name in the instructions. They need to be to same. I'll report to docs team.

**Comment by client-site** [comment]
So, if I added 'Digital Goods' in the Additional Tax Classes text box on Tax Options sub-tab, then what is the name of the intended importing csv file should on its Rates sub-tab.

I am asking what is the nomenclature naming convention for the csv filename which will be parsed correctly into the corresponding Rates sub-tab.

**Comment by mikejolley** [comment]
The values in the CSV I believe should be `Digital Goods` so it matches the name you entered.
