### ISSUE TITLE
WooCommerce 2.6.14 - Responsive Styles

### ISSUE THREAD

**Issue by CDMVladimir** [woocommerce/woocommerce#13610]
## EXPLANATION OF THE ISSUE
When using bundler / minifier, responsive styles are lost because of the media query that is on "link"tag.

## Reproduce
To reproduce the issue use and bundler / minifer (we used W3 Total Cache), and look at the pages on responsive.

## Solution
Please take a look at the screenshot:
http://oi65.tinypic.com/a5hi7r.jpg

**Comment by mikejolley** [comment]
Exclude them; this cannot be worked around in code.
