### ISSUE TITLE
API authentication Error - PLUS character in signature

### ISSUE THREAD

**Issue by emajkl** [woocommerce/woocommerce#13615]
## EXPLANATION OF THE ISSUE
Authentication over HTTP - if generated signature contains PLUS character you get error.
e.g. my generated signature is:
9VBDNzMeOE4vyoo/J2QPrmoFjQi6unBLmJWKlb4+NhU=

but in
woocommerce/includes/api/class-wc-rest-authentication.php

$consumer_signature is 
9VBDNzMeOE4vyoo/J2QPrmoFjQi6unBLmJWKlb4 NhU=

(PLUS characters are replaced with spaces)

## SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://www.velkyvoci.cz/bar
Site URL: http://www.velkyvoci.cz/bar
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: cs_CZ

### Server Environment ###

Server Info: Apache/2.2.22 (Debian)
PHP Version: ❌ 5.4.45-0+deb7u7 - Doporučujeme PHP minimálně ve verzi 5.6. Více: Jak aktualizovat verzi PHP
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - Minimální doporučená verze MYSQL je 5.6. Více: Požadavky Wordpressu
Max Upload Size: 60 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Vzdálená metoda Post: ✔
Vzdálená metoda Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (5) ###

Application Passwords: o George Stephanis – 0.1-dev
Custom account fields: o Tomáš Slavík – 1.2.2
FeedWordPress: o Charles Johnson – 2016.0420
Maintenance Mode: o Lukas Juhas – 2.2.5
WooCommerce: o WooThemes – 2.6.14

### Settings ###

Force SSL: –
Currency: CZK (Kč)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Sídlo obchodu: #1511 - /obchod/
Košík: #1512 - /kosik/
Pokladna: #1513 - /pokladna/
Můj účet: #1514 - /muj-ucet/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Twelve
Version: 1.1 – 2.2 je k dispozici
Author URL: http://cs.wordpress.org/
Child Theme: ❌ – Pokud upravujete WooCommerce
nebo rodičovskou šablonu
kterou jste nevytvořili
doporučujeme použít child šablonu. Viz. Jak vytvořit child šablonu

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
@claudiosanches can you confirm this?

**Comment by claudiosanches** [comment]
@mikejolley confirmed.
