### ISSUE TITLE
Replay protection on refunds

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#13614]
## EXPLANATION OF THE ISSUE

One of our team was making a partial refund on an order. However, his browser repeated the HTTP request (we verified this in the Apache logs - the team member was in a different country, and the second identical request came in seconds later, presumably caused by a networking glitch). As a result, the customer got refunded twice as much as he should have been.

So, it seems that WooCommerce partial refunds from the WP dashboard are not replay-safe.

(https://blog.cloudflare.com/introducing-0-rtt/ - "Applications need to be replay safe to work with modern browsers, whether they support 0-RTT or not. Browsers replay data all the time due to normal network glitches, and researchers from Google have even shown that attackers can trick the browser into to replaying requests in almost any circumstance by triggering a particular type of network error.").

## STEPS TO REPRODUCE THE ISSUE

1. Make a partial refund on an order.

2. Emulate an attacker or network glitchiness by replaying the HTTP request.

This was done on WooCommerce 2.6.

Result: two refunds.
Expected result: only one.

**Comment by mikejolley** [comment]
There are some protections in place;

1. Nonce checking using `check_ajax_referer`
2. Max refund check (checks amount being refunded against remaining order amount)

I'm not sure what else could be added however. @justinshreve @coderkevin @claudiulodro any ideas? Do you think something like checking the last update timestamp against a timestamp sent with the request would work? If the timestamps don't match, reject the request?

**Comment by DavidAnderson684** [comment]
@mikejolley Yes, unfortunately those didn't help prevent it: anything in the networking stack that re-transmits the packets (browser, router, etc.) will have the nonce, and the refund was for less than 50% of the order amount, so, it could be sent a second time without being prevented.

Perhaps the refund form in the admin page can have some quasi-random identifier that gets saved with the refund, and then, when a refund request comes in, WC core can check that there's no recent existing refund on the order with the same identifier. (When a dashboard refund is successfully made, the dashboard page can receive a new identifier to allow new refunds, as part of the response. Or perhaps that'd be automatic anyway via refreshing the HTML of that section).

**Comment by DavidAnderson684** [comment]
"anything in the networking stack that re-transmits the packets" - it can only have been the browser. Any routers that were re-transmitting would have used the same TCP sequence number, and the webserver would have dropped the packets as duplicates.

**Comment by claudiulodro** [comment]
The overarching problem is that WP nonces aren't actually "numbers used only once,":

> Nor are they used only once, but have a limited "lifetime" after which they expire. During that time period the same nonce will be generated for a given user in a given context. The nonce for that action will remain the same for that user until that nonce life cycle has completed . . . They help protect against several types of attacks including CSRF, but do not protect against replay attacks because they aren't checked for one-time use.

https://codex.wordpress.org/WordPress_Nonces

To handle this, we can save the most recent valid nonce in a customer meta field ( 'last_used_refund_nonce' ). Each time a refund happens, check the new nonce against the most recent nonce used by the customer for a refund, and reject if they are the same or update the saved nonce if they aren't. This will solve the replay issue, but will introduce a small "refund window" where a customer can only have one refund each nonce period (1 day by default, but we can customize it).

@mikejolley, we can't use timestamps for checking because it would be trivial to change the timestamp sent in the request to be a valid one if you are trying to do a replay attack.

**Comment by DavidAnderson684** [comment]
@claudiulodro I think that the 'threat model' here is where the browser either accidentally (network glitches), or forced by an attacker, sends a new HTTP request to duplicate the one which it (wrongly) thinks was never received. As such, it's not about man-in-the-middle scenarios where someone can observe and inject customised traffic. (In those scenarios, the solution is SSL - without SSL, a MITM attacker with observe+inject capabilities can just steal the login cookie and so every other protection is moot). So, I agree with you that people grabbing the nonce isn't something that comes into scope. If I follow rightly, the timestamp is functioning as a good-enough unique ID?

**Comment by claudiulodro** [comment]
Yep. You're correct. We don't need to worry about that other stuff. Microtimestamp or random number should work fine. That'll teach me for trying to solve things before coffee. :)

**Comment by mikejolley** [comment]
We can use https://github.com/woocommerce/woocommerce/issues/15780 for this too; the first request will lock it and the 2nd will wait or fail. Just send the original amount with the first request.

**Comment by DavidAnderson684** [comment]
Just to note that, if my memory serves me correctly, the two HTTP requests in the case that led to the opening of this were a few seconds apart. The problem was not concurrency. The shop agent was the other side of the world to the shop webserver, and I'd guess he was on an unreliable network too, leading to his browser re-trying the request. By the time that this second request was sent by his browser, any lock claimed would very likely have been released. A lock would still be necessary to prevent concurrent requests, so is a good idea. But I'm pretty sure it wouldn't have helped my case.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16973
