### ISSUE TITLE
Paging Through Shop Pages returns the Wrong # of Products Still not fixed.

### ISSUE THREAD

**Issue by martinsmagic** [woocommerce/woocommerce#13616]
## EXPLANATION OF THE ISSUE

I reported this at #13398 for 2.7.9-RC1 and it was closed as fixed but the problem is still there with 3.0.0 RC1.

## STEPS TO REPRODUCE THE ISSUE

Click here: https://beta.qualitymagicsales.com/ and it says 1-10 of 119 results when in fact it should omit the out of stock items.  It does not.

Thanks,

andy

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://beta.qualitymagicsales.com
Site URL: https://beta.qualitymagicsales.com
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: ❌ 5.5.9-1ubuntu4.21 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 180
PHP Max Input Vars: 1620
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

OpenID: by DiSo Development Team – 3.4.2
Rename wp-login.php: by Ella Iseulde Van Dorpe – 2.5.5
WooCommerce: by Automattic – 3.0.0-rc.1
WP Security Audit Log: by WP White Security – 2.6.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #826 - /
Cart: #827 - /cart/
Checkout: #828 - /checkout/
My account: #830 - /my-account/

### Theme ###

Name: Twenty Twelve
Version: 2.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
The problem has been fixed in the upgrade script. But you've already updated so it won't rerun. Updaters run once.

**Comment by mikejolley** [comment]
Need to de-activate and re-activate so `create_terms` runs during the installer script.

Then, the data upgrade needs to be ran OR you can fire this code manually via your functions.php file. Remove when it's ran.

```
global $wpdb;

if ( $outofstock_term = get_term_by( 'name', 'outofstock', 'product_visibility' ) ) {
		$wpdb->query( $wpdb->prepare( "INSERT INTO {$wpdb->term_relationships} SELECT post_id, %d, 0 FROM {$wpdb->postmeta} WHERE meta_key = '_stock_status' AND meta_value IN 'outofstock';", $outofstock_term->term_id ) );
	}
```

Or start fresh since this is a staging environment.

**Comment by mikejolley** [comment]
NVM there is an SQL issue after all.

**Comment by martinsmagic** [comment]
Hi Mike - I think you figured this out now.  I rebuilt the whole site and reran the updater and still we have the same issue.

Thanks,

andy
