### ISSUE TITLE
Possible to Add Invalid Product Quantities in Safari

### ISSUE THREAD

**Issue by catrymer** [woocommerce/woocommerce#13629]
## EXPLANATION OF THE ISSUE

In the current version of Safari it's possible to add invalid amounts of an item to a cart (like adding 1.5 t-shirts). In Firefox and Chrome trying to do this results in an error message telling you to pick a valid value. In Safari it adds the invalid amount to the cart and calculates the price accordingly.

## STEPS TO REPRODUCE THE ISSUE

1. Open a product page in a a browser that isn't Safari (I tested in both Firefox and Chrome). 
2. Click into the item quantity box and manually type the number 1.5 to indicate you want 1.5 of these products.
3. Click Add to Cart
4. Note that an error message pops up with the message, "Please select a valid value. The two nearest valid values are 1 and 2."
5. Repeat steps 1 to 3 in Safari with the same product and note that Safari happily adds 1.5 products to your cart without any issues or error messages. If you check the cart you will see the amount owed is calculated at 1.5 times that product's price.

## ADDITIONAL INFORMATION

This was first reported in https://woothemes.zendesk.com/agent/tickets/547605 . The user's site, where I have confirmed the same behavior, is https://paumedeterre.fr .

**Comment by catrymer** [comment]
Here's a screenshot of a cart in Safari that shows the incorrect product amount problem:

![http://cld.wthms.co/EFkx](https://drops.azureedge.net/drops/files/acc_545605/EFkx?rscd=inline%3B%20filename%3DScreen_Shot_2017-03-16_at_10.24.49.png&rsct=image%2Fpng&se=2017-03-16T16%3A54%3A52Z&sig=437XYnAGvIcWuhaE5tCUr6hop7jGzy%2Ful%2Fh%2BWeqB%2B6s%3D&sp=r&sr=b&st=2017-03-16T15%3A54%3A52Z&sv=2013-08-15)

**Comment by mikejolley** [comment]
@catrymer WooCommerce core has code in place to convert any decimal value to an integer, regardless of whether or not the HTML5 validation/step attributes lets the user set a decimal value. The HTML5 validation/notice you see in Chrome is likely just not part of the Safari browser.

This is our code which formats to integers:

https://github.com/woocommerce/woocommerce/blob/71d0702523bcc365403dd3b84b945da5218d88b4/includes/wc-core-functions.php#L41 

Looks like there is an extension on that site running which allows decimal values. Measurement price calculator is one which does this and they have it installed.

If this product is not configured to allow decimals in Measurement price calculator, this may be a bug in that extension. https://github.com/woocommerce/woocommerce-measurement-price-calculator/search?utf8=%E2%9C%93&q=woocommerce_stock_amount You can CC skyverge into the ticket.

**Comment by mikejolley** [comment]
Added a note to zendesk.
