### ISSUE TITLE
[wc 3.0-RC1]: Missing purchased col in WooCommerce > Orders

### ISSUE THREAD

**Issue by andreagrillo** [woocommerce/woocommerce#13627]
## EXPLANATION OF THE ISSUE

With WooCommerce 3.0-RC1 in WooCommerce > Orders list table missing the column "Purchased"

## STEPS TO REPRODUCE THE ISSUE

Simply, place an order and visit the page orders in WordPress admin area (WooCommerce > Orders)

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://localhost/yith
Site URL: http://localhost/yith
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3-RC1-40141
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.5.30
PHP Version: ❌ 5.5.30 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.42.1
OpenSSL/1.0.2d

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 2.13.2
AG-ALR WP Mail Debug: by Andrea Grillo - Antonio La Rocca – 1.4
User Switching: by John Blackbourn – 1.0.9
WooCommerce: by Automattic – 3.0.0-rc.1
WordPress Importer: by wordpressdotorg – 0.6.3
YITH WooCommerce Ajax Product Filter Premium: by YITHEMES – 3.3.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by mikejolley** [comment]
This was intentional - it involves loading ALL items for ALL orders on page and is a major performance bottleneck.

**Comment by andreagrillo** [comment]
It is not a bad idea but when I seen this for the first time I thought to an error.
I like it!

Good Works. 
Bye 

AG

**Comment by dvdtth** [comment]
@mikejolley I sort of like the old days (up till 2.6) where orders > purchased column shows the items purchased for all orders (limited to x orders per page). Understand that there's a performance hit doing that, but now that it's been removed in >=2.7, what's the plan/replacement feature other than to go into each order individually to see what items are actually bought?

**Comment by keinx02** [comment]
Please help me out! give me step by step instruction on how to get back the purchase column on woocomerce > order. Thank you very much!

**Comment by mikejolley** [comment]
https://href.li/?http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/18832222-dynamically-display-order-content-on-orders-page

**Comment by WPprodigy** [comment]
For those that stumble across this, you can add this plugin to restore the functionality if you need to: https://wordpress.org/plugins/yith-purchased-column-for-woocommerce/

**Comment by appsocioo** [comment]
Would you like to reactivate the Purchased column removed in the last Woo Commerce version but you don’t know how to do it? Easy! We have developed this plugin for you: after installing and activating it, you will have the column again just like before. You can download it for free from here:

https://wordpress.org/plugins/yith-purchased-column-for-woocommerce

[iphone development company](https://www.appsocio.com/ios-app-development.php)
