### ISSUE TITLE
variation description using rest api

### ISSUE THREAD

**Issue by ranieribarbarossa** [woocommerce/woocommerce#13638]
## EXPLANATION OF THE ISSUE
the variation description field is present and valorized in back office.
getting a product using rest api , the field is not present .
the issue has been verified in WC 2.6 and even in 3.0 (that i have just dowloaded) .
i use WC 4.6.4 and storefront theme .

Ranieri .

**Comment by mikejolley** [comment]
This is part of the v2 API in 3.0.0

**Comment by ranieribarbarossa** [comment]
Hi Mike .
I have tried with wc-api/v2 and wc-api/v3 but description field is not shown .
i forgot to mention that i use WP italian variant .

Ranieri .

**Comment by claudiosanches** [comment]
@ranieribarbarossa `wc-api` it's our legacy API, that is deprecated and will be removed in next versions, what Mike said is about `wc/v2/` our new REST API that is an integration with WordPress REST API.

**Comment by ranieribarbarossa** [comment]
Hi Claudio .
wc/v2 works as expected .
i see that variations are now separated from products .
where can i get the new docs for wc/w2 ?
all links i found leads to wc/v1 .
thank you .
have a nice weekend .

Ranieri .

**Comment by claudiosanches** [comment]
@ranieribarbarossa docs will be ready by April 4.
