### ISSUE TITLE
Remember Me checkbox on login form not working. 

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#13634]
## EXPLANATION OF THE ISSUE

User in 544546-zd-woothemes states that the _Remember me_ checkbox does not work on WooCommerce login forms. Upon searching, I found two forms, and neither seem to set a username from a cookie, only from posted data. 

* [My account login form](https://github.com/woocommerce/woocommerce/blob/master/templates/myaccount/form-login.php#L45)
* [Global login form](https://github.com/woocommerce/woocommerce/blob/master/templates/global/form-login.php#L36)

Am I missing it, or us the username not set if the box is checked and the cookie is set?

**Comment by claudiosanches** [comment]
WordPress is the responsible of setting cookies.

We get the `username`,` password` and `rememberme` here: https://github.com/woocommerce/woocommerce/blob/adfd955194dd9084f994078ad15a3437baede5f5/includes/class-wc-form-handler.php#L865-L870

And we pass to `wp_signon()` here: https://github.com/woocommerce/woocommerce/blob/adfd955194dd9084f994078ad15a3437baede5f5/includes/class-wc-form-handler.php#L908

Docs about the `wp_signon()`: https://developer.wordpress.org/reference/functions/wp_signon/

**Comment by jessepearson** [comment]
Ah, `wp_signon()` got me over to [`wp_set_auth_cookie()` ](https://developer.wordpress.org/reference/functions/wp_set_auth_cookie/), which explains that the *Remember me* box just extends the life of the cookie from the current browsing session to two weeks. The user and I were both under the assumption that it meant "remember my username", which it does not.
