### ISSUE TITLE
Woocommerce Disable Checkout

### ISSUE THREAD

**Issue by w3prodigy** [woocommerce/woocommerce#13633]
A client is having issues with their Merchant Service Provider and needs to prevent their site from accepting orders until the issue is resolved.

The issue with Woocommerce is that there is no simple option to suspend the acceptance of orders within Woocommerce.

As a work-around I removed all payment options which presents any customers attempting to place an order with the "Invalid payment method." message.

Please accept this as a feature request to add a simple option to suspend acceptance of orders for online stores that may come across a similar issue.

**Comment by claudiosanches** [comment]
Please submit new ideas on http://ideas.woocommerce.com/forums/133476-woocommerce

And there is already an option for disable purchases, you can use this plugin: https://docs.woocommerce.com/document/catalog-visibility-options/

**Comment by anupvrj** [comment]
Better you change any custom page in woocommerce setting. and in custom page just write that delivery is not available now. No need to pay any charge for unwanted plugins.
woocommerce>setting>checkout>checkout>select custom page.
