### ISSUE TITLE
[Select2 V4]

### ISSUE THREAD

**Issue by pixedelic** [woocommerce/woocommerce#13631]
Has the markup of Select2 v.4 completely changed or am I missing something? Select boxes are completely messed up in my themes and even if I activate Twenty-Seventeen I see two different things, also the default styles are changed:

v.2.6.x
![screen shot 2017-03-16 at 18 21 05](https://cloud.githubusercontent.com/assets/527057/24009496/78ae3e96-0a75-11e7-8def-5f77c3e9c098.png)

v.3.0.0 RC1
![screen shot 2017-03-16 at 18 21 36](https://cloud.githubusercontent.com/assets/527057/24009519/87a1735a-0a75-11e7-81a8-3de77103e2a8.png)

Is there any way to restore the original markup and assure consistency with old versions, a hook anywhere, anyhow?

TIA

**Comment by mikejolley** [comment]
No you cannot restore the old markup.

https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#select2-version-4

Update your CSS which has select2 styling.
