### ISSUE TITLE
Product inventory and shipping tabs visibility

### ISSUE THREAD

**Issue by lutrov** [woocommerce/woocommerce#13641]
Consider making the visibility of the "Inventory" and "Shipping" tabs in the product editing screen conditional on the store settings.

1. If we set the "Enable stock management" checkbox in "Woocommerce > Settings > Products > Inventory" to unchecked, should there be an "Inventory" tab in the product editing screen?

2. If we set the "Shipping Locations" dropdown in "Woocommerce > Settings > General Options" to "Disable shipping & shipping locations", should there be a "Shipping" tab in the product editing screen?

If we make the display for both of the tabs conditional on whether we're using those store features it would make the UI less cluttered and look more customised.

**Comment by mikejolley** [comment]
Stores that don't manage inventory via WooCommerce may still have SKUs.

Stores which do not charge shipping may still define product dimensions.

You can customise the tabs with filters if you want to hide things from clients.
