### ISSUE TITLE
Resized Product Gallery thumbnails

### ISSUE THREAD

**Issue by chirag255** [woocommerce/woocommerce#13648]
## EXPLANATION OF THE ISSUE

I was testing a new product gallery update (RC1 3.0.0) in Twenty Sixteen as well as Twenty Seventeen. For the variable products, I have noticed that when I select the product variation, the first picture in thumbnail gallery displays larger then the all remaining thumbnail gallery pictures. While testing in storefront theme it works good, no resized thumbnail. 

Fix is possible with the CSS. This is to just bring into your attention.

## STEPS TO REPRODUCE THE ISSUE

Use the theme Twenty Seventeen or Twenty Sixteen.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://localhost/ledtestwoo
Site URL: http://localhost/ledtestwoo
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.9 (Win64) PHP/5.5.12
PHP Version: ❌ 5.5.12 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 3 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.36.0
OpenSSL/1.0.1g

SUHOSIN Installed: –
MySQL Version: 5.6.17
Max Upload Size: 3 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Font Awesome 4 Menus: by New Nine Media – 4.7.0
LED World Canada Site Settings: by LED World – 1.0.1
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce: by Automattic – 3.0.0-rc.1
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Sounds like you may be missing some CSS styles if it actually appears larger. This is what I'm seeing 
![2017-03-17 at 16 22](https://cloud.githubusercontent.com/assets/90977/24052593/f1933ba0-0b2d-11e7-8414-45298c380891.png)

The image in the source is larger, since it reuses the shop single image. But it should not be visible.
