### ISSUE TITLE
CRUD search helpers for products

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13645]
Same as https://github.com/woocommerce/woocommerce/issues/12677 but for products.

**Comment by mikejolley** [comment]
Punting to 3.2. Order helpers will still be in place for 3.1.

**Comment by mikejolley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CRUD search helpers for Products](https://trello.com/c/7UYO3EXV/98-crud-search-helpers-for-products)

**Comment by claudiulodro** [comment]
This is pretty much ready in [this branch](https://github.com/woocommerce/woocommerce/tree/improvement/13645). Just needs unit tests, one of those wiki pages, and any bugs/changes that pop up during unit tests. I'll just need one day in a future sprint to wrap everything up with this.
