### ISSUE TITLE
Product submenu labels in admin screens

### ISSUE THREAD

**Issue by lutrov** [woocommerce/woocommerce#13640]
I've had a look at the current issues and this doesn't appear to have been mentioned.

Consider changing the Woocommerce dashboard menu labels to conform to Wordpress standards.

Currently we use the following naming convention for the Products submenu:

- Products > Products
- Products > Add Product

If we go by the standard Wordpress naming convention, it should be:

Products > All Products
Products > Add New

**Comment by mikejolley** [comment]
@jameskoster

**Comment by jameskoster** [comment]
I agree.

**Comment by faisal-alvi** [comment]
Hi,

I have submitted #13712 

Thank you

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/13712
