### ISSUE TITLE
Broken Link in readme.txt on Development

### ISSUE THREAD

**Issue by garrett-eclipse** [woocommerce/woocommerce#13649]
## EXPLANATION OF THE ISSUE

Doing translations I found the URL in this one was broken;
https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev-readme/en-ca/default?filters%5Boriginal_id%5D=4193382

String - * To read more about this release, see our dev blog announcement here: http://wp.me/p6wtcw-Uo

This can be found in the readme.txt here;
https://github.com/woocommerce/woocommerce/blob/master/readme.txt#L224

**Comment by mikejolley** [comment]
This post is in draft because we have not released yet :)

**Comment by garrett-eclipse** [comment]
Thanks @mikejolley just wanted to make sure it's not launched with the broken link. Cheers
