### ISSUE TITLE
CRUD search helpers for orders

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13646]
See #12677. This is for orders only.

**Comment by melatova** [comment]
Would appreciate ability to search orders by first name + last name , e.g. "John Smith". Currently can only search by "John" or "Smith". Thank you.

**Comment by mikejolley** [comment]
@claudiulodro The only query I'm not sure about is the date_x queries. With dates there are a few things we may need to support, even though there is only 1 item of data:

- >= / > / < / <=
- Ranges of dates

How can we support these? We could support an array of args so you could specify range, type of comparison etc. We could alternatively support something similar to how github allows dates in query strings:

- >=2017-05-05
- >2017-05-05
- <2017-05-05
- <=2017-05-05
- 2017-05-05...2017-05-08

Thoughts?

**Comment by claudiulodro** [comment]
@mikejolley, ranges are supported in my implementation for all date params. You can do e.g.
```
$args = array(
    'date_created_after' => '2017-05-04',
    'date_created_before' => '2017-05-05',
);
```

**Comment by mikejolley** [comment]
@claudiulodro I saw, but that requires a special suffix (_after, _before). Thats good :) Just wondered if you thought it would be good to have a single key with multiple values.

**Comment by claudiulodro** [comment]
That is a good idea now that I think about it more. Then we don't have to have 3 query vars for each date param. I like the GitHub date format you listed.

**Comment by mikejolley** [comment]
@claudiulodro Just an idea - either way we'd still have to support timestamps etc, and then parse the operators from the string. Do you see any downsides to doing it that way?

**Comment by claudiulodro** [comment]
I think it should be fine. We can just use a regex `/([^.<>]*)(<|>|\.\.\.=?)([^.<>]+)/` to parse the string if we do it the GitHub way.
