### ISSUE TITLE
updating simple product

### ISSUE THREAD

**Issue by keloniton** [woocommerce/woocommerce#13659]
I am trying to update a product using post method. I simple use
`'products/'+product.id, data, function(err, data, res)`
and the data is 
`    var data = {
      regular_price : '5'
    };`
but i receive error which mentions 
no product data specified to edit product

**Comment by mikejolley** [comment]
There are no issues with the endpoint in the current release so it has to be your code/request. Try using a REST API client to test - I use insomnia :)

Please use Github for bug reports in future, not support questions. If you can confirm a real bug with the API, feel free to log, but it needs to be reproducible.
