### ISSUE TITLE
Product price is shown as 0 instead of "Free"

### ISSUE THREAD

**Issue by transbetacism** [woocommerce/woocommerce#13658]
## EXPLANATION OF THE ISSUE
Since WooCommerce 2.7/3.0, products with the price 0 is no longer shown as "Free" - they are shown as $0 instead.

![New frontend](http://share.hellodetail.com/jc4U/[e8eb41c22ec672632d9aac992c13decf]_Image%202017-03-18%20at%203.26.30%20em.png)

![New backend](http://share.hellodetail.com/jcqb/[5973a8acc007abbcea9865ced8ce64a3]_Image%202017-03-18%20at%203.28.21%20em.png)

In WooCommerce 2.6.14; products with price 0 was shown as "Free" in both backend and admin:

![Frontend](http://share.hellodetail.com/jcPP/[b53198d37e342b611106b946ddf5fce3]_Image%202017-03-18%20at%203.24.22%20em.png)

![Backend](http://share.hellodetail.com/jchh/[13a54ef7653226d7ed1f80d4800b98d3]_Image%202017-03-18%20at%203.18.44%20em.png)

## STEPS TO REPRODUCE THE ISSUE
Setup a product with price 0.

**Comment by mikejolley** [comment]
Pretty sure this was deliberate. I'll confirm and document.

**Comment by MousAbuDoush** [comment]
Hi,
Could we have have script to make it work as version 2.7 ?

**Comment by claudiosanches** [comment]
@MousAbuDoush there is no version 2.7. We changed 2.7 to 3.0.

**Comment by MousAbuDoush** [comment]
Hi Claudiosanches,
I know, but I want my products prices to display "Free" rather than 0.0$
I would be much appreciated if some could help me

**Comment by claudiosanches** [comment]
You can use this:

```php
function my_wc_custom_get_price_html( $price, $product ) {
	if ( $product->get_price() == 0 ) {
		if ( $product->is_on_sale() && $product->get_regular_price() ) {
			$regular_price = wc_get_price_to_display( $product, array( 'qty' => 1, 'price' => $product->get_regular_price() ) );

			$price = wc_format_price_range( $regular_price, __( 'Free!', 'woocommerce' ) );
		} else {
			$price = '<span class="amount">' . __( 'Free!', 'woocommerce' ) . '</span>';
		}
	}

	return $price;
}

add_filter( 'woocommerce_get_price_html', 'my_wc_custom_get_price_html', 10, 2 );
```

**Comment by MousAbuDoush** [comment]
It works great, thank you!

**Comment by fuscoj** [comment]
Hi, this script working in Woo 3.1.2? Because, I have a product with price 0, but in frontpage show 0.00 and not "Free".
I paste this code in my function.php and not working.

thks.

**Comment by victorsueiro** [comment]
in version 3.2.6 it works correctly.
Thank you very much!

**Comment by happivize** [comment]
Thank you I also added it via Code Snippets plugin and it worked fine. I just deleted the ! mark as I just wanted it to say Free. I'm also on v 3.2.6
