### ISSUE TITLE
Signature Error in REST API when filtering with nested array

### ISSUE THREAD

**Issue by elodieg** [woocommerce/woocommerce#13667]
When using Woocommerce rest api, filtering can cause a Signature error :   
"Invalid Signature - provided signature does not match."  

It occurs when filtering with nested arrays.  

Here are my query arguments, for products endpoint :  

```
$args = [  
    'filter' => [  
        'date_query' => [  
            'before' => '3 hour ago',  
            'column' => 'post_modified_gmt',  
        ],  
    ],  
    'per_page' => 100,  
];
```

If I remove the filter array, it works fine.

Problem is located here :  
https://github.com/woocommerce/woocommerce/blob/2.7.0-beta-4/includes/api/class-wc-rest-authentication.php#L350

`$param_value_inner` is an array, and this is not supported.

Here is the resulting `$query_string` value. You can see it contains the string `"Array"` :  
`"filter%255Bdate_query%255D%3DArray%26oauth_consumer_key%3Dck_10faa73fcad77c1ec7b05d664d0ef2f32ccaab44%26oauth_nonce%3D53718ddf5ea6a3df65cb84822284e8e0651ce782%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1490004695%26oauth_token%3D%26oauth_version%3D1.0%26per_page%3D100"`

**Comment by mikejolley** [comment]
What you're doing is not supported. The filter param was removed in WordPress 4.7, and is deprecated in our API, and removed in our v2 API coming this month. As such, this won't be fixed.
