### ISSUE TITLE
Unable to filter order by date_created in REST API 

### ISSUE THREAD

**Issue by routbiplab** [woocommerce/woocommerce#13668]
## EXPLANATION OF THE ISSUE

WP: 4.7
WC : 2.6.2

## STEPS TO REPRODUCE THE ISSUE

GET : http://localhost/wordpress/index.php/wp-json/wc/v1/orders?filter[date_created]2017-03-20T11:49:27
Using : OAtuth 1.0

Expected result: Order should be filtered according to the date given.
Actual result : Returning all the orders.

**Comment by mikejolley** [comment]
Filter is no longer supported with WordPress 4.7+

**Comment by claudiosanches** [comment]
You should use `after` and `before`, the same way that is documented in https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders


![screenshot from 2017-03-20 13-33-26](https://cloud.githubusercontent.com/assets/1264099/24110280/d1366882-0d71-11e7-9b19-dbdddee38e44.png)

**Comment by avijit143** [comment]
But, after and before is not fetching the updated items.

**Comment by routbiplab** [comment]
@mikejolley @claudiosanches Then how we will get/pull order as per created_date or modified_date ?

**Comment by mikejolley** [comment]
Thats not supported. Only creation date is.

**Comment by seeya** [comment]
I'm facing the issue of not being able to get orders created after a certain hour.
I tested difference cases.
Calling the endpoint`orders?after=2017-03-21T03:00:00` returns 
```
2017-03-21T08:34:30
2017-03-21T02:40:13 <-- Should not rerturn this
```

I also tested with older orders whereby the dates were more than a day old. Those records are not shown. 

Hence could there be a check missed out on the hours and minutes?

**Comment by sahaindra** [comment]
Hi,

I am struck in the middle of a project, can anybody tell me how to apply filters while fetching data from woocommerce. I have applied the after filter but the results are not desired. For e.g: - I am trying to fetch customers using after filter which is set as 2017-03-30T06:25:13, but the response contains data with created date before 30th March.

Regards,
Saha

**Comment by seeya** [comment]
Hey Saha, you can try checking your server's timezone and date time. It could be wrong which caused the issue.

**Comment by sahaindra** [comment]
Hi Seeya,

I am using POSTMAN to fetch the datas. What I did, I first fetched customers and from the response I chose a created time lets say 28th March. Now, when I resend the request with filter date as 29th, I am still getting the customer created on 28th March. So, my concern is How should I fetch the customers correctly based on filterer data and time.

**Comment by avijit143** [comment]
Hi all, 
It has been a long time that I am facing problem with filtering the data. As @claudiosanches said "after" will work for filtering the data but it is not working for customers and orders. It is only working for products. I am using several times in postman. But, it is not working as it should be. 
I am using /wp-json/wc/v1/products?after=2017-04-04T12%3A34%3A45 and /wp-json/wc/v1/products?filter%5Bafter%5D=2017-04-04T12%3A34%3A45. But, it is giving me data before 2017-04-04. Why is it happening? How to solve it?
It is an emergency.

Thanks in advance

**Comment by claudiosanches** [comment]
@avijit143 what `after` for customers? There is none. Please check the docs before.
Note that for products and orders the date is passed to `WP_Query`.

**Comment by avijit143** [comment]
Then, What shall I use for filtering customer?

**Comment by avijit143** [comment]
![woocommerce_ex](https://cloud.githubusercontent.com/assets/26545272/24656484/630101d8-1960-11e7-80bd-bdbb8e69bc3a.jpg)
after is also not working for orders. Where is the filtering section in woocommerce api? I only found after and before under "orders" in "list all orders". Otherwise, I could not find anywhere. @claudiosanches 

Help me out of these.

**Comment by avijit143** [comment]
How to use PUT to fetch the updated products?
Operation Type:PUT
Body:{
  "regular_price": "24.54"
}
Url:    http://www.abcd.com/wp-json/wc/v1/products/182
Content Type: application/json
Expected result: only update the updated product 182
Actual result: 401 unauthorized error

**Comment by avijit143** [comment]
Actual result:{
  "code": "woocommerce_rest_authentication_error",
  "message": "Invalid Signature - provided signature does not match.  PUT&http%3A%2F%2Ftemplatebar.com%2FIndividual%2Fsaurav%2Fwordpress1%2Fwp-json%2Fwc%2Fv1%2Fproducts%2F182&oauth_consumer_key%3Dck_7098b8fbe0b6d58d287d344f5faca8fe120cd60c%26oauth_nonce%3DqUf4hD%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1491830025%26oauth_token%3D%26oauth_version%3D1.0  ",
  "data": {
    "status": 401
  }
}

**Comment by avijit143** [comment]
@claudiosanches in woocommerce api for customer update it is mentioned 
curl -X PUT https://example.com/wp-json/wc/v2/customers/25 \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "first_name": "James",
  "billing": {
    "first_name": "James"
  },
  "shipping": {
    "first_name": "James"
  }
}
like these way. But, same things while I am doing on postman, it is giving me 401 unauthorized error.
How to do update the customer?

**Comment by claudiosanches** [comment]
@avijit143 so you are using wrong credentials or your server is removing the credentials, or even blocking PUT requests.

**Comment by avijit143** [comment]
@claudiosanches  For PUT credential will change? But, for the same credential GET, POST is working. Why not for PUT?

**Comment by claudiosanches** [comment]
@avijit143 have you checked if you server is allowing PUT requests? If PUT request have auth headers removed?

**Comment by avijit143** [comment]
![woocommerce](https://cloud.githubusercontent.com/assets/26545272/25219194/38b70f18-25cb-11e7-86d2-17367018b933.JPG)
I am testing the particular url in Basic Auth. Url: https://krmgfnqr.preview.infomaniak.website/wc-api/v2
I provided certain user name and password. It is giving me 200 success. But, when I am trying test with customers or products. Like: https://krmgfnqr.preview.infomaniak.website/wc-api/v2/products. It is giving me: {
  "errors": [
    {
      "code": "woocommerce_api_authentication_error",
      "message": "The user key is invalid"
    }
  ]
}
I tried with every permutation and combination by providing CS and CK as user name and password, By using oauth 1.0. I did not get 200 success message.
![woocommerce_1](https://cloud.githubusercontent.com/assets/26545272/25219469/3f4de01c-25cc-11e7-9ff9-509c713ac5a2.JPG)

@claudiosanches  How to solve this?

**Comment by claudiosanches** [comment]
The index endpoint in `/wc-api/v2` does not require any kind of authentication.
So still it's the same problem, you don't have permissions for it.
Maybe created the keys for a user that don't have any permission or maybe using a plugin to limit it.
Still works just fine and you should be already using our new REST API that you can find in https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by avijit143** [comment]
![capture](https://cloud.githubusercontent.com/assets/26545272/25378042/cfc76624-29c6-11e7-818d-4d2fb64ac82c.JPG)
As you told I don't have permission from my server, but I have checked in my admin panel there is read and write  permission. I have attached screen shot please check.
![capture](https://cloud.githubusercontent.com/assets/26545272/25378758/9fd16efe-29c8-11e7-81bb-42b2dea5168f.JPG)
What more permission shall I need to give?

And I did not get your second point "If PUT request have auth headers removed?". Can you explain it?

I can not do the update. Can you send me one screen shot of update?

**Comment by claudiosanches** [comment]
Contact your hosting provider support, ask then if there is something blocking PUT requests in the server or removing query strings or authentication headers.

**Comment by avijit143** [comment]
checked by disabling WAF. But, I am getting the same problem(401 unauthorized error) for PUT request. It is working fine for old api(i.e. wc-api). But, for new api it is not working. What to do now?

**Comment by claudiosanches** [comment]
@avijit143 have you changed the user permissions? There is a button to reset it on System status > Tools.

**Comment by avijit143** [comment]
@claudiosanches No, I have not changed any permission. I have only selected read/write permission. Shall I give you my access and you change whatever it is required? I have only changed "Setup shipping zones" under System status > Tools.

**Comment by avijit143** [comment]
@claudiosanches I am getting the following error.
<html><head><meta http-equiv="content-type" content="text/html;charset=utf-8">    <META HTTP-EQUIV="CACHE-CONTROL" CONTENT="NO-CACHE">
    <title>Security Violation</title></head>
    <body>
        <img style="border:0px" src="//d296wykt099k0b.cloudfront.net/error-pages-resources/amigo.co.il/logo.png"/> 
        <hr/>
        <h1>Access denied (403)</h1>
        <h2>Current session has been terminated.</h2>
        <p>For further information, do not hesitate to contact us.</p>
        <p>Contact us: <a href="mailto:support@cloudwm.com">support@cloudwm.com</a></p>
    <p>For a reference, please provide the following paragraph:</p>
        <pre>59.160.209.34://n-0000008c313439333831323336355d4449daecd05919 [1493812365]</pre></body></html>
Why is it happening?

**Comment by avijit143** [comment]
Which option I need to reset for inventory update? Here, I am attaching the screen shot of it below
![capture](https://cloud.githubusercontent.com/assets/26545272/25661740/665866b0-302f-11e7-8a99-76bf27b1fac0.JPG)
.

**Comment by claudiosanches** [comment]
@avijit143 not sure if we are talking about the same thing anymore, and there is already some from your hosting company asking for contact them.

**Comment by avijit143** [comment]
Hello @claudiosanches,
Good news is that I am able to update products or customers from POSTMAN. 
But, for that  I have to check "Add empty params to signature". 
![capture](https://cloud.githubusercontent.com/assets/26545272/26101503/fc27bf14-3a4e-11e7-97f7-2d8e6b0f5cca.JPG)
I am developing an adapter for WooCommerce, so I need that particular authentication to send through my adapter in C# language. How can I send it?
I am sending the following headers for authentication
httpWebRequest = (HttpWebRequest)WebRequest.Create(request);
                        httpWebRequest.Method = "PUT";
                        httpWebRequest.ContentType = "application/json";
                        httpWebRequest.KeepAlive = true;
                        httpWebRequest.Accept = "*/*";
                        httpWebRequest.Headers.Add("Accept-Language", "en-US,en;q=0.8");
                        httpWebRequest.UserAgent = ".NET Framework Test Client";
                        httpWebRequest.Headers.Add("Origin", "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop");
                        httpWebRequest.Headers.Add("Accept-Encoding", "gzip, deflate, sdch"); 

What else do I need to send?

If I do not choose "Add empty params to signature", It is giving me 401 Unauthorized error.
![capture](https://cloud.githubusercontent.com/assets/26545272/26101984/cfc18282-3a50-11e7-8c65-a095d0bc47fe.JPG)

**Comment by sirdowan** [comment]
This worked for me: /wp-json/wc/v2/orders?customer=36
