### ISSUE TITLE
API returns only two records

### ISSUE THREAD

**Issue by aishinfotech** [woocommerce/woocommerce#13664]
## EXPLANATION OF THE ISSUE

We are trying to integrate the woocommerce api with our external application but it returns only two order records having cancelled status even after pagination. 

## STEPS TO REPRODUCE THE ISSUE

I used the below code to reproduce this issue. For securty purpose I have changed the keys values.

$woocommerce = new Client(
    'http://www.makemydelivery.com', 
    'ck_cc7b0******************************************', 
    'cs_9c56f*******************************************',
    [
    	'wp_api' => true,
        'version' => 'wc/v1',
    ]
);
$options = ['per_page' => 10,'page' => 1,'order'=>'asc','status'=>'any',];
$results = $woocommerce->get('orders',$options);

echo '<pre>';
echo sizeOf($results);
print_r($results);
echo '</pre>';
[ordersdata.txt](https://github.com/woocommerce/woocommerce/files/854364/ordersdata.txt)

**Comment by mikejolley** [comment]
`any` is not a documented status.

> Order status. Default is pending. Options (plugins may include new status): pending, processing, on-hold, completed, cancelled, refunded and failed.

https://woocommerce.github.io/woocommerce-rest-api-docs/#orders

**Comment by aishinfotech** [comment]
Hi,

I tried request without status parameter still getting only two records as results.

$woocommerce = new Client(
    'http://www.makemydelivery.com', 
    'ck_cc**********************************************', 
    'cs_9c5*********************************************',
    [
    	'wp_api' => true,
        'version' => 'wc/v1',
    ]
);
$options = ['per_page' => 1,'page' => 2,'order'=>'asc',];
$results = $woocommerce->get('orders',$options);
echo '<pre>';
echo sizeOf($results);
print_r($results);
echo '</pre>';
?>

**Comment by aishinfotech** [comment]
Please let me know you require keys to test.

**Comment by mikejolley** [comment]
Claudio suggested you may have code filtering the results outside of the REST API. Otherwise we'd be able to replicate on all sites.

**Comment by claudiosanches** [comment]
Or maybe changing the `posts_per_page` on `WP_Query`.
