### ISSUE TITLE
If shipping is disabled, shipping address metas are still created

### ISSUE THREAD

**Issue by pmgarman** [woocommerce/woocommerce#13677]
1. Place an order with shipping disabled in the WC global general settings.
1. Place an order
1. Check the orders post meta, 9 blank shipping metas will have been created

![](http://c.pmgr.mn/57q0+)

Is this something required or just happens by nature of the new crud system? Wondering if there is room here to *not* write these empty metas on checkout if the benefit of a slight potential performance/scaling bump is worth whatever effort it would take to cleanly do this without breaking things.

Simple napkin math, 100 orders/min for 10 minutes = 1000 orders * 9 metas = 9000 avoided inserts in a 10 minute period.

**Comment by mikejolley** [comment]
@justinshreve 

In theory they could be left blank and non-existant because get_post_meta will return an empty string if they don't exist. However, this could have implications if metadata_exists is used, so this should not be added to 3.0.0

**Comment by justinshreve** [comment]
Hmm yeah, based on our checking for changes props using `metadata_exists`, we might have to think about this a bit to properly fix it. I agree its annoying to have the empty rows for a feature that is not being used.

**Comment by pmgarman** [comment]
I had a feeling all the new CRUD stuff made it more than just "hey lets not insert meta that we don't need to"

Definitely a nice to have and not a blocker of any sort.

**Comment by UserName011** [comment]
One can also argue that if merchant disabled the ability to choose shipping address that is different from billing address then WooCommerce should not create empty rows of shipping.
