### ISSUE TITLE
Disabling "Anyone can register" doesn't affect WC registration settings

### ISSUE THREAD

**Issue by aheckler** [woocommerce/woocommerce#13676]
## EXPLANATION OF THE ISSUE

If I disable user registrations from within the standard WP settings (under Settings > General), I intuitively expected that to override the WC settings under WooCommerce > Settings > Accounts, but it did not. Anyone can still register on the My Account page (if that is enabled), or on the Checkout page (if that is enabled).

Since the core setting says "_Anyone_ can register", I would definitely expect registrations on the My Account page to be disabled. However, I can see an argument for still accepting registrations during checkout, since those users aren't just anyone, but confirmed customers.

## STEPS TO REPRODUCE THE ISSUE

1. Settings > General. 
2. Uncheck "Anyone can register."
3. Save changes.
4. WooCommerce > Settings > Accounts.
5. Check "Enable registration on the 'My Account' page."
6. Save changes.
7. Visit the My Account page.
8. You can register there.

**Comment by mikejolley** [comment]
I'm against changing this one @aheckler. If this setting were respected, it would break;

- Our settings to allow registration, even if explicitly set to on.
- It would break disabling guest checkout - that requires reg.
- You'd have to explore WP blog settings to change the settings in WC.

To me it makes more sense to keep it as-is so you have separate control.

@justinshreve @claudiosanches  ?

**Comment by mbgrafik** [comment]
My point of view.... a shopowner expect's that users can register and all settings should be available from shop setup and not in different places. You could place a hint in backend "overwrites WP Standard Settings/behaviour"

**Comment by claudiosanches** [comment]
Not to mention that WordPress "registration" is for "subscribers", WooCommerce controls registration of "customers".

**Comment by mikejolley** [comment]
Agreed. Changing this would also be a breaking change since it goes against what WC has done up until now. 

@aheckler hope that clarifies enough for whomever brought it up :)

**Comment by aheckler** [comment]
> To me it makes more sense to keep it as-is so you have separate control.

> Not to mention that WordPress "registration" is for "subscribers", WooCommerce controls registration of "customers".

@claudiosanches @mikejolley These statements may be true, but the distinction is not made clear anywhere in the WC settings.

Perhaps instead of "Enable registration on the 'My Account' page" we should clarify by saying "Enable **customer** registration on the 'My Account' page"?

We could also add a question mark popup/tooltip thing like the My Account Page setting has, in order to explain that the WC settings will override the WP core configuration under Settings > General.

**Comment by mikejolley** [comment]
If you were editing that setting, wouldn't you expect it to *do* something, regardless of WP settings or the wording?

**Comment by mikejolley** [comment]
I'm not against adding the term 'customer'.

**Comment by CzarnaMamba** [comment]
how does it work now?

**Comment by Alehashariq** [comment]
while i check to anyone can register and save changes after that when i go to this window its uncheck automatically

**Comment by Alehashariq** [comment]
wordpress settings general anyone can registered if i check and save changes still its uncheck
