### ISSUE TITLE
wc-template-function.php - There is one " too much.

### ISSUE THREAD

**Issue by grosssmutttr** [woocommerce/woocommerce#13670]
Just checked my page with https://validator.w3.org and saw that there is a " too much in the variations select box:

`$html = '<select id="' . esc_attr( $id ) . '" class="' . esc_attr( $class ) . '" name="' . esc_attr( $name ) . '" data-attribute_name="attribute_' . esc_attr( sanitize_title( $attribute ) ) . '"' . ' " data-show_option_none="' . ( $show_option_none ? 'yes' : 'no' ) . '">';`
		
Line 2077 in wc-template-functions.php after the data-attribute_name=""

Hopefully fixed in the next version :D

**Comment by claudiosanches** [comment]
Already fixed: https://github.com/woocommerce/woocommerce/commit/8adfe15d8f4e3cb38a6d0101d76c9938428771f9
