### ISSUE TITLE
"Only show stock when low" does not work

### ISSUE THREAD

**Issue by ValeDeOro** [woocommerce/woocommerce#13671]
## EXPLANATION OF THE ISSUE

When using the option "only show stock when low" in WooCommerce >> Settings >> Products >> Inventory, the product always displays "in stock". 

The expectation is that no inventory message appears until the low threshold is met. 

![](http://cld.wthms.co/uVtB+)
Link to screenshot: http://cld.wthms.co/uVtB

## STEPS TO REPRODUCE THE ISSUE

1. Set a low threshold (e.g. 2 items) and choose "Only show stock when low"

![](http://cld.wthms.co/uVtB+)
Link to screenshot: http://cld.wthms.co/uVtB

2. Create a product with stock higher than the threshold: 

![](http://cld.wthms.co/HmaK+)
Link to screenshot: http://cld.wthms.co/HmaK

3. Result: "in stock" displays

![](http://cld.wthms.co/QioF+)
Link to screenshot: http://cld.wthms.co/QioF

**Comment by mikejolley** [comment]
This refers to the stock QTY, not the text itself.
