### ISSUE TITLE
WooCommerce 3.0 Shipping Zones

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#13683]
Hi, 

When you first time install the plugin and go to the Shipping Zones panel in Dashboard -> WooCommerce -> Settings -> Shipping Zones and added some zone and when you try to add methods ajax add it inside methods panel but save changes button is blocked and you can't click to save you changes.

If you switch between enable/disable on some method then save button is enabled and you can click on it

Best Regards, 
Nenad

**Comment by NenadObradovic** [comment]
Also if you clicked finally to save, browser always popup the notice Do you want to leave this site? Changes you made may not be saved. Click leave or stay

**Comment by mikejolley** [comment]
I only get the 2nd issue if I don't save, so that appears to be working as it should.

**Comment by mikejolley** [comment]
There is no need to save after adding a method - it saves for you.
