### ISSUE TITLE
[3.0.0-RC1] WC_Order::get_tax_refunded_for_item - unused argument

### ISSUE THREAD

**Issue by Dartui** [woocommerce/woocommerce#13681]
## EXPLANATION OF THE ISSUE
`WC_Order::get_tax_refunded_for_item` method required `$tax_id` argument, but it is unused: https://github.com/woocommerce/woocommerce/blob/71d0702523bcc365403dd3b84b945da5218d88b4/includes/class-wc-order.php#L1679-L1697. This PR removed usage of this variable: https://github.com/woocommerce/woocommerce/commit/ece2b5bf57d55998a804e3f426b659294a6cd8a1.

**Comment by mikejolley** [comment]
It was present in 2.6.x so it has to stay for bw compat. It can be deprecated in the next release.

**Comment by Dartui** [comment]
Can it be changed to optional? I think that something like `get_tax_refunded_for_item($item_id, $item_type = 'line_item', $deprecated = false)` with some checks inside would be even better.

**Comment by mikejolley** [comment]
Looks like it's needed - there is a bug with totals. 

![2017-03-21 at 11 08](https://cloud.githubusercontent.com/assets/90977/24144872/cbfa580a-0e26-11e7-9222-e902a7ed0f40.png)

I only refunded one of the taxes.
