### ISSUE TITLE
'woocommerce_add_order_item_meta' is not called when adding an order manually via backend

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce#13680]
We have some custom product field "Bio" (i.e. product is organic). And this is added to an order item with:
```
// Adds _fr_is_bio to item meta of an order (if Bio)
add_action( 'woocommerce_add_order_item_meta', 'fr_add_bio_to_meta', 10, 3 );
function fr_add_bio_to_meta( $item_id, $values, $cart_item_key ) {
  $product_id = $values['product_id'];
  $is_bio = fr_product_is_bio($product_id);
  if ($is_bio) {
    wc_add_order_item_meta( $item_id, '_fr_is_bio', $is_bio );
  }
}
```

Works **perfectly** if an order is created by a customer through the shop. However, the `woocommerce_add_order_item_meta` does not seem to be called if the order is created **manually** via `WooCommerce` > `Orders` > `Add order` in the backend.

I think that `woocommerce_add_order_item_meta` action should also be called when the order is added through the backend, too. Because of DRY. Moreover, I do also not see another hook or action specific to the backend-added orders. 

WooCommerce version 2.6.14

**Comment by mikejolley** [comment]
I'd suggest waiting for v 3.0.0 which uses the same CRUD system in admin or frontend. Read our dev blog for details.
