### ISSUE TITLE
Selector div showing up in billing fields

### ISSUE THREAD

**Issue by amjad** [woocommerce/woocommerce#13696]
Using latest versions of both WP and WC. Using Safari.

On the checkout field. (click [here](https://www.whitelanelimousine.com) for URL), there is this selector showing up below the state field. I am unable to remove or hide it with CSS. Its not clickable as well.

![screen shot 2017-03-21 at 4 05 01 pm](https://cloud.githubusercontent.com/assets/1428634/24170853/3bea8224-0e50-11e7-804e-592439681a57.png)

**Comment by mikejolley** [comment]
You have a custom select enhancement script on your site - you need to ensure it doesn't kick in for WooCommerce checkout fields which already get enhanced. This is a theme issue.

**Comment by amjad** [comment]
Thanks.
