### ISSUE TITLE
How to get customers against an order ?

### ISSUE THREAD

**Issue by shihaspm** [woocommerce/woocommerce#13706]
## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
> - GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://woocommerce.com/my-account/tickets/ for premium plugin support

Please don't open issues for these types of questions - the question needs more detail anyway. Use the forums :)
