### ISSUE TITLE
[WC 3.0.0 RC1] Issue js in product detail page. Can't click product data tab!

### ISSUE THREAD

**Issue by rafadiot** [woocommerce/woocommerce#13701]
## EXPLANATION OF THE ISSUE
- When you go do Product detail page, you will see this warning : "Option 'ajax' is not allowed for Select2 when attached to a select element."
- Then you can't click Product data tab.

## STEPS TO REPRODUCE THE ISSUE
1. Uploaded WC 3.0.0 RC1
2. Go to Product detail page, then you can't click Product data tab
3. Error js like this attachment: http://prnt.sc/emz6pc

### WordPress Environment ###

Home URL: 
Site URL: 
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.15 (CentOS)
PHP Version: 5.6.27RC1
PHP Post Max Size: 300 MB
PHP Time Limit: 1000
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
WC Database Prefix: stac_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (12) ###

Query Monitor: by John Blackbourn – 2.12.0
Gravity Forms: by rocketgenius – 2.0.3
Advanced Custom Fields PRO: by Elliot Condon – 5.3.9.1
Duplicate Post: by Enrico Battocchi – 2.6
Lockdown WP Admin: by Sean Fisher – 2.3.2
Incassomachtigen voor Woocommerce via PayIBAN: by van Stein en Groentjes – 1.1.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
WPML Multilingual CMS: by OnTheGoSystems – 3.5.3
TinyMCE Advanced: by Andrew Ozz – 4.3.10.1
WooCommerce: by Automattic – 3.0.0-rc.1
Yoast SEO: by Team Yoast – 3.4.2
WP Migrate DB: by Delicious Brains – 0.8

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (euro)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #2425 - /shop/
Cart: #2408 - /cart/
Checkout:  Page does not contain the shortcode.
My account:  Page not set

### Theme ###

WooCommerce Support:  Not declared

### Templates ###

Overrides: /woocommerce/archive-product.php
/woocommerce/auth/footer.php
/woocommerce/auth/form-grant-access.php
/woocommerce/auth/form-login.php
/woocommerce/auth/header.php
/woocommerce/cart/cart-empty.php
/woocommerce/cart/cart-item-data.php
/woocommerce/cart/cart-shipping.php
/woocommerce/cart/cart-totals.php
/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.0
/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
/woocommerce/cart/mini-cart.php
/woocommerce/cart/proceed-to-checkout-button.php
/woocommerce/cart/shipping-calculator.php
/woocommerce/checkout/cart-errors.php
/woocommerce/checkout/form-billing.php
/woocommerce/checkout/form-checkout.php
/woocommerce/checkout/form-coupon.php
/woocommerce/checkout/form-login.php
/woocommerce/checkout/form-pay.php
/woocommerce/checkout/form-shipping.php
/woocommerce/checkout/payment-method.php
/woocommerce/checkout/payment.php
/woocommerce/checkout/review-order.php
/woocommerce/checkout/terms.php
/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
/woocommerce/content-product.php
/woocommerce/content-product_cat.php
/woocommerce/content-single-product.php
/woocommerce/content-widget-product.php
/woocommerce/emails/admin-cancelled-order.php
/woocommerce/emails/admin-failed-order.php
/woocommerce/emails/admin-new-order.php
/woocommerce/emails/customer-completed-order.php
/woocommerce/emails/customer-invoice.php
/woocommerce/emails/customer-new-account.php
/woocommerce/emails/customer-note.php
/woocommerce/emails/customer-on-hold-order.php
/woocommerce/emails/customer-processing-order.php
/woocommerce/emails/customer-refunded-order.php
/woocommerce/emails/customer-reset-password.php
/woocommerce/emails/email-addresses.php
/woocommerce/emails/email-customer-details.php
/woocommerce/emails/email-footer.php
/woocommerce/emails/email-header.php
/woocommerce/emails/email-order-details.php
/woocommerce/emails/email-order-items.php version 2.1.2 is out of date. The core version is 3.0.0
/woocommerce/emails/email-styles.php
/woocommerce/emails/plain/admin-cancelled-order.php
/woocommerce/emails/plain/admin-failed-order.php
/woocommerce/emails/plain/admin-new-order.php
/woocommerce/emails/plain/customer-completed-order.php
/woocommerce/emails/plain/customer-invoice.php
/woocommerce/emails/plain/customer-new-account.php
/woocommerce/emails/plain/customer-note.php
/woocommerce/emails/plain/customer-on-hold-order.php
/woocommerce/emails/plain/customer-processing-order.php
/woocommerce/emails/plain/customer-refunded-order.php
/woocommerce/emails/plain/customer-reset-password.php
/woocommerce/emails/plain/email-addresses.php
/woocommerce/emails/plain/email-customer-details.php
/woocommerce/emails/plain/email-order-details.php
/woocommerce/emails/plain/email-order-items.php version 2.1.2 is out of date. The core version is 3.0.0
/woocommerce/global/breadcrumb.php
/woocommerce/global/form-login.php
/woocommerce/global/quantity-input.php
/woocommerce/global/sidebar.php
/woocommerce/global/wrapper-end.php
/woocommerce/global/wrapper-start.php
/woocommerce/loop/add-to-cart.php
/woocommerce/loop/loop-end.php
/woocommerce/loop/loop-start.php
/woocommerce/loop/no-products-found.php
/woocommerce/loop/orderby.php
/woocommerce/loop/pagination.php
/woocommerce/loop/price.php
/woocommerce/loop/rating.php
/woocommerce/loop/result-count.php
/woocommerce/loop/sale-flash.php
/woocommerce/myaccount/dashboard.php
/woocommerce/myaccount/downloads.php version 2.6.0 is out of date. The core version is 3.0.0
/woocommerce/myaccount/form-add-payment-method.php
/woocommerce/myaccount/form-edit-account.php
/woocommerce/myaccount/form-edit-address.php
/woocommerce/myaccount/form-login.php
/woocommerce/myaccount/form-lost-password.php
/woocommerce/myaccount/form-reset-password.php
/woocommerce/myaccount/lost-password-confirmation.php
/woocommerce/myaccount/my-account.php
/woocommerce/myaccount/my-address.php
/woocommerce/myaccount/my-downloads.php
/woocommerce/myaccount/my-orders.php
/woocommerce/myaccount/navigation.php
/woocommerce/myaccount/orders.php
/woocommerce/myaccount/payment-methods.php
/woocommerce/myaccount/view-order.php
/woocommerce/notices/error.php
/woocommerce/notices/notice.php
/woocommerce/notices/success.php
/woocommerce/order/form-tracking.php
/woocommerce/order/order-again.php
/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 3.0.0
/woocommerce/order/order-details-item.php version 2.5.0 is out of date. The core version is 3.0.0
/woocommerce/order/order-details.php version 2.6.0 is out of date. The core version is 3.0.0
/woocommerce/order/tracking.php
/woocommerce/product-searchform.php
/woocommerce/single-product/add-to-cart/external.php
/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.0
/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
/woocommerce/single-product/add-to-cart/variable.php
/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
/woocommerce/single-product/add-to-cart/variation.php
/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.0.0
/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.0.0
/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.0.0
/woocommerce/single-product/rating.php
/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
/woocommerce/single-product/review-meta.php version 2.6.0 is out of date. The core version is 3.0.0
/woocommerce/single-product/review-rating.php version 2.6.0 is out of date. The core version is 3.0.0
/woocommerce/single-product/review.php
/woocommerce/single-product/sale-flash.php
/woocommerce/single-product/share.php
/woocommerce/single-product/short-description.php
/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
/woocommerce/single-product/tabs/description.php
/woocommerce/single-product/tabs/tabs.php
/woocommerce/single-product/title.php
/woocommerce/single-product/up-sells.php
/woocommerce/single-product-reviews.php
/woocommerce/single-product.php
/woocommerce/taxonomy-product_cat.php
/woocommerce/taxonomy-product_tag.php

**Comment by mikejolley** [comment]
This will be caused by an outdated select2 ajax enhanced field on your product page. WooCommerce does not render anything like that, so it is likely the theme.

It needs to be updated and migrated to select2 v4 https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#select2-version-4
