### ISSUE TITLE
(WC 3.0.0 RC1) Can't change product status

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#13708]
I have two issues.
1. When i put some product tags, the product was turned from publish to scheduled automatically.
2. I can't change the schedule status to publish status both on quick edit or edit. there is maybe missing publish status either.

![screen shot 2017-03-22 at 7 05 02 am](https://cloud.githubusercontent.com/assets/2909982/24195043/9ac6e7c8-0ece-11e7-9008-7234b01adb31.png)

**Comment by mikejolley** [comment]
Matches the post screen - if you want it to publish, you need to change the date it's scheduled for from a future date to now/past date.

**Comment by kevin25** [comment]
it was automatically changed from publish status to scheduled status after i added some tags via quick edit. I tried to change the date but no luck.

**Comment by mikejolley** [comment]
What was the status before it changed, and what is the timezone setting in Settings > General. And does the status page complain about UTC timezones?

**Comment by kevin25** [comment]
it was publish status. The timezone is UTC-5.

**Comment by mikejolley** [comment]
Post system status report.

**Comment by mikejolley** [comment]
FYI I'm not able to replicate this either so perhaps you can make a new product and see what steps you need to take to make it turn scheduled.

AND THEN repeat the test for a new post and see if it does the same.

**Comment by kevin25** [comment]
> `
### WordPress Environment ###


WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 7.1.2RC1
PHP Post Max Size: 8 MB
PHP Time Limit: 1200
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: mug_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.41
Contact Form 7: by Takayuki Miyoshi – 4.7
Google Authenticator: by Henrik Schack – 0.48
Woocommerce Products Price Bulk Edit: by Mostafa Qanbari – 2.0
PixelYourSite PRO: by PixelYourSite – 5.0.9
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.1.7
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SEO Optimized Images: by priyanshu.mittal – 1.6.7
WooCommerce Advanced Shipping - Advanced Pricing: by Jeroen Sormani – 2.1.0
WooCommerce Advanced Shipping: by Jeroen Sormani – 1.0.13
WooSwatches - Woocommerce Color or Image Variation Swatches: by parbat chaudhari – 2.2.9
WooCommerce Stripe Gateway: by WooCommerce – 3.1.3
WooCommerce: by Automattic – 3.0.0-rc.1
Yoast SEO Premium: by Team Yoast – 4.3
WP Rocket: by WP Media – 2.9.6
Yoast WooCommerce SEO: by Team Yoast – 3.0
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3-beta-1
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

**Comment by kevin25** [comment]
i added some product tags like these by using Quick edit.

autism awareness 2017 shirt, autism awareness products, autism awareness products bulk, autism awareness products clothing, autism awareness products for dads, Autism harry potter shirt, Autism harry potter t-shirt, Autism harry potter tshirt, harry potter Autism t-shirt

**Comment by mikejolley** [comment]
Do it again please. And then repeat for posts. If I cannot replicate this (or you cannot) it doesn't help.

**Comment by mikejolley** [comment]
Got it. 

New product. Date shows up yesterday (?). Then quick edit schedules it. Looking into this now.

**Comment by kevin25** [comment]
Yes. It was.

**Comment by kevin25** [comment]
Any update on this?
