### ISSUE TITLE
VAT NO - required by law and missing in WooCommerce

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#13715]
EU customers are required to write their **VAT NO** account on their Invoices.
Most often they forget to write the VAT NO while ordering. It's something that is required just like address or phone number.

Is there a way to add a VAT NO  field to the order so that they will remember to write it?
This cause trouble for merchants as we are required to rewrite our invoices after we send them. It's very frustrating and time consuming.

Can you support it in WooCommerce?

This can be either a separate field or a field that will be attached to the customer address.

**Comment by mikejolley** [comment]
Includes validation: https://woocommerce.com/products/eu-vat-number/

Or use the various checkout editor plugins.

This is only for B2B, not all stores.

**Comment by UserName011** [comment]
@mikejolley  This is not the same...
This plugin actually disable the vat for the order.

The scenario I'm talking about and it's the most common scenario is that the customer only specify the VAT NO. We charge the VAT regularly and then he get refund with our Invoice.
This is for example how it works in Amazon Europe. 

So all is needed is a field to write the VAT NO. It's just text to appear on Invoice nothing more.

**Comment by mikejolley** [comment]
It is the same. You collect the VAT number and it can (optionally) remove the VAT from the order, as it should in the EU if they have a valid EU VAT number.

There are other solutions/snippets/checkout editors if you prefer - search.

This is for B2B sites in the EU, not all users. So I don't think it belongs in core, thats why there are extensions.
