### ISSUE TITLE
Setup Wizard Filters

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13716]
Allow extensions to change steps and insert their own content for the steps.

**Comment by claudiulodro** [comment]
Just out of curiosity, what's the use-case for this? Wouldn't the user have run the setup wizard *before* activating any extensions?

**Comment by mikejolley** [comment]
@claudiulodro Bundled i.e. pre-installed with hosting

**Comment by mikejolley** [comment]
This is taken care of and RTM in https://github.com/woocommerce/woocommerce/pull/13817 and will be part of 3.1 release.
