### ISSUE TITLE
(WC 3.0.0 RC1) Select2 Loading failed error

### ISSUE THREAD

**Issue by fakeartist** [woocommerce/woocommerce#13714]
Hi. I have this issue with the new select2. To recreate it, follow these steps:

1.  Go to a page of woocommerce where it uses select2 (eg. order)
2. Go to select2 "search for a customer" field.
3. Write 3 characters.
4. While it says "searching...", press one more (or more) characters.
5. A message appears "loading failed" until the results are returned.

Seems like a bug to me, right?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/13628
