### ISSUE TITLE
[3.0] Refunded order email - problem with resending email

### ISSUE THREAD

**Issue by Dartui** [woocommerce/woocommerce#13711]
## EXPLANATION OF THE ISSUE
After trying to resend **fully** refunded email I have got email with headings from **partial** refunded order. It is caused because of this part of code: https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php#L133 and this one: https://github.com/woocommerce/woocommerce/blob/master/includes/emails/class-wc-email-customer-refunded-order.php#L108

`$order` will be always true, so `$partial_refunded` will be true also. Also this is PR which added `$order` to metabox actions: https://github.com/woocommerce/woocommerce/pull/13135

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/13738
