### ISSUE TITLE
[REST API] Payment gateways don't return updated values in PUT requests

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#13722]
Changes `enabled` or `description` do not apply the change changes in `settings` data.

**Comment by mikejolley** [comment]
@claudiosanches I just tested this - `https://local.wordpress.dev/wp-json/wc/v2/payment_gateways/bacs` and changed both. Both changes were reflected in both the response, and in admin.

**Comment by claudiosanches** [comment]
@mikejolley here: https://cloudup.com/c2VQ6TPfM8v

That `"value": "yes"` should be `"value": "no"` after updated.
