### ISSUE TITLE
Portugal shipping area: how to split by postcodes?

### ISSUE THREAD

**Issue by LyonBeton** [woocommerce/woocommerce#13735]
Hello,
I've issue with assigning specific areas of portugal to specific shipping zone in Woocommerce.
I tried to use postcodes as there is no district management.
It's not working but it may come from me.
Let me explain what I've tried so far.

For Islands from France ant Italy I use the postcodes to include or exclude them of shipping zones like this: 
![image](https://cloud.githubusercontent.com/assets/20840018/23654836/e43d09f2-0332-11e7-8b5a-91e8e13827b9.png)
It works well.

For portugal as I understood, there is only 4 digits for the postcodes.
So I tried to apply the same pattern: 
![image](https://cloud.githubusercontent.com/assets/20840018/23654898/1e2df7f2-0333-11e7-81cb-404c5b66cf48.png)
But It ain't working.
I've also tried a "wildcards" pattern like this:
00*
01*
02*
03*
04*
05*
06*
But it's not working too.

Did I made a mistake or is there an issue with Portugal in woocommerce ?
Thanks.

**Comment by mikejolley** [comment]
Check the rates themselves; I just tested the above one and entered `0200` postcode and it matched fine.
