### ISSUE TITLE
Removed products and orders still show up in app - IOS App

### ISSUE THREAD

**Issue by JimmyAppelt** [woocommerce/woocommerce#13741]
WC 2.6.14
IOS App 1.1.6.2

All removed products and orders that are deleted (also out of the trash) still show in the App. This is amazingly frustrating.

Kind regards
Jim

**Comment by mikejolley** [comment]
I've logged this in the correct place https://github.com/woocommerce/woocommerce-mobile/issues/163

**Comment by JimmyAppelt** [comment]
@mikejolley I'm sorry is that a private repo ?

**Comment by mikejolley** [comment]
Yes it is.

**Comment by Bnbstories** [comment]
still no solution to this ?

**Comment by mikejolley** [comment]
It was closed:

> We've built the ability to both automatically and manually purge orders/products from the local app database. This will remove any trashed objects the user is seeing locally in the app. We have to do this because we have no clean way to verify all existing orders/products with the API efficiently.
