### ISSUE TITLE
Multiple webhooks firing

### ISSUE THREAD

**Issue by achadee** [woocommerce/woocommerce#13760]
We have a customer that is firing multiple webhooks per single event (product.update, order.update etc.)

I have confirmed that it is a woocommerce issue by looking at the webhook logs under the API settings. It seems to fire around 9 webhooks.

wc: 2.6.14
wp: 4.7.3
api version: v3 legacy

**Comment by mikejolley** [comment]
Product events here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-webhook.php#L651-L656

Order events here: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-webhook.php#L638-L643

@claudiosanches can correct me if I'm wrong, but these fire for ALL actions which get triggered, even if triggered multiple times by multiple things. e.g. you save a product twice, or an extension saves and triggers those actions.

Webhooks will get a refactor during https://github.com/woocommerce/woocommerce/issues/12439 where this could be looked at.

**Comment by achadee** [comment]
hmmmm this can definitely lead to possible race conditions on the receiving end, thanks for looking into it :)

**Comment by looknear** [comment]
Is that a known issue? as it's still a cause for major headache now, end of 2018.
With latest woo update - i still see 3 times of "order updated" event fired for every single order.
any solution for that?

**Comment by rrennick** [comment]
#22088 should address the issue with multiple actions for one event.
