### ISSUE TITLE
Variation does not get selected in dropdown when we pass inch " in variation name.

### ISSUE THREAD

**Issue by dixitadusara** [woocommerce/woocommerce#13768]
Hello Team,

I have an issue while passing direct url into browser: 

Below are steps to reproduce: 

1. I have one product with variation name: 66" Wide
2. When I pass direct url into browser https://xyz.com/product/rhr-8-aluminum-spoiler/?attribute_size=66%22+Wide&attribute_color=Red
3. On product detail page in dropdwon menu variation is not getting selected. because I have special charater in my variation name:

Would you please let me know how can I resolve it ?

Thanks, 

![variation](https://cloud.githubusercontent.com/assets/24749815/24299118/1aa46654-10ce-11e7-9b83-734cdfab36ab.png)

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/13762
