### ISSUE TITLE
Problem authenticating with /wp-json/wc/v1 using OAuth1 and filter 

### ISSUE THREAD

**Issue by davidduus** [woocommerce/woocommerce#13767]
We have discovered a couple of issues in OAuth1 when using filter param(s). 

Se example below. 

_**Request from Client (note correctly sorted filter params);**_

/wp-json/wc/v1/orders?filter%5Bdate_query%5D%5Bafter%5D=2031-12-01T00:00:00&filter%5Bpaged%5D=0&filter%5Bposts_per_page%5D=9999999999&oauth_callback=oob&oauth_consumer_key=ck_7641ad8a2ff1e0a61d55e18e9f51d948b42ff7e0&oauth_nonce=u2TLdlk7k3wPiX5tPkUWAn%2Ba&oauth_signature=Es8dmrGSP1/ZBhOheb1N6%2BLBiI0%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1490361835&order=asc&orderby=date

_**Correct OAuth1 base string;**_

GET&http://localhost/wp-json/wc/v1/orders?filter%5Bdate_query%5D%5Bafter%5D=2031-12-01T00:00:00&filter%5Bpaged%5D=0&filter%5Bposts_per_page%5D=9999999999&oauth_callback=oob&oauth_consumer_key=ck_7641ad8a2ff1e0a61d55e18e9f51d948b42ff7e0&oauth_nonce=u2TLdlk7k3wPiX5tPkUWAn%2Ba&oauth_signature=Es8dmrGSP1/ZBhOheb1N6%2BLBiI0%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1490361835&order=asc&orderby=date

_**Server side base string that WooCommerce uses;**_

GET&http://localhost/wp-json/wc/v1/orders&filter%5Bdate_query%5D=Array&filter%5Bpaged%5D=0&filter%5Bposts_per_page%5D=9999999999&oauth_callback=oob&oauth_consumer_key=ck_7641ad8a2ff1e0a61d55e18e9f51d948b42ff7e0&oauth_nonce=u2TLdlk7k3wPiX5tPkUWAn%2Ba&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1490361835&order=asc&orderby=date

_**Three issues to report;**_

1) Double array params (like filter[...][...]) are not correctly expanded (see "date_query%5D=Array" in request example above)

2) Query parameters containing [...] are not properly sorted before constructing OAuth1 signature. Seems to be the same bug as in v3 API (https://github.com/woocommerce/woocommerce/issues/11223). Possible to circumvent by sorting. To avoid these issues you could use raw request data for generating the OAuth1 signature not what PHP parses it into.

 - For example, take $_SERVER['QUERY_STRING']
 - Split on &-characters.
 - Sort the result and use that to build the base string
 - Thus eliminating any and all issues caused by php/etc transforming the query parameters.

3) None of the sorting issues in OAuth1 with filter is stated in v1 docs (which it is in deprecated v3 docs). May be good to emphasize this in v1 docs as well.

**Comment by mikejolley** [comment]
@davidduus `filter` is no longer supported by WP since 4.7, and we don't fully support it either. It's being dropped from the newer APIs. This is a won't fix item.

**Comment by claudiosanches** [comment]
`?filter%5Bdate_query%5D%5Bafter%5D=2031-12-01T00:00:00&filter%5Bpaged%5D=0&filter%5Bposts_per_page%5D=9999999999&`

Why using this filters?

1. `filter[date_query]`... There is already `after` that you can use.
2 `filter[paged]` already have `page`.
3. `filter[posts_per_page]` you can use `per_page`

See the docs:
https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders

![screenshot from 2017-03-24 11-56-56](https://cloud.githubusercontent.com/assets/1264099/24299769/01453f7a-1089-11e7-9468-6b7f2c454a92.png)

Closing since `filter` is deprecated and should not be used in any case.
