### ISSUE TITLE
How Upload image from a local disk to product in WooCommerce

### ISSUE THREAD

**Issue by eduarchap** [woocommerce/woocommerce#13769]
## EXPLANATION OF THE ISSUE

How Upload image from a local disk to product in WooCommerce

**Comment by mikejolley** [comment]
>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>- https://wordpress.org/support/plugin/woocommerce for general support
>- https://woocommerce.com/my-account/tickets/ for premium plugin support
