### ISSUE TITLE
Getting an order object on woocommerce_init

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce#13763]
## EXPLANATION OF THE ISSUE

`wc_get_order` is not available on `woocommerce_init`, but `wc_get_product` is. This also happens in 2.6, so the issue isn't that important at this point but good to have w.r.t. consistency.

## STEPS TO REPRODUCE THE ISSUE

1. Have a product and an order in place (remember their IDs)
2. Put this code in `mu-plugins/test.php`:
```
<?php
add_action( 'woocommerce_init', 'test' );
function test() {
    $order = wc_get_order( $order_id );
    var_dump( $order );

    $product = wc_get_product( $product_id );
    var_dump( $product );
}
```
3. Observe the results
Expected: Order object shows, product order shows
Actual: Order object is false ❌, product order shows ✅ 

## WORKAROUND
Use the `init` action instead.

## INVESTIGATION
Investigation with @mikejolley has shown that this has to do with the way we're determining `$classname`.

Orders rely on a global:
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order-factory.php#L33

Products do not:
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-factory.php#L43

The global `wc_order_types` being null at that point currently is by design, because `woocommerce_init` is init priority 0 before post types.

## PROPOSED SOLUTIONS
- Change the notice at https://github.com/woocommerce/woocommerce/blob/master/includes/wc-order-functions.php#L97 to be consistent with this behaviour (should be a simple fix)
- Change the loading order (architectural/design change, not a simple fix)

**Comment by yurisa2** [comment]
This came around again in version 5.2.3, released on sep 04 2019.
Need to run INIT.

in 5.2.2 worked fine.
