### ISSUE TITLE
Transients causing bad stock values using 'get_total_stock()'

### ISSUE THREAD

**Issue by rafdizzle86** [woocommerce/woocommerce#13774]
## EXPLANATION OF THE ISSUE

Built-in transients within `get_children()` return bad results for variable products assuming you're adding new variations programmatically (via a plugin) and not through the Woo UI. See: [here](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/class-wc-product-variable.php#L136) and [here](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/class-wc-product-variable.php#L108)

This impacts a function called `get_total_stock()` as it uses `get_children()`. See [here](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/abstracts/abstract-wc-product.php#L226).

In my plugin, I'm adding new variations to a variable product programmatically which doesn't reset the `wc_product_children_<variable_prod_id>` transient. Therefore when I call `get_total_stock()` I'm getting bad stock data which doesn't take into account the new variations I'm adding.

It would be nice if transients related to woo products got reset via a post update hook or something like this so that plugin developers wouldn't have to worry about reseting the transients manually / having various woo-product functions return obsolete data.

Also if the transient prefix name "`wc_product_children_`" could be stored in a constant instead of defining it in-line, then it would be good for plugin developers as well in case the name changed.

## STEPS TO REPRODUCE THE ISSUE

1. Create a variable product with 1 variation, make sure total stock is 0
2. Add a new variation _programmatically_ (e.g. via a plugin) to the variable you created in step 1; set the stock > 0 (e.g. 5)
3. Note that the function `get_total_stock()` when called on the parent variable product will return 0 where it should return 1 - this is because the `get_children` function is still using the `wc_product_children_<variable_prod_id>` transient to query for all the children ids.
4. Delete the `wc_product_children_<variable_prod_id>` transient
5. Call `get_total_stock()` on the variable product again and notice that the stock is now what you set it to in step 2.

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: http://lightspeed.local
Site URL: http://lightspeed.local
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/5.6.10 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version: 5.6.10
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/0.9.8zd

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.42 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. PayPal IPN won't work with your server. Contact your hosting provider. Error: cURL error 35: Unsupported SSL protocol version
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (4) ###

WooCommerce LightSpeed POS: by WooThemes – 1.4.2
WooCommerce: by WooThemes – 2.6.14
WP Crontrol: by John Blackbourn & Edward Dale – 1.4
WP PHP Console: by Fulvio Notarstefano – 1.5.0

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4 - /?page_id=4
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My Account: #7 - /?page_id=7

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Twenty Fourteen
Version: 1.9
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by mikejolley** [comment]
This doesn't need action. In the current version, you can `delete_transient` if working with these with custom code.

As of `3.0.0`, if you use the CRUD objects, transients and cache are handled for you on save.

**Comment by rafdizzle86** [comment]
@mikejolley can you provide a link to the CRUD objects for manipulating woo-product objects?

**Comment by mikejolley** [comment]
Take a look in the wiki on this site.
