### ISSUE TITLE
22 php issues revealed in 3.3. rc2

### ISSUE THREAD

**Issue by Tobias-Conrad** [woocommerce/woocommerce#13776]
## EXPLANATION OF THE ISSUE

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/templates/cart/cross-sells.php

FOUND 1 ERROR AFFECTING 1 LINE

 36 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/templates/single-product/related.php

FOUND 1 ERROR AFFECTING 1 LINE

 36 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/templates/single-product/up-sells.php

FOUND 1 ERROR AFFECTING 1 LINE

 36 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/templates/single-product/add-to-cart/grouped.php

FOUND 1 ERROR AFFECTING 1 LINE

 36 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/includes/wc-core-functions.php

FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE

 1370 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4.

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/includes/api/legacy/v3/class-wc-api-server.php

FOUND 4 ERRORS AFFECTING 4 LINES

 664 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
 668 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
 669 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
 672 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/includes/api/legacy/v2/class-wc-api-server.php

FOUND 4 ERRORS AFFECTING 4 LINES

 658 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
 662 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
 663 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
 666 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/includes/api/legacy/v1/class-wc-api-server.php

FOUND 4 ERRORS AFFECTING 4 LINES

 615 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
 619 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
 620 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
 623 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/includes/gateways/simplify-commerce/includes/Simplify/Authentication.php

FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES

 56 | WARNING | Method name "Simplify_Authentication::__construct1" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
 60 | WARNING | Method name "Simplify_Authentication::__construct2" is discouraged; PHP has reserved all method names with a double underscore prefix for future use
 65 | WARNING | Method name "Simplify_Authentication::__construct3" is discouraged; PHP has reserved all method names with a double underscore prefix for future use

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/includes/class-wc-download-handler.php

FOUND 1 ERROR AFFECTING 1 LINE

 321 | ERROR | Function set_magic_quotes_runtime() is deprecated since PHP 5.3 and removed since PHP 7.0

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/includes/admin/views/html-admin-page-status-report.php

FOUND 1 ERROR AFFECTING 1 LINE

 166 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.

## STEPS TO REPRODUCE THE ISSUE

plugin "PHP Compatibility Checker" installed and scanned.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: http://dummy.santegra-international.com
Site URL: http://dummy.santegra-international.com
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: nginx/1.10.2
PHP Version: 7.0.9
PHP Post Max Size: 100 MB
PHP Time Limit: 1200
PHP Max Input Vars: 3000
cURL Version: 7.47.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: dummy_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

PHP Compatibility Checker: von WP Engine – 1.4.0
WooCommerce Beta Tester: von Mike Jolley – 1.0.2
WooCommerce: von Automattic – 3.0.0-rc.2
WooCommerce & WP Email Marketing Integration: von Tobias B. Conrad – 3.6.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #5 - /shop/
Warenkorb: #6 - /warenkorb/
Kasse: #7 - /kasse/
My account: #8 - /mein-konto/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://de.wordpress.org/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –
````

**Comment by claudiosanches** [comment]
@Tobias-Conrad note that "PHP Compatibility Checker" don't look for conditional code, like for example:

```
FOUND 4 ERRORS AFFECTING 4 LINES

664 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
668 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
669 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
672 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/includes/api/legacy/v2/class-wc-api-server.php

FOUND 4 ERRORS AFFECTING 4 LINES

658 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
662 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
663 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
666 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.

FILE: /var/www/clients/client1/web29/web/wp-content/plugins/woocommerce-woocommerce-3946654/includes/api/legacy/v1/class-wc-api-server.php

FOUND 4 ERRORS AFFECTING 4 LINES

615 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
619 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
620 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
623 | ERROR | Global variable '$HTTP_RAW_POST_DATA' is deprecated since PHP 5.6 and removed since PHP 7.0 - use php://input instead.
```

All comes from a conditional code to suporte old versions of PHP:

https://github.com/woocommerce/woocommerce/blob/a9b8d41500af92950688383c25d5f0e8ad2d5f83/includes/api/legacy/v3/class-wc-api-server.php#L652-L673

**Comment by claudiosanches** [comment]
I just tested it and all things that you listed here are false positives.
Please check this kind of thing before posting, thanks.

**Comment by Tobias-Conrad** [comment]
thank you. no it is clear.
i was not able to clear it.
