### ISSUE TITLE
Cart.php 

### ISSUE THREAD

**Issue by sinashamsizadeh** [woocommerce/woocommerce#13780]
Hi There,

In new project, we started a shop with Woocommerce. We created a theme based on Woocommerc hooks without templates, but when we went to edit cart page with product we realized that we can't apply any change inside of form tag. In fact we’re going to implement another structure with 2 columns but unfortunately we could not find any hook to be able to remove current content with it; otherwise we’d like to add a pull request.

Thanks in advance
![2017-03-27_16-34-19](https://cloud.githubusercontent.com/assets/26713060/24357029/7686774c-1311-11e7-8fa6-cbe813b37371.png)

**Comment by mikejolley** [comment]
If you're making major structural changes, templates are the way to go. You're not moving things around so hooks are not really suitable.
