### ISSUE TITLE
Data stores/Data object - Only save changes when updating meta.

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13791]
See https://github.com/woocommerce/woocommerce/pull/13784

**Comment by crodas** [comment]
Can I assign it to myself @mikejolley? I wanna get this through, but I agree with your thoughts on #1378, this is not blocking and it needs more testings.

**Comment by mikejolley** [comment]
Sure thing :)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/14751
