### ISSUE TITLE
There is an Unresponsive Scripting error displayed on adding new Shipping zone

### ISSUE THREAD

**Issue by galakhyati** [woocommerce/woocommerce#13797]
Having v3.0.0 RC 2, I am trying to add a new shipping zone under Shipping tab under WooCommerce> Settings page. After adding the shipping zone name, I tried adding the country name in Zone regions field, there the screen turned black, whereas I was expecting the searched county to be listed. 

![image](https://cloud.githubusercontent.com/assets/7382505/24406488/07ee24da-13e6-11e7-85f7-175c06b02311.png)

http://prntscr.com/epgzfe

STEPS TO REPRODUCE THE ISSUE

1. Go to WooCommerce Settings page.
2. Go to Shipping tab and go to Shipping Zone.
3. Click on Add Shipping Zone button.
4. Enter the shipping zone and then while adding the shipping region, the issue is 

SYSTEM STATUS REPORT
`
### WordPress Environment ###

Home URL: http://localhost/wordpress-ordddpro2
Site URL: http://localhost/wordpress-ordddpro2
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Unix) OpenSSL/1.0.2h PHP/7.0.9 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version: 7.0.9
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Order Delivery Date Pro for WooCommerce: by Tyche Softwares – 6.5.1
WooCommerce: by Automattic – 3.0.0-rc.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #30 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
@galakhyati Just tested in firefox, chrome, and safari - no issues.

Turn off other extensions (Order Delivery Date Pro) and re-test after flushing all caches.

**Comment by galakhyati** [comment]
I suppose it is the issue when Order Delivery Date Pro plugin is enabled.

Just tried by flushing the cache in Chrome and Firefox, could not replicate the issue when Order Delivery Date Pro plugin is inactive. Thanks for the quick reply. Really appreciate it.

**Comment by mikejolley** [comment]
Maybe they have logic hooking into there; please check with the author.

**Comment by galakhyati** [comment]
@mikejolley I am still able to get the scripting error while having only WooCommerce activated on my store. I contacted the plugin author, they confirmed they do not have any hooks for shipping method.

The error is coming when I focus on the Shipping Zone field. The screen goes black and then comes back again until the values of the fields are fetched.

The issue is coming on Firefox browser. This is version of Firefox on my machine: http://prntscr.com/eq7f9a
 
Also tried by flushing cache and cookies. Still, the issue persists.

**Comment by mikejolley** [comment]
> Just tried by flushing the cache in Chrome and Firefox, could not replicate the issue when Order Delivery Date Pro plugin is inactive.

What was that then?

> The error is coming when I focus on the Shipping Zone field. The screen goes black and then comes back again until the values of the fields are fetched.

There is not fetching - the counties are local.
