### ISSUE TITLE
Single Product Images

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#13794]
Hi,

I have a problem with a new single product layout and new functions/variables, because you changed a lot code for product-image and product-thumbnails and for my case I need to improve these files to have compatibility for both version of plugins for mine customers.

Problem is if I want:
1) To override these templates inside theme folder with older version to leave same look/design I got the notice on live because you set some functions to be deprecated and I can't leave it because you can decide at any moment to remove it and I will got fatal error.
2) If I want to override these templates (html) with filter / hooks then I will override both templates at the same time because you added same filter name **woocommerce_single_product_image_thumbnail_html** inside both files and this filter can't be used anywhere because you override and parent and child elements at the same time, this is my opinion.
3) Additional issues, you changed with each major plugin updates core functions name, variables etc and authors always need to implemented compatibility for early version of plugins and for the latest one, a lot sites goes down with fatal error, because that functions doesn't exist in early version and also you didn't add it in deprecated functions, for me this is not a god practice for customers (yours and for authors). Example cart.php template early function name was **$_product->get_title()** and new one **$_product->get_name()** , then thankyou.php template **$order->payment_method_title** now is  **$order->get_payment_method_title()** same issue for **$order->get_payment_method()** etc etc, and there is no any deprecated notice or something else for these problem and only you got is white page and fatal error. 
4) Also can you set some different class name for main feature image on single product, so custom css or core style modification will be easily
5) Early was hook around thumbnail images apply_filters( 'single_product_small_thumbnail_size', 'shop_thumbnail' ) so we can be able to change image size if we want, at this version you remove it, can you return it back it's a good feature.

I hope you will fix some of these issues and implement major updates with better logic and compatibility with early versions. Thanks and sorry for my English

Best regards,
Nenad

**Comment by mikejolley** [comment]
> because you changed a lot code for product-image and product-thumbnails and for my case I need to improve these files to have compatibility for both version of plugins for mine customers.

Thats how this works. If you don't want this burden, don't change template files. Use hooks only.

> To override these templates inside theme folder with older version to leave same look/design I got the notice on live because you set some functions to be deprecated and I can't leave it because you can decide at any moment to remove it and I will got fatal error.

Use conditionals to detect if functionality is available.

> If I want to override these templates (html) with filter / hooks then I will override both templates at the same time because you added same filter name woocommerce_single_product_image_thumbnail_html inside both files and this filter can't be used anywhere because you override and parent and child elements at the same time, this is my opinion.

Look at the naming and intention of the file; it handles the thumbnail image. Both the single and gallery use thumbnails.

> Additional issues, you changed with each major plugin updates core functions name, variables etc and authors always need to implemented compatibility for early version of plugins and for the latest one, a lot sites goes down with fatal error, because that functions doesn't exist in early version and also you didn't add it in deprecated functions, for me this is not a god practice for customers (yours and for authors).

This is why you use conditional code. 

> Also can you set some different class name for main feature image on single product, so custom css or core style modification will be easily

They are being introduced slowly, but old ones are kept around for bw compat. 

> Early was hook around thumbnail images apply_filters( 'single_product_small_thumbnail_size', 'shop_thumbnail' ) so we can be able to change image size if we want, at this version you remove it, can you return it back it's a good feature.

Not required. The user can change thumbnail sizes in settings, or it can be done with code. Resizing is possible with CSS.
