### ISSUE TITLE
Can't get products by categories using Beta 3.0.0 

### ISSUE THREAD

**Issue by WaldenStew** [woocommerce/woocommerce#13790]
Actually i use WordPress 4.6.4 with Woocommerce 2.6.11 and everything is OK.

The application I have developed works perfectly.

Now, i want to try the new beta 3.0.0 with wordpress 4.7 to prepare to upgrade my application soon.

But my first "Get request" does not work correctly

For the moment, i get my product list by this request : 
$woo->get("products", array('category' => $id_category, 'page' => $page, 'per_page' => $limit));
 but in the last version i can't get products with the first param category of my array. The API retuns me a 'Syntax error'.

If i try the following request, it works correctly (but not sort by category ;) )

$woo->get("products", array( 'page' => $page, 'per_page' => $limit));

So my question is:

Is it a bug? or the API categories request has changed ? 

PS: I worked last six months on your API thanks for your help and your last answers Mike, who really helped me ( And Claudio's answers on the forum too 🥇 )

**Comment by WaldenStew** [comment]
Ok ... i'm just trying to replace 'category' by 'categories' and it works...but what is the correct term ? 

Should I realize specific conditions for future 3.0.0 users in my application or will this be corrected?

Thanks .

Steeve

**Comment by mikejolley** [comment]
@claudiosanches docs state `category`

**Comment by claudiosanches** [comment]
There is no `categories` parameter.
We always use `category` and the docs are correct.

There is really a bug but `categories` are returning all values and not only by category.
