### ISSUE TITLE
Minor bug in wc_dropdown_variation_attribute_options function

### ISSUE THREAD

**Issue by andykeith** [woocommerce/woocommerce#13799]
## EXPLANATION OF THE ISSUE

WooCommerce v2.6.14. 

Function `wc_dropdown_variation_attribute_options()` in wc-template-functions.php contains an extra quote " which shouldn't be there.

Line 2077:

`$html = '<select id="' . esc_attr( $id ) . '" class="' . esc_attr( $class ) . '" name="' . esc_attr( $name ) . '" data-attribute_name="attribute_' . esc_attr( sanitize_title( $attribute ) ) . '"' . '" data-show_option_none="' . ( $show_option_none ? 'yes' : 'no' ) . '">';`

The extra quote mark before `data-show_option_none` is not needed.

## STEPS TO REPRODUCE THE ISSUE

Call the function for any product variation.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
This is patched in master and will be fixed in 3.0. Thanks.
