### ISSUE TITLE
product factory bleedover bug when product id is false

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce#13798]
## EXPLANATION OF THE ISSUE

This affects 2.6.14, and _maybe_ latest master as well, though I didn't test it for that.

_EDIT:_ fixed link locations

I have some custom functionality that overrides the stock levels of some products. The functionality is basically along these lines:

> If `<product>` is simple, and belongs to a group, find the parent, get children, and select one of its other children, and use the stock of that one instead.

I'm filtering the `woocommerce_get_stock_quantity` which receives the product. To find the parent of the product, I use a recursive function:

```
private function find_group_parent( $id ) {
	// RECURSION!
	$product = wc_get_product( $id );

	if ( ! $product ) {
		return false;
	}

	if ( 'grouped' === $product->get_type() ) {
		return $product;
	}

	return $this->find_group_parent( $product->post->post_parent );
}
```
It works well for everything, I can throw all sorts of products at it, and it will always either return `false`, or the passed in product's parent grouped product, which can be itself.

Except when I'm on a single page, OR an admin page with a list table on it.

At that point, I get an error:

```
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in  <file>
```
## Why this is a bug

In [the WC_Product_Factory->get_product_object](https://github.com/woocommerce/woocommerce/tree/2.6.14/includes/class-wc-product-factory.php#L104-L106) if the passed in variable is `false`, it grabs whatever is in the global `$post`.

If the [product is not found in the same method](https://github.com/woocommerce/woocommerce/tree/2.6.14/includes/class-wc-product-factory.php#L114), it returns `false`.

Which means that if I'm on a single page, my recursive function is going to be stuck in an infinite loop, because even though I _expect_ `wc_get_product( false )` to return `false`, it will return the current page, post, comment, whatever I'm on. 

The same is true when trying to list products on the list table, because [in WordPress core the posts list table single row method](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/class-wp-posts-list-table.php#L1162-L1190) will set the current row data into the global `$post`, which will inevitably bleed over to the next one.

**Comment by nerrad** [comment]
In the [linked code](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-factory.php#L104-L106), it looks to me like the condition is:

- If incoming argument is `false`,
- And there is a set `$post` global and that has an `id`
- AND the product type for that post is `product`, then the id gets returned for that post.

So its not clear to me that this is the cause of the recursion you discovered unless I read that conditional wrong.

**Comment by javorszky** [comment]
The condition should be that

* if `wc_get_product( false )` returns `false`, then the recursive function should return `false` too
* because if there's a post that has an ID, `wc_get_product` will return that ID instead of `false` (not expected!), the recursive function will never end

**Comment by mikejolley** [comment]
@javorszky Master does the same - `false` is the default value - when product ID is false it gets the global post. https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-factory.php#L27

This is so you can do something like:

`
$product = wc_get_product();
`

On the frontend, like you can do with `get_post`. Preventing this at this point in time would be a breaking change for anyone relying on that functionality so there isn't much that can be done to workaround or fix.

The solution from your side is simple. If `$id` is `false`, break.

**Comment by javorszky** [comment]
Hm, fair point @mikejolley, thanks for the reasoning :)
