### ISSUE TITLE
'woocommerce_get_price' is gone and not deprecated on 3.0.0-rc2

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#13795]
When using the 'woocommerce_get_price' filter on 3.0.0-rc2 we get the following notice:

> Notice: The "woocommerce_get_price" hook uses out of date data structures and is <strong>deprecated</strong> since version 3.0.0! Use woocommerce_product_get_price instead.

This filter is applied on WC_Product::get_price on 2.6.14 and is nowhere to be found on 3.0.0-rc2 besides the WC_Deprecated_Filter_Hooks class.
The new 'woocommerce_product_get_price' filter is also nowhere to be found on 3.0.0-rc2

Basically, 3.0.0-rc2 renders useless any plugin that uses the 'woocommerce_get_price' filter which is not a deprecation but a breaking change.

I discovered this while trying to update my plugin [Taxonomy / Term based Discounts for WooCommerce](https://wordpress.org/plugins/taxonomy-discounts-woocommerce/) to work with 3.0, which it won't at all.

**Comment by mikejolley** [comment]
Wrong, get_prop triggers all actions and filters. See https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L618

**Comment by webdados** [comment]
Thank you @mikejolley 
I'm sorry for the mistake.
