### ISSUE TITLE
save_post fires twice when updating products

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce#13800]
## EXPLANATION OF THE ISSUE

The save_post hook fires twice when a product is updated on WooCommerce 3.0.0-rc.1. It only fires a single time on 2.6.14.

## STEPS TO REPRODUCE THE ISSUE

Attach to the save_post with your favourite debug output. Update a post, e.g.

    add_action( 'save_post', function ( $post_id ) {
        if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
            return;
        }
        error_log('save_post called!');
    }

## Expected output

A single instance of "save_post called!" in the error log. This is what you get on 2.6.14.

## Actual output

Two copies of "save_post called!" in the error log.

**Comment by mikejolley** [comment]
@leewillis77 1 save post is called by WordPress when doing regular admin save.

1 save post is called by the CRUD class when updating the product object.

These are separate events handled by separate code.

**Comment by leewillis77** [comment]
Hi @mikejolley;

Thanks for the swift reply. It's not causing me a big issue since my use case is some internal background processing. I'll do more than necessary, but no huge deal.

I did think I'd flag it as anyone hooking into those hooks will potentially get double actions when WC3 goes live? I'm thinking of things like 3rd party integrations / notification emails / workflow type applications?

**Comment by mikejolley** [comment]
@leewillis77 That may be the case, they would need to put some protection in place like core did a few versions back for the meta box save events. Sometimes we'd call save post multiple times there too e.g. if we needed to update a post status during save.

Rather than relying on save_post which literally gets fired everywhere, on any update_post, it would be better to target specific object save hooks such as the new ones in CRUD. e.g `woocommerce_update_product`

Thanks for flagging - will take note if it causes issues, although I see no workaround at present. cc @claudiosanches

**Comment by ole1986** [comment]
IMO this issue needs to be escalated?

Example code below still causing an order or a product to fire the action twice.
```
add_action('post_save', 'my_save_action');
function my_save_action() {
    if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
    if( ! ( wp_is_post_revision( $post_id) || wp_is_post_autosave( $post_id ) ) ) {
        // STILL FIRES TWICE
    }
}
```

**Only workaround is to make use of `remove_action`**

Example:

`remove_action('post_save', 'my_save_action')`;

**Comment by mikejolley** [comment]
As stated above, it does fire twice because it's called when objects get saved. This has always been the case and your save_post hook needs to workaround as core does.

We can switch to direct queries but not until a major version as it has other consequences.

**Comment by acafourek** [comment]
I've landed here a few times over the last year when Googling this issue - for future passersby, check out [this comment](https://github.com/woocommerce/woocommerce/issues/21867#issuecomment-438975924) for a summary of why the multi-save occurs.

> As for the issue regarding the multiple saves, that is due to the way we need to have a base product saved first before saving images to it, we need the ID to tie the image to it, same goes for variations. Not much we can about it I'm afraid, we need to save it multiple times and in return it will fire the webhook multiple times, each with the latest data.

**Comment by felixprojekt** [comment]
As @ole1986 said, if you are sure you are done with the function after firing it once, remove it at the end of the execution.

`
add_action('post_save', 'my_save_action');
function my_save_action() {
    if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
    if( ! ( wp_is_post_revision( $post_id) || wp_is_post_autosave( $post_id ) ) ) return;

// do stuff here

    remove_action('post_save', 'my_save_action')
}
`

**Comment by rasimyilmaz** [comment]
check empty($_POST)

**Comment by 2Cubed-ie** [comment]
A simpler solution would be to set a `$_POST` variable and check at the start of the function.

`add_action( 'woocommerce_update_product', 'my_action', 10, 1 );
function my_action(){
   if( isset($_POST['action_performed']) ){
      //Prevent running the action twice
      return;
    }
   
   // do you stuff here

   $_POST['action_performed'] = true;
}`

**Comment by h08831n** [comment]
> A simpler solution would be to set a `$_POST` variable and check at the start of the function.
> 
> ```
> function my_action(){
>    if( isset($_POST['action_performed']) ){
>       //Prevent running the action twice
>       return;
>     }
>    
>    // do you stuff here
> 
>    $_POST['action_performed'] = true;
> }```
> ```

this finally worked for me
