### ISSUE TITLE
terms under Products/Attributes not showing

### ISSUE THREAD

**Issue by mskmw** [woocommerce/woocommerce#13819]
## EXPLANATION OF THE ISSUE

WC 2.6.14
Wordpress 4.7.3–de_DE

The terms under Products/Attributes are not showing.

Not a plugin problem, I tried to deactivate all plugins.
Not a Theme problem.
Tried also to reinstall woocommerce.

## STEPS TO REPRODUCE THE ISSUE

When I add a attribute under Products/Attributes and then add new terms under Configure items,
they are showing in the list. Then, when clicking Configure items again there are no terms showing. 

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: http://sporthaus-reich.de
Site URL: http://sporthaus-reich.de
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.1
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 16000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ❌ Table does not exist
woocommerce_api_keys: ❌ Table does not exist
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ❌ Table does not exist
woocommerce_shipping_zone_locations: ❌ Table does not exist
woocommerce_shipping_zone_methods: ❌ Table does not exist
woocommerce_payment_tokens: ❌ Table does not exist
woocommerce_payment_tokenmeta: ❌ Table does not exist
MaxMind GeoIP Database: ✔

### Active Plugins (20) ###

Breadcrumb NavXT: by John Havlik – 5.6.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Login Logo: by Dreams Online Themes – 1.0.2
Envato WordPress Toolkit: by Envato – 1.7.3
WooCommerce Quickview: by James Kemp – 3.0.5
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.0.1
Loco Translate: by Tim Whitlock – 2.0.12
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1
OXY Shortcodes: by Smartdatasoft – 1.0
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.4
WooCommerce Bulk Pricing: by WP Lab – 1.8.6
WooCommerce German Market: by Inpsyde GmbH – 2.6.8
WooCommerce Print Invoices/Packing Lists: by WooThemes / SkyVerge – 3.1.7 – 3.2.0 is available
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
WP Database Backup: by Prashant Walke – 4.3.7
YITH WooCommerce Compare: by YITHEMES – 2.1.0
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /shop/
Cart: #6 - /warenkorb/
Checkout: #7 - /kasse/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: OXY
Version: 2.9
Author URL: http://www.smartdatasoft.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: oxy/woocommerce/archive-product.php
oxy/woocommerce/cart/mini-cart.php
oxy/woocommerce/content-product.php
oxy/woocommerce/content-product_cat.php
oxy/woocommerce/content-single-product.php
oxy/woocommerce/loop/orderby.php
oxy/woocommerce/loop/pagination.php
oxy/woocommerce/loop/price.php
oxy/woocommerce/loop/sale-flash.php
oxy/woocommerce/single-product/add-to-cart/external.php
oxy/woocommerce/single-product/add-to-cart/grouped.php
oxy/woocommerce/single-product/add-to-cart/simple.php
oxy/woocommerce/single-product/add-to-cart/variable.php
oxy/woocommerce/single-product/price.php
oxy/woocommerce/single-product/product-image.php
oxy/woocommerce/single-product/product-thumbnails.php
oxy/woocommerce/single-product/related.php
oxy/woocommerce/single-product/review.php
oxy/woocommerce/single-product/sale-flash.php
oxy/woocommerce/single-product/share.php
oxy/woocommerce/single-product/short-description.php
oxy/woocommerce/single-product/tabs/additional-information.php
oxy/woocommerce/single-product/tabs/description.php
oxy/woocommerce/single-product/tabs/tabs.php
oxy/woocommerce/single-product/title.php
oxy/woocommerce/single-product/up-sells.php
oxy/woocommerce/single-product-reviews.php
oxy/woocommerce/single-product.php
oxy/woocommerce/taxonomy-product_cat.php
oxy/woocommerce/taxonomy-product_tag.php

`
![17622728_1643613692333917_552096521_o](https://cloud.githubusercontent.com/assets/26761606/24444016/418979d6-1465-11e7-86e0-ec44fd9e8a48.png)
![17622479_1643613582333928_322489586_o](https://cloud.githubusercontent.com/assets/26761606/24444017/418a8056-1465-11e7-8f20-73b469909fcc.png)

**Comment by mikejolley** [comment]
You have database issues, possibly permission issues for your Mysql user. You can see in the report you have missing tables; you're likely missing term meta also, thats why they reveal when you sort by count - you're missing the term meta which handles sorting.

Look into your database config, once resolved, reactivate WooCommerce so those missing tables get created, confirm you have a wp_termmeta table, and add a few new terms/sort them to get the missing values populated.

**Comment by mskmw** [comment]
Hello mike,

I checked the permissions, the database is now updated and all missing tables were created.
I have a wp_termmeta table which is filled with actually 1206 entries. (checked via phpmyadmin)
I added a few new terms and sorted them. When I sort, they show up, but then they are still not showing.

What else can I do?

`
### WordPress Environment ###

Home URL: http://sporthaus-reich.de
Site URL: http://sporthaus-reich.de
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.1
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 16000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (21) ###

Breadcrumb NavXT: by John Havlik – 5.6.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Login Logo: by Dreams Online Themes – 1.0.2
Database Browser: by Chris Taylor – 1.4
Envato WordPress Toolkit: by Envato – 1.7.3
WooCommerce Quickview: by James Kemp – 3.0.5
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.0.1
Loco Translate: by Tim Whitlock – 2.0.12
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1
OXY Shortcodes: by Smartdatasoft – 1.0
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.4
WooCommerce Bulk Pricing: by WP Lab – 1.8.6
WooCommerce German Market: by Inpsyde GmbH – 2.6.8
WooCommerce Print Invoices/Packing Lists: by WooThemes / SkyVerge – 3.1.7 – 3.2.0 is available
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
WP Database Backup: by Prashant Walke – 4.3.7
YITH WooCommerce Compare: by YITHEMES – 2.1.0
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #5 - /shop/
Cart: #6 - /warenkorb/
Checkout: #7 - /kasse/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: OXY
Version: 2.9
Author URL: http://www.smartdatasoft.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: oxy/woocommerce/archive-product.php
oxy/woocommerce/cart/mini-cart.php
oxy/woocommerce/content-product.php
oxy/woocommerce/content-product_cat.php
oxy/woocommerce/content-single-product.php
oxy/woocommerce/loop/orderby.php
oxy/woocommerce/loop/pagination.php
oxy/woocommerce/loop/price.php
oxy/woocommerce/loop/sale-flash.php
oxy/woocommerce/single-product/add-to-cart/external.php
oxy/woocommerce/single-product/add-to-cart/grouped.php
oxy/woocommerce/single-product/add-to-cart/simple.php
oxy/woocommerce/single-product/add-to-cart/variable.php
oxy/woocommerce/single-product/price.php
oxy/woocommerce/single-product/product-image.php
oxy/woocommerce/single-product/product-thumbnails.php
oxy/woocommerce/single-product/related.php
oxy/woocommerce/single-product/review.php
oxy/woocommerce/single-product/sale-flash.php
oxy/woocommerce/single-product/share.php
oxy/woocommerce/single-product/short-description.php
oxy/woocommerce/single-product/tabs/additional-information.php
oxy/woocommerce/single-product/tabs/description.php
oxy/woocommerce/single-product/tabs/tabs.php
oxy/woocommerce/single-product/title.php
oxy/woocommerce/single-product/up-sells.php
oxy/woocommerce/single-product-reviews.php
oxy/woocommerce/single-product.php
oxy/woocommerce/taxonomy-product_cat.php
oxy/woocommerce/taxonomy-product_tag.php

`

**Comment by mikejolley** [comment]
After sorting that meta should be there for all terms. You can try adding a new term too.

If you still have problems, try with the other WC plugins off for testing.

**Comment by mskmw** [comment]
I tried all of it. It´s still not working...

**Comment by mskmw** [comment]
Any further idea what it could be?

**Comment by mikejolley** [comment]
Thats all I've got. Conflicts with other plugins or the missing data in the termmeta table is all I've ever come across. It works on other installs.
