### ISSUE TITLE
Does WC_Checkout::get_posted_data ever really return "errors"?

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#13818]
## EXPLANATION OF THE ISSUE

The phpdocs for WC_Checkout::get_posted_data ( https://github.com/woocommerce/woocommerce/blob/ae7c4e713b58f0278a62dd4a4c1e627cd90f05b0/includes/class-wc-checkout.php#L522 ) say it returns:

`@return array of data and errors.`

But I think that should be just `data`, right? I don't see how errors are returned by this method.

**Comment by mikejolley** [comment]
Looks like it should be yes.
