### ISSUE TITLE
->get("system_status") Return "rest_no_route"

### ISSUE THREAD

**Issue by WaldenStew** [woocommerce/woocommerce#13826]
Hi,
I'm using WP 4.7.3 and woocommerce 3.0.0 
I'm trying to list all system status item by $woocommerce->get("system_status") but API returns me 
"code": "rest_no_route" 
Is it a bug?
Thx,
 Steeve

**Comment by claudiosanches** [comment]
Works just fine, but if you are getting this error it's because you are not setting the library to use the correct version of the WooCommerce REST API.

**Comment by claudiosanches** [comment]
Here how to set the correct version: https://woocommerce.github.io/woocommerce-rest-api-docs/?php#libraries-and-tools

**Comment by WaldenStew** [comment]
Thx !
