### ISSUE TITLE
Bug in woocommerce 3.0 in _wc_average_rating

### ISSUE THREAD

**Issue by belcherj** [woocommerce/woocommerce#13829]
Bug reported via support ticket.

## EXPLANATION OF THE ISSUE

When a product is reviewed for first time, its not being updated in wp_postmeta ( _wc_average_rating = 0 , _wc_rating_count = a:0 ) . But on 2nd review both values get updated for the 1st review only. 
Example : 
1st review = 4stars 
Then wp_postmeta ( _wc_average_rating = 0 , _wc_rating_count = a:0 )

2nd review = 3stars 
Then wp_postmeta ( _wc_average_rating = 4.00 , _wc_rating_count = a:1:{i:4;i:1;} )

## STEPS TO REPRODUCE THE ISSUE
Rate a product for the first time, observe rating
Rate a product for the second time, observe rating

**Comment by siddharthcedcoss** [comment]
thanks for the fix..
