### ISSUE TITLE
Need a possibility to extend $data in WC_Order_Item_Fee

### ISSUE THREAD

**Issue by InoPlugs** [woocommerce/woocommerce#13827]
@mikejolley 

## WooCommerce Payment Gateway Based Fees needs to identify added fees by our plugin

because when recalculating an order (when saveing order from backend) we have to remove our fees and replace them with new calculated values.

Currently no chance to add a new property to $data to be safed in database (using hook 'woocommerce_checkout_create_order_fee_item' - cannot replace given WC_Order_Item_Fee with a derived object in an action)

Currently only chance would be to modify the name of the fee by adding a unique string for our plugin (but not a nice solution).

Pls let me know asap your solution - **currently plugin is broken and will not work with 3.0.0**

**Comment by mikejolley** [comment]
@InoPlugs All objects support meta data - just add some meta to your fee?

**Comment by InoPlugs** [comment]
@mikejolley 

Thanks a lot - works.
