### ISSUE TITLE
Change/update Slug of a product

### ISSUE THREAD

**Issue by itphil** [woocommerce/woocommerce#13824]
Hello!

WC Version: 2.7.0

I try to change the slug of a product sending following json to the API:
{
	"id": 3387,
	"name": "My Product",
	"slug": "MYNEWSLUG",
...

After sending the product to the API, I have still the old slug. The other properties were changed and it gives me no error.

How can I change the slug of an existing product?

**Comment by mikejolley** [comment]
@claudiosanches Confirmed slug is not editable.
