### ISSUE TITLE
The problem in Connect rest api v2 with postman

### ISSUE THREAD

**Issue by ghazalejon** [woocommerce/woocommerce#13834]
Hello
I'm connecting to the site to confront  "Invalid timestamp." message

{
  "code": "woocommerce_rest_authentication_error",
  "message": "Invalid timestamp.",
  "data": {
    "status": 401
  }
}

This problem does not exist in store in localhost
please help me

**Comment by claudiosanches** [comment]
ILooks like you need to send a valid timestamp, maybe something related to the timezone configured in your server that is not the same from your localhost.
But not an issue with WooCommerce, if is saying that the timestamp is invalid, it's because for your server is really invalid.

**Comment by ghazalejon** [comment]
I thank you for your answers
But the problem did not exist in previous versions (wc version 2.6.x    -  /wp-json/wc/v1/products)
This problem was created after the update to  wc version 3.0.x
This server has no problem with the previous version
Please send video configuration and testing this version the server
![2](https://cloud.githubusercontent.com/assets/10259185/24496962/1aa7100e-154f-11e7-9510-915c4bd35bd1.jpg)
![untitled](https://cloud.githubusercontent.com/assets/10259185/24496963/1aabf9e8-154f-11e7-851a-91497b0fb977.jpg)

**Comment by meysamsh** [comment]
hello
please tell me how problem solved?
i have this problem issue
