### ISSUE TITLE
Image zoom init javascript

### ISSUE THREAD

**Issue by britner** [woocommerce/woocommerce#13830]
## EXPLANATION OF THE ISSUE

Using 3.0 the image zoom doesn't init unless the image is larger then the gallery container. This is an issue for 2 reasons. 

1. If the image is the same size as the gallery container it won't init. It's not looking at the full size image? so if your output is correct in that your image size is the same as your image container it won't init.
My suggestion is to simply change: https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/single-product.js#L171

to be:

`if ( image.attr( 'width' ) >= galleryWidth ) {`

2. It also means the zoom will not init if the gallery layout has thumbnails beside the "main" image instead of below. Because it's comparing the width of the image vs the width of the gallery container instead of the "woocommerce-product-gallery__image" div

See image:
<img width="1298" alt="screen shot 2017-03-29 at 11 40 19 am" src="https://cloud.githubusercontent.com/assets/4762451/24468343/23ff20ae-1475-11e7-917d-da2e9c5871ac.png">

My suggestion is to simply change: https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/single-product.js#L161

to get the first woocommerce-product-gallery__image width. something like:
`galleryWidth =  $('.woocommerce-product-gallery .woocommerce-product-gallery__image:first-child').width(),`

If there is a better alternative that I can add on my end to force the init I would be happy to hear.

Thanks

**Comment by jameskoster** [comment]
Point 2 makes sense, thanks for the input. 

I'm wondering why you'd want to init the zoom if the image is the _same size_ as the gallery though? If it's the same size, the zooming won't actually do anything?

**Comment by mikejolley** [comment]
@jameskoster is it the scaled display size or the actual image size?

**Comment by mikejolley** [comment]
I see it's the attr, nvm. 1 is a non-issue. Zooming I agree is pointless if they are the same size.

**Comment by britner** [comment]
Point one. The javascript looks at the "shop_single" size image, NOT the full size image which is actually the image used for zoom. So with the current javascript the "shop_single" size can be the exact size of the container (usually a desired thing) and the full size can be 3 times larger and it won't init the zoom. 

Another way you could fix this is by changing the javascript to look at the "data-large-image-width" but either way does that clarify point one? 

Ben

**Comment by jameskoster** [comment]
> The javascript looks at the "shop_single" size image, NOT the full size image which is actually the image used for zoom

That sounds like an oversight on my part. It should compare against the image that's being zoomed. If we change that, point one becomes a non-issue?

**Comment by britner** [comment]
Yes, changing to look at the data-large-image-width would make the most sense.

Ben

**Comment by jameskoster** [comment]
That commit ensures we check the full size image before initialising the zoom.

The problem with your suggestion for the second point is that on document.ready() the width of each `'.woocommerce-product-gallery__image'` equals the full width of the slider container. The width hasn't been applied at that point. So it's not a reliable selector to use for the gallery width.

Now that we're comparing the full size image this seems to be _less_ of an issue as well. Especially considering that that layout (vertical adjacent thumbs) isn't all that common.

**Comment by britner** [comment]
I agree that it's less of an issue. I still think there should be a better way to get the size of the item that is actually determining the width of the image zoom rather then it's wrapper. I didn't have the issue you described until until I tested with storefront so there must be some css difference. If I get a chance I'll test some different code with storefront to see if there is some obvious better method.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/commit/1cd85b1b9b6a8bd7986497507340ccb6dc2ba1c8

@jameskoster please submit PRs for fixes :p 🤠

**Comment by jameskoster** [comment]
I missed that memo 🐙
