### ISSUE TITLE
Shipping methods names lose their translations when migrated from 2.6 to 3?

### ISSUE THREAD

**Issue by tivnet** [woocommerce/woocommerce#13836]
@mikejolley 

If I try 3.0 with the POT from 2.6, the shipping methods on checkout appear untranslated, obviously, because of the case change (`Flat Rate` became `Flat rate`). 

Now, I change the POT to the new way, "Flat rate", compile to `.mo` - but the method name is still not translated. I have to remove the method and add it again.

I may be wrong, and it will be all fixed when DB is migrated with the new POT present? But for that, the new MO files should be there already, and they are not until I do "upgrade translations".

**Comment by claudiosanches** [comment]
It's a new string and requires do download the new .mo file from translate.wordpress.org, something that will happens automatically when released and when the translation for your language is finished.

**Comment by tivnet** [comment]
As I wrote, updating MO doesn't update the names already in use. Therefore,
the translations will be lost.

**Comment by mikejolley** [comment]
Shipping rate names are *user defined*. Existing methods cannot be translated in this way.

**Comment by tivnet** [comment]
You are right. However, if the users accept the default name, it will show
the correct default translations from the MO.
With the changes to the pomo, this stops working.

Important for WPML, WPGlobus and similar.

**Comment by mikejolley** [comment]
Once the method is saved, the name is fixed at that value. If the user accepts the default value, it's no longer the 'default value', it's the actual forever stored value.

If you're suggesting that no name be set so the default is used, thats not something we should be doing. Name is required.

**Comment by mikejolley** [comment]
> The only way to restore the functionality in my experiments was to delete the method and add it again

Or edit the rate and change the name yourself?

**Comment by tivnet** [comment]
Not sure. Did not work for me. Had to delete and add again.

**Comment by mikejolley** [comment]
Maybe you can screenshot what you're talking about because 'flat rate' is user set. You can translate or set it to ANY value. Changing the translation should not affect already set methods.

**Comment by tivnet** [comment]
# Step 1:
The admin language is de_DE. The code is `dev-master`. POMO is old, from 2.6
The "Local pickup" is in English:

![image](https://cloud.githubusercontent.com/assets/1696330/24519057/e84a2b3e-1551-11e7-98a3-0d81392ebbf6.png)

# Step 2:
Change the code to match the POMO:
![image](https://cloud.githubusercontent.com/assets/1696330/24519157/4425f08c-1552-11e7-8433-17cca01c9d9a.png)

Now, refresh the admin screen (we are still in `de_DE`)
![image](https://cloud.githubusercontent.com/assets/1696330/24519204/6ba58b86-1552-11e7-989e-666b758f3d52.png)

**Comment by mikejolley** [comment]
I was going to wrap with __() but I've changed my mind - I believe we should respect the user set value. If we changed it based on translation it could be very confusing to see values that differ from the value the user actually input.

There is a filter `woocommerce_shipping_rate_label` which can be used by yourself or WPML to support dynamic localiation.

cc @claudiosanches

**Comment by tivnet** [comment]
@mikejolley 
As you see in https://github.com/woocommerce/woocommerce/issues/13836#issuecomment-290480861, that's the exact filter I used in my tests.

Anyway, thanks for your time. At least we are aware of the situation and can tell to the WPGlobus users what they have to do.
