### ISSUE TITLE
Server is slow when edit products or post

### ISSUE THREAD

**Issue by daniel-bios** [woocommerce/woocommerce#13841]
Helllo 

I have a website in wordpress and Woocomerce and I have got 98000 products on it without images
i have  dedicated server  , with 8core 2 ghz xeon processor , 12 GB RAM ,, it still exists the problem when I edit products in the WOOcomerce or edit the post
editing of a product would last around 3 minutes , and also appears the message Connetion lost.

And also the CPU usage jump at 80-100 %.

**php.ini**
max_execution_time = 30
max_input_time = 60
memory_limit = 512M

**wp-config**
define('WP_MEMORY_LIMIT', '512M');
define('WP_MAX_MEMORY_LIMIT', '1024M');

**How can this issue be solved?**

**_Tuning MySQL Server Settings_**

[root@lnx-vps01 ~]# perl mysqltuner.pl
 >>  MySQLTuner 1.6.20 - Major Hayden <major@mhtx.net>
 >>  Bug reports, feature requests, and downloads at http://mysqltuner.com/
 >>  Run with '--help' for additional options and output filtering

[--] Skipped version check for MySQLTuner script
Please enter your MySQL administrative login: root
Please enter your MySQL administrative password:
[OK] Currently running supported MySQL version 10.1.21-MariaDB
[OK] Operating on 64-bit architecture

-------- Storage Engine Statistics -----------------------------------------------------------------
[--] Status: +Aria +CSV +InnoDB +MEMORY +MRG_MyISAM +MyISAM +PERFORMANCE_SCHEMA +SEQUENCE
[--] Data in MyISAM tables: 973M (Tables: 193)
[--] Data in InnoDB tables: 21M (Tables: 76)
[OK] Total fragmented tables: 0

-------- CVE Security Recommendations --------------------------------------------------------------
[--] Skipped due to --cvefile option undefined

-------- Performance Metrics -----------------------------------------------------------------------
[--] Up for: 13h 41m 30s (2M q [46.245 qps], 21K conn, TX: 25G, RX: 400M)
[--] Reads / Writes: 94% / 6%
[--] Binary logging is disabled
[--] Physical Memory     : 11.6G
[--] Max MySQL memory    : 6.3G
[--] Other process memory: 2.2G
[--] Total buffers: 5.7G global + 2.9M per thread (200 max threads)
[--] P_S Max memory usage: 0B
[--] Galera GCache Max memory usage: 0B
[OK] Maximum reached memory usage: 5.8G (50.42% of installed RAM)
[OK] Maximum possible memory usage: 6.3G (54.54% of installed RAM)
[OK] Overall possible memory usage with other process is compatible with memory available
[OK] Slow queries: 0% (0/2M)
[OK] Highest usage of available connections: 16% (32/200)
[OK] Aborted connections: 0.00%  (1/21255)
[OK] Query cache efficiency: 35.5% (1M cached / 3M selects)
[!!] Query cache prunes per day: 225257
[OK] Sorts requiring temporary tables: 4% (6K temp sorts / 146K sorts)
[OK] No joins without indexes
[!!] Temporary tables created on disk: 76% (149K on disk / 195K total)
[OK] Thread cache hit rate: 99% (32 created / 21K connections)
[OK] Table cache hit rate: 74% (220 open / 294 opened)
[OK] Open file limit used: 1% (247/16K)
[OK] Table locks acquired immediately: 99% (1M immediate / 1M locks)

-------- Performance schema ------------------------------------------------------------------------
[--] Performance schema is disabled.

-------- ThreadPool Metrics ------------------------------------------------------------------------
[--] ThreadPool stat is enabled.
[--] Thread Pool Size: 8 thread(s).
[--] Using default value is good enough for your version (10.1.21-MariaDB)

-------- MyISAM Metrics ----------------------------------------------------------------------------
[!!] Key buffer used: 36.9% (198M used / 536M cache)
[OK] Key buffer size / total MyISAM indexes: 512.0M/323.9M
[OK] Read Key buffer hit rate: 100.0% (1B cached / 97K reads)
[!!] Write Key buffer hit rate: 15.5% (112K cached / 94K writes)

-------- AriaDB Metrics ----------------------------------------------------------------------------
[--] AriaDB is enabled.
[OK] Aria pagecache size / total Aria indexes: 128.0M/1B
[OK] Aria pagecache hit rate: 100.0% (308M cached / 112K reads)

-------- InnoDB Metrics ----------------------------------------------------------------------------
[--] InnoDB is enabled.
[OK] InnoDB buffer pool / data size: 4.0G/21.5M
[OK] InnoDB buffer pool instances: 4
[--] InnoDB Buffer Pool Chunk Size not used or defined in your version
[OK] InnoDB Read buffer efficiency: 99.97% (2335483 hits/ 2336273 total)
[!!] InnoDB Write Log efficiency: 27.16% (28436 hits/ 104699 total)
[OK] InnoDB log waits: 0.00% (0 waits / 76263 writes)

-------- TokuDB Metrics ----------------------------------------------------------------------------
[--] TokuDB is disabled.

-------- Galera Metrics ----------------------------------------------------------------------------
[--] Galera is disabled.

-------- Replication Metrics -----------------------------------------------------------------------
[--] Galera Synchronous replication: NO
[--] No replication slave(s) for this server.
[--] This is a standalone server.

-------- Recommendations ---------------------------------------------------------------------------
General recommendations:
    MySQL started within last 24 hours - recommendations may be inaccurate
    Temporary table size is already large - reduce result set size
    Reduce your SELECT DISTINCT queries without LIMIT clauses
Variables to adjust:
    query_cache_size (> 100M)

**Comment by mikejolley** [comment]
I suggest you post on one of the communities (facebook) or support forums for advice because you're not reporting a bug here or anything actionable. Whilst we're committed to improving performance (see our dev blog), we cannot optimise your site or hosting.
