### ISSUE TITLE
Polish Currency Information is incorrect

### ISSUE THREAD

**Issue by belcherj** [woocommerce/woocommerce#13846]
Created from a support ticket:

The default polish currency info in /woocommerce/i18n/locale-info.php contains wrong information about thousand and decimal separator.

According to https://en.wikipedia.org/wiki/Decimal_mark, prices in polish złoty should be displayed as "1 234 567,89" (Comma as decimal separator and space as thousand sep). Currency position should be changed to 'right_space' as well.

@iMazed can you verify that this is correct.

**Comment by lhopkins** [comment]
The fix for this is incorrect. `decimal_sep` was changed to spaces instead of `thousand_sep`. Also `currency_pos` should be changed to `right_space`.
