### ISSUE TITLE
[3.0] Product image flickers on load

### ISSUE THREAD

**Issue by dennyf** [woocommerce/woocommerce#13847]
## EXPLANATION OF THE ISSUE
The product image seems to get resized to a bigger size for a fraction of second when the page loads, which makes the image flicker:

![wc-image-load](https://cloud.githubusercontent.com/assets/901213/24529725/0ad1f20c-15f9-11e7-8b67-e965310f33ab.gif)

It looks like this happens only with the image slider option enabled, when visiting a single-image product on Chrome.

## STEPS TO REPRODUCE THE ISSUE
1. Make sure that the product gallery slider feature is enabled
2. Visit a product that has only one image with Chrome

I tested it with the TwentySixteen theme, but it also happens with other themes as well.

**Comment by mikejolley** [comment]
Put in a possible fix in https://github.com/woocommerce/woocommerce/pull/13859, but this may not be part of 3.0 since it's minor and simply caused by the loading.

See https://github.com/woocommerce/woocommerce/pull/13859

**Comment by faisal-alvi** [comment]
This can be resolved just by CSS. Here is the #13860
