### ISSUE TITLE
Trash/delete product hooks don't fire

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce#13852]
## EXPLANATION OF THE ISSUE

WC_Product_Data_Store_CPT has a delete() method which should fire one of the following hooks depending on the precise action (trash, or delete permanently), and the type (simple, or variation)

- woocommerce_delete_product
- woocommerce_delete_product_variation
- woocommerce_trash_product
- woocommerce_trash_product_variation

The delete_product_variation hook is fired correctly, but woocommerce_delete_product and woocommerce_trash_product never seem to be fired when removing a product through the WordPress UI. Specifically it looks like the delete() method on WC_Product_Data_Store_CPT is never invoked. 

The same issue also affects Abstract_WC_Order_Data_Store_CPT - the delete method is never fired, so the hooks are never fired. 

I haven't researched other data stores to see if they're similarly affected or not, but can do if that would be helpful.

**Comment by mikejolley** [comment]
This is true; we don't control the WordPress UI delete and trash functionality, so it bypasses CRUD completely. 

If you need to detect these events across CRUD and across WordPress UI, use `wp_trash_post` and `wp_delete_post` actions. If we ever have our own UI (not WP UI) we'll be able to consistently fire them everywhere.

**Comment by MounirHamani** [comment]
Hi there,

While I understand that the hooks aren't fired through the WP UI, this part:

> The same issue also affects Abstract_WC_Order_Data_Store_CPT - the delete method is never fired, so the hooks are never fired.

is a **_pseudo-bug_** that I also encountered.

What I mean here is that the delete method is fired and that hook as well but you are probably trying to use the $id parameter to get the product but the thing is the product deleted and its $id set to 0 just before firing the hook, rendering it useless and inaccessible.

As a workaround I propose to add:
`do_action( 'woocommerce_before_delete_' . $post_type, $id );`
right before deleting the product. WordPress offers the `before_delete_post` hook which I, ultimately, had to use but I would rather prefer to have a WooCommerce built-in hook and be forward compatible.

If you are okay with my proposition, I can submit a Pull Request.

**Comment by MounirHamani** [comment]
Hi @mikejolley  and @leewillis77 ,

While I understand that the hooks aren't fired through the WP UI, this part:

> The same issue also affects Abstract_WC_Order_Data_Store_CPT - the delete method is never fired, so the hooks are never fired.

is a **_pseudo-bug_** that I also encountered.

What I mean here is that the delete method is fired and that hook as well but you are probably trying to use the $id parameter to get the product but the thing is the product deleted and its $id set to 0 just before firing the hook, rendering it useless and inaccessible.

As a workaround I propose to add:
`do_action( 'woocommerce_before_delete_' . $post_type, $id );`
right before deleting the product. WordPress offers the `before_delete_post` hook which I, ultimately, had to use but I would rather prefer to have a WooCommerce built-in hook and be forward compatible.

If you are okay with my proposition, I can submit a Pull Request.
