### ISSUE TITLE
WC 3.0 filter changes which affect extended classes

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce#13851]
## EXPLANATION OF THE ISSUE

This isn't necessarily an issue I expect can be fixed but rather just letting you know in case you guys or other third party devs weren't aware of this. 

We've recently discovered with Subscriptions that some filters which applied to subscriptions no longer apply in WC 3.0 because of the way `WC_Data` generates the filter string [(here)](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L597) - using the object type. 

One example of this is the WC `2.6.x` `WC_Abstract_Order::get_total()` filter, `woocommerce_order_amount_total`. That function was never overridden by the `WC_Subscription` class so third parties could also use that filter to filter subscription totals. 

In WC 3.0 the equivalent filter is `woocommerce_order_get_total` or in the case of a subscription object, `woocommerce_subscription_get_total`. 

Because of the `WC_Deprecated_Filter_Hooks` class, third parties hooking onto the old hooks will still get triggered when the new hooks are called but not when `woocommerce_subscription_get_total` are called.

Of course, this makes perfect sense, hence why I don't expect any changes on WC's end. This particular example is also unlikely to affect other third parties as I'm not aware of other plugins which extend the `WC_Abstract_Order` order class. 

The more likely scenario is third parties extending the `WC_Product` or related classes and setting the `$object_type` property.

So just as an example, if you have extended the `WC_Product` class and set your own `$object_type` (not to be confused with the value returned from `get_type()`) third parties which hooked onto the `2.6.x` filters like `woocommerce_product_width` will now need to use `woocommerce_{your_object_type}_get_width` to filter your product's width property. 

To get around that you just need to make sure you don't override the `$object_type` property. 

Feel free to close this if this is known. Thought it might be worth sharing in case some devs aren't aware of that possibility.

**Comment by mikejolley** [comment]
Cheers for the write up @james-allan. I'll add to the wiki.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#data-filters-differ-when-extending-classes-with-a-different-object-type

**Comment by james-allan** [comment]
@mikejolley this might also affect WC core products. For example `WC_Product_Variation` use to fall back to `WC_Product::get_price()` and the `woocommerce_get_price` filter in `2.6.x` but in WC 3.0 `WC_Product_Variation::get_hook_prefix()` means that it now filters on `woocommerce_product_variation_get_price`. This is fine, however the hook deprecator doesn't make that connection.
