### ISSUE TITLE
price range filter using woocommerce rest api

### ISSUE THREAD

**Issue by ddhara** [woocommerce/woocommerce#13861]
Hi,

I am using woocommerce rest api for my android app. I need products between specific price range like minimum price and maximum price. Is that possible to do?

For now am using below api but am getting products which having price exactly 200.

`https://my-domian/wp-json/wc/v1/products/?filter[meta_key]=_price&filter[meta_value]=200`

I need to filter products by discount price, price range(minimum and maximum price) and also by the brand name. Is there any filter available for any of them? Can I use only meta fields for filtering?

I already gone through the documentation but couldn't find anything useful and now I saw that documentation is also updated and new version is `v2` and filter is removed from v1. So now how can I use filter with `v1`? Please help me

**Comment by mikejolley** [comment]
Filter is no longer supported by WordPress. There is a price range option in v2 when it launches https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products
