### ISSUE TITLE
Setting a sub shipping method

### ISSUE THREAD

**Issue by MrBillAcey99** [woocommerce/woocommerce#13868]
When you select that a product has a different shipping method it does not over ride any other settings.
This is DUMB!

**Comment by mikejolley** [comment]
I assume you're talking about shipping classes. See https://docs.woocommerce.com/document/product-shipping-classes/

> Shipping classes are used to group products – they are not used directly to offer shipping rates to customers. 

Please also note, Github is not for support questions - it's for bug reports, as stated in the new issue form.
