### ISSUE TITLE
woocommerce_rest_cannot_view - Sorry, you can not list the resources

### ISSUE THREAD

**Issue by hikarushin** [woocommerce/woocommerce#13869]
Hi, I'm new to the API of the WooCommerce. I'm testing our site but it seems I cannot access it using Basic Auth below are the details:

> Woo commerce is 2.6.14
> wordpress is 4.7.3

When I'm trying to access the API using Basic Auth:

Key: ck_ea8961dxxxxxxxx
Secret: cs_193441xxxxxxx
`{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you can not list the resources.",
  "data": {
    "status": 401
  }
}`

I'm using `http://aba.com/wp-json/wc/v1/orders` the same with `https://`
In my WooCommerce setting the API is Read/Write permission.

What do I need to check?

**Comment by claudiosanches** [comment]
If you are using Basic Auth so you should use `https://`, not to mention that maybe you server is ignoring the authentication headers and maybe you should do it as query string.
You can find instructions for it on https://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by MrSiNiSt3R** [comment]
Enjoy:
https://www.domain.com/wp-json/wc/v2/products/attributes?consumer_key=ck_01234567890&consumer_secret=cs_01234567890

**Comment by savan13** [comment]
@MrSiNiSt3R Not working

**Comment by rwschmitz** [comment]
@goranefbl This worked for me, using Postman.  Thank you!

**Comment by eyal670** [comment]
> Enjoy:
> https://www.domain.com/wp-json/wc/v2/products/attributes?consumer_key=ck_01234567890&consumer_secret=cs_01234567890

Worked for me, thank's
