### ISSUE TITLE
No download link in Order Completed email in 3.0 RC2

### ISSUE THREAD

**Issue by AdriOosterwijk** [woocommerce/woocommerce#13870]
Hi,
As far as I can tell is de download link for a downloadable product disappeared in the Order Completed email. It started in the 2.7 RC1. I have checked my install and templates but could not find anything causing this. Please be so kind to look into it.
Thanks and best wishes.

Adri

**Comment by WillBrubaker** [comment]
Adri,

I am using RC-2 and the download link is in the completed order email:
![see screen shot](http://cld.wthms.co/QnDA+)

**Comment by AdriOosterwijk** [comment]
Wil,
Thank you for your reply. I have to look in another direction then. Still very strange.
I will close this for now.

**Comment by AdriOosterwijk** [comment]
Turns out to be a WPML issue. Order completed emails in another language then the default are also sent in admin language (in my case English) AND the download links are missing. WPML is working on a solution.
