### ISSUE TITLE
Confusing REST-API requirements

### ISSUE THREAD

**Issue by Babelfisch** [woocommerce/woocommerce#13874]
You write in the REST-API docs:

> The current WP REST API integration version is v2 which takes a first-order position in endpoints.

On the table below you write that the v2 API is available since WC 3.0.x or later (currently we have WC 2.6.14).

At the v1 docs you write red on top:

> This documentation is for the WooCommerce REST API v1 which is deprecated since WooCommerce 2.7. Please use the latest REST API version.

Once again: WC 2.6.14 is the most recent version and v2 should available on 3.0.x and not 2.7.

It’s very confusing!

**Comment by mikejolley** [comment]
I've asked @claudiosanches to update the ref from 2.7 to 3.0 in the v1 notice. 

3.0 is out next week. https://woocommerce.wordpress.com/
