### ISSUE TITLE
Change number of Orders per page in My Account Page

### ISSUE THREAD

**Issue by panbill** [woocommerce/woocommerce#13876]
Hello,
It would be a good idea to able to show all orders in one page in My Account so to remove pagination.
Any ideas?
Thanks

**Comment by claudiosanches** [comment]
Just use the `woocommerce_my_account_my_orders_query` filter for it.

And please note that here is not an support channel:

>BEFORE POSTING YOUR ISSUE
>- These comments won't show up when you submit the issue.
>- Try to add as much detail as possible. Be specific!
>- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
>  - https://wordpress.org/support/plugin/woocommerce for general support
>  - https://woocommerce.com/my-account/tickets/ for premium plugin support
