### ISSUE TITLE
Revenue Figures are now excluding all but processing orders

### ISSUE THREAD

**Issue by marshallparr** [woocommerce/woocommerce#13889]
Our business has always reported revenue figures by taking the recored "Gross Sales" figure for each week. From what we understand this figure has always included "On Hold", "Order with Courier", etc order statuses. As of this week, this figure now only contains orders in the "Processing" order status it appears. We have changed a large order using the "On hold" status temporarily to "processing" to verify this and it does appear that this is the issue.

We have not made any changes to WooCommerce or any related plugin for a number of a weeks, so I can only presume that an automatic update has caused this change in settings. This may not be considered a bug, but is certainly an issue for us when reporting, to keep this consistent with all revenue figures to date.

As you will see from system status, there are some updates and recommendations however I can't see why this would change how the reporting is being recorded.

Any help you can provide would be really appreciated. 

`
### WordPress Environment ###

Home URL: http://www.abell.co.uk
Site URL: http://www.abell.co.uk
WC Version: 2.6.13
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.31 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 2000
cURL Version: 7.37.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 16 MB
Default Timezone is UTC: ❌ Default timezone is Europe/London - it should be UTC
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() failed. The WooCommerce plugin updater won't work with your server. Contact your hosting provider. Error: cURL error 6: name lookup timed out

### Database ###

WC Database Version: 2.6.13
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (38) ###

Antispam Bee: by pluginkollektiv – 2.6.9
Breadcrumb Trail: by Justin Tadlock – 1.0.0
Code Snippets: by Shea Bunge – 2.8.0
Admin Columns: by AdminColumns.com – 2.5.6.4
Contact Form 7: by Takayuki Miyoshi – 4.6.1
Event Espresso - Calendar: by Event Espresso – 2.2.7.p
Event Espresso - MailChimp Integration: by  – 1.2
Event Espresso: by Event Espresso – 3.1.37.8.P
EWWW Image Optimizer: by Shane Bishop – 3.2.2
T(-) Countdown: by twinpictures
baden03 – 2.3.15

Salient Visual Composer: by Michael M - WPBakery.com | Modified by ThemeNectar – 4.12
MailChimp for WordPress Lite: by ibericode – 2.3.17
Manufacturer Price: by Fantastic Plugins – 1.7
PayPal for WooCommerce: by Angell EYE – 1.3.1
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
WooCommerce SagePay Direct Payment Gateway: by DeviceSoftware – 0.1.7.4
SB-RSS_feed-plus: by Ladislav Soukup (ladislav.soukup@gmail.com) – 1.4.18
Sitemap: by webvitaly – 4.3
Threat Scan Plugin: by Keith P. Graham – 1.0
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.1.1

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.30

WooCommerce Breadcrumbs: by Anthony Hortin – 1.0.2
Woocommerce Custom Add to cart Text: by creativeG – 1.1.0
Follow-Up Emails: by WooThemes – 4.4.17 – 4.4.18 is available
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce AdWords Dynamic Remarketing: by Wolf + Bär GmbH – 1.3.3
WooCommerce MailChimp: by Saint Systems – 2.0.19
WooCommerce Google Product Feed: by Lee Willis – 7.0.1
WooCommerce Tab Manager: by WooThemes / SkyVerge – 1.7.3 – 1.8.0 is available
WooCommerce Table Rate Shipping: by Automattic – 3.0.2
WooCommerce: by WooThemes – 2.6.13
WooCommerce SagePayCw: by customweb GmbH – 3.0.64
WooCommerce Helper: by WooCommerce – 1.7.2
Yoast SEO: by Team Yoast – 4.1
WP Maintenance Mode: by Designmodo – 2.0.9
WP Rocket: by WP Media – 2.9.4
WPX Cron Manager Light: by Giovambattista Fazioli – 2.3.2

### Settings ###

Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #1127 - /shop/
Cart: #1128 - /cart/
Checkout: #1129 - /checkout/
My Account: #1130 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Salient
Version: 7.5.02
Author URL: http://themenectar.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: salient/woocommerce/cart/cart-shipping.php
salient/woocommerce/cart/cart-totals.php
salient/woocommerce/cart/cart.php
salient/woocommerce/cart/shipping-calculator.php
salient/woocommerce/checkout/form-checkout.php
salient/woocommerce/checkout/form-shipping.php
salient/woocommerce/checkout/review-order.php
salient/woocommerce/content-product.php
salient/woocommerce/content-product_cat.php
salient/woocommerce/content-single-product.php
salient/woocommerce/loop/add-to-cart.php
salient/woocommerce/myaccount/form-login.php
salient/woocommerce/single-product/product-image.php
salient/woocommerce/single-product/tabs/description.php
salient/woocommerce/single-product/tabs/tabs.php

`

**Comment by mikejolley** [comment]
No problems here - on-hold status is valid and used https://github.com/woocommerce/woocommerce/blob/master/includes/admin/reports/class-wc-report-sales-by-date.php#L195

Have not been any recent auto updates. Last was in feb. Maybe the gateway is not setting the correct "on-hold" status, or it's cached. I don't see anything else in core which would break this in particular.

Experiment with a manual order or different gateway.
