### ISSUE TITLE
Improvement Request: Don't nest selectors if not really necessary

### ISSUE THREAD

**Issue by rellect** [woocommerce/woocommerce#13886]
This is an improvement suggestion.
I saw few cases of sass code such as this
```
table.my_account_orders {
	tr {
		td {
			&.order-actions {
				text-align: left;

				&::before {
					display: none;
				}

				.button {
					float: none;
					margin: 0.125em 0.25em 0.125em 0;
				}
			}
		}
	}
}
```
Put aside if such specificity is necessary, this deep nesting just makes things complicated.
It's harder to search selectors and it makes code longer to read.
Sass is powerful but nesting should be used wisely.

To clarify, the above should look like this
```
table.my_account_orders tr td.order-actions {
	text-align: left;

	&::before {
		display: none;
	}

	.button {
		float: none;
		margin: 0.125em 0.25em 0.125em 0;
	}
}
```

I

**Comment by mikejolley** [comment]
Sounds like something we can work into future additions or changes, rather than refactoring it all at once (since the end result CSS should be identical). Feel free to submit a PR for the above changes if you want and we'll merge for 3.1.

Thanks

cc @jameskoster
