### ISSUE TITLE
Only variation Id when $woo->get("products") instead of array

### ISSUE THREAD

**Issue by WaldenStew** [woocommerce/woocommerce#13881]
Actually i use WordPress 4.6.4 with Woocommerce 2.6.11 and everything is OK.
The application I have developed works perfectly.
Now, i want to try the new beta 3.0.0 with wordpress 4.7 to prepare to upgrade my application soon.

So when I try use $woo->get("products"), the API returns me:
             [variations] => Array
                (
                    [0] => 52
                )
But with the old version, the API returns me an array:

 [variations] => Array
                (
                    [0] => Array
                        (
                            [id] => 1450
                            [date_created] => 2017-04-03T08:53:25
                            [date_modified] => 2017-04-03T08:53:25
                            [permalink] => http://myWebsite/product/baguette/
                            [sku] => 
                            [price] => 
                            [regular_price] => 
                            [sale_price] => 
                            [date_on_sale_from] =>  etc ......
I searched in the issues to know if the variation system has change ..but i found nothing to help me.. so.. is it a bug? 
Thanks
 Steeve

**Comment by mikejolley** [comment]
First port of call should be the documentation which shows what each property should be https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

New API = New endpoints = New data.
