### ISSUE TITLE
Variation ID instead Variation Description in Order Page WOO3-RC2

### ISSUE THREAD

**Issue by hopesemper** [woocommerce/woocommerce#13882]
In the Order Page I see the Variation ID of the products in the list of items purchased, instead the Variation Description like before
Just Add to the Order a Product with some variation. Using Woocommerce 3 RC2. Not with the stable release. Also with the StoreFront theme.

**Comment by mikejolley** [comment]
It's part of the titles in 3.0 
![2017-04-03 at 12 12](https://cloud.githubusercontent.com/assets/90977/24606842/e9f29864-1866-11e7-85f6-2645d78bee77.png)
