### ISSUE TITLE
Incorrect pull for shop_order_table for partially and fully refunded orders

### ISSUE THREAD

**Issue by alexkovachevic** [woocommerce/woocommerce#13892]
## EXPLANATION OF THE ISSUE

Report pulls all **completed**, **processing** and **on-hold** orders and ALL shop_order_refunds. Some shop_order_refunds are attached to **refundned**  orders.

class-wc-report-sales-by-product.php

This means that the report is deducting more refunds then it should.

## STEPS TO REPRODUCE THE ISSUE

Make 3 orders of same product, qty 5. 
Refund 1 order completely, refund 1 order partially (2 products)

And pull report for that product

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
No issue in master with your example.

![2017-04-04 at 11 31](https://cloud.githubusercontent.com/assets/90977/24652663/9736fc04-192a-11e7-9168-960d919ad3df.png)

**Comment by alexkovachevic** [comment]
Actually issue is in single product view of reporting, replicated with freshly updated WooCoomerce
![screenshot 2017-04-04 12 37 37](https://cloud.githubusercontent.com/assets/26896009/24652813/864ab8f0-1933-11e7-966c-1e7573c2be43.png)

15 items across 3 orders (5 per order), 1 order full refunded (5 items, wc-refunded post status) 1 order partial refund (2 items, wc-on-hold status -- on hold is for ease of testing, works with wc-completed as well)

So the report is saying 2 purchases but it should say 7.

![screenshot 2017-04-04 12 38 50](https://cloud.githubusercontent.com/assets/26896009/24652865/be641164-1933-11e7-9f2a-9dec41c56b32.png)

The issue is that even shop_order_refunds belonging to wc-refunded orders are counted  but the purchases from wc-refunded are not, so the math is incorrect (deducting more refunds then there should be)

**Comment by mikejolley** [comment]
It's also fine in master 
![2017-04-04 at 11 46](https://cloud.githubusercontent.com/assets/90977/24653120/672ca19c-192c-11e7-84d0-c5821f2ce242.png)

**Comment by mikejolley** [comment]
Master is v3.0.0 which is not released yet.

**Comment by alexkovachevic** [comment]
Oh - so bug exists in production version, but has already been fixed?

**Comment by claudiosanches** [comment]
@alexkovachevic In a few hours 3.0.0 will be the product version.
