### ISSUE TITLE
Hook woocommerce_email_before_order_table seems to no longer work

### ISSUE THREAD

**Issue by absoluteweb** [woocommerce/woocommerce#13897]
## EXPLANATION OF THE ISSUE

My plugins use the hook woocommerce_email_before_order_table to add content into customer email, no longer work since WooCommerce 3.0. Can you confirm a problem?

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mikejolley** [comment]
No problem, still exists https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=woocommerce_email_before_order_table&type=

But note, emails are deferred, so if your code is not present when the email actually sends, it won't do anything.

https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#notification-email-sending

**Comment by absoluteweb** [comment]
Check payment use woocommerce_email_before_order_table and instructions are not included into the customer email.
