### ISSUE TITLE
Query by - date_modified for Customers and Products

### ISSUE THREAD

**Issue by hikarushin** [woocommerce/woocommerce#13895]
I want to query by date_modified for Customers and products. Is that possible? We are integrating the WooCommerce to our ERP, but I want to get only the Customers and Products that are updated. Of course no one will not like if I will get all the Customers and Products in certain xx of minutes. What parameters should I used to achieved that?

![image](https://cloud.githubusercontent.com/assets/5128620/24664696/e74f6d6c-198d-11e7-9208-b0896eb9c475.png)

`
### WordPress Environment ###
 
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: ✔
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.17-1~dotdeb+8.1
PHP Post Max Size: 10 MB
PHP Time Limit: -1
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Publicación remota: ✔
Obtención remota: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (13) ###

Contact Form 7: por Takayuki Miyoshi – 4.7
Hello Dolly: por Matt Mullenweg – 1.6
Imagify: por WP Media – 1.6.3
Nextend Facebook Connect: por Nextendweb – 2.0.2
Nextend Google Connect: por Roland Soos
Jamie Bainbridge – 1.6.1

Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 2.2.6
Braintree For WooCommerce Pro: por Payment Plugins
support@paymentplugins.com – 2.6.1

Woocommerce All Discounts: por ORION – 1.8
WooCommerce PayPal Express Checkout Gateway: por Automattic – 1.1.2
WooCommerce: por WooThemes – 2.6.14
WooSidebars: por WooThemes – 1.4.3
Yoast SEO Premium: por Team Yoast – 4.5
Yoast SEO: WooCommerce: por Team Yoast – 4.5
FG Magento to WooCommerce Premium: por Frédéric GILLES – 2.20.2
WP All Export Pro: por Soflyy – 1.4.5
WP All Import Pro: por Soflyy – 4.4.3
WP All Import - Link Cloaking Add-on: por Soflyy – 1.1.0
WP All Import - User Import Add-On: por Soflyy – 1.0.9
WP All Import - WooCommerce Add-On Pro: por Soflyy – 2.3.4
iThemes Sync: por iThemes – 1.174.0
createIT Size Guide Plugin: por createIT – 2.1
WooCommerce MailChimp: por Saint Systems – 2.0.20
WooCommerce Sequential Order Numbers Pro: por WooThemes / SkyVerge – 1.10.1 – 1.11.0 está disponible
WooCommerce Force Default Variant: por HappyKite – 1.2
WooCommerce Variation Swatches: por ThemeAlien – 1.0.1
BackupBuddy: por iThemes – 7.3.0.3
Remove HTTP: por Fact Maven – 2.0.0
WooCommerce Google Analytics Integration: por WooThemes – 1.4.0
YITH WooCommerce Name Your Price: por YITHEMES – 1.0.7
MailChimp for WordPress: por ibericode – 4.1.0
WooCommerce Product Feed Manager: por Michel Jongbloed – 1.6.5
WooCommerce Bulk Edit Product Variations: por matterico_themes – 2.6
Braintree For WooCommerce Pro: por Payment Plugins
support@paymentplugins.com – 2.6.1

WP Rocket: por WP Media – 2.9.10
Nextend Google Connect: por Roland Soos
Jamie Bainbridge – 1.6.1

Woocommerce All Discounts: por ORION – 1.8
Yoast SEO Premium: por Team Yoast – 4.5
Yoast SEO: WooCommerce: por Team Yoast – 4.5
WP-Mail-SMTP: por Callum Macdonald – 0.10.1
CC & BCC for Woocommerce Order Emails: por Dario Curasì – 1.4.1
WooCommerce Shipping Tracking: por Lagudi Domenico – 10.2
WooCommerce Shipping Tracking - Bulk import addon: Import Sequential Order Number Pro: por Lagudi Domenico – 1.0

### Settings ###

Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Base de la tienda: ❌ La visibilidad de la página debería ser público
Carrito: #124586 - /cart/
Finalizar compra: #124585 - /checkout/
Mi cuenta: #124584 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.2.5
Parent Theme Author URL: //www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
This is not supported afaik. Supported query options are listed in the new docs (this is for v2 api in 3.0) https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-customers

Customers you can sort by registered date, not modified date.

If you're trying to track updates to customers + projects, consider webhooks instead.

**Comment by hikarushin** [comment]
@mikejolley can you please post a sample webhooks? I'm stuck where to find the Delivery URL is.
