### ISSUE TITLE
Loading Failed message with Select2 v4 wc-product-search inputs

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#13890]
## EXPLANATION OF THE ISSUE

When searching for a product via the `wc-product-search` input with current `master` branch, a _Loading Failed_ message is displayed after typing 3+ characters (i.e. when the search begins) and when the search results are returned/loaded.

Gif demonstration:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/39031t1Q3S0y2s163b2R/Screen%20Recording%202017-04-03%20at%2005.01%20pm.gif?X-CloudApp-Visitor-Id=667152&v=3df65ea2)

The location of the _Loading failed_ element also seems to "stick" on the 2nd search.

## STEPS TO REPRODUCE THE ISSUE

1. Go to **WooCommerce > Edit Order** screen
1. Go to **Downloadable product permissions** metabox
1. Click in the select element
1. Search for a product

**Comment by Umangvaghela** [comment]
Hi @thenbrent 

If ajax call is inconsistent that time loading failed  message is display.I have tested this issue with current version of WooCommerce  but I have not found this issue. Can you explain more about it. 

Thanks

**Comment by mikejolley** [comment]
It's a select2 bug here https://github.com/select2/select2/issues/4355 for loading failed. Can 'hide' it but cannot fix it.

**Comment by mikejolley** [comment]
The other issue is select2 and seems to be reported here https://github.com/select2/select2/issues/4816

We'll update the library when it's available. It's won't fix from our side.
