### ISSUE TITLE
Customer session address not updating after login

### ISSUE THREAD

**Issue by saulfautley** [woocommerce/woocommerce#13906]
## EXPLANATION OF THE ISSUE

On fresh install of latest WordPress, latest WooCommerce 3.0.0.

Checkout is not using the saved billing/shipping address of a customer by default after they log in. It is using the customer session address from before the customer logged in.

This is particularly an issue in the case where the country is automatically set by the system, i.e. `Default customer location` setting. If the default country/state is different from a customer's saved country/state, then after the customer logs in the checkout form will show their saved address except for the country/state, which will still be the default country/state set in the session.

This is confusing for a customer and forces them to correct their address every time they come to the site and go to checkout (if they were not already logged in).

A similar thing happens when you enter an address at checkout as a guest and then login - your saved address won't be used in the checkout form, it will still use the address you had previously entered in as a guest. This could maybe be considered a feature if it weren't for the fact that there's absolutely no way to get the checkout form to update to your *saved* address, again forcing you to re-enter your saved address manually if it is different from the one you entered as a guest in any way.

## STEPS TO REPRODUCE THE ISSUE

1. `Base location` = US, `Default customer location` = Shop base address
2. Create a customer with a UK billing/shipping address.
3. In an incognito window, add a product as a guest, then login with the UK customer.
3. Go to checkout and the country/state fields will show the shop's base location (US), not the customer's saved country/state (UK).

**Comment by nerdy-kronos** [comment]
@claudiosanches @mikejolley I had the same issue and applied the patch (solved the bug).
But I think the patch should have been already present.

wordpress: 4.8
woocommerce: 3.1.0

I am a newbie so please excuse my mistakes. :)
