### ISSUE TITLE
Use only CSS for RTL styling.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#13908]
This issue was discovered at https://wordpress.org/support/topic/styling-issue-with-settings-api/

Input RTL handling would be better done with pure CSS, instead of sprinkling control characters through the codebase. In addition, control characters like `&lrm;` tie the presentation to the functionality, which is not really a good practice.

Screenshot of problem:
<img width="405" alt="screen shot 2017-04-04 at 1 15 19 pm" src="https://cloud.githubusercontent.com/assets/7317227/24677031/2f8553de-193a-11e7-9d24-4887c42852ec.png">

**Comment by rellect** [comment]
The &lrm; char is zero width character, the extra space is probably because the whitespace that comes after it.

I agree that css only is preferable, but there are cases where it's not going to be easy without extra markup, and even then it may be not so flexible.

**Comment by claudiosanches** [comment]
@rellect still the fix should be only applied to the color picker, right? If so I think I fixed it in #13909

**Comment by rellect** [comment]
Yes, the problem was only with the color picker. It slipped my mind that other fields are involved there, my bad. I'll take a look at your fix
