### ISSUE TITLE
Additional Variation Images does only load the additional images

### ISSUE THREAD

**Issue by Ragowit** [woocommerce/woocommerce#13901]
## EXPLANATION OF THE ISSUE

WooCommerce Additional Variation Images 1.7.5 with WooCommerce 3.0.0
Along with my main image for my variable product so do I add additional images, and I expect all of these images to be seen but only those under additional images are shown.

## STEPS TO REPRODUCE THE ISSUE

Create a variable product. Add some images.
Create a variant for this product. Add a main image and some additional variation images.
Go to this product, select the variant. Notice that only the additional variation images are shown.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

Home URL: https://grh.se
Site URL: https://grh.se
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 256 MB
PHP Time Limit: 240
PHP Max Input Vars: 10000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: tu6u_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Edit Author Slug: av Brandon Allen – 1.3.0
Jetpack från WordPress.com: av Automattic – 4.7.1
Limit Login Attempts: av Johan Eenfeldt – 1.7.1
Really Simple SSL: av Rogier Lankhorst – 2.5.11
Smart Reporter for e-commerce: av StoreApps – 2.9.16
W3 Total Cache: av Frederick Townes – 0.9.5.2
WooCommerce Additional Variation Images: av WooCommerce – 1.7.5
WooCommerce - Store Exporter: av Visser Labs – 1.8.8
WooCommerce Swish Ecommerce Gateway: av Redlight Media – 1.3
WooCommerce Google Analytics Integration: av WooThemes – 1.4.0
WooCommerce PDF Invoices & Packing Slips: av Ewout Fernhout – 1.6.1
WooCommerce Pricefiles: av Peter Elmered – 1.0.0-beta
WooCommerce: av Automattic – 3.0.0
WooCommerce Helper: av WooCommerce – 1.7.2 – Nätverk aktiverat
WP-SpamShield: av Scott Allen – 1.9.9.9.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Butikbas: #4 - /shop/
Varukorg: #5 - /cart/
Kassan: #6 - /checkout/
Mitt konto: #7 - /my-account/

### Theme ###

Name: Boutique
Version: 2.0.7
Author URL: http://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by mikejolley** [comment]
I cannot comment on how this worked previously or how it should work - it sounds like the images for the variation are showing so it does it's job.

CC'ing @roykho Roy, if this is a bug, can you move to the correct repo please?

**Comment by roykho** [comment]
Issue moved to [woocommerce/woocommerce-additional-variation-images #25](https://github.com/woocommerce/woocommerce-additional-variation-images/issues/25) via [**ZenHub**](https://www.zenhub.com/)

**Comment by roykho** [comment]
@Ragowit - Thanks for reporting. I have logged your issue in the correct repo and will fix that issue by next release.

**Comment by Ragowit** [comment]
@roykho - Thank you, and I can confirm that 1.7.6 fixes my issue. Thanks a lot.

**Comment by GrahamC-me** [comment]
@roykho still seeing the same problem if variations have more than 1 custom attribute.

Create a variable product with 2 custom product attributes (e.g. size, colour). Add some images.
Create a variant for this product. Add a main image and some additional variation images.
Go to this product, select a value for both custom product attributes (e.g. Large, Pink).
Notice that only the additional variation images are shown.

**Comment by mikejolley** [comment]
@GrahamC-me This issue is 3 months stale and not for core - can you use the helpdesk please?

Closing this since the original issue is resolved.
