### ISSUE TITLE
CSS bug?

### ISSUE THREAD

**Issue by artprojectgroup** [woocommerce/woocommerce#13907]
![captura de pantalla 2017-04-04 a las 22 14 00](https://cloud.githubusercontent.com/assets/6569259/24676643/0fcab044-1984-11e7-9a83-4464d3672ce0.jpg)

I detect this bug on two installations with WooCommerce 3.0 and Avada 5.1.5

And on frontend .hidden is a blank class, without `display:none;`.

Great job!

Kind regards.

**Comment by mikejolley** [comment]
This is related to select2. Clear your caches!

**Comment by artprojectgroup** [comment]
Thanks for your answer Mike. 

I deleted the cache before open this, but now works fine both :-D

Kind regards.
