### ISSUE TITLE
Page is refreshing/reloading automatically in all pages 

### ISSUE THREAD

**Issue by Vijayshubhankar** [woocommerce/woocommerce#13905]
#13902  EXPLANATION OF THE ISSUE

<!-After updating woocommerce plugin to 3.0, problem of page reloading arises.
This happens in all the pages except dashboard. -->

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/13902

**Comment by Vijayshubhankar** [comment]
Hey!! Have you considered this as an issue and closed this issue because its a duplicate?
