### ISSUE TITLE
Page is permanently reloading

### ISSUE THREAD

**Issue by jowgn** [woocommerce/woocommerce#13902]
## EXPLANATION OF THE ISSUE

When "Default customer location" (Woocommerce settings - General) is set to use page cash the page will reload permanently.

## STEPS TO REPRODUCE THE ISSUE

change setting "Default customer location"

**Comment by mikejolley** [comment]
Confirmed.

**Comment by t-bo** [comment]
This happens to me if Geolocate is enabled (caching support or not enabled).

**Comment by XcomBattle** [comment]
thanks for your help

**Comment by Rellis27** [comment]
Yes that was the Error the  "geolocation settings"  thanks  mikejolley
