### ISSUE TITLE
3.0: WC_Abstract_Order::set_paymet_method() no longer writes to database

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#13915]
In WC < 3.0, a call to `WC_Abstract_Order::set_payment_method()` would write the new payment method data to the database. In WC 3.0, it will not.

It makes sense that it doesn't with CRUD, because the method is now just a setter, and setter's don't write to the database. But because the method existed prior to 3.0, unlike most other setters, it's behaviour has been broken.

I'm not sure the best fix for this is to call `save()` within it. Instead, it might just need to be added to the [migration notes](https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes).

**Comment by mikejolley** [comment]
Added to the notes - looks like extendables may have already worked around this. Calling save early could break other parts of the CRUD.

`update_payment_method` is unaffected.
