### ISSUE TITLE
woocommerce_debug_posting hook removed

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#13918]
## EXPLANATION OF THE ISSUE

SHA: 8df6ff3c removed the `'woocommerce_debug_posting'` filter from the **WooCommerce > System Status** page. This filter could previously be used to add rows to the System Status page (which Subscriptions did).

We're moving to add a new section on the `'woocommerce_system_status_report'` instead, but wanted to report it in case you want to document it or fix it.

**Comment by om4james** [comment]
I noticed this yesterday too when making the WC Zapier extension compatible with WC 3.0.

Are WC extension developers encouraged to use the new status report functionality, or are there plans to restore this `woocommerce_debug_posting` hook?

Thank you :)

**Comment by mikejolley** [comment]
Looks like it's gone because the array of status data is generated elsewhere so it's available in API. 

@justinshreve thoughts?

**Comment by justinshreve** [comment]
Let's add it back in with a different name, with `woocommerce_debug_posting` as a deprecated alias. It's not named well since it's technically related to the POST/Get Rows. There's still some value to have a hook on that page even if the info is generated in the API.
