### ISSUE TITLE
Hook woocommerce_add_to_cart repeat 3 times.

### ISSUE THREAD

**Issue by julioc96** [woocommerce/woocommerce#13911]
I have a function that save in database when anyone add to cart some product.  I use the action  add_action(" woocommerce_add_to_cart", someFunction) to execute this code. Before Woocommerce 3.0 it worked fine but now the hook is reproducing 3 times for action.

If some user added to cart some product, this repeat 3 times the hooks. 

I debug the file class-wc-cart.php in function add_to_cart and thi is execute 3 times by execution.

**Comment by mikejolley** [comment]
You could debug at this point https://github.com/woocommerce/woocommerce/blob/71d0702523bcc365403dd3b84b945da5218d88b4/includes/class-wc-cart.php#L966 I only see 1 call to that action.

**Comment by mikejolley** [comment]
Tested this with an error log. It only logs once for adding items to the cart, not 3 times.

**Comment by julioc96** [comment]
I did that before posted this thread. Three times, 2 in core and one more when page has been refreshed and woocommerce add in url this parameter ?add-to-cart=53. 

![captura de pantalla 2017-04-05 a las 9 05 18 a m](https://cloud.githubusercontent.com/assets/4606051/24709303/13478fe8-19df-11e7-80b7-7f73df858a23.png)

![captura de pantalla 2017-04-05 a las 9 06 06 a m](https://cloud.githubusercontent.com/assets/4606051/24709329/2357a1de-19df-11e7-8bcd-9854eccc8bec.png)

**Comment by julioc96** [comment]
I did a new test, i added two products to my cart and add_to_cart repeat 5 times.

![captura de pantalla 2017-04-05 a las 9 10 09 a m](https://cloud.githubusercontent.com/assets/4606051/24709541/d403ee2a-19df-11e7-8b82-9d276b385eb3.png)

**Comment by julioc96** [comment]
@mikejolley ?

**Comment by viktoro** [comment]
Old thread, but if anyone stumbles into this thread: 

I just experienced the same thing, although it was only repeated twice.

I found out that I had required woocommerce.php twice which caused this hook to fire multiple times. Not sure if that was what happened in this case, but maybe worth investigating.
