### ISSUE TITLE
Products Out of Stock after Update - cannot change this

### ISSUE THREAD

**Issue by merchify** [woocommerce/woocommerce#13916]
I use Woocommerce in German language. 
The new Version 3 bring some Problems.

- Translation failed. My Site is now in englisch
- Many products are after update "out of stock". I cannot change this in "in stock"

**Comment by kevin25** [comment]
I happened to me before.

**Comment by mikejolley** [comment]
> Translation failed. My Site is now in englisch

Translations need updating. Contribute here https://translate.wordpress.org/projects/wp-plugins/woocommerce

> Many products are after update "out of stock". I cannot change this in "in stock"

Edit product. Inventory tab. Uncheck manage stock. Set stock status to 'in stock'.

If it does not update, ensure it's not an incompatible extension blocking the update.
