### ISSUE TITLE
Can't access Product ID now it's protected

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#13929]
Just updated to v3 this morning and it caused havoc with almost everything. Updated all the WooCommerce official extensions and there are still issues with things like Smart Coupons.

But the most common issue i'm seeing is that the global `$product->id` is protected.

Is there a new way of accessing this information without having to rebuild everything that has the ID? Or is it that everything that I would have needed the ID for now just has it's own method of accessing it and I have to rewrite regardless?

**Comment by mikejolley** [comment]
https://woocommerce.wordpress.com/2017/01/17/deprecation-in-woocommerce-core/
