### ISSUE TITLE
photo gallery not working in 3.0

### ISSUE THREAD

**Issue by Emil44** [woocommerce/woocommerce#13926]
## EXPLANATION OF THE ISSUE

After updating to 3.0 the photo gallery doesn't work anymore. Pictures open in same browser tab, so you have to cllick "back" for your site. Anybody solved this problem?

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```

**Comment by mbgrafik** [comment]
Is your theme 3.0 ready?
https://woocommerce.wordpress.com/2017/02/28/adding-support-for-woocommerce-2-7s-new-gallery-feature-to-your-theme/

**Comment by mikejolley** [comment]
Read the release posts and that ^ and update your theme.
