### ISSUE TITLE
API product -> Categories not returning Category ID

### ISSUE THREAD

**Issue by Sturzaker123** [woocommerce/woocommerce#13924]
**## EXPLANATION OF THE ISSUE**
Call print_r($woocommerce->get('products')

Expected:

```
"categories": [
      {
        "id": 9,
        "name": "Clothing",
        "slug": "clothing"
      },
```

Received:
only returning the name...

```
 ["categories"]=>
    array(1) {
      [0]=>
      string(9) "Chainsaws"
    }


```which is no good because there can be 5 categories with the same name.

How do I get it to return the ID like it shows in the documentation.


**## STEPS TO REPRODUCE THE ISSUE**

When I call

http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

<?php print_r($woocommerce->get('products')); ?>

I Get returned:

```
array(2) {
  ["product"]=>
  array(58) {
    ["title"]=>
    string(14) "Tooline Prod 1"
    ["id"]=>
    int(103)
    ["created_at"]=>
    string(20) "2017-04-01T01:50:28Z"
    ["updated_at"]=>
    string(20) "2017-04-01T01:51:20Z"
    ["type"]=>
    string(6) "simple"
    ["status"]=>
    string(5) "trash"
    ["downloadable"]=>
    bool(false)
    ["virtual"]=>
    bool(false)
    ["permalink"]=>
    string(65) "http://localhost:84/wordpress/product/tooline-prod-1__trashed-32/"
    ["sku"]=>
    string(14) "TOOLINE PROD 1"
    ["price"]=>
    string(4) "0.00"
    ["regular_price"]=>
    string(4) "0.00"
    ["sale_price"]=>
    NULL
    ["price_html"]=>
    string(0) ""
    ["taxable"]=>
    bool(true)
    ["tax_status"]=>
    string(7) "taxable"
    ["tax_class"]=>
    string(0) ""
    ["managing_stock"]=>
    bool(false)
    ["stock_quantity"]=>
    int(0)
    ["in_stock"]=>
    bool(true)
    ["backorders_allowed"]=>
    bool(false)
    ["backordered"]=>
    bool(false)
    ["sold_individually"]=>
    bool(false)
    ["purchaseable"]=>
    bool(false)
    ["featured"]=>
    bool(false)
    ["visible"]=>
    bool(true)
    ["catalog_visibility"]=>
    string(7) "visible"
    ["on_sale"]=>
    bool(false)
    ["product_url"]=>
    string(0) ""
    ["button_text"]=>
    string(0) ""
    ["weight"]=>
    NULL
    ["dimensions"]=>
    array(4) {
      ["length"]=>
      string(1) "0"
      ["width"]=>
      string(1) "0"
      ["height"]=>
      string(1) "0"
      ["unit"]=>
      string(2) "cm"
    }
    ["shipping_required"]=>
    bool(true)
    ["shipping_taxable"]=>
    bool(true)
    ["shipping_class"]=>
    string(0) ""
    ["shipping_class_id"]=>
    NULL
    ["description"]=>
    string(22) "
TEST TL PRod 1

"
    ["short_description"]=>
    string(20) "
uyyiryiryiyu

"
    ["reviews_allowed"]=>
    bool(true)
    ["average_rating"]=>
    string(4) "0.00"
    ["rating_count"]=>
    int(0)
    ["related_ids"]=>
    array(1) {
      [0]=>
      int(104)
    }
    ["upsell_ids"]=>
    array(0) {
    }
    ["cross_sell_ids"]=>
    array(0) {
    }
    ["parent_id"]=>
    int(0)
    ["categories"]=>
    array(1) {
      [0]=>
      string(9) "Chainsaws"
    }
    ["tags"]=>
    array(0) {
    }
    ["images"]=>
    array(2) {
      [0]=>
      array(7) {
        ["id"]=>
        int(102)
        ["created_at"]=>
        string(20) "2017-04-01T01:45:16Z"
        ["updated_at"]=>
        string(20) "2017-04-01T01:45:16Z"
        ["src"]=>
        string(70) "http://localhost:84/wordpress/wp-content/uploads/2017/04/image-17.jpeg"
        ["title"]=>
        string(0) ""
        ["alt"]=>
        string(0) ""
        ["position"]=>
        int(0)
      }
      [1]=>
      array(7) {
        ["id"]=>
        int(101)
        ["created_at"]=>
        string(20) "2017-04-01T01:45:15Z"
        ["updated_at"]=>
        string(20) "2017-04-01T01:45:15Z"
        ["src"]=>
        string(70) "http://localhost:84/wordpress/wp-content/uploads/2017/04/image-16.jpeg"
        ["title"]=>
        string(0) ""
        ["alt"]=>
        string(0) ""
        ["position"]=>
        int(1)
      }
    }
    ["featured_src"]=>
    string(70) "http://localhost:84/wordpress/wp-content/uploads/2017/04/image-17.jpeg"
    ["attributes"]=>
    array(0) {
    }
    ["downloads"]=>
    array(0) {
    }
    ["download_limit"]=>
    int(0)
    ["download_expiry"]=>
    int(0)
    ["download_type"]=>
    string(0) ""
    ["purchase_note"]=>
    string(0) ""
    ["total_sales"]=>
    int(0)
    ["variations"]=>
    array(0) {
    }
    ["parent"]=>
    array(0) {
    }
  }
```
According to documentation it should be displayed in this format: http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

```
"categories": [
      {
        "id": 9,
        "name": "Clothing",
        "slug": "clothing"
      },
```
but it is only returning the name...

```
 ["categories"]=>
    array(1) {
      [0]=>
      string(9) "Chainsaws"
    }

```which is no good because there can be 5 categories with the same name.

How do I get it to return the ID like it shows in the documentation.

## SYSTEM STATUS REPORT

```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: http://localhost:84/wordpress
Site URL: http://localhost:84/wordpress
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 1,000 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.5.38
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 750 MB
PHP Time Limit: 259200
PHP Max Input Vars: 2000
cURL Version: 7.49.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
Max Upload Size: 750 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Image Cleanup: by Robbert Langezaal – 1.9.1
WooCommerce: by Automattic – 3.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Tried to verify this but no luck; it is working. 

![2017-04-05 at 10 33](https://cloud.githubusercontent.com/assets/90977/24699401/bf516fdc-19eb-11e7-8aca-d1e1b416a96d.png)

Try using the API via a client instead of with your code.
 
https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

cc @claudiosanches
