### ISSUE TITLE
Subscriptions paypal BUG - Some renewal orders are not registered as expected

### ISSUE THREAD

**Issue by menoz** [woocommerce/woocommerce#13922]
## EXPLANATION OF THE ISSUE

Hi, 
I think I found a Bug inside Subscriptions plugin, precisely in file includes\gateways\paypal\includes\class-wcs-paypal-standard-ipn-handler.php

What happens to me: my problem is that some renewal orders subscription I create are not marked as completed, even if Paypal correctly pays it AND sends IPN communication to my website.

To better understand why, I enabled Paypal logs, and I found that those transactions that are not marked as completed reports this error:

> Subscription IPN Error: IPN subscr_payment_feccb32da3369 message has already been correctly handled

Obviuosly, that IPN transaction wasn't handled before, but the plugin thinks so - and does not process it, that's why the relative order remains in waiting state.

I investigated furthermore and went to the **class-wcs-paypal-standard-ipn-handler.php** file, where I found that around lines 106 ( expecially line 118) and further on line 494 you use the "ipn_track_id" variable, and that's the problem! 
As I can see in my paypal logs, paypal sends me different IPN messages ( relative to different orders!)  but with the same ipn_track_id! I do not really know why, but this is what I saw in the logs:

> 03-29-2017 @ 15:05:35 - IPN Request: Array 
> ( 
> [body] => Array 
> ( 
> _[...]_ 
> [ipn_track_id] => feccb32da3369 
> )

AND, the DAY AFTER, a new IPN request for a NEW order but with THE SAME track_id:

> 03-30-2017 @ 14:44:39 - IPN Request: Array 
> ( 
> _[...]_ 
> [ipn_track_id] => feccb32da3369 
> )

And here's why the order dated 03-30-2017 remains in waiting state, because the plugin thinks that the last payment received as a copy of the previous one, where in fact it is a completely new one. 
Can you please fix this? Maybe using "txn_id" field instead "ipn_track_id"? I read here [1] that "ipn_track_id" is said to be only for Paypal internal use, so why don't you use "txn_id" that is 100% sure to be unique for every transaction?

[1] https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNandPDTVariables/

Thanks 
Daniele

Ps: 
Here the full IPN requests I received in those days:

> 03-29-2017 @ 15:05:35 - IPN Request: Array 
> ( 
> [body] => Array 
> ( 
> [cmd] => _notify-validate 
> [transaction_subject] => Subscription 110826 (Order 110825) - CLUB Membership Program (TEST) 
> [payment_date] => 04:04:31 Mar 29, 2017 PDT 
> [txn_type] => subscr_payment 
> [subscr_id] => I-WxxxxxxxxxxHNS0 
> [last_name] => menozzi 
> [residence_country] => US 
> [item_name] => Subscription 110826 (Order 110825) - CLUB Membership Program (TEST) 
> [payment_gross] => 
> [mc_currency] => EUR 
> [business] => menoz@xxx.it 
> [payment_type] => instant 
> [protection_eligibility] => Ineligible 
> [verify_sign] => AO-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-yH-3frDf4SE6BzN 
> [payer_status] => verified 
> [test_ipn] => 1 
> [payer_email] => menoz.xxxx@gmail.com 
> [txn_id] => 72D70898GA8745113 
> [receiver_email] => menoz@xxx.it 
> [first_name] => daniele 
> [invoice] => 110825 
> [payer_id] => FWxxxxxxxxxxxxWU 
> [receiver_id] => 4HHxxxxxxxxxSKS 
> [payer_business_name] => daniele menozzi's Test Store 
> [payment_status] => Completed 
> [payment_fee] => 
> [mc_fee] => 5.11 
> [mc_gross] => 122.00 
> [custom] => {"order_id":110825,"order_key":"wc_order_58d3fdd24f2bd","subscription_id":110826,"subscription_key":"wc_order_58d3fdd663013"} 
> [charset] => windows-1252 
> [notify_version] => 3.8 
> [ipn_track_id] => feccb32da3369 
> )
> 
> [timeout] => 60 
> [httpversion] => 1.1 
> [compress] => 
> [decompress] => 
> [user-agent] => WooCommerce/2.6.14 
> )
> 

[....]

> 03-30-2017 @ 14:44:39 - IPN Request: Array 
> ( 
> [body] => Array 
> ( 
> [cmd] => _notify-validate 
> [transaction_subject] => Subscription 110826 (Order 110825) - CLUB Membership Program (TEST) 
> [payment_date] => 03:43:54 Mar 30, 2017 PDT 
> [txn_type] => subscr_payment 
> [subscr_id] => I-WM1xxxxxxxxHNS0 
> [last_name] => menozzi 
> [residence_country] => US 
> [item_name] => Subscription 110826 (Order 110825) - CLUB Membership Program (TEST) 
> [payment_gross] => 
> [mc_currency] => EUR 
> [business] => menoz@xxx.it 
> [payment_type] => instant 
> [protection_eligibility] => Ineligible 
> [verify_sign] => AGV6csTgxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxh8uA0PAGYR0OlTBT 
> [payer_status] => verified 
> [test_ipn] => 1 
> [payer_email] => menoz.xxxxxx@gmail.com 
> [txn_id] => 0X6761016U045574M 
> [receiver_email] => menoz@xxx.it 
> [first_name] => daniele 
> [invoice] => 110825 
> [payer_id] => FWxxxxxxxxxxxMWU 
> [receiver_id] => 4HHxxxxxxxxxSKS 
> [payer_business_name] => daniele menozzi's Test Store 
> [payment_status] => Completed 
> [payment_fee] => 
> [mc_fee] => 5.11 
> [mc_gross] => 122.00 
> [custom] => {"order_id":110825,"order_key":"wc_order_58d3fdd24f2bd","subscription_id":110826,"subscription_key":"wc_order_58d3fdd663013"} 
> [charset] => windows-1252 
> [notify_version] => 3.8 
> [ipn_track_id] => feccb32da3369 
> )
> 
> [timeout] => 60 
> [httpversion] => 1.1 
> [compress] => 
> [decompress] => 
> [user-agent] => WooCommerce/2.6.14 
> )

## STEPS TO REPRODUCE THE ISSUE

Create 2 or 3 daily recurring orders with the same customer (and the same paypal account), in a few days you will notice that some payment will not be registered by WC as expected, because some IPN transactions will have the same ipn_track_id. I'm using a sandbox account for these tests.

## SYSTEM STATUS REPORT

`
### WordPress Environment ###

Home URL: https://dev.xxx.it
Site URL: https://dev.xxx.it/cms
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 2 GB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 2 GB
Default Timezone is UTC: ❌ Il fuso orario predefinito è Europe/Rome - Dovrebbe essere UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
POST remoto: ✔
GET remoto: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ Il database di MaxMind GeoIP non esiste - La geolocalizzazione non funzionerà. Puoi scaricarlo da http://dev.maxmind.com/geoip/legacy/geolite/ ed installarlo manualmente in: . Scorri a \"Downloads\" e scarica il file \"Binary / gzip/" dopo \"GeoLite Country\"

### Active Plugins (47) ###

Admin Show Sticky: by Matt Martz – 1.0
Advanced Custom Fields: by Elliot Condon – 4.4.11
Anti-Spam Akismet: by Automattic – 3.3
Contact Form 7: by Takayuki Miyoshi – 4.7
Simple Custom CSS and JS: by Diana Burduja – 2.10
Disqus Comment System: by Disqus  – 2.86
Duplicate Post: by Enrico Battocchi – 3.2
Easy Facebook Likebox: by Sajid Javed – 4.3.0
Facebook Conversion Pixel: by Kellen Mace – 1.3.5
Filament: by dtelepathy – 1.2.14
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.6
iframe: by webvitaly – 4.3
Image Widget: by Modern Tribe
Inc. – 4.3.1

WPBakery Visual Composer: by Michael M - WPBakery.com – 5.0.1
PayPal for WooCommerce: by Angell EYE – 1.3.3
PCOM ACCA: by Simone Conti – 1.0.0
PCOM Affiliates: by Simone Conti – 1.0.3-dev.0
PCOM FP Customizations: by Simone Conti – 1.3.11-dev.0
PCOM Ground Control: by Simone Conti – 1.2.6-dev.0
PCOM Instant Products: by Simone Conti – 1.4.6-dev.0
PCOM Major Tom Landing: by Simone Conti – 1.5.11-dev.0
PCOM S3 Upload Interface: by Simone Conti – 1.2.1-dev.0
PCOM Supervisor: by Simone Conti – 1.3.1-dev.0
PCOM Woo Codice Fiscale: by Simone Conti – __GRUNT_REPLACE_WITH_VERSION__
PCOM WOO Hooks: by Simone Conti – 1.6.3-dev.0
PCOM Woo Products Manager: by Simone Conti – 1.1.4-dev.3
PCOM Workshop Cal Widget: by Simone Conti – 1.1.2-dev.0
PP&P - Professional Photography & Post-Production: by Simone Conti – 1.0.1 $Rev: 287 $
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Search & Replace: by Inpsyde GmbH – 3.1.2
Simple Share Buttons Adder: by Simple Share Buttons – 6.3.4
Under Construction: by Noah Kagan – 1.18
Vafpress Framework Plugin: by Vafpress – 2.0.1
WC Product Bundles: by Saravana Kumar K – 1.0.7
WF Cookie Consent: by wunderfarm – 1.1.2
WooCommerce Cart Tab: by jameskoster – 1.1.1
WooCommerce My Account Widget: by Bart Pluijms – 0.5.0
WooCommerce Order Status Control: by WooThemes / SkyVerge – 1.7.0 – 1.8.0 è disponibile
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.1
WooCommerce Subscriptions: by Prospress Inc. – 2.1.4
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
Before After Image/Content Slider: by MOEWE Studio (by Adrian Mörchen) – 2.3
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.5
WP Crontrol: by John Blackbourn & Edward Dale – 1.4
WP Pusher: by WP Pusher – 2.2.0

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #14625 - /eshop
Carrello: #14626 - /carrello
Cassa: #14627 - /checkout
Il mio account: #14628 - /il-mio-account

### Taxonomies ###

Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: FotografiaProfessionale
Version: 1.0
Author URL: http://www.xxx.it/
Child Theme: ❌ – Se stati modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

### Templates ###

Overrides: fotografiaprofessionale.wptheme/woocommerce/archive-product.php
fotografiaprofessionale.wptheme/woocommerce/cart/cart-empty.php
fotografiaprofessionale.wptheme/woocommerce/cart/cart-totals.php
fotografiaprofessionale.wptheme/woocommerce/cart/cart.php
fotografiaprofessionale.wptheme/woocommerce/cart/proceed-to-checkout-button.php
fotografiaprofessionale.wptheme/woocommerce/checkout/form-billing.php
fotografiaprofessionale.wptheme/woocommerce/checkout/form-checkout.php
fotografiaprofessionale.wptheme/woocommerce/checkout/form-login.php
fotografiaprofessionale.wptheme/woocommerce/checkout/form-pay.php
fotografiaprofessionale.wptheme/woocommerce/checkout/payment.php
fotografiaprofessionale.wptheme/woocommerce/checkout/thankyou.php
fotografiaprofessionale.wptheme/woocommerce/content-product.php
fotografiaprofessionale.wptheme/woocommerce/content-product_cat.php
fotografiaprofessionale.wptheme/woocommerce/content-single-product.php
fotografiaprofessionale.wptheme/woocommerce/myaccount/form-edit-account.php
fotografiaprofessionale.wptheme/woocommerce/myaccount/form-edit-address.php
fotografiaprofessionale.wptheme/woocommerce/myaccount/form-login.php
fotografiaprofessionale.wptheme/woocommerce/myaccount/form-lost-password.php
fotografiaprofessionale.wptheme/woocommerce/myaccount/my-account.php
fotografiaprofessionale.wptheme/woocommerce/myaccount/view-order.php
fotografiaprofessionale.wptheme/woocommerce/order/order-details-customer.php
fotografiaprofessionale.wptheme/woocommerce/single-product.php
fotografiaprofessionale.wptheme/woocommerce/taxonomy-product_cat.php

`

**Comment by mikejolley** [comment]
Please use https://woocommerce.com/my-account/tickets/ so the Subscriptions developers/support can look into this. This is the WC core github.

cc @thenbrent 

Thanks

**Comment by menoz** [comment]
Yeah.. That was my first shot.
I opened ticket n. 554377 in their ticketing system, I too thought they should fix this - but they told me to write here.

I'll get back to them.

**Comment by thenbrent** [comment]
Sorry for the confusion @menoz, I've assigned the Prospress team to your ZenDesk ticket and will make sure we get you an answer soon.

**Comment by louie171** [comment]
@menoz @thenbrent did you find a solution to this, I think I have the same problem

**Comment by thenbrent** [comment]
@louie171 we have a fix currently in review and it should be released in the next version of Subscriptions - v2.2.7.

Apologies for the delay and any trouble this has caused you. It's taking longer than hoped to ship the fix because we need to test as many cases as possible with actual PayPal IPNs. The docs don't clarify what is and isn't a unique ID for each IPN.

**Comment by louie171** [comment]
@thenbrent thanks, appreciate you coming back to me. look forward to 2.2.7 , fortunately it's only 1 order affected to date.

**Comment by menoz** [comment]
@thenbrent Thank you for your work; luckily I only had those problems during testing (up until now).
I believe that it's more likely to crash in this bug when you have very close payments (eg every day or every 3 days). I didn't get any problems on monthly payments so far (what we really use in production enviroment).

**Comment by jarmosiim** [comment]
Any news on the update? We have several orders every day with this and only found out about this issue ca 3 weeks after we started having it = have to check every day to make sure all orders are processed.

**Comment by hannahswain** [comment]
Subscriptions version 2.2.7 was released on 27 May. You should have access to it via your dashboard - if not, contact WooCommerce support for further assistance.

**Comment by jarmosiim** [comment]
Not according to the product’s own page, WP updates page or its change log:

https://woocommerce.com/products/woocommerce-subscriptions/
http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-subscriptions/changelog.txt


On 30 May 2017 at 13:30:27, Hannah Swain (notifications@github.com) wrote:

Subscriptions version 2.2.7 was released on 27 May. You should have access to it via your dashboard - if not, contact WooCommerce support for further assistance.

**Comment by rvpatel** [comment]
I have using 
WooCommerce Subscriptions 2.0.18.
WooCommerce - 2.6.4
wordpress - 4.6

Last 2 months user payment (paypal recurring) not created as renewal order. All ready paypal processed payments.

I have checked payment log says.

Subscription IPN Error: IPN subscr_payment_{xxipn_track_idxx} message has already been correctly handled.

This one issue from paypal or woocommerce code?

**Comment by thenbrent** [comment]
> I have using
> WooCommerce Subscriptions 2.0.18.

Please update to the latest version.

> Subscription IPN Error: IPN subscr_payment_{xxipn_track_idxx} message has already been correctly handled.

PayPal started sending the same `ipn_track_id` for different IPN messages in some cases around April/May. We addressed that in Subscriptions v2.2.7 back in May. See this changelog entry:

> * Fix: Use more than 'ipn_track_id' for different PayPal IPN messages now that PayPal has suddenly begun to use the same 'ipn_track_id' for different IPN messages. PR#2090

If you update to v2.2.7 or newer, you won't have the issue anymore.

**Comment by rvpatel** [comment]
@thenbrent Thanks for reply.

Now one question every update on woocommerce document changed.

Now my auto renewal order not created & payment processed success by paypal. 

How to create my renewal order entry in subscription?  Simple options available but parent & subscription relation not managed by manually.

**Comment by jarmosiim** [comment]
I actually have now the same issue - some of the payments that were not correctly processed and that were manually processed by us due to that in that specific month, are not renewing automatically. This means that we’ve been having to check every Paypal renewal payment in the past month manually. However, I’ve noticed that these subscriptions are in the system as 'active' BUT with the 'next payment' date in the past.

On 12 July 2017 at 18:09:54, Ravi Patel (notifications@github.com) wrote:

@thenbrent Thanks for reply.

Now one question every update on woocommerce document changed.

Now my auto renewal order not created & payment processed success by paypal.

How to create my renewal order entry in subscription? Simple options available but parent & subscription relation not managed by manually.

**Comment by thenbrent** [comment]
@rvpatel @jarmosiim please submit support request for these questions/issues here: https://woocommerce.com/my-account/create-a-ticket/

**Comment by jarmosiim** [comment]
Thanks for the suggestion but it usually takes more than a month to solve such issues via the ticketing system and thus it seems more reasonable to have that information publicly available.

On 13 July 2017 at 05:03:47, Brent Shepherd (notifications@github.com) wrote:

@rvpatel @jarmosiim please submit support request for these questions/issues here: https://woocommerce.com/my-account/create-a-ticket/

**Comment by rvpatel** [comment]
@thenbrent
I have managed manually entry with database changes now need document how to created scheduled-action for next payment.

Which function on this one auto created?

**Comment by kennedyluke** [comment]
Seeing the same issue also with the latest version of all WC extensions and WC core.

Agree with @jarmosiim if solutions were publicly posted it would help those who are finding the GH issues.

WC support isn't what it used to be. Although I totally understand the challenge in offering support to a quarter of all e-commerce stores on the internet!

**Comment by thenbrent** [comment]
@kennedyluke whenever there is a solution that helps more than one store, we do publish that solution publicly by releasing a fix in Subscriptions codebase. As was done in v2.2.7 of Subscriptions to address the issue mentioned in this comment: https://github.com/woocommerce/woocommerce/issues/13922#issuecomment-314281558

That fix was also mentioned publicly in the [changelog](https://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-subscriptions/changelog.txt):

> * Fix: Use more than 'ipn_track_id' for different PayPal IPN messages now that PayPal has suddently begun to use the same 'ipn_track_id' for different IPN messages. PR#2090

The general problem being reported on this Issue is just a symptom of a problem which has an infinite number of different ways it can occur, with an infinite number of different solutions, almost all of which are completely irrelevant to this _Issue_, because more often than not, it is caused by conflicts with 3rd party code, which requires special diagnosis for a specific site using sensitive data like login details to your site, system status reports etc. That's why we ask folks to contact support.

**Comment by rvpatel** [comment]
@jarmosiim  
I have fixed issue in WooCommerce - 2.6.4 for ipn traking issue using v2.2.7 code review. I have changed data format which one stored for ipn record & payment records.  Also added manually in database with parent relation.

**Comment by kennedyluke** [comment]
@thenbrent fair point.
