### ISSUE TITLE
I got error from error log after upgrading to version 3.0

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#13920]
I got those error from error log:

> #0 /home/domain/public_html/wp-includes/functions.php(3638): WP_List_Util->pluck('slug', NULL)
#1 /home/domain/public_html/wp-content/plugins/woocommerce/includes/wc-term-functions.php(33): wp_list_pluck(Object(WP_Error), 'slug', NULL)
#2 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(104): wc_get_object_terms(2796, 'color', 'slug')
#3 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(34): WC_Product_Variable_Data_Store_CPT->read_variation_attributes(Object(WC_Product_Variable))
#4 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php(154): WC_Product_Variable_Data_Store_CPT->read_product_data(Object(WC_Product_Variable))
#5 /home/domain/public_html/wp-content/plugins/w" while reading response header from upstream, client: 158.69.64.178, server: domain.com, request: "GET /shop/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "domain.com", referrer: ""
2017/04/04 20:55:04 [error] 26823#0: *767471 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /home/domain/public_html/wp-includes/class-wp-list-util.php:157
Stack trace:
#0 /home/domain/public_html/wp-includes/functions.php(3638): WP_List_Util->pluck('slug', NULL)
#1 /home/domain/public_html/wp-content/plugins/woocommerce/includes/wc-term-functions.php(33): wp_list_pluck(Object(WP_Error), 'slug', NULL)
#2 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(104): wc_get_object_terms(2796, 'color', 'slug')
#3 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(34): WC_Product_Variable_Data_Store_CPT->read_variation_attributes(Object(WC_Product_Variable))
#4 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php(154): WC_Product_Variable_Data_Store_CPT->read_product_data(Object(WC_Product_Variable))
#5 /home/domain/public_html/wp-content/plugins/w" while reading response header from upstream, client: 158.69.64.178, server: domain.com, request: "GET /shop// HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "domain.com", referrer: ""
2017/04/04 20:55:15 [error] 26823#0: *767489 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /home/domain/public_html/wp-includes/class-wp-list-util.php:157
Stack trace:
#0 /home/domain/public_html/wp-includes/functions.php(3638): WP_List_Util->pluck('slug', NULL)
#1 /home/domain/public_html/wp-content/plugins/woocommerce/includes/wc-term-functions.php(33): wp_list_pluck(Object(WP_Error), 'slug', NULL)
#2 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(104): wc_get_object_terms(2796, 'color', 'slug')
#3 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(34): WC_Product_Variable_Data_Store_CPT->read_variation_attributes(Object(WC_Product_Variable))
#4 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php(154): WC_Product_Variable_Data_Store_CPT->read_product_data(Object(WC_Product_Variable))
#5 /home/domain/public_html/wp-content/plugins/w" while reading response header from upstream, client: 158.69.64.178, server: domain.com, request: "GET /shop/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "domain.com", referrer: ""
2017/04/04 20:55:24 [error] 26823#0: *767506 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /home/domain/public_html/wp-includes/class-wp-list-util.php:157
Stack trace:
#0 /home/domain/public_html/wp-includes/functions.php(3638): WP_List_Util->pluck('slug', NULL)
#1 /home/domain/public_html/wp-content/plugins/woocommerce/includes/wc-term-functions.php(33): wp_list_pluck(Object(WP_Error), 'slug', NULL)
#2 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(104): wc_get_object_terms(2796, 'color', 'slug')
#3 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(34): WC_Product_Variable_Data_Store_CPT->read_variation_attributes(Object(WC_Product_Variable))
#4 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php(154): WC_Product_Variable_Data_Store_CPT->read_product_data(Object(WC_Product_Variable))
#5 /home/domain/public_html/wp-content/plugins/w" while reading response header from upstream, client: 158.69.64.178, server: domain.com, request: "GET /shop/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "domain.com", referrer: ""
2017/04/04 20:55:33 [error] 26823#0: *767518 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /home/domain/public_html/wp-includes/class-wp-list-util.php:157
Stack trace:
#0 /home/domain/public_html/wp-includes/functions.php(3638): WP_List_Util->pluck('slug', NULL)
#1 /home/domain/public_html/wp-content/plugins/woocommerce/includes/wc-term-functions.php(33): wp_list_pluck(Object(WP_Error), 'slug', NULL)
#2 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(104): wc_get_object_terms(2796, 'color', 'slug')
#3 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-variable-data-store-cpt.php(34): WC_Product_Variable_Data_Store_CPT->read_variation_attributes(Object(WC_Product_Variable))
#4 /home/domain/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php(154): WC_Product_Variable_Data_Store_CPT->read_product_data(Object(WC_Product_Variable))
#5 /home/domain/public_html/wp-content/plugins/w" while reading response header from upstream, client: 158.69.64.178, server: domain.com, request: "GET /shop// HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "domain.com",

**Comment by mikejolley** [comment]
Looks like a plugin may be trying to load terms for a taxonomy which does not exist ('color').

Will add a workaround to the function to protect against this.
