### ISSUE TITLE
Products photo

### ISSUE THREAD

**Issue by and1me2i3** [woocommerce/woocommerce#13925]
the photos are not in grid and the lightbox is not available
https://www.grabprinting.com/product/envelope-printing/
![screen shot 2017-04-05 at 4 23 57 pm](https://cloud.githubusercontent.com/assets/26921116/24696601/97247f46-1a1c-11e7-8794-6ae3cc67a5a8.png)

**Comment by faisal-alvi** [comment]
have you checked your browser's console? 

Here is what I have seen:

![image](https://cloud.githubusercontent.com/assets/25176325/24697485/fe5485ec-1a0a-11e7-939d-8f4346b95fdb.png)

**Comment by mikejolley** [comment]
The new gallery has to be enabled with https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox)-in-3.0.0 If this is a WooCommerce theme, get an update with support from the author.
