### ISSUE TITLE
Variable products 'sold individually' setting is no longer working

### ISSUE THREAD

**Issue by sortit-luke** [woocommerce/woocommerce#13933]
### EXPLANATION OF THE ISSUE

Variable products can no longer be sold individually via the inventory setting tab. 
I had this happen on a live site with plenty of plugins, so to test it I created a new site running WordPress 4.7.3 & WooCommerce 3.0.0 with no other plugins and the WordPress Twenty Fifteen theme.

### STEPS TO REPRODUCE THE ISSUE

1. Create a new variation product 
2. Check the '**Sold individually**' checkbox
3. Set up a test attribute
4. Set the variations up with prices
5. View the front end and you can see that you can add more than 1 product.

I also tested a simple product which did work when I checked the sold individually checkbox. 

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: --devsiteurl--
Site URL: --devsiteurl--
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.22
PHP Post Max Size: 100 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.41.0
OpenSSL/1.0.2a

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Fifteen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikeyarce** [comment]
I tested this out and get the same result - I'm able to add multiple variable products when "Sold Individually" is checked.

**Comment by zudofeathers** [comment]
This problem is not fixed yet. I still have this issue and other people aswell.
