### ISSUE TITLE
Important problem ! WooCommerce 3.0

### ISSUE THREAD

**Issue by webdepotet** [woocommerce/woocommerce#13932]
Hi woocommerce.
We found serious problem.

After updating to 3.0 and visited the backend - the orderview page had a other feature so we could quickview what each order contained..

Like, 2items and when clicked, it showed SKU or name of it...
This feature is now gone - and now taking many many many hours to see what each order has, because we have to go inside each order, and go back and inside the next one, and go back...

Is this problem or is it a new "not good" improvement??

We have multistore network setup

**Comment by mikejolley** [comment]
See Performance improvements section in https://woocommerce.wordpress.com/2017/04/04/say-hello-to-woocommerce-3-0-bionic-butterfly/

**Comment by webdepotet** [comment]
Ok - thank you.
But how do we get it back through functions. This feature almost killing our business by hours.
Lets say we got 100 orders in progress - and now i would like to check each order what it contains - now i have to go under each order 100 times instead of Quick View of it.

Like this one has 6pc but i know we only have 1pc in stock, so i have to check eeeeeeevery order to find this 1pc order.

Is anyway to get it back manually?


#We’ve removed the ‘order items’ column on the orders page. Whilst this can be useful, loading all items for all orders on the page is not performant. This may return in the future but it will need to be dynamic so it may just be left for a future UI redesign."

**Comment by mikejolley** [comment]
I believe someone started an ideas on ideas.woocommerce.com to get it back - if it gets traction we'd have to add a dynamic replacement. In it's current form it cannot be added back however -it's simply too slow. It's still also possible to add columns with custom code.
