### ISSUE TITLE
String with data in the mails after upgradingto WooCommerce 3.0

### ISSUE THREAD

**Issue by carazo** [woocommerce/woocommerce#13930]
Good morning,

After updating to WooCommerce 3.0 all "New order" emails comes with a string with data after the table and before the addresses.

Something like it:
_{"@context":"http:\/\/schema.org\/","@type":"Order","url":"https:\/\/codection.com\/wp-admin\/post.php?post=5546&action=edit","orderStatus":"","orderNumber":"5546","orderDate":"2017-04-05T09:13:33+00:00","acceptedOffer":_

I have no hooks in my system which can do it.

I am going to have a look in the code to see where can be the source of the problem.

**Comment by carazo** [comment]
Ok, this is structured data in JSON-LD format.

I am trying to see why it is visible in the middle of the HTML content of the email.

**Comment by mikejolley** [comment]
Is it a particular client/service?

**Comment by carazo** [comment]
Ok I have seen:

In class-wc-structured-data.php:
// Output structured data.
add_action( 'woocommerce_email_order_details', array( $this, 'output_email_structured_data' ), 30, 3 );

I have to remove this action to avoid it appearing in all emails.

Most of mail clients shows it and it should not be there I think.

**Comment by carazo** [comment]
@mikejolley 

This is correct if it would be started with:
<script type="application/ld+json">

But most of mail services detect it as suspicius and change it to:
<MailScannerScript686126 script type="application/ld+json">

I am seeing how to avoid it without removing the structured data.

**Comment by carazo** [comment]
I have created an issue in MailScanner https://github.com/MailScanner/v5/issues/46

Anyway, I had to deactivate it using remove_action on my shop (and in every shop of every client who told me the client):

add_action( 'wp', 'cod_remove_hook_woocommerce', 9999);
function cod_remove_hook_woocommerce() {
    remove_filters_with_method_name( 'woocommerce_email_order_details', 'output_email_structured_data', 30 );
}

As the hook is inside a non-static class I had to use it https://github.com/herewithme/wp-filters-extras.

It would be a good idea if we could deactivate it from the admin.

Surely most of mail services will do something like it.

**Comment by claudiosanches** [comment]
@mikejolley we could disable by default schema in emails.

**Comment by carazo** [comment]
I have asked to fix it in MailScanner and it seems they are managing it.

**Comment by robfaas** [comment]
I am experiencing the same problem after updating to Woocommerce 3.0!

**Comment by praveen-c** [comment]
@carazo 

Hi I tried to add the remove_action you have provided in my functions.php and it crashed the site sir. Here is the exact code I have added

`add_action( 'wp', 'cod_remove_hook_woocommerce', 9999);
function cod_remove_hook_woocommerce() {
remove_filters_with_method_name( 'woocommerce_email_order_details', 'output_email_structured_data', 30 );
}`

What am I doing wrong. Thanks

**Comment by carazo** [comment]
@praveen-c 

Have you added it?

https://github.com/herewithme/wp-filters-extras/blob/master/wp-filters-extras.php

**Comment by mikejolley** [comment]
@claudiosanches rather than disabling, we could just hide it so if the tag is changed it won't be visible. It's unlikely folks will *know* about this functionality in google to even know to enable it. I'll put in an alternative PR for you to review.
