### ISSUE TITLE
Add filter to woocommerce_products_will_display() to allow manual control

### ISSUE THREAD

**Issue by leeroyrose** [woocommerce/woocommerce#13944]
woocommerce_products_will_display() does not give the developer the ability to manually decide if it will return true or false. 

The use case I have for it, is whilst building a custom plugin that brings high performance facet filtering to woocommerce, using elastic search, I can't get the sort by options to show on the search results page.

A filter here would be perfect!

**Comment by mikejolley** [comment]
Could consider it. Please submit a PR. However please note, if your queries are independent and WC cannot see them, it's probably not going to work with things like layered nav too. You may want to look into that first.

Thanks
