### ISSUE TITLE
Are Template Version Numbers Wrong?

### ISSUE THREAD

**Issue by wesdekoninck** [woocommerce/woocommerce#13942]
I updated to WC v3.0.0 this morning and in doing my usual walk through of my themes after a major update to WC, I noticed that the System Status > Templates area was stating that there were templates in the theme that are out of date, but when checking the versions of the templates in the new v3.0.0 update, the version numbers are the same...

**For example in my theme:**
Woocommerce > archive-product.php is version 2.0.0

**and in the v3.0.0 templates both in the plugin templates folder and on Github (https://github.com/woocommerce/woocommerce/tree/master/templates):**
Templates > archive-product.php is version 2.0.0

Here are the other templates that I am overridding that are displaying as out of date in the template overrides in System Status (custom theme name has been replaced with "themename"):

```
themename/woocommerce/archive-product.php, 
themename/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.0, 
themename/woocommerce/checkout/form-checkout.php, 
themename/woocommerce/checkout/form-pay.php, 
themename/woocommerce/checkout/payment.php, 
themename/woocommerce/global/wrapper-end.php, 
themename/woocommerce/global/wrapper-start.php, 
themename/woocommerce/loop/orderby.php, 
themename/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0, 
themename/woocommerce/single-product.php
```

It looks like modifications were made to some of the template files, but the version number listed at the top is the same as the version in my template.

Am I missing something?

**Comment by danyj** [comment]
> archive-product.php is version 2.0.0

that file version  not Woo version . 
Means that the file was not changed since it was 2.0.0  ,  

if there were changes in  3.0.0  than the file would get the 3.0.0

**Comment by danyj** [comment]
>  single-product/meta.php version 1.6.4 

was last changed when Woo was 1.6.4  , and now , so it gets  3.0.0
