### ISSUE TITLE
Variation attributes on old orders and mini cart

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13943]
See https://wordpress.org/support/topic/on-3-0-the-order-detail-doesnt-show-the-attributes/

**Comment by BurlesonBrad** [comment]
Unless there term `mini-cart` that the person is referring to, is _"something else"_, I've tested `variations` in both the sidebar cart widget and in the header cart as well. 👍 label=good-to-go

![variations-in-sidebar-cart-widget](https://cloud.githubusercontent.com/assets/6208757/24722609/fdd47164-1a09-11e7-8b47-fc5706ef23be.png)
![variations-header-cart](https://cloud.githubusercontent.com/assets/6208757/24722667/3423b70c-1a0a-11e7-8eb6-40d0f2d9a1cd.png)

**Comment by claudiulodro** [comment]
It works great in carts and new orders as far as I can tell. It just needed a small tweak for old orders.
