### ISSUE TITLE
the_widget('WC_Widget_Products') template tag show same result if passed different parameters

### ISSUE THREAD

**Issue by AmirRafiee** [woocommerce/woocommerce#13940]
### EXPLANATION OF THE ISSUE
wordpress version = 4.7.3
woocommerce version = 2.6.14
i was trying to get featured products and onsale product in my index page

the_widget( 'WC_Widget_Products',
    array(
        'title' => __( 'On Sale Products', 'woocommerce' ),
        'number' => 5
        'show' => 'onsale'
    ), 
	array()
);

the_widget( 'WC_Widget_Products',
    array(
        'title' => __( 'Fetured Products', 'woocommerce' ),
        'number' => 5,
        'show' => 'featured'
    ), 
	array()
);

but both of the widgets are displaying the onsale products i mean the first parameters only affect the_widget .

**Comment by mikejolley** [comment]
Pass a unique 'widget_id' to each or it will cache the first and show the same for the second.

**Comment by groucho75** [comment]
I solved using `wp_reset_query()` between the two functions.
