### ISSUE TITLE
Sort countries correctly when translated 

### ISSUE THREAD

**Issue by martinsnajdr** [woocommerce/woocommerce#13950]
### EXPLANATION OF THE ISSUE

The countries are not sorted properly when translated in some languages. English has no accented characters, but in my native language (czech), there are some extra characters like Č, Ř, Š etc. The countries that start with accented characters (Czech republic – Česká republika, Spain – Španělsko etc.) are placed after the countries that start with Z, which is wrong and quite confusing. 

Current sorting: A, B, C, D, E...X, Y, Z, Č, Š
It should be: A, B, C, Č, D, E...S, Š,...X, Y, Z, Ž...

I think this is a problem of all languages that have accented letters in country names.

### STEPS TO REPRODUCE THE ISSUE

Just download czech translation and switch to cs_CZ language.

### WordPress Environment ###

Home URL: http://wordpress.czech
Site URL: http://wordpress.czech
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: cs_CZ

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) PHP/7.1.0
PHP Version: 7.1.0
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.50.3
SecureTransport

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce PayPal Express Checkout Gateway: o Automattic – 1.1.2
WooCommerce: o Automattic – 3.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CZK (Kč)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

**Comment by claudiosanches** [comment]
It's sorted by PHP `asort()`.

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-countries.php#L39-L51

Can you try something to me?

Change

```php
asort( $this->countries );
```

To

```php
asort( $this->countries, SORT_LOCALE_STRING );
```

This should be consider your locale while sorting.
http://php.net/manual/en/function.sort.php#refsect1-function.sort-parameters

**Comment by martinsnajdr** [comment]
@claudiosanches 

I've tried your code, but the result was the same. I have also tried setlocale before the asort function, but it didn't help. However after using collator class the sorting seems to be partially working. The countries are sorted correctly on the checkout page and in single-select-boxes (in admin), but in multi-select-boxes the countries remain sorted incorrectly.

```
$collator = new Collator( get_locale() );
$collator->asort( $this->countries );
```

**Comment by claudiosanches** [comment]
@marcinbot Collator isn't a good option, since don't works in PHP 5.2, but maybe could be an working around.

**Comment by martinsnajdr** [comment]
@claudiosanches Well, I thought that PHP 5.6 or greater is a requirement for WooCommerce...

**Comment by claudiosanches** [comment]
@martinsnajdr "recommended" isn't the same of "required". We need to keep support for PHP 5.2.

**Comment by martinsnajdr** [comment]
@claudiosanches I was playing a lot with SORT_LOCALE_STRING before (in other plugin), but I actually have never got it working. So I hope we will find a solution.

**Comment by UserName011** [comment]
@martinsnajdr One solution is to save the countries list in the database instead of in the PHP files and then you can sorth within the SQL query.

**Comment by claudiosanches** [comment]
@UserName011 no so good idea when you still need to have the site available in 20 different languages, and not to mention that it's possible sort it by PHP, no need for SQL, but thanks for your input.

**Comment by claudiosanches** [comment]
@martinsnajdr I tested everything and the only solution is with `Collator` part of the PHP Internationalization Functions from PHP 5.3+, some cases this is not even installed by default on PHP, so better move this into a plugin.

I just created a plugin for it and I'll submit soon to wp.org to help more people: https://github.com/claudiosanches/wc-properly-sort-countries

Not so easy as have it by default on WooCommerce, but until we update our PHP requirement this should be the solution.

cc @mikejolley

**Comment by martinsnajdr** [comment]
@claudiosanches Thank you! As a WooCommerce czech translation editor I will suggest this plugin as a solution.
