### ISSUE TITLE
Checkout div wrappers are smaller than their contents.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#13957]
Originally reported [here](https://wordpress.org/support/topic/woocommerce-3-billing-field-issue/). 

The `.woocommerce-billing-fields` and `.woocommerce-shipping-fields` divs on the checkout page are smaller than their contents in Australian shops, which causes background-colors on those elements to look bad. See screenshot in original ticket.

**Comment by krbvroc1** [comment]
I am seeing the same issue (with twentysixteen). I don't use a background so it is not obvious, but I verified under firebug.
