### ISSUE TITLE
WC 3.0 Checkout field layout issue

### ISSUE THREAD

**Issue by krbvroc1** [woocommerce/woocommerce#13953]
I have code which reorders some checkout fields using the `woocommerce_checkout_fields` filter and it is not styling the same with 3.0. In particular the fields where I had set 'clear' to 'true' is not working. I see no 'clear' div in the html output under 3.0.

**Comment by krbvroc1** [comment]
Even with no modifications via a filter, the class-wc-countries.php sets several fields as `'clear' => 'true'`, but there is no clear div in the browser output. (ie; billing_last_name, billing_postcode, billing_email)

**Comment by claudiosanches** [comment]
3.0 do not use any `clear` now, and allow you to reorders the fields using the `priority` parameter.

**Comment by claudiosanches** [comment]
Removing the legacy `'clear' => 'true'` here https://github.com/woocommerce/woocommerce/pull/13958

**Comment by krbvroc1** [comment]
But I don't want to simply reorder the field, for example I put state and postcode on the same line. And compressed a few other fields. All required the use of the clear. Is it documented somewhere how to accomplish this? Is it smart enough that if I use the filter change a `form-row-wide` to `form-row-first` and `form-row-last` it will put them on the same line?

**Comment by krbvroc1** [comment]
@claudiosanches Here is what existing page looks like:
![selection_008](https://cloud.githubusercontent.com/assets/1335118/24712012/aa4cc844-19ef-11e7-9a5f-33ce42c2a769.png)

**Comment by krbvroc1** [comment]
It also appears that template file form-billing.php was modified and the version was not updated, nor is it listed as changed on the 2.6 to 3.x Template changes.

I tried changing the priority and it does not 'reorder' the fields. You sure what is not simply for the order of tabbing between fields? Order appears to be still dictated by the order in the array.

**Comment by mikejolley** [comment]
The priority based sorting is done by javascript FYI

**Comment by krbvroc1** [comment]
@mikejolley Odd, so as a test when I swapped the priority of the first and last name nothing changed on the page render. I had to reorder the array for the field order to actually change. With the lack of the 'clear', it is not possible to duplicate my current site page. The closest I could get is below - but the woocommerce form fields do line line up properly.

 For example the State and Zip does not line up properly. And it trickles down to the email and email verify fields. 

**I think the select2 fields are the issue - they are not the same height as other fields. They need to be taller.**

Maybe you didn't notice it during testing since the default page always uses them as form-row-wide and never as form-row-first or last like I am doing.?

![selection_009](https://cloud.githubusercontent.com/assets/1335118/24718883/ad72756c-1a05-11e7-8f33-e8ac1be48572.png)

**Comment by krbvroc1** [comment]
> I think the select2 fields are the issue - they are not the same height as other fields. They need to be taller.

NOTE: I am not a CSS expert, but it seems the select2-container vertical-align:middle is part of the problem with the alignment. Since the select2 is not tall enough, if I remove that/change it to vertical-align:baseline, everything lines up properly.

**Comment by mikejolley** [comment]
cc @jameskoster

**Comment by jameskoster** [comment]
It's not worth us styling the select2 components to be a specific height beyond the default styles. While that may improve the appearance in some themes, it's not a catch-all solution.

This is something you should be adding to your own customisations imo.

**Comment by krbvroc1** [comment]
@jameskoster Forget I said they need to be taller or a specific height, but don't you think if you simply  place a woocommerce field with a select2 side-by-side with another woocommerce field should at least align properly?

I ended up adding:
```
/* WC 3 fix */
.woocommerce-page .checkout .select2-container {
    vertical-align: baseline !important;
}
``` 
but I am thinking there might be some sort of underlying issue here that is not theme related. Some sort of underflow or something.
