### ISSUE TITLE
WooSwatches plugin stop working with Woocommerce 3.0.0 update

### ISSUE THREAD

**Issue by VerifiedLabel** [woocommerce/woocommerce#13951]
### EXPLANATION OF THE ISSUE

WooSwatches plugin stop working with Woocommerce 3.0.0 update

### STEPS TO REPRODUCE THE ISSUE

WooSwatches plugin stop working with Woocommerce 3.0.0 update.. .After updating woocommerce to 3.0.0.  The WooSwatches (Woocommerce Color or Image Variation Swatches) stop working... only displays the dropdown option and not the images or colors.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikeyarce** [comment]
Hi @VerifiedLabel - this is not an issue with WooCommerce.  It sounds like you are using a third party plugin so my suggestion would be to contact them to make sure their plugin is compatible with WooCommerce 3.0
