### ISSUE TITLE
Bug in DB Log Viewer - Incorrect CSS for log level badges on non-english websites

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#13954]
If you're not using English as your wp-admin language, the DB Log Viewer table may not have the "logs" class and the CSS declarations for each log level badges are incorrect.

Example: In Portuguese the table has "registos" as a class, and not "logs":
![image](https://cloud.githubusercontent.com/assets/6853605/24710339/bfc6c650-1a14-11e7-8f32-8611f9e338d8.png)

Which results on the badges not having the proper styling:
![image](https://cloud.githubusercontent.com/assets/6853605/24710360/ced2e14c-1a14-11e7-904d-c2576cb5c540.png)

Like they do in English:
![image](https://cloud.githubusercontent.com/assets/6853605/24710367/d7f8c318-1a14-11e7-9586-9e17ceba1adc.png)

**Comment by claudiosanches** [comment]
I just tested in pt_BR and works fine:

![screenshot from 2017-04-05 17-14-12](https://cloud.githubusercontent.com/assets/1264099/24724922/53c6330a-1a23-11e7-9f87-4754b4cda0e2.png)

Maybe browser cache?

**Comment by webdados** [comment]
The pt_BR version hasn't translated the word "Logs".
That's the only reason it works.

**Comment by claudiosanches** [comment]
@webdados ohh yeah, we are using `WP_List_Table` wrong. Thanks for report.

**Comment by webdados** [comment]
@claudiosanches you're welcome
