### ISSUE TITLE
[3.0] woocommerce_related_products_args Filter removed what should we use.

### ISSUE THREAD

**Issue by wpdev321** [woocommerce/woocommerce#13962]
@mikejolley , @claudiosanches ,

I see that in 3.0 version woocommerce_related_products_args filter removed so now what other filter is available to set the related product arguments.

Thanks

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by justinshreve** [comment]
`wc_get_related_products` in `wc-product-functions.php` is used by the template and shortcode and contains a few filters. The product data store method `get_related_products` also contains a filter: `woocommerce_product_related_posts_query`.

**Comment by wpdev321** [comment]
@justinshreve,

Is there any filter available to display other products as related product  ?

Thanks

**Comment by nokemono42** [comment]
I wanted to hide/remove related products, which broke in 3.0.

This:
```
function wc_remove_related_products( $args ) {
	return array();
}
add_filter('woocommerce_related_products_args','wc_remove_related_products', 10);
```

Becomes this:
```
function wc_remove_related_products( $args ) {
	return array();
}
add_filter('woocommerce_product_related_posts_query','wc_remove_related_products', 10);
```

The old how-to post, https://docs.woocommerce.com/document/remove-related-posts-output/, was taken down, but this working for me.

**Comment by corsonr** [comment]
you can simply add this to `functions.php`:

```
/**
  * Remove related product in WC 3+
  */
function woocommerce_related_products() {
	return null;
}
```
