### ISSUE TITLE
So many MySQL queries that slow down server WooCommerce 3.0

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#13969]
I upgraded my WooCommerce to 3.0 and noticed that there are so many queries whenever WP-rocket starts crawling. My site has about 25k variant products. That never happened before.

![screen shot 2017-04-05 at 2 35 20 pm](https://cloud.githubusercontent.com/assets/2909982/24721365/242e0e48-1a0e-11e7-914f-0481d54facac.png)

**Comment by kevin25** [comment]
This is when i update some variants' images. 
![screen shot 2017-04-05 at 2 50 10 pm](https://cloud.githubusercontent.com/assets/2909982/24721752/456a0e1c-1a0f-11e7-9458-0e3050708458.png)

![screen shot 2017-04-05 at 2 50 00 pm](https://cloud.githubusercontent.com/assets/2909982/24721740/3b64dda2-1a0f-11e7-97eb-ff0ddf35d131.png)

**Comment by mikejolley** [comment]
These are just random queries from all requests? Some are from frontend. Some are from WP (priming caches). I cannot work with that. 

Use query monitor https://en-gb.wordpress.org/plugins/query-monitor/ This will identify slow queries when you view a page and help debug.

**Comment by kevin25** [comment]
I really don't know but this happened on WooCommerce 3.0 with large sites. This happened after i upgraded it to WooCommerce 3.0. Please investigate it.
