### ISSUE TITLE
Up sells template does not have the 3.0 version 

### ISSUE THREAD

**Issue by themedotal** [woocommerce/woocommerce#13965]
### EXPLANATION OF THE ISSUE
Up Sells template
single-product/up-sells.php 

does not have the correct version 3.0.0, there are changes in the file of course matching the new version 3.0 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by claudiulodro** [comment]
Good catch. This [was just merged](https://github.com/woocommerce/woocommerce/commit/f7b41ec4686e5e9e179cb105633e6360a284c32c) and will be fixed soon.
