### ISSUE TITLE
Payment gateways are not able to add information to transactional emails

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#13966]
In a clean WordPress + WooCoomerce 3.0 + Storefront install (all latest versions) it seems that payment gateways are not being initialized when the transactional emails are actually being sent (on the cron).

It's easy to test it with WooCommerce own BACS payment gateway, which should add the bank information using the 'woocommerce_email_before_order_table' action to the new order email.

I've added this simple code to Storefront functions.php file and this paragraph is successfully added to the email.
`add_action( 'woocommerce_email_before_order_table', 'test_email_instructions', 10, 2) ;
function test_email_instructions($order, $sent_to_admin) {
	?>
	<p>test</p>
	<?php
}`
The BACS payment instruction, which use the exact same action, are not.

We can see the bank details on the Thank You page:
![image](https://cloud.githubusercontent.com/assets/6853605/24719011/0c1f25fe-1a30-11e7-9770-79baa5b6d757.png)

But not on the email:
![image](https://cloud.githubusercontent.com/assets/6853605/24719647/6eb7ebf4-1a32-11e7-94e8-803e4d93d476.png)

This seems to be something similar to #10461 that was fixed on 7dadae7bc80a842e10e78a972334937ed5c4416a

**Comment by webdados** [comment]
UPDATE: For testing purposes I've added this to send_queued_transactional_email:
`public static function send_queued_transactional_email( $filter = '', $args = array() ) {
		if ( apply_filters( 'woocommerce_allow_send_queued_transactional_email', true, $filter, $args ) ) {
			self::instance(); // Init self so emails exist.
			// Ensure gateways are loaded in case they need to insert data into the emails
			WC()->payment_gateways();
			WC()->shipping();
			do_action_ref_array( $filter . '_notification', $args );
		}
	}`

And the information is now correctly added to the transactional emails:
![image](https://cloud.githubusercontent.com/assets/6853605/24719628/570befdc-1a32-11e7-80f0-a6452922c8bf.png)

**Comment by claudiosanches** [comment]
Confirmed.

**Comment by webdados** [comment]
@claudiosanches you're welcome.

**Comment by webdados** [comment]
If someone needs a quick fix while 3.0.1 is not released, here it is:
https://gist.github.com/webdados/527e849579adf5707d3a8cdb8af1c4c5

**Comment by kevin25** [comment]
@webdados  Which file should be patched?

**Comment by webdados** [comment]
@kevin25 What I shared on a gist link should be inserted, for example, on your child theme functions.php file. It checks the WooCommerce version and is only activated for 3.0.
You should not patch a WooCommerce file.
According to @claudiosanches this will be fixed on 3.0.1.
