### ISSUE TITLE
Variable prices - There is no strike through when all variations are on sale and identical

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13968]
When all variations have the same regular and sale prices, the top price has no strike through, and the variation prices are not displayed.

This might be larger to tackle and may need to wait for 3.1. @franticpsyx

**Comment by franticpsyx** [comment]
@mikejolley got an example? Would love to have a look but can't decipher the problem description :)

**Comment by mikejolley** [comment]
Sorry I've been awake too long :) Updated.
