### ISSUE TITLE
[3.0] Saving product meta on `save_post` no longer works

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#13960]
Extensions that save product meta on `save_post` (priority > 1), such as Bookings and Subscriptions are failing to update their meta when `WC_Data::maybe_read_meta_data` is called on the `woocommerce_admin_process_product_object` action by another plugin/extension.

It's not yet entirely clear to me why, but this is causing conflicts with all extensions that have been updated for 3.0 and save their meta on `woocommerce_admin_process_product_object` using the `WC_Data` methods.

Might be worth giving some attention to this as it looks serious. @thenbrent @mikejolley @claudiulodro

**Comment by justinshreve** [comment]
@franticpsyx What steps did you take to trigger this the conflict/issue? Or is there an extension you would recommend trying out with Bookings or Subscriptions to trigger? I'm trying to investigate this but so far don't seem to see a reason.

**Comment by franticpsyx** [comment]
Hey @justinshreve - try a small/simple one like Name Your Price or Conditional Shipping and Payments with Subs.

**Comment by helgatheviking** [comment]
Name Your Price apparently falls into the conflict category. 
https://github.com/woocommerce/woocommerce-name-your-price/issues/33

I'm still recovering from handball competition and getting home rather late, so haven't had a chance to dig into it myself.

**Comment by justinshreve** [comment]
Thanks, reproduced. I will see what I can figure out.

**Comment by justinshreve** [comment]
I think I found the issue and a fix. Confirming and writing a test :).
