### ISSUE TITLE
3 WooC 3.0 Bugs

### ISSUE THREAD

**Issue by bryandotlloyd** [woocommerce/woocommerce#13979]
### EXPLANATION OF THE ISSUE

We have updated to the 3.0 WooCommerce plugin from 2.x, I'm seeing 3 big issues:

1- Order Notes are not "saving" or being added to the Order
![2017-04-05 11 54 27 am](https://cloud.githubusercontent.com/assets/8723728/24723693/1bd76ca8-1a0e-11e7-93b2-dc9a62955e06.png)

2- Dropdown boxes are bot displaying properly. They are missing the background color and border. This is noticeable in the Bookings Plugin Calendar, CSV Export plugin & other WooC dropdown fields.
![2017-04-05 02 30 22 pm](https://cloud.githubusercontent.com/assets/8723728/24723863/b260f18a-1a0e-11e7-86de-18ce9d0aac98.png)

3- The Booking Product Resources show on the calendar that the whole day is unavailable/fully booked, but the Calendar View in the admin section shows open times are available. I don't believe this is a transient/cancelled order issue.
![2017-04-05 11 55 11 am](https://cloud.githubusercontent.com/assets/8723728/24724103/8dfcbc42-1a0f-11e7-9ee6-a93bb512543e.png)

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://broheimsgolf.com
Site URL: https://broheimsgolf.com
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Flywheel/4.1.0
PHP Version: 5.6.30-7+deb.sury.org~xenial+1
PHP Post Max Size: 300 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_m70mxrvtn7_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (27) ###

Gravity Forms: by rocketgenius – 2.2.1
AddToAny Share Buttons: by AddToAny – 1.7.8
Advanced Custom Fields: Font Awesome: by Matt Keys – 1.7.3
Advanced Custom Fields PRO: by Elliot Condon – 5.5.11
The SEO Framework: by Sybre Waaijer – 2.9.1
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

Column Shortcodes: by Codepress – 0.6.9
Enable Media Replace: by Måns Jonasson – 3.0.6
Gravity Forms: Add Class To Submit Button: by poweredbycoffee – 1.0
Gravity Forms Coupons Add-On: by rocketgenius – 2.5
Gravity Forms MailChimp Add-On: by rocketgenius – 4.1
Manage Notification E-mails: by Virgial Berveling – 1.3.0
Mouseflow 4.2: by Mouseflow – 4.2
SeedProd Coming Soon Pro: by SeedProd – 4.5.7
SVG Support: by Benbodhi – 2.3.7
The SEO Framework - Title Fix: by Sybre Waaijer – 1.0.3
WC Fields Factory: by Saravana Kumar K – 1.3.8
WooCommerce Bookings: by Automattic – 1.10.0
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.2.1
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce SecureSubmit Gateway: by SecureSubmit – 1.11.2
WooCommerce: by Automattic – 3.0.0
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Notification Bar: by SeedProd – 1.3.8
WP Crontrol: by John Blackbourn & contributors – 1.5
WP Help: by Mark Jaquith – 1.5.1
WP Master Admin: by WPMasterAdmin.com – 2.4.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #45 - /cart/
Checkout: #46 - /checkout/
My account: #47 - /my-account/

### Theme ###

Name: Broheims Golf & Pub
Version: 1.7
Author URL: http://www.farmboyinc.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: default
Automatically Export Orders: local
Export Trigger: schedule
Export Start Time: 12:00am
Export Interval: 60
Next Export: Scheduled on April 5
2017 3:00 pm

Order Statuses: 
Product Categories: 
Products: 
Automatically Export Customers: disabled
`
</details>

**Comment by claudiosanches** [comment]
![screenshot from 2017-04-05 17-20-09](https://cloud.githubusercontent.com/assets/1264099/24725167/251da780-1a24-11e7-9d1c-661fa4e6d685.png)

Notes working just fine.

For the other issues contact the WooCommerce.com support since are issues from WooCommerce Bookings: https://woocommerce.com/my-account/create-a-ticket/
But make sure that testing with the last version of WooCommerce Bookings.
