### ISSUE TITLE
Out of Stock, Wont Restock

### ISSUE THREAD

**Issue by AntBentinck** [woocommerce/woocommerce#13978]
### EXPLANATION OF THE ISSUE

Permanently Out Of Stock!  

Latest Version of Wordpress & WooCommerce. 

Products with with variations that are all in stock are showing as out of stock on the front end and in the back end. We had a similar issue when our stock control system **Veeqo** put product variants back in stock the item would remain out of stock on the back end and front end. 

Our Resolution to this was via "Quick Edit" > "In Stock?" > Selecting "In Stock".  The product would then go back into stock.

### STEPS TO REPRODUCE THE ISSUE

Not sure about this.

### SYSTEM STATUS

<details>
I would give you a system report but unfortunately we get a empty grey box and in the console a 500 errror

Failed to load resource: the server responded with a status of 500 ()

</details>

**Comment by BurlesonBrad** [comment]
@AntBentinck just like in this thread https://github.com/Yoast/wordpress-seo/issues/6942 this is not the place to receive support.

Working in the `admin` ❓ Yup 👍 


![f0284341e63d43c7be04b3b6c38e327c](https://cloud.githubusercontent.com/assets/6208757/24724986/d9f5d1d0-1a12-11e7-8489-56674627edc9.png)

Working on the front end as well ❓ Yup 👍 https://emojithreads.com/shop/emoji-shirts/poop-emoji-shirt/

GitHub is for reporting bugs, creating patches to bugs, compiling code, version control, merging code fixes to legitimate and verifiable bugs within the core of WooCommerce.

**Comment by claudiosanches** [comment]
Confirmed.

**Comment by AntBentinck** [comment]
I'm confused why @BurlesonBrad is saying I'm requesting support. I'm not I'm simply stating there is a issue with updating stock levels on products with multiple variants. @claudiosanches do you see what I am referring to?

**Comment by claudiosanches** [comment]
@AntBentinck yes, missing steps in your description but I was able to reproduce.

**Comment by claudiosanches** [comment]
Notes:

Until WooCommerce 2.6 variable product are changed to "Out of Stock" if all variations are out of stock too.
But starting WooCommerce 3.0 this don't happens any more, the variable products still display as "In Stock".

So if you update to 3.0 with a variable product out of stock becomes impossible to automatically update the status when restock all or at least one of the variations.

Until WooCommerce 2.6 when a variable product have all variations out of stock

- Need to be using WooCommerce 2.6

**Comment by claudiosanches** [comment]
@mikejolley @justinshreve not sure what should fix, should we always change the stock status like before or should create a migration script to fix all variations and prevent this problem while updating?

**Comment by BurlesonBrad** [comment]
> create a migration script to fix all variations and prevent this problem while updating
👍

**Comment by claudiosanches** [comment]
Looks like it's really a bug on the sync and not made by default xD

**Comment by AntBentinck** [comment]
Just updated our WooCommerce to 3.0.1 and still unable to get products to show as "in stock".

Marking them as in stock and re-saving does not rectify the issue.

**Comment by AntBentinck** [comment]
Infact doing a Bulk Edit > In Stock has actually marked all items as "out of stock".

**Comment by mikejolley** [comment]
@AntBentinck The sync issue needs to correct itself by saving a variation or the variable product. Bulk edit may not help because variable products don't have a UI for setting it manually.

**Comment by AntBentinck** [comment]
@mikejolley I understand but this still does not seem to correct the issue at the product level. I have gone into each variant of the product changed the stock level +1 and then saved the variations then saved the entire post. The parent product still shows out of stock.

**Comment by heints** [comment]
Heip,

We also have some hundreds of products, with in total 10 times more variations and suffer now from the same problem, that after sale of an Item, the whole item is set to out of stock! Is there any bulk way to fix it?

**Comment by mikejolley** [comment]
Screenshot me your variations.

**Comment by heints** [comment]
not sure if it helps, but here is some screenshots. Also as short explanation, it seems that we are able to override the problem, by setting stock quantity of a variable product to "1", and save. Then for some reason woo is treating the products correctly again.... So we are currently re-saving all products.

![variations](https://cloud.githubusercontent.com/assets/5124801/24807219/0eebc788-1bc0-11e7-9171-6b851c4df217.jpg)
![product main](https://cloud.githubusercontent.com/assets/5124801/24807224/1475d7c0-1bc0-11e7-8f3f-e2e862a64b40.jpg)
![product variations](https://cloud.githubusercontent.com/assets/5124801/24807229/179ca2da-1bc0-11e7-9afb-691431e19fe6.jpg)

**Comment by AntBentinck** [comment]
![screen shot 2017-04-07 at 16 57 40](https://cloud.githubusercontent.com/assets/13118094/24808384/5f424af2-1bb3-11e7-8036-2b6dfade2216.png)

**Comment by AntBentinck** [comment]
Unfortunately saving the variants is not working for us here.

![screen shot 2017-04-07 at 16 58 32](https://cloud.githubusercontent.com/assets/13118094/24808404/78848516-1bb3-11e7-81df-4c8538a5c641.png)

**Comment by AntBentinck** [comment]
Also confirmed that when a product is sold the product is put out of stock. We have over 3000 SKU's on site so as you can imagine this is a nightmare for us. Luckily we are just hiding the "Out of stock" label in categories for the time being but its not friendly for our customers.

**Comment by heints** [comment]
I think the main "stock QTY" is overriding the variable stock qty... If you set it to 1, then your able to sell variations again, but soon after 1 item is sold, from the ones in stock, its back to out od stock.

**Comment by heints** [comment]
how are you hiding it? CSS code?

**Comment by AntBentinck** [comment]
@heints **Confirmed**
> I think the main "stock QTY" is overriding the variable stock qty... If you set it to 1, then your able to sell variations again, but soon after 1 item is sold, from the ones in stock, its back to out of stock.

**Comment by AntBentinck** [comment]
@heints 

.out-of-stock-label {
    display: none!important;
}

**Comment by mikejolley** [comment]
Why are you opening quick edit here? the stock status is shown in the list. If you give access privately I can take a quick look but so far we're not seeing issues on test stores.

**Comment by AntBentinck** [comment]
Sent you a email.

**Comment by mikejolley** [comment]
@AntBentinck Ignore my last email Is see whats wrong.

![2017-04-07 at 18 07](https://cloud.githubusercontent.com/assets/90977/24811267/3a7c46dc-1bbd-11e7-9881-4e560dbac830.png)

I don't know if you did this, but it has stock set at variable level. This needs to be turned off - you want stock management at variation level.

As soon as thats unchecked and saved, the sync works and it's back in stock.

**Comment by AntBentinck** [comment]
Thanks Mike this makes sense now, I did always wonder about this setting.

**Comment by heints** [comment]
Yep, works. :/ Why and how did it work prior to upgrade.... Or did the update script fill the variable product stock management itself?

**Comment by mikejolley** [comment]
No there was nothing in place to do that.

**Comment by AntBentinck** [comment]
So to clarify, Mike we now need to go through thousands of products and uncheck this setting to prevent this from happening?

**Comment by mikejolley** [comment]
We cannot blindly update that for all users - it may have been intentional. I don't know if the sync behavior changed, but core did not turn this option on for you. It may have been enabled in err or after import.

**Comment by non-entity9** [comment]
Ran into this same issue.

Before Woo 3.0.X, enabling stock management at both the product and variation level worked, even if it was unintentional.

I did this because it would show the combined available units of the products variations in the admin product list view, eg. In stock (X). If you disabled it at the product level it would just display "In stock". It was just a hack that I found useful for giving quick and very rough info about the stock levels of products.

From what I can see, previously the stock level at a product level used to be ignored if both were selected (I always left this at 0). However, since upgrading to 3.0.X, it now seems to take precedence over variation stock levels. Because I previously had these set to zero, they now appear as out of stock.

Simple fix is to just disable the stock management at a product level, and only enable it on variations.

I don't expect a fix for this as I believe it is now behaving as originally intended and my use case was just making the most of a bug.

**Comment by TomasHurtz** [comment]
I have issue with this too.

Prior to 3.0 - we set Parent with its own SKU e.g. 1000 and Manage Stock to YES and stock amount to 0

Then we added each child product (variation) with unique SKU e.g. 1001, 1002 etc

Then we sync all across to XERO (accounting and inventory management system) - so we have parent product listed, then all listed variations underneath.

Making a changeover to now disregard the parent product is going to be a nightmare for us as this is going to affect our entire accounting system. 

What is suggested best practice here?

**Comment by TheFlav** [comment]
Was this ever resolved?

**Comment by non-entity9** [comment]
The fix was just to disable the management of stock at a product level.

**Comment by RevealMarketing** [comment]
I am having this problem. I have tried deselecting the boxs. I am still getting "out of stock" for all products.
