### ISSUE TITLE
500 Error when loading an ORDER or SUBSCRIPTION

### ISSUE THREAD

**Issue by stickypages** [woocommerce/woocommerce#13973]
### EXPLANATION OF THE ISSUE
I go to ORDERS or SUBSCRIPTIONS, and I get an error. 
_Failed to load resource: the server responded with a status of 500 (Internal Server Error)_

Some more details in the Debug >> _Just noticed this is more of a woocommerce subscription problem._
Fatal error: Using $this when not in object context in /www/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-cart-renewal.php on line 1078

Not able to load all the details on these pages. 

### STEPS TO REPRODUCE THE ISSUE
Go to an individual ORDER or SUBSCRIPTION

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.township7.com
Site URL: https://www.township7.com
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Flywheel/4.1.0
PHP Version: 5.6.29-1+deb.sury.org~precise+1
PHP Post Max Size: 300 MB
PHP Time Limit: -1
PHP Max Input Vars: 4000
cURL Version: 7.22.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_town_dev2016
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

PW Advanced Woo Reporting CrossTab ADD-ON: by Proword – 1.1
PW Advanced Woo Reporting Variation ADD-ON: by Proword – 1.1
PW Advanced Woo Reporting: by Proword – 3.1
Akismet Anti-Spam: by Automattic – 3.3
Beaver Builder Plugin (Pro Version): by The Beaver Builder Team – 1.8.3
PowerPack for Beaver Builder: by Team IdeaBox - Beaver Addons – 1.2.3
Backup by blogVault: by Backup by blogVault – 1.46
CB Custom Beaver Builder Modules: by Brian Coords – 1.2.2
Duplicate Post: by Enrico Battocchi – 3.2
Genesis Connect for WooCommerce: by StudioPress – 0.9.9
Genesis Dambuster: by Russell Jamieson – 1.6
Genesis Simple Edits: by StudioPress – 2.2.0
Genesis Title Toggle: by Bill Erickson – 1.7.1
Smart Manager: by StoreApps – 3.9.21
User Switching: by John Blackbourn – 1.0.9
Follow-Up Emails: by WooCommerce – 4.4.19
WooCommerce Force Sells: by WooCommerce – 1.1.11
WooCommerce Authorize.Net CIM Gateway: by SkyVerge – 2.6.0
WooCommerce MailChimp Subscribe (shared on wplocker.com): by John Turner – 1.0.3
WooCommerce Memberships: by SkyVerge – 1.8.1
WooCommerce Product Fees: by Caleb Burks – 1.2
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.0-beta
WooCommerce Subscriptions: by Prospress Inc. – 2.2.1
WooCommerce Table Rate Shipping: by Automattic – 3.0.2
WP All Import - WooCommerce Add-On: by Soflyy – 1.3.2
WooCommerce: by Automattic – 3.0.0
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WP All Export Pro: by Soflyy – 1.4.1
WP All Import Pro: by Soflyy – 4.4.3
WP Crontrol: by John Blackbourn & contributors – 1.5
WP All Import - User Import Add-On: by Soflyy – 1.0.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### WC Pages ###

Shop base: #45 - /shop/
Cart: #46 - /cart/
Checkout: #47 - /checkout/
My account: #48 - /my-account/

### Theme ###

Name: Altitude Pro
Version: 1.0.3
Author URL: http://www.studiopress.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.4.2
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: altitude-pro/woocommerce/checkout/review-order.php
altitude-pro/woocommerce/emails/customer-new-account.php

### Authorize.Net CIM ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Save to Log
`
</details>
After updating to v3 of WooCommerce, I am not able to load subscriptions or orders. 
seems to be more-so in the META data, the post loads, but not totals or shipping numbers appear. 

In the console it says, 
_Failed to load resource: the server responded with a status of 500 (Internal Server Error)_

**Comment by claudiosanches** [comment]
Please check your ALL your plugins before open an issue or at least open with more details, because there is no steps that I could use to try reproduce it and fix... Right now you are using 31 plugins and any of this plugins could be causing the issue.

I tested with WooCommerce + WooCommerce Subscriptions, but works just fine.

**Comment by stickypages** [comment]
Yes I did de-activate ALL, but subscriptions and woocommerce.
As well as, removing my functions code to see if that was affecting anything. 

Still having the same error.

**Comment by stickypages** [comment]
![2017-04-05 12_51_22-edit subscription township 7 wine wordpress](https://cloud.githubusercontent.com/assets/658488/24724053/9bcc2abc-19fe-11e7-9e9b-f232db797360.png)

Sample view of error

**Comment by claudiosanches** [comment]
So need to be reported to subscriptions and make sure that you are using the last version of WooCommerce Subscriptions.

**Comment by stickypages** [comment]
Yes, I am. I found the culprit. 
Subscriptions is using a STATIC method inside a NON Static class. 

-- Submitted as ticket to WOO.

![2017-04-05 13_55_04-township redmillcreative com - d__xampp_htdocs_township redmillcreative com -](https://cloud.githubusercontent.com/assets/658488/24726514/8117c4c0-1a07-11e7-9697-6d03f8bfe1e5.png)

**Comment by mikejolley** [comment]
cc @thenbrent

**Comment by thenbrent** [comment]
This has been fixed with https://github.com/Prospress/woocommerce-subscriptions/pull/2043 and the fix will go out soon.

**Comment by stickypages** [comment]
Thanks for the prompt resolution. Will wait for the update. 
Hopefully in the morning!
