### ISSUE TITLE
Variable Product meta data in the cart

### ISSUE THREAD

**Issue by adriandmitroca** [woocommerce/woocommerce#13987]
### EXPLANATION OF THE ISSUE

I don't see a way to pass custom variation attributes to display in the cart using `WC_Cart->add_to_cart($product_id, $variation_id, $meta_data_array` anymore. `cart-item-data.php` template is never being rendered after upgrade from WooCommerce 2.6 to 3.0.

### STEPS TO REPRODUCE THE ISSUE

1. Add variable product to Cart
2. See missing cart-item-data.php from the render
3. Attributes are displayed from $_product->get_title() instead.

### SYSTEM STATUS

WooCommerce 3.0

**Comment by mikejolley** [comment]
> Attributes are displayed from $_product->get_title() instead.

Attributes that are not in the title are rendered normally.

https://github.com/woocommerce/woocommerce/blob/master/templates/cart/cart.php#L87

**Comment by adriandmitroca** [comment]
@mikejolley 

How do you differentiate which attributes come to title and which to the item data then? From what I've noticed all attributes come to title and none to item data.

**Comment by starypop** [comment]
@mikejolley 

There is still a problem on 3.0.1 with checking attribute values against product variation name being too strictly. What about one-char attribute value, i.e. clothes sizes like "s" or "m"? It's super possible for stristr to find one-char string in whole title, not only in "attributes part" of product variation title but in "product parent title part" as well. Even if there is no attribute name or value in whole variation title (pre 3.0 manner).

/includes/class-wc-cart.php:561
```
// Check the nicename against the title.
if ( '' === $value || stristr( $cart_item['data']->get_name(), $value ) ) {
      continue;
}
```
