### ISSUE TITLE
Variable products don't show in categories

### ISSUE THREAD

**Issue by JohnDoe218** [woocommerce/woocommerce#13982]
After update 3.0 variable products are no longer shown in categories and also block categories. I also tried to create new variable product and after clicking Preview it shows blank page. After clicking on Categories which contains simple products and also variable products shows no products at all in the categories.

**Comment by mikejolley** [comment]
No issues https://dl.dropboxusercontent.com/s/2rdui4gbdnda0hj/2017-04-05%20at%2022.33.png

If it looks 'blank' it may be an error on the page stopping rendering. Enable debug https://codex.wordpress.org/Debugging_in_WordPress to see if this is happening.
