### ISSUE TITLE
variation not changing displayed price or displaying description

### ISSUE THREAD

**Issue by darrenhedges** [woocommerce/woocommerce#13984]
### EXPLANATION OF THE ISSUE

version 3.0.0 - a product i have has two variations comprising of 'Package Type' and 'Options'.  Depending on the type and options the prices are different.  Prior to v3.0.0 the price displayed for the product changed depending on what type and option was selected.  It also displayed the description for the choices which I used to indicate what they were getting when they selected those combinations.  Now the price doesnt change and the description doesnt appear.  It does put the correct choices into the cart though.

### STEPS TO REPRODUCE THE ISSUE

Create two variations, product type and options.  Assign bronze and silver to product type, assign drysuit and vip to options.  assign a price of 400 to bronze with no option, assign 510 to bronze and drysuit, assign 550 to bronze and vip.  assign 425 to silver with no option, 535 to silver and drysuit, 575 to silver and vip.

### SYSTEM STATUS

<details>
nothing is appearing on that tab, it remains blank page
</details>

**Comment by mikejolley** [comment]
Works fine here, however, that was with me assuming "no option" was also one of the actual options. If you left it blank and only had vip/drysuit, your variations would overlap/conflict since 'any' would match before the others.

Since this works my side I'm closing  - you did not provide a site link for me to check. Reply back to share.

**Comment by darrenhedges** [comment]
www.raid-diving-lessons.co.uk

**Comment by mikejolley** [comment]
It's working on your site.

**Comment by darrenhedges** [comment]
very odd as its not on my screen i will try different computer
