### ISSUE TITLE
Customer search box does not search by ID

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#13980]
On new order screen.

**Comment by claudiosanches** [comment]
![screenshot from 2017-04-05 17-18-37](https://cloud.githubusercontent.com/assets/1264099/24725085/ebecf0e2-1a23-11e7-8eb7-d2778b398c53.png)

This one?

On 2.6.14 it's required to have more than 3 characters too, what make hard to search by ID.

**Comment by mikejolley** [comment]
Yes. Thats also true. In this case, it was over 3 anyway.

**Comment by claudiosanches** [comment]
Do not sounds like a feature if just allow search by IDs that have more than 3 digits.
Better keep this way or allow search by any ID.

**Comment by justinshreve** [comment]
Maybe we could add a search operator for searching by IDs instead (i.e. `id:5`)

**Comment by mikejolley** [comment]
A numeric check might be enough. The user says this worked in 2.6 which is why I raised.

**Comment by claudiosanches** [comment]
Worked with a bug. So still not help everyone, since you need to have more than 99 users to see this working.
