### ISSUE TITLE
PHP Fatal Error after upgrade from 2.6.x to 3.0

### ISSUE THREAD

**Issue by alaarihan** [woocommerce/woocommerce#13990]
I'm running WP site with latest version of WP witch is 4.7.3..
After I updated WooCommerce in my site from 2.6.x to 3.0 I faced this error in every page has woocommerce loop, like /shop or any category pages..

I tried to disable all plugins except WooCommerce, and activated sixteen default WP theme but the error is the same, this is the error message:
Fatal error: Uncaught Error: Call to undefined method WP_Post::get_id() in /home/ubuntu/workspace/wp-content/plugins/woocommerce/includes/class-wc-product-factory.php:111
Stack trace:
#0 /home/ubuntu/workspace/wp-content/plugins/woocommerce/includes/class-wc-product-factory.php(28): WC_Product_Factory-&gt;get_product_id(Object(WP_Post))
#1 /home/ubuntu/workspace/wp-content/plugins/woocommerce/includes/wc-product-functions.php(108): WC_Product_Factory-&gt;get_product(Object(WP_Post), Array)
#2 /home/ubuntu/workspace/wp-content/plugins/woocommerce/includes/wc-template-functions.php(124): wc_get_product(Object(WP_Post))
#3 /home/ubuntu/workspace/wp-includes/class-wp-hook.php(300): wc_setup_product_data(Object(WP_Post))
#4 /home/ubuntu/workspace/wp-includes/class-wp-hook.php(323): WP_Hook-&gt;apply_filters('', Array)
#5 /home/ubuntu/workspace/wp-includes/plugin.php(515): WP_Hook-&gt;do_action(Array)
#6 /home/ubuntu/workspace/wp-includes/class-wp-query.php(4059): do_action_ref_array('the_post', Array)
#7 /home/ubuntu/workspace/wp-includes in /home/ubuntu/workspace/wp-content/plugins/woocommerce/includes/class-wc-product-factory.php on line 111

**Comment by mikejolley** [comment]
Have you been doing any find/replace on your own plugins? There is no get_id() call on line 111 https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-factory.php#L111

**Comment by alaarihan** [comment]
Sorry, it's my fault :( I deleted WC and reinstalled it, that solved the problem.
