### ISSUE TITLE
wc_get_order_item_meta

### ISSUE THREAD

**Issue by katdidit** [woocommerce/woocommerce#13996]
### EXPLANATION OF THE ISSUE
Notices of get_item_meta is deprecated even though it still works currently.  When replaced with wc_get_order_item_meta undefined error is thrown 
Call to undefined method WC_Order::wc_get_order_item_meta()  

Fails when extracting order details when using wc_get_order_item_meta but still works with get_item_meta call.  Was expecting wc_get_order_item_meta to return the order item meta the same way that get_item_meta works.

Sorry if maybe i'm just being dense?  Calling it the wrong way?  Found this issue on scrutinizer that may or may not be related to the error.   https://scrutinizer-ci.com/g/woocommerce/woocommerce/inspections/482ad86b-cca4-4dd4-8bba-195d0bf40053/code-structure/operation/includes/wc-order-item-functions.php%3A%3Awc_get_order_item_meta

### STEPS TO REPRODUCE THE ISSUE
 $items = $the_order->get_items();
    foreach ( $items as $item_id => $item_data ) {
		
      $items1 = $the_order->wc_get_order_item_meta($item_id, 'META_NAME', true);

### SYSTEM STATUS

<details>
Home URL: 		http://hugthehomemaker.com/hugs
Site URL: 		http://hugthehomemaker.com/hugs
WC version: 		3.0.0
Log directory writable: 		/home/hugthe5/public_html/hugs/wp-content/uploads/wc-logs/
WP version: 		4.7.3
WP multisite: 		–
WP memory limit: 		512 MB
WP debug mode: 		
WP cron: 		
Language: 		en_US
Server environment
Server info: 		Apache
PHP version: 		5.6.30
PHP post max size: 		128 MB
PHP time limit: 		30
PHP max input vars: 		4000
cURL version: 		7.45.0, OpenSSL/1.0.1e
SUHOSIN installed: 		–
MySQL version: 		5.6.33	
Max upload size: 		128 MB
Default timezone is UTC: 		
fsockopen/cURL: 		
SoapClient: 		
DOMDocument: 		
GZip: 		
Multibyte string: 		
Remote post: 		
Remote get: 		
Database
WC database version: 		3.0.0
Database prefix 	  	wp_	
woocommerce_sessions 	  	
woocommerce_api_keys 	  	
woocommerce_attribute_taxonomies 	  	
woocommerce_downloadable_product_permissions 	  	
woocommerce_order_items 	  	
woocommerce_order_itemmeta 	  	
woocommerce_tax_rates 	  	
woocommerce_tax_rate_locations 	  	
woocommerce_shipping_zones 	  	
woocommerce_shipping_zone_locations 	  	
woocommerce_shipping_zone_methods 	  	
woocommerce_payment_tokens 	  	
woocommerce_payment_tokenmeta 	  	
Security
Secure connection (HTTPS): 		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors 		Error messages should not be shown to visitors.
Active plugins (8)
Custom Post Type UI 	  	by WebDevStudios – 1.5.3
DK PDF 	  	by Emili Castells – 1.9
Master Slider 	  	by averta – 2.9.7
WC-Ecard 	  	by katdidit – 0.010a
Woocommerce Order address Print 	  	by Bhavik Patel – 3.0
WooCommerce 	  	by Automattic – 3.0.0
Wordfence Security 	  	by Wordfence – 6.3.6
WP-Optimize 	  	by David Anderson, Ruhani Rabin, Team Updraft – 2.1.1
Settings
API enabled: 		–
Force SSL: 		–
Currency 		USD ($)
Currency position 		left
Thousand separator 		,
Decimal separator 		.
Number of decimals 		2
Taxonomies: Product types 		external (external), grouped (grouped), simple (simple), variable (variable)
WC pages
Shop base:		#1163 - /gifts/
Cart:		#176 - /cart/
Checkout:		#177 - /checkout/
My account:		#178 - /my-account/
Theme
Name: 		HugtheHomemaker
Version: 		1.3.0
Author URL: 		http://Katdidit.com
Child theme: 		
Parent theme name: 		One Page
Parent theme version: 		1.3.7
Parent theme author URL: 		http://www.inkthemes.com
WooCommerce support: 		
Templates
Overrides 	  	hugthehomemaker/woocommerce/archive-product.php,
hugthehomemaker/woocommerce/content-product.php,
hugthehomemaker/woocommerce/content-product_cat.php,
hugthehomemaker/woocommerce/content-single-product.php,
hugthehomemaker/woocommerce/single-product.php

```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by claudiosanches** [comment]
There is no `WC_Order::wc_get_order_item_meta()` method, there just a function called `wc_get_order_item_meta()`.

So you code should be:

```php
$items = $the_order->get_items();
foreach ( $items as $item_id => $item_data ) {
    $items1 = wc_get_order_item_meta($item_id, 'META_NAME', true);
}
```

Or even better and the correct way:

```php
$items = $the_order->get_items();
foreach ( $items as $item_id => $item_data ) {
    $items1 = $item_data->get_meta( 'META_NAME' );
}
```

**Comment by af-developpement** [comment]
Hi,

Is there a way to get meta with an incomplete meta_name please ?
A kind of get_meta('META_NAME', 'LIKE');

Regards.
