### ISSUE TITLE
WooCommerce Shop page reloading Conineously.

### ISSUE THREAD

**Issue by Vijayshubhankar** [woocommerce/woocommerce#13997]
Hey guys!!

This is my site [http://myspecialtoybox.in/tb/](http://myspecialtoybox.in/tb/)

After updating Woocommerce to its newest 3.0 i am facing this problem. 

The shop page continuously reloads and stops and again it starts to reload.

 In browser’s console there is this error “Navigated to http://myspecialtoybox.in/tb/?v=c86ee0d9d7ed jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1″.

In browser's sources page “http://myspecialtoybox.in/tb/?v=c86ee0d9d7ed” is appearing and disappearing. 

I am not a full stack developer and i am building this site on my own. Please help me.

I tried to deactivate all the plugins and activate one by one, the problem exists in woocommerce plugin itself because as soon as i activated woocommerce this problem started.

And I want to ask you guys does reinstalling Woocommerce helps?
If Yes, then how do i do it without loosing any data

Thanks in advance.

**Comment by claudiosanches** [comment]
Already reported in https://github.com/woocommerce/woocommerce/issues/13902

Will be solved in the 3.0.1.
Thanks for report it.

**Comment by haazo** [comment]
Hi, Vijayshubhankar, Your site looks cool. I'm new to the wordpress and woocommerce as well GitUniverse. can you pls. help me out with...

1. whenever I click on the add to the cart button, the page reloads.. which is pretty annoying. I see your site is perfectly working fine. How did you do it ? 

2 what is the plugin you are using, to show, view cart next to add to cart button.

3. as well as the check out page..

Pls help me with the plugin.

Thanks.

**Comment by Vijayshubhankar** [comment]
Use WooCommerce Cart Tab by JamesKoster
