### ISSUE TITLE
Adding Multi-step Checkout Option to WooCommerce

### ISSUE THREAD

**Issue by AUM001** [woocommerce/woocommerce#13999]
Has there been consideration to adding a multi-step checkout option to WooCommerce?

It would be great to be able to have it so that we can capture the visitors email address as they begin to checkout just in case they decide to abandon the cart early in the process. I imagine a first step would request they enter the email address of their existing account to login in or to enter one to being the registration/checkout process. Then they would move on to the second step of making payment or entering the rest of their information.

The sooner we can capture the new customer email address the better...

- M

**Comment by claudiosanches** [comment]
This is not something that we are considering right now, but fell free to submit this idea in http://ideas.woocommerce.com/forums/133476-woocommerce
Thanks for your suggestion.
