### ISSUE TITLE
Download links always download the first product in the list

### ISSUE THREAD

**Issue by lazharichir** [woocommerce/woocommerce#13998]
Basically, a customer orders a product that offers several downloads, then receives the email with all the links. Regardless of the link clicked, it will download the first file only and increment its download count (in the DB, this is the download with the lowest ID.)

I looked at the DB and here is what the rows look like - everything seems correct since the download_id's are the right one (matching the postmeta array of downloadable files).

<img width="639" alt="screen shot 2017-04-06 at 10 20 38" src="https://cloud.githubusercontent.com/assets/12215372/24736563/e0fb7d22-1ab2-11e7-9c23-b065166a6031.png">

It's problematic as all my orders are downloads......

WC 3.0 (latest)
WP 4.7.3 (latest)

**Comment by claudiosanches** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/13983
Thanks for report it.

**Comment by lazharichir** [comment]
Indeed - just replaced the file in question to test and seems to work correctly.

**Comment by claudiosanches** [comment]
@lazharichir thanks for the help.
