### ISSUE TITLE
Woocommerce 3.0 - Can't see the size bought in the order and in the New Order Mail

### ISSUE THREAD

**Issue by contino23** [woocommerce/woocommerce#14005]
### EXPLANATION OF THE ISSUE
I've installed woocommerce 3.0 and I have a big problem with product variations.
In my e-commerce www.jarare.com I sell Sandals.
In past when a client bought a pair of sandals I recive an e-mail (New Orders Mail) with the correct variation (the size of the sandal) that the client Ordered.

Now I don't see the correct variation ordered in new orders mail 
and I also don't see the correct variation ordered in the woocommerce Orders Page.

This is two screenshot example:
http://imgur.com/5yrjHoF
http://imgur.com/RlgPY11

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: http://www.jarare.com
Site URL: http://www.jarare.com/newsite
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 32 MB
PHP Time Limit: 400
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: ❌ 5.1.73 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: 3w3gGhPoE_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (42) ###

LayerSlider WP: by Kreatura Media – 6.2.2
Anti-Spam Akismet: by Automattic – 3.3
BAW Login/Logout menu: by Juliobox – 1.3.3
Black Studio TinyMCE Widget: by Black Studio – 2.3.1
X-Pay CartaSi e-commerce: by CartaSi S.p.a. – 1.0.9
Cimy User Extra Fields: by Marco Cimmino – 2.7.1
Contact Form 7: by Takayuki Miyoshi – 4.7
Cookie Notice: by dFactory – 1.2.38
Duplicate Post: by Enrico Battocchi – 3.2
Enjoy Plugin for Instagram: by F. Prestipino
F. Di Pane - Mediabeta Srl – 3.3

Envato WordPress Toolkit: by Envato – 1.7.3
ExportFeed for WooCommerce Google Product Feed: by ExportFeed.com – 1.0.0
Google Analytics Dashboard per WP: by Alin Marcu – 4.9.6.2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.6
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Instagram Feed: by Smash Balloon – 1.4.8
Jetpack by WordPress.com: by Automattic – 4.8
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1
MailChimp per Wordpress: by ibericode – 4.1.0
Facebook Pixel for WP: by NsThemes – 1.1.2
Peter's Login Redirect: by Peter Keung – 2.9.1
Product CSV Import Export (BASIC): by HikeForce – 1.3.1
Slider Revolution: by ThemePunch – 5.4.1
WPML Multilingual CMS: by OnTheGoSystems – 3.6.3
TheGem Theme Elements: by Codex Themes – 2.1.0
TheGem Import: by Codex Themes – 2.0.0
Widget Importer & Exporter: by churchthemes.com – 1.4.5
WooCommerce CartaSi X-Pay Payment Gateway: by Alian Schiavoncini – 1.0.1
WooCommerce AdWords Conversion Tracking: by Wolf+Bär GmbH – 1.3.5
WooCommerce Multilingual: by OnTheGoSystems – 4.1.2
WooCommerce Partita IVA e Codice Fiscale [FREE]: by NetstarSolution – 1.0
WooCommerce: by Automattic – 3.0.0
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
Wordpress Page Widgets: by CodeAndMore – 3.2
WP User Avatar: by flippercode – 2.0.8
WPML Media: by OnTheGoSystems – 2.1.24
WPML String Translation: by OnTheGoSystems – 2.5.2
WPML Translation Management: by OnTheGoSystems – 2.2.7
WPML Widgets: by Jeroen Sormani – 1.0.6
Easy Forms for MailChimp: by YIKES
Inc. – 6.3.11

YITH WooCommerce Wishlist: by YITHEMES – 2.1.0
ZillaLikes: by ThemeZilla – 1.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #7 - /shop/
Carrello: #8 - /cart/
Cassa: #9 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: TheGem_child_user_icons
Version: 1.0
Author URL: http://codex-themes.com/thegem/
Child Theme: ✔
Parent Theme Name: TheGem
Parent Theme Version: 2.0.2
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Archive Template: Il tuo tema ha il file woocommerce.php
non potrai sovrascrivere il template personalizzato woocommerce/archive-product.php poichè woocommerce.php ha priorità su archive-product.php. Questo serve a prevenire problemi di visualizzazione.

Overrides: thegem/woocommerce/archive-product.php
thegem/woocommerce/cart/cart-item-data.php
thegem/woocommerce/cart/cart-shipping.php
thegem/woocommerce/cart/cart-totals.php
thegem/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.0
thegem/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
thegem/woocommerce/cart/mini-cart.php
thegem/woocommerce/cart/shipping-calculator.php
thegem/woocommerce/checkout/form-billing.php
thegem/woocommerce/checkout/form-checkout.php
thegem/woocommerce/checkout/form-login.php
thegem/woocommerce/checkout/form-shipping.php
thegem/woocommerce/checkout/payment-method.php
thegem/woocommerce/checkout/payment.php
thegem/woocommerce/checkout/review-order.php
thegem/woocommerce/checkout/terms.php
thegem/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
thegem/woocommerce/content-product.php
thegem/woocommerce/content-product_cat.php
thegem/woocommerce/content-single-product.php
thegem/woocommerce/content-widget-product.php
thegem/woocommerce/global/breadcrumb.php
thegem/woocommerce/global/form-login.php
thegem/woocommerce/loop/loop-end.php
thegem/woocommerce/loop/loop-start.php
thegem/woocommerce/loop/orderby.php
thegem/woocommerce/loop/pagination.php
thegem/woocommerce/loop/price.php
thegem/woocommerce/loop/rating.php
thegem/woocommerce/loop/result-count.php
thegem/woocommerce/loop/sale-flash.php
thegem/woocommerce/myaccount/form-edit-account.php
thegem/woocommerce/myaccount/form-edit-address.php
thegem/woocommerce/myaccount/form-login.php
thegem/woocommerce/myaccount/form-lost-password.php
thegem/woocommerce/myaccount/my-account.php
thegem/woocommerce/myaccount/navigation.php
thegem/woocommerce/myaccount/orders.php
thegem/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 3.0.0
thegem/woocommerce/order/order-details-item.php version 2.5.0 is out of date. The core version is 3.0.0
thegem/woocommerce/order/order-details.php version 2.6.0 is out of date. The core version is 3.0.0
thegem/woocommerce/product-searchform.php
thegem/woocommerce/single-product/add-to-cart/external.php
thegem/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.0
thegem/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
thegem/woocommerce/single-product/add-to-cart/variable.php
thegem/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
thegem/woocommerce/single-product/rating.php
thegem/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
thegem/woocommerce/single-product/review.php
thegem/woocommerce/single-product/short-description.php
thegem/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
thegem/woocommerce/single-product/tabs/description.php
thegem/woocommerce/single-product/tabs/tabs.php
thegem/woocommerce/single-product/title.php
thegem/woocommerce/single-product-reviews.php

Outdated Templates: ❌Learn how to update
`

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/13975
