### ISSUE TITLE
Image loss

### ISSUE THREAD

**Issue by Armadur** [woocommerce/woocommerce#14010]
### EXPLANATION OF THE ISSUE

In **media** some of images are lost, links dont work, for example, when i click on image, its not shown but when i click edit it shows a picture
Screenshot: 
http://prntscr.com/et2pvk
http://prntscr.com/et2pzr
http://prntscr.com/et2q41
checked my permalinks, all good
 
Tried other themes too, same problem

**Comment by mikejolley** [comment]
Looks like missing thumbnails. If you're using a CDN, try refreshing or disabling it. Otherwise use 'regenerate thumbnails' plugin.

**Comment by Armadur** [comment]
Not using CDN, tried with that plugin, well couple of them, didnt help at all...
