### ISSUE TITLE
rating.php template file dont have the correct version 3.0 number

### ISSUE THREAD

**Issue by themedotal** [woocommerce/woocommerce#14015]
### EXPLANATION OF THE ISSUE
templates/loop/rating.php dont have the correct version 3.0 number, of course changes are made to this file.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by dixitadusara** [comment]
@mikejolley ,

I have pushed the code for fixes and did pull request  # #14022  please review it and let us know your thoughts for the same.

Thanks,
Dixita
