### ISSUE TITLE
add-to-cart.php template file dont have the correct version 3.0 number

### ISSUE THREAD

**Issue by themedotal** [woocommerce/woocommerce#14016]
### EXPLANATION OF THE ISSUE
templates/loop/add-to-cart.php dont have the correct version number 3.0, of course changes are made in this file.

This is the 3rd template file that i have found to not have the correct version number, maybe there are more. 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by dixitadusara** [comment]
@mikejolley ,

I have pushed the code for fixes and did pull request # #14024 please review it and let us know your thoughts for the same.

Thanks,
Dixita
