### ISSUE TITLE
Image loss after 3.0 update

### ISSUE THREAD

**Issue by Armadur** [woocommerce/woocommerce#14019]
In **media** some of images are lost, links dont work, for example, when i click on image, its not shown but when i click edit it shows a picture
Screenshot:
http://prntscr.com/et2pvk
http://prntscr.com/et2pzr
http://prntscr.com/et2q41,
http://prntscr.com/et3iie
checked my permalinks, all good

Tried other themes too, same problem
I am not using CDN and i tried with "regenerate thumbnails" plug in

and i checked my folders for uploaded files, files are deleted.

**Comment by mikejolley** [comment]
This has not affected myself or other users (?). I don't think it's related. There are no unlink calls on images or gallery items https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=unlink&type=

@claudiosanches Any ideas?

**Comment by mikejolley** [comment]
Were these on variations by any change? Are the variations missing too?

**Comment by Armadur** [comment]
No only images were missing, problem was that new version does NOT support special caracters as 
**"Ü",  "Ä",  "Ö"** and similar and it deletes it automaticly from folder uploads, i would recommend now to name all pictures without these characters

**Comment by Armadur** [comment]
No only images were missing, problem was that new version does NOT support special caracters as
"Ü", "Ä", "Ö" and similar and it deletes it automaticly from folder uploads, i would recommend now to name all pictures without these characters

**Comment by claudiosanches** [comment]
This is weird, since WordPress controls images... We don't have anything on WooCommerce do be able to control this kind of thing.
