### ISSUE TITLE
HTTP ERROR 500 after update 3.0.0

### ISSUE THREAD

**Issue by felipecarvalho0** [woocommerce/woocommerce#14025]
After update the woocommerce, the hole site stopped to open. Genarating HTTP ERROR 500.

Please. How to fix this?

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/how-to-debug-issues-after-updates/

**Comment by felipecarvalho0** [comment]
Thanks mikejolley!!

I downloaded the previous version (2.6.14). 

Got back working.
