### ISSUE TITLE
Template Version Issue

### ISSUE THREAD

**Issue by hardikgohil79** [woocommerce/woocommerce#14020]
your latest version is 3.0.0 but The template file templates/content-product.php have @version 2.6.1 version.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by dixitadusara** [comment]
@mikejolley ,

I have pushed the code for fixes and did pull request  # https://github.com/woocommerce/woocommerce/pull/14021 please review it and let us know your thoughts for the same.

Thanks,
Dixita

**Comment by mikejolley** [comment]
This is the last version it was updated in. Not the current WC version.
