### ISSUE TITLE
up-sell version issue

### ISSUE THREAD

**Issue by hardikgohil79** [woocommerce/woocommerce#14038]
The template file templates/single-product/up-sells.php was modified but the version was not updated. still listed as @version 1.6.4

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/up-sells.php#L16
