### ISSUE TITLE
Issue with product gallery image size

### ISSUE THREAD

**Issue by cristian-ungureanu** [woocommerce/woocommerce#14034]
This is how my theme displays product gallery http://prntscr.com/et5duo and this is how it should be http://prntscr.com/et5f8u .

Product gallery images aren't cropping. Instead of getting 'shop_thumbnail' size, they are getting 'shop_single' size.
This can be fixed by replacing 'shop_single' size from this line https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-thumbnails.php#L43 with 'shop_thumbnail'

**Comment by mikejolley** [comment]
It comes from here which is thumbnail size https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-thumbnails.php#L42

Looks like that needs hard crop to stop this.

To test, I made an odd shaped shop single. This was the result: 

![2017-04-06 at 14 21](https://cloud.githubusercontent.com/assets/90977/24756048/523bec94-1ad4-11e7-8ae6-b9eee7ee3c9d.png)

So it's not that.

**Comment by UXbarn** [comment]
Hello,

I also got the same issue as @cristian-ungureanu. Why it uses "shop_single" instead of the "shop_thumbnail" size for the product thumbnails in the product-thumbnails.php file?

It looks like the thumbnail URL is only put in the "data-thumb" attribute of the div and it has no use? 

Thanks.

**Comment by mikejolley** [comment]
Look at the link I provided.
