### ISSUE TITLE
Override class of woo-commerce rest-api using plugin 

### ISSUE THREAD

**Issue by prakashsatani** [woocommerce/woocommerce#14030]
is it possible to override a class of the woocommerce api?

I want to override the class-wc-api-customers.php so that there is no email sent when a new user is created.

Up to now the only possibility I found was to directly edit the file in includes/api/legacy/v3.
If I use this structure (mytheme/woocommerce/includes/api/legacy/v3/class-wc-api-products.php) in my theme it doesn't work.

Thanks for your ideas.

**Comment by mikejolley** [comment]
No, these classes cannot be changed as they are part of the core plugin.

**Comment by prakashsatani** [comment]
So is there another way to call my function when rest-api calls ?

**Comment by claudiosanches** [comment]
@prakashsatani not to mention that you should use our legacy REST API, since will be removed soon.
Not to mention that you can use the new WordPress REST API to create your own endpoints without need to change anything from our endpoints.

**Comment by prakashsatani** [comment]
how can i create new WordPress REST API to own endpoints?

**Comment by claudiosanches** [comment]
@prakashsatani here how to create custom WordPress REST API endpoints: https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/

**Comment by prakashsatani** [comment]
Thank you @claudiosanches
