### ISSUE TITLE
Can't see what variations have been bought, only the variation codes

### ISSUE THREAD

**Issue by Unbelieva** [woocommerce/woocommerce#14033]
### EXPLANATION OF THE ISSUE

It seems like WooCommerce 3.0.0 hasn't been tested at all! In the full Orders view it doesn't have the column for quick viewing an order and its details anymore and even if I go to a certain order's main view I can't find a place where to see in what variations the item has been bought (for instnace color and size wise), I only see the variation codes but that makes the whole process 10000 times more time consuming.

### STEPS TO REPRODUCE THE ISSUE

Just log into a WP page where you have the newest vers of WooCommerce installed and you will see that it has lost one of its most functional features.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://streetshopone.ee
Site URL: http://streetshopone.ee
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: et

### Server Environment ###

Server Info: Apache/2.4.7
PHP Version: ❌ 5.5.9-1ubuntu4.21 - Soovitame PHP versiooniks vähemalt 5.6. Vaata: Kuidas uuendada oma PHP versiooni
PHP Post Max Size: 8 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - Soovitame MySQL versiooniks vähemalt 5.6. Vaata: WordPressi nõuded
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Sinu pood ei kasuta HTTPS-i. Lisainfo HTTPS-i ja SSL sertifikaatide kohta.
Hide errors from visitors: ✔

### Active Plugins (31) ###

Admin Menu Editor: - Janis Elsts – 1.7.3
Affiliates Manager WooCommerce Coupons Integration: - wp.insider
affmngr – 1.0.2

WP Affiliate Manager: - wp.insider
wpaffiliatemgr – 2.4.3

Customize Admin: - Johan van der Wijk – 1.7.3
DNUI: - Nicearma – 2.5.7
WooCommerce - Gift Cards: - WP Ronin – 2.5.6
Google Analytics Dashboard for WP: - Alin Marcu – 4.9.6.2
JP Sharing: - JP – 3.9.6
Limit Login Attempts: - Johan Eenfeldt – 1.7.1
Loco Translate: - Tim Whitlock – 2.0.12
Slider Revolution: - ThemePunch – 5.3.1.5
Simple Page Ordering: - Jake Goldman
10up – 2.2.4

WPML Multilingual CMS: - OnTheGoSystems – 3.6.3
Facebook Open Graph, Google+ and Twitter Card Tags: - Webdados – 2.0.8.1
Woocommerce E-Abi Postoffice plugin: - Matis Halmann
Aktsiamaailm LLC – 1.24

WooCommerce Multilingual: - OnTheGoSystems – 4.1.2
Woocommerce Maksekeskus Estonia: - Matis Halmann
Aktsiamaailm LLC – 2.21

WooCommerce POS: - kilbot – 0.4.6
E-Abi Omniva Shipping method plugin: - Matis Halmann
Aktsiamaailm LLC – 1.1

E-Abi Woocommerce Itella Shipping method plugin: - Matis Halmann
Aktsiamaailm LLC – 1.6

Woocommerce Simple Storewide Sale: - Wpgenie – 1.0.6
WooCommerce: - Automattic – 3.0.0
WP All Import Pro: - Soflyy – 4.4.3
WP-Optimize: - David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP All Import - WooCommerce Add-On Pro: - Soflyy – 2.3.5
WPML All Import: - OnTheGoSystems – 2.0.3
WPML CMS Nav: - OnTheGoSystems – 1.4.19
WPML Sticky Links: - OnTheGoSystems – 1.4.0
WPML String Translation: - OnTheGoSystems – 2.5.2
WPML Translation Management: - OnTheGoSystems – 2.2.7
YITH WooCommerce Wishlist: - YITHEMES – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Poe alusaadress: #1037 - /epood/
Ostukorv: #141 - /ostukorv/
Kassa: #143 - /checkout/
Minu konto: #145 - /minu-konto/

### Theme ###

Name: Kallyas Child Theme
Version: 4.1
Author URL: http://themeforest.net/user/hogash
Child Theme: ✔
Parent Theme Name: Kallyas
Parent Theme Version: 4.10.3
Parent Theme Author URL: http://themeforest.net/user/hogash
WooCommerce Support: ✔

### Templates ###

Overrides: kallyas/woocommerce/product-searchform.php
`
</details>

**Comment by mikejolley** [comment]
The column is gone - read the release notes. https://href.li/?http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/18832222-dynamically-display-order-content-on-orders-page

other issue https://github.com/woocommerce/woocommerce/pull/13975
