### ISSUE TITLE
'Shipping Only' Tax status not working

### ISSUE THREAD

**Issue by JoeDMitchell** [woocommerce/woocommerce#14045]
### EXPLANATION OF THE ISSUE

In 3.0, products that were set with the shipping only tax status are not being exempt from tax.

### STEPS TO REPRODUCE THE ISSUE

1. Set a product with the shipping only tax status. 
2. Product does not appear without tax added on.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://192.168.100.200:2223/build
Site URL: http://192.168.100.200:2223/build
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.0
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/0.9.8zd

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.42 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 35: Unsupported SSL protocol version
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. 200

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #4 - /all-products/
Basket: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
Taxes shipping only:

![2017-04-06 at 16 36](https://cloud.githubusercontent.com/assets/90977/24762755/30006264-1ae7-11e7-8ce6-975ab87bdaf3.png)

if this is variable, ensure the variations have the same tax settings.

**Comment by JoeDMitchell** [comment]
It is indeed a variation and they do indeed have the tax status 'same as parent'

<img width="492" alt="screen shot 2017-04-06 at 16 39 31" src="https://cloud.githubusercontent.com/assets/8067085/24762952/dbc450ec-1ae7-11e7-8940-6f72efbfbf00.png">
<img width="720" alt="screen shot 2017-04-06 at 16 39 45" src="https://cloud.githubusercontent.com/assets/8067085/24762958/e025b6bc-1ae7-11e7-8b00-f2d0302ed9f2.png">
<img width="379" alt="screen shot 2017-04-06 at 16 40 46" src="https://cloud.githubusercontent.com/assets/8067085/24762970/e3920b3e-1ae7-11e7-8f88-3f7e2424d778.png">
<img width="360" alt="screen shot 2017-04-06 at 16 40 52" src="https://cloud.githubusercontent.com/assets/8067085/24762976/e67f8038-1ae7-11e7-87a1-b35857f98a33.png">
<img width="688" alt="screen shot 2017-04-06 at 16 38 05" src="https://cloud.githubusercontent.com/assets/8067085/24762983/e9ae8b00-1ae7-11e7-823f-f3170401d5f0.png">

**Comment by chriskemm** [comment]
@mikejolley

**Comment by mikejolley** [comment]
Same with variable my side:

![2017-04-06 at 16 53](https://cloud.githubusercontent.com/assets/90977/24763541/937e55d8-1ae9-11e7-8fcf-2bc4e4d20c40.png)

Tax rate is 10%. Variations are same as parent, parent has shipping only.

![2017-04-06 at 16 54](https://cloud.githubusercontent.com/assets/90977/24763585/b5f749a8-1ae9-11e7-840d-f688fd81c7f4.png)

**Comment by JoeDMitchell** [comment]
@mikejolley If it helps, the issue is not present on simple products but happens on every variable product for me if I adjust the tax status, including if I change it to 'none'. There is actually no option on each variant to change the 'tax status', only the tax class and shipping class. 

At a bit of a loss if you can't replicate it.

**Comment by mikejolley** [comment]
Ah you're right I set tax class. Not sure if the setting should be there - it might just inherit at all times. Checking in a sec.

**Comment by JoeDMitchell** [comment]
@mikejolley Thanks for this. The issue seems to only be half fixed though. It now shows the right price when you select a variant but the range itself is showing with tax included. 

<img width="349" alt="screen shot 2017-04-07 at 09 24 10" src="https://cloud.githubusercontent.com/assets/8067085/24791958/0804d852-1b74-11e7-87ac-9cbc085062fb.png">
