### ISSUE TITLE
Quantity text field remains visible

### ISSUE THREAD

**Issue by Tibolab60240** [woocommerce/woocommerce#14040]
### EXPLANATION OF THE ISSUE

The quantity text field remains visible on product pages despite having checked the "unique item" box in the inventory section

### STEPS TO REPRODUCE THE ISSUE

Check box "unique item" and refresh product page

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: https://macocotteenpapier.fr
Site URL: https://macocotteenpapier.fr
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 64 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: mcep_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

VaultPress: par Automattic – 1.8.8
Contact Form 7: par Takayuki Miyoshi – 4.7
Social Media Flying Icons | Floating Social Media Icon: par Acurax – 4.2.4
Meta Slider: par Matcha Labs – 3.5
Popup: par Gopi Ramasamy – 11.8
Storefront Hamburger Menu: par WooThemes – 1.2.0
Storefront Homepage Contact Section: par WooThemes – 1.0.3
Storefront Product Pagination: par WooThemes – 1.2.1
Storefront Sticky Add to Cart: par WooThemes – 1.1.6
WP Simple Pay Lite for Stripe: par Moonstone Media – 1.6.0
Theme Customisations: par WooThemes – 1.0.0
Use Any Font: par Dinesh Karki – 4.7.2
W3 Total Cache: par Frederick Townes – 0.9.5.2
WC Fields Factory: par Saravana Kumar K – 1.3.8
WooCommerce Customizer: par SkyVerge – 2.4.0
WooCommerce Stripe Gateway: par WooCommerce – 3.1.6
WooCommerce Product Gift Wrap: par Mike Jolley – 1.1.0
WooCommerce: par Automattic – 3.0.0
WordPress Website Monitoring: par WP Rocket – 2.0.2

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Base boutique: #79 - /boutique/
Panier: #148 - /panier/
Commande: #477 - /commande/
Mon compte: #479 - /mon-compte/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14023
