### ISSUE TITLE
featured product not updated in postmeta table

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/woocommerce#14056]
### EXPLANATION OF THE ISSUE

The postmeta table does not show _featured "yes" when product is set to "featured" in the products list or in the single product edit page. Hence the product is not picked up as being featured by WCPS (WooCommerce Product Slider).

### STEPS TO REPRODUCE THE ISSUE
mark a product as "featured" either way and check the postmeta table for a "_featured" = "yes". It is not there.
Putting a "yes" in the table makes the product to show up in the slider

### SYSTEM STATUS
<details>
`
### WordPress Environment ###

Home URL: https://www.speldorado.com
Site URL: https://www.speldorado.com
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: shop_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Adminer: door Frank Bültge – 1.4.5
BackWPup: door Inpsyde GmbH – 3.3.7
Contact Form 7: door Takayuki Miyoshi – 4.7
Display Posts Shortcode: door Bill Erickson – 2.7.0
Easy WP SMTP: door wpecommerce – 1.2.4
Flexible Shipping PRO: door WP Desk – 1.4
Flexible Shipping: door WP Desk – 1.9
Google Analytics for WordPress by MonsterInsights: door MonsterInsights – 6.1.6
Image Widget: door Modern Tribe
Inc. – 4.3.1

Instagram Slider Widget: door jetonr – 1.4.0
Kassa: door Dennis Claassens – 1.0
Overzicht: door Dennis Claassens – 1.0
Productimport: door Dennis Claassens – 1.0
Pronamic iDEAL: door Pronamic – 4.5.3
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 2.2.6
Simple Facebook Plugin: door topdevs.net – 1.5
Speldo Tools: door Egbert Jan van den Bussche – 3.0
TinyMCE Advanced: door Andrew Ozz – 4.4.3
Transacties: door Dennis Claassens – 1.0
Voorraadbeheer: door Dennis Claassens – 1.0
WooCommerce Customizer: door SkyVerge – 2.4.0
WooCommerce Print Invoices/Packing Lists: door SkyVerge – 3.2.0
WooCommerce Product CSV Export Suite: door Egbert Jan van den Bussche – 1.9.11
WooCommerce Product CSV Import Suite: door Automattic – 1.10.12
Woocommerce Products Slider: door pickplugins – 1.12.6
WooCommerce: door Automattic – 3.0.0
WooCommerce Helper: door WooCommerce – 1.7.2 – Netwerk geactiveerd
WP Desk Helper: door WP Desk – 1.2
MailPoet Newsletters: door MailPoet – 2.7.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Winkelbasis: #5 - /webwinkel/
Winkelmand: #6 - /webwinkel/winkelwagen/
Afrekenen: #7 - /webwinkel/afrekenen/
Mijn account: #9 - /webwinkel/mijn-account/

### Theme ###

Name: speldorado
Version: 2.0.0
Author URL: http://www.vandenbussche.nl/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
3.0 uses a taxonomy. Product_visibiity

**Comment by EgbertJan** [comment]
In which table? postmeta? I can only find _visibility.

Egbert Jan


Op 6-4-2017 om 20:31 schreef Mike Jolley:

**Comment by EgbertJan** [comment]
Where in the database can I find that a products is marked "featured".
It used to be _featured in postmeta. We need to set/retrieve/revoke
featured products on the go. This is an interactive process. As soon as
we mark a product "featured", we should be able to find its featured
status in the DB somewhere. It used to be a simple query in postmeta.
regards,
Egbert Jan

Op 6-4-2017 om 20:31 schreef Mike Jolley:

**Comment by claudiosanches** [comment]
@EgbertJan this is a new taxonomy now, WooCommerce don't use `_featured` postmeta anymore.

**Comment by EgbertJan** [comment]
TNX.
That is what Mike told me. But where is the fact stored that I selected
a product as being featured now? Can I easily retrieve this from the
database like i used to do with _featured in postmeta?

Egbert Jan

Op 6-4-2017 om 23:22 schreef Claudio Sanches:

**Comment by EgbertJan** [comment]
Addittion:
I have marked 3 products as featured but I have yet to find out how to retrieve this information from any the database tables.
EJ

**Comment by claudiosanches** [comment]
@EgbertJan the same way that any other taxonomy in WordPress.
How WordPress store regular post categories and tags?

**Comment by EgbertJan** [comment]
Hm. Via a very inconvenient way with several relationship tables. Why can't I find any trace of a product being marked featured in any table??? 
BTW: WCPS needs repairing too. I've informed Nur Hasan. 
CU, Egbert Jan

**Comment by claudiosanches** [comment]
@EgbertJan WordPress uses it for several years and looks just fine, still if you thing that it's inconvenient way, you can open a ticket in WordPress core trac.

> Why can't I find any trace of a product being marked featured in any table???

Looking in the wrong place?

Here WordPress database description: https://codex.wordpress.org/Database_Description
And here how works taxonomies in WordPress: https://codex.wordpress.org/WordPress_Taxonomy

**Comment by EgbertJan** [comment]
Many thanks. With the url's I should be able to proceed.
CU, Egbert Jan

Op 6-4-2017 om 23:53 schreef Claudio Sanches:

**Comment by asadalarma** [comment]
yes , 3.0 uses the Product_visibiity taxonomy .

First thing , you can search the products by 

select * from wp_posts where post_type='product'

you can take randomly one product id from post table .

The term relationship is having the post_id in form of object id , you can join as well
