### ISSUE TITLE
Subscriptions not processing since your update - SO FRUSTRATING EVERY TIME YOU UPDATE!!!!!

### ISSUE THREAD

**Issue by vindugle** [woocommerce/woocommerce#14050]
### EXPLANATION OF THE ISSUE

I swear everytime WooCommerce updates my recurring payments never restart. You would think a major commerce company like WOO would want small businesses to succeed. I wish I could talk to a LIVE person and get this figured out too.

Plus I think your NAME YOUR PRICE tool is causing problems as well.

### STEPS TO REPRODUCE THE ISSUE

After every update my recurring people in the system fail to process. Which is valuable money for me.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://beresolute.org
Site URL: https://beresolute.org
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_0xstpstp5g_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Akismet Anti-Spam: by Automattic – 3.3
Beaver Builder Plugin (Standard Version): by The Beaver Builder Team – 1.9.5.3
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

Captcha Pro by BestWebSoft: by BestWebSoft – 4.2.9
Google Analyticator: by SumoMe – 6.5.2
Groups Engine: by Eric Murrell (Volacious) – 1.0.9
Password Strength for WooCommerce: by Potent Plugins – 1.0.1
Tax Rate Upload: by Adam Bowen – 2.4.5
Watu PRO: by Kiboko Labs – 5.4.0.5
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce Memberships: by SkyVerge – 1.8.1
WooCommerce - ShipStation Integration: by WooThemes – 4.1.8
WooCommerce Subscriptions Gifting: by Prospress Inc. – 1.0
WooCommerce Subscriptions: by Prospress Inc. – 2.2.2
WooCommerce Zapier Integration: by OM4 – 1.6.6
WooCommerce: by Automattic – 3.0.0
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### WC Pages ###

Shop base: #2259 - /shop/
Cart: #7026 - /cart/
Checkout: #2261 - /checkout/
My account: #7436 - /my-account/

### Theme ###

Name: Flatsome
Version: 3.3.1
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
```
</details>

<!--
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
-->

**Comment by rocketeer76** [comment]
You can talk to a live person. If you've bought a plugin/theme from Woo that they support, regardless of the plugin/theme. Please, don't capitalize and keep in mind, no one forces you to use any of the code or functionality developed by Woo or the community.

**Comment by mikejolley** [comment]
Sorry about your issue. You need to go through the help desk so the subscriptions devs can look into this and get access if needed.

https://woocommerce.com/my-account/tickets/

Put in a ticket and someone will get back to you.

**Comment by vindugle** [comment]
Rocketeer76, so give me a number of who I can call. I would love to talk through this issue.
