### ISSUE TITLE
pagination 

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/woocommerce#14057]
### EXPLANATION OF THE ISSUE
pagination used to show "showing 1 - 24 from 345" (page 2:  25 - 50...). In 3.0.0 it only shows "showing 1". Page number in the url seens OK
### STEPS TO REPRODUCE THE ISSUE
Show an archive page with more than the set number of products per page
### SYSTEM STATUS
<details>
`
### WordPress Environment ###

Home URL: https://www.speldorado.com
Site URL: https://www.speldorado.com
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: shop_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Adminer: door Frank Bültge – 1.4.5
BackWPup: door Inpsyde GmbH – 3.3.7
Contact Form 7: door Takayuki Miyoshi – 4.7
Display Posts Shortcode: door Bill Erickson – 2.7.0
Easy WP SMTP: door wpecommerce – 1.2.4
Flexible Shipping PRO: door WP Desk – 1.4
Flexible Shipping: door WP Desk – 1.9
Google Analytics for WordPress by MonsterInsights: door MonsterInsights – 6.1.6
Image Widget: door Modern Tribe
Inc. – 4.3.1

Instagram Slider Widget: door jetonr – 1.4.0
Kassa: door Dennis Claassens – 1.0
Overzicht: door Dennis Claassens – 1.0
Productimport: door Dennis Claassens – 1.0
Pronamic iDEAL: door Pronamic – 4.5.3
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 2.2.6
Simple Facebook Plugin: door topdevs.net – 1.5
Speldo Tools: door Egbert Jan van den Bussche – 3.0
TinyMCE Advanced: door Andrew Ozz – 4.4.3
Transacties: door Dennis Claassens – 1.0
Voorraadbeheer: door Dennis Claassens – 1.0
WooCommerce Customizer: door SkyVerge – 2.4.0
WooCommerce Print Invoices/Packing Lists: door SkyVerge – 3.2.0
WooCommerce Product CSV Export Suite: door Egbert Jan van den Bussche – 1.9.11
WooCommerce Product CSV Import Suite: door Automattic – 1.10.12
Woocommerce Products Slider: door pickplugins – 1.12.6
WooCommerce: door Automattic – 3.0.0
WooCommerce Helper: door WooCommerce – 1.7.2 – Netwerk geactiveerd
WP Desk Helper: door WP Desk – 1.2
MailPoet Newsletters: door MailPoet – 2.7.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Winkelbasis: #5 - /webwinkel/
Winkelmand: #6 - /webwinkel/winkelwagen/
Afrekenen: #7 - /webwinkel/afrekenen/
Mijn account: #9 - /webwinkel/mijn-account/

### Theme ###

Name: speldorado
Version: 2.0.0
Author URL: http://www.vandenbussche.nl/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/38tu4tggov9nfzx/2017-04-06%20at%2019.52.png

I think you'll find this is your localisation?

**Comment by EgbertJan** [comment]
So it might be a broken translation? Dunno who does NL/B nowadays...

TNX
Egbert Jan, NL

Op 6-4-2017 om 20:52 schreef Mike Jolley:

**Comment by EgbertJan** [comment]
The probem vanished with the update to 3.0.1.
Thanks!
