### ISSUE TITLE
can't add categories

### ISSUE THREAD

**Issue by sixTeamMooses** [woocommerce/woocommerce#14069]
### EXPLANATION OF THE ISSUE

unable to add or edit categories after upgrade

### STEPS TO REPRODUCE THE ISSUE

unable to add or edit categories after upgrade
(i'm removing server names & paths)
### SYSTEM STATUS

<details>
WordPress environment
Home URL:		http://pluscotton.com
Site URL:		http://pluscotton.com
WC version:		3.0.0
Log directory writable:		 /xxxxx/wp-content/uploads/wc-logs/
WP version:		4.7.3
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		–
WP cron:		
Language:		en_US
Server environment
Server info:		Apache
PHP version:		5.6.30
PHP post max size:		8 MB
PHP time limit:		800
PHP max input vars:		1000
cURL version:		7.53.1, OpenSSL/1.0.1e
SUHOSIN installed:		–
MySQL version:		5.6.35
Max upload size:		8 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		 Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument:		
GZip:		
Multibyte string:		 Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote post:		
Remote get:		
Database
WC database version:		2.6.14
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 /xxxxxxxxxx/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (4)
PrintAura WooCommerce API	 	by Print Aura – 3.3.0
Remove Comment Website/URL Box	 	by Mark Hodder – 1.0
WooCommerce	 	by Automattic – 3.0.0
WPS Hide Login	 	by Remy Perona for WPServeur – 1.1.7
Settings
API enabled:		
Force SSL:		–
Currency		USD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
WC pages
Shop base:		#18 - /
Cart:		#19 - /cart/
Checkout:		#20 - /checkout/
My account:		#21 - /my-account/
Theme
Name:		Storefront Child
Version:		2.1.8
Author URL:		
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
</details>

**Comment by mikejolley** [comment]
Main category screen? product screen? Checked both - no issues.

**Comment by sixTeamMooses** [comment]
happens on main category screen
i *think* its conflicting w the printaura api plugin
 if that's the case will have to downgrade regardless

**Comment by mikejolley** [comment]
Thats working. I think you have a javascript conflict. In chrome, View > Developer > Javascript console. Should shown an error.
