### ISSUE TITLE
Downloadable Products: If product comes with several links to download files, only one of them is being downloaded upon purchasing the product

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#14063]
**TESTING ENVIRONMENT:**

- Pressable Site
- Theme: Twenty Sixteen
- WooCommerce 3.0
- Stripe 3.1.6

**PRODUCT SETUP:**

![](https://cloudup.com/cq2pFRIRpOp+)
Image Link: https://cloudup.com/cq2pFRIRpOp

**WHAT I EXPECT:**

Each of the 3 files available to download upon purchasing the product.

**WHAT HAPPENS INSTEAD:**

Each file link is clickable upon purchasing the product and files could be downloaded. But despite the fact that each of the links supposed to link to a different pdf file, the same document gets downloaded (the 1st one):

http://g.recordit.co/yOG52ucSQY.gif

**Comment by claudiosanches** [comment]
Already reported and fixed:

https://github.com/woocommerce/woocommerce/issues/13923
https://github.com/woocommerce/woocommerce/pull/13983

Thanks for report it.
