### ISSUE TITLE
Calls to undefined methods in /includes/legacy/abstract-wc-legacy-product.php

### ISSUE THREAD

**Issue by dumb** [woocommerce/woocommerce#14060]
After updating to 3.0, WooCommerce was exiting with `Fatal error: Call to undefined method WC_Abstract_Legacy_Product::sync() in /public_html/wp-content/plugins/woocommerce/includes/legacy/abstract-wc-legacy-product.php on line 538`

On line 538 of abstract-wc-legacy-product.php, within `variable_product_sync()` there's a reference to:
`self::sync( $product_id );`

but there is no `sync` function declared in the `WC_Abstract_Legacy_Product` class.

Also a couple of lines down on 541 there's this call:
`$this->read_product_data();`

which is also not declared anywhere in the class.

Commenting out these lines cleared the error, since`WC_Abstract_Legacy_Product::variable_product_sync()` doesn't seem to be called anywhere, but some people might be looking to use the deprecated action so might be worth fixing fwiw.

**Comment by mikejolley** [comment]
In master, I added an is_callable. Its in the variable classes; the method is just there for bw compat.
