### ISSUE TITLE
problem with price in products

### ISSUE THREAD

**Issue by bianqui149** [woocommerce/woocommerce#14065]
The price of the products is missing, Does not recognize get_price_html ().
I Was using 2.6 and updated 3.0, the single product.php look similar but product->get_price_html() not showing
![1491509714482screensave](https://cloud.githubusercontent.com/assets/22307049/24773783/d9b0b2fa-1aec-11e7-908e-975a45ba2101.png)

**Comment by mikejolley** [comment]
Re-save the product. it's missing variation prices. And make sure all variations have regular prices. 

Could also be affected by https://wordpress.org/support/topic/lost-all-variation-data-on-update/
