### ISSUE TITLE
Dissapeared taxes from shipping line

### ISSUE THREAD

**Issue by navasjuanramon** [woocommerce/woocommerce#14066]
### EXPLANATION OF THE ISSUE

After updating to WooCommerce 3.0, all taxes from shipping line, dissapeared.

The Total from orders is correct, but if yoy resend any email to client, total order is recalculated and misses the old dissapeared taxes from shipping line.

Maybe the name of the product can be a variable.

### STEPS TO REPRODUCE THE ISSUE

Product titles: 
**Book "WooCommerce basics guide"**
**Book WooCommercé basics guide**

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://localhost/woocommerce
Site URL: http://localhost/woocommerce
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.28
PHP Version: 5.6.28
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Tu servidor no tiene la clase SoapClient habilitada - puede que algunos plugins de puerta de enlace que utilizan SOAP no funcionen como se espera.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Hide errors from visitors: ❌Los mensajes de error no deberían mostrarse a los visitantes.

### Active Plugins (1) ###

WooCommerce: por Automattic – 3.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Base de la tienda: #6 - /productos
Carrito: #7 - /carrito
Finalizar compra: #8 - /finalizar-compra
Mi cuenta: #9 - /mi-cuenta

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: : Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
In this test I had taxes still:

![2017-04-06 at 21 25](https://cloud.githubusercontent.com/assets/90977/24774124/a989e8bc-1b0f-11e7-87b8-4ff64a496cf3.png)

Next better examples.

**Comment by navasjuanramon** [comment]
Try with this name of products, with double commas **" "** or accent **é**, line:

- Book "WooCommerce basics guide"
- Book WooCommercé basics guide

**Comment by mikejolley** [comment]
What does that have to do with taxes.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14067

**Comment by navasjuanramon** [comment]
This scenario:

![2017-04-06 22_40_54-woocommerce settings tu manual de psicotecnicos wordpress](https://cloud.githubusercontent.com/assets/26978267/24775206/213ad7d4-1b1c-11e7-8529-fbfb31b29ae3.png)

Order before:

![2017-04-06 22_46_26-edit order tu manual de psicotecnicos wordpress](https://cloud.githubusercontent.com/assets/26978267/24775238/3b0f255c-1b1c-11e7-9d9b-c79fd8c63bf5.png)

Order after update to 3.0:

![2017-04-06 22_54_21-edit order tu manual de psicotecnicos wordpress](https://cloud.githubusercontent.com/assets/26978267/24775248/464b4ef0-1b1c-11e7-8c52-9fa697bf4d1d.png)

The system is the same from the initial message.

Anything I can do to help?

**Comment by navasjuanramon** [comment]
Maybe I miss relevant info, the missing taxes are from old orders, that were before upgrade.

Sorry and thanks.
