### ISSUE TITLE
Can't add or edit coupon

### ISSUE THREAD

**Issue by huitingyu** [woocommerce/woocommerce#14073]
After Woocommerce 3.0 update, when I click on add coupon or tries to edit an existing coupon, I get an error saying "Exception Throw invalid order"

### STEPS TO REPRODUCE THE ISSUE

1. Go to WooCommerce->Coupons
2. click on add coupon or click on any existing coupon for edit
3. Get the Exception Throw invalid order

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: http://www.secretbb.com
Site URL: http://www.secretbb.com
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 64 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (32) ###

Polylang: by Frédéric Demarle – 2.1.2
All In One SEO Pack: by Michael Torbert – 2.3.12.2.1
Black Studio TinyMCE Widget: by Black Studio – 2.3.1
Contact Us Form: by Kenmore Design LLC – 1.2
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.19
Font: by Paweł Misiurski – 7.5.1
Google Language Translator: by Rob Myrick – 5.0.30
Homepage Control: by WooThemes – 2.0.2
Instagram image gallery: by Iconosquare – 1.0.8
Jetpack by WordPress.com: by Automattic – 4.8.1
Lingotek Translation: by Lingotek and Frédéric Demarle – 1.2.6
Meteor Slides: by Josh Leuze – 1.5.6
Meta Slider: by Matcha Labs – 3.5
NextGEN Gallery Voting: by Shaun Alberts – 2.7.6
OptinMonster API: by Thomas Griffin – 1.1.6.2
Perfect WooCommerce Brands: by Alberto de Vera Sevilla – 1.4.4
Simple Lightbox: by Archetyped – 2.6.0
Social Icons: by ThemeGrill – 1.5.0
Storefront Footer Bar: by WooThemes – 1.0.3
Storefront Site Logo: by Wooassist – 1.2.2
Tidio Chat: by Tidio Ltd. – 3.0.2
Stamps.com WooCommerce Extension (USPS): by WooForce – 1.6.9
Woocommerce All Discounts: by ORION – 1.0
Woo Email Control: by Ian Young – 1.061
USPS (BASIC) WooCommerce Shipping: by WooForce – 1.1.6
WooCommerce - All in One SEO Pack: by Visser Labs – 1.3.4
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
Booster for WooCommerce: by Algoritmika Ltd – 2.6.0
WooCommerce Social Media Share Buttons: by Toastie Studio – 1.3.0
WooCommerce: by Automattic – 3.0.0
WP Mail Logging: by Christian Zöller – 1.8.0
NextGEN Gallery: by Imagely – 2.2.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /index.php/shop/
Cart: #5 - /index.php/cart/
Checkout: #6 - /index.php/checkout/
My account: #7 - /index.php/my-account/

### Theme ###

Name: estore Child
Version: 1.0.0
Author URL: http://secretbb.com
Child Theme: ✔
Parent Theme Name: eStore
Parent Theme Version: 1.1.5 – 1.1.6 is available
Parent Theme Author URL: https://www.themegrill.com
WooCommerce Support: ✔

### Templates ###

Overrides: estore/woocommerce/archive-product.php
estore/woocommerce/cart/cart-totals.php
estore/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
estore/woocommerce/checkout/form-billing.php
estore/woocommerce/checkout/form-checkout.php
estore/woocommerce/checkout/form-login.php
estore/woocommerce/content-product.php
estore/woocommerce/content-single-product.php
estore/woocommerce/global/wrapper-end.php
estore/woocommerce/global/wrapper-start.php
estore/woocommerce/loop/add-to-cart.php
estore/woocommerce/loop/price.php
estore/woocommerce/loop/rating.php
estore/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
estore/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
estore/woocommerce/single-product.php
estore/woocommerce/taxonomy-product_cat.php

Outdated Templates: ❌Learn how to update
`

**Comment by claudiosanches** [comment]
Working just fine for my.
And any of the plugins that you are using could cause `Exception Throw invalid order`, without the entire error message it's impossible to know where it comes from.
Closing since do not sounds like an issue on WooCommerce.
