### ISSUE TITLE
Page is constant refreshing after update to 3.0

### ISSUE THREAD

**Issue by mlichtronix** [woocommerce/woocommerce#14077]
### EXPLANATION OF THE ISSUE

Page is constant refreshing after update to version 3.0.
(Chrome and Firefox tested)

### STEPS TO REPRODUCE THE ISSUE

..update woocommerce to 3.0 by WP updates.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://foobar.sk
Site URL: http://foobar.sk
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sk_SK

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 48 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 48 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: lkzoat
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Regenerate Thumbnails: Alex Mills (Viper007Bond) – 2.2.6
WooCommerce: Automattic – 3.0.0
WP Statistics: Greg Ross & Mostafa Soufi – 12.0.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #7 - /
Košík: #8 - /kosik/
Pokladňa: #9 - /kontrola-objednavky/
My account: #10 - /moj-ucet/

### Theme ###

Name: Vantage Premium
Version: 2.5.4
Author URL: https://siteorigin.com/
Child Theme: ❌ – Ak upravujete WooCommerce alebo nadradenú tému
ktorej autorom nie ste vy
odporúčame vám použiť radšej odvodenú tému. Prečítajte si návod Ako vytvoriť odvodenú tému.

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by claudiosanches** [comment]
Already reported and fixed: Page is permanently reloading
Thanks for report.
