### ISSUE TITLE
`woocommerce_cross_sells_columns` filter dropped

### ISSUE THREAD

**Issue by jconroy** [woocommerce/woocommerce#14087]
Hi Guys,

Just doing some theme compat. Looks like the `woocommerce_cross_sells_columns` filter was dropped here: https://github.com/woocommerce/woocommerce/commit/76b32c9aa52ebac70fe5a60a8d56351218760471#diff-7c7fde532a1aa97c8e3c2c7b78f02103L41

But the equivalent didn't make it into the `woocommerce_cross_sell_display()` function 

https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L1386

Other filters like `woocommerce_cross_sells_total` are there.

Let me know if I have simply missed a new/better way to override that value.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/14096

**Comment by korywakefield** [comment]
Filtering `woocommerce_cross_sells_columns` doesn't seem to have any effect on the output. Others such as `woocommerce_cross_sells_total` appear to be working appropriately, but I am unable to affect the column count.
