### ISSUE TITLE
Unable to set product Image and Unable to Add New Product Category and search function not working in mobile but working in laptop

### ISSUE THREAD

**Issue by NaveenKollu** [woocommerce/woocommerce#14086]
### EXPLANATION OF THE ISSUE

 I have recently upgraded to woocommerce 3.0.0 . From then I am unable to set product image and Add images to product gallary and Unable to ass New Product category.

and Also Search function is not working in mobile but working in laptop
 
### STEPS TO REPRODUCE THE ISSUE

1. Add new product
2. Select product image 
3. Nothing will be added
4.Add images to product gallery
5.Nothing is added
6.Add New category
7.Nothing is Added
8.Search products in mobile
8. No results shown
9. website https://atoz.firm.in

**Comment by mikejolley** [comment]
JavaScript conflict with an extension. 3.0.1 may help as it wraps some of our scripts in try/catch blocks, but ideally you need to find the conflict and remove the extension/get an update from the author.

**Comment by NaveenKollu** [comment]
Hi ,

Thanks for response. But search is there from the begining. It is working
in laptop but not in mobile

**Comment by mikejolley** [comment]
Caching plugins?

**Comment by NaveenKollu** [comment]
Hi ,

Did you get the chance to check the website https://atoz.firm.in . Which
Plugin I should install to get serch worked in mobile.

**Comment by mikejolley** [comment]
Yeah the search is working my side.
