### ISSUE TITLE
Need a way to get the ID of the lowest-priced variation

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#14083]
While you can get the price of the minimum variation via `$product->get_variation_price('min')` if the minimum variation is a name our price variation, I'd like to be able to change the price string. Currently, there seems to be no way to do this other than to filter `woocommerce_get_variation_price` and sort through the array keys of `$product->get_variation_prices()`. 

I think ideally the `woocommerce_get_variation_price` filter would include the ID of the variation whose price is being returned by the filter.

**Comment by mikejolley** [comment]
You can use `woocommerce_get_variation_price` - you can use the method we're using:

`
	$prices = $this->get_variation_prices( $include_taxes );
`

Get the array of prices you want, get the first element (cheapest) then look at it's key. I don't want to pass around extra ids to this filter in case we need to change the logic in a future version. Better to work with what is there already IMO.
