### ISSUE TITLE
Blank Product Screen after Update

### ISSUE THREAD

**Issue by marc1na** [woocommerce/woocommerce#14084]
I just updated to the most recent version of Woocommerce and now the product pages only show the top breadcrumbs. The rest of the page and all CSS style on the page is blank. 

http://grassrootsmeats.com/product/mountain-man-beef-special/

Please let me know what is going on. Thank you.

**Comment by claudiulodro** [comment]
```<b>Fatal error</b>:  Uncaught Error: Call to undefined function get_the_post_thumbnail_url() in /home/taylor1/public_html/wp-content/plugins/woocommerce/templates/single-product/product-image.php:49
Stack trace:
#0 /home/taylor1/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(203): include()
#1 /home/taylor1/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php(839): wc_get_template('single-product/...')
#2 /home/taylor1/public_html/wp-includes/class-wp-hook.php(298): woocommerce_show_product_images('')
#3 /home/taylor1/public_html/wp-includes/class-wp-hook.php(323): WP_Hook-&gt;apply_filters(NULL, Array)
#4 /home/taylor1/public_html/wp-includes/plugin.php(453): WP_Hook-&gt;do_action(Array)
#5 /home/taylor1/public_html/wp-content/plugins/woocommerce/templates/content-single-product.php(48): do_action('woocommerce_bef...')
#6 /home/taylor1/public_html/wp-includes/template.php(686): require('/home/taylor1/p...')
#7 /home/taylor1/public_html/wp-content/plugins/woocommerce/includes/wc-core- in <b>/home/taylor1/public_html/wp-content/plugins/woocommerce/templates/single-product/product-image.php</b> on line <b>49</b><br />
```

Fatal error. You can see it if you "View Source" on the page. I'll have to investigate and see if it's a bug, but that function should be defined since it's a standard WP function.

**Comment by marc1na** [comment]
Yes, but I have no idea how to fix it. I deleted all plugins and switched to the default WP theme and it still happens.

**Comment by jeffrimko** [comment]
Seeing a similar issue. Haven't done much debugging yet but the issue we are seeing has something to do with WC thinking there are more products in a category than there actually are. Here is the behavior we are seeing:

- We have a category with 17 active products. 
 - The WC store page for that category is showing that 20 products are found.
 - The store pages shows 12 items per page by default. The first page displays okay but the second page is blank.
  - If we change the number of items per page to 17, the first displays correctly. However, if we change it to 18, the page does not display correctly. Seems like WC might be trying to load a product that doesn't exist (or something similar) and is throwing an error which causes the page to be blank.

Pretty strange! Not sure why WC thinks there are 3 extra products. Not sure if it is the same issue reported by OP but hope it can help.

**Comment by mikejolley** [comment]
Not seeing it now. Resolved?

@jeffrimko Ensure the data update ran. It sounds like some hidden products are missing the product_visibility taxonomy so they are queried, but not output. Unrelated to the OP.

**Comment by marc1na** [comment]
No, I had to switch back to Woocommerce 2.6 to get the store back online. No clean install worked.. I didn't have any hidden products - ALL Products would not show.
