### ISSUE TITLE
after 3.0 update pagination not going to next page

### ISSUE THREAD

**Issue by 24sevenproweb** [woocommerce/woocommerce#14082]
### EXPLANATION OF THE ISSUE

We upgraded to version 3.0 yesterday and now when clicking on the next button or on a page number to go to a different page to view more products in a category it does not go to the new page it just reloads and the first page is shown again.  I am removing the pagination on most of the pages for now because no one can view products after the other pages but would like to know if there is a way to fix it.

### STEPS TO REPRODUCE THE ISSUE

go to our site http://24sevenpro.com/musical-acts/
go to bottom of page and click on any of the page numbers or arrows to go to the next page

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://24sevenpro.com
Site URL: http://24sevenpro.com
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 16 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: w_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (22) ###

Advanced Post Types Order: by Nsp Code – 3.9.6
Akismet Anti-Spam: by Automattic – 3.3
Activity Log: by Yakir Sitbon
Maor Chasen
Ariel Klikstein – 2.3.4

Bloom: by Elegant Themes – 1.1.8
Breadcrumb NavXT: by John Havlik – 5.6.0
Contact Form 7 Datepicker: by Aurel Canciu – 2.6.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Display All Image Sizes: by Press Up – 1.1.5
Duplicator: by Snap Creek – 1.2.2
Woocommerce - Request a Quote: by Kiran P – 2.43
Elegant Themes Updater: by Elegant Themes – 1.2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.6
Loginizer: by Raj Kothari – 1.3.4
Net-Results Marketing Automation: by Net-Results Marketing Automation – 2.1
Ninja Forms: by The WP Ninjas – 3.0.31
Virtual Robots.txt: by Marios Alexandrou – 1.8
Shortcode Pagination for WooCommerce: by James Kemp – 1.0.5
Simple 301 Redirects: by Scott Nellé – 1.07
User Role Editor: by Vladimir Garagulya – 4.32.3
WooCommerce: by Automattic – 3.0.0
Yoast SEO: by Team Yoast – 4.5
WP Smush: by WPMU DEV – 2.6.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: #81 - /my-account/

### Theme ###

Name: 24seven
Version: 1.0
Author URL: http://www.24sevenpro.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.40
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
> Shortcode Pagination for WooCommerce: by James Kemp – 1.0.5

^ this plugin outputs your pagination.

**Comment by 24sevenproweb** [comment]
Thanks for the quick response.  Looks like this update killed several more of the plugin's I have
