### ISSUE TITLE
New products, don't show at top of product List

### ISSUE THREAD

**Issue by AntBentinck** [woocommerce/woocommerce#14080]
### EXPLANATION OF THE ISSUE

Latest Version of Wordpress & WooCommerce (3.0). This may have been fixed already but as Yoast gave us a fix for their plugin (beta) we are now able to add products.

I duplicated a product and edited it as it has similar attributes etc but upon saving its not at the top of the list like new products used to be.

Side Note: The products can still be found by searching by category or product name.

### STEPS TO REPRODUCE THE ISSUE

- Duplicate a product.
- Make Edits.
- Save/Publish
- Refresh Products Sections  

### SYSTEM STATUS

<details>

Unfortunately, we are still seeing a empty grey box on system report accompanied by a 503 in the console. Sorry! 

</details>

**Comment by AntBentinck** [comment]
Additional notes: The duplicated (new) products also do not show on the "New Products" widget.

**Comment by claudiosanches** [comment]
Sorting setting in admin?
Or maybe related to https://github.com/woocommerce/woocommerce/issues/14072 ?
If is duplicating and using a old date, for sure will be an issue to the sorting order.

**Comment by mikejolley** [comment]
The fix for https://github.com/woocommerce/woocommerce/issues/14072 fixes this too.

**Comment by AntBentinck** [comment]
Published on: 18 Oct 2016 @ 17:55 - You were correct! Thanks.
