### ISSUE TITLE
Undefine index : position

### ISSUE THREAD

**Issue by jameshwartlopez** [woocommerce/woocommerce#14085]
### EXPLANATION OF THE ISSUE
Error when upgrading woocommerce manually
Notice: Undefined index: position in ...........woocommerce\includes\data-stores\class-wc-product-data-store-cpt.php on line 371

I have a local site that i manually upgraded from version 2.6.14 to version 3.0.1

### STEPS TO REPRODUCE THE ISSUE

1. I have downloaded woocommerce via https://github.com/woocommerce/woocommerce/archive/3.0.1.zip
2. In the plugin directory i have deleted the woocommerce folder then extracted the zip file above. After extraction folder name should be woocommerce-3.0.1
3. Rename woocommerce-3.0.1 to woocommerce
4. Open product list 
### SYSTEM STATUS

<details>

WordPress environment
Home URL:		http://localhost/vend
Site URL:		http://localhost/vend
WC version:		3.0.1
Log directory writable:		 G:\xampp\htdocs\vend/wp-content/uploads/wc-logs/
WP version:		4.7.3
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		
WP cron:		
Language:		en_US
Server environment
Server info:		Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/7.0.13
PHP version:		7.0.13
PHP post max size:		8 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.51.0, OpenSSL/1.0.2h
SUHOSIN installed:		–
Max upload size:		2 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		 Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		2.6.14
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 G:\xampp\htdocs\vend/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		Error messages should not be shown to visitors.
Active plugins (2)
linksync for WooCommerce	 	by linksync – 2.4.17
WooCommerce	 	by Automattic – 3.0.1
Settings
API enabled:		
Force SSL:		–
Currency		GBP (£)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
WC pages
Shop base:		 Page not set
Cart:		 Page not set
Checkout:		 Page not set
My account:		 Page not set
Theme
Name:		Twenty Seventeen
Version:		1.0 – 1.1 is available
Author URL:		https://wordpress.org/
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Overrides:	 	–
</details>

**Comment by marc1na** [comment]
Weird since I didn't update it manually but through the WP backend automatically. Will this wipe out my products and data?

**Comment by jameshwartlopez** [comment]
No it wouldn't it will just show a bunch of notice from class-wc-product-data-store-cpt.php on line 371. This will show if debug is on which i usually set to on when developing something or testing something.

**Comment by marc1na** [comment]
I followed your steps and the problem persisted. Not sure what the issue is since I restored a brand new version of Woocommerce. So, I went ahead and just restored the old version of woocommerce and it is working.

 

I don't seem able to upgrade at this time. Perhaps there is an issue since the hosting company doesn't have MYSQL 5.6?

 

THank you for the help,

Marcy

**Comment by linksyncjameshwartlopez** [comment]
Hi @marc1na for my case the error is gone after turning debug on and off. It looks like the previous meta attributes i have in my local database dont have position on it but fix by woocommerce automatically after some page load.

**Comment by jameshwartlopez** [comment]
Hi @marc1na for my case the error is gone after turning debug on and off. It looks like the previous meta attributes i have in my local database dont have position on it but fix by woocommerce automatically after some page load.

**Comment by mikejolley** [comment]
@jameshwartlopez yeah looks like some data was missing and was corrected automatically. I'll add some additional checking.

**Comment by jameshwartlopez** [comment]
Thanks for that @mikejolley

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/14097
