### ISSUE TITLE
Template version question

### ISSUE THREAD

**Issue by colmtroy** [woocommerce/woocommerce#14095]
3.0.1 included some updates to templates
e.g.
https://github.com/woocommerce/woocommerce/commit/ca85b55a611189c94059e275e4690eaa051bf6d9

As far as I can see - nothing else in the template changed.
@mikejolley - per your comment here
https://github.com/woocommerce/woocommerce/issues/14020#issuecomment-292140919

My understanding is/was that template version numbers reflect the version the template was last updated - not the current version - but looking at the commit history for content-product.php it looks like no changes were made to the file in 3.0.0 or 3.0.1 (other than the aforementioned version increment) and the last actual change to the file was in July 2016.
https://github.com/woocommerce/woocommerce/commits/3.0.1/templates/content-product.php

I know you guys are doing stellar work and have enough on your plate this week, but we spent a few weeks pre the release of 3.0.0 to ensure our themes were up to date with no issues re: template overrides being out of date etc. and just a few days after the release of 3.0.0 we have an influx of customers wondering why our theme is now out of date (even though we followed the beta release cycle closely). And from what I can see this template update doesn't look to match with the logic of why the version number should be incremented. 

So now we're back to square one and have to start the update process for all our WooCommerce themes again - argh! Just wondering if I'm missing something here re: rationale for the version number update? 

p.s. congrats again on the 3.0 release - it's clear that a huge amount of work went into the release - well done to everyone involved.

**Comment by mikejolley** [comment]
@colmtroy These template files had changes in 3.0.0 from 2.6.14, but a user pointed out the template version had not been bumped. Compare to the 2.6.14 version and you'll see the changes you're missing.

Also, as a theme dev, if you can do your themes **without** overriding templates that would be better. Use the action hooks where possible - then you won't have to deal with this ever again.

Also, if you are copying templates into your theme which do not need modification, don't. Be selective.

**Comment by colmtroy** [comment]
@mikejolley - thanks for the reply.
Re: not using overrides - yip hear you loud and clear! These are legacy themes nearly 3 years old before we knew better :) (and we're slowly removing all overrides from them in favour of action hooks). 

I see legit changes now in single-product/up-sells.php and /loop/result-count.php - but still don't see what changed in content-product.php - hence my question.

Also, I don't think /loop/result-count.php was called out on the changelog - might be worth updating it.

Thanks Mike!
