### ISSUE TITLE
Add to cart by using ajax fails

### ISSUE THREAD

**Issue by ersinpw** [woocommerce/woocommerce#14093]
After updating the database, I can't add products by using ajax.

This is how my ajax (post)request looks like:
`?wc-ajax=add_to_cart&attribute_pa_type=type1&variation_id=1075&quantity=1&add-to-cart=8`

After update I got this:
```
{
 error: true,
 product_url: "https://www.domain.com/"
}
```

This is the exact error:
`PHP Notice:  Undefined index: product_id in woocommerce/includes/class-wc-ajax.php on line 357`

I tried to add product_id in my request, but fortunately I still got the same response

**Comment by ersinpw** [comment]
Hmm, I also get an error when I try to edit a product
Same error as them: https://wordpress.org/support/topic/help-new-update-screwed-up/

**Comment by mikejolley** [comment]
We use this AJAX endpoint in our loops and it works. Really, you should only be using OUR ajax endpoint if you use it identically to core. It does not support variations and it expects product_id.

`
$product_id        = apply_filters( 'woocommerce_add_to_cart_product_id', absint( $_POST['product_id'] ) );
`

Make your own endpoint if you need something custom.
