### ISSUE TITLE
Additional paragraphs in shortcodes in WC 3.0.1

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce#14098]
### EXPLANATION OF THE ISSUE

Hi, I'm using WooCommerce 3.0.1 and [displaying a featured products shortcode on a shop page](https://themedemos.webmandesign.eu/monument-valley/shop/). As you can see there are empty spaces in the displayed featured products, unlike the rest of the products below.

I had no issue with this with previous major WC version 2.6.##. This was also fine with WC 3.0.0 (however, there were no featured products displaying after a plugin update, so I had to set them manually again...). Yesterday I've updated WC to 3.0.1 and that's when I've noticed the gaps in shortcode output.

On my test server I have WC 3.0.0 installed still and it is working fine, without gaps, so indeed, there must have been some change in WC 3.0.1

Also, it seems this issue is only appearing on shop page as on [other page](https://themedemos.webmandesign.eu/monument-valley/home/home-2/) the layout of featured products is fine.

I've also tried with TwentySeventeen theme and the issue still persist.

### STEPS TO REPRODUCE THE ISSUE

Just add a `[featured_products]` shortcode into the shop page content.

**Comment by mikejolley** [comment]
No changes to shortcodes: https://github.com/woocommerce/woocommerce/compare/3.0.0...3.0.1

No whitespace:

![2017-04-07 at 11 19](https://cloud.githubusercontent.com/assets/90977/24796233/1210cf3a-1b84-11e7-9bae-8303eec4361b.png)

In the past I've seen this in themes which change wpautop hooks on the_content. This adds parragraphs if there is white space in the template file.

**Comment by webmandesign** [comment]
Hi Mark,

**Please reopen the ticket, the issue is not resolved.**

Here is my Shop page content: http://easycaptures.com/fs/uploaded/997/1455798126.png

And here is how it renders: https://www.dropbox.com/s/f6fblp0s9bxb8i6/wc-shop-page-shortcode-rendering-issue.jpg?dl=0

The screenshot is all just a single Shop page. **On the left** there is a Shop page content area displaying a featured products shortcode. You can see a lot of additional whitespace and markup added with WPAUTOP possibly. **On the right** is the same page scrolled down below the Shop page content area where the actual products are displayed. You can compare highlighted areas for differences. There is no additional markup there.

**Comment by webmandesign** [comment]
Also, I'm not changing `wpautop` in the theme in any way. My theme is [coded 100% according to WordPress best practices](http://themecheck.org/score/wordpress-theme-monument-valley.html).

I don't know then why it works with WC3.0.0 and not with WC3.0.1...

**Comment by webmandesign** [comment]
Also, I'm not modifying WC template files via the theme. I'm using hooks only.

**Comment by mikejolley** [comment]
Check the functions.php. I have come across this several times in the past with themes adding space to shortcodes. The_Content hooks are nearly always responsible. It has nothing to do with the template files in WC.

**Comment by webmandesign** [comment]
BTW, all those screenshots of mine are actually from TwentySeventeen. Unmodified...

**Comment by webmandesign** [comment]
Have you tried to set up the Shop page according to my screenshots to test?

**Comment by webmandesign** [comment]
Also, how you explain the fact it worked with WC3.0.0 and not with WC3.0.1 then?

**Comment by webmandesign** [comment]
I just tested with TwentySixteen and Storefront - the same story. So now I have the same issue on my own Monument Valley theme, TwentySeventeen theme, TwentySixteen theme and WooThemes Storefront theme. I really don't think this is a theme issue

**Comment by webmandesign** [comment]
To complete debugging info, I've disabled all the plugins except WooCommerce with no luck.

**Comment by mikejolley** [comment]
Calm down I'm looking :)

**Comment by mikejolley** [comment]
2017:
![2017-04-07 at 12 38](https://cloud.githubusercontent.com/assets/90977/24798709/39d96ab2-1b8f-11e7-8f33-4c785dcfb92d.png)

Do you see it? I don't see any BRs but let me know if you mean something else.

**Comment by webmandesign** [comment]
Sorry for all the comments before, they come up to me after I've posted previous one...

There is a misunderstanding here. I'm not talking about using `[featured_products]` on a standard page/post as in your screenshot. I'm adding this shortcode into the Shop page (the page set for **WooCommerce > Settings > Products > Display > "Shop page"**) content so I get featured products displayed first and then all the others below.

[As mentioned in my previous comment](#issuecomment-292507822), here is my Shop page content to test: 

![Setting up a WooCommerce shop page content](http://easycaptures.com/fs/uploaded/997/1455798126.png)

You can see in the screenshot I'm editing the actual WooCommerce shop page (there is "This is the WooCommerce shop page. The shop page is a special archive..." notification on top).

I've mentioned this in the original issue description too.

**Comment by webmandesign** [comment]
Hi Mike, any update on this? Did you tested on actual shop page?

**Comment by mikejolley** [comment]
We have a fix in 3.0.2

**Comment by webmandesign** [comment]
Cool, thank you for the update and the fix!
