### ISSUE TITLE
Woocommerce 3.0.1 doesn't save "Downloadable files"

### ISSUE THREAD

**Issue by Track77** [woocommerce/woocommerce#14104]
### EXPLANATION OF THE ISSUE

Woocommerce 3.0.1 doesn't save "Downloadable files" with url like "/download-manager.php?id=14"

### STEPS TO REPRODUCE THE ISSUE

1) Create downloadable simple product
2) Add file with some name and url like  "/download-manager.php?id=14"
http://clip2net.com/s/3Jibylb
3) Save product
4) Fields "Downloadable files" is empty

### SYSTEM STATUS

<details>

`Note: http://3ddkstudio.com - this is a site on my local computer.

### WordPress Environment ###

Home URL: http://3ddkstudio.com
Site URL: http://3ddkstudio.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.14
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.7.16
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (62) ###

Custom Admin-Bar Favorites: by Robert Wise – 0.1
Admin Menu Editor: by Janis Elsts – 1.7.3
BackUpWordPress: by Human Made Limited – 3.6.3.1
Basic User Avatars: by Jared Atchison – 1.0.3
bbP Live Preview: by r-a-y – 0.1
bbP Toolkit: by Pascal Casier – 1.0.10
bbPress - Live Topic Suggestions: by Hudson Atwell,japh,salbahra – 1.1.0
bbPress Advanced Statistics: by Jake Hall – 1.4.4.1
bbPress Notify (No-Spam): by Vinny Alves (UseStrict Consulting) – 1.15.4
bbPress Permalinks Advanced: by  – 1.0.0
bbPress: by The bbPress Community – 2.5.12
Buddy-bbPress Support Topic: by G3ronim0 – 2.1.3
Crop Thumbnails: by Volkmar Kantor – 0.10.12
Custom Taxonomy Order NE: by Marcel Pol – 2.8.3
Dashboard Post-it: by Mark Dingemanse – 1.1
Disable Embeds: by Pascal Birchler – 1.3.0
Display All Image Sizes: by Press Up – 1.1.5
Advanced Download Counter: by Andy Staines – 1.3
Duplicate Post: by Enrico Battocchi – 3.2
Enhanced Media Library: by wpUXsolutions – 2.4.4
Flexible FAQ: by S. Bage – 0.2
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
Google Video Sitemap Feed With Multisite Support: by Art Project Group – 1.8.1
Hierarchical HTML Sitemap: by Alexandra Vovk – 1.1
Image Upload for BBPress: by Potent Plugins – 1.1.14
Lazy Load for Videos: by Kevin Weber – 2.2.3
Link Library: by Yannick Lefebvre – 5.9.15.15
Log Deprecated Notices: by Andrew Nacin – 0.4
My Link Order: by Andrew Charlton – 4.3
New User Email Setup: by Alex Cragg – 0.5.2
Feed by Mail Extension for Newsletter: by Stefano Lissa – 2.2.0
Newsletter Reports Extension: by Stefano Lissa – 2.2.2
Newsletter: by Stefano Lissa & The Newsletter Team – 4.6.4
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Plugin Groups: by David Cramer  – 1.1.0
Plugin Notes: by Mohammad Jangda – 1.6
Post Tags and Categories for Pages: by curtismchale – 1.3
WooCommerce Product Filter: by Mihajlovic Nenad – 6.1.1
Quick Alt Editor: by Arsmoon – 1.0.1
Redirection: by John Godley – 2.5
Relevanssi: by Mikko Saari – 3.5.8
Search Regex: by John Godley – 1.4.16
To-Dos: by Johan Ström (Updated: Alex Kramer) – 1.2
Ultimate Tag Cloud Widget: by Rickard Andersson – 2.7.2
User Role Editor: by Vladimir Garagulya – 4.32.3
User Switching: by John Blackbourn – 1.0.9
WCP Contact Form: by Webcodin – 3.1.0
WooCommerce Bulk Discount: by Rene Puchinger – 2.5.2
WooCommerce Cross-Sale Discount: by Alex Kramer – 0.2
WooCommerce Currency Converter Widget: by Alexander Kramer – 0.5.0
WooCommerce Custom Product Tabs Lite: by SkyVerge – 2.2.5
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2
WooCommerce Sales by Country: by MH Mithu – 1.5
WooCommerce Sales By Location Report: by ChuckMac Development – 1.3.1
WooCommerce: by Automattic – 3.0.1
Yoast SEO Premium: by Team Yoast – 4.5
WP Easy Uploader: by Chris Jean – 1.0.11
Media Library Categories: by Jeffrey-WP – 1.5.4
WP-PostViews: by Lester 'GaMerZ' Chan – 1.75
WP User Frontend: by Tareq Hasan – 3.3.3
YITH WooCommerce Review Reminder: by YITHEMES – 1.3.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #65 - /shop/
Cart: #66 - /cart/
Checkout: #67 - /checkout/
My account: #68 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.2
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart\cart-empty.php
flatsome/woocommerce/cart\cart.php
flatsome/woocommerce/checkout\form-checkout.php
flatsome/woocommerce/checkout\form-coupon.php
flatsome/woocommerce/checkout\thankyou.php
flatsome-child/woocommerce/content-product.php
flatsome-child/woocommerce/content-product_cat.php
flatsome-child/woocommerce/content-single-product.php
flatsome-child/woocommerce/content-widget-product.php
flatsome-child/woocommerce/emails\email-header.php
flatsome-child/woocommerce/emails\email-styles.php
flatsome-child/woocommerce/global\breadcrumb.php
flatsome/woocommerce/global\quantity-input.php
flatsome/woocommerce/global\wrapper-end.php
flatsome/woocommerce/global\wrapper-start.php
flatsome/woocommerce/loop\loop-end.php
flatsome/woocommerce/loop\loop-start.php
flatsome/woocommerce/loop\orderby.php
flatsome/woocommerce/loop\pagination.php
flatsome/woocommerce/loop\result-count.php
flatsome/woocommerce/loop\sale-flash.php
flatsome-child/woocommerce/myaccount\downloads.php
flatsome-child/woocommerce/myaccount\form-edit-address.php
flatsome-child/woocommerce/myaccount\form-login.php
flatsome/woocommerce/myaccount\navigation.php
flatsome/woocommerce/notices\error.php
flatsome/woocommerce/notices\notice.php
flatsome/woocommerce/notices\success.php
flatsome/woocommerce/product-searchform.php
flatsome-child/woocommerce/single-product\add-to-cart\external.php
flatsome-child/woocommerce/single-product\add-to-cart\grouped.php
flatsome-child/woocommerce/single-product\add-to-cart\simple.php
flatsome-child/woocommerce/single-product\add-to-cart\variable.php
flatsome-child/woocommerce/single-product\add-to-cart\variation-add-to-cart-button.php
flatsome-child/woocommerce/single-product\meta.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product\photoswipe.php
flatsome-child/woocommerce/single-product\price.php version 2.4.9 is out of date. The core version is 3.0.0
flatsome-child/woocommerce/single-product\product-image.php
flatsome-child/woocommerce/single-product\product-thumbnails.php
flatsome-child/woocommerce/single-product\rating.php
flatsome-child/woocommerce/single-product\related.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product\review.php
flatsome/woocommerce/single-product\sale-flash.php
flatsome/woocommerce/single-product\share.php
flatsome/woocommerce/single-product\short-description.php
flatsome/woocommerce/single-product\tabs\tabs.php
flatsome-child/woocommerce/single-product\title.php
flatsome/woocommerce/single-product\up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
Invalid file path. use the full absolute path.

**Comment by mikejolley** [comment]
And it's a .php file - this is not a supported mime type for downloadable files. Doing so would be a security risk.

You could add this type of functionality with a shortcode based download path. Thats how the amazon downloadable files extension works.
