### ISSUE TITLE
 Product gallery

### ISSUE THREAD

**Issue by daoquangminh76** [woocommerce/woocommerce#14102]
Help me minimize images in Product gallery
example: http://windshiphangrussian.ml/san-pham/mat-na-sua-non-ba-gia-agafi

**Comment by mikejolley** [comment]
This theme will have an update soon.

https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox)-in-3.0.0
