### ISSUE TITLE
Username Fishing by Using Product Reviews usernames

### ISSUE THREAD

**Issue by gwgw** [woocommerce/woocommerce#14111]
### EXPLANATION OF THE ISSUE

WC Version: 3.0
Category: Security, Product Reviews

When we allow only registered users to write reviews for purchased product,
by default published review will show customer login username, and
this can be used for brute force attack, since attacker can see customer 
username from review.
Is there a way to exclude 'username' from dropdown menu: Display name publicly as

To be honest, when customers buys something on our website, in most cases they
provide much more information than username, like first and last name and adress

If we change username in reviews to first & last name this can prevent brute force attacts
on login page, using our customer username.

Sorry for my English

**Comment by DavidAnderson684** [comment]
WordPress's default setup allows username enumeration; the WP core devs do not consider usernames to be sensitive information. So, there's nothing different that WC is adding here. If you disagree and consider usernames secret information, then presumably you already deploy a plugin that blocks the already-existing-in-WP username enumeration mechanisms? You should ask developers of those plugins to look at this too, as I'd really doubt that the WC devs are going to modify WC core to block something that WP already allows in other ways by default/policy.

**Comment by mikejolley** [comment]
Our customer class actually sets display name to First Last when it comes through us, but other users registered through WordPress are not in our control. This is also the Wordpress commenting system so it's the same for regular comments and out of scope for WC to address.

You can modify the templates and remove `comment_author()` if you are concerned.

**Comment by gwgw** [comment]
Sorry to bother you with this, i just read a lot of security and 
different types
of attacks, and now i'm trying to secure my  website on localhost,
as tight as i can, before publishing.
I read that i can denied acces to urls with suffix ?author=1 via 
httaccess file,
and it works, so i was wondering is there a way to force users don't 
display their
login username anywhere

I've also secured website for brute force attacks with cerber plugin,
maybe i want secure everything to much, sorry for dumb subject
