### ISSUE TITLE
CSS: .hidden

### ISSUE THREAD

**Issue by tivnet** [woocommerce/woocommerce#14119]
The `<div class="quantity hidden">` :

https://github.com/woocommerce/woocommerce/blob/94628c2460623070302e16f92b9aaa3b7c7bcf9a/templates/global/quantity-input.php#L25

I am unable to locate the `.hidden` CSS entry.

**Comment by mikejolley** [comment]
The input is hidden so it does not matter.

**Comment by tivnet** [comment]
Well, almost :)

![image](https://cloud.githubusercontent.com/assets/1696330/24812046/922a4644-1b96-11e7-8acd-0c8f03a10018.png)

**Comment by tivnet** [comment]
Some nice themes (Avada in this case) do nice things... 

So, 
 
    .hidden {
		display: none;
    }

could be quite useful.

**Comment by claudiosanches** [comment]
There is the class, still there are free to complete override WooCommerce styles. Storefront for examples does it.
No to mention that we don't use the `+` and `-` elements since WooCommerce 2.3, so this theme requires update.
