### ISSUE TITLE
Payment/Order spinning

### ISSUE THREAD

**Issue by bwya77** [woocommerce/woocommerce#14112]
### EXPLANATION OF THE ISSUE

When someone tries to order on my site www.o365admin.center they can continue as it just spins 
Go to site and try to order something. Was working without issues on 3.0.0, upgraded to 3.0.1 and it broke. Tried to revert back and it doesnt work

jquery.js?ver=1.12.4:4 POST https://www.o365admin.center/checkout-2/?wc-ajax=update_order_review 403 (Forbidden)
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
update_checkout_action @ checkout.min.js?ver=3.0.0:1

**Comment by mikejolley** [comment]
Try a different payment gateway.

**Comment by bwya77** [comment]
Disabled WooCommerce Stripe Gateway and still same issue

**Comment by mikejolley** [comment]
yeah I see the 403 now. Try doing settings > permalinks save. If it does not resolve it would have to be a conflict with theme or plugin. This is not affecting other sites.

**Comment by mikejolley** [comment]
@bwya77 Any luck?

**Comment by Lamysnake** [comment]
Hi, 
I am receiving this same problem :( and I am loosing orders in my website please help!

**Comment by mikejolley** [comment]
See if you're running anything this user is https://wordpress.org/support/topic/wc-ajax-requests-return-403/ He isn't using 3.0 but has the same issue.

**Comment by patrix87** [comment]
Same issue here since the upgrade with only woocommerce running on default up to date superstore theme.

This shows up in the google chrome console when I click Calculate taxes or Calculate Total.
`

jquery.js?ver=1.12.4:4 POST https://taktikairsoft.com/wp-admin/admin-ajax.php 404 (Not Found)
send	@	jquery.js?ver=1.12.4:4
ajax	@	jquery.js?ver=1.12.4:4
calculate_tax	@	meta-boxes-order.js?ver=3.0.1:561
dispatch	@	jquery.js?ver=1.12.4:3
r.handle	@	jquery.js?ver=1.12.4:3
﻿

​`

**Comment by bwya77** [comment]
I was able to fix mine by clearing my HTACCESS file to 

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
# Fix 403 errors on existing directories; WordPress overrides.
RewriteCond %{REQUEST_URI} ^/(wordpress)/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . /index.php [L]
</IfModule>
# END WordPress

and then going to settings>permalinks and changing to Day and name

**Comment by patrix87** [comment]
Only thing is that I don't want to change to Day and name and I just spent the last hour trying to fix a 403 error with permalinks.

**Comment by bwya77** [comment]
I just changed it to Day and name because that what I used to have it as.
During troubleshooting I tried changing it as suggested above and got 403 as well

**Comment by mikejolley** [comment]
What changed in htaccess?

**Comment by bwya77** [comment]
Absolutely.no clue

**Comment by Lamysnake** [comment]
Thank you! Thanks a lot!! You are my HERO right now thank you

**Comment by Wegerich** [comment]
I am having the same problem at https://www.reagent-tests.uk

**Comment by bwya77** [comment]
Did you try my change listed above

**Comment by Wegerich** [comment]
Yes but I'm unable to change the permalink type. When I click "save changes" it refreshes to a 404 not found page. Refreshing again takes me to the permalink settings page and the settings are not changed.

I just updated to WooCommerce 3.0.1 but that did not solve the problem.

**Comment by Wegerich** [comment]
I have now manually changed my permalink URL in the phpMyAdmin interface and it has not fixed the issue even with the .htaccess stripped down to the suggested structure.

Do you have any idea what might have caused this feature to break? Maybe that can shed light on a more effective fix?

**Comment by patrix87** [comment]
Well... 
Changing permalink_structure to /%postname%/ in phpmyadmin
then in wp changing the permalink to Day and Name
then in wp chaning it back to Post Name

Worked.

But that is some weird stuff...

But it's wordpress so I'm not that suprised.

**Comment by Wegerich** [comment]
I have used the following snippet inserted into functions.php using the "editor" tool to disable this checkout verification for the time being but I really need a true fix
```

function so_27023433_disable_checkout_script(){
    wp_dequeue_script( 'wc-checkout' );
}
add_action( 'wp_enqueue_scripts', 'so_27023433_disable_checkout_script' );
```
