### ISSUE TITLE
Duplicate product does not duplicate custom meta data 

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#14118]
According to https://wordpress.org/support/topic/woocommerce-no-longer-carries-custom-field-information-when-duplicating-product/

**Comment by sherii20** [comment]
I am having same issue, product is not duplication custom fields data

**Comment by glenprimitivesense** [comment]
This has happened again, it won't carry across the data for custom fields upon duplicating

**Comment by glenprimitivesense** [comment]
Any news on this please

**Comment by willgorham** [comment]
@glenprimitivesense Already fixed for 3.2.2 here: #17242

**Comment by glenprimitivesense** [comment]
@willgorham hmm....I still seem to get the issue will check this.

**Comment by willgorham** [comment]
@glenprimitivesense 3.2.2 has not been released yet. You can either add the changes from #17242 yourself, or wait until the 3.2.2 update is released (presumably this week).
