### ISSUE TITLE
Problems for Thumbnails products

### ISSUE THREAD

**Issue by Infolu** [woocommerce/woocommerce#14114]
Person receiving the registry error below both in production and on local host, the error happens only some products and not all, generating the error not product-trumbnails

Error \ plugins \ woocommerce \ templates \ single product \ product-thumbnails.php on line 32

http://imgur.com/AF6An2T

I am using a last version of wordpress and a last version of woocommerce
I am not using any modified template.

`
### WordPress Environment ###

Home URL: http://localhost/e-commerce
Site URL: http://localhost/e-commerce
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_BR

### Server Environment ###

Server Info: Apache/2.4.23 (Win64) PHP/7.0.10
PHP Version: 7.0.10
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.50.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (8) ###

Formulário de contato 7: por Takayuki Miyoshi – 4.7
Infolu Management System Store: por Infolu LTDA – 1.0.0
Infolu Management System: por Infolu LTDA – 2.0.3
InfiniteWP - Client: por Revmakx – 1.6.3.2
Members: por Justin Tadlock – 1.1.3
WooCommerce Correios: por Claudio Sanches – 3.2.2
WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.5.0
WooCommerce: por Automattic – 3.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /loja/
Carrinho: #1234 - /carrinho/
Finalizar compra: #1235 - /finalizar-compra/
My account: #1236 - /minha-conta/

### Theme ###

Name: Store
Version: 99.2.0.0
Author URL: http://infolu.com.br/
Child Theme: ❌ – Caso você esteja personalizando o WooCommerce em um tema pai que você não desenvolveu
então recomendamos utilizar um tema filho. Veja como criar um tema filho

WooCommerce Support: ✔

### Templates ###

Outdated Templates: ❌Learn how to update
`

**Comment by Infolu** [comment]
Personal I made the following change in the file
Plugins \ woocommerce \ templates \ single product \ product-thumbnails.php on line 32

Replaces line 32
From $ image_title = $ thumbnail_post-> post_content;
FOR $ image_title = get_the_title ($ attachment_id);

Where $ image_title = $ thumbnail_post-> post_content; Not after the title of the image.

If someone has the same problem, that was my solution.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/14116
