### ISSUE TITLE
Cleared product variation data

### ISSUE THREAD

**Issue by chirag255** [woocommerce/woocommerce#14115]
### EXPLANATION OF THE ISSUE

Woocommerce 3.0.1 update cleared my all variable product variation data. Attribute tab shows the attribute and its value but the variations tab is empty after updating to 3.0.1

### STEPS TO REPRODUCE THE ISSUE

Update woocommerce from 3.0.0 to 3.0.1

<details>
### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: http://localhost/ledtestwoo
Site URL: http://localhost/ledtestwoo
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.9 (Win64) PHP/5.5.12
PHP Version: ❌ 5.5.12 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 3 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.36.0
OpenSSL/1.0.1g

SUHOSIN Installed: –
MySQL Version: 5.6.17
Max Upload Size: 3 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Font Awesome 4 Menus: by New Nine Media – 4.7.0
LED World Canada Site Settings: by LED World – 1.0.1
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce: by Automattic – 3.0.1
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: LED World Canada
Version: 1.0
Author URL: http://ledworld.ca
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: ledworldcanada/woocommerce/archive-product.php
ledworldcanada/woocommerce/cart\cart-empty.php
ledworldcanada/woocommerce/cart\cart-shipping.php
ledworldcanada/woocommerce/cart\cart-totals.php
ledworldcanada/woocommerce/cart\cart.php
ledworldcanada/woocommerce/cart\shipping-calculator.php
ledworldcanada/woocommerce/checkout\form-billing.php version 2.1.2 is out of date. The core version is 3.0.0
ledworldcanada/woocommerce/checkout\form-checkout.php
ledworldcanada/woocommerce/checkout\form-coupon.php
ledworldcanada/woocommerce/checkout\form-login.php
ledworldcanada/woocommerce/checkout\form-shipping.php
ledworldcanada/woocommerce/checkout\payment.php
ledworldcanada/woocommerce/checkout\review-order.php
ledworldcanada/woocommerce/checkout\thankyou.php
ledworldcanada/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
ledworldcanada/woocommerce/content-product_cat.php
ledworldcanada/woocommerce/content-single-product.php
ledworldcanada/woocommerce/emails\admin-new-order.php
ledworldcanada/woocommerce/emails\customer-completed-order.php
ledworldcanada/woocommerce/emails\customer-invoice.php
ledworldcanada/woocommerce/emails\customer-on-hold-order.php
ledworldcanada/woocommerce/emails\customer-processing-order.php
ledworldcanada/woocommerce/emails\email-footer.php
ledworldcanada/woocommerce/emails\email-order-details.php
ledworldcanada/woocommerce/emails\email-order-items.php version 2.1.2 is out of date. The core version is 3.0.0
ledworldcanada/woocommerce/emails\email-styles.php
ledworldcanada/woocommerce/global\quantity-input.php
ledworldcanada/woocommerce/loop\loop-end.php
ledworldcanada/woocommerce/loop\loop-start.php
ledworldcanada/woocommerce/loop\orderby.php
ledworldcanada/woocommerce/loop\pagination.php
ledworldcanada/woocommerce/myaccount\form-edit-account.php
ledworldcanada/woocommerce/myaccount\form-login.php
ledworldcanada/woocommerce/myaccount\form-lost-password.php
ledworldcanada/woocommerce/myaccount\my-account.php
ledworldcanada/woocommerce/single-product\add-to-cart\external.php
ledworldcanada/woocommerce/single-product\add-to-cart\simple.php version 2.1.0 is out of date. The core version is 3.0.0
ledworldcanada/woocommerce/single-product\add-to-cart\variable.php
ledworldcanada/woocommerce/single-product\meta.php
ledworldcanada/woocommerce/single-product\product-image.php
ledworldcanada/woocommerce/single-product\product-thumbnails.php
ledworldcanada/woocommerce/single-product\share.php
ledworldcanada/woocommerce/single-product\tabs\description.php
ledworldcanada/woocommerce/single-product\tabs\tabs.php
ledworldcanada/woocommerce/single-product\title.php
ledworldcanada/woocommerce/single-product\up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
ledworldcanada/woocommerce/single-product-reviews.php
ledworldcanada/woocommerce/single-product.php
ledworldcanada/woocommerce/taxonomy-product_cat.php
ledworldcanada/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
There is no special upgrade routine between 3.0.0 and 3.0.1 so this looks impossible.

There was however a bug in 3.0.0 where swapping a product type could trash variations. This will restore them https://gist.github.com/mikejolley/7dc21432643a4fdd342474dc2694a22d

**Comment by chirag255** [comment]
I have tested on local site as well as my hosted testing site. It repeating the same.

**Comment by mikejolley** [comment]
Maybe you should show an example in case you mean something else.

**Comment by chirag255** [comment]
Never mind. Not an issue for production website.
