### ISSUE TITLE
Dynamic items sold view/column/button

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#14121]
The items side column was removed in 3.0 due to inefficiencies and heavy load (it loaded all items for all orders).

http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/18832222-dynamically-display-order-content-on-orders-page

Build a dynamic version which uses AJAX to pull a list of items and display them somewhere, somehow. 

(Snippet for adding it back through code in the meantime, but not recommended due to the performance issues: https://gist.github.com/rynaldos/4d193083e0ca7bb187d361deae837f04)

**Comment by pmgarman** [comment]
Have any thoughts on if this loads on page load for all orders (giving the ability to see it without interaction) or on hover on the order? Based on user feedback from having removed it any insights into how people were using it most that could guide that?

Loading immediately keeps it easy to view on the fly without interaction but adds additional load for all page loads, but adds additional (potentially unneeded) load by triggering Ajax calls on every page load of the orders screen.

**Comment by mikejolley** [comment]
@pmgarman Previous version was displayed on click. It would have to be ajaxified to avoid the large number of item queries we removed the original column for.

**Comment by mikejolley** [comment]
@jameskoster would you have time to whip up a wireframe for this? Whilst the issue to is show line items, it could be some extra details too - think of it as a quick view of the main order details you can access via a button on the order list.

**Comment by jameskoster** [comment]
We're looking at orders next in c9n. Quick view might not be as relevant there as the app is faster but if it is then the same design could be applied to core. If not, I can look at this separately.

Should be ready in a couple of weeks. Hopefully we can make it work with your Sprint 4 deadline.

**Comment by mikejolley** [comment]
@jameskoster any movement there? If not we can push it back to 3.2 since we have quite a lot left to do anyway.

**Comment by jameskoster** [comment]
We're finishing up the designs / prototypes this week. As yet, being able to view order items on the order list screen hasn't come up in any of our stories/flows.

**Comment by mikejolley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Show a quick view of items sold on the orders list screen](https://trello.com/c/kVBOsQoq/102-show-a-quick-view-of-items-sold-on-the-orders-list-screen)

**Comment by pipdig** [comment]
If anyone wants a quick solution in the meantime, we created a quick plugin for our own site which displays the ordered items via an ajax request - https://wordpress.org/plugins/purchased-items-column-woocommerce

**Comment by mikejolley** [comment]
This is being worked on in branch: https://github.com/woocommerce/woocommerce/pull/16700

**Comment by mikejolley** [comment]
@mattyza Can you update http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/18832222-dynamically-display-order-content-on-orders-page?
