### ISSUE TITLE
problem with product import from 3rd parties.

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#14122]
Our 3rd fulfillment stopped working correctly. I can import but there aren't variants. The attributes are empty. I got this from error log:

2017/04/07 18:27:15 [error] 21171#0: *12122 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/xxxx/public_html/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php on line 1756" while reading response header from upstream, client: 216.51.130.154, server: domain.com, request: "POST /wc-api/v3/products HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "domain.com"

I'm using WooCommmerce Version 3.0.1.

**Comment by claudiosanches** [comment]
Already reported and fixed in https://github.com/woocommerce/woocommerce/pull/14107

**Comment by kevin25** [comment]
@claudiosanches Not complete fix i think. It's just better that i can see the variants but not in the attribute section.

![screen shot 2017-04-07 at 3 32 46 pm](https://cloud.githubusercontent.com/assets/2909982/24816671/a61d9032-1ba7-11e7-9d07-2aa36c176ef1.png)
![screen shot 2017-04-07 at 3 32 57 pm](https://cloud.githubusercontent.com/assets/2909982/24816722/c80ecf44-1ba7-11e7-81ce-afd9a8d260fa.png)
![screen shot 2017-04-07 at 3 33 02 pm](https://cloud.githubusercontent.com/assets/2909982/24816727/cd4aea74-1ba7-11e7-9c8a-d5b7de1b09ef.png)

**Comment by kevin25** [comment]
@claudiosanches It's seriously that is our production and our business is affected. Can you please check it carefully? Thanks
