### ISSUE TITLE
After 3.0 update Grouped Products and Up-sells and Cross-Sells are gone and unable to add

### ISSUE THREAD

**Issue by dezzell** [woocommerce/woocommerce#14127]
Just updated to Woocommerce 3.0 and afterwards all my Grouped Products and payment options vanished. I am unable to Add them back under Linked Products. It looks like a Multi Select box but no way to edit or add products. Tried on multiple computers and in Chrome and Edge with no luck.. All My Linked Products are gone with the wind.. Please fix or provide a way to fix or a new update..

**Comment by mikejolley** [comment]
This is due to a conflict with another plugin using an old version of SELECT2. View your javascript error console/turn off plugins to find a conflict.

As plugins update to v4 select2, this issue will resolve.

**Comment by dezzell** [comment]
Thank you, after awhile of Process of Elimination, It turned out to be Ultimate Addons version 3.16.3.. I will contact their support..

**Comment by dezzell** [comment]
There is a new version of 3.16.9 out, which I Installed, and still broken.. Sending a message to their support..
