### ISSUE TITLE
Showing fatal error when activating plugin 

### ISSUE THREAD

**Issue by emgk** [woocommerce/woocommerce#14124]
### EXPLANATION OF THE ISSUE
I have cloned the the latest code and when i am trying to active the plugin it showing me fatal error.

Plugin could not be activated because it triggered a fatal error.
**Parse error: syntax error, unexpected '{' in C:\xampp\htdocs\wp\wp-content\plugins\woocommerce\includes\data-stores\class-wc-product-data-store-cpt.php on line 356**

**Comment by mikejolley** [comment]
@claudiosanches this was a PR earlier. Only in master, not stable.
