### ISSUE TITLE
Variable Products / Stock Quantity / Structured Data

### ISSUE THREAD

**Issue by jsmusiker** [woocommerce/woocommerce#14129]
### EXPLANATION OF THE ISSUE

This issue is only for Variable Products, and only happening after the update.

When I set the stock quantity at the Variation level and only the variation level, it shows "Out of Stock" under the "Stock" column on the following page: WooCommerce > Products

So in the "Inventory" Tab under "Variable Product" I have checked the box next to "Manage Stock" and I have left the Stock Quantity blank, which is the same as zero. The only place I have entered a quantity is under the "Variations" Tab for each variation.

This did not behave like this in the previous versions. When you set the stock quantity at the variable level it showed the product as "In Stock", as it should. Showing "Out of Stock" is misleading, and confusing.

Additionally, the Structured Data / schema.org code is pulling the stock status only from the product level inventory, not the variable inventory. So when a variable Product is in stock and has a quantity set at that variable level and doesn't have a stock quantity set at the Product level, it shows "Out of Stock" in googles search results. And that is not good for sites that get a majority of their traffic from Google.

### STEPS TO REPRODUCE THE ISSUE

1. Create variable product
2. Inventory Tab - manage stock = check the box
3. Leave stock quantity blank or at 0 
4. Add attribute with 2 values
5. Add variations from all attributes
6. Manage Stock - check the box
7. Set price
8. Set stock quantity
9. Stock status - Change to In Stock

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

WooCommerce > Products - Showing "Out of Stock"
![product-stock](https://cloud.githubusercontent.com/assets/7741647/24820729/85d2c750-1bb8-11e7-8783-1a3573fdd6ac.png)

Inventory Tab - stock status set to 0 or blank
![inventory-tab](https://cloud.githubusercontent.com/assets/7741647/24821038/4c6842a4-1bba-11e7-8030-c02e525f6bd8.png)

Variations Tab - This is where stock qty. is set
![variations-tab](https://cloud.githubusercontent.com/assets/7741647/24821060/6d183554-1bba-11e7-9422-6d5af5eb7277.png)

**Comment by mikejolley** [comment]
If you are managing stock at variation level, the stock at variable level needs to be removed - otherwise it won't sync with it's children.

**Comment by mikejolley** [comment]
Confirmed, this is a bug in 2.6 which is fixed. Your parent is both **stock managed** and has **0 stock** - therefore it is out of stock. You need to turn off stock managing at the parent level.
