### ISSUE TITLE
WC_Order_Item_Meta doesn't show deprecation notice

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#14126]
title says it all: `WC_Order_Item_Meta` is [tagged deprecated](https://github.com/woocommerce/woocommerce/blob/71d0702523bcc365403dd3b84b945da5218d88b4/includes/class-wc-order-item-meta.php#L11), but it doesn't throw any deprecation notice.

**Comment by mikejolley** [comment]
It's used in the legacy API also. Not sure if a notice is needed @claudiosanches? We could just deprecate it when we deprecate the legacy api.

**Comment by claudiosanches** [comment]
@mikejolley we could include notices in 3.1.0 and leave soft deprecated for now. But should done soon, since plugins use it today and should be updated to the new CRUD classes.
And for sure legacy API should be already update to stop use it, right now in a next patch release.
