### ISSUE TITLE
Attribute issue WooCommerce 3.0.1

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#14137]
I have 3rd fulfillment to import variable products with sizes and colors. Since upgraded to WooCommerce 3.0.x, it stopped working.

If the attribute color and size are still there, then when i import variable products, it will look like:

![screen shot 2017-04-07 at 3 32 46 pm](https://cloud.githubusercontent.com/assets/2909982/24827153/5202177c-1c13-11e7-9172-69bc4c072f12.png)
![screen shot 2017-04-07 at 3 32 57 pm](https://cloud.githubusercontent.com/assets/2909982/24827155/59ddd53a-1c13-11e7-9624-59d26ee1907f.png)

![screen shot 2017-04-07 at 3 33 02 pm](https://cloud.githubusercontent.com/assets/2909982/24827157/6205e888-1c13-11e7-89db-e47b28985b48.png)

 I found out that when I renamed the existing attribute Size and Color, I can import the products correctly:

![screen shot 2017-04-08 at 4 17 51 am](https://cloud.githubusercontent.com/assets/2909982/24827133/fcdc2c42-1c12-11e7-9278-98a97f2a8d6e.png)

![screen shot 2017-04-08 at 4 25 57 am](https://cloud.githubusercontent.com/assets/2909982/24827166/90a102cc-1c13-11e7-85d9-88c68f538345.png)
![screen shot 2017-04-08 at 4 26 04 am](https://cloud.githubusercontent.com/assets/2909982/24827165/90a03cd4-1c13-11e7-87ba-137f8cb87edd.png)

So i doubt there is something wrong with API.

**Comment by mikejolley** [comment]
@claudiosanches

**Comment by mukk85** [comment]
I am having a similar issue. Old product attributes do not show if I use the "Color" type. I believe the above worked the second time because it is changed from a selector to plain text. It seems that when you use the selector it uses the array syntax of attribute_values[0][] instead of the | syntax.

**Comment by kevin25** [comment]
@mukk85  exactly.

**Comment by claudiosanches** [comment]
@kevin25 show me an example of JSON that you are using.
Not that `slug` should be only used if it's a global attribute.

**Comment by claudiosanches** [comment]
@kevin25 I just tested and works just fine, without any problem with existing global attributes, just need to properly set up the JSON data:

Here an example:

```json
{
  "product": {
    "title": "Ship Your Idea",
    "type": "variable",
    "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
    "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
    "categories": [
      9,
      14
    ],
    "attributes": [
      {
        "name": "Color",
        "position": "0",
        "visible": false,
        "variation": true,
        "options": [
          "Black",
          "Green"
        ]
      }
    ],
    "default_attributes": [
      {
        "name": "Color",
        "option": "Black"
      }
    ],
    "variations": [
      {
        "regular_price": "19.99",
        "attributes": [
          {
            "name": "Color",
            "option": "Black"
          }
        ]
      },
      {
        "regular_price": "19.99",
        "attributes": [
          {
            "name": "Color",
            "option": "Green"
          }
        ]
      }
    ]
  }
}
```

Note that an attribute it's created only using `"name": "Color"`, without any slug, it because if you send an slug, will try find for a global attribute, the on the variations are used the same.

This is not good, still it's how works since 2 years ago, see: https://github.com/woocommerce/woocommerce/blame/master/includes/api/legacy/v3/class-wc-api-products.php#L1887

For better handle products and variations I recommend you migrate your integration to our new REST API v2 documented in https://woocommerce.github.io/woocommerce-rest-api-docs/
Or at least for now use the REST API v1, that it's present in WooCommerce 2.6.

**Comment by kevin25** [comment]
Here is our slug:

> {
    "product": {
        "title": "TEST PRODUCT 5A",
        "description": "TEST PRODUCT 5A",
        "catalog_visibility": "hidden",
        "type": "variable",
        "attributes": [
            {
                "name": "Size",
                "slug": "size",
                "variation": true,
                "options": [
                    "S",
                    "M",
                    "L",
                    "XL",
                    "2XL",
                    "3XL",
                    "4XL",
                    "5XL",
                    "Youth XS",
                    "Youth S",
                    "Youth M",
                    "Youth L",
                    "Youth XL"
                ]
           }
        ],
        "images": [
            {
                "src": "https://domain.com/store/def48a1f084477982089/Cust/000/133/355/10214_4682_0x2.jpg",
                "position": 0
            }
        ],
        "variations": [
            {
                "regular_price": "99.00",
                "sku": "TS.8077870",
                "weight": 0.365,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "S"
                    }
                ]
            },
            {
                "regular_price": "99.00",
                "sku": "TS.8077871",
                "weight": 0.415,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "M"
                    }
                ]
            },
            {
                "regular_price": "99.00",
                "sku": "TS.8077872",
                "weight": 0.475,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "L"
                    }
                ]
            },
            {
                "regular_price": "99.00",
                "sku": "TS.8077873",
                "weight": 0.506,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "XL"
                    }
                ]
            },
            {
                "regular_price": "100.50",
                "sku": "TS.8077874",
                "weight": 0.561,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "2XL"
                    }
                ]
            },
            {
                "regular_price": "102.00",
                "sku": "TS.8077875",
                "weight": 0.681,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "3XL"
                    }
                ]
            },
            {
                "regular_price": "102.50",
                "sku": "TS.8077876",
                "weight": 0.85,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "4XL"
                    }
                ]
            },
            {
                "regular_price": "102.50",
                "sku": "TS.8077877",
                "weight": 0.9,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "5XL"
                    }
                ]
            },
            {
                "regular_price": "99.00",
                "sku": "TS.8077878",
                "weight": 0.21,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "Youth XS"
                    }
                ]
            },
            {
                "regular_price": "99.00",
                "sku": "TS.8077879",
                "weight": 0.246,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "Youth S"
                    }
                ]
            },
            {
                "regular_price": "99.00",
                "sku": "TS.8077880",
                "weight": 0.286,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "Youth M"
                    }
                ]
            },
            {
                "regular_price": "99.00",
                "sku": "TS.8077881",
                "weight": 0.315,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "Youth L"
                    }
                ]
            },
            {
                "regular_price": "99.00",
                "sku": "TS.8077882",
                "weight": 0.358,
                "attributes": [
                    {
                        "name": "Size",
                        "slug": "size",
                        "option": "Youth XL"
                    }
                ]
            }
        ]
    }
}

**Comment by claudiosanches** [comment]
@kevin25 as I said, when submit need to remove the slug if it's not a global attribute.
