### ISSUE TITLE
new WC_Order() throws exception/fatal error if the order doesn't exist

### ISSUE THREAD

**Issue by NTShop** [woocommerce/woocommerce#14130]
When trying to load an order by ID that doesn't exist WC throws an exception/fatal error instead of returning false as in previous versions of WC. This causes major problems and doesn't take into account race conditions of various types. 

For example, lets say an some created an order (doesn't matter how, admin area, frontend, plugin, whatever), then Person A is doing routine tasks that on the site with code that takes action on orders for whatever reasons, in the meantime Person B deletes an order. This causes a crash when the tools Person A is using tries to load that now non-existent order. 

Same thing happens when a remote API is given a list of orders and later that remote API tries to take action against an order on the origin site because it was previously told the order exists. 

Granted, this can be avoided by adding a lot of extra (previously unnecessary) code and processing overhead (which is an unnecessary performance and resource hit). But that's not really an ideal solution. 

The call to "new WC_Order()" should return false or empty as it did in the past.

**Comment by Spreeuw** [comment]
What about using `wc_get_order()` instead? That's the official method since WC2.2 and this will return false for non-existing orders.

**Comment by mikejolley** [comment]
A constructor cannot 'return false',

**Comment by mikejolley** [comment]
Using `wc_get_order()` is the way forward as it handles try/catch for you. Order constructors cannot return anything but you need to know if they are invalid. Hence exception, added in a major release.

**Comment by jquerytraining** [comment]
better check like below before [woocommerce get order](http://jquerytraining.com) detsils
 if ( TRUE === get_post_status( $vendor_order->order_id  ) ){ 
$order_data = new WC_Order( $order_id );
}

**Comment by mikejolley** [comment]
Not it's not. Better to use `wc_get_order()` function as I said.
