### ISSUE TITLE
Product titles are not being controlled by title.php template.

### ISSUE THREAD

**Issue by logixtreeCode** [woocommerce/woocommerce#14134]
### Site is not reflecting the header settings and classes

WooCommerce Update : 3.0.1

In Earlier version, We have been controlling product titles in archive page by loop/title.php. Recent Update has broken the procedure. Now, We are left with not way to edit core file for title update. Not even a filter is available. 

Woocommerce 2.4.8 :
`if (  ! function_exists( 'woocommerce_template_loop_product_title' ) ) {

	/**
	 * Show the product title in the product loop. By default this is an H3
	 */
	function woocommerce_template_loop_product_title() {
		wc_get_template( 'loop/title.php' );
	}
}`

Current Version : 3.0.1 
`if ( ! function_exists( 'woocommerce_template_loop_product_title' ) ) {

    /**
     * Show the product title in the product loop. By default this is an H3.
     */
    function woocommerce_template_loop_product_title() {
        echo '<h2 class="woocommerce-loop-product__title">' . get_the_title() . '</h2>';
    }
}`

Even the comment is saying it's gonna be H3, but code is done using h2. 

More info : Please check doc [Woocommerce Documentation ](https://docs.woocommerce.com/wc-apidocs/source-function-woocommerce_template_loop_product_title.html#579-584)

Thank you, 
Regards,
Team LogixTree

**Comment by mikejolley** [comment]
This function is pluggable. The docblock is updated is master. H2 is correct from semantic and seo standpoint.

**Comment by logixtreeCode** [comment]
Thanks Mike, yes got it working by throwing function in functions.php
It just broke our woocommerce sites layout (having big titles), thought it might worth mentioning here.
