### ISSUE TITLE
woocommerce 3.0.1 not working right

### ISSUE THREAD

**Issue by 50caljoe** [woocommerce/woocommerce#14132]
### EXPLANATION OF THE ISSUE
after updating to the 3.0 update every thing stop working now after the 3.0.1 update most everything is back up but I do not have the new features and when I try to add variable product it dose not load it just spin

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: https://thebijouxcollection.com
Site URL: https://thebijouxcollection.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.16
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Akismet Anti-Spam: by Automattic – 3.3
Autoptimize: by Frank Goossens (futtta) – 2.1.0
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.9
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp for WordPress: by ibericode – 4.1.0
MOJO Marketplace: by Mike Hansen – 1.1.3
Ninja Forms: by The WP Ninjas – 3.0.31
Optin Forms: by FancyThemes – 1.2.8
Post Types Order: by Nsp Code – 1.9.3
PRESSO Demo Installer: by Envirra – 1.0.0
PRESSO Shortcodes: by Envirra – 3.0.0
PRESSO Theme Options Panel: by Envirra – 1.0.0
Really Simple SSL: by Rogier Lankhorst – 2.5.11
Slider Revolution: by ThemePunch – 5.4.2
Shareaholic | share buttons, analytics, related content: by Shareaholic – 7.8.0.6
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

WooCommerce PayPal Powered by Braintree Gateway: by WooThemes – 1.2.7
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce: by Automattic – 3.0.1
Wordfence Security: by Wordfence – 6.3.6
WordPress Popular Posts: by Hector Cabrera – 3.3.4
Envato Market: by Derek Herman – 1.0.0-RC2
WP Smush: by WPMU DEV – 2.6.2
WP Super Cache: by Automattic – 1.4.9
WP User Avatar: by flippercode – 2.0.8

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #12 - /shop/
Cart: #14 - /cart/
Checkout: #16 - /checkout/
My account: #18 - /my-account/

### Theme ###

Name: Presso - Child
Version: 1.0
Author URL: http://envirra.com
Child Theme: ✔
Parent Theme Name: Presso
Parent Theme Version: 3.0.1
Parent Theme Author URL: http://themeforest.net/user/envirra?ref=envirra
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
Have you disabled plugins to find the conflict yet?

**Comment by 50caljoe** [comment]
Yes I deactivated them one by one and tried to add a variable product and
it is still just loading, I installed woocommerce 3.0.1 onto one of my
other site and the variable works just fine how ever the update dose not
look like the video from woocoommerce said it would look and the images
dose not change with each color or size when I view page from the site
side. Thank You for getting back to me. Eric

**Comment by layoutph** [comment]
I have the same problem like from OP. Our woocommerce store has different product images, but after the update, everything created as variable is not working upon selection. Hope you fix this bug.

**Comment by mensmaximus** [comment]
Most likely this is an issue with your theme not being compatible with woocommerce 3 yet. I have seen this with many themes. You can verify it be temporarily activating the theme twenty seventeen. There you should see the images changing with the selection of variations.

**Comment by mikejolley** [comment]
When you select a variation an event is fired which needs to be picked up by the gallery script to swap the image. If this has been replaced i.e. theme custom gallery, or the classnames in templates do not match, this cannot occur.

I suggest you test a default WP theme - if it works there you'll know it's a theme incompatibility. For me, this functionality is working as it should on default themes and Storefront.

**Comment by 50caljoe** [comment]
Ok Thank You I will try that.

**Comment by boudga** [comment]
The problem is a result of a MySQL SELECT statement that makes multiple LEFT JOINs and causes MySQL to hang on that query. I have created a ticket with Woocommerce and they will not respond about it.

**Comment by mikejolley** [comment]
Sounds completely unrelated to this.

**Comment by boudga** [comment]
trust me it is not...I was experiencing the exact same issue as 50caljoe and I ran mytop to monitor MySQL on product detail pages and as I selected variations this query would hang and never complete.

**Comment by mikejolley** [comment]
Well his description was pretty vague :) If you have a lot of variations + attributes, make sure mysql big selects is enabled.

**Comment by boudga** [comment]
thank you for that info. I am on a shared host and they will not enable that in the my.cnf. Do you have a recommendation on how best to implement that per session?
