### ISSUE TITLE
Cannot Update Products

### ISSUE THREAD

**Issue by dropsprops** [woocommerce/woocommerce#14131]
### When I try to update a product, I get http://website.com/wp-admin/post.php instead of refreshing with the correct product page. 

Issues occurred after updating to WooCommerce 3.0.1.

I have tested without plugins and with a different theme so it is not related to either of those.

### STEPS TO REPRODUCE THE ISSUE

Go to any product and click the "Update" button. (No changes need to be made.)

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://dropsprops.com
Site URL: http://dropsprops.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.3
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 10000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: bku_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (24) ###

Akismet Anti-Spam: by Automattic – 3.3
Contact Form 7: by Takayuki Miyoshi – 4.7
Disable New User Notifications: by Thomas Griffin – 1.0.2
Fusion Builder: by ThemeFusion – 1.1.5
Fusion Core: by ThemeFusion – 3.1.5
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.6
Improved Sale Badges for WooCommerce: by Mihajlovic Nenad – 2.4.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Woocommerce Advanced Bulk Edit: by George Iron – 4.2
WooCommerce Conversion Tracking: by Tareq Hasan – 1.2.2
WooCommerce Email Customizer: by cxThemes – 3.07
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce ShareThis Integration: by WooThemes – 1.0
WooCommerce UPS Shipping: by Automattic – 3.2.1
WooCommerce - ShipStation Integration: by WooThemes – 4.1.9
WooCommerce: by Automattic – 3.0.1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.5
WP Performance Score Booster: by Dipak C. Gajjar – 1.7.2
WP Smush: by WPMU DEV – 2.6.2
WP Super Cache: by Automattic – 1.4.9
WPMU DEV Dashboard: by WPMU DEV – 4.3
Yoast WooCommerce SEO: by Team Yoast – 1.1.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #4098 - /cart-2/
Checkout: #4099 - /checkout-2/
My account: #4100 - /my-account-2/

### Theme ###

Name: Avada
Version: 5.1.5
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

`
</details>

**Comment by mikejolley** [comment]
I think you posted this on .org also. You need to rule out a plugin conflict and/or view the server error logs for details.

**Comment by mhsh0001** [comment]
I have the same problem... plz help
sometimes update some field, sometimes nothings changed!

**Comment by mhsh0001** [comment]
I also deactivate every plugin but this is still the same :(

**Comment by mhsh0001** [comment]
i do not use any cache plugins or system also, everything works just fine last week
