### ISSUE TITLE
Outdated template? content-single-product.php

### ISSUE THREAD

**Issue by AdriOosterwijk** [woocommerce/woocommerce#14133]
After upgrading a Notice message was thrown on my single product page. It says:

Notice:  woocommerce_get_product_schema is deprecated since version 3.0 with no alternative available. in ../htdocs/wp-includes/functions.php on line 3832

Notice:  download_type was called incorrectly. Product properties should not be accessed directly. Please see <a href=" https:="" codex.wordpress.org="" debugging_in_wordpress"="">Debugging in WordPress for more information. (This message was added in version 3.0.) in ../htdocs/wp-includes/functions.php on line 4137

Debugging it I learned that it was caused by the template content-single-product.php.

It was still version 1.6.4. while the code in the 3.0 install was changed.
It think te adjustment of the version number was overlooked and therefor was the template file not marked as outdated. If so... please correct it.

**Comment by umitcil** [comment]
whats the solution?

**Comment by claudiosanches** [comment]
@umitcil update your WooCommerce.
