### ISSUE TITLE
403 forbidden error for POST to ?wc-ajax=update_order_review on woocommerce checkout

### ISSUE THREAD

**Issue by Wegerich** [woocommerce/woocommerce#14149]
### EXPLANATION OF THE ISSUE

I had this problem this morning on 2.7.4 and updated to the latest version to see if it would fix it but I still have the issue. I did not make any changes that might have triggered it.
I have disabled all plugins except woocommerce
I have changed theme to twenty twelve
I have sequentially disabled payment methods in woocommerce
Tested in three browsers and verified by multiple users -very easy to reproduce

When customers go to the checkout page, the "your order details" next to the billing address entry part just has the loading spinner which never loads. Inspecting using the console in chrome shows:

```
JQMIGRATE: Migrate is installed, version 1.4.1

VM2707:1 POST https://www.reagent-tests.uk/checkout/?wc-ajax=get_refreshed_fragments 403 (Forbidden)
(anonymous) @ VM2707:1
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
d @ cart-fragments.min.js?ver=3.0.1:1
(anonymous) @ cart-fragments.min.js?ver=3.0.1:1
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2

VM2707:1 POST https://www.reagent-tests.uk/checkout/?wc-ajax=update_order_review 403 (Forbidden)
(anonymous) @ VM2707:1
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
update_checkout_action @ checkout.min.js?ver=3.0.1:1
```
I have gone into FTP and set the public permissions for the affected files to "write" and this has not made a different.

### STEPS TO REPRODUCE THE ISSUE

Go to https://www.reagent-tests.uk, add an item to the cart then check out. The site will not allow you to progress further.
http://reallytasty.co.uk/ also displays the issue. I restored this site to its backup from 2 weeks ago and the issue is persisting.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.reagent-tests.uk
Site URL: https://www.reagent-tests.uk/wp
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: a8m9rq466w
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Ask Me: by Timo Schiller
Alexander Siemer-Schmetzke – 0.5

Bitcoin Payments for WooCommerce: by BitcoinWay – 4.11
Custom Admin Bar: by Ve Bailovity (Incsub) – 1.3.1.1
Disable Emojis: by Ryan Hellyer – 1.5.3
Jetpack by WordPress.com: by Automattic – 4.8.2
ExportFeed - Create Product Feeds For 40+ Merchants: by ExportFeed.com – 3.1.7.7
Scripts-To-Footer: by Joshua David Nelson – 0.6.1
Title Toggle for Storefront Theme: by Wooassist – 1.2.3
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce Google Analytics Pro: by WooThemes / SkyVerge – 1.1.7 – 1.2.0 is available
WooCommerce Discounts Per Payment Method: by Claudio Sanches – 2.3.0
WooCommerce Xero Integration: by WooThemes – 1.7.5 – 1.7.8 is available
WooCommerce: by Automattic – 3.0.1
Wordfence Security: by Wordfence – 6.3.6
WP Super Cache: by Automattic – 1.4.9

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
No mentioned of htaccess above - that was the issue on https://github.com/woocommerce/woocommerce/issues/14112

> I restored this site to its backup from 2 weeks ago and the issue is persisting.

This clearly points to a server error because the old WC version was working beforehand.

**Comment by Wegerich** [comment]
Sorry I forgot to mention that I tried everything in that issue. I figure it's something different.

**Comment by mikejolley** [comment]
Still, if 2.6 is affected too it looks site/server related.

Disable caching.
Delete .htaccess
Save permalink settings (So htaccess is remade)

**Comment by Wegerich** [comment]
Every time I try to save permalink settings the page loads wp-admin/options-permalink.php but gives a 404 error. Refreshing takes me back to the permalink settings page in the admin controls but the settings are unchanged. 

Thanks for your help already.

**Comment by dreamesper** [comment]
i have the same issue on my site as well... the checkout page continues to load forever... NOT allowing my customers to make payment through Paypal. Will this be fixed soon?

**Comment by alinrzv** [comment]
Same issue here on a namecheap hosting , i've debugged the requests AND I THINK IS A DAMN HOSTING SECURITY FEATURE that is BLOCKING SOME POST REQUESTS woocommerce ajax is giving 403 forbiden , tried saving permalinks in wordpress i get 404 not found when form is submited (more then that the server got me banned by ip as if there was an attack ), after i connected over a vpn i disabled all plugins , moved woocommerce out of the plugins folder through cPanel file manager , activated a wordpress default template tried saving permalinks again , same issue 404 error , this si clearly bogus , either hosting or something wrong from the wordpress , God knows , runing on wordpress 4.7.3 here , let me know your thoughts .

**Comment by alinrzv** [comment]
If you guys run on NAMECHEAP HOSTING please reply here , this might be a server side error happening all over their servers / hosting .

**Comment by Wegerich** [comment]
Yes, I am also using namecheap hosting

**Comment by alinrzv** [comment]
Namecheap just confirmed , is the mod_security doing this , message them and ask for disabling:

Adding this in .htaccess might disable it as well , give it a try ;

<IfModule mod_security.c>
  SecFilterEngine Off
  SecFilterScanPOST Off
</IfModule>

**Comment by Wegerich** [comment]
I contacted Namecheap support and they confirmed that it was an issue with their firewall which they have now fixed. 8 hours of my life troubleshooting and it took them about 30 minutes to fix. Thank you for your support and pointers @mikejolley

**Comment by organikekspres** [comment]
Namecheap is the culprit here. I can't believe this has been going on for a while. We have SEVERAL ABANDONED CARTS! 
So far Namecheap has fucked up 3 times wihin the last month. Worst hosting to start a Woocommerce business on their shared hosting. 
Looking for a better solution now.

**Comment by findbmx** [comment]
I as well confirm its a server shortcoming, maybe old PHP version.

**Comment by onefreeborn** [comment]
Thanks to Alinrzv and Wegerich I have this resolved for 2 clients. (Only wasted a few hours restoring websites & DBs to pre-3.0 WooCommerce backups, and mucking around trying to solve this one. Arrgh!) 
Namecheap runs ModSecurity (Apache security module which works as a web application firewall) on it's shared servers. It blocks the server IP for certain behaviors, but still not sure if the WooCommerce 3.01 update triggered it or what. Took them 5 min to fix once I sent them the link to this post.
Thanks all!

**Comment by cbernard** [comment]
Hello,

I've the same issue with my woocommerce installation, I've tried everything with the permalinks, htaccess, modsecurity... I still have a 403 error when I access to https://tacave.ch/geneve if I'm not connected and only during the first load... 

https://tacave.ch/?wc-ajax=update_order_review

Thanks for your help in advance.

**Comment by ForbiddenChunk** [comment]
Not sure if it's connected but getting an error with Woo Bookings;

> jquery.js?ver=1.12.4:4 GET /?wc-ajax=wc_bookings_find_booked_day_blocks 403 (Forbidden)

I've tried above and have it locally with the same error.

**Comment by majidorc** [comment]
Hello
Does anybody find any solution for this problem?
i have same this problem 
wc-ajax=wc_bookings_find_booked_day_blocks 403

**Comment by Wegerich** [comment]
Yes, contact your server host.

**Comment by majidorc** [comment]
what i have asking from them ?
just start live chat with hostgator
thank you

**Comment by Wegerich** [comment]
Send them the link to this github discussion

**Comment by majidorc** [comment]
server (Hostgator) said all is ok!

> However, issue seems to be out of scope of our HostGator services.

do you have any idea?
www.paralleltour.com

https://prnt.sc/pqluvp

thank you

**Comment by Turpoint** [comment]
I could fix it by setting `COOKIEPATH` to `'/'`.

**Comment by spishu21** [comment]
I am using Cloudways hosting it is also returning me with this error.
I have cache turned off for now
![image](https://user-images.githubusercontent.com/33219178/132449185-aaab4919-9bbf-4e4e-a2d7-0d3a183e59eb.png)

**Comment by jessuppi** [comment]
@spishu21 et al

WordPress and WooCommerce users should be aware that if they are using CloudFlare, some of these 403 (etc) errors have been increasing lately due to security/WAF firewall settings there.

Try disabling CloudFlare temporarily to confirm if that's the cause... and a long-term solution could be adjusting the security settings based on certain URLs using Page Rules, or relaxing some of the firewall rules, etc.

**Comment by spishu21** [comment]
> @spishu21 et al
> 
> WordPress and WooCommerce users should be aware that if they are using CloudFlare, some of these 403 (etc) errors have been increasing lately due to security/WAF firewall settings there.
> 
> Try disabling CloudFlare temporarily to confirm if that's the cause... and a long-term solution could be adjusting the security settings based on certain URLs using Page Rules, or relaxing some of the firewall rules, etc.

Will try doing this.
Thanks.

**Comment by janmeza** [comment]
> I could fix it by setting `COOKIEPATH` to `'/'`.

That solved the issue for me too! Thanks! 👍

**Comment by seni04** [comment]
> > I could fix it by setting `COOKIEPATH` to `'/'`.
> 
> That solved the issue for me too! Thanks! 👍

How to setting cookiepath ? never done this before

**Comment by stephanmantler** [comment]
In my case it was apparently interference with [wp-fastest-cache](https://wordpress.org/plugins/wp-fastest-cache/). Disabling that plugin resolved this issue on my multisite installation. Changing `COOKIEPATH` was not an option because it is controlled by `sunrise.php` for domain mapping.

**Comment by Jamesllllllllll** [comment]
I solved this today by disabling the plugin **Mailchimp for WooCommerce**. Following up with them to see how this can be fixed.

**Comment by srinaqvi** [comment]
[janmeza](https://github.com/janmeza) would you please tell in detail?

**Comment by drokk3** [comment]
I had the same issue after I added code to **.htaccess to force redirection to HTTPS**
**After removing it, the thing started to work again**. This was only in localhost enviroment so not sure if this
is relevant in live production.

**Comment by demironmanx** [comment]
This might happen because of country restrictions on to form submissions you set long time ago and forgot about it. When you allow the remote country or relax the security settings, it may resolve by itself.
