### ISSUE TITLE
Variation order change after add or save a variation description

### ISSUE THREAD

**Issue by titanco** [woocommerce/woocommerce#14140]
A have 3 variations on a product.
The current order of variations:
- Variation 1
- Variation 2
- Variation 3
But after i add a description to Variation 2 and Save, the new order is:
- Variation 1
- Variation 3
- Variation 2
So, i'm always need to re-order again.

Is this a bug or a just a function ?

**Comment by titanco** [comment]
P/s:
In the Woocommerce Admin the order not change, its only change on Frontend.

**Comment by mikejolley** [comment]
Re-ordering variations in the backend does not change the order in the frontend.

You need to re-order the attributes, not the variations. Products > Attributes if global.
