### ISSUE TITLE
woocommerce_get_template_part is deprecated since version 3.0

### ISSUE THREAD

**Issue by lovebum91** [woocommerce/woocommerce#14148]
Please help me.
When I upgrade on version 3.0. I have many bug. 

Link: https://ibb.co/gqRJd5

Thank you very much

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Deprecation-in-core#warnings-in-production-store-owners-read-this

Your themes/plugins need an update. You can hide these warnings in production.

**Comment by lovebum91** [comment]
Hi @mikejolley 
When I  turn off WP_DEBUG = false: define('WP_DEBUG', false); It's hidden
Please tell me. It is a bug:  https://ibb.co/c4Pod5 (Notice in the red box)
Thank you very much

**Comment by mikejolley** [comment]
It's deprecated and needs to be fixed in the theme, but is not a 'bug'. It does need to be addressed by the author.

**Comment by lovebum91** [comment]
Hi,
please tell me steps fix it on the my theme. I don't understand how fix it.
Thank you very much.
