### ISSUE TITLE
mod_fcgid: stderr: ERROR LOG

### ISSUE THREAD

**Issue by majidempire** [woocommerce/woocommerce#14145]
Dear Friends , 
What's going on , after update to WC3 
everything generate error in log
error is same

`mod_fcgid: stderr: individual_use was called incorrectly. individual_use should be true or false instead of yes or no.`

Every ajax GET request generate this of course outside WC :(
can't save pages, can't save posts , settings , everything

WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

**Comment by mikejolley** [comment]
This is a deprecation warning from a plugin. What are you running?

**Comment by mikejolley** [comment]
Please check your extensions for updates. https://github.com/woocommerce/woocommerce/wiki/Deprecation-in-core
