### ISSUE TITLE
Product Visibility Taxonomy needs debugging tools

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#14147]
We need something on system status, and a way to clean them - I just debugged a site where there were multiple outofstock terms which broke the frontend queries since it was trying to filter out the wrong term ID.

**Comment by andrewlreeve** [comment]
@mikejolley I've just seen this issue in a production site migrated to WC3.0. How is it best to clean up product visibility taxonomys. I've ended up with: 

exclude-from-catalog (exclude-from-catalog), exclude-from-catalog (exclude-from-catalog-2), exclude-from-search (exclude-from-search), exclude-from-search (exclude-from-search-2), featured (featured), featured (featured-2), featured (featured-3), outofstock (outofstock), outofstock (outofstock-2), outofstock (outofstock-3),

**Comment by andrewlreeve** [comment]
@mikejolley I've managed to tidy up the DB by removing the extra terms. It's working correctly for logged in users but not in incognito. Any ideas?

**Comment by dineshkashera** [comment]
The Correct Product Visibility Should be 
![deepak-out-of-stock](https://user-images.githubusercontent.com/25048361/38353469-24ff5fb2-38d4-11e8-9efc-a759c859bfa7.png)
But In my wordpress it shows multiple value raplicate after update to version 3.0. 
![dinesh-out-of-stock](https://user-images.githubusercontent.com/25048361/38353470-25316174-38d4-11e8-8e5e-415a6436135f.png)

**To fix the problem you have to do** 
1) Access your current database .
2) Execute below query 

> SELECT * FROM wp_terms WHERE term_id IN ( SELECT term_id FROM wp_term_taxonomy WHERE taxonomy = "product_visibility");

And remove the extra row.

I hope it will help you also.

Thanks
