### ISSUE TITLE
Variable product images not displaying correctly

### ISSUE THREAD

**Issue by jhapeman** [woocommerce/woocommerce#14154]
### EXPLANATION OF THE ISSUE

WC 3.0 broke the product variable product image gallery functionality.  Still not working with WC 3.0.1.  I have tested with various themes including: Storefront, Canvas, Resort--all on latest version.

When an image is set for a variable product variation, selecting the variation in the product dropdown will not cycle the correct variation image to the main image displayed.  

### STEPS TO REPRODUCE THE ISSUE

1) Create a variable product.
2) Create product variations and assign a different image to each variation.
3) Save product and got to product page.
4) Select variations.  Main image will not change to display variation image.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.earthstreasury.com
Site URL: http://www.earthstreasury.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: lhn_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (25) ###

Query Monitor: by John Blackbourn – 2.13.4
Cart recovery for WordPress Pro: by Lee Willis – 1.7.3
Cart recovery for WordPress: by Lee Willis – 2.1.4
Contact Form 7: by Takayuki Miyoshi – 4.7
Google Analytics +: by WPMU DEV – 3.1.5.5
MailChimp for WordPress: by ibericode – 4.1.0
PixelYourSite: by PixelYourSite – 5.0.1
Storefront Powerpack: by WooThemes – 1.3.1
WooCommerce Authorize.Net CIM Gateway: by SkyVerge – 2.6.0
WooCommerce AdWords Conversion Tracking: by Wolf+Bär GmbH – 1.3.5
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Product Archive Customiser: by jameskoster – 1.0.5
WooCommerce Product Search: by itthinx – 1.8.1
WooCommerce ShippingEasy Integration: by WooThemes – 3.4.1
WooCommerce WishLists: by Lucas Stark – 2.0.1
WooCommerce: by Automattic – 3.0.1
WooDojo: by WooThemes – 1.5.4
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
WP Hummingbird: by WPMU DEV – 1.4.2
WP Smush Pro: by WPMU DEV – 2.6.2
WP Staging: by WP-Staging
René Hermenau – 1.1.4

SmartCrawl: by WPMU DEV – 2.0
WPMU DEV Dashboard: by WPMU DEV – 4.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Galleria
Version: 2.2.10
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Authorize.Net CIM ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
`
</details>

**Comment by mikejolley** [comment]
This works on my test sites - I don't think there is a bug. In fact, the variation frontend code in 3.0.0 is almost identical to 2.6.14. Link to an example product?

**Comment by jhapeman** [comment]
Actually after clearing my browse cache now the images aren't loading at all.  

http://www.earthstreasury.com/product/the-helena-engagement-ring/

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/5zfp6hrdgq110jy/2017-04-08%20at%2020.01.png

Caching/minify plugin?

**Comment by mikejolley** [comment]
Endurance Page Cache?

**Comment by jhapeman** [comment]
It appears that there was an errant plugin messing with this.  I killed it and cleared the Cloudflare cache and now it all appears to be working.  Thanks!

**Comment by vanderbreye** [comment]
having the same problem here.
works in 2.x - does not in 3.0  - seems to break somewhere in "woocommerce_single_product_image_html" ...

**Comment by mensmaximus** [comment]
Your theme is using an old hook. https://github.com/woocommerce/woocommerce/issues/14152
Please contact the theme author.

**Comment by jvolvovski** [comment]
I am running into the exact same issue. The images used to swap when you selected one from the dropdown, but with one of the more recent updates, it stopped.

You can see the site here:
https://www.also-online.com/product/all-the-houses/

Latest version of both Wordpress and WooCommerce. I disabled all plugins, same issue. The site doesn't have any errors.

Any help would be appreciated,
Jenny

**Comment by tjkelly** [comment]
@mensmaximus does simply replacing all instances of `woocommerce_single_product_image_html` with `woocommerce_single_product_image_thumbnail_html` fix the issue? It doesn't seem to on my site.

Can you point us to any documentation on how to update the hook and bring back this functionality?

**Comment by MrSamSeen** [comment]
**[FIX FOUND]**
I replaced the "product-image.php" file in the theme folder (wp-content/themes/[path-to-theme]/woocommerce/single-product) with the one found in the woocommerce folder (wp-content/plugins/woocommerce/templates/single-product)

And it works.

> Please backup your current files before you do this

preferably the theme developer should do this in their next theme update, but above solution worked for me.

I just followed the instructions in this [Fixing Outdated WooCommerce Templates](https://docs.woocommerce.com/document/fix-outdated-templates-woocommerce/)

**Comment by RAMI15** [comment]
MrSamSeen and tjkelly answers are  right, worked for me ;)

**Comment by Sukonik** [comment]
The latest woocomerce-wordpress update makes a separate section (button) for product images in the image menu. 

![product image](https://user-images.githubusercontent.com/2436557/28290025-cd9d176c-6b12-11e7-9851-3803ec92d4a8.png)

**Comment by housammuhanna** [comment]
dears,
i am facing a problem with woocommerce product variations gallery.
 we are using the Smart Variations Images plugin and need to have a specific image gallery for each variation, but the problem is that the product gallery is not changing according to the variations: this is a link for a sample product to see the issue: https://party21-fashion.com/product/evening-dress/
please advice.

**Comment by ssuess** [comment]
I am experiencing the same problem, and I wonder if it is related to using a child theme? I am using storefront theme with a custom child, but I am not customizing any of the code related to that template, it is not even included in my theme files. If I switch to the parent theme of storefront, the images will switch again.

**Comment by ssuess** [comment]
This was happening to me too, and I figured out the cause: A filter I was using to remove links on the product image. Once I removed it, the images started swapping again just fine. here was the code in question:
```
add_filter('woocommerce_single_product_image_thumbnail_html','wc_remove_link_on_thumbnails' ); 
function wc_remove_link_on_thumbnails( $html ) {
     return strip_tags( $html,'<img>' );
}
```

**Comment by mimomedia** [comment]
Hi all, I found a solution for this:

The variations select tries to find the closest .product to change the variation image when variations select is changed with this code in woocommerce file add-to-cart-variation.js:
`
$product  = $form.closest( '.product' ),`

In my case i changed the single product image markup and the variations form lost the parent closest .product so that's why it was not working.

So i have given a class of 'product' to the closest parent of both, variations form and .images div and all works properly.

So the thing is to give a class of 'product' to the closest parent of both(the first parent that contains both), variations forms and images

**Comment by julienouellette** [comment]
@MrSamSeen could you tell me how you do it step by step please. I'm really new to this and it's a nightmare since my variations product images won't appear anymore.

**Comment by lefreaka** [comment]
I was having the same problem, i used the suggested fic of uploading product-image.php into my themmes woocommerce single-product folder, but the problem persisted so i looked through the css and found this "opacity: 0; transition: opacity .25s ease-in-out;" in the div created by product-image.php 

"
<div class="woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-4 images" data-columns="4" style="opacity: 0; transition: opacity .25s ease-in-out;">
 "

i then went into my product-image.php file and deleted the style part in the div.

Its working fine now.

**Comment by lefreaka** [comment]
I was having the same problem, i used the suggested fic of uploading product-image.php into my themmes woocommerce single-product folder, but the problem persisted so i looked through the css and found this "opacity: 0; transition: opacity .25s ease-in-out;" in the div created by product-image.php

"
div class="woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-4 images" data-columns="4" style="opacity: 0; transition: opacity .25s ease-in-out;
"
i then went into my product-image.php file and deleted the style part in the above div.

Its working fine now.

**Comment by that-ben** [comment]
Thanks @MrSamSeen this is still working as a fix.  Thanks.

**Comment by RiaanC** [comment]
@MrSamSeen - thank you!  Works like a charm.
