### ISSUE TITLE
Duplicates shown in cross sells list

### ISSUE THREAD

**Issue by ryankereliuk** [woocommerce/woocommerce#14158]
Noticed after upgrade to WC3 (but not blaming this version specifically).  Reproduce by adding items that have overlapping cross sells and loading the cart page.

Tracked into class-wc-cart.php ... array_merge will add items with duplicate keys if keys are numeric.

<pre>
--- /tmp/class-wc-cart.php	2017-04-08 14:27:34.654250308 -0700
+++ class-wc-cart.php	2017-04-08 14:23:44.857419693 -0700
@@ -613,7 +613,7 @@
 		if ( ! $this->is_empty() ) {
 			foreach ( $this->get_cart() as $cart_item_key => $values ) {
 				if ( $values['quantity'] > 0 ) {
-					$cross_sells = array_merge( $values['data']->get_cross_sell_ids(), $cross_sells );
+					$cross_sells = array_replace( $cross_sells, $values['data']->get_cross_sell_ids() );
 					$in_cart[]   = $values['product_id'];
 				}
 			}
</pre>

**Comment by mensmaximus** [comment]
Maybe related to https://github.com/woocommerce/woocommerce/pull/14136
