### ISSUE TITLE
Problem with dropdown product attributes display

### ISSUE THREAD

**Issue by jhapeman** [woocommerce/woocommerce#14153]
### EXPLANATION OF THE ISSUE

WC 3.0 introduced an error with the dropdown select lists in product attributes.  They render overtop of existing screen display/text making them difficult to read/select.  The issue still exists in WC 3.0.1

![attributes](https://cloud.githubusercontent.com/assets/27082412/24831025/a51af662-1c5f-11e7-84ad-b1e58dcf409a.jpeg)

### STEPS TO REPRODUCE THE ISSUE

Have a product with multiple attributes that can be selected from a list.  Go to select an attribute.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.earthstreasury.com
Site URL: http://www.earthstreasury.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: lhn_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (25) ###

Query Monitor: by John Blackbourn – 2.13.4
Cart recovery for WordPress Pro: by Lee Willis – 1.7.3
Cart recovery for WordPress: by Lee Willis – 2.1.4
Contact Form 7: by Takayuki Miyoshi – 4.7
Google Analytics +: by WPMU DEV – 3.1.5.5
MailChimp for WordPress: by ibericode – 4.1.0
PixelYourSite: by PixelYourSite – 5.0.1
Storefront Powerpack: by WooThemes – 1.3.1
WooCommerce Authorize.Net CIM Gateway: by SkyVerge – 2.6.0
WooCommerce AdWords Conversion Tracking: by Wolf+Bär GmbH – 1.3.5
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Product Archive Customiser: by jameskoster – 1.0.5
WooCommerce Product Search: by itthinx – 1.8.1
WooCommerce ShippingEasy Integration: by WooThemes – 3.4.1
WooCommerce WishLists: by Lucas Stark – 2.0.1
WooCommerce: by Automattic – 3.0.1
WooDojo: by WooThemes – 1.5.4
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
WP Hummingbird: by WPMU DEV – 1.4.2
WP Smush Pro: by WPMU DEV – 2.6.2
WP Staging: by WP-Staging
René Hermenau – 1.1.4

SmartCrawl: by WPMU DEV – 2.0
WPMU DEV Dashboard: by WPMU DEV – 4.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Galleria
Version: 2.2.10
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Authorize.Net CIM ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
`
</details>

**Comment by mikejolley** [comment]
Clear all browser caches. You're missing styles.

**Comment by jhapeman** [comment]
Thanks, cleared the cache and it was resolved.
