### ISSUE TITLE
Woo import CSV (export tab)

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/woocommerce#14155]
### EXPLANATION OF THE ISSUE

The export funnction in the Woo product import CSV uses still the old "_feature" in the postmeta table. Should follow the WC 3.0.1 way. 

### STEPS TO REPRODUCE THE ISSUE

Do an export of just the featured field. Ik will not show the "new" featured products

### SYSTEM STATUS

<details>
Brings nothing new
</details>

**Comment by mikejolley** [comment]
Logged https://github.com/woocommerce/woocommerce-product-csv-import-suite/issues/107

**Comment by EgbertJan** [comment]
It might happen on the import tab too; I haven't been able to check.
EJ
