### ISSUE TITLE
woo shortcode [featured_products ...]

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/woocommerce#14156]
### EXPLANATION OF THE ISSUE

I seem to remember the on each visit to the homepage with a shorcode for featured of related products with the option orderby="rand", the products changed order on refresh. Now they stayin the same order each time. Dunno if you should call this a regression.

### STEPS TO REPRODUCE THE ISSUE

visit a page with  [featured_products per_page="24" columns="4" orderby="rand"] or similar  and refresh te page. The order does not change. 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
All shortcodes get transient cached here: https://github.com/woocommerce/woocommerce/blob/76f8c3ddddded3dea808a0891c6e82b87815f646/includes/class-wc-shortcodes.php#L90-L96

This is for performance and by design.
