### ISSUE TITLE
Product and Shop pages - Sort by Price issue

### ISSUE THREAD

**Issue by voaooo** [woocommerce/woocommerce#14150]
issue: When selecting the sorting options in Woocommerce -> Settings -> Display -> Default Product sorting -> Sort By Price (ASC or DSC), there is problem with all the variation products.

It sorts randomly and not taking into account the products lowest price so the sorting looks out of sync and users won’t know this.

Is there a way to sort the products low to high/high to low and use the variable products lowest price when sorting?

this issue was not resolved after my woocommerce updated to 3.0.1.  Please assist?
my page: [http://bit.ly/2octiPt](url)
you may also want to refer to the closed one which is the same issue: [https://github.com/woocommerce/woocommerce/issues/13567](url)

**Comment by mikejolley** [comment]
Variable products need to be saved in order to sync (to take advantage of the fix mentioned in https://github.com/woocommerce/woocommerce/issues/13567).

**Comment by voaooo** [comment]
Hello,
each time i saved them, the item jumped into another place.  could you please check?
[http://bit.ly/2octiPt](url)
my sorting is all messy.  they are not following any price order.

**Comment by mikejolley** [comment]
They are sorting by the min price when I view?

**Comment by voaooo** [comment]
please scroll down to the middle.  after Domaine Dupont Reserve at $138, you will see Kopparberg 16.9.  and scroll down more, after Original Sin Pear Cider $35, you will see La Chouette at $30.   and scroll down more, after Thistly Cross Traditional $37, you will see Napoleone Ciderhouse Apple $31.

**Comment by mikejolley** [comment]
So the question is, were these ones saved again, and what _price meta does the parent have. Focus on the Kopparberg - save it. No effect? Look at the postmeta table and see what each of it's _price fields are set to. It should have a _price set for each variation price that exists.

**Comment by voaooo** [comment]
focus on the Kopparberg.  I have updated the min variable price, it jumped to the first one when by pricing sorting.  If I update it again, it would jump back to the original place (in the middle of the product sorting if sorted by price).

**Comment by mikejolley** [comment]
>  I have updated the min variable price

What do you mean there? Prices are synced, not set.

**Comment by voaooo** [comment]
I updated the min variable price.  Then it jumped to the lowest price.  This screenshot shows you.
<img width="706" alt="screen shot 2017-04-16 at 1 52 58 am" src="https://cloud.githubusercontent.com/assets/25746260/25065739/7befee3a-2247-11e7-81e7-d78e549cf913.png">

And if I updated it (the per bottle price) again.  It is no more there and jumped back to the middle position of the list.  This is the screenshot.
<img width="709" alt="screen shot 2017-04-16 at 1 55 19 am" src="https://cloud.githubusercontent.com/assets/25746260/25065770/daa9c522-2247-11e7-8a4f-6e1258ab96bf.png">

So this circumstance is happening to every item after updating them each time.  I don't know why and very confused.

**Comment by mikejolley** [comment]
Tools > Export, export the products, send here and give me the ID of the kpparberg/affected products. I'll be able to see what values _price has from that.

**Comment by voaooo** [comment]
[wanderer.wordpress.2017-04-15.xml.zip](https://github.com/woocommerce/woocommerce/files/923786/wanderer.wordpress.2017-04-15.xml.zip)
I think all products are affected.  the name of Kopparberg is Kopparberg Pear Cider.

**Comment by mikejolley** [comment]
That one has the _price meta, 16.9 being the lowest value. Correct?

I'm still not sure what you meant when you said: "I updated the min variable price." Where? How?

**Comment by voaooo** [comment]
yes, 16.9 is the lowest value.
sorry, i used the wrong phrase.  i intented to say "lowest value", not min variable price.

**Comment by mikejolley** [comment]
Last thing to check. In the postmeta table for that product, look for rows with key _price and ID of the product. What order are they shown in? Can you screenshot that? I'm wondering if they are being saved out of order, so lowest value is not considered.

**Comment by voaooo** [comment]
sorry, i am not too familiar with programming.  could you show me how to access the postmeta table?
is this screenshot what you want?
<img width="788" alt="screen shot 2017-04-17 at 11 13 32 pm" src="https://cloud.githubusercontent.com/assets/25746260/25093181/a59a7ec6-23c3-11e7-8e37-0389bb691289.png">

**Comment by mikejolley** [comment]
wp_postmeta table in your database. View using PHPMyAdmin.

**Comment by voaooo** [comment]
Please have a look of the screenshots.  I have set this product 4 variations.
<img width="593" alt="screen shot 2017-04-18 at 12 01 36 am" src="https://cloud.githubusercontent.com/assets/25746260/25094608/8e4c0fb2-23ca-11e7-8348-ea3775faba23.png">
<img width="532" alt="screen shot 2017-04-18 at 12 01 58 am" src="https://cloud.githubusercontent.com/assets/25746260/25094619/9ab96c68-23ca-11e7-957d-804b9a159c5c.png">
<img width="526" alt="screen shot 2017-04-18 at 12 02 10 am" src="https://cloud.githubusercontent.com/assets/25746260/25094624/a1edc77c-23ca-11e7-8a8f-0bd6be8ca349.png">
<img width="531" alt="screen shot 2017-04-18 at 12 02 42 am" src="https://cloud.githubusercontent.com/assets/25746260/25094631/a9aca4d8-23ca-11e7-9e47-fe4d71a1b249.png">
<img width="747" alt="screen shot 2017-04-18 at 12 02 56 am" src="https://cloud.githubusercontent.com/assets/25746260/25094636/af708a2e-23ca-11e7-8bd8-fa271a5e104b.png">

**Comment by mikejolley** [comment]
repeat for the parent product. Filter it to only show meta_keys with name '_price'. The parent product should have a whole bunch of _price fields.

**Comment by voaooo** [comment]
like this?
<img width="290" alt="screen shot 2017-04-18 at 12 21 43 am" src="https://cloud.githubusercontent.com/assets/25746260/25095181/1e637cdc-23cd-11e7-92e4-178101f6759f.png">

**Comment by mikejolley** [comment]
Yes. Now in addition filter the post_id to the variable product ID with the problem.

**Comment by voaooo** [comment]
i have tried to update several and they all have the same problem.  so i haven't continued and assume the problem occurred on every products.
By the way, it's midnight in HK and I am going offline now.  Thanks for following up and I will reply you tomorrow evening.
Screenshots for three of them for your reference:
<img width="290" alt="screen shot 2017-04-18 at 12 32 53 am" src="https://cloud.githubusercontent.com/assets/25746260/25095621/0a20c78c-23cf-11e7-87d3-154c99740a8d.png">
<img width="255" alt="screen shot 2017-04-18 at 12 33 39 am" src="https://cloud.githubusercontent.com/assets/25746260/25095636/13bcde34-23cf-11e7-9ad8-22e24a5c3f19.png">
<img width="217" alt="screen shot 2017-04-18 at 12 34 19 am" src="https://cloud.githubusercontent.com/assets/25746260/25095640/1a29a004-23cf-11e7-9bb7-a9ce45d2ef2d.png">

**Comment by voaooo** [comment]
any thought on the above?

**Comment by mikejolley** [comment]
I need the results from one product (post_id). There will be multiple rows for each variable

**Comment by voaooo** [comment]
this is one product with 4 variables,
<img width="290" alt="screen shot 2017-04-18 at 12 32 53 am" src="https://cloud.githubusercontent.com/assets/25746260/25239644/21cf13f6-2623-11e7-8e8e-8caee23247c1.png">

second products with 4 variables,
<img width="255" alt="screen shot 2017-04-18 at 12 33 39 am" src="https://cloud.githubusercontent.com/assets/25746260/25239663/3180922a-2623-11e7-8307-5f0a157e2e9e.png">

third products with 4 variables,
<img width="217" alt="screen shot 2017-04-18 at 12 34 19 am" src="https://cloud.githubusercontent.com/assets/25746260/25239678/41abc9e4-2623-11e7-8cf1-e8044bb1bdb2.png">

**Comment by mikejolley** [comment]
No they are not the same product - the id's are all different.

e.g. filter by post ID 101 if thats a variable product (the parent, not the variation).

**Comment by voaooo** [comment]
got it.  do you want me to export?
<img width="287" alt="screen shot 2017-04-21 at 12 00 05 am" src="https://cloud.githubusercontent.com/assets/25746260/25240549/ab68fc74-2625-11e7-9812-781340b2b10f.png">

**Comment by mikejolley** [comment]
Just contact me via WordPress or WooCommerce slack and I'll try looking at the site myself since we're not getting very far here.

**Comment by stefan-media90** [comment]
Hi mikejolley, i have the same problem, prices not sort ok, works only if I always update the variables after publishing a new product. This problem has occurred since the update to 3.0. I tried to disable the modules and the theme but no change. Now all products have updated variables but do not find a solution to this problem: http://shop.roofexpert.ro   I can send you the login to wordpress to do a test. please help me. Thank you!

[problema](https://cloud.githubusercontent.com/assets/27854916/25275350/8320f2ee-269d-11e7-990b-e53b0bbbd2bb.png)

PS: All products are added manually, not imported

**Comment by mikejolley** [comment]
Still unable to replicate this locally but looking into OP site.

**Comment by stefan-media90** [comment]
I can give you private access data to wpadmin and cpanel

**Comment by mikejolley** [comment]
Looking at OP first since what fix works there will probably work for you too.

**Comment by stefan-media90** [comment]
I'm ashamed to ask, but what is OP

**Comment by mikejolley** [comment]
original poster

**Comment by stefan-media90** [comment]
Ah, ok, do you want to do that: "Tools > Export, export the products, send here and give me the ID of the..
?"

**Comment by stefan-media90** [comment]
Hi, thanks, you are the best!!!! It's work only in the main shop page: http://shop.roofexpert.ro/magazin/

If I exchange the file with the one you modified, shop returns missing products in all categories and for sort choices: http://shop.roofexpert.ro/categorie/ferestre-de-mansarda/  

Please help. many thanks!

**Comment by stefan-media90** [comment]
<img src="http://imgur.com/a/BPzXk" alt="" /> I changed with the old one until I get an answer. thank you so much

**Comment by mikejolley** [comment]
I'll update the PR.

**Comment by stefan-media90** [comment]
Ok, please let me know after update, thank you very much

**Comment by mikejolley** [comment]
Updated.

**Comment by stefan-media90** [comment]
You're brilliant! Thank you

**Comment by Hussnain1** [comment]
Hello @mikejolley, I have the same problem. My low to high products sorting is not right and showing random products. My woocommerce version is 4.6.2. I have checked the fix you mentioned above but it's already updated in new woocommerce versions. I can give you private access to backend. Please let me know how can I  fix it. Thanks
<img width="1023" alt="Screen Shot 2021-01-31 at 4 25 51 PM" src="https://user-images.githubusercontent.com/8127852/106383738-0655a680-63e1-11eb-937f-4ab743b225bf.png">
