### ISSUE TITLE
Removed filter woocommerce_single_product_image_html missing in developer migration notes

### ISSUE THREAD

**Issue by mensmaximus** [woocommerce/woocommerce#14152]
The filter hook woocommerce_single_product_image_html has been removed from product-image.php without notice. At least I could not find any information at https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes

I already talked to Mike Jolley about it on slack and I understand the concerns to bring the filter back. However dropping a filter without notice causes a lot of issues for theme developers formerly using that filter hook and not knowing it has been removed.

I would like to suggest to add the removal of this filter hook to the documentation.

**Comment by mikejolley** [comment]
added to https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#deprecated-filters
