### ISSUE TITLE
No Emails Sent To me or to the customer

### ISSUE THREAD

**Issue by moe83** [woocommerce/woocommerce#14151]
### EXPLANATION OF THE ISSUE

hello, after i updated to woocommerce 3.0.1 i started having problems with the emails, i dont get  orders email notifications, and the customer does not get receipt or order confirmation too, the only way to send emails is to go to order actions and (resend new order or customer invoice) and thats hard to send the order confirmation manually.

### STEPS TO REPRODUCE THE ISSUE

i am using the theme (impreza) so i thought the problem is from the theme, i reinstalled the theme and same problem, no emails, 
so i installed woocommerce 2.6 (the old version) and emails came back and worked perfectly, so i am 100% sure now that the issue is from woocommerce not the theme.

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: https://www.tarbooshtv.com
Site URL: https://www.tarbooshtv.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.35 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 35: Unsupported SSL protocol version
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. 200

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

Polylang: by Frédéric Demarle – 2.1.2
Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.9
Authorize.Net WooCommerce Addon: by Syed Nazrul Hassan – 1.0.6
CM Pop-Up banners for WordPress: by CreativeMindsSolutions – 1.2.2
SiteOrigin Widgets by CodeLights: by CodeLights – 1.1.4
Under Construction / Maintenance Mode From Acurax: by Acurax – 2.5.3
Contact Form 7: by Takayuki Miyoshi – 4.7
EWWW Image Optimizer: by Shane Bishop – 3.2.7
WooCommerce shop to Facebook: by StoreYa – 2.4
FormCraft Basic: by nCrafts – 1.0.5
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Limit Login Attempts Reloaded: by wpchefgadget – 2.5.0
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Postman SMTP: by Jason Hendriks – 1.7.2
Prime Extensions For Visual Composer: by codecans – 2.4.4
Process Steps Template Designer: by narinder-singh – 1.0.2
Really Simple SSL: by Rogier Lankhorst – 2.5.11
Slider Revolution: by ThemePunch – 5.4.1
SiteOrigin CSS: by SiteOrigin – 1.1.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.40.1

UpSolution Header Builder: by UpSolution – 1.0.3
User Role Editor: by Vladimir Garagulya – 4.32.3
USPS (BASIC) WooCommerce Shipping: by WooForce – 1.1.8
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 3.6
WooCommerce - APG SMS Notifications: by Art Project Group – 2.11
WooCommerce: by Automattic – 3.0.1
Yoast SEO: by Team Yoast – 4.5
Clef: by Clef – 2.6.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #119 - /products/
Cart: #137 - /shoppin-cart/
Checkout: #919 - /check-out/
My account: #287 - /my-account/

### Theme ###

Name: Impreza
Version: 4.2
Author URL: http://us-themes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Whilst this can be disabled with: https://gist.github.com/mikejolley/16ca078f5c74b401e6ba210644e3173d

I'd look into why these are broken with your host:

Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 35: Unsupported SSL protocol version
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. 200

Background processing which sends mails uses these to do it's posts.

The snippet above will fix your issue if your host cannot help fix the remote posts.

**Comment by TomasHurtz** [comment]
What is this new feature "woocommerce_defer_transactional_emails" where can I read more about this in latest woocommerce version?  I was not aware emails would now be delayed.

Changelog
= 3.0.0 - 2017-04-04 =
* Performance - Deferred email sending for faster checkouts. Now uses CRON.

What is the logic behind this?  If no one visits my site for 24 hrs, emails from last order won't get sent for 24hrs??

Thanks for further insight.

**Comment by dexterdomingo** [comment]
Yeah, also just realized this was the issue. I have no New Order emails being sent out to customers.

I'd like to get this fixed as well.

**Comment by mikejolley** [comment]
@dexterdomingo @TomasHurtz If you want to privately give me access to admin/ftp I'd be happy to look into why background processing is not working on your server.

@TomasHurtz background processing does not work that way. It spawns an event to send any queued emails and keeps spawning itself until the queue is empty.

**Comment by TomasHurtz** [comment]
Well I have tried with and without the functions snippet to disable background processing and I am still not receiving order emails.  Is there any investigation into this issue or is it just me ?

There seems some otheres in this thread: https://wordpress.org/support/topic/3-0-issues-cannot-add-order-email-not-sent-for-new-order-or-other-status/

So is this an "official bug" or not?

**Comment by mikejolley** [comment]
It's closed because if the snippet is not working, and the emails are not being logged by a mail logging plugin (which you should have installed to debug this), then it's a plugin conflict i.e. throwing an error during email generation.

**Comment by motografik** [comment]
It's not working for me either on any WC 3.0+ sites. I even updated to 3.02 and it's still an issue. New order emails are not being sent or received by the user or admin.

**Comment by mikejolley** [comment]
If it works with the gist i posted, if granted access i would happily look into why deferred emails don't work on your server.

**Comment by TomasHurtz** [comment]
I tried with the gist - and now it is working - however, I manage dozens of stores and now I am faced with having to track this "failure" across multiple stores - Not happy about that.  Clearly I am not the only one given the number of posts here and in WP forms.

Latest woocommerce release 3.0.2 did not fix this issue.  

This new feature appears broken.

**Comment by dexterdomingo** [comment]
Hey guys.. Try this one.. This works. v3.01 woocommerce. I've been using it for the past few days.

It's an issue with the woocommerce plugin as I reverted back to a backup and emails came in perfectly fine. Found this fix. Upgraded to 3.01 and added this in functions and boom! Works 👍 

Add this to functions.php.

add_filter( 'woocommerce_defer_transactional_emails', '__return_false' );

**Comment by mikejolley** [comment]
@TomasHurtz offered multiple times to look.

**Comment by TomasHurtz** [comment]
Thanks for offer @mikejolley - please advise what are the server requirements for this to work and I will investigate myself and post results.  I have several WC sites on several servers and the same behaviour exists for all, so I do not think this is a server issue, however appreciate your willingness to assist.

**Comment by mikejolley** [comment]
@TomasHurtz The problem is we don't know what aspects of the server are breaking it - it's just on certain hosting environments. 3.0.3 disables the defer, but I would still like to look in the future since it can be enabled via filter. Email if you'd allow me to do so, or just state which host and we'll grab an account.

**Comment by TomasHurtz** [comment]
OK so 3.0.3 turns off deferred email - does that mean I should now remove all of the Gists I had added to prevent it in the first place - or can I ignore them?  Very messy v 3 release, but is good you are responsive. Thank you.

**Comment by desigstate** [comment]
@mikejolley 

I've been using the gist above since 3.0.1 and its working with 3.0.3 too.

It solved the major problem I had with new order and customer note e-mails not being automatically sent (thanks Mike!), I just wanted to make sure I'm right to think I should mention this code to the [invoice pdf plugin from woocommerce](https://docs.woocommerce.com/document/woocommerce-pdf-invoice-setup-and-customization/) people at WooCommerce since the completed order e-mail I have setup to work with that plugin is not sending automatically?

BTW new order e-mails, on-hold order e-mails, and customer note e-mails (created when a tracking number is created by [Shipstation Plugin for Woocommerce](https://docs.woocommerce.com/document/shipstation-for-woocommerce/) ) are all sending perfectly since adding your gist.

**Comment by KaiserBakunawa** [comment]
@mikejolley my site is running on 3.0.3 but email is still not working. I've also tried the adding the add_filter to functions but it still did not work. My site is on bluehost.

**Comment by rdelooper** [comment]
3.0.3 didn't bring the Solution, e-mail still not working, problem occurs after installing 3.0.1

**Comment by mikejolley** [comment]
If it's not working then it's not related to the CRON stuff and you simply need to enable a mail logging plugin and ensure other plugins are not breaking the send e.g. by triggering errors.

**Comment by drmdesign** [comment]
Hello @mikejolley , I have WC3.0.3 on Aruba Hosting. I've added the string to functions.php.
add_filter( 'woocommerce_defer_transactional_emails', '__return_false' );
It not works.
No email sent.
I hope that something will fix this.
Thank you, 
Andreadrm.

**Comment by ajimix** [comment]
Hello, I'm having exactly the same issue. I'm on 3.0.3 and the emails are only being sent if I do the manual sending but no automatic email is sent after installing 3.0.1 :(

**Comment by mikejolley** [comment]
You're both not reading my last comment :) snippet is no longer needed.

**Comment by ajimix** [comment]
@mikejolley thanks for the fast reply. I haven't added any snippet. I have a clean 3.0.3 installation (by clean I mean that I haven't touched the code of it). Still the emails are only sent if I manually resend them from the order edit panel. No automatically emails are sent.

**Comment by mikejolley** [comment]
Using mail logger?

**Comment by drmdesign** [comment]
Thank you @mikejolley for your support.
Updated to WC 3.0.4, deleted snippet from function.php, using mail logger, same situation.
No emails sent. This is a very frustrating problem.

**Comment by mikejolley** [comment]
Well if nothing is logged, and you're on 3.0.4, it's most definitely an error preventing send - check the server error logs.

If it IS logged, but not sent, it's a server issue and using something like WP Mail SMTP or sendgrid, or both, can help.

**Comment by kdsfx** [comment]
@mikejolley I am having the exact same issue, using 3.0.4 on Bluehost. I never added anything to the functions.php and still cannot get any new order emails. Is the only option to FIX this using a 3rd party SMTP plugin? Although I am seeing posts where people are using these other smtp plugins and its still not working. @drmdesign @ajimix

**Comment by mikejolley** [comment]
Check your logs. it can still be something blocking the send, but it's not related to cron.

**Comment by TonyC5** [comment]
I'm using the 'Postman SMTP' plugin and my new order notification e-mails stopped working after I upgraded from WC 2.6.14 to WC 3.0.5.  I can immediately fix the problem by reverting to WC 2.6.14.  I noticed that the new order notifications with WC 3.0.5 have a "Reply-To" address where notifications sent with WC 2.6.14 do not.  After the upgrade to WC 3.0.5, the Postman SMTP plugin log shows the error "Invalid Reply-To e-mail address."  The Reply-To address is blank.  I'm not certain yet, but it appears that this error may be payment-gateway-dependent.

Can you think of a reason why the Postman SMTP plugin would not get the correct Reply-To address from WooCommerce 3.0.5 and does it make sense that this problem is specific to the payment gateway?

**Comment by TonyC5** [comment]
I have confirmed that the blank Reply-To e-mail address is the problem with WooCommerce 3.0.5 and Postman SMTP.  When I checked the Postman SMTP plugin option to "Disable e-mail verification" (Postman SMTP Settings -> Message Tab -> Disable e-mail validation), the order notification e-mails are sent by WooCommerce 3.0.5 (even though the Reply-To e-mail address is still blank).

**Comment by mikejolley** [comment]
Maybe needs an extra check here https://github.com/woocommerce/woocommerce/blob/36092cba54f62ee2a2b2710f07371fb35620338a/includes/emails/class-wc-email.php#L284

**Comment by mikejolley** [comment]
@TonyC5 Checked and it's all set correctly. I'm adding extra validation to ensure it's set anyway, but you should look to see what in your environment is either setting reply-to, or why this data is not set.

**Comment by TonyC5** [comment]
@mikejolley - Thank you for your quick response!  My WooCommerce and Postman SMTP settings are the same for my WC 2.6.14 and WC 3.0.5 tests, so your extra validation may help me to find the issue.  I'll retest with WC 3.0.5+.  

Thanks for your great plugin and great support.

**Comment by alwiser** [comment]
I'm having the same problem as TonyC5, is there a fix yet?

**Comment by TonyC5** [comment]
@alwiser - WooCommerce (WC) 3.0.6 fixed the issue that I reported.  With the fix, WC 3.0.6 is no longer adding the "Reply-to" field to the admin e-mail header if the customer e-mail and name billing fields are not populated.   If you're still experience your issue with WC 3.0.6, it is possible that your issue is different than mine.  More details below.

Beginning with version 3.0.0, WC started including a "Reply-to" field in admin e-mail headers (like the e-mail header for the new order notification e-mail).  WC derives the Reply-to field from customer billing fields.  This new Reply-to field caused problems for me, because I'm using the `woocommerce_checkout_fields` filter to unset billing fields that I don't require for PayPal standard checkout.  With my empty billing fields, WC 3.0.0-3.0.5 was inserting the text "Reply-to" into the e-mail header without a Reply-to address and Postman SMTP was flagging this empty Reply-to address as an e-mail validation error (unless Postman SMTP e-mail validation was disabled).  Now that WC 3.0.6 validates the billing fields before inserting the "Reply-to" field into the e-mail header, this problem is fixed.

**Comment by twiap** [comment]
In my case the emails get delivered after exactly 3 hours.
Before upgrading to WC 3.0 the emails were delivered almost instantly.
Any idea how to remove this delay?
Thank you

**Comment by jvmauricio** [comment]
same problem as with @twiap , all mails are working prior Version 3.0.8 but now, auto-email sending is not working...

**Comment by mikejolley** [comment]
Not the same issue then is it. 

Once WC send the mail (using wp_mail function) any delay is down to the server. Cron is not used by default any more.

**Comment by jbrenner99** [comment]
We are having the same issue.  Since upgrading from WC 3.0.3 to WC 3.0.8, automatic emails are only sometimes sent.  In all cases where not sent, the order does not contain a Order status changed from Pending payment to Processing.  In addition, any cancelled orders no longer send an email.

**Comment by aselvaraj16** [comment]
I am also having the same issue after the upgrade to WC 3.0.8. The shipping address is not getting registered at the backend, not receiving any order emails, Order status is always in processing but Paypal email is sent to the owner as the order complete. The contact form email works and lost password email works but just not woocommerce emails. Hope there is a fix for this soon.

**Comment by mikejolley** [comment]
I've said several times to use mail logging plugins and rule out the server as a cause of fault (you can use SMTP plugins to send in a different way if needed). Core is not at fault here.
