### ISSUE TITLE
Variation Name Format

### ISSUE THREAD

**Issue by rockeypjb** [woocommerce/woocommerce#14159]
When a customer adds a variable product to their cart the product name has reformatted. This formatting appears in the cart, checkout, emails, and the admin order review. This is how a variable product appeared before v3.0:
<img width="794" alt="screen shot 2017-04-08 at 10 15 55 pm" src="https://cloud.githubusercontent.com/assets/27113199/24834122/619ca52a-1caa-11e7-8be3-fac938b04a84.png">

The product name now contains the variation options, and lists the attributes below:
<img width="787" alt="screen shot 2017-04-08 at 10 16 29 pm" src="https://cloud.githubusercontent.com/assets/27113199/24834135/9f26f88c-1caa-11e7-8687-096960303df4.png">

This makes the products and options chosen more difficult to verify for both the customer and the shop managers.

**Comment by ryankereliuk** [comment]
I discovered this today too.  There does not appear to be a way to override the behavior through filters or configuration.  You can easily hack the WC code to output all the attributes but mangled product names are written to the database so you need to strip attribute information out of the name as well. (If you want some pointers, please ask. Changing the core code makes upgrades more difficult, which makes me reticent to roll it out myself.)

Personally I think the old behavior is better.  If not configurable, I would prefer to have the product name mangling algorithm have customization options through filters.

**Comment by hopesemper** [comment]
Yes, I prefer the old way, is infinitely better for real ecommerces. Seems useful for stores with just one variation, not based in the real world. I hope the old way come back. Just a bad movement.

**Comment by mikejolley** [comment]
@hopesemper please don't assume your setup is the 'real' way over everyone else. If you only have 1 or 2 variation attributes the formatting is much more concise at checkout.

i.e. Some t-shirt - Blue, Large

And let's not forgot, this is what variations were initially designed for. Not for a bazillion attributes at once (that does not scale).

@ryankereliuk there is a filter to remove attribute 'names' but not remove it altogether. We can look into that.

It may also make sense to disable it if there are greater than say 2 attributes present at once. @claudiulodro 

@claudiulodro Another option would be to always list all attributes in backend regardless of title? It's more longwinded however on some setups.

**Comment by ryankereliuk** [comment]
@mikejolley It's not quite that concise.  The new rendering is

Some t-shirt - Color: Blue, Size: Large

which is helpful if somebody thinks the flavor is blue (rather than color) but undermines the aim to make this more concise.  Not so much concise as relocated.  In addition the mangled product names are no longer simple strings but can be considered serialized objects.  Elsewhere in the code, for example, there are regex checks to see of an attribute name is present in the mangled product name.  Without knowing much about the code I would be concerned about scalability and maintainability with this change.

**Comment by rockeypjb** [comment]
I would have to agree with @ryankereliuk, maybe a filter would be the best solution. My store is over 90% variable products, so this change is a big deal.

**Comment by claudiulodro** [comment]
> It may also make sense to disable it if there are greater than say 2 attributes present at once. 

That makes sense. What about a radio select in the Products->Display settings?
```
( X ) List attributes in variable product names.
(   ) List attributes under variable product names.
```
If you don't like the radio, we should definitely add more filters to give people control over the feature if they need it.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14209
