### ISSUE TITLE
Importing products with 0 price is set to no price

### ISSUE THREAD

**Issue by transbetacism** [woocommerce/woocommerce#14168]
### EXPLANATION OF THE ISSUE
As of WooCommerce 3.0, products are no longer shown as Free but are shown as 0 instead.

When importing products with 0 price, the price is set to null instead of $0.

The Add to Cart button is not shown for the products since it has no price and the price is ofcourse missing (instade of being 0).

### STEPS TO REPRODUCE THE ISSUE

This is the product from the file I tried to import:

	  <item>
			<title>Business Card PSD Template</title>
			<link>http://scandinavian.hellodetail.com/shop/business-card-psd-template/</link>
			<pubDate>Tue, 03 May 2016 14:12:58 +0000</pubDate>
			<dc:creator><![CDATA[joakim]]></dc:creator>
			<guid isPermaLink="false">http://scandinavian.hellodetail.com/?post_type=product&#038;p=190</guid>
			<description></description>
			<content:encoded><![CDATA[]]></content:encoded>
			<excerpt:encoded><![CDATA[Time to check off that "order business cards" item from your to-do list? Get a head start with this free Business Card Template. Open the PSD file in Photoshop and update the text (or redesign the whole thing). Links to download the free fonts are included.]]></excerpt:encoded>
			<wp:post_id>190</wp:post_id>
			<wp:post_date><![CDATA[2016-05-03 14:12:58]]></wp:post_date>
			<wp:post_date_gmt><![CDATA[2016-05-03 14:12:58]]></wp:post_date_gmt>
			<wp:comment_status><![CDATA[closed]]></wp:comment_status>
			<wp:ping_status><![CDATA[closed]]></wp:ping_status>
			<wp:post_name><![CDATA[business-card-psd-template]]></wp:post_name>
			<wp:status><![CDATA[publish]]></wp:status>
			<wp:post_parent>0</wp:post_parent>
			<wp:menu_order>120</wp:menu_order>
			<wp:post_type><![CDATA[product]]></wp:post_type>
			<wp:post_password><![CDATA[]]></wp:post_password>
			<wp:is_sticky>0</wp:is_sticky>
			<category domain="product_tag" nicename="branding"><![CDATA[Branding]]></category>
			<category domain="product_tag" nicename="marketing"><![CDATA[Marketing]]></category>
			<category domain="product_type" nicename="simple"><![CDATA[simple]]></category>
			<category domain="product_cat" nicename="stantionery"><![CDATA[Stantionery]]></category>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_edit_last]]></wp:meta_key>
				<wp:meta_value><![CDATA[1]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_product_attributes]]></wp:meta_key>
				<wp:meta_value><![CDATA[a:4:{s:4:"size";a:6:{s:4:"name";s:4:"Size";s:5:"value";s:9:"3.5" x 2"";s:8:"position";s:1:"0";s:10:"is_visible";i:1;s:12:"is_variation";i:0;s:11:"is_taxonomy";i:0;}s:11:"file-format";a:6:{s:4:"name";s:11:"File format";s:5:"value";s:3:"PSD";s:8:"position";s:1:"1";s:10:"is_visible";i:1;s:12:"is_variation";i:0;s:11:"is_taxonomy";i:0;}s:10:"fonts-used";a:6:{s:4:"name";s:10:"Fonts used";s:5:"value";s:36:"Butler Stencil | American Typewriter";s:8:"position";s:1:"2";s:10:"is_visible";i:1;s:12:"is_variation";i:0;s:11:"is_taxonomy";i:0;}s:7:"licence";a:6:{s:4:"name";s:7:"Licence";s:5:"value";s:44:"Who needs licences? Use it however you like.";s:8:"position";s:1:"3";s:10:"is_visible";i:1;s:12:"is_variation";i:0;s:11:"is_taxonomy";i:0;}}]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_visibility]]></wp:meta_key>
				<wp:meta_value><![CDATA[visible]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_stock_status]]></wp:meta_key>
				<wp:meta_value><![CDATA[instock]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[total_sales]]></wp:meta_key>
				<wp:meta_value><![CDATA[0]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_downloadable]]></wp:meta_key>
				<wp:meta_value><![CDATA[yes]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_virtual]]></wp:meta_key>
				<wp:meta_value><![CDATA[yes]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_tax_status]]></wp:meta_key>
				<wp:meta_value><![CDATA[taxable]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_tax_class]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_purchase_note]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_featured]]></wp:meta_key>
				<wp:meta_value><![CDATA[yes]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_weight]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_length]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_width]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_height]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_sku]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_regular_price]]></wp:meta_key>
				<wp:meta_value><![CDATA[0]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_sale_price]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_sale_price_dates_from]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_sale_price_dates_to]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_price]]></wp:meta_key>
				<wp:meta_value><![CDATA[0]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_sold_individually]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_manage_stock]]></wp:meta_key>
				<wp:meta_value><![CDATA[no]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_backorders]]></wp:meta_key>
				<wp:meta_value><![CDATA[no]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_stock]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_upsell_ids]]></wp:meta_key>
				<wp:meta_value><![CDATA[a:0:{}]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_crosssell_ids]]></wp:meta_key>
				<wp:meta_value><![CDATA[a:0:{}]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_downloadable_files]]></wp:meta_key>
				<wp:meta_value><![CDATA[a:0:{}]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_download_limit]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_download_expiry]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_download_type]]></wp:meta_key>
				<wp:meta_value><![CDATA[]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_product_version]]></wp:meta_key>
				<wp:meta_value><![CDATA[2.6.13]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_product_image_gallery]]></wp:meta_key>
				<wp:meta_value><![CDATA[192,195]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_wc_rating_count]]></wp:meta_key>
				<wp:meta_value><![CDATA[a:0:{}]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_wc_average_rating]]></wp:meta_key>
				<wp:meta_value><![CDATA[0]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_wc_review_count]]></wp:meta_key>
				<wp:meta_value><![CDATA[0]]></wp:meta_value>
			</wp:postmeta>
			<wp:postmeta>
				<wp:meta_key><![CDATA[_thumbnail_id]]></wp:meta_key>
				<wp:meta_value><![CDATA[197]]></wp:meta_value>
			</wp:postmeta>
		</item>

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://localhost:8888/smoke
Site URL: http://localhost:8888/smoke
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.0.15 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.0.15
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (6) ###

Contact Form 7: by Takayuki Miyoshi – 4.7
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
Image Widget: by Modern Tribe
Inc. – 4.3.1

One Click Demo Import: by ProteusThemes – 2.2.1
WooCommerce: by Automattic – 3.0.1
WP Retina 2x: by Jordy Meow – 4.8.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/

### Theme ###

Name: Scandinavian Child
Version: 1.0
Author URL: http://www.hellodetail.com/
Child Theme: ✔
Parent Theme Name: Scandinavian
Parent Theme Version: 1.1
Parent Theme Author URL: http://www.hellodetail.com/
WooCommerce Support: ✔

### Templates ###

Overrides: scandinavian/woocommerce/archive-product.php
scandinavian/woocommerce/cart/cart-shipping.php
scandinavian/woocommerce/cart/cart-totals.php
scandinavian/woocommerce/cart/cart.php
scandinavian/woocommerce/checkout/form-checkout.php
scandinavian/woocommerce/checkout/form-coupon.php
scandinavian/woocommerce/checkout/payment.php
scandinavian/woocommerce/checkout/review-order.php
scandinavian/woocommerce/checkout/thankyou.php
scandinavian/woocommerce/content-product.php
scandinavian/woocommerce/content-single-product.php
scandinavian/woocommerce/global/wrapper-end.php
scandinavian/woocommerce/global/wrapper-start.php
scandinavian/woocommerce/loop/add-to-cart.php
scandinavian/woocommerce/loop/loop-end.php
scandinavian/woocommerce/loop/loop-start.php
scandinavian/woocommerce/loop/orderby.php
scandinavian/woocommerce/loop/pagination.php
scandinavian/woocommerce/loop/price.php
scandinavian/woocommerce/loop/rating.php
scandinavian/woocommerce/loop/result-count.php
scandinavian/woocommerce/loop/sale-flash.php
scandinavian/woocommerce/myaccount/form-login.php
scandinavian/woocommerce/myaccount/my-account.php
scandinavian/woocommerce/myaccount/navigation.php
scandinavian/woocommerce/notices/error.php
scandinavian/woocommerce/notices/notice.php
scandinavian/woocommerce/notices/success.php
scandinavian/woocommerce/single-product/product-image.php
scandinavian/woocommerce/single-product/product-thumbnails.php
scandinavian/woocommerce/single-product/related.php
scandinavian/woocommerce/single-product/review-meta.php
scandinavian/woocommerce/single-product/tabs/tabs.php
scandinavian/woocommerce/single-product-reviews.php

`
</details>

**Comment by mikejolley** [comment]
The 0 instead of free is intentional. As for import, I set _price to 0, _regular_price to 0 and _sale_price blank. After import, it worked as expected.

![2017-04-11 at 19 45](https://cloud.githubusercontent.com/assets/90977/24925250/9212ba40-1eef-11e7-953e-f1c292f68b0b.png)
![2017-04-11 at 19 45 2](https://cloud.githubusercontent.com/assets/90977/24925254/93feba20-1eef-11e7-8b10-5e1fe6a0f1b0.png)
