### ISSUE TITLE
Error upon editing products

### ISSUE THREAD

**Issue by highacid** [woocommerce/woocommerce#14161]
### EXPLANATION OF THE ISSUE

3.0.1

### STEPS TO REPRODUCE THE ISSUE

The user wants to edit with Edit button from WP Admin products he gets the error bellow

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.tabaklaedeli.ch
Site URL: https://www.tabaklaedeli.ch
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

WPBruiser Pro: von Mihai Chelaru – 1.3.1
Ninja Popups: von ArsCode – 4.4.6
Comet Cache Pro: von WebSharks
Inc. – 170220

Contact Form 7: von Takayuki Miyoshi – 4.7
Envato Market: von Derek Herman – 1.0.0-RC2
OPcache Dashboard: von Daisuke Takahashi(Extend Wings) – 0.3.1
WooCommerce Product Filter: von Mihajlovic Nenad – 6.1.1
Velvet Blues Update URLs: von VelvetBlues.com – 3.2.7
WooCommerce PDF Invoice: von RightPress – 3.0
WooCommerce: von Automattic – 3.0.1
WooCommerce SaferpayCw: von customweb GmbH – 5.0.65
Yoast SEO Premium: von Team Yoast – 4.5
WP-Piwik: von André Bräkling – 1.0.14

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CHF (CHF)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #1 - /shop/
Warenkorb: #2 - /warenkorb/
Kasse: #3 - /kasse/
My account: #4 - /mein-konto/

### Theme ###

Name: Flatsome Child Theme
Version: 2.5
Author URL: http:%20//www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.2
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`
</details>

This is our error:

`Fatal error: Uncaught Exception: Ungültige Bestellung. in /home/tabaklaedeli/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:86 Stack trace: #0 /home/tabaklaedeli/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(143): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order)) #1 /home/tabaklaedeli/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(109): WC_Data_Store->read(Object(WC_Order)) #2 /home/tabaklaedeli/public_html/wp-content/plugins/woocommerce-pdf-invoice/woocommerce-pdf-invoice.php(1825): WC_Abstract_Order->__construct('4589') #3 /home/tabaklaedeli/public_html/wp-includes/class-wp-hook.php(300): WooPDF->add_woo_pdf_metabox('product') #4 /home/tabaklaedeli/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #5 /home/tabaklaedeli/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #6 /home/tabaklaedeli/public_html/wp-admin/edit-form-advanced.php(324): do_act in /home/tabaklaedeli/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 86`

**Comment by rynaldos** [comment]
Hi @highacid 

The problem is coming from WooCommerce PDF Invoice plugin (Rightpress). You'll need to update to version 3.1.4 of the plugin to resolve this issue. 

See: https://codecanyon.net/item/woocommerce-pdf-invoice/5951088/comments?page=50&filter=all#comment_16150125

Cheers!
