### ISSUE TITLE
Duplicate Product Categories 

### ISSUE THREAD

**Issue by dlareg08** [woocommerce/woocommerce#14167]
Duplicate Product Categories

My Product Categories was duplicated. If i delete one of them then both will be remove. Im using the current version. WC 3.0.1 I already deactivated all my plugins to see if the issue will be solved but nothing happened. Tried to use the built in theme twenty fourteen, and fifteen but issue still present

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: https://www.derby.com.kw
Site URL: https://www.derby.com.kw
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.21
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_load_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Akismet Anti-Spam: by Automattic – 3.3
BackWPup: by Inpsyde GmbH – 3.3.7
Contact Form 7: by Takayuki Miyoshi – 4.7
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
Hello Dolly: by Matt Mullenweg – 1.6
Jetpack by WordPress.com: by Automattic – 4.8.2
WooCommerce KNET gateway: by Firoz Udaipurwala – 1.2
Limit Login Attempts Reloaded: by wpchefgadget – 2.5.0
MOJO Marketplace: by Mike Hansen – 1.1.3
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Ninja Forms: by The WP Ninjas – 3.0.31
qTranslate-X: by qTranslate Team – 3.4.6.8
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Simple History: by Pär Thernström – 2.13
SSL Insecure Content Fixer: by WebAware – 2.2.3
WooCommerce Weight Based Shipping: by dangoodman – 4.2.3
All Currencies for WooCommerce: by Algoritmika Ltd – 2.0.2
WooCommerce Currency Switcher: by realmag777 – 2.1.9
WooCommerce CyberSource SA SOP Gateway: by WooThemes / SkyVerge – 2.6.0 – 2.7.0 is available
WooCommerce PDF Invoice: by RightPress – 3.1.3
WooCommerce & qTranslate-X: by qTranslate Team – 1.3
WooCommerce: by Automattic – 3.0.1
WooSidebars: by WooThemes – 1.4.3
Wordfence Security: by Wordfence – 6.3.6
Yoast SEO: by Team Yoast – 4.5
WP Instagram Widget: by Scott Evans – 1.9.8
YITH WooCommerce Ajax Search: by YITHEMES – 1.5.2
YITH WooCommerce Wishlist: by YITHEMES – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: KWD (KWD)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 3
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: Flatsome
Version: 3.3.2
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php


### CyberSource SA SOP ###

Environment: Live
`
```
</details>

**Comment by faisal-alvi** [comment]
Why don't you try exporting data and importing in a another fresh WooCommerce and check if the problem is solved?

**Comment by dlareg08** [comment]
Dear Faisal,
Hi how are you?thank you for the reply. I saw from the error logs that im
having wordpress database error duplicate key name for the following;
attribute_name, download_order_key_product, meta_key, tax_rate_state,
tax_rate_class and location_type_code.

I will also try your suggestion. Thanks!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by faisal-alvi** [comment]
I'm Fine @dlareg08 Thank you!

Have a look at this too - https://core.trac.wordpress.org/ticket/34870

**Comment by dlareg08** [comment]
Dear,

I tried Export Import Data. I was able to add it in a new woocommerce but
the variations where missing. i have a lot of product with variations so i
think this will not be the best way to solve the issue.

This issue happened when there was update to woocommerce. I hope there is a
fix to remove the duplicate.

Thanks



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mikejolley** [comment]
Since WooCommerce core has no upgrade routine or code to duplicate categories I'm going to say this is related to translation plugins which DO duplicate terms into other languages. If you delete one, most of those plugins sync it across all translated terms. 

WooCommerce & qTranslate-X? It was last updated a year ago so has not had 3.0 compatibility work done.

**Comment by dlareg08** [comment]
Dear,

I also have other test site that has woocommerce & qtranslate-x installed
activated and has the updated woocommerce version and it doesnt have
duplicates on product categories. While the other one has duplicates.

Deactivating and uninstall of the said plugin didnt resolve the issue.



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dlareg08** [comment]
Dear Mike,

Good day! My duplicate product categories is now solved. I've seen your
post last 9 months ago in this link -
https://github.com/woocommerce/woocommerce/commit/1e70bc71720d76d34d38940e5915da7e33c583c2

and i compared it with my wc-term-functions.php and im having these*
$clauses['fields'] = 'DISTINCT ' . $clauses['fields'] . ', tm.meta_value'; *

i removed the last part . ', tm.meta_value' save it and boom...duplicates
are gone.

But i have 1 more to issue to solve, if my old product  is set to a
category and uncategorized or remove the link, it show out of stock even
though it has stock. You think i need to remove some part of code again?

Thanks!






<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by mikejolley** [comment]
@dlareg08 Can you do this instead and tell me if it helps? https://github.com/woocommerce/woocommerce/pull/14291

**Comment by dlareg08** [comment]
Dear Mike,

Hi! I tried to put $clauses['fields'] = 'DISTINCT t.term_id, tm.meta_value,
' . $clauses['fields']; and it showed me again the
duplicate product categories.

I tries this $clauses['fields'] = 'DISTINCT t.term_id,' . $clauses['fields'];
and showed no duplicate product categories
but the old product unassigned shows no stock even it has stock. new
products created and assigned are good
and shows the true stock status.

**Comment by neko-in-space** [comment]
I had duplicated categories in the backend and frontend after an update as well but on WC Version 3.0.4 and WP Version 4.7.4 and I do not use qTranslate-X plugin.

@mikejolley [#14291](https://github.com/woocommerce/woocommerce/pull/14291) didn't work.
@dlareg08 Your solution worked for me, thank you!

**Comment by dlareg08** [comment]
Dear,

Im glad that your issue has been solved. It is actually mike's work which i
just removed some part.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jgonzo127** [comment]
I'm getting this duplication issue as well. Any word on if this will be fixed in an upcoming release?

**Comment by mikejolley** [comment]
The query change is not supported on some SQL environments. qTranslate-X  works for me. It has the option to update legacy data into the new format which seems to not have the issue. Old qTranslate-X made a duplicate into each language for each category.

**Comment by socketbox** [comment]
Had the same issue but had never heard of qTranslate-X. Used fix proposed by @dlareg08 to good effect.

**Comment by Ground29** [comment]
Hi, I am getting double post now and in backend of store looks fine, just the front of store where I am seeing doubles. I'm using printful to upload my products. Printful side looks fine too. When I upload to store from printful everything looks fine but when I go to storefront I see double and when it doubles it take a place on a older product and hides it. In backend everything looks normal. Need help please been trying to fix this for weeks now. Thanks
