### ISSUE TITLE
Adding New Products with Elementor & Elementor Pro

### ISSUE THREAD

**Issue by Drysand** [woocommerce/woocommerce#14166]
### EXPLANATION OF THE ISSUE

I am running fully updated versions of both Elementor and WooCommerce. When I add a new product to my store all seems to save fine. They can be found in searches on woocommerce and show on the shop page. 

New items however will not load through then using elementor to design your page. 

My hosting team say: 
Hi, I think the problem is with the plugin. It looks like bad coding. The server's web application firewall says that the request contains content but there is no Content-Type header. If you pass that back to the developers perhaps they can fix it by making sure a valid Content-Type is included in the header.
Kind Regards,
Chris.

Elementor say:
Hi,

Thank you for the reply.

The code is from WooCommerce. Can you report the issue to them?

### STEPS TO REPRODUCE THE ISSUE

Edit page with elementor, select woo products widget and select any filter or option. Product created before the update always load but post update nothing.

### SYSTEM STATUS

<details>
```

### WordPress Environment ###

Home URL: https://monkey-nutz.com
Site URL: https://monkey-nutz.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: mnz17_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Cookie Notice: by dFactory – 1.2.38
Customizer Export/Import: by The Beaver Builder Team – 0.6
Elementor Pro: by Elementor.com – 1.2.4
Elementor: by Elementor.com – 1.4.2
Features: by WooThemes – 1.5.0
Icons For Features: by WooThemes – 1.1.0
Jetpack by WordPress.com: by Automattic – 4.8.2
Loginizer: by Raj Kothari – 1.3.4
Ocean Extra: by OceanWP – 1.2.0.1
Testimonials: by WooThemes – 1.5.4
WooCommerce Amazon Pay Gateway: by WooCommerce – 1.7.0
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.0
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce: by Automattic – 3.0.1
WooSidebars - Sidebar Manager to WooSidebars Converter: by WooThemes – 1.1.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: OceanWP Child
Version: 1.0
Author URL: https://oceanwp.org/
Child Theme: ✔
Parent Theme Name: OceanWP
Parent Theme Version: 1.1.8
Parent Theme Author URL: https://oceanwp.org/about-me/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: oceanwp/woocommerce/archive-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/product-image.php
oceanwp/woocommerce/single-product/title.php

</details>

<!--
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
-->

**Comment by mikejolley** [comment]
I installed it to test and added the widget. It appeared to show products fine:

![2017-04-10 at 15 33](https://cloud.githubusercontent.com/assets/90977/24866792/25ea2d90-1e03-11e7-8405-4691fb8ac2ff.png)

Cached widget? Add to your sidebar via regular interface. Should be the same.

**Comment by Drysand** [comment]
Hi Thanks for your response.

That is the wooCommerce products widget and works with me fine.

Sorry if I gave the wrong info but it’s the woo -products widget that doesn’t work.

Below I have added the icon.
[cid:image001.png@01D2B22E.6A188FC0]

Thanks ,
Dan



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mikejolley** [comment]
What widget? I don't know which one you mean. Screenshot? Is it even from core?

**Comment by Drysand** [comment]
It’s from elementor pro options.

I’ve gone to my hosting who say it’s incorrect code. And I’ve gone to Elementor team who say it’s a problem with WooCommerce’s code.

I have uninstalled the whole store and re-installed WP, Woo and Elementor from scratch again but the issue is still there.

Let me know if you need more info.

Kind regards,
Dan



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mikejolley** [comment]
> It’s from elementor pro options.

If this is a custom "elementor pro" widget I fail to see how WooCommerce can be responsible. Sorry you're being passed off between support areas, but this **sounds** like an elementor pro feature. If you have a screenshot I can check to make sure you're not talking about a WooCommerce core component.

(please reply on github, your email footer is coming though with your replies).

**Comment by Drysand** [comment]
Yeah it's a pro widget. I agree with you on this, appreciate your time, thanks again! 

I'll go back to the Elementor team.

**Comment by mikejolley** [comment]
👍 Feel free to send them to this thread if they disagree. No point you being messenger.

**Comment by petemah** [comment]
Hello, were you able to fix the problem OP? 

Also facing the same exact issue. Very frustrating when upgrading to the Pro version is actually giving more problems than the free. 

Makes no sense that the free "Woocommerce - products" seems to at least load the products. 

But the Pro "Woo - Products" loads nothing. 


Also I find it a bit disappointing that Elementor pro didn't come with a menu widget. To go along with the Elementor Canvas template.

**Comment by Drysand** [comment]
Hi, 

Unfortunately not. No one would claim the issue was with their code and I ended up getting a refund for Elementor Pro and deleted my whole store. Trying Prestashop now so hopefully this will work. But me back a few months though so not great.

Fingers crossed you can find a resolution.

**Comment by petemah** [comment]
Elementor pro just released an update yesterday. And it fixed my problems!
(same exact problems as you)

Perhaps you can give them another chance.


I know it sucks that you already got a refund. But I liked their app as a
whole because it was so easy to use.


Was just frustrated that the first 5 days in. I basically couldn't use it...

**Comment by rianrenton** [comment]
This thread seems to address my own problem that is driving me nuts.

I am working up a website using the Generate Press theme, Elementor and WooCommerce and have found the Elementor "Edit Woo-Products" Query function unresponsive. While I have several products available, no products or tags show whether I pick "Products or "Manual Selection"as the source. I am not able to type anything into the "Search and Select" or the "Product tag" boxes.

All of my updates are loaded so I believe I am working with the most up-to-date software.

Ideas anyone? Has anyone come up with a solution?

**Comment by Tizara** [comment]
While i also looked everywhere to solve this issue, i found my sollution in the fact that my article only showing up when i change the stock from not available to available. Product is only shown when it is in stock.
