### ISSUE TITLE
WC 3.0.0 Virtual Download product - issues with download exipry

### ISSUE THREAD

**Issue by lifeforceinst** [woocommerce/woocommerce#14163]
**### EXPLANATION OF THE ISSUE**

Brief explanation: if the "Download Expiry" date is set, then as soon as the customer downloads the item the expiry sate is set to the current time (the expiry time should not be changed).

This means if you wanted to create a webshop where the end customer could download a document up to 4 times within 2 days this is not possible and indeed setting any time limit means the file can ever only be downloaded once.

The testing performed with the customer and then for a few hours determined that these value can not both be set and indeed if the "Download Expiry" is set, then under all circumstances the customer of the shop can only download the item once, because as soon as the download occurrs, the download expiry date in the order is changed from a future date to the current date. 

### STEPS TO REPRODUCE THE ISSUE

The use scenario is WooCommerce 3.0.0 setup with 10 virtual downloadable products and the setting of the "Download Limit" and "Download Expiry" values, with most items being proverbially out of the box settings.

CASE 1: Make a virtual downloadable product with the following download limits:
- Setting the "Download Limit" to 4 (times) & "Download Expiry" to 2 (days) for a product.
- Then have a customer places an order for this product.
- This results in the order being set correctly such that Download Limit = 4 (times) & the Download Expiry is set to 2 days in the future.
- Then when the customer downloads the file, the available download count is correctly reduced by one; BUT the download expiry time is then also set to the current time. This means that the customer cannot download the item again even through the download count remains at 3.

CASE 2: Make a virtual downloadable product with the following download limits: 
- Setting the "Download Limit" to 4 (times) & "Download Expiry" to Never for a product.
- Then have a customer places an order for this product,
- Results in the order being set correctly such that Download Limit = 4 (times) & the Download Expiry is set to never. 
- Then when the customer downloads the file, the available download count is correctly reduced by one; and the download date is left unchanged (at never).
- The customer can then continue to download their document a further 3 times.
- THIS CASE WORKS EXACTLY AS EXPECTED :)

CASE 3: Make a virtual downloadable product with the following download limits: 
- Setting the "Download Limit" to Unlimited & "Download Expiry" to 2 (days) for a product.
- Then have a customer places an order for this product.
- Results in the order being set correctly such that Download Limit = Unlimited & the Download Expiry is set to 2 days in the future.
- Then when the customer downloads the file, the download expiry time is then also set to the current time. This means that the customer cannot download any future versions. 
*** IN MY VIEW THIS IS BROKEN, you should not change the expiry date of the download when the customer performs a download, it should be left unchanged.

### WordPress Environment ###
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Memory Limit: 384 MB
WP Cron: ✔
Language: en_GB

### Server Environment ###
Server Info: Apache/2.4.25 OpenSSL/1.0.2j PHP/5.6.30
PHP Version: 5.6.30
PHP Post Max Size: 16 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###
WC Database Version: 3.0.0
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###
Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###
WooCommerce: by Automattic – 3.0.0

**Comment by lifeforceinst** [comment]
I have also tested with 3.0.1 and the issue is still apparent

**Comment by mensmaximus** [comment]
With each download the access_expires and access_granted property get reduced by one day. This maybe caused in WC_Customer_Download_Data_Store->update() while building the $data array to be stored:

```php
$data = array(
			'download_id'         => $download->get_download_id( 'edit' ),
			'product_id'          => $download->get_product_id( 'edit' ),
			'user_id'             => $download->get_user_id( 'edit' ),
			'user_email'          => $download->get_user_email( 'edit' ),
			'order_id'            => $download->get_order_id( 'edit' ),
			'order_key'           => $download->get_order_key( 'edit' ),
			'downloads_remaining' => $download->get_downloads_remaining( 'edit' ),
			'access_granted'      => date( 'Y-m-d', $download->get_access_granted( 'edit' )->getTimestamp() ),
			'download_count'      => $download->get_download_count( 'edit' ),
			'access_expires'      => ! is_null( $download->get_access_expires( 'edit' ) ) ? date( 'Y-m-d', $download->get_access_expires( 'edit' )->getTimestamp() ) : null,
		);
```

Fetching the $data array before save I got

`
Array
(
    [download_id] => bd95c0eeb4d116a5be331d6481be73f6
    [product_id] => 343
    [user_id] => 1
    [user_email] => mw@izd.de
    [order_id] => 345
    [order_key] => wc_order_58ea509e3eda2
    [downloads_remaining] => 2
    [access_granted] => 2017-04-07
    [download_count] => 2
    [access_expires] => 2017-04-09
)
`

for a download created on 2017-04-09 expiring on 2017-04-11 after the second download.

**Comment by mensmaximus** [comment]
As far as I can say the issue stems from

`date( 'Y-m-d', $download->get_access_granted( 'edit' )->getTimestamp() )`

Unfortunately the new CRUD drives me nuts. Normally I would say calling getTimestamp() creates a new timestamp which in case of an update seems wrong. Therefore i modified the line to

`date( 'Y-m-d', $download->get_access_granted( 'edit' ) )`

which returns an empty value. Therefore I inspected the return value of

`$download->get_access_granted( 'edit' )`

and got an object

```
WC_DateTime Object
(
    [utc_offset:protected] => 0
    [date] => 2017-04-07 00:00:00.000000
    [timezone_type] => 3
    [timezone] => Europe/Berlin
)
```

Therefore I tried

`$download->get_access_granted( 'edit' )->date`

but I get an empty value.

**Comment by mensmaximus** [comment]
Maybe this helps: If I edit an order in the backend and set a new date for 'Access expires' in the 'Downloadable product permissions' metabox and save the order the date displayed is one day off.

I enter 2017-04-30, save the order, expand the product in the metabox again and the expire date showy 2017-04-29. If I save it again the date changes to 2017-04-28.

**Comment by mensmaximus** [comment]
The issue occurs only in timezones larger than UTC (+1, +2, +3, etc.). If i select Europe/Berlin the displayed value is always on day off than the stored value. If I choose Amercia/New York the displayed and stored value for accees_granted and access_expires are always identical.

**Comment by mensmaximus** [comment]
Maybe related 
https://core.trac.wordpress.org/ticket/33624

**Comment by lifeforceinst** [comment]
So I think a fundamental question, at least from my perspective is why is the download expiry being changed after is it initially set when the customer orders the product.  There are two settings for a product limitations for downloads being: Download limit and Download expiry.  

In my opinion the Download expiry should never be reduced when a customer downloads a product; there is a separate item download limit for this purpose, trying to make the expiry date perform both functions seems illogical.

The logic for checking the eligibility for download of a product should be:
If (current date < expiry date) && (times downloaded < download limit) then
   allow download
   then increment times downloaded
else
  deny access message & optionally log reason
endif

**Comment by mensmaximus** [comment]
I would consider this a bug too ;-) I guess the problem occurs because each time a download is triggered the new CRUD function set_props is executed and because the whole $data array is saved each time the date displaying wrong (see explanation above about i18n) decrements both the access_granted and access_expires. This is not a faulty logic as one might think it is 'simply' an inconsistent handling of date values that might be related to i18n.

**Comment by mikejolley** [comment]
I see the issue. Read reads a y-m-d date format and assumes it's local time, when it's not, it's UTC.
