### ISSUE TITLE
Broken translation functionality

### ISSUE THREAD

**Issue by Anwenderix** [woocommerce/woocommerce#14169]
### EXPLANATION OF THE ISSUE

After Update of WooCommerce (now 3.0.1 and Germanized now 1.8.8) cart-buttons and billing Details are now in english. I expected them to stay in German.

### STEPS TO REPRODUCE THE ISSUE

Just updating... I guess.

### SYSTEM STATUS

<details>
```
WordPress environment
Home URL:

http://weltbaby.de
Site URL:

http://weltbaby.de
WC version:

3.0.1
Log directory writable:

 /home/u163238127/public_html/wp-content/uploads/wc-logs/ 
WP version:

4.7.3
WP multisite:

–
WP memory limit:

256 MB
WP debug mode:

– 
WP cron:

 
Sprache:

de_DE
```
</details>

**Comment by Anwenderix** [comment]
Ok, I found out that the problem is just that translation is not ready yet. However the translation that I was looking for has been done 5 days ago according to the list. The language in the cart and checkout is important for our customers! They do not buy if they feel uncomfortable with it. Therefore it should be high priority. I would have done it myself, if it could have been found via Loco-plugin. Unfortunately it is not found. Do you know when it will be available?

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/updating-translations-after-updates/

Translations are community managed so I cannot give you a date. See that ^ and you can help. Outdated translation files is not a core bug/missing functionality.
