### ISSUE TITLE
Call to a member function get_upsell_ids() on null

### ISSUE THREAD

**Issue by mensmaximus** [woocommerce/woocommerce#14162]
### EXPLANATION OF THE ISSUE

Using the shortcode [product_page] causes a fatal error if woocommerce_upsell_display() gets unhooked and a custom function calling woocommerce_upsell_display() its self gets hooked in after woocommerce_output_related_products().

This error maybe related to the new CRUD approach in woocommerce_upsell_display() at line 1324 in wc-template-functions.php because $product is empty. 

The issue does no occur if you hook in your custom function before woocommerce_output_related_products().

Calling the single product page works well in both cases and displays both the upsells and related products. 

### STEPS TO REPRODUCE THE ISSUE

1. Unhook woocommerce_upsell_display() and hook your own function to the woocommerce_after_single_product_summary action hook.

```php
remove_action( 'woocommerce_after_single_product_summary', 'woocommerce_upsell_display', 15 );
remove_action( 'woocommerce_after_single_product', 'woocommerce_upsell_display', 10);
// hook in after woocommerce_output_related_products() that has priority 20
add_action( 'woocommerce_after_single_product_summary', 'my_output_upsells', 21);
function my_output_upsells($items = false, $columns = false) {
    $output = "";
    if(!$items) $items = 4;
    if(!$columns) $columns = 4;
    ob_start();
    woocommerce_upsell_display($items,$columns);
    $output = ob_get_clean();
    echo $output;
}
```

2. Add [product_page id="99"] to a static page (replace id with an id of an existing product)

3. Call the page in your browser.

### LOGS

```
[09-Apr-2017 08:49:33 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_upsell_ids() on null in /var/www/websites/woo.mensmaximus.com/htdocs/
wp-content/plugins/woocommerce/includes/wc-template-functions.php:1324
Stack trace:
#0 /var/www/websites/woo.mensmaximus.com/htdocs/wp-content/themes/twentysixteen/functions.php(436): woocommerce_upsell_display(4, 4)
#1 /var/www/websites/woo.mensmaximus.com/htdocs/wp-includes/class-wp-hook.php(298): my_output_upsells(4)
#2 /var/www/websites/woo.mensmaximus.com/htdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#3 /var/www/websites/woo.mensmaximus.com/htdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /var/www/websites/woo.mensmaximus.com/htdocs/wp-content/plugins/woocommerce/templates/content-single-product.php(79): do_action('woocommerce_aft...')
#5 /var/www/websites/woo.mensmaximus.com/htdocs/wp-includes/template.php(686): require('/var/www/websit...')
#6 /var/www/websites/woo.mensmaximus.com/htdocs/wp-content/plugins/woocommerce/includes/wc-core-functi in /var/www/websites/woo.mensmaximus.com/htdocs/wp-conten
t/plugins/woocommerce/includes/wc-template-functions.php on line 1324
```

**Comment by mensmaximus** [comment]
The patch does not fix this issue. Using my example above upsell products are not displayed anymore even if exist using the product_page shortcode.

**Comment by mikejolley** [comment]
My patch addresses the fatal error, which itself is caused by a missing $product global. As for the issue, even after snippet i have no problems:

![2017-04-12 at 10 20](https://cloud.githubusercontent.com/assets/90977/24950680/baf7fd06-1f69-11e7-98ca-819701ad647c.png)

**Comment by mensmaximus** [comment]
@mikejolley you still have access to woo.mensmaximus.com

Call to the single product shows cross sells
https://woo.mensmaximus.com/product/test-physical/

Call to a page including the same product via shortcode product_page does not show cross sells
https://woo.mensmaximus.com/beispiel-seite/ 

Please keep in mind my description to hook cross sells after related products.

**Comment by mikejolley** [comment]
I see, I placed the snippet in wrong file.

**Comment by mensmaximus** [comment]
The issue I described is still not solved in Woo 3.0.3

**Comment by mikejolley** [comment]
@mensmaximus it won't be - the PR is marked for 3.1. It's a larger change not suitable for a fix release.

**Comment by aromboli** [comment]
Guy - I get this error: Fatal error: Call to a member function get_cart() on null in /home/aromboli/public_html/explora/wp-content/plugins/woo-mercado-pago-module/mercadopago/mercadopago-gateway.php on line 1367 

Any ideas on hoe to solve it? It appears when I activate the woo subscriptions plugin.

**Comment by pinkrada** [comment]
I get the same issue with aromboli. I hope someone can help us with this

Fatal error: Call to a member function get_cart() on null , mine in on functions.php
