### ISSUE TITLE
Woocommerce not sending automatic emails

### ISSUE THREAD

**Issue by tehmooo** [woocommerce/woocommerce#14170]
### EXPLANATION OF THE ISSUE

During the order process, no automatic emails are sent. If i go into an order and manually get woocommerce to 'resend' emails, they send correctly - but no automatic emails send during the normal process.

Things I have tested that do work:
- Wordpress's password recovery email
- manually sending emails via the order options
- installing an SMTP plugin and sending test emails (still wont send automatic emails)
- uninstalling an SMTP plugin and sending manual emails

### STEPS TO REPRODUCE THE ISSUE

Purchasing an item does not send an email

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://stickerkitten.co.uk
Site URL: https://stickerkitten.co.uk
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.9
Akismet Anti-Spam: by Automattic – 3.3
hey-jax: by James Douglas – 0.1
Jetpack by WordPress.com: by Automattic – 4.8.2
MailChimp for WordPress: by ibericode – 4.1.0
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce: by Automattic – 3.0.1
WooHoo: by James Douglas – 0.01
Yoast SEO: by Team Yoast – 4.5
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP Super Cache: by Automattic – 1.4.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #753 - /shop/
Basket: #1121 - /cart/
Checkout: #1122 - /checkout/
My account: #1123 - /my-account/

### Theme ###

Name: StickerKittenTheme
Version: 1.0
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: stickerkitten/woocommerce/archive-product.php
stickerkitten/woocommerce/auth/footer.php
stickerkitten/woocommerce/auth/form-grant-access.php
stickerkitten/woocommerce/auth/form-login.php
stickerkitten/woocommerce/auth/header.php
stickerkitten/woocommerce/cart/cart-empty.php
stickerkitten/woocommerce/cart/cart-item-data.php
stickerkitten/woocommerce/cart/cart-shipping.php
stickerkitten/woocommerce/cart/cart-totals.php
stickerkitten/woocommerce/cart/cart.php
stickerkitten/woocommerce/cart/cross-sells.php
stickerkitten/woocommerce/cart/mini-cart.php
stickerkitten/woocommerce/cart/proceed-to-checkout-button.php
stickerkitten/woocommerce/cart/shipping-calculator.php
stickerkitten/woocommerce/checkout/cart-errors.php
stickerkitten/woocommerce/checkout/form-billing.php
stickerkitten/woocommerce/checkout/form-checkout.php
stickerkitten/woocommerce/checkout/form-coupon.php
stickerkitten/woocommerce/checkout/form-login.php
stickerkitten/woocommerce/checkout/form-pay.php
stickerkitten/woocommerce/checkout/form-shipping.php
stickerkitten/woocommerce/checkout/payment-method.php
stickerkitten/woocommerce/checkout/payment.php
stickerkitten/woocommerce/checkout/review-order.php
stickerkitten/woocommerce/checkout/terms.php
stickerkitten/woocommerce/checkout/thankyou.php
stickerkitten/woocommerce/content-product.php
stickerkitten/woocommerce/content-product_cat.php
stickerkitten/woocommerce/content-single-product.php
stickerkitten/woocommerce/content-widget-product.php
stickerkitten/woocommerce/emails/admin-cancelled-order.php
stickerkitten/woocommerce/emails/admin-failed-order.php
stickerkitten/woocommerce/emails/admin-new-order.php
stickerkitten/woocommerce/emails/customer-completed-order.php
stickerkitten/woocommerce/emails/customer-invoice.php
stickerkitten/woocommerce/emails/customer-new-account.php
stickerkitten/woocommerce/emails/customer-note.php
stickerkitten/woocommerce/emails/customer-on-hold-order.php
stickerkitten/woocommerce/emails/customer-processing-order.php
stickerkitten/woocommerce/emails/customer-refunded-order.php
stickerkitten/woocommerce/emails/customer-reset-password.php
stickerkitten/woocommerce/emails/email-addresses.php
stickerkitten/woocommerce/emails/email-customer-details.php
stickerkitten/woocommerce/emails/email-footer.php
stickerkitten/woocommerce/emails/email-header.php
stickerkitten/woocommerce/emails/email-order-details.php
stickerkitten/woocommerce/emails/email-order-items.php
stickerkitten/woocommerce/emails/email-styles.php
stickerkitten/woocommerce/emails/plain/admin-cancelled-order.php
stickerkitten/woocommerce/emails/plain/admin-failed-order.php
stickerkitten/woocommerce/emails/plain/admin-new-order.php
stickerkitten/woocommerce/emails/plain/customer-completed-order.php
stickerkitten/woocommerce/emails/plain/customer-invoice.php
stickerkitten/woocommerce/emails/plain/customer-new-account.php
stickerkitten/woocommerce/emails/plain/customer-note.php
stickerkitten/woocommerce/emails/plain/customer-on-hold-order.php
stickerkitten/woocommerce/emails/plain/customer-processing-order.php
stickerkitten/woocommerce/emails/plain/customer-refunded-order.php
stickerkitten/woocommerce/emails/plain/customer-reset-password.php
stickerkitten/woocommerce/emails/plain/email-addresses.php
stickerkitten/woocommerce/emails/plain/email-customer-details.php
stickerkitten/woocommerce/emails/plain/email-order-details.php
stickerkitten/woocommerce/emails/plain/email-order-items.php
stickerkitten/woocommerce/global/breadcrumb.php
stickerkitten/woocommerce/global/form-login.php
stickerkitten/woocommerce/global/quantity-input.php
stickerkitten/woocommerce/global/sidebar.php
stickerkitten/woocommerce/global/wrapper-end.php
stickerkitten/woocommerce/global/wrapper-start.php
stickerkitten/woocommerce/loop/add-to-cart.php
stickerkitten/woocommerce/loop/loop-end.php
stickerkitten/woocommerce/loop/loop-start.php
stickerkitten/woocommerce/loop/no-products-found.php
stickerkitten/woocommerce/loop/orderby.php
stickerkitten/woocommerce/loop/pagination.php
stickerkitten/woocommerce/loop/price.php
stickerkitten/woocommerce/loop/rating.php
stickerkitten/woocommerce/loop/result-count.php
stickerkitten/woocommerce/loop/sale-flash.php
stickerkitten/woocommerce/myaccount/dashboard.php
stickerkitten/woocommerce/myaccount/downloads.php
stickerkitten/woocommerce/myaccount/form-add-payment-method.php
stickerkitten/woocommerce/myaccount/form-edit-account.php
stickerkitten/woocommerce/myaccount/form-edit-address.php
stickerkitten/woocommerce/myaccount/form-login.php
stickerkitten/woocommerce/myaccount/form-lost-password.php
stickerkitten/woocommerce/myaccount/form-reset-password.php
stickerkitten/woocommerce/myaccount/lost-password-confirmation.php
stickerkitten/woocommerce/myaccount/my-account.php
stickerkitten/woocommerce/myaccount/my-address.php
stickerkitten/woocommerce/myaccount/my-downloads.php
stickerkitten/woocommerce/myaccount/my-orders.php
stickerkitten/woocommerce/myaccount/navigation.php
stickerkitten/woocommerce/myaccount/orders.php
stickerkitten/woocommerce/myaccount/payment-methods.php
stickerkitten/woocommerce/myaccount/view-order.php
stickerkitten/woocommerce/notices/error.php
stickerkitten/woocommerce/notices/notice.php
stickerkitten/woocommerce/notices/success.php
stickerkitten/woocommerce/order/form-tracking.php
stickerkitten/woocommerce/order/order-again.php
stickerkitten/woocommerce/order/order-details-customer.php
stickerkitten/woocommerce/order/order-details-item.php
stickerkitten/woocommerce/order/order-details.php
stickerkitten/woocommerce/order/tracking.php
stickerkitten/woocommerce/product-searchform.php
stickerkitten/woocommerce/single-product/add-to-cart/external.php
stickerkitten/woocommerce/single-product/add-to-cart/grouped.php
stickerkitten/woocommerce/single-product/add-to-cart/simple.php
stickerkitten/woocommerce/single-product/add-to-cart/variable.php
stickerkitten/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
stickerkitten/woocommerce/single-product/add-to-cart/variation.php
stickerkitten/woocommerce/single-product/meta.php
stickerkitten/woocommerce/single-product/photoswipe.php
stickerkitten/woocommerce/single-product/price.php
stickerkitten/woocommerce/single-product/product-attributes.php
stickerkitten/woocommerce/single-product/product-image.php
stickerkitten/woocommerce/single-product/product-thumbnails.php
stickerkitten/woocommerce/single-product/rating.php
stickerkitten/woocommerce/single-product/related.php
stickerkitten/woocommerce/single-product/review-meta.php
stickerkitten/woocommerce/single-product/review-rating.php
stickerkitten/woocommerce/single-product/review.php
stickerkitten/woocommerce/single-product/sale-flash.php
stickerkitten/woocommerce/single-product/share.php
stickerkitten/woocommerce/single-product/short-description.php
stickerkitten/woocommerce/single-product/stock.php
stickerkitten/woocommerce/single-product/tabs/additional-information.php
stickerkitten/woocommerce/single-product/tabs/description.php
stickerkitten/woocommerce/single-product/tabs/tabs.php
stickerkitten/woocommerce/single-product/title.php
stickerkitten/woocommerce/single-product/up-sells.php
stickerkitten/woocommerce/single-product-reviews.php
stickerkitten/woocommerce/single-product.php
stickerkitten/woocommerce/taxonomy-product_cat.php
stickerkitten/woocommerce/taxonomy-product_tag.php
</details>

**Comment by mensmaximus** [comment]
I have created nearly 50 test orders today and all have sent emails as usual. Have you deactivated all plugins except woocommerce and tried it again?

**Comment by tehmooo** [comment]
Yes, that was one of the first things i tried - It didn't work. And I realised it wasn't a common issue, otherwise I'd have solved it with googling the problem - What I don't understand is why i can manually send emails, but the automated side of it doesn't work - I would have expected all or nothing, not half working

**Comment by tehmooo** [comment]
https://github.com/woocommerce/woocommerce/issues/14151 This solved my problem!

**Comment by mathakiyajuber** [comment]
i can not get email after completed process but i sent from smtp plugin then i get so how to fix this erro 
please help me!!!!!
