### ISSUE TITLE
How do I use WC CLI

### ISSUE THREAD

**Issue by williamli** [woocommerce/woocommerce#14174]
### EXPLANATION OF THE ISSUE

When I call

`wp wc`

I get an error saying

`'wc' is not a registered wp command`

Do I need to install something to have WC CLI available in WP CLI?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Overview You need to run it from the directory where WordPress is installed.

**Comment by williamli** [comment]
found out what's causing it.
I was running wordpress inside a docker container with the wp-content directory mounted from a separate location.

sorry about that.

**Comment by BrianHenryIE** [comment]
WooCommerce needs to be active!

`wp plugin activate woocommerce --path=${pwd}`
