### ISSUE TITLE
'New Customer Order' email broken URL

### ISSUE THREAD

**Issue by BuggeringHell** [woocommerce/woocommerce#14171]
Since 3.0, it seems the URL that takes me directly to the order overview page for new order emails is broken.

In Gmail, it tries to send me to a local URL e.g. https://mail.google.com/wp-admin/post.php?post=XXX&action=edit instead of my store's URL

**Comment by mikejolley** [comment]
Uses https://codex.wordpress.org/Function_Reference/admin_url

Suspect yours is being filtered by a plugin; testing locally gives the correct full URL. Not a relative URL.
