### ISSUE TITLE
Copy to new draft for products no longer resets SKU Field

### ISSUE THREAD

**Issue by jhapeman** [woocommerce/woocommerce#14172]
### EXPLANATION OF THE ISSUE

When using the "Copy to new Draft" link to created a new product by copying an existing one, the SKU field is no longer reset as  before.  In addition, it no longer shows "(Copy)" in the title field.  Saving can create a complete duplicate product.

### STEPS TO REPRODUCE THE ISSUE

Select any product.  Click on "Copy to new Draft" link in the "Publish" section.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.earthstreasury.com
Site URL: http://www.earthstreasury.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: lhn_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (21) ###

Query Monitor: by John Blackbourn – 2.13.4
Cart recovery for WordPress Pro: by Lee Willis – 1.7.3
Cart recovery for WordPress: by Lee Willis – 2.1.4
Contact Form 7: by Takayuki Miyoshi – 4.7
Google Analytics +: by WPMU DEV – 3.1.5.5
MailChimp for WordPress: by ibericode – 4.1.0
PixelYourSite: by PixelYourSite – 5.0.1
Storefront Powerpack: by WooThemes – 1.3.1
WooCommerce Authorize.Net CIM Gateway: by SkyVerge – 2.6.0
WooCommerce AdWords Conversion Tracking: by Wolf+Bär GmbH – 1.3.5
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Product Archive Customiser: by jameskoster – 1.0.5
WooCommerce Product Search: by itthinx – 1.8.1
WooCommerce ShippingEasy Integration: by WooThemes – 3.4.1
WooCommerce WishLists: by Lucas Stark – 2.0.1
WooCommerce: by Automattic – 3.0.1
WooDojo: by WooThemes – 1.5.4
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
WP Staging: by WP-Staging
René Hermenau – 1.1.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Canvas
Version: 5.11.4
Author URL: http://www.woothemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Authorize.Net CIM ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
`
</details>

**Comment by mensmaximus** [comment]
The slug and sku get updated by appending 'dash-number' and the status is set to draft. Only the title stays the same (word copy missing).

**Comment by rellect** [comment]
#14142, #14141

**Comment by mikejolley** [comment]
^ see those PRs

SKU should not be reset. SKU get a suffix.
