### ISSUE TITLE
Call to undefined method WC_Product_Variable::has_persons()

### ISSUE THREAD

**Issue by miong13** [woocommerce/woocommerce#14173]
### EXPLANATION OF THE ISSUE

WooCommerce Version 3. Could not retrieve Smart Coupons, and Has Person option is not displaying as well.

### STEPS TO REPRODUCE THE ISSUE

adding New Product.

### SYSTEM STATUS
`
### WordPress Environment ###

Home URL: http://letsindulge.desketing.com.au
Site URL: http://letsindulge.desketing.com.au
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 2 GB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: ❌ 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wppf_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (11) ###

Duplicate Page: by mndpsingh287 – 2.2
SOGO Add Script Header Footer: by orenhav (SOGO) – 2.3
Simple CSS: by Tom Usborne – 0.4
WooCom SecurePay Payment Gateway: by Hem Thapa – 1.1
WooCommerce Bookings: by Automattic – 1.10.0
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.0
WooCommerce Smart Coupons: by StoreApps – 3.2.1
WooCommerce: by Automattic – 3.0.1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WP Fastest Cache: by Emre Vona – 0.8.6.8
WP Migrate DB: by Delicious Brains – 0.9.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
virtual (virtual)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #434 - /cart/
Checkout: #436 - /checkout/
My account: #438 - /my-account/

### Theme ###

Name: Enfold Child
Version: 1.0
Author URL: http://www.kriesi.at
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.0.5
Parent Theme Author URL: http://www.kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mensmaximus** [comment]
There are other reports about issues in WC3 in conjunction with Smart Coupons (e.g. together with Yoast SEO [see here](https://github.com/Yoast/wordpress-seo/issues/6942)). You might contact the support of Smart Coupons first.

**Comment by mikejolley** [comment]
Please put it a real support ticket - https://woocommerce.com/my-account/tickets - the bookings team would need the full error message in order to find where the call is being made and to add a check to ensure it's a booking object and not a product.

cc @roykho @bor0

**Comment by dare-devil-arrives** [comment]
@miong13 : Updating Smart Coupons to v3.3.0 solves the issue of retrieving coupons.
