### ISSUE TITLE
Checking shot attribute names against the cart item variation title 

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce#14187]
### EXPLANATION OF THE ISSUE

There is still a problem on 3.0.1 with checking attribute values against product variation name being too strictly. What about one-char attribute value, i.e. clothes sizes like "s" or "m"? It's super possible for stristr to find one-char string in whole title, not only in "attributes part" of product variation title but in "product parent title part" as well. Even if there is no attribute name or value in whole variation title (pre 3.0 manner).

/includes/class-wc-cart.php:561

```
// Check the nicename against the title.
if ( '' === $value || stristr( $cart_item['data']->get_name(), $value ) ) {
      continue;
}
```

Issue mentioned here: [https://github.com/woocommerce/woocommerce/issues/13987](url)

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14209
