### ISSUE TITLE
view-order.php template has not updated the version number

### ISSUE THREAD

**Issue by Umangvaghela** [woocommerce/woocommerce#14183]
### EXPLANATION OF THE ISSUE
view-order.php template has not updated the version number.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by faisal-alvi** [comment]
Please let us know which version number is displaying and which should be displayed instead?

**Comment by Umangvaghela** [comment]
Now in current version view-order.php page display @version 2.6.0 instead @version 3.0.1
