### ISSUE TITLE
Email formatting: attributes are not on a new line - printed in one line

### ISSUE THREAD

**Issue by el-presidente** [woocommerce/woocommerce#14194]
Maybe this is one of them it's not a bug, it's a new feature :) But on the new WC3 emails that are sent the attributes are printed on one line, in the old days we had a beautiful line break. Two emails for comparing before and after:

![before](https://cloud.githubusercontent.com/assets/937382/24863186/115e6dbc-1e00-11e7-84b6-b2ea0097a3e9.png)

![after](https://cloud.githubusercontent.com/assets/937382/24863191/137baf7e-1e00-11e7-9e92-db3dcdbcd3fa.png)

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14159

Variation names contain attributes in 3.0. We'll look at length ^
