### ISSUE TITLE
If checkout registration is disabled and not logged in, the user cannot checkout

### ISSUE THREAD

**Issue by max32002** [woocommerce/woocommerce#14195]
### SYSTEM STATUS

not logined user checkout.

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

show return in templates/checkout/form-checkout.php 

should use:
`if ( $checkout->is_registration_enabled() && $checkout->is_registration_required() && ! is_user_logged_in() ) {`

instead of:
`if ( ! $checkout->is_registration_enabled() && $checkout->is_registration_required() && ! is_user_logged_in() ) {
`

**Comment by claudiulodro** [comment]
It looks correct, as far as I can tell.

If checkout registration is disabled and the user isn't logged in, they are presented with a login dialogue. If they don't already have an account, they have to make a new account on the "My Account" page. That's the correct behavior for those settings.

```
if ( $checkout->is_registration_enabled() && $checkout->is_registration_required() && ! is_user_logged_in() ) {
```
Try submitting an order after making this change. You'll get an `Account password is a required field.` error.
