### ISSUE TITLE
WOD in /my-account/orders/

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#14196]
### EXPLANATION OF THE ISSUE

With latest WC, I got WOD when requesting /my-account/orders/ as a logged-in user.

### STEPS TO REPRODUCE THE ISSUE

1. Use latest WC. No other extensions.
2. Update `_product_id` record in `wp_woocommerce_order_itemmeta` table to arbitrary number that's not product ID. Make sure to update recent order or the order that would appear in /my-account/orders/ page.
3. Open /my-account/orders/

It might be related to my env (using VVV) as @bor0 wasn't able to replicate the issue here. Nothing logged in the log when WOD happens, which might be related to nginx or php-fpm 7.0 setting. When I edit `_product_id` to zero the page loads fine. Template file for the page doesn't seem to cause this issue as I put break point at the beginning of template file and WOD still happens.

**Comment by mikejolley** [comment]
I use VVV and also don't get the WSOD.

**Comment by mikejolley** [comment]
No luck. Set it to all kinds of things. If invalid, `set_product_id` throws an exception, but as it's set via `set_props` it's caught.

Let's chat over slack and narrow it down. I'm not sure there is a core bug and I cannot replicate.
