### ISSUE TITLE
get_description() & get_short_description() on variable products

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#14193]
In 2.6, I could do `$product->get_post_data()->post_excerpt` to get the short description of a product. This is replaced in 3.0 by `$product->get_short_description()`. This works fine on simple products, but variable products return an empty string (whereas this used to return the main short description in 2.6).

**Comment by mikejolley** [comment]
Works. I think you may be calling get_short_description on a variation (the child) rather than the parent variable product.

**Comment by Spreeuw** [comment]
@mikejolley correct, I am calling the short_description on the variation product. However, I think the function should have an automatic fallback to the parent when accessed on a variation.

To be more precise, I am loading the product via `$order->get_product_from_item( $item )`.
In this case, this returns a `WC_Product_Variation` object. In 2.6, `$product->get_post_data()` on this object would return the parent post (the `WC_Product_Variation` would actually be labeled with the parent product id, in addition to `variation_id`.
In 3.0 this is all much more coherent where the object is actually the variation, but that leaves the `get_description` method useless (as well as the `get_short_description` method). Rather than returning the variation description for `get_description` (which I would not prefer but would be better than nothing), there's a separate `get_variation_description` method.

Summarizing, since there's a separate method for the variation description anyway, I would suggest to return the main short and long descriptions with `get_description` and `get_short_description` respectively, this is in line with how this worked in 2.6 and older.

**Comment by mikejolley** [comment]
That does not make sense for these data objects. Inheritance is a slippery slope and I believe the data should be separated.

**Comment by Anikora** [comment]
Looking for the same thing. For my theme (Royal by 8theme) I had to add the following code to cart & checkout get the short descriptions without errors for simple and variable products:
`									<?php if( $_product->is_type( 'simple' ) ){
										echo $_product->get_short_description();
									} 
									else {
										$product_id = $_product->get_parent_id(); $product = wc_get_product($product_id); echo $product->get_short_description();
									}
									?>	`

But that looks really weird to me and I am wondering if there isnt a better solution for this....?!
