### ISSUE TITLE
don't know where to ask this. (official woocommerce paying plugins) suggestions on pricing

### ISSUE THREAD

**Issue by raykai** [woocommerce/woocommerce#14205]
Hi,
do you have a bundle price to get all of the Woocommerce official paying plugins ? or have a subscription in place for the ppl that need allot of your extensions? i think you would sell allot more if you did.

Just look at what yithemes did. They added a Join the club subscription. ppl save and its a pay per month which is a lot better for ppl then paying the full price for each plugin they get each year.
see it here https://yithemes.com/themes/membership/annual-yithemes-club-subscription/
there plugin sells went up 6X this way.

i would love to get a subscription as i can not afford to pay ... what 800$ for the plugins that i would need that's is just for the minimum of the plugins that i was looking to get it can go in the 1000$.   i cant afford paying a big bill like that on a one go every year.

A monthly plan would be allot beater for starters too.

I think a monthly plan would benefit your team allot more as it gets accessible for every one to use your official paying plugins.

**Comment by mikejolley** [comment]
There are specialised bundles but no there is not right now. https://woocommerce.com/product-category/woocommerce-extensions/bundles/

I'll pass on your feedback.
