### ISSUE TITLE
Variation and attribute name generation fixes

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#14209]
- [ ] Attribute already in name check is too strict (https://github.com/woocommerce/woocommerce/issues/14187)
- [ ] Add filter to disable attributes in variation names completely (#14159)
- [ ] Disable if variation has > 3 attributes.
- [ ] Disable if ATTRIBUTE NAME > 2 words
- [ ] Never prefix term with attribute name in new logic

**Comment by ryankereliuk** [comment]
Another test case would be if there are two similar attributes such as Inside-color and Outside-color in which case stripping the attribute name leads to ambiguity.  That said, this new feature doesn't seem to make sense when attributes get complicated (which the task list above sort of acknowledges) so perhaps this case is best addressed by disabling the feature altogether.

**Comment by mensmaximus** [comment]
Imho it should be the sole decision of the shop owner how variations should be displayed in the cart. There are even regulatory rules for some products like food or cigarettes. Why not keep the WC 2.6 style and offer a checkbox in the backend to switch to the new style? Together with a filter this gives enough room for modifications. Automaticaly enabling or disabling based on attribute count or word count imho will only cause questions from shop owners. The T-Shirt has two attributes but the jeans has four. So they will be displayed different in the same shopping cart by default.

**Comment by mikejolley** [comment]
Adding options should not be in a fix release. We should just fix the broken cases reported and add the filter.

**Comment by ryankereliuk** [comment]
Thanks @mikejolley.  I tested it myself in 3.0.2 and it works just fine.  Maybe worth noting in the documentation that the fix requires adding the filter and opening every product and re-saving.

**Comment by rockeypjb** [comment]
@ryankereliuk, I just downloaded 3.0.2, but I am not noticing any changes in the names. Which filter did you add? When you are referring to re-saving every product do you just mean the products that were created between v3.0 and 3.0.2? Thanks.

**Comment by mensmaximus** [comment]
@rockeypjb the actual version ist 3.0.3

**Comment by ryankereliuk** [comment]
@rockeypjb I added a filter function in my theme's functions.php, not doing much now but maybe later.

<pre>
function rkk_woocommerce_product_variation_title_include_attributes($should_include_attributes, $product) {
        return false;
}
add_filter('woocommerce_product_variation_title_include_attributes', 'rkk_woocommerce_product_variation_title_include_attributes');
</pre>

Then I had to go into every variation of every product and re-save.  I used an SQL query on my database to make sure I got them all.

**Comment by rockeypjb** [comment]
@mensmaximus, that is correct, my mistake

@ryankereliuk, I added your function and manually updated a few products. No luck.
