### ISSUE TITLE
Missing a way to refund but not in cash but as coupon for next off next purchase

### ISSUE THREAD

**Issue by raykai** [woocommerce/woocommerce#14203]
As of now there is only a way to refund  a client with cash using the payment gateway to refund.
it would be nice having an extra way to just refund using a coupon (Vouchers) code and not in cash.

Some woocommerce alternatives like PrestaShop has this option in there core.

**Comment by mikejolley** [comment]
This is not a refund. There is nothing to stop you just creating a coupon and noting in order notes?

Please use http://ideas.woocommerce.com/forums/133476-woocommerce for ideas like this.
