### ISSUE TITLE
Refund amount input js regex

### ISSUE THREAD

**Issue by rellect** [woocommerce/woocommerce#14202]
I'm looking at the refund amount input validation, I located it in `woocommerce_admin.js`
It looks like this
```
if ( $( this ).is( '.wc_input_price' ) || $( this ).is( '#refund_amount' ) ) {
	regex = new RegExp( '[^\-0-9\%\\' + woocommerce_admin.mon_decimal_point + ']+', 'gi' );
	error = 'i18n_mon_decimal_error';
}
```
Something looks wrong here.. For instance, it allows to write `%` and `\`, and also negative numbers..
Is there a use for that?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14232 which is due for 3.1
