### ISSUE TITLE
3.0: Checkout properties broken changing return value of new functions

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#14211]
### EXPLANATION OF THE ISSUE

In WC 2.6, properties on `WC_Checkout` were set once when `WC()->checkout` was constructed. This meant that property could be overridden once and that value would be used for all future logic.

In WC 3.0, the methods used to replace these properties always use a `get_option()` call instead of a property set once, e.g. `WC_Checkout::is_registration_required()` checks `'yes' !== get_option( 'woocommerce_enable_guest_checkout' )` instead of a property set to that value like `WC_Checkout->enable_guest_checkout`.

This means the `WC_Checkout::__get()` method used in 3.0 designed to maintain backward compatibility with these old properties, does not maintain the old behaviour. The new methods for accessing the equivalent of those old properties' values, which are used in core, also have different behaviour, which means checkout behaviour prior to 3.0 breaks.

The new filters in the new functions must be used to avoid this issue with 3.0+. However, no deprecated notices are logged when getting/setting the `WC_Checkout` properties so it's an easy issue to miss.

### STEPS TO REPRODUCE THE ISSUE

To reproduce one example of the issue

1. enable the _Guest Checkout_ option: https://cl.ly/2I181Z1Y1J1O
2. use the following snippet:

```
function eg_force_checkout_registration( $checkout ) {

	$checkout->enable_signup = true;
	$checkout->enable_guest_checkout = false;

	if ( ! is_user_logged_in() ) {
		$checkout->must_create_account = true;
	}

	return $checkout;
}
add_action( 'woocommerce_before_checkout_form', 'eg_force_checkout_registration', 0 );
```

With that snippet on WC `2.6.14`, checkout account fields display like this: https://cl.ly/2j0X2H041q0S

With that snippet on WC `3.0.0`, checkout account fields display like this: https://cl.ly/2i2F2I2a1B2f (the _Create an account_ checkbox is displayed now because `$checkout->is_registration_required()` returns a comparison to the `get_option()` value, not the `$checkout->enable_guest_checkout` property).

Backward compatibility could be maintained by using `private` or `protected `properties`. If that's not done, the issue should be written up in [the Wiki](https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes) and deprecated notices added for those properties to indicate their behaviour has changed.

**Comment by mikejolley** [comment]
I think the logic in __get may just have a few props backwards.
