### ISSUE TITLE
Filter hook post_date_column_time removed without notice

### ISSUE THREAD

**Issue by mensmaximus** [woocommerce/woocommerce#14215]
### EXPLANATION OF THE ISSUE

WooCommerce 3 has removed the filter ´post_date_column_time´ in method ´render_shop_order_columns´ of class ´WC_Admin_Post_Types´. This information is missing in the deprecated filters section of the [developer migration notes](https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes)

**Comment by mikejolley** [comment]
`post_date_column_time` is not a deprecated filter, it's a WordPress filter used on post type screens. Since Orders now use their own dates, not not post_date, this filter is not relevant (but may still be relevant to other post types).
