### ISSUE TITLE
Zoom Slider not support RTL Language and add new feature

### ISSUE THREAD

**Issue by mostafaabd** [woocommerce/woocommerce#14213]
Hello,
in new version woocommerce plugin 3.0+
1- flex slider not add support RTL Language.
2-  woocommerce single-product.js need to wrap flex slider "flex-viewport " like this http://flexslider.woothemes.com/ in this example user can add border and background around image so i can add border and background in my  theme.

3- When end user select item from drop down menu first image in thumbnail resized
see this 
http://demo.eyethemes.com/majesty/product/woo-select/
when you select item from size and color dropdown menu the first image in thumbnails is resize and i test it in storefront theme and twentyfifteen theme , the same issue.
see
https://drive.google.com/file/d/0Bxoe2K0kaNnyMjZGTEw4OHY0RFk/view?usp=sharing
https://drive.google.com/file/d/0Bxoe2K0kaNnyQzNac25uZ1BEZlE/view?usp=sharing

thanks great job

**Comment by mikejolley** [comment]
RTL is supported, and .flex-viewport does not need a wrapper because you can style .flex-viewport directly.

Checking 3.

**Comment by mostafaabd** [comment]
Hello,
Thanks for answer
please for this point
i can't style flex-viewport it's style but not work good if i can style it why flex slider main project http://flexslider.woothemes.com/ wrap it , try it your self if you add background and border for 'flex-viewport' right border not displayed https://drive.google.com/file/d/0Bxoe2K0kaNnyVWVOTVlobUxDU28/view?usp=sharing

and flex slider not support rtl language please ask him to add this feature i can use css to fix it but image not display good like LTR.

thanks , Have nice day.
