### ISSUE TITLE
Using Custom Post Types no longer possible after "ba8f308"

### ISSUE THREAD

**Issue by pe6o** [woocommerce/woocommerce#14212]
Hi there, I'm a theme developer and I stumbled on an issue after that latest update. As the https://github.com/woocommerce/woocommerce/commit/ba8f308100a7ab59fe411efe366eb91142a8979d commit adds an additional `product` check here:

```php
if ( ! $product->get_id() || ! ( $post_object = get_post( $product->get_id() ) ) || 'product' !== $post_object->post_type ) {
      throw new Exception( __( 'Invalid product.', 'woocommerce' ) );
}
```

it is no longer possible to add custom post types in a cart.We are having themes that use post types separate from the main `product` one and they are no longer functional.  Is there a hook, filter or any other way that can get around this issue?

**Comment by mikejolley** [comment]
The data stores work exclusively with product data - that is product custom post type, and product meta data which your custom product type will be lacking.

You can either extend the data stores for your own usage, or extend the constructor and avoid calls to the core data stores. This is not something which will work out of the box.

See: 

https://github.com/woocommerce/woocommerce/wiki/Data-Stores
https://github.com/woocommerce/woocommerce/wiki/Product-Data-Schema

And the call in the product class you can replace via your child class:

https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L126

**Comment by pe6o** [comment]
Thank you for the answer. I created a custom data store, but how can I replace the product class, and where I load the custom data via the `WC_Data_Store::load`?

**Comment by mikejolley** [comment]
> how can I replace the product class

Not sure what you mean - you must have a product class to represent your 'custom post type' no? How else would it know how to handle things (even in 2.6)?

**Comment by pe6o** [comment]
The custom post type, that I have, has only the basic "Add to Cart" functionality. It uses the WooCommerce `_price`, `_visibility` and `_sold_individually` meta fields and nothing else.

What I meant above was how can I replace the product class call to my custom data store where I have removed the product check:

```php
if ( ! $product->get_id() || ! ( $post_object = get_post( $product->get_id() ) ) ) {
	throw new Exception( __( 'Invalid product.', 'woocommerce' ) );
}
```

**Comment by mikejolley** [comment]
You can call your custom data store instead, and not include this check at all.

**Comment by pe6o** [comment]
So far so good, I created a custom data store. Created `abstract-wc-my-post-type.php` where I replaced the line that loads the product data store with one reloading mine.

However, when I place an order, the item doesn't contain any product data because in the following stack
`WC_Checkout->create_order_line_items` 
`WC_Data->set_props`
`WC_Order_Item_Product->set_product_id`
the `set_product_id()` method checks if the post type of the item is `product`. Is it possible to overwrite/extend it?

**Comment by pe6o** [comment]
It seems the problem is not in `set_product_id()`. Then which function gives the product meta of the ordered item so that I don't receive the error on the Checkout.

> Trying to get property of non-object in themename\woocommerce\order\order-details.php on line `$purchase_note = get_post_meta( $product->id, '_purchase_note', true );`

**Comment by pe6o** [comment]
Soon I will start testing it.

For now, I see that `wc_update_total_sales_counts()` has a hard coded `product` data store.

Isn't it more logical for it to use the `update_product_sales` of the user data store.

**Comment by mikejolley** [comment]
Yes this could use get_data_store method instead.

**Comment by nirmalgoswami** [comment]
Any solution ?

One person is using woocommerce plugin owner suggestion 

[Stackoverflow](https://stackoverflow.com/questions/43273286/wp-custom-post-type-cant-already-add-to-cart-in-woocommerce-3-0-above)

But i am getting `INVALID DATA STORE` error IN `WP-CONTENT\PLUGINS\WOOCOMMERCE\INCLUDES\CLASS-WC-DATA-STORE.PHP ON LINE 92`

**Comment by nirmalgoswami** [comment]
Any way, i got solution

```
/**
 * Check if WooCommerce is active
 **/
if ( in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
    // Put your plugin code here

    add_action('woocommerce_loaded' , function (){
         //Put your code here that needs any woocommerce class 
         //You can also Instantiate your main plugin file here 
    });

}
```

Complete Solution : 

```
if ( in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {
	// Put your plugin code here

	add_action('woocommerce_loaded' , function (){
		//Put your code here that needs any woocommerce class
		//You can also Instantiate your main plugin file here
		class WCCPT_Product_Data_Store_CPT extends WC_Product_Data_Store_CPT
		{

			/**
			 * Method to read a product from the database.
			 * @param WC_Product
			 */

			public function read(&$product)
			{

				$product->set_defaults();

				if (!$product->get_id() || !($post_object = get_post($product->get_id())) || !in_array($post_object->post_type, array('birds', 'product'))) { // change birds with your post type
					throw new Exception(__('Invalid product.', 'woocommerce'));
				}

				$id = $product->get_id();

				$product->set_props(array(
					'name' => $post_object->post_title,
					'slug' => $post_object->post_name,
					'date_created' => 0 < $post_object->post_date_gmt ? wc_string_to_timestamp($post_object->post_date_gmt) : null,
					'date_modified' => 0 < $post_object->post_modified_gmt ? wc_string_to_timestamp($post_object->post_modified_gmt) : null,
					'status' => $post_object->post_status,
					'description' => $post_object->post_content,
					'short_description' => $post_object->post_excerpt,
					'parent_id' => $post_object->post_parent,
					'menu_order' => $post_object->menu_order,
					'reviews_allowed' => 'open' === $post_object->comment_status,
				));

				$this->read_attributes($product);
				$this->read_downloads($product);
				$this->read_visibility($product);
				$this->read_product_data($product);
				$this->read_extra_data($product);
				$product->set_object_read(true);
			}

			/**
			 * Get the product type based on product ID.
			 *
			 * @since 3.0.0
			 * @param int $product_id
			 * @return bool|string
			 */
			public function get_product_type($product_id)
			{

				$post_type = get_post_type($product_id);
				if ('product_variation' === $post_type) {
					return 'variation';
				} elseif (in_array($post_type, array('birds', 'product'))) { // change birds with your post type
					$terms = get_the_terms($product_id, 'product_type');
					return !empty($terms) ? sanitize_title(current($terms)->name) : 'simple';
				} else {
					return false;
				}
			}
		}
	});

}


add_filter( 'woocommerce_data_stores', 'woocommerce_data_stores' );

function woocommerce_data_stores ( $stores ) {
	$stores['product'] = 'WCCPT_Product_Data_Store_CPT';
	return $stores;
}
add_filter('woocommerce_product_get_price', 'woocommerce_product_get_price', 10, 2 );
function woocommerce_product_get_price( $price, $product ) {
	if ($post->post->post_type === 'birds') // change birds with your post type
		$price = get_post_meta($post->id, "price", true);
	return $price;
}
```

**Comment by mysticalghoul** [comment]
Great, will this work for upcoming woocommerce versions?

**Comment by nirmalgoswami** [comment]
yeah

**Comment by WeDesIn** [comment]
It does not work anymore, it returns a Fatal error: Uncaught exception 'Exception' with message 'Invalid data store.' error... :-(

**Comment by yichenlovetj** [comment]
Hey guys any one have found a solution for this? I am getting the same error with 3.5.2

**Comment by wpcoderca** [comment]
This doesn't seem to work anymore. Has anyone found a solution to this?

**Comment by Farhadsaadatpei** [comment]
@nirmalgoswami The solution doesn't work anymore. It throws the following error: 

`Fatal error: Uncaught Exception: Invalid data store. in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php:101 Stack trace: #0 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('product') #1 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-product-factory.php(81): WC_Data_Store::load('product') #2 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-product-factory.php(32): WC_Product_Factory::get_product_type(901) #3 /var/www/html/wp-content/plugins/woocommerce/includes/wc-product-functions.php(69): WC_Product_Factory->get_product(901, Array) #4 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(763): wc_get_product(901) #5 /var/www/html/wp-includes/class-wp-hook.php(287): WC_Form_Handler::add_to_cart_action('') #6 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #7 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #8 /var/www/ in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 101`
