### ISSUE TITLE
Photoswipe missing captions

### ISSUE THREAD

**Issue by GlazerGallery** [woocommerce/woocommerce#14218]
### EXPLANATION OF THE ISSUE

I updated to WooCommerce 3.0.1. In the earlier version of WooCommerce I was way happier with the product gallery than what is there now, because we absolutely **need** and depend upon the captions showing up with the images from the gallery to explain what they are showing. If this functionality is gone it cripples our site. I'm pretty upset about it, because we've already invested a few thousand dollars into switching our site over to WooCommerce and we are midway through the process. The thought that you have for some reason decided it is an "improvement" to remove the display of titles and captions is distressing in the extreme!  Also, we think it is confusing to have the entire product page now be replaced by that solid black. Why did you take away the transparency? That is not an "improvement" either. Note that it does NOT matter if I use Vantage or Storefront -- same thing happens. So don't assume that if I used Storefront all would be resolved. _It is definitely not._

### STEPS TO REPRODUCE THE ISSUE

View product. Click magnifier icon. Image opens on screen with solid black background. No title and no caption show.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.georgeglazer.com/wpmain
Site URL: http://www.georgeglazer.com/wpmain
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.3.29-pl0-gentoo - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 7.39.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (10) ###

Jetpack by WordPress.com: by Automattic – 4.8.2
Meta Slider: by Matcha Labs – 3.5
Page Builder by SiteOrigin: by SiteOrigin – 2.4.25
SiteOrigin CSS: by SiteOrigin – 1.1.3
SiteOrigin Widgets Bundle: by SiteOrigin – 1.8.2
WooCommerce: by Automattic – 3.0.1
WooSidebars: by WooThemes – 1.4.3
WP All Import Pro: by Soflyy – 4.4.3
YITH Essential Kit for WooCommerce #1: by YIThemes – 1.4.4
YITH WooCommerce Catalog Mode: by YITHEMES – 1.5.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #5 - /shop/
Cart: ❌ Page not set
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Vantage
Version: 1.5.8
Author URL: https://siteorigin.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
That sounds like a bit of an over exaggeration, but @jameskoster Can we get caption support in Photoswipe easily?

**Comment by GlazerGallery** [comment]
What sounds like an exaggeration? I assure you that the money we've spent moving about 1,600 products from an HTML site to WooCommerce, including scraping the data from the old site and importing into WordPress and our dependence on captions (we sell antiques, sometimes in sets, or that have details that need explaining) is all too accurate.
