### ISSUE TITLE
Shop Home Page Strips Inline SVG

### ISSUE THREAD

**Issue by ojbravo** [woocommerce/woocommerce#14222]
### EXPLANATION OF THE ISSUE

Since upgrading from 2.6 to 3.0.1, the Shop Home Page strips the inline SVG code and leaves plain text.  This SVG code worked fine before updating to 3.0.  I tested with the twentyseventeen theme and it doesn't work there either.

### STEPS TO REPRODUCE THE ISSUE

Add inline SVG to the Shop Home page and it will be removed.  HTML code remains.

Example: 
This....
```
<div class="slogan">
			<svg id="banners" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 385 80"><text transform="matrix(.75 0 0 1 0 70)" class="bdb0 bdb1 bdb2">Garage Banners</text><text transform="translate(34 16)" class="bdb0 bdb4 bdb5 bdb6">MOTORIZED</text></svg><svg id="fans" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 510 80"><text transform="matrix(.7464 0 0 1 35 69.26)" class="bdb0 bdb1 bdb2">Biggest Sports Fans</text><text transform="matrix(0 -.7464 1 0 30 70.26)" class="bdb0 bdb1 bdb3">For The</text></svg>
</div>
```

Results in this....

```
<div class="slogan">
	Garage BannersMOTORIZEDBiggest Sports FansFor The
</div>
```

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://bigdawgbanners.dev
Site URL: http://bigdawgbanners.dev
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.0
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/0.9.8zd

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.42 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 35: Unsupported SSL protocol version
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. 200

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: oisudf_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (10) ###

Enable Media Replace: by Måns Jonasson – 3.0.6
Enhanced Category Pages: by Ciprian Amariei
Diana Amitroaei – 2.3.0

FooGallery - Video Extension: by FooPlugins
CalderaWP – 1.0.11

Foo Gallery: by FooPlugins – 1.2.18
Open Swatch - Woocommerce Color Swatch: by anhvnit@gmail.com – 2.0
Raw HTML: by Janis Elsts – 1.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
WooCommerce: by Automattic – 3.0.1
WP Editor: by Benjamin Rojas – 1.2.6.3
WP Migrate DB Pro: by Delicious Brains – 1.6.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /
Cart: #121 - /cart/
Checkout: #122 - /checkout/
My account: #123 - /my-account/

### Theme ###

Name: BigDawg - v2.0
Version: 2.0.0
Author URL: http://underscores.me/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: bigdawg-v2/woocommerce/archive-product.php
bigdawg-v2/woocommerce/auth/footer.php
bigdawg-v2/woocommerce/auth/form-grant-access.php
bigdawg-v2/woocommerce/auth/form-login.php
bigdawg-v2/woocommerce/auth/header.php
bigdawg-v2/woocommerce/cart/cart-empty.php
bigdawg-v2/woocommerce/cart/cart-item-data.php
bigdawg-v2/woocommerce/cart/cart-shipping.php
bigdawg-v2/woocommerce/cart/cart-totals.php
bigdawg-v2/woocommerce/cart/cart.php
bigdawg-v2/woocommerce/cart/cross-sells.php
bigdawg-v2/woocommerce/cart/mini-cart.php
bigdawg-v2/woocommerce/cart/proceed-to-checkout-button.php
bigdawg-v2/woocommerce/cart/shipping-calculator.php
bigdawg-v2/woocommerce/checkout/cart-errors.php
bigdawg-v2/woocommerce/checkout/form-billing.php
bigdawg-v2/woocommerce/checkout/form-checkout.php
bigdawg-v2/woocommerce/checkout/form-coupon.php
bigdawg-v2/woocommerce/checkout/form-login.php
bigdawg-v2/woocommerce/checkout/form-pay.php
bigdawg-v2/woocommerce/checkout/form-shipping.php
bigdawg-v2/woocommerce/checkout/payment-method.php
bigdawg-v2/woocommerce/checkout/payment.php
bigdawg-v2/woocommerce/checkout/review-order.php
bigdawg-v2/woocommerce/checkout/terms.php
bigdawg-v2/woocommerce/checkout/thankyou.php
bigdawg-v2/woocommerce/content-product.php
bigdawg-v2/woocommerce/content-product_cat.php
bigdawg-v2/woocommerce/content-single-product.php
bigdawg-v2/woocommerce/content-widget-product.php
bigdawg-v2/woocommerce/emails/admin-cancelled-order.php
bigdawg-v2/woocommerce/emails/admin-failed-order.php
bigdawg-v2/woocommerce/emails/admin-new-order.php
bigdawg-v2/woocommerce/emails/customer-completed-order.php
bigdawg-v2/woocommerce/emails/customer-invoice.php
bigdawg-v2/woocommerce/emails/customer-new-account.php
bigdawg-v2/woocommerce/emails/customer-note.php
bigdawg-v2/woocommerce/emails/customer-on-hold-order.php
bigdawg-v2/woocommerce/emails/customer-processing-order.php
bigdawg-v2/woocommerce/emails/customer-refunded-order.php
bigdawg-v2/woocommerce/emails/customer-reset-password.php
bigdawg-v2/woocommerce/emails/email-addresses.php
bigdawg-v2/woocommerce/emails/email-customer-details.php
bigdawg-v2/woocommerce/emails/email-footer.php
bigdawg-v2/woocommerce/emails/email-header.php
bigdawg-v2/woocommerce/emails/email-order-details.php
bigdawg-v2/woocommerce/emails/email-order-items.php
bigdawg-v2/woocommerce/emails/email-styles.php
bigdawg-v2/woocommerce/emails/plain/admin-cancelled-order.php
bigdawg-v2/woocommerce/emails/plain/admin-failed-order.php
bigdawg-v2/woocommerce/emails/plain/admin-new-order.php
bigdawg-v2/woocommerce/emails/plain/customer-completed-order.php
bigdawg-v2/woocommerce/emails/plain/customer-invoice.php
bigdawg-v2/woocommerce/emails/plain/customer-new-account.php
bigdawg-v2/woocommerce/emails/plain/customer-note.php
bigdawg-v2/woocommerce/emails/plain/customer-on-hold-order.php
bigdawg-v2/woocommerce/emails/plain/customer-processing-order.php
bigdawg-v2/woocommerce/emails/plain/customer-refunded-order.php
bigdawg-v2/woocommerce/emails/plain/customer-reset-password.php
bigdawg-v2/woocommerce/emails/plain/email-addresses.php
bigdawg-v2/woocommerce/emails/plain/email-customer-details.php
bigdawg-v2/woocommerce/emails/plain/email-order-details.php
bigdawg-v2/woocommerce/emails/plain/email-order-items.php
bigdawg-v2/woocommerce/global/breadcrumb.php
bigdawg-v2/woocommerce/global/form-login.php
bigdawg-v2/woocommerce/global/quantity-input.php
bigdawg-v2/woocommerce/global/sidebar.php
bigdawg-v2/woocommerce/global/wrapper-end.php
bigdawg-v2/woocommerce/global/wrapper-start.php
bigdawg-v2/woocommerce/loop/add-to-cart.php
bigdawg-v2/woocommerce/loop/loop-end.php
bigdawg-v2/woocommerce/loop/loop-start.php
bigdawg-v2/woocommerce/loop/no-products-found.php
bigdawg-v2/woocommerce/loop/orderby.php
bigdawg-v2/woocommerce/loop/pagination.php
bigdawg-v2/woocommerce/loop/price.php
bigdawg-v2/woocommerce/loop/rating.php
bigdawg-v2/woocommerce/loop/result-count.php
bigdawg-v2/woocommerce/loop/sale-flash.php
bigdawg-v2/woocommerce/myaccount/dashboard.php
bigdawg-v2/woocommerce/myaccount/downloads.php
bigdawg-v2/woocommerce/myaccount/form-add-payment-method.php
bigdawg-v2/woocommerce/myaccount/form-edit-account.php
bigdawg-v2/woocommerce/myaccount/form-edit-address.php
bigdawg-v2/woocommerce/myaccount/form-login.php
bigdawg-v2/woocommerce/myaccount/form-lost-password.php
bigdawg-v2/woocommerce/myaccount/form-reset-password.php
bigdawg-v2/woocommerce/myaccount/lost-password-confirmation.php
bigdawg-v2/woocommerce/myaccount/my-account.php
bigdawg-v2/woocommerce/myaccount/my-address.php
bigdawg-v2/woocommerce/myaccount/my-downloads.php
bigdawg-v2/woocommerce/myaccount/my-orders.php
bigdawg-v2/woocommerce/myaccount/navigation.php
bigdawg-v2/woocommerce/myaccount/orders.php
bigdawg-v2/woocommerce/myaccount/payment-methods.php
bigdawg-v2/woocommerce/myaccount/view-order.php
bigdawg-v2/woocommerce/notices/error.php
bigdawg-v2/woocommerce/notices/notice.php
bigdawg-v2/woocommerce/notices/success.php
bigdawg-v2/woocommerce/order/form-tracking.php
bigdawg-v2/woocommerce/order/order-again.php
bigdawg-v2/woocommerce/order/order-details-customer.php
bigdawg-v2/woocommerce/order/order-details-item.php
bigdawg-v2/woocommerce/order/order-details.php
bigdawg-v2/woocommerce/order/tracking.php
bigdawg-v2/woocommerce/product-searchform.php
bigdawg-v2/woocommerce/single-product/add-to-cart/external.php
bigdawg-v2/woocommerce/single-product/add-to-cart/grouped.php
bigdawg-v2/woocommerce/single-product/add-to-cart/simple.php
bigdawg-v2/woocommerce/single-product/add-to-cart/variable.php
bigdawg-v2/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
bigdawg-v2/woocommerce/single-product/add-to-cart/variation.php
bigdawg-v2/woocommerce/single-product/meta.php
bigdawg-v2/woocommerce/single-product/photoswipe.php
bigdawg-v2/woocommerce/single-product/price.php
bigdawg-v2/woocommerce/single-product/product-attributes.php
bigdawg-v2/woocommerce/single-product/product-image.php
bigdawg-v2/woocommerce/single-product/product-thumbnails.php
bigdawg-v2/woocommerce/single-product/rating.php
bigdawg-v2/woocommerce/single-product/related.php
bigdawg-v2/woocommerce/single-product/review-meta.php
bigdawg-v2/woocommerce/single-product/review-rating.php
bigdawg-v2/woocommerce/single-product/review.php
bigdawg-v2/woocommerce/single-product/sale-flash.php
bigdawg-v2/woocommerce/single-product/share.php
bigdawg-v2/woocommerce/single-product/short-description.php
bigdawg-v2/woocommerce/single-product/stock.php
bigdawg-v2/woocommerce/single-product/tabs/additional-information.php
bigdawg-v2/woocommerce/single-product/tabs/description.php
bigdawg-v2/woocommerce/single-product/tabs/tabs.php
bigdawg-v2/woocommerce/single-product/title.php
bigdawg-v2/woocommerce/single-product/up-sells.php
bigdawg-v2/woocommerce/single-product-reviews.php
bigdawg-v2/woocommerce/single-product.php
bigdawg-v2/woocommerce/taxonomy-product_cat.php
bigdawg-v2/woocommerce/taxonomy-product_tag.php

`
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14135
