### ISSUE TITLE
New customer receives welcome email repeatedly every 6 minutes!

### ISSUE THREAD

**Issue by winepair** [woocommerce/woocommerce#14220]
### EXPLANATION OF THE ISSUE

I'm not sure if the issue is related to wooCommerce update or a plugin or what, but the new customer receives an email telling them about their reistration, every 6 mintes all day. IT has sent over a 100 emails today. Luckily it is just a test email address I used when testing the site.

What could be causing this issue?

### STEPS TO REPRODUCE THE ISSUE

Create a new customer account on www.winepair.co.za and see if the welcome email is sent to you repeatedly.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://winepair.co.za
Site URL: http://winepair.co.za
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_ZA

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30-1~dotdeb+7.1
PHP Post Max Size: 32 MB
PHP Time Limit: -1
PHP Max Input Vars: 2500
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (41) ###

Akismet Anti-Spam: by Automattic – 3.3
Better Search Replace: by Delicious Brains – 1.3
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom ShortCode Creator: by swadeshswain – 2.0
Disable WooCommerce Reviews: by pipdig – 1.1
Duplicate Post: by Enrico Battocchi – 3.2
Envato Market: by Derek Herman – 1.0.0-RC2
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp for WordPress: by ibericode – 4.1.0
VarkTech Minimum Purchase for WooCommerce: by Vark – 1.09.8
Notely: by Michael Ott – 1.3
Official StatCounter Plugin: by Aodhan Cullen – 2.0.1
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Pargo: by Pargo – 1.0.0
Password Strength for WooCommerce: by Potent Plugins – 1.0.1
Responsive Lightbox: by dFactory – 1.6.12
WC Cancel Order: by Vikram Singh – 2.1
Widget Clone: by 93digital – 1.1
Advanced AJAX Product Filter for WooCommerce: by BeRocket – 1.1.8
Booster Plus for WooCommerce: by Algoritmika Ltd – 1.1.0
WooCommerce PayFast Gateway: by WooCommerce – 1.4.1
WooCommerce SnapScan Gateway: by SnapScan – 1.0.1
WooCommerce Advanced Product Quantities: by WP BackOffice – 2.1.9
Booster for WooCommerce: by Algoritmika Ltd – 2.6.0
WooCommerce Menu Extension: by August Infotech – 1.5
WooCommerce Min and Max Quantities: by BeRocket – 2.0.3.2
WooCommerce My Account Widget: by Bart Pluijms – 0.5.0
WooCommerce PDF Invoices: by Bas Elbers – 2.6.4
WooCommerce Thumbnail Input Quantities: by WP BackOffice – 1.1.2
WP All Import - WooCommerce Add-On: by Soflyy – 1.3.2
WooCommerce: by Automattic – 3.0.1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.5
WP All Export: by Soflyy – 1.1.3
WP All Import: by Soflyy – 3.4.2
YITH WooCommerce Added to Cart Popup: by YITHEMES – 1.1.0
YITH WooCommerce Advanced Reviews: by YITHEMES – 1.2.6
YITH WooCommerce Ajax Search: by YITHEMES – 1.5.2
YITH WooCommerce Frequently Bought Together: by YITHEMES – 1.1.0
YITH WooCommerce Wishlist: by YITHEMES – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: ZAR (R)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #9 - /shop/
Basket: #23 - /cart/
Checkout: #24 - /checkout/
My account: #25 - /my-account/

### Theme ###

Name: Betheme
Version: 17.6
Author URL: http://muffingroup.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: betheme/woocommerce/archive-product.php
betheme/woocommerce/cart/cart-empty.php
betheme/woocommerce/cart/cart.php
betheme/woocommerce/cart/mini-cart.php
betheme/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
betheme/woocommerce/content-single-product.php
betheme/woocommerce/loop/loop-end.php
betheme/woocommerce/loop/loop-start.php
betheme/woocommerce/loop/no-products-found.php
betheme/woocommerce/loop/pagination.php
betheme/woocommerce/notices/error.php
betheme/woocommerce/notices/notice.php
betheme/woocommerce/notices/success.php
betheme/woocommerce/single-product/add-to-cart/external.php
betheme/woocommerce/single-product/product-image.php
betheme/woocommerce/single-product/product-thumbnails.php
betheme/woocommerce/single-product/sale-flash.php
betheme/woocommerce/single-product/tabs/additional-information.php
betheme/woocommerce/single-product/tabs/description.php
betheme/woocommerce/single-product/tabs/tabs.php
betheme/woocommerce/single-product/title.php

Outdated Templates: ❌Learn how to update
`
```
</details>

**Comment by mikejolley** [comment]
Can you check the server error logs? The background processing may be erring after send but before the option gets updated which records which emails need sending out.

**Comment by winepair** [comment]
Hi Mike
Sure - where does one look for that info?

**Comment by mikejolley** [comment]
Depends; sometimes in wp-content/debug_log

**Comment by davey-w** [comment]
Same problem here, every 5 minutes the 'order completed' e-mail is being sent to the customer. Tried to set the order status to 'processing', but the 'order completed' e-mails are still being sent out every 5 minutes for that order. No traces of any errors in the (server) error logs. 

Installed a cron plugin and deleted the cron task manually to solve this for now ('wp_wc_emailer_cron' hook, which is calling WC_Background_Emailer->handle_cron_healthcheck()  )

**System status:**
<details>
### WordPress Environment ###

Home URL: https://wpfortune.com
Site URL: https://wpfortune.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.0.17
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wpf_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Gravity Forms: by rocketgenius – 2.2.1
CodeStyling Localization: by Heiko Rabe – 1.99.30
Crayon Syntax Highlighter: by Aram Kocharyan – 2.8.4
Disable Comments: by Samir Shah – 1.6
FV Top Level Categories: by Foliovision – 1.8.2
Geev contact widget: by Geev – 0.1
Geev knop widget: by Geev – 0.1
InfiniteWP - Client: by Revmakx – 1.6.4
User Switching: by John Blackbourn – 1.0.9
WooCommerce API Manager: by Todd Lahman LLC – 1.5.3
WooCommerce DYMO Print: by WP Fortune – 2.5.1
WooCommerce EU VAT Number: by WooThemes – 2.1.14
MoneyBird API integration for WooCommerce: by Marco Cox
ExtensionTree.com – 2.4.3

WooCommerce PDF Invoices: by Andrew Benbow – 3.5.0
WooCommerce - Store Exporter Deluxe: by Visser Labs – 2.3.1
WooCommerce Subscriptions: by Prospress Inc. – 2.2.3
WooCommerce: by Automattic – 3.0.1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.5
WP Crontrol: by John Blackbourn & contributors – 1.5
WP Time Capsule: by Revmakx – 1.8.6
Custom Styles: by  –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)


### WC Pages ###

Shop base: #387 - /wordpress-plugins/
Cart: #270 - /cart/
Checkout: #271 - /checkout/
My account: #272 - /my-account/

### Theme ###

Name: Stndrd
Version: 1.0
Author URL: https://www.wpfortune.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: stndrd/woocommerce/archive-product.php
stndrd/woocommerce/emails/customer-completed-order.php
stndrd/woocommerce/emails/email-header.php
stndrd/woocommerce/single-product/add-to-cart/variable.php
stndrd/woocommerce/single-product/tabs/description.php
stndrd/woocommerce/single-product/title.php


### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Templates ###

Scheduled Export to FTP: ✔
Scheduled Export to SFTP: ❌ The required SFTP functions are not available

</details>

**Comment by mikejolley** [comment]
@davey-w can I get access somehow? Email or slack me. I want to see why it's failing on some hosts.

**Comment by davey-w** [comment]
@mikejolley Just sent you an e-mail with login credentials!

**Comment by winepair** [comment]
Now my site has stopped sending any emails whatsoever. Driving me nuts

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14268

Please note this could also be a conflict. I found some issues with plugins which attached PDFs which were stalling the queue. If in doubt, use https://gist.github.com/mikejolley/16ca078f5c74b401e6ba210644e3173d
