### ISSUE TITLE
Grouped, Up-sell, Cross-sell & MixnMatch Field does not work

### ISSUE THREAD

**Issue by Noozlie** [woocommerce/woocommerce#14234]
Hi. After updating to 3.0.1, Grouped, Up-sell, Cross-sell & MixnMatch Field does not work. I am not able to type anything in the field.

**Comment by mikejolley** [comment]
You have an extension or plugin loading select2 v3, whilst WC 3.0 requires v4. You need to find which extension it is and disable and/or update.

You can also clear browser caches in case the old version has been cached somehow.
