### ISSUE TITLE
Tax calculations wrong for zero decimal currencies

### ISSUE THREAD

**Issue by haddi77** [woocommerce/woocommerce#14230]
### EXPLANATION OF THE ISSUE

Woocommerce tax calculations don't respect the number of decimals set in Woocommerce settings.
F.x. ISK (Icelandic currency) does not use decimals, therefore I set Woocommerce to zero decimals, however when using prices inclusive of tax (24% in this example) with a product costing 10000 if I add 100pcs to the cart I would expect the total to be 1000000 and that if I had the checkout display price exclusive of tax I would expect the the values to be 806500 + 193500 tax because the taxes where rounded to zero decimal places on the unit level before being added together. But it seems that Woocommerce adds the quantity together first therefore giving me for the same example 806451 +  193548 tax for a total of 999999.

### STEPS TO REPRODUCE THE ISSUE

1. Set woocommerce decimals to 0
2. Display prices exclusive of tax in checkout
3. Enable tax calculations and put in a standard tax rate of 24%  (or any other value that 

### SYSTEM STATUS

<details>

### WordPress Environment ###

Home URL: http://borgun.webdev.is/wordpress
Site URL: http://borgun.webdev.is/wordpress
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 4000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp7i_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

WooCommerce Borgun Consumer Loan Gateway: by Vefumsjón – 1.2.0
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
WooCommerce Borgun Gateway: by Tactica – 1.2.6
WooCommerce Valitor Gateway: by Tactica – 1.2
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce: by Automattic – 3.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ISK (kr.)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Poseidon
Version: 1.0.4 – 1.2.2 is available
Author URL: https://themezee.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by mikejolley** [comment]
![2017-04-11 at 10 41](https://cloud.githubusercontent.com/assets/90977/24902876/84c41560-1ea3-11e7-8d28-6e685dc601c1.png)

![2017-04-11 at 10 41 2](https://cloud.githubusercontent.com/assets/90977/24902878/865d4126-1ea3-11e7-83c8-fb1c85c45ce7.png)

Exclusive:

![2017-04-11 at 10 42](https://cloud.githubusercontent.com/assets/90977/24902915/a49042c4-1ea3-11e7-9365-7eb8f914b10b.png)

**Comment by haddi77** [comment]
@mikejolley 
In your screenshot I see 8065 x 100 = 806452, do you not see the problem?

**Comment by haddi77** [comment]
@mikejolley 
To clarify I'm proposing adding a third option here:
![image](https://cloud.githubusercontent.com/assets/5619298/24910361/0d450512-1eb7-11e7-8818-77a25aecccc5.png)

1. Rounding on item unit level (missing)
2. Rounding per line (current default)
3. Rounding at subtotal level (currently optional)

I don't know if other countries have similar issues but in Iceland the smallest currency value is 1 ISK ~ $0.01 and the tax is calculated on a 1 unit basis, then multiplied to the quantity since otherwise the unit item tax amount would always have decimals which aren't allowed.

**Comment by mikejolley** [comment]
That would have severe implications for all calculations-  unit level rounding would also fail under most other DP settings. If the final total is correct, why bother showing ex vat on checkout?
