### ISSUE TITLE
Update Notice to include Read More link

### ISSUE THREAD

**Issue by msdesign21** [woocommerce/woocommerce#14231]
I was wondering if it would be a good idea to include a "Learn More" link in the 3.0 update alert message: 

<img src="http://cld.wthms.co/AePZ+"/>

There are a couple possible pages we could link to like the blog post announcement: https://woocommerce.com/2017/04/woocommerce-3-0-release/

But the most important message should be to backup and test before pushing the update live. If there was a 'Learn More' link this may make people click thru to read more vs. updating straightaway without considering how important it is to back up and test first which is why I may lean towards linking here instead: https://docs.woocommerce.com/document/how-to-update-your-site/

cc'ing @nicoleckohler and @californiakat for their input. 

@kevinbates - it would also be great if we could get a trackable link to see how many click on it. Would that be possible?

**Comment by nicoleckohler** [comment]
I suggested something like this somewhere on Slack a bit ago, great minds! I had no idea we could even do this so I didn't do anything with it.

I think rather than a simple "learn more" with a link, it'd be ideal if we could opt for something like:

> x.x is a **major update**. [Make a full site backup](https://docs.woocommerce.com/document/backup-wordpress-content/), update your theme and plugins and [review update best practices](https://docs.woocommerce.com/document/how-to-update-your-site/) before upgrading.

We could add a "Learn more about x.x" link at the end if we wanted, but IMO the better links would be to the best practices vs the info, esp. since the changelog sort of intros that.

Thoughts? 💃

**Comment by BurlesonBrad** [comment]
@nicoleckohler Before I bug 'em with _yet-another_ merge in the midst of their business, take a quick gander over this text and **(more importantly)** the links over to your wonderfully witty written words (a.k.a. your posts) 😜 

Unless you've got some other posts, that you think might be more appropriate, let's use the following:

[3.0 is a major update!](https://woocommerce.com/2017/04/woocommerce-3-0-release/) You Can [Read More About Bionic Butterfly Here](https://woocommerce.wordpress.com/2017/04/04/say-hello-to-woocommerce-3-0-bionic-butterfly/). It is important that you [make backups](https://docs.woocommerce.com/document/how-to-update-your-site/) and ensure themes and extensions are 3.0 compatible before upgrading.

**Comment by nicoleckohler** [comment]
@BurlesonBrad I would advise against linking both the development blog and the WooCommerce blog. This could potentially confuse customers, especially those who don't necessarily need the in-depth details of the update.

When we're creating calls to action I've found it's much better to have a single clear destination that's stated (ex. "read more on the development blog" vs a simple "read more," and the former vs. "read more here and on this other place here").

So my preference would be to go with what I've written. :)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/14250
