### ISSUE TITLE
My woocommerce can't send email to admin

### ISSUE THREAD

**Issue by legendxu** [woocommerce/woocommerce#14233]
### EXPLANATION OF THE ISSUE
When I updated the woocommerce to Version 3.0.1, I don't receive the order status from woocommerce.
I don't know whether user has received it.

Before I update the woocommerce to Version 3.0.1, I can receive email from woocommerce.

### SYSTEM STATUS
`
### WordPress Environment ###
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en

### Server Environment ###

Server Info: Apache/2.4.25
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 48 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: qy3x_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Access Denied: by wpkids – 1.0
All In One SEO Pack: by Michael Torbert – 2.3.12.2.1
Category SEO Meta Tags: by Bala Krishna
Sergey Yakovlev – 2.5

Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.19
Eggplant 301 Redirects: by Shawn Wernig http://www.eggplantstudios.ca – 2.3.0
No Category Parents: by Sergio Milardovich – 0.2.4.1
Really Simple SSL: by Rogier Lankhorst – 2.5.11
Shareaholic | share buttons, analytics, related content: by Shareaholic – 7.8.0.6
WooCommerce - All in One SEO Pack: by Visser Labs – 1.3.4
WooCommerce ShareThis Integration: by WooThemes – 1.0
WooCommerce: by Automattic – 3.0.1
WooSidebars: by WooThemes – 1.4.3
WooThemes Helper: by WooThemes – 1.5.9 – Network enabled
YITH WooCommerce Wishlist: by YITHEMES – 2.1.0
Elfsight Yottie Lite: by Elfsight – 1.2.0

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #704 - /shop/
Cart: #156 - /cart/
Checkout: #158 - /checkout/
My account: #160 - /my-account/

### Theme ###

Name: Mystile
Version: 1.3.3 – 1.3.19 is available
Author URL: http://www.woothemes.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
I need access to a site to debug (email if possible), but this will work around the issue in the meantime. https://gist.github.com/mikejolley/16ca078f5c74b401e6ba210644e3173d

**Comment by legendxu** [comment]
@mikejolley https://gist.github.com/mikejolley/16ca078f5c74b401e6ba210644e3173d to disable woocommerce email function?

**Comment by legendxu** [comment]
It works! I have tried! Thanks!
