### ISSUE TITLE
Calling the order key URL of a deleted order causes an exception

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/woocommerce#14239]
### EXPLANATION OF THE ISSUE

Fatal error: Uncaught Error: Call to a member function get_order_key() on boolean in /home/zuegerpi/www/beta.firewoodshop.ch/wp-content/plugins/woocommerce/includes/wc-cart-functions.php:169 Stack trace: #0 /home/zuegerpi/www/beta.firewoodshop.ch/wp-includes/class-wp-hook.php(298): wc_clear_cart_after_payment(NULL) #1 /home/zuegerpi/www/beta.firewoodshop.ch/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #2 /home/zuegerpi/www/beta.firewoodshop.ch/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /home/zuegerpi/www/beta.firewoodshop.ch/wp-includes/general-template.php(35): do_action('get_header', NULL) #4 /home/zuegerpi/www/beta.firewoodshop.ch/wp-content/themes/storefront/page.php(13): get_header() #5 /home/zuegerpi/www/beta.firewoodshop.ch/wp-includes/template-loader.php(74): include('/home/zuegerpi/...') #6 /home/zuegerpi/www/beta.firewoodshop.ch/wp-blog-header.php(19): require_once('/home/zuegerpi/...') #7 /home/zuegerpi/www/beta.firewoodshop.ch/index.php(17): require('/home/zuegerpi/...') in /home/zuegerpi/www/beta.firewoodshop.ch/wp-content/plugins/woocommerce/includes/wc-cart-functions.php on line 169

### STEPS TO REPRODUCE THE ISSUE

1. Create an order in Woocommerce
2. Delete the order in admin, also remove from trash
3. Call the URL the user get like https://...../order-received/790/?key=wc_order_58ec69d976086

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://beta.firewoodshop.ch
Site URL: https://beta.firewoodshop.ch
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_CH

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 7.0.17
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: fws_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Contact Form 7: von Takayuki Miyoshi – 4.7
Email Address Encoder: von Till Krüss – 1.0.5
WooCommerce Delivery Slots: von Iconic – 1.7.4
Limit Login Attempts Reloaded: von wpchefgadget – 2.5.0
Storefront Designer: von WooThemes – 1.8.4
WooCommerce Custom Invoice BACS Gateway: von Thomas Zueger – 1.0.1
WooCommerce Round Numbers: von Thomas Zueger – 1.0
WooCommerce Dynamic Pricing & Discounts: von RightPress – 1.1.2
Mindestbestellmenge: von Morning Train Technologies ApS – 2.2.0
WooCommerce Conditional Shipping and Payments: von WooThemes – 1.2.4
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 1.6.2
WooCommerce PDF Invoices & Packing Slips Premium Templates: von Ewout Fernhout – 2.3.0
WooCommerce Table Rate Shipping: von Automattic – 3.0.2
WooCommerce: von Automattic – 3.0.1
WooCommerce Helper: von WooCommerce – 1.7.2 – Netzwerk aktiviert

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CHF (CHF)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /
Warenkorb: #5 - /warenkorb/
Kasse: #6 - /kasse/
My account: #7 - /mein-konto/

### Theme ###

Name: Storefront Child Theme
Version: 1.0
Author URL: http://woothemes.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/emails/customer-invoice.php
storefront-child/woocommerce/emails/email-order-details.php

`
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14247
