### ISSUE TITLE
Brands-Plugin with WooCommerce 

### ISSUE THREAD

**Issue by johnwrise** [woocommerce/woocommerce#14238]
Products not show brands array after woocommerce upgraded to 3.0, using woocommerce brand 1.5.

And wanted to show brands array on orders, previously hook 'my_prepare_item_for_response' and add/call brands array inside the $line_item on function, it work perfectly, after woocommerce 3.0, do not work anymore, any hook to apply this??

**Comment by mikejolley** [comment]
Seems to work https://dl.dropboxusercontent.com/s/gsmg0f8pz70gikm/2017-04-11%20at%2010.29.png

Please use the helpdesk for extension issues https://woocommerce.com/my-account/tickets/

**Comment by johnwrise** [comment]
Sorry, maybe i did not describe properly, i did not get the brands array using woocommerce rest api using endpoints products or orders

**Comment by mikejolley** [comment]
There is a new API in 3.0 so to use the new API your custom code will need adjustments.

**Comment by johnwrise** [comment]
brands array is show when using woocommerce 2.6, only upgraded to 3.0 the brands array dissappear on API endpoint products.

For the API endpoint orders, woocommerce 2.6, i hooked my_prepare_item_for_response' and add some script inside the $line_item on my theme function.php. When i using endpoint orders, under the line_item will show brands array, can woocommerce 3.0 api possible make the hook(file:class-wc-rest-orders-controller.php, line:147 get_order_item_data) for this, thanks
