### ISSUE TITLE
Same cross-sell product displays multiple times in cart

### ISSUE THREAD

**Issue by gspitzer** [woocommerce/woocommerce#14246]
**Short description:** the same cross-sell product is displayed multiple times in the cart, if that same cross-sell product is assigned to multiple products that are placed to the cart.

**Expected behaviour:** one cross-sell product should be displayed only once in the cart, even if the same cross-sell product is assigned to multiple products that are placed to the cart.

**Testing environment (Pressable test site):**

WooCommerce: 3.0.1
WordPress: 4.7.3
Theme: Twenty Seventeen
Plugins enabled: Akismet, Jetpack, VaultPress, WooCommerce

**Steps to reproduce:**

- Created two different test products (**Test Product - Cross Sell Duplicates** and **Test Product - Cross Sell Duplicates 2**)

- Assigned the same cross-sell product (**Test Product A**) to both test products.

- Added **Test Product - Cross Sell Duplicates** to the cart, **Test Product A** was displayed.

- Added **Test Product - Cross Sell Duplicates 2** to the cart too, the same **Test Product A** got displayed two times, as Test Product A is assigned to both products in the cart.

![https://cloudup.com/cZO6F_hIvNG](https://cloudup.com/cZO6F_hIvNG+)

Image Link: https://cloudup.com/cZO6F_hIvNG

- The more I add, the more is displayed. The same cross-sell product displays multiple times, if products are added to the cart that have the same cross-sell product assigned. 

![https://cloudup.com/ctoolHESaGa](https://cloudup.com/ctoolHESaGa+)

Image Link: https://cloudup.com/ctoolHESaGa

- Checked on WooCommerce 2.6.14: the same cross-sell product is displayed only once, even if that was assigned to multiple products in the cart.

**Ticket:** 558752-zd-woothemes

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/14198
