### ISSUE TITLE
Adding Variable Products into the Cart is creating problem

### ISSUE THREAD

**Issue by parthagithub** [woocommerce/woocommerce#14241]
### EXPLANATION OF THE ISSUE

There are issues when a variable product is added to the cart. I am pasting screenshot links of the issues.

### STEPS TO REPRODUCE THE ISSUE

1. http://prntscr.com/ev03a2
2. http://prntscr.com/ev042l
3. http://prntscr.com/ev04fl
4. http://prntscr.com/ev057g
5. http://prntscr.com/ev05gb
6. http://prntscr.com/ev05zv

Also in the admin when I go the order details, list products are not displayed after the first one. Please check the attached screenshot.
![screenshot_1](https://cloud.githubusercontent.com/assets/10935510/24896917/9eae5358-1eb4-11e7-8477-b244093cdbfb.png)

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.bengalshopping.com
Site URL: https://www.bengalshopping.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.31 (Unix)
PHP Version: 5.6.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.49.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: bs_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (48) ###

Accordion Shortcodes: by Phil Buchanan – 2.3.2
Akismet Anti-Spam: by Automattic – 3.3
Brute Force Login Protection: by Fresh-Media – 1.5.2
WooCommerce CCAvenue gateway: by mRova – 1.2.4
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.9
Contact Form DB: by Michael Simpson – 2.10.29
Contact Form 7: by Takayuki Miyoshi – 4.7
Easy FancyBox: by RavanH – 1.5.8.2
WooCommerce - Gift Cards: by WP Ronin – 2.5.6
Max Mega Menu: by Tom Hemsley – 2.3.5
Meta Slider: by Matcha Labs – 3.5
myStickymenu: by m.r.d.a – 1.8.3
Newsletter: by Stefano Lissa & The Newsletter Team – 4.8.9
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 2.9
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SEO Ultimate: by SEO Design Solutions – 7.6.5.9
SI Captcha Anti-Spam: by Mike Challis – 3.0.0.10
Simple Custom CSS: by John Regan
Danny Van Kooten – 3.3

Ultimate WooCommerce Brands: by MagniumThemes – 1.1.2
WC Cancel Order: by Vikram Singh – 2.1
WooCommerce Weight Based Shipping: by dangoodman – 4.2.3
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.0
WooCommerce Checkout Manager: by Visser Labs – 4.1
WooCommerce COD Advanced: by Aheadzen Team – 1.2.7
WooCommerce Custom Product Tabs Lite: by SkyVerge – 1.6.1
WooCommerce Customizer: by SkyVerge – 2.4.0
WooCommerce New Product Badge: by jameskoster – 0.3.0
WooCommerce Predictive Search LITE: by a3rev Software – 4.0.0
WooCommerce Product Details Customiser: by jameskoster – 0.2.0
WooCommerce Product Gift Wrap: by Mike Jolley – 1.1.0
WooCommerce Product SKU Generator: by SkyVerge – 2.3.1
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.1
WooCommerce Show Attributes: by Isabel Castillo – 1.6
WooCommerce Smart Sale Badge: by Hugh Lashbrooke – 1.1
WooCommerce Sold Out Products: by Gerhard Potgieter – 1.0.4
WooCommerce WooCart Popup Lite: by Festi – 1.1
WooCommerce: by Automattic – 3.0.1
WooThemes Helper: by WooThemes – 1.5.7 – Network enabled
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.3.1
YITH WooCommerce Bulk Product Editing: by YITHEMES – 1.2.0
YITH WooCommerce Cart Messages: by YITHEMES – 1.2.0
YITH WooCommerce Compare: by YITHEMES – 2.2.0
YITH WooCommerce Order Tracking: by YITHEMES – 1.1.1
YITH WooCommerce Quick View: by YITHEMES – 1.2.1
YITH WooCommerce Waiting List: by YITHEMES – 1.1.0
YITH WooCommerce Wishlist: by YITHEMES – 2.1.0
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.28

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (Rs.)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Bengal Shopping
Version: 1.0
Author URL: http://www.ayanonline.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: bengalshopping/woocommerce/archive-product.php
bengalshopping/woocommerce/auth/footer.php
bengalshopping/woocommerce/auth/form-grant-access.php
bengalshopping/woocommerce/auth/form-login.php
bengalshopping/woocommerce/auth/header.php
bengalshopping/woocommerce/cart/cart-empty.php
bengalshopping/woocommerce/cart/cart-item-data.php
bengalshopping/woocommerce/cart/cart-shipping.php
bengalshopping/woocommerce/cart/cart-totals.php
bengalshopping/woocommerce/cart/cart.php
bengalshopping/woocommerce/cart/cross-sells.php
bengalshopping/woocommerce/cart/mini-cart.php
bengalshopping/woocommerce/cart/proceed-to-checkout-button.php
bengalshopping/woocommerce/cart/shipping-calculator.php
bengalshopping/woocommerce/checkout/cart-errors.php
bengalshopping/woocommerce/checkout/form-billing.php
bengalshopping/woocommerce/checkout/form-checkout.php
bengalshopping/woocommerce/checkout/form-coupon.php
bengalshopping/woocommerce/checkout/form-login.php
bengalshopping/woocommerce/checkout/form-pay.php
bengalshopping/woocommerce/checkout/form-shipping.php
bengalshopping/woocommerce/checkout/payment-method.php
bengalshopping/woocommerce/checkout/payment.php
bengalshopping/woocommerce/checkout/review-order.php
bengalshopping/woocommerce/checkout/terms.php
bengalshopping/woocommerce/checkout/thankyou.php
bengalshopping/woocommerce/content-product.php
bengalshopping/woocommerce/content-product_cat.php
bengalshopping/woocommerce/content-single-product.php
bengalshopping/woocommerce/content-widget-product.php
bengalshopping/woocommerce/emails/admin-cancelled-order.php
bengalshopping/woocommerce/emails/admin-failed-order.php
bengalshopping/woocommerce/emails/admin-new-order.php
bengalshopping/woocommerce/emails/customer-completed-order.php
bengalshopping/woocommerce/emails/customer-invoice.php
bengalshopping/woocommerce/emails/customer-new-account.php
bengalshopping/woocommerce/emails/customer-note.php
bengalshopping/woocommerce/emails/customer-on-hold-order.php
bengalshopping/woocommerce/emails/customer-processing-order.php
bengalshopping/woocommerce/emails/customer-refunded-order.php
bengalshopping/woocommerce/emails/customer-reset-password.php
bengalshopping/woocommerce/emails/email-addresses.php
bengalshopping/woocommerce/emails/email-customer-details.php
bengalshopping/woocommerce/emails/email-footer.php
bengalshopping/woocommerce/emails/email-header.php
bengalshopping/woocommerce/emails/email-order-details.php
bengalshopping/woocommerce/emails/email-order-items.php
bengalshopping/woocommerce/emails/email-styles.php
bengalshopping/woocommerce/emails/plain/admin-cancelled-order.php
bengalshopping/woocommerce/emails/plain/admin-failed-order.php
bengalshopping/woocommerce/emails/plain/admin-new-order.php
bengalshopping/woocommerce/emails/plain/customer-completed-order.php
bengalshopping/woocommerce/emails/plain/customer-invoice.php
bengalshopping/woocommerce/emails/plain/customer-new-account.php
bengalshopping/woocommerce/emails/plain/customer-note.php
bengalshopping/woocommerce/emails/plain/customer-on-hold-order.php
bengalshopping/woocommerce/emails/plain/customer-processing-order.php
bengalshopping/woocommerce/emails/plain/customer-refunded-order.php
bengalshopping/woocommerce/emails/plain/customer-reset-password.php
bengalshopping/woocommerce/emails/plain/email-addresses.php
bengalshopping/woocommerce/emails/plain/email-customer-details.php
bengalshopping/woocommerce/emails/plain/email-order-details.php
bengalshopping/woocommerce/emails/plain/email-order-items.php
bengalshopping/woocommerce/global/breadcrumb.php
bengalshopping/woocommerce/global/form-login.php
bengalshopping/woocommerce/global/quantity-input.php
bengalshopping/woocommerce/global/sidebar.php
bengalshopping/woocommerce/global/wrapper-end.php
bengalshopping/woocommerce/global/wrapper-start.php
bengalshopping/woocommerce/loop/add-to-cart.php
bengalshopping/woocommerce/loop/loop-end.php
bengalshopping/woocommerce/loop/loop-start.php
bengalshopping/woocommerce/loop/no-products-found.php
bengalshopping/woocommerce/loop/orderby.php
bengalshopping/woocommerce/loop/pagination.php
bengalshopping/woocommerce/loop/price.php
bengalshopping/woocommerce/loop/rating.php
bengalshopping/woocommerce/loop/result-count.php
bengalshopping/woocommerce/loop/sale-flash.php
bengalshopping/woocommerce/myaccount/dashboard.php
bengalshopping/woocommerce/myaccount/downloads.php
bengalshopping/woocommerce/myaccount/form-add-payment-method.php
bengalshopping/woocommerce/myaccount/form-edit-account.php
bengalshopping/woocommerce/myaccount/form-edit-address.php
bengalshopping/woocommerce/myaccount/form-login.php
bengalshopping/woocommerce/myaccount/form-lost-password.php
bengalshopping/woocommerce/myaccount/form-reset-password.php
bengalshopping/woocommerce/myaccount/lost-password-confirmation.php
bengalshopping/woocommerce/myaccount/my-account.php
bengalshopping/woocommerce/myaccount/my-address.php
bengalshopping/woocommerce/myaccount/my-downloads.php
bengalshopping/woocommerce/myaccount/my-orders.php
bengalshopping/woocommerce/myaccount/navigation.php
bengalshopping/woocommerce/myaccount/orders.php
bengalshopping/woocommerce/myaccount/payment-methods.php
bengalshopping/woocommerce/myaccount/view-order.php
bengalshopping/woocommerce/notices/error.php
bengalshopping/woocommerce/notices/notice.php
bengalshopping/woocommerce/notices/success.php
bengalshopping/woocommerce/order/form-tracking.php
bengalshopping/woocommerce/order/order-again.php
bengalshopping/woocommerce/order/order-details-customer.php
bengalshopping/woocommerce/order/order-details-item.php
bengalshopping/woocommerce/order/order-details.php
bengalshopping/woocommerce/order/tracking.php
bengalshopping/woocommerce/product-searchform.php
bengalshopping/woocommerce/single-product/add-to-cart/external.php
bengalshopping/woocommerce/single-product/add-to-cart/grouped.php
bengalshopping/woocommerce/single-product/add-to-cart/simple.php
bengalshopping/woocommerce/single-product/add-to-cart/variable.php
bengalshopping/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
bengalshopping/woocommerce/single-product/add-to-cart/variation.php
bengalshopping/woocommerce/single-product/meta.php
bengalshopping/woocommerce/single-product/photoswipe.php
bengalshopping/woocommerce/single-product/price.php
bengalshopping/woocommerce/single-product/product-attributes.php
bengalshopping/woocommerce/single-product/product-image.php
bengalshopping/woocommerce/single-product/product-thumbnails.php
bengalshopping/woocommerce/single-product/rating.php
bengalshopping/woocommerce/single-product/related.php
bengalshopping/woocommerce/single-product/review-meta.php
bengalshopping/woocommerce/single-product/review-rating.php
bengalshopping/woocommerce/single-product/review.php
bengalshopping/woocommerce/single-product/sale-flash.php
bengalshopping/woocommerce/single-product/share.php
bengalshopping/woocommerce/single-product/short-description.php
bengalshopping/woocommerce/single-product/stock.php
bengalshopping/woocommerce/single-product/tabs/additional-information.php
bengalshopping/woocommerce/single-product/tabs/description.php
bengalshopping/woocommerce/single-product/tabs/tabs.php
bengalshopping/woocommerce/single-product/title.php
bengalshopping/woocommerce/single-product/up-sells.php
bengalshopping/woocommerce/single-product-reviews.php
bengalshopping/woocommerce/single-product.php
bengalshopping/woocommerce/taxonomy-product_cat.php
bengalshopping/woocommerce/taxonomy-product_tag.php

`
</details>

**Comment by mikejolley** [comment]
You need to do 2 things;

1. Check the server error log for PHP errors (I think an extension is erring which stops the admin bar rendering)
2. In Chrome, go to View > Developer > Javascript console, and see if there are JS errors.

Both appear to be incompatibilities with a plugin since they are specific issues to your store.

https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Comment by mikejolley** [comment]
Gift cards for wc errors: 
![2017-04-11 at 10 26](https://cloud.githubusercontent.com/assets/90977/24902241/7433fc08-1ea1-11e7-9426-6aca7d7e980e.png)

**Comment by parthagithub** [comment]
Thank you for your help. It is working fine now. Thanks again.
