### ISSUE TITLE
wc_fragments_loaded not triggered after ajax add to cart

### ISSUE THREAD

**Issue by michael-crowdy** [woocommerce/woocommerce#14245]
### EXPLANATION OF THE ISSUE

On line 105 of woocommerce/assets/js/frontend/add-to-cart.js the fragments are replaced. Comparing this with a similar function on line 137 of woocommerce/assets/js/frontend/cart-fragments.js the same is happening but its followed by $( document.body ).trigger( 'wc_fragments_loaded' ); I was using this trigger to add an element within the mini-cart. Could this trigger be added here or a new trigger that could be used to make changes after the html has been replaced inside the mini cart. 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/14248
