### ISSUE TITLE
When the order was created, order total is incorrect? 

### ISSUE THREAD

**Issue by jameshwartlopez** [woocommerce/woocommerce#14249]
### EXPLANATION OF THE ISSUE

Im running some test on order but it looks like a certain combination or products leads to  order total being incorrect. I wonder if I should post it here or not because this is the only order that went wrong because of the product and quantity combination. 

### STEPS TO REPRODUCE THE ISSUE

Product1 price: 2.5
Product2 price: 16.5
Product3 price: 25.99

**Shipping Cost is 10 which is not taxable**
![image](https://cloud.githubusercontent.com/assets/12094295/24903899/63dd2984-1ee1-11e7-9f0d-1133fcf66092.png)

**Heres my standard rates set up**
![image](https://cloud.githubusercontent.com/assets/12094295/24903793/0dfaac62-1ee1-11e7-8ecc-3e0902b15955.png)

When the order was created, order total is incorrect.
![image](https://cloud.githubusercontent.com/assets/12094295/24903730/d5a9915c-1ee0-11e7-8355-32bcc6a08af5.png)

### SYSTEM STATUS

<details>

WordPress environment
Home URL:		http://localhost/vend
Site URL:		http://localhost/vend
WC version:		3.0.1
Log directory writable:		 G:\xampp\htdocs\vend/wp-content/uploads/wc-logs/
WP version:		4.7.3
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		–
WP cron:		
Language:		en_US
Server environment
Server info:		Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/7.0.13
PHP version:		7.0.13
PHP post max size:		8 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.51.0, OpenSSL/1.0.2h
SUHOSIN installed:		–
Max upload size:		2 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		 Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		2.6.14
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (3)
Formidable Forms	 	by Strategy11 – 2.03.04
linksync for WooCommerce	 	by linksync – 2.4.17
WooCommerce	 	by Automattic – 3.0.1
Settings
API enabled:		
Force SSL:		–
Currency		NZD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
WC pages
Shop base:		 Page not set
Cart:		#8 - /cart/
Checkout:		#10 - /checkout/
My account:		 Page not set
Theme
Name:		Twenty Seventeen
Version:		1.0 – 1.1 is available
Author URL:		https://wordpress.org/
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Overrides:	 	–
</details>

**Comment by mikejolley** [comment]
Add the line taxes, not the total. Thats rounded separately.
