### ISSUE TITLE
Navigate Back issue after adding a product to cart

### ISSUE THREAD

**Issue by Track77** [woocommerce/woocommerce#14252]
### EXPLANATION OF THE ISSUE

Reproduced in WooCommerce 2.6.14 and 3.0.1
Internet explorer or chrome

Receive an error message like "Confirm Form Resubmission" in browser after press navigate back

### STEPS TO REPRODUCE THE ISSUE

- Add product to cart

- Navigate to any another product

- Try navigate back using a button in internet explorer or chrome 

### SYSTEM STATUS

<details>
Site https://test.3d-kstudio.com
Sorry - i can't open the page /wp-admin/admin.php?page=wc-settings - i receive a message "Gateway Timeout"

</details>

**Comment by mikejolley** [comment]
This is because add to cart is a POST, and we don't redirect after adding to cart (that is slower). This is expected.
