### ISSUE TITLE
Random sorting products using shortcodes orderby="rand" not working

### ISSUE THREAD

**Issue by juliajonesltd** [woocommerce/woocommerce#14260]

**Comment by adnanmultidots** [comment]
Hello @juliajonesltd 

I have tested and it's working fine. If you want to display product randomly so you can add [order='ASC' or order="DESC"].

Thanks

**Comment by juliajonesltd** [comment]
@adnanmultidots Strange! I have tested it in a local installation too with the same behaviour. Is it working for you in the sense that on each refresh a new product order is displayed? I tried adding in order="asc" and it makes no difference.

Will try with a clean install...

**Comment by mikejolley** [comment]
Shortcode output is CACHED in a transient. Running rand() queries for all visitors on each reload does not scale.

**Comment by juliajonesltd** [comment]
@mikejolley  Sorry, I don't quite understand why the behaviour changed with the new release. The 'related products' section displays a new random set of products upon each refresh, for example.

**Comment by mikejolley** [comment]
> Running rand() queries for all visitors on each reload does not scale.

**Comment by melindahelt** [comment]
I cleared transients in my WooCommerce install and this shortcode which worked in 2.6.14, `[product_category category="hoodies" orderby="rand"]`, no longer seems to generate random order in 3.0. All visitors see the products in the same order. Tested on both a staging site and a local install. Tested this after seeing at least two tickets related to random shortcode.

**Comment by mikejolley** [comment]
Showing random results to every visitor on every page load without caching is still a terrible idea. This was disabled for a reason.

**Comment by mikejolley** [comment]
@justinshreve @claudiosanches @claudiulodro What are your thoughts on this? Let sites burn, or leave the caching in place? The transient I believe can be filtered to disable cache if needed.

**Comment by claudiulodro** [comment]
I think it's good with the caching in place. 

How would a visitor know the results are cached and not uniquely random for them unless they are literally sitting next to someone and comparing, anyways?

**Comment by mikejolley** [comment]
@claudiulodro can we ask in dev chat?

**Comment by opusuno** [comment]
random should be random

**Comment by mikejolley** [comment]
@opusuno it is random, then cached. As stated above.

**Comment by claudiosanches** [comment]
We can go with @thenbrent ideas:

> separate caches of random order, so you do one query, get a random ordered set, then cache that, then you do another query, get a different random ordered set, then cache that, and repeat for a number of times, say 10, then when a customer orders by random, you choose 1 of those 10

**Comment by mikejolley** [comment]
This is a nice to have but not essential item for 3.1. I'm moving it to 3.2 to allow more time on other items.

**Comment by Eetheart** [comment]
This is actually a bigger issue than what is stated. Random should truly be random. Maybe exclude caching on elements that have orderby="rand"?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16725
