### ISSUE TITLE
Simple Product Add to Cart Quantity Reset issue

### ISSUE THREAD

**Issue by chirag255** [woocommerce/woocommerce#14264]
Simple Product add to cart quantity input field does't reset to 1 after adding >1 products in cart. i.e After adding 4 qty to cart, the product input quantity field stay default to 4 qty. 
Moreover  the qty fields for products display with [products ids=""] shortcode also set default to 4 qty.

I have tried with storefront theme. Issue remains the same.
I am not sure this behaviour should be like that or not.

Screenshot attached at: https://ibb.co/g1RrWQ

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: https://03972bd.ledworldlighting.com
Site URL: https://03972bd.ledworldlighting.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

HTML in Category Descriptions: by Arno Esterhuizen – 1.2.1.1
AMP: by Automattic – 0.4.2
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Post Type UI: by WebDevStudios – 1.5.3
Font Awesome 4 Menus: by New Nine Media – 4.7.0
Jetpack by WordPress.com: by Automattic – 4.8.2
LED World Canada Site Settings: by LED World – 1.0.1
Remove Query Strings From Static Resources: by Speed Up My Website
Your WP Expert – 1.4

SG Optimizer: by SiteGround – 3.2.3
WooCommerce Barcode Invoice: by LedWorld – 1.0
WooCommerce Composite Products: by WooThemes – 3.9.0
Woocommerce Custom Tabs: by WebshopLogic – 1.0.18
WooCommerce Beanstream Gateway: by SkyVerge – 1.11.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.2
WooCommerce Services: by Automattic – 1.3.2
WooCommerce FedEx Shipping: by WooCommerce – 3.4.5
WooCommerce Stock Out Customer Note: by LedWorld – 0.1
WooCommerce: by Automattic – 3.0.1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.6
YITH Plugin Framework Temporary Fix: by YITHEMES – 1.0.0
YITH WooCommerce Color and Label Variations Premium: by YITHEMES – 1.3.0
YITH WooCommerce Coupon Email System Premium: by YITHEMES – 1.1.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: LED World Canada
Version: 1.0
Author URL: http://ledworld.ca
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: ledworld/woocommerce/archive-product.php
ledworld/woocommerce/cart/cart-empty.php
ledworld/woocommerce/cart/cart-shipping.php
ledworld/woocommerce/cart/cart-totals.php
ledworld/woocommerce/cart/cart.php
ledworld/woocommerce/cart/shipping-calculator.php
ledworld/woocommerce/checkout/form-billing.php
ledworld/woocommerce/checkout/form-checkout.php
ledworld/woocommerce/checkout/form-coupon.php
ledworld/woocommerce/checkout/form-login.php
ledworld/woocommerce/checkout/form-shipping.php
ledworld/woocommerce/checkout/payment.php
ledworld/woocommerce/checkout/review-order.php
ledworld/woocommerce/checkout/thankyou.php
ledworld/woocommerce/content-product.php
ledworld/woocommerce/content-product_cat.php
ledworld/woocommerce/content-single-product.php
ledworld/woocommerce/emails/admin-new-order.php
ledworld/woocommerce/emails/customer-completed-order.php
ledworld/woocommerce/emails/customer-invoice.php
ledworld/woocommerce/emails/customer-on-hold-order.php
ledworld/woocommerce/emails/customer-processing-order.php
ledworld/woocommerce/emails/email-addresses.php
ledworld/woocommerce/emails/email-footer.php
ledworld/woocommerce/emails/email-header.php
ledworld/woocommerce/emails/email-order-details.php
ledworld/woocommerce/emails/email-order-items.php
ledworld/woocommerce/emails/email-styles.php
ledworld/woocommerce/global/quantity-input.php
ledworld/woocommerce/loop/loop-end.php
ledworld/woocommerce/loop/loop-start.php
ledworld/woocommerce/loop/orderby.php
ledworld/woocommerce/loop/pagination.php
ledworld/woocommerce/myaccount/form-add-payment-method.php
ledworld/woocommerce/myaccount/form-edit-account.php
ledworld/woocommerce/myaccount/form-login.php
ledworld/woocommerce/myaccount/form-lost-password.php
ledworld/woocommerce/myaccount/my-account.php
ledworld/woocommerce/single-product/add-to-cart/external.php
ledworld/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.0
ledworld/woocommerce/single-product/add-to-cart/simple.php
ledworld/woocommerce/single-product/add-to-cart/variable.php
ledworld/woocommerce/single-product/meta.php
ledworld/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
ledworld/woocommerce/single-product/product-image.php
ledworld/woocommerce/single-product/product-thumbnails.php
ledworld/woocommerce/single-product/share.php
ledworld/woocommerce/single-product/tabs/description.php
ledworld/woocommerce/single-product/tabs/tabs.php
ledworld/woocommerce/single-product/title.php
ledworld/woocommerce/single-product/up-sells.php
ledworld/woocommerce/single-product-reviews.php
ledworld/woocommerce/single-product.php
ledworld/woocommerce/taxonomy-product_cat.php
ledworld/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌Learn how to update
`

**Comment by mikejolley** [comment]
Yes, it remembers this. Useful if submission fails for any reason.

Multiple product pages on a single page is edge case - we have no way to prevent this since all forms use the same input names.
