### ISSUE TITLE
[3.0] "Billing State/Country required" error for certain countries

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce#14266]
### EXPLANATION OF THE ISSUE
WordPress: 4.7.3
WooCommerce: 3.0.1

When selecting certain countries as your billing country, the checkout incorrectly produces the following error:

> Billing state / country is a required field
![](http://cld.wthms.co/aWZT+)
Image Link: http://cld.wthms.co/aWZT

### STEPS TO REPRODUCE THE ISSUE
Upon checkout set your billing address country to `Kuwait`
Try to checkout

**Comment by volkerforster** [comment]
Does that problem has been resolved????? I can't find anything about it, and this thread here just ended suddenly.

I need to have the county/state field mandatory for Canada, but I can NOT sell a thing for example to France, because of that error message. How can I fix this?
