### ISSUE TITLE
variation_id was called incorrectly

### ISSUE THREAD

**Issue by ribeiroeder** [woocommerce/woocommerce#14265]
Hello

I'm having trouble adapting code that calculates discount percentage.
It worked fine in version 2.6.x, however in the 3.0 encounter notices in the log.

`	  <?php
	  $sale_price = get_post_meta( $product->get_id(), '_sale_price', true);
	  $regular_price = get_post_meta( $product->get_id(), '_regular_price', true);
	  
	  if (empty($sale_price)){ //then this is a variable product
		  $available_variations = $product->get_available_variations();
		  $variation_id = $available_variations[0]['variation_id'];
		  $variation = new WC_Product_Variation( $variation_id );
		  $regular_price = $variation ->regular_price;
		  $sale_price = $variation ->sale_price;
	  }
	  $sale = ceil(( ($regular_price - $sale_price) / $regular_price ) * 100);
      ?>`

error log:
regular_price was called incorrectly, Product properties should not be accessed directly. This message was added in version 3.0
sale_price was called incorrectly, Product properties should not be accessed directly. This message was added in version 3.0

**Comment by rafsuntaskin** [comment]
You are not allowed to access properties directly from now on. Instead use given setter and getter functions :

` $regular_price = $variation ->get_regular_price();
	  $sale_price = $variation ->get_sale_price();`

**Comment by ribeiroeder** [comment]
Hello rafsuntaskin 

It worked perfectly, thank you very much.
