### ISSUE TITLE
Emails New Order and Processing Order are not being send after update 3.0 

### ISSUE THREAD

**Issue by ashkan-fp** [woocommerce/woocommerce#14261]
### EXPLANATION OF THE ISSUE

After the update 3.0 are emails to customers (Processing Order) and our customer department (New Order) are not being send after the latest update. 

We switched back to an older version of our site, and now the emails are being send again, so the issue is related to the 3.0 version of Woocommerce.

The error message = 

2017/04/10 11:49:24 [error] 30525#30525: *195151 FastCGI sent in stderr: "PHP message: PHP Warning: Invalid argument supplied for foreach() in /var/www/befrancot-tildio/wordpress/current/wp-content/plugins/woocommerce/includes/libraries/wp-background-process.php on line 299" while reading response header from upstream, client: 139.162.193.215, server: www.francotyp.be, request: "POST /wp-admin/admin-ajax.php?action=wp_wc_emailer&nonce=bc6b500799 HTTP/1.1", upstream: "fastcgi://unix:/dev/shm/php-fpm.befrancot-tildio.sock:", host: "www.francotyp.be", referrer: "https://www.francotyp.be/wp-admin/admin-ajax.php?action=wp_wc_emailer&nonce=bc6b500799"

### STEPS TO REPRODUCE THE ISSUE

Update to 3.0

### SYSTEM STATUS

<details>

WordPress Environment
Home URL: 		https://www.francotyp.be
Site URL: 		https://www.francotyp.be
WC Version: 		2.6.14
Log Directory Writable: 		/var/www/befrancot-tildio/wordpress/current/wp-content/uploads/wc-logs/
WP Version: 		4.7.3
WP Multisite: 		–
WP Memory Limit: 		256 MB
WP Debug Mode: 		–
WP Cron: 		
Language: 		en_US
Server Environment
Server Info: 		nginx/1.10.2
PHP Version: 		5.6.26
PHP Post Max Size: 		64 MB
PHP Time Limit: 		120
PHP Max Input Vars: 		3000
cURL Version: 		7.53.1, OpenSSL/1.0.1e
SUHOSIN Installed: 		–
MySQL Version: 		5.6.29	
Max Upload Size: 		64 MB
Default Timezone is UTC: 		
fsockopen/cURL: 		
SoapClient: 		
DOMDocument: 		
GZip: 		
Multibyte String: 		
Remote Post: 		
Remote Get: 		
Database
WC Database Version: 		2.6.14
woocommerce_sessions 	  	
woocommerce_api_keys 	  	
woocommerce_attribute_taxonomies 	  	
woocommerce_downloadable_product_permissions 	  	
woocommerce_order_items 	  	
woocommerce_order_itemmeta 	  	
woocommerce_tax_rates 	  	
woocommerce_tax_rate_locations 	  	
woocommerce_shipping_zones 	  	
woocommerce_shipping_zone_locations 	  	
woocommerce_shipping_zone_methods 	  	
woocommerce_payment_tokens 	  	
woocommerce_payment_tokenmeta 	  	
Active Plugins (31)
Gravity Forms 	  	by rocketgenius – 2.2.1
WooCommerce (nl) 	  	by Pronamic – 1.1.7
Advanced Custom Fields Multilingual 	  	by OnTheGo Systems – 0.4
Black Studio TinyMCE Widget 	  	by Black Studio – 2.3.1
EU Cookie Law 	  	by Alex Moss, Marco Milesi, Peadig, Shane Jones – 2.10
Global Content Blocks 	  	by Dave Liske – 2.1.5
Gravity Forms Event Tracking 	  	by Ronald Huereca – 2.0.3
Gravity Forms Multilingual 	  	by OnTheGoSystems – 1.3.14
Head, Footer and Post Injections 	  	by Stefano Lissa – 3.0.7
Media Library Assistant 	  	by David Lingren, Fair Trade Judaica – 2.51
Quick Page/Post Redirect Plugin 	  	by anadnet – 5.1.8
Really Simple CAPTCHA 	  	by Takayuki Miyoshi – 1.9
Shortcodes Ultimate 	  	by Vladimir Anokhin – 4.9.9
Page Builder by SiteOrigin 	  	by SiteOrigin – 2.4.25
WPML Multilingual CMS 	  	by OnTheGoSystems – 3.6.3
SiteOrigin Widgets Bundle 	  	by SiteOrigin – 1.8.2
Styles & Layouts Gravity Forms 	  	by Sushil Kumar – 2.0.8
TinyMCE Advanced 	  	by Andrew Ozz – 4.4.3
UpdraftPlus - Backup/Restore 	  	by UpdraftPlus.Com, DavidAnderson – 1.12.40
Woo Checkout Field Editor Pro 	  	by ThemeHiGH – 1.1.6
WooCommerce Advanced Free Shipping 	  	by Jeroen Sormani – 1.1.0
WooCommerce Customizer 	  	by SkyVerge – 2.4.0
WooCommerce Google Analytics Integration 	  	by WooThemes – 1.4.0
WooCommerce Multilingual 	  	by OnTheGoSystems – 4.1.2
WooCommerce 	  	by WooThemes – 2.6.14
Yoast SEO 	  	by Team Yoast – 4.6
WP Smush 	  	by WPMU DEV – 2.6.2
WPML Media 	  	by OnTheGoSystems – 2.1.24
WPML Page Builders 	  	by OnTheGoSystems – 1.0.0
WPML String Translation 	  	by OnTheGoSystems – 2.5.2
WPML Translation Management 	  	by OnTheGoSystems – 2.2.7
Settings
Force SSL: 		–
Currency 		EUR (€)
Currency Position 		left
Thousand Separator 		.
Decimal Separator 		,
Number of Decimals 		2
API
API Enabled: 		
WC Pages
Shop Base:		#15 - /shop/
Cart:		#2819 - /cart/
Checkout:		#17 - /checkout/
My Account:		#18 - /my-account/
Taxonomies
Product Types: 	  	external (external), grouped (grouped), simple (simple), variable (variable)
Theme
Name: 		Customizr Pro
Version: 		1.3.2
Author URL: 		http://presscustomizr.com/
Child Theme: 		– If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce Support: 		
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14268

**Comment by ntsekouras** [comment]
I have the exact same problem and i tried updating the file you had commited but with no wanted results.
(https://github.com/woocommerce/woocommerce/pull/14268/commits/63cd7c25d03dcf335078174d7b219896a37e91b8). 

any idea?

If i go to order actions -> send again some mail (new order or anything) it sends it ok.

My problem is when a customer makes new order and for sure when the admin changes order status to complete.

thanks
