### ISSUE TITLE
So many issues

### ISSUE THREAD

**Issue by LadySlynn** [woocommerce/woocommerce#14262]
### EXPLANATION OF THE ISSUE

After the update to 3.0.1 all of our variable products information was deleted, I've had to manually input information for about 58 products.  It is no longer sending emails for new orders, and some of the information sent to our shipping program was missing.

For now I'm am going to roll back to the version before 3.0.0 when everything worked how we wanted it to. At least until these bugs are fixed.

### SYSTEM STATUS

Home URL: https://bulletcentral.com
Site URL: https://bulletcentral.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_j63rfqj01t_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

ZitchDog Sort Shipping by Price: by Saralynn – .01
Ajax Search Lite: by Ernest Marcinko – 4.7.3
AuctionInc ShippingCalc for WooCommerce: by Paid
Inc. – 1.12

Autoptimize: by Frank Goossens (futtta) – 2.1.0
Anti-Spam by CleanTalk: by СleanTalk  – 5.61
Converge Gateway for WooCommerce: by Jacob Davidson – 2.0.0
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.43
Contact Form 7: by Takayuki Miyoshi – 4.7
Content Views: by PT Guy – 1.9.7
WooCommerce Coupon Generator: by Jeroen Sormani – 1.0.0
Easy Table: by Takien – 1.6
Envato WordPress Toolkit: by Envato – 1.7.3
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp: by MailChimp – 1.5.7
WooCommerce Product Filter: by Mihajlovic Nenad – 6.1.1
ReadyShipper WooCommerce API: by TrueShip
LLC – 1.0.5

Really Simple SSL: by Rogier Lankhorst – 2.5.11
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Scripts-To-Footer: by Joshua David Nelson – 0.6.1
U-Design WooCommerce Integration: by Andon – 2.1.16
U-Design Shortcode Insert Button: by Andon – 1.1.7
WC Password Strength Settings: by Daniel Santoro – 1.1.0
WC Return products: by Paco Castillo – 1.5
WooChimp: by RightPress – 2.2.1
WooCommerce Anti Fraud: by WooCommerce – 1.0.8
WooCommerce Extended Coupon Features: by Soft79 – 2.4.0
Woocommerce Bulk Attribute Manager: by Varun Sridharan – 2.2.1
WooCommerce Cart Tab: by jameskoster – 1.1.1
WooCommerce - Country Based Payments: by Ivan Paulin – 1.1.6.1
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Product Badge: by Terry Tsang – 1.0.4
WooCommerce FedEx Shipping: by WooCommerce – 3.4.5
WooCommerce: by Automattic – 3.0.1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.5
YITH WooCommerce Badge Management: by YITHEMES – 1.3.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/

### Theme ###

Name: U-Design Child
Version: 2.10.7
Author URL: http://themeforest.net/user/andondesign/portfolio?ref=AndonDesign
Child Theme: ✔
Parent Theme Name: U-Design
Parent Theme Version: 2.12.1
Parent Theme Author URL: https://themeforest.net/user/andondesign/portfolio?ref=AndonDesign
WooCommerce Support: ✔

### Templates ###

Overrides: U-design Child/woocommerce/cart/cart-shipping.php
U-design Child/woocommerce/checkout/thankyou.php
U-design Child/woocommerce/emails/admin-new-order.php
U-design Child/woocommerce/emails/email-order-details.php

`

**Comment by mikejolley** [comment]
- There is an open PR for issues for workarounds on some hosts (it's not on all sites) or disable the email queue with https://gist.github.com/mikejolley/16ca078f5c74b401e6ba210644e3173d
- The variable product issue can be 1 of 2 things; a plugin conflict (so they are hidden in admin but there) or a bug in 3.0.0 which trashed them when changing product type from variable to simple (recover with https://gist.github.com/mikejolley/7dc21432643a4fdd342474dc2694a22d)
- Shipping, down to the extension.
