### ISSUE TITLE
Dropdrown inputs on Woo Admin screen not working

### ISSUE THREAD

**Issue by tigredanky** [woocommerce/woocommerce#14277]
### EXPLANATION OF THE ISSUE

Latest Woo Version 3.0.1 and WP 4.7.3. When going to WooCommerce  > Settings all dropdowns aren't showing up correctly. Not happening in other settings dashboard on the site (e.g. Settings > General, etc.)

### STEPS TO REPRODUCE THE ISSUE

Go to WooCommerce >  Settings. Dropdown normal styling shows up for a brief flash, then goes away, just showing the selected text input.

### SYSTEM STATUS

<details>

`
### WordPress Environment ###

Home URL: https://wildplayground.com
Site URL: https://wildplayground.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.10
PHP Version: 7.0.17
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.51.0
NSS/3.21.3 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

Custom 404 Pro: by Kunal Nagar – 2.0.3
Divi Builder Membership Restriction Add-On: by Alex Marko – 0.0.4
Divi Builder: by Elegant Themes – 2.0.3
Google Tag Manager for Wordpress: by Thomas Geiger – 1.5.1
Elegant Themes Updater: by Elegant Themes – 1.2
EventON: by AshanJay – 2.4.10
Formidable MailChimp: by Strategy11 – 2.01
Formidable Payment: by Strategy11 – 2.04.07
Formidable Forms: by Strategy11 – 2.03.04
Instagram Feed Pro Personal: by Smash Balloon – 2.4.1
Monarch Plugin: by Elegant Themes – 1.3.2
My Account Integration: by Tamas Herpay – 1.0.0
Per page head: by Erik von Asmuth – 1.4.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Tako Movable Comments: by Ren Aysha – 1.0.7
Ultimate Member: by Ultimate Member – 1.3.83
Ultimate Member - Social Activity: by Ultimate Member – 1.3.3
Ultimate Member - Private Messages: by Ultimate Member – 1.1.2
Ultimate Member - Online Users: by Ultimate Member – 1.1.0
Ultimate Member - User Tags: by Ultimate Member – 1.0.2
Ultimate Member - WooCommerce: by Ultimate Member – 1.0.11
Woo Stickers by Webline: by Weblineindia – 1.0.4
WooChimp: by RightPress – 2.2.3
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.0
WooCommerce Appointments: by BizzThemes – 2.6.2
WooCommerce Colors: by WooThemes – 1.0.6
WooCommerce PayPal Powered by Braintree Gateway: by WooThemes – 1.2.7
WooCommerce MailChimp: by Saint Systems – 2.0.20
WooCommerce - Memberships Content Shortcode: by Tamas Herpay – 1.0.0
WooCommerce Memberships: by SkyVerge – 1.8.1
WooCommerce Shipment Tracking: by WooCommerce – 1.6.4
WooCommerce Stamps.com API integration: by WooCommerce – 1.3.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.5
WooCommerce Smart Coupons: by StoreApps – 3.2.1
WooCommerce - Store Toolkit: by Visser Labs – 1.7.1
WooCommerce Subscriptions: by Prospress Inc. – 2.2.3
WooCommerce: by Automattic – 3.0.1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.6
WP Product Feed Manager: by Michel Jongbloed – 1.4.3
WP Smush: by WPMU DEV – 2.6.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: appointment (appointment)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### WC Pages ###

Shop base: #3393 - /market/
Cart: #2341 - /tipi/
Checkout: #2342 - /checkout/
My account: #9064 - /my-orders/

### Theme ###

Name: Wild Playground
Version: 1
Author URL: https://wildplayground.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.40
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-Wild-Playground-Child/woocommerce/cart/cart.php
Divi-Wild-Playground-Child/woocommerce/checkout/review-order.php
Divi-Wild-Playground-Child/woocommerce/myaccount/downloads.php
Divi-Wild-Playground-Child/woocommerce/myaccount/my-downloads.php

### Templates ###

thumbnail: 
medium: 
medium_large: 
large: 
et-pb-post-main-image: 
et-pb-post-main-image-fullwidth: 
et-pb-portfolio-image: 
et-pb-portfolio-module-image: 
et-pb-portfolio-image-single: 
et-pb-gallery-module-image-portrait: 
shop_thumbnail: 
shop_catalog: 
shop_single: 

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`

</details>

![screen shot 2017-04-11 at 12 36 56 pm](https://cloud.githubusercontent.com/assets/460065/24928225/975c9144-1eb6-11e7-8cc1-6f7b3df64f11.png)

**Comment by mikejolley** [comment]
Just need to clear your browser cache.

**Comment by tigredanky** [comment]
thanks, mike
