### ISSUE TITLE
State / County is a required field error message issue WooCommerce

### ISSUE THREAD

**Issue by nomisnibor** [woocommerce/woocommerce#14270]
My client from Lebanon get this error message when they try to pay online through woocommerce plug in.
On edit billing / shipping address page, the county field is hidden by default, and if I deselect the current country and select any other country it becomes visible but as soon as we choose Lebanon.

I have done the changes like here:
https://github.com/woocommerce/woocommerce/commit/bc779e5e2b0ff26a71bd16674c36d867188dd3f5

Unfortunatley, it does not work!

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/14272
