### ISSUE TITLE
Bring back "items" column in orders panel

### ISSUE THREAD

**Issue by keeneyemedia** [woocommerce/woocommerce#14275]
### EXPLANATION OF THE ISSUE
3.0 Removed "items" column in orders panel
https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#removed-items-column-in-orders-panel

Can we bring this back? By a filter or other hook?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14121
