### ISSUE TITLE
WC won't show translated strings

### ISSUE THREAD

**Issue by TadashiCZ** [woocommerce/woocommerce#14286]
### EXPLANATION OF THE ISSUE

I have Czech Wordpress site instalacekotlu.cz and the WooCommerce is showing English strings like "View cart" and "Proceed to checkout" and others even though they all are translated to Czech in the pot file.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.instalacekotlu.cz
Site URL: http://www.instalacekotlu.cz
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: cs_CZ

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_ssl/2.2.31 OpenSSL/1.0.1e-fips mod_fcgid/2.3.9
PHP Version: 7.0.17
PHP Post Max Size: 33 MB
PHP Time Limit: 90
PHP Max Input Vars: 10000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wpei_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: o Automattic – 3.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #42 - /e-shop/
Košík: #79 - /e-shop/kosik/
Pokladna: #80 - /e-shop/pokladna/
My account: #81 - /muj-ucet/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – Pokud upravujete WooCommerce
nebo rodičovskou šablonu
kterou jste nevytvořili
doporučujeme použít child šablonu. Viz. Jak vytvořit child šablonu

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/updating-translations-after-updates/
