### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by hardikgohil79** [woocommerce/woocommerce#14287]
### EXPLANATION OF THE ISSUE

I got PHP Warning:  Invalid argument supplied for foreach() in wp-content\plugins\woocommerce\includes\libraries\wp-background-process.php on line 299 when place order.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Should be fixed in https://github.com/woocommerce/woocommerce/pull/14268/files
