### ISSUE TITLE
CSS Issue with dates [Reports]

### ISSUE THREAD

**Issue by amjad** [woocommerce/woocommerce#14281]
Using latest Google Chrome / Safari with Latest WC and WP installation. Tested it on MacOS and Windows.

`https://www.xyz.com/wp-admin/admin.php?page=wc-reports`

Default view, no date selected. "dd" gets cut off.

![screen shot 2017-04-08 at 4 59 25 am](https://cloud.githubusercontent.com/assets/1428634/24934412/190476c4-1ee1-11e7-86b1-8c5d408b40a2.png)

This is what happens when you select a date and add it. 

![screen shot 2017-04-08 at 4 59 32 am](https://cloud.githubusercontent.com/assets/1428634/24934411/1903754e-1ee1-11e7-9683-807d4375684b.png)

![screen shot 2017-04-08 at 4 59 43 am](https://cloud.githubusercontent.com/assets/1428634/24934410/18f70534-1ee1-11e7-909e-c80cb405454e.png)

Works fine in Firefox.

**Comment by mikejolley** [comment]
testing safari, chrome, firefox on mac. 
![2017-04-12 at 12 45](https://cloud.githubusercontent.com/assets/90977/24956109/05f0246e-1f7e-11e7-9c35-95533cf6d784.png)

Input has no set width, just `size="11"` which > than the 10 chars needed.
