### ISSUE TITLE
Invalid argument supplied for foreach - class-wc-product-data-store-cpt.php - line 391

### ISSUE THREAD

**Issue by nishitlangaliya** [woocommerce/woocommerce#14284]
Hello,

I updated version and i found Warning for  Invalid argument supplied for foreach - class-wc-product-data-store-cpt.php - line 391

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
With an unmodified codebase I don't understand how such an issue would be possible.

```
	$meta_values = array_filter( (array) get_post_meta( $product->get_id(), '_downloadable_files', true ) );

		if ( $meta_values ) {
			$downloads = array();
			foreach ( $meta_values as $key => $value ) {
```

The meta is not only cast to an array, but ran through array_filter which returns an array. ` $meta_values` must be an array. To see the notice you have, ` $meta_values` would not be an array.

You should var_dump the meta values here and see what value it has when you view a product page (the same product page your saw the notice).

I suspect the code may have been changed directly. If you can send more information to this issue once you've looked into the above (also confirming the file has not been modified) I can assess. 

cc @claudiosanches
