### ISSUE TITLE
Issue with Toggles in WooCommerce Settings

### ISSUE THREAD

**Issue by tg2434** [woocommerce/woocommerce#14283]
Using latest Safari with Latest WC and WP installation. Tested it on MacOS.

Directly within WooCommerce Settings --> the toggles for dropdown not working properly. Tested disabling other plugins but it didnt no make any difference. 

<img src="http://i.imgur.com/Sjgub1g.png">
### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.engagingpapers.com/engagingpapersphase2
Site URL: https://www.engagingpapers.com/engagingpapersphase2
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Adminer: by Frank Bültge – 1.4.5
Advanced Code Editor: by BaInternet – 2.2.7
Advanced Custom Fields: by Elliot Condon – 4.4.11
ARG Multistep Checkout for WooCommerce: by ARG Themes – 2.7
BackupBuddy: by iThemes – 7.1.3.1
WooCommerce Order Status & Actions Manager: by Actuality Extensions – 1.7.1
Connects - Mailchimp Addon: by Brainstorm Force – 2.0.3.2
Contact Form 7: by Takayuki Miyoshi – 4.7
Duplicate Post: by Enrico Battocchi – 3.2
My Custom Code: by  –
Slider Revolution: by ThemePunch – 5.2.6
Say What?: by Lee Willis – 1.9.0
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.4.9
Uncode Core: by Undsgn – 1.2.2
Uncode Dave's WordPress Live Search (4.4.1): by Dave Ross – 1.0
Uncode Visual Composer: by Michael M - WPBakery.com – 4.12.1
Use Any Font: by Dinesh Karki – 4.7.2
Visual Composer Clipboard: by bitorbit – 3.24
VC Particles Background: by Boom-Apps – 1.2
WooCommerce Dynamic Pricing & Discounts: by RightPress – 1.0.18
WooCommerce Deposits: by Automattic – 1.2.1
WooCommerce Authorize.Net AIM Gateway: by SkyVerge – 3.11.0
WooCommerce Advanced Product Quantities: by WP BackOffice – 2.1.9
WooCommerce TM Extra Product Options: by themecomplete – 4.5.1
WooCommerce: by Automattic – 3.0.1
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.3.6
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WPide: by Simon @ WPsites – 2.4.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: Uncode Child
Version: 1.0.0
Author URL: http://www.undsgn.com
Child Theme: ✔
Parent Theme Name: Uncode
Parent Theme Version: 1.4.2
Parent Theme Author URL: http://www.undsgn.com
WooCommerce Support: ✔

### Templates ###

Overrides: uncode/woocommerce/archive-product.php
uncode/woocommerce/cart/mini-cart.php
uncode/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
uncode/woocommerce/content-product_cat.php
uncode/woocommerce/content-single-product.php
uncode/woocommerce/loop/loop-end.php
uncode/woocommerce/loop/loop-start.php
uncode/woocommerce/loop/pagination.php
uncode/woocommerce/myaccount/my-account.php
uncode/woocommerce/myaccount/navigation.php
uncode/woocommerce/notices/error.php
uncode/woocommerce/notices/notice.php
uncode/woocommerce/notices/success.php
uncode/woocommerce/order/order-details-customer.php
uncode/woocommerce/order/order-details.php
uncode/woocommerce/product-searchform.php
uncode/woocommerce/single-product/add-to-cart/external.php
uncode/woocommerce/single-product/add-to-cart/grouped.php
uncode-child/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
uncode-child/woocommerce/single-product/add-to-cart/variable.php
uncode-child/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
uncode/woocommerce/single-product/price.php
uncode-child/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.0.0
uncode/woocommerce/single-product/product-thumbnails.php
uncode/woocommerce/single-product/related.php
uncode/woocommerce/single-product/review.php
uncode/woocommerce/single-product/share.php
uncode/woocommerce/single-product/tabs/additional-information.php
uncode/woocommerce/single-product/tabs/description.php
uncode/woocommerce/single-product/tabs/tabs.php
uncode/woocommerce/single-product/title.php
uncode/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
uncode/woocommerce/single-product-reviews.php
uncode/woocommerce/single-product.php
uncode/woocommerce/taxonomy-product_cat.php

Outdated Templates: ❌Learn how to update

### Authorize.Net AIM ###

Environment: Production
Debug Mode: Off
`
</details>

**Comment by claudiosanches** [comment]
Please clear your browse cache.
