### ISSUE TITLE
WC-specific rel attributes on Product Categories and Product Tags

### ISSUE THREAD

**Issue by ZXCVLuke** [woocommerce/woocommerce#14282]
Currently all product taxonomies output;
`<a href=".../product-category/category" rel="tag">Category</a>`

I would like to request that Product Categories output; 
`<a href=".../product-category/category" rel="product category">Category</a>`

and Product Tags output;
`<a href=".../product-category/category" rel="product tag">Category</a>`

I use `a[rel~="category"]` and a[rel~="tag"] for styling and would like to apply different styling to WC product categories and tags than to post categories and tags.

**Comment by claudiosanches** [comment]
We use https://developer.wordpress.org/reference/functions/get_the_term_list/ to list the categories and tags.
So you can do the same as you should be do to change any other taxonomy link in WordPress.

**Comment by ZXCVLuke** [comment]
Yes, I have seen that this is the function used. Thanks Claudio. Do you not agree though that it would be better semantically for WC to distinguish between product taxonomy and post taxonomy with the rel attribute?

**Comment by claudiosanches** [comment]
@ZXCVLuke not sure even it's valid, I already saw a lot of problems with bad `rel` values, and can impact bad to SEO too, more than just CSS styles. So it's not an easy decision.
Anyway good luck.

**Comment by ZXCVLuke** [comment]
Sorry, you are totally correct. I should have checked the HTML5 spec first. Perhaps WP should not be using 'category', as it is not listed in the spec...
Thanks again for the response.
