### ISSUE TITLE
Email is not working 

### ISSUE THREAD

**Issue by rajmohanvy** [woocommerce/woocommerce#14296]
Hi team,

I have web site with woocommerce and Pinpoint Booking System PRO, after booking the email not received. Also tried deactivate "Pinpoint Booking System" plugins, Test with sample product, but still not yet received the order emails. Normal other email(contact form and test emails) are received.    

PHP Version 5.4.16 
Wordpress Version : 4.5.7
Woocommerce Version : 3.0.1
WP-Mail-SMTP 0.9.5
Pinpoint Booking System PRO 2.4.9

**Comment by mikejolley** [comment]
Search before logging new issues please.

https://wordpress.org/support/topic/3-0-email-sending-issues/

**Comment by a1ur3l** [comment]
Hello
i still face this issue on 3.0.2 version even without wp-mail-smtp plugin.
