### ISSUE TITLE
shipping method title is not saved to the database

### ISSUE THREAD

**Issue by kseyedmehdi** [woocommerce/woocommerce#14290]
### EXPLANATION OF THE ISSUE

shipping method title is not saved to the database.
when updating the shipping method title using the admin frontend the shipping method title is not saved to the database.

Also when updating the shipping object using set_method_title() combined with save() using code it does not work.

### STEPS TO REPRODUCE THE ISSUE

1. create an order containing a shipping method
2. set the payment status to pending
3. try to update the shipping method title
4. you will see that you changes are not saved after submitting your changes.

### SYSTEM STATUS

<details>

`
### WordPress Environment ###

Home URL: 
Site URL: 
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE

### Server Environment ###

Server Info: nginx/1.6.0
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: So aktualisierst Du Deine PHP-Version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.37 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wkek_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Admin Columns Pro: von AdminColumns.com – 4.0.2
Advanced Custom Fields: von Elliot Condon – 4.4.11
AjaxFlow: von Andreas Ek – 1.1
Admin Columns - Advanced Custom Fields add-on: von Codepress – 2.0.1
Admin Columns - WooCommerce add-on: von Codepress – 2.0
Contact Form 7: von Takayuki Miyoshi – 4.7
Enhanced E-commerce for Woocommerce store: von Tatvic – 1.0.19
Multisafepay: von Multisafepay – 2.2.5
Radio Buttons for Taxonomies: von Kathy Darling – 1.7.7
Say What?: von Lee Willis – 1.9.0
WooCommerce MailChimp: von Saint Systems – 2.0.20
Trustbadge Reviews for WooCommerce: von Vendidero – 2.1.0
WooCommerce: von Automattic – 3.0.1
WooThemes Helper: von WooThemes – 1.5.9 – Netzwerk aktiviert
WP Crontrol: von John Blackbourn & contributors – 1.5
WP Maintenance Mode: von Designmodo – 2.0.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: /
Warenkorb: #34862 - /
Kasse: #6 - /checkout/
My account: #7 - /mein-konto/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
We have a fix coming in 3.0.2 for this.
