### ISSUE TITLE
Add error message if quantity field is blank when click on add to cart button from product page

### ISSUE THREAD

**Issue by jitenmultidots** [woocommerce/woocommerce#14299]
### EXPLANATION OF THE ISSUE

When quantity field is empty and if we click on add to cart button from the product page then product with successfully added to the cart instead of showing empty quantity field error. So, there is need to be add some error message for empty quantity field and prevent product from adding to the cart.

![empty-quantity-field](https://cloud.githubusercontent.com/assets/24750334/24961083/5a3e5e32-1fb5-11e7-8892-e19a4cc247fc.png)

### STEPS TO REPRODUCE THE ISSUE

1. Go to the product detail page.
2. Remove the value from the quantity field.
3. Click on add to cart button.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://localhost/woocommerce_latest
Site URL: http://localhost/woocommerce_latest
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.9 (Win64) PHP/5.5.12
PHP Version: ❌ 5.5.12 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 3 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.36.0
OpenSSL/1.0.1g

SUHOSIN Installed: –
MySQL Version: 5.6.17
Max Upload Size: 3 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 3.0.1
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
It defaults to 1 if left black. I don't see any benefit to stopping someone adding to cart if they want to. Why add extra roadblocks?
