### ISSUE TITLE
New version WC3 order not in shopping cart

### ISSUE THREAD

**Issue by janmensink** [woocommerce/woocommerce#14301]
After upgrade to WC 3 orders don't come in the shopping cart. I have tried other Themes but by all the same problem. I use the newest version of WP.

**Comment by mikejolley** [comment]
You need to be clearer here. Issue does not make much sense and has no context.

**Comment by mikejolley** [comment]
Please provide the details on the new issue form or we cannot assist.

**Comment by janmensink** [comment]
I find it a bit strange, what information do you need? New version 3 WooCommerce, Wordpress 4.7.3 after update Woocommerce to 3.0  an order is not placed in the shopping cart.
Jan

**Comment by claudiosanches** [comment]
@janmensink have you tested with other theme? Have you tried to deactivate other plugins? Have you installed just WordPress 4.7.3 and WooCommerce 3.0.1 and tested? Have you enabled WordPress debug and check for errors?

**Comment by janmensink** [comment]
Thank you Claudio, that are good suggestions. I was succesfull with deactivating of the Uni CPO - WooCommerce Options and Price Calculation Formulas plugin. Remarkeble i reactivated the plugin and no problems. 
Thanks, Jan

**Comment by claudiosanches** [comment]
Good to hear that it's working for you now.
