### ISSUE TITLE
Images Not Displaying

### ISSUE THREAD

**Issue by catrymer** [woocommerce/woocommerce#14303]
This morning I've seen two different tickets from users reporting that their images stopped displaying. You can see them at:

http://koosvanderbeek.nl/superdeals/
https://theproteinchef.co/product/protein-chef-baking-protein/

The sites are using different themes and are owned by different users with different plugin configurations. The images are actually loading into the page, you can click them in the browser to view just the image and it displays as expected, but they aren't visible in the WooCommerce page. 

On investigation of the page source there is an opacity: 0 setting on 'woocommerce-product-gallery woocommerce-product-gallery--with-images woocommerce-product-gallery--columns-4 images' . 

It appears @mikejolley made a change two weeks ago to the way product galleries fade-in in https://github.com/woocommerce/woocommerce/commit/62bd505bdae4c0fe704125fe3558dfab263a60a6 . Possibly this issue was introduced then?

**Comment by catrymer** [comment]
Tickets Reporting this issue:

https://woothemes.zendesk.com/agent/tickets/556486
https://woothemes.zendesk.com/agent/tickets/559364

**Comment by claudiulodro** [comment]
Replied in zendesk.

**Comment by diymat** [comment]
Have exactly the same problem. No pictures in the product gallery
