### ISSUE TITLE
Saving an item in a different object than "WC_Order_Item_Product". Possible?

### ISSUE THREAD

**Issue by pnpetroff** [woocommerce/woocommerce#14302]
As I am creating sellable custom post type via WooCommerce I stumbled on the following problem.

When a post is ordered, it is a `WC_Order_Item_Product` object. The problem with that class is that there is a check in the `set_product_id` method if the post type is `product`.

I see that the `create_order_line_items` method of the `WC_Checkout` class is responsible for the object saving. Is it possible to override the method so that I can save it in a custom `WC_Order_Item_Ticket` object?

**Comment by mikejolley** [comment]
Is the woocommerce_checkout_create_order_line_item action viable to swap it? It gives you a reference to $item.

**Comment by pe6o** [comment]
I tried hooking, using the same code but swapping the object:

```php
function _action_my_change_wc_order_item_meta( $item, $cart_item_key, $values, $order) {
	$product                    = $values['data'];
	$item                       = new WC_Order_Item_Ticket();
	$item->legacy_values        = $values; // @deprecated For legacy actions.
	$item->legacy_cart_item_key = $cart_item_key; // @deprecated For legacy actions.
	$item->set_props( array(
		'quantity'     => $values['quantity'],
		'variation'    => $values['variation'],
		'subtotal'     => $values['line_subtotal'],
		'total'        => $values['line_total'],
		'subtotal_tax' => $values['line_subtotal_tax'],
		'total_tax'    => $values['line_tax'],
		'taxes'        => $values['line_tax_data'],
	) );
	if ( $product ) {
		$item->set_props( array(
			'name'         => $product->get_name(),
			'tax_class'    => $product->get_tax_class(),
			'product_id'   => $product->is_type( 'variation' ) ? $product->get_parent_id() : $product->get_id(),
			'variation_id' => $product->is_type( 'variation' ) ? $product->get_id() : 0,
		) );
	}
	$item->set_backorder_meta();
}

add_action( 'woocommerce_checkout_create_order_line_item', '_action_my_change_wc_order_item_meta', 10, 4 );
```

It doesn't seem to change the $item.
```php
var_dump($item);
do_action( 'woocommerce_checkout_create_order_line_item', $item, $cart_item_key, $values, $order );
var_dump($item);
```
`$item` is still `WC_Order_Item_Ticket`.

**Comment by pe6o** [comment]
Is it possible to return the `$item` in an action?

I tried hooking, using the same code but swapping the object:

```php
function _action_my_change_wc_order_item_meta( $item, $cart_item_key, $values, $order) {
	$product                    = $values['data'];
	$item                       = new WC_Order_Item_Ticket();
	$item->legacy_values        = $values; // @deprecated For legacy actions.
	$item->legacy_cart_item_key = $cart_item_key; // @deprecated For legacy actions.
	$item->set_props( array(
		'quantity'     => $values['quantity'],
		'variation'    => $values['variation'],
		'subtotal'     => $values['line_subtotal'],
		'total'        => $values['line_total'],
		'subtotal_tax' => $values['line_subtotal_tax'],
		'total_tax'    => $values['line_tax'],
		'taxes'        => $values['line_tax_data'],
	) );
	if ( $product ) {
		$item->set_props( array(
			'name'         => $product->get_name(),
			'tax_class'    => $product->get_tax_class(),
			'product_id'   => $product->is_type( 'variation' ) ? $product->get_parent_id() : $product->get_id(),
			'variation_id' => $product->is_type( 'variation' ) ? $product->get_id() : 0,
		) );
	}
	$item->set_backorder_meta();
}

add_action( 'woocommerce_checkout_create_order_line_item', '_action_my_change_wc_order_item_meta', 10, 4 );
```

It doesn't seem to change the `$item`.
```php
///file: class-wc-checkout.php -> create_order_line_items
var_dump($item);
do_action( 'woocommerce_checkout_create_order_line_item', $item, $cart_item_key, $values, $order );
var_dump($item);
```
`$item` is still `WC_Order_Item_Ticket`.

**Comment by mikejolley** [comment]
> $item is still WC_Order_Item_Ticket.

Did you mean product?

**Comment by pe6o** [comment]
Ah, yes, sorry... It's still `WC_Order_Item_Product`

**Comment by mikejolley** [comment]
Hmm so ideally you'd have a filter to do something before that code runs? Want to submit a PR?

**Comment by pe6o** [comment]
Unfortunately, I never did any PRs until now and I'm afraid I would mess something up... :/


This is a snippet the object in the Checkout page:
```
WC_Order_Item_Product
(
   ...
   [*:order] => null
    [*:cache_group] => 'order-items'
    [*:meta_type] => 'order_item'
    [*:object_type] => 'order_item'
    [*:id] => 90
    [*:changes] => array()
   ...
)
```
Where and how in WooCommerce the ** [*:id]** is set? This 90 is some very random number and is neither the order ID nor the Ticket ID.

Is there a method that I can save the actual ID with the `save_post` so I can send it to the Checkout page and use it to display all kind of information about the ticket?

`$item->get_name()` returns the correct ticket title though.

**Comment by mikejolley** [comment]
90 is the item id in the order_items table.

**Comment by pe6o** [comment]
Ah, alright.

So is there some way that I can add custom meta (the ID) on the item and retrieve it later in the Checkout page?

**Comment by mikejolley** [comment]
Yes, you can use the add meta functions on line items. But I'm not really sure what you're doing now :) Look at the WC_Data class to see what type of thing you can do.

**Comment by pe6o** [comment]
Okay, this will be long. The way I approached this is the following:

I created class `WC_Ticket_Simple`, which is the same as `WC_Product_Simple` with the only difference that it extends my other custom class `WC_Ticket`

`WC_Ticket`'s only difference with `WC_Product` is that it loads my custom data store (e.g. replaced `WC_Data_Store::load( 'product-' . $this->get_type() )` with `WC_Data_Store::load( 'ticketdata' )`.

Added the custom data store in *functions.php* with the following filter:
```php
function _filter_my_wc_set_ticket_data_store( $stores ) {
	$stores['ticketdata'] = 'WC_Ticket_Data_Store_CPT';
	
	return $stores;
}

add_filter( 'woocommerce_data_stores', '_filter_my_wc_set_ticket_data_store' );
```

`WC_Ticket_Data_Store_CPT`'s only difference with the original `WC_Product_Data_Store_CPT`  is that I removed the `product` check from the `read()` method.

In my *functions.php* I added the following function so I can change the product class (hope this is the right way so) or otherwise the Add to Cart button won't work:
```php
function _filter_my_woocommerce_product_class( $classname, $product_type, $post_type, $product_id ) { 

    if ( get_post_type($product_id) == 'ticket' ) {
    	$classname = 'WC_Ticket_Simple';
    }

    return $classname; 
}; 
         
add_filter( 'woocommerce_product_class', '_filter_my_woocommerce_product_class', 10, 4 ); 
```

We will need a pricing so I add a hook to write the price from the ACF field that I use in my custom post type:

```php
function _action_my_save_ticket_woocommerce_meta($post_id) {

	$ticket = new WC_Ticket_Simple($post_id);

	if ( get_field('ticket_price', $post_id) ) {
		$ticket->set_regular_price($price);
		$ticket->set_price($price);
	}

	$ticket->save();
}

add_action('acf/save_post', '_action_my_save_ticket_woocommerce_meta', 99);
```

And now it is possible to add a custom post type using the following Add to Cart button:
```html
<div class="woocommerce">
	<form class="cart" method="post" enctype="multipart/form-data">
		<div class="quantity hidden">
			<input type="hidden" class="qty" name="quantity" value="1">
		</div>

		<button type="submit" name="add-to-cart" value="<?php echo $post->ID ?>" class="single_add_to_cart_button button alt"><?php esc_html_e('Add to cart', 'themename') ?></button>

	</form>
</div>
````

Now everything is good until the Checkout page with the Order Details.

As I have some ACF fields on my custom post type, I want to display some of their values in the checkout page. So I must make a call to get the value of the post meta using the post id like this:
```
get_field('ticket_description', $post_id);
```
As said above I can't save the ID as a product ID because `WC_Checkout ->create_order_line_items()`  does that only if the post type is `product`.

To get the ID I used the `woocommerce_checkout_create_order_line_item` action hook to insert it in the `WC_Order_Item_Product` object. 

```php
function _action_my_change_wc_order_item_meta( $item, $cart_item_key, $values, $order) {
	$item->update_meta_data('ticket_id', $values['product_id']);
}

add_action( 'woocommerce_checkout_create_order_line_item', '_action_my_change_wc_order_item_meta', 10, 4 );
```

And now I can use it in the *order-details.php* template like so:
```php
foreach ( $order->get_items() as $item_id => $item ) {
	$ticket_id = $item->get_meta('ticket_id ');
}
```

Of course, a little bit below in this template, the problem stays. 
```php
$product = apply_filters( 'woocommerce_order_item_product', $item->get_product(), $item );
```
This returns nothing because we just don't have a real product with its own ID.

So I guess until there is a filter for the $item object in `WC_Checkout ->create_order_line_items()` there is no proper way to create custom post type that uses WC 3.0?

**Comment by mikejolley** [comment]
Is we added a filter there (or you added one temporarily) are there any other problems or errors which would need resolving? Admin order views work? Emails? View order on frontend?

**Comment by mikejolley** [comment]
Just following up here - any comments? If so we can get some filters in place for 3.1.

**Comment by pe6o** [comment]
Sorry for the delay, I will look into it in the next 3 days.

**Comment by pnpetroff** [comment]
Currently working on this...

**Comment by pnpetroff** [comment]
Okay here are my observations.

I created a pull request - https://github.com/woocommerce/woocommerce/pull/14678

`WC_Order_Factory -> get_order_item` never goes to its default case and thus never applies the `woocommerce_get_order_item_classname` filter because  the operation bails before that in `WC_Abstract_Order -> add_item`(`WC_Abstract_Order -> get_items_key` returns nothng on a custom classname).

The only thing that I'm concerned is if the change in `WC_Abstract_Order -> get_items_key` is correct.

**Comment by mikejolley** [comment]
Let's move the discussion to https://github.com/woocommerce/woocommerce/pull/14678#pullrequestreview-34565840 and work there.
