### ISSUE TITLE
Can't edit pages after update to 301

### ISSUE THREAD

**Issue by vernonwebsites** [woocommerce/woocommerce#14307]
### EXPLANATION OF THE ISSUE

Upgraded woocommerce to 3.0.1 and then could not edit pages on the site. (Like front page, contact page etc) Noticed this with Vantage Pro and Divi themes. 

### STEPS TO REPRODUCE THE ISSUE
Upgraded woocommerce to 3.0.1 and then could not edit pages on the site. (Like front page, contact page etc) Noticed this with Vantage Pro and Divi themes. 

### SYSTEM STATUS

<details>
```
Already restored from backups.
```
</details>

**Comment by mikejolley** [comment]
No error messages? No status report showing extensions?

Really, we cannot work with the above - there is not enough information, and since you've already restored a backup troubleshooting is now impossible.

Setup on a staging site if you can and replicate the issue, then we can talk.

**Comment by vernonwebsites** [comment]
Sorry, I was just trying to help.

I realize I didn’t have enough info... and again apologize, but thought 
it was better to report this issue than to not mention it at all. Next 
time I won't bother.

Have a good day.

Mike Bjerstedt
Internet & Technology Specialist
Websites:  www.vernonwebsites.com <http://www.VernonWebsites.com> - 
www.affordablecomputertech.com <http://www.affordablecomputertech.com>
<http://www.MikesMegabits.comEmail>Email 
<http://www.MikesMegabits.comEmail>:mike@vernonwebsites.com
Phone: 250.308.7545 (Or SMS Text)
Skype: mikesmegabits Twitter: @mikesmegabits - @vernonwebsites - 
@affdablecomptec
Facebook:  Affordable Computer Tech, Vernon Websites




------ Original Message ------

**Comment by mikejolley** [comment]
Thats fine to report, but we need information as requested on the form e.g. system status report. Without this there is nothing we can do from our side - especially if it's a problem specific to your site.

Again, if you can get a test install up and replicate the problem we can look into this.

**Comment by vernonwebsites** [comment]
Thanks for your reply...

I have actually just created a test sub-domain and its sitting at its 
pre-update level right now. Everything is working...

Here is the system report with everything working ok... (I will also 
paste the system report AFTER doing the upgrade below this...)

`
### WordPress Environment ###

Home URL: http://test.okanaganfeldenkrais.com
Site URL: http://test.okanaganfeldenkrais.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - 
some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
:
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (16) ###

Gravity Forms: by rocketgenius – 2.2.1.2
Canada Post WooCommerce Shipping with Print Label: by WooForce – 1.6.2
Custom Facebook Feed: by Smash Balloon – 2.4.5
Social Media Flying Icons | Floating Social Media Icon: by Acurax – 
4.2.4
Gravity Forms Constant Contact Add-On: by Katz Web Services
Inc. – 2.2.2

Gravity Forms PayPal Standard Add-On: by rocketgenius – 2.8
Gravity Forms Signature Add-On: by Rocketgenius – 3.3
InfiniteWP - Client: by Revmakx – 1.6.3.2
Jetpack by WordPress.com: by Automattic – 4.8.2
Meta Slider: by Matcha Labs – 3.5
SEO Ultimate: by SEO Design Solutions – 7.6.5.9
Page Builder by SiteOrigin: by SiteOrigin – 2.4.25
SiteOrigin Widgets Bundle: by SiteOrigin – 1.8.2
Instagram Feed WD: by WebDorado – 1.1.26
WooCommerce: by WooThemes – 2.6.14
WP-SpamShield: by Scott Allen – 1.9.9.9.5

### Settings ###

Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #431 - /shop/
Cart: #432 - /cart/
Checkout: #433 - /checkout/
My Account: #434 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### Theme ###

Name: Divi Child Theme
Version: 2.6
Author URL: http://www.vernonwebsites.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.18
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

-------------------------------------------------------------------------------------------------------------------------

Here is the report AFTER the update to woocommerce. The editing of pages 
now is no longer working...

If you wish, here is a login to the test platform for you to check into 
it further.

u: mikejolley  p:  aU6y(F1JQNIlvIHPEFhp&$Pu

http://test.okanaganfeldenkrais.com/wp-admin


`
### WordPress Environment ###

Home URL: http://test.okanaganfeldenkrais.com
Site URL: http://test.okanaganfeldenkrais.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - 
some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more 
about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (16) ###

Gravity Forms: by rocketgenius – 2.2.1.2
Canada Post WooCommerce Shipping with Print Label: by WooForce – 1.6.2
Custom Facebook Feed: by Smash Balloon – 2.4.5
Social Media Flying Icons | Floating Social Media Icon: by Acurax – 
4.2.4
Gravity Forms Constant Contact Add-On: by Katz Web Services
Inc. – 2.2.2

Gravity Forms PayPal Standard Add-On: by rocketgenius – 2.8
Gravity Forms Signature Add-On: by Rocketgenius – 3.3
InfiniteWP - Client: by Revmakx – 1.6.3.2
Jetpack by WordPress.com: by Automattic – 4.8.2
Meta Slider: by Matcha Labs – 3.5
SEO Ultimate: by SEO Design Solutions – 7.6.5.9
Page Builder by SiteOrigin: by SiteOrigin – 2.4.25
SiteOrigin Widgets Bundle: by SiteOrigin – 1.8.2
Instagram Feed WD: by WebDorado – 1.1.26
WooCommerce: by Automattic – 3.0.1
WP-SpamShield: by Scott Allen – 1.9.9.9.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #431 - /shop/
Cart: #432 - /cart/
Checkout: #433 - /checkout/
My account: #434 - /my-account/

### Theme ###

Name: Divi Child Theme
Version: 2.6
Author URL: http://www.vernonwebsites.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.18
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`


Mike Bjerstedt
Internet & Technology Specialist
Websites:  www.vernonwebsites.com <http://www.VernonWebsites.com> - 
www.affordablecomputertech.com <http://www.affordablecomputertech.com>
<http://www.MikesMegabits.comEmail>Email 
<http://www.MikesMegabits.comEmail>:mike@vernonwebsites.com
Phone: 250.308.7545 (Or SMS Text)
Skype: mikesmegabits Twitter: @mikesmegabits - @vernonwebsites - 
@affdablecomptec
Facebook:  Affordable Computer Tech, Vernon Websites




------ Original Message ------
