### ISSUE TITLE
Bug - Low Stock/Out of Stock report returns error

### ISSUE THREAD

**Issue by bborden51** [woocommerce/woocommerce#14312]
Dashboard ---> Woocommerce Status-->Click on either Out of Stock or Low Stock returns--->

Fatal error: Call to a member function get_sku() on boolean in /home/content/p3pnexwpnas03_data03/48/2428948/html/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-stock.php on line 86

![capture](https://cloud.githubusercontent.com/assets/15631464/24970293/a40767ae-1f68-11e7-8ca6-ce4e246b712c.JPG)

**Comment by mikejolley** [comment]
We have a fix in master for this (3.0.2) already. You can also delete orphan variations on the system status > tools section to possibly resolve.
