### ISSUE TITLE
No Grouping for Simple and Affiliate Procuts

### ISSUE THREAD

**Issue by Reverse-Flashed** [woocommerce/woocommerce#14311]
### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Done at the grouped product level now. Edit the grouped product.

**Comment by Reverse-Flashed** [comment]
It would be great if you could update your videos accordingly (i.e. https://www.youtube.com/watch?v=sDydnr3AOdo)

**Comment by mikejolley** [comment]
@californiakat @ryanr14 ^

**Comment by Reverse-Flashed** [comment]
Thanks a lot for your fast answers!

**Comment by ryanr14** [comment]
Hi @Reverse-Flashed!

Sorry you spotted that inconsistency, I hadn't yet updated all of our videos on YouTube just yet. I'm in the process now of uploading our updated videos though!

**Comment by Reverse-Flashed** [comment]
Thanks @ryanr14!
