### ISSUE TITLE
Woocommerce +Woocommerce  API Manager

### ISSUE THREAD

**Issue by jayyogvihalkrupa** [woocommerce/woocommerce#14313]
Hello Sir,
Please help me urgent.
I have integrated  Woocommerce +Woocommerce  API Manager.
https://docs.woocommerce.com/wp-content/uploads/2013/09/api-manager-settings-tools.png

Have set and rebuild database as per instruction.

Now old cutsomer don't have seen API Key and API Download file after  integrated Woocommerce  API Manager.

**Is there any way to rebuild/recreate woocommerce_downloadable_product_permissions 
Please help.**

http://prnt.sc/evo6h1

Regards
Nilesh

**Comment by mikejolley** [comment]
if that option/button is not working right, please file a ticket on https://woocommerce.com/my-account/ so the dev can look into this and fix if needed. The tool has a big disclaimer so hopefully you took a backup also just in case you need to restore. Thanks.
