### ISSUE TITLE
When duplicating products after WC 3.0.0/1 upgrade, the brand and metadata is not copied

### ISSUE THREAD

**Issue by heints** [woocommerce/woocommerce#14318]
### EXPLANATION OF THE ISSUE

After upgrade to WC 3.0.0 and 3.0.1 there seems to be an issue with the duplication of

### STEPS TO REPRODUCE THE ISSUE

Products -> select product and choose duplicate.

The new product does not include the metadata, brands etc. info from the original product.
This was working for WC version <3.0.x

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.hobukeskus.ee
Site URL: https://www.hobukeskus.ee
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: et

### Server Environment ###

Server Info: Apache / ZoneOS
PHP Version: 5.6.30
PHP Post Max Size: 2 GB
PHP Time Limit: 30
PHP Max Input Vars: 20000
cURL Version: 7.51.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: m6el_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

Google XML Sitemaps: - Arne Brachhold – 4.0.8
Easy HTTPS (SSL) Redirection: - Tips and Tricks HQ – 1.6
Joomla2WP Migrated Users Authentication Plugin: - lucky62 – 1.0.1
Limit Login Attempts: - Johan Eenfeldt – 1.7.1
PRyC WP/WooCommerce: Edit all orders: - PRyC – 1.0.3
Slider Revolution: - ThemePunch – 5.4.1
Mobile Redirect: - Ozette Plugins – 1.7
SSL Insecure Content Fixer: - WebAware – 2.2.3
User Login Log: - weblizar – 2.2.2
W3 Total Cache: - Frederick Townes – 0.9.5.2
Woocomerce Brands Pro: - Proword – 4.2.0
WooCommerce Colors: - WooThemes – 1.0.6
Woocommerce E-Abi Postoffice plugin: - Matis Halmann
Aktsiamaailm LLC – 1.23

WooCommerce Google Analytics Integration: - WooThemes – 1.4.0
WooCommerce Liisi gateway: - Veebipoed and Liisi – 0.1.0
Woocommerce SEB bank Estonia: - Matis Halmann
Aktsiamaailm LLC – 1.5

Woocommerce Swedbank Estonia: - Matis Halmann
Aktsiamaailm LLC – 1.5

WooCommerce PDF Invoice: - RightPress – 3.1.4
WooCommerce Product Filter: - Farhad Ahmadi – 2.3.4
WOOF - WooCommerce Products Filter: - realmag777 – 1.1.6.1
WooCommerce Sequential Order Numbers Pro:  WooThemes 1.11.0
E-Abi DPD Shipping method plugin: - Matis Halmann
Aktsiamaailm LLC – 1.0

E-Abi Woocommerce Omniva Autosend method plugin: - Matis Halmann
Aktsiamaailm LLC – 1.1

E-Abi Omniva Shipping method plugin: - Matis Halmann
Aktsiamaailm LLC – 1.3

Woocommerce Omniva Estonia: - Matis Halmann
Aktsiamaailm LLC – 1.4

Woocommerce Omniva Postkontor Estonia: - Matis Halmann
Aktsiamaailm LLC – 1.3

E-Abi Woocommerce Itella Shipping method plugin: - Matis Halmann
Aktsiamaailm LLC – 1.13

WooCommerce Order Status & Actions Manager: - Actuality Extensions – 2.1.4
WooCommerce: - Automattic – 3.0.1
WP Robots Txt: - Christopher Davis – 1.1
WP Smush: - WPMU DEV – 2.6.2
YITH Essential Kit for WooCommerce #1: - YIThemes – 1.4.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Poe alusaadress: #7 - /shop/
Ostukorv: #8 - /cart/
Kassa: #9 - /checkout/
Minu konto: #10 - /my-account/

### Theme ###

Name: Tyrion
Version: 1.7.2
Author URL: http://yithemes.com/
Child Theme: ❌ – Kui muudad WooCommerce-i ülemteemas
mida sina isiklikult ei ole ehitanud
soovitame kasutada alamteemat. Vaata: kuidas luua alamteema

WooCommerce Support: ✔

### Templates ###

Overrides: tyrion/woocommerce/archive-product.php
tyrion/woocommerce/cart/cart-empty.php
tyrion/woocommerce/cart/cart-shipping.php
tyrion/woocommerce/cart/cart-totals.php
tyrion/woocommerce/cart/cart.php
tyrion/woocommerce/cart/mini-cart.php
tyrion/woocommerce/checkout/form-checkout.php
tyrion/woocommerce/checkout/form-login.php
tyrion/woocommerce/checkout/form-shipping.php
tyrion/woocommerce/checkout/payment.php
tyrion/woocommerce/checkout/review-order.php
tyrion/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
tyrion/woocommerce/content-product_cat.php
tyrion/woocommerce/content-single-product.php
tyrion/woocommerce/emails/admin-new-order.php version 2.0.0 is out of date. The core version is 2.5.0
tyrion/woocommerce/emails/email-footer.php version 2.0.0 is out of date. The core version is 2.3.0
tyrion/woocommerce/emails/email-header.php version 2.3.0 is out of date. The core version is 2.4.0
tyrion/woocommerce/global/breadcrumb.php
tyrion/woocommerce/global/sidebar.php
tyrion/woocommerce/global/wrapper-end.php
tyrion/woocommerce/global/wrapper-start.php
tyrion/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0
tyrion/woocommerce/loop/loop-end.php
tyrion/woocommerce/loop/loop-start.php
tyrion/woocommerce/loop/pagination.php
tyrion/woocommerce/loop/sale-flash.php
tyrion/woocommerce/single-product/add-to-cart/external.php
tyrion/woocommerce/single-product/add-to-cart/grouped.php
tyrion/woocommerce/single-product/add-to-cart/simple.php
tyrion/woocommerce/single-product/meta.php
tyrion/woocommerce/single-product/price.php
tyrion/woocommerce/single-product/product-attributes.php
tyrion/woocommerce/single-product/product-image.php
tyrion/woocommerce/single-product/product-thumbnails.php
tyrion/woocommerce/single-product/rating.php
tyrion/woocommerce/single-product/related.php
tyrion/woocommerce/single-product/sale-flash.php
tyrion/woocommerce/single-product/short-description.php
tyrion/woocommerce/single-product/tabs/tabs.php
tyrion/woocommerce/single-product/title.php
tyrion/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
tyrion/woocommerce/single-product-reviews.php
tyrion/woocommerce/single-product.php

</details>

**Comment by mikejolley** [comment]
3.0.2 restores meta duplication.

**Comment by mikejolley** [comment]
Logged brand support in the brands repo since it's a custom taxonomy https://github.com/woocommerce/woocommerce-brands/issues/78
