### ISSUE TITLE
Images with long captions fail to advance in the viewer

### ISSUE THREAD

**Issue by GlazerGallery** [woocommerce/woocommerce#14323]
### EXPLANATION OF THE ISSUE

Images with long caption will not advance when either of the arrows are clicked. Instead, clicking the arrow sends you pack to the product page. This does not seem to happen with very short captions though. here's an example of a page with this problem, attached. 
![long caption example](https://cloud.githubusercontent.com/assets/26978001/24980958/72d3e302-1fa8-11e7-99fc-538d7f0cea6f.jpg)

### STEPS TO REPRODUCE THE ISSUE

Click the magnifier next to the main product image to open the viewer. Try clicking the right arrow to advance. Viewer closes and returns visitor to product page. Try again, clicking the left arrow instead. Same thing happens.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.georgeglazer.com/wpmain
Site URL: http://www.georgeglazer.com/wpmain
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.3.29-pl0-gentoo - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 7.39.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (11) ###

Code Snippets: by Shea Bunge – 2.8.2
Jetpack by WordPress.com: by Automattic – 4.8.2
Meta Slider: by Matcha Labs – 3.5
Page Builder by SiteOrigin: by SiteOrigin – 2.5.0
SiteOrigin CSS: by SiteOrigin – 1.1.3
SiteOrigin Widgets Bundle: by SiteOrigin – 1.8.2
WooCommerce: by Automattic – 3.0.2
WooSidebars: by WooThemes – 1.4.3
WP All Import Pro: by Soflyy – 4.4.3
YITH Essential Kit for WooCommerce #1: by YIThemes – 1.4.4
YITH WooCommerce Catalog Mode: by YITHEMES – 1.5.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: ❌ Page not set
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by jameskoster** [comment]
As mentioned [here](https://github.com/woocommerce/woocommerce/pull/14223#issuecomment-293846039) I'm pretty sure this one is a Storefront Child Theme issue. Please confirm which you're using so I can patch and close this out.

**Comment by mikejolley** [comment]
@GlazerGallery ^ did you have feedback on this?

**Comment by GlazerGallery** [comment]
Yes, I left the feedback here: https://github.com/woocommerce/woocommerce/pull/14223#issuecomment-293846039
It is Storefront 2.1.8.

**Comment by jameskoster** [comment]
> It is Storefront 2.1.8.

That's not happening for me in Storefront 2.1. 

Please open an issue [here](https://github.com/woocommerce/storefront) with more info such as which child theme you're using and a URL to your store. 

Cheers!
