### ISSUE TITLE
Sold Individually ignored on variable products

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#14328]
### EXPLANATION OF THE ISSUE

Adding to the cart 2 variations from a product that is marked as "Sold Individually" is allowed, while it should be not.

### STEPS TO REPRODUCE THE ISSUE

1. Mark a variable product as Sold Individually.
2. Add 2 variations of the same product to the cart

![](http://cld.wthms.co/rqZ0+)
**Image Link**: http://cld.wthms.co/rqZ0+

**Comment by mikejolley** [comment]
@SiR-DanieL This matches 2.6 functionality - each variation is sold individually, not the entire product. Changing this would be breaking, not inline with 2.6 and past versions, and cause more issues.

**Comment by franticpsyx** [comment]
@mikejolley @SiR-DanieL -- see https://github.com/woocommerce/woocommerce/pull/13761

If we add this in 3.1 we can at least make it easy for people to control this behavior with a snippet.
