### ISSUE TITLE
Woocommerce 3.0.2 Issue

### ISSUE THREAD

**Issue by amirhosain1352** [woocommerce/woocommerce#14327]
### EXPLANATION OF THE ISSUE
Hi, in version 3.0.2 in login page, there is an extra link next to "/my-account/lost-password" named "/lost-user-password/?login" which returns "Page Not Found 404" error.

### STEPS TO REPRODUCE THE ISSUE
1) Go to login page
2) Under password frame and next to "Lost Your Password?", there is a new link "Click here to reset your password" which points to "/lost-user-password/?login" and leads to page not found 404 error.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.ravpower.co
Site URL: http://www.ravpower.co
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: fa_IR

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 20 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 20 MB
Default Timezone is UTC: ❌ منطقه زمانی پیشفرض Asia/Tehran می باشد - شما می بایست از UTC استفاده کنید
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌فروشگاه شما از HTTPS استفاده نمی کند. اطلاعات بیشتر درباره HTTPS و SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (32) ###

LayerSlider WP: توسط Kreatura Media – 5.6.8
Broken Link Checker: توسط Janis Elsts
Vladimir Prelovac – 1.11.2

Captcha by BestWebSoft: توسط BestWebSoft – 4.2.9
Contact Form 7: توسط Takayuki Miyoshi – 4.7
Envato Market: توسط Derek Herman – 1.0.0-RC2
Envato WordPress Toolkit: توسط Envato – 1.7.3
Flatastic Content Types: توسط mad_velikorodnov – 1.0.4
Google XML Sitemaps: توسط Arne Brachhold – 4.0.8
WPBakery Visual Composer: توسط Michael M - WPBakery.com – 5.0.1
Loco Translate: توسط Tim Whitlock – 2.0.13
درگاه پرداخت بانک ملت افزونه ووکامرس: توسط ووکامرس فارسی – 4.0.2
Newsletter: توسط Stefano Lissa & The Newsletter Team – 4.8.3
افزونه حرفه ای پیامک ووکامرس: توسط ووکامرس فارسی – 3.4.7
ووکامرس فارسی: توسط ووکامرس فارسی – 3.0
SUMO Reward Points: توسط Fantastic Plugins – 17.0
Rich Snippets WordPress Plugin by WP-Buddy: توسط wp-buddy – 1.6.1
Shiny Updates: توسط the WordPress team – 3-20160927
تلگرام برای وردپرس: توسط Ameer Mousavi – 1.6.1
Ultimate Addons for Visual Composer: توسط Brainstorm Force – 3.16.7
W3 Total Cache: توسط Frederick Townes – 0.9.5.2
WC Ajax Product Filter: توسط Shamim Al Mamun – 2.0.2
Woo Checkout Field Editor Pro: توسط ThemeHiGH – 1.1.6
درگاه پرداخت بانک سامان افزونه ووکامرس: توسط ووکامرس پارسی – 2.0.0
ووکامرس: توسط اتوماتیک – 3.0.2
Wordfence Security: توسط Wordfence – 6.3.6
افزونه Yoast SEO: توسط تیم Yoast – 4.6
بسته وردپرس پارسی: توسط تیم وردپرس پارسی – 2.2.2
WP Smush: توسط WPMU DEV – 2.6.2
WP Statistics: توسط Greg Ross & Mostafa Soufi – 12.0.5
YITH WooCommerce Ajax Search: توسط YITHEMES – 1.5.2
YITH WooCommerce Compare: توسط YITHEMES – 2.2.0
YITH WooCommerce Wishlist: توسط YITHEMES – 2.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

پایگاه فروشگاه: #673 - /grid-view-page/shop-%d9%81%d8%b1%d9%88%d8%b4%da%af%d8%a7%d9%87-%d8%a2%d9%86%d9%84%d8%a7%db%8c%d9%86-%d8%b1%d9%88%d9%be%d8%a7%d9%88%d8%b1-%d8%a7%db%8c%d8%b1%d8%a7%d9%86/
سبد خرید: #825 - /grid-view-page/cart-2/
تسویه حساب: #675 - /grid-view-page/checkout/
حساب کاربری: #676 - /grid-view-page/my-account/

### Theme ###

Name: Flatastic
Version: 1.6.2
Author URL: http://inthe7heaven.com
Child Theme: ❌ – اگر شما در حال ویرایش و شخصی سازی ووکامرس یا پوسته والد هستید پیشنهاد می کنیم از پوسته کودک استفاده کنید. چگونه یک پوسته کودک بسازیم را ببینید
WooCommerce Support: ✔

### Templates ###

Overrides: flatastic/woocommerce/archive-product.php
flatastic/woocommerce/auth/footer.php
flatastic/woocommerce/auth/form-grant-access.php
flatastic/woocommerce/auth/form-login.php
flatastic/woocommerce/auth/header.php
flatastic/woocommerce/cart/cart-empty.php
flatastic/woocommerce/cart/cart-item-data.php
flatastic/woocommerce/cart/cart.php
flatastic/woocommerce/cart/cart-shipping.php
flatastic/woocommerce/cart/cart-totals.php
flatastic/woocommerce/cart/cross-sells.php
flatastic/woocommerce/cart/mini-cart.php
flatastic/woocommerce/cart/proceed-to-checkout-button.php
flatastic/woocommerce/cart/shipping-calculator.php
flatastic/woocommerce/checkout/cart-errors.php
flatastic/woocommerce/checkout/form-billing.php
flatastic/woocommerce/checkout/form-checkout.php
flatastic/woocommerce/checkout/form-coupon.php
flatastic/woocommerce/checkout/form-login.php
flatastic/woocommerce/checkout/form-pay.php
flatastic/woocommerce/checkout/form-shipping.php نسخه 2.2.0 بروز نیست. نسخه پایه 3.0.0 می باشد
flatastic/woocommerce/checkout/payment-method.php
flatastic/woocommerce/checkout/payment.php
flatastic/woocommerce/checkout/review-order.php
flatastic/woocommerce/checkout/terms.php
flatastic/woocommerce/checkout/thankyou.php
flatastic/woocommerce/content-product_cat.php
flatastic/woocommerce/content-product.php
flatastic/woocommerce/content-single-product.php نسخه 1.6.4 بروز نیست. نسخه پایه 3.0.0 می باشد
flatastic/woocommerce/content-widget-product.php
flatastic/woocommerce/emails/admin-cancelled-order.php
flatastic/woocommerce/emails/admin-new-order.php
flatastic/woocommerce/emails/customer-completed-order.php
flatastic/woocommerce/emails/customer-invoice.php
flatastic/woocommerce/emails/customer-new-account.php
flatastic/woocommerce/emails/customer-note.php
flatastic/woocommerce/emails/customer-processing-order.php
flatastic/woocommerce/emails/customer-refunded-order.php
flatastic/woocommerce/emails/customer-reset-password.php
flatastic/woocommerce/emails/email-addresses.php نسخه 2.4.0 بروز نیست. نسخه پایه 3.0.0 می باشد
flatastic/woocommerce/emails/email-footer.php
flatastic/woocommerce/emails/email-header.php
flatastic/woocommerce/emails/email-order-items.php
flatastic/woocommerce/emails/email-styles.php
flatastic/woocommerce/emails/plain/admin-cancelled-order.php
flatastic/woocommerce/emails/plain/admin-new-order.php
flatastic/woocommerce/emails/plain/customer-completed-order.php
flatastic/woocommerce/emails/plain/customer-invoice.php
flatastic/woocommerce/emails/plain/customer-new-account.php
flatastic/woocommerce/emails/plain/customer-note.php
flatastic/woocommerce/emails/plain/customer-processing-order.php
flatastic/woocommerce/emails/plain/customer-refunded-order.php
flatastic/woocommerce/emails/plain/customer-reset-password.php
flatastic/woocommerce/emails/plain/email-addresses.php
flatastic/woocommerce/emails/plain/email-order-items.php
flatastic/woocommerce/global/breadcrumb.php
flatastic/woocommerce/global/form-login.php
flatastic/woocommerce/global/quantity-input.php
flatastic/woocommerce/global/sidebar.php
flatastic/woocommerce/global/wrapper-end.php
flatastic/woocommerce/global/wrapper-start.php
flatastic/woocommerce/loop/add-to-cart.php
flatastic/woocommerce/loop/loop-end.php
flatastic/woocommerce/loop/loop-start.php
flatastic/woocommerce/loop/no-products-found.php
flatastic/woocommerce/loop/orderby.php
flatastic/woocommerce/loop/pagination.php
flatastic/woocommerce/loop/price.php
flatastic/woocommerce/loop/rating.php
flatastic/woocommerce/loop/result-count.php
flatastic/woocommerce/loop/sale-flash.php
flatastic/woocommerce/myaccount/form-login.php
flatastic/woocommerce/myaccount/my-address.php
flatastic/woocommerce/myaccount/my-downloads.php
flatastic/woocommerce/myaccount/my-orders.php
flatastic/woocommerce/notices/error.php
flatastic/woocommerce/notices/notice.php
flatastic/woocommerce/notices/success.php
flatastic/woocommerce/order/form-tracking.php
flatastic/woocommerce/order/order-again.php
flatastic/woocommerce/order/order-details-customer.php
flatastic/woocommerce/order/order-details-item.php
flatastic/woocommerce/order/tracking.php
flatastic/woocommerce/product-searchform.php
flatastic/woocommerce/single-product/add-to-cart/external.php
flatastic/woocommerce/single-product/add-to-cart/grouped.php
flatastic/woocommerce/single-product/add-to-cart/simple.php
flatastic/woocommerce/single-product/add-to-cart/variable.php
flatastic/woocommerce/single-product/meta.php
flatastic/woocommerce/single-product/price.php
flatastic/woocommerce/single-product/product-attributes.php
flatastic/woocommerce/single-product/product-image.php نسخه 3.0.0 بروز نیست. نسخه پایه 3.0.2 می باشد
flatastic/woocommerce/single-product/product-thumbnails.php نسخه 3.0.0 بروز نیست. نسخه پایه 3.0.2 می باشد
flatastic/woocommerce/single-product/rating.php
flatastic/woocommerce/single-product/related.php
flatastic/woocommerce/single-product/review.php
flatastic/woocommerce/single-product/sale-flash.php
flatastic/woocommerce/single-product/share.php
flatastic/woocommerce/single-product/short-description.php
flatastic/woocommerce/single-product/tabs/additional-information.php
flatastic/woocommerce/single-product/tabs/description.php
flatastic/woocommerce/single-product/tabs/tabs.php
flatastic/woocommerce/single-product/title.php
flatastic/woocommerce/single-product/up-sells.php
flatastic/woocommerce/single-product.php
flatastic/woocommerce/single-product-reviews.php
flatastic/woocommerce/taxonomy-product_cat.php
flatastic/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌آموزش چگونگی بروزرسانی قالب های قدیمی
`
</details>

**Comment by mikejolley** [comment]
I think this must be coming from one of your plugins - we have one reference to "Click here to reset your password" which is in an email template, not output in other places: 

https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=Click+here+to+reset+your+password&type=

I'm not seeing it on my own sites (clean install).

**Comment by amirhosain1352** [comment]
Thanks Mike.
How can I track which plugin this link comes from?

**Comment by mikejolley** [comment]
Trial and error :(
