### ISSUE TITLE
Wrong refund date and time

### ISSUE THREAD

**Issue by AdriOosterwijk** [woocommerce/woocommerce#14332]
When refunding an order the date and time stamp is set to the order date/time instead of the refund date / time (current). As you can see the credit note date and time in the screenshot is the correct one. Please fix......
![schermafbeelding 2017-04-13 om 08 55 17](https://cloud.githubusercontent.com/assets/10272269/24993760/0ee844de-2028-11e7-8ad2-4795299e0e20.png)

**Comment by mensmaximus** [comment]
Just checked and the refund displays the order date for me too
![refund](https://cloud.githubusercontent.com/assets/4742179/24994119/b29564c6-2029-11e7-8ff8-4b2f2e75bb45.png)

**Comment by avinapatel** [comment]
@mikejolley I have fixed refund order date and time issue and please check PR for the same.

Please see the URL for the PR: https://github.com/woocommerce/woocommerce/pull/14337

Thanks,

**Comment by AdriOosterwijk** [comment]
Fix works for me, thanks!
