### ISSUE TITLE
Question more than issues

### ISSUE THREAD

**Issue by benjaminthedev** [woocommerce/woocommerce#14338]
Does the latest WooCommerce use Flexslider?

I am using WooCommerce version 3.0.2  - for slider on single products does it use Flexslider?

https://woocommerce.com/flexslider/

I am trying to make a customisation but it is not having luck, 
 PLease let me know, 

Cheers,
Ben.

**Comment by mikejolley** [comment]
Yes it does. See https://woocommerce.wordpress.com/2017/02/28/adding-support-for-woocommerce-2-7s-new-gallery-feature-to-your-theme/

**Comment by benjaminthedev** [comment]
Cheers
