### ISSUE TITLE
Plugin upgrade notice from 3.0.1 to 3.0.2

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce#14333]
### EXPLANATION OF THE ISSUE

I've already installed 3.0.1 version, which was updated from 3.0.0 and 2.6. There is an info on WordPress plugins.php screen that there's a new 3.0.2 version, which is fine. But there is also a red notice says that 3.0 is a major update and I should make a backup, etc. That notice can be confusing, because I already have 3.0.1 version, which is newer than 3.0. I've already made that major update (from 2.6 to 3.0.0, right?), so I think that this notice shouldn't be written this way or can be disabled in this case actually. 

Also don't know is it bug or feature but you can see two spinner icons one at the top, and one below that upgrade notice.

![zrzut ekranu 2017-04-13 o 09 37 30](https://cloud.githubusercontent.com/assets/27000783/24994868/f8789622-202c-11e7-9c4c-7afc423a6e8f.png)

### SYSTEM STATUS

<details>
### WordPress Environment ###

WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pl_PL
</details>

**Comment by AntBentinck** [comment]
I noticed some strange behaviour when uploading the 3.0.2 release via plugin page. It failed and actually installed 3.0.2 as its own plugin not overwriting 3.0.1.

I ended up uploading the 3.0.2 via FTP instead.

**Comment by mikejolley** [comment]
WordPress handles the update process. Maybe your directly naming was off?
