### ISSUE TITLE
Update regular price of a product is not working

### ISSUE THREAD

**Issue by BennSandoval** [woocommerce/woocommerce#14330]
### EXPLANATION OF THE ISSUE

We are trying to update the regular price of a product in the full edition way but if we save it, appears the previous one, we tried updating others fields at the same time like COG and the values are updated as expected except the regular price.

### STEPS TO REPRODUCE THE ISSUE

Open a product and change the regular price, quick edit works but full edition doesn't, looks like the edition of the field using the API is working but I'm not sure.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.taloselectronics.com
Site URL: https://www.taloselectronics.com
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_MX

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: 5.6.24-1+deb.sury.org~trusty+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.31
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

AfterShip - WooCommerce Tracking: por AfterShip – 1.6.8
Capability Manager Enhanced: por Jordi Canals
Kevin Behrens – 1.5.7

Contact Form 7: por Takayuki Miyoshi – 4.7
Machine Learning Related Products for WooCommerce: por Benn Sandoval – 0.1
DHL (BASIC) WooCommerce Extension: por WooForce – 1.1.9
Envato WordPress Toolkit: por Envato – 1.7.3
Factura punto com para woocommerce: por Factura.com – 1.6.4
FedEx WooCommerce Extension (BASIC): por WooForce – 2.0.3
Force HTTPS Srcset: por Hinaloe – 1.0
Force SSL: por Trevor Turk
BestWebLayout – 1.3

GetBowtied Tools: por GetBowtied – 1.3.1
Heartbeat Control: por Jeff Matson – 1.0.3
Invisible reCaptcha: por Mihai Chelaru – 1.0.8
WPBakery Visual Composer: por Michael M - WPBakery.com – 5.1.1
Optimus: por KeyCDN – 1.4.8
Pixel de Facebook para Woocommerce: por Lab School – 1.0.3
Postcode Estafeta: por Ruben Sandoval – 2.0
SendGrid: por SendGrid – 1.10.9
Shopkeeper Typekit Fonts: por GetBowtied – 1.1
Swift Mailer: por  – 5.4.3
W3 Total Cache: por Frederick Townes – 0.9.5.2
Woo Mercado Pago Module: por Mercado Pago – 2.2.0
WooCommerce Cost of Goods: por SkyVerge – 2.3.1
WooCommerce Google Analytics Integration: por WooThemes – 1.4.0
WooCommerce Waitlist: por Neil Pie – 1.5.2
WooCommerce: por Automattic – 3.0.2
WooCommerce Helper: por WooCommerce – 1.7.2 – Red activada
WordPress Importer: por wordpressdotorg – 0.6.3
WP Async CSS: por Robert Sæther – 1.2
WP Mail Logging: por Christian Zöller – 1.8.0
Zendesk Chat Widget: por Zopim – 1.4.8

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: MXN ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6 - /
Carrito: #299 - /carrito-de-compras/
Pago: #300 - /checkout/
My account: #9 - /mi-cuenta/

### Theme ###

Name: Shopkeeper
Version: 2.0.3
Author URL: http://www.getbowtied.com/
Child Theme: ❌ – Si estás modificando WooCommerce o un tema que no hiciste tu
recomendamos usar un tema hijo (child theme). Ver Cómo crear un tema hijo (child theme)

WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php
shopkeeper/woocommerce/cart/cart-empty.php
shopkeeper/woocommerce/cart/mini-cart.php
shopkeeper/woocommerce/checkout/form-billing.php
shopkeeper/woocommerce/checkout/form-checkout.php
shopkeeper/woocommerce/checkout/form-coupon.php
shopkeeper/woocommerce/checkout/form-login.php
shopkeeper/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.0.0
shopkeeper/woocommerce/content-product.php
shopkeeper/woocommerce/content-product_cat.php
shopkeeper/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
shopkeeper/woocommerce/emails/customer-on-hold-order.php
shopkeeper/woocommerce/emails/customer-processing-order.php
shopkeeper/woocommerce/global/quantity-input.php
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/loop/loop-end.php
shopkeeper/woocommerce/loop/loop-start.php
shopkeeper/woocommerce/loop/no-products-found.php
shopkeeper/woocommerce/myaccount/form-login.php
shopkeeper/woocommerce/myaccount/my-downloads.php
shopkeeper/woocommerce/order/form-tracking.php
shopkeeper/woocommerce/single-product/product-image.php version 3.0.0 is out of date. The core version is 3.0.2
shopkeeper/woocommerce/single-product/product-thumbnails.php version 3.0.0 is out of date. The core version is 3.0.2
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product-reviews.php
shopkeeper/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
</details>

**Comment by mensmaximus** [comment]
I can not confirm this issue. I have just changed several regular prices successfully. Did you disable all plugins and switched to a standard theme (twenty xxx) for testing?

**Comment by BennSandoval** [comment]
Thanks @mensmaximus no, I don't want to do it on my site, I'm looking on the /var/log/apache2/error.log and nothing related with the issue appears, is there another way to see issues?

**Comment by mensmaximus** [comment]
You should have a development/staging/testing environment to test such things.

**Comment by AdriOosterwijk** [comment]
Can't confirm it either. It works properly on my end.

**Comment by mikejolley** [comment]
+1. Please rule out extensions. Since this is working for multiple people I'm closing the issue.
