### ISSUE TITLE
Tax-rate on Shipping/Freight Cost based on Cart items and their Tax-rate

### ISSUE THREAD

**Issue by hedqvist** [woocommerce/woocommerce#14334]
### EXPLANATION OF THE ISSUE

Today in WooCommerce the calculation of tax on Shipping/Freight cost is incorrect if we compare this to the rules that The Swedish Tax Agency put out for us.
The following guidelines are availible in Swedish, but I will describe it down below

[Link to Guidelines at the Swedish Tax Agency](https://www.skatteverket.se/rattsinformation/skrivelser/ar/2002/2002/skrivelser20020913.4.18e1b10334ebe8bc80001578.html)

Today it works like this:

If a single product is added to the cart that have tax-rate tied to it, the same rate will be applied to shipping if we selected this under tax settings. So far so good.

The issue appears when we are having mixed tax-rates in our cart.

For example we have Product A with 12% Tax-rate & Product B with 25% Tax-rate.

If we check out tax on the shipping cost it will automatically take the highest tax-rate and apply that to the shipping cost, in this case 25%.

According to the the Swedish Tax Agency (Skatteverket) it should be like this:

VAT on shipping should be based on the VAT rate on the order that contains the greatest amount.

> Example:
> The rows with 25% VAT is 100 SEK together
> The rows with 12% VAT is 200 SEK together
> The VAT rate on shipping/freight should be 12%.

> Example:
> The rows with 25% VAT is 200 SEK together
> The rows with 12% VAT is 100 SEK together
> The VAT rate on shipping/freight should be 25%.

**If the amount of the order items is the same, the highest rate will be applied.**

> Example:
> The rows with 25% VAT is 100 SEK together
> The rows with 12% VAT is 100 SEK together
> The VAT rate on shipping/freight should be 25%.

### STEPS TO REPRODUCE THE ISSUE

1. Create Tax-rates with 25% and 12%
2. Set the option: No, I will enter prices exclusive of tax
3. Create two products Tied to the above rates. (one of each)
4. Set product price to 100kr on each product.
5. Add flat-rate shipping cost, for example 100kr (ex VAT)
6. Add to cart/checkout and look at the total.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: https://www.backend.se
Site URL: https://www.backend.se
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 400 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.7.13
Max Upload Size: 356 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: yD1w5Gtu62_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

WooCommerce Swish Ecommerce Gateway: by Redlight Media – 1.3
WooCommerce: by Automattic – 3.0.2
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My account: #8 - /?page_id=8

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
May need to research what other country requirements are before making any changes in core.

**Comment by mensmaximus** [comment]
@mikejolley nearly each country in Europe has it's won tax regulation In Germany e.g. a shop may apply mixed tax on shipping in the same ratio as mixed tax is applied to products. However it is also allowed to charge the highest tax applied to a product in the card for shipping only. I would not implement it in core because it will be a nightmare to maintain. And if it would be in core you would need to implement the European general tax regulations as well with all its exceptions. There are already plugins handling this for different countries.

**Comment by hedqvist** [comment]
@mensmaximus In Sweden we are also allowed to charge  mixed tax on shipping in the same ratio as mixed tax is applied to products. But I think some of the Tax alternatives are more standard than others. Perhaps some of the normal ways could be applied into core? Also, what plugins are you thinking about that sorts this?

**Comment by mikejolley** [comment]
I agree with @mensmaximus, I think this should start in a separate plugin mainly because it could then be maintained by Swedes who know more about the tax rules of that country. AFAIK this rule only seems to apply to Sweden?
