### ISSUE TITLE
$product->get_attribute() crashes on custom attributes

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#14345]
### EXPLANATION OF THE ISSUE

using `$product->get_attribute()` on a product variation produces a fatal error:
`
PHP Fatal error:  Call to a member function is_taxonomy() on string in /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php on line 1772
`
It seems that the main product returns a list of object with `get_attributes()` whereas on a variation it returns an array.
I believe this issue was introduced in 3.0.2.

### STEPS TO REPRODUCE THE ISSUE

* Create a variable product
* Add an attribute
* Assign the attribute to a variation
* load the variation (`wc_get_product( $variation_id )`) and call `$product->get_attribute( $attribute )`

**Comment by mikejolley** [comment]
No changes to that method in 3.0.2

**Comment by mikejolley** [comment]
Just this to prevent non-valid values being loaded https://github.com/woocommerce/woocommerce/compare/3.0.1...3.0.2#diff-dfe1f5ea8a99b6978fadb1301dc0d750R356

**Comment by mikejolley** [comment]
Can repro though. Seeing if it's an error on my part and what version it appeared.

**Comment by mikejolley** [comment]
Same in 3.0

**Comment by Spreeuw** [comment]
What other information can I provide to help you reproduce this issue?

**Comment by Spreeuw** [comment]
The attribute i was testing with was a custom attribute (i.e. entering text in the product attributes tab)

**Comment by claudiosanches** [comment]
@Spreeuw but are you sure that are using the correct attribute name?
Show me how you are setting it on the admin and then in your code.

**Comment by Spreeuw** [comment]
Haha, fixed while I was busy making screenshots of my settings and reproducible steps.

Thanks for the quick fix Mike!

**Comment by claudiosanches** [comment]
@Spreeuw thanks for report it.
