### ISSUE TITLE
Prices messed up

### ISSUE THREAD

**Issue by aprwebdesign** [woocommerce/woocommerce#14349]
I installed the latest woocommerce update today.

However something is very wrong with the prices inside our store.
The prices inside our store are not matching with the prices inserted inside the variations.

I can't figure out why.

Also not all prices are wrong... some prices are correct and some are entirely wrong.

![image](https://cloud.githubusercontent.com/assets/23439533/25008397/db4c1f88-2063-11e7-8d70-d21327bb964f.png)

![image](https://cloud.githubusercontent.com/assets/23439533/25008413/e7cced64-2063-11e7-82a7-b62e3e8ae43c.png)

**Comment by aprwebdesign** [comment]
It seems like there is something wrong with the TAX classes.

When u update the tax class manually to default the right prices are set.
However when the tax class is set to same as parent the prices are wrong

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14331

**Comment by aprwebdesign** [comment]
Thanks,

I managed to fix it with the following:

run a sql query:

UPDATE `bkwp_postmeta` SET `meta_value`='' WHERE `meta_key` = '_tax_class'

(this sets the tax class to default instead of same as parent) .

after that i went to woocommerce > settings > tax  and just re-saved the settings  (don't know if it is required but not all products where updated after the query but when re-saved the tax setting all prices when right again)

**Comment by aprwebdesign** [comment]
Applyed the patch of Mikejolley and all prices are fixed.

Thanks Mikejolley
