### ISSUE TITLE
Product can be ordered twice although its Stock Quantity is 1

### ISSUE THREAD

**Issue by pe6o** [woocommerce/woocommerce#14343]
Latest version of WooCommerce.

I have opened two browser windows (one logged and one logged off in incognito mode). On both of them I've added the same product in the cart. The product has a quantity of 1.

On the last step I clicked "Place Order" almost at the same time and managed to buy the product twice in both sessions.

I have automatic order completion enabled as shown here - https://docs.woocommerce.com/document/automatically-complete-orders/

**Comment by mikejolley** [comment]
We have an issue logged here https://github.com/woocommerce/woocommerce/issues/13359. It's not preventable at present.
