### ISSUE TITLE
woocommerce Stamps.com plugin gets lost on address verificatoin 3.0/30.1/3.0.2

### ISSUE THREAD

**Issue by collinbrendemuehl** [woocommerce/woocommerce#14347]
### EXPLANATION OF THE ISSUE

System goes into an infinite wait loop, never returns.

### STEPS TO REPRODUCE THE ISSUE

When an order comes in the first step is to verify the customer shipping address by clicking the Continue button in the shipping labels widget box.

### SYSTEM STATUS

<details>
```

`
### WordPress Environment ###

Home URL: http://www.g-corautomotive.com
Site URL: http://www.g-corautomotive.com
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Microsoft-IIS/8.5
PHP Version: 7.0.17
PHP Post Max Size: 200 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (19) ###

404page - your smart custom 404 error page: by Peter's Plugins (formerly smartware.cc) – 2.4
Akismet Anti-Spam: by Automattic – 3.3
Divi Builder: by Elegant Themes – 2.0.3
PayPal Express Checkout for WooCommerce: by wpgateways – 1.1.9
Additional Registration Attributes: by FME Addons – 1.0.2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.7
Login Security Solution: by Daniel Convissor – 0.56.0
Relevanssi: by Mikko Saari – 3.5.8
Total Security: by Fabrix DoRoMo – 3.4.7
User Roles and Capabilities: by mahabub – 1.2.1
USPS WooCommerce Shipping: by WooForce – 3.0.1
Woocommerce CSV Import: by Allaerd Mensonides – 3.3.5
WooCommerce - Store Exporter: by Visser Labs – 1.8.8
WooCommerce Image Zoom: by wpbean – 1.02.1
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.6.0

WooCommerce Stamps.com API integration: by WooThemes – 1.2.8 – 1.3.1 is available
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0

WooCommerce Simple Registration: by Astoundify – 1.3.0
WooCommerce: by Automattic – 3.0.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #9776 - /shopping/
Cart: #19 - /cart/
Checkout: #20 - /checkout/
My account: #21 - /my-account/

### Theme ###

Name: Divi
Version: 3.0.40
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

```
</details>

**Comment by collinbrendemuehl** [comment]
Per the log, it appears that authentication is happening without issue, but system not returning to customer.
04-13-2017 @ 13:56:23 - Endpoint CleanseAddress Response: stdClass Object
(
    [Authenticator] => exp=1492178211&uid=8577604&cty=swsim&ctk=jmRdNIzW/wLYD+/d+3u2TQJo8YQ=&iid=AloUYpmd30ektMcE0KCasg==&rsid=0&irsid=1&eac=1480459706&eacx=29554687&eac3=0&rrsid=0&raid=0&resellerid=0&pexp=0&pl=&ast=1&ipaddr=54.85.36.223&ace=1492095411&mac=0hXqEPvJplZ5Sq+grslbHqpYJpw=
    [Address] => stdClass Object
        (
            [FullName] => DAVE-SEAWINGS MONIZ-SEAWINGS
            [Company] => SEAWINGS EXPESS INTERNATIONAL
            [Address1] => 1927 BOBLETT ST
            [Address2] => 
            [City] => BLAINE
            [State] => WA
            [ZIPCode] => 98230
            [ZIPCodeAddOn] => 5188
            [DPB] => 27
            [CheckDigit] => 7
            [Urbanization] => 
            [CleanseHash] => Je3i6rw5IUCiJBv1cviofiJEpi9kZWFkYmVlZg==20171011R013
            [OverrideHash] => uGuteH3nrQdJqPUCdDF3AutZ6TpkZWFkYmVlZg==20171011R013
        )

    [AddressMatch] => 1
    [CityStateZipOK] => 1
    [ResidentialDeliveryIndicator] => No
    [IsPOBox] => 
    [CandidateAddresses] => stdClass Object
        (
        )

    [StatusCodes] => stdClass Object
        (
            [ReturnCode] => 31
            [Footnotes] => stdClass Object
                (
                    [Footnote] => stdClass Object
                        (
                            [Value] => N
                        )

                )

            [DpvFootnotes] => stdClass Object
                (
                    [DpvFootnote] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [Value] => AA
                                )

                            [1] => stdClass Object
                                (
                                    [Value] => BB
                                )

                            [2] => stdClass Object
                                (
                                    [Value] => R1
                                )

                        )

                )

        )

)

**Comment by mikejolley** [comment]
Do you have an open ticket on support?

**Comment by collinbrendemuehl** [comment]
I attempted to but the system would not accept it. 3x.
Does not show up in my ticket list.

Collin Brendemuehl
G-COR Automotive
2148 Refugee Rd.
Columbus, Ohio 43207
877.888.5160 / 614.444.5160

**Comment by mikejolley** [comment]
> WooCommerce Stamps.com API integration: by WooThemes – 1.2.8 – 1.3.1 is available

Looks like you're out of date. Please log a ticket if you have more problems!

**Comment by collinbrendemuehl** [comment]
Looking for information on a proper update procedure without an update link.
Do I delete the plugin + data and reinstall the plug-in from scratch? Or do I delete that plug-in via FTA (to leave the data intact) and then install the plugin?
Can’t find docs on the website with respect to a proper procedure here.
(I spent my IT career around IBM technologies and there are some things about the open source movement that I’m still trying to figure out.)

Collin Brendemuehl
G-COR Automotive
2148 Refugee Rd.
Columbus, Ohio 43207
877.888.5160 / 614.444.5160

**Comment by mikejolley** [comment]
You can FTP it to wp-content/plugins and overwrite the old version.

**Comment by collinbrendemuehl** [comment]
Gook me a while but I found the api key etc.
One link took me to elegant themes, the other to woo. Not a productive half hour.
Open source is certainly clumsy.
Thanks again for your help.

Collin Brendemuehl
G-COR Automotive
2148 Refugee Rd.
Columbus, Ohio 43207
877.888.5160 / 614.444.5160
