### ISSUE TITLE
404 - Page not found after upgrade plugin

### ISSUE THREAD

**Issue by antoniobosio** [woocommerce/woocommerce#14354]
### EXPLANATION OF THE ISSUE

Hi,
I have upgrade the plugin to 3.0.2 version on wordpress 4.7.3.
In my site, Product Permalink is Custom Base: /shop-imagevintage/

After the upgrade all child pages show me 404 Page not Found.
If I try to change the product Permalink in "Default" all pages works fine, but when I click on a single product the URL is no longer the same as before:

Before upgrade: http://www.<mysite>.it/wp_iv_2017_new/shop-imagevintage/bianco_03/
After upgrade: http://www.<mysite>.it/wp_iv_2017_new/prodotto/bianco_03/

I would like to be able to reconfigure my custom base Product Permalink.
How can I do this ?

Best Regards
Antonio

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Can you screenshot your current permalink settings and bases?

**Comment by antoniobosio** [comment]
![iv_1](https://cloud.githubusercontent.com/assets/6931815/25012542/1acd532c-2071-11e7-976e-6e17f9f3869a.PNG)
![iv_2](https://cloud.githubusercontent.com/assets/6931815/25012541/1acced60-2071-11e7-8a0f-51a460887f13.PNG)

**Comment by mikejolley** [comment]
Need to see all permalinks including the taxonomy ones further up.

**Comment by antoniobosio** [comment]
![iv_0](https://cloud.githubusercontent.com/assets/6931815/25012708/a93740aa-2071-11e7-8a97-947e678ab75e.PNG)

**Comment by mikejolley** [comment]
Ok post your full system status report please. Seeing if there are obvious conflicts like WPML present.

**Comment by antoniobosio** [comment]
`
### WordPress Environment ###

Home URL: http://www.imagevintage.it/wp_iv_2017_new
Site URL: http://www.imagevintage.it/wp_iv_2017_new
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: Come aggiornare la versione di PHP
PHP Post Max Size: 25 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.52.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (17) ###

LayerSlider WP: by Kreatura Media – 5.6.10
Contact Form 7: by Takayuki Miyoshi – 4.7
Duplicate Post: by Enrico Battocchi – 3.2
Envato WordPress Toolkit: by Envato – 1.7.3
I Recommend This: by themeist – 3.7.7
Relevanssi: by Mikko Saari – 3.5.8
Slider Revolution: by ThemePunch – 5.2.6
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.4.9
Uncode Core: by Undsgn – 1.2
Uncode Dave's WordPress Live Search (4.4.1): by Dave Ross – 1.0
Uncode Visual Composer: by Michael M - WPBakery.com – 4.12.1
Uncode Related Posts for WordPress (1.9.3): by Never5 – 1.0
Visual Composer Clipboard: by bitorbit – 3.24
VC Particles Background: by Boom-Apps – 1.2
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.0
WooCommerce: by Automattic – 3.0.2
WP-CopyProtect [Protect your blog posts]: by Chetan Gole – 3.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ La pagina non è impostata
Carrello: #9 - /cart/
Cassa: #10 - /checkout/
My account: #11 - /my-account/

### Theme ###

Name: Uncode
Version: 1.4
Author URL: http://www.undsgn.com
Child Theme: ❌ – Se stati modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

### Templates ###

Overrides: uncode/woocommerce/archive-product.php
uncode/woocommerce/cart/mini-cart.php
uncode/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
uncode/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
uncode/woocommerce/loop/loop-end.php
uncode/woocommerce/loop/loop-start.php
uncode/woocommerce/loop/pagination.php
uncode/woocommerce/myaccount/my-account.php
uncode/woocommerce/myaccount/navigation.php
uncode/woocommerce/notices/error.php
uncode/woocommerce/notices/notice.php
uncode/woocommerce/notices/success.php
uncode/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 3.0.0
uncode/woocommerce/order/order-details.php version 2.6.0 is out of date. The core version is 3.0.0
uncode/woocommerce/product-searchform.php
uncode/woocommerce/single-product/add-to-cart/external.php
uncode/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.0
uncode/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
uncode/woocommerce/single-product/add-to-cart/variable.php
uncode/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
uncode/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
uncode/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.0.2
uncode/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.0.2
uncode/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
uncode/woocommerce/single-product/review.php
uncode/woocommerce/single-product/share.php
uncode/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
uncode/woocommerce/single-product/tabs/description.php
uncode/woocommerce/single-product/tabs/tabs.php
uncode/woocommerce/single-product/title.php
uncode/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
uncode/woocommerce/single-product-reviews.php
uncode/woocommerce/single-product.php
uncode/woocommerce/taxonomy-product_cat.php

Outdated Templates: ❌Learn how to update
`

**Comment by claudiosanches** [comment]
@antoniobosio do you have a page on WordPress with the slug `shop-imagevintage`?

**Comment by antoniobosio** [comment]
Yes, It is bere: http://www.imagevintage.it/wp_iv_2017_new/shop-imagevintage/

**Comment by antoniobosio** [comment]
In edit page I show this permalink:
Permalink: http://www.imagevintage.it/wp_iv_2017_new/shop-imagevintage/ ‎

**Comment by mikejolley** [comment]
I think the base is invalid. You need a product base after the 'page'.

So something like /shop-imagevintage/product/product-name is fine. But /shop-imagevintage/product-name conflicts.

**Comment by mikejolley** [comment]
Actually that works for me. 

Set the option in WooCommerce > Products:

> Shop base: ❌ La pagina non è impostata

Set that to shop-imagevintage page

Then set permalinks to shop-base. That should fix.
