### ISSUE TITLE
Issue with variants on WooCommerce 3.0.2

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#14351]
I can't create variants with attributes from 3rd app. 

Please check this video:
https://drive.google.com/file/d/0B5IOJBhjjLrNUU5fQnItbWM0c1U/view?usp=sharing

**Comment by claudiulodro** [comment]
Can I please get a copy+paste of the system status report to better troubleshoot this? It's in WooCommerce > System Status

**Comment by kevin25** [comment]
Here is our System Status

> `
### WordPress Environment ###


WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 7.1.3
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 2000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Contact Form 7: by Takayuki Miyoshi – 4.7
Google Authenticator: by Henrik Schack – 0.48
Woocommerce Products Price Bulk Edit: by Mostafa Qanbari – 2.0
PixelYourSite PRO: by PixelYourSite – 6.0.3
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.1.8
Recover Abandoned Cart: by Fantastic Plugins – 15.8.3
Redirection: by John Godley – 2.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SEO Optimized Images: by priyanshu.mittal – 1.6.7
WooCommerce Advanced Shipping - Advanced Pricing: by Jeroen Sormani – 2.1.0
WooCommerce Advanced Shipping: by Jeroen Sormani – 1.0.13
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce MailChimp Subscribe: by SeedProd – 1.0.8
WooCommerce Notification: by Andy Ha (villatheme.com) – 1.1.4
WooCommerce Google Product Feed: by Lee Willis – 7.0.7
WooCommerce: by Automattic – 3.0.2
Yoast SEO Premium: by Team Yoast – 4.6
WP Rocket: by WP Media – 2.9.11
Yoast SEO: WooCommerce: by Team Yoast – 4.5
YITH WooCommerce Wishlist: by YITHEMES – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Flatsome
Version: 3.3.3
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome-new/woocommerce/archive-product.php
flatsome-new/woocommerce/cart/cart-empty.php
flatsome-new/woocommerce/cart/cart.php
flatsome-new/woocommerce/checkout/form-checkout.php
flatsome-new/woocommerce/checkout/form-coupon.php
flatsome-new/woocommerce/checkout/thankyou.php
flatsome-new/woocommerce/content-product.php
flatsome-new/woocommerce/content-product_cat.php
flatsome-new/woocommerce/content-single-product.php
flatsome-new/woocommerce/global/breadcrumb.php
flatsome-new/woocommerce/global/quantity-input.php
flatsome-new/woocommerce/global/wrapper-end.php
flatsome-new/woocommerce/global/wrapper-start.php
flatsome-new/woocommerce/loop/loop-end.php
flatsome-new/woocommerce/loop/loop-start.php
flatsome-new/woocommerce/loop/orderby.php
flatsome-new/woocommerce/loop/pagination.php
flatsome-new/woocommerce/loop/result-count.php
flatsome-new/woocommerce/loop/sale-flash.php
flatsome-new/woocommerce/myaccount/form-login.php
flatsome-new/woocommerce/myaccount/navigation.php
flatsome-new/woocommerce/notices/error.php
flatsome-new/woocommerce/notices/notice.php
flatsome-new/woocommerce/notices/success.php
flatsome-new/woocommerce/product-searchform.php
flatsome-new/woocommerce/single-product/photoswipe.php
flatsome-new/woocommerce/single-product/price.php
flatsome-new/woocommerce/single-product/product-image.php
flatsome-new/woocommerce/single-product/product-thumbnails.php
flatsome-new/woocommerce/single-product/related.php
flatsome-new/woocommerce/single-product/review.php
flatsome-new/woocommerce/single-product/sale-flash.php
flatsome-new/woocommerce/single-product/share.php
flatsome-new/woocommerce/single-product/short-description.php
flatsome-new/woocommerce/single-product/tabs/tabs.php
flatsome-new/woocommerce/single-product/title.php
flatsome-new/woocommerce/single-product/up-sells.php
flatsome-new/woocommerce/single-product-reviews.php
flatsome-new/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
If you want to check yourself, look at the server error log and see if there are fatal errors. This would stop the ajax loading and cause variation panel to be empty.

Also check there are no errors on the console - in chrome, View > Developer > Javascript console.

Need access to look into this further - email or log a ticket in our helpdesk. This isn't reproducible our end so looks like a conflict of sorts.

**Comment by kevin25** [comment]
> \nNotice: Undefined index: style in /home/domain/public_html/wp-content/plugins/woocommerce-colororimage-variation-select/woocommerce/single-product/add-to-cart/variable.php on line 38
\nNotice: Undefined index: color in /home/domain/public_html/wp-content/plugins/woocommerce-colororimage-variation-select/woocommerce/single-product/add-to-cart/variable.php on line 38
\nNotice: Undefined index: size in /home/domain/public_html/wp-content/plugins/woocommerce-colororimage-variation-select/woocommerce/single-product/add-to-cart/variable.php on line 38
\nNotice: Undefined index: style in /home/domain/public_html/wp-content/plugins/woocommerce-colororimage-variation-select/woocommerce/single-product/add-to-cart/variable.php on line 38
\nNotice: Undefined index: color in /home/domain/public_html/wp-content/plugins/woocommerce-colororimage-variation-select/woocommerce/single-product/add-to-cart/variable.php on line 38
\nNotice: Undefined index: size in /home/domain/public_html/wp-content/plugins/woocommerce-colororimage-variation-select/woocommerce/single-product/add-to-cart/variable.php on line 38
\nWarning: touch(): Unable to create file /home/domain/public_html/wp-content/cache/wp-rocket/thewholesaletshirts.com/shop/ya-done-messed-up-a-a-ron-sweatshirt-8-oz/.mobile-active because No such file or directory in /home/domain/public_html/wp-content/plugins/wp-rocket/inc/front/process.php on line 178
\nNotice: Undefined index: style in /home/domain/public_html/wp-content/plugins/woocommerce-colororimage-variation-select/woocommerce/single-product/add-to-cart/variable.php on line 38
\nNotice: Undefined index: color in /home/domain/public_html/wp-content/plugins/woocommerce-colororimage-variation-select/woocommerce/single-product/add-to-cart/variable.php on line 38
\nNotice: Undefined index: size in /home/domain/public_html/wp-content/plugins/woocommerce-colororimage-variation-select/woocommerce/single-product/add-to-cart/variable.php on line 38

This is what i got from debug log

**Comment by kevin25** [comment]
And from webserver log:

> 2017/04/13 15:50:32 [error] 3165#0: *286240 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-variations.php on line 23
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-variations.php on line 23" while reading response header from upstream, client: 14.176.92.192, server: domain.com.com, request: "GET /wp-admin/post.php?post=66635&action=edit HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "domain.com.com", referrer: "https://domain.com.com/wp-admin/edit.php?post_type=product"
2017/04/13 15:50:44 [error] 3165#0: *286240 FastCGI sent in stderr: "PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php on line 35
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php on line 35
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php on line 35
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php on line 35" while reading response header from upstream, client: 14.176.92.192, server: domain.com.com, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.sock:", host: "domain.com.com", referrer: "https://domain.com.com/wp-admin/post.php?post=66635&action=edit"

**Comment by kevin25** [comment]
There is no error on Chrome Console @mikejolley

**Comment by claudiosanches** [comment]
@kevin just check that all this warnings are coming from `woocommerce-colororimage-variation-select` plugin. Have you reported for it?

**Comment by kevin25** [comment]
WooSwatches - Woocommerce Color or Image Variation Swatches was disabled @claudiosanches

**Comment by claudiosanches** [comment]
@kevin25 and you are sure that this last errors are from now, from your last check?

**Comment by kevin25** [comment]
Yes. This is the latest warning that is filling my server log.

> PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-variation-admin.php on line 35

**Comment by claudiosanches** [comment]
@kevin25 I just tested and works fine.
In your video that checkbox it's wrong, should be just like an input file with Select2, looks like errors with JS.
Still have you tried to disable other plugins and change your theme?

**Comment by kevin25** [comment]
I'll check them. Thank you @claudiosanches

**Comment by nrkdirect** [comment]
I just found this error on my non working site which is not loading attributes

Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.min.js:30)
    at Function.each (load-scripts.php:2)
    at c.prepareOpts (select2.min.js:30)
    at c.prepareOpts (select2.min.js:63)
    at c.init (select2.min.js:24)
    at HTMLSelectElement.<anonymous> (select2.min.js:79)
    at Function.each (load-scripts.php:2)
    at a.fn.init.each (load-scripts.php:2)
    at a.fn.init.e.fn.select2 (select2.min.js:79)
    at HTMLSelectElement.<anonymous> (wc-enhanced-select.min.js:1)
select2.min.js:30 Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.min.js:30)
    at Function.each (load-scripts.php:2)
    at c.prepareOpts (select2.min.js:30)
    at c.prepareOpts (select2.min.js:63)
    at c.init (select2.min.js:24)
    at HTMLSelectElement.<anonymous> (select2.min.js:79)
    at Function.each (load-scripts.php:2)
    at a.fn.init.each (load-scripts.php:2)
    at a.fn.init.e.fn.select2 (select2.min.js:79)
    at HTMLSelectElement.<anonymous> (wc-enhanced-select.min.js:1)
