### ISSUE TITLE
Shortcode Pagination for WooCommerce plugin doesn't compatible with WooCommerce 3.0

### ISSUE THREAD

**Issue by amraja** [woocommerce/woocommerce#14350]
Shortcode Pagination for WooCommerce plugin after woocommerce 3.0 update doesn't work. how to add pagination to recent product shortcode in woocommerce 3.0 or how to fix this plugin?
problem: page 2,3,..,n = page 1

my wordpress version: 4.7.3
woocommerce 3.0.2
plugin: 1.0.5

demo of this problem: babyarshiya.ir/old/wordpress/test/

**Comment by mikejolley** [comment]
This plugin won't work because shortcodes get cached. Dev has to use the `woocommerce_shortcode_products_query` filter to modify the actual query args before it gets cached. cc @jamesckemp

**Comment by jamesckemp** [comment]
Thanks @mikejolley - saw the update earlier and was pleased to see the filter moved outside of the transient!

@amraja Update will be available soon.

**Comment by amraja** [comment]
I wait impatiently
@jamesckemp

**Comment by amraja** [comment]
@jamesckemp thank you for update.
but in debug mode:
Notice: تابع id به‌صورت
نادرست
فراخوانی شد. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/twentysixteen/page.php'), get_template_part, locate_template, load_template, require('/themes/twentysixteen/template-parts/content-page.php'), the_content, apply_filters('the_content'), call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, WC_Shortcodes::recent_products, WC_Shortcodes::product_loop, wc_get_template_part, load_template, require('/plugins/woocommerce/templates/content-product.php'), do_action('woocommerce_after_shop_loop_item_title'), call_user_func_array, woocommerce_template_loop_price, wc_get_template, include('/plugins/woocommerce/templates/loop/price.php'), WC_Product->get_price_html, WC_Product->get_price_suffix, apply_filters('woocommerce_get_price_suffix'), call_user_func_array, WC_Quantities_and_Units_Product_U in /home/babynaha/public_html/old/wordpress/wp-includes/functions.php on line 4041
ریال1,000.00

Notice: تابع product_type به‌صورت
نادرست
فراخوانی شد. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/twentysixteen/page.php'), get_template_part, locate_template, load_template, require('/themes/twentysixteen/template-parts/content-page.php'), the_content, apply_filters('the_content'), call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, WC_Shortcodes::recent_products, WC_Shortcodes::product_loop, wc_get_template_part, load_template, require('/plugins/woocommerce/templates/content-product.php'), do_action('woocommerce_after_shop_loop_item'), call_user_func_array, woocommerce_template_loop_add_to_cart, apply_filters('woocommerce_loop_add_to_cart_args'), call_user_func_array, WC_Quantities_and_Units_Filters->woocommerce_loop_add_to_cart_args, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong  in /home/babynaha/public_html/old/wordpress/wp-includes/functions.php on line 4041

**Comment by jamesckemp** [comment]
@amraja Think this is coming from another plugin, something like "WC_Quantities_and_Units_Filters"?

**Comment by amraja** [comment]
@jamesckemp yes .You are right
