### ISSUE TITLE
Infinity loop when wrapping 'woocommerce_template_single_add_to_cart()' inside a shortcode

### ISSUE THREAD

**Issue by indikatordesign** [woocommerce/woocommerce#14358]
### EXPLANATION OF THE ISSUE

I am developing a plugin for a page builder (divi) that makes it possible to add the different woo elements where the customer wants them.

Everything works fine till WC 3. Works still fine for simple products but it creates an infinite loop with variable products. Perhaps you have an idea what's going wrong..

### STEPS TO REPRODUCE THE ISSUE

This part of a shortcode can be included in a product page:

Shortcode Content:

```
ob_start();

echo sprintf( '<div%1$s class="woo-add-to-cart %2$s"><div class="inner">', $id, $class );

	woocommerce_template_single_add_to_cart();

echo '</div></div>';

return ob_get_clean();
```
The problem is located inside
    "/woocommerce/includes/class-wc-product-variable.php"

Line 297: ( function call to "get_available_variation( $variation )" )

`    'variation_description' => wc_format_content( $variation->get_description() ),`

When I comment this line out, everything works well.. Otherwise it performs an php error: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted

Memory Size is set to 256MB.

Maybe it has a problem when a string is served, without a shortcode included?

When I change the line above to this:
    'variation_description' => $variation->get_description(),

everything works fine.

It seems that it has a problem with a string like this: "Hello 4" or just an empty string. I added this string for test purposes inside the variation descriptions..

### SYSTEM STATUS

Divi, WooCommerce, My Plugin. Everywhere the newest versions (WP itself also).. Nothing else..

**Comment by indikatordesign** [comment]
Edit: When downgrading to WooCommerce 3.0.1 solves the issue. No endless loop there.. Seems to happen with WooCommerce 3.0.2 ++

**Comment by mikejolley** [comment]
@indikatordesign wc_format_content applies some filters:

https://github.com/woocommerce/woocommerce/blob/e027e5b0a1ab8e2c7b746c7d6bd2ef3879178139/includes/wc-core-functions.php#L47-L54

Do you do any callbacks on those?

**Comment by indikatordesign** [comment]
To get the content from the pagebuilder into the right place, it is needed to change the output-fields.

```

global $post;

$this->post = $post;

add_filter( 'woocommerce_short_description', [ $this, 'placeContent' ], 9 );

public function placeContent()
{

	return apply_filters( 'dawp_post_content', $this->post->post_content, $this->post );

} // end placeContent
```
This output includes the shortcodes from the pagebuilder. Here are also the shortcodes for the Woo elements included.

It works pretty well, as long as the add-to-cart-shortcode-content with "woocommerce_template_single_add_to_cart();" (described in the initial post) isn't included.

Something seems to be changed since Woo 3.0.2, cause it never generates a problem before.

But it seems to be limited to the variable products. When you set exactly the same content to simple product, it works fine.

**Comment by indikatordesign** [comment]
@mikejolley thank you for your reply. You guided me the right way. It was possible for me to fix the issue using the hooking-system.

Thank you and best regards
