### ISSUE TITLE
address info got replaced bij "Guest"

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/woocommerce#14360]
### EXPLANATION OF THE ISSUE

When you open an order and save it again, the invoice and shipping address details are gone and replaced by "Guest". I observed this with completed orders, both recent as well as from months ago. This is really nasty. I do not want WP account created by every client so I have Pay as Guest enabled but shipping address details must always be filled in.  

### STEPS TO REPRODUCE THE ISSUE

See issue. 

### SYSTEM STATUS

<details>
latest 3.0.3
</details>

**Comment by EgbertJan** [comment]
just retrieves some orders from postmeta. In the one opened and saved (no edits), all _billing and _shipping field are empty. An untouched order has all fields fille in as expected.

![order2](https://cloud.githubusercontent.com/assets/7521869/25022508/6a5c2f88-2096-11e7-83bd-0b0aa0499ae8.PNG)
![order1l](https://cloud.githubusercontent.com/assets/7521869/25022507/6a5bbf3a-2096-11e7-9aa1-dd6ec610f60e.PNG)

Egbert Jan

**Comment by mikejolley** [comment]
@EgbertJan Not to sound like a broken record but what testing have you done in regards to extensions that are active? You provided no status report.

I've just tried saving both a guest order and a user order, and setting status, and changing data, and in none of these cases was the data removed. I'd like to think that if such a serious issue were present in core, it would have been caught.

**Comment by EgbertJan** [comment]
I fully agree. The only things that were updated were WC 3.0.1 to WC 3.0.2 yesterday and to 3.0.3 today and 2 days ago, WCPS by Nur Hasan (a product slider that uses featured products).
There is rarily a reason to edit an order, so it may be going on longer... I'll try to switch off plugins as much as I can. I''ll replay this on the testsite. Cannot affort to loose more orders this way.

**Comment by mikejolley** [comment]
Good idea 👍 As I said, I followed the instructions you gave and nothing was lost, so I'd expect something on your site :)

**Comment by EgbertJan** [comment]
initial test on the test site are OK. I did not switch off anything yet.

**Comment by EgbertJan** [comment]
Strange, Test site works fine whatever I try. On the production site: when I open the order and try to edit the invoice or shipping address (via the little pencil icon), all fields are blank. On the test site address data is visible, I can reload either of then since I am a known user. When I reload both and save the order all seems ok. But when I reload one of them and save, the other one is blanked!!! Weird. Stay tuned. Tnx Egbert Jan.

**Comment by EgbertJan** [comment]
YES! Found the plugin. It is the Pronamic iDEAL plugin. When I disable it, order editing is OK again. This is a paid/licensed pluging and I cannot do without is; its the main payment vehicle. I'll try to explain my problem to them. I am not aware of another iDEAL plugin.
Egbert Jan

**Comment by mikejolley** [comment]
Ok, not sure why a gateway would touch existing orders but let us know how it goes :)

**Comment by EgbertJan** [comment]
Well, the plugin changes the state of the payment. In progress/failed/aborted by customer, etc. I got feedback from Pronamic: the problem is known and solved but is not announced yet (Easter holiday). Advise was to revert to the previous version, which I did.
Egbert Jan
