### ISSUE TITLE
Price display suffix not displayed after #14356 patch apply

### ISSUE THREAD

**Issue by bellonig** [woocommerce/woocommerce#14363]
### EXPLANATION OF THE ISSUE

 #14356 patch work for me but on variable product affected i cannot display the Price display suffix

### STEPS TO REPRODUCE THE ISSUE

apply   #14356 patch on clas-wc-product-variation.php

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: http://www.staging2.perlettidivingstore.it
Site URL: http://www.staging2.perlettidivingstore.it
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: Come aggiornare la versione di PHP
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: wp1e_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (16) ###

Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.43
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Order Numbers for WooCommerce: by Algoritmika Ltd – 1.0.1
Loco Translate: by Tim Whitlock – 2.0.13
Loginizer: by Raj Kothari – 1.3.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Woocomerce Brands Pro: by Proword – 4.2.0
Woo Import Export: by VJInfotech – 2.3
WooCommerce P.IVA e Codice Fiscale per Italia: by dot4all – 1.0.11
Woocommerce Advanced Bulk Edit: by George Iron – 4.1.1
WooSwatches - Woocommerce Color or Image Variation Swatches: by parbat chaudhari – 2.3.1
Woocommerce CSV Import: by Allaerd Mensonides – 3.3.5
WooCommerce Extra Charges To Payment Gateway (Standard): by hemsingh1 – 1.0.12.1
WooCommerce: by Automattic – 3.0.2 – 3.0.3 è disponibile
WooSidebars: by WooThemes – 1.4.3
YITH WooCommerce Wishlist: by YITHEMES – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
variation (variation)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2386 - /shop/
Carrello: #13 - /cart/
Cassa: #14 - /checkout/
My account: #15 - /account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
This one is intentional. Explained in the docblock here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-variable.php#L121-L125
