### ISSUE TITLE
Notice: id was called incorrectly. Product properties should not be accessed directly. 

### ISSUE THREAD

**Issue by withlovestudio** [woocommerce/woocommerce#14369]
### EXPLANATION OF THE ISSUE

Just upgrade WooCommerce two days ago - we use WeDevs/Dokan Multi-Vendor mod and now we are getting this error

Notice: id was called incorrectly. Product properties should not be accessed directly. Backtrace: require(‘wp-blog-header.php’), require_once(‘wp-includes/template-loader.php’), include(‘/plugins/dokan-lite/templates/store.php’), wc_get_template_part, load_template, require(‘/plugins/woocommerce/templates/content-product.php’), do_action(‘woocommerce_after_shop_loop_item’), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, user_logged_in_product_already_bought, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in ………/functions.php on line 4137

### STEPS TO REPRODUCE THE ISSUE

All we did was upgrade and woocommerce and the plugins

**Comment by Umangvaghela** [comment]
Hi @withlovestudio 

Accessing directly product data is not allowed, e.g. $product->id. Correct method going forward is $product->get_id().

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Deprecation-in-core#warnings-in-production-store-owners-read-this

Issue is in `/plugins/dokan-lite/templates/store.php`

**Comment by erakashpatel** [comment]
Hello,I got same error.

Can you please tell me where can i changed $product->get_id().?

**Comment by Umangvaghela** [comment]
Hello @erakashpatel 

whenever you get ID by global $product variable , there error are occurred. If you want to remove the error so find this and change on it by do it previous solution.

**Comment by erakashpatel** [comment]
Thanks for the very quick reply.

I got error like this 
:(

[20-Apr-2017 09:28:07 UTC] id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Payment_Gateways->get_available_payment_gateways, apply_filters('woocommerce_available_payment_gateways'), WP_Hook->apply_filters, call_user_func_array, WC_Subscriptions_Payment_Gateways::get_available_payment_gateways, WC_Subscriptions_Cart::cart_contains_subscription, WC_Subscriptions_Product::is_subscription, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.

So you means i need to changed all woocommerce $product variable?

**Comment by customwristbands** [comment]
Got the same problem.

**Comment by erakashpatel** [comment]
Hello customwristbands,  
In my case i fixed below way..you can try it,

Go to : /wp-content/plugins/woocommerce/includes
file name :class-wc-checkout.php
function name : protected function process_order_payment
 you can find it WC()->session->set( 'order_awaiting_payment', $order_id ); in that function just add before 
"//" OR removed this line.
I fixed that way.

may be its helps you.

Thanks
akashpatel

**Comment by customwristbands** [comment]
thanks @erakashpatel !

thanks for that super fast reply.. but isnt editing the plugin a bad practice? can i edit it using my child theme?

**Comment by erakashpatel** [comment]
Hello customwristbands,
Actually problem is here  "wp_woocommerce_session_{cookie}"
wp-content/plugins/woocommerce/includes/class-wc-session-handler.php:

While checkout. if this cookie is set then gives internal server error.
else its works.

Take a look it.I am not sure it's help you or not. 

Thanks
akashpatel

**Comment by mikejolley** [comment]
If setting a cookie gives an error, it means the headers have been sent by something (the notice most likely).

These deprecation notices need fixing in the plugins that cause it. Disable notices in production. See my comment above.

**Comment by carmenates09** [comment]
@erakashpatel Update with the before at "[20-Apr-2017 09:28:07 UTC] id was called incorrectly. Pro" log. There are the file with de problem and tell what's the line, in my case the problem was in 
"file ->  /home/username/site.domain.com/wp-content/plugins/woocommerce-multilingual/inc/class-wcml-cart.php  line 239"

Please, let me know to help you.

**Comment by erakashpatel** [comment]
Hello @carmenates09 

I followed @mikejolley  instruction . its due to header set cookie data .with wp_woocommerce_session_ cookie.
please followed that  instruction.


Thanks
akashpatel

**Comment by chem20** [comment]
Same Problem
How Can I Fix this
`[02-May-2017 14:29:17 UTC] virtual was called incorrectly.  Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->get_posted_data, WC_Checkout->get_checkout_fields, apply_filters('woocommerce_checkout_fields'), WP_Hook->apply_filters, call_user_func_array, custom_override_checkout_fields, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
`

**Comment by khadlock** [comment]
I had this exact issue, but resolved it by upgrading WooCommerce Subscriptions. It's unfortunate that these outdated plugins can completely break your checkout. Is there not a way to keep things backwards compatible?

**Comment by chem20** [comment]
update WooCommerce to version 3.0.5 but this error dont fix

**Comment by hossamhossny** [comment]
As @khadlock suggested, there are dozens of plugins depending on $product->id and am not sure how awful it is to have a production site broken over this non-backwards compatible change. In my case it was WooCommerce Subscriptions.

**Comment by mikejolley** [comment]
@hossamhossny Deprecation notices do not break backwards compatibility, yet.

https://github.com/woocommerce/woocommerce/wiki/Deprecation-in-core

^ Read this. And disable such notices in production as suggested.

**Comment by beekayjay** [comment]
**Please I have this issue with an e-commerce site I created, Please someone help out**

Notice: id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/porto/page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode_VC_Row->content, WPBakeryShortCode->loadTemplate, include('/themes/porto/vc_templates/vc_row.php'), wpb_js_remove_wpautop, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, vc_do_shortcode, WPBakeryShortCode->output, WPBakeryShortCode->content, WPBakeryShortCode->loadTemplate, include('/themes/porto/vc_templates/vc_column.php'), wpb_js_remove_wpautop, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, WC_Shortcodes::product_category, WC_Shortcodes::product_loop, wc_get_template_part, load_template, require('/themes/porto/woocommerce/ in /home/lynncou2/public_html/wp-includes/functions.php on line 4138

**Comment by mikejolley** [comment]
The link above explains this. Plugins need to update to remove the deprecated calls at some point.
