### ISSUE TITLE
[3.0] Virtual Orders no long copy shipping address

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#14364]
### EXPLANATION OF THE ISSUE

Prior to WooCommerce 3.0, orders that did not require shipping (ie all virtual items) did not prompt for this at checkout, but the billing address was still copied over to the shipping address.

In WooCommerce 3.0+, the shipping address fields will just be blank in this case instead rather than copying information from the billing address. 

This results in errors with certain payment gateways that require shipping addresses to be set, which were present in previous versions.

If this isn't going to be changed, then the 2.6 -> 3.0 migration notes should be updated to document this.

### STEPS TO REPRODUCE THE ISSUE

Place an order with only virtual items in WC 2.6 and WC 3.0 -- shipping fields are blank in the order admin and db in 3.0+.

**Comment by BurlesonBrad** [comment]
Just saw the same thing as well.

**Comment by mikejolley** [comment]
Seems to have been intentional. Added a note here: https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#virtual-orders-do-not-have-shipping-addresses And submitted a PR for a helper function to make detection easier going forward.

cc @claudiosanches
