### ISSUE TITLE
When I "Duplicate" A Product It Copied The Customer Reviews Also

### ISSUE THREAD

**Issue by jsmusiker** [woocommerce/woocommerce#14366]
### EXPLANATION OF THE ISSUE

Updated to the latest WC today...

Not sure if this is happening to everyone, but I just "duplicated" a product to save time, and it duplicated the customer reviews as well. 

- Under the product title it shows "3 Customer Reviews"
- In the reviews section again it says "3 Reviews"
- But then there are no actual reviews there.

Note: Duplicating a product should not duplicate reviews right?

There are no comments/reviews on the edit product page, so there is nothing for me to delete.

### STEPS TO REPRODUCE THE ISSUE

Duplicate a product that already has customer reviews.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

Shows 3 Reviews under the Title
![reviews-under-title](https://cloud.githubusercontent.com/assets/7741647/25033167/2327236c-20a9-11e7-8670-026b9af8c771.png)

And Then No Reviews Here
![review-section](https://cloud.githubusercontent.com/assets/7741647/25033179/45cdaf4e-20a9-11e7-892d-f05fd7210688.png)

**Comment by jsmusiker** [comment]
Shows 3 Reviews under the Title
![reviews-under-title](https://cloud.githubusercontent.com/assets/7741647/25033167/2327236c-20a9-11e7-8670-026b9af8c771.png)

And Then No Reviews Here
![review-section](https://cloud.githubusercontent.com/assets/7741647/25033179/45cdaf4e-20a9-11e7-892d-f05fd7210688.png)

**Comment by jsmusiker** [comment]
Hi @claudiulodro, If this is fixed in the next update, will that fix the products already duplicated? Or only going forward? Is there a way to delete the "3 Reviews" now? Thanks...

**Comment by claudiulodro** [comment]
@jsmusiker, the update won't fix the counts on products that have already been duplicated. It will fix the issue in the duplicator, though. 

The review counts will get recalculated to the correct amount as soon as someone leaves a review, so the easiest fix is going to be to post a review and then delete the review. You can do this now. Hope it wasn't too many products you duplicated! :)

**Comment by jsmusiker** [comment]
@claudiulodro, ah ok, that makes sense. I submitted a review and it's fixed! Thank you for you help.
