### ISSUE TITLE
Inconsistent parameters for callbacks on 'woocommerce_new_order_item' hook

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#14362]
The `'woocommerce_new_order_item'` hook is triggered in both WC < 3.0 and 3.0+; however, the parameters passed to callbacks on it are different between the different versions, and worse,  different in the same version depending on how it is being triggered.

Specifically:

1. `'woocommerce_new_order_item'` is triggered by both:
    1.1. `Abstract_WC_Order_Item_Type_Data_Store::create()` and
    1.1. `wc_add_order_item()` (which was done in WC < 3.0 and 3.0+)
1. when triggered by:
    1.1. `Abstract_WC_Order_Item_Type_Data_Store::create()`, the 2nd param, `$item`, will be an instance of a `WC_Order_Item`, because that's what that method requires as its parameter
   1.1. `wc_add_order_item()`, the 2nd param may be an array, because that's what that method requires as its parameter

Issue discovered when reviewing ZD ticket 558581.

**Comment by mikejolley** [comment]
Note to self; `wc_add_order_item` does indeed pass array, but also creates the item which will be an object. This needs to retrieve the object before firing the hook to be consistent. Array access will take care of the rest.
