### ISSUE TITLE
Possibility safing letters into sale price field

### ISSUE THREAD

**Issue by Ninos** [woocommerce/woocommerce#14365]
### EXPLANATION OF THE ISSUE
It's possible to add letters into the sale price field of the product on admin page.

### STEPS TO REPRODUCE THE ISSUE
Use firebug and add some letters into the value attribute of the field.

### SOLUTION
I recommend enhancing the function `wc_format_decimal()` by removing letters and all non-valid chars from price string.
Following preg_replace should solve this problem:
```$price = preg_replace( '/[^0-9\.]/', '', $price )```

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/14232

**Comment by Ninos** [comment]
For me it's not a js-error. Disabling js or manipulating the request will lead to same problem again. As described in #14232 I recommend adding the above `preg_replace()` to the `wc_format_decimal()`-function.

**Comment by claudiosanches** [comment]
@Ninos there is already validation for letters.

https://github.com/woocommerce/woocommerce/blob/master/includes/wc-formatting-functions.php#L256-L260

```
wp shell
wp> wc_format_decimal( 'Ninos' )
=> string(0) ""
wp> wc_format_decimal( 'Ninos.99' )
=> string(3) ".99"
wp> wc_format_decimal( '123Ninos.99' )
=> string(6) "123.99"
```

**Comment by Ninos** [comment]
Ahh, seems with 3.0 it's implemented now. Sry, did not checked enough. +1

**Comment by Ninos** [comment]
@claudiosanches I've found another small bug. You also need to do following:
```$number = str_replace( wc_get_price_thousand_separator(), '', $number );```

Reason:
```
wc_format_decimal( '12.345,99' ) -> 12.345.99
```
In germany we have `.` as thousand seperator and `,` as decimal seperator.

PS: Another solution would be removing all dots just not the last:
```$number = preg_replace( '/[.](?!\d*$)/', '', $number );```

**Comment by mikejolley** [comment]
@Ninos Look at the docblock:

> float|string $number Expects either a float or a string with a decimal separator only (no thousands)

We don't accept thousands chars.
