### ISSUE TITLE
Unable to hide item meta by key on emails

### ISSUE THREAD

**Issue by Dartui** [woocommerce/woocommerce#14372]
### EXPLANATION OF THE ISSUE

Inside order screen we can use [`woocommerce_hidden_order_itemmeta`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-order-item-meta.php#L2) filter to hide item meta by keys. There is no method to do this inside emails. What do you think about moving this filter to `WC_Order_Item::get_formatted_meta_data()`? [Order screen](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-order-item-meta.php#L15) and [emails](https://github.com/woocommerce/woocommerce/blob/master/templates/emails/email-order-items.php#L48) are using this function, so it could be filtered once for each. Hard to figure out how this will impact other things which are using `wc_display_item_meta` function (legacy API, payment gateways etc)

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Need to check what was used in 2.6 and apply the same filter if possible. Will look next week.

**Comment by mikejolley** [comment]
2.6 had woocommerce_order_items_meta_display
