### ISSUE TITLE
Payment Processing Shut Down

### ISSUE THREAD

**Issue by withlovestudio** [woocommerce/woocommerce#14370]
### EXPLANATION OF THE ISSUE

We upgraded to the latest version of WooCommerce and now none of our customers can order anything. Paypal will not work even though everything is correctly listed.

### STEPS TO REPRODUCE THE ISSUE

We can't figure out why this happened since all the information is the same since before the update and is current with our paypal account.

Customers get 'Internal Server Error'. Contacted GoDaddy since they are our server and nothing is wrong on their end. Even had them check the SSL cert.

**Comment by mikejolley** [comment]
> Internal Server Error

You need to look at the server error logs. A plugin will be causing 'fatal error' during the processing of the order.

**Comment by mikejolley** [comment]
@withlovestudio find it?

**Comment by mikejolley** [comment]
https://uk.godaddy.com/help/working-with-error-logs-1197

Also look in the site root, and wp-content directory for a file named debug_log. This can also give you the error message (500 is generic so we don't have enough information from just that alone).
