### ISSUE TITLE
500 Errors on Saving Posts & System Status Page

### ISSUE THREAD

**Issue by AntBentinck** [woocommerce/woocommerce#14377]
### EXPLANATION OF THE ISSUE

Sorry I'm posting this here simply because since (3.0.3) I haven't been able to save any products or been able to generate a system status report since (3.0).

Whenever I'm trying to save products I get a 500 Error. This has started happening directly after 3.0.3 however we have been getting 500 errors a lot since 2.6 when performing updates and generating system status pages. 

**UPDATE**: It seems the products are actually saving but its not getting through to the product updated status. going back and refreshing the products page shows the changes have actually saved.

### STEPS TO REPRODUCE THE ISSUE

Performing Updates (sporadic) since (2.6), Saving Products (3.0.3) and generating a system status page (3.00). File permissions look absolutely fine, server spec is perfect and resources barely flexing.

### SYSTEM STATUS

<details>
Unfortunately have not been able to produce system status report since 3.00
</details>

**Comment by mikejolley** [comment]
Error 500 is generic. To get a real error message one has to look at either the server error logs, or enable WP_DEBUG. Nothing we can do with just that info ^

**Comment by mikejolley** [comment]
@AntBentinck Any more info yet from that log?

**Comment by lauwqui** [comment]
I've been fighting with the same issues since 3.0
I don't know what to do...
With one product, everytime I try to change product data and save, it crashes the website for a few seconds/minutes, and my database takes 10 more MO..

**Comment by lauwqui** [comment]
The more I edit a product, the more there's more in my wp_postmeta.
If I edit a product like ten 10 times, I'll get 20000 rows.
I've disabled all other plugins, used a twenty theme to test, style nothing works !

**Comment by mikejolley** [comment]
@lauwqui that doesn't sound like the same issue. What postmeta is being created?

**Comment by mikejolley** [comment]
BTW I would suspect a plugin using `save_post` could cause a redirect like this - since the save event also uses wp_update_post which fires it's own `save_post`. Care must be taken to avoid this running multiple times.

**Comment by lauwqui** [comment]
![telechargement 2](https://cloud.githubusercontent.com/assets/16436030/25065692/0e9fe9ee-2214-11e7-9f3f-edef2d587655.png)

Thank you for your answer.
I disabled every other plugins, theme.. I don't see anything else that could interfere ?
Here's a screenshot showing there is 20000 rows now for one product ID 17773 it keeps adding more and more rows everytime I save. And after a few times editing/saving a product, it gets heavier and I can't edit anymore (product data anyway, I still can change the description but there is a error 500 then).

**Comment by mikejolley** [comment]
What plugin has prefix vc_? 

> I disabled every other plugins, theme..

That meta wouldn't be saved unless that plugin was active would it?

We have some protection against multiple save_post calls here https://github.com/woocommerce/woocommerce/blob/31cd2dcb904868658dcb4febd70e1081c3564a51/includes/admin/class-wc-admin-meta-boxes.php#L184-L221 and I think some plugins may not do this. I would like to prevent multiple save_post calls but we won't be doing this until 3.1, and it's not something new in 3.0 either.

**Comment by mensmaximus** [comment]
vc_ is visual composer. It is part of many 'premium' themes

**Comment by lauwqui** [comment]
VC_ should be Visual Composer I guess.
All these rows appeared when I had all my plugins enabled yes. It can't mean that all my plugin are in conflict with woocommerce, right? Take Revolution slider for instance.
Sure, they won't appear anymore if I don't have any plugins activated anymore but they sure might be a fix to that.

What do you mean by it's not something new in 3.0 either ?

Thank you for help and your quick reply anyway.

**Comment by lauwqui** [comment]
Why it worked with 2.6 and don't with 3.0 is a total mystery to me.

**Comment by lauwqui** [comment]
So, I made a test on my test server.
I updated to woocommerce 3.0 on my test server, and boom, not working.

Everytime I update/save my product, the number of rows almost double. 3176 -> 6254 -> 12404 .. etc
.. to a point that I get a error 500 and can't edit product data anymore.

Here's a pdf with all entries created exponantially in the db.
[wp_postmeta.pdf](https://github.com/woocommerce/woocommerce/files/923793/wp_postmeta.pdf)

**Comment by mikejolley** [comment]
@lauwqui so on your test server, does it double with a default theme active?

> Why it worked with 2.6 and don't with 3.0 is a total mystery to me.

Possibly just the extra 'save_posts' that can run when saving a product.

**Comment by mikejolley** [comment]
BTW if you send me a copy I can see what usage of save_post there is.

**Comment by lauwqui** [comment]
Hi again,

After multiple tests, one by one, I think I've found the culprit..

It seems that YITH Pre-order premium is responsible for this.

I explain myself:
For a unkown reason (for me anyway), this plugin duplicates rows indefinitely like I said, until the product is overloaded and changes can't apply.

The reason I thought  plugins were not in cause was because, even disabled, the damage on the edited products was already done. Which means that the only way to make it "work" normally again si to delete it or clean it manually in the databse.

I wish it wasn't this stupid.

**Comment by lauwqui** [comment]
It might eventually help the author of this post. It really seems like the same issue but he may not know the reason why.

**Comment by mikejolley** [comment]
Does that plugin have it's own meta box on the product screen?

**Comment by lauwqui** [comment]
![telechargement 1](https://cloud.githubusercontent.com/assets/16436030/25066428/5dbdb770-2225-11e7-97d0-78117d94b028.png)

Yes, it does

**Comment by mikejolley** [comment]
So this is indeed a conflict. I've put in https://github.com/woocommerce/woocommerce/issues/14415 for feedback to see if we can help mitigate the issue.

@AntBentinck as for your system status problem, I think it's a timeout or memory limit being hit. You would need to look at that error log or enable WP_DEBUG, look at the report, and let us know the error message. Comment back if you can do that - if not we don't have anything to go on. 

Thanks

**Comment by lauwqui** [comment]
Great !! It seems that you already found a solution to this !

**Comment by lauwqui** [comment]
I tested your changes, sadly, it doesn't seem to fix the issue in my case.

**Comment by mikejolley** [comment]
@lauwqui Then it's almost certainly a logic fail in the plugin you identified. I don't own the plugin, so I cannot check.

**Comment by lauwqui** [comment]
You're probably right.. Thank you for your help !
