### ISSUE TITLE
3.0 Variation downloads are not processed

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#14389]
For a single product in `class-wc-product-data-store-cpt.php` it reads the file downloads using the function read_downloads.

```
protected function read_downloads( &$product ) {
	$meta_values = array_filter( (array) get_post_meta( $product->get_id(), '_downloadable_files', true ) );

	if ( $meta_values ) {
		$downloads = array();
		foreach ( $meta_values as $key => $value ) {
			if ( ! isset( $value['name'], $value['file'] ) ) {
				continue;
			}
			$download    = new WC_Product_Download();
			$download->set_id( $key );
			$download->set_name( $value['name'] ? $value['name'] : wc_get_filename_from_url( $value['file'] ) );
			$download->set_file( apply_filters( 'woocommerce_file_download_path', $value['file'], $product, $key ) );
			$downloads[] = $download;
		}
		$product->set_downloads( $downloads );
	}
}
```

This calls the filter `woocommerce_file_download_path` which allows a plugin to change the download path, or parse it from a shortcode to an actual URL.

For a variation in `class-wc-product-variation-data-store-cpt.php` it reads the `_downloadable_files` directly from post meta and doesn't do any processing or call the filter `woocommerce_file_download_path`. https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L241

In 2.6 the filter was previously called from the abstract WC_Product class so it was called for a product variation as well.

It would seem that either the variation data store class would need to process the downloads the same way as is done for simple products. Or the code for processing the downloads would need to get moved back to the products class so it's called for variations containing downloads as well.

**Comment by astridsvs** [comment]
@claudiulodro when will 3.0.4 be released. Our shop has been down a several days now because of bugs in the variations. First taxes were charged double. Now with 3.0.3 shipping costs aren't charged. Will this be fixed in 3.0.4 cause we are loosing money now every day

**Comment by astridsvs** [comment]
or do you know @mikejolley ?

**Comment by mikejolley** [comment]
@astralbodies Apply it manually if you need it now https://github.com/woocommerce/woocommerce/pull/14387/files

**Comment by astridsvs** [comment]
Thanks @mikejolley
