### ISSUE TITLE
Product Add-ons saves &nbsp; with add-on price > issues in Excel

### ISSUE THREAD

**Issue by puregraphx** [woocommerce/woocommerce#14382]
I am using:
- Woocommerce 2.6.14
- WooCommerce Product Add-ons 2.8.0
- Mollie Payments for WooCommerce 2.5.4
all other plugins disabled and switched to the Twenty Seventeen theme.

When placing an order, the Product Add-on Price get's stored in the database as meta_key `Tomsgates installatieservice (&euro;&nbsp;130,00)` which at first seems fine, but when we export our orders, that non-braking space splits column A into 3 columns, which prevents the Text to Columns function in Excel, as columns B and C always get overwritten by column A.

There is no problem with free product add-ons as the system does not need to store a price.

<details>
### WordPress Environment ###

Home URL: http://tomsgates.puregraphx.be
Site URL: http://tomsgates.puregraphx.be
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.2.24 (Unix) mod_hive/5.5 mod_ssl/2.2.24 OpenSSL/1.0.0-fips mod_auth_passthrough/2.1 mod_bwlimited/1.4 mod_fastcgi/2.4.6 mod_fcgid/2.3.6
PHP Version: 5.6.30
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 24 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (3) ###

Mollie Payments for WooCommerce: by Mollie – 2.5.4
WooCommerce Product Add-ons: by WooCommerce – 2.8.0
WooCommerce: by WooThemes – 2.6.14

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page not set
Basket: #12 - /cart/
Checkout: #13 - /checkout/
My Account: #14 - /myaccount/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by mikejolley** [comment]
Export needs to wrap each value with quotes and escape the contents.  These are only htmlentities - there is nothing invalid with them.

I'm not sure what export you're using, but it needs to handle escaping. Please also note this is the core issue tracker - if you have issues with extensions, please use the helpdesk.

Thanks!

**Comment by puregraphx** [comment]
I am not saying that &nbsp; is invalid, I know it is a htmlentity and the problem is not with the export. In the meta_key there are 2 "normal" spaces for the label, but the space between the currency and the number gets stored as &nbsp; instead of " " like in the label and that prevents the Text to Columns in Excel, which I believe many people use to view exports.

**Comment by mikejolley** [comment]
The price formatting/currency in WC uses nbsp when you have currency symbol position to 'left with space'. Because wrapping this would be invalid. This entity is correct and should not be changed.
