### ISSUE TITLE
Twenty Seventeen: WooCommerce checkout details not readable in Dark color scheme

### ISSUE THREAD

**Issue by maheshprajapati** [woocommerce/woocommerce#14381]
With the Dark color scheme enabled some WooCommerce elements render with white text on white background. So far I've noticed:

Payment method details at checkout:
Screenshot: http://cld.wthms.co/wwk2

### STEPS TO REPRODUCE THE ISSUE

Enable Dark color scheme on any WooCommerce site,
Add a product to cart and proceed to checkout,
Observe how payment method descriptions show in white on white.

### SYSTEM STATUS

<details>
```
WordPress environment

Home URL: 		http://localhost/teststore
Site URL: 		http://localhost/teststore
WC version: 		3.0.2
Log directory writable: 		D:\wamp\www\teststore/wp-content/uploads/wc-logs/
WP version: 		4.7.3
WP multisite: 		–
WP memory limit: 		256 MB
WP debug mode: 		
WP cron: 		
Language: 		en_US

Server environment:

Server info: 		Apache/2.4.23 (Win64) PHP/5.6.25
PHP version: 		5.6.25
PHP post max size: 		250 MB
PHP time limit: 		12000
PHP max input vars: 		2500
cURL version: 		7.50.1, OpenSSL/1.0.1t
SUHOSIN installed: 		–
MySQL version: 		5.7.14	
Max upload size: 		250 MB
```
</details>

**Comment by maheshprajapati** [comment]
Hello emgk,
Your patch is correct and now working fine.

**Comment by emgk** [comment]
Sounds good. @maheshprajapati  👍

**Comment by avinapatel** [comment]
Hello @maheshprajapati 

Also, I have noticed that country and state field data is not readable with the dark color scheme. And, these fields should have the same gray background like other input fields on the checkout page for the dark color scheme. I have a attached a screenshots of it for reference.

Thanks,
![woocommerce-checkout-dark-color-scheme](https://cloud.githubusercontent.com/assets/27285861/25082755/7895bc7c-2370-11e7-9ec1-14cb85eda9b0.png)

**Comment by avinapatel** [comment]
#14433 Fixed country and state field data is not readable issue.

**Comment by avinapatel** [comment]
#14433

**Comment by maheshprajapati** [comment]
@avinapatel,
Yes you right and #14433 patch is right.

**Comment by avinapatel** [comment]
Thanks @maheshprajapati

**Comment by maheshprajapati** [comment]
Hello @avinapatel,@emgk,@claudiulodro,

I have resolve all checkout page color scheme issue in #14438

Thanks

**Comment by kalariak** [comment]
Hello @maheshprajapati , @mikejolley 
I have resolved the issue of checkout page dark color scheme in #14446 

Thank you.

**Comment by mikejolley** [comment]
All attempted fixes so far are either editing wrong files or changing more than is needed. SCSS needs to be changed, not CSS.

**Comment by kalariak** [comment]
Hello @maheshprajapati , @mikejolley 
I have formatted the SCSS file again and resolved the issue.
Thank you.

**Comment by mikejolley** [comment]
@kalariak no you have not :/

![2017-04-17 at 13 01](https://cloud.githubusercontent.com/assets/90977/25088416/16945a1c-236e-11e7-8e22-d4aacfca2b4c.png)

**Comment by avinapatel** [comment]
Hello @mikejolley, @maheshprajapati 

Please see my above commit and let me suggest if any further changes required.

Thanks,

**Comment by mikejolley** [comment]
@avinapatel I think that is fine. submit a PR and we can test it.

**Comment by avinapatel** [comment]
@mikejolley 

Please see the PR #14454 for this issue. 

Thanks,
