### ISSUE TITLE
trouble adding attribute to variable product in woocommerce

### ISSUE THREAD

**Issue by suesheppard** [woocommerce/woocommerce#14392]
### EXPLANATION OF THE ISSUE
When I try to add attributes to a variable product it just freezes large spinning black ball appears 
happened obth in older version and 3.0 of woocommerce

### STEPS TO REPRODUCE THE ISSUE
woocommerce/add  variable product/add attribute 

### SYSTEM STATUS

<details>
````
### WordPress Environment ###

Home URL: http://fantasyshopping.co.uk
Site URL: http://fantasyshopping.co.uk
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 32 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.21.3 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.26
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wpbn_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (14) ###

LayerSlider WP: by Kreatura Media – 6.1.0
Backup: by BackupGuard – 1.1.37
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

Contact Form 7: by Takayuki Miyoshi – 4.7
Flexible Shipping: by WP Desk – 1.9
Fusion Builder: by ThemeFusion – 1.0.6
Fusion Core: by ThemeFusion – 3.0.6
Slider Revolution: by ThemePunch – 5.3.1.5
TablePress: by Tobias Bäthge – 1.8
WooCommerce: by Automattic – 3.0.3
Yoast SEO: by Team Yoast – 4.6
WP Fastest Cache: by Emre Vona – 0.8.6.8
Yoast SEO: WooCommerce: by Team Yoast – 4.6
Google XML Sitemap Generator: by XmlSitemapGenerator.org – 1.3.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Basket: #16564 - /cart/
Checkout: #16586 - /checkout/
My account: #16576 - /my-account/

### Theme ###

Name: Avada
Version: 5.0.6
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.0.2
Avada/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.0.2
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌Learn how to update
`
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

<!--
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
-->

**Comment by claudiulodro** [comment]
What testing have you done with just WooCommere active?
```
Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
```

**Comment by suesheppard** [comment]
sorry bear with me I am new to all this can you explain ohw I - Switch to Twenty Twelve theme to ensure it's a core bug and not a theme issue.

**Comment by suesheppard** [comment]
i do have a message saying the Your theme (Avada) contains outdated copies of some WooCommerce template files. These files may need updating to ensure they are compatible with the current version of WooCommerce. You can see which files are affected from the system status page. If in doubt, check with the author of the theme.

Is this the reason ?? what do I need ot do

**Comment by claudiulodro** [comment]
@suesheppard first thing you should try is deactivating all plugins except for WooCommerce and see if you can successfully add attributes to a variable product. 

If the problem doesn't happen with other plugins deactivated, the problem is going to be caused by one of those plugins. Go through each plugin one-by-one, turn it on, and see if the problem happens. When the problem starts happening again, that's going to be your problem plugin.

**Comment by suesheppard** [comment]
Tested all the active plug ins deactivated and then tried adding attribute to variable product no joy I'm afraid that ball keeps on spinning 

found this is it of any significance 
Your theme (Avada) contains outdated copies of some WooCommerce template files. These files may need updating to ensure they are compatible with the current version of WooCommerce. You can see which files are affected from the system status page. If in doubt, check with the author of the theme.

**Comment by jazerlaser** [comment]
Got the same problem ... did switch to standard theme and disabled almost all the plugins. No succes so far. Use the square theme ... I have seen many people with the same problem in the forums. 

If i disable all the plugins and the problem stays, what is the solution in that case to fix this problem?

**Comment by mikejolley** [comment]
@suesheppard Do a final test with a different theme active (use a default WP theme like Twenty Twelve). If it still fails, if you contact me with access creds I'll take a look into it.

**Comment by suesheppard** [comment]
I afraid I made a fatal rookie error I tried ot update theme that went wrong I tried a back up using backup guard this got ot 51% and stopped completely I have now lost the whole thing - my web designer said if I can access the ftp details that may solve things is there a way of finding these or anyway of getting the system back up and running. Otherwise its start form scratch not really wanting to do that. This might be my last woocommerce site  I do say that the help system is woefully inadequate it was either pay my webdesigner when everything went wrong or try to fix it myself . Even I didn't beleivei t was so touchy that it could all go up in a puff of smoke.

**Comment by suesheppard** [comment]
all I get as I try to log in now is an error 500

**Comment by mikejolley** [comment]
So your backup was half complete? If the database is intact, renaming the wp-content/plugins and wp-content/themes directory via FTP, then logging in, then renaming them back will get you back into WP with all themes/plugins off. 

http://www.wpbeginner.com/plugins/how-to-deactivate-all-plugins-when-not-able-to-access-wp-admin/

**Comment by suesheppard** [comment]
yes but I closed the browser window

**Comment by suesheppard** [comment]
FTP need the log in details then

**Comment by suesheppard** [comment]
will I be able ot get them form my host ??

**Comment by mikejolley** [comment]
Yes.

**Comment by suesheppard** [comment]
thanks so some hope I hope it may be ok I learnt a big lesion today either way I am new ot woo and wp and it is just os deep you need a degree to know it

**Comment by suesheppard** [comment]
I managed to log in via my host and found the folders and files they are still there I renamed the plugins plugins.decactivate but still got the dread white screen of dead.

**Comment by mikejolley** [comment]
Repeat for the theme directory. If it's still broken I don't know what your backup plugin did :(

May want to consider https://vaultpress.com/ for future - this is offsite.

**Comment by suesheppard** [comment]
I have found this from april 10th  fantasys_hopping_2017-04-10_13-47-12.sql.zip

**Comment by jazerlaser** [comment]
For me it was the twitterfeed plugin that causes the problem ...

**Comment by mikejolley** [comment]
At this point you may want to see if the host can do a restore to a previous date. I don't know if you're missing files, or it's just a DB backup restore that failed. It depends what was running when you said it stopped at 51%. 

Usually in cases of white screens you'd just look at error logs or enable debugging https://codex.wordpress.org/Debugging_in_WordPress but it sounds like your issues are more serious.

**Comment by suesheppard** [comment]
did that the log in has reappeared but when I tried to log in it said Invalid post type.

**Comment by suesheppard** [comment]
got it back today had ot get web designer took him 4 hours still not sure what caused originl rpoblem with variable and attribute freezing

**Comment by nickmarlou** [comment]
i have the same issue with attribute freezing. today i am gonna to check my plugins.

**Comment by suesheppard** [comment]
i think our issue was the themes but as my knowledge wasn't that great I left it ot my web guy

**Comment by mikejolley** [comment]
@suesheppard if you can get them to comment here what the cause was that would be good - just to check we don't need to fix anything our side.

Thanks!

**Comment by yonjuukyuu** [comment]
Must likely is the select2 problem , plugins js conflict https://wordpress.org/support/topic/3-0-error-option-ajax-is-not-allowed-for-select2/

**Comment by kprovance** [comment]
So...by reading that link.  ALl plugins that cause WC to not function properly must take the dev time to upgrade to select2 4.x?  I mean, I feel like that's what they are saying.  Our way ro 'oh well'  Since some option frameworks still use select2 3.x, you're not giving them much of a choice except to waste dev time on a not so needed upgrade.  Hardly seems fair.  Ever heard of shims as not to break your own stuff, or the stuff of others?  Based on how often those templates change and breaks things, I'm doubtin' it.  :(

**Comment by claudiulodro** [comment]
@kprovance, @yonjuukyuu the latest version of WooCommerce (3.0.3) has checks in place to prevent the whole site from breaking if old versions of select2 are being used. See #14029.

**Comment by kprovance** [comment]
I see.  So, that would explain this?

```
select2.js?ver=3.5.2:930 
Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.(anonymous function) @ select2.js?ver=3.5.2:930
n.extend.each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
clazz.prepareOpts @ select2.js?ver=3.5.2:928
clazz.prepareOpts @ select2.js?ver=3.5.2:2601
clazz.init @ select2.js?ver=3.5.2:690
(anonymous function) @ select2.js?ver=3.5.2:3391
n.extend.each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
n.fn.n.each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
$.fn.select2 @ select2.js?ver=3.5.2:3378
(anonymous function) @ wc-enhanced-select.min.js?ver=3.0.3:1
n.extend.each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
n.fn.n.each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
(anonymous function) @ wc-enhanced-select.min.js?ver=3.0.3:1
n.event.dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:3
r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:3
n.event.trigger @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:3
a.event.trigger @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:9
(anonymous function) @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:3
n.extend.each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
n.fn.n.each @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
n.fn.extend.trigger @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:3
(anonymous function) @ meta-boxes-product.min.js?ver=3.0.3:1i @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
j.fireWith @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2
y @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:4
c @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:4
```

When attempting to an attribute to a variable product

WC 3.0.3
WP 4.3.7

All of this stems from WC and Redux Framework running into one another, and our users suggesting we add inputs to our code to fix this.

https://github.com/reduxframework/redux-extensions/issues/327

**Comment by yonjuukyuu** [comment]
In my case, it was in attempting to add attribute to a variable product had that same error as well , WC 3.0.3, fixed by upgrading the ACF PRO to latest version believe that one last version still using that select2 3x

**Comment by mikejolley** [comment]
@kprovance afaik there are no shims for v3 and v4 compatibility. v4 has different requirements for the markup itself (i.e. select boxes instead of hidden inputs).

**Comment by monaye** [comment]
I am still having the same issues. When trying to edit the Variations, Woocomerce hangup and see following error on console.  Woocommerce version is 3.0.4. 
`Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.`
After doing some google search, I can see a lot of people are having same errors recently, after upgrading to Woocommerce version 3.

**Comment by kprovance** [comment]
They broke a LOT of stuff with three.  A *lot*.  :(

**Comment by mikejolley** [comment]
As stated above, this can happen when a plugin uses select2 v3 and loads it on WooCommerce screens. WooCommerce uses v4. The two are not compatible, and there is no possible shim to *make* them compatible. Downgrading to v3 is not an option.

To find the conflict you can either:

1. View the page source, find the select2.js/select2.min.js file and see where it comes from (it may be in a plugin directory)
2. Disable plugins/switch to default theme and re-enable things until the conflict occurs.

Authors can load select2 conditionally in the admin area, or use v4.

Since there are 2 incompatible versions in circulation, and any theme/plugin can choose to use either, these types of conflicts are inevitable - it just so happens that WC has more installs so the issue is not as rare now.

We're going to look into forking the library or wrapping it so we have a custom version which cannot conflict, but this will not be done any time soon.

I'm closing this thread since I've answered this a few times now and have given instructions to rectify.
