### ISSUE TITLE
Duplicate gallery thumbnail when featured image added to product gallery

### ISSUE THREAD

**Issue by wpexplorer** [woocommerce/woocommerce#14395]
### EXPLANATION OF THE ISSUE

If the main featured image for a product is also added to the product gallery metabox for some reason, it will display twice in the gallery thumbnails. This can be prevented easily by altering product-thumbnails.php and adding the following within the loop:

```
if ( get_post_thumbnail_id() == $attachment_id ) {
    continue;
}
```

### STEPS TO REPRODUCE THE ISSUE

1. Create new product
2. Set featured image
2. Add featured image to product gallery as well

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://localhost/new-york
Site URL: http://localhost/new-york
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.0
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: wp_308_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

WaspThemes - Yellow Pencil Pro: by WaspThemes – 5.5.5
WooCommerce: by Automattic – 3.0.2 – 3.0.3 is available
WPEX User Social Profiles: by WPExplorer – 1.0
Theme Check: by Otto42
pross – 20160523.1

WPEX Local User Avatar: by Aj Clarke – 1.0.0
Disable Embeds: by Pascal Birchler – 1.3.0
ThemeForest-Check: by Japh – 1.0.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #75 - /shop/
Cart: #76 - /shop/cart/
Checkout: #77 - /shop/checkout/
My account: #78 - /shop/my-account/

### Theme ###

Name: WPEX New York
Version: 1.4.0
Author URL: http://www.wpexplorer.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
If added twice, yes this will happen and should happen? You've set both. This should be clearer and more noticeable after https://github.com/woocommerce/woocommerce/issues/13071 since the panels will be combined.

**Comment by maxgx** [comment]
i had the same issue using the FG Prestashop to WooCommerce plugin to transfer data from a PrestaShop install to WooCommerce.

one of the settings asks if you want to use the Featured Image in the product gallery too. if by chance you worry about the image not showing up in gallery and enable the option, you end up with the Featured Image being the first of the gallery, then repeated a second time because the attachment is also part of the gallery.

if you try to remove it from the gallery, both images (Featured and the same as attachment) are removed.

the code above does solve the issue.

**Comment by jsolorzano0209** [comment]
Hi there, sorry for opening this one up, but I tried adding the code mentioned to product-thumbails.php file but still no luck. 

I added it this way:

<?php
/**
 * Single Product Thumbnails
 *
 * This template can be overridden by copying it to yourtheme/woocommerce/single-product/product-thumbnails.php.
 *
 * HOWEVER, on occasion WooCommerce will need to update template files and you
 * (the theme developer) will need to copy the new files to your theme to
 * maintain compatibility. We try to do this as little as possible, but it does
 * happen. When this occurs the version of the template file will be bumped and
 * the readme will list any important changes.
 *
 * @see 	    https://docs.woocommerce.com/document/template-structure/
 * @author 		WooThemes
 * @package 	WooCommerce/Templates
 * @version     3.1.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

global $post, $product;

$attachment_ids = $product->get_gallery_image_ids();

if ( $attachment_ids && has_post_thumbnail() ) {
    
    
   
    foreach ( $attachment_ids as $attachment_id ) {
        if ( get_post_thumbnail_id() == $attachment_id ) {
            continue;
        }
		$full_size_image = wp_get_attachment_image_src( $attachment_id, 'full' );
		$thumbnail       = wp_get_attachment_image_src( $attachment_id, 'woocommerce_thumbnail' );
		$attributes      = array(
			'title'                   => get_post_field( 'post_title', $attachment_id ),
			'data-caption'            => get_post_field( 'post_excerpt', $attachment_id ),
			'data-src'                => $full_size_image[0],
			'data-large_image'        => $full_size_image[0],
			'data-large_image_width'  => $full_size_image[1],
			'data-large_image_height' => $full_size_image[2],
		);
        $html  = '<div data-thumb="' . esc_url( $thumbnail[0] ) . '" class="woocommerce-product-gallery__image"><a href="' . esc_url( $full_size_image[0] ) . '">';
		$html .= wp_get_attachment_image( $attachment_id, 'woocommerce_single', false, $attributes );
 		$html .= '</a></div>';

		echo apply_filters( 'woocommerce_single_product_image_thumbnail_html', $html, $attachment_id );
        
	}
    }

I've tried several methods and also tried css, but still can get this one to work. Any ideas? (using the plugin WPIS- woocommerce product image slider for gallery)
