### ISSUE TITLE
WooCommerce Pre-Order 1.4.9 Fatal Error after 3.0.3 update

### ISSUE THREAD

**Issue by dweuste** [woocommerce/woocommerce#14391]
When editing an order and attempting to re-send a customer email or regenerate downloads, if WooCommerce Pre-Orders (Version 1.4.9) is enabled, the following is triggered:

Fatal error: Uncaught Error: Call to a member function get_id() on boolean in /wp-content/plugins/woocommerce-pre-orders/includes/admin/class-wc-pre-orders-admin-orders.php:85 Stack trace: #0 /wp-includes/class-wp-hook.php(300): WC_Pre_Orders_Admin_Orders->check_manual_order_for_pre_order_products(7516) #1 /wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(true, Array) #2 /wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /wp-includes/post.php(3505): do_action('save_post', 7516, Object(WP_Post), true) #4 /wp-includes/post.php(3578): wp_insert_post(Array, false) #5 /wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order- in /wp-content/plugins/woocommerce-pre-orders/includes/admin/class-wc-pre-orders-admin-orders.php on line 85

With Pre-Orders deactivated, everything works as it should.

### STEPS TO REPRODUCE THE ISSUE

1. Activate Pre-Orders plugin
2. Attempt to regenerate an email or download permissions from Edit Order screen
3. Deactivate Pre-Orders plugin
4. Repeat step 2.

### SYSTEM STATUS

<details>
WordPress environment
WC version:		3.0.3
Log directory writable:		 /wp-content/uploads/wc-logs/
WP version:		4.7.3
WP multisite:		–
WP memory limit:		64 MB
WP debug mode:		–
WP cron:		
Language:		en_US
Server environment
Server info:		Apache/2.4.25 (Unix) OpenSSL/1.0.2g
PHP version:		7.0.17
PHP post max size:		1 GB
PHP time limit:		30
PHP max input vars:		5000
cURL version:		7.47.0, OpenSSL/1.0.2g
SUHOSIN installed:		–
MySQL version:		5.7.17
Max upload size:		512 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.3
Database prefix	 	rrllcwprr_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 /wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		
Hide errors from visitors		
Active plugins (27)
Gravity Forms	 	by rocketgenius – 2.2.1
All In One SEO Pack Pro	 	by Michael Torbert – 2.4.12.1
WP Offload S3	 	by Delicious Brains – 1.4
WP Offload S3 - WooCommerce Addon	 	by Delicious Brains – 1.0.7
Amazon Web Services	 	by Delicious Brains – 1.0.2
BackupBuddy	 	by iThemes – 7.3.1.0
Better Internal Link Search	 	by Cedaro – 1.3.0
Easy Theme and Plugin Upgrades	 	by Chris Jean – 2.0.0
Gravity Forms MailChimp Add-On	 	by rocketgenius – 4.2
Gravity Forms Polls Add-On	 	by Rocketgenius – 3.1
iThemes Security Pro	 	by iThemes – 3.7.4
Jetpack by WordPress.com	 	by Automattic – 4.8.2
Pods - Custom Content Types and Fields	 	by Pods Framework Team – 2.6.8
Rotating Tweets (Twitter widget & shortcode)	 	by Martin Tod – 1.9
SearchWP	 	by SearchWP, LLC – 2.8.7
WooCommerce Cart Reports	 	by WPBackOffice – 1.1.13
WooCommerce Dynamic Pricing	 	by Lucas Stark – 3.0.1
WooCommerce Stripe Gateway	 	by WooCommerce – 3.1.6
WooCommerce MailChimp Integration	 	by WooCommerce – 1.0.2
WooCommerce PDF Invoices & Packing Slips	 	by Ewout Fernhout – 1.6.4
WooCommerce Product CSV Import Suite	 	by WooCommerce – 1.10.14
WooCommerce USPS Shipping	 	by WooCommerce – 4.4.5
WooCommerce Smart Coupons	 	by StoreApps – 3.2.1
WooCommerce Table Rate Shipping	 	by Automattic – 3.0.2
WooCommerce	 	by Automattic – 3.0.3
WP Retina 2x	 	by Jordy Meow – 4.8.0
WP Rocket	 	by WP Media – 2.9.11
Settings
API enabled:		
Force SSL:		
Currency		USD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), subscription (subscription), variable (variable), variable subscription (variable-subscription)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#8 - /catalog/
Cart:		#9 - /cart/
Checkout:		#10 - /checkout/
My account:		#11 - /my-account/
Theme
Child theme:		Custom
Parent theme name:		Parker
Parent theme version:		5.1.4
Parent theme author URL:		http://ithemes.com/
WooCommerce support:		
Templates
Overrides	 /woocommerce/archive-product.php, 
/woocommerce/cart/cart-empty.php, 
/woocommerce/cart/cart-item-data.php, 
/woocommerce/cart/cart-shipping.php, 
/woocommerce/cart/cart-totals.php, 
/woocommerce/cart/cart.php, 
/woocommerce/cart/mini-cart.php, 
/woocommerce/cart/proceed-to-checkout-button.php, 
/woocommerce/cart/shipping-calculator.php, 
/woocommerce/checkout/form-checkout.php, 
/woocommerce/checkout/payment-method.php, 
/woocommerce/checkout/review-order.php, 
/woocommerce/content-product.php, 
/woocommerce/content-single-product.php, 
/woocommerce/content-widget-product.php, 
/woocommerce/emails/email-header.php, 
/woocommerce/emails/email-styles.php, 
/woocommerce/loop/add-to-cart.php, 
/woocommerce/loop/loop-end.php, 
/woocommerce/loop/loop-start.php, 
/woocommerce/loop/no-products-found.php, 
/woocommerce/loop/orderby.php, 
/woocommerce/loop/pagination.php, 
/woocommerce/loop/price.php, 
/woocommerce/loop/sale-flash.php, 
/woocommerce/order/order-details-item.php, 
/woocommerce/order/order-details.php, 
/woocommerce/single-product/rating.php, 
/woocommerce/single-product/related.php, 
/woocommerce/single-product/sale-flash.php, 
/woocommerce/single-product/share.php, 
/woocommerce/single-product/short-description.php, 
/woocommerce/single-product/title.php, 
/woocommerce/single-product-reviews.php, 
/woocommerce/single-product.php, 
/woocommerce/taxonomy-product_cat.php, 
/woocommerce/taxonomy-product_tag.php

</details>

**Comment by genehighley** [comment]
I am having the same issues can't change a products preorder info and if I try to trash a product get error as above.

**Comment by mikejolley** [comment]
I've logged in the correct place and notified the devs.

**Comment by dweuste** [comment]
@gedex Thank you!
