### ISSUE TITLE
DASHBOARD: Orders summary SHIP TO link to Google results in "Not Found" .. 

### ISSUE THREAD

**Issue by thehoffr** [woocommerce/woocommerce#14398]
### EXPLANATION OF THE ISSUE

PROBLEM: From admin > wc > orders > [Ship to] (Google Maps) link (includes CUSTOMER NAME resulting in map "not found".   
FIX: Starting the "link" at the STREET will exclude the customer name for a valid map result.  Map is high value for this feature.

### STEPS TO REPRODUCE THE ISSUE

  See any valid address under dashboard.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by claudiulodro** [comment]
I've confirmed the generated Google Maps link from "Ship to" is no good.

**Comment by mattyza** [comment]
I've confirmed this as well. Removing the customer name from the generated link, and focusing purely on the address, remedies this.

**Comment by thehoffr** [comment]
I just updated the file with your fix and it works great.  I sell a product for rolling solar covers and helps to see the home instantly with your now working link.  Thanks you guys for such prompt fixes,  Very impressive!  I'm and ex-Oracle DBA gone rogue inventor haha.
