### ISSUE TITLE
Filter for modifying Photoswipe options (improvement)

### ISSUE THREAD

**Issue by wpexplorer** [woocommerce/woocommerce#14393]
### EXPLANATION OF THE ISSUE

When looking at single-product.js it doesn't appear that there is any way to hook into the Photoswipe options to alter them via a child theme/plugin. For example to add an opacity to the lightbox would require using the bgOpacity option during Photoswipe init as it can't be adjusted via CSS according to the Photoswipe docs. It would be nice to have the ability to alter any of the Photoswipe options. This can be done by localizing the script. I'll be submitting a pull request shortly. This issue is being added as a way to properly follow the "guidelines for contributing".

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://localhost/new-york
Site URL: http://localhost/new-york
WC Version: 3.0.2
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.0
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.2
WC Database Prefix: wp_308_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

WaspThemes - Yellow Pencil Pro: by WaspThemes – 5.5.5
WooCommerce: by Automattic – 3.0.2 – 3.0.3 is available
WPEX User Social Profiles: by WPExplorer – 1.0
Theme Check: by Otto42
pross – 20160523.1

WPEX Local User Avatar: by Aj Clarke – 1.0.0
Disable Embeds: by Pascal Birchler – 1.3.0
ThemeForest-Check: by Japh – 1.0.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #75 - /shop/
Cart: #76 - /shop/cart/
Checkout: #77 - /shop/checkout/
My account: #78 - /shop/my-account/

### Theme ###

Name: WPEX New York
Version: 1.4.0
Author URL: http://www.wpexplorer.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14394 We'll consider for 3.1
