### ISSUE TITLE
Cannot access wp-admin/admin.php?page=wc-status

### ISSUE THREAD

**Issue by sugandaaa** [woocommerce/woocommerce#14406]
After update to woocommerce 3.0.3 cannot access this page wp-admin/admin.php?page=wc-status. How to fix this?

**Comment by mikejolley** [comment]
Timeout? Think you're out of memory? There are a few remote posts on this page to test functionality is working so it can load slowly.

**Comment by mikejolley** [comment]
Need more details. I think you'll find you're hitting memory limit - error log will give you details.

**Comment by voxoff79** [comment]
i Have a very strange issue a cannot access wp-admin/admin.php?page=wc-status. 
I get a 404 response. I only see this page once the first time i install the plug-in the next day in i always get this 404 response. i can access the admin.php?page=wc-status&tab=tools and =logs but no the System status page! i already uninstall / install the plug in again. I even install another wordpress web site in my shared hosted webserver but I get the same problem!

Do you have any clue how can i troubleshoot this issue!! 

Thank ypu in advance

**Comment by mikejolley** [comment]
Possibly a timeout since that status page makes remote requests to test that is working.

**Comment by voxoff79** [comment]
Thansk mikejolley for your quick reply!

But i get a 404 (page not found), i already change my max_execution_time to 300, same 404 response.

But for example if i copy the code in html-admin-page-status-report.php to one of my page i can see the resport!  

Any advice?

thnks

WordPress environment
Home URL:		https://www.brunodasilva.pt
Site URL:		https://www.brunodasilva.pt/byfoot
WooCommerce version:		3.3.5
Log directory writable:		/home/brphotog/public_html/byfoot/wp-content/uploads/wc-logs/
WordPress version:		4.9.5
WordPress multisite:		–
WordPress memory limit:		128 MB
WordPress debug mode:		–
WordPress cron:		
Language:		en_US
External object cache:		–
Server environment
Server info:		Apache
PHP version:		5.6.36 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP post max size:		8 MB
PHP time limit:		300
PHP max input vars:		1000
cURL version:		7.54.0, OpenSSL/1.0.2k
SUHOSIN installed:		–
MySQL version:		5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max upload size:		2 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WooCommerce database version:		3.3.5
Database prefix	 	wp_
MaxMind GeoIP database:		The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: /home/brphotog/public_html/byfoot/wp-content/uploads/GeoIP.dat. Scroll down to "Downloads" and download the "MaxMind DB binary, gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.
Total Database Size	 	5.34MB
Database Data Size	 	4.57MB
Database Index Size	 	0.77MB
wp_woocommerce_sessions	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta	 	Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log	 	Data: 0.00MB + Index: 0.00MB
wp_commentmeta	 	Data: 0.00MB + Index: 0.01MB
wp_comments	 	Data: 0.02MB + Index: 0.01MB
wp_links	 	Data: 0.00MB + Index: 0.00MB
wp_ngg_album	 	Data: 0.00MB + Index: 0.00MB
wp_ngg_gallery	 	Data: 0.00MB + Index: 0.00MB
wp_ngg_pictures	 	Data: 0.00MB + Index: 0.00MB
wp_options	 	Data: 1.69MB + Index: 0.17MB
wp_postmeta	 	Data: 1.07MB + Index: 0.26MB
wp_posts	 	Data: 1.70MB + Index: 0.20MB
wp_termmeta	 	Data: 0.00MB + Index: 0.01MB
wp_terms	 	Data: 0.01MB + Index: 0.02MB
wp_term_relationships	 	Data: 0.01MB + Index: 0.02MB
wp_term_taxonomy	 	Data: 0.01MB + Index: 0.01MB
wp_usermeta	 	Data: 0.02MB + Index: 0.02MB
wp_users	 	Data: 0.00MB + Index: 0.01MB
wp_wc_download_log	 	Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks	 	Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links	 	Data: 0.02MB + Index: 0.01MB
wp_yoast_seo_meta	 	Data: 0.02MB + Index: 0.02MB
Post Type Counts
attachment	 	345
custom_css	 	1
customize_changeset	 	264
grid_template	 	6
jetpack-portfolio	 	21
jetpack-testimonial	 	2
nav_menu_item	 	147
ngg_gallery	 	2
ngg_pictures	 	8
oembed_cache	 	3
page	 	27
post	 	41
revision	 	452
sell_media_item	 	3
sell_media_payment	 	3
Security
Secure connection (HTTPS):		
Hide errors from visitors		
Active plugins (4)
JP Sharing	 	by JP – 3.9.6
Shapely Companion	 	by Colorlib – 1.0.5
WooCommerce	 	by Automattic – 3.3.5
Yoast SEO	 	by Team Yoast – 7.4.2
Settings
API enabled:		
Force SSL:		–
Currency		EUR (€)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WooCommerce pages
Shop base:		#5832 - /shop/
Cart:		#5691 - /cart/
Checkout:		#5692 - /checkout/
My account:		#5693 - /my-account/
Terms and conditions:		Page not set
Theme
Name:		Shapely
Version:		– 1.2.2 is available
Author URL:		https://colorlib.com/
Child theme:		– If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Overrides	 	shapely/woocommerce/archive-product.php, 
shapely/woocommerce/content-product.php, 
shapely/woocommerce/single-product.php

**Comment by anhdq1801** [comment]
@voxoff79  I have same issue. Could you tell me how you solve the issue.

Thanks

**Comment by petervangorder** [comment]
I have the same issue as well.  

It sure would be great if the people who came here for help, and then found a solution, could post said solution!

 : )
 
 Pretty please.
