### ISSUE TITLE
Setting Product to Featured does not seem to work.

### ISSUE THREAD

**Issue by vlaskiz** [woocommerce/woocommerce#14403]
### EXPLANATION OF THE ISSUE

I am under WooCommerce 3.0.3 version. I have set few products to feautred by ticking the star icon. It's blue and all. Now I use custom WP query to get these products on my front page template. Query seems proper, tried few variants, but that can be set aside - I have went to database to check where these specific products meta_value is "yes" for meta_key "_featured" - and it's not.

Tried un-ticking and ticking the start again, no change.

After manually changing meta_value of specific product to "yes", it shows up via my custom WP query.

My Query:
`				$args2 = array(
					'post_type'   	=> 'product',
					'post_status' 	=> 'publish',
					'stock'      	=> 1,
					'showposts'  	=> 4,
					'orderby'    	=> 'menu_order',
					'order'      	=> 'DESC',
					'meta_key'		=> '_featured',
					'meta_value'	=> 'yes',
					'meta_query'	=> array(
						'relation' => 'AND',
						array(
							'key'           => '_visibility',
							'value'         => array('catalog', 'visible'),
							'compare'       => 'IN'
						),
						array(
							'key'   	=> '_featured',
							'value' 	=> 'yes'
						)
					)
				);`

<details>
`
### WordPress Environment ###

Home URL: http://squarepixel.lt/biovaistine
Site URL: http://squarepixel.lt/biovaistine
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: lt_LT

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: biv0_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (32) ###

Query Monitor: pridėjo John Blackbourn – 2.13.4
ACF Content Analysis for Yoast SEO: pridėjo ViktorFroberg
marol87
pekz0r
angrycreative – 1.2.6

Advanced Custom Fields: YouTube Picker: pridėjo Aires Gonçalves – 3.1.0
Admin Customizer: pridėjo Nilambar Sharma – 2.0
Admin Menu Editor Pro: pridėjo Janis Elsts – 2.4.3
Advanced Custom Fields: Nav Menu Field: pridėjo Faison Zutavern – 2.0.0
Advanced Custom Fields PRO: pridėjo Elliot Condon – 5.5.11
Contact Form 7 Honeypot: pridėjo Nocean – 1.10
Contact Form 7: pridėjo Takayuki Miyoshi – 4.7
Custom Post Type Permalinks: pridėjo Toro_Unit – 3.1.1
Custom Post Type UI: pridėjo WebDevStudios – 1.5.3
Custom Related Products for WooCommerce: pridėjo Scott Nelle – 1.3
Disable XML-RPC: pridėjo Philip Erb – 1.0.1
Show IDs by Echo Plugins: pridėjo Echo Plugins – 1.0.0
Force Regenerate Thumbnails: pridėjo Pedro Elsner – 2.0.6
Limit Login Attempts: pridėjo Johan Eenfeldt – 1.7.1
Maintenance: pridėjo fruitfulcode – 3.4.1
Newsletter: pridėjo Stefano Lissa & The Newsletter Team – 4.8.9
Post Types Order: pridėjo Nsp Code – 1.9.3
Responsive Lightbox - PhotoSwipe: pridėjo dFactory – 1.0.4
Responsive Lightbox: pridėjo dFactory – 1.6.12
TinyMCE Advanced: pridėjo Andrew Ozz – 4.4.3
User Role Editor: pridėjo Vladimir Garagulya – 4.32.3
Woocomerce Brands Pro: pridėjo Proword – 4.2.0
WooCommerce Min/Max Quantities: pridėjo WooCommerce – 2.3.16
WooCommerce - Store Toolkit: pridėjo Visser Labs – 1.7.1
WooCommerce: pridėjo Automattic – 3.0.3
Yoast SEO: pridėjo Team Yoast – 4.6
WP All Import Pro: pridėjo Soflyy – 4.4.3
WP Better Emails: pridėjo Nicolas Lemoine – 0.3
WordPress Toolbar Editor: pridėjo Janis Elsts – 1.2.1
WP All Import - WooCommerce Add-On Pro: pridėjo Soflyy – 2.3.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Parduotuvės bazė: #5 - /parduotuve/
Krepšelis: #6 - /krepselis/
Apmokėjimas: #7 - /apmokejimas/
Mano paskyra: #8 - /paskyra/

### Theme ###

Name: Biovaistinė
Version: 1.0.0
Author URL: http://squarepixel.lt/
Child Theme: ❌ – Jei norite redaguoti WooCommerce arba temą
kurios kūrėjas nesate Jūs pats
mes rekomenduojame naudoti potemes. Daugiau infomacijos: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: biovaistine/woocommerce/archive-product.php
biovaistine/woocommerce/auth/footer.php
biovaistine/woocommerce/auth/form-grant-access.php
biovaistine/woocommerce/auth/form-login.php
biovaistine/woocommerce/auth/header.php
biovaistine/woocommerce/cart/cart-empty.php
biovaistine/woocommerce/cart/cart-item-data.php
biovaistine/woocommerce/cart/cart-shipping.php
biovaistine/woocommerce/cart/cart-totals.php
biovaistine/woocommerce/cart/cart.php
biovaistine/woocommerce/cart/cross-sells.php
biovaistine/woocommerce/cart/mini-cart.php
biovaistine/woocommerce/cart/proceed-to-checkout-button.php
biovaistine/woocommerce/cart/shipping-calculator.php
biovaistine/woocommerce/checkout/cart-errors.php
biovaistine/woocommerce/checkout/form-billing.php
biovaistine/woocommerce/checkout/form-checkout.php
biovaistine/woocommerce/checkout/form-coupon.php
biovaistine/woocommerce/checkout/form-login.php
biovaistine/woocommerce/checkout/form-pay.php
biovaistine/woocommerce/checkout/form-shipping.php
biovaistine/woocommerce/checkout/payment-method.php
biovaistine/woocommerce/checkout/payment.php
biovaistine/woocommerce/checkout/review-order.php
biovaistine/woocommerce/checkout/terms.php
biovaistine/woocommerce/checkout/thankyou.php
biovaistine/woocommerce/content-product.php
biovaistine/woocommerce/content-product_cat.php
biovaistine/woocommerce/content-single-product.php
biovaistine/woocommerce/content-widget-product.php
biovaistine/woocommerce/emails/admin-cancelled-order.php
biovaistine/woocommerce/emails/admin-failed-order.php
biovaistine/woocommerce/emails/admin-new-order.php
biovaistine/woocommerce/emails/customer-completed-order.php
biovaistine/woocommerce/emails/customer-invoice.php
biovaistine/woocommerce/emails/customer-new-account.php
biovaistine/woocommerce/emails/customer-note.php
biovaistine/woocommerce/emails/customer-on-hold-order.php
biovaistine/woocommerce/emails/customer-processing-order.php
biovaistine/woocommerce/emails/customer-refunded-order.php
biovaistine/woocommerce/emails/customer-reset-password.php
biovaistine/woocommerce/emails/email-addresses.php
biovaistine/woocommerce/emails/email-customer-details.php
biovaistine/woocommerce/emails/email-footer.php
biovaistine/woocommerce/emails/email-header.php
biovaistine/woocommerce/emails/email-order-details.php
biovaistine/woocommerce/emails/email-order-items.php
biovaistine/woocommerce/emails/email-styles.php
biovaistine/woocommerce/emails/plain/admin-cancelled-order.php
biovaistine/woocommerce/emails/plain/admin-failed-order.php
biovaistine/woocommerce/emails/plain/admin-new-order.php
biovaistine/woocommerce/emails/plain/customer-completed-order.php
biovaistine/woocommerce/emails/plain/customer-invoice.php
biovaistine/woocommerce/emails/plain/customer-new-account.php
biovaistine/woocommerce/emails/plain/customer-note.php
biovaistine/woocommerce/emails/plain/customer-on-hold-order.php
biovaistine/woocommerce/emails/plain/customer-processing-order.php
biovaistine/woocommerce/emails/plain/customer-refunded-order.php
biovaistine/woocommerce/emails/plain/customer-reset-password.php
biovaistine/woocommerce/emails/plain/email-addresses.php
biovaistine/woocommerce/emails/plain/email-customer-details.php
biovaistine/woocommerce/emails/plain/email-order-details.php
biovaistine/woocommerce/emails/plain/email-order-items.php
biovaistine/woocommerce/global/breadcrumb.php
biovaistine/woocommerce/global/form-login.php
biovaistine/woocommerce/global/quantity-input.php
biovaistine/woocommerce/global/sidebar.php
biovaistine/woocommerce/global/wrapper-end.php
biovaistine/woocommerce/global/wrapper-start.php
biovaistine/woocommerce/loop/add-to-cart.php
biovaistine/woocommerce/loop/loop-end.php
biovaistine/woocommerce/loop/loop-start.php
biovaistine/woocommerce/loop/no-products-found.php
biovaistine/woocommerce/loop/orderby.php
biovaistine/woocommerce/loop/pagination.php
biovaistine/woocommerce/loop/price.php
biovaistine/woocommerce/loop/rating.php
biovaistine/woocommerce/loop/result-count.php
biovaistine/woocommerce/loop/sale-flash.php
biovaistine/woocommerce/myaccount/dashboard.php
biovaistine/woocommerce/myaccount/downloads.php
biovaistine/woocommerce/myaccount/form-add-payment-method.php
biovaistine/woocommerce/myaccount/form-edit-account.php
biovaistine/woocommerce/myaccount/form-edit-address.php
biovaistine/woocommerce/myaccount/form-login.php
biovaistine/woocommerce/myaccount/form-lost-password.php
biovaistine/woocommerce/myaccount/form-reset-password.php
biovaistine/woocommerce/myaccount/lost-password-confirmation.php
biovaistine/woocommerce/myaccount/my-account.php
biovaistine/woocommerce/myaccount/my-address.php
biovaistine/woocommerce/myaccount/my-downloads.php
biovaistine/woocommerce/myaccount/my-orders.php
biovaistine/woocommerce/myaccount/navigation.php
biovaistine/woocommerce/myaccount/orders.php
biovaistine/woocommerce/myaccount/payment-methods.php
biovaistine/woocommerce/myaccount/view-order.php
biovaistine/woocommerce/notices/error.php
biovaistine/woocommerce/notices/notice.php
biovaistine/woocommerce/notices/success.php
biovaistine/woocommerce/order/form-tracking.php
biovaistine/woocommerce/order/order-again.php
biovaistine/woocommerce/order/order-details-customer.php
biovaistine/woocommerce/order/order-details-item.php
biovaistine/woocommerce/order/order-details.php
biovaistine/woocommerce/order/tracking.php
biovaistine/woocommerce/product-searchform.php
biovaistine/woocommerce/single-product/add-to-cart/external.php
biovaistine/woocommerce/single-product/add-to-cart/grouped.php
biovaistine/woocommerce/single-product/add-to-cart/simple.php
biovaistine/woocommerce/single-product/add-to-cart/variable.php
biovaistine/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
biovaistine/woocommerce/single-product/add-to-cart/variation.php
biovaistine/woocommerce/single-product/meta.php
biovaistine/woocommerce/single-product/photoswipe.php
biovaistine/woocommerce/single-product/price.php
biovaistine/woocommerce/single-product/product-attributes.php
biovaistine/woocommerce/single-product/product-image.php
biovaistine/woocommerce/single-product/product-thumbnails.php
biovaistine/woocommerce/single-product/rating.php
biovaistine/woocommerce/single-product/related.php
biovaistine/woocommerce/single-product/review-meta.php
biovaistine/woocommerce/single-product/review-rating.php
biovaistine/woocommerce/single-product/review.php
biovaistine/woocommerce/single-product/sale-flash.php
biovaistine/woocommerce/single-product/share.php
biovaistine/woocommerce/single-product/short-description.php
biovaistine/woocommerce/single-product/tabs/additional-information.php
biovaistine/woocommerce/single-product/tabs/description.php
biovaistine/woocommerce/single-product/tabs/tabs.php
biovaistine/woocommerce/single-product/title.php
biovaistine/woocommerce/single-product/up-sells.php
biovaistine/woocommerce/single-product-reviews.php
biovaistine/woocommerce/single-product.php
biovaistine/woocommerce/taxonomy-product_cat.php
biovaistine/woocommerce/taxonomy-product_tag.php

### Templates ###

thumbnail: 
medium: 
medium_large: 
large: 
shop_thumbnail: 
shop_catalog: 
shop_single: 
`
</details>

**Comment by mikejolley** [comment]
It's a taxonomy in 3.0 - product_visibility, term featured. Use tax_query.
