### ISSUE TITLE
Filter to remove trailing zero's not working on Woocommerce 3.x

### ISSUE THREAD

**Issue by edwinhamers** [woocommerce/woocommerce#14407]
### EXPLANATION OF THE ISSUE

Starting from Woocommerce 3.0.x the filter that i was using stopped working. See code below.

```
// Show trailing zeros on prices, default is to hide it.
add_filter( 'woocommerce_price_trim_zeros', 'wc_hide_trailing_zeros', 10, 1 );
function wc_hide_trailing_zeros( $trim ) {
    // set to false to show trailing zeros
    return false;
}
```

This code is directly from the woocommerce docs site
https://docs.woocommerce.com/document/show-trailing-zeros-on-prices/

### STEPS TO REPRODUCE THE ISSUE

Install woocommerce 3.0.x and add the filter code to functions.php

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: http://www.108bits.nl/testwp
Site URL: http://www.108bits.nl/testwp
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: twp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

InfiniteWP - Client: by Revmakx – 1.6.4
WooCommerce: by Automattic – 3.0.3
WooThemes Helper: by WooThemes – 1.6.2 – Network enabled

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: donation (donation)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by edwinhamers** [comment]
Interestingly, the filter function has been reversed!!!

Now a "true" value will actually remove trailing zero's.... Way to go

**Comment by mikejolley** [comment]
@edwinhamers but if you compare:

https://github.com/woocommerce/woocommerce/blob/e027e5b0a1ab8e2c7b746c7d6bd2ef3879178139/includes/wc-formatting-functions.php#L478-L480

to 

https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/wc-formatting-functions.php#L421-L423

You'll see there was no change in 3.0.

And no change in 2.5 https://github.com/woocommerce/woocommerce/blob/2.5.0/includes/wc-formatting-functions.php#L393

And 2.4 https://github.com/woocommerce/woocommerce/blob/2.4.0/includes/wc-formatting-functions.php#L384-L386 And 2.3 https://github.com/woocommerce/woocommerce/blob/2.3.0/includes/wc-formatting-functions.php#L362

It was changed between 2.1 and 2.2 https://github.com/woocommerce/woocommerce/blob/2.1.0/includes/wc-formatting-functions.php#L326 -->  https://github.com/woocommerce/woocommerce/blob/2.2.0/includes/wc-formatting-functions.php#L335

And this has not changed the filter - this has just changed the default.

Way to go.
