### ISSUE TITLE
Incorrect net sales value when there are refunds

### ISSUE THREAD

**Issue by decimoseptimo** [woocommerce/woocommerce#14402]
I came here to report exactly this #10885. The issue was closed but i feel the explanation is incomplete.  These are my findings:
```
Example April report (2 items sold, 1100 each, 10% tax included. 1 item refunded)

gross sales = 2200
explanation: 1100 + 1100

refund = 1100

net sales prior refund = 2000
1000 + 1000

net sales after refund (as shown in reports) = 2000 - 1100 = 900
net sales after refund (what i think is correct) = 2000 - 1000 = 1000
```
I may be missing something, i just don't see where. Woocomerce net sales differ from "cost of goods" plugin net sales.

**Comment by mikejolley** [comment]
1 order, 2 items. 1 item refunded:

https://dl.dropboxusercontent.com/s/ne7cv71h0k2i6ws/2017-04-15%20at%2016.33.png

Looks correct afaik. Net is 1000 because thats 1 item without taxes.

**Comment by decimoseptimo** [comment]
It may be the version or settings, but i'm geting a different result

1 order, 1 items. 1 item refunded:
http://imgur.com/a/LgYx8

**Comment by mikejolley** [comment]
Can you show me how you did the refund? did you refund the line, or enter the amount manually?

**Comment by decimoseptimo** [comment]
Manually in 'edit order', the 'refund' button just before 'custom fields'.
I dont know what "the line" is.

**Comment by mikejolley** [comment]
Show me how you did it before clicking manual refund. Screenshot.

**Comment by decimoseptimo** [comment]
Orders > edit > refund > refund ammount textfield > refund XXX$ manually > accept
http://imgur.com/8BOrXoW

**Comment by mikejolley** [comment]
Because you have not refunded the ITEM (the row above), the report doesn't know if you've refunded item costs or taxes.

**Comment by decimoseptimo** [comment]
I see. I think there should be an alert icon just before 'refund_amount' label warning about the implications of: manually inputing a value there, instead of auto-fill using the 'line'.
