### ISSUE TITLE
Session data getting wiped when adding an item to the cart

### ISSUE THREAD

**Issue by indextwo** [woocommerce/woocommerce#14408]
I'm using `WC_Session` to set a variable at the point someone visits a store: `WC()->session->set('storeid', $relevantIDValue);` - this helps dictate what is available, what fees should be applied at checkout, etc. and makes the variable accessible everywhere, and easily manageable.

However, if the session var is set at the point when the cart is empty (which is almost always the case), then as soon as the user adds something to the cart, the custom session var gets wiped. 

**To reproduce:**

1. Add `print_r(WC()->session);` to `header.php`
2. Add `WC()->session->set('customsessionvar', 1);` before `get_header()` on a single custom page;
3. Visit page with empty cart, see that `customsessionvar` exists;
4. Add an item to your cart;
5. Go to _another page_ (as simply refreshing the current page will re-add the custom session var) - like the cart or checkout;
6. See that `customsessionvar` is no longer present in session data.

If you revisit that page or otherwise re-set `customsessionvar` _after_ the first item has been added to an empty cart, then it persists even after other items have been added. It's only when setting the var with an empty cart that the issue occurs.

At the moment I'm kinda-sorta getting around this by using `wc_setcookie()` at the same time as setting `WC()->session->set()`, then checking to see if a) the session var exists, and b) if not, then setting it to the value of the cookie. But this seems dreadfully unnecessary, as blocking cookies immediately stops this from working.

I guess, at the point a product is added to the cart, the session's `_data` gets wiped and replaced with the new cart information. Is there any way for that to _not_ happen, or to protect a custom var that's been set elsewhere?

**Comment by mikejolley** [comment]
No sessions are saved unless the user has a cart. I think you'll find if you set the session once, then browse around, it will be gone. 

You're right about needing to set the wc_setcookie manually if needed. You'll need to continue to do that, or a different method of storing that data (such as a dedicated cookie).

The reason why this session does not persist is for compatible with caching plugins. If we had active sessions for all visitors, no static cache could ever be used. WP is stateless by default.
