### ISSUE TITLE
Missing column in orderlist after update to woocommerce 3.0.0 / 3.0.3

### ISSUE THREAD

**Issue by barfalarm** [woocommerce/woocommerce#14413]
### EXPLANATION OF THE ISSUE

In the new version there is no column with order-information

### STEPS TO REPRODUCE THE ISSUE

Check old-orderlist:
https://drive.google.com/open?id=0B9hVB29a0jawWDd4cWx4ODlSRXM

Check new-orderlist:
https://drive.google.com/open?id=0B9hVB29a0jawYkNlbzJtOU51NFU

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: https://www.barf-alarm.de
Site URL: https://www.barf-alarm.de
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 80 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 80 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Autoptimize: von Frank Goossens (futtta) – 2.1.0
Custom Header Extended: von Justin Tadlock – 1.0.0
DHL Express/DHL Paket WooCommerce Shipping with Print Label: von WooForce – 2.1.9
Jetzt kaufen: von t.kumpanenko@gmail.com – 1.0.0
Kommentare deaktivieren: von Samir Shah – 1.6
Google Tag Manager for Wordpress: von Thomas Geiger – 1.5.1
eKomi Integration: von eKomi – 1.3.0
Leadpages Connector: von Leadpages – 2.1.6.2
Loco Translate: von Tim Whitlock – 2.0.13
Pinterest Verify: von Phil Derksen – 1.0.4
Price traking plugin: von t.kumpanenko@gmail.com – 1.0.0
Woocomerce Product Export: von Taras Kumpanenko – 0.1
Redirection: von John Godley – 2.5
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 2.2.6
Remember Me Controls: von Scott Reilly – 1.6
Simple History: von Pär Thernström – 2.13
UpdraftPlus - Backup/Restore: von UpdraftPlus.Com
DavidAnderson – 1.12.40

W3 Total Cache: von Frederick Townes – 0.9.5.2
WC API Custom Meta: von Jason Judge – 0.7.0
WooCommerce Product Feed: von WebAppick – 2.0.13
WooCommerce Weight Based Shipping: von dangoodman – 4.2.3
WooCommerce Brands: von Taras Kumpanenko – 1.0
Hundereasse: von t.kumpanenko@gmail.com – 1.0.0
WooCommerce Cart Extended: von ThemePlugger – 1.0.0
WooCommerce Category custom fields: von Taras Kumpanenko – 1.0
Rabatt: von t.kumpanenko@gmail.com – 1.0.0
WooCommerce Germanize extended: von Taras Kumpanenko – 1.0
WooCommerce Germanized: von Vendidero – 1.8.8
Order Statuses extend: von Taras Kumpanenko – 1.0
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 1.6.4
WooCommerce Product fields extension: von Taras Kumpanenko – 1.0
WooCommerce fake old price: von Taras Kumpanenko – 1.0
SOFORT Banking for WooCommerce: von Awesome UG & MarketPress – 1.1.19
WooCommerce Google product feed: von asaquzzaman – 1.5.2
WooCommerce: von Automattic – 3.0.3
WooCommerce: Anbindung an idealo.de: von Alexnder Kirk – 1.0.0
WooCommerce Helper: von WooCommerce – 1.7.2 – Netzwerk aktiviert
Yoast SEO: von Team Yoast – 4.6
WP-Lister Pro for Amazon: von Matthias Krok – 0.9.6.34
WP-Mail-SMTP: von Callum Macdonald – 0.10.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /shop/
Warenkorb: #8 - /cart/
Kasse: #9 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: Martha
Version: 1.4.4
Author URL: http://themeforest.net/user/bigtreat
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: marthav1.4.4/woocommerce/archive-product.php
marthav1.4.4/woocommerce/cart/cart-empty.php
marthav1.4.4/woocommerce/cart/cart-shipping.php
marthav1.4.4/woocommerce/cart/cart-totals.php
marthav1.4.4/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
marthav1.4.4/woocommerce/cart/shipping-calculator.php
marthav1.4.4/woocommerce/checkout/cart-errors.php
marthav1.4.4/woocommerce/checkout/form-billing.php version 2.1.2 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/checkout/form-checkout.php
marthav1.4.4/woocommerce/checkout/form-login.php
marthav1.4.4/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/checkout/review-order.php
marthav1.4.4/woocommerce/checkout/terms.php
marthav1.4.4/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/content-product.php version 2.5.0 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/emails/customer-processing-order.php
marthav1.4.4/woocommerce/global/form-login.php
marthav1.4.4/woocommerce/global/sidebar.php
marthav1.4.4/woocommerce/global/wrapper-end.php
marthav1.4.4/woocommerce/global/wrapper-start.php
marthav1.4.4/woocommerce/loop/loop-end.php
marthav1.4.4/woocommerce/loop/loop-start.php
marthav1.4.4/woocommerce/loop/no-products-found.php
marthav1.4.4/woocommerce/loop/orderby.php
marthav1.4.4/woocommerce/loop/pagination.php
marthav1.4.4/woocommerce/loop/price.php
marthav1.4.4/woocommerce/loop/rating.php version 2.0.0 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/loop/result-count.php version 2.0.0 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/loop/sale-flash.php
marthav1.4.4/woocommerce/myaccount/form-add-payment-method.php version 2.1 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/myaccount/form-edit-address.php version 2.1.0 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 2.6.0
marthav1.4.4/woocommerce/myaccount/form-lost-password.php version 2.3.0 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/myaccount/my-account.php version 2.0.0 is out of date. The core version is 2.6.0
marthav1.4.4/woocommerce/myaccount/my-address.php version 2.2.0 is out of date. The core version is 2.6.0
marthav1.4.4/woocommerce/myaccount/my-downloads.php
marthav1.4.4/woocommerce/single-product/add-to-cart/external.php
marthav1.4.4/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.3
marthav1.4.4/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/single-product/add-to-cart/variable.php
marthav1.4.4/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 3.0.2
marthav1.4.4/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 3.0.2
marthav1.4.4/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/single-product/review.php version 2.5.0 is out of date. The core version is 2.6.0
marthav1.4.4/woocommerce/single-product/sale-flash.php
marthav1.4.4/woocommerce/single-product/share.php
marthav1.4.4/woocommerce/single-product/short-description.php
marthav1.4.4/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
marthav1.4.4/woocommerce/single-product/tabs/description.php
marthav1.4.4/woocommerce/single-product/tabs/tabs.php
marthav1.4.4/woocommerce/single-product/title.php
marthav1.4.4/woocommerce/single-product-reviews.php
marthav1.4.4/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14121
