### ISSUE TITLE
Table Rate Shipping broken with latest Woocommerce update

### ISSUE THREAD

**Issue by BuggeringHell** [woocommerce/woocommerce#14412]
Since updating Woocommerce from 3.0.0 to the latest version, all products using Table rate shipping zones (premium plugin by Woocommerce) are broken.

'There are no shipping methods available. Please check your address or contact us if you need any help.'

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/14387 It's shipping class related.

**Comment by BuggeringHell** [comment]
Thanks for clearing that up. In terms of a fix, will it be sometime this weekend or should I rollback?

**Comment by mikejolley** [comment]
You can apply it manually - it won't be released until mid next week.

**Comment by daisylane** [comment]
Can you point to the link and directions to apply the fix manually?  We are in a real bind without this working on an ecommerce site, obviously.  Thanks so much!

**Comment by claudiosanches** [comment]
@daisylane we are releasing it right now, should be available in a few minutes.

**Comment by daisylane** [comment]
I updated Woocommerce as recommended (I did not see an update for Table Rates), but this did not fix the problem.  When I click on the details for Table Rates, I am told it is the most recent version.

**Comment by mikejolley** [comment]
Sounds unrelated to this. Put a ticket in with the help desk.
