### ISSUE TITLE
missing text of attribute in variable product in woocommerce

### ISSUE THREAD

**Issue by eeteurope** [woocommerce/woocommerce#14411]
For my new product I made new attribute named "Hours".
In variations appear attribue Hours, but after updating, my web product page, I can't see the attribute name on it, just the value, why?

![screen shot 2017-04-14 at 18 53 49](https://cloud.githubusercontent.com/assets/27572157/25065602/56d609e6-21d8-11e7-871e-fdc8f25a0550.png)
![screen shot 2017-04-14 at 18 53 55](https://cloud.githubusercontent.com/assets/27572157/25065601/56d505c8-21d8-11e7-9aa2-fed18c6c5eef.png)
![screen shot 2017-04-14 at 19 05 14](https://cloud.githubusercontent.com/assets/27572157/25065600/56d4881e-21d8-11e7-9cc2-8f9fcdc877fd.png)

In my other web page in woocommerce the products doesn't have any of these problems at all.

![screen shot 2017-04-15 at 12 39 25](https://cloud.githubusercontent.com/assets/27572157/25065649/cf651af0-21d8-11e7-99e6-4f4d395b3c5a.png)
![screen shot 2017-04-15 at 12 39 29](https://cloud.githubusercontent.com/assets/27572157/25065648/cf640160-21d8-11e7-8ee1-a1ac5f53dad3.png)

I thank you in advance and hope for your soonest reply.

**Comment by mikejolley** [comment]
Are you using a plugin like WPML to translate these?
