### ISSUE TITLE
[API v2] Hook after order created + totals calculated

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#14416]
### EXPLANATION OF THE ISSUE

In older versions of the API (pre WP REST API), the `woocommerce_api_create_order` action was fired after creating an order, giving on-site code full access to the created order with full data. 

When posting to `wp-json/wc/v2/orders`, I don't see an equivalent hook being fired. When [saving the object](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-orders-controller.php#L482) and following through [`$object->save()`](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-orders-controller.php#L501), to `WC_Data::save()`, you will eventually get to `WC_Order_Data_Store_CPT::create( $order )`, which will fire the `woocommerce_new_order` action. 

However, at the point this is fired, order totals are not finalized, so when trying to check this new order for totals, you'll get 0. This is posing a problem in Sequential Order Numbers Pro when I'm trying to restore REST API support, as a "free" order number will be generated on this hook for every API order since the totals aren't yet set.

How about re-adding the old action (or adding a new one) [right here before the object is returned](https://github.com/woocommerce/woocommerce/blob/5a7dd4938dd728adea6ca6379846323136a76d59/includes/api/class-wc-rest-orders-controller.php#L519), which means it will have all of its data after totals are recalculated? Happy to submit a PR, just wanted to outline this first to make sure I haven't missed something obvious or if it's not something that will be considered.

cc @claudiosanches @mikejolley 

### STEPS TO REPRODUCE THE ISSUE

Error log an order created via the REST API when hooked into `woocommerce_new_order` and see discount_total / shipping_total / total not yet set.

**Comment by mikejolley** [comment]
@claudiosanches thoughts on where to put this and version? There has been no action in any new WP Rest API so this could wait for 3.1. I'd do a new action, not use the old one.

**Comment by claudiosanches** [comment]
> How about re-adding the old action (or adding a new one) right here before the object is returned, which means it will have all of its data after totals are recalculated? Happy to submit a PR, just wanted to outline this first to make sure I haven't missed something obvious or if it's not something that will be considered.

Well, `woocommerce_api_create_order` is present only in the legacy API.

But there is already actions for it in your new REST API.

On v2 there is the [`woocommerce_rest_insert_{$this->post_type}_object`](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-rest-crud-controller.php#L204) filter.

And on v1 you can use the [`woocommerce_rest_insert_{$this->post_type}`](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-rest-posts-controller.php#L211) filter.

So the correct hook for what you need is `woocommerce_rest_insert_shop_order_object`, since the order will be already saved and with all calculated and ready to be changed if needed.

**Comment by bekarice** [comment]
@claudiosanches thanks for the tip! didn't think to look for a dynamic hook there. 

One note on the [`woocommerce_rest_insert_{$post_type}` filter](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-rest-posts-controller.php#L211): The docblock says this about the first param:

```
@param object          $post      Inserted object (not a WP_Post object).
``` 

Which led me to assume the first param for the hook is a `WC_Order` instance at first. However, this is actually a `WP_Post` instance instead, contrary to what the docblock says. You can see a few lines up that this is done:

```
$post     = get_post( $post_id );
```

So devs will get a WP_Post instance passed into this hook. Do you want a separate issue opened for the v1 API?

**Comment by claudiosanches** [comment]
@bekarice for v1 it's a WP_Post, that's why we have two different hooks, we need to fix this docblock.
We can solve it here, let me know if you need help.

**Comment by bekarice** [comment]
@claudiosanches 👍 thanks for the docblock update, sounds good to me. just wanted to be sure it was intended to pass in the `WP_Post` object -- will handle grab the order from this param for that hook in SONP

**Comment by claudiosanches** [comment]
@bekarice can use the same function to hook on both, but need to check first like:

```php
if ( ! is_a( $order, 'WC_Order' ) ) {
    $order = wc_get_order( $order->ID );
}
```
