### ISSUE TITLE
featured item not working

### ISSUE THREAD

**Issue by IR4N0nY** [woocommerce/woocommerce#14425]
hello all
i use the last version of wordpress:4.7.3 and last version of woocommerce: 3.0.3
my theme is Storefront but on woocommerce products page when i click on featured item the star show me yes but in database with phpmyadmin there is no change on _featured meta_key and still set to no
i just install woocommerce and there is no plugin in my wordpress just woocommerce!

my qustion on stackoverflow:
http://stackoverflow.com/questions/43439429/admin-ajax-phpaction-woocommerce-feature-product-403-error

**Comment by rafsuntaskin** [comment]
Check the answer on stackoverflow.

> Featured products are also using the new product_visibility taxonomy instead of meta which improves queries on those.

**Comment by IR4N0nY** [comment]
sorry i open this issue again
can you give me and example how can i do that?

**Comment by mikejolley** [comment]
Use tax query https://codex.wordpress.org/Class_Reference/WP_Query#Taxonomy_Parameters

**Comment by JoelLisenby** [comment]
This is an unfortunate breaking change on the part of woocommerce. There is no error message if you are using the meta_query method and any new products marked as featured will just fail to appear.

Here is the new method for future reference:

```
$args = array(
	'post_type'   =>  'product',
	'stock'       =>  1,
	'showposts'   =>  1,
	'orderby'     =>  'date',
	'order'       =>  'DESC',
	'tax_query'   =>  array(
		array(
			'taxonomy' => 'product_visibility',
			'field' => 'name',
			'terms' => 'featured',
			'operator' => 'IN'
		)
	)
);
```

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#product-visibility-is-taxonomy-based-instead-of-meta-based
