### ISSUE TITLE
No way to easily alter Product Gallery lightbox image size

### ISSUE THREAD

**Issue by wpexplorer** [woocommerce/woocommerce#14428]
### EXPLANATION OF THE ISSUE

Currently the following code is used in product-image.php:

`$full_size_image   = wp_get_attachment_image_src( $post_thumbnail_id, 'full' );`

Any chance you would consider adding a filter to the image size so that the lightbox image can be changed to for example the "large" image size or a custom image size specific for lightbox images?

Thanks!

**Comment by claudiosanches** [comment]
Closed by #14432

Thanks @emgk
