### ISSUE TITLE
API works fine for authorized GET requests, but not for authorized POST requests

### ISSUE THREAD

**Issue by miguelalche** [woocommerce/woocommerce#14427]
### EXPLANATION OF THE ISSUE
As the title says I can get signed get requests to work fine. But Post requests give me an error

Wordpress version 	4.7.3
WC version: 2.6.14

### STEPS TO REPRODUCE THE ISSUE

In postman I fill the consumer key and secret, and then select "Encode OAuth Signature". 

I know this works because it allows me to list my products by sending a get request to 
http://mysite.com/wp-json/wc/v1/products

However when I try to do a post request to the same url the response says: 
{
  "code": "woocommerce_rest_authentication_error",
  "message": "Firma no válida - la firma proporcionada no coincide.",
  "data": {
    "status": 401
  }
}

This is weird since I haven't modified the authorization settings.

### SYSTEM STATUS

<details>

Entorno WordPress
URL ﻿de la página de inicio:		http://www.MYSITE.com
URL del sitio:		http://www.MYSITE.com
Versión de WC:		2.6.14
Directorio de registros con permiso de escritura:		 /home/MYUSERNAME/public_html/wp-content/uploads/wc-logs/
Versión de WP:		4.7.3
WordPress Multisitio:		–
Límite de memoria WP:		256 MB
WP Debug Mode:		–
WP Cron:		
Idioma:		es_ES

</details>

**Comment by mikejolley** [comment]
The signature changes for POST requests. See how the sig is generated on https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API for better ways - using HTTPS is much easier.
