### ISSUE TITLE
Cannot use object of type WP_Error on class-wc-product-attribute.php on line 80

### ISSUE THREAD

**Issue by Brown-Ninja** [woocommerce/woocommerce#14429]
### EXPLANATION OF THE ISSUE

When updating product with attributes(changing short description or image), I get following error with WooCommerce Version 3.0.3 

Fatal error: Cannot use object of type WP_Error in /home/content/a2pewpnas01_data03/69/3970369/html/wp-content/plugins/woocommerce/includes/class-wc-product-attribute.php on line 80

### STEPS TO REPRODUCE THE ISSUE
1. I got to Products under dashboard
2. Edit a product called "Lip Balm in Slider Tin with SPF" on www.sudsys4u.com
3. Change short description or add an image.
4. Click update.
5. I get Fatal error: Cannot use object of type WP_Error as array in /home/content/a2pewpnas01_data03/69/3970369/html/wp-content/plugins/woocommerce/includes/class-wc-product-attribute.php on line 80

### SYSTEM STATUS
`
### WordPress Environment ###

Home URL: https://www.sudsys4u.com
Site URL: https://www.sudsys4u.com
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_chwaap6d5c_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Beaver Builder Booster: by The Beaver Builder Team – 1.0.5
Beaver Builder Plugin (Lite Version): by The Beaver Builder Team – 1.9.5.3
Breadcrumb NavXT: by John Havlik – 5.6.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Contact Widgets: by GoDaddy – 1.4.1
Fast Secure reCAPTCHA: by Mike Challis – 1.0.13
GoDaddy Email Marketing: by GoDaddy – 1.2.0
Meta Slider: by Matcha Labs – 3.5
Ninja Forms: by The WP Ninjas – 3.0.33
Page Links To: by Mark Jaquith – 2.9.9
Rich Reviews: by Nuanced Media – 1.7.3
Search Engine Visibility: by GoDaddy – 0.5
Simple Wp Sitemap: by Webbjocke – 1.1.8
Page Builder by SiteOrigin: by SiteOrigin – 2.4.25
WooCommerce: by Automattic – 3.0.3
Wordfence Security: by Wordfence – 6.3.6
Yoast SEO: by Team Yoast – 4.6
WP101 Video Tutorials: by WP101Plugin.com – 0.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #310 -
Cart: #311 - /cart/
Checkout: #312 - /checkout/
My account: #313 - /my-account/

### Theme ###

Name: Sabino
Version: 1.1.02
Author URL: https://kairaweb.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
The product has a taxonomy based attribute, but the terms do not exist, and when it tries to create the missing terms it is erring. Looks like a product problem, possibly from a bad import.

I can work around the issue by checking if the term failed to update, but you need to look into this.
