### ISSUE TITLE
Shipping Class Not Being Selected, Defaulting to No Shipping Class Cost

### ISSUE THREAD

**Issue by bluestreakdesigns** [woocommerce/woocommerce#14423]
### EXPLANATION OF THE ISSUE

I have multiple flat rate shipping classes defined by product type.  Each product is assigned to a shipping class in the product data section of the product definition.  I also have a shipping class for No shipping Class as a default. Prior to Woocommerce 3.0 this worked perfectly, with the correct shipping cost being picked up during check out based on the product's assigned shipping class.  After installing Woocommerce 3.0 on my sandbox I found that all products at checkout are defaulting to the No Shipping Class cost, and is no longer picking up the correct shipping cost based on the assigned shipping class.  I disabled all other plugins, and switched theme to twelve twenty, the issue persisted so it appears to be in Woocommerce 

### STEPS TO REPRODUCE THE ISSUE
1. Create multiple flat rate shipping classes in a shipping zone with different costs
2. Create a default No Shipping Class cost with a shipping cost different from all other shipping classes.
2. Assign different shipping class to several different products.
3. Select a product for checkout and see if the correct shipping cost is assigned.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://sandbox.bluestreakdesigns.com
Site URL: http://sandbox.bluestreakdesigns.com
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.25
PHP Post Max Size: 8 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (19) ###

Breadcrumb NavXT: by John Havlik – 5.6.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Display Widgets: by Strategy11 – 2.05
Google Language Translator: by Rob Myrick – 5.0.30
Master Slider: by averta – 2.9.8
Responsive Menu: by Responsive Menu – 3.0.18
TemplatesNext ToolKit: by TemplatesNext – 2.0.5
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

Use Google Libraries: by Jason Penney – 1.6.2.1
WooCommerce Variation Swatches: by ThemeAlien – 1.0.2
WooCommerce Extended Coupon Features: by Soft79 – 2.4.2.1
Booster for WooCommerce: by Algoritmika Ltd – 2.7.1
WooCommerce Product Archive Customiser: by jameskoster – 1.0.5
WooCommerce Social Media Share Buttons: by Toastie Studio – 1.3.0
WooCommerce: by Automattic – 3.0.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.3.6
Yoast SEO: by Team Yoast – 4.6
WP Super Cache: by Automattic – 1.4.9

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1146935 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: i-craft-child
Version: 1.1.7
Author URL: http://www.bluestreakdesigns.com
Child Theme: ✔
Parent Theme Name: i-craft
Parent Theme Version: 2.0.0
Parent Theme Author URL: http://templatesnext.org/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: i-craft/woocommerce/archive-product.php
i-craft-child/woocommerce/cart/cart-empty.php
i-craft-child/woocommerce/cart/proceed-to-checkout-button.php
i-craft-child/woocommerce/checkout/review-order.php
i-craft-child/woocommerce/checkout/thankyou.php
i-craft/woocommerce/content-product.php
i-craft-child/woocommerce/content-single-product.php
i-craft-child/woocommerce/emails/customer-completed-order.php
i-craft/woocommerce/loop/loop-end.php
i-craft/woocommerce/loop/loop-start.php
i-craft-child/woocommerce/loop/no-products-found.php
i-craft/woocommerce/loop/orderby.php
i-craft/woocommerce/loop/pagination.php
i-craft/woocommerce/loop/sale-flash.php
i-craft-child/woocommerce/single-product/add-to-cart/variable.php
i-craft-child/woocommerce/single-product/price.php
i-craft/woocommerce/single-product/sale-flash.php
i-craft/woocommerce/single-product/share.php
i-craft-child/woocommerce/single-product/short-description.php
i-craft-child/woocommerce/single-product/tabs/description.php
i-craft-child/woocommerce/single-product/title.php

</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/14387
