### ISSUE TITLE
issue calculation total price - fee extra (miscalculation of the total price when using a spare premium COD)

### ISSUE THREAD

**Issue by lukasprelovsky** [woocommerce/woocommerce#14422]
# EXPLANATION OF THE ISSUE

when using extra premium for cash on delivery, the issue of badly miscalculated the total price, resulting in a violation of law in the country-in some cases bad calculation of VAT.

we live in a country where cash on delivery surcharge used by almost everyone as cash on delivery is charged.

# **STEPS TO REPRODUCE THE ISSUE**

total price calculate is wrong. 

Total price exemple: 9.90 euro product + shipping 1.90 euro + fee extra 1.00 euro = 12.79 is wrong. 
Really is 12.80 euro ! This calculate is fail

i testing in woo 2.6.14 and 3.0.3
see example:
![pokladna](https://cloud.githubusercontent.com/assets/15073394/25068402/d40e088e-2262-11e7-856d-b98f72019ecb.png)

in WordPress org no response, so I try here! Please help thx

# SYSTEM STATUS

<details>
There is a need, this issue has in itself every shop. I tried it on 10 eshops, since version 2.6.14 - 3.0.3!
</details>

**Comment by mikejolley** [comment]
> There is a need, this issue has in itself every shop

![2017-04-16 at 10 25](https://cloud.githubusercontent.com/assets/90977/25070172/23c3d8d2-228f-11e7-8cf5-5eb6263bf1a5.png)

Cash on delivery has no built in way to add a charge/fee. Without seeing the code for the fee, and how it has been configured for tax, I won't be able to reproduce it.

**Comment by mikejolley** [comment]
Additionally, without knowing the prices for the shipping ex tax, and tax rate, it's not possible for me to even try replicating this.

Closing until more info is provided.
