### ISSUE TITLE
Don't not return the variations in the response in create order api

### ISSUE THREAD

**Issue by basanthalluri** [woocommerce/woocommerce#14439]
Hi,

Here is the what i am passing the variations in create order api

{
  "payment_method": "bacs",
  "payment_method_title": "Direct Bank Transfer",
  "set_paid": true,
  "billing":{
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US",
    "email": "john.doe@example.com",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "John",
    "last_name": "Doe",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US"
  },
  "line_items": [

    	
    	{
        "product_id": 4669,
        "quantity": 1,
        "variations": {
         "pa_color": "Black"
        }
      }
      
 
  ],
  "coupon_lines": [
  	{
  		"id":1337,
  		"code":"cstore",
  		"discount":5
  	}
  	],
  "shipping_lines": [
    {
      "method_id": "flat_rate",
      "method_title": "Flat Rate",
      "total": 10
    }
  ]
}

Here is the response

{
  "id": 4701,
  "parent_id": 0,
  "status": "processing",
  "order_key": "wc_order_58f48be0206a4",
  "number": 4701,
  "currency": "USD",
  "version": "2.6.13",
  "prices_include_tax": false,
  "date_created": "2017-04-17T09:33:20",
  "date_modified": "2017-04-17T09:33:20",
  "customer_id": 0,
  "discount_total": "5.00",
  "discount_tax": "0.00",
  "shipping_total": "10.00",
  "shipping_tax": "0.00",
  "cart_tax": "0.00",
  "total": "17.99",
  "total_tax": "0.00",
  "billing": {
    "first_name": "John",
    "last_name": "Doe",
    "company": "",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US",
    "email": "john.doe@example.com",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "John",
    "last_name": "Doe",
    "company": "",
    "address_1": "969 Market",
    "address_2": "",
    "city": "San Francisco",
    "state": "CA",
    "postcode": "94103",
    "country": "US"
  },
  "payment_method": "bacs",
  "payment_method_title": "Direct Bank Transfer",
  "transaction_id": "",
  "customer_ip_address": "138.197.124.219",
  "customer_user_agent": "WooCommerce API Client-Node.js/1.4.2",
  "created_via": "rest-api",
  "customer_note": "",
  "date_completed": "2017-04-17T09:33:20",
  "date_paid": "2017-04-17 09:33:20",
  "cart_hash": "",
  "line_items": [
    {
      "id": 6504,
      "name": "Led Fan Clock Req USB chrger",
      "sku": "",
      "product_id": 4669,
      "variation_id": 0,
      "quantity": 1,
      "tax_class": "",
      "price": "12.99",
      "subtotal": "12.99",
      "subtotal_tax": "0.00",
      "total": "12.99",
      "total_tax": "0.00",
      "taxes": [],
      "meta": []
    }
  ],
  "tax_lines": [],
  "shipping_lines": [
    {
      "id": 6505,
      "method_title": "Flat Rate",
      "method_id": "flat_rate",
      "total": "10.00",
      "total_tax": "0.00",
      "taxes": []
    }
  ],
  "fee_lines": [],
  "coupon_lines": [
    {
      "id": 6506,
      "code": "cstore",
      "discount": "5.00",
      "discount_tax": "0.00"
    }
  ],
  "refunds": [],
  "_links": {
    "self": [
      {
        "href": "http://www.example..com/wp-json/wc/v1/orders/4701"
      }
    ],
    "collection": [
      {
        "href": "http://www.example.com/wp-json/wc/v1/orders"
      }
    ]
  }
}

Here is product attribute set in the admin.

![screen shot 2017-04-17 at 3 09 00 pm](https://cloud.githubusercontent.com/assets/1677959/25085471/f8bcac8a-237f-11e7-98f2-d81678757f67.png)

Please suggest me what's going wrong.

Thanks

**Comment by mikejolley** [comment]
You pass variation_id, it is not worked out for you. https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

**Comment by basanthalluri** [comment]
I am still new to the woocommerce. Can you please explain me in more details?

**Comment by mikejolley** [comment]
Look a the docs I sent a link to ^ you send the variation ID with your request.
