### ISSUE TITLE
After disabling legacy shipping options, cannot add shipping classes or zones

### ISSUE THREAD

**Issue by modelu3d** [woocommerce/woocommerce#14442]
### EXPLANATION OF THE ISSUE

As of yesterday I have been experiencing the Shipping Class Not Being Selected issue for flat rate shipping.  I have disabled legacy flat rate shipping to start using the shipping zones and classes, but cannot add new shipping classes or shipping zones.   When clicking the Add Shipping Class button nothing happens.

### STEPS TO REPRODUCE THE ISSUE

Shipping Classes
1.  From Shipping Tab / Shipping Classes, pressing Add shipping class does not do anything.

![capture](https://cloud.githubusercontent.com/assets/27679081/25087169/ee840954-2364-11e7-860c-49e82101b768.JPG)

Shipping Zones
1.  From Shipping Tab / Shipping zones, clicking Add Shipping zone goes to Shipping zones > Zone screen successfully
2.  Save changes is greyed out.  When clicking Add shipping method, message 'Your settings have been saved' is displayed, but nothing changes.

![capture1](https://cloud.githubusercontent.com/assets/27679081/25087784/60f52adc-2369-11e7-8823-14683027c1e2.JPG)

### SYSTEM STATUS

<details>

WordPress environment
Home URL:		http://www.modelu3d.co.uk
Site URL:		http://www.modelu3d.co.uk
WC version:		3.0.3
Log directory writable:		 
WP version:		4.7.3
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		–
WP cron:		
Language:		en_GB
Server environment
Server info:		Apache
PHP version:		5.6.30
PHP post max size:		256 MB
PHP time limit:		300
PHP max input vars:		50000
cURL version:		7.36.0, OpenSSL/1.0.1e
SUHOSIN installed:		–
MySQL version:		5.6.35
Max upload size:		256 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		 Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument:		
GZip:		
Multibyte string:		 Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote post:		
Remote get:		
Database
WC database version:		3.0.3
Database prefix	 	cor_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (44)
AccessPress Instagram Feed	 	by AccessPress Themes – 2.2.7
AccessPress Social Icons	 	by AccessPress Themes – 1.6.7
AccessPress Twitter Feed	 	by AccessPress Themes – 1.5.5
Advanced Reporting For Woocommerces	 	by phoeniixx – 1.2
Advanced WP Columns	 	by Vladica Savic – 2.0.6
Akismet Anti-Spam	 	by Automattic – 3.3
Alpine PhotoTile for Instagram	 	by the Alpine Press – 1.2.7.7
Cart Product Feed Additional Product Fields	 	by ShoppingCartProductFeed; Remi Corson & Harsha Venkatesh – 1.1.3
Custom Facebook Feed	 	by Smash Balloon – 2.4.5
Custom Related Products for WooCommerce	 	by Scott Nelle – 1.3
Easy Google Fonts	 	by Titanium Themes – 1.4.2
Email Subscribers & Newsletters	 	by Icegram – 3.2.9
Rainmaker - The Best Readymade WP Forms Plugin	 	by icegram – 0.19
Instagram Feed	 	by Smash Balloon – 1.4.8
Jetpack by WordPress.com	 	by Automattic – 4.8.2
Collapse-O-Matic	 	by twinpictures, baden03 – 1.7.4
Limit Login Attempts	 	by Johan Eenfeldt – 1.7.1
MailChimp for WordPress	 	by ibericode – 4.1.1
Nextend Smart Slider 2 Full	 	by Nextend – 2.3.11
Nextend	 	by Nextend – 1.3.8
Status Tracking Plugin	 	by Etoile Web Design – 2.9.0
PDF Product Catalog 2 for WooCommerce	 	by Kyriakos Ktorides – 2.1.1
Quantities and Units for WooCommerce	 	by Nicholas Verwymeren – 1.0.13
Regenerate Thumbnails	 	by Alex Mills (Viper007Bond) – 2.2.6
Simple Notices	 	by Pippin Williamson – 1.0.7
Smart Manager	 	by StoreApps – 3.9.21
TablePress	 	by Tobias Bäthge – 1.8
TinyMCE Advanced	 	by Andrew Ozz – 4.4.3
WooCommerce Admin Bar Addition	 	by David Decker - DECKERWEB – 2.7.0
Woocommerce Advanced Bulk Edit	 	by George Iron – 3.5.5
WooCommerce Availability Notifications	 	by ThemePlugger – 1.0.7
WooCommerce Print Invoice & Delivery Note	 	by Triggvy Gunderson – 4.1.5
WooCommerce DYMO Print Product Add-on	 	by WP Fortune – 3.0.4
WooCommerce DYMO Print	 	by WP Fortune – 3.0.5
WooCommerce SagePay Form and SagePay Direct Gateway	 	by Andrew Benbow – 3.7.2
WooCommerce Grid / List toggle	 	by jameskoster – 1.1.0
WooCommerce MailChimp	 	by Saint Systems – 2.0.20
WooCommerce PickingPal	 	by PickingPal – 1.2.11
WooCommerce Order Status & Actions Manager	 	by Actuality Extensions – 2.2.0
WooCommerce Stock Manager	 	by Vladislav Musílek – 1.1.4
WooCommerce	 	by Automattic – 3.0.3
WooCommerce Helper	 	by WooCommerce – 1.7.2 – Network enabled
WP Better Emails	 	by Nicolas Lemoine – 0.3
WP Fortune	 	by WP Fortune – 1.0.8
Settings
API enabled:		
Force SSL:		–
Currency		GBP (£)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#6 - /shop/
Basket:		#7 - /cart/
Checkout:		#8 - /checkout/
My account:		#9 - /my-account/
Theme
Name:		AccessPress Store
Version:		2.1.7
Author URL:		http://accesspressthemes.com/
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Overrides	 	accesspress-store/woocommerce/archive-product.php, 
accesspress-store/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0, 
accesspress-store/woocommerce/content-product_cat.php, 
accesspress-store/woocommerce/content-single-product.php version 2.5.2 is out of date. The core version is 3.0.0, 
accesspress-store/woocommerce/global/breadcrumb.php, 
accesspress-store/woocommerce/global/sidebar.php, 
accesspress-store/woocommerce/global/wrapper-end.php, 
accesspress-store/woocommerce/global/wrapper-start.php, 
accesspress-store/woocommerce/loop/result-count.php version 2.5.2 is out of date. The core version is 3.0.0, 
accesspress-store/woocommerce/single-product/up-sells.php version 2.5.2 is out of date. The core version is 3.0.0, 
accesspress-store/woocommerce/single-product.php

</details>

**Comment by mikejolley** [comment]
In chrome, View > Developer > Javascript console. what error is shown?

**Comment by modelu3d** [comment]
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-wi…:9 JQMIGRATE: Migrate is installed, version 1.4.1
VM2259:1 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLDocument.<anonymous> (settings.js?ver=4.7.3:2)
    at i (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-wi…:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-wi…:2)
    at Function.ready (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-wi…:2)
    at HTMLDocument.K (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-wi…:2)
(anonymous) @ settings.js?ver=4.7.3:2
i @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-wi…:2
fireWith @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-wi…:2
ready @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-wi…:2
K @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-wi…:2


[www.modelu3d.co.uk-1492429334020.txt](https://github.com/woocommerce/woocommerce/files/925459/www.modelu3d.co.uk-1492429334020.txt)

**Comment by mikejolley** [comment]
If you're using caching/minification plugins, clear all caches.

**Comment by modelu3d** [comment]
Hi Mike,

Just tested in Microsoft Edge and same issue there so appears to be server side.  Not using any caching plugins within Wordpress/Woo that I can see.

**Comment by mikejolley** [comment]
Can you screenshot me the full console showing that error?

**Comment by modelu3d** [comment]
![class page load](https://cloud.githubusercontent.com/assets/27679081/25088437/40b57fc4-236e-11e7-95d8-cd442db106b6.JPG)

**Comment by mikejolley** [comment]
VM4702 - see what plugin that is from.

**Comment by mikejolley** [comment]
Did you find what is adding the script? @modelu3d

**Comment by modelu3d** [comment]
Hi Mike, having difficulty with that sorry! This is the screen shot of what I get when clicking the VM text:

![capture](https://cloud.githubusercontent.com/assets/27679081/25095078/f646938c-2391-11e7-816c-21bc38353c09.JPG)

**Comment by claudiosanches** [comment]
@modelu3d you are using 44 plugins, have you tried to disable each plugin and check if this start work again?

**Comment by modelu3d** [comment]
I'll give that a go @claudiosanches, thanks for the tip.

**Comment by modelu3d** [comment]
Thank you @claudiosanches and @mikejolley for your assistance, the issue was caused by the plugin WooCommerce Order Status & Actions Manager which adds and admin tab into the WooCommerce Settings.  Deactivating it now enables the zones and classes tables to correctly display. 

![capture1](https://cloud.githubusercontent.com/assets/27679081/25097186/5ef95cd0-239b-11e7-9bce-bb4d829e722f.JPG)
![class page load](https://cloud.githubusercontent.com/assets/27679081/25097187/5efdd1f2-239b-11e7-96d2-ddbfe4471b73.JPG)

**Comment by claudiosanches** [comment]
@modelu3d I'm glad to hear that everything is working.

**Comment by lorrinevil** [comment]
super - this is the exact problem I was having with the same plug-in - have written the author for a "fix"...disabling the plug-in solved the issues for me as well.
