### ISSUE TITLE
missing argument 3 and missing argument 4 on product shop page after defining product image

### ISSUE THREAD

**Issue by mahsisu** [woocommerce/woocommerce#14440]
### EXPLANATION OF THE ISSUE

After defining a product image on the product page in wp-admin the product is not shown correctly any more on the product shop page. First of all there appears the product image and right behind:
![grafik](https://cloud.githubusercontent.com/assets/26695665/25086848/3e4eb776-236b-11e7-92ae-bb0e2c75b9d8.png)

### STEPS TO REPRODUCE THE ISSUE

1. define a product image on the product page on wp-admin
2. show product

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://wp-guardcontrol.sisufiles.de
Site URL: http://wp-guardcontrol.sisufiles.de
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4.10
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 260 MB
PHP Time Limit: 192
PHP Max Input Vars: 65536
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: ✔
MySQL Version: 5.6.30
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔  No
Subscriptions Mode: ✔  Live

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: dcd6e_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ Die MaxMind GeoIP Datenbank existiert nicht - Die Ortung (Geolokalisierung) wird nicht funktionieren. Du kannst sie manuell installieren von http://dev.maxmind.com/geoip/legacy/geolite/ zu dem Pfad: . Scrolle einfach nach unten bis zu "Downloads" und lade die Datei "Binary / gzip" vom Typ "GeoLite Country" herunter. Denke bitte daran
die Datei GeoIP.dat.gz zu entpacken und nur die entpackte Datei GeoIP.dat hochzuladen.

### Security ###

Secure connection (HTTPS): ❌Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ✔

### Active Plugins (36) ###

Affiliates Pro: von itthinx – 2.18.1
Affiliates WooCommerce Integration: von itthinx – 1.7.1
bbPress: von Die bbPress Community – 2.5.12
BuddyPress: von Die BuddyPress Community – 2.8.2
Cherry Data Importer: von TemplateMonster – 1.1.1
Cherry Live Demo Mods Switcher: von Cherry Team – 1.1
Cherry Projects: von Cherry Team – 1.2.2
Cherry Services List: von TemplateMonster – 1.1.0
Cherry Sidebars: von Cherry Team – 1.1.1
Cherry Team Members: von TemplateMonster – 1.1.0
Cherry Testimonials: von Template Monster – 1.0.1
Dropbox Backup & Restore: von  – 1.5.1.3
Easy Pricing Tables Premium: Business: von Fatcat Apps – 2.3.6
Itthinx Updates: von itthinx – 1.2.0
Limit Login Attempts: von Johan Eenfeldt – 1.7.1
Loco Translate: von Tim Whitlock – 2.0.13
Moto Tools Integration: von TemplateMonster – 1.0.0
MotoPress Content Editor: von MotoPress – 2.2.0
MotoPress Slider: von MotoPress – 2.0.0
Power Builder Integrator: von Template Monster – 1.0.12
Power Builder UPD: von TemplateMonster – 1.4.0
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 2.2.6
TM Dashboard: von Cherry Team – 1.0.3.1
TM Mega Menu: von TemplateMonster – 1.1.2
TM Style Switcher: von CherryTeam – 1.0.4
TM Timeline: von Template Monster – 1.0.5
TM Wizard: von TemplateMonster – 1.1.0
TM WooCommerce Compare & Wishlist: von TemplateMonster – 1.1.4
Vendidero Helper: von Vendidero – 1.1.3
WooCommerce Stripe Gateway: von WooCommerce – 3.1.6
WooCommerce Germanized Pro: von Vendidero – 1.7.6
WooCommerce Germanized: von Vendidero – 1.8.9
WooCommerce Social Media Share Buttons: von Toastie Studio – 1.3.0
WooCommerce Subscriptions: von Prospress Inc. – 2.1.4 – 2.2.4 ist verfügbar
WooCommerce: von Automattic – 3.0.3
WooCommerce Helper: von WooCommerce – 1.7.2 – Netzwerk aktiviert

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #25 - /shop/
Warenkorb: #26 - /warenkorb/
Kasse: #27 - /kasse/
Mein Konto: #28 - /mein-konto/

### Theme ###

Name: Monstroid2
Version: 1.1.0
Author URL: http://www.templatemonster.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: monstroid2/woocommerce/archive-product.php
monstroid2/woocommerce/cart/cart-totals.php
monstroid2/woocommerce/cart/cart.php Version 2.3.8 ist veraltet. Die Hauptversion ist 3.0.3
monstroid2/woocommerce/cart/cross-sells.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.0.0
monstroid2/woocommerce/checkout/review-order.php
monstroid2/woocommerce/content-product.php Version 2.6.1 ist veraltet. Die Hauptversion ist 3.0.0
monstroid2/woocommerce/content-product_cat.php
monstroid2/woocommerce/content-widget-product.php
monstroid2/woocommerce/global/breadcrumb.php
monstroid2/woocommerce/global/wrapper-end.php
monstroid2/woocommerce/global/wrapper-start.php
monstroid2/woocommerce/loop/loop-end.php
monstroid2/woocommerce/loop/loop-start.php
monstroid2/woocommerce/product-searchform.php
monstroid2/woocommerce/single-product/meta.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.0.0
monstroid2/woocommerce/single-product/product-image.php Version 2.6.3 ist veraltet. Die Hauptversion ist 3.0.2
monstroid2/woocommerce/single-product/related.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.0.0
monstroid2/woocommerce/single-product/up-sells.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.0.0
monstroid2/woocommerce/single-product-reviews.php
monstroid2/woocommerce/single-product.php

Outdated Templates: ❌Erfahren Sie
wie Sie aktualisieren können

`
</details>

**Comment by mikejolley** [comment]
This is a theme issue.  The function name in the error message is prefixed with "Monstroid2" which is the theme you are using.

**Comment by mahsisu** [comment]
Thanks for the quick response!
