### ISSUE TITLE
min height of single product image does not ge adjusted on screen resize

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#14448]
Hi

When opening a single product page at f.e. below 768 px and then turn the tablet or resize the browser to above 768px the single product image css does not get adjusted to a correct min-height creating a huge gab between the thumbs and the active image. It creates weird zoom effects as the zoom enlarges the image to the min-height of the container.

![min-height-woo](https://cloud.githubusercontent.com/assets/6078370/25088310/b952bfbc-2375-11e7-81fc-c8410aacceb6.png)

The same happens when opening a page above 1024px and then resize the browser to below 1024px….. the gap will also occur until 768px is reached but less as the original min-height value is not so big as below 768px.

Pls fix the javascript so one does not have to reload the page and the min-height gets the correct size on resize.

Tested also with default twenty sixteen theme. Same problem occurs.

This fixes temporary fixes the issue !

.woocommerce div.product div.images .woocommerce-product-gallery__image {
	min-height:auto !important;
}

**Comment by mikejolley** [comment]
Caused by https://github.com/woocommerce/woocommerce/pull/12956

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14462 for 3.1.
