### ISSUE TITLE
Coupon Usage/Limit no longer clickable for order search

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#14457]
### EXPLANATION OF THE ISSUE

In versions before v3.0.0 of WooCommerce a site admin could click the usage number on the Coupons screen which would take them to the order list and display all orders which had used that particular coupon.

![screenshot](http://cld.wthms.co/2PD9+) 
**Image Link:** http://cld.wthms.co/2PD9

In WooCommerce v3.0.0 and above however the coupon usage quantity is no longer linked.

![screenshot](http://cld.wthms.co/Q1FP+) 
**Image Link:** http://cld.wthms.co/Q1FP

**Comment by mikejolley** [comment]
@stuartduff This was removed purposely because it's not possible to accurately search orders by coupon. 

See https://github.com/woocommerce/woocommerce/issues/13568 for background. 

And see https://github.com/woocommerce/woocommerce/issues/13570 for what we need in core to support this.
