### ISSUE TITLE
Select 2 issue.

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#14453]
WOO has issues keeping product items in selected order with the new select2 script.

To create the issue do the following

1) select 3 upsells or related products  in random order and save the single product. 

2) Now suppose you want the middle upsell or related product to be last in order. Delete the middle one from the selected products and select it again. One would expect that it will be added last to the item list of selected upsell or related products but it will go back to the middle position. 

3) If however you save the product first after deleting the middle one then go back to the upsell or related products field and add the deleted  product back in again it then will be added at the end of the selected products and you have it at the correct location. Very cumbersome !

This is caused by the new select2 script. In the old version it was just added ad the end of the selected items and no need for a extra save of the product.

This was never a issue in the pre woo v 3.0 versions. By changing the select2 script of which its developers say that it is a mayor and better update they wrecked that nice ability to keep the selected order.

**Comment by mikejolley** [comment]
I get that a bunch of theme authors are going berserk over this change, and this has been argued in other places, but at the end of the day this is a Select2 limitation. 

Reverting to select2 v3 _is not an option_ - themes and plugins have already been updated to v4. Select2 themselves have stated this is not a bug and was never intended to be a 'feature'.

The USE CASE you just presented is invalid. Custom ordering has never been supported. Upsells/cross sells get sorted before display:

https://github.com/woocommerce/woocommerce/blob/f57dee51572f048c308a8cf15025c84d8ba7e119/includes/wc-product-functions.php#L1043-L1063

**Default is random order.**

**But one thing you're missing is we actually support select v4 sorting of options.** Add `data-sortable="true"` to your select2 select box and boom, you can sort the values and the order is preserved on save. You're welcome :)
