### ISSUE TITLE
Refunds not reflected in reports properly

### ISSUE THREAD

**Issue by f3bruary** [woocommerce/woocommerce#14456]
WooCommerce 3.0.3
Wordpress 4.7.3

On March 31 I received an order valued 39.95 EUR. On April 8, I refunded this. (Go to order > Click Refund > select the product from the line (both the price and tax) ).

When I look at the report, both the graph as the csv export have omitted all the refunds that were made...

It should instead show up in the graph (red line), and in the refund column from the csv export.

### STEPS TO REPRODUCE THE ISSUE

1. Receive an order, and refund it...

### SYSTEM STATUS

<details>
```
### WordPress Environment ###

Home URL: https://
Site URL: https://
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 128 MB
PHP Time Limit: -1
PHP Max Input Vars: 1000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_supershoes
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (46) ###

BackWPup: door Inpsyde GmbH – 3.3.7
Breadcrumb NavXT: door John Havlik – 5.6.0
Broken Link Checker: door Janis Elsts
Vladimir Prelovac – 1.11.2

Contact Form 7 MailChimp Extension: door Renzo Johnson – 0.4.43
Contact Form 7: door Takayuki Miyoshi – 4.7
Cookie Notice: door dFactory – 1.2.38
Dashboard Widgets Suite: door Jeff Starr – 1.3
Google Tag Manager for Wordpress: door Thomas Geiger – 1.5.1
Easy Theme and Plugin Upgrades: door Chris Jean – 2.0.0
Jetpack door WordPress.com: door Automattic – 4.8.2
Loginizer: door Raj Kothari – 1.3.4
MailChimp for WooCommerce: door MailChimp – 1.1.1
MailChimp voor WordPress: door ibericode – 4.1.1
Mollie Payments for WooCommerce: door Mollie – 2.5.4
My Custom Functions: door Arthur Gareginyan – 3.5
Nextend Facebook Connect: door Nextendweb – 2.0.2
Nextend Google Connect: door Roland Soos
Jamie Bainbridge – 1.6.1

PixelYourSite PRO: door PixelYourSite – 6.0.4
WooCommerce Product Filter: door Mihajlovic Nenad – 6.1.1
Product Catalog Feed Pro by PixelYourSite: door PixelYourSite – 3.1.8
WooCommerce Pushover Integration: door Shop Plugins – 1.0.11
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 2.2.6
Search & Replace: door Inpsyde GmbH – 3.1.2
SG Optimizer: door SiteGround – 3.2.3
Simple Tags: door Amaury BALMER – 2.4.6
Two Factor Authentication: door David Nutbourne + David Anderson
original plugin by Oskar Hane – 1.2.21

Woocommerce Advanced Bulk Edit: door George Iron – 4.1.5
WooCommerce Advanced Free Shipping: door Jeroen Sormani – 1.1.0
WooCommerce DYMO Print Product Add-on: door WP Fortune – 3.0.4
WooCommerce DYMO Print: door WP Fortune – 3.0.5
Woocommerce Mailchimp Discount: door Magnigenie – 2.0
WooCommerce MyParcel: door Ewout Fernhout – 2.2.0
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 1.6.4
WooCommerce Point of Sale: door Actuality Extensions – 4.0.2
WooCommerce Product SKU Generator: door SkyVerge – 2.3.1
WP All Import - WooCommerce Add-On: door Soflyy – 1.3.2
WooCommerce: door Automattic – 3.0.3
WooSidebars: door WooThemes – 1.4.3
WordPress Importeerder: door wordpressdotorg – 0.6.3
Yoast SEO: door Team Yoast – 4.6
WP All Export: door Soflyy – 1.1.3
WP All Import: door Soflyy – 3.4.2
WP Instagram Widget: door Scott Evans – 1.9.8
WP Migrate DB: door Delicious Brains – 0.9.2
Categorieën naar tags omzetter importeur: door wordpressdotorg – 0.5
YITH WooCommerce Wishlist: door YITHEMES – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
heren (heren)
simple (simple)
variable (variable)
veterschoenen (veterschoenen)
zwart (zwart)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Winkelbasis: #2910 - /winkel/
Winkelmand: #2911 - /winkelmand/
Afrekenen: #2912 - /afrekenen/
Mijn account: #2913 - /mijn-account/

### Theme ###

Name: Flatsome
Version: 3.3.4
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een subthema aan. Zie: Hoe maak je een subthema

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
```
</details>

**Comment by f3bruary** [comment]
I'd like to add that it does appear in the left column next to the graph. But the amount is clearly not visible in the graph (nor in the csv export)

![selection_011](https://cloud.githubusercontent.com/assets/5641933/25089344/208ac24a-237d-11e7-9f18-0b7cfc439917.png)

**Comment by mikejolley** [comment]
The refund shows up when it was made (april) not when the order was made (march).

**Comment by f3bruary** [comment]
The order was made on March 31. The refund was on April 8. The image above shows the report of april, which doesn't have any refunds, although it's showed in the sidebar. 8 april is in the middle and should have 39.95 in refunds

**Comment by mikejolley** [comment]
@f3bruary When you performed the refund, did you fill in the 'refund total' box manually?

And was it full or partial?

**Comment by f3bruary** [comment]
I have several refunds, one of which is partial. The others are full. I did not set the amount manually, I used the product line above by +1'ing the price+tax.

**Comment by f3bruary** [comment]
Like so. I did notice the tax on the shipping is missing.

![selection_013](https://cloud.githubusercontent.com/assets/5641933/25093056/c9495e60-2390-11e7-850e-a73ab778cd2c.png)

**Comment by mikejolley** [comment]
Odd, if you change the filter to 7-9 what does the chart look like then?

**Comment by f3bruary** [comment]
Which filter is this ? You mean the date range ? Cause I don't have data for those months.

**Comment by mikejolley** [comment]
yes the date range. 7th april to 9th april.

**Comment by f3bruary** [comment]
Same issue. It appears in the sidebar, but not in the graph or csv export.

**Comment by mikejolley** [comment]
I've got it working my side https://dl.dropboxusercontent.com/s/knc3dk05q7rdnrr/2017-04-17%20at%2016.50.png

I'm worried there are query-altering plugins on your site. The order screenshot itself looks fine.

**Comment by f3bruary** [comment]
Oh that sounds scary.

I was just looking at some other dates and on April 4 I have a refund of 25 EUR. But I can't find it anywhere in the Orders page..

**Comment by f3bruary** [comment]
I tried disabling all plugins except WooCommerce but it's still the same. I'm not sure which plugin can cause this. I've been using WooCommerce since ~January and it has always been working fine until now. I was working on my bookkeeping today as I was a few weeks behind. I'm not sure what to do now as the financial info might be off. I think it has to do with the 3.X update of WooCommerce, but I'm not sure how to find out.

**Comment by mikejolley** [comment]
After disabling plugins, go save an order. If you don't do this, the results may be cached.

**Comment by f3bruary** [comment]
Done, but still the same unfortunately

**Comment by f3bruary** [comment]
Another weird thing happened after re-saving the order. The breakdown is messed up now. See image
![selection_015](https://cloud.githubusercontent.com/assets/5641933/25095396/dd05a840-239b-11e7-8ec2-4df0c389e5ee.png)

**Comment by mikejolley** [comment]
The total has changed. Saving does not recalculate anything though. It looks like something is messing with the values :/ Are you 100% sure there is no custom code or plugins active right now?

**Comment by f3bruary** [comment]
Yes, I'm sure. I disabled ALL plugins except WooCommerce. I kept custom functions in a plugin that manages them and since that is disabled as well, no functions can be messing with the data now. Would it help if I tested with the twentysixteen theme ?

**Comment by f3bruary** [comment]
I enabled plugins 5 at a time, each time re-saving the order. I wanted to see if it would change back the way it was before when a certain plugin was activated. All plugins are active now but the order is still the same, showing the wrong total and breakdown...

**Comment by claudiosanches** [comment]
@f3bruary 

> Would it help if I tested with the twentysixteen theme ?

Still make a theme could be doing something to impact on it.

**Comment by f3bruary** [comment]
I also tested with another theme but it's the same. It was a long shot anyways. Any help is appreciated... :(

**Comment by mikejolley** [comment]
I think the save recalc may have been different - if the line items had been open for editing it may have triggered recalc.

The refund is a separate issue however, and thats the one I still cannot replicate. If you send me a login privately I can take a look.

**Comment by f3bruary** [comment]
Sent! Let me know if I can help...

**Comment by mikejolley** [comment]
@f3bruary where did you send this?

**Comment by f3bruary** [comment]
@mikejolley to your @me.com address
