### ISSUE TITLE
Problem with rounding taxes

### ISSUE THREAD

**Issue by pavelevap** [woocommerce/woocommerce#14458]
Hi,

there is a price difference 0,01 for some orders (price including tax), please see our example:

![image](https://cloud.githubusercontent.com/assets/3008007/25089065/562c9330-237b-11e7-8ee1-2e8b8ba04c28.png)

Total tax should be 273,34 Kč (sum of all items taxes), but instead of this there is 273,35 Kč.

![image](https://cloud.githubusercontent.com/assets/3008007/25089682/6b00a1da-237f-11e7-99fc-97933ea0b487.png)

Our products prices were 350 and 25 (shipping added as 123,97 to achieve 150 with tax), marked by blue color. Each items tax should be rounded, so I am not sure, how it is possible that `tax_total` is 247,314, but expected is 247,31? Also `shipping_tax_total` should be 26,03, but WooCommerce uses 26,0337. So, in the end WooCommerce take 273,3477 as a tax result and round it to 273,35 which is wrong and should be 273,34 (sum of all order items).

We have one standard tax rate (21 %).

![image](https://cloud.githubusercontent.com/assets/3008007/25089201/17369d1e-237c-11e7-9c40-7af96d1fc519.png)

Tax settings:

![image](https://cloud.githubusercontent.com/assets/3008007/25089226/3b7bde50-237c-11e7-9784-ccdf7fa71486.png)

Only one shipping method (flat rate), price 123,97 Kč (I did not find a way to insert the whole price with VAT = 150,00 Kč):

![image](https://cloud.githubusercontent.com/assets/3008007/25089255/5f6e8ea2-237c-11e7-9e5d-c42afbfcab3d.png)

Using latest WooCommerce 3.0.3, Twenty Seventeen, no plugins activated.

**Comment by mikejolley** [comment]
This is just an abnormality due to you adding up: 60.74+4.34+60.74+121.49+26.03 Those are ROUNDED for display (round half down when using tax inclusive pricing).

The actual tax calculation does not round each line tax. If you edit those line items you'll see the actual tax values which may have more than 2 decimals. Taxes and line items in 3.0 use 4dp precision.

In your spreadsheet, you said that 273.3477 should be rounded to 273.34 but thats not correct. That rounds up to 273.35.

To avoid these types of rounding issues (because it's a math problem, not something we can work around), use tax exclusive prices. Calculations are more straightforward when prices are exclusive of tax.

Hope that all makes sense anyway. 

https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce

**Comment by pavelevap** [comment]
@mikejolley: Thank you, but it is not abnormality, I guess. I found another strange thing. I did not make any changes in this order, but only clicked "Save order" and tax was automatically changed to the right value of 273,34 Kč (basic value magically decreased from 273,3477 to 273,3437). Any idea why? This behaviour should be at least consistent.

![image](https://cloud.githubusercontent.com/assets/3008007/25096047/cc0dadbe-239e-11e7-81a0-97c83b8c651c.png)

So, when order is placed, everything (email, invoice) is sent with wrong tax value, but when I resave order without any change, there is another value?

I am not saying that 273,3477 should be rounded to 273,34. I am saying that WooCommerce is using number 273,3477 and rounds it to 273,35 which is mathematically correct, but **WooCommerce should take sum of rounded values** 60,74 + 4,34 + 60,74 + 121,49 + 26,03 = 273,34. When these numbers are displayed on invoices, there is no reason to show another number 273,35 as tax total? It leads to many problems with accounting systems, etc.

> The actual tax calculation does not round each line tax. If you edit those line items you'll see the actual tax values which may have more than 2 decimals. Taxes and line items in 3.0 use 4dp precision.

This is not correct. I tried to edit order items, but there are following values: 60,74 + 4,34 + 60,74 + 121,49 = 247,31 (there is 2dp precision). Only shipping is not rounded with value 26,0337, see attached screenshot.

![image](https://cloud.githubusercontent.com/assets/3008007/25096473/aa05f4fe-23a0-11e7-9c49-13427869432b.png)

So, how could be `tax_total` = 247,314 and not 247,31? And why is `shipping_tax_total` not rounded to 26,03?

**Comment by mikejolley** [comment]
Hmm I wonder if we are rounding to 2dp after checkout. But actual sums during cart however will be using 4dp. This is looking familiar - the 2dp save thing may have been a fix for something else. I'll dig around the issues tommorrow.

**Comment by mikejolley** [comment]
Traced to https://github.com/woocommerce/woocommerce/commit/54256c4123b5aa948f181c9ecf1d2b98d7974060. Looks like the rounding to help with display may have thrown off the calculations. 

We were also looking at increasing precision to 6 - let me revert that and add to a PR then you can try it out and I can run tests.

**Comment by pavelevap** [comment]
Thank you very much, I can test it tomorrow! I also tried to debug cart content with `get_cart()` method and there was also 2dp on checkout: `["line_tax"]=>float(60.74)` (for 4dp it should be 60.7438).

But the main issue is that **WooCommerce should use sum of rounded values of all line items (including shipping) to get total tax value** to avoid small (but important) differences. When tax is rounded for all line items and rounded values are for example displayed on invoices, then total tax should respect this behaviour and use sum of all line taxes (and do not round different value). There are many problems reported by our accountants when `sum of items taxes != total tax` (and it should).

Probably also related: #14422

**Comment by mikejolley** [comment]
This is experimental, but let's continue this in https://github.com/woocommerce/woocommerce/pull/14475 where I've made some changes which may help this.
