### ISSUE TITLE
"Billing email is a required field." error...

### ISSUE THREAD

**Issue by chrispthomas1990** [woocommerce/woocommerce#14465]
Hi,

I am getting an error on the Checkout page saying 'Billing email is a required field.' even though the billing email has been filled in.

I am running Version 3.0.3 of WooCommerce, version 4.7.3 of WordPress, and I am using the following hooks in my child theme's functions.php file:

```
// WooCommerce Checkout Fields Hook
add_filter( 'woocommerce_checkout_fields' , 'hjs_wc_checkout_fields' );
 
function hjs_wc_checkout_fields( $fields ) {
 $fields['billing']['billing_email']['label'] = 'Email';
 $fields['shipping']['billing_email']['label'] = 'Email';
 $fields['billing']['billing_email']['required'] = true;
 $fields['billing']['billing_email']['placeholder'] = '';
 $fields['shipping']['billing_email']['placeholder'] = '';
 $fields['billing']['billing_address_1']['placeholder'] = '';
 $fields['shipping']['shipping_address_1']['placeholder'] = '';
 $fields['billing']['billing_address_2']['placeholder'] = '';
 $fields['shipping']['shipping_address_2']['placeholder'] = '';
 $fields['order']['order_comments']['placeholder'] = '';
 return $fields;
}
```

You can see the site I'm working on here: http://www.pratimakramer.co.uk/dev/product/pk130/
If you go though and 'Add to Cart' and complete the purchasing process you'll see the issue for yourself on the Checkout page.

Apologies for any naivety, this is my first GitHub post.

Many thanks,

Chris

<details>
### WordPress Environment ###

Home URL: http://www.pratimakramer.co.uk/dev
Site URL: http://www.pratimakramer.co.uk/dev
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.1.73 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (11) ###

Akismet Anti-Spam: by Automattic – 3.3
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Login: by Austin Passy – 3.2.5
Redirection: by John Godley – 2.5
Simple Image Sizes: by Rahe – 3.1.1
The Grid: by Themeone – 2.3.5
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.0
WooCommerce Product Navigation: by WP BackOffice – 1.0.0
WooCommerce Social Media Share Buttons: by Toastie Studio – 1.3.0
WooCommerce: by Automattic – 3.0.3
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.28

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #72 - /shop/
Basket: #73 - /basket/
Checkout: #74 - /checkout/
My account: #75 - /my-account/

### Theme ###

Name: Pratima Kramer
Version: 1.0.0
Author URL: http://www.christhomasdesign.co.uk
Child Theme: ✔
Parent Theme Name: Blask
Parent Theme Version: 1.1.0
Parent Theme Author URL: http://wordpress.com
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –
</details>

**Comment by mikejolley** [comment]
You are adding a 'billing_email' field to the shipping section, but you have no code to handle it correctly. Remove the lines with 'shipping' key. Only billing addresses have emails.

**Comment by chrispthomas1990** [comment]
@mikejolley Thanks that worked perfectly!
