### ISSUE TITLE
Shipping Calculator is not shown on the cart page

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#14461]
With WooCommerce 3.0+ the shipping calculator is no longer shown on the cart page.

In templates/cart/cart-shipping.php the calculator is shown when is_cart is true and $index does not have a true value. The $index is the index value for the current shipping package.

In WooCommerce 2.6 when there was only one shipping package the $index value used to be 0 as it was the first element in the array.

With WooCommerce 3.0+ this has a different index value, even if there is only one shipping package. Because the $Index variable has a value the shipping calculator is never displayed on the cart page.

With multiple shipping packages the calculator should be displayed only once (if it should be displayed at all). But with one shipping package it should always be displayed.

The shipping calculator template itself will check the corresponding setting which allows the user to enable / disable the calculator. This part is working fine.

**Comment by mikejolley** [comment]
Added different handling for 3.1. See https://github.com/woocommerce/woocommerce/issues/14463

**Comment by Nickigreen** [comment]
Has this bug been fixed? I have Woocommerce Version 3.2.1 and can't get the shipping calculator to show on the cart page. How can I fix this? www.bokashiliving.ca/cart
Thanks in advance

**Comment by whitnelson** [comment]
This is also broken for me now. Checking the "Enable the shipping calculator on the cart page" box has no effect after updating the version. The shipping area never appears.
