### ISSUE TITLE
Tooltip arrow position off in rtl

### ISSUE THREAD

**Issue by rellect** [woocommerce/woocommerce#14478]
### EXPLANATION OF THE ISSUE

Tooltip arrow position is off in rtl.
![image](https://cloud.githubusercontent.com/assets/2431842/25118832/8730b0d8-2420-11e7-83cc-cfc7350e7c10.png)

### STEPS TO REPRODUCE THE ISSUE

I tested in Orders page in admin panel.

### SYSTEM STATUS

Tested with master branch

**Comment by emgk** [comment]
@rellect  just tested with master branch, It's working fine in Google Chrome Version 57.0.2987.133 and Firefox 52.0.2. It seems it's a caching issue clear the cache and check again.
