### ISSUE TITLE
Product category is not deleted if image url is invalid

### ISSUE THREAD

**Issue by dNassaro** [woocommerce/woocommerce#14474]
### EXPLANATION OF THE ISSUE

Using the API to send a new category if the image url is not valid (woocommerce_rest_invalid_remote_image_url) the category is not deleted and an error is raised 

### STEPS TO REPRODUCE THE ISSUE

create a new category via API giving and invalid image url 

### POSSIBLE FIX
I think the failing line is 408 in file includes/abstracts/abstract-wc-rest-terms-controller.php
`wp_delete_term( $term['term_id'], $taxonomy );`
should be 
`wp_delete_term( $term->term_id, $taxonomy );`
Making this change fixed the issue for me

**Comment by watchlondon** [comment]
wp_delete_term( $term->term_id, $taxonomy );
