### ISSUE TITLE
CSS customization assistance request @JamesKoster

### ISSUE THREAD

**Issue by GlazerGallery** [woocommerce/woocommerce#14477]
### EXPLANATION OF THE ISSUE

>>James Koster wrote: I'm happy to help with the css customisation to tweak the caption for you. Just open a support ticket and ping me here :)

Thanks for offering to help, James. I generally like left alignment for long captions, too, but I am dealing with bringing in hundreds -- probably a few thousand -- of those smaller images from a legacy site that we are just not going to resize right now. I would be happy with leaving left alignment as the default if it would align to the left bottom corner of the image and appear within 10 to 20 pixels below it. If you can tell me the CSS tag that would do that and which stylesheet it goes in, that would be great. I am comfortable editing the Custom CSS page in the WordPress Dashboard. I also know how to add code to the functions.php and upload it to the server. Also, I have FTP capabilities and can download CSS and PHP pages via Dreamweaver for editing and then upload them back to the site, if that's a better way to make the needed changes.

If that solid black background could be made slightly transparent, I'd like to know how to do that, too.

Also, in the previous version of WooCommerce the image title tag popped up when the mouse hovered over a thumbnail image in the grid below the main product image. Is there a way to bring that feature back? Because I was using that, too.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by jameskoster** [comment]
@GlazerGallery Please open this on the WordPress.org support forums and drop a link to that topic here :)

**Comment by GlazerGallery** [comment]
https://wordpress.org/support/topic/3-0-how-can-i-get/

**Comment by GlazerGallery** [comment]
Find it here: https://wordpress.org/support/topic/3-0-want-to-get-captions-to-align-with-images/
