### ISSUE TITLE
Return Empty Array for get_children()

### ISSUE THREAD

**Issue by hasnatbabur** [woocommerce/woocommerce#14471]
the following code will always return empty array - abstract-wc-product.php

	/**
	 * Returns the children IDs if applicable. Overridden by child classes.
	 *
	 * @return array of IDs
	 */
	public function get_children() {
		return array();
	}

I think something is missed in the logic!

**Comment by claudiulodro** [comment]
The WC_Product class is designed to be extended by other classes, and not to be used as a stand-alone class. Classes that work with children can override that function with one that does something substantial. Here's an example from WC_Product_Grouped: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-grouped.php#L125
