### ISSUE TITLE
product_type_options filter not working

### ISSUE THREAD

**Issue by josiahdwill** [woocommerce/woocommerce#14470]
### EXPLANATION OF THE ISSUE

I've added a filter on product_type_options that enables "virtual" by default on a product and it is no longer working on the latest WooCommerce release. I've reinstalled release 2.6.14 and it works - when running this filter and creating a new product virtual is checked by default as expected. However, in version 3.0.0 and 3.0.3 virtual is not checked by default. 

### STEPS TO REPRODUCE THE ISSUE

1. Add this code to functions
```
/Sets default product type options
add_filter( 'product_type_options', 'wc_product_type_options' );
function wc_product_type_options( $product_type_options ) {
    $product_type_options['virtual']['default'] = 'yes'; //Enables virtual product by default
    return $product_type_options;
}

```
2. Add a new product
3. Should expect to see that virtual is selected by default. I've verified that the array should default as yes

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by claudiulodro** [comment]
Good catch! It appears there is a logic error on [this line](https://github.com/woocommerce/woocommerce/blob/b16d3a091ce6125470d484fd10c4f71ba6c724b0/includes/admin/meta-boxes/views/html-product-data-panel.php#L15). We'll have this sorted in the next patch release.
