### ISSUE TITLE
Custom Fields Duplicating

### ISSUE THREAD

**Issue by AntBentinck** [woocommerce/woocommerce#14482]
### EXPLANATION OF THE ISSUE

Whenever we duplicate a product on **3.0.3** after each duplication the custom fields seem to be duplicating each time as well.  

This then causes huge delay in pages saving and functioning in the admin area. 

### STEPS TO REPRODUCE THE ISSUE

- Duplicate Product
- Expand Custom Fields Tab
- Duplicate Product
- Expand Custom Fields Tab

### SYSTEM STATUS

<details>

</details>

**Comment by mikejolley** [comment]
Yes, all meta data is duplicated like in v2.6. 

https://github.com/woocommerce/woocommerce/issues/14118
