### ISSUE TITLE
Delete (or update) option to add stand alone order total

### ISSUE THREAD

**Issue by ValeDeOro** [woocommerce/woocommerce#14494]
### EXPLANATION OF THE ISSUE

When creating a new order, the little pencil next to "order total" indicates that the total can be adapted manually: 

![](http://cld.wthms.co/MiXx+)
Link to screenshot: http://cld.wthms.co/MiXx

However this does not work as expected. The total always goes back to "cero": 

![](http://cld.wthms.co/xeMY+)
Link to screenshot: http://cld.wthms.co/xeMY

Can we either remove the little "edit" pencil or make it work :)

### STEPS TO REPRODUCE THE ISSUE

Create a new order
Without adding any fees or products, try to change the order total.

**Comment by mikejolley** [comment]
This is auto-calculated - nothing even handles it. Removing :)
