### ISSUE TITLE
PayPal Gateway Error

### ISSUE THREAD

**Issue by Nigel-S** [woocommerce/woocommerce#14495]
### EXPLANATION OF THE ISSUE

I am using the latest versions of both WP (4.7.3) and WC (3.0.3) and since the 13th of this month have been experiencing an issue with the in-built PayPal Gateway.

On selecting "Proceed to PayPal" the Checkout Page Reloads with  the message "Service Unavailable" at the top (just above "Billing Details").

I have spoken to PayPal Technical and they managed to replicate the error immediately.

They advise me that they updated their security on the 13th and the problem is a "Syntax Error in the PayPal module withing Woocommerce".

### STEPS TO REPRODUCE THE ISSUE

Visit https://www.airsoft-action.online/shop/13-issue-subscription-uk/

Click the "Sign Up Now" button.

Proceed to the Cart and then Checkout.

Complete the relevant details, select PayPal as the payment option and click "Proceed To PayPal" button.

Wait...

The error will be displayed at the top of the reloaded page.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
<details>
`
### WordPress Environment ###

Home URL: https://www.airsoft-action.online
Site URL: https://www.airsoft-action.online
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.6.30
PHP Post Max Size: 52 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 52 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔  No
Subscriptions Mode: ✔  Live

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: aa_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

WeatherSlider WP: by Kreatura Media – 2.6.7
Akismet Anti-Spam: by Automattic – 3.3
Caldera Forms: by Caldera Labs – 1.5.0.8
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.43
Contact Form 7: by Takayuki Miyoshi – 4.7
Cornerstone: by Themeco – 2.0.3
Custom Facebook Feed: by Smash Balloon – 2.4.5
Easy WP SMTP: by wpecommerce – 1.2.5
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
Google Language Translator: by Rob Myrick – 5.0.30
Google XML Sitemaps: by Arne Brachhold – 4.0.8
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp for WordPress: by ibericode – 4.1.1
Official StatCounter Plugin: by Aodhan Cullen – 2.0.1
Page Specific Menu Items: by Dharma Poudel (@rogercomred) – 1.6.5
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Slider Revolution: by ThemePunch – 5.4.1
SAM Pro (Free Edition): by minimus – 2.0.1.76
Search Everything: by Sovrn
zemanta – 8.1.9

Simple Lightbox: by Archetyped – 2.6.0
Stop Spammers Spam Control: by Keith P. Graham – 6.15
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

WooCommerce - Autocomplete Orders: by Serious Plugins – 1.1.4
Follow-Up Emails: by 75nineteen Media LLC – 4.4.14 – 4.4.19 is available
WooCommerce Braintree Gateway: by WooThemes / SkyVerge – 3.0.1 – 3.3.2 is available
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.2 – 2.4.3 is available
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.4
WooCommerce Subscriptions: by Prospress Inc. – 2.0.17
WooCommerce: by Automattic – 3.0.3
WooReports API: by Lucian Capdefier (luciancapdefier) – 2.0.1
WordPress Social Stream: by Lee Chestnutt – 1.5.15
WP Fastest Cache: by Emre Vona – 0.8.6.8
WP Google Map Pro: by flippercode – 4.0.0
WP Joomag: by Joomag. – 2.5.0
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP Adverts: by Greg Winiarski – 1.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable-subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /basket/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: X – Child Theme
Version: 1.0.0
Author URL: http://theme.co/
Child Theme: ✔
Parent Theme Name: X
Parent Theme Version: 4.6.4
Parent Theme Author URL: http://theme.co/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: x/woocommerce/cart/cart-empty.php
x/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
x/woocommerce/loop/loop-end.php
x/woocommerce/loop/loop-start.php
x/woocommerce/loop/pagination.php
x/woocommerce/notices/error.php
x/woocommerce/notices/notice.php
x/woocommerce/notices/success.php
x/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.0.2
x/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.0.2
x/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
x/woocommerce/single-product/tabs/tabs.php
x/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
x/woocommerce/single-product-reviews.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
You've attached no system status report, nor provided logs from PayPal so we can see what args are sent. Not enough information to even confirm a bug yet.

**Comment by Nigel-S** [comment]
Err... Yes, I did, between the <details></details> tags, as requested.

Nigel.

**Comment by mikejolley** [comment]
Ok, it was double nested
![2017-04-18 at 20 09](https://cloud.githubusercontent.com/assets/90977/25148477/f977a62c-2472-11e7-8e48-8affb8f4a707.png)

You're not on latest subs - is this a subscription product?

http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-subscriptions/changelog.txt

**Comment by Nigel-S** [comment]
Was on the site when I took it over and assume so.

**Comment by mikejolley** [comment]
There are a whole bunch of PayPal related notes in the changelog, so I think you'll need to update to the latest version which also has WC 3.0 compatibility. As for the PayPal security changes, we worked through these in core with them a few months back so standard PayPal payments through WC are compliant.
