### ISSUE TITLE
woocommerce_process_product_file_download_paths action fail

### ISSUE THREAD

**Issue by MahmudHamid** [woocommerce/woocommerce#14503]
Running the action hook woocommerce_process_product_file_download_paths fails due to treating the downloads array as an object.

```
public static function process_product_file_download_paths( $product_id, $variation_id, $downloads ) {
        if ( $variation_id ) {
            $product_id = $variation_id;
        }
        $product    = wc_get_product( $product_id );
        $data_store = WC_Data_Store::load( 'customer-download' );

        if ( $downloads ) {
            foreach ( $downloads as $download ) {
                $new_hash = md5( $download->get_file() );

                if ( $download->get_previous_hash() && $download->get_previous_hash() !== $new_hash ) {
                    // Update permissions.
                    $data_store->update_download_id( $product_id, $download->get_previous_hash(), $new_hash );
                }
            }
        }

```
Also why would we need to get the $product when it is unused?

**Comment by mikejolley** [comment]
Your comment on`product` is valid, but downloads are an object.

**Comment by mikejolley** [comment]
@claudiulodro The variation downloads PR you did covers this right? See class-wc-product-data-store-cpt.php:

```
			if ( $product->is_type( 'variation' ) ) {
				do_action( 'woocommerce_process_product_file_download_paths', $product->get_parent_id(), $product->get_id(), $downloads );
			} else {
				do_action( 'woocommerce_process_product_file_download_paths', $product->get_id(), 0, $downloads );
			}

```

Should be able to remove `$product`.

**Comment by claudiulodro** [comment]
@mikejolley I'm not 100% sure what you're asking. `process_product_file_download_paths` should always be getting an array of Download objects  as the third parameter, if that's what you're asking.

[Here's the PR](https://github.com/woocommerce/woocommerce/pull/14401/files). Regardless if we're using `WC_Product_Data_Store_CPT::read_downloads` or just setting downloads with metadata straight from the DB, `WC_Product::set_downloads` handles both and turns everything into Download objects. 

I believe the only thing to do here is remove the unused `$product` from `process_product_file_download_paths`.
