### ISSUE TITLE
After removing a product from a grouped product, the parent/child arrow does not get removed from the title

### ISSUE THREAD

**Issue by edgar-sanchez-is** [woocommerce/woocommerce#14507]
### EXPLANATION OF THE ISSUE

Woocommerce: 3.0.3
Woocommerce Subscriptions: 2.2.2

After removing a group product, the related child products retain the arrow in the product name. 

See screenshot: ![image](http://i.imgur.com/5hdwc2P.png)

### STEPS TO REPRODUCE THE ISSUE

I created a grouped product (let's call it a parent), which I set to private and hidden, then I added three regular subscription products (let's call them children) to it.

This displayed the product title as: `CHILD PRODUCT <- PARENT GROUP`

I later decided that I didn't need the group any more, and so I opened it, removed each child product from it, and then trashed it and emptied the trash.

Now, when I go to my products, they're displayed as: `CHILD PRODUCT <-` with a lingering arrow.

### SYSTEM STATUS

<details>
### WordPress Environment ###

Home URL: https://arkonlabs.com
Site URL: https://arkonlabs.com
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: 7.0.17-2+deb.sury.org~trusty+1
PHP Post Max Size: 1,000 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 98 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

The SEO Framework: by Sybre Waaijer – 2.9.1
SendGrid: by SendGrid – 1.10.9
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

WooCommerce Email Customizer: by WooThemes – 1.1.5
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce Memberships: by SkyVerge – 1.8.1 – 1.8.2 is available
WooCommerce Order Status Control: by SkyVerge – 1.8.0
WooCommerce Subscriptions: by Prospress Inc. – 2.2.2 – 2.2.4 is available
WooCommerce: by Automattic – 3.0.3
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.2.1

Akismet Anti-Spam: by Automattic – 3.3
Ultimate Branding: by WPMU DEV – 1.8.3.1
Elegant Themes Updater: by Elegant Themes – 1.1
WP Security Audit Log: by WP White Security – 2.6.1
Jetpack by WordPress.com: by Automattic – 4.8.2
Domain Mapping: by WPMU DEV – 4.4.2.4
Wordfence Security: by Wordfence – 6.3.6
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WPMU DEV Dashboard: by WPMU DEV – 4.3
W3 Total Cache: by Frederick Townes – 0.9.5.2
SendGrid: by SendGrid – 1.10.9
Network Username Restrictions Override: by Joseph Rafferty – 1.3
The SEO Framework: by Sybre Waaijer – 2.9.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #81 - /cart/
Checkout: #82 - /checkout/
My account: #83 - /my-account/

### Theme ###

Name: Divi - ArkonLabs
Version: – 0 is available
Author URL: http://arkonlabs.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.40
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
</details>

**Comment by mikejolley** [comment]
Thanks, these need to be unset during the update routine.

I'm going to tweak the `wc_update_300_grouped_products()` function to handle unsetting the post_parent during upgrade. To fix your site you can either re-run that function after patched, or unset the post_parent via the database for the affected products.

**Comment by phillipcornwell** [comment]
@claudiulodro @claudiosanches A user has products showing these same left arrows. I have a couple of products on my test site with them as well but in my case, they were never part of a grouped product and I do not know how they were "applied" to the product:

![Screenshot](https://cld.wthms.co/MQYDNV+)
Screenshot direct link: https://cld.wthms.co/MQYDNV

Can someone shed some light on this for me? I found I can remove the arrows by saving the products as something other than a Simple product then back again. Thanks :-)

**Comment by joshuaiz** [comment]
I'm seeing this issue as well. None of my products are grouped or linked in any way and I have arrows on some but not on others.

Anyone know what is causing this and how to fix? 

Any products with these arrows are not getting returned via WooGraphQL queries.
