### ISSUE TITLE
Follow up to #14477 @JamesKoster

### ISSUE THREAD

**Issue by GlazerGallery** [woocommerce/woocommerce#14511]
### EXPLANATION OF THE ISSUE

See https://wordpress.org/support/topic/3-0-want-to-get-captions-to-align-with-images/ as per your request to post it there.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by claudiulodro** [comment]
@jameskoster (I don't think it notifies you if the name is in the title)

**Comment by jameskoster** [comment]
A comment on the original issue would have been sufficient @GlazerGallery xD

No worries. I'll reply on the forum asap.
