### ISSUE TITLE
"grey out" out of stock options for variable products fail when lot of variations

### ISSUE THREAD

**Issue by dappi** [woocommerce/woocommerce#14514]
I have followed the steps in this thread and it works when I have few variations. But on some products I have +100 variations and then the disabling of varion doesn't work anymore. Why  is that? Seem's it doesn't go that function at all.

Function in use:

```
add_filter( 'woocommerce_variation_is_active', 'grey_out_variations_when_out_of_stock', 10, 2 );

function grey_out_variations_when_out_of_stock( $grey_out, $variation ) {

    if ( ! $variation->is_in_stock() )
        return false;

    return true;
}
```

https://github.com/woocommerce/woocommerce/issues/5661

**Comment by mikejolley** [comment]
> 30 switches to ajax loading.

Increase with https://gist.github.com/claudiosanches/6f91ad228c2176b986b2

**Comment by jstephenJF** [comment]
Was there ever an actual fix for this? to me this seems more like a workaround than a fix. I currently have a couple products that have up to 100 variations, I could increase that threshold to 200 just to be safe but I imagine it was set to 30 for a reason. I would think any hooks or filters should still be applied regardless of whether that part was loaded via ajax.
