### ISSUE TITLE
Fatal error: Uncaught Error: Class 'WC_REST_System_Status_Controller' not found

### ISSUE THREAD

**Issue by dancalder** [woocommerce/woocommerce#14517]
### EXPLANATION OF THE ISSUE
Version 3.0.3
Viewing system status
Produces following error:
Fatal error: Uncaught Error: Class 'WC_REST_System_Status_Controller' not found in /home/dev/public_html/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-status-report.php:11 Stack trace: #0 /home/dev/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php(31): include_once() #1 /home/dev/public_html/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-status.php(41): WC_Admin_Status::status_report() #2 /home/dev/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php(24): include_once('/home/dev/publi...') #3 /home/dev/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(218): WC_Admin_Status::output() #4 /home/dev/public_html/wp-includes/class-wp-hook.php(298): WC_Admin_Menus->status_page('') #5 /home/dev/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #6 /home/dev/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #7 /home/dev/public_html/wp-admin/admi in /home/dev/public_html/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-status-report.php on line 11

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Have you disabled the rest API on your site? It's needed here.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/14526 will check to see if it does not exist and die if missing. We use the REST API classes for this report so disabling it will break this functionality.
