### ISSUE TITLE
Wrong spelling of Related Products on line 27 in templates/single-product/related.php

### ISSUE THREAD

**Issue by mumbomedia** [woocommerce/woocommerce#14516]
### EXPLANATION OF THE ISSUE

The issue is that the text "Related products" isn't translated. This is caused by a different writing in the language file. In the language file the string is written "Related Products" but in the template the word "products" is written in lowercase. Therefore the translation isn't found. 
The the codepoints in the comments  also are not  correct, because this string was on line 27 and not on 51 as mentioned in the language file.

### STEPS TO REPRODUCE THE ISSUE

Use a different language like de_DE.
You will see, that this text isn't translated because no translation is found because translation are case sensitive and use comments to determine the correct translation if there more than one.

I have point out this issue also in the support forum of woocommerce and I am really disappointed that I have to point it out again and it is still not fixed because is a little issue which could be fixed in no time.

**Comment by mikejolley** [comment]
Directing you to https://wordpress.org/support/topic/updating-translations-after-updates/

I'm not German speaking, nor am I on the translation team to approve strings. This has to be changed on GlotPress. https://translate.wordpress.org/projects/wp-plugins/woocommerce

**Comment by mumbomedia** [comment]
Now, I am even more disappointed.
I have wrote this in the woocommerce support forum because I could approve if this is an issue in the php-file or in the translation file. But I have look into some translation and in all translation I have seen the word product is in lowercase. They advise me to post it here and now I should post on Glotpress. Are you serious? My intention was to inform the developers of woocommerce so that they could check it and fix it in their way. But now I believe they don't want to get informed.

**Comment by mensmaximus** [comment]
'Related Products' is missing in the woocommerce.pot file at all.

**Comment by mumbomedia** [comment]
@mensmaximus 

lol, I know this.
But the word "Related products" is in the pot file, but the source comment doesn't match exactly. The file name is ok but the line isn't correct. Is not 51  it is 27. So the question is: Is the php file correct or the pot-file. I don't know.
That's what I am saying since 3 days.

**Comment by mensmaximus** [comment]
My bad. Just updated the translation files and 'Related products' is in the .pot as well as perfectly translated in the german .po file

**Comment by mumbomedia** [comment]
Yes, but this didn't help because the translation a case sensitive and in the php file the word products starts with a uppercase character. So there a 2 options. update every language file to match the php file which would be a large amount of work or change the character in the php file which would only cost a sec.

**Comment by mensmaximus** [comment]
related.php line 27
esc_html_e( 'Related products', 'woocommerce' );

woocommerce.pot
#: templates/single-product/related.php:27
msgid "Related products"

woocommerce-de_DE.po
#: templates/single-product/related.php:27
msgid "Related products"

There are no uppercase versus lowercase issues in the most resent translations.

Maybe you have a theme that overloads the related.php file from woocommerce

**Comment by mumbomedia** [comment]
No I haven't.
I have change it in the original file of woocommerce.
I seen this issue by changing the language to de_DE_formal.
If it is also in this translation, the issue is fixed.

**Comment by mikejolley** [comment]
The topic I linked to shows how to update your PO file if using a custom translation.

Otherwise this simply needs to be updated on GlotPress (if not already, it looks 100%). "Related products" with the sentence case is correct going forward.

**Comment by mumbomedia** [comment]
I don't use a custom translation for woocommerce. The german formal translation looks good to me, so from my side there is no need to customize it. But if I need to I know how to make this. My company runs some websites with woocommerce and we and also our customers are very happy with it.
I have version 3.0.1 installled and could update to 3.0.3 which I will do.
