### ISSUE TITLE
Products with 'pending' status are duplicated without any warning..

### ISSUE THREAD

**Issue by maximumver** [woocommerce/woocommerce#14525]
### EXPLANATION OF THE ISSUE

Not sure if bug or feature. 
If we will try to create the product with same 'sku' multiple times with 'pending' status it will be created, no matter how many copies we've created before, only if status of the product 'publish' there will be the check for existing products & we will get an error of 'invalid sku'

If this is the feature what is the best way to not create duplicates while importing products with 'pending' status? When some client imports same CSV twice i'll have a lot of duplicates with 'pending' status.

Yeah, while writing this issue i've become quite sure that's a feature & it must be so (sorry, in that case)

Thank you for your work!

**Comment by mikejolley** [comment]
'pending' - is that even a valid status?

**Comment by maximumver** [comment]
https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

> status	string	Product status (post status). Options: draft, pending, private and publish. Default is publish.

**Comment by maximumver** [comment]
By the way, 'draft' & i maybe even 'private'  are duplicated too(not sure).
Then when i do bulk edit from 'admin dashboard' of all pending products, all that clones are published, doesn't matter they have same 'sku'.

**Comment by mikejolley** [comment]
Ah yes pending is valid. https://codex.wordpress.org/Function_Reference/get_post_status

**Comment by maximumver** [comment]
However if i can accept duplicates of 'draft' or even 'pending' products as a feature, i can't understand why products with 'private' status are also duplicated, those should definitely return 'sku' error if same 'private' product already exists, imho

**Comment by mikejolley** [comment]
It should check all post types unless trashed. Fixing now.

**Comment by maximumver** [comment]
oh, good news, thanks 👍
