### ISSUE TITLE
Customers are notified even when backorders are allowed and "Allow" is selected.

### ISSUE THREAD

**Issue by BSWWill** [woocommerce/woocommerce#14530]
### EXPLANATION OF THE ISSUE

After updating to Woo 3.0 I noticed that I lost the backorder functionality where selecting "allow" still notifies the customer. the only way I can avoid it is if I uncheck manage stock. many of my products are drop shipped so this is an issue and i lost a lot of sales from it. I Use stitch labs as well.

www.mtgtactical.com

### STEPS TO REPRODUCE THE ISSUE

Create a product where stitch labs is the master of stock.

Click manage stock, allow backorders, and select "allow" instead of notify customer.

the product page will show "Available on backorder"

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: https://megiddotacticalgroup.com
Site URL: https://megiddotacticalgroup.com
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 350 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 mod_fcgid/2.3.9
PHP Version: 5.6.23
PHP Post Max Size: 8 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

AutomateWoo: by AutomateWoo – 2.9.12
Bloom: by Elegant Themes – 1.1.8
Elegant Themes Support: by Elegant Themes – 1.0
Elegant Themes Updater: by Elegant Themes – 1.0
ET Shortcodes: by Elegant Themes – 1.2.1
Instagram Feed Pro Business: by Smash Balloon – 2.4.1
Jetpack by WordPress.com: by Automattic – 4.8.2
Monarch Plugin: by Elegant Themes – 1.3.2
Redirection: by John Godley – 2.5
W3 Total Cache: by Frederick Townes – 0.9.5.2
WC Custom Thank You: by Nicola Mustone – 1.2.0
Woocommerce Advanced Bulk Edit: by George Iron – 4.2.1
WooCommerce Brands: by WooThemes – 1.5.0
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
WooCommerce TM Extra Product Options: by themecomplete – 4.5.2
WooCommerce: by Automattic – 3.0.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.6
WP Edit: by Josh Lobe – 4.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #12 - /shop/
Cart: #13 - /cart/
Checkout: #14 - /checkout/
My account: #15 - /my-account/

### Theme ###

Name: Divi
Version: 3.0.40
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
`Available on backorder` will be displayed if there is 0 or less stock for the item.

Notify setting in 3.0 will show on in stock products, `In stock (available for backorder)`

**Comment by BSWWill** [comment]
So that is a change from prior versions then. In the past selecting allow would not notify the customer. How would I replicate that? I'm losing sales as people don't realize that the items are drop shipped and will be shipped in a timely manner. 
Thanks,
Will

**Comment by mikejolley** [comment]
What would you expect it to show, since these items are not "in stock"? Nothing at all?

**Comment by BSWWill** [comment]
For the last few years if I clicked "allow" and had in stock selected it would not notify the customer that it was out of stock and would in fact mark it as "In Stock". If you wanted to notify the customer then you would select "Allow, but notify customer".

**Comment by BSWWill** [comment]
So, if your first response is correct and woo operates that way under 3.0 then why does it provide three options under the "Allow backorders" tab? What you are saying is the "Allow, but notify customer" and "Allow" selections are essentially the same option. Traditionally selecting allow would hide the fact that it is not in stock. Two selections have the same result? Am I missing something?
Thanks,
Will

**Comment by mikejolley** [comment]
I'm looking at it now; just trying to decide on how it should be presented. Showing 'in stock' is wrong IMO.

**Comment by BSWWill** [comment]
So, 
As a consumer we both probably hate ordering something that is on back order. I assume it probably bothers both of us equally. However, many products online are drop shipped or built after they are ordered by the customer. If we notify the customer then they will assume there is a wait and won’t order. Explaining the intricacies of your fulfillment process is going to make customers eyes glaze over. Just need to re-establish the option to override the backordered notification. My flashlights are shipped directly to the customers via priority mail so they get them faster than most of my competitors is it right that Im penalized because the inventory is at the manufacturer not in my shop? Not he other hand, we don’t build our holsters until the order comes in and then they ship out in three days which is far faster than the industry standard but essentially they are backordered. Hope that explains my dilemma.
Thanks,
Will

William 	
Owner/Editor
BlackSheepWarrior.com
E: Admin@BlackSheepWarrior.com <mailto:Admin@BlackSheepWarrior.com>

Don’t forget to subscribe to my newsletter. Subscribe here <https://www.blacksheepwarrior.com/about-us/subscribe/>

**Comment by mikejolley** [comment]
@BSWWill If you hold no stock at all, why even have manage stock enabled at all? You could just have no stock management and make it 'in stock'.

For the scenarios where back ordering is enabled for whatever reason, I feel we need to display this differently. Either with 'Available on backorder' as in 3.0, or with no string at all. Showing "in stock" in this setup is misleading.

**Comment by BSWWill** [comment]
Thats a good question and here is why. I have some products that I actively manage stock on and I want to make sure that I don't accidentally sell that and put the customer in a real backordered situation.  I use Stitch labs to manage that inventory and so I can't use a blanket approach. I do not agree with your assessment that it is misleading. Is it not right to give the webmaster the control over notifying a customer regarding stock status or not seeing there are so many different products on the market that have different fulfillment options. What if you were selling MAC trucks and the truck models were made after the order was made? As I have attempted to articulate, it is not a black and white approach and it is not a misleading or not issue. It is a tool I have used for years and the update changed it and caused my sales to drop off.  What about changing it to "Available" instead of "in stock"? I really think a change like this while it seams simple and to you may be a morale decision could have huge impacts down the line for sales worldwide. Thanks for interacting on this. Its really a big deal on my end. I would just like it to be returned to the way it was before. Did people complain about how it was?
Thanks,
Will

**Comment by mikejolley** [comment]
@BSWWill Is there a reason you opposed to _no_ output in this scenario?

**Comment by BSWWill** [comment]
I could definitely deal with that. 
Thanks,
Will

**Comment by BSWWill** [comment]
The change was made and I appreciate it greatly. You guys rock.

**Comment by phemels** [comment]
@mikejolley:
I understand that "In stock" is the wrong information when the stock level is 0 and "allow" is selected.
But No information is in my opinion als NOK :(
Why not create a text like "Inform for stock status" when the stock level is 0 and "allow" is selected!

It would be great if that is possible.

**Comment by BSWWill** [comment]
People will not purchase items with anything vague in that area. It's best left to the seller to decide. There is an option to notify the customer for sellers if they want.

**Comment by phemels** [comment]
@BSWWill 
Do you mean the option "Allow, but notify customer"? or is there another option?
Because I want the option "In stock, delivery in 1 a 2 days" (not the message "backorder")

**Comment by BSWWill** [comment]
I think having a custom field option would be great.

**Comment by phemels** [comment]
Sure it would be great, do you have that? or how did you solve your problem v.s. version 2.6

**Comment by BSWWill** [comment]
Well it was a while ago and I haven't reviewed the thread as I'm responding via email. However, I think we agreed on some mitral language verses nothing at all. Currently I see that the drop shipped items on my site don't say anything which is the way it should be. I don't ever select notify customer because I drop ship so it's not backordered. I think you can get a custom plugin for woo that will let you change the verbiage.

**Comment by phemels** [comment]
OK thanks for your input.

**Comment by mikemoorejolley** [comment]
Mike Jolley you are LAME. get off.
