### ISSUE TITLE
Woocommer V3 can't make related products

### ISSUE THREAD

**Issue by bikkel78** [woocommerce/woocommerce#14532]
### EXPLANATION OF THE ISSUE

running latest version of WP and Woocommerce, I cant make related products i.e. upsells and cross sells. The field is blank, and cant get it to do anything

### STEPS TO REPRODUCE THE ISSUE

de activated all plugins related to woocommerce, cleared cache

### SYSTEM STATUS

<details>
WC-versie:		3.0.3
WP-versie:		4.7.3
WP Multisite:		–
WP geheugenlimiet:		512 MB
WP debug-modus:		–
WP Cron:		
Taal:		nl_NL
Serveromgeving
Serverinformatie:		Apache
PHP-versie:		7.0.17-1byte1
PHP post max size:		250 MB
PHP time limit:		0
PHP max input vars:		10000
cURL Versie:		7.26.0, OpenSSL/1.0.1t
SUHOSIN geïnstalleerd:		–
MySQL-versie:		5.6.32
Max upload size:		250 MB
Standaard tijdzone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC-databaseversie:		3.0.3
Prefix database	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
</details>

![image6](https://cloud.githubusercontent.com/assets/27774884/25185916/de606188-251e-11e7-847a-7c41d9b8621e.jpg)

**Comment by mikejolley** [comment]
This is a plugin conflict with something including select2 v3. View the page source and look for 'select2'. The path of that file should reveal what plugin is including it.
