### ISSUE TITLE
WC_Order::get_user_id() should be WC_Abstract_Order::get_user_id()

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#14543]
### EXPLANATION OF THE ISSUE

In WooCommerce 2.5 / 2.6, `$order->get_user_id()` was a valid method for any order object, as this was part of the abstract order class. However, in WC 3.0, this method was moved to `WC_Order`. This causes issues when the order object being dealt with is a refund instance, as that method doesn't exists.

Considering a refund still has a user ID associated with, it seems this method should be moved back to the abstract class.

See https://github.com/woocommerce/woocommerce-memberships/issues/80

**Comment by mikejolley** [comment]
@bekarice I think you need some code to ensure you're dealing with an order object, not a refund object regardless here.

2.6 no customer user is set for refunds: https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/wc-order-functions.php#L807

We can add a method for BW compatibility, but refunds don't have customer ids in the schema. They are just linked to an order. So this will return 0.
