### ISSUE TITLE
Error on Product Page: Notice ID was called incorrectly

### ISSUE THREAD

**Issue by BestOnlineSubscriptions** [woocommerce/woocommerce#14542]
### EXPLANATION OF THE ISSUE

Error message shows on the product page underneath the product short description.  This appeared after WooCommerce was updated to the new version 3.0.3.

WooCommerce updated and the below message started appearing under the product short description. 
 There should be no notice on the product.  This is the message that shows on every product page:

Notice: id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce/templates/single-product.php'), wc_get_template_part, load_template, require('/plugins/woocommerce/templates/content-single-product.php'), do_action('woocommerce_single_product_summary'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, woocommerce_template_single_add_to_cart, do_action('woocommerce_external_add_to_cart'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, ImprovedExternalProducts->iepp_external_add_to_cart, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in /home/beston19/public_html/wp-includes/functions.php on line 4137

Inmotion Support Team said to contact WooCommerce: 

This is Allen with Support. I will be helping you with your issue with WooCommerce. 

We looked at the error logs and the main issue there is that there were none. This means when WooCommerce communicates with the server, this not where the issue lies. 
From the error it looks like certain templates still need to be updated. I understand that you have already have done this update but it might not have completed. At this time you will want to contact WooCommerce about resolution. It is an issue with the application itself so they will be the ones that can help you resolve this issue. I am terribly sorry that there is nothing we can do at this time, but if WooCommerce needs some type of a update on the server please let us know. We will do our best to help.

The best way going forward is to take that exact error you presented to us and submit this in a ticket with the error you gave us. 

 

### STEPS TO REPRODUCE THE ISSUE

Notice is showing on all product pages and any new products added.  View product, see error message.

### SYSTEM STATUS

<details `
### WordPress Environment ###

Home URL: http://bestonlinesubscriptions.com
Site URL: http://bestonlinesubscriptions.com
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_vgvc_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (25) ###

Woocommerce CSV import downloadable, external, grouped products: by Allaerd Mensonides – 3.0.1
AddToAny Share Buttons: by AddToAny – 1.7.8
Akismet Anti-Spam: by Automattic – 3.3
Autoptimize: by Frank Goossens (futtta) – 2.1.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Display Posts Shortcode: by Bill Erickson – 2.8.0
EWWW Image Optimizer: by Shane Bishop – 3.2.7
Jetpack by WordPress.com: by Automattic – 4.8.2
MOJO Marketplace: by Mike Hansen – 1.1.2
Popup by Supsystic: by supsystic.com – 1.9.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Search & Filter: by Designs & Code – 1.2.9
External Links: by Denis de Bernardy & Mike Koepke – 6.8
Widget Logic: by wpchefgadget
alanft – 5.7.2

WooCommerce Cloak Affiliate Links: by datafeedr.com – 1.0.8
Woocommerce CSV Import: by Allaerd Mensonides – 3.3.5
WooCommerce Improved External Products: by Jeremiah Prummer – 1.4.1
WooCommerce: by Automattic – 3.0.3
Wordfence Security: by Wordfence – 6.3.6
Yoast SEO: by Team Yoast – 4.6
WP Database Backup: by Prashant Walke – 4.3.7
WP Migrate DB: by Delicious Brains – 0.9.2
MailPoet Newsletters: by MailPoet – 2.7.9
YITH WooCommerce Wishlist: by YITHEMES – 2.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #42 - /
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: #45 - /my-account/

### Theme ###

Name: Customizr
Version: 3.5.11
Author URL: http://presscustomizr.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by bekarice** [comment]
@BestOnlineSubscriptions based on that stack trace, it looks like the issue is likely this: 
```
WooCommerce Improved External Products: by Jeremiah Prummer – 1.4.1
```

As I see this: 

```
 ImprovedExternalProducts->iepp_external_add_to_cart, 
```

then the `doing_it_wrong` immediately after, indicating this method / plugin is the issue. This is not an issue with WC core -- please contact that author, as likely the plugin needs to be updated to support WC 3.0+

**Comment by claudiulodro** [comment]
Also worth noting that even though you get a deprecation notice, everything should still be working correctly (for now at least). That notice is intended for developers working in local development environments.

From your system status:
```
Hide errors from visitors: ❌Error messages should not be shown to visitors.
```

You should set `WP_DEBUG` to false in your live site. [Here's how](https://codex.wordpress.org/Debugging_in_WordPress).

**Comment by albert-pws** [comment]
Permission to post it here, since my issue also notices id was called incorrectly. Allow me to post it here. 

Here's the notice that I encountered: 
PHP Notice:  id was called <strong>incorrectly</strong>. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/Avada/templates/order-now.php'), get_header, locate_template, load_template, require_once('/themes/Avada/header.php'), WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.0.) in /Users/philwebsrvicesinc/Documents/Chris/development/site/gwplabs.com/wp-includes/functions.php on line 4139

FYI, I am using:
1. Woocommerce 3.2.1 
2. WP 4.8.2.
3. PHP version 5.6

I would really appreciate your help. Thanks

**Comment by willgorham** [comment]
@albert-pws 

You most likely need to update your theme (Avada) or child theme. If this error still occurs after that, opening a new issue and adding your system status (go to WooCommerce > Status and copy-paste) would be helpful to debug.

**Comment by albert-pws** [comment]
Here's the system status:

**Comment by willgorham** [comment]
@albert-pws This line: `require_once('/themes/Avada/header.php')` indicates the problem is in the Avada header template. I'd recommend contacting theme support as this isn't a WooCommerce core issue.
