### ISSUE TITLE
fstat() expects parameter 1 to be resource, boolean given

### ISSUE THREAD

**Issue by NTShop** [woocommerce/woocommerce#14544]
FYI: This is seen from the PayPal settings page when first enabling the payment gateway and saving setting for the first time, the enable logging was checked. 

`fstat() expects parameter 1 to be resource, boolean given in /var/www/wc30/wp-content/plugins/woocommerce/includes/log-handlers/class-wc-log-handler-file.php on line 270`

**Comment by claudiulodro** [comment]
@sirreal Any ideas? It looks like one of the log handles has `false` for its info. Maybe if WooCommerce fails to create the log file? I can't reproduce this on my local environment and don't see much that would do it in the code.

**Comment by sirreal** [comment]
Looks like @claudiosanches has got it 😄
