### ISSUE TITLE
Update notice when updating

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#14554]
![](http://cld.wthms.co/IdAe+)
**Image Link**: http://cld.wthms.co/IdAe+

Can we remove the red box when we click on the Update link? There's no useful reason to have it there and it's just a duplicate of the one from WP.

**Comment by mikejolley** [comment]
If it can be done with CSS only. It's not really a major issue nor one which will actually affect anyone. Low priority.

**Comment by faisal-alvi** [comment]
Hi @mikejolley and @SiR-DanieL 

Please have a look at #14672 

I have spent more than an hour on this. I hope it would help.

Thanks

**Comment by faisal-alvi** [comment]
@mikejolley i dont know why "fix-13847 for SCSS" is being displayed in #14672 ?

**Comment by mikejolley** [comment]
@faisal-alvi your branch was not in sync with master.

**Comment by faisal-alvi** [comment]
can you please instruct, how to sync from web?

**Comment by mikejolley** [comment]
Well I think your branch is in front. Maybe just fork again and apply your changes on a fresh branch?

**Comment by faisal-alvi** [comment]
Thank you so much @mikejolley

**Comment by faisal-alvi** [comment]
Hi @mikejolley I have successfully synced my branch with master.

Please have a look at #14718 

I hope this would fix the issue.

Thanks
