### ISSUE TITLE
Custom Post Type as Product?

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#14558]
Hi,

As WC_Order class is always called when place order action is called and used for transfering items from cart to checkout ( https://www.screencast.com/t/WBCwNVK4X ), we coulnd't find way for overriding products with custom one that we have created. In abstract-wc-order.php file, funcion get_items_key, in case of product always calls default WC_Order_Item_Product ( https://www.screencast.com/t/g81Bbt3DqM ). When further process gets deeper into product and checks if that is really product based on it's ID, false is returned as custom post type that has separate product class is result. Is it possible that get_items_key function gets filter where custom product class can be returned?

Nenad

**Comment by mikejolley** [comment]
Not possible right now but follow or contribute to https://github.com/woocommerce/woocommerce/issues/14302
