### ISSUE TITLE
Rest API Sales Reports - Refunds

### ISSUE THREAD

**Issue by chris-haigh** [woocommerce/woocommerce#14569]
When using the API to get a report, you get a value for total refunds for the entire period, but when you go down into the individual dates (months in my case), you only get the total sales including tax and refunds, but no separate record for refunds, meaning I have no idea what value of refunds took place that month.

This makes it extremely difficult for plotting the sales for each month.

Is this something that can be added?

**Comment by mikejolley** [comment]
@chris-haigh Could be added. Want to submit a PR?

**Comment by chris-haigh** [comment]
@mikejolley You'll have to forgive my naivety, I'm not overly familiar with the whole process and fairly new to git. What's the process?

**Comment by mikejolley** [comment]
Ah, take a look here https://help.github.com/articles/creating-a-pull-request/ There is a github app to make it easier.

**Comment by claudiosanches** [comment]
@mikejolley better leave it for a future release after we have a better reports API.
Since today is really bad querying like we are doing.

**Comment by mikejolley** [comment]
Thats true. But it will always be like this until we do custom tables or some kind of cache.

**Comment by chris-haigh** [comment]
Thanks for the info. Just working through it now. I've forked woocommerce and i'm attempting to get the figure to pull through on the API, however I cannot seem to get the refund figure to be deducted.

I've added a line into the period_totals section in the API called "sales_net" which pulls through fine, however when I use $order->total_refunds to get the refund value and subtract it, nothing happens.

I'm currently running on the v3 woocommerce rest API.

The line I have is:

`$period_totals[ $time ]['sales_net']    = wc_format_decimal( ($order->total_sales - $order->total_refunds), 2 );`

Any thoughts?

**Comment by mikejolley** [comment]
Don't you need to specifically query refunds in that $time?

**Comment by chris-haigh** [comment]
Not for the purposes of what i'm trying to achieve. I've got it feeding a Klipfolio dashboard and I want to show comparative stats of this years sales vs last years sales.

Additionally, refunds are a bit skewed anyway, since they show up for the month when the refund was processed, rather than against the month that the order was originally placed, which makes it difficult to compare one month to the next if you've got a refund from 2 months ago showing up.

**Comment by mikejolley** [comment]
What you describe isn't actually how we want to present refunds in core. Refunds should be shown in the date range they were granted.

Think of it another way. If you had an order at the end of the tax year, then refunded in the new tax year, when would you account for the refund in your taxes? It would be in the new tax year. I believe thats why they do not show in previous periods when the order was initially made.

I'd suggest adding a custom API endpoint or custom reporting to tailor this to your needs.
