### ISSUE TITLE
FlexSlider: SmoothHeight not working

### ISSUE THREAD

**Issue by Ninos** [woocommerce/woocommerce#14568]
### EXPLANATION OF THE ISSUE
Hey there, after enabling smoothHeight for the products flexslider, it's not working as excepted. The height is fixed on the max-height of all images.

### STEPS TO REPRODUCE THE ISSUE

```
add_filter( 'woocommerce_single_product_carousel_options', 'single_product_carousel_options' );
/**
 * Change carousel options on single product page
 * @param array
 * @return array
 */
function single_product_carousel_options( $options ) {
	$options['smoothHeight'] = true;

	return $options;
}
```
Also upload two images with different heights and set the thumbnail size to `full` or `600x0` (in my example `600x0` is working because I'm using a self-coded live thumbnail generator, but with `full` you get same results):
`$html .= wp_get_attachment_image( $attachment_id, 'full', false, $attributes );`
Additionally use following CSS:
```
.woocommerce-product-gallery__image > a > img {
  width: 100%;
  height: auto;
}
```

Now you can see the space between the carousel thumbnails and the images with the smaller height.

BTW: On mobile there's also a strange space between carousel thumbnails and the image. May because of the zoom image, but it's the same problem with `smoothHeight`.

### SYSTEM STATUS
WC 3.0.3

**Comment by mikejolley** [comment]
It won't work because of min height code. See https://github.com/woocommerce/woocommerce/pull/14462

**Comment by Ninos** [comment]
Oh that's right. Setting `.woocommerce-product-gallery__image { min-height: auto !important; }` solved the problem.

**Comment by martinsnajdr** [comment]
This bug seems to be a problem again (if the smoothHeight will be enabled in next release).
https://github.com/woocommerce/woocommerce/issues/12868

I have tried your #14462 fix and now the flex-viewport has height: 0, when the image is not cached (first load).

**Comment by mikejolley** [comment]
@martinsnajdr I'm not able to replicate it any more.
