### ISSUE TITLE
Variation counting is not correct.

### ISSUE THREAD

**Issue by emgk** [woocommerce/woocommerce#14565]
### EXPLANATION OF THE ISSUE

When I create variations through "Create variations from all attributes" option. after variation added, in window alert it saying that "1 variation added" that is correct, but above the product variation lists in "Product Data" meta box it showing "2 variations" which is not correct. 

The problem is that `update_variations_count` method is calling two times, first is inside the `update_single_quantity` method when variations are added and the second time inside `set_paginav` which is calling inside the 'reload' method. 

in alert:
<img src="https://image.ibb.co/btkRJ5/alert.png"/> 

above variation lists
<img src="https://image.ibb.co/i7P8WQ/2variations.png"/>

### STEPS TO REPRODUCE THE ISSUE

1. Edit any variable product.
2. Delete all variation first, reload the page and add variations again using "Create variations from all attributes".
3. Now see variations counts.

**Comment by mikejolley** [comment]
Not able to replicate this one with the steps listed. Count is correct after add. Suspect you may have a trashed variation being counted..
