### ISSUE TITLE
img title tag removed from main image on single product pages?

### ISSUE THREAD

**Issue by pcaWeb** [woocommerce/woocommerce#14578]
### EXPLANATION OF THE ISSUE

Has the img title tag been removed from the main product image on a single product page?

### STEPS TO REPRODUCE THE ISSUE

Examine html for the main product image on any single product page. The img tag does not contain a title tag.

**Comment by mikejolley** [comment]
It will use the 'Caption' field so the scripts display this in the lightbox.

**Comment by mikejolley** [comment]
Thats if I'm talking about the same tag. Add a caption to your image so you can see what it adds.

**Comment by pcaWeb** [comment]
Dont think we're talking about the same thing. I run an SEO audit from Raventools every month. Having just updated to WooCommerce 3.03 I now have 2.5k issues raised by this months report as compared to last month.

I believe this is because for main product image on a single product page (not in the lightbox), the title tag is now not being returned as part of the <img> tag whereas prior to updating it was.

The <img> title tag is still considered important for on page SEO so rather than adding captions to every image (which we really don't need), I'd rather just display the title tag which we already have populated and optimised.

**Comment by mikejolley** [comment]
Sure but if we are talking about the same thing, you should know that the title tag will show up in the lightbox. 

![2017-04-20 at 19 40](https://cloud.githubusercontent.com/assets/90977/25246946/3194d540-2601-11e7-800b-a5c702ac3872.png)

Is this the markup you're talking about?

**Comment by pcaWeb** [comment]
![fine_ripple_textured_4mm_titanium_ring_-_ti2_titanium](https://cloud.githubusercontent.com/assets/1008413/25249569/39ac8f58-260a-11e7-8261-158ef5f89150.jpg)

This is the markup from this page: https://ti2titanium.com/product/fine-ripple-textured-4mm-ring/

In the above example, in the media library, the title field for the image is populated but the caption field is not. Prior to 3.x the title tag was output, now it isn't.

I understand that adding a caption to the image will generate the title tag in ver 3.x, but:

- this isn't intuitive
- on sites with many products, populating an otherwise blank caption field is significant work
- in the meantime, the absence of a title tag may impact on-page SEO across the site
- where a product (or other) image is used in multiple locations on a site, an image caption is not always desirable/required and so adding one will cause unintended behaviour
