### ISSUE TITLE
Inventory on Variable Products Doesn't Work With Paypal, Works When Amount is $0

### ISSUE THREAD

**Issue by dwedeking** [woocommerce/woocommerce#14572]
When purchased through Paypal Variable Products don't count down inventory. I used a coupon to reduce the order total to $0 (so didn't go through Paypal) and the inventory was controlled correctly. 

General Settings --> Products --> Inventory "Enable stock management" is checked. 
Product --> Product --> Inventory "Enable stock management at product level" is unchecked
Variation --> Manage Stock box is checked. 

### SYSTEM STATUS

<details>
WordPress environment
Home URL: 		http://sunrisesurfshop.com
Site URL: 		http://sunrisesurfshop.com
WC version: 		3.0.3
Log directory writable: 		/home/sunri24/public_html/wp-content/uploads/wc-logs/
WP version: 		4.7.3
WP multisite: 		–
WP memory limit: 		256 MB
WP debug mode: 		
WP cron: 		
Language: 		en_US
Server environment
Server info: 		Apache
PHP version: 		5.6.30
PHP post max size: 		8 MB
PHP time limit: 		30
PHP max input vars: 		1000
cURL version: 		7.29.0, NSS/3.21.3 Basic ECC
SUHOSIN installed: 		–
MySQL version: 		5.6.35	
Max upload size: 		2 MB
Default timezone is UTC: 		
fsockopen/cURL: 		
SoapClient: 		
DOMDocument: 		
GZip: 		
Multibyte string: 		
Remote post: 		
Remote get: 		
Database
WC database version: 		3.0.3
Database prefix 	  	wp_	
woocommerce_sessions 	  	
woocommerce_api_keys 	  	
woocommerce_attribute_taxonomies 	  	
woocommerce_downloadable_product_permissions 	  	
woocommerce_order_items 	  	
woocommerce_order_itemmeta 	  	
woocommerce_tax_rates 	  	
woocommerce_tax_rate_locations 	  	
woocommerce_shipping_zones 	  	
woocommerce_shipping_zone_locations 	  	
woocommerce_shipping_zone_methods 	  	
woocommerce_payment_tokens 	  	
woocommerce_payment_tokenmeta 	  	
MaxMind GeoIP database: 		/home/sunri24/public_html/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS): 		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors 		Error messages should not be shown to visitors.
Active plugins (20)
Advanced Custom Fields 	  	by Elliot Condon – 4.4.11
Antispam Bee 	  	by pluginkollektiv – 2.7.1
Automatic Featured Images from YouTube / Vimeo 	  	by WebDevStudios – 1.0.3
Contact Form 7 	  	by Takayuki Miyoshi – 4.7
Easy Social Share Buttons for WordPress 4.1 	  	by CreoApps – 4.1
Elfsight InstaShow 	  	by Elfsight – 2.3.2
Get Custom Field Values 	  	by Scott Reilly – 3.7
Google Analytics Dashboard for WP 	  	by Alin Marcu – 4.9.6.2
Nextend Facebook Connect 	  	by Nextendweb – 2.0.2
Nextend Google Connect 	  	by Roland Soos, Jamie Bainbridge – 1.6.1
No Category Base (WPML) 	  	by Marios Alexandrou – 1.3
Regenerate Thumbnails 	  	by Alex Mills (Viper007Bond) – 2.2.6
Simple Custom CSS 	  	by John Regan, Danny Van Kooten – 3.3
Vimeography 	  	by Dave Kiss – 1.5
WooCommerce 	  	by Automattic – 3.0.3
WooSidebars 	  	by WooThemes – 1.4.3
Yoast SEO 	  	by Team Yoast – 4.6
WP Smush 	  	by WPMU DEV – 2.6.3
WPForms Lite 	  	by WPForms – 1.3.6.2
YITH WooCommerce Wishlist 	  	by YITHEMES – 2.1.0
Settings
API enabled: 		
Force SSL: 		–
Currency 		USD ($)
Currency position 		left
Thousand separator 		,
Decimal separator 		.
Number of decimals 		2
Taxonomies: Product types 		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility 		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		Page ID is set, but the page does not exist
Cart:		#919 - /shop/cart/
Checkout:		#921 - /checkout/
My account:		#77 - /my-account/
Theme
Name: 		Flatsome Child
Version: 		3.0
Author URL: 		
Child theme: 		
Parent theme name: 		Flatsome
Parent theme version: 		3.3.4
Parent theme author URL: 		http://www.uxthemes.com/
WooCommerce support: 		
Templates
Overrides 	  	flatsome/woocommerce/archive-product.php,
flatsome/woocommerce/cart/cart-empty.php,
flatsome/woocommerce/cart/cart.php,
flatsome/woocommerce/checkout/form-checkout.php,
flatsome/woocommerce/checkout/form-coupon.php,
flatsome/woocommerce/checkout/thankyou.php,
flatsome/woocommerce/content-product.php,
flatsome/woocommerce/content-product_cat.php,
flatsome/woocommerce/content-single-product.php,
flatsome/woocommerce/global/breadcrumb.php,
flatsome/woocommerce/global/quantity-input.php,
flatsome/woocommerce/global/wrapper-end.php,
flatsome/woocommerce/global/wrapper-start.php,
flatsome/woocommerce/loop/loop-end.php,
flatsome/woocommerce/loop/loop-start.php,
flatsome/woocommerce/loop/orderby.php,
flatsome/woocommerce/loop/pagination.php,
flatsome/woocommerce/loop/result-count.php,
flatsome/woocommerce/loop/sale-flash.php,
flatsome/woocommerce/myaccount/form-login.php,
flatsome/woocommerce/myaccount/navigation.php,
flatsome/woocommerce/notices/error.php,
flatsome/woocommerce/notices/notice.php,
flatsome/woocommerce/notices/success.php,
flatsome/woocommerce/product-searchform.php,
flatsome/woocommerce/single-product/photoswipe.php,
flatsome/woocommerce/single-product/price.php,
flatsome/woocommerce/single-product/product-image.php,
flatsome/woocommerce/single-product/product-thumbnails.php,
flatsome/woocommerce/single-product/related.php,
flatsome/woocommerce/single-product/review.php,
flatsome/woocommerce/single-product/sale-flash.php,
flatsome/woocommerce/single-product/share.php,
flatsome/woocommerce/single-product/short-description.php,
flatsome/woocommerce/single-product/tabs/tabs.php,
flatsome/woocommerce/single-product/title.php,
flatsome/woocommerce/single-product/up-sells.php,
flatsome/woocommerce/single-product-reviews.php,
flatsome/woocommerce/single-product.php
</details>

**Comment by mikejolley** [comment]
Depends what status the order gets after paying with paypal?

**Comment by UserName011** [comment]
@mikejolley  it should be status wc-processing   (post_status in wp_posts table)

**Comment by dwedeking** [comment]
Both orders show in WooCommerce as "Processing". The top order was via Payapl and did not process inventory. The bottom order was couponed out to $0 (so not paypaled) and inventory was correct. 
![2017-04-20_11-14-21](https://cloud.githubusercontent.com/assets/27818879/25238250/e8ef172e-25ba-11e7-8843-16c999b74219.jpg)

**Comment by mikejolley** [comment]
If you edit the order, is there a transaction ID for the paypal one? And what order notes are there?

**Comment by mikejolley** [comment]
I've confirmed the `$order->payment_complete();` method and callbacks work fine. I added the code to BACS and tested that.

I'll get my sandbox working and try PDT from PayPal as I cannot use IPN locally. I don't see a problem in the code however.

**Comment by dwedeking** [comment]
No that field is blank. Here's the order screen. 
![paypal-order](https://cloud.githubusercontent.com/assets/27818879/25239388/da630820-25bd-11e7-892d-a435ccd4c2f7.jpg)

The Paypal set up screen
![paypal-setup](https://cloud.githubusercontent.com/assets/27818879/25239544/4b5b0050-25be-11e7-97ee-ab926ae74725.jpg)

**Comment by mikejolley** [comment]
Order notes? On the order edit page.

I want to see if it was manually set processing, since you are missing the transaction ID.

**Comment by mikejolley** [comment]
Confirmed no issue with PDT https://dl.dropboxusercontent.com/s/6ozaktud9jeueyc/2017-04-20%20at%2016.47.png

**Comment by mikejolley** [comment]
And repeated with 2 variable products; 1 with stock managed at variable level, and 1 with stock managed at variation level. All works.

**Comment by dwedeking** [comment]
![2017-04-20_11-48-50](https://cloud.githubusercontent.com/assets/27818879/25239929/84b64b92-25bf-11e7-93ba-1e6696407757.jpg)

Would changing the Paypal setting from Capture to Authorize change the return from Paypal?

**Comment by mikejolley** [comment]
So I can see from that you changed the order status manually from pending to processing. Matthew Brooks edited the order.

See https://docs.woocommerce.com/document/paypal-standard/ for trouble shooting steps on IPN, or enable PDT as a fallback.

This is not related to 3.0 and not a bug.

**Comment by UserName011** [comment]
@dwedeking  Pending is when the customer placed an order and Woo Commerce is waiting for paypal to send IPN confirmation for the payment. If payment isn't received the order will be changed to status canceled. If payment is received the order will change to processing. When Woocomerce handle the IPN it also reduce the stock. Since you did it manually the stock was not removed. 

Also, Why did you do it manually? Are you sure you got the payment?
