### ISSUE TITLE
List of "guest" orders using wc_get_orders

### ISSUE THREAD

**Issue by gonzalesc** [woocommerce/woocommerce#14575]
In Woocommerce 3.0.3.
In postmeta table, the key "**_customer_user**" in 0 are the guest orders, then if I want to list it, my code will be:

`<?php $guest_orders = wc_get_orders(	array( 'type' => array( 'shop_order' ), 'customer' => 0 ) ); ?>`

However, this always brings me "all" orders and not guest orders.

This function calls "get_orders ()" in includes/data-stores/class-wc-order-data-store-cpt.php

[Line 386:](https://github.com/woocommerce/woocommerce/blob/31cd2dcb904868658dcb4febd70e1081c3564a51/includes/data-stores/class-wc-order-data-store-cpt.php#L386)
```
if ( ! empty( $args['customer'] ) ) {
        $values = is_array( $args['customer'] ) ? $args['customer'] : array( $args['customer'] );
        $wp_query_args['meta_query'][] = $this->get_orders_generate_customer_meta_query( $values );
}
```

Although I have put "customer" in 0, the condition does not catch it.

Here a posible bug. The function empty() always is "true" when the value is 0 or "0", in these cases should be used "isset()"

`if ( isset( $args['customer'] ) )`

## My temporal solution

```
add_filter('woocommerce_order_data_store_cpt_get_orders_query','correct_guest_orders',10,3);
function correct_guest_orders($wp_query_args, $args, $order) {

	if( isset($args['customer']) && $args['customer']==0 ) {
		$wp_query_args['meta_query'][] = array('key' => '_customer_user',  'value' => 0, 'compare' => '=' );
	}
	return $wp_query_args;
}
```

Regards

**Comment by dragosstancu** [comment]
$query = "SELECT COUNT(*) FROM $wpdb->posts, $wpdb->postmeta WHERE $wpdb->posts.ID = $wpdb->postmeta.post_id AND $wpdb->postmeta.meta_key = '_customer_user' AND $wpdb->postmeta.meta_value = '0' AND $wpdb->posts.post_type ='shop_order'";
