### ISSUE TITLE
Woocommerce 3.0.4 NOT updating!

### ISSUE THREAD

**Issue by dreamesper** [woocommerce/woocommerce#14588]
Woocommerce, as a plugin, will NOT update to the latest 3.0.4 build through Wordpress. Any suggestions?

**Comment by mikejolley** [comment]
Upload manually using FTP. Upload the plugin files to wp-content/plugins and replace the existing version. 

https://codex.wordpress.org/Managing_Plugins#Manual_Plugin_Installation

WordPress manages plugin updates FYI, not woocommerce.
