### ISSUE TITLE
Refund should transact on NEW DATE of refund, not on original date of purchase

### ISSUE THREAD

**Issue by jennr** [woocommerce/woocommerce#14585]
### EXPLANATION OF THE ISSUE

I have tested in 2.6.14, 3.0.3, 3.0.4

When a refund is issued by invoice number, the refund should be processed for the day of refund not the date the sale was originally made. 

The way WooCommerce processes refunds now modifies the sale and taxes, which have already been submitted to the government.

### STEPS TO REPRODUCE THE ISSUE

1. Create order.

2. Wait some period of days

3. Refund order

4. Note that there is no mention of a refund transaction on the date of refund in reports, but the transaction is modified to reflect that a refund was made on the date of sale rather than the date of refund.

### SYSTEM STATUS

<details>

`
### WordPress Environment ###

Home URL: https://stage.nslsxx.com
Site URL: https://stage.nslsxx.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_CA

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: nslwpwc_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Duplicator: by Snap Creek – 1.2.4
Redirection: by John Godley – 2.5
Page Builder by SiteOrigin: by SiteOrigin – 2.5.2
SiteOrigin Widgets Bundle: by SiteOrigin – 1.8.2
WooCommerce Colours: by WooThemes – 1.0.6
WooCommerce Customizer: by SkyVerge – 2.4.0
WooCommerce Point of Sale: by Actuality Extensions – 4.0.4
WooCommerce - Table Rates: by WP Ronin – 1.6.0
WooCommerce: by Automattic – 3.0.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3786 - /shop/
Cart: #18 - /cart/
Checkout: #19 - /checkout/
My account: #20 - /my-account/

### Theme ###

Name: Twenty Fourteen Child
Version: 1.0.0
Author URL: http://jennlog.com
Child Theme: ✔
Parent Theme Name: Twenty Fourteen
Parent Theme Version: 1.9
Parent Theme Author URL: https://en-ca.wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: twentyfourteen-child/woocommerce/loop/price.php
`

</details>

**Comment by rafaelcmrj** [comment]
is there any way to re-enable the calculation to be in the order DATE instead of the refund date?

**Comment by rafaelcmrj** [comment]
anyone? @jennr ? is this possible? use the order data instead of the refund date

**Comment by rafaelcmrj** [comment]
@jennr I understand it, but for reports it's terrible. Suppose you sold 120k in products last month and 80k this month, but you had to refund 80k this month from last month's orders. The report will show you 120k in sales last month and 0 this month. I understand why/how it works, but in terms of sales analysis, it's a wrong/confuse information.

**Comment by jennr** [comment]
@rafaelcmrj Yes, but from a cashflow perspective, you are at a net 0 at that point for the month and it'd be pretty important to know.  I imagine there could be an additional sales report made to itemize classes of credits and debits using the data inside the database?

**Comment by jennr** [comment]
Also, depending on the type of product/service (if a product), you are then having to deal with potentially re-entering the product back in to inventory or processing returns back to suppliers, which would all flow from the subsequent refund transaction rather than the original purchase.
