### ISSUE TITLE
Checkout address changes ignored logged in user

### ISSUE THREAD

**Issue by ellisar** [woocommerce/woocommerce#14583]
### EXPLANATION OF THE ISSUE

On WooCommerce Versions 3.0 - 3.0.4 during the checkout process when a user is logged in, the system does not process address changes. It instead still uses the default address.

### STEPS TO REPRODUCE THE ISSUE

The steps and issue can be found clearly documented in the following Loom video: https://www.useloom.com/share/80a222da9e5c46eea3e151c7d36da616

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
@claudiulodro can you investigate this one please?

**Comment by mikejolley** [comment]
I can see whats going on here. That checkout has been customised somewhat.

Notice you have a checkbox "my shipping address is the same as my billing address"?

Core actually hides this by default and has "ship to a different address": https://dl.dropboxusercontent.com/s/g8uqz1taytc9bh3/2017-04-25%20at%2014.49.png

If that box is not checked, the form is ignored. Looks like that customisation needs to be updated for 3.0 compatibility.

**Comment by mschipperheyn** [comment]
So, what is the status on this? I'm running into this issue

**Comment by claudiulodro** [comment]
@mschipperheyn this was a problem in the custom theme the original poster was using and not in WooCommerce core. See @mikejolley's comment above.
