### ISSUE TITLE
No system status. Blank Page ! 

### ISSUE THREAD

**Issue by Gabemedia** [woocommerce/woocommerce#14582]
Can´t provide any information, the page is blank!!!

**Comment by gmondragon** [comment]
Hi. Did you upgrade to the latest version? The same thing happens to me after updating. When I activate DEBUG I get the following error:

Class 'WC_Payment_Gateway_CC' not found in <PLUGIN>

Regards.

**Comment by Gabemedia** [comment]
Yes I just updated to 3.0.4. 
My debug is showing nothing, just a blank system status page. 

Regards.

**Comment by gmondragon** [comment]
I just solved the problem by doing the following:

1: Activate the DEBUG mode in the wp-config.php to know which plugin is causing problems.
2: Log in via FTP / SFTP and rename the plugins to disable them.
3: Log in to wp-admin and enable Woocomemrce.
4: Log in via FTP / SFTP and rename the plugins to their original name

Apparently the problem arises because Woocommerce is disabled after the upgrade.

**Comment by mikejolley** [comment]
Gateways should check WC exists before loading. Report to the Dev.

**Comment by mikejolley** [comment]
Gabemedia enable WP_DEBUG mode and see what is on the page. It sounds like a timeout.

**Comment by mikejolley** [comment]
Any update @Gabemedia ? Will be closing this if it does not get more info.

**Comment by Gabemedia** [comment]
Hi Mike.

Sorry for the wait. :-/

I did not have the time to look into this. Debug does not help.

But I still need to test the renaming of plugins, but the site is under heavy traffic...
So i have to wait until night to test it.

I will try to reply the solution or bug in about 24 hours. 👍

**Comment by claudiosanches** [comment]
@Gabemedia should have a PHP fatal error, since is showing only a blank page, so debug should help. Or at least checking the server error log.

**Comment by mikejolley** [comment]
What did you find if anything?

**Comment by mikejolley** [comment]
Going to close this. If not resolved, please email me (link on profile) so I can get access.

**Comment by Gabemedia** [comment]
Hi and thanks for the help and many comments.

No plugins did the blank page, also debug showed nothing.
Nothing did work, but the last woocommerce update did put everything back in place. :)

Thanks! 

Best regards.
Daniel G. Svendsen
