### ISSUE TITLE
Rogue :before element appearing on orders pages on mobile

### ISSUE THREAD

**Issue by jaygidwitz** [woocommerce/woocommerce#14581]
### EXPLANATION OF THE ISSUE

Rogue `:before` element appearing on orders pages on mobile. Appeared after the WooC 3.0 update.

/woocommerce/my-account/orders/

Appearing on multiple themes, including Twentyseventeen.

<img width="555" alt="screen shot 2017-04-05 at 3 07 40 pm" src="https://cloud.githubusercontent.com/assets/3248407/24729318/79da3bba-1a12-11e7-82e8-a4ab71b4eb99.png">

<img width="441" alt="screen shot 2017-04-05 at 3 08 31 pm" src="https://cloud.githubusercontent.com/assets/3248407/24729322/7dac3b94-1a12-11e7-91ec-97786b11e877.png">

**Twenty Seventeen:**

<img width="400" alt="screenshot 2017-04-20 13 51 16" src="https://cloud.githubusercontent.com/assets/3248407/25252074/7a1b8e2a-25d0-11e7-8dc1-3f5d29517c6d.png">

### STEPS TO REPRODUCE THE ISSUE

1. Make purchases
1. View your account
1. View your orders
1. Shrink browser window to mobile size

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
`
### WordPress Environment ###

Home URL: https://test.studiopress.com/twentyseventeen
Site URL: http://test.studiopress.com/twentyseventeen
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.9
PHP Version: ❌ 5.5.9-1ubuntu4.21 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 12 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_221_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

WooCommerce: by Automattic – 3.0.4
Genesis eNews Extended: by Brandon Kraft – 2.0.2
Akismet Anti-Spam: by Automattic – 3.3
Gravity Forms: by rocketgenius – 2.2.1.2
Genesis Beta Tester: by Nathan Rice – 0.9.3
Soliloquy: by Soliloquy Team – 2.5.3.1
Simple Social Icons: by Nathan Rice – 2.0.1
SSL Insecure Content Fixer: by WebAware – 2.2.3
Quick Cache: by s2Member® / WebSharks
Inc. – 150129.3

Monster Widget: by Automattic – 0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1 – 1.2 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

</details>

**Comment by avinapatel** [comment]
@jaygidwitz, @mikejolley 

I have fixed :before element appearing on orders pages on the mobile issue and also I have set the "View" order text on the left side as it was in < 3.0 versions. 

Please see the PR #14617.

Thanks,

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14648
