### ISSUE TITLE
Variable subscriptions + one-time shipping not working

### ISSUE THREAD

**Issue by nikkimacfarlane** [woocommerce/woocommerce#14586]
### EXPLANATION OF THE ISSUE

Since the upgrade to WC3, variable subscriptions that have one-time shipping checked are actually applying the shipping amount in the cart as being monthly (aligned with the subscription length) and not one time as previously.

### STEPS TO REPRODUCE THE ISSUE

1. Edit a variable subscription product.
2. Click on shipping.
3. Choose a shipping option (I am using Table Shipping). Check one time shipping and save.
4. Add the item to the shopping cart.
5. Go to the cart - the shipping is shown as a monthly amount, not a one time amount. This was working fine before the recent WC upgrade.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://childbirthinternational.com
Site URL: http://childbirthinternational.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔  2 active Zapier Feeds.
Zapier Integration - Cron Tasks: ✔  0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔  Create new invoices in Zoho Books from new WooCommerce orders
Zapier Feed #1 Webhook URL: ✔  https://hooks.zapier.com/hooks/catch/1929584/h4h9rn/
Zapier Feed #1 Trigger: ✔  New Order
Zapier Feed #1 Test Result: ✔  Successfully sent sample data to https://hooks.zapier.com/hooks/catch/1929584/h4h9rn/.
Zapier Feed #2 Name: ✔  Subscription Payment
Zapier Feed #2 Webhook URL: ✔  https://hooks.zapier.com/hooks/catch/1929584/h4h8m9/
Zapier Feed #2 Trigger: ✔  Subscription Renewed
Zapier Feed #2 Test Result: ✔  Successfully sent sample data to https://hooks.zapier.com/hooks/catch/1929584/h4h8m9/.

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (37) ###

Add Categories to Pages.: by a.ankit – 1.0
Comet Cache: by WebSharks
Inc. – 170220

Contact Form 7: by Takayuki Miyoshi – 4.7
Crazy Egg: by Crazy Egg – 2.0
Duplicate Post: by Enrico Battocchi – 3.2
Envato WordPress Toolkit: by Envato – 1.7.3
Facebook Button by BestWebSoft: by BestWebSoft – 2.54
Facebook Conversion Pixel: by Kellen Mace – 1.3.5
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.7
IgniteWoo Updater: by Ignition – 2.1.7
Insert PHP Code Snippet: by xyzscripts.com – 1.2.1
Salient Visual Composer: by Michael M - WPBakery.com | Modified by ThemeNectar – 4.11.2
List category posts: by Fernando Briano – 0.72
Members: by Justin Tadlock – 1.1.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Restrict Usernames: by Scott Reilly – 3.6
SMTP Mailer: by naa986 – 1.0.3
Abandoned Cart Pro for WooCommerce: by Tyche Softwares – 4.8.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.4
WooCommerce Conditional Content: by Lucas Stark – 2.0.0
Woocommerce Enforce Strong Password: by Bernard Peh – 1.2.2
WooCommerce Stripe Gateway: by WooCommerce – 3.1.7
WooCommerce WorldPay Gateway: by Add On Enterprises (Andrew Benbow) – 3.6.0
WooCommerce Min/Max Quantities: by WooCommerce – 2.3.16
WooCommerce Name Your Price: by Kathy Darling – 2.5.2 – 2.5.3 is available
WooCommerce Product Add-ons: by WooCommerce – 2.8.1
WooCommerce Restrict Categories Plus: by Ignitewoo.com – 3.5.11
WooCommerce Subscriptions: by Prospress Inc. – 2.2.4
WooCommerce Tab Manager: by SkyVerge – 1.8.0
WooCommerce Table Rate Shipping: by Automattic – 3.0.2
WooCommerce Zapier Integration: by OM4 – 1.6.7
WooCommerce: by Automattic – 3.0.4
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO Premium: by Team Yoast – 3.6
YITH WooCommerce Added to Cart Popup Premium: by YITHEMES – 1.0.7
YITH WooCommerce Dynamic Pricing and Discounts Premium: by YITHEMES – 1.2.3
YITH WooCommerce Gift Cards Premium: by YITHEMES – 1.4.11

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #77 - /shop/
Cart: #78 - /cart/
Checkout: #79 - /checkout/
My account: #80 - /my-account/

### Theme ###

Name: Salient child theme
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Salient
Parent Theme Version: 7.0.8
Parent Theme Author URL: http://themenectar.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: salient-child/woocommerce/cart/cart-empty.php
salient-child/woocommerce/cart/cart-shipping.php
salient-child/woocommerce/cart/cart-totals.php
salient-child/woocommerce/cart/cart.php
salient-child/woocommerce/cart/shipping-calculator.php
salient-child/woocommerce/checkout/form-checkout.php
salient-child/woocommerce/checkout/form-shipping.php
salient-child/woocommerce/checkout/review-order.php
salient-child/woocommerce/checkout/thankyou.php
salient-child/woocommerce/content-product.php
salient-child/woocommerce/content-single-product.php
salient-child/woocommerce/loop/add-to-cart.php
salient-child/woocommerce/single-product/product-image.php
salient-child/woocommerce/single-product/tabs/description.php
salient-child/woocommerce/single-product/tabs/tabs.php

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
</details>

**Comment by HammerofPompey** [comment]
Flat rate shipping is not working with WC3.0.3 variable products either if the shipping class is set to same as the parent.  If the variation is set to the correct class then it works, but when you have  M/F, 8 sizes and 10 colours and 20 products it is not viable to do manually.

There is a workaround https://github.com/woocommerce/woocommerce/pull/14387/files but let's hope this is fixed with some urgency as editing 20 stores is also a pain!

**Comment by HammerofPompey** [comment]
3.0.4 fixed my issue above...

**Comment by mikejolley** [comment]
Please use the helpdesk or subscription issues https://woocommerce.com/my-account/tickets/
