### ISSUE TITLE
wc_get_products should filter out empty/invalid results (false) before returning objects

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#14592]
https://wordpress.org/support/topic/major-issue-with-3-0-1-update/page/2/#post-9052293

**Comment by emgk** [comment]
@mikejolley please check my commit #14598

**Comment by mikejolley** [comment]
@emgk thats not what I said in the issue title. "wc_get_products should filter out empty/invalid results "

Handling should be inside `wc_get_products()`

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14685
