### ISSUE TITLE
Featured Product not working in version 3.0.4

### ISSUE THREAD

**Issue by khanhtranvn90** [woocommerce/woocommerce#14591]
` <?php`
` $meta_query[] = array(`
`  'key'   => '_featured',`
`  'value' => 'yes'`
`  );`
`  $args = array(`
`  'post_type'   =>  'product',`
`    'stock'       =>  1,`
`  'showposts'   =>  12,`
`   'orderby'     =>  'date',`
`   'order'       =>  'DESC',`
`   'meta_query'  =>  $meta_query`
` );`
`?>`
Currently, This query not working. I make a check in table wp_postmeta, "_featured" not update ( still has value 'no' ) when checked on Quick Edit Woocommerce Product. I am using Woocommerce version 3.0.4

**Comment by mikejolley** [comment]
See the release notes. It's a taxonomy called product_visibility in 3.0, not meta.
