### ISSUE TITLE
How to retrieve “care and info” and “cod info” of a product from woocommerce using woocommerce rest api

### ISSUE THREAD

**Issue by NishithGit** [woocommerce/woocommerce#14597]
I am creating products in my woocommerce inventory and retrieving them on my android app using woocommerce rest api. While creating the products, along with the product info I am passing "Product Short Description" , "Care and Info" and "Cod Info" properties of the product.

Now while fetching the product I am getting the "product short description" property but I am unable to get "Care and Info" and "Cod Info" properties of the product. Are these not supported in the rest api because I am not able to see them in the rest api doc ?

I am referring http://woocommerce.github.io/woocommerce-rest-api-docs/

**Comment by mikejolley** [comment]
Those fields are not part of core. Look at the 'meta data' property of each product - if it's set, it will be there.

**Comment by NishithGit** [comment]
Thanks Mike

**Comment by mikejolley** [comment]
meta data is in the v2 api.
