### ISSUE TITLE
Woocommerce - Add to Cart link issues

### ISSUE THREAD

**Issue by dreamesper** [woocommerce/woocommerce#14596]
Basically, every time that I test to see if the proper product is 'added to cart', a different product is selected as being added to cart.

www.dreamesper.com

In other words... once I 'empty cart' & re-attempt to add a certain product to SHOPPING CART, a previous product selected will re-appear... rendering the entire shopping experience confusing for my customers, etc.

Will this be updated in a future version of WooCommerce??

**Comment by dreamesper** [comment]
Can anyone provide an update?? Has anyone looked into this issue?

**Comment by mikejolley** [comment]
This is a **caching** issue. Your cart page is being cached by simple cache, so you're not seeing the current up to date cart.

https://docs.woocommerce.com/document/configuring-caching-plugins/
