### ISSUE TITLE
Downloadable Product File URL not being accepted in field

### ISSUE THREAD

**Issue by nlevasseur** [woocommerce/woocommerce#14600]
Hi There,

**The Issue**
I am using WP version: 4.7.3, WC version 3.0.4
I have downloadable products in the WooCommerce store. When I paste an encoded URL into the File URL field and click Update, the pre-populated example (http://) appears as a prefix to the encoded URL.
It should go away.

**I have disabled all other plugins, and the issue persists
I have created a staging area in WP, used the 2017 theme, and the issue persists**.

**How to Reproduce this Issue**
1. Add new product
2. Under Product Data, choose Simple product.
3. Check the boxes: Virtual and Downloadable
4. In the name box, type "Test download"
5. In the File URL, paste an encoded URL over the example (http://)
6. Note that the field example (http://) is gone.
6. Click update
7. Check to see if the example URL (http://) has come back as a prefix to the encoded URL. 
Here is my result after updating: http://https%3A%2F%2Fshop.......

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://shop.kathi-wilson.com
Site URL: https://shop.kathi-wilson.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_nmy5thfrva_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

Akismet Anti-Spam: by Automattic – 3.3
Cornerstone: by Themeco – 2.0.3
Form Maker Pro: by WebDorado – 2.10.7
MP3-jPlayer: by Simon Ward – 2.7.2
Slider Revolution: by ThemePunch – 5.3.1.5
WooCommerce: by Automattic – 3.0.4
Yoast SEO: by Team Yoast – 4.6
X – Custom 404: by Themeco – 1.1.3
X – Email Forms (MailChimp): by Themeco – 1.1.2
X – Google Analytics: by Themeco – 1.0.3
X – Typekit: by Themeco – 1.0.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #68 - /shop/
Cart: #70 - /shop/cart/
Checkout: #72 - /shop/cart/checkout/
My account: #74 - /my-account/

### Theme ###

Name: X – Child Theme
Version: 1.0.0
Author URL: http://theme.co/
Child Theme: ✔
Parent Theme Name: X
Parent Theme Version: 5.0.2
Parent Theme Author URL: http://theme.co/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: x/woocommerce/cart/cart-empty.php
x/woocommerce/cart/cross-sells.php
x/woocommerce/loop/loop-end.php
x/woocommerce/loop/loop-start.php
x/woocommerce/loop/pagination.php
x/woocommerce/notices/error.php
x/woocommerce/notices/notice.php
x/woocommerce/notices/success.php
x/woocommerce/single-product/product-image.php
x/woocommerce/single-product/product-thumbnails.php
x/woocommerce/single-product/related.php
x/woocommerce/single-product/tabs/tabs.php
x/woocommerce/single-product/up-sells.php
x/woocommerce/single-product-reviews.php

`
</details>

**Comment by mikejolley** [comment]
Why use an encoded URL? Paste the proper URL and WC will handle encoding.

**Comment by nlevasseur** [comment]
Hey Mike,

Thanks so much for your reply. When you hover over the little question mark, it says that all URLs must be encoded.

 

Does WP really encode files?

 

This is my first store. . . so I’m learning!!!

 

Nancy

 

 <https://youbydesignwebsites.com/> Youbydesignwebsites.com

 

Everyone has a story.

We can help you tell yours.

 

Nancy LeVasseur

198 Ironstone Ridge Road

Lancaster, PA 17603

 

717-413-1498

**Comment by mikejolley** [comment]
I believe thats referring to things like spaces being encoded to `%20`, not how you're entering it.
