### ISSUE TITLE
Add a webhook event for untrashing (restoring) an order

### ISSUE THREAD

**Issue by cristiangrama** [woocommerce/woocommerce#14607]
### EXPLANATION OF THE ISSUE

Version 3.0.x

When trashing and restoring an order, there is no hook associated with the restore action.

### STEPS TO REPRODUCE THE ISSUE

Trashing an order triggers the webhook `order.deleted`. However the order still exists in the system and can be restored. When restoring the order there is not associated webhook topic that can be set for that.

### SOLUTION
I believe that the best option here would be to trigger an `order.created` or `order.updated` when restoring an order. Another option would be to have another hook `order.restored`.

**Comment by claudiulodro** [comment]
See #14767.
