### ISSUE TITLE
Filter parameter is needed in the new REST API

### ISSUE THREAD

**Issue by postnik0706** [woocommerce/woocommerce#14603]
Hi, will there be something like a Filter parameter existing in WooCommerce new REST API v2?
I need it. That seems to be the only way of getting modified orders only, using updated_at_min / updated_at_max. 
I need to maintain a database-based cache of orders; was relying on getting the changed orders only.
Would appreciate any insights, or maybe there is another way of implementing the above.
Thanks!
Alex

**Comment by mikejolley** [comment]
No; WordPress no longer supports the filter param. We do have some custom parameters to search orders and these are listed in the docs. Post modified is not a field we search on.

If you need to track changes to orders as modified, take a look into our webhooks instead.

**Comment by claudiosanches** [comment]
We can include new filters for query by last modified in a future release.

**Comment by postnik0706** [comment]
That would be so great! Thanks for taking into consideration!

**Comment by apost0706** [comment]
Hi, any word on when this is going to be implemented? We use wc-api/v3; is it going to be retired any time soon?
We use a desktop app to import WooCommerce data; need this function as there is no internet endpoint.
Please advise.
