### ISSUE TITLE
Coupon field too small

### ISSUE THREAD

**Issue by luggie** [woocommerce/woocommerce#14614]
Hi there!
The input field of vouchers when checking out in my WooCommerce shop is too small.
![wooc](https://cloud.githubusercontent.com/assets/27887321/25303629/5e32054e-2757-11e7-894c-5039049f5e5b.PNG)
I'm using uptodate WP and WC (4.74/3.0.4 with German Translation 3.2) with Graphene Theme
Any Suggestions?
Thanks
luggie

**Comment by mikejolley** [comment]
Needs to be styled in your theme CSS - you'll see the default theme styling handles it correctly: https://dl.dropboxusercontent.com/s/s7lst65o67gvy88/2017-04-22%20at%2012.18.png

Look at setting font size and padding on the field.

**Comment by luggie** [comment]
shouldn't it be somewhere in WooCommerce CSSs?

**Comment by mikejolley** [comment]
CSS cascades by design; so your theme may have rules which change the size too, or may not even use our CSS.
