### ISSUE TITLE
Product types - wc_get_products()

### ISSUE THREAD

**Issue by Chunkford** [woocommerce/woocommerce#14619]
I don't understand why in [wc-product-functions.php](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-product-functions.php#L56) you can pass in an array for `type`, but when it calls [get_products()](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-product-functions.php#L88) within the product data store it overwrites `post_type` with either [product_variation or product](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L1162) exclusively.

Unless there are plans in the future to change this, does this mean if I need both products and variations, I need to run two seperate queries and merge them together?
Also, if I want custom product types such as subscriptions or variable subscriptions products, I will have to use standard WP queries?

**Comment by mikejolley** [comment]
`post_type` !== `type`

post type is `product_variation` or `product`, always.

`type` is simple, grouped, variable etc.

**Comment by Chunkford** [comment]
Thanks for replying @mikejolley 
OK, that makes sense.
But does that mean that I can only get products or variations, not both at the same time?

I used to use:
```
$product_ids = get_posts( array(
   'posts_per_page' => -1,
   'post_type'	=> array(
      'product', 
       'product_variation'
   )
) );
```

But when I do:
```
$products = wc_get_products( array(
   'limit' => -1,
) );
```
It doesn't return variations.

**Comment by mikejolley** [comment]
Not at the same time no because of the difference in post types.

**Comment by pablo-sg-pacheco** [comment]
Hi guys,

Do I really have to run `wc_get_products()` twice if I need to get the variations too? I could only make it work like that.
