### ISSUE TITLE
Invalid argument supplied for foreach() in class-wc-logger.php on line 47

### ISSUE THREAD

**Issue by alanmac** [woocommerce/woocommerce#14615]
### EXPLANATION OF THE ISSUE

After upgrade to WP 4.7.4 and WooCommerce 3.0.4 I'm getting the following output in WordPress backend and some front-end areas of the site:

**Warning: Invalid argument supplied for foreach() in ../wp-content/plugins/woocommerce/includes/class-wc-logger.php on line 47**

### STEPS TO REPRODUCE THE ISSUE

Upgraded to Wordpress 4.7.4 and WooCommerce 3.0.4

### SYSTEM STATUS

<details>

### WordPress Environment ###

Home URL: [removed]
Site URL: [removed]
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔  1 active Zapier Feed.
Zapier Integration - Cron Tasks: ✔  0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔  Order Processing Trigger
Zapier Feed #1 Webhook URL: ✔  [removed]
Zapier Feed #1 Trigger: ✔  New Order Status Change
Zapier Feed #1 Test Result: ✔  Successfully sent sample data to [removed].

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

AfterShip - WooCommerce Tracking: by AfterShip – 1.6.8
Akismet Anti-Spam: by Automattic – 3.3
iThemes Security: by iThemes – 6.2.1
Black Studio TinyMCE Widget: by Black Studio – 2.3.2
Check Email: by Chris Taylor – 0.5.2
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.2.1

Creative Clans Embed Script: by Guido Tonnaer – 1.2
Disable Comments: by Samir Shah – 1.6
Don’t Muck My Markup: by Martyn Chamberlin – 1.6
Google Tag Manager for Wordpress: by Thomas Geiger – 1.6.1
Eggplant 301 Redirects: by Shawn Wernig http://www.eggplantstudios.ca – 2.3.0
Maintenance: by fruitfulcode – 3.4.1
Ninja Forms: by The WP Ninjas – 3.0.34
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.1.6
WordPress Robots.txt File: by Ataul Ghani – 1.4
Server IP & Memory Usage Display: by Apasionados
Apasionados del Marketing – 1.4.0

SG Optimizer: by SiteGround – 3.2.3
Simple History: by Pär Thernström – 2.13
Page Builder by SiteOrigin: by SiteOrigin – 2.5.2
SSL Insecure Content Fixer: by WebAware – 2.2.3
Aelia Foundation Classes for WooCommerce: by Aelia – 1.8.6.170405
WooCommerce Brands: by WooThemes – 1.5.0
WooCommerce Categories Menu: by Alvaro Neto – 1.2.0
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Email Validation: by Hugh Lashbrooke – 2.1
WooCommerce Free Gift: by Rene Puchinger – 1.7.8
WooCommerce First Data/Authipay Gateway: by Aelia – 1.2.17.161006
WooCommerce MailChimp Integration: by WooCommerce – 1.0.2
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.1
WooCommerce Smart Sale Badge: by Hugh Lashbrooke – 1.1
WooCommerce Zapier Integration: by OM4 – 1.6.7
WooCommerce: by Automattic – 3.0.4
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.6
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP Server Date Time: by Dhruwal Patel – 0.5
WP Sitemap Page: by Tony Archambeau – 1.6
WP Smush: by WPMU DEV – 2.6.3

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1320 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Virtue - Premium Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Virtue - Premium
Parent Theme Version: 4.1.6
Parent Theme Author URL: https://www.kadencethemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: virtue_premium/woocommerce/archive-product.php
virtue_premium/woocommerce/content-product.php
virtue_premium/woocommerce/content-product_cat.php
virtue_premium/woocommerce/content-single-product.php
virtue_premium/woocommerce/loop/loop-end.php
virtue_premium/woocommerce/loop/loop-start.php
virtue_premium/woocommerce/loop/rating.php
virtue_premium/woocommerce/loop/sale-flash.php
virtue_premium/product-searchform.php
virtue_premium/woocommerce/single-product/add-to-cart/external.php
virtue_premium/woocommerce/single-product/add-to-cart/grouped.php
virtue_premium/woocommerce/single-product/add-to-cart/simple.php
virtue_premium/woocommerce/single-product/add-to-cart/variable.php
virtue_premium/woocommerce/single-product/product-image.php
virtue_premium/woocommerce/single-product/product-thumbnails.php
virtue_premium/woocommerce/single-product/related.php
virtue_premium/woocommerce/single-product/sale-flash.php
virtue_premium/woocommerce/single-product/title.php
virtue_premium/woocommerce/single-product/up-sells.php
virtue_premium-child/woocommerce/single-product.php
virtue_premium/woocommerce/taxonomy-product_cat.php
virtue_premium/woocommerce/taxonomy-product_tag.php

</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14616
