### ISSUE TITLE
Change order of billing fields on checkout page

### ISSUE THREAD

**Issue by ZERGE** [woocommerce/woocommerce#14618]
### EXPLANATION OF THE ISSUE

I'm using the WC filter to order billing fields, and it worked fine before (WC 3.0.3) updating to WooCommerce 3.0.4

It seems the filter works fine, but for unknown reasons it revert back on the fly to the default order.

```
add_filter("woocommerce_checkout_fields", "custom_order_fields");

function custom_order_fields($fields) {
	$order = array(
		"billing_email", 
		"billing_first_name", 
		"billing_last_name",
		"billing_phone", 
		"billing_address_1",  
		"billing_postcode",
		"billing_address_2",
		"billing_country" 
	);

	foreach($order as $field)
	{
		$ordered_fields[$field] = $fields["billing"][$field];
	}

	$fields["billing"] = $ordered_fields;

	$fields['billing']['billing_address_1']['placeholder'] = '';
	$fields['billing']['billing_address_2']['placeholder'] = '';
	$fields['billing']['billing_phone']['placeholder'] = '';
	$fields['billing']['billing_address_2']['label'] = __( 'City', 'blank' );
	$fields['billing']['billing_phone']['label'] = __( 'Phone number', 'blank' );

	return $fields;
}
```

As I understand, it happened after these changes - https://github.com/woocommerce/woocommerce/commit/3b6e7d9d141375fcfd792c484066760bf33a14a9

### STEPS TO REPRODUCE THE ISSUE

WooCommerce 3.0.4 + code above in the functions.php

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: [removed]
Site URL: [removed]
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 7.0.18
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Redux Framework: by Team Redux – 3.6.4
AJAX Thumbnail Rebuild: by junkcoder – 1.12
Change Quantity on Checkout for WooCommerce: by Bhavik Kiri – 1.0
Fraktjakt Shipping Method for WooCommerce: by Fraktjakt AB (Sweden) – 1.6.3
Instagram Feed: by Smash Balloon – 1.4.8
Meta Box: by Anh Tran – 4.11
Smart Variations Images: by David Rosendo – 3.2.11
WooCommerce Variation Swatches: by ThemeAlien – 1.0.2
vConnect PostNord All in One - Origin Sweden: by vConnect – 1.2.13
Booster Plus for WooCommerce: by Algoritmika Ltd – 1.1.0
WooCommerce Direct Checkout: by Terry Tsang – 1.1.2
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.0
WooCommerce Stripe Gateway: by WooCommerce – 3.1.6
Booster for WooCommerce: by Algoritmika Ltd – 2.7.1
WooCommerce MailChimp: by Saint Systems – 2.0.20
WooCommerce Quantity Increment: by Automattic
WooThemes – 1.1.0

WooCommerce: by Automattic – 3.0.4
WordPress Importer: by wordpressdotorg – 0.6.3
XCloner - Site Backup and Restore: by Liuta Ovidiu – 4.0.3
Easy Forms for MailChimp: by YIKES
Inc. – 6.3.14

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #21851 - /butik/
Cart: #20076 - /cart/
Checkout: #8 - /checkout/
My account: #20078 - /my-account/

### Theme ###

Name: Blank
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: blank-v2/woocommerce/cart/cart-shipping.php
blank-v2/woocommerce/checkout/form-billing.php
blank-v2/woocommerce/checkout/form-checkout.php
blank-v2/woocommerce/checkout/form-coupon.php
blank-v2/woocommerce/checkout/form-shipping.php
blank-v2/woocommerce/checkout/payment.php
blank-v2/woocommerce/checkout/review-order.php
blank-v2/woocommerce/content-single-product.php
blank-v2/woocommerce/global/quantity-input.php
blank-v2/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
blank-v2/woocommerce/single-product/price.php
blank-v2/woocommerce/single-product.php

`
</details>

**Comment by mikejolley** [comment]
Answered on forum.

**Comment by TCattd** [comment]
If someone arrives here by Googling this same issue, the topic is this: https://wordpress.org/support/topic/change-order-of-billing-fields-on-checkout-page/

The trick is to set the "priority", like this:
```
$fields['billing']['billing_country']['priority'] = 10;
$fields['billing']['billing_phone']['priority'] = 20;
```

That's all.

**Comment by WM4362** [comment]
This is a much better way to do it. As Mike has noted elsewhere it will cut out a bunch of hacky code from your functions file!

The key point is this comment from line 1144 of class-wc-countries.php:

```
		/**
		 * Important note on this filter: Changes to address fields can and will be overridden by
		 * the woocommerce_default_address_fields. The locales/default locales apply on top based
		 * on country selection. If you want to change things like the required status of an
		 * address field, filter woocommerce_default_address_fields instead.
		 */
```

So if you set a priority using filters like "woocommerce_checkout_fields", "woocommerce_billing_fields" or "woocommerce_shipping_fields" that conflicts with the localisation formatting defined in public function get_address_formats() (line 421)... then your priorities will be ignored/overwritten (weird things might happen too... like additional fields appearing without labels and other such gibberish).

So the trick (I think) is to customise what you can using one of the above mentioned filters, and then use "woocommerce_default_address_fields" to prioritise fields that will conflict with your localisation.

E.g. with an AU locale, I could move Country to last as this matched my locale, but I had to use the default address fields filter to reorder the Address 1 and 2 fields.

```
// Billing Fields.
add_filter( 'woocommerce_billing_fields' , 'woocommerce_billing_fields_custom' );

function woocommerce_billing_fields_custom( $fields ) {
	$fields['billing_phone']['required'] = false;
	$fields['billing_phone']['maxlength'] = 10;
	$fields['billing_state']['class'] = array( 'form-row-first' );
	$fields['billing_postcode']['maxlength'] = 4;
	$fields['billing_postcode']['class'] = array( 'form-row-last' );
	//Order Billing fields
	$fields['billing_email']['priority'] = 33;
	$fields['billing_phone']['priority'] = 37;
	$fields['billing_country']['priority'] = 100;
	
	return $fields;
}

// Shipping Fields.
add_filter( 'woocommerce_shipping_fields' , 'woocommerce_shipping_fields_custom' );

function woocommerce_shipping_fields_custom( $fields ) {
	$fields['shipping_state']['class'] = array( 'form-row-first' );
	$fields['shipping_postcode']['maxlength'] = 4;
	$fields['shipping_postcode']['class'] = array( 'form-row-last' );
	//Order Shipping fields
	$fields['shipping_country']['priority'] = 100;
	
	return $fields;
}

add_filter( 'woocommerce_default_address_fields', 'woocommerce_default_address_fields_reorder' );
 
function woocommerce_default_address_fields_reorder( $fields ) {
	$fields['address_1']['priority'] = 60;
	$fields['address_2']['priority'] = 50;
	
	return $fields;
}
```

PS: an alternative to using the woocommerce_default_address_fields filter could be to customise your locale to match your prioritising of fields using the "woocommerce_localisation_address_formats" filter. I've not tested this, but I figured it might help others.

```
add_filter( 'woocommerce_localisation_address_formats', 'woocommerce_localisation_address_formats_custom', 20 );

function woocommerce_localisation_address_formats_custom( $formats ) {
	$formats['AU'] = "{name}\n{company}\n{address_2}\n{address_1}\n{city} {state} {postcode}\n{country}";
	
	return $formats;
}
```

**Comment by claudiosanches** [comment]
@TCattd @WM4362 as pointed in several places, here is not a support forum and questions like this should be answered on the properly support forum on WordPress.org, that is still indexed by Google.
Thanks for both contributions, but I'm closing this issue for future iterations.
