### ISSUE TITLE
WC Tab Manager 1.8.0 (Global Tab not visible)

### ISSUE THREAD

**Issue by xlanalyticsinc** [woocommerce/woocommerce#14613]
I'm using WC Tab Manager 1.8.0. The global tab is not visible on product pages, unless activated inside individual product pages. The same is true for global tab created for product categories, Any ideas? Thanks. 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
This bug tracker is for core, not extensions. Please use the help desk so the devs can be notified if there is an issue - https://woocommerce.com/my-account/tickets/
