### ISSUE TITLE
set_prop inherited methods doesn't work on WC 3.0.4

### ISSUE THREAD

**Issue by ducminhn** [woocommerce/woocommerce#14611]
### EXPLANATION OF THE ISSUE

Since WC 3.0.0, the abstract Product class has these methods: set_sale_price, set_date_on_sale_from, set_date_on_sale_to ... When I'm trying to set the the sale price in PHP, the method doesn't do anything. None of the methods above work to update the new value.

### STEPS TO REPRODUCE THE ISSUE
```
$product = new WC_Product(4139);
$product->set_sale_price(2099);
$product->set_date_on_sale_from('20/04/2017');
$product->set_date_on_sale_to('27/04/2017');
```

### SYSTEM STATUS

<details>
WordPress environment
WC version:		3.0.4
WP version:		4.7.4
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		
WP cron:		
Language:		en_US
Server environment
Server info:		Apache
PHP version:		5.6.30
PHP post max size:		32 MB
PHP time limit:		-1
PHP max input vars:		1000
cURL version:		7.53.1, OpenSSL/1.0.1e
SUHOSIN installed:		–
MySQL version:		5.6.35
Max upload size:		32 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.4
</details>

**Comment by mikejolley** [comment]
Changes do not persist until you save: https://github.com/woocommerce/woocommerce/wiki/CRUD-Objects-in-3.0#saving-and-deleting

**Comment by ducminhn** [comment]
Thanks, @mikejolley
