### ISSUE TITLE
Product removed from Downloadable product permissions TAB in all orders?

### ISSUE THREAD

**Issue by drosendo** [woocommerce/woocommerce#14610]
I cant say 100% sure its related to latest update, but If someone can backup me woudl be great.

So I just updated my virtual product, and all orders that should have access to it lost the download permission, meaning it no longer shows the product on the order to be download nor in the back-office in the "Downloadable product permissions" tab.

THanks,
David

**Comment by mikejolley** [comment]
Updating past orders with new downloads is simply not performant and cannot scale. This has been taken out (place back at your own risk - https://github.com/woocommerce/grant-download-permissions-for-past-woocommerce-orders).

Additionally, the old behavior would essentially reset download counts + access restrictions as new permissions were granted.

It's just removing and adding files which will not update those past orders.

In 3.0, EDITING a download file will however update past order download permissions with the new link.
