### ISSUE TITLE
Unpaid order cancelled - time limit reached 

### ISSUE THREAD

**Issue by impressionsagency** [woocommerce/woocommerce#14625]
### EXPLANATION OF THE ISSUE

After updated to woo 3.0.4, we randomly had three orders canceled all with the message: Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled.

We made some additional plugin updates to some woo plugins, and placed a test order which it did not happen to, but then today it randomly did the same thing again to two more orders. 

### STEPS TO REPRODUCE THE ISSUE

Placed a test order, but wasn't able to reproduce it. When I checked server error logs I couldn't find anything indicating a server timeout issue. 
<img width="357" alt="screen shot 2017-04-22 at 10 41 10 pm" src="https://cloud.githubusercontent.com/assets/27909808/25310947/bf1613de-27af-11e7-9d08-42a2f2e63486.png">
<img width="353" alt="screen shot 2017-04-22 at 10 41 50 pm" src="https://cloud.githubusercontent.com/assets/27909808/25310948/bf16696a-27af-11e7-9ccc-dd81340f7257.png">

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://holistichound.com
Site URL: https://holistichound.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.21
PHP Post Max Size: 64 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_mtyq_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

All In One SEO Pack: by Michael Torbert – 2.3.12.2.1
Artbees Themes Captcha: by Jose Rodriguez  – 1.0
Contact Form DB: by Michael Simpson – 2.10.28
Contact Form 7: by Takayuki Miyoshi – 4.7
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
Facebook Page Plugin: by Cameron Jones – 1.6.1
Instagram Feed: by Smash Balloon – 1.4.8
Jetpack by WordPress.com: by Automattic – 4.8.2
WPBakery Visual Composer (Modified Version): by Michael M - WPBakery.com – 5.0.2
Local Geo Search: by Elite Impressions
LLC – 1.1.1

Login Screen Manager: by Nazmul Hossain Nihal – 3.5.1
Postman SMTP: by Jason Hendriks – 1.7.2
Redirection: by John Godley – 2.5
Slider Revolution: by ThemePunch – 5.3.1.5
WooCommerce Intuit Payments Gateway: by SkyVerge – 2.0.0
WooCommerce USPS Shipping: by WooCommerce – 4.4.5
WooCommerce Simply Order Export: by Ankit Gade – 2.1.7
WooCommerce Wholesale Lead Capture: by Rymera Web Co – 1.6.10
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.14.4
WooCommerce Wholesale Prices: by Rymera Web Co – 1.4.4
WooCommerce: by Automattic – 3.0.4
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1120 - /shop/
Cart: #87 - /cart/
Checkout: #89 - /checkout/
My account: #91 - /my-account/

### Theme ###

Name: Theme for Holistic Hound
Version: 1.2
Author URL: 
Child Theme: ✔
Parent Theme Name: Jupiter
Parent Theme Version: 5.9
Parent Theme Author URL: http://themeforest.net/user/artbees
WooCommerce Support: ✔

### Templates ###

Overrides: jupiter/woocommerce/archive-product.php
jupiter/woocommerce/content-product.php
jupiter/woocommerce/content-product_cat.php
jupiter/woocommerce/loop/add-to-cart.php
jupiter/woocommerce/loop/loop-end.php
jupiter/woocommerce/loop/loop-start.php

### Intuit QBMS ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
`
</details>

**Comment by mikejolley** [comment]
According to the notes you posted, a user named holistichound changed the order status to **pending payment**. Pending orders will cancel after X days/hours if not paid. It's not random.

**Comment by impressionsagency** [comment]
Okay thanks. So the issue is probably the payment gateway.. It only started happening since we updated, and the payment gateway was also updated, but we'll dive in further. 

Thanks,

**Comment by mikejolley** [comment]
The notes indicate a user updated the order, not a gateway. the user name is displayed in the note.

**Comment by impressionsagency** [comment]
Hi Mike, 
Here is the full chain though. The orders automatically get updated to pending by woocommerce until they are set to complete. But take a look at this full note history: 
![screenshot-holistichound com 2017-04-24 11-23-26](https://cloud.githubusercontent.com/assets/27909808/25350029/f867986a-28e0-11e7-8c66-1867f0b2293b.png)


The payment gets approved, then the order is set to processing, tracking is assigned via USPS, then it reverts back processing to pending payment, and order is cancelled. 

This has happened with 5 orders within 2 days. The payments go through which is why it seems random. I can't figure out what is causing it.  If you have any additional thoughts let me know. 

Thanks!

**Comment by impressionsagency** [comment]
Hi, 
You can disregard this. I think it may be coming from the shipping plugin that auto updates the order. 

Thanks again,

**Comment by sumitsinghwp** [comment]
Any update about this issue? I am facing this issue last few months :(
![image](https://github.com/woocommerce/woocommerce/assets/23701579/40954b11-cdc9-4b19-b7e4-4095efcc1f0e)
