### ISSUE TITLE
The item attribute on the page is not added after the update

### ISSUE THREAD

**Issue by ArtemChay** [woocommerce/woocommerce#14621]
### EXPLANATION OF THE ISSUE

I'm trying to add an attribute created in advance in the product card, but it is not added. This began to happen after the upgrade of the platform and the WooCommerce plugin

<details>
`
### WordPress Environment ###

Home URL: http://magya.kz
Site URL: http://magya.kz
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: 42c3Zh_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌В вашем магазине не используется HTTPS. Подробнее о HTTPS и SSL-сертификатах .
Hide errors from visitors: ✔

### Active Plugins (12) ###

LayerSlider WP: от Kreatura Media – 6.0.5
Ultimate Addons for Visual Composer: от Brainstorm Force – 3.16.7
All In One SEO Pack: от Michael Torbert – 2.3.12.2.1
Contact Form 7: от Takayuki Miyoshi – 4.7
DesignThemes Core Features Plugin: от DesignThemes – 1.7
Envato WordPress Toolkit: от Envato – 1.7.3
WPBakery Visual Composer: от Michael M - WPBakery.com – 4.12.1
Responsive Styled Google Maps: от greenline – 4.0
Slider Revolution: от ThemePunch – 5.3.0.2
The Events Calendar: от Modern Tribe
Inc. – 4.4.5

Veda Demo Importer: от DesignThemes – 1.9
WooCommerce: от Automattic – 3.0.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: KZT (KZT)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Ссылка магазина: #13 - /shop/
Корзина: #14 - /shop/cart/
Оформление заказа: #15 - /shop/checkout/
Мой аккаунт: #16 - /shop/my-account/

### Theme ###

Name: Veda
Version: 2.0
Author URL: https://wedesignthemes.com/
Child Theme: ❌ – Если вы модифицируете элементы WooCommerce в теме WordPress
которую вы не разрабатывали самостоятельно
рекомендуется использовать дочернюю тему. Читайте: Как создать дочернюю тему

WooCommerce Support: ✔

### Templates ###

Overrides: veda/woocommerce/content-product_cat.php
veda/woocommerce/single-product-reviews.php

`
</details>

**Comment by mikejolley** [comment]
Can you provide some screenshots showing what you're attempting and what happens?

**Comment by ArtemChay** [comment]
Hi.There're some screenshots for you.You can login to my adminpanel to look by yourself. Login: Admin:Password: CfwwC)A)g8q06P*VX((*nBtm 24.04.2017, 18:34, "Mike Jolley" <notifications@github.com>:Can you provide some screenshots showing what you're attempting and what happens?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.     Sincerely,Artem Chay,e-mail: art.chay@yandex.ru+7 771 864 04 24

**Comment by mikejolley** [comment]
Nooo don't share login details on here it's public. I've removed them - **you need to change that password asap.**

**Comment by ArtemChay** [comment]
That's ok))) It's not dangerous now for me!))  24.04.2017, 20:33, "Mike Jolley" <notifications@github.com>:Nooo don't share login details on here it's public. I've removed them - you need to change that password asap.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- С уважениемАртем Чай+7 771 864 04 24

**Comment by ArtemChay** [comment]
The item attribute on the page is not added after the update (#14621)And what shell I do? Just wait for another update? 24.04.2017, 20:33, "Mike Jolley" <notifications@github.com>:Nooo don't share login details on here it's public. I've removed them - you need to change that password asap.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- SencerelyArtem Chay+7 771 864 04 24

**Comment by mikejolley** [comment]
Just providing some screenshots as requested would be ideal thanks!

**Comment by ArtemChay** [comment]
When I try to choose any attribute, the system starts loading and then freeze.Whitout any signs of life 24.04.2017, 23:14, "Mike Jolley" <notifications@github.com>:Just providing some screenshots as requested would be ideal thanks!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- С уважениемАртем Чай+7 771 864 04 24

**Comment by gorrynych** [comment]
I have its problem too. When I try to choose any attribute, the system starts loading and then freeze. Why?

**Comment by mikejolley** [comment]
> When I try to choose any attribute, the system starts loading and then freeze.Whitout any signs of life

Then this is a **conflict** - something will be throwing an error during the AJAX load.

You can either look at the PHP error log to get the 'fatal error', or disable/switch themes until the issue resolves so you know what is causing it.

Feel free to paste the error message here if you need to know which one is doing it. You could send a login privately also if you wish but I may not be able to see the error without the logs.
