### ISSUE TITLE
Error "No route was found matching the URL and request method" when call api

### ISSUE THREAD

**Issue by trathi** [woocommerce/woocommerce#14629]
Hi ALL
I test woocommerce-rest-api retrieve list product 

https://xxx.net/dev/binl-retail-pos/wp-json/wc/v2/products

return error
{
  "code": "rest_no_route",
  "message": "No route was found matching the URL and request method",
  "data": {
    "status": 404
  }
}

Please help me get this going on.

Thanks

**Comment by mikejolley** [comment]
See the requirements https://woocommerce.github.io/woocommerce-rest-api-docs/#requirements and ensure you're on WC 3.0+
