### ISSUE TITLE
Woocommerce My account custom end point breadcrumb

### ISSUE THREAD

**Issue by rgfx** [woocommerce/woocommerce#14624]
Can't seem to make a breadcrumb when I add a custom page to "My account"

Followed the direction on Woocommerce [Customizing account page tabs](https://github.com/woocommerce/woocommerce/wiki/Customising-account-page-tabs#adding-content-to-an-endpoint")

Worked fine, just have an issue with breadcrumbs, maybe am being too detail oriented let me know. 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/F5Xom.gif

I would like it to list like the downloads page

**Comment by mikejolley** [comment]
To be in the breadcrumb, it needs a custom title set: https://github.com/woocommerce/woocommerce/blob/e614d9d5e3bbce38d7e85719b65a7e6958cd0409/includes/class-wc-query.php#L132

Code is handled here if you want to trace back why it's not showing if the above does not work. 

https://github.com/woocommerce/woocommerce/blob/a7b2a0ac7c2942ce9eab9e17f49f106263835944/includes/class-wc-breadcrumb.php#L326-L331

**Comment by sehrish-iftikhar** [comment]
Hello Mike,

Filter is not working for custom endpoint. For example, I added custom "history" end point then the filter hook "'woocommerce_endpoint_history_title" is not working.

Can you please guide me where I'm doing wrong?

Thanks!

**Comment by sehrish-iftikhar** [comment]
Mike, can you please answer my query?

**Comment by mikejolley** [comment]
Maybe add a var dump around here to see what $endpoint is in your case? https://github.com/woocommerce/woocommerce/blob/e614d9d5e3bbce38d7e85719b65a7e6958cd0409/includes/class-wc-query.php#L131

**Comment by sehrish-iftikhar** [comment]
Please correct me if I am doing something wrong. Just let me know if I am creating a custom endpoint let suppose "product-history".  When I use WC breadcrumb then it shows all breadcrumb for WC My Account tabs but showing blank for my custom product history tab.

**Comment by sehrish-iftikhar** [comment]
Can you please guide me which filter I need to use to show this custom endpoint with WooCommerce breadcrumb.

**Comment by sehrish-iftikhar** [comment]
WooCommerce breadcrumb with their default My Account tabs:

**Comment by sehrish-iftikhar** [comment]
https://prnt.sc/hlzvk1

WC breadcrumb with custom endpoint
https://prnt.sc/hlzvgh

**Comment by sehrish-iftikhar** [comment]
Mike any response? I think you are the person who can guide me better. I just need direction and rest of the code and customizations I will do myself. Many thanks!

**Comment by mikejolley** [comment]
Can you share the code on github gist?

**Comment by sehrish-iftikhar** [comment]
I'm not writing any code instead of using your plugin default breadcrumb code on My Account page.

```
$args = array(
                    'delimiter' => ' <li><i class="fa fa-angle-double-right" aria-hidden="true"></i></li>',
                    'wrap_before' => '<div class="breadcrumb"><ol>',
                    'wrap_after' => '</ol></div>',
                    'before' => '<li> ',
                    'after' => '</li>',
                    'home' => '',
                );

                woocommerce_breadcrumb($args);
```
This code is working perfectly for My Account tabs but not working for the custom added tab. Is your code is not compatible with other custom tabs? If no then please suggest me the hook to add breadcrumb.

WC breadcrumb with custom endpoint
https://prnt.sc/hlzvgh

**Comment by mikejolley** [comment]
I want to see the code used to add the custom endpoint so I can try it.

**Comment by sehrish-iftikhar** [comment]
https://gist.github.com/sehrish-iftikhar/08ab63db4e6dafdb435153d478ebacaa

**Comment by mikejolley** [comment]
Is this missing your `woocommerce_endpoint_banked-hours_title` code? Or are you adding that elsewhere?

**Comment by sehrish-iftikhar** [comment]
I am adding the menu using "woocommerce_account_menu_items" hook.

**Comment by sehrish-iftikhar** [comment]
Also "woocommerce_endpoint_banked-hours_title" is not working.

**Comment by mikejolley** [comment]
The `woocommerce_endpoint_banked-hours_title` filter and function is missing in the code you showed me. That controls the title on the endpoint/breadcrumb. Without this the endpoint has no title.

**Comment by sehrish-iftikhar** [comment]
It is not working for me :(  I have updated the gist code and put a die() function to test function's running. But no success.
https://gist.github.com/sehrish-iftikhar/08ab63db4e6dafdb435153d478ebacaa

**Comment by mikejolley** [comment]
It's not adding the query var through our API. It needs to be:

```
    /**
     * Initialize the class and set its properties.
     *
     * @since    1.0.0
     */
    public function __construct() {

        // Woocommerce Hook - Add query variable for user's banked hours purchase history
        add_filter('woocommerce_get_query_vars', array($this, 'banked_hours_history_query_vars'), 0);

        // Woocommerce Hook - Add endpoint title.
        add_filter('woocommerce_endpoint_banked-hours_title', array($this, 'banked_hours_tab_title'), 0);

        // Woocommerce Hook - Get My Account Menu Items
        add_filter('woocommerce_account_menu_items', array($this, 'add_banked_hours_history_menu'), 0);

        // Woocommerce Hook - Add content to banked hours history
        add_action('woocommerce_account_banked-hours_endpoint', array($this, 'banked_hours_history_content'), 0);
    }

    /**
     * Set endpoint title.
     *
     * @since   1.0.0
     */
    public function banked_hours_tab_title( $title ) {
        return __( 'Banked Hours', 'woocommerce' );
    }

    /**
     * Add endpoints for banked hours History
     *
     * @since    1.0.0
     */
    public function banked_hours_history_query_vars( $endpoints ) {
		$endpoints['banked-hours'] = 'banked-hours';
		return $endpoints;
    }
```

Otherwise WC does not know it exists.

**Comment by sehrish-iftikhar** [comment]
WOW! It is working as expected. Thank you so much, Mike, for your help :) Really appreciate your time and help. God bless you.
