### ISSUE TITLE
Percent encoding of shop page slug is case sensitive with regards to product display

### ISSUE THREAD

**Issue by ripieces** [woocommerce/woocommerce#14631]
### EXPLANATION OF THE ISSUE

When the shop page slug requires percent encoding (i.e. due to having UTF8 characters), products will only be displayed when the percent encoding uses lower case letters.

Expecting instead:
Percent encoding should work regardless if upper case or lower case letters are used for the encoding.

### STEPS TO REPRODUCE THE ISSUE

1. Use i.e. חנות as shop page slug
2.  Observe that `http://woo.vagas.co.il/%d7%97%d7%a0%d7%95%d7%aa/` works, while i.e. `http://woo.vagas.co.il/%D7%97%D7%A0%D7%95%D7%AA/` does not.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://woo.vagas.co.il
Site URL: http://woo.vagas.co.il
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17-1~dotdeb+8.1
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Limit Login Attempts: by Johan Eenfeldt – 1.7.1
WooCommerce: by Automattic – 3.0.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /%d7%97%d7%a0%d7%95%d7%aa/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

This is from a test site, it happens on other sites with different plugins and different themes as well, switching off all plugins except WooCommerce doesn't help either (in this case only the Limit Login Attempts plugin).

**Comment by ripieces** [comment]
(Edited the comment above with the details of a dedicated test site that has almost no plugins and a standard theme.)

**Comment by mikejolley** [comment]
This is a WordPress issue - see https://core.trac.wordpress.org/ticket/6697 Doesn't look like this is planned to support at present.

**Comment by ripieces** [comment]
@mikejolley thank you for your reply, but I found what you linked in Google earlier already too.

The **issue you linked is not related to the problem** in my opinion:

The issue complains about WordPress normalizing the slug to lower-case, which is a decision that does not void the standard quoted there.
The correct page content is served by WordPress nevertheless without a redirect, as demanded by the standard quoted there:
> If two URIs differ only in the case of hexadecimal digits used in percent-encoded octets, they are equivalent.

For example, both these URLs serve the **correct** WordPress "Test" ("בדיקה") page content _without_ a redirect (You can verify that with Firefox network analysis.):
`http://woo.vagas.co.il/%d7%91%d7%93%d7%99%d7%a7%d7%94/`
`http://woo.vagas.co.il/%D7%91%D7%93%D7%99%D7%A7%D7%94/`

Similarly the "Shop" ("חנות") page is served by WordPress for these two links _without_ a redirect:
`http://woo.vagas.co.il/%d7%97%d7%a0%d7%95%d7%aa/`
`http://woo.vagas.co.il/%D7%97%D7%A0%D7%95%D7%AA/`
**The difference here is that the lower-case version does display the shop page with products, while the upper-case version is missing the products.**

This problem is somewhat troublesome for non Latin charset users:
- Some search engines might decide to normalize the URLs, causing the Shop page served for the link not work properly.
- Also i.e. browsers like Firefox will normalize to upper-case letters when you enter the text behind the slash manually, meaning the "Shop" ("חנות") page won't work in those cases.

**Comment by mikejolley** [comment]
Thats the issue on trac. WP gets the querystring and decides what type of content/query is being shown. WC does not control this?

**Comment by ripieces** [comment]
Yes it indeed is a WordPress issue with the way the rewrite rules for the rewrite property of custom post types (in this case Product) are generated / applied for UTF8, so it's not WooCommerce related. I will try to file a bug report for the WordPress team instead.
Thank you for your reply and your time.
