### ISSUE TITLE
serializeJSON() conflicitng libraries

### ISSUE THREAD

**Issue by mensmaximus** [woocommerce/woocommerce#14630]
### EXPLANATION OF THE ISSUE

WooCommere variation data (price, atributes, stock, etc.) can't be saved if a plugin or theme uses [jquery.serialize-object.js](https://github.com/macek/jquery-serialize-object/blob/master/jquery.serialize-object.js) to serialize form data.

WooCommerce is using [jquery.serializeJSON](https://github.com/marioizquierdo/jquery.serializeJSON) to serialize the variation form data.

Both libraries use serializeJSON() to serialize data. Jquery.serialize-object.js retruns a real JSON string while jquery.serializeJSON returns a javascript object.

It took me some time to discover this issue because you don't get any error messages as you would with wrong data structures in php. At the moment WC_Meta_Box_Product_Data->save_variations() assumes the variatons form data to be processed as an array in $_POST.

Although the result of $variation->set_props is checked for errors there was no such admin message. This brings me to the actual question: Would there be a more reliable way to catch an error?

PS.: WooCommerce includes the rather old version 2.6.1 of jquery.serializeJSON. Should be repalced with version 2.8.1 with the next update.

### SYSTEM STATUS

<details>

`
### WordPress Environment ###

Home URL: http://bauenlassen.mmx.red
Site URL: http://bauenlassen.mmx.red
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips
PHP Version: 5.6.30
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: twijy_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ Die MaxMind GeoIP Datenbank existiert nicht - Die Ortung (Geolokalisierung) wird nicht funktionieren. Du kannst sie manuell installieren von http://dev.maxmind.com/geoip/legacy/geolite/ zu dem Pfad: . Scrolle einfach nach unten bis zu "Downloads" und lade die Datei "Binary / gzip" vom Typ "GeoLite Country" herunter. Denke bitte daran
die Datei GeoIP.dat.gz zu entpacken und nur die entpackte Datei GeoIP.dat hochzuladen.

### Security ###

Secure connection (HTTPS): ❌Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ❌Fehlermeldungen sollten Besuchern nicht angezeigt werden.

### Active Plugins (13) ###

All In One WP Security: von Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.2.7

Relevanssi Premium: von Mikko Saari – 1.15.0.1
Search & Filter Pro: von Designs & Code – 2.3.3
User Role Editor Pro: von Vladimir Garagulya – 4.34
User Switching: von John Blackbourn – 1.0.9
Web-Plan Finder: von mensmaximus – 2.3.0
WooCommerce PayPal Express Checkout Gateway: von WooCommerce – 1.2.0
WooCommerce Stripe Gateway: von WooCommerce – 3.1.7
WooCommerce Memberships: von SkyVerge – 1.8.3
WooCommerce Subscriptions: von Prospress Inc. – 2.2.5
WooCommerce: von Automattic – 3.0.4
WooCommerce Helper: von WooCommerce – 1.7.2 – Netzwerk aktiviert
WP ULike: von Ali Mirzaei – 2.4.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CHF (CHF)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #6442 - /shop/
Warenkorb: #6443 - /warenkorb/
Kasse: #6444 - /kasse/
Mein Konto: #6527 - /dashboard/dashboard-abopage/

### Theme ###

Name: Enfold Child Theme
Version: 1.0
Author URL: https://www.mensmaximus.info
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.0.5
Parent Theme Author URL: http://www.kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
</details>

**Comment by mikejolley** [comment]
Issue requires:

- Error handling
- Way to fail gracefully or handle both formats? Decode JSON after POST?
- Version bump the library.

Punting to 3.1.

**Comment by mikejolley** [comment]
I've moving this out since it's not a priority.

**Comment by mikejolley** [comment]
So we can update our version of serializeJSON for sure. But we won't be working around the conflict with serialize object because it's not well maintained, it's edge case, and given the lib name it should be using something other than serializeJSON function name...
