### ISSUE TITLE
Featured Prodcut 

### ISSUE THREAD

**Issue by alikhanbrandon** [woocommerce/woocommerce#14638]
Hi i just update the woocommerce but i cannot get the featured product my query like this .

                                                              array(
								'taxonomy' => 'product_visibility',
								'field' => '_featured',
								'terms' => 'Yes'
							    )

**Comment by mikejolley** [comment]
This is not a support forum.

> Hi i just update the woocommerce but i cannot get the featured product my query like this

https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#product-visibility-is-taxonomy-based-instead-of-meta-based
