### ISSUE TITLE
Product attributes not loading in backend

### ISSUE THREAD

**Issue by melcarthus** [woocommerce/woocommerce#14636]
### EXPLANATION OF THE ISSUE

Woocommerce ^3.0
Product attributes in backend are gone ( empty list ).
Adding new product attributes do show up in the back end.
Product attributes are in database
Product attributes show up on front end.

Debug mode on, no error is given.

So old products before the attributes went missing still have the attributes. But when I want to make a new variable product there are no attributes to choose from.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://audiowoud.site
Site URL: http://audiowoud.site
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL_formal

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) PHP/7.0.6 LibreSSL/2.2.7
PHP Version: 7.0.6
PHP Post Max Size: 25 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.51.0
SecureTransport

SUHOSIN Installed: –
MySQL Version: 5.7.9
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce: door Automattic – 3.0.4
WordPress Importer: door wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Pagina niet ingesteld
Winkelmand: ❌ Pagina niet ingesteld
Afrekenen: ❌ Pagina niet ingesteld
My account: ❌ Pagina niet ingesteld

### Theme ###

Name: Vender
Version: 2.0.5
Author URL: http://ecommercethemes.org/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

None happens with default install.

`
```
</details>

I disables all the plugins but woocommerce. I switchted to a default twenty17 theme. Still no product attributes.

I did an export of the variations and did a reimport, I got the message that they already excist.
I backed up my database, removed it and re-installed woocommerce and wordpress. Imported my exported data from the old website. no product attibutes showed up in the back end. The front-end and the database have the attributes in them.

**Comment by greenph1** [comment]
I have a similar problem where I cannot edit my product variations. The page won't open. Just a spinning ball.

`
### WordPress Environment ###

Home URL: http://greenphoenix.co.uk
Site URL: http://greenphoenix.co.uk
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wpb1_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (17) ###

Advanced Custom Fields Pro: by elliot condon – 5.3.4
Black Studio TinyMCE Widget: by Black Studio – 2.3.2
Breadcrumb NavXT: by John Havlik – 5.7.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Duplicate Post: by Enrico Battocchi – 3.2
Easy FancyBox: by RavanH – 1.5.8.2
Essential Grid: by ThemePunch – 2.0.9.1
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
Portfolio Post Type: by Devin Price – 0.9.3
QreativeShortcodes: by QreativeThemes – 1.0.1
Simple Page Sidebars: by Cedaro – 1.2.0
Page Builder by SiteOrigin: by SiteOrigin – 2.5.2
SiteOrigin Widgets Bundle: by SiteOrigin – 1.8.2
TwentyTwenty: by Corey Martin – 1.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

WooCommerce: by Automattic – 3.0.4
Yoast SEO: by Team Yoast – 4.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5581 - /shop/
Cart: #5582 - /shop/cart/
Checkout: #5583 - /shop/checkout/
My account: #5584 - /shop/my-account/

### Theme ###

Name: The Landscaper
Version: 1.1.2
Author URL: http://themeforest.net/user/QreativeThemes/portfolio
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: the-landscaper/woocommerce/global/sidebar.php
`

**Comment by mikejolley** [comment]
I think you'll find it's just a display issue - see https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x

There are instructions in there. @greenph1 that post also tells you how to open the error console, which may reveal your loading issue.

Either way, this is a plugin conflict and not something reproducible on a clean install. Let us know how you get on.

**Comment by melcarthus** [comment]
No there are no errors in my console. Newly added attributes display just fine. After an update all the product attributes are gone. The database woocommerce_taxonomy_terms? is also completely empty now.. I wish I could reproduce this problem but the client manages his own site and I don't know with which update it went wrong.

**Comment by mikejolley** [comment]
@melcarthus "woocommerce_taxonomy_terms" <-- we have no such table. https://github.com/woocommerce/woocommerce/wiki/Database-Description

**Comment by melcarthus** [comment]
Correct

I typed out of memory

I looked it up it's this table

wp_woocommerce_attribute_taxonomies

**Comment by mikejolley** [comment]
The only way this would be empty would be on 'deleting' WooCommerce. I've seen some people do upgrades by deleting WC then uploading the new version, but this is dangerous because 'delete' is equivalent to uninstall.

**Comment by greenph1** [comment]
Unfortunately I do not understand all this code, I'm not a developer just a simple Woocommerce user. Are you able to see the plugin conflict?

Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.min.js:21)
    at Function.each (load-scripts.php:2)
    at d.prepareOpts (select2.min.js:21)
    at d.prepareOpts (select2.min.js:22)
    at d.init (select2.min.js:21)
    at HTMLSelectElement.<anonymous> (select2.min.js:22)
    at Function.each (load-scripts.php:2)
    at a.fn.init.each (load-scripts.php:2)
    at a.fn.init.a.fn.select2 (select2.min.js:22)
    at HTMLSelectElement.<anonymous> (wc-enhanced-select.min.js:1)

**Comment by greenph1** [comment]
JQMIGRATE: Migrate is installed, version 1.4.1
wc-enhanced-select.min.js:1 Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.min.js:21)
    at Function.each (load-scripts.php:2)
    at d.prepareOpts (select2.min.js:21)
    at d.prepareOpts (select2.min.js:22)
    at d.init (select2.min.js:21)
    at HTMLSelectElement.<anonymous> (select2.min.js:22)
    at Function.each (load-scripts.php:2)
    at a.fn.init.each (load-scripts.php:2)
    at a.fn.init.a.fn.select2 (select2.min.js:22)
    at HTMLSelectElement.<anonymous> (wc-enhanced-select.min.js:1)

**Comment by mikejolley** [comment]
@greenph1 https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x view the source.

**Comment by melcarthus** [comment]
Wel my table that houses the data is empty so this issue is not about the select2 options. New product can't be creatie as variable because there are no attributes to use. 

Update issue or my client did delete everything without knowing it. :) this thread can be closed.

**Comment by greenph1** [comment]
It seems to indicate it has something to do with Advanced Custom Fields Pro. I have tried to deactivate and then delete, but it won't let. 

This is really frustrating as it means I cannot use the Variation ability.

**Comment by mikejolley** [comment]
@melcarthus I'd make sure they know how to do updates without using the 'delete' button in admin.

**Comment by greenph1** [comment]
Mike. I followed your instructions, used the Chrome developer to find the issue. It seems it is a plugin I guess, but I have deactivated all plugins and the issue still persists. I think the plugin is bundled with Woocommerce. As I said I am not a coder, developer, so this all looks alien to me and very frustrating. Can you give me any advice on how I can fix this??

**Comment by mikejolley** [comment]
What was the error?

**Comment by greenph1** [comment]
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:9 JQMIGRATE: Migrate is installed, version 1.4.1
wc-enhanced-select.min.js:1 Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.min.js:21)
    at Function.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2)
    at d.prepareOpts (select2.min.js:21)
    at d.prepareOpts (select2.min.js:22)
    at d.init (select2.min.js:21)
    at HTMLSelectElement.<anonymous> (select2.min.js:22)
    at Function.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2)
    at a.fn.init.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2)
    at a.fn.init.a.fn.select2 (select2.min.js:22)
    at HTMLSelectElement.<anonymous> (wc-enhanced-select.min.js:1)
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2 Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.min.js:21)
    at Function.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2)
    at d.prepareOpts (select2.min.js:21)
    at d.prepareOpts (select2.min.js:22)
    at d.init (select2.min.js:21)
    at HTMLSelectElement.<anonymous> (select2.min.js:22)
    at Function.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2)
    at a.fn.init.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2)
    at a.fn.init.a.fn.select2 (select2.min.js:22)
    at HTMLSelectElement.<anonymous> (wc-enhanced-select.min.js:1)
(anonymous) @ select2.min.js:21
each @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
prepareOpts @ select2.min.js:21
prepareOpts @ select2.min.js:22
init @ select2.min.js:21
(anonymous) @ select2.min.js:22
each @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
each @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
a.fn.select2 @ select2.min.js:22
(anonymous) @ wc-enhanced-select.min.js:1
each @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
each @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
(anonymous) @ wc-enhanced-select.min.js:1
dispatch @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
r.handle @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
trigger @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
a.event.trigger @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:9
(anonymous) @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
each @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
each @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
trigger @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
variations_loaded @ meta-boxes-product-variation.min.js:1
dispatch @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
r.handle @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
trigger @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
a.event.trigger @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:9
(anonymous) @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
each @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
each @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
trigger @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:3
success @ meta-boxes-product-variation.min.js:1
i @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
fireWith @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2
y @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:4
c @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:4

**Comment by mikejolley** [comment]
Look at https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x

**Comment by greenph1** [comment]
I have, but I cannot deactivate the Advanced Custom Fields Pro plugin. There is no that lets me do this.

**Comment by greenph1** [comment]
![acfp](https://cloud.githubusercontent.com/assets/27953510/25392605/f58900ac-29d0-11e7-81f2-fbbdd98066fb.jpeg)
I cannot deactivate this plugin unlike the others

**Comment by mikejolley** [comment]
cc @elliotcondon

**Comment by elliotcondon** [comment]
Hi @greenph1 - can you please update ACF PRO to the latest version (5.5.12). 
I have made many improvements since v5.3.4 including better select2 v4 support.

**Comment by greenph1** [comment]
Hi @elliotcondon. Could you possibly explain how I do this update? Is there a step by step procedure? I really am a novice here. Plus I cannot see how you can do this within Wordpress as it only says Edit on the Plugin.

**Comment by elliotcondon** [comment]
Hi @greenph1 

Updating ACF PRO is like any other plugin. Your screenshot shows the ACF PRO plugin is unable to be deactivated which suggests some custom code at play.

Can you see the menu item 'Custom Fields -> Updates'?
Did you purchase an ACF PRO license, or has ACF PRO been provided to you in another way?

Thanks
Elliot

**Comment by greenph1** [comment]
Hi @elliotcondon,

I'm afraid I cannot see 'Custom Fields -> Updates'.  Attached is a file of what I can see once I hit Edit.
![screengrab](https://cloud.githubusercontent.com/assets/27953510/25520776/1dbe0c7c-2bf5-11e7-9002-1cfe7b1ef91d.jpeg)


I didn't buy the ACF Pro license directly, I believe it came bundled with the Theme I purchased.

Kind Regards,

David

**Comment by mikejolley** [comment]
If it's bundled you better go moan to the theme author because that sounds very underhanded :)

**Comment by elliotcondon** [comment]
Hi @greenph1 - I'm a bit confused why you are looking in the 'Plugins -> Editor' menu page. If you can't see the 'Custom Fields' menu item, it is most likely your theme contains some code that has hidden it from you. Please contact your theme developer for help with your issue
