### ISSUE TITLE
Table Rate Shipping v2.9.2 causes http500 w/ WC3.0.0

### ISSUE THREAD

**Issue by TimMarshAU** [woocommerce/woocommerce#14635]
### EXPLANATION OF THE ISSUE

Upgrading to WC3.0.0 causes an http500.

### STEPS TO REPRODUCE THE ISSUE

Upgrade WC to WC3.0.0 on WP4.7.4.

HTTP500 Internal Server Error.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.velonomad.com
Site URL: http://www.velonomad.com/vni
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔  3 active Zapier Feeds.
Zapier Integration - Cron Tasks: ✔  0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔  Order to buyers list
Zapier Feed #1 Webhook URL: ✔  https://zapier.com/hooks/catch/ojnecu/
Zapier Feed #1 Trigger: ✔  New Order
Zapier Feed #1 Test Result: ✔  Successfully sent sample data to https://zapier.com/hooks/catch/ojnecu/.
Zapier Feed #2 Name: ✔  WC->AC: New Order - SKU lines
Zapier Feed #2 Webhook URL: ✔  https://zapier.com/hooks/catch/oj7pk7/
Zapier Feed #2 Trigger: ✔  New Order
Zapier Feed #2 Test Result: ✔  Successfully sent sample data to https://zapier.com/hooks/catch/oj7pk7/.
Zapier Feed #3 Name: ✔  Woocommerce-Freshdesk
Zapier Feed #3 Webhook URL: ✔  https://zapier.com/hooks/catch/lte1u/
Zapier Feed #3 Trigger: ✔  New Order
Zapier Feed #3 Test Result: ✔  Successfully sent sample data to https://zapier.com/hooks/catch/lte1u/.

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: ce2syyjf_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (41) ###

Gravity Forms: by rocketgenius – 1.9.19
Amazon Affiliate Link Globalizer: by Attila Gyoerkoes
Markus Goetz (Woboq) – 1.3

WP Offload S3: by Delicious Brains – 1.2.2
WP Offload S3 - WooCommerce Addon: by Delicious Brains – 1.0.5
Amazon Web Services: by Delicious Brains – 1.0
Custom Sidebars: by WPMU DEV – 2.1.1.1
Force SSL URL Scheme: by WebAware – 1.0.0
Redirection: by John Godley – 2.4.5
Simple URLs: by Nathan Rice – 0.9.6
SSL Insecure Content Fixer: by WebAware – 2.2.3
SumoMe: by SumoMe – 1.22
TablePress: by Tobias Bäthge – 1.7
WooCommerce Checkout Add-Ons: by WooThemes / SkyVerge – 1.7.1 – 1.10.2 is available
WooCommerce Checkout Field Editor: by WooThemes / Mike Jolley / Patrick Garman – 1.2.11 – 1.5.4 is available
WooCommerce Currency Converter: by WooThemes – 1.6.3 – 1.6.5 is available
WooCommerce Stripe Gateway: by WooCommerce – 3.1.7
WooCommerce jQuery Cookie Fix: by Splashing Pixels (Roy Ho) – 1.0
WooCommerce Product Add-ons: by WooThemes – 2.7.10 – 2.8.1 is available
WooCommerce Australia Post: by WooThemes – 2.3.6 – 2.4.2 is available
WooCommerce Zapier Integration: by OM4 – 1.5 – 1.6.7 is available
WooCommerce: by Automattic – 3.0.4
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO Premium: by Team Yoast – 3.8
WP Review Pro: by MyThemesShop – 1.0.9
Wufoo Shortcode Plugin: by Chris Coyier / Wufoo – 1.43

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #9996 - /shop/
Cart: #9997 - /cart/
Checkout: #9998 - /checkout/
My account: #9999 - /my-account/

### Theme ###

Name: Velonomad
Version: 3.0
Author URL: https://kolakube.com/
Child Theme: ✔
Parent Theme Name: Marketers Delight
Parent Theme Version: 4.6.4
Parent Theme Author URL: https://kolakube.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
You're not using a compatible version: http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-table-rate-shipping/changelog.txt
