### ISSUE TITLE
Zoom for small images

### ISSUE THREAD

**Issue by hosein71** [woocommerce/woocommerce#14634]
Zoom will cause showing real size of image if image is smaller than gallery/slider area. So image will follow mouse on hover and it isn't good view for gallery.

Tested with WordPress 4.7.4, WooCommerce 3.0.4 and 2012 theme 2.2. No more plugins are activated.
![themes-cart](https://cloud.githubusercontent.com/assets/6560172/25327824/d6702b14-28ea-11e7-9084-b6cfdd03c877.png)

The small "Learn more" button is what i mean.

**Comment by mikejolley** [comment]
Zoom only enables itself if the image is larger than the gallery:

https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/single-product.js#L174-L184

I tested this with a small image and no hover-zoom was shown. Again, clean install, new product, no plugins but WC.

Either you're talking about something else (?), the script has been cached, or it's something else. There was no link to a test site so I cannot inspect the scripts + sizes in the markup.

If you can provide additional details to reproduce this comment back.

**Comment by hosein71** [comment]
I looked at the code before creating an issue.
There is samples that you can see a small image in gallery.
https://wp-persia.com/product/ship-your-idea-2/
https://wp-persia.com/product/woo-single-2/

Data is added from WooCommerce dummy data and then last image (the small one) is added to the gallery.

I know that is no cache (tested without cache and on other browser). Even I've checked the sizes using console.log() and everything was correct about image size.

**Comment by mikejolley** [comment]
Ok, so zoom is enabled because most images are large enough but one is not. Zoom cannot be conditionally disabled per image.

**Comment by hosein71** [comment]
I think it is better to check it per image. Could you mark it as an improvement? (Maybe i can help for code)
It can helps other developers to avoid possible issues about images in plugins and themes for WooCommerce.

**Comment by mikejolley** [comment]
I can mark it but as I said, I don't think the zoom library will support it.

**Comment by hosein71** [comment]
I did it for a custom usage by initiating the zoom function for each images but no idea about that **performance**. I can share my code for review or create a pull request after making changes in my fork.

**Comment by MasterK999** [comment]
This is a pretty nasty bug. If h71's fix to load the zoom for each image is not workable it would be nice to offer an option to disable zoom per product through a checkbox.
