### ISSUE TITLE
Add or Edit Product causes HTTP 500 Error

### ISSUE THREAD

**Issue by rbendit** [woocommerce/woocommerce#14642]
### EXPLANATION OF THE ISSUE

When using Woocommerce 3.0.4 with "WooCommerce Amazon Payments Advanced Gateway" Plugin add or edit a Product causes HTTP 500 Error. When deactivating the "WooCommerce Amazon Payments Advanced Gateway" Plugin there is no problem occuring.

### STEPS TO REPRODUCE THE ISSUE

When using Woocommerce 3.0.4 with "WooCommerce Amazon Payments Advanced Gateway" Plugin add or edit a Product causes HTTP 500 Error. When deactivating the "WooCommerce Amazon Payments Advanced Gateway" Plugin there is no problem occuring.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://dlbs.bendit.com
Site URL: https://dlbs.bendit.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 5.6.30-10+deb.sury.org~xenial+2
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wpdlbs_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (44) ###

Admin Menu Editor Pro: by Janis Elsts – 2.4.3
Contact Form 7: by Takayuki Miyoshi – 4.7
Loco Translate: by Tim Whitlock – 2.0.13
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Nginx Helper: by rtCamp – 1.9.10
WP Post Cloner: by Evan Herman
Ben Rothman – 0.1.1

Postman SMTP: by Jason Hendriks – 1.7.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.0
WooCommerce Stripe Gateway: by WooCommerce – 3.1.7
WooSidebars: by WooThemes – 1.4.3
YITH WooCommerce Wunschliste: by YITHEMES – 2.1.0
W3 Total Cache: by Frederick Townes – 0.9.5.2
Admin Menu Editor Pro: by Janis Elsts – 2.4.3
Contact Form 7: by Takayuki Miyoshi – 4.7
Loco Translate: by Tim Whitlock – 2.0.13
Multisite Language Switcher: by Dennis Ploetner – 1.1
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Postman SMTP: by Jason Hendriks – 1.7.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.0
WooCommerce Stripe Gateway: by WooCommerce – 3.1.7
WooSidebars: by WooThemes – 1.4.3
WP Post Cloner: by Evan Herman
Ben Rothman – 0.1.1

YITH WooCommerce Wunschliste: by YITHEMES – 2.1.0
Envato Market: by Derek Herman – 1.0.0-RC2
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Nginx Helper: by rtCamp – 1.9.10
Server IP & Memory Usage Display: by Apasionados
Apasionados del Marketing – 1.4.0

Sofort payment gateway: by Awesome UG – 1.1.19
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout Fernhout – 2.1.12
WP Performance & Security: by JMR.codes – 0.7.3
FooEvents for WooCommerce: by Grenade – 1.3.0
FooEvents PDF Tickets: by Grenade – 1.2.0
FooEvents Express Check-in: by Grenade – 1.0.7
WooCommerce: by Automattic – 3.0.4
FooEvents Custom Attendee Fields: by Grenade – 1.0.1
FooEvents Calendar: by Grenade – 1.0.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #415 - /ju-52-rund-und-streckenfluege/
Cart: #62 - /cart/
Checkout: #61 - /checkout/
My account: #60 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.4
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
</details>

**Comment by vic3636** [comment]
Same problem!!

**Comment by mikejolley** [comment]
No mention of "WooCommerce Amazon Payments Advanced Gateway" version?

**Comment by vic3636** [comment]
I'm using Mercadopago payment Gateway 2.2.1 version. Probably both are not compatible yet. I don't use another payment plugin. I need to make it work.  What do you suggest?

**Comment by mikejolley** [comment]
@vic3636 Asking the developer. And this is not the 'same problem' because the OP is using amazon.

@rbendit what version of Amazon.

**Comment by rbendit** [comment]
"WooCommerce Amazon Payments Advanced Gateway" Version 1.6.4

**Comment by rbendit** [comment]
Something happened after updating to Woocommerce 3.0.4: after the update there is shown a button to update the database! After klicking this database-update Button the problem occured

**Comment by mikejolley** [comment]
You're not on the compatible version https://github.com/woocommerce/woocommerce-gateway-amazon-payments-advanced/blob/master/changelog.txt

There is a 1.7.

**Comment by rbendit** [comment]
Here the (debug > true) error message:

Fatal error: Uncaught exception 'Exception' with message 'Invalid order.' in /var/www/dlbs.bendit.com/htdocs/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:86 Stack trace: #0 /var/www/dlbs.bendit.com/htdocs/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(143): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order)) #1 /var/www/dlbs.bendit.com/htdocs/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(109): WC_Data_Store->read(Object(WC_Order)) #2 /var/www/dlbs.bendit.com/htdocs/wp-content/plugins/woocommerce-gateway-amazon-payments-advanced/includes/class-wc-amazon-payments-advanced-order-admin.php(136): WC_Abstract_Order->__construct(921) #3 [internal function]: WC_Amazon_Payments_Advanced_Order_Admin->meta_box('product') #4 /var/www/dlbs.bendit.com/htdocs/wp-includes/class-wp-hook.php(300): call_user_func_array(Array, Array) #5 /var/www/dlbs.bendit.com/htdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #6 /var/www/dl in /var/www/dlbs.bendit.com/htdocs/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 86

**Comment by rbendit** [comment]
ok, it seems my Version of Amazon Pay is not the actual one. But this Plugin semms not to show when an update is available... :-(

**Comment by photoncreative** [comment]
I actually had this same issue today with the "WooCommerce PDF Invoice" plugin. All other plugins and WP are latest build. 3.0.7. Deactivating it fixed the problem.

**Comment by flacnvinyl** [comment]
We are having the same issue.  Debug generates nothing helpful.  Disabling the plugin allows us to edit pages/posts/etc, enabling it locks up editing.  Updating various plugins made zero impact.  Seems like the developers are refusing to patch?

**Comment by claudiosanches** [comment]
@flacnvinyl contact the developers of the plugins that are stopping it to work.

**Comment by flacnvinyl** [comment]
they JUST patched it.  latest version resolves the issues.  woot!

**Comment by cbracco** [comment]
@flacnvinyl can you please post a link to where we can get the updated version?

**Comment by zakirsajib** [comment]
Got same issue!

**Comment by zakirsajib** [comment]
updated to 1.8.1 from 1.6.8. now  its fixed.
