### ISSUE TITLE
SKU must be unique for variation

### ISSUE THREAD

**Issue by Daaaaad** [woocommerce/woocommerce#14643]
Hello,

I'm using WooCommerce with variations and I discovered that SKU must be unique for each variation. That's a problem because when using WooCommerce with LocoTranslate (to translate product pages in several languages) the product is duplicated and we should be able to set the same SKU for multiple variations 😔

Do you have an idea of how I could bypass this limitation ?

Thank you 😀

David.

**Comment by mikejolley** [comment]
This would need to be handled by a translation plugin - you could add a suffix, but you have larger problems if managing stock because each 'product' translation would have it's own stock! This is not something core handles for you.
