### ISSUE TITLE
WooCommerce & Bookings 404 Page Not found Errors

### ISSUE THREAD

**Issue by bmalott01** [woocommerce/woocommerce#14649]
### EXPLANATION OF THE ISSUE

WooCommerce Version 3.0.4
WooCommerce Bookings 1.10.01

I get a 404 page not found error when clicking on the below links.
http://kinmanfarm.com/wp-admin/edit.php?post_type=shop_order
http://kinmanfarm.com/wp-admin/edit.php?post_status=wc-cancelled&post_type=shop_order
http://kinmanfarm.com/wp-admin/edit.php?post_type=wc_booking

But these links work.
http://kinmanfarm.com/wp-admin/edit.php?post_status=wc-processing&post_type=shop_order
http://kinmanfarm.com/wp-admin/edit.php?post_status=wc-pending&post_type=shop_order
http://kinmanfarm.com/wp-admin/edit.php?post_status=wc-completed&post_type=shop_order

I’ve tried, flushing the permalinks, deactivating plugins – turning them on one-by-one, changing themes. 

### STEPS TO REPRODUCE THE ISSUE

I made the update to 3.0 > was testing bookings > adding / deleting orders > then started receiving the error. Updated to most recent version of WooCommerce & Bookings, but still get the Page Not Found Error.

### SYSTEM STATUS

WordPress environment
Home URL:		http://kinmanfarm.com
Site URL:		http://kinmanfarm.com
WC version:		3.0.4
Log directory writable:		 /home/kinmanfarm/public_html/wp-content/uploads/wc-logs/
WP version:		4.7.4
WP multisite:		–
WP memory limit:		512 MB
WP debug mode:		–
WP cron:		
Language:		en_US
Server environment
Server info:		Apache/2.4.25
PHP version:		5.6.30
PHP post max size:		128 MB
PHP time limit:		300
PHP max input vars:		1000
cURL version:		7.36.0, OpenSSL/1.0.1e
SUHOSIN installed:		–
MySQL version:		5.6.33
Max upload size:		128 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.4
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 /home/kinmanfarm/public_html/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (19)
Contact Form 7	 	by Takayuki Miyoshi – 4.7
Contact Widgets	 	by GoDaddy – 1.4.1
Coupon Creator	 	by Brian Jessee – 2.4
Custom Facebook Feed	 	by Smash Balloon – 2.4.5
Goodlayers Conference	 	by Goodlayers – 1.0.0
Goodlayers Portflio Post Type	 	by Goodlayers – 1.0.0
Goodlayers Shortcode	 	by Goodlayers – 1.0
GoDaddy Email Marketing	 	by GoDaddy – 1.2.0
Goodlayers Importer	 	by Goodlayers – 1.0.0
Hello Dolly	 	by Matt Mullenweg – 1.6
Limit Login Attempts	 	by Johan Eenfeldt – 1.7.1
Master Slider Pro	 	by averta – 2.25.4
Newsletter	 	by Stefano Lissa & The Newsletter Team – 4.8.9
Ninja Forms	 	by The WP Ninjas – 3.0.34
Simple Custom CSS	 	by John Regan, Danny Van Kooten – 3.3
WooCommerce Bookings	 	by Automattic – 1.10.1
WooCommerce	 	by Automattic – 3.0.4
WordPress Importer	 	by wordpressdotorg – 0.6.3
WP Google Map Plugin	 	by flippercode – 3.2.0
Settings
API enabled:		
Force SSL:		–
Currency		USD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		booking (booking), external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#4272 - /shop/
Cart:		#4273 - /cart/
Checkout:		#4274 - /checkout/
My account:		#4275 - /my-account/
Theme
Name:		The Keynote
Version:		2.01
Author URL:		http://www.goodlayers.com
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Archive template:	 	Your theme has a woocommerce.php file, you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides:	 	–

**Comment by mikejolley** [comment]
I remember this from https://wordpress.org/support/topic/page-not-found-404-error-3/

As I said, you need to use the customer helpdesk ---> https://woocommerce.com/my-account/tickets/

They will likely need access; you cannot share credentials on Github.
