### ISSUE TITLE
Fatal error deleting coupon

### ISSUE THREAD

**Issue by marcoweening** [woocommerce/woocommerce#14641]
### EXPLANATION OF THE ISSUE

I can create coupons, but not bin them. I get a fatal error.

Fatal error: Uncaught exception 'Exception' with message 'Invalid order.' in /home/nickwilm/public_html/store/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:86 Stack trace: #0 /home/nickwilm/public_html/store/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(143): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order)) #1 /home/nickwilm/public_html/store/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(109): WC_Data_Store->read(Object(WC_Order)) #2 /home/nickwilm/public_html/store/wp-content/plugins/woocommerce-pre-orders/includes/class-wc-pre-orders-order.php(389): WC_Abstract_Order->__construct(285) #3 [internal function]: WC_Pre_Orders_Order->maybe_cancel_trashed_pre_order(285) #4 /home/nickwilm/public_html/store/wp-includes/class-wp-hook.php(298): call_user_func_array(Array, Array) #5 /home/nickwilm/public_html/store/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #6 /home/nickwilm/public_html/store/wp-includes/plugin in /home/nickwilm/public_html/store/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 86

### STEPS TO REPRODUCE THE ISSUE

I have URL Coupons installed. But even when I disable that, it does not work.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://store.kingsarms.org
Site URL: http://store.kingsarms.org
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wpkastore_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (14) ###

ManageWP - Worker: by ManageWP – 4.2.18
iThemes Security: by iThemes – 6.2.1
Code Snippets: by Shea Bunge – 2.8.2
Cookie Law Info: by Richard Ashby – 1.5.3
WooCommerce Table Rate Shipping by Mangohour: by mangohour – 1.2.1
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.4
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.5
WooCommerce Conversion Tracking: by Tareq Hasan – 1.2.2
WooCommerce Stripe Gateway: by WooCommerce – 3.1.7
WooCommerce MailChimp: by Saint Systems – 2.0.20
WooCommerce Pre-Orders: by WooThemes – 1.4.4 – 1.4.10 is available
WooCommerce URL Coupons: by SkyVerge – 2.5.0
WooCommerce: by Automattic – 3.0.4
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Uno
Version: 1.0.4
Author URL: http://www.woothemes.com
Child Theme: ✔
Parent Theme Name: Canvas
Parent Theme Version: 5.11.4
Parent Theme Author URL: http://www.woothemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
The error message comes from pre-orders:

> WooCommerce Pre-Orders: by WooThemes – 1.4.4 – 1.4.10 is available

Which is not up to date.
