### ISSUE TITLE
Allow forward slash in is_phone()

### ISSUE THREAD

**Issue by freeaanzee** [woocommerce/woocommerce#14646]
Could a forward slash be added to [WC_Validation->is_phone()](https://github.com/woocommerce/woocommerce/blob/7b2be1d62fe05475c3172c34d164390229cb0fbf/includes/class-wc-validation.php#L35)? This is a very common phone notation in Belgium, but it currently blocks order checkout in WooCommerce.

![screenshot](https://www.fairtradecrafts.be/wp-content/screens/is-phone-forward-slash.png)

Of course, we can format it away ourselves through the 'woocommerce_process_checkout_field_'-filters, so no biggie. But it might be counterintuitive for regular users.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14651
