### ISSUE TITLE
Missing the product name in the orders list

### ISSUE THREAD

**Issue by voorhammr** [woocommerce/woocommerce#14654]
Hi,

After updating to version 3.0.3 we are missing the product name in the orders list on the admin side?

Any idea how to get this back, because our webshop admin now need to open every order now to see which products are bought.

Kind regards,
Robin

**Comment by mojo2405** [comment]
they removed it as it was a bad bottle neck - removing it made better performance.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14121
