### ISSUE TITLE
searching an order sometimes shows only name of the buyer without family name

### ISSUE THREAD

**Issue by mojo2405** [woocommerce/woocommerce#14658]
### EXPLANATION OF THE ISSUE
happens after migrating from woocommerce 2.6 to 3.04 .
sometimes when searching an order - the search results shows only first name of the buyer without his last name - expecting to get both. need to say - it only happens sometimes.

### STEPS TO REPRODUCE THE ISSUE

go to orders page -> search for user by his name -> only first names appear (sometimes) and in other times the search doesn't find any results at all ! strange..

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.shaked-presents.com
Site URL: https://www.shaked-presents.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL

### Server Environment ###

Server Info: Apache/2.2.15 (CentOS)
PHP Version: 5.6.29
PHP Post Max Size: 12 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 12 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Invoice4u Meshulam Clearing: by Invoice4U – 1.3
Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.10
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Order Status for WooCommerce: by Algoritmika Ltd – 1.2.1
Duplicator: by Snap Creek – 1.2.4
Dynamic Featured Image: by Ankit Pokhrel – 3.5.2
Envato WordPress Toolkit: by Envato – 1.7.3
Export WooCommerce: by Algoritmika Ltd – 1.0.0
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Loco Translate: by Tim Whitlock – 2.0.13
Master Slider Pro: by averta – 2.26.0
Porto Content Types: by SW-THEMES – 1.3.1
Porto Shortcodes: by SW-THEMES – 1.6.6
Porto Widgets: by SW-THEMES – 1.3.1
WordPress Post Type Archive Links: by Stephen Harris – 1.3.1
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Woocommerce Order address Print: by Bhavik Patel – 3.0
WooCommerce TM Extra Product Options: by themecomplete – 4.5.2
WooCommerce Upload Files: by Lagudi Domenico – 19.8
WP All Import - WooCommerce Add-On: by Soflyy – 1.3.3
WooCommerce: by Automattic – 3.0.4
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.6
WP Accessibility: by Joe Dolson – 1.5.10
WP All Import: by Soflyy – 3.4.2
WP Google Maps: by WP Google Maps – 6.4.03
WP Mail Logging: by Christian Zöller – 1.8.0
WP-ServerInfo: by Lester 'GaMerZ' Chan – 1.64
WP Sitemap Page: by Tony Archambeau – 1.6
WP Super Cache: by Automattic – 1.4.9
WPS Hide Login: by Remy Perona for WPServeur – 1.1.7
MailPoet Newsletters: by MailPoet – 2.7.10
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.3.2
YITH WooCommerce Ajax Search: by YITHEMES – 1.5.2
Advanced Custom Fields: by Elliot Condon – 4.4.11

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: ILS (₪)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2471 - /shop-2/
Cart: #2562 - /cart-2/
Checkout: #3745 - /checkout-2/
My account: #3746 - /my-account-2/

### Theme ###

Name: Porto
Version: 3.6
Author URL: http://www.newsmartwave.net/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/content-product.php
porto/woocommerce/content-product_cat.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/order-details.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/external.php
porto/woocommerce/single-product/add-to-cart/grouped.php
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/share.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

`
</details>

**Comment by mikejolley** [comment]
Orders are displayed in the same way regardless of search or query type in the admin list. If a result appears to have missing data, look at the order itself. It will most likely be missing billing data, or the user object associated with the order has a different display name.
