### ISSUE TITLE
product_url was called incorrectly

### ISSUE THREAD

**Issue by ApplicationError** [woocommerce/woocommerce#14650]
I know this is a problem on my end. I've been looking for an answer, but haven't been able to find one. Was hoping someone can help me out. I get this... 

Notice: product_url was called incorrectly. Product properties should not be accessed directly.

And I assume that it means that this isn't the right way to do it:

$link = $product->product_url;

Can someone help out?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/CRUD-Objects-in-3.0

Make sure it's the correct type before calling it!

https://docs.woocommerce.com/wc-apidocs/source-class-WC_Product_External.html#45-53
