### ISSUE TITLE
Empty Item List in Admin Panel

### ISSUE THREAD

**Issue by gelinger777** [woocommerce/woocommerce#14655]
### EXPLANATION OF THE ISSUE

After successfull order , we want to view the items ordered by the user , go to Orders->Edit Order 
and see there no item listed in items. 

Also notification email holds no item information. 

What could be the reason?

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
A plugin could be interfering with the order creation process, or you're missing a database table. 

You didn't provide a status report so I cannot check the tables nor see what is being ran. You should disable plugins and do a test order to see if there is a conflict.
