### ISSUE TITLE
Fatal errors if parent_id === post_id for shop_order

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#14660]
### EXPLANATION OF THE ISSUE

It appears that [this bug](https://github.com/woocommerce/woocommerce-bookings/issues/1059) has been using the `ID` as the `parent_id` for `shop_order`s for quite some time. This went without issue until users started updating to WC 3.0, and then it started creating fatal errors.

```
[24-Apr-2017 19:33:06 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 130968 bytes) in .../wp-includes/post.php on line 640
```

Fatal errors are encountered if:

* Order is viewed directly
* Order is in the current page view
* Order is called for another reason, like viewing a booking or booking list

### STEPS TO REPRODUCE THE ISSUE

1. Edit your latest `shop_order` to have the `parent_id` as its own `ID`
1. View your order list
1. List will not display

### SYSTEM STATUS

<details>
```
WC Version: 3.0.4
WP Version: 4.7.4
```
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14687
