### ISSUE TITLE
Image slider and zoom not working

### ISSUE THREAD

**Issue by YannMic** [woocommerce/woocommerce#14661]
### EXPLANATION OF THE ISSUE

With Woocommerce 3.0.4, on the single product view, the slider and the zoom don't launch. Furthermore, the thumbnail of the current photo is missing.
Wordpress version: 4.7.4.
It only works with "base" templates like Tewenty Fifteen, Twenty Sixteen and TwenTy Seventeen. 
The bugs happends with any other compatible template.

**Comment by claudiosanches** [comment]
>  The bugs happends with any other compatible template.

But that other compatible templates are declaring support for slider and zoom, like we are saying in https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox)-in-3.0.0 ?

**Comment by mikejolley** [comment]
Support needs to be defined, this is not a bug. Update the theme.

**Comment by YannMic** [comment]
Ok, I added the support in the functions.php file. It solved my problem. Actually, this is not a bug.
Thank you for your response and the link.
