### ISSUE TITLE
Category visibility / product count wrong

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/woocommerce#14662]
### EXPLANATION OF THE ISSUE

A product is setup with «Catalog visibility: Search» and belongs to a category named «Category 2», this is the only product in the category. The shop page display is set to «Show categories».

Category 2 will be shown with count 1, clicking on the category will result in a empty display with the message «No products were found matching your selection.» 

### STEPS TO REPRODUCE THE ISSUE

1. setup a category
2. setup a product with catalog visibility: Search, assing to the category from step 1
3. The shop page display is set to «Show categories».

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://eval.firewoodshop.ch
Site URL: https://eval.firewoodshop.ch
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 5.6.30
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: fws_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CHF (CHF)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /warenkorb/
Checkout: #7 - /kasse/
My account: #8 - /mein-konto/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by SiR-DanieL** [comment]
The same happens when products on a category are out of stock:

![](http://cld.wthms.co/1hNl+)
**Image Link**: http://cld.wthms.co/1hNl+

The category Music says 6 products, but all of them are out of stock:

![](http://cld.wthms.co/G3Rl+)
**Image Link**: http://cld.wthms.co/G3Rl+

The store is set to hide out of stock products.

Reproduced locally.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14681
