### ISSUE TITLE
product image and gallery not working in quick view fancybox popup

### ISSUE THREAD

**Issue by presslayouts** [woocommerce/woocommerce#14668]
When i click on quick view button, after display completed product in fancybox but not display product image and product image gallery. Why? I think product gallery and image js loading problem.

So please give me hint for load product image and gallery js in fancybox popup ASAP.

This is my critical issue, So please give me reply ASAP. And we have sent this query in WordPress support request but not received any answer.

Thank you in advance!!!

**Comment by mikejolley** [comment]
On the callback after the fancybox has loaded you'd need to call the gallery function (assuming it's enqueued) to render it:

https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/single-product.js#L285

Should be taken care of in Quick View.

**Comment by presslayouts** [comment]
Thank you for quick replied Mike.

But we are sorry, because when i add below code in after complete fucntion but display js conflict error message "TypeError: $(...).wc_product_gallery is not a function", So how can resolve it and work fine.

`onComplete : function() {
	$( '.woocommerce-product-gallery' ).each( function() {
		$( this ).wc_product_gallery();
	} );
} );`

Please help me how to use this code .

Thank you.

**Comment by mensmaximus** [comment]
@presslayouts did you try to load your script with 'wc-single-product' as a dependency? As @mikejolley wrote: assuming it's enqueued

**Comment by presslayouts** [comment]
Hello Michael,

Sorry, Actually we can't understand, what you say?

Please give me hint with code, We need this issue resolving asap. 

Thank you,
PressLayouts.

**Comment by mensmaximus** [comment]
wp_enqueue_script( 'your-script', '/path/to/your/script', array( 'jquery', 'wc-single-product' ) );

**Comment by presslayouts** [comment]
Hello Michael,

Thank you product image display completed in popup, but product image gallery, zoom and lightbox not working. Why? What is my mistck? 

Please give me hint for this problem.

Thank you,
PressLayouts.

**Comment by presslayouts** [comment]
Please give me reply ASAP.. We need fast solution

**Comment by mensmaximus** [comment]
@presslayouts github is for reporting bugs not for support. Please visit https://wordpress.org/support/plugin/woocommerce for support.

**Comment by presslayouts** [comment]
Sorry michael,

We have sent request before 5 days, but no any reply.
https://wordpress.org/support/topic/product-image-and-gallery-not-working-in-quick-view-fancybox/

Why?

Please help me you !!!
