### ISSUE TITLE
Grouped Products Menu Order Issue

### ISSUE THREAD

**Issue by fragglefusion** [woocommerce/woocommerce#14665]
### EXPLANATION OF THE ISSUE

Before upgrading (I believe I was on 2.6) I had previously set the menu order of my child items on grouped products. After the upgrade to 3.04 I can see the menu orders are still there on each child product however each grouped product is not showing the child products in the correct orders on the actual shop page.

How can I fix this?

It does not appear to be a cache issue, I have removed cache plugins, cleared WC Transients an Expired Transients.

Thanks

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Ideally, we'd allow a custom sort order per grouped product: https://github.com/woocommerce/woocommerce/issues/14560

But we can restore for now.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14676
