### ISSUE TITLE
Old order totals wrong due to shipping tax not being calculated

### ISSUE THREAD

**Issue by nuclearape** [woocommerce/woocommerce#14674]
### EXPLANATION OF THE ISSUE

Our shipping is taxable. When we look at orders made prior to the update the total price (in admin) is displaying wrong because the tax for the shipping hasn't been calculated. The only way to get the correct price is to recalculate the total. 

**We would have to manually open every order and subscription & recalculate the total to get our store back correctly!**

### STEPS TO REPRODUCE THE ISSUE

1. View an order (made prior to WC 3.0) with a (taxable) shipping line added to it.
2. Notice the total price is wrong as the tax hasn't been calculated.
3. Fix the total by recalculating it.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://dev.chucklinggoat.co.uk
Site URL: https://dev.chucklinggoat.co.uk
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

### WC Pages ###

Shop base: #90 - /shop/
Cart: #91 - /shop/cart/
Checkout: #92 - /shop/checkout/
My account: #93 - /shop/my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
@nuclearape "Notice the total price is wrong as the tax hasn't been calculated.". Totals are static. If the stored total is wrong, that cannot be changed - it was correct at the time of calculation.

**Comment by nuclearape** [comment]
@mikejolley I thought that at first - so I went to the payment gateway to see how much was actually taken and can see that the correct amount (including the tax) was taken. 

When you recalculate the total the order then matches the amount originally taken.

**Comment by mikejolley** [comment]
Screenshot me what you're seeing?

**Comment by nuclearape** [comment]
Before recalculating:
![before-recalculating](https://cloud.githubusercontent.com/assets/6885015/25382716/c68f1e6e-29b0-11e7-8e8e-6feccc1299ad.png)

After recalculating:
![after-recalculating](https://cloud.githubusercontent.com/assets/6885015/25382724/cf6991fe-29b0-11e7-8dc6-3dd6a0bd4746.png)

**Comment by nuclearape** [comment]
@mikejolley this is a different issue to #14675 btw.

This is regarding existing orders total displaying wrong. #14675 is regarding entering new orders with mixed taxable and non-taxable products

**Comment by mikejolley** [comment]
Show your status report so I can see what is running. I mentioned the order total is static, so I don't understand how downgrading would make a difference _unless a plugin is changing the total on display._

**Comment by nuclearape** [comment]
@mikejolley I've pasted the system status in the original post - I'll paste it below as well. 

I am testing on the Twenty Seventeen theme and the only plugin active is WooCommerce - both of which are up to date.

To clarify the problem - the total for existing orders that have been paid for is displaying wrong. You need to manually re-calculate the total to get the invoice correct again.

` ### WordPress Environment ###
Home URL: https://dev.chucklinggoat.co.uk
Site URL: https://dev.chucklinggoat.co.uk
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

Server Environment

Server Info: Apache/2.4.25 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

Database

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

Security

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

Active Plugins (1)

WooCommerce: by Automattic – 3.0.4

Settings

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

WC Pages

Shop base: #90 - /shop/
Cart: #91 - /shop/cart/
Checkout: #92 - /shop/checkout/
My account: #93 - /shop/my-account/

Theme

Name: Twenty Seventeen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

Templates

Overrides: –
`

**Comment by mikejolley** [comment]
I edited my reply ^

**Comment by mikejolley** [comment]
@nuclearape See here https://github.com/woocommerce/woocommerce/blob/0b60af0774d998ce949c7eb71257b2a91bc7c370/includes/data-stores/abstract-wc-order-data-store-cpt.php#L221

Order total is pulled from post meta. it's not changed. Look at the postmeta table, '_order_total' meta_key and see if it matches that is output.

If that value is wrong, but the gateway took a different amount, either the gateway changed the amount before taking payment, or the order has been modified.

**Comment by nuclearape** [comment]
@mikejolley Maybe these screen shots will help explain my issue better:

1. This is the original order - **before updating to 3.0**
![before](https://cloud.githubusercontent.com/assets/6885015/25429041/91d5887e-2a6f-11e7-8a7f-d5941a4d1355.png)

2. This is the same order after updating to 3.0 and refreshing the screen - **notice the tax is missing from the shipping row but the total is still correct.**
![after](https://cloud.githubusercontent.com/assets/6885015/25429051/9a7ab9ea-2a6f-11e7-893c-3dc1d73fbe0e.png)

3. This is that same order after **only** changing the order status - **notice the total line has now changed!**
![status-change](https://cloud.githubusercontent.com/assets/6885015/25429100/caa50882-2a6f-11e7-9af4-bdf972a4630b.png)

We need to be able to change the status of our orders without the total line getting messed up! We have orders in "processing" status that need to move to "labelling" etc.

We also need the shipping tax to stay on the invoice so it doesn't confuse customers.

Is there anything else you'd like me to provide to help get this sorted? Or am I being a muppet and missing something?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14716
