### ISSUE TITLE
WooCommerce 3.0.4: Fatal error: Call to undefined method WC_Customer::get_address()

### ISSUE THREAD

**Issue by Innivo** [woocommerce/woocommerce#14679]
### EXPLANATION OF THE ISSUE

Running Wordpress 4.7.4, WooCommerce 3.0.4 update breaks the woocommerce review order page when being directed from Paypal Express checkout. The customer address area shows:
Fatal error: Call to undefined method WC_Customer::get_address() in /home/allisport/public_html/wp-content/plugins/paypal-for-woocommerce/template/paypal-review-order.php on line 105
Rolling back to WooCommerce 3.0.3 fixes the issue.

### STEPS TO REPRODUCE THE ISSUE

1. Click on 'Checkout with Paypal Express' from the cart or checkout
2. On the Paypal checkout page, log in, and then click continue
3. When redirected back to the WooCommerce site, the customer address has the error above
Note: If you have already logged in to Paypal, it seems fine. THE ERROR ONLY SHOWS AFTER YOU HAVE HAD TO LOG IN ON THE PAYPAL CHECKOUT

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.allisport.com
Site URL: https://www.allisport.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 300 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 50 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

LayerSlider WP: by Kreatura Media – 5.1.1
Advanced Custom Fields: by Elliot Condon – 4.4.11
Allow Shortcode in Text Widgets: by Travis Pflanz – 1.0
Antispam Bee: by pluginkollektiv – 2.7.1
Admin Columns: by AdminColumns.com – 2.5.6.4
Collapsing Categories: by Robert Felty – 2.0.8
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.9
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Field Bulk Editor: by SparkWeb Interactive
Inc. – 1.9.1

Customizer Export/Import: by The Beaver Builder Team – 0.6
Divi Booster: by Dan Mossop – 2.4.3
Divi Builder: by Elegant Themes – 2.0.3
Duplicator: by Snap Creek – 1.2.4
Envato WordPress Toolkit: by Envato – 1.7.3
EWWW Image Optimizer: by Shane Bishop – 3.3.0
Flow-Flow: by Looks Awesome – 3.0.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.7
Members: by Justin Tadlock – 1.1.3
WooCommerce Table Rate Shipping Plus: by mangohour – 1.9.2
No Page Comment: by Seth Alling – 1.2
Password Protected: by Ben Huson – 2.0.3
PayPal for WooCommerce: by Angell EYE – 1.3.3
Product Brands For WooCommerce: by Varun Sridharan – 0.7
PRyC WP/WooCommerce: Product search in any search: by PRyC – 1.0.8
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Relevanssi: by Mikko Saari – 3.5.8
Search & Replace: by Inpsyde GmbH – 3.1.2
searchIQ: by searchiq – 1.5.2
Shortcode Widget: by Gagan Deep Singh – 1.2
SSL Insecure Content Fixer: by WebAware – 2.2.3
Stripe WooCommerce Addon: by Syed Nazrul Hassan – 1.0.8
Widget or Sidebar Shortcode: by Frank Staude – 0.6.1
WooCommerce Advanced Review Reminder: by kodemann.com – 2.0
WooCommerce collapsing categories: by subhansanjaya – 0.0.1
WooCommerce EU VAT Number: by WooCommerce – 2.2.0
WooCommerce AdWords Conversion Tracking: by Wolf+Bär GmbH – 1.3.5
Import from eBay to WooCommerce: by WP Lab – 1.5.12
WooCommerce Sales MIS Report: by Infosoft Consultant – 2.1
WooCommerce Order Status Control: by SkyVerge – 1.8.0
WooCommerce Google Product Feed: by Lee Willis – 7.0.7
WooCommerce - Store Toolkit: by Visser Labs – 1.7.1
WooCommerce Wholesale Order Form: by Rymera Web Co – 1.6.6
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.14.4
WooCommerce Wholesale Prices: by Rymera Web Co – 1.4.5
WooCommerce: by Automattic – 3.0.4
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.3.6
Yoast SEO: by Team Yoast – 4.6
WP Database Backup: by Prashant Walke – 4.3.7
WP Fastest Cache: by Emre Vona – 0.8.6.8
WP-Invoice: by Usability Dynamics
Inc. – 4.1.7

WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

YITH WooCommerce Waiting List Premium: by YITHEMES – 1.1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3501 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Divi Child
Version: 2.7.6
Author URL: http://www.innivo.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.40
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
Divi-child/product-searchform.php version - is out of date. The core version is 2.5.0
Divi-child/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0

Outdated Templates: ❌Learn how to update

### Templates ###

thumbnail: 
medium: 
medium_large: 
large: 
et-pb-post-main-image: 
et-pb-post-main-image-fullwidth: 
et-pb-portfolio-image: 
et-pb-portfolio-module-image: 
et-pb-portfolio-image-single: 
et-pb-gallery-module-image-portrait: 
pbf_wc_small: 
pbf_wc_medium: 
pbf_wc_large: 
shop_thumbnail: 
shop_catalog: 
shop_single: 
`
</details>

**Comment by mikejolley** [comment]
@Innivo The error comes from a paypal plugin, not core which can be seen from the error path:

> Fatal error: Call to undefined method WC_Customer::get_address() in /home/allisport/public_html/wp-content/plugins/paypal-for-woocommerce/template/paypal-review-order.php on line 105

See here on that extension: https://github.com/angelleye/paypal-woocommerce/blob/release/template/paypal-review-order.php#L105

Looks like a method was removed/renamed without a BW compat method being added. This isn't related to 3.0.4, but 3.0.0 too.

I'll add a method back.

cc @angelleye

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14682

**Comment by angelleye** [comment]
We are just about to release our 1.4.0 update which will add full compatibility for WC 3.0.  We should have it released in just another day or two (hopefully).
