### ISSUE TITLE
Shipping classes do not work, unless shipping zone is saved

### ISSUE THREAD

**Issue by rellect** [woocommerce/woocommerce#14680]
### EXPLANATION OF THE ISSUE

Shipping classes do not work, unless shipping zone is saved.

### STEPS TO REPRODUCE THE ISSUE

1. Create shipping class
5. Create/edit a product and set the shipping class created
2. Create/edit a shipping zone and add a shipping method
4. Edit the method, and set a value in "shipping class cost" for the shipping class created earlier

Expected:
An additional cost for the shipping.

Result:
No change in shipping price.

I noticed that saving the shipping class resolves the problem.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://wp.wordpress.local
Site URL: http://wp.wordpress.local
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.20
PHP Version: 5.6.20
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.47.1
OpenSSL/1.0.2d

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (6) ###

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Woo Pelecard Gateway: by Ido Friedlander – 1.1.12
Woocommerce iCredit: by rivhit.co.il – 1.2.2
WooCommerce: by Automattic – 3.1.0-alpha
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1 – 1.2 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
1. Create shipping class named 'testing;
2. Assigned to product.
3. Rest of world zone
4. Add flat rate shipping. edit.
5. Set 'testing' price to 100. save

Went to cart and the shipping cost was $100. Appears to be fine..

**Comment by rellect** [comment]
There's an option to add additional cost based on shipping class.
Please set a value and see if it adds to the total shipping cost.

![image](https://cloud.githubusercontent.com/assets/2431842/25385344/6aa5a5b6-29cc-11e7-9c90-d401a668d2b2.png)

**Comment by mikejolley** [comment]
Yes, thats what I set to 100 :)

**Comment by rellect** [comment]
I'll try to test with master branch

**Comment by rellect** [comment]
@mikejolley in your tests, did you have a value in Cost field, or you left it 0 and only applied value in the shipping class?
Please check when both have values.

**Comment by mikejolley** [comment]
Tried both. First time I entered 1, 2nd time I left blank (0).

**Comment by rellect** [comment]
@mikejolley I verified the issue with updated master branch.

These are my settings
![image](https://cloud.githubusercontent.com/assets/2431842/25388207/d6aaecd6-29d5-11e7-933a-f9fec6c73db9.png)

And this is what I see in cart
![image](https://cloud.githubusercontent.com/assets/2431842/25388229/e5226578-29d5-11e7-9b02-777ebbc24b7f.png)

10 instead of 40.
Should mention that if I save the shipping zone (changing its name), it fixes it and then I see 40.
![image](https://cloud.githubusercontent.com/assets/2431842/25388264/0a05d80c-29d6-11e7-86ac-081239d69b4c.png)

**Comment by mikejolley** [comment]
Logged in or out? If you change cart contents does it also refresh?
