### ISSUE TITLE
Lightbox not working in version 3.0.4

### ISSUE THREAD

**Issue by rickvandeven** [woocommerce/woocommerce#14686]
### EXPLANATION OF THE ISSUE

Image gets opened as a new page, instead of in a lightbox (or the new advanced woocommerce 3.0 version of this)

### STEPS TO REPRODUCE THE ISSUE

Go to this link: https://www.saddlesonly.nl/product/prestige-d1-zadel/
Open a photo. 

### SYSTEM STATUS

<details>
WordPress omgeving
Home-URL:		https://www.saddlesonly.nl
Site URL:		https://www.saddlesonly.nl
WC-versie:		3.0.4
Logmap beschrijfbaar:		 /var/www/saddlesonly.nl/www/web/wp-content/uploads/wc-logs/
WP-versie:		4.7.4
WP Multisite:		–
WP geheugenlimiet:		256 MB
WP debug-modus:		
WP Cron:		
Taal:		nl_NL
Serveromgeving
Serverinformatie:		Apache/2.4.10 (Debian)
PHP-versie:		5.6.24-0+deb8u1
PHP post max size:		64 MB
PHP time limit:		300
PHP max input vars:		1000
cURL Versie:		7.26.0, OpenSSL/1.0.1t
SUHOSIN geïnstalleerd:		–
MySQL-versie:		 5.5.53 - Wij adviseren een minimum MySQL-versie 5.6. Bekijk: WordPress vereisten
Max upload size:		64 MB
Standaard tijdzone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC-databaseversie:		3.0.4
Prefix database	 	abzx_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP Database:		 /var/www/saddlesonly.nl/www/web/wp-content/uploads/GeoIP.dat
Beveiliging
Beveiligde verbinding (HTTPS):		
Verberg fouten voor bezoekers		
Actieve plugins (42)
Adminimize	 	door Frank Bültge – 1.11.2
All In One WP Security	 	door Tips and Tricks HQ, Peter, Ruhul, Ivy – 4.2.7
AMP	 	door Automattic – 0.4.2
BJ Lazy Load	 	door Bjørn Johansen, Aron Tornberg, angrycreative – 1.0.8
Canonical Seo Wordpress Plugin	 	door Harsh Agrawal – 2.1
Capability Manager Enhanced	 	door Jordi Canals, Kevin Behrens – 1.5.7
Contact Form 7	 	door Takayuki Miyoshi – 4.7
Disqus Comment System	 	door Disqus – 2.87
Dokan (Lite) - Multi-vendor Marketplace	 	door Tareq Hasan – 2.6.0
Dokan (Pro) - Multi-vendor Marketplace	 	door weDevs – 2.6.0
Contacteer de verkoper over het product	 	door Tareq Hasan – 0.1
Dokan - Subscription	 	door weDevs – 1.1.4
Dokan Seller Verification	 	door weDevs – 1.2
Google Tag Manager for Wordpress	 	door Thomas Geiger – 1.6.1
FacetWP - WPML	 	door FacetWP, LLC – 1.2.1
FacetWP	 	door FacetWP, LLC – 2.8.4
Google Analytics Dashboard voor WP	 	door Alin Marcu – 4.9.6.2
Monarch Plugin	 	door Elegant Themes – 1.3.2
WPBakery Visual Composer	 	door Michael M - WPBakery.com – 4.11.2.1
MailChimp voor WordPress	 	door ibericode – 4.1.1
Mollie Payments for WooCommerce	 	door Mollie – 2.5.4
Noindex Pages	 	door Radley Sustaire – 1.0.1
Facebook Instant Articles & Google AMP Pages door PageFrog	 	door PageFrog Team – 1.0.9
Project Supremacy Plugin	 	door ProjectSupremacy (support@projectsupremacy.com) – 2.5.65
Recent Posts Widget Extended	 	door Satrya – 0.9.9.6
Redirection	 	door John Godley – 2.5
Resize Image After Upload	 	door iamphilrae – 1.7.2
Slider Revolution	 	door ThemePunch – 5.4.3
SEO Friendly Images	 	door Vladimir Prelovac – 3.0.5
Simple Author Box	 	door Tiguan – 1.6
WPML Multilingual CMS	 	door OnTheGoSystems – 3.7.0
SSH SFTP Updater Support	 	door TerraFrost – 0.7.1
Social Media and Share Icons (Ultimate Social Media)	 	door UltimatelySocial – 1.6.8
WooCommerce Multilingual	 	door OnTheGoSystems – 4.1.2
WooCommerce	 	door Automattic – 3.0.4
Yoast SEO	 	door Team Yoast – 4.6
WP Super Cache	 	door Automattic – 1.4.9
WPML String Translation	 	door OnTheGoSystems – 2.5.3
WPML Translation Management	 	door OnTheGoSystems – 2.3.0
YITH WooCommerce Compare	 	door YITHEMES – 2.2.0
YITH WooCommerce Email Templates	 	door YITHEMES – 1.3.1
YITH WooCommerce Wishlist	 	door YITHEMES – 2.1.1
Instellingen
API geactiveerd:		
Forceer SSL:		–
Valuta		EUR (€)
Positie van valutasymbool		left
Duizendtalscheiding		.
Decimaalscheiding		,
Aantal decimalen		2
Taxonomieën: Producttypen		external (external), grouped (grouped), product_pack (product_pack), simple (simple), variable (variable)
Taxonomieën: productzichtbaarheid		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pagina's
Winkelbasis:		#13 - /marktplaats/
Winkelmand:		#14 - /koop-via-secure-checkout/
Afrekenen:		#15 - /afronden/
Mijn account:		#11 - /en/my-account/
Thema
Naam:		Dokan Child
Versie:		1.0.0
URL van de maker:		http://websitelatenmaken.be
Subthema:		
Hoofdthema naam:		Dokan
Hoofdthema versie:		2.2.3
URL van de maker van het hoofdthema:		http://tareq.weDevs.com
WooCommerce Support:		
Templates
Overschrijvingen	 	dokan-child/archive-product.php, 
dokan/woocommerce/cart/mini-cart.php, 
dokan-child/checkout/thankyou.php versie 2.2.0 is verouderd. De hoofdversie is 3.0.0, 
dokan/woocommerce/global/form-login.php, 
dokan/woocommerce/loop/add-to-cart.php, 
dokan-child/myaccount/dashboard.php, 
dokan/woocommerce/myaccount/form-login.php, 
dokan-child/myaccount/my-account.php, 
dokan-child/myaccount/navigation.php, 
dokan-child/single-product.php
</details>

**Comment by mikejolley** [comment]
Themes need to enable it https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox)-in-3.0.0
