### ISSUE TITLE
Product in one line issue

### ISSUE THREAD

**Issue by MrTwIXx** [woocommerce/woocommerce#14688]
### EXPLANATION OF THE ISSUE

Under Version 3.0.4, the products are above in one line.
After I updated the template files, I get this Bug.

### STEPS TO REPRODUCE THE ISSUE

Check my Website.
### SYSTEM STATUS

<details>
### WordPress Environment ###

Home URL: https://twixx.xyz
Site URL: https://twixx.xyz
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

LayerSlider WP: by Kreatura Media – 6.2.2
Advanced Ads: by Thomas Maier – 1.7.24
Affiliates Manager Google reCAPTCHA Integration: by wp.insider
affmngr – 1.0.3

WP Affiliate Manager: by wp.insider
wpaffiliatemgr – 2.4.3

Analytics Code Integration: by tms_gac – 1.2.1
Awesome Support: by Awesome Support Team – 3.3.4
w3dev Ban Users: by WEBxMedia LTD. (Matt Whiteman) – 1.4.1
Disable Blog: by Joshua Nelson – 0.4.3
Disable Cart Fragments: by LittleBizzy – 1.0.1
Exclude Pages from Navigation: by Simon Wheatley – 1.92
Google Pagespeed Insights: by Matt Keys – 1.0.6
GoUrl Bitcoin Payment Gateway & Paid Downloads & Membership: by GoUrl.io – 1.3.15
GoUrl WooCommerce - Bitcoin Altcoin Payment Gateway Addon: by GoUrl.io – 1.1.11
WPBakery Visual Composer & qTranslate-X: by qTranslate Team – 1.0
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1
Block AdBlock: by Ibrahim Mohamed Abotaleb – 1.3
No CAPTCHA reCAPTCHA for WooCommerce: by Agbonghama Collins – 1.2
qTranslate-X: by qTranslate Team – 3.4.6.8
reSmush.it Image Optimizer: by Maecia – 0.1.11
Under Construction: by Web factory Ltd – 2.0
User Role Editor: by Vladimir Garagulya – 4.32.3
Woocommerce Email Verification: by Sandeep – 2.5.1
WooCommerce Payment Methods: by vendocrat – 1.1.2
WooCommerce & qTranslate-X: by qTranslate Team – 1.3
WooCommerce: by Automattic – 3.0.4
Wordfence Security: by Wordfence – 6.3.6
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 4.2.1
WP Rocket: by WP Media – 2.9.11
Integration: Yoast SEO & qTranslate-X: by qTranslate Team – 1.1.1
Yoast SEO: WooCommerce: by Team Yoast – 4.2.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Aurum
Version: 2.9.7
Author URL: http://laborator.co/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: aurum/woocommerce/archive-product.php
aurum/woocommerce/cart/cart-empty.php
aurum/woocommerce/cart/cart-shipping.php
aurum/woocommerce/cart/cart.php
aurum/woocommerce/cart/cross-sells.php
aurum/woocommerce/cart/shipping-calculator.php
aurum/woocommerce/checkout/form-billing.php
aurum/woocommerce/checkout/form-checkout.php
aurum/woocommerce/checkout/form-login.php
aurum/woocommerce/checkout/form-pay.php
aurum/woocommerce/checkout/form-shipping.php
aurum/woocommerce/checkout/review-order.php
aurum/woocommerce/checkout/thankyou.php
aurum/woocommerce/content-product.php
aurum/woocommerce/content-product_cat.php
aurum/woocommerce/content-single-product.php
aurum/woocommerce/global/form-login.php
aurum/woocommerce/global/wrapper-end.php
aurum/woocommerce/global/wrapper-start.php
aurum/woocommerce/loop/add-to-cart.php
aurum/woocommerce/loop/loop-end.php
aurum/woocommerce/loop/loop-start.php
aurum/woocommerce/loop/no-products-found.php
aurum/woocommerce/loop/orderby.php
aurum/woocommerce/loop/pagination.php
aurum/woocommerce/loop/price.php
aurum/woocommerce/loop/rating.php
aurum/woocommerce/loop/result-count.php
aurum/woocommerce/loop/sale-flash.php
aurum/woocommerce/myaccount/form-edit-account.php
aurum/woocommerce/myaccount/form-edit-address.php
aurum/woocommerce/myaccount/form-login.php
aurum/woocommerce/myaccount/form-lost-password.php
aurum/woocommerce/myaccount/form-reset-password.php
aurum/woocommerce/myaccount/my-account.php
aurum/woocommerce/myaccount/my-address.php
aurum/woocommerce/myaccount/my-downloads.php
aurum/woocommerce/myaccount/orders.php
aurum/woocommerce/myaccount/view-order.php
aurum/woocommerce/order/form-tracking.php
aurum/woocommerce/order/order-details-customer.php
aurum/woocommerce/order/order-details-item.php
aurum/woocommerce/order/order-details.php
aurum/woocommerce/order/tracking.php
aurum/woocommerce/single-product/add-to-cart/grouped.php
aurum/woocommerce/single-product/add-to-cart/variable.php
aurum/woocommerce/single-product/meta.php
aurum/woocommerce/single-product/price.php
aurum/woocommerce/single-product/product-image.php
aurum/woocommerce/single-product/product-thumbnails.php
aurum/woocommerce/single-product/rating.php
aurum/woocommerce/single-product/review-meta.php
aurum/woocommerce/single-product/review-rating.php
aurum/woocommerce/single-product/review.php
aurum/woocommerce/single-product/sale-flash.php
aurum/woocommerce/single-product/tabs/additional-information.php
aurum/woocommerce/single-product/tabs/description.php
aurum/woocommerce/single-product/tabs/tabs.php
aurum/woocommerce/single-product/title.php
aurum/woocommerce/single-product-reviews.php
aurum/woocommerce/single-product.php
</details>

**Comment by mikejolley** [comment]
The theme author may have changed the templates you replaced e.g. changed classnames. _You need to ask the theme author for a compatible update._
