### ISSUE TITLE
WooCommerce + Stamps.com API Integration

### ISSUE THREAD

**Issue by jsmusiker** [woocommerce/woocommerce#14695]
### EXPLANATION OF THE ISSUE

When Stamps.com / USPS can't verify the address, and you choose "Continue Anyway", then choose your package type, ship date, etc... then click "Get Rates", it returns the error:

To Address does not match Cleanse Hash

This is new. I have sent countless packages that don't get a successful address verification. Hence the option to "Continue Anyway".

For these purposes I have tried Flat Rate Padded Envelope & Flat Rate Box. But I don't think this has anything to do with the package type or shipping method used.

Error Message -

![stamps-plugin-cleanse-hash](https://cloud.githubusercontent.com/assets/7741647/25403200/988f55ba-29c9-11e7-9a59-b2440fbe9abf.png)

**Comment by claudiosanches** [comment]
There is no Stamps.com integration into WooCommerce Core.
Please report it to the author of the integration.
If is a WooCommerce.com plugin you can report in https://woocommerce.com/my-account/create-a-ticket/

**Comment by jsmusiker** [comment]
Hi Claudio,

I'm aware it's not part of core.  It it is a WC Plugin, from the WC site. And it looks to be a bug, I was told to report all bugs here. Pretty sure creating a ticket is for support, not bugs. I could be wrong.

**Comment by claudiosanches** [comment]
Note that when you come to this repository you were contemplated by the following message:

![screenshot from 2017-04-25 16-34-52](https://cloud.githubusercontent.com/assets/1264099/25404148/2fe7f0c4-29d5-11e7-98d5-3ebc9bf500e8.png)

https://github.com/woocommerce/woocommerce#support

So ok, I understand that looks like a bug, still not a bug on WooCommerce core, so only the WooCommerce.com support will be able to help you with it.

**Comment by jsmusiker** [comment]
I completely understand. Not looking for support. Just reporting a bug as I was told to do.

Thank you
