### ISSUE TITLE
I can't delete products since the update

### ISSUE THREAD

**Issue by infolightroom** [woocommerce/woocommerce#14690]
### EXPLANATION OF THE ISSUE

Hello, since I have updated the Woocommerce plugin to 3.0.4 version I can't delete any product. When I press the Delete button, the screen remains absolute white.

### STEPS TO REPRODUCE THE ISSUE
1. I open the Woocommerce products page
2. I click on DELETE on one of them
3. The screen turns complete white and stay these way

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://juegosdemesayrol.com
Site URL: https://juegosdemesayrol.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache/2.2.22 (Debian) mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_ssl/2.2.22 OpenSSL/1.0.1t
PHP Version: 7.0.1
PHP Post Max Size: 30 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - Recomendamos como versión mínima de MySQL la 5.6. Ver: Requisitos de WordPress
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

AfterShip - WooCommerce Tracking: por AfterShip – 1.6.8
Akismet Anti-Spam: por Automattic – 3.3
MonsterInsights - eCommerce Addon: por MonsterInsights Team – 6.0.4
MonsterInsights Pro: por MonsterInsights – 6.1.7
Gravity Forms MailPoet Add-on: por Ben Hays – 2.0.1
Gravity Forms: por rocketgenius – 1.9.13.4
Gravity Forms PayPal Standard Add-On: por rocketgenius – 2.3.1
Gravity Forms Polls Add-On: por Rocketgenius – 2.0
Homepage Control: por WooThemes – 2.0.2
HubSpot Marketing Free (formerly Leadin): por HubSpot – 6.1.2
Loco Translate: por Tim Whitlock – 2.0.13
MailPoet Gravity Forms Add-on: por Sebs Studio – 2.0.4
Quitar contador productos: por Joan Boluda – 1.5
Shortcodes in Menus: por Gagan Deep Singh and Saurabh Shukla – 3.1
Shortcode Widget: por Gagan Deep Singh – 1.2
Page Builder by SiteOrigin: por SiteOrigin – 2.5.2
Snippets: por Business Xpand – 0.9.4
SiteOrigin CSS: por SiteOrigin – 1.1.3
SiteOrigin Widgets Bundle: por SiteOrigin – 1.8.2
Storefront Blog Customiser: por WooThemes – 1.2.1
Storefront Checkout Customiser: por WooThemes – 1.1.4
Storefront Designer: por WooThemes – 1.8.4
Storefront Mega Menus: por WooThemes – 1.3.3 – 1.4.0 está disponible
Storefront WooCommerce Customiser: por WooThemes – 1.9.1 – 1.9.2 está disponible
Woo Checkout Field Editor Pro: por ThemeHiGH – 1.1.6
WooCommerce Advanced Ajax Layered Navigation: por Sixty-One Designs
Inc. – 1.4.9

WooCommerce Customizer: por SkyVerge – 2.4.0
WooCommerce Email Customizer: por WooThemes – 1.1.3 – 1.1.5 está disponible
WooCommerce PayPal Express Checkout Gateway: por WooCommerce – 1.2.0
WooCommerce Stripe Gateway: por WooCommerce – 3.1.7
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 1.6.5
WooCommerce Points and Rewards: por WooThemes – 1.5.13
WooCommerce Pre-Orders: por WooThemes – 1.4.5 – 1.4.10 está disponible
WooCommerce Google Product Feed: por Lee Willis – 6.7.3
WooCommerce Product Search: por itthinx – 1.6.0
WooCommerce Smart Coupons: por WooThemes – 3.1.5 – 3.3.0 está disponible
WooCommerce Waitlist: por Neil Pie – 1.4.12 – 1.5.2 está disponible
WooCommerce: por Automattic – 3.0.4
Yoast SEO: por Equipo Yoast – 4.6
MailPoet Newsletters Premium: por MailPoet – 2.7.8
MailPoet Newsletters: por MailPoet – 2.7.10

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base de la tienda: #599 - /tienda/
Carrito: #600 - /carrito/
Finalizar compra: #601 - /finalizar-comprar/
Mi cuenta: #602 - /mi-cuenta/

### Theme ###

Name: Juegos de mesa y rol Storefront
Version: 1.0.0.1479663657
Author URL: http://juegosdemesayrol.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

THANKS

**Comment by mikejolley** [comment]
Lot's of extensions in that list need an update ^ 

Also see https://wordpress.org/support/topic/how-to-debug-issues-after-updates/

Report back if the above doesn't solve it or help you find the issue.
