### ISSUE TITLE
Woocommerce Price Filter  Handle is not at correct location in RTL

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#14693]
Please checkout this image

tested in the default wordpress theme. But i see similar issues in other themes in rtl mode,

![pricefilter-woo-rtl](https://cloud.githubusercontent.com/assets/6078370/25400500/1bbb262a-29f3-11e7-89dd-ec2d18297874.png)
How to fix.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14714
