### ISSUE TITLE
Missing argument 3 & 4 ... on Line 1360

### ISSUE THREAD

**Issue by Hawthornek** [woocommerce/woocommerce#14692]
### EXPLANATION OF THE ISSUE

Site worked perfectly until updated 5 days ago.  Product Image is blurry but related products are correct.
Now all sites show this above the Blurry Product Image:
Warning: Missing argument 3 for avia_woocommerce_gallery_thumbnail_description() in /home/gridir18/public_html/wp-content/themes/enfold/config-woocommerce/config.php on line 1360

Warning: Missing argument 4 for avia_woocommerce_gallery_thumbnail_description() in /home/gridir18/public_html/wp-content/themes/enfold/config-woocommerce/config.php on line 1360

### STEPS TO REPRODUCE THE ISSUE

Visit www.gridironproductions.com - Click "Order Here" ---> Select ANY item as it does it to them all

### SYSTEM STATUS
`
### WordPress Environment ###

Home URL: http://gridironproductions.com
Site URL: http://gridironproductions.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (11) ###

All-in-One Event Calendar Extended Views by Time.ly: by Time.ly Network Inc. – 1.2.11
All-in-One Event Calendar by Time.ly: by Time.ly Network Inc. – 2.5.19
Comet Cache: by WebSharks
Inc. – 170220

SumoMe: by SumoMe – 1.26
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

Woo Checkout Field Editor Pro: by ThemeHiGH – 1.1.6
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.5
WooCommerce: by Automattic – 3.0.4
Yoast SEO: by Team Yoast – 4.6
WP Robots Txt: by Christopher Davis – 1.1
WP Smush: by WPMU DEV – 2.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #855 - /order-here/
Cart: #856 - /cart/
Checkout: #857 - /checkout/
My account: #858 - /my-account/

### Theme ###

Name: Enfold Child
Version: 1.0
Author URL: http://www.kriesi.at
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 3.5.2
Parent Theme Author URL: http://www.kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

<!--
BEFORE POSTING YOUR ISSUE
Issue begin after the last update - Nothing specific to add - Product Image is blurry but related products are correct.

**Comment by mensmaximus** [comment]
This issue is related to the theme. Please update the theme to its latest version 4.0.5 and follow the instructions on the [enfold forum](http://www.kriesi.at/support/topic/woocommerce-3-0-03-0-1-and-the-images-issue/).
