### ISSUE TITLE
WC_Coupon::exclude_sale_items is deprecated since version 3.0!

### ISSUE THREAD

**Issue by ApplicationError** [woocommerce/woocommerce#14696]
Are these core WooCommerce notices?

Notice: WC_Coupon::exclude_sale_items is deprecated since version 3.0! Use WC_Coupon::get_exclude_sale_items instead. in /web/sites/healthful/###.com/shop/wp-includes/functions.php on line 3830

**Comment by claudiosanches** [comment]
Messages from WooCommerce, but caused by a plugin or theme.
Check the theme and all plugins if they are compatible with WooCommerce 3.0.
