### ISSUE TITLE
Woo_subscriptions_bug

### ISSUE THREAD

**Issue by spouellet** [woocommerce/woocommerce#14704]
Hello. I've update woo_subscriptions I have a lot of issues. 
In my Wp-admin panel, in Woocommerce-Subscription, I just see 1 subscription order. Some of the subscription product disappear. Do you know what to do? Thanks

**Comment by spouellet** [comment]
My website: www.olabamboo.com

**Comment by mensmaximus** [comment]
For WooCommerce Supscription support please open a ticket in your account at woocommerce.com

**Comment by mikejolley** [comment]
Please use https://woocommerce.com/my-account/tickets/
