### ISSUE TITLE
Compulsory custom checkout fields can be left empty when proceeding to payment

### ISSUE THREAD

**Issue by konamac** [woocommerce/woocommerce#14708]
### EXPLANATION OF THE ISSUE

This problem has only arisen since I upgraded to 3.0.x from the final 2.x release.

I use woocommerce_form_field() to gather some custom metadata on my checkout page.
In the simplest demonstration case, I gather one extra field, which is compulsory  (i.e. the
argument 'required' is set to true for this field.)

The 'required' custom field is still marked with a red star on my checkout page, as expected.  The problem occurs when this field is left blank and the user tries to proceed to payment.

If a native required checkout field such as customer 'First name' is ALSO left blank, then the user is directed to fill in both compulsory fields (custom one and native one).  (They are both surrounded by a red box in my theme, to flag up that they need to be filled out.) 

If the compulsory custom field is the ONLY field left blank (so all native compulsory fields are populated), then the user is NOT forced to fill it out, and can proceed to the checkout without supplying the required custom information.

### STEPS TO REPRODUCE THE ISSUE

1. Write a function that creates an extra, compulsory checkout field using woocommerce_form_field(), and hook this function onto the woocommerce_checkout_before_customer_details hook.

2. Add product to cart and proceed to checkout.

3. Complete ALL compulsory checkout fields EXCEPT this new custom field.

4. Try to proceed to payment.  You should not be able to do this yet, because of the missing field, but as of the upgrade to WC 3.0.4 you are able to proceed to the payment page without supplying the required information.

### SYSTEM STATUS

NB This is from my development server, with all but the essential 3 plugins needed to demonstrate the error disabled.

<details>
``
### WordPress Environment ###

Home URL: http://devtryst.fidgetylizard.com
Site URL: http://devtryst.fidgetylizard.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.6
PHP Version: 5.6.5
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.19.1 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_5Td3Hc_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.12
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.0
WooCommerce: by Automattic – 3.0.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3940 - /events/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Drovers Tryst theme
Version: 1.0.0
Author URL: http://fidgetylizard.com
Child Theme: ✔
Parent Theme Name: Total
Parent Theme Version: 4.1
Parent Theme Author URL: https://themeforest.net/user/wpexplorer
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: Total/woocommerce/archive-product.php
Total/woocommerce/content-product.php
Total/woocommerce/content-widget-product.php
Total/woocommerce/loop/loop-start.php
Total/woocommerce/loop/pagination.php
Total/woocommerce/single-product/add-to-cart/variable.php
Total/woocommerce/single-product/title.php

```

```
</details>

**Comment by mikejolley** [comment]
If you're using `woocommerce_form_field()` and `woocommerce_checkout_before_customer_details` and manually adding fields, how is the checkout class supposed to know the field exists? It cannot - it can only loop over the fields it knows about. 

Checkout class only gets POSTED data for fields it renders itself:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L531-L578

This is the data it validates.

I did your test and my custom was never validated - not even when leaving other required fields blank. Maybe your code differs somewhat but looking at the class it seems to be the expected result.

You can add custom validation to this hook if you want to render fields manually in the way you describe:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L709

Hope that helps.

**Comment by konamac** [comment]
Gah, thanks Mike, I could have sworn the checks were working before the upgrade, but I see that this is clearly impossible ;)  

I think I must have been misled before because my fields were being flagged up in the _styling_ as needing to be set when validation failed, even though it wasn't them that was causing the validation failure.  Damn fool assumption!

Apologies for the false alarm. It's been one of those weeks.
