### ISSUE TITLE
woocommerce-rest-api Post/Put orders

### ISSUE THREAD

**Issue by johnwrise** [woocommerce/woocommerce#14703]
as subject post/put using below array:

        $data = array (
            'status' => 'completed',
            'set_paid' => 'true'
        );

message 'Syntax error' 

follow:
http://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order
$data = [
    'status' => 'completed'
];

and

http://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order
'set_paid' => true

Please help, thanks

**Comment by mikejolley** [comment]
You're not sending valid JSON. See this working example in my client:

![2017-04-26 at 11 27](https://cloud.githubusercontent.com/assets/90977/25430132/5f64ede0-2a73-11e7-93ce-723be6ebbbbd.png)

Don't send both however; set_paid updates the status (if pending payment).

**Comment by larssn** [comment]
@mikejolley Is it possible that you could reverify that this is still working? Doing what you posted, leaves the date_paid fields as null when I try to do the same via REST, on an order that is processing (latest WC).
