### ISSUE TITLE
Cannot save Add Meta for manual orders

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#14700]
### EXPLANATION OF THE ISSUE

WC 3.0.4

When creating a manual order and adding meta, cannot save the meta.

### STEPS TO REPRODUCE THE ISSUE

![](http://cld.wthms.co/q86j+)
Link to screenshot: http://cld.wthms.co/q86j

566605-zd-woothemes

**Comment by mikejolley** [comment]
Because both meta name and value are required and you missed the name field. 

We can add a placeholder but this is not a bug.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14712

**Comment by yukikatayama** [comment]
Ah, I see!

Thanks!
