### ISSUE TITLE
Searching form for orders

### ISSUE THREAD

**Issue by adamostrogorski** [woocommerce/woocommerce#14715]
How works searching form for orders in panel admin? I want search in my all orders e.g. orders from one city. Earlier this work properly, but now if I want search specified orders, I received only specified orders from  last month. How can I change this and where, if is possible? Thanks for all help.

**Comment by mikejolley** [comment]
See this thread https://wordpress.org/support/topic/wc-3-0-orders-search/#post-9060771 

There is a filter to add fields to the default search. Older orders won't have the new 'indexes' to make this efficient so if you can do without it it's best.
