### ISSUE TITLE
Tax not calculating correctly when manually entering an order

### ISSUE THREAD

**Issue by nuclearape** [woocommerce/woocommerce#14711]
### EXPLANATION OF THE ISSUE

If you manually create an order with a non-taxable product and a taxable shipping charge no tax is calculated for the shipping.

You can rectify this by including a taxable product in the order. See screen shots in "steps to reproduce" below.

_This isn't a duplicate of #14674. This happens when you manually add a new order.
All this testing is done with WooCommerce being the only active plugin and 2017 as the theme._

### STEPS TO REPRODUCE THE ISSUE

1. Go to the add new order screen (and ensure a country that is taxable is selected in the address details)
2. Add a non-taxable product
3. Add a taxable shipping cost
4. Calculate the totals - **notice that no tax has been added to the shipping**
![taxable-only](https://cloud.githubusercontent.com/assets/6885015/25429452/f5fa796c-2a70-11e7-98c5-61bd1783d0c8.png)

5. Add another taxable product
6. Recalculate the totals - **notice that the tax has now been added to the shipping correctly**
![mixed](https://cloud.githubusercontent.com/assets/6885015/25429457/fa99743c-2a70-11e7-8fda-b9b4bd272ef0.png)

Most of our orders are for a single, non-taxable product. So most of the time no tax gets added to the shipping. 

### SYSTEM STATUS

<details>
` ### WordPress Environment ###
Home URL: https://dev.chucklinggoat.co.uk
Site URL: https://dev.chucklinggoat.co.uk
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

Server Environment

Server Info: Apache/2.4.25 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

Database

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

Security

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

Active Plugins (1)

WooCommerce: by Automattic – 3.0.4

Settings

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

WC Pages

Shop base: #90 - /shop/
Cart: #91 - /shop/cart/
Checkout: #92 - /shop/checkout/
My account: #93 - /shop/my-account/

Theme

Name: Twenty Seventeen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

Templates

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/v03ufxetyqqqslr/2017-04-26%20at%2012.00.png

**Comment by nuclearape** [comment]
I've just tried with the '_Shipping tax class_' setting set to '_standard_' and I've tried with it set to '_Shipping tax class based on cart items_' and it makes no difference - **still no tax gets added to the shipping line if only a non-taxable product is in the order.**

**Comment by mikejolley** [comment]
No it seems to add regardless:

![2017-04-26 at 12 22](https://cloud.githubusercontent.com/assets/90977/25432137/36c6d2d8-2a7b-11e7-9ff0-59539507fd09.png)

**Comment by nuclearape** [comment]
@mikejolley thanks for testing that for me... that is weird - I have only the WooCommerce plugin active and am using the default WordPress theme so we should get the same results...

How would you suggest I go about getting to the bottom of this?

**Comment by mikejolley** [comment]
Try a new dummy product like me? Non taxable, simple product.

**Comment by nuclearape** [comment]
No luck. created a simple, non-taxable product and get the same results. 

![dummy-product](https://cloud.githubusercontent.com/assets/6885015/25440573/bea885ea-2a97-11e7-8565-30ceaeb42300.png)

**Comment by mikejolley** [comment]
Maybe you can screenshot your shipping, tax and tax rate settings for me?

**Comment by mikejolley** [comment]
Will need to be able to reproduce this to do anything.

**Comment by nuclearape** [comment]
@mikejolley sorry for the slow reply... shall I just give you a login to the dev site?

**Comment by mikejolley** [comment]
Sure via email.

**Comment by mikejolley** [comment]
Your non-taxable item had 'zero rate' tax class, and the tax rate defined in 'zero rates' didn't have the 'shipping' checkbox on :) Works after enabling that.

Seems to be a config issue.

**Comment by nuclearape** [comment]
Cheers @mikejolley 👍
