### ISSUE TITLE
Allow to set free shipping minimum amount with or without tax

### ISSUE THREAD

**Issue by TheZoker** [woocommerce/woocommerce#14728]
Currently it is only possible to set the amount that is needed for free shipping for a value including tax, but it would be useful to also set this amount to exclude tax.

Example:
Cart value: 
- 140$ (ex. tax)
- 155$ (incl. tax)

Free shipping minimum amount: 150$

So currently shipping is only free if the value with tax is above 150$. I need an additional setting to also respect the value without tax.

**Comment by mikejolley** [comment]
This needs to be requested on http://ideas.woocommerce.com/forums/133476-woocommerce to validate demand. We shouldn't add features like this with demand.

In the meantime, there are filters to add custom logic you should use: https://github.com/woocommerce/woocommerce/blob/master/includes/shipping/legacy-free-shipping/class-wc-shipping-legacy-free-shipping.php#L214
