### ISSUE TITLE
Product Attribute JSON

### ISSUE THREAD

**Issue by jmawebtech** [woocommerce/woocommerce#14720]
Hi,

I am using the WP JSON API.

When I add product variations, the parent product attributes are cleared. I can confirm that the JSON that I send matches the parent product attributes exactly. Please see the attached word document, which out lines our technical issue.

[parent.docx](https://github.com/woocommerce/woocommerce/files/958371/parent.docx)

**Comment by mikejolley** [comment]
@claudiosanches in v3 legacy API, should the name/slug of a global Color attribute be "Color" and "color" or the prefixed real attribute name ("pa_color"). It should be pa_color this may have changed.

**Comment by mikejolley** [comment]
NVM confirmed it's identical. Also a simple request like this works fine:

```
{
	"product": {
		"attributes": [
			{
				"name": "color",
				"slug": "color",
				"position": 0,
				"visible": false,
				"variation": true,
				"options": [
					"Black",
					"Test2"
				]
			}
		]
	}
}
```

**Comment by mikejolley** [comment]
Looking deeper, the options are SET and returned, but not actually set in admin so it looks like it's not detecting a term is required.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14722
