### ISSUE TITLE
Null prices are no longer filtered by woocommerce_get_price_html

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#14727]
Why did [`$product->get_price_html()`](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L1644) start returning the `$html` early if the price is null? In 2.6.x [`$product->get_price_html()`](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/abstracts/abstract-wc-product.php#L1011) still went through the `woocommerce_get_price_html` filter even if the price was null.

In the case of a Name Your Price product the regular price is often null, so I'm getting reports that the suggested price string (which filters `get_price_html()`) is now not showing, which I missed in my testing. Is this something that can be reverted? I can send the PR for the following change to the abstract product (and find the equivalent in other product classes):

```

	/**
	 * Returns the price in html format.
	 * @return string
	 */
	public function get_price_html( $deprecated = '' ) {
		if ( '' === $this->get_price() ) {
			$price = apply_filters( 'woocommerce_empty_price_html', '', $this );
		} else if ( $this->is_on_sale() ) {
			$price = wc_format_sale_price( wc_get_price_to_display( $this, array( 'price' => $this->get_regular_price() ) ), wc_get_price_to_display( $this ) ) . $this->get_price_suffix();
		} else {
			$price = wc_price( wc_get_price_to_display( $this ) ) . $this->get_price_suffix();
		}

		return apply_filters( 'woocommerce_get_price_html', $price, $this );
	}
```

**Comment by mikejolley** [comment]
Ok, send a PR.
