### ISSUE TITLE
Product Variations will not come up/display

### ISSUE THREAD

**Issue by phylynn35** [woocommerce/woocommerce#14735]
### EXPLANATION OF THE ISSUE

Try to bring up the variations under a product. Just get the rotating symbol as if it is trying to find the variations but after minutes of waiting nothing is ever brought up.  I have multiple products with variations and at this time can not bring them up to review or update.

This started happening with the new release of WooCommerce - 3.0. The variations worked just fine before hand.  I have already reloaded my data base to previous version of Woo Commerce. Variations worked just fine. Updated back to version 3.0 and problem is back.  When updated to new version did do the step to update the database. Did get the message that the database was updated. 

Will have to go back again in order to be able to work with all of my products and their variations. 
  
### STEPS TO REPRODUCE THE ISSUE

Edit a product with variations. 

Click on the variations tab. 

At this point the system acts as if it is looking for items it cannot find. 
### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>
`
### WordPress Environment ###

Home URL: https://www.petgatesplusmore.com
Site URL: https://www.petgatesplusmore.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_7d9hsv64fm_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Akismet Anti-Spam: by Automattic – 3.3
CMB2: by WebDevStudios – 2.2.4
Contact Form 7: by Takayuki Miyoshi – 4.7
Kirki Toolkit: by Aristeides Stathopoulos – 2.3.7
No Page Comment: by Seth Alling – 1.2
Search Engine Visibility: by GoDaddy – 0.5
Social Icons: by ThemeGrill – 1.5.0
WooCommerce Table Rate Shipping by Mangohour: by mangohour – 1.2.1
TWP Shortcodes: by Themes4WP – 1.0.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.40.21

WooCommerce - Store Exporter: by Visser Labs – 1.8.8
WooCommerce Extra Product Sorting Options: by SkyVerge – 2.6.0
WooCommerce: by Automattic – 3.0.4
Yoast SEO Premium: by Team Yoast – 4.6
WP Image Zoom PRO: by SilkyPress – 1.16
WP-Sweep: by Lester 'GaMerZ' Chan – 1.0.10
MailPoet Newsletters: by MailPoet – 2.7.10

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #4494 - /cart/
Checkout: #4497 - /checkout-page/
My account: #4526 - /account-page-petgatesplusmore/

### Theme ###

Name: MaxStore PRO
Version: 1.9.0
Author URL: http://themes4wp.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: maxstore-pro/woocommerce/myaccount/my-account.php version 2.0.0 is out of date. The core version is 2.6.0
Outdated Templates: ❌Learn how to update
`

**Comment by mikejolley** [comment]
Pretty sure it's a conflict but if you mail me a login I will check; mike.jolley at automattic.com. Need to be running 3.0 if I look.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14744
