### ISSUE TITLE
Multi-site User Checkout Issue

### ISSUE THREAD

**Issue by Josh-Love** [woocommerce/woocommerce#14736]
### EXPLANATION OF THE ISSUE

Using woocommerce 3.0.4 on a wordpress multi-site, when logging into one store on the multi-site, then visiting another store on the multi-site, then trying to check out, I get an 'Please provide a valid e-mail' error message. 

### STEPS TO REPRODUCE THE ISSUE

1) Have 2 stores in a multi-site.
2) Create user on store 1
2) Login as that user on store1
3) Go to store 2 (do not log in on store 2 or it will fix the issue)
4) Check out on store 2
5) When trying to place order, error message should appear

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14755
