### ISSUE TITLE
Woocommerce Variation

### ISSUE THREAD

**Issue by kadirakkus9** [woocommerce/woocommerce#14730]
Hi; 
I am adding variation from Woocommerce product options. I need to add at least 35 variations. I add 30 variations and everything works fine. 
But, 
31. The options on the product view page are broken when I add the variation. All the variations appear on the product view page. How can I solve this problem.

**Comment by mikejolley** [comment]
When there are > 30 it  triggers ajax loading on the front end.

https://gist.github.com/claudiosanches/6f91ad228c2176b986b2
