### ISSUE TITLE
`set_price()` does not update cart item's price

### ISSUE THREAD

**Issue by TechieKent** [woocommerce/woocommerce#14747]
### EXPLANATION OF THE ISSUE

WC version: 		3.0.4
WP version: 		4.7.4
I was using `woocommerce_before_calculate_totals` action hook to manipulate price for certain products in cart. I used the `set_price()` method, but the price return from `get_price()` is still the original ones, thus causing miscalculation of total prices.

### STEPS TO REPRODUCE THE ISSUE

Following is the simplified code I used to test price change over the hook:

```
add_action('woocommerce_before_calculate_totals', 'set_custom_price');

function set_custom_price($cart_obj) {
    foreach ($cart_obj->get_cart() as $key => $value) {
        if ($value['product_id'] == 123) {
            $value['data']->set_price(9.90);
            $new_price = $value['data']->get_price();
        }
    }
}
```
The resulting`$new_price` should be `9.90`, but it still return original price instead.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.bty.com.my
Site URL: http://www.bty.com.my
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.32 (Unix) mod_ssl/2.2.32 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (16) ###

WPCoreSys: by Wordpress – 2.0
Block Specific Plugin Updates: by Dinesh Karki – 2.2
BTY Custom Plugin: by Webqlo – 1.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom WooCommerce iPay88 Payment Gateway: by Chan Hui Kent – 0.0.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.11.2
Nav Menu Roles: by Kathy Darling – 1.8.6
Options Framework: by Devin Price – 1.8.5
Slider Revolution: by ThemePunch – 5.1.2
Social Media Feather: by socialmediafeather – 1.8.3
User Roles and Capabilities: by mahabub – 1.2.1
WooCommerce PDF Invoices: by Bas Elbers – 2.4.11
WooCommerce Product Sort and Display LITE: by a3rev Software – 1.7.6
WooCommerce: by Automattic – 3.0.4
WordPress Importer: by wordpressdotorg – 0.6.3
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.28

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: Malaysia Custom (MYR)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: dgfw_gift (dgfw_gift)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #21 - /product/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: ❌ Page does not contain the shortcode.

### Theme ###

Name: Pharmacy
Version: 1.5.2 Updated 20-Nov-2015
Author URL: http://bit.ly/opalwp
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: pharmacy/woocommerce/archive-product.php
pharmacy/woocommerce/cart/cart-empty.php
pharmacy/woocommerce/cart/cart-shipping.php version 2.3.0 is out of date. The core version is 2.5.0
pharmacy/woocommerce/cart/cart-totals.php
pharmacy/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
pharmacy/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
pharmacy/woocommerce/cart/mini-cart.php version 2.1.0 is out of date. The core version is 2.5.0
pharmacy/woocommerce/cart/shipping-calculator.php
pharmacy/woocommerce/checkout/form-billing.php version 2.1.2 is out of date. The core version is 3.0.0
pharmacy/woocommerce/checkout/form-checkout.php
pharmacy/woocommerce/checkout/form-coupon.php
pharmacy/woocommerce/checkout/form-pay.php version 2.4.7 is out of date. The core version is 2.5.0
pharmacy/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.0.0
pharmacy/woocommerce/checkout/payment-method.php
pharmacy/woocommerce/checkout/payment.php
pharmacy/woocommerce/checkout/review-order.php
pharmacy/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
pharmacy/woocommerce/content-product.php version 2.4.0 is out of date. The core version is 3.0.0
pharmacy/woocommerce/content-product_cat.php version 2.4.0 is out of date. The core version is 2.6.1
pharmacy/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
pharmacy/woocommerce/content-widget-product.php version - is out of date. The core version is 2.5.0
pharmacy/woocommerce/global/form-login.php
pharmacy/woocommerce/global/quantity-input.php version - is out of date. The core version is 2.5.0
pharmacy/woocommerce/global/wrapper-end.php
pharmacy/woocommerce/global/wrapper-start.php
pharmacy/woocommerce/loop/loop-end.php
pharmacy/woocommerce/loop/loop-start.php
pharmacy/woocommerce/loop/orderby.php
pharmacy/woocommerce/loop/pagination.php
pharmacy/woocommerce/loop/price.php
pharmacy/woocommerce/loop/rating.php version 2.0.0 is out of date. The core version is 3.0.0
pharmacy/woocommerce/loop/result-count.php version 2.0.0 is out of date. The core version is 3.0.0
pharmacy/woocommerce/loop/sale-flash.php
pharmacy/woocommerce/myaccount/form-add-payment-method.php version 2.1 is out of date. The core version is 3.0.0
pharmacy/woocommerce/myaccount/form-edit-account.php version 2.2.7 is out of date. The core version is 2.6.0
pharmacy/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 2.6.0
pharmacy/woocommerce/myaccount/form-lost-password.php version 2.3.0 is out of date. The core version is 3.0.0
pharmacy/woocommerce/myaccount/my-address.php version 2.2.0 is out of date. The core version is 2.6.0
pharmacy/woocommerce/myaccount/my-downloads.php
pharmacy/woocommerce/myaccount/my-orders.php
pharmacy/woocommerce/notices/error.php
pharmacy/woocommerce/notices/notice.php
pharmacy/woocommerce/notices/success.php
pharmacy/woocommerce/order/form-tracking.php
pharmacy/woocommerce/order/order-details.php version 2.4.0 is out of date. The core version is 3.0.0
pharmacy/woocommerce/single-product/add-to-cart/external.php
pharmacy/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.3
pharmacy/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
pharmacy/woocommerce/single-product/add-to-cart/variable.php version 2.4.0 is out of date. The core version is 3.0.0
pharmacy/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
pharmacy/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
pharmacy/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.0.0
pharmacy/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
pharmacy/woocommerce/single-product/review.php version 2.1.0 is out of date. The core version is 2.6.0
pharmacy/woocommerce/single-product/sale-flash.php
pharmacy/woocommerce/single-product/short-description.php
pharmacy/woocommerce/single-product/tabs/tabs.php
pharmacy/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
pharmacy/woocommerce/single-product-reviews.php
pharmacy/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
It works fine. I filtered my price to 1000 and that carried through to the order. tested with a simple product. If yours is variable, you need to use the variation id.
