### ISSUE TITLE
Vertical alignment of images, not cropping

### ISSUE THREAD

**Issue by stefan-media90** [woocommerce/woocommerce#14746]
Can you help me please to align product images in categories vertically without being cropped. 

I tried with CSS but no result. I need something like vertical-align:middle 

<img src="http://i.imgur.com/J956XCG.jpg" alt="" />

Thank you

**Comment by mikejolley** [comment]
We don't provide customisations on our issue tracker. vertical-align is not sufficient for this. https://www.brunildo.org/test/img_center.html

**Comment by stefan-media90** [comment]
ah .. ok. This link dosen't work: https://www.brunildo.org/test/img_center.html
