### ISSUE TITLE
Free products not showing as free but as 0,00

### ISSUE THREAD

**Issue by vipii** [woocommerce/woocommerce#14745]
### EXPLANATION OF THE ISSUE

Since update 3.0.0 our free products are not showing anymore as "Free"  but as 0,00.
Also if we delete the price, the add to card button becomes inactive.
We own a large store that is selling a lot every day and we need this fixed asap.

### STEPS TO REPRODUCE THE ISSUE

Create a new product, give it the price 0,00.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.vangastel.be
Site URL: https://www.vangastel.be
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.12-1~dotdeb+8.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.29
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_6_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (46) ###

ManageWP - Worker: door ManageWP – 4.2.18
Polylang: door Frédéric Demarle – 2.1.3
VaultPress: door Automattic – 1.8.8
Gravity Forms: door rocketgenius – 2.2.1
Advanced Custom Fields: Sliders Field: door WPPress.net – 1.1
Advanced Custom Fields: TablePress: door Tyler Digital – 1.3.2
Advanced Access Manager: door Vasyl Martyniuk  – 4.7
Advanced Custom Fields: Font Awesome: door Matt Keys – 1.7.3
Advanced Custom Fields PRO: door Elliot Condon – 5.5.12
Akismet Anti-Spam: door Automattic – 3.3
Better Font Awesome: door MIGHTYminnow & Mickey Kay – 1.6.0
Disable Comments: door Samir Shah – 1.6
Duplicate Post: door Enrico Battocchi – 3.2
FooEvents for WooCommerce: door Grenade – 1.3.0
Intracto WooCommerce Extra's: door Christophe Vanleeuw | Intracto Digital Agency – 1.0
WooCommerce Delivery Slots: door Iconic – 1.7.4
Jetpack door WordPress.com: door Automattic – 4.8.2
Loco Translate: door Tim Whitlock – 2.0.13
Min and Max Quantity for WooCommerce: door BeRocket – 911.0.2
Page Links To: door Mark Jaquith – 2.9.9
Polldaddy Polls & Ratings: door Automattic
Inc. – 2.0.34

Post Expirator: door Aaron Axelsen – 2.1.4
WP Real Media Library: door Matthias Günter – 2.6.3
Really Simple SSL: door Rogier Lankhorst – 2.5.11
Redirection: door John Godley – 2.5
Responsive Menu: door Peter Featherstone – 3.1.0
Slider Revolution: door ThemePunch – 5.4.3.1
Page Builder by SiteOrigin: door SiteOrigin – 2.5.2
SiteOrigin Widgets Bundle: door SiteOrigin – 1.8.2
TablePress: door Tobias Bäthge – 1.8
What The File: door Never5 – 1.5.3
Advanced Order Export For WooCommerce: door AlgolPlus – 1.3.0
WooCommerce EU VAT Number: door WooCommerce – 2.2.0
WooCommerce Intracto Credits Gateway: door Intracto Digital Agency – 1.0.2
WooCommerce Ogone Payment Gateway: door SkyVerge – 1.9.0
WooCommerce Google Analytics Integration: door WooThemes – 1.4.0
WooCommerce Order Status Manager: door SkyVerge – 1.7.1
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 1.6.5
Woocommerce Remove SKU: door Prem Tiwari – 1.0.0
WooCommerce Role Based Methods: door WPBackOffice – 2.0.9
WooCommerce - Store Exporter Deluxe: door Visser Labs – 2.3.2
WooCommerce Subscriptions: door Prospress Inc. – 2.2.5
WooCommerce: door Automattic – 3.0.4
WooCommerce Helper: door WooCommerce – 1.7.2 – Netwerk geactiveerd
Yoast SEO: door Team Yoast – 4.6
YITH WooCommerce Added to Cart Popup Premium: door YITHEMES – 1.2.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #5 - /shop/
Winkelmand: #6 - /winkelmand/
Afrekenen: #7 - /checkout/
Mijn account: #8 - /mijn-account/

### Theme ###

Name: UnderStrap
Version: 9.4.9
Author URL: http://www.holgerkoenemann.de
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een subthema aan. Zie: Hoe maak je een subthema

WooCommerce Support: ✔

### Templates ###

Archive Template: Jouw thema heeft een woocommerce.php bestand. Je zal het woocommerce/archive-product.php template niet kunnen overschrijven omdat woocommerce.php prioriteit heeft over archive-product.php. Dit is bedoeld om weergave-problemen te voorkomen.
Overrides: understrap/woocommerce/archive-product.php
understrap/woocommerce/content-product.php
understrap/woocommerce/content-single-product.php
understrap/woocommerce/emails/admin-cancelled-order.php
understrap/woocommerce/emails/admin-failed-order.php
understrap/woocommerce/emails/admin-new-order.php
understrap/woocommerce/emails/customer-completed-order.php
understrap/woocommerce/emails/customer-invoice.php
understrap/woocommerce/emails/customer-new-account.php
understrap/woocommerce/emails/customer-note.php
understrap/woocommerce/emails/customer-on-hold-order.php
understrap/woocommerce/emails/customer-processing-order.php
understrap/woocommerce/emails/customer-refunded-order.php
understrap/woocommerce/emails/customer-reset-password.php
understrap/woocommerce/emails/email-addresses.php
understrap/woocommerce/emails/email-customer-details.php
understrap/woocommerce/emails/email-footer.php
understrap/woocommerce/emails/email-header.php
understrap/woocommerce/emails/email-order-details.php
understrap/woocommerce/emails/email-order-items.php
understrap/woocommerce/emails/email-styles.php
understrap/woocommerce/emails/plain/admin-cancelled-order.php
understrap/woocommerce/emails/plain/admin-failed-order.php
understrap/woocommerce/emails/plain/admin-new-order.php
understrap/woocommerce/emails/plain/customer-completed-order.php
understrap/woocommerce/emails/plain/customer-invoice.php
understrap/woocommerce/emails/plain/customer-new-account.php
understrap/woocommerce/emails/plain/customer-note.php
understrap/woocommerce/emails/plain/customer-on-hold-order.php
understrap/woocommerce/emails/plain/customer-processing-order.php
understrap/woocommerce/emails/plain/customer-refunded-order.php
understrap/woocommerce/emails/plain/customer-reset-password.php
understrap/woocommerce/emails/plain/email-addresses.php
understrap/woocommerce/emails/plain/email-customer-details.php
understrap/woocommerce/emails/plain/email-order-details.php
understrap/woocommerce/emails/plain/email-order-items.php
understrap/woocommerce/global/breadcrumb.php
understrap/woocommerce/myaccount/dashboard.php
understrap/woocommerce/single-product/tabs/description.php
understrap/woocommerce/single-product.php

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Templates ###

Scheduled Export to FTP: ✔
Scheduled Export to SFTP: ❌ The required SFTP functions are not available
`
</details>

**Comment by mikejolley** [comment]
https://gist.github.com/rynaldos/c42a41c415f2fd4f77415398204b84a0
