### ISSUE TITLE
Fillter for template loader for all files

### ISSUE THREAD

**Issue by sebastianpisula** [woocommerce/woocommerce#14742]
If in theme exists woocommerce.php in child theme I can remove him. I think that via this filter I can remove default template :)

move woocommerce_template_loader_files filter before return

**Comment by mikejolley** [comment]
woocommerce.php is supposed to be a catch all template, so filtering it should not be supported. We recommend not using woocommerce.php at all but it's down to the user. System status report informs if this is being used.
