### ISSUE TITLE
CLI router broken for some commands

### ISSUE THREAD

**Issue by electrokit** [woocommerce/woocommerce#14750]
CLI won't handle these commands:
wp wc --user=test shipping_zone_method list
wp wc --user=test shipping_zone_method get 0
wp wc --user=test shipping_zone_location list
wp wc --user=test shipping_zone get 0

They all echo:
Error: No route was found matching the URL and request method {"status":404}

WooCommerce 3.0.4
WordPress 4.7.4

**Comment by mikejolley** [comment]
@justinshreve any idea if this should be working? I cannot get it working either.

**Comment by electrokit** [comment]
I think I found it. The commands expect a zone_id, but it isn't in the $supported_ids array (and therefore won't show in the usage text)

It will work if we add the `row`
`'zone_id'      => __( 'Zone ID.', 'woocommerce' ),`
to the $supported_ids array in class-wc-cli-runner.php:register_route_commands()

and fix the broken route texts by replacing `(?P<zone_id>[\d-]+)` by `(?P<zone_id>[\d]+)` (removing the minus sign) in all places:
tests/unit-tests/api/shipping-zones.php:66
tests/unit-tests/api/shipping-zones.php:67
tests/unit-tests/api/shipping-zones.php:68
includes/api/class-wc-rest-shipping-zone-methods-controller.php:29
includes/api/class-wc-rest-shipping-zone-methods-controller.php:56
includes/api/class-wc-rest-shipping-zone-locations-controller.php:29
includes/api/class-wc-rest-shipping-zones-controller.php:50

Note: I haven't tested normal REST functionality, so I don't know if this breaks something

**Comment by justinshreve** [comment]
I haven't dug further but yeah it looks like that ID/route format needs added to the CLI runner. I'm not sure if we need to change the route on the API side -- it would be nicer to fix in the CLI runner code.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14787
