### ISSUE TITLE
URL's modified when on My Account sections

### ISSUE THREAD

**Issue by WhoopDav** [woocommerce/woocommerce#14757]
### EXPLANATION OF THE ISSUE
When you are logged in and accessing the "My Account" section, the URL's in the footer of my site are changed. For example www.mysite.com/contact/ is changed to www.mysite.com/my-account/contact/  The same applies to all URL's in my footer. I am not sure is this is a WC issue or one related to theme.

### STEPS TO REPRODUCE THE ISSUE

1. Login, go to 'my-account' > orders/ download / addresses / acount details (any of these sectiosn except for the 'dashboard'). Now check the URL's in your footer which have been created by the WordPress auto URL box (the system which helps automatically offer one of site URLs).

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
No link or details to check, but it simply sounds like those URLs have been input relatively e.g. `/contact/` so it will just append to the current URL.

Tested with a menu added to the footer area and it was not changed. Does not appear to be a WC issue.

**Comment by WhoopDav** [comment]
Actually no the URLs were not input relatively. The full URL was entered: https://www.mysite.com/contact/

This URL only changes when on the my-account sections that I listed., where "my-account" is added into teh URL.

**Comment by mikejolley** [comment]
I've tested this with a menu on the account page - no links are changed. Maybe you're using a plugin to output relative urls or similar.

**Comment by WhoopDav** [comment]
Thanks for your fast replies. OK I will try see what this is caused by. I
have no plugin for URL output but obviously some plugin then affecting this.
