### ISSUE TITLE
Woocommerce Variation Availability Stock Number

### ISSUE THREAD

**Issue by emarketingclusters** [woocommerce/woocommerce#14759]
### EXPLANATION OF THE ISSUE

Is Variable Product. Manage Stock is checked. Stock quantity is 1. In single product page, when I choose the variation (eg size & color) is says "Only 1.000000 left in stock" instead of "Only 1 left in stock". I noticed this after the last woocommerce update to version 3.0.4.  

### STEPS TO REPRODUCE THE ISSUE

Is Variable Product. Manage Stock is checked. Stock quantity is 1. In single product page, when I choose the variation (eg size & color) is says "Only 1.000000 left in stock". The link of the product is https://www.europedress.com/product/113932/

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.europedress.com
Site URL: https://www.europedress.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Contact Form 7: by Takayuki Miyoshi – 4.7
IgniteUp: by Ceylon Systems – 3.2
KingComposer: by King-Theme – 2.6.11
MailChimp for WordPress: by ibericode – 4.1.1
Meta Box: by Anh Tran – 4.11
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.3.0.2
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.0
WooCommerce: by Automattic – 3.0.4
Wordfence Security: by Wordfence – 6.3.7
Yoast SEO: by Team Yoast – 4.6
WPOPAL Framework For Themes: by WPOPAL – 1.2.6.8
YITH WooCommerce Compare: by YITHEMES – 2.2.0
YITH WooCommerce Wishlist: by YITHEMES – 2.1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
simple (simple-ar)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /shopping-cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: happytime
Version: 1.0
Author URL: http://www.europedress.com/
Child Theme: ✔
Parent Theme Name: happytime
Parent Theme Version: 1.0 Updated 1-July-2016
Parent Theme Author URL: http://www.themelexus.com;
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: happytime/woocommerce/cart/cart-empty.php
happytime/woocommerce/cart/mini-cart.php
happytime/woocommerce/checkout/form-checkout.php
happytime/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.0.0
happytime/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
happytime/woocommerce/content-product_cat.php
happytime-child/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
happytime/woocommerce/global/breadcrumb.php
happytime/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0
happytime/woocommerce/loop/loop-end.php
happytime/woocommerce/loop/loop-start.php
happytime/woocommerce/loop/rating.php version 2.0.0 is out of date. The core version is 3.0.0
happytime/woocommerce/single-product/related.php version 2.6.1 is out of date. The core version is 3.0.0
happytime/woocommerce/single-product/review.php
happytime/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
happytime/woocommerce/single-product-reviews.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
Stock is ran through the filter `woocommerce_stock_amount` when loaded. By default we cast this to integer https://github.com/woocommerce/woocommerce/blob/e027e5b0a1ab8e2c7b746c7d6bd2ef3879178139/includes/wc-core-functions.php#L41

This means on your site this filter is being removed/replaced, possibly by an extension, and possibly to allow 'floats' (decimal values).

I tested this by entering 1.0000 on a product. It was formatted as 1 on the frontend.

**Comment by acaparrelli** [comment]
Exactly the same problem here.

**Comment by emarketingclusters** [comment]
The problem still exists. So I went back to previous version of WooCommerce, version 2.6.14.

**Comment by mikejolley** [comment]
Like I said, it's caused by 3rd party code.

**Comment by miniMAC** [comment]
Hello! I've tested and the problem persist. Reopen the Issue, it's a bug and is not caused by other 3rd party code @mikejolley

**Comment by mikejolley** [comment]
If that was the case wouldn't we see it on all installs?

**Comment by emarketingclusters** [comment]
I noticed the problem after woocommerce update. In the same website, with the same plugins. This problem doesn't exist in older version 2.6.14. So this is a woocommerce's update bug.

**Comment by mikejolley** [comment]
You can keep saying that but unless a developer can replicate it on a clean install with no addons, it cannot be patched.

**Comment by miniMAC** [comment]
It'a bug for the 3.X.X. If you update the stock quantity, for example, from 1 to 2 and save, the problem is resolved.
But with the bulk fast edit this not work! You can update and re-save post per post.

**Comment by SarrahW** [comment]
Hi there! I'm experiencing this issue as well, and was able to reproduce it consistently. I have disabled all other plugins, so right now I am testing on an install with only Wordpress v 4.7.5, Storefront theme v 2.2.3, and WooCommerce v 3.0.7.

**Steps to reproduce:**

1. Create a variable product.
2. Enable Manage Stock on the product level and enter a quantity (leave disabled on the variation level)
3. Save the product (if the product is viewed on the front end, it looks fine at this point)
4. In the Products list, click Quick Edit.
5. Click Update.
6. View product - the stock number will now display x.000000 on the front end.
