### ISSUE TITLE
Sale Badge on Related and Upsell Products

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#14754]
Hi  

Why does the Sale badge not show on related and upsell products? Is there a setting or code to achieve that?

Thank you for any suggestion

**Comment by mikejolley** [comment]
Theme related? Works here : https://dl.dropboxusercontent.com/s/xju88gosk9jnwko/2017-04-27%20at%2013.50.png

**Comment by BackuPs** [comment]
Yeah here works also... browser cache was playing tricks on me... should have checked another browser first. Sorry about that.
