### ISSUE TITLE
Missing order details on checkout with Amazon Pay gateway

### ISSUE THREAD

**Issue by LiquidSponge** [woocommerce/woocommerce#14758]
### EXPLANATION OF THE ISSUE

When an order is completed using Amazon Pay there are missing order details. In the orders backend I only see the town, county and postcode for an order. Missing parameters include the forename, surname, email address, phone number and address line.

I am testing on a local WordPress install and with only Twenty Twelve, Woocommerce and the Amazon Pay gateway installed. This issue first started following the upgrade to 3.0.

Clicking on the Amazon Pay reference in the orders backend takes me to the Amazon seller backend where I can retrieve the missing details. Aside from the missing details in the Woocommerce backend the order completes successfully (payment is authorised and captured).

When checking out using Amazon Pay in Google Chrome `billing_first_name`, `billing_last_name`, `billing_email` are empty in the post form data. I am not familar with how Woocommerce processes checkout so this may or may not be relevant.

![Request data in Chrome](http://i.imgur.com/aviX8QW.png)

### STEPS TO REPRODUCE THE ISSUE

1. Install WordPress
2. Install Twenty Twelve theme
3. Install Woocommerce
i. Complete installation wizard
ii. Add test product
4. Install [Amazon Pay](https://woocommerce.com/products/pay-with-amazon/) gateway
i. Enable Amazon Pay checkout
ii. Fill out seller ID and MWS keys
5. Sign out
6. Add test product to cart
7. Select checkout through Amazon Pay
8. Sign in to Amazon
9. Select Amazon address and payment method
10. Complete checkout

### SYSTEM STATUS

<details>
```
### WordPress Environment ###

Home URL: http://10.5.0.9
Site URL: http://10.5.0.9
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.0
PHP Version: 5.6.30-10+deb.sury.org~xenial+2
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Amazon Pay Gateway: by WooCommerce – 1.7.0
WooCommerce: by Automattic – 3.0.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9

### Theme ###

Name: Twenty Twelve
Version: 2.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
Will be fixed in 1.7.1
