### ISSUE TITLE
thumbnail not showing

### ISSUE THREAD

**Issue by bianqui149** [woocommerce/woocommerce#14760]
### EXPLANATION OF THE ISSUE

Was using version 2.6 and updated to 3.0.4 and the thumbnails of the variations are not shown in the single-product.

![woo 3 04](https://cloud.githubusercontent.com/assets/22307049/25488199/cf28a102-2b3c-11e7-9474-b871c8c87cf0.png)

**Comment by mikejolley** [comment]
if the theme does not support the new gallery, image substitution may not occur. Looks like you need a theme update. 

https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox)-in-3.0.0
