### ISSUE TITLE
CLI orderby date_modified is not considered a date

### ISSUE THREAD

**Issue by rcojoe** [woocommerce/woocommerce#14762]
### EXPLANATION OF THE ISSUE

When using wp wc cli command,  I try to order the product list by date_modified, an error occurs saying the orderby is not a "date"

I have tried the wp default of `--orderby=modified` but I get the same error.   I can list them by doing this
`wp --user=5 list --post_type=product --orderby=modified --fields=ID,modified --order=asc`

### STEPS TO REPRODUCE THE ISSUE

`$ wp wc --user=5 product list --orderby=date_modified`
`Error: Invalid parameter(s): orderby {"status":400,"params":{"orderby":"orderby is not one of date, id, include, title, slug."}}`

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.rockcreek.com
Site URL: https://www.rockcreek.com/gear
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 8 MB
PHP Time Limit: -1
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.16
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: R0cK_wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

Akismet Anti-Spam: by Automattic – 3.3
Categories in Hierarchical Order: by Amit Sonkhiya
Kamal Agrawal – 1.1

Child Theme Configurator: by Lilaea Media – 2.2.4.1
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.2.1

Code Snippets: by Shea Bunge – 2.8.2
Dave's WordPress Live Search: by Dave Ross – 4.5
Display Categories Widget: by Suresh Baskaran – 2.1
Display Widgets: by Strategy11 – 2.05
Disqus Comment System: by Disqus  – 2.87
Google Tag Manager for Wordpress: by Thomas Geiger – 1.6.1
FacetWP - Relevanssi integration: by FacetWP
LLC – 0.5

FacetWP: by FacetWP
LLC – 2.8.4

FraudLabs Pro for WooCommerce: by FraudLabs Pro – 2.8.17
Get The Image: by Justin Tadlock – 1.0.1
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Max Mega Menu - StoreFront Integration: by Tom Hemsley – 0.1
Max Mega Menu: by Tom Hemsley – 2.3.5
Meta Slider: by Matcha Labs – 3.5
Page Links To: by Mark Jaquith – 2.9.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Relevanssi: by Mikko Saari – 3.5.8
Simple Social Icons: by Nathan Rice – 2.0.1
Title Toggle for Storefront Theme: by Wooassist – 1.2.3
SumoMe: by SumoMe – 1.26
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.40.1

Wc Bulk Product Delete: by Varun Sridharan – 0.2
WC Duplicate Order: by Jamie Gill – 1.2
WooSwatches - Woocommerce Color or Image Variation Swatches: by parbat chaudhari – 2.3.6
WooCommerce Amazon Pay Gateway: by WooCommerce – 1.7.0
WooCommerce CyberSource SA SOP Gateway: by SkyVerge – 2.7.1-dev.1 – 2.7.1 is available
WooCommerce Google Trusted Stores Integration: by enollo – 1.0.0
WooCommerce MailChimp Integration: by WooCommerce – 1.0.2
WooCommerce Order Status Manager: by SkyVerge – 1.7.1-dev – 1.7.1 is available
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.14
WooCommerce Shipment Tracking: by WooCommerce – 1.6.4
WooCommerce: by Automattic – 3.0.4
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.6
WP All Export: by Soflyy – 1.1.3
WP All Import Pro: by Soflyy – 4.4.3
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP Super Cache: by Automattic – 1.4.9
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.5
WPSSO Schema JSON-LD Markup (WPSSO JSON) Pro: by JS Morisset – 1.13.8
WPSSO Update Manager (WPSSO UM): by JS Morisset – 1.6.2
WordPress Social Sharing Optimization (WPSSO) Pro: by JS Morisset – 3.41.0
YouTube: by EmbedPlus Team – 11.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
exclude-from-search (exclude-from-search-2)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)
rated-5 (rated-5-2)

### WC Pages ###

Shop base: #26557 - /shop
Cart: #26558 - /cart
Checkout: #26559 - /checkout
My account: #26560 - /my-account

### Theme ###

Name: Storefront Child
Version: 2.1.0.1476111885
Author URL: https://woocommerce.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/archive-product.php
storefront-child/woocommerce/content-product.php
storefront-child/woocommerce/emails/admin-new-order.php

### CyberSource SA SOP ###

Environment: Live
Debug Mode: Off
`
</details>

**Comment by mikejolley** [comment]
> orderby is not one of date, id, include, title, slug

it tells you what is valid ^ date_modified is not valid.
