### ISSUE TITLE
Changes to the Buyer's company name in the shipping section of checkout are not persisted to the logged in user's profile

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#14768]
### EXPLANATION OF THE ISSUE

A logged in customer's profile is updated with changes entered in the billing and shipping parts of the checkout form with one exception - changes to the company name in the shipping address area are not saved to the logged in customer's profile.

### STEPS TO REPRODUCE THE ISSUE

Observed with today's master

Log in to the store
Add a shippable item to your cart
Proceed to checkout
Select something simple like direct bank transfer for payment method
Enter billing name and address, including something like "115" at the end of each text field
Tick the "Ship to a Different Address" checkbox
Enter shipping name and address, including something like "116" at the end of each text field, including the company name
Click Place order
Go look at your profile (wp-admin > Users > Your Profile)
Note that the "115s" and "116s" appears in all the billing and shipping address fields you entered it on, except for one - the shipping address company will be unchanged

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14781
