### ISSUE TITLE
Array returned by /wp-json/wc/v2/settings/checkout (and a few other groups) contains duplicated items

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#14769]
### EXPLANATION OF THE ISSUE

Doing an authenticated GET on /wc/v2/settings/checkout returns an array with items such as `woocommerce_enable_coupons` repeated multiple times.  Interestingly, the amount of repetition matches the number of sub-tabs visible on the checkout tab (wp-admin/admin.php?page=wc-settings&tab=checkout). If you install a new payment gateway, for example, the amount of repetition increases by 1.

### STEPS TO REPRODUCE THE ISSUE

GET /wp-json/wc/v2/settings/checkout 
Review the array returned, noting the repetition, e.g.:

<img width="974" alt="screen shot 2017-04-27 at 4 35 01 pm" src="https://cloud.githubusercontent.com/assets/1595739/25508558/b4425e66-2b67-11e7-86ec-a5116f3c1db8.png">

```
grep "woocommerce_enable_coupons" foo2.txt
        "id": "woocommerce_enable_coupons",
                    "href": "http://localhost/wc30_us/wp-json/wc/v2/settings/checkout/woocommerce_enable_coupons"
        "id": "woocommerce_enable_coupons",
                    "href": "http://localhost/wc30_us/wp-json/wc/v2/settings/checkout/woocommerce_enable_coupons"
        "id": "woocommerce_enable_coupons",
                    "href": "http://localhost/wc30_us/wp-json/wc/v2/settings/checkout/woocommerce_enable_coupons"
        "id": "woocommerce_enable_coupons",
                    "href": "http://localhost/wc30_us/wp-json/wc/v2/settings/checkout/woocommerce_enable_coupons"
        "id": "woocommerce_enable_coupons",
                    "href": "http://localhost/wc30_us/wp-json/wc/v2/settings/checkout/woocommerce_enable_coupons"
```

### SYSTEM STATUS

Observed with today's master

**Comment by allendav** [comment]
Looks like this happens for `/wp-json/wc/v2/settings/shipping` `/wp-json/wc/v2/settings/tax` and `/wp-json/wc/v2/settings/api`  too

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/14784
