### ISSUE TITLE
Error Messages in Woocommerce Checkout are all lowercase

### ISSUE THREAD

**Issue by pascalknecht** [woocommerce/woocommerce#14761]
### EXPLANATION OF THE ISSUE

In Woocommerce Checkout the error messages are all lowercase. I would like to have them in uppercase since I am speaking German.

### STEPS TO REPRODUCE THE ISSUE

Use German Translation of Woocommerce

### SYSTEM STATUS

<details>
### WordPress Environment ###

Home URL: http://**
Site URL: http://**
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: nginx/1.10.2
PHP Version: 7.0.17
PHP Post Max Size: 200 MB
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

</details>

The Lines that have changed since the last Woocommerce Version are the following:
![image](https://cloud.githubusercontent.com/assets/8436238/25489159/47ec42e8-2b69-11e7-8107-7284c6632945.png)

Line 603 and 607 in class-wc-checkout.php

**Comment by mikejolley** [comment]
This will be fixed in 3.0.5

**Comment by pascalknecht** [comment]
Ok thank you
