### ISSUE TITLE
Set attributes via api - Bug

### ISSUE THREAD

**Issue by grosssmutttr** [woocommerce/woocommerce#14764]
Hi there,
I created two attributes terms which belong to the attribute "pa_farbe":

name: "white/black" which creates a slug "whiteblack"
name: "white/(black)" which creates a slug "whiteblack-2"
Now when I add a product via the api (v1) with:

$dataProduct = [
            'attributes' => [
                    [
                    'id' => 1,
                    'name' => 'Farbe',
                    'slug' => 'pa_farbe',
                    'visible' => false,
                    'variation' => true,
                    'options' => array("white/(black)")
                ]
            ]
        ];
It tries to add the whiteblack slug instead of the whiteblack-2 slug.
After digging around I think that the api sets the attribute after creating the slug from the given name. Because of that the sent data "white/(black)" becomes whiteblack and not whiteblack-2.

So the api shouldn't create a slug out of the sent data (sanitize_title?) instead it should look after the slug in the already existing attributes.
Something like that:
get_term_by( 'name', $sentApiNameField, 'pa_farbe')->slug

**Comment by mikejolley** [comment]
![2017-04-28 at 14 53](https://cloud.githubusercontent.com/assets/90977/25531917/3a795dca-2c23-11e7-8fc9-f771eec221e6.png)

Using master, and api v2, worked fine. They are set by name.

**Comment by grosssmutttr** [comment]
I'm sad how quickly you close issues.
If you read the post you should have recognized that you must insert both attributes in theme backend so that it adds the slugs "whiteblack" and "whiteblack-2".
After these two attribute terms are available it tries to add the wrong attribute when adding a new product.

I found out that it works fine when using slugs in the api data. So you should adjust the docs so that one uses term slugs instead of term names.

**Comment by mikejolley** [comment]
@grosssmutttr I followed your instructions. I created both attributes before running my test.

If you want issues to be reproduced exactly, give more instructions/the full requests used.

**Comment by grosssmutttr** [comment]
@mikejolley I updated my answer before. I forgot to tell you that I'm speaking about variable product attributes.

**Comment by grosssmutttr** [comment]
```
$dataProduct = [
            'variations' => [
                    [
                    'sku' => '10000010'
                    'regular_price' => $10,
                    'visible' => $prodVisible,
                    'tax_status' => 'taxable',
                    'manage_stock' => true,
                    'stock_quantity' => $stockqty,
                    'attributes' => [
                            [
                            'id' => 1,
                            'option' => 'black/(white)' ----> this is not working!
                        ]
                    ]
                ]
            ]
        ];
```

**Comment by claudiosanches** [comment]
@grosssmutttr not sure what is happening, in your initial report the bug has in the product attributes, you gave a full example:

```php
$dataProduct = [
'attributes' => [
[
'id' => 1,
'name' => 'Farbe',
'slug' => 'pa_farbe',
'visible' => false,
'variation' => true,
'options' => array("white/(black)")
]
]
];
```

But the product now is on variations?

Have you tried the version 2 of the REST API? Now there is an endpoint only for variations.

**Comment by claudiosanches** [comment]
Ohh yeah @grosssmutttr still missing a full example of how you are creating this product, if you are creating variations, ok, but here the other parts of the code.

**Comment by grosssmutttr** [comment]
OK I try to write down the full scenario.
**In the woocommerce/wordpress backend:**
1. Create the attribute called "farbe" (select)
2. Add the two terms "white/black" and "white/(black)" to the attribute "farbe". The created permalinks are "whiteblack" and "whiteblack-2" -> white/(black) must have the slug "whiteblack-2" to reproduce the issue
3. Create a product and set it as variable.

**Via api:**
4. Add the attribute "farbe" and the term "white/(black)" to the created product:
```
$dataProduct = [
            'attributes' => [
                    [
                    'id' => 1,
                    'name' => 'Farbe',
                    'slug' => 'pa_farbe',
                    'visible' => false,
                    'variation' => true,
                    'options' => array('white/(black)')
                ]
            ]
        ];
try {
            $importedProduct = $this->api_client->put('products/' . $productID, $dataProduct);
        } catch (HttpClientException $e) {
            $error_str .= ' add_missing_attributes() - API-ERROR $this->api_client->put("products/" . $productID, $dataProduct) ... ' . PHP_EOL;
            $error_str .= $e->getMessage() . PHP_EOL;
            $this->write_error_log($error_str);
            return false;
        }
```
5. Try to add the variation:
$dataProduct = [
            'variations' => [
                    [
                    'sku' => '10000102',
                    'regular_price' => 11,
                    'visible' => $prodVisible,
                    'tax_status' => 'taxable',
                    'manage_stock' => true,
                    'stock_quantity' => 5,
                    'attributes' => [
                            [
                            'id' => 1,
                            'option' => 'white/(black)'
                        ]
                    ]
                ]
            ]
        ];

**Result:**
The variation is created but the "farbe" isn't set to the expected value 'white/(black)'

**If I do the following for part 4:**
$attrFarbe = get_term_by('name', 'white/(black)', 'pa_farbe')->slug;
$dataProduct = [
            'attributes' => [
                    [
                    'id' => 1,
                    'name' => 'Farbe',
                    'slug' => 'pa_farbe',
                    'visible' => false,
                    'variation' => true,
                    'options' => array($attrFarbe)
                ]
            ]
        ];
**and for step 5:**
$attrFarbe = get_term_by('name', 'white/(black)', 'pa_farbe')->slug;
$dataProduct = [
            'variations' => [
                    [
                    'sku' => '10000102',
                    'regular_price' => 11,
                    'visible' => $prodVisible,
                    'tax_status' => 'taxable',
                    'manage_stock' => true,
                    'stock_quantity' => 5,
                    'attributes' => [
                            [
                            'id' => 1,
                            'option' => $attrFarbe 
                        ]
                    ]
                ]
            ]
        ];

If I use the slug instead of the name everything works as expected.
In my opinion the api grabs the name that is send in the options/option field and calls sanitize_title to create the slug. Unfortunately this doesn't cover the case when there are two similiar attribute terms so it creates automatically "-2" behind the slug.

So best would be to call the following part in the api instead of the sanitize_title part.
get_term_by('name', SENT_ATTRIBUTE_TERM_NAME, SENT_ATTRIBUTE_NAME)->slug;

**Comment by grosssmutttr** [comment]
$dataTerm = [
                'name' => 'Black'
            ];
            try {
                $importedProduct = $this->api_client->post('products/attributes/1/terms', $dataTerm);
            } catch (HttpClientException $e) {
                $pContent = print_r($importData, true);
                $error_str .= ' add_update_variable_product() - API-ERROR $this->api_client->put("products", $dataTerm) ... ' . PHP_EOL;
                $error_str .= $e->getMessage() . PHP_EOL;
                $error_str .= $pContent;
                $this->write_error_log($error_str);
                return;
            }
        }

Now another bug appeared:
If the color 'black' already exists we get this error message:
Error: Dieses Schlagwort mit dem gleichen übergeordneten Schlagwort gibt es bereits. [term_exists]
-> Term already exists with the same parent term? (translation)

So I think adding terms is not case-sensitive as it should be?

**Comment by grosssmutttr** [comment]
Have you had success in reproducing the bug with this example or do you need more details? @mikejolley @claudiosanches
