### ISSUE TITLE
SKU disappeared from front- and backend

### ISSUE THREAD

**Issue by wmcgit** [woocommerce/woocommerce#14765]
Hi, 

I have updated my WooCommerce shop to the newst version and now the SKU has completely disappeared from front- and backend.

I cannot find it anywhere.

Is there any workaround to trigger a SKU-force or something compareable?

Best
WM

**Comment by mikejolley** [comment]
It's on the inventory tab. It's still there; if it's not visible a plugin may be hiding it!
