### ISSUE TITLE
how to pass a unique product image to woocommerce cart andd checkout?

### ISSUE THREAD

**Issue by Andriy-Kulak** [woocommerce/woocommerce#14770]
I have an app built with Javascript/React in which I will direct users to the woocommerce cart and checkout. I will be doing this via a query string like below.

```
myWPwebiste.com/?add-to-cart=1175&variation_id=1184&attribute_pa_size=x
```

However, each of my products is going to have unique printing on it depending on the photo that the user uploads in my react app. So in a hypothetical example, if I was selling a mug, and a customer uploads a photo of their cat, my react app will create a customized photo of the cat on the mug. I store these transformed photos in AWS S3 bucket.

**I am wondering if I can pass this transformed photo URL as a  product_image to each product that is added to cart via the query string like above? Or maybe there are other alternatives?**

In my hypothetical example, I want to pass the customized cat mug photo to the cart so that the customer sees that as the product when the purchase the item. Each customer will upload their own unique photo and create a unique product so putting up a single stock photo will not create a good customer experience for me.

Another option is to create a new product via the below woocommerce API each time a user tries to add an item to cart. This way I will be able to add a new image for every item in cart. However, will this cause any problems? If I make 1,000 or 10,000 sales, I will have just as many unique products floating around in my woocommerce admin panel. Will this cause any issues by any chance?

```
WooCommerce.post('products', data, function(err, data, res) {
  console.log(res);
});
```

Any idea and suggestions are welcome!! Thanks!

**Comment by mikejolley** [comment]
Each thumbnail output in the cart is wrapped in a filter named: `woocommerce_cart_item_thumbnail`

You can code a function on the PHP side to pickup your querystring based image and output it via that.

https://github.com/woocommerce/woocommerce/blob/6b9bd2259fca945d7621f6ccf9f83462f04141fa/templates/cart/cart.php#L68
