### ISSUE TITLE
Woocommerce able to proceed to checkout with weak password 

### ISSUE THREAD

**Issue by jianhao90** [woocommerce/woocommerce#14774]
### EXPLANATION OF THE ISSUE

Wordpress version 4.7.3, Woocommerce version 3.0.4. 

When checking out in woocommerce and wanted to create an account during checkout, but the password field is stated weak and i am still able to proceed to checkout.  If the password is weak then i should not be able to checkout.

**Comment by mikejolley** [comment]
This one is allowed through. We've already gotten enough flak for even _showing_ the password meter there, so we let them through to avoid killing conversions.

We'll look at this again during https://github.com/woocommerce/woocommerce/issues/10672
