### ISSUE TITLE
Cash on Delivery orders considered as paid when placed on WC 3.0

### ISSUE THREAD

**Issue by ragulka** [woocommerce/woocommerce#14775]
Pre 3.0, COD orders were not considered paid in the sense that they did not have the `_paid_date` meta set when placed. This made sense, since technically, the payment would only be made on delivery. As such, the `_paid_date` was never set on COD orders AFAIK, unless an admin manually added it to the DB.

Since 3.0, all orders, regardless of the payment gateway, when moved to `processing` or `completed` [will get a paid date](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order.php#L244-L261) automatically.

This breaks the previous behaviour, and while this may not affect everybody, we have been using the `paid_date` meta when tracking revenue in Mixpanel, Google Analytics Pro and Kissmetrics.

I considered using using `$order->is_paid()`, but this yields the same results, as it [checks for the order status](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order.php#L1246-L1248) and [considers completed and processing orders as being paid](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-order-functions.php#L138-L140), which, however, in case of COD orders in `processing` state is not exactly true.

I currently don't have immediate suggestions at hand, but would love to hear your thoughts on whether this change was intentional (specifically for COD orders), or rather something that slipped through.

**Comment by mikejolley** [comment]
COD, the most regretful gateway :p

Technically, processing = paid in our context. When an order is waiting for payment it should be on-hold,  but it seems folks requested processing for COD so they knew to ship the order.

Open to suggestions.

**Comment by mensmaximus** [comment]
Why not introducing a status selector for the COD (and if you are at it for BACS as well)? Give shop owners the freedom to decide them selves which status an order should have if customers use that payment gateway.

**Comment by ragulka** [comment]
Part of the challenge here is that WooCommerce tries to keep the order, fulfillment and payment statuses in a single order status field. I think Shopify did a rather nice job by [separating these into 3 separate fields](https://help.shopify.com/api/reference/order#index): `status`, `fulfillment_status` and `financial_status`.

While it seems like a more complex approach, it does allow for greater flexibility in cases like this. I know it's not something we can consider at this point, but perhaps might be worth discussing for a  major release (v4).

Another approach I've seen with some financial software is to simply have a flag for the payment status. I.e. `paid: true` - this could be set by a payment gateway or even manually by an admin (for example by clicking on a "Mark as paid" button), or automatically when order is moved to `completed` (since any orders without a payment will never get here).
Thinking about this now - it feels very similar to what WC 3.0 is already doing with the `paid_date` field though... so perhaps gateways could indicate themselves, at which point (status) the order should be considered paid? The default would include `processing` and `completed`, but COD could then override this and only include `completed`.

**Comment by mikejolley** [comment]
Thats mentioned in https://github.com/woocommerce/woocommerce/issues/10071

Have you seen the maybe_set_date_paid method? There is a filterable check there which I assume could be adapted for this?

**Comment by ragulka** [comment]
Thanks for the pointer, didn't notice that topic before. As for the `maybe_set_date_paid` method, I'm assuming you mean leveraging the `woocommerce_payment_complete_order_status` filter used there? That could work, although I did notice the same filter is applied in a [few](https://github.com/woocommerce/woocommerce/blob/9d7403f2a9b86f5dc8782a7c68fa9fd42c29be5b/includes/class-wc-order.php#L733) [other](https://github.com/woocommerce/woocommerce/blob/9d7403f2a9b86f5dc8782a7c68fa9fd42c29be5b/includes/class-wc-order.php#L119) [places](https://github.com/woocommerce/woocommerce/blob/9d7403f2a9b86f5dc8782a7c68fa9fd42c29be5b/includes/data-stores/class-wc-order-data-store-cpt.php#L145) as well.
Glancing through these, it doesn't look like filtering this value would break anything immediately.

Basiscally, something like this in the COD gateway class could work then, right?
```php
add_filter( 'woocommerce_payment_complete_order_status', array( $this, 'payment_complete_order_status' ), 10, 2 );

public function payment_complete_order_status( $status, $order_id ) {

  $order = wc_get_order( $order_id );

  if ( $order->get_payment_method() === $this->id ) {
    $status = 'completed';
  }  

  return $status;
}
```

**Comment by mikejolley** [comment]
I think it would have to be outside of the COD method to work. But something along those lines.

**Comment by stephangroen** [comment]
Somewhat related to this change, the API now considers all COD orders paid. Pre 3.0 COD orders would get paid => false in the API, whereas they now get paid => true. I think this should be considered a breaking change in the API. Software like ours that use this to determine the paid state of the order are getting the wrong information, impacting the invoice cycle when using third party invoicing software.

**Comment by claudiosanches** [comment]
@stephangroen are you talking about WooCommerce REST API?

**Comment by stephangroen** [comment]
@claudiosan Yes, retrieving a WooCommerce order via the REST API. In this case version 3.

**Comment by mikejolley** [comment]
https://woocommercecommunity.slack.com/archives/C4TNYTR28/p1495558043886866
