### ISSUE TITLE
Issues after updating to 2.6.14

### ISSUE THREAD

**Issue by Rubien** [woocommerce/woocommerce#14778]
After updating to 2.6.14 i excperience different issues.

1. Woocommerce is not sending emails. Orderstatus is changed but still noe emails beeing sent. I have installed the Email Log plugin, but it has not registraded any emails. Log empty it says.

2. The packing list does not show order totals and shipping method anymore.

3. It is not possible to send a notification to the customer from the order. A spinning "wheel" appares but nothing happens.

4. when i tick of "Order completed" it switches to a new window showing the text that normaly is beeing sendt on email to customers. 

5. In the Dashboard under "Woocommerce Status" the orders are not beeing added to the monthly revenue.

6. Klarna CHeckout cart is not working 100%. It is no longer in av Frame and products and price is beeing showed in a messy way. Also - if you try to change qty or shipping option nothing happens. 

Any ide what is causing this?

<details>
`
### WordPress Environment ###

WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: nb_NO

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 32 MB
PHP Time Limit: -1
PHP Max Input Vars: 6000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Fjernt innlegg: ✔
Fjernt 'Get': ✔
suhosin.post.max_array_index_length: ❌ 64 - A minimum of 256 is required.
suhosin.post.max_totalname_length: ❌ 256 - A minimum of 65535 is required.
suhosin.post.max_vars: ❌ 1000 - A minimum of 1024 is required.
suhosin.request.max_array_index_length: ❌ 64 - A minimum of 256 is required.
suhosin.request.max_totalname_length: ❌ 256 - A minimum of 65535 is required.
suhosin.request.max_vars: ❌ 1000 - A minimum of 1024 is required.

### Database ###

WC Database Version: 2.5.2
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (32) ###

Email Log: av Sudar – 1.9.1
Enhanced E-commerce for Woocommerce store: av Tatvic – 1.0.20
Fiken: av Fiken – 1.4
WooCommerce - Gift Cards: av WP Ronin – 2.5.8
Google AdSense: av Google – 1.2.1
Groups: av itthinx – 2.0.2
WPBakery Visual Composer: av Michael M - WPBakery.com – 5.0.1
MailChimp for WordPress Lite: av ibericode – 2.3.15
Official StatCounter Plugin: av Aodhan Cullen – 2.0.1
PixelYourSite: av PixelYourSite – 5.0.2
Product Catalog Feed Pro by PixelYourSite: av PixelYourSite – 3.1.8
Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 2.2.6
Revolution Slider: av ThemePunch – 4.6.0
Screets Live Chat: av Screets Team – 1.5
User Role Editor: av Vladimir Garagulya – 4.32.3
WooCommerce Dynamic Pricing & Discounts: av RightPress – 1.0.18
Webshipr for WooCommerce: av webshipr.com – 2.4.5
Abandoned Cart Lite for WooCommerce: av Tyche Softwares – 3.7
WooCommerce Cost of Goods: av SkyVerge – 2.3.2
WooCommerce Print Invoice & Delivery Note: av Triggvy Gunderson – 4.1.5
WooCommerce Klarna Gateway: av WooThemes – 2.2.6 – 2.3.6 er tilgjengelig
WooCommerce MailChimp: av Saint Systems – 2.1.0
WooCommerce PDF Invoices & Packing Slips: av Ewout Fernhout – 1.6.5
WooCommerce TradeGecko Integration: av TradeGecko Pte Ltd – 1.7.9
WP All Import - WooCommerce Add-On: av Soflyy – 1.3.3
WooCommerce: av Woothemes – 2.6.14
WooCommerce Helper: av WooCommerce – 1.7.2
Yoast SEO: av Vi i Yoast – 4.6
WP All Export: av Soflyy – 1.1.4
WP All Import: av Soflyy – 3.4.3
WP Staging: av WP-Staging
René Hermenau – 1.1.5

YITH WooCommerce Wishlist: av YITHEMES – 2.1.1

### Settings ###

Force SSL: –
Currency: NOK (kr)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Butikkbase: #4 - /shop
Handlekurv: #5 - /cart
Til kassen: #6 - /checkout
Min konto: #7 - /my-account

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: LEGENDA - 8theme WordPress theme
Version: 3.1
Author URL: http://themeforest.net/user/8theme
Child Theme: ❌ – Hvis du endrer WooCommerce eller et foreldertema du selv ikke bygget
anbefaler vi å bruke et dattertema. Se: Hvordan lage et dattertema

WooCommerce Support: ✔

### Templates ###

Overrides: legenda/woocommerce/archive-product.php
legenda/woocommerce/cart/cart-empty.php
legenda/woocommerce/cart/cart-shipping.php
legenda/woocommerce/cart/cart.php
legenda/woocommerce/cart/cross-sells.php
legenda/woocommerce/cart/mini-cart.php
legenda/woocommerce/checkout/form-billing.php
legenda/woocommerce/checkout/form-checkout.php
legenda/woocommerce/checkout/form-coupon.php
legenda/woocommerce/checkout/form-login.php
legenda/woocommerce/checkout/form-shipping.php
legenda/woocommerce/checkout/review-order.php
legenda/woocommerce/content-product.php
legenda/woocommerce/content-product_cat.php
legenda/woocommerce/content-single-product.php
legenda/woocommerce/content-widget-product.php
legenda/woocommerce/global/form-login.php
legenda/woocommerce/global/quantity-input.php
legenda/woocommerce/loop/add-to-cart.php
legenda/woocommerce/loop/loop-end.php
legenda/woocommerce/loop/loop-start.php
legenda/woocommerce/loop/no-products-found.php
legenda/woocommerce/loop/pagination.php
legenda/woocommerce/loop/rating.php
legenda/woocommerce/myaccount/form-edit-address.php
legenda/woocommerce/myaccount/form-login.php
legenda/woocommerce/myaccount/my-account.php
legenda/woocommerce/myaccount/my-downloads.php
legenda/woocommerce/single-product/add-to-cart/external.php
legenda/woocommerce/single-product/add-to-cart/simple.php
legenda/woocommerce/single-product/meta.php
legenda/woocommerce/single-product/product-image.php
legenda/woocommerce/single-product/product-thumbnails.php
legenda/woocommerce/single-product/related.php
legenda/woocommerce/single-product/short-description.php
legenda/woocommerce/single-product/tabs/tabs.php
legenda/woocommerce/single-product/title.php
legenda/woocommerce/single-product/up-sells.php
legenda/woocommerce/single-product-reviews.php
legenda/woocommerce/single-product.php

### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: Eid not set Secret key not set Checkout URL not set
Norway: ✔
Finland: Eid not set Secret key not set Checkout URL not set
Germany: Eid not set Secret key not set Checkout URL not set
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Terms Page: ✔
`
</details>

**Comment by mikejolley** [comment]
If you are seeing conflicts as you describe it's no doubt related to the plugins you are running alongside and you'll need to do your own debugging to work out what.

if mail logs are empty, it means something is blocking the send itself.

Disable other plugins aside from WooCommerce and go from there.

Closing this because Github is not a support channel. Please read the new issue form before posting.
