### ISSUE TITLE
Error 500 after AddToCart

### ISSUE THREAD

**Issue by Armadur** [woocommerce/woocommerce#14779]
After i add product to cart i get Error 500 internal server error, tried with reinstalation of woocommerce  and its default files and theme change, same happened again

screenshots: 
http://prntscr.com/f1sex5
http://prntscr.com/f1sg1r

### STEPS TO REPRODUCE THE ISSUE

rivald.dk
add some product to cart
some of them will be added some of them will cause err 500

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://rivald.dk
Site URL: http://rivald.dk
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

SUHOSIN Installed: –

Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.

### Active Plugins (15) ###

Ajax Search Lite: by Ernest Marcinko – 4.7.3
Kiwi Social Sharing WordPress Plugin: by Macho Themes – 1.0.4
Menu Icons: by Dzikri Aziz – 0.10.2
WPML Multilingual CMS: by OnTheGoSystems – 3.7.0
WooCommerce ePay Payment Solutions Gateway: by ePay – 2.6.6
WooCommerce Multilingual: by OnTheGoSystems – 4.1.2
WooCommerce: by Automattic – 3.0.4
Wordfence Security: by Wordfence – 6.3.7
Yoast SEO: by Team Yoast – 4.6
WP All Export: by Soflyy – 1.1.4
WP All Import: by Soflyy – 3.4.3
WPML Media: by OnTheGoSystems – 2.2.0
WPML String Translation: by OnTheGoSystems – 2.5.3
WPML Translation Management: by OnTheGoSystems – 2.3.0
Elfsight Yottie Lite: by Elfsight – 1.2.0

### WC Pages ###

Shop base: #13497 - /shop/
Cart: #73 - /cart/
Checkout: #74 - /checkout/
My account: ❌ Page ID is set
but the page does not exist

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: sparkling-child/woocommerce/checkout/form-checkout.php
sparkling-child/content-product.php
sparkling-child/woocommerce/content-single-product.php
sparkling-child/woocommerce/loop/add-to-cart.php
sparkling-child/woocommerce/loop/price.php
sparkling-child/woocommerce/single-product/meta.php

`
</details>

**Comment by mikejolley** [comment]
You need to look at the server PHP logs - it will be a conflict with another plugin and the error message will tell you more. possibly WPML.
