### ISSUE TITLE
Cannot Save Custom Product Data

### ISSUE THREAD

**Issue by ricodjavaweb** [woocommerce/woocommerce#14771]
### EXPLANATION OF THE ISSUE

I made a custom product data, but the product data I created is not stored properly. 
i made videocapture for this: https://www.screencast.com/t/61inGU2iQJkF

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://localhost/adventurademo
Site URL: http://localhost/adventurademo
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.12 PHP/7.1.0 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.1.0
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: IDR (Rp)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
tour (tour)
tours (tours)
variable (variable)
wdm_custom_product (wdm_custom_product)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
That screencast requires flash which I don't want to install.

Custom data needs custom code to manage; we'd need to see that, but seeing as no extension developers have complained I don't think there are any issues in the API. reply back if you want to share what you've used.

**Comment by ricodjavaweb** [comment]
hi mike, thanks for your response.
i reupload videocapture with this link: https://vimeo.com/215786987
hope that helps.

**Comment by mikejolley** [comment]
@ricodjavaweb can you add that code in a gist?

**Comment by ricodjavaweb** [comment]
hi mike, this is the gist 
https://gist.github.com/ricodjavaweb/4140545bbe0c15337fb37cb12b82133d

thanks

**Comment by mikejolley** [comment]
Try with 3.0.5 - there were some meta tweaks.

**Comment by ricodjavaweb** [comment]
Have you seen the full video yet? There is clearly listed WooCommerce that I use is version 3.0.5
http://prntscr.com/f611ae

**Comment by mikejolley** [comment]
It's a long video and mismatches the system status report in your original post, so no.

How much debug/experimenting have you done so far? Have you tried a later priority on woocommerce_process_product_meta so WC saves it's data first (we use priority 10)?
