### ISSUE TITLE
pa_ slug removed in attribute archives

### ISSUE THREAD

**Issue by ilcava** [woocommerce/woocommerce#14773]
### EXPLANATION OF THE ISSUE

In the woocommerce 3.0.4 I note that the attributes archive have lost the "pa_" word in the slug of link.
This cause a 404 error in all my indexed pages with "pa_" slug.

### STEPS TO REPRODUCE THE ISSUE

I update the woocommerce to 3.0.4. I go to frontend and digit www.namesite.com/pa_nameattribute
Return 404 error page

### SYSTEM STATUS

I return my site to woocommerce 2.x.x because I may lost my index page ranking

**Comment by kevin25** [comment]
You're right. I got a lot of 404 on my shop.
![screen shot 2017-04-28 at 4 16 24 am](https://cloud.githubusercontent.com/assets/2909982/25521595/3d8ee8e0-2bce-11e7-8bea-abf74d016617.png)

![screen shot 2017-04-28 at 4 50 59 am](https://cloud.githubusercontent.com/assets/2909982/25521605/4e6b3c2c-2bce-11e7-8f39-e14795cda6c2.png)

**Comment by mikejolley** [comment]
Looks like this change slipped through the cracks; it shouldn't be reverted now because it's done and the prefixless URLs are better in general (pa_ means nothing).

If you prefer a prefix, you can add one via this filter https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-post-types.php#L234

If not, you can setup 301 redirects from the old URLs to the new if you're worried about ranking on those pages. It does not look like this can be done automatically from our side. You can do that in htaccess, via your host, or with a plugin.

Hope that helps.

**Comment by ilcava** [comment]
Ok, but is possible to set an instruction in the funcions.php file?
However If I modify a code when there is an update I must re-modify and re-modify and re-modify.....

**Comment by mensmaximus** [comment]
> It does not look like this can be done automatically from our side. You can do that in htaccess, via your host, or with a plugin.

Maybe I am totally wrong put wouldn't it be possible to populate the terms as well as the 'pa_'.term to the redirect rules?

**Comment by kevin25** [comment]
@mikejolley How to add that one via filter? Functions.php?

> register_taxonomy( $name, apply_filters( "woocommerce_taxonomy_objects_{$name}", array( 'product' ) ), apply_filters( "woocommerce_taxonomy_args_{$name}", $taxonomy_data ) );

**Comment by mikejolley** [comment]
@mensmaximus It's not a term prefix, it's a taxonomy prefix.

@kevin25 The filter would be done per taxonomy. 301 redirects would be better.

**Comment by kevin25** [comment]
@mikejolley I have thousands of those terms.

**Comment by kevin25** [comment]
`add_action('woocommerce_register_taxonomy', 'razorfrog_woo_register_taxonomy');
function razorfrog_woo_register_taxonomy() {
	global $razorfrog_woo_attribute_labels;
	$razorfrog_woo_attributes_labels = array();

	if ( $attribute_taxonomies = wc_get_attribute_taxonomies() ) {
		foreach ( $attribute_taxonomies as $tax ) {
			if ( $name = wc_attribute_taxonomy_name( $tax->attribute_name ) ) {
				$razorfrog_woo_attribute_labels[ $tax->attribute_label ] = $tax->attribute_name;
				add_filter('woocommerce_taxonomy_args_'.$name, 'razorfrog_woo_taxonomy_args');
			}
		}
	}
}

function razorfrog_woo_taxonomy_args($taxonomy_data) {
	global $razorfrog_woo_attribute_labels;
	
	if (isset($taxonomy_data['rewrite']) && is_array($taxonomy_data['rewrite']) && empty($taxonomy_data['rewrite']['slug'])) {
		$taxonomy_data['rewrite']['slug'] = $razorfrog_woo_attribute_labels[ $taxonomy_data['labels']['name'] ];
	}	
	return $taxonomy_data;
}`


Will this remove those pa_ from products?

**Comment by mikejolley** [comment]
301 can have wildcard so you'd only do it for the attribute itself: http://stackoverflow.com/questions/6877486/how-can-i-use-htaccess-to-redirect-paths-with-a-wildcard-character

The code/site you've found is about REMOVING pa_. You want to ADD pa_

**Comment by kevin25** [comment]
The problem is the the string query:

> /pages/?filter_color=

I'm researching how to match it.

**Comment by mikejolley** [comment]
TBH I don't think you should index filters because they are dynamic. Those are not the same as archives.

**Comment by kevin25** [comment]
Any suggestion rule for it?

As i know that the correct url now is /pages/?color=. Right now I have to rewrite all /pages/?filter_color= to /shop instead.

**Comment by mikejolley** [comment]
pages?

I thought you were referring to the archives; e.g. /color/blue /pa_color/blue

**Comment by kevin25** [comment]
Yes, and those urls like this:

> /shop/page/11/?filter_color=deep-red,deep-royal,smoke-grey,ice-gray

**Comment by mikejolley** [comment]
Thats a filter, not an attribute.

**Comment by ilcava** [comment]
ok, sorry but i'm not a developer. I I use a 301 redirect, I can use a single code to redirect all archives pages?
