### ISSUE TITLE
Bug with digital product variation and pdfstamper

### ISSUE THREAD

**Issue by mafrica** [woocommerce/woocommerce#14772]
### EXPLANATION OF THE ISSUE
I am using 3.0.4 and since the upgrade the dashboard hangs when I try and examine a product variation (I have a choice of paper book or a digital product download).

My customers also report that the provided download links no longer work

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
If you're using a pdfstamper extension, and that causes a crash, it's likely conflicting and not tested with 3.0. Inform the developer or see if they have an update available already - we do not maintain it.
