### ISSUE TITLE
Get - List of State using cURL

### ISSUE THREAD

**Issue by hikarushin** [woocommerce/woocommerce#14788]
Hi, I just want to ask if it is possible to get all the list of state using cURL? I want to get the Name of the state `"state": "CA",` in customer data.

**Comment by mikejolley** [comment]
This one is not possible, as we only return the ISO codes. You'd need to convert them on the application side.

**Comment by hikarushin** [comment]
@mikejolley can you please send me a reference?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/tree/master/i18n/states
