### ISSUE TITLE
billing_city label is not changing

### ISSUE THREAD

**Issue by saimonh3** [woocommerce/woocommerce#14782]
### EXPLANATION OF THE ISSUE

I'm using the latest version of woocommerce. I was trying to change the billing_city lable using hook but its not working. But I can easily change all the other fields label.

### STEPS TO REPRODUCE THE ISSUE

add_filter('woocommerce_checkout_fields', function($fields) {

	$fields['billing']['billing_city']['label'] = 'Your City';

	return $fields;
	
});

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

`
### WordPress Environment ###

Home URL: http://localhost/wp
Site URL: http://localhost/wp
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Win64) PHP/7.0.10
PHP Version: 7.0.10
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.50.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (11) ###

Query Monitor: by John Blackbourn – 2.13.4
Better Font Awesome: by MIGHTYminnow & Mickey Kay – 1.6.0
CMB2: by WebDevStudios – 2.2.4
Contact Form 7: by Takayuki Miyoshi – 4.7
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
TD Shortcodes: by Theme Dutch – 1.9.2
Titan Framework: by Benjamin Intal
Gambit – 1.11

TotalPoll Lite: by MisqTech – 3.0.0
WooCommerce: by Automattic – 3.0.4
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #2326 - /cart/
Checkout: #2328 - /checkout/
My account: ❌ Page ID is set
but the page does not exist

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Look in the countries class at the 'locale' fields. Some have one for the locale so it's swapped dynamically.
