### ISSUE TITLE
Please provide a valid email address on multisite

### ISSUE THREAD

**Issue by jarvo1980** [woocommerce/woocommerce#14783]
Using a multi-site install with WooCommerce 3.0.4 and no custom code or plugins in place to alter the checkout process. When you click to pay whether it be BACS, COD or PayPal, it displays the error:

Please provide a valid email address

Yet the email address is correct. I found a similar issue here: https://github.com/woocommerce/woocommerce/issues/14562

I've tried FF and Chrome but still the same issue

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: http://carrotsandpeas.digitalgrowthhub.org.uk
Site URL: http://carrotsandpeas.digitalgrowthhub.org.uk
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: ✔
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.18
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: advFin2016_17_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (18) ###

Gravity Forms PayPal Standard Add-On: by rocketgenius – 2.8
Gravity Forms User Registration Add-On: by rocketgenius – 3.7
Advanced Custom Fields PRO: by Elliot Condon – 5.5.12
Gravity Forms: by rocketgenius – 2.2.1.2
User Activation Keys: by D. Sader – 4.6
Groups: by itthinx – 2.1.1
Groups WooCommerce: by itthinx – 1.9.6
My Page Order: by Andrew Charlton – 3.3.2
WooCommerce: by Automattic – 3.0.4
New Blog Templates: by WPMU DEV – 2.8.3
Adminimize: by Frank Bültge – 1.11.2
Domain Mapping: by WPMU DEV – 4.4.2.4
Cloner: by WPMU DEV – 1.7.5
WPMU DEV Dashboard: by WPMU DEV – 4.3
Erident Custom Login and Dashboard: by Libin V Babu – 3.5.4
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
WooCommerce Subscriptions: by Prospress Inc. – 2.2.2 – 2.2.5 is available
LiteSpeed Cache: by LiteSpeed Technologies – 1.0.15

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /directory-signup/
Basket: #6 - /basket/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: AFFranchise
Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: affranchise/woocommerce/checkout/form-checkout.php
affranchise/woocommerce/checkout/thankyou.php
affranchise/woocommerce/myaccount/view-order.php

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`

If anyone can shed some light, that would be ace!

**Comment by mikejolley** [comment]
Search the closed issues; this is being fixed in 3.0.5

**Comment by jarvo1980** [comment]
Thanks, do you have a date for 3.0.5?

**Comment by mikejolley** [comment]
Soon; I need to catch up with team before deciding.
