### ISSUE TITLE
Review partial missing closing li tag

### ISSUE THREAD

**Issue by chyupa** [woocommerce/woocommerce#14804]
### EXPLANATION OF THE ISSUE

The file used for reviews is missing the closing `</li>` tag: templates/single-product/review.php

**Comment by chyupa** [comment]
I opened a pull request. see #14805

**Comment by claudiulodro** [comment]
[WP automatically adds closing tags](http://stackoverflow.com/questions/19161310/why-does-wordpress-automatically-output-a-closing-li-or-div-tag-at-the-end-of-ea).

[Also see this line at the top of the template file.](https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/review.php#L5) :)
