### ISSUE TITLE
Bug Report: Gravity Forms Product Add-ons on WC 3.0+

### ISSUE THREAD

**Issue by iamrobertchow** [woocommerce/woocommerce#14803]
Environment
WP 4.7.4
WC 3.0.2
Gravity Forms Product Add-ons - WooCommerce: 3.1.8 (released April 25 2017)

My Woocommerce product is calling a Gravity Form using "Gravity Forms Product Add-ons - WooCommerce". The product quantity increment is disabled in the backend for this product [see screenshot below], however, it still shows on the front end

![backend2](https://cloud.githubusercontent.com/assets/28207667/25560040/e8c962e6-2cfd-11e7-9af4-59bb025b6601.PNG)

![quantity2](https://cloud.githubusercontent.com/assets/28207667/25560039/e8c92ee8-2cfd-11e7-9f93-8f4b4df5045a.PNG)

The last environment that didn't have this issue is:

WP: 4.7.3
WC: 2.6.14
Gravity Forms Product Add-ons - WooCommerce: 3.1.6

**Comment by iamrobertchow** [comment]
Update:

I downgraded WC to back to 2.6.14 & Upgraded Gravity Forms Product Add-ons - WooCommerce to 3.1.8 and is working.

So I think the bug has something to do with WC 3.0+

**Comment by mensmaximus** [comment]
For Gravity Forms Product Add-ons you need to open a ticket in your account at woocommerce.com
