### ISSUE TITLE
How to pass custom product attributes to cart via query string

### ISSUE THREAD

**Issue by Andriy-Kulak** [woocommerce/woocommerce#14809]
I have my own front end built with a react.js app because of customizations that I am implementing. I am using woocommerce to keep track of product, cart, checkout and payment processing.

I am passing products from my react app to woocommerce via query string like below. It works well but The custom attribute I am trying to pass will be different for each individual product depending on what images the person uploads to my react.js app. Therefore, I cannot predefine attributes like t-shirt sizes (Small, Medium, Large).

**Query String:**
`https://RadomWPsite.io/cart/?add-to-cart=28587&attribute_selected_image=<custom_attribute_will_go_here>`

Is there a way to pass custom product attributes that will always be unique via query string? Also, can I ensure that these custom attributes prevent the products from grouping in cart like in the image below?

So if I send over 5 separate requests with each diffferent custom attributes (img_src1, img_src2, etc.), they should be separate.

![screen shot 2017-04-30 at 6 33 55 pm](https://cloud.githubusercontent.com/assets/12179976/25568565/9b7b9eba-2dd3-11e7-9c0f-6f6c7bd74d40.png)

**Comment by claudiulodro** [comment]
You can use the `woocommerce_add_to_cart` ajax call to add products to the cart. WooCommerce doesn't have the exact feature you are looking for, so you'll have to build that out either as part of your theme or as an extension plugin for WooCommerce.
