### ISSUE TITLE
Terms and Conditions check box not working with WooCommerce Version 3.0.5

### ISSUE THREAD

**Issue by mohaVocast** [woocommerce/woocommerce#14807]
### EXPLANATION OF THE ISSUE
When you've added a product to the cart and are at the checkout, you are supposed to be able to check off the terms and conditions check box. However with the new update of WooCommerce, the check box is there, but when clicking, no check mark appears. 

In addition to that, you can actually continue and "submit order", without even checking off the check box. That is usually not possible when you have declared a terms and conditions page in the settings. 

### STEPS TO REPRODUCE THE ISSUE

Go to
http://sollens.com/produkt/edgy-solbriller-sort/

Click "Tilføj til kurv" (Means add to cart)

Go to http://sollens.com/check-out/

Fill out some dummy text in the input fields

At the bottom of the page, try to check off "Jeg har læst og accepterer handelsbetingelserne *" (Means: I have read and accept terms and conditions)

It does not check off the box.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://sollens.com
Site URL: http://sollens.com
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_cyh89bfg9p_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (19) ###

Bambora Online ePay: af ePay (en del af Bambora) – 3.0.2
Color Filters for WooCommerce: af Elementous – 1.2.2
Kontakt-widgets: af GoDaddy – 1.4.1
GoDaddy e-mailmarkedsføring: af GoDaddy – 1.2.0
Ippo Widgets: af Themes Kingdom – 1.1
JP Widget Visibility: af JP – 3.9.6
Loco Translate: af Tim Whitlock – 2.0.13
MailChimp: af MailChimp – 1.5.7
Ninja-formularer: af The WP Ninjas – 3.0.34.1
PixelYourSite: af PixelYourSite – 5.0.2
TK Advertising Widget: af ThemesKingdom – 1.1
TK Contact Form: af Themes Kingdom – 1.0
TK Shortcodes: af ThemesKingdom – 2.0
TK Social Share: af Themes Kingdom – 1.1
WooCommerce Product Feed: af WebAppick – 2.0.15
Widget Visibility: af Nico Amarilla – 1.3.1
WooCommerce Google Analytics Integration: af WooThemes – 1.4.0
WooCommerce: af Automattic – 3.0.5
Yoast SEO: af Team Yoast – 4.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop basisside: #790 - /solbriller/
Kurv: #1058 - /kurv/
Checkout: #1056 - /check-out/
Min konto: ❌ Siden er ikke defineret

### Theme ###

Name: Ippo Shop.
Version: 1.0.3
Author URL: http://www.themeskingdom.com
Child Theme: ❌ – Hvis du redigerer WooCommerce i et forældre-tema
som du ikke selv har udviklet
anbefaler vi at du anvender et "børne"-tema. Se: Hvordan du opretter et "Børne"-tema

WooCommerce Support: ✔

### Templates ###

Overrides: ippo-shop/woocommerce/archive-product.php
ippo-shop/woocommerce/cart/cart.php
ippo-shop/woocommerce/content-product.php
ippo-shop/woocommerce/content-single-product.php
ippo-shop/woocommerce/global/sidebar.php
ippo-shop/woocommerce/global/wrapper-end.php
ippo-shop/woocommerce/global/wrapper-start.php
ippo-shop/woocommerce/loop/loop-end.php
ippo-shop/woocommerce/loop/loop-start.php
ippo-shop/woocommerce/loop/pagination.php
ippo-shop/woocommerce/single-product/meta.php
ippo-shop/woocommerce/single-product/price.php
ippo-shop/woocommerce/single-product/product-thumbnails.php
ippo-shop/woocommerce/single-product/rating.php
ippo-shop/woocommerce/single-product.php

`
</details>

**Comment by N3wRa** [comment]
Hi, I have the same issue!

**Comment by claudiosanches** [comment]
I just tested and the issue is in your theme that is replacing the browser checkbox element for new one, and this new need to be fixed.
Talk with the theme author, he/she will be able to fix it for you.

**Comment by N3wRa** [comment]
@mohaVocast I solve the issue by updating some .php file of theme/woocommerce folder that cause conflicts!

**Comment by mohaVocast** [comment]
@N3wRa Which files did you update specifically? And how did you update them?

**Comment by N3wRa** [comment]
personally cart.php and cross-sells.php but i think that depend from Your theme files! If You have a theme status try to check what is too old ( under 2.6 version ) . But remember to keep the old version of .php : in few cases website could go down and You have to restore file via ftp.
Then i force with CSS : 
input[type="checkbox"], input[type="radio"], .woocommerce form .form-row .input-checkbox {
    display: inline;
}

Because the checkbox still had some onclick problems.
Now it run..is not the best thing but better than no checkout actions!

I hope I was helpful

**Comment by Jamman** [comment]
Solved this issue for me by going into Woo settings > checkout > resaving the options.  (I also turned on force SSL for checkout)
That fixed it immediately.
I am on latest Woocomerce and Storefront by Woo.
