### ISSUE TITLE
Store Notice Use Class instead of JS to Show/Hide (Enhancement not Bug)

### ISSUE THREAD

**Issue by wpexplorer** [woocommerce/woocommerce#14801]
Rather than using JS - https://github.com/woocommerce/woocommerce/blob/0f57fa0b502f7cae6298075818c8910bf4ba8ab5/assets/js/frontend/woocommerce.js - to show/hide the store notice which causes a "flash" on load. It wouldn't it be best to use PHP to check for the cookies and add/remove a specific class so the notice is hidden via CSS instead?

Thank you for considering! I'd be happy to create a commit for this if you think it would get pulled.

**Comment by mensmaximus** [comment]
Using jquery has some advantage if it comes to caching plugins. And it is much easier to use local storage in browsers. What kind of 'flash' do you mean?

**Comment by wpexplorer** [comment]
@mensmaximus - You are correct about caching, I did forget about that. Hum..good point. Because it's hidden by default it "pops" in instead of being visible as the site renders. I guess there really isn't a way around that. Having it visible and then disappear would be worse.

Thanks for your input.
