### ISSUE TITLE
Woocommerce Subscription Next Payment Date

### ISSUE THREAD

**Issue by mbrimberry** [woocommerce/woocommerce#14817]
### EXPLANATION OF THE ISSUE
The next payment date is correct in the cart (in this case there is a 30 day free trial then payments come out on the 15th of the month.   When you are in the cart, the next payment date calculates correctly, but at checkout, the date is the next month, regardless of the 30 day free trial and the subscription creates with the next 15th instead of considering the 30 day free trial.

### STEPS TO REPRODUCE THE ISSUE

Choose product to purchase
Verify cart is correct and it shows the correct next payment date (ie:  June 15)
Checkout / Registration - complete information
Redisplay (to enter CC info) shows the incorrect next payment date (ie: May 15)

### SYSTEM STATUS

<details>

`
### WordPress Environment ###

Home URL: http://132.148.90.148/~srlifepresclub
Site URL: http://132.148.90.148/~srlifepresclub
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (20) ###

Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.10
Agent-Custom-SeniorLife-Plugin: by Marcia Brimberry – 1.0
Agent-Registration-Plugin: by Marcia Brimberry – 1.0
Authorize.Net CIM for WooCommerce: by Cardpay Solutions
Inc. – 1.0.3

Code Snippets: by Shea Bunge – 2.8.2
Customize Woocommerce Shop: by RepUPress.com – 6.0
The7 Post Types: by Dream-Theme – 1.2.1
Google Analytics: by ShareThis – 2.1.3
GoToWP Personal: by GoToWP.com – 2.0.4
Font Awesome Icons WP: by Jeff Bullins – 1.0
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Slider Revolution: by ThemePunch – 5.4.3
WooCommerce Checkout Field Editor Pro: by ThemeHiGH – 2.7.4
WooCommerce Memberships: by SkyVerge – 1.8.3 – 1.8.4 is available
WooCommerce Menu Extension: by August Infotech – 1.5
WooCommerce Subscriptions: by Prospress Inc. – 2.2.5
WooCommerce: by Automattic – 3.0.4 – 3.0.5 is available
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
YouTube Embed WpDevArt: by WpDevArt YouTube Embed – 1.9.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1086 - /checkout/
Cart: ❌ Page does not contain the shortcode.
Checkout: #1086 - /checkout/
My account: ❌ Page does not contain the shortcode.

### Theme ###

Name: The7
Version: 5.1.6
Author URL: http://dream-theme.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: dt-the7/woocommerce/cart/cart.php
dt-the7/woocommerce/cart/cross-sells.php
dt-the7/woocommerce/checkout/form-billingxxx.php
dt-the7/woocommerce/checkout/form-checkout.php
dt-the7/woocommerce/checkout/form-coupon.php
dt-the7/woocommerce/checkout/form-login.php
dt-the7/woocommerce/checkout/form-shipping.php
dt-the7/woocommerce/checkout/review-orderxxx.php
dt-the7/woocommerce/checkout/thankyou.php
dt-the7/woocommerce/content-product.php
dt-the7/woocommerce/content-product_cat.php
dt-the7/woocommerce/global/breadcrumb.php
dt-the7/woocommerce/global/form-login.php
dt-the7/woocommerce/global/quantity-input.php
dt-the7/woocommerce/loop/loop-end.php
dt-the7/woocommerce/loop/loop-start.php
dt-the7/woocommerce/loop/orderby.php
dt-the7/woocommerce/loop/pagination.php
dt-the7/woocommerce/myaccount/form-login.php
dt-the7/woocommerce/notices/error.php
dt-the7/woocommerce/notices/notice.php
dt-the7/woocommerce/notices/success.php
dt-the7/woocommerce/order/order-details-customer.php
dt-the7/woocommerce/order/order-details.php
dt-the7/woocommerce/single-product/meta.php
dt-the7/woocommerce/single-product/price.php
dt-the7/woocommerce/single-product/related.php
dt-the7/woocommerce/single-product/up-sells.php

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
</details>

**Comment by claudiulodro** [comment]
Please [submit a support request](https://woocommerce.com/my-account/tickets/) and someone will investigate. The issues area here is just for the WooCommerce core plugin and not associated extensions.
