### ISSUE TITLE
SmallScreen CSS breakpoint 768

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#14813]
Hi 

I have a question where most themes are using css like this

@media only screen and (min-width:768px;) {
}
@media only screen and (max-width:767px;) {
}

Woo decided to have their max-width end at 768px. The smallscreen.css break point is set at 768px causing issues at exactly the 768px breakpoint, As woo is already changing the float of every second element in the shop ul li and removing  margins where themes that use 767px for their responsive css are still using other width dimensions. Especially when we are changing away from the 4 column look of the shop page, related products, upsell products etc.

`			'woocommerce-smallscreen' => array(
				'src'     => str_replace( array( 'http:', 'https:' ), '', WC()->plugin_url() ) . '/assets/css/woocommerce-smallscreen.css',
				'deps'    => 'woocommerce-layout',
				'version' => WC_VERSION,
				'media'   => 'only screen and (max-width: ' . apply_filters( 'woocommerce_style_smallscreen_breakpoint', $breakpoint = '768px' ) . ')'
			),`

Should that 768px not be 767px? As the css it creates =

@media only screen and (max-width:768px;) {
}

Why has this been done so? As most of all the other css even in the prettyPhoto.css woo uses is using 767px as max-width?

What is the reason woocommerce is doing this this way and stepping away from the normal breakpoints most themes use?

looking forward to the explaination.

Note: I know i can change that by a filter. Others seem to have issues as well if i search the internet on this...    http://stackoverflow.com/questions/39612275/change-woocommerce-media-query-breakpoint-to-load-woocommerce-smallscreen-css-at 

But that is not the question i have.

Note : I know ipad portrait mode is exactly 768px. But why is woo not following the normal media query as most themes do?

Thank you !

BackuPs

**Comment by diegocanal** [comment]
I agree with @BackuP, and it is even more curious that in the woo themes (e.g. [storefront](http://demo.woothemes.com/storefront/?_ga=1.261308101.973504238.1493612831)) _**max**-width: 768px_ is not used (it uses _**min**-width: 768px_)...as if this media query –that must be causing trouble to most themes– had been removed/fixed....while the official WooCommerce plugin still uses it.

**Comment by claudiulodro** [comment]
@jameskoster In your opinion, which way is the way to go?

**Comment by diegocanal** [comment]
Also, using the `$media` parameter in `wp_enqueue_style()` function to set media queries forces developers to exclude those enqueued stylesheets from being minified/combined when using caching plugins such as _W3 Total Cache_ –here you have [an example of that kind of issue](https://wordpress.org/support/topic/stylesheets-enqueued-with-media-query-minmax-width-pulled-out/)– instead I think it would be better to hardcode them (media queries) directly in one of the stylesheets.

**Comment by jameskoster** [comment]
768 was the breakpoint we chose so as to serve the 'mobile' layout to iPad portrait. 4 product columns displayed on screens that narrow looks pretty bad;

![bad-layout](https://cldup.com/Q8yCYvQqxL-2000x2000.png)

> But why is woo not following the normal media query as most themes do?

This question should probably be asked the other way around seeing as our CSS was written ~6 years ago xD

Given this is filterable I'm not sure it's necessary that we change it in core. It'd need to go in a major update if we did as it would impact existing WC themes.

> @jameskoster In your opinion, which way is the way to go?

I'm not convinced the argument is strong enough to change core. We offer a way to filter and WooCommerce specific themes should really be working _with_ our css rather than the other way around.

**Comment by claudiulodro** [comment]
Thanks @jameskoster! Good explanation. We'll leave this as-is.

**Comment by BackuPs** [comment]
> WooCommerce specific themes should really be working with our css rather than the other way around.

I disagree on that.   Woocommerce should actually follow what is the common way in css to use and not oppose a breakpoint that is illogical because a 4 col layout does not look ok....

Anyway i will use the filter as i was already doing

Thanks

**Comment by diegocanal** [comment]
>using the $media parameter in wp_enqueue_style() function to set media queries forces developers to exclude those enqueued stylesheets from being minified/combined when using caching plugins such as W3 Total Cache.

@jameskoster what is your opinion about that matter?

> This question should probably be asked the other way around seeing as our CSS was written ~6 years ago xD

I am afraid that "max-width: 768px" was introduced in WooCommerce after version 2.0.20 (I think in 2.1.0) so it was 3 years ago, when plenty of responsive themes, grids and frameworks were already using 767px instead.

> Woocommerce should actually follow what is the common way in css to use and not oppose a breakpoint that is illogical because a 4 col layout does not look ok...

I totally agree with @BackuPs, even more, if the problem was the 4 column layout not looking OK, WooCommerce could have used "max-width: 979px" which was and still is used by most themes.

**Comment by BackuPs** [comment]
@diegocanal  Using max-width 979px is more logical as then themes can override that with their normal css as it is a normal breakpoint and it would also solve the issue for cache plugins.

@jameskoster. How hard is it to write css to go to three columns between 768 and 979 and below 768 to 2 columns? (not really a problem i guess) I dont think it looks fine on a ipad having the two columns either on portrait view. More over for code being there for 6 years (which is actually 3 years) is not a argument not to change it when its using a wrong and not a valid breakpoint.

That being said i will write that css myself to go to 3 columns for all the above columns abilities as themes are using not only the 4 col layout and i will use the filter.

Have a great day !

**Comment by jameskoster** [comment]
> using the $media parameter in wp_enqueue_style() function to set media queries forces developers to exclude those enqueued stylesheets from being minified/combined when using caching plugins such as W3 Total Cache.

Why does it do that? Sorry I'm not too familiar with w3tc. If we were to include the media query in the stylesheet however, folks wouldn't be able to easily change it's behaviour. That's why it is how it is.

To be clear, I'm not opposed to changing our css to provide better layouts. But that is a very different 'issue' to simply changing the current breakpoint. It's not a trivial change - it would have a significant impact on current WC themes and would consequently need to be properly planned and included in a major release.

I'm keen to hear from more theme authors about this. Until then this won't be a priority for us.

**Comment by louisdoe** [comment]
Hi, I just discovered this thread, can someone help me with changing the css breakpoint for small screen with Storefront ? As @diegocanal said, it's `min-width: 768px` but it need it to be `min-width: 769px` so the mobile layout is applied to 768px-wide screens. Thanks for your help

**Comment by BackuPs** [comment]
I think it should be

```
add_filter('woocommerce_style_smallscreen_breakpoint','woo_custom_breakpoint');
function woo_custom_breakpoint($px) {
  $px = '767px';
  return $px;
}
```

**Comment by louisdoe** [comment]
Hi, don't you think it's the filter that is not working ?

**Comment by BackuPs** [comment]
It works fine for me. I added above code in 2017 and since then i have no issues anymore between 768 until 980px as the woo default resposinve css kicks now in below 768 at 767px which is exactly what i needed to make my responsive css between 768 until 980  to work

**Comment by ChrisColotti** [comment]
@BackuPs I just tried this filter today (can't believe I didn't notice the iPad was not forced to mobile) but it's still presenting desktop format using you posted a couple above.

**Comment by ChrisColotti** [comment]
I guess my issue is the "default" in storefront is not even kicking in mobile responsive on a iPad in portait mode....I get it may not in landscape (@1024) but why on earth is it not in mobile mode in portrait it makes the site look like garbages in desktop mode.

**Comment by louisdoe** [comment]
Hey 
I have installed Storefront 2.3.4 and I need to modify the css breakpoints.
I tried the following but it doesn't work.

```
add_filter('woocommerce_style_smallscreen_breakpoint','woo_custom_breakpoint');
function woo_custom_breakpoint($px) {
  $px = '800px';
  return $px;
}
```
Can you help ? I really want to avoid the pain of reprocessing the sass.

**Comment by BackuPs** [comment]
@louisedoe   why do you want to set the bp to 800px?  Its not  a valid screensize for mobile.

Note: It works for me if i test it.  Where did you add the code?

**Comment by louisdoe** [comment]
Hey @BackuPs I added the code in functions.php of my storefront child theme.
It's a special order from a client. 
But the main thing is to get the iPads to show the mobile version.
Can you help me further with this ? I'd like to avoid changing the sass variable and reprocessing the sass.

**Comment by BackuPs** [comment]
Hi Louis

The default woocss is set at breakpoint 768. This means that it kicks in also on ipad portrait mode. Because it is one pixel bigger then 767. So changing your code to 800px does not really do much as it is already working on ipad portrait mode because of the 768px which is the default woo breakpoint. The ipad portrait mode goes until 979px. Landscape mode of the ipad starts at 980px and above.

If you add a skype id i can contact you and we can discuss your problem.

After i have received the id you can remove it again in here and delete your reply.

**Comment by BackuPs** [comment]
Ok there is another catch here.  The storefront/style.css also is loaded and has responsive css set to768px.  What a bummer.  And all the extensions css also has hardcode 768px.  And there is a js file that has 768px set in its code. 

So this cannot be done at all.  

The only way is to de minify all storefront css and change it hardcoded. and upload the changed files into the parent theme,

This is really bad coding from woocommerce !!  Find a better woocommerce theme is my final advice ! I have no solution for you.

**Comment by louisdoe** [comment]
> Hi Louis
> 
> The default woocss is set at breakpoint 768. This means that it kicks in also on ipad portrait mode. Because it is one pixel bigger then 767. So changing your code to 800px does not really do much as it is already working on ipad portrait mode because of the 768px which is the default woo breakpoint. The ipad portrait mode goes until 979px. Landscape mode of the ipad starts at 980px and above.

No, actually the mobile layout displays, by default, from less to 767px up to 767px, then the "desktop" layout kicks in. See the code: 
`@include susy-media (max-width $desktop) {`
whereas what I need is the mobile layout to display up to 800px. But I need the ipad landscape to display the desktop layout.
Hence my need to change this $desktop breakpoint.

> They all have hardcoded 768px !
Actually they SASS, so what I usually do is that I download storefront, modify the scss files (_variables.scss) change the breakpoint value ($desktop : ...), the reprocess everything, and upload it to my site.

Then thing is, it would be great to have hook to do this directly in the functions.php.

Where can I request this feature !! I am not the only one needing this.

**Comment by BackuPs** [comment]
**No, actually the mobile layout displays, by default, from less to 767px up to 767px, then the "desktop" layout kicks in. See the code:
@include susy-media (max-width $desktop) {
whereas what I need is the mobile layout to display up to 800px. But I need the ipad landscape to display the desktop layout.
Hence my need to change this $desktop breakpoint.**

There is no 'susy-media' or $desktop code in the woocommerce storefront theme ! I don't  know where you are finding this code (in what file). We are talking about different things here.

The whole strorefront theme has fixed 768px code. You can get it for free here https://woocommerce.com/storefront/

**Where can I request this feature !! I am not the only one needing this.**

Please ask woocommerce as they developed this theme. I am not developing or selling their themes.

**Comment by BackuPs** [comment]
@jobthomas Correct.  But this means that you will have to repeat it on every update of storefront as the css could have changed.

The suggestion of @louisedoe that it will be implemented the same way as woocommerce has it would be much better. But that is up to the woodev team  who is in control of the storefront theme template.

I dont have any other solutions for @louisedoe other then described before. It is beyond my control.

Signing off from this thread.

Thanks all !

**Comment by louisdoe** [comment]
> But this means that you will have to repeat it on every update of storefront

Exactly, that's the issue. Anywhere we can issue a request for this ?

Thanks

**Comment by jobthomas** [comment]
@BackuPs and @louisdoe - I doubt there's an easy solution for this apart from manually adding the Sass into a child theme and compiling it there.

**Comment by BackuPs** [comment]
@jobthomas  that is whole issue we are talking about.  There should be just like woo itself a breakpoint to load the css and not hardcoded breakpoints.

Anyway we are getting circular here. So this is leading nowhere until the theme developers change their code in the theme.

**Comment by louisdoe** [comment]
yes @jobthomas can you point me to where to discuss this / issue a request ?

**Comment by louisdoe** [comment]
cool thanks

**Comment by louisdoe** [comment]
here it is : https://github.com/woocommerce/storefront/issues/991
