### ISSUE TITLE
REST API Queries

### ISSUE THREAD

**Issue by amjad** [woocommerce/woocommerce#14811]
1. Is it possible to specify which fields should return in API response rather than fetching all keys and values? 
2. Will fetching less fields make the response any faster?
3. How to improve the speed of the REST API response and what affects it? (Currently I get 600ms, I want to make this around 200ms or less.)

**Comment by claudiulodro** [comment]
General questions belong in the [support forums](https://wordpress.org/support/plugin/woocommerce). GitHub issues are only for reporting bugs to the development team.

1 & 2 won't change your response times much if any. 

Your biggest response time gains are going to be:
1. Deactivate plugins that you don't need.
2. Use caching.
3. Better server. This is the main one. You're never going to get 200ms response times on a shared host or server with low memory.

**Comment by amjad** [comment]
I apologize for posting here. Thanks for your reply. How does caching help improve REST API response times? What plugin can help with this?

For better server - do you consider GCP micro with 0.6gb mem and shared cpu powerful or a digital ocean droplet 0.5gb and 1 cpu than a shared hosting server. My customers only use the REST API and dashboard and not the front end at all.

**Comment by mommyme** [comment]
claudiulodro, what type of caching do you recommend? My WooCommerce API calls are so sluggish.  I am using WPEngine and I do have the WPEngine cache turned on, but I just noticed that query_cache_size is 0 and query_cache_type is OFF (for mySQL I believe), and I am wondering if this could be affecting things. Also, are there a list of 'bad' plugins? I am just having the worst time figuring out what is going on and could use any help you can possibly give. Thanks.

**Comment by amjad** [comment]
I moved my site to Digital Ocean. API calls are blazing fast now. I have a heavy multi-site WooCommerce server thousands of orders everyday. I get 160ms now. 80% faster than before.

**Comment by mommyme** [comment]
Who did you use before? I use WPEngine. 

    On Tuesday, May 23, 2017 12:50 AM, Amjad <notifications@github.com> wrote:
 

 I moved my site to Digital Ocean. API calls are blazing fast now. I have a heavy multi-site WooCommerce server thousands of orders everyday. I get 160ms now. 80% faster than before.—

**Comment by amjad** [comment]
Site5 - shared hosting.
