### ISSUE TITLE
Gallery thumbnail alignment issues

### ISSUE THREAD

**Issue by philbearman** [woocommerce/woocommerce#14819]
### EXPLANATION OF THE ISSUE

In version 3.0.5, the gallery thumbnails aren't aligning properly in some circumstances.  I believe this may be because one of my images is taller than the others, and therefore occupies two rows.

I notice in the CSS that every 4th child of the list (`li:nth-child(4n)`) overrides `margin-right`, setting it to zero, but the tall image means that every fourth image isn't necessarily positioned at the end of a row. 

See a screenshot here - I've labelled the 4th, 8th and 12th items - these are the ones receiving the zero margin-right which is causing the layout to look wrong: [http://imgur.com/a/bMhV8](http://imgur.com/a/bMhV8)

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://quebec.xnoc.net/~textinmo
Site URL: http://quebec.xnoc.net/~textinmo
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ❌ Default timezone is Europe/London - it should be UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (16) ###

Head & Footer Code: by Aleksandar Urosevic – 1.0.7
LambertGroup - HTML5 Video Player with Multiple Skins: by Lambert Group – 4.3.3
LambertGroup - HTML5 Video Player with Bottom Playlist and Multiple Skins: by Lambert Group – 4.7.1
PixelYourSite: by PixelYourSite – 5.0.2
VarkTech Pricing Deals for WooCommerce: by Vark – 1.1.7
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Storefront Header Picker: by Wooassist – 1.0.2
The Grid: by Themeone – 2.3.5
Theme Customisations: by WooThemes – 1.0.0
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.4
WooCommerce Custom Product Tabs Lite: by SkyVerge – 1.6.1
WooCommerce EU VAT Compliance (Premium): by David Anderson – 1.11.2
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.1
WooCommerce: by Automattic – 3.0.5
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WP Super Cache: by Automattic – 1.4.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #42 - /shop/
Basket: #6 - /shop/basket/
Checkout: #7 - /shop/checkout/
My account: #8 - /my-account/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/archive-product.php
`
</details>

**Comment by claudiulodro** [comment]
Does this happen for you in other themes, or just Storefront?

**Comment by philbearman** [comment]
That was in Storefront. In Twenty Seventeen it appears like this: http://imgur.com/a/TuFNq

**Comment by mikejolley** [comment]
Fixed in core but @jameskoster will need to do a similar fix in Storefront since it has it's own styling.

**Comment by philbearman** [comment]
Thanks for looking at this and for fixing so quickly Mike.

**Comment by jameskoster** [comment]
@philbearman this shouldn't be happening in Storefront as we force a `clear: both` on the `.first` class. Would you mind opening an issue over [here](https://github.com/woocommerce/storefront) and include a url to your site for me to investigate?

**Comment by philbearman** [comment]
Sure James, will do.
