### ISSUE TITLE
strtolower corrupts Save Order button label

### ISSUE THREAD

**Issue by podkot** [woocommerce/woocommerce#14818]
### EXPLANATION OF THE ISSUE

`class-wc-meta-box-order-actions.php` uses `strtolower( $order_type_object->labels->singular_name )`, which leads to a problem with multibite encodings.

F.e. in ru_RU language, I see `Сохранить �����` label on the save_order button, instead of `Сохранить заказ`

### STEPS TO REPRODUCE THE ISSUE

Using Russian localization, edit an order.

### SYSTEM STATUS

```
WC: 3.0.5
WP: 4.7.4
Language: ru_RU
```

**Comment by claudiosanches** [comment]
We should not use strtolower() there, but still maybe something missing in your server.

See;:

```
wp shell
wp> strtolower( 'заказ' )
=> string(10) "заказ"
wp> mb_strtolower( 'заказ' )
=> string(10) "заказ"
```

**Comment by podkot** [comment]
```
wp> strtolower( 'Заказ' )
string(10) "�����"
wp> mb_strtolower('Заказ')
string(10) "заказ"
wp> exit

$ locale
LANG="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_CTYPE="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_ALL=
```

It's possible to `mbstring.func_overload`, but this feature is [deprecated](http://php.net/manual/en/mbstring.overload.php) and dangerous.

**Comment by claudiosanches** [comment]
@podkot Looks like `mb_strtolower()` solve it, and we already check for it in the System status for "Multibyte string". So will be better for everyone.

Thanks for you feedback.
