### ISSUE TITLE
New zoom function in gallery shows the original image in the background

### ISSUE THREAD

**Issue by el-presidente** [woocommerce/woocommerce#14814]
When the image has a transparent background, when you start to zoom you can see the 'not zoomed' image in the background. I don't know but I think it has appeared in the new 3.0.5

![screen shot 2017-05-01 at 08 36 13](https://cloud.githubusercontent.com/assets/937382/25574884/9c938f5e-2e52-11e7-8695-2735c80c263f.png)

**Comment by el-presidente** [comment]
Tested on macOS 10.12.3 (16D32) and Chrome Version 58.0.3029.81 (64-bit).

Same issue in Safari Version 10.0.3 (12602.4.8):

![screen shot 2017-05-01 at 11 12 14](https://cloud.githubusercontent.com/assets/937382/25576425/23961268-2e5f-11e7-9649-5812d0256a24.png)

**Comment by el-presidente** [comment]
I guess one workaround would be to use JPEGs with a background instead of PNGs..

**Comment by el-presidente** [comment]
https://www.landhave.dk/produkt/land-modern-40-x-120-cm-hoejbede-paa-hjul-50-cm-hoej/

**Comment by claudiulodro** [comment]
[This was fixed in 3.0.4](https://github.com/woocommerce/woocommerce/issues/14515). Which version of WooCommerce are you running, and does this still happen if you use a different theme?

**Comment by claudiulodro** [comment]
Closing this issue in favor of [the one on Storefront](https://github.com/woocommerce/storefront/issues/569).
