### ISSUE TITLE
After 3.0 update, brands plugin duplicating descriptions and removing sort tools

### ISSUE THREAD

**Issue by shawaj** [woocommerce/woocommerce#14812]
After 3.0 update, official WooCommerce Brands plugin duplicating descriptions and removing sort tools.

**Comment by claudiulodro** [comment]
Hi there. Please [leave a ticket](https://woocommerce.com/my-account/tickets/) in the WooCommerce support and someone can investigate it.

**Comment by shawaj** [comment]
It says there to leave any bug reports here! Haha. Which is it?

I've reported it here already so if somebody else needs to know then hopefully you can let them know :-)

Thanks

**Comment by claudiulodro** [comment]
We mean bug reports with the core WooCommerce plugin, not other plugins.

I'll go ahead pass this issue to the appropriate people.  :)

**Comment by claudiulodro** [comment]
@roykho @gedex is this something you're seeing reported for WooCommerce Brands?

**Comment by shawaj** [comment]
@claudiulodro - sorry, I misunderstood the message there. My bad!

It was something that didn't occur before the update and has afterwards so thought it was worth mentioning here.

In any case, I've submitted a ticket about it too.

Thanks for your help
