### ISSUE TITLE
Simple Subscription stuck as simple product

### ISSUE THREAD

**Issue by AmandaMoreSpace** [woocommerce/woocommerce#14810]
### EXPLANATION OF THE ISSUE

Upgraded Woocommerce to most recent version and my subscription product is stuck as a simple product. When I change it and update the simple product to a simple subscription, it immediately reverts back to a simple product. Recovered previous back-up and started getting a white screen with only the letter "g" in the top left corner on all woocommerce pages and was not able to access my site from the back end. Turned off all plugins and updated Woocommerce and can now access the back end again, however, my product is still stuck as a simple product instead of a subscription. Issue persists in a different theme as well. 

### STEPS TO REPRODUCE THE ISSUE

1. upgraded woocommerce, encountered issue
2. recovered back-up, woocommerce crashed 
3.turned off all plugins 
4. upgraded woo commerce 
5. reactivated plugins individually 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```

Home URL:		https://www.ineedmorespace.ca
Site URL:		https://www.ineedmorespace.ca
WC version:		3.0.5
Log directory writable:		 /home/content/a2pewpnas01_data03/14/3891614/html/wp-content/uploads/wc-logs/
WP version:		4.7.4
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		–
WP cron:		
Language:		en_US
Server environment
Server info:		Apache
PHP version:		5.6.27
PHP post max size:		65 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.45.0, OpenSSL/1.0.1e
SUHOSIN installed:		–
MySQL version:		5.6.32
Max upload size:		64 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
WCS_DEBUG:		 No
Subscriptions Mode:		 Live
Database
WC database version:		3.0.5
Database prefix	 	wp_t8rz4pa2rd_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 /home/content/a2pewpnas01_data03/14/3891614/html/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		
Hide errors from visitors		
Active plugins (30)
Nav Menu Roles + WooCommerce Memberships Bridge	 	by Kathy Darling – 1.0.0
Akismet Anti-Spam	 	by Automattic – 3.3
PWS Custom Templates	 	by PWS DTS – 1.1
Beaver Builder Plugin (Agency Version)	 	by The Beaver Builder Team – 1.9.2
PowerPack for Beaver Builder	 	by Team IdeaBox - Beaver Addons – 1.2.3
Ultimate Addon for Beaver Builder	 	by Brainstorm Force – 1.3.1
Blog Designer	 	by Solwin Infotech – 1.7.2.1
Woocommerce order delivery or pickup with date and time	 	by Mrinmoy Dalabar – 1.0.3.1
Google Analytics for WordPress by MonsterInsights	 	by MonsterInsights – 6.1.7
Homepage Control	 	by WooThemes – 2.0.2
Jetpack by WordPress.com	 	by Automattic – 4.8.2
Nav Menu Roles	 	by Kathy Darling – 1.8.6
Ninja Forms	 	by The WP Ninjas – 3.0.34.1
Pharmacy Theme Customizer Pro	 	by Mahdi Yazdani – 1.1.1
Search Engine Visibility	 	by GoDaddy – 0.5
Storefront Mega Menus	 	by WooThemes – 1.3.4 – 1.4.0 is available
Storefront Parallax Hero	 	by WooThemes – 1.5.4
Storefront Powerpack	 	by WooThemes – 1.3.1
Title Toggle for Storefront Theme	 	by Wooassist – 1.2.3
FAQ	 	by Etoile Web Design – 1.5.31
WooCommerce Extra Cost	 	by Multidots – 2.3
WooCommerce Customizer	 	by SkyVerge – 2.4.0
WooCommerce Extra Fee Option	 	by Terry Tsang – 1.0.7
WooCommerce Memberships	 	by WooThemes / SkyVerge – 1.7.1
WooCommerce Product Add-on	 	by nmedia – 2.8
WooCommerce Product Fees	 	by Caleb Burks – 1.2
WooCommerce Software Add-On	 	by WooThemes – 1.6.2
WooCommerce Subscriptions	 	by Prospress Inc. – 2.0.20
WooCommerce	 	by Automattic – 3.0.5
Yoast SEO	 	by Team Yoast – 4.6
Settings
API enabled:		
Force SSL:		
Currency		CAD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), subscription (subscription), variable (variable), variable subscription (variable-subscription)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#51 - /shop/
Cart:		#52 - /myorders/
Checkout:		#53 - /checkout/
My account:		#54 - /my-account/
Theme
Name:		Pharmacy
Version:		2.0.5
Author URL:		https://woocommerce.com
Child theme:		
Parent theme name:		Storefront
Parent theme version:		2.1.8
Parent theme author URL:		https://woocommerce.com/
WooCommerce support:		
Templates
Overrides	 	pharmacy-master/woocommerce/myaccount/dashboard.php
</details>

**Comment by claudiulodro** [comment]
It looks like your version of WooCommerce Subscriptions is out of date. The current version is 2.2.5 and is compatible with WooCommerce 3.0. I believe upgrading to the latest version should solve your issues.
