### ISSUE TITLE
manual order - search variable product via parent SKU

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#14827]
### EXPLANATION OF THE ISSUE

The variations in variable product use parent SKU. When manually creating an order and searching for variable product via SKU, only the parent product shows up, not the variations. (When searching via title, parent and variations show up).

![](http://cld.wthms.co/7G2Q6+)
Link to screenshot: http://cld.wthms.co/7G2Q6

Is it possible to search for the variation via just the parent SKU?

Was brought up in 566345-zd-woothemes

**Comment by mikejolley** [comment]
No this one won't be possible. Doing so would mean either:

a) needing to do some huge queries to find variations with no SKU, but the parent with matching SKU, or
b) storing parent sku to the variation which could lead to duplicates and/or sync issues when updating the parent sku and expecting children to be updated too.

This needs to be looked at with https://github.com/woocommerce/woocommerce/issues/13084 - one thing we do want to do is make setting unique SKUs for all products/variations something mandatory.

Users should for now either set variation SKUs (you can add a suffix for example), or simply add the variable product to the order (with matching sku) and set the line price themselves. 

cc @claudiosanches
