### ISSUE TITLE
My Account Shortcode grid style is not working.

### ISSUE THREAD

**Issue by dineshchouhan** [woocommerce/woocommerce#14828]
### EXPLANATION OF THE ISSUE

When i tried to use `[woocommerce_my_account]` shortcode on a page, then it not showing in grid, you can check in following both screenshots:
On My Account Page: http://bsf.io/3ciwx
On Normal Page using ShortCode: http://bsf.io/2cwp1

### STEPS TO REPRODUCE THE ISSUE

1. Add New Page
2. Add Shortcode `[woocommerce_my_account]` in Page Content

**Comment by claudiulodro** [comment]
It looks good to me in the twentytwelve theme (which doesn't override any WooCommerce styling). What theme are you testing in? My guess is that the theme is not handling the styling correctly.

**Comment by claudiosanches** [comment]
This happens because the "normal page" will not receive the `.woocommerce-account` class in the body.

You can fix it using the WordPress `body_class` filter.
Or just apply your own CSS.
