### ISSUE TITLE
Possible issue with coupons and taxes

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce#14820]
### EXPLANATION OF THE ISSUE

WooCommerce discounts tax besides the actual price of the product and goes over its value. If we create a coupon worth $100 and we have a product worth $100 showing up as $119 due to $19 VAT then upon applying the $100 coupon, it discounts the entire amount and results in Zero payment.

### STEPS TO REPRODUCE THE ISSUE

Here are the settings to show the tax added to the product price:

![](http://cld.wthms.co/1dwlM/3vDi3TKD+)

I create a coupon named "test" with value of 100:
![screen shot 2017-05-01 at 15 42 02 pm](https://cloud.githubusercontent.com/assets/1620929/25580925/bbe98c64-2e84-11e7-8c9d-ae59b3e3bee1.png)

I have a product with value of 100.

Cart before applying coupon:
![screen shot 2017-05-01 at 15 42 33 pm](https://cloud.githubusercontent.com/assets/1620929/25580934/d259d670-2e84-11e7-8b2b-a7c5aa903e06.png)

Cart after applying coupon:
![screen shot 2017-05-01 at 15 43 01 pm](https://cloud.githubusercontent.com/assets/1620929/25580947/dfdca0b6-2e84-11e7-931f-bec112df75b3.png)

Reproduced using latest master.

**Comment by mikejolley** [comment]
@bor0 This one is intentional. Sales tax is based on the amount being paid. If you're paying £0 after discount, VAT on £0 is £0. This is how WC does discounts.
