### ISSUE TITLE
CLI command doesn't return instance_id

### ISSUE THREAD

**Issue by electrokit** [woocommerce/woocommerce#14831]
When creating a shipping zone method in WC CLI, e.g:
wp wc --user=test shipping_zone_method create 6 --method_id=flat_rate --porcelain
With or without the --porcelain flag, the instance_id isn't returned.
The problem is probably in class-wc-cli-rest-command.php:create_item()
This function references $body['id'], which isn't set in the response. 

WooCommerce 3.0.5
WordPress 4.7.4

**Comment by claudiosanches** [comment]
I missed it on REST API, need to remember fix in v3, all objects need to have `id`.
