### ISSUE TITLE
Proceed to checkout Button Border Color Not Properly in twenty-seventeen dark screen.

### ISSUE THREAD

**Issue by maheshprajapati** [woocommerce/woocommerce#14833]
### EXPLANATION OF THE ISSUE

Proceed to checkout Button Border Color Not Properly in the twenty-seventeen dark screen.

### STEPS TO REPRODUCE THE ISSUE

- Select dark color scheme in  twenty-seventeen theme 

T
![cartpagecheckoutbutton](https://cloud.githubusercontent.com/assets/26894056/25616639/a7ab6e02-2f5b-11e7-8b61-7e65e544c01f.PNG)
hen go to the checkout page 

### SYSTEM STATUS

<details>

WordPress environment
Home URL:		http://www.wordpress-test.com
Site URL:		http://www.wordpress-test.com
WC version:		3.0.5
Log directory writable:		 D:\wamp\www\wordpress-test/wp-content/uploads/wc-logs/
WP version:		4.7.4
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		
WP cron:		
Language:		en_US

Server environment
Server info:		Apache/2.4.23 (Win64) PHP/5.6.25
PHP version:		5.6.25
PHP post max size:		250 MB
PHP time limit:		12000
PHP max input vars:		2500
cURL version:		7.50.1, OpenSSL/1.0.1t
SUHOSIN installed:		–
MySQL version:		5.7.14
Max upload size:		250 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:			
</details>

**Comment by claudiosanches** [comment]
@jameskoster Would you like to check this?

**Comment by maheshprajapati** [comment]
Hey @claudiosanches,
If we can Marge this #1c458d4 css then this issue has been resolved.
Thanks

**Comment by maheshprajapati** [comment]
![cart wordpress test](https://cloud.githubusercontent.com/assets/26894056/25648891/2feab542-2fee-11e7-9a80-b0965cd857a9.png)

**Comment by jameskoster** [comment]
@maheshprajapati if you can fix the formatting of your css this looks good.

https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/

**Comment by maheshprajapati** [comment]
@jameskoster sure I will do and create new PR.

**Comment by maheshprajapati** [comment]
@jameskoster I have added latest PR and fix the formatting.

**Comment by jameskoster** [comment]
Good to go @claudiosanches

**Comment by maheshprajapati** [comment]
Thanks @jameskoster
