### ISSUE TITLE
CLI router broken for some commands (2)

### ISSUE THREAD

**Issue by electrokit** [woocommerce/woocommerce#14835]
The following commands are broken in WP CLI:
 wp wc --user=test shipping_zone_method delete 6 3
 wp wc --user=test shipping_zone_method update 6 3
where 6 is a valid zone_id and 3 is an **instance_id**. I haven't looked into this, but i think it's because shipping zone methods doesn't use **id** anymore.

**Comment by claudiosanches** [comment]
Shipping zone methods is a new endpoint.
Closed in favor of #14843
