### ISSUE TITLE
Warning: sprintf(): Too few arguments in wc-admin-help.php on line 208

### ISSUE THREAD

**Issue by jasomdotnet** [woocommerce/woocommerce#14838]
Hi, I have this message in wp-admin also after fresh reinstall (only woocommerce is enabled)

Warning: sprintf(): Too few arguments in wp-content/plugins/woocommerce/includes/admin/class-wc-admin-help.php on line 208

Latest woocommerce + latest wp

**Comment by claudiulodro** [comment]
It looks good to me: https://github.com/woocommerce/woocommerce/blob/3.0.5/includes/admin/class-wc-admin-help.php#L205

sprintf is expecting 2 string arguments and we're providing two strings. Is the site in a language other than American English? Only thing I can think of would be that a translation for the string might be incorrect.

**Comment by claudiosanches** [comment]
@jasomdotnet what language you use in your WordPress installation?

**Comment by jasomdotnet** [comment]
default language of site is slovak sk_SK

**Comment by claudiulodro** [comment]
Looks like it's an issue in the sk_SK translation:

En: `For further assistance with WooCommerce core you can use the <a href=\"%1$s\">community forum<\/a>. If you need help with premium extensions sold by WooCommerce, please <a href=\"%2$s\">use our helpdesk<\/a>.`

Sk: `Pre \u010fal\u0161iu pomoc s WooCommerce jadrom, vyu\u017eite pros\u00edm %1$skomunitn\u00e9 f\u00f3rum%2$s. Ak potrebujete pomoc s pr\u00e9miov\u00fdmi roz\u0161\u00edreniami, ktor\u00e9 pred\u00e1va WooCommerce, %3$svyu\u017eite n\u00e1\u0161 helpdesk%4$s.`

The translated string expects 4 arguments when passed into sprintf. If you make a correct translation of the string, you can submit a new translation at https://translate.wordpress.org/ . I don't speak Slovak, so I can't help much there. :)

**Comment by jasomdotnet** [comment]
Perfect, thanks.

**Comment by filipkotian** [comment]
@jasomdotnet could you please let me know how to fix this? I have the same problem. Many thanks!

**Comment by jasomdotnet** [comment]
prepni an anglicke admin rozhranie a cakaj na update :)

**Comment by oxnxo** [comment]
The default language of my wordpress installation is American English but i'm getting a similar 
error : `Warning: sprintf() [function.sprintf]: Too few arguments in /Applications/AMPPS/www/as/wp-admin/includes/class-bulk-upgrader-skin.php on line 154`
Please help.

**Comment by claudiulodro** [comment]
@oxnxo that error seems to be coming from the WordPress core and not from WooCommerce. You'll have to check the stack trace in the rest of the error message to see which plugin is causing the error.

**Comment by JToward** [comment]
@oxnxo How did you solve the problem? I am getting the same error as @oxnxo during fresh theme installing.

**Comment by WPJobs** [comment]
the same fo me, latest WP 4.8.1, english language, is there any fix please?

**Comment by katrein** [comment]
Same here. Latest WP version 4.8.1, English (South Africa), when installing Superlist theme.

**Comment by cjadeveloper** [comment]
Same Warning: WP 5.2.2 and WooCommerce 3.6.5 version. Linux Ubuntu 19.04. Language: Español (Argentina)

Warning: sprintf(): Too few arguments in /opt/lampp/htdocs/wc/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-help.php on line 48

Warning: sprintf(): Too few arguments in /opt/lampp/htdocs/wc/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-help.php on line 54

**Comment by claudiosanches** [comment]
@cjadeveloper seems like that you need to fix the translations for ES_AR in translate.wordpress.org

**Comment by Skatox** [comment]
Yes, it's happening right now for es-AR

**Comment by GithArtprofile** [comment]
Hi guys, I had this problem, any idea to solve it? It showing on product page. 
Warning: sprintf(): Too few arguments in /web/htdocs/www.xxx.com/home/wp-content/plugins/woocommerce/includes/wc-formatting-functions.php on line 1185

**Comment by GithArtprofile** [comment]
Solved. Was a traduction problem. Tks
/* translators: %s: stock amount */
				$display = sprintf( __( 'Only %s left in stock', 'woocommerce' ), wc_format_stock_quantity_for_display( $stock_amount, $product ) );
			}

**Comment by ShirsSosa** [comment]
¿Cómo lo resolvieron?

**Comment by Skatox** [comment]
@ShirsSosa use a different language for the moment. It's a translation issue. Or translate it by yourself.

**Comment by wl4dig3** [comment]
> ¿Cómo lo resolvieron?

Después de leer varias respuestas. Había una donde apliqué lo siguiente, cambié el idioma Español Chile a solamente Español (ajustes generales), refrésquenles la pagina web y listo, se solucionó así de simple
