### ISSUE TITLE
CSV import suite extremely slow

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/woocommerce#14840]
### EXPLANATION OF THE ISSUE

Since a few days the import of a products CSV is extremely slow. Normally I see the "busybar" 2 or 3 times and then a burst of 20 products. 

### STEPS TO REPRODUCE THE ISSUE

Switched off nearly all plugins

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://speldorado.vandenbussche.nl
Site URL: https://speldorado.vandenbussche.nl
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: shop_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Foutmeldingen zouden niet getoond moeten worden aan bezoekers.

### Active Plugins (9) ###

WooCommerce Customizer: door SkyVerge – 2.4.0
WooCommerce Facturen en Pakbonnen afdrukken: door SkyVerge – 3.2.1
WooCommerce Product Archive Customiser: door jameskoster – 1.0.5
WooCommerce Product CSV Import Suite: door WooCommerce – 1.10.14
Woocommerce Products Slider: door pickplugins – 1.12.7
WooCommerce: door Automattic – 3.0.5
WooCommerce Helper: door WooCommerce – 1.7.2 – Netwerk geactiveerd
WP Maintenance Mode: door Designmodo – 2.0.9
WP Desk Helper: door WP Desk – 1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #5 - /winkel/
Winkelmand: #6 - /winkel/winkelwagen/
Afrekenen: #7 - /winkel/afrekenen/
Mijn account: #9 - /winkel/mijn-account/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een subthema aan. Zie: Hoe maak je een subthema

WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by EgbertJan** [comment]
Aaddition: trying all kind of things. recalculating Terms (in the Tools tab of System Status) takes also extremely much time. That was not before. 
Egbert Jan

**Comment by claudiosanches** [comment]
@EgbertJan hello,
This repository is not a support channel for WooCommerce.com products, if you need support with any product from WooCommerce.com you should contact the properly support in opening a ticket in https://woocommerce.com/my-account/create-a-ticket/
Thanks.

**Comment by EgbertJan** [comment]
I posted it here because the issue emerged when going from WC 3.0.4 to 3.0.5. I reloaded 3.0.4 over 3.0.5 a few minutes ago and all is well again. 3.0.5 broke something with regard to CSV import suite.
Egbert Jan

**Comment by claudiosanches** [comment]
@EgbertJan I understand, still is an issue with a WooCommerce.com product, so better use the ticket system, they will be able to help you properly.

**Comment by EgbertJan** [comment]
will do. Thanks.

**Comment by EgbertJan** [comment]
There is no response in 7 days on the normal ticket queue. I have the feeling that my reported problem is related to #14900 which has PR already.
Thanks, Egbert Jan

**Comment by bradydan** [comment]
@EgbertJan Yes, that is the same issue. The PR has been [merged into master now](https://github.com/woocommerce/woocommerce/pull/14948)
