### ISSUE TITLE
No Price in Rich Snippet for Variable Products

### ISSUE THREAD

**Issue by f3bruary** [woocommerce/woocommerce#14848]
### EXPLANATION OF THE ISSUE

WP: 4.7.4
WC: 3.0.4

The rich snippet schema is not showing prices for variable products. I've tested by copying the schema script in the page source, and testing it in the Google Structured Data Tester. Neither there nor in actual search results on Google do prices for variable products appear. Title and Rating all appear fine. Prices also show for Simple Products. I think it's because for variations you use a different (min/max price) method.

I also tried with the snippet from an actual variation page instead of the parent page (site.com/product/?attribute_pa_size=36). Same result.

I haven't updated to WC 3.0.5 yet but I haven't seen anything in the changelog that could be related to this issue.

FYI, my variable products are shoes. All sizes have the same price so if the issue is the min/max price method, then please include the option to set a single price in the snippet code.

### STEPS TO REPRODUCE THE ISSUE

Add variable product and assign variations. Test the rich snippet at https://search.google.com/structured-data/testing-tool

**Comment by claudiulodro** [comment]
I think we may want to use [AggregateOffer](https://developers.google.com/search/docs/data-types/products#product_information_properties) for Variations. That might make more sense since it has high/low price.

**Comment by mikejolley** [comment]
We use price specification. https://developers.google.com/gmail/markup/reference/types/PriceSpecification

![2017-05-08 at 15 28](https://cloud.githubusercontent.com/assets/90977/25808795/05cf4778-3403-11e7-9d81-0f82b04521be.png)

And in the testing tool:

![2017-05-08 at 15 29](https://cloud.githubusercontent.com/assets/90977/25808839/22d21b8e-3403-11e7-9894-b24c22ab6946.png)

@claudiulodro no bug.

**Comment by f3bruary** [comment]
@mikejolley It's not really a bug. I have a Price/MinPrice/MaxPrice in the snippet and it shows in the testing tool, but the actual prices are not visible in the preview. I only get the rating and availability in the preview (and in actual search results). But for simple products the prices show up just fine.

**Comment by mikejolley** [comment]
Variables don't have a single price which is why it uses specification instead. Looks to be by design. The data is valid.

**Comment by f3bruary** [comment]
That's a shame because the majority of my products are variable, and all variations have the same price.

I can understand that if you sell something based on weight or volume like foods and liquids, then prices can vary, but for shoes and clothing it's usually the same for each size/color...

If you guys don't want to go this direction, then is it possible to disable it completely ? Then I'll just use a plugin to create the desired code.

**Comment by jsmusiker** [comment]
@mikejolley Not to be annoying and bring up a old topic, but this is pretty important to stores I believe. Or at least to stores that get all their traffic organically. I see you fixed this issue  if all variations have the same price, but there are lots of cases where the prices are different for each variation.

A lot of people when using Google look at the price in the Search Results to determine if they are going to click through to the page. There are sites not using WooCommerce that have prices listed in Google, and have multiple variations of a product. I think they just use the lowest price or set a default price and that is what shows in Google. Either way, by not having the price listed it's a disadvantage.

Here is a link to a competitior of ours that has a Price in google and multiple variations of the product. They are not using WooCommerce, but Structued Data is the same regardless of the platiform I believe. https://www.elementvape.com/smok-tfv12-cloud-beast-king-tank

**Comment by mikejolley** [comment]
If you look above there has already been a PR to address this.

**Comment by jsmusiker** [comment]
Hey Mike. Thanks for replying so fast! I thought I only saw a fix if prices are the same. What about if each variation has a different price?

**Comment by f3bruary** [comment]
@jsmusiker Then woocommerce uses the initial method using min/max price. And if I understand correctly, woocommerce has no influence on whether this is actually shown in search results. I think it's google's design.

**Comment by jsmusiker** [comment]
Sorry Mike I didn't see your edited comment when I posted that other comment. 
I understand the data is correct, but since Google isn't showing it maybe there is another way.
What about just assigning the lowest price of the variations then?

**Comment by mikejolley** [comment]
We shown the min and max, which is valid, and picked up by the testing tool.

**Comment by jsmusiker** [comment]
I know it's valid Mike, it's not WC fault. But if Google doesn't show the price maybe something can be edited to make it show? Perhaps assigning the min price as the default price so at least their is something in Google showing up?

**Comment by f3bruary** [comment]
@mikejolley I was under the impression that commit https://github.com/woocommerce/woocommerce/commit/7d956ca797c7e9f6db9448997e74e6dbdbab92c3 would make variable products that have the same price for each variation use a single price instead of a PriceSpecification with min/max price. But I just tested it and it acts the same as before. I'm using WC3.0.7.

**Comment by jsmusiker** [comment]
@f3bruary I think it's scheduled for 3.1. It says it was added to the 3.1 milestone.

**Comment by f3bruary** [comment]
@jsmusiker ah right.

I got some seasonal products that I would prefer to have a price in search results asap. I'll try to apply the changes manually.

**Comment by jsmusiker** [comment]
@f3bruary I wish Mike understood how important this is. For those of us that get almost all of our traffic from Google having the price show up is imperative.

**Comment by mikejolley** [comment]
3.1 is due in June, it's not too far off. Patch manually if you want it now.

**Comment by saulfautley** [comment]
I'm posting here since I don't want to create a duplicate issue...

@mikejolley, I urge you to take a minute to reconsider your implementation of this. You are deliberately using outdated markup and hindering all WooCommerce stores around the world by preventing prices showing on Google results for variable products.

It may seem like your data is valid since the testing tool is not showing any errors, but in fact `priceSpecification` is not a valid property for JSON-LD markup anymore, and it is not even mentioned on the updated [structured data specification for Products](https://developers.google.com/search/docs/data-types/products), nor in the markup examples. This is further reflected by the fact that the Preview feature of the testing tool does not show the price when using `priceSpecification`:

![2017-07-18_113525](https://user-images.githubusercontent.com/2036475/28310662-77a1e2e8-6bad-11e7-900c-e816a2e42518.png)

As well as the live result:

![2017-07-18_113043](https://user-images.githubusercontent.com/2036475/28310703-9e0e9458-6bad-11e7-90cf-81fb43c2cf98.png)

However, after changing the JSON-LD markup to use [`AggregateOffer`](http://schema.org/AggregateOffer) (the recommended and only currently supported method of displaying min-max pricing with JSON-LD):

![2017-07-18_113550](https://user-images.githubusercontent.com/2036475/28310780-d0ca1f34-6bad-11e7-9c9f-4ff285b9e9bb.png)

The fact that the testing tool isn't showing any errors for the current implementation does not change the fact that it does not work and is clearly not supported by Google.

This is not a big code change to make, but it will benefit WooCommerce stores tremendously by allowing them to actually compete with product listings from other stores in Google, rather than looking like none of us know how to implement SEO properly for our products.

**Comment by f3bruary** [comment]
@claudiulodro already suggested this. 

If any changes are made, please keep commit https://github.com/woocommerce/woocommerce/commit/7d956ca797c7e9f6db9448997e74e6dbdbab92c3 because in many cases variations have the same price and I'd rather a single price is showing, than for example "29.99 EUR to 29.99 EUR"

**Comment by mikejolley** [comment]
@saulfautley Send a PR?

**Comment by saulfautley** [comment]
@mikejolley I'm happy to as long as it won't be rejected like the AggregateOffer changes in [#11411](https://github.com/woocommerce/woocommerce/pull/11411) or @claudiulodro's suggestion.

@f3bruary Google is already smart enough to not show a range for the same min/max prices. In this case it will just show `Price: 29.99 EUR`. However to be safe it is probably a good idea to keep that commit anyway.

**Comment by mikejolley** [comment]
@saulfautley If it doesn't work across all cases it will be rejected but you sounded pretty confident it wouldn't.

**Comment by adborges** [comment]
@saulfautley I'm afraid AggregateOffer is meant to use when there are more than one offer from different retailers, as explained in Google Rich Card manuals:

https://developers.google.com/search/docs/data-types/products

> "This page explains how to mark up your product information so that Google can display rich snippets. There are two types of pages where you would typically use this markup:
> 
> a product page that describes a single product
> a shopping aggregator page that lists a single product, along with information about different sellers offering that product"
> 

I think the correct approach is get a foreach done to each one of variables, sending each one as an offer, using the itemOffered property with Product Name + Variable attributes (ie: Ninja Shirt Blue Large) and individual prices, conditions and availability

I've managed to run this manually in the microdata test tool, and got all of it working in Preview, with Reviews, Available AND PRICE RANGE showing good!

**Comment by saulfautley** [comment]
@adborges It's no doubt a bit of a stretch to use AggregateOffer for variable products, but considering some products can have hundreds of variations or more, it's not practical to list an `itemOffered` entry for each one.

It can also be argued that Google's description of AggregateOffer is simply a suggestion of a use-case, but not every use-case for it.

> There are two types of pages where you would **typically** use this markup

> An AggregateOffer is a kind of Offer representing an aggregation of other offers.

^ This description in my opinion matches variable products perfectly.

The preview tool also doesn't complain about any lack of information for "different sellers", which further suggests that Google does not enforce this but rather suggests/recommends it.

But the real proof is in the pudding... I've been using AggregateOffer for variable products on a site for 1-2 weeks and Google has already picked up the pricing without any issue:

![2017-07-30_212434](https://user-images.githubusercontent.com/2036475/28756408-d6101560-756d-11e7-8133-a90944e8d0fb.png)

I have a custom filter to omit the `highPrice` value, but it's still using AggregateOffer nonetheless.

**Comment by adborges** [comment]
@saulfautley 

Yes. If the goal was just to force Rich Snippet to work, I would agree with you. But I understand that we are talking about semantic best practices when it comes to data cataloging here. And knowing that Google also uses this data to relate products, indicate similar products, and also verify / ratify product feed information for the Merchant Center, I think we have to study this better.

We can not forget that in the eCommerce market, an aggregator is a website that aggregates offers from different vendors, by concept, mainly when a unique EAN code is taken into account.

Another factor that made me think, is that if you choose to put the data using Microdata or RFDa, you would markup each variation as an offer, right? Imagining that your theme would show all variations of the product on the same page for the user to choose with a Radio Button, how would you mark each offer using Microdata? Let's forget the LD-JSON for a moment ...

I think if we were to think about AgreggateOffer, I think it would be better to use it to differentiate offers from the same product, but with different forms of payment. For example: Gummy Bear Vape: $ 100 on credit card, or $ 130 with 10 installments of $ 13 using Barclays finance card.

In any case, it's something to think about, is not it? .... I think we need more debate about this, and think outside the box to use this not just to "force" Google to show some Card feature, but also guarantee that data is beeing cataloged the right way, to be prepared for future Google features using this data.

**Comment by saulfautley** [comment]
@mikejolley has already addresses the option of listing each variation:

> Listing all variations is not a solution though; it's too slow. Some stores have too many variations and this would kill loading times.

At this point it's choosing between "forcing" Google to show appropriate pricing, or not having any pricing show at all. My vote is for the former.

Either way it would be great to get some more opinions on this.

**Comment by jsmusiker** [comment]
@saulfautley I'm 100% with you on this. I / my company firmly believes that having some data is better than not having it. It's quite clear that Google is not going to show prices for variable Products that have different prices. This is evidenced by all of our sites not showing price in search results when we have variations with different price points.

There is nothing wrong with "Forcing" Google to show data. After all that's what the Title Tag does, meta description, etc... If something changes in Google then we just adjust accordingly. Nothing is written in stone and code can be changed whenever.

Please continue what you were doing in regards to getting this current code changed.

**Comment by adborges** [comment]
Yes, i think this could be a solution for now. In other hand i think we cannot close question on this, and stop looking for more wider solution for future releases.

**Comment by jsmusiker** [comment]
@adborges 
The image below that @saulfautley previously posted is the exact definition of a variable product in my opinion. If the small variation costs $2.50 & the large variation costs $135.50 that's exactly what the data is showing in the image. Whether it's a short term or long term solution some of us have been waiting for a answer to this for a long time. Any type of improvement should be welcome.

![img_1601](https://user-images.githubusercontent.com/7741647/28756887-6fd62622-7545-11e7-8f61-9513522d450b.PNG)

**Comment by adborges** [comment]
i agree....

**Comment by saulfautley** [comment]
Haha @adborges it's a client's site, and I'm pretty sure they do ship to Brazil - http://vaporvapes.com/

**Comment by susanwinters214** [comment]
If our PRODUCT pages don't have prices - should we code them for "THING" instead? 
This is SO FRUSTRATING that there doesn't seem to be a "solution" (proper way to code) a product page that has no prices. Should we even bother coding using "THING"? Should I even spend time on SCHEMA code if they're not going to make it possible to code Product pages without prices?
