### ISSUE TITLE
Peremalinks not working after update to 3.0.5

### ISSUE THREAD

**Issue by straining** [woocommerce/woocommerce#14859]
### EXPLANATION OF THE ISSUE

I am on WP 4.7.4 and running WC 2.6.14. When I do the update to 3.0.5 and it does the database update after install, I am then not able to access any pages on my site without getting 404 error except the store pages. I have tried to reset all permalinks after upgrade and this still does not work. I am forced to restore the site from backup and everything works again.. Please help! Thank you.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>
`
### WordPress Environment ###

Home URL: https://sctrainingllc.com
Site URL: https://sctrainingllc.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 5.6.30-10+deb.sury.org~xenial+2
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.53 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (29) ###

WP Hide & Security Enhancer: by Nsp Code – 1.4.4.4
Akismet Anti-Spam: by Automattic – 3.3.1
All In One SEO Pack: by Michael Torbert – 2.3.12.5
Autoptimize: by Frank Goossens (futtta) – 2.1.0
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.2.1

Contact Form 7: by Takayuki Miyoshi – 4.7
EWWW Image Optimizer: by Shane Bishop – 3.3.0
Gmail SMTP: by naa986 – 1.1.1
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
Jetpack by WordPress.com: by Automattic – 4.9
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp for WordPress: by ibericode – 4.1.1
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Really Simple SSL: by Rogier Lankhorst – 2.5.13
Slider Revolution: by ThemePunch – 5.4.1
TablePress: by Tobias Bäthge – 1.8
TinyMCE Advanced: by Andrew Ozz – 4.5.6
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

W3 Total Cache: by Frederick Townes – 0.9.5.4
WooCommerce Customizer: by SkyVerge – 2.4.0
WooCommerce Intuit Payments Gateway: by SkyVerge – 2.0.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.1
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
Wordfence Security: by Wordfence – 6.3.8
WP All Import: by Soflyy – 3.4.3
WP Email Template LITE: by a3rev Software – 2.1.4
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP Smush: by WPMU DEV – 2.6.3

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #83 - /shop/
Cart: #84 - /cart/
Checkout: #85 - /checkout/
My Account: #86 - /my-account/

### Taxonomies ###

Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: iFeature Pro 5
Version: 6.0
Author URL: http://www.cyberchimps.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Intuit QBMS ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off
`

**Comment by claudiosanches** [comment]
Have you tried to disable plugins that you have installed and tried to save the permalinks again?

**Comment by LiamMcArthur** [comment]
Have you tried going to **Settings > Permalinks** and hitting save? This has worked for me in the past when permalinks have stopped working.

**Comment by mikejolley** [comment]
In addition to the above, add a prefix for product attributes in settings > permalinks. If you have page titles which conflict with attribute names, this may 404. Page URLs must not conflict with other things like taxonomies or WordPress will 404.
