### ISSUE TITLE
checkout page show notice Notice: Array to string conversion 

### ISSUE THREAD

**Issue by maheshprajapati** [woocommerce/woocommerce#14850]
### EXPLANATION OF THE ISSUE

When empty country selection than its show notice

Notice: Array to string conversion in  \plugins\woocommerce\includes\wc-template-functions.php on line 2039

### STEPS TO REPRODUCE THE ISSUE

1.Enable Debug.
2.Open incognito tab and add the product to the cart then go to checkout page.
3.Its notice show clearly,

### SYSTEM STATUS

<details>
```
WordPress environment
Home URL:		http://www.wordpress-test.com
Site URL:		http://www.wordpress-test.com
WC version:		3.0.5
Log directory writable:		 D:\wamp\www\wordpress-test/wp-content/uploads/wc-logs/
WP version:		4.7.4
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		
WP cron:		
Language:		en_US

```
</details>
![checkoutpage notice](https://cloud.githubusercontent.com/assets/26894056/25662824/8c4c5f4e-3033-11e7-828a-fc6df66a2d74.PNG)

**Comment by maheshprajapati** [comment]
![checkoutpage notice](https://cloud.githubusercontent.com/assets/26894056/25662842/99d40dce-3033-11e7-861e-cbe779f2037b.PNG)

**Comment by claudiosanches** [comment]
Unable to reproduce this issue with the steps that you related.
Have something more that I should to know to reproduce it?

**Comment by maheshprajapati** [comment]
@claudiosanches,

STEPS TO REPRODUCE THE ISSUE:

1)Debug true in wp-config.php

2)In WooCommerce setting save same as attached screenshot.

3)Open private browser tab and add product into cart then go to checkout( make sure you have not selected country)

4)error showing :)
![setting](https://cloud.githubusercontent.com/assets/26894056/25690722/b8fe6e14-30b1-11e7-95ae-15a95200e0a9.PNG)

**Comment by faisal-alvi** [comment]
Hi all,

Agree with @maheshprajapati 

Here is the fix in another way.

Have a look #14868 

Thanks!

**Comment by faisal-alvi** [comment]
Here is the fresh fix with no extra/unnecessary commits.

#14873 

Thanks :)

**Comment by maheshprajapati** [comment]
@claudiosanches this PR #14887 is good solutions :+1:
