### ISSUE TITLE
Product variations can't be edited anymore. 

### ISSUE THREAD

**Issue by eskadesign** [woocommerce/woocommerce#14852]
### EXPLANATION OF THE ISSUE

I have a problem when updating from 2.6.14 to 3.0.5 where the product variations can't be edited anymore. 

See screenshot.
https://www.dropbox.com/s/eaed2iw6tnp3dmr/Clipboard01.jpg?dl=0

### STEPS TO REPRODUCE THE ISSUE

I tried to replicate this on a staging server with an exact copy but I can't replicate the issue. 
I turned off all other plugins but the problem stays. When I downgrade to 2.6.14 all is back to normal.

### SYSTEM STATUS

<details>
### WordPress Environment ###

Home URL: https://www.globalfurniture-elst.nl
Site URL: https://www.globalfurniture-elst.nl
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: shpl_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Shield Security: door iControlWP – 5.8.2
Redux Framework: door Team Redux – 3.6.4
Custom Sidebars Pro: door WPMU DEV – 3.0.5
Developer Mode: door Jesper van Engelen – 0.4.1.3
Google Analytics Dashboard voor WP: door Alin Marcu – 4.9.6.2
WPBakery Visual Composer: door Michael M - WPBakery.com – 5.1.1
MainWP Child: door MainWP – 3.3
Mammoth Mega Submenu: door aislin – 1.0.0
Menu Icons: door Dzikri Aziz – 0.10.2
Meta Slider - Pro Addon Pack: door Matcha Labs – 2.6.8
Meta Slider: door Matcha Labs – 3.5.1
Mollie Payments for WooCommerce: door Mollie – 2.5.4
Really Simple SSL: door Rogier Lankhorst – 2.5.13
WPML Multilingual CMS: door OnTheGoSystems – 3.7.0
SW Responsive Slider Widget: door smartaddons.com – 1.0
SW Core: door smartaddons.com – 1.1.0
Sw Woocommerce: door Smartaddons – 1.1.0
TinyMCE Advanced: door Andrew Ozz – 4.5.6
User Role Editor: door Vladimir Garagulya – 4.32.3
WooCommerce Availability Notifications: door ThemePlugger – 1.1.5
WooCommerce Multilingual: door OnTheGoSystems – 4.1.2
WooCommerce PDF Invoices: door Bas Elbers – 2.8.1
WooCommerce Sequential Order Numbers: door SkyVerge – 1.8.1
WooCommerce Tab Manager: door SkyVerge – 1.8.0
WooCommerce Table Rate Shipping: door Bolder Elements – 3.6.6
WooCommerce: door Automattic – 3.0.5
WooSwipe: door Dean Oakley
Eric Jinks
BJ CJ – 1.1.6.5

Yoast SEO Premium: door Team Yoast – 4.7
WP Add Custom CSS: door Daniele De Santis – 1.0.1
WP Fastest Cache Premium: door Emre Vona – 1.3.4
WP Fastest Cache: door Emre Vona – 0.8.6.8
WP Hummingbird: door WPMU DEV – 1.4.3
WPML CMS Nav: door OnTheGoSystems – 1.4.20
WPML Media: door OnTheGoSystems – 2.2.0
WPML Sticky Links: door OnTheGoSystems – 1.4.1
WPML String Translation: door OnTheGoSystems – 2.5.3
WPML Translation Management: door OnTheGoSystems – 2.3.0
WPML Widgets: door Jeroen Sormani – 1.0.6
WPMU DEV Dashboard: door WPMU DEV – 4.3
Yoast SEO: WooCommerce: door Team Yoast – 4.7

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
simple (simple-fr)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #10 - /shop/
Winkelmand: #11 - /winkelmand/
Afrekenen: #12 - /afrekenen/
Mijn account: #13 - /mijn-account/

### Theme ###

Name: Furnicom Child Theme
Version: 1.6.0
Author URL: http://flytheme.net/
Child Theme: ✔
Parent Theme Name: Furnicom
Parent Theme Version: 1.6.0
Parent Theme Author URL: http://flytheme.net/
WooCommerce Support: ✔

### Templates ###

Overrides: furnicom-child-theme/woocommerce/archive-product.php
furnicom/woocommerce/cart/cart.php
furnicom/woocommerce/content-product.php
furnicom/woocommerce/content-single-product.php
furnicom/woocommerce/loop/loop-end.php
furnicom/woocommerce/loop/loop-start.php
furnicom/woocommerce/loop/pagination.php
furnicom/woocommerce/loop/price.php
furnicom/woocommerce/loop/rating.php
furnicom/woocommerce/myaccount/form-login.php
furnicom-child-theme/woocommerce/single-product/add-to-cart/grouped.php
furnicom/woocommerce/single-product/add-to-cart/simple.php
furnicom/woocommerce/single-product/meta.php
furnicom/woocommerce/single-product/price.php
furnicom/woocommerce/single-product/product-image.php
furnicom/woocommerce/single-product/product-thumbnails.php
furnicom/woocommerce/single-product/rating.php
furnicom/woocommerce/single-product/share.php
furnicom/woocommerce/single-product/tabs/tabs.php
furnicom/woocommerce/single-product/title.php
furnicom/woocommerce/single-product-reviews.php
furnicom/woocommerce/single-product.php`

</details>

**Comment by f3bruary** [comment]
Could you try disabling and then re-enabling all WPML related plugins, and check again ? Worked for this guy: https://github.com/woocommerce/woocommerce/issues/14103

**Comment by eskadesign** [comment]
Live saver! This worked. But how?

**Comment by claudiosanches** [comment]
@eskadesign because looks like WPML needs update.

**Comment by dmejiasks** [comment]
Hi all, 
Im having the same issue but I dont have WPML plugins installed.. How can I fix this?

Plugins Installed: Active plugins (30)

WooCommerce Related Products Widget	 	by Sell with WP – 1.0.0
Advanced Recent Posts	 	by Eugene Holin – 0.6.14
All-in-One WP Migration	 	by ServMask – 6.43
Black Studio TinyMCE Widget	 	by Black Studio – 2.3.2
Blog Designer	 	by Solwin Infotech – 1.7.2.1
Blog Manager Light	 	by OTWthemes.com – 1.9
Anti-Spam by CleanTalk	 	by СleanTalk – 5.64
Code Snippets	 	by Shea Bunge – 2.8.4
Simple Custom CSS and JS	 	by Diana Burduja – 3.0
Genesis Connect for WooCommerce	 	by StudioPress – 0.9.9
Genesis Featured Page Advanced	 	by Nick Diego – 1.9.3
Genesis Design Palette Pro	 	by Reaktiv Studios – 1.3.20
Genesis Responsive Slider	 	by StudioPress – 0.9.5
Genesis Simple Edits	 	by StudioPress – 2.2.0
Genesis Simple Share	 	by Rainmaker Digital LLC – 1.0.9
Genesis Simple Sidebars	 	by StudioPress – 2.1.0
Lightweight Social Icons	 	by Thomas Usborne – 0.9
Ninja Forms	 	by The WP Ninjas – 3.1.1
Page Builder Sandwich Premium	 	by Gambit Technologies – 2.18
Shopify eCommerce Plugin - Shopping Cart	 	by Shopify – 1.1.8
Simple Photo Gallery	 	by Tips and Tricks HQ, Peter Petreski – v1.8.1
Responsive WordPress Slider - Soliloquy Lite	 	by Soliloquy Team – 2.5.1.3
SumoMe	 	by SumoMe – 1.26
WooCommerce Social Media Share Buttons	 	by Toastie Studio – 1.3.0
WooCommerce	 	by Automattic – 3.0.5
Wordfence Security	 	by Wordfence – 6.3.8
WordPress Importer	 	by wordpressdotorg – 0.6.3
Yoast SEO	 	by Team Yoast – 4.7
WP-Optimize	 	by David Anderson, Ruhani Rabin, Team Updraft – 2.1.1
Youtube Showcase	 	by eMarket Design – 2.6.0

**Comment by f3bruary** [comment]
Have you tried disabling and re-enabling all plugins?

**Comment by dmejiasks** [comment]
Hi @f3bruary, 
In my case the cause of issue was "Blog Manager Light" plugin.
Thank you.
