### ISSUE TITLE
woo commerce translate by loco translate did not translate email.

### ISSUE THREAD

**Issue by itevolution** [woocommerce/woocommerce#14867]
Hi there
I have search the solution more than 3 weeks about Email translate by loco translate plugin but seem in the dark press could you please point me the light to solve this problem.

They all go well to translate woo commerce even first email after customer press order but after I got order when I ran next process it won’t translate for me as you can see in the picture.

Thank you so much for help

![translate](https://cloud.githubusercontent.com/assets/28382942/25692145/91d92202-30ca-11e7-89cf-431c5e22d432.jpg)

**Comment by f3bruary** [comment]
Why not just use the Thai language in WordPress ? Or isn't that available ?

**Comment by itevolution** [comment]
Wordpress available and I did using Thai in  Wordpress also have to use loco translater to convert sting in woocommerce verything seem look fine in woocomerce even first email after customer press an order so then after I got order when I press the next process it not translate for me.

**Comment by claudiulodro** [comment]
Thai translations are also available for WooCommerce, so you don't have to manually translate everything. If you don't have Thai automatically available, you can download it [here](https://translate.wordpress.org/projects/wp-plugins/woocommerce/language-packs). 

That should solve your issue and save you a lot of work. :)
