### ISSUE TITLE
Photoswipe init incorrect

### ISSUE THREAD

**Issue by hoangc7** [woocommerce/woocommerce#14866]
### EXPLANATION OF THE ISSUE

There 2 bugs which are related Photoswipe script in this version:

1. When you click on the zoom icon of any image, the first image always shows up. 

Reason: The "index" option was calculated wrong.

2. When a variation is selected, the first image will be changed. It works correctly. But when you click on the zoom button of the first image, the lightbox show up and the first image is not zoomable.

Reason: With the variable products, the first <img> tag attribute "data-large_image_width" and "data-large_image_height" are wrong when found a variation.

### STEPS TO REPRODUCE THE ISSUE

1. Deactivate all plugins but WooCommerce
2. Activate the default theme: Twenty Seventeen

With the first bug:

1. Select a gallery thumbnail which is not the first one.
2. The main image will change to the selected image.
3. Click on the zoom icon
4. You will see the first image always shows up, not the selected image.

With the second bug:

1. On a variable product, select a correct variation.
2. Then the main image will change when you selected a correct variation.
3. Click on the zoom icon
4. You will see the first image shows up but can't be zoomed. You can slide to next images, they are zoomable. Just the first image are not.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://localhost
Site URL: http://localhost
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.2
PHP Post Max Size: 12 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/1.0.2e

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: dev_6_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

WooCommerce: by Automattic – 3.0.5
Theme Check: by Otto42
pross – 20160523.1

Debug Bar: by wordpressdotorg – 0.8.4
Monster Widget: by Automattic – 0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1252 - /shop/
Cart: #1253 - /cart/
Checkout: #1254 - /checkout/
My account: #1255 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by claudiulodro** [comment]
I'm not able to reproduce these issues on WC 3.0.5 and Twenty Seventeen 1.2. The zooms work great for me. Can you clear your caches and try again?

**Comment by mikejolley** [comment]
Neither of these are broken my side either. Both sound like issues patched before 3.0 launch...so possibly caching as I've not seen it on any other sites either.

**Comment by hoangc7** [comment]
Hi,

I'm sorry for late reply. I tested this problem again with a fresh install:
WC 3.0.5
Twenty Seventeen 1.2
WC Dummy Data imported

And it still happened. This is the record: http://recordit.co/XX1593mUL3

Thanks

**Comment by mikejolley** [comment]
Just looks like the variation image is smaller than the main featured image?

**Comment by hoangc7** [comment]
No, it is not. 

1. This is the demo image which is imported from the dummy-data.xml file. Its dimension is 1000x1000.
2. If you debug it, by adding a listener to event "found_variation" and use console.log to the found variation, you will see properties: variation.image.src_w and variation.image.src_h are wrong. It is the reason why photoSwipe doesn't allow us to zoom that image.

**Comment by hoangc7** [comment]
Or this is an easier way to debug it: http://prntscr.com/f5dztr
You can see 2 attributes "data-large_image_width" and "data-large_image_width" of the first are wrong. They should be 1000.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/796ab0f25766454b60ff8b3e7fc6a1640709bd77/includes/wc-product-functions.php#L710

Uses large.

https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-image.php#L25

Uses full.

So yes there is a difference but it wasn't related to photoswipe init.

**Comment by hoangc7** [comment]
I'm sorry for not explaining it clearly. But, do you think the issue I reported is a bug of WooCommerce. In my opinion, it is a bug.

And I see that difference does relate to PhotoSwipe init:
https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/single-product.js#L212

The attributes "data-large_image_width" and "data-large_image_width" help PhotoSwipe detect what image can be zoom. While the first image of product gallery  (the thumbnail)  uses the image size "large", other images use "full".
