### ISSUE TITLE
Country is missing when shop only ships to one country

### ISSUE THREAD

**Issue by ValeDeOro** [woocommerce/woocommerce#14860]
### EXPLANATION OF THE ISSUE

When your store is based in one country, and only ships to that country, then the country is not explicitly mentioned in the order confirmation.

This can create confusion in cases where the customer "invents" an address (e.g. because they would like to have it shipped elsewhere). 

567909-zd-woothemes

### STEPS TO REPRODUCE THE ISSUE

Example: Ireland

1. Restrict your store to only this country. 

![](http://cld.wthms.co/bIP2u+)
Link to screenshot: http://cld.wthms.co/bIP2u

Under shipping zones, you'll see the same in both shops: Republic of Ireland (or Ireland) is the only place where shipping options are available.

![](http://cld.wthms.co/2p54s+)
Link to screenshot: http://cld.wthms.co/2p54s

In this example, in checkout I tried to use "Barcelona" as shipping address: 

![](http://cld.wthms.co/B1wrw+)
Link to screenshot: http://cld.wthms.co/B1wrw

I had to choose a county (but this depends on the country selected - some countries do not have this). 

I can create the order and pay (because I "invented" a non-existent address), but the confirmation email states very clearly the "correct" county - but no country:

![](http://cld.wthms.co/W6Re8+)
Link to screenshot: http://cld.wthms.co/W6Re8

**Can we add the country of the store to this address field, even though it is already pre-selected in the checkout process?**

**Comment by claudiosanches** [comment]
There is to "Country" fields, maybe some error in the translation?
Since the last one should be the "State",.

For me the result in the email is:

Street name: Via Europa
City: Barcelona
State: Donegal
Country: Ireland

**Comment by claudiosanches** [comment]
I personally don't really see any confusion in it, see that "Country" is already setup as "Ireland", maybe it's missing only a message in this shop saying that only say to Ireland, something that can even be included into the "Terms and conditions" page.

Not to mention that according to the Shipping Zones, any address inside Ireland is a valid address for shipping, so there is nothing wrong with it if you filled the order using an incorrect address.

> Can we add the country of the store to this address field, even though it is already pre-selected in the checkout process?

Not sure why we remove it, even selling to only one place, there is nothing wrong to always include the country.

**Comment by mikejolley** [comment]
Talked to team r/e this. We skip the address for the base country because you don't need to include it on shipping labels domestically. I don't think we need to change core behavior.

**Comment by nathanhere** [comment]
I would have personally loved this feature as well.

**Comment by KoolPal** [comment]
While everyone can debate about this, I believe all should have a choice rather than have opinions thrust upon them.

Use below code in functions.php to override this **feature**:
`add_filter( 'woocommerce_formatted_address_force_country_display', '__return_true' );`

Cheers!

**Comment by nathanhere** [comment]
Bless your soul KoolPal!!!

Cheers,

Nathan

On Dec 27, 2017, at 8:11 AM, KoolPal <notifications@github.com<mailto:notifications@github.com>> wrote:


While everyone can debate about this, I believe all should have a choice rather than have opinions thrust upon them.

Use below code in functions.php to override this feature:
add_filter( 'woocommerce_formatted_address_force_country_display', '__return_true' );

Cheers!
