### ISSUE TITLE
Category archive pagination not working with grouped products after update to 3.0.5

### ISSUE THREAD

**Issue by rpovelones** [woocommerce/woocommerce#14862]
### EXPLANATION OF THE ISSUE

After updating the plugin from 2.6 -> 3.0.5 and running the database update, category pagination seems to be broken. The issue appears to be related to grouped products. I have deactivated all plugins except WooCommerce and switched to the TwentySixteen theme to debug and still the same issue.

*BEFORE* This is what the category page looks like with WC v2.6.14. Notice how there are 2 pages and the "showing" text says "Showing 1-12 of 15 results". Note that the products shown here are mostly grouped products.

![screen shot 2017-05-03 at 4 13 08 pm](https://cloud.githubusercontent.com/assets/3476825/25680935/7b20adaa-3020-11e7-92a1-a1d8079a6277.png)

*AFTER* This is now what the category page looks like after the update to WC v3.0.5. Notice now there are 9 pages of results and we are seeing "Showing 1-12 of 103 results".

![screen shot 2017-05-03 at 4 07 06 pm](https://cloud.githubusercontent.com/assets/3476825/25681016/d164dfa6-3020-11e7-941e-fcf79fb7887e.png)

Then page 2 is blank:

![screen shot 2017-05-03 at 4 07 24 pm](https://cloud.githubusercontent.com/assets/3476825/25681027/dc6f4f94-3020-11e7-9115-1f01196c0955.png)

And the last page has a bunch of results on it:

![screen shot 2017-05-03 at 4 07 37 pm](https://cloud.githubusercontent.com/assets/3476825/25681044/ee1cacfa-3020-11e7-9064-a0df464091ee.png)

Not sure what is going on here but I believe this is a bug in the plugin. Can someone please advise how to remedy this and/or if this is in the works to get patched? 

Thanks in advance for your help!
--Robert

### STEPS TO REPRODUCE THE ISSUE

Create a grouped product and try to view on a category archive page.

### SYSTEM STATUS

<details>
```
### WordPress Environment ###

Home URL: http://apr.dev
Site URL: http://apr.dev
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: apr_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)


### WC Pages ###

Shop base: #8 - /rental-catalog/
Cart: #178 - /wishlist/
Checkout: #179 - /checkout/
My account: #180 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by hellerbenjamin** [comment]
I cannot reproduce on a blank theme, and fresh Woocommerce install.  Do you have an online instance of this?

**Comment by rpovelones** [comment]
Hi, thanks for the quick reply. Yeah, the live site is http://americanpartyrentals.com/product-category/dinnerware/china-patterns/.

**Comment by claudiosanches** [comment]
Not able to reproduce it, maybe you skipped the upgrade button.
Still have you disabled every plugin, one by one, checking if something changes?
Have you tried with other theme?

**Comment by hellerbenjamin** [comment]
I have had a similar issue before, I'm trying to remember for sure, but I believe it was a plugin issue.

**Comment by mikejolley** [comment]
```
Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)
```

You have duplicates, not sure why, but they need to be removed. Could be due to upgrades/downgrades.

Make this true: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-post-types.php#L72

Go to products > product visibility. Remove all duplicate terms.

That will resolve it.

**Comment by rpovelones** [comment]
Thanks guys. I believe the issue was with the way that categories are handled for grouped products. It appeared as though the grouped products were displaying on the category archive page but as simply blank placeholders. Removing the category from the product that was part of the main group seems to have solved the issue. Seems to only be an issue after the upgrade.

I'll keep @mikejolley's recommendation in the back pocket in case I need it. 

Thanks again! Great plugin!
--Robert
