### ISSUE TITLE
Bulk variation popups stop working if browser prevents future popups

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#14863]
### EXPLANATION OF THE ISSUE

After disabling future popups from site by the browser, bulk variation editing (like setting price) no longer is able to show a popup, so prices aren't set.  

WC3.0.5 (and presumably applies to earlier versions too). Also using Windows Chrome browser. 

### STEPS TO REPRODUCE THE ISSUE

If you do something like "create variations from all attributes" in the bulk variation options, Chrome will show a message asking if you'd like to prevent this site from creating future popup messages. 

![disable future popups](https://cloud.githubusercontent.com/assets/507025/25681756/15b1ad8e-301b-11e7-97bd-ff7c6a77812e.png)

If you click yes, the variations are created successfully. But if you then try to "set regular prices" (or other options requiring a popup) the popup doesn't load and the ajax action for `bulk_edit_variations()` is triggered without the needed data.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.sandbox.dev
Site URL: http://www.sandbox.dev
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.5.24
PHP Version: ❌ 5.5.24 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.40.0
OpenSSL/1.0.1l

SUHOSIN Installed: –
MySQL Version: 5.6.24
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (16) ###

Airplane Mode: by Andrew Norcross – 0.1.2
KIA Subtitle: by Kathy Darling – 1.6.6
MailChimp Bulk Signup Form shortcode: by Kathy Darling – 0.1.0
Nav Menu Roles: by Kathy Darling – 1.8.6
Plugin Toggle: by Cedaro – 1.3.1
String Locator: by Clorith – 2.1.2
Puppy Age Custom Product Field: by Kathy Darling – 1.0.0
WooCommerce Shipping Contact: by Kathy Darling – 1.1.0
WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0
WooCommerce Free Gift Coupons: by Kathy Darling – 1.2.1
WooCommerce Stripe Gateway: by WooCommerce – 3.1.7
WooCommerce Mix and Match: by WooThemes – 1.2.2
WooCommerce Name Your Price: by Kathy Darling – 2.5.4
WooCommerce One Page Checkout: by Prospress Inc. – 1.4.0 – 1.4.1 is available
WooCommerce Subscriptions: by Prospress Inc. – 2.2.5
WooCommerce: by Automattic – 3.1.0-alpha

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: '
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
catalog (catalog)
composite (composite)
custom-catalog (custom-catalog)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
simple_workshop (simple_workshop)
simple-workshop (simple-workshop)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
variable-mix-and-match (variable-mix-and-match)
variable-workshop (variable-workshop)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #103 - /shop/
Cart: #104 - /cart/
Checkout: #105 - /checkout/
My account: #106 - /my-account/

### Theme ###

Name: Twenty Seventeen Child
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ✔
Parent Theme Name: Twenty Seventeen
Parent Theme Version: 1.2
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
</details>

I may be pretty edge case, but could probably be solved with using something else for the modals, like backbone or even the WordPress media modal, in lieu of the `window.alert()` function.

**Comment by claudiosanches** [comment]
Yeah, it's a problem for usability, but should be already part of #13084.
Closing, since is better wait for #13084.

**Comment by helgatheviking** [comment]
Doesn't seem to be talked about there yet, but now that you've referenced it the two issues are linked and this can be improved in the UI overhaul.
