### ISSUE TITLE
REST API /wc/v2/customers fails when email parameter in query contains plus sign.

### ISSUE THREAD

**Issue by trajche** [woocommerce/woocommerce#14878]
### EXPLANATION OF THE ISSUE

When a customer has registered with an email address that has a plus sign in it, such as 'hello+you@gmail.com', we are unable to query that user via the WooCommerce API. Have tried encoding the plus sign, ex. using %2B instead of a +, but it still doesn't work.

### STEPS TO REPRODUCE THE ISSUE

1. Create a customer inside WooCommerce / WordPress that has a '+' (read: plus sign) in their email address.
2. Query the WooCommerce REST API for that customer by email. Example:
https://woocommerceinstall.com/wp-json/wc/v2/customers?email=hello+you@gmail.com
3. Error is returned:
`{
 “code”: “rest_invalid_param”,
 “message”: “Invalid parameter(s): email”,
 “data”: {
   “status”: 400,
   “params”: {
     “email”: “Invalid email address.”
   }
 }
}`

**Comment by claudiosanches** [comment]
I just checked with `%2B` and works just fine.

No to mention that WordPress is who valid the email and not WooCommerce.
This is where this message comes from: https://developer.wordpress.org/reference/functions/rest_validate_value_from_schema/

See my local test:

![screenshot from 2017-05-04 17-55-16](https://cloud.githubusercontent.com/assets/1264099/25724589/ddbe4364-30f2-11e7-9596-240dbd55d4d3.png)

`[]` means that did not found any customer, but still is an valid email.

**Comment by trajche** [comment]
Thanks for the reply @claudiosanches 
Just tested it again and it returns [] no matter if a customer with that email exists or not.
To replicate: Create user that has 'Customer' role with email address that contains a '+' and query it.

Will test with WP API and get back to you - I guess it could be a WP bug.
