### ISSUE TITLE
Featured products resets stock

### ISSUE THREAD

**Issue by Gabemedia** [woocommerce/woocommerce#14876]
### EXPLANATION OF THE ISSUE

I have imported a lot of products from an old shop to a newer shop with over 500 products.
The last imports worked just fine, but now we are getting some weird bugs.

If I feature a product with the star icon, it resets the stock for the products.
I have also created a new test product and tried to feature it and the test product works just fine.

I also can´t delete some of the categories.

I think there is an mysql error. :) My table "postmeta has 5984 pages. 

Any ideas?

### STEPS TO REPRODUCE THE ISSUE

![info](https://cloud.githubusercontent.com/assets/27831562/25699539/f8af5eda-30c3-11e7-8169-59c5f35d3f8c.png)

This screenshot displays as follows. 
"Produkt til test" is the test product and works just fine.
New LAURA CARDIGAN/LEMONADE is set to featured and the stock is now resettet.
NEW LAURA CARDIGAN/DENIM is not set to featured and still has it stock, but will be changed to "not in stock" if I mark it as featured.

UPDATE: This also happens if I change the product picture and then I rename a product.
Did found some errors in a Woo 2.1 - Woo 2.2 with simlar issues on google. But nothing simlar with Woocommerce 3.0.5

![skaermbillede 2017-05-04 kl 12 22 51](https://cloud.githubusercontent.com/assets/27831562/25699658/733d404a-30c4-11e7-8758-4f887af68ac7.png)
This screenshot displays as follows. 
I have marked and confirmed the category to delete. It just keeps showing red and nothing happens. 

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://www.gabemedia.dk/websites/happyhunting
Site URL: http://www.gabemedia.dk/websites/happyhunting
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 32 MB
PHP Time Limit: 240
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Din server har ikke SoapClient klasse aktiveret - nogle gateway plugins
der bruger SOAP
virker muligvis ikke som forventet.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: hh16db
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (13) ###

Ajax Search Lite: af Ernest Marcinko – 4.7.3
boostr fragt modul til WooCommerce: af Boostr – 2.0.10
Divi Booster: af Dan Mossop – 2.4.3
Gabemedia Builder: af Elegant Themes – 2.0.5
Gabemedia Ghoster: af Aspen Grove Studios – 2.1.5
Divi Switch: af divi.space – 2.3.3
Force Regenerate Thumbnails: af Pedro Elsner – 2.0.6
WooThumbs - Awesome Product Imagery: af Iconic – 4.6.2
IEX Integration for WooCommerce: af IEX Integration – 2.2.4.2
Perfect WooCommerce Brands: af Alberto de Vera Sevilla – 1.4.5
SearchWP Live Ajax Search: af Jonathan Christopher – 1.2.0
WooCommerce ePay Payment Solutions Gateway: af ePay – 2.6.6
WooCommerce: af Automattic – 3.0.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
variation (variation)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
rated-5 (rated-5-2)


### WC Pages ###

Shop basisside: #18633 - /webshop/
Kurv: #18982 - /kurv/
Checkout: #18983 - /kasse/
Min konto: #18984 - /min-konto/

### Theme ###

Name: Gabemedia Child Theme
Version: 1.0.0
Author URL: https://www.gabemedia.dk
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.43
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: divi-child/woocommerce/cart/proceed-to-checkout-button.php
```
</details>

**Comment by claudiulodro** [comment]
I'm not able to reproduce this. Everything works like it's supposed to when I try. Have you tried deactivating all other plugins and seeing if the problem still happens? Another thing you could do is use a MYSQL tool or command line to inspect the database and make sure everything looks good there.

**Comment by Gabemedia** [comment]
Hi Claudiulodro.
Yes I have tried to deactivate plugins.. But yeah I think there is a problem in the database.
I am not strong in MYSQL, so have you any ideas? 

I have 100% access to everything on the server, and yes I can a command line if needed. But I don´t know any. :)

**Comment by Gabemedia** [comment]
I have tried now to create a local copy by install a new wordpress site with only woocommerce - wp import - brands running. I still have the same problem after the import on my local site, I think it lies in the variations. The site has 2 "Størrelser" (Sizes). But it worked fine before the last update.

**Comment by mikejolley** [comment]
> Yes I have tried to deactivate plugins.. But yeah I think there is a problem in the database.
I am not strong in MYSQL, so have you any ideas?

If you're leaving any extension active, especially ones not by us, how can you be sure it's not affecting it? Deleting is also working fine my side.

Updating a product to featured will not erase or change any other data. What it may however do is 'correct' invalid data e.g. from a bad import. Saving triggers things like syncing, so if you for example had a variable product where all the children were out of stock, or IT had no stock, the status would change on save (either editing or changing something like featured).

I'd look at the data and product setup instead to confirm this. If it's variable and you're managing stock per variation, make sure stock management is NOT enabled at the product level.

**Comment by Gabemedia** [comment]
Hi @mikejolley
It was indeed the stock management. All products have now been edited with the right stock setting. And everything works fine for now. :) Thank you.
