### ISSUE TITLE
Order search not working

### ISSUE THREAD

**Issue by LiamMcArthur** [woocommerce/woocommerce#14879]
### EXPLANATION OF THE ISSUE

When using the "Search Orders" feature on the orders page, I'd expect orders to be narrowed down to the search terms I use such as name, postcode etc. If I search the surname Green - I would expect any orders that have the word green associated with names, addresses or custom metadata of the order to be listed. Unfortunatley this isn't the case. Nothing changes at all.

After performing this search the URL changes to:

`wp-admin/edit.php?s=Green&post_status=all&post_type=shop_order&action=-1&m=0&_customer_user&paged=1&action2=-1`

To the left of the search function, it then says:

`Search results for “”`

### STEPS TO REPRODUCE THE ISSUE

- Go to WooCommerce > Orders
- On the right hand-side, enter a search term and click "Search orders".

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://insurance.eden-mobility.co.uk
Site URL: https://insurance.eden-mobility.co.uk
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.25 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 50 MB
PHP Time Limit: 10000
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Accelerated Mobile Pages: by Ahmed Kaludi
Mohammed Kaludi – 0.9.48

AMP: by Automattic – 0.4.2
Base URL Shortcode: by Liam McArthur – 1.0.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Eden FAQ: by Liam McArthur – 1.5
Eden Phone Number: by Liam McArthur – 1.0
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.20
Flamingo: by Takayuki Miyoshi – 1.5
Generate Policy Document: by Liam McArthur – 1.0
Google Captcha (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.29
MailChimp for WordPress: by ibericode – 4.1.1
Recent Blog Posts: by Liam McArthur – 1.0.0
SagePay Direct Gateway for WooCommerce: by PatSaTECH – 1.2.5
Scripts-To-Footer: by Joshua David Nelson – 0.6.1
ShiftNav - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.5.1.2

Tawk.to Live Chat: by Tawkto – 0.2.5
W3 Total Cache: by Frederick Townes – 0.9.5.4
Add optgroup support to WooCommerce select form fields: by QWp6t –
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.1.7
WooCommerce - Autocomplete Orders: by Serious Plugins – 1.1.4
WooCommerce Buy Insurance: by Liam McArthur – 1.0.0
WooCommerce Email Template Overrides: by Liam McArthur – 1.0.0
WooCommerce MultiStep Checkout: by Mubashir Iqbal – 2.3.3
WooCommerce: by Automattic – 3.0.5
Wordfence Security: by Wordfence – 6.3.8
Yoast SEO: by Team Yoast – 4.7
WP Crontrol: by John Blackbourn & contributors – 1.5
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP Smush: by WPMU DEV – 2.6.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #22 - /shop/
Basket: #24 - /basket/
Checkout: #26 - /checkout/
My account: #28 - /my-account/

### Theme ###

Name: Eden Mobility
Version: 1.2.0
Author URL: https://www.eden-mobility.co.uk
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: edenmobility/woocommerce/cart/cart-empty.php
eden/woocommerce/checkout/thankyou.php
eden/woocommerce/emails/customer-completed-order.php
eden/woocommerce/emails/email-header.php
eden/woocommerce/notices/error.php
eden/woocommerce/notices/notice.php
eden/woocommerce/notices/success.php

`
</details>

**Comment by claudiulodro** [comment]
I'm not able to reproduce this. The order search is working correctly for me. 

What troubleshooting have you done? Have you deactivated your other plugins and tested again? Does the post search work normally for you?

<img width="1497" alt="screen shot 2017-05-05 at 2 32 26 pm" src="https://cloud.githubusercontent.com/assets/7317227/25765038/b44d513e-319f-11e7-9550-b53697da5485.png">

**Comment by fgl87** [comment]
Since updating above WC3.0 the search function of our client's website is also not working as it should. He uses the search function mainly by putting postal codes in. Currently only new orders are shown in the search results, the older ones from before the update aren't retrievable the same way.

I realize this isn't helping very much because I didn't post any details yet, but I'll get back to this post later.
This might be the same issue the TS is talking about.

Kind regards.

**Comment by LiamMcArthur** [comment]
I disabled every plugin and still had the same problem, but when using another theme - the issue didn't exist, meaning something in my theme is causing this problem.

**Comment by LiamMcArthur** [comment]
It turned out I was using this code (https://wpism.com/disable-the-search-feature-of-wordpress/) to disable search on the front-end. I altered the code to use `!is_admin()` to prevent it affecting order search.

**Comment by kasimkk23** [comment]
I am facing same issue, could someone please help me out to resolve this issue? 
Thanks

**Comment by davewadestein** [comment]
When I disable all plugins except WooCommerce, I still can't search. I get this error:

```
Error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))) AND wp_posts.post_type = 'shop_order' AND ((wp_posts.post_status = 'wc-pend' at line 1]
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts WHERE 1=1 AND wp_posts.ID IN (6150,6210,0) AND ((())) AND wp_posts.post_type = 'shop_order' AND ((wp_posts.post_status = 'wc-pending' OR wp_posts.post_status = 'wc-processing' OR wp_posts.post_status = 'wc-on-hold' OR wp_posts.post_status = 'wc-completed' OR wp_posts.post_status = 'wc-cancelled' OR wp_posts.post_status = 'wc-refunded' OR wp_posts.post_status = 'wc-failed')) ORDER BY wp_posts.post_date DESC LIMIT 0, 20
```

Any ideas?

**Comment by bootleweb** [comment]
Not sure why it's closed. It's a real problem, and here's a plugin that fixes it and explains the reason why: https://wordpress.org/plugins/order-search-repair-for-woocommerce/

Basically, a recent major version of woocommerce (probably 3.0) changed how searching works. That's fine for searching orders since that version, but it can't search orders prior to the update, due to relying on a new database column that it introduced. The plugin above adds the new database column and data to older orders.

**Comment by LiamMcArthur** [comment]
Mine works perfectly since the 3.0 upgrade. Have you tried disabling all plugins one by one and switching to a default theme to eliminate a potential conflict?

**Comment by bootleweb** [comment]
Thanks, please see the link in my comment above. It's a real problem, and there's a real cure. Yes, I had done the standard disabling routine. The search fails for orders placed before the 3.0 upgrade. See also discussion in plugin above. Glad you found a solution in your case - but also check searching for old orders, e.g. by postcode, you might be surprised.

**Comment by dynamicJake** [comment]
@bootleweb, thank you for sharing that plugin. An issue that was marked as closed and is still a problem 2 years later is odd.

I second this issue and it was occurring even after uninstalling all plugins and custom code. The site had orders dating back until 2014 and the orders were not showing when searching by the customer's name (only recent orders from about 2017-present). Even some orders in 2017 were not searchable.

Others will have a hard time finding this plugin and this thread so this should be fixed in WC not offloaded. The plugin hasn't been updated for around 2 years but luckily it worked.

I suggest a deeper look into this issue.

Thank you.

**Comment by Rakeshbakshi** [comment]
$wpdb->prepare(
    "SELECT DISTINCT p1.post_id FROM {$wpdb->postmeta} p1 WHERE p1.meta_value LIKE %s AND p1.meta_key IN ('" . implode( "','", array_map( 'esc_sql', $search_fields ) ) . "')", // @codingStandardsIgnoreLine
                        s . $wpdb->esc_like( wc_clean( $term ) ) . '%'
                    )
                ),

if I replace LIKE TO = then it's fetching the exact order ID for me, otherwise it's not searching correctly as entered ID.
