### ISSUE TITLE
Don't show 'Restock refunded items' when stock management is off 

### ISSUE THREAD

**Issue by freeaanzee** [woocommerce/woocommerce#14888]
I don't think this checkbox should be appearing on the refund screen when woocommerce_manage_stock is set to 'no'. It doesn't cause a problem but it's a bit confusing for shop managers:

![screenshot](https://www.fairtradecrafts.be/wp-content/screens/dont-restock-refunded-items.png)

**Comment by nishitlangaliya** [comment]
@mikejolley , @claudiosanches 

I have made adjustment to fix the issue and done the pr for the same please review it and let me know if any changes required.

PR: https://github.com/woocommerce/woocommerce/pull/15527

Thanks
