### ISSUE TITLE
Pay button for 'on hold' orders that are pending payment.

### ISSUE THREAD

**Issue by decimoseptimo** [woocommerce/woocommerce#14889]
Orders on "pending payment" status show the button. Like when a user chooses paypal at checkout but abandons the paypal website. In that case payment can be re-initiated from `my-account/orders` or even a different payment method can be chosen.

For offline payments like bank transfer, that button is not shown, since those orders are in "on hold" status. So users cannot read again the payment instructions nor change the payment method if they were willing to do so.

**Comment by claudiosanches** [comment]
So should display again the payment instructions. But never the "Pay" button again, since the "pay" button will be confuse for people that already passed by the checkout process.

**Comment by decimoseptimo** [comment]
@claudiosanches Not sure. To me the "pay" button belongs to a default order state where its payment is "yet to be confirmed". It means: "Until we can confirm you have paid us, we'll require you to do so".

It is the nature of offline payments.

**Comment by claudiosanches** [comment]
@decimoseptimo so easy to fix in your end.

You can use this code:

```php
add_action( 'woocommerce_valid_order_statuses_for_payment', function( $statuses, $order ) {
	$statuses[] = 'on-hold';

	return $statuses;
}, 10, 2 );
```

This will solve it for you. Good luck.

**Comment by aaronhong7** [comment]
Hi @claudiosanches, how can we display payment instructions before or after the Order Details Table in the View Orders Page?

I've tried the below snippet, but it doesn't work. Please help me assess where I did wrong:

```
add_action( 'woocommerce_order_details_after_order_table', 'view_order_custom_payment_instruction', 5, 1); // Email notifications
function view_order_custom_payment_instruction( $order ){

    // Only for "on-hold" and "processing" order statuses and on 'view-order' page
    if( in_array( $order->get_status(), array( 'on-hold', 'processing' ) ) && is_wc_endpoint_url( 'view-order' ) ){

        // The "Payment instructions" will be displayed with that:
        do_action( 'woocommerce_thankyou_' . $order->get_payment_method(), $order->get_id() );

    }
}
```

**Comment by Melebius** [comment]
I find this a valid issue and the code by @claudiosanches (https://github.com/woocommerce/woocommerce/issues/14889#issuecomment-299590725) helps partially. Using it, the Pay button is displayed and you can see the instructions again or choose another payment method. However, the behavior of the `Pay for the order` button is a bit misleading if you keep BACS, for example, selected. It directs you to the Order received page saying: “Thank you. Your order has been received.”
