### ISSUE TITLE
Featured products can not be sorted anymore 

### ISSUE THREAD

**Issue by sdevroey** [woocommerce/woocommerce#14883]
### EXPLANATION OF THE ISSUE

After the upgrade to woocommerce 3.0 and consequent upgrades to 3.05 the column for featured products can no longer be sorted anymore. In version 2.7 there was a small triangle next to featured in the product list that would sort the product list to featured or not. After upgrade to 3.05 this is no longer possible. 

#
### SYSTEM STATUS
Tested on twenty-seventeen with all plugins disabled.

<details>

</details>

<!--
`
### WordPress Environment ###

Home URL: http://www.justjoli.be
Site URL: http://www.justjoli.be
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18
PHP Post Max Size: 40 MB
PHP Time Limit: 180
PHP Max Input Vars: 10000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Jouw winkel gebruikt geen HTTPS. Leer meer over HTTPS en SSL-certificaten.
Hide errors from visitors: ✔

### Active Plugins (21) ###

BackupBuddy: door iThemes – 7.3.1.1
bpost shipping: door Antidot – 2.2.7
Contact Form 7: door Takayuki Miyoshi – 4.7
Disable Comments: door Samir Shah – 1.6
Elfsight InstaShow: door Elfsight – 2.3.2
Force Regenerate Thumbnails: door Pedro Elsner – 2.0.6
Woocommerce Soldout Badges  - by Gema75: door Gema75 – 2.4
JP Sharing: door JP – 3.9.6
Multisafepay: door Multisafepay – 3.0.1
Rating-Widget: Star Review System (Premium): door Rating-Widget – 2.8.7
Slider Revolution: door ThemePunch – 5.2.6
TinyMCE Advanced: door Andrew Ozz – 4.5.6
WooCommerce Category Banner: door WP BackOffice – 1.1.2
WooCommerce Colors: door WooThemes – 1.0.6
WooCommerce Points and Rewards: door WooCommerce – 1.6.0
WooCommerce Pretty Emails: door MB Création – 1.4.4
WooCommerce Quantity Increment: door Automattic
WooThemes – 1.1.0

WooCommerce: door Automattic – 3.0.5
WooSidebars: door WooThemes – 1.4.3
WooCommerce Helper: door WooCommerce – 1.7.2 – Netwerk geactiveerd
Yoast SEO: door Team Yoast – 4.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #230 - /shop/
Winkelmand: #231 - /cart/
Afrekenen: #232 - /checkout/
Mijn account: ❌ Pagina bevat niet de shortcode.

### Theme ###

Name: Betheme Child
Version: 1.6
Author URL: http://muffingroup.com
Child Theme: ✔
Parent Theme Name: Betheme
Parent Theme Version: 17.8
Parent Theme Author URL: http://muffingroup.com
WooCommerce Support: ✔

### Templates ###

Overrides: betheme/woocommerce/archive-product.php
betheme/woocommerce/cart/cart-empty.php
betheme/woocommerce/cart/cart.php
betheme/woocommerce/cart/mini-cart.php
betheme-child/woocommerce/content-product.php
betheme/woocommerce/content-single-product.php
betheme/woocommerce/loop/loop-end.php
betheme/woocommerce/loop/loop-start.php
betheme/woocommerce/loop/no-products-found.php
betheme/woocommerce/loop/pagination.php
betheme/woocommerce/notices/error.php
betheme/woocommerce/notices/notice.php
betheme/woocommerce/notices/success.php
betheme/woocommerce/single-product/add-to-cart/external.php
betheme/woocommerce/single-product/product-image.php
betheme/woocommerce/single-product/product-thumbnails.php
betheme/woocommerce/single-product/sale-flash.php
betheme/woocommerce/single-product/tabs/additional-information.php
betheme/woocommerce/single-product/tabs/description.php
betheme/woocommerce/single-product/tabs/tabs.php
betheme/woocommerce/single-product/title.php
betheme/woocommerce/single-product.php

`

**Comment by claudiosanches** [comment]
It was removed because WooCommerce 3.0 changed the way it works with featured products, now using a taxonomy.
We have warned about the change in the release notes and this column is a consequence of that.

**Comment by sdevroey** [comment]
i understand that the way featured products are using taxonomy, but i fail to see why this has to remove the sorting option in the product overview. If you have 5000+ products of which 20 are featured it's almost impossible to find them easily without this sorting option

**Comment by ldsilickas** [comment]
I am second to that. Disabling the 'Feature' sorting option was a really bad move.

**Comment by mikejolley** [comment]
WordPress does not allow you to sort by terms/taxonomies

**Comment by ldsilickas** [comment]
Thanks Mike,

But, we are missing the point here. We End-Users are not interested to know if WordPress allows or not the feature. We just want the feature back. 

Cheers,

Lucas

**Comment by mikejolley** [comment]
It's not technically possible with terms. The speed improvements from using terms instead of meta for everything else trumps this.

**Comment by sdevroey** [comment]
That's strange that you say it's technically not possible. Since woocommerce has stopped this feature, I'm using the Woocommerce Advanced Bulk Edit plugin which has this sort feature and works like a charm.

**Comment by mikejolley** [comment]
Then it's probably not setting featured status correctly as terms.

**Comment by ldsilickas** [comment]
Hi Mike, 

Please could you enlighten us explaining the pros and cons of having the Featured column moved to taxonomy/terms?

I have been in touch with the guys at https://www.admincolumns.com/ and their plugin also covers the Featured column sorting. But the way you put above makes me wonder if these plugins are doing good or bad. 

Thank you. 

Regards, 

Lucas

**Comment by mikejolley** [comment]
Simply for performance; doing queries on meta data requires extra joins and is inefficient. Querying terms is faster. For something like featured which is technically a type of product visibility we were able to group these into a single, performant taxonomy. This allows WP Queries to get the data faster on the frontend.

**Comment by rshaw01** [comment]
We are also disappointed that this feature has been removed/is not available. Regarding performance, the product list load time has increased significantly since we upgraded from 2.4.x to 3.0.7. It takes 1 minute and 28 seconds to load a list of 450 products. Is this normal?

**Comment by mikejolley** [comment]
Loading that number all at once is of course going to be slow for any post type.

**Comment by rshaw01** [comment]
Hi Mike. Many thanks for the quick reply. I guess 450 records doesn't sound that much to me, but I guess its all relative.  Are there any recommended configuration settings for WooCommerce that will help us to optimise the system?  I am thinking WordPress and PHP configuration, as well as hardware recommendations?

**Comment by mikejolley** [comment]
Where are you listing these? Admin or frontend?

**Comment by rshaw01** [comment]
I'm referring to the admin console. Front end performance is fine.  With the admin console we work with it daily to update, add, remove and change product listing so performance is critical. If you are interested, the site is www.dancewearuniverse.co.uk. I could set you up an account.

**Comment by mikejolley** [comment]
If you set the limit to 450 on the posts screen (assuming you have 450 posts) you'll get the same. Thats too much data tbh all at once.

**Comment by rshaw01** [comment]
OK. Any thoughts or good links to info on performance optimisation?

**Comment by ldsilickas** [comment]
Hi all,

Please let's keep messages relevant to the subject of this thread only. For performance issues, relate them to another thread or create a new one.

Thank you.

**Comment by judddunagan** [comment]
Hey guys, 

On this issue of sorting for featured products. My client really liked and used the featured product sort tool on the backend. They have over 3000 products so this was very important to them. Feedback on the products updating and loading of the page. 3.08 was barely updating the products if not at all. We had to downgrade to 3.04 which work better. However, overall the backend performance is not going well after 3.0. Are there any plans on bringing the featured sorting option in the future?

**Comment by Ragdog** [comment]
So how can a shop manager see all of their featured products on the admin screen. You have a tab to show all of the shop categories. Why have something like this ??

**Comment by aonzzung** [comment]
Oh, I have 30,000 products on my shop and I cannot sort/filter by featured products ? 

I recommend adding another dropdown to filter by "featured products" along with "filter by category", "filter by product type"

**Comment by Lomion-tm** [comment]
so why got this closed? is there a workaround yet?

**Comment by Barns-be** [comment]
+1 from me:
I have 5000 products in my shop and want to have an overview of the featured products on the backend, so I can easily manage them by switching on/off the "star". Is there a solution?

**Comment by MKme** [comment]
+1 from me. Featured products are virtually useless now since finding them in the heap is so time consuming. A simple sort function (that we ALREADY had) would solve this.

**Comment by Lomion-tm** [comment]
+1 it is a must have feature nothing less

**Comment by mikejolley** [comment]
Sorting is technically impossible as I said further up. A *filter* could be added, if someone wants to contribute it.

**Comment by nviitala** [comment]
I think it would be smart that when user browses a category for example, featured products would be first. It's actually quite business critical feature. Currently that isn't possible. The only way to do that with normal WP query would be to first search for a featured products with other parameters, and then non-featured products with other parameters and then merge the results. The change was made to increase performance, but now that kind of sorting probably takes even more time.

**Comment by webaissance** [comment]
One good solution I found is to simply create a category called Featured and use this to designate the featured products. It can be filtered in the admin and in the store.

The built-in Featured method can be ignored and hidden (via screen options) until this issue is fixed.

Meantime - there is this thread about it. Do these methods work?
https://wordpress.stackexchange.com/questions/104537/woocommerce-filter-by-featured-products-in-admin

**Comment by claudiosanches** [comment]
@webaissance those methods are about "filtering" and not about "sorting", as @mikejolley said, is not possible "sort" anymore.

**Comment by Jany-M** [comment]
While I perfectly understand the move to taxonomies, I also think that not re-adding a filter, is not acceptable, from an admin perspective, as well as basic UX practices.

For anyone in need of this feature, add [this](https://wordpress.stackexchange.com/questions/104537/woocommerce-filter-by-featured-products-in-admin) to your `functions.php` (tested on WP 4.9.4 and WC 3.3.3):

```
function wpa104537_filter_products_by_featured_status() {

     global $typenow, $wp_query;

    if ($typenow=='product') :


        // Featured/ Not Featured
        $output .= "<select name='featured_status' id='dropdown_featured_status'>";
        $output .= '<option value="">'.__( 'Show All Featured Statuses', 'woocommerce' ).'</option>';

        $output .="<option value='featured' ";
        if ( isset( $_GET['featured_status'] ) ) $output .= selected('featured', $_GET['featured_status'], false);
        $output .=">".__( 'Featured', 'woocommerce' )."</option>";

        $output .="<option value='normal' ";
        if ( isset( $_GET['featured_status'] ) ) $output .= selected('normal', $_GET['featured_status'], false);
        $output .=">".__( 'Not Featured', 'woocommerce' )."</option>";

        $output .="</select>";

        echo $output;
    endif;
}
add_action('restrict_manage_posts', 'wpa104537_filter_products_by_featured_status');

function wpa104537_featured_products_admin_filter_query( $query ) {
    global $typenow;

    if ( $typenow == 'product' ) {

        // Subtypes
        if ( ! empty( $_GET['featured_status'] ) ) {
            if ( $_GET['featured_status'] == 'featured' ) {
                $query->query_vars['tax_query'][] = array(
                    'taxonomy' => 'product_visibility',
                    'field'    => 'slug',
                    'terms'    => 'featured',
                );
            } elseif ( $_GET['featured_status'] == 'normal' ) {
                $query->query_vars['tax_query'][] = array(
                    'taxonomy' => 'product_visibility',
                    'field'    => 'slug',
                    'terms'    => 'featured',
                    'operator' => 'NOT IN',
                );
            }
        }

    }

}
add_filter( 'parse_query', 'wpa104537_featured_products_admin_filter_query' );
```

There's several snippets out there, I find this one to work the best for my needs.

**Comment by conshelf** [comment]
@Jany-M Lifesaver!! Thank you for posting this. Still, in shock, this feature was removed.

**Comment by joeyorlando** [comment]
Thanks for removing this feature (sarcasm)

**Comment by mitchellkrogza** [comment]
> Simply for performance; doing queries on meta data requires extra joins and is inefficient. Querying terms is faster. For something like featured which is technically a type of product visibility we were able to group these into a single, performant taxonomy. This allows WP Queries to get the data faster on the frontend.

Wow this is from 2017 and you refer to "performance improvements" on Woocommerce? I have yet to see them. I have several functions to disable half the rubbish introduced by Automattic to actually make Woo and Wordpress fast. As far as Woocommerce goes with Core Web Vitals .... it sucks plain and simple.
