### ISSUE TITLE
woocommerce rest api, set order status to completed/processing, will not send email

### ISSUE THREAD

**Issue by johnwrise** [woocommerce/woocommerce#14890]
As subject, can have an option not send email to customers when add orders using rest api

**Comment by claudiulodro** [comment]
I'm not quite sure what you are saying. Can you tell me more about what the problem is?

**Comment by mikejolley** [comment]
API does not suppress emails - appears to be working my side.

**Comment by johnwrise** [comment]
@claudiulodro, when add order from api, 'set_paid' => true, or  'status' => 'completed', woocommerce will send an email to customer, i dont wan woocommerce send email to customer when i create an order using api, is there a option do not send email to customer???

p/s: i wan to send email to customer when customer while order via check-out

**Comment by johnwrise** [comment]
@mikejolley, your woocommerce site, send email to customer notification set true or false??? my site is true.

**Comment by mikejolley** [comment]
We don't have an option to disable sending from the API.

**Comment by johnwrise** [comment]
@mikejolley do have any possible way to disable send email to customer when add orders from api, we are doing integration with pos system.

**Comment by pqkluan** [comment]
@johnwrise I found a hacky way to do this.

Create new order as Guest (a.k.a no customer_id, billing, shipping). Then send the second request to update that order with actual customer info.

The system can't find customer email so it won't send the email and update order via API won't trigger the email notification.
