### ISSUE TITLE
Infinite loop on product create/update supposedly fixed in 3.04, still wrong in 3.05

### ISSUE THREAD

**Issue by gotyou** [woocommerce/woocommerce#14893]
### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by claudiulodro** [comment]
Can I get a link to the original issue? There were a few issues opened for infinite loops, some of which were more valid than others.

**Comment by mikejolley** [comment]
Yeah not enough details here. There wasn't actually an infinite loop bug in 3.0.4 core - the code change was a preventative measure in case extensions were not checking for loops themselves.

**Comment by gotyou** [comment]
Have turned off all plugins except woocomerce, when i update or add a product it is giving me the following message.

"Connection lost. Saving has been disabled until you’re reconnected.	We’re backing up this post in your browser, just in case."
