### ISSUE TITLE
Grouped Product inconsistency with on sale

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#14903]
### EXPLANATION OF THE ISSUE
If a child product of a grouped product is on sale, the parent (grouped) product gets a sale badge, however, if using the `sale_products` shortcode, the parent product is not displayed. I believe that the correct behaviour would be that the parent product would be displayed with the shortcode.

### STEPS TO REPRODUCE THE ISSUE
1. A grouped product exists
2. At least one of the grouped product's child products is on sale
3. See that the parent product has a sale badge
4. See that the parent product is not output by the `sale_products` shortcode

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://local.woo
Site URL: http://local.woo
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.8
PHP Version: 7.0.14-2+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.53 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 3.1.7
WooCommerce: by Automattic – 3.0.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
This one is not going to change (for now). The sale badge reflects that of the children within the group and you can see it's dynamically done here:

https://github.com/woocommerce/woocommerce/blob/a0822e6d1f243bbb888928f7c939f792bfd187e3/includes/class-wc-product-grouped.php#L52

No sale status is stored on the grouped product itself so there is nothing to query when getting sale_products via the shortcode.

We **can** get the children, but remember each child can be in multiple groups now so grabbing all grouped products and comparing them to the found children would be too inefficient.

This cannot be fixed until https://github.com/woocommerce/woocommerce/issues/14217 is in place enabling us to do a more efficient query. Let's revisit this once we have that table in place.
