### ISSUE TITLE
Duplicate Categories

### ISSUE THREAD

**Issue by benjaminthedev** [woocommerce/woocommerce#14904]
Hi folks, 

Since the last update I have an issue with Duplicate Categories.

Now each product as two categories which are the same and if I remove one of the categories then I will lose the products?

I just saw that someone else has this issue two days ago so hoping there will be a fix?

Cheers,

Ben.

**Comment by mikejolley** [comment]
Q-translate?

It has an option to update terms to the new Q-translate format (which does not use duplicate categories per language). Run that and no duplicates should display.

**Comment by benjaminthedev** [comment]
Hi Mike, 

On my client site I fixed this dup categories by going to:
wc-term-functions.php

Line 522 this:
	// Query fields.
	$clauses['fields'] = 'DISTINCT ' . $clauses['fields'] . ', tm.meta_value';

and replaced with this:
 
// Query fields.
	$clauses['fields'] = 'DISTINCT ' . $clauses['fields'];

That removed the duped cats. Not the best fix but will have to do for now.  I have seen a few more post about this too.

Not sure Q-translate would do anything, had a look at the plugin.

Cheers again!

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/15182
