### ISSUE TITLE
[Rest API] Impossible to pass several parameters to URL

### ISSUE THREAD

**Issue by samisafr** [woocommerce/woocommerce#14901]
Hello, 
I'm using the rest api, and it's great to get the products, but I have a problem to get product with specific tags or attributes.
I can get products by tags with https://website.com/wp-json/wc/v2/products?tag=138
The problem is when I want to get several of them, for exemple I want all the product with the tag id 138 and 140 how is it possible ? I tried tag=138+140 or tag=138&tag=140 but none of them work :(

Also I can't get product by attribute, in the doc we have this : 
attribute	string	Limit result set to products with a specific attribute.
but how to implement it in the url ? I tried many solution, but any of them work

thank you for your help ! :)

**Comment by claudiosanches** [comment]
You can just use commas, like `tag=138,140`.
About attributes works just fine.

Note that here is not a support channel, if you are looking for support you should try the community forum: https://wordpress.org/support/plugin/woocommerce

**Comment by claudiulodro** [comment]
To get a product by attribute you have to pass in both the attribute taxonomy with the `attribute` query var and the attribute term id with the `attribute_term` query var. e.g. `/wp-json/wc/v2/products/?attribute=pa_color&attribute_term=15`. [Here](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L222-L231) is the source code for the part of the API that handles attribute filtering.

**Comment by samsaf** [comment]
Hello, 
Yes I also tried https://website.com/wp-json/wc/v2/products?tag=163,95&consumer_key=xxx&consumer_secret=xxx

But in the result I have the tag 95 in every product (which is right) but the tag 163 I only have it in the first product that appear in the JSON.
I should only have the first product with the 2 tags ID, the other one only have the tag 95 and not the 163.
I have the extact same problem with the attributes : 

https://website.com/wp-json/wc/v2/products?attribute=pa_color&attribute_term=136,129&consumer_key=xxx&consumer_secret=xxx

May be that's the normal behavior of the tag and attributes filter (I hope not)

Thank you

**Comment by samsaf** [comment]
Hello, The only way I found to filter with 2 parameter is to use 2 different parameter, with tag and attributes, but impossible to filter with 2 different value of the same one
Thank you
