### ISSUE TITLE
Recounting of product terms gets exponentially slow with the number of products

### ISSUE THREAD

**Issue by judgej** [woocommerce/woocommerce#14900]
### EXPLANATION OF THE ISSUE

WC 3.x saving/adding a product on a shop with 30k+ products is taking over 240 seconds to do. The speed issue is entirely in one query - run by `_wc_term_recount` in here https://github.com/woocommerce/woocommerce/blob/25bca1c2183c27b59c47bddf38172bd0264bffe9/includes/wc-term-functions.php#L557

### STEPS TO REPRODUCE THE ISSUE

Large number of products; large number of categories; edit a product and save. Then wait. And wait. And wait...

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: https://example.com
Site URL: https://example.com
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

Query Monitor: by John Blackbourn – 2.13.4
Advanced Custom Fields: by Elliot Condon – 4.4.11
Akismet Anti-Spam: by Automattic – 3.3.1
cbnet Multi Author Comment Notification: by chipbennett – 3.2
Constant Contact Forms by MailMunch: by MailMunch – 2.0.6
Contact Form 7 Honeypot: by Nocean – 1.10
Contact Form 7: by Takayuki Miyoshi – 4.7
Debug Bar: by wordpressdotorg – 0.8.4
Flamingo: by Takayuki Miyoshi – 1.5
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.7
Heartbeat Control: by Jeff Matson – 1.0.3
InfiniteWP - Client: by Revmakx – 1.6.4
Mailgun: by Mailgun – 1.5.8.2
Members: by Justin Tadlock – 1.1.3
Posts 2 Posts. DO NOT UPGRADE: see Jira ticket SOUL-89: by scribu – 200 (was 1.4.2
changed to 200 to prevent it being updated)

VarkTech Pricing Deals for WooCommerce: by Vark – 1.1.7
VarkTech Pricing Deals PRO for WooCommerce: by VarkTech – 1.1.7
Query Multiple Taxonomies: by scribu – 1.6.3-alpha
Really Simple SSL: by Rogier Lankhorst – 2.5.13
Redirection: by John Godley – 2.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Customer Advanced Search: by Consilience Media Ltd – 1.0.0
Simple Image Sizes: by Rahe – 3.1.1
W3 Total Cache: by Frederick Townes – 0.9.5.4
Order Weight for WooCommerce: by We Up North – 0.3.5
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.7
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce SagePay Form and SagePay Direct Gateway: by Andrew Benbow – 3.7.4
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.14
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.1
WooCommerce Sold Out Products: by Gerhard Potgieter – 1.0.4
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.3
WooCommerce: by Automattic – 3.0.5
Shipping Details for WooCommerce: by PatSaTECH – 1.7.0
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.7
WP Admin No Show: by Doug Sparling – 1.7.0
WP-Cron Control: by Thorsten Ott
Erick Hitter
Automattic – 0.7.1


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: cd (cd)
external (external)
grouped (grouped)
sev (sev)
simple (simple)
tw (tw)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: Customer
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Canvas
Parent Theme Version: 5.0.9 – 5.11.4 is available
Parent Theme Author URL: http://www.woothemes.com
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: woocommerce/archive-product.php
woocommerce/cart/shipping-calculator.php
woocommerce/content-single-product.php
woocommerce/single-product/add-to-cart/simple.php
woocommerce/single-product/meta.php
woocommerce/single-product/related.php
woocommerce/single-product/title.php

`
```
</details>

**Comment by judgej** [comment]
Here is a query picked up by our MariaDB slow query log:

```sql
# Time: 170505 16:28:59
# User@Host: soulbrother_DB[soulbrother_DB] @  [62.255.26.86]
# Thread_id: 15903  Schema: soulbrother_DB  QC_hit: No
# Query_time: 228.687706  Lock_time: 0.000238  Rows_sent: 1  Rows_examined: 382733844
SET timestamp=1493998139;
SELECT SQL_CALC_FOUND_ROWS COUNT( DISTINCT ID )

FROM wp_posts

WHERE post_status = 'publish'
AND post_type = 'product'

AND ID NOT IN (
    SELECT object_ID FROM wp_term_relationships WHERE term_taxonomy_id IN (20241 )
)

AND ID IN (
    SELECT object_ID FROM wp_term_relationships
    LEFT JOIN wp_term_taxonomy AS tax
    USING( term_taxonomy_id )
    WHERE term_id IN (17463,3832,3833,3834,3835,3836,3837,3838,3839,3840,3841,3842,3843,3844,3845,3846,3847,3848,3849,3850 )
);
```

The two subqueries take approximately 15mS to run on their own, and the second one - `IN (...)` - returns ~9000 rows.

Since MySQL and MariaDB both have an IMMENSE optimisation flaw with sub-queries, I do not believe this query is built the right way. The problem is, MySQL will run the sub-query for *every single* intermediate row that is retrieved in the outer query. It makes no difference whether the sub-query references the outer query or not - it just blindly executes it over and over.

I do remember coming across a change by an Oracle developer that fixed this optimisation issue, but I don't believe it was every pulled into the MySQL main repository, and so never got released.

**Comment by judgej** [comment]
I've tried restructuring this query to use joins in place of the `IN(...)` condition, and that comes back in a few milliseconds.

```sql
SELECT COUNT( DISTINCT ID )

FROM wp_posts

INNER JOIN wp_term_relationships
ON wp_term_relationships.object_ID = wp_posts.id

inner JOIN wp_term_taxonomy AS tax
on wp_term_relationships.term_taxonomy_id = tax.term_taxonomy_id
and tax.term_id IN (17463,3832,3833,3834,3835,3836,3837,3838,3839,3840,3841,3842,3843,3844,3845,3846,3847,3848,3849,3850 )

WHERE post_status = 'publish'
AND post_type = 'product'

AND wp_posts.ID NOT IN (       
    SELECT object_ID FROM wp_term_relationships WHERE term_taxonomy_id IN (20241 )
)
;
```

The query builder in `_wc_term_recount `, if it had to do this, would need to use multiple table aliases since it looks like the `IN(...)` condition can be added multiple times.

I just knocked this query up quickly, so need to do some more tests to make sure it is returning the *same* data, but it feels about right to me. `IN` on a primary key, with a simple sub-select? Just do a join :-) What I don't have is visibility of where this query could be heading next, so whether a join is the right way to go. The current position though, is that this current query has brought sales down for one of our customers by a non-significant amount, as they can no longer add products (they add new products every Friday that collectors eagerly wait for).

**Comment by judgej** [comment]
Here is the query with the NOT IN also turned into a join:

```sql
SELECT COUNT( DISTINCT ID )

FROM wp_posts

INNER JOIN wp_term_relationships
ON wp_term_relationships.object_ID = wp_posts.id

# Inner join for all IN terms
inner JOIN wp_term_taxonomy AS tax1 
on wp_term_relationships.term_taxonomy_id = tax1.term_taxonomy_id
and tax1.term_id IN (17463,3832,3833,3834,3835,3836,3837,3838,3839,3840,3841,3842,3843,3844,3845,3846,3847,3848,3849,3850 )

# Outer join for all NOT IN terms
left join wp_term_relationships AS tax2
on tax2.object_id = wp_posts.ID
and tax2.term_taxonomy_id IN (20241 )

WHERE post_status = 'publish'
AND post_type = 'product'
# NOT IN terms need to be filters here too
and tax2.object_id is null
```

**Comment by judgej** [comment]
Thinking about it again, a top from here gives me this alternative query:

```sql
SELECT COUNT( DISTINCT wp_posts.ID )

FROM wp_posts

INNER JOIN (
    SELECT object_ID FROM wp_term_relationships
    LEFT JOIN wp_term_taxonomy AS tax
    USING( term_taxonomy_id )
    WHERE term_id IN (17463,3832,3833,3834,3835,3836,3837,3838,3839,3840,3841,3842,3843,3844,3845,3846,3847,3848,3849,3850 )
) AS join1
ON join1.object_id = wp_posts.id

LEFT JOIN (
    SELECT object_ID FROM wp_term_relationships WHERE term_taxonomy_id IN (20241 )
) as join2
ON join2.object_id = wp_posts.id

WHERE post_status = 'publish'
AND post_type = 'product'

# Don't forget this.
AND join2.object_id is null
;
```

That runs in 15mS, and does not need the inner queries to be ripped apart. Instead of running the sub-queries on every outer query row, it aggregates them first into two result sets, then joins. I'm still not entirely sure about the left join for the `NOT IN`, but it's a start.

**Comment by judgej** [comment]
Would you take a PR?

**Comment by claudiulodro** [comment]
Absolutely! Thanks.

**Comment by judgej** [comment]
Okay - installing a clone now. I'll make a start now, and finish off in the morning.

**Comment by judgej** [comment]
Trying out my changes in production. So far so good.

Is there anywhere an automated test can be put in, or a test that can be run to show that the changes are doing the *right* thing, as well as doing the thing super-zippy fast now? I can monitor the [DML] queries and post some here for inspection, if that helps, before I convert the branch into a PR.

**Comment by claudiulodro** [comment]
If you can validate it using PHPUnit, there's a whole testing suite in the `tests/unit-tests` folder. :)

**Comment by judgej** [comment]
Ah, cool. I'll look at that in the morning. Not sure how testable this function is going to be, considering it needs a database to operate (with known data to provide expected results) but I'll see what I can do.

**Comment by judgej** [comment]
Here is an example SQL statement when updating a product with my changes (formatted for this post):

```sql
SELECT Count(DISTINCT id)
FROM   wp_posts
       LEFT JOIN (SELECT object_id
                  FROM   wp_term_relationships
                  WHERE  term_taxonomy_id IN ( 7 )) AS exclude_join
              ON exclude_join.object_id = id
       INNER JOIN (SELECT object_id
                   FROM   wp_term_relationships
                          LEFT JOIN wp_term_taxonomy AS tax using(
                          term_taxonomy_id )
                   WHERE  term_id IN ( 17 )) AS include_join1
               ON include_join1.object_id = id
WHERE  post_status = 'publish'
       AND post_type = 'product'
       AND exclude_join.object_id IS NULL  
```

The `include_join1` would be repeated with an incrementing suffix if more than one were needed. I don't know in what circumstances that would happen though. There is only one "exclusion" clause though, so far as I can see.

The original SQL for the same product update:

```sql
SELECT Count(DISTINCT id)
FROM   wp_posts
WHERE  post_status = 'publish'
       AND post_type = 'product'
       AND id NOT IN (SELECT object_id
                      FROM   wp_term_relationships
                      WHERE  term_taxonomy_id IN ( 7 ))
       AND id IN (SELECT object_id
                  FROM   wp_term_relationships
                         LEFT JOIN wp_term_taxonomy AS tax using(
                         term_taxonomy_id )
                  WHERE  term_id IN ( 17 ))  
```

Posting this for visibility of the change to the query structure in case anyone can spot any flaws.

**Comment by judgej** [comment]
Not been able to get the test suite running - just too many errors, warnings, "output already started" warnings etc. so I'm going to skip the tests (sorry, just don't have the time).

**Comment by mikejolley** [comment]
@judgej Looks good. can you send the PR? I'm using a similar thing to solve https://github.com/woocommerce/woocommerce/issues/14909

**Comment by judgej** [comment]
With pleasue. I'll do that now.

**Comment by judgej** [comment]
Using `EXISTS` and `NOT EXISTS` has been suggested to be as an alternative. Running a test query took the same amount of time - of the order of 250 seconds. Maybe a few seconds were shaved off.

Something else that has been pointed out, and that I questioned myself about yesterday, is the `LEFT` join in this bit:

       AND id IN (SELECT object_id
                  FROM   wp_term_relationships
                         LEFT JOIN wp_term_taxonomy AS tax using(
                         term_taxonomy_id )
                  WHERE  term_id IN ( 17 ))  

Because of the WHERE clause here, it is acting as an INNER join, so perhaps it should explicitly state that it is an INNER join and not a LEFT join? I can make that change on the PR if you think so. It's not a problem, so far as I know is not causing a performance issue, but will just make it easier to understand when revisiting?

**Comment by judgej** [comment]
I've done that now `wp_term_relationships` is explicitly *INNER* joined to `wp_term_taxonomy` as the where-cause forces this anyway.
