### ISSUE TITLE
Inconsistent sale prices for variable product with identical variation prices

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#14905]
On 3.0.5 and storefront, when a variable product has variations with the same sale price but different regular prices, the sale price is shown but as a regular price, in the loop as well as on the single product page. The prices of the variation are displayed correctly.

For example, if a product has 2 variations :
A) with a sale price 100€ and regular price 200€ and
B) with a sale price 100€ and regular price 150€,

the product is shown as on sale in the loop but 100€ is shown without strikethrough. On the product page the product is shown with a regular price of 100€, but the variations have regular and sale prices shown.

**Comment by mikejolley** [comment]
Multiple ranges are no longer shown due to the length of displayed prices. This is intentional - see the note here https://github.com/woocommerce/woocommerce/blob/a6329fa68c90f6cbddd6cf16991bcb64252914ac/includes/class-wc-product-variable.php#L127-L129
