### ISSUE TITLE
Edit Image in Product gallery Woo 3.0.5 + 2.6.9

### ISSUE THREAD

**Issue by atolos** [woocommerce/woocommerce#14916]
### EXPLANATION OF THE ISSUE

When i click **Edit Image** in the **Add Images to Product Gallery** window,
Editor opens in a **new tab**(window) 

Version 2.6.9 + 3.0.5

it should open like the main product image window when you click there **Edit Image** the editor is opening in the same window.

### STEPS TO REPRODUCE THE ISSUE

1) New or Edit Product
2) click "**Add product gallery images**" 
3) choose or upload a picture 
4) click Edit Image 
5) expected to opens in the same window but it does not

### SYSTEM STATUS

<details>

`
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: tr_TR

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Mağazanız HTTPS kullanmıyor. HTTPS and SSL sertifikaları hakkında bilgi alın.
Hide errors from visitors: ✔

### Active Plugins (34) ###

Advanced Custom Fields: Gallery Field: (Elliot Condon) – 1.1.1
Advanced Custom Fields: Repeater Field: (Elliot Condon) – 1.1.1
Admin Menu Editor: (Janis Elsts) – 1.7.3
Advanced Access Manager: (Vasyl Martyniuk ) – 4.7
Advanced Custom Fields: (Elliot Condon) – 4.4.11
AG Custom Admin: (WAP) – 5.7.1
Contact Form 7: (Takayuki Miyoshi) – 4.7
CSS3 Responsive Web Pricing Tables Grids: (QuanticaLabs) – 10.6
Disable All WordPress Updates: (Oliver Schlöbe) – 1.5.0
Easy WP SMTP: (wpecommerce) – 1.2.5
Enable Media Replace: (Måns Jonasson) – 3.0.6
Essential Grid: (ThemePunch) – 2.1.0.2
WP için Google Analytics: (Alin Marcu) – 4.9.6.2
MPC Mega Menu: (Lee Chestnutt | Modified by MPC Team) – 1.6
WPBakery Visual Composer: (Michael M - WPBakery.com) – 5.0.1
Loco Translate: (Tim Whitlock) – 2.0.13
Screets Live Chat EXTRAS: () – 1.0
MAY DÖVİZ: (MAY-Hosting) – 1.0
MAY CANLI DESTEK: () – 1.0
MAY PAKET BİLGİLERİ: () – 1.0
MPC Extensions: (MassivePixelCreation) – 3.9.1
MPC Shortcodes: (MassivePixelCreation) – 3.8.2
MPC Widgets: (MassivePixelCreation) – 3.9
Plupload Fix v2.3.1: () – 1.0
Post Views Counter: (dFactory) – 1.2.7
Slider Revolution: (ThemePunch) – 5.3.1.5
Screets Live Chat: (Screets Team) – 2.2.8
MAY Counter: (MAY-Hosting) – 1.0
WPML Multilingual CMS: (OnTheGoSystems) – 3.7.0
WooCommerce: (Automattic) – 3.0.5
WP Cerber: (Gregory) – 4.7.7
WPML Media: (OnTheGoSystems) – 2.2.0
WPML String Translation: (OnTheGoSystems) – 2.5.3
WPML Translation Management: (OnTheGoSystems) – 2.3.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: TRY (₺)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Mağaza giriş sayfası: #1572 - /magaza/
Sepet sayfası: #1573 - /sepet/
Ödeme sayfası: #1574 - /odeme/
Hesabım sayfası: #1575 - /hesabim/

### Theme ###

Name: Blaszok Child
Version: 1.0
Author URL: http://www.blog.mpcreation.pl
Child Theme: ✔
Parent Theme Name: Blaszok
Parent Theme Version: 3.9.1
Parent Theme Author URL: http://mpcreation.net
WooCommerce Support: ✔

### Templates ###

Overrides: blaszok/woocommerce/archive-product.php
blaszok/woocommerce/cart/cart-empty.php
blaszok/woocommerce/cart/cart-shipping.php
blaszok/woocommerce/cart/cart-totals.php
blaszok/woocommerce/cart/cart.php 2.3.8 sürümü güncel değil. Çekirdek sürüm: 3.0.3
blaszok/woocommerce/cart/cross-sells.php 1.6.4 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/cart/mini-cart.php
blaszok/woocommerce/cart/shipping-calculator.php
blaszok/woocommerce/checkout/form-billing.php 2.1.2 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/checkout/form-checkout.php
blaszok/woocommerce/checkout/form-shipping.php 2.2.0 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/content-product.php 2.6.1 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/content-product_cat.php
blaszok-child/woocommerce/content-single-product.php 1.6.4 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/loop/add-to-cart.php 2.5.0 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/loop/loop-end.php
blaszok/woocommerce/loop/loop-start.php
blaszok/woocommerce/loop/no-products-found.php
blaszok/woocommerce/loop/pagination.php
blaszok/woocommerce/loop/result-count.php 2.0.0 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/loop/sale-flash.php
blaszok/woocommerce/myaccount/form-add-payment-method.php 2.6.0 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/myaccount/form-edit-address.php 2.6.0 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/myaccount/form-login.php
blaszok/woocommerce/myaccount/my-address.php
blaszok/woocommerce/myaccount/my-orders.php
blaszok/woocommerce/notices/error.php
blaszok/woocommerce/notices/notice.php
blaszok/woocommerce/notices/success.php
blaszok/woocommerce/order/order-details.php 2.6.0 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/order/tracking.php
blaszok/product-searchform.php
blaszok/woocommerce/single-product/meta.php 1.6.4 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/single-product/product-image.php 2.6.3 sürümü güncel değil. Çekirdek sürüm: 3.0.2
blaszok/woocommerce/single-product/product-thumbnails.php 2.6.3 sürümü güncel değil. Çekirdek sürüm: 3.0.2
blaszok/woocommerce/single-product/related.php 1.6.4 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/single-product/review.php
blaszok/woocommerce/single-product/sale-flash.php
blaszok/woocommerce/single-product/tabs/additional-information.php 2.0.0 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/single-product/tabs/description.php
blaszok/woocommerce/single-product/tabs/tabs.php
blaszok/woocommerce/single-product/up-sells.php 1.6.4 sürümü güncel değil. Çekirdek sürüm: 3.0.0
blaszok/woocommerce/single-product-reviews.php

</details>

**Comment by mikejolley** [comment]
Will look during https://github.com/woocommerce/woocommerce/issues/13071 but I don't think we control how the modal works - it's core WP.

**Comment by atolos** [comment]
featured image is core, i didnt know Product Gallery is core too ?!

**Comment by mikejolley** [comment]
The gallery is not core, but the modal window is.

**Comment by atolos** [comment]
ok i hope you find something i need a solution so much customer is making my life living hell

**Comment by mikejolley** [comment]
It's not a high priority - the edit still works regardless where it opens.
