### ISSUE TITLE
SyntaxError: JSON Parse error: Unexpected identifier "object"

### ISSUE THREAD

**Issue by jdbaluch** [woocommerce/woocommerce#14919]
### EXPLANATION OF THE ISSUE

During checkout, when trying to place the order I receive "SyntaxError: JSON Parse error: Unexpected identifier "object"" at the top of the screen right below the gift card and coupon area.

### STEPS TO REPRODUCE THE ISSUE

1. Visit http://yazbeck.com
2. Put something in the shopping cart.
3. Fill out user form.
4. Fill in fake credit card info and try to "place order".
5. Error occurs.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://yazbeck.com
Site URL: http://yazbeck.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.16 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 512 MB
PHP Time Limit: 500
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.15.4

SUHOSIN Installed: –
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: ugAd5YM5q_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (40) ###

BackupBuddy: by iThemes – 7.1.5.1
AfterShip - WooCommerce Tracking: by AfterShip – 1.6.8
Boxzilla: by ibericode – 3.1.12
Comet Cache: by WebSharks
Inc. – 170220

Easy Testimonials: by Gold Plugins – 2.2.5
WooCommerce - Gift Cards: by WP Ronin – 2.5.8
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
Google Doc Embedder: by Kevin Davis
Dan Lester – 2.6.2

Groups: by itthinx – 2.1.2
Hide Admin Bar From Non-admins: by Stranger Studios – 1.0
Instagram Feed: by Smash Balloon – 1.4.8
iThemes Sync: by iThemes – 1.175.0
MailChimp for WordPress: by ibericode – 4.1.1
MailChimp for WordPress - Top Bar: by ibericode – 1.2.16
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Ninja Forms reCAPTCHA: by Aman Saini – 1.2.5
Ninja Forms: by The WP Ninjas – 3.1.1
Q and A Focus Plus FAQ: by Lanexatek Creations – 1.3.9.7
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Taxonomy Metadata: by mitcho (Michael Yoshitaka Erlewine)
sirzooro – 0.5

Ultimate Member: by Ultimate Member – 1.3.84
Ultimate Member - Google reCAPTCHA: by Ultimate Member – 1.0.3
WooCommerce Extended Coupon Features: by Soft79 – 2.4.3
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Elavon Converge Gateway: by SkyVerge – 2.1.1
WooCommerce Group Coupons: by itthinx – 1.7.0
WooCommerce Memberships: by SkyVerge – 1.8.4
WooCommerce Multiple Free Gift: by Ankit Pokhrel – 1.2.0
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.1
WooCommerce Table Rate Shipping: by Bolder Elements – 3.6.6
WooCommerce: by Automattic – 3.0.4 – 3.0.5 is available
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WP Instagram Widget: by Scott Evans – 1.9.8
WP-SpamShield: by Scott Allen – 1.9.9.9.8
Custom Product Tabs for WooCommerce: by YIKES
Inc – 1.5.13

YITH WooCommerce Ajax Search: by YITHEMES – 1.5.2
YITH WooCommerce Wishlist: by YITHEMES – 2.1.1
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.29

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2659 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/

### Theme ###

Name: Flatsome
Version: 3.3.5
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Elavon Converge Credit Card ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Elavon Converge eCheck ###

Environment: Production
Debug Mode: Off
`
</details>

**Comment by mikejolley** [comment]
This did not occur with PayPal. Looks like a plugin issue (gateway or plugin throwing an error when order is placed). Server/PHP error logs will have the full error message to help you trace it. 

This is not a core issue. PayPal is unaffected which backs that up.

**Comment by Manoj002** [comment]
i have getting some error with a replcament of Unexpected identifier "System"
and what i think is the error in the type of data you are getting from your server
Here is my code:
fetch('url', {
            method: 'POST',
            headers: {
                'cache-control': 'no-cache',
                'content-type': 'application/x-www-form-urlencoded',
                'postman-token': 'k4j343lk5k5l3l34',
            },
            body: JSON.stringify({
                'UserName': 'usrname',
                'Password': 'pass'
            })
        }).then(response => response.json())
        .then(response => console.log(response));

Just make sure the data you are getting from server is the same type of data your request is able to handle.

**Comment by erkrujjawal786** [comment]
if you are using react-native then their might be some issue using fetch api ,so its better to use axios inpite of fetch functionality.i have also used axios module and have got the response in json format.

**Comment by redoz94** [comment]
I'm getting this error, with a 3rd party API; in my expo app. Any one, willing to help?

**Comment by Sonaaa10** [comment]
> I'm getting this error, with a 3rd party API; in my expo app. Any one, willing to help?

Did you solve the error? If yes, kindly help!
