### ISSUE TITLE
Manually add coupons on the backend is not possible

### ISSUE THREAD

**Issue by tonybahama** [woocommerce/woocommerce#14915]
Hi!

Unfortunately adding coupons using only the coupon code is not possible even though is a pretty simple feature.

Right now we use a simple calculator and we have to manually withdraw the coupon amount when someone forgets to enter it during the checkout. We have to manually calculate the net amount first, then save the modifications, recalculate taxes etc. Also we loose the ability to track coupons.

In the Woo ideabase it is the 3rd most voted feature request for 4 year! Without any response for years...
http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/3867647-ability-to-apply-coupons-manually-when-manually-ad

This would save us about 4-8 minutes of manual work at our business alone.

What is the reason it is not implemented yet?

Thank you very much
Levente

**Comment by mikejolley** [comment]
This requires a discounts API which is planned but not shipped yet. When we have a discount API, we'll offer this in the backend.
