### ISSUE TITLE
Woocommerce API 401 (fresh installation droplet on Digitalocean, siteground, ...) 

### ISSUE THREAD

**Issue by tileng1** [woocommerce/woocommerce#14918]
### EXPLANATION OF THE ISSUE

```
{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot list resources.",
  "data": {
    "status": 401
  }
}
```
Server hosting = geek plan on siteground
Fresh installation of wordpress and woocommerce through softacolus. HTTP works as it should, HTTPS with lets encrypt gives the error above. Tried a lot of things, different server (fresh droplet on digitalocean), same error.

Support of siteground said:

Hello

The reported issue is application related rather than a server side one. You have stated that the authentication works when the HTTP URL is used. That is a proof that the issue is not related to the server’s configuration. The Let’s Encrypt SSL certificate seems to be properly installed and I cannot detect any issues with it. An online tool do not indicate issues as well:

https://www.sslshopper.com/ssl-checker.html#hostname=xyz

We have carefully investigated the problem, and tried to resolve it however to no avail. As a part of my investigation I tried to change the PHP version for the site, the .htaccess redirect rules, disable a security Apache module called mod_security, updated file and folder permissions etc. Moreover I checked online for a related articles and suggested solutions – it seems that the issue is quite common:

https://github.com/woocommerce/wc-api-node/issues/43
https://github.com/woocommerce/woocommerce/issues/11714

The log records on the server also do not indicate what can be the reason for the issue. We do have experienced engineers/technicians, seasoned in dealing with various hosting-related WordPress issues. We do try to assist as much as possible with any application based related issue that you might approach us with, although sometimes there are more complex issues that require deeper investigation, which includes dedicating time and effort for debugging a problem, and this is usually best done by a professional developer. If a specific setting is suggested, we would gladly apply it for you (if the hosting environment allows it). You can find such developers in the most popular freelance websites.

Best Regards,

Hope this thread finds a correct person who will be able to solve the issue for me.

After talking to programmer he said that server is not parsing the right authorization headers. So I went to siteground support again and they said, they dont find any thing on their end. So I went and created a fresh droplet on DigitalOcean, with woocommerce and wordpress, installed lets encrypt, and I got 401.

So before you cut me off, try this yourself.

### STEPS TO REPRODUCE THE ISSUE

Install wordpress and woocommerce, put it on lets encrypt https, and try API.

URL: domain.com/wp-json/wc/v1/orders oauth1 or basic auth, neither works.

### SYSTEM STATUS

<details>
https://cloud.githubusercontent.com/assets/10894671/25775883/0378cce6-32b0-11e7-99fa-5799679ef962.png

</details>

**Comment by mikejolley** [comment]
You need to read https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API.

Auth does work, or we'd have way more reports of an issue, and no services would be able to use our API (all servers would be affected). You can try the validation thing pointed out in that doc in case the certificate is not valid or configured correctly ^ 

I also suggest you try authenticating with the WORDPRESS Rest API before coming back with more details (if you cannot solve), and remember basic auth only works over https. https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication

https://github.com/WP-API/Basic-Auth Use that and test the WP API endpoints. If you get similar errors, you'll know it's server related.

Signing up for a droplet/account myself isn't really ideal unfortunately. Happy to fix an issue if your debugging finds an actual issue in our code, but I cannot debug your setup personally. Feel free to comment back with your findings - I'm closing this issue as it's working in our environments but can reopen if you find anything. Thanks.

**Comment by software770** [comment]
In the documentagtion it seems to say that, if you can't connect wiht the authentication with the header, you should use parameters directly in the adress: www.yourstore.com/.../orders?consumer_key=XXXX&consumer_secret=XXXX

But, it seems vey unsafe to do that. Its very easyer to look at an adress of the request then its content. Why can't we send this in the Json body for this special case ? (in my understanding, puting this in the body, with https, the content will be also encrypted). 

I'm not judging (first because there is not enought thanks to give to the people that did such a nice work and gave it for free), but just trying to understand, since this something that, even the official documentation says this is something that evey one stuble on ("authetification").

Thank you so much in advance for explaining !

**Comment by kotlandroid** [comment]
you have to configure apache `http.conf` and add this `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` to be sure that apache will return authorization header
