### ISSUE TITLE
Product data are hidden in admin product page because of conflict with Bootstrap.css

### ISSUE THREAD

**Issue by adeacetis** [woocommerce/woocommerce#14922]
### EXPLANATION OF THE ISSUE

After WooCommerce update to from 2.5.3 to 3.0.5, product data tabs are hidden. Product data tabs aren't visible any longer. This is the result of a conflict with Bootstrap css required by a third party plugin, T-Shirt Ecommerce.

When user clicks on a tab (eg: inventory, shipping), the underlying jquery script (located in woocommerce/assets/js/frontend/meta-boxes.js) will call jquery `.show()` method and leaves the hidden class on tab holder element. While `.hidden` class is quite loose in WP/WC core, the former is much more stronger in Bootstrap which causes the element to remain hidden. 

```
// WP/WC core
.hidden {
  display:block;
}
```

```
// Bootstrap
.hidden {
  display: block !important;
  visibility: hidden !important;
}

```
Instead of calling .show() and .hide(), I'd suggest to add and remove `.hidden` class instead. That would avoid further conflict with BS down the road.

### STEPS TO REPRODUCE THE ISSUE

1. Register bootstrap.css stylesheet in admin area
2. Open product edit page
3. Look at Product Data meta box - General tab data should be visible
4. Click on Inventory tab
There the content should be hidden
5. Repeat for all tabs. Normally, they should be hidden

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (22) ###

HTML in Category Descriptions: by Arno Esterhuizen – 1.2.1.1
Duplicator: by Snap Creek – 1.2.6
Essential Grid: by ThemePunch – 2.0.5
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
Image Sizes Manager: by Web factory Ltd – 1.0
WooCommerce Quickview: by James Kemp – 3.0.7
Ninja Forms: by The WP Ninjas – 2.9.33
Plugin Security Scanner: by Glen Scott – 1.4.1
Slider Revolution: by ThemePunch – 5.2.1
WooCommerce Custom Product Designer: by tshirtecommerce.com – 3.2.2
WooCommerce Custom Fields: by RightPress – 1.2
WooCommerce Quantity Increment: by WooThemes
Bryce Adams – 1.0.0

WooCommerce Quick Export Plugin: by MB Création – 2.1.2
WooCommerce Simply Order Export: by Ankit Gade – 2.0.7
WooCommerce - Store Exporter Deluxe: by Visser Labs – 2.0.4
WooCommerce Table Rate Shipping: by Erica Dion – 3.3.4
WooCommerce: by Automattic – 3.0.5
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 3.1.1
WP Migrate DB: by Delicious Brains – 0.9.2
WP Rocket: by WP Rocket – 2.6.15
WP Sync DB: by Sean Lang – 1.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #47 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Flatsome Child Theme
Version: 2.0
Author URL: http:%20//www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 2.1
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart.php version 2.1.0 is out of date. The core version is 3.0.3
flatsome/woocommerce/cart/shipping-calculator.php
flatsome/woocommerce/checkout/form-checkout.php version 2.0.0 is out of date. The core version is 2.3.0
flatsome/woocommerce/content-product.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/content-product_cat.php version 1.6.4 is out of date. The core version is 2.6.1
flatsome/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/global/breadcrumb.php version 2.2.0 is out of date. The core version is 2.3.0
flatsome/woocommerce/global/quantity-input.php version 2.1.0 is out of date. The core version is 2.5.0
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 2.6.0
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php version - is out of date. The core version is 2.5.0
flatsome/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.3
flatsome/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/add-to-cart/variable.php version 2.1.0 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/price.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 3.0.2
flatsome/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/review.php version 2.1.0 is out of date. The core version is 2.6.0
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/tabs/description.php
flatsome/woocommerce/single-product/tabs/tabs.php version 2.0.0 is out of date. The core version is 2.4.0
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product-reviews.php version 2.1.0 is out of date. The core version is 2.3.2
flatsome/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
```
</details>

**Comment by adeacetis** [comment]
Hello everyone, 
Not sure whether this is intended, but product type design has also disappeared for exact same reason than 
the one described above (conflict with Bootstrap hidden class).
In that case, I had to remove the `hidden` class set on the drop down you can see below. 
![image](https://cloud.githubusercontent.com/assets/20586054/25784617/c83b9a48-3370-11e7-9dd0-a218e1d7113f.png)
Not sure whether my solution is a good one. I'd be grateful to hear the reasoning behind this specific case ? 
Thank you for your time.

**Comment by 1manfactory** [comment]
Try 3.0.4.

It seems to me that this error was caused after 3.0.4->3.0.5

**Comment by mikejolley** [comment]
No it's not. And it's easy to compare releases rather than speculating https://github.com/woocommerce/woocommerce/compare/3.0.4...3.0.5

**Comment by mikejolley** [comment]
`show` and `hide` add inline CSS. The code you pasted above I assume is from your DOM inspector after this occurs.

WordPress defines the .hidden style without `!important` and I'm pretty certain parts of WP admin use `.hidden` e.g. screen options:

![2017-05-08 at 15 19](https://cloud.githubusercontent.com/assets/90977/25808378/c8adabce-3401-11e7-9699-e1a32bf2b811.png)

This means the bootstrap style is going to break much more than just WooCommerce. Should it be fixed in WC? No - because it affects all of WP admin and changes how WP admin works by default.

http://stackoverflow.com/questions/36272728/why-does-bootstrap-break-wordpress-admin

**Comment by adeacetis** [comment]
@mikejolley Thank you for the pointer.

This seems a very common issue that could be easily avoided if we were reducing WC exposition to other libraries. 

IMHO, if WooCommerce or WordPress are exposed to third party CSS, it's not OK to say we won't fix because it could happen again and again. BS is just one library on the market but as state classes get more and more popular, I think WC and WP should strive to mitigate friction for user/developer whenever it's cheap and possible. Here this is a case where it could be done easy without harming the solution.
I agree my fix is partial and should be propagated wherever possible into the code base.

Don't get me wrong: I actually do use state classes wherever it's needed but I'd rather remove them than override them inline style. That's it. ;)

Anyway, I might be wrong. It's just my opinion, thanks again for the follow-up.
Cheers.

**Comment by mikejolley** [comment]
I'm also not happy with working around it is because (IMHO) using bootstrap in admin is pretty darn lazy :) It's a framework and I don't feel it belongs in WP Admin because the chance of conflicts are too great, and WP admin has it's own layout styles. The link I sent shows WP Admin itself conflicts with bootstrap.css.

Your fix does not look harmful on the surface, but it's a potentially breaking change if plugins rely on the inline CSS, or that style is ever changed in WP core css. Hard to know for certain but I'd feel uneasy changing it in a fix release.

**Comment by adeacetis** [comment]
Okay, got it. :) Thanks for the discussion about such trivial thing.

Have a nice day.

**Comment by ruturaaj** [comment]
> using bootstrap in admin is pretty darn lazy :)
I understand; but there are some libraries like SummerNote which need Bootstrap CSS and JS to be loaded. When I plan SummerNote to be integrated with one of my Metabox field, I need the dependencies to be loaded. In such case, I don't find any work-around to deal with this issue, unless check if we're on WooCommerce Product Edit page using current_screen and avoid enqueue script and style for that page in Admin.

**Comment by vulieumang** [comment]
In my case: I had install extension (laban dict) and it make woo error, deactivate and woo work.
You can check by using other browser and see

**Comment by cuongcnb** [comment]
thanks @vulieumang 
I removed laban dict and product data section worked.

**Comment by webargon** [comment]
I solved this issue updating Woocmmerce version to 4.5.1. (I did it just now) So, I think I may have others problems... not found yet.. site working properly. If appears any new trouble, I'll write here. Best regards.

**Comment by dennisklappe** [comment]
This appears to be an old thread, but I'm encountering the same problem. Even with all plugins disabled (except for WooCommerce) and using a default theme, my product editor seems to lack many fields because they are 'hidden'. How did you manage to resolve this issue?

![image](https://github.com/woocommerce/woocommerce/assets/35347995/aa28c981-ae16-45d5-b3f8-ff5e74e4ba12)
![image](https://github.com/woocommerce/woocommerce/assets/35347995/0c5ebdfe-f232-4220-8a7d-33b832be2e6c)
![image](https://github.com/woocommerce/woocommerce/assets/35347995/e2a0fa5b-2611-4167-8688-95770e9f4fbb)
