### ISSUE TITLE
Variations stay hidden in back-end

### ISSUE THREAD

**Issue by KLucky13** [woocommerce/woocommerce#14921]
I have a strange issue that just started today (I have not been installing new plug-ins in months). After creating variations and saving the article, the next time I cannot make them show up anymore. It's a bit hard to explain so I'll try to explain with the screenshot below:

![image](https://cloud.githubusercontent.com/assets/16277786/25780312/06892c52-3326-11e7-8590-7a4e5250e55c.png)

As you can see, this article has 5 variations. The buttons that are used to "unfold" and show all the variations no longer does anything. If I create a new variation, it is visible until the next time I save and re-open this article. The variations are there, but they do no longer show and I can no longer edit them. I have no clue what is happening but it seems that these 2 buttons (uitvouwen and sluiten = unfold/close) just don't work anymore?

If I hover over the button, this is the link that shows: 

![image](https://cloud.githubusercontent.com/assets/16277786/25780330/704fa260-3326-11e7-9181-7ea4c8331b1f.png)

I don't know if that might help to troubleshoot the problem

**Comment by mikejolley** [comment]
We've seen WPML cause this on some sites - looks like you do indeed have a translation plugin active as I can see lang=nl in the URL, so disable that to confirm, then look for updates/contact WPML support to resolve.

Thanks
