### ISSUE TITLE
Strange post pointer added to product name using rest api

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#14926]
### EXPLANATION OF THE ISSUE

Version 4.7.4

I created multiple products via the latest rest api, but it creates a strange pointer to my first wordpress post added to every product in the name attribute. Why is this added, and how to get rid of it?

**Image:**
![skjermbilde 2017-05-08 kl 09 46 21](https://cloud.githubusercontent.com/assets/4593184/25795802/472cc8a2-33d7-11e7-81c2-3fad53c22325.png)

Here is how the name attributes is returned from the rest api for a product: `Hello world! &rarr; Bakdekk grove SMC Barossa`

### STEPS TO REPRODUCE THE ISSUE

1. Install a new copy of latest wordpress with latest woocommerce
2. Create a new product by using the `/wp-json/wc/v2/products` rest api endpoint

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://localhost:9001
Site URL: http://localhost:9001
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: PHP 7.1.3 Development Server
PHP Version: 7.1.3
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.51.0
SecureTransport

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

StorePilot: by StorePilot AS – 1.0.0
WooCommerce: by Automattic – 3.0.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #234 - /index.php/products-pags/
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.1 – 1.2 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
You may have set the 'parent' when creating the product - leave parent_id set to 0 or omitted.
