### ISSUE TITLE
Attributes with non-english slug cannot be selected in product

### ISSUE THREAD

**Issue by rellect** [woocommerce/woocommerce#14920]
### EXPLANATION OF THE ISSUE

I noticed that when I create an attribute with non-english characters, the slug will automatically be generated from the title.
In this case, when the slug is not in english, I noticed that I can't choose the attribute in a product.
It will treat it as a new Custom attribute.

Changing the slug to english resolves the problem.

### STEPS TO REPRODUCE THE ISSUE

1. Create a new Attribute with non english chars, for example (hebrew): בדיקה
2. Leave slug empty
3. Save attribute
4. Create few terms inside the attribute
5. Go to product and add the attribute

I see the attribute in the list, but clicking on it produces a Custom attribute.

![image](https://cloud.githubusercontent.com/assets/2431842/25778696/5db31190-330e-11e7-9824-dbd5909ea64c.png)

### SYSTEM STATUS

Tested with latest master branch

**Comment by 9beat7** [comment]
I can reproduce it too with Ω

![capture](https://cloud.githubusercontent.com/assets/10142261/25795414/713a07fe-33ff-11e7-9758-d993e34b2b1c.PNG)
