### ISSUE TITLE
customer orders failed to notify order when successful

### ISSUE THREAD

**Issue by kokiecosmetics** [woocommerce/woocommerce#14924]
### EXPLANATION OF THE ISSUE

We have recently been having a problem with WooCommerce and customer orders on our site. It happened once in a while in the past, however these incidents are getting more and more frequent.
 
The problem is that when an order fails, for whatever reason, it is still given an order number, for example “Order #abcd has failed”. When someone goes to place an order next, they get the same order #abcd as their successful order, however WooCommerce does not record this and fails to document order #abcd entirely, which means people are being charged, but we are not getting any notification of their purchase.
 
An example of this kind of order is order #1797. 

### STEPS TO REPRODUCE THE ISSUE

the original order #1797 failed to be placed. HOWEVER, we have been notified by a DIFFERENT customer who placed their order SUCCESFULLY right after that they never got their order because we are not notified of it on WooCommerce, it just doesn’t show up, even though they got an email from woocommerce’s automated system saying their order #1797 was successfully placed AND they were charged for the order according to our separate paypal account’s system. This is causing chaos.
 
In other words, I believe successful orders made right after failed orders are given the same order # due to a glitch of some kind, which causes woocommerce to fail to notify us of the successful order that has been placed.

The original order #1797 was placed and had FAILED (due to whatever reason, it doesn’t matter for this scenario). However, A DIFFERENT PERSON placed an order RIGHT AFTER and their order was given order #1797 which does not show up on woocommerce’s orders list as seen below. The reason we know someone was given order #1797 is because the customer will file a complaint that they have not received their order yet, usually attached with an email of our automated order# confirmation emails that only THE CUSTOMER had received.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://kokiecosmetics.com
Site URL: https://kokiecosmetics.com
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.6.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.6.16
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.11
WC Database Prefix: wp_gfwc_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

Gravity Forms: by rocketgenius – 2.1.3
LayerSlider WP: by Kreatura Media – 5.6.6
AJAX Thumbnail Rebuild: by junkcoder – 1.12
Autoptimize: by Frank Goossens (futtta) – 2.1.0
Backup by blogVault: by Backup by blogVault – 1.42
Simple Custom CSS and JS: by Diana Burduja – 2.10
Duplicator: by LifeInTheGrid – 1.1.26
EWWW Image Optimizer: by Shane Bishop – 3.2.6
Fusion Core: by ThemeFusion – 2.0.3
Google Analytics by MonsterInsights: by MonsterInsights – 5.5.4
Instagram Slider Widget: by jetonr – 1.3.3
Lazy Load for Videos: by Kevin Weber – 2.2.3
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
PayPal for WooCommerce: by Angell EYE – 1.4.2
Really Simple SSL: by Rogier Lankhorst – 2.5.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Remove query strings from static resources: by Your WP Expert – 1.3.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.30

UPS WooCommerce Shipping: by WooForce – 2.2.5
WooCommerce Product Subtitle: by Varun Sridharan – 2.3
WooCommerce Custom Product Tabs Lite: by SkyVerge – 1.6.1
WooCommerce Dynamic Pricing: by Lucas Stark – 2.11.6 – 3.0.7 is available
WooCommerce Multiple Free Gift: by Ankit Pokhrel – 1.2.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.10 – 1.10.14 is available
WooCommerce Sequential Order Numbers Pro: by WooThemes / SkyVerge – 1.10.0 – 1.11.1 is available
WooCommerce Table Rate Shipping: by WooThemes – 3.0.1 – 3.0.3 is available
WooCommerce Variation Swatches and Photos: by Lucas Stark – 2.1.4 – 3.0.3 is available
WooCommerce Volume Discount Coupons: by itthinx – 1.2.3
WooCommerce: by Automattic – 3.0.5
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.2.8
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.0.2
WP Fastest Cache: by Emre Vona – 0.8.6.6
WP Google Maps: by WP Google Maps – 6.4.03
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.0.1

WP Resized Image Quality: by Mike Bijon
Etch Software – 2.1.2

WP Smush: by WPMU DEV – 2.5.2
WP Super Minify: by Dipak C. Gajjar – 1.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

### WC Pages ###

Shop base: #16552 - /shop-full-width/
Cart: #16564 - /cart/
Checkout: #16586 - /checkout/
My account: #16576 - /my-account/

### Theme ###

Name: Avada
Version: 4.0.3
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 3.0.2
Avada/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 3.0.2
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
Order numbers which you are speaking of are controlled by:

> WooCommerce Sequential Order Numbers Pro: by WooThemes / SkyVerge – 1.10.0 – 1.11.1 is available

Core uses post IDs as order ids by default and these cannot be duplicated or shared, unless you have a caching issue e.g. Checkout page being cached.

Suggest you run the update (http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-sequential-order-numbers-pro/changelog.txt), ensure the checkout is not being cached (exclude all checkout and cart pages from WP Fastest Cache) and use the helpdesk if that does not resolve.

**Comment by kokiecosmetics** [comment]
Hi,

I would like to ask if I need also to update the template along with the theme? Is it the reason why we are having problems with the order?

  Your theme (Avada) contains outdated copies of some WooCommerce template files. These files may need updating to ensure they are compatible with the current version of WooCommerce. You can see which files are affected from the system status page. If in doubt, check with the author of the theme.
