### ISSUE TITLE
woocommerce_is_sold_individually filter not working since the 3.0.5?

### ISSUE THREAD

**Issue by aureliendebord** [woocommerce/woocommerce#14928]
Hello,

Since the version 3.0, I can not remove the quantity field on my shop.

I am using the filter woocommerce_is_sold_individually like this:

`add_filter( 'woocommerce_is_sold_individually', 'wc_remove_all_quantity_fields', 10, 2 );
function wc_remove_all_quantity_fields( $return, $product ) {
    return true;
}`

Has anyone an idea to solve this problem?

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://localhost/mysite
Site URL: http://localhost/mysite
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.28
PHP Post Max Size: 32 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: arte_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ✔

### Active Plugins (16) ###

All-in-One WP Migration: par ServMask – 6.43
Genesis Connect for WooCommerce: par StudioPress – 0.9.9
Genesis Simple Edits: par StudioPress – 2.2.0
Genesis Traductions: par ThemeMix
Remkus de Vries – 2.4.1

Ninja Forms - Conditional Logic: par The WP Ninjas – 3.0.13
Ninja Forms - Stripe: par The WP Ninjas – 3.0.8
Ninja Forms - Layout & Styles: par The WP Ninjas – 3.0.19
Ninja Forms: par The WP Ninjas – 3.1.1
Regenerate Thumbnails: par Alex Mills (Viper007Bond) – 2.2.6
WP REST API: par WP REST API Team – 2.0-beta15
Widget CSS Classes: par C.M. Kendrick – 1.4.0
WooCommerce Stripe Gateway: par WooCommerce – 3.1.7
WooCommerce Product Add-ons: par WooCommerce – 2.8.1
WooCommerce: par Automattic – 3.0.5
WP Migrate DB Pro: par Delicious Brains – 1.7.1
WP Sitemap Page: par Tony Archambeau – 1.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base boutique: #28 - /shop/
Panier: #29 - /cart/
Commande: #30 - /checkout/
Mon compte: #31 - /my-account/

### Theme ###

Name: mysite Theme
Version: 0.1
Author URL: https://www.mysite.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.5.0
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
That filter is fine, and it will restrict to 1 in the cart. The display of the qty input however is template based, so your theme version may differ from the core version.

**Comment by aureliendebord** [comment]
Hello Mike,

Now, when I apply this filter, an error 500 occurs... I will not say "it is fine" ;).

**Comment by mikejolley** [comment]
Thats an error with your code, not the filter.
