### ISSUE TITLE
missing tax rate information in sales order when standard and reduced is applied

### ISSUE THREAD

**Issue by GiriSantosh** [woocommerce/woocommerce#14925]
### EXPLANATION OF THE ISSUE

When we apply standard tax and reduced tax rates on multiple products (say 2), the Order json message we get through api in tax_lines only respond us with standard tax rate.
**Version**: 3.0.5
Expecting: we're trying to find out the tax rate applied on each item but there is no relation between **tax_lines and line_items**

### STEPS TO REPRODUCE THE ISSUE

1. Apply standard tax rate on one of the product and reduced tax rate on other.
2. create an order by selecting these 2 products.
3. check the JSON message and in tax_lines 

### SYSTEM STATUS

<details>
### WordPress Environment ###

Home URL: http://52.74.241.106/wordpress
Site URL: http://52.74.241.106/wordpress
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.28-1+deb.sury.org~trusty+1
PHP Post Max Size: 8 MB
PHP Time Limit: 18000
PHP Max Input Vars: 5000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.53 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Custom Order Status for WooCommerce: by Algoritmika Ltd – 1.3.0
Import users from CSV with meta: by codection – 1.10.6.2
Woo Calculate Total: by hellodev.us – 1.0
Booster for WooCommerce: by Algoritmika Ltd – 2.7.1
WooCommerce: by Automattic – 3.0.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Education Base
Version: 1.2.1 – 1.2.7 is available
Author URL: http://www.acmethemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
</details>
[woocommerce_taxRate_issue.txt](https://github.com/woocommerce/woocommerce/files/982620/woocommerce_taxRate_issue.txt)

**Comment by mikejolley** [comment]
https://en-gb.wordpress.org/plugins/woo-calculate-total/ is not needed any more FYI.

I did the above test and had no issue via API:

![2017-05-08 at 12 41](https://cloud.githubusercontent.com/assets/90977/25802773/c05d566a-33eb-11e7-9444-a8478940a5b2.png)

Thats 2 tax rates, 1 standard, 1 reduced, in a single order.

Suggest you check your extensions in case they are affecting this. Also ensure the tax rates have different names.

**Comment by GiriSantosh** [comment]
Thanks @mikejolley 
It was an issue of same Tax name but still I'm not able to figure out how to identify the relationship between each taxes with line items

Example in the attachment.
[multiple_tax_relation_lineItem.txt](https://github.com/woocommerce/woocommerce/files/983661/multiple_tax_relation_lineItem.txt)

- What if same Tax is applied on multiple products how we will relate that given tax is applied on given products?

Please suggest
Thanks in Advance!

**Comment by mikejolley** [comment]
tax_lines is the sum of all line items. Look at the line items themselves if you want a breakdown.

**Comment by GiriSantosh** [comment]
it is clear that line_item sends tax value and tax_lines contains the sum of all line items but I want to convert each line_items's tax values into %percentage (one of our client's requirement).
Even if we try to convert into tax% it doesn't produce in exact value. It has been found that wooCommerce round of total_tax in each line_items at their end which cause wrong calculation of %.

I was trying to break it down using tax_lines but tax_lines/line_items have no relation with line_items/tax_lines.

**Comment by mikejolley** [comment]
You can add the line item tax rows and work out a percent from that. All the data you need is on the line items.

**Comment by GiriSantosh** [comment]
that we have already tried by reverse calculating into tax% but since wooCommerce round off 3 decimal value in to 2 decimal place, it creates a big gap with original tax% in woocommerce.

It is possible to add **rate_id** in line_items ?

**Comment by mikejolley** [comment]
How does that work if a line item has multiple taxes?

**Comment by GiriSantosh** [comment]
agree, that will fail.
But, ### It is possible to add rate_ids in line_items ?
