### ISSUE TITLE
Many fields in the Bulgarian version are displayed in English

### ISSUE THREAD

**Issue by mimi0604** [woocommerce/woocommerce#14930]
### EXPLANATION OF THE ISSUE

Many of the fields in v. 3.0.0 in the Card/Shop/Checkout pages are displayed in English even though I am using Bulgarian. 

### STEPS TO REPRODUCE THE ISSUE

1. In Wordpress Settings select language diferent than English (in my case Bulgarian).
2. Open the shop
3. Click Add to Card. The button View Card is in English (should be translated).
4. Click View Card. On the card page most of the buttons are in English (should be translated).

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://astroacademy.bg
Site URL: http://astroacademy.bg
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: bg_BG

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.3.29 - We recommend a minimum PHP version of 5.6. See: Как се надгражда версията на PHP
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: t4f0_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (7) ###

Intergeo - Google Maps Plugin: от Themeisle – 2.1.3
Free & Simple Contact Form Plugin - PirateForms: от Themeisle – 1.2.0
The Events Calendar: от Modern Tribe
Inc. – 4.4.5

WooCommerce - Autocomplete Orders: от Serious Plugins – 1.1.4
WooCommerce ePay.bg Gateway: от dimitrov.adrian – 1.3
WooCommerce PayPal Express Checkout Gateway: от WooCommerce – 1.2.0
WooCommerce: от Automattic – 3.0.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #36 - /?page_id=36
Количка: #30 - /?page_id=30
Поръчка: #34 - /?page_id=34
My account: #32 - /?page_id=32

### Theme ###

Name: Parallax One Child
Version: 1.0.0
Author URL: http://astroacademy.bg/
Child Theme: ✔
Parent Theme Name: Parallax One
Parent Theme Version: 2.1.4
Parent Theme Author URL: http://themeisle.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
See https://wordpress.org/support/topic/updating-translations-after-updates/ - this needs to be handled in the translation files.
