### ISSUE TITLE
502 and 504 errors moving products to trash

### ISSUE THREAD

**Issue by REGGSenterprises** [woocommerce/woocommerce#14941]
### EXPLANATION OF THE ISSUE

Ever since updating to WooCommerce V. 3.0.5 , whenever we attempt to move any product from any of our sites into the trash, we get either a 502 error or 504 error.

### STEPS TO REPRODUCE THE ISSUE

Go into list of products, hover over any product and click on Trash.

**Comment by mikejolley** [comment]
502/504 are server errors, possibly timeouts. I'm not experiencing the problem so I think you'll find (if anything) it's a plugin conflict. You didn't provide your status report so there is not enough info to even speculate what would be to blame.

**Comment by REGGSenterprises** [comment]
I have already reverted back to version 3.0.3 which does not cause the errors so I cannot give an up to date status report from when the errors occurred.  I have deactivated every plugin leaving only WooCommerce active and still received the errors.  In V. 3.0.3 , my server jumps to around 21% usage when moving a product to trash.  In V. 3.0.5, it jumps to 100%.

**Comment by mikejolley** [comment]
What do your PHP error logs say?

**Comment by REGGSenterprises** [comment]
There are no errors.

**Comment by mikejolley** [comment]
It sounds like a timeout/endless loop but without being able to replicate or knowing what extensions are running I cannot say.

**Comment by REGGSenterprises** [comment]
From what I understand, many are having the same issue.

**Comment by mikejolley** [comment]
Well it doesn't affect all sites or it would happen to me too? Same hosting providers? Same plugins?

**Comment by REGGSenterprises** [comment]
It happens even with ALL plugins disabled except WooCommerce.  One plugin I use has also put in support requests since a number of their users are having similar errors but I not only deactivated the plugin but also deleted it to be sure that was not the cause.

**Comment by mikejolley** [comment]
What plugin? You'll have to be more specific and share status reports. Like I said, unless I can reproduce this I cannot fix anything.

**Comment by REGGSenterprises** [comment]
`
### WordPress Environment ###

Home URL: http://topcellulardeals.com
Site URL: http://topcellulardeals.com
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 3 GB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.21
PHP Post Max Size: 3 GB
PHP Time Limit: 600
PHP Max Input Vars: 1500
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 3 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_reev_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (16) ###

Clicky Analytics: by Alin Marcu – 1.4.7
Simple Custom CSS and JS: by Diana Burduja – 3.0
JCH Optimize: by Samuel Marshall – 2.0.8
Kingdom - Core Functionality: by AA-Team – 1.0
Kingdom - Shortcodes plugin: by AA-Team – 1.0
Max Mega Menu: by Tom Hemsley – 2.3.5
NIX Gravatar Cache: by NIX Solutions Ltd – 0.0.7
NextScripts: SNAP Pro Upgrade Helper: by NextScripts – 1.3.9
Recent Posts Widget Extended: by Satrya – 0.9.9.6
NextScripts: Social Networks Auto-Poster: by NextScripts – 3.7.17
StopBadBots: by Bill Minozzi – 3.3
WooCommerce: by Automattic – 3.0.3 – 3.0.5 is available
WooZone - WooCommerce Amazon Affiliates: by AA-Team – 9.0.4.5
Yoast SEO: by Team Yoast – 4.7
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP Super Cache: by Automattic – 1.4.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #26 - /shop/
Cart: #27 - /cart/
Checkout: #28 - /checkout/
My account: #29 - /my-account/

### Theme ###

Name: Kingdom
Version: 3.2.2
Author URL: http://themeforest.net/user/AA-Team/portfolio?ref=AA-Team
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: kingdom/woocommerce/archive-product.php
kingdom/woocommerce/cart/cart-empty.php
kingdom/woocommerce/cart/cart-item-data.php
kingdom/woocommerce/cart/cart.php
kingdom/woocommerce/cart/cross-sells.php
kingdom/woocommerce/cart/mini-cart.php
kingdom/woocommerce/cart/shipping-calculator.php
kingdom/woocommerce/checkout/cart-errors.php
kingdom/woocommerce/checkout/form-billing.php
kingdom/woocommerce/checkout/form-login.php
kingdom/woocommerce/checkout/form-pay.php
kingdom/woocommerce/content-product.php
kingdom/woocommerce/content-single-product.php
kingdom/woocommerce/global/form-login.php
kingdom/woocommerce/global/sidebar.php
kingdom/woocommerce/global/wrapper-end.php
kingdom/woocommerce/global/wrapper-start.php
kingdom/woocommerce/loop/loop-end.php
kingdom/woocommerce/loop/loop-start.php
kingdom/woocommerce/loop/no-products-found.php
kingdom/woocommerce/loop/orderby.php
kingdom/woocommerce/loop/price.php
kingdom/woocommerce/loop/rating.php
kingdom/woocommerce/loop/result-count.php
kingdom/woocommerce/loop/sale-flash.php
kingdom/woocommerce/myaccount/form-add-payment-method.php
kingdom/woocommerce/myaccount/form-edit-address.php
kingdom/woocommerce/myaccount/form-login.php
kingdom/woocommerce/myaccount/my-account.php
kingdom/woocommerce/myaccount/my-downloads.php
kingdom/woocommerce/notices/error.php
kingdom/woocommerce/notices/notice.php
kingdom/woocommerce/notices/success.php
kingdom/woocommerce/order/form-tracking.php
kingdom/woocommerce/single-product/add-to-cart/external.php
kingdom/woocommerce/single-product/add-to-cart/grouped.php
kingdom/woocommerce/single-product/add-to-cart/simple.php
kingdom/woocommerce/single-product/add-to-cart/variable.php
kingdom/woocommerce/single-product/meta.php
kingdom/woocommerce/single-product/product-attributes.php
kingdom/woocommerce/single-product/product-image.php
kingdom/woocommerce/single-product/product-thumbnails.php
kingdom/woocommerce/single-product/related.php
kingdom/woocommerce/single-product/sale-flash.php
kingdom/woocommerce/single-product/share.php
kingdom/woocommerce/single-product/short-description.php
kingdom/woocommerce/single-product/tabs/additional-information.php
kingdom/woocommerce/single-product/tabs/description.php
kingdom/woocommerce/single-product/tabs/tabs.php
kingdom/woocommerce/single-product/title.php
kingdom/woocommerce/single-product/up-sells.php
kingdom/woocommerce/single-product.php
kingdom/woocommerce/taxonomy-product_cat.php
kingdom/woocommerce/taxonomy-product_tag.php

`

**Comment by mikejolley** [comment]
And what was the plugin you heard had issues? "WooZone - WooCommerce Amazon Affiliates"?

**Comment by REGGSenterprises** [comment]
Yes, that is it.

**Comment by mikejolley** [comment]
Being premium I cannot check the code but it sounds like it could do some syncing/saving of data when WC saves data. That could cause a timeout.

**Comment by REGGSenterprises** [comment]
That of course was my first thought but even when I deactivate and delete the Woozone plugin, I still get the errors.

**Comment by mikejolley** [comment]
I did see a case where a plugin like that (may have been another) duplicated a whole bunch of meta data, so even when disabled it would timeout due to the shear number of meta records in the database.

**Comment by REGGSenterprises** [comment]
Again, could certainly be a possibility especially seeing the size of the metadata table in my database but then why would my server/resource usage jump from around 11% in version 3.0.3 to 100% in version 3.0.5 causing the errors.

**Comment by mikejolley** [comment]
Maybe the cache cleaning? https://github.com/woocommerce/woocommerce/compare/3.0.3...3.0.5#diff-1c21163ea1dd16dc3e34f8b3ede74fdcR168

**Comment by REGGSenterprises** [comment]
I have cleaned cache more times than I can count while trying to find out the cause of the errors.

**Comment by REGGSenterprises** [comment]
Any further thoughts or comments on this problem?

**Comment by mikejolley** [comment]
Not without seeing it myself. And I mean browser cache too.

**Comment by REGGSenterprises** [comment]
Certainly have cleared browser cache.  Tried every browser known to man.

**Comment by mikejolley** [comment]
Will need access to look any further then.

**Comment by REGGSenterprises** [comment]
How can I give you access to one of my sites?

**Comment by mikejolley** [comment]
Email on profile.

**Comment by REGGSenterprises** [comment]
I just had a thought as to what may have occured that may be the problem.  I recall that when I updated to 3.0.5 that it said there was an update required to the database.  I never saw or confirmed that the updates ever were completed on any of my sites.  Could that be the problem?  If so, is there a way to re-run the database update that was required?

**Comment by REGGSenterprises** [comment]
Just added you and emailed details.

**Comment by srjwebster** [comment]
Did this ever resolve?

If I run a duplicate on an item with lots of meta data (variable currency data) I get 502s. Is this related to timeouts due to inefficient database updates? It's always surprised me how many separate queries are sent, rather than condensing them into one query.

**Comment by streamworksaudio** [comment]
I am having a very similar issue with 3.1.2 - every time I try to Trash any post I get a 500 Server error.  If I deactivate WooCommerce I am able to trash the posts.

So this seems to be an issue of some sort.

**Comment by mikejolley** [comment]
Different error code - different problem. Look at the server error logs.

I'm closing this issue out because the issue topic so generic and un-detailed it could literally be caused by anything, or apply to other unrelated things like conflicts.
