### ISSUE TITLE
Enable zoom / flex on some posts only

### ISSUE THREAD

**Issue by pixedelic** [woocommerce/woocommerce#14947]
Is there any way to support new features (zoom, flex...) but to enable them on some posts only? 

`add_theme_support` doesn't allow to use post ids, and there's no way to destroy Flex carousel once initialized, for instance.

Any plan to allow this kind of customization? Maybe on [https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-frontend-scripts.php](url)

```php
   'zoom_enabled'       => apply_filters( 'woocommerce_single_product_zoom_enabled', get_theme_support( 'wc-product-gallery-zoom' ) ),
   'photoswipe_enabled' => apply_filters( 'woocommerce_single_product_photoswipe_enabled', get_theme_support( 'wc-product-gallery-lightbox' ) ),
   'flexslider_enabled' => apply_filters( 'woocommerce_single_product_flexslider_enabled', get_theme_support( 'wc-product-gallery-slider' ) ),
```

Any chance to get something like that in future updates?

**Comment by mikejolley** [comment]
Wouldn't that be too early to tell what post you're on?

**Comment by pixedelic** [comment]
If I'm not wrong, they are on `wp_print_scripts` hook. It seems to work in my first tests, but maybe I have to try some edge case

**Comment by mikejolley** [comment]
Ok. If you're testing this for your own use case, please file a PR. Your filter name proposal looks good so should be fine to merge for 3.1.

Thanks

**Comment by asafm7** [comment]
Returning `false` to the filters empties the args, but not setting it to `false` - so it isn't really disabled. Or am I missing something? 
![image](https://github.com/woocommerce/woocommerce/assets/14274769/878e79c8-0705-4f98-9329-0045db48076c)
