### ISSUE TITLE
itemmeta only shown if both meta_key and meta_value is provided

### ISSUE THREAD

**Issue by kseyedmehdi** [woocommerce/woocommerce#14955]
### EXPLANATION OF THE ISSUE

Since V3 order_itemmeta only show in the backend view/edit when key and value are provided.
If only the order_itemmeta is set you won't be able to view/edit the meta anymore.

### STEPS TO REPRODUCE THE ISSUE

1. Grab an order which is still pending so you are able to edit the order items
2. Edit an order item
3. add a meta and only fill in the meta_key do not provide the meta_value
4. press save
5. you will now see that you cannot see the meta you just added, while it is stored in the database and you will never be able to touch it using the admin panel.

### SYSTEM STATUS

<details>
WC Version:		3.0.4
WP-Version:		4.7.4
WP Multisite:		–
WP Memory Limit:		768 MB
WP Debug-Modus:		–
WP Cron:		–
Sprache:		de_DE
</details>

**Comment by mikejolley** [comment]
Both fields are required. We added a placeholder text to make this more obvious a few versions back. I don't see a good reason to support keys with no values.
