### ISSUE TITLE
Apply filter not used on add to cart for loops

### ISSUE THREAD

**Issue by alenb** [woocommerce/woocommerce#14952]
### EXPLANATION OF THE ISSUE

`/templates/loop/add-to-cart.php` uses a quantity variable, which doesn't use the `woocommerce_quantity_input_min` filter, so it comes out incorrect.

I recommend replacing:

`esc_attr( isset( $quantity ) ? $quantity : 1 ),`

with:

`esc_attr( apply_filters( 'woocommerce_quantity_input_min', $product->get_min_purchase_quantity(), $product ) ),`

**Comment by mikejolley** [comment]
`woocommerce_quantity_input_min` is for the `min` attribute on input fields. Thats not what this template has or uses. This is a link, and that value is used by ajax. I don't think the same filter should apply tbh.

You can use the woocommerce_loop_add_to_cart_link filter to change the defaults if you wish.

**Comment by alenb** [comment]
Hey mikejolley,

That's fair enough. I guess it would have been better to have had a global `min` i.e. `woocommerce_quantity_min` that could be used by both the link and the input. Either way, thank you very much on the explanation :)
