### ISSUE TITLE
Woocommerce variable product cannot display variable image

### ISSUE THREAD

**Issue by hchanbluebell** [woocommerce/woocommerce#14951]
### EXPLANATION OF THE ISSUE

Hi, I have a site using Woocommerce and it is the latest version. 
https://davidoff-asia.com/product/davidoff-freshly-rolled-cigars/
However the variable product image cannot change when I select the option.
I sure that I insert the images already.
The image URL is in the code but the script seems not trigger when I select option.
I can give u the login if needed.
Thanks.
### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://davidoff-asia.com
Site URL: https://davidoff-asia.com
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wphi_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Advanced Custom Fields: by Elliot Condon – 4.4.11
Akismet Anti-Spam: by Automattic – 3.3
API KEY for Google Maps: by GeoDirectory – 1.1.0
Custom Email to Shop: by Pavan Potdar – 1.0.0
Custom Upload Dir: by Ulf Benjaminsson – 3.4.3.1
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.20
Google Analytics: by ShareThis – 2.1.3
Jetpack by WordPress.com: by Automattic – 4.8.2
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
SG Optimizer: by SiteGround – 3.2.3
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.1.6
WooCommerce Click And Pick: by Osama Ahmed Attia – 1.9.9
WooCommerce Currency Switcher: by realmag777 – 2.1.8
WooCommerce Email Test: by RaiserWeb – 1.8
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Quick Buy: by Varun Sridharan – 1.4
WooCommerce: by Automattic – 3.0.5
Yoast SEO: by Team Yoast – 4.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: HKD (HK$)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #614 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: ❌ Page not set

### Theme ###

Name: Shopkeeper Child
Version: 1.6.3
Author URL: http://www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: Shopkeeper
Parent Theme Version: 1.6.8
Parent Theme Author URL: http://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php
shopkeeper/woocommerce/cart/cart-empty.php
shopkeeper-child/woocommerce/checkout/form-billing.php version 2.1.2 is out of date. The core version is 3.0.0
shopkeeper-child/woocommerce/checkout/form-checkout.php
shopkeeper/woocommerce/checkout/form-coupon.php
shopkeeper/woocommerce/checkout/form-login.php
shopkeeper/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.0.0
shopkeeper/woocommerce/checkout/payment-method.php
shopkeeper-child/woocommerce/checkout/payment.php
shopkeeper-child/woocommerce/checkout/review-order.php
shopkeeper-child/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
shopkeeper-child/woocommerce/content-product.php version 2.5.0 is out of date. The core version is 3.0.0
shopkeeper/woocommerce/content-product_cat.php
shopkeeper/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
shopkeeper-child/woocommerce/emails/email-addresses.php version 2.4.0 is out of date. The core version is 3.0.0
shopkeeper-child/woocommerce/emails/email-styles.php
shopkeeper/woocommerce/global/breadcrumb.php
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/loop/loop-end.php
shopkeeper/woocommerce/loop/loop-start.php
shopkeeper/woocommerce/loop/no-products-found.php
shopkeeper/woocommerce/loop/orderby.php
shopkeeper/woocommerce/myaccount/form-login.php
shopkeeper/woocommerce/myaccount/my-downloads.php
shopkeeper/woocommerce/order/form-tracking.php
shopkeeper-child/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 3.0.0
shopkeeper/woocommerce/single-product/add-to-cart/external.php
shopkeeper/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
shopkeeper-child/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
shopkeeper/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
shopkeeper/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 3.0.2
shopkeeper/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 3.0.2
shopkeeper/woocommerce/single-product/rating.php
shopkeeper/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
shopkeeper/woocommerce/single-product/short-description.php
shopkeeper/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
shopkeeper/woocommerce/single-product/tabs/description.php
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
shopkeeper/woocommerce/single-product-reviews.php
shopkeeper/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update

</details>

**Comment by hellerbenjamin** [comment]
I wold imagine this is because of the fresco lightbox plugin you have running.  I would also recommend updating your page templates before opening an issue.

**Comment by mikejolley** [comment]
Custom lightboxes need to support variation images and events to work correctly, like our core lightbox scripts do.
