### ISSUE TITLE
Warning: date() expects parameter 2 to be long, object given in

### ISSUE THREAD

**Issue by mrjey92** [woocommerce/woocommerce#14950]
### Warning: date() expects parameter 2 to be long, object given in /home/user/public_html/wp-includes/functions.php on line 104

 I have a woocommerce version 3.0.5 and im getting this warning after the checkout under order details where its supposed to say the date..

**Comment by hellerbenjamin** [comment]
Have you tried disabling all plugins?  Is this happening on a live site, or is there any further information you can provide?

**Comment by mrjey92** [comment]
I have a wordpress site hosted with hostgator and runing this theme: North Version: 3.1.1 By fuelthemes. Yes, this happening on live site.. yes i have tried disabling all plugins.

**Comment by mikejolley** [comment]
Dates in the new CRUD are WC_Datetime objects. Looks like you have some code on your store which is not handling this correctly so you'll need to find out what is inserting the custom date. Does not appear to be core.

**Comment by mrjey92** [comment]
How do i do it? Any help?

**Comment by mikejolley** [comment]
I can't help without seeing the date code you have.

**Comment by mrjey92** [comment]
I got this issue resolved

**Comment by amaleather** [comment]
How did you resolved it? I have the same issue

**Comment by thenewbreed** [comment]
Please, please post your solution. I really need help.

**Comment by jerryg45** [comment]
How can this be resolved
