### ISSUE TITLE
Billing is copied to shipping address for local pickups (no destination needed)

### ISSUE THREAD

**Issue by freeaanzee** [woocommerce/woocommerce#14960]
## EXPLANATION OF THE ISSUE

When a customer selects a local pickup method during checkout (through the built-in shipping method or the Local Pickup Plus plugin) the shipping address is unnecessarily set to match the billing address:

![screenshot](https://www.fairtradecrafts.be/wp-content/screens/shipping-address-set-on-pickup.png)

This is very confusing on the admin orders screen (and our external parcel service mistakenly suggests to print shipping labels for these orders too).

They used to stay blank on our demo environment, as far as I can see at least untill the WC 3.0 RC1 release. This old test order shows the way it used te behave:

![screenshot](https://www.fairtradecrafts.be/wp-content/screens/local-pickup-with-empty-shipping-address.png)

I added some debugging info to the [get_posted_data()](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L571) function in class-wc-checkout.php to check where it goes wrong:

- The shipping fieldset is initially skipped for these type of orders, since the 'ship_to_different_address' checkbox is off (and hidden) for pickups.
- Next WC()->cart->needs_shipping_address() immediately invokes [WC()->cart->needs_shipping()](https://github.com/woocommerce/woocommerce/blob/0d89250b3f2df2bb0698034cb7eaae77d096ea73/includes/class-wc-cart.php#L1517). When shipping is enabled this function runs over all cart items to check if one of them is not virtual, creating the need for shipping. 
- Since we sell physical products true is returned to the second conditional, and the billing fieldset is indeed copied to the shipping fieldset.

For the moment I dirty-fixed this by using the 'woocommerce_cart_needs_shipping_addres' filter but this should be provided by WooCommerce core, I guess?

![screenshot](https://www.fairtradecrafts.be/wp-content/screens/dirty-fix-pickup-through-filter.png)

Our 'woocommerce_ship_to_destination' value is set to 'billing' and not 'billing_only' so the 'Force shipping to the customer billing address' option doesn't matter here. 

## STEPS TO REPRODUCE THE ISSUE

1. Enable a local pickup method
2. Make sure the 'Force shipping to the customer billing address' option is disabled
3. Finish an order with local pickup as the shipping method
4. Check the 'Destination' column in the back-end
5. It should be empty but it's not :(

## SYSTEM STATUS REPORT

```
### WordPress Environment ###

Home URL: https://demo.oxfamwereldwinkels.be/oostende
Site URL: https://demo.oxfamwereldwinkels.be/oostende
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: shop_10_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce: door Automattic – 3.0.5
Mollie Payments for WooCommerce: door Mollie – 2.5.4
User Role Editor Pro: door Vladimir Garagulya – 4.34.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Winkelbasis: #5 - /producten/
Winkelmand: #6 - /winkelmandje/
Afrekenen: #7 - /afrekenen/
Mijn account: #8 - /mijn-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.2
Author URL: https://nl.wordpress.org/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een subthema aan. Zie: Hoe maak je een subthema

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by mikejolley** [comment]
As stated in past issues, this cannot be changed easily. a) it would be breaking change in behaviour and some users may need that address (e.g. for gateways), and b) the shipping address etc is collected BEFORE the user selects a shipping option (local pickup). Shipping is _not_ chosen beforehand. 

Therefore since the data is collected, this will still be set.

> and our external parcel service mistakenly suggests to print shipping labels for these orders too

There is this method which can be used: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order.php#L1263

This could be revisited when the checkout flows are looked at, but it's tricky because shipping methods require a shipping addresses before calculation. Your filter does not really solve this - in fact, the filter cannot work until after shipping has been calculated and an address may have already been provided by then.

Hope that makes sense.
