### ISSUE TITLE
WC Logger Entries Not Ordering Correctly

### ISSUE THREAD

**Issue by josiahdwill** [woocommerce/woocommerce#14967]
### EXPLANATION OF THE ISSUE

In the WC Logger, log entries shown from the database interface are not displaying in true chronological order as the events are fired. This occurs because the events are ordering by the second in the timestamp. If the timestamps were order by milliseconds the events should show in the actual sequence as they occur. 

### STEPS TO REPRODUCE THE ISSUE
Create several wc_logger events that run sequentially in the codebase in close timestamp proximity. The WC Log in the wp admin will show those events out of order if they occur within the same second.

**Comment by mikejolley** [comment]
http://stackoverflow.com/questions/14038746/how-to-insert-a-microsecond-precision-datetime-into-mysql

**Comment by reescott** [comment]
I implemented a possible fix for this by moving the responsibility of the timestamp to the database. Please see it here: https://github.com/woocommerce/woocommerce/pull/15010

**Comment by sirreal** [comment]
If I'm not mistaken, the timestamp will be insufficiently precise, but the logs are inserted sequentially.

A simple solution when ordering by time might be to order on `timestamp` and `log_id` columns [here](https://github.com/woocommerce/woocommerce/blob/656508f65268dea0109f63f768986123a5f75588/includes/admin/class-wc-admin-log-table-list.php#L299-L315). @reescott this might be a simpler fix with better MySQL coverage if you care to have a look.

**Comment by reescott** [comment]
@sirreal That sounds like a much simpler solution. I will give it a try and submit a new pull request.
