### ISSUE TITLE
VAT calculation seems to be based on name, should be on "type"

### ISSUE THREAD

**Issue by Alphabc** [woocommerce/woocommerce#14968]
### EXPLANATION OF THE ISSUE
Hi,
I'm running 3.0.5 version.
It seems the VAT calculations, when "itemized" is selected, are done through some sort of group by "VAT name"

![image](https://cloud.githubusercontent.com/assets/24738945/25871355/7d467baa-3507-11e7-90e6-f17c31117266.png)

### STEPS TO REPRODUCE THE ISSUE

For instance, I needed to have 2 VAT rates, but with same name (in French, TVA)
So I filled in the 2 tables, both for standard & reduced rates, but with same name "TVA"

![image](https://cloud.githubusercontent.com/assets/24738945/25871528/1cc5bae2-3508-11e7-87f2-c956e8f357ae.png)
![image](https://cloud.githubusercontent.com/assets/24738945/25871559/3cc8de96-3508-11e7-917b-bd230e488253.png)

And I didn't understand why I only had 1 line even though I had 2 columns
![image](https://cloud.githubusercontent.com/assets/24738945/25871783/f09cb4e2-3508-11e7-9965-d52dd4531a3a.png)

Changing name to different ones did the thing...
But **in my opinion** (maybe I'm wrong :) ), this should not be the good behaviour as the calculation is done on name (value in database) & not on the id or the type
VAT for reduced rate & VAT for standard rate are not same kinds of VAT rates, so the VAT total at bottom of cart, order or invoice should behave as for the columns

Tks!

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://xxxx
Site URL: https://xxxx
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –

WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: nginx/1.10.2
PHP Version: 7.0.16

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Votre serveur n’a pas la classe SoapClient activée - certaines extensions de passerelle utilisant SOAP peuvent ne pas fonctionner correctement.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: cb_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base boutique: ❌ Page non définie
Panier: #45 - /panier/
Commande: #13 - /commande/
Mon compte: #20 - /mon-compte/

### Theme ###

Name: Avada Child
Version: 1.0.0
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.1.6
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

`
</details>

**Comment by mikejolley** [comment]
Merging by name was a common request a few major versions back - some countries desire this behavior when the tax name is the same.

Changing the name is the correct cause of action so each tax line has a unique name (makes more sense on the totals too).

Thanks
