### ISSUE TITLE
Custom order_item_type does not work for get_items()?

### ISSUE THREAD

**Issue by pavelevap** [woocommerce/woocommerce#14961]
Hi,

I used custom `order_item_type` for adding items through `wc_add_order_item()` function.
But after update to 3.0.x `$order->get_items( 'my_custom_type' )` no longer returns saved order items?

**Comment by mikejolley** [comment]
Custom types will have no associated class so won't function. Each type (fee, line_item, shipping) has a dedicated class in 3.0 which adds more structure.

Someone is working on an alternative; see https://github.com/woocommerce/woocommerce/pull/14678

**Comment by pavelevap** [comment]
OK, thank you, I will check it!

But as I understand it correctly, there is currently no way to get it working? And also adding order items will not work? So it worked well in 2.6.x and it is broken in 3.0.x? Any suggestion what to do with stored data (except not updating WooCommerce)?

**Comment by mikejolley** [comment]
Based on the report, no not yet. Custom order item types I don't think have ever been documented?

**Comment by pavelevap** [comment]
I am not sure, but I wanted to save custom data related to order payment somewhere outside postmeta table. I found database table and functions for order items and I thought it is a good idea :-) And it worked well in 2.6.x, there was an `order_item_type` parameter, everything looked nice :-(

What is the best approach to store similar data (related to order payment)?

**Comment by mikejolley** [comment]
What type of data exactly?

**Comment by pavelevap** [comment]
Electronic evidence of orders required by our government. With every order we have to send order amount and taxes automatically and I stored it as custom order item (with items meta values like date, required data + response value and date from government server).

**Comment by mikejolley** [comment]
That doesn't really sound like an order item - order items are essentially line items. tax, shipping, products, fees.

Is meta really not suitable?

**Comment by pavelevap** [comment]
It was a great plan :-( Order item fits better, I guess, this feature is related only to some payment methods and it is part (item) of order (response id is only special item for particular order).

But after further reading, it seems to me, that it could be possible to use current approach with the help of `woocommerce_data_stores` and `woocommerce_get_order_item_classname` filters and creating own classes `WC_Order_Item_Custom` and `WC_Order_Item_Custom_Data_Store` (only with simple methods - I could move here some of my current methods)?

And it seems that `wc_add_order_item()` works well with custom `order_item_type`, so the only problem is `get_items()` method. I will try to play with it, but it is still unexpected regression in 3.0.x :-(

**Comment by mikejolley** [comment]
Right; see the PR for that

**Comment by pavelevap** [comment]
OK, thank you! This is my minimum code to make `get_items( 'custom' )` working again.

```
add_filter( 'woocommerce_order_type_to_group', 'custom_group';
add_filter( 'woocommerce_get_order_item_classname', 'custom_classname', 10, 2 );
add_filter( 'woocommerce_data_stores', 'custom_stores' );

function custom_group( $types ) {
  $types['custom'] = 'custom_lines';
  return $types;
}
  
function custom_classname( $classname, $item_type ) {
  if ( $item_type == 'custom' ) {
    $classname = 'WC_Order_Item_Custom';
  }
  return $classname;
}
  
function custom_stores( $stores ) {
  $stores['order-item-custom'] = 'WC_Order_Item_Custom_Data_Store';
  return $stores;
}

class WC_Order_Item_Custom extends WC_Order_Item {
  public function get_type() {
    return 'custom';
  }
}

class WC_Order_Item_Custom_Data_Store extends Abstract_WC_Order_Item_Type_Data_Store implements WC_Object_Data_Store_Interface, WC_Order_Item_Type_Data_Store_Interface {
}
```

Maybe I am missing something, but it works now. BTW, data storages are interesting :+1: 

This is a little bit different issue (related to mentioned PR), but it would be nice to have default values and classes (maybe dummy instances of abstract classes) to allow `get_items( 'custom' )` working **automatically** as in 2.6.x?
