### ISSUE TITLE
PayPal drops cart on checkout

### ISSUE THREAD

**Issue by siriusmw** [woocommerce/woocommerce#14976]
Are you working on a fix for this? Is it related to the major Woo Commerce upgrade? If so, we have to revert. (It was working fine until last night.)

### EXPLANATION OF THE ISSUE

Checkout drops when moving to PayPal

### STEPS TO REPRODUCE THE ISSUE
Intermittent. Check Out, proceed to PayPal, transaction is cancelled. Happens in all browers. Please see GitHub thread.

https://github.com/woocommerce/woocommerce/issues/14956 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
PayPal issue being discussed here affecting all versions and other software platforms.

https://github.com/woocommerce/woocommerce/issues/14956
