### ISSUE TITLE
language bug, how to fix it

### ISSUE THREAD

**Issue by philippeheon** [woocommerce/woocommerce#14977]
### EXPLANATION OF THE ISSUE

Hi,
           I am presently using the seven child theme, and i have a major bug on my online store, the home laguage is french, and nothing seems to work. Everything works ok in english, is it the theme of wpml, or woo commerce. 

How can i fix my problem, what would i need to check?

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
You didn't include much detail, but if you mean features under the other language, WPML

If you mean translation of strings, see https://wordpress.org/support/topic/updating-translations-after-updates/

Thanks
