### ISSUE TITLE
Non-static method WC_Geolocation

### ISSUE THREAD

**Issue by MichaelCalleia** [woocommerce/woocommerce#14970]
### EXPLANATION OF THE ISSUE

Updated to Version 3.0.6 and now seeing this erros:
Strict Standards: Non-static method WC_Geolocation::is_ip_address() should not be called statically in /srv/bindings/f70355488c4d479bb15f3cf4ea650786/code/wp-content/plugins/woocommerce/includes/class-wc-geolocation.php on line 106

### STEPS TO REPRODUCE THE ISSUE

Sorry it is on a dev site, so can't give the location to see it.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://dev-calleia.pantheonsite.io
Site URL: http://dev-calleia.pantheonsite.io
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.8.1
PHP Version: ❌ 5.5.24 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 120
PHP Max Input Vars: 10000
cURL Version: 7.40.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (21) ###

Native PHP Sessions for WordPress: by Pantheon – 0.6.0
Advanced Custom Fields: by Elliot Condon – 4.4.11
Akismet Anti-Spam: by Automattic – 3.3.1
Broken Link Checker: by Janis Elsts
Vladimir Prelovac – 1.11.2

Duplicate Post: by Enrico Battocchi – 3.2
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
Jetpack by WordPress.com: by Automattic – 4.9
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
No Category Base (WPML): by Marios Alexandrou – 1.3
Pantheon HUD: by Pantheon – 0.1.1
Public Post Preview: by Dominik Schilling – 2.6.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SendGrid: by SendGrid – 1.11.2
TinyMCE Advanced: by Andrew Ozz – 4.5.6
Toggle wpautop: by Linchpin – 1.2.5
WooCommerce: by Automattic – 3.0.6
WordPress Popular Posts: by Hector Cabrera – 3.3.4
Yoast SEO: by Team Yoast – 4.7.1
WP Job Manager: by Automattic – 1.25.3
WP Redis: by Pantheon
Josh Koenig
Matthew Boynes
Daniel Bachhuber
Alley Interactive – 0.6.1

WP-Sweep: by Lester 'GaMerZ' Chan – 1.0.10

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #974 - /cart/
Checkout: #975 - /checkout/
My account: #976 - /my-account/

### Theme ###

Name: 
Version: 4.0
Author URL: http://calleia.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by enigmatik2** [comment]
Same thing happened to me

**Comment by votrungtruong90** [comment]
I found the same

**Comment by WackoMako** [comment]
Happening to me too....Its fine on my computer but this error shows up on another

**Comment by kwlvarun** [comment]
Getting below error on my site:
Deprecated: Non-static method WC_Geolocation::is_ip_address() should not be called statically in /srv/users/serverpilot/apps/celeberry/public/wp-content/plugins/woocommerce/includes/class-wc-geolocation.php on line 106

**Comment by halakoukeh** [comment]
Still getting the same issue as well.
