### ISSUE TITLE
How to reduce stock when generating order via REST API?

### ISSUE THREAD

**Issue by ddhara** [woocommerce/woocommerce#14988]
Hi

When order is generated from the website stock is being reduced but when am going to generate same order via REST API stock remains as it is.

How to maintain stock using REST API? I am using `woocommerce 3.0.5` and `REST API v2`

**Comment by mikejolley** [comment]
Stock will reduce when the payment is made - use the set_paid option. https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

**Comment by ddhara** [comment]
I am using `set_paid = true` when creating order using `REST API` but it's not reducing stock when canceling using `REST API to update order`. API which am using is 

`/wp-json/wc/v2/orders/<id>` using `PUT` method and passing parameter `'status' => 'cancelled`

 So now what if payment method is COD? I can't use `set_paid = true`.
