### ISSUE TITLE
Add a scalar check on order item meta

### ISSUE THREAD

**Issue by tobiasschutter** [woocommerce/woocommerce#14983]
### EXPLANATION OF THE ISSUE

A Fatal Error appears on the order page when the order item meta contains an object.

WC version: WC 3.x and later ( also 3.1.0alpha )
WP version: 4.7.4

### STEPS TO REPRODUCE THE ISSUE

1. Add a stdClass or any object to order item meta. For example: `wc_update_order_item_meta( 1, '_meta_example', new stdClass );`
2. Go to the Order page which has the item ( in this case id:1 )
3. A Fatal Error appears

`
Catchable fatal error: Object of class stdClass could not be converted to string in /woocommerce/includes/class-wc-order-item.php on line 189
`

### SOLUTION

WC_Order_Item::get_formatted_meta_data needs a patch. Add a scalar check on each $meta->value before casting it to a string.

**Comment by CasperBraske** [comment]
Arrays won't pass this check, then undoing the fix to #13556.
