### ISSUE TITLE
Shipping rates using incorrect details when calculated during processing checkout 

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#14985]
Steps to reproduce:

- Have at least one shipping method enabled (needs to log destination address to see the problem)
- Save both a billing address and a shipping address for a logged in user
- Add an item to the cart and proceed to checkout
- In the checkout change the shipping address (with a different city/address line 1)

In my test I added the following logging code to the Local Pickup rate to view the destination address:

```
$logger = new WC_Logger();
ob_start();
var_dump( $package['destination'] );
$logger->debug( ob_get_clean() );
```

When processing the checkout the function [update_session](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L718) is called. This first saves some of the billing/shipping fields (country, state, postcode) and then it calls `WC()->cart->calculate_totals()`. Part of calculating the totals is to recalculate the shipping costs.

However when getting the shipping packages it uses the following code for the destination address:

```
'destination'     => array(
	'country'   => WC()->customer->get_shipping_country(),
	'state'     => WC()->customer->get_shipping_state(),
	'postcode'  => WC()->customer->get_shipping_postcode(),
	'city'      => WC()->customer->get_shipping_city(),
	'address'   => WC()->customer->get_shipping_address(),
	'address_2' => WC()->customer->get_shipping_address_2(),
),
```

Since in the [update_session](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L718) function only the country, state and postcode fields were saved for the customer, the city and address fields will be loaded from the Address which has been previously saved for the customer, instead of the ones entered at checkout.

If one of the Shipping Methods returns an error because it can't ship to the "Invalid" address then the customers saved details will only have been partially updated.

The rest of the address fields are saved when the [process_customer](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L943) function has been called.

**Comment by krugazul** [comment]
Im having an issue with the update_session function as well.  I contribute to a Shipping plugin for South African sites, and their API relies on the "city" field to calculate the shipping costs. 

So the following happens
- The customer adds in their city and then places the order.
- During the "process_checkout" it updates the session, but only the country, state and postcode.
- Then when the shipping is calculated next it fails because the customers city in the session has not been updated yet.

I completely fixed my problem by adding in the billing_city and the shipping_city like the others in "update_session".

**Comment by mikejolley** [comment]
I think the inclusion of the addresses in the packages is more recent. Looks like it needs adding to `update_session` afterall.

**Comment by mikejolley** [comment]
@claudiulodro Should be a quick one for you :)
