### ISSUE TITLE
[API] Add support to Filter products by Attributes

### ISSUE THREAD

**Issue by hoseinit** [woocommerce/woocommerce#14986]
It is very vital for an Application based on WP/WC to have a user-friendly filter option. unfortunately I couldn't find a way to filter products by their attributes. please consider adding this feature in the next versions.

**Comment by mikejolley** [comment]
Please use http://ideas.woocommerce.com/forums/133476-woocommerce for feature requests.

We'll be expanding this naturally as https://github.com/woocommerce/woocommerce/issues/13645 related tasks are completed.
