### ISSUE TITLE
Variation images not updating correctly

### ISSUE THREAD

**Issue by manuelspaan** [woocommerce/woocommerce#14993]
### EXPLANATION OF THE ISSUE

When a variable product has a product image attached to it, variation images won't update correctly when you change a variation on the product page.

### STEPS TO REPRODUCE THE ISSUE

In the gif below you see a product page with multiple variations. When I change a variation nothing happens. When I change another variation the first variation change gets executed. Another variation change, and the second change executes. It seems like the variation is always lacking behind one step:

![select box lacking](https://cloud.githubusercontent.com/assets/14261188/25900923/65db4e4e-3595-11e7-837f-fb6da9a21be3.gif)

If I remove the product image, this won't happen. Here I've removed the product image:
![schermafbeelding 2017-05-10 om 15 30 51](https://cloud.githubusercontent.com/assets/14261188/25901065/d78b9ed6-3595-11e7-86b9-c3bf8827649e.png)

The following gif shows how I want the product page to work:
![select box working](https://cloud.githubusercontent.com/assets/14261188/25901214/5b57599e-3596-11e7-9c5d-3ee9ee066f3e.gif)

This is how the page should function. But because I've removed the product image, Product Gallery images I've attached to the product won't show up either.
![schermafbeelding 2017-05-10 om 15 36 55](https://cloud.githubusercontent.com/assets/14261188/25901275/8f3eeec0-3596-11e7-87ca-95503275b035.png)
![schermafbeelding 2017-05-10 om 15 37 06](https://cloud.githubusercontent.com/assets/14261188/25901279/94aa698e-3596-11e7-860a-2082b6532b04.png)

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: http://ppsk-kiosk.com
Site URL: http://ppsk-kiosk.com
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1800
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.16
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-Spam: by Automattic – 3.3.1
All-in-One WP Migration: by ServMask – 6.43
Fusion Builder: by ThemeFusion – 1.1.6
Fusion Core: by ThemeFusion – 3.1.6
Slider Revolution: by ThemePunch – 5.4.2
WooCommerce: by Automattic – 3.0.6

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #68 - /shop/
Cart: #70 - /cart/
Checkout: #72 - /checkout/
My account: #74 - /my-account/

### Theme ###

Name: Avada
Version: 5.1.6
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

`

**Comment by mikejolley** [comment]
I tested a few variations of this with Storefront and 2012 themes, and also with the new gallery on and off.

My variable product has 1 attribute, variations, images set for variations + main featured image, and I forced the 'ajax' loading via code.

In all case, the image changed once the ajax load had completed. It was not 1 step behind. I suspect a theme issue but unfortunately I cannot test premium themes. You may want to get a test site or do a test with another theme briefly to confirm. 

Closing as I cannot replicate, but feel free to comment back if you find anything else.

**Comment by manuelspaan** [comment]
I found out it's caused by my Avada theme. Without it activated it works great. Thanks for the help nonetheless.

**Comment by lmchenry91** [comment]
Hello Manuelspaan.  I am having this EXACT same issue with Avada.  I'm curious if you ever found a fix? I have everything updated and running on current versions and still having issues.  I have been having the issue for quite some time, i guess i was just hoping an update would fix it which it unfortunately hasn't.

**Comment by wanderyang** [comment]
having the same issue, still looking for fix!!
