### ISSUE TITLE
rated-5 term automatically added to all products with changed visibility?

### ISSUE THREAD

**Issue by pavelevap** [woocommerce/woocommerce#14994]
After update to latest 3.0.x, terms for `product_visibility` were successfully created.

Example for product which was visible before update:
- `_wc_average_rating` was `0` in `wp_postmeta`
- no term was assigned to this product during update

But when I switched visibility of this product to exclude from search, following terms were assigned:
- `exclude-from-search` (from `product_visibility` taxonomy)
- `rated-5` (also from `product_visibility` taxonomy) :exclamation: 
 Second term should not be assigned in this case?

I switched visibility back to visible everywhere and:
- `exclude-from-search` term was correctly removed from product
- `rated-5` is still here :exclamation: 

Maybe I am missing something, but it seems strange to me.

**Comment by mikejolley** [comment]
`
if ( $rating_term = get_term_by( 'name', 'rated-5', 'product_visibility' ) ) {
		$wpdb->query( $wpdb->prepare( "INSERT IGNORE INTO {$wpdb->term_relationships} SELECT post_id, %d, 0 FROM {$wpdb->postmeta} WHERE meta_key = '_wc_average_rating' AND ROUND( meta_value ) = 5;", $rating_term->term_taxonomy_id ) );
	}
`

Thats ran in the updater. It's the same for all of the rating queries so all of them would fail if it were a bug and you'd have rated-1 to 5 on all of the products.

**Comment by pavelevap** [comment]
Yes, there is no problem during initial data migration, something wrong is when visibility manually changed and product updated.
