### ISSUE TITLE
Functions and classes missing

### ISSUE THREAD

**Issue by KuneStudio** [woocommerce/woocommerce#14999]
Hi,

I’m doing some cleaning in my themes and it seems that on a website I have a lot of errors from missing functions and classes from WooCommerce.
Do you have an idea of where that it can come from ?

Here are some of the errors :
`
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/ZA.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/HK.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/US.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/AU.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/MY.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/IR.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/PH.php on line 12
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/IE.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/ID.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/BG.php on line 13
PHP Fatal error:  Call to undefined function __() in /www/wp-content/plugins/woocommerce/i18n/states/JP.php on line 13

PHP Fatal error:  Call to undefined function wc_product_weight_enabled() in /www/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-shipping.php on line 4

PHP Fatal error:  Class 'Simplify_Object' not found in /www/wp-content/plugins/woocommerce/includes/gateways/simplify-commerce/includes/Simplify/Event.php on line 30

PHP Fatal error:  Class 'WP_Widget' not found in /www/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-widget.php on line 11

PHP Fatal error:  Call to undefined function esc_attr_e() in /www/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-download.php on line 4`

I'm using the last version of WP and Woocommerce.

Thanks ! and best regards

**Comment by mikejolley** [comment]
Something including those files before WordPress is loaded? They are standard WordPress functions.

**Comment by mikejolley** [comment]
Need to add abspath checks to prevent direct access.
