### ISSUE TITLE
REST API - sending orders and process payment on the backend

### ISSUE THREAD

**Issue by merhawifissehaye** [woocommerce/woocommerce#14991]
How do we send orders from the REST API and process payment - get payment status notification back on result.
I am currently doing it by setting the set-paid property to true when sending order. And I am processing payment on the client side. I searched for hooks to intercept order response before payment, but I couldn't discover that.

**Comment by mikejolley** [comment]
> I am currently doing it by setting the set-paid property to true when sending order. And I am processing payment on the client side

This is the only way. Our API does not support taking payments since there is no cross-gateway/secure way of doing so. The API does not handle user carts either FWIW
