### ISSUE TITLE
Removing zoom feature also removes magnifying icon

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce#15006]
When using the following code to remove the zoom feature, the magnifying icon also gets removed: 

```
add_action( 'after_setup_theme', 'remove_pg_zoom_theme_support', 100 );

function remove_pg_zoom_theme_support() { 
remove_theme_support( 'wc-product-gallery-zoom' );
}
```

Before adding the code: 

<img width="804" alt="screen shot 2017-05-10 at 7 08 32 pm" src="https://cloud.githubusercontent.com/assets/6198774/25911480/496ee7c4-35b4-11e7-8a29-15b09ccc1483.png">

Once the code is added: 

<img width="759" alt="screen shot 2017-05-10 at 7 08 52 pm" src="https://cloud.githubusercontent.com/assets/6198774/25911483/4cbdc210-35b4-11e7-9c1d-db2aaf5f37b6.png">

Checked on clean install (WP 4.7.4 | and WC 3.0.6 | Storefront 2.1.8 | Canvas 5.11.4 | also the default twentysixteen/seventeen themes)

Thanks!

**Comment by mikejolley** [comment]
Correct; without zoom the image itself is clickable!

**Comment by Felipe-NS** [comment]
How can I remove just the magnifying icon
