### ISSUE TITLE
Norway - Tax versus VAT

### ISSUE THREAD

**Issue by catrymer** [woocommerce/woocommerce#15001]
### EXPLANATION OF THE ISSUE

Norway is not included in the list of the "get_european_union_countries" function, but because it's a member of something called EØS it also uses the European VAT system. 

Norway should be coded such that it uses the term "VAT" instead of the term "Tax."

### RELATED TICKET

571893-zd-woothemes

**Comment by DavidAnderson684** [comment]
But, it's not part of the EU VAT system for digital goods at least, is it? Adding it to get_european_union_countries() has broad implications.
