### ISSUE TITLE
PowerPak broken: Designer > +Add a Style - Cannot get a header image to "Stick"

### ISSUE THREAD

**Issue by KennethErvinYoung** [woocommerce/woocommerce#15019]
### EXPLANATION OF THE ISSUE

PowerPak broken: Designer > +Add a Style - Cannot get a header image to "Stick". After "Save" followed by a "refresh" the Header Image is gone.

### STEPS TO REPRODUCE THE ISSUE

1. Install Power Pak
2. Click Appearance
3. Click Customze
4. Click PowerPak
5. Click Designer
6. Click Add a Style
7. Click in the Header region being sure it is highlighted
8. Scroll down to "Background Image"
9. Click Choose an Image
10. Select an Image
11. Click "Set as Background"
12. Then on return screen, Click "Save" in top right of leftmost column
13. Image is there, but if you refresh the screen, it disappears showing only the selected background color. 
Only the Default Header button outside of the PowerPak is able to set the header image, but this does so globally and powerpak should enable me to set a unique header image for each Page.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://kenontech.net
Site URL: http://kenontech.net
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.15-0ubuntu0.16.10.4
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.50.1
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (33) ###

ManageWP - Worker: by ManageWP – 4.2.18
Akismet Anti-Spam: by Automattic – 3.3.1
AMP: by Automattic – 0.4.2
Autoptimize: by Frank Goossens (futtta) – 2.1.0
Backup by blogVault: by Backup by blogVault – 1.46
Business Hours Indicator: by Maarten Belmans – 2.0.5
Business Profile: by Theme of the Crop – 1.1.4
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.2.1

Facebook for WooCommerce: by Facebook – 1.1.0
Glue for Yoast SEO & AMP: by Joost de Valk – 0.4.2
Google Maps Widget: by Web Factory Ltd – 3.55
Server IP & Memory Usage Display: by Apasionados
Apasionados del Marketing – 1.4.0

Storefront Footer Bar: by WooThemes – 1.0.3
Storefront Powerpack: by WooThemes – 1.3.1
Storefront Pro Skins: by pootlepress – 0.5.0
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri
Inc – 1.8.3

Theme Customisations: by WooThemes – 1.0.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.12.30.22

Upload Larger Plugins: by David Anderson – 1.4.1
User Role Editor: by Vladimir Garagulya – 4.32.3
Woocommerce Category Best Seller Widget: by Steve Stone – 1.0
WooCommerce Stripe Gateway: by WooCommerce – 3.1.8
Woocommerce Recently Viewed Products Widget: by Nguyen Ngoc Linh – 1.1
WooCommerce: by Automattic – 3.0.5 – 3.0.6 is available
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.3.8
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.7.1
WP Google Maps: by WP Google Maps – 6.4.03
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP Performance Score Booster: by Dipak C. Gajjar – 1.7.2
WP Smush: by WPMU DEV – 2.6.3
WP-SpamShield: by Scott Allen – 1.9.9.9.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #103 - /shop/
Cart: #104 - /cart/
Checkout: #105 - /checkout/
My account: #106 - /my-account/

### Theme ###

Name: ProShop
Version: 2.0.6
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by claudiosanches** [comment]
This repository is for WooCommerce issues only, what you are reporting is better report to "Power Pak" author.
Thanks.

**Comment by KennethErvinYoung** [comment]
Excuse me but I bought PowerPak from WooCommerce and I therefore consider it your product. Why are you saying it's not a WooCommerce Product when from what I can tell it is and is not listed as a 3rd party plugin on your Support site and my money went to you!

Your response is both confusing and inadequate to a customer who has spent hundreds of dollars with WooCommerce. If you are unwilling to appropriately answer my support question please Connect me with your Supervisor.

Thank You and Best Regards,

Kenneth Ervin Young
Idea To Growth LLC - CEO
500 East Kennedy Blvd, 3rd Floor
Tampa, FL 33602
Web: www.IdeaToGrowth.com
Twitter: www.twitter.com/IdeaToGrowth/
Mobile: +1 (813) 407-8240
Skype: kennethervinyoung 
LinkedIn: www.linkedin.com/in/KennethErvinYoung
Email: Ken@IdeaToGrowth.com

On May 10, 2017, at 5:37 PM, Claudio Sanches <notifications@github.com> wrote:

Closed #15019.

**Comment by claudiosanches** [comment]
> Excuse me but I bought PowerPak from WooCommerce and I therefore consider it your product.

Note that this repository is for WooCommerce software, if you bought something in WooCommerce.com, so you need to open a ticket in WooCommerce.com and not here.

**Comment by claudiulodro** [comment]
Hi @KennethErvinYoung,

The GitHub page is for filing bugs and issues about the core WooCommerce plugin, and not associated extensions. We're not going to be able to troubleshoot or provide support for WooCommerce extensions on GitHub. To file a support ticket for products purchased through WooCommerce.com, please use [this link](https://woocommerce.com/my-account/tickets/).

Thanks!

**Comment by KennethErvinYoung** [comment]
Hi Claudia,

Thank you for the clarification. When I read your initial email it sounded like you were responding on behalf of WooCommerce, not GitHub- my apologies. I've had some recent bad customer experiences and and quick to shoot first. I had in parallel filed the same bug report on the WooCommerce support which had very confusing Support Ticket site on which it has a link, unclearly labelled which directs users to the GitHub site making it look like their support has moved there. It's a whale fail.

Thank You and Best Regards,

Kenneth Ervin Young
Idea To Growth LLC - CEO
500 East Kennedy Blvd, 3rd Floor
Tampa, FL 33602
Web: www.IdeaToGrowth.com
Twitter: www.twitter.com/IdeaToGrowth/
Mobile: +1 (813) 407-8240
Skype: kennethervinyoung 
LinkedIn: www.linkedin.com/in/KennethErvinYoung
Email: Ken@IdeaToGrowth.com

On May 10, 2017, at 7:14 PM, Claudiu Lodromanean <notifications@github.com> wrote:

Hi @KennethErvinYoung,

The GitHub page is for filing bugs and issues about the core WooCommerce plugin, and not associated extensions. We're not going to be able to troubleshoot or provide support for WooCommerce extensions on GitHub. To file a support ticket for products purchased through WooCommerce.com, please use this link.

Thanks!
