### ISSUE TITLE
Variable Product loading never stop

### ISSUE THREAD

**Issue by mochaumedia** [woocommerce/woocommerce#15025]
### EXPLANATION OF THE ISSUE
Woocommerce 3.0.6
Wordpress 4.7.4

When going to type in variations or attributes the loading in variations or attributes never stop loading.

### STEPS TO REPRODUCE THE ISSUE

Edit product
When go to variation: Error - Variations options never stop loading.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.bingoshop.dk
Site URL: http://www.bingoshop.dk
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 256 MB
PHP Time Limit: 60
PHP Max Input Vars: 5000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wpcg_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (21) ###

Ultimate Addons for Visual Composer: af Brainstorm Force – 3.16.7
Akismet Anti-Spam: af Automattic – 3.3.2
Constellation Menu: af Planetshine – 1.0.5
Contact Form 7: af Takayuki Miyoshi – 4.7
Flexible Shipping: af WP Desk – 1.9
Google Captcha (reCAPTCHA) by BestWebSoft: af BestWebSoft – 1.29
WPBakery Visual Composer: af Michael M - WPBakery.com – 4.12
Planetshine Demo Import: af Planetshine – 1.0
Ultimate Under Construction page: af HappyKite
Morrowmedia – 1.9.1

UpdraftPlus - Backup/Restore: af UpdraftPlus.Com
DavidAnderson – 1.13.1

WooCommerce Product Add-ons: af WooThemes – 2.7.13 – 2.8.1 er tilgængelig
WooCommerce Product Fees: af Caleb Burks – 1.2
WooCommerce Sequential Order Numbers: af SkyVerge – 1.8.1
WooCommerce: af Automattic – 3.0.6
Simple Mobile Payment Gateway: af Rune Stenstrøm – 1.0
WooCommerce Helper: af WooCommerce – 1.7.2 – Netværk aktiveret
WP Google Fonts: af Noah Kagan – v3.1.4
MailPoet nyhedsbrev: af MailPoet – 2.7.10
Widget Content Blocks: af Danny van Kooten – 2.3.6
YITH WooCommerce Ajax Search: af YITHEMES – 1.5.2
YITH WooCommerce Wishlist: af YITHEMES – 2.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop basisside: #7 - /shop/
Kurv: #8 - /kurv/
Checkout: #9 - /kassen/
Min konto: #10 - /min-konto/

### Theme ###

Name: BingoShop
Version: 1.1.18
Author URL: http://mochaumedia.dk
Child Theme: ❌ – Hvis du redigerer WooCommerce i et forældre-tema
som du ikke selv har udviklet
anbefaler vi at du anvender et "børne"-tema. Se: Hvordan du opretter et "Børne"-tema

WooCommerce Support: ✔

### Templates ###

Overrides: BingoShop/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
BingoShop/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
BingoShop/woocommerce/content-product_cat.php
BingoShop/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
BingoShop/woocommerce/global/breadcrumb.php
BingoShop/woocommerce/global/quantity-input.php
BingoShop/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0
BingoShop/woocommerce/loop/loop-end.php
BingoShop/woocommerce/loop/loop-start.php
BingoShop/woocommerce/loop/orderby.php
BingoShop/woocommerce/loop/pagination.php
BingoShop/woocommerce/loop/price.php
BingoShop/woocommerce/loop/rating.php version 2.0.0 is out of date. The core version is 3.0.0
BingoShop/woocommerce/loop/sale-flash.php
BingoShop/woocommerce/myaccount/my-address.php
BingoShop/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 3.0.0
BingoShop/woocommerce/single-product/add-to-cart/external.php
BingoShop/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.6
BingoShop/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
BingoShop/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
BingoShop/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
BingoShop/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
BingoShop/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.0.2
BingoShop/woocommerce/single-product/rating.php
BingoShop/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
BingoShop/woocommerce/single-product/review.php
BingoShop/woocommerce/single-product/sale-flash.php
BingoShop/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
BingoShop/woocommerce/single-product/tabs/description.php
BingoShop/woocommerce/single-product/tabs/tabs.php
BingoShop/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
BingoShop/woocommerce/single-product-reviews.php
</details>

**Comment by mikejolley** [comment]
See my answer here https://github.com/woocommerce/woocommerce/issues/14972#issuecomment-300402820
