### ISSUE TITLE
Missing Grouping Products option under Linked Products Tabs

### ISSUE THREAD

**Issue by erdivyang10** [woocommerce/woocommerce#15024]
Hello 
We have installed woocommerce version 3.0.4. While adding new product of type “simple” we are unable to find the “Grouping Products” option in the Linked Products Tab. We are unable to associate a simple product with a group product. In older version of woocommerce “Grouped Products” option was available through which we were able to search and associate a group product with current simple product.

Please assist.

**Comment by mikejolley** [comment]
It's part of the grouped product options, not the children.

**Comment by Talkrotimi** [comment]
Please, How to solve this in this new version 3.0.4

**Comment by kampiamodikuesto** [comment]
it's not confortable to link simple product from grouped product, if we have sevaral simple product we have to write each of them. Before it was easy use drop-down group menu from simple product. now if a product must me linkable to multiple group why not do this association from sample product?
