### ISSUE TITLE
Showing 'SSSSS' instead of star symbol in Product Review

### ISSUE THREAD

**Issue by ddhara** [woocommerce/woocommerce#15022]
In single product page it showing 'SSSSS' in place of star symbols. I have updated woocommerce version and also theme according to wc version and started facing this issue.

My current version of woocommerce is 3.0.5 and before that I was using 2.6.14

Screenshot of my webpage:

[link](https://www.hevaya.com/hevaya.png)

**Comment by mikejolley** [comment]
This is caused by missing fonts/styling in the theme. If you try a default theme or Strorefront for example it won't occur.
