### ISSUE TITLE
Date error with the North Theme of FuelThemes at the Thank You page

### ISSUE THREAD

**Issue by amaleather** [woocommerce/woocommerce#15035]
### EXPLANATION OF THE ISSUE

North Theme vs 3.1.1 and Woocommerce vs 3.0.7

### STEPS TO REPRODUCE THE ISSUE

You find the error at the Thank You page - The website is www.amaleather.com

### SYSTEM STATUS

<details>
```
/home/amaleath/public_html/wp-includes/functions.php on line 106-108-11
```
</details>

Warning: date() expects parameter 2 to be integer, object given in /home/amaleath/public_html/wp-includes/functions.php on line 106

Warning: date() expects parameter 2 to be integer, object given in /home/amaleath/public_html/wp-includes/functions.php on line 108

Warning: date() expects parameter 2 to be integer, object given in /home/amaleath/public_html/wp-includes/functions.php on line 111

**Comment by mikejolley** [comment]
If it's coming from template files inside the "North Theme" you need to tell the developer of that theme so they can patch it for their own users.
