### ISSUE TITLE
Improvement - Make WC_Checkout::get_posted_data() public

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#15038]
In WC 2.6 and earlier `WC_Checkout->posted` was a public property, useful to retrieve all the posted data at once. In WC 3.0+, the property has been replaced by method `WC_Checkout::get_posted_data()`, which is declared as "protected". This makes it impossible to access the posted data, unless one resorts to calling `WC_Checkout->posted` again (which triggers the deprecation notice, but works).

I believe that `WC_Checkout::get_posted_data()` should be made `public`, just like `get_posted_address_data()`, so that the data can be accessed as it was done before.

**Comment by mikejolley** [comment]
https://github.com/aelia-co/woocommerce/commit/8fd1366bbab76d54f1c28b95c961a73931034c70
