### ISSUE TITLE
Many products not visible on front end of store although appear on back end after update to woo commerce 3.0.5   

### ISSUE THREAD

**Issue by elainejackson** [woocommerce/woocommerce#15033]
On version 2.6.14 of woo commerce total products indicated on SHOP page is 293, which is correct. Once I update to version 3.0.5 the number of products indicated on SHOP page is 253. 40 products are no longer visible on front end but appear fine on back end.

### STEPS TO REPRODUCE THE ISSUE
1. Woocommerce version 2.6.14. View SHOP page and check number of products.
2. Update woo commerce plugin to 3.0.5
3. View SHOP page and check number of products.

### SYSTEM STATUS
`
### WordPress Environment ###

Home URL: http://exoticfishshop.org
Site URL: http://exoticfishshop.org
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (20) ###

VaultPress: by Automattic – 1.8.9
Akismet Anti-Spam: by Automattic – 3.3.2
PayPal Express Checkout for WooCommerce: by wpgateways – 1.1.9
WooCommerce - Gift Cards: by WP Ronin – 2.5.7
Jetpack by WordPress.com: by Automattic – 4.9
Meta Slider - Pro Addon Pack: by Matcha Labs – 2.6.8
Meta Slider: by Matcha Labs – 3.5.1
WP REST API: by WP REST API Team – 2.0-beta15
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.1

Import from eBay to WooCommerce: by WP Lab – 1.5.12
WooCommerce MailChimp: by Saint Systems – 2.1.0
WooCommerce Product Categories Selection: by PluginForage.com – 2.0
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0

WooCommerce: by WooThemes – 2.6.14
WooMobile: by Bowdie Mercieca – 1.2.4
WooCommerce Helper: by WooCommerce – 1.7.2
Yoast SEO: by Team Yoast – 4.7.1
WP-Lister Pro for eBay: by Matthias Krok – 2.0.18
WP Maintenance Mode: by Designmodo – 2.0.9
WP Rollback: by WordImpress – 1.4

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #7 - /shop/
Cart: #8 - /cart/
Checkout: ❌ Page does not contain the shortcode: [woocommerce_checkout]
My Account: #10 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Mystile
Version: 1.3.19
Author URL: http://www.woothemes.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

<!--
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

Before logging BUGS, ensure you:
I disabled all plugins and changed theme but problem continues to exist.

**Comment by elainejackson** [comment]
I have deleted all plugins except woo commerce and changed theme to storefront. The issue continues as above. 
SYSTEM STATUS:
The PHP is 5.6 and the checkout page does have the shortcode [woocommerce_checkout].

**Comment by mikejolley** [comment]
This one is impossible to replicate from the given report, however, it should be fairly easy to diagnose yourself.

1. Find a product that appears 'missing' on the frontend.
2. Edit it.
3. Check the visibility setting (top right) - if it's not catalog visible it will not show.
4. Check the status. If it's not published it will not show.
5. Check it's stock status. If you have the setting enabled to 'hide out of stock products from catalog' and it's not in stock, it will not show.

Those things affect visibility. If all look good, save the product. Does it appear? If yes, it's a data problem likely caused by imports not setting correct data. That could be an import plugin, or a plugin that syncs such as the lister on you're using.

Hope that helps.

**Comment by rafaelmcampos** [comment]
Hi!
In addition to the comment above by mikejolley, you can also add a star to this product, choosing highlight product. It can force the product to appear.
I'm having some problems like that in woocomerce / storefront child theme, suddently some products disappears from product pages. I solved this by highlighting the product.
