### ISSUE TITLE
Can No Longer Search Woocommerce Orders via Order Number??

### ISSUE THREAD

**Issue by jstormthakid** [woocommerce/woocommerce#15037]
### EXPLANATION OF THE ISSUE

I am always running the latest WooCommerce. We used to be able to Search the Orders page for a specific order simply by keying in either "#3177" or "3177" into the Search bar on the Orders page. Why was that function removed? **And How do we get it back?**

For easy customer service work, I need to key in an order number to quickly pull up an order.

### STEPS TO REPRODUCE THE ISSUE

1. Head to the Orders Page.
2. Key in any order number.
3. Watch the search results come up blank.

### SYSTEM STATUS

<details>

```
N/A
```
</details>

**Comment by mikejolley** [comment]
You just need to enter the number; it supports ID search:

![2017-05-12 at 10 06](https://cloud.githubusercontent.com/assets/90977/25991369/ca483638-36fa-11e7-8b65-ab1ea3c3d7cb.png)

**Comment by rkhoury82** [comment]
hi @mikejolley 
I am having this issue on a multi-site / network setup - I tried disabling all plugins and still occurs, wonder if its worth looking further into ?
Rudi

**Comment by mikejolley** [comment]
WC needs to be enabled per site, so it works the same on a network as each store is independent.

**Comment by rkhoury82** [comment]
@mikejolley yes I understand - I have enabled it enabled on each site - these are production stores that are working in every other way, I disabled all other plugins to ensure there are no conflicts and I am getting the same result as @jstormthakid reports.

@jstormthakid did you resolve or work out what the issue was?

**Comment by rkhoury82** [comment]
Found an error in the web server logs after searching - obviously the order number I searched was 42109

`2017-05-19 14:54:46.973 [NOTICE] [XXXXXXX:20417] [STDERR] WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')))  AND wp_posts.post_type = 'shop_order' AND ((wp_posts.post_status = 'wc-pend' at line 1 for query SELECT SQL_CALC_FOUND_ROWS  wp_posts.ID FROM wp_posts  WHERE 1=1  AND wp_posts.ID IN (42109,0) AND ((()))  AND wp_posts.post_type = 'shop_order' AND ((wp_posts.post_status = 'wc-pending' OR wp_posts.post_status = 'wc-processing' OR wp_posts.post_status = 'wc-on-hold' OR wp_posts.post_status = 'wc-completed' OR wp_posts.post_status = 'wc-cancelled' OR wp_posts.post_status = 'wc-refunded' OR wp_posts.post_status = 'wc-failed'))  ORDER BY wp_posts.post_date DESC LIMIT 0, 100 made by WP_Posts_List_Table->prepare_items, wp_edit_posts_query, wp, WP->main, WP->query_posts, WP_Query->query, WP_Query->get_posts`

**Comment by mikejolley** [comment]
That doesn't look like the search query we use - are you sure it's not a plugin?

**Comment by rkhoury82** [comment]
@mikejolley you are right, found the plugin culprit... my apologies!

**Comment by seacucumberinc** [comment]
We use to search by order number, name, phone number or portion of the address, but now only the order can be searched and found, but not others, other searches only show some orders or not found? Any idea?(Problem happen - After update to WooCommercence 3.0.7)

**Comment by rkhoury82** [comment]
I found the issue for me was a conflict with a plugin called "Search Anywhere" - check and double check your plugins which might not have been updated and are conflicting

**Comment by seacucumberinc** [comment]
@rkhoury82 but I don't have the "Search Anywhere" plugin!?
