### ISSUE TITLE
Product Attributes Tab doesn't display attributes

### ISSUE THREAD

**Issue by lddale** [woocommerce/woocommerce#15036]
### EXPLANATION OF THE ISSUE

When I add or edit a variable product, the attribute tab is not displaying any of the attribute items (it looks like the items might be "underneath" the tabs) - I cannot add/edit attributes for a variable product

### STEPS TO REPRODUCE THE ISSUE

Add a new product (or edit an existing product);   Select "Variable product" under product data (or it's already selected), then look at the Attributes tab (within the product data).   You can see that the left hand side of the tab data is missing... (there are no options to add attributes anywhere). (you only see Expand/Close on the far right).

![image](https://cloud.githubusercontent.com/assets/13694217/25975640/8f2020f2-367d-11e7-991b-258230606f23.png)

This image here shows that I do have attributes defined:
- 
![image](https://cloud.githubusercontent.com/assets/13694217/25975690/e69997f0-367d-11e7-9a76-bd26ed7893a1.png)

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://ontariozcar.com
Site URL: http://ontariozcar.com
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (32) ###

a3 Lazy Load: by a3 Revolution – 1.7.1
Accordions: by pickplugins – 2.0.17
Advanced post slider: by digontoahsan – 2.5.0
Akismet Anti-Spam: by Automattic – 3.3
All-in-One Event Calendar Extended Views by Time.ly: by Time.ly Network Inc. – 1.2.0
All-in-One Event Calendar by Time.ly: by Time.ly Network Inc. – 2.5.19
Black Studio TinyMCE Widget: by Black Studio – 2.3.2
BNS SMF Feeds: by Edward Caissie – 2.1
Contact Form 7: by Takayuki Miyoshi – 4.4.2
PayPal Shopping Cart: by Scott Paterson – 1.1.9
Form Maker Pro: by WebDorado – 2.8.17
Jetpack by WordPress.com: by Automattic – 3.9.6
jQuery UI Widgets: by David Gwyer – 0.50
News Headline Ticker: by S M Hasibul Islam – 2.3.3
OSD Social Media Sharing: by OSD Web Development Team – 3.5.6
Photo Gallery: by Photo Gallery Team – 1.3.38
Huge IT Product Catalog: by http://huge-it.com/ – 9.2.2
PTA Member Directory: by Stephen Sherrard – 1.6.8
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Responsive Lightbox: by dFactory – 1.6.12
Simple Ads Manager: by minimus – 2.9.8.125
Page Builder by SiteOrigin: by SiteOrigin – 2.4.25
SiteOrigin Widgets Bundle: by SiteOrigin – 1.8.4
Social Media Buttons & Widgets: by Ruel Nopal – 1.4.1
TinyMCE Advanced: by Andrew Ozz – 4.2.5
Welcome to WordPress: by Starfield Technologies – 1.0
WooCommerce: by Automattic – 3.0.6
WordPress Importer: by wordpressdotorg – 0.6.3
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.91
WP PDF: by wppdf.org – 1.0.0
Xpert Accordion: by ThemeXpert – 1.8
YouTube Channel: by Aleksandar Urošević – 3.0.11

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1134 - /?page_id=1134
Cart: #1135 - /?page_id=1135
Checkout: #1136 - /?page_id=1136
My account: #1137 - /?page_id=1137

### Theme ###

Name: Hueman
Version: 1.5.4 – 3.3.10 is available
Author URL: http://alxmedia.se
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
```
Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
```

This looks like a conflict/plugin issue, and your status reports lists several plugins active, so I suspect you have not tried this yet.
