### ISSUE TITLE
Auto accept terms and conditions when using google payment request api?

### ISSUE THREAD

**Issue by shawaj** [woocommerce/woocommerce#15040]
Hi there,

Is there a way with WooCommerce to auto-accept the terms and conditions when using a specific payment method?

For example, using the official stripe plugin and using Apple Pay / Google Payment Request API from the cart page, the payment looks to be successful through the payment request API but then it returns an error and you get sent back to the cart page where it has an error message "You must accept our terms and conditions" 

Is there a way to override the need to tick this box when using Apple Pay / Google Payment Request API?

Thanks

**Comment by mikejolley** [comment]
There is not, and I don't think users would desire this on the checkout. What you describe sounds like a bug in apple pay/stripe though - can you report via helpdesk or the Stripe repo?

CC'ing @mattyza to review this

**Comment by shawaj** [comment]
Users would not desire what on the checkout?

What I was suggesting, is a way to NOT have to accept the terms and conditions when using apple pay / google payment request API (or perhaps for it to auto-accept the terms and conditions somehow). Not sure whether this would happen on the WooCommerce side or the payment gateway side?

What I do know though, is that obviously nobody has tested the official WooCommerce Stripe Plugin with all settings options. Because this has basically stopped anyone from making any payments on mobile to us for about a week!

Coupled with the cock-up in the official WooCommerce Google Analytics plugin (missing the GA ID from the code!) it has altogether not been a good couple weeks for WC.

Why can't these things be tested before launch?

**Comment by mikejolley** [comment]
> What I was suggesting, is a way to NOT have to accept the terms and conditions when using apple pay / google payment request API

> What you describe sounds like a bug in apple pay/stripe

> CC'ing @mattyza to review this

**Comment by shawaj** [comment]
Have posted this over on the stripe plugin page too - https://github.com/woocommerce/woocommerce-gateway-stripe/issues/254

There is also an issue with that plugin whereby it completely ignores the chosen delivery address in Apple Pay / Google Payment Request API and just uses the customers default address in either of those two payment gateways.

**Comment by shawaj** [comment]
Thanks for your help @mikejolley

**Comment by mikejolley** [comment]
This will be taken care of in the stripe/apple pay repos.

**Comment by shawaj** [comment]
Thanks for you help @mikejolley :-)
