### ISSUE TITLE
"My Content" on membership area it gives a 404 error

### ISSUE THREAD

**Issue by DaisySpotebi** [woocommerce/woocommerce#15048]
When logged in users click "View" on their membership plan it gives a 404 error and doesn't actually go to the membership page. This issue started happening after Woocommece last update 3.0.6

STEPS TO REPRODUCE THE ISSUE
1. Login to your account.
2. Click "View" under your membership.
 3. You should go to the membership content but instead it gives a 404 error.

**Comment by mikejolley** [comment]
A quick fix may be to go to settings > permalinks and save so the rules are updated. If that doesn't work, please use the help desk because memberships is a premium plugin https://woocommerce.com/my-account/tickets/

**Comment by DaisySpotebi** [comment]
It worked, thank you!


On May 15, 2017, at 11:54 AM, Mike Jolley <notifications@github.com<mailto:notifications@github.com>> wrote:


A quick fix may be to go to settings > permalinks and save so the rules are updated. If that doesn't work, please use the help desk because memberships is a premium plugin https://woocommerce.com/my-account/tickets/
