### ISSUE TITLE
Missing ASC/ DESC sort for Featured Products in product listing

### ISSUE THREAD

**Issue by SensicalCat** [woocommerce/woocommerce#15044]
Running on several different sites, in versions 3.0.5 and 3.0.6 I have lost the ability to sort my products by Featured Product. wp 4.7.4

It may have appeared earlier, but I just noticed it.

**Comment by mikejolley** [comment]
With the move to terms (instead of meta) this is no longer technically possible. WP does not allow sorting by terms.
