### ISSUE TITLE
Select2 4.0.3 causing tabbing problem on select dropdown.

### ISSUE THREAD

**Issue by ssuess** [woocommerce/woocommerce#15049]
This problem seems to be inside an external component (Select2), so not sure if it is up to them to fix this, but in any case perhaps Woo should revert to earlier version.

### EXPLANATION OF THE ISSUE
Current version of Select2 (4.03) causes tabbing problem for select dropdowns (tab order reset after selecting)

### STEPS TO REPRODUCE THE ISSUE
1. Add a new order
2. Open billing address edit, fill in fields, tabbing to get to next one after input. When getting to selection for state dropdown, after selecting/entering, tab order is reset to top of page instead of next field (email address).

### WORKAROUND
reverting select2 to version 4.0.2 fixes this problem.

**Comment by mikejolley** [comment]
This is indeed a select2 bug. We do workaround this on the CHECKOUT because it impacts customers, but it needs fixing in Select2 to fix all other instances.

FWIW we're considering a custom version of select2 for future versions so we can include fixes ourselves.

**Comment by ssuess** [comment]
Any updates on this? I am forced with each and every update to hand fix select2 because tabbing is so badly broken.

**Comment by mikejolley** [comment]
Check our beta of 3.2

**Comment by ssuess** [comment]
thanks!
