### ISSUE TITLE
Override class-wc-structured-data.php

### ISSUE THREAD

**Issue by SensicalCat** [woocommerce/woocommerce#15045]
I need to modify the new json+ld data for schema to include the following.
brand, include condition (new), and we use the excerpt (short description) as our description data. I currently modify class-wc-structured-data.php. but that is wrong way, and obviously with each update i need to remember to upload a new version.

so, how can i over ride this file, is there a hook, or over ride method?

here are the items i added.
from: function generate_product_data
$markup['brand']  = $shop_name;
'itemCondition' => 'http://schema.org/NewCondition',
'description'   => $product->get_short_description(),

**Comment by mikejolley** [comment]
There are several apply_filter and do_action calls in https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-structured-data.php you can use. 

I cannot give you the code to do so though.

**Comment by Trebacz** [comment]
I had a similar issue and solved it using this code in my functions.php vs modifying WooCommerce code. All of our products are new, so it was a relatively easy hack:
```// Add additional structured data  to Product Offers
add_filter('woocommerce_structured_data_product_offer','trebacz_add_meta');
function trebacz_add_meta($markup_offer_trebacz) {
                if ( ! is_object( $product ) ) {
                        global $product;
                }
                if ( ! is_a( $product, 'WC_Product' ) ) {
                        return;
                }

                if ( '' !== $product->get_price() ) {
                        $markup_offer_trebacz['itemCondition'] = 'https://schema.org/NewCondition';
                }
                return $markup_offer_trebacz;
}```

I just needed the item condition, but think you can modify for your needs. I'm not entirely sure the two if statement are needed...

**Comment by Trebacz** [comment]
There was a php error in my first suggestion (sadly it still "worked" under most conditions). Switching the is_object for isset now has proper logic. I also added the description concatenation as you originally asked.

`add_filter('woocommerce_structured_data_product_offer','trebacz_add_offer_meta');
function trebacz_add_offer_meta($markup_offer_trebacz) {
                if ( ! isset( $product ) ) {
                        global $product;
                }
                if ( ! is_a( $product, 'WC_Product' ) ) {
                        return;
                }
                if ( '' !== $product->get_price() ) {
                        $markup_offer_trebacz['itemCondition'] = 'https://schema.org/NewCondition';
                        $markup_offer_trebacz['description'] = $product->get_short_description().' '.$product->get_description();
                }
                return $markup_offer_trebacz;
}
`

**Comment by Lutinho** [comment]
Trebacz, thanks so much for that bit of code. I searched for so long to get item condition added to my structured 'offer' list, and this made it happen!

Sorry for hijacking:
I will also try to learn what it does technically. I imagine the only files affected/involved by this are functions.php and class-wp-structured-data.php? 

Thanks again!

**Comment by benabbott** [comment]
Hi

Is there a way to do this per product? I have about 20 products and i need their descriptions and to be

**Comment by bergeny** [comment]
> There was a php error in my first suggestion (sadly it still "worked" under most conditions). Switching the is_object for isset now has proper logic. I also added the description concatenation as you originally asked.
> 
> ```
> add_filter('woocommerce_structured_data_product_offer','trebacz_add_offer_meta');
> 
> function trebacz_add_offer_meta($markup_offer_trebacz) {
>                 if ( ! isset( $product ) ) {
>                         global $product;
>                 }
>                 if ( ! is_a( $product, 'WC_Product' ) ) {
>                         return;
>                 }
>                 if ( '' !== $product->get_price() ) {
>                         $markup_offer_trebacz['itemCondition'] = 'https://schema.org/NewCondition';
>                         $markup_offer_trebacz['description'] = $product->get_short_description().' '.$product->get_description();
>                 }
>                 return $markup_offer_trebacz;
> }
> ```

Unfortunately your code doesn't return both values but just the first one instead, which is 
                        $markup_offer_trebacz['itemCondition'] = 'https://schema.org/NewCondition';

**Comment by Trebacz** [comment]
I think it is still working, biut there is a bug in WooCommerce that is putting the product schema under the "BreadcrumbList" see #22024 .

**Comment by bergeny** [comment]
> I think it is still working, biut there is a bug in WooCommerce that is putting the product schema under the "BreadcrumbList" see #22024 .

Sorry my bad , yeah it does, it's working just fine but we can only modify what's under offers (price, availability, curreny,priceCurrency...) and can't modify description, any solution to do so ?

if we try your code to modify description, it just adds a description field under offers

and by the way I currently disabled woocommerce breacrumb, I'll find a solution for it later on

I just have 

Organization
Product
AggregateRating

**Comment by wcgooner** [comment]
Hey guys, this helped me a lot, but still having a few little issues that I was wondering if anyone knows how to fix (for our mutual benefit). 

1.) Is there a way to just make it output only the main description for the "description" field in the structured data? Currently with the code I've used from this thread, the structured data output has 2 "description" fields: 1 that uses the product short description and the other that uses the main description.

2.) How to we get it to pull the brand attribute for the "brand" structured data field? I notice it does it on random products but not all.

3.) For variable products, it never pulls the price of the variation, just the "lowPrice" and "highPrice". This confuses google and makes it seems that the price for a product variation is not specified. Anyone know how to make it output the price of a variation for specific product variation permalinks?
