### ISSUE TITLE
Variable products are not available to put in cart

### ISSUE THREAD

**Issue by welomoedia** [woocommerce/woocommerce#15043]
### EXPLANATION OF THE ISSUE

My WE-Version is 3.0.6. I had problems with different plugins so I cannot exactly say when the problem startet. But now exists the following problem:
Every time I add a product with variations it shows me in the frontpage that the product is not available although in the backend it shows me that it is in stock. I read already older issues about this problem and tried the there presented solutions. But nothing works. I have no problems withs single products. I even tried to produce a new single product. Tested it and it worked. Then I changed it to variable product and it stopped working. I tried it with "in stock" on product level and without and so on. I deaktivated my different plugins (WPML, Warehouses) but it doesn't help. I cannot put a variable product into the cart even when it shows me on the frontpage that it is in stock.

### STEPS TO REPRODUCE THE ISSUE

Probably you are not able to replicate. My steps are:
new product --> build variations --> activate stock management on variation level --> increase stock -->Activate the product --> try to put in cart --> "this product variation is not available"....

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
`
### WordPress Environment ###

Home URL: http://www.garten-schaffen.de/sittsame-kleidung
Site URL: http://www.garten-schaffen.de/sittsame-kleidung
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: ✔
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27-0+deb8u1
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_6_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ Die MaxMind GeoIP Datenbank existiert nicht - Die Ortung (Geolokalisierung) wird nicht funktionieren. Du kannst sie manuell installieren von http://dev.maxmind.com/geoip/legacy/geolite/ zu dem Pfad: . Scrolle einfach nach unten bis zu "Downloads" und lade die Datei "Binary / gzip" vom Typ "GeoLite Country" herunter. Denke bitte daran
die Datei GeoIP.dat.gz zu entpacken und nur die entpackte Datei GeoIP.dat hochzuladen.

### Security ###

Secure connection (HTTPS): ❌Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ✔

### Active Plugins (32) ###

Duplicator: von Snap Creek – 1.2.6
Instant Search + for WooCommerce Search: von Fast Simon Inc – 1.8.4
PayPal for WooCommerce: von Angell EYE – 1.4.3
WPML Multilingual CMS: von OnTheGoSystems – 3.7.0
WooCommerce Gateways Country Limiter: von OnTheGoSystems – 1.4
WooCommerce Multilingual: von OnTheGoSystems – 4.1.4
WooCommerce Stock Manager: von Vladislav Musílek – 1.1.4
WooCommerce Warehouses: von hellodev.us – 1.6.2.2
WooCommerce: von Automattic – 3.0.6
WP All Import: von Soflyy – 3.4.3
WPML Media: von OnTheGoSystems – 2.2.0
WPML Sticky Links: von OnTheGoSystems – 1.4.1
WPML String Translation: von OnTheGoSystems – 2.5.3
WPML Translation Management: von OnTheGoSystems – 2.3.0
YITH Essential Kit for WooCommerce #1: von YIThemes – 1.4.6
YITH WooCommerce Multi-step Checkout: von YITHEMES – 1.4.2
Antispam Bee: von pluginkollektiv – 2.7.1
Captcha by BestWebSoft: von BestWebSoft – 4.3.0
Contact Form by BestWebSoft: von BestWebSoft – 4.0.6
Disable Feeds: von Samir Shah
BBpress Unterstützung durch Matthew Sigley – 1.4.4

Do Follow: von Denis de Bernardy
Mike Koepke – 4.2.2

Enable Site Ping WPMU: von Sean Fisher – 1.0
Featured image widget: von Walter Vos – 0.4
Image Widget: von Modern Tribe
Inc. – 4.4.2

PHP Text Widget: von Stefano Lissa – 1.0.8
Posts Character Count Admin: von Jan Teriete – 2.1
Quttera Web Malware Scanner: von Quttera team – 3.0.7.5
UpdraftPlus - Backup/Restore: von UpdraftPlus.Com
DavidAnderson – 1.13.1

W3 Total Cache: von Frederick Townes – 0.9.5.4
WordPress MU Domain Mapping: von Donncha O Caoimh – 0.5.5.1
WP Keyword Link: von 柳城 – 1.7
Yoast SEO: von Team Yoast – 4.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #4 - /
Warenkorb: #5 - /warenkorb/
Kasse: #6 - /kasse/
Mein Konto: #7 - /mein-konto/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
Then it's probably missing a regular price..?

**Comment by welomoedia** [comment]
Ok, probably I forgot that when testing without the plugins. After retesting without plugins and making sure that every variation has a regular price I could verify that the problem comes with wpml for woocommerce.
Thank you for your fast reply and hint.
