### ISSUE TITLE
Customer search text indicates incorrect amount of characters

### ISSUE THREAD

**Issue by geeklore** [woocommerce/woocommerce#15056]
### EXPLANATION OF THE ISSUE

WooCommerce 3.0.6.

When manually adding a Subscription or Booking for example, you search for a customer. The minimum required amount of characters needed is 3, but drop down indicates 1 or more characters, which is causing confusion for some customers.

### STEPS TO REPRODUCE THE ISSUE

Manually add a Booking or Subscription product.

![see screen shot](http://cld.wthms.co/KjoD2+)
Link: http://cld.wthms.co/KjoD2

![see screen shot](http://cld.wthms.co/FP8IK+)
Link: http://cld.wthms.co/FP8IK

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://woocommerce.dev
Site URL: http://woocommerce.dev
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1k

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (11) ###

Bookings Helper: by WooCommerce – 1.0.0
WooCommerce Accommodation Bookings: by WooCommerce – 1.0.9
WooCommerce Bookings: by Automattic – 1.10.2
WooCommerce Dynamic Pricing: by Lucas Stark – 3.0.7
WooCommerce Product Vendors: by WooCommerce – 2.0.30
WooCommerce FedEx Shipping: by WooCommerce – 3.4.6
WooCommerce UPS Shipping: by WooCommerce – 3.2.3
WooCommerce Subscription Downloads: by WooCommerce – 1.1.6
WooCommerce Subscriptions: by Prospress Inc. – 2.2.6
WooCommerce: by Automattic – 3.0.6
WP Mail Logging: by Christian Zöller – 1.8.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Fifteen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
```
</details>

**Comment by mikejolley** [comment]
I believe the required number of chars was recently changed to better support ID based searches. Core indeed uses 1 char on the orders screen.

cc'ing @mattyza and @thenbrent to check this just in case they need to set a different limit or make the server side code match.

**Comment by thenbrent** [comment]
IMO this should be reopened. It's a bug in core, not extensions.

> The minimum required amount of characters needed is 3, but drop down indicates 1 or more characters

@geeklore is right, `WC_Ajax::json_search_customers()` still requires 3 characters _unless_ an integer is passed in.

For example, you might search with 2 valid characters that clearly exist in a customer's name, but still get the "_No matches found_" response, because `WC_Ajax::json_search_customers()` just calls [`wp_die()` when it gets less than 3 non-numeric characters](https://github.com/woocommerce/woocommerce/commit/7d223b67fb468bbf3991c9996e6ce76cad034f71#diff-133db5662c51f5686d87611121a05a3bR1233).

This screenshot shows this exact issue on the _Edit Order_ screen: https://cl.ly/33442r220546 (i.e. nothing to do with Subscriptions, Bookings or other extensions)

What `WC_Ajax::json_search_customers()` actually requires is 3 or more non-numeric characters _or_ 1 or more numeric characters. The requirement description may need to be updated to reflect that.

> I believe the required number of chars was recently changed to better support ID based searches. 

A quick `git bisect` shows it was changed by #14001 in 3.0.1.

**Comment by mikejolley** [comment]
The requirement text is on/off not conditional, so one of the criteria has to change.

**Comment by claudiosanches** [comment]
We could remove search by ID, since makes it too hard, and generally no ones know the users IDs.
