### ISSUE TITLE
Mobile Web Checkout Issue

### ISSUE THREAD

**Issue by Khalan20** [woocommerce/woocommerce#15055]
### EXPLANATION OF THE ISSUE

When on mobile website, on the checkout page where user enters billing details, The "phone number" and "email address" fields are not editable.  

### STEPS TO REPRODUCE THE ISSUE

1. Access woocoomerce on mobile web/site. 
2. Add products to car then proceed to checkout.
3. On checkout page try to change/enter your phone number and email address. 

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: http://mobiwizentertainment.com/store
Site URL: http://mobiwizentertainment.com/store
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: ✔
WP Memory Limit: 1,000 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_6_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

TinyMCE Advanced: by Andrew Ozz – 4.5.6
WooCommerce: by Automattic – 3.0.6
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.2.1

BuddyPress: by The BuddyPress Community – 2.8.2
myCRED: by Gabriel S Merovingi – 1.7.8.1
MobiLoud Canvas: by MobiLoud – 1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: MYC (P)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3 - /
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/

### Theme ###

Name: BuddyApp
Version: 1.3
Author URL: http://themeforest.net/user/SeventhQueen
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
I can only test my own store on mobile which does not have the issue - yours requires login.

See if it happens in your desktop browser when resizing the window. I've seen themes causing this with overlapping elements (which can be seen in the DOM inspector in the browser).

You did not mention if you tested another theme so do that first before reporting core bugs - its very likely it's a theme issue. Let us know.
