### ISSUE TITLE
Grouped products not listing individual products names

### ISSUE THREAD

**Issue by winepair** [woocommerce/woocommerce#15058]
### EXPLANATION OF THE ISSUE

Hi there, 
All my plugins and woocommerce are up to date. I have deactivated the lugins to see if they might solve the issue but no.

What happens is, when you click on the grouped product, where it used to list each item individually by name, it now lists them using the name and link of the prouped product.

E.g. instea dof listing the individual wines in a mixed case, it now lists, "mixed case, mixed case, mixed case".

### STEPS TO REPRODUCE THE ISSUE

You can see what i mean here:
http://winepair.co.za/shop/mixed-cases/mostly-whites-mixed-case-with-a-couple-of-reds/
### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://winepair.co.za
Site URL: http://winepair.co.za
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_ZA

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30-1~dotdeb+7.1
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 2500
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (32) ###

Akismet Anti-Spam: by Automattic – 3.3.2
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom ShortCode Creator: by swadeshswain – 2.0
Envato Market: by Derek Herman – 1.0.0-RC2
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Official Mad Mimi Signup Forms: by Mad Mimi
LLC – 1.5.1

MailChimp for WordPress: by ibericode – 4.1.2
Notely: by Michael Ott – 1.3
Official StatCounter Plugin: by Aodhan Cullen – 2.0.1
Taxonomy Dropdown Widget: by Erick Hitter – 2.3
WooCommerce Wishlist Plugin: by TemplateInvaders – 1.3.4
WC Force Pass: by Leo Baiano – 1.0.2
Widget Clone: by 93digital – 1.1
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 3.7
Advanced AJAX Product Filter for WooCommerce: by BeRocket – 1.1.8.1
WooCommerce Extended Coupon Features: by Soft79 – 2.4.3
Booster Plus for WooCommerce: by Algoritmika Ltd – 1.1.0
WooCommerce PayFast Gateway: by WooCommerce – 1.4.3
WooCommerce SnapScan Gateway: by SnapScan – 1.0.1
Woocommerce Gift Wrapper: by Little Package – 2.0.3
WooCommerce Advanced Product Quantities: by WP BackOffice – 2.1.9
Booster for WooCommerce: by Algoritmika Ltd – 2.7.1
WooCommerce Menu Extension: by August Infotech – 1.6
WooCommerce Min/Max Quantities: by WooCommerce – 2.3.16
WooCommerce My Account Widget: by Bart Pluijms – 0.5.0
WP All Import - WooCommerce Add-On: by Soflyy – 1.3.3
WooCommerce: by Automattic – 3.0.6
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.7.1
WP All Import: by Soflyy – 3.4.3
WP Mail Logging: by Christian Zöller – 1.8.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: ZAR (R)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #9 - /shop/
Basket: #23 - /cart/
Checkout: #24 - /checkout/
My account: #25 - /my-account/

### Theme ###

Name: Betheme
Version: 17.7.1
Author URL: http://muffingroup.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: betheme/woocommerce/archive-product.php
betheme/woocommerce/cart/cart-empty.php
betheme/woocommerce/cart/cart.php
betheme/woocommerce/cart/mini-cart.php
betheme/woocommerce/content-product.php
betheme/woocommerce/content-single-product.php
betheme/woocommerce/emails/admin-new-order.php
betheme/woocommerce/emails/customer-completed-order.php
betheme/woocommerce/emails/customer-new-account.php
betheme/woocommerce/emails/customer-note.php
betheme/woocommerce/emails/customer-on-hold-order.php
betheme/woocommerce/emails/customer-processing-order.php
betheme/woocommerce/loop/loop-end.php
betheme/woocommerce/loop/loop-start.php
betheme/woocommerce/loop/no-products-found.php
betheme/woocommerce/loop/pagination.php
betheme/woocommerce/notices/error.php
betheme/woocommerce/notices/notice.php
betheme/woocommerce/notices/success.php
betheme/woocommerce/single-product/add-to-cart/external.php
betheme/woocommerce/single-product/product-image.php
betheme/woocommerce/single-product/product-thumbnails.php
betheme/woocommerce/single-product/sale-flash.php
betheme/woocommerce/single-product/tabs/additional-information.php
betheme/woocommerce/single-product/tabs/description.php
betheme/woocommerce/single-product/tabs/tabs.php
betheme/woocommerce/single-product/title.php

### TI WooCommerce Wishlist Templates ###

Overrides: –
`
</details>

**Comment by transbetacism** [comment]
Same happens to me. I have tried: 

1. Removing the linked products and re-adding them. 
2. Creating a brand new Grouped Product. 

Both with the same results. **Tested with the Storefront theme**.

See screenshot below where each linked product has the same name as the Grouped Product.

![image 2017-05-14 at 4 19 46 em](https://cloud.githubusercontent.com/assets/9765146/26034727/343690a4-38c1-11e7-912b-48de4f4137a7.png)

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/14982
