### ISSUE TITLE
Product Importer; Background processing

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#15050]
Follow on from https://github.com/woocommerce/woocommerce/issues/13082

**Comment by johnlmccurdy** [comment]
I am quite new to using github and have searched the issues but this one seems most relevant. We use woocommerce (of course) and WP All Import Pro. Both plugins released new versions yesterday and I updated both. Today, all of our products which are uploaded daily using a cron and WP All Import are gone. I have tried manually uploading them but to no avail. 

In the end I have rolled back the database and plugin versions to those of a couple of days ago.

No settings had been changed, and the product variations simply didn't want to load in with the cron or manual upload. I was left with product title and description (although even that was only partial sentences in some cases.)

Is mine the same issue as above?

**Comment by mikejolley** [comment]
This issue is for a new feature we're building. Nothing to do with WP All import.
