### ISSUE TITLE
wc_get_page_id() depracated with no substitute

### ISSUE THREAD

**Issue by galbaras** [woocommerce/woocommerce#15068]
I use wc_get_page_id() to decide whether or not to display something on the page, regardless of the order involved. The code runs on pages that aren't even related to shopping, where an order isn't available.

Rather than directly using get_option() to get the slugs for endpoints, it will be good to have a replacement function for wc_get_page_id(), or simply to reinstate it.

Basically, I'd like the code below to work.

```
function gbol_is_woo_special_page( $page = '' ) {
	global $post;

	$woocommerce_pages = array(
		wc_get_page_id( 'myaccount' ),
		wc_get_page_id( 'edit_address' ),
		wc_get_page_id( 'cart' ),
		wc_get_page_id( 'checkout' ),
		wc_get_page_id( 'pay' ),
		wc_get_page_id( 'view_order' ),
	);
	if ( $page ) {
		return in_array( $page->ID, $woocommerce_pages );	
	} else {
		return in_array( $post->ID, $woocommerce_pages );	
	}
}
```

**Comment by mikejolley** [comment]
wc_get_page_id is not deprecated.

**Comment by galbaras** [comment]
Well, it writes messages to my error log and that's no fun either.

**Comment by mikejolley** [comment]
Then look at the messages and what they suggest - https://github.com/woocommerce/woocommerce/blob/d56d11f1aaf500a6927a0f7bf74a38db4d92d9d5/includes/wc-page-functions.php#L46

Some args are not pages as it explains.

**Comment by CreativForm** [comment]
Just searching an solution and your code works fine. Here is the example:

```
if(function_exists('wc_get_page_id'))
{
	if(in_array($post->ID, array(
		wc_get_page_id( 'myaccount' ),
		wc_get_page_id( 'edit_address' ),
		wc_get_page_id( 'cart' ),
		wc_get_page_id( 'checkout' ),
		wc_get_page_id( 'pay' ),
		wc_get_page_id( 'view_order' ),
	), true) !== false) continue;
}

```
