### ISSUE TITLE
API returns 404 after update

### ISSUE THREAD

**Issue by Gwildor** [woocommerce/woocommerce#15064]
### EXPLANATION OF THE ISSUE

Since updating Wordpress and WooCommerce, the REST API no longer works. Pages like `/wp-json/` and `/wp-json/wp/v2/` work fine, but `/wp-json/wc/v1/` and `/wp-json/wc/v2/` return the Wordpress 404 page (so not the REST API 404 error). All the pages under the `/wc/` namespace are still listed on the root `/wp-json/` page. Using `index.php?rest_route=/wc/v2/` works fine, which made me think that this was a permalinks issue, but refreshing those by resaving them does not help.

### STEPS TO REPRODUCE THE ISSUE

* Visit `/wp-json/`. Ensure that all routes under `/wc/v1/` and `/wc/v2/` are there.
* Visit `/wp-json/wc/v2/`. Get HTML 404-page instead of a JSON result.
* Visit `index.php?rest_route=/wc/v2/`. Get a JSON result with all routes listed, as expected.

### SYSTEM STATUS

<details>

### WordPress Environment ###

Home URL: https://m.pearle.be
Site URL: https://m.pearle.be
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_BE

### Server Environment ###

Server Info: Apache/2
PHP Version: ❌ 5.5.32 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.19.1 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.5
WC Database Prefix: wpbe_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

ACF to REST API: by Aires Gonçalves – 2.2.1
Advanced Custom Fields Multilingual: by OnTheGo Systems – 0.4
Advanced Custom Fields: by Elliot Condon – 4.4.11
Application Passwords: by George Stephanis – 0.1-dev
Cleanup Duplicate Meta: by WP Developers Club and Tonya – 1.0.2
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12.1
Multilingual Tools: by WPML Compatibility Team – 1.2
CF Page or Post Duplicator: by Carlos Fazenda – 0.1
WooCommerce Product Filter: by Mihajlovic Nenad – 5.8.5
Redirection: by John Godley – 2.5
Responsive Menu Pro: by Responsive Menu – 3.0.11
WP REST API: by WP REST API Team – 2.0-beta15
WPML Multilingual CMS: by OnTheGoSystems – 3.7.0
WooCommerce Extra Product Sorting Options: by SkyVerge – 2.6.0
WooCommerce Multilingual: by OnTheGoSystems – 4.1.3
WooCommerce WishLists: by Lucas Stark – 2.0.4 – 2.0.5 is available
WooCommerce: by Automattic – 3.0.5 – 3.0.6 is available
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 3.7.2
Wordpress Amazon Web Services: by Sander Heling – 0.1
Wordpress Amazon S3 and CloudFront: by Sander Heling – 0.1
WPML All Import: by OnTheGoSystems – 2.0.3
WPML CMS Nav: by OnTheGoSystems – 1.4.20
WPML Media: by OnTheGoSystems – 2.2.0
WPML Sticky Links: by OnTheGoSystems – 1.4.1
WPML String Translation: by OnTheGoSystems – 2.5.3
WPML Translation Management: by OnTheGoSystems – 2.3.0
WPtouch Pro: by WPtouch – 4.3.13

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #33 - /product
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page ID is set
but the page does not exist

### Theme ###

Name: Twenty Sixteen Child
Version: 1.0.0
Author URL: http://www.wend.nl
Child Theme: ✔
Parent Theme Name: Twenty Sixteen
Parent Theme Version: 1.3
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: twentysixteen-child/woocommerce/archive-product.php
twentysixteen-child/woocommerce/auth/footer.php
twentysixteen-child/woocommerce/auth/form-grant-access.php
twentysixteen-child/woocommerce/auth/form-login.php
twentysixteen-child/woocommerce/auth/header.php
twentysixteen-child/woocommerce/cart/cart-empty.php
twentysixteen-child/woocommerce/cart/cart-item-data.php
twentysixteen-child/woocommerce/cart/cart-shipping.php
twentysixteen-child/woocommerce/cart/cart-totals.php
twentysixteen-child/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
twentysixteen-child/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/cart/mini-cart.php
twentysixteen-child/woocommerce/cart/proceed-to-checkout-button.php
twentysixteen-child/woocommerce/cart/shipping-calculator.php
twentysixteen-child/woocommerce/checkout/cart-errors.php
twentysixteen-child/woocommerce/checkout/form-billing.php version 2.1.2 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/checkout/form-checkout.php
twentysixteen-child/woocommerce/checkout/form-coupon.php
twentysixteen-child/woocommerce/checkout/form-login.php
twentysixteen-child/woocommerce/checkout/form-pay.php
twentysixteen-child/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/checkout/payment-method.php
twentysixteen-child/woocommerce/checkout/payment.php
twentysixteen-child/woocommerce/checkout/review-order.php
twentysixteen-child/woocommerce/checkout/terms.php
twentysixteen-child/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/content-product_cat.php
twentysixteen-child/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/content-widget-product.php
twentysixteen-child/woocommerce/emails/admin-cancelled-order.php
twentysixteen-child/woocommerce/emails/admin-failed-order.php
twentysixteen-child/woocommerce/emails/admin-new-order.php
twentysixteen-child/woocommerce/emails/customer-completed-order.php
twentysixteen-child/woocommerce/emails/customer-invoice.php
twentysixteen-child/woocommerce/emails/customer-new-account.php
twentysixteen-child/woocommerce/emails/customer-note.php
twentysixteen-child/woocommerce/emails/customer-on-hold-order.php
twentysixteen-child/woocommerce/emails/customer-processing-order.php
twentysixteen-child/woocommerce/emails/customer-refunded-order.php
twentysixteen-child/woocommerce/emails/customer-reset-password.php
twentysixteen-child/woocommerce/emails/email-addresses.php version 2.4.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/emails/email-customer-details.php
twentysixteen-child/woocommerce/emails/email-footer.php
twentysixteen-child/woocommerce/emails/email-header.php
twentysixteen-child/woocommerce/emails/email-order-details.php version 2.5.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/emails/email-order-items.php version 2.1.2 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/emails/email-styles.php
twentysixteen-child/woocommerce/emails/plain/admin-cancelled-order.php
twentysixteen-child/woocommerce/emails/plain/admin-failed-order.php
twentysixteen-child/woocommerce/emails/plain/admin-new-order.php
twentysixteen-child/woocommerce/emails/plain/customer-completed-order.php
twentysixteen-child/woocommerce/emails/plain/customer-invoice.php
twentysixteen-child/woocommerce/emails/plain/customer-new-account.php
twentysixteen-child/woocommerce/emails/plain/customer-note.php
twentysixteen-child/woocommerce/emails/plain/customer-on-hold-order.php
twentysixteen-child/woocommerce/emails/plain/customer-processing-order.php
twentysixteen-child/woocommerce/emails/plain/customer-refunded-order.php
twentysixteen-child/woocommerce/emails/plain/customer-reset-password.php
twentysixteen-child/woocommerce/emails/plain/email-addresses.php
twentysixteen-child/woocommerce/emails/plain/email-customer-details.php
twentysixteen-child/woocommerce/emails/plain/email-order-details.php
twentysixteen-child/woocommerce/emails/plain/email-order-items.php version 2.1.2 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/global/breadcrumb.php
twentysixteen-child/woocommerce/global/form-login.php
twentysixteen-child/woocommerce/global/quantity-input.php
twentysixteen-child/woocommerce/global/sidebar.php
twentysixteen-child/woocommerce/global/wrapper-end.php
twentysixteen-child/woocommerce/global/wrapper-start.php
twentysixteen-child/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/loop/loop-end.php
twentysixteen-child/woocommerce/loop/loop-start.php
twentysixteen-child/woocommerce/loop/no-products-found.php
twentysixteen-child/woocommerce/loop/orderby.php
twentysixteen-child/woocommerce/loop/pagination.php
twentysixteen-child/woocommerce/loop/price.php
twentysixteen-child/woocommerce/loop/rating.php version 2.0.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/loop/result-count.php version 2.0.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/loop/sale-flash.php
twentysixteen-child/woocommerce/myaccount/dashboard.php
twentysixteen-child/woocommerce/myaccount/downloads.php version 2.6.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/myaccount/form-add-payment-method.php version 2.6.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/myaccount/form-edit-account.php
twentysixteen-child/woocommerce/myaccount/form-edit-address.php version 2.6.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/myaccount/form-login.php
twentysixteen-child/woocommerce/myaccount/form-lost-password.php version 2.6.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/myaccount/form-reset-password.php version 2.6.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/myaccount/lost-password-confirmation.php
twentysixteen-child/woocommerce/myaccount/my-account.php
twentysixteen-child/woocommerce/myaccount/my-address.php
twentysixteen-child/woocommerce/myaccount/my-downloads.php
twentysixteen-child/woocommerce/myaccount/my-orders.php
twentysixteen-child/woocommerce/myaccount/navigation.php
twentysixteen-child/woocommerce/myaccount/orders.php version 2.6.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/myaccount/payment-methods.php
twentysixteen-child/woocommerce/myaccount/view-order.php version 2.6.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/notices/error.php
twentysixteen-child/woocommerce/notices/notice.php
twentysixteen-child/woocommerce/notices/success.php
twentysixteen-child/woocommerce/order/form-tracking.php
twentysixteen-child/woocommerce/order/order-again.php
twentysixteen-child/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/order/order-details-item.php version 2.5.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/order/order-details.php version 2.6.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/order/tracking.php
twentysixteen-child/woocommerce/product-searchform.php
twentysixteen-child/woocommerce/single-product/add-to-cart/external.php
twentysixteen-child/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.3
twentysixteen-child/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product/add-to-cart/variation.php
twentysixteen-child/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.0.2
twentysixteen-child/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.0.2
twentysixteen-child/woocommerce/single-product/rating.php
twentysixteen-child/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product/review-meta.php version 2.6.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product/review-rating.php version 2.6.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product/review.php
twentysixteen-child/woocommerce/single-product/sale-flash.php
twentysixteen-child/woocommerce/single-product/share.php
twentysixteen-child/woocommerce/single-product/short-description.php
twentysixteen-child/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product/tabs/description.php
twentysixteen-child/woocommerce/single-product/tabs/tabs.php
twentysixteen-child/woocommerce/single-product/title.php
twentysixteen-child/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
twentysixteen-child/woocommerce/single-product-reviews.php
twentysixteen-child/woocommerce/single-product.php
twentysixteen-child/woocommerce/taxonomy-product_cat.php
twentysixteen-child/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌Learn how to update
</details>

**Comment by mikejolley** [comment]
It's working now?

This isn't something affecting other sites or my own so does not look like a bug.  It could be extension, API disabled in WC > Settings > API, or simply a permalink issue if something else has flushed the rules incorrectly (going to settings > permalinks and saving will resolve).

**Comment by Gwildor** [comment]
Apparently this was an issue with WPML. I was using `/en/wp-json/` before the update because using regular `/wp-json/` didn't work, but after the update it was the other way around. I'm using regular `/wp-json/`, without the language part, now. So yeah, not a bug!
