### ISSUE TITLE
Missing Attribute/Variations but still in database 3.0.6 does not fix

### ISSUE THREAD

**Issue by paxjah** [woocommerce/woocommerce#15065]
3.0.6 does not fix the variation/attribute issue. We are still getting it. All plugins up-to-date. No customisations.

Attributes and variation are gone within the edit product screen, including both global and non-global attributes.

However all variations are still in database, they just don't seem to be linking. Please see parent and variation exports, as well as system report here - https://drive.google.com/drive/folders/0Bx22mhyUGaBOaFA5V3ZUN3ZObE0?usp=sharing

We tried reverting to 3.0.4, disabling plugins both in .6 and .4, and the usual debug tricks, but these did not fix the issue. I can provide full access to the site.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14824#issuecomment-301442899
