### ISSUE TITLE
I can't log into WooCommerce Support

### ISSUE THREAD

**Issue by lyudmila28** [woocommerce/woocommerce#15075]
### EXPLANATION OF THE ISSUE

I have an issue but I can't log into the support website for help. It says my wordpress.com username/ pw are invalid. But that's what they are.... I tested wordpress by logging in with those exact same credentials but I still can't seem to get into Woo Commerce help. 

### STEPS TO REPRODUCE THE ISSUE

try to log into woo commerce help desk with my username. 

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://missionlean.com
Site URL: http://missionlean.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Active Plugins (23) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.8
Divi Builder: by Elegant Themes – 1.3.10
Duplicate Page: by mndpsingh287 – 2.2
Elegant Themes Support: by Elegant Themes – 1.3
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.0.4
Subscribe Forms Premium: by  – 1.6
Menu Icons: by Dzikri Aziz – 0.10.2
Nav Menu Roles: by Kathy Darling – 1.8.6
Ninja Forms: by The WP Ninjas – 3.0.29
Slider Revolution: by ThemePunch – 5.4.3.2
Shortcodes Ultimate: by Vladimir Anokhin – 4.9.9
TablePress: by Tobias Bäthge – 1.7
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.34

Digital Goods Checkout for WooCommerce: by WebSmacker – 1.3
WonderPlugin Lightbox: by Magic Hills Pty Ltd – 5.6C
WooCommerce Direct Checkout: by Terry Tsang – 1.1.2
WooCommerce Stripe Gateway: by WooCommerce – 3.0.7
WooCommerce Memberships: by WooThemes / SkyVerge – 1.7.5 – 1.8.4 is available
WooCommerce Tab Manager: by WooThemes / SkyVerge – 1.7.4 – 1.8.0 is available
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
WP Video Lightbox: by Tips and Tricks HQ
Ruhul Amin – 1.8.4

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page not set
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My Account: #8 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Mission:Lean Child Theme
Version: 1
Author URL: http://willgorham.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.17
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-Child/woocommerce/checkout/form-billing.php
Divi-Child/woocommerce/checkout/form-checkout.php
Divi-Child/woocommerce/emails/customer-completed-order.php
Divi-Child/woocommerce/emails/customer-new-account.php
Divi-Child/woocommerce/myaccount/dashboard.php
Divi-Child/woocommerce/order/order-details-customer.php

</details>

**Comment by mikejolley** [comment]
Not sure if relevant, but it wants a WordPress.com account login, not the login for your website. https://docs.woocommerce.com/document/log-into-woocommerce-com-with-wordpress-com/

If not you can use the contact form here and someone should be able to help you get in https://woocommerce.com/contact-us/#sales-form

Thanks
