### ISSUE TITLE
"Featured" Product Doesn't Save to Database

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#15077]
### EXPLANATION OF THE ISSUE

When a product is set to "Featured", nothing changes in the database to reflect this change and it cannot be pulled by a query.

### STEPS TO REPRODUCE THE ISSUE

1. Create a product and set it to "Featured".
2. Open MySQL to view the post meta and look for the `_featured` key. Either the value will be `no` or you can't find the value at all.

This was tested on two sites, one live and one localhost, with just WooCommerce and Storefront activated. The localhost was spun up specifically for this issue so it had no previous use.

575658-zd-woothemes

**Comment by mikejolley** [comment]
@DanielSantoro 

https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#product-visibility-is-taxonomy-based-instead-of-meta-based

terms.

**Comment by minkadev** [comment]
I'm updating as a taxonomy, and still not showing...

```
if ( $featured_term = get_term_by('name', 'featured', 'product_visibility') ) {
    wp_set_object_terms( $post_id, array($featured_term->term_id), 'product_visibility', TRUE);
    delete_transient( 'wc_featured_products' );
}

```
I am doing anything wrong?
