### ISSUE TITLE
Customer email field showing code

### ISSUE THREAD

**Issue by linkhousemedia** [woocommerce/woocommerce#15082]
### EXPLANATION OF THE ISSUE

All most recent versions of Woocommerce and plugins (see system status below). Customer email (chosen) field on order screen showing code output. Expect to just see customer email if available.

**Example:**
 ```<span class="select2-selection__rendered" id="select2-customer_user-container" title="example-username (#73 &amp;ndash; [email&nbsp;protected]/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&amp;&amp;(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */)"><span class="select2-selection__clear">×</span>example-username (#73 – [email&nbsp;protected]/* <!--[CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]--> */)</span>```

<img src="http://i.imgur.com/dPnUnng.png" />

### STEPS TO REPRODUCE THE ISSUE

1. Navigate to edit an order. 
2. Check out the email field. 

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://example.com
Site URL: https://example.com
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_CA

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 250 MB
PHP Time Limit: 30
PHP Max Input Vars: 2000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: ❌ 5.5.42 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.13
Akismet Anti-Spam: by Automattic – 3.3.2
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.2.1

Featured Custom Post Type Widget for Genesis: by Jo Waltham – 2.1.0
Formidable Forms: by Strategy11 – 2.03.07
Genesis Connect for WooCommerce: by StudioPress – 0.9.9
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.8
MailChimp Forms by MailMunch: by MailMunch – 3.0.5
Prevent Concurrent Logins: by Frankie Jarrett – 0.4.0
Printful Integration for WooCommerce: by Printful – 1.2.7
Public Post Preview: by Dominik Schilling – 2.6.0
Seriously Simple Podcasting: by PodcastMotor – 1.16.1
Simple Login Log: by Max Chirkov – 1.1.1
Simple Social Icons: by Nathan Rice – 2.0.1
StarBox: by Squirrly UK – 3.0.6
UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 1.13.1

User Role Editor: by Vladimir Garagulya – 4.32.3
User Switching: by John Blackbourn – 1.0.9
WC Speed Drain Repair: by WP Fix It – 1.0
WooCommerce - Autocomplete Orders: by Serious Plugins – 1.1.4
WooCommerce Coupon Links: by Cedaro – 2.2.0
WooCommerce Stripe Gateway: by WooCommerce – 3.1.8
WooCommerce Memberships: by SkyVerge – 1.8.4
WooCommerce Custom Cafe Post Notification Email: by SkyVerge – 0.1
WooCommerce Subscriptions: by Prospress Inc. – 2.2.6
WooCommerce: by Automattic – 3.0.6
Yoast SEO: by Team Yoast – 4.7.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #189 - /shop/
Cart: #190 - /cart/
Checkout: #191 - /checkout/
My account: #192 - /my-account/

### Theme ###

Name: Maker Pro
Version: 1.0.0
Author URL: http://www.jtgrauke.com
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.5.0
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: maker-pro/woocommerce/archive-product.php
maker-pro/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
maker-pro/woocommerce/emails/customer-processing-order.php
maker-pro/woocommerce/emails/email-header.php
maker-pro/woocommerce/emails/email-styles.php
maker-pro/woocommerce/global/wrapper-end.php
maker-pro/woocommerce/global/wrapper-start.php
maker-pro/woocommerce/myaccount/dashboard.php
maker-pro/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
</details>

**Comment by mikejolley** [comment]
You have a script active which replaces email addresses with a munged version. This is not from core or subscriptions; it's either a plugin or code you have added yourself :)

**Comment by linkhousemedia** [comment]
I'd love to agree but I'm stumped.  It still happens when WooCommerce is the ONLY plugin active, and I activate the twentysixteen theme.  No caching, no drop-ins... nothing.

**Comment by mikejolley** [comment]
You can have code present which only works when wc is active...  view the page source and see if there is anything obvious? Scripts for example.

**Comment by linkhousemedia** [comment]
Right, but if I'm not even using my own functions.php file, where on earth would that code come from?  Literally no other plugins an an out-of-the-box theme.

**Comment by mikejolley** [comment]
Service such as cloudflare? https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-

**Comment by linkhousemedia** [comment]
@mikejolley you were on to something.  IT'S CLOUDFLARE. Thanks for pointing me in the right direction. Sorry about the.... just saw your last post.  lol.

**Comment by scottbuscemi** [comment]
@mikejolley can we please re-open this issue? CloudFlare says that they will not fix this issue, and I'm sure a huge portion of WC sites are running CloudFlare. It's not the biggest issue in the world, but it's definitely a bug that I run into with every single client site.

From their email support when I inquired about this:

> The Obfuscation is performed in the Cloudflare edge - and we search for some elements and pattern to make it happen.
>
>If we find such pattern (which we cannot disclose), it will obfuscate the email.
>
>I understand you are hesitant to use page rules, but this is the best solution at this time as it can be limited to the pages you need to skip.
>
>What WooCommerce could maybe, at this point, is to not show the email in this confirmation - just name and/or some customer code.

**Comment by mikejolley** [comment]
>  is to not show the email in this confirmation

Thats not a very good "fix" :) Does cloud flare affect other WordPress screens such as the users page?

**Comment by scottbuscemi** [comment]
@mikejolley This is the only instance of the issue I've ever seen. In fact, the email addresses aren't obfuscated when shown in the search results...

<img width="295" alt="screen shot 2017-07-07 at 10 10 24 am" src="https://user-images.githubusercontent.com/4336848/27968639-af3e4e8a-62fc-11e7-9b27-d681c5ee9903.png">

**Comment by mikejolley** [comment]
@claudiosanches ?

**Comment by claudiosanches** [comment]
Looks like you can disable https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-

> But it's definitely a bug that I run into with every single client site.

I disagree, it's not a bug, since CloudFlare is causing it and you can disable on CloudFlare side.

And for me we should not change anything, since is something that is out of our control.
But since this is the only instance, I don't see a problem in improve it.

**Comment by claudiosanches** [comment]
@scottbuscemi this should fix, please test for me: https://github.com/woocommerce/woocommerce/pull/16016

**Comment by claudiosanches** [comment]
If this keep happening, is more easy for you use:

```php
add_action( 'in_admin_header', function() {
    echo '<!--email_off-->';
});

add_action( 'admin_footer', function() {
    echo '<!--/email_off-->';
});
```

So will disable CloudFlare email obfuscation in the entire WordPress admin.

**Comment by scottbuscemi** [comment]
@claudiosanches the commit does fix the issue.
