### ISSUE TITLE
add manually order didn´t work after update 

### ISSUE THREAD

**Issue by henrikhaake** [woocommerce/woocommerce#15085]
### EXPLANATION OF THE ISSUE

After I updated to woo 3.0 upto 3.0.6 I can´t add manually orders. I can´t add aproduct. The system is loading to death..

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30-he.0
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: ✔
MySQL Version: 5.6.34
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Autoptimize: von Frank Goossens (futtta) – 2.1.0
Cache Enabler: von KeyCDN – 1.2.0
Cookie Notice: von dFactory – 1.2.38
Eagle Eye Profit Tracker: von Fantastic Plugins – 1.2
Envato Market: von Derek Herman – 1.0.0-RC2
Heartbeat Control: von Jeff Matson – 1.0.3
Improved Variable Product Attributes for WooCommerce: von Mihajlovic Nenad – 3.2.4
WPBakery Visual Composer: von Michael M - WPBakery.com – 5.1.1
MailChimp for WordPress Lite: von ibericode – 2.3.17
PAYMILL GmbH: von Matthias Reuter info@straightvisions.com – 1.12
Really Simple SSL: von Rogier Lankhorst – 2.5.16
Relevanssi: von Mikko Saari – 3.5.9.1
WooCommerce Print Invoice & Delivery Note: von Triggvy Gunderson – 4.1.5
WooCommerce Google Analytics Integration: von WooCommerce – 1.4.2
WooCommerce Point of Sale: von Actuality Extensions – 4.1.1
WooCommerce Sequential Order Numbers: von SkyVerge – 1.8.1
WooCommerce - Store Credit: von Visser Labs – 1.1
WooCommerce: von Automattic – 3.0.6
Yoast SEO: von Team Yoast – 4.7.1
WP Instagram Widget: von Scott Evans – 1.9.8
WP-Mail-SMTP: von Callum Macdonald – 0.10.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #4 - /shop/
Warenkorb: #5 - /warenkorb/
Kasse: #6 - /kasse/
Mein Konto: #7 - /mein-konto/

### Theme ###

Name: Savoy Child
Version: 1.0.1
Author URL: http://www.nordicmade.com
Child Theme: ✔
Parent Theme Name: Savoy
Parent Theme Version: 1.7.6
Parent Theme Author URL: http://www.nordicmade.com
WooCommerce Support: ✔

### Templates ###

Overrides: savoy/woocommerce/archive-product.php
savoy/woocommerce/cart/cart-empty.php
savoy/woocommerce/cart/cart-item-data.php
savoy/woocommerce/cart/cart-shipping.php
savoy/woocommerce/cart/cart-totals.php
savoy/woocommerce/cart/cart.php
savoy/woocommerce/cart/cross-sells.php
savoy/woocommerce/cart/mini-cart.php
savoy/woocommerce/cart/proceed-to-checkout-button.php
savoy/woocommerce/cart/shipping-calculator.php
savoy/woocommerce/checkout/cart-errors.php
savoy/woocommerce/checkout/form-billing.php
savoy/woocommerce/checkout/form-checkout.php
savoy/woocommerce/checkout/form-coupon.php
savoy/woocommerce/checkout/form-login.php
savoy/woocommerce/checkout/form-pay.php
savoy/woocommerce/checkout/form-shipping.php
savoy/woocommerce/checkout/payment-method.php
savoy/woocommerce/checkout/payment.php
savoy/woocommerce/checkout/review-order.php
savoy/woocommerce/checkout/terms.php
savoy/woocommerce/checkout/thankyou.php
savoy/woocommerce/content-product.php
savoy/woocommerce/content-product_cat.php
savoy/woocommerce/content-single-product.php
savoy/woocommerce/content-widget-product.php
savoy-child/woocommerce/emails/customer-completed-order.php
savoy-child/woocommerce/emails/customer-processing-order.php
savoy/woocommerce/global/breadcrumb.php
savoy/woocommerce/global/form-login.php
savoy/woocommerce/global/quantity-input.php
savoy/woocommerce/global/sidebar.php
savoy/woocommerce/global/wrapper-end.php
savoy/woocommerce/global/wrapper-start.php
savoy/woocommerce/loop/add-to-cart.php
savoy/woocommerce/loop/loop-end.php
savoy/woocommerce/loop/loop-start.php
savoy/woocommerce/loop/no-products-found.php
savoy/woocommerce/loop/pagination.php
savoy/woocommerce/loop/price.php
savoy/woocommerce/loop/rating.php
savoy/woocommerce/loop/sale-flash.php
savoy/woocommerce/myaccount/dashboard.php
savoy/woocommerce/myaccount/downloads.php
savoy/woocommerce/myaccount/form-add-payment-method.php
savoy/woocommerce/myaccount/form-edit-account.php
savoy/woocommerce/myaccount/form-edit-address.php
savoy/woocommerce/myaccount/form-login.php
savoy/woocommerce/myaccount/form-lost-password.php
savoy/woocommerce/myaccount/form-reset-password.php
savoy/woocommerce/myaccount/lost-password-confirmation.php
savoy/woocommerce/myaccount/my-account.php
savoy/woocommerce/myaccount/my-address.php
savoy/woocommerce/myaccount/navigation.php
savoy/woocommerce/myaccount/orders.php
savoy/woocommerce/myaccount/payment-methods.php
savoy/woocommerce/myaccount/view-order.php
savoy/woocommerce/notices/error.php
savoy/woocommerce/notices/notice.php
savoy/woocommerce/notices/success.php
savoy/woocommerce/order/form-tracking.php
savoy/woocommerce/order/order-again.php
savoy/woocommerce/order/order-details-customer.php
savoy/woocommerce/order/order-details-item.php
savoy/woocommerce/order/order-details.php
savoy/woocommerce/order/tracking.php
savoy/woocommerce/product-searchform.php
savoy/woocommerce/single-product/add-to-cart/external.php
savoy/woocommerce/single-product/add-to-cart/grouped.php
savoy/woocommerce/single-product/add-to-cart/simple.php
savoy/woocommerce/single-product/add-to-cart/variable.php
savoy/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
savoy/woocommerce/single-product/add-to-cart/variation.php
savoy/woocommerce/single-product/meta.php
savoy/woocommerce/single-product/photoswipe.php
savoy/woocommerce/single-product/price.php
savoy/woocommerce/single-product/product-attributes.php
savoy/woocommerce/single-product/product-image.php
savoy/woocommerce/single-product/product-thumbnails.php
savoy/woocommerce/single-product/rating.php
savoy/woocommerce/single-product/related.php
savoy/woocommerce/single-product/review-meta.php
savoy/woocommerce/single-product/review-rating.php
savoy/woocommerce/single-product/review.php
savoy/woocommerce/single-product/sale-flash.php
savoy/woocommerce/single-product/share.php
savoy/woocommerce/single-product/short-description.php
savoy/woocommerce/single-product/stock.php
savoy/woocommerce/single-product/tabs/additional-information.php
savoy/woocommerce/single-product/tabs/description.php
savoy/woocommerce/single-product/tabs/tabs.php
savoy/woocommerce/single-product/title.php
savoy/woocommerce/single-product/up-sells.php
savoy/woocommerce/single-product-reviews.php
savoy/woocommerce/single-product.php
savoy/woocommerce/taxonomy-product_cat.php
savoy/woocommerce/taxonomy-product_tag.php

`
</details>

**Comment by mikejolley** [comment]
Endless loading issues are caused by conflicts and are not affecting all stores.

2 things you need to check first to narrow down the problem; server error logs, and the 'javascript console'. https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x#finding-a-javascript-error

Alternatively you can test with no other plugins active/default theme.

Report back when you have an actionable error.

**Comment by henrikhaake** [comment]
Hi Mike,

 

thanks for your help. The Server error log was the perfect hint.

The problem war gereated by an old plugin which was outdated (removed from the the list)

 

Thanks.


Best Henrik

 

 

Gesendet: Dienstag, 16. Mai 2017 um 09:18 Uhr
Von: "Mike Jolley" <notifications@github.com>
An: woocommerce/woocommerce <woocommerce@noreply.github.com>
Cc: henrikhaake <henrik-haake@web.de>, Author <author@noreply.github.com>
Betreff: Re: [woocommerce/woocommerce] add manually order didn´t work after update (#15085)


Endless loading issues are caused by conflicts and are not affecting all stores.

2 things you need to check first to narrow down the problem; server error logs, and the 'javascript console'. https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x#finding-a-javascript-error

Alternatively you can test with no other plugins active/default theme.

Report back when you have an actionable error.
