### ISSUE TITLE
Please enter a valid postcode / ZIP for United Kingdom

### ISSUE THREAD

**Issue by umerkakar** [woocommerce/woocommerce#15083]
### EXPLANATION OF THE ISSUE
I have created shop only for United Kingdom that sell services to specific areas that can be find by postcodes on checkout page.
Please enter a valid postcode / ZIP for United Kingdom error. unable to solve the issue. Tried it via using VPN from United Kingdom and without VPN. Same error. I have attached all the settings and error screenshot. Unable to debug the issue.

### STEPS TO REPRODUCE THE ISSUE

1. Selected United Kingdom from sell to countries and ship to countries option. 
2. Created new shipping zone named it United Kingdom, select UK country and added postal codes in this format.
W14*
W9*
W2*
W1*
NW8*
NW5*
NW4*
NW3*
NW1*
3. Select free shipping as shipping method.
4. Select COD and Stripe for payment methods. Both are configured correctly.
5. Add products to cart.
6. On checkout page filled up the form and got the error about postalcode/zip code validation.

### SYSTEM STATUS

<details>
WordPress environment
Home URL:		https://dryclean.platin.life
Site URL:		https://dryclean.platin.life
WC version:		3.0.6
Log directory writable:		 /home/*****/*******/wp-content/uploads/wc-logs/
WP version:		4.7.4
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		–
WP cron:		
Language:		en_US
Server environment
Server info:		Apache
PHP version:		5.6.30
PHP post max size:		5 GB
PHP time limit:		90
PHP max input vars:		1000
cURL version:		7.53.1, OpenSSL/1.0.1e
SUHOSIN installed:		–
MySQL version:		5.6.35
Max upload size:		50 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.6
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
Security
Secure connection (HTTPS):		
Hide errors from visitors		
Active plugins (3)
WPBakery Visual Composer	 	by Michael M - WPBakery.com – 5.0.1
WooCommerce Stripe Gateway	 	by WooCommerce – 3.1.8
WooCommerce	 	by Automattic – 3.0.6
Settings
API enabled:		–
Force SSL:		
Currency		GBP (£)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#2886 - /shop/
Cart:		#2887 - /cart/
Checkout:		#2888 - /checkout/
My account:		#3047 - /my-account/
Theme
Name:		dryclean
Version:		1.0
Author URL:		http://platin.life
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Archive template:	 	Your theme has a woocommerce.php file, you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides	 	dryclean/woocommerce/archive-product.php, 
dryclean/woocommerce/cart/cart-empty.php, 
dryclean/woocommerce/cart/cart.php, 
dryclean/woocommerce/cart/mini-cart.php, 
dryclean/woocommerce/cart/proceed-to-checkout-button.php, 
dryclean/woocommerce/checkout/form-checkout.php, 
dryclean/woocommerce/checkout/form-coupon.php, 
dryclean/woocommerce/checkout/form-pay.php, 
dryclean/woocommerce/checkout/payment.php, 
dryclean/woocommerce/global/form-login.php, 
dryclean/woocommerce/global/quantity-input.php, 
dryclean/woocommerce/global/wrapper-end.php, 
dryclean/woocommerce/global/wrapper-start.php, 
dryclean/woocommerce/loop/add-to-cart.php, 
dryclean/woocommerce/loop/orderby.php, 
dryclean/woocommerce/myaccount/downloads.php, 
dryclean/woocommerce/myaccount/form-edit-account.php, 
dryclean/woocommerce/myaccount/form-edit-address.php, 
dryclean/woocommerce/myaccount/form-login.php, 
dryclean/woocommerce/myaccount/form-lost-password.php, 
dryclean/woocommerce/myaccount/form-reset-password.php, 
dryclean/woocommerce/myaccount/my-address.php, 
dryclean/woocommerce/myaccount/my-orders.php, 
dryclean/woocommerce/myaccount/navigation.php, 
dryclean/woocommerce/myaccount/orders.php, 
dryclean/woocommerce/single-product/add-to-cart/simple.php, 
dryclean/woocommerce/single-product/product-thumbnails.php, 
dryclean/woocommerce/single-product/rating.php, 
dryclean/woocommerce/single-product/review-rating.php, 
dryclean/woocommerce/single-product/short-description.php

</details>

screenshots.
![1](https://cloud.githubusercontent.com/assets/11842713/26079803/7d479136-39dd-11e7-91d2-e5a4dfb8b0a8.png)
![2](https://cloud.githubusercontent.com/assets/11842713/26079806/7d4e2ad2-39dd-11e7-81e1-9234e7bf9a6d.png)
![3](https://cloud.githubusercontent.com/assets/11842713/26079805/7d4d57e2-39dd-11e7-9ff3-a1b2f8b7fdac.png)
![4](https://cloud.githubusercontent.com/assets/11842713/26079804/7d49b330-39dd-11e7-834a-768169ae1c05.png)

**Comment by mikejolley** [comment]
@umerkakar NW4 is not a valid postcode - it is not complete.

**Comment by umerkakar** [comment]
These are the codes that are provided by client. You can take a look here.
https://dryclean.platin [ . ] life/locations/

**Comment by umerkakar** [comment]
I have just tried complete code like this. NW8 0DU
And that is working. But client want to use NW8 as a zip code and want to skip the second part. How to deal with it?

**Comment by sterenas** [comment]
What if you just remove the * at the end of each ZIPCODE?  Wouldn't that work as that'd make them full ZIPCODES for you?

**Comment by umerkakar** [comment]
without * those were showing the same error. But as I followed the pattern. Working fine. But that needs to be only on three letters as mentioned before. Like NW8 or NW4

**Comment by mikejolley** [comment]
Those are simply not valid postcodes. No address uses 3 chars only.m in a postcode. I am UK based.

**Comment by mikejolley** [comment]
Refer to https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom

Tweak this if you want but it's not supported, not valid, and your client won't be able to post packages without a valid postcode https://github.com/woocommerce/woocommerce/blob/d39e3171821e6aa618653f77fac40702ca77c3bc/includes/class-wc-validation.php#L96

**Comment by umerkakar** [comment]
Yeh I know that. I think, I have to tell client that its not possible. Things only work as per standard.

**Comment by Nomi11** [comment]
What will be the postcode for Lahore Pakistan?

**Comment by Nomi11** [comment]
My shop is only in Lahore and deliver services only in Lahore Pakistan. What will be the zone name and zone region and postcode also? Please tell me.
