### ISSUE TITLE
Add REST API method for returning supported locations

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#15080]
The `/settings/*` endpoints return various locations (countries or states), but those are tied pretty closely to the each setting. For example, `woocommerce_default_country` returns countries and some states within countries while `woocommerce_all_except_countries` returns just countries. It is not easy to just get a list of countries that WooCommerce supports, or just a list of states/provinces.

To allow for more flexible user interfaces for other parts of shop management (like configuring a shipping zone) and to avoid needing to cobble together a list from multiple sources, it would be useful to have a way to get this data from the REST API.

We essentially need to return the information present at `i18n/states/`, `i18n/continents`, and `i18n/countries` via `GET` requests. I'm not sure what the path should be.

**Comment by DanReyLop** [comment]
> it would be useful to have some new endpoints.

Does it need to be multiple endpoints? I was thinking on a single endpoint that has all the `continents / countries / states` data. At least for the UI requirements of the `Shipping Zones` settings, we need all the data upfront, and I can't think on any use case where you would just need the states of a single country.

**Comment by justinshreve** [comment]
> Does it need to be multiple endpoints? 

Nope. I've updated my title/description a bit to be a little more general.

**Comment by mikejolley** [comment]
@justinshreve would it make sense to do the same for currency symbols rather than changing https://github.com/woocommerce/woocommerce/issues/15101 ?

**Comment by justinshreve** [comment]
Yeah I think that makes sense. 👍

**Comment by ryelle** [comment]
I've been taking a look at implementing this, and i have a few questions: Should this be behind a permissions check? It's basically public data, and I'm not sure what permission to check for.

I was thinking of using `data/location` for the route, with the option to have other `data/*` endpoints later — based on the currency [comment here](https://github.com/woocommerce/woocommerce/issues/15080#issuecomment-301822693). Data is vague, is there any other meta-term for this kind of info?

_Would_ there be more data endpoints like this & currency, or am I premature in trying to work for that?

**Comment by mikejolley** [comment]
> Would there be more data endpoints like this & currency, or am I premature in trying to work for that?

@justinshreve / @coderkevin ideas?

> I was thinking of using data/location for the route, with the option to have other data/* endpoints later

Are you thinking this is open like the index? Whilst the data itself is public, would that open it up to abuse?

@claudiosanches thoughts on this?

**Comment by coderkevin** [comment]
I guess it depends on how much static data we have like this. Is it something we would always need all of? If so, we could just include all of it in one JSON request. What if it were a single endpoint but one that we could filter for the fields we need?

**Comment by coderkevin** [comment]
For the permissions, we should think about public uses of this information. Would we ever need this information for say, a JS-powered cart page?

**Comment by entr** [comment]
It could at least be a route for validation purposes, so apps could check if shipping is available for user selected locations.

**Comment by claudiosanches** [comment]
Can use `wc_rest_check_manager_permissions()` to check this permissions, will check for at least a shop manager, that currently is the same permission if you are accessing shipping zones endpoints.
No reason to make it public now, since we don't have any public endpoints, not to mention that there is filters in `wc_rest_check_manager_permissions()` and all over other endpoints to make it possible, if someone want to create a JS-powered cart page.

For the endpoint name is better just `locations`.

Endpoints:

```
GET /locations # returns all continents, countries and states.
GET /locations/<continent> # return all countries and states from a continent.
GET /locations/<continent>/<country> # return all states of a country.
GET /locations/?hide-continents=1 # return only the list of countries and states, like we does on cart page.
```

This should cover all use cases.

**Comment by mikejolley** [comment]
@claudiosanches locations does not cover currency codes as noted above.

> with the option to have other data/* endpoints later — based on the currency comment here

https://github.com/woocommerce/woocommerce/issues/15080#issuecomment-301822693

**Comment by claudiosanches** [comment]
@mikejolley can already get currency from settings endpoint, and no reason to have a all in one `data/` endpoint.

**Comment by justinshreve** [comment]
Re currencies, see #15101 linked above for one reason we need something different. I think we need to return them on a new endpoint and not require someone to dig into the settings output. These can be used independent of settings.

Even if we multiple endpoints like Claudio mentioned above, I don't think they need to be root level.

I agree with @ryelle's suggestion of having them under `/data/. For WordPress.com, we did something similar and put them under a `/meta` path. Example: https://developer.wordpress.com/docs/api/1.1/get/meta/sharing-buttons/.

**Comment by claudiosanches** [comment]
I can't see the cons of having this at root level, even more that we don't need to worry about create an index inside `/data`, I can't see not even that how this could be so strict related to require some endpoint to group it. That's the problem of `/data` for me.

**Comment by ryelle** [comment]
Just `/locations` to me might read as business locations, or some other user-defined store data (since other top-level things are products, orders, etc). Giving this & currencies the data/meta prefix indicates that they're part of a collection of "meta-information" for stores, not about this particular store. (to me)

Do we need to have something at the root `/data`? Right now with the code I'm working on, it just returns the `rest_no_route` error.

> the conventions that all endpoints uses plurals

I'm pretty sure that `meta` and `data` both work as plural forms here.

**Comment by claudiosanches** [comment]
@ryelle ok.

> Just /locations to me might read as business locations, or **some other user-defined store data** (since other top-level things are products, orders, etc). Giving this & currencies the data/meta prefix indicates that they're part of a collection of "meta-information" for stores, **not about this particular store**. (to me)

Let's go with `/data`, but it's possible return different results, since there is filters to remove or include new countries and currencies.

> Do we need to have something at the root /data? 

Definitely yes, for the sake of consistency, all endpoints are created to return something.
Check `/reports` for reference.

**Comment by coderkevin** [comment]
> Let's go with /data, but it's possible return different results, since there is filters to remove or include new countries and currencies.

That's the whole reason we're using the API for this, and not just hard-coding it somewhere, right?

**Comment by claudiosanches** [comment]
@coderkevin not sure what you mean, I'm saying for me there is no need to be under `/data` since is possible change in every site.

**Comment by coderkevin** [comment]
@claudiosanches I didn't realize `/data` meant completely static and hard-coded within the software. It honestly doesn't matter to me where this endpoint is as long as it exists.

**Comment by claudiosanches** [comment]
@coderkevin looks like they are choosing `/data` because they expect this to be "static". That's why I'm not a big fan of `/data`, but for sure we need the endpoint.

**Comment by justinshreve** [comment]
`/data` doesn't imply static or not static to me. In my mind, these locations and currency sets of information are both part of a group of data that is used for the same purposes (mainly to build settings configuration UI). We could group them to avoid introducing two new root paths, but I really don't have a crazy strong opinion on this.

**Comment by justinshreve** [comment]
Closing since this was merged in to the REST API feature pluginL https://github.com/woocommerce/wc-api-dev/pull/3
