### ISSUE TITLE
Variation menu order error

### ISSUE THREAD

**Issue by codejunkie33** [woocommerce/woocommerce#15081]
### EXPLANATION OF THE ISSUE

When adding variations to a product by "Create variations from all attributes", the first variation is assigned a "Variation menu order" of "0". If "drag and drop" is used to rearrange the "Variation menu order" the first variation is assigned a "variation menu order" value of "1" and all subsequent variations are reassigned sequentialy. If there is more than one page of variations, the last variation on page 1 is assigned a "Variation menu order" value of "15" however, the first variation on page 2 is also assigned a "Variation menu order" value of "15". This then causes the menu order to constantly change on every save thereafter as there is a duplicate.

### STEPS TO REPRODUCE THE ISSUE

1) localhost clean install of Wordpress and WooCommerce
2) create attribute set of 27 items
3) create variable product and add all variations
4) verify first "Variation menu order" value by clicking on hamburger menu icon "to set admin variation order"
5) click and drag first variation under second then back to first
6) verify first and last "Variation menu order" values on page 1 and first "Variation menu order" values on page 2

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost/test
Site URL: http://localhost/test
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.1
PHP Version: 7.1.1
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
Not sure how to work around this one. We could add new variations with a negative menu_order, but we'd need to ensure the 'set menu order' function considers the offset from 0 rather that these.

Not too important but one to fix in a future release. I'll add good first patch label but it's tricky on first look.

**Comment by codejunkie33** [comment]
Thanks for your time. Unfortunately, this seems to compound on multiple pages of variations. I have a store with many variable products, some with hundreds of variations. Due to this, I'm unable to edit variations efficiently due to them randomizing on every save. The only workaround I've found is to modify the woocommerce_admin_meta_boxes_variations_per_page to eliminate the pagination but this doesn't account for the randomizing. Therefore, my workflow for any variation edits is to reorganize the variations, make edits, then save. For large products this is quite time consuming. 
Any advice on a more efficient workflow is appreciated.

**Comment by claudiosanches** [comment]
@codejunkie33 can you please test the changes from https://github.com/woocommerce/woocommerce/pull/15462 and check if is fixed now?

**Comment by codejunkie33** [comment]
You guys are the best! Thanks!!
