### ISSUE TITLE
“Minimum spend” can’t be restricted to categories

### ISSUE THREAD

**Issue by 4kittenbritches** [woocommerce/woocommerce#15089]
### EXPLANATION OF THE ISSUE

Ever since the 3.0 woocommerce update, coupons can no longer be restricted to spending a minimum in a category.

You used to be able to require a customer buy $X of a category to get a discount on it. The category restriction worked for both the “minimum spend” and what items the discount would be applied to.

Now, they just have to spend $X total (in any category) to get the discount on the specified category.

This means there's now no way to have a volume discount code.

### STEPS TO REPRODUCE THE ISSUE

1. Create a coupon for a "fixed item discount". Amount $1.50.
2. Go to Coupon Restriction Tab. Set minimum spend to $100.
3. Choose a Coupon Product Category (A) and Exclude a Category (B)
4. Save Coupon
5. Add an item from both Category A and B to your cart that are less than $100 each
6. Increase the quantity of Category B items in your cart until your total sale is at least $100. 
7. Go to your cart and enter the coupon code.
8. At this point you should receive a discount on Category A items, despite not buying $100 worth of Category A.

This also works if item B is not listed as an Excluded Category.

I tried disabling plugins which resulted in no change, but couldn't change the theme or my website goes blank.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://www.darcygoedecke.com
Site URL: http://www.darcygoedecke.com
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Flywheel/4.1.0
PHP Version: 5.6.30-10+deb.sury.org~precise+2
PHP Post Max Size: 300 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.22.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.47 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (37) ###

Akismet Anti-Spam: by Automattic – 3.3.2
Chimpy Lite - MailChimp WordPress Plugin: by RightPress – 1.0.3
Duplicate Page: by mndpsingh287 – 2.3
Genesis Connect for WooCommerce: by StudioPress – 0.9.9
Genesis eNews Extended: by Brandon Kraft – 2.0.2
Genesis Featured Widget Amplified: by Nick_theGeek – 0.8.1
Genesis Responsive Slider: by StudioPress – 0.9.5
Genesis Simple Share: by Rainmaker Digital LLC – 1.0.9
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.8
Hide Related Products in WooCommerce: by Basit Ansari – 1.0
Image Widget: by Modern Tribe
Inc. – 4.4.3

Jetpack by WordPress.com: by Automattic – 4.9
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Ninja Forms: by The WP Ninjas – 3.1.1
Optimize your feed for feedly: by implenton – 1.0
PopupAlly: by AmbitionAlly – 2.0.1
Career Portfolio: by Miixee Lab – 1.8.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Text Blocks: by Hal Gatewood – 1.5.1
Search Everything: by Sovrn
zemanta – 8.1.9

Simple Social Icons: by Nathan Rice – 2.0.1
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 1.2.4
Revive Old Post (Former Tweet Old Post): by revive.social – 7.4.8
Visual Composer Undo/Redo: by ERROPiX – 1.2.2
Widget CSS Classes: by C.M. Kendrick – 1.4.0
Woo Out Of Stock Products: by Andrew Gunn
Ryan Van Ess – 2.1

WooCommerce MailChimp: by Saint Systems – 2.1.0
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.6.0

WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce USPS Shipping: by WooCommerce – 4.4.5
WooCommerce Wholesale Prices: by Rymera Web Co – 1.4.5
WooCommerce: by Automattic – 3.0.6
WooSidebars: by WooThemes – 1.4.3
WooSwipe: by Dean Oakley
Eric Jinks
BJ CJ – 1.1.6.5

WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WP Database Backup: by Prashant Walke – 4.3.7
YITH Infinite Scrolling: by YITHEMES – 1.0.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #333 - /shop/
Cart: #334 - /cart/
Checkout: #335 - /checkout/
My account: #336 - /my-account/

### Theme ###

Name: Fun WordPress Theme
Version: 1.1
Author URL: http://www.prettydarncute.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.5.0
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
Minimum spend is not something which has ever restricted itself to a category; it works on the subtotal field. **This matches how it works in 2.6 and prior versions.**

3.0 validation code: 

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-coupon.php#L815-L819

2.6 validation code:

https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/class-wc-coupon.php#L396-L400

Notice the logic is identical. Perhaps you have a customisation using the `woocommerce_coupon_validate_minimum_amount` filter before.

Closing as nothing has changed in 3.0 with this function.

**Comment by 4kittenbritches** [comment]
Hi Mike! Thanks for looking at this. 

Apologies, I've posted this issue on so many support sites trying to find help since the 3.0 update, I forgot where I originally started! I remembered after your response that prior to the update, I was using the "product % discount", which restricted the minimum purchase to the items or category listed. It was deleted in the update, so I switched to the fixed item discount to try to get it to work. But I can't get anything to behave the same now.

I saw in the 3.0 update notes that the product % discount method was deleted because it worked the same as the other discounts, but this was not the case. Here is my original post from another support site, when I discovered the issue:

-----

I just updated my woocommerce database and it seems as though there's been some changes to the coupon options!

It looks like you've done away with the option to do a product % discount! Now there's only the option for a cart % discount, which has messed a bunch of my coupons up!

For instance:

Normally I have a 10% discount on cards when people buy 5 or more. I had this set up as 10% discount on a min purchase of $20 (they're $4 each), linked to the cards product category. But now that it's a cart % discount, the customer can spend $20 on anything, not just cards and gets the discount on any number of cards!

When I change it to a fixed product discount, it still allows customers to only order 1 card and get the discount if the total order is over $20 from other items.

-----
I remember "product % discount" truly did limit the purchase minimum to the categories listed, because I was so excited it worked that way in testing it. And it was the reason I chose a % based discount, it was the only option that worked that way.

Thanks so much for your help and investigation into this! It has been a frustrating and discouraging time, and this feature is very important to my business!

Best,
Darcy

**Comment by mikejolley** [comment]
I've really just switched back to 2.6 branch and searched for all references to 'minimum_spend'. validate_minimum_amount is the only reference, and that works on subtotal. 

I suggest you grab a copy of 2.6 and test yourself; I cannot see how it would work in the way you describe.

**Comment by 4kittenbritches** [comment]
Okay! I will try that! I didn't know that was something I could do. Thanks :)

**Comment by mikejolley** [comment]
Yep, you'll find them here https://github.com/woocommerce/woocommerce/releases Be sure to do it on a test install and not your actual store :)
