### ISSUE TITLE
404 rest_no_route

### ISSUE THREAD

**Issue by marcoferretti** [woocommerce/woocommerce#15097]
### EXPLANATION OF THE ISSUE

I wrote a php script to import products from xml to woocommerce.

It worked great until now, when sistem give me back

[woocommerce_product_image_upload_error] error 400 – Error get remote image

From today it give me back:

[rest_no_route] error 404

I doesn t changed nothing in my code, it started alone.

Can anyone suggest me something?

### STEPS TO REPRODUCE THE ISSUE

API CALL:
http://www.gallianiduemila.it/api_query/api.php?r=articoli

EXAMPLE IMAGE:
http://www.gallianiduemila.it/wp-content/uploads/ahrwp/img/011/00000000000000001140_art_icol_12742.jpg

### SYSTEM STATUS
`
### WordPress Environment ###

Home URL: http://www.gallianiduemila.it
Site URL: http://www.gallianiduemila.it
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
POST remoto: ✔
GET remoto: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (32) ###

Ultimate Addons for Visual Composer: by Brainstorm Force – 3.13.4
CSS Plus: by Paulo E. Calixto – 1.4.4
Envato WordPress Toolkit: by Envato – 1.7.3
Google Language Translator: by Rob Myrick – 5.0.29
Iconize WordPress: by Mladen Ivančević – 1.1.4
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.0.1
Logo Carousel: by Sleepless Developers – 1.7.3
Meta Box: by Anh Tran – 4.10.4
Nav Menu Images: by Milan Dinić – 3.4
Ninja Forms: by The WP Ninjas – 3.0.31
Packlink PRO shipping solution: by 202 ecommerce – 1.0.0
Post Expirator: by Aaron Axelsen – 2.1.4
Slider Revolution: by ThemePunch – 5.3.1.5
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1
Simple Custom Post Order: by Colorlib – 2.3.2
WooCommerce Shipping Pro with Table Rate (BASIC): by WooForce – 1.2.1
Woocommerce Advanced Bulk Edit: by George Iron – 4.1.1
WooCommerce Checkout Manager: by Visser Labs – 4.1
WooCommerce: by WooThemes – 2.6.14
WooSidebars: by WooThemes – 1.4.3
Wordfence Security: by Wordfence – 6.3.5
WP Font Awesome Share Icons: by Spyros Vlachopoulos – 1.1.1
WP-Lister Pro for eBay: by Matthias Krok – 2.0.16
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP Migrate DB: by Delicious Brains – 0.9.2
WPFront User Role Editor: by Syam Mohan – 2.13
MailPoet Newsletters: by MailPoet – 2.7.8
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.3.1
YITH WooCommerce Ajax Search: by YITHEMES – 1.5.0
YITH WooCommerce Cart Messages: by YITHEMES – 1.1.6
YITH WooCommerce Wishlist: by YITHEMES – 2.0.16
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.26

### Settings ###

Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #7 - /negozio/
Carrello: #8 - /carrello/
Cassa: #9 - /checkout/
Il mio account: #10 - /mio-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome
Version: 3.2.5
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – Se stati modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
`api_query` Is not one of our endpoints and is not our API. This is custom.

**Comment by marcoferretti** [comment]
My question is: if this script that I wrote works correctly on other hosting, it just does not work right about that. Will there be a motivation?

**Comment by mikejolley** [comment]
Well without knowing the API calls it's making I cannot comment on it.

**Comment by marcoferretti** [comment]
$data_insert = [
                            'name' => $articolo_tabella->nome,
                            'type' => 'simple',
                            'regular_price' => $articolo_tabella->price,
                            'description' => $articolo_tabella->descrizione,
                            'short_description' => $short_description,
                            'sku' => $articolo_tabella->codice_articolo,
                            'weight' => $articolo_tabella->peso,
                            'dimensions' => [
                                'length' => $articolo_tabella->lunghezza,
                                'width' => $articolo_tabella->larghezza,
                                'height' => $articolo_tabella->altezza
                            ],
                            'sale_price' => $prezzo_sale,
                            'date_on_sale_from' => $articolo_tabella->sale_price_dates_from,
                            'date_on_sale_to' => $articolo_tabella->sale_price_dates_to,
                            'manage_stock' => true,
                            'in_stock' => true,
                            'stock_quantity' => $articolo_tabella->qta_disponibile,
                            'categories' => [
                                [
                                    'id' => $id_categoria_padre
                                ],
                                [
                                    'id' => $id_categoria_figlio
                                ]
                            ],
                            'attributes' => [
                                [
                                    'name' => 'marca',
                                    'options' => [ $articolo_tabella->marca ],
                                    'type' => 'select',
                                    'order_by' => 'menu_order',
                                    'has_archives' => true,
                                    'visible' => true
                                ],
                                [
                                    'name' => 'ean',
                                    'options' => [ $articolo_tabella->codice_barre ],
                                    'type' => 'select',
                                    'order_by' => 'menu_order',
                                    'has_archives' => true,
                                    'visible' => true
                                ]
                            ],
                            'images' => [
                                        [
                                         "src" => "http://www.gallianiduemila.it/wp-content/uploads/ahrwp/img/011/00000000000000001140_art_icol_12742.jpg",
                                         "position" => 0
                                        ]
                            ]
                        ];


            try {

                $woocommerce->post('products/', $data_insert);

            } catch(Exception $ex) {

                echo $ex->getCode()." | ".$ex->getMessage()."<br>"; exit;

            }

**Comment by mikejolley** [comment]
You should look at the library you're using to do the post, and test the requests in your client.
