### ISSUE TITLE
Non-static method WC_Geolocation::is_ip_address() should not be called statically

### ISSUE THREAD

**Issue by indramgl** [woocommerce/woocommerce#15099]
### EXPLANATION OF THE ISSUE

We upgraded WooCommerce to the 
![fireshot capture 5 - beranda - fakultas ekonomi dan bisnis universitas m_ - https___feb ummgl ac id_](https://cloud.githubusercontent.com/assets/6686910/26108486/e0341a32-3a76-11e7-8df0-72918656f878.png)
latest version. Once the upgrade is completed, our main page showed Strict Standards: Non-static method WC_Geolocation::is_ip_address() should not be called statically in /var/www/feb.ummgl.ac.id/wp-content/plugins/woocommerce/includes/class-wc-geolocation.php on line 106

### STEPS TO REPRODUCE THE ISSUE

There is no special step required to reproduce the issue. The only changes made to our site was plugin upgrade.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://feb.ummgl.ac.id
Site URL: https://feb.ummgl.ac.id
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: id_ID

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.9-1ubuntu4.21 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (32) ###

ManageWP - Worker: by ManageWP – 4.2.18
CloudFlare Flexible SSL: by iControlWP – 1.2.2
Admin Menu Editor: by Janis Elsts – 1.7.3
Administrator Khusus: by CV Solusi Integral – 0.0.2
Advanced Custom Fields PRO: by Elliot Condon – 5.4.5
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.2.1

Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Sidebars: by WPMU DEV – 3.0.6
Feature a Page Widget: by Mark Root-Wiley (MRWweb) – 2.0.10
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Heartbeat Control: by Jeff Matson – 1.0.3
Instagram Feed: by Smash Balloon – 1.4.8
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12.1
K Courses: by LunarTheme – 4.1
K Events: by LunarTheme – 4.1
K Gallery: by LunarTheme – 4.1
K Project: by LunarTheme – 4.1
K Shortcodes: by LunarTheme – 4.1
K Teachers: by LunarTheme – 4.1
OneSignal Push Notifications: by OneSignal – 1.14.3
PDF Embedder: by Dan Lester – 3.0.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.2.6
SSL Insecure Content Fixer: by WebAware – 2.4.0
TinyMCE Advanced: by Andrew Ozz – 4.5.6
User Role Editor: by Vladimir Garagulya – 4.32.3
W3 Total Cache: by Frederick Townes – 0.9.5.4
WooCommerce: by Automattic – 3.0.6
Wordfence Security: by Wordfence – 6.3.8
Yoast SEO: by Team Yoast – 4.7.1
WP Job Manager: by Automattic – 1.25.3
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set

### Theme ###

Name: Lincoln
Version: 4.1
Author URL: http://lunartheme.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: lincoln/woocommerce/archive-product.php
lincoln/woocommerce/content-product.php
lincoln/woocommerce/content-single-product.php
lincoln/woocommerce/loop/loop-start.php
lincoln/woocommerce/loop/orderby.php
lincoln/woocommerce/loop/sale-flash.php
lincoln/woocommerce/single-product/add-to-cart/external.php
lincoln/woocommerce/single-product/add-to-cart/grouped.php version 3.0.0 is out of date. The core version is 3.0.6
lincoln/woocommerce/single-product/add-to-cart/simple.php
lincoln/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
lincoln/woocommerce/single-product/meta.php
lincoln/woocommerce/single-product/price.php
lincoln/woocommerce/single-product/product-attributes.php
lincoln/woocommerce/single-product/product-image.php
lincoln/woocommerce/single-product/product-thumbnails.php
lincoln/woocommerce/single-product/rating.php
lincoln/woocommerce/single-product/related.php
lincoln/woocommerce/single-product/review.php
lincoln/woocommerce/single-product/sale-flash.php
lincoln/woocommerce/single-product/share.php
lincoln/woocommerce/single-product/short-description.php
lincoln/woocommerce/single-product/tabs/additional-information.php
lincoln/woocommerce/single-product/tabs/description.php
lincoln/woocommerce/single-product/tabs/tabs.php
lincoln/woocommerce/single-product/title.php
lincoln/woocommerce/single-product/up-sells.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
Already fixed in master.
