### ISSUE TITLE
Resolution to #11775 is not working

### ISSUE THREAD

**Issue by atandrauser** [woocommerce/woocommerce#15091]
Updating variant stock quantity via API v2 still does not work - following @mikejolley  suggestions at #11775 .
I have woocommerce Version 3.0.6

Sending request to THIS url as per suggestions above
https://shoplasunandsport.com/wp-json/wc/v2/products/1728/variations/2073?consumer_key=ck_f30ef9630f46bd6b2b5a0477a7402c081c2f8e3b&consumer_secret=XYZ

The productID and variant ID is correct - https://www.screencast.com/t/Ct7M9CZx32

We do get a response back but the field stock_quantity  for the variant 2073 is not updated. The response still shows    "stock_quantity":0

Please help. Below is response back from API call to update variant
video of testing steps here https://www.screencast.com/t/uf6fEfInQ

{  
   "id":2073,
   "date_created":"2017-02-27T23:03:08",
   "date_created_gmt":"2017-02-27T23:03:08",
   "date_modified":"2017-05-12T14:52:49",
   "date_modified_gmt":"2017-05-12T14:52:49",
   "description":"",
   "permalink":"https:\/\/shoplasunandsport.com\/product\/lanai-bia-tube-halter\/?attribute_pa_color=blk-taupe&attribute_pa_size=large",
   "sku":"018-508-L",
   "price":"105",
   "regular_price":"105",
   "sale_price":"",
   "date_on_sale_from":null,
   "date_on_sale_from_gmt":null,
   "date_on_sale_to":null,
   "date_on_sale_to_gmt":null,
   "on_sale":false,
   "visible":false,
   "purchasable":true,
   "virtual":false,
   "downloadable":false,
   "downloads":[  

   ],
   "download_limit":-1,
   "download_expiry":-1,
   "tax_status":"taxable",
   "tax_class":"",
   "manage_stock":true,
   "stock_quantity":0,
   "in_stock":false,
   "backorders":"no",
   "backorders_allowed":false,
   "backordered":false,
   "weight":"",
   "dimensions":{  
      "length":"",
      "width":"",
      "height":""
   },
   "shipping_class":"",
   "shipping_class_id":0,
   "image":{  
      "id":0,
      "date_created":"2017-05-12T15:30:56",
      "date_created_gmt":"2017-05-12T15:30:56",
      "date_modified":"2017-05-12T15:30:56",
      "date_modified_gmt":"2017-05-12T15:30:56",
      "src":"https:\/\/shoplasunandsport.com\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png",
      "name":"Placeholder",
      "alt":"Placeholder",
      "position":0
   },
   "attributes":[  
      {  
         "id":1,
         "name":"Color",
         "option":"BLK\/TAUPE"
      },
      {  
         "id":2,
         "name":"Size",
         "option":"LARGE"
      }
   ],
   "menu_order":0,
   "meta_data":[  
      {  
         "id":21503,
         "key":"_upsell_skus",
         "value":[  

         ]
      },
      {  
         "id":21504,
         "key":"_crosssell_skus",
         "value":[  

         ]
      },
      {  
         "id":21507,
         "key":"_min_variation_price",
         "value":""
      },
      {  
         "id":21508,
         "key":"_max_variation_price",
         "value":""
      },
      {  
         "id":21509,
         "key":"_min_variation_regular_price",
         "value":""
      },
      {  
         "id":21510,
         "key":"_max_variation_regular_price",
         "value":""
      },
      {  
         "id":21511,
         "key":"_min_variation_sale_price",
         "value":""
      },
      {  
         "id":21512,
         "key":"_max_variation_sale_price",
         "value":""
      },
      {  
         "id":21514,
         "key":"_file_path",
         "value":""
      },
      {  
         "id":21518,
         "key":"_product_url",
         "value":""
      },
      {  
         "id":21519,
         "key":"_button_text",
         "value":""
      }
   ],
   "_links":{  
      "self":[  
         {  
            "href":"https:\/\/shoplasunandsport.com\/wp-json\/wc\/v2\/products\/1728\/variations\/2073"
         }
      ],
      "collection":[  
         {  
            "href":"https:\/\/shoplasunandsport.com\/wp-json\/wc\/v2\/products\/1728\/variations"
         }
      ],
      "up":[  
         {  
            "href":"https:\/\/shoplasunandsport.com\/wp-json\/wc\/v2\/products\/1728"
         }
      ]
   }
}

**Comment by mikejolley** [comment]
Your request is missing from the report, but there is no bug here. See:

![2017-05-16 at 09 24](https://cloud.githubusercontent.com/assets/90977/26096596/952c80c2-3a19-11e7-813d-4656323db80e.png)

Using PUT/POST is important, as is ensuring the server supports it. Use a rest api client to test.

https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

**Comment by atandrauser** [comment]
Yes it works now,, the problem was in the request message body. This helped a lot. Thank you so much.

**Comment by strarsis** [comment]
Related issue: https://github.com/woocommerce/wc-api-php/issues/157
