### ISSUE TITLE
Variable Prices not being display after woocommerce update

### ISSUE THREAD

**Issue by VerifiedLabel** [woocommerce/woocommerce#15102]
Hi,

After updating woo commerce... the variable prices are no longer display...  When user picks feature on drop down selection... prices are not being displayed as before...

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://jlat.verifieddev.com
Site URL: https://jlat.verifieddev.com
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Advanced Floating Content: by Code Tides – 1.2.0
Code Snippets: by Shea Bunge – 2.8.5
Custom CSS Manager: by MyWebsiteAdvisor – 1.5.2
Easy FancyBox: by RavanH – 1.6
Fusion Core: by ThemeFusion – 1.7.6
Login Logo: by Mark Jaquith – 0.7
N-Media WooCommerce Personalized Product Meta Manager: by Najeeb Ahmad – 7.5
Password Protected: by Ben Huson – 2.0.3
Plugin Organizer: by Jeff Sterup – 8.1
Post Types Order: by Nsp Code – 1.9.3
Quick Paypal Payments: by aerin – 5.4.2
Really Simple SSL: by Rogier Lankhorst – 2.5.16
Revolution Slider: by ThemePunch – 5.0.9
Fast Secure Contact Form: by Mike Challis
Ken Carlson – 4.0.50

W3 Total Cache: by Frederick Townes – 0.9.5.4
Woocommerce All Discounts: by ORION – 1.11
WooCommerce: by Automattic – 3.0.6
Yoast SEO: by Team Yoast – 4.7.1
WP-DBManager: by Lester 'GaMerZ' Chan – 2.79
WP Retina 2x: by Jordy Meow – 5.0.5
WP Smush: by WPMU DEV – 2.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 3.8.7
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
Avada/woocommerce/cart/shipping-calculator.php
Avada/woocommerce/checkout/form-checkout.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
Avada/woocommerce/content-product.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/loop/pagination.php
Avada/woocommerce/myaccount/form-edit-address.php version 2.6.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/add-to-cart/variable.php version 2.4.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 3.0.2
Avada/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 3.0.2
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/description.php
Avada/woocommerce/single-product/title.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
No links to the site so cannot check.

**Comment by VerifiedLabel** [comment]
Hi,

The dev website url:  https://jlat.verifieddev.com/
One of the Product Page with Variable:   https://jlat.verifieddev.com/product/small-poly-barbell-labels/

Willy Freites
Digital Marketing Manager
Verified Label, Print & Promotions, Inc.
P: 1-800-764-6110   or   813-290-7721
E: wfreites@VerifiedLabel.com   <>   www.VerifiedLabel.com<http://www.verifiedlabel.com/>
EquipmentIDLabels.com<http://equipmentidlabels.com/> | JewelryLabelsAndTags.com<http://jewelrylabelsandtags.com/> | ShopCorporateApparel.com<https://shopcorporateapparel.com/>

**Comment by mikejolley** [comment]
Likely due to these https://dl.dropboxusercontent.com/s/m1dxbgo8z7e0l5t/2017-05-16%20at%2017.44.png

**Comment by VerifiedLabel** [comment]
Sorry but how do I address the error..  Can you provide suggestion on how to fix.

Willy Freites
Digital Marketing Manager
Verified Label, Print & Promotions, Inc.
P: 1-800-764-6110   or   813-290-7721
E: wfreites@VerifiedLabel.com   <>   www.VerifiedLabel.com<http://www.verifiedlabel.com/>
EquipmentIDLabels.com<http://equipmentidlabels.com/> | JewelryLabelsAndTags.com<http://jewelrylabelsandtags.com/> | ShopCorporateApparel.com<https://shopcorporateapparel.com/>

**Comment by mikejolley** [comment]
Not really because those scripts are not part of WooCommerce.
