### ISSUE TITLE
Cannot Set Default Variation to "0"

### ISSUE THREAD

**Issue by catrymer** [woocommerce/woocommerce#15103]
### EXPLANATION OF THE ISSUE

If you have variations that are numbers (0, 1, 2, etc) you can set any of them as the default value except for 0. If you try to set 0 as the default variation value WooCommerce saves it as having no default value set.

### STEPS TO REPRODUCE THE ISSUE

1. Create a variable product with variations of 0, 1, and 2.
2. Set 1 as the default form value.
3. Open the product in the shop and note that the dropdown defaults to 1, as it should.
4. Edit the variable product to set 0 as the default form value and click the update button.
5. Open the product in the shop and note that the dropdown defaults to "choose an option" instead of defaulting to 0. 
6. Return to the variations tab and note that setting the default value to 0 didn't save and the default form value now displays as if you had chosen the 'no default' option.

Here's [a screencast](http://cld.wthms.co/S9U2I) demonstrating these steps:

![screen_capture_on_2017-05-16_at_11-06-29](https://cloud.githubusercontent.com/assets/8796369/26119000/fad8dba0-3a28-11e7-9859-4e6a06923a8d.gif)

**Comment by timondavis** [comment]
https://github.com/woocommerce/woocommerce/pull/15144
