### ISSUE TITLE
Make importer/parser handle relative fields.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#15106]
Relates to #13082 .

There are some fields in the schema like post_parent and cross_sell_ids that are defined as:

```
Can be just a numeric ID e.g. id:100, a row ID if importing 
for the first time e.g. row:20, or a SKU. Export will use SKU when possible.
```

We need to implement handling of these sorts of fields in the importer (and possible the parser, depending on implementation).

**Comment by claudiulodro** [comment]
I've spent some time thinking through this, and I don't see a good way of handling this in all situations. 

ID or SKU should be fine as long as the parent is always above the child in the CSV, because the parent will have been created by the time the child is processed. 

If the parent is below the child in the CSV, you'd have to process items in the CSV until you found the correct parent, then go back to the child, and update the child. I think that is going to be crazy complicated, especially with batch processing.

`row:X` doesn't seem to be feasible with batch processing, either. If we read and process 10 rows at a time and the parent is in a different batch than the child, I'm not quite sure how to handle that. "row:123" isn't useful when you have a 10-item segment of the CSV with no row numbers.

How do you feel about changing this to:
```
A numeric ID e.g. id:100 or a SKU. 
Referenced products should be located above the reference in the CSV
```

Thoughts or ideas about how to implement this feature?
@mikejolley @claudiosanches

**Comment by claudiosanches** [comment]
For `row:` will force open and parse the file again... Maybe better forget about `row:`, not to mention that this could lead to wrong results if you change the CSV after.

**Comment by mikejolley** [comment]
Are we still doing `row:`? I'm having second thoughts on that - we should really enforce SKUs

**Comment by mikejolley** [comment]
We've decided not to handle this in v1 and wait for feedback.
