### ISSUE TITLE
API - woocommerce_currency should return separate field for symbol

### ISSUE THREAD

**Issue by belcherj** [woocommerce/woocommerce#15101]
When using the wc-api to get general settings `/wc/v2/settings/general`, the `woocommerce_currency` object has an options array that has the following format:

`{AED: "United Arab Emirates dirham (&#x62f;.&#x625;)"}`

This results in having to use a regex to separate the country and currency name from the currency symbol.

I propose that the options object should take this format:

`{
  AED: {
    country: "United Arab Emirates",
    currency: "dirham",
    symbol: "&#x62f;.&#x625;"
  }
}`

**Comment by belcherj** [comment]
@mattyza This is the enhancement reuqest that we talked about on Friday.

**Comment by mikejolley** [comment]
I've moved this to the API dev repo here: https://github.com/woocommerce/wc-api-dev/issues/2
