### ISSUE TITLE
Replace add to cart button with dropdown quantity

### ISSUE THREAD

**Issue by umerkakar** [woocommerce/woocommerce#15109]
### EXPLANATION OF THE ISSUE

I am trying to achieve that user just select number of products from a dropdown menu. And then products auto add to cart using ajax. Means i completely want to remove add to cart button. But only the number of items to cart from select box. 
Screenshot: http://prntscr.com/f8nfyj
I have made some code. That is working with click. As it still have  submit button. But that can lead you to understand, what I need.

<select id="products" data-quantity="0"
data-product_id="<?php echo get_the_ID( $loop->post->ID ); ?>" 
data-product_sku="">

<?php for($i=0; $i<=30; $i++){
$selected = ($i==0) ? ' selected="selected"' : '';
?>
<option value="<?php echo $i; ?>" <?php echo $selected; ?>><?php echo $i; ?></option>
<?php } ?>

</select>
<input  id="productz" type="submit"
data-quantity="0" data-product_id="<?php echo get_the_ID( $loop->post->ID ); ?>"
class="button alt ajax_add_to_cart add_to_cart_button product_type_simple">

Waiting for response.

**Comment by mikejolley** [comment]
I'm not sure why you're asking for custom code here (presumably for your client).

```
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.
```

What you're doing may or may not be possible, I've not tried, but I do know the ajax cart buttons accept a data-quantity attribute so maybe you/a developer can utilise that.

**Comment by umerkakar** [comment]
I did that last night. 👍
