### ISSUE TITLE
Error URL in Pricing & Dimensions fields + error message Warning: date() expects parameter 2 to be long, string given in /nas/content/staging/bahamafood1/wp-includes/functions.php on line 112

### ISSUE THREAD

**Issue by thenewbreed** [woocommerce/woocommerce#15108]
### EXPLANATION OF THE ISSUE

The fields for Regular Price, Sale Price, and the Shipping Dimensions now have an image URL replacing their original info. 

I am using WooCommerce as a catalogue and am getting the following error message in the backend under the Product Attributes options:

```
Warning: date() expects parameter 2 to be long, string given in /nas/content/staging/bahamafood1/wp-includes/functions.php on line 112

Warning: date() expects parameter 2 to be long, string given in /nas/content/staging/bahamafood1/wp-includes/functions.php on line 114

Warning: date() expects parameter 2 to be long, string given in /nas/content/staging/bahamafood1/wp-includes/functions.php on line 116

Warning: date() expects parameter 2 to be long, string given in /nas/content/staging/bahamafood1/wp-includes/functions.php on line 117

Warning: date() expects parameter 2 to be long, string given in /nas/content/staging/bahamafood1/wp-includes/functions.php on line 112

Warning: date() expects parameter 2 to be long, string given in /nas/content/staging/bahamafood1/wp-includes/functions.php on line 114

Warning: date() expects parameter 2 to be long, string given in /nas/content/staging/bahamafood1/wp-includes/functions.php on line 116

Warning: date() expects parameter 2 to be long, string given in /nas/content/staging/bahamafood1/wp-includes/functions.php on line 117


```

### STEPS TO REPRODUCE THE ISSUE

This is a staging site. I installed the following plugins which all worked correctly:

- Media File Renamer
- Media Library Categories
- Phoenix Media Rename
- Woo Custom Stock Status

Other things I did were to turn off "Stock Management" option and then turn it back on. I also have another user (role is "Editor") logged in and updating products in WooCommerce including adding images. The URL that is an image URL showing up in the wrong places is a file that she uploaded. This file also showed up as the background of the Menu on the front of the page. I deleted the image.

I also deactivated all new plugins to no avail.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://bahamafood1.staging.wpengine.com
Site URL: http://bahamafood1.staging.wpengine.com
WC Version: 2.6.4
Log Directory Writable: ✔
WP Version: 4.6.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30-1+wpengine8
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.4
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to \"Downloads\" and download the \"Binary / gzip\" file next to \"GeoLite Country\"

### Active Plugins (22) ###

Akismet: by Automattic – 3.1.11
Artbees Themes Captcha: by Jose Rodriguez  – 1.0
bbPress: by The bbPress Community – 2.5.10
BuddyPress: by The BuddyPress Community – 2.6.2
Constant Contact Forms by MailMunch: by MailMunch – 2.0.6
Contact Form 7: by Takayuki Miyoshi – 4.5
WPBakery Visual Composer (Artbees Modified Version): by Michael M - WPBakery.com – 4.12.1
MailChimp for WordPress: by ibericode – 3.1.11
Members: by Justin Tadlock – 1.1.2
Product Enquiry for WooCommerce: by WisdmLabs – 1.4
Search & Replace: by Inpsyde GmbH – 3.1.0
WP woocommerce best selling products by category: by WP Online Support – 1.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.40

User Role Editor: by Vladimir Garagulya – 4.27.1
Widget Importer & Exporter: by Steven Gliebe – 1.3.1
WooCommerce Product Search: by itthinx – 1.6.0
Woocommerce PWP: by  – 1.0.0
WooCommerce: by WooThemes – 2.6.4
WordPress Importer: by wordpressdotorg – 0.6.3
WordPress Social Login: by Miled – 2.3.0
WP All Import Pro: by Soflyy – 4.4.0
WP Editor: by Benjamin Rojas – 1.2.6.3

### Settings ###

Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: ❌ Page not set
Cart: #6050 - /cart/
Checkout: ❌ Page not set
My Account: ❌ Page not set

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Jupiter Child Theme
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: jupiter
Parent Theme Version: 5.1.7
Parent Theme Author URL: http://themeforest.net/user/artbees
WooCommerce Support: ✔

### Templates ###

Overrides: jupiter-child/woocommerce/archive-product.php
jupiter-child/woocommerce/cart/cart-empty.php
jupiter-child/woocommerce/cart/cart.php
jupiter-child/woocommerce/cart/mini-cart.php
jupiter-child/woocommerce/cart/shipping-calculator.php
jupiter-child/woocommerce/checkout/cart-errors.php
jupiter-child/woocommerce/checkout/form-checkout.php
jupiter-child/woocommerce/checkout/form-coupon.php
jupiter-child/woocommerce/checkout/review-order.php
jupiter-child/woocommerce/content-product.php
jupiter-child/woocommerce/content-product_cat.php
jupiter-child/woocommerce/content-single-product.php
jupiter-child/woocommerce/global/form-login.php
jupiter-child/woocommerce/loop/add-to-cart.php
jupiter-child/woocommerce/loop/loop-end.php
jupiter-child/woocommerce/loop/loop-start.php
jupiter-child/woocommerce/loop/no-products-found.php
jupiter-child/woocommerce/loop/orderby.php
jupiter-child/woocommerce/loop/pagination.php
jupiter-child/woocommerce/loop/price.php
jupiter-child/woocommerce/loop/rating.php
jupiter-child/woocommerce/loop/result-count.php
jupiter-child/woocommerce/loop/sale-flash.php
jupiter-child/woocommerce/myaccount/form-edit-account.php
jupiter-child/woocommerce/myaccount/form-edit-address.php
jupiter-child/woocommerce/myaccount/form-login.php
jupiter-child/woocommerce/myaccount/form-lost-password.php
jupiter-child/woocommerce/notices/error.php
jupiter-child/woocommerce/notices/notice.php
jupiter-child/woocommerce/notices/success.php
jupiter-child/woocommerce/order/form-tracking.php
jupiter-child/woocommerce/single-product/add-to-cart/external.php
jupiter-child/woocommerce/single-product/add-to-cart/grouped.php
jupiter-child/woocommerce/single-product/add-to-cart/simple.php
jupiter-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
jupiter-child/woocommerce/single-product/meta.php
jupiter-child/woocommerce/single-product/price.php
jupiter-child/woocommerce/single-product/product-attributes.php
jupiter-child/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 2.6.3
jupiter-child/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 2.6.3
jupiter-child/woocommerce/single-product/rating.php
jupiter-child/woocommerce/single-product/related.php
jupiter-child/woocommerce/single-product/sale-flash.php
jupiter-child/woocommerce/single-product/share.php
jupiter-child/woocommerce/single-product/short-description.php
jupiter-child/woocommerce/single-product/tabs/additional-information.php
jupiter-child/woocommerce/single-product/tabs/description.php
jupiter-child/woocommerce/single-product/tabs/tabs.php
jupiter-child/woocommerce/single-product/title.php
jupiter-child/woocommerce/single-product/up-sells.php

: Learn how to update outdated templates
`
</details>

**Comment by mikejolley** [comment]
"The fields for Regular Price, Sale Price, and the Shipping Dimensions now have an image URL replacing their original info."

What are you even talking about here? Can you show a screenshot? I fail to see how this could be a core issue.

**Comment by thenewbreed** [comment]
One image is how it looks on the front-end and the other is how it looks on the backend.


![woocommerce errors](https://cloud.githubusercontent.com/assets/13543624/26123297/64979e22-3a48-11e7-9fff-a2cb396ffaa1.png)
![woocommerce errors2](https://cloud.githubusercontent.com/assets/13543624/26123296/6495f4d2-3a48-11e7-9cae-932f1956aedf.png)

**Comment by mikejolley** [comment]
It looks like someone or something has set all those values invalid (importer? user error?)

**Comment by thenewbreed** [comment]
The data was imported correctly. This issue happened yesterday and I cannot locate the cause. I listed above recent actions on the site yesterday:

STEPS TO REPRODUCE THE ISSUE

This is a staging site. I installed the following plugins which all worked correctly:

Media File Renamer
Media Library Categories
Phoenix Media Rename
Woo Custom Stock Status
Other things I did were to turn off "Stock Management" option and then turn it back on. I also have another user (role is "Editor") logged in and updating products in WooCommerce including adding images. The URL that is an image URL showing up in the wrong places is a file that she uploaded. This file also showed up as the background of the Menu on the front of the page. I deleted the image.

I also deactivated all new plugins to no avail.

**Comment by mikejolley** [comment]
Listed a bunch of 3rd party plugins are not 'steps to reproduce issue'. If you cannot REPRODUCE IT AGAIN and without extensions, the issue is not core?

**Comment by thenewbreed** [comment]
The site was fine yesterday and then the user doing the product updates pointed out to me this new issue. If I could undo it, then I could re-produce it, but my issue is that the problem is occuring and I am looking for help on how to undo it. The best I could do was list what I did yesterday. The other user edited exisiting products and uploaded images. 

If you do not think that you could help me here, then maybe you can point me to a better place. I did a search and found that someone else had a similar problem and posted here. Then they posted that they found the solution, but did not post it.

**Comment by mikejolley** [comment]
Why not work out which one of the plugins you added caused the issue, and then you can either find an alternative or patch it?

Core doesn't even let you set prices as image URLs so whatever it is is writing to the database or updating post meta directly.

It could be that you did an import with WP All Import Pro and overwrote the product data...

If the data is changed in the database, WooCommerce cannot undo it. You'd need to restore a backup or  recreate those affected products.

Interested to hear what you found caused it, but I don't see how core could break this, and it's not affecting other users or we'd have heard by now because that would be serious :)

Thanks
