### ISSUE TITLE
Purchases notes no longer included for variable products

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce#15115]
Purchase notes that are added through the product data (advanced tab), are no longer included in the processing / completed order email, with variable products. It's still included with simple products.

Here's where the note gets added: 

<img width="764" alt="screen shot 2017-05-17 at 11 53 11 am" src="https://cloud.githubusercontent.com/assets/6198774/26148983/c5da12fe-3af8-11e7-9d7b-734146e137b2.png">

Simple VS variable product order processing emails: 

Simple: 

<img width="428" alt="screen shot 2017-05-17 at 12 04 58 pm" src="https://cloud.githubusercontent.com/assets/6198774/26149179/9712901c-3af9-11e7-9a0d-55cfd51a2d11.png">

Variable: 

<img width="417" alt="screen shot 2017-05-17 at 12 06 53 pm" src="https://cloud.githubusercontent.com/assets/6198774/26149200/ab1ea546-3af9-11e7-9d9a-be156cc5f9cb.png">

### STEPS TO REPRODUCE THE ISSUE

1. open the 'advanced' tab in product data on any variable item, and add a purchase note
2. add any variation of this product to your cart and proceed to checkout 
3. checkout

### SYSTEM STATUS

<details>

```
### WordPress Environment ###

Home URL: https://rynald0.wpsandbox.me
Site URL: https://rynald0.wpsandbox.me
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.8-beta1-40736
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

Jetpack by WordPress.com: by Automattic – 4.9
WooCommerce Advanced Notifications: by WooCommerce – 1.2.7
WooCommerce Advanced Ajax Layered Navigation: by Sixty-One Designs
Inc. – 1.4.9

WooCommerce: by Automattic – 3.0.7
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

</details>

Cheers!

**Comment by merylvdm** [comment]
Has this been corrected? I just discovered this today - took a while to figure out as my customers have been buying classes that don't start till the fall so no one was panicking when they didn't get the log in info. I just updated to the latest version of Woocommerce but haven't done a test to see if it is fixed yet.

**Comment by KissWebMedia** [comment]
Even better, instead of variation inheriting the purchase_note from the parent product, each variation should have its own optional purchase note field.

**Comment by heikohaensge** [comment]
Now, May 2024, still purchase notes are not included in WooCommerce emails.
Anything new on this front?
