### ISSUE TITLE
ACF Custom Image Fields Not Saving in Order Backend After "Save" Button Becomes "Update"

### ISSUE THREAD

**Issue by DASdrones** [woocommerce/woocommerce#15112]
### EXPLANATION OF THE ISSUE

Yesterday I updated to Woocommerce 3.0.6 (and just a minute ago 3.0.7) and the Advanced Custom Fields for basic image uploads are no longer saving the data upon updating a shop order from the backend. It will upload and properly display it in the panel, but once you click “update” for an order, the field returns to a blank, default state.

I’ve tested a separate image upload field on a WooCommerce product, as well as a generic post, and the image upload function works as intended. The issue seems to be focused on post types of “shop_order” only, as if the location/address where the data is saved for the field on the database has been moved.

If I upload/attach an image, then resend an email from the dropdown selection, it saves the image upon page refresh.

If I click the actual “Update” button, it doesn’t save the fields. <– This is clearly the issue. Something tied into this new button update:

Tweak – Improve “Save Order” button to reproduce WordPress post/page behavior.

WordPress 4.7.4
WooCommerce 3.0.6
Advanced Custom Fields 4.4.11

### STEPS TO REPRODUCE THE ISSUE

Create a new order from the dashboard. Click "create" to save the order. After the page refreshes, upload or choose an image from a custom field from Advanced Custom Fields. When clicking "update," the page will refresh but the custom field returns to a default blank state.

It works if the order is brand new, and the button says "Create," but the moment an order is being "updated" it won't save custom field data.

### SYSTEM STATUS

<details>
```
System Status checks out all items as good.
```
</details>

**Comment by vipii** [comment]
Same issue here.
When I try to edit a value of the custom field in an order.
The value is not being saved.

When creating a new order, the value is being saved correctly. But not when updating the post.
We need this fixed ASAP!

**Comment by mikejolley** [comment]
The create button:

```
<input type="submit" class="button save_order button-primary" name="save" value="Create">
```

The update button:

```
<input type="submit" class="button save_order button-primary" name="save" value="Update">
```

Identical names and classes. Maybe you should ask ACF? I doubt anyone would target a button by value since that would break with translations.

**Comment by DASdrones** [comment]
Thanks for the response Mike.

Where can the code that you mentioned be found in the core?

**Comment by mikejolley** [comment]
Here https://github.com/woocommerce/woocommerce/blob/31651e41cbc1ad8b731532f6629a334c8ddf94c2/includes/admin/meta-boxes/class-wc-meta-box-order-actions.php#L84

As you can see, only the text of the button changes like with posts and other post types.

I just tested with ACF and an image field and had no issue with it saving - the placeholder image remained.

Maybe ensure the name of your field does not clash with a field WooCommerce uses, because the WC data would take precedence.
