### ISSUE TITLE
Android Tablet use: Cannot edit Product Categories

### ISSUE THREAD

**Issue by tenaja** [woocommerce/woocommerce#15118]
### EXPLANATION OF THE ISSUE

Brand new installation of woocommerce. Android 7.1.2, on Pixel C tablet.
I can edit products, but not the Categories. None of the edit links work with the touchscreen. I must use the Tab key on the keyboard to find the Edit link, and hit the Enter key. (This is very tedious.)
I can create new, and drag & drop the categories, and that is it.

### STEPS TO REPRODUCE THE ISSUE
Login on to admin using an Android tablet, navigate to Product Categories, and attempt to edit a category.

**Comment by mikejolley** [comment]
What about post categories?

**Comment by mikejolley** [comment]
Looks to be the drag and drop script. Maybe we can add a handle icon to avoid the entire row being draggable.

**Comment by tenaja** [comment]
Thanks!
