### ISSUE TITLE
Products with variations showing as 'invalid' at checkout

### ISSUE THREAD

**Issue by TintaCrayons** [woocommerce/woocommerce#15117]
### EXPLANATION OF THE ISSUE

Products with variations are coming up as an 'invalid product' at the payment gateway. This started happening after update 3.0.5 and is continuing. It is occurring on existing variable products and newly created variable products.

### STEPS TO REPRODUCE THE ISSUE

1. Create a product with 1 or more variation
2. Add it to the basket
3. Click on the 'proceed to payment' button and the 'invalid product' error comes up

### SYSTEM STATUS

<`
### WordPress Environment ###

Home URL: http://www.tintacrayons.com.au
Site URL: http://www.tintacrayons.com.au
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache/2.4.25
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (21) ###

ManageWP - Worker: by ManageWP – 4.2.18
Affiliatly Integration: by Affiliatly.com – 2.0
Akismet Anti-Spam: by Automattic – 3.3.2
Chamber Dashboard Business Directory: by Morgan Kay – 2.8.7
Contact Form 7: by Takayuki Miyoshi – 4.7
Easy SMTP: by James Stamford  – 1.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.9
Image Widget: by Modern Tribe
Inc. – 4.4.3

Jetpack by WordPress.com: by Automattic – 4.9
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
MailChimp for WordPress: by ibericode – 4.1.2
MailChimp for WordPress - Premium: by ibericode – 3.3.11
Modular Custom CSS: by Nick Halsey – 2.0
Social Media Feather: by socialmediafeather – 1.8.3
What The File: by Never5 – 1.5.3
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.2
WooCommerce: by Automattic – 3.0.7
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #898 - /shop/
Basket: #899 - /basket/
Checkout: #900 - /checkout/
My account: #901 - /my-account/

### Theme ###

Name: Boutique
Version: 2.0.8
Author URL: http://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`>

**Comment by mikejolley** [comment]
What gateway? Tried simply bank transfer?

**Comment by TintaCrayons** [comment]
Hi Mike, our site uses paypal as the payment gateway

**Comment by mikejolley** [comment]
I tried the express button on cart and checkout button and neither gave that error. If it's the error core throws it happens when the variation/product is invalid or cannot be loaded - I didn't see this occur however. 

If you can provide more details on what product, and screenshot the error etc I could possibly look again but it's hard to do anything without access or seeing it first.

Thanks

**Comment by TintaCrayons** [comment]
Hi Mike, it's on any of the variable products on the site. Choose either the 'Easter Dozen', 'Name Crayons' or 'Christmas Crayons'. Add the variation to the cart and then click through to fill in all the address details and hit 'proceed to paypal'. That's when the error appears.

![screenshot 4](https://cloud.githubusercontent.com/assets/28756428/26435245/36f04c70-4151-11e7-97ab-a00ff47add8b.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/28756428/26435244/36efaffe-4151-11e7-8ce7-05b44fd5942a.png)

**Comment by TintaCrayons** [comment]
I also tried creating brand new variable products and still got the error

**Comment by mikejolley** [comment]
@TintaCrayons only with PayPal? Can you test another gateway like bacs?

**Comment by TintaCrayons** [comment]
@mikejolley, I activated BACS and got the same issue

**Comment by TintaCrayons** [comment]
![screenshot 6](https://cloud.githubusercontent.com/assets/28756428/26516673/a9cea00c-42cd-11e7-99f5-674fbaf2200a.png)
![Uploading Screenshot (7).png…]()

**Comment by mikejolley** [comment]
Is there any custom code present at all? Just affects variable products? I'm not able to replicate this locally at all, and it's not being reported anywhere else.

**Comment by TintaCrayons** [comment]
@mikejolley, no custom code and yes, affects all variable products - existing ones and new ones. Our web developer can't find the issue either. Through google, we found some people raising the same/similar issue.

**Comment by mikejolley** [comment]
Sometimes folks forget about custom code in the theme functions.php file.  I suggest you test with a default theme active.

**Comment by bronthulke** [comment]
Hi, I'm the web developer that @TintaCrayons has mentioned, I thought it best to jump in myself at this stage to avoid "man in the middle" syndrome :) 

I've done some deeper digging and found that a plugin called "Affiliatly Integration" is causing the issue.  Having seen other people's reports on the same issue, it looks like we're all suffering similar root causes around code such as:

```
if ($product_variation_id)
		// 	$product = new WC_Product($v['variation_id']);
		// else
			$product = new WC_Product($v['product_id']);
```

Do you know what has changed that may cause this to not work?  If I take out the IF statement so that it's just `$product = new WC_Product($v['product_id']);` then it works fine.  Thanks.

**Comment by mikejolley** [comment]
@bronthulke The product class instances have validation on the type to ensure the ID being passed is actually valid. `WC_Product` is also a generic class, not specifically for variations, so I don't think this code ever would have worked 'properly' but it may not have errored before the validation as added.

The correct approach is to pass the id to the `wc_get_product()` function. This will load the correct class based on the ID and return either a product instance, or false if not valid.

**Comment by sathapa** [comment]
@bronthulke @mikejolley Did you guys ever found the root cause of this?
I'm also having this same issue on payment process. And, does remove the error on commenting out the 'variation_id' instance? But, other way around would be a better approach rather than changing a core plugin file. 
Thanks.
