### ISSUE TITLE
Bug with woocommerce 3.0 and slug

### ISSUE THREAD

**Issue by wooheb** [woocommerce/woocommerce#15111]
### EXPLANATION OF THE ISSUE

Hello, after the new update (3.0) all the links to the Shop page not working.(from the content-text\image)
it is happend if the url slug is in Hebrew ("/hebrew word" instead "/Shop")
the links take to the shop page but the shop page not showing any products- only text with "Showing the single result"
you can see it live : 
http://testbug.s21.upress.link/
There is link inside the content (not work) and inside the menu (work) - the url is the same.

Thank You.
### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Go to settings > permalinks and save.

If that does not clear it up, on the same page, give attributes/categories etc a unique prefix and save again. That should clear up the conflict.

**Comment by wooheb** [comment]
it is not happend on categories pages - only on the main shop page.
and i try your suggestion -not working.

**Comment by mikejolley** [comment]
System status?

**Comment by wooheb** [comment]
![wo](https://cloud.githubusercontent.com/assets/28747277/26150813/e468a2c0-3b08-11e7-94a8-4736a844c4c0.png)
i am also tried to change all the "Optional" to unique...

**Comment by mikejolley** [comment]
You didn't add an attribute base URL, so I don't think you did my suggestions.

**Comment by wooheb** [comment]
you mean something like this?
![d](https://cloud.githubusercontent.com/assets/28747277/26155794/0ed03050-3b1d-11e7-92c2-548a6a117229.png)

if yes- i did it before...

**Comment by mikejolley** [comment]
Need the system status report.

**Comment by wooheb** [comment]
the system status report inside the first comment

**Comment by mikejolley** [comment]
Does it only happen with your custom shop name then? Can you paste it here so I can try?

**Comment by wooheb** [comment]
http://testbug.s21.upress.link/%D7%97%D7%A0%D7%95%D7%AA/

this is the link.
it is happend only if the slug name is on hebrew.
if i will change the url to english it will work.
and yes only with the main shop page.

**Comment by mikejolley** [comment]
Use a different product base and it won't happen either. Looking into it.
