### ISSUE TITLE
woocommerce_api_authentication_error

### ISSUE THREAD

**Issue by lsantaniello** [woocommerce/woocommerce#15121]
Hy guys,
I have a problem with communicate with my wordpress/woocommerce store. I installed it in my local machine. I invoke the service inside my ionic app.

`     this.WooCommerce = WC({
      url: "http://localhost/wordpress",
      consumerKey: "ck_7681851dd851c8b5eacd7cda61e5fc6cb997a653",
      consumerSecret: "cs_e4ee5f928c6ae1d0243478bb95b6d71f6ce3d5aa"
    });`

CALL 1
`    this.WooCommerce.getAsync("products").then( (data) => {
      console.log(data);
    }, (err) => {
      console.log(err);
    })`

CALL 2
`this.WooCommerce.postAsync('customers', customerData).then( (data) => {
      console.log(data);
    }, (err) => {
      console.log(err);
    })`

CALL 1 works but CALL 2 always return the following error (in italian language):

`{"errors":[{"code":"woocommerce_api_authentication_error","message":"Firma non valida - la firma fornita non corrisponde."}]}`

I also implemented the PHP client and it works successfully

Could you please help me?
Thanks

Luca

**Comment by mikejolley** [comment]
If it works with the PHP client and a REST client (https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API) the problem is down to the code you're using - we cannot support custom code here.

**Comment by lsantaniello** [comment]
Sorry, I used PHP because I'd like found the reason of my problem. The problem is related to Woocommerce REST API and apache configuration, I think.
