### ISSUE TITLE
Product Variation

### ISSUE THREAD

**Issue by Copeland231** [woocommerce/woocommerce#15123]
Having Problem with woocommerce products variations when adding variations or even editing it in products would just stuck on the spinning ball loading icon, it also happen when adding attributes.

It was working fine before and then just suddenly stopped working.

I'm very new to everything WP related so I am at a standstill. 

Please help, anyone.

![image](https://cloud.githubusercontent.com/assets/28759076/26162832/adb0b1e0-3adc-11e7-98a3-157ef443f898.png)

-Mike C.

**Comment by lynn219** [comment]
Mine is the same way. Variations does not load at all.
-Lynn

**Comment by mikejolley** [comment]
As stated many times this is a conflict and needs to be identified - we cannot fix JS errors caused by other plugins.

See https://github.com/woocommerce/woocommerce/issues/14972#issuecomment-300402820

Once identified, the other plugin can be disabled or updated (if the author is aware).

Thanks
