### ISSUE TITLE
Extra unnecessary(?) meta data being created for variations since 3.0

### ISSUE THREAD

**Issue by peterigz** [woocommerce/woocommerce#15122]
### EXPLANATION OF THE ISSUE

Since v3.0.x When saving a variation, lots of new meta data is being created. In 2.6 there were 11-15 postmeta items for each variation in my store (depending on whether you left some fields blank I presume), now it's creating 34 which will really start to ramp up the number of records in the postmeta table (I have a few thousand variations). Maybe it's nothing to worry about but it feels like it shouldn't be saving a meta value if it doesn't need to which is what appeared to happen in 2.6.

Looks like in WC_Product_Variation_Data_Store_CPT there's a 'Callback to remove unwanted meta data' so I don't know if that's something that can be used at all?

### STEPS TO REPRODUCE THE ISSUE

Simply save a new variation or update an old one and compare the meta data to a 2.6 version.

**Comment by mikejolley** [comment]
I've added a note to https://github.com/woocommerce/woocommerce/pull/13865 to look at it all at the same time. Right now all meta will be created so it knows not to use the default values.
