### ISSUE TITLE
Recalculate add additional Tax data

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/woocommerce#15127]
### EXPLANATION OF THE ISSUE
The Recalculate button will add some extra tax rows:
Before Recalculate:
<img width="827" alt="beforerecalculate_order_items_meta" src="https://cloud.githubusercontent.com/assets/25877146/26166724/b97af44c-3b34-11e7-8388-e7b59e844c7c.png">

After Recalculate in Order_Items
<img width="759" alt="afterrecalculate_order_items" src="https://cloud.githubusercontent.com/assets/25877146/26166659/74beb794-3b34-11e7-9b51-c7e21f63c2b0.png">

After Recalculate in Order_Items_Meta
<img width="677" alt="afterrecalculate_order_items_meta" src="https://cloud.githubusercontent.com/assets/25877146/26166734/ccc699ca-3b34-11e7-8365-134de73ac0fb.png">

The database is still the same as when I reporting #15057

### STEPS TO REPRODUCE THE ISSUE
1. Add an order in the frontend
2. Use the recalculate button in the backend

### SYSTEM STATUS

<details>
### WordPress Environment ###

Home URL: https://eval.firewoodshop.ch
Site URL: https://eval.firewoodshop.ch
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 7.1.4
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: fws_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.7

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CHF (CHF)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /warenkorb/
Checkout: #7 - /kasse/
My account: #8 - /mein-konto/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by mikejolley** [comment]
There are no taxes shown though right?

**Comment by thomas-zg** [comment]
Not in the backend, but there was an VAT field in the template of WooCommerce PDF Invoices & Packing Slips Premium Templates. After the Recalculate, the new data were shown in the report.
<img width="782" alt="bildschirmfoto 2017-05-17 um 19 17 37" src="https://cloud.githubusercontent.com/assets/25877146/26167059/000903da-3b36-11e7-83ce-3dd4516ecf2f.png">
