### ISSUE TITLE
woocommerce_add_to_cart_validation - Variations not working

### ISSUE THREAD

**Issue by grosssmutttr** [woocommerce/woocommerce#15120]
Before wommerce 3.0 it was possible to check the variation data send through a add to cart click:

```
add_action('woocommerce_add_to_cart_validation', 'val_product_validation', 10, 3);

function val_product_validation($flaq, $product_id, $quantity, $variation_id, $variations) {
 try {
        $prod = new WC_Product_Variation($product_id);
        if ($prod->get_type() == 'variation') {
            $prod_is_set = get_post_meta($prod->parent->get_id(), '_is_product_set', true);
        }
    } catch (Exception $ex) {
        
    }
}
```

Since 3.0 the $variation_id and $variations ist empty so it is not possible to validate variation products anymore?

**Comment by mikejolley** [comment]
Depends on the product type - all product types go through that filter. https://github.com/woocommerce/woocommerce/blob/f434fc7d9a1f00363b07c60bde0aa3c0666e46ac/includes/class-wc-form-handler.php#L847

Calling `WC_Product_Variation` is a bad idea. Use wc_get_product function or you'll get issues.

**Comment by grosssmutttr** [comment]
I'm adding a variable product to the cart but if I echo the $variation_id it is empty so I think this should work as it did before upgrading woocommerce from 2.5 to 3.0?

**Comment by mikejolley** [comment]
It's your code at fault...

Looks at the add action - you're passing 3 args in, not 5.

**Comment by laychopy** [comment]
Could you post the solution please?
