### ISSUE TITLE
woocommerce_rest_authentication_error

### ISSUE THREAD

**Issue by lsantaniello** [woocommerce/woocommerce#15130]
Hi guys,
I always receive "woocommerce_rest_authentication_error" response on POST call (for example new consumer API). I'd like disable or change the configuration of OAuth. Is it possible?

I added into my .htaccess file this lines:

```
Header always add Access-Control-Allow-Origin "*"
Header always add Access-Control-Allow-Headers "origin, user-agent, accept, x-requested-with, content-type"
Header always add Access-Control-Allow-Methods "PUT, GET, POST, DELETE, OPTIONS"
 
# Added a rewrite to respond with a 200 success on every OPTIONS request
RewriteEngine On
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=200,L]

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /wordpress/
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /wordpress/index.php [L]
</IfModule>
# END WordPress
```
The problem is the same.

Could you please help me?

Thanks

**Comment by mikejolley** [comment]
I understand that this is an ongoing problem for you but Github is not a support forum, and questions like this whilst related to the API are not really questions we can answer. It's a server issue.

I'd expect the web host to be better equipped to help with this.

Remember you can also test the WORDPRESS Rest API which ours works on top of, and test using a desktop client. https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

You can also use the _method to simulate post if your server is not compatible https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_method-or-x-http-method-override-header
