### ISSUE TITLE
WC_Order->set_status does not update order status in DB.

### ISSUE THREAD

**Issue by reescott** [woocommerce/woocommerce#15137]
### EXPLANATION OF THE ISSUE

Using WooCommerce 3.0.6, when we create an new `WC_Order` object and try to use the `set_status` method, it does not actually change the value in the database. However, if I use the `update_status` method (which I could not find in WC documentation), it does change the value in the database.

### STEPS TO REPRODUCE THE ISSUE

Run the following code:
`
$orderid = <<Order with wc-processing status>>
$wc_order = new WC_Order( $orderid );
$result = $wc_order->set_status('completed'); 
var_dump($result); //returns array(2) { ["from"]=> string(10) "processing" ["to"]=> string(9) "completed" }
`
This will not change the database, however it does return the above array listed in the `set_status` method is listed in the documentation here:
https://docs.woocommerce.com/wc-apidocs/class-WC_Abstract_Order.html

**Comment by timondavis** [comment]
I think you may be missing a command, @reescott , which may get you across the finish line.  After updating the status on the object, try invoking the save() method on the order object.  `$wc_order->save();`  

Following your reproduce steps, I was able to commit the update to the database after adding that command.

**Comment by mikejolley** [comment]
All setters require a save once you're complete editing the object.
