### ISSUE TITLE
Email and online receipt not showing "purchase note"

### ISSUE THREAD

**Issue by andymax** [woocommerce/woocommerce#15134]
Purchace notes are not shown anymore in emals and on the online receipt.

I think it might only be a problem if the order total is 0,-

...or maybe the feature has been removed?

**Comment by timondavis** [comment]
If you're referring to the order notes that the customer enters on the checkout page, I can't seem to confirm this bug.  On the latest version, I am able to see the note in the following scenarios:
* When doing a typical checkout
* When applying a coupon for 100% discount

Can you provide more specifics that might help narrow down the error case?

**Comment by andymax** [comment]
It is the product note. You can set a note on the advanced tab on the product. And it shows up in the online receipt and the order completed under each product line.

The conditions are
- It's a virtual product
- It's a downloadable product
- It's a free product

I think it happens in this part in the email template:
do_action( 'woocommerce_email_order_details', $order, $sent_to_admin, $plain_text, $email );

And it calls this function:
woocommerce_email_order_details
https://docs.woocommerce.com/wc-apidocs/source-function-wc_get_email_order_items.html#2343-2376

And it calls this function:
        wc_get_template( $template, apply_filters( 'woocommerce_email_order_items_args', array(
            'order'               => $order,
            'items'               => $order->get_items(),
            'show_download_links' => $order->is_download_permitted() && ! $args['sent_to_admin'],
            'show_sku'            => $args['show_sku'],
            'show_purchase_note'  => $order->is_paid() && ! $args['sent_to_admin'],
            'show_image'          => $args['show_image'],
            'image_size'          => $args['image_size'],
            'plain_text'          => $args['plain_text'],
            'sent_to_admin'       => $args['sent_to_admin'],
        ) ) );

And I'm not sure what happens with this line:
'show_purchase_note'  => $order->is_paid() && ! $args['sent_to_admin']

Maybe is_paid() returns different values for 0,- orders in the new version?

Best/
Andy

**Comment by mikejolley** [comment]
The cost of the order should make no difference; it checks order status. If it's completed or processing, is_paid is true.

**Comment by andymax** [comment]
But still it does not show the notes :-/

**Comment by mikejolley** [comment]
`woocommerce_order_is_paid_statuses` is filterable, maybe your site changes it? I'll test a free order in a second.

**Comment by andymax** [comment]
It can be the Mystile theme making problems as well.

**Comment by mikejolley** [comment]
Confirmed this is working fine with free orders.

The only known issue is https://github.com/woocommerce/woocommerce/issues/15115 which I'm patching now.

**Comment by andymax** [comment]
Ahh ...it's the same :-) Perfect
