### ISSUE TITLE
Error Log reporting add_to_cart_fragment issue

### ISSUE THREAD

**Issue by conorot** [woocommerce/woocommerce#15136]
### EXPLANATION OF THE ISSUE

just updated to v3.0.7 and my Apache logs are showing the following error every 2 - 5 minutes:
`The The "add_to_cart_fragments" hook uses out of date data structures and function is deprecated since version 3.0.7. Replace with woocommerce_add_to_cart_fragments., referer: https://www.mydomain.com`

### STEPS TO REPRODUCE THE ISSUE

1. Update to v3.0.7
2. view error logs

I have a few other wooCommerce plugins installed including, WooCommerce Dynamic Pricing, WooCommerce Helper, WooCommerce Table Rate Shipping. All are on their latest versions.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.mysite.com
Site URL: https://www.mysite.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.25
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.40.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Ebor Framework: by Tom Rhodes – 1.1.16
amr shortcode any widget: by anmari – 3.4
Contact Form 7 Conditional Fields: by Jules Colle – 1.3.2
Contact Form DB: by Michael Simpson – 2.10.28
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Content by Country (from iControlWP): by iControlWP – 2.17.161112
Gift Card Price Calculator: by mysite – 0.1
Google Analytics Dashboard for WP: by Alin Marcu – 4.9.6.2
Anti-Malware Security and Brute-Force Firewall: by Eli Scheetz – 4.16.53
HubSpot Tracking Code for WordPress: by HubSpot – 1.1.2
mysite Hubspot Sales Messages: by mysite – 1.0
mysite Visitor Widget: by mysite – 0.1
Master Slider WP: by averta – 2.12.2
VarkTech Minimum Purchase for WooCommerce: by Vark – 1.09.8
Revolution Slider: by ThemePunch – 4.6.9
SKT Skill Bar: by SKT Themes – 1.4
SSH SFTP Updater Support: by TerraFrost – 0.7.1
Velvet Blues Update URLs: by VelvetBlues.com – 3.2.7
W3 Total Cache: by Frederick Townes – 0.9.5.4
WooCommerce Dynamic Pricing: by Lucas Stark – 3.0.7
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.3
WooCommerce: by Automattic – 3.0.7
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.7.1
WP Crontrol: by John Blackbourn & contributors – 1.5
WPFront Scroll Top: by Syam Mohan – 1.5
Google XML Sitemap Generator: by XmlSitemapGenerator.org – 1.3.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #768 - /shop
Cart: #769 - /cart
Checkout: #770 - /checkout
My account: #771 - /my-account

### Theme ###

Name: mysite
Version: 1.0
Author URL: http://www.mysite.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: mysite/woocommerce/content-product.php
mysite/woocommerce/global/wrapper-end.php
mysite/woocommerce/global/wrapper-start.php
mysite/woocommerce/loop/add-to-cart.php
mysite/woocommerce/loop/no-products-found.php
mysite/woocommerce/loop/pagination.php
mysite/woocommerce/notices/error.php
mysite/woocommerce/notices/notice.php
mysite/woocommerce/notices/success.php
mysite/product-searchform.php
mysite/woocommerce/single-product/product-image.php
mysite/woocommerce/single-product/product-thumbnails.php

`
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Deprecation-in-core

The notice is slightly misleading in that it was deprecated in 3.0, not 3.0.7, but the issue is with another plugin which has not been updated for 3.0 yet.
