### ISSUE TITLE
UX: No way to clear filters while keeping search query

### ISSUE THREAD

**Issue by lawkwok** [woocommerce/woocommerce#15133]
### EXPLANATION OF THE ISSUE

Suppose you are viewing all your Completed orders (https://www.domain.com/wp-admin/edit.php?post_status=wc-completed&post_type=shop_order), but you want to search for an order with another status.

You would probably go to the search box and type in an order ID (or another string).

However, you will get no results since it only searches among Completed orders. It is not immediately obvious what's wrong other than a slightly bolded label.

<img width="1000" alt="screen shot 2017-05-17 at 1 55 01 pm" src="https://cloud.githubusercontent.com/assets/11021583/26175723/79808c5c-3b08-11e7-8e05-1ad6ebf12d2f.png">

Furthermore, you aren't able to keep the search query and just clear the Completed filter (by clicking an X for example).

Instead it becomes a multi-step process. You must:

1. Focus on the search box.
2. Copy the search string.
3. Click on All orders.
4. Paste the search string.
5. Press Search Orders.

This issue is present on all screens with a search box filterable options.

### STEPS TO REPRODUCE THE ISSUE

1. Select the Completed status on the Orders screen.
2. Now search for an order ID with a status other than Complete.
3. The results will be blank.

### SYSTEM STATUS

WooCommerce 3.0.6

**Comment by mikejolley** [comment]
Whilst I agree its not great, this is WordPress UI - look at posts to see the exact same thing. It's not something we can change.

We're working on a new interface for Calypso where issues like this will be a thing of the past as the entire UX is being redesigned :)
