### ISSUE TITLE
wc.GetOrder.GetAll

### ISSUE THREAD

**Issue by markldavison** [woocommerce/woocommerce#15131]
Trying to migrate to WooCommerce.NET 0.7.0.

When I call:

Dim orderslist as List(of [Order]) = Await wc.Order.GetAll(dict)

I get the response:

"There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v2.Order, WooCommerceNET, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null]]. End element 'value' from namespace '' expected. Found element 'item' from namespace ''."

I think someone else reported the same issue with wc.Product.GetAll but I cannot find that issue now.

**Comment by markldavison** [comment]
The same problem with Order.Get(x) which gives the message:

"There was an error deserializing the object of type WooCommerceNET.WooCommerce.v2.Order. End element 'value' from namespace '' expected. Found element 'refundable_txns' from namespace ''."

**Comment by mikejolley** [comment]
Shouldn't this be posted to https://github.com/XiaoFaye/WooCommerce.NET? We don't author this lib and I have no idea about .net :)
