### ISSUE TITLE
Drag and drop ordering of attribute terms not functioning properly

### ISSUE THREAD

**Issue by jkhopkins** [woocommerce/woocommerce#15140]
### EXPLANATION OF THE ISSUE

Recently I went to change a few attribute terms for an attribute which is set to 'Custom ordering' and noticed some of the terms would not move.  When trying to drag them and drop them in another place, they just zip back to their original place and refuse to move.  This doesn't happen for all the terms, only a few.
After scratching around for a while, I couldn't find anything that would cause this.  I tried going into System Status and doing the usual clear transients, clear expired transients, delete orphaned variations and recount terms, but nothing helped.
So, finally I tried looking up the database table 'wp_termmeta' and specifically the 'meta_value' column and noticed that although the numbers are sequential, some numbers are missing.
![table](https://cloud.githubusercontent.com/assets/27403815/26191581/fda1083a-3be0-11e7-9113-0f754e8ac5da.png)
From the table you can see the meta values go from 1 to 102, but there are only 89 rows, which means there are 13 values missing.  Is this normal? Or should the meta values be fully sequential? If so, could this be causing the problem?
I noticed also the recent change:
https://github.com/woocommerce/woocommerce/commit/dbda57780f086783365560c0d70c475e1253bdd2
Could this have something to do with it?

### STEPS TO REPRODUCE THE ISSUE

I tried changing to twenty-seventeen theme, and disabling all plugins, but no change.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://dev.jkhopkins.com.au
Site URL: http://dev.jkhopkins.com.au
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 100 MB
PHP Time Limit: 900
PHP Max Input Vars: 5000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (14) ###

Redux Framework: by Team Redux – 3.6.5
XTEMOS Post Types plugin: by  – 1.1
CMB2: by WebDevStudios – 2.2.4
Contact Form 7: by Takayuki Miyoshi – 4.7
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Table Rate Shipping: by Amit Sidhpura – 1.1.0
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.4.1
SMTP Mailer: by naa986 – 1.0.3
Test Plugin: by  –
WooCommerce: by Automattic – 3.0.7
YITH WooCommerce Compare: by YITHEMES – 2.2.0
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Basel
Version: 3.2.0
Author URL: http://themeforest.net/user/xtemos
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: basel/woocommerce/archive-product.php
basel/woocommerce/cart/cart.php
basel/woocommerce/cart/cross-sells.php
basel/woocommerce/cart/mini-cart.php
basel/woocommerce/checkout/form-checkout.php
basel/woocommerce/content-product.php
basel/woocommerce/content-product_cat.php
basel/woocommerce/content-single-product.php
basel/woocommerce/global/breadcrumb.php
basel/woocommerce/global/quantity-input.php
basel/woocommerce/loop/loop-end.php
basel/woocommerce/loop/loop-start.php
basel/woocommerce/loop/no-products-found.php
basel/woocommerce/loop/orderby.php
basel/woocommerce/loop/pagination.php
basel/woocommerce/loop/sale-flash.php
basel/woocommerce/myaccount/form-login.php
basel/woocommerce/product-searchform.php
basel/woocommerce/single-product/add-to-cart/variable.php
basel/woocommerce/single-product/meta.php
basel/woocommerce/single-product/product-image.php
basel/woocommerce/single-product/product-thumbnails.php
basel/woocommerce/single-product/related.php
basel/woocommerce/single-product/tabs/tabs.php
basel/woocommerce/single-product/title.php
basel/woocommerce/single-product/up-sells.php
basel/woocommerce/single-product.php

`
</details>

**Comment by jkhopkins** [comment]
Just to reiterate, I've only noticed this issue recently, never had the problem before, so I'm thinking it might be due to a recent Woocommerce update.

**Comment by jkhopkins** [comment]
As an example, the attribute term which represents meta_value=29, I can drag and drop that one anywhere upwards in the list, but it won't let me move it downwards,  Now if you see the table the number before 29 is 28, 27, 26, 25 etc , but the number **after** 29 is 31.  So, because the value 30 is missing, it won't let me move it down in the list because the sequence is broken.  And same applies for all terms which are next to a missing meta_value, they can't be moved.

**Comment by gitbmd** [comment]
I think it´s the same Issue as: "Variation menu order error", reference: #15081

**Comment by claudiosanches** [comment]
> I noticed also the recent change: dbda577

Recent change is only for when picking the attributes for the product, does not have anything related to attribute terms ordering.

**Comment by claudiosanches** [comment]
@jkhopkins I'm not able to reproduce the error.

> From the table you can see the meta values go from 1 to 102, but there are only 89 rows, which means there are 13 values missing. Is this normal? Or should the meta values be fully sequential

This is normal, since does not try to reorder after delete any term, or when is adding terms all have order as `0`.

I tried to reproduce what you say in https://github.com/woocommerce/woocommerce/issues/15140#issuecomment-302334275 but without any success.
There is more steps to reproduce it?

**Comment by jkhopkins** [comment]
I seem to have fixed the problem.

Steps to find the problem:
**1.** I noticed the terms which were not movable (i.e. unable to re-order) were **also not able to be edited**. When I tried to edit the term, I got the error "**Parent term does not exist**".  This is strange, as there should not be any parent terms.
**2.**  Ran another SQL query to check parent terms:
![broken](https://cloud.githubusercontent.com/assets/27403815/26833418/efcc32b0-4b04-11e7-85f5-b8ea07785519.png)
3. Weird, some parent terms set to '0'  and a lot with non-zero values.  Then I realised the terms with parent set to '0' were working correctly (i.e. can edit, and re-order them).  The terms with parent set to non-zero were the ones not working.
4. Ran a SQL command to set all parent terms to '0':
**UPDATE `wp_term_taxonomy` SET `parent` = '0' WHERE `wp_term_taxonomy`.`taxonomy` = 'pa_colour'**
5. In WP admin, go into attribute 'Colour' and move a few terms in the list to force WP to update the order list.  All terms are now moveable and editable as per normal.
6. Run one more SQL query to check the list has been re-ordered correctly:
![fixed](https://cloud.githubusercontent.com/assets/27403815/26833776/fd58a3fe-4b05-11e7-9c48-12812bf5d787.png)
7. Confirmed, the list is now ordered perfectly sequential from 1-89 and all terms are working correctly.

So the cause of this issue was a lot of the attribute terms had non-existent parent IDs assigned to them.  The fix was to set all parent IDs to zero, but I still have no idea how this issue happened in the first place.

**Comment by claudiosanches** [comment]
Now makes sense, but maybe this is happening because we used to allow parent terms, but removed since we don't use in any place in core.
But sounds like a edge case, I don't think we should try do something in core to fix or prevent it since we don't allow parents anymore, still good to know about this potential problem if we cross again with something related.
Thank you very much for your report and help to understand it.

**Comment by socca1157** [comment]
Still Broken. Custom ordering via Woocommerce Settings does absolutely nothing. Neither does specifying a Menu Order ID via Products.
