### ISSUE TITLE
Unable to add/edit attributes and variations after updating

### ISSUE THREAD

**Issue by fiefaifoefum** [woocommerce/woocommerce#15141]
### EXPLANATION OF THE ISSUE

Updated to WC 3.0.7, attributes and variations are not functioning when adding a variable product. For new products, attributes can't be loaded. For existing products, variations can't be edited. Theme is up-to-date. 

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: http://www.thekembara.com
Site URL: http://www.thekembara.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_nb5a5r8tcn_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (15) ###

Contact Form 7: by Takayuki Miyoshi – 4.7
Easy WP SMTP: by wpecommerce – 1.2.5
Envato WordPress Toolkit: by Envato – 1.7.3
Handmade Framework: by g5plus – 1.0
Imagify: by WP Media – 1.6.4
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.2.6
W3 Total Cache: by Frederick Townes – 0.9.5.4
WooCommerce: by Automattic – 3.0.7
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

YITH Essential Kit for WooCommerce #1: by YIThemes – 1.4.6
YITH WooCommerce PDF Invoice and Shipping List: by YITHEMES – 1.1.18

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: MYR (RM)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2084 - /shop/
Cart: #589 - /cart-2/
Checkout: #1573 - /checkout/
My account: #1574 - /my-account/

### Theme ###

Name: HandMade Child Theme
Version: 1.0
Author URL: http://g5plus.net
Child Theme: ✔
Parent Theme Name: HandMade
Parent Theme Version: 3.2
Parent Theme Author URL: http://g5plus.net/
WooCommerce Support: ✔

### Templates ###

Overrides: handmade/woocommerce/archive-product.php
handmade/woocommerce/cart/cart-shipping.php
handmade/woocommerce/cart/cart-totals.php
handmade/woocommerce/cart/cart.php
handmade/woocommerce/cart/cross-sells.php
handmade/woocommerce/cart/mini-cart.php
handmade/woocommerce/cart/shipping-calculator.php
handmade/woocommerce/checkout/form-coupon.php
handmade/woocommerce/checkout/form-login.php
handmade/woocommerce/checkout/payment-method.php
handmade/woocommerce/content-product.php
handmade/woocommerce/content-product_cat.php
handmade/woocommerce/content-single-product.php
handmade-child/woocommerce/emails/admin-cancelled-order.php
handmade-child/woocommerce/emails/admin-failed-order.php
handmade-child/woocommerce/emails/admin-new-order.php
handmade-child/woocommerce/emails/customer-completed-order.php
handmade-child/woocommerce/emails/customer-invoice.php
handmade-child/woocommerce/emails/customer-new-account.php
handmade-child/woocommerce/emails/customer-note.php
handmade-child/woocommerce/emails/customer-on-hold-order.php
handmade-child/woocommerce/emails/customer-refunded-order.php
handmade-child/woocommerce/emails/customer-reset-password.php
handmade/woocommerce/global/quantity-input.php
handmade/woocommerce/loop/add-to-cart.php
handmade/woocommerce/loop/loop-end.php
handmade/woocommerce/loop/loop-start.php
handmade/woocommerce/loop/pagination.php
handmade/woocommerce/loop/sale-flash.php
handmade/woocommerce/product-searchform.php
handmade/woocommerce/single-product/meta.php
handmade/woocommerce/single-product/product-image.php
handmade/woocommerce/single-product/rating.php
handmade/woocommerce/single-product/related.php
handmade/woocommerce/single-product/sale-flash.php
handmade/woocommerce/single-product/short-description.php
handmade/woocommerce/single-product/title.php
handmade/woocommerce/single-product/up-sells.php
handmade/woocommerce/single-product.php

```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
See my answer here #14972 (comment) - this is a plugin conflict.
