### ISSUE TITLE
Rounding issues

### ISSUE THREAD

**Issue by Matekk** [woocommerce/woocommerce#15149]
Hi,
I'm experiencing rounding issues due to float point numbers used in WC. 
The specific order this happened in had a 27% discount and a 25% tax rate applied to it. Following are screenshots of the issue and the discrepancy in backend and frontend:

BACKEND:
![woocommerce_rounding_issue_1_backend](https://cloud.githubusercontent.com/assets/7734648/26203846/1cb8f3da-3bdd-11e7-971d-a21a16534e48.jpg)

FRONTEND:
![woocommerce_rounding_issue_1_frontend](https://cloud.githubusercontent.com/assets/7734648/26203854/20a23196-3bdd-11e7-8ca9-d54c3ec83acd.jpg)

To simulate and try to reproduce the issue - create 3 products in your shop:
- product no.1 - price 113.38 € (ex. tax) - order x1
- product no.2 - price 14.02 € (ex. tax)  - order x3
- product no.3 - price 14.02 € (ex. tax) - order x1 (or just order product no.2 x4)

Create and enter a coupon for a product % discount -27%

Create and apply tax - value of 25%

This should yield the same results, although I'm certain there is an infinite number ways to reproduce this since I believe it is the result of relying on floating-point arithmetic.
Is there any specific reason why this is handled in such a way in WC? 
Why not just use integers or any other suggested system besides float?

Or am I missing something and this is a result of poor configuration on my part? 

Please help either way,
Thank you!

P.S.: my template overrides are outdated, yes, but that does not affect this issue in any way, I've just upgraded to WC 3, moments ago since I hoped it would fix this issue. 

P.P.S.: tried it without plugins and with twenty seventeen, same results.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://zrinski.eu
Site URL: http://zrinski.eu
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 5 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wpqo_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (28) ###

Query Monitor: by John Blackbourn – 2.13.4
Advanced Custom Fields Multilingual: by OnTheGo Systems – 0.4
Admin Language Per User: by unclego – 1.0.9
Advanced Custom Fields PRO: by Elliot Condon – 5.5.9
Enhanced Media Library PRO: by wpUXsolutions – 2.4.1
Imsanity: by Shane Bishop – 2.3.9
New User Approve: by Josh Harrison – 1.7.4
Orbis WP Assets: by Orbis.hr – 1.0.0
Ordered Variable Product Report: by CedCommerce – 1.0.5
Parent Category Toggler: by Ben Lobaugh – 1.3.3
WPML Multilingual CMS: by OnTheGoSystems – 3.6.3
SVG Support: by Benbodhi – 2.3.8
User Role Editor: by Vladimir Garagulya – 4.32.3
WC Coupons by Country: by AxisThemes – 1.0.0
WooCommerce Extended Coupon Features: by Soft79 – 2.4.3
WooCommerce Multilingual: by OnTheGoSystems – 4.1.4
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 1.4.7
WooCommerce: by Automattic – 3.0.7
WP Better Emails: by Nicolas Lemoine – 0.3
WP Mail Logging: by Christian Zöller – 1.8.0
WP Super Cache: by Automattic – 1.4.9
WPML All Import: by OnTheGoSystems – 2.0.3
WPML CMS Nav: by OnTheGoSystems – 1.4.19
WPML Media: by OnTheGoSystems – 2.1.24
WPML Sticky Links: by OnTheGoSystems – 1.4.0
WPML String Translation: by OnTheGoSystems – 2.5.2
WPML Translation Management: by OnTheGoSystems – 2.2.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /account/

### Theme ###

Name: Zrinski
Version: 1.0
Author URL: http://www.orbis.hr
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: zrinski/woocommerce/archive-product.php
zrinski/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
zrinski/woocommerce/content-product_cat.php
zrinski/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
zrinski/woocommerce/emails/customer-on-hold-order.php
zrinski/woocommerce/global/quantity-input.php
zrinski/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0
zrinski/woocommerce/myaccount/my-account.php
zrinski/woocommerce/myaccount/navigation.php
zrinski/woocommerce/single-product/add-to-cart/external.php
zrinski/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.7
zrinski/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
zrinski/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
zrinski/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
zrinski/woocommerce/single-product/add-to-cart/variation.php
zrinski/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
zrinski/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update

</details>

**Comment by mikejolley** [comment]
This is nothing to do with floats; its the discounts. Discounts are split between items, and stored > 2 dp. You're adding the rounded for display values, but if you added the actual 4dp values (visible on edit) the sum would be correct.

See https://github.com/woocommerce/woocommerce/pull/14475

Unsure if this will be merged yet because it can affect how much discount is given,  but that is specifically for this issue.

**Comment by Matekk** [comment]
Thanks for the quick reply, I've applied the patch, unless I'm doing something wrong I don't see any change on recalculate.

**Comment by mikejolley** [comment]
It will take a new order.
