### ISSUE TITLE
Shipping tax not updating in Woocommerce report

### ISSUE THREAD

**Issue by ShabbyAbby** [woocommerce/woocommerce#15146]
### EXPLANATION OF THE ISSUE

When I started my shop, I set tax for shipping the wrong way. A lot of orders got shipping without any shipping taxes. After I updated shipping tax (25%), everything started to work well. The problem is that I'm trying to update shipping on old orders. I have tried to update it in back-end or via database, but numbers in tax report won't update

### STEPS TO REPRODUCE THE ISSUE

1. Add order with without shipping tax.
2. Update it in back-end or database.
3. Report numbers won't update.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://gronnmat.no
Site URL: http://gronnmat.no
WC Version: 2.6.8
Log Directory Writable: ✔
WP Version: 4.6.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nb_NO

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 5.6.30-10+deb.sury.org~xenial+2
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Fjernt innlegg: ✔
Fjernt 'Get': ✔

### Database ###

WC Database Version: 2.6.8
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (27) ###

Gravity Forms: av rocketgenius – 2.1.1
Advanced Custom Fields: Image Crop Add-on: av Anders Thorborg – 1.4.9
Admin Columns Pro: av AdminColumns.com – 3.8.9
Admin Menu Editor Pro: av Janis Elsts – 2.4.2
Advanced Custom Fields Pro: av Elliot Condon – 5.5.0
Backup: av BackupGuard – 1.1.39
Custom Post Type UI: av WebDevStudios – 1.4.3
English WordPress Admin: av khromov – 1.5.1
Gcode Custom Dashboard: av M.Diaz – 1.0
Loco Translate: av Tim Whitlock – 2.0.12
07 Change delivery address: av 07 Interaktiv – 1.0
07 Change subscription end date: av 07 Interaktiv – 1.0
07 Delivery days: av 07 Interaktiv – 1.0
07 Routific export: av 07 Interaktiv – 1.0
TinyMCE Advanced: av Andrew Ozz – 4.4.1
User Role Editor: av Vladimir Garagulya – 4.29
Brukerbytting: av John Blackbourn – 1.0.9
Woo Store Vacation: av Mahdi Yazdani – 1.0.3
WooCommerce Print Invoice & Delivery Note: av Triggvy Gunderson – 4.1.5
WooCommerce Stripe Gateway: av Automattic – 3.0.6
WooCommerce Measurement Price Calculator: av WooThemes / SkyVerge – 3.10.1 – 3.11.4 er tilgjengelig
WooCommerce Subscribe All the Things: av Prospress Inc. – 1.1.0
WooCommerce Subscriptions: av Prospress Inc. – 2.2.5
WooCommerce: av Woothemes – 2.6.8
WooCommerce Helper: av WooCommerce – 1.7.2
Nested Pages: av Kyle Phillips – 1.5.4
WP Sync DB: av Sean Lang – 1.5

### Settings ###

Force SSL: ✔
Currency: NOK (kr)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Butikkbase: #97 - /nettbutikk/
Handlekurv: #330 - /handlekurv/
Til kassen: #331 - /nettbutikk/kasse/
Min konto: #332 - /nettbutikk/min-konto/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: SUAVE
Version: 2.0
Author URL: https://gevir.no
Child Theme: ❌ – Hvis du endrer WooCommerce eller et foreldertema du selv ikke bygget
anbefaler vi å bruke et dattertema. Se: Hvordan lage et dattertema

WooCommerce Support: ✔

### Templates ###

Overrides: SUAVE/woocommerce/archive-product.php
SUAVE/woocommerce/auth/footer.php
SUAVE/woocommerce/auth/form-grant-access.php
SUAVE/woocommerce/auth/form-login.php
SUAVE/woocommerce/auth/header.php
SUAVE/woocommerce/cart/cart-empty.php
SUAVE/woocommerce/cart/cart-item-data.php
SUAVE/woocommerce/cart/cart-shipping.php
SUAVE/woocommerce/cart/cart-totals.php
SUAVE/woocommerce/cart/cart.php
SUAVE/woocommerce/cart/cross-sells.php
SUAVE/woocommerce/cart/mini-cart.php
SUAVE/woocommerce/cart/proceed-to-checkout-button.php
SUAVE/woocommerce/cart/shipping-calculator.php
SUAVE/woocommerce/checkout/cart-errors.php
SUAVE/woocommerce/checkout/form-billing.php
SUAVE/woocommerce/checkout/form-checkout.php
SUAVE/woocommerce/checkout/form-coupon.php
SUAVE/woocommerce/checkout/form-login.php
SUAVE/woocommerce/checkout/form-pay.php
SUAVE/woocommerce/checkout/form-shipping.php
SUAVE/woocommerce/checkout/payment-method.php
SUAVE/woocommerce/checkout/payment.php
SUAVE/woocommerce/checkout/review-order.php
SUAVE/woocommerce/checkout/terms.php
SUAVE/woocommerce/checkout/thankyou.php
SUAVE/woocommerce/content-product.php versjon 2.5.0 er utdatert. Kjerneversjonen er 2.6.1
SUAVE/woocommerce/content-product_cat.php versjon 2.5.2 er utdatert. Kjerneversjonen er 2.6.1
SUAVE/woocommerce/content-single-product.php
SUAVE/woocommerce/content-widget-product.php
SUAVE/woocommerce/emails/admin-cancelled-order.php
SUAVE/woocommerce/emails/admin-failed-order.php
SUAVE/woocommerce/emails/admin-new-order.php
SUAVE/woocommerce/emails/customer-completed-order.php
SUAVE/woocommerce/emails/customer-invoice.php
SUAVE/woocommerce/emails/customer-new-account.php
SUAVE/woocommerce/emails/customer-note.php
SUAVE/woocommerce/emails/customer-on-hold-order.php
SUAVE/woocommerce/emails/customer-processing-order.php
SUAVE/woocommerce/emails/customer-refunded-order.php
SUAVE/woocommerce/emails/customer-reset-password.php
SUAVE/woocommerce/emails/email-addresses.php
SUAVE/woocommerce/emails/email-customer-details.php
SUAVE/woocommerce/emails/email-footer.php
SUAVE/woocommerce/emails/email-header.php
SUAVE/woocommerce/emails/email-order-details.php
SUAVE/woocommerce/emails/email-order-items.php
SUAVE/woocommerce/emails/email-styles.php
SUAVE/woocommerce/emails/plain/admin-cancelled-order.php
SUAVE/woocommerce/emails/plain/admin-failed-order.php
SUAVE/woocommerce/emails/plain/admin-new-order.php
SUAVE/woocommerce/emails/plain/customer-completed-order.php
SUAVE/woocommerce/emails/plain/customer-invoice.php
SUAVE/woocommerce/emails/plain/customer-new-account.php
SUAVE/woocommerce/emails/plain/customer-note.php
SUAVE/woocommerce/emails/plain/customer-processing-order.php
SUAVE/woocommerce/emails/plain/customer-refunded-order.php
SUAVE/woocommerce/emails/plain/customer-reset-password.php
SUAVE/woocommerce/emails/plain/email-addresses.php
SUAVE/woocommerce/emails/plain/email-customer-details.php
SUAVE/woocommerce/emails/plain/email-order-details.php
SUAVE/woocommerce/emails/plain/email-order-items.php
SUAVE/woocommerce/global/breadcrumb.php
SUAVE/woocommerce/global/form-login.php
SUAVE/woocommerce/global/quantity-input.php
SUAVE/woocommerce/global/sidebar.php
SUAVE/woocommerce/global/wrapper-end.php
SUAVE/woocommerce/global/wrapper-start.php
SUAVE/woocommerce/loop/add-to-cart.php
SUAVE/woocommerce/loop/loop-end.php
SUAVE/woocommerce/loop/loop-start.php
SUAVE/woocommerce/loop/no-products-found.php
SUAVE/woocommerce/loop/orderby.php
SUAVE/woocommerce/loop/pagination.php
SUAVE/woocommerce/loop/price.php
SUAVE/woocommerce/loop/rating.php
SUAVE/woocommerce/loop/result-count.php
SUAVE/woocommerce/loop/sale-flash.php
SUAVE/woocommerce/myaccount/form-add-payment-method.php versjon 2.1 er utdatert. Kjerneversjonen er 2.6.0
SUAVE/woocommerce/myaccount/form-edit-account.php versjon 2.5.1 er utdatert. Kjerneversjonen er 2.6.0
SUAVE/woocommerce/myaccount/form-edit-address.php versjon 2.1.0 er utdatert. Kjerneversjonen er 2.6.0
SUAVE/woocommerce/myaccount/form-login.php versjon 2.2.6 er utdatert. Kjerneversjonen er 2.6.0
SUAVE/woocommerce/myaccount/form-lost-password.php versjon 2.3.0 er utdatert. Kjerneversjonen er 2.6.0
SUAVE/woocommerce/myaccount/my-account.php versjon 2.0.0 er utdatert. Kjerneversjonen er 2.6.0
SUAVE/woocommerce/myaccount/my-address.php versjon 2.2.0 er utdatert. Kjerneversjonen er 2.6.0
SUAVE/woocommerce/myaccount/my-downloads.php
SUAVE/woocommerce/myaccount/my-orders.php
SUAVE/woocommerce/myaccount/view-order.php versjon 2.2.0 er utdatert. Kjerneversjonen er 2.6.0
SUAVE/woocommerce/notices/error.php
SUAVE/woocommerce/notices/notice.php
SUAVE/woocommerce/notices/success.php
SUAVE/woocommerce/order/form-tracking.php
SUAVE/woocommerce/order/order-again.php
SUAVE/woocommerce/order/order-details-customer.php
SUAVE/woocommerce/order/order-details-item.php
SUAVE/woocommerce/order/order-details.php versjon 2.5.0 er utdatert. Kjerneversjonen er 2.6.0
SUAVE/woocommerce/order/tracking.php
SUAVE/woocommerce/product-searchform.php
SUAVE/woocommerce/single-product/add-to-cart/external.php
SUAVE/woocommerce/single-product/add-to-cart/grouped.php
SUAVE/woocommerce/single-product/add-to-cart/simple.php
SUAVE/woocommerce/single-product/add-to-cart/variable.php
SUAVE/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
SUAVE/woocommerce/single-product/add-to-cart/variation.php
SUAVE/woocommerce/single-product/meta.php
SUAVE/woocommerce/single-product/price.php
SUAVE/woocommerce/single-product/product-attributes.php
SUAVE/woocommerce/single-product/product-image.php versjon 2.0.14 er utdatert. Kjerneversjonen er 2.6.3
SUAVE/woocommerce/single-product/product-thumbnails.php versjon 2.3.0 er utdatert. Kjerneversjonen er 2.6.3
SUAVE/woocommerce/single-product/rating.php
SUAVE/woocommerce/single-product/related.php
SUAVE/woocommerce/single-product/review.php versjon 2.5.0 er utdatert. Kjerneversjonen er 2.6.0
SUAVE/woocommerce/single-product/sale-flash.php
SUAVE/woocommerce/single-product/share.php
SUAVE/woocommerce/single-product/short-description.php
SUAVE/woocommerce/single-product/tabs/additional-information.php
SUAVE/woocommerce/single-product/tabs/description.php
SUAVE/woocommerce/single-product/tabs/tabs.php
SUAVE/woocommerce/single-product/title.php
SUAVE/woocommerce/single-product/up-sells.php
SUAVE/woocommerce/single-product-reviews.php
SUAVE/woocommerce/single-product.php
SUAVE/woocommerce/taxonomy-product_cat.php
SUAVE/woocommerce/taxonomy-product_tag.php

: Lær å oppdatere utdaterte maler

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
</details>

**Comment by mikejolley** [comment]
Reports are cached; they will not update until an order is saved or transients are cleared in system status.
