### ISSUE TITLE
new WC_Order(5793) causes HTTP 500 Error

### ISSUE THREAD

**Issue by FlorianB385** [woocommerce/woocommerce#15154]
### EXPLANATION OF THE ISSUE

Hi,
i’ve got an error, if i call “new WC_Order($order->ID)”; I’ve deactivate all other Plugins, switch to Twenty Seventeen Theme, but the error occured.

### STEPS TO REPRODUCE THE ISSUE

Call http://aiya.herrlich-media.de/?test=1 
The function behind this, is
`
if(isset($_GET['test']) && $_GET['test'] == 1){
$order2 = new WC_Order(5793); 
error_log( print_r( $order2, true ) ); 
}
`
### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://aiya.herrlich-media.de
Site URL: http://aiya.herrlich-media.de
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 300 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.45-0+deb7u8 - Wir empfehlen mindestens die PHP Version 5.6. Siehe: So aktualisierst Du Deine PHP-Version
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - Wir empfehlen mindestens MySQL-Version 5.6. Siehe: WordPress-Anforderungen
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ❌Fehlermeldungen sollten Besuchern nicht angezeigt werden.

### Active Plugins (1) ###

WooCommerce: von Automattic – 3.0.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #37 - /shop/
Warenkorb: #38 - /warenkorb/
Kasse: #39 - /kasse/
Mein Konto: #40 - /mein-konto/

### Theme ###

Name: Twenty Seventeen
Version: 1.2
Author URL: https://de.wordpress.org/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
You need to use `wc_get_order` because doing it direct can throw an exception if the order ID is invalid. This is not a bug.
