### ISSUE TITLE
Possible need for improvement with stock management

### ISSUE THREAD

**Issue by johanmoberg** [woocommerce/woocommerce#15157]
Running WP 4.7.5 and WC 3.0.7.

I have a client who called me about a problem he had with stock management. He had a variable product with som variants and had "accidentally" turned on manage stock in the inventory tab and saved the product.

As a result, and as expected, no one could order the product as the stock quantity was set to 0. No problem he thought, I just turn the manage stock of. But the problem remained and hence the phone call.

At first, I was also a little confused to why but quickly saw that the stock status for each variant was set to out of stock. After some investigation I explained to him that when you turn on manage stock for a variable product and and save the product with the stock quantity set to 0. The stock status for each variant will change to out of stock but if you turn the manage stock off and save, the status won’t change back to in stock.

In any case, he thought it was a bit confusing and I kind of agree. It may not be so common for anyone to turn on manage stock if they don’t use the feature, but if they do and then turn it off. Is it not more logical that the stock status is changed back to in stock instead of having to change it for each variant?

Thanks

**Comment by mikejolley** [comment]
Logical maybe but there is no way to know if the stock statuses were manually changed on purpose, vs a change in the parent status so it's not really a good change to make IMO.

What we do have coming in 3.1 is a bulk edit for stock status so you can at least correct it with a few clicks.

FWIW the variations system is due a refactor and has a few issues open to redesign it. Things like this will be addressed.

Thanks
