### ISSUE TITLE
Duplicated Variable Products show up incorrectly in cart

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce#15158]
### EXPLANATION OF THE ISSUE

When placing a variable product in the cart, the product title is correct on the product page and in the dashboard title and slug, but (copy) is added to the end of the product name when viewing the shopping cart page

Reported 569370-zd-woothemes 

Issue remained with only WooCommerce and Storefront, though at first inconsistent between products. Re-tested on my staging site (WooCommerce 3.0.7) and happened right away

### STEPS TO REPRODUCE THE ISSUE

1. Create a variable product and save
2. From product list, use duplicate function
3. Edit product title, permalink and details and save
4. Product page title and URL appear as expected
5. Add item to shopping cart, on page notice appears as expected
6. Go to cart page and **(copy)** appears at the end of the product name

![](https://cloudup.com/ca7CvA9zvoP+)Image Link: https://cloudup.com/ca7CvA9zvoP

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: https://melinda-woo.mystagingwebsite.com
Site URL: https://melinda-woo.mystagingwebsite.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.19
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.53.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
mix-and-match (mix-and-match)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #135 - /
Basket: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
@melindahelt Ignoring the duplication a moment, the variation titles in your example for the ORIGINAL product are in the format "Variation for X" which is the legacy format. How were these products created?

With the old format, the title substitution code ran after saving the duplicated product will not work because the old title of the parent product is not part of the variation product titles.

**Comment by melindahelt** [comment]
@mikejolley The product in the first test was created just for this, right before I made the screencast. I created a new product from scratch just now, following the steps outlined at https://docs.woocommerce.com/document/variable-product (using custom attributes specific to the product), and then copying the product as shown above and the (copy) still appeared in the shopping cart.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/15173 resolves this
