### ISSUE TITLE
Getting `Invalid Order` upon clicking `Customer payment page →` link on Edit order page

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce#15168]
### EXPLANATION OF THE ISSUE

Getting `Invalid Order` message upon clicking `Customer payment page →` link on Edit order page after manually creating the order from backend.

### STEPS TO REPRODUCE THE ISSUE

1. Goto **WooCommerce >> Orders >> Add Order**
2. Select a customer and add products to the order.
3. Click the `Create` button on top right as this will create a new manual order in `Pending Payment` status.
4. Now click on the `Customer payment page →` link which will give the `Invalid Order` error

### Demo:

![](http://cld.wthms.co/yENBq+)

### Ticket:
zd-woothemes-573842

###Cc
@mattyza @mikejolley

**Comment by mikejolley** [comment]
If an order is assigned to a user, the form will not show unless logged in as said user.

This PR for 3.1 adds a login form and changes the error messages to make this clearer: https://github.com/woocommerce/woocommerce/pull/15076

I've seen admin users argue that they use this to take customer payments, but this is not a supported use case and can have severe limitations e.g. card tokens being stored to the admin account, and customer address details being stored to the admin user object. In these cases, a user switching plugin can work instead.
