### ISSUE TITLE
WooCommerce Price Filter Widget doesn't working fine with variable products

### ISSUE THREAD

**Issue by andreagrillo** [woocommerce/woocommerce#15169]
### EXPLANATION OF THE ISSUE

If a customer of mine visit an attribute page, 
e.g.: http://support.dev/shop/?min_price=10&max_price=15&filter_color=blue 
and I try to filter by price From 10$ to 15$, this is the results page: 

https://www.dropbox.com/s/6kk6l2ce21ly45z/Selection_596.png?dl=0

If I visit the single product page of the highlighted products you can see that the blue variation of it, is our of range 10$-15$ because the "blue" products cost 18$.

Why this products appears after a filter was applied  ? 

https://www.dropbox.com/s/k4118onm0zpbs5e/Selection_597.png?dl=0

### STEPS TO REPRODUCE THE ISSUE

1. You simply need to create a variable product with 3 variation, 2 of this cost a price in the range 10$ -15$, one of this have a price greather then 15$. 

2. Visit a page like this http://www.mysite.com/shop/?filter_color=blue

3. Add the WooCommerce price filter in shop sidebar and try to filter for range 10$ - 15$

### SYSTEM STATUS
`
### WordPress Environment ###

Home URL: http://localhost/yith
Site URL: http://localhost/yith
WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3-RC1-40141
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.5.30
PHP Version: ❌ 5.5.30 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.42.1
OpenSSL/1.0.2d

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 2.13.2
AG-ALR WP Mail Debug: by Andrea Grillo - Antonio La Rocca – 1.4
User Switching: by John Blackbourn – 1.0.9
WooCommerce: by Automattic – 3.0.0-rc.1
WordPress Importer: by wordpressdotorg – 0.6.3
YITH WooCommerce Ajax Product Filter Premium: by YITHEMES – 3.3.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
This isn't something that can be fixed today as it would require heavier queries.

The variable product (parent) is given all child prices so that the filters work,  but there is no relation between stored price + variation/attributes making this type of filtering impossible.

Possibly something to look at during https://github.com/woocommerce/woocommerce/issues/13085 but lower priority IMO
