### ISSUE TITLE
Need Default Atttirbute for Mulitple Attribute Variation

### ISSUE THREAD

**Issue by serenityaquariums** [woocommerce/woocommerce#15160]
### EXPLANATION OF THE ISSUE

When creating a variable product that has multiple attributes that do not all apply to "ALL" products the selection of a variable product with an attribute that doesn't apply to the rest causes other attributes to be not present.  What should be happening is a either the first attribute set or an ability to mark a default attribute that will always be present regardless of the lower selection.  If the default attribute is say "xxxx"  which is the only one with "yyyy" attribute and someone changes attribute "xxxx" to "zzzz" then the secondary attribute should set to "select option".

This has been a standard in e-commerce for as long as I remember, and at that is at least back to 2006.

This can be seen on my site with various products, but the most obvious is "Cichlid Pellets" where I have Small, Medium, and Large.  They are all the same product, but the Large is a different weight in the small and medium sizes.  When someone selects large 3oz size they can no longer choose any other pellet size until they switch the secondary attribute to "Select Option".  Normally I have larger sizes available, but don't have them enabled at the moment.

https://www.serenityaquariums.net/product/omega-one-cichlid-pellets-floating/

### STEPS TO REPRODUCE THE ISSUE

Create a variable product with 2 attributes.  When create the variations make sure that product one has an attribute option that is not available for product 2 but both products should have the same second attributes available at some point as well.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.serenityaquariums.net
Site URL: https://www.serenityaquariums.net
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.19
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wpkc_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

Category Posts Widget: by TipTopPress – 4.7.2
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Facebook Feed: by Smash Balloon – 2.4.5
Facebook for WooCommerce: by Facebook – 1.2.6
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.9
Grid/List View for WooCommerce: by BeRocket – 1.0.6
iframe: by webvitaly – 4.3
Instagram Feed: by Smash Balloon – 1.4.8
IP Ban: by Jay Fortner – 0.7
Jetpack by WordPress.com: by Automattic – 4.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Storefront Hamburger Menu: by WooThemes – 1.2.0
Storefront Product Pagination: by WooThemes – 1.2.1
Storefront Product Sharing: by WooThemes – 1.0.3
Storefront Sticky Add to Cart: by WooThemes – 1.1.6
Theme Customisations: by WooThemes – 1.0.0
TinyMCE Advanced: by Andrew Ozz – 4.5.6
Turbo Widgets: by Datamad Ltd
Todd Halfpenny – 1.0.4

FAQ: by Etoile Web Design – 1.5.34
UPS (BASIC) WooCommerce Shipping: by XAdapter – 1.2.3
W3 Total Cache: by Frederick Townes – 0.9.5.4
USPS (BASIC) WooCommerce Shipping: by XAdapter – 1.1.9
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.1
WooCommerce Extended Coupon Features: by Soft79 – 2.4.3
WooCommerce Conditional Shipping and Payments: by WooThemes – 1.2.5
WooCommerce Amazon Pay Gateway: by WooCommerce – 1.7.1
WooCommerce Intuit Payments Gateway: by SkyVerge – 2.0.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.2
WooCommerce Product Retailers: by SkyVerge – 1.9.0
WooCommerce FedEx Shipping: by WooCommerce – 3.4.6
WooCommerce: by Automattic – 3.0.7
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.7.1
WP Facebook Review Slider: by LJ Apps – 1.7
WP Hummingbird: by WPMU DEV – 1.4.3
WP Smush Pro: by WPMU DEV – 2.6.3
WP-SpamShield: by Scott Allen – 1.9.10
WPMU DEV Dashboard: by WPMU DEV – 4.3
YITH WooCommerce Social Login: by YITHEMES – 1.2.0
YouTube: by EmbedPlus Team – 11.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: ❌ Page ID is set
but the page does not exist

### Theme ###

Name: Storefront
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Intuit Payments Credit Card ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off
`</details>

**Comment by mikejolley** [comment]
> When someone selects large 3oz size they can no longer choose any other pellet size until they switch the secondary attribute to "Select Option". Normally I have larger sizes available, but don't have them enabled at the moment.

If someone did try this, the combination would be invalid - thats why it gets prevented. You have no 'medium' '3oz'.

TBF the way other systems do it is mighty confusing too - amazon for example will let you change the attribute, but then deselects all other inputs which is damn annoying, especially since you cannot tell which combinations **actually are** valid.

With that in mind, I'd prefer to keep the existing way we do it since the alternatives are worse.

If you want the option to show up, leave the other variations enabled but out of stock. The user can choose them but will see an out of stock message.

Hope that makes sense.

**Comment by serenityaquariums** [comment]
Deselecting options when switching one primary attribute from both a business and consumer standpoint instead of selecting an option and having all other options  is a lot less confusing than selecting two options and not seeing any of the others previously seen.But I understand the situation since this was closed.  As a business it leaves me a lot to think about.Larry StevensOn May 19, 2017 3:30 AM, Mike Jolley <notifications@github.com> wrote:
When someone selects large 3oz size they can no longer choose any other pellet size until they switch the secondary attribute to "Select Option". Normally I have larger sizes available, but don't have them enabled at the moment.

If someone did try this, the combination would be invalid - thats why it gets prevented. You have no 'medium' '3oz'.
TBF the way other systems do it is mighty confusing too - amazon for example will let you change the attribute, but then deselects all other inputs which is damn annoying, especially since you cannot tell which combinations actually are valid.
With that in mind, I'd prefer to keep the existing way we do it since the alternatives are worse.
If you want the option to show up, leave the other variations enabled but out of stock. The user can choose them but will see an out of stock message.
Hope that makes sense.

**Comment by mikejolley** [comment]
I disagree but ok 👍 Without a comparison/metrics for both it's just speculation anyway. And you have a workaround so..

> If you want the option to show up, leave the other variations enabled but out of stock. The user can choose them but will see an out of stock message.

**Comment by serenityaquariums** [comment]
Mike,       Yes, you provided a work around.  What you also told me, at least from appearances, is that one person is making the decisions with no checking with businesses or consumers on front facing design.  There is nothing wrong with that for a product, I just didn't know that is the way it was.       As I said, it has given me a lot to think about as a business.  And some research to do that I should have done earlier.Larry StevensOn May 19, 2017 7:27 AM, Mike Jolley <notifications@github.com> wrote:I disagree but ok 👍 Without a comparison/metrics for both it's just speculation anyway. And you have a workaround so..

If you want the option to show up, leave the other variations enabled but out of stock. The user can choose them but will see an out of stock message.

**Comment by mikejolley** [comment]
We have this issue open to look into this - https://github.com/woocommerce/woocommerce/issues/13085 Designs resulting from that will be **user tested.**

**Comment by serenityaquariums** [comment]
I’ll be reviewing all options including custom plugins, custom programming, and other options unrelated.  

 

I understand this is supposed to be a basic e-commerce store, opensource and fully customizable.  But as was stated amazons is a mess, but the truth is it sells.  

And after re-reading the emails with more coffee in me I realized there may be some confusion here.

You are right, there is no medium in 3oz and that is the issue.  There is no large in 3.5oz.  But they are all the same product.

 

The issue is from a consumer standpoint when they choose “Large” and lets say “3oz” they no longer see any other options for other sized pellets, which is the primary differentiation in this product.  

 

Essentially what I would expect should happen, and I’ve tested with two other products now to see if they have retained it, is that a “Default” attribute is set.  In this case it would be the Pellet Size.  Once the default attribute is set and someone selects say “Large” and then “3oz” the Small and Medium would still be visible but upon selecting either if the secondary attribute is not a valid variation it would default back to “select option”.

Maybe in the view of Woocommerce this should be a plugin feature and not an integral part and I am viewing it wrong.

 

There are a lot of products, especially consumables, where the product itself is the same but can come in varying description sizes which alters the secondary variation of weight.  This is relevant I would suspect primarily in consumable products and less so in standard goods products.

 

If this was 8 years ago I could have made the changes myself as I used to do php programming and work with mysql, etc… but that was a while ago and as a business owner the time I have available it would take a long time for me to refresh myself and catch up with any changes in order to do so.

 

Hence why I mentioned reviewing all options because one of the reasons I went with woocommerce was the cost factor, even though I’ve spent quite a bit on plugins through woothemes which I honestly thought was helping support woocommerce (I’ve since discovered that may be wrong and am now unsure).

But thank you for responding and the interaction gave me an insight into the product and the development which I appreciate.  

Hopefully the way I’ve explained it above makes better sense.  

 

Larry Stevens

**Comment by mikejolley** [comment]
May I ask why set a default if you want all options to show up?

**Comment by serenityaquariums** [comment]
It’s not “all options”.  It would only be one of the attributes that would show all.

 

An example would be in reference to the link I provided.  The only one that would be checked as “Default” would be “Pellet Size”.  This is the only one where all options would show up.

 

They come in Small, Medium, and Large but due to variations in the size of the pellets the containers weight is different for Large.

 

My expectation, based on previous work with e-commerce software was that the first attribute would have been the default.  If someone were to select “Large” and “3oz” then select “Small” instead the size option would revert to “Select Option”. 

This avoids consumer confusion when trying to look at the product and variables.

Larry
