### ISSUE TITLE
No Order Notes and Marking Order Complete Goes To Wrong Screen

### ISSUE THREAD

**Issue by jarvo1980** [woocommerce/woocommerce#15176]
### EXPLANATION OF THE ISSUE

Orders don't seem to contain any order notes. Also, if you try to mark an order as processing or complete, it takes you to this screen: https://pasteboard.co/Ova2acSt.png

The order notes aren't updated but the status is

Not come across this before

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://hastingschamber.co.uk
Site URL: https://hastingschamber.co.uk
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.18
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: hacc_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Gravity Forms: by rocketgenius – 2.2.2
ACF Content Analysis for Yoast SEO: by ViktorFroberg
marol87
pekz0r
angrycreative – 1.2.6

Advanced Custom Fields: Flexible Content Field: by Elliot Condon – 1.1.1
Advanced Custom Fields: Gallery Field: by Elliot Condon – 1.1.1
Advanced Custom Fields: Options Page: by Elliot Condon – 1.2.0
Advanced Custom Fields: Repeater Field: by Elliot Condon – 1.1.1
Adminimize: by Frank Bültge – 1.11.2
Advanced Custom Fields: by Elliot Condon – 4.4.11
Capability Manager: by Jordi Canals – 1.3.2
Change WP Mail From Details: by Ruhul Amin – 1.0
Erident Custom Login and Dashboard: by Libin V Babu – 3.5.4
Event Tickets Plus: by Modern Tribe
Inc. – 4.4.8

Event Tickets: by Modern Tribe
Inc. – 4.4.8

Export Users to CSV: by Ulrich Sossou – 1.0.0
Gravity Forms No CAPTCHA reCAPTCHA: by John Parks - Folkhack Studios – 1.0.7
Groups 404 Redirect: by itthinx – 1.3.1
Groups WooCommerce: by itthinx – 1.9.6
Groups: by itthinx – 2.1.2
Import Users from CSV: by Ulrich Sossou – 1.0.0
iQ Block Country: by Pascal – 1.1.42
LiteSpeed Cache: by LiteSpeed Technologies – 1.0.15
MailChimp for WordPress: by ibericode – 4.1.2
My Page Order: by Andrew Charlton – 4.3
Page-list: by webvitaly – 5.1
Post Expirator: by Aaron Axelsen – 2.1.4
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Revolution Slider: by ThemePunch – 4.6.5
Simple 301 Redirects: by Scott Nellé – 1.07
The Events Calendar: by Modern Tribe
Inc. – 4.5.2

Users to CSV: by Joost de Valk – 1.4.5
WooCommerce - Autocomplete Orders: by Serious Plugins – 1.1.4
WooCommerce Customer/Order CSV Export: by WooThemes / SkyVerge – 4.0.5 – 4.3.2 is available
WooCommerce WorldPay Gateway: by Add On Enterprises (Andrew Benbow) – 3.6.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.2
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.1
WooCommerce Subscriptions: by Prospress Inc. – 2.2.5 – 2.2.6 is available
WooCommerce: by Automattic – 3.0.7
Wordfence Security: by Wordfence – 6.3.9
Yoast SEO: by Team Yoast – 4.7.1
WP-Mail-SMTP: by Callum Macdonald – 0.10.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /membership/
Basket: #8 - /basket/
Checkout: #9 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: Hastings
Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: hastings/woocommerce/emails/email-header.php
hastings/woocommerce/emails/email-order-items.php
hastings/woocommerce/myaccount/my-account.php
hastings/woocommerce/order/order-details-item.php

### subscriptions ###

WCS_DEBUG: ❌ Yes
Subscriptions Mode: ✔ Live

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled
`
</details>

**Comment by mikejolley** [comment]
This is an error being thrown whilst emails are generated. Looks like the plugin adding that booking/event info to the email. Check error logs to be sure.
