### ISSUE TITLE
Grouped Products Not Working

### ISSUE THREAD

**Issue by benjaminthedev** [woocommerce/woocommerce#15178]
Thought it was my site but just installed on MAMP server brand new install and set up grouped product and the simple product and I do not get the option to add to grouped product.

**Comment by mikejolley** [comment]
It's in the GROUPED product linked products section.

**Comment by benjaminthedev** [comment]
I know normally it is but it isn't for me

**Comment by benjaminthedev** [comment]
![screen shot 2017-05-19 at 15 46 32](https://cloud.githubusercontent.com/assets/14097672/26253218/7c94bf64-3caa-11e7-87ee-306cad6abeeb.png)

**Comment by benjaminthedev** [comment]
The image above is from my grouped product and this is from my single product 
![screen shot 2017-05-19 at 15 49 35](https://cloud.githubusercontent.com/assets/14097672/26253313/d91d9f3a-3caa-11e7-98b1-dd4a75399510.png)

So are you saying that:

1, I set up a grouped product
2, Then go into my single product(s) and then look at the product data => Linked Products.

As I have done this and grouped products is not there.  I have done this before and it isn't working for me.

Cheers,

Ben.

**Comment by mikejolley** [comment]
https://docs.woocommerce.com/document/managing-products/#section-13

If it's missing you should look at extension conflicts.

**Comment by benjaminthedev** [comment]
There are no other plugins just woocommerce and that is it.  On a brand new install on MAMP server. I will try my other mac / mamp.

**Comment by benjaminthedev** [comment]
Still having issues with this. I have read the link you have sent me and nothing is working.  Just had look on another website and this is the pic they use:

![screen shot 2017-05-19 at 16 34 45](https://cloud.githubusercontent.com/assets/14097672/26255352/353e1258-3cb1-11e7-82a6-2ca8f9334e8e.png)

Simple product in the dropdown and then grouping at the bottom.

This is what I am missing.  If I use grouping on a sub-product of the group then how am I supposed to add prices etc?  Just doesn't make sense to me and I have this on another machine on a different install of MAMP?

Please help as I am pulling my hairout!

**Comment by benjaminthedev** [comment]
This is the article I was reading and got the image from. Circa 2016

https://code.tutsplus.com/articles/woocommerce-grouped-products-and-attributes-which-to-use--cms-25493

Has grouping changed since then?

**Comment by mikejolley** [comment]
Yes read the doc.

**Comment by benjaminthedev** [comment]
ok thanks for the help Mike. Have a good weekend.

**Comment by phil2010** [comment]
did you find an answer? I am having the same problem

**Comment by ken0101010101** [comment]
I have two websites with the exact same problem.
I do not see an actual answer to the problem on this thread or on any of the others I have been looking at.

I select the "Grouped Product" option from pull down menu, but when i go to the "linked products" section i Do Not see any "Gouping" pull down menu, 


There is "Up-Sells" & "Cross-Sells" selections but there is NO "Grouping" option below these in the "Linked Products" tab

**Comment by ken0101010101** [comment]
I am guessing that the fact that this thread has not been responded to in many months
and ... 
not accurately addressed that there is no fix to this issue and woo commerce is not able to group products.

I have spent a lot of time trying to resolve this issue and it does not look like Woocommerce support is able to help.

What is a better online store to switch to?
Is VirtueMart more reliable and able to solve these problems?

Does any one recommend a better / more reliable product that i can switch to?

**Comment by mikejolley** [comment]
> I do not see an actual answer to the problem on this thread or on any of the others I have been looking at.

> It's in the GROUPED product linked products section.

![add new product local wordpress dev wordpress 2017-12-04 12-34-13](https://user-images.githubusercontent.com/90977/33553135-774c3294-d8ef-11e7-8ee1-a851a40f87ec.png)

This has been addressed and is not a bug. If you're missing the grouped product section you're either seeing a plugin/extension conflict, or you're on a version of WooCommerce before this change was made. 

> I am guessing that the fact that this thread has not been responded to in many months

This is an old, outdated/resolved issue. This is also not a support forum. Thats why.
