### ISSUE TITLE
Grouped products

### ISSUE THREAD

**Issue by matslju** [woocommerce/woocommerce#15181]
### EXPLANATION OF THE ISSUE

Version 4.7.5 the box for adding a single product to a grouped product is missing

### STEPS TO REPRODUCE THE ISSUE

Added a product and classified it as grouped.
Added a single product and opened the Linked products tab
There should be a box where I can add the Linked product to the grouped, but it doesn't work

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.metodio.se
Site URL: https://www.metodio.se
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.5
PHP Post Max Size: 50 MB
PHP Time Limit: 90
PHP Max Input Vars: 3000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

Gravity Forms: av rocketgenius – 1.9.15
Advanced Custom Fields: Repeater Field: av Elliot Condon – 1.1.1
Advanced Custom Fields Pro: av elliot condon – 5.3.6.1
Advanced Custom Fields: av Elliot Condon – 4.4.11
Autoptimize: av Frank Goossens (futtta) – 2.1.0
Better Delete Revision: av Galerio & Urda – 1.6.1
Easy Columns: av Pat Friedl – v2.1.3
Enable Media Replace: av Måns Jonasson – 3.0.6
Enhanced E-commerce for Woocommerce store: av Tatvic – 1.0.21
Gravity Forms Quiz Add-On: av Rocketgenius – 2.4.1
Jetpack från WordPress.com: av Automattic – 4.9
Master Slider: av averta – 2.9.8
Quick Page/Post Redirect Plugin: av anadnet – 5.1.8
Reduce Bounce Rate: av Okoth1 – 4.3.1
Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 2.2.6
Storefront Blog Customiser: av WooThemes – 1.2.1
Storefront Designer: av WooThemes – 1.8.4
Storefront Mega Menus: av WooThemes – 1.4.0
Storefront Powerpack: av WooThemes – 1.3.1
Storefront Product Hero: av WooThemes – 1.2.10
WooCommerce Composite Products: av SomewhereWarm – 3.9.4
WooCommerce Conditional Content: av Lucas Stark – 2.0.0
WooCommerce Gateways Country Limiter: av OnTheGoSystems – 1.3
WooCommerce Mix and Match: av WooThemes – 1.2.3
WooCommerce Product Add-ons: av WooCommerce – 2.8.1
WooCommerce Product Bundles: av SomewhereWarm – 5.2.4
WooCommerce Product CSV Import Suite: av WooCommerce – 1.10.14
WooCommerce Google Product Feed: av Lee Willis – 7.1.2
WooCommerce Sequential Order Numbers Pro: av SkyVerge – 1.11.2
WooCommerce Specter Integration: av Krokedil – 1.9.5
WooCommerce Table Rate Shipping: av WooCommerce – 3.0.3
WooCommerce: av Automattic – 3.0.7
WooSlider - WooCommerce Products Slideshow: av WooThemes – 1.0.10
WooSlider: av WooThemes – 2.4.0
WooCommerce Helper: av WooCommerce – 1.7.2 – Nätverk aktiverat
Yoast SEO: av Team Yoast – 4.7.1
WP Featherlight: av WP Site Care – 1.1.0
WP Smush: av WPMU DEV – 2.6.3
WP Super Cache: av Automattic – 1.4.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Butikbas: #2314 - /shop/
Varukorg: #2315 - /varukorg/
Kassan: #2316 - /kassa/
Mitt konto: #2317 - /konto/

### Theme ###

Name: Metodio2017 SF-Child
Version: 1.0.0
Author URL: http://prinforydins.se
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/15178

https://docs.woocommerce.com/document/managing-products/#section-13

**Comment by matslju** [comment]
Ok I saw it there, but it's not possible to enter any values in that box

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x
