### ISSUE TITLE
default_checkout_billing_country filter not used

### ISSUE THREAD

**Issue by thasmin** [woocommerce/woocommerce#15183]
### EXPLANATION OF THE ISSUE

In Woocommerce 3.0, the default_checkout_billing_country filter is marked as a replacement for the default_billing_country filter but it is not used. This issue is tested on Woocommerce 3.0.7.

### STEPS TO REPRODUCE THE ISSUE

grep 'default_checkout_billing_country' -R /var/www/html/wp-content/plugins/woocommerce

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/0334ed255ae86305ec400d4674975341b22e202a/includes/class-wc-checkout.php#L1013
