### ISSUE TITLE
Woocommerce login and wp-admin login Error

### ISSUE THREAD

**Issue by jose3329** [woocommerce/woocommerce#15193]
### EXPLANATION OF THE ISSUE

WordPress latest version and Woocommerce latest version. Every time I log into wp-admin of my website (frnshx.com) it logs in with a Woocommerce account, an account I created to test the Woocommerce registration function. Every time I log out from that Woocommerce account it logs out from the wp-admin. This creates some problems to me and to the website management. If there was a solution I'd be grateful.

### STEPS TO REPRODUCE THE ISSUE

To reproduce the issue you need name and password for wp-admin login

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://frnshx.com
Site URL: http://frnshx.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.19
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp6p_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Il tuo negozio non utilizza HTTPS. Scopri di più su HTTPS e certificati SSL .
Hide errors from visitors: ✔

### Active Plugins (28) ###

Ajax Search Lite: by Ernest Marcinko – 4.7.4
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.43
Contact Form 7: by Takayuki Miyoshi – 4.7
Cookie Notice: by dFactory – 1.2.38
CSSHero: by CssHero.org – 2.3
Sidebar personalizzate: by WPMU DEV – 3.0.6
Easy Google Fonts: by Titanium Themes – 1.4.2
MailChimp per Wordpress: by ibericode – 4.1.2
Max Mega Menu: by Tom Hemsley – 2.3.6
Personal Contact Info Widget: by Juan Sanchez Jr. – 1.2
Free & Simple Contact Form Plugin - PirateForms: by Themeisle – 1.2.2
Pirate Parrot: by Themeisle – 1.2.0
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Responsive WordPress Slider - Soliloquy Lite: by Soliloquy Team – 2.5.1.3
ThemeIsle Companion: by Themeisle – 1.0.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.1

W3 Total Cache: by Frederick Townes – 0.9.5.4
WEN Skill Charts: by WEN Solutions
wenthemes – 1.3.1

Booster Plus for WooCommerce: by Algoritmika Ltd – 1.1.0
WooCommerce Stripe Gateway: by WooCommerce – 3.1.8
Booster for WooCommerce: by Algoritmika Ltd – 2.8.1
WooCommerce MailChimp: by Saint Systems – 2.1.0
WooCommerce: by Automattic – 3.0.7
WP Smush: by WPMU DEV – 2.6.3
WP-SpamShield: by Scott Allen – 1.9.10
WPFront Scroll Top: by Syam Mohan – 1.5
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.29

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #1531 - /catalog/
Carrello: #29 - /carrello/
Cassa: #30 - /checkout/
Il mio account: #1604 - /my-account/

### Theme ###

Name: Zerif Pro Child
Version: 0.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Zerif PRO
Parent Theme Version: 1.8.7.6
Parent Theme Author URL: https://themeisle.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Il tuo tema ha il file woocommerce.php
non potrai sovrascrivere il template personalizzato woocommerce/archive-product.php poichè woocommerce.php ha priorità su archive-product.php. Questo serve a prevenire problemi di visualizzazione.

Overrides: –
`
```
</details>

**Comment by f3bruary** [comment]
Accounts are used for both, as WooCommerce is simply a plugin for WordPress. You can group accounts by assigning a user role like Customer (for front-end only testing or Admin for total control, but authentication is unified. Logging out in WooCommerce (the front-end, also signs you out of the admin area (back-end).

**Comment by jose3329** [comment]
OK. Clear.

There’s another little error on the checkout page, regarding the payment methods box at the bottom of the page. If you trying putting something in the cart you can replicate the issue. However here’s a picture of the error (attached).
I’d be grateful if you could provide me the css selector to easily fix the issue with css, if possible.



Thanks a lot in advance for any support with this,
JS

**Comment by f3bruary** [comment]
@jose3329 There is no image attached. I'm not even sure that's possible through email reply. Either provide the screenshot or the error message through Github.

**Comment by jose3329** [comment]
Here's the image of the error:

<img width="1280" alt="schermata 2017-05-17 alle 21 43 00" src="https://cloud.githubusercontent.com/assets/26511906/26276322/597c274e-3d75-11e7-80b0-ad93b63b693e.png">



JS

**Comment by f3bruary** [comment]
I don't see an error message... If you have trouble setting stuff up ( I assume you are new to WooCommerce), then I suggest asking your questions on the WooCommerce plugin page https://wordpress.org/support/plugin/woocommerce or by searching for tutorials on Google.

**Comment by jose3329** [comment]
I'm sorry Sir,

I installed Stripe credit card payment gateway plugin. I think it is not right that the credit card payment option is located below the Terms and Conditions banner, and outside the payment methods grey box. 


Thanks in advance

Kind regards,
JS

Inviato da iPhone

**Comment by mikejolley** [comment]
This appears to be an issue with the theme. Try another to be sure, then report to the author if it is indeed the cause.
