### ISSUE TITLE
REST API and doc for Payment Gateway

### ISSUE THREAD

**Issue by calvintam236** [woocommerce/woocommerce#15196]
### EXPLANATION OF THE ISSUE

I wrote [Paypal Here Payment Gateway](https://bitbucket.org/calvintam236/developersteve-woocommerce-gateway-paypal-here) with callback (mobile app-based), and I could not find any API doc saying how to implement the callback with the new REST API. 
1. Is the REST API support callback from payment gateway?
2. Payment gateways usually return with GET only. (e.g. Mobile app-based) It doesn't look like REST API call can use GET.

**Comment by mikejolley** [comment]
You can update an order via REST API if you have keys on your app, but this isn't really suitable. Better to make a listener via your gateway plugin and send a request to that. See how we do PayPal Standard IPN in core.
