### ISSUE TITLE
I have updated woocommerce and the price filter is not showing on shop page

### ISSUE THREAD

**Issue by rakeshmali** [woocommerce/woocommerce#15194]
### EXPLANATION OF THE ISSUE

I have updated wooCommerce to 3.0.7. This was showing before update but now it is not showing http://teescart.com/shop/

### STEPS TO REPRODUCE THE ISSUE

Please check here: http://teescart.com/shop/

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Settings > Permalink save. The widget only shows on product archives and the shop page - something may be causing that query to fail.

Tested locally on 3.0.7 and have no issue showing the price widget so I don't think it's a bug.

**Comment by rakeshmali** [comment]
@mikejolley I have saved the permalink again. no resolve the issue. The search widget and category and recent viewed product widgets are showing here perfectly, but only the price widget not showing. I have changed the theme also, but not resolved the issue. Checked at localend and getting the same issue there.. Could you please let me know how can I check and resolve this?

**Comment by mikejolley** [comment]
What about layered nav? Do those show?

The widget won't appear if it can find no prices, or the page is not considered an 'archive'. Plugins can affect that.

**Comment by rakeshmali** [comment]
Ok, Got it. Actually this was not the issue. I have just changed product price at same rate and so the price filter was not showing.
Thanks @mikejolley
