### ISSUE TITLE
Issues with product webhooks

### ISSUE THREAD

**Issue by tzviziv** [woocommerce/woocommerce#15198]
### EXPLANATION OF THE ISSUE

Two issues I noticed when testing the product webhooks:

1. When you create a product with variations, a 'product.created' webhook will be called. The problem is that in the json object that is sent, under 'variations' there are only the variations IDs, without any further data, such as price, sku, etc.
2. When you update a product, instead of 'product.updated' webhook, a 'product.created' is sent again. In this case also, the 'variations' object contains only the variation ID's, even if the change was in a variation property.

### STEPS TO REPRODUCE THE ISSUE

1. Create 'product.created' and 'product.updated' webhooks, with delivery URL to requestBin or similar service.
2. Create a new product with variations. Add some data and click on 'Publish.
3. Check the data arrived to your requestBin.
4. Update some properties of the product. Click on 'Update'
5. Check the data arrived to your requestBin.

### SYSTEM STATUS

<details>

### WordPress Environment ###

Home URL: http://localhost/wp-test
Site URL: http://localhost/wp-test
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.31 (Win32) mod_ssl/2.2.31 OpenSSL/1.0.1t
PHP Version: 5.6.23
PHP Post Max Size: 512 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Remarkety - Email Marketing for WooCommerce: by Remarkety – 1.1.22
WooCommerce Discounts Plus: by Fahad Mahmood – 2.4.1
WooCommerce: by Automattic – 3.0.7
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /index.php/shop/
Cart: #5 - /index.php/cart/
Checkout: #6 - /index.php/checkout/
My account: #7 - /index.php/my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1 – 1.2 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by mikejolley** [comment]
> The payload is JSON encoded and for API resources (coupons, customers, orders, products), the response is exactly the same as if requested via the REST API.

https://woocommerce.github.io/woocommerce-rest-api-docs/#webhooks

If you need details about a product variation, you can query by ID via the REST API. Variations are not expanded automatically.

@claudiosanches Do we need variation webhooks?

**Comment by tzviziv** [comment]
@mikejolley, thanks. From a business point of view, we need the payload to contain relevant information to the webhook topic, without having to do more queries. The whole idea of webhooks is to allow reacting to events near real-time. Having the need to do more requests is a hindrance to that goal, no?

**Comment by mikejolley** [comment]
The webhook is for the product, not the variation. Loading potentially hundreds of variations is not a great idea.

**Comment by tzviziv** [comment]
You got a point. Maybe just those that were updated?

**Comment by claudiosanches** [comment]
> the 'variations' object contains only the variation ID's, even if the change was in a variation property.

For this you can change the output for the REST API v1 that still includes variations, but there is nothing wrong with only including IDs, since the webhook does not requires to include all data, you call still use the REST API to fetch any extra data that you require.

Still as Mike said, we removed variations data from the endpoint, since is a burden for performance loading a product with a lot of variations.

> You got a point. Maybe just those that were updated?

What we can do here is to send specific webhooks for variations.

Maybe we can include all this changes with Webhooks CRUD.

cc @mikejolley

**Comment by mikejolley** [comment]
Noted in that issue.

**Comment by looknear** [comment]
Is there news about this issue?
In architectural point of view, a need for request will miss the purpose of the webhook. 
I would expect the variation data to be in the webhook, if needed.
Maybe adding some yes/No to the webhook settings - "send variation data" ?
