### ISSUE TITLE
PayPal Pro: [L_LONGMESSAGE0] => The totals of the cart item amounts do not match order amounts.

### ISSUE THREAD

**Issue by mirza572** [woocommerce/woocommerce#15206]
### EXPLANATION OF THE ISSUE
[L_LONGMESSAGE0] => The totals of the cart item amounts do not match order amounts.

1.	WooCommerce version is 3.0.7.
2.	In WooCommerce settings ‘prices’ are inclusive of tax.
3.	In WooCommerce settings ‘currency options’ Number of decimals is set as two decimal places
4.	Some transaction details from the log.

[VERSION] => 119
[AMT] => 136.00
....
....
....
[BUTTONSOURCE] => WooThemes_Cart
[L_NUMBER0] => 0
[L_NAME0] => Sheepskin Rug Vole SML
[L_AMT0] => 28.33
[L_QTY0] => 4
[ITEMAMT] => 113.33
[TAXAMT] => 22.67

5.	The cart session data shows that the tax subtotals are fine but I think the total tax calculation is incorrect, one pence less than the order totals.
6.	The issue has been going on since the major update to 3.0.7 for a handful of orders per day. 

### WordPress Environment ###

Home URL: https://www.hiderugs.co.uk
Site URL: https://www.hiderugs.co.uk
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.13
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

301 Redirects: by Tony Spiro – 0.3
PW Advanced Woo Reporting: by Proword – 3.1
Woocommerce Admin Save Rules: by Adrac – 1.0.0
Care Instructions: by Adrac – 1.0.1
DPD for WooCommerce: by Adrac – 1.0.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Cookie Law Info: by Richard Ashby – 1.5.3
Google Tag Manager for Wordpress: by Thomas Geiger – 1.6.1
Easy Testimonials: by Gold Plugins – 2.3
Enable Media Replace: by Måns Jonasson – 3.0.6
Image Widget: by Modern Tribe
Inc. – 4.4.3

Salient Visual Composer: by Michael M - WPBakery.com | Modified by ThemeNectar – 4.12.1
Menu Image: by Alex Davyskiba aka Zviryatko – 2.7.0
Ultimate Expandable WooCommerce Categories: by MagniumThemes – 1.1
Ninja Kick: Contact Form: by Looks Awesome – 3.2.6
Ultimate Social Media PLUS: by UltimatelySocial – 2.6.3
WooCommerce Address Validation: by SkyVerge – 2.1.0
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.7
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce Google Product Feed: by Lee Willis – 7.1.2
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.3
WooCommerce: by Automattic – 3.0.7
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.3.9
Yoast SEO: by Team Yoast – 4.7.1
WP Custom Widget area: by Kishor Khambu – 1.2.5
WP Force SSL: by Kostas Vrouvas – 1.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6 - /search/
Basket: #7 - /cart/
Checkout: #8 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: Salient Child Theme
Version: 0.1
Author URL: http:%20//mysite.com/
Child Theme: ✔
Parent Theme Name: Salient
Parent Theme Version: 8.0.15
Parent Theme Author URL: http://themenectar.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: salient-child/woocommerce/cart/cart-shipping.php
salient/woocommerce/cart/cart-totals.php
salient-child/woocommerce/cart/cart.php
salient/woocommerce/cart/shipping-calculator.php
salient/woocommerce/checkout/form-checkout.php
salient/woocommerce/checkout/form-shipping.php
salient/woocommerce/checkout/review-order.php
salient/woocommerce/checkout/terms.php
salient/woocommerce/content-product.php
salient/woocommerce/content-single-product.php
salient/woocommerce/loop/add-to-cart.php
salient/woocommerce/loop/loop-start.php
salient-child/woocommerce/loop/no-products-found.php
salient/woocommerce/myaccount/form-login.php
salient-child/woocommerce/order/order-details-customer.php
salient-child/woocommerce/order/order-details.php
salient-child/woocommerce/single-product/add-to-cart/grouped.php
salient-child/woocommerce/single-product/add-to-cart/simple.php
salient-child/woocommerce/single-product/price.php
salient-child/woocommerce/single-product/product-attributes.php
salient/woocommerce/single-product/product-image.php
salient-child/woocommerce/single-product/rating.php
salient/woocommerce/single-product/tabs/description.php
salient-child/woocommerce/single-product/tabs/tabs.php
salient-child/woocommerce/single-product-reviews.php

**Comment by mikejolley** [comment]
Can you post to the helpdesk? https://woocommerce.com/contact-us/ They will need to review the logs and see whats going on. PayPal  is more complex as it sends line totals separately and tries to add them up that way - the fallback code may need tweaking to make up the difference.

Thanks

**Comment by mirza572** [comment]
Already done. Thank you.
