### ISSUE TITLE
Dot missing in telephone number validation

### ISSUE THREAD

**Issue by DavidKox** [woocommerce/woocommerce#15205]
In the validation regex for telephone numbers there is a dot (".") missing.
See: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-validation.php#L35

When using input type tel and adding a space some browsers automatically add this dot and cause the validation to fail.

The enhanced regex should be
```'/[\s\#0-9_\.\-\+\(\)]/'```

**Comment by UserName011** [comment]
The `-` is tricky.
"The hyphen should not be confused with dashes (‒, –, —, ―), which are longer and have different uses, or with the minus sign (−), which is also longer in some contexts."
https://en.wikipedia.org/wiki/Hyphen

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/15248#issuecomment-303803667
