### ISSUE TITLE
Shipping calculator in cart doesn't remember address changes for users with shipping address set

### ISSUE THREAD

**Issue by catacaustic** [woocommerce/woocommerce#15201]
### EXPLANATION OF THE ISSUE

Woocommerce 3.0.7

When a user has a shipping address set in their account they cannot set a different address (state, postcode) in the cart shipping calculator and change shipping methods, otherwise the address details are reverted back to the customers shipping address and not the details entered in the calculator.

### STEPS TO REPRODUCE THE ISSUE

Create a new user with no shipping address defined.
Add any items to the cart
Update the address in the cart calculator and submit to calculate costs, this will return correct values.
Choose a differnt shipping method for the same address details, this will return the correct details.

Update the user account to set a shipping address.

Update the address in the cart calculator and submit to calculate costs, this will return correct values.
Choose a differnt shipping method for the same address details, this will return the users shipping address details instead of the address details that were entered.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://testing.dev
Site URL: http://testing.dev
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.5.37
PHP Version: ❌ 5.5.37 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.49.1
OpenSSL/1.0.2d

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
This is expected behavior when logged in because the checkout will load your SAVED shipping and billing addresses. 

The calculator only collects country, state and zip so passing this to the checkout would 

a) Mean incomplete addresses are shown, 
b) mean the saved shipping addresses are not loaded,
c) would only make a difference if the ship to another address box is checked, unless we replaced billing address too which is likely unexpected.

IMO we should leave it for now and review as part of https://github.com/woocommerce/woocommerce/issues/10672

Thanks

**Comment by catacaustic** [comment]
Thanks Mike, but the issue isn't in the checkout, it's in the cart. Users with a shipping address set cannot see a total cart total for anything apart from their set address details, or the first shipping option if they enter different details into the cart shipping calculator.

These details don't have to be sent through to the checkout as I do agree that they are will result in onvalid details there, but it's extremely confusing for users that want to check alternatve shipping rates for ana alternative destination before they move on to the checkout.

**Comment by mikejolley** [comment]
Are you saying it's not updating from the calculator? Not sure what you mean.

**Comment by catacaustic** [comment]
This is the shipping calculator on the cart page.

This was found through a clients use-case. They supply wholesale goods for their customers, and deliver all around the country. The customers have a standard shipping address set in their account as part of their set up. When they create an order they need to ship to areas outside of their set shipping locations, so they need to be able to see a complete total cost in the cart area to know what the cost of the order is to give the final clients accurate quotes, which is important because shipping rates can change dramatically depending on what part of the country they are shipping to because these are large bulky items.

At this stage this cannot happen if they try to use a different shipping method.

On the cart page, selecting anything apart from the first shipping method forces the address details in the carts shipping calculator to be reverted to the saved shipping address. It does not use the location details entered in the carts shipping calculator and gives incorrect results, and this is not visible because the address panel gets hidden after the changes are submitted, so the clients can't see the error.

If you need more examples, I can set up a default system and you can follow the steps that I outlined in my firs submission to see the problem.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/15228 seems to be similar.

**Comment by catacaustic** [comment]
You are correct, it is the same issue. I'd be happy to continue on that ticket.
