### ISSUE TITLE
Product image with thumbnails carousel slider as navigation

### ISSUE THREAD

**Issue by vlaskiz** [woocommerce/woocommerce#15207]
Hello,

It seems I have tried pretty much anything without modifying core files too much to get this flexslider functionality working on Porduct thumbnails.

Scenario:
We have a featured product image and additional 5-6 images in product gallery, which obviously shows up as product thumbnails under main image.

Now thumbnails are just stacking under each other and it seems there's no way to get these thumbnails to display in single line carousel with navigation arrows to scroll that carousel.

Say I want to display 4 thumbnails at any given time and click navigation arrows to scroll through thumbnails just like in flexnav demo on this page http://flexslider.woothemes.com/thumbnail-slider.html

There doesn't seem to be proper container for thumbnails to init flexslider on, even if I append one via jquery, flexslider would still probably need to be initialized first on thumbnails container and synced with product image slider, as per flexslider specifications on the page I mentioned above.

Any solution/feature solution for this?

**Comment by mikejolley** [comment]
> Now thumbnails are just stacking under each other and it seems there's no way to get these thumbnails to display in single line carousel with navigation arrows to scroll that carousel.

You need to style them with CSS - I don't think this sounds like a WC bug at all, just something lacking in your theme..

Have you looked at a default theme or Storefront? Those use flexslider etc and style the thumbnails correct in a line to be clickable. Take a look.

**Comment by vlaskiz** [comment]
I took a look into storefront, and thumbnails do not stack in a single line, they stack in multiple rows with each containing 5 columns. This may not be a bug but it sure does not provide proper features to use all or at least these specific features of official flexslider plugin.

**Comment by mikejolley** [comment]
FWIW our gallery does more than stock flexslider e.g. zoom and lightbox and is more suited to product display that a carousel.

You have control over CSS, and can override templates if needed if you need something custom.

https://docs.woocommerce.com/document/template-structure/

 Github however is not the place to solicit this kind of work. https://woocommerce.com/experts/

**Comment by vlaskiz** [comment]
I understand. But lack of container div for ol element that holds thumbnail li elements does make it harder and even ol element is added via jquery and not naturally, why?
also why it's ol instead of standart ul which is used in flexsliders markup examples? (this one might not matter).

I am not trying to brag, but markup seems weird from what standart flexslider markup uses, and being able to edit it slightly or wrap in container div's via templates would make it much easier than modifying js files that are enqueued in core woo files (that means, I have to dequeue it, enqueue one from withing my template and I doubt system status tool notifies if there's any changes in script files in case there would be any in the future).

**Comment by mikejolley** [comment]
Where are you seeing ol/ul? https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-thumbnails.php

If you're using JS to add flexslider, I don't think it's unreasonable to change markup with JS too if needed?

**Comment by vlaskiz** [comment]
This is from storefront theme, default markup (which is pretty much the same on my stores that I develop, but just for the sake of it being default):

http://imgur.com/a/Geh2H

I am using default WooCommerce flexslider that is enabled via add theme support, my external flexslider script won't even respond within product page, unless I would modify stuff very heavily changing how thumbnails are retrieved for product, most likely that could work.

But then, as you can see in the screenshot, li elements surrounding thumgnail links, and ol element is added via js (within flexslider script), leaving almost no way modifying it or adding proper container element (considering we want best practices here to be involved).

May not be unreasonable, but can you say it's ideal or at least moderately ideal way?

**Comment by mikejolley** [comment]
Those elements are added by flexslider no...?

**Comment by vlaskiz** [comment]
I will look into it if I am not missing something here.

**Comment by retroriff** [comment]
Hi @vlaskiz , did you find a solution? I also tried to create a flexslider carousel but it lacks a flexslider container. The current WC structure doesn't allow to add it without overwriting the their templates.

**Comment by retroriff** [comment]
Single Product Thumbnails template version 2.3.0 had this container:

<div class="flexslider" id="carousel"></div>

**Comment by retroriff** [comment]
Single Product Thumbnails template version 2.3.0 had this container:

`<div class="flexslider" id="carousel">`

**Comment by vlaskiz** [comment]
@retroriff Sadly I had to just ignore 3.x flexslider functionality and make my own. In older versions it was very convenient to easily attach flexslider, now you kind of have to skip most of it and modify both default templates markup and add your own on top.

**Comment by retroriff** [comment]
Yes, it's a pitty that WC doesn't give any solution for products with several images. The default Storefront layout is not optimized for mobile devices:

http://i.imgur.com/Wv0HoCY.png

**Comment by SergiiManiuk** [comment]
As I understand, this is meant carousel.
http://flatsome3.uxthemes.com/shop/clothing/ship-your-idea/
http://flatsome3.uxthemes.com/shop/women/varanise-cn-tee-hilfiger-denim/?vertical_tabs
And if you look here
https://demo.woothemes.com/storefront/product/stripy-top/
(great girl by the way =) )
we can see
<ol class="flex-control-nav flex-control-thumbs"><li><img src="https://demo.woothemes.com/storefront/wp-content/uploads/sites/78/2015/07/stripy-top.jpg?w=200&amp;h=200&amp;crop=1" class="flex-active" draggable="false"></li><li><img src="" draggable="false"></li></ol>
There is no carousel
And this code does not help
    $(window).load(function(){
      $('.flex-control-thumbs').flexslider({
        animation: "slide",
        controlNav: "thumbnails",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });
And how to add arrows to flip?

**Comment by jordan-webdev** [comment]
My solution for this is to use slick slider, but set a timeout of 300 first in order to let WooCommerce execute its JavaScript first. I know, it's not a great solution, and I've been frustrated with how difficult it has been to develop with WooCommerce. There really should be functions like wc_get_gallery_thumbs() and wc_get_gallery_main_image() so we can just construct the HTML ourselves, or at least offer a document trigger in JS that we can hook on to once WooCommerce has finished setting up the gallery.

`setTimeout(function() {
    $('.flex-control-nav').slick({
      infinite: false,
      slidesToShow: 4,
      slidesToScroll: 1,
    });
  }, `300);`

**Comment by retroriff** [comment]
@SergiiManiuk They are using custom templates. The question here is how to create a carousel while keeping the original WC templates.

**Comment by Pablo-Araya** [comment]
so... does anyone has found a solution ?

**Comment by ryonwhyte** [comment]
@Pablo-Araya Have you applied this code? And it works?

**Comment by juandavid92** [comment]
Hi, I have the same problem, do any of you know any solution?
I want to make a carousel of images in the woocommerce product gallery 
but I can't, I tried with flexslider and I can't.
<ol class="flex-control-nav flex-control-thumbs"><li></li></ol>

**Comment by ryonwhyte** [comment]
@juandavid92 Try slick slider. Flex slider would work so I used slick slider instead.

**Comment by retroriff** [comment]
As I understandit, WooCommerce default Flexlider behaviour is "Slider w/thumbnail controlNav pattern":

http://flexslider.woothemes.com/thumbnail-controlnav.html

While we are asking for a "Slider w/thumbnail slider":

http://flexslider.woothemes.com/thumbnail-slider.html

This means that the HTML code should be replaced with 2 lists (#slider and #carousel). Therefore the images template should be copied and modifed in your theme. But this is something that we would like to avoid.

**Comment by SergiiManiuk** [comment]
> As I understandit, WooCommerce default Flexlider behaviour is "Slider w/thumbnail controlNav pattern":
> 
> http://flexslider.woothemes.com/thumbnail-controlnav.html
> 
> While we are asking for a "Slider w/thumbnail slider":
> 
> http://flexslider.woothemes.com/thumbnail-slider.html
> 
> This means that the HTML code should be replaced with 2 lists (#slider and #carousel). Therefore the images template should be copied and modifed in your theme. But this is something that we would like to avoid.

This is exactly what we are trying to do. 
Only without adding asNavFor: '#slider', sync: "#carousel". Guys, am I right?

**Comment by SergiiManiuk** [comment]
> > As I understandit, WooCommerce default Flexlider behaviour is "Slider w/thumbnail controlNav pattern":
> > http://flexslider.woothemes.com/thumbnail-controlnav.html
> > While we are asking for a "Slider w/thumbnail slider":
> > http://flexslider.woothemes.com/thumbnail-slider.html
> > This means that the HTML code should be replaced with 2 lists (#slider and #carousel). Therefore the images template should be copied and modifed in your theme. But this is something that we would like to avoid.
> 
> This is exactly what we are trying to do.
> Only without adding asNavFor: '#slider', sync: "#carousel". Guys, am I right? 
You need to create two sliders. $ ('# carousel'). flexslider ({
$ ('# slider'). flexslider (
What for? If we already have a thumbnail, which should have arrows to scroll left and right.

Like here http://flexslider.woothemes.com/thumbnail-slider.html

**Comment by edmundcwm** [comment]
Has anyone managed to achieve this without using Slick or any template override?

**Comment by de-b** [comment]
I have spent a lot time to fix this, and it worked for me. If you guys are happy to use slick slider for the thumbnail, here is the solution:
Like @jordan-webdev said, set a timeout of 300 first in order to let WooCommerce execute its JavaScript.

`setTimeout(function() {
    $('.flex-control-nav').slick({
        dots: true,
        infinite: true,
        arrows: true,
        speed: 600,
        slidesToShow: 3,
        slidesToScroll: 1,
    });
}, 300);`

to make it perfectly work, use this css which will fix the issue:
`.woocommerce div.product .woocommerce-product-gallery--columns-4 .flex-control-thumbs li:nth-child(4n+1) { clear:none }`

**Comment by edmundcwm** [comment]
I put together a [plugin](https://github.com/edmundcwm/EDM-Product-Gallery-Slider) for this and it's working well for me.

**Comment by retroriff** [comment]
@edmundcwm @de-b Excellent! Do you have any live example?

**Comment by ThomasSultana** [comment]
I've managed to work around this. You can take a look at the simple script i've put together in my gist.

https://gist.github.com/ThomasSultana/390c7c015efb3d76bb89ece0f523ba56

**Comment by retroriff** [comment]
@ThomasSultana Hello, I add it to my theme but it didn't work as expected. Do you have any running live example?

**Comment by edmundcwm** [comment]
@retroriff Did u try using the my [plugin](https://github.com/edmundcwm/EDM-Product-Gallery-Slider)?

**Comment by retroriff** [comment]
@edmundcwm Yes, it works, thank you. The thumbs are located before the image, but this is something that I could fix with CSS. Also the arrows are missing but I can fix it dequeing assets and using my own:

https://i.imgur.com/0Y6FYYm.png

**Comment by de-b** [comment]
@retroriff 
https://ezilift.webconcierge.com.au/product/sales/materials-handling-sales/ezilift-el-series/

if this helps.
Thanks

**Comment by retroriff** [comment]
@de-b Thanks, I also decided to use Slick.

**Comment by judegimeno** [comment]
@edmundcwm I tried your plugin and it's awesome and i've found out that it's not working with additional image gallery (gallery not changing) i used woocomerce additional variation gallery image  by woocomerce and codixer

**Comment by edmundcwm** [comment]
@judegimeno Thanks for the feedback. Could you open an issue in the [plugin repo](https://github.com/edmundcwm/EDM-Product-Gallery-Slider/issues)? I'll try my best and look into that!

**Comment by judegimeno** [comment]
> @judegimeno Thanks for the feedback. Could you open an issue in the [plugin repo](https://github.com/edmundcwm/EDM-Product-Gallery-Slider/issues)? I'll try my best and look into that!

Sure! i will open an issue ticket about this thank u!!

**Comment by maiarra** [comment]
> @retroriff Did u try using the my [plugin](https://github.com/edmundcwm/EDM-Product-Gallery-Slider)?

Man, this plugin is fire!! I've been searching for a solution for days now, this is the only one that works fine besides Crocoblock. About the product variations issue, mine, when selected, is showing up on the main product image thumbnail.

Thank you immensely!

**Comment by payalord** [comment]
> @retroriff
> https://ezilift.webconcierge.com.au/product/sales/materials-handling-sales/ezilift-el-series/
> 
> if this helps.
> Thanks

Your example helped me a lot, thanks. Exactly what i was looking for.

**Comment by pixelicous** [comment]
@edmundcwm I dont see the arrows with the plugin..

**Comment by pixelicous** [comment]
@de-b -c how did you manage to get past the fact that arrows are not shown?? i see previous/next text, i tried some code examples to change it to fontawesome but everything is just transparent :(

**Comment by pixelicous** [comment]
@de-b @retroriff @ryonwhyte @payalord  did you guys manage to use slick with variation products? when using slick i cannot get the product image to correctly change when picking a color for instance

**Comment by payalord** [comment]
@pixelicous i just created my own solution with that example i mentioned. And I took only thumbs part of it.

**Comment by pixelicous** [comment]
I got the whole main image/thumbnails thing working with slick
The problem is that when picking any variation from woocommerce, the main image slides to a blank image..

You have anywhere I can see your code or working example?

Been trying flex slider and slick, in so many ways.. I just can't get it to work on flex slider.. It's always showing a grid

**Comment by AbhishekAnand-Cedcoss** [comment]
@payalord I got the same issue, Not able to manage Slick slider with variation images. Main image is not changing as per variation selected. Any hope..?

**Comment by payalord** [comment]
> @payalord I got the same issue, Not able to manage Slick slider with variation images. Main image is not changing as per variation selected. Any hope..?

Plugin's main php file:
```php
// If this file is called directly, abort.
if (!defined('WPINC')) {
    die;
}

add_action('plugins_loaded', 'wpg_hooks');

function wpg_hooks() {
    add_action('wp_enqueue_scripts', 'wpg_assets');
}

//---------------------------------------------------------------------
// Plugin Functions
//---------------------------------------------------------------------

if (!function_exists('wpg_assets')) {
    //---------------------------------------------------------------------
    // enqueue scripts and styles For Product Gallery
    //---------------------------------------------------------------------

    function wpg_assets() {
        wp_enqueue_script('slick-js', plugin_dir_url(__FILE__) . 'assets/public/js/slick.min.js', array('jquery'), '2.0', true);
        wp_register_script('wpgjs', plugin_dir_url(__FILE__) . 'assets/public/js/wpg.js', array(), '2.0', true);

        // Enqueued script with localized data.
        wp_enqueue_script( 'wpgjs' );

        wp_enqueue_style('slick-style', plugin_dir_url(__FILE__) . 'assets/public/css/slick.css', null,'2.0' );
        wp_enqueue_style('slick-theme', plugin_dir_url(__FILE__) . 'assets/public/css/slick-theme.css', null, '2.0');
        wp_enqueue_style('wpg-style', plugin_dir_url(__FILE__) . 'assets/public/css/wpg.css', null, '2.0');
    }
}
```

`wpg.js` file:
```js
;(function($) {
    function setupSlick() {
        let nav = $('.flex-control-nav');
        if (nav.length) {
            nav.slick({
                slidesToShow:4,
                slidesToScroll:1,
                dots: false,
                infinite: false,
                arrows: true,
                speed: 600,
                prevArrow: "<button type='button' class='pull-left'><i class='fa fa-angle-left' aria-hidden='true'></i></button>",
                nextArrow: "<button type='button' class='pull-right'><i class='fa fa-angle-right' aria-hidden='true'></i></button>",
                responsive:[
                    {
                        breakpoint:767,
                        settings:{
                            draggable:true,
                            isMobile:true,
                            arrows:false
                        }
                    },
                ]
            });
        } else {
            setTimeout(setupSlick, 300);
        }
    };
    function fixSize() {
        setTimeout(function() {
            $('ol.flex-control-nav.flex-control-thumbs div.slick-track li.slick-slide').css("height", $("ol.flex-control-nav.flex-control-thumbs div.slick-track li.slick-slide").innerWidth());
        }, 300);
    }
    $( document ).ready(function() {
        $('div.imagewrapper').css("height", $("div.imagewrapper").innerWidth());
        $('.woocommerce-product-gallery .woocommerce-product-gallery__image').css("min-height", $(".woocommerce-product-gallery").innerWidth());
        $('.woocommerce-product-gallery .woocommerce-product-gallery__image>a').css("min-height", $(".woocommerce-product-gallery").innerWidth());
        $('.woocommerce-product-gallery .woocommerce-product-gallery__image a>img').css("max-height", $(".woocommerce-product-gallery").innerWidth());
        fixSize();
    });
    $(window).resize(function() {
        $('div.imagewrapper').css("height", $("div.imagewrapper").innerWidth());
        $('.woocommerce-product-gallery .woocommerce-product-gallery__image').css("min-height", $(".woocommerce-product-gallery").innerWidth());
        $('.woocommerce-product-gallery .woocommerce-product-gallery__image>a').css("min-height", $(".woocommerce-product-gallery").innerWidth());
        $('.woocommerce-product-gallery .woocommerce-product-gallery__image a>img').css("max-height", $(".woocommerce-product-gallery").innerWidth());
        fixSize();
    }).resize();
    setupSlick();
})( jQuery );
```

`wpg.css`:
```css
ol.flex-control-nav.flex-control-thumbs { overflow:visible !important; }
ol.flex-control-nav.flex-control-thumbs .slick-list.draggable { margin:0 -4px 0 -5px; }
ol.flex-control-nav.flex-control-thumbs li { background:#fff; text-align:center; margin:0 5px !important; display:flex; align-items:center; justify-content:center; box-shadow:0 0 0 1px rgba(0, 0, 0, 0.2) inset; position:relative; }
ol.flex-control-nav.flex-control-thumbs li img { display:inline-block !important; height:auto !important; width:auto !important; max-width:100% !important; max-height:100% !important; }
ol.flex-control-nav.flex-control-thumbs li:focus { outline:none; }
ol.flex-control-nav.flex-control-thumbs button.slick-arrow { position:absolute; top:50%; transform:translate(0, -50%); z-index:10; background:#f47925; border:none; width:40px; height:40px; border-radius:500px; color:#fff; }
ol.flex-control-nav.flex-control-thumbs button.slick-arrow:focus { outline:none; }
ol.flex-control-nav.flex-control-thumbs button.slick-arrow.slick-disabled { background:#ccc; color:#888; }
ol.flex-control-nav.flex-control-thumbs button.pull-right { right:-20px; }
ol.flex-control-nav.flex-control-thumbs button.pull-left { left:-20px; }
```

But not sure will it help or not in your case guys.

**Comment by draganmilenkovic** [comment]
> Hello,
> 
> It seems I have tried pretty much anything without modifying core files too much to get this flexslider functionality working on Porduct thumbnails.
> 
> Scenario: We have a featured product image and additional 5-6 images in product gallery, which obviously shows up as product thumbnails under main image.
> 
> Now thumbnails are just stacking under each other and it seems there's no way to get these thumbnails to display in single line carousel with navigation arrows to scroll that carousel.
> 
> Say I want to display 4 thumbnails at any given time and click navigation arrows to scroll through thumbnails just like in flexnav demo on this page http://flexslider.woothemes.com/thumbnail-slider.html
> 
> There doesn't seem to be proper container for thumbnails to init flexslider on, even if I append one via jquery, flexslider would still probably need to be initialized first on thumbnails container and synced with product image slider, as per flexslider specifications on the page I mentioned above.
> 
> Any solution/feature solution for this?

if you're already inside a jQuery(document).ready(function($) {  /* YOU'RE HERE */ }); in your main JS file, wrap it in another one (another jQuery(document).ready(function($) { } ). It's the goddemn woocommerce making people's life hell. But this works, I guess having another doc ready makes it "really" wait for it. That's how you can wait any Woo issue out BUT get familiar with what their code can actually do (i.e. read docs thoroughly, read in-code comments etc.) because when they make it hard to change something, that something is usually being managed from elsewhere / or being relied on by other functionality. HNY2023

**Comment by prescribed330** [comment]
> > Now thumbnails are just stacking under each other and it seems there's no way to get these thumbnails to display in single line carousel with navigation arrows to scroll that carousel.
> 
> You need to style them with CSS - I don't think this sounds like a WC bug at all, just something lacking in your theme..
> 
> Have you looked at a default theme or Storefront? Those use flexslider etc and style the thumbnails correct in a line to be clickable. Take a look.





https://preprocessor.space/questions/generating-a-perfectly-centered-thumbnail-image
