### ISSUE TITLE
Automatic Email on order not sending

### ISSUE THREAD

**Issue by nbdamian** [woocommerce/woocommerce#15200]
### EXPLANATION OF THE ISSUE
When going to the "Thanks for your order" page, it is supposed to send out the emails. However php is returning the following error:
`
sh: -t: command not found
`
I read this an being an issue with the wp_mail. as it does not occur if I prevent the emails from sending.
The website was imported over from utf8mb4 to utf8, so perhaps this is an encoding issue?

### STEPS TO REPRODUCE THE ISSUE

Made an order, went to checkout, checked out.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://www.engraveit.co.nz
Site URL: http://www.engraveit.co.nz
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.17
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.45.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: ❌ 5.1.73 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (20) ###

Gravity Forms: by rocketgenius – 2.2.2
Advanced Custom Fields: Gravity Forms Field: by @adam_pope of @stormuk – 1.1.0
Admin Menu Tree Page View: by Pär Thernström – 2.6.9
Advanced Custom Fields PRO: by Elliot Condon – 5.5.14
AJAX Thumbnail Rebuild: by junkcoder – 1.12
Custom Related Products for WooCommerce: by Scott Nelle – 1.3
Debug Bar Actions and Filters Addon: by Subharanjan – 1.5.2
Debug Bar: by wordpressdotorg – 0.9
Duplicator: by Snap Creek – 1.2.8
Monkeyman Rewrite Analyzer: by Jan Fabry – 1.0
Bitbucket Issues: by ninetyblack – 0.2.10
Convert WP Database to UTF-8: by Yihui Xie – 1.0.2
WooCommerce Dynamic Pricing: by Lucas Stark – 3.0.7
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.3
WooCommerce TM Extra Product Options: by themecomplete – 4.5.2
WooCommerce: by Automattic – 3.0.7
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.3.9
Yoast SEO: by Team Yoast – 4.7.1
WP fail2ban: by Charles Lecklider – 3.5.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #209 - /shop/
Cart: #210 - /cart/
Checkout: #211 - /checkout/
My account: #212 - /my-account/

### Theme ###

Name: Engrave It
Version: 0.1
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Engrave-it/woocommerce/archive-product.php
Engrave-it/woocommerce/cart/cart-empty.php
Engrave-it/woocommerce/cart/cart-item-data.php
Engrave-it/woocommerce/cart/cart-totals.php
Engrave-it/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
Engrave-it/woocommerce/cart/mini-cart.php
Engrave-it/woocommerce/cart/proceed-to-checkout-button.php
Engrave-it/woocommerce/checkout/cart-errors.php
Engrave-it/woocommerce/checkout/form-checkout.php
Engrave-it/woocommerce/checkout/form-coupon.php
Engrave-it/woocommerce/checkout/form-pay.php
Engrave-it/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/checkout/payment.php
Engrave-it/woocommerce/checkout/review-order.php
Engrave-it/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/emails/admin-cancelled-order.php
Engrave-it/woocommerce/emails/admin-failed-order.php
Engrave-it/woocommerce/emails/admin-new-order.php
Engrave-it/woocommerce/emails/customer-completed-order.php
Engrave-it/woocommerce/emails/customer-invoice.php
Engrave-it/woocommerce/emails/customer-new-account.php
Engrave-it/woocommerce/emails/customer-note.php
Engrave-it/woocommerce/emails/customer-on-hold-order.php
Engrave-it/woocommerce/emails/customer-processing-order.php
Engrave-it/woocommerce/emails/customer-refunded-order.php
Engrave-it/woocommerce/emails/customer-reset-password.php
Engrave-it/woocommerce/emails/email-styles.php
Engrave-it/woocommerce/global/quantity-input.php
Engrave-it/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/loop/loop-end.php
Engrave-it/woocommerce/loop/loop-start.php
Engrave-it/woocommerce/loop/no-products-found.php
Engrave-it/woocommerce/loop/price.php
Engrave-it/woocommerce/myaccount/dashboard.php
Engrave-it/woocommerce/myaccount/downloads.php version 2.6.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/myaccount/form-add-payment-method.php version 2.6.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/myaccount/form-edit-account.php
Engrave-it/woocommerce/myaccount/form-edit-address.php version 2.6.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/myaccount/form-login.php
Engrave-it/woocommerce/myaccount/form-lost-password.php version 2.6.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/myaccount/form-reset-password.php version 2.6.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/myaccount/lost-password-confirmation.php
Engrave-it/woocommerce/myaccount/my-account.php
Engrave-it/woocommerce/myaccount/my-address.php
Engrave-it/woocommerce/myaccount/my-downloads.php
Engrave-it/woocommerce/myaccount/my-orders.php
Engrave-it/woocommerce/myaccount/navigation.php
Engrave-it/woocommerce/myaccount/orders.php version 2.6.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/myaccount/payment-methods.php
Engrave-it/woocommerce/myaccount/view-order.php version 2.6.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/notices/error.php
Engrave-it/woocommerce/notices/notice.php
Engrave-it/woocommerce/notices/success.php
Engrave-it/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/order/order-details-item.php version 2.5.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/order/order-details.php version 2.6.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
Engrave-it/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
DB should be utf8mb4 - thats what WordPress uses. 

But it could also be a server issue so you should contact your hosting provider https://leo.steamr.com/2010/05/php-mail-returns-sh-t-command-not-found/

You could alternatively use a SMTP plugin to use a different method of sending.
