### ISSUE TITLE
Login and shop cart dont working

### ISSUE THREAD

**Issue by iannizzotto-ga** [woocommerce/woocommerce#15212]
### EXPLANATION OF THE ISSUE

Hi, I have a website on-line, is not working when the users try login and when I click "add to the cart" to any product, immediately erases or disappears from it. i have the same website in my local files and it really works, i didn't find the differences between them for track the issues. This is the website www.kolection.com, I Switched to Twenty theme and it still does not work.
**Any solution/feature solution for this?**
Sorry if my english is hard to understand.

### STEPS TO REPRODUCE THE ISSUE

1. is not working when the users try login.
2.  when i click "add to the cart" to any product, immediately erases or disappears from it

### SYSTEM STATUS

<details>
Entorno WordPress
URL ﻿de la página de inicio:		http://www.kolection.com
URL del sitio:		http://www.kolection.com
Versión de WC:		3.0.7
Directorio de registros con permiso de escritura:		 /home/kolectio/public_html/wp-content/uploads/wc-logs/
Versión de WP:		4.7.5
WordPress Multisitio:		–
Límite de memoria WP:		256 MB
Modo de depuración de WP:		–
WP Cron:		
Idioma:		es_ES
Entorno del servidor
Información del servidor:		Apache
Versión de PHP:		5.6.30
PHP post max size:		64 MB
PHP time limit:		30
PHP max input vars:		1000
Versión cURL:		7.53.1, OpenSSL/1.0.1e
SUHOSIN Instalado:		–
Versión de MySQL:		5.6.35
Tamaño máximo de subida:		64 MB
Por defecto la zona horaria es GMT:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Cadena multibyte:		
Publicación remota:		
Obtención remota:		
Base de datos
Versión de la base de datos de WC:		3.0.7
Prefijo de la base de datos	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
Base de datos GeoIP de MaxMind:		 /home/kolectio/public_html/wp-content/uploads/GeoIP.dat
Seguridad
Conexión segura (HTTPS):		Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Ocultar errores a los visitantes		
Plugins activos (19)
Dokan (Lite) - Multi-vendor Marketplace	 	por Tareq Hasan – 2.6.2
Gigaom New Relic	 	por Gigaom – 0.3
Loco Translate	 	por Tim Whitlock – 2.0.14
Ninja Forms	 	por The WP Ninjas – 3.1.2
Regenerate Thumbnails	 	por Alex Mills (Viper007Bond) – 2.2.6
Taxonomy Metadata	 	por mitcho (Michael Yoshitaka Erlewine), sirzooro – 0.5
TimThumb Vulnerability Scanner	 	por Peter Butler – 1.54
WooCommerce Oca Shipping	 	por Wanderlust Web Design – 0.7.2
WC Password Strength Ajustes	 	por Daniel Santoro – 1.1.0
Woocommerce CSV Import	 	por Allaerd Mensonides – 3.3.5
WooCommerce MercadoPago	 	por Claudio Sanches – 50.0.0
WooCommerce Simply Exportar pedidos	 	por Ankit Gade – 2.1.7
WooCommerce	 	por Automattic – 3.0.7
WooSidebars	 	por WooThemes – 1.4.3
Yoast SEO	 	por Equipo Yoast – 4.7.1
WordPress Database Backup	 	por Austin Matzko – 2.3.1
WP Super Cache	 	por Automattic – 1.4.9
YITH WooCommerce Ajax Buscar	 	por YITHEMES – 1.5.2
YITH WooCommerce Wishlist	 	por YITHEMES – 2.1.2
Ajustes
API activada:		
Forzar SSL:		–
Moneda		ARS ($)
Ubicación de la moneda		left
Separador de miles		.
Separador decimal		,
Número de decimales		2
Taxonomías: Tipos de producto		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomías: Visibilidad del producto		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Páginas de WC
Base de la tienda:		#10 - /tienda/
Carrito:		#11 - /carro/
Finalizar compra:		#12 - /finalizar-comprar/
Mi cuenta:		#13 - /mi-cuenta/
Tema
Nombre:		Flatsome Child Theme
Versión:		2.5
URL del autor:		http:%20//www.uxthemes.com/
Tema hijo:		
Nombre del tema padre:		Flatsome
Versión del tema padre:		2.5.6
URL del autor del tema padre:		http://www.uxthemes.com/
Soporte WooCommerce:		
Plantillas
Anulaciones	 	flatsome/woocommerce/archive-product.php, 
flatsome/woocommerce/cart/cart.php, 
flatsome/woocommerce/checkout/form-checkout.php, 
flatsome/woocommerce/content-product.php, 
flatsome/woocommerce/content-product_cat.php, 
flatsome/woocommerce/content-single-product.php, 
flatsome-child/woocommerce/emails/email-header.php, 
flatsome/woocommerce/global/breadcrumb.php, 
flatsome/woocommerce/global/wrapper-end.php, 
flatsome/woocommerce/global/wrapper-start.php, 
flatsome/woocommerce/loop/loop-end.php, 
flatsome/woocommerce/loop/loop-start.php, 
flatsome/woocommerce/loop/orderby.php, 
flatsome/woocommerce/loop/pagination.php, 
flatsome/woocommerce/loop/sale-flash.php, 
flatsome-child/woocommerce/myaccount/form-login.php, 
flatsome/woocommerce/notices/error.php, 
flatsome/woocommerce/notices/success.php, 
flatsome/woocommerce/product-searchform.php, 
flatsome/woocommerce/single-product/add-to-cart/grouped.php, 
flatsome/woocommerce/single-product/add-to-cart/simple.php, 
flatsome/woocommerce/single-product/add-to-cart/variable.php, 
flatsome/woocommerce/single-product/price.php, 
flatsome/woocommerce/single-product/product-image.php, 
flatsome/woocommerce/single-product/related.php, 
flatsome/woocommerce/single-product/review.php, 
flatsome/woocommerce/single-product/sale-flash.php, 
flatsome/woocommerce/single-product/share.php, 
flatsome/woocommerce/single-product/short-description.php, 
flatsome/woocommerce/single-product/tabs/additional-information.php, 
flatsome/woocommerce/single-product/tabs/description.php, 
flatsome/woocommerce/single-product/tabs/tabs.php, 
flatsome/woocommerce/single-product/title.php, 
flatsome/woocommerce/single-product/up-sells.php, 
flatsome/woocommerce/single-product-reviews.php, 
flatsome/woocommerce/single-product.php
</details>

**Comment by mikejolley** [comment]
This is usually a caching plugin issue. Exclude cart/checkout/account from cache. That includes server side cache if using it (varnish).
