### ISSUE TITLE
Missing Variable

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#15213]
Hi,

Could you please check this file class-wc-geolocation.php, code below

`if ( ! preg_match( $ipv4_pattern, $ip ) && ! Requests_IPv6::check_ipv6( $ip ) ) {`

**$ip variable is undefined**

Best regards,
Nenad

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/15223
