### ISSUE TITLE
Method override doesnt work with Rest Api. Ex. _method=PUT

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#15218]
### EXPLANATION OF THE ISSUE

_woocommerce 3.0 +_

The following Request types is accepted by the api (with cors and http - im not targetting https sites now)

- GET
- POST

Any other requests creates preflight.
It also requires content type to be **multipart form data** or **text / plain** to avoid preflight.

**application/json** will execute **Preflight request which I think is not correctly handled by the API** so the request is unexpectedly ended. My nginx server accepts application/json, so it has to be an wordpress / woocommerce issue.

Adding post data to **URL PARAMETERS** is now the only solution I found which is accepted, but the _method=PUT override function doesnt seems to work.

**Works:**
Ex. http://mysite.com/wp-json/wc-api/v2/coupons?code=my_code&oauth_x...

**Doesnt work:**
Ex. http://mysite.com/wp-json/wc-api/v2/coupons/2354?_method=PUT&code=my_new_code&oauth_x...

I tried to append _method=PUT to oauth signature and leave it out. Both attempts returned:

> Invalid signature - provided signature does not match.

But **IT IS** matched if I remove _method=PUT, so the signature is correctly generated (Have been through it in about 3 days now to check if anything is wrong according to [oauthbible](http://oauthbible.com/) and [twitter](https://dev.twitter.com/oauth)) but everything looks ok.

I also tried to switch method in OAuth basestring from POST to PUT and visa versa with no success.

I found one workaround to also accept PUT requests, by first applying OAuth credentials to URL and then applying another generated OAuth credentials to the header which is unique the one in URL and send the request as an OPTIONS request with _method=PUT in the URL...

This is getting very ugly, so I would be happy for any advice here :-)

**Edit:**

I forgot to say that this did work correctly with earlier versions of woocommerce...

And I have also tried alot of libraries, SDKs etc. so I decided to create my own oauth generator to get it correctly handled according to the twitter oauth tutorial. 

Also tried all different ways to handle OAuth 1.0a in postman etc..

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
It will be the way in which you generate the signature. The string to sign will be something like this:

```
GET&http%3A%2F%2Flocal.wordpress.dev%2Fwp-json%2Fwc%2Fv2%2Forders%2F391&_method%3DPUT%26oauth_consumer_key%3DXXXXXXXX%26oauth_nonce%3D1%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1
```

The actual request method will be `GET`.

`_method` will be `PUT` and is positioned first alphabetically.

If you want to see what the API is signing and compare it to the string you're app is signing, add a var_dump in the `check_oauth_signature` method in core and it will show up in the response for debugging purposes ;)

https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

**Comment by steffanhalv** [comment]
@mikejolley Ok, thx But here is mine compared to yours:

**Your basestring:**
GET&
http
%3A%2F%2F
local.wordpress.dev%2F
wp-json%2F
wc%2F
v2%2F
orders%2F
391&
_method%3D
PUT%26
oauth_consumer_key%3DXXXXXXXX%26
oauth_nonce%3D1%26
oauth_signature_method%3DHMAC-SHA1%26
oauth_timestamp%3D1

raw:
`GET&http%3A%2F%2Flocal.wordpress.dev%2Fwp-json%2Fwc%2Fv2%2Forders%2F391&_method%3DPUT%26oauth_consumer_key%3DXXXXXXXX%26oauth_nonce%3D1%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1`


**My basestring:**
POST&
http%3A%2F%2F
localhost%3A9001%2F
wp-json%2F
wc%2F
v2%2F
products%2F
94&
_method%3D
PUT%26
name%3D
Airs6al%252520extreme%25252078%25252C5cc%252520D50B0%26
oauth_consumer_key%3Dck_XXX%26
oauth_nonce%3Dw03wgU%26
oauth_signature_method%3DHMAC-SHA1%26
oauth_timestamp%3D1495537482%26
oauth_version%3D1.0

raw:
`POST&http%3A%2F%2Flocalhost%3A9001%2Fwp-json%2Fwc%2Fv2%2Fproducts%2F94&_method%3DPUT%26name%3DAirs6al%252520extreme%25252078%25252C5cc%252520D50B0%26oauth_consumer_key%3Dck_XXX%26oauth_nonce%3Dw03wgU%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1495537482%26oauth_version%3D1.0`

And my signing key:
`cs_XXX&`

Hash created with:
`crypto.createHmac('sha1', signingKey).update(baseString).digest('base64')`

Request URL:
`http://localhost:9001/wp-json/wc/v2/products/94?_method=PUT&name=Airs6al%2520extreme%252078%252C5cc%2520D50B0&oauth_consumer_key=ck_18fc53cdbc2fca2acfb3303beb3f3aec0955a329&oauth_nonce=w03wgU&oauth_signature=JJc7THsPfi7MNyKU87EeJcFUoZM%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1495537482&oauth_version=1.0`

Request method:
`POST`

Request query string parameters:
```
_method:PUT
name:Airs6al%20extreme%2078%2C5cc%20D50B0
oauth_consumer_key:ck_18fc53cdbc2fca2acfb3303beb3f3aec0955a329
oauth_nonce:w03wgU
oauth_signature:JJc7THsPfi7MNyKU87EeJcFUoZM=
oauth_signature_method:HMAC-SHA1
oauth_timestamp:1495537482
oauth_version:1.0
```

So the difference is that I added the oauth_version:1.0 But if I do not add oauth_version it makes no difference.

Response:
`"Invalid signature - provided signature does not match."
Name
`

**Comment by mikejolley** [comment]
Compare the RAW to your RAW version before you encode it? If they match I don't understand how it can be a problem in the API itself

**Comment by steffanhalv** [comment]
Before encode:

**Yours:**
GET&http://local.wordpress.dev/wp-json/wc/v2/orders/391&_method=PUT&oauth_consumer_key=XXXXXXXX&oauth_nonce=1&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1

**Mine:**
POST&http://localhost:9001/wp-json/wc/v2/products/94&_method=PUT&name=Airs6al%2520extreme%252078%252C5cc%2520D50B0&oauth_consumer_key=ck_XXX&oauth_nonce=w03wgU&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1495537482&oauth_version=1.0

I cant find anything wrong with it and I dont have time to dive into the rest api code right now..

Currently im using my workaround as it works just fine. (Sending an options preflight request with oauth in params first and then another generated options request which is the actual request containg a new OAuth signature added to Authorization header)

A bit complicated, but I let you know if I find whats wrong later on.
