### ISSUE TITLE
ACF Conflicts with Woocommerce product variation

### ISSUE THREAD

**Issue by majekagriffin** [woocommerce/woocommerce#15229]
### EXPLANATION OF THE ISSUE

Woocommerce variations continuously spins when opened. This only occurs when advanced custom fields is in use. Wordpress version: 4.7.5
Woocommerce: 3.0.7
ACF: 5.3.9.1 

### STEPS TO REPRODUCE THE ISSUE

create a product, try to add attribute or variation and an it continuously spins

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://www.bhindbikinis.com
Site URL: http://www.bhindbikinis.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (cPanel) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 7.0.19
PHP Post Max Size: 128 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (18) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.3.9.1
Excel Like Price Change for WooCommerce and WP E-commerce - Light: by Holest Engineering – 2.1.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.10
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12
MailChimp for WordPress: by ibericode – 4.1.2
Meta Slider: by Matcha Labs – 3.5.1
Ninja Forms: by The WP Ninjas – 3.1.2
OKThemes Custom Post Types: by Gogoneata Cristian – 1.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Resize images before upload: by Simon @ WPsites – 1.8
Slider Revolution: by ThemePunch – 5.2.5.4
Simple 301 Redirects: by Scott Nellé – 1.07
Simple Google Analytics: by Jerome Meyer – 2.2.2
WooCommerce: by Automattic – 3.0.7
Yoast SEO: by Team Yoast – 4.8
WP SEO HTML Sitemap: by Magna Technology
LLC – 0.9.6

YITH WooCommerce Wishlist: by YITHEMES – 2.1.2
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.29

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #2996 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Voux WooCommerce Shopping Theme
Version: 2.3
Author URL: http://www.okthemes.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: voux/woocommerce/cart/cart-totals.php
voux/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
voux/woocommerce/checkout/form-checkout.php
voux/woocommerce/checkout/form-coupon.php
voux/woocommerce/checkout/form-login.php
voux/woocommerce/checkout/review-order.php
voux/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
voux/woocommerce/content-product_cat.php
voux/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
voux/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0
voux/woocommerce/loop/loop-end.php
voux/woocommerce/loop/loop-start.php
voux/woocommerce/myaccount/my-address.php
voux/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 3.0.0
voux/woocommerce/product-searchform.php
voux/woocommerce/single-product-reviews.php

Outdated Templates: ❌Learn how to update
`
```
</details>

**Comment by mikejolley** [comment]
ACF have been patching issues such as this and likely have an update (?) already. I cannot check because it's premium. Look at the ACF support site.

**Comment by omarbortolato** [comment]
Hi all, I have the same problem, the product variations don't work anymore. 
I have not ACF plugin installed.

`
### WordPress Environment ###

Home URL: http://new17.herbashop.it
Site URL: http://new17.herbashop.it
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: hs_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Il tuo negozio non utilizza HTTPS. Scopri di più su HTTPS e certificati SSL .
Hide errors from visitors: ✔

### Active Plugins (37) ###

PayPal Sandbox IPN Tester: by WooThemes – 1.0.0
LayerSlider WP: by Kreatura Media – 5.1.1
Ultimate Addons for Visual Composer: by Brainstorm Force – 3.1.0
Alligator Popup: by cubecolour – 1.2.0
Calculated Fields Form: by CodePeople – 1.0.163
Contact Form 7: by Takayuki Miyoshi – 4.8
Cookie Notice: by dFactory – 1.2.38
Coupon Pop widget for WP: by StoreYa – 1.1
Ditty News Ticker: by Metaphor Creations – 2.1.7
Duplicator: by Snap Creek – 1.2.8
Google Tag Manager for Wordpress: by Thomas Geiger – 1.6.1
EWWW Image Optimizer: by Shane Bishop – 3.4.1
Export User Data: by Q Studio – 1.3.1
WooCommerce shop to Facebook: by StoreYa – 2.4
Far Future Expiration Plugin: by Tips and Tricks HQ – 1.3
Formilla Live Chat: by Formilla.com – 1.1
FV Top Level Categories: by Foliovision – 1.8.2
Hello Bar (Official): by Hello Bar – 1.0
Hide Price Until Login: by CedCommerce – 1.0.8
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.2.3
MailChimp for WooCommerce: by MailChimp – 2.0.0
MailChimp per Wordpress: by ibericode – 4.1.5
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Peter's Login Redirect: by Peter Keung – 2.9.1
PixelYourSite: by PixelYourSite – 5.0.5.2
Quiz And Survey Master: by Frank Corso – 5.0.5
Conversio for WooCommerce: by Receiptful – 1.3.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Simple 301 Redirects: by Scott Nellé – 1.07
SEO by SQUIRRLY: by Squirrly SEO – 8.0.2
Testimonials Widget: by Axelerant – 3.4.2
Social Media and Share Icons (Ultimate Social Media): by UltimatelySocial – 1.7.4
Easy Tables (vc): by WPBakery – 1.0.2
Widget Logic: by wpchefgadget
alanft – 5.8.2

Woocommerce Shop Assistant: by cxThemes – 1.11
WooCommerce: by Automattic – 3.1.0
Yoast SEO: by Team Yoast – 5.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Carrello: #5 - /carrello/
Cassa: #6 - /checkout/
Il mio account: #7 - /mio-account/

### Theme ###

Name: Flatsome
Version: 3.3.7
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
