### ISSUE TITLE
Add new order: variation product titles missing attributes

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#15225]
This is probably related to the frontend change around when attributes are shown in the variation title or not, but I'm not sure if this is working correctly in the backend.

Create a new variable product, and give it one attribute with a single word as the attribute title: http://cld.wthms.co/JHdCl. Proceed to create variations and give each a price. Then add a new order and search for the product: http://cld.wthms.co/SdZRp. All is good so far.

Now go to the product and change the attribute name to be three words: http://cld.wthms.co/Dwd5u. Then save and re-assign attributes to the variations. Now no attributes show up here: http://cld.wthms.co/f0a1bw

The attribute title length definitely shouldn't be affecting whether or not attributes are shown in the backend. I'm not 100% sure, but I believe some other rules are also being taken into account on whether or not the attribute terms show here. In my opinions, terms should always show up here. Store owners could otherwise have a very hard time selecting a specific variation.

Edit: On a customer site in support, I found just this attribute/term combination causes them to not show up in the admin as well. I can replicate locally. `Colour Options` and `Black | Dark Blue | Dark Green | Light Blue | Light Green | Orange | Pink | Red | White | Yellow`

**Comment by mikejolley** [comment]
Any attribute name with multiple words is ignored from the naming logic to avoid situations where you have 'Something color' 'something else color' and names like - Black, Blue.

The admin view however should probably list them if possible so they are distinguishable. Will see if it's possible/performance issue.

**Comment by WPprodigy** [comment]
The attribute title length shouldn't matter at all here though. It doesn't show up, even if there are 2+ attributes: http://cld.wthms.co/N89HGD

So I'm thinking there might be a need for a secondary function to create these titles for the admin area product searches.

(Not completely related, but there is some weird behavior around if the variation title updates or not. Just saving the product doesn't do the trick. I'm finding you have to edit prices sometimes or recreate all variations. This does cause confusion when people try to use the `woocommerce_product_variation_title_include_attributes` filter. Clearing transients doesn't do it either afaik.)

**Comment by mikejolley** [comment]
@WPprodigy your comment part 2 see https://github.com/woocommerce/woocommerce/pull/15355 Variations only 'update' when data changes FYI

**Comment by mikejolley** [comment]
> The attribute title length shouldn't matter at all here though. It doesn't show up, even if there are 2+ attributes: http://cld.wthms.co/N89HGD

Rendering all attributes here won't be ideal as it will need to load and process all before display. Even the PR above is borderline too much but I cannot think of an alternative solution yet.

Listed variations do have IDs and can have SKUs if you need to distinguish many from one another. SKUs would be best - we're going to be pushing them more in future versions to ensure they are set.

If anything, we can revisit how the titles are generated,  but I'd like to do that after 3.1 after more feedback on the recent changes are implemented 👍
