### ISSUE TITLE
Product image doesn't change when clicking a swatch

### ISSUE THREAD

**Issue by kokiecosmetics** [woocommerce/woocommerce#15222]
### EXPLANATION OF THE ISSUE

the variation images won’t change on any of the products. In other words, if you click on the swatches for any variable product on our site, the main image should change to the corresponding color, but this does not happen. This issue must take priority over everything else, as soon as possible.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://kokiecosmetics.com
Site URL: https://kokiecosmetics.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.16 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.6.16
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_gfwc_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Gravity Forms: by rocketgenius – 2.2.2
LayerSlider WP: by Kreatura Media – 5.6.6
AJAX Thumbnail Rebuild: by junkcoder – 1.12
Autoptimize: by Frank Goossens (futtta) – 2.1.0
Backup by blogVault: by Backup by blogVault – 1.46
Simple Custom CSS and JS: by Diana Burduja – 3.1
Duplicator Pro: by Snap Creek – 3.0.15.2
EWWW Image Optimizer: by Shane Bishop – 3.3.1
Fusion Core: by ThemeFusion – 2.0.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.9
Instagram Slider Widget: by jetonr – 1.4.0
Lazy Load for Videos: by Kevin Weber – 2.2.3
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Really Simple SSL: by Rogier Lankhorst – 2.5.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Remove query strings from static resources: by Your WP Expert – 1.3.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.1

WooCommerce Custom Product Tabs Lite: by SkyVerge – 1.6.1
WooCommerce Dynamic Pricing: by Lucas Stark – 3.0.7
WooCommerce Multiple Free Gift: by Ankit Pokhrel – 1.2.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.14
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.1 – 1.11.2 is available
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.3
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.3
WooCommerce Volume Discount Coupons: by itthinx – 1.2.3
WooCommerce: by Automattic – 3.0.7
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.3.9
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.0.2
WP Fastest Cache: by Emre Vona – 0.8.6.9
WP Google Maps: by WP Google Maps – 6.4.03
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.0.1

WP Resized Image Quality: by Mike Bijon
Etch Software – 2.1.2

WP Smush: by WPMU DEV – 2.5.2
WP Super Minify: by Dipak C. Gajjar – 1.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

### WC Pages ###

Shop base: #16552 - /shop-full-width/
Cart: #16564 - /cart/
Checkout: #16586 - /checkout/
My account: #16576 - /my-account/

### Theme ###

Name: Avada
Version: 4.0.3
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 3.0.2
Avada/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 3.0.2
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌Learn how to update

</details>

**Comment by mikejolley** [comment]
Swatches is not part of core. I would say open a ticket https://woocommerce.com/contact-us/ but I suggest you test another theme **first** to ensure it's not just the custom gallery in Avada. They may have updates available.
