### ISSUE TITLE
Categories not shown in admin after adding woocommerce products via wp wc cli

### ISSUE THREAD

**Issue by w7089** [woocommerce/woocommerce#15220]
After the following script is run

    wp wc product create --name='b' --categories=32 --user=user

Output is printed:

    Success: Created product 1370.

But no categories are shown in wp-admin/WooCommerce->Products page for the newly added product.

I have followed [Find Product Category IDs][1] to get category id.
Tried to use [32], ['32'] instead of 32. The result is the same. Category is not shown in wordpress admin.
Seems like a bug.

  [1]: https://docs.woocommerce.com/document/find-product-category-ids/

**Comment by mikejolley** [comment]
Confirmed. Not sure how to deal with this one. CC'ing @justinshreve for ideas.

@justinshreve categories in the REST API are an object https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties How do we use those here?

**Comment by mikejolley** [comment]
Got it! Working example:

```
wp wc product create --name='b' --categories='[{"id":21}]' --user=admin
```

Updating the docs.

**Comment by mikejolley** [comment]
Added to FAQ https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Overview#frequently-asked-questions

**Comment by BKirev** [comment]
Can we use the name of the category/ies, instead of the ID?
Something like:
`wp wc product create --name='b' --categories='[{"name":"Category name"}]' --user=admin`

**Comment by 3ruce** [comment]
I think you have to use the ID not the text string...
