### ISSUE TITLE
Need a reply  for #13040 for WordPress Core team to fix core bug.

### ISSUE THREAD

**Issue by raykai** [woocommerce/woocommerce#15224]
Team at WP might need your input on the bug from ticket #13040 
 [https://github.com/woocommerce/woocommerce/issues/13040](url)

The place to reply for WordPress Core team is at the ticket that i opened with WordPress Core at https://core.trac.wordpress.org/ticket/40827#comment:3 

let's hope they can fix this bug without affecting WC to much.

**Comment by mikejolley** [comment]
Saw the comment.
