### ISSUE TITLE
woo offer

### ISSUE THREAD

**Issue by mon33x** [woocommerce/woocommerce#15230]
### EXPLANATION OF THE ISSUE

Hello, I wonder  how can I make when person click on product 'add to cart' that instead of it take him to cart that pop up a window that asks for email so we can make offer to him.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://statiprom.hr
Site URL: http://statiprom.hr
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: hr

### Server Environment ###

Server Info: Apache Phusion_Passenger/4.0.10 mod_bwlimited/1.4 mod_fcgid/2.3.9
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: Kako ažurirati vašu PHP verziju
PHP Post Max Size: 32 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.25
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wpwm_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Vaša trgovina ne koristi HTTPS. Saznajte više o HTTPS-u i SSL certifikatima.
Hide errors from visitors: ✔

### Active Plugins (12) ###

BackUpWordPress: od Human Made Limited – 3.6.3.1
Child Theme Configurator: od Lilaea Media – 2.2.4.1
Contact Form 7: od Takayuki Miyoshi – 4.7
Real-Time Find and Replace: od Marios Alexandrou – 3.9
Scroll Back to Top: od Joe Sexton – 1.1.3
Page Builder by SiteOrigin: od SiteOrigin – 2.5.3
SiteOrigin Widgets Bundle: od SiteOrigin – 1.8.6
ThemeGrill Demo Importer: od ThemeGrill – 1.3.2
Under Construction: od Noah Kagan – 1.18
WooCommerce: od Automattic – 3.0.7
Wordfence Security: od Wordfence – 6.3.9
YITH WooCommerce Compare: od YITHEMES – 2.2.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: HRK (Kn)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 3
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Osnova trgovine: #277 - /trgovina/
Košarica: #259 - /kosarica/
Blagajna: #260 - /narudzba/
Moj račun: #261 - /my-account/

### Theme ###

Name: Spacious Child
Version: 1.4.5.1492759012
Author URL: https://themegrill.com
Child Theme: ✔
Parent Theme Name: Spacious
Parent Theme Version: 1.4.6
Parent Theme Author URL: https://themegrill.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
Whilst I'm sure it's possible, Github is for bug reports, not custom development.
