### ISSUE TITLE
Please re-open the ticket 15092

### ISSUE THREAD

**Issue by olarionov** [woocommerce/woocommerce#15236]
EXPLANATION OF THE ISSUE

Testing version 3 on a local copy of a site, I think the only thing stopping me from updating the live site is the way backorder availability is notified on product pages. As previously raised, having a product in stock with backorder possible, and advising the customer that it is 'In stock (can be backordered)', is conflicting and sounds like it has to be backordered.

I preferred the way it was; when the low stock threshold was met the backorder advice was given (one of the points for having a low stock threshold). However if we must have this advice no matter how much stock there is, may I suggest we advise customers that 'more can be backordered'. By including 'more' we clearly say that the shop has stock and the ability to backorder more is an option if need be.

STEPS TO REPRODUCE THE ISSUE

Edit product.
Product data box > Inventory tab > Allow backorders? option.
Select drop-down list item 'Allow, but notify customer'.
View product page.

Thank you for your initial reply and all hard work you do to make WC better.
As per description of the issue in my ticket, I'd like to add this. To show the stock quantity on the product page is optional and configurable (which is excellent). Many stores are configured do not show stock QTY on the product page. So If I have only 1 or 2 items in stock and allow backorder, the stock message in WC 3.0.7 says "In stock (can be backordered)". As a customer, I can read it as this product "in stock as backordered" and need to wait longer for delivery (1 or more months), so I would not buy and move somewhere else. The customer must not see word "backorder" on a product page with items in stock. You will never find any online store that would do that, why you introduce this problem in WC3?. Try to find any online store based on Magento or other platform that will display word "backorder" in any variation of a sentence on a product page where a product is actualy in stock, this doesn't exist in the World. The only place we want to show that product of such QTY is on backorder during check-out if the customer ordered more that in stock. I have to hire PHP developer at $50/HR to wok on this issue and to revert it back as in WC2.6 in order to upgrade. Please don't introduce new feature like this if you never had a request from business that this is useful , at least make it optional or configurable. Make a simple checkbox for this new feature wording, so users can decide if they need it to use. PLEASE revert it back as it was in WC 2.6 to show only "In stock" phrase. Or make it configurable.

**Comment by mikejolley** [comment]
My answer is still valid and it's translatable so you CAN change it https://github.com/woocommerce/woocommerce/issues/15092#issuecomment-301712943
