### ISSUE TITLE
Woocommerce Coupons issue

### ISSUE THREAD

**Issue by Gowsalayadevi** [woocommerce/woocommerce#15241]
Hi,
I am using woo-commerce 2.4.2 version. I created a product coupon for a product. the coupon works completely fine when I am adding only that particular product in the cart. but if I add any other products, the discount is applying for all the products in the cart.

can some one give me the solution.

**Comment by mikejolley** [comment]
Sounds like a cart coupon, not a product coupon. But you're on a very old version so you'd need to replicate with 3.0 for us to look further.
