### ISSUE TITLE
Importer/Exporter progress bar style only on Chrome

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#15246]
Missing support for other browsers.

It's possible use [`::-moz-progress-bar` ](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-progress-bar) and [`::-ms-fill` ](https://developer.mozilla.org/en-US/docs/Web/CSS/::-ms-fill) as an alternative of `::-webkit-progress-value`.

The gradient in the background requires vendor prefixes as well.

**Comment by claudiulodro** [comment]
It looks good in Firefox and Safari to me. Only thing I saw that we should fix is FF has a blue progress bar instead of purple.

**Comment by claudiosanches** [comment]
All CSS only applies to `webkit` browsers, that's why is blue on Firefox.
