### ISSUE TITLE
Loop shop columns in 2.6.1+

### ISSUE THREAD

**Issue by chris-haigh** [woocommerce/woocommerce#15250]
In a new site i'm building using the latest version of WooCommerce, 3.0+ i've come to change the number of products in a row on the product category page only to realise the old method of using a filter on loop_shop_columns no longer works.

Is there a new method of doing this since 2.6.1 because i've noticed the code for this filter no longer exists in the template file for content-product.php. 

I can see in the CSS there is scope for having different columns by applying a class of "columns-3" for example to the body class, and i've done this and it works, but I wanted to know if there was a proper solution for it?

Cheers

Chris

**Comment by mikejolley** [comment]
Its still there as a default https://github.com/woocommerce/woocommerce/blob/8a22d416056af8b2e06dd4a464c5c8b69d466446/includes/wc-template-functions.php#L279
