### ISSUE TITLE
WooCommerce incorrectly count products in shop?

### ISSUE THREAD

**Issue by DrMTR** [woocommerce/woocommerce#15257]
I have upgraded Woo to latest version recently, and noticed one strange issue. In All Show 69 products but in published show 30 products. So from where woo count 30 products more i dont know. I checked for non published products for draft also, but dont see any product like that.

### STEPS TO REPRODUCE THE ISSUE

From admin panel ,click on Products, and see [this](http://i.imgur.com/QdkJpOd.png?1)

### SYSTEM STATUS

<details>

- WordPress environment
- Home URL:		https://www.favoriteboutique.co.uk
- Site URL:		https://www.favoriteboutique.co.uk
- WC version:		3.0.7
- Log directory writable:		 /home/limso/public_html/favoriteboutique.co.uk/wp-content/uploads/wc-logs/
- WP version:		4.7.5
- WP multisite:		–
- WP memory limit:		512 MB
- WP debug mode:		–
- WP cron:		
- Language:		en_GB
- Server environment
- Server info:		Apache/2.4.25
- PHP version:		5.6.30
- PHP post max size:		128 MB
- PHP time limit:		3000
- PHP max input vars:		1000
- cURL version:		7.36.0, OpenSSL/1.0.1e
- SUHOSIN installed:		–
- MySQL version:		5.6.35
- Max upload size:		128 MB
- Default timezone is UTC:		
- fsockopen/cURL:		
- SoapClient:		
- DOMDocument:		
- GZip:		
- Multibyte string:		
- Remote post:		
- Remote get:		
- Database
- WC database version:		3.0.7
- Database prefix	 	wp_
- woocommerce_sessions	 	
- woocommerce_api_keys	 	
- woocommerce_attribute_taxonomies	 	
- woocommerce_downloadable_product_permissions	 	
- woocommerce_order_items	 	
- woocommerce_order_itemmeta	 	
- woocommerce_tax_rates	 	
- woocommerce_tax_rate_locations	 	
- woocommerce_shipping_zones	 	
- woocommerce_shipping_zone_locations	 	
- woocommerce_shipping_zone_methods	 	
- woocommerce_payment_tokens	 	
- woocommerce_payment_tokenmeta	 	
- Security
- Secure connection (HTTPS):		
- Hide errors from visitors		
- Active plugins (31)
- Redux Framework	 	by Team Redux – 3.6.5
- Ultimate Addons for Visual Composer	 	by Brainstorm Force – 3.16.12
- CMB2	 	by WebDevStudios – 2.2.4
- Contact Form 7	 	by Takayuki Miyoshi – 4.7
- Cookie Notice	 	by dFactory – 1.2.38
- Dynamic Featured Image	 	by Ankit Pokhrel – 3.5.2
- Envato Market	 	by Derek Herman – 1.0.0-RC2
- XStore Core	 	by 8theme – 1.0.14
- Image Widget	 	by Modern Tribe, Inc. – 4.4.3
- WPBakery Visual Composer	 	by Michael M - WPBakery.com – 5.1.1
- Like 2 Discount	 	by Laborator – 1.3.1
- MailChimp for WordPress	 	by ibericode – 4.1.2
- Massive Addons for Visual Composer	 	by MassivePixelCreation – 2.2
- Responsive Coming Soon	 	by wpshopmart – 1.5.4
- Slider Revolution	 	by ThemePunch – 5.3.1.5
- WooCommerce Infinite Scroll and Ajax Pagination	 	by SB Themes – 1.1
- Smart Product Viewer	 	by topdevs – 1.4.6
- Subscriptio	 	by RightPress – 2.3.8
- Tawk.to Live Chat	 	by Tawkto – 0.2.9
- WooCommerce Currency Switcher	 	by realmag777 – 1.1.9
- WooCommerce PayPal Express Checkout Gateway	 	by WooCommerce – 1.2.1
- WooCommerce Zoomifier - The Ultimate Responsive WooCommerce Magnifier	 	by The WP Instinct Team – 1.7
- WooCommerce	 	by Automattic – 3.0.7
- WP Smush Pro	 	by WPMU DEV – 2.7.1
- WPMU DEV Dashboard	 	by WPMU DEV – 4.3
- GMAPS for Visual Composer	 	by WWP – 1.5
- MailPoet Newsletters	 	by MailPoet – 2.7.10
- YITH WooCommerce Ajax Product Filter	 	by YITHEMES – 3.4.1
- YITH WooCommerce Ajax Search	 	by YITHEMES – 1.5.2
- YITH WooCommerce Cart Messages	 	by YITHEMES – 1.2.0
- YITH WooCommerce Wishlist	 	by YITHEMES – 2.1.2
- Settings
- API enabled:		
- Force SSL:		–
- Currency		GBP (£)
- Currency position		left
- Thousand separator		,
- Decimal separator		.
- Number of decimals		2
- Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
- Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
- WC pages
- Shop base:		#207 - /shop/
- Basket:		#208 - /cart/
- Checkout:		#209 - /checkout/
- My account:		#210 - /my-account/
- Theme
- Name:		Xstore Child
- Version:		1.0
- Author URL:		http://8theme.com
- Child theme:		
- Parent theme name:		XStore
- Parent theme version:		3.14
- Parent theme author URL:		http://www.8theme.com
- WooCommerce support:		
- Templates
- Overrides	 	xstore/woocommerce/archive-product.php, 
- xstore/woocommerce/cart/cart-empty.php, 
- xstore/woocommerce/cart/cart-item-data.php, 
- xstore/woocommerce/cart/cart.php, 
- xstore/woocommerce/cart/cross-sells.php, 
- xstore/woocommerce/cart/mini-cart.php, 
- xstore/woocommerce/checkout/form-billing.php, 
- xstore/woocommerce/checkout/form-checkout.php, 
- xstore/woocommerce/checkout/form-shipping.php, 
- xstore/woocommerce/content-product.php, 
- xstore/woocommerce/content-product_cat.php, 
- xstore/woocommerce/content-single-product.php, 
- xstore/woocommerce/content-widget-product.php, 
- xstore/woocommerce/global/breadcrumb.php, 
- xstore/woocommerce/global/form-login.php, 
- xstore/woocommerce/global/wrapper-end.php, 
- xstore/woocommerce/global/wrapper-start.php, 
- xstore/woocommerce/loop/loop-end.php, 
- xstore/woocommerce/loop/loop-start.php, 
- xstore/woocommerce/loop/no-products-found.php, 
- xstore/woocommerce/loop/pagination.php, 
- xstore/woocommerce/loop/sale-flash.php, 
- xstore/woocommerce/single-product/add-to-cart/simple.php, 
- xstore/woocommerce/single-product/product-image.php, 
- xstore/woocommerce/single-product/product-thumbnails.php, 
- xstore/woocommerce/single-product/related.php, 
- xstore/woocommerce/single-product/sale-flash.php, 
- xstore/woocommerce/single-product/short-description.php, 
- xstore/woocommerce/single-product/tabs/additional-information.php, 
- xstore/woocommerce/single-product/tabs/description.php, 
- xstore/woocommerce/single-product/tabs/tabs.php, 
- xstore/woocommerce/single-product/title.php, 
- xstore/woocommerce/single-product/up-sells.php, 
- xstore/woocommerce/single-product.php

</details>

What i have do :
- Installed latest WooCommerce 3.0.7 atm.
- Recount products from System Status > Tools tab.

Without success. Any suggestion?

**Comment by mikejolley** [comment]
I'd expected that may be from a failed import. You'd need to look into the database to see what they are.
