### ISSUE TITLE
Mandatory fiels in checkout don't SEEM mandatory but are blocked by a '\'

### ISSUE THREAD

**Issue by icusrv** [woocommerce/woocommerce#15259]
### EXPLANATION OF THE ISSUE
When checking out items on my webshop, i select 'checkout as guest'.
On that page a '\' is written on the screen above the payment types.
When I don't fill in all obligate fields I don't receive an error message on the screen (via the code the message is available, but isn't showed because of the \ sign).

When I select a payment type now and click, next, then a JSON message appears concerning the \ sign.

ALSO Issue's with all plugins disabled except woocommerce and pronamic (my payment gateway...else i can't test it).

### STEPS TO REPRODUCE THE ISSUE
www.icuserver.nl
1. go to webshop
2. add a product to store
3. press checkout
4. press 'as guest'
(now you should see the '\' appear on left side of the screen)
5. don't fill in any obligate userdata + click on pay/proceed.
6. select payment type and there is the message.

### SYSTEM STATUS

<details>
Home-URL:		https://www.icuserver.nl
Site URL:		https://www.icuserver.nl
WC-versie:		3.0.7
Logmap beschrijfbaar:		 /home/icuserve/public_html/wp-content/uploads/wc-logs/
WP-versie:		4.7.5
WP Multisite:		–
WP geheugenlimiet:		256 MB
WP debug-modus:		–
WP Cron:		
Taal:		nl_NL
Serveromgeving
Serverinformatie:		Apache/2.4.23 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP-versie:		7.0.19
PHP post max size:		8 MB
PHP time limit:		30
PHP max input vars:		10000
cURL Versie:		7.36.0, OpenSSL/1.0.1e
SUHOSIN geïnstalleerd:		–
MySQL-versie:		 5.5.54 - Wij adviseren een minimum MySQL-versie 5.6. Bekijk: WordPress vereisten
Max upload size:		2 MB
Standaard tijdzone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC-databaseversie:		3.0.7
Prefix database	 	icunl
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP Database:		 /home/icuserve/public_html/wp-content/uploads/GeoIP.dat
Beveiliging
Beveiligde verbinding (HTTPS):		
Verberg fouten voor bezoekers		
Actieve plugins (2)
Pronamic betalen	 	door Pronamic – 4.6.0
WooCommerce	 	door Automattic – 3.0.7
Instellingen
API geactiveerd:		
Forceer SSL:		
Valuta		EUR (€)
Positie van valutasymbool		left_space
Duizendtalscheiding		,
Decimaalscheiding		.
Aantal decimalen		2
Taxonomieën: Producttypen		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomieën: productzichtbaarheid		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pagina's
Winkelbasis:		#558 - /winkel/
Winkelmand:		#559 - /winkelmand/
Afrekenen:		#560 - /afrekenen/
Mijn account:		#561 - /mijn-account/
Thema
Naam:		TheFox
Versie:		2.07
URL van de maker:		http://themeforest.net/user/tranmautritam?ref=tranmautritam
Subthema:		 – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt, raden we het gebruik van een subthema aan. Zie: Hoe maak je een subthema
WooCommerce Support:		
Templates
Overschrijvingen	 	thefox/woocommerce/archive-product.php, 
thefox/woocommerce/cart/cart-shipping.php, 
thefox/woocommerce/cart/cart.php, 
thefox/woocommerce/cart/cross-sells.php, 
thefox/woocommerce/cart/mini-cart.php, 
thefox/woocommerce/cart/shipping-calculator.php, 
thefox/woocommerce/checkout/form-billing.php, 
thefox/woocommerce/checkout/form-checkout.php, 
thefox/woocommerce/checkout/form-coupon.php, 
thefox/woocommerce/checkout/form-login.php, 
thefox/woocommerce/checkout/form-shipping.php, 
thefox/woocommerce/checkout/review-order.php, 
thefox/woocommerce/checkout/thankyou.php, 
thefox/woocommerce/global/quantity-input.php, 
thefox/woocommerce/myaccount/my-account.php, 
thefox/woocommerce/myaccount/my-address.php, 
thefox/woocommerce/order/order-details.php, 
thefox/woocommerce/single-product/product-image.php, 
thefox/woocommerce/single-product/product-thumbnails.php, 
thefox/woocommerce/single-product/related.php, 
thefox/woocommerce/single-product/short-description.php, 
thefox/woocommerce/single-product/tabs/tabs.php, 
thefox/woocommerce/single-product/up-sells.php, 
thefox/woocommerce/single-product-reviews.php, 
thefox/woocommerce/single-product.php
</details>

**Comment by mikejolley** [comment]
This is a custom checkout process (multi step). Core has a one page checkout. Therefore this is due to that customisation.
