### ISSUE TITLE
State validation is too strict

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce#15252]
### EXPLANATION OF THE ISSUE

In working on https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/262, I found out that they entered `"Act"` instead of `"ACT"` (might as well be coming from PayPal itself).

While there are no reproducible steps for that issue, this makes me think that there's an issue around https://github.com/woocommerce/woocommerce/blob/3.0.0/includes/class-wc-checkout.php#L633-L643.

### Investigation

@mikejolley, please have a look at the following code, and let me know your opinion:
```
<?php

function test_logic( $state ) {
        $valid_states = [
                'AL' => 'Alabama',
                'AK' => 'Alaska',
                'AZ' => 'Arizona',
        ];

        $valid_state_values = array_flip( array_map( 'strtolower', $valid_states ) );

        // Convert value to key if set
        if ( isset( $valid_state_values[ strtolower( $state ) ] ) ) {
                $state = $valid_state_values[ strtolower( $state ) ];
        }

        //                  ↓ should be strtoupper( $state )
        return in_array( $state, array_keys( $valid_states ) );
}       

var_dump( test_logic( 'aLaBaMa' ) ); // Good.
var_dump( test_logic( 'Alabama' ) ); // Good.
var_dump( test_logic( 'AL' ) ); // Good.
var_dump( test_logic( 'Al' ) ); // Bad.

/*
 output:
boro@bor0:~/dev/ext/woocommerce$ php test.php
/Users/boro/dev/ext/woocommerce/test.php:21:
bool(true)
/Users/boro/dev/ext/woocommerce/test.php:22:
bool(true)
/Users/boro/dev/ext/woocommerce/test.php:23:
bool(true)
/Users/boro/dev/ext/woocommerce/test.php:24:
bool(false)
boro@bor0:~/dev/ext/woocommerce$ 
*/
```

**Comment by mikejolley** [comment]
Looks like it may need to use upper instead of lower in that method. State codes are uppercase.

**Comment by bor0** [comment]
Agreed with @mikejolley that if we allow 'aLaBaMa', we should allow 'Al' as well (besides 'AL').

**Comment by lestaticon** [comment]
Same for our customers in Quebec, Canada. See the attached screenshot. Note that the customer's record has Quebec but the error references needing to have Québec.
![quebec](https://cloud.githubusercontent.com/assets/26077113/26403018/9b765592-405a-11e7-94e7-68b4d2c914be.jpg)

**Comment by bor0** [comment]
@lestaticon can you please file a different issue for that?

**Comment by julienouellette** [comment]
I have the same issue here, from Québec.

**Comment by sonatech25** [comment]
i have also same issue paypal is not working because of state validation please let me know if any one get the solution
