### ISSUE TITLE
Cyprus Missing From Shipping Zone Country List

### ISSUE THREAD

**Issue by AntBentinck** [woocommerce/woocommerce#15254]
### EXPLANATION OF THE ISSUE

We are trying to setup shipping zones for the EU and unfortunately we cannot find Cyprus on the list.

### STEPS TO REPRODUCE THE ISSUE

Look for Cyprus

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.e-liquids.uk
Site URL: https://www.e-liquids.uk
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: nginx/1.10.2
PHP Version: 7.0.19
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: eluk
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (68) ###

VaultPress: by Automattic – 1.8.9
AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.1.7
AffiliateWP - Pushover Notifications: by Chris Klosowski – 1.0.2
AffiliateWP: by AffiliateWP
LLC – 2.0.9.1

AffiliateWP - Affiliate Dashboard Sharing: by Pippin Williamson and Andrew Munro – 1.1.3
AffiliateWP - Affiliate Info: by Pippin Williamson and Andrew Munro – 1.0.3
AffiliateWP - Affiliate Product Rates: by Pippin Williamson and Andrew Munro – 1.0.4
AffiliateWP - Checkout Referrals: by AffiliateWP – 1.0.4
AffiliateWP - Custom Affiliate Slugs: by Pippin Williamson and Andrew Munro – 1.0
AffiliateWP - Direct Link Tracking: by AffiliateWP – 1.1
AffiliateWP - Order Details For Affiliates: by AffiliateWP – 1.1.3
AffiliateWP - Signup Referrals: by Pippin Williamson and Andrew Munro – 1.0.1
AffiliateWP - Store Credit: by AffiliateWP Team – 2.1.2
AffiliateWP - Tiered Rates: by AffiliateWP – 1.1
AffiliateWP - WooCommerce Redirect Affiliates: by Pippin Williamson and Andrew Munro – 1.0
Aimtell Push Notifications: by Aimtell – 1.5
CategoryTinymce: by Kevin Heath – 3.6.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.1.10
Imagify: by WP Media – 1.6.4
Jetpack by WordPress.com: by Automattic – 4.9
MailChimp for WooCommerce: by MailChimp – 2.0.0
Manage Notification E-mails: by Virgial Berveling – 1.3.0
Max Mega Menu - Pro Addon: by Tom Hemsley – 1.6.2.1
Max Mega Menu: by Tom Hemsley – 2.3.6
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Ninja Forms: by The WP Ninjas – 3.1.2
Woocommerce Onsale Page: by wpgenie – 1.0.9
Postman SMTP: by Jason Hendriks – 1.7.2
Product/Review CSV Import Export: by HikeForce – 3.2.1
SVG Support: by Benbodhi – 2.3.8
Taxonomy Metadata: by mitcho (Michael Yoshitaka Erlewine)
sirzooro – 0.5

Veeqo for WooCommerce: by Veeqo – 1.0.3
WooCommerce Bulk Edit Product Variations: by matterico_themes – 2.6
Woocommerce Variations Table - Grid: by Spyros Vlachopoulos – 1.3.6
WooCommerce Payment Gateway Based Fees: by WooThemes – 3.0.2
WooCommerce Address Validation: by SkyVerge – 2.1.0
WooCommerce Advanced Review Reminder: by kodemann.com – 2.2
WooCommerce Create Customer on Order: by cxThemes – 1.33
WooCommerce Currency Switcher: by realmag777 – 2.1.9
WooCommerce - Estimated Dispatch Date: by Cuzzy – 2.4.6
WooCommerce Email Customizer: by cxThemes – 3.10
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.1
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.7
WooCommerce Help Scout: by WooCommerce – 1.3.3
OneSaas Connect: by OneSaas – 2.0.6.34
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 1.4.2
WooCommerce Points and Rewards: by WooCommerce – 1.6.3
WooCommerce Shop as Customer: by cxThemes – 2.10
WooCommerce Store Credit: by WooCommerce – 2.1.7
WooCommerce Table Rate Shipping: by Bolder Elements – 4.0.1
WooWaitlist: by WPCream.com – 4.0.3
WooCommerce: by Automattic – 3.0.7
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO Premium: by Team Yoast – 4.8
WP Instagram Widget: by Scott Evans – 1.9.8
WP Rocket: by WP Media – 2.10-beta4
Yoast SEO: WooCommerce: by Team Yoast – 4.8
WP Stagecoach: by WP Stagecoach – 1.3.6
YITH Infinite Scrolling Premium: by YITHEMES – 1.1.0
YITH Topbar Countdown: by YITHEMES – 1.1.0
YITH WooCommerce Ajax Search: by YITHEMES – 1.5.2
YITH WooCommerce Badge Management Premium: by YITHEMES – 1.3.3
YITH WooCommerce Cart Messages Premium: by YITHEMES – 1.4.0
YITH WooCommerce Dynamic Pricing and Discounts Premium: by YITHEMES – 1.2.5
YITH WooCommerce Popup: by YITHEMES – 1.1.1
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
lottery (lottery)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /shop
Basket: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My account: #10 - /my-account

### Theme ###

Name: E-LIQUIDS-UK
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.5
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/906b7dbf10eba9da49c1abe24bf5668bdc99f030/i18n/countries.php#L77

https://dl.dropboxusercontent.com/s/ng5tz235iajpjb0/2017-05-24%20at%2012.37.png
