### ISSUE TITLE
WooCommerce Customer List Issue

### ISSUE THREAD

**Issue by deskroid** [woocommerce/woocommerce#15258]
### EXPLANATION OF THE ISSUE

The customer list under WooCommerce > Reports > Customers shows all the active WordPress users with all user-roles. I think only users with the user-role `customer` should be shown here.

![Screenshot](https://d1zjcuqflbd5k.cloudfront.net/files/acc_547844/bKd4k?response-content-disposition=inline;%20filename=Screen%20Shot%202017-05-24%20at%2018.16.28.png&Expires=1495630571&Signature=ZI-GjAkljbTadzUHHVIV-Fxl-IoOL0EFTs~ewbFCH8NIJC4xVOrNLHyFjC5VjeCq85xjI8qKf5sPdEWOU9qLAeGMKiKNENfCJxl5EHaMdKGxbnYR-f8HRVIAjKVtnjK-eMWrbST0gRntyxy5paleaipyPqaCWiZ1AekDEhcohGw_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

### STEPS TO REPRODUCE THE ISSUE

1. Navigate to WooCommerce > Reports > Customers > Customer List.
2. This section shows up all the WordPress users, many of them having placed no orders, along with the customers. 

### SYSTEM STATUS

<details>

`
### WordPress Environment ###

Home URL: https://rusticartistry.com
Site URL: https://rusticartistry.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (23) ###

Akismet Anti-Spam: by Automattic – 3.3.2
Disable REST API: by Dave McHale – 1.3
Envato WordPress Toolkit: by Envato – 1.7.3
Eggplant 301 Redirects: by Shawn Wernig http://www.eggplantstudios.ca – 2.3.0
GTmetrix for WordPress: by GTmetrix – 0.4.2
Header and Footer Scripts: by Anand Kumar – 1.3.4
Heartbeat Control: by Jeff Matson – 1.0.3
PHP Compatibility Checker: by WP Engine – 1.4.0
Code Insert Manager (Q2W3 Inc Manager): by Max Bond – 2.3.3
SSL Insecure Content Fixer: by WebAware – 2.2.3
SumoMe: by SumoMe – 1.25
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.2.7

WooCommerce Export Customer Email: by MH Mithu – 1.3
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.6
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Product Add-ons: by WooCommerce – 2.8.1
WooCommerce Shipping Per Product v2: by WooThemes – 2.2.8
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
Yoast SEO: by Team Yoast – 4.6
WP Smush: by WPMU DEV – 2.6.3
WPSEO Pinterest Rich Pins for WooCommerce: by Jonathan Christopher – 0.1.1
YITH WooCommerce Ajax Search: by YITHEMES – 1.5.2

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #4463 - /shop/
Cart: #4001 - /cart/
Checkout: #4005 - /checkout/
My Account: #4524 - /account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.2.2
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php version - is out of date. The core version is 2.5.0
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

: Learn how to update outdated templates
`
</details>

**Comment by mikejolley** [comment]
Any user can place an order on a store; not all stores use the customer role for everything.

**Comment by mikejolley** [comment]
Since this may be used by people, or be used on stores with other roles (membership sites for example), this should be left as is.
