### ISSUE TITLE
Coupon usage not clickable

### ISSUE THREAD

**Issue by seacucumberinc** [woocommerce/woocommerce#15265]
After upgrade to woocommerence 3.0.7 the coupon usage counter number not clickable--it used to be able to click and then will show this coupon code be used in how many orders!

### STEPS TO REPRODUCE THE ISSUE

under coupon --- Usage/Limit

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://haishentianxia.com
Site URL: http://haishentianxia.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18
PHP Post Max Size: 128 MB
PHP Time Limit: -1
PHP Max Input Vars: 4000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp1b1x5f6m_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (40) ###

PW Advanced WooCommerce Order Status & Actions Manager: by Proword – 1.0
Templatemela Custom Post: by Templatemela – 1.0
Templatemela Meta Box: by Templatemela – 1.0
Templatemela Shortcodes: by Templatemela – 1.0
Templatemela SlideShow: by Templatemela – 1.0
All-in-One WP Migration FTP Extension: by ServMask – 2.21
All-in-One WP Migration: by ServMask – 6.45
Baidu Sitemap Generator: by 柳城 – 1.6.5
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

Under Construction / Maintenance Mode From Acurax: by Acurax – 2.5.3
File Manager: by  – 4.1.5
Form Maker: by WebDorado Form Builder Team – 1.11.4
WooCommerce Group Buy: by wpgenie – 1.1.1
Inactive Logout: by Deepen Bajracharya – 1.4.6
MailPoet WooCommerce Add-on: by Sébastien Dumont – 3.0.2
NihaoPay Gateway for WooCommerce: by nihaopay – 1.0.0
Password Strength for WooCommerce: by Potent Plugins – 1.0.1
Google Analytics for WordPress: by praveenchauhan1984 – 1.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slideshow: by StefanBoonstra – 2.3.1
WooCommerce Dynamic Pricing & Discounts: by RightPress – 1.1.2
WooCommerce Weight Based Shipping +: by dangoodman – 4.1.4
WeChatPay For WooCommerce: by Shudong Zhu – 1.0
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 3.7
WooCommerce Min/Max Quantities: by WooCommerce – 2.3.16
WooCommerce PDF Invoices: by Bas Elbers – 2.9.1
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.2
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.15
WooCommerce Stock Manager: by Vladislav Musílek – 1.1.4
WooCommerce: by Automattic – 3.0.7
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.8
WP All Export Pro: by Soflyy – 1.4.6
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.91
WPS Hide Login: by Remy Perona for WPServeur – 1.1.7
MailPoet Newsletters Premium: by MailPoet – 2.7.8
MailPoet Newsletters: by MailPoet – 2.7.10
海参天下佣金推广插件-请勿删除: by 刘浩 – 1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
groupbuy (groupbuy)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Branchy
Version: 1.0
Author URL: http://www.templatemela.com
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: WCM010020/woocommerce/archive-product.php
WCM010020/woocommerce/content-product.php
WCM010020/woocommerce/global/wrapper-start.php
WCM010020/woocommerce/loop/loop-start.php
WCM010020/woocommerce/single-product/short-description.php

`
</details>

**Comment by mikejolley** [comment]
This was a search field but was not accurate. We will reintroduce it when https://github.com/woocommerce/woocommerce/issues/13570 is added.
