### ISSUE TITLE
assets/admin/quick-edit.js custom product types

### ISSUE THREAD

**Issue by nikolastheologos** [woocommerce/woocommerce#15261]
### EXPLANATION OF THE ISSUE
When you create a custom product type WooCommerce doesn't allow you to edit regular and sale prices from quick edit button. I've checked your code here:

assets/admin/quick-edit.js in line 74 and you write

```
if ( 'simple' === product_type || 'external' === product_type ) {
	$( '.price_fields', '.inline-edit-row' ).show().removeAttr( 'style' );
} else {
	$( '.price_fields', '.inline-edit-row' ).hide();
}
```

What about custom product types? Do you have any plans on changing this part of code in order to allow quick editing of custom product types?

### STEPS TO REPRODUCE THE ISSUE

1. Create a custom product type
2. In admin product list press quick edit for this product type you will see that price fields are hidden

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
No plans to handle this, but you could use JS to handle your custom types. If you need an extra trigger event to do this, please raise a PR.
