### ISSUE TITLE
Changes in the order item meta array format

### ISSUE THREAD

**Issue by ChaseWiseman** [woocommerce/woocommerce#15267]
### EXPLANATION OF THE ISSUE

As of v3.0.x, getting the meta array for an order item via `$item['item_meta_array']` will only return the last meta value in a set of meta rows with the same key. This seems to be due to a change in the array format, where now each array key is set as the `meta_key` value instead of meta ID: https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/class-wc-order-item.php#L298

This results in `WC_Order_Item_Meta::display()` only displaying a single meta entry when there may be many with the same key. This is most apparent when trying to display the meta set by Product Add-ons when using a global checkbox add-on with multiple options, since they store each option with the same meta key.

### STEPS TO REPRODUCE THE ISSUE

1. Add some custom meta to an order item, all with the same `meta_key`
2. Try and display or log the item meta using `WC_Order_Item_Meta::display()`. Only one will be available.
3. Downgrade to WC 2.6.x and see that all are displayed

### SYSTEM STATUS

Only WooCommerce 3.0.7

**Comment by mikejolley** [comment]
Ref https://github.com/woocommerce/woocommerce/blob/2.6.0/includes/abstracts/abstract-wc-order.php#L1407
