### ISSUE TITLE
Can not access Woocommerce Settings, what's the problem?

### ISSUE THREAD

**Issue by vecodo** [woocommerce/woocommerce#15270]
### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by vecodo** [comment]
`
### WordPress Environment ###

Home URL: https://www.listadeo.com/multistore
Site URL: https://www.listadeo.com/multistore
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: es_ES

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.10
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.31
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (44) ###

All In One SEO Pack: por Michael Torbert – 2.3.12.5
BulkPress: por Jesper van Engelen – 0.3.5
Code Snippets: por Shea Bunge – 2.8.6
Facebook for WooCommerce: por Facebook – 1.3.0
Homepage Control: por WooThemes – 2.0.2
Loco Translate: por Tim Whitlock – 2.0.14
MailChimp for WooCommerce: por MailChimp – 2.0.0
Storefront Footer Bar: por WooThemes – 1.0.3
Storefront Hamburger Menu: por WooThemes – 1.2.0
Storefront Powerpack: por WooThemes – 1.3.1 – 1.4.0 está disponible
Storefront Product Pagination: por WooThemes – 1.2.1
Storefront Product Sharing: por WooThemes – 1.0.3
Storefront Sticky Add to Cart: por WooThemes – 1.1.6
Storefront Top Bar: por Wooassist – 1.1.1
W3 Total Cache: por Frederick Townes – 0.9.5.4
Woo Mercado Pago Module: por Mercado Pago – 2.2.6
WooCommerce Advanced Product Labels: por Jeroen Sormani – 1.1.1
Woocommerce Marcas: por WooThemes – 1.5.0
WooCommerce Distance Rate Shipping: por Automattic – 1.0.5 – 1.0.6 está disponible
WooCommerce Anuncios de precios mínimos: por SkyVerge – 1.8.0
WooCommerce Nested Category Layout: por SkyVerge – 1.10.0
WooCommerce Formulario de consulta de producto: por WooThemes – 1.2.1
WooCommerce Product Finder: por WooThemes – 1.2.1
WooCommerce Product Reviews Pro: por SkyVerge – 1.8.0 – 1.8.1 está disponible
WooCommerce Product Search: por itthinx – 1.9.0
WooCommerce Product Vendors: por WooCommerce – 2.0.30
WooCommerce Products Of The Day: por WooThemes – 1.1.4
WooCommerce Quantity Increment: por Automattic
WooThemes – 1.1.0

WooCommerce Shipment Tracking: por WooCommerce – 1.6.6
WooCommerce Local Pickup Plus: por SkyVerge – 1.14.0 – 1.14.1 está disponible
WooCommerce Shipping Per Product v2: por WooThemes – 2.2.8
WooCommerce Shortcodes: por WooThemes
Claudio Sanches – 1.0.0

Ingreso Social de WooCommerce: por SkyVerge – 2.1.0 – 2.2.1 está disponible
WooCommerce Splash Popup: por WooThemes – 1.2.1
WooCommerce Subscribe to Newsletter: por WooCommerce – 2.3.6
WooCommerce Tabla de Tarifas de Envío: por WooCommerce – 3.0.3
WooCommerce Waitlist: por Neil Pie – 1.5.4
WooCommerce WishLists: por Lucas Stark – 2.0.5
WooCommerce: por Automattic – 3.0.7
WooCommerce Helper: por WooCommerce – 1.7.2 – Red habilitado
WP-Optimize: por David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

YITH WooCommerce Featured Audio and Video Content: por YITHEMES – 1.1.10
YITH WooCommerce Quick View Premium: por YITHEMES – 1.2.2
YITH WooCommerce Zoom Magnifier Premium: por YITHEMES – 1.2.22

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ARS ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base de la tienda: #4 - /tienda/
Carrito: #5 - /carrito/
Finalizar compra: #6 - /finalizar-compra/
Mi cuenta: #7 - /mi-cuenta/

### Theme ###

Name: Storefront
Version: 2.1.8 – 2.2.3 está disponible
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: : Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
This issue is lacking details like how to reproduce, and does not appear to have followed steps on the new issue form.

```
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
```
