### ISSUE TITLE
Variations are no longer loading on Wordpress Admin

### ISSUE THREAD

**Issue by atlanticfurniture** [woocommerce/woocommerce#15279]
### EXPLANATION OF THE ISSUE

I went in to a variation product parent. Clicked on Variations tab, and I just get the ajax spinner image without anything loading. This is the error message I get in the inspector:

JQMIGRATE: Migrate is installed, version 1.4.1  load-scripts.php:9:542
Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
Stack trace:
c<.prepareOpts/<@https://www.atlanticfurniture.com/wp-content/plugins/advanced-custom-fields-pro/assets/inc/select2/select2.min.js?ver=5.3.0:21:22578
.each@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:2879
c<.prepareOpts@https://www.atlanticfurniture.com/wp-content/plugins/advanced-custom-fields-pro/assets/inc/select2/select2.min.js?ver=5.3.0:21:22457
e<.prepareOpts@https://www.atlanticfurniture.com/wp-content/plugins/advanced-custom-fields-pro/assets/inc/select2/select2.min.js?ver=5.3.0:22:17924
c<.init@https://www.atlanticfurniture.com/wp-content/plugins/advanced-custom-fields-pro/assets/inc/select2/select2.min.js?ver=5.3.0:21:17968
a.fn.select2/<@https://www.atlanticfurniture.com/wp-content/plugins/advanced-custom-fields-pro/assets/inc/select2/select2.min.js?ver=5.3.0:22:30933
.each@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:2879
n.prototype.each@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:844
a.fn.select2@https://www.atlanticfurniture.com/wp-content/plugins/advanced-custom-fields-pro/assets/inc/select2/select2.min.js?ver=5.3.0:22:30618
@https://www.atlanticfurniture.com/wp-content/plugins/woocommerce/assets/js/admin/wc-enhanced-select.min.js?ver=3.0.7:1:2241
.each@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:2879
n.prototype.each@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:844
@https://www.atlanticfurniture.com/wp-content/plugins/woocommerce/assets/js/admin/wc-enhanced-select.min.js?ver=3.0.7:1:1472
n.event.dispatch@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:3:12392
n.event.add/r.handle@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:3:9156
n.event.trigger@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:3:11571
a.event.trigger@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:9:8273
.trigger/<@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:3:18983
.each@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:2879
n.prototype.each@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:844
.trigger@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:3:18962
@https://www.atlanticfurniture.com/wp-content/plugins/woocommerce/assets/js/admin/wc-enhanced-select.min.js?ver=3.0.7:1:896
n.Callbacks/i@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:27444
n.Callbacks/j.fireWith@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:28213
.ready@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:30004
K@https://www.atlanticfurniture.com/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,underscore,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable,jquery-ui-positio&load%5B%5D=n,jquery-ui-menu,wp-a11y,jquery-ui-autocomplete,backbone,wp-util,wp-backbone,media-models,plupload,jquery-ui-resizable&ver=4.7.5:2:30366
  wc-enhanced-select.min.js:1:4298
downloadable font: rejected by sanitizer (font-family: "dashicons" style:normal weight:normal stretch:normal src index:0) source: https://www.atlanticfurniture.com/wp-includes/fonts/dashicons.eot  load-styles.php:1:11
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!  post.php
n.default.defaultView.getComputedStyle(...) is null  E-v1.js:398:1677
a@https://src.litix.io/core/2/mux.js:7:28766
a/i.getStateData@https://src.litix.io/core/2/mux.js:8:2162
[16]</V.prototype.updateStateData@https://src.litix.io/core/2/mux.js:7:25330
[16]</V/<@https://src.litix.io/core/2/mux.js:7:23260
[5]</a.prototype.emit/o/<@https://src.litix.io/core/2/mux.js:7:4886
[5]</a.prototype.emit/o@https://src.litix.io/core/2/mux.js:7:4864
[5]</a.prototype.emit@https://src.litix.io/core/2/mux.js:7:4917
[16]</V@https://src.litix.io/core/2/mux.js:7:24814
[15]</t.exports</a.init@https://src.litix.io/core/2/mux.js:7:18779
a@https://src.litix.io/core/2/mux.js:8:3225
[15]</t.exports</a.monitor@https://src.litix.io/core/2/mux.js:7:18466
e.mux.setup/</t@https://fast.wistia.net/assets/external/E-v1.js:1637:2706
e.mux.setup/</u@https://fast.wistia.net/assets/external/E-v1.js:1637:2922
StopGo</t.prototype.flush/</<@https://fast.wistia.net/assets/external/E-v1.js:398:820
StopGo</t.prototype.tryAndReport@https://fast.wistia.net/assets/external/E-v1.js:398:1599
StopGo</t.prototype.flush@https://fast.wistia.net/assets/external/E-v1.js:398:765
StopGo</t.prototype.runFn@https://fast.wistia.net/assets/external/E-v1.js:398:2704
StopGo</t.prototype.run@https://fast.wistia.net/assets/external/E-v1.js:398:2501
StopGo</t.prototype._allInOne@https://fast.wistia.net/assets/external/E-v1.js:398:3340
t/this.allInOne</<@https://fast.wistia.net/assets/external/E-v1.js:398:160
e.mux.setup/</</</<@https://fast.wistia.net/assets/external/E-v1.js:1637:3499
doTimeout/a<@https://fast.wistia.net/assets/external/E-v1.js:156:556
  E-v1.js:398:1744
XML Parsing Error: no root element found
Location: https://distillery.wistia.com/x
Line Number 1, Column 1:  x:1:1
Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.  select2.min.js:21:22578

### STEPS TO REPRODUCE THE ISSUE

Login to WP admin.
Click on Products.
Choose to edit a product.
Click on variations tab.
The image just keeps spinning, and the variations do not load.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.atlanticfurniture.com
Site URL: https://www.atlanticfurniture.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_ssl/2.2.31 OpenSSL/1.0.1e-fips DAV/2 mod_bwlimited/1.4
PHP Version: 5.6.29
PHP Post Max Size: 8 MB
PHP Time Limit: 720
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Advanced Custom Fields Pro: by elliot condon – 5.3.0
Akismet Anti-Spam: by Automattic – 3.3.2
Contact Form 7: by Takayuki Miyoshi – 4.7
Custom Related Products for WooCommerce: by Scott Nelle – 1.3
Dynamic Widgets: by Qurl – 1.5.12
Facebook for WooCommerce: by Facebook – 1.3.0
Google Sitemap by BestWebSoft: by BestWebSoft – 3.0.9
MailChimp for WordPress: by ibericode – 4.1.2
Really Simple CAPTCHA: by Takayuki Miyoshi – 1.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Page Builder by SiteOrigin: by SiteOrigin – 2.5.3
Smart Manager: by StoreApps – 3.9.21
SiteOrigin Widgets Bundle: by SiteOrigin – 1.8.6
Under Construction: by Web factory Ltd – 2.10
WooCommerce Accordions: by Magnigenie – 1.0
WooCommerce PayTrace Payment Gateway: by VanboDevelops – 1.4.5 – 1.4.8 is available
WooCommerce PDF & Print: by gVectors Team – 1.5.0
WooCommerce Product Categories Selection: by PluginForage.com – 2.0
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.14
WooCommerce Shipment Tracking: by WooCommerce – 1.6.6
WooCommerce UPS Shipping: by WooCommerce – 3.2.3
WooCommerce Stock Manager: by Vladislav Musílek – 1.1.4
WooCommerce Upsells Widget: by SkyVerge – 1.0.1
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.3
WooCommerce Warranty & Return System: by Mojoomla – 2.0
WooCommerce: by Automattic – 3.0.7
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.8
WP htaccess Control: by António Andrade – 3.5.1
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.29
Zendesk Chat Widget: by Zopim – 1.4.10

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Atlantic Furniture
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: atlanticfurniture/woocommerce/archive-product.php
atlanticfurniture/woocommerce/auth/footer.php
atlanticfurniture/woocommerce/auth/form-grant-access.php
atlanticfurniture/woocommerce/auth/form-login.php
atlanticfurniture/woocommerce/auth/header.php
atlanticfurniture/woocommerce/cart/cart-empty.php
atlanticfurniture/woocommerce/cart/cart-item-data.php
atlanticfurniture/woocommerce/cart/cart-shipping.php
atlanticfurniture/woocommerce/cart/cart-totals.php
atlanticfurniture/woocommerce/cart/cart.php
atlanticfurniture/woocommerce/cart/cross-sells.php
atlanticfurniture/woocommerce/cart/mini-cart.php
atlanticfurniture/woocommerce/cart/proceed-to-checkout-button.php
atlanticfurniture/woocommerce/cart/shipping-calculator.php
atlanticfurniture/woocommerce/checkout/cart-errors.php
atlanticfurniture/woocommerce/checkout/form-billing.php
atlanticfurniture/woocommerce/checkout/form-checkout.php
atlanticfurniture/woocommerce/checkout/form-coupon.php
atlanticfurniture/woocommerce/checkout/form-login.php
atlanticfurniture/woocommerce/checkout/form-pay.php
atlanticfurniture/woocommerce/checkout/form-shipping.php
atlanticfurniture/woocommerce/checkout/payment-method.php
atlanticfurniture/woocommerce/checkout/payment.php
atlanticfurniture/woocommerce/checkout/review-order.php
atlanticfurniture/woocommerce/checkout/terms.php
atlanticfurniture/woocommerce/checkout/thankyou.php
atlanticfurniture/woocommerce/content-product.php
atlanticfurniture/woocommerce/content-product_cat.php
atlanticfurniture/woocommerce/content-single-product.php
atlanticfurniture/woocommerce/content-widget-product.php
atlanticfurniture/woocommerce/emails/admin-cancelled-order.php
atlanticfurniture/woocommerce/emails/admin-failed-order.php
atlanticfurniture/woocommerce/emails/admin-new-order.php
atlanticfurniture/woocommerce/emails/customer-completed-order.php
atlanticfurniture/woocommerce/emails/customer-invoice.php
atlanticfurniture/woocommerce/emails/customer-new-account.php
atlanticfurniture/woocommerce/emails/customer-note.php
atlanticfurniture/woocommerce/emails/customer-on-hold-order.php
atlanticfurniture/woocommerce/emails/customer-processing-order.php
atlanticfurniture/woocommerce/emails/customer-refunded-order.php
atlanticfurniture/woocommerce/emails/customer-reset-password.php
atlanticfurniture/woocommerce/emails/email-addresses.php
atlanticfurniture/woocommerce/emails/email-customer-details.php
atlanticfurniture/woocommerce/emails/email-footer.php
atlanticfurniture/woocommerce/emails/email-header.php
atlanticfurniture/woocommerce/emails/email-order-details.php
atlanticfurniture/woocommerce/emails/email-order-items.php
atlanticfurniture/woocommerce/emails/email-styles.php
atlanticfurniture/woocommerce/emails/plain/admin-cancelled-order.php
atlanticfurniture/woocommerce/emails/plain/admin-failed-order.php
atlanticfurniture/woocommerce/emails/plain/admin-new-order.php
atlanticfurniture/woocommerce/emails/plain/customer-completed-order.php
atlanticfurniture/woocommerce/emails/plain/customer-invoice.php
atlanticfurniture/woocommerce/emails/plain/customer-new-account.php
atlanticfurniture/woocommerce/emails/plain/customer-note.php
atlanticfurniture/woocommerce/emails/plain/customer-on-hold-order.php
atlanticfurniture/woocommerce/emails/plain/customer-processing-order.php
atlanticfurniture/woocommerce/emails/plain/customer-refunded-order.php
atlanticfurniture/woocommerce/emails/plain/customer-reset-password.php
atlanticfurniture/woocommerce/emails/plain/email-addresses.php
atlanticfurniture/woocommerce/emails/plain/email-customer-details.php
atlanticfurniture/woocommerce/emails/plain/email-order-details.php
atlanticfurniture/woocommerce/emails/plain/email-order-items.php
atlanticfurniture/woocommerce/global/breadcrumb.php
atlanticfurniture/woocommerce/global/form-login.php
atlanticfurniture/woocommerce/global/quantity-input.php
atlanticfurniture/woocommerce/global/sidebar.php
atlanticfurniture/woocommerce/global/wrapper-end.php
atlanticfurniture/woocommerce/global/wrapper-start.php
atlanticfurniture/woocommerce/loop/add-to-cart.php
atlanticfurniture/woocommerce/loop/loop-end.php
atlanticfurniture/woocommerce/loop/loop-start.php
atlanticfurniture/woocommerce/loop/no-products-found.php
atlanticfurniture/woocommerce/loop/orderby.php
atlanticfurniture/woocommerce/loop/pagination.php
atlanticfurniture/woocommerce/loop/price.php
atlanticfurniture/woocommerce/loop/rating.php
atlanticfurniture/woocommerce/loop/result-count.php
atlanticfurniture/woocommerce/loop/sale-flash.php
atlanticfurniture/woocommerce/myaccount/dashboard.php
atlanticfurniture/woocommerce/myaccount/downloads.php
atlanticfurniture/woocommerce/myaccount/form-add-payment-method.php
atlanticfurniture/woocommerce/myaccount/form-edit-account.php
atlanticfurniture/woocommerce/myaccount/form-edit-address.php
atlanticfurniture/woocommerce/myaccount/form-login.php
atlanticfurniture/woocommerce/myaccount/form-lost-password.php
atlanticfurniture/woocommerce/myaccount/form-reset-password.php
atlanticfurniture/woocommerce/myaccount/lost-password-confirmation.php
atlanticfurniture/woocommerce/myaccount/my-account.php
atlanticfurniture/woocommerce/myaccount/my-address.php
atlanticfurniture/woocommerce/myaccount/my-downloads.php
atlanticfurniture/woocommerce/myaccount/my-orders.php
atlanticfurniture/woocommerce/myaccount/navigation.php
atlanticfurniture/woocommerce/myaccount/orders.php
atlanticfurniture/woocommerce/myaccount/payment-methods.php
atlanticfurniture/woocommerce/myaccount/view-order.php
atlanticfurniture/woocommerce/notices/error.php
atlanticfurniture/woocommerce/notices/notice.php
atlanticfurniture/woocommerce/notices/success.php
atlanticfurniture/woocommerce/order/form-tracking.php
atlanticfurniture/woocommerce/order/order-again.php
atlanticfurniture/woocommerce/order/order-details-customer.php
atlanticfurniture/woocommerce/order/order-details-item.php
atlanticfurniture/woocommerce/order/order-details.php
atlanticfurniture/woocommerce/order/tracking.php
atlanticfurniture/woocommerce/product-searchform.php
atlanticfurniture/woocommerce/single-product/add-to-cart/external.php
atlanticfurniture/woocommerce/single-product/add-to-cart/grouped.php
atlanticfurniture/woocommerce/single-product/add-to-cart/simple.php
atlanticfurniture/woocommerce/single-product/add-to-cart/variable.php
atlanticfurniture/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
atlanticfurniture/woocommerce/single-product/add-to-cart/variation.php
atlanticfurniture/woocommerce/single-product/meta.php
atlanticfurniture/woocommerce/single-product/price.php
atlanticfurniture/woocommerce/single-product/product-attributes.php
atlanticfurniture/woocommerce/single-product/product-image.php
atlanticfurniture/woocommerce/single-product/product-thumbnails.php
atlanticfurniture/woocommerce/single-product/rating.php
atlanticfurniture/woocommerce/single-product/related.php
atlanticfurniture/woocommerce/single-product/review-meta.php
atlanticfurniture/woocommerce/single-product/review-rating.php
atlanticfurniture/woocommerce/single-product/review.php
atlanticfurniture/woocommerce/single-product/sale-flash.php
atlanticfurniture/woocommerce/single-product/share.php
atlanticfurniture/woocommerce/single-product/short-description.php
atlanticfurniture/woocommerce/single-product/tabs/additional-information.php
atlanticfurniture/woocommerce/single-product/tabs/description.php
atlanticfurniture/woocommerce/single-product/tabs/tabs.php
atlanticfurniture/woocommerce/single-product/title.php
atlanticfurniture/woocommerce/single-product/up-sells.php
atlanticfurniture/woocommerce/single-product-reviews.php
atlanticfurniture/woocommerce/single-product.php
atlanticfurniture/woocommerce/taxonomy-product_cat.php
atlanticfurniture/woocommerce/taxonomy-product_tag.php

`
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x
