### ISSUE TITLE
order_item_product_invalid_tax_class

### ISSUE THREAD

**Issue by deepak-iselect** [woocommerce/woocommerce#15287]
![githubissuescreenshot](https://cloud.githubusercontent.com/assets/28970706/26478323/cdf92cd2-420e-11e7-94f5-e11936a4ebd1.JPG)
We are trying to create a new Order using WooCommerce Rest API **/wc/v2/orders** but it fails with the following JSON error

_{
  "code": "order_item_product_invalid_tax_class",
  "message": "Invalid tax class",
  "data": {
    "status": 400
  }
}_

As you can see we are using v2 of API and we have been able to retrieve the Orders but unable to create one.

### STEPS TO REPRODUCE THE ISSUE

1. We are using PostMan to test this flow with the following payload

**{
    "payment_method": "bacs",
    "payment_method_title": "Direct Bank Transfer",
    "set_paid": true,
    "billing": {
        "first_name": "John",
        "last_name": "Doe",
        "address_1": "969 Market",
        "address_2": "",
        "city": "San Francisco",
        "state": "CA",
        "postcode": "94103",
        "country": "AU",
        "email": "john.doe@example.com",
        "phone": "(555) 555-5555"
    },
    "shipping": {
        "first_name": "John",
        "last_name": "Doe",
        "address_1": "969 Market",
        "address_2": "",
        "city": "San Francisco",
        "state": "CA",
        "postcode": "94103",
        "country": "AU"
    },
    "line_items": [
        {
            "product_id": 268,
            "quantity": 1
        }
    ]
}**

We are using Basic Authentication and have not issue authenticating to the Server as we are able to retrieve the Orders.

Looking at the error message we seems to have understood that the issue is to do with the Tax Class and by looking at the Code, we understand that the Tax Class is retrieved from **Product**.

When we looked at the specific Product 'Testing Product', in this case, (see screenshot), we see the Tax Class set against the Product is Standard where as the Code is looking for **Zero Rate** every time. No matter what value is set against the Tax Class field in the **Edit Product** form.

Can you let us know what could be the reason for this behavior and what are we missing that will help us get around this issue.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://magasales.com/wp
Site URL: https://magasales.com/wp
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔  2 active Zapier Feeds.
Zapier Integration - Cron Tasks: ✔  0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔  Order
Zapier Feed #1 Webhook URL: ✔  https://hooks.zapier.com/hooks/catch/2206562/92oq33/
Zapier Feed #1 Trigger: ✔  New Order
Zapier Feed #1 Test Result: ✔  Successfully sent sample data to https://hooks.zapier.com/hooks/catch/2206562/92oq33/.
Zapier Feed #2 Name: ✔  cust
Zapier Feed #2 Webhook URL: ✔  https://hooks.zapier.com/hooks/catch/2206562/92oprd/
Zapier Feed #2 Trigger: ✔  New Customer
Zapier Feed #2 Test Result: ✔  Successfully sent sample data to https://hooks.zapier.com/hooks/catch/2206562/92oprd/.

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wpxu_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

WooCommerce Stripe Gateway: by WooCommerce – 3.1.9
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.3 – 1.3.4 is available
WooCommerce Zapier Integration: by OM4 – 1.6.8
WooCommerce: by Automattic – 3.0.7
WP Editor: by Benjamin Rojas – 1.2.6.3
WP Mail Logging: by Christian Zöller – 1.8.0
Homepage Control: by WooThemes – 2.0.2
Theme Customisations: by WooThemes – 1.0.0
WooCommerce Zapier Integration: by OM4 – 1.6.8
Woo Extra Product Options: by ThemeHiGH – 1.2.1
VarkTech Pricing Deals for WooCommerce: by Vark – 1.1.7
WooCommerce Multiple Free Gift: by Ankit Pokhrel – 1.2.0
Social Media and Share Icons (Ultimate Social Media): by UltimatelySocial – 1.7.2
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.3 – 1.3.4 is available
JSON Basic Authentication: by WordPress API Team – 0.1
WP REST API - OAuth 1.0a Server: by WP REST API Team – 0.3.0
Smart Slider 3: by Nextend – 3.1.10
Error Log Monitor: by Janis Elsts – 1.5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #42 - /?page_id=42
Checkout: #39 - /?page_id=39
My account: #44 - /?page_id=44

### Theme ###

Name: Storefront
Version: 2.2.2 – 2.2.3 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
Sounds like you may have somehow added invalid tax class to the product itself. Change it's tax class, re-save, the try again. (data must change to re-save correctly).

**Comment by deepak-iselect** [comment]
Hi Mike,

Thank you for the response.

I have tried updating the Product through the UI but seems no matter what value I set against the tax Class field on the UI,when I query for the Product record through rest Service, I always get 'Zero Rate' as the Tax Class value.

Not sure why the form field is not updating the value in the data base.

PS: I even tested a scenario where I deleted the 'Zero Rate' tax class but still no luck.

**Comment by mikejolley** [comment]
Screenshot me your tax class settings, and if you can export the products in tools > export and look at the stored tax class in there.

**Comment by mikejolley** [comment]
Any news?

**Comment by mikejolley** [comment]
Closing due to lack of feedback and non-reproducible state.
