### ISSUE TITLE
woocommerce webhook character problems when use chinese

### ISSUE THREAD

**Issue by qycary** [woocommerce/woocommerce#15288]
Hi
I want integrate woocommerce into my theme, now i get one problem about webhook.
I register one  order account , use it to buy product and set this account s first_name is `益`, last_name is `达`.  I can see my order in http://10.168.1.213/eyetv/my-account/view-order/2215/, everything is ok. 
when i use webhook , i see in request content 
```
.......
{
    "billing_address": {
        "first_name": "u8fbe",
        "last_name": "u76ca",
        "company": "test",
        "address_1": "ytrhafha fahjsfajs afdhsfj",
        "address_2": "fasdf dsaf45",
        "city": "calcc",
        "state": "china",
        "postcode": "33",
        "country": "AS",
        "email": "test@test.com",
        "phone": "11111111"
    }
}
......
```
first_name and last_name been changed into `u8fbe` and `u76ca`  not `\u8fbe` `\u76ca`,  then in Delivery URL server i got an error 
```
  Status: 500 Internal Server Error
  36798 out of char range
````

if i use one account use english to write name , Delivery URL server can get the correct data.
so if i forget to set something,or webhook character problems  

### my woocommerce version 
`WC Version:		2.6.14`

**Comment by mikejolley** [comment]
Confirmed in 3.0 too, only in payload. API is fine.

**Comment by claudiosanches** [comment]
I just tested and works just fine: 

![screenshot from 2017-06-05 15-08-01](https://cloud.githubusercontent.com/assets/1264099/26796715/d7d21490-4a00-11e7-9803-6d2288eafc83.png)

The only place where we try any `\` in the webhook log on admin, still works just fine.

**Comment by claudiosanches** [comment]
WordPress is removing it when saving comment meta data, see:

```
wp> add_comment_meta( 1, '_foo', '{"first_name":"\u76ca","last_name":"\u8fbe"}' )
=> int(251)
wp> get_comment_meta( 1, '_foo', true )
=> string(42) "{"first_name":"u76ca","last_name":"u8fbe"}"
```

Maybe the best solution here is to move from WordPress comments to our new log system.
