### ISSUE TITLE
CRUD functions for WC_Customer object

### ISSUE THREAD

**Issue by nbstreet** [woocommerce/woocommerce#15280]
Using the CRUD methodology in V3, how do I get a WC customer object?
Should it be like: 
$customer = new WC_Customer( $user->id );

After research, I think we need a method like "wc_get_customer()", since there is a already "wc_get_product()" and "wc_get_order()".   Basicly, there needs to be a wc_get_*** for all CRUD objects.   

On a related note, when deleting a WC customer, should I use delete_and_reassign() or wp_delete_user() ?  I think delete_and_reassign() is more correct, but it is currently not working.

**Comment by mikejolley** [comment]
`
$customer = new WC_Customer( $user->id );
`

is acceptable. There are not extra steps required like with orders/products so you can use directly.

`delete_and_reassign` is only needed if you want to move the user's posts to another user. Use delete if not.
