### ISSUE TITLE
Import Export User Docs

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#15299]
Create on WIKI.

**Comment by claudiulodro** [comment]
@mikejolley @claudiosanches 

https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Importer-&-Exporter

If this looks good, go ahead and close this ticket.

**Comment by claudiosanches** [comment]
Looks good for me, let's Mike check and close.

**Comment by mikejolley** [comment]
Thanks. I've updated the schema and TOC.
