### ISSUE TITLE
Gravity Forms Product Add-On grabbing Old Lead Data from Unrelated Orders

### ISSUE THREAD

**Issue by MikeBytion** [woocommerce/woocommerce#15295]
### EXPLANATION OF THE ISSUE

We are having periods where orders submitted are grabbing data from old unrelated orders.  What's interesting is this is several unique orders from individual customers all grabbing the same piece of data.  For instance one of our fields is biography, and the biography from the old order is being put in as the data retrieved from the current orders drop down.  So it's not even the same type.

This tends to happen within isolated time periods.

### STEPS TO REPRODUCE THE ISSUE

None, the issue is completely random.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://devumi.com
Site URL: https://devumi.com
WC Version: 2.6.14
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.15-0ubuntu0.16.04.4
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Database ###

WC Database Version: 2.6.14
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Active Plugins (54) ###

Gravity Perks: by Gravity Wiz – 1.2.18.6
Gravity Forms: by rocketgenius – 2.1.3
Better 2Checkout for WooCommerce: by Agbonghama Collins (W3Guy LLC) – 1.2
Admin Menu Editor Pro: by Janis Elsts – 2.4.2
Advanced Custom Fields: Font Awesome: by Matt Keys – 1.7.3
Advanced Custom Fields PRO: by Elliot Condon – 5.5.10
AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.1.7
AffiliateWP: by AffiliateWP
LLC – 2.0.4

AffiliateWP - Force Pending Referrals: by Pippin Williamson and Andrew Munro – 1.0
Akismet Anti-Spam: by Automattic – 3.3.2
coinbase-woocommerce: by Coinbase Inc. – 2.1.3
Devumi Mail Chimp: by Mike Grotton – 0.1.0
Duplicate Page: by mndpsingh287 – 2.2
Genesis Connect for WooCommerce: by StudioPress – 0.9.9
GitHub Updater: by Andy Fragen – 6.2.2
Gravity Forms CSS Ready Class Selector: by Brad Vincent – 1.1
Gravity Forms MailChimp Add-On: by rocketgenius – 4.1
GP Conditional Pricing: by David Smith – 1.2.26
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1
Maintenance Pro: by fruitfulcode – 3.0
Maintenance: by fruitfulcode – 3.3
Optimizely: by Optimizely Inc. – 3.7.5
Peter's Login Redirect: by Peter Keung – 2.9.1
Placehold Gravity Forms: by 51seven GmbH
Timo Maemecke – 1.2

Plugins Garbage Collector: by Vladimir Garagulya – 0.10.3
Pretty Link: by Blair Williams – 2.0.7
Simple Social Icons: by Nathan Rice – 2.0.1
SIP Reviews Shortcode Pro WooCommerce: by ShopitPress  – 1.1.8
SVG Support: by Benbodhi – 2.3.6
Top Bar PRO: by WP Darko – 1.2
User Role Editor Pro: by Vladimir Garagulya – 4.30
WC Check Order Ip: by Be Duc Tai – 1.5
Widget Logic: by wpchefgadget
alanft – 5.7.2

WooCommerce - Variations URL Load: by Remi Corson – 1.0
WooCommerce Account Funds: by WooThemes – 2.1.0 – 2.1.5 is available
WooCommerce Ambassador Integration: by WooThemes – 1.1.4 – 1.1.5 is available
WooCommerce Google Analytics Pro: by WooThemes / SkyVerge – 1.1.7 – 1.3.3 is available
WooCommerce - Gravity Forms Product Add-Ons: by WooThemes – 2.10.10 – 3.1.9 is available
Booster for WooCommerce: by Algoritmika Ltd – 2.6.0
WooCommerce Order Status & Actions Manager: by Actuality Extensions – 2.1.4
WooCommerce Store Credit: by WooThemes – 2.1.5 – 2.1.7 is available
WooCommerce Subscriptions: by Prospress Inc. – 2.1.4
WooCommerce Tab Manager: by WooThemes / SkyVerge – 1.7.4 – 1.8.0 is available
Devumi WooCommerce Product Variations JSON: by  – 1.0
WooCommerce: by WooThemes – 2.6.14
WooCommerce Helper: by WooCommerce – 1.7.2
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 4.4
WP Admin No Show: by Doug Sparling – 1.7.0
WP Migrate DB: by Delicious Brains – 0.9.2
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

Yoast SEO: WooCommerce: by Team Yoast – 4.4
YITH WooCommerce Anti-Fraud Premium: by YITHEMES – 1.1.0
Zendesk for WooCommerce: by SlopeTracker. – 1.0.77

### Settings ###

Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔

### WC Pages ###

Shop Base: #14 - /shop/
Cart: #15 - /cart/
Checkout: #16 - /checkout/
My Account: #17 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

### Theme ###

Name: Devumi Auto Engagements
Version: 0.1.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.4.2
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: devumiae/woocommerce/cart/cart.php
devumiae/woocommerce/checkout/cart-errors.php
devumiae/woocommerce/checkout/form-billing.php
devumiae/woocommerce/checkout/form-checkout.php
devumiae/woocommerce/checkout/form-coupon.php
devumiae/woocommerce/checkout/form-login.php
devumiae/woocommerce/checkout/form-pay.php
devumiae/woocommerce/checkout/form-shipping.php
devumiae/woocommerce/checkout/payment-method.php
devumiae/woocommerce/checkout/payment.php
devumiae/woocommerce/checkout/review-order.php
devumiae/woocommerce/checkout/terms.php
devumiae/woocommerce/checkout/thankyou.php
devumiae/woocommerce/myaccount/form-login.php
devumiae/woocommerce/myaccount/my-account.php
devumiae/woocommerce/myaccount/my-orders.php
devumiae/woocommerce/single-product/review-meta.php
devumiae/woocommerce/single-product/review-rating.php
devumiae/woocommerce/single-product-reviews.php
devumiae/woocommerce/single-product.php

</details>

**Comment by claudiulodro** [comment]
`WooCommerce - Gravity Forms Product Add-Ons: by WooThemes – 2.10.10 – 3.1.9 is available`

You should update to the latest version. That will probably solve your problem.

There are a bunch of other WooCommerce plugins you're using that aren't updated also. These updates are how bugs are fixed, so your problem may have already been solved.
