### ISSUE TITLE
HTML tags for attributes not displayed revisited

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#15291]
Was this update ever included as discussed here: #6620

I've tried to add some HTML to an attribute but it's only presented as text. I used both the WooCommerce Product CSV Import Suite plugin as well as added it manually in the admin area of a product.

**Comment by mikejolley** [comment]
Yes, but you should be using a local attribute, not global, if including HTML. Or custom field.

**Comment by rocketeer76** [comment]
I understand! Why did you limit this functionality to local attributes? So that this functionality is not allowed to be used in the Layered Navigation widget?

When I read the manual (https://docs.woocommerce.com/document/managing-product-taxonomies/) they are talking about custom attributes (I guess equal to local attributes). If I try to add a custom attribute with data like this:
<a href="http://www.website.com"</a>

It is cut of like this:
<a href="http://www.website.com"

This happens in the admin area when I edit a product. Whenever I click the Update button the </a> portion is removed from the custom attribute when the screen is reloaded. I use WooCommerce 3.0.7.

Thanks!

**Comment by presencewebdesign** [comment]
Yes this problem occurs when you import data from other CMS platforms that are not the same as the woocommerce structure.
