### ISSUE TITLE
HTML code not displayed properly for custom attributes

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#15305]
### EXPLANATION OF THE ISSUE

When adding html tags to a custom attribute for a product the code is not displayed properly.

If I try to add a custom attribute with data like this:
`<a href="http://www.website.com">Website</a>`.

It is only displayed with the text `Website` without any link. If allowed, it should be displayed with a clickable link.

Referring to issue: #6620 it would be good to have the documentation updated on what limited html is allowed in custom attributes. Perhaps it is, but I can't find it.

### STEPS TO REPRODUCE THE ISSUE

Create a custom attribute for a product and add `<a href="http://www.website.com">Website</a>` as the value.

**Comment by rocketeer76** [comment]
It seems the html is stripped out of the value field when clicking the update button.

http://imgur.com/JzpthXJ
http://imgur.com/XheuQiP

**Comment by mikejolley** [comment]
Ok, so no HTML is allowed for attribute values. Attribute values can be terms or text, but both can be used for variations so using HTML is not ideal nor allowed.

https://github.com/woocommerce/woocommerce/pull/15400 at least makes values clickable, so if your value is URL or contains URLs, they will be shown as links.

cc'ing @claudiosanches and @claudiulodro so they are aware.

**Comment by knittl** [comment]
It was possible to put HTML content into custom attributes with version 3.2.6, but it was then again disabled with 3.3.0-beta.1 (more specifically commit 2e08bfdb3369bbb51161455b55567ebf334244d0 in November 2017).

What is the intended behavior of markup in custom meta_data of items? IMHO it is a bit strange that its values are always sanitized and stripped of HTML tags, regardless of output context.

**Comment by mikejolley** [comment]
Markup should not be allowed in attributes as it breaks certain comparisons. Attribute names should not be used for html content.

**Comment by knittl** [comment]
No, not attribute names, but attribute *values*.

It is sensible that the name cannot contain markup (but even then, it should only be escaped according to the current output context).

For values I would expect to be able to store arbitrary data

**Comment by mikejolley** [comment]
Those are in many cases terms. Why not use term meta? That's for arbitrary data.

**Comment by presencewebdesign** [comment]
This is an issue especially when you import data with hundreds of products into woocommerce. 

All the specifications attributes have html tables but when you update the product all the html gets stripped out.
