### ISSUE TITLE
Add a column to indicate if attribute is global

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#15302]
Add new column.

**Comment by rocketeer76** [comment]
That would be great. Also, you were talking about local attributes. But in the documentation it is named custom attributes here: [https://docs.woocommerce.com/document/managing-product-taxonomies/](url)

Perhaps the documentation should be updated!?

**Comment by mikejolley** [comment]
@rocketeer76 These issues are all for our new importer. Nothing else.
