### ISSUE TITLE
Dummy Data

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#15301]
Generate from XML dummy data.

**Comment by claudiosanches** [comment]
There is already two CSV: https://github.com/woocommerce/woocommerce/tree/master/dummy-data
I think we can just merge both and update the columns to match what our new CSV importer expects.

**Comment by mikejolley** [comment]
@claudiosanches They are for CSV import suite and pretty bad, and split up.

I say we import XML content and simply export it/clean it up

**Comment by claudiosanches** [comment]
@mikejolley that's the idea, still need to fix URLs after, and maybe we can include a few new things too, like external products and grouped products.
