### ISSUE TITLE
Hide country from cart when only shipping to one country

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#15318]
### EXPLANATION OF THE ISSUE

When shipping to a single country is selected in the WooCommerce settings, the country is shown in the cart as a fixed value text string. I would prefer having a checkbox in the settings area letting me choose if country shall be displayed or not in the cart.

Also, the Shipping Details string seems not to have been translated to Swedish.

http://imgur.com/FrF2sgH

### STEPS TO REPRODUCE THE ISSUE

Select one country only to ship to in the WooCommerce general settings.

**Comment by mikejolley** [comment]
Use CSS to hide it if not desired.
