### ISSUE TITLE
Changing variation attributes name doesn't change the attribute title in cart product title and email title

### ISSUE THREAD

**Issue by el-presidente** [woocommerce/woocommerce#15315]
I have changed one of my variation attribute titles from "Højgalvaniseret (Magnelis) - på lager April" to "Højgalvaniseret (Magnelis)" but kept the permalink. However the title is kept in the product title in as far as I can see the Cart and the receipt email - see attachments.

1. Add variation "Højgalvaniseret (Magnelis)" to cart - https://www.landhave.dk/produkt/ben-til-land-modern/
2. Go to cart and see the old variation title in the product title
3. Also appears in the email receipt - here I'm also wondering why the attribute is both printed in the product title and below?
 
**Cart**
![screen shot 2017-05-27 at 10 40 14](https://cloud.githubusercontent.com/assets/937382/26519997/8c5333ec-42ca-11e7-8390-e234c58bce6d.png)

**BACS receipt page**
![screen shot 2017-05-27 at 10 41 08](https://cloud.githubusercontent.com/assets/937382/26519998/8c559344-42ca-11e7-80c7-e5a531dfdab3.png)

**Email receipt**
![screen shot 2017-05-27 at 10 41 47](https://cloud.githubusercontent.com/assets/937382/26519999/8c558b56-42ca-11e7-9e63-e7db37838ab8.png)

**Comment by mikejolley** [comment]
What type of attribute? Global?

**Comment by el-presidente** [comment]
I guess so - it's a attribute created in WooCommerce for variation products. Just tested on another instance with the same occurrence.
