### ISSUE TITLE
cURL - Update product variation

### ISSUE THREAD

**Issue by hikarushin** [woocommerce/woocommerce#15319]
I'm trying to update the stock of the variation, but I get the error below. 

Retrieving product using ID ` http://mywoo.com/wp-json/wc/v1/products/107018?` is failed.
But when retrieving using sku `http://mywoo.com/wp-json/wc/v1/products?sku=` I get the correct response.
  
```
{
  "code": "woocommerce_rest_invalid_product_id",
  "message": "To manipulate product variations you should use the /products/&lt;product_id&gt;/variations/&lt;id&gt; endpoint.",
  "data": {
    "status": 404
  }
}
```

The other product id can be retrieved. What should I check?

`
### WordPress Environment ###

Home URL: //mywoo.com
Site URL: //mywoo.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: ✔
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.19-1~dotdeb+8.1
PHP Post Max Size: 100 MB
PHP Time Limit: -1
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 15 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (34) ###

Contact Form 7: by Takayuki Miyoshi – 4.7
Hello Dolly: by Matt Mullenweg – 1.6
Imagify: by WP Media – 1.6.4
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Braintree For WooCommerce Pro: by Payment Plugins
support@paymentplugins.com – 2.6.1

Woocommerce All Discounts: by ORION – 1.11
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.1
WooCommerce: by Automattic – 3.0.7
WooSidebars: by WooThemes – 1.4.3
Yoast SEO Premium: by Team Yoast – 4.5
Yoast SEO: WooCommerce: by Team Yoast – 4.5
WP All Import Pro: by Soflyy – 4.4.7
WP All Import - Link Cloaking Add-on: by Soflyy – 1.1.0
WP All Import - User Import Add-On: by Soflyy – 1.0.9
iThemes Sync: by iThemes – 1.174.0
createIT Size Guide Plugin: by createIT – 2.1
WooCommerce Sequential Order Numbers Pro: by WooThemes / SkyVerge – 1.10.1 – 1.11.2 is available
Remove HTTP: by Fact Maven – 2.1.0
YITH WooCommerce Name Your Price: by YITHEMES – 1.0.7
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Woocommerce All Discounts: by ORION – 1.11
Yoast SEO Premium: by Team Yoast – 4.5
Yoast SEO: WooCommerce: by Team Yoast – 4.5
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
CC & BCC for Woocommerce Order Emails: by Dario Curasì – 1.4.1
WooCommerce Shipping Tracking: by Lagudi Domenico – 10.2
WooCommerce Shipping Tracking - Bulk import addon: Import Sequential Order Number Pro: by Lagudi Domenico – 1.0
WP All Import - Yoast WordPress SEO Add-On: by Soflyy – 1.1.5
WooCommerce: by Automattic – 3.0.7
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.5
WP All Import - ACF Add-On: by Soflyy – 3.1.3
WP All Export Pro: by Soflyy – 1.4.6

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #124586 - /cart/
Checkout: #124585 - /checkout/
My account: #124584 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.2.5
Parent Theme Author URL: //www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
flatsome/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php version 2.0.0 is out of date. The core version is 3.0.0
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/product-image.php version 2.6.4 is out of date. The core version is 3.0.2
flatsome/woocommerce/single-product/product-thumbnails.php version 2.6.4 is out of date. The core version is 3.0.2
flatsome/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`

**Comment by mikejolley** [comment]
As the error message states, to edit a variation you need to use the variation endpoint, not the variation ID on the product endpoint.

**Comment by hikarushin** [comment]
@mikejolley, can you tell me or send me a link for that?

**Comment by mikejolley** [comment]
https://woocommerce.github.io/woocommerce-rest-api-docs/#product-variations
