### ISSUE TITLE
Woocommerce V.3 product Stock possible stock issue

### ISSUE THREAD

**Issue by cooldool** [woocommerce/woocommerce#15317]
### EXPLANATION OF THE ISSUE

I am handling online Store on Internet using Woocommerce 3.0
in Woocommerce everything is working fine but the major problem i face is this.

i have 10 products in stock and if some one buy 1 product my product stock status go 'out of stock'  instead of 9. i am not able to handle this issue please kindly help me.

**Comment by mikejolley** [comment]
Without more details on the environment or product setup this issue is not valid nor reproducible.

Just as a guess, if it's a variable product, ensure stock management is not enabled on the PARENT if your variations have stock.
