### ISSUE TITLE
New filters for query by last modified date in /wp-json/wc/

### ISSUE THREAD

**Issue by apost0706** [woocommerce/woocommerce#15311]
claudiosanches mentioned you could consider adding this in a future release.

This is a highly needed feature for us - our project is a desktop based shipping application. 
This can be also useful for other devs that are maintaining a local cache of WooCommerce data by downloading changed orders only, since the last poll.

Making use of webhooks might be too costly for those devs (like us) who do not have a shared cloud endpoint available to collect the calls on behalf of all their customers.
Thanks.

**Comment by claudiosanches** [comment]
Better post it in http://ideas.woocommerce.com/forums/133476-woocommerce

But as I said, will be included in a future release, but need to come in REST API v3, we just released v2 and should take a while.
Anyway you still can introduced custom filters for any endpoint, the same way you can introduce filters in WordPress REST API.

**Comment by apost0706** [comment]
Thanks - got it.
