### ISSUE TITLE
Update Template versions when WooCommerce gets updated

### ISSUE THREAD

**Issue by KoolPal** [woocommerce/woocommerce#15314]
### EXPLANATION OF THE ISSUE

I am currently on WooCommerce Version 3.0.7 but the templates continue to show version 2.6.0
Ideally these should reflect the current version number as per the release.
In case there are any changes, it would be easier to check.

### STEPS TO REPRODUCE THE ISSUE

Pick any template and check the version number within them

### SYSTEM STATUS

Not relevant 

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
No, they should reflect the version they were last changed under. https://github.com/woocommerce/woocommerce/wiki/Template-File-Guidelines-for-Devs-and-Theme-Authors#changes-to-template-versions
