### ISSUE TITLE
wc_get_orders to allow meta query?

### ISSUE THREAD

**Issue by lazharichir** [woocommerce/woocommerce#15321]
Building a home plugin to handle stripe subscriptions api for my website/platform, I add meta fields to the `WC_Order` I generate or deal with. They store some stripe IDs (invoice, charge and subscription IDs.)

To handle Stripe's webhook events, I need to search and retrieve the corresponding order using the Stripe's invoice ID. The stripe invoice ID is saved as a meta using `$order->update_meta_data( '_stripe_invoice_id', $invoice->id );`.

Because of WC's move to custom tables, I refrain from using WP_Query which would be easy here. Are there plans to get `wc_get_orders` to work with metas?

Thanks!

L

**Comment by mikejolley** [comment]
3.1 will have a search helper. See our dev blog/dev chats/master branch.

**Comment by theritesite** [comment]
The search helper released in WooCommerce 3.1 works great if you have a specific meta value you are looking for, but is there any plans to create similar functionality to the [WP_Meta_Query](https://codex.wordpress.org/Class_Reference/WP_Meta_Query)?
I am looking for the ability to use the compare parameter with the different inputs ( >, <, EXISTS, NOT EXISTS, etc)
