### ISSUE TITLE
Customer limited to purchase qty of stock available in system even though stock management is disabled

### ISSUE THREAD

**Issue by Magine** [woocommerce/woocommerce#15329]
### EXPLANATION OF THE ISSUE

My client has a B2B for retailers buying parts. Customers login and can order any item that is in stock (regardless of how many items are in stock). They don't see stock levels etc.
After 3.0 upd the customers can only order as many of the items as are set in their respective qty fields.

HOW IT USED TO WORK:
Product A is in-stock and has a qty of 5
Customers logs in, he/she does not see quantity and can order as many items of this product as they'd like to, no matter what the qty.

WHAT HAPPENS NOW:
Product A is in-stock and has a qty of 5
Customers logs in, he/she does not see quantity, when they place their order the system gives a message saying that they can only order between 1 - 5 items.

### STEPS TO REPRODUCE THE ISSUE

Not applicable as the system is for registered customers only.

**Comment by mikejolley** [comment]
Stock messages do not show specific ranges of levels. This issue lacks details of settings used, screenshots of errors, system status report.

**Comment by Magine** [comment]
Hi Mike,

I'm not sure what more info I can give you. I'm running WC with Stock Management OFF.
Customers could order any amount of product as long as it is in stock regardless of the stock qty of the product.

This used to work but since the 3.0 update it doesn't. Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/1397897/26545195/032ebef0-4465-11e7-8a86-9ca746a29d78.png)
