### ISSUE TITLE
Woocoomerce product page not showing dropdown selection menu for variations

### ISSUE THREAD

**Issue by damjanstojancic** [woocommerce/woocommerce#15320]
On the page I have only buttons to ad product to chart, without dropdown selection menu for variations. Once I click on ad to chart, it reloads the page and only then shows the dropdown menu. Also the price below the headline is for particular package and not as it is used to be, from-to.
![1](https://cloud.githubusercontent.com/assets/29004685/26523658/6c624698-431c-11e7-8bdc-f1c40ef37b1a.png)
![2](https://cloud.githubusercontent.com/assets/29004685/26523659/6c62c280-431c-11e7-9872-0a7d36139733.png)

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/2587#issuecomment-304485702

Contact Avada if you believe it's that theme. 

```
Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
```
