### ISSUE TITLE
Fatal Error. Missing children of the grouped product

### ISSUE THREAD

**Issue by komarovartem** [woocommerce/woocommerce#15322]
Hello,

### EXPLANATION OF THE ISSUE
The method get_price_html() of the WC_Product_Grouped class does not check if the product exists. It causes a fatal error if one of the child was deleted. 

Call to a member function get_price() on boolean class-wc-product-grouped.php on line 82

### STEPS TO REPRODUCE THE ISSUE
Add two simple products and one grouped product which will have these simple products as children. Then permanently delete one of the child product.

Also, this error might happen during the content import because of WP importer does not save initial post_id during import.

Last ver. of WP and WOO

Cheers.

**Comment by nishitlangaliya** [comment]
@mikejolley ,

I have made some adjustment to fix issue and done the pr # https://github.com/woocommerce/woocommerce/pull/15325 please check for the same and let me know if  any changes required

Thanks,

**Comment by komarovartem** [comment]
@nishitlangaliya added a comment #15325

**Comment by nishitlangaliya** [comment]
@komarovartem 

Thanks for your reply but could not reproduce case you mention regarding price replace with dash can you please provide screenshot or steps to reproduce so that I can check for the same.

Thanks

**Comment by nishitlangaliya** [comment]
@komarovartem

Got it let me do adjustment thanks :)

**Comment by nishitlangaliya** [comment]
@komarovartem 

I have made adjustement as per your suggestion please check for the same # https://github.com/nishitlangaliya/woocommerce/commit/9d180e726dbe189072ae526bb88b192ee859b6a and let me know if still any issue.

Thanks

**Comment by komarovartem** [comment]
@nishitlangaliya

Great, thanks for cooperation.

**Comment by nishitlangaliya** [comment]
@komarovartem,

You welcome :) should I need to create new pull request ? currently. not allowing to create new pull request.
Thanks

**Comment by nishitlangaliya** [comment]
@mikejolley , @komarovartem 

New pr done ref # https://github.com/woocommerce/woocommerce/pull/15326 

Thanks

**Comment by mikejolley** [comment]
We don't need to loop/unset on read. We just need to check if the object exists because `wc_get_product` can return false and that is not handled here.
