### ISSUE TITLE
drop downs e.g. country and state on checkout page crash safari on iOS 8.11 with Woocommerce 3.0 onwards

### ISSUE THREAD

**Issue by wpuser17** [woocommerce/woocommerce#15323]
### EXPLANATION OF THE ISSUE

Drop down fields on the checkout page cause Safari to crash when a selection is made. This occurs in Woocommerce 3.0 onwards. Problem did not occur in previous Woocommerce 2.x versions.

Encountered this issue on an ipad running **Safari on iOS 8.11.**

### STEPS TO REPRODUCE THE ISSUE

Add item to cart.
Go to checkout page.
Select a drop down field e.g. country or state. Safari will crash and when browser restarts cart is empty.

Can test this with a brand new wordpress install (latest version 4.7.5 with default theme) and any version of woocommerce greater than 3.0.

**Comment by jameskoster** [comment]
Hey,

iOS 8.11 is nearly 3 years old. We can't really promise to support such an old version ourselves. As it happens the script we use for our dropdowns isn't maintained by us. You might like to open an issue over [here](https://github.com/select2/select2). 

FYI Devices running versions older than 9 account for just 5% of usage [according to the Apple](https://developer.apple.com/support/app-store/).

I tested the latest version back to 9.3 and couldn't replicate this issue (the crash).

If you have a significant amount of traffic on older iOS versions all I can really suggest is to disable select2 on mobile devices apply your own fix.

Cheers
