### ISSUE TITLE
Registration displays ERROR: with no message

### ISSUE THREAD

**Issue by JonnyLinja** [woocommerce/woocommerce#15328]
### EXPLANATION OF THE ISSUE

I'm on WC 3.0.7. When I attempt to register, it displays  `ERROR:` but does not actually list a reason.

I set up a PHP error log, but all I get is `The log file is empty.` I saw https://github.com/woocommerce/woocommerce/issues/14821 which seemed similar, but in my case the JS console also doesn't mention any errors. I also checked the `wp-content/uploads/wc-logs` directory but there were no meaningful errors.

### STEPS TO REPRODUCE THE ISSUE

1. Go to http://squatsandscience.com/my-account/
2. Attempt to register (make sure password is strong enough)
3. It will display `ERROR:` with no message

### SYSTEM STATUS

<details>

### WordPress Environment ###

Home URL: http://squatsandscience.com
Site URL: http://squatsandscience.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_c8h9w7n1yh_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (21) ###

WP Author Bio: by penguininitiatives – 1.5.5
LayerSlider WP: by Kreatura Media – 5.6.5
Akismet Anti-Spam: by Automattic – 3.3.2
Envato WordPress Toolkit: by Envato – 1.7.3
Error Log Monitor: by Janis Elsts – 1.5.2
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.0.0.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.11.2.1
Ni WooCommerce Sales Report Pro: by Anzar Ahmed – 1.2
No CAPTCHA reCAPTCHA for WooCommerce: by Agbonghama Collins – 1.2
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
PayPal Multiple Emails for WooCommerce: by Jeff Sherk – 1.2.0
ExportFeed - Create Product Feeds For 40+ Merchants: by ExportFeed.com – 3.1.7.8
Qode Instagram Widget: by Qode Themes – 1.0
Go Daddy Quick Setup: by GoDaddy.com
LLC – 1.06

Smart Manager: by StoreApps – 3.9.21
WooCommerce: by Automattic – 3.0.7
Wordfence Security: by Wordfence – 6.3.9
WP User Avatar: by flippercode – 2.0.8
WP User Manager: by Alessandro Tesoro – 1.4.3
WP101 Video Tutorials: by WP101Plugin.com – 0.3
WPUM - reCAPTCHA: by Alessandro Tesoro – 1.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/

### Theme ###

Name: Bridge
Version: 11.0
Author URL: http://www.qodethemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: bridge/woocommerce/cart/cart-empty.php
bridge/woocommerce/cart/cart-shipping.php
bridge/woocommerce/cart/cart-totals.php
bridge/woocommerce/cart/cart.php
bridge/woocommerce/cart/shipping-calculator.php
bridge/woocommerce/checkout/form-coupon.php
bridge/woocommerce/checkout/thankyou.php
bridge/woocommerce/content-product.php
bridge/woocommerce/content-single-product.php
bridge/woocommerce/global/form-login.php
bridge/woocommerce/global/quantity-input.php
bridge/woocommerce/loop/add-to-cart.php
bridge/woocommerce/loop/loop-start.php
bridge/woocommerce/loop/pagination.php
bridge/woocommerce/loop/rating.php
bridge/woocommerce/loop/result-count.php
bridge/woocommerce/loop/sale-flash.php
bridge/woocommerce/myaccount/form-login.php
bridge/woocommerce/myaccount/form-lost-password.php
bridge/woocommerce/myaccount/my-address.php
bridge/woocommerce/myaccount/my-orders.php
bridge/woocommerce/single-product/add-to-cart/external.php
bridge/woocommerce/single-product/add-to-cart/grouped.php version 3.0.3 is out of date. The core version is 3.0.7
bridge/woocommerce/single-product/add-to-cart/simple.php
bridge/woocommerce/single-product/add-to-cart/variable.php
bridge/woocommerce/single-product/related.php
bridge/woocommerce/single-product/sale-flash.php
bridge/woocommerce/single-product/tabs/additional-information.php
bridge/woocommerce/single-product/tabs/description.php
bridge/woocommerce/single-product/tabs/tabs.php
bridge/woocommerce/single-product/up-sells.php

Outdated Templates: ❌Learn how to update
</details>

**Comment by mikejolley** [comment]
Security plugins can hide error reasons/codes.

**Comment by mikejolley** [comment]
Also you have "No CAPTCHA reCAPTCHA for WooCommerce: by Agbonghama Collins – 1.2" but no captcha shown on the form. It's probably that.

**Comment by JonnyLinja** [comment]
That was it! Thanks a bunch. I had disabled one of the plugins but missed that one.

**Comment by alexxpaull** [comment]
I am also having display error but here I am adding a registration form. Here is the code 

`function wooc_extra_register_fields() {?>
       <p class="form-row form-row-wide">
       <label for="reg_billing_phone"><?php _e( 'Phone', 'woocommerce' ); ?></label>
       <input type="text" class="input-text" name="billing_phone" id="reg_billing_phone" value="<?php esc_attr_e( $_POST['billing_phone'] ); ?>" />
       </p>
       <p class="form-row form-row-first">
       <label for="reg_billing_first_name"><?php _e( 'First name', 'woocommerce' ); ?><span class="required">*</span></label>
       <input type="text" class="input-text" name="billing_first_name" id="reg_billing_first_name" value="<?php if ( ! empty( $_POST['billing_first_name'] ) ) esc_attr_e( $_POST['billing_first_name'] ); ?>" />
       </p>
       <p class="form-row form-row-last">
       <label for="reg_billing_last_name"><?php _e( 'Last name', 'woocommerce' ); ?><span class="required">*</span></label>
       <input type="text" class="input-text" name="billing_last_name" id="reg_billing_last_name" value="<?php if ( ! empty( $_POST['billing_last_name'] ) ) esc_attr_e( $_POST['billing_last_name'] ); ?>" />
       </p>
       <div class="clear"></div>
       <?php
 }
`
I have seen this code here https://www.cloudways.com/blog/add-woocommerce-registration-form-fields/.

**Comment by alvinarichard** [comment]
I am still having an error in registration form while adding to [https://mesheble.com/](https://mesheble.com/)
`function wooc_extra_register_fields() {?> <p class="form-row form-row-wide"> <label for="reg_billing_phone"><?php _e( 'Phone', 'woocommerce' ); ?></label> <input type="text" class="input-text" name="billing_phone" id="reg_billing_phone" value="<?php esc_attr_e( $_POST['billing_phone'] ); ?>" /> </p> <p class="form-row form-row-first"> <label for="reg_billing_first_name"><?php _e( 'First name', 'woocommerce' ); ?><span class="required">*</span></label> <input type="text" class="input-text" name="billing_first_name" id="reg_billing_first_name" value="<?php if ( ! empty( $_POST['billing_first_name'] ) ) esc_attr_e( $_POST['billing_first_name'] ); ?>" /> </p> <p class="form-row form-row-last"> <label for="reg_billing_last_name"><?php _e( 'Last name', 'woocommerce' ); ?><span class="required">*</span></label> <input type="text" class="input-text" name="billing_last_name" id="reg_billing_last_name" value="<?php if ( ! empty( $_POST['billing_last_name'] ) ) esc_attr_e( $_POST['billing_last_name'] ); ?>" /> </p> <div class="clear"></div> <?php }`
