### ISSUE TITLE
Foreign Orders and adresses in "Latest Order List" at WooCommerce 3.0.7

### ISSUE THREAD

**Issue by GabrielTheCoder** [woocommerce/woocommerce#15324]
Hello Guys.
There have been an issue lately with WooCommerce 3.0.7 on Wordpress 4.7.5.
Random customers with user accounts claim, that they are getting wrong orders and data from other users in their "latest order" list; the list where you can see the stuff you bought lately ... I am sorry for my bad explainations skills, im not a native speaker.

The issue occoursed randomly with at least 5 users. Even after updating to the versions mentioned above, where the bug still there. One of the biggest problem, beside the annoying fact, that you have foreign orders in your list, is the lack of privacy. Users are also able to see adress of other users like they were in the wrong account. 

There is no certain way to reproduce the error but in my opinion its pretty weighty.
The MySQL Version is 5.5.55, recommended is version at least 5.6.

Also I have stuff like this (the theme i use is kalium)

> Kalium / woocommerce / cart / cart.php Version 2.3.8 is obsolete. The main version is 3.0.3

Therefore i guess my woocommerce templates are outdated. i was not able to update them at the moment.

I am trying to fix the bug by myself and will update this thread after.

regards

**Comment by mikejolley** [comment]
@GabrielTheCoder This is very likely caching, either on the site or server. Remember checkout + account pages NEED to be excluded from page cache.

**Comment by mikejolley** [comment]
Also, "latest order" - what is this? It's not part of core.

**Comment by GabrielTheCoder** [comment]
Hey @mikejolley thank you for your fast response!
actually i am not familiar with wordpress that much but it seems to be a nice solution to use it for small projects, so i have no idea how to divide the checkout and account page cache :S

i tried to update the templates without success. after replacing the outdated templates, the website layout by itself changed completely. luckily i had a backup. i am searching for the reason at the moment but i think there must be a easier solution.

im searching for caching for wordpress now. thank you for the tip

**Comment by mikejolley** [comment]
https://docs.woocommerce.com/document/configuring-caching-plugins/

**Comment by mikejolley** [comment]
Where is the latest order thing you're talking about anyway? Got a screenshot?

**Comment by GabrielTheCoder** [comment]
@mikejolley its when you create an account after buying something and go to 

> http://www.url.com/my-account/orders/

i am able to recreate this issue with every testaccount. 

<img width="1306" alt="bildschirmfoto 2017-05-29 um 11 54 20" src="https://cloud.githubusercontent.com/assets/26571793/26545422/d7739276-4465-11e7-8759-dfd924b19a30.png">

there are three orders as you can see, actually i only made one order, the other ones are from other customers. when i click on the orders, i can even see their adresses.  :S i am checking your link now. thank you very much!

**Comment by GabrielTheCoder** [comment]
I was checking your link, unfortunately, there is no caching plugin installed which could cause the problem. I think it might be a plugin but I dont actually know which one

<img width="383" alt="bildschirmfoto 2017-05-29 um 12 06 10" src="https://cloud.githubusercontent.com/assets/26571793/26545830/763f0bbe-4467-11e7-8748-ba80db8cccb9.png">
<img width="435" alt="bildschirmfoto 2017-05-29 um 12 06 29" src="https://cloud.githubusercontent.com/assets/26571793/26545833/7759746c-4467-11e7-8837-4a1d9d1e58b8.png">
<img width="452" alt="bildschirmfoto 2017-05-29 um 12 06 42" src="https://cloud.githubusercontent.com/assets/26571793/26545836/7956916e-4467-11e7-8350-585328da0cc9.png">
<img width="334" alt="bildschirmfoto 2017-05-29 um 12 07 44" src="https://cloud.githubusercontent.com/assets/26571793/26545837/7a982d6c-4467-11e7-8fde-9f9bb24cb0ec.png">

these are my installed plugins. i think some might be obsolete. due to the administration and only partially rebuilding of the website, im not able to tell which of the plugins are essential for the proper workflow of the website.

**Comment by mikejolley** [comment]
Best remove all a moment and retest.

**Comment by GabrielTheCoder** [comment]
all a moment? what do you mean?
i started to remove certain plugins. without success yet.

**Comment by mikejolley** [comment]
I mean you should deactivate all of them temporarily.

**Comment by jdarbuckle2** [comment]
Hello @GabrielTheCoder and @mikejolley , I apologize I am not familiar with Github etiquette but I made an account specifically to tell you we are having the exact same issue. 

Recurring orders were working fine with us, then suddenly on 5/1/17 many orders got switched around with different Customer accounts, but the correct billing address and card being charged.

It looks like you are NOT using Woo Subscriptions, so perhaps we can rule that out. The plugins you and I have in common are Yoast, Duplicator (now uninstalled), Monarch, Woo, and Askimet. 

We have a ton of subscriptions renewing on 6/1/17. Gabriel, if you would like to connect somehow and try and work through this together, please reach out. I will be watching this thread.

**Comment by mmilosheski** [comment]
Hello @jdarbuckle2 @GabrielTheCoder  I have the same issue here... I'm developer I tried to compare all the orders per customer previous and new ones... and the billing and shipping are sometimes I'm repeating sometimes mixing up :) I still don't know why this happens... but I'm close to finding out why... I was simulating orders from multiple accounts in local test env. and once I recreate this issue all logs on I think I will track down the issue, and I will contribute to the next WC version with a fix for this. I'm also open for help and sharing experience with you guys so contact me

**Comment by jdarbuckle2** [comment]
That's great to hear, @mmilosheski - I am not a developer but I am here to run any tests on our site you might need. Right now I've changed all the past mixed up orders to the correct customers. 

It might be interesting to note I am almost positive that our "Customer" Number seems to have changed for users, and some have swapped! I was pretty sure I started our users at 100 when I used a mass-import plugin for these subscriptions. Now, for instance, our Customer 103 changed to 109, or our 102 changed to 99, or down to 33, or something. 

So it's almost like the Customer Number, which seems to be a Woo additional field to a Wordpress User, got mixed up with different Customers. Sorry I am not more confident with what happened, but putting out fires here. 

Interested in your potential solutions, and I hope this isn't insulting but if you'd like to fix this on our client site tomorrow, I'd happily pay. Talk soon.

**Comment by mikejolley** [comment]
If you're importing orders + customers be careful if orders have customer IDs for user which do not exist. When the user ID IS CREATED it will appear to be associated with the older imported orders.

**Comment by GabrielTheCoder** [comment]
@jdarbuckle2 I will provide as much information as I can. I have deactivated most of the plugins, there havent been any issue recently I guess. Not every customer is telling me, that there is the problem, so I am stepping in the dark actually. I can create test accounts but that is some time eating stuff...

@mikejolley That could be a reason. There have been another wordpress theme installed and i have extracted some data .. but actually none of the woocommerce ones. I dont think that the IDs flipped up while i imported some of the data back again. I hope that deactivating the most plugins ( yes I deactivated nearly everything I could) should do the trick. 

by the way. Woocommerce is a hell of an ecommerce solution! Thumbs up for your help and this awesome solution!

**Comment by mikejolley** [comment]
One thing you can look at (if it's not too late) - in the database look at the highest user ID in the wp_user tables. Then compare this to the postmeta table, key _customer_user. If there is a _customer_user with a higher user ID than exists, that will be it.

**Comment by GabrielTheCoder** [comment]
wp_user only got 2 users, both are admins, one of them is my account... I thought that every new user is going to get registered in this table as user oO

**Comment by mikejolley** [comment]
Since no one on the team has been able to replicate this I will close it, but by all means continue to comment if you learn anything or we need to take another look.

**Comment by GabrielTheCoder** [comment]
the issue is still there, i checked every list and disabled nearly every non essential plugin. The issue came spontaneously... now it comes with every new account :S

**Comment by mikejolley** [comment]
Have you cross referenced the user IDs yet?

**Comment by GabrielTheCoder** [comment]
i did

**Comment by mikejolley** [comment]
Email me an admin login and install query monitor plugin. I will take a quick look over it, but I'm confident this is not a core bug.

**Comment by jdarbuckle2** [comment]
Hey Mike, could you expand a bit more on importing Orders with non-existent Users? I believe we used an Import plugin for our Subscribers and they were not users yet.

**Comment by mikejolley** [comment]
If you import posts/orders/content assigned to a non-existing user ID, when that user ID is later created it will be linked to the old content, even if it did not create it in the first place.

**Comment by jdarbuckle2** [comment]
I think this is our problem. This is what my dev. team found. Do we have any chance at editing or correcting this? We have the initial user numbers from the import and who they should actually be attached to..

_We have an update for you:

_We found that there are 2 _customer_user with a higher value than the user ID on wp_user. What did woocommerce suggest to do with this?_

_Have you imported orders/post/contents before?_

_customer_user:_ 

![woo import issue customer mixup 1](https://user-images.githubusercontent.com/29074658/27151948-3ca86f98-511a-11e7-9591-0f89254daff9.png)

_Download wp_user:_

![woo import issue customer mixup 2](https://user-images.githubusercontent.com/29074658/27151949-3caed040-511a-11e7-8308-64f9cc22dd2b.png)

**Comment by mikejolley** [comment]
Remove that meta data.

**Comment by GabrielTheCoder** [comment]
@jdarbuckle2 @mikejolley 
thank you for your help. especially to you mike. i noticed that there are tons of _customer_user keys with a value higher than the max user id. should i set every value of this to 0 ? i am not that familiar with wordpress and its database so please excuse my question
