### ISSUE TITLE
wc_get_product_ids_on_sale() is not working as expected

### ISSUE THREAD

**Issue by GasparSukk** [woocommerce/woocommerce#15330]
Product regular price = 7.515
Product on sale price = 6.39
Product **is not included in wc_get_product_ids_on_sale()** list.

I debugged this function and discovered some logic i do not understand!
		SELECT post.ID, post.post_parent FROM `$wpdb->posts` AS post
		LEFT JOIN `$wpdb->postmeta` AS meta ON post.ID = meta.post_id
		LEFT JOIN `$wpdb->postmeta` AS meta2 ON post.ID = meta2.post_id
		WHERE post.post_type IN ( 'product', 'product_variation' )
			AND post.post_status = 'publish'
			AND meta.meta_key = '_sale_price'
			AND meta2.meta_key = '_price'
			AND CAST( meta.meta_value AS DECIMAL ) >= 0
			AND CAST( meta.meta_value AS CHAR ) != ''
			AND **CAST( meta.meta_value AS DECIMAL ) = CAST( meta2.meta_value AS DECIMAL** )
		GROUP BY post.ID;

This makes my product regular price 6 and sale price 8.
And **if you compare them (8=6), they do not match** (of course) and not included in list!
Should it be NOT EQUAL instead?

**Comment by mikejolley** [comment]
`price` is the active price.
`sale_price` is the sale price.
`regular_price` is the normal non-sale price.

A product is only *on sale* when the sale price is active. Otherwise it's not. Sale prices should not be greater than the regular prices.

**Comment by GasparSukk** [comment]
Sorry for mistyped words.
I do have product price (7.515) and sale price (6.39) set!
And it is active! I can see this in product detail page - it has discount.
What i am missing here?

**Comment by GasparSukk** [comment]
This problem is not solved. Why did you close it?

I will rewrite temporary fix for it (us my own SQL for that).
Please review this problem. And let me know.

**Comment by mikejolley** [comment]
It's not comparing regular to sale, it's comparing sale to the active price (_price and _sale_price meta). Both will be equal if on sale.

**Comment by GasparSukk** [comment]
Ok, i get it now. Thanks for info.
