### ISSUE TITLE
Rest no route

### ISSUE THREAD

**Issue by wantondude** [woocommerce/woocommerce#15335]
EXPLANATION OF THE ISSUE

Cannot _get woocommerce order list from rest API, I can however _get post list from rest API

STEPS TO REPRODUCE THE ISSUE

1.) Go to https://alba1913.dream.press/wp-json/wc/v2/orders
2.) Go to https://alba1913.dream.press/wp-json/wp/v1/posts
3.) Go to https://alba1913.dream.press/wp-json/ 

I have no different languages installed, only english. 
In step 3 You'll see that /wc/v2/orders is listed and all....

Ideas ? 

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://alba1913.dream.press
Site URL: https://alba1913.dream.press
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.14
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wp_69mpej_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

LayerSlider WP: by Kreatura Media – 6.3.0
Contact Form 7: by Takayuki Miyoshi – 4.7
Envato WordPress Toolkit: by Envato – 1.7.3
Image Widget: by Modern Tribe
Inc. – 4.4.1

WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp for WordPress: by ibericode – 4.1.2
Qode Instagram Widget: by Qode Themes – 1.1
Qode Quick Links: by Qode Themes – 1.0
Qode Twitter Feed: by Qode Themes – 1.0
Slider Revolution: by ThemePunch – 5.4.3.1
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 1.2.4
Timetable Responsive Schedule For WordPress: by QuanticaLabs – 3.8
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.2.7

Use Any Font: by Dinesh Karki – 4.7.2
Varnish HTTP Purge: by Mika Epstein – 4.1
WooCommerce Stripe Gateway: by WooCommerce – 3.1.8
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.3
WooCommerce: by Automattic – 3.0.6 – 3.0.7 is available
Yoast SEO: by Team Yoast – 4.7.1
WPForms Lite: by WPForms – 1.3.7.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Bridge Child
Version: 1.0.0
Author URL: http://www.qodethemes.com/
Child Theme: ✔
Parent Theme Name: Bridge
Parent Theme Version: 11.0
Parent Theme Author URL: http://www.qodethemes.com/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: bridge/woocommerce/cart/cart-empty.php
bridge/woocommerce/cart/cart-shipping.php
bridge/woocommerce/cart/cart-totals.php
bridge/woocommerce/cart/cart.php
bridge/woocommerce/cart/shipping-calculator.php
bridge/woocommerce/checkout/form-coupon.php
bridge/woocommerce/checkout/thankyou.php
bridge/woocommerce/content-product.php
bridge/woocommerce/content-single-product.php
bridge/woocommerce/global/form-login.php
bridge/woocommerce/global/quantity-input.php
bridge/woocommerce/loop/add-to-cart.php
bridge/woocommerce/loop/loop-start.php
bridge/woocommerce/loop/pagination.php
bridge/woocommerce/loop/rating.php
bridge/woocommerce/loop/result-count.php
bridge/woocommerce/loop/sale-flash.php
bridge/woocommerce/myaccount/form-login.php
bridge/woocommerce/myaccount/form-lost-password.php
bridge/woocommerce/myaccount/my-address.php
bridge/woocommerce/myaccount/my-orders.php
bridge/woocommerce/single-product/add-to-cart/external.php
bridge/woocommerce/single-product/add-to-cart/grouped.php version 3.0.3 is out of date. The core version is 3.0.6
bridge/woocommerce/single-product/add-to-cart/simple.php
bridge/woocommerce/single-product/add-to-cart/variable.php
bridge/woocommerce/single-product/related.php
bridge/woocommerce/single-product/sale-flash.php
bridge/woocommerce/single-product/tabs/additional-information.php
bridge/woocommerce/single-product/tabs/description.php
bridge/woocommerce/single-product/tabs/tabs.php
bridge/woocommerce/single-product/up-sells.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by claudiosanches** [comment]
Are you trying to look for support about the WordPress REST API?
Because `wp/v1/posts` is not an endpoint from WooCommerce, not to mention that does not exists any `wp/v1` even in WordPress...
Have you checked the WordPress REST API docs https://developer.wordpress.org/rest-api/?

This does not sounds like an issue with WooCommerce, sounds like some out of scope question about WordPress REST API.

**Comment by claudiosanches** [comment]
> Cannot _get woocommerce order list from rest API, I can however _get post list from rest API

Missing authentication?
Should be really bad have your orders public listed for anyway that want to check.
Still missing read the docs first: https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication
