### ISSUE TITLE
$crosssells returns null always

### ISSUE THREAD

**Issue by iahnn** [woocommerce/woocommerce#15346]
### EXPLANATION OF THE ISSUE

Hi, i was wondering if the cross sells still uses the same method in inserting product id's into the database? Under version 3.0, cross sells stop working in our site.

We added cross sells from zoho using a custom code which inserts the product id's into the _crosssell_ids post meta.

The live site here https://kgtraining.wa.edu.au/ which uses 2.6.14, while the staging uses 3.0.7 http://staging.kgtraining.wa.edu.au/

### STEPS TO REPRODUCE THE ISSUE

1. Make an order from the live site under the dogging courses https://kgtraining.wa.edu.au/dogging-dates-and-price/. You will see cross sells from basic rigging in the cart.

2. Make an order from the staging http://staging.kgtraining.wa.edu.au/dogging-dates-and-price/. They have the same products and cross sells setup. But cross sells not working

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://staging.kgtraining.wa.edu.au
Site URL: http://staging.kgtraining.wa.edu.au
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp2jsdds_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (15) ###

VaultPress: by Automattic – 1.8.9
Advanced Custom Fields PRO: by Elliot Condon – 5.5.13
All 404 Redirect  to Homepage: by Fakhri Alsadi – 1.7
Gravity Forms: by rocketgenius – 1.9.12.1
PixelYourSite PRO: by PixelYourSite – 6.0.8
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.2.0
Thrive Visual Editor: by Thrive Themes – 1.500.17
WooCommerce Dynamic Pricing & Discounts: by RightPress – 1.1.2
WooCommerce eWAY Payment Gateway: by WooThemes – 3.1.12 – 3.1.13 is available
WooCommerce: by Automattic – 3.0.7
Wordfence Security: by Wordfence – 6.3.8
Yoast SEO: by Team Yoast – 4.7.1
WP Smush: by WPMU DEV – 2.6.3
WP Super Cache: by Automattic – 1.4.9
YITH WooCommerce Product Bundles Premium: by YITHEMES – 1.2.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: KG Theme
Version: 1.0.1
Author URL: http://www.bryanlusica.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: kg/woocommerce/archive-product.php
kg/woocommerce/content-product.php
kg/woocommerce/single-product/add-to-cart/simple.php

`
</details>

**Comment by mikejolley** [comment]
You need to format the value correctly. _crosssell_ids expects an array of IDs which is serialised. Look at a manually created product's meta data for reference.
