### ISSUE TITLE
Duplicate _price meta for variable products

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#15345]
### EXPLANATION OF THE ISSUE

http://cld.wthms.co/zjfar

### STEPS TO REPRODUCE THE ISSUE

Create a variable product, and give each variation a different price: http://cld.wthms.co/OgDU6L. Save. Search for the `_price` meta.

I'm using the latest version of WooCommerce, and no other extensions.

Perhaps this is what is causing some strange issues with the price filtering on the frontend?

579002-zd-woothemes

**Comment by bekarice** [comment]
@WPprodigy had a discussion about this in #12997 😄

**Comment by WPprodigy** [comment]
Ah, missed that. Thanks!
