### ISSUE TITLE
Product gallery images are not displayed when no "product image" is set.

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#15342]
If you have no image set under `Product image`, but you do under `Product gallery`, only a placeholder image is displayed on the front end. 

<img width="387" alt="screen shot 2017-05-29 at 1 20 31 pm" src="https://cloud.githubusercontent.com/assets/689165/26561302/161a0472-4472-11e7-9fbe-08719712f065.png">

The work around when using `wp-admin` is to just set a product image, however that is not a great user experience.

This is more of a problem when you are just configuring things via the API. I am using the [`images property`](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties) to set product images via the API. These show in `wp-admin` under gallery and are correctly associated with the product. There is no way for me to have these show on the front-end however because of this bug.

Our product image logic on the front end should show both the 'product image' and 'product gallery' images and not have them depend on each other like this.

**Comment by justinshreve** [comment]
cc @mikejolley

**Comment by mikejolley** [comment]
```
{
	"images": [
		{
			"src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_front.jpg",
			"position": 0
		},
		{
			"src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_2_back.jpg",
			"position": 1
		}
	]
}
```

This sets both.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/wc-api-dev/pull/1
