### ISSUE TITLE
Inconsistency with WC_Order::get_qty_refunded_for_item

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#15341]
In WooCommerce 2.6 and lower, `WC_Order::get_qty_refunded_for_item()` returns a negative integer, ie `-1`.

In WooCommerce 3.0+, `WC_Order::get_qty_refunded_for_item()` will return a positive integer, ie `1` instead. 

Not sure if this is intentional or another change that should be in the migration guide.

**Comment by mikejolley** [comment]
Sounds like a bug in 2.6 tbh - the qty refunded on a refund should definitely be a positive count representing how many units have actually been refunded.

https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#get_qty_refunded_for_item-handling

👍

**Comment by bekarice** [comment]
I don't disagree that a positive int is better / more expected, just been [the same way since 2.2](https://github.com/woocommerce/woocommerce/blob/2.2.0/includes/class-wc-order.php#L73-L90) when refunds were added, so figured it was note-worthy 😸  thanks!
