### ISSUE TITLE
Checkout Issue

### ISSUE THREAD

**Issue by feliciastarks** [woocommerce/woocommerce#15344]
### EXPLANATION OF THE ISSUE

When going to check out in live and test mode, there is no dropdown box for the state. I tried different options under the check out tab and I cannot proceed to pay because of the missing required state dropdown box.

### STEPS TO REPRODUCE THE ISSUE

go to checkout using stripe payment and there is no option for a dropdown for the state.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>
`
### WordPress Environment ###

Home URL: http://feliciastarks.com
Site URL: http://feliciastarks.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.3.24 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 33 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.48.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.0.96 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (10) ###

Acuity Online Appointment Scheduling: by Acuity Scheduling – 1.1.0
Advanced Text Widget: by Max Chirkov – 2.0.10
Akismet Anti-Spam: by Automattic – 3.3.2
AWeber Web Forms: by AWeber – 1.1.17
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Stripe Payment Gateway for WooCommerce ( Basic ): by XAdapter – 2.0.1
Pretty Link: by Blair Williams – 2.0.9
Buy Now for Stripe: by Caseproof
LLC – 1.1.5

Unyson: by ThemeFuse – 2.6.16
WooCommerce: by Automattic – 3.0.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #810 - /services/work-with-felicia/
Cart: #831 - /cart/
Checkout: #829 - /check-out/
My account: ❌ Page does not contain the shortcode.

### Theme ###

Name: In Shape Child
Version: 2.0
Author URL: http://themefuse.com
Child Theme: ✔
Parent Theme Name: In Shape Parent
Parent Theme Version: 2.0.4
Parent Theme Author URL: http://themefuse.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Your theme is hiding the select box: https://dl.dropboxusercontent.com/s/24cdoxl1g934ug7/2017-05-30%20at%2011.06.png This is a theme issue, not a core issue.
