### ISSUE TITLE
Add icon to Settings tab? Override html-admin-settings.php view?

### ISSUE THREAD

**Issue by softtama** [woocommerce/woocommerce#15349]
I'm using WooCommerce 3.0.0. I want to add an icon inside my custom setting tab so it will appear like this:

![image](https://cloud.githubusercontent.com/assets/7237624/26574115/5c12e538-454a-11e7-8161-00f38b890a64.png)

I have successfully achieved that by directly passing an HTML string to `label` property of `WC_Settings_Page`, and yeah it is just me doing some experiments and I won't actually use that way.

```php
public $icon_html = '<span class="admin-woocommerce-ciptaloka-tab"></span>';

...

$this->label = $this->icon_html . __( 'Ciptaloka', 'ciptaloka' );
```

When I search for a template file that holds this settings tab, I was brought to `html-admin-settings.php` file. I'm sure that that's the template file, right? Now I wonder if that file can be overridden in a way, like modifying the `foreach` block of tab creation to become like this; make the tab shows an icon if `$label` is an array that contains `icon_class` key:

```php
...
<nav class="nav-tab-wrapper woo-nav-tab-wrapper">
    <?php
        foreach ( $tabs as $name => $label ) {
            $icon_class = '';
            $icon_html = '';

            if ( is_array( $label ) && isset( $label['icon_class'] ) ) {
                $icon_class = $label['icon_class'];
                $icon_html = '<span class="' . $icon_class . '"></span>';
                $text = $label['text'];
            }
            else {
                $text = $label;
            }

            echo '<a href="' . admin_url( 'admin.php?page=wc-settings&tab=' . $name ) . 
                 '" class="nav-tab ' . ( $current_tab == $name ? 'nav-tab-active' : '' ) . '">' . 
                 $icon_html . $text . '</a>';
        }
        do_action( 'woocommerce_settings_tabs' );
    ?>
</nav>
...
```

Thanks.

**Comment by mikejolley** [comment]
Icons on those tabs are not supported and neither are template overrides for admin files. Only frontend theme template files can be overridden.

You can append any HTML/tab with https://github.com/woocommerce/woocommerce/blob/master/includes/admin/views/html-admin-settings.php#L17 if preferred.
