### ISSUE TITLE
Gallery lightbox loads wrong product gallery image

### ISSUE THREAD

**Issue by ucoocho** [woocommerce/woocommerce#15363]
### EXPLANATION OF THE ISSUE
Summary:
Using WC 3.0.7, the gallery lightbox will load the wrong target image. Clicking on any product thumbnail will result in the gallery lightbox loading the image 1 position over (that follows the targeted image in the product gallery.

### STEPS TO REPRODUCE THE ISSUE
1. Go to https://myseatcovers.com/shop/custom-seat-covers/spacer-mesh-seat-covers/
2. Click on the "black spacer mesh" image in the product gallery
3. The lightbox will then load the image following the actual target image (1 position to the right) which is the "grey spacer mesh"

### SYSTEM STATUS

> WordPress environment
> Home URL:		https://myseatcovers.com
> Site URL:		https://myseatcovers.com
> WC version:		3.0.7
> Log directory writable:		 /home/content/p3pnexwpnas13_data02/68/2880168/html/wp-content/uploads/wc-logs/
> WP version:		4.7.5
> WP multisite:		–
> WP memory limit:		256 MB
> WP debug mode:		–
> WP cron:		
> Language:		en_US
> Server environment
> Server info:		Apache
> PHP version:		5.6.27
> PHP post max size:		65 MB
> PHP time limit:		30
> PHP max input vars:		1000
> cURL version:		7.45.0, OpenSSL/1.0.1e
> SUHOSIN installed:		–
> MySQL version:		5.6.32

**Comment by mikejolley** [comment]
This does not appear to be our gallery - this is custom, possibly part of the theme.

**Comment by ucoocho** [comment]
I believe you are looking at the wrong gallery. I have a customer image gallery that is completely separate from the woocommerce product image gallery. The gallery I am referencing is the lightbox gallery that is part of the featured product gallery. I attached the image below.

![gallery](https://cloud.githubusercontent.com/assets/29067767/26643062/d79ea940-45e4-11e7-9384-be8cb0ae22a0.JPG)

**Comment by mikejolley** [comment]
Yes, compare that to a default theme. It's different.

**Comment by divyadoshi** [comment]
Hi, 

I am also having the same issue,
you can check link here : https://funkysteel.com/product/funky-wood-firewood-storage-rack/
Clicking on any product thumbnail will result in the gallery lightbox loading the image 1 position over (that follows the targeted image in the product gallery.

Please help me in solving it ASAP.
Thanks!

Regards
Divya!

**Comment by mikejolley** [comment]
Contact the theme author.

**Comment by divyadoshi** [comment]
But this is not the theme issue.

**Comment by divyadoshi** [comment]
These is woocoomerce lightbox, which is totally different from the theme. why is this happening. Please help me out of it.

**Comment by mikejolley** [comment]
Unless you've tried the default WP theme, you cannot say it's not a theme issue?

**Comment by mikejolley** [comment]
Some customisation to the gallery has been done because you're missing the 'zoom' icon. Seeing as this doesn't happen on all stores, theme is most likely at fault here.

**Comment by divyadoshi** [comment]
Hey, zoom feature is working , you can hover on product image and can see this

**Comment by mikejolley** [comment]
Flexslider is missing though. Again, compare to a default theme.

**Comment by divyadoshi** [comment]
I didn't want slider for product gallery images, i just want that correct images sholud open in lightbox. What is the relation between Flexslider and product gallery images?

**Comment by mikejolley** [comment]
Flexslider is enabled by default.

Flexslider is disabled on your site.

Hence either yourself, or the theme, has customised the gallery.

So the issue is in your theme's custom gallery. Again, again, compare your gallery to that of the default WP theme Twenty Twelve and you'll see it works in Twenty Twelve.

**Comment by divyadoshi** [comment]
ok, So it means that, if i enabled flex slider, then this product gallery lightbox will work correctly?

**Comment by vsosp16** [comment]
Hey guys, i have the same crap on here http://goksaklima.gameologs.com/urun/u-crown-inverter-duvar-tipi-split-klima-9000-btuh/
Its not about the theme as u see. Different people live the same issue, so its not theme related and also i tried it with default theme. Is there any fix for this ?

**Comment by NatalieMac** [comment]
I'm having this issue as well. I don't want to use the slider or the zoom functionality on the particular site I'm working on, so I've only added theme support for the wc-product-gallery-lightbox. Clicking any thumbnail opens only the featured image for the product and not full-size image that corresponds to the thumbnail clicked.
