### ISSUE TITLE
Documentation incorrect for woocommerce_template_loop_product_title

### ISSUE THREAD

**Issue by Phiph** [woocommerce/woocommerce#15361]
### EXPLANATION OF THE ISSUE

Since WooCommerce 3.0 woocommerce_template_loop_product_title displays the title as a h2.

The documentation states by default it is H3. 

https://docs.woocommerce.com/wc-apidocs/function-woocommerce_template_loop_product_title.html

https://docs.woocommerce.com/wc-apidocs/source-function-woocommerce_template_loop_product_title.html#579-584

P.S. I have overidden the function for now 👍

**Comment by mikejolley** [comment]
Docs will be refreshed with next version: https://github.com/woocommerce/woocommerce/blob/8a22d416056af8b2e06dd4a464c5c8b69d466446/includes/wc-template-functions.php#L608
