### ISSUE TITLE
Product Gallery - Responsive style height issue

### ISSUE THREAD

**Issue by WM4362** [woocommerce/woocommerce#15369]
### EXPLANATION OF THE ISSUE
WordPress 4.7.5–en_AU
WooCommerce 3.0.7
StoreFront 2.1.8

On the **Single Product** page, the **div.woocommerce-product-gallery__image.flex-active-slide** element is styled with **min-height: 442px;**.

This looks fine (as it always has) on a full desktop screen with a full height image. As the page responsively adjusts to smaller width's, the product image width also shrinks, BUT the height remains at 442px. This creates significant "white space" between the image and the Product Name (div.summary.entry-summary), instead of just the standard padding/margin space that's normally there.

In pre WooC 3.x versions it appears that the **div.images img** element was styled with **height: auto;** which kept the page nice and tight responsively.

Not being personally intimate with WooC's style, my best guess fix is simply to swap out "min-height: 442px; with "height: auto;" on the "div.woocommerce-product-gallery__image.flex-active-slide" element. 

That's what I've done in my child theme's css for now at least and it appears to be working fine.

### STEPS TO REPRODUCE THE ISSUE

Scale your browser window width down / view on a lower width resolution screen (i.e. a mobile screen) to the point where the product name wraps around under the product image/gallery.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://localhost/dev
Site URL: http://localhost/dev
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: d3ulw72n_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (7) ###

Black Studio Touch Dropdown Menu: by Black Studio – 1.0.0
Homepage Control: by WooThemes – 2.0.2
Meta Slider: by Matcha Labs – 3.5.1
POLi Payments: by POLi Payments – 1.4
WooCommerce: by Automattic – 3.0.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /products/
Basket: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront Child
Version: 0.9
Author URL: https://www.myshop.com.au
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8 – 2.2.3 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/emails/admin-cancelled-order.php
storefront-child/woocommerce/emails/admin-failed-order.php
storefront-child/woocommerce/emails/admin-new-order.php
storefront-child/woocommerce/emails/customer-completed-order.php
storefront-child/woocommerce/emails/customer-invoice.php
storefront-child/woocommerce/emails/customer-new-account.php
storefront-child/woocommerce/emails/customer-note.php
storefront-child/woocommerce/emails/customer-on-hold-order.php
storefront-child/woocommerce/emails/customer-processing-order.php
storefront-child/woocommerce/emails/customer-refunded-order.php
storefront-child/woocommerce/emails/customer-reset-password.php
storefront-child/woocommerce/myaccount/dashboard.php
</details>

**Comment by mikejolley** [comment]
Height scales with browser window resize (the events are detected). Tested and working on Chrome and master.

Height is needed for sliders so images do not wrap and images are shown inline.
