### ISSUE TITLE
our shop on line in our website does not work

### ISSUE THREAD

**Issue by astrid1968** [woocommerce/woocommerce#15378]
Dear Sir,
 This error appears once I choose the items and order to proceed to check
 out.
 Awaiting for your response.

 Best regards,
                                    Billing

 *Fatal error*: Uncaught Error: Call to undefined method
 WC_Checkout::get_checkout_fields() in
 /home/astrid90/webapps/insignia/wp-content/themes/neighborhood/woocommerce/checkout/form-billing.php:40
 Stack trace: #0
/home/astrid90/webapps/insignia/wp-content/plugins/woocommerce/includes/wc-core-functions.php(203):
 include() #1
 /home/astrid90/webapps/insignia/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(147):
 wc_get_template('checkout/form-b...', Array) #2
/home/astrid90/webapps/insignia/wp-includes/class-wp-hook.php(298):
WC_Checkout->checkout_form_billing('') #3
/home/astrid90/webapps/insignia/wp-includes/class-wp-hook.php(323):
WP_Hook->apply_filters('', Array) #4
/home/astrid90/webapps/insignia/wp-includes/plugin.php(453):
WP_Hook->do_action(Array) #5
/home/astrid90/webapps/insignia/wp-content/themes/neighborhood/woocommerce/checkout/form-checkout.php(43):
do_action('woocommerce_che...') #6
/home/astrid90/webapps/insignia/wp-content/plugins/woocommerce/includes/wc-core-functions.php(203):
include('/home/as in
*/home/astrid90/webapps/insignia/wp-content/themes/neighborhood/woocommerce/checkout/form-billing.php*
on  line *40*

**Comment by astrid1968** [comment]
please need help for re starting my web page www.insigniasport.es

**Comment by mikejolley** [comment]
The error is coming from your theme.

https://github.com/woocommerce/woocommerce/blob/64a60de24f7d68ee4eea071c82439311d7fb24c9/includes/class-wc-checkout.php#L192 exists but it is not static. Tell the author or switch themes.
