### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by boutzamat** [woocommerce/woocommerce#15376]
I keep getting this error when i click magnify icon on single product 

Uncaught TypeError: Cannot read property 'x' of undefined
    at La (photoswipe.min.js?ver=4.1.1:4)
    at bc (photoswipe.min.js?ver=4.1.1:4)
    at a.setContent (photoswipe.min.js?ver=4.1.1:4)
    at a.init (photoswipe.min.js?ver=4.1.1:4)
    at ProductGallery.openPhotoswipe (single-product.min.js?ver=3.0.7:270)
    at HTMLDivElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDivElement.r.handle (jquery.js?ver=1.12.4:3)

All templates are copied from WooCommerce plugin. Markup is totally identical to the default ones that comes with the plugin.

**Comment by mikejolley** [comment]
Without an example link there is not much to work with here. Even if the template files are the same, it does not mean that the theme is allowing the image scripts to be enqueued. If it works with a default theme (which it does our side), this is a theme issue.

**Comment by krypsin** [comment]
I have also run into this issue before.
For me, it was because I was removing the widths and heights on the `post_thumbnail_html` filter which as a result causes PhotoSwipe to break.

**Comment by vinigarcia87** [comment]
I had the same issue!

Thanks @krypsin for share your comment, It solved my problem.

I hooked `post_thumbnail_html` to make better responsive images on bootstrap 3. In this hook, I remove the width/height from the images:

	/**
	 * Wordpress Bootstrap 3 responsive images
	 * Add img-responsive class and remove dimensions
	 * Source: https://gist.github.com/mkdizajn/7352469
	 */
	public function responsive_images( $html ) {
		$classes = 'img-responsive'; // separated by spaces, e.g. 'img image-link'
		// check if there are already classes assigned to the anchor
		if ( preg_match('/<img.*? class="/', $html) ) {
			$html = preg_replace('/(<img.*? class=".*?)(".*?\/>)/', '$1 ' . $classes . ' $2', $html);
		} else {
			$html = preg_replace('/(<img.*?)(\/>)/', '$1 class="' . $classes . '" $2', $html);
		}

                 // remove dimensions from images
		// @WARNING If we remove the width/height properties from images, the WooCommerce PhotoSwipe will not work!
		// @see https://github.com/woocommerce/woocommerce/issues/15376
		//$html = preg_replace( '/(width|height)=\"\d*\"\s/', "", $html );

		return $html;
	}

**Comment by boutzamat** [comment]
I can confirm that removing the width and height from the product image was causing the issue.

**Comment by simeonrowsell** [comment]
Yep, removing the width and height worked for me too.
