### ISSUE TITLE
Grand total does not always round correctly, causes failed PayPal Pro payments due to $0.01 discrepancy in order total

### ISSUE THREAD

**Issue by cqrmskgiub** [woocommerce/woocommerce#15372]
### EXPLANATION OF THE ISSUE

PayPal Pro payment fails. Payment was rejected due to an error: (10413) “The totals of the cart item amounts do not match order amounts.”

v3.0.7

It happens when there is a % off coupon used and is a taxable sale and rounding errors end up causing the totals of cart item amounts to be 1 cent different from order amounts; so sometimes it's fine, sometimes it isn't, just depends on how the math works.

Grand total needs to be the addition of the rounded cart items. For example:

$58.53 subtotal 
-$5.85 coupon 
$4.00 shipping 
$4.64 tax
$61.32 grand total

However what happens is:

$58.53-$5.853=$52.677 subtotal including coupon
$52.677*8.8%=$4.636 tax
$4.00 shipping
$61.31 grand total

### HOW TO FIX THIS ISSUE

It appears that in includes/class-wc-cart.php:1388 the code that calculates the grand total doesn't used the rounded versions displayed in the cart for subtotal, tax, etc.

Current code:
```
// Grand Total - Discounted product prices, discounted tax, shipping cost + tax 
$this->total = max( 0, apply_filters( 'woocommerce_calculated_total', round( $this->cart_contents_total + $this->tax_total + $this->shipping_tax_total + $this->shipping_total + $this->fee_total, $this->dp ), $this ) );
```

I temporarily changed the code to the following and it now comes up with the correct amount (I don't tax shipping so I didn't bother changing that):

```
// Grand Total - Discounted product prices, discounted tax, shipping cost + tax 
$this->total = max( 0, apply_filters( 'woocommerce_calculated_total', round($this->cart_contents_total, $this->dp) + round($this->tax_total, $this->dp) + $this->shipping_tax_total + round($this->shipping_total, $this->dp) + $this->fee_total, $this ) );
```

**Comment by mikejolley** [comment]
Can you log this via the helpdesk? https://woocommerce.com/contact-us/

PayPal uses per-item rounding, but WC uses per-line rounding. Discrepancies should be calculated and a correction line added, but this code may not be working. They can check this via the helpdesk with the help of your logs. 

Changing the line in core may fix your case, but will break others so we cannot just make this change for all users.

cc @bor0 @mattyza

**Comment by cqrmskgiub** [comment]
Got it, will do.
