### ISSUE TITLE
Product Variation not showing in cart, emails or on invoice?

### ISSUE THREAD

**Issue by designboxmedia** [woocommerce/woocommerce#15377]
We updated to the latest 3.03 and suddenly all of the product variations stopped coming through. 
I have cleared the sites cache and made sure this is not an issue. I have gone through and updated all plugins to the latest additions and we are still experiencing the same issues. I have also gone through and updated any bespoke templates for woocommerce to ensure that is also not an issue?
Any ideas of what we can try next?

**Comment by mikejolley** [comment]
3.0.3 is not latest. 3.0.7 is. There is no system status report provided or links for context. Please read the 'new issue' description before posting here.

```
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
```
