### ISSUE TITLE
Unable to clear mini-cart.php cache

### ISSUE THREAD

**Issue by GuerrillaCoder** [woocommerce/woocommerce#15375]
### EXPLANATION OF THE ISSUE

mini-cart.php template is being cached somewhere but I do not know where.  Changes are not being reflected when an update is made and browser cache is cleared.  Is is cached into a transient or something?

### STEPS TO REPRODUCE THE ISSUE

Modify mini-cart.php template and upload.  The changes won't be there.  I have tried clearing browser cache but it doesn't work.  After a period of time the changes will appear but it makes developing template pretty difficult.

The cart contents is set by javascript so does WooCommerce have an ajax cache with a TTL set somewhere?

Is there anyway to disable this while I develop template?

**Comment by mikejolley** [comment]
Changing cart contents will refresh it. It's stored in local storage of your browser. Clearing cookies and browser cache will flush it but it's easier to just add something to your cart :)
