### ISSUE TITLE
Table rate shipping plugin too slow

### ISSUE THREAD

**Issue by domlat** [woocommerce/woocommerce#15374]
This code appears in wp-content/plugins/woocommerce-table-rate-shipping/inc/instance-settings-fields.php :

`$blogusers` = get_users( 'blog_id=1&orderby=nicename' );
$users = array();
foreach( $blogusers as $key => $user )
	$users[ $key ] = $user->user_nicename;
`
and was kicking off a select meta data query for every user on the system.
It can be replaced by this one quick line:
`$users = get_users( array('blog_id' => 1, 'fields' => array('user_nicename'), 'orderby' => 'nicename') );`

In any case I cannot see anywhere in the code that this data is actually referenced.

**Comment by mikejolley** [comment]
Not only is this not core (you're reporting on the core issue tracker), it's not the official extension either :) Our table rate shipping plugin has no 'inc' directory.

Please report to the author.
