### ISSUE TITLE
Storefront Update Changed Front Page

### ISSUE THREAD

**Issue by irreverance** [woocommerce/woocommerce#15379]
### EXPLANATION OF THE ISSUE

Note: I am not overly technically inclined. I'm not sure if this is a bug, and if I need to do something else to get it fixed, please let me know. 

Last night, I updated to the newest Storefront theme. A couple format issues have arisen.
1. The body of the homepage has narrower margins. I had hoped to fix this by recreating the page. When I use PageBuilder to add a 3-column block, it appears that it will fill the page like it should, but when I drop it the margins shrink back to the more narrow look. 
2. Near the bottom, it appears that new sections have appeared (which I like). The "Shop by Category" images, however, are blank. I don't seem to be able to change them in PageBuilder. 

### STEPS TO REPRODUCE THE ISSUE

To see the issues, just go to www.puppytutor.me. They are both on the home page. 

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>
`
### WordPress Environment ###

Home URL: http://puppytutor.me
Site URL: http://puppytutor.me
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23
PHP Version: 5.6.30
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (16) ###

Accelerated Mobile Pages: by Ahmed Kaludi
Mohammed Kaludi – 0.9.50

Akismet Anti-Spam: by Automattic – 3.3.2
AMP: by Automattic – 0.4.2
Google Analytics Counter Tracker: by WPAdm – 3.5.6
Beaver Builder Booster: by The Beaver Builder Team – 1.0.6
Beaver Builder Plugin (Lite Version): by The Beaver Builder Team – 1.9.5.3
Contact Form 7: by Takayuki Miyoshi – 4.7
Contact Widgets: by GoDaddy – 1.4.1
Jetpack by WordPress.com: by Automattic – 4.9
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Schema App Structured Data: by Hunch Manifest – 1.7.2
WooCommerce: by Automattic – 3.0.7
WooZone - WooCommerce Amazon Affiliates: by AA-Team – 9.0.3.3
Wordfence Security: by Wordfence – 6.3.9
Yoast SEO: by Team Yoast – 4.8
Clef: by Clef – 2.6.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #380 - /shop/
Cart: #381 - /cart/
Checkout: #382 - /checkout/
My account: #383 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Issues for Storefront can be logged on https://github.com/woocommerce/storefront/issues

CC @jameskoster 

Thanks
