### ISSUE TITLE
Downloads should open in new tab

### ISSUE THREAD

**Issue by accetturo** [woocommerce/woocommerce#15387]
### EXPLANATION OF THE ISSUE

Up to newest Woo version

After purchasing a downloadble file, when trying to download assets, downloads open in the same window, forcing the user to hit the back button. This is particularly annoying with PDF files when a product has dozens of them, adding dozens of back actions that are unneeded. The Downloads php should have the target="_blank" action enclosed to open each file in a new window / tab.

### STEPS TO REPRODUCE THE ISSUE

Purchase a downloadable file, goto the My Downloads page then try and download your files.

**Comment by mikejolley** [comment]
For order display, it's already there so long as your theme doesn't render them itself:

https://github.com/woocommerce/woocommerce/blob/8a22d416056af8b2e06dd4a464c5c8b69d466446/includes/wc-template-functions.php#L2501
