### ISSUE TITLE
Products that have attributes with no value are deleted upon saving

### ISSUE THREAD

**Issue by ucoocho** [woocommerce/woocommerce#15388]
### EXPLANATION OF THE ISSUE

After upgrading to recent versions of woocommerce (noticed in 3.0.6+), products that have attributes with no values are automatically removed. This is behavior was not reproducible in our old staging site still using woocommerce 2.5.

### STEPS TO REPRODUCE THE ISSUE

1. Go to any variable product
2. Add a new attribute giving it a name but no assigned list of values
3. Click save attribute and observe that attribute is removed.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
This is correct. Values are required. Attributes can do nothing/cannot display without values.
