### ISSUE TITLE
Partial Refund Line Items

### ISSUE THREAD

**Issue by jmawebtech** [woocommerce/woocommerce#15380]
Hi,

I have a partial refund in WooCommerce. When I pull the order, I see a section called refunds. I do not see the line items that were refunded, but I do see the total refunded. Can you tell me which line items received the refund? I have attached a screenshot of the order and a JSON response.

URL:
https://www.XX.com/wp-json/wc/v1/orders/32179?consumer_key=XX&consumer_secret=XX&filter%5bmeta%5d=false 

[Response.docx](https://github.com/woocommerce/woocommerce/files/1042069/Response.docx)

**Comment by mikejolley** [comment]
See https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-refund - you have an ID in the refunds array
