### ISSUE TITLE
WooCommerce 3.1 beta 1 don't execute shortcodes on inline "terms and conditions" on checkout.

### ISSUE THREAD

**Issue by artprojectgroup** [woocommerce/woocommerce#15389]
![captura de pantalla 2017-06-01 a las 7 50 43](https://cloud.githubusercontent.com/assets/6569259/26666214/152aea2a-469f-11e7-857d-8123e58fd72f.jpg)

**Comment by artprojectgroup** [comment]
Wrong test. Work fine.

Great option. Thank you.

**Comment by ksere** [comment]
Does it (parse shortcodes) ?

In my tests it also looks like it doesn't.

**Comment by artprojectgroup** [comment]
@ksere right, work with WooCommerce shortcodes, but don't parse other shortcodes :-(

Reopen the issue.

Kind regards.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/terms.php#L17

This function runs a few filters on the content: https://github.com/woocommerce/woocommerce/blob/7529e1ac267966c116e558a2328542905fc8e17c/includes/wc-formatting-functions.php#L899

`do_shortcode` is one of them https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/wc-core-functions.php#L47-L55

If a plugin implements shortcodes correctly in the WP API, it will render.

> work with WooCommerce shortcodes, but don't parse other shortcodes

WC shortcodes are simply added with `add_shortcode` - the correct way https://codex.wordpress.org/Function_Reference/add_shortcode

Visual composer likely adds their shortcodes conditonally.. I cannot check, I don't own it.

**Comment by artprojectgroup** [comment]
Thanks @mikejolley.

Kind regards.

**Comment by DonSanto** [comment]
This is what I have done trying to solve a similar scenario where I wanted to be able to parse shortcodes, both VC shortcodes and other shortcodes, in a page fetched added  before the terms and conditions.

```php
add_action( 'woocommerce_checkout_before_terms_and_conditions', 'myFunction', 1 );
function myFunction() {
    // Fix for rendering Visual Composer shortcodes.
    if(class_exists('WPBMap') && method_exists('WPBMap', 'addAllMappedShortcodes')) { 
        WPBMap::addAllMappedShortcodes();
    }
    $mypost = get_page_by_path('checkout/page-slug');
    $mypost->ID;
    $content = get_post_field('post_content', $mypost);
    echo do_shortcode($content);
}
```

I don't know if this is the correct way to solve it, but it works. Maybe you could look at a similar solution for the terms page?
