### ISSUE TITLE
Add key for order_id in woocommerce_downloadable_product_permissions table.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#15382]
This was first reported [on the forums](https://wordpress.org/support/topic/3-0-slow-checkout/).

It appears that we don't set a key for `order_id` when we [create the woocommerce_downloadable_product_permissions table](https://github.com/woocommerce/woocommerce/blob/85b8d8661a8e345ce122fa7a1f4f9c50ba8f57ed/includes/class-wc-install.php#L506-L521). We can get a performance boost in [`update_user_by_order_id`](https://github.com/woocommerce/woocommerce/blob/00e5189a0568aff8388200d8ede2b67edffadfbd/includes/data-stores/class-wc-customer-download-data-store.php#L336) with a key on order_id.

We'll have to update the table creation code and add a db update that runs when the user upgrades to the latest WooCommerce version.

**Comment by BobSmithJoe** [comment]
What will happen for those of us that have already manually added this index -- will Woo throw a fit when updating?

**Comment by claudiulodro** [comment]
The update will most likely work like [this index check](https://github.com/woocommerce/woocommerce/blob/85b8d8661a8e345ce122fa7a1f4f9c50ba8f57ed/includes/class-wc-install.php#L441-L447) and add the index if it doesn't exist.

**Comment by BobSmithJoe** [comment]
Got it, thanks.
