### ISSUE TITLE
Reviews/Ratings Confusion

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#15399]
The difference between disabling ratings and disabling reviews is a bit confusing. You can disable ratings here for all products: http://cld.wthms.co/cj3ROH, but you need to manually disable comments per product here: http://cld.wthms.co/BuTTCp. The "Allow people to post comments on new articles" option at "Settings > Discussions" also plays a role here, which could add to the confusion.

I'd propose we try to separate and simplify things a bit. Product Reviews should be handled differently than normal post comments (as far as the user is concerned). The comment system in WordPress is hard enough to grasp from a user's standpoint, so I think we should take a step away from it and make it easier in WooCommerce.

Suggestions:

- Step away from using "comments" lingo and use just "Reviews".
- Have an option to globally disable product reviews.
- Clean up settings. For example, these two settings may be needed even if ratings are disabled: http://cld.wthms.co/PGH2ZF, but if the first setting is unchecked they are hidden.
- Have a way to view Product Reviews in the admin separately from other post comments (this one is likely like a lot more work than the others, but just throwing it out there as a chain of thoughts).

**Comment by mikejolley** [comment]
@WPprodigy you know a lot of this is hardcoded into WordPress? https://github.com/WordPress/WordPress/blob/f884d7973b052c3efe0901bb136b9898ece8aa39/wp-admin/includes/class-wp-posts-list-table.php#L1628

TBH I'd rather let the Calypso people do their thing here since thats pretty much the interface of the future :)

**Comment by WPprodigy** [comment]
We can always ask for filters and hooks in core xD. But yea, I agree a lot of this can be changed/made better with Calypso.

That said, there are some things we can still do. Namely, have an option to globally disable product reviews, and make that the first option in our settings. Then if it's disabled, we can hide the rest. If it's enabled, we can show these two: http://cld.wthms.co/PGH2ZF. And the ratings option will control whether or not the other setting is shown.

**Comment by mikejolley** [comment]
WP has a global setting for comments, so it may not be technically possible to do so. Will need looking into.

**Comment by mikejolley** [comment]
> Have a way to view Product Reviews in the admin separately from other post comments (this one is likely like a lot more work than the others, but just throwing it out there as a chain of thoughts). 

This one shouldn't be tackled in WP Admin IMO. It's reinventing the wheel and best taken care of in Calypso. We can however add some shortcuts to manage reviews under the existing UI.
