### ISSUE TITLE
Should Product Visibility be Inherited?

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#15392]
### EXPLANATION OF THE ISSUE

When a product's visibility is changed to "hidden", this is not inherited by the variations, visibility checks will return that the variation is visible when the parent isn't. This seems counter intuitive, as the product variations class has a fair number of checks to return the parent property if not set for the variation, so perhaps this should be the same for `$product->is_visible()` and `$product->get_catalog_visibility()`.

With Memberships specifically, it will show a list of products that can grant access to a plan in a list. If a product is hidden, it's typically removed from this list (usually used for "invite-only" sort of gigs). However, if the product is hidden, but _the variation_ grants access to the plan, the variation is still shown in the list since `$product->is_visible()` will return `true` here in our check for what should be in the list:

```
if ( $product instanceof WC_Product && $product->is_purchasable() && $product->is_visible() ) {
	$products[] = $product_id;
}
```

Curious if this is expected behavior or should be worked around.

### STEPS TO REPRODUCE THE ISSUE

1. Set a variable product to be hidden from the catalog.
2. Log the result of `wc_get_product( {aVariationID} )->get_catalog_visibility()` and notice it's "visible"

**Comment by mikejolley** [comment]
@bekarice I wouldn't straight inherit it due to needing to read all the parent terms etc. Not to mention catalog visibility means nothing to variations since they are not displayed in the catalog.

Variations do have `variation_is_visible` which looks at status but thats not quite the same.

Open to suggestions. If we did have to read it would be possible, but may be expensive.

**Comment by bekarice** [comment]
@mikejolley I don't really see a way to do this aside from overriding the abstract `is_visible()` in the variation class and doing a read on the parent, unless you want to change the default visibility on read to be consistent with what it was in prior versions.

The reason this worked fine in WooCommerce 2.6 was the following: 

1. `$this->visibility` [was checked to determine visibility] (https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/abstracts/abstract-wc-product.php#L767-L771) for all products
1. When getting that property, [the post meta was used](https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/abstracts/abstract-wc-product.php#L116-L127), and if it didn't exist (which it didn't for a variation), it was always returned as `hidden`

So you won't see this issue on any WC version prior to 3.0.

In WC 3.0, now [default visibility](https://github.com/woocommerce/woocommerce/blob/08279dc7b99aae8a403e8bb2248bfd9f9851780d/includes/abstracts/abstract-wc-product.php#L1384-L1385) always checks `$this->get_catalog_visibility()` reads [the product terms](https://github.com/woocommerce/woocommerce/blob/eda55579b747a9f859c76a73769418e5f9d97ec9/includes/data-stores/class-wc-product-data-store-cpt.php#L343), and the variation post obviously won't have terms set, so the item defaults to `visible`.

So either an override or change the default back to being consistent with previous behavior and `hidden` instead of visible. Not sure which would be preferred here.

**Comment by mikejolley** [comment]
Right. We cannot force it hidden as that will break upsell/cross sell display of variations.
