### ISSUE TITLE
Product page doesn't work at all if Woocommerce membership plugin is activated

### ISSUE THREAD

**Issue by OrangeSheepWeb** [woocommerce/woocommerce#15391]
### EXPLANATION OF THE ISSUE

Updated woocommerce and all the other plugins to the latest version. 

Just if you activate the woocommerce membership plugin, you cannot work on the products  ( modifing or whatever on product page, also the product tabs do not work ).

### STEPS TO REPRODUCE THE ISSUE

1- Deactivate all plugins
2- Keeping active only woocommerce and the Avada theme plugins.
3- Activating woocommerce membership plugin

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: https://corsipernegozi.cliento.info
Site URL: https://corsipernegozi.cliento.info
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache/2.2.24 (Unix) mod_hive/5.5 mod_ssl/2.2.24 OpenSSL/1.0.0-fips mod_auth_passthrough/2.1 mod_fastcgi/2.4.6 mod_bwlimited/1.4 mod_fcgid/2.3.6
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 15000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

ManageWP - Worker: by ManageWP – 4.2.18
404 to Start: by Jürgen Schulze – 1.6
WooCommerce Order Export and More PRO: by JEM Plugins – 1.4.3
Theia Sticky Sidebar: by WeCodePixels – 1.4.2
Contact Form 7 Honeypot: by Nocean – 1.10
Contact Form 7: by Takayuki Miyoshi – 4.7
Disable Admin Bar: by Ozh – 1.1
eWI Bespoke Addon (Bulk Sync of Tags): by Ektagon Platforms – 0.2.0
Fusion Builder: by ThemeFusion – 1.0.6
Fusion Core: by ThemeFusion – 3.0.6
SOGO Add Script Header Footer: by orenhav (SOGO) – 2.3
Save Contact Form 7: by Nimblechapps – 1.5
Simple 301 Redirects: by Scott Nellé – 1.07
User Switching: by John Blackbourn – 1.0.9
WC-AC Hook: by Matthew Treherne – 1.2.2
WC Vendors: by WC Vendors – 1.9.11
WooCommerce international phone input: by Alex Masliychuk (alex91ckua) – 1.3.2
WooCommerce All in One Currency Converter: by Dev49.net – 2.9
WooCommerce Checkout Manager: by Visser Labs – 4.1.2
WooCommerce Direct Checkout: by Terry Tsang – 1.1.2
WooCommerce Extra Charges To Payment Gateway (Standard): by hemsingh1 – 1.0.12.3
Follow-Up Emails: by WooCommerce – 4.4.19
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.2
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.4
WooCommerce Intercom Integration: by Ektagon Platforms – 0.9.1
WooCommerce Memberships: by SkyVerge – 1.8.4 – 1.8.5 è disponibile
WooCommerce PDF Invoices Premium: by Bas Elbers – 1.3.9
WooCommerce PDF Invoices: by Bas Elbers – 2.9.1
WooCommerce Redirect Thank You: by Shop Plugins – 1.0.6
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.1
WooCommerce Subscriptions: by Prospress Inc. – 2.2.7
WooCommerce URL Coupons: by SkyVerge – 2.5.1
WooCommerce: by Automattic – 3.0.7
WooCommerce Helper: by WooCommerce – 1.7.2 – Abilitato sul Network
Yoast SEO: by Team Yoast – 4.8
WP Admin No Show: by Doug Sparling – 1.7.0
WP Rocket: by WP Media – 2.9.11

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #8569 - /
Carrello: #8549 - /store/carrello/
Cassa: #8551 - /store/cassa/
Il mio account: #8561 - /store/account/

### Theme ###

Name: Avada Child
Version: 4.0.3
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.0.6
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php versione 2.3.8 è obsoleta. La versione attuale è 3.0.3
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php versione 2.2.0 è obsoleta. La versione attuale è 3.0.0
Avada/woocommerce/loop/loop-start.php
Avada-child/woocommerce/myaccount/downloads.php versione 2.6.0 è obsoleta. La versione attuale è 3.0.0
Avada-child/woocommerce/myaccount/payment-methods.php
Avada/woocommerce/single-product/add-to-cart/variable.php versione 2.5.0 è obsoleta. La versione attuale è 3.0.0
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php versione 2.5.0 è obsoleta. La versione attuale è 3.0.0
Avada/woocommerce/single-product/product-image.php versione 2.6.3 è obsoleta. La versione attuale è 3.0.2
Avada/woocommerce/single-product/product-thumbnails.php versione 2.6.3 è obsoleta. La versione attuale è 3.0.2
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php versione 2.0.0 è obsoleta. La versione attuale è 3.0.0
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌Scopri come aggiornare

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off
`

**Comment by OrangeSheepWeb** [comment]
Also tried to update membership plugin to 1.8.5 version ... but still you cannot edit your product...and all tabs in the single product page don't works.

**Comment by mikejolley** [comment]
I doubt it's memberships alone - it is likely conflicting with another. 

Could even be https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x

I suggest you start by turning off the rest of the extensions to find a conflict. That includes non-WC plugins, since any plugin can include it's own scripts.

If after that you're certain it's memberships, raise a ticket in the correct place: https://woocommerce.com/contact-us/

Thanks
