### ISSUE TITLE
Rest API queries with multidimensional arrays generates wrong signature

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#15395]
### EXPLANATION OF THE ISSUE

_Version: woocommerce master_

Rest API Signatures & multi-dimensional arrays applied to the query:

Ex. [http://url.com/wp-json/wc-api/v2/endpoint?arr[0][func]=example](http://url.com/wp-json/wc-api/v2/endpoint?arr[0][func]=example)

_Bug: This will in any condition respond with 'invalid signature' because core only supports one dimensional arrays in signature_

**Pull request:**
[https://github.com/woocommerce/woocommerce/pull/15396
](https://github.com/woocommerce/woocommerce/pull/15396
)

**Comment by mikejolley** [comment]
@steffanhalv Which documented query in the REST api supports multidimensional?

**Comment by steffanhalv** [comment]
@mikejolley All batch endpoints

Ex. http://woocommerce.github.io/woocommerce-rest-api-docs/#batch-update-products

Supports:

```
{
  "create": [
    {
      "name": "Woo Single #1",
      "type": "simple",
      "regular_price": "21.99",
      "virtual": true,
      "downloadable": true,
      "downloads": [
        {
          "name": "Woo Single",
          "file": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/cd_4_angle.jpg"
        }
      ],
      "categories": [
        {
          "id": 11
        },
        {
          "id": 13
        }
      ],
      "images": [
        {
          "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/cd_4_angle.jpg",
          "position": 0
        }
      ]
    }
```

Which is encoded to:

url/api_path/products/batch?create[0][name]=Woo%20Single%20#1&create[0][type]=simple&...

**IF** posted as **QUERY** parameters.

And stated from OAuth tips from the docs:

> OAuth tips
> 
> The OAuth parameters may be added as query string parameters or included in the Authorization header.
> Note there is no reliable cross-platform way to get the raw request headers in WordPress, **so query string should be more reliable in some cases**.

**Comment by mikejolley** [comment]
@steffanhalv Why are you posting that with query params though?

**Comment by steffanhalv** [comment]
@mikejolley 

See #15218 and #14987 

When accessing wc-api from cross origin through browser, preflight is generated by browser when POST request is used with conten-type application/json in header & this options request is not accepted after the latest wp / wc was upgraded and returns unauthenticated.

**Comment by mikejolley** [comment]
@claudiosanches thoughts?

**Comment by claudiosanches** [comment]
@mikejolley official plugin now accept multidimensional arrays: https://github.com/WP-API/OAuth1/blob/30e4339b7ff5c91817c094bf588235059e8acec7/lib/class-wp-rest-oauth1.php#L721-L743
So I think we can copy this code and do the same.

**Comment by neonics** [comment]
FYI both WP and WooCommerce still have a bug: they sort the parameters too soon.

See https://oauth.net/core/1.0a/#rfc.section.9.1.1 and https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http :

> The request parameters are **collected**, **sorted** and **concatenated** into a normalized string

The parameters are sorted before they are flattened, so not all parameter names are properly collected. Only the top level array keys in the parameter tree are sorted, which in the case of the batch-update-products example would only be the `create` "parameter" (which isn't a real parameter).

The way [WP](https://github.com/WP-API/OAuth1/blob/30e4339b7ff5c91817c094bf588235059e8acec7/lib/class-wp-rest-oauth1.php#L674-L678) and [WooCommerce](https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-authentication.php#L363-L369) flatten the parameters makes it impossible to sort them. An approach [like this](https://github.com/woocommerce/woocommerce/pull/12661/files) is needed to support that.
