### ISSUE TITLE
[3.1.0] Order details in wrong language

### ISSUE THREAD

**Issue by Chrystll** [woocommerce/woocommerce#15414]
Storefront 2.2.3
only WooCommerce 3.1.0-beta
WordPress 4.7.5

To reproduce:
Go to Users > Your profile: set French
Go to Settings > General > Site Language: set English (United States).

The WooCommerce menu (admin sidebar) is in French as expected.

But go to WooCommerce > Orders > edit order: 

* the Order metabox is in English, such as the labels 'General Details', 'Order Status'('Pending payment', 'Processing'..)'Customer', 'Billing details'... 

* the Order actions metabox is in English (except the title) such as 'Resend order emails'.

* the Note metabox is in English (except the title) such as 'Add note', 'Private note', 'Add' button ...

* the Item metabox is in English, such as the 'SKU', the 'Refund', the 'Add item(s)' and the 'Add tax' buttons and also the labels 'Cost', 'Qty',  'Discount', 'Shipping', 'Order total'.

* the Downloadable product permissions metabox is also in English (except the title) such as 'Search for a downloadable product ...) and the 'Grant access' button.

I didn't reproduce this issue when the Site Language and the Admin language are in French.
No issue in WooCommerce 3.0.7

**Comment by claudiulodro** [comment]
@mikejolley I think this is most likely a bug from something in that email change, where order e-mails sent out will be in the site language.
