### ISSUE TITLE
Change order of billing fields on checkout page  

### ISSUE THREAD

**Issue by rdgajera** [woocommerce/woocommerce#15418]
@mikejolley 
I'm using the WC filter to order billing fields, and it worked fine before (WC  @2.9) updating to WooCommerce 3.0.4  
It seems the filter works fine, but for unknown reasons it revert back on the fly to the default order.

function order_fields($fields) {

    $order = array(
        "billing_email", 
        "billing_phone",
        "billing_first_name", 
        "billing_last_name", 
        "billing_country", 
		"billing_state",
        "billing_company", 
        "billing_address_1", 
        "billing_address_2",
		"billing_city", 
        "billing_postcode"
    );
    foreach($order as $field)
    {
        $ordered_fields[$field] = $fields["billing"][$field];
    }

    $fields["billing"] = $ordered_fields;
    return $fields;

}

**Comment by mikejolley** [comment]
Each field needs/has a 'priority' set. Change that rather than reordering the fields manually.

**Comment by rdgajera** [comment]
Can you reference to any example?

**Comment by mikejolley** [comment]
https://businessbloomer.com/woocommerce-move-reorder-fields-checkout-page/
