### ISSUE TITLE
POST REQUEST IN ORDERS NOT WORKING

### ISSUE THREAD

**Issue by chandanbhandari** [woocommerce/woocommerce#15410]
![screenshot 7](https://cloud.githubusercontent.com/assets/20203095/26698703/a6bff7e2-4734-11e7-8347-1435a1ccd2be.png)
![screenshot 8](https://cloud.githubusercontent.com/assets/20203095/26698704/a6c4b926-4734-11e7-9e19-3316c3fe91e1.png)

### EXPLANATION OF THE ISSUE
,am creating an android app of my website .
came to know about woocommerce api.
while trying to GET orders on wc/v2/orders i am able to fetch all orders but for the same POST request not working.
I am using postman for making requests.

### STEPS TO REPRODUCE THE ISSUE

http://34.204.89.28/wp-json/wc/v2/orders?oauth_consumer_key=ck_23ceadc9879168299cbbece8975cebddcb955607&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1496347040&oauth_nonce=2SHU23&oauth_version=1.0&oauth_signature=Yo2pHJTye/EnDYFlzRkpVwdTF1k=

[GET] request working but [POST] showing 401 error

-----------body -------------
{
    "order": {
        "payment_details": {
            "method_id": "bacs",
            "method_title": "Direct Bank Transfer",
            "paid": True
        },
        "billing_address": {
            "first_name": "John",
            "last_name": "Doe",
            "address_1": "969 Market",
            "address_2": "",
            "city": "San Francisco",
            "state": "CA",
            "postcode": "94103",
            "country": "US",
            "email": "john.doe@example.com",
            "phone": "(555) 555-5555"
        },
        "shipping_address": {
            "first_name": "John",
            "last_name": "Doe",
            "address_1": "969 Market",
            "address_2": "",
            "city": "San Francisco",
            "state": "CA",
            "postcode": "94103",
            "country": "US"
        },
        "customer_id": 2,
        "line_items": [
            {
                "product_id": 83470,
                "quantity": 2
            
        ],
        "shipping_lines": [
            {
                "method_id": "flat_rate",
                "method_title": "Flat Rate",
                "total": 10
            }
        ]
    }
}
-------------body ends------------

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#server-does-not-support-postdeleteput

**Comment by tahirhameed** [comment]
i am facing some problem in woocommerce order create api can you guide to fix my issue 

when i post 
line_items array  


                                    

@"line_items": @[ @{ @"product_id": @380, @"quantity": @1, @"meta_data": @[ @{ @"key": @"Booking Date", @"value": @"July 05, 2017" }, @{ @"key": @"Booking Time", @"value": @"4:30 pm" }, @{ @"key": @"Duration", @"value": @"45 minutes" } ] } ],

{

    "code": "woocommerce_rest_authentication_error",

    "message": "Invalid signature - provided signature does not match.",

    "data": {

        "status": 401

    }


}



this error returing from woocommerce server but when i post without line_items array its working fine 



waiting for positive response
