### ISSUE TITLE
multiple entry for the  "_price"  in post_meta table in recent woocommerce update

### ISSUE THREAD

**Issue by krunal05** [woocommerce/woocommerce#15422]
![capture](https://cloud.githubusercontent.com/assets/29148393/26733870/2ed24270-478a-11e7-982d-5edae5d53b29.JPG)
### EXPLANATION OF THE ISSUE

As shown in the Image,

The Product in the Blue mark are added during the previous version of the woocommerce and the product in the red was added after the update of woocommerce.

The Red Product has value $124 , so it should appear first when we Sort by Price : Low to High

But instead during the Query it is picking up the higher value of "_price" from the meta Table.

How could I solve this Issue without affecting or creating new issues?

https://github.com/woocommerce/woocommerce/issues/12997

Woocommerce developers' has suggested me the above discussion link, but it looks like there is no solution provided in the link, instead there is a detail about the same issue.

Even i have created a ticket on Woocommerce 
https://woocommerce.com/my-account/tickets/?id=579002

Is there any solution for this issue?

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
This is part of the upcoming 3.1 release.
