### ISSUE TITLE
Wordpress N-Media WooCommerce Personalized Product Option Manager

### ISSUE THREAD

**Issue by fabiofernandes12** [woocommerce/woocommerce#15423]
Im working on a WordPress site with Woo-Commerce. I'm having a problem with Woo-Commerce Personalized Product Option Manager.

The client can upload a file but that file doesn't appear on admin order (_product_attached_files:A) <- it comes this way and has No file is attached/uploaded.

Anyone know why?

**Comment by mikejolley** [comment]
This is not a plugin we maintain, contact the dev.
