### ISSUE TITLE
Change order of billing fields on checkout page

### ISSUE THREAD

**Issue by rdgajera** [woocommerce/woocommerce#15426]
Hi @mikejolley ,

I created the filter to change the sequence billing details fields on woocommerce checkout page. 
But the problem is that the default cursor is still coming on "First Name". I wanna change it to "Email Address" as default. 

Here, is my code. 

----------------------------------------------------CODE---------------------------------------------------------

add_filter("woocommerce_checkout_fields", "custom_order_fields");

function custom_order_fields($fields) {
	$order = array(
		"billing_email", 
		"billing_phone", 
		"billing_first_name", 
		"billing_last_name",
		"billing_country" ,
		"billing_address_1", 
		"billing_address_2",		
		"billing_postcode"
	);

	foreach($order as $field)
	{
		$ordered_fields[$field] = $fields["billing"][$field];
	}

	$fields["billing"] = $ordered_fields;

	$fields['billing']['billing_address_1']['placeholder'] = '';
	$fields['billing']['billing_address_2']['placeholder'] = '';
	$fields['billing']['billing_phone']['placeholder'] = '';
	//$fields['billing']['billing_address_2']['label'] = __( 'City', 'blank' );
	//$fields['billing']['billing_phone']['label'] = __( 'Phone number', 'blank' );

	return $fields;
}

$fields['billing']['billing_email']['priority'] = 1;
$fields['billing']['billing_phone']['priority'] = 2;
$fields['billing']['billing_first_name']['priority'] = 3;
$fields['billing']['billing_last_name']['priority'] = 4;
$fields['billing']['billing_country']['priority'] = 5;
$fields['billing']['billing_address_1']['priority'] = 6;
$fields['billing']['billing_address_2']['priority'] = 7;

---------------------------------------------------CODE----------------------------------------------------------

Thanks in advance.

**Comment by mikejolley** [comment]
@rdgajera Please don't treat Github like a support forum. You can also comment on closed issues.

```
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
```

Cursor will still default to the first field loaded - the reordering is done with javascript. You can combine your last snippet with the priorities if needed.
