### ISSUE TITLE
Deprecated id in REST API (v2)

### ISSUE THREAD

**Issue by stodorovic** [woocommerce/woocommerce#15437]
### EXPLANATION OF THE ISSUE

When a client gets data using REST API (v2), we see notice in `debug.log`.

### STEPS TO REPRODUCE THE ISSUE

Example for request:
`https://yourwebsite.com/wc-api/v2/orders.....`

debug.log:
```
PHP Notice:  id est appelée de la mauvaise manière. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Legacy_API->handle_rest_api_requests, WC_Legacy_API->handle_v2_rest_api_request, WC_API_Server->serve_request, WC_API_Server->dispatch, call_user_func_array, WC_API_Orders->get_orders, WC_API_Orders->get_order, apply_filters('woocommerce_api_order_response'), WP_Hook->apply_filters, call_user_func_array, WC_API_Resource->maybe_add_meta, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Veuillez lire <a href="https://codex.wordpress.org/Debugging_in_WordPress">Débugger dans WordPress</a> (en) pour plus d’informations. (Ce message a été ajouté à la version 3.0.) in ...../wp-includes/functions.php on line 4138
```

I was able to found line:

https://github.com/woocommerce/woocommerce/blob/master/includes/api/legacy/v2/class-wc-api-resource.php#L286

When I change `$resource->id` with `$resource->get_id()`, I don't see this notice.  I'm not sure, is it good fix or no. I hope that you will fix it in next release because there are a lot of record in the logs.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15446
