### ISSUE TITLE
WooCommerce checkout steps

### ISSUE THREAD

**Issue by daniel-bios** [woocommerce/woocommerce#15436]
I have this website www.bios-downloads.com with WoCommerce integrated , where i have uploaded  downloadable files , and when A user wants to download a file , he should procceed in some steps like in the attachement:

How can it be reduced these steps in a single one , so that he can download directly a product?

![1](https://cloud.githubusercontent.com/assets/25803569/26752905/993e707c-485a-11e7-97f0-8b7423fc1ec3.png)
![2](https://cloud.githubusercontent.com/assets/25803569/26752903/9939ca54-485a-11e7-8571-46a838e2945d.png)
![3](https://cloud.githubusercontent.com/assets/25803569/26752902/993920b8-485a-11e7-84ae-2179c9e9333b.png)
![4](https://cloud.githubusercontent.com/assets/25803569/26752904/993bfdec-485a-11e7-9a1a-067f1f3c3b4a.png)

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
If you're not selling downloads, and just want to give it to them I don't think a product is the best thing for this.

You could setup an external product and give the product URL a direct link to the download, but it may be best to look at an alternative solution unless you will need to sell access to them in future.
