### ISSUE TITLE
product slider not working for rtl on woocommerce update

### ISSUE THREAD

**Issue by LucyTech** [woocommerce/woocommerce#15438]
### EXPLANATION OF THE ISSUE

I updated to woocommerce Version 3.0.7
I'm using the Storefront theme Version: 2.2.3
My site is multilingual
The product slider is working as it should on the English product pages.
However on the Hebrew pages the slider is moving in the wrong direction and the images are not showing in the image area on the page. .woocommerce-product-gallery__image is not working for RTL. It could be the javascript code is not supporting RTL. 
[image](https://cloud.githubusercontent.com/assets/1766837/26759803/f32382c8-4911-11e7-8f5b-015e83dc06ef.png)
### STEPS TO REPRODUCE THE ISSUE

Install woocommerce
Install storefront
Create Hebrew product with images

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://storenet.co.il
Site URL: http://storenet.co.il
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (25) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.13
All In One WP Security: by Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.2.7

BackupBuddy: by iThemes – 7.1.6.1
Better Font Awesome: by MIGHTYminnow & Mickey Kay – 1.6.0
Cross Sell Product Display For Woocommerce: by Codextent – 1.0
Easy Video Player: by naa986 – 1.1.6
Embed Any Document: by Awsm Innovations – 2.3
Homepage Control: by WooThemes – 2.0.2
MailChimp for WordPress: by ibericode – 4.1.3
Max Mega Menu: by Tom Hemsley – 2.3.6
Menu Image: by Alex Davyskiba aka Zviryatko – 2.7.0
Meta Slider: by Matcha Labs – 3.5.1
Restrict Widgets: by dFactory – 1.3.1
Search & Filter Pro: by Designs & Code – 2.3.3
WPML Multilingual CMS: by OnTheGoSystems – 3.7.1
Storefront Add Slider: by Pangolin Themes – 0.3
Storefront Blog Excerpt: by Wooassist – 1.1.2
Storefront Homepage Extra Sections: by WPDevHQ – 1.0.2
WooCommerce Product Feed Pro: by WebAppick – 2.1.4
WooCommerce Multilingual: by OnTheGoSystems – 4.1.4
WooCommerce: by Automattic – 3.0.7
WPML Media: by OnTheGoSystems – 2.2.0
WPML String Translation: by OnTheGoSystems – 2.5.4
WPML Translation Management: by OnTheGoSystems – 2.3.1
YITH WooCommerce Compare: by YITHEMES – 2.2.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #36 - /en/shop/
Cart: #37 - /en/cart-2/
Checkout: #38 - /en/checkout-2/
My account: #39 - /en/my-account-2/

### Theme ###

Name: StoreNet
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storenet/archive-product.php
storenet/woocommerce/content-single-product.php
storenet/woocommerce/single-product.php

`
</details>

**Comment by mikejolley** [comment]
This is latest storefront (not a child theme like you're using) and WC 3.0.7:

![2017-06-05 10 21 23](https://cloud.githubusercontent.com/assets/90977/26778346/cc371086-49d8-11e7-9253-7922a76fef65.gif)

Seems to support RTL just fine. Suggest you look at your child theme CSS.

**Comment by LucyTech** [comment]
I switched off the child theme and put up the storefront theme and it still doesn't work for the Hebrew site. http://storenet.mgtestsite.com/product/%D7%9E%D7%97%D7%A9%D7%91-%D7%A0%D7%99%D7%99%D7%93-lenovo-thinkpad-p50-20en001mus/

**Comment by mikejolley** [comment]
My gif above shows it's working.

Nothing JS based is going to work on your store whilst it's riddled with errors: https://dl.dropboxusercontent.com/s/ehba7a2391zkgb1/2017-06-05%20at%2011.02.png

**Comment by LucyTech** [comment]
I have fixed all the JS errors. 
I swiched off all the plugins and the images still did not show. 
I'm using the latest storefront theme. 
It works on the English site as expected but does not work on the Hebrew site. 
English site : http://storenet.mgtestsite.com/en/product/lenovo-image-slider-example-for-debug/
Hebrew site:  http://storenet.mgtestsite.com/product/%D7%9E%D7%97%D7%A9%D7%91-%D7%A0%D7%99%D7%99%D7%93-lenovo-thinkpad-p50-20en001mus/
It looks like a bug to me.  Please can you help me with this. Thanks

**Comment by mikejolley** [comment]
You are missing a float:left on the figure element.

**Comment by LucyTech** [comment]
could you please post the exact css change needed? 
I added (in the child theme) `.woocommerce-product-gallery__image.flex-active-slide {
    float:right !important;
}
.woocommerce-product-gallery__image{
    float:right !important;
}`
but it only fixes the featured image. The other images in the slider are still in the incorrect place.

**Comment by mikejolley** [comment]
Style the .woocommerce-product-gallery__wrapper element. This is the figure.

**Comment by LucyTech** [comment]
I added 
.woocommerce-product-gallery__wrapper{
float: left !important; 
} it didn't fix it. 
Could it be a javascript issue? It seems the slideshow is going the wrong way. 
http://storenet.mgtestsite.com/product/%D7%9E%D7%97%D7%A9%D7%91-%D7%A0%D7%99%D7%99%D7%93-lenovo-thinkpad-p50-20en001mus/

**Comment by mikejolley** [comment]
I'm not sure - I tested with RTL tested plugin for my gif above and had no issue which makes me thing it's your child theme or a customisation.

**Comment by LucyTech** [comment]
I can't figure out what is causing the issue. 
Could I give you a login to my site and you can have a look? Can I sent it to you privately?
Thanks

**Comment by LucyTech** [comment]
Woocommerce support said:
There is indeed a compatibility issue between Storefront and the multilingual plugin you're using (WPML). While Storefront is set up for RTL sites, it looks for the site-wide language setting.
It appears that you have WPLANG installed at a top level site, which is not changing the site-wide language but rather only the front-end display. This is what's been causing the trouble!

But they did not give me a working fix for the slideshows.

**Comment by webbos** [comment]
Di you figure this out? I have the same problem with my gallery on "Newspaper theme".

**Comment by LucyTech** [comment]
It seems it is a conflict with the storefront-homepage-extra-sections plugin, they are using an older version of flexslider which is causing conflict with the new woocommerce flexslider version. Maybe your theme is using something similar. I haven't found a perfect fix yet.

**Comment by webbos** [comment]
But i have tried it with twenty seventeen theme, and the issue persists.

So its not a theme problem necessary

**Comment by MrMajidAsadi** [comment]
all you need to do is just set direction for gallery wrapper to rtl.
and somehow limit this direction to just for rtl languages
here is how i do this (my site just need rtl language):
.woocommerce-product-gallery
{
    direction: ltr;
}
