### ISSUE TITLE
WooCommerce update problem

### ISSUE THREAD

**Issue by daniel-bios** [woocommerce/woocommerce#15435]
I have WooCommerce 2.6.14 and when I update the Woocomerce, some of the existing configurations are changed , and they are not saved. 
But , since there has passed a long time now , I cannot identify the configurations that i have made at the existing  WooCommerce 2.6.14 .How can I update and also save the configurations that I have made ?
 Thank you

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
See the notes on updating custom code for 3.0 compatibility here https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes
