### ISSUE TITLE
Product Stock Doesn't Match Actual Order Count

### ISSUE THREAD

**Issue by JonnyLinja** [woocommerce/woocommerce#15431]
## EXPLANATION OF THE ISSUE

We recently released a product for preorder on May 30 which has limited stock. I noticed recently that the numbers don't add up and we want to avoid the possibility of overselling.

## STEPS TO REPRODUCE THE ISSUE

I'll endeavor to showcase 3 ways to prove that there is actually a stock count issue. Note that I've changed the actual values of the product name, table names, and IDs for privacy purposes. The prices and the stocks are the actual values.

### > PREPARATION: Querying for number sold (213) and current stock (188)

First, here's the query for the number sold. `SELECT * FROM wpdb_postmeta WHERE post_id = 12345;` The result is several meta fields, one of which is `total_sales` with a value of `213` and `_stock` with a value of `188` as of the writing of this post.

Note that `188` matches the stock count shown in wp-admin's product page.

![screen shot 2017-06-02 at 4 04 05 pm](https://cloud.githubusercontent.com/assets/684861/26744074/64ac34f0-47b2-11e7-987a-c1730e107087.png)

### > DISCREPANCY 1: There's 223 Processing Orders of the product, 223 > 213

I log into wp-admin and go to woocommerce orders. There are currently `245` processing orders and `8` on hold orders. As the product is on preorder, the stock count can only be affected by these two.

The product costs around `$250`. So, I click on processing orders and sort by cost in ascending order. You'll notice that the first page has `20` values that are too small to be our latest product, and the second page has `2` values that are too small to be our product.

![screen shot 2017-06-02 at 4 07 18 pm](https://cloud.githubusercontent.com/assets/684861/26744537/65e5741a-47b4-11e7-9d47-1a239bf9364b.png)
_screenshot shows 20 rows of other miscellaneous products as they are too small_

![screen shot 2017-06-02 at 4 07 56 pm](https://cloud.githubusercontent.com/assets/684861/26744631/b9dcee90-47b4-11e7-8214-449b37b8d52f.png)
_screenshot shows 2 rows of other miscellaneous products as they are too small_

That means we have at least `245 - 22 = 223` orders. Plus, this doesn't account for orders on hold, which are all also our preorder product, so let's add `8` to make `231` orders.

This does not correspond to the number sold that woocommerce is reporting (`213`) at all. Keep in mind that these are ORDERS, and several people purchase more than one of our product in a single order, so the actual number sold is GREATER than `231`. Quite a few purchase 2 products in a single order, and a few folks purchase larger amounts.

### > DISCREPANCY 2: Paypal Export Count is > 213

The full PayPal information is a little too private to give out, but I will describe the process that showed that we have more than `213` sold.

We exported the sales since the launch of our preorder and created a column in the spreadsheet with `=round(J731/249,0)`. This divides the net amount in column J by `249` and rounds it to approximate the number of products purchased given a $ amount. We then sum that new column K with `=QUERY( E2:K735 , "Select SUM(K) WHERE E = 'Website Payment' AND (K > 0)" )`

The number we got here was GREATER than `213` which is the number sold.

### > DISCREPANCY 3: SQL queries indicate 292 were sold, 292 > 213

I attempted to query the database for the total number sold by summing up all the quantities. My query is as follows.

```
SELECT SUM(meta_value)
FROM wpdb_woocommerce_order_itemmeta
LEFT JOIN wpdb_woocommerce_order_items
ON wpdb_woocommerce_order_items.order_item_id = wpdb_woocommerce_order_itemmeta.order_item_id
LEFT JOIN wpdb_posts
ON wpdb_posts.ID = wpdb_woocommerce_order_items.order_id
WHERE order_item_name = 'UNIQUE PRODUCT NAME HERE'
AND meta_key = '_qty'
AND (post_status = 'wc-on-hold'
OR post_status = 'wc-processing')
```

The result is `292`. Help verifying if I wrote this query correctly would be appreciated as well as we're trying to determine exactly how many were actually preordered.

![screen shot 2017-06-02 at 4 31 50 pm](https://cloud.githubusercontent.com/assets/684861/26743972/eb0c9b1c-47b1-11e7-8322-5ae0769eb206.png)

## SYSTEM STATUS

<details>

```
### WordPress Environment ###

Home URL: http://squatsandscience.com
Site URL: http://squatsandscience.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.27
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_c8h9w7n1yh_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (21) ###

WP Author Bio: by penguininitiatives – 1.5.5
LayerSlider WP: by Kreatura Media – 5.6.5
Akismet Anti-Spam: by Automattic – 3.3.2
Envato WordPress Toolkit: by Envato – 1.7.3
Error Log Monitor: by Janis Elsts – 1.5.2
Fast Secure reCAPTCHA: by Mike Challis – 1.0.19
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.0.0.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.11.2.1
Ni WooCommerce Order Export: by anzia – 2.1.5
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
PayPal Multiple Emails for WooCommerce: by Jeff Sherk – 1.2.0
ExportFeed - Create Product Feeds For 40+ Merchants: by ExportFeed.com – 3.1.7.8
Qode Instagram Widget: by Qode Themes – 1.0
Go Daddy Quick Setup: by GoDaddy.com
LLC – 1.06

Smart Manager: by StoreApps – 3.9.21
WooCommerce: by Automattic – 3.0.7
WooThemes Helper: by WooThemes – 1.5.9 – Network enabled
Wordfence Security: by Wordfence – 6.3.10
WP User Avatar: by flippercode – 2.0.8
WP User Manager: by Alessandro Tesoro – 1.4.3
WP101 Video Tutorials: by WP101Plugin.com – 0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #11313 - /shop-2/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/

### Theme ###

Name: Bridge
Version: 11.0
Author URL: http://www.qodethemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: bridge/woocommerce/cart/cart-empty.php
bridge/woocommerce/cart/cart-shipping.php
bridge/woocommerce/cart/cart-totals.php
bridge/woocommerce/cart/cart.php
bridge/woocommerce/cart/shipping-calculator.php
bridge/woocommerce/checkout/form-coupon.php
bridge/woocommerce/checkout/thankyou.php
bridge/woocommerce/content-product.php
bridge/woocommerce/content-single-product.php
bridge/woocommerce/global/form-login.php
bridge/woocommerce/global/quantity-input.php
bridge/woocommerce/loop/add-to-cart.php
bridge/woocommerce/loop/loop-start.php
bridge/woocommerce/loop/pagination.php
bridge/woocommerce/loop/rating.php
bridge/woocommerce/loop/result-count.php
bridge/woocommerce/loop/sale-flash.php
bridge/woocommerce/myaccount/form-login.php
bridge/woocommerce/myaccount/form-lost-password.php
bridge/woocommerce/myaccount/my-address.php
bridge/woocommerce/myaccount/my-orders.php
bridge/woocommerce/single-product/add-to-cart/external.php
bridge/woocommerce/single-product/add-to-cart/grouped.php version 3.0.3 is out of date. The core version is 3.0.7
bridge/woocommerce/single-product/add-to-cart/simple.php
bridge/woocommerce/single-product/add-to-cart/variable.php
bridge/woocommerce/single-product/related.php
bridge/woocommerce/single-product/sale-flash.php
bridge/woocommerce/single-product/tabs/additional-information.php
bridge/woocommerce/single-product/tabs/description.php
bridge/woocommerce/single-product/tabs/tabs.php
bridge/woocommerce/single-product/up-sells.php

Outdated Templates: ❌Learn how to update
```
</details>

**Comment by mikejolley** [comment]
Total sold and stock have no relation whatsoever. I'd suggest you verify stock is correct and ignore sold for now. 

Stock has a more robust update method than sold. Sold is only used for sorting by popularity. Not in stats or reports.

**Comment by mikejolley** [comment]
There are a few other flaws with this bug report;

1. It's not clear if these products/sales were made before or after 3.0.x. Before 3.0 total sales was simply incremented and was not as accurate as 3.0.x (as pointed out above this is not used in reporting, just for a few sorting params, so accuracy is not critical)

2. If a product has the same price, or the title was ever changed, these queries would be off.

3. If products were imported, or total_sales was ever manually set this would not be accurate.

I suspect total_sales is simply out of sync. As long as the STOCK figure is correct, this is not an issue. We don't have a bulk update of total sales due to the massive number of queries which would required to update these values.

The only issue you may encounter with stock is https://github.com/woocommerce/woocommerce/issues/13359 which can affect high traffic sites.
