### ISSUE TITLE
get_formatted_legacy Notice

### ISSUE THREAD

**Issue by jamesckemp** [woocommerce/woocommerce#15443]
### EXPLANATION OF THE ISSUE

On Woo 3.0.7. I'm doing some code updates and one of the warning notices reads:

`[05-Jun-2017 07:15:13 UTC] PHP Notice:  [05-Jun-2017 07:15:13 UTC] PHP Notice:  get_formatted_legacy is <strong>deprecated</strong> since version 2.4! Use Item Meta Data is being called with legacy arguments instead. in /app/public_html/wp/wp-includes/functions.php on line 3830`

This notice seems wrong to me?

**Comment by mikejolley** [comment]
Be aware that entire class is deprecated.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15446
