### ISSUE TITLE
Sku not changing when variation selected

### ISSUE THREAD

**Issue by Anthonipples** [woocommerce/woocommerce#15445]
### EXPLANATION OF THE ISSUE

On version 3.0.7 I have a range of beds, when I select a variation (single bed etc) the sku remains as the parent sku, if i remove the parent sku then no sku is shown at all, am I perhaps missing this functionality somewhere?

### STEPS TO REPRODUCE THE ISSUE

Added product, added variations with sku's 
go to frontend then change variation, no variation displayed if no parent sku, if parent sku then sku only displays parent sku

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
This is working. I suspect a theme issue; the javascript code which updates the SKU requires some specific classnames for the SKU display for it to know what to update.

https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js#L182

If the theme changes this, it cannot update.
