### ISSUE TITLE
[3.1.0] Variable Products can directly added to cart without choosing an option

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/woocommerce#15449]
### EXPLANATION OF THE ISSUE

The variable product will be shown as simple product an can be added to the cart without choosing an option:
<img width="268" alt="bildschirmfoto 2017-06-05 um 14 56 45" src="https://cloud.githubusercontent.com/assets/25877146/26784703/3fa991a8-49ff-11e7-80de-60e2f00b3e67.png">

The product details:
<img width="711" alt="bildschirmfoto 2017-06-05 um 14 59 45" src="https://cloud.githubusercontent.com/assets/25877146/26784798/ad5b3080-49ff-11e7-83c1-37f9034173fa.png">

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://eval.firewoodshop.ch
Site URL: https://eval.firewoodshop.ch
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 7.1.5
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: fws_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.0-beta

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CHF (CHF)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /warenkorb/
Checkout: #7 - /kasse/
My account: #8 - /mein-konto/

### Theme ###

Name: Storefront
Version: 2.2.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/uq8whpoumdafw8j/2017-06-05%20at%2014.22.png

Bit thin on details don't you think. How was this product made? Does it have variations? Is it definitely variable? Only storefront?

**Comment by thomas-zg** [comment]
These are the product details:
<img width="784" alt="bildschirmfoto 2017-06-05 um 15 33 10" src="https://cloud.githubusercontent.com/assets/25877146/26785761/5367fffe-4a04-11e7-867c-be9307f37485.png">

It looks the same with Twenty Seventeen.

The product was created with a 3.0.x release version, now I'm replacing the woocommerce folder with the current beta.

**Comment by mikejolley** [comment]
No, but it would be good to try a new product to narrow it down?

**Comment by thomas-zg** [comment]
I'm adding a new product:
<img width="181" alt="bildschirmfoto 2017-06-05 um 15 52 19" src="https://cloud.githubusercontent.com/assets/25877146/26786448/fe23f900-4a06-11e7-9aec-d0b689378a26.png">

<img width="790" alt="bildschirmfoto 2017-06-05 um 15 53 23" src="https://cloud.githubusercontent.com/assets/25877146/26786550/4ee1da4c-4a07-11e7-81ea-a0e0e30835cd.png">

<img width="792" alt="bildschirmfoto 2017-06-05 um 15 53 33" src="https://cloud.githubusercontent.com/assets/25877146/26786560/556a0182-4a07-11e7-858e-f5b4b3bcd471.png">

<img width="788" alt="bildschirmfoto 2017-06-05 um 15 53 39" src="https://cloud.githubusercontent.com/assets/25877146/26786566/5b3d67a2-4a07-11e7-8e8b-09db6829d7b7.png">

<img width="788" alt="bildschirmfoto 2017-06-05 um 15 53 46" src="https://cloud.githubusercontent.com/assets/25877146/26786574/604f6fce-4a07-11e7-939e-2a0950c63027.png">

<img width="616" alt="bildschirmfoto 2017-06-05 um 15 54 13" src="https://cloud.githubusercontent.com/assets/25877146/26786582/65bc45f4-4a07-11e7-97cd-b3a5f62e6fe8.png">

<img width="786" alt="bildschirmfoto 2017-06-05 um 15 54 33" src="https://cloud.githubusercontent.com/assets/25877146/26786586/6b092cc0-4a07-11e7-8ace-18f8538a03e2.png">

**Comment by mikejolley** [comment]
Simply not happening here.  Also when I view your site, I see 'select options' , not add to cart.

**Comment by thomas-zg** [comment]
I recreated the database from ground and add a new variable product. The product looks fine.
But I also used the copy of the production database and do see the same behaviour as I reported. I'll do some more research.

**Comment by thomas-zg** [comment]
Mike, try to add a simple product and change it later on to a variable one. With this scenario, i can reproduce the behaviour and the add to cart is shown. Checkout the «Simple to Variable Product 3» on my test page.

**Comment by mikejolley** [comment]
@thomas-zg your comment disappeared but even switching type and adding variations it works as intended.

Without variations it says 'read more'.

**Comment by thomas-zg** [comment]
Sorry for the confusion, the browser didn't properly refresh the page.

Just to let you know, I do see the same in a copy of my production database which is running properly with 3.0.7 but not with 3.1.0. The products on the scrennshot are alle variable products.

with 3.0.7:
<img width="1247" alt="bildschirmfoto 2017-06-05 um 18 18 00" src="https://cloud.githubusercontent.com/assets/25877146/26792639/5f594b76-4a1b-11e7-982a-06568780f9d3.png">

same DB with 3.1.0:
<img width="1201" alt="bildschirmfoto 2017-06-05 um 18 13 39" src="https://cloud.githubusercontent.com/assets/25877146/26792662/6d821854-4a1b-11e7-8adb-de02e332f4ea.png">

**Comment by mikejolley** [comment]
Where are you seeing this? I don't see it on your example URL in status report.

**Comment by mikejolley** [comment]
Also you're the only person to report this so far FWIW.

**Comment by thomas-zg** [comment]
with 3.1.0: https://beta.firewoodshop.ch/produkt-kategorie/barbecue-smoker-holz/wood-chunks/
with 3.0.7: https://staging.firewoodshop.ch/produkt-kategorie/barbecue-smoker-holz/wood-chunks/

**Comment by thomas-zg** [comment]
@mikejolley try to duplicate a variable product, just change the title and publish it. I created https://eval.firewoodshop.ch/produkt/variable-product-2/ that way.

**Comment by thomas-zg** [comment]
#15398 fixes the issue
