### ISSUE TITLE
Product Backend Doesn't Match Product Data

### ISSUE THREAD

**Issue by anphira** [woocommerce/woocommerce#15442]
### EXPLANATION OF THE ISSUE & STEPS TO REPRODUCE THE ISSUE

I'm using Storefront (child theme) and did try disabling all plugins except WooCommerce.

On the edit product screen I have code which adds some content to the Product Data general area

`$product = wc_get_product(get_the_ID());
	if ( $post->post_status == 'draft' && ! $product->get_manage_stock() ) {
		$product->set_manage_stock(true);
		$product->set_stock_quantity(1);
		$product->set_shipping_class_id(28);
		$product->save();
    }`

This runs in add_action( 'woocommerce_product_options_general_product_data', 'woo_add_custom_general_fields' );

If I var_dump($product) then I see that the manage stock is in fact set to true, that the shipping class is in fact set. However, when I click over to the Inventory and Shipping tabs the check box for manage stock is NOT checked and the shipping class is NOT selected.

I can click save draft several times, publish, and on the front end I can clearly add the item to cart, but on the edit product screen the box is still not checked and the shipping class is still not selected. I can manually select them and then they stay selected (the data does not change at all what's printed out).

I know a lot of people need to programmatically set up defaults and modify products with code. So this displaying of the edit screen not matching what's actually set in the data is really upsetting.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://woodemo.dev
Site URL: http://woodemo.dev
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1k

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Advanced Custom Fields: by Elliot Condon – 4.4.11
FacetWP: by FacetWP
LLC – 2.8.7

WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
WooCommerce Work Vendors: by WooCommerce – 2.0.30
WooCommerce: by Automattic – 3.0.7
WP Smush: by WPMU DEV – 2.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront Artclick
Version: 2.1.8
Author URL: https://woocommerce.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8 – 2.2.3 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/.DS_Store
storefront-child/woocommerce/archive-product.php
storefront-child/woocommerce/content-single-product.php
storefront-child/woocommerce/single-product/tabs/tabs.php

`
```
</details>

**Comment by mikejolley** [comment]
Look at where the data is set.

https://github.com/woocommerce/woocommerce/blob/db012b3a126b4ba0304804ee69ef58652f2b4ced/includes/admin/meta-boxes/views/html-product-data-general.php#L159

`$product_object` already exists by that point. 

https://github.com/woocommerce/woocommerce/blob/fe4a4a7e834198288ae26fc9131ef13b2d043669/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L31

You are updating a separate instance of it. So your changes won't appear to take any effect until next load, and your changes will also prevent those values being set whilst a product is a draft so it's not great anyway.

Target global `$product_object`.
