### ISSUE TITLE
Out of stock Products, Still showing in product count in catergories

### ISSUE THREAD

**Issue by simon369** [woocommerce/woocommerce#15455]
### EXPLANATION OF THE ISSUE

I have over 8000 products on my woocommerce, with only around 2000 actually being in stock. I have under stock management to hide out of stock products. Which does hide them, however when you navigate to a catergory its showing the total count of products. Including once which are out of stock. Then when you click on a catergory which has say 500 products in total but only 10 in stock. ITs showing 25 pages with no products in. 

### STEPS TO REPRODUCE THE ISSUE

https://casivu.co.uk/product-category/electronics/electronics-electronic-accessories-gadgets/

is showing that the catergory alarm clocks has 32 products in, however when you click it and go to https://casivu.co.uk/product-category/electronics/electronics-electronic-accessories-gadgets/electronics-electronic-accessories-gadgets-alarm-clocks/ , 

it has 4 blank pages with only 1 product in stock 

### SYSTEM STATUS

<details>

`
### WordPress Environment ###

Home URL: https://casivu.co.uk
Site URL: https://casivu.co.uk
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) mod_hive/6.6 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.0.19
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wpx0_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Add Shortcodes Actions And Filters: by Michael Simpson – 2.0.9
Contact Form 7: by Takayuki Miyoshi – 4.7
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.0.0.1
Jetpack by WordPress.com: by Automattic – 4.9
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SG Optimizer: by SiteGround – 3.3.1
WooCommerce Auto Category Thumbnails: by Shellbot – 1.1
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.14
WooCommerce Google Product Feed: by Lee Willis – 7.0.7 – 7.1.2 is available
WooCommerce Sort By Stock: by Brandon Yanofsky – 2.2.0
WooCommerce: by Automattic – 3.0.7
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 4.7.1
WP-Lister Pro for eBay: by Matthias Krok – 2.0.20
Yoast SEO: WooCommerce: by Team Yoast – 4.4
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #64 - /shop/
Cart: #63 - /cart/
Checkout: #62 - /checkout/
My account: #61 - /my-account/

### Theme ###

Name: Flatsome
Version: 3.3.2
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php version 3.0.0 is out of date. The core version is 3.0.3
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php version 3.0.0 is out of date. The core version is 3.0.2
flatsome/woocommerce/single-product/product-thumbnails.php version 3.0.0 is out of date. The core version is 3.0.2
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

</details>

**Comment by mikejolley** [comment]
Are these products imported with an earlier version of `WooCommerce Product CSV Import Suite`?

You have missing data. The products will be missing the `outofstock` term of the `Product Visibility` taxonomy.

Saving them in admin should update this. Or run this Code in your theme functions.php file once:

```
global $wpdb;
if ( $outofstock_term = get_term_by( 'name', 'outofstock', 'product_visibility' ) ) {
		$wpdb->query( $wpdb->prepare( "INSERT IGNORE INTO {$wpdb->term_relationships} SELECT post_id, %d, 0 FROM {$wpdb->postmeta} WHERE meta_key = '_stock_status' AND meta_value = 'outofstock';", $outofstock_term->term_taxonomy_id ) );
	}
```

**Comment by Libertie** [comment]
@mikejolley, I'm having this problem under the same circumstances and tried using the code you suggested but `get_term_by( 'name', 'outofstock', 'product_visibility' )` returns no result. Saving an out-of-stock product in the admin doesn't seem to work either. Can you recommend a next step? Thank you!

## System Status ##
<details> 

### WordPress Environment ###

Home URL: http://blazingshuttles.com
Site URL: http://blazingshuttles.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (16) ###

Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.1

Contact Form 7: by Takayuki Miyoshi – 4.8
Facebook Widget: by Milap Patel – 4.2
Google Analyticator: by SumoMe – 6.5.3
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Resize images before upload: by Simon @ WPsites – 1.8
Storefront Product Sharing: by WooThemes – 1.0.4
Storefront Sticky Add to Cart: by WooThemes – 1.1.6
The Events Calendar: by Modern Tribe
Inc. – 4.5.8

WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce USPS Shipping: by WooCommerce – 4.4.8
WooCommerce: by Automattic – 3.1.1
WooSidebars: by WooThemes – 1.4.3
YITH Plugin Framework Temporary Fix: by YITHEMES – 1.0.0
YITH WooCommerce Gift Cards Premium: by YITHEMES – 1.6.9
NextGEN Gallery: by Imagely – 2.2.10

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #15 - /shop/
Cart: #16 - /cart/
Checkout: #17 - /checkout/
My account: #18 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by arsoboy** [comment]
Hello @mikejolley, i've the same issue which is disturbing site's product grid view.
i'd run above code once but no luck yet.

started a thread 5 days ago regarding this issue on woocommerce plugin support.
here are my system details & response of this code
`get_term_by( 'name', 'outofstock', 'product_visibility' )`

https://wordpress.org/support/topic/out-of-stock-products-are-still-counting-in-loop-on-shopcategory-archive-pages/

$wp_query response:
[wp_query-response.txt](https://github.com/woocommerce/woocommerce/files/1161921/wp_query-response.txt)

please guide.

**Comment by remilopes** [comment]
Same issue that's been driving me nuts for days : In my categories some page display as low as 5 products and the next one will show 9. These pages are supposed to display 12 products, the hidden ones are the out of stock ones. 

How to remove them from being counted in the results if they are out of stock ?

**Comment by mikejolley** [comment]
@arsoboy fixed his and found a plugin conflict https://wordpress.org/support/topic/out-of-stock-products-are-still-counting-in-loop-on-shopcategory-archive-pages/

**Comment by mikejolley** [comment]
I'm locking this issue because the original post was resolved and a few solutions have been posted already.
