### ISSUE TITLE
[3.1.0] Issue with one-digit prices

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#15458]
Testing 3.1.0, I'm not able anymore to edit prices with one digit like 8,50 for example. The issue exists for regular and sales prices.
8,5 or 8,50 as a regular price led to a correct meta of _regular_price 8.50 but the returned price in the admin screen is 850€ as well as in the front end. The effect doesn't occur for a price of 8,51 which lead to a meta of 8.51 and get displayed in the frontend as 8,51€

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/15457
