### ISSUE TITLE
Add order manually

### ISSUE THREAD

**Issue by yannhilaire** [woocommerce/woocommerce#15454]
### EXPLANATION OF THE ISSUE
I updated woo commerce 2.6.14 to 3.0.7 but the fonction "ADD ORDER" no longer works.
When you adding an order manually you can't change or choose a customer or a user.
I rollback on the 2.6.14 and the fonction "ADD ORDER" running.

### STEPS TO REPRODUCE THE ISSUE

Orders, Add Order, and click on User

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x
