### ISSUE TITLE
Order date should respect the default WP date

### ISSUE THREAD

**Issue by worldsdream** [woocommerce/woocommerce#15453]
Order date in WC should respect the default WP date. See screenshots attached.

http://i.imgur.com/rUXKsx0.png
http://i.imgur.com/3ijuGrB.png

**Comment by worldsdream** [comment]
Great!

**Comment by worldsdream** [comment]
@mikejolley will this be added in 3.1? Or this updated with version 3.0.8? Because in 3.0.8 the change is not in effect. Thank you.

**Comment by mikejolley** [comment]
3.1
