### ISSUE TITLE
 Right side of Product picture is cut off

### ISSUE THREAD

**Issue by Robinm123** [woocommerce/woocommerce#15464]
### EXPLANATION OF THE ISSUE

The issue is the right side of my product picture is cut off. 
### STEPS TO REPRODUCE THE ISSUE

You can view the problem at http://bellaann.com/build-a-bar/

Here is what I think needs to be fixed on the current Woocommerce update: 
The layout CSS is messed up

The Woocommercee top div container (class woocommerce-product-gallery) that contains the image is set for a width of 30%

But there is a sub container (class woocommerce-product-gallery__image) that contains the image and that has its width sets dynamically to a fixed pixel width.
 Unfortunately the calculation of that width is wrong and it makes that container bigger than its parent, resulting in the content being cutoff.

### SYSTEM STATUS

<details>
### WordPress Environment ###

Home URL: http://bellaann.com
Site URL: http://bellaann.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: 5.6.36
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: qcg_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (21) ###

Better WordPress Google XML Sitemaps: by Khang Minh – 1.4.1
Form Maker Pro: by http://web-dorado.com/ – 2.6.6
Image Widget: by Modern Tribe
Inc. – 4.4.4

Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SEO Ultimate: by SEO Design Solutions – 7.6.5.9
Weaver Show Posts: by wpweaver – 1.3.9
Weaver Show Sliders: by wpweaver – 1.4.8
Weaver II Theme Extras: by Bruce Wampler – 2.3.1
Weaver II to Weaver Xtreme: by Bruce Wampler – 1.0.2
Weaver Xtreme Plus: by Bruce Wampler – 3.0
Weaver Xtreme Theme Support: by wpweaver – 3.1
Widget Shortcode: by Hassan Derakhshandeh – 0.3.0
WooCommerce Colors: by WooThemes – 1.0.6
Woocommerce Gift Wrapper: by Little Package – 2.0.3
WooCommerce Product Sort and Display LITE: by a3rev Software – 1.7.6
WooCommerce Subscriptions: by Prospress Inc. – 2.2.6 – 2.2.7 is available
WooCommerce: by Automattic – 3.0.7
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WP Edit: by Josh Lobe – 4.0.1
WP SMTP: by BoLiQuan – 1.1.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #34 - /cart/
Checkout: #35 - /checkout/
My account: #36 - /my-account/

### Theme ###

Name: Weaver Xtreme
Version: 3.1.5
Author URL: //weavertheme.com/about
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
`
</details>

**Comment by mikejolley** [comment]
Theme CSS issue. Add:

`
figure {
margin: 0;
}
`

**Comment by Robinm123** [comment]
I wish that had worked.  It didn't change anything.  I am not really that great at CSS, is there more I should have added? 

Robin Moran Your Website Designer


On ‎Tuesday‎, ‎June‎ ‎6‎, ‎2017‎ ‎03‎:‎38‎:‎39‎ ‎AM‎ ‎MDT, Mike Jolley <notifications@github.com> wrote:


Theme CSS issue. Add:

figure { margin: 0; }

**Comment by mikejolley** [comment]
Try important:

figure { margin: 0 !important; }

This worked in my inspector.

**Comment by Robinm123** [comment]
That worked!  Thank you
I must have something off in my custom CSS.  because it worked once I moved it to the top.  
Thank you so much!

Robin Moran Your Website Designer


On ‎Tuesday‎, ‎June‎ ‎6‎, ‎2017‎ ‎07‎:‎51‎:‎23‎ ‎AM‎ ‎MDT, Mike Jolley <notifications@github.com> wrote:


Try important:

figure { margin: 0 !important; }

This worked in my inspector.

**Comment by Robinm123** [comment]
Now the picture and words won't line up. The description is below.  I tried changing the margins between the columns and that didn't work.  

Robin Moran Your Website Designer


On ‎Tuesday‎, ‎June‎ ‎6‎, ‎2017‎ ‎07‎:‎51‎:‎23‎ ‎AM‎ ‎MDT, Mike Jolley <notifications@github.com> wrote:


Try important:

figure { margin: 0 !important; }

This worked in my inspector.

**Comment by Robinm123** [comment]
Fixed it!  This had to be less than 50%
.woocommerce div.product div.images img{display:block;width:30%;height:auto;box-shadow:none;}
This is so frustrating.  I have to do this every time on every site when I use WooCommerce.  It didn't use to have these issues with the product pictures.
Thank you for your help!!!

Robin Moran Your Website Designer


On ‎Tuesday‎, ‎June‎ ‎6‎, ‎2017‎ ‎07‎:‎51‎:‎23‎ ‎AM‎ ‎MDT, Mike Jolley <notifications@github.com> wrote:


Try important:

figure { margin: 0 !important; }

This worked in my inspector.
