### ISSUE TITLE
Language issue changes hyperlinks

### ISSUE THREAD

**Issue by james090** [woocommerce/woocommerce#15466]
### EXPLANATION OF THE ISSUE

When choosing a new language on the wordpress site translations occur correctly; however the plugin looks for the product category in the /product-category/**your category format while it changes it to /categoria-productos/*** therefore creating a 404 error as this site does not exist

### STEPS TO REPRODUCE THE ISSUE

click on any product and go to catregory the language does not change the urls on the backend, but in front end it does

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
After changing site languages, you must go to Settings > Permalinks and save to update used links and prevent a 404.

**Comment by james090** [comment]
Hi this works, but only for the product permalinks, not for the product categories as there is no option to change this on the setting permalinks page

**Comment by mikejolley** [comment]
They don't need changing, just saving.

**Comment by james090** [comment]
Before coming on here, I changed the permalinks in the settings and this fixed the products issue, but when I click on categories for specific products, woocomerce attempts to access the permalink in spanish and not the real one which is in english. Not sure if this makes sense, but this is the problem and I do not know how to fix this

**Comment by james090** [comment]
thanks btw for the help

**Comment by mikejolley** [comment]
Using multilingual plugin?

**Comment by james090** [comment]
no the site settings in worpress are in spanish but there is only one language i have not used any multilingual plugins

**Comment by mikejolley** [comment]
Hardcode the base in permalink settings then. Usually a save is enough to get the links working.
