### ISSUE TITLE
Disable auto-complete on Virtual-Downloadable

### ISSUE THREAD

**Issue by ihavecapslockon** [woocommerce/woocommerce#15465]
Hello!

I'd like to disable virtual-downloadable products from automatically completing, and instead have them change to processing after payment (same functionality as setting a product to only virtual). I believe this should be doable with a few lines added to the end of the Functions.php file, but I've been unable to find the correct code. 

Any help would be appreciated! Thanks!

**Comment by mikejolley** [comment]
```
add_filter( 'woocommerce_order_item_needs_processing', '__return_true' );
```

**Comment by hdossary** [comment]
Thanks for this! i found this really helpful. @mikejolley  do you know if its possible to set this filter to only specific products or product variants? 

i have a product that is available in 3 formats (digital, print OR digital&print). i therefore want the digital variant to auto-complete as default, but it looks like the variant with digital&print is also triggered to auto-complete. Need this one to be set to processing so that the print part of the order can be processed as usual.

any ideas? thanks!!!

**Comment by sanjaisc** [comment]
Here is the code that works and has been tested by me on my live site. Copy and paste it into your functions.php file or just use a plugin like Snippets like I do and add it in as a snippet. 

```
// Prevent auto-completion of orders for products that are both downloadable and virtual after payment is completed

add_action( 'woocommerce_payment_complete', 'custom_change_order_status_to_processing', 10, 1 );
function custom_change_order_status_to_processing( $order_id ) {
    $order = wc_get_order( $order_id );
    if ( ! $order ) {
        return;
    }
    
    $has_downloadable_virtual = false;
    
    // Check if any product in the order is both downloadable and virtual

    foreach( $order->get_items() as $item_id => $item ){
        $product_id = $item->get_product_id();
        $product = wc_get_product( $product_id );
        
        if ( $product && $product->is_downloadable() && $product->is_virtual() ) {
            $has_downloadable_virtual = true;
            break;
        }
    }
    
    // If any product is both downloadable and virtual, change order status to processing

    if ( $has_downloadable_virtual ) {
        $order->update_status( 'processing' );
    }
}

// Force processing for orders containing downloadable and virtual products

add_filter( 'woocommerce_order_item_needs_processing', 'custom_force_processing_for_downloadable_virtual', 10, 2 );
function custom_force_processing_for_downloadable_virtual( $needs_processing, $product ) {
    if ( $product && $product->is_downloadable() && $product->is_virtual() ) {
        return true;
    }
    return $needs_processing;
}
```
