### ISSUE TITLE
Order items dissapeared

### ISSUE THREAD

**Issue by yurihellyn** [woocommerce/woocommerce#15468]
### EXPLANATION OF THE ISSUE

In the order overview: 'order items' aren't visible anymore

### STEPS TO REPRODUCE THE ISSUE

Woocommerce => Orders (in the orderlist, the order items should apear with possibility to click and see the details)

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.drone-kopen.be
Site URL: https://www.drone-kopen.be
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.26
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 20000
cURL Version: 7.52.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.31 - Wij adviseren een minimum MySQL-versie 5.6. Bekijk: WordPress vereisten
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: dr_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

WooCommerce (nl): door Pronamic – 1.1.7
AffiliateWP: door AffiliateWP
LLC – 2.0.9.2

AffiliateWP - Allowed Products: door AffiliateWP
LLC – 1.1.1

Akismet Anti-Spam: door Automattic – 3.3.2
AMP Analytics: door Valet – 0.0.2
AMP: door Automattic – 0.4.2
WooCommerce Back In Stock Notifier: door Fantastic Plugins – 6.4
BackWPup: door Inpsyde GmbH – 3.4.0
Contact Form 7: door Takayuki Miyoshi – 4.8
Crazy Egg: door Crazy Egg – 2.0
Easy Slide-In for WordPress: door CreoApps – 2.1
Easy Theme and Plugin Upgrades: door Chris Jean – 2.0.0
WooCommerce Search Plugin by Instant Search +: door WooCommerce Search by Fast Simon Inc – 1.8.10
Instapage Plugin: door Instapage – 3.1.8
Loco Translate: door Tim Whitlock – 2.0.14
My Wordpress Login Logo: door Afsal Rahim – 2.0
OG: door Marcin Pietrzak – 2.4.4
P3 (Plugin Performance Profiler): door GoDaddy.com – 1.5.3.9
Redirection: door John Godley – 2.6.1
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 2.2.6
WooCommerce Sisow Betaal Opties: door Sisow – 4.7.0
Smartsupp Live Chat: door Smartsupp – 3.1
WP WooCommerce Best Selling Products by Category: door WP Online Support – 1.1
SSL Insecure Content Fixer: door WebAware – 2.4.0
Sucuri Security - Auditing, Malware Scanner and Hardening: door Sucuri
Inc – 1.8.3

Table Maker: door Wpsoul – 1.6
WooCommerce Table Rate Shipping by Mangohour: door mangohour – 1.2.1
W3 Total Cache: door Frederick Townes – 0.9.5.4
WooChimp: door RightPress – 1.4.2
Abandoned Cart Lite for WooCommerce: door Tyche Softwares – 3.8
WooCommerce Checkout Manager: door Visser Labs – 4.1.2
WooCommerce Conversion Tracking: door Tareq Hasan – 1.2.2
WooCommerce Google Analytics Integration: door WooCommerce – 1.4.2
WooCommerce AdWords Dynamic Remarketing: door Wolf + Bär GmbH – 1.3.3
WooCommerce Pay for Payment: door Karolína Vyskočilová – 2.0.1
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 1.6.5
WooCommerce Product Add-ons: door Automattic – 2.7.26 – 2.8.1 is beschikbaar
WooCommerce Google Product Feed: door Lee Willis – 7.0.2 – 7.1.2 is beschikbaar
WooCommerce Rental & Bookings System: door RedQ Team – 3.0.0
WooCommerce: door Automattic – 3.0.7
Shipping Details for WooCommerce: door PatSaTECH – 1.7.0
WooCommerce Helper: door WooCommerce – 1.7.2 – Netwerk geactiveerd
WP Job Manager: door Automattic – 1.26.0
WP-Optimize: door David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP Smush: door WPMU DEV – 2.7.1
YITH WooCommerce Custom Order Status: door YITHEMES – 1.1.0
YITH WooCommerce Product Bundles: door YITHEMES – 1.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
redq_rental (redq_rental)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #45 - /shop/
Winkelwagen: #46 - /winkelwagen/
Afrekenen: #47 - /checkout/
Mijn account: #48 - /my-account/

### Theme ###

Name: Flatsome Child Theme
Version: 2.5
Author URL: http:%20//www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 2.9.6
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart.php versie 2.3.8 is verouderd. De hoofdversie is 3.0.3
flatsome/woocommerce/cart/proceed-to-checkout-button.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/content-product.php versie 2.6.1 is verouderd. De hoofdversie is 3.0.0
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php versie 1.6.4 is verouderd. De hoofdversie is 3.0.0
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/add-to-cart/grouped.php versie 2.1.7 is verouderd. De hoofdversie is 3.0.7
flatsome-child/flatsome-child/woocommerce/single-product/add-to-cart/simple.php versie 2.1.0 is verouderd. De hoofdversie is 3.0.0
flatsome/woocommerce/single-product/add-to-cart/variable.php versie 2.5.0 is verouderd. De hoofdversie is 3.0.0
flatsome/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php versie 2.5.0 is verouderd. De hoofdversie is 3.0.0
flatsome/woocommerce/single-product/price.php versie 2.4.9 is verouderd. De hoofdversie is 3.0.0
flatsome/woocommerce/single-product/product-image.php versie 2.6.3 is verouderd. De hoofdversie is 3.0.2
flatsome/woocommerce/single-product/product-thumbnails.php versie 2.6.3 is verouderd. De hoofdversie is 3.0.2
flatsome/woocommerce/single-product/related.php versie 1.6.4 is verouderd. De hoofdversie is 3.0.0
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php versie 2.0.0 is verouderd. De hoofdversie is 3.0.0
flatsome/woocommerce/single-product/tabs/description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php versie 1.6.4 is verouderd. De hoofdversie is 3.0.0
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌Leer hoe te updaten
`
</details>

**Comment by JoelMbondi** [comment]
hi,
I got the same problem. 
Regards
<img width="1263" alt="capture d ecran 2017-06-06 a 11 23 24" src="https://cloud.githubusercontent.com/assets/15074721/26827656/8c83fd78-4abe-11e7-96bd-e5afd61f1208.png">

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14121
