### ISSUE TITLE
date_completed returning null for GET Orders API v2

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#15463]
Requests for Orders using WooCommerce Version 3.0.7 via the v2 API are not returning the date_completed. My request is for:

wp-json/wc/v2/orders?page=1&orderby=id&order=asc

and I'm getting:

` "date_completed": null, 
    "date_completed_gmt": null, `

instead of the actual date completed values.

**Comment by mikejolley** [comment]
Order must be either not complete, or missing the date info:

<img width="1071" alt="2017-06-06 at 13 02" src="https://cloud.githubusercontent.com/assets/90977/26828262/7c62d654-4ab8-11e7-9d98-dc80792bab6f.png">

This could happen if the order was updated without using core functions, or if it's an old order before the meta data was forced on status changes. Look at the order itself/database/postmeta table.
