### ISSUE TITLE
[3.1.0] Missing data in product search(Admin)

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/woocommerce#15461]
### EXPLANATION OF THE ISSUE

There are 5 variable products, assigned to Category 1 in the database. This is the default sort in the product search, the category is missing, the price range is missing:
<img width="1092" alt="bildschirmfoto 2017-06-05 um 22 35 43" src="https://cloud.githubusercontent.com/assets/25877146/26802101/8a0ea3ba-4a3f-11e7-99ed-52d859f5f5a6.png">

Changing the sort to SKU:
<img width="1091" alt="bildschirmfoto 2017-06-05 um 22 39 11" src="https://cloud.githubusercontent.com/assets/25877146/26802173/d6c14e38-4a3f-11e7-9b31-a5467c41b750.png">

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://eval.firewoodshop.ch
Site URL: https://eval.firewoodshop.ch
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_CH

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 7.1.5
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: fws_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.0-beta

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CHF (CHF)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /warenkorb/
Checkout: #6 - /kasse/
My account: #7 - /mein-konto/

### Theme ###

Name: Storefront
Version: 2.2.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by claudiosanches** [comment]
Already fixed in https://github.com/woocommerce/woocommerce/pull/15398
