### ISSUE TITLE
Can't see Order / Orders are not displayed

### ISSUE THREAD

**Issue by JoelMbondi** [woocommerce/woocommerce#15472]
### EXPLANATION OF THE ISSUE

 I can see sales on my backend. I deleted and reinstall but I always get the same problem. 
Please find enclosed the image.

Version WC :		3.0.7
Dossier journaux enregistrable :		 /home/clients/joelmb/dev/yatu_presque_tout/wp-content/uploads/wc-logs/
Version WP :		4.7.5
WP multisite :		–
Limite mémoire WP :		256 MB
Mode débogage WP :		–
Cron WP :		
Langue :		fr_FR
Environnement serveur
Info serveur:		nginx/1.10.3
Version PHP:		5.6.30-0+deb8u1
Poids Max Post PHP:		200 MB
Limite d’exécution PHP:		30
PHP Max Input Vars:		1000
Version de cURL:		7.38.0, OpenSSL/1.0.1t
SUHOSIN installé:		–
Version MySQL:		 5.5.55 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Taille maximale de téléversement:		200 MB
Le fuseau horaire par défaut est UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Chaînes multi-octets:		
Remote post:		
Remote get:		
Base de données
WC version base de données:		3.0.7
Préfixe de base de données	 	hx3pr_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
Base de données GeoIP de MaxMind:		 /home/clients/joelmb/dev/yatu_presque_tout/wp-content/uploads/GeoIP.dat
Sécurité
### STEPS TO REPRODUCE THE ISSUE

1°° Woocommerce
2°°Orders
3°°Can't see orders
<img width="1263" alt="capture d ecran 2017-06-06 a 11 23 24" src="https://cloud.githubusercontent.com/assets/15074721/26828876/9ba5a2c0-4ac3-11e7-8c0b-f1607307f2d7.png">

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Open screen options, top right of the page. You're missing all columns.

**Comment by echersdk** [comment]
@mikejolley Fan-f'ing-tastic! 
I couldn't figure this out until this!!! THANK YOU!
