### ISSUE TITLE
Variation Stock = 0, Variation Still Shows w/Hide Out of Stock Items from the Catalog

### ISSUE THREAD

**Issue by co50** [woocommerce/woocommerce#15484]
### EXPLANATION OF THE ISSUE

When a variation of a product (that has other variations still in stock) drops to 0 qty in stock, the variation still appears for sale (allow backorders is "no")

Not sure if this is a bug or intended functionality. If it's a bug, great...here's the report. If it's intended functionality, I don't understand why. If I want to hide items that are out of stock, why would this only apply to the parent product itself? Why would I want to show variations that are out of stock if this option is checked? And why does the admin show "In Stock" for these variations with Qty 0? We imported the items via CSV and do not include the instock/outofstock column, assuming the qty would determine that.

### STEPS TO REPRODUCE THE ISSUE

Set "Hide Out of Stock Items from the Catalog" active. Drop the stock level of any variation to 0, but with other variations of the item still with stock of >1 .

### SYSTEM STATUS

Not Related

**Comment by mikejolley** [comment]
2 x Variations:

<img width="959" alt="2017-06-07 at 10 54" src="https://user-images.githubusercontent.com/90977/26872888-06535d18-4b70-11e7-9579-6fb41fdc1132.png">

Frontend:

<img width="435" alt="2017-06-07 at 10 55" src="https://user-images.githubusercontent.com/90977/26872892-0beb2346-4b70-11e7-8e7b-094a4ca4fad6.png">
<img width="450" alt="2017-06-07 at 10 55 2" src="https://user-images.githubusercontent.com/90977/26872894-0db1461a-4b70-11e7-8336-7334db03a387.png">

With hide out of stock enabled:

<img width="441" alt="2017-06-07 at 10 56" src="https://user-images.githubusercontent.com/90977/26872895-12a25e3e-4b70-11e7-878e-fffbaf65845c.png">

Appears fine. It cannot be purchased.

**Comment by co50** [comment]
2x variations:

![capture](https://user-images.githubusercontent.com/11934431/26881414-4fcefc6e-4b65-11e7-9852-788608028209.PNG)

With hide out of stock enabled:

![capture2](https://user-images.githubusercontent.com/11934431/26881415-4fd2081e-4b65-11e7-8488-6dcec823ca7e.PNG)

Appears incorrectly. Can be selected.

**Comment by mikejolley** [comment]
I cannot see all the variation attributes you've set up, but this could also be the out of stock threshold in settings. This could be set to something other than 0.

**Comment by co50** [comment]
It is....it is set so 9 or less is considered out of stock. How does that effect this though? If anything I figure a qty of 9 or less would trigger the product to vanish. Does it not work this way?

**Comment by mikejolley** [comment]
Can you screenshot it for me?

**Comment by co50** [comment]
Anyway, I changed the threshold from 9 to 0, but got the same result. Sure, I can screenshot for you.......

![capture](https://user-images.githubusercontent.com/11934431/26881729-4afc0c6c-4b66-11e7-9af6-4f22f310be9b.PNG)

**Comment by mikejolley** [comment]
So when you save that product, does the status change to out of stock?

**Comment by mikejolley** [comment]
If not, look for plugin conflicts. You said "Not Related" in system status -> it is.

**Comment by co50** [comment]
Mike, The reason I put N/A for that is because I already tested it after deactivating all non-critical plugins. Pretty much only WooCommerce and a couple of official Woo plugins were left active. Result was the same. But I can paste it anyway if you think it would be of help.....

`
### WordPress Environment ###

Home URL: https://frankmorrow.com
Site URL: https://frankmorrow.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.5
PHP Post Max Size: 256 MB
PHP Time Limit: 500
PHP Max Input Vars: 5000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wordpress_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

ManageWP - Worker: by ManageWP – 4.2.18
Admin Menu Editor Pro: by Janis Elsts – 2.4.3
Akismet Anti-Spam: by Automattic – 3.3.2
Fusion Builder: by ThemeFusion – 1.1.6
Fusion Core: by ThemeFusion – 3.1.6
Gravity Forms: by rocketgenius – 2.2.3
IgniteWoo Updater: by IgniteWoo.com – 2.1.11
My Custom Functions: by Arthur Gareginyan – 4.2
PDF Product Catalog 2 for WooCommerce: by Kyriakos Ktorides – 2.3.1
Postman SMTP: by Jason Hendriks – 1.7.2
WooCommerce Product Filter: by Mihajlovic Nenad – 6.2.3
Product Sales Report for WooCommerce: by Potent Plugins – 1.4.8
Really Simple SSL: by Rogier Lankhorst – 2.5.16
Set JPG Compression: by Company 50 – 1.0
Smart Cleanup Tools: by Milan Petrovic – 4.2
SO Hide SEO Bloat: by SO WP – 3.0.0
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.2.7

Ultimate Branding: by WPMU DEV – 1.8.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.13.1.21

User Switching: by John Blackbourn – 1.0.9
Woo Custom Fee: by AcvSoft – 1.6
Woo Search Box: by Guaven Labs – 1.6.6
WooCommerce Bulk Pricing: by WP Lab – 1.9.0
WooCommerce Cart Reports: by WooCommerce – 1.1.15
WooCommerce Authorize.Net CIM Gateway: by SkyVerge – 2.6.3
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.4
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.14
WooCommerce Shipment Tracking: by WooCommerce – 1.6.6 – 1.6.7 is available
WooCommerce UPS Shipping Pro: by IgniteWoo.com - Custom Add-ons for WooCommerce! – 3.4.7
WooCommerce: by Automattic – 3.0.7 – 3.0.8 is available
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.8
WP Rocket: by WP Media – 2.9.11
WP Store Locator: by Tijmen Smit – 2.2.8
Yoast SEO: WooCommerce: by Team Yoast – 4.8

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #650 - /shop/
Cart: #651 - /cart/
Checkout: #652 - /checkout/
My account: #653 - /my-account/

### Theme ###

Name: Avada
Version: 5.1.6
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.0.2
Avada/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.0.2
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌Learn how to update

### Authorize.Net CIM ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
`

**Comment by mikejolley** [comment]
Can you do the .8 update and also try what I said? Change the stock amount and see if the status changes.

**Comment by co50** [comment]
Sorry Mike - I did try what you said before and forgot to report back. I edited the item w/o changing anything and clicked Update. 

Just did the .8 update. Same result. The variation is still selectable.

However, I just tried changing the stock for the variation in question to 25, updated, then back to 0 and updated. **Now** the variation disappears. I won't be able to do this manually for 10,000 products - is this a bug or is there some workaround?

**Comment by mikejolley** [comment]
It sounds like it could be related to the change in out of stock threshold. Usually it would go out of stock once the threshold is reached. Changing that above the current stock level would break it.

**Comment by co50** [comment]
I agree, it should disappear when the variation reaches the out of stock threshold, but it does not.

I had the threshold at 9 (the reason is because out min qty purchase is 10 units)....and it's been that way for at least a year. I changed it today when you brought it up, to 0. That change itself made no difference. It's still set at 0.

Not sure what the workaround is to get all 10,000 of our products on the same page so the variations disappear if stock is 0?

**Comment by mikejolley** [comment]
They won't disappear for the reasons I mentioned, but they should not be purchasable regardless? Cart should show an error.

**Comment by co50** [comment]
They are not purchasable....the cart does show an out of stock error if you try, but what we're trying to accomplish here is not have the 0 stock variations show at all. Customers get frustrated having to click through every variation to see what's available so we want to eliminate those that are out of stock. 

I'm not sure I understand the 'reasons [you] mentioned'.....that the out of stock threshold was changed? It wasn't. It's been at 9 since the catalog was first imported. Only today did I change it to 0 just to see if it made any difference. So ruling that out, is this not a bug? And either way, how to get WC to recognize variations are actually out of stock and thus remove them, on a mass scale? A new CSV import? Some SQL cmd?

**Comment by mikejolley** [comment]
I'm not sure of a way to do it in bulk. The status transition changes when the stock is reduced. Since it never hit the threshold (it was already past the 7) this never occurred :(

**Comment by co50** [comment]
So if we do a CSV import and a variation's stock is 0 in the CSV, it will still show up? You're saying it's only when stock was above the threshold and then fell below it that the variation disappears?

**Comment by waynep16** [comment]
This is still a bug for us too. If the threshold is set to 10 and hide out of stock yet we have 6 in stock it should hide the product but it doesn’t. It’s a bug

**Comment by mmtomm** [comment]
I also see this as a bug, cause on my site it does not appear due to a csv upload but happens also when a variation 'naturally' goes below treshold or to zero - the variation displays in the dropdown, ad to cart is active and first when a customer hits the button it display the error.

**Comment by Guztavsson** [comment]
I also have this problem, any idea how to solve it?

**Comment by co50** [comment]
There is a solution but it's not a fix-all

Go here:  https://stackoverflow.com/questions/24639288/woocommerce-products-showing-out-of-stock-message-when-not-actually-out-of-sto

Follow the instructions in the comment that begins "It's 2017..."

This will automatically update any product that is visited, with the correct meta stock info. Thoroughly tested on two sites with this bug and works perfectly. Downside is that you have to visit each product individually. Bots do not -seem- to trigger the update when they visit a page, unfortunately. 

@mikejolley - Seriously there should be a better solution for this bug in Woo. Maybe a button on the status page that does the above across all products?

**Comment by Guztavsson** [comment]
Tested it, but it didn´t work for me and if it had worked it had been to much job with it, far too many products to do it manually

**Comment by antoinepernaud** [comment]
Since 3 years, it's still not solved : https://github.com/woocommerce/woocommerce/issues/5840#issuecomment-50601474

It's a shame... How can we do ??? I have to delete out of stock variations, and create it again when back in stock...

**Comment by co50** [comment]
Agreed. No idea why this issue is closed. It's a huge issue - the whole stock tracking mechanism is a disaster. I hear 3.3 finally uses common sense and marks items with 0 inventory as outofstock and those with inventory as instock. Unaware if that update also fixes the issue in this thread.

**Comment by antoinepernaud** [comment]
No, it doesn't...

**Comment by mmtomm** [comment]
BOAH I can see on stackexchange this issue is almost 3 years old, searching google I see a lot of people having this stock problem. Now we have 2018 and woo 3.2.6 and it is still an issue

**Comment by antoinepernaud** [comment]
It's a pitty... This issue, make woocommerce unusable for everyone who want to selle variable products with more than 1 attribute... I juste made a project with woocommerce, and now, I'm in a deep pain each time my client call... =(

**Comment by mikejolley** [comment]
You folks commenting - this issue only occurs when you change the THRESHOLD from 0 to something else and don't update your products. I highly doubt this is what you're all doing because it's a rarely used setting. I think you may have "similar" issues but not the same. I'm closing this issue - if you have a real bug, put together a proper, detailed new report.
