### ISSUE TITLE
PayPal error

### ISSUE THREAD

**Issue by ocdevops** [woocommerce/woocommerce#15497]
Last night we updated our Woocommerce to Version 3.0.8.
After the update the PayPal payment stopped working, we get the following error after clicking on the Place order button in our store:
**Things don't appear to be working at the moment. Please try again later.**

**Comment by mikejolley** [comment]
PayPal config error or outage. PayPal gateway code has not changed in 3.0.8. Sandbox is working for me still.

Try a clean order/new session, check PayPal settings, and if still stuck see if PayPal have logs their side about the issue.
