### ISSUE TITLE
After update, pages on CPT URL’s not working anymore

### ISSUE THREAD

**Issue by marcopetersamazing** [woocommerce/woocommerce#15491]
Hi fellow developers,

We have a few pages (/vacatures, /vacatures/actueel and /vacatures/vast) with page templates. These slugs are the same as a CPT, so these are shown instead of the archive page (/vacatures) and other pages.

This has always worked, however, after updating WooCommerce from 2.6.14 to 3.0.8, this breaks and the normal archive pages are shown (our custom pages are skipped). We’ve tested this a few times by rolling back te update and database and updating again, however, the problem keeps coming back when doing the WooCommerce update.

Does anyone have the same issue and/or a solution for this? We’ve seen “solutions” like “change the slug of your pages” and “change the slug of your CPT”, but these are fixes we don’t want to do. We would love to get it working like it was working.

Thank you all!

**Comment by mikejolley** [comment]
Archives should take priority over page URLs, because when you use a archive base on single product permalinks they cannot function correctly otherwise. To be clear, your setup **will** lead to conflicts regardless of version.

I'd suggest disabling the archive if you're not using it. You can do this with the `woocommerce_register_post_type_product` filter and set has_archive to false: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-post-types.php#L293

**Comment by marcopetersamazing** [comment]
@mikejolley Except that the slug I'm talking about is the slug of one of our own CPT's. This is suddenly broken by the WooCommerce update. How is it that WordPress itself let's this work perfectly, but a WooCommerce update breaks this?

**Comment by mikejolley** [comment]
Because previous versions of WC would force `use_verbose_page_rules` on more frequently. Newer versions only enable this if the shop page is used as the base.

Without WC active and custom post types, your pages/archives would break in the same way.

**Comment by marcopetersamazing** [comment]
@mikejolley With WooCommerce disabled, the pages on the CPT slugs work correctly, the single views of the CPT also work. Looks like specifically WooCommerce is breaking this.

**Comment by mikejolley** [comment]
Share a plugin isolating the issue to prove it?

**Comment by Jany-M** [comment]
@mikejolley I've also been noticing some issues with slugs lately.

So if I have a page with slug "shop", which needs to show custom content (not wc archive), and I DONT set that page as store page in wc (in fact, I leave the store page option empty), shouldn't my shop page appear without issues?
The custom shop page worked fine, then it was mistakenly associated as the wc store page, then removed from it (no store page), however wc doesnt seem to let go of it... and now "shop" is "owned" by a wc archive... and I cant seem to find a way to break it away from wc, as a simple page.
Advice?

**Comment by snecz** [comment]
I have the same problem. After updating WooCommerce static pages with slugs the same as CPT taxonomies names show archive templates. Does anybody have solution for this (except for changing slugs names)?
