### ISSUE TITLE
Price Display Suffix not showing on Products with Variations

### ISSUE THREAD

**Issue by silentmedia** [woocommerce/woocommerce#15493]
### EXPLANATION OF THE ISSUE

Price Display Suffix not showing on Products with Variations.
WC Version: 3.0.7

### STEPS TO REPRODUCE THE ISSUE

1. Add value to WooCommerce > Settings > Tax > 'Price Display Suffix'.  e.g (Ex-VAT {price_excluding_tax})
2. Add products with and without variations.
3. 'Price Display Suffix' will not show on products with variations.  Even if you select the variation on Product page. 

### SYSTEM STATUS

<details>

`
### WordPress Environment ###

Home URL: https://www.forest-av.com
Site URL: https://www.forest-av.com
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.19
PHP Post Max Size: 1,000 MB
PHP Time Limit: 600
PHP Max Input Vars: 50000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wpxb_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

WP Kraken [#h158482] - Add to cart button fix: by WP Kraken [Pawe�] – 1.0
PCA Predict: by PCA Predict – 1.0.3
LiteSpeed Cache: by LiteSpeed Technologies – 1.0.15
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SiteOrigin CSS: by SiteOrigin – 1.1.4
Advanced Order Export For WooCommerce: by AlgolPlus – 1.4.0
WooCommerce Cost of Goods: by SkyVerge – 2.3.2
WooCommerce EU VAT Number: by WooCommerce – 2.2.0
WooCommerce SagePay Form and SagePay Direct Gateway: by Andrew Benbow – 3.7.6
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.4
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 1.5.2
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout Fernhout – 2.3.0
WooCommerce Google Product Feed: by Lee Willis – 7.1.2
WooCommerce: by Automattic – 3.0.7 – 3.0.8 is available
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO Premium: by Team Yoast – 4.8
WPForms Lite: by WPForms – 1.3.7.3
Custom Product Tabs for WooCommerce: by YIKES
Inc – 1.5.14

YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #63 - /shop/
Basket: #62 - /cart/
Checkout: #61 - /checkout/
My account: #60 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.5
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`
</details>

**Comment by beayeric** [comment]
Hi , I have the same problem. Any solution? 

thank you

**Comment by beayeric** [comment]
HI !!! 

Is no sense... but anyway . 

i found this maybe help 

https://tomjesch.com/display-woocommerce-products-with-and-without-tax/

regards.

**Comment by dougaitken** [comment]
As Mike mentions here - this isn't possible - https://github.com/woocommerce/woocommerce/issues/14839#issuecomment-299712267
