### ISSUE TITLE
login_errors hook disturbing woocommerce login

### ISSUE THREAD

**Issue by abdulwahab610** [woocommerce/woocommerce#15492]
I'm using the login_errors hook for modifying the WordPress login error messages. It's working fine on a login page. But when I login through Woocommerce login form get the error `Fatal error: Uncaught Error: Call to a member function get_error_codes();`  and die.

Here using the global variable $errors in the callback function that return null on Woocommerce login form, therefore fatal error happen. 
Question 1: Is there any hook to modify the Woocommerce login error messages?
Question 2: Is there any way to differentiate the Woocommerce and WordPress login form?

Thanks in advance :)

**Comment by mikejolley** [comment]
Just check the type of object passed: https://github.com/woocommerce/woocommerce/blob/f434fc7d9a1f00363b07c60bde0aa3c0666e46ac/includes/class-wc-form-handler.php#L926

^ This will be a string based error message.

Core also uses a string: https://github.com/WordPress/WordPress/blob/430422b0b7a3642cf6a793190180c0af3f760512/wp-login.php#L203

We also have this hook: https://github.com/woocommerce/woocommerce/blob/f434fc7d9a1f00363b07c60bde0aa3c0666e46ac/includes/class-wc-form-handler.php#L874

That is similar to the hook WP has for errors.

**Comment by abdulwahab610** [comment]
Hi, @mikejolley  
Thanks for the handy reply :) solves the part of the problem.

I've 1 issue there. I'm using the Google reCaptcha on the login form. When I login with Woocommerce login form it gives the error of reCaptcha while there is no reCaptcha visible, that is called on WordPress login form.

Why the reCaptcha error occur on Woocommerce login form?

Thank again.

**Comment by mikejolley** [comment]
The WC login form has similar hooks to the WP login form, so the plugin needs to output recaptcha in both places or adjust it's code to see if it was actually posted.

**Comment by abdulwahab610** [comment]
I just apply the condition if `isset( $_POST['woocommerce-login-nonce'] ) return;`
For no more reCaptcha call there. 

Is it right? any suggestion there?
Thank you
