### ISSUE TITLE
Remove order notes from Dashboard Activity widget

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#15509]
### EXPLANATION OF THE ISSUE

On large sites, this widget could cause performance issues because of the order notes. Can we remove them from there? If WPML is installed this is even worse.

### SYSTEM STATUS

Ticket 580683-zd-woothemes

**Comment by mikejolley** [comment]
They are already excluded. See `exclude_order_comments` method or your own test install.

https://github.com/woocommerce/woocommerce/blob/c83e725f9923982220acea2f4260e966805f016f/includes/class-wc-comments.php#L33

I will look to ensure these queries are optimised, but if visible for that user, it indicates something is removing these functions form use (WPML?)

**Comment by mikejolley** [comment]
Seems fine. We can make a small tweak to optimise the query using comment type - Ill send a PR.

**Comment by jarmosiim** [comment]
Wanted to add here - as I reported the issue - that it's not a tiny amount it adds to the loading of that page but about 5-7 seconds.
