### ISSUE TITLE
WooCommerce makes some bbPress user profiles redirect to the shop page

### ISSUE THREAD

**Issue by douglsmith** [woocommerce/woocommerce#15508]
When WooCommerce is on a site with bbPress, clicking on a bbPress user profile link sometimes redirects to the shop page instead.

This happens because WooCommerce disables author archives for customers. It checks to see if it's on an author archive page using `is_author()`, which returns true for bbPress profile pages too. It then checks to see if the user is a customer and redirects to the shop page if they are.

So bbPress profile pages don't work for users who are customers.

```php
/**
 * Disable author archives for customers.
 *
 * @since 2.5.0
 */
function wc_disable_author_archives_for_customers() {
	global $author;
	if ( is_author() ) {
		$user = get_user_by( 'id', $author );
		if ( isset( $user->roles[0] ) && 'customer' === $user->roles[0] ) {
			wp_redirect( wc_get_page_permalink( 'shop' ) );
		}
	}
}
add_action( 'template_redirect', 'wc_disable_author_archives_for_customers' );
```
https://github.com/woocommerce/woocommerce/blob/cb4ea0c356a42b7a023a69e5e5ce1ec1dab9ca24/includes/wc-user-functions.php#L499-L516

I was about to submit a patch to watch for bbPress profile pages but I noticed that what it's doing for checking the user role could break things too.

A WP user can have multiple roles and WooCommerce is only checking the first one. Some examples that I've seen happen on real sites…

- If someone becomes a user by becoming a customer then that will be the first role and it should be okay as is.
- If someone becomes a customer after already being a user by other means then the first role might not be _customer_ and it would not redirect from the author archive page.
- If someone becomes a customer first, then is granted the _author_ role in a way that adds to the roles rather than replacing the _customer_ role then the author's archive page wouldn't work even though it probably would be desired.

I'd be happy to write a patch to fix this but what is the desired behavior knowing that  _customer_ may only be one many roles a user has and it may not be the first role assigned?

How about this:

1. Check if we're on a bbPress (maybe BuddyPress too) profile page and don't redirect them.
2. Do not redirect if the user has the [_edit_posts_](https://codex.wordpress.org/Roles_and_Capabilities#edit_posts) capability. That will make sure we don't redirect users who should have a user archive page, like _contributors_, _authors_, _editors_, and _administrators_, even though some of them could also be customers.
3. Finally, check all of a user's roles for _customer_ and redirect if found among them.

**Comment by mikejolley** [comment]
That makes sense although I'd like to try avoiding bbpress functions if possible. Are you sending a PR?

**Comment by JJJ** [comment]
The way that bbPress uses multiple roles is currently an anomaly, but it isn't unsupported by WordPress, so even though it's weird, I tend to agree with @douglsmith that it's worth trying to support the idea that users may have multiple roles in the same site.

I'm looking into the author-archive flag that gets set with bbPress. I have a vague memory of setting this, but need to do some research to remember fully.

**Comment by JJJ** [comment]
The offending line in bbPress is:

```
$posts_query->set( 'author_name', $the_user->user_nicename );
```

This has been in bbPress since 2010, but it may not be necessary anymore since we aren't pulling in any blog posts like we did originally.

I'll keep looking into this on the bbPress side, too.

**Comment by JJJ** [comment]
I've removed the offending line of code in bbPress (for the 2.6 release soon'ish)

See: https://bbpress.trac.wordpress.org/changeset/6503

Once y'all can confirm this is resolved, feel free to close at your leisure. 💜

**Comment by douglsmith** [comment]
I've verified that the change to bbPress from @jjj fixes it for me.

@mikejolley, So do we ignore it here knowing that it will eventually be fixed in bbPress 2.6 or try to work around it for older versions? I think I'd lean toward ignoring and avoid adding bbPress specifics here.

Either way, we should probably clean up the logic around user roles to handle the possibility of multiple roles.

**Comment by JJJ** [comment]
bbPress 2.6 is due out like a year ago, so once I wipe the egg off my face and ship it, this issue should go away. For those reasons, my recommendation would also be to close this issue and let bbPress sort it out.

**Comment by mikejolley** [comment]
Thanks @JJJ 

This will fix it, but I'd like to take a look into why we're using the role object directly and not current_user_can etc. I *think* it may have been a core issue with multi-role users and I **think** I recall reporting it/patching. I'll try finding it.

**Comment by mikejolley** [comment]
https://core.trac.wordpress.org/ticket/36376

**Comment by douglsmith** [comment]
Changes tested and verified working here. Thanks everyone!
