### ISSUE TITLE
Add an hook in \WC_Abstract_Order::calculate_totals for additional order total processing

### ISSUE THREAD

**Issue by logiuffrida** [woocommerce/woocommerce#15504]
### EXPLANATION OF THE ISSUE
In several scenarios, I use to alter the cart totals while processing the checkout, hooking the 'woocommerce_calculate_totals' action that is there for this specific case but there isn't a similar hook for the calculate_totals method in the order class.
So, any changes applied to the cart total during the checkout, can't be performed after an order total recalculation.

### STEPS TO REPRODUCE THE ISSUE

With WooCommerce 3, hook  the 'woocommerce_calculate_totals' action and set a different cart total and complete the checkout process.
Now open the edit order page and simply click on 'Recalculate' or 'Update' button, it will trigger the \WC_Abstract_Order::calculate_totals methods where there isn't any way for hooking the total retrieved, it simply sums all the order items, fees and shipping cost and retrieve the result as the order total.

**Comment by claudiosanches** [comment]
>  So, any changes applied to the cart total during the checkout, can't be performed after an order total recalculation.

Like discounts or increase values?
Well for increase values you can add fees and soon we'll have a discounts API.
So I don't think that is a good idea have a hook to allow just hack the total price without anything listed in the orders details, better wait for discounts API.

**Comment by logiuffrida** [comment]
Hi Claudio,
I let users apply gift card codes previously purchased for total or partial order payment.
I can't alter the order item cost the way WC do when a coupon is applied and I can't use fee too as they are recalculated on order update, for example adding taxes that were not applied early.

I thought I could refactor the plugin and create a new order item type but this will lead me to the same problem because of the method \WC_Abstract_Order::calculate_totals that recalculate the totals using only order items, fees and shipping costs.

> So I don't think that is a good idea have a hook to allow just hack the total price without anything listed in the order's details, better wait for discounts API.

I agree with you, but what does not make sense to me and what leads me to a dead end is that in \WC_Cart::calculate_totals(line 1384 in WooCommerce 3.0.8), there is an explicit hook for letting us 'change the totals' without having to add objects to the order itself:
```
// Allow plugins to hook and alter totals before final total is calculated
do_action( 'woocommerce_calculate_totals', $this );

// Grand Total - Discounted product prices, discounted tax, shipping cost + tax
$this->total = max( 0, apply_filters( 'woocommerce_calculated_total', round( $this->cart_contents_total + $this->tax_total + $this->shipping_tax_total + $this->shipping_total + $this->fee_total, $this->dp ), $this ) );
```
My concerns at the moment are about having several orders that turn to be incoherent after an order save(just changing the order status and pressing update will trigger the issue) and I can't avoid it in WooCommerce 3+ while until WC 2.6+ the save order action don't alter the totals and the issue is triggered only by explicit 'Calculate total' button click.

At the moment all orders that have a gift card applied have a wrong total and this is not only a visual issue because it leads the customers to receive the order complete email notification with the wrong order total and leads shop owner to potentially refund more money than the customer really paid for that order.

At the moment I had to add some custom hook in the WooCommerce's core files for letting me apply the same logic to the order both during the checkout and update process.

My suggestion about adding a hook in \WC_Abstract_Order::calculate_totals is just for being coherent with the hook in \WC_Cart::calculate_totals as I don't see any better workaround for that scenario.

I'll be grateful if you'll take it into account for a code improvement or if you would suggest a better approach

**Comment by claudiosanches** [comment]
As I said, you are giving discounts without declaring any reason for WooCommerce.

>  I can't alter the order item cost the way WC do when a coupon is applied and I can't use fee too as they are recalculated on order update, for example adding taxes that were not applied early.

This is not what I'm saying, I'm saying in a discounts API, like you can set fee to an order or on checkout, you will be able to properly apply discounts without any coupon.
