### ISSUE TITLE
Limiting products returned by `meta_key` and `meta_value` via `wc_get_products()`

### ISSUE THREAD

**Issue by Chunkford** [woocommerce/woocommerce#15503]
Before WC3 I would use `get_posts()` and in the args I would use `meta_key` and `meta_value` to only get the products I needed.

So trying not use WP functions directly and going through the WC datastores I'm using wc_get_products(), but there isn't any way to limit what products I wanted by their meta data - unless I've missed it.

Is there any plans to add `meta_key` and `meta_value`  to the input args for `wc_get_products()` so it can only return the products that are needed?

The problem I have is using the wc_get_products() on a site with lots of product causes so many data queries that it slows everything down due to getting products I don't need and populating the product object.
In particular:
`WP_Term_Query->get_terms()` 
```
SELECT t.*, tt.*
FROM wp_terms AS t 
INNER JOIN wp_term_taxonomy AS tt
ON t.term_id = tt.term_id
INNER JOIN wp_term_relationships AS tr
ON tr.term_taxonomy_id = tt.term_taxonomy_id
WHERE tt.taxonomy IN ('product_shipping_class')
AND tr.object_id IN (18863)
ORDER BY t.name ASC
```
according to the Query Monitor plugin.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/13645
