### ISSUE TITLE
After downgrade to v 2.6.14 can't update products.

### ISSUE THREAD

**Issue by minds4** [woocommerce/woocommerce#15512]
### EXPLANATION OF THE ISSUE

I've updated to version v 3 and then downgrade to v 2.6.14 . After this i can't update products. When i press update button nothing happening. How to fix this? I dont need update to latest version, only fix this issue.

**Comment by mikejolley** [comment]
Switch to downloadable, remove the -1 from the fields, switch back and save.

Fix your issues; 2.6 will eventually be non-supported by anyone.
