### ISSUE TITLE
Typo in PHPDoc in WC_Coupon Class

### ISSUE THREAD

**Issue by gpisarski** [woocommerce/woocommerce#15518]
### EXPLANATION OF THE ISSUE

There is small typo in PHPDoc in line 162 for get_amount method. Current description is 'Get coupon code.', should be 'Get coupon amount.' 

### STEPS TO REPRODUCE THE ISSUE

--

### SYSTEM STATUS

--

**Comment by mikejolley** [comment]
Looks to be corrected in master.
