### ISSUE TITLE
Category Issued

### ISSUE THREAD

**Issue by alfredoizjr** [woocommerce/woocommerce#15514]
Hi I used the v2 of api rest woocomerce  I just try get a list of the products is in one specific category, I use for this Ionic
```

    this.WooComerce.getAsync('products/?filter[category]=myslughere').then((data)=>{
      console.log('by category ',JSON.parse(data.body));
      console.log(this.category.slug);
       this.products = JSON.parse(data.body);
    }, (err)=>{
        console.log(err);
    });
```
but I just received my first 10 item  
the filter is don't work is another way for do this or I miss some thing here

**Comment by mikejolley** [comment]
Filter is not supported. Look here http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

**Comment by alfredoizjr** [comment]
but them Who I can get my al my producs by especific category

2017-06-08 10:28 GMT-04:00 Mike Jolley <notifications@github.com>:

**Comment by mikejolley** [comment]
The docs explain it...

**Comment by alfredoizjr** [comment]
Can you only put for me here a example Uriel how is work please I don't
understand very well the documentation. Please

**Comment by mikejolley** [comment]
"Available parameters" via the link I sent lists category as an option.

**Comment by alfredoizjr** [comment]
sorry but I don't understand I wnat to do some like this

products/?filter[category]=slug-of-categoy

this hold version give to me all the products under that category now I
know this is no working any more who is work now ??? can you please put me
example like this please

2017-06-08 11:49 GMT-04:00 Mike Jolley <notifications@github.com>:

**Comment by mikejolley** [comment]
You'd append `?category=` etc. The parameters are all listed in the docs. There is no need for `filter`.

http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

Please don't use Github like a support forum. It's not.

**Comment by ShujaShah** [comment]
> Hi I used the v2 of api rest woocomerce I just try get a list of the products is in one specific category, I use for this Ionic
> 
> ```
> 
>     this.WooComerce.getAsync('products/?filter[category]=myslughere').then((data)=>{
>       console.log('by category ',JSON.parse(data.body));
>       console.log(this.category.slug);
>        this.products = JSON.parse(data.body);
>     }, (err)=>{
>         console.log(err);
>     });
> ```
> 
> but I just received my first 10 item
> the filter is don't work is another way for do this or I miss some thing here

this happens because the page returns only 10 products by default....to get all the products from the specific category you will need to add  the following code in the html file :
<ion-infinite-scroll (ionInfinite)="loadMoreProducts($event)">
      <ion-infinite-scroll-content></ion-infinite-scroll-content>
    </ion-infinite-scroll>
and then in the ts file you need to add the loadMoreProducts($event) function like this :
 loadMoreProducts(event) {
    this.page++;
    console.log("Getting page " + this.page);
    this.WooCommerce.getAsync("products?filter[category]=" + this.category.slug + "&page=" + this.page).then((data) => {
      let temp = (JSON.parse(data.body).products);

      this.products = this.products.concat(JSON.parse(data.body).products)
      console.log(this.products);
      event.complete();

      if (temp.length < 10)
        event.enable(false);
    })

**Comment by ShujaShah** [comment]
> Hi I used the v2 of api rest woocomerce I just try get a list of the products is in one specific category, I use for this Ionic
> 
> ```
> 
>     this.WooComerce.getAsync('products/?filter[category]=myslughere').then((data)=>{
>       console.log('by category ',JSON.parse(data.body));
>       console.log(this.category.slug);
>        this.products = JSON.parse(data.body);
>     }, (err)=>{
>         console.log(err);
>     });
> ```
> 
> but I just received my first 10 item
> the filter is don't work is another way for do this or I miss some thing here

This happens because by default only first 10 products are loaded and to add more products you will need to add the following code in your html file:
`
<ion-infinite-scroll (ionInfinite)="loadMoreProducts($event)">
      <ion-infinite-scroll-content></ion-infinite-scroll-content>
    </ion-infinite-scroll>
`
And then call the function loadMoreProducts($event) in your ts file like this: 
`loadMoreProducts(event) {
    this.page++;
    console.log("Getting page " + this.page);
    this.WooCommerce.getAsync("products?filter[category]=" + this.category.slug + "&page=" + this.page).then((data) => {
      let temp = (JSON.parse(data.body).products);

      this.products = this.products.concat(JSON.parse(data.body).products)
      console.log(this.products);
      event.complete();

      if (temp.length < 20)
        event.enable(false);
    })
  }`

**Comment by ShujaShah** [comment]
> Hi I used the v2 of api rest woocomerce I just try get a list of the products is in one specific category, I use for this Ionic
> 
> ```
> 
>     this.WooComerce.getAsync('products/?filter[category]=myslughere').then((data)=>{
>       console.log('by category ',JSON.parse(data.body));
>       console.log(this.category.slug);
>        this.products = JSON.parse(data.body);
>     }, (err)=>{
>         console.log(err);
>     });
> ```
> 
> but I just received my first 10 item
> the filter is don't work is another way for do this or I miss some thing here

This happens because by default only first 10 products are loaded from a category. You will need to define the following code in the html file :

```
<ion-infinite-scroll (ionInfinite)="loadMoreProducts($event)">
      <ion-infinite-scroll-content></ion-infinite-scroll-content>
    </ion-infinite-scroll>
```

And in the ts file you will need to call the loadMoreProducts($event) function and also define the page: number;

this.page=1 is called when first 10 products are loaded and then 

```
loadMoreProducts(event) {
    this.page++; // increments the page 
    console.log("Getting page " + this.page);
    this.WooCommerce.getAsync("products?filter[category]=" + this.category.slug + "&page=" + this.page).then((data) => {
      let temp = (JSON.parse(data.body).products);
      this.products = this.products.concat(JSON.parse(data.body).products)
      console.log(this.products);
      event.complete();
      if (temp.length < 10)
        event.enable(false);
    })
  }
```
