### ISSUE TITLE
Chosen variation not showing active in variation form

### ISSUE THREAD

**Issue by luizqa** [woocommerce/woocommerce#15516]
### EXPLANATION OF THE ISSUE

Issues in Chrom and Safari:
When choosing a product from drop down menu on product page the chosen product is not showing active within a label. 
In Chrome - if I click chosen product 3 times it shows active
In Safari - after clicking chosen product twice it shows active in the variation form

http://roxwellpress.co.uk/product/spring-blooms-place-card-copy/

Could this be JS conflict?

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
It's the custom select element being implemented by the theme - it needs to listen for WC events to update itself correctly. Contact the theme author.
