### ISSUE TITLE
Invoice reminder send when there is no order

### ISSUE THREAD

**Issue by mickaelmonsieur** [woocommerce/woocommerce#15517]
Woocommerce sends bill payment reminders for deleted orders.

My woocommerce is new and up-to-date, I have no order, they have **all been deleted,** and I receive an email every day for 2 bills to pay. I received this email for 2 months, every day.

The deleted orders were subscriptions.

**Comment by mikejolley** [comment]
Please use the helpdesk for subscriptions issues https://woocommerce.com/contact-us/

Thanks
