### ISSUE TITLE
REST API Update Stock Product Variant

### ISSUE THREAD

**Issue by jmawebtech** [woocommerce/woocommerce#15526]
Hi,

I am trying to update the stock of a product variant. Instead of updating the variant, the parent product gets updated. Should I change my JSON for variants? Please see the attached JSON.

[json.txt](https://github.com/woocommerce/woocommerce/files/1062764/json.txt)

**Comment by mikejolley** [comment]
See https://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-product-variation - there is a dedicated endpoint.
