### ISSUE TITLE
Invalid CSS property value in Cart in Storefront theme

### ISSUE THREAD

**Issue by Jpegtobbe** [woocommerce/woocommerce#15521]
### EXPLANATION OF THE ISSUE

There is invalid css in the Storefront theme, on the cart page. On the remove icon.
In the class table.cart td.product-remove a.remove ->  top: -ms(-2);
Got to be a typo? -ms(-2) is not valid css. I guess thats something from the "modularscale"-lib?

### STEPS TO REPRODUCE THE ISSUE

Go to the cart page. View the page in mobile mode. Then inspect the a.remove element.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://.....
Site URL: http://.....
WC Version: 3.0.7
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache/2.4.4 (Win64) OpenSSL/1.0.1d PHP/5.4.12
PHP Version: ❌ 5.4.12 – Vi rekommenderar lägst PHP-version 5.6. Se: Hur du uppdaterar din PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 40000
PHP Max Input Vars: 5000
cURL Version: 7.29.0
OpenSSL/1.0.1d

SUHOSIN Installed: –
MySQL Version: 5.6.12
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.7
WC Database Prefix: wpdem_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Din butik använder inte HTTPS. Lär dig mer om HTTPS och SSL-certifikat.
Hide errors from visitors: ✔

### Active Plugins (13) ###

Advanced Custom Fields PRO: av Elliot Condon – 5.3.10
BackupBuddy: av iThemes – 7.3.1.0
Black Studio TinyMCE Widget: av Black Studio – 2.3.2
Menu Image: av Alex Davyskiba aka Zviryatko – 2.7.0
Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 2.2.6
Search By SKU - for Woocommerce: av Matthew Lawson – 0.6.1
Simple Custom Post Order: av Colorlib – 2.3.2
TinyMCE Advanced: av Andrew Ozz – 4.5.6
WooCommerce Klarna Gateway: av WooCommerce – 2.3.10
WooCommerce Grid / List toggle: av jameskoster – 1.1.0
WooCommerce: av Automattic – 3.0.7 – 3.0.8 finns tillgänglig
WooCommerce Helper: av WooCommerce – 1.7.2 – Nätverk aktiverat
WP Mail Logging: av Christian Zöller – 1.8.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Butikbas: #2 - /webbshop/
Varukorg: #21 - /varukorg/
Kassan: ❌ Sidan saknar kortkoden.
Mitt konto: #25 - /mitt-konto/

### Theme ###

Name: Djurfarmacia www
Version: 2.1.0
Author URL: http://www.kform.se
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8 – 2.2.3 finns tillgänglig
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: djurfarmacia/archive-product.php
djurfarmacia/cart\cart-totals.php
djurfarmacia/cart\cart.php
djurfarmacia/cart\mini-cart.php
djurfarmacia/content-product.php
djurfarmacia/content-single-product.php
djurfarmacia/global\breadcrumb.php
djurfarmacia/loop\sale-flash.php
djurfarmacia/single-product\add-to-cart\simple.php
djurfarmacia/single-product\meta.php
djurfarmacia/single-product\price.php
djurfarmacia/single-product\related.php
djurfarmacia/single-product\sale-flash.php
djurfarmacia/single-product\short-description.php
djurfarmacia/single-product\tabs\tabs.php
djurfarmacia/single-product\up-sells.php

### Klarna ###

Test mode: Enabled Your Klarna Checkout account must be in test mode for all configured countries in order for it to work
please get in touch with Klarna to check your account status

Sweden: ✔
Norway: Eid not set Secret key not set Checkout URL not set
Finland: Eid not set Secret key not set Checkout URL not set
Germany: Eid not set Secret key not set Checkout URL not set
Austria: Eid not set Secret key not set Checkout URL not set
UK: Eid not set Secret key not set Checkout URL not set
USA: Eid not set Secret key not set Checkout URL not set
Villkorssida: ✔
`
</details>

**Comment by claudiosanches** [comment]
>  Invalid CSS property value in Cart in Storefront theme

And why not report it in the Storefront repository?

https://github.com/woocommerce/storefront
