### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by ernest35** [woocommerce/woocommerce#15529]
Hi my search does not work. Both on the standard theme and on my purchase
[screenshot1](https://prnt.sc/fhpdx4)
[screenshot2](https://prnt.sc/fhpe14)
[screenshot3](https://prnt.sc/fhpfmy)
[screenshot4](https://prnt.sc/fhpg00)

**Comment by mikejolley** [comment]
The search searches titles + content. I'm pretty sure all of those products contain the letter 'b' somewhere :)

**Comment by ernest35** [comment]
thanks I got it
