### ISSUE TITLE
Filter results by date_modified

### ISSUE THREAD

**Issue by natesholland** [woocommerce/woocommerce#15525]
### EXPLANATION OF THE ISSUE

This is a feature request. We would like to see the ability to filter orders by date_modified instead of date created. I looked at the documentation and saw that there is an `after` parameter and an `orderby` parameter but both of these work on `date_created`. I would like to see a way to filter by `date_modified` since I think this would be useful for a number of integrations and would save us from having to make a bunch of extra calls to the WooCommerce API.

### STEPS TO REPRODUCE THE ISSUE

See [the documentation](http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders) for the current api endpoint.

### WHY WE SHOULD ADD THIS FEATURE

I think that this would be a useful thing to have for multiple use cases.
The current use case I have is that I would like to look at a list of orders modified after a certain point.
This could additionally be useful for integrations with products so that they could check for changes in a product catalog without having to scan the entire product catalog again.
It looks like one way to solve this would be to put in a code change around [here](https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/abstracts/abstract-wc-rest-crud-controller.php#L544) to add the ability to filter by `date_modified`.

Additionally this change can be an addition to the existing API and is not a breaking change so it wouldn't require any versioning issues and wouldn't break anyone's existing integrations.

**Comment by natesholland** [comment]
It looks like this was also asked for in: #15444

**Comment by claudiosanches** [comment]
Mikes answer applies to here too https://github.com/woocommerce/woocommerce/issues/15444#issuecomment-306150109
No worry, this filter is something that I personally want to implement here, so I'll not forget about it.

**Comment by natesholland** [comment]
Any ideas on the timeline that it will be coming?

**Comment by claudiosanches** [comment]
We started the development: https://github.com/woocommerce/wc-api-dev
But no timeline yet, still there is filter from WordPress REST API that allows include new filters to any endpoint, so it's possible you implement right now for your projects.

**Comment by jmawebtech** [comment]
Hi,

Can you send me the instructions or sample code to filter orders by the date modified and status, using the wp-json/wc/v2 API?

**Comment by natesholland** [comment]
@jmawebtech There is currently no way to filter by date modified as far as I know. However it is good to know that more people are looking for this functionality.

@claudiosanches any update on when you expect this functionality to come out?

**Comment by jmawebtech** [comment]
I run an Accounting software company and users need to sync refunds. If they can't sync by modified date, users must login to resync each day. You basically can't filter by status without this feature.

**Comment by natesholland** [comment]
@claudiosan any update on this?

**Comment by natesholland** [comment]
Is there any progress on this ticket? This is causing another issue for us.

**Comment by natesholland** [comment]
For anyone who lands here, this has been moved to a feature request here: https://github.com/woocommerce/wc-api-dev/issues/65
