### ISSUE TITLE
Improve caching of wc_customer_bought_product

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#15524]
[`wc_customer_bought_product`](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-user-functions.php#L197) can be called three different ways that get the same results:

`wc_customer_bought_product( 'email@example.com', 12, 50 );`
`wc_customer_bought_product( '', 12, 50 );`
`wc_customer_bought_product( 'email@example.com', 0, 50 );`

The function calculates the transient name using the input email and customer id:
`$transient_name = 'wc_cbp_' . md5( $customer_email . $user_id . WC_Cache_Helper::get_transient_version( 'orders' ) );`

For each of the three ways of calling `wc_customer_bought_product` above, there will be a cache miss, a new query will be run, and a new transient will be cached. 

Since the results will be the same for all three calls, they should ideally all cache to the same place.

**Comment by mikejolley** [comment]
@claudiulodro How is that possible? You don't know the data will be the same until AFTER the query. We only have the passed in props to go by!

**Comment by claudiulodro** [comment]
I don't think this will be possible.
