### ISSUE TITLE
Pass context information to formatted order item meta data filters

### ISSUE THREAD

**Issue by bitadvisor** [woocommerce/woocommerce#15536]
Currently filters `woocommerce_order_item_display_meta_key` and `woocommerce_order_item_display_meta_value` limit what you can do with values since no context information is available.

Those two filter calls should look like this:
`apply_filters( 'woocommerce_order_item_display_meta_key', $display_key, $meta, $this )`
`apply_filters( 'woocommerce_order_item_display_meta_value', $display_value, $meta, $this )`

This is useful for some types of custom product fields, e.g. displaying clickable link for file upload field.

**Comment by mikejolley** [comment]
@bitadvisor Submit this as a PR and I think we can include it :)

**Comment by Chunkford** [comment]
It just so happened I was thinking the same thing, so hope you don't mind @bitadvisor but I created the PR - https://github.com/woocommerce/woocommerce/pull/15551

**Comment by Chunkford** [comment]
@mikejolley just manually updated this and I've noticed that 'woocommerce_order_item_display_meta_value' is called in another files - `class-wc-order-item.php` and `class-wc-order-item-meta.php`

Just created a PR (https://github.com/woocommerce/woocommerce/pull/15554)) for `class-wc-order-item-meta.php` so it matches the same data being passed in, but I'm not sure what to use for the hook being called in 'get_formatted_legacy()'
