### ISSUE TITLE
[FR] Use textbox for email restrictions in coupons

### ISSUE THREAD

**Issue by f3bruary** [woocommerce/woocommerce#15534]
### EXPLANATION FEATURE REQUEST

I made a single coupon code to which I add new users to who have left a rating/review on a third party review site. I make sure each user can only use it once of course.

Each time someone leaves a review and/or rating I add his/her email to the email restrictions list so they can use the same code for themselves. So I find myself adding new email addresses often. Right now this text area is small and contains many comma seperated addresses. It's easy to make a mistake like forgetting a comma and it's difficult to look up an address to confirm it has been added.

My request is to turn it into a (bigger) textbox where I can new email addresses per new line.

![image](https://user-images.githubusercontent.com/5641933/26968680-2f3efba8-4d03-11e7-884c-8de827fa74a2.png)

**Comment by mikejolley** [comment]
This seems like a unique/edge case TBH, and something that could easily be solved in a better way though automation.

Why not have something in place to generate a 1 use coupon when a review is placed? Then you won't need to have this manual process at all :)

Just found this after a quick search https://woocommerce.com/products/review-for-discount/

**Comment by f3bruary** [comment]
My review service is a third party. It's an independant source for reviews with integration into WooCommerce (for automatic sending review requests). It also helps getting yellow stars in google search results.

That plugin is for reviews on the site itself, which I don't really use.

I'll try contacting the review company about it.

**Comment by mikejolley** [comment]
There are hooks triggered when any review is added; I think it would be possible to build.
