### ISSUE TITLE
V2 API Filter SKU

### ISSUE THREAD

**Issue by jmawebtech** [woocommerce/woocommerce#15549]
Hi,

I am trying to filter products by SKU.

When I use the V1 endpoint, it works. When I use V2, I get an error saying no end point can be found. Is SKU no longer filterable? I noticed that there is no products end point. Is something wrong with his version?

https://valfa.com/wp-json/wc/v2

Is there a way to get his WooCommerce version number? Perhaps he is using an older version of V2 where the products endpoint is missing.

Please see attached.
[sku.txt](https://github.com/woocommerce/woocommerce/files/1065537/sku.txt)

**Comment by mikejolley** [comment]
There is no older version where they are not included; product endpoints are available under v2. The endpoint is valid.

It looks like something on his install is disabling those endpoints. I'd guess a plugin, but you'd need to debug his site to establish the cause.

I've confirmed other installs have the endpoints so this does not look like a core issue.
