### ISSUE TITLE
Woocommerce Product Review Count On Thumbnail

### ISSUE THREAD

**Issue by cannabismo** [woocommerce/woocommerce#15548]
Woocommerce Product Review Count Display

Review count only shows up on full product page:
http://imgur.com/a/jEyQP

How do i get it to display review count on the thumbnail:
http://imgur.com/a/lNF6d

Where do i edit and which code do i add?

**Comment by mikejolley** [comment]
What you're trying to do is possible with template overrides or hooks, but this is not a support forum and I cannot provide customisations. If you need help, hire a developer to code this into your theme.
