### ISSUE TITLE
The layout of Product list is corrupted

### ISSUE THREAD

**Issue by ikourfaln** [woocommerce/woocommerce#15553]
### EXPLANATION OF THE ISSUE

As you can see in the image:

![capture](https://user-images.githubusercontent.com/9744226/27002819-4444857c-4dda-11e7-84e6-7878656414bc.PNG)

the two column, stock, and price are without width, broken.
it was fine at first, but after a while, The problem occurs !!!
I didn't touch anything !! and I can't fix it.

### STEPS TO REPRODUCE THE ISSUE

it just happens. I recreate my project again, all fine, but again, after a while, The problem occurs.
### SYSTEM STATUS

<details>

### WordPress Environment ###

Home URL: http://solusglobus.org/idb3
Site URL: http://solusglobus.org/idb3
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (23) ###

Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.10
Contact Form 7: by Takayuki Miyoshi – 4.8
Dynamic Featured Image: by Ankit Pokhrel – 3.5.2
Envato WordPress Toolkit: by Envato – 1.7.3
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Mailgun: by Mailgun – 1.5.8.2
Porto Content Types: by SW-THEMES – 1.3.1
Porto Shortcodes: by SW-THEMES – 1.6.6
Porto Widgets: by SW-THEMES – 1.3.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.3.1.5
Telr Secure Payments: by Telr – 2.0
WC Vendors: by WC Vendors – 1.9.11
WooCommerce Aramex: by WooThemes – 1.0.2
WooCommerce: by Automattic – 3.0.8
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.9
WP Sitemap Page: by Tony Archambeau – 1.6
WP User Avatar: by flippercode – 2.0.8
MailPoet Newsletters: by MailPoet – 2.7.10
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.4.2
YITH WooCommerce Ajax Search: by YITHEMES – 1.5.3
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AED (د.إ)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #207 - /shop/
Cart: #208 - /cart/
Checkout: #209 - /checkout/
My account: #210 - /my-account/

### Theme ###

Name: Porto
Version: 3.6.2
Author URL: http://www.newsmartwave.net/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/content-product.php
porto/woocommerce/content-product_cat.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/order-details.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/external.php
porto/woocommerce/single-product/add-to-cart/grouped.php version 3.0.6 is out of date. The core version is 3.0.7
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/share.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

Outdated Templates: ❌Learn how to update

</details>

**Comment by mikejolley** [comment]
Screen options, top right of the screen. Hide some columns - there are too many (added by SEO plugin).
