### ISSUE TITLE
export woocommere

### ISSUE THREAD

**Issue by uldemarche** [woocommerce/woocommerce#15557]
Hello,
From my woocommerce store, product categories have been selected but not parent categories :
https://www.dropbox.com/s/z5ipr8u2ikhz3jj/Immage%201.png?dl=0
On the store fronted, the products are correctly placed under the parent category even if not selected. https://www.dropbox.com/s/mqny6uvo9a09eps/Immage%202.png?dl=0

I can extract this information on csv file for export ?

**Comment by mikejolley** [comment]
Categories are hierarchical, so if you have a product inside a sub-category, it's still contained within the parent category. Not sure how this bares any relevance to export.

**Comment by uldemarche** [comment]
I know the categories are hierarchical.

But the information of each product to which category is associated, where can I find them?

**Comment by mikejolley** [comment]
wp_term_relationships

**Comment by uldemarche** [comment]
I'm sorry, I did not understand

**Comment by claudiosanches** [comment]
@uldemarche 

> But the information of each product to which category is associated, where can I find them?

You can find in the `wp_term_relationships` table created by WordPress.

**Comment by uldemarche** [comment]
Thanks for the answers.
I would need a little more help.
I've seen in the wp_term_relationships table and I have the fields

Object_id Descending
term_taxonomy_id
term_order
Where do I find the information I need?
Thank you

**Comment by mikejolley** [comment]
This is not a WC question. Terms are part of WordPress. You should do your own research into this - Github is not a support forum.

**Comment by uldemarche** [comment]
Ok thanks and I apologize
