### ISSUE TITLE
Reconsiderations on - "product titles missing attributes #15225"

### ISSUE THREAD

**Issue by stockmaster** [woocommerce/woocommerce#15555]
In relation to the following issue:
Add new order: variation product titles missing attributes #15225 

Some strange behavior - at least different from < 3.0 WC 

If a product has more than ONE variation attribute adding a product to an order in the backend will not display the identifier labels while searching.

Example:
Product contains ONE attribute 
https://gyazo.com/180b11ef3cbe47f92a2c639e1e195989
There is one variation per Attribute, active and with price
https://gyazo.com/5295cdd875c154a99958815f7f873d5c

When in order -> add a new product -> search by product name -> Variations are listed with their identifier label variation
https://gyazo.com/166227f1fdca4aef79bab444aa1c9f0b

This is correct and normal behavior

IF a 2nd attribute is set, 
https://gyazo.com/c229876c54f67788d32b166761b3fa7f
And each variation is set to use any (OR one) of the 2 second atributes
https://gyazo.com/cd81adf596699db9f8880486ce3f2380

While trying to add a product -> search by product name -> variation apears and is added correctly however its identifying lable is lost, rendering the search pretty much useless as one has to memorize the product variation by #xxxxx ID number.
Note # 6895 lost both  variation lables

However if added to product it does add both atributes correctly
https://gyazo.com/8008798fd0e3cd6489bee9a8f6bd75ca

IF the 2ndproduct atribute is set to ANY in the variation. the label of the first attribute is kept but the 2nd metadata attribute is dismissed once added to the order: 
https://gyazo.com/ca2162a283f081b36adf0cec408f36f4

neither of this situations is optimal.

The problem with this is it becomes nearly impossible to memorize variations 
And in a product with many variations its nearly impossible to know what product is what combination of variables.

I believe the commit https://github.com/woocommerce/woocommerce/commit/9001978b1c240f82a21bcd9e68fd5b8ab84bd1b7 should be rethought for the sake of shop administrators inability to work what they are doing in product variations when adding by hand products.

### SYSTEM STATUS

`
### WordPress Environment ###

Home URL: https://www.lojadofolclore.pt
Site URL: https://www.lojadofolclore.pt
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_PT

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wpld_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (54) ###

Ultimate Addons for Visual Composer: por Brainstorm Force – 3.16.10
Admin Menu Editor: por Janis Elsts – 1.7.3
Cloudflare: por John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.2.1

Cookie Law Info: por Richard Ashby – 1.5.3
Delete Expired Transients: por WebAware – 2.0.6
Duplicate Page: por mndpsingh287 – 2.3
EuPago para WooCommerce: por WebAtual – 0.1.2
EWWW Image Optimizer: por Shane Bishop – 3.4.1
Ninja Facebook Messenger: por Ninja Team – 2.1
Heartbeat Control: por Jeff Matson – 1.0.3
WPBakery Visual Composer: por Michael M - WPBakery.com – 5.1.1
Popup Maker: por WP Popup Maker – 1.6.3
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: por ThemePunch – 5.4.1
Server IP & Memory Usage Display: por Apasionados
Apasionados del Marketing – 2.0.3

Simple Login Log: por Max Chirkov – 1.1.2
Preloader: por Alobaidi – 1.0.9
Visual Composer Clipboard: por bitorbit – 3.24
WC Call For Price: por  – 1.1.1
WooCommerce Cash On Pickup: por Pinch Of Code – 1.1.2
WooCommerce Payment Fees Lite: por Pinch Of Code – 1.5.2
WooCommerce: por Automattic – 3.0.8
Yoast SEO: por Team Yoast – 4.9
WP Super Cache - Clear all cache: por Apasionados.es – 1.4
WP Super Cache: por Automattic – 1.4.9
WP-Sweep: por Lester 'GaMerZ' Chan – 1.0.10
XCloner - Site Backup and Restore: por Liuta Ovidiu – 4.0.4
YITH Desktop Notifications for WooCommerce Premium: por YITHEMES – 1.1.0
YITH Essential Kit for WooCommerce #1: por YIThemes – 1.4.7
YITH Infinite Scrolling Premium: por YITHEMES – 1.1.0
YITH Live Chat Premium: por YITHEMES – 1.2.1
YITH Product Size Charts for WooCommerce Premium: por YITHEMES – 1.1.0
YITH WooCommerce Product Add-Ons Premium: por YITHEMES – 1.2.5
YITH WooCommerce Advanced Reviews Premium: por YITHEMES – 1.4.2
YITH WooCommerce Ajax Product Filter Premium: por YITHEMES – 3.4.2
YITH WooCommerce Ajax Search Premium: por YITHEMES – 1.5.5
YITH WooCommerce Badge Management Premium: por YITHEMES – 1.3.3
YITH WooCommerce Bulk Product Editing Premium: por YITHEMES – 1.2.3
YITH WooCommerce Category Accordion Premium: por YITHEMES – 1.0.16
YITH WooCommerce Checkout Manager: por YITHEMES – 1.0.5
YITH WooCommerce Color and Label Variations Premium: por YITHEMES – 1.3.0
YITH WooCommerce Custom Order Status Premium: por YITHEMES – 1.1.0
YITH WooCommerce Customer History Premium: por YITHEMES – 1.0.5
YITH WooCommerce Customize My Account Page: por YITHEMES – 2.1.0
YITH WooCommerce Email Templates Premium: por YITHEMES – 1.3.2
YITH WooCommerce Featured Audio and Video Content: por YITHEMES – 1.1.10
YITH WooCommerce Order Tracking Premium: por YITHEMES – 1.2.84
YITH WooCommerce PDF Invoice and Shipping List Premium: por YITHEMES – 1.4.16
YITH WooCommerce Questions and Answers Premium: por YITHEMES – 1.1.24
YITH Woocommerce Request A Quote Premium: por YITHEMES – 1.7.6
YITH WooCommerce Sequential Order Number: por Yithemes – 1.0.11
YITH WooCommerce Social Login Premium: por YITHEMES – 1.2.0
YITH WooCommerce Stripe Premium: por YIThemes – 1.3.0
YITH WooCommerce Tab Manager Premium: por YITHEMES – 1.1.22

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
variable (variable)

Taxonomies: Product Visibility: featured (featured)
outofstock (outofstock)

### WC Pages ###

Página da Loja: #6 - /loja/
Carrinho: #7 - /cart/
Finalizar compras: #8 - /checkout/
Minha conta: #9 - /minha-conta/

### Theme ###

Name: Rémy Child
Version: 1.1.4
Author URL: http://yithemes.com/
Child Theme: ✔
Parent Theme Name: Rémy
Parent Theme Version: 1.1.4
Parent Theme Author URL: http://yithemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: remy/woocommerce/archive-product.php
remy/woocommerce/cart/cart-empty.php
remy/woocommerce/cart/cart-shipping.php
remy/woocommerce/cart/cart-totals.php
remy/woocommerce/cart/cart.php
remy/woocommerce/cart/mini-cart.php
remy/woocommerce/cart/shipping-calculator.php
remy/woocommerce/checkout/form-checkout.php
remy/woocommerce/checkout/form-coupon.php
remy/woocommerce/checkout/form-login.php
remy/woocommerce/checkout/form-shipping.php
remy/woocommerce/checkout/review-order.php
remy/woocommerce/content-product.php
remy/woocommerce/content-product_cat.php
remy/woocommerce/content-single-product.php
remy/woocommerce/content-widget-product.php
remy/woocommerce/global/form-login.php
remy/woocommerce/global/sidebar.php
remy/woocommerce/global/wrapper-end.php
remy/woocommerce/global/wrapper-start.php
remy/woocommerce/loop/add-to-cart.php
remy/woocommerce/loop/loop-end.php
remy/woocommerce/loop/loop-start.php
remy/woocommerce/myaccount/my-downloads.php
remy/woocommerce/myaccount/my-orders.php
remy/woocommerce/myaccount/navigation.php
remy/woocommerce/single-product/add-to-cart/external.php
remy/woocommerce/single-product/add-to-cart/simple.php
remy/woocommerce/single-product/product-image.php
remy/woocommerce/single-product/rating.php
remy/woocommerce/single-product/sale-flash.php
remy/woocommerce/single-product-reviews.php

**Comment by mikejolley** [comment]
For the admin lists, we should probably list ones not in the title.

**Comment by ShopLancaster** [comment]
I too am facing this issue. Since updating to 3.0 a few products are still using the old formatting with variations listed below the product title. We have tried duplicating the product and it still faces the same issue. How can we fix those specific products to follow the same format as the others?

<img width="292" alt="correct" src="https://user-images.githubusercontent.com/10392998/29421924-9133df64-8344-11e7-8ee4-b2fd937afb72.png">
<img width="258" alt="incorrect" src="https://user-images.githubusercontent.com/10392998/29421925-913bbcfc-8344-11e7-9d3d-54ab7e4a6962.png">

Thank you!
