### ISSUE TITLE
Costumers using Paypal are redirected to wp-admin/profile.php.

### ISSUE THREAD

**Issue by jwit** [woocommerce/woocommerce#15568]
### EXPLANATION OF THE ISSUE

Users are reporting they end up in the dashboard after placing an order. I checked the logs and it confirms that they are redirected to the wp-admin/profile.php page. It only happens after a payment was done with Paypal. I tried opening the page with the same role but I was redirected to the My Account page with a 302 redirect. I also placed an order to see how they got there but it didn't happen to me and there is no link to the profile page that they could have clicked.

Here is a part of the log. I cleaned up the private information. IP address 1.1.1.1 is the user. 2.2.2.2 is Paypal. 127.0.0.1 is the server ip address.

```
1.1.1.1 - - [11/Jun/2017:18:25:20 -0700] "GET /checkout/ HTTP/1.1" 200 115592 "/checkout/" 
1.1.1.1 - - [11/Jun/2017:18:25:23 -0700] "POST /checkout/?wc-ajax=get_refreshed_fragments HTTP/1.1" 200 4177 "/checkout/" 
1.1.1.1 - - [11/Jun/2017:18:25:23 -0700] "POST /checkout/?wc-ajax=update_order_review HTTP/1.1" 200 10480 "/checkout/" 
1.1.1.1 - - [11/Jun/2017:18:25:42 -0700] "POST /checkout/?wc-ajax=checkout HTTP/1.1" 200 2212 "/checkout/" 
1.1.1.1 - - [11/Jun/2017:18:26:49 -0700] "GET /checkout/order-received/38103?key=wc_order_12345678
1.1.1.1 - - [11/Jun/2017:18:26:51 -0700] "GET /checkout/order-received/38103/?key=wc_order_12345678
1.1.1.1 - - [11/Jun/2017:18:26:53 -0700] "POST /checkout/order-received/38103/?key=wc_order_12345678
2.2.2.2 - - [11/Jun/2017:18:26:49 -0700] "POST /wc-api/WC_Gateway_Paypal/ HTTP/1.1" 200 5125 "-" "PayPal IPN ( https://www.paypal.com/ipn )" 
127.0.0.1 - - [11/Jun/2017:18:26:50 -0700] "POST /wp-cron.php?doing_wp_cron=12345678 HTTP/1.1" 200 5056 "/wp-cron.php?doing_wp_cron=12345678" "WordPress/4.7.5; " 
1.1.1.1 - - [11/Jun/2017:18:27:08 -0700] "GET /product/my-product/ HTTP/1.1" 200 80014 "/checkout/order-received/38103/?key=wc_order_12345678
1.1.1.1 - - [11/Jun/2017:18:33:51 -0700] "GET /wp-admin/profile.php HTTP/1.1" 200 163272 "/checkout/order-received/38103/?key=wc_order_12345678
```

The strange thing is that they click on the product page after payment as expected. But 5 minutes later they end up on the profile.php with the order-received page still as the referral page.

### STEPS TO REPRODUCE THE ISSUE

1. Add product to cart and check out. 
2. Pay using Paypal.
3. After the payment you are redirected to wp-admin/profile.php but I don't know how.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 65 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (34) ###

VaultPress: by Automattic – 1.9.0
ActiveCampaign: by ActiveCampaign – 6.2.12
Add to All: by Ajay D'Souza – 1.2.2
AffiliateWP: by AffiliateWP LLC – 2.0.9.2
Black Studio TinyMCE Widget: by Black Studio – 2.3.2
Contact Form 7: by Takayuki Miyoshi – 4.8
Duplicate Page: by mndpsingh287 – 2.3
ES Woocommerce ActiveCampaign: by EqualServing.com – 1.1
EWWW Image Optimizer: by Shane Bishop – 3.4.1
Header and Footer Scripts: by Anand Kumar – 1.3.4
JF3 Maintenance Redirect: by Jack Finch – 1.3
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Universal Video Player - Addon For Visual Composer: by Lambert Group – 1.4.4
Media Cleaner: by Jordy Meow – 4.0.2
OptinMonster API: by OptinMonster Team – 1.1.9
PixelYourSite PRO: by PixelYourSite – 6.1.3
Slider Revolution Background FilmStrip Add-On: by ThemePunch – 1.0.0
Slider Revolution: by ThemePunch – 5.4.3
TheGem Theme Elements: by Codex Themes – 2.2.1
Woo Import Export: by VJInfotech – 2.4
Woocommerce CSV Import: by Allaerd Mensonides – 3.3.5
WooCommerce Amazon Pay Gateway: by WooCommerce – 1.7.1
WooCommerce Stripe Gateway: by WooCommerce – 3.1.9
WooCommerce Smart Coupons: by StoreApps – 3.3.3
WooCommerce: by Automattic – 3.0.8
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WP File Manager: by mndpsingh287 – 1.6
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

Wordpress Page Widgets: by CodeAndMore – 3.2
WPForms Lite: by WPForms – 1.3.7.4
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2
YouTube: by EmbedPlus Team – 11.8
ZillaLikes: by ThemeZilla – 1.1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
variation (variation)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #13 - /shop/
Cart: #35 - /cart/
Checkout: #36 - /checkout/
My account: #37 - /my-account/

### Theme ###

Name: TheGem
Version: 2.2.0
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: thegem/woocommerce/archive-product.php
thegem/woocommerce/cart/cart-shipping.php
thegem/woocommerce/cart/cart-totals.php
thegem/woocommerce/cart/cart.php
thegem/woocommerce/cart/cross-sells.php
thegem/woocommerce/cart/mini-cart.php
thegem/woocommerce/cart/shipping-calculator.php
thegem/woocommerce/checkout/form-billing.php
thegem/woocommerce/checkout/form-checkout.php
thegem/woocommerce/checkout/form-coupon.php
thegem/woocommerce/checkout/form-login.php
thegem/woocommerce/checkout/form-shipping.php
thegem/woocommerce/checkout/payment-method.php
thegem/woocommerce/checkout/payment.php
thegem/woocommerce/checkout/review-order.php
thegem/woocommerce/checkout/terms.php
thegem/woocommerce/checkout/thankyou.php
thegem/woocommerce/content-product.php
thegem/woocommerce/content-product_cat.php
thegem/woocommerce/content-single-product.php
thegem/woocommerce/content-widget-product.php
thegem/woocommerce/global/breadcrumb.php
thegem/woocommerce/global/form-login.php
thegem/woocommerce/loop/loop-end.php
thegem/woocommerce/loop/loop-start.php
thegem/woocommerce/loop/orderby.php
thegem/woocommerce/loop/pagination.php
thegem/woocommerce/loop/price.php
thegem/woocommerce/loop/rating.php
thegem/woocommerce/loop/result-count.php
thegem/woocommerce/loop/sale-flash.php
thegem/woocommerce/myaccount/form-edit-account.php
thegem/woocommerce/myaccount/form-edit-address.php
thegem/woocommerce/myaccount/form-login.php
thegem/woocommerce/myaccount/form-lost-password.php
thegem/woocommerce/myaccount/form-reset-password.php
thegem/woocommerce/myaccount/my-account.php
thegem/woocommerce/myaccount/navigation.php
thegem/woocommerce/myaccount/orders.php
thegem/woocommerce/order/order-details-customer.php
thegem/woocommerce/order/order-details-item.php
thegem/woocommerce/order/order-details.php
thegem/woocommerce/product-searchform.php
thegem/woocommerce/single-product/add-to-cart/external.php
thegem/woocommerce/single-product/add-to-cart/grouped.php version 3.0.3 is out of date. The core version is 3.0.7
thegem/woocommerce/single-product/add-to-cart/simple.php
thegem/woocommerce/single-product/add-to-cart/variable.php
thegem/woocommerce/single-product/meta.php
thegem/woocommerce/single-product/rating.php
thegem/woocommerce/single-product/related.php
thegem/woocommerce/single-product/review.php
thegem/woocommerce/single-product/short-description.php
thegem/woocommerce/single-product/tabs/additional-information.php
thegem/woocommerce/single-product/tabs/description.php
thegem/woocommerce/single-product/tabs/tabs.php
thegem/woocommerce/single-product/title.php
thegem/woocommerce/single-product-reviews.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
WooCommerce has no redirect code to this page. In fact, WC blocks access to admin for non-admin by default FWIW, thats why you see that 302.

Sounds like it could be a rogue plugin. `JF3 Maintenance Redirect` has redirect code based on cookies etc - have you ruled that out? It's > 2 years old.

You should do the same for others too, and maybe see if there is any other redirect code in htaccess or find a way to log it. Unfortunately without steps to replicate I cannot confirm a WC core issue, nor replicate it.
