### ISSUE TITLE
deprecated method referencing deprecated function as replacement.

### ISSUE THREAD

**Issue by katdidit** [woocommerce/woocommerce#15562]
### EXPLANATION OF THE ISSUE

Woo version 3.10 deprecated function get_product() cross referenced as replacement for deprecated method get_product_from_item 

https://docs.woocommerce.com/wc-apidocs/source-class-WC_Abstract_Legacy_Order.html#313-326

original function Function in the plugin is  `$order->get_product_from_item($item);`  which if I follow the deprecated instructions would be changed to `$item->get_product();` 

Sorry to be dense, but what am I missing here?  I could not find get_product() defined in any other function or class as a method, but it is used in a few places.    I think it should be wc_get_product() but am not sure if that is correct because it doesn't take arguments.  I am getting ready to test `$item->wc_get_product()`

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/blob/9f4b29a677b3a00885021b79b6bad4a425a86c52/includes/class-wc-order-item-product.php#L315
