### ISSUE TITLE
Improve importer image handling.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#15576]
This has been a big issue when I have tried to import csvs from customer sites we're upgrading. Some people use giant, 3000x3000 2 Mb images for products. When the importer tries to process these, sometimes it runs out of time downloading them.

In the best case situation when it runs out of time downloading the image you get an error like this:
`
Error getting remote image https://XXXXXXXXXX.com/wp-content/uploads/2010/02/D3S4889-copy.jpg. Error: cURL error 28: Operation timed out after 9998 milliseconds with 4306236 out of 5675879 bytes received.
`
When this happens, the product is marked as "Failed" in the import.

In the worst case situation, you get this:
`
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /srv/www/wordpress-default/public_html/wp-includes/class-wp-image-editor-imagick.php on line 363
`
And the importer breaks because of a 500 error in the ajax call.

Here's two potential solutions (I'm sure there are other better ones probably):
- Decrease import batch size
- Don't export full size images in exporter. Export at a reasonable size if the image is giant.

**Comment by mikejolley** [comment]
- Add ajax error handling
- Don't import if the exported image already exists on server
- Have a check per ajax run to see what the memory usage is looking like/time, then return current progress and offset from that rather than a fixed offset per run

**Comment by mikejolley** [comment]
@claudiulodro Take a look at how it's done in background processing: https://github.com/woocommerce/woocommerce/blob/master/includes/libraries/wp-background-process.php#L308

If exceeded, we can return how many records were processed, and this can be used to calculate the offset for the next import task in our JS script.

As for the error 500, the script should just continue if encountered, not fail.

**Comment by claudiosanches** [comment]
> Don't import if the exported image already exists on server

We already check if the image already exists:

https://github.com/woocommerce/woocommerce/blob/master/includes/import/abstract-wc-product-importer.php#L483-L523

**Comment by mikejolley** [comment]
I see the failure logs to console. Since it fails it would be wrong to continue/retry. So see #15615
