### ISSUE TITLE
Login Issue when the username is an email address that is different than the email address

### ISSUE THREAD

**Issue by rdbrinkhurst** [woocommerce/woocommerce#15577]
### EXPLANATION OF THE ISSUE

Let's say that I have the username ryan@test.com but my email address is rbrinkhurst@test.com

I can't login using ryan@test.com on the My Account page, but rbrinkhurst@test.com will work.

If I use the normal WordPress login - "/wp-login.php" - I can login with both username and password.

If my username is the same as my email, I can login fine. If the username is not an email address, I can also login fine.

### STEPS TO REPRODUCE THE ISSUE

I tried this on WordPress 4.7.5 with no plugins activated and the Twenty Seventeen theme.

### SYSTEM STATUS

<details>
WordPress environment
Home URL: 		https://www.chalearning.ca
Site URL: 		https://www.chalearning.ca
WC version: 		3.0.8
Log directory writable: 		/var/www/html/chalearning/wp-content/uploads/wc-logs/
WP version: 		4.7.5
WP multisite: 		–
WP memory limit: 		256 MB
WP debug mode: 		–
WP cron: 		
Language: 		en_US
Server environment
Server info: 		Apache/2.4.7 (Ubuntu)
PHP version: 		5.6.30-11+deb.sury.org~trusty+3
PHP post max size: 		8 MB
PHP time limit: 		-1
PHP max input vars: 		1000
cURL version: 		7.35.0, OpenSSL/1.0.1f
SUHOSIN installed: 		–
MySQL version: 		5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements	
Max upload size: 		2 MB
Default timezone is UTC: 		
fsockopen/cURL: 		
SoapClient: 		Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.	
DOMDocument: 		
GZip: 		
Multibyte string: 		
Remote post: 		
Remote get: 		
Database
WC database version: 		3.0.8
Database prefix 	  	wp_khxcby_	
woocommerce_sessions 	  	
woocommerce_api_keys 	  	
woocommerce_attribute_taxonomies 	  	
woocommerce_downloadable_product_permissions 	  	
woocommerce_order_items 	  	
woocommerce_order_itemmeta 	  	
woocommerce_tax_rates 	  	
woocommerce_tax_rate_locations 	  	
woocommerce_shipping_zones 	  	
woocommerce_shipping_zone_locations 	  	
woocommerce_shipping_zone_methods 	  	
woocommerce_payment_tokens 	  	
woocommerce_payment_tokenmeta 	  	
MaxMind GeoIP database: 		The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: /var/www/html/chalearning/wp-content/uploads/GeoIP.dat. Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Security
Secure connection (HTTPS): 		
Hide errors from visitors 		
Active plugins (44)
Gravity Forms 	  	by rocketgenius – 2.2.3
Accordion Shortcodes 	  	by Phil Buchanan – 2.3.2
Advanced Custom Fields Multilingual 	  	by OnTheGo Systems – 0.4
Advanced Custom Fields PRO 	  	by Elliot Condon – 5.5.14
Custom Post Type UI 	  	by WebDevStudios – 1.5.3
Dual Code Moodle Integration 	  	by Mohd Abdullah Al Nasser – 1.0.0
Gravity Forms Multilingual 	  	by OnTheGoSystems – 1.3.15
Gravity Forms MailChimp Add-On 	  	by rocketgenius – 4.2
Groups Import Export 	  	by itthinx – 1.2.4
Groups WooCommerce 	  	by itthinx – 1.2.0
Groups 	  	by itthinx – 2.2.0
Meta Slider - Pro Addon Pack 	  	by Matcha Labs – 2.7
Meta Slider 	  	by Matcha Labs – 3.5.1
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC) 	  	by XAdapter – 1.1.9
Popup Maker 	  	by WP Popup Maker – 1.6.3
Product CSV Import Export (BASIC) 	  	by XAdapter – 1.3.2
Responsive Lightbox 	  	by subhansanjaya – 1.3.2
Responsive Menu Pro 	  	by Peter Featherstone – 3.1.3
Search Everything 	  	by Sovrn, zemanta – 8.1.9
WPML Multilingual CMS 	  	by OnTheGoSystems – 3.7.1
TablePress 	  	by Tobias Bäthge – 1.8
The Events Calendar Shortcode 	  	by Event Calendar Newsletter – 1.6
The Events Calendar 	  	by Modern Tribe, Inc. – 4.5.2.1
TinyMCE Advanced 	  	by Andrew Ozz – 4.5.6
WooCommerce Adobe Connect connector plugin. 	  	by Relit.Ca – 1.0
WooCommerce Custom Product Tabs Lite 	  	by SkyVerge – 1.6.1
WooCommerce Customer/Order CSV Export 	  	by WooThemes / SkyVerge – 3.12.0 – 4.3.5 is available
WooCommerce Dynamic Pricing 	  	by Lucas Stark – 3.0.8 – 3.0.9 is available
WooCommerce Email Test 	  	by RaiserWeb – 1.8
Follow-Up Emails 	  	by 75nineteen Media LLC – 4.4.7 – 4.4.19 is available
WooCommerce Moneris Gateway 	  	by WooThemes / SkyVerge – 2.6.0 – 2.7.2 is available
WooCommerce - Gravity Forms Product Add-Ons 	  	by WooThemes – 2.10.6 – 3.1.10 is available
WooCommerce Multilingual 	  	by OnTheGoSystems – 4.1.4
WooCommerce Smart Coupons 	  	by StoreApps – 3.3.1 – 3.3.3 is available
WooCommerce 	  	by Automattic – 3.0.8
Yoast SEO 	  	by Team Yoast – 4.8
WP All Export Pro 	  	by Soflyy – 1.4.6
WP All Import Pro 	  	by Soflyy – 4.4.8
wp2moodle 	  	by Tim St.Clair – 0.1
WPML CMS Nav 	  	by OnTheGoSystems – 1.4.20
WPML Media 	  	by OnTheGoSystems – 2.2.0
WPML Sticky Links 	  	by OnTheGoSystems – 1.4.1
WPML String Translation 	  	by OnTheGoSystems – 2.5.4
WPML Translation Management 	  	by OnTheGoSystems – 2.3.1
Settings
API enabled: 		
Force SSL: 		–
Currency 		CAD ($)
Currency position 		left
Thousand separator 		,
Decimal separator 		.
Number of decimals 		2
Taxonomies: Product types 		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility 		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		Page visibility should be public
Cart:		#21 - /cart/
Checkout:		#22 - /checkout/
My account:		#23 - /my-account/
Theme
Name: 		CHA
Version: 		1.0.0
Author URL: 		http://www.brinkhurst.com/
Child theme: 		– If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support: 		
Templates
Overrides 	  	chalearning/woocommerce/archive-product.php,
chalearning/woocommerce/auth/footer.php,
chalearning/woocommerce/auth/form-grant-access.php,
chalearning/woocommerce/auth/form-login.php,
chalearning/woocommerce/auth/header.php,
chalearning/woocommerce/cart/cart-empty.php,
chalearning/woocommerce/cart/cart-item-data.php,
chalearning/woocommerce/cart/cart-shipping.php,
chalearning/woocommerce/cart/cart-totals.php,
chalearning/woocommerce/cart/cart.php,
chalearning/woocommerce/cart/cross-sells.php,
chalearning/woocommerce/cart/mini-cart.php,
chalearning/woocommerce/cart/proceed-to-checkout-button.php,
chalearning/woocommerce/cart/shipping-calculator.php,
chalearning/woocommerce/checkout/cart-errors.php,
chalearning/woocommerce/checkout/form-billing.php,
chalearning/woocommerce/checkout/form-checkout.php,
chalearning/woocommerce/checkout/form-coupon.php,
chalearning/woocommerce/checkout/form-login.php,
chalearning/woocommerce/checkout/form-pay.php,
chalearning/woocommerce/checkout/form-shipping.php,
chalearning/woocommerce/checkout/payment-method.php,
chalearning/woocommerce/checkout/payment.php,
chalearning/woocommerce/checkout/review-order.php,
chalearning/woocommerce/checkout/terms.php,
chalearning/woocommerce/checkout/thankyou.php,
chalearning/woocommerce/content-product.php,
chalearning/woocommerce/content-product_cat.php,
chalearning/woocommerce/content-single-product.php,
chalearning/woocommerce/content-widget-product.php,
chalearning/woocommerce/emails/admin-cancelled-order.php,
chalearning/woocommerce/emails/admin-failed-order.php,
chalearning/woocommerce/emails/admin-new-order.php version 2.4.0 is out of date. The core version is 2.5.0,
chalearning/woocommerce/emails/customer-completed-order.php version 2.4.0 is out of date. The core version is 2.5.0,
chalearning/woocommerce/emails/customer-invoice.php version 2.4.0 is out of date. The core version is 2.5.0,
chalearning/woocommerce/emails/customer-new-account.php,
chalearning/woocommerce/emails/customer-note.php version 2.4.0 is out of date. The core version is 2.5.0,
chalearning/woocommerce/emails/customer-on-hold-order.php,
chalearning/woocommerce/emails/customer-processing-order.php version 2.4.0 is out of date. The core version is 2.5.0,
chalearning/woocommerce/emails/customer-refunded-order.php,
chalearning/woocommerce/emails/customer-reset-password.php,
chalearning/woocommerce/emails/email-addresses.php version 2.4.0 is out of date. The core version is 3.0.0,
chalearning/woocommerce/emails/email-customer-details.php,
chalearning/woocommerce/emails/email-footer.php,
chalearning/woocommerce/emails/email-header.php,
chalearning/woocommerce/emails/email-order-details.php,
chalearning/woocommerce/emails/email-order-items.php version 2.1.2 is out of date. The core version is 3.0.0,
chalearning/woocommerce/emails/email-styles.php,
chalearning/woocommerce/emails/plain/admin-cancelled-order.php,
chalearning/woocommerce/emails/plain/admin-failed-order.php,
chalearning/woocommerce/emails/plain/admin-new-order.php,
chalearning/woocommerce/emails/plain/customer-completed-order.php,
chalearning/woocommerce/emails/plain/customer-invoice.php,
chalearning/woocommerce/emails/plain/customer-new-account.php,
chalearning/woocommerce/emails/plain/customer-note.php,
chalearning/woocommerce/emails/plain/customer-on-hold-order.php,
chalearning/woocommerce/emails/plain/customer-processing-order.php,
chalearning/woocommerce/emails/plain/customer-refunded-order.php,
chalearning/woocommerce/emails/plain/customer-reset-password.php,
chalearning/woocommerce/emails/plain/email-addresses.php,
chalearning/woocommerce/emails/plain/email-customer-details.php,
chalearning/woocommerce/emails/plain/email-order-details.php,
chalearning/woocommerce/emails/plain/email-order-items.php,
chalearning/woocommerce/global/breadcrumb.php,
chalearning/woocommerce/global/form-login.php,
chalearning/woocommerce/global/quantity-input.php,
chalearning/woocommerce/global/sidebar.php,
chalearning/woocommerce/global/wrapper-end.php,
chalearning/woocommerce/global/wrapper-start.php,
chalearning/woocommerce/loop/add-to-cart.php,
chalearning/woocommerce/loop/loop-end.php,
chalearning/woocommerce/loop/loop-start.php,
chalearning/woocommerce/loop/no-products-found.php,
chalearning/woocommerce/loop/orderby.php,
chalearning/woocommerce/loop/pagination.php,
chalearning/woocommerce/loop/price.php,
chalearning/woocommerce/loop/rating.php,
chalearning/woocommerce/loop/result-count.php,
chalearning/woocommerce/loop/sale-flash.php,
chalearning/woocommerce/myaccount/dashboard.php,
chalearning/woocommerce/myaccount/downloads.php,
chalearning/woocommerce/myaccount/form-add-payment-method.php,
chalearning/woocommerce/myaccount/form-edit-account.php,
chalearning/woocommerce/myaccount/form-edit-address.php,
chalearning/woocommerce/myaccount/form-login.php,
chalearning/woocommerce/myaccount/form-lost-password.php,
chalearning/woocommerce/myaccount/form-reset-password.php,
chalearning/woocommerce/myaccount/lost-password-confirmation.php,
chalearning/woocommerce/myaccount/my-account.php,
chalearning/woocommerce/myaccount/my-address.php,
chalearning/woocommerce/myaccount/my-downloads.php,
chalearning/woocommerce/myaccount/my-orders.php,
chalearning/woocommerce/myaccount/navigation.php,
chalearning/woocommerce/myaccount/orders.php,
chalearning/woocommerce/myaccount/payment-methods.php,
chalearning/woocommerce/myaccount/view-order.php,
chalearning/woocommerce/notices/error.php,
chalearning/woocommerce/notices/notice.php,
chalearning/woocommerce/notices/success.php,
chalearning/woocommerce/order/form-tracking.php,
chalearning/woocommerce/order/order-again.php,
chalearning/woocommerce/order/order-details-customer.php,
chalearning/woocommerce/order/order-details-item.php,
chalearning/woocommerce/order/order-details.php,
chalearning/woocommerce/order/tracking.php,
chalearning/woocommerce/product-searchform.php,
chalearning/woocommerce/single-product/add-to-cart/external.php,
chalearning/woocommerce/single-product/add-to-cart/grouped.php,
chalearning/woocommerce/single-product/add-to-cart/simple.php,
chalearning/woocommerce/single-product/add-to-cart/variable.php,
chalearning/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php,
chalearning/woocommerce/single-product/add-to-cart/variation.php,
chalearning/woocommerce/single-product/meta.php,
chalearning/woocommerce/single-product/photoswipe.php,
chalearning/woocommerce/single-product/price.php,
chalearning/woocommerce/single-product/product-attributes.php,
chalearning/woocommerce/single-product/product-image.php,
chalearning/woocommerce/single-product/product-thumbnails.php,
chalearning/woocommerce/single-product/rating.php,
chalearning/woocommerce/single-product/related.php,
chalearning/woocommerce/single-product/review-meta.php,
chalearning/woocommerce/single-product/review-rating.php,
chalearning/woocommerce/single-product/review.php,
chalearning/woocommerce/single-product/sale-flash.php,
chalearning/woocommerce/single-product/share.php,
chalearning/woocommerce/single-product/short-description.php,
chalearning/woocommerce/single-product/stock.php,
chalearning/woocommerce/single-product/tabs/additional-information.php,
chalearning/woocommerce/single-product/tabs/description.php,
chalearning/woocommerce/single-product/tabs/tabs.php,
chalearning/woocommerce/single-product/title.php,
chalearning/woocommerce/single-product/up-sells.php,
chalearning/woocommerce/single-product-reviews.php,
chalearning/woocommerce/single-product.php,
chalearning/woocommerce/taxonomy-product_cat.php,
chalearning/woocommerce/taxonomy-product_tag.php
Outdated templates: 	  	Learn how to update
Moneris
Environment: 		Production
Tokenization Enabled: 		–
Customer/Order CSV Export
Order Export Format: 		default
Customer Export Format: 		default
Automatically Export Orders: 		disabled
</details>

**Comment by nishitlangaliya** [comment]
@mikejolley 

I have made some adjustment to fix the issue an done the pr https://github.com/woocommerce/woocommerce/pull/15591 please review it and let me know if any changes required.

Thanks
