### ISSUE TITLE
Check Out Form - State drop down field is not accessible

### ISSUE THREAD

**Issue by bobkamp** [woocommerce/woocommerce#15572]
The State drop down field is reading as follows in screen readers:

With JAWS 18: State drop down box is announced as “Edit Combo Collapsed”
With NVDA: State drop down box announced as “Combo Box Collapsed, Editable”.

We need to make that field accessible for the blind and visually-impaired. Is there a way to edit that alt tag or ID, so it states, "State Drop Down Field"?

**Comment by mikejolley** [comment]
Mentioned in https://github.com/woocommerce/woocommerce/issues/14317, but this is a problem in the Select2 library. 

https://github.com/select2/select2/issues/3735

As such this is not fixable from our side without refactoring select2 ourselves. We're considering this but it's not short term nor something we've committed to yet.

**Comment by bobkamp** [comment]
Thanks Mike.
