### ISSUE TITLE
Tax is 0 on cart and on checkout does not include shipping until billing details modified

### ISSUE THREAD

**Issue by Matekk** [woocommerce/woocommerce#15589]
Hi,

Maybe it's down to configuration but I can not solve this issue.
On the cart page the tax is displayed 0 (I have display tax as single total selected, read someplace that is the reason) then on checkout it calculates tax but without shipping costs.

Modifying billing details then recalculates taxes correctly, including shipping costs. (Modifying as in just to fire the recalculation action, entering the same values)

I haven't concluded what causes this, but it seems it's saved in cookie information, as afterwards the tax is always correctly calculated on the checkout page (cart still shows 0).

Please help,
Matt

**Comment by mikejolley** [comment]
This report lacks examples, steps to reproduce, system status report. 

```
BEFORE POSTING YOUR ISSUE
- These comments won't show up when you submit the issue.
- Try to add as much detail as possible. Be specific!
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
- If you're requesting a new feature, explain why you'd like it to be added.
- Search this repository (top of the page) for the issue and it has not been fixed or reported already.

Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
```

If you can tell us how to replicate on a clean install I'll look into this.

**Comment by Matekk** [comment]
Nevermind, I was modifying wc session data which caused the errors, fixed.
