### ISSUE TITLE
Auto-Mail sending not working after Version 3.0.8 upgrade

### ISSUE THREAD

**Issue by jvmauricio** [woocommerce/woocommerce#15582]
### 
Auto-Mail sending not working after Version 3.0.8 upgrade. verified core bug by rolling back version, updating the plugins one-by-one, changing themes and disabling other plugins.

**notes:**

-  Manual triggering of email working.
-  No log of email generated or being sent via WP Mail Log plugin.

### SYSTEM STATUS
`
### WordPress Environment ###

WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Redux Framework: by Team Redux – 3.6.5
Contact Form 7: by Takayuki Miyoshi – 4.8
Meta Slider: by Matcha Labs – 3.5.1
Postman SMTP: by Jason Hendriks – 1.7.2
Printful Integration for WooCommerce: by Printful – 1.2.8
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.2
WooCommerce Quantity Increment: by Automattic
WooThemes – 1.1.0

WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0

WooCommerce: by Automattic – 3.0.8
WordPress phpinfo(): by Chris Flannagan – 16.1
WP Google Maps: by WP Google Maps – 6.4.04
WP Mail Logging: by Christian Zöller – 1.8.1
xclean core: by 8theme – 1.0.1
YITH WooCommerce Zoom Magnifier: by YITHEMES – 1.2.29

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: XClean
Version: 1.0.6
Author URL: http://8theme.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: xclean/woocommerce/archive-product.php
xclean/woocommerce/cart/cart-empty.php
xclean/woocommerce/cart/cart.php
xclean/woocommerce/cart/mini-cart.php
xclean/woocommerce/checkout/form-checkout.php
xclean/woocommerce/content-single-product.php
xclean/woocommerce/content-widget-product.php
xclean/woocommerce/emails/admin-cancelled-order.php
xclean/woocommerce/emails/admin-new-order.php
xclean/woocommerce/emails/customer-completed-order.php
xclean/woocommerce/single-product/product-image.php
xclean/woocommerce/single-product/product-thumbnails.php
xclean/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
This only confirms something is blocking sending i.e. a plugin not compatible with 3.0. The actual method of sending is identical in 3.0 as 2.6.

I'd suggest looking at the server PHP error log and seeing what has been logged there, and/or disabling other plugins to find the source of the conflict.

If you've added any snippets to enable cron based email sending, disable that. 

```
Before logging BUGS, ensure you:
- Use the latest stable release of WooCommerce.
- Disabled all plugins to ensure it's a core bug and not a plugin issue.
- Switched to Twenty Twelve theme to ensure it's a core bug and not a theme issue.
```

Let us know what you find.
