### ISSUE TITLE
Tax Not Updating When States Changed on Checkout

### ISSUE THREAD

**Issue by digamber89** [woocommerce/woocommerce#15583]
### EXPLANATION OF THE ISSUE

Using WordPress 4.7.5 and WooCommerce 3.0.8 we are seeing that tax rates do not change on checkout when state is changed. The tax is only shown when the country field is changed. This is causing tax rates to not show up correctly on checkout.

### STEPS TO REPRODUCE THE ISSUE

You can reproduce the issue using the default twentyseventeen theme and WooCommerce installed.
Input tax rates for 3 states and one for the entire United States. 

Then after purchasing a product the tax is only calculated when you change the country field.

### SYSTEM STATUS

<details>
WordPress environment
Home URL:		http://202.166.207.19/general-woocommerce
Site URL:		http://202.166.207.19/general-woocommerce
WC version:		3.0.8
Log directory writable:		 /home/anamika/public_html/general-woocommerce/wp-content/uploads/wc-logs/
WP version:		4.7.5
WP multisite:		–
WP memory limit:		512 MB
WP debug mode:		
WP cron:		
Language:		en_US
Server environment
Server info:		Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.6.16
PHP version:		5.6.16
PHP post max size:		6 GB
PHP time limit:		600
PHP max input vars:		1000
cURL version:		7.54.0, NSS/3.28.1
SUHOSIN installed:		–
MySQL version:		5.6.36
Max upload size:		5 GB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.8
Database prefix	 	gcomm_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 /home/anamika/public_html/general-woocommerce/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		Error messages should not be shown to visitors.
Active plugins (4)
Woo Preview Emails	 	by Digamber Pradhan – 1.2.7
WooCommerce Stripe Gateway	 	by WooCommerce – 3.1.9
WooCommerce	 	by Automattic – 3.0.8
WordPress Importer	 	by wordpressdotorg – 0.6.3
Settings
API enabled:		
Force SSL:		–
Currency		USD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#27 - /
Cart:		#28 - /cart/
Checkout:		#29 - /checkout/
My account:		#30 - /my-account/
Theme
Name:		Twenty Seventeen
Version:		1.2 – 1.3 is available
Author URL:		https://wordpress.org/
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Overrides:	 	–
</details>

**Comment by shivapoudel** [comment]
Reference video: http://screencast-o-matic.com/watch/cb1I15XPtb

**Comment by mikejolley** [comment]
The state field, and other address fields all have the 'address-field' class. Tax is recalculated when the address fields are all populated. Tax can of course also be based on zip code and city, so it waits for all data before triggering a recalculation.

Country is an exception simply because the entire form can change when this input is updated.
