### ISSUE TITLE
Breadcrumbs within the my account section not correct.

### ISSUE THREAD

**Issue by matthewpaulhaigh** [woocommerce/woocommerce#15593]
### EXPLANATION OF THE ISSUE

The breadcrumbs within the my account section seem to repeat the child page so you end up with:

Home   >   Orders   >   Orders

instead of:

Home   >   My Account   >   Orders

### STEPS TO REPRODUCE THE ISSUE

Use the woocommerce_breadcrumb(); function within your page template.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://sheffield-tooling-company.helium.etchedagency.co.uk
Site URL: http://sheffield-tooling-company.helium.etchedagency.co.uk
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) OpenSSL/1.0.2g
PHP Version: 7.0.20
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.14
WooCommerce Stripe Gateway: by WooCommerce – 3.1.9
WooCommerce: by Automattic – 3.0.8
Yoast SEO: by Team Yoast – 4.9
WP Migrate DB: by Delicious Brains – 0.9.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /browse-by-category/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Sheffield Tooling Company
Version: 1.0
Author URL: http://etchedagency.co.uk
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: sheffield-tooling-company/woocommerce/archive-product.php version - is out of date. The core version is 2.0.0
sheffield-tooling-company/woocommerce/product-searchform.php version - is out of date. The core version is 2.5.0
sheffield-tooling-company/woocommerce/single-product.php version - is out of date. The core version is 1.6.4
sheffield-tooling-company/woocommerce/taxonomy-product_cat.php version - is out of date. The core version is 1.6.4

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
You need to move the tag outside of the LOOP in the page template. Then it will work:

<img width="908" alt="2017-06-13 at 13 37" src="https://user-images.githubusercontent.com/90977/27082688-a594dd30-503d-11e7-9bb9-05ac207527df.png">

**Comment by matthewpaulhaigh** [comment]
Thanks Mike.
