### ISSUE TITLE
Webhooks not triggering on fresh instance.

### ISSUE THREAD

**Issue by hickscorp** [woocommerce/woocommerce#15599]
### EXPLANATION OF THE ISSUE

Using the latest version of wordpress, along with the WooCommerce plugin that can be found on the Wordpress marketplace, we are unable to get the webhooks to actually trigger properly.

### STEPS TO REPRODUCE THE ISSUE

After installing everything, we set up webhooks like this:

![image](https://user-images.githubusercontent.com/822933/27096696-cf04d306-5069-11e7-8e13-15d4f95404c5.png)

Note that the very creation of these hooks triggered the hook on the requestbin itself (incorrect behaviour) but with empty payloads. Is it intended as a "test" feature? If yes, it would be wiser to move it into a "Test Webhook" button, and actually send a test payload.

Then, we created and edited a product: **Nothing got sent to the requestbin**.

### SYSTEM STATUS

```
### WordPress Environment ###

Home URL: http://localhost:8080
Site URL: http://localhost:8080
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 5.6.26
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.56 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /?page_id=4
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My account: #7 - /?page_id=7

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```

**Comment by claudiulodro** [comment]
Is there anything helpful in the webhook logs? Each webhook should have its own log on its 'edit' screen.

**Comment by hickscorp** [comment]
@claudiulodro Thanks for your help,

The webhook log is completelly empty.
I have tried updating a product (By appending characters to its description) but the webhook log still is empty afterward.

**Comment by mikejolley** [comment]
Tried to reproduce on a clean local install.

Settings:

<img width="809" alt="2017-06-14 at 11 33" src="https://user-images.githubusercontent.com/90977/27128142-57e3f680-50f5-11e7-9a83-5c57f06dc80d.png">

I then updated a description. 

Result:

<img width="1500" alt="2017-06-14 at 11 34" src="https://user-images.githubusercontent.com/90977/27128167-6c974c3a-50f5-11e7-82cf-c88da43d8e5f.png">

This appears to be working. I think it's likely that your local server cannot communicate to send the request. I had some issues on localhost before restarting my machine with CURL errors. Maybe check the server logs?

I also tested with master (3.1-beta). Since you're on local host you may want to do the same. 

If you narrow the issue or have steps to reproduce I can try (since the above worked) please reply back.

**Comment by hickscorp** [comment]
@mikejolley I narrowed it...

- I installed the php `curl` module.
- I manually ran the cron jobs.

The webhooks got delivered. I think some documentation about those requirements might help, as the "WooCommerce Status" page was all green...

Thank you!
