### ISSUE TITLE
Enabling COD for Flat Rate also enables it for Flat Rate Box

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#15606]
Originally reported by @conschneider  in Flat Rate Boxes extension. The main question of the issue is:

> Why does setting "Flat Rate" activate both "Flat Rate" and "Flat Rate Box Shipping"?:

<img width="661" alt="woocommerce_settings_ _local_wp_dev_ _wordpress" src="https://user-images.githubusercontent.com/78313/27118002-606d1a26-5103-11e7-80b7-9f4ec3bbebb0.png">

Even if you don't have Flat Rate instance available and only FRB it still makes COD available:

<img width="341" alt="checkout_ _local_wp_dev" src="https://user-images.githubusercontent.com/78313/27118029-8236a5e6-5103-11e7-8589-c76e4ec16f74.png">

The culprit of it is COD checks for enabled payment method by checking [string position](https://github.com/woocommerce/woocommerce/blob/ac4bcf39c2f4c3165c12f5d1c9d22a5e503d885d/includes/gateways/cod/class-wc-gateway-cod.php#L184-L186):

```php
if ( strpos( $check_method, $method_id ) === 0 ) {
	$found = true;
	break;
}
```

Since method ID of FRB is `flat_rate_boxes` it matches the check of `flat_rate`.

**Comment by dixitadusara** [comment]
@gedex 

Let me try to solve this bug.

Thanks,

**Comment by dixitadusara** [comment]
@gedex 

I have done PR #15608 for the same.

Thanks,
Dixita Dusara
