### ISSUE TITLE
Catalog visibility is confusing

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#15604]
Without referencing documentation or looking in the code, this section can be quite confusing especially combined with the WordPress Visibility settings.

![](http://cld.wthms.co/sIKxwb+)

> Choose where this product should be displayed in your catalog.

These settings are more of an "if is should be displayed". I think this wording could use some clarification.

> The product will always be accessible directly.

True for the above 4 settings, but not true if you take the "WordPress Visibility" setting into consideration. I get what it's trying to say, but still think it could use some clarification along with the above sentence.

____

Without looking it up, I had no clue what the difference was between "visible" and "catalog". Maybe it should read more like "Fully Visible" and "Catalog Only"? I'm bad with words, but really think this needs some altering. I believe the first option used to read "Catalog/Search". Not sure why it was originally changed, but using just the "Visible" term is quite confusing given that it is also used in different context right above by WP core.

If possible within WordPress, a lot of this confusion could be solved if we displayed a relevant description about what they have selected using some javascript right below the radio boxes. Then the "featured product" area could be separated with an `<hr>` or something.

Just some food for thought :)

**Comment by WPprodigy** [comment]
Secondary thought. Is "Search-only" even that common? If we could just remove/fade-out that setting, this would all be loads easier. There would be either the option to have the product visible or hidden. How common is it really to have products that you want only available via search?

Maybe we should include something in a survey asking about this, or see if we can pull this down in the tracking. If it's not very common, moving this to a tiny feature plugin could help simplify things for WC's future.

**Comment by mikejolley** [comment]
We can do some copy tweaks but to remind you, UI changes like this are already being looked at in the Calypso designs.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15610

**Comment by WPprodigy** [comment]
That should help quite a bit for now.

Had another secondary thought though. "Search only" may not be used very often, but I really don't think "Catalog only" has a use case. Why would you want something on your shop page that doesn't show up when searching for it? 0.o

Really think there's room for removing some complexity here by just offering 2 or 3 options. ¯\\\_(ツ)\_/¯

**Comment by mikejolley** [comment]
We think the same but that would need to wait for a major.

**Comment by XReploid** [comment]
hi how to remove the catalog visibility from woocommerce? So that by default it only shows in shop and search.

https://snipboard.io/aVU7mJ.jpg

Thanks for all the support in advance
