### ISSUE TITLE
Is MySQL 5.6 required or recommended?

### ISSUE THREAD

**Issue by Zodiac1978** [woocommerce/woocommerce#15609]
### EXPLANATION OF THE ISSUE

Status report is [recommending](https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/de/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=1756300&filters%5Btranslation_id%5D=48609378) MySQL 5.6, but the website says it is a [requirement](https://docs.woocommerce.com/document/server-requirements/).

Readme.txt is recommending 5.6 too, requirement is MySQL 5.0:
https://github.com/woocommerce/woocommerce/blob/818c3df7fbf036b20c6504c7b6ec297b6b722916/readme.txt#L92

### STEPS TO REPRODUCE THE ISSUE

See above.

### SYSTEM STATUS

<details>
```
MySQL Version: 		5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
```
</details>

**Comment by mikejolley** [comment]
It is a requirement, as per https://wordpress.org/about/requirements/
