### ISSUE TITLE
Add street-level store address to settings

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#15602]
### EXPLANATION OF THE ISSUE

Knowing the base location city, state, postcode and country is not enough in many US states to calculate sales taxes properly.  We also need to know the street address of the business. This is known in the tax business as "rooftop accurate" rates. 

How about we expand wp-admin > Settings > General > Base Location but to rename it to Store Address and get Address_1, Address_2, City, State, Postcode and Country there.

<del>Maybe we should also go ahead and add Store Name there too, since it isn't always exactly the same as Site title (wp-admin > Settings > General )</del>

This will probably also be useful for shipping extensions

See also https://github.com/woocommerce/wc-api-dev/issues/12

cc @mikejolley and @jeffstieler

**Comment by mikejolley** [comment]
Not sure we need store name? But I agree with the other points. Should go into the wizard too.

**Comment by allendav** [comment]
> Not sure we need store name?

Yeah, we don't - striking that - we're going to use the WordPress Site Title for that.

> Should go into the wizard too.

I agree!

**Comment by WPprodigy** [comment]
Wanted to note that this can/will have an effect on the Local Pickup shipping method when it comes to taxes being applied.

Should be a positive improvement, but something we need to test and maybe adjust for still.

**Comment by joycegrace** [comment]
Hi, this is somewhat tedious for those of us who don't need street address to calculate taxes. Could this be an optional thing to turn on or off? Or is there some code snippet to turn it off? I don't like making customers enter their entire street address just to see what taxes come to, when they are based on province and product type, in Canada. Thank you.
