### ISSUE TITLE
[3.1.0] The variations are not imported

### ISSUE THREAD

**Issue by Chrystll** [woocommerce/woocommerce#15614]
Storefront 2.2.3
only WooCommerce 3.1.0-beta.2 (master)
WordPress 4.8

To reproduce:
Create a variable product with:
* a global attribute: for example 'Size'
* a term: for example 'XL'
* set a price at the level variation

Export this product: I keep the default options 'Export all columns' and 'Export all products'.

Import the csv file: I do not import the column name ID.

Then edit the just imported product: the variation tab is empty.

**Comment by mikejolley** [comment]
Parent will be set to an ID. This ID will match the old product, not the new product. Old product gets the variation.

**Comment by Chrystll** [comment]
Ok thanks for the explanation. So after creating a SKU parent I was able to import the variations correctly.

**Comment by mikejolley** [comment]
Still needs looking at.
