### ISSUE TITLE
Error - Can't call API in live website

### ISSUE THREAD

**Issue by hikarushin** [woocommerce/woocommerce#15613]
I've received this error in our live server. See attached file:
[error.txt](https://github.com/woocommerce/woocommerce/files/1074156/error.txt)

But in our dev environment. I can access all the API call.

Here's a preview:
```
<!DOCTYPE html>
<!--[if IE 9 ]>
<html lang="es-ES" prefix="og: //ogp.me/ns# fb: //ogp.me/ns/fb#" class="ie9 loading-site no-js">
    <![endif]-->
    <!--[if IE 8 ]>
    <html lang="es-ES" prefix="og: //ogp.me/ns# fb: //ogp.me/ns/fb#" class="ie8 loading-site no-js">
        <![endif]-->
        <!--[if (gte IE 9)|!(IE)]>
        <!-->
        <html lang="es-ES" prefix="og: //ogp.me/ns# fb: //ogp.me/ns/fb#" class="loading-site no-js">
            <!--
            <![endif]-->
```

`
### WordPress Environment ###

Home URL: //www.gretaq.com
Site URL: //www.gretaq.com
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: ✔
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.19-1~dotdeb+8.1
PHP Post Max Size: 100 MB
PHP Time Limit: -1
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 15 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

Contact Form 7: por Takayuki Miyoshi – 4.8
Hello Dolly: por Matt Mullenweg – 1.6
Imagify: por WP Media – 1.6.4
Nextend Facebook Connect: por Nextendweb – 2.0.2
Nextend Google Connect: por Roland Soos
Jamie Bainbridge – 1.6.1

Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 2.2.6
Braintree For WooCommerce Pro: por Payment Plugins
support@paymentplugins.com – 2.6.12

WooCommerce Sequential Order Numbers Pro: por WooThemes / SkyVerge – 1.10.1 – 1.11.2 está disponible
WooCommerce: por Automattic – 3.0.8
WooSidebars: por WooThemes – 1.4.3
Yoast SEO Premium: por Equipo Yoast – 4.9
Yoast SEO: WooCommerce: por Equipo Yoast – 4.6
Remove HTTP: por Fact Maven – 2.1.0
WooCommerce: por Automattic – 3.0.8
AutoChimp: por Wanderer LLC Dev Team – 2.15
BackupBuddy: por iThemes – 7.3.1.0
Braintree For WooCommerce Pro: por Payment Plugins
support@paymentplugins.com – 2.6.12

CC & BCC for Woocommerce Order Emails: por Dario Curasì – 1.4.1
createIT Size Guide Plugin: por createIT – 2.1
MailChimp para WordPress: por ibericode – 4.1.3
Nextend Facebook Connect: por Nextendweb – 2.0.2
Nextend Google Connect: por Roland Soos
Jamie Bainbridge – 1.6.1

WooCommerce Bulk Edit Product Variations: por matterico_themes – 2.6
WooCommerce MailChimp: por Saint Systems – 2.1.0
WooCommerce Product Feed Manager: por Michel Jongbloed – 1.7.4
WooCommerce Sequential Order Numbers Pro: por WooThemes / SkyVerge – 1.10.1 – 1.11.2 está disponible
WooCommerce Shipping Tracking: por Lagudi Domenico – 10.2
WooCommerce Shipping Tracking - Bulk import addon: Import Sequential Order Number Pro: por Lagudi Domenico – 1.0
WooSidebars: por WooThemes – 1.4.3
WP All Export Pro: por Soflyy – 1.4.6
WP All Import - ACF Add-On: por Soflyy – 3.1.4
WP All Import - Link Cloaking Add-on: por Soflyy – 1.1.0
WP All Import - User Import Add-On: por Soflyy – 1.0.9
WP All Import - Yoast WordPress SEO Add-On: por Soflyy – 1.1.5
WP All Import Pro: por Soflyy – 4.4.8
WP Rocket: por WP Media – 2.10.3
WP-Mail-SMTP: por Callum Macdonald – 0.10.1
YITH WooCommerce Name Your Price: por YITHEMES – 1.0.8
Yoast SEO Premium: por Equipo Yoast – 4.9
Yoast SEO: WooCommerce: por Equipo Yoast – 4.6
WooCommerce Conditional Shipping and Payments: por WooThemes – 1.2.5 – 1.2.6 está disponible
WP Force Lowercase URLs: por Josh Buchea – 2.0.1
Post Affiliate Pro: por QualityUnit – 1.10.2
Hide YouTube Related Videos: por SparkWeb Interactive
Inc. – 1.4.2

Woo Search Box: por Guaven Labs – 1.6.5
Google Tag Manager para Wordpress: por Thomas Geiger – 1.6.1
Code Snippets: por Shea Bunge – 2.8.6
Woocommerce All Discounts: por ORION – 1.14
Leadpages Connector: por Leadpages – 2.1.6.7
WooCommerce Extended Coupon Features PRO: por Soft79 – 2.5.0
WP-Lister Pro for Amazon: por Matthias Krok – 0.9.6.36
WP All Import - WooCommerce Add-On Pro: por Soflyy – 2.3.6
Theia Upload Cleaner: por WeCodePixels – 1.3.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base de la tienda: ❌ Página sin definir
Carrito: #124586 - /cart/
Finalizar compra: #124585 - /checkout/
Mi cuenta: #124584 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.5
Parent Theme Author URL: //www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
<img width="1070" alt="2017-06-14 at 13 23" src="https://user-images.githubusercontent.com/90977/27131893-ab9bd1d0-5104-11e7-8d3a-21e00d8de069.png">

**Comment by hikarushin** [comment]
Hi @mikejolley , what would be the cause in my end? I'm using Postman app to access API.

**Comment by hikarushin** [comment]
Okay I get it now. I need to put "www". Thanks.
