### ISSUE TITLE
[3.0.8] Fatal Error with wc_get_customer_available_downloads()

### ISSUE THREAD

**Issue by cdukes** [woocommerce/woocommerce#15617]
$_product->get_file() on wc-user-functions.php:409 can return false (abstract-wc-product.php:1804), but wc_get_customer_available_downloads() assumes it always returns an object, calling $download_file->get_name() on line 439. If $download_file is a boolean instead of an object, you get a fatal error.

I think just checking that $download_file is an object would fix this?

```
$download_file = $_product->get_file( $result->download_id );
if( !is_object($download_file) ) {
	continue;
}
```

**Comment by claudiulodro** [comment]
```
// wc_get_customer_available_downloads line 404-409
if ( ! $_product || ! $_product->exists() || ! $_product->has_file( $result->download_id ) ) {
	continue;
}

$download_file = $_product->get_file( $result->download_id );
```

```
// abstract-wc-product.php line 1585-1587
public function has_file( $download_id = '' ) {
	return $this->is_downloadable() && $this->get_file( $download_id );
}
```

It looks to me like the `has_file` check will catch it every time. Is there something I'm missing?
