### ISSUE TITLE
Rating Filter Widget

### ISSUE THREAD

**Issue by romi-getbowtied** [woocommerce/woocommerce#15624]
Hi,

we use to apply a filter to "wp_list_categories" in order to remove the "(" and ")" from .count

http://screencast.com/t/jcoiwQXN6

We would like to be able to filter also the result of "Rating Filter" widget:

https://github.com/woocommerce/woocommerce/blob/master/includes/widgets/class-wc-widget-rating-filter.php

https://www.screencast.com/t/3MtUO9bgyhv

in order to remove those brackets.

https://www.screencast.com/t/kwubXMKF8qU

Thanks,
Romi.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/15627
