### ISSUE TITLE
Flate Rate zone shipping not applying

### ISSUE THREAD

**Issue by ArtemisHi** [woocommerce/woocommerce#15621]
### EXPLANATION OF THE ISSUE

My flat rate shipping was set for Canada as 0.95*[qty], but I just got an order with a shipping and billing address located in Canada, and WooCommerce charged them the domestic US shipping rate.

I have WooCommerce v4.8

**Comment by mikejolley** [comment]
We will need more information than that. Status report. Screenshot of zones and methods. Can you replicate etc.

**Comment by ArtemisHi** [comment]
OK, could not replicate. Does this mean it's a non-issue?

**Comment by mikejolley** [comment]
Without being able to replicate it would be very hard to say. I also don't know if an extension could affect things. Have you tried as a guest user? Try to replicate as the user best you can - if you are able to do so it will make solving it possible :)

Still this issue lacks basic information we ask for such as the status report.
