### ISSUE TITLE
Product Data Store CPT ignores meta_query arg for get_products()

### ISSUE THREAD

**Issue by NTShop** [woocommerce/woocommerce#15622]
In the file **class-wc-product-data-store-cpt.php** in the **get_products** method the _meta_query_ argument is set to array() completely ignoring any meta_query arg passed into the method either directly or via wc_get_products(). This makes it impossible to query based on a meta data, which results in having to take a different custom approach to querying which in turn increases database queries exponentially (i.e. seriously hampers performance) depending on the use case. Seems to me this was an oversight, and if so can someone correct that please? 
```
$wp_query_args = array(
	'post_type'      => 'variation' === $args['type'] ? 'product_variation' : 'product',
	'post_status'    => $args['status'],
	'posts_per_page' => $args['limit'],
	'meta_query'     => array(),
	'orderby'        => $args['orderby'],
	'order'          => $args['order'],
	'tax_query'      => array(),
);
```

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/13645 but note, we don't have a 1:1 mapping to WP_Query - we want to support core/product props only.
