### ISSUE TITLE
Localize number formats to visitor locale

### ISSUE THREAD

**Issue by Jon007** [woocommerce/woocommerce#15623]
### EXPLANATION OF THE ISSUE

WooCommerce numeric value displays are not readily localizable to user locale.

- WooCommerce, Settings has values for Thousand separator and Decimal separator which only apply to prices.
- for other numeric values WooCommerce uses wc_format_localized_decimal() which uses localeconv() for decimal point instead of wc_get_price_decimal_separator() and has no filter available.  While locale can be changed using setlocale(), as this applies at PHP process level so not ideal for a user level locale.

In both cases this seems opposite to expectation:  a Spanish reader will expect to see 1 million written as 1.000.00,00 regardless of whether it is a currency amount in dollars or Euros, or another type of number.  (actually more confusing for smaller numbers as is easier to misread 1,23 1,233 1.233 1.23)

So is there any alternative solution?
- number formats can't easily follow user locale
- number formats decimal separator and thousands separator may be inconsistent between price fields and non-price fields

For example one solution could be to use 'wc_get_price_decimal_separator' and  'wc_get_price_thousand_separator' in formatting additional numeric fields.  Since these have filters, then any other plugins can also filter to format appropriately and consistently. 

### STEPS TO REPRODUCE THE ISSUE

Install latest Wordpress/WooCommerce version.
Install any user locale switcher and attempt to change locale - Tested with both Polylang translation toole and the simpler locale switcher "JSM's User Locale".

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost:8888/woo3test
Site URL: http://localhost:8888/woo3test
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.0.15 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.0.15
PHP Post Max Size: 32 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

JSM's User Locale: by JS Morisset – 1.2.2
WooCommerce: by Automattic – 3.1.0-alpha

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #34 - /shop/
Basket: #35 - /cart/
Checkout: #36 - /checkout/
My account: #37 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
What is the issue with setlocale? It's per site right?

Using the settings we have is no good; currency can differ from decimal settings.

**Comment by Jon007** [comment]
The front end may be shown in a different language from the site level locale:
 - When using a translation tool such as WPML or Polylang, in this case the site contains content in multiple languages, and specifically translated Product Posts and everything possible is mapped to the user locale.
-  when using other tools such as "JSM's User Locale" cited Wordpress Front End follows user locale setting, at least as far as translation mechanism .po/.mo files etc are concerned.

**Comment by mikejolley** [comment]
Now I'm lost. Currencies already have locale settings. There is nothing to fix or change there.

What decimals are you actually talking about? The only ones I can think of are the weight/dimensions shown on product pages.

**Comment by mikejolley** [comment]
Wait, are you saying you want to adjust the settings based on the actual visitor? Thats way out of scope for this - the store settings should be used, not the visitor. That could quickly get confusing.

**Comment by Jon007** [comment]
Let me try to simplify:

- can we have a filter on `wc_format_localized_decimal()`

When updating a localization plugin such as Hyyan WooCommerce Polylang Integration, we can then make sure the different numbers are localized in the same way in the user locale so it is not confusing to site visitor.

**Comment by mikejolley** [comment]
That was easier :p

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/15628

**Comment by Jon007** [comment]
wow that's fast!  thanks...   ..ok will do PR next time..
