### ISSUE TITLE
Webhook Not Firing Sometimes

### ISSUE THREAD

**Issue by Shotster** [woocommerce/woocommerce#15620]
### EXPLANATION OF THE ISSUE

I'm running WP 4.7.5 and WC 3.0.7 with no caching enabled on a shared hosting platform. I have a single webhook that fires on "Order created", but it's not 100% reliable. Every once in a while, it doesn't get triggered (which is problematic since I have a back-office workflow that depends on it).

A developer in the WP forums was experiencing the same thing and said...

> I debugged this to the point where I see that every now and then the webhook is not added to the table that is read in (and then fired) by the CRON job.

I initially posted this to the WC support site but was told this is the proper place.

### STEPS TO REPRODUCE THE ISSUE

I can't reliably reproduce it. I know that poses a problem for debugging and troubleshooting, but I at least wanted to document the issue.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://powsci.org
Site URL: https://powsci.org
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.14
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 2048
cURL Version: 7.35.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: blog_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Fusion Builder: by ThemeFusion – 1.1.6
Fusion Core: by ThemeFusion – 3.1.6
Google Apps Login: by Dan Lester – 3.0
Imsanity: by Shane Bishop – 2.3.9
Maintenance Mode: by Lukas Juhas – 2.3.1
Post Expirator: by Aaron Axelsen – 2.2.1
Powerhouse Science Center Plugin: by  –
Simple 301 Redirects: by Scott Nellé – 1.07
NextScripts: Social Networks Auto-Poster: by NextScripts – 3.8.5
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.13.4.1

User Role Editor: by Vladimir Garagulya – 4.35
User Switching: by John Blackbourn – 1.0.9
Advanced Order Export For WooCommerce: by AlgolPlus – 1.4.0
WooCommerce Stripe Gateway: by WooCommerce – 3.1.9
WooCommerce Order Status Control: by SkyVerge – 1.8.0
WooCommerce: by Automattic – 3.0.8

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #265 - /store/
Cart: #266 - /cart/
Checkout: #267 - /checkout/
My account: #268 - /account/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.1.6
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada-Child-Theme/woocommerce/cart/cart-empty.php
Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada-Child-Theme/woocommerce/emails/admin-new-order.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

`
</details>

**Comment by mikejolley** [comment]
As pointed out, without steps to reproduce this we won't be able to fix, but I can give you some things to check.

- Each webhook has logs. If the event is logged, it may have additional details e.g. rejected by your endpoint/server.
- Server error logs (PHP) can tell you if there was a problem on your server before the webhook fired.
- Try to establish which type of update didn't fire to help reproduce it. What was being done at the time.
- Did the order get created in the 'correct' way, by the checkout. Or was it an update? Or created via a plugin?

We'll be improving logging with https://github.com/woocommerce/woocommerce/issues/12439

**Comment by Shotster** [comment]
Thanks for the response, @mikejolley. You can keep this issue closed, but I can add a bit more detail to address some of the points you raised...

> Each webhook has logs. If the event is logged, it may have additional details e.g. rejected by your endpoint/server.

The event is not logged in WP. It's as though the webhook http request is never triggered.

> Try to establish which type of update didn't fire to help reproduce it. What was being done at the time.

As stated in my OP, it's the "order created" webhook that's not firing. Order confirmation email is sent just fine, but the webhook is not triggered when the issue occurs. As I said, it fires most of the time, but on occasion, it does not, and I have been unable to discern a correlation with anything else. It seems sporadic and random.

All payments go through the Stripe payment gateway, and I have set up a Stripe webhook which fires 100% of the time. The WC webhook, on the other hand, "skips a beat" every now and then.

> Did the order get created in the 'correct' way, by the checkout. Or was it an update? Or created via a plugin?

The order was created by a customer making a purchase via WC Stripe checkout. FWIW, I am using the WC *Order Status Control* plugin to auto-complete "Virtual Orders". (We are selling class registrations.)

I understand the challenge of troubleshooting this type of issue. If it were triggered by a user interaction, I could surely provide more detail, but it's [supposed to be] an automated WC process, so it seems unreasonable for the onus to be on the end user to provide everything necessary to identify the issue. I'd be happy to provide more detail if/when it becomes available though.

**Comment by mikejolley** [comment]
I wonder if you setup an order.updated webhook too and compare that to your Stripe webhooks if those match up...

Sometimes orders can be resumed.

**Comment by kgatan** [comment]
We have the same issue with missing "order.create". Two orders have been lost and there are no records at all of the specific order in the "order.create" logs.
The order.update is however present and successful as well as the customer create/update hooks.

I'll check the server logs as well and post again if anything useful.

**Comment by crstauf** [comment]
I am experiencing this as well. I have confirmed that several times, altho infrequent, a webhook is scheduled, but is not delivered. Here is a log of the scheduled cron events (`_get_cron_array()`), running in a hook on the `schedule_event` filter, and the new event being added to the logged data manually (since there's no hook after the event is added to the array). Each log entry follows this format:

```
Timestamp INFO current_action() (epoch): Array(
    [webhook name] => Array( [order_id] => scheduled event time ) 
)
```

And here's the log entries of events being scheduled (focus on order 370360):
```
2017-10-23T14:53:08+00:00 INFO woocommerce_webhook_delivery (1508788388): Array
(
    [Order updated] => Array( [370352] => 1508788356 )
)

2017-10-23T14:55:22+00:00 INFO schedule_event (1508788522): Array
(
    [Order created] => Array ( [370360] => 1508788522 )
)

***2017-10-23T14:55:25+00:00 INFO schedule_event (1508788525): Array
(
    [Order created] => Array ( [370360] => 1508788522 )
    [Order updated] => Array( [370360] => 1508788525 )
)***

2017-10-23T14:55:53+00:00 INFO schedule_event (1508788553): Array
(
    [Order created] => Array ( [370361] => 1508788553 )
)
```

The entry wrapped in asterisks indicates that the `order.created` webhook was actually in `_get_cron_array()` (and not added to the array log). Another log shows the webhooks being fired: 

```
2017-10-23T14:53:09+00:00 INFO 370352 - Order updated:
Array
(
    [body] => {}
    [response] => Array
        (
            [code] => 200
            [message] => OK
        )
)

2017-10-23T14:57:29+00:00 INFO 370361 - Order created:
Array
(
    [body] => {}
    [response] => Array
        (
            [code] => 200
            [message] => OK
        )
)

2017-10-23T14:57:30+00:00 INFO 370361 - Order updated:
Array
(
    [body] => {}
    [response] => Array
        (
            [code] => 200
            [message] => OK
        )
)
```

If you cross-reference both logs, you'll notice that events are registered in the following order for orders 370352, 370360, and 370361, but the second log only shows responses for orders 370352 and 370361... 370360 was completely skipped.

In our case, we are using webhooks to grant "points" to our customers for each other they make, and the quickly let us know that they were not _always_ receiving points for their orders.

It is unclear to me if this issue is absolutely founded in WooCommerce, if it's in WordPress, or if it's caused by a host configuration... I am still attempting to track it down, but saw this issue and thought I'd contribute what I've learned.

**Comment by kevin25** [comment]
Any update on this, @crstauf . My shop sometimes doesn't fire and i have many unsynced orders to the external fulfillment.

**Comment by akaspick** [comment]
So far in my usage of the webhooks, I've had to treat create and update webhooks almost the same. So far I've had instances where I've had woocommerce send multiple create hooks for one order, I've had some orders not send any create calls and instead send update hooks.  These instances match up with what I see in the webhook logs and in my own apps logs.

The only issue I've yet to find a solution for is I've had woocommerce call the hook with 0 for the order quantity when in fact woocommerce had it set to 2 in wordpress.  Forcing an update (manually in wordpress) on the order sent another update hook with the correct quantity though. 

The majority of the time, these issues seem to occur when a payment initially fails on an order and then the payment is re-attempted again.  This isn't always the case, but something always seems a bit out of whack for orders that had payment issues.

**Comment by kevin25** [comment]
I realized this happened when I have more than one item in the order. I can't still figure it out why the hook didn't fire then. Is there any workaround?

**Comment by pachalaa** [comment]
Hello,
I have the same problem, sometimes the order update webhook is not firing and I have to manually update the order to make the webhook fire. Once updated, it fires two times. It seams the webhook is stuck somewhere...

**Comment by crstauf** [comment]
Sorry, @kevin25, just now saw that you had addressed me. And no, I've not made any significant progress. Setting the webhooks to not fire async (accessed via a filter) seems to have made it more reliable, but that's definitely less desirable.

**Comment by claudiosanches** [comment]
@crstauf there is filters now on 3.3 that allows you to use any queue software that you want.
