### ISSUE TITLE
Meta values that are arrays/object (after being unserialised) and being cast into string

### ISSUE THREAD

**Issue by Abbid** [woocommerce/woocommerce#15635]
In class-wc-order-item.php, when the meta data is fetched (using get_meta_data()) the values that are serialised and unserialised.

These values are then cast into a string on line 195 in the method get_formatted_meta_data() however this is throwing a Array to string conversion notice.

There is a check on line 190 to see if the value is serialised and to skip if it is, but because the values is unserialised in get_mata_data() this will never equal true.

Any ideas? If there an error in the logic here?

**Comment by mikejolley** [comment]
What meta data? Perhaps you can give examples, especially if this is custom data you've set?

**Comment by Abbid** [comment]
Yes it's custom meta data. 
It's saved in the order meta data table as a serialised array. 

When the class gets the values of the meta data is unserialises It and the casts it into a string as mentioned.

**Comment by mikejolley** [comment]
Clearly not on latest version in that case: https://github.com/woocommerce/woocommerce/blob/3.0.8/includes/class-wc-order-item.php#L195

There is an is_scaler check - serialised data is skipped.
