### ISSUE TITLE
Total Price Round Up after Place order

### ISSUE THREAD

**Issue by emreaky** [woocommerce/woocommerce#15630]
Hello,
İ use 3.2.0. İ have an issue with total price after place order. My currency options are like below and i dont use any taxes.
![image](https://user-images.githubusercontent.com/12774405/27181712-66b9d4d0-51e1-11e7-8d8c-4e68c5a9a273.png)

Before place order everything is ok and total price is correct (26,90) bu after i click on place order button, total price round up (27,00).

![image](https://user-images.githubusercontent.com/12774405/27181722-75217122-51e1-11e7-88e9-403033153c06.png)

After Place Order

![image](https://user-images.githubusercontent.com/12774405/27181734-7db51424-51e1-11e7-86bb-8df8ea7ec731.png)

![image](https://user-images.githubusercontent.com/12774405/27181745-84b38882-51e1-11e7-8646-650021222c04.png)

**Comment by mikejolley** [comment]
System status report? Also, 3.2 does not exist.

**Comment by mikejolley** [comment]
@emreaky This needs more details and the status report, and confirmation it happens with no extensions and the stable version of WooCommerce (3.0.8). Without that we cannot confirm a bug - it works our side and has no other reports.
