### ISSUE TITLE
State/Country Dropdowns do not work on Checkout Field

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#15634]
### EXPLANATION OF THE ISSUE

When using WooCommerce 3.x (tested in 3.0.8), checkout dropdown fields don't work as they used to in 2.6.14. The country or state dropdown, when _tabbed_ into, does not load, though clicking and then typing works.

### STEPS TO REPRODUCE THE ISSUE

1. In an incognito window, go to [this product on my staging site](https://wpsantoro.mystagingwebsite.com/product/a-book-about-things-digital-download/).
2. Add it to your cart, then go to Checkout (without entering address or shipping anything on the cart if it appears - it's a digital item, anyway).
3. When entering the Billing Details, use **Tab** to go between fields. When you get to the country field, it won't allow you to start typing unless you click on that box, whereas it would in 2.6.14.

### SYSTEM STATUS

Pressable install of a WC 3.0.8, WP 4.8, Storefront 2.2.3

-----

590596-zd-woothemes

**Comment by mikejolley** [comment]
This is a Select2 issue so we cannot change this one directly (we're going to work on a custom version soon but not in the next release, cc @claudiulodro). 

But I will just add, even though this does not match select2 v3, it DOES match native select inputs. You have to hit enter to open the options - you cannot just type. Clicking is not required. 

Found this issue: https://github.com/select2/select2/issues/3279

**Comment by nburch** [comment]
@mikejolley I am confused by your response. You are referenced a GitHub issue from 2015 - This behavior/issue was not present in Woocommerce until 3.X - In previous version you could tab to the state dropdown and enter letters to search.

**Comment by claudiulodro** [comment]
@nburch 
WooCommerce 3.0+ uses select2 v4 for the dropdowns. 
WooCommerce 2.* used select2 v3. 
select2 v4 does not have the "tab then type" feature. 

WooCommerce 3.2+ is going to be using a custom version of select2 that fixes the bug.

**Comment by nburch** [comment]
@claudiulodro Oh OK! That makes sense. Thanks for clarification!

**Comment by chriseckman** [comment]
Is there a fix for this yet? It seems like it's only on logged out users.
