### ISSUE TITLE
Recalculate button not working properly for calculating including taxes

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [woocommerce/woocommerce#15637]
### EXPLANATION OF THE ISSUE

After you click on recalculate button, the price of including taxes(18%) is not getting calculated properly

### STEPS TO REPRODUCE THE ISSUE

1. Setup inclusive taxes on **woocommerce > settings > tax**, making sure calculate tax based on **shop base address** is selected
![admin-page](https://user-images.githubusercontent.com/8193404/27194149-e63b973e-51d7-11e7-925a-c436a79e8efb.png)

2. Create a tax of 18%
![admin-page-tax](https://user-images.githubusercontent.com/8193404/27194210-2105a86e-51d8-11e7-9d5c-29bc31dcf981.png)

3. Create a product of $250,00 and buy it

4. Go to this order edit page on admin
At first, the tax price is OK: $ 38,14
![price-ok](https://user-images.githubusercontent.com/8193404/27194283-63889a7a-51d8-11e7-9212-6613c24168ff.png)

5. After you click on **recalculate button**
Tax price is calculated wrong
![price-wrong](https://user-images.githubusercontent.com/8193404/27194299-6cc386ae-51d8-11e7-97b9-d5fe88308dc2.png)

### SYSTEM STATUS

<details>
```
Home URL:		http://127.0.0.1/wp-tests
Site URL:		http://127.0.0.1/wp-tests
WC version:		3.0.8
Log directory writable:		 C:\xampp\htdocs\wp-tests/wp-content/uploads/wc-logs/
WP version:		4.7.5
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		
WP cron:		
Language:		en_US
Server environment
Server info:		Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.0.15
PHP version:		7.0.15
PHP post max size:		8 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.51.0, OpenSSL/1.0.2j
SUHOSIN installed:		–
Max upload size:		2 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		 Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.8
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 C:\xampp\htdocs\wp-tests/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (12)
Multi Order for WooCommerce	 	by Algoritmika Ltd – 1.0.0
Color or Image Variation Swatches for WooCommerce Pro	 	by Algoritmika Ltd – 1.0.0
Wish List for WooCommerce Pro	 	by Algoritmika Ltd – 1.2.7
Debug Bar Extender	 	by Thorsten Ott, Automattic – 0.5
Debug Bar	 	by wordpressdotorg – 0.9
File Renaming on upload	 	by Pablo S G Pacheco – 2.1.4
User Role Editor	 	by Vladimir Garagulya – 4.32.3
Booster Plus for WooCommerce	 	by Algoritmika Ltd – 1.1.0
Booster for WooCommerce	 	by Algoritmika Ltd – 2.8.2
WooCommerce	 	by Automattic – 3.0.8
WordPress Importer	 	by wordpressdotorg – 0.6.3
YITH WooCommerce Customize My Account Page	 	by YITHEMES – 2.1.0
Settings
API enabled:		
Force SSL:		–
Currency		USD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#10 - /shop/
Cart:		#11 - /cart/
Checkout:		#12 - /checkout/
My account:		#13 - /my-account/
Theme
Name:		Themify Corporate
Version:		1.5.7
Author URL:		http://www.themify.me
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Overrides	 	themify-corporate/woocommerce/emails\email-footer.php, 
themify-corporate/woocommerce/emails\email-header.php

```
</details>

**Comment by kaonur** [comment]
I'm suffet that this issue.

Thank you Pablo!

I beleive, woocommerce developer team will fix this issue.

**Comment by mikejolley** [comment]
When the values are stored you lack the precision in order to get the same value back again when using tax inclusive prices. e.g. for a 20% tax rate and 9.99 cost inclusive of VAT:

```
(9.99 / 1.2) = 8.325
```

If `8.325` is stored as `8.32`:

```
8.32 * 1.2 = 9.98
```

If stored as `8.325` you run into similar problems when rounding the tax amounts. Usually you end up with either 10 total, or 9.98 total. Increased quantities also affect this.

Hope this makes sense. When dealing with tax inclusive prices these need to be adjusted manually.

To help us work on the above rounding scenarios you should follow https://github.com/woocommerce/woocommerce/pull/14475 where we're trying to come up with a solution which satisfies most scenarios, but tbh if you want to avoid the problem, use tax exclusive prices.
