### ISSUE TITLE
WC CLI Order Creation no longer allows a customer_id parameter

### ISSUE THREAD

**Issue by JustinSainton** [woocommerce/woocommerce#15639]
### EXPLANATION OF THE ISSUE

With latest WooCommerce (3.0.8), creating orders with a customer_id parameter fails, e.g. 

`wp wc shop_order create --customer_id=1 --status=pending --payment_method=wp-cli --payment_method_title=WP-CLI --set_paid=1` does not work.  Seems to affect both the `update` and `create` commands.

<img width="577" alt="screen shot 2017-06-15 at 10 49 48 am" src="https://user-images.githubusercontent.com/1168754/27195344-3785f944-51bb-11e7-84fb-89d14259d17c.png">

As you can see in this screenshot, the `help` flag does not seem to indicate `customer_id` is a known argument, while the [documentation does](https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Commands#wc-shop_order-create).

### STEPS TO REPRODUCE THE ISSUE

Log into Terminal, SSH into a WC installation, try above command. Output shows the following error:
```
Error: Parameter errors:
 unknown --customer_id parameter
```

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: http://elearning.dev
Site URL: http://elearning.dev
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.8

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
@justinshreve Bit stuck on this one. It seems to be because `customer_id` is defined in  `$supported_ids`. Any ideas?
