### ISSUE TITLE
Order is not really in order

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#15647]
My order numbers are not in order. Please check the attachment.
It went from 25k to 70k another day. 

![screen shot 2017-06-16 at 3 37 05 am](https://user-images.githubusercontent.com/2909982/27216845-5e8c592c-5245-11e7-895d-a4f196901607.png)

> `
### WordPress Environment ###

Home URL: https://www.domain.com
Site URL: https://www.domain.com
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.12.0
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.38.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: ag_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

AliDropship Woo Plugin: by Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin – 0.6
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.44
Contact Form 7: by Takayuki Miyoshi – 4.8
Google Authenticator: by Henrik Schack – 0.48
Just In Time Sales Offers Premium: by Rymera Web Co – 1.3.2
Just In Time Sales Offers: by Rymera Web Co – 1.2.7
MailChimp for WooCommerce: by MailChimp – 2.0.0
McAfee SECURE: by McAfeeSECURE – 1.7.5
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

PixelYourSite PRO: by PixelYourSite – 6.1.2
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.2.0
Recover Abandoned Cart: by Fantastic Plugins – 16.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SEO Optimized Images Business With WooCommerce: by priyanshu.mittal – 1.5.2
WooCommerce Advanced Shipping - Advanced Pricing: by Jeroen Sormani – 2.1.1
WooCommerce Advanced Shipping: by Jeroen Sormani – 1.0.13
WooSwatches - Woocommerce Color or Image Variation Swatches: by woomatrix – 2.3.9
WooCommerce Stripe Gateway: by WooCommerce – 3.1.9
WooCommerce: by Automattic – 3.0.8
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 4.7
WP Rocket: by WP Media – 2.10.3
Yoast SEO: WooCommerce: by Team Yoast – 4.6
YITH Product Size Charts for WooCommerce Premium: by YITHEMES – 1.1.0
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.5
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
Order (post ids) are not sequential. Plenty of resources on the web about this. https://www.speakinginbytes.com/2014/07/woocommerce-order-numbers-order/

**Comment by kevin25** [comment]
@mikejolley I've been using WooCommerce for years and I've never seen this issue before. But 3.x has such issue.

**Comment by mikejolley** [comment]
Nope it's been like this since day 1.

**Comment by mikejolley** [comment]
In which case you may want to look at what posts/content were made to fill the DB and increase those ids :)

**Comment by kevin25** [comment]
I only post some content. I don't think order ID shares with Post ID. And I couldn't go from 25k up to 7k in one day.

**Comment by mikejolley** [comment]
Look at the wp_posts table then.
