### ISSUE TITLE
How to access customers after specified modified date?

### ISSUE THREAD

**Issue by sagaraloha** [woocommerce/woocommerce#15646]
### EXPLANATION OF THE ISSUE

I am using WooCommerce version: 3.0.8
Wordpress version: 4.8

I want to fetch the customers which are updated after the particular date.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
This is not supported in the API - available args are https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-customers

You'll need to extend the API or make a custom endpoint to do this.

If this is not for the API but PHP, use https://codex.wordpress.org/Function_Reference/get_users

**Comment by sagaraloha** [comment]
How can I extend API for the same?

I am following this: 'https://github.com/XiaoFaye/WooCommerce.NET' to use woocommerce API's in .net application.
