### ISSUE TITLE
Add option to turn off term counts for WC Layered Nav widget

### ISSUE THREAD

**Issue by jkohlbach** [woocommerce/woocommerce#15643]
### EXPLANATION OF THE ISSUE

On stores with a LOT of attribute terms, the query that is generated by the WC Layered Nav Widget is incredibly inefficient (it basically dumps an array of all terms and does several joins).

If you then try to filter this query to add in your own conditions (like to filter out certain products for example), it adds to what is already an inefficient query making things 10x worse.

The interesting thing is this query is based on the number of terms available to be filtered for that page. If that N number is something high (like 50, or 100, or 1000) it will still dutifully run this inefficient query for as many terms as it finds.

Additionally, this query is literally only used to get the count of products for that term. So it seems like its just cosmetic.

If we can't fix the query to be more efficient then I suggest we at least add a toggle switch on the widget to turn OFF the counts so that the query is not run. This would be especially handy for installs with lots of terms.

### STEPS TO REPRODUCE THE ISSUE

1. Setup an attribute with tons of terms on your store
2. Add the WC Layered Nav widget to the sidebar
3. Visit the store page and marvel at how many queries are now being run just to get counts of products

### SYSTEM STATUS

WC 3.0.8
PHP 7.0
MySQL 5.6

**Comment by jkohlbach** [comment]
On closer inspection, this count is also being used to check if the term should show or not.

`// Only show options with count > 0
if ( 0 < $count ) {
	$found = true;
} elseif ( 0 === $count && ! $option_is_set ) {
	continue;
}`

**Comment by mikejolley** [comment]
Counts are relative to the current view. I don't see a way of improving this short of dropping the feature.

**Comment by jkohlbach** [comment]
Could we have a toggle to turn off the count feature (and therefore the query)?

The impact would be if it is off:

1. We then don't hide non-empty terms
2. We don't show count values when showing the list

This would be hugely beneficial for people who are altering the main query especially like our plugin (and many others do as well).

Specifically in our case it filters the product lists all throughout WC to alter the visibility of certain products. Its a feature in our wholesale pricing module. Currently because we filter pre_get_posts it adversely affects this query because it adds another INNER JOIN to the postmeta table. That basically kills it.

If there was a toggle to turn off the counts, this kind of thing would be a non-issue.

Aside from my personal woes, for sites that have attributes with hundreds of terms (one of our customers has this exact scenario) it means this query is basically dumping a huge list of term ids into the query all just to find counts. It's an expensive operation for the benefit it provides and this widget shows on pages that are already sensitive to load time (like the shop archive).

It just seems like there might be a better way.

Let me know what you think @mikejolley

**Comment by mikejolley** [comment]
Counts/hiding non-relevant terms are pretty fundamental to this widget. Showing non-relevant terms is not user friendly. If you want that, just output a list of terms in a separate widget and link to archives..

**Comment by mikejolley** [comment]
Let's see what else we can do in https://github.com/woocommerce/woocommerce/pull/15658 - please reply there.

We need to keep these counts around because it reduces the terms displayed based on the current query.

Example; say you have color based terms and narrow the results to 'blue'. The other displayed terms should only be those relevent to 'blue' too - we do this with counts.
