### ISSUE TITLE
Ending of Website-Link

### ISSUE THREAD

**Issue by sebo3000** [woocommerce/woocommerce#15649]
### EXPLANATION OF THE ISSUE

When loading my website (http://brufuture.com/) a not defined combination of letters and numbers pops up as ending of my website link: http://brufuture.com/?v=3a52f3c22ed6. How can i get rid of this ending (?v=3a52f3c22ed6) ? Thank you

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Change 'default customer address' in settings to anything except 'geolocation with page caching support'.
