### ISSUE TITLE
Can add a new product

### ISSUE THREAD

**Issue by ascend2glory** [woocommerce/woocommerce#15644]
### EXPLANATION OF THE ISSUE

When I try to add a product, I get this type of error
![woocommerce add product error](https://user-images.githubusercontent.com/29472212/27209818-c1254cba-5213-11e7-992a-b3fcb3c2a5d9.JPG)

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
See https://docs.woocommerce.com/document/increasing-the-wordpress-memory-limit/
