### ISSUE TITLE
Wrong Mobile display

### ISSUE THREAD

**Issue by sebo3000** [woocommerce/woocommerce#15650]
### EXPLANATION OF THE ISSUE

When displaying the mobile version, a big black section pops up right of the actual website. I would like to get rid of that. Attached you see the problem.
![img_0990](https://user-images.githubusercontent.com/29478970/27222033-0d2ff958-528b-11e7-89a2-7349287d56d4.PNG)

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
This is controlled by the theme, not WooCommerce itself.
