### ISSUE TITLE
Hitting enter when cart line item quantity is 0 bypasses ajax and forces user to reload page.

### ISSUE THREAD

**Issue by admah** [woocommerce/woocommerce#15666]
### EXPLANATION OF THE ISSUE

Using WC 3.0.6, if a user updates the cart line item quantity to 0 and presses the enter button, the cart disappears, leaving them in some limbo state. They have to reload the page to see the cart with the item removed.

### STEPS TO REPRODUCE THE ISSUE

1. Add item to cart.
2. Navigate to cart and set quantity to 0
3. Hit enter on your keyboard.

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: Private
Site URL: Private
WC Version: 3.0.6
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/7.0.18 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version: 7.0.18
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.6
WC Database Prefix: wvus_woo_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (35) ###

Mailgun: by Mailgun – 1.5.8.2
SEO Redirection Premium: by Fakhri Alsadi – 2.8
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.1
WVUS Add to Cart: by World Vision US – 1.0
WVUS Cart Clear: by World Vision US – 1.0
WVUS Sponsorship: by World Vision US – 1.0
WVUS Product: by World Vision US – 1.0
WVUS Donate: by World Vision US – 1.0
WVUS Google Tag Manager: by World Vision US – 1.1
WVUS Orders: by World Vision US – 1.0
WVUS Payment Gateways: by World Vision US – 1.0
WVUS Product Meta: by World Vision US – 1.0.0
WVUS Password Reset: by World Vision US – 1.0.0
WVUS Session: by World Vision US – 1.0.0
YITH WooCommerce Name Your Price Premium: by YITHEMES – 1.0.14
Autoptimize: by Frank Goossens (futtta) – 2.1.0
Imsanity: by Shane Bishop – 2.3.8
Vulnerability Alerts: by Edir Pedro – 1.3.1
Widget Shortcode: by Hassan Derakhshandeh – 0.3.0
WooCommerce Show Attributes: by Isabel Castillo – 1.6.2
WP Smush: by WPMU DEV – 2.6.1
WVUS EdgeCast: by World Vision US – 1.0.0
WVUS Environment: by World Vision US – 1.0
WVUS Global Header Footer Consumer: by World Vision US – 1.0.0
Yoast SEO: by Team Yoast – 4.5
Native PHP Sessions for WordPress: by Pantheon – 0.6.0
Activity Log: by Yakir Sitbon
Maor Chasen
Ariel Klikstein – 2.3.4

YITH WooCommerce Name Your Price Premium: by YITHEMES – 1.0.14
Advanced Custom Fields PRO: by Elliot Condon – 5.5.10
SEO Redirection Premium: by Fakhri Alsadi – 2.8
WooCommerce: by Automattic – 3.0.6 – 3.0.8 is available
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.2.1
WVUS Api Integrations: by World Vision US – 1.0.0
WVUS Logger: by World Vision US – 1.0.0
WVUS Session: by World Vision US – 1.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop
Cart: #5 - /cart
Checkout: #6 - /checkout
My account: #7 - /my-account

### Theme ###

Name: 
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: 
Parent Theme Version: – 0 is available
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: wvecomm/woocommerce/cart/cart.php
wvecomm/woocommerce/cart/proceed-to-checkout-button.php
wvecomm/woocommerce/checkout/form-billing.php
wvecomm/woocommerce/checkout/form-checkout.php
wvecomm/woocommerce/content-single-product.php
wvecomm/woocommerce/single-product/add-to-cart/simple.php
wvecomm/woocommerce/single-product/meta.php
wvecomm/woocommerce/single-product/photoswipe.php
wvecomm/woocommerce/single-product/price.php
wvecomm/woocommerce/single-product/product-attributes.php
wvecomm/woocommerce/single-product/product-image.php
wvecomm/woocommerce/single-product/product-thumbnails.php
wvecomm/woocommerce/single-product/related.php
wvecomm/woocommerce/single-product/share.php
wvecomm/woocommerce/single-product/short-description.php
wvecomm/woocommerce/single-product/stock.php
wvecomm/woocommerce/single-product/tabs/additional-information.php
wvecomm/woocommerce/single-product/tabs/description.php
wvecomm/woocommerce/single-product/tabs/tabs.php
wvecomm/woocommerce/single-product/title.php
wvecomm/woocommerce/single-product/up-sells.php
wvecomm/woocommerce/single-product.php

`
</details>

**Comment by claudiulodro** [comment]
I haven't been able to reproduce this on WC 3.0.8. There's a few things you should try to pinpoint the problem:

1. Upgrade to WC 3.0.8 and see if the problem persists. WC 3.0.7 and WC 3.0.8 have many bug fixes in them and have no changes that will break existing code.
2. Try the WordPress twenty-twelve theme and see if the problem persists. If it doesn't happen on that theme it's an issue in your current theme.
3. Deactivate your other plugins and see if the problem persists. The problem could be caused by any of your WooCommerce plugin extensions, especially some of the ones I see in the status report that do stuff with the cart.

**Comment by admah** [comment]
Thank you!
