### ISSUE TITLE
After upgrading from WC 3.0.3. to 3.0.8 not receiving Order status changed from Pending payment to Processing intermittently

### ISSUE THREAD

**Issue by jbrenner99** [woocommerce/woocommerce#15664]
### EXPLANATION OF THE ISSUE
Upgraded database and from version WC 3.0.3 to WC 3.0.8.  Use PayPal for payments and have both IPN and PDT set-up.  Since upgrading, on some orders we see an IPN or a PDT in Order Notes but never see "Order status changed from Pending Payment to Processing".  This is happening randomly.  When this occurs, the customer does not get a receipt email and we do not get a new order notification.  I think I have ruled out it being an email problem.  We use WP-Mail-SMPT to send out emails.  Installed WP-Mail-Logging.  When we have a problem order, there is no entry in the log.  When an order contains the Order status changed from Pending Payment to Processing, the emails are sent and logged.  It seems something is preventing it from even reaching the email stage.  On the problem orders if I manually resend the Processing order, the email goes out and is logged.

Since upgrading, cancelled orders once they reach their time limit never send an email but I see no difference in the order notes from prior to the upgrade and now after the upgrade.  Both scenarios have a Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled so I am perplexed on those.

### STEPS TO REPRODUCE THE ISSUE

Orders that are placed and paid for seem to have the problem randomly so difficult to reproduce. 

Canceling an order and waiting for the expiration time limit results in no email notification to be sent so this can easily be reproduced.
### SYSTEM STATUS

<details>
### WordPress Environment ###

Home URL: https://kappapuzzles.com
Site URL: https://kappapuzzles.com
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_1mcgxq2kjc_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

HTML in Category Descriptions: by Arno Esterhuizen – 1.2.1.1
Beaver Builder Plugin (Lite Version): by The Beaver Builder Team – 1.10.5.1
Contact Form 7 Conditional Fields: by Jules Colle – 1.3.4
Contact Form 7: by Takayuki Miyoshi – 4.8
Contact Widgets: by GoDaddy – 1.4.1
Easy Google Fonts: by Titanium Themes – 1.4.3
GoDaddy Email Marketing: by GoDaddy – 1.2.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
iframe: by webvitaly – 4.3
Insert PHP: by Will Bontrager Software
LLC  – 1.3

Menu Image: by Alex Davyskiba aka Zviryatko – 2.7.0
WooCommerce Order Export and More: by JEM Plugins – 1.3.2
Post Expirator: by Aaron Axelsen – 2.2.1
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Responsive Image Maps: by Philip Newcomer – 1.4
Storefront Product Pagination: by WooThemes – 1.2.1
Storefront Product Sharing: by WooThemes – 1.0.3
Storefront Sticky Add to Cart: by WooThemes – 1.1.6
WooCommerce Print Invoice & Delivery Note: by Triggvy Gunderson – 4.1.5
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.6.0

WooCommerce Remove Product Sorting: by SkyVerge – 1.0.0
WooCommerce Shortcodes: by WooThemes
Claudio Sanches – 1.0.0

WooCommerce: by Automattic – 3.0.8
Crossword Compiler Puzzles: by WordWeb Software – 11.0
WP Mail Logging: by Christian Zöller – 1.8.1
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP Rollback: by WordImpress – 1.4
WP101 Video Tutorials: by WP101Plugin.com – 0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: ❌ Page visibility should be public

### Theme ###

Name: Merlin Child Theme
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Merlin
Parent Theme Version: 1.2.3
Parent Theme Author URL: https://themezee.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`</details>

**Comment by mikejolley** [comment]
>  It seems something is preventing it from even reaching the email stage.  

I think this is the case and the only real way for you to know is to look at the PHP error log on your server and scout for 'fatal' errors.

It could be something email related. I notice "WooCommerce Print Invoice & Delivery Note" is installed which does stuff to emails, and has also ceased development. This may be a good place to start. Or it could be memory related.

Ultimately the logs should give you the information you are after. I'd expect all orders to be affected, and other users, if this were a core bug in 3.0.8. I cannot spot anything obvious and it appears to be working as intended here.

**Comment by jbrenner99** [comment]
We are seeing the following PHP errors
Jun 19, 17:38:37

PHP Fatal error: Call to undefined method APCu_Object_Cache::incr2() in /home/content/a2pewpnas01_data03/35/3702635/html/wp-content/object-cache.php on line 242

[object-cache.zip](https://github.com/woocommerce/woocommerce/files/1086001/object-cache.zip)

Jun 19, 17:38:25

PHP Fatal error: Call to undefined method APCu_Object_Cache::incr2() in /home/content/a2pewpnas01_data03/35/3702635/html/wp-content/object-cache.php on line 242

I attached object-cache.php in a zip file.  Any insight you can supply would be appreciated.

**Comment by mikejolley** [comment]
Looks like it's from https://en-gb.wordpress.org/plugins/apcu/

**Comment by bretweinraub** [comment]
I have all the symptoms minus the fatal errors.... :(

**Comment by scotthopkins** [comment]
We disabled PDT... only IPN is needed

**Comment by jbrenner99** [comment]
As a further update we continue to have the issue since the upgrade from 3.04 to 3.08.  The fatal PHP cache errors were happening at times unrelated to when the orders were attempting to complete.  We have been reluctant to disable PDT since we do sell downloadable products in addition to real products and want our users to see the links upon completion.  Order Status always changes to Processing for non-downloadable products and Completed for downloadable products.  But, sporadically we continue to have some orders that never get an "Order status changed from Pending Payment to Processing" in the Order notes even though the Order Status is Processing. What's interesting is that when it "works", we only see an "Order status changed from Pending Payment to Processing" in the Order notes and a PDT completed.  When it doesn't work we only see an "IPN payment completed" in the Order notes and thus no email gets sent to us or the customer.  We then have to manually resend the Order Processing email to the customer in order for them to get their receipt.  The problem occurs sporadically and appears to be random.  I can have 10 orders that process properly and then I can have 3 in a row that don't.

It's been frustrating.  I've seen other users complain about duplicate orders and emails being sent and in 3.2 it looks like there will be code implemented to using a locking mechanism as PayPal orders are processing.  My hope is that the 3.2 change may also help the problem we have been experiencing.

**Comment by bretweinraub** [comment]
Ours is similar, it's the WC hooks that don't fire [like that order status has changed, or payment is completed].

Just guessing here, any chance that PayPal drops the connection and there's something in the PHP code that makes it exit?   For example, writing a byte to an open connection?

https://stackoverflow.com/questions/11360274/can-closing-the-browser-terminate-the-php-script-on-the-server

Since we don't get a Fatal error stack trace, it sure seems like the request is exiting prematurely and just thinking why that would happen.

**Comment by studentco** [comment]
@jbrenner99 ,
had same issue(when using paypal for payments, emails were not sent), renamed object-cache.php to object-cache-disabled.php and this fixed the issue - emails are sent normally

**Comment by jbrenner99** [comment]
@studentco,
Thank you! That seems to have fixed the problem.  We were seeing the Object_cache errors but the time stamps didn't always seem to correlate with our problem orders.  But after renaming the object-cache.php to object-cache-disabled.php, orders that only receive an IPN now successfully have an order note that says "Order status changed from Pending Payment to Processing" so the emails are being sent.

**Comment by bretweinraub** [comment]
Eventually, I had to conclude that the callback from PayPal was dying, although contrary to other comments, the error logs never included an error message.   PHP simply exited silently [PHP 7.0].   We had to put in a manual error_log() statement before and after every single line of our code.   Then we found the last line executed, repaired it, and it all works like it used to.
