### ISSUE TITLE
Product CSV Exporter tax_class Field Mapping

### ISSUE THREAD

**Issue by vendidero** [woocommerce/woocommerce#15663]
### EXPLANATION OF THE ISSUE

When exporting data through the Product CSV Exporter (3.1) the product `tax_status` gets exported as `tax_class` which becomes problematic as soon as you import the exported data (product `tax_class` is overridden by the `tax_status` e.g. taxable). The issue lies within `WC_Product_CSV_Exporter::get_default_column_names`: 

`'tax_status'         => __( 'Tax class', 'woocommerce' ),`

which should be:

`'tax_status'         => __( 'Tax status', 'woocommerce' ),`

in fact the actual `tax_class` is missing as a field within `get_default_column_names` so we should consider adding it (because the importer is capable of importing the field).

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15686
