### ISSUE TITLE
RFE: Possibility of line-item tax exemptions, required to sell to UK VAT law for disabled/older people

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#15668]
### EXPLANATION OF THE ISSUE

Currently in WooCommerce, tax exemption is a property of the customer, which then becomes a property of the order. Line item exemptions aren't possible. Tax calculation functions deal with (and hence can pass on to filters) only information about item pricing, not about the item itself (e.g. tax class, product category), and hence extensions cannot exempt on a line item basis.

This, unfortunately, makes it impossible to have a shop which can sell to users who, under UK law, are eligible to VAT exemptions on certain products, but not on others. (Without ugly/cumbersome solutions such as forbidding them to add goods of one kind to their cart if they already have goods of another kind there - and requesting information on their eligibility at the cart, prior to the checkout).
More info: https://www.gov.uk/government/publications/vat-notice-7017-vat-reliefs-for-disabled-people/vat-notice-7017-vat-reliefs-for-disabled-and-older-people

### PROPOSAL

Re-factor the tax calculation code in WC, so that when calculating tax on a line-item, the product that the line-item is for is passed down the chain, and eventually is available to relevant filters that can over-ride line-item tax calculations, so that it can be taken into account.

**Comment by mikejolley** [comment]
We have a disability VAT extension which I think manages. Do it by using:

`woocommerce_product_get_tax_class`
`woocommerce_product_variation_get_tax_class`

If the product is valid for exemption, as well as the customer, return a zero rate tax class instead of the standard tax class. This will remove the taxes as needed.
