### ISSUE TITLE
Unable to Place Orders: State and Country dropdowns missing

### ISSUE THREAD

**Issue by jtdaugh** [woocommerce/woocommerce#15665]
### EXPLANATION OF THE ISSUE

The dropdowns for State and Country on the Billing Address section are missing. The "State" and "Country" titles show up but there is no way to choose. 

Attached a Screenshot 
<img width="331" alt="screen shot 2017-06-16 at 10 24 26 am" src="https://user-images.githubusercontent.com/1005019/27237569-79361db0-527e-11e7-9299-c9a56e219529.png">

### SYSTEM STATUS

<details>
Home URL:		//pickals.org
Site URL:		//pickals.org
WC version:		3.0.8
Log directory writable:		 /homepages/43/d653319877/htdocs/app658393883/wp-content/uploads/wc-logs/
WP version:		4.8
WP multisite:		–
WP memory limit:		 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP debug mode:		–
WP cron:		
Language:		en_US
Server environment
Server info:		Apache
PHP version:		7.0.19
PHP post max size:		6 MB
PHP time limit:		0
PHP max input vars:		1000
cURL version:		7.38.0, OpenSSL/1.0.1t
SUHOSIN installed:		–
MySQL version:		 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max upload size:		64 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		2.6.14
Database prefix	 	m5wedmhslp
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 /homepages/43/d653319877/htdocs/app658393883/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (16)
LayerSlider WP	 	by Kreatura Media – 5.6.10
BackupGuard Pro	 	by BackupGuard – 1.1.25
CMB2	 	by WebDevStudios – 2.2.4
FedEx WooCommerce Shipping with Print Label	 	by WooForce – 2.4.2
Hide All Notices	 	by Duncan Platt – 0.2
HTTP / HTTPS Remover	 	by CONDACORE – 1.5.3
Less & scss PHP Compilers	 	by Aristeides Stathopoulos – 2.0.1
Quick Page/Post Redirect Plugin	 	by anadnet – 5.1.8
Slider Revolution	 	by ThemePunch – 5.2.6
Shortcoder	 	by Aakash Chakravarthy – 4.0.1
SSL Insecure Content Fixer	 	by WebAware – 2.4.0
Unyson	 	by ThemeFuse – 2.6.16
User Role Editor	 	by Vladimir Garagulya – 4.34
WooCommerce PayPal Powered by Braintree Gateway	 	by WooCommerce – 2.0.3
WooCommerce	 	by Automattic – 3.0.8
WooCommerce Helper	 	by WooCommerce – 1.7.2 – Network enabled
Settings
API enabled:		
Force SSL:		
Currency		USD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		 Page ID is set, but the page does not exist
Cart:		#1185 - /cart/
Checkout:		#1186 - /checkout/
My account:		#1187 - /my-account/
Theme
Name:		Philanthropy Parent
Version:		2.0.4
Author URL:		http://themefuse.com/
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
</details>

**Comment by jtdaugh** [comment]
The select2-hidden-accessible class and explicit style="display: none;" are both preventing this from showing.

<select name="billing_state" id="billing_state" class="state_select select2-hidden-accessible selectized" autocomplete="address-level1" data-placeholder="" tabindex="-1" aria-hidden="true" style="display: none;">
... state options
</select>

**Comment by claudiulodro** [comment]
WooCommerce uses the select2 library for the dropdowns. 

select2 hides the actual `select` element and builds a dynamic HTML dropdown, so the "display:none" is correct. You should see a `span` under the `select` element with class `select2-container`. That's going to be the actual element that gets rendered.

This is going to be a CSS or JS problem in your theme or other plugins. I would check the console for JS errors and the CSS on the `select2-container` that should be right next to the `select` element.

**Comment by patmccormick** [comment]
I have the same problem and the JS console shows no errors.

**Comment by S0PR** [comment]
Just revert back to your previous woocommerce version, this error arises in later version of woocommerce 3.0.0
