### ISSUE TITLE
Cannot create grouped product through the REST API

### ISSUE THREAD

**Issue by cnkcp** [woocommerce/woocommerce#15667]
### EXPLANATION OF THE ISSUE

When trying to create a new grouped product in REST API v2, a simple product is created instead.
Do you plan on adding the ability to create grouped products?

**Comment by mikejolley** [comment]
May be related: https://github.com/woocommerce/woocommerce/pull/15575

But this is working:

<img width="1025" alt="2017-06-19 at 10 34" src="https://user-images.githubusercontent.com/90977/27278997-041d6fa6-54db-11e7-8f7e-7a89784fa68f.png">
