### ISSUE TITLE
Email Restrictions added with upper case characters not comparing to lower case properly on checkout

### ISSUE THREAD

**Issue by markdavies-vivait** [woocommerce/woocommerce#15676]
Hi 

When a customer's email address is entered into the Coupon email restrictions area, and that email address has upper case characters
TestingEmail.Address@Domain.Com

It's a valid email, however when checking out, the system returns the "Sorry, this coupon is not yours" error message.

The issue is in here
class-wc-cart, around line 1650 (WC 3.0.8)

$check_emails[] = $posted['billing_email'];
$check_emails   = array_map( 'sanitize_email', array_map( 'strtolower', $check_emails ) );

if ( 0 == sizeof( array_intersect( $check_emails, $coupon->get_email_restrictions() ) ) ) {

It validates the posted billing email correctly into lowercase, however it doesn't map the email restrictions entered into the coupon into lowercase.  Subsequently, array_intersect which is case sensitive, 

A fix like this would work fine:
if ( 0 == sizeof( array_intersect( $check_emails, array_map( 'sanitize_email', array_map( 'strtolower', $coupon->get_email_restrictions() ) ) ) ) ) {

Any chance we can get that pushed up in a patch release?

Mark

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15678
