### ISSUE TITLE
Cannot display results (woocommerce Cart Add-ons)

### ISSUE THREAD

**Issue by Liquivana** [woocommerce/woocommerce#15675]
### EXPLANATION OF THE ISSUE

When trying to add up sell products I search for them and it just says cannot display results. Just bought the plugin today so it's the latest version.

### STEPS TO REPRODUCE THE ISSUE

Go to cart add-ons
search for a product that is on our site

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Please contact the help desk https://woocommerce.com/contact-us/
