### ISSUE TITLE
Product Gallery Close Button

### ISSUE THREAD

**Issue by vadimilyin** [woocommerce/woocommerce#15673]
### EXPLANATION OF THE ISSUE

Product gallery (post editor) delete button (on thumbnail hover) has no background
Version 3.0.8

### STEPS TO REPRODUCE THE ISSUE

???

### SYSTEM STATUS

<details>
```
???
```
</details>

**Comment by mikejolley** [comment]
<img width="306" alt="2017-06-19 at 10 14" src="https://user-images.githubusercontent.com/90977/27278043-2947746e-54d8-11e7-8863-36e400389d96.png">

**Comment by vadimilyin** [comment]
Button has no background inside the cross. 
It ugly and button can not be seen if an image have grey background.
I think it should have white background, cross should be white.
![screen shot 2017-06-19 at 12 25 31](https://user-images.githubusercontent.com/11349876/27278616-86dceaca-54ea-11e7-8a76-5d2c9e5208b2.png)

**Comment by mikejolley** [comment]
^ That would have been a better issue description ;)

**Comment by mikejolley** [comment]
Should be fixed in https://github.com/woocommerce/woocommerce/pull/15684
