### ISSUE TITLE
cart-fragments.js issues (and fix) for IE

### ISSUE THREAD

**Issue by ericboles** [woocommerce/woocommerce#15670]
Noticed an issue at checkout on older IE browsers when testing an upgrade to WC3.  Checkout would result in this error when using a credit card (Stripe):

> Please enter your card details to make a payment. Developers: Please make sure that you are including jQuery and there are no JavaScript errors on the page.

With some testing, I found that the un-minified cart-fragments.js file got everything working again.  Seems that something in that minified JS file causes IE to flail.  In addition, minifying the un-minified file with UglifyJS2 also keeps everything working fine.

I realize the older IE versions are likely not supported.  (We try to keep it working because our customers are enterprise B2B and many depressingly take forever to upgrade into this decade...)  I at least wanted to let others know what I had found.  All the better if the re-minified file can be added to Master.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15683
