### ISSUE TITLE
woocommerce_checkout_fields works only  if fields is not set

### ISSUE THREAD

**Issue by jgfrm** [woocommerce/woocommerce#15674]
### EXPLANATION OF THE ISSUE

woocommerce_checkout_fields filter is only called if fields are not set.
I want to apply a filter such that user's first and last name in obtained from the standard wordpress user database. This works fine with the following code:
`
// Hook in
add_filter( 'woocommerce_checkout_fields' , 'custom_create_customer_details' );
// Our hooked in function - $fields is passed via the filter!
// see https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/
function custom_create_customer_details( $fields ) {
     $current_user_data = wp_get_current_user();
 	 $user_last = $current_user_data->last_name;
 	 $user_first = $current_user_data->first_name;
     $user_email = $current_user_data->user_email;
  
     $fields['billing']['billing_first_name']['default'] = $user_first;
     $fields['billing']['billing_last_name']['default'] = $user_last;
     $fields['billing']['billing_email']['default'] = $user_email;
     return $fields;
}
`

However, once a user ordered an item earlier, the filter is not called anymore.
So, if the user changes first or last name in Wordpress username, the old name as known in WC is used.

WP v 4.8, WC v 3.0.8

### STEPS TO REPRODUCE THE ISSUE

1. Install the filter as mentioned above
2. Register a user using the standard wordpress facilities
3. With the new user buy an item
4. The billing data shows the user's first and lastname as provided in step 2 (due to the filter)
5. Update the user first/lastname using the standard wordpress facilities
6. With the user, buy an item
7. The billing data shows the first/last name as used in step 4 and not the changed first/lastname

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
`
### WordPress Environment ###

Home URL: https://www1.e3value.com
Site URL: https://www1.e3value.com
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 500 MB
PHP Time Limit: 1600
PHP Max Input Vars: 2000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Akismet Anti-Spam: by Automattic – 3.3.2
bbPress: by The bbPress Community – 2.5.12
Code Snippets: by Shea Bunge – 2.8.6
Email Return-Path Header Fix: by Abdussamad Abdurrazzaq – 0.1
Easy HTTPS (SSL) Redirection: by Tips and Tricks HQ – 1.6
Llorix One Companion: by Themeisle – 1.1.4
Redirection: by John Godley – 2.6.2
Easy Updates Manager: by Easy Updates Manager Team – 6.3.0
WaterWoo PDF: by Caroline Paquette – 1.2.5
WooCommerce Checkout Manager: by Visser Labs – 4.1.2
WooCommerce: by Automattic – 3.0.8
WP-Cron Control: by Thorsten Ott
Erick Hitter
Automattic – 0.7.1

WP Crontrol: by John Blackbourn & contributors – 1.5
WP-Members: by Chad Butler – 3.1.8.1
WP Simple Mail Sender: by Enrique Chavez – 1.0.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #38 - /shop/
Cart: #39 - /cart/
Checkout: #40 - /checkout/
My account: #41 - /my-account/

### Theme ###

Name: Llorix One Lite
Version: 0.2.12
Author URL: http://themeisle.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
You're only setting the default (what gets used if empty) here. If you want to keep billing and names entered elsewhere in sync, you'll need to update them as needed via other hooks.

**Comment by jgfrm** [comment]
I have searched for the relevant hook, but I can not find such a hook. A suggestion would be appreciated.

**Comment by mikejolley** [comment]
https://codex.wordpress.org/Plugin_API/Action_Reference/profile_update

**Comment by jgfrm** [comment]
Thanks.
Where does WooCommerce pull the last/firstname from?
Because it does not take it from the wp user table.

**Comment by mikejolley** [comment]
billing_first_name and billing_last_name. It's part of the addresses.

**Comment by jgfrm** [comment]
Well,

I have the following:
`
add_action( 'profile_update', 'my_profile_update', 10, 2 );

function my_profile_update( $user_id, $old_user_data ) {
    $current_user_id = get_current_user_id();
	$current_user_data = wp_get_current_user();
 	$user_last = $current_user_data->last_name;
 	$user_first = $current_user_data->first_name;
    $user_email = $current_user_data->user_email;

    update_user_meta($current_user_id, 'billing_last_name', $user_last);
	update_user_meta($current_user_id, 'billing_first_name', $user_first);
	update_user_meta($current_user_id, 'billing_email', $user_email);
}`

If I change the first/last name of the user, the billing first/lastname is changed in the database.
However, in order to use the new billing name, I must first logout and login.
Is there a way to avoid this?
