### ISSUE TITLE
Product Update: Taking over 12 seconds to update or does not update at all after 3.0 update.

### ISSUE THREAD

**Issue by judddunagan** [woocommerce/woocommerce#15685]
We have tried several things to try and correct this issue.

We have found that some people have seen that the 3.04 update was more stable. We downgraded from 3.08 to 3.04 and found that this started to work but again the issue was reported back from the client.

https://wordpress.org/support/topic/woocommerce-3-0-5-update-et-very-slow-product-upload/

To reproduce the issue, we simply tried editing any part of the product. The loading animation would start and then not update.

The site uses Avada theme and does need updating on a few files. However, we do not believe any of those issues are the cause. We also believe that the old developer modified the parent theme files which we are in the process of updating in a staging area.

We have disabled all plugins and did test and the same issue happened in staging and in the developement site.

Thanks,
Judd

### SYSTEM STATUS

<details>
`
### WordPress Environment ###

Home URL: https://www.raptisrarebooks.com
Site URL: https://www.raptisrarebooks.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 16384
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.23
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

Gravity Forms: by rocketgenius – 2.2.3
LayerSlider WP: by Kreatura Media – 5.5.0
Import User Meta Data from CSV: by Q Studio – 0.3.2
Admin Columns Pro: by AdminColumns.com – 4.0.5
Advanced Custom Fields: by Elliot Condon – 4.4.11
BBytes Image SEO: by Greg Schoppe – 0.1
Admin Columns - WooCommerce add-on: by Codepress – 2.1.3
Disable Comments: by Samir Shah – 1.6
Enable Media Replace: by Måns Jonasson – 3.0.6
Export User Data: by Q Studio – 1.3.1
Fusion Core: by ThemeFusion – 1.7.4
Gravity Forms MailChimp Add-On: by rocketgenius – 4.2
Import External Images: by Marty Thornley – 1.4
Post Duplicator: by Metaphor Creations – 2.20
Redirection: by John Godley – 2.6.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Reveal Template: by Scott Reilly – 3.2
Revolution Slider: by ThemePunch – 4.6.5
SEO Ultimate: by SEO Design Solutions – 7.6.5.9
Visual Term Description Editor: by Shea Bunge – 1.7.0
W3 Total Cache: by Frederick Townes – 0.9.5.4
Woocommerce Update Files: by Team Bright Vessel –
WooCommerce Admin Custom Order Fields: by SkyVerge – 1.8.0
WooCommerce Intuit Payments Gateway: by SkyVerge – 2.0.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.2
WooCommerce PDF Invoices: by Andrew Benbow – 3.7.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.14
WooCommerce Google Product Feed: by Lee Willis – 5.2.1
WooCommerce - Store Toolkit: by Visser Labs – 1.7.3
WooCommerce - Custom Users Meta Extra Search: by Remi Corson – 1.0
WooCommerce WishLists: by Lucas Stark – 2.0.5
WooCommerce: by Automattic – 3.0.4 – 3.0.8 is available
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
WP-Admin Search Post Meta: by MELONIQ.NET – 0.2
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.91
WP Smush Pro: by WPMU DEV – 2.6.1
WP Sync DB: by Sean Lang – 1.5
WPMU DEV Dashboard: by WPMU DEV – 4.3
XML Sitemap & Google News feeds: by RavanH – 4.7.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4097 - /shop/
Cart: #4098 - /my-account/cart/
Checkout: #4099 - /checkout/
My account: #4100 - /my-account/

### Theme ###

Name: Avada Child
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 3.8.5
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada-Child-Theme/woocommerce/archive-product.php
Avada/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.0.3
Avada/woocommerce/cart/shipping-calculator.php
Avada/woocommerce/checkout/form-checkout.php
Avada/woocommerce/checkout/form-pay.php version 1.6.4 is out of date. The core version is 2.5.0
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
Avada-Child-Theme/woocommerce/content-product.php version 1.6.4 is out of date. The core version is 3.0.0
Avada-Child-Theme/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
Avada-Child-Theme/woocommerce/global/quantity-input.php version 2.1.0 is out of date. The core version is 2.5.0
Avada-Child-Theme/woocommerce/loop/add-to-cart.php version 2.1.0 is out of date. The core version is 3.0.0
Avada/woocommerce/loop/loop-start.php
Avada-Child-Theme/woocommerce/loop/no-products-found.php
Avada-Child-Theme/woocommerce/loop/orderby.php
Avada/woocommerce/loop/pagination.php
Avada/woocommerce/myaccount/form-edit-address.php version 2.1.0 is out of date. The core version is 3.0.0
Avada-Child-Theme/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
Avada-Child-Theme/woocommerce/single-product/add-to-cart/variable.php version 2.3.0 is out of date. The core version is 3.0.0
Avada-Child-Theme/woocommerce/single-product/price.php version 1.6.4 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/product-image.php version 2.0.14 is out of date. The core version is 3.0.2
Avada-Child-Theme/woocommerce/single-product/product-thumbnails.php version 2.3.0 is out of date. The core version is 3.0.2
Avada-Child-Theme/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/short-description.php
Avada-Child-Theme/woocommerce/single-product/tabs/description.php
Avada-Child-Theme/woocommerce/single-product/tabs/tabs.php version 2.0.0 is out of date. The core version is 2.4.0
Avada-Child-Theme/woocommerce/single-product/title.php

Outdated Templates: ❌Learn how to update

### Templates ###

thumbnail: 
medium: 
medium_large: 
large: 
shop_thumbnail: 
shop_catalog: 
shop_single: 
blog-large: 
blog-medium: 
tabs-img: 
related-img: 
portfolio-full: 
portfolio-one: 
portfolio-two: 
portfolio-three: 
portfolio-four: 
portfolio-five: 
portfolio-six: 
recent-posts: 
recent-works-thumbnail: 

### Intuit QBMS ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off
`
</details>

**Comment by mikejolley** [comment]
> To reproduce the issue, we simply tried editing any part of the product. The loading animation would start and then not update.

This simply sounds like a conflict/error on the server which we've answered several times on here. Or similarly, https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x

Looking at the server error logs is the best cause of action, especially if it's specific to your site. I cannot work with the above report locally nor reproduce it.

If you can reproduce it on your staging server with **only** WooCommerce 3.0.8 and a default theme (Twenty Sixteen) active, please email me the details so I can look at the site itself since thats the only thing I can do to diagnose an issue. mike.jolley@automattic.com If it turns out to be a bug I'll log a more detailed issue here or patch right away.

Thanks
