### ISSUE TITLE
I have issue with REST API in my wordpress

### ISSUE THREAD

**Issue by AladinDridi** [woocommerce/woocommerce#15687]
### EXPLANATION OF THE ISSUE

Hello when i try to put this link "http://localhost/wc-api/v2/orders/" for display json response of orders : 
it's show me error like this : 
{"errors":[{"code":"woocommerce_api_authentication_error","message":"Le param\u00e8tre oauth_consumer_key est manquant"}]}
<details>
```Please it's urgently for me i need to take json response of our orders with payment methods , wish someone help for resolve that issue .... :) thank you very much

**Comment by mikejolley** [comment]
Please go through https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API, this is not a support area,
