### ISSUE TITLE
Related products by subcategorie in WC > V3.0.0

### ISSUE THREAD

**Issue by dontbyte** [woocommerce/woocommerce#15681]
Does anyone has a working solution to show related products for the same subcategory? Currently there are related products for the parent product category. I've found some solutions for older version (like [850](https://github.com/woocommerce/woocommerce/issues/850) but it doesn't work for WC > V3.0.0. ) of WC but they don't work anymore.

Thanks in advance!

**Comment by mikejolley** [comment]
```
- GitHub issues ARE NOT FOR SUPPORT! If you have questions, use the either:
  - https://wordpress.org/support/plugin/woocommerce for general support
  - https://woocommerce.com/my-account/tickets/ for premium plugin support
```

You may need a developer to code this customisation if nothing pre-made exists.

Working out all subcategories would add extra page load time for the query FWIW
