### ISSUE TITLE
I Can not change order status through an API

### ISSUE THREAD

**Issue by jordaokilla** [woocommerce/woocommerce#15688]
### EXPLANATION OF THE ISSUE

The code line below used to work on woocommerce 2.6.X since I upgraded to 3.0 no longer works.

$client->orders->update_status( $order_id, 'Processing' );

### STEPS TO REPRODUCE THE ISSUE

Update order from pending to processing through an API.

### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
</details>

**Comment by mikejolley** [comment]
Which client? PHP? Issues can be logged and the latest versions gathered from https://github.com/woocommerce/wc-api-php

**Comment by jordaokilla** [comment]
yes. PHP.


Jordão Neto
*Founder*
Bwe Vip Group
m: +244 923453462
a: Projecto Nova, Rua 36, Casa 8
w: blog.bwevip.com  e: jordao.neto@bwevip.com
<https://facebook.com/jordao.neto>   <https://twitter.com/jordaokilla>
<https://linkedin.com/jordao.neto>   <https://instagram.com/jkilla>
[image: Inbound Certification] <http://hubs.ly/H035cNn0>

**Comment by jordaokilla** [comment]
, és meu convidado VIP,

Acho que já ouviste falar que a Jucélia Gabriel (Especialista em
finanças) esta a fazer uma MasterClass para um número reduzido de
pessoas.

Pois as vagas ACABARAM, mas eu não podia te deixar de fora, então
estou a mandar o link VIP para ainda fazeres a inscrição e assistires
a aula gratuitamente.

Veja o que vais aprender nesta aula

Ela vai falar falar sobre os seguintes temas: 

✅ Como começar a organizar a tua vida financeira 

✅ Como montar e controlar o orçamento de forma prática 

✅ Como começar a poupar e investir 

✅ Como identificar novas fontes de rendimento 

A aula começa às 19h00 de hoje basta clicares no botão para fazeres a
inscrição no link VIP.

QUERO FAZER A MINHA INSCRIÇÃO AGORA!

Vejo-te na MasterClass. Até já.

Jordão Neto

**Fundador da**Owysa
m:+244 9346282559
a:Projecto Nova, Rua 36, Casa 8
e: info@owysa.com

Sent to: reply@reply.github.com

Bwe Vip Group, Projecto Nova Vida, Rua 39, Casa 8, Angola

Não queres receber meus emails? 

Não por favor
