### ISSUE TITLE
An individual product which is set to draft within a Grouped Product is still visible to customers

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#15689]
In WooCommerce v3.0.8 if you set a product which is part of a Grouped Product to be the status of Draft the product still displays within the Grouped Product to customers like this example below and which produces an `Oops! That page can’t be found` if read more is clicked.

![pm8lds](https://user-images.githubusercontent.com/1190565/27290211-77d90f12-5504-11e7-826e-4c3cd688420a.png)

Individual Products which are set to a status of Draft but which are part of a Grouped Product should not display like this, correct and it was indicated by the customer who reported this behavior that it used to completely hide the product.

**Comment by WPprodigy** [comment]
There is some wacky behavior with being logged-in vs logged-out when it comes to draft mode and other visibility settings. I'm using the master branch in testing.

1) When logged in, the product always appears visible in the grouped product. Regardless of draft mode, private visibility, or password protected. This may be a WordPress Admin feature, but I'm thinking it could cause some store owners a headache if they are only testing while logged in.

2) When logged out, what @stuartduff reported also happens with the private visibility and password protected modes.

**Comment by mikejolley** [comment]
Thanks for looking. I agree `woocommerce_grouped_add_to_cart` would be a good place to filter products out - a new filter could work. I need to look into price generation too however so this is probably more complex than it looks.
