### ISSUE TITLE
WooCommerce Product Issues

### ISSUE THREAD

**Issue by MasMehTure** [woocommerce/woocommerce#15690]
### EXPLANATION OF THE ISSUE

WooCommerce 3.0.8 If you click on a product in the live site, the picture doesn't display. Its there in the code, but it doesn't display. Also, When inserting a product in the backend, The tabs under the Product Data Tab don't work

### STEPS TO REPRODUCE THE ISSUE

Go to WP admin console

Click products

Click add product

Go down to Product Data tab

Click on any side tabs under product data tab
### SYSTEM STATUS

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here between the `details` tags.
```
WordPress environment
Home URL:		http://kenningtonjewelers.com
Site URL:		http://kenningtonjewelers.com
WC version:		3.0.8
Log directory writable:		 /home/kennjewelers/public_html/wp-content/uploads/wc-logs/
WP version:		4.8
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		–
WP cron:		
Language:		en
Server environment
Server info:		Apache/2.4.25
PHP version:		5.6.30
PHP post max size:		8 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.36.0, OpenSSL/1.0.1e
SUHOSIN installed:		–
MySQL version:		5.6.35
Max upload size:		2 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.8
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: /home/kennjewelers/public_html/wp-content/uploads/GeoIP.dat. Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (32)
Contact Info	 	by aviplugins.com – 3.1
Contact Widgets	 	by GoDaddy – 1.4.1
GoDaddy Email Marketing	 	by GoDaddy – 1.2.0
Google Analytics for WordPress by MonsterInsights	 	by MonsterInsights – 6.2.0
Limit Login Attempts	 	by Johan Eenfeldt – 1.7.1
Max Mega Menu - StoreFront Integration	 	by Tom Hemsley – 0.1
Max Mega Menu	 	by Tom Hemsley – 2.3.7.1
Ninja Forms	 	by The WP Ninjas – 3.1.4
Portfolio	 	by Huge IT – 10.0
Contact Info Widget	 	by Riotweb.nl – 2.6.1
Huge IT Slider	 	by Huge-IT – 4.0.4
Storefront Add Slider	 	by Pangolin Themes – 0.3
Storefront Footer Bar	 	by WooThemes – 1.0.3
Storefront Footer Text	 	by Wooassist – 1.0.1
Storefront Gridder	 	by ulisesfreitas – 1.0.1
Storefront Hamburger Menu	 	by WooThemes – 1.2.1
Storefront Header Picker	 	by Wooassist – 1.0.2
Storefront Homepage Contact Section	 	by WooThemes – 1.0.3
Storefront Homepage Extra Sections	 	by WPDevHQ – 1.0.2
Storefront Jetpack	 	by PootlePress – 1.0.0
Storefront Pro Skins	 	by pootlepress – 0.5.0
Storefront Product Pagination	 	by WooThemes – 1.2.1
Storefront Product Sharing	 	by WooThemes – 1.0.4
Storefront Sticky Add to Cart	 	by WooThemes – 1.1.6
Title Toggle for Storefront Theme	 	by Wooassist – 1.2.3
Storefront Top Bar	 	by Wooassist – 1.1.1
Ultimate Form Builder Lite	 	by AccessPress Themes – 1.3.4
WooCommerce Cart Tab	 	by jameskoster – 1.1.1
WooCommerce	 	by Automattic – 3.0.8
WordPress Importer	 	by wordpressdotorg – 0.6.3
Wordpress File Upload	 	by Nickolas Bossinas – 3.11.0
Opening Hours	 	by Jannik Portz – 2.1.2
Settings
API enabled:		
Force SSL:		
Currency		USD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#31 - /products/
Cart:		#6 - /cart/
Checkout:		#7 - /checkout/
My account:		#8 - /my-account/
Theme
Name:		Storefront
Version:		2.2.3
Author URL:		https://woocommerce.com/
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Overrides:	 	–

**Comment by claudiosanches** [comment]
Tested using the steps you described and works just fine, sounds like incomparability with some 3rd party plugin or theme, since you have 32 installed plugins, my guess is that you should start testing it, still since there is a problem with images on frontend, maybe you theme is not compatibility and requires an update.
