### ISSUE TITLE
Lightbox doesn't show images

### ISSUE THREAD

**Issue by thehung2224** [woocommerce/woocommerce#15698]
### EXPLANATION OF THE ISSUE

I'm using Woo 3.0.8. I switched default theme, however the lightbox doesn't show product images, it's only empty.

Here are product images http://prntscr.com/fly4nq. When I opened lightbox, nothing displayed http://prntscr.com/fly4v2

I already added functions as you said https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox)-in-3.0.0

**Comment by mikejolley** [comment]
Need a link to the site + system status report or this will be closed.

**Comment by mikejolley** [comment]
Feel free to post more information like requested on the new issue form. Given the information, this works for me.

**Comment by thehung2224** [comment]
@mikejolley This is my site: http://sabasrl.com/prodotti/sistemi-di-trasporto

**Comment by mikejolley** [comment]
Images load here

**Comment by thehung2224** [comment]
Thank you @mikejolley However, why the images appear one by one instead of slider?

**Comment by thehung2224** [comment]
@mikejolley Please let me know how can I control number of images are displayed. I want to it look like slider instead of showing one by one

**Comment by mikejolley** [comment]
I think it's the template files in your theme. Has the author put out a compatible update?

**Comment by thehung2224** [comment]
@mikejolley I have removed all template files from my theme, however it still doesn't work while default theme works fine.

**Comment by mikejolley** [comment]
To be clear; the gallery requires CSS, the code to enable it, and theme files which account for it. Get an update from the author.
