### ISSUE TITLE
Log error php message function deprecated

### ISSUE THREAD

**Issue by Johanwalter** [woocommerce/woocommerce#15693]
Hi,

Since version Woocommerce 3, we  have log php error message on cart validation

"AH01071: Got error 'PHP message: The The "woocommerce_add_order_item_meta" hook uses out of date data structures and function is deprecated since version 3.0.8. Replace with woocommerce_new_order_item.\nPHP message: The woocommerce_add_order_item_meta function is deprecated since version 3.0. Replace with wc_add_order_item_meta.\nPHP message: The woocommerce_update_order_item_meta function is deprecated since version 3.0. Replace with wc_update_order_item_meta.\n', referer: http://www.domainname.com/commande/"

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Deprecation-in-core#warnings-in-production-store-owners-read-this
