### ISSUE TITLE
Endless loading/spinner on the checkout page. (On the Paypal window)

### ISSUE THREAD

**Issue by benevbright** [woocommerce/woocommerce#15706]
## Prerequisites

- [O] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [?] The issue still exists against the latest `master` branch of WooCommerce
- [O] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [O] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

It worked fine before I update Woocommerce to 3.0.8 from 2.x.x.

1. Please visit my website http://myallb.com
2. When you proceed checkout, the spinner is spinning on the paypal window forever.
3. If I press the button right before spinner make it hide, I got "SyntaxError: Unexpected token < in JSON at position 0" error message.

What I tried.
- I already read this https://docs.woocommerce.com/document/endless-loadingspinner-on-the-checkout-page/ but it would have not helped for me.
- deactivate all plug-in one-by-one. 
- changed the theme to another one.
nothing works.
no error message on the system status except about https (SSL).

Thanks.

## Environment

WordPress environment
Home URL:		http://myallb.com
Site URL:		http://myallb.com
WC version:		3.0.8
Log directory writable:		 /usr/share/nginx/allb/wp-content/uploads/wc-logs/
WP version:		4.8
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		–
WP cron:		
Language:		en_US
Server environment
Server info:		nginx/1.10.0
PHP version:		7.0.18-0ubuntu0.16.04.1
PHP post max size:		100 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.47.0, OpenSSL/1.0.2g
SUHOSIN installed:		–
MySQL version:		5.6.27
Max upload size:		100 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.8
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 /usr/share/nginx/allb/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		
Active plugins (28)
Amazon Product In a Post Plugin	 	by Don Fischer – 3.6.4
Blogger Importer	 	by wordpressdotorg – 0.9
Easy WP SMTP	 	by wpecommerce – 1.2.5
Facebook Conversion Pixel	 	by Kellen Mace – 1.3.5
Formidable Forms	 	by Strategy11 – 2.03.09
Google Analytics Dashboard for WP (GADWP)	 	by Alin Marcu – 5.0.1
Master Slider Pro	 	by averta – 3.1.3
MaxButtons	 	by Max Foundry – 6.20
Meta Box Tabs	 	by Rilwis – 0.1.1
Meta Box	 	by MetaBox.io – 4.11.3
Post Types Order	 	by Nsp Code – 1.9.3.1
qTranslate-X	 	by qTranslate Team – 3.4.6.8
Quick and Easy FAQs	 	by M Saqib Sarwar – 1.0.3
Simple Page Ordering	 	by Jake Goldman, 10up – 2.2.4
Super Simple Google Analytics	 	by bitacre – 1.7.2
Themovation Custom Post Types	 	by Themovation – 2
Themovation Shortcodes	 	by Themovation – 2.1.2
Widget Importer & Exporter	 	by churchthemes.com – 1.4.5
Widget Logic	 	by wpchefgadget, alanft – 5.8.2
WooComemrce Better Thumbnail Navigation	 	by Peter Elmered – 0.1.2
WooCommerce Direct Checkout	 	by Terry Tsang – 1.1.2
WooCommerce & qTranslate-X	 	by qTranslate Team – 1.3
WooCommerce	 	by Automattic – 3.0.8
WooCommerce Helper	 	by WooCommerce – 1.7.2 – Network enabled
WordPress Importer	 	by wordpressdotorg – 0.6.3
Yoast SEO	 	by Team Yoast – 4.9
WP Mail Logging	 	by Christian Zöller – 1.8.1
Integration: Yoast SEO & qTranslate-X	 	by qTranslate Team – 1.1.1
Settings
API enabled:		
Force SSL:		–
Currency		USD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#11 - /shop/
Cart:		#12 - /cart/
Checkout:		#13 - /checkout/
My account:		#14 - /my-account/
Theme
Name:		Stratus
Version:		2.0.1
Author URL:		http://themovation.com
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Overrides	 	stratus/woocommerce/archive-product.php, 
stratus/woocommerce/cart/cart.php, 
stratus/woocommerce/single-product.php

## Isolating the problem

- [?] This bug happens with only WooCommerce plugin active
- [?] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [O] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
> deactivate all plug-in one-by-one.

Did you deactivate all plugins except for WooCommerce at once, and switch to a default theme at the same time? Deactivate everything but WooCommerce and run a test. This error only appears when another extension is causing problems at checkout.

This is more of a support request than a bug report, as there is nothing wrong in the latest version of WooCommerce core causing this. Something on your website specifically is.

It would be best to use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce) for this, or search around the [WooCommerce Support](https://docs.woocommerce.com/) page.

**Comment by mikejolley** [comment]
http://myallb.com/checkout/?wc-ajax=update_order_review is redirecting to `http://myallb.com/checkout/`

Something is disabling this endpoint and redirecting.  

<img width="494" alt="2017-06-21 at 10 17" src="https://user-images.githubusercontent.com/90977/27376677-cd140308-566a-11e7-8ab7-a97328c3f73a.png">

Suggest you look at your htaccess and hosting config and ensure this redirect does not occur. It is not a core bug.

**Comment by benevbright** [comment]
Hi, 
We've looked our issue several days.
It turns out it was a problem related to ours nginx hosting.
I'm sorry for issuing this.
And we really appreciate your help.
Thanks.

**Comment by johngit7** [comment]
@benevbright What was the specific issue with the nginx hosting. I also experience this and have been unable to solve it so far.

**Comment by benevbright** [comment]
Hi @johngit7 . I asked our server developer but he can't remember what exactly he fixed. He said, "Maybe I fixed some at config".
