### ISSUE TITLE
Products got disappeared from the product list page in Wordpress

### ISSUE THREAD

**Issue by zamsonj** [woocommerce/woocommerce#15708]
## Steps to reproduce the issue

1. Installed Woocommerce and added some products. The list of products were appearing in the shop page and then individual display for each product. 
2. Everything worked fine.
3. Suddenly one day without doing anything, the products are disappeared from the shop page. They are still appearing in the individual product pages.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active

**Comment by WPprodigy** [comment]
Hi zamsonj,

Have you isolated the problem? Does this occur when only WooCommerce is active with a default theme? Also, make sure your Shop page is properly configured: https://docs.woocommerce.com/document/woocommerce-pages/

This isn't likely to be an issue with WooCommerce core, as it doesn't happen on other website. Something on your website specifically caused this.

**Comment by zamsonj** [comment]
@WPprodigy ,
Thank you. This was an issue with the configuration of the shop page

**Comment by cavalihno** [comment]
@zamsonj What was the problem exactly, can you describe what was configured incorrect? I'm facing an identical problem.

**Comment by Bushinas** [comment]
If anyone still faces this issue please check this link:
https://searchwp.com/how-to-fix-woocommerce-shop-page-not-showing-products/
Hope this will solve it.
