### ISSUE TITLE
Canceled emails when orders go from Pending to Canceled no longer sent

### ISSUE THREAD

**Issue by jbrenner99** [woocommerce/woocommerce#15707]
In WC 3.0.8 a fix was made for issue #15163.  Now Pending orders that go to Cancelled no longer send an email.  Is it possible to have Cancelled emails sent for both a status change from Pending to Cancelled, and from Processing to Cancelled?   When offsite and not logged into WC, we relied on these emails to ensure that orders weren't being skipped for some reason.  Since the emails are no longer sent, there are gaps in order number email notifications.  Previously, we may have received an email for new order 1001, followed by an email for new order 1002, followed by a canceled order 1003, followed by new order 1004.  Now we don't receive an email on order 1003 so we are uncertain if there was an issue or if the order was canceled.

**Comment by WPprodigy** [comment]
Pending orders can be created by a spam bot on your website. All it takes is adding items to the cart, clicking on PayPal, then leaving without paying. That's the reasoning behind removing this email. A pending -> cancelled order means nothing.

That said, this email could be re-enabled using the hooks available. That change shows exactly what hook you need to use: https://github.com/woocommerce/woocommerce/commit/067489b1550f53144b1f1a99326b5704fb2ea464

**Comment by mikejolley** [comment]
Pending is unpaid, so no cancelled email should sent by default. This was a core bug; it was changed to processing to cancelled which is the correct event.
