### ISSUE TITLE
Please remove unnecessary scripts

### ISSUE THREAD

**Issue by xttn** [woocommerce/woocommerce#15711]
Your plugin is including Woocomerce settings.js on all admin pages , basically making color picker and other scripts unusable since Woocomerce settings.js is made for Woocomerce admin only. Can please fix this.
https://github.com/ThemeFuse/Unyson/issues/1822#issuecomment-248814672

**Comment by WPprodigy** [comment]
It's not being loaded on all admin pages though? Open up the console and do a search for `woocommerce/assets/js/admin/settings.js` on non-WooCommerce settings pages in the admin.

It's only loaded on WooCommerce > Settings pages. The conflict you are having is not with WooCommerce core. It's either with your theme, `Unyson`, or the plugin `yith-woocommerce-wishlist`.

**Comment by xttn** [comment]
Yes, exactly it conflicts with YITH wishlists plugin. I created a topic here: https://wordpress.org/support/topic/please-remove-unecessary-scripts/, but it looks like it was not supported.

**Comment by mikejolley** [comment]
We don't maintain YITH wishlists.
