### ISSUE TITLE
Coupon issue with multiple items in cart

### ISSUE THREAD

**Issue by anamicab** [woocommerce/woocommerce#15715]
Hello,

Coupon is getting applied where it shouldn't. My WC version is 3.0.8

## Details of the coupon
I have created a coupon called "SALE" whose details are as follows:
### General
**Discount Type :** Fixed cart discount
**Coupon Amount:** 5

### Usage restriction
**minimum spend:** 0
**maximum spend:** 700
**Individual use only:** checked
**Exclude sale items:** checked
**Product categories:** Coffee & Tea Saucers

**Usage limit** is unlimited

## Details of the issue
Now i have added two products in my cart.
**Product 1**: On sale, belongs to category Coffee & Tea Saucers
**Product 2**: Not on sale, doesn't belongs to the category Coffee & Tea Saucers

When i tries to apply coupon on my cart it gets applied. What i was expecting it shouldn't get applied. To test this i changed my **Discount Type** to **Percentage Discount** and it performed just as i expected. I got **Sorry, this coupon is not applicable to your cart contents** error.

Another thing that i''ve noticed is when i apply same coupon on these products individually with **Discount Type** as **Fixed cart discount** it doesn't gets applied. So how it should get applied when both of these products are added to the same  cart.

## How to test this issue
- goto [http://glowifi.com/shop/](http://glowifi.com/shop/)
- Add **a** and **Grouped Product** in your cart
- Click on **View Cart**
- Enter **SALE** in COUPON CODE and hit **APPLY COUPON**

Now as you can see the coupon gets applied. See the details of product **a** and product **Grouped Product**. You'll see that **a** is not on sale but also doesn't belongs to the product category for which 
coupon is applicable whereas product **Grouped Product** is on sale and belongs to the product category specified. So, in this scenario none of the product completes the coupon requirements so the coupon should not get applied.

**Comment by mikejolley** [comment]
Since it's a fixed discount, as long as there is a non-on-sale product in the cart, the coupon amount is the same regardless. 

> Product 1: On sale, belongs to category Coffee & Tea Saucers
> Product 2: Not on sale, doesn't belongs to the category Coffee & Tea Saucers

This user could pay the exact same amount, and use the exact same coupon, if they submitted 2 orders with 1 item in each. That is counter productive.

I'll check the combination of sale and category.

**Comment by anamicab** [comment]
Thanks.. for your review in this
I am waiting for your answer because i think the coupon should not get applied since none of the product is meeting the requirements of coupon

**Comment by anamicab** [comment]
Thanks alot for adding this as a bug
Will wait for the next update
