### ISSUE TITLE
one button add_to_cart , another button redirect_to_cart_after_add_to_cart

### ISSUE THREAD

**Issue by CaryQY** [woocommerce/woocommerce#15713]
hi
In single product page, I use `woocommerce_single_product_summary` action to get `Add to cart` button, and in `woocommerce->settings->display` to set  if redirect to cart page. 
now i want to add two buttons in a single page .
    1. one is only add_to_cart  
    2. another is  redirect_to_cart_page_after_add_to_cart

in plugins/woocommerce/js/frontend/add-to-cat.js. I find here is to judge whether redirect but i want to use action to  achieve this purpose. I didn`t find this action in  plugins/woocommerce ,so if i miss something or give me some   suggestion.
thanks

**Comment by mikejolley** [comment]
Add your second button via a filter or the template. Simply link to the cart page with `add-to-cart=X` on the end of the URL.
