### ISSUE TITLE
Setting Variation Stock Status to 'outofstock' programatically does not update Parent Product Stock Status

### ISSUE THREAD

**Issue by thomasmery** [woocommerce/woocommerce#15716]
Hi there,

was trying to understand why some of my variable products were still 'instock' after I made a programatic pass at them to set their variations to 'outofstock' under certain conditions (site specific)

as they still appeared in the shop after enabling 'hide out of stock products' 
I tested manually and it was working as expected
but seemed like my code did not set the mechanism in motion

thanks to anyone who can help on this

## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. setup a variable product with one variation
2. set the variation stock status to 'instock'
check that the parent product is 'instock' (in 3.0 there is NO term_relationship entry between the parent product and the 'outofstock' term_taxonomy_id)
3. set the variation stock status to out of stock (using wp-cli  for instance)
```
$variation = wc_get_product(VARIATION_ID);
$variation->set_stock_status('outofstock');
$variation->save();
```

## Expected behavior and actual behavior

the parent product is not 'outofstock'
no entry is created in the term_relationships table for the parent product and the 'outofstock' term

I was expecting...

the same behaviour as when setting a variation 'outofstock' via the admin panel

namely that setting a unique variation (or all variations) to 'outofstock' will update the parent status

## Environment

I can provide it but I don't think this is relevant (let me know)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/15569

**Comment by mikejolley** [comment]
Also note, the parent status depends on whether it itself is stock managed or not. It won't sync if so.

**Comment by thomasmery** [comment]
thanks @mikejolley 

I'll test the fix now

and yes this only applies to variation managed stock

**Comment by thomasmery** [comment]
@mikejolley,

I tried the fix you pointed to and also had a look at it regarding the issue I raised

and unless I'm mistaken this does not seem related as my pb is that I can't programmatically switch Variations visibility & have the mechanism that sets the parent product to be triggered

the code that's in the PR seems to only set the Variation visibility but not trigger the visibility change on the parent

maybe I'm mistaken but in any case testing manually with wp-cli does not seem to work

maybe you can point me to the code where the parent visibility is set depending on the variations visibility

thanks

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/d9e946491f8db0de43e4c42bff35de7b57ccf21b/includes/class-wc-post-data.php#L79

**Comment by thomasmery** [comment]
thanks,

so am I right in saying I need to call `$product->sync( $product )` to make things happen?
`$product` being `wc_get_product($variation->get_parent_id())`

as the `sync` seems to happen at shutdown time
if I want it to happen sooner I need to do this

I was not seeing the changes because I was on a WP CLI session and did not go through the 'shutdown' phase

If I'm right and if there is a place that would benefit from this info please let me know and I'll update the docs about this

maybe this is already documented though

thanks for any insight on this
