### ISSUE TITLE
Order status set as completed right after creation but should be processing

### ISSUE THREAD

**Issue by ticatagdev** [woocommerce/woocommerce#15726]
Since we upgraded from woocommerce 2.x to .3.0.x the order is set as "completed" right after creation and doesn't go through the "processing" status.

I do not know understand why the order is auto completed as none of our products are digital/downloadable.

An other user opened a topic for the same issue on wordpress : https://wordpress.org/support/topic/order-status-on-hold-or-completed-should-be-processing/

**Comment by mikejolley** [comment]
This can be controlled by:

- plugins
- custom code (in theme)
- gateway

You need to rule these items out before logging issues, as stated on the new issue form. We cannot reproduce this on a clean install and more users would be affected than 2 if it were a widespread problem.

**Comment by ticatagdev** [comment]
Hi mike,

Indeed, updating the theme fixed the issue.

Thks.
