### ISSUE TITLE
Show variation details even if price is empty

### ISSUE THREAD

**Issue by bmndan** [woocommerce/woocommerce#15724]
I wrote a few conditional HTML lines in the variation.php (i.e. if X then display Y)
I want these to print out on the single-product page even if the variation price is empty
How do I go about doing that?

**Comment by mikejolley** [comment]
We cannot help with custom coding on Github - it's a bug tracker. There are filters to control the returned price html, even if core does not want to display it by default.

**Comment by bmndan** [comment]
Hi Mike
Ok I'd then better ask on forums for help or research the docs first to better understand how it works with the filters
Thanks!
Daniel
