### ISSUE TITLE
Too many queries in woo3 when using product_category shortcode

### ISSUE THREAD

**Issue by ilyatrepachko** [woocommerce/woocommerce#15720]
I've updated to woocommerce v3.0.8 from v2.6.14. Now woo3 calls 2268 db queries, eats all my server resources and takes ~30 sec to load category page with 150 products. I use product_category shortcode to show products on category page. Woo2 calls ~300 db queries and takes ~5 sec to load the same page.
All tests I did with theme "Storefront"

**Query stats:**
![korobki-queries](https://user-images.githubusercontent.com/28954735/27386243-d6f3f594-569d-11e7-935d-fbde58fdeca6.png)
![korobki-slow-queries](https://user-images.githubusercontent.com/28954735/27386242-d6effa2a-569d-11e7-9129-312cf8651f1c.png)

**Status report:**
### WordPress Environment ###

Home URL: http://stage.ipapera.by
Site URL: http://stage.ipapera.by
WC Version: 3.0.8
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 10000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.54 - Мы рекомендуем MySQL версии не меньше 5.6. Читайте: Требования WordPress
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌В вашем магазине не используется HTTPS. Подробнее о HTTPS и SSL-сертификатах .
Hide errors from visitors: ✔

### Active Plugins (7) ###

Query Monitor: от John Blackbourn – 2.13.4
All In One SEO Pack: от Michael Torbert – 2.3.13.2
Instagram Feed: от Smash Balloon – 1.4.9
Ограничение попыток авторизации: от Johan Eenfeldt – 1.7.1
RusToLat: от Anton Skorobogatov  – 0.3
Saphali Woocommerce Russian: от Saphali – 1.7.1
WooCommerce: от Automattic – 3.0.8

### Settings ###

API Enabled: –
Force SSL: –
Currency: BYN (руб.)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Ссылка магазина: #74 - /shop/
Корзина: #75 - /cart/
Оформление заказа: #76 - /checkout/
Мой аккаунт: #77 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – Если вы модифицируете элементы WooCommerce в теме WordPress
которую вы не разрабатывали самостоятельно
рекомендуется использовать дочернюю тему. Читайте: Как создать дочернюю тему

WooCommerce Support: ✔

### Templates ###

Overrides: –

**Comment by mikejolley** [comment]
Which queries are being called the most?

**Comment by ilyatrepachko** [comment]
See list of queries in attachment.
[korobki-queries.xlsx](https://github.com/woocommerce/woocommerce/files/1092115/korobki-queries.xlsx)

**Comment by ilyatrepachko** [comment]
@mikejolley, i collected log data for a small page with 3 products (ids: 17988; 9913; 9909). I think is an easy way to analyze the data. So, i counted 13 queries for one product. And the most of them are the queries with ordering by each product attribute in the attribute referrence.  

**Queries for product = 17988:**
![3products-queries-1](https://user-images.githubusercontent.com/28954735/27421514-65598ca0-5733-11e7-9b56-8c694dabef48.png)
![3products-queries-2](https://user-images.githubusercontent.com/28954735/27421518-6a5124e8-5733-11e7-9e02-bd23f2c90de3.png)
![3products-queries-3](https://user-images.githubusercontent.com/28954735/27421523-72b69398-5733-11e7-8332-064148b897fb.png)
![3products-queries-4](https://user-images.githubusercontent.com/28954735/27421530-8103240c-5733-11e7-970c-5b5101abf87b.png)

I have attributes: color; cvet-konverta; cvet-naklejki; cvet-struzhki; kak-dostavlyat; nabory; nadpis; razmer; ves. These attributes are used for some varriative products, but not for all products.

**All queries for 3-products category:**
[3products-queries.txt](https://github.com/woocommerce/woocommerce/files/1093920/3products-queries.txt)

So, if woo calls 13 queries for one product, it calls 13*150 = 1950 queries minimum for 150 products. But it's too many queries for one page. And if i had 100 attributes, woo would call more than 100*150 = 15000 queries. I think it's a big leak of performance.

**Comment by mikejolley** [comment]
@ilyatrepachko Can you test this patch? https://github.com/woocommerce/woocommerce/commit/e06aa6f60a2dba502d37f08d8c6432c10e1066c2

**Comment by ilyatrepachko** [comment]
@mikejolley I did it. Number of queries is decreased, but just on a half. Now, there are 6 queries per product. There are 1191 queries for page with 150 products, and it takes ~13 sec to load the page. It is too slow yet.

**Stats of queries for page with 150 products:**
![korobki-queries-with-patch](https://user-images.githubusercontent.com/28954735/27432390-9af42274-5758-11e7-943d-8a06db65b7fb.png)

**Log of queries for page with 3 products:**
[3products-queries-with-patch.txt](https://github.com/woocommerce/woocommerce/files/1094596/3products-queries-with-patch.txt)

 I'd like to upgrade to woo3 very much, but i can't do it with the current performance issue :-(

**Comment by ilyatrepachko** [comment]
It seems, that woo cals the odd queries yet, such as:
`
SELECT t.*, tt.*
FROM wp_terms AS t 
INNER JOIN wp_term_taxonomy AS tt
ON t.term_id = tt.term_id
INNER JOIN wp_term_relationships AS tr
ON tr.term_taxonomy_id = tt.term_taxonomy_id
WHERE tt.taxonomy IN ('product_type')
AND tr.object_id IN (17988)
ORDER BY t.name ASC

SELECT DISTINCT t.*, tt.*, tm.meta_value
FROM wp_terms AS t 
INNER JOIN wp_term_taxonomy AS tt
ON t.term_id = tt.term_id
INNER JOIN wp_term_relationships AS tr
ON tr.term_taxonomy_id = tt.term_taxonomy_id
LEFT JOIN wp_termmeta AS tm
ON (t.term_id = tm.term_id
AND tm.meta_key = 'order_pa_razmer') 
WHERE tt.taxonomy IN ('pa_razmer')
AND tr.object_id IN (17988)
ORDER BY tm.meta_value+0 ASC, t.name ASC

SELECT t.*, tt.*
FROM wp_terms AS t 
INNER JOIN wp_term_taxonomy AS tt
ON t.term_id = tt.term_id
INNER JOIN wp_term_relationships AS tr
ON tr.term_taxonomy_id = tt.term_taxonomy_id
WHERE tt.taxonomy IN ('product_visibility')
AND tr.object_id IN (17988)
ORDER BY t.name ASC

`

**Comment by mikejolley** [comment]
These are from WordPress itself; reading the terms for each product (loading attributes on read). The fix I posted primes the cache per product. There may be other primes we can do, but ultimately loading a tonne of products at once will be slower.

**Comment by ilyatrepachko** [comment]
I see your point, but woo2 calls less queries (~300 for product page with 150 products).

**Comment by mikejolley** [comment]
yeah, It does not do a full object read afaik. This does.

**Comment by ilyatrepachko** [comment]
I wonder if there will be further steps on this issue, or not?)

**Comment by ilyatrepachko** [comment]
@mikejolley it seems that value of "per_page" attr in the shortcode affects to number of queries. As i said i have 150 products on the page. When i use per_page = 900 (to not wory about number of products) the number of queries is ~1K. But when i use per_page = 200 for the same page (with 150 products) the number of queries ~300. What's the reason?

**Comment by ilyatrepachko** [comment]
@mikejolley i have some loadings where number of queries was normal.

**Comment by mikejolley** [comment]
Try this one https://github.com/woocommerce/woocommerce/commit/67bc729ea5d75a4ffc683b3f76a1e47c91e11164

**Comment by mikejolley** [comment]
@ilyatrepachko ^ That PR primes cache for all posts on the page at once. Should reduce the number of queries substantially.

**Comment by ilyatrepachko** [comment]
@mikejolley You are the hero!!! It works perfectly ) there are 331 queries for the page with 150 products)

**Comment by ilyatrepachko** [comment]
This commit will be included in the next release, won't this?
