### ISSUE TITLE
When entering numeric coupon codes, the coupon the same post id is picked up rather than the coupon

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce#15725]
### Summary:

On the cart page if you enter a coupon called `9418` and in the backend if there is a coupon with post id `9418` then it gets picked up rather then the coupon called `9418`.

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create the below 2 coupons ![](http://cld.wthms.co/X085cT+)
2. Now add a product to cart and apply coupon `9408`
3. What will happen is that the coupon called `Gift Card` that has the post id `9408` will be applied rather than the coupon called `9418`.

## Expected behavior and actual behavior

On the cart page if you enter a coupon called `9418` and in the backend if there is a coupon with post id `9418` then the coupon called `9418` gets picked up

 

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

zd-woothemes-583839

**Comment by greenr1227** [comment]
I'm still getting this issue. Any ideas?

**Comment by claudiulodro** [comment]
@greenr1227 [The fix is going to be in 3.2](https://github.com/woocommerce/woocommerce/pull/15829)
