### ISSUE TITLE
Update Dummy Data

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#15723]
The new dummy data still includes the older products. I'd like to update that based on the Storefront starter content. I'll also create a few things that aren't available in the starter content (like variable products, featured products)

Is that okay @mikejolley ?

**Comment by mikejolley** [comment]
If you want to take this on :) This was on my eventual list.

**Comment by claudiosanches** [comment]
Should at least include more than one picture for product, and keep examples of downloadable (with real files to download), external, and grouped products too... All not included into the Storefront starter content.

**Comment by lukecav** [comment]
I would be happy to help with this as well.

**Comment by jobthomas** [comment]
@tiagonoronha I've seen you work on variation of the starter images. Could I also turn to you for images for grouped products and maybe multiple images per product?

**Comment by tiagonoronha** [comment]
@jobthomas give me examples of what would be needed :)

**Comment by jobthomas** [comment]
Images for:

* At least two variable products (different colours)
* At least two products with more than 1 image (e.g. a hat on someone's face)
* At least two grouped products (e.g. an accessory with a hoodie)

Is that enough @tiagonoronha or do I need to be even more specific? :trollface:

**Comment by mikejolley** [comment]
@jobthomas should we move this to a master thread?

**Comment by jobthomas** [comment]
That sounds good. Would you like me to post that? Happy to take the lead on this part.

**Comment by mikejolley** [comment]
Yes please @jobthomas. Thanks for this :)
