### ISSUE TITLE
Rest API: create new order assigning a customer_id

### ISSUE THREAD

**Issue by ferama** [woocommerce/woocommerce#15722]
I think it should be possible to assign a customer_id during creation of an order via Rest API.

According to the docs http://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order the customer_id field is not supported. 

I noticed that if customer_id field is provided to the object during the API call, WooCommerce store it into database but then a not logged in user can't pay it anymore using the link generated from the admin section -> order details (something like [site.domain]/checkout/order-pay/130?pay_for_order=true&key=wc_order_594a48eb56e6f)

The url will fail with the message "Invalid order. If you have an account please log in and try again"

I investigated further and the issue is related to the "pay_for_order" capability

Use case
=======

1.  Create an order from an APP linking to an existing customer or a created one using the "customers" endpoint
2. Direct user to the "checkout" page generating a checkout link for the order using the template /checkout/order-pay/[order_id]?pay_for_order=true&key=[order_key]

**Comment by mikejolley** [comment]
From 3.1, the user will be prompted to login instead of seeing that error message. This is intentional.

**Comment by ferama** [comment]
Why user should login? I don't want to give credential to the user in use case exposed. Why if the order is created without the cusomer_id field, the link work well and doesn't five any error?

**Comment by mikejolley** [comment]
If the order is assigned to a user, only that user should be able to see it.

**Comment by ferama** [comment]
No one would pay for an order from another user and that page is already public for customer_id=0 (the default customer_id assigned by the create order rest api). This limit a lot the usage of the create order api in my opinion. Maybe I'm wrong and I'm missing some thing :)

I've just developed a simple plugin to bypass this problem, but I would like to find a less hackish and elegant solution
