### ISSUE TITLE
Tabs not showing with custom product type

### ISSUE THREAD

**Issue by danieluyo** [woocommerce/woocommerce#15732]
## Steps to reproduce the issue

1. Register the custom product type after init
2. Add the product type to selector
3. In woocommerce_product_data_tabs add in the general attribute css class name "show_if_custom_product"

## Expected behavior and actual behavior

When I follow those steps, I don't see the "General" tab for any. 

I was expecting show for default + custom_product

## Environment
WooCommerce Version 3.0.8 

The code
```
/**
 * Register the custom product type after init
 */
function register_2017_custom_product_type() {

    class WC_Product_Custom_Product extends WC_Product {

        public function __construct( $product ) {
            parent::__construct( $product );
            $this->product_type = 'custom_product';
        }

    }

}
add_action( 'init', 'register_2017_custom_product_type' );

function add_custom_product_selector( $types ){
    $types[ 'custom_product' ] = __( 'New custom product' );
    return $types;
}
add_filter( 'product_type_selector', 'add_custom_product_selector' );

function hide_attributess_for_custom_product_data_panel( $tabs ) {
    $tabs[ 'general' ][ 'class' ][]    = 'show_if_custom_product';
    $tabs[ 'inventory' ][ 'class' ][]  = 'show_if_custom_product';
    $tabs[ 'shipping' ][ 'class' ][]   = 'hide_if_custom_product';
    $tabs[ 'linked_product' ][ 'class' ][] = 'hide_if_custom_product';
    $tabs[ 'variations' ][ 'class' ][] = 'hide_if_custom_product';
    $tabs[ 'advanced' ][ 'class' ][]   = 'hide_if_custom_product';
    $tabs[ 'attribute' ][ 'class' ][]  = 'hide_if_custom_product';
    return $tabs;
}
add_filter( 'woocommerce_product_data_tabs', 'hide_attributess_for_custom_product_data_panel' , 10, 1);
```

**Comment by WPprodigy** [comment]
That is curious. I can replicate. But you shouldn't need to use the `show_if_*` class on the general tab. If you remove the line, it will show by default.

**Comment by mikejolley** [comment]
In your install/activation script you should create the term for the custom product type (custom_product). Once the term exists, WC can handle tab visibility. Until then, it cannot.

I'd also suggest looking at the source to see where other hide_if show_if classes are found. Your's should be on the same level for it to hide/show correctly. You can append classes with JS if filters do not yet exist.

Thanks
