### ISSUE TITLE
Add visual feedback on Variable Product Edit Screen to indicate stock status when stock is managed via Variations

### ISSUE THREAD

**Issue by thomasmery** [woocommerce/woocommerce#15733]
Just a question about the possibility to have visual feedback in the Admin - On the Product Edit Screen - about the stock status of a Variable product where stock is managed at the variation level

at the moment, as far as I can tell, the user has to look at each variation to be aware of the Parent Product stock status

it would be quite convenient to get the same visual feedback we have right now in the Products List

it might have been discussed before and I saw a few issues around this but not precisely what I'm describing here,

apologies if it's a duplicate

**Comment by WPprodigy** [comment]
To clarify what you are suggesting, you're thinking about there being a stock indicator here for each variation: http://cld.wthms.co/cQq2g ?

**Comment by thomasmery** [comment]
I was actually thinking about the Parent Product Stock Status when based on its variations stock statuses

![image](https://user-images.githubusercontent.com/1503822/27421455-cb6abda6-572a-11e7-9b84-e29c511cd89f.png)

like we can see here

![image](https://user-images.githubusercontent.com/1503822/27421492-f0f1383e-572a-11e7-994c-15310ae41a6f.png)

I know there are design/features discussions around this area

just wanted to point out that at the moment there does not seem to be a quick and easy way to see the parent product status when it's based on its variations stock statuses

let me know if can further clarify

thanks

**Comment by mikejolley** [comment]
There is a separate issue logged for variation UI, and we've already had some designs done for a separate project which we want to start building in q4 :) This should be taken care of then!
