### ISSUE TITLE
CSV server box input too small.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#15735]
See screenshot:

<img width="677" alt="screen shot 2017-06-21 at 11 42 21 am" src="https://user-images.githubusercontent.com/7317227/27408502-db9fc8fe-5691-11e7-8b0c-ac126e34dc71.png">

The text gets cut off halfway through the input, making it hard to use and see what you're doing.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/15739
