### ISSUE TITLE
Suddenly not able to show featured products?

### ISSUE THREAD

**Issue by yupsdk** [woocommerce/woocommerce#15730]
Hello. 

Im having some troubles that i suddenly cant show any featured products? It have been working but suddenly it not showing? Did you change anything that i should know about?

My code for the frontpage:
`<div id="frontpage_products">
        <?php
        $args = array( 'post_type' => 'product', 'meta_key' => '_featured' ,'posts_per_page' => 8,'columns' => '4', 'meta_value' => 'yes' );
        $loop = new WP_Query( $args );
        while ( $loop->have_posts() ) : $loop->the_post(); global $product; ?>
            <li class="product">
                <a href="<?php echo get_permalink( $loop->post->ID ) ?>" title="<?php echo esc_attr($loop->post->post_title ? $loop->post->post_title : $loop->post->ID); ?>">
                <?php woocommerce_show_product_sale_flash( $post, $product ); ?>
                    <?php
                    $percentage = round( ( ( $product->regular_price - $product->sale_price ) / $product->regular_price ) * 100 );
                    if($percentage != 100) {
                        ?>
                        <div id="frontpage_products_percentage">- <?php echo $percentage; ?>%</div>
                        <?php
                    }
                    ?>

                    <?php if (has_post_thumbnail( $loop->post->ID )) echo '<div id="frontpage_products_image">'.get_the_post_thumbnail($loop->post->ID, 'shop_catalog').'</div>'; else echo '<div id="frontpage_products_image"><img src="'.woocommerce_placeholder_img_src().'" alt="Placeholder" width="300px" height="300px" /></div>'; ?>
                <div class="frontpage_products_title"><h3><?php the_title(); ?></h3></div>
                <div class="motangan"><?php echo apply_filters( 'woocommerce_short_description', $post->post_excerpt ) ?></div><br />
                    <div class="frontpage_products_readmore">Læs mere</div><div class="frontpage_products_price"><?php echo $product->get_price_html(); ?></div></a>
            </li>
            <?php
            /**
             * woocommerce_pagination hook
             *
             * @hooked woocommerce_pagination - 10
             * @hooked woocommerce_catalog_ordering - 20
             */
            do_action( 'woocommerce_pagination' );
            ?>
        <?php endwhile; ?>
        <?php wp_reset_query(); ?>
    </div>`

**Comment by mikejolley** [comment]
It's taxonomy based since 3.0. Read the release notes: https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes
