### ISSUE TITLE
I am unable to update rating count through nodejs rest API v3

### ISSUE THREAD

**Issue by kiyos1221** [woocommerce/woocommerce#15738]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Because as stated in the docs, it's read only https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

**Comment by kiyos1221** [comment]
@mikejolley How can I implement product rating using Rest API then,

**Comment by mikejolley** [comment]
Ratings are based on reviews/comments. Not hardcoded.
