### ISSUE TITLE
Products with Visibility set to Hidden are shown in the widgets

### ISSUE THREAD

**Issue by samuelaguilera** [woocommerce/woocommerce#15747]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a Woocommerce Products widget to your sidebar and set it to show Featured Products
2. In the edit product screen, check the featured product checkbox.
3. Now set the product Visibility to Hidden.
 
Another way to reproduce it:

1. Add a Woocommerce Products widget to your sidebar and set it to show On-sale products
2. Set a sale price for the product.
3. Now set the product Visibility to Hidden.

## Expected behavior and actual behavior

The products are hidden from the catalog listings but are shown in the widgets, so the Hidden visibility is being ignored in the widgets.

In WooCommerce 2.x a product with the above setup is hidden from shop catalog and from the widgets too, and that makes sense to me. The Hidden setting should have more priority over any other setting that could affect to the product visibility in the front-end.

## Environment

<details>
`
### WordPress Environment ###

Home URL: http://localhost/wp
Site URL: http://localhost/wp
WC Version: 3.0.9
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.20-2~ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 10 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.9
WC Database Prefix: YUs8_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
suscripción variable (suscripcion-variable)
variable (variable)
variable-subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1061 - /catalogo
Cart: #1062 - /carrito
Checkout: #1063 - /tramitar
My account: #1064 - /gestion-clientes

### Theme ###

Name: Storefront
Version: 2.2.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
The widget has an option; 'show hidden products'. They are hidden for me unless checked :)

**Comment by samuelaguilera** [comment]
I know the widget has that option, but it's showing hidden products **even when that option is not checked**.

As the check for 'show hidden products' is not checked by default I assumed that it was clear, but I have updated the issue title and instructions to replicate the issue to make this clear.

No third-party stuff enabled on the site as explained previously.

**Comment by mikejolley** [comment]
Save a product; the widget is likely cached. I was not able to replicate after changing the option and saving a featured product.

**Comment by samuelaguilera** [comment]
> Save a product; the widget is likely cached.

Do you really think that I spent my time writing the above report for an issue without trying to fix myself it doing something so obvious as saving the product again or setting it as Visible and Hidden again to see if that helps? Give me a little more credit Mike...

I'm not using any caching in the site or server. Are you referring to something cached by WC? If so, maybe WC should clear the cache after updates. And how it's stored? I tried to delete all transients using the System Status -> Tools page and but that doesn't help.

Also tried to delete the widget, and add it again. Same result. The issue is not only happening with already created products. If I add a new product the new product is also being displayed in the widgets.

The issue only arises after upgrading WC 2.x to latest 3.0.9

Maybe it's an edge case, but the issue is real.

**Comment by mikejolley** [comment]
Can you debug around this line; https://github.com/woocommerce/woocommerce/blob/master/includes/widgets/class-wc-widget-products.php#L110-L118

I.e. see if the option is set, and see if you can output everything to prove you're not seeing cached output?

FYI I'm only testing on master which you indicated had the issue.

**Comment by mikejolley** [comment]
Products: https://dl.dropboxusercontent.com/s/rqiysx1vaxvi6pz/2017-06-23%20at%2016.12.png

Output: https://dl.dropboxusercontent.com/s/tyef0b297larf57/2017-06-23%20at%2016.12%20%281%29.png

**Comment by mikejolley** [comment]
Also, did you run the data upgrader after 3.0.x? Featured moved to a taxonomy (from meta), don't know if you read about that.

> Do you really think that I spent my time writing the above report for an issue without trying to fix myself it doing something so obvious as saving the product again or setting it as Visible and Hidden again to see if that helps? Give me a little more credit Mike...

It's not my job to judge your ability. I just tested using the steps you provided.

**Comment by samuelaguilera** [comment]
You know what? My job is not trying to convince you about an issue or doing debugging for you. If you want to discard the issue thinking I'm so dumb to not doing the upgrade after updating to 3.x, that I marked this was reproduced on master but not did it, or whatever, do what you want, if any other WC users are experiencing the problem without even noticing it that's not my problem. I'll find the solution for the issue by myself, that will be nicer than spending my time talking to a wall.

You can close the issue, oh wait! No need to do it because that was what you did already before asking for any further details.

**Comment by mikejolley** [comment]
I really don't know why you're taking this personally...

Closing an issue does not mean we don't read replies here. Please understand I have to work through a whole bunch of new issues daily and triage them for the team to work on. If I left them all open waiting for feedback things would quickly become unmanageable. 

You can see my screenshots above where I attempted to replicate the issue based on your instructions. It worked. I showed you the code which controls it so you could do additional debug if needed.  I can imagine that if you're switching between old and new versions, whilst saving data under both something could get out of sync, and the update method may not have fired for the products you're testing.

>  If you want to discard the issue thinking I'm so dumb to not doing the upgrade after updating to 3.x

3.0.x moved visibility/featured from meta to terms.This is the update function Id expect to handle it:

https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L1066-L1068

Maybe you can confirm the products which are not displaying correctly have these terms?

**Comment by emoop** [comment]
Hi! In my case the hidden products also were shown in Products Widget. My solution to the problem is:
add_filter('woocommerce_products_widget_query_args','hidde_no_img');
function hidde_no_img($query_args){
    $query_args['meta_query'][] = array(
				'key'     => '_thumbnail_id',
				'value'   => '',
				'compare' => '!=',
			);
	return 	 $query_args;	
}
, because my hidden products don't have images.
But of course every custom field in postmeta table would work.
Cheers

**Comment by ArtDubrovsky** [comment]
Same thing with 3.2.5: Visibility set to Hidden, but it is shown in Widget New Products. The setting date to early time is only solution for me.

**Comment by kerojohan** [comment]
Same in 3.2.6, tag cloud is showind tags of hidden products.

**Comment by mikejolley** [comment]
Tag cloud is not related to this option/widget.
