### ISSUE TITLE
Custom (scripted) attributes on variations don't work properly when parent doesn't have them

### ISSUE THREAD

**Issue by Grezvany13** [woocommerce/woocommerce#15743]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Have a custom attribute which is added through PHP especially for Product Variations
```php
<?php
function custom_product_after_variable_attributes($loop, $variation_data, $variation)
{
    woocommerce_wp_text_input([
        'id' => 'custom_attr['.$loop.']',
        'label' => __('Custom Attr', 'woocommerce'),
        'value' => array_key_exists('attribute_custom_attr', $variation_data) ? $variation_data['attribute_custom_attr'] : '',
    ]);
}
add_action('woocommerce_product_after_variable_attributes', 'custom_product_after_variable_attributes', 10, 3);

function custom_save_product_variation($variation_id, $i)
{
    $variation = wc_get_product($variation_id);
    $attributes = $variation->get_attributes();

    if (array_key_exists('custom_attr', $_POST) && array_key_exists($i, $_POST['custom_attr'])) {
        $attributes['custom_attr'] = wc_clean($_POST['custom_attr'][$i]);
    }

    if (0 !== count($attributes)) {
        $variation->set_attributes($attributes);
        $variation->save();
    }
}
add_action('woocommerce_save_product_variation', 'custom_save_product_variation', 10, 2);
```
2. Create a new Product, and add a Variation
3. Add a value to the "Custom Attr" field
4. Use ```$variant->get_attributes();``` or ```$variant->get_attribute('custom_attr');``` to retrieve the value.

## Expected behavior and actual behavior

I see that the custom attribute is saved in the database for the Variant and it shows the value in Variation options.

However when calling ``` $variant->get_attributes(); ```, it does not include 'attribute_custom_attr' or 'custom_attr'.

The reason seems to be that variation attributes are only allowed to show up when the parent (product) also have these attributes.

When I modify [wc-product-functions.php#L642](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-product-functions.php#L642) to not check in ```$found_parent_attributes``` then everything works as expected.

## Environment

<details>
```
N/A
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
> The reason seems to be that variation attributes are only allowed to show up when the parent (product) also have these attributes.

This is correct. Assign them to the parent first.

**Comment by Grezvany13** [comment]
I can understand the reasoning of the current setup and on how attributes are used. Although it's the only possible method to add additional data to products (and specifically variants) within Woocommerce.

Of course it's possible to use post_meta to add and retrieve data, although these won't be available within the Woocommerce ecosystem and requires a lot of extra DB queries. Additionally it's currently not possible to "inject" additional data into the WC_Product object for easy access.

I'm aware it's not a bug, but rather a missing feature which I feel should be available, in any form.

**Comment by mikejolley** [comment]
All CRUD objects actually support custom meta data through the new API. See the WC_Data class for available methods. Attributes should not be used for meta data.
