### ISSUE TITLE
Name Changing when placing order

### ISSUE THREAD

**Issue by LadySlynn** [woocommerce/woocommerce#15741]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Login to Admin,Shop Manager, or Editor Account
2. Place an Order using the front end shop with a name that isn't yours

## Expected behavior and actual behavior

When I follow those steps, I see... my name changed to whoever I placed the order as

I was expecting... to see my own name

## Explanation
We frequently place phone orders while logged into our own accounts on the front end shop rather than the backend.  I am the only one the really uses the backend of wordpress and my co-workers are not comfortable doing it the other way (placing an order under WooCommerce>Orders>New Order)
You'll notice we are not on the current version of WordPress but our Test Site is (still testing before doing an update to the newest version), and I have tested it there and it does the same thing.  Is there an easy fix for this?

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://bulletcentral.com
Site URL: https://bulletcentral.com
WC Version: 3.0.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: ❌ 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 65 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.1
WC Database Prefix: wp_j63rfqj01t_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

ZitchDog Sort Shipping by Price: by Saralynn – .01
AuctionInc ShippingCalc for WooCommerce: by Paid
Inc. – 1.13

Autoptimize: by Frank Goossens (futtta) – 2.2.0
Anti-Spam by CleanTalk: by СleanTalk  – 5.67.3
Converge Gateway for WooCommerce: by Jacob Davidson – 2.0.0
Contact Form 7: by Takayuki Miyoshi – 4.8
Easy Table: by Takien – 1.6
Envato WordPress Toolkit: by Envato – 1.7.3
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp: by MailChimp – 1.5.7
WooCommerce Product Filter: by Mihajlovic Nenad – 6.2.3
ReadyShipper WooCommerce API: by TrueShip
LLC – 1.0.5

Really Simple SSL: by Rogier Lankhorst – 2.5.17
Scripts-To-Footer: by Joshua David Nelson – 0.6.1
U-Design WooCommerce Integration: by Andon – 2.1.16
U-Design Shortcode Insert Button: by Andon – 1.1.7
WC Password Strength Settings: by Daniel Santoro – 1.1.0
WC Return products: by Paco Castillo – 1.5
Woo Import Export: by VJInfotech – 2.4
WooChimp: by RightPress – 2.2.1
WooCommerce Anti Fraud: by WooCommerce – 1.0.11
WooCommerce Extended Coupon Features: by Soft79 – 2.5.1
WooCommerce Cart Tab: by jameskoster – 1.1.1
WooCommerce - Country Based Payments: by Ivan Paulin – 1.1.8
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.2
WooCommerce Product Badge: by Terry Tsang – 1.0.4
WooCommerce Product Bundle: by wplive – 1.5
WooCommerce FedEx Shipping: by WooCommerce – 3.4.8 – 3.4.9 is available
Woocommerce Shipping Gateway per Product: by Dreamfox Media – 1.2.6
WooCommerce: by Automattic – 3.0.7 – 3.0.8 is available
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 4.9
YITH WooCommerce Badge Management: by YITHEMES – 1.3.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)


### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/

### Theme ###

Name: U-Design Child
Version: 2.10.7
Author URL: http://themeforest.net/user/andondesign/portfolio?ref=AndonDesign
Child Theme: ✔
Parent Theme Name: U-Design
Parent Theme Version: 2.12.3
Parent Theme Author URL: https://themeforest.net/user/andondesign/portfolio?ref=AndonDesign
WooCommerce Support: ✔

### Templates ###

Overrides: U-design Child/woocommerce/cart/cart-shipping.php
U-design Child/woocommerce/checkout/thankyou.php
U-design Child/woocommerce/single-product/rating.php
U-design Child/woocommerce/single-product-reviews.php

````
</details>

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
This is why we discourage checking out as a customer - your user account will inherit addresses, name settings, even credit card tokens with some gateways. There is no way to know if you want this to happen or not, since the checkout is intended for customers.

There is a filter to disable customer updates but it could affect all users. Custom code can be added to do this.

If you can, try a user switching plugin so you can checkout *as* the customer, if they have an account.

**Comment by LadySlynn** [comment]
Thank you! I don’t think we want credit tokens being inherited, I will inform my coworkers to use a different account.  Thank you again!
