### ISSUE TITLE
Weight in API is not clear

### ISSUE THREAD

**Issue by natesholland** [woocommerce/woocommerce#15746]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Make an API request for a product like described [here](http://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-product)
2. Look at the weight. Is it in KG or LBs?

## Expected behavior and actual behavior

According to the API documentation here the weight is in kgs: http://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

But in the API it has me filling out the weight in lbs. The number I get back is the same number (which shouldn't be). So my question is which is correct? If the documentation is wrong and it should be weight in lbs I can make a quick PR to update the documentation.

## Environment

<details>
```

WC version:		3.0.8
WP version:		4.7.5
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		–
WP cron:		
Language:		en_US
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by claudiosanches** [comment]
> According to the API documentation here the weight is in kgs: http://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

In fact this need to be fixed on REST API docs, since is generated automatically.

But it use your store weight unit settings, you can check what unit are you using checking the schema with:

```
OPTIONS /wp-json/wc/v2/products
```

**Comment by claudiosanches** [comment]
Docs updated. Thanks.

**Comment by natesholland** [comment]
I figured it out, I think you meant to check `/wp-json/wc/v2/settings/products` to see what value was being used.

**Comment by claudiosanches** [comment]
@natesholland sorry but I mean and I'm sure for what I'm saying is for you use `OPTIONS /wp-json/wc/v2/products`, even more because works on v1 too.

**Comment by thealexbaron** [comment]
Is it still required to rely on the `v2` endpoint for my `v3` implementation? I see no way in the v3 docs to determine the weight unit.

**Comment by claudiosanches** [comment]
@thealexbaron there's the same endpoint for `v3`, weight unit depends on the store's settings.
