### ISSUE TITLE
Footer design changes 

### ISSUE THREAD

**Issue by jano2165** [woocommerce/woocommerce#15749]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by jano2165** [comment]
Basically, I've made sure after testing that the WooCommerce plugin alone is enabled, this issue occurs.  Basically, when I'm on the home page my footer is as it is expected to be, however, when I access any Shop/WooCommerce related pages my footer changes in design as per Image 2. 
![1](https://user-images.githubusercontent.com/28293583/27467847-3a9cf9ba-5829-11e7-9df1-56b348706417.PNG)
![2](https://user-images.githubusercontent.com/28293583/27467848-3aa053ee-5829-11e7-8951-a42b2ac53431.PNG)

**Comment by WPprodigy** [comment]
I am unsure why the WooCommerce plugin is causing this, but your theme has control over these styles and is ultimately where this needs to be resolved.

Contact the theme authors.

**Comment by mikejolley** [comment]
> This bug happens with a default WordPress theme active, or Storefront

I don't think that is true or should be checked off.

It's a style conflict. Clearly a style used in WooCommerce shares a classname with the widget area in the footer or your theme.

If you provided a link to the site I could tell you what style rule it is, and see if it's specific enough to be a theme issue or a wc issue, but you've provided no status report or website link. Feel free to reply back.

**Comment by jano2165** [comment]
Hello,

My link is   www.NaturalOnlineTherapy.com<http://www.NaturalOnlineTherapy.com>  , you will see the difference with the home page and the appointments page.

thanks

**Comment by mikejolley** [comment]
This style comes from your theme it seems: https://dl.dropboxusercontent.com/s/iha71z63s181vaf/2017-06-23%20at%2015.03.png
