### ISSUE TITLE
quick checkout add-to-cart broken 

### ISSUE THREAD

**Issue by fort** [woocommerce/woocommerce#15750]
From **2.7.0-beta-3** in file templates/single-product/add-to-cart/simple.php **line: 48** input element
`<input type="hidden" name="add-to-cart" value="<?php echo esc_attr( $product->get_id() ); ?>" />` element is missed. 

woocommerce-quick-checkout plugin handles click event on `<button>` add_to_cart/buyNow element and serialized form is sent to server. But  woocommerce-quick-checkout(
`woocommerce-quick-checkout/classes/woocommerce-quick-checkout-engine.php` line:248
) ajax endpoint expects product_id is included into POST with key **add-to-cart**. But jquery serizlize method does not pass element's type="button" and `<button>` where is **product_id** is stored. And the script is broken.
Before **2.7.0-beta-3** release 
file file templates/single-product/add-to-cart/simple.php contained
`<input type="hidden" name="add-to-cart" value="<?php echo esc_attr( $product->get_id() ); ?>" />`

**Comment by fort** [comment]
It issue appears with WooCommerce Quick Checkout before Version 1.8.4

**Comment by mikejolley** [comment]
Report to WooCommerce Quick Checkout if they need to add WC 3.0 compatibility.

https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes
