### ISSUE TITLE
Feature request: shipping method extra fields

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#15753]
Hi there, on a project I developed ( [VINHA](https://www.vinha.co.uk/) ) I had the need to have specific checkout fields depending on the chosen shipping method, just like when you choose a credit card payment option and you get the credit card fields.

I did this by extending the Shipping Methods and adding extra php/html code on the cart-shipping.php template file, that would check if there are extra fields for each method and render them (we could possibly just have hooked into "woocommerce_after_shipping_rate" also), and then by hooking into "woocommerce_checkout_update_order_meta" to save those fields alongside the order.

I also added a Shipping Method public description, that WooCommerce also doesn't have.

![image](https://user-images.githubusercontent.com/6853605/27475701-0c656cb0-57fe-11e7-9ea5-5c125cfd2bff.png)

Today people are adding fields to the checkout form to achieve this, but those fields are not tied to the specific needs of each shipping method. One method may need some input and other don't.

My code is fairly simple and not that extendable because it was made just for this one project, but I think this could be a very good idea for the future of the WooCommerce core, by doing it similarly to payment options:
- Shipping method public description
- Shipping method specific/extra fields

Usage examples:
- Choose delivery day
- Choose time slot
- Choose pick-up point
- Enter additional instructions for the delivery guy
- Pick extra delivery premium services (that could have an extra fee attached to this*)

* this kind of more complex stuff could be added later on, on a second phase of this feature implementation

**Comment by s3rgiosan** [comment]
Yes, please!

I also need this functionality for the shipping method plugin that I am developing for a Portuguese delivery service that works with pickup points.

**Comment by vlaskiz** [comment]
Pick-up point/location if local pickup is selected is very much needed.

**Comment by webdados** [comment]
@vlaskiz abstracting this into "specific fields per shipping method" support would solve all these issues.

**Comment by mikejolley** [comment]
Given this is already possible and core methods do not need this, I'm not sure this should be much of a priority tbh. Have you logged on the ideas board?

**Comment by webdados** [comment]
This is possible as a workaround. My suggestion was to make it available to any developer that needs to implement their own methods and need extra fields.

Regarding core methods, "Local pickup" for example could use an (optional, set by the store owner) field for selecting locations.

I've also mentioned "description" just like payment gateways have. I also think this could also be a good enhancement.


You are right, I should probably use the Ideas board for this, and not a github issue, but I think I may have a problem here...
![image](https://user-images.githubusercontent.com/6853605/27481015-7ea84ee6-5812-11e7-8ca6-83a62ec9a050.png)

**Comment by mikejolley** [comment]
Been spamming :p ?

I can log it on there for you perhaps, unless you were interested in working on it for your use case and submitting a separate PR to contribute to?

**Comment by webdados** [comment]
I don't remember spamming there at all :-D
In the meanwhile I recovered the login with my main username on wordpress.com / woocommerce.com (whatever...) and will submit this as an idea.

**Comment by claudiosanches** [comment]
Related to #9797

**Comment by WPprodigy** [comment]
I'm not sure how I feel about about adding all these settings/options to core. It will just crowd up the available options and make shipping more confusing for people (Decisions, not options.). Seems better left to plugins IMO. That said, I think core should make it as easy as possible for a plugin to add in these extra fields.

SkyVerge recently re-working their local pickup plus extension that added extra shipping fields like this without overriding templates. So I'm thinking they may have some thoughts on this. CC'ing @bekarice

**Comment by webdados** [comment]
@WPprodigy I'm just suggesting that shipping methods have the same functionality as payment gateways: description and fields.

**Comment by mikejolley** [comment]
Payment methods **need** fields, and if they have fields e.g. credit card fields, they are all pretty similar.

I don't think it's common to need fields for shipping methods so a consistent API is probably not possible, and not needed by core.

**Comment by bekarice** [comment]
Shipping fields can be added via the `woocommerce_after_shipping_rate` action and validated via the `woocommerce_after_checkout_validation` action. I agree with MJ here -- as there are no standard fields needed for most methods, this doesn't really feel like it makes sense for core, and rather customizations or new methods should add their own fields when needed (`woocommerce_form_field()` buys you plenty).

**Comment by webdados** [comment]
@bekarice yes, I've used that approach before. I guess I'll write a tutorial about that for the community sometime soon.

**Comment by FreeRiderNSK** [comment]
Good afternoon! Could you share your code? I need to add 3 input fields for some delivery methods.
