### ISSUE TITLE
Layout subcategorie

### ISSUE THREAD

**Issue by PiafCreation** [woocommerce/woocommerce#15756]
Hi team,

    On my website: http://www.kit-aero.fr, I use Woocommerce just as a catalog for my product, no sale, no payment.
    I would like to display only the sub-category not the products when I click on the category in my shop of Woocommerce.
    I know there is a setting for that in Woocommerce.
    But when I choose only sub-categories visible in a category there is no difference. I have sub-categories and products.
    I don’t understand why, can you help me ?

    The problem appears before the update of Woocommerce Version 3.0.8 ( it’s the same after)
    I have the theme The7 (the last version Version : 5.2.2). Since I installed Woocommerce, it’s the same problem. I have contacted the support team of the theme The7, it’s seem it’s a Woocommerce’issue.

    Thanks a lot

**Comment by mikejolley** [comment]
```
## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently
```

Follow the steps on the new issue form to rule out the theme and extensions. This is not a support area; please confirm actual, reproducible bugs before logging.
