### ISSUE TITLE
Problem with encoding with CSV files

### ISSUE THREAD

**Issue by sebas** [woocommerce/woocommerce#15758]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
Considering that you already have products with content that uses characters like á é í.

1. Go to products
2. Click export
3. Select export all columns, select export all products. Click Generate CSV.
4. Open exported file with Excel.

## Expected behavior and actual behavior

When I follow those steps, I see...
rÃ¡pido instead of rápido on Excel.

I was expecting...
rápido instead of rÃ¡pido on Excel.

## Environment

<details>
`
### WordPress Environment ###

Home URL: https://staging.subastasenmexico.com
Site URL: https://staging.subastasenmexico.com
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.1.6
PHP Version: 7.1.6
PHP Post Max Size: 128 MB
PHP Time Limit: 360
PHP Max Input Vars: 1500
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Query Monitor: por John Blackbourn – 2.13.4
User Switching in Admin Bar: por Mark Wilkinson – 1.1.1
Autoptimize: por Frank Goossens (futtta) – 2.2.1
CB Change Mail Sender: por Md Abul Bashar – 1.1
Admin Columns: por AdminColumns.com – 3.0.1
Contact Form 7: por Takayuki Miyoshi – 4.8
Disable WooCommerce Reviews: por pipdig – 1.1
Easy Theme and Plugin Upgrades: por Chris Jean – 2.0.0
EWWW Image Optimizer: por Shane Bishop – 3.4.1
File Manager: por  – 4.1.6
Flamingo: por Takayuki Miyoshi – 1.6
Fusion Builder: por ThemeFusion – 1.1.6
Fusion Core: por ThemeFusion – 3.1.6
Google Analytics for WordPress by MonsterInsights: por MonsterInsights – 6.2.0
InfiniteWP - Client: por Revmakx – 1.6.4
Custom Login Page Customizer: por Hardeep Asrani – 1.1.0
MailChimp for WooCommerce: por MailChimp – 2.0.0
MailChimp para WordPress: por ibericode – 4.1.4
Openpay SPEI Plugin: por Federico Balderas – 1.3.0
OptinMonster API: por OptinMonster Team – 1.2.0
Profile Builder - WooCommerce Sync Add-on: por Cozmoslabs
Adrian Spiac – 1.4.7

PDF Viewer: por Envigeek Web Services – 0.1
Profile Builder Pro: por Cozmoslabs
Madalin Ungureanu
Antohe Cristian
Barina Gabriel
Mihai Iova – 2.6.4

Really Simple SSL: por Rogier Lankhorst – 2.5.17
Remove Query Strings From Static Resources: por Speed Up My Website
Your WP Expert – 1.4

Restrict Content Pro: por Restrict Content Pro Team – 2.8.6
SO Hide SEO Bloat: por SO WP – 3.0.0
WP woocommerce featured product by category: por WP Online Support – 1.1
WooCommerce Display Products by Tags: por Sebs Studio – 1.0.0
Tracking Code Manager: por IntellyWP – 1.11.1
User Switching: por John Blackbourn – 1.0.9
WooCommerce Google Analytics Integration: por WooCommerce – 1.4.3
WooCommerce: por Automattic – 3.1.0-rc.1
Yoast SEO: por Equipo Yoast – 4.9
WP Mail Logging: por Christian Zöller – 1.8.1
YITH Live Chat Premium: por YITHEMES – 1.2.1
YITH Auctions for WooCommerce Premium: por YITHEMES – 1.1.4.15s
YITH WooCommerce Brands Add-on Premium: por Yithemes – 1.1.1
YITH WooCommerce Multi Vendor Premium: por YITHEMES – 2.0.1s
YITH WooCommerce Terms & Conditions Popup: por Yithemes – 1.1.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: MXN ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: auction (auction)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
ywf_deposit (ywf_deposit)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base de la tienda: #469 - /listado-productos-woocommerce/
Carrito: #6 - /carrito/
Finalizar compra: #7 - /finalizar-compra/
Mi cuenta: ❌ La página no contiene el shortcode.

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.1.6
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada-Child-Theme/woocommerce/archive-product.php
La  version 3.0.3 de Avada-Child-Theme/woocommerce/cart/cart.php está obsoleta. La versión del núcleo es la 3.1.0
Avada-Child-Theme/woocommerce/checkout/form-pay.php
Avada-Child-Theme/woocommerce/checkout/review-order.php
Avada-Child-Theme/woocommerce/checkout/thankyou.php
Avada-Child-Theme/woocommerce/content-single-product.php
Avada-Child-Theme/woocommerce/loop/loop-start.php
Avada-Child-Theme/woocommerce/loop/price.php
Avada-Child-Theme/woocommerce/single-product/add-to-cart/variable.php
Avada-Child-Theme/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada-Child-Theme/woocommerce/single-product/meta.php
La  version 3.0.2 de Avada-Child-Theme/woocommerce/single-product/product-image.php está obsoleta. La versión del núcleo es la 3.1.0
Avada-Child-Theme/woocommerce/single-product/related.php
Avada-Child-Theme/woocommerce/single-product/short-description.php
Avada-Child-Theme/woocommerce/single-product/tabs/additional-information.php
Avada-Child-Theme/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌Aprende cómo actualizar
`
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Can you add this and test? https://github.com/woocommerce/woocommerce/issues/15759

**Comment by sebas** [comment]
So I opened the exported file on Sheets from Google Drive and it works.

But I opened the exported file, using an export done with woocommerce-master and I still see the problem with the encoding.

If I go with the method described using the wizard, that works.

**Comment by sebas** [comment]
It works with Numbers.

**Comment by claudiosanches** [comment]
@sebas it's possible test with master only now. But I had some friends testing too and looks like is fixed.

**Comment by sebas** [comment]
You are correct it is working now.

Thanks for your help.

**Comment by claudiosanches** [comment]
@sebas thank you for let us know about this issue :)
