### ISSUE TITLE
Multi-factor price for wordpress woocommerce products

### ISSUE THREAD

**Issue by moosavi12** [woocommerce/woocommerce#15767]
my products price have 2 factor: Money and percent And I want to display both of them for customers for example: 200$ + 6% It's not like taxes and it's not related to the price.

i just need to get orders and don't use online payment. so just want to show it.

but i have two problem: 1- woocommerce just get one factor for price. 2-don't support Multi-factor price.

**Comment by mikejolley** [comment]
Correct it's not supported, meaning you'll need a developer to code this for you custom. Sounds edge case but you can also log an idea on ideas.woocommerce.com

Thanks
