### ISSUE TITLE
Feature: free shipping requires shipping class X

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#15764]
![](http://cld.wthms.co/YeNKlN+)

### New Feature

A very common question I see asked is "How do a set up free shipping for specific products". If you want to use only core to do this, the answer involves using Flat Rate and Shipping Classes. But it can get messy, especially if you don't have other flat rates costs. Plus, the shipping method then reads `Flat Rate: $0`. Other methods require another plugin or [custom code](https://metorik.com/blog/apply-free-shipping-to-certain-products-in-woocommerce), which is out of the question for most users.

I'm proposing we add another option to the Free Shipping settings, one that restricts Free Shipping to only when a specific shipping class is in the cart. This would only work if all products in the cart have this shipping class, or all products in the "package" (if the cart has been split up for example by another plugin).

____

### Refactoring ideas the current settings.

The way those four requirements are structured could quickly get out of hand by adding in another setting though. So I'd also propose restructuring the settings a little. Maybe the "and/or" options aren't even necessary? I can't say I've really seen them used before. Free shipping via a shipping class is a far greater use case than "minimum amount and/or coupon".

If we do need to keep all the current options, maybe splitting it into two sections with repeatable fields would keep it clear and perhaps less confusing? How ZD does this comes to mind: http://cld.wthms.co/Gw8B3R. The first section would be "meets all of the conditions", and the second would be "meet any...". Of course the UX and wording could be altered, but thats the general idea that came to mind. Though I'd prefer slimming down the options and avoiding that if possible.

Alternatively, if we could get rid of those two "and/or" options things would be simplified a lot. For starters, does the shipping method even need to declare support for free shipping coupons? I feel like store owners want that coupon setting to override any other restrictions already. So if there is free shipping in the zone, just show it if the coupon says so. If ya'll do think people find this setting useful though, then removing it from the main select and just using a "Support Free Shipping Coupon" setting checkbox could be the answer.

Anyways, just something to think about.

**Comment by mikejolley** [comment]
There is also https://docs.woocommerce.com/document/woocommerce-advanced-shipping-packages/ / http://jeroensormani.com/splitting-shipping-packages-in-woocommerce/

**Comment by WPprodigy** [comment]
I don't think we need to add the splitting ability to core, can just keep this simple. If all items in the cart have shipping class X, then show free shipping.

If you want some items in the cart to cost $0 and some to cost money, then flat rate covers that need pretty well.

**Comment by mikejolley** [comment]
"simple" :p What you're proposing sounds more complicated tbh. It also does not work very well when you're mixing 'free to ship' items with non free to ship items?

**Comment by WPprodigy** [comment]
When there are non free to ship items in the cart, then this condition would just fail and the Free Shipping method wouldn't be shown. It's an "all or nothing" scenario that I had in mind at first. Cart splitting would continue to need to be done through other plugins.

Consider this scenario. Site is using USPS for shipping all products, but you have one or two products that you want to ship to the US for free if they are all that is purchased. Now try setting that up with flat rate - you can't.

The complicated part comes in when looking at the current "free shipping requires" settings, which seems to need some refactoring.

**Comment by mikejolley** [comment]
> Consider this scenario. Site is using USPS for shipping all products, but you have one or two products that you want to ship to the US for free if they are all that is purchased. Now try setting that up with flat rate - you can't.

With your proposal, as soon as a non-free item is added to cart, it will quote USPS for ALL ITEMS IN THE CART. Fair? :)

**Comment by WPprodigy** [comment]
Hmm, yeah. I know about cart splitting, but was hoping to leave that out and keep this simple.

The more I think about scenarios though, maybe basic cart splitting for the free shipping items would make sense and still be relatively simple from the user's standpoint.

**Comment by mikejolley** [comment]
I think cart splitting is better, but I'm not sure it's core ready yet.

**Comment by mikejolley** [comment]
@WPprodigy Since there is an extension solution, let's leave for ideas board. It has 1 vote I can find though :P http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/11113716-disallow-flat-rate-shipping-on-product-without-shi
