### ISSUE TITLE
Sugestion: Combine all the JS files in one file

### ISSUE THREAD

**Issue by a1ur3l** [woocommerce/woocommerce#15762]
Hello,
I don't know if the place of this should be here, but i will try my luck,
Have you think about combining all the JS files in one in order to reduce the number of them (if there are specific scripts for cart / account or other pages?

for eg 3.0.8 has:
 5 js files with it loads on home page (on my case)
/woocommerce/assets/js/frontend/add-to-cart.min.js?ver=3.0.8
/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js?ver=2.70
/woocommerce/assets/js/js-cookie/js.cookie.min.js?ver=2.1.4
/woocommerce/assets/js/frontend/woocommerce.min.js?ver=3.0.8
/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=3.0.8

8 on category & subcategory pages
/woocommerce/assets/js/frontend/add-to-cart.min.js?ver=3.0.8
/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js?ver=2.70
/woocommerce/assets/js/js-cookie/js.cookie.min.js?ver=2.1.4
/woocommerce/assets/js/frontend/woocommerce.min.js?ver=3.0.8
/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=3.0.8
/woocommerce/assets/js/jquery-ui-touch-punch/jquery-ui-touch-punch.min.js?ver=3.0.8
/woocommerce/assets/js/accounting/accounting.min.js?ver=0.4.2
/woocommerce/assets/js/frontend/price-slider.min.js?ver=3.0.8

10 on product page
/woocommerce/assets/js/frontend/add-to-cart.min.js?ver=3.0.8
/woocommerce/assets/js/zoom/jquery.zoom.min.js?ver=1.7.15
/woocommerce/assets/js/flexslider/jquery.flexslider.min.js?ver=2.6.1
/woocommerce/assets/js/photoswipe/photoswipe.min.js?ver=4.1.1
/woocommerce/assets/js/photoswipe/photoswipe-ui-default.min.js?ver=4.1.1
/woocommerce/assets/js/frontend/single-product.min.js?ver=3.0.8
/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js?ver=2.70
/woocommerce/assets/js/js-cookie/js.cookie.min.js?ver=2.1.4
/woocommerce/assets/js/frontend/woocommerce.min.js?ver=3.0.8
/woocommerce/assets/js/frontend/cart-fragments.min.js?ver=3.0.8

Thanks and sorry if this shouldn't be here.

**Comment by WPprodigy** [comment]
There are benefits/dis-benefits to both merging all into one and using them separately. In the past this was done to prevent multiple requests, but with HTTP 2 that's not longer the case as far as I understand.

Different scripts are also required on different pages, as you noted above. If we were to merge all into one for each page, that would be, say, 5+ different large JS files that would need to be downloaded by the browser then locally cached. Or, it would be one very large file with code that will potentially never be needed. Whereas splitting them up, the browser can locally cache individual ones.

That's what comes to mind at least, without me doing any research on it. I don't think this is something core would be interested in doing anytime soon, but Mike would know better ¯\\_(ツ)_\/¯

This is certainly something you can do on your websites though, and I've seen many that do. Lots of CDN services and plugins offer this as an option. (Careful though, as it can cause conflicts if done incorrectly. )

**Comment by mikejolley** [comment]
Combining them would mean we cannot:

- Load scripts only relevant to the current page
- Allow developers to unhook certain scripts only (rather than all of them).

The 2nd is most important. Scripts/plugins/themes may need to disable certain parts e.g. gallery scripts.

Use a minify plugin :)
