### ISSUE TITLE
Get code indentation/alignment under control

### ISSUE THREAD

**Issue by markjaquith** [woocommerce/woocommerce#15761]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)

## The issue

The indentation and alignment in the WooCommerce code is all over the place. Mixed use of tabs and spaces to indent, plus the use of tabs (!?!?) to attempt alignment of code (which of course fails unless your editor is configured to draw tabs as a specific length).

<img width="789" alt="screen shot 2017-06-23 at 3 10 55 pm" src="https://user-images.githubusercontent.com/353790/27497046-b112b132-5826-11e7-86be-5aab49ba7e0e.png">

I recommend using tabs to indent code, and spaces to align code within an indentation level. That way, it'll look orderly and aligned on all editors. [https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards](The WordPress Coding Standards) project can help automate this cleanup (use the current `master` though, as it has a lot of fixes since the last stable release).

**Comment by claudiosanches** [comment]
I've packed all the files a few versions ago, even so after several Pull Requests this is happening over again, but for sure it's time to setup our phpcs ruleset to start catch it.

**Comment by claudiosanches** [comment]
Closing in favor of #15798
