### ISSUE TITLE
Download Links are not immediately generated

### ISSUE THREAD

**Issue by accetturo** [woocommerce/woocommerce#15768]
## Prerequisites
Set Download method to Redirect, Host offsite on S3 and direct link to them in the product listing.

We are using the latest WooCommerce and getting about 60 tickets a day in a high volume WooCommerce store that people are being redirected back to the homepage when clicking the download links in the thank you confirmation emails. 

By the time we see the emails tickets and click the links, they work and the customer confirms they work so its just the initial period after purchase, maybe 1-3 minutes that they do not seem to have been set to redirect.

Is there some sort of Cron powering this struggling to handle the volume of sales? We have a high-performance setup on a large dedicated server using a LAMP w/ NGINX + PHP7/FPM setup.

**Comment by accetturo** [comment]
I should also note you will need to replicate a high volume situation, at least 3000 orders a day of downloadable products which may be difficult.

**Comment by mikejolley** [comment]
@accetturo WooCommerce does not generate or process download links as you describe. It generates permissions, and without permissions nothing would be added to the email, so this is working.

Maybe you're using an extension to give access to s3?

**Comment by accetturo** [comment]
No extension, Just direct link right into the product options. I think it has to do with the wait until completed status before granting access(no processing), maybe at times PayPal IPN might not be switching the status

**Comment by accetturo** [comment]
Somewhere in here, something is not lined up. They should 100% be completing the order as they are sent to the Thank you page and dispatched the email. Not only that, the link added to the emails is correct. But, we have gotten a ton of tickets with people replying directly to the confirmation with the download links, saying the links are not working and directing them back to the homepage. It's interesting, because sometime's they will say anything past Download #4 or #5, etc dont work.

By the time we see the tickets, we click the links and they work. We tell the customer they should work now, and its fixed.  This only happens during extremely busy times

**Comment by mikejolley** [comment]
Status does not matter; if the user has a download link, it's been generated, and MUST be valid already. S3 links usually require some type of auth or key - are you sure there is nothing else involved here? i.e. protection on the links..

**Comment by accetturo** [comment]
No the links are public, I could share them here and you could download them if you wanted without any keys or protection. We just use the redirect only method to track download counts for refund / return processing

**Comment by mikejolley** [comment]
So again; if the links are public, and the WC download links are inside the email, the permissions are granted and thus download links should not go to the homepage. 

Have you been able to replicate this one yourself, or just customers? Could it be an issue in the customers email client for example breaking long links?

or am I misunderstanding the issue as written and do the emails to customers NOT have the download links at first?

**Comment by mikejolley** [comment]
Also important; download errors e.g. from bad links do not redirect to the homepage, they show an error message:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-download-handler.php#L405

**Comment by accetturo** [comment]
From what I can tell its email only, and its possible that SendGrid link tracking could be causing some sort of breakage. The links are whitelabeled using a CNAME to links.domain.com and tracked for deliverability purposes, but we really don't use it so I will turn it off to see if that could be the issue then get back to you.

Also, we have not been able to replicate this and by the time we see the ticket, which many times is a reply to the confirmation including the download links, we have no trouble. But, we have prob had about 300 tickets over the last ten days related to this, and in many cases the users reply before we see the ticket "FIXED". Very very strange, which made me wonder if there was some sort of cron backup which obviously I know there is not. We have a complex site with a lot of attribution features, I will start breaking them down then get back to you on this. First and foremost, let's remove white labeling of links / click tracking.

**Comment by mikejolley** [comment]
I expect tracking links would go 'via' another URL to do the tracking, or you'd have some kind of handler on the site? Both cases I presume could affect these links, so thats a good start.

You can also enable plain text rather than HTML emails - that will prevent 'real' links being sent and send URLs only to the customer. URLs are less likely to be munged by the email client.

I'm going to close this out as it does not look like we require to take any action yet, but please follow up with your learnings after testing the parts highlighted. The fact that emails have links show that permissions are being generated correctly from the WC side.

Thanks

**Comment by accetturo** [comment]
Hey @mikejolley , We figured out its redirecting people to the homepage. If any UTM's are added into the links, they no longer seem to work in some cases, see the following to links

https://www.rudymawer.com/?download_file=1649&order=wc_order_5955ce0719dcd&email=miskinro%40yahoo.com&key=5fc2f9be659dcfd63e90771a8b1a286f&utm_campaign=transactional&utm_source=sendgrid&utm_term=transactional&utm_medium=email

https://www.rudymawer.com/?download_file=1649&order=wc_order_5955ce0719dcd&email=miskinro%40yahoo.com&key=5fc2f9be659dcfd63e90771a8b1a286f

**Comment by accetturo** [comment]
Let me also clarify, Any external email service like sendgrid plugin will break the woocommerce as is w/ analytic's compatible tracking enabled(default), and they should not. UTM's are standardized and it should still work after being appended.

**Comment by accetturo** [comment]
We fixed this, it was due to improper UTM handling by sendgrid's plugin. It was adding breaking UTM's by not append & correctly, please close this
