### ISSUE TITLE
WC 3.0.9 WP 4.8 - Product Category and Product Tag Text Boxes show as 'Empty' or not At All

### ISSUE THREAD

**Issue by Pierre72** [woocommerce/woocommerce#15765]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce
- [X ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. The issue is current on our Wordpress when going to Products, Categories and try to Edit or create a new Product category or a Product Tag. 
![category view_2](https://user-images.githubusercontent.com/29675720/27508959-6dfe1654-58f1-11e7-91b4-f8f18690fc14.jpg)
![category view_3](https://user-images.githubusercontent.com/29675720/27508960-6dfef998-58f1-11e7-8614-cc92d3b44128.jpg)
![category view_4](https://user-images.githubusercontent.com/29675720/27508962-6e01630e-58f1-11e7-8c03-9fd1468adb8c.jpg)
![category view_1](https://user-images.githubusercontent.com/29675720/27508961-6dffc4f4-58f1-11e7-9bbf-a047876a722c.jpg)

2. The issue does not occur for Products or Page editing.
3. The issue occured after upgrading Woocommerce 3.0.9 , Woocommerce Booster tools and Wordpress 4.8.

## Expected behavior and actual behavior
When I click to edit a category I expect to see the Description in a textbox which is editable.

When I follow those steps, I see... No Description Text

I was expecting... Description Text to show in the textbox

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
WordPress environment
Home URL:		https://www.lilyblue.co.za
Site URL:		https://www.lilyblue.co.za/wp
WC version:		3.0.9
Log directory writable:		 /home/lilyblu2/public_html/wp/wp-content/uploads/wc-logs/
WP version:		4.8
WP multisite:		–
WP memory limit:		512 MB
WP debug mode:		–
WP cron:		
Language:		en_GB
Server environment
Server info:		Apache
PHP version:		5.6.30
PHP post max size:		64 MB
PHP time limit:		600
PHP max input vars:		2000
cURL version:		7.54.0, OpenSSL/1.0.2k
SUHOSIN installed:		–
MySQL version:		5.6.35
Max upload size:		60 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.9
Database prefix	 	wplb_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 /home/lilyblu2/public_html/wp/wp-content/uploads/GeoIP.dat
Security
Secure connection (HTTPS):		
Hide errors from visitors		
Active plugins (23)
Enhanced Media Library	 	by wpUXsolutions – 2.4.5
Product Custom Options(Free)	 	by FME Addons – 1.0.1
Google Analytics for WordPress by MonsterInsights	 	by MonsterInsights – 6.2.0
Google XML Sitemaps	 	by Arne Brachhold – 4.0.8
Meta Slider	 	by Matcha Labs – 3.5.1
Photo Gallery	 	by Photo Gallery Team – 1.3.45
Really Simple SSL	 	by Rogier Lankhorst – 2.5.17
Regenerate Thumbnails	 	by Alex Mills (Viper007Bond) – 2.2.6
Simple 301 Redirects	 	by Scott Nellé – 1.07
WC Variations Radio Buttons	 	by 8manos – 2.0.0
WooCommerce - Store Exporter	 	by Visser Labs – 1.9.1.1
WooCommerce PayFast Gateway	 	by WooThemes – 1.4.0 – 1.4.4 is available
Booster for WooCommerce	 	by Algoritmika Ltd – 2.8.2
WooCommerce Menu Cart	 	by Jeremiah Prummer, Ewout Fernhout – 2.6.0
WooCommerce PDF Invoices & Packing Slips	 	by Ewout Fernhout – 1.6.5
WooCommerce Stock Manager	 	by Vladislav Musílek – 1.1.5
WooCommerce	 	by Automattic – 3.0.9
Yoast SEO	 	by Team Yoast – 4.9
WP Image Zoom	 	by SilkyPress – 1.12
WPSSO Schema JSON-LD Markup Pro	 	by JS Morisset – 1.15.0
WPSSO Update Manager	 	by JS Morisset – 1.6.4
WPSSO Pro (Core Plugin)	 	by JS Morisset – 3.45.0
YITH WooCommerce Waiting List	 	by YITHEMES – 1.1.1
Settings
API enabled:		
Force SSL:		–
Currency		ZAR (R)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable), wcpb (wcpb)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#6 - /shop/
Basket:		#7 - /cart/
Checkout:		#8 - /checkout/
My account:		#9 - /my-account/
Theme
Name:		freestore
Version:		– 0 is available
Author URL:		
Child theme:		
Parent theme name:		FreeStore
Parent theme version:		1.2.0 – 1.2.1 is available
Parent theme author URL:		https://kairaweb.com/
WooCommerce support:		
Templates
Overrides	 	freestore-child/woocommerce/cart/cart.php

## Isolating the problem

- [] This bug happens with only WooCommerce plugin active 
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Please report to the booster plugin devs if you're certain it is responsible for the WYSIWYG editors there - WordPress/WooCommerce only uses plain textareas there. 

FWIW I don't think anything changed in core that would affect this in 3.0.9 so it may simply be a javascript conflict on the page. In your browser, go to view > developer > javascript console and it will tell you if errors are present and what scripts are causing it.

**Comment by Pierre72** [comment]
HI Mike

Thanks for the pointer to use the Javascript Console - worked a treat. For refference, I found the issue in a WP Image Zoom Plugin. It is likely it is not compatible with Wordpress 4.8.

Thanks Again
