### ISSUE TITLE
Product's children is not set properly when hooking into woocommerce_product_duplicate action

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#15770]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a variable product with some variations.
2. Hook into [`woocommerce_product_duplicate`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-duplicate-product.php#L100). Following is a simple use case:

   ```php
   add_action( 'woocommerce_product_duplicate', function( $duplicate, $product ) {
   	error_log( 'duplicate children: ' . print_r( $duplicate->get_children(), true ) );
   	error_log( 'original children: ' . print_r( $product->get_children(), true ) );
   } );
   ```

3. Duplicate the product created on step 1.
4. You'll see `$duplicate->get_children()` returns the same variation IDs as `$product->get_children()`.

## Expected behavior and actual behavior

Inside `woocommerce_product_duplicate` action handler, I'd expect `$duplicate->get_children()` returns its own variation IDs.

My suspect is that `$child_duplicate->save()` doesn't sync children prop of parent product. This might be not an issue. For extension this can be easily fix by calling `wc_get_product( $duplicate );` in the `woocommerce_product_duplicate` action handler. Or if this seems like in an issue in core, make sure to sync the duplicated children to duplicated parent product prop.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
```
add_action( 'woocommerce_product_duplicate', function( $duplicate, $product ) {
	error_log( 'duplicate children: ' . print_r( $duplicate->get_children(), true ) );
	error_log( 'original children: ' . print_r( $product->get_children(), true ) );
}, 10, 2 );
``` or you get error.
