### ISSUE TITLE
Creating an Order using REST API --> email shows 0 for grand total

### ISSUE THREAD

**Issue by keyurpatel30** [woocommerce/woocommerce#15779]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create new Order using REST API
2. Check the "new order placed" email (the one sent to customers) 
3. The subtotal, delivery, tax, etc is correct, but the grand total says 0

This happened after upgrading WooCommerce to latest version. The email sent after creating a new order using REST shows 0 for grand total (it is correct when creating from WordPress).

Before:
![image](https://user-images.githubusercontent.com/10952555/27533529-76ee26ea-5a96-11e7-9592-1ca4206a428d.png)

Now:
![image](https://user-images.githubusercontent.com/10952555/27533516-6922f446-5a96-11e7-87b4-78ed9bb4e92f.png)

**Comment by mikejolley** [comment]
Without providing the API requests I cannot confirm if it's just your request at fault here. Also no status report...

I tested on 3.0.9 with the following results and you can see the total is set correctly:

<img width="1406" alt="2017-06-26 at 12 30" src="https://user-images.githubusercontent.com/90977/27537364-6e63774e-5a6b-11e7-8eab-696727113ad4.png">
