### ISSUE TITLE
Provide action right after duplicating child of a variable product

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#15771]
This is a request to add new hook that might benefits extension developers. I mentioned @mikejolley in per-product-shipping as an example.

The action placement is right after [`$child_duplicate->save()`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-duplicate-product.php#L161).
 
### Use case

* You've custom table keyed by product ID (including variation ID).
* You need to duplicate the data in custom table when the variable product is duplicated.

There are two hooks that seem like a good place:

* [`woocommerce_product_duplicate`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-duplicate-product.php#L100) &mdash; after duplicate product is created.
* [`woocommerce_product_duplicate_before_save `](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-duplicate-product.php#L159) &mdash; especially the second hook when iterating children. This is before variation is inserted into DB.

If we use the first approach, we already lost track which one is the original variation of the duplicated variation when we use `$product->get_children()`. Meanwhile with the second approach we don't have duplicated variation ID yet (until `$child_duplicate->save()` is called).

**Comment by mikejolley** [comment]
@gedex Actually, I realised there is a solution you can use now without needing to wait on a new hook or patch. 

`woocommerce_product_duplicate_before_save`

This gives you the actual child object, which has no ID, but that doesn't stop you from saving the object to get the ID :)

just do:

```
$id = $child_duplicate->save();
```

Then do whatever you need to do with $id in hand.

The save called by core when your action is complete will not break, and will not save unless there are further changes made in extensions.
