### ISSUE TITLE
Prices aren't displayed for variable products

### ISSUE THREAD

**Issue by vjdobermann** [woocommerce/woocommerce#15774]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a variable product with different attributs
2. define the prices per attribut
3.the price should be displayed by attribut on the product page and in the cart.

## Expected behavior and actual behavior

When I follow those steps, I see the price at 0.00 for every attribut and also in the cart
see capture screen here : []http://kinesiologie-reiki.ch/fichiers/capture_prix.png and here : []http://kinesiologie-reiki.ch/fichiers/capture_prix2.png
it's in french but I hope it won't be a problem to understand my issue.

Many thanks in advance

**Comment by mikejolley** [comment]
Need to see all variations/prices/sale prices in your screenshot, and need a link to the product page. You also forgot to include system status report.

**Comment by vjdobermann** [comment]
Hi Mikejolley, 

Sorry I was tired when I wrote this topic.

System status report can be viewed [here](www.kinesiologie-reiki.ch/fichiers/wc_report.txt)

the product page is [here](http://kinesiologie-reiki.ch/ecommerce/product/creme-neutre/)

And I made captures screen from all the product variations : 
[5 liters](http://kinesiologie-reiki.ch/fichiers/capt_5l.PNG)
[1 liter](http://kinesiologie-reiki.ch/fichiers/capt_1l.PNG)
[500ml](http://kinesiologie-reiki.ch/fichiers/capt_500ml.PNG)
[250ml](http://kinesiologie-reiki.ch/fichiers/capt_250ml.PNG)

I hope it will help, great thanks

**Comment by mikejolley** [comment]
I can see prices :) So I think it's Woocommerce Role Pricing for your logged in user.
