### ISSUE TITLE
File to import not found or unreadable: bourbon

### ISSUE THREAD

**Issue by chandra10207** [woocommerce/woocommerce#15786]
## Steps to reproduce the issue

1. I have install fresh woocommerce plugin
2. install in wordpress
3.run in local server

## Expected behavior and actual behavior

When I follow those steps, I see File to import not found or unreadable: bourbon

I was expecting not this error and not faced before

## Environment

Windows 

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

![capture](https://user-images.githubusercontent.com/9652251/27547964-3c650194-5ab7-11e7-8293-bbb3653ce6fb.PNG)

**Comment by WPprodigy** [comment]
Eh, what are you doing exactly? Download WooCommerce from here if you are looking to use it on a website: https://wordpress.org/plugins/woocommerce/

**Comment by claudiosanches** [comment]
Maybe Windows related... But closing since 3.1.0 and master does not include bourbon anymore.

**Comment by chandra10207** [comment]
@WPprodigy I have downloaded and install woocommerce from the wordpress plugin store and still appearing this problem :(

**Comment by chandra10207** [comment]
@claudiosanches May be the windows problem but I can't figure out whats the problem exactly.
It works fine on other project on same machine but shows this problem on one project.
