### ISSUE TITLE
[3.1-RC.2] Relative fields (e.g. Up-sells) not imported correctly

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#15781]
Finally found some time to look at the Importer/Exporter. Having some weird issues with relative fields (up-sells, cross-sells). Had a look at the code, and it seems to mirror some of my findings here.

Note this is only about "vanilla" importing, not merging/updating merging data yet.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create 3 products, e.g. with IDs = [1,2,3]. 
2. Assign Up-sell IDs = [1,3] to the product with ID = 2.
3. Export to CSV.
4. Create a fresh install and Import the CSV file created in step 3. Do not check the **Update** (merge data) box.

Variations:

A) Do not define SKUs for any product. Make sure that in the mapping screen, the ID field is mapped to the default - ??? -, "Do not Import".
B) Do not define SKUs for any product. Make sure that in the mapping screen, the ID field is mapped to "ID".
C) Define SKUs for IDs 1 and 3. Make sure that in the mapping screen, the ID field is mapped to the default - ??? -, "Do not Import".
D) Define SKUs for IDs 1 and 3. Make sure that in the mapping screen, the ID field is mapped to "ID".

## Expected behavior and actual behavior

Go to the **Product Data > Linked Products > Up-sells** tab of the product with Original ID = 2.

Case A)
You'll see no products there, or whatever product(s) ended up being imported with Post-Import ID=[1,3].

Case B)
You will only see the product with Original ID = 1. Looking at the code, I guess this is because there is no product with meta `_original_id = 3` when the product with Original ID = 2 gets imported.

Summary:

1. relative `id:` fields don't get imported correctly.
2. relative `sku` fields don't get imported correctly unless we make sure that in the mapping screen, the ID field is mapped to "ID".
3. What's the difference between "ID" and "Do not Import" in the mapping screen? I don't get it and I guess the average user won't get it either. Why does it default to "Do not Import"???

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

## Comments

The `_original_id` meta idea doesn't seem to work because  `WC_Product_CSV_Importer::parse_relative_field` will only look for the `_original_id` of products that have already been parsed (previous rows). If an existing product is not found with the defined `_original_id`, the logic falls back to using whatever ID is passed to the function, which is not an acceptable fallback unless you are merging/updating data.

Some possible solutions:

a) Parse all IDs in one pass, to ensure that the products you need will be added first, along with the `_original_id` meta. Then do the actual import in the second pass.
b) Create a Pre / Post-Import IDs mapping during the import and then do another pass to update relative field references.
c) Drop the `_original_id` approach and always work with temporary SKUs. When handling a relative `id:` field, treat it as a dummy SKU and look for a product with that SKU. If not found, create a product with that temp SKU. Modify `WC_Product_CSV_Importer ::parse_id_field` to create a temporary SKU instead of creating an `_original_id` meta.

I'd give (c) a shot and send a PR, but the existing logic is hard to decipher. I don't understand how it's supposed to work, and real-world testing yields equally confusing results.

**Comment by franticpsyx** [comment]
Also maybe I am missing something but I don't see a way to merge products at all.

e.g. 

- export db from live, 
- import to a test/staging site and add products there, 
- merge products added in staging with live.

Here's what I'm seeing after adding one product and attempting to merge: https://cl.ly/2i3v1w0H0H35

**Comment by mikejolley** [comment]
You want to share your CSV used in testing?

**Comment by franticpsyx** [comment]
@mikejolley It's the standard dummy install you get from Storefront. I exported these products after installing Storefront. Fresh install/db.

**Comment by franticpsyx** [comment]
OK [here](http://somewherewarm.gr/uploads/wc-product-export-2017-06-26.csv) it is.

I added 2 Upsells to "Cap" ("Beanie" and "Belt").

**Comment by mikejolley** [comment]
> What's the difference between "ID" and "Do not Import" in the mapping screen? I don't get it and I guess the average user won't get it either. Why does it default to "Do not Import"???

"Do not Import"....does not import :p The column is ignored. This maps to ID by default for me because the column header is an exact match.

Testing your CSV above, "hoodies" has upsells and crosssells because it maps to `id:`. SKU does not exist.

If there is no ID column mapped, those `id:` linked products would not work either.

**Comment by mikejolley** [comment]
Also note I had to remove the images column from your CSV for it to work my side because those are not accessible.

**Comment by claudiosanches** [comment]
@franticpsyx please let us know if the recent changes fix the issues.

**Comment by franticpsyx** [comment]
@claudiosanches Just found ID was prepended by `\ufeff` (BOM). The fix in #15790 looks good 👍

**Comment by franticpsyx** [comment]
Update:

1. The BOM fix #15790  resolved the `ID` mapping issue.
2. The tweak in #15785 fixes the reported issue about relative `id:` fields 👍 .

@mikejolley Still trying to understand the use case for "merging/updating" if it doesn't actually add new IDs. It's been a while since I used the old importer but I remember that _merging_ would work as follows there:

1. If a product with the same ID exists, update the existing product data.
2. If a product with the same ID does not exist, create a product (if possible with the same ID).

In the new Importer, products cannot be "appended" by merging.

**Comment by mikejolley** [comment]
It was intentional. It was confusing to both update and add all at once because it makes managing IDs nigh impossible.

If you're updating, only updates on existing products are performed as part of that import.

**Comment by franticpsyx** [comment]
@mikejolley Makes sense -- "merging" was never a true sync process anyway. Might make sense to make this clearer in the UI, though, especially since users coming from the old PCSVIE extension might expect everything to work in the same way. 👍
