### ISSUE TITLE
Adding microdata "condition" for products in woocommerce

### ISSUE THREAD

**Issue by Gowsalayadevi** [woocommerce/woocommerce#15797]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X ] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Expected behavior and actual behavior

I trying to add micro data "condition" for products

## Environment

<details>
I am using woocoomerce 3.1. I would like to do chnages in the schema which is generated by woocommerce as my google merchant account showing warnings "missing microdata for condition " 
</details>

## Isolating the problem

- [ X ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
WooCommerce doesn't, by default, have a "condition" field for products.

You will need to add a field in the product admin page for selecting the condition type, and then you'll need to use the available filters for adding in this microdata. Likely this one: https://github.com/woocommerce/woocommerce/blob/c2a1b8cc586337f85353a5b96db6684e5b337ec4/includes/class-wc-structured-data.php#L245

This is not something we can help you with though, so you'll either need to find a plugin for this or hire a developer.

**Comment by Gowsalayadevi** [comment]
Thanks. I am using 2.4.2 woocommerce version in other website which can not be updated to recent one as it is integrated with other accounting software. Can you let me know from which file the structured data is coming from.

**Comment by WPprodigy** [comment]
Older versions of WooCommerce had the microdata stored in the template files. So you could probably just add it to one of the single product templates - or one of these hooks: https://github.com/woocommerce/woocommerce/blob/master/templates/content-single-product.php

This isn't something we can help with, as it's a customization way out of scope for what this repo/issues are for. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooCommerce Support](https://docs.woocommerce.com/) page.

**Comment by Gowsalayadevi** [comment]
thank you so much. I will post the issue in wooCommerce support

**Comment by coccoinomane** [comment]
I suspect several people are encountering this issue due to Google Merchants requiring the 'condition' markup to be present in the product page. If this is the case, you just need to add the following snippet in your `functions.php`:

```php
/**
 * Add properties to the http://schema.org/Offer markup for all products.
 */
function omai_woocommerce_structured_data_product_offer( $markup, $product ) {
	
	/* By default, we assume all products sold in the ecommerce are in
	new condition */
	if ( empty( $markup[ 'itemCondition' ] ) ) {
		$markup[ 'itemCondition' ] = 'http://schema.org/NewCondition';
	}
	
	return $markup;

}
```

This assumes that your products are all sold as new. If this is not the case, you can use any of the conditions listed in the Schema specification at http://schema.org/OfferItemCondition, that is:

* DamagedCondition => http://schema.org/DamagedCondition
* NewCondition => http://schema.org/NewCondition
* RefurbishedCondition => http://schema.org/RefurbishedCondition
* UsedCondition => http://schema.org/UsedCondition

Hope this is helpful!

Cheers,
Guido

**Comment by sahilsaid** [comment]
Thanks @coccoinomane. Managed to get it working with your suggestion. I had to find  correct filter to use though. Below is the example of the usage with appropriate filter.

add_filter( 'woocommerce_structured_data_product', 'filter_woocommerce_structured_data_product', 10, 2 ); 

/**
 * Add properties to the http://schema.org/Offer markup for all products.
 */
function filter_woocommerce_structured_data_product( $markup, $product ) { 
        /* By default, we assume all products sold in the ecommerce are in new condition */
	if ( empty( $markup[ 'itemCondition' ] ) ) {
		$markup[ 'itemCondition' ] = 'http://schema.org/NewCondition';
	}
	return $markup;
}

**Comment by coccoinomane** [comment]
You're right @sahilsaid, I forgot to include the actual filter 😜 I've edited my answer accordingly.

As a side note consider that, according to the schema.org specifications for [itemCondition](http://schema.org/itemCondition), you could also use the `woocommerce_structured_data_product_offer` filter.

Cheers,
Guido
