### ISSUE TITLE
Columns classes (col-1 and col-2) conflicts with Bootstrap v4

### ISSUE THREAD

**Issue by cyrildc** [woocommerce/woocommerce#15793]
WooCommerce uses the classes col-1 and col-2 in the following files:

- templates/checkout/form-checkout.php
- templates/myaccount/form-login.php
- templates/order/order-details-customer.php

These classes are used in Boostrap v4 to create 1/12 and 2/12 column.
`.col-1 {
  -webkit-box-flex: 0;
  -webkit-flex: 0 0 8.333333%;
      -ms-flex: 0 0 8.333333%;
          flex: 0 0 8.333333%;
  max-width: 8.333333%;
}`
`.col-2 {
  -webkit-box-flex: 0;
  -webkit-flex: 0 0 16.666667%;
      -ms-flex: 0 0 16.666667%;
          flex: 0 0 16.666667%;
  max-width: 16.666667%;
}`

**Comment by WPprodigy** [comment]
WooCommerce doesn't declare Bootstrap support, so not sure if this is something that will be/should be changed. There are countless frameworks and themes out there and it would be impossible to be compatible with them all.

CC @jameskoster

**Comment by claudiosanches** [comment]
I'm not a big fan of `col-1` or `col-2`, both means nothing... Maybe replace for better naming in 4.0.0.
But right now the best solution in to create custom templates inside the theme to avoid fix any conflict with your theme Bootstrap v4 based.

**Comment by jameskoster** [comment]
We'll be adding new classes whenever we get around to https://github.com/woocommerce/woocommerce/issues/10674

But I'm still not sure we'll ever fully remove all the old classes. Too much risk for breakage for comparatively little reward.

Imo your best approach would be to dequeue the wc stylesheets and add your own custom versions. It's the only way to rule out conflicts 100%.

**Comment by hasanrang** [comment]
In-case anyone may looking for quick fix until the issue fixed. just replace the col-1 and col-2 by appropriate bootstrap class, hope that help.

`
    $('#customer_details .col-1').removeClass('col-1').addClass('col-6').css({"display": "inline-block", "vertical-align": "top"});
    $('#customer_details .col-2').removeClass('col-2').addClass('col-5').css('display','inline-block');
    $('.woocommerce-MyAccount-content .col-1').removeClass('col-1').addClass('col-12');
    $('.woocommerce-MyAccount-content .col-2').removeClass('col-2').addClass('col-12');

`

**Comment by viviancruzbt** [comment]
I did fix with CSS.
There is my SASS code:
.woocommerce{
  .col-1, .col-2{
    max-width:none;
  }
}

**Comment by kurdi89** [comment]
as viviancruzbt  suggested this worked for me :  

.woocommerce .col-1, .col-2{ max-width:none;}

**Comment by max4kaps** [comment]
.woocommerce .col-1, .woocommerce .col-2{ max-width:none;}

**Comment by Coernel82** [comment]
Those workarounds didn't work for me. My solution:
Use a custom bootstrap version: https://getbootstrap.com/docs/3.3/customize/ and un-tick the "Forms" in the first colum "Common CSS".

**Comment by muktoapb** [comment]
this works for me
`.woocommerce-billing-fields .form-row, .woocommerce-shipping-fields .form-row,.woocommerce form .form-row {
	display: block;
}

.woocommerce .col2-set .col-1, .woocommerce-page .col2-set .col-1,.woocommerce .col2-set .col-2, .woocommerce-page .col2-set .col-2 {
    max-width: unset;
}
`

**Comment by PopcornDesign** [comment]
I am having this issue with latest bootstrap

**Comment by smarterdigitalltd** [comment]
A good solution would be to use a WordPress filter on the CSS classes in the template file. Backwards compatible, and easily changed by a developer. No need to override the template. Feasible?

**Comment by iziCodeBlog** [comment]
Replace all "col-" on "boot-col-" and  "form-row" on "boot-form-row" in file "bootstrap.min.css"
And now use the new name wherever you want to see bootstrap
Also I attach my modified working file...
Just change the name from " bootstrap.txt " on " bootstrap.min.css" 
Because I can't add css files to github

[bootstrap.txt](https://github.com/woocommerce/woocommerce/files/2591717/bootstrap.txt)

**Comment by jilson23** [comment]
> this works for me
> .woocommerce-billing-fields .form-row, .woocommerce-shipping-fields .form-row,.woocommerce form .form-row {
> display: block;
> }
> 
> .woocommerce .col2-set .col-1, .woocommerce-page .col2-set .col-1,.woocommerce .col2-set .col-2, .woocommerce-page .col2-set .col-2 {
> max-width: unset;
> }

excelent, this works for me

**Comment by strabsquad** [comment]
> .woocommerce .col-1, .woocommerce .col-2{ max-width:none;}

Thanks for the quick tip fix

**Comment by leecollings** [comment]
Amazed that the creators of WC are so ignorant that they will not fix this. Bootstrap should absolutely be able to be used in conjunction with this without any conflicts considering how popular the two items are.

I would strongly urge the WC devs to look into this, and rename their classes. Sticking to their guns is really not the right message to be sending out here, we're supposed to be working together.

**Comment by tex0gen** [comment]
@leecollings Agreed! While there are many CSS frameworks out there, Bootstrap is the most commonly used framework. Please don't ignore this. The best solution would be as @smarterdigitalltd suggested and use a filter for backwards compatibility.

**Comment by claudiosanches** [comment]
Have my or James comments?
This is still a possibility for us to change, but this implicates in breaking backwards compatibility with themes, something that we are not looking forward to do at this time.

But I assure everyone that when it is possible, it will be done.

I'm closing this issue for new comments because of the rage that doesn't add up to anything in this discussion.
