### ISSUE TITLE
How can i make custom endpoint/extend API to retrieve customers/products/order by modified date?

### ISSUE THREAD

**Issue by sagaraloha** [woocommerce/woocommerce#15807]
I am using WooCommerce version: 3.0.8
Wordpress version: 4.8

I want to fetch the customers and products and orders which are updated after the particular date.

**Comment by mikejolley** [comment]
The REST API does not have this type of filtering built in. Available filtering options are listed on https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders
