### ISSUE TITLE
Product variations status stay 'publish' even after the product is set to draft

### ISSUE THREAD

**Issue by anag0** [woocommerce/woocommerce#15812]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Make a variable product + some variations
2. Set the product to draft
3. The variation statuses are still set 'publish' for the product within the database

## Expected behavior and actual behavior

I believe the product variation object statuses should be 'draft' within the database as well.

## Environment

<details>
WordPress environment
Home URL:		http://test.wp-dreams.com
Site URL:		http://test.wp-dreams.com
WC version:		3.0.9
Log directory writable:		 To allow logging, make /var/www/test.wp-dreams.com/public_html/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.
WP version:		4.8
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		
WP cron:		
Language:		en_US
Server environment
Server info:		Apache/2.4.7 (Ubuntu)
PHP version:		 5.5.9-1ubuntu4.14 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP post max size:		8 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.35.0, OpenSSL/1.0.1f
SUHOSIN installed:		–
MySQL version:		 5.5.46 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max upload size:		8 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.0.9
Database prefix	 	wp_
woocommerce_sessions	 	
woocommerce_api_keys	 	
woocommerce_attribute_taxonomies	 	
woocommerce_downloadable_product_permissions	 	
woocommerce_order_items	 	
woocommerce_order_itemmeta	 	
woocommerce_tax_rates	 	
woocommerce_tax_rate_locations	 	
woocommerce_shipping_zones	 	
woocommerce_shipping_zone_locations	 	
woocommerce_shipping_zone_methods	 	
woocommerce_payment_tokens	 	
woocommerce_payment_tokenmeta	 	
MaxMind GeoIP database:		 The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: /var/www/test.wp-dreams.com/public_html/wp-content/uploads/GeoIP.dat. Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Security
Secure connection (HTTPS):		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors		Error messages should not be shown to visitors.
Active plugins (12)
Advanced Custom Fields	 	by Elliot Condon – 4.4.11
Ajax Search Lite	 	by Ernest Marcinko – 4.7.5
Bold News Plugin	 	by BoldThemes – 1.0.5
Bold Builder	 	by BoldThemes – 1.2.6
Cost Calculator	 	by BoldThemes – 1.1.6
BoldThemes WordPress Importer	 	by BoldThemes – 1.0.4
Contact Form 7	 	by Takayuki Miyoshi – 4.4
Meta Box	 	by MetaBox.io – 4.11.3
Team	 	by RadiusTheme – 1.9
WooCommerce	 	by Automattic – 3.0.9
WooSidebars	 	by WooThemes – 1.4.3
WordPress Reset	 	by Matt Martz – 1.4
Settings
API enabled:		
Force SSL:		–
Currency		GBP (£)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#49 - /?page_id=49
Cart:		#50 - /?page_id=50
Checkout:		#51 - /?page_id=51
My account:		#52 - /?page_id=52
Theme
Name:		Twenty Fifteen
Version:		1.3 – 1.8 is available
Author URL:		https://wordpress.org/
Child theme:		 – If you're modifying WooCommerce on a parent theme you didn't build personally, then we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Overrides:
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Child posts never sync with the parent in this way; their status is independent and based on the 'enabled' checkbox in the UI. Since variations are not shown in loops this should not be a problem.
