### ISSUE TITLE
[3.1.0-rc.2] orderby is gone when search in category 

### ISSUE THREAD

**Issue by cannap** [woocommerce/woocommerce#15813]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce

## Steps to reproduce the issue

1. install WooCommerce beta Plugin
2.  Update 
3. add ?product_cat=clothing&s=ninja  to the url 

## Expected behavior and actual behavior

When I follow those steps, I see...

![GitHub Logo](https://i.gyazo.com/1a5e21251923b6365e9b98af08d6de4b.png)
I was expecting...
![GitHub Logo](https://i.gyazo.com/ca31c27e232798664b7c97e9f6226335.png)

## Environment

<details>
latest rc
win 10
wp 4.8
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Order by is disabled when searching, because WordPress orders results by relevance. This is intended in 3.1.
