### ISSUE TITLE
Product category api not working 

### ISSUE THREAD

**Issue by heemu9** [woocommerce/woocommerce#15810]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
You need to provide more details or issues will be closed.

**Comment by heemu9** [comment]
Sir I am trying to use api, http://demotwo.technitab.net/wp-json/wc/v2/products?category=id its working fine on postman but getting 401 error while integrating the API in android app. Any help will be appreciated

**Comment by mikejolley** [comment]
That means your keys are wrong.

**Comment by heemu9** [comment]
Dear sir,

If the keys are wrong then why it is working fine on postman..Also the http://demotwo.technitab.net/wp-json/wc/v2/orders are working fine on both android integration and postman

Did I need any to set separate keys for http://demotwo.technitab.net/wp-json/wc/v2/products/category=Id

If yes kindly guide how can I do so? 


Sent from YU

On Jun 27, 2017 7:30 PM, Mike Jolley <notifications@github.com> wrote:

That means your keys are wrong.

**Comment by mikejolley** [comment]
If it works in postman, there is no problem with the API, so it must be your client code...

401 means the keys are not being sent or received correctly.  I'm not able to debug your app.

**Comment by heemu9** [comment]
But sir some api' s are working on same code but few of them is not working like : baseurl/product/category=Id, baseurl/search=news not working however api like baseurl:/products, baseurl/orders on same android code

Sent from YU

On Jun 27, 2017 7:50 PM, Mike Jolley <notifications@github.com> wrote:

    This message is eligible for Automatic Cleanup! (notifications@github.com) Add cleanup rule | More info 

If it works in postman, there is no problem with the API, so it must be your client code...

401 means the keys are not being sent or received correctly. I'm not able to debug your app.

**Comment by mikejolley** [comment]
Maybe you're using signatures? If so, any query string args you add need to be taken into consideration.

**Comment by heemu9** [comment]
Yes, signature is used in this.Will u please elaborate what you want to say. I am unable to get you

Sent from YU

On Jun 27, 2017 8:14 PM, Mike Jolley <notifications@github.com> wrote:

Maybe you're using signatures? If so, any query string args you add need to be taken into consideration.

**Comment by mikejolley** [comment]
See the docs on signature generation - it explains it.

**Comment by heemu9** [comment]
@mikejolley mikejolley Okay Sir. Thank you. 

Let me study that and revert.

**Comment by heemu9** [comment]
Dear @mikejolley , 

I understand the following from your comments 
1. Because Postman is able to fetch data for all urls (http://demotwo.technitab.net/wp-json/wc/v2/products/category=Id, http://demotwo.technitab.net/wp-json/wc/v2/orders, http://demotwo.technitab.net/wp-json/wc/v2/products, http://demotwo.technitab.net/wp-json/wc/v2/customers, http://demotwo.technitab.net/wp-json/wc/v2/products?search=news), so woocommerce API is fine
2. Because Android is able to fetch data for particular urls (http://demotwo.technitab.net/wp-json/wc/v2/orders, http://demotwo.technitab.net/wp-json/wc/v2/products, http://demotwo.technitab.net/wp-json/wc/v2/customers), but not for these two urls ( http://demotwo.technitab.net/wp-json/wc/v2/products/category=Id,  http://demotwo.technitab.net/wp-json/wc/v2/products?search=news) so Android Code needs some authenitication 
3. I have used 	Consumer key and 	Consumer secret key  for Android Code. signature method used is HMAC-SHA1 so no query string or arguments are passed.

Please help in finding the fault

**Comment by mikejolley** [comment]
https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

```
Collect parameters

Collect and normalize your parameters. This includes all oauth_* parameters except for the oauth_signature itself.

These values need to be encoded into a single string which will be used later on. The process to build the string is very specific:

Percent encode every key and value that will be signed.
Sort the list of parameters alphabetically by encoded key.
For each key/value pair:
Append the encoded key to the output string.
Append the = character to the output string.
Append the encoded value to the output string.
If there are more key/value pairs remaining, append a & character to the output string.
When percent encoding in PHP for example, you would use rawurlencode().

When sorting parameters in PHP for example, you would use uksort( $params, 'strcmp' ).
```

**Comment by heemu9** [comment]
I am trying to create an API for mobile to signup with url: 

http://demotwo.technitab.net/wp-json/wp/v2/users?username=thty&email=h34@gmail.com&password=123455

But I am getting error :

{
    "code": "rest_cannot_create_user",
    "message": "Sorry, you are not allowed to create new users.",
    "data": {
        "status": 401
    }
}


Kindly Help.


Thanks in Advance
