### ISSUE TITLE
WooCommerce overrides stock instead of incrementing/decrementing it

### ISSUE THREAD

**Issue by UserGalileo** [woocommerce/woocommerce#15818]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce
- [ x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.Shopping manager opens Product page (ex. Jeans) and sees that there are 5 remaining in stock
2.A random user buys 1 pair of Jeans, causing the stock to decrement to 4. But the admin still sees 5 on his Product page (still open and not refreshed)
3.The admin, in order to add 2 pairs of Jeans, overwrites the 5 and enters 7, and Saves.

## Expected behavior and actual behavior

When I follow those steps, I see that now the stock for the Jeans is 7.

I was expecting to see 6 because 1 of them was bought during the admin modification.
I was expecting Woocommerce NOT to override the 5, but to do 7 minus 5 equals 2, and increment the stock by 2.

I would solve it this way, OR the product page could display the actual stock via ajax in real-time, NOT allowing it to be modified, but instead using an "increment by/decrement by" button.

## Environment

<details>
Latest version of WooCommerce, latest version of WordPress. 
</details>

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15827

**Comment by UserGalileo** [comment]
@mikejolley Record time, thanks ;)
