### ISSUE TITLE
New product gallery has poor support for responsive images (and no lazy loading)

### ISSUE THREAD

**Issue by EmilEriksen** [woocommerce/woocommerce#15825]
When both the slider and zoom are enabled all of the product images seem to be loaded at full size. I imagine this means tens of MBs on many sites.

The thumbnail images are loaded as "old school" images with no srcset. 

I'm not entirely sure how jQuery Zoom works but it seems like it replaces the images with single src "old school" full size images immediately on page load. I'd expect a smaller image to be loaded at first.

The slider doesn't seem to lazy load the images so if I have a product with 10 product images and I have zoom and the slider enabled I'd maybe have upwards of 100 MBs full size images being loaded just to view that product. This doesn't seem ideal to me.

I realise some of this could be mitigated by using the `woocommerce_product_thumbnails_large_size` filter to define a new image size but let's be honest - that's not going to happen in probably the majority of themes (looking at you ThemeForest).

**Comment by mikejolley** [comment]
@EmilEriksen The image loaded on the actual page is not FULL, it's shop_single. Look here:

https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-thumbnails.php#L40

It's linked but not rendered. The zoom script loads it.

**Comment by EmilEriksen** [comment]
Yeah you're right, it does only replace the shop_single image with the full size after the shop_single image has loaded. It's still a little concerning if e.g. 10 shop_single images are loaded at first, then replaced by zoom with 10 full size images that are consequently loaded - especially for mobile users.

**Comment by mikejolley** [comment]
@EmilEriksen There is also a srcset. And regardless of deferring zoom (I am testing it now with no zoom) the large image is loaded by that.

**Comment by mikejolley** [comment]
^ try that

**Comment by EmilEriksen** [comment]
Awesome! That was quick. Looks great. I'll try it ASAP.

Yes, there's a srcset on the shop_single image but not the full size image loaded by zoom which makes sense now I understand how it's all loaded :)

There's still no srcset on the slider thumbnails though.

How about lazy loading the slides (all images but the active product image) or is that beyond the scope of WC? It's still potentially quite a lot of images being loaded on initial page load.

**Comment by mikejolley** [comment]
Slider thumbnails are dynamic, so no srcset can be added there. They are created by flexslider when init.

Closed in favour of https://github.com/woocommerce/woocommerce/issues/15828
