### ISSUE TITLE
Legacy api (/wc-api/v3) product bulk update causing fatal error on CIN 7 integration

### ISSUE THREAD

**Issue by rhurley-delta** [woocommerce/woocommerce#15834]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
So I have had a lot of drama trying to push product data (mostly for stock keeping reasons) from CIN 7 to woocommerce using the API integration. I kept getting 500 responses.

CIN 7 is talking to woocommerce via: POST to /wc-api/v3/products/bulk

Please note that I cannot exactly reproduce this issue - My impression of my problem is that it stems of invalid data being contained in my store and woocommerce code not handling the invalid data in a sensible manner.

I have fixed the issue now, but in a way that is extremely shady - What I have done is add a snippet of code to the woocommerce plugin code. What was edited exactly is /woocommerce/includes/data-stores/class-wc-product-variation-data-store-cpt.php.

I added in this snippet of code @ line 147:
` if ( ! $product->get_date_created() ) {`
`   $product->set_date_created( current_time( 'timestamp', true ) );`
`}`

I did this because when I checked my php error logs I consistently got this error upon trying to push data from cin 7:
`PHP Fatal error:  Call to a member function getOffsetTimestamp() on null in ...../woocommerce/includes/data-stores/class-wc-product-variation-data-store-cpt.php on line 153`

Now my thoughts are that my database holds existing products that SOMEHOW do not have a creation date field set. I do not know how that would occur exactly but if anybody has any idea I would love to hear them. And when the function 'update' is called in class-wc-product-variation-data-store-cpt.php it will break upon these products with non-existent dates.

1. Using woocommerce (version 3.09), Using CIN 7 (integration with woocommerce, via api)
2. Hit update recently modified stock in the woocommerce integration dashboard of CIN 7
3. If you're (un) lucky you will be met with a prompt of failure because of a 500 response.

## Expected behavior and actual behavior
When I follow those steps, I see...
500 internal server error response
I was expecting...
201 content created response

## Environment
<details>
`### WordPress Environment ###

Home URL: http://www.4dcontrols.com.au
Site URL: http://www.4dcontrols.com.au
WC Version: 3.0.9
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: 5.6.30-12~ubuntu14.04.1+deb.sury.org+1
PHP Post Max Size: 200 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.49 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.9
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (38) ###

Gravity Forms: by rocketgenius – 2.0.3
WP REST API - OAuth 1.0a Server: by WP REST API Team – 0.3.0
PW Advanced Woo Reporting: by Proword.net – 2.2
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.10
Contact Form 7: by Takayuki Miyoshi – 4.8
Gravity Forms CSS Ready Class Selector: by Brad Vincent – 1.1
WooCommerce Search Plugin by Instant Search +: by WooCommerce Search by Fast Simon Inc – 1.8.12
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

WooCommerce Product Filter: by Mihajlovic Nenad – 6.3.0
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.0
Recent Posts Widget Extended: by Satrya – 0.9.9.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Revolution Slider: by ThemePunch – 4.6.92
TablePress: by Tobias Bäthge – 1.8
TinyMCE Advanced: by Andrew Ozz – 4.6.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.4

WooCommerce Additional Variation Images: by WooCommerce – 1.7.7
Woocommerce Advanced Bulk Edit: by George Iron – 4.1.1
WooCommerce Advanced Shipping Zones: by Jeroen Sormani – 1.1.1
WooCommerce Advanced Shipping: by Jeroen Sormani – 1.0.13
WooCommerce Brands: by WooCommerce – 1.5.2
woocommerce csv export: by Allaerd Mensonides – 1.0.3
Woocommerce CSV import attributes: by Allaerd Mensonides – 3.0.2
Woocommerce CSV import custom fields: by Allaerd Mensonides – 3.0.1
Woocommerce CSV import downloadable, external, grouped products: by Allaerd Mensonides – 3.0.1
Woocommerce CSV import variable products: by Allaerd Mensonides – 3.0.2
Woocommerce CSV Import: by Allaerd Mensonides – 3.3.5
WooCommerce: by Automattic – 3.0.9
WooSidebars: by WooThemes – 1.4.3
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 4.9
WP REST API Menus: by Fulvio Notarstefano – 1.3.1
WP-Lister Pro for eBay: by Matthias Krok – 2.0.22
WP Pro Image Editor: by Niels M. – 1.0.6
YITH Woocommerce Request A Quote Premium: by Yithemes – 1.3.5
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #16 - /plc-and-control-parts/
Cart: #7577 - /cart/
Checkout: #7578 - /checkout/
My account: #7579 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.5
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Created date should always be set - odd, maybe related to status, but there is a workaround here: https://github.com/woocommerce/woocommerce/pull/15843
