### ISSUE TITLE
Product import - Stock update

### ISSUE THREAD

**Issue by danielhuesken** [woocommerce/woocommerce#15840]
I will update prices or stock with the product import. For that i have created a csv file that has only the SKU and the stock amount. Wenn i have in the csv products that not exists in the shop, they will be created. The checkbox "Update existing products" is checked.

I think this desired behavior is not wished in that case of an import. And we have many cases where clients need a import like that without creating the not existing products. I thnik there are to less information for creating a product.

When i with to import the products that i will noch check the "Update existing products" checkbox and import the csv again. Because existing Products will be skipped.

**Comment by mikejolley** [comment]
The description:

> If a product being imported matches an existing product by ID or SKU, update the existing product rather than creating a new product or skipping the row.

If the product being imported does not match by ID or SKU, it will/should be created. I think we should leave this as is for now and revisit based on customer feedback. FWIW product CSV import suite extension does it this way too.

> And we have many cases where clients need a import like that without creating the not existing products

Why would a CSV contain rows for update which do not exist? I think the work flow most users would use would be to export, edit, import/update. The rows would match.

**Comment by danielhuesken** [comment]
> Why would a CSV contain rows for update which do not exist? I think the work flow most users would use would be to export, edit, import/update. The rows would match.

For example an export from another system will be done (like SAP). But you would not have all products from that in the shop. In moment you must edit the export again to filter out the products you would not have. That is a often needed scenario of our clients.

If you need the products to be crated you can import simply the products again without checking the option.

**Comment by danielhuesken** [comment]
Else you can completely remove the checkbox and always update the products that are in the shop. Because you can edit the file and remove products that should not be updated.

**Comment by mikejolley** [comment]
Well, I'll submit a new PR because your's had typos. Give me a moment

**Comment by danielhuesken** [comment]
Thanks
