### ISSUE TITLE
can not add atributes

### ISSUE THREAD

**Issue by gkakhadze** [woocommerce/woocommerce#15847]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by gkakhadze** [comment]
its loading and nothing doing wen i click add

**Comment by mikejolley** [comment]
Please see https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x - it will be a conflict.
