### ISSUE TITLE
Searching orders using the customer's Full Name returns 0 results

### ISSUE THREAD

**Issue by geeklore** [woocommerce/woocommerce#15853]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install a version of WooCommerce prior to `3.0.8`
2. Create a simple product and then purchase it.
3. Go to orders and search by the customers full name which will return expected results.
4. Update to WooCommerce `3.1`.
5. Go to orders and search for customer by full name and 0 results are returned. If you search by the last name, results are returned.

_Tested with Master as well. Same results._

## Expected behavior and actual behavior

When I follow those steps, I see that an order belonging to the customer is returned in the results as expected using a version before `3.0.8`, but when on the latest version of `3.1` (and master) I do not see the results.

I was expecting to see the order belonging to the customer returned when searching the full name in version `3.1`.

![see screen shot](http://cld.wthms.co/KwEVIf+)
Link: http://cld.wthms.co/KwEVIf

![see screen shot](http://cld.wthms.co/Xh8cc+)
Link: http://cld.wthms.co/Xh8cc

![see screen shot](http://cld.wthms.co/OFWpSx+)
Link: http://cld.wthms.co/OFWpSx

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://woo3plus.dev
Site URL: http://woo3plus.dev
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Flywheel/4.1.0
PHP Version: 5.6.20
PHP Post Max Size: 1,000 MB
PHP Time Limit: 300
PHP Max Input Vars: 4000
cURL Version: 7.38.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by yukikatayama** [comment]
Was able to replicate this as well. Nice details!

**Comment by claudiulodro** [comment]
For posterity, I was able to replicate this problem like so:
- Create an order in WC 2.6.14
- Update to any 3.x.x (I tried 3.1 and 3.0.7)
- Search for full name.
