### ISSUE TITLE
CSV: Handling of product Images

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/woocommerce#15855]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Used existing CSV which loads with the old products import CSV suite
2. 
3.

## Expected behavior and actual behavior

When I follow those steps, I see...
The none of the product images are being fetched from the (remote) URL and are not copied to the upload directory. 

I was expecting...
to see that pictures were fetched from remote location and placed in standard upload directory.

## Environment
Beta site is in /var/www/beta.vandenbussche.nl/web
images are in /var/www/www.speldorado.com/web/images (or https://speldorado.vandenbussche.nl/images) The url is given in the CSV.

This is because we have 30.000 images and 8.500 products but still we have an image for every product. The "old" import/merge finds the remote image (if any) and places it in "upload" and makes the link between product and image. 

Grab the system status report from WooCommerce > System Status and paste it here.
`
### WordPress Environment ###

Home URL: https://beta.vandenbussche.nl
Site URL: https://beta.vandenbussche.nl
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.18-0ubuntu0.16.04.1
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: shop_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Foutmeldingen zouden niet getoond moeten worden aan bezoekers.

### Active Plugins (12) ###

Adminer: door Frank Bültge – 1.4.5
BackWPup: door Inpsyde GmbH – 3.4.1
Boemerang Tools: door Egbert Jan van den Bussche – 3.2
Contact Form 7: door Takayuki Miyoshi – 4.8
Display Posts Shortcode: door Bill Erickson – 2.8.0
Easy WP SMTP: door wpecommerce – 1.2.5
TinyMCE Advanced: door Andrew Ozz – 4.6.3
Voorraadbeheer: door Dennis Claassens – 1.0
WooCommerce Beta Tester: door Mike Jolley – 1.0.3
WooCommerce: door Automattic – 3.1.0
WP Maintenance Mode: door Designmodo – 2.0.9
WP Desk Helper: door WP Desk – 1.3.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #5 - /winkel/
Winkelmand: #6 - /winkel/winkelwagen/
Afrekenen: #7 - /winkel/afrekenen/
Mijn account: #9 - /winkel/mijn-account/

### Theme ###

Name: 
Version: – 0 is beschikbaar
Author URL: 
Child Theme: ✔
Parent Theme Name: 
Parent Theme Version: – 0 is beschikbaar
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [] I can reproduce this bug consistently

**Comment by claudiulodro** [comment]
Can I get the first header line and at least one product's line from the CSV file you're using? It's going to be a lot more useful for me to determine what the issue is if I can see the raw data you're trying to use. :)

**Comment by EgbertJan** [comment]
Here is a CSV with only a few products. Very irritating is that de mapping is not saved. I have to do it over and over again which is absolutely out of the question in a prod. env. The header fields are based upon the original mapping as used in the Woo prod. import suite plugin. I cannot find all target fields (they are translated and I do not always understand them). My final attempt was an import of this CSV and none was imported with an error about the image not being found at the given URL. Some might not be available but the has never given any problem .

<CSV>
post_title,post_name,ID,post_excerpt,post_content,post_status,menu_order,post_date,post_parent,post_author,comment_status,sku,downloadable,virtual,visibility,stock,stock_status,backorders,manage_stock,regular_price,sale_price,weight,length,width,height,tax_status,tax_class,upsell_ids,crosssell_ids,featured,sale_price_dates_from,sale_price_dates_to,download_limit,download_expiry,product_url,button_text,images,downloadable_files,tax:product_type,tax:product_cat,tax:product_tag,tax:product_shipping_class,meta:product_ean,meta:product_supplier,meta:_yoast_wpseo_focuskw
"7ATE9 (999 Games)",,,01-999-7A901,"Chaotisch kaartspel, waarbij snel gerekend en gereageerd moet worden Je krijgt een gedekte stapel kaarten en probeert die zo snel mogelijk kwijt te raken. Er ligt 1 kaart open op tafel. Daar staat een groot getal en een klein getal met een plusminteken op. De volgende kaart die gespeeld moet worden is het grote getal plus of min het kleine getal. Daarbij wordt ""om een hoekje"" geteld. Zo is 9+2 bijvoorbeeld 1, en 3 - 4 = 9. Iedere speler mag nu één voor één en met maar 1 hand kaarten van zijn stapel trekken en eventueel spelen. Maar doe dat snel, want als een ander je voor is, ontstaat er weer een nieuwe som! Wie nog maar 1 kaart overheeft, mag deze gedekt op de stapel leggen en wint het spel!7ATE9 is een gezellig en spectaculair kaartspel. Voor jonge kinderen heeft het rekenelement ook een educatieve werking.",publish,,,,,closed,01-999-7A901,open,no,visible,4,instock,no,yes,9.99,8.99,,,,,,,,,,,,,,,,https://speldorado.vandenbussche.nl/images/01-999-7a901.jpg,,simple,SPELLEN>kaartspellen,"999 Games",STANDAARD,8717249195696,"999 Games",
"Agricola Expert-editie (999 Games)",,,01-999-AGR01B,"Verbeterde versie van het succesvolle, strategische bordspel Je hebt aan het begin van het spel niet meer dan een houten huis met 2 kamers, waarin 2 gezinsleden wonen. Je beschikt over een scala aan mogelijkheden om door middel van huisuitbreiding, landbouw en veeteelt een comfortabel leven op te bouwen. Je verzamelt grondstoffen zoals hout en leem, breidt je gezin uit en zorgt voor voldoende voedsel voor iedereen. Je ploegt akkers en beplant deze met graan en groente. Ook houd je schapen, varkens en runderen. Verder krijg je 14 unieke ambachten en kleine investeringen, die jou kleine voordelen in het spel opleveren. Omdat het spel 96 van die kaarten bevat, is geen spel hetzelfde! Heb jij je erf het best ontwikkeld, dan scoor je de meeste punten en win je!Deze nieuwe versie van Agricola bevat niet alleen de beste kaarten uit het originele spel, maar ook veel nieuwe. De houten fiches zijn vervangen door miniaturen en de tableaus zijn zeer praktisch vormgegeven. De speelborden kunnen nu als een puzzel worden gekoppeld. Verder zijn de kaarten beter gebalanceerd en bevat de handleiding verschillende varianten en spelregels om een campagne te kunnen spelen. In deze nieuwe edtie kunnen de spelers een compacter gestroomlijnd spel verwachten dat toch alle spanning en tactische mogelijkheden in zich draagt. De speelduur is korter geworden.",publish,,,,,closed,01-999-AGR01B,open,no,visible,2,instock,no,yes,49.99,41.99,,,,,,,,,,,,,,,,https://speldorado.vandenbussche.nl/images/01-999-agr01b.jpg,,simple,SPELLEN>strategiespellen,"999 Games",STANDAARD,8719214420949,"999 Games",
"Agricola: 2 Spelers (999 Games)",,,01-999-AGR04,"Deze opzichzelfstaande versie van het populaire agrarische spel ""Agricola"" is uitsluitend bedoeld voor 2 spelers. De spelregels zijn wat eenvoudiger dan die van het oorspronkelijke spel.In dit spel draait alles om de dieren. Je kiest zoals gebruikelijk met ieder van je knechten een actie en bouwt daarmee hekken om weiden te omheinen, stallen of andere speciale gebouwen. Verder houd je schapen, varkens, runderen en paarden, die aan het einde van het spel voor de nodige bonuspunten zorgen. Al je gebouwen en weiden hebben een bepaalde capaciteit, die door middel van voederbakken kan worden verhoogd.Omdat het spel maar een half uurtje duurt, is het uitstekend geschikt voor tussendoor. Ook ideaal om op reis mee te nemen als je met z'n tweetjes bent!",publish,,,,,closed,01-999-AGR04,open,no,visible,1,instock,no,yes,24.99,22.50,,,,,,,,,,,,,,,,https://speldorado.vandenbussche.nl/images/01-999-agr04.jpg,,simple,SPELLEN>gezelschapsspellen,"999 Games",STANDAARD,8717249197003,"999 Games",
</CSV>

Egbert Jan

**Comment by EgbertJan** [comment]
Addition: I am used to do a MERGE. If a product in the CSV is not already in the database (SKU), it would be imported in the old situation.
EJ

**Comment by EgbertJan** [comment]
The CSV given might be damaged in the process of publicitating here. The header ends with meta:_yoast_wpseo_focuskw. 
EJ

**Comment by mikejolley** [comment]
@EgbertJan Please stop comparing this to Product CSV import suite, it is not supposed to be compatible.

> If a product in the CSV is not already in the database (SKU), it would be imported in the old situation.

Update only updates, no creation.

>  Very irritating is that de mapping is not saved.

There are a standard set of column headers which auto-map. Not the same as CSV import suite.

**Comment by mikejolley** [comment]
@EgbertJan Please upload the CSV for us somewhere since the paste above is missing quote characters around each cell.

**Comment by EgbertJan** [comment]
I will try to upload somewhere else or can I email a zipped file? 

At the moment my only reference is the "good old" import suite. Hence my refs. to it. Please understand. At the moment I cannot switch to the new native importer yet. 

Where can I find a full list of officilal (english) column headers? I will change mij header accordingly with (hopefully) the net effect that my fields are automagically mapped to the right fields. The creation of the CSV is fully under my control. I can easily change the header.

Will a merge operation switch to an import operation (and assign an ID) for an new product? This old behaviour seems essential for us. 

TNX, EJ

**Comment by mikejolley** [comment]
If you do an export, it will show all headers :)

A zip is fine. Just upload to your media library and share the link.

**Comment by EgbertJan** [comment]
I used the attach function before I saw your reply... 

[merge.csv.gz](https://github.com/woocommerce/woocommerce/files/1112084/merge.csv.gz)

**Comment by EgbertJan** [comment]
I cannot export when there are no products in the site...

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/2xd5nglqps8ckqk/2017-06-29%20at%2013.58.png

Those were important successfully. I did a clean import, didn't map ID column.

**Comment by EgbertJan** [comment]
Wonderful! Did you map any other field?

**Comment by mikejolley** [comment]
I left default mappings for the others. Some of your fields in that CSV won't be compatible.  But images is working :)

Create a product manually, then export it. Then you can see all the default column headers and use that as a template!

**Comment by EgbertJan** [comment]
will do. Tnx for bearing with me...
CU, EJ

**Comment by EgbertJan** [comment]
I have a completely Dutch header now. Very ugly. But if it has to be so, I'll make it so... Isn't there a nice slug for each of the header fields that is recognized?

Can you please answer my earlier question when during a merge a new product is detected. Will it be imported? I really need that (old) functionality. It is nearly impossible to do a pure merge and a pure import.

**Comment by EgbertJan** [comment]
Yes. For things like a CSV header it is. 

That is why we do not use ID but only SKU. No insert during merge. That forces us to stick to the Woo import suite... Please do not retire it and keep it updated when needed.

EJ

**Comment by mikejolley** [comment]
Why do you need it? I don't understand the exact use case?

**Comment by EgbertJan** [comment]
Try to explain the user case.
If a merge/update operation cannot do insert/add operation, we have to do two operations: one for updated and one for new products. The CSV is currently generated from a separate set of tables in the shop database. These tables are updated with new and updated products from a third party XLSX. Products in this tabel get a time stamp for the last modification. But it could also be a newly inserted product. I cannot tell that without checking the woo tables to see if an SKU exists.  My CSV generator plugin selects all rows in the third party table with a timestamp later that the last time a CSV was generated (and some other flags). This was mainly because the large number of products. the TP tabel contains well over 18000 products of which about 8000 are loaded in the site (via the CSV ofcause). Deleting all products followed bij a full import takes way to much time and is unnessessary becaue most products are not changed at all. 
The shop keeper has learned to do the CSV generation and merge. Although it is a fairly strait forward process, it took quite some time to get him understand what he needs to do. Any change will repeat this learning curve. Certainly if it gets more steps. That is why I am so happy with the old suite. (i think I even have lifetime support on it...).
EJ

**Comment by mikejolley** [comment]
2 routines sounds more efficient to me. The update could for example only contain essential changed data and rows (quicker).

**Comment by EgbertJan** [comment]
When I also keep track of the highest ID (auto-increment field) during the last CSV generation, I could probably assume that any record in the TP table with an higher ID is a new product. Hmmm... Time to re-think the whole proces. Thanks for listening.
Egbert Jan.
