### ISSUE TITLE
Adding first product - include option to actually dismiss tool tips 

### ISSUE THREAD

**Issue by msdesign21** [woocommerce/woocommerce#15858]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] This is not an issue, it is a suggested enhancement 

## Steps to reproduce the issue

1. On a fresh install of WooCommerce, add your first product
2. Be bombarded by :allthetooltips:  
3. Continue to try to dismiss them all without getting frustrated 

## Expected behavior and actual behavior
It would be ideal to include a way to opt-out of the add a new product tool tips for those that don't prefer to learn that way or that don't need them. 

Possible example: 
<img width="70%" src="http://cld.wthms.co/wXkY0E+"/>

Dismiss would close for good. 

## User Testing Video 
As demonstrated yesterday in a usability test: 
<img src="http://cld.wthms.co/4yXjwO+"/>

**Comment by WPprodigy** [comment]
+1million for this! Exiting out of the walkthrough when you want to would be really helpful.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16109
