### ISSUE TITLE
[Functional request] Preset Variations for Variable Product based on tag/category/group

### ISSUE THREAD

**Issue by freshtofujam** [woocommerce/woocommerce#15869]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

When having large amounts of products with quite some variations per product, the database is getting bloated quite fast.

wp_postmeta has over a million records because of the amount of variations per product.

It would be great if there was a predefined variation group and attach it to a product, so it wouldn't have to create all the excess wp_postmeta data per product.

When using the api, creating a product increased from 2/4 seconds per product to around 20 seconds per product after the database started blowing up in size.

**Comment by mikejolley** [comment]
This should maybe be placed on woo ideas. TBH though, that type of relationship does not sound possible.  Post meta is 1:1 - there is no relationships table.

We do have some issues logged to rethink variations UI (https://github.com/woocommerce/woocommerce/issues/13085) and we're working towards a storage solution outside of post meta. This is long term but being thought about. I don't feel we need another issue logged for that aspect of this.

Thanks
