### ISSUE TITLE
Download Links in Account View Incorrect

### ISSUE THREAD

**Issue by S4racen** [woocommerce/woocommerce#15867]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Purchase Circuit Editor from Website (Free Product) https://isotonikstudios.com/product/novation-circuit-editor/
2. Download from Email Links - Pass all direct correctly
3. Download from Account Links - FAIL - All direct to a premium product file

## Expected behavior and actual behavior

When I follow those steps, I see... The right titles for download links in the account view but they actually link to an incorrect file

I was expecting... To download the file as it's configured in the product set up

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://isotonikstudios.com
Site URL: https://isotonikstudios.com
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.20
PHP Post Max Size: 64 MB
PHP Time Limit: 50000
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.1.73 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (48) ###

LayerSlider WP: by Kreatura Media – 6.5.1
Autoptimize: by Frank Goossens (futtta) – 2.2.2
CDN Enabler: by KeyCDN – 1.0.4
Disable Emojis: by Ryan Hellyer – 1.5.3
Far Future Expiration Plugin: by Tips and Tricks HQ – 1.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
Grant download permissions for past WooCommerce orders: by Claudio Sanches – 0.0.2
Redirect List: by MembershipWorks – 1.8
Remove Query Strings From Static Resources: by Speed Up My Website
Your WP Expert – 1.4

Simple Image Sizes: by Rahe – 3.1.1
SoundCloud Shortcode: by SoundCloud Inc. – 3.0.2
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.2.7

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.4

WCDPUE Pro: by Uriahs Victor – 1.3.0
WooCommerce Cart Count Shortcode: by Pronto Tools – 1.0.2
WooCommerce Payment Gateway Based Fees: by WooThemes – 3.0.5
WooCommerce Checkout Manager: by Visser Labs – 4.1.2
WooCommerce Conversion Tracking: by Tareq Hasan – 1.2.2
WooCommerce Currency Converter: by WooCommerce – 1.6.5
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.3.5
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce Nested Category Layout: by SkyVerge – 1.10.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.6
Woocommerce Sendy: by Sushil Kumar – 1.0
WooCommerce Support Ticket System: by Lagudi Domenico – 3.7
WooCommerce: by Automattic – 3.1.0
Wordfence Security: by Wordfence – 6.3.12
Yoast SEO: by Team Yoast – 4.9
WP Smush Pro: by WPMU DEV – 2.0.6.1
WP Super Cache: by Automattic – 1.4.9
WP Version in Query String Modifier: by joesat – 1.0.0.7
YITH WooCommerce Added to Cart Popup Premium: by YITHEMES – 1.2.2
YITH WooCommerce Advanced Reviews Premium: by YITHEMES – 1.4.3
YITH WooCommerce Affiliates: by YITHEMES – 1.1.0
YITH WooCommerce Ajax Product Filter Premium: by YITHEMES – 3.4.2
YITH WooCommerce Ajax Search Premium: by YITHEMES – 1.5.5
YITH WooCommerce Best Sellers Premium: by YITHEMES – 1.1.0
YITH WooCommerce Cart Messages Premium: by YITHEMES – 1.4.0
YITH WooCommerce Category Accordion Premium: by YITHEMES – 1.0.16
YITH WooCommerce Customize My Account Page: by YITHEMES – 2.1.0
YITH WooCommerce Dynamic Pricing and Discounts Premium: by YITHEMES – 1.2.7
YITH WooCommerce Multi Vendor Premium: by YITHEMES – 2.0.3
YITH WooCommerce Recover Abandoned Cart Premium: by YITHEMES – 1.1.4
YITH WooCommerce Review Reminder Premium: by YITHEMES – 1.3.1
YITH WooCommerce Role Based Prices Premium: by YITHEMES – 1.0.16
YITH WooCommerce Stripe Premium: by YIThemes – 1.3.0
YITH WooCommerce Tab Manager Premium: by YITHEMES – 1.1.23
YITH WooCommerce Terms & Conditions Popup: by Yithemes – 1.1.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
virtual (virtual)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #11514 - /shop/
Cart: #11515 - /cart/
Checkout: #11516 - /checkout/
My account: #11517 - /my-account/

### Theme ###

Name: Enfold Child
Version: 1.0
Author URL: http://www.kriesi.at
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.0.7
Parent Theme Author URL: http://www.kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled
`
</details>

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
@S4racen sometimes it serves a circuit file, sometimes a PDF. Both links are identical. I think this may be your CDN...

**Comment by S4racen** [comment]
That sounds like it is!! Turning it off works!!

Awesome, just got to figure out how not to CDN my Woocomfiles folder now…!!

Thank you!!

Cheers
D

On 29 Jun 2017, at 22:50, Mike Jolley <notifications@github.com> wrote:

@S4racen <https://github.com/s4racen> sometimes it serves a circuit file, sometimes a PDF. Both links are identical. I think this may be your CDN...
