### ISSUE TITLE
read_meta_data mangles very long meta_ids (integer overflow)

### ISSUE THREAD

**Issue by ragulka** [woocommerce/woocommerce#15866]
I ran into this on a customer's site where meta_ids are very-very long, for example `13332906696831108711`. When meta data is read, the [meta_id is cast to `(int)`](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L453), which will cause an [integer overflow](http://php.net/manual/en/language.types.integer.php#language.types.integer.overflow), and the meta_id will be changed to `9223372036854775807` (on a 64-bit system), which obviously is incorrect.

This in turn means that the meta key cannot be removed or updated, as WC CRUD will always try to do that based on the meta_id, for which in this case, there is no match found.

Of course this is a very rare corner case, but since the underlying SQL structure (`meta_id` in `wp_postmeta`) does use `BIGINT(20)`, it should likely be treated by PHP/WP/WC in ways that would not break it.

I'm not entirely sure why the cast to int there is necessary in the first place, so perhaps the easiest way would be to simply remove it?

Also, something else I noticed while debugging this - when updating a meta value by key (not meta_id), WC will actually the meta key first and then re-add it, instead of simply updating the existing meta key. Here's the backtrace:

1. Call `$order->update_meta_data( 'some_existing_key', 'new_value' );`
2. Since no `meta_id` was provided, this will result in calling `add_meta_data` [here](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L373)
3. `add_meta_data` will first mark any existing meta with `some_existing_key` for removal and will simply push the new meta key/value to the meta data array [here](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L347-L353)
4. Call `$order->save_meta_data()`
5. This will loop over `$order->meta_data` and run 2 SQL queries: 1 for [removing the existing meta](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L477) key/value and another one for [adding the new key/value](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L481-L482)

I'm not sure about the reasoning behind this approach, but to me it seems sub-optimal, as it uses 2 database queries instead of 1 + it will increment the `meta_id` for no good reason in the `wp_postmeta` table. Mind you that 3rd party extensions or outside systems connecting via the API may use the meta_id for linking together data, and that link will be lost/destroyed with this approach.

**Comment by mikejolley** [comment]
Meta keys can be used more than once, hence that logic.

**Comment by ragulka** [comment]
> Meta keys can be used more than once, hence that logic.

How about when the meta_key is unique? Would it be possible to short-circuit the remove-add logic there?

**Comment by mikejolley** [comment]
You can override it via your class, but core doesn't keep it unique.

**Comment by ragulka** [comment]
Well I'm no sure why though? If you call `$order->update_meta_data()`, [there's no way to say if this meta should be unique or not, but WC seems to assume it on line 373](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L364-L375). If you're assuming the meta will be unique, then why bother removing the old meta key and the re-adding it? You already know it will be unique, so you could just do override the meta value in the existing meta_data array, right? 

On line 366, WC checks for a matching meta_id, if provided. If one is not provided, it will defer to `add_meta_data` on line 373. Isn't this flawed? Shouldn't you look for a matching meta_id based on the meta_key if the meta_id is not provided? After all, his whole method assumes that meta keys are unique...

Also - any thoughts on the integer overflow issue above as well?

**Comment by unfulvio** [comment]
> Also - any thoughts on the integer overflow issue above as well?

this seems a 32-bit system issue: https://stackoverflow.com/questions/24002152/proper-way-of-converting-string-to-long-int-in-php

if anything, WC core could add a warning in the System Status page if PHP_INT_MAX is equal or below  2147483647 -- or if there's another way to detect if a system is 32bit recommending to switch to a 64 bit architecture that would work too

**Comment by mikejolley** [comment]
@ragulka have you tested the (int) removal? Side effects?

**Comment by ragulka** [comment]
@mikejolley I only tested it on the customer's site that was facing the integer overflow issue. I did not notice any side effects there.

However, quickly scanning over WP codebase, it seems that while meta_id is not always being cast to an integer, there are a few instances where it happens: `get_metadata_by_mid`, `update_metadata_by_mid`, `delete_metadata_by_mid` - all when directly dealing with a specific meta_id.

I'm not really sure about the purpose of casting the meta_id to an integer in those cases, as it will be cast to an integer by sprintf/wpdb->prepare later anyway, which also triggers the same integer overflow issue.

So it looks like this also happens in WP core when directly getting, updating or removing meta by it's ID. But not when updating by meta_key, as the meta id is never touched in those cases. I'm not sure what the best course of action would be here. 

My suggestion above for directly updating the meta (instead of doing remove + add) would at least work around this issue.

**Comment by mikejolley** [comment]
@ragulka So given WP core meta functions do indeed use intval (https://developer.wordpress.org/reference/functions/update_metadata_by_mid/) we seem to be inline with that. Input sanitization is important.

Maybe a core trac ticket should be logged?

I don't think meta_id is used as a foreign key here, so it could be dropped and recreated to start the index from 0 again. No idea why your index would be so high with regular usage :D 

> My suggestion above for directly updating the meta (instead of doing remove + add) would at least work around this issue.

For WC maybe, but the issue would still be there. Plus as I said earlier, we do it this way for a reason. If you have 2 values for the same meta_key, if you delete by key you lose both values. Thats why it works with meta_ids both in the WC_Data class and in the data store. meta_id is unique, meta_key is not.

I don't see much action we can take here.

**Comment by ragulka** [comment]
> If you have 2 values for the same meta_key, if you delete by key you lose both values.

@mikejolley this is exactly what's currently happening when calling `WC_Data::update_meta_data()` without the `$meta_id` param. First, it [calls `add_meta_data()` with the `$unique` param set to `true` here](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L373), which in turn [deletes _any_ existing meta keys here](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L347-L349), and finally [adds the meta key again](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L350-L353).

So, it looks like `WC_Data` _already_ assumes that meta keys are unique, at least when updating them. I'm not sure if this is the intended behaviour or simply a side effect?

Having taken a deeper look, I found that both `WC_Data::update_meta_data()` and `WC_Data::add_meta_data()` have discrepancies with how WP core `update_metadata()` and `add_metadata()` work:
* Calling `add_metadata()` with `$unique = true` will [simply not add the meta key/value if a value for the meta key already exists](https://codex.wordpress.org/Function_Reference/add_metadata#Parameters), it does not remove existing values.
* Calling `update_metadata()` will simply [update all values for the given meta key](https://codex.wordpress.org/Function_Reference/update_post_meta#Parameters), it does not attempt to ensure the meta key is unique.

I'm not sure if these differences are in intentional and if they are, I'm curious what was the reasoning behind it?

In any case, my argument is that `WC_Data::update_meta_data()` with no `$meta_id` param should behave similar to `update_metadata()` in WP core, which simply updates _all_ existing values for the given meta key. I would also expect `WC_Data::add_meta_data()` to align with WP core when it comes to the `$unique` param.

There's really no need to go and remove the existing meta key values _unless_ you want to ensure the meta key is unique. If you don't need to ensure that, you can simply update it. And it would save you at least 1 database query + would not bump the meta_id unnecessarily.

Does the above make sense or am I missing something here?

**Comment by mikejolley** [comment]
@ragulka I don't recall the reasoning from something built a year ago. All I know is this was made to be backwards compatible with both order item meta, and the "WP" style meta when implementing CRUD.

This is our layer on top after all so it doesn't matter if things work differently where it makes sense. If you really feel this is worth breaking backwards compatibility over send a PR for 4.0 review...but before doing so please ask yourself which way is better; WP or CRUD.

In fact, that just triggered some memories.

https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L345

The unique there is not supposed to mirror the [WP unique property](https://codex.wordpress.org/Function_Reference/add_post_meta). Unique in this context is just so the function can be used in the [update method](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L373). I think the naming being the same is just coincidental...

This is giving me a headache anyway. @justinshreve and @claudiosanches may want to chime in since they contributed to WC_Data.

**Comment by mikejolley** [comment]
@ragulka Are you going to move those meta parts to a PR? If so I'd like to close this issue since the OP about IDs is not being fixed.

**Comment by mikejolley** [comment]
I checked with Justin and it was indeed not built to be used in the same way as WP meta functions despite the naming. Our meta functions are quite different because everything is held in properties before being sent to the DB, whereas WP meta functions write to the DB right away.

If this could be changed like WP without breaking BW compat I'd be happy to review a PR, but it isn't a priority.
