### ISSUE TITLE
Automatic Cancel notifications not sent after cancelling payment at external payment gateway

### ISSUE THREAD

**Issue by Jannemanrobinson** [woocommerce/woocommerce#15876]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Order product and check out with ideal payment gateway (Sisow)
2. Cancel payment at external payment gateway
3. Return to shop

## Expected behavior and actual behavior

When I follow those steps, I see that the order is created with status cancelled

I was expecting to see a 'cancelled order' notification email being send but I can't see any email going out on my postman smtp log 

Manually sending the 'cancelled order' notification works fine.

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://bloemenbezorgendenhaag.net
Site URL: https://bloemenbezorgendenhaag.net
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) OpenSSL/1.0.2g
PHP Version: 7.0.20
PHP Post Max Size: 1 GB
PHP Time Limit: 0
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_1e603cbc9d_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Akismet Anti-Spam: door Automattic – 3.3.2
All In One WP Security: door Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.2.8

Contact Form 7: door Takayuki Miyoshi – 4.8
Features: door WooThemes – 1.5.0
Google Places Reviews: door WordImpress – 1.4.3
Kiyoh Customerreview: door kiyoh – 1.0.6
Loco Translate: door Tim Whitlock – 2.0.14
Postman SMTP: door Jason Hendriks – 1.7.2
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 2.2.6
Simple 301 Redirects: door Scott Nellé – 1.07
WooCommerce Sisow Betaal Opties: door Sisow – 4.7.0
Testimonials: door WooThemes – 1.5.4
WooCommerce Button Variations: door Candle Studio – 1.5.3
WooCommerce Checkout Field Editor Pro: door ThemeHiGH – 2.7.7
WooCommerce Google Analytics Pro: door SkyVerge – 1.3.4
WooCommerce Min/Max Quantities: door WooCommerce – 2.3.16 – 2.3.18 is beschikbaar
Woocommerce auto update order status: door N/A – 1.1
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 1.6.5
WooCommerce: door Automattic – 3.1.0
Yoast SEO: door Team Yoast – 4.9
WP Fastest Cache: door Emre Vona – 0.8.6.9
WP Product Feed Manager: door Michel Jongbloed – 1.5.0
Yoast SEO: Local: door Team Yoast and Arjan Snaterse – 4.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #6 - /ons-assortiment/
Winkelmand: #7 - /winkelwagentje/
Afrekenen: #8 - /afrekenen/
Mijn account: #9 - /mijn-account/

### Theme ###

Name: Flatsome Child Theme
Version: 2.5
Author URL: http:%20//www.uxthemes.com/
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.5
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome-child/woocommerce/checkout/payment.php
flatsome-child/woocommerce/checkout/review-order.php
flatsome-child/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome-child/woocommerce/emails/admin-cancelled-order.php
flatsome-child/woocommerce/emails/admin-new-order.php
flatsome-child/woocommerce/emails/customer-completed-order.php
flatsome-child/woocommerce/emails/customer-invoice.php
flatsome-child/woocommerce/emails/customer-new-account.php
flatsome-child/woocommerce/emails/customer-note.php
flatsome-child/woocommerce/emails/customer-on-hold-order.php
flatsome-child/woocommerce/emails/customer-processing-order.php
flatsome-child/woocommerce/emails/customer-refunded-order.php
flatsome-child/woocommerce/emails/customer-reset-password.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Unpaid orders do not get this notification any more since it's not needed in most cases e.g. abandoned paypal order.

```
add_action( 'woocommerce_order_status_processing_to_cancelled_notification', array( $this, 'trigger' ), 10, 2 );
		add_action( 'woocommerce_order_status_on-hold_to_cancelled_notification', array( $this, 'trigger' ), 10, 2 );
```

Those are the transitions which get the email.

**Comment by Jannemanrobinson** [comment]
Hi Mike, Thganks for your answer.

I'm using a third party payment gateway to handle ideal payments. Customers are redirected to the ideal payment gateway that is currently not 100% reliable. I have had a few of these cases the last month:
Notification form ideal Gateway: Payment Success
Status in Woocommerce shop: Payment Cancelled

Since I don't receive Cancelled emails anymore, I have to log into my shop every day to check if there are any cancelled payments.

Could you please let me know how I can enable cancelled emails again?

Hope you can help me out.

**Comment by mikejolley** [comment]
Sounds like you need to work out why ideal isn't updating orders, rather than relying on emails?

**Comment by Jannemanrobinson** [comment]
I am working on that too. Unfortunately the payment provider which handles the ideal payments happens to be a bank, that is not very cooperative. I'm thinking of switching to another payment provider if they don't come up with a proper solution. In the mean time I really need the cancelled emails to be send. 

Is there a fix to enable cancelled emails again? Hope you can help me out.

**Comment by mikejolley** [comment]
You could hook into the event `woocommerce_order_status_pending_to_cancelled` and trigger a custom email to yourself.
