### ISSUE TITLE
Order status notes don't show user name or correct color when individual order is edited

### ISSUE THREAD

**Issue by joelwills** [woocommerce/woocommerce#15874]
If you use the main Order screen and change an order status using Bulk Edit, this is recorded on an individual order in a grey/gray box with the username attached.

However if you edit an individual order and change the status within the order, it is in a purple box with no name attached:

![Screenshot](http://joelwills.com/FMGIQq+)

Link to image: http://joelwills.com/FMGIQq

**To replicate:**

1) Edit an order using Bulk Edit to change its status. 

2) View the individual order and under Order Notes see how it is recorded in a grey/gray box with the user display name attached.

3) Change the order status within the order and press Update.

4) The new order note shows in purple with no user name attached. 

**Expected:**

Manual order status changes should be in a grey/gray box with username attached when edited in an individual order, the same as they are when edited using Bulk Edit. 

Tested in WC 3.0.9 and 3.1 (same behavior) on Storefront with no other plugins active. 

Please let me know any questions, thanks!

**Comment by nishitlangaliya** [comment]
Fixes - 15874,

I have made some adjustment to sort out the issue. and done the PR https://github.com/woocommerce/woocommerce/pull/15877 . Please check for the same and let me know if any changes required.

Thanks

**Comment by nishitlangaliya** [comment]
Fixes- 15874,

HI Please ignore previous pr #15877, I have made other PR https://github.com/woocommerce/woocommerce/pull/15882 for check both condition in on if statement.

Thanks

**Comment by mikejolley** [comment]
This is fixed in https://github.com/woocommerce/woocommerce/pull/15891
