### ISSUE TITLE
problem with paypal with when i use price with comma

### ISSUE THREAD

**Issue by moltochic** [woocommerce/woocommerce#15872]
i am using WooCoomerce and Wordpress .. I enter my prices like 24,99€. The decimal position is separated by an "," and the thousand separator by an "." I Also tried to set the decimal to "." and the thousand to "" (empty)

The payment gateway is PayPal. After getting to the checkout and clicking on the "Pay with PayPal" link the following error appears:

in the url

**before:**
https://www.paypal.com/cgi-bin/webscr?cmd=_cart&business=webstore%40pissei.com&no_note=1&currency_code=EUR&charset=utf-8&rm=2&upload=1&return=https%3A%2F%2Fwww.pissei.com%2Fcheckout%2Forder-received%2F12988%3Fkey%3Dwc_order_59553cf9d093f%26utm_nooverride%3D1&cancel_return=https%3A%2F%2Fwww.pissei.com%2Fcart%2F%3Fcancel_order%3Dtrue%26order%3Dwc_order_59553cf9d093f%26order_id%3D12988%26redirect%26_wpnonce%3Dd694fb44e3&page_style=&image_url=&paymentaction=sale&bn=WooThemes_Cart&invoice=WC-12988&custom=%7B%22order_id%22%3A12988%2C%22order_key%22%3A%22wc_order_59553cf9d093f%22%7D&notify_url=https%3A%2F%2Fwww.pissei.com%2Fwc-api%2FWC_Gateway_Paypal%2F&first_name=francesco&last_name=innocenti&address1=via+garibaldi+2&address2=&city=montecatini+terme&state=Pistoia&zip=51016&country=IT&email=francescoinnocenti77%40gmail.com&night_phone_b=%2B39057324330&no_shipping=1&tax_cart=0.00&item_name_1=Calzino+Summer+Pois+-+S-M&quantity_1=1&amount_1=14,9&item_number_1=FANSCPOIS&item_name_2=Pantaloncino+Vortice+-+3xl&quantity_2=1&amount_2=104,9&item_number_2=VORTICEBB

**after**

https://www.paypal.com/webapps/shoppingcart/error?flowlogging_id=654cb283c7d24&code=AMOUNT_ERROR&mfid=1498758396232_654cb283c7d24

**in the page** 

There was a system error. Try later.

**Debug Info**

WordPress Version: 4.8
Current WordPress Theme: Crazy Diamond version 1.58
Theme Author: Lollum - http://www.lollum.com/
Theme URI: http://www.demo.lollum.com/crazydiamond
Active Plugins: akismet/akismet.php | backup-wp/backup-wordpress.php | coming-soon/coming-soon.php | cookie-notice/cookie-notice.php | debug-info/debug-info.php | duplicate-post/duplicate-post.php | enhanced-e-commerce-for-woocommerce-store/woocommerce-enhanced-ecommerce-google-analytics-integration.php | enjoy-instagram-instagram-responsive-images-gallery-and-carousel/enjoyinstagram.php | export-users-data-to-csv/users-data-to-csv.php | facebook-conversion-pixel/facebook-conversion-pixel.php | google-analytics-for-wordpress/googleanalytics.php | homepage-pop-up/mlab.php | icegram/icegram.php | instagram-feed/instagram-feed.php | js_composer/js_composer.php | lollum-framework/lollum-framework.php | mailchimp-wp/mailchimp-wp.php | ninja-forms/ninja-forms.php | oauth-twitter-feed-for-developers/twitter-feed-for-developers.php | postcode-shipping/postcode_shipping.php | revslider/revslider.php | sendgrid-email-delivery-simplified/wpsendgrid.php | shortcodes-ultimate/shortcodes-ultimate.php | smart-manager-for-wp-e-commerce/smart-manager.php | ssl-insecure-content-fixer/ssl-insecure-content-fixer.php | vo-locator-the-wp-store-locator/vo-locator.php | woocommerce/woocommerce.php | wordpress-seo/wp-seo.php | wp-google-maps/wpGoogleMaps.php | 
PHP Version: 5.6.30
MySQL Version: 5.5.54
Apache Version: Apache

The system worked correctly and suddenly i have this problem. If i set the prices without decimals pay pal works

Tell me if more informations need.

Thanks for the help

**Comment by moltochic** [comment]
This is helpful?

https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ2067

**Comment by mikejolley** [comment]
We convert to the correct format; what version of WC?

**Comment by moltochic** [comment]
Now i'm running 3.0.9 

I have also tried with 2.6.1 -  3.0.0 and the last version 3.1.0

The problem still remain

**Comment by mikejolley** [comment]
Please test https://github.com/woocommerce/woocommerce/pull/15887 This will be part of 3.2.
