### ISSUE TITLE
Rich class-wc-structured-data not showing on single product page (3.1)

### ISSUE THREAD

**Issue by Trebacz** [woocommerce/woocommerce#15873]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Upgraded existing site from wordpress 3.09 to 3.1
2. Analyze product page in Google Structured data testing tool.
3. Look under the "Product" tab in the testing tool and the information is very truncated.

## Expected behavior and actual behavior

When I follow those steps, I see...
Prior to 3.1 upgrade (3.09 enviroment): https://search.google.com/structured-data/testing-tool/u/0/#url=%20https%3A%2F%2Fproto.glasshousestore.com%2Fproduct%2Fglass-fusing-makes-me-hot-tee-shirt%2F
After 3.1 upgrade: https://search.google.com/structured-data/testing-tool/u/0/#url=%20https%3A%2F%2Fwww.glasshousestore.com%2Fproduct%2Fglass-fusing-makes-me-hot-tee-shirt%2F
I was expecting...
Similar JSON+LD information to be generated by Woocommerce. I removed all plugins and went back to the Storefront theme and get the same behavior since the upgrade.
## Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://www.glasshousestore.com
Site URL: https://www.glasshousestore.com
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 356 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.14
PHP Post Max Size: 65 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

a3 License Manager: by A3 Revolution – 1.0.2
Akismet Anti-Spam: by Automattic – 3.3.2
All In One SEO Pack: by Michael Torbert – 2.3.13.2
BackupBuddy: by iThemes – 8.0.0.3
iThemes Security: by iThemes – 6.2.1
Contact Form 7: by Takayuki Miyoshi – 4.8
Duplicate Post: by Enrico Battocchi – 3.2
Google Customer Reviews for WooCommerce: by eCreations – 1.0.3
Enable Media Replace: by Måns Jonasson – 3.0.6
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.21
Enhanced Media Library: by wpUXsolutions – 2.4.5
Facebook for WooCommerce: by Facebook – 1.4.2
Fast Velocity Minify: by Raul Peixoto – 2.1.2
Flamingo: by Takayuki Miyoshi – 1.6
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
WooCommerce - Gift Cards: by WP Ronin – 2.5.10
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.0.1
iOS Images Fixer: by Bishoy A. – 1.2.3
Jetpack by WordPress.com: by Automattic – 5.0
LH Archived Post Status: by Peter Shaw – 2.15
Lightweight Grid Columns: by Tom Usborne – 0.7
MailPoet - Contact Form 7 Integration: by Jesse Pearson – 1.0.7.5
N-Media WooCommerce Personalized Product Meta Manager: by Najeeb Ahmad – 7.8
OPcache Dashboard: by Daisuke Takahashi(Extend Wings) – 0.3.1
PayPal for WooCommerce: by Angell EYE – 1.4.5
PayPal IPN for WordPress: by Angell EYE – 1.1.0
Postman SMTP: by Jason Hendriks – 1.7.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Robo Gallery: by RoboSoft – 2.6.16
Robo Gallery Key: by RoboSoft – 1.4
Social Media Follow Buttons Bar: by Arthur Gareginyan – 4.12.1
Srizon Facebook Album: by Afzal – 3.3
Storefront Blog Customiser: by WooThemes – 1.2.1
Storefront Blog Excerpt: by Wooassist – 1.1.2
Theme Customisations: by WooThemes – 1.0.0
Udinra All Image Sitemap: by Udinra – 3.5.1
Facebook Open Graph, Google+ and Twitter Card Tags: by Webdados – 2.0.8.2
WooCommerce Advanced Review Reminder: by kodemann.com – 2.2
WooCommerce Stripe Gateway: by WooCommerce – 3.2.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce Predictive Search PRO: by a3rev Software – 4.3.0
WooCommerce Shipping Estimates: by SkyVerge – 2.1.0
WooCommerce ShippingEasy Integration: by WooThemes – 3.4.1
WooCommerce: by Automattic – 3.1.0
WooCommerce Google Feed Manager: by Michel Jongbloed – 1.8.1
WP Super Cache: by Automattic – 1.4.9
MailPoet Newsletters: by MailPoet – 2.7.10

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude-from-search (exclude-from-search-2)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)


### WC Pages ###

Shop base: #250 - /shop/
Cart: #251 - /cart/
Checkout: #252 - /checkout/
My account: #253 - /my-account/

### Theme ###

Name: Boutique
Version: 2.0.9
Author URL: http://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.4
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by Trebacz** [comment]
I can confirm that a quick revert of the one line has temporarily fixed the issue on our production server (class-wc-structured-data.php). Assuming there are no other repercussions of the change... Thanks for the quick action... This should keep Google and others happy for awhile :+1:

**Comment by jsmusiker** [comment]
Can someone please reply here with the line of code to get the prices back? And instructions on where to put it. @Trebacz @claudiulodro 
Thanks

**Comment by WPprodigy** [comment]
@jsmusiker you can find that information here: https://github.com/woocommerce/woocommerce/pull/15875/files

Or just wait for the next patch release.

**Comment by jsmusiker** [comment]
@WPprodigy Thanks I ended up finding it. But I am not a developer, I do not know the correct way to add it back. And I do not know where to add it in class-wc-structured-data.php.

**Comment by WPprodigy** [comment]
You'll need to wait for the release then, as I can't do it for you.

**Comment by jsmusiker** [comment]
Unfortunately that's not a option for us. We can't afford to lose pricing in Search.

**Comment by jsmusiker** [comment]
Could someone please add that code back to the file and post the complete code somewhere we can just copy then paste?

**Comment by WPprodigy** [comment]
That is a link to the complete code...

https://github.com/woocommerce/woocommerce/blob/6706da6d458b7abf82bf5fb034539e49cf149c46/includes/class-wc-structured-data.php

**Comment by jsmusiker** [comment]
Thank you much appreciated. Is that the new structured data code for 3.1 ?
