### ISSUE TITLE
3.1.0 - Order Completing but no Download Permissions or 'New Order' email

### ISSUE THREAD

**Issue by wildambience** [woocommerce/woocommerce#15881]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Order placed for downloadable product & paid for via Paypal
2. Order completes and customer receives only the receipt from Paypal - no invoice or 'new order' email from the Woocommerce store
3. By manually regenerating download permissions and manually resending 'new order' or 'order invoice'  customer now receives the links to downloadable products. 

## Expected behavior and actual behavior

This was working fine until I updated to 3.1.0 & also updated to version 2.1.6 of the Amazon S3 Storage plugin.

### WordPress Environment ###

Home URL: https://wildambience.com
Site URL: https://wildambience.com
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 388 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.20
PHP Post Max Size: 27 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Divi Widget Builder: by Stephen James – 1.0
Akismet Anti-Spam: by Automattic – 3.3.2
WP Offload S3 Lite: by Delicious Brains – 1.2
Amazon Web Services: by Delicious Brains – 1.0.3
Bloom: by Elegant Themes – 1.2.6
Custom Sidebars: by WPMU DEV – 3.0.8.1
Divi/Extra Layout Injector: by Sean Barton - Tortoise IT – 2.3
Duplicate Post: by Enrico Battocchi – 3.2
Divi Map Module Extended: by Divi Web Design – 1.3.1
Jetpack by WordPress.com: by Automattic – 5.0
MailChimp: by MailChimp – 1.5.7
Media Player Style Kit: by Hugh Lashbrooke – 1.0
Redirection: by John Godley – 2.6.2
W3 Total Cache: by Frederick Townes – 0.9.5.4
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.6
WooCommerce Colors: by WooThemes – 1.0.6
WooCommerce: by Automattic – 3.1.0
Yoast SEO: by Team Yoast – 4.9
WP Meta and Date Remover: by Prasad Kirpekar – 1.4
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.91
WP Rollback: by WordImpress – 1.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #689 - /albums/
Basket: #5785 - /cart/
Checkout: #5786 - /checkout/
My account: #5787 - /my-account/

### Theme ###

Name: Divi Wild Ambience Child Theme
Version: 1.0.0
Author URL: https://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.53
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
Could be an IPN issue: https://docs.woocommerce.com/document/paypal-standard/#section-27

**Comment by seerdekens** [comment]
I have the same issue since upgarding to 3.1.0.
I'm not using Paypal, but Mollie (a payement broker). The only thing what has changed is the Paypal version,

**Comment by wildambience** [comment]
When I check on each order, the status is showing either PDT or IPN payments as successfully completed.

**Comment by mikejolley** [comment]
If you only have a 'completed' note, but not 'order status changed' note, something stopped the request.

This could be a plugin for example doing something to orders during status change.

Find your PHP error log and send it to us in your ticket: https://woothemes.zendesk.com/agent/tickets/596594

Reply there.
