### ISSUE TITLE
[UX] Quick order status update action buttons

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce#15889]
In all contexts I am aware of the 3 dots icons symbolizes something like a "More options" menu. At least in all three mayor browsers like Chrome, Edge and Firefox (with the upcoming new menus in Firefox 56)

When clicking on the 3 dots icon I would assume that a menu pops up letting me set the order status to any of the possibilities:

![3_dots_icon](https://user-images.githubusercontent.com/12525563/27731523-944c44a2-5d8d-11e7-924e-b796b62744bc.png)

Instead this stands for "processing". I personally have always find this confusing  (same icon but different meaning between browser and woocommerce) and think another icon should be used for "processing", maybe something like a working hand or similar.

**Comment by mikejolley** [comment]
What is "a working hand"?...

**Comment by gerdneuman** [comment]
... you don't seem to be socialist ;) 
https://openclipart.org/detail/279568/man-weilding-a-hammer 
https://openclipart.org/detail/151477/hammer-in-hand

Anyway, something like a "tool", e.g. a hammer would symbolize "in progress" (working at it) to me. Though I cannot find anything immediately looking at http://fontawesome.io/icons/ 

Maybe an hour glass with rinsing sand would do http://fontawesome.io/icon/hourglass-start/

**Comment by jameskoster** [comment]
I understand the potential confusion. Although our icon predates Material design I believe xD

The tooltip explains what is happening so I don't think this is urgent. (We should update the tooltip to say "Mark as processing" rather than "Processing" though - separate issue).

That of course is not visible on mobile so this needs to be addressed somehow. I'm not keen on any of the suggested icons because they have alternative interpretations. There is no universally recognisable icon for 'processing' that I can think of.

Imo we should redesign the actions here. Potentially to use a `select` with a go button. Similar to the actions meta box on the single order screen.

**Comment by gerdneuman** [comment]
> There is no universally recognisable icon for 'processing' that I can think of.

Don't you have some designers at Woo/WordPress? Usually devs aren't UX or visual experts usually. I think everything like "working", "in progress" would do better than ...

> Imo we should redesign the actions here. Potentially to use a select with a go button. Similar to the actions meta box on the single order screen.

Actually, I like it that it is one click. Select would mean 2-3 clicks I guess.

FWIW, here's a Firefox with the upcoming Quantum/Photon changes coming with Firefox 57 in Nov:
![2017-06-30 13_57_05-nightly start page - nightly](https://user-images.githubusercontent.com/12525563/27734717-7499f28a-5d9c-11e7-8eb6-fd793c78b643.png)

...and here's current Edge:
![2017-06-30 13_58_29-start - microsoft edge](https://user-images.githubusercontent.com/12525563/27734718-749a527a-5d9c-11e7-8499-868c8234fab0.png)

So, sure you've been first but you can't work against the browser :-P

**Comment by gerdneuman** [comment]
Last try (I propose ;). How about a loop with arrows. Something like 
![image](https://user-images.githubusercontent.com/12525563/27734934-7349f9d8-5d9d-11e7-93ce-760ff1daab6b.png)

so that it does not look like a "Reload" button

(without the white space it would be even better I think, that is, one line only)

There's more like this: https://duckduckgo.com/?q=loop+arrow&t=ffhp&iax=1&ia=images

**Comment by mikejolley** [comment]
It's still abstract. It could literally mean anything...

This also affects the status icon on the left of orders.

**Comment by claudiulodro** [comment]
IMO [the loading spinner thing](https://d1yn1kh78jj1rr.cloudfront.net/preview/process-icon-shapes_fJL27Jtu_M.jpg) might be a good "processing" icon, since generally things are "processing" while it's displayed. 

It also might be confusing. Not sure if people would think something's loading there. :)

**Comment by WPprodigy** [comment]
> Actually, I like it that it is one click. Select would mean 2-3 clicks I guess.

Being able to quickly change the status in one click is nice, but it's not very helpful if most people don't understand what the buttons mean in the first place. This UX also worsens when you have more custom order statuses with icons as well.

I wonder what the use case actually is for quickly changing the order status on the order-list page? If your orders needed fulfillment, I would think the store management would need to be clicking into the orders to get the information anyway. If people scroll through the orders just auto-completing or going straight to processing, there may be an issue in the workflow (they should be using virtual & downloadable products for example, or somethings wrong with the gateway thats not sending orders to processing).

I like the idea of rethinking this, and perhaps using a select instead. It makes the UX consistent across the order-list and single-order pages, and provides more context as to what the user's options actually are.

**Comment by jameskoster** [comment]
> So, sure you've been first but you can't work against the browser :-P

Exactly, I was just making the point that we didn't make the decision to do that by using the same icon haha :D

I'm not worried about 2 clicks to update order status when the trade-off is a clearer UX. 

A `select` scales better with extensions (and is easier to integrate with). It's better for accessibility and localisation as well.

But @WPprodigy makes a good point, I wonder how often these actions really get used. We didn't include them in our designs for WC on WordPress.com. We should probably leave them for now (replace with `select`) but I think we can consider removing them in the future.

**Comment by mikejolley** [comment]
This is being worked on in branch: https://github.com/woocommerce/woocommerce/pull/16700
