### ISSUE TITLE
Variation products and grayed selection doesn't working right 

### ISSUE THREAD

**Issue by gntoum** [woocommerce/woocommerce#15883]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.Create a variable product
2.Set 2 attributes (color - size)
3.Make variation foreach compination
4.Set a few variations out of stock and the other as in stock
5.Set in woocommerce settings page, the out of stock products to be hidden
6.Try to play with variation compinations in single product page

## Expected behavior and actual behavior

When i have a product with 2 attributes (size - color), and i have selected the "out of stock" products to be hidden, in my product view page, i expected when i choose the color of the product then the availables sizes to be selectable and the others grayed out. Also this must be refreshed if i change the color.

Instead of this, when i select another color of the product, the available size selection remain the same from the previous color selection. I have to select and another size (if i am lucky and it's available) to be refresh the available options.

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://socialadvisor.gr/shefashion
Site URL: http://socialadvisor.gr/shefashion
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: el

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Το κατάστημά σας δε χρησιμοποιεί HTTPS. Μάθετε περισσότερα σχετικά με το HTTPS και τα πιστοποιητικά SSL.
Hide errors from visitors: ✔

### Active Plugins (20) ###

Redux Framework: από τον/την Team Redux – 3.6.5
Ajax Search Lite: από τον/την Ernest Marcinko – 4.7.6
Bloom: από τον/την Elegant Themes – 1.2.3
Google Analyticator: από τον/την SumoMe – 6.5.3
Instagram Feed: από τον/την Smash Balloon – 1.4.9
Logo Carousel Slider: από τον/την ADL Plugins – 1.5
Nav Menu Roles: από τον/την Kathy Darling – 1.8.6
New Facebook Pixel with Standard Events for WooCommerce: από τον/την GhostMonitor – 1.4.0
Woocommerce Onsale Page: από τον/την wpgenie – 1.0.9
Pylon and Woocommerce Integration: από τον/την SocialMind – 1.0.0
Regenerate Thumbnails: από τον/την Alex Mills (Viper007Bond) – 2.2.6
Smart Variations Images Pro: από τον/την David Rosendo – 3.2.30
WooCommerce AJAX Products Filter: από τον/την BeRocket – 2.0.6.48
WooSwatches - Woocommerce Color or Image Variation Swatches: από τον/την parbat chaudhari – 2.3.6
WooCommerce Product Image Flipper: από τον/την jameskoster – 0.3.0
WooCommerce Social Media Share Buttons: από τον/την Toastie Studio – 1.3.0
Woocart Popup Lite for WooCommerce: από τον/την Festi-Team – 1.1
WooCommerce: από τον/την Automattic – 3.1.0
WP Live Chat Support: από τον/την WP-LiveChat – 7.1.02
YITH WooCommerce Wishlist: από τον/την YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Βάση καταστήματος: #39 - /shop/
Καλάθι: #40 - /cart/
Ταμείο: #41 - /checkout/
Ο λογαριασμός μου: #42 - /my-account/

### Theme ###

Name: Divi - Child theme
Version: 0.1
Author URL: http://www.socialmind.gr
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.51
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
I found your test product with the issue. Note you are using:

> WooSwatches - Woocommerce Color or Image Variation Swatches: από τον/την parbat chaudhari – 2.3.6

This implements logic on top of the defaults. You need to confirm this happens without swaches to be a valid bug in core.. 

In tests it works as expected.
