### ISSUE TITLE
Bulk Stock products not changing Status

### ISSUE THREAD

**Issue by zarausto** [woocommerce/woocommerce#15880]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. /wp-admin/edit.php?product_cat=custom_cat
2.Select on or two. Click bulk Edit.
3.Try to change In Stock to Out of Stock
4.Nothing changes

## Expected behavior and actual behavior

It should change the product stock status.
## Environment
<details>
`
### WordPress Environment ###

Home URL: https://loja.acervochrome.com.br
Site URL: https://loja.acervochrome.com.br
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18
PHP Post Max Size: 40 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Adminimize: por Frank Bültge – 1.11.2
Advanced Custom Fields: por Elliot Condon – 4.4.11
Contact Form 7: por Takayuki Miyoshi – 4.8
Duplicate Post: por Enrico Battocchi – 3.2
Easy Review Reminders: por Rymera Web Co – 1.2.3
Force Regenerate Thumbnails: por Pedro Elsner – 2.0.6
Reduzir estoque de pedidos manuais do WooCommerce: por Claudio Sanches – 1.0.1
Relevanssi: por Mikko Saari – 3.5.11
Slider Revolution: por ThemePunch – 5.4.5.1
W3 Total Cache: por Frederick Townes – 0.9.5.4
Woo Awaiting Reviews: por Fausto Rodrigo Toloi – 1.0.5
Woo Show your Reviews: por Fausto Rodrigo Toloi – 1.0.0
WooCommerce Correios: por Claudio Sanches – 3.4.1
WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.6.0
Integração do Google Analytics com o WooCommerce: por WooCommerce – 1.4.3
WooCommerce Installments: por Anderson Franco – 1.4.0
WooCommerce MercadoPago: por Claudio Sanches – 2.0.9
WooCommerce PagSeguro: por Claudio Sanches – 2.12.5
WooCommerce: por Automattic – 3.1.0
Yoast SEO: por Equipe da Yoast – 4.9
WP-Mail-SMTP: por WPForms – 0.10.1
WP Smush: por WPMU DEV – 2.7.1
YITH WooCommerce Wishlist: por YITHEMES – 2.1.2
Zendesk Chat Widget: por Zopim – 1.4.11

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base da loja: #4 - /produtos/
Carrinho: ❌ A página não contém shortcode.
Finalizar compra: ❌ A página não contém shortcode.
Minha conta: ❌ A página não contém shortcode.

### Theme ###

Name: Acervo Chrome (C)
Version: – 0 está disponível
Author URL: 
Child Theme: ✔
Parent Theme Name: Acervo Chrome (20)
Parent Theme Version: – 0 está disponível
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: acervochrome-child/woocommerce/archive-product.php
acervochrome/woocommerce/cart/cart-empty.php versão 2.0.0 está desatualizado. A versão do core é 3.1.0
acervochrome/woocommerce/cart/cart.php versão 3.0.3 está desatualizado. A versão do core é 3.1.0
acervochrome/woocommerce/cart/mini-cart.php versão 2.5.0 está desatualizado. A versão do core é 3.1.0
acervochrome/woocommerce/content-product.php
acervochrome/woocommerce/content-single-product.php
acervochrome-child/woocommerce/emails/email-styles.php
acervochrome/woocommerce/loop/loop-end.php
acervochrome-child/woocommerce/loop/loop-start.php
acervochrome/woocommerce/loop/no-products-found.php
acervochrome-child/woocommerce/loop/pagination.php
acervochrome/woocommerce/notices/error.php
acervochrome/woocommerce/notices/notice.php
acervochrome/woocommerce/notices/success.php
acervochrome-child/woocommerce/order/order-details.php
acervochrome/woocommerce/single-product/add-to-cart/external.php
acervochrome-child/woocommerce/single-product/meta.php
acervochrome/woocommerce/single-product/product-image.php versão 3.0.2 está desatualizado. A versão do core é 3.1.0
acervochrome/woocommerce/single-product/product-thumbnails.php versão 3.0.2 está desatualizado. A versão do core é 3.1.0
acervochrome/woocommerce/single-product/sale-flash.php
acervochrome/woocommerce/single-product/tabs/additional-information.php
acervochrome/woocommerce/single-product/tabs/description.php
acervochrome/woocommerce/single-product/tabs/tabs.php
acervochrome/woocommerce/single-product/title.php

Outdated Templates: ❌Aprenda como atualizar
`

</details>

## Isolating the problem
- [ ] This bug happens with only WooCommerce plugin active
-- I couldn't test in this way as store already in production mode
- [ ] This bug happens with a default WordPress theme active, or [Storefront]
-- I couldn't test in this way as store already in production mode
- [X] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Tested and working. I think you may be editing a different product type, such as variable. Variable stock status is not user set, it's determined by the children. Thats why it cannot be set. We're aware this can be confusing in the UI and are working on this in the future.
