### ISSUE TITLE
WooCommerce Subscriptions version 2.2.8, change subscription is not working

### ISSUE THREAD

**Issue by anhducbkhn** [woocommerce/woocommerce#15884]
## Environment
- Woocommerce Subscription version 2.2.8
- Woocommerce 2.6.4
- Wordpress 4.5

## Steps to reproduce the issue

1. I signup a variant subscription product
2. Checkout successfully
3. Go to account page -> view subscription --> click on change subscription. It bring me to domain.com/product/product-name/?switch-subscription=268286&item=17195&_wcsnonce=620d0dc157

and get error.

This is log

> [30-Jun-2017 04:53:22 UTC] PHP Fatal error:  Call to undefined method WC_Subscription::get_parent_id() in /var/www/domain.com/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscription.php on line 1796

Please help

**Comment by mikejolley** [comment]
Please use the helpdesk so the subscriptions developers can be cc'ed in. https://woocommerce.com/contact-us/
