### ISSUE TITLE
missing DOING_AUTOSAVE test, risky without it, and not aligned with other core code

### ISSUE THREAD

**Issue by diablodale** [woocommerce/woocommerce#15896]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce
- [ X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ X] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. View code in woocommerce\includes\admin\class-wc-admin-meta-boxes.php
2. Go to method save_meta_boxes()
3. See missing boolean test for DOING_AUTOSAVE

## Expected behavior
Core code should check the value of DOING_AUTOSAVE as per core Wordpress spec and core Woocommerce does in bulk_and_quick_edit_save_post()

## Actual behavior
Existing core code does not check the value of DOING_AUTOSAVE. Therefore, values of false, "foobar", and 42 all will cause havok with this code.

The simple fix is to change the line of code within save_meta_boxes()
from
```php
if ( defined( 'DOING_AUTOSAVE' ) || is_int( wp_is_post_revision( $post ) ) || is_int( wp_is_post_autosave( $post ) ) ) {
```
to
```php
if ( ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) || is_int( wp_is_post_revision( $post ) ) || is_int( wp_is_post_autosave( $post ) ) ) {
```

**Comment by claudiulodro** [comment]
In the future we also accept pull requests if you don't want to submit an issue with a long description of everything. :)

**Comment by diablodale** [comment]
We were working in parallel. :-) Pull request submitted.
