### ISSUE TITLE
paypal gateway doesn't allow class of test scenarios of status = pending

### ISSUE THREAD

**Issue by diablodale** [woocommerce/woocommerce#15899]
There is a class of test scenarios that are not able to be tested in sandbox due to the longstanding Paypal gateway shortcircuit of state=pending to immediate state=completed. The only known workaround is to remove/disable two lines in class-wc-gateway-paypal-ipn-handler.php. The two lines are

```php
// Sandbox fix.
if ( isset( $posted['test_ipn'] ) && 1 == $posted['test_ipn'] && 'pending' == $posted['payment_status'] ) {
    $posted['payment_status'] = 'completed';
}
```

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue

## Repro steps

1. Fully working Woocommerce setup with Paypal pdt/ipn in place for _**sandbox**_
2. Paypal account linked is a USD-only account
3. Paypal account has the default profile setting of accept/deny non-matching currencies
4. Customer pays from their Euro-based Paypal account

## Expected behavior

The order should remain in status=pending because a payment was made but it requires human intervention on Paypal to deal with it. This allows for testing of both Woocommerce code and the human process around it for handling scenarios as above.

## Actual behavior

The order is silently and automatically completed. It is not possible to test pending payment scenarios as above. I believe everyone should be able to test in _sandbox_ the Woocommerce code and their human processes for handling payments.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently

## Notes

I found several issues in this repro which treat this behavior as expected, but no issues which inquire into the behavior itself. I quickly found this issue in Paypal Gateway 2.0.0 during my testing several years ago. I have a Euro-based Paypal account with many USD customers. This issue is still present in gateway 2.3.0 which is part of the current Woo 3.x generation.

I acknowledge there may be scenarios where the silent treatment ;-) is desired. Therefore, a discussion here in this issue is desired.

**Comment by mikejolley** [comment]
@diablodale Last time I tested this, PayPal IPN never sent back completed status on sandbox. Thats a more important test case, and one we need to force.

Have you ever gotten back completed from sandbox?

**Comment by diablodale** [comment]
Yes I have. Was in my testing of my now live 2.x store. There are settings in Paypal's sandbox config that need to be made. Two possible reasons; one in my OP and both discussed here https://stackoverflow.com/questions/4298117/paypal-ipn-always-return-payment-status-pending-on-sandbox

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15933
