### ISSUE TITLE
Subscription Price is showing Highest as the "From price"

### ISSUE THREAD

**Issue by ryanbarron** [woocommerce/woocommerce#15894]
When viewing a subscription item the "From price" shows the highest dollar amount instead of the lowest amount. The item does have variations to it. The item variations are storage amounts; 250,500,1000,1500, etc. Not sure if the counting is the issue, but the logic should be evaluate the prices and find the lowest. What appears to be happening is the system is order based on the variation ID not the actual cost.

**Comment by claudiulodro** [comment]
Is this a problem in the WooCommerce Subscriptions plugin? If so, you should [file a support ticket](https://woocommerce.com/my-account/create-a-ticket/).

We can only handle bugs in the core WooCommerce plugin on GitHub, and subscriptions aren't part of that.
