### ISSUE TITLE
WC_Cart -> add_fee() does not work outside woocommerce_cart_calculate_fees action hook

### ISSUE THREAD

**Issue by diablodale** [woocommerce/woocommerce#15904]
WC_Cart add_fee() does not work unless it is called within the 'woocommerce_cart_calculate_fees' hook. The documentation is unclear and I suggest the documentation and the code comments be updated to clearly state the limitation that this API only functions correctly when called within a 'woocommerce_cart_calculate_fees' action.

I found this while porting my plugin code from Woo 2.1.x -> 3.1.x. The approach to assign fees has changed between those versions and add_fees() is now limited to only function within a 'woocommerce_cart_calculate_fees' action. Previously, it could be called in many situations on a cart. I was doing it in a 'woocommerce_after_checkout_validation' action hook. That won't work anymore.

Technically, this is due to the first line of calculate_totals() when all fees are erased due to the reset() which uses the $cart_session_data template to replace previously saved fees via cart->add_fee() with an empty array. To me, this is odd behavior. I only found the cause by tracing the Woocommerce code in a debugger to find the culprit. However, it should not be any further problem with clearer documentation.

In the docs at https://docs.woocommerce.com/document/add-a-surcharge-to-cart-and-checkout-uses-fees-api/ are examples. All the examples are within a woocommerce_cart_calculate_fees hook, yet the page doesn't state it **_must_** be within that hook. I recommend the API docs, example page, and core code comments all be updated to state the context limitation of the add_fee() api.

Comments?

**Comment by mikejolley** [comment]
The fees API has not changed in 3.x?

https://github.com/woocommerce/woocommerce/blob/4f66d214fa98e0f41f546972a5d6d0d1970594c2/includes/class-wc-cart.php#L2041-L2042

This filter has always been there ^ It's needed because for one thing, fees do not persist across page loads.

Here it is identical in 2.6 https://github.com/woocommerce/woocommerce/blob/2.6.14/includes/class-wc-cart.php#L1997

**Comment by diablodale** [comment]
I'm not asking for a code change or bug fix. Instead, requesting an update in the documentation that add_fees() is will only function within a 'woocommerce_cart_calculate_fees' action.

Without that documentation, Woocommerce devs like myself will not have the knowledge to understand why their call to add_fee() fails to appear in the order. There are many hooks between a customer clicking 'place order' in the UI and a payment gateway receiving a packet of order data. That is the transition from a cart to an order. A dev can not use any of those hooks except 'woocommerce_cart_calculate_fees ' for add_fees(). Any usage outside that hook will fail due to the reasons in my OP above.

That's why I request the documentation be updated. A single sentence at the URL above, add_fee() doc, and in the comment header of it in the codebase. That will then educate a Woocommerce dev how to use the API and prevent loss of time debugging/tracing like I had to do.

**Comment by mikejolley** [comment]
I've added a note in the codebase. All the examples on the URL in docs use `woocommerce_cart_calculate_fees`.

**Comment by diablodale** [comment]
Great, thanks. As CASE said "safety first". ;-)

**Comment by larssn** [comment]
Sorry to bump and old thread, but it's pretty unintuitive that fees are basically not persisted in any way in the cart, if you don't add them in the above hook.

Would it not be better to store them on the WC session object or something to that effect?
