### ISSUE TITLE
remove type="tel" from credit card expiration field b/c no slash provided on iphone

### ISSUE THREAD

**Issue by contemplate** [woocommerce/woocommerce#15902]
We've had numerous reports of people not being able to checkout on their iPhones b/c the credit card expiration field requires a slash in order to validate (with the Stripe WooCommerce gateway) but the numeric keypad that comes up from type="tel" doesn't offer a slash.

Once I removed this from the input field on line 65 of woocommerce/includes/gateways/class-wc-payment-gateway-cc.php it worked for people.  Is there any other possible work around?

**Comment by mikejolley** [comment]
The slash is added automatically by the script we use for the cc form. This is a library from Stripe and our field matches those.

Maybe your checkout is missing the script which formats the codes? Of course, it's impossible for me to say since you ignored the information we request on the new issue for :)

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/master/assets/js/jquery-payment/jquery.payment.js#L327

**Comment by contemplate** [comment]
Ok it looks like this issue is related to only one of my customer sites.  Although there isn't any js errors and the payments.min.js is loaded.  

Although others have reported something similar here: 
https://wordpress.org/support/topic/checkout-expiry-date-requirement/

One thing I notice is the Genesis Theme does not declare WooCommerce support.  

## Prerequisites



- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X ] The issue still exists against the latest `master` branch of WooCommerce
- [ X ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Visit https://room.handsonaswegrow.com/
2. add a product to the cart and go to checkout
3. try entering an expiration date without the slash.  

## Expected behavior and actual behavior

When I follow those steps, I see...
No slash is added automatically

I was expecting...
A slash to be added after the first two digits

## Environment

<details>
Home URL: 		https://room.handsonaswegrow.com
Site URL: 		https://room.handsonaswegrow.com
WC version: 		3.1.0
Log directory writable: 	/home/www/whphx8/room.handsonaswegrow.com/htdocs/wp-content/uploads/wc-logs/
WP version: 		4.8
WP multisite: 		–
WP memory limit: 		256 MB
WP debug mode: 		–
WP cron: 		yes
Language: 		en_US

Server info: 		Apache
PHP version: 		7.0.19
PHP post max size: 		54 MB
PHP time limit: 		300
PHP max input vars: 		4000
cURL version: 		7.54.0, OpenSSL/1.0.2l
SUHOSIN installed: 		–
Max upload size: 		52 MB
Default timezone is UTC:  ! Default timezone is America/Chicago - it should be UTC	
fsockopen/cURL: 		yes
SoapClient: 		yes 
DOMDocument: 		yes
GZip: 		yes
Multibyte string: 	yes	
Remote post: 		yes
Remote get: 		yes
</details>

## Isolating the problem

- [ X  ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
You're missing:

```
<script type='text/javascript' src='//local.wordpress.dev/wp-content/plugins/woocommerce/assets/js/frontend/credit-card-form.js?ver=3.2.0'></script>
```

I just installed our stripe plugin to confirm this is enqueued and working. It's missing on your store. Not sure what Stripe extension you're using or if you've made customisations, but that should steer you in the correct direction.

**Comment by claudiosanches** [comment]
All fields from our credit cart form is based on Stripe Checkout form, using the same input types too.

**Comment by parcelpet-simon** [comment]
Had the same problem on all platforms, so a little function to make thing happy, happy as called for. 

This is the entire "$default_fields" section in woocommerce/includes/gateways/class-wc-payment-gateway-cc.php

`		$default_fields = array(
			'card-number-field' => '<p class="form-row form-row-wide">
				<label for="' . esc_attr( $this->id ) . '-card-number">' . esc_html__( 'Card number', 'woocommerce' ) . ' <span class="required">*</span></label>
				<input id="' . esc_attr( $this->id ) . '-card-number" class="input-text wc-credit-card-form-card-number" inputmode="numeric" autocomplete="cc-number" autocorrect="no" autocapitalize="no" spellcheck="no" type="tel" placeholder="&bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull;" ' . $this->field_name( 'card-number' ) . ' />
			</p>',
			'card-expiry-field' => '<p class="form-row form-row-first">
				<label for="' . esc_attr( $this->id ) . '-card-expiry">' . esc_html__( 'Expiry (MM/YY)', 'woocommerce' ) . ' <span class="required">*</span></label>
				<input maxlength="5" onkeydown="checkExpiry()" id="' . esc_attr( $this->id ) . '-card-expiry" class="input-text wc-credit-card-form-card-expiry" inputmode="numeric" autocomplete="cc-exp" autocorrect="no" autocapitalize="no" spellcheck="no" type="tel" placeholder="' . esc_attr__( 'MM / YY', 'woocommerce' ) . '" ' . $this->field_name( 'card-expiry' ) . ' />
			</p>
			<script>
			function checkExpiry(){
				var thisKey = event.which || event.keyCode;
					if(document.getElementById("' . esc_attr( $this->id ) . '-card-expiry").value.length == 2 && thisKey != 8 && thisKey != 46) {
						console.log(thisKey + " - doing stuff");
						document.getElementById("' . esc_attr( $this->id ) . '-card-expiry").value = document.getElementById("' . esc_attr( $this->id ) . '-card-expiry").value + "/";
					}
				}
			</script>
			',
		);`

**Comment by JavierPC2012** [comment]
Hi i have the same issue, but in my case credit card number and expiry date fields no have style format (no slash automatic), you have an idea of what is the root cause of the issue?
