### ISSUE TITLE
Coupon codes can be used multiple times by adding spaces

### ISSUE THREAD

**Issue by lawkwok** [woocommerce/woocommerce#15909]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a coupon code.
2. Use the coupon code on the cart or checkout page.
3. Enter the same coupon code, but insert a space anywhere within the string.

## Expected behavior and actual behavior

You expect the coupon code to be able to be used once, but you can use it again by adding a space between any two characters. You can repeat this as many times as the code is long. For example, a coupon code "SALE", can be used four times:

1. SALE
2. S ALE
3. SA LE
4. SAL E

## Environment

<details>
WooCommerce 3.1.0
I can successfully reproduce this on other WooCommerce sites.
</details>

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
Can't replicate with the master branch: http://cld.wthms.co/ZSygWO

**Comment by mikejolley** [comment]
3.1 branch is also fine. Must be some custom logic on the sites.

https://dl.dropboxusercontent.com/s/h7k9x00p4pghaug/2017-07-03%20at%2010.57.png
