### ISSUE TITLE
Wiki Typo

### ISSUE THREAD

**Issue by cdCorey** [woocommerce/woocommerce#15901]
On https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox)-in-3.0.0 the name of the PhotoSwipe library has been mistyped.

Sorry, I would've fixed this myself, but couldn't find a link to edit the wiki.

**Comment by WPprodigy** [comment]
Thanks for the report. Fixed :)
