### ISSUE TITLE
Product Is Not Importing with the New Built In Importer/Exporter for Woocommerce

### ISSUE THREAD

**Issue by publifiedlabs** [woocommerce/woocommerce#15917]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Exported products from a different Woocommerce store for the CSV file template
2. Changed all fields accordingly with the exported template to fit the new store
3. When importing the finished file everything loads properly and says all products were successfully uploaded, however no products show in my "Products Dashboard" or anywhere else in the store. (It did create new categories from the importer, so it is partially working)

## Expected behavior and actual behavior

When I follow those steps, I see...
False success message. Says item has successfully imported but does not actually import the items

I was expecting...
For the items to import into my Products Dashboard

## Environment
Wordpress Version 4.8 (latest version)
Woocommerce Version 3.1.0 (latest version)
<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: http://publifiedlabs.com/npiproducts
Site URL: http://publifiedlabs.com/npiproducts
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp8w_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Loginizer: by Raj Kothari – 1.3.5
WooCommerce: by Automattic – 3.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #298 - /shop/
Cart: #299 - /cart/
Checkout: #300 - /checkout/
My account: #301 - /my-account/

### Theme ###

Name: Divi-child
Version: 1.0.0
Author URL: http://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.55
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
We'd need the CSV to test this.

**Comment by publifiedlabs** [comment]
Hello, Thank you for the quick response. You may download the CSV file here http://publifiedlabs.com/npiproducts/wp-content/uploads/2017/07/woocommerce-csv-import-file-npi-products.csv

**Comment by publifiedlabs** [comment]
I have also attached screen shots of each step I took and the outcome. Hope this helps. Let me know if you need anything else. Thank you.

![import-issue-1](https://user-images.githubusercontent.com/14099990/27766022-8ea0c5e2-5e77-11e7-9c24-b8dd4fa9e0a8.jpg)
![import-issue-2](https://user-images.githubusercontent.com/14099990/27766024-8ea21410-5e77-11e7-9d6b-6047ad2a670f.jpg)
![import-issue-3](https://user-images.githubusercontent.com/14099990/27766023-8ea0e3b0-5e77-11e7-8e54-40e0f3a7c25b.jpg)

**Comment by mikejolley** [comment]
The CSV contains invalid, non-utf8 characters in the description. Thats why this is failing.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15934

**Comment by rosaleebeauty** [comment]
I am having this same problem but after converting to UTF-8, the problem still occurs. The importer says that 80 products were imported but when I check products there are no new published products.

**Comment by scilang** [comment]
is there anyone who can help me about woocommerce product import problem ?
![ekran alintisi](https://user-images.githubusercontent.com/35400199/42307205-5eb5317a-803a-11e8-8284-3000e6e4eaa9.PNG)


A valid address was not provided.

I really dont know how can I fix this..

**Comment by peterfabian** [comment]
Hi, 

I would suggest to first try to contact support via https://woocommerce.com/contact-us/

If you believe this is a bug and you have a valid file, please create a New issue, attach relevant part of the csv file so that we can reproduce the problem.

Thx.
