### ISSUE TITLE
Cannot Checkout: SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by iGlitch** [woocommerce/woocommerce#15914]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add any product to cart
2. Proceed to checkout page
3. Click Pay

## Expected behavior and actual behavior

When I follow those steps, I see in developer tools console... Unable to fix malformed JSON    checkout.min.js?ver=3.1.0:1

I was expecting... normal checkout behavior.

## Environment

Tried disabling all plugins (except WC), tried three different themes (including Wordpress' Twenty Seventeen), Turning cloudflare on/off...

<details>

```
### WordPress Environment ###

Home URL: https://chevalsaddlery.com
Site URL: https://chevalsaddlery.com
WC Version: 3.1.0
Log Directory Writable: 
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 3 GB
WP Debug Mode: –
WP Cron: 
Language: zh_CN

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.20
PHP Post Max Size: 600 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 300 MB
Default Timezone is UTC: 
fsockopen/cURL: 
SoapClient: 
DOMDocument: 
GZip: 
Multibyte String: 
Remote Post: 
Remote Get: 

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: 
woocommerce_api_keys: 
woocommerce_attribute_taxonomies: 
woocommerce_downloadable_product_permissions: 
woocommerce_order_items: 
woocommerce_order_itemmeta: 
woocommerce_tax_rates: 
woocommerce_tax_rate_locations: 
woocommerce_shipping_zones: 
woocommerce_shipping_zone_locations: 
woocommerce_shipping_zone_methods: 
woocommerce_payment_tokens: 
woocommerce_payment_tokenmeta: 
MaxMind GeoIP Database: 

### Security ###

Secure connection (HTTPS): 
Hide errors from visitors: 

### Active Plugins (17) ###

Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.12
GetBowtied Tools: by GetBowtied – 1.3.2
GTranslate: by Edvard Ananyan – 2.8.25
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Newsletter - Extended Composer Blocks: by The Newsletter Team – 1.0.0
Newsletter: by Stefano Lissa & The Newsletter Team – 4.9.9
PayPal Currency Converter BASIC for WooCommerce: by Intelligent-IT.asia – 1.7
Postman SMTP: by Jason Hendriks – 1.7.2
Remove Yoast SEO Comments: by Mitch – 3.0
The7 Slider Revolution: by ThemePunch – 5.4.5
WeiXin Payments for WooCommerce: by 迅虎网络 – 1.8.2
Booster for WooCommerce: by Algoritmika Ltd – 2.8.2
WooCommerce: by Automattic – 3.1.0
WP Baidu Map: by suifengtec – 1.1
YITH Product Size Charts for WooCommerce Premium: by YITHEMES – 1.1.0
YITH WooCommerce One-Click Checkout Premium: by YITHEMES – 1.1.0
YITH WooCommerce Wishlist Premium: by YITHEMES – 2.1.2

### Settings ###

API Enabled: 
Force SSL: 
Currency: CNY (¥)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #63 - /account/

### Theme ###

Name: Cheval
Version: 5.3.1
Author URL: http://glitchery.jp
Child Theme:  – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: 

### Templates ###

Overrides: glitch/woocommerce/cart/cart.php
glitch/woocommerce/cart/cross-sells.php
glitch/woocommerce/checkout/form-billing.php
glitch/woocommerce/checkout/form-checkout.php
glitch/woocommerce/checkout/form-coupon.php
glitch/woocommerce/checkout/form-login.php
glitch/woocommerce/checkout/form-shipping.php
glitch/woocommerce/checkout/review-order.php
glitch/woocommerce/checkout/thankyou.php
glitch/woocommerce/content-product.php
glitch/woocommerce/content-product_cat.php
glitch/woocommerce/global/breadcrumb.php
glitch/woocommerce/global/form-login.php
glitch/woocommerce/global/quantity-input.php
glitch/woocommerce/loop/loop-end.php
glitch/woocommerce/loop/loop-start.php
glitch/woocommerce/loop/orderby.php
glitch/woocommerce/loop/pagination.php
glitch/woocommerce/myaccount/form-login.php
glitch/woocommerce/notices/error.php
glitch/woocommerce/notices/notice.php
glitch/woocommerce/notices/success.php
glitch/woocommerce/order/order-details-customer.php
glitch/woocommerce/order/order-details.php
glitch/woocommerce/single-product/meta.php
glitch/woocommerce/single-product/price.php
glitch/woocommerce/single-product/related.php
glitch/woocommerce/single-product/up-sells.php
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by bporcelli** [comment]
I'm able to reproduce this with PHP 7.0.2, WP 4.8, WC 3.1.0, and Storefront 2.2.4. In my case, the root cause seems to be memory exhaustion. Reverting a268f21900b17d1b73fc8e911ef78620bc9d8558 fixes the problem.

**Comment by apsrivast** [comment]
Getting the same error. Reverting [a268f21](https://github.com/woocommerce/woocommerce/commit/a268f21900b17d1b73fc8e911ef78620bc9d8558)  

Didnt help. Please advice. We are live and its critical issue for us.

**Comment by mikejolley** [comment]
This should not be a page: https://chevalsaddlery.com/checkout/?wc-ajax=checkout

This should be a JSON response. Thats not working here.

Ensure it's not cloudflare or caching, and try going to settings > permalinks and saving settings.

**Comment by apsrivast** [comment]
@mikejolley 
I really admire on how proactive you are. Unfortunately, all the pointers you have given do not point a newb to the right file or change he has to make to fix this issue. 
While I really appreciate you getting involved into most minor of the issues, it would greatly help if you can elaborate a bit more on the resolution of this issue.

**Comment by mikejolley** [comment]
@apsrivast go to the URL I pasted above (change domain to yours). If it shows text, it's working. If it shows the checkout page, it's broken.

**Comment by apsrivast** [comment]
@mikejolley , thank you so much. IT shows this - 

{"result":"failure","messages":"<ul class=\"woocommerce-error\">\n\t\t\t<li>We were unable to process your order, please try again.<\/li>\n\t<\/ul>\n","refresh":true,"reload":false}

But still, when we try to make a payment, it given Invalid token error. Have tried disabling all plugins and everything as you suggested.

**Comment by mikejolley** [comment]
Right @apsrivast so with yours you have a completely separate plugin, and one most likely caused by the theme or a plugin you have installed. Do this:

https://mikejolley.com/2015/11/12/debugging-unexpected-token-in-woocommerce-2-4/

This will give you the error message. You provided no URL so I cannot look for you.

**Comment by mikejolley** [comment]
@iGlitch did you find the problem?

**Comment by apsrivast** [comment]
@mikejolley , I am a newb dev. Not able to understand where to add this code. URL is - 

https://www.mariericci.com/

If I use a wrong card, I get invalid card error message, but on a good card, same error

**Comment by mikejolley** [comment]
@apsrivast I can't really test a real payment on your store. Read my post. There is no coding required! Just look at the console OR look at your error logs on the server.

**Comment by mikejolley** [comment]
O and if you're using DIVI theme, they know about it.

**Comment by apsrivast** [comment]
@mikejolley , thank you. 
Response contains -

Raw data 

which is empty. 

If you can kindly take a look here - 

https://www.mariericci.com/dev/

And use test card - 

 4242424242424242
06/2018  or 12/2018

**Comment by mikejolley** [comment]
Since it's error 500 either enable WP_DEBUG mode or look at server error log.

**Comment by iGlitch** [comment]
Yeah, mine was the permalink issue as you initially stated it seems, thanks!

**Comment by apsrivast** [comment]
@mikejolley , 
The error after Wp-debug true is - 

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

All other plugins are disabled except woocommerce. Please help

**Comment by mikejolley** [comment]
@apsrivast wrong, error is:

```
<b>Catchable fatal error</b>:  Object of class Requests_Utility_CaseInsensitiveDictionary could not be converted to string in <b>/home/mariericci/public_html/dev/wp-content/plugins/woocommerce-gateway-authorize-net-aim/lib/skyverge/woocommerce/class-sv-wc-plugin.php</b> on line <b>448</b><br />
```

So update that to 3.11.3 or log an issue on the helpdesk.

Thanks

**Comment by iiamirti** [comment]
Dear Team,

I am also facing the same issue. I have updated the plugins too but still this is coming. Can annyone please help me out?

http://thehumanshield.org/our-packages

STEPS TO REPRODUCE:
1) Place Order from the shared URL
2) FILL the Form and Hit
3) Pay button you will receive the error:
    "SyntaxError: Unexpected token < in JSON at position 0"

SCREENSHOT Attached.

![asv](https://user-images.githubusercontent.com/19576745/32412511-a1e8eff0-c21b-11e7-8624-9b27d8f2812b.jpg)

**Comment by mitdralla** [comment]
I am experiencing this issue also. With Authorize.net gateway.

**Comment by dambrogia** [comment]
FWIW - be sure to check your servers apache / nginx log. I had a PHP error in an email template that was causing this error. 

Common locations for apache are:

    Centos / RHEL: /var/log/httpd/error_log
    Ubuntu / Debian: /var/log/apache/error_log

Also, in response to @mikejolley 's comment about using `example.com/checkout/?wc-ajax=checkout` 

I am receiving an error on that specific url but I can successfully checkout without the JSON error after fixing my PHP error. (I have 1 item in my cart using cash / check payment for testing) So it might be useful to double check even if you are still seeing that error pop up on your screen at that `example.com/checkout/?wc-ajax=checkout` url

![image](https://user-images.githubusercontent.com/6516452/34226439-93cab468-e57e-11e7-8bd3-c2c716d42b10.png)

@mikejolley - thanks for your attention to the situation, much appreciated!

**Comment by wish2** [comment]
![image](https://user-images.githubusercontent.com/37868371/38024851-d4fc93b2-32a3-11e8-98e7-8b411a92c97a.png)

plz help me to solve it i m gettiig interal server error when click proceed button of checkout page (wordpress) error say "  SyntaxError: Unexpected token < in JSON at position 0  "

**Comment by wish2** [comment]
i m using shopstudio theme

**Comment by webtindo** [comment]
IWe are theme developers and we had the same problem with our theme.
The error was a function which uses ob_start callback function to gzip output buffer.
The function was to create output all files as gzip format.

The function is also used via extension_loaded ('zlib').
Various caching or compression plugins could also generate this error when in use.
Solution: Check all plugins and your theme for functions which might use GZip compression (via extension_loaded zlib and ob_gzhandler).

**Comment by blue928** [comment]
@mikejolley 

Thank you for this immensely helpful article.  
https://mikejolley.com/2015/11/12/debugging-unexpected-token-in-woocommerce-2-4/

After reading this it was a breeze to pinpoint our errors and fix them. It make me a better developer!

Clients are reporting getting the same error on checkout, even though I cannot reproduce them locally.

Is there a way the hard log errors like this, maybe server side, so I can review them? Despite WP_DEBUG being set to true, nothing in them indicates that an error takes place. Same goes for Apache logs, unless I just don't know what I'm looking for?

Thanks again for taking the time to write that!
