### ISSUE TITLE
woocommerce 3.1: please choose product options

### ISSUE THREAD

**Issue by poyagh** [woocommerce/woocommerce#15910]
Hi. This problem has been occurred for me!
I checked ny JQuery version in source. There is this code:
`<script type='text/javascript' src='https://xx/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>`
And I checked the JS conosle. It just shows 2 errors:

`Mixed Content: The page at 'https://xx/shop/productpage/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Oswald'. This request has been blocked; the content must be served over HTTPS.`
```
addthis_widget.js:2 GET https://graph.facebook.com/?id=https%3A%2F%2Fwww.esrb.org%2Fratings%2Fsearc…DB%258C%2520The%2520Sims%25204%23Content_title&callback=_ate.cbs.rcb_k2d20 net::ERR_CONNECTION_REFUSED
e.exports @ addthis_widget.js:2
ajs @ layers.4acb6c5….js:1
e.default @ layers.4acb6c5….js:1
(anonymous) @ layers.4acb6c5….js:1
e.default @ layers.4acb6c5….js:1
getShareCounts @ layers.4acb6c5….js:1
finalize @ layers.4acb6c5….js:1
render_logic @ layers.4acb6c5….js:1
render @ layers.4acb6c5….js:1
create @ layers.4acb6c5….js:1
r @ layers.4acb6c5….js:1
createWidget @ layers.4acb6c5….js:1
(anonymous) @ layers.4acb6c5….js:1
p @ addthis_widget.js:2
(anonymous) @ addthis_widget.js:2
```
I updated all plugins and my wordpress. But not solved!
Disabled all other plugins. But not solved!
Enabled default theme. But not solved!
Changed php version from 7 to 5.6 . But not solved!
Repaired and optimized all tables. But not solved!

**Comment by mikejolley** [comment]
If you don't provide the status report as required, nor a link to the site, this issue is going to be closed.

**Comment by poyagh** [comment]
https://ipalex.biz/shop/original-gta-v-for-pc/

**Comment by mikejolley** [comment]
add to cart worked for me. But the errors and mixed contents are not from WooCommerce. You have scripts, either added yourself or by a plugin, being defined has http:// rather than https:// and they need to be changed.

https://dl.dropboxusercontent.com/s/fkjcnig5g8afpr0/2017-07-02%20at%2011.19.png

**Comment by poyagh** [comment]
Yes, this is a strange problem for me.
I changed my first php version from 7 to 5.6 and second php from 5.6 to 7 and all scenarios! After I created this topic and after about 5-6 hours I changed first php to 7 and second to 5.6 .
My problem resolved strangely!
