### ISSUE TITLE
Add to Cart + Order Review Not Loading - Spinning Icons? 

### ISSUE THREAD

**Issue by AZJR** [woocommerce/woocommerce#15913]
As of today the Add to Cart buttons do nothing on my website, if I click the buttom I just get the loading animation with the spinning circle, and nothing happens, but if I refresh the page that item is added to my cart. 

When I go to my cart and go to checkout, the order-preview section will not load and has a spinning loading icon as well. 

I reviewed the official guide from WooCommerce here: https://docs.woocommerce.com/document/endless-loadingspinner-on-the-checkout-page/

But that did not solve my problem. I tried disabling all my plugins, still no luck.

I also noticed I cannot search for plug ins, it's just a blank page now with the loading icon in the middle. If I try to update a plugin I get weird strings of text and then an error code. 

Example:

 "Update Failed: 
 Stereotypo
 4 immagini 1 parola
 word guru
 Wort Guru Level 133
 Wort Guru Level 381
 Word guru 856
 Wordscapes Beach
 
 {"success":true,"data":{"update":"plugin","slug":"easy-wp-smtp","oldVersion":"Version 1.2.4","newVersion":"Version 1.2.5","plugin":"easy-wp-smtp\/easy-wp-smtp.php","pluginName":"Easy WP SMTP"}}"

I have no idea where the Stereotypo and weird words are coming from?

From what I can research I think it's an AJAX issue? If I try to export my site via XML using the exporter I get the weird strings of text and errors. 

Any ideas? Any help is greatly appreciated!!

**Comment by AZJR** [comment]
[error_log.txt](https://github.com/woocommerce/woocommerce/files/1117256/error_log.txt)

**Comment by AZJR** [comment]
[debug.txt](https://github.com/woocommerce/woocommerce/files/1117260/debug.txt)

**Comment by mikejolley** [comment]
Your debug log has many deprecated calls so a plugin you're running looks out of date.

```
"Update Failed:
Stereotypo
4 immagini 1 parola
word guru
Wort Guru Level 133
Wort Guru Level 381
Word guru 856
Wordscapes Beach

{"success":true,"data":{"update":"plugin","slug":"easy-wp-smtp","oldVersion":"Version 1.2.4","newVersion":"Version 1.2.5","plugin":"easy-wp-smtp/easy-wp-smtp.php","pluginName":"Easy WP SMTP"}}"
```

This causes your error. You'll need to find out what is trying to do updates because thats not core.

**Comment by AZJR** [comment]
That happens to any plugin I try to update not just this one. Any advice?

**Comment by mikejolley** [comment]
I don't know which plugin would output it no.
