### ISSUE TITLE
Referer login is incorrect in class-wc-form-handler.php ll-921-926

### ISSUE THREAD

**Issue by Jon007** [woocommerce/woocommerce#15911]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional) 

## Steps to reproduce the issue

1.  Log out of the system
2.  Attempt to directly access an order page eg http://mysite/my-account/view-order/12345/
3.  Login form is presented, note that login form contains hidden input _wp_http_referer 
4.  do login
5.  user is redirected to My Account page

## Expected behavior and actual behavior

Step 5, expected to redirect to order page

The code issue is as follows:  the code for wp_get_referer() returns false if we are already on the right page... however the WooCommerce code treats false as a failure and proceeds to redirect to my account:
```
					if ( ! empty( $_POST['redirect'] ) ) {
						$redirect = $_POST['redirect'];
					} elseif ( wp_get_referer() ) {
						$redirect = wp_get_referer();
					} else {
						$redirect = wc_get_page_permalink( 'myaccount' );
					}
 
```

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/15939
