### ISSUE TITLE
Incorrect translation of cart for English (Australia)

### ISSUE THREAD

**Issue by lutrov** [woocommerce/woocommerce#15925]
If you install Wordpress for English (Australia), Woocommerce uses the word "cart" inconsistently. Sometimes it's "cart" and sometimes it's "basket". We use the word "cart" in Australia and I suspect the `woocommerce-en_AU.po` file was copied over from `woocommerce-en_GB.po` but the translations were incomplete before release. :-)

**Comment by mikejolley** [comment]
Hi there,

We added this: https://wordpress.org/support/topic/updating-translations-after-updates/

This needs to be community translated and approved :)
