### ISSUE TITLE
Comma in Product Attribute Term name problems for Export/Import

### ISSUE THREAD

**Issue by Jon007** [woocommerce/woocommerce#15926]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Export a Variable product which is linked to some Product Attribute terms which contain a comma
2. Import the same variable product from the exported file

## Expected behaviour and actual behavior
Expected: import ok
Actual:  variation linked to the term name which contained a comma is now delinked

## This is the explanation:
In the test case, the variation attribute has 2 terms, let's suppose these are:
- "a, b"
- "c"

When exported, the value produced in eg the "Attribute 1 value(s)" field is:
"a, b, c"

There is no way that any importer could know that "a, b, c" is a representation of two values "a, b" and "c".

Possible solutions:
- disallow comma when saving term name (but what about data already saved)
- character escaping rule for comma within multi-value field data 

[this is a simplified case of a real-world example with longer text. Here is an example in English and Spanish with 2 commas in the term: 
- 1,000 piece pack, shipping weight 2.5kg
- paquete 1.000 piezas, peso 2,5kg
Here the user has added the quantity and weight so it is very clear to the customer when opening the attribute selector which sizes of product are available.
The comma between two words is easy to substitute, but the comma in numeric text is common usage in different languages.]

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Yeah, we accepted this would be the case in this release. We can work on escaping for 3.2.

**Comment by mikejolley** [comment]
Added this for 3.2. https://github.com/woocommerce/woocommerce/pull/15943

**Comment by Jon007** [comment]
thanks yes I saw the commit.

If there's stuff "accepted this would be the case in this release"  it would be great to have some clear warnings/limitations.
While the attribute issue was easy enough to spot at the product level, issues caused by a comma in a category name a couple of levels down the category hierarchy were less obvious..

**Comment by SupermanRob** [comment]
I am seeing this issue still in version 3.3.3.

Variations are imported, but not correctly 'linked' to the parent. All imported fine except the ones with commas.

Is there any known work-around currently?

![screen shot 2018-03-21 at 12 54 42 am](https://user-images.githubusercontent.com/29809914/37673320-7bdb26ec-2ca2-11e8-9481-51fab201f2e7.png)
![screen shot 2018-03-21 at 12 54 33 am](https://user-images.githubusercontent.com/29809914/37673329-80a53230-2ca2-11e8-8029-cd88d2e99b13.png)

**Comment by mikejolley** [comment]
Commas can be escaped with backslash I believe.

**Comment by Jon007** [comment]
while there isn't a normative standard for csvs, I wasn't aware of a version which escapes commas with backslash.
It's more normal for the text fields to be "delimited with quotes" so that further text escaping within the field is unnecessary (apart from the quote character).   
This is what you get when you save a csv out of excel which is itself a de facto standard - you don't expect the csv to 'break' after editing it in Excel and you don't expect the average user to then go through their file to apply additional escaping.   Note the excel csv text fields can also include line breaks without escaping.

Such convention is also covered in the nearest thing there is to a standards document:
https://tools.ietf.org/html/rfc4180

The escaping rule for a double-quote in the quoted situation is to double it as:
       "aaa","b""bb","ccc"

Alternatively if escaping is used, comma could be escaped as indicated:
      COMMA = %x2C

**Comment by sohaibwoof** [comment]
This comma thing is still causing trouble. 
One of our custom attributes' value contains , but WooCommerce treats the comma as seperate value which is really annoying.

Tried to used comma with backslash but that did not work too. 

Just attached the CSV and **Attribute 2 value(s)** is where the issue happens.
[Untitled spreadsheet - sohaib-test-2.csv](https://github.com/user-attachments/files/16669253/Untitled.spreadsheet.-.sohaib-test-2.csv)
