### ISSUE TITLE
API changes on WooCommerce 3.1

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#15922]
I was noticed that none of my 3rd parties can import products to our store via API after we upgraded WooCommerce 3.0.9 to 3.1.0. 

As we checked it before, there is no changes on API. I was wondering why it stopped working.

``
### WordPress Environment ###

Home URL: https://www.domain.com
Site URL: https://www.domain.com
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.12.0
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.38.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: ag_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

AliDropship Woo Plugin: by Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin – 0.6
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.45
Contact Form 7: by Takayuki Miyoshi – 4.8
Google Authenticator: by Henrik Schack – 0.48
GTranslate: by Edvard Ananyan – 2.8.25
MailChimp for WooCommerce: by MailChimp – 2.0.0
McAfee SECURE: by McAfeeSECURE – 1.7.5
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

PixelYourSite PRO: by PixelYourSite – 6.2.0
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.2.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SEO Optimized Images Business With WooCommerce: by priyanshu.mittal – 1.5.2
WooCommerce Advanced Shipping - Advanced Pricing: by Jeroen Sormani – 2.1.1
WooCommerce Advanced Shipping: by Jeroen Sormani – 1.0.13
WooSwatches - Woocommerce Color or Image Variation Swatches: by woomatrix – 2.3.9
WooCommerce Currency Converter: by WooCommerce – 1.6.5
WooCommerce Stripe Gateway: by WooCommerce – 3.2.1
WooCommerce Notification: by Andy Ha (villatheme.com) – 1.2.1
WooCommerce: by Automattic – 3.1.0
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 4.7
WP Rocket: by WP Media – 2.10.4
Yoast SEO: WooCommerce: by Team Yoast – 4.6
YITH Product Size Charts for WooCommerce Premium: by YITHEMES – 1.1.0
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.6
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

``

**Comment by mikejolley** [comment]
API does not receive changes aside from fixes without a version bump. https://github.com/woocommerce/woocommerce/tree/master/includes/api

Without details of the error, or proper debugging first, it's not possible to say.

**Comment by kevin25** [comment]
@mikejolley I'll try to provide more details. I have 3 Woo Shop. 2 of them was upgraded to 3.1.0 and have the same issue. The 3.0.9 version doesn't have issue. I tested it some hours ago. I imported products without issue. So I wonder what was changed on API.

**Comment by kevin25** [comment]
So here is the issue:

https://github.com/woocommerce/woocommerce/commit/f62337890e72f29e22f8cf5fb9e69a3751802f1c

You guys remove this:

`$setting['value']    = empty( $admin_setting_value ) ? $default : $admin_setting_value;`

And add this like default:

`$setting['value']    = $admin_setting_value;`

So my 3rd apps were die at the first time connected to your store via API.

I changed it back to:
`$setting['value']    = empty( $admin_setting_value ) ? $default : $admin_setting_value;`

Now I can import without issue.

**Comment by mikejolley** [comment]
@kevin25 This change was a fix and cannot be reverted. If the value is SUPPOSED to be empty, this would revert it to 'default'.

Why can't the app handle this? I don't understand.

**Comment by kevin25** [comment]
The 3rd app is still no chance. When i rolled that change back, everything is working fine. So I don't really know what to say to those suppliers.

**Comment by mikejolley** [comment]
@kevin25 Maybe you can explain how the apps works/what endpoints and calls are being made?
