### ISSUE TITLE
CSV Importer - extendability improvement when exporting

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#15923]
Currently, you need to create a new function and hook for every column you wish to export: https://github.com/woocommerce/woocommerce/blob/c38d02b62bcdadeb72ffc571a79f0249a29b3b04/includes/export/class-wc-product-csv-exporter.php#L154-L155.

This seems a bit overkill for plugins that need to export a large number of simple meta fields. Instead, what are your thoughts on a filter that simply allows a plugin to hook in at the end and conditionally change the value (would need to pass the $column_id)? Then the plugin's export function would look similar to the import function using `woocommerce_product_import_pre_insert_product_object`.

Also, that `woocommerce_product_export_{$this->export_type}_column_{$column_id}` filter's name is kinda meh, as `product` ends up being mentioned twice. I don't think the second variable is really needed, since it's an unnecessary abstraction as `class-wc-product-csv-exporter.php` will only ever be about product exporting.

**Comment by WPprodigy** [comment]
On second thought, just passing `$column_id` into the filter could help. You would still need a bunch of filters, but could create a loop for those I suppose.

**Comment by mikejolley** [comment]
`export_type` could be changed by extensions e.g. a subscription product importer/exporter

**Comment by mikejolley** [comment]
And upon inspection, `woocommerce_product_export_row_data` is available to handle all columns later in the method.

**Comment by WPprodigy** [comment]
Would it be okay to pass `$column_id` into the filter?
