### ISSUE TITLE
Mini cart widget displaying wrong subtotal when adding bundled products to cart

### ISSUE THREAD

**Issue by MariemeMbengue** [woocommerce/woocommerce#15929]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a product bundle to cart by clicking on Add to Cart button
2.
3.

## Expected behavior and actual behavior

When I follow those steps, the subtotal showing in the Woocommerce mini cart widget is wrong. It is showing a subtotal based on the prices of each simple products included in the bundle.
The subtotal should be the price of the bundle as defined in the bundle product. 
The subtotal is displaying correctly on the actual cart page, though. The issue is with the mini cart widget only.
I am using the YITH WooCommerce Product Bundles to create my product bundles.

Thank you

## Environment

<details>
`
### WordPress Environment ###

Home URL: https://oneofakind.world
Site URL: https://oneofakind.world
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_CA

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.20
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wpvd_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

WPBruiser: by Mihai Chelaru – 3.1.7
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.10
Hello Dolly: by Matt Mullenweg – 1.6
Jetpack by WordPress.com: by Automattic – 5.0
Orange Themes Custom Widgets: by Orange Themes – 1.0.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SG Optimizer: by SiteGround – 3.3.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 1.13.4

Woo Checkout Field Editor Pro: by ThemeHiGH – 1.1.9
Woo Stickers by Webline: by Weblineindia – 1.1.0
WooCommerce Bundle Style Coupons: by Coen Jacobs – 0.1.1
WooCommerce Cart Stock Reducer: by James Golovich – 2.10
WooCommerce Email Validation: by Hugh Lashbrooke – 2.1
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.1
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.6.0

WooCommerce Services: by Automattic – 1.6.0
WooCommerce: by Automattic – 3.1.0
Yoast SEO: by Team Yoast – 4.9
WP Instagram Widget: by Scott Evans – 1.9.8
YITH WooCommerce Product Bundles: by YITHEMES – 1.1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #87 - /shop/
Cart: #89 - /cart/
Checkout: #91 - /checkout/
My account: #93 - /my-account/

### Theme ###

Name: Barletta Child
Version: 1.1.3
Author URL: http://moozthemes.com
Child Theme: ✔
Parent Theme Name: Barletta
Parent Theme Version: 1.1.3
Parent Theme Author URL: http://moozthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: barletta-child/woocommerce/cart/cart.php
barletta-child/woocommerce/checkout/form-billing.php
barletta-child/woocommerce/checkout/form-shipping.php
barletta-child/woocommerce/checkout/payment.php
barletta-child/woocommerce/single-product/tabs/description.php

`
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Since core does not control bundled products, this is something you'll need to get in contact with "YITH WooCommerce Product Bundles" about.
