### ISSUE TITLE
API: Update product type from simple to variable

### ISSUE THREAD

**Issue by alanbukstein** [woocommerce/woocommerce#15927]
I am trying via Postman (using API V3) sending:
{
  "product": {
	"type": "variable",
	 "attributes": [
            {
                "name": "COLOR",
                "visible": true,
                "variation": true,
                "options": [
                    "RedTest"
                ]
            },
            {
                "name": "SIZE",
                "visible": true,
                "variation": true,
                "options": [
                    "LargeTest"
                ]
            }
        ],
    "variations": [
    {
    	"regular_price":1,
    	"stock_quantity":1,
    	"visible":true,
        "attributes": [
          {
            "name": "COLOR",
            "option": "RedTest"
          },
          {
            "name": "SIZE",
            "option": "LargeTest"
          }
        ]
      }
    ]
  }
}

The product is adding the attribute, but it doesn't change the type either add the variation

**Comment by mikejolley** [comment]
JSON is invalid. Your props are nested.

Should be:

```
{
	"type": "variable",
	"attributes": [
		{
			"name": "COLOR",
			"visible": true,
			"variation": true,
			"options": [
				"RedTest"
			]
		},
		{
			"name": "SIZE",
			"visible": true,
			"variation": true,
			"options": [
				"LargeTest"
			]
		}
	],
	"variations": [
		{
			"regular_price": 1,
			"stock_quantity": 1,
			"visible": true,
			"attributes": [
				{
					"name": "COLOR",
					"option": "RedTest"
				},
				{
					"name": "SIZE",
					"option": "LargeTest"
				}
			]
		}
	]
}
```

**Comment by alanbukstein** [comment]
i tried with:
`{
	"product": {
		"type": "variable",
		"attributes": [{
				"name": "COLOR",
				"visible": true,
				"variation": true,
				"options": [
					"RedTest"
				]
			},
			{
				"name": "SIZE",
				"visible": true,
				"variation": true,
				"options": [
					"LargeTest"
				]
			}
		],
		"variations": [{
			"regular_price": 1,
			"stock_quantity": 1,
			"visible": true,
			"attributes": [{
					"name": "COLOR",
					"option": "RedTest"
				},
				{
					"name": "SIZE",
					"option": "LargeTest"
				}
			]
		}]
	}
}` 
And still with type simple. Happen the same trying to change from variable to simple.

**Comment by mikejolley** [comment]
Because you're still including that "product" and nesting the attributes. Look at the JSON I posted!

**Comment by mikejolley** [comment]
I don't think so..

**Comment by claudiosanches** [comment]
@alanbukstein nice opportunity to update your App, since legacy API v3 what is what you are using will be removed from WooCommerce next year.
