### ISSUE TITLE
new order email is cut off when displayed in Android Gmail app

### ISSUE THREAD

**Issue by mojo2405** [woocommerce/woocommerce#15928]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce
- [ X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create new order
2. Open new order mail in Gmail APP in Android  - latest version 

## Expected behavior and actual behavior

When I follow those steps, I see cut off email . when openenig it in a desktop - it seems ok

I was expecting not a cut off email
See link [https://ibb.co/id9QQF](url)

## Environment

<details>
`
### WordPress Environment ###

Home URL: https://www.shaked-presents.com
Site URL: https://www.shaked-presents.com
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL

### Server Environment ###

Server Info: Apache/2.2.15 (CentOS)
PHP Version: 5.6.29
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.9
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Invoice4u Meshulam Clearing: by Invoice4U – 1.3
Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.12
Contact Form 7: by Takayuki Miyoshi – 4.8
Custom Order Status for WooCommerce: by Algoritmika Ltd – 1.3.1
Dynamic Featured Image: by Ankit Pokhrel – 3.5.2
Envato WordPress Toolkit: by Envato – 1.7.3
Export WooCommerce: by Algoritmika Ltd – 1.0.0
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Loco Translate: by Tim Whitlock – 2.0.14
Porto Content Types: by SW-THEMES – 1.3.1
Porto Shortcodes: by SW-THEMES – 1.6.8
Porto Widgets: by SW-THEMES – 1.3.1
WordPress Post Type Archive Links: by Stephen Harris – 1.3.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
WooCommerce Tree Table Rate Shipping: by tablerateshipping.com – 1.15.3
Woocommerce Order address Print: by Bhavik Patel – 3.1
WooCommerce TM Extra Product Options: by themecomplete – 4.5.3
WooCommerce Upload Files: by Lagudi Domenico – 24.5
WP All Import - WooCommerce Add-On: by Soflyy – 1.3.5
WooCommerce: by Automattic – 3.1.0
Yoast SEO: by Team Yoast – 4.9
WP Accessibility: by Joe Dolson – 1.6.0
WP All Import: by Soflyy – 3.4.4
WP Google Maps: by WP Google Maps – 6.4.05
WP Mail Logging: by Christian Zöller – 1.8.1
WP-ServerInfo: by Lester 'GaMerZ' Chan – 1.64
WP Sitemap Page: by Tony Archambeau – 1.6
WP Super Cache: by Automattic – 1.4.9
WPS Hide Login: by Remy Perona for WPServeur – 1.1.7
MailPoet Newsletters: by MailPoet – 2.7.10
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.4.2
YITH WooCommerce Ajax Search: by YITHEMES – 1.5.3
Advanced Custom Fields: by Elliot Condon – 4.4.11

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: ILS (₪)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2471 - /shop-2/
Cart: #2562 - /cart-2/
Checkout: #3745 - /checkout-2/
My account: #3746 - /my-account-2/

### Theme ###

Name: Porto
Version: 3.6.3
Author URL: http://www.newsmartwave.net/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.1.0
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.1.0
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.1.0
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php version 3.0.0 is out of date. The core version is 3.0.9
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/content-product.php
porto/woocommerce/content-product_cat.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php version 3.0.0 is out of date. The core version is 3.0.9
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/order-details.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/external.php
porto/woocommerce/single-product/add-to-cart/grouped.php
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php version 3.0.0 is out of date. The core version is 3.1.0
porto/woocommerce/single-product/product-image.php version 3.0.2 is out of date. The core version is 3.1.0
porto/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date. The core version is 3.1.0
porto/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.1.0
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php version 3.0.0 is out of date. The core version is 3.1.0
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/share.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

Outdated Templates: ❌Learn how to update

</details>

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
The emails are not responsive. I think this will be part of the https://github.com/woocommerce/woocommerce/issues/10704 redesign.
