### ISSUE TITLE
Get order items problem

### ISSUE THREAD

**Issue by urosmil** [woocommerce/woocommerce#15937]
Hi,

We are working with custom product objects. We have succeeded in adding custom product, making it as order item and getting its info in wp admin panel. Unfortunately we couldn't get it on order details block when order is placed on checkout page. In wp admin panel template, there is filter 
wp-content\plugins\woocommerce\includes\admin\meta-boxes\views\html-order-items.php
$line_items  = $order->get_items( apply_filters( 'woocommerce_admin_order_item_types', 'line_item' ) );

but in order-details.php template located in order directory

wp-content\plugins\woocommerce\templates\order\order-details.php
foreach ( $order->get_items() as $item_id => $item ) {

is called and there is no possibility to use same filter in $order->get_items() part. Is it possible to add filter on this place also?

Thanks in advance,
Uros

**Comment by mikejolley** [comment]
If you feel a filter is needed, submit a PR with justification so we can see what you actually want and why. Give examples.

Thanks
