### ISSUE TITLE
Guest checkout always enabled (cannot disable) on Woocommerce 3.1.0. Worked fine on 2.x

### ISSUE THREAD

**Issue by gmo81** [woocommerce/woocommerce#15938]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. From the wordpress dashboard, go to woocommerce -> Settings
2. Click 'checkout'
3. Find 'Enable guest checkout' - which is ticked (even though previously, this was not ticked
4. Untick 'Enable guest checkout' and save changes
5. Page returns with 'Your settings have been saved.', however 'Enable guest checkout' is still ticked, and enabled when going through checkout

## Expected behavior and actual behavior

When I follow those steps, guest checkout remains enabled no matter what

I was expecting for it to be disabled when I uncheck 'Enable guest checkout' and click save changes

## Environment

<details>
WordPress environment
Home URL: 		http://hidden
Site URL: 		http://hidden
WC version: 		3.1.0
Log directory writable: 		/home/hidden/public_html/wp-content/uploads/wc-logs/
WP version: 		4.8
WP multisite: 		–
WP memory limit: 		512 MB
WP debug mode: 		–
WP cron: 		
Language: 		en_AU
Server environment
Server info: 		Apache
PHP version: 		5.6.30
PHP post max size: 		256 MB
PHP time limit: 		120
PHP max input vars: 		1000
cURL version: 		7.19.7, NSS/3.27.1
SUHOSIN installed: 		–
MySQL version: 		5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements	
Max upload size: 		64 MB
Default timezone is UTC: 		
fsockopen/cURL: 		
SoapClient: 		
DOMDocument: 		
GZip: 		
Multibyte string: 		
Remote post: 		
Remote get: 		
Database
WC database version: 		3.1.0
Database prefix 	  	wp_	
woocommerce_sessions 	  	
woocommerce_api_keys 	  	
woocommerce_attribute_taxonomies 	  	
woocommerce_downloadable_product_permissions 	  	
woocommerce_order_items 	  	
woocommerce_order_itemmeta 	  	
woocommerce_tax_rates 	  	
woocommerce_tax_rate_locations 	  	
woocommerce_shipping_zones 	  	
woocommerce_shipping_zone_locations 	  	
woocommerce_shipping_zone_methods 	  	
woocommerce_payment_tokens 	  	
woocommerce_payment_tokenmeta 	  	
Security
Secure connection (HTTPS): 		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors 		
Active plugins (29)
BackWPup 	  	by Inpsyde GmbH – 3.4.1
CB Change Mail Sender 	  	by Md Abul Bashar – 1.1
Cimy User Extra Fields 	  	by Marco Cimmino – 2.7.2
Contact Form 7 	  	by Takayuki Miyoshi – 4.8
Easy Theme and Plugin Upgrades 	  	by Chris Jean – 2.0.0
Edwiser Bridge Single Sign On 	  	by WisdmLabs – 1.2.1
Edwiser Bridge - WordPress Moodle LMS Integration 	  	by WisdmLabs – 1.2.2
Insert Pages 	  	by Paul Ryan – 3.2.2
Minimum Password Strength 	  	by Will Anderson and Tony Ferrell – 1.2.0
Meta Slider 	  	by Matcha Labs – 3.5.1
MOJO Marketplace 	  	by Mike Hansen – 1.1.4
Password Strength for WooCommerce 	  	by Potent Plugins – 1.0.1
Plugins Garbage Collector 	  	by Vladimir Garagulya – 0.10.3
Selective Synchronization 	  	by WisdmLabs – 1.1.0
ShortCode Redirect 	  	by Cartpauj – 1.0.02
Sign Me Up 	  	by Jaromy Russo – 1.5.1
Smart Manager 	  	by StoreApps – 3.9.23
Stripe WooCommerce Addon 	  	by Syed Nazrul Hassan – 1.0.8
Transients Manager 	  	by Pippin Williamson – 1.7.3
Woo Payment Discounts 	  	by WPCodelibrary – 1.0.2
WooCommerce Dynamic Pricing 	  	by Lucas Stark – 3.0.9
WooCommerce PayPal Express Checkout Gateway 	  	by WooCommerce – 1.4.1
WooCommerce Integration 	  	by WisdmLabs – 1.1.4
WooCommerce MailChimp 	  	by Saint Systems – 2.1.0
WooCommerce PDF Invoices & Packing Slips 	  	by Ewout Fernhout – 1.6.6
WooCommerce Product Bundles 	  	by SomewhereWarm – 5.3.1
WooCommerce Xero Integration 	  	by WooCommerce – 1.7.9
WooCommerce 	  	by Automattic – 3.1.0
WP Time Capsule 	  	by Revmakx – 1.10.1
Settings
API enabled: 		
Force SSL: 		
Currency 		AUD ($)
Currency position 		left
Thousand separator 		,
Decimal separator 		.
Number of decimals 		2
Taxonomies: Product types 		bundle (bundle), external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility 		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#8 - /index.php/shop/
Basket:		#9 - /index.php/cart/
Checkout:		#10 - /index.php/checkout/
My account:		#11 - /index.php/account/
Theme
Name: 		Vogue
Version: 		10.3.7
Author URL: 		https://kairaweb.com/
Child theme: 		– If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce support: 		
Templates
Overrides: 	  	–
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
There is no issue saving this and other options. It sounds like this may be an option one of your extensions wants to force on :) I've seen this before.

Search all plugins and the theme in `wp-content` for the option name `woocommerce_enable_guest_checkout`. That should help you confirm if there is indeed some code setting this.

**Comment by gmo81** [comment]
Mike - you're absolutely right, I apologise for the false alarm. I very much appreciate the help, as with that knowledge in hand I was able to locate the responsible plugin pretty quickly with a:

find . -type f -exec grep -H woocommerce_enable_guest_checkout {} \;

and have now contacted the responsible author :)

Thanks again - that was a great help in locating the problematic plugin!
