### ISSUE TITLE
Woocommerce processing order not send email to costumer

### ISSUE THREAD

**Issue by sanditheresia** [woocommerce/woocommerce#15935]
Hi all i'm tirred for this

when i click this action "processing" email not sending to costumer, but action for complete & cancel everything is fine 
![1](https://user-images.githubusercontent.com/20878118/27790324-2ef0c35a-601a-11e7-91e6-f480abd7b4c6.png)

i try instal this plugin [https://wordpress.org/plugins/wp-mail-logging/](url) to see if email are sending but theres not log for processing order

please help me. thanks

**Comment by mikejolley** [comment]
This is not happening on all stores, so I think it's a conflict..I certainly have no issue on my installs.

Look at your php error logs and WP debug log. Look for fatal errors. Also ensure the order is assigned to a customer, and has valid billing email set.

Also, the current status needs to be failed, on-hold, or pending for this email to send.

Thanks
