### ISSUE TITLE
Product price wrong display

### ISSUE THREAD

**Issue by sferdiand** [woocommerce/woocommerce#15940]
Hy,

We identify a lot of products with the following issue:

1. Client order one product with one price... the are displayed on the page.

2. Refresh page... same product... different price (client and seller)

We encounter this issue with a few products.

You can find the page source code with the different price:

Bad price:
 <nav class="woocommerce-breadcrumb"><a href="http://www.elit-pavaj.ro">Acasă</a>&nbsp;&#47;&nbsp;<a href="http://www.elit-pavaj.ro/categorie/pavaje/">Pavaje</a>&nbsp;&#47;&nbsp;Pavaj Nardo</nav><h1 class="product_title entry-title">**Pavaj Nardo**</h1><p class="price"><span class="woocommerce-Price-amount amount">24&nbsp;<span class="woocommerce-Price-currencySymbol">lei</span></span> &ndash; <span class="woocommerce-Price-amount amount">27&nbsp;<span class="woocommerce-Price-currencySymbol">lei</span></span> <small class="woocommerce-price-suffix">incl. TVA</small></p>

Good price:
 <nav class="woocommerce-breadcrumb"><a href="http://www.elit-pavaj.ro">Acasă</a>&nbsp;&#47;&nbsp;<a href="http://www.elit-pavaj.ro/categorie/pavaje/">Pavaje</a>&nbsp;&#47;&nbsp;Pavaj Nardo</nav><h1 class="product_title entry-title">Pavaj Nardo</h1><p class="price"><span class="woocommerce-Price-amount amount">28&nbsp;<span class="woocommerce-Price-currencySymbol">lei</span></span> &ndash; <span class="woocommerce-Price-amount amount">32&nbsp;<span class="woocommerce-Price-currencySymbol">lei</span></span> <small class="woocommerce-price-suffix">incl. TVA</small></p>

Website URL: http://www.elit-pavaj.ro

**Comment by sferdiand** [comment]
![image](https://user-images.githubusercontent.com/29863110/27793038-178aaf2e-600
![image](https://user-images.githubusercontent.com/29863110/27793045-1ae2277e-6005-11e7-9e25-08bf775f990a.png)

![image](https://user-images.githubusercontent.com/29863110/27793121-5bae9ddc-6005-11e7-927c-29e03cd44cd4.png)

**Comment by mikejolley** [comment]
Looks like taxes are being removed.

If taxes are based on customisation location this can happen. You can set the 'default customer address' to shop base to avoid it if geolocation fails. See your settings.
