### ISSUE TITLE
[3.1] Infinite loop if T&C page is set to be the Checkout Page

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#15949]
![](http://cld.wthms.co/KecOlP+)

Can prevent this by disallowing any "special" pages from being selectable here. This could include cart, checkout, account, shop, blog, and front page. Thought it's really only the checkout page that's going to cause problems.

Ultimately this stems back to us allowing shortcodes to being parseable in the T&C area at checkout though. So another solution could be to disallow some shortcodes from being parsed?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/15959
