### ISSUE TITLE
Percentage discount coupon with usage restriction products not applied to entire cart

### ISSUE THREAD

**Issue by brezocordero** [woocommerce/woocommerce#15945]
## Prerequisites
WooCommerce 3.1

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a coupon with Percentage discount and a product on usage restrictions
http://cld.wthms.co/3Y4l0
http://cld.wthms.co/35lxeo
2. Add the product on usage restrictions and other products to the cart
3. Apply the coupon

## Expected behavior and actual behavior

When I follow those steps, I see...

The discount is only applied to the product on usage restrictions
http://cld.wthms.co/XBTbL2

I was expecting...
The discount would be applied to the entire cart. 
593925-zd-woothemes

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://brezotestsite.mystagingwebsite.com
Site URL: https://brezotestsite.mystagingwebsite.com
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.20
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.54.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-Spam: by Automattic – 3.3.2
Jetpack by WordPress.com: by Automattic – 5.0
VaultPress: by Automattic – 1.9.1
WooCommerce: by Automattic – 3.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #3 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
@brezocordero Is this documented to work differently anywhere? Seems the current logic makes more sense - you're only applying it to a single product.

**Comment by brezocordero** [comment]
@mikejolley Thanks for looking into it!

From the doc here: 
https://docs.woocommerce.com/document/coupon-management/
> Discount type :
> Percentage discount – A percentage discount for the entire cart. For example, if the cart contains three (3) t-shirts @ $20 each = $60, a coupon for 10% off applies a discount of $6.
> Fixed cart discount – A fixed total discount for the entire cart. For example, if the cart contains three (3)  t-shirts @ $20 each = $60, a coupon for $10 off gives a discount of $10.
> Fixed product discount – A fixed total discount for selected products only. Customer receives a set amount of discount per item. For example, three (3) t-shirts @ $20 each with a coupon for $10 off applies a discount of $30.

And on Usage Restriction section:

> Products – Products that the cart must contain for the coupon to be valid; or which products are discounted for Product Discounts.

My understanding is that the coupon would be applied to the entire cart, if the product is present.

**Comment by mikejolley** [comment]
I think we should change that wording so restrictions are clearly honoured. If you restrict a coupon to certain things, it should only affect those IMO. This has been the behaviour for a few versions anyhow.

@californiakat

**Comment by jobthomas** [comment]
@mikejolley It also needs to be reworded in the help tool in core, but I can do that. 

Before the coupons were changed, depending on whether it was a cart or product coupon the effect of this condition was different indeed.

![http://cld.wthms.co/YcpBJa](http://cld.wthms.co/YcpBJa+)
Link to image here: http://cld.wthms.co/YcpBJa.

I'll assign to myself and take this issue for WooCommerce core.

**Comment by jobthomas** [comment]
@californiakat doc updated as well.

**Comment by jobthomas** [comment]
@ryanr14 I've tried to see what's happening with that video, but for some reason it's not working here. Can you check that it's in line with the docs?
