### ISSUE TITLE
Free Shipping (min order) + Virtual Product = unexpected results

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#15946]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Free shipping is configured to require a minimum order total of $50
2. A virtual product exists which costs $25
3. A regular, physical simple product exists - cost unimportant
4. Add one of the virtual products to the cart
5. Add some number of the physical product to the cart so that the cart subtotal is less than the $50 threshold.
6. On the cart page, increase the qty of the virtual product - the cart subtotal is now above the requisite order total for free shipping
6. Expect free shipping to be available at this point, but it is not:
![see screen shot](http://cld.wthms.co/N7NyiQ+)
7. Add one more of the physical product, free shipping now available:
![see screen shot](http://cld.wthms.co/aSFjV6+)
8. Decrease the qty of each product by one then update cart. cart subtotal now below the minimum for free shipping but free shipping remains:
![see screen shot](http://cld.wthms.co/aEjZHG+)

## Expected behavior and actual behavior

When I follow those steps, I see...

Shipping options that are presented are not as configured

I was expecting...

For my free shipping to work as configured

reported in ticket: 589657-zd-woothemes and replicated locally with latest master

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://local.woo
Site URL: http://local.woo
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.8
PHP Version: 7.0.14-2+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.53 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 3.2.1
WooCommerce: by Automattic – 3.2.0-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
Umm, hmmm. This get's weirder, at least on my install w/ master branch.

Free Shipping: requires $100 in cart
Virtual Product: $50
Physical Product: $15

Free shipping shows up even before just the physical product reaches over $100: http://cld.wthms.co/Bn20P. What's more, is that free shipping then stays available when it shouldn't be as a reduce to below $100. You can see where it disappears, and it's quite strange. The last two refreshes show a new problem.

**Comment by WPprodigy** [comment]
Problem is here: https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/class-wc-shipping.php#L358. `get_rates_for_package` is never called/doesn't need updating when virtual products are increased.

This probably causes issues with other extensions with conditional logic around shipping, like Conditional Shipping and Payments.
