### ISSUE TITLE
Typo in dutch version at checkout "Accept terms"

### ISSUE THREAD

**Issue by Bldjef** [woocommerce/woocommerce#15942]
There's a very little typo (but still ugly ^^) when accepting terms and conditions at the checkout in the Dutch language file.

current: Ik heb de voowaarden gelezen en ga ermee akkoord
correct: Ik heb de voorwaarden gelezen en ga ermee akkoord

and maybe its better to use this, because it's the most known/used in dutch webshops:

Ik heb de algemene voorwaarden gelezen en ga ermee akkoord

Thanks!

**Comment by mikejolley** [comment]
Please see https://wordpress.org/support/topic/updating-translations-after-updates/ - this needs handling on the translation site :)
