### ISSUE TITLE
update_wc_div called incorrectly when removing products from cart

### ISSUE THREAD

**Issue by jkohlbach** [woocommerce/woocommerce#15950]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce
- [X ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Seems we aren't calling update_wc_div correctly in item_remove_clicked in cart.js causing old messages to stack/display in some cases.

Its the same issue as #12877 but for removing products (this previous ticket was about quantity box change event, this is about clicking remove event)

## Expected behavior and actual behavior

I believe the fix should be to change:

`success: update_wc_div,`

to:

`success: function( response ) {
	update_wc_div( response );
},`

## Environment

<details>
```
Not required
```
</details>

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
Can replicate: http://cld.wthms.co/pRuS3
