### ISSUE TITLE
Issue with Woocommerce Product type

### ISSUE THREAD

**Issue by zitihsk** [woocommerce/woocommerce#15957]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce 

Create any product from woocommerce  product tab and all later when tried to fetch type of product for variable product programatically, output is  simple type.

I tried to create multiple product with variable product type , all i can receive from below code is simple type. 
Code Snippet : 
..., 
$product = new WC_Product($post->ID);
var_dump($product->get_type()); 
.. 

Output: 
string(6) "simple"

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
You shouldn't be calling `new WC_Product()`. See https://github.com/woocommerce/woocommerce/blob/cb59bd048764ebf3e2aa311e1d30d745960bee44/includes/abstracts/abstract-wc-product.php#L105-L108

```
$product = wc_get_product( 253 );
var_dump( $product->get_type() );
```
