### ISSUE TITLE
PayPal Standard: IPN and PDT enabled

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#15951]
I see support problems come up quite often in regards to "duplicate stock removal" and issues like that. The issue is when a merchant has PDT enabled but IPN isn't enabled. Is there something we can do to prevent this from mattering? Fool-proof this setting in other words?

![](http://cld.wthms.co/EtIVgh+)

**Comment by mikejolley** [comment]
@WPprodigy  If being used as a fallback you cannot work around the requests coming in at the same time until we do https://github.com/woocommerce/woocommerce/issues/15780 That issue was logged specifically for this.

**Comment by mikejolley** [comment]
Yup checked the code. This can happen if you return at the same time as the IPN request coming in separately. Since there is no locking, both updates occur simultaneously. We'll need #15780 to resolve this. If IPN is working, PDT can be disabled for now.

**Comment by thenbrent** [comment]
Now that #20030 has been proposed as a solution to #16971 (which replaces #15780 mention above), let me know if you'd like me to submit a PR to address this issue with Action Scheduler. We just saw it come up on AutomateWoo.com, where we had both IPN and PDT enabled.

**Comment by kloon** [comment]
@thenbrent I like the idea, let's wait till Action Scheduler gets merged then you are welcome to give it a go. We are not too far away from getting it merged.

**Comment by bome** [comment]
Any update on this? Thanks!

**Comment by oempire** [comment]
I still have this issue @mikejolley was there any progress with the subsequent tasks?

**Comment by ptvtpc** [comment]
I still have the same problem. Is there any fix for this yet?

**Comment by alexalouit** [comment]
@ptvtpc remove PayPal token in order to disable IPN
