### ISSUE TITLE
Rest API Product shipping_class property doesnt accept empty string

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#15960]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. push request to /wp-json/wc/v2/products/<id>
2. update property shipping_class from 'my_class' to ''
3. send request returns 'my_class' and product is not updated

## Expected behavior and actual behavior

shipping_class should be changed to '' but instead it returns the old 'my_class' value

Also tried with -1, '-1', null etc. but the problem still occurs

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost:9001
Site URL: http://localhost:9001
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: PHP 7.1.3 Development Server
PHP Version: 7.1.3
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.51.0
SecureTransport

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

StorePilot Dev: by StorePilot – 1.0.0
WooCommerce: by Automattic – 3.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NOK (kr)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #234 - /index.php/products-pags/
Cart: #453 - /index.php/cart/
Checkout: #455 - /index.php/checkout/
My account: #457 - /index.php/my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1 – 1.3 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/da35bad7bc9922a430aeeb0870ae8da557e4f46f/includes/api/class-wc-rest-products-controller.php#L1122-L1128
