### ISSUE TITLE
Help Tab: "Ghost" views occurring on some videos.

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce#15964]
Hi all,

I've noticed this over the past two releases that via the help tab this video is getting a lot of ghost plays. It's racking up a lot of "views" with less than one percent engagement rates which makes me suspect a problem or conflict of some sort. The urls look like these below.

wp-admin/term.php?taxonomy=product_cat&tag_ID=24&post_type=product
wp-admin/edit.php?post_type=product&page=product_attributes
wp-admin/edit-tags.php?taxonomy=product_cat&post_type=product

There are other videos embedded in the help tab in WooCommerce core, but this is the only one recording this behavior. Any ideas or suggestions?

![](http://cld.wthms.co/TDOgOw+)

**Comment by mikejolley** [comment]
@ryanr14 From what I can see they are no different. All videos are the same on all pages. 

Could it be something video related? https://wistia.com/doc/embed-options#autoplay

> If you're using your Wistia account you can set a video to autoplay right within the Customize panel. Check out our help page for all of the details.

Or maybe it's because the videos are all in english and the visitors bouncing are from new markets ¯\_(ツ)_/¯

**Comment by ryanr14** [comment]
I like your theories. :)

Autoplay is off, I double checked there. I don't think it's a problem of English language scaring off viewers. Lots of the "plays" come from English speaking countries. Plus no other videos in the collection have that many plays and that low engagement. The 0% engagement rates you see above mean the video starts to play then essentially stops before even one second actually plays.

It's only happening on this video for some reason. Here you can see where I tested and watched 16 seconds of the video. When I first logged into the site and loaded the help screen the video flashed, but I haven't been able to reproduce it yet.

![](http://cld.wthms.co/yFuTW+)

I'll keep digging and try replacing the video, changing the title, etc... to see if I can find any cause.

**Comment by ryanr14** [comment]
I snooped further through stats and actually found more videos plagued by this. 👎 

![http://cld.wthms.co/PLKNe](http://cld.wthms.co/PLKNe+)
![http://cld.wthms.co/t37TqA](http://cld.wthms.co/t37TqA+)
![http://cld.wthms.co/e7cWca](http://cld.wthms.co/e7cWca+)
![http://cld.wthms.co/Xb2c5](http://cld.wthms.co/Xb2c5+)

I think in addition to the first, there are 5 total that are getting the ghost plays. I'll continue looking for any signs that would be causing this for these few videos.

**Comment by ryanr14** [comment]
@mikejolley Is there a 3.1.1 being prepped for release soon? Just curious on how much time'ish I'd have to figure this out. :)

**Comment by mikejolley** [comment]
@ryanr14 Next tue.

**Comment by mikejolley** [comment]
@ryanr14 I think it will be difficult to get to the bottom of this one without some trial and error - they don't autoplay for me, however I do notice if auto play is set to true, it shows when the tab is hidden. Related.

I just reviewed the docs and the implementation is wrong. We have an iframe + async JS. Iframes are already aysync. I'll switch over to the correct async method of embedding - it may help.
