### ISSUE TITLE
API - Updatet order with new order_items, stock not updatet

### ISSUE THREAD

**Issue by wespiremedia** [woocommerce/woocommerce#15962]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

I want to update an order with extra products (upsells) by the API after an original order is created. 

To achieve this I've written the following (demo) code: 

```
$order = $woocommerce->get('orders/45');

$order_items     = $order['line_items'];
$order_items[]   = array(
    'sku'       => 'UP1',
    'quantity'  => 3
);

$update = $woocommerce->put('orders/45', array(
    'line_items' => $order_items
));
```

After executing this code, the upselling product is added to the order and order amounts etc. are updatet. 

## Expected behavior and actual behavior

When I follow those steps, I see that the order lines are added to the order, but the stock of the newly added product isn't reduced. 

I was expecting that the stock of the added product (with SKU 'UP1') was reduced by 3. 

From a previous project I can remember I have to run a Woocommerce PHP function after updating an order, to recount and recalculate stock/totals. I expected the API to run this functions after the update, because I can't find anything about manually trigger this in te docs.

**Comment by mikejolley** [comment]
Stock is reduced after certain events, such as a status change, and once. They are not ran multiple times after adding new items to orders. 

https://github.com/woocommerce/woocommerce/issues/13359

You'll either need to do the changes before the order gets paid, or reduce the stock of the products via the products endpoint.

**Comment by mikejolley** [comment]
`set_paid` is the API arg you'd need to use. Stock reduction is hooked into `woocommerce_payment_complete`

**Comment by wespiremedia** [comment]
The stock is indeed updatet after the order status has changed. Thank you!
