### ISSUE TITLE
Getting "Billing State / County is not valid." when selecting Mexico as a country and Edo de Mexico as state

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce#15977]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set your general settings to ![](http://cld.wthms.co/6kQt1m+)
2. Checkout with a product and select `Edo de Mexico` as Billing state
3. Click `Place Order` to be greeted with:  ![](http://cld.wthms.co/OVUkax+)

## Expected behavior and actual behavior

I was expecting the order to be placed but got an error from the Billing state field.

## Environment

<details>

### WordPress Environment ###

Home URL: http://wootest.dev
Site URL: http://wootest.dev
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.13.1
PHP Version: 7.0.20-2~ubuntu14.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: MXN ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /?page_id=4
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My account: #7 - /?page_id=7

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

@mattyza @mikejolley

**Comment by pacom3434** [comment]
El problema pasa cuando  actualizas de la version 3.0.5 a  la version 3.1.0 no encuentro una solucion mas viable que volver a la version anterior....a mi me paso lo mismo y especificamente al seccionar el estado de mexico....es uno de los tantos problemas que da woocommerce tras cada actualizacion ...

**Comment by mayakid** [comment]
We are having the same problem! Selecting Queretaro for the desired state and this message appears.

**Comment by mayakid** [comment]
Has anyone had a solution with this?

**Comment by claudiulodro** [comment]
@mayakid @pacom3434  WC 3.1.1 is releasing tomorrow with a fix for this. If you can't wait, [these are the changes you need to make](https://github.com/woocommerce/woocommerce/pull/15980/files).

**Comment by segsalerty2013** [comment]
@claudiulodro , The update didn't fix the issue when a `filter` is applied to change a country states. 
Facing thesame challenge too. Had to temporarily comment out line `666 to 669` to completely remove that validation. 
Also, this is same reason `shipping calculator` still loads up woocommerce default states in `cart` page. 
- I still havent figured out work around for the `shipping calculator` issue. Any help will be appreciated.
cc: @spraveenitpro Is your issues fixed?

Thanks.

**Comment by mikejolley** [comment]
The states will use correct codes in 3.2

**Comment by segsalerty2013** [comment]
Okay, great ! Appreciate this. How soon are we looking at ?

**Comment by mikejolley** [comment]
3.2 is due out Early sep.

**Comment by danielsalare** [comment]
@spraveenitpro Hi, did you manage to fix this, we are having the same issue.
