### ISSUE TITLE
Product Is Not Importing with the New Built In Importer/Exporter for Woocommerce due to "invalid product type"

### ISSUE THREAD

**Issue by KelvinCabrera** [woocommerce/woocommerce#15973]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Exported product CSV file from my shopify site, removed non-UTF-8 characters from it, and uploaded it in the CSV importer.
2. Mapped the columns as best as I could, then proceeded to import.
3. The CSV file I imported was Test-WooCommerce-Import-4.csv, viewable here https://drive.google.com/file/d/0B6hq7WP8wlDvbUYtSTY1NGh6QUk/view?usp=sharing.

## Expected behavior and actual behavior

When I follow those steps, I see...
Import failure, with "invalid product type" as the reason.
![image](https://user-images.githubusercontent.com/29916896/27861988-b522e72c-61b5-11e7-9899-4bc5217bf4ae.png)

I was expecting...
Import success.
## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
We plan on mapping Shopify data in a future update, but for now you just need to ensure 'type' is not mapped to product type since they are different. You can map it to category or tag, or "do not map".

<img width="734" alt="2017-07-05 at 12 25" src="https://user-images.githubusercontent.com/90977/27862435-0ce165e4-617d-11e7-89bb-178e11694ff4.png">

**Comment by mikejolley** [comment]
Once that is deselected or mapped elsewhere it works.

We're working on the mappings in https://github.com/woocommerce/woocommerce/pull/15976

Thanks

**Comment by claudiosanches** [comment]
The "Type" from Shopify CSV is in fact "Categories", you could just change it to categories and import all products as "Simple" type.
