### ISSUE TITLE
Stock Levels Disappearing 

### ISSUE THREAD

**Issue by jzmwebdevelopment** [woocommerce/woocommerce#15972]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

I have just done an upgrade to 3.1.0 and noticed that all my stock levels have gone to 0 and out of stock on all products however there are still variations that should be in stock that are not showing the correct setting of in stock etc.

I have managed to reproduce this on a live and local server using 2x back up databases from different times and all stock shows 0 and out of stock.

**Live Server**  
`
### WordPress Environment ###

Home URL:
Site URL: 
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 300 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 300 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (36) ###

Swipe Checkout for WooCommerce: by Swipe – 2.9.1
Akismet Anti-Spam: by Automattic – 3.3.2
All-in-One WP Migration: by ServMask – 6.50
Contact Form 7: by Takayuki Miyoshi – 4.8
Simple Custom CSS and JS: by Diana Burduja – 3.3
Disable Comments: by Samir Shah – 1.6
Paulund Facebook Like Box: by Paul Underwood – 1.0
Google Analyticator: by SumoMe – 6.5.3
IgniteWoo Updater: by IgniteWoo.com – 2.1.9
Maintenance: by fruitfulcode – 3.5.1
Newsletter: by Stefano Lissa & The Newsletter Team – 4.9.9
Page Speed: by Rex Anthony D. Eubanas – 1.2.3
WooCommerce PartPay Gateway: by John Andrew Jose – 1.0
Post Types Order: by Nsp Code – 1.9.3.1
WooCommerce Product Filter: by Mihajlovic Nenad – 2.2.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Remove Query Strings From Static Resources: by Speed Up My Website
Your WP Expert – 1.4

Simple Responsive Menu: by SutharInfo – 2.1
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.5
WooCommerce Bulk Stock Management: by WooThemes – 2.2.1 – 2.2.8 is available
WooCommerce - Country Based Payments: by Ivan Paulin – 1.1.8
WooCommerce Customizer: by SkyVerge – 2.5.0
WooCommerce Payment Express Gateway: by OPMC – 1.93 – 2.2 is available
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce js cookie fix: by Rynaldo – 1.0
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.6.0

WooCommerce Order Status Control: by SkyVerge – 1.2 – 1.8.0 is available
WooCommerce Store Credit: by WooThemes – 2.1.4 – 2.1.8 is available
WooCommerce Xero Integration: by WooThemes – 1.7.3 – 1.7.9 is available
WooCommerce: by Automattic – 3.1.0
WooSidebars: by WooThemes – 1.4.3
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 4.9
WP Add Custom CSS: by Daniele De Santis – 1.0.1
WP Migrate DB: by Delicious Brains – 0.9.2
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD (NZD $)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
featured (featured)
exclude-from-catalog (exclude-from-catalog)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #2302 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: PrimRose Fashion Shop
Version: 1.5
Author URL: http://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Primrosefashionshop/woocommerce/archive-product.php
Primrosefashionshop/woocommerce/auth/footer.php
Primrosefashionshop/woocommerce/auth/form-grant-access.php
Primrosefashionshop/woocommerce/auth/form-login.php
Primrosefashionshop/woocommerce/auth/header.php
Primrosefashionshop/woocommerce/cart/cart-empty.php
Primrosefashionshop/woocommerce/cart/cart-item-data.php
Primrosefashionshop/woocommerce/cart/cart-shipping.php
Primrosefashionshop/woocommerce/cart/cart-totals.php
Primrosefashionshop/woocommerce/cart/cart.php
Primrosefashionshop/woocommerce/cart/cross-sells.php
Primrosefashionshop/woocommerce/cart/mini-cart.php
Primrosefashionshop/woocommerce/cart/proceed-to-checkout-button.php
Primrosefashionshop/woocommerce/cart/shipping-calculator.php
Primrosefashionshop/woocommerce/checkout/cart-errors.php
Primrosefashionshop/woocommerce/checkout/form-billing.php
Primrosefashionshop/woocommerce/checkout/form-checkout.php
Primrosefashionshop/woocommerce/checkout/form-coupon.php
Primrosefashionshop/woocommerce/checkout/form-login.php
Primrosefashionshop/woocommerce/checkout/form-pay.php
Primrosefashionshop/woocommerce/checkout/form-shipping.php
Primrosefashionshop/woocommerce/checkout/payment-method.php
Primrosefashionshop/woocommerce/checkout/payment.php
Primrosefashionshop/woocommerce/checkout/review-order.php
Primrosefashionshop/woocommerce/checkout/terms.php
Primrosefashionshop/woocommerce/checkout/thankyou.php
Primrosefashionshop/woocommerce/content-product.php
Primrosefashionshop/woocommerce/content-product_cat.php
Primrosefashionshop/woocommerce/content-single-product.php
Primrosefashionshop/woocommerce/content-widget-product.php
Primrosefashionshop/woocommerce/emails/admin-cancelled-order.php
Primrosefashionshop/woocommerce/emails/admin-failed-order.php
Primrosefashionshop/woocommerce/emails/admin-new-order.php
Primrosefashionshop/woocommerce/emails/customer-completed-order.php
Primrosefashionshop/woocommerce/emails/customer-invoice.php
Primrosefashionshop/woocommerce/emails/customer-new-account.php
Primrosefashionshop/woocommerce/emails/customer-note.php
Primrosefashionshop/woocommerce/emails/customer-on-hold-order.php
Primrosefashionshop/woocommerce/emails/customer-processing-order.php
Primrosefashionshop/woocommerce/emails/customer-refunded-order.php
Primrosefashionshop/woocommerce/emails/customer-reset-password.php
Primrosefashionshop/woocommerce/emails/email-addresses.php
Primrosefashionshop/woocommerce/emails/email-customer-details.php
Primrosefashionshop/woocommerce/emails/email-footer.php
Primrosefashionshop/woocommerce/emails/email-header.php
Primrosefashionshop/woocommerce/emails/email-order-details.php
Primrosefashionshop/woocommerce/emails/email-order-items.php
Primrosefashionshop/woocommerce/emails/email-styles.php
Primrosefashionshop/woocommerce/emails/plain/admin-cancelled-order.php
Primrosefashionshop/woocommerce/emails/plain/admin-failed-order.php
Primrosefashionshop/woocommerce/emails/plain/admin-new-order.php
Primrosefashionshop/woocommerce/emails/plain/customer-completed-order.php
Primrosefashionshop/woocommerce/emails/plain/customer-invoice.php
Primrosefashionshop/woocommerce/emails/plain/customer-new-account.php
Primrosefashionshop/woocommerce/emails/plain/customer-note.php
Primrosefashionshop/woocommerce/emails/plain/customer-on-hold-order.php
Primrosefashionshop/woocommerce/emails/plain/customer-processing-order.php
Primrosefashionshop/woocommerce/emails/plain/customer-refunded-order.php
Primrosefashionshop/woocommerce/emails/plain/customer-reset-password.php
Primrosefashionshop/woocommerce/emails/plain/email-addresses.php
Primrosefashionshop/woocommerce/emails/plain/email-customer-details.php
Primrosefashionshop/woocommerce/emails/plain/email-order-details.php
Primrosefashionshop/woocommerce/emails/plain/email-order-items.php
Primrosefashionshop/woocommerce/global/breadcrumb.php
Primrosefashionshop/woocommerce/global/form-login.php
Primrosefashionshop/woocommerce/global/quantity-input.php
Primrosefashionshop/woocommerce/global/sidebar.php
Primrosefashionshop/woocommerce/global/wrapper-end.php
Primrosefashionshop/woocommerce/global/wrapper-start.php
Primrosefashionshop/woocommerce/loop/add-to-cart.php
Primrosefashionshop/woocommerce/loop/loop-end.php
Primrosefashionshop/woocommerce/loop/loop-start.php
Primrosefashionshop/woocommerce/loop/no-products-found.php
Primrosefashionshop/woocommerce/loop/orderby.php
Primrosefashionshop/woocommerce/loop/pagination.php
Primrosefashionshop/woocommerce/loop/price.php
Primrosefashionshop/woocommerce/loop/rating.php
Primrosefashionshop/woocommerce/loop/result-count.php
Primrosefashionshop/woocommerce/loop/sale-flash.php
Primrosefashionshop/woocommerce/myaccount/dashboard.php
Primrosefashionshop/woocommerce/myaccount/downloads.php
Primrosefashionshop/woocommerce/myaccount/form-add-payment-method.php
Primrosefashionshop/woocommerce/myaccount/form-edit-account.php
Primrosefashionshop/woocommerce/myaccount/form-edit-address.php
Primrosefashionshop/woocommerce/myaccount/form-login.php
Primrosefashionshop/woocommerce/myaccount/form-lost-password.php
Primrosefashionshop/woocommerce/myaccount/form-reset-password.php
Primrosefashionshop/woocommerce/myaccount/lost-password-confirmation.php
Primrosefashionshop/woocommerce/myaccount/my-account.php
Primrosefashionshop/woocommerce/myaccount/my-address.php
Primrosefashionshop/woocommerce/myaccount/my-downloads.php
Primrosefashionshop/woocommerce/myaccount/my-orders.php
Primrosefashionshop/woocommerce/myaccount/navigation.php
Primrosefashionshop/woocommerce/myaccount/orders.php
Primrosefashionshop/woocommerce/myaccount/payment-methods.php
Primrosefashionshop/woocommerce/myaccount/view-order.php
Primrosefashionshop/woocommerce/notices/error.php
Primrosefashionshop/woocommerce/notices/notice.php
Primrosefashionshop/woocommerce/notices/success.php
Primrosefashionshop/woocommerce/order/form-tracking.php
Primrosefashionshop/woocommerce/order/order-again.php
Primrosefashionshop/woocommerce/order/order-details-customer.php
Primrosefashionshop/woocommerce/order/order-details-item.php
Primrosefashionshop/woocommerce/order/order-details.php
Primrosefashionshop/woocommerce/order/tracking.php
Primrosefashionshop/woocommerce/product-searchform.php
Primrosefashionshop/woocommerce/single-product/add-to-cart/external.php
Primrosefashionshop/woocommerce/single-product/add-to-cart/grouped.php
Primrosefashionshop/woocommerce/single-product/add-to-cart/simple.php
Primrosefashionshop/woocommerce/single-product/add-to-cart/variable.php
Primrosefashionshop/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Primrosefashionshop/woocommerce/single-product/add-to-cart/variation.php
Primrosefashionshop/woocommerce/single-product/meta.php
Primrosefashionshop/woocommerce/single-product/price.php
Primrosefashionshop/woocommerce/single-product/product-attributes.php
Primrosefashionshop/woocommerce/single-product/product-image.php
Primrosefashionshop/woocommerce/single-product/product-thumbnails.php
Primrosefashionshop/woocommerce/single-product/rating.php
Primrosefashionshop/woocommerce/single-product/related.php
Primrosefashionshop/woocommerce/single-product/review-meta.php
Primrosefashionshop/woocommerce/single-product/review-rating.php
Primrosefashionshop/woocommerce/single-product/review.php
Primrosefashionshop/woocommerce/single-product/sale-flash.php
Primrosefashionshop/woocommerce/single-product/share.php
Primrosefashionshop/woocommerce/single-product/short-description.php
Primrosefashionshop/woocommerce/single-product/tabs/additional-information.php
Primrosefashionshop/woocommerce/single-product/tabs/description.php
Primrosefashionshop/woocommerce/single-product/tabs/tabs.php
Primrosefashionshop/woocommerce/single-product/title.php
Primrosefashionshop/woocommerce/single-product/up-sells.php
Primrosefashionshop/woocommerce/single-product-reviews.php
Primrosefashionshop/woocommerce/single-product.php
Primrosefashionshop/woocommerce/taxonomy-product_cat.php
Primrosefashionshop/woocommerce/taxonomy-product_tag.php

**Local Server**

`
### WordPress Environment ###

Home URL: 
Site URL: http://localhost/woocom
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Unix) PHP/7.0.10 mod_wsgi/3.5 Python/3.5.2 OpenSSL/1.0.1p
PHP Version: 7.0.10
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/1.0.1p

SUHOSIN Installed: –
MySQL Version: 5.6.31
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (36) ###

Akismet Anti-Spam: by Automattic – 3.3.2
WooCommerce PartPay Gateway: by John Andrew Jose – 1.0
WooCommerce: by Automattic – 3.1.0
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #2302 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Primrosefashionshop
Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –
`
`
- [X ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
This won't help: http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-bulk-stock-management/changelog.txt You're running an old version. Don't use it after updating.

I suspect this is a misconfiguration of variable product stock. If you're managing variation stock, ensure the checkbox to enable stock management at product level is unchecked. If it's checked, it won't sync with the children and may assume it has 0 in stock (thus out of stock).

**Comment by mikejolley** [comment]
Closing due to lack of feedback.
