### ISSUE TITLE
Shipping Calculator not using Select2

### ISSUE THREAD

**Issue by Naspat** [woocommerce/woocommerce#15985]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Hi Claudio,

While it’s possible to **fully style** the **Country dropdown menu** as well as the **State/County dropdown menu** on the **Checkout Page**, it’s not currently possible to change the style of the **Country dropdown menu** as well as the **State/County dropdown menu** on the **Cart Page**.

Based on our theme provider it’s because the fields currently have **different semantics.**

**Example: Checkout Page** (here you see a **clean integration** of the Country dropdown menu which **matches the template style.** The same applies to the State/County dropdown menu if active):

![checkout page](https://user-images.githubusercontent.com/29928681/27888475-75ae28aa-61e6-11e7-8a56-78cc95d87ac3.png)

**Example: Cart Page** (here you see the Country and State/County dropdown menu which **DOES NOT currently match** the rest of **the theme style** due to current semantics):

![cart page](https://user-images.githubusercontent.com/29928681/27888478-78fa5088-61e6-11e7-90be-45f53b811b5c.png)

**Please adjust the semantics of the Country and State/County dropdown menu on the Cart Page** so that our template provider is able to adjust the style with the rest of the template accordingly.

Thanks,
Patrick 

## Expected behavior and actual behavior

When I follow those steps, I see...
a mismatch with the rest of the template style.

I was expecting...
to see a match with the rest of the template style.

## Environment

<details>
```

### WordPress Environment ###

WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.19
PHP Post Max Size: 50 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (28) ###

Query Monitor: by John Blackbourn – 2.13.4
404 to 301: by Joel James – 2.3.3
WooCommerce Currency Switcher - Dynamic Pricing Integration: by Aelia  – 1.0.0.170123
Duplicator: by Snap Creek – 1.2.8
Improved Variable Product Attributes for WooCommerce: by Mihajlovic Nenad – 3.3.0
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Nav Menu Roles: by Kathy Darling – 1.8.6
Smart Slider 3 Pro: by Nextend – 3.2.4
Ninja Forms: by The WP Ninjas – 3.1.6
WPML Multilingual CMS: by OnTheGoSystems – 3.7.1
UpSolution Header Builder: by UpSolution – 1.0.4
Use Any Font: by Dinesh Karki – 4.7.3
Aelia Foundation Classes for WooCommerce: by Aelia – 1.8.9.170629
WooCommerce User Role Minimums: by Stephen Sherrard – 2.0.1
Woocommerce User Role Pricing: by Stephen Sherrard – 2.1.2
WooCommerce Wholesale Ordering: by Stephen Sherrard – 3.1.3
Aelia Currency Switcher for WooCommerce: by Aelia – 4.4.11.170405
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.2.7
WooCommerce Dynamic Pricing: by Lucas Stark – 3.0.9
WooCommerce Stripe Gateway: by WooCommerce – 3.2.1
WooCommerce Multilingual: by OnTheGoSystems – 4.2.0
WooCommerce: by Automattic – 3.1.0
WP Cerber: by Gregory – 4.8.2
WP-DBManager: by Lester 'GaMerZ' Chan – 2.79
WP Rocket: by WP Media – 2.10.5
WPML Media: by OnTheGoSystems – 2.2.0
WPML String Translation: by OnTheGoSystems – 2.5.4
WPML Translation Management: by OnTheGoSystems – 2.3.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
instock (instock)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #6697 - /checkout/
My account: ❌ Page does not contain the shortcode.

### Theme ###

Name: Impreza Child
Version: 1.0
Author URL: http://us-themes.com/
Child Theme: ✔
Parent Theme Name: Impreza
Parent Theme Version: 4.5
Parent Theme Author URL: http://us-themes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
Currently the cart page uses standard select fields for the shipping calculator: http://cld.wthms.co/WKXzm

Would need to use select2 instead, or selectWoo when it's ready.
