### ISSUE TITLE
Unfinished WooCommerce Province/State/Canton Master List

### ISSUE THREAD

**Issue by Naspat** [woocommerce/woocommerce#15983]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

On the **WooCommerce Cart Page** --> **Calculate Shipping** --> **Select a country...** --> **Brazil** there are existing provinces (i.e. Acre, Alagoas, etc.) automatically showing up if you click on the **"Select an option..."** box, whereas in case of i.e. Switzerland nothing shows up despite of existing cantons (= provinces).

The same observation can be made on the **WooCommerce Checkout Page.**

**INFO:** Not only Switzerland is affected by this **unfinished province/state/canton master list** but also many other countries as well.

Solution?
Thanks!

## Expected behavior and actual behavior

When I follow those steps, I see...
no provinces/cantons

I was expecting...
to see provinces/cantons

## Environment

<details>
```
`
### WordPress Environment ###

WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.19
PHP Post Max Size: 50 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (28) ###

Query Monitor: by John Blackbourn – 2.13.4
404 to 301: by Joel James – 2.3.3
WooCommerce Currency Switcher - Dynamic Pricing Integration: by Aelia  – 1.0.0.170123
Duplicator: by Snap Creek – 1.2.8
Improved Variable Product Attributes for WooCommerce: by Mihajlovic Nenad – 3.3.0
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Nav Menu Roles: by Kathy Darling – 1.8.6
Smart Slider 3 Pro: by Nextend – 3.2.4
Ninja Forms: by The WP Ninjas – 3.1.6
WPML Multilingual CMS: by OnTheGoSystems – 3.7.1
UpSolution Header Builder: by UpSolution – 1.0.4
Use Any Font: by Dinesh Karki – 4.7.3
Aelia Foundation Classes for WooCommerce: by Aelia – 1.8.9.170629
WooCommerce User Role Minimums: by Stephen Sherrard – 2.0.1
Woocommerce User Role Pricing: by Stephen Sherrard – 2.1.2
WooCommerce Wholesale Ordering: by Stephen Sherrard – 3.1.3
Aelia Currency Switcher for WooCommerce: by Aelia – 4.4.11.170405
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.2.7
WooCommerce Dynamic Pricing: by Lucas Stark – 3.0.9
WooCommerce Stripe Gateway: by WooCommerce – 3.2.1
WooCommerce Multilingual: by OnTheGoSystems – 4.2.0
WooCommerce: by Automattic – 3.1.0
WP Cerber: by Gregory – 4.8.2
WP-DBManager: by Lester 'GaMerZ' Chan – 2.79
WP Rocket: by WP Media – 2.10.5
WPML Media: by OnTheGoSystems – 2.2.0
WPML String Translation: by OnTheGoSystems – 2.5.4
WPML Translation Management: by OnTheGoSystems – 2.3.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
instock (instock)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #6697 - /checkout/
My account: ❌ Page does not contain the shortcode.

### Theme ###

Name: Impreza Child
Version: 1.0
Author URL: http://us-themes.com/
Child Theme: ✔
Parent Theme Name: Impreza
Parent Theme Version: 4.5
Parent Theme Author URL: http://us-themes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

In case of Brazil (the same applies to the US and Turkey):
![brazil](https://user-images.githubusercontent.com/29928681/27885945-2ed39552-61da-11e7-9606-d8a04fe531b3.jpg)

In case of Switzerland:
![switzerland](https://user-images.githubusercontent.com/29928681/27885956-3c80cea4-61da-11e7-85b6-071334ccd8c0.jpg)

**Comment by claudiosanches** [comment]
Are you talking about not having options for Switzerland like for Brazil?

![screenshot from 2017-07-05 18-32-24](https://user-images.githubusercontent.com/1264099/27885959-5ae1bcf2-61b0-11e7-8bff-2624d8d74c62.png)

Like this screenshot?
If so is not a bug, it's just because no one every sent to us any list of Switzerland cantons like we have for Brazil:
https://github.com/woocommerce/woocommerce/blob/master/i18n/states/BR.php

> INFO: Not only Switzerland is affected by this unfinished province/state/canton master list but also many other countries as well.

Is not unfinished or don't try to be a master list.. It list only for those that contributed sending Pull Requests with the correct list of provinces/states/cantons for they own countries, and in some countries is not even necessary indicate anything for this field too, another reason to depend on contributors. So welcome to the open source world and I'm waiting for your contribution listing all Switzerland cantons :smiley:

**Comment by Naspat** [comment]
Hi Claudio,

Please find below the complete list of **all 26 Swiss cantons:**

**Aargau
Appenzell Ausserrhoden
Appenzell Innerrhoden
Basel-Landschaft
Basel-Stadt
Bern
Freiburg
Genf
Glarus
Graubünden
Jura
Luzern
Neuenburg
Nidwalden
Obwalden
Schaffhausen
Schwyz
Solothurn
St. Gallen
Tessin
Thurgau
Uri
Waadt
Wallis
Zug
Zürich**

_Source: https://de.wikipedia.org/wiki/Kanton_(Schweiz)_ 

Thank you for updating your database accordingly asap.
Patrick

**Comment by claudiosanches** [comment]
@Naspat That `Abk.` codes on Wikipedia are the correct ones?

**Comment by Naspat** [comment]
@claudiosanches 

**Abk.** stands for **Abkürzung** in German which means **Abbreviation** in English.

So, in case of i.e. **Zürich** (which is the full name of the canton), the abbreviation of Zürich is **ZH**. 

**Note:** Make sure to **USE ONLY the full length of the canton** (i.e. Zürich) in your dropdown list instead of also the abbreviation ZH.

**Example of a typical dropdown list** (Strikethrough terms have been corrected accordingly to reflect the grammatically correct German language. Also compare to the official Wikipedia source further above):

![swiss cantons](https://user-images.githubusercontent.com/29928681/27887645-199218e6-61e2-11e7-881a-d556383a2949.png)

Thanks for the inclusion asap,
Patrick

**Comment by claudiosanches** [comment]
I think is better copy from https://en.wikipedia.org/wiki/Cantons_of_Switzerland
So can be properly translated into any language after.

**Comment by Naspat** [comment]
Ok, that sounds reasonable. When will the list become part of your next official WooCommerce update?

**Comment by claudiosanches** [comment]
Probably on 3.2.

**Comment by Naspat** [comment]
Great! Thank you.
