### ISSUE TITLE
Empty area of product images (Woocommerce)

### ISSUE THREAD

**Issue by DavidDeas** [woocommerce/woocommerce#15989]
Hello!
I ask you to help with this I want to remove the display of images from all products registered in functions.php:
`remove_action( ‘woocommerce_before_single_product_summary’, ‘woocommerce_show_product_images’, 20 );
As I wanted the image disappeared, but there remains an empty area and I would like to headline and everything else to divide the field
[http://icloudspb.ru/product/1/](url)
Thank you in advance!

**Comment by DavidDeas** [comment]
I have no idea what to prescribe in style.css

**Comment by mikejolley** [comment]
```
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
```

This is not the place for customisations.
