### ISSUE TITLE
[woocommerce_order_tracking] needs some updating.

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#15986]
Well, TIL there is a [woocommerce_order_tracking] shortcode.

1) I'm not sure if we should be showing download links: http://cld.wthms.co/Ni2m3X. That is giving download access if somebody just has order number and email address. Could maybe wait for https://github.com/woocommerce/woocommerce/issues/15563 to resolve this, and just not include the new downloads table.

2) The error handeling isn't so great.

If you enter an order ID that doesn't exist, you get an error about the order ID not existing in the database.

If you enter a valid ID but not the right email, you get no messages - page just refreshes.

____

I honestly wonder how used this shortcode is though? Maybe worth deprecating?

**Comment by mikejolley** [comment]
It's quite common to find tracking pages on stores. The errors I agree should be more vague to hinder brute forcing.
