### ISSUE TITLE
Widget "Sale product" shows products with expired offers

### ISSUE THREAD

**Issue by networksolution** [woocommerce/woocommerce#15991]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. For a given product X, enter a sale price and sale price dates in the past (expired offer);
2. Add widget "Sale products" to sidebar;

## Expected behavior and actual behavior

When I follow those steps, I see the widget doesn't display product X, as it isn't on sale anymore

I was expecting the widget display product X (luckily, with the correct, regular, price).

## Environment

<details>
### WordPress Environment ###

Home URL: http://www.digitpro.it/laboratoriocanevari
Site URL: http://www.digitpro.it/laboratoriocanevari
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: it_IT

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 16 MB
PHP Time Limit: 999999
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - Consigliamo l'uso di MySQL con versione minima 5.6. Per i dettagli: Requisiti WordPress
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: nsm28uQfA_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ Il database MaxMind GeoIP non esiste - La geolocalizzazione non funzionerà. È possibile scaricarlo e installarlo manualmente da http://dev.maxmind.com/geoip/legacy/geolite/ al percorso: . Scorrere fino a "download" e scaricare il file "Binary / gzip" accanto a "GeoLite Country". Ricordarsi di decomprimere GeoIP.dat.gz e caricare solo il file GeoIP.dat.

### Security ###

Secure connection (HTTPS): ❌Il tuo negozio non utilizza HTTPS. Scopri di più su HTTPS e certificati SSL .
Hide errors from visitors: ✔

### Active Plugins (14) ###

Share Buttons by AddThis: by The AddThis Team – 5.3.5
Akismet Anti-Spam: by Automattic – 3.3.2
Essential Grid: by ThemePunch – 2.1.0.2
Instagram Feed: by Smash Balloon – 1.4.9
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MailChimp per Wordpress: by ibericode – 4.1.5
Slider Revolution: by ThemePunch – 5.2.5.4
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.5
ThemeREX Utilities: by ThemeREX – 3.0
Visual Composer Extensions All In One: by Sike – 3.4.5
Booster Plus for WooCommerce: by Algoritmika Ltd – 1.1.0
Booster for WooCommerce: by Algoritmika Ltd – 2.9.0
WooCommerce: by Automattic – 3.1.0
WordPress Social Login: by Miled – 2.3.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #21 - /shop/
Carrello: #514 - /carrello/
Cassa: #516 - /checkout/
Il mio account: #518 - /my-account/

### Theme ###

Name: Organic Beauty
Version: 1.0
Author URL: http://themerex.net/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
There is no 'sale widget', but there is a products widget which supports filtering by on sale, and a shortcode.

Did 2 tests.

1 adding a new product and checking widget and sale shortcode.
2 editing an existing sale product and setting dates to the past

Both resulted in the product not being shown, which is correct given it's expired. So you're either using a different widget, or you're seeing cache/conflict from another plugin.

Even though you checked "This bug happens with only WooCommerce plugin active", the log states others are active e.g. booster which can affect this.

**Comment by networksolution** [comment]
I did tests with default theme and no other plugin active, but when I generated the log later, I already had switched again to my theme. I updated the report with the correct log and a screenshot.

**Comment by mikejolley** [comment]
Make sure you put a product on sale after deactivating those plugins - they may interfere with the actual save routines.

**Comment by networksolution** [comment]
I understood what happened. There was a variable product, where only one 
variant is on sale. The widget displayed the whole product (showing the 
correct price range: 12,00 € - 25,00 €), and not just the variant.

I suspect this is by design, but this may confuse users. I would suggest 
to improve this in next releases, maybe offer an option to show just 
variants on sale.

Also, it is currently not possible to show only a single variant in any 
slider (like an Essential Grid or Revolution Slider used to show only 
sale products).

MM


Il 06/07/2017 11:24, Mike Jolley ha scritto:

**Comment by tk1175** [comment]
I was having the same problem and tracked the issue back to a wp-cron event called woocommerce_scheduled_sales that hadn't been firing.  Manually firing the event using the "WP Control" plugin resolved the issue at least temporarily.  Others may want to check for issues with wp-cron.php to resolve this issue.  Note that visiting /wp-cron.php?doing_wp_cron was not running the job for some reason...
