### ISSUE TITLE
Fatal error in checkout if we add order pay in URL

### ISSUE THREAD

**Issue by eliasjnior** [woocommerce/woocommerce#15995]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add some product to the cart
2. Go to checkout
3. Add `?order-pay=75782831273` (any unknown ID)

Example: `http://localhost/finalizar-compra/?order-pay=1234` (`finalizar-compra` is the endpoint to the checkout).

## Expected behavior and actual behavior

Following this steps, I got a fatal error:
```
( ! ) Fatal error: Uncaught Error: Call to a member function get_total() on boolean in /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php on line 219

Error: Call to a member function get_total() on boolean in /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-payment-gateway.php on line 219
```

This is caused because of the `get_order_total()` in `is_available()` method in the gateway. The only check is `if ( 0 < $order_id ) {`, so in this example, 75782831273 is bigger than 0, but doesn't exists. 

## Environment

<details>
`
### WordPress Environment ###

Home URL: http://paypal.dev
Site URL: http://paypal.dev
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR

### Server Environment ###

Server Info: nginx/1.11.13
PHP Version: 7.1.3
PHP Post Max Size: 40 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ O seu servidor não possui a classe SoapClient ativada - alguns métodos de pagamento que usam SOAP podem não funcionar como esperado.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ O banco de dados GeoIP MaxMind não existe. A geolocalização não funcionará. Você pode fazer download e o instalar manualmente de http://dev.maxmind.com/geoip/legacy/geolite/ para o caminho: . Role a página para baixo para "Downloads" e faça download do arquivo "Binary / gzip" ao lado de "GeoLite Country". Lembre-se de descompactar o GeoIP.dat.gz e fazer upload apenas do arquivo GeoIP.dat.

### Security ###

Secure connection (HTTPS): ❌Sua loja não está usando HTTPS. Saiba mais sobre HTTPS e certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (6) ###

PagBrasil: por PagBrasil – 2.1.0
PayPal Plus Brazil for WooCommerce: por  –
Woo PayPal Plus Brasil: por Elias Júnior – 1.0.5
WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.6.0
WooCommerce: por Automattic – 3.1.0
Importador do WordPress: por wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base da loja: #4 - /
Carrinho: #5 - /carrinho/
Finalizar compra: #6 - /finalizar-compra/
Minha conta: #7 - /minha-conta/

### Theme ###

Name: Storefront
Version: 2.2.3 – 2.2.4 está disponível
Author URL: https://woocommerce.com/
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema pai. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by hogash** [comment]
@eliasjnior this issue still happens. Why did you closed it? Did you remember what was causing it?

**Comment by eliasjnior** [comment]
> @eliasjnior this issue still happens. Why did you closed it? Did you remember what was causing it?

Nice question. I think I reported the error to somebody that fixed, or should have fixed.

Later today I will check if this bug still happed, and if yes, I will re-open and make a PR.

**Comment by hogash** [comment]
@eliasjnior Thanks!! Following your steps to reproduce the issue, it still ends up in some errors. I know that this shouldn't happen, but still, the checks must be validated to avoid errors.
