### ISSUE TITLE
I can't add a new shipping method

### ISSUE THREAD

**Issue by fabiocorda** [woocommerce/woocommerce#15990]
## Prerequisites
I can't add a new shipping zone.
![immagine](https://user-images.githubusercontent.com/29942613/27900858-3248645a-6230-11e7-9f36-2f77aa8b8100.png)
![immagine](https://user-images.githubusercontent.com/29942613/27900893-4bee0022-6230-11e7-8b70-9a2a6ce0cb10.png)

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. woocommerce -> Setting -> shipping
2. Add new zone
3. Add new spedition method

## Expected behavior and actual behavior

When I follow those steps, nothing heppens

## Environment

<details>

`
### WordPress Environment ###

Home URL: http://www.semplicidesideri.it/centro.benessere.biologico
Site URL: http://www.semplicidesideri.it/centro.benessere.biologico
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.20
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Il tuo negozio non utilizza HTTPS. Scopri di più su HTTPS e certificati SSL .
Hide errors from visitors: ✔

### Active Plugins (7) ###

Akismet Anti-Spam: by Automattic – 3.3.2
eCommerce Product Catalog sviluppato da impleCode: by impleCode – 2.7.4
PopupAlly: by AmbitionAlly – 2.0.1
Code Embed: by David Artiss – 2.2.2
Ultimate Landing Page Premium: by umarbajwa – 4.0
WooCommerce: by Automattic – 3.1.0
WP-Pro-Quiz: by Julius Fischer – 0.37

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: e-mail (e-mail)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ La pagina non è impostata
Carrello: ❌ La pagina non è impostata
Cassa: ❌ La pagina non è impostata
Il mio account: ❌ La pagina non è impostata

### Theme ###

Name: Formation
Version: 2.4.3
Author URL: http://www.templateexpress.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ❌ Non dichiarato

### Templates ###

Overrides: –
`

</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
No issues here. Also from your screenshot it's not really clear what is not working. You have a zone. You have a method. So clearly you were able to add them both?

**Comment by fabiocorda** [comment]
I can add, but i can't save

**Comment by mikejolley** [comment]
It's not clear, but the save is greyed out because it's already saved. If you refresh the zone/method is still there. Save only becomes available when there are pending changes.

UI improvements will come in future versions.

**Comment by fabiocorda** [comment]
It's not possible to change, it's not possible to save. What's unclear?

**Comment by mikejolley** [comment]
The UI is unclear that you don't need to 'save' once you've added a new method.

**Comment by fabiocorda** [comment]
I think that it's not difficult to understand:
I can't add a new method. 
I can't modify a method. 
I can't delete a method. 

I don't need to 'save' after added a new method.
I need to add a new method, but i can't.

woocommerce -> Setting -> shipping
Add new zone
Add new spedition method
Nothing change. No method added.


No problem Mikejolley, bug solved, I uninstalled woocommerce.

**Comment by mikejolley** [comment]
@fabiocorda I tried following your instructions. They were on the thin side and your screenshots were not clear. 

If you want me to look for myself and see if there are errors, my email is on my profile. I'd need a login. Otherwise I'm not able to replicate the issue.
