### ISSUE TITLE
WooCommerce order notification not received after PayPal payment completed

### ISSUE THREAD

**Issue by dbriedel** [woocommerce/woocommerce#15992]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Customers are making product purchases using the configured standard PayPal payment gateway.
2. After success the client sees the order received summary page.
3. And the customer gets a payment confirmation from PayPal but nothing from WooCommerce.

## Expected behavior and actual behavior

When I follow those steps, the shop owner nor the customer get a confirmation email from WooCommerce as that was happening before the update (30/06/2017) to version 3.1 from version 3.08.

But I see the order being created with the purchase and customer details and an IPN payment completed notification within the order page.

If an order is done using bank transfer or payment on delivery everybody gets notification emails without fail. 

I have installed an Email logging plug-in to see if anything is triggered when a PayPal transaction happens but nothing shows up. I also activated the PayPal debugging feature and it shows all details of the purchase reported back to WooCommerce, as attached below.
[paypal-f5cffba681017ec7ce9ccd2e57348361.txt](https://github.com/woocommerce/woocommerce/files/1127301/paypal-f5cffba681017ec7ce9ccd2e57348361.txt)

I checked the format of the emails in the email templates, as well as adding an email from a different domain, but to no avail.

## Environment

<details>
`
### WordPress Environment ###

Home URL: https://www.esotech.com.au
Site URL: https://www.esotech.com.au
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.29
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wpeso_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

All In One WP Security: by Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.2.8

Advanced Automatic Updates: by pento – 1.0.2
BackWPup: by Inpsyde GmbH – 3.4.1
Check Email: by Chris Taylor – 0.5.5
Contact Form 7: by Takayuki Miyoshi – 4.8
Divi 100 Login Page: by Elegant Themes – 0.0.1
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.2.7
WooCommerce: by Automattic – 3.1.0
WP Mail Logging: by Christian Zöller – 1.8.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #92 - /shop/
Cart: #93 - /shop/cart/
Checkout: #94 - /shop/checkout/
My account: #95 - /my-account/

### Theme ###

Name: Divi Child Theme
Version: 1.0.9
Author URL: http://wdb.nz/
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.53
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/woocommerce/emails/admin-cancelled-order.php
Divi-child/woocommerce/emails/admin-failed-order.php
Divi-child/woocommerce/emails/admin-new-order.php
Divi-child/woocommerce/emails/customer-completed-order.php
Divi-child/woocommerce/emails/customer-invoice.php
Divi-child/woocommerce/emails/customer-new-account.php
Divi-child/woocommerce/emails/customer-note.php
Divi-child/woocommerce/emails/customer-on-hold-order.php
Divi-child/woocommerce/emails/customer-processing-order.php
Divi-child/woocommerce/emails/customer-refunded-order.php
Divi-child/woocommerce/emails/customer-reset-password.php
Divi-child/woocommerce/emails/email-addresses.php
Divi-child/woocommerce/emails/email-customer-details.php
Divi-child/woocommerce/emails/email-footer.php
Divi-child/woocommerce/emails/email-header.php
Divi-child/woocommerce/emails/email-order-details.php
Divi-child/woocommerce/emails/email-order-items.php
Divi-child/woocommerce/emails/email-styles.php
Divi-child/woocommerce/emails/plain/admin-cancelled-order.php
Divi-child/woocommerce/emails/plain/admin-failed-order.php
Divi-child/woocommerce/emails/plain/admin-new-order.php
Divi-child/woocommerce/emails/plain/customer-completed-order.php
Divi-child/woocommerce/emails/plain/customer-invoice.php
Divi-child/woocommerce/emails/plain/customer-new-account.php
Divi-child/woocommerce/emails/plain/customer-note.php
Divi-child/woocommerce/emails/plain/customer-on-hold-order.php
Divi-child/woocommerce/emails/plain/customer-processing-order.php
Divi-child/woocommerce/emails/plain/customer-refunded-order.php
Divi-child/woocommerce/emails/plain/customer-reset-password.php
Divi-child/woocommerce/emails/plain/email-addresses.php
Divi-child/woocommerce/emails/plain/email-customer-details.php
Divi-child/woocommerce/emails/plain/email-order-details.php
Divi-child/woocommerce/emails/plain/email-order-items.php
`
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
@dbriedel If you want to email me admin and FTP details I can find the error which was thrown before the status changed, but I'm 99% sure this will be a conflict with a plugin/theme.

**Comment by dbriedel** [comment]
Thanks for your quick reply I have emailed you the access credentials.

**Comment by kylehovance** [comment]
We have been experiencing the exact same issue. We have tried disabling all other plugins and temporarily switching to the default theme with no luck.

**Comment by jbrenner99** [comment]
We have had the exact same issue since upgrading from 3.0.4 to 3.0.8.  We have PayPal set to send both IPN and PDT.  If seems that if the order only gets updated with a PDT then in the order notes we get an "Order status changed from Pending payment to Processing" and emails are sent properly.  However, if only an IPN is received, no order status change occurs and no emails are sent.

**Comment by bretweinraub** [comment]
I have the exact problem.   SInce upgrading to WC 3.0.7, IPN payment completed message appear in the order notes, but there is no message 'order status changed from pending to processing'.   Strangely enough, the order status is processing.

Our own plugins that implement hooks on 

woocommerce_order_status_processing

no longer get called.

We tried adding hooks on 

woocommerce_payment_complete_order_status

but those don't get called either.

Theme is:

Mystile

Version: 1.3.4

**Comment by bretweinraub** [comment]
@dbriedel - what was the problem?   Maybe my theme has the same problem.

**Comment by kebarriere** [comment]
Just like @bretweinraub, I'm experiencing the same problem but the ticket was closed without stating the exact problem with @dbriedel's theme. Why not explaining to everybody else?

**Comment by bretweinraub** [comment]
In the end, PHP was erroring out in the PayPal callback.   Sadly for me, silently [nothing in the PHP log]; so it was quite challenging to debug.

Are you sure PHP isn't crashing?

**Comment by Jaethon** [comment]
This may be related.  When selling virtual products (gift cards),  the order remained at pending, even after payment.

After speaking with the guy at Angelleye, I was directed to a plugin (PayPal IPN) and to some php code to add to the site. (I put it in a must-use plugin).

`    if(!empty($order_id)) {
        $order = new WC_Order($order_id);
        $order->update_status('completed');     
    }
}
add_action('paypal_ipn_for_wordpress_payment_status_completed', 'update_wc_order_status', 10, 1);
`
Now it was working fine—however, I noticed that if I programmatically "completed" the order, the other actions weren't triggered (email notification of order and order completion, as well as an email going to the recipient of the gift cards).

So I've been looking all over for solutions to this.  I think the triggers are tied in to the actual clicking of the 'complete' button and not the completed status of the order itself.  Because even with the new code, the button click still triggers all the actions.

**Comment by 1manfactory** [comment]
The answer is pretty easy.
The customer simply does not wait till he gets redirected to the shop. I tested it with my wife when I finally realiced the problem. She never waits till she gets redirected, she always closed the browser tab.
Hence WooCommerce never receives a payment confirmation.
So the status gets stuck at "awayting payment."
