### ISSUE TITLE
Rest api query param one dimensional arrays should not require 0

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#15998]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use Rest Api to post / push one dimensional arrays as query param to any endpoint
2. ex. mysite.com/wp-json/wc/v2/endpoint?arr[]=test1&arr[]=test2
3.

## Expected behavior and actual behavior

Expected:

arr[]=test1&arr[]=test2 to be supported

But does only work with

arr[0]=test1&arr[0]=test2

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
@steffanhalv  What is 'arr'? Is it listed in the REST API docs? I don't think any are?

**Comment by steffanhalv** [comment]
@mikejolley Any array, its not a specific property

For example, try to update upsell_ids for product with queryparams like ?upsell_ids[]=1&upsell_ids[]=2 etc..

It doesnt work and you have to type

?upsell_ids[0]=1&upsell_ids[0]=2 etc..

**Comment by claudiosanches** [comment]
We just copied the same behavior from https://wordpress.org/plugins/rest-api-oauth1/ that is the official plugin for oAuth1.0 for WordPress REST API.
And I don't see any problem to include the array indexes, even more that almost any programming language will do it without any extra effort.
