### ISSUE TITLE
Enable flexslider only when there's multiple slides

### ISSUE THREAD

**Issue by cyrildc** [woocommerce/woocommerce#16002]
Currently on a single product page, if we only  have  the Product Image and no Product Gallery, the slider is initialized.

In the single-product.js, the allowOneSlide parameter should be set to false when flexslider is initialized.
`

	ProductGallery.prototype.initFlexslider = function() {
		var $target = this.$target;

		$target.flexslider( {
			selector:       ".woocommerce-product-gallery__wrapper > .woocommerce-product-gallery__image",
			animation:      wc_single_product_params.flexslider.animation,
			smoothHeight:   wc_single_product_params.flexslider.smoothHeight,
			directionNav:   wc_single_product_params.flexslider.directionNav,
			controlNav:     wc_single_product_params.flexslider.controlNav,
			slideshow:      wc_single_product_params.flexslider.slideshow,
			animationSpeed: wc_single_product_params.flexslider.animationSpeed,
			animationLoop:  wc_single_product_params.flexslider.animationLoop, // Breaks photoswipe pagination if true.
			allowOneSlide:  false,
			start: function() {
				$target.css( 'opacity', 1 );
			}
		} );
	};

`

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16011
