### ISSUE TITLE
Updating to Canvas 5.11.5 using the new WooCommerce Updater from 3.1 deletes theme files

### ISSUE THREAD

**Issue by jeffikus** [woocommerce/woocommerce#16004]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Expected behavior and actual behavior

To update to version 5.11.5 of Canvas directly from the new WooCommerce updater, and the installation to run smoothly.

After running the update, the theme files are deleted from the site. The site's homepage displays and error message saying "Stylesheet missing".

An extension takes the place of the plugin. I had "woocommerce-shipping-multiple-addresses" be pulled up by the site as the theme, but a user I helped on Live Chat seemed to have a different file referenced there.

The issue is solved by manually uploading the theme files of Canvas version 5.11.5.

Further details: https://github.com/woocommerce/canvas/issues/820

**Comment by mikejolley** [comment]
The canvas issue specifically has been resolved on the woo.com side, with some other hardening patches being merged soon again woo.com side. There is no action required in core.

**Comment by jeffikus** [comment]
Thanks @mikejolley !
