### ISSUE TITLE
install woothemes update plugin prompt remains after update to woocommerce 3.1

### ISSUE THREAD

**Issue by waterfireprov** [woocommerce/woocommerce#16005]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. upgrade to woocommerce 3.1 (from 3.0)
2. connect to woocommerce.com
3. delete old woocommerce helper plugin

## Expected behavior and actual behavior

When I follow those steps, I see...

The `Install the WooThemes Updater plugin to get updates for your WooThemes plugins.` alert on my admin pages.

I was expecting...

Not to see this alert anymore.

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://waterfire.org/store
Site URL: http://waterfire.org/store
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 16 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.19.1 Basic ECC

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.30 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_6_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (47) ###

Popup Maker: by WP Popup Maker – 1.6.3
Fancier Author Box: by ThematoSoup – 1.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
Homepage Control: by WooThemes – 2.0.2
VarkTech Pricing Deals for WooCommerce: by Vark – 1.1.7.1
VarkTech Pricing Deals PRO for WooCommerce: by VarkTech – 1.1.7.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SeedProd Coming Soon Pro: by SeedProd – 4.5.3
Storefront Footer Bar: by WooThemes – 1.0.3
Storefront Parallax Hero: by WooThemes – 1.5.4
Storefront Product Pagination: by WooThemes – 1.2.1
Storefront Product Sharing: by WooThemes – 1.0.4
Storefront Site Logo: by Wooassist – 1.2.2
Storefront Sticky Add to Cart: by WooThemes – 1.1.6
Storefront WooCommerce Customiser: by WooThemes – 1.9.2
Woo Stickers by Webline: by Weblineindia – 1.1.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce: by Automattic – 3.1.0
Gravity Forms Authorize.Net Add-On: by rocketgenius – 2.3
Gravity Forms PayPal Standard Add-On: by rocketgenius – 2.8
Pretty Link: by Blair Williams – 2.1.1
WordPress HTTPS: by Mike Ems – 3.3.6
WordPress Importer: by wordpressdotorg – 0.6.3
WP-UserOnline: by Lester 'GaMerZ' Chan – 2.87.1
Print, PDF & Email by PrintFriendly: by Print
PDF
& Email by PrintFriendly – 3.9.0

WooCommerce Customer/Order CSV Export: by SkyVerge – 4.3.5
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Shortcoder: by Aakash Chakravarthy – 4.0.2
Enhanced Text Widget: by Boston Dell-Vandenberg – 1.4.5
Akismet Anti-Spam: by Automattic – 3.3.2
WooCommerce Authorize.Net AIM Gateway: by SkyVerge – 3.11.3
Broken Link Checker: by Janis Elsts
Vladimir Prelovac – 1.11.3

Gravity Forms MailChimp Add-On: by rocketgenius – 4.2
Storefront Sticky Add to Cart: by WooThemes – 1.1.6
Storefront WooCommerce Customiser: by WooThemes – 1.9.2
Wordfence Security: by Wordfence – 6.3.12
BackupBuddy: by iThemes – 8.0.1.0
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.8
Optimize Database after Deleting Revisions: by CAGE Web Design | Rolf van Gelder
Eindhoven
The Netherlands – 4.2.3

Yoast SEO: by Team Yoast – 4.9
Gravity Forms: by rocketgenius – 2.2.3
Social Media Feather: by socialmediafeather – 1.8.4
Google Language Translator: by Rob Myrick – 5.0.30
Storefront Parallax Hero: by WooThemes – 1.5.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
WP Super Cache: by Automattic – 1.4.9
Easy WP SMTP: by wpecommerce – 1.2.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #6 - /products/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: Homestore
Version: 2.0.20
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.4
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: homestore/woocommerce/single-product/title.php

### Authorize.Net AIM ###

Environment: Production
Debug Mode: Off

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled
`
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
@waterfireprov I've just spent a while installing all of the woo extensions you're running and get no notice. We have code in core which unhooks that notice as soon as the helper is loaded:

https://github.com/woocommerce/woocommerce/blob/d1ad5a92d218931a230a265f406da09031f9ac02/includes/admin/helper/class-wc-helper-compat.php#L25

So it could be that a notice is being added by a different function in one of the extensions, OR it could be that a third party plugin has 'borrowed' some core code and prefixed this functions differently.

Something odd in your report, and I'm not sure if this is related, you have lots of duplicate plugins. I wonder if there is something going on with those, or if it's just a copy/paste error.

Ideally someone needs to access your site and take a look around/narrow down the cause to a single plugin which is adding the notice. **For that reason I'm going to ask you to submit a ticket to https://woocommerce.com/contact-us/, reference this issue, and provide them with a temporary login.**

This issue does not appear to be affecting other users; I had a search across zendesk before replying.

Cheers

p.s. Minor nitpick, you did check the "- [x] This bug happens with only WooCommerce plugin active" box. If that were the case you'd have no notices at all because no extensions would be active :)

**Comment by waterfireprov** [comment]
Thanks @mikejolley,

Since the old helper plugin was network activated I had several extensions also network activated, this is what was causing the erroneous alert. Thanks for pointing out the duplicate plugins. Also, I misread the "with only woocommerce active" check box as "only with woocommerce"

Best, Tim
