### ISSUE TITLE
Structured data is incomplete

### ISSUE THREAD

**Issue by attilah** [woocommerce/woocommerce#16006]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Create a product with variants and check the resulting html.

## Expected behavior and actual behavior

Correct LD+JSON data rendered for the page.

On a launched site with the latest WP and WC I tried to locate the SEO data. I was happy what WC is using LD+JSON instead of markup, which is really theme dependent and a mess to maintain.

I found out that the simple product page contains 2 types of seo data: breadcrumb and product.

I see the following problems:
- Structured Data when wrapped into a graph element, there is not @context attribute at that level.
- Product item is missing the description, image and some other values, since in case of variants they're put into the Offers item and no default values lifted to the product level.

The root cause of the problem in the latest release is that this line was missing, which was re-added now in master: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-structured-data.php#L237

**Comment by mikejolley** [comment]
If it's in master, why have you logged this issue again?

**Comment by mikejolley** [comment]
That's being added in 3.1.1. Is there more to the issue?

**Comment by attilah** [comment]
@mikejolley that one line is in master, but that is only part of the problem/bug.

I think that if you've variants of a product and there is a default variant selected on the visible web page, then that selected variant data should be reflected in the ```$markup``` too, to make google happy.

Currently if you validate the generated simple product page with google for a product, you'll see what I miss, I think.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/16010 takes care of context.

As for variations, we don't show each and every variation in that markup. For stores with hundreds of variations (does happen) this would take too long to query and render.

<img width="702" alt="2017-07-07 at 11 29" src="https://user-images.githubusercontent.com/90977/27954448-f29407a0-6307-11e7-8068-69a85e99c142.png">

With variable products, the image + description is pulled from the parent. For variations, we simply take the min and max prices.

Filters exist to extend the markup if needed.

Thanks

**Comment by bimini** [comment]
I think we all realize Structured Data is not all about Rich Snippets, and Breadcrumbs, and how you appear on SERP, but about providing **complete structured (machine readable) information** about your item, service, company, person, or content, image or video clip. Most of the SD we audit is partial, usually missing important information. Other is simply Markup from original incorrect information.

**Comment by frankug** [comment]
Structured data is failing the structured data testing tool

@id is not a known valid target type for the identifier property.

There never used to be an @id and there shouldn;t be one - how do I quickly remove this in the interim until woocommerce fix this properly?

**Comment by opportus** [comment]
Hi @frankug,

From [W3](https://www.w3.org/TR/json-ld/#node-identifiers):

> `@id` is used to uniquely identify things that are being described in the document with IRIs or blank node identifiers.

> To be able to externally reference nodes in a graph, it is important that nodes have an identifier.

If you mean that Google is throwing an error because of the `@id` property, then it's new.
Does it throw this same error in product categories? If not, my guess would be that Google now checks if the `@id` is in a `@graph` or not...

Meanwhile, you can use this filter hook `woocommerce_structured_data_product` to modify what you want.

Some references about the `@id`:
https://www.w3.org/TR/json-ld/#h3_syntax-tokens-and-keywords
https://www.w3.org/TR/json-ld/#node-identifiers

**Comment by opportus** [comment]
About the `@id` error, see #16292

**Comment by globalee** [comment]
Hi opportus, thanks for taking the time to reply.

Can you paste the code to add to functions to resolve this for now, you mention its a google tool error, I see that it was in the prior examples of class--wc-structured-data.php

so does this mean conclusivly it is not an error in that file?

Or is it required to modiy the functions file to remove or change something.

Im a noob so a code snippet for functions would be most appreciated that i ca just paste in there for now.

Do you think its ok to add the # to get rid of the error or shall I just leave it?

thanks

**Comment by opportus** [comment]
Hi @globalee,

I'm not sure this thread is appropriate for this kind of question, however, since you asked already and it might help somebody else, I think I should answer...

Meanwhile Google or WooCommerce fixes the situation you can remove the trailing slash which cause the problem this way:

```php
add_filter( 'woocommerce_structured_data_product', 'my_structured_data_product', 10, 2 );

function my_structured_data_product( $markup, $product ) {
    $markup['@id'] = rtrim( $markup['@id'] );

    return $markup;
}
```

I think this should work...

**Comment by globalee** [comment]
Traditionally, URLs that pointed to files did not include the trailing slash, while URLs that pointed to directories do include the trailing slash. This means that:

    http://webdesign.about.com/example/ is a directory, while
    http://webdesign.about.com/example is a file

could this be the issue

**Comment by globalee** [comment]
Thanks, @opportus

**Comment by globalee** [comment]
OK could not get the trim function to work,,,

However Im using a custom permalinks plugin that allows me to strips the category,  and remove the product page / manually from the permalink and slug fields on the page.
url  = domain/product**/**

So i had the opotunity to strip the trailing slash/ directly from within editing the product by changing the permalink directly  to to **url = domain/product**  (no trailing slash)  then tested this by calling from google structured data testing tool

Still get error...

However the modification with the # as per what I mentiond before does not return an error when using GDSTT?

the plot thickens.

**Comment by opportus** [comment]
@globalee, I forgot the second argument of the `rtrim()` in my first reply which I've updated since then. Did you take the newer reply as reference?

Personnally, I find more appropriate/natural to trim the trailing slash instead of adding a `#` next to it...

**Comment by globalee** [comment]
that dosent fix it though

it appears its the 

**{"@graph":[  enclosing it thats causing the issue on single items mabey? without variations**
## graph removed
[https://search.google.com/structured-data/testing-tool#url=www.seopremo.co.uk%2Ftest.html](url)
see this example here works correctly and includes the back slash

*and the trim function you provided did not work in removing the / for me

**Comment by opportus** [comment]
@globalee,

I just tried my code snippet above... On products with and without variations, with WC 3.1.1, it works for me. Put it in child theme `functions.php` file maybe, purge your caches, and deactivate conflicting plugins...

**Comment by globalee** [comment]
@opportus hi thanks for getting back to me
# this is the version with the slash removed using your code snippet
![error3](https://user-images.githubusercontent.com/108716/28799225-a01b447a-763f-11e7-9984-b8fdd3a81825.png)
 
# this is a version of the page saved from source and edited with the @graph removed  (with or without slash on end)

![error4](https://user-images.githubusercontent.com/108716/28799341-1d340f1e-7640-11e7-861c-95079d58aa53.png)

as you can see the NON graph one has the option to preview?

**I think _graph_ is only used for Groups of products Not single products?**

this page makes mention of it
[https://webmasters.stackexchange.com/questions/90300/how-to-use-more-than-1-schema-org-schema-on-a-web-page](url)

i have structured data in the page already defining other elements, localbusiness, website, organisation, ect....

is the @graph for defining arrays of products or is it used for products with reviews? (as this page is the only one that has reviews and the only one that does not show the preview button?)

**Comment by opportus** [comment]
Hi @globalee,

By default, on single product, WC generates the following SD items:

 - BreadcrumbList
 - Product
 - Review

 This is the reason why there is a `@graph` which is there to contain these multiple items...

In your SS, there is no BreadcrumbList item. I believe this is the cause of some of your problems when you test a product without reviews...

Also, don't use the SDTT editor box to test your changes as at this time, it seems bugged...

Please, post your comments `@id` related in the issue 16292 you have opened.
