### ISSUE TITLE
magnifying glass icon in gallery

### ISSUE THREAD

**Issue by wearehappybits** [woocommerce/woocommerce#16009]
Not sure for what reasons this is inside, but it is very annoying and I am recommending to remove:
https://ibb.co/j6F3Hv

It has to be removed from: assets/js/frontend/single-product.js 

`this.$target.prepend( '<a href="#" class="woocommerce-product-gallery__trigger">🔍</a>' );`

**Comment by mikejolley** [comment]
Theme should hide it once it's added the replacement image: https://dl.dropboxusercontent.com/s/8p11m9xce1v1epi/2017-07-07%20at%2010.42.png

**Comment by wearehappybits** [comment]
So, user is forced to use an image? Storefront theme is using a fontawesome icon instead. So two icons comes up.

**Comment by mikejolley** [comment]
No, user is not forced to use an image. Storefront hides the icon but shows the image. Maybe you have customised some css? Old storefront?

**Comment by jordan-webdev** [comment]
I've run into this issue, too. I had to use CSS pseudo elements to both hide it, and then include my desired background image. It seems a bit hacky. I would think there should be some sort of filter, or option, we can use to get rid of that and add our own html / image instead.

**Comment by mrleemon** [comment]
It would be cool if there was a filter to replace the magnifying glass icon easily. I want to add a SVG icon and the current way to do it is a bit hacky, to be honest.

**Comment by JJ-Coding** [comment]
> It would be cool if there was a filter to replace the magnifying glass icon easily. I want to add a SVG icon and the current way to do it is a bit hacky, to be honest.

Exactly this. I just spent 30 minutes looking through various snippets but not a single one seems to be able to do this. Or if it's included in the template file of the product image that'd be great (/templates/single-product/product-image.php).
