### ISSUE TITLE
post_meta serialized data broken in 3.1.0 when duplicating products.

### ISSUE THREAD

**Issue by Pross** [woocommerce/woocommerce#16007]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Create product
2. Add the following post_meta `a:1:{s:4:"Test";O:8:"stdClass":1:{s:5:"hello";s:5:"world";}}`
3. Duplicate the product.
4. view post_meta for new product in phpmyadmin it is now `a:1:{s:4:"Test";N;}`

This was introduced at commit e14d85d0a39afb65e79a6df6df73632f22f2cfd6

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
This will be in tuesdays fix release, and is already patched in master so I'm not sure why you checked that box ^

https://github.com/woocommerce/woocommerce/pull/15879

**Comment by Pross** [comment]
Maybe I got the compare wrong, yes its fixed in master then.

**Comment by Ver3** [comment]
I hope it is. Can't wait for the update!
