### ISSUE TITLE
Schema data out of date in review-meta.php

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#16018]
As the title says, the schema data in the template is out of date since json-ld is now used:
https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/review-meta.php

Looks like it's the only one still using `itemprop`.

**Comment by nishitlangaliya** [comment]
Fixes - 16018,

itemprop schema removed from review-meta.php. Done PR https://github.com/woocommerce/woocommerce/pull/16021

Thanks
