### ISSUE TITLE
tax import causes double entries on tax standard rates. 

### ISSUE THREAD

**Issue by dmcmillin** [woocommerce/woocommerce#16019]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.import  from csv 100~ tax codes
2.save import
3.erase import
4. save import
5. import again

## Expected behavior and actual behavior

When I follow those steps, I see... double entries. see screen shot
![woocommerce settings live web testing wordpress](https://user-images.githubusercontent.com/13723980/27975416-e9e0dc28-6316-11e7-887e-73dbe9decaee.png)

I was expecting... single entries into the tax system

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
@dmcmillin Can you share your CSV?

**Comment by mikejolley** [comment]
Found a CA tax rates file on internet.
Imported 2592 rates.
System status > tools > delete all rates
0 rates.
Imported again. 2592 rates.

Seems to be fine.

**Comment by Changeworlds11** [comment]
In my case, all tax rates are uploaded successfully but the old rates are not removed. So there are duplicated lists.

Can you please help me to fix that?

**Comment by Changeworlds11** [comment]
Is there any option to replace the old rates when I upload a CSV file?
