### ISSUE TITLE
WooCommerce Pre-Order 1.5.2

### ISSUE THREAD

**Issue by dweuste** [woocommerce/woocommerce#16017]
Pre-ordered product didn't auto-complete and when trying to manually bulk complete orders, it got through three and then it stopped and threw this error which continues to show on each subsequent manual completion attempt:

Fatal error: Uncaught Error: Call to a member function is_type() on boolean in /wp-content/plugins/woocommerce-pre-orders/includes/class-wc-pre-orders-product.php:257 Stack trace: #0 /wp-content/plugins/woocommerce-pre-orders/includes/class-wc-pre-orders-order.php(134): WC_Pre_Orders_Product::product_is_charged_upon_release(false) #1 /wp-content/plugins/woocommerce-pre-orders/includes/class-wc-pre-orders-manager.php(604): WC_Pre_Orders_Order::order_will_be_charged_upon_release(Object(WC_Order)) #2 /wp-content/plugins/woocommerce-pre-orders/includes/admin/class-wc-pre-orders-admin-pre-orders.php(316): WC_Pre_Orders_Manager::complete_pre_order(Object(WC_Order), NULL) #3 /wp-content/plugins/woocommerce-pre-orders/includes/admin/class-wc-pre-orders-admin-pre-or in /wp-content/plugins/woocommerce-pre-orders/includes/class-wc-pre-orders-product.php on line 257

**Comment by claudiulodro** [comment]
GitHub is only for bugs in the core WooCommerce plugin. For WooCommerce extensions, please [file a support ticket](https://woocommerce.com/my-account/create-a-ticket/).
