### ISSUE TITLE
Typo in woocommerce-nl_NL.mo

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/woocommerce#16023]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce
- [ x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Isolating the problem
in .../laguages/plugins/woocommerce-nl_NL.po and .mo a typo exists:
"voowaarden" should be "voorwaarden"

an "r" is missing.

Tnx 

- [x] This bug happens with only WooCommerce plugin active
- [] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by willgorham** [comment]
See #15942

**Comment by WPprodigy** [comment]
https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/nl/default?filters%5Bterm%5D=voowaarden&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
