### ISSUE TITLE
Product Import doesn't import "Date sale price starts" and "Date sale price ends"

### ISSUE THREAD

**Issue by Botronicz** [woocommerce/woocommerce#16028]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Product->Export, save .csv file locally.
2. Open .csv file, modify "Date sale price starts" and "Date sale price ends" fields, save .csv file.
3. Product->Import local .csv file.

## Expected behavior and actual behavior

When I follow those steps, I see...
No change to either date field

I was expecting...
Changes to both date fields.

## Environment
<details>

### WordPress Environment ###

Home URL: https://www.noveltyproducts.org
Site URL: https://www.noveltyproducts.org
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 64 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wptp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Backup: by Backup Guard – 1.1.46
Contact Form 7: by Takayuki Miyoshi – 4.8
Flamingo: by Takayuki Miyoshi – 1.6
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
SendinBlue Subscribe Form And WP SMTP: by SendinBlue – 2.7.3
Media Cleaner: by Jordy Meow – 4.0.7
Product CSV Import Export (BASIC): by XAdapter – 1.3.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SEO by SQUIRRLY: by Squirrly SEO – 8.0.2
Storefront Sticky Add to Cart: by WooThemes – 1.1.6
W3 Total Cache: by Frederick Townes – 0.9.5.4
Sales Notify for WooCommerce: by alisaleem252 – 1.0.0
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.2
WooCommerce Cart Tab: by jameskoster – 1.1.1
WooCommerce Amazon Pay Gateway: by WooCommerce – 1.7.2 – 1.7.3 is available
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2
WooCommerce Sendinblue Newsletter Subscription: by SendinBlue – 1.2.8
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.16 – 4.1.17 is available
WooCommerce: by Automattic – 3.1.0
Wordfence Security: by Wordfence – 6.3.12
WP-Lister Lite for eBay: by Matthias Krok – 2.0.20
mb.miniAudioPlayer: by Pupunzi (Matteo Bicocchi) – 1.8.6
WP Smush: by WPMU DEV – 2.7.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Looks like the date regex in the importer may be too strict.

**Comment by Charan-sai-Myana** [comment]
The same issue is faced by me,when I am trying to import the products in bulk through csv ,it is able to import all the fields except date sale price starts and ends.It would be really helpful if it is able to fix.

**Comment by msacco6** [comment]
same issue.

**Comment by merlin-magic** [comment]
I was having this same issue until I came across this comment from a similar issue:
https://github.com/woocommerce/woocommerce/issues/18019#issuecomment-349333331
The date and time need to be in a very specific format of YYYY-MM-DD HH:MM:SS. 
Opening the csv in a text editor and doing a find/replace on the values I had in there for these new formats did the trick.

**Comment by silviu3dfx** [comment]
@merlin-magic  - great. works like magic:)

**Comment by gbujalil** [comment]
> I was having this same issue until I came across this comment from a similar issue: [#18019 (comment)](https://github.com/woocommerce/woocommerce/issues/18019#issuecomment-349333331) The date and time need to be in a very specific format of YYYY-MM-DD HH:MM:SS. Opening the csv in a text editor and doing a find/replace on the values I had in there for these new formats did the trick.

Amazing! That is the solution, thank you for sharing.

**Comment by bumrushtheshow** [comment]
More than two years later and this still applies. Make sure your spreadsheet program doesn't butcher the format YYYY-MM-DD HH:MM:SS and it will work.

Lovely work @merlin-magic - no idea how you found out because WooCommerce exports do not format like this.
