### ISSUE TITLE
action woocommerce_shipping_classes_save_class sends through different data types depending on context

### ISSUE THREAD

**Issue by majemedia** [woocommerce/woocommerce#16027]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Steps 1:

1. tie into `woocommerce_shipping_classes_save_class` action to save a custom column on a new shipping class
2. print_r `$term_id` contents

Steps 2:

1. tie into  `woocommerce_shipping_classes_save_class` action to update a custom column on an existing shipping class
2. print_r `$term_id` contents

Results

For *Steps 1* `$term_id` is an array consisting of term_id and taxonomy_id

For *Steps 2* `$term_id` is an integer

## Expected behavior and actual behavior

When I follow those steps, I see... an array when a new shipping class is saved and an integer when an existing shipping class is saved.

I was expecting... both situations have the same data type (integer) come through

Class `WC_Ajax`: method `shipping_classes_save_changes`

A new $term_id is set using `wp_insert_term`which returns an array containing the `term_id` and `term_taxonomy_id` 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16044
