### ISSUE TITLE
[shipping_method] shortcode problem

### ISSUE THREAD

**Issue by poyagh** [woocommerce/woocommerce#16029]
Hi. Why after update woocommerce (2.6 to 3.1) shipping method shortcode not works?
It shows:
a:1:{i:0;s:12:”flat_rate:13″;}
I used this shortcode in
https://wordpress.org/plugins/woocommerce-order-address-print/
plugin to show shipping method and it's necessary for me
Regards

**Comment by WPprodigy** [comment]
This github repository is for the WooCommerce core plugin only. There is and never was a `[shipping_method]` shortcode in WC core. Another plugin or your theme had added this feature.
