### ISSUE TITLE
_sale_price_dates_to issue

### ISSUE THREAD

**Issue by antondrob** [woocommerce/woocommerce#16026]
Hi!

I am trying to get **sale price date to** by get_date_on_sale_to(), but var_dump() displays NULL. mysql postmeta displays empty meta_value in _sale_price_dates_to and _sale_price_dates_from. Is it a bug? Or am i wrong?

### WordPress Environment ###

Home URL: https://obuvmart.ru
Site URL: https://obuvmart.ru
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU

### Server Environment ###

Server Info: Apache/2.2.22 (Debian)
PHP Version: 7.0.0
PHP Post Max Size: 128 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.26.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Плагин доставки Boxberry для Woocommerce: от Boxberry – 1.0
Contact Form 7: от Takayuki Miyoshi – 4.8
Custom Taxonomy Order NE: от Marcel Pol – 2.8.3
Cyr to Lat enhanced: от Sol
Sergey Biryukov
Nikolay Karev
Dmitri Gogelia – 3.5

Переводчик Loco: от Tim Whitlock – 2.0.14
MailPoet: от MailPoet – 3.0.0-beta.36.2.0
Extensions for Obuvmart.ru: от Anton Drobyshev – 1.0
Popup Maker: от WP Popup Maker – 1.6.4
Widget Logic: от wpchefgadget
alanft – 5.8.2

WooCommerce and 1C:Enterprise/1С:Предприятие Data Exchange: от Данил Семеленов – 0.7
WOOF - WooCommerce Products Filter: от realmag777 – 2.1.7
WooCommerce: от Automattic – 3.1.0
WordPress HTTPS: от Mike Ems – 3.3.6
Yoast SEO: от Команда Yoast – 5.0.1
WP Encrypt: от Felix Arntz – 1.0.0-beta.7
WP-Mail-SMTP: от Callum Macdonald – 0.10.1
WP Smush: от WPMU DEV – 2.7.1
Яндекс.Касса для WooCommerce: от Yandex.Money – 2.3.6.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: RUB (руб.)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Ссылка магазина: #4 - /shop/
Корзина: #5 - /cart/
Оформление заказа: #6 - /checkout/
Мой аккаунт: #7 - /my-account/

### Theme ###

Name: Virtue - Premium
Version: 4.2.2
Author URL: https://www.kadencethemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: virtue_premium/woocommerce/archive-product.php
virtue_premium/woocommerce/content-product.php
virtue_premium/woocommerce/content-product_cat.php
virtue_premium/woocommerce/content-single-product.php
virtue_premium/woocommerce/loop/loop-end.php
virtue_premium/woocommerce/loop/loop-start.php
virtue_premium/woocommerce/loop/rating.php
virtue_premium/woocommerce/loop/sale-flash.php
virtue_premium/product-searchform.php
virtue_premium/woocommerce/single-product/add-to-cart/external.php
virtue_premium/woocommerce/single-product/add-to-cart/grouped.php
virtue_premium/woocommerce/single-product/add-to-cart/simple.php
virtue_premium/woocommerce/single-product/add-to-cart/variable.php
virtue_premium/woocommerce/single-product/product-image.php
virtue_premium/woocommerce/single-product/product-thumbnails.php
virtue_premium/woocommerce/single-product/related.php
virtue_premium/woocommerce/single-product/sale-flash.php
virtue_premium/woocommerce/single-product/title.php
virtue_premium/woocommerce/single-product/up-sells.php
virtue_premium/woocommerce/single-product.php
virtue_premium/woocommerce/taxonomy-product_cat.php
virtue_premium/woocommerce/taxonomy-product_tag.php

`

**Comment by mikejolley** [comment]
> I am trying to get sale price date to by get_date_on_sale_to(), but var_dump() displays NULL. mysql postmeta displays empty meta_value in _sale_price_dates_to and _sale_price_dates_from. Is it a bug? Or am i wrong?

`get_date_on_sale_to()` is correct to be NULL if _sale_price_dates_to meta is empty - that means there is no date set.

**Comment by antondrob** [comment]
Yes, sorry. This function works only with simple products. Is there any  possibilities to display sale expiry date with variable products? Thanks
