### ISSUE TITLE
Switzerland tax rounding to 0.05

### ISSUE THREAD

**Issue by manuelfrick** [woocommerce/woocommerce#16035]
I tried all, but it is not possible to round to 0.05.

See screenshot attached here:
https://ibb.co/gF8zQF

Doesn't matter if i am in WooRechnung or SevDesk, it doesn't round the price and taxes to 0.05

https://ibb.co/kYUykF

Can you help me?

**Comment by manuelfrick** [comment]
When i add 

`   function euro_5cent_rounding( $in ) {
          return round( $in / 5, 2 ) * 5;
     }
     add_filter( 'woocommerce_tax_round', 'euro_5cent_rounding' );`

to my functions.php it will round my VAT to 10.35 in this example and the complete price to 146.98, so that doesn't work at all.

**Comment by thomas-zg** [comment]
I think you should post this request on https://wordpress.org/support/plugin/woocommerce.

**Comment by manuelfrick** [comment]
But this is a problem with woocommerce, so why don't get help from the programmers of this plugin?

**Comment by mikejolley** [comment]
That code does not work. We'll look at this as part of https://github.com/woocommerce/woocommerce/pull/14475 since it's not a simple fix and affects all calculation logic.
