### ISSUE TITLE
Permalink 404 error

### ISSUE THREAD

**Issue by tunyk** [woocommerce/woocommerce#16032]
I use wordpress 4.8, woocommerce 3.1.0, php 7.1, nginx 1.11, mysql 5.7 in my virtual server.

I off all plugins and use standard theme. I find bug in /wp-admin/options-permalink.php page.

In site woocommerce pages work only if I use combination Plain (Common Settings) + Standard (Product permalinks). In others - 404 error for: all pages, products, categories, my-account, shop, checkout, cart.

I need next links structure:
Site archives: http://site.com/category/postname/
Shop page: http://site.com/shop/
Checkout: http://site.com/checkout/
Cart: http://site.com/cart/
My-account: http://site.com/my-account/
Category: http://site.com/shop/categoryname/
Subcategory: http://site.com/shop/categoryname/subcategoryname/ etc.
Product: http://site.com/shop/productname/

I write next settings, but I don't know why error:
Plain
Сustom Structure - http://site.com/%category%/%postname%/

Optional
Product category base - shop

Product permalinks
Here, I want select Shop base - http://site.com/shop/sample-product/, but when I save radio checked Custom base - /shop/

Maybe it's bug?

**Comment by tunyk** [comment]
I try off woocommerce, all site pages work only if I use Plain (Common Settings), other - 404

**Comment by mikejolley** [comment]
The checkbox isn't the problem, the structure is. You cannot have a product category base of `shop` and a product base of `shop` because they conflict. This will cause 404s.

Set a unique base for the category. e.g. shop-category
