### ISSUE TITLE
WooCommerce 3.1

### ISSUE THREAD

**Issue by Gowsalayadevi** [woocommerce/woocommerce#16039]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Expected behavior and actual behavior

I have integrated the woocommce with the MYOb.  Now I upgraded the wooCommerce version from 2.4 to 3.1. 
There is no issue in placing the order but when it storing the value to MYOB .it is storing the same customer id and name  for very one.
I just wanted to know where I could find the customers detail from woocommerce database and what could be the issue.

**Comment by mikejolley** [comment]
Look at the MYOB integration and see how/when it gets the order and customer details. You can get the customer id FROM the order object. 

`$order->get_customer_id()`

If you didn't build it, contact the developer. We don't develop the MYOB integration,
