### ISSUE TITLE
The cart is empty when Manually creating orders for clients

### ISSUE THREAD

**Issue by C4StudioAU** [woocommerce/woocommerce#16037]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce
- [ X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a manual order for customer
2. Customer will login to pay order via MyAccount-Order via Paypal
3. Customer will be returned to the basket with error (The cart is empty - we have not charged you for this order.)

## Expected behavior and actual behavior

When I follow those steps, I see... Shopping cart with error (The cart is empty - we have not charged you for this order.)

I was expecting... PayPal Login or Payment screen

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: http://c4studio.com.au
Site URL: http://c4studio.com.au
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.30
PHP Post Max Size: 50 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.15
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (22) ###

Hide Admin Bar and Toolbar: by sLaNGjIs & D.J.Fischer – 1.6.1.1
All-in-One WP Migration: by ServMask – 6.52
Contact Form 7: by Takayuki Miyoshi – 4.8
Cornerstone: by Themeco – 2.0.5
Woocommerce - Request a Quote: by Kiran P – 2.54
Lazy Load: by  – 0.6.1
MailChimp for WooCommerce: by MailChimp – 2.0.0
Redirection: by John Godley – 2.6.4
Slider Revolution: by ThemePunch – 5.4.5.1
Subscriptio: by RightPress – 2.3.8
User Switching: by John Blackbourn – 1.0.9
WonderPlugin Grid Gallery: by Magic Hills Pty Ltd – 3.2C
Woo Import Export: by VJInfotech – 2.4
WooCommerce Extended Coupon Features: by Soft79 – 2.5.1
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.1
WooCommerce: by Automattic – 3.1.0
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 5.0.1
WP All Import: by Soflyy – 3.4.4
WP Smush: by WPMU DEV – 2.7.1
X – Email Forms (MailChimp): by Themeco – 1.1.2
X – Google Analytics: by Themeco – 1.0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
variation (variation)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1383 - /shop/
Basket: #424 - /cart/
Checkout: #425 - /checkout/
My account: #426 - /my-account/

### Theme ###

Name: X
Version: 5.1.0
Author URL: http://theme.co/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: x/woocommerce/cart/cart-empty.php
x/woocommerce/cart/cross-sells.php
x/woocommerce/loop/loop-end.php
x/woocommerce/loop/loop-start.php
x/woocommerce/loop/pagination.php
x/woocommerce/notices/error.php
x/woocommerce/notices/notice.php
x/woocommerce/notices/success.php
x/woocommerce/single-product/related.php
x/woocommerce/single-product/tabs/tabs.php
x/woocommerce/single-product/up-sells.php
x/woocommerce/single-product-reviews.php

`

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
I thought this may be PayPal Express but I just did a test order with that and the cart passed correctly across. Ensure your manual order actually has line items, not just a total. Line items are mandatory.

If it's not that, please submit a ticket on https://woocommerce.com/contact-us/ so they can look deeper. I imagine support will require a login to see whats going on - I cannot tell from your status report if there are any problems.

Thanks
