### ISSUE TITLE
Unable to Drag and Drop Categories 

### ISSUE THREAD

**Issue by EatingSaigon** [woocommerce/woocommerce#16030]
Suddenly after a year of successfully and easily dragging & dropping categories to my desired order, the function does not seem to operate.  I drag, but the categories revert back to the top position & will to stay "dropped" to the desired location.

Only change is a recent update to the latest version of WP .  

http://eatingvietnamwithhai.com

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate

**Comment by WPprodigy** [comment]
I can't replicate this. Make sure this still happens when only WooCommerce is active and a default WordPress theme.

Please follow all the prompts / checklists when creating an issue.

**Comment by mikejolley** [comment]
+1 you can reply back if you can reproduce on a clean install, or have entries in your debug log from core relating to this.
