### ISSUE TITLE
VAT not display with variables after update

### ISSUE THREAD

**Issue by beayeric** [woocommerce/woocommerce#16042]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community]
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. update to the last version
2.
3.

I have a problem after update. All products with variable now display directly with VAT and not like before that was with VAT and after with out VAT . This happen only with the variable products. Any help ? thank you very much.

**Comment by mikejolley** [comment]
Variable products do not show this; variations do. See the note here: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-variable.php#L119-L129

**Comment by beayeric** [comment]
Dear mikejolley , 

thank you for your answer. Already check what you say . 
Please correct me if I am wrong. this is about variable products with variable price , right? My problem is that I have a variable product with a fix price. And I need to show the price with and without . any suggestion? Thank you !

**Comment by mikejolley** [comment]
The inline comment explains why it's not possible at variable level.
