### ISSUE TITLE
Fatal error: Call to a member function has_status() on boolean in woocommerce/templates/order/order-details.php on line 25

### ISSUE THREAD

**Issue by Manojmahajan119** [woocommerce/woocommerce#16049]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by Manojmahajan119** [comment]
Fatal error: Call to a member function has_status() on boolean in woocommerce/templates/order/order-details.php on line 25 
i have issue

**Comment by mikejolley** [comment]
This means the order does not exist and `$order = wc_get_order( $order_id );` is returning false. Are you trying to view an order which does not exist?

**Comment by Manojmahajan119** [comment]
Hello mikejolley 
my issue is not resolved  Fatal error: Call to a member function has_status() on boolean in woocommerce order.php skpe id :harry.tanvar1 plz update on skype .
Thanks & Regards
Manoj

**Comment by mikejolley** [comment]
Why did you ignore my question?

**Comment by mikejolley** [comment]
@Manojmahajan119 Basically, that could happen if you're viewing an order ID which does not exist, somehow. So what are you viewing, and can you post your status report as requested.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16068
