### ISSUE TITLE
Product Gallery

### ISSUE THREAD

**Issue by JackHowarth** [woocommerce/woocommerce#16048]
Hi,

I've been trying to update our website so it is more user friendly and when I've been adding more images to the product gallery they seem to be showing like this?

![image](https://user-images.githubusercontent.com/30045852/28017037-0a68ca1e-656f-11e7-842e-1ca480339402.png)

Does anyone know how I can fix them and make sure the spacing is regular rather than apart like this and on different lines?

**Comment by mikejolley** [comment]
The styling of the columns/gallery is down to your theme. Thats not the way the default core gallery looks - we have a slider as of 3.0.

**Comment by JackHowarth** [comment]
Hi Mike,

Have you got any idea how I can chance the theme? Just for the product gallery placement? I’d ask the person who did our website for us however he doesn’t seem to be available anymore.

Thank You
Jack Howarth

**Comment by mikejolley** [comment]
You cannot just change the theme of the gallery, you'd need to add new CSS to your current theme. 

Maybe you could get a test install setup and test some others. Storefront is a good free one..but depends on your needs.
