### ISSUE TITLE
woocommerce price wont show

### ISSUE THREAD

**Issue by sporkyzz** [woocommerce/woocommerce#16040]
As the title says, woocommerce price wont show...

**Comment by mikejolley** [comment]
This issue lacks the details requested on the new issue form, and is thus invalid. 

https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md

**Comment by sporkyzz** [comment]
It randomly works now, i have 1 more question how the hell do u get this slider /product? https://i.imgur.com/bZuhrry.png

**Comment by mikejolley** [comment]
Thats custom, thats not from WC.

**Comment by sporkyzz** [comment]
Darn :(

**Comment by sporkyzz** [comment]
http://mysticgn.com/csgo-boosting/ why is this happening?

**Comment by sporkyzz** [comment]
im getting &quot;fonts&quot;

**Comment by sporkyzz** [comment]
`,&quot;fonts&quot;:{`

**Comment by mikejolley** [comment]
I don't know where you're looking.

**Comment by sporkyzz** [comment]
https://i.imgur.com/3md6dZ7.png

**Comment by sporkyzz** [comment]
and when i try edit i get 404 error

**Comment by mikejolley** [comment]
Are you using a page builder? Edit the content and remove it with the 'text' view.
