### ISSUE TITLE
Gallery First Image Viewport Height

### ISSUE THREAD

**Issue by leanda** [woocommerce/woocommerce#16055]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce
- [ x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Load single product page
2. Using .woocommerce-product-gallery__image { min-height: auto !important; } to get variable height images.
3.

## Expected behavior and actual behavior

When gallery on the product page loads the first image is collapsed until another thumbnail is clicked or the browser window is resized. 

I've temporarily solved the issue by installing a lazy load plugin which works out the viewport height before loading the first image.

![screen shot 2017-07-10 04 49 16 pm](https://user-images.githubusercontent.com/2487875/28028237-cf732dbc-6593-11e7-925d-2b544b1a56a6.png)

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://www.k-type.com
Site URL: http://www.k-type.com
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (8) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.14
BackUpWordPress: by Human Made Limited – 3.6.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Rocket Lazy Load: by WP Media – 1.1.1
Simple 301 Redirects: by Scott Nellé – 1.07
WooCommerce: by Automattic – 3.1.0
Wordfence Security: by Wordfence – 6.3.12

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /fonts/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: K-Type
Version: 1.0.0
Author URL: http://www.leandaryan.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: k-type/woocommerce/single-product.php
`
```
</details>

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
This is fixed here for the next release. Let us know if it does not work for you. https://github.com/woocommerce/woocommerce/pull/15893

**Comment by leanda** [comment]
Thanks! That works.
