### ISSUE TITLE
New CSV Importer Schema: Incorrect attributes column names documented

### ISSUE THREAD

**Issue by webspecnick** [woocommerce/woocommerce#16051]
The documentation for importing attributes on the [new CSV importer schema](https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema) is incorrect. The columns just list "attributes" as their header, but the importer is looking for more defined names such as "attributes:name0"

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Create a csv such as the following, which is valid according to the new schema.
```
type,sku,name,attributes,attributes,attributes,attributes,default_attributes,attributes,attributes,attributes,attributes,default_attributes
"simple","i-am-a-sku","Large Pizza","Color","Blue, Red",1,1,"Red","Hue","Cyan, Magenta",1,1,"Cyan"
```
2. Upload the csv to the new importer
3. The attribute fields default to Do Not Import
4. Cancel out of the importer without importing products
5. Upload this csv to the new importer
```
type,sku,name,attributes:name0,attributes:value0,attributes:taxonomy0,attributes:visible0,attributes:default1,attributes:name1,attributes:value1,attributes:taxonomy1,attributes:visible1,attributes:default1
"simple","i-am-a-sku","Large Pizza","Color","Blue, Red",1,1,"Red","Hue","Cyan, Magenta",1,1,"Cyan"
```
6. The attributes now map to the correct fields
7. Importing the products with the second one correctly creates the attributes and products

## Expected behavior and actual behavior

When I follow those steps, I see...
When using "attributes" as the column names the importer doesn't recognize them.

I was expecting...
The importer to recognize the columns, as outlined in the schema.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
@webspecnick In the schema, look at the column headings. You want "Name in CSV", not the first column.

**Comment by Manojmahajan119** [comment]
Thx

**Comment by webspecnick** [comment]
@mikejolley Oh, I didn't realize that the second column is the column name. Myself and a client were confused by the docs. Could we change the reference table to be more in line with the [old importer](https://docs.woocommerce.com/document/product-csv-import-suite-column-header-reference/)?
Here's what I propose:
1. Move the "Name In CSV" to be the first column
1. Rename Name in CSV to "CSV Column Name"
1. Wrap the "Name in the CSV" in backticks
1. List the "prop" column second
1. Change prop to "Description" or "Product Properties"
1. Remove backtick formatting from prop

**Comment by mikejolley** [comment]
We'll update the wiki to make it clearer, thanks.
