### ISSUE TITLE
Backorders Issue after Failed Payments

### ISSUE THREAD

**Issue by huwrowlands** [woocommerce/woocommerce#16069]
## Came across a possible bug where backorders are not allowed but can still be ordered. 

Customer A orders several items but payment has failed for whatever reason their end and doesn't retry. 
Customer B comes along and orders items deeming them out of stock.
Customer A returns and finally completes payment for the now out of stock items.
Thus creating backorders which should technically not be allowed.

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

I was expecting Customer A to be notified that they cannot order any out of stock items once returning back to complete payment.

## Environment

<details>
`
### WordPress Environment ###

Home URL: http://visibleimage.co.uk
Site URL: http://visibleimage.co.uk
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (23) ###

ManageWP - Worker: by ManageWP – 4.2.19
Advanced Custom Fields: by Elliot Condon – 4.4.11
All In One SEO Pack: by Michael Torbert – 2.3.13.2
Anti-spam: by webvitaly – 4.3
BackupBuddy: by iThemes – 8.0.0.3
Blogger Importer: by wordpressdotorg – 0.9
Categories Images: by Muhammad Said El Zahlan – 2.5.3
Contact Form 7: by Takayuki Miyoshi – 4.8
Content Aware Sidebars: by Joachim Jensen – 3.6.1
Flat Rate per State/Country/Region for WooCommerce: by Webdados – 2.4.8.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Pinterest "Pin It" Button Lite: by Phil Derksen – 2.1.0.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SG Optimizer: by SiteGround – 3.3.1
Toolset Types: by OnTheGoSystems – 2.2.13
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.0
WooCommerce - All in One SEO Pack: by Visser Labs – 1.3.4
WooCommerce Currency Converter: by WooCommerce – 1.6.5
WooCommerce SagePay Form and SagePay Direct Gateway: by Andrew Benbow – 3.7.6 – 3.9.0 is available
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.3.1 – 3.3.2 is available
WooCommerce Role Based Methods: by WPBackOffice – 2.0.9 – 2.1.2 is available
WooCommerce - Table Rates: by WP Ronin – 1.6.0
WooCommerce: by Automattic – 3.1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /your-basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: upBootWP
Version: 0.1
Author URL: http://upplex.de
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: upBootstrap3WP-master/woocommerce/archive-product.php
upBootstrap3WP-master/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.1.0
upBootstrap3WP-master/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.1.0
upBootstrap3WP-master/woocommerce/content-product_cat.php
upBootstrap3WP-master/woocommerce/content-single-product.php
upBootstrap3WP-master/woocommerce/loop/add-to-cart.php
upBootstrap3WP-master/woocommerce/loop/loop-end.php
upBootstrap3WP-master/woocommerce/loop/loop-start.php
upBootstrap3WP-master/woocommerce/loop/price.php
upBootstrap3WP-master/woocommerce/single-product/add-to-cart/simple.php
upBootstrap3WP-master/woocommerce/single-product/price.php

Outdated Templates: ❌Learn how to update
`
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
What gateway and what order status after failed payment?

**Comment by huwrowlands** [comment]
It was via PayPal. Actually, I cannot see if there was a failed payment. It does not state this on the order screen.

**Comment by mikejolley** [comment]
The order screen has 'notes' on the right side. Grab those.

**Comment by mikejolley** [comment]
@huwrowlands Find them? A screenshot would be welcome.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16122

**Comment by huwrowlands** [comment]
Thanks. Hopefully this will be resolved and updated soon.
