### ISSUE TITLE
Improve Orders Screen on Mobile Devices

### ISSUE THREAD

**Issue by f3bruary** [woocommerce/woocommerce#16061]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. View orders on a mobile device

## Expected behavior and actual behavior

When I follow those steps, I see... a page that is not optimized for small screens

I was expecting...a page that is optimized for small screens

The text is hard to read, the formatting is misaligned and the buttons are hard to press.

Running WC3.1 and WP4.7.5

Screenshot:
![image](https://user-images.githubusercontent.com/5641933/28039536-fc4ecc54-65c2-11e7-984e-c7f650f0e56d.png)

**Comment by WPprodigy** [comment]
What version of WC? Something (theme or plugin) is likely causing a conflict. Because this is what it looks like for me: http://cld.wthms.co/kxfYiu & http://cld.wthms.co/wcx9A1

**Comment by f3bruary** [comment]
oh wow

I guess it might be caused by a plugin then. I have several that add actions like printing invoices/package slips. I'll try to disable those to see if one of them is responsible.

**Comment by f3bruary** [comment]
Found the plugin responsible. If anyone cares, it's the WooCommerce POS plugin (codecanyon version).
