### ISSUE TITLE
Possible Bug With Time Query Handling

### ISSUE THREAD

**Issue by treyrich** [woocommerce/woocommerce#16064]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x ] The issue still exists against the latest `master` branch of WooCommerce
- [ x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Call `wc_get_orders` with a datetime argument (i.e. `"date_before" => "2017-01-01 12:00:00"`)

## Expected behavior and actual behavior

When I follow those steps, I see...
The date that ultimately gets queried is the UTC date.

I was expecting...
The date that gets queried to be in the site's timezone.

## Isolating the problem

- [ x ] This bug happens with only WooCommerce plugin active
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x ] I can reproduce this bug consistently

It's possible that this isn't a bug, but I wanted to double check because this doesn't seem consistent with the way that dates were handled in the past. Before I issue a PR I want to check what the intended behavior of the date queries is, should these default to UTC or to the site's timezone?

**Comment by WPprodigy** [comment]
It depends on what is passed: https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#date. Timestamps are supposed to be UTC, while standard dates are in the site's timezone.

It doesn't support standard dates with the hour/minutes/seconds though. You'll see why here: https://github.com/woocommerce/woocommerce/blob/7046b480a0d37bc553b70deb8fb35f3b521808e2/includes/wc-order-functions.php#L52

**Comment by treyrich** [comment]
But the standard dates with hour/minute/second is supported through the `wc_string_to_datetime` call here: https://github.com/woocommerce/woocommerce/blob/7046b480a0d37bc553b70deb8fb35f3b521808e2/includes/wc-order-functions.php#L51 right?

So then I'd say this is confirmed a bug if the intention is for a date string to be treated as having the site's time zone.

**Comment by WPprodigy** [comment]
Yea, looks like h/m/s is supported in `wc_string_to_datetime()`.

But the `$datetime->date( 'Y-m-d' )` line here would just ignore I think: https://github.com/woocommerce/woocommerce/blob/7046b480a0d37bc553b70deb8fb35f3b521808e2/includes/wc-order-functions.php#L52

**Comment by treyrich** [comment]
Yes, but this code `$datetime->date( 'Y-m-d' )` only runs if a time was not provided, if a time is provided it runs `$datetime->getOffsetTimestamp()` which is where I believe the big lies. I believe that call should probably be `$datetime->getTimestamp()` though I haven't dug into it enough to know for sure. I just know that when running queries it is resulting in unexpected results currently.

**Comment by WPprodigy** [comment]
That's only relevant when using the deprecated date_before and date_after args :). Try the new ones and see if the problem still exists.

**Comment by treyrich** [comment]
Fair enough, if it's not a concern then I won't bother with a PR.
