### ISSUE TITLE
Cart.JS 'wc_update_cart' event does not trigger 'woocommerce_update_cart_action_cart_updated' filter

### ISSUE THREAD

**Issue by reescott** [woocommerce/woocommerce#16079]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add custom hidden field to the cart.php form, and hook into the `woocommerce_update_cart_action_cart_updated` filter in attempt to save this to WC Session.
2. Trigger the `wc_update_cart` event via `$(document).trigger('wc_update_cart')` after value change in hidden field.
3. `woocommerce_update_cart_action_cart_updated` filter will not fire, due to absence of `update_cart` hidden field in the update_cart ajax function. 
https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/cart.js#L326
This `update_cart` field is added in the quantity_update function, but this cannot be triggered, it only fires on click of the update function 
https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/cart.js#L503

## Expected behavior and actual behavior

I expected to be able to trigger the `wc_update_cart` event on document and hook into the filter on the backend, however I am forced to 'click' on the update button in order to trigger the quantity_update function instead. This seems fragile, and not very long term. 

My proposal is to add the `update_cart` hidden field to the update_cart function to allow the filter to fire here:
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L543

If this sounds like a good solution, I am happy to submit a pull request.

**Comment by mikejolley** [comment]
If it's not a cart/quantity update, and this is entirely custom, why do you need to use the WC endpoint and hook?

**Comment by reescott** [comment]
@mikejolley We are also using the `woocommerce_update_cart_action_cart_updated` hook to update cart line item properties such as price, because it has the 'refresh fragments' feature. Unfortunately, because of the way that cart.js is written, we are having to 'click' on the update button to fire that update ajax call. I think making the ‘wc_update_cart’ event trigger the hook `woocommerce_update_cart_action_cart_updated` would make the cart page more flexible.

**Comment by mikejolley** [comment]
Ok makes sense.

> My proposal is to add the update_cart hidden field to the update_cart function to allow the filter to fire here:
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L543
> If this sounds like a good solution, I am happy to submit a pull request.

I'll close this and review the PR when it comes in - I think it sounds fine :)
