### ISSUE TITLE
Keeps adding products to order after checkout complete

### ISSUE THREAD

**Issue by baselbers** [woocommerce/woocommerce#16074]
On my dev machine when I add 2 products to cart and checkout order, wc is adding more products on order creation. Very strange behaviour. It's a clean install with storefront theme.

![image](https://user-images.githubusercontent.com/10761673/28072707-1f8cb69a-6654-11e7-926e-ce15f49de1ed.png)

- I've deleted all transients.
- Cleared broswer cache
- Did a redis-cli flushall object cache
- Did a checkout with different account
- Switched theme

Still getting products added to the order.

![image](https://user-images.githubusercontent.com/10761673/28072767-4a4e1c20-6654-11e7-889c-268f492e0e32.png)

It seems that one product has VAT class, while the same product hasn't.

`
### WordPress Environment ###

Home URL: http://wp.box
Site URL: http://wp.box
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.10
PHP Version: 7.1.5-1+deb.sury.org~trusty+1
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

SMTP Mailer: by naa986 – 1.0.3
WooCommerce PDF Invoices Premium: by Bas Elbers – 1.6.2
WooCommerce PDF Invoices: by Bas Elbers – 2.9.3
WooCommerce: by Automattic – 3.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Take a peek in the woocommerce_sessions table and see what is there/in the cart. We've not had luck replicating this one in the past.

**Comment by WPprodigy** [comment]
Also, have you done any database/order imports in the past? Double check to make sure there aren't any test/staging sites connected to your live database as well.

**Comment by mikejolley** [comment]
@baselbers any feedback?

**Comment by baselbers** [comment]
Thanks for your quick replies.
I've managed to resolve the problem by just removing all products and adding them again with the import.
