### ISSUE TITLE
Error calling Legacy API V3 Products endpoint

### ISSUE THREAD

**Issue by DEARMarvin** [woocommerce/woocommerce#16072]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
Calling /wc-api/v3/products (+ some optional parameters)
2.
instead of valid json the following is returned on one specific store of our client, it works fine on our test store. Client claims this is standard installation and we have no access to verify it.
3.
Error received from WooCommerce API:
<br />
<b>Fatal error</b>: Uncaught Error: Call to a member function get_name() on boolean in /srv/users/serverpilot/apps/1800doorbellproduction/public/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php:1151
Stack trace:
#0 /srv/users/serverpilot/apps/1800doorbellproduction/public/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php(214): WC_API_Products-&gt;get_product_data(false)
#1 /srv/users/serverpilot/apps/1800doorbellproduction/public/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php(166): WC_API_Products-&gt;get_product(2689, NULL)
#2 /srv/users/serverpilot/apps/1800doorbellproduction/public/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-server.php(372): WC_API_Products-&gt;get_products(NULL, NULL, Array, '1')
#3 /srv/users/serverpilot/apps/1800doorbellproduction/public/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-server.php(223): WC_API_Server-&gt;dispatch()
#4 /srv/users/serverpilot/apps/1800doorbellproduction/p in <b>/srv/users/serverpilot/apps/1800doorbellproduction/public/wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-products.php</b> on line <b>1151</b><br />

## Expected behavior and actual behavior

Expected response should be a valid json product details data.

## Environment

This client's store: https://www.1800doorbell.com
WooCommerce version 3.1.0

## Isolating the problem

I can reproduce this bug consistently only on this store.

**Comment by WPprodigy** [comment]
Fataling here at the start of getting product data: https://github.com/woocommerce/woocommerce/blob/master/includes/api/legacy/v3/class-wc-api-products.php#L1151

Seems to be running into this line as well: https://github.com/woocommerce/woocommerce/blob/master/includes/api/legacy/v3/class-wc-api-products.php#L214

Sounds like you don't have access to the site to debug this though? Looks like a simple product has a parent ID, and it's causing problems (perhaps it is trashed).
