### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by lisssina** [woocommerce/woocommerce#16073]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.When I try to send a note to the customer, the mail does not start
2.The order will no longer work, and if it changes its status, it will no longer send mail
3.

## Expected behavior and actual behavior

When I follow those steps, I see the order will no longer work, and if it changes its status, it will no longer send mail

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
Are you sure any emails are sending? Use this plugin to log outgoing emails: https://wordpress.org/plugins/email-log/

Could just be an issue with your web/email server.

**Comment by lisssina** [comment]
The order change status mails are sent. Only when you try to send a note to the customer freezes the browser and the order in question is compromised. Any other action on that order does not send mail

**Comment by WPprodigy** [comment]
I couldn't replicate. Installed email log and sent a customer note and got email. Then I changed order status and still got emails.

Typically issues like this may be caused by either a conflict with your theme or with another plugin. Try temporarily switching back to the WordPress Twenty Seventeen Theme, or [Storefront](http://www.woothemes.com/storefront/), and disable all plugins except for WooCommerce. Then test again. If that resolves the issue, then slowly re-enable features until you find the one that's causing the conflict.

**Comment by lisssina** [comment]
I tried to follow your suggestions but I did not solve the problem. In detail the error: when in an order I try to add a "note to the client", the browser freezes and I can not even press "update" the order; If I stop the browser, the note I tried to add appears in the note list with a blue colour, but no mails start (checked with the plug in "Email Log"); after this action, the order is compromised and any action on the order does not generate mail. Instead, if I add a "private note" it works perfectly well. It works perfectly even though I changed my order and started the mail regularly.

**Comment by lisssina** [comment]
![cattura](https://user-images.githubusercontent.com/30078613/28109384-33aeca46-66ef-11e7-85f8-fe94a0ef6f09.PNG)
The BROWSER resumes this way

**Comment by mikejolley** [comment]
Thats definitely a conflict or non-wc error killing the script. Follow the instructions on https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x

> Typically issues like this may be caused by either a conflict with your theme or with another plugin. Try temporarily switching back to the WordPress Twenty Seventeen Theme, or Storefront, and disable all plugins except for WooCommerce. Then test again. If that resolves the issue, then slowly re-enable features until you find the one that's causing the conflict.

Important you do this for all extensions and plugins. Feel free to reply if you find an error and need help with tackling it.

Thanks
