### ISSUE TITLE
page arg not respected in wc_get_orders

### ISSUE THREAD

**Issue by treyrich** [woocommerce/woocommerce#16080]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x ] The issue still exists against the latest `master` branch of WooCommerce
- [ x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Call `wc_get_orders` with a `page` arg specified.

## Expected behavior and actual behavior

When I follow those steps, I see...
The first page of results is returned regardless of what number is passed as the page arg

I was expecting...
Each page to be returned as requested.

## Isolating the problem

- [ x ] This bug happens with only WooCommerce plugin active
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x ] I can reproduce this bug consistently

The issue stems from the fact that the `page` arg is not respected because it's never converted to `paged` before being passed to `WP_Query` here: https://github.com/woocommerce/woocommerce/blob/7046b480a0d37bc553b70deb8fb35f3b521808e2/includes/data-stores/class-wc-order-data-store-cpt.php#L692

The equivalent logic for Products functions correctly because of this line here: https://github.com/woocommerce/woocommerce/blob/7046b480a0d37bc553b70deb8fb35f3b521808e2/includes/data-stores/class-wc-product-data-store-cpt.php#L1253

I'm happy to put together a PR if needed, but I'm not certain what the most appropriate location for converting the args is (as is evidenced by my failed PR #16063).

**Comment by mikejolley** [comment]
`page` is not used by WP_Query, so we convert `page` to `paged`. This is broken in 3.1 but fixed in 3.1.1

**Comment by treyrich** [comment]
Exactly. That sounds great, if it's already fixed then this can be closed!
