### ISSUE TITLE
Add new Tool in System Status Area: Regenerate Download Permissions

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#16081]
## Scenario

User buys a downloadable/virtual product, which grants access to the following files:

* File1.pdf
* File2.pdf
* File3.pdf

Those files are then available in their account. This part is working fine. However, if there's an update to one of the files (like a revised PDF, updated ebook, new software version, etc.) then changing the downloads doesn't update what the user would see. While you'd want all of your buyers to have `File2b.pdf`, deleting `File2.pdf` and adding `File2b.pff` in the product doesn't change anything.

You _can_ go into each order for that product and then regenerate download permissions, but once you have more than a handful of orders this can be a nightmare.

## Proposed Solution

If we added a new tool in either the Product's Downloads area or the **System Status > Tools** area to Regenerate Download Permissions for all orders, then this would solve that problem by updating what is available for the user in their Account, so now after the change the user would see:

* File1.pdf
* File2b.pdf
* File3.pdf

-----

Related on Ideas board: http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/10122462-add-regenerate-download-permissions-button

**Comment by mikejolley** [comment]
If you delete and add, old orders are not updated. This was a huge bottleneck and moved out of core. This tool already exists: https://github.com/woocommerce/grant-download-permissions-for-past-woocommerce-orders

If you edit a download, rather than re-add it, old orders will have their links updated.
