### ISSUE TITLE
woocommerce update wiped out hours of another plugin custom product data

### ISSUE THREAD

**Issue by peter443** [woocommerce/woocommerce#16089]
OMG, i just found after updating to woocommerce Version: 3.1.1 it wipe out my other plugin called "Custom product tabs for Woocommerce" , so basically the update made my other plugin default to NOTHING  ...so now i am stuck to find to pick...the Woocommerce update each time and/or to restore at least 100 hours or custom product tabs of data each time, afterwards, SHIT, I need HELP to find a solution to have both....can someone help ??

**Comment by mikejolley** [comment]
@peter443 Upgrade from what version to what version?

What plugin handles the tabs?

Did you do regular update, or 'delete' via the plugins page first?

**Comment by mikejolley** [comment]
I found that plugin; it has code to deactivate itself when WC is not installed. So it may just be deactivated since it won't be active during the update. Check that.

The 3.1.1 update itself was very small and updates in general do not delete any data.

**Comment by peter443** [comment]
The plugin is called "Custom product tabs for Woocommerce", I just update
your plugin, then this plugin listed above was Wipeout and reset to to
restart, so I when back over and over to see the differences, it was the
plugin update

On Jul 12, 2017 4:53 AM, "Mike Jolley" <notifications@github.com> wrote:

@peter443 <https://github.com/peter443> Upgrade from what version to what
version?

What plugin handles the tabs?

Did you do regular update, or 'delete' via the plugins page first?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/woocommerce/woocommerce/issues/16089#issuecomment-314699217>,
or mute the thread

**Comment by mikejolley** [comment]
Well there is no mechanism to selectively destroy data after updates. Still waiting on answers to my other points.

**Comment by peter443** [comment]
My developer designer says, it was hosting company that takes some to
update the website, then everything was updatded and the data was refound,
apparently it takes the hosting company one full day to complete
