### ISSUE TITLE
product image problems

### ISSUE THREAD

**Issue by nerdygirlsuccess** [woocommerce/woocommerce#16082]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce
- [X ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Click a product in the store
2.Click on a product image
3.

## Expected behavior and actual behavior

When I follow those steps, I see...
I select a product in the store and then click on one of the product images. I am redirected to the image url/page rather than seeing the pop up image gallery.

I was expecting...
Expected behavior is that a gallery of the product images would pull up and viewer is able to scroll through the images and then x out of the gallery. All without leaving the product page.
## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
Please follow all of the steps in the "Isolating the problem" section. This is likely a theme or plugin conflict issue.

Temporarily switch back to the WordPress Twenty Seventeen Theme, or [Storefront](http://www.woothemes.com/storefront/), and disable all plugins except for WooCommerce. Then test again. If that resolves the issue, then slowly re-enable features until you find the one that's causing the conflict.

**Comment by mikejolley** [comment]
^ that. Also without the status report or a link to the site it's not possible for us to even "see" the problem. This issue is invalid.
