### ISSUE TITLE
shop_order

### ISSUE THREAD

**Issue by aitnom** [woocommerce/woocommerce#16095]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Upgraded to most recent version of WooCommerce
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I received a Google Alert this morning and found that a "shop_order" page on my site with the timestamp of an order is showing publicly online. For example the page title is similar to "Order – July 3, 2017 @ 01:13 AM". No order information is on the page but Google appears to be indexing this pages. Is there a way to prevent this?

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by WPprodigy** [comment]
What does the permalink look like? There's very likely another plugin causing a conflict. So please follow all of the above steps in the "Isolating the problem" section.

If the page still exists when only WC active, then report back here. This is very likely not a WC bug though.
