### ISSUE TITLE
product images [with links]

### ISSUE THREAD

**Issue by nerdygirlsuccess** [woocommerce/woocommerce#16097]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Visit a product in the WooCommerce store on my site (https://nerdygirlsuccess.com/product/2017-2018-nerdy-girl-planner/)
2.Click on any of the image files, you are redirected to the image file url rather than having the pop up gallery. (https://nerdygirlsuccess.com/wp-content/uploads/2017/07/amazing-square.png)
3.

## Expected behavior and actual behavior

When I follow those steps, I see...
I see the image file url page
I was expecting...
to have the gallery of product images pop up and be able to scroll through the gallery.
## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://nerdygirlsuccess.com
Site URL: https://nerdygirlsuccess.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_15xfpcgxj6_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Redux Framework: by Team Redux – 3.6.5
AutoChimp: by Wanderer LLC Dev Team – 2.15
Anti-Spam by CleanTalk: by СleanTalk  – 5.69
Contact Form Maker: by WebDorado – 1.8.43
Display Posts Shortcode: by Bill Erickson – 2.8.0
Easy Author Image: by Jesse Lawson – 1.5
Easy Google Fonts: by Titanium Themes – 1.4.3
Feed Them Social (Facebook, Instagram, Twitter, etc): by SlickRemix – 2.2.5
Google XML Sitemap for Mobile: by Amit Agarwal – 1.6.1
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Juicer: by Ryan MacInnes – 1.8
Mailchimp Forms by Optin Cat: by Fatcat Apps – 2.0.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Search Engine Visibility: by GoDaddy – 0.5
Simple Social Icons: by Nathan Rice – 2.0.1
Page Builder by SiteOrigin: by SiteOrigin – 2.5.8
SiteOrigin Widgets Bundle: by SiteOrigin – 1.9.3
Super Simple Google Analytics: by bitacre – 1.7.2
USPS (BASIC) WooCommerce Shipping: by XAdapter – 1.1.10
WooCommerce: by Automattic – 3.1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #350 - /shop/
Cart: #351 - /cart/
Checkout: #352 - /checkout/
My account: #353 - /my-account/

### Theme ###

Name: FlatOn Pro
Version: 1.6.1
Author URL: http://www.webulousthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

when I do the default WordPress theme, the gallery does not act as it has in the past. It does not initiate a popup window of the images. instead as you click on an image it shows it in the display.

I have deactivated/re-activated plugins and the problem persists.

**Comment by WPprodigy** [comment]
Same as https://github.com/woocommerce/woocommerce/issues/16082...

> when I do the default WordPress theme, the gallery does not act as it has in the past. It does not initiate a popup window of the images. instead as you click on an image it shows it in the display.

This is what should happen. Here is a video: http://cld.wthms.co/jSQaF

**Comment by nerdygirlsuccess** [comment]
That is not what happens in my theme.

Click the link to a product in my store
https://nerdygirlsuccess.com/product/2017-2018-nerdy-girl-planner/
And then click on an item and you are redirected to the actual image file
url
https://nerdygirlsuccess.com/wp-content/uploads/2017/07/amazing-square.png

I need the fix please


Be the Nerd,

*Christina Meade*
Nerd Girl & Career Builder
Nerdy Girl Success ~ Shaping Tomorrow's Leaders
954-Nerd-Grl
Website <https://nerdygirlsuccess.com/> | Facebook
<http://www.facebook.com/NerdyGirlSuccess> | Twitter
<https://www.twitter.com/NerdGirlSuccess> | Instagram
<https://www.instagram.com/NerdyGirlSuccess>

**Comment by WPprodigy** [comment]
Right, I see that on your site. That is because of your theme. That does not happen when using a default WordPress theme, correct? What I posted a video of happens for you as well on a default theme?

You need to contact the theme authors. There is nothing we can do about issues in your theme.
