### ISSUE TITLE
Explode error warning when creating a coupon

### ISSUE THREAD

**Issue by maurisrx** [woocommerce/woocommerce#16105]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a new coupon as usual with only "general" options filled out.

## Expected behavior and actual behavior

When I follow that step, I see these warnings with `WP_DEBUG` and `WP_DEBUG_DISPLAY` set to true:

```
Warning: explode() expects parameter 2 to be string, array given in D:\Dropbox\xampp\htdocs\wordpress\wp-content\plugins\woocommerce\includes\data-stores\class-wc-coupon-data-store-cpt.php on line 107

Warning: explode() expects parameter 2 to be string, array given in D:\Dropbox\xampp\htdocs\wordpress\wp-content\plugins\woocommerce\includes\data-stores\class-wc-coupon-data-store-cpt.php on line 108
```

The problem seems to be the `save_post` hooked function saves the `product_ids` and `excluded_product_ids` as array. And in the mentioned file stated in error message, it uses `explode()` to generate the result.

Or is it intended since the keys' value were previously saved as csv before WC 3.0? Should we make a helper function such as `maybe_explode()` to prevent the errors?

## Environment

<details>
### WordPress Environment ###

Home URL: http://localhost/wordpress
Site URL: http://localhost/wordpress
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/7.0.13
PHP Version: 7.0.13
PHP Post Max Size: 20 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

Debug Bar Actions and Filters Addon: by Subharanjan – 1.5.2
Debug Bar: by wordpressdotorg – 0.8.4
Debug Objects: by Frank Bültge – 2.4.1
Genesis Connect for WooCommerce: by StudioPress – 0.9.8
WooCommerce: by Automattic – 3.2.0-dev
WP Admin Keyboard Shortcut: by WP House – 0.1
WP Crontrol: by John Blackbourn & contributors – 1.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #104 - /shop/
Cart: #105 - /cart/
Checkout: #106 - /checkout/
My account: #107 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by maurisrx** [comment]
The issue seems resolved in fresh install. Sorry for the confusion.

**Comment by KouroshMoradyan** [comment]
I had the same problem and could solve it by just removing unnecessary lines in my code. I think this error occur in situations where a coupon is being created and you want some of the coupon fields to be its default value but try to set their default values in code where there is no need to express that by code. just ignore it.
