### ISSUE TITLE
WebHook verification doesn't match - PHP

### ISSUE THREAD

**Issue by LorenzoRogai** [woocommerce/woocommerce#16106]
Hi,

We are calculating the raw json body we receive on the webhook call with the following code:

$secret = "cs_...";

$rawbody = file_get_contents('php://input');

$calculated_hmac = base64_encode(hash_hmac('sha256', $rawbody, $secret, true));

But the $calculated_hmac never matches the signature inside X_WC_WEBHOOK_SIGNATURE

Thank you

**Comment by WPprodigy** [comment]
The `$secret` should be the Webhook Secret, not a Consumer Secret Key. So double check that.

Otherwise, I guess somehow `$http_args['body']` isn't the same as your `$rawbody` somehow.
