### ISSUE TITLE
After update woocommerce 3.1.1 Failed to load resource: the server responded with a status of 500 

### ISSUE THREAD

**Issue by jeffreytanuwidjaja** [woocommerce/woocommerce#16102]
i just update woocommerce version 3.1.1 then i got blank white page and in console says that

Failed to load resource: the server responded with a status of 500 ()

**Comment by jeffreytanuwidjaja** [comment]
conflict with another plugin

**Comment by ThomasNucleus** [comment]
@jeffreytanuwidjaja which plugin was it?
