### ISSUE TITLE
Admin variation sorting/creation is backwards?

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#16117]
For a variable product, you can control the order each attribute shows up on the product page via drag and drop. You can also control the order each terms shows up in the dropdown by sorting them by menu_order and drag/drop as well.

Here are my attributes: http://cld.wthms.co/NvtNct
Here are the terms: http://cld.wthms.co/qCyp0
And the correct display on the product page: http://cld.wthms.co/67NOjF

The problem occurs when you have it automatically create all variations for you. With the above product, you end up with this: http://cld.wthms.co/fpR0tu.

The variation IDs show that Blue-Small, Blue-M, and Blue-L were created last, but it would make sense to do those first I think? Seems to be parsing right to left. This current behavior makes the end-result hard to predict for a store owner that would like these to be in a very particular order.

**Comment by mikejolley** [comment]
The variation order (menu order) has no affect on the frontend display.

**Comment by WPprodigy** [comment]
Right, sorry that was confusing. I mean the display order in the admin. Was just showing that is is the same everywhere else.

With this setup: http://cld.wthms.co/qCyp0
You would expect Blue-Small to be created first and on-top: http://cld.wthms.co/fpR0tu
