### ISSUE TITLE
Creating order via API too limiting

### ISSUE THREAD

**Issue by willfaulds** [woocommerce/woocommerce#16139]
Basically I believe the API should allow (perhaps limited to a higher tier of ACL) creation of orders for specific customers/users and needs a "ProcessAsCart" call or similar.

I am looking at developing a form of POS/Admin app that will allow orders to be created for regular customers but the API is currently too limiting (a customer_id cannot be set when creating an order). Neither can discounts, overridden prices etc. Some many of the properties are read-only that the API is almost useless for creating a fully functional app.

A "ProcessAsCart" call or similar for created orders would massively enhance the features of the api - allowing orders to have all processes/plugins that would fire when created via front-end applied to a targeted order via the API (one you've created via the API).

Workaround greatly appreciated.

**Comment by mikejolley** [comment]
> I am looking at developing a form of POS/Admin app that will allow orders to be created for regular customers but the API is currently too limiting (a customer_id cannot be set when creating an order). Neither can discounts, overridden prices etc. Some many of the properties are read-only that the API is almost useless for creating a fully functional app.

Customer ID can be set, it's not read only https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

You also have full control over prices for line items added to the order, see "Order - Line items properties". Taxes are read only because they get calculated for you once the order is saved.

True discounts/coupons won't be possible before https://github.com/woocommerce/woocommerce/issues/15499 Until then you can simply adjust the line item costs above.

"ProcessAsCart" would likely involve payments, something we don't want to tackle in the API at this point in time.

Thanks

**Comment by willfaulds** [comment]
I appreciate the prompt response.

It would be useful to see `customer_id` added to the "Create an order" example as my first reading of this was that it could not be passed.

However the "Order - Line items properties" says that `price` **is read-only**... This means I cannot override the price for an order based on a customer's userrole. Without something similar to "ProcessAsCart" or "RunCartPlugins" or "PassToHook"... I cannot utilise prebuilt plugins nor can I recreate many plugin's functionality using the API,

**Comment by mikejolley** [comment]
Price is the product price, but line items get subtotal + total rows which are editable.

**Comment by mikejolley** [comment]
This idea was moved to the roadmap for voting :) See https://trello.com/c/gpC7lYTv/115-creating-order-via-api-too-limiting

**Comment by willfaulds** [comment]
Thanks Mike,

I shall read through the way order data is stored as I would like to track sales based on product sale price. In this use case product price is dictated by user-role (direct, wholesale, etc.). Other than reporting I can see your solution will work - plugins currently available seem to be more robust and it is frustrating to not be able to utilise or recreate their functionality with the API.
