### ISSUE TITLE
Product Sub Categories Do Not Work After Update

### ISSUE THREAD

**Issue by mayphilc** [woocommerce/woocommerce#16134]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mayphilc** [comment]
`
### WordPress Environment ###

Home URL: http://www.herpsnverts.com
Site URL: http://www.herpsnverts.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (29) ###

Advanced Database Cleaner: by Younes JFR. – 2.0.0
bbPress Do Short Codes: by Pippin Williamson – 1.0.3
bbPress: by The bbPress Community – 2.5.12
BuddyPress Activity Plus: by WPMU DEV – 1.6.4
BuddyPress Edit Activity: by BuddyBoss – 1.0.8
BuddyPress Wall: by Meg@Info – 0.9.4
BuddyPress: by The BuddyPress Community – 2.8.2
Display Widgets: by displaywidget – 2.6.2.1
Dokan (Lite) - Multi-vendor Marketplace: by Tareq Hasan – 2.6.4
Envato Market: by Derek Herman – 1.0.0-RC2
Events Manager: by Marcus Sykes – 5.7.3
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.2
Members page only for logged in users: by Narendran TS – 1.4.1
myCRED: by Gabriel S Merovingi – 1.7.9
Slider Revolution: by ThemePunch – 5.4.1
RH BuddyPress Member Types: by Wpsoul – 1.0.1
RH Grandchild Custom: by Check docs – 1.0.3
Role Scoper: by Kevin Behrens – 1.4.4
User Role Editor: by Vladimir Garagulya – 4.35.1
User Switching: by John Blackbourn – 1.0.9
Wiki: by WPMU DEV – 1.2.5.2
WooCommerce: by Automattic – 3.1.1
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 5.0.2
WP Custom Widget area: by Kishor Khambu – 1.2.5
WP-DBManager: by Lester 'GaMerZ' Chan – 2.79
WP Smush: by WPMU DEV – 2.7.1
YITH WooCommerce Product Add-Ons: by YITHEMES – 1.0.6
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Rehub child theme - Revendor
Version: 6.9.1.5
Author URL: https://wpsoul.com/
Child Theme: ✔
Parent Theme Name: Rehub theme
Parent Theme Version: 6.9.5
Parent Theme Author URL: https://wpsoul.com/
WooCommerce Support: ✔

### Templates ###

Overrides: rehub/woocommerce/archive-product.php
rehub/woocommerce/cart/cross-sells.php
rehub/woocommerce/content-product.php
rehub/woocommerce/content-product_cat.php
rehub-vendor/woocommerce/emails/admin-new-order.php
rehub/woocommerce/global/wrapper-end.php
rehub/woocommerce/global/wrapper-start.php
rehub/woocommerce/loop/add-to-cart.php
rehub/woocommerce/loop/loop-end.php
rehub/woocommerce/loop/loop-start.php
rehub/woocommerce/loop/sale-flash.php
rehub/woocommerce/single-product/add-to-cart/external.php
rehub/woocommerce/single-product/meta.php
rehub/woocommerce/single-product/price.php
rehub/woocommerce/single-product/product-image.php
rehub/woocommerce/single-product/product-thumbnails.php
rehub/woocommerce/single-product/related.php
rehub/woocommerce/single-product/sale-flash.php
rehub/woocommerce/single-product/short-description.php
rehub/woocommerce/single-product/tabs/description.php
rehub/woocommerce/single-product/up-sells.php
rehub/woocommerce/single-product-reviews.php
rehub/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
You have no filled out the description of what is happening correctly, and the site you linked to is using dummy content. The links on your homepage are not even linking to your own site....they go to your theme authors site.

**Comment by mayphilc** [comment]
Yeah I uninstalled the entire site and started new with some dumby content.
The issue was retarded and I didn't have time to wait for someone to figure
it out
