### ISSUE TITLE
Mobile and tablet customers can't enter Phone or Email on Checkout page

### ISSUE THREAD

**Issue by bborden51** [woocommerce/woocommerce#16138]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Place MOBILE Order at https:palmfreesunwear.com
2. At Checkout page try to click on Phone or Email Box.
3. 

## Expected behavior and actual behavior

When I follow those steps, I see... AND I disable the code at the bottom of this post then I am not able to enter any data into the phone or email box.

I was expecting... customer to enter phone number and email address 

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://palmfreesunwear.com
Site URL: https://palmfreesunwear.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 1 GB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (11) ###

All In One SEO Pack: by Michael Torbert – 2.3.14
Force Plugin Updates Check: by Pippin Williamson – 1.0.1
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.1.1.1
Meta Slider: by Matcha Labs – 3.5.1
VarkTech Pricing Deals for WooCommerce: by Vark – 1.1.7.1
Simple Popup Plugin: by Garrett Grimm – 4.4
Tax Rate Upload: by Adam Bowen – 2.4.5
WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.6
WooCommerce: by Automattic – 3.1.1
WP Rocket: by WP Media – 2.10.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: ❌ Page not set

### Theme ###

Name: Virtue - Premium Child
Version: 1.0.1434301506
Author URL: 
Child Theme: ✔
Parent Theme Name: Virtue - Premium
Parent Theme Version: 4.2.3
Parent Theme Author URL: https://www.kadencethemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: virtue_premium/woocommerce/archive-product.php
virtue_premium/woocommerce/content-product.php
virtue_premium/woocommerce/content-product_cat.php
virtue_premium/woocommerce/content-single-product.php
virtue_premium/woocommerce/loop/loop-end.php
virtue_premium/woocommerce/loop/loop-start.php
virtue_premium/woocommerce/loop/rating.php
virtue_premium/woocommerce/loop/sale-flash.php
virtue_premium/product-searchform.php
virtue_premium/woocommerce/single-product/add-to-cart/external.php
virtue_premium/woocommerce/single-product/add-to-cart/grouped.php
virtue_premium/woocommerce/single-product/add-to-cart/simple.php
virtue_premium/woocommerce/single-product/add-to-cart/variable.php
virtue_premium/woocommerce/single-product/product-image.php
virtue_premium/woocommerce/single-product/product-thumbnails.php
virtue_premium/woocommerce/single-product/related.php
virtue_premium/woocommerce/single-product/sale-flash.php
virtue_premium/woocommerce/single-product/title.php
virtue_premium/woocommerce/single-product/up-sells.php
virtue_premium/woocommerce/single-product.php
virtue_premium/woocommerce/taxonomy-product_cat.php
virtue_premium/woocommerce/taxonomy-product_tag.php

`
</details>

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently

If I enter this CSS code then the mobile customers can enter phone and email.

/*I had to add this to allow mobile users to input email and phone at checkout-Who knows why???? Added code on 7-13-2017*/
.woocommerce-billing-fields {
    position: relative;
    z-index: 1;
}

I have disable all plugins except Woocommerce and the problems still exists.  Problem is the CSS code I entered is creating other problems at checkout.

I use the Kadence Virtue theme.

Thanks.

**Comment by mikejolley** [comment]
> This bug happens with a default WordPress theme active, or Storefront

I'm guessing you did not check this because it's specific to this theme. It needs to be reported to Kadence Themes. This theme does not use WooCommerce core CSS - it has it's own.

Times I've seen this before there have been 'overlaps' of content, so the front element blocks access to the fields behind. Usually this can be confirmed in desktop too by shrinking the browser but in this case it does not happen.
