### ISSUE TITLE
CSV Import fails to create variations correctly if attribute has space in title

### ISSUE THREAD

**Issue by glaing** [woocommerce/woocommerce#16141]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [-] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create and import a CSV with variable products based on a variety of attributes.
2. 
3. 

## Expected behavior and actual behavior

The attributes are created properly, but if the attribute name has a space in (not the actual attribute value, that seems ok) variations are not set correctly for them.

Image of the product edit screen - shows Defaults are set correctly and that the attributes have applied, but the values for the variations have not set correctly.
[https://staging.pxadventures.co.uk/wp-content/uploads/2017/07/Screenshot-2017-07-17-11.20.45-e1500286947620.png](https://staging.pxadventures.co.uk/wp-content/uploads/2017/07/Screenshot-2017-07-17-11.20.45-e1500286947620.png)

Image of the product edit screen - shows attributes are created successfully.
[https://staging.pxadventures.co.uk/wp-content/uploads/2017/07/Screenshot-2017-07-17-11.32.07-e1500287587660.png](https://staging.pxadventures.co.uk/wp-content/uploads/2017/07/Screenshot-2017-07-17-11.32.07-e1500287587660.png)

Image of the product page - pricing information is not showing correctly for the variation choices (but the price range and MSRP range are showing that the information has been set).
[https://staging.pxadventures.co.uk/wp-content/uploads/2017/07/Screenshot-2017-07-17-11.21.27-e1500287013277.png](https://staging.pxadventures.co.uk/wp-content/uploads/2017/07/Screenshot-2017-07-17-11.21.27-e1500287013277.png)

Product Page
[https://staging.pxadventures.co.uk/product/high5-energy-gel/](https://staging.pxadventures.co.uk/product/high5-energy-gel)

Looking through my site, I can see that the issue has only repeated itself on products with spaces in the attribute name (eg. Pack Type and Heart Rate Monitor) - all others have set as expected.

## Environment

<details>
`
### WordPress Environment ###

Home URL: https://staging.pxadventures.co.uk
Site URL: https://staging.pxadventures.co.uk
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.21
PHP Post Max Size: 512 MB
PHP Time Limit: 720
PHP Max Input Vars: 10000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: pxwp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

AffiliateWP: by AffiliateWP
LLC – 2.1.2

AffiliateWP - Affiliate Info: by Pippin Williamson and Andrew Munro – 1.0.3
Akismet Anti-Spam: by Automattic – 3.3.3
Contact Form 7: by Takayuki Miyoshi – 4.8
Download Attachments: by dFactory – 1.2.20
Facebook for WooCommerce: by Facebook – 1.4.1
Imagify: by WP Media – 1.6.7.1
Meta Slider: by Matcha Labs – 3.5.1
Postman SMTP: by Jason Hendriks – 1.7.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SearchWP Fuzzy Matches: by SearchWP
LLC – 1.4.3

SearchWP Live Ajax Search: by Jonathan Christopher – 1.2.0
SearchWP Related: by SearchWP
LLC – 1.0.2

SearchWP Term Highlight: by Jonathan Christopher – 2.1.5
SearchWP Term Synonyms: by SearchWP
LLC – 2.4.11

SearchWP: by SearchWP
LLC – 2.8.14

Page Builder by SiteOrigin: by SiteOrigin – 2.5.8
SiteOrigin Widgets Bundle: by SiteOrigin – 1.9.3
Storefront Hamburger Menu: by WooThemes – 1.2.1
Cookie Consent: by Catapult_Themes – 2.3.2
WooCommerce Accommodation Bookings: by WooCommerce – 1.0.9
WooCommerce Extended Coupon Features: by Soft79 – 2.5.1
WooCommerce Bookings: by Automattic – 1.10.3 – 1.10.4 is available
WooCommerce Composite Products: by SomewhereWarm – 3.10.1 – 3.11.0 is available
WooCommerce - Store Exporter: by Visser Labs – 1.9.1.1
WooCommerce Stripe Gateway: by WooCommerce – 3.2.2
WooCommerce AdWords Conversion Tracking: by Wolf+Bär GmbH – 1.4.1
WooCommerce AdWords Dynamic Remarketing: by Wolf+Bär GmbH – 1.4.1
WooCommerce MSRP Pricing: by Lee Willis – 2.7.0 – 2.9.0 is available
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.6
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 1.3.7
WooCommerce Product Add-ons: by WooCommerce – 2.8.1
WooCommerce Google Product Feed: by Lee Willis – 7.1.4 – 7.1.5 is available
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2
Trustbadge Reviews for WooCommerce: by Vendidero – 2.1.0
WooCommerce Xero Integration: by WooCommerce – 1.7.9
WooCommerce: by Automattic – 3.1.1
WooCommerce BarclaycardCw: by customweb GmbH – 4.0.87
WooSidebars: by WooThemes – 1.4.3
Yoast SEO Premium: by Team Yoast – 4.9
WP reCaptcha Integration: by Jörn Lund – 1.1.10
WP Rollback: by WordImpress – 1.4
Yoast SEO: WooCommerce: by Team Yoast – 4.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #9 - /store/
Basket: #10 - /basket/
Checkout: #11 - /checkout/
My account: #12 - /my-account/

### Theme ###

Name: Storefront Child
Version: 1.1.0
Author URL: http://pxhosting.co.uk
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.1.8 – 2.2.4 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
@glaing Want to share the CSV?

**Comment by glaing** [comment]
@mikejolley Sure, this is a cut-down version of our full import.

[https://staging.pxadventures.co.uk/wp-content/uploads/2017/07/WC3-1_Import_20170710-attempt5.csv](https://staging.pxadventures.co.uk/wp-content/uploads/2017/07/WC3-1_Import_20170710-attempt5.csv)

**Comment by mikejolley** [comment]
Testing this and happy to report it does import and map correctly. I also tested a new import with an attribute called "The Color" which worked too.

I did have to remove the 'images' column. Otherwise import fails because those images cannot be read yet (something about SSL certificate on the domain).

[test.zip](https://github.com/woocommerce/woocommerce/files/1152596/test.zip)

Thats the CSV after removing images column ^

This is the result of one variable product:

<img width="887" alt="2017-07-17 at 13 37" src="https://user-images.githubusercontent.com/90977/28268173-265dfc0e-6af5-11e7-9bb6-9f5a64f64cc0.png">

Are you doing new import, or update?

**Comment by glaing** [comment]
Ok, well I'm glad it isn't a wider issue, but I'm still a bit confused as to why it isn't working on these products for me.

I am running the import as an update.

I have just tried to import again using your file and it reports that it imported correctly, as my previous attempts do, but it still doesn't set the variations up correctly.

It is only probably affecting 20 products out of 900+, so I could try deleting these products and then reimporting them again to see if it's resolved.

**Comment by mikejolley** [comment]
let me try an update.

**Comment by glaing** [comment]
Hi Mike,
I've just tried deleting and re-creating one of the affected products and I get the same result on my staging server.

I'm wondering if I have a left over issue from my previous CSV product import method that has damaged my database rather than there being an issue with WooCommerce.

I'm going to try renaming the attributes to see if I can get something working.

Thanks,
George

**Comment by mikejolley** [comment]
@glaing did you find the issue?

**Comment by mikejolley** [comment]
I've done several variations of this testing now all on master branch. Imported, removed attributes from a product, imported with update checked, attributes set correctly. Not able to replicate I'm afraid. Get in touch if you cannot solve it and can provide access.

**Comment by vibe** [comment]
I was having this issue importing some products for a client of mine, turns out disabling a third party import plugin that was installed fixed the issue. 👍  

- Just incase anyone else drops by here and had this issue.

**Comment by sanchezalcala** [comment]
Hi, I have the same problem as you, I want to upload products with variations, this is the link for the CSV
https://drive.google.com/file/d/0B_SdFdDFrsFqejMyMDYzV2E2U0E/view?usp=sharing   , can you test it and tel me what´s the mistake please,

**Comment by glaing** [comment]
In the end, I found that if I included any other attributes that weren't involved with setting up that particular variation, it would fail.

Once I cleared my CSV up, my variations were being created properly.

However, I think your file is failing due to the variable line having Small|Medium|Large|Extra Large when it should be Small, Medium, Large, Extra Large. I also don't think you have set SKU's for the parent product.

I hope this helps!

**Comment by sanchezalcala** [comment]
Hi. thanks for the advice, can you send me and example  with sizes? Im goin to atach one of the CSV that I've create. I would be great if you can help me, Im a graphic designer so this is difficult for me :) .

________________________________

**Comment by suprin-bajracharya** [comment]
I am having a similar issue where i can't get the variations for the uploaded products. here' the link to the csv file please tell me what i have done wrong
https://docs.google.com/spreadsheets/d/1_KUm8I30ghhZSjJCwFQI_i9ivCH6AY9UWCHvJUm8OFc/edit#gid=0
