### ISSUE TITLE
Search for order numbers

### ISSUE THREAD

**Issue by elnicknamio** [woocommerce/woocommerce#16142]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [X] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to Orders
2. Search for a existing Order number
3. No result

## Environment

<details>
`
### WordPress Environment ###

WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g
PHP Version: 7.0.18-0ubuntu0.16.04.1
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 128 MB
Default Timezone is UTC: ❌ Standard-Zeitzone ist Europe/Paris – es sollte UTC sein
fsockopen/cURL: ✔
SoapClient: ❌ Dein Server verfügt nicht über eine lauffähige Version der SoapClient Klasse - einige Zahlungsschnittstellen
welche SOAP nutzen
funktionieren unter Umständen nicht korrekt.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: kbwp16_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Adminimize: von Frank Bültge – 1.11.2
Advanced Custom Fields PRO: von Elliot Condon – 5.5.14
iThemes Security: von iThemes – 6.3.0
Clean Image Filenames: von Upperdog – 1.1.1
Contact Form DB: von Michael Simpson – 2.10.17
Contact Form 7: von Takayuki Miyoshi – 4.8
Cookie Notice: von dFactory – 1.2.38
Loco Translate: von Tim Whitlock – 2.0.14
Redirector: von Ralf Hortt – 3.0.1
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 2.2.6
Search Everything: von Sovrn
zemanta – 8.1.9

TinyMCE Advanced: von Andrew Ozz – 4.6.3
Vendidero Helper: von Vendidero – 1.1.4
WooCommerce Bulk Discount: von Rene Puchinger – 2.4.5
WooCommerce Stripe Gateway: von WooCommerce – 3.2.2
WooCommerce Germanized Pro: von Vendidero – 1.8.0
WooCommerce Germanized: von Vendidero – 1.8.11
WooCommerce Min/Max Quantities: von Automattic – 2.3.14 – 2.3.18 ist verfügbar
WooCommerce: von Automattic – 3.1.1
WordPress Importer: von wordpressdotorg – 0.6.3
Yoast SEO: von Team Yoast – 5.0.2
WP Migrate DB: von Delicious Brains – 0.9.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: configurable (configurable)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #3722 - /shop/
Warenkorb: #3723 - /warenkorb/
Kasse: #22432 - /kasse/
Mein Konto: #21574 - /mein-konto/

WooCommerce Support: ❌ Nicht deklariert

### Templates ###

Overrides: something/woocommerce/archive-product.php
something/woocommerce/auth/footer.php
something/woocommerce/auth/form-grant-access.php
something/woocommerce/auth/form-login.php
something/woocommerce/auth/header.php
something/woocommerce/cart/cart-empty.php Version 2.0.0 ist veraltet. Die Hauptversion ist 3.1.0
something/woocommerce/cart/cart-item-data.php
something/woocommerce/cart/cart.php Version 2.3.8 ist veraltet. Die Hauptversion ist 3.1.0
something/woocommerce/cart/cart-shipping.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.1.0
something/woocommerce/cart/cart-totals.php
something/woocommerce/cart/cross-sells.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/cart/mini-cart.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.1.0
something/woocommerce/cart/proceed-to-checkout-button.php
something/woocommerce/cart/shipping-calculator.php
something/woocommerce/checkout/cart-errors.php
something/woocommerce/checkout/form-billing.php Version 2.1.2 ist veraltet. Die Hauptversion ist 3.0.9
something/woocommerce/checkout/form-checkout.php
something/woocommerce/checkout/form-coupon.php
something/woocommerce/checkout/form-login.php
something/woocommerce/checkout/form-pay.php
something/woocommerce/checkout/form-shipping.php Version 2.2.0 ist veraltet. Die Hauptversion ist 3.0.9
something/woocommerce/checkout/payment-method.php
something/woocommerce/checkout/payment.php
something/woocommerce/checkout/review-order.php
something/woocommerce/checkout/terms.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.1.1
something/woocommerce/checkout/thankyou.php Version 2.2.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/content-product_cat.php
something/woocommerce/content-product.php Version 2.6.1 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/content-single-product.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/content-widget-product.php
something/woocommerce/emails/admin-cancelled-order.php
something/woocommerce/emails/admin-failed-order.php
something/woocommerce/emails/admin-new-order.php
something/woocommerce/emails/customer-completed-order.php
something/woocommerce/emails/customer-invoice.php
something/woocommerce/emails/customer-new-account.php
something/woocommerce/emails/customer-note.php
something/woocommerce/emails/customer-on-hold-order.php
something/woocommerce/emails/customer-processing-order.php
something/woocommerce/emails/customer-refunded-order.php
something/woocommerce/emails/customer-reset-password.php
something/woocommerce/emails/email-addresses.php Version 2.4.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/emails/email-customer-details.php
something/woocommerce/emails/email-footer.php
something/woocommerce/emails/email-header.php
something/woocommerce/emails/email-order-details.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/emails/email-order-items.php Version 2.1.2 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/emails/email-styles.php
something/woocommerce/emails/plain/admin-cancelled-order.php
something/woocommerce/emails/plain/admin-failed-order.php
something/woocommerce/emails/plain/admin-new-order.php
something/woocommerce/emails/plain/customer-completed-order.php
something/woocommerce/emails/plain/customer-invoice.php
something/woocommerce/emails/plain/customer-new-account.php
something/woocommerce/emails/plain/customer-note.php
something/woocommerce/emails/plain/customer-on-hold-order.php
something/woocommerce/emails/plain/customer-processing-order.php
something/woocommerce/emails/plain/customer-refunded-order.php
something/woocommerce/emails/plain/customer-reset-password.php
something/woocommerce/emails/plain/email-addresses.php
something/woocommerce/emails/plain/email-customer-details.php
something/woocommerce/emails/plain/email-order-details.php
something/woocommerce/emails/plain/email-order-items.php Version 2.1.2 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/global/breadcrumb.php
something/woocommerce/global/form-login.php
something/woocommerce/global/quantity-input.php
something/woocommerce/global/sidebar.php
something/woocommerce/global/wrapper-end.php
something/woocommerce/global/wrapper-start.php
something/woocommerce/loop/add-to-cart.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/loop/loop-end.php
something/woocommerce/loop/loop-start.php
something/woocommerce/loop/no-products-found.php
something/woocommerce/loop/orderby.php
something/woocommerce/loop/pagination.php
something/woocommerce/loop/price.php
something/woocommerce/loop/rating.php Version 2.0.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/loop/result-count.php Version 2.0.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/loop/sale-flash.php
something/woocommerce/myaccount/dashboard.php
something/woocommerce/myaccount/downloads.php Version 2.6.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/myaccount/form-add-payment-method.php Version 2.6.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/myaccount/form-edit-account.php
something/woocommerce/myaccount/form-edit-address.php Version 2.6.0 ist veraltet. Die Hauptversion ist 3.0.9
something/woocommerce/myaccount/form-login.php
something/woocommerce/myaccount/form-lost-password.php Version 2.6.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/myaccount/form-reset-password.php Version 2.6.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/myaccount/lost-password-confirmation.php
something/woocommerce/myaccount/my-account.php
something/woocommerce/myaccount/my-address.php
something/woocommerce/myaccount/my-downloads.php
something/woocommerce/myaccount/my-orders.php
something/woocommerce/myaccount/navigation.php
something/woocommerce/myaccount/orders.php Version 2.6.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/myaccount/payment-methods.php
something/woocommerce/myaccount/view-order.php Version 2.6.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/notices/error.php
something/woocommerce/notices/notice.php
something/woocommerce/notices/success.php
something/woocommerce/order/form-tracking.php
something/woocommerce/order/order-again.php
something/woocommerce/order/order-details-customer.php Version 2.4.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/order/order-details-item.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/order/order-details.php Version 2.6.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/order/tracking.php
something/woocommerce/product-searchform.php
something/woocommerce/single-product/add-to-cart/external.php
something/woocommerce/single-product/add-to-cart/grouped.php Version 2.1.7 ist veraltet. Die Hauptversion ist 3.0.7
something/woocommerce/single-product/add-to-cart/simple.php Version 2.1.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/single-product/add-to-cart/variable.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/single-product/add-to-cart/variation.php
something/woocommerce/single-product/meta.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/single-product/price.php Version 2.4.9 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/single-product/product-attributes.php Version 2.1.3 ist veraltet. Die Hauptversion ist 3.1.0
something/woocommerce/single-product/product-image.php Version 2.6.3 ist veraltet. Die Hauptversion ist 3.1.0
something/woocommerce/single-product/product-thumbnails.php Version 2.6.3 ist veraltet. Die Hauptversion ist 3.1.0
something/woocommerce/single-product/rating.php Version 2.3.2 ist veraltet. Die Hauptversion ist 3.1.0
something/woocommerce/single-product/related.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/single-product/review-meta.php Version 2.6.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/single-product/review.php
something/woocommerce/single-product/review-rating.php Version 2.6.0 ist veraltet. Die Hauptversion ist 3.1.0
something/woocommerce/single-product/sale-flash.php
something/woocommerce/single-product/share.php
something/woocommerce/single-product/short-description.php
something/woocommerce/single-product/tabs/additional-information.php Version 2.0.0 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/single-product/tabs/description.php
something/woocommerce/single-product/tabs/tabs.php
something/woocommerce/single-product/title.php
something/woocommerce/single-product/up-sells.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.0.0
something/woocommerce/single-product.php
something/woocommerce/single-product-reviews.php
something/woocommerce/taxonomy-product_cat.php
something/woocommerce/taxonomy-product_tag.php
</details>

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Custom order numbers, i.e. not the default order IDs, are provided by extensions. In your case, I think Germanised. It needs to provide this functionality for you.
