### ISSUE TITLE
No Shipping Address on Single Page Checkout Form

### ISSUE THREAD

**Issue by jeffcandoris** [woocommerce/woocommerce#16143]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Single Product One Page Checkout
2. Our results: http://imgur.com/a/ZLVzu
3. Here is the regular cart page that shows both Billing AND Shipping: http://imgur.com/a/sY5xy
4. I have added this code to functions.php which fixed the issue temporarily, then the issue has returned. PHP code: add_filter( 'woocommerce_ship_to_different_address_checked', '__return_true' );

## Expected behavior and actual behavior

When I follow those steps, I see... no shipping address.

I was expecting... to be able to add billing and shipping address.

## Environment

<details>
`
### WordPress Environment ###

Home URL: https://deltawaterfowl.org
Site URL: https://deltawaterfowl.org
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30-1+wpengine8
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

404page - your smart custom 404 error page: by Peter Raschendorfer – 3.0
Akismet Anti-Spam: by Automattic – 3.3.2
Login by Auth0: by Auth0 – 3.2.22
Candoris Overrides: by Candoris – 1.0.0
Gallery Carousel Without JetPack: by Syed Balkhi – 0.7.5
Contact Form 7: by Takayuki Miyoshi – 4.8
Duplicate Page: by mndpsingh287 – 2.3
Easing Slider: by Matthew Ruddy – 3.0.8
Easy Pricing Tables Premium: Business: by Fatcat Apps – 2.3.5
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
Enhanced Category Pages: by Ciprian Amariei
Diana Amitroaei – 2.3.0

Envato Market: by Derek Herman – 1.0.0-RC2
Flamingo: by Takayuki Miyoshi – 1.6
Flip Book: by flipbuilder.com – 2.0
Fusion Builder: by ThemeFusion – 1.1.6
Fusion Core: by ThemeFusion – 3.1.6
Hide Title: by Brandon Kraft & Randall Runnels – 1.0.4
Insert Headers and Footers: by WPBeginner – 1.4.2
jQuery Updater: by Ramoonus – 3.2.1
JSON API: by Dan Phiffer – 1.1.1
Log Out Shortcode: by OM4 – 1.0.5
Nav Menu Roles: by Kathy Darling – 1.8.6
Page Restrict: by Matt Martz & Andy Stratton – 2.2.8
Photo Contest Wordpress Plugin: by Zbyněk Hovorka – 3.1
Slider Revolution: by ThemePunch – 5.4.2
Slideshow: by DevPress – 0.1
User Role Editor: by Vladimir Garagulya – 4.35
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.5
WooCommerce Authorize.Net AIM Gateway: by WooThemes / SkyVerge – 3.9.2 – 3.11.3 is available
WooCommerce Authorize.Net CIM Gateway: by WooThemes / SkyVerge – 2.5.1 – 2.6.3 is available
WooCommerce Name Your Price: by Kathy Darling – 2.5.5
WooCommerce One Page Checkout: by Prospress Inc. – 1.5.1
WooCommerce Ultimate Multi Currency Suite: by Dev49.net – 1.9.1
WooCommerce: by Automattic – 3.1.0 – 3.1.1 is available
Wp Lightbox Bank Standard Edition: by Tech Banker – 2.0.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: donation (donation)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/

### Theme ###

Name: Avada
Version: 5.1.6
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Authorize.Net CIM ###

Environment: Production
Tokenization Enabled: 

### Authorize.Net AIM ###

Environment: Production
`
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
> WooCommerce One Page Checkout: by Prospress Inc

> unless this is a question about a premium plugin in which you should use the helpdesk for official extensions

Please use the helpdesk as the issue form says.
