### ISSUE TITLE
Behaviour of get_regular_price() / get_sale_price() on WC_Product_Variable

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce#16145]
I'm not sure what the defined behaviour of calling `get_regular_price()` / get_sale_price() on a variable product is, and therefore whether or not this is a bug (although it seems like one). Comments welcome!

## Prerequisites

1. Create a variable product (product A) with two variations, set the price of both variations to $10
2. Create a simple product (product B) with a price of $30 and a sale price of $28
3. Edit product B, and convert it to a variable product with two variations, each with a price of $10. 

## Steps to reproduce the issue

Call `get_regular_price()` or `get_sale_price()` on product A - you get back an empty string. 

```
wp> get_class($p);
=> phar:///Users/leewillis/bin/wp-cli.phar/php/WP_CLI/REPL.php:43:
string(19) "WC_Product_Variable"
wp> $p->get_sale_price()
=> phar:///Users/leewillis/bin/wp-cli.phar/php/WP_CLI/REPL.php:43:
string(0) ""
wp> $p->get_regular_price()
=> phar:///Users/leewillis/bin/wp-cli.phar/php/WP_CLI/REPL.php:43:
string(0) ""
```
Call `get_regular_price()` or `get_sale_price()` on product B however, returns the values that were set against the product before it was converted into a variable product. 
```
wp> get_class($p);
=> phar:///Users/leewillis/bin/wp-cli.phar/php/WP_CLI/REPL.php:43:
string(19) "WC_Product_Variable"
wp> $p->get_regular_price()
=> phar:///Users/leewillis/bin/wp-cli.phar/php/WP_CLI/REPL.php:43:
string(3) "30"
wp> $p->get_sale_price()
=> phar:///Users/leewillis/bin/wp-cli.phar/php/WP_CLI/REPL.php:43:
string(3) "28"
```

Since both products have two variations priced at $10, I'd expect the results for product B to be the same as for product A.

**Comment by mikejolley** [comment]
I think it should return nothing, since it has no prices of it's own.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/16199

**Comment by leewillis77** [comment]
Thanks @mikejolley !
