### ISSUE TITLE
Flexible shipping not showing in list of shipping methods

### ISSUE THREAD

**Issue by m45group** [woocommerce/woocommerce#16147]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce
- [X ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Expected behavior and actual behavior

When I follow those steps, I see
After I install and activate the flexible shipping plugin (both new version and previous version) I do not get Flexible Shipping in my list of zone choices - only Flat Rate, Free Shipping and Local Pickup. I've used this plug-in before and know that I should see Flexible Shipping in the list. 

I was expecting... Flexible Shipping to be in the list.

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://yellowcreekquiltdesigns.com
Site URL: https://yellowcreekquiltdesigns.com
WC Version: 3.0.9
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.9
WC Database Prefix: wp3i_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Pinterest WordPress Plugin - AccessPress Pinterest: by AccessPress Themes – 3.1.9
Better Search Replace: by Delicious Brains – 1.3
Contact Form 7: by Takayuki Miyoshi – 4.8
Contact Form CFDB7: by Arshid – 1.1.2
Duplicate Page and Post: by Arjun Thakur – 1.0.1
Flexible Shipping: by WP Desk – 1.9.5
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
Insert Headers and Footers: by WPBeginner – 1.4.2
Kraken Image Optimizer: by Karim Salman – 2.6.2
LayerSlider WP: by Kreatura Media – 5.6.9
Virtual Robots.txt: by Marios Alexandrou – 1.8
SEO XML SITEMAP: by MacZin Team – 1.0
WooCommerce: by Automattic – 3.0.9 – 3.1.1 is available
WP Stagecoach: by WP Stagecoach – 1.3.6
WordPress Zero Spam: by Ben Marshall – 3.0.6

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #14 - /shop/
Cart: #15 - /cart/
Checkout: #16 - /checkout/
My account: ❌ Page does not contain the shortcode.

### Theme ###

Name: Yellow Creek xmarket Custom
Version: 1.0.0
Author URL: http://www.m45.com
Child Theme: ✔
Parent Theme Name: Xmarket - Responsive WordPress Theme
Parent Theme Version: 2.2.1
Parent Theme Author URL: http://themeforest.net/user/8theme
WooCommerce Support: ✔

### Templates ###

Overrides: xmarket/woocommerce/archive-product.php
xmarket/woocommerce/cart/cart.php
xmarket/woocommerce/cart/cross-sells.php
xmarket/woocommerce/cart/mini-cart.php
xmarket/woocommerce/checkout/review-order.php
xmarket/woocommerce/content-product.php
xmarket/woocommerce/content-product_cat.php
xmarket/woocommerce/content-single-product.php
xmarket/woocommerce/global/breadcrumb.php
xmarket/woocommerce/global/quantity-input.php
xmarket/woocommerce/loop/add-to-cart.php
xmarket/woocommerce/loop/loop-end.php
xmarket/woocommerce/loop/loop-start.php
xmarket/woocommerce/loop/no-products-found.php
xmarket/woocommerce/loop/pagination.php
xmarket/woocommerce/loop/rating.php
xmarket/woocommerce/loop/result-count.php
xmarket/woocommerce/loop/sale-flash.php
xmarket/woocommerce/myaccount/form-edit-account.php
xmarket/woocommerce/myaccount/form-login.php
xmarket/woocommerce/myaccount/my-orders.php
xmarket/woocommerce/single-product/add-to-cart/grouped.php
xmarket/woocommerce/single-product/add-to-cart/simple.php
xmarket/woocommerce/single-product/meta.php
xmarket/woocommerce/single-product/price.php
xmarket/woocommerce/single-product/product-image.php
xmarket/woocommerce/single-product/product-thumbnails.php
xmarket/woocommerce/single-product/related.php
xmarket/woocommerce/single-product/review.php
xmarket/woocommerce/single-product/sale-flash.php
xmarket/woocommerce/single-product/short-description.php
xmarket/woocommerce/single-product/tabs/additional-information.php
xmarket/woocommerce/single-product/tabs/description.php
xmarket/woocommerce/single-product/tabs/tabs.php
xmarket/woocommerce/single-product/title.php
xmarket/woocommerce/single-product/up-sells.php
xmarket/woocommerce/single-product-reviews.php
xmarket/woocommerce/single-product.php

`</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
You need to ask WP Desk about this - flexible shipping is not a core option nor something maintained by ourselves.

FWIW I did install the free version and did see it in the dropdown. I'm using 3.1.1

**Comment by amirvenus** [comment]
It seems like this problem is appearing again in the latest version of WC only.
