### ISSUE TITLE
How to maintain stock?

### ISSUE THREAD

**Issue by ddhara** [woocommerce/woocommerce#16154]
I am using set_paid = true when creating order using REST API so product is being redduced. But it's not auto increasing stock when canceling using REST API to update order. API which am using to cancel order is:

/wp-json/wc/v2/orders/<id> using PUT method and passing parameter 'status' => 'cancelled'

So every time I have to increase stock manually for the orders which are cancelled by user and it's really tough task to do it manually when bulk orders are coming and being cancelled.

And what if payment method is COD? I can't use set_paid = true. In this case order will be generated with status pending and stock will not be reduced. And even it's not reducing stock if am manually changing status to processing, confirmed, completed from wp-admin. It means stock remains as it is in fact product is delivered to the customer successfully.

So how can I maintain stock with some easy way so I don't need to reduce/increase the stock manually?

**Comment by mikejolley** [comment]
Stock is not restored automatically - there can be many reasons for a cancel (lost package, user request) so we leave this to the admin.

If you cannot leave this to the admin, product endpoints would be needed. The order itself will have `meta_data` if the stock was reduced so you can track it that way.

No easy way sorry.

**Comment by gauravmillipixels** [comment]
I am using set_paid = true when creating an order using REST API 
but unfortunately it's not reducing stock can you please help me out on it.
