### ISSUE TITLE
WC_DateTime will return false offset if I've deliberately overridden the UTC offset

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce#16151]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a new WC_DateTime object.
2. Set the timezone on it to `'Pacific/Chatham'`
3. Assume that https://github.com/woocommerce/woocommerce/issues/16150 is solved, and when setting the timezone on the object, the `utc_offset` property is also automatically set to the timezone's actual UTC offset instead of always being 0.
4. Then deliberately set the `utc_offset` property to `0` by calling the `set_utc_offset` public method with an argument of 0.
5. Try to recall the offset by using `getOffset`.

## Expected behavior and actual behavior

I expect the behaviour to return `0`.

However due to how the conditional works, a manually set `0` value on the offset will evaluate to `false`, and I will get back the `49500` that is originally the offset for the `'Pacific/Chatham'` TZ making step 4. above totally useless.

## Environment

None, it's code.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by javorszky** [comment]
Having thought more about:

Is the existence of the `utc_offset` property on the `WC_DateTime` object there so we could set the offset without having to set the timezone itself?

And is the reason it's setting the `utc_offset` property to 0 as soon as a timezone is deliberately set so that the `getOffset` would return the timezone's version of the offset instead of whatever was stored on the `utc_offset` previously?

**Comment by mikejolley** [comment]
So utc_offset is not supposed to reflect the timezone you set. It's neigh impossible to get an accurate offset from some timezone strings e.g. if you set the NY timezone, with daylight savings time it can change throughout the year.

utc_offset is used when no timezone is set and it maps to the WordPress gmt_offset setting. Code example:

```
if ( get_option( 'timezone_string' ) ) {
				$datetime->setTimezone( new DateTimeZone( wc_timezone_string() ) );
} else {
				$datetime->set_utc_offset( wc_timezone_offset() );
}
```

So it's either or, not both.

When the class has a timezone, it can let PHP DateTime class work things out.

When it does not have a timezone and only has an offset, it can do manual offsetting.

I'll try to clear this up in the code comments.

**Comment by javorszky** [comment]
Awesome, thank you very much for clearing this up!

**Comment by mikejolley** [comment]
@javorszky committing up some docblocks in a mo
