### ISSUE TITLE
WC_Email_Customer_Refunded_Order::get_default_heading() returns incorrect heading for full refunds

### ISSUE THREAD

**Issue by nikolov-tmw** [woocommerce/woocommerce#16157]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to Woocommerce > Settings > Emails
2. Click `Configure Order` for "Refunded Order"

## Expected behavior and actual behavior

When I follow those steps, I see that the default for "Full refund email heading" is "Your order has been partially refunded"

I was expecting to see the default for this to not include "partially"

## Environment

Environment details are irrelevant, problem comes down to a typo in the code.

## Isolating the problem

- [x] I can reproduce this bug consistently

You can see this typo right here - https://github.com/woocommerce/woocommerce/blob/master/includes/emails/class-wc-email-customer-refunded-order.php#L79 

In case where the refund is not partial, the string returned is "Your order has been **partially** refunded". It's a simple fix, so let me know if you'd like me to submit a PR or not.

**Comment by nikolov-tmw** [comment]
On that note, I found another issue with this same class. On this line - https://github.com/woocommerce/woocommerce/blob/master/includes/emails/class-wc-email-customer-refunded-order.php#L93 , `get_default_heading()` is used instead of `get_default_subject()`, which results in the subject being used instead of the heading(which is incorrect).

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/issues/16186 thanks.
