### ISSUE TITLE
Delay after submitting checkout form

### ISSUE THREAD

**Issue by yaniv1983** [woocommerce/woocommerce#16155]
Hi, I saw a few posts on this issue with different themes, decided to check with you. 

After submitting an order, on checkout form, user is waiting for 20-40 seconds. Nothing happens on screen, not even loading of a new page. After that wait the next screen loads (Credit card payment/ checkout/ thank you for phone orders).

Tried disabling plugins, changing theme, using core template - none worked.

WC Version:  3.1.1
WP Version: 4.8
Memory Limit: 256 MB
Server: Apache/2.2.22 (Debian) mod_ssl/2.2.22 OpenSSL/1.0.1e PHP/5.4.45-0+deb7u3
URL: https://rotemee.com

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Environment

<details>

סביבת WordPress
--
כתובת דף הבית: |   | https://rotemee.com
כתובת URL של אתר: |   | https://rotemee.com
גרסת WC: |   | 3.1.1
ספריית יומן הניתנת לכתיבה: |   | /html/wp-content/uploads/wc-logs/
גרסת WP: |   | 4.8
רשת אתרים של WP: |   | –
מגבלת זיכרון של WP: |   | 256 MB
מצב איתור באגים של WP: |   | –
אירוע מתוזמן של WP: |   |  
שפה: |   | he_IL

סביבת שרת
פרטי שרת:		Apache/2.2.22 (Debian) mod_ssl/2.2.22 OpenSSL/1.0.1e PHP/5.4.45-0+deb7u3
גרסת PHP:		 5.4.45-0+deb7u3 - דרישת מינימום מומלצת היא PHP גירסה 5.6. ראו: כיצד לעדכן את גירסת ה-PHP שברשותך
גודל מרבי של פוסט PHP:		10 MB
מגבלת זמן של PHP:		30
וריאציות קלט מרביות של PHP:		1000
גרסת cURL:		7.26.0, OpenSSL/1.0.1e
SUHOSIN מותקן:		–
גרסת MySQL:		 5.5.49 - דרישת מינימום מומלצת היא MySQL גירסה 5.6. ראו: הדרישות של WordPress
גודל העלאה מקסימלי:		10 MB
אזור הזמן המוגדר כברירת מחדל הוא UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
מחרוזת מרובת בתים:		
פרסום מרחוק:		
קבלה מרחוק:		

מסד נתונים
--
WC גרסת בסיס נתונים: |   | 3.1.1
קידומת מסד נתונים |   | wp_
woocommerce_sessions |   |  
woocommerce_api_keys |   |  
woocommerce_attribute_taxonomies |   |  
woocommerce_downloadable_product_permissions |   |  
woocommerce_order_items |   |  
woocommerce_order_itemmeta |   |  
woocommerce_tax_rates |   |  
woocommerce_tax_rate_locations |   |  
woocommerce_shipping_zones |   |  
woocommerce_shipping_zone_locations |   |  
woocommerce_shipping_zone_methods |   |  
woocommerce_payment_tokens |   |  
woocommerce_payment_tokenmeta |   |  
מסד הנתונים GeoIP של MaxMind: |   | /html/wp-content/uploads/GeoIP.dat

אבטחה
חיבור מאובטח (HTTPS):		
הסתר שגיאות ממבקרים		

תוספים פעילים (20)
--
Woocommerce Tranzila Payment Gateway |   | מאת 10Bit – 1.6.18
Akismet Anti-Spam |   | מאת Automattic – 3.3.3
CF7 HubSpot Forms Add-on For Contact Form 7 |   | מאת Ahmad Karim – 1.0
טפסי צרו קשר 7 |   | מאת טקאיוקי מיושי – 4.8
Features |   | מאת WooThemes – 1.5.0
HubSpot Tracking Code for WordPress |   | מאת HubSpot – 1.2.1
WPBakery Visual Composer |   | מאת Michael M - WPBakery.com – 4.11.2.1
Slider Revolution |   | מאת ThemePunch – 5.2.5
WD Grid / List toggle |   | מאת Wpdance – 1.0.0
WD Portfolio |   | מאת WD Team – 1.0.1
WD QuickShop |   | מאת Wpdance – 1.0.1
WD ShortCode |   | מאת Wpdance – 1.0.4
WD Slide |   | מאת WD Team – 1.0.0
WooCommerce Weight Based Shipping |   | מאת weightbasedshipping.com – 5.0.9
ווקומרס |   | מאת חברת אוטומטיק – 3.1.1
Wordfence Security |   | מאת Wordfence – 6.3.12
Yoast SEO |   | מאת Team Yoast – 5.0.2
WP-Mail-SMTP |   | מאת Callum Macdonald – 0.10.1
WP Rocket |   | מאת WP Media – 2.10.5
YITH WooCommerce Ajax Search |   | מאת YITHEMES – 1.5.3

הגדרות
--
API מופעל: |   |  
הכרח SSL: |   |  
מטבע |   | ILS (₪)
מיקום סימון מטבע |   | left
מפריד אלפים |   | ,
מפריד עשרוני |   | .
מספר הספרות העשרוניות |   | 2
טקסונומיות: סוגי מוצרים |   | external (external), grouped (grouped), simple (simple), variable (variable)
טקסונומיות: נראות המוצר |   | exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)

</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
The multi-step checkout flow you have is not from WooCommerce, it's your theme. 

There is no magic fix for performance issues either, the site and the hosting would need looking at by a developer and would need to be optimised.

**Comment by yaniv1983** [comment]
Thanks Mike, 
I did try using the default WC files (deleted the ones altered by the template) - the issue remained.

The site is well-optimised, with compressed images, caching plugin (wp-rocket) etc. Loading time is about 2 seconds for the homepage. The problem is only on checkout, after submitting.

**Comment by mikejolley** [comment]
Which is uncached, and writing lots of data to the DB, as well as sending emails and handling payments. There is more going on there.

**Comment by yaniv1983** [comment]
I understand it is a very complicated process, but it seems that nothing happens after clicking. There is a delay before any of that even starts.

**Comment by mikejolley** [comment]
You need to work out what part is slow; i.e. emails, payment, just the connection from your client to your server.

You can try deferring emails with `add_filter( 'woocommerce_defer_transactional_emails', '__return_true' );`

**Comment by yaniv1983** [comment]
I'll try and post back. I think, though, emails is not the issue, since they are sen after payment. Don't you think so?
Thanks for your help!

**Comment by yaniv1983** [comment]
Hi, sorry, tried that, didn't affect this issue.

**Comment by mikejolley** [comment]
It's not really possible to suggest anything else without an in depth look at the server + hosting etc. You may want to find someone experienced who can help there.

**Comment by yaniv1983** [comment]
Ok, will try that. Thanks!
