### ISSUE TITLE
get_reviews_allowed() is true, wp_posts.comment_status is 'open' but $post->comment_status=='closed'

### ISSUE THREAD

**Issue by Jon007** [woocommerce/woocommerce#16153]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1.  Create a product with Enable reviews checked, Save it
2. Check in the database that wp_posts.comment_status for the ID is 'open'
3. hook save_post action
4. debug

## Expected behavior and actual behavior

When I follow those steps, I see...
- $product->get_reviews_allowed() is true
- $post->comment_status=='closed'

I was expecting...
- $post->comment_status=='open'

This was found debugging a translation tool: post level information such as 'comment_status', 'ping_status', 'menu_order' was previously synchronised between the linked posts using a standard post level function (as implemented by Polylang). 
However now, saving any Product causes the comment_status to be unset on the linked posts..
It may be that now this has changed with the WC3+ load optimizations.

[I have not spotted a similar problem for other attributes, for example menu_order seems to be correct in both $post->menu_order and $product->menu_order]

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost:8888/woo3debug
Site URL: http://localhost:8888/woo3debug
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.0.15 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.0.15
PHP Post Max Size: 32 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Polylang: by Frédéric Demarle – 2.1.5
WooCommerce: by Automattic – 3.2.0-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #802 - /es/terms/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
````
</details>

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently

**Comment by Jon007** [comment]
class-wc-product-data-store-cpt.php:

l.149: reviews_allowed is set to boolean
			'reviews_allowed'   => 'open' === $post_object->comment_status,

l.178: reviews_allowed fails comparison to string and so is always set to 'closed'
				'comment_status' => $product->get_reviews_allowed( 'edit' ) ? 'open' : 'closed',

**Comment by mikejolley** [comment]
After WooCommerce has saved the product, it sets this:

https://github.com/woocommerce/woocommerce/blob/5ebc4a40104b2f93c7329cda3b4fb0c75aa54444/includes/data-stores/class-wc-product-data-store-cpt.php#L176

I don't think messing with the $post global would be a good idea...

**Comment by Jon007** [comment]
Yes, I know it's set after save, its just during the save that things are out of sync and $post->comment_status is set to 'closed' by wordpress core.
Then other components (in this case Polylang) are hooking the wordpress core and potentially propagating the wrong value.

**Comment by mikejolley** [comment]
Since other things can change post data on that hook maybe it would make sense to a) use a later priority and b) load the object rather than rely on the global.

**Comment by Jon007** [comment]
> b) load the object rather than rely on the global.
It's not using global, it's hooking save_post which receives $post as a parameter.
As it's a save it is expecting to get the submitted values, not reload.

> a) use a later priority 
if it's a workaround to 3rd party components getting the wrong value from Wordpress since WooCommerce form field is different, then it would have to go in on an earlier priority.  
They also use a very specific priority, from their comment:
// Priority 21 to come after advanced custom fields ( 20 ) and before the event calendar which breaks everything after 25
