### ISSUE TITLE
WC_DateTime sets utc_offset to 0 when a timezone is set on it

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce#16150]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. See this code: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-datetime.php#L62
2. We're passing in a `DateTimeZone` object because the parent class demands it, which has a `getOffset` method which the code is using somewhere else

## Expected behavior and actual behavior

Given the following code:

```
$wc_dt = new WC_DateTime( 'now' );
$tz = new DateTimeZone( 'Pacific/Chatham' );
$wc_dt->setTimeZone( $tz );
```
I would expect the `utc_offset` to be `49500` instead of `0`. (49500 is 13 hours and 45 minutes in seconds)

See http://uk1.php.net/manual/en/datetime.settimezone.php

## Environment

None, it's code.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by javorszky** [comment]
The reason is probably what I've written here: https://github.com/woocommerce/woocommerce/issues/16151#issuecomment-315926074, though a confirm / deny would be ace!

**Comment by mikejolley** [comment]
I'll reply there - the comments in the code may need rewording since it's not that clear.
