### ISSUE TITLE
email placeholders missing; suggest reconciling

### ISSUE THREAD

**Issue by diablodale** [woocommerce/woocommerce#16156]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce
- [ X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [  ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Have default working install of Woocommerce 3.1
2. Go to Woocommerce admin
3. Click Emails tab
4. Click on "Processing order"
5. Hover cursor over (?) to the right of subject

## Expected behavior

I see placeholders are: {site_title}, {blogname}, {order_number}, {order_date}, 

## Actual behavior

I see placeholder is only: {site_title}

## Discussion

This is a repeating problem across other emails. E.g., customer_on_hold_order also has this problem. All of the emails are subs of the main class WC_Email. This mail class can always parse placeholders of {blogname} and {site_title} yet the description at lines 541 and 550 of class-wc-email.php write otherwise. Changing that text is an isolated quick fix.

I suggest a brief discussion with this issue on an alternate fix. The separation of $this->find[] from the text derived in init_form_fields() ... $this->form_fields[]['description'] has lead to this bug.

One approach could be to:

1. Reorder the WC_Email _construct so that the call to init_form_fields() is after the assignments into the class' find[] array.
2. Reconcile that all the child email classes assign their find[] entries in their own _construct before they call the parent _construct. For example, class-wc-email-customer-invoice should move the two find[] assignments out of its trigger() method and into its _construct()
3. Update init_form_fields() to create its 'description' text from the find[] array. This might need some reconciling across the child email classes since some of the classes have their own init_form_fields() rather than using the parent's.

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://axa73.hidale.com
Site URL: https://axa73.hidale.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.18-0ubuntu0.16.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Akismet Anti-Spam: by Automattic – 3.3.3
All In One SEO Pack: by Michael Torbert – 2.3.14.1
REST API Basic Authentication over HTTPS: by Dale Phurrough – 0.2
Change Wordpress robot email behavior: by Dale Phurrough – 1.0.1
Cookie Law Info: by Richard Ashby – 1.5.3
Disable Emojis: by Ryan Hellyer – 1.5.3
Disable XML-RPC: by Philip Erb – 1.0.1
Hard 404 on Wordpress searches: by Dale Phurrough – 1.00
Reset Opcache on Upgrade: by Dale Phurrough – 1.0.0
Restrict Dashboard News: by Dale Phurrough – 0.1.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
Woocommerce modify checkout fields for hidale.com: by Dale Phurrough – 1.0.1
Woocommerce Paypal Gateway Extras: by Dale Phurrough – 1.1.0
Woocommerce Digital Downloads, Registration, Authorization: by Dale Phurrough – 1.1.0
WooCommerce: by Automattic – 3.1.1
WP Google Authenticator: by Julien Liabeuf – 1.1.0
WP Maintenance Mode: by Designmodo – 2.0.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #753 - /shop/
Cart: #754 - /cart/
Checkout: #755 - /checkout/
My account: #756 - /my-account/

### Theme ###

Name: Twenty Eleven Customized by Dale
Version: 1.0
Author URL: http://hidale.com
Child Theme: ✔
Parent Theme Name: Twenty Eleven
Parent Theme Version: 2.6
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

## Isolating the problem

- [ X] This bug happens with only WooCommerce plugin active
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/16185
