### ISSUE TITLE
Variation Product Sale Display

### ISSUE THREAD

**Issue by jgajera** [woocommerce/woocommerce#16169]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a variable product, give variations different prices
2. Put all variations on sale with different sale prices
3. Shop page does not show the original striked-out with sale range next to it anymore. I know you guys removed this from the API with WC 3.0.x. Is there any way to get this feature back?

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://florence-ave-clone-4.mystagingwebsite.com
Site URL: https://florence-ave-clone-4.mystagingwebsite.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.21
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.54.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (42) ###

VaultPress: by Automattic – 1.9.2
Akismet Anti-Spam: by Automattic – 3.3.3
Breadcrumb NavXT: by John Havlik – 5.7.1
Child Theme Configurator: by Lilaea Media – 2.2.6
Contact Form 7: by Takayuki Miyoshi – 4.8
Dokan (Lite) - Multi-vendor Marketplace: by Tareq Hasan – 2.6.4
Dokan (Pro) - Multi-vendor Marketplace: by weDevs – 2.6.3
Dokan - Duplicate Product: by weDevs – 0.3
Dwolla Payment Gateway for WooCommerce: by Pablo Carranza – 1.0
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
Facebook for WooCommerce: by Facebook – 1.4.1
Head, Footer and Post Injections: by Stefano Lissa – 3.0.7
Hello Bar (Official): by Hello Bar – 1.0
Icon List: by DesignOrbital.com – 0.4
Instapage Plugin: by Instapage – 3.1.8
Jetpack by WordPress.com: by Automattic – 5.1
MailChimp for WooCommerce: by MailChimp – 2.0.0
Max Mega Menu: by Tom Hemsley – 2.3.7.1
Meta Slider: by Matcha Labs – 3.5.1
Pods - Custom Content Types and Fields: by Pods Framework Team – 2.6.9
POWr Countdown Timer: by POWr.io – 1.6.3
Product Catalog Feed by PixelYourSite: by PixelYourSite – 1.0.4
Product CSV Import Export (BASIC): by XAdapter – 1.3.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Simple Tooltips: by Justin Saad – 2.1.3
Page Builder by SiteOrigin: by SiteOrigin – 2.5.8
SiteOrigin Widgets Bundle: by SiteOrigin – 1.9.3
Abandoned Cart Reports For WooCommerce: by Small Fish Analytics – 2.1.11
WC Disable Zoom / Lightbox features: by Rynaldo Stoltz – 1.0
WC Fields Factory: by Saravana Kumar K – 1.4.0
Packages Configuration for WooCommerce: by Jason Judge jason@academe.co.uk – 1.2.5
WC Password Strength Settings: by Daniel Santoro – 1.1.0
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.3
WooCommerce Stripe Gateway: by WooCommerce – 3.2.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce Product Fees: by Caleb Burks – 1.2
WooCommerce ShippingEasy Integration: by WooThemes – 3.4.1
WooCommerce Slack: by WooCommerce – 1.1.4
WooCommerce: by Automattic – 3.1.1
WooSwipe: by Dean Oakley
Eric Jinks
BJ CJ – 1.1.6.5

WP Smush: by WPMU DEV – 2.7.1
YITH Infinite Scrolling: by YITHEMES – 1.0.7

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #3 - /
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/

### Theme ###

Name: FreeStore Child
Version: 1.0.0.1496874028
Author URL: http://www.korecreative.io
Child Theme: ✔
Parent Theme Name: FreeStore
Parent Theme Version: 1.2.1
Parent Theme Author URL: https://kairaweb.com/
WooCommerce Support: ✔

### Templates ###

Overrides: freestore-child/woocommerce/loop/price.php

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off
`
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
This isn't a bug report is it :) 

This filter gives you full control over the price HTML, you just need to generate it with code: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-variable.php#L156

https://www.skyverge.com/blog/change-woocommerce-price-display/

https://calebburks.com/modify-variable-product-prices-in-woocommerce/

**Comment by jgajera** [comment]
@mikejolley I apologize, it's definitely not a bug; I did my homework! I figured it out half an hour ago, and Caleb's post helped me through it. I edited quite a bit of the code so it didn't apply to all products (just variable products). I've pasted my code below for another poor soul's future reference. Thank you for giving me all of those references, I appreciate you!

`//add variation sale strikethrough with original price on shop and category pages
function wc_wc20_variation_price_format( $price, $product ) {

// Main Price
$prices = array( $product->get_variation_price( 'min', true ), $product->get_variation_price( 'max', true ) );
$price_min = $prices[0] !== $prices[1] ? sprintf( __( '%1$s', 'woocommerce' ), wc_price( $prices[0] ) ) : wc_price( $prices[0] );
$price_max = $prices[0] !== $prices[1] ? sprintf( __( '%1$s', 'woocommerce' ), wc_price( $prices[1] ) ) : wc_price( $prices[1] );
// Sale Price
$prices = array( $product->get_variation_regular_price( 'min', true ), $product->get_variation_regular_price( 'max', true ) );
sort( $prices );
$saleprice_min = $prices[0] !== $prices[1] ? sprintf( __( '%1$s', 'woocommerce' ), wc_price( $prices[0] ) ) : wc_price( $prices[0] );
$saleprice_max = $prices[0] !== $prices[1] ? sprintf( __( '%1$s', 'woocommerce' ), wc_price( $prices[1] ) ) : wc_price( $prices[1] );
if ( $price_min !== $price_max ) {
$price = '<del>' . $saleprice_min . ' - '. $saleprice_max . '</del> <ins>' . $price_min . ' - '. $price_max . '</ins>';
}
return $price;
}
add_filter( 'woocommerce_variable_sale_price_html', 'wc_wc20_variation_price_format', 10, 2 );
add_filter( 'woocommerce_variable_price_html', 'wc_wc20_variation_price_format', 10, 2 );
`

**Comment by waseemsannib** [comment]
Hello jgajera
Actually, I have added your code but the strikethrough was on the original & sale prices together, not only on the original prices, so how can I apply the strikethrough to the original prices only?
thank you
waiting for your reply

**Comment by jgajera** [comment]
Hi @waseemsannib - my code looks correct in that the `<del>` tag (i.e. strikethrough) is only going through the original sale prices. Additionally, the website I used it on has it working fine still. I would play around with where the `<del>` tags are in your code. Maybe your theme has custom WC code added in the parent theme's functions.php file?

**Comment by waseemsannib** [comment]
Thank you for your reply Janki,
your code worked in my system, but see what is the problem below, as you see the strikethrough on the sale products and on the regular product, this the problem with me, maybe we need to delete some line of your code.
Please help me in this as I’m tired of trying to fix this issue.
Thank you very much

//add variation sale strikethrough with original price on shop and category pages
function wc_wc20_variation_price_format( $price, $product ) {

// Main Price
$prices = array( $product->get_variation_price( 'min', true ), $product->get_variation_price( 'max', true ) );
$price_min = $prices[0] !== $prices[1] ? sprintf( __( '%1$s', 'woocommerce' ), wc_price( $prices[0] ) ) : wc_price( $prices[0] );
$price_max = $prices[0] !== $prices[1] ? sprintf( __( '%1$s', 'woocommerce' ), wc_price( $prices[1] ) ) : wc_price( $prices[1] );
// Sale Price
$prices = array( $product->get_variation_regular_price( 'min', true ), $product->get_variation_regular_price( 'max', true ) );
sort( $prices );
$saleprice_min = $prices[0] !== $prices[1] ? sprintf( __( '%1$s', 'woocommerce' ), wc_price( $prices[0] ) ) : wc_price( $prices[0] );
$saleprice_max = $prices[0] !== $prices[1] ? sprintf( __( '%1$s', 'woocommerce' ), wc_price( $prices[1] ) ) : wc_price( $prices[1] );
if ( $price_min !== $price_max ) {
$price = '<del>' . $saleprice_min . ' - '. $saleprice_max . '</del> <ins>' . $price_min . ' - '. $price_max . '</ins>';
}
return $price;
}
add_filter( 'woocommerce_variable_sale_price_html', 'wc_wc20_variation_price_format', 10, 2 );
add_filter( 'woocommerce_variable_price_html', 'wc_wc20_variation_price_format', 10, 2 );
check if you can edit the code to apply the strikethrough on the sale products only.

**Comment by CookPete** [comment]
I've tweaked @jgajera's example to fix the issue that @waseemsannib pointed out, where the `<del>` prices were appearing for all products. It also fixes a bug where a variable product with a non-variable price was appearing as `£20 - £20`:

```php
//add variation sale strikethrough with original price on shop and category pages
function wc_wc20_variation_price_format($price, $product) {
  // Main Price
  $prices = array($product->get_variation_price('min', true), $product->get_variation_price('max', true));
  $price_min = $prices[0] !== $prices[1] ? sprintf(__('%1$s', 'woocommerce'), wc_price($prices[0])) : wc_price($prices[0]);
  $price_max = $prices[0] !== $prices[1] ? sprintf(__('%1$s', 'woocommerce'), wc_price($prices[1])) : wc_price($prices[1]);
  // Sale Price
  $prices = array($product->get_variation_regular_price('min', true), $product->get_variation_regular_price('max', true));
  sort($prices);
  $saleprice_min = $prices[0] !== $prices[1] ? sprintf(__('%1$s', 'woocommerce'), wc_price($prices[0])) : wc_price($prices[0]);
  $saleprice_max = $prices[0] !== $prices[1] ? sprintf(__('%1$s', 'woocommerce'), wc_price($prices[1])) : wc_price($prices[1]);
  if ($price_min !== $saleprice_min || $price_max !== $saleprice_max) {
    $del = $saleprice_min === $saleprice_max ? $saleprice_min : "$saleprice_min - $saleprice_max";
    $ins = $price_min === $price_max ? $price_min : "$price_min - $price_max";
    return "<del>$del</del> <ins>$ins</ins>";
  }
  return $price;
}
add_filter('woocommerce_variable_sale_price_html', 'wc_wc20_variation_price_format', 10, 2);
add_filter('woocommerce_variable_price_html', 'wc_wc20_variation_price_format', 10, 2);
```

**Comment by Spahbed** [comment]
Works great except it seems to take off like 0.5% of my prices. Ie. the variation might be 20.99 but the normal main price will say 20.71 for instance, Once I take the code out it is fine and back to normal.Is it the same for anyone else?

**Comment by siderio2** [comment]
Thank you so much, @jgajera, works fine.

**Comment by AndersJpg** [comment]
hey, could one try and help me with try to add text infront of the sale price so its says

// Main Price
$prices = array( $product->get_variation_price( 'min', true ), $product->get_variation_price( 'max', true ) );
$price = $prices[0] !== $prices[1] ? sprintf( __( 'fra %1$s', 'woocommerce' ), wc_price( $prices[0] ) ) : wc_price( $prices[0] );
// Sale Price
$prices = array( $product->get_variation_regular_price( 'min', true ), $product->get_variation_regular_price( 'max', true ) );
sort( $prices );
$saleprice = $prices[0] !== $prices[1] ? sprintf( __( 'fra %1$s', 'woocommerce' ), wc_price( $prices[0] ) ) : wc_price( $prices[0] );
if ( $price !== $saleprice ) {
$price = '' . $saleprice . ' ' . $price . '';
}
return $price;
}

i just cant make it to work with the new code there that @CookPete  made
