### ISSUE TITLE
attribute

### ISSUE THREAD

**Issue by filoslav** [woocommerce/woocommerce#16163]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by filoslav** [comment]
Hello. 

I am unable to add any attribute when I am creating a new product. 
I can create attributes but while I am creating a new product, after clicking on add attribute it still loading evend after 1 min it's still rounding and loading... I really don't know where is the problem. Tried to change theme, turned off the cache. But the issue is still there. 

<img width="1080" alt="snimka obrazovky 2017-07-18 o 15 52 24" src="https://user-images.githubusercontent.com/29380169/28320533-20bd0696-6bd1-11e7-8254-aa508810601b.png">
 
Thank you, Filip

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x
