### ISSUE TITLE
zero units available but "In stock" status

### ISSUE THREAD

**Issue by apb1963** [woocommerce/woocommerce#16167]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to woo>Reports>Stock>Out of Stock with zero units in stock
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...
"In Stock" status, with zero units in stock.

I was expecting...
"Out of Stock" status.

Additional Info:  File attached.  Note the one "Out of Stock" product.  This started as a zero  unit "In Stock" product like the others, and I clicked on the eye icon to view it.  I think I then tried to buy it at which point it failed properly (no units available), and when I came back to that window the status had changed to "Out of Stock" which is of course the correct status.

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://greetonix.com
Site URL: https://greetonix.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 96 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.20
PHP Post Max Size: 6 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: [sanitized]
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

1&1 WP Wizard: by 1&1 – 4.0.0
affilinet Performance Ads: by affilinet – 1.8.7
Akismet Privacy Policies: by Inpsyde GmbH – 1.1.2
Akismet Anti-Spam: by Automattic – 3.3.3
Code Snippets: by Shea Bunge – 2.8.6
Contact Form 7: by Takayuki Miyoshi – 4.8
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
TinyMCE Advanced: by Andrew Ozz – 4.6.3
Woocommerce CSV Import: by Allaerd Mensonides – 3.3.5
Woocommerce Table Rate Shipping: by JEM Plugins – 1.2.3
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.3
WooCommerce: by Automattic – 3.1.1
Categories to Tags Converter Importer: by wordpressdotorg – 0.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart
Checkout: #7 - /checkout
My account: #8 - /my-account

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently
![woostock](https://user-images.githubusercontent.com/6220724/28300139-34f60878-6b32-11e7-85d7-431e6930467a.png)
![woostock](https://user-images.githubusercontent.com/6220724/28324837-38e53dfa-6b91-11e7-9637-b8ccb7441848.png)

**Comment by mikejolley** [comment]
This is likely because you imported this product via "Woocommerce CSV Import: by Allaerd Mensonides – 3.3.5", so if that plugin did not set the stock status correctly on import, it wouldn't correct itself until viewed or saved by WC itself.
