### ISSUE TITLE
Invalid capability defined in wc_products_array_filter_editable

### ISSUE THREAD

**Issue by scottybo** [woocommerce/woocommerce#16160]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

The function below calls the current_user_can checking 'edit_product' against the current user's capabilities, but 'edit_product' is **not** a valid capability.

```
function wc_products_array_filter_editable( $product ) {

	return $product && is_a( $product, 'WC_Product' ) && current_user_can( 'edit_product', $product->get_id() );

}
```

Modifying the capability 'edit_products' fixes the issue.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
What makes you say that? It's the product equivalent of edit_post https://codex.wordpress.org/Function_Reference/map_meta_cap

**Comment by scottybo** [comment]
When looking at all the possible roles (using the "Members" plugin) "edit_product" is not listed as an option, see attached.

![edit role thirty wordpress](https://user-images.githubusercontent.com/11498904/28326576-0836d63a-6bd9-11e7-8152-522953dfe96b.png)

**Comment by mikejolley** [comment]
https://dl.dropboxusercontent.com/s/5pzzghqz1bqel2m/2017-07-19%20at%2014.42.png

From:

```
$data = get_userdata( get_current_user_id() );

if ( is_object( $data) ) {
    $current_user_caps = $data->allcaps;

    // print it to the screen
    echo '<pre>' . print_r( $current_user_caps, true ) . '</pre>';
}
```

So it's valid. They are created/applied to users when creating the post type - we set `map_meta_cap` to true. There is some explanation on https://codex.wordpress.org/Function_Reference/register_post_type

Thanks

**Comment by scottybo** [comment]
Thanks, makes sense - not sure how to close this thread? :)
