### ISSUE TITLE
"Force secure checkout" ticked disallows downloading of ANY downloadable products.

### ISSUE THREAD

**Issue by jobst** [woocommerce/woocommerce#16179]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce

      **I cannot test this as this is a real working site.**

- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

  **I would, but sorry I currently do not have the time, sorry.**

## Steps to reproduce the issue

1. Make your site HTTPS only (full site).
2. Under WooCoomerce->Settings->Checkout->Checkout options TICK "force secure checkout" 
3. Either have PREVIOUSLY purchased a downloadable product or purchase a NEW downloadable product
4. try download
5. Access forbidden!
6. Untick the WooCoomerce->Settings->Checkout->Checkout options->"force secure checkout" 
7. try download
8. It downloads perfectly

## Expected behavior and actual behavior

I am not the only person having this issue and everyone solved it by doing the above, e.g. this one:
https://wordpress.org/support/topic/403-forbidden-error-with-woocommerce-downloads/#post-9332005

I turned my site from https checkout/shop ONLY to FULL SITE https a few months ago (May) - as I am doing this with every site I have currently own. I did not expect the behavior and thought everything is fine ... there must have been lots of people giving up .... until one nice person told me she has a problem just a few days ago.

## Environment

```
<details>

### WordPress Environment ###
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
### Server Environment ###
Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 6000
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1
SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
### Database ###
WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
### Security ###
Secure connection (HTTPS): ✔
Hide errors from visitors: ✔
### Active Plugins (18) ###
BCG Anti Spam: by Jobst Schmalenbach – 2.0.0
BCG Enforce Passwords: by Jobst Schmalenbach 2013 – 2.3 
BCG MIGS Gateway: by Jobst Schmalenbach (C) 2013-2017 – 4.0.0
BCG WooCommerce Wishlist Member Integration: by Jobst Schmalenbach was WooThemes – 2.5.2
Google XML Sitemaps: by Arne Brachhold – 4.0.8
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.2
Karma Builder: by TrueThemes – 2.2.6
Manage Notification E-mails: by Virgial Berveling – 1.3.0
TinyMCE Advanced: by Andrew Ozz – 4.6.3
Widget Logic: by wpchefgadget alanft – 5.8.2
WishList Member™: by WishList Products – 2.92.3228
WooCommerce: by Automattic – 3.1.1
Sensei: by WooCommerce – 1.9.14 – 1.9.16 is available
Wordfence Security: by Wordfence – 6.3.12
Yoast SEO: by Team Yoast – 5.0.1
WP SMTP: by BoLiQuan – 1.1.9
### Settings ###
API Enabled: ✔
Force SSL: –
Currency: AUD (AUD $)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: configurable (configurable)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
virtual (virtual)
Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
### WC Pages ###
Shop base: #12 - /shop/
Cart: #13 - /cart/
Checkout: #14 - /checkout/
My account: #16 - /my-account/
### Theme ###
Name: Salesessentials Karma Child Theme 4.8.6
Version: 1.2
Author URL: 
Child Theme: ✔
Parent Theme Name: Karma
Parent Theme Version: 4.9.2
Parent Theme Author URL: http://www.truethemes.net
WooCommerce Support: ✔
### Templates ###
Overrides: PATH/archive-product.php
PATH/checkout/review-order.php
PATH/checkout/thankyou.php
PATH/content-single-product.php
PATH/emails/email-header.php
PATH/emails/email-order-details.php
PATH/emails/email-styles.php
PATH/myaccount/form-edit-account.php
PATH/myaccount/form-reset-password.php
PATH/myaccount/my-account.php
PATH/myaccount/my-downloads.php
PATH/order/order-details.php
PATH/single-product/meta.php
PATH/single-product/price.php
PATH/single-product-reviews.php

</details>
```

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
       Well this is NOT 100% achievable as I need SOME of the plugins
       However, turning MOST of the plugins off produces the SAME results
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
  I cannot test this as the layout of the "My Account Page" requires my theme (Karma)
- [x] I can reproduce this bug consistently
   I can do this on my development AND my real site in any browser consistently.

**Comment by mikejolley** [comment]
@jobst No issues locally. Setting makes no difference. Site is over https. 

Your report is incomplete. Is the WordPress site/home URL using HTTPS or are you using SSL by proxy? What is an example download URL? Is that relative or absolute?

**Comment by jobst** [comment]
@mikejolley
Site is Virtual Host Apache (2.2) based with its own document root, sits on one of my own servers. EV certificate from DigiCert. If you call site using HTTP it gets redirected to HTTPS (Apache conf files). Wordpress and Site address are defined the same "https://www.salesessentials.com".
Not sure what you mean by relative and absolute ... IMHO it's both relative (with respect to the document root) but also absolute is you specify https://www.salesessentials.com/wp-content/uploads/woocommerce_uploads/2013/08/Barrett-Lessons-Inisghts.pdf (this file is protected).

**Comment by mikejolley** [comment]
So with force SSL were you sent to "https://www.salesessentials.com/wp-content/uploads/woocommerce_uploads/2013/08/Barrett-Lessons-Inisghts.pdf" directly, or was the URL the WC download link still? Sounds like it could not read the file.

**Comment by jobst** [comment]
Assume I have Firefox open, I am logged in as a normal user and I am on the "My Account" page that displays links to downloadable content previously purchased through Woocommerce. In another browser (say Chrome) I am in the admin panel in Woocommerce settings.
Now, if I tick "force secure checkout" then save and then click on a downloadable content link it displays "access forbidden".  
Immediately afterwards I untick "force secure checkout" then save and then click the SAME link I clicked above - I will be able to download the file.
Nothing else has changed, just toggled the flag "force secure checkout".
I have set the setting "File Download Method" set to "Force Downloads" in both cases.

**Comment by jobst** [comment]
Ok, I did some debugging, I had some time to actually try this out on my development server.
The ONLY differences between my development and life server is hardware (real machine is a DELL Blade server while the development is a Custom Build) and off course the domain name.
Paths, software and configurations are identical (this is the whole point!).

In the code below is a function call to a function called "pinf", it's one of my debuggers printing arrays and outputting the data to particular files (so I can distinguish domains) and dont crowd other files. You can also see WHERE the calls to the debug functions are made and what is output, so you can compare.

I found that the problem is created within the function parse_file_path() in class-wc-download-handler (188) after I debugged all other functions as well. It seems that when the flag is ticked/on it returns the FULL URL (INCORRECT), if the flag is unticked/off it return the absolute path to the file (CORRECT). The real issue lies within the call of "parse_url", which creates the problem, you will see this in the debug lines.

I will provide the output of the debugging below for case 1 with "Force secure checkout" ticked (on) and case 2 "Force secure checkout" unticked (off).

**Here us the code for the function parse_file_path in class-wc-download-handler (188)**
`
  public static function parse_file_path( $file_path ) {
    $wp_uploads     = wp_upload_dir();
    $wp_uploads_dir = $wp_uploads['basedir'];
    $wp_uploads_url = $wp_uploads['baseurl'];

    pinf("------------------------------------------------------------ \n");
    pinf("FUNCTION ".__FUNCTION__." parms -> $file_path");
    pinf($wp_uploads, "\$wp_uploads -> ");

    // Replace uploads dir, site url etc with absolute counterparts if we can
    pinf("TEST1 >".network_site_url( '/', 'https' )."<");
    pinf("TEST2 >".network_site_url( '/', 'http' )."<");
    pinf("TEST3 >".site_url( '/', 'https' )."<");
    pinf("TEST4 >".site_url( '/', 'http' )."<");

    $replacements = array(
      $wp_uploads_url                  => $wp_uploads_dir,
      network_site_url( '/', 'https' ) => ABSPATH,
      network_site_url( '/', 'http' )  => ABSPATH,
      site_url( '/', 'https' )         => ABSPATH,
      site_url( '/', 'http' )          => ABSPATH,
    );
    pinf($replacements,"\$replacements ->");

    pinf("\$file_path BEF str_replace ->$file_path<-");
    $file_path        = str_replace( array_keys( $replacements ), array_values( $replacements ), $file_path );
    pinf("\$file_path AFT str_replace ->$file_path<-");

    $parsed_file_path = parse_url( $file_path );
    $remote_file      = true;

    pinf("FILE_PATH >".$file_path."<");
    pinf($parsed_file_path, "PARSED_FILE_PATH -> ");
    pinf("REMOTE FILE >".$remote_file."<");

    // See if path needs an abspath prepended to work
    if ( file_exists( ABSPATH . $file_path ) ) {
      $remote_file = false;
      $file_path   = ABSPATH . $file_path;

    } elseif ( '/wp-content' === substr( $file_path, 0, 11 ) ) {
      $remote_file = false;
      $file_path   = realpath( WP_CONTENT_DIR . substr( $file_path, 11 ) );

    // Check if we have an absolute path
    } elseif ( ( ! isset( $parsed_file_path['scheme'] ) || ! in_array( $parsed_file_path['scheme'], array( 'http', 'https', 'ftp' ) ) ) && isset( $parsed_file_path['path'] ) && file_exists( $parsed_file_path['path'] ) ) {
      $remote_file = false;
      $file_path   = $parsed_file_path['path'];
    }

    pinf(array( 'remote_file' => $remote_file,'file_path'   => $file_path), __FUNCTION__." RETURN VALUE -> ");

    return array(
      'remote_file' => $remote_file,
      'file_path'   => $file_path,
    );
  }
`

**OUPUT FOR CASE 1 - "Force secure checkout" ticked (on)**
`
2017-07-21 05:39:16 ------------------------------------------------------------ 

2017-07-21 05:39:16 FUNCTION parse_file_path parms -> http://dev.salesessentials.com/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf
2017-07-21 05:39:16 $wp_uploads ->  Array
(
    [path] => /PATH/www.salesessentials.com/htdocs/wp-content/uploads/2017/07
    [url] => https://dev.salesessentials.com/wp-content/uploads/2017/07
    [subdir] => /2017/07
    [basedir] => /PATH/www.salesessentials.com/htdocs/wp-content/uploads
    [baseurl] => https://dev.salesessentials.com/wp-content/uploads
    [error] => 
)

2017-07-21 05:39:16 TEST1 >https://dev.salesessentials.com/<
2017-07-21 05:39:16 TEST2 >https://dev.salesessentials.com/<
2017-07-21 05:39:16 TEST3 >https://dev.salesessentials.com/<
2017-07-21 05:39:16 TEST4 >https://dev.salesessentials.com/<
2017-07-21 05:39:16 $replacements -> Array
(
    [https://dev.salesessentials.com/wp-content/uploads] => /PATH/www.salesessentials.com/htdocs/wp-content/uploads
    [https://dev.salesessentials.com/] => /PATH/www.salesessentials.com/htdocs/
)

2017-07-21 05:39:16 $file_path BEF str_replace ->http://dev.salesessentials.com/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf<-
2017-07-21 05:39:16 $file_path AFT str_replace ->http://dev.salesessentials.com/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf<-
2017-07-21 05:39:16 FILE_PATH >http://dev.salesessentials.com/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf<
2017-07-21 05:39:16 PARSED_FILE_PATH ->  Array
(
    [scheme] => http
    [host] => dev.salesessentials.com
    [path] => /wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf
)

2017-07-21 05:39:16 REMOTE FILE >1<
2017-07-21 05:39:16 parse_file_path RETURN VALUE ->  Array
(
    [remote_file] => 1
    [file_path] => http://dev.salesessentials.com/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf
)
` 

**OUPUT FOR CASE 2 - "Force secure checkout" unticked (off)** 

`
2017-07-21 05:39:56 ------------------------------------------------------------ 

2017-07-21 05:39:56 FUNCTION parse_file_path parms -> http://dev.salesessentials.com/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf
2017-07-21 05:39:56 $wp_uploads ->  Array
(
    [path] => /PATH/www.salesessentials.com/htdocs/wp-content/uploads/2017/07
    [url] => https://dev.salesessentials.com/wp-content/uploads/2017/07
    [subdir] => /2017/07
    [basedir] => /PATH/www.salesessentials.com/htdocs/wp-content/uploads
    [baseurl] => https://dev.salesessentials.com/wp-content/uploads
    [error] => 
)

2017-07-21 05:39:56 TEST1 >https://dev.salesessentials.com/<
2017-07-21 05:39:56 TEST2 >http://dev.salesessentials.com/<
2017-07-21 05:39:56 TEST3 >https://dev.salesessentials.com/<
2017-07-21 05:39:56 TEST4 >http://dev.salesessentials.com/<
2017-07-21 05:39:56 $replacements -> Array
(
    [https://dev.salesessentials.com/wp-content/uploads] => /PATH/www.salesessentials.com/htdocs/wp-content/uploads
    [https://dev.salesessentials.com/] => /PATH/www.salesessentials.com/htdocs/
    [http://dev.salesessentials.com/] => /PATH/www.salesessentials.com/htdocs/
)

2017-07-21 05:39:56 $file_path BEF str_replace ->http://dev.salesessentials.com/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf<-
2017-07-21 05:39:56 $file_path AFT str_replace ->/PATH/www.salesessentials.com/htdocs/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf<-
2017-07-21 05:39:56 FILE_PATH >/PATH/www.salesessentials.com/htdocs/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf<
2017-07-21 05:39:56 PARSED_FILE_PATH ->  Array
(
    [path] => /PATH/www.salesessentials.com/htdocs/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf
)

2017-07-21 05:39:56 REMOTE FILE >1<
2017-07-21 05:39:56 parse_file_path RETURN VALUE ->  Array
(
    [remote_file] => 
    [file_path] => /PATH/www.salesessentials.com/htdocs/wp-content/uploads/woocommerce_uploads/2013/04/Creating-and-Becoming-Elite-Sales-Performers.pdf
)
`

**Comment by mikejolley** [comment]
So if you edit the download URL to use HTTPS you can avoid the problem. I'll see if we can add a code workaround too.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16214
