### ISSUE TITLE
define( ‘WOOCOMMERCE_CHECKOUT’, true ); does not add a correct behaviour

### ISSUE THREAD

**Issue by ZygimantasKairys** [woocommerce/woocommerce#16172]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [ ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  Do these lines in header.php 

    define( ‘WOOCOMMERCE_CHECKOUT’, true );
    echo do_shortcode(“[woocommerce_checkout]”);

    define( ‘WOOCOMMERCE_CART’, true );
    echo do_shortcode(“[woocommerce_cart]”)
2. In woocomerce settings do not select any cart or checkout page leave it blank.
3. Make and order and try to place order.

## Expected behavior and actual behavior

When I follow those steps, I see...

The checkout does not have a normal behaviour. Create account does not work, sign in for returning customer, when clicking place order and there are errors redirects to home page, also if there are no errors and you place order the order goes through but than it does not redirect to thank you page. 

I was expecting...

Expected to work checkout and cart on all pages as it's defined in the header, the customers would be able to checkout from any page. Used newest woocomerce and wordpress available. 

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
It doesn't work that way. The constant is set when on the page, you have no page. So all the functionality which links to cart/checkout pages cannot function.

You must set the pages.

**Comment by ZygimantasKairys** [comment]
Thanks Mike, so to make it clear there is no way to have checkout and cart combined in the header or footer so that would work on any page in the shop?

**Comment by mikejolley** [comment]
It's not unfortunately, without recreating those parts without a reliance on pages. I think thats how https://woocommerce.com/products/woocommerce-one-page-checkout/ does it.

When we get round to doing https://github.com/woocommerce/woocommerce/issues/10672 I'll try to make sure it is more flexible.

Thanks

**Comment by michaelaguiar** [comment]
I was able to make the cart / checkout work in the header on every page with minor changes.  You can see it on canabyst.com.

I ended up overriding the Shortcodes output function for cart / checkout, making minor changes for it to print the forms everywhere.
