### ISSUE TITLE
Api to create user not working

### ISSUE THREAD

**Issue by heemu9** [woocommerce/woocommerce#16176]
I am trying to create an API for mobile to signup with url:

http://demotwo.technitab.net/wp-json/wp/v2/users?username=thty&email=h34@gmail.com&password=123455

But I am getting error :

{
"code": "rest_cannot_create_user",
"message": "Sorry, you are not allowed to create new users.",
"data": {
"status": 401
}
}

Kindly Help.

Thanks in Advance

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#401-unauthorized
