### ISSUE TITLE
Wrong delivery selection issue

### ISSUE THREAD

**Issue by peterigz** [woocommerce/woocommerce#16170]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. It's a very hard to recreate bug but what I've found is: Customer from europe orders and uses Euro delivery
2. Customer from GB then tries to order but is shown the euro delivery option. 

I've watched out for a euro delivery order to come in and then opened a private browsing session and added a product to the basket and it indeed showed me euro delivery even though the setting in woocommerce is set to "Use Store Location" by default (which is GB). Strange thing is that changing the country to US set the delivery correctly to worldwide, but setting it back to GB incorrectly set it to Euro delivery again. I've tested this with all plugins disabled except woocommerce and the theme set to 2017. No caching plugins are being used (I disabled them to see if that was the cause). 

I've found I can fix the issue by setting debug shipping mode under shipping options, so that must narrow it down to the shipping cache. I have other woocommerce sites that also ship to Europe and yet I've never had this issue occur with them.

I've also tried this with geolocate both with/without caching enabled with the same results.

I can appreciate this might be hard to get to the bottom of, it certainly has me confused, but if there's any error logging in a specific place I can do to give some insight into what's going on then let me know. 

## Expected behavior and actual behavior

It should select the shipping option correctly according to the store location, instead it's selecting euro delivery if the previous order was to europe.

## Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://www.snugglebundl.co.uk
Site URL: https://www.snugglebundl.co.uk
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.21
PHP Post Max Size: 16 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.54.1
NSS/3.28.4

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: sb_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Redux Framework: by Team Redux – 3.6.5
ClickToAddress Auto-Complete Integration: by Crafty Clicks – 1.1.1
Contact Form 7: by Takayuki Miyoshi – 4.8
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.0.21.1
EWWW Image Optimizer: by Shane Bishop – 3.5.0
Fusion Builder: by ThemeFusion – 1.1.5
Fusion Core: by ThemeFusion – 3.1.5
Easy HTTPS (SSL) Redirection: by Tips and Tricks HQ – 1.6
WooCommerce Variation Report: by Infosoft Consultants – 3.3
WooCommerce Attribute Swatches: by Iconic  – 1.0.5
MailChimp for WooCommerce: by MailChimp – 2.0.0
Product Tabs Manager for WooCommerce: by BeRocket – 1.0.6
Simple 301 Redirects: by Scott Nellé – 1.07
Smart Variations Images: by David Rosendo – 3.2.14
Advanced Order Export For WooCommerce: by AlgolPlus – 1.4.2
WooCommerce Direct Variation Link: by WP BackOffice – 1.0.3
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.6
WooCommerce Secure Trading Gateway: by Illustrate Digital – 1.0.2
WooCommerce: by Automattic – 3.1.1
Wordfence Security: by Wordfence – 6.3.14
Yoast SEO: by Team Yoast – 5.0.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #141 - /shop/
Basket: #142 - /cart/
Checkout: #143 - /checkout/
My account: #144 - /my-account/

### Theme ###

Name: Snuggle Bundl
Version: 1.0.1
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.1.5
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php version 3.0.0 is out of date. The core version is 3.1.0
snuggle_theme/woocommerce/checkout/form-billing.php version 3.0.0 is out of date. The core version is 3.0.9
Avada/woocommerce/checkout/form-pay.php
snuggle_theme/woocommerce/checkout/form-shipping.php version 3.0.0 is out of date. The core version is 3.0.9
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
snuggle_theme/woocommerce/emails/customer-completed-order.php
snuggle_theme/woocommerce/emails/plain/customer-completed-order.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌Learn how to update
`
```
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Would need to at least see the zone setup. If you change the cart contents that will flush the cache too - try that.

**Comment by peterigz** [comment]
The zone setup is just United Kingdom as first zone, and then Europe as the other, then the standard "Locations not covered by your other zones". I can try changing the contents but obviously can't expect a customer to know to do that. Surely the shipping cache of one user can't be shared/used by another? Thanks.

**Comment by peterigz** [comment]
I had a cart open over night that had the correct delivery showing, I hit refresh just to make sure that all was still ok with debug mode and it went back to Europe delivery. The notice said customer matched as europe. So maybe not a caching issue then? I changed the location using the shipping calculator to USA and it showed world wide delivery, swtiched back to UK and it went back to Europe again. Very Strange! I also changed the cart - same result. So I've now deleted the United Kindom zone and recreated it and so far it's working ok again.

**Comment by peterigz** [comment]
Another quick update - I checked the dev server database which is a copy of live and took a look at the shipping zones table and noticed that both the europe and UK zones both had the same order value of 0. Would that explain why it would sometimes choose europe? I guess Uk is in eu so both would apply and then the order would determine which gets chosen, but if they're both the same then it becomes a coin flip of sorts.

Since i recreated the UK zone on the live server (and had to reorder UK to the top as it gets created at the bottom), the order in the live database now shows EU as 1 and UK as 0 which is correct so hopefully that's the issues completely resolved, but I wonder why they ended up both with 0 to start with?

**Comment by mikejolley** [comment]
@peterigz 

<del>Ok. This one does not seem to be reproducible. It would have been good to see the full zones setup (screenshots) to attempt to reproduce it, but given a basic UK zone first setup it works (I have this usually as standard). 

I did visit your site and have GB shipping.

If you manage to reproduce it again, you may want to double check you don't have cache on the server (varnish for example) as if misconfigured this could lead to sessions being shared. Read here https://docs.woocommerce.com/document/configuring-caching-plugins/ And contact me via email (on profile) so I can login and see for myself.</del>

Order of 0 for both would explain it. Let me take a look.

**Comment by mikejolley** [comment]
Sorted. :trollface: 

See https://github.com/woocommerce/woocommerce/pull/16180

Thanks

**Comment by peterigz** [comment]
Great, thanks!
