### ISSUE TITLE
Catagories are shown in browser not in apk app

### ISSUE THREAD

**Issue by sathyababuram** [woocommerce/woocommerce#16177]
Hi All,
I have a live woocommerce site and i have converted the site into mobile app by using ionic woocommerce app. I have generated key and i as test in by browser ,its work well all the categories can be visible in my browser.

When i was built the app in android platform , and i intslled the app in my phone . I cant see the categories and products. The page is blank in my apk. Can anyone help me with this problem?

**Comment by mikejolley** [comment]
You'll need to contact ionic about this - I have no idea how their app and code works.
