### ISSUE TITLE
Bug on product exports

### ISSUE THREAD

**Issue by ferfelipetto** [woocommerce/woocommerce#16171]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create at least two products in the store and in the description field place text with at least two rows (can be line break or paragraph)
2. Export the products using the woocommerce native product exporter or some premium export plugin.
3. 
Open the .csv file in some .csv preview program or import it into excel.

## Expected behavior and actual behavior

When I follow those steps, I see...

The second line of product description 1 stands as the id of a new product. So the two products exported end up turning 4 products in the .csv file with the data all out of place.

I was expecting...

The file generated when being opened in a .csv display program should contain two product lines, with the data fields id, description, price, stock, etc in their respective columns.

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```

`
### WordPress Environment ###

Home URL: https://loja.grafinorte.com.br
Site URL: https://loja.grafinorte.com.br
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: ❌ 40 MB - Nós recomendamos configurar pelo menos 64MB de memória. Mais informações: Acrescentando memória alocada para o PHP
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR

### Server Environment ###

Server Info: nginx/1.12.1
PHP Version: 5.6.31
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.56 - Nós recomendamos utilizar pelo menos a versão 5.6 do MySQL. Mais informações: Requerimentos do WordPress
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: gn_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Gravity Forms: por rocketgenius – 2.2.3
Admin Menu Editor: por Janis Elsts – 1.8
Akismet Anti-Spam: por Automattic – 3.3.3
All-in-One WP Migration: por ServMask – 6.52
Cielo WooCommerce - Solução Webservice: por Gabriel Reguly
Claudio Sanches
Paulo Vieira – 4.0.14

Desativar Comentários: por Samir Shah – 1.7
Duplicate Post: por Enrico Battocchi – 3.2
Gravity Forms CSS Ready Class Selector: por Brad Vincent – 1.1
Tradução (Loco): por Tim Whitlock – 2.0.14
MailChimp for WordPress: por ibericode – 4.1.5
Maintenance: por fruitfulcode – 3.5.1
Nginx Helper: por rtCamp – 1.9.10
Filtro de produtos WooCommerce: por Mihajlovic Nenad – 6.3.0
Redis Object Cache: por Till Krüss – 1.3.5
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 2.2.6
Simple Sitemap: por David Gwyer – 2.1
Snapshot Pro: por WPMU DEV – 3.1.2
Tawk.to Live Chat: por Tawkto – 0.3.1
Ultimate Branding: por WPMU DEV – 1.8.8
WooCommerce Weight Based Shipping: por weightbasedshipping.com – 5.0.9
Woo Gerencianet Oficial: por Gerencianet – 0.5.3
Woo Import Export: por VJInfotech – 2.4
Woo Mercado Pago Module: por Mercado Pago – 2.2.10
WooCommerce Fundos de Conta: por WooCommerce – 2.1.6
WooCommerce Correios: por Claudio Sanches – 3.4.1
WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.6.0
WooCommerce Order Status Manager: por SkyVerge – 1.7.1
WooCommerce PagSeguro: por Claudio Sanches – 2.12.5
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 1.6.6
WooCommerce TM Extra Product Options: por themecomplete – 4.5.3
WooCommerce Upload Files: por Lagudi Domenico – 24.7
WooCommerce: por Automattic – 3.1.1
WooSidebars: por WooThemes – 1.4.3
WP Defender Pro: por WPMU DEV – 1.6.2
Hummingbird Pro: por WPMU DEV – 1.5.4
WP Smush Pro: por WPMU DEV – 2.7.3.1
WP Upload Restriction: por Sajjad Hossain – 2.1.0
WPMU DEV Dashboard: por WPMU DEV – 4.3.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base da loja: #5 - /produtos/
Carrinho: #8 - /carrinho/
Finalizar compra: #10 - /finalizar-compra/
Minha conta: #14 - /minha-conta/

### Theme ###

Name: Grafinorte
Version: 3.5
Author URL: 
Child Theme: ✔
Parent Theme Name: Grafinorte
Parent Theme Version: 3.5
Parent Theme Author URL: https://felipettomarketing.com.br
WooCommerce Support: ✔

### Templates ###

Overrides: grafinorte/woocommerce/archive-product.php
grafinorte/woocommerce/cart/cart-empty.php versão 2.0.0 está desatualizado. A versão do core é 3.1.0
grafinorte/woocommerce/cart/cart.php versão 3.0.3 está desatualizado. A versão do core é 3.1.0
grafinorte/woocommerce/checkout/form-checkout.php
grafinorte/woocommerce/checkout/form-coupon.php
grafinorte/woocommerce/checkout/thankyou.php
grafinorte/woocommerce/content-product.php
grafinorte/woocommerce/content-product_cat.php
grafinorte/woocommerce/content-single-product.php
grafinorte-child/woocommerce/emails/customer-completed-order.php
grafinorte-child/woocommerce/emails/customer-on-hold-order.php
grafinorte-child/woocommerce/emails/customer-processing-order.php
grafinorte/woocommerce/global/breadcrumb.php
grafinorte/woocommerce/global/quantity-input.php
grafinorte/woocommerce/global/wrapper-end.php
grafinorte/woocommerce/global/wrapper-start.php
grafinorte/woocommerce/loop/loop-end.php
grafinorte/woocommerce/loop/loop-start.php
grafinorte/woocommerce/loop/orderby.php
grafinorte/woocommerce/loop/pagination.php
grafinorte/woocommerce/loop/result-count.php
grafinorte/woocommerce/loop/sale-flash.php
grafinorte/woocommerce/myaccount/form-login.php
grafinorte/woocommerce/myaccount/navigation.php
grafinorte/woocommerce/notices/error.php
grafinorte/woocommerce/notices/notice.php
grafinorte/woocommerce/notices/success.php
grafinorte-child/woocommerce/order/order-details.php
grafinorte/woocommerce/product-searchform.php
grafinorte/woocommerce/single-product/photoswipe.php
grafinorte/woocommerce/single-product/price.php
grafinorte/woocommerce/single-product/product-image.php versão 3.0.2 está desatualizado. A versão do core é 3.1.0
grafinorte/woocommerce/single-product/product-thumbnails.php versão 3.0.2 está desatualizado. A versão do core é 3.1.0
grafinorte/woocommerce/single-product/related.php
grafinorte/woocommerce/single-product/review.php
grafinorte/woocommerce/single-product/sale-flash.php
grafinorte/woocommerce/single-product/share.php
grafinorte/woocommerce/single-product/short-description.php
grafinorte/woocommerce/single-product/tabs/tabs.php
grafinorte/woocommerce/single-product/title.php
grafinorte/woocommerce/single-product/up-sells.php
grafinorte/woocommerce/single-product-reviews.php
grafinorte/woocommerce/single-product.php

Outdated Templates: ❌Aprenda como atualizar
`
</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
If you're reporting an issue with `Woo Import Export: por VJInfotech – 2.4`, thats not ours....

Our exporter doesn't seem to have this issue - all fields are wrapped correctly. You can even see our dummy data which is exported with it https://github.com/woocommerce/woocommerce/blob/master/dummy-data/dummy-data.csv

Example content: 
<img width="719" alt="2017-07-18 at 21 39" src="https://user-images.githubusercontent.com/90977/28338669-94e329e4-6c01-11e7-98b0-96a1bdf97337.png">

Resulting CSV in numbers: 
<img width="992" alt="2017-07-18 at 21 40" src="https://user-images.githubusercontent.com/90977/28338719-b9c9220e-6c01-11e7-8d57-2ea5e51566d8.png">

**Comment by ferfelipetto** [comment]
No, as I said in the description the same problem happens using the native tool to export woocommerce products

**Comment by mikejolley** [comment]
Send us your CSV.

**Comment by mikejolley** [comment]
@ferfelipetto We need 2 things to proceed here.

1. The CSV you exported so I can compare it to mine.
2. Confirmation it was exported without other plugins active, just WooCommerce, with status report to back it up. The other exporter could still be affecting other exports.

**Comment by ferfelipetto** [comment]
Attached is my .csv exported with the native Woo tool after disabling the other export plugin.
Ps .: product id 6181 is exactly the same as all others, I just left it with only one line in the description field. It is correct. Others that have two lines of description are wrong.

Many thanks for your patience to investigate!

Below my system report

`
### WordPress Environment ###

Home URL: https://loja.grafinorte.com.br
Site URL: https://loja.grafinorte.com.br
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR

### Server Environment ###

Server Info: nginx/1.12.1
PHP Version: 5.6.31
PHP Post Max Size: 100 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.57 - Nós recomendamos utilizar pelo menos a versão 5.6 do MySQL. Mais informações: Requerimentos do WordPress
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: gn_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Gravity Forms: por rocketgenius – 2.2.3
Admin Menu Editor: por Janis Elsts – 1.8
Akismet Anti-Spam: por Automattic – 3.3.3
All-in-One WP Migration: por ServMask – 6.52
Cielo WooCommerce - Solução Webservice: por Gabriel Reguly
Claudio Sanches
Paulo Vieira – 4.0.14

Desativar Comentários: por Samir Shah – 1.7
Duplicate Post: por Enrico Battocchi – 3.2
Gravity Forms CSS Ready Class Selector: por Brad Vincent – 1.1
Tradução (Loco): por Tim Whitlock – 2.0.14
MailChimp for WordPress: por ibericode – 4.1.5
Maintenance: por fruitfulcode – 3.5.1
Nginx Helper: por rtCamp – 1.9.10
Filtro de produtos WooCommerce: por Mihajlovic Nenad – 6.3.0
Redis Object Cache: por Till Krüss – 1.3.5
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 2.2.6
Simple Sitemap: por David Gwyer – 2.1
Snapshot Pro: por WPMU DEV – 3.1.2
Tawk.to Live Chat: por Tawkto – 0.3.1
Ultimate Branding: por WPMU DEV – 1.8.8
WooCommerce Weight Based Shipping: por weightbasedshipping.com – 5.0.9
Woo Gerencianet Oficial: por Gerencianet – 0.5.3
Woo Mercado Pago Module: por Mercado Pago – 2.2.10
WooCommerce Fundos de Conta: por WooCommerce – 2.1.6
WooCommerce Correios: por Claudio Sanches – 3.4.1
WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.6.0
WooCommerce Order Status Manager: por SkyVerge – 1.7.1
WooCommerce PagSeguro: por Claudio Sanches – 2.12.5
WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 1.6.6
WooCommerce TM Extra Product Options: por themecomplete – 4.5.3
WooCommerce Upload Files: por Lagudi Domenico – 24.7
WooCommerce: por Automattic – 3.1.1
WooSidebars: por WooThemes – 1.4.3
WP Defender Pro: por WPMU DEV – 1.6.2
Hummingbird Pro: por WPMU DEV – 1.5.4
WP Smush Pro: por WPMU DEV – 2.7.3.1
WP Upload Restriction: por Sajjad Hossain – 2.1.0
WPMU DEV Dashboard: por WPMU DEV – 4.3.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base da loja: #5 - /produtos/
Carrinho: #8 - /carrinho/
Finalizar compra: #10 - /finalizar-compra/
Minha conta: #14 - /minha-conta/

### Theme ###

Name: Grafinorte
Version: 3.5
Author URL: 
Child Theme: ✔
Parent Theme Name: Grafinorte
Parent Theme Version: 3.5
Parent Theme Author URL: https://felipettomarketing.com.br
WooCommerce Support: ✔

### Templates ###

Overrides: grafinorte/woocommerce/archive-product.php
grafinorte/woocommerce/cart/cart-empty.php
grafinorte/woocommerce/cart/cart.php
grafinorte/woocommerce/checkout/form-checkout.php
grafinorte/woocommerce/checkout/form-coupon.php
grafinorte/woocommerce/checkout/thankyou.php
grafinorte/woocommerce/content-product.php
grafinorte/woocommerce/content-product_cat.php
grafinorte/woocommerce/content-single-product.php
grafinorte-child/woocommerce/emails/customer-completed-order.php
grafinorte-child/woocommerce/emails/customer-on-hold-order.php
grafinorte-child/woocommerce/emails/customer-processing-order.php
grafinorte/woocommerce/global/breadcrumb.php
grafinorte/woocommerce/global/quantity-input.php
grafinorte/woocommerce/global/wrapper-end.php
grafinorte/woocommerce/global/wrapper-start.php
grafinorte/woocommerce/loop/loop-end.php
grafinorte/woocommerce/loop/loop-start.php
grafinorte/woocommerce/loop/orderby.php
grafinorte/woocommerce/loop/pagination.php
grafinorte/woocommerce/loop/result-count.php
grafinorte/woocommerce/loop/sale-flash.php
grafinorte/woocommerce/myaccount/form-login.php
grafinorte/woocommerce/myaccount/navigation.php
grafinorte/woocommerce/notices/error.php
grafinorte/woocommerce/notices/notice.php
grafinorte/woocommerce/notices/success.php
grafinorte-child/woocommerce/order/order-details.php
grafinorte/woocommerce/product-searchform.php
grafinorte/woocommerce/single-product/photoswipe.php
grafinorte/woocommerce/single-product/price.php
grafinorte/woocommerce/single-product/product-image.php
grafinorte/woocommerce/single-product/product-thumbnails.php
grafinorte/woocommerce/single-product/related.php
grafinorte/woocommerce/single-product/review.php
grafinorte/woocommerce/single-product/sale-flash.php
grafinorte/woocommerce/single-product/share.php
grafinorte/woocommerce/single-product/short-description.php
grafinorte/woocommerce/single-product/tabs/tabs.php
grafinorte/woocommerce/single-product/title.php
grafinorte/woocommerce/single-product/up-sells.php
grafinorte/woocommerce/single-product-reviews.php
grafinorte/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
Your CSV is valid: 
<img width="1357" alt="2017-07-20 at 12 26" src="https://user-images.githubusercontent.com/90977/28415240-c1c24a08-6d46-11e7-824e-c965e2313287.png">

Tried Open Office? Google sheets?

**Comment by ferfelipetto** [comment]
Hey, on google sheets opened properly! Many thanks for your patience in helping. Thank you very much!

**Comment by mikejolley** [comment]
I don't have Excel to test because I'm on mac, but it looks like the CSV is fine anyway :) It may be something to do with the UTF characters, but good to hear other spreadsheet apps work.
