### ISSUE TITLE
Downloadable Products Not Being Made Accessible After Order Status Changes from PayPal

### ISSUE THREAD

**Issue by composerbdaniel** [woocommerce/woocommerce#16174]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Configure a downloadable product in the WooCommerece Catalog
2. Add the product to the cart and proceed to checkout.  In a separate browser window (track the status of the order and the accessibility of the downloadable file at each step).
3. Pay for product with Paypal and make sure that Paypal is configured to return the IPN (Instant Payment Notification)
4. Once payment is made at PayPal, Return to Merchant.
5. See that the order has been completed. Also see that the order received the IPN from paypal (a note on the right hand side of the screen).
6. Go to WooCommerce Orders section on the backend.  See that the order has been marked as Completed, but the downloadable file is not accessible.

## Expected behavior and actual behavior

When I follow those steps, I see the completed order, but the file is not accessible.  I do have the setting 'Grant access to downloadable products after payment' checked.

I was expecting ... the file that I payed for to be accessible when I returned to the Downloads section of my site.
I have included an example order where I tracked this action. Look at the order history comments on the right hand side.

[woocommerce_download_issue_example.pdf](https://github.com/woocommerce/woocommerce/files/1157777/woocommerce_download_issue_example.pdf)

## Environment

`
### WordPress Environment ###

Home URL: https://knightwindmusic.com
Site URL: https://knightwindmusic.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

ManageWP - Worker: by ManageWP – 4.2.20
Carousel Slider: by Sayful Islam – 1.7.2
CC Child Pages: by Caterham Computing – 1.35
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.10
Contact Form 7: by Takayuki Miyoshi – 4.8
Posts in Page: by IvyCat
Inc. – 1.3.0

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Simple Audio Player: by Marty – 0.2
Simple Facebook Plugin: by topdevs.net – 1.5
Storefront Product Sharing: by WooThemes – 1.0.4
Tabby Responsive Tabs: by cubecolour – 1.2.3
WooCommerce Grid / List toggle: by jameskoster – 1.1.0
WooCommerce Social Login: by SkyVerge – 2.1.0 – 2.3.1 is available
WooCommerce: by Automattic – 3.1.1
WP Clone by WP Academy: by WP Academy – 2.2.4
WPS Hide Login: by Remy Perona for WPServeur – 1.1.7

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #72 - /catalog/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront Child
Version: 1.0.0
Author URL: http://knightwindmusic.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.4
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

I was able to hack a workaround by adding to the woocommerce/includes/wc-order-functions.php file.

If you go down to line 409~410, you will see the code that attaches the downloadable permissions action to the woocommerce_order_status_completed and woocommerce_order_status_processing actions. By tracing back through the checkout process, I saw that line 979 of the main checkout class was not firing the woocommerce_order_status_completed action. I believe that it called the order processed action after it got confirmation from PayPal that the payment was successful.

I have to find the following action: and make it call the completed action above.
woocommerce_checkout_order_processed.

I added the following line to the Order-funtions file right below the other two add_actions:

add_action('woocommerce_checkout_order_processed', 'wc_downloadable_product_permissions' );

When the checkout completes via PayPal and the order is set to status processed, it calls the downloadable product permissions action and everything works like it should.

**Comment by mikejolley** [comment]
`woocommerce_order_status_completed` fires when a status change occurs, in this case 'completed'. If you have a note in the order saying the status change happened, but nothing was granted, you need to check the error logs to see if there is a reason for this.

**Comment by composerbdaniel** [comment]
Were you able to recreate my issue?  Where are the log files located in a
typical install of woocommerce.  I will check them out.

Thanks,

Ben

**Comment by mikejolley** [comment]
No I wasn't, but I can only use PDT locally. Find the PHP error log if you can.

**Comment by mikejolley** [comment]
No other reports of this I can find, and it seems no-reproducible. I'm confident that if you find the PHP error log the cause will be apparent.

https://snapcreek.com/blog/wordpress-error-log-friend/ 
https://codex.wordpress.org/Debugging_in_WordPress
https://en-gb.wordpress.org/plugins/error-log-monitor/

**Comment by composerbdaniel** [comment]
so you are saying that when you test WordPress and woocommerce with PayPal
and you get the ipn the download becomes available?

thanks,

Ben

**Comment by mikejolley** [comment]
Yes, as soon as the status changes because it is all part of that action.

**Comment by composerbdaniel** [comment]
Dear WooCommerce Support,

Just to recap: here is the code that I edited in order-functions.php
-------------------------------------------------------
add_action( 'woocommerce_order_status_completed',
'wc_downloadable_product_permissions' ); //code originally here
add_action( 'woocommerce_order_status_processing',
'wc_downloadable_product_permissions' ); //code originally here

//Ben Daniel Added this line to make the processed status trigger the
downloadable product permissions
//added processed (so when the call from PayPal is received with the IPN,
the customer
//will be granted access to the downloaded purchase
add_action('woocommerce_checkout_order_processed',
'wc_downloadable_product_permissions' );
-------------------------------------------------------
I REMOVED the the call that I entered and tried to buy a downloadable
product on GoDaddy. I got the following error message in the debug log.
They use a caching server on their managed WordPress sites.

[22-Jul-2017 15:32:35 UTC] PHP Fatal error:  Call to undefined method
APCu_Object_Cache::incr2() in
/home/content/a2pewpnaspod04_data01/88/41209588/html/wp-content/object-cache.php
on line 242
[22-Jul-2017 15:32:46 UTC] PHP Fatal error:  Call to undefined method
APCu_Object_Cache::incr2() in
/home/content/a2pewpnaspod04_data01/88/41209588/html/wp-content/object-cache.php
on line 242
[22-Jul-2017 15:35:05 UTC] PHP Fatal error:  Call to undefined method
APCu_Object_Cache::incr2() in
/home/content/a2pewpnaspod04_data01/88/41209588/html/wp-content/object-cache.php
on line 242
[22-Jul-2017 15:35:17 UTC] PHP Fatal error:  Call to undefined method
APCu_Object_Cache::incr2() in
/home/content/a2pewpnaspod04_data01/88/41209588/html/wp-content/object-cache.php
on line 242

When I put my code back in, the system works as desired.  Are you sure the
word 'processing' in the second code line above should not be 'processed'?

Thank you,

Ben

**Comment by composerbdaniel** [comment]
I apologize.  I started using the Order Status Control and for some reason
its working as it should now.

This ticket can remain closed. Thank you for your attention.

Best,

Ben

On Sat, Jul 22, 2017 at 11:47 AM, Benjamin Daniel <composerbdaniel@gmail.com
