### ISSUE TITLE
Can't change woocommerce language

### ISSUE THREAD

**Issue by tymeq1** [woocommerce/woocommerce#16173]
I tried many ways to fix this problem, but none of them don't work. I set language to polish on dashboard and upload .mo and .po files named woocommerce-pl_PL to languages/plugins folder (and also to woocommerce/i18n/languages) and shop language was still english. I tried also with Loco and Say What plugins, but it's still the same.

**Comment by mikejolley** [comment]
See https://wordpress.org/support/topic/updating-translations-after-updates/ and https://docs.woocommerce.com/document/woocommerce-localization/
