### ISSUE TITLE
Inconsistent refunded tax display

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#16183]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. An order exists. There is a tax amount paid on the order that is > 0
2. Refund an item on the order. The tax is shown as refunded on the order ![see screen shot](http://cld.wthms.co/lgt4wp+)
3. The customer does not see the tax refunded on their "My Account" page ![see screen shot](http://cld.wthms.co/kDJzZx+)

## Expected behavior and actual behavior

When I follow those steps, I see...
That the tax is not struck-through on the refund summary
I was expecting...
That the tax is displayed as struck-through and $0 (or whatever is left over after the refund)
## Environment

<details>
```
### WordPress Environment ###

Home URL: http://local.woo
Site URL: http://local.woo
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.8
PHP Version: 7.0.14-2+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.53 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

WooCommerce Stripe Gateway: by WooCommerce – 3.2.2
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.15
WooCommerce: by Automattic – 3.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
@WillBrubaker Clearly the backend view and frontend view are not displayed in the same way (different totals and line etc), so why exactly is this expected? And which view is 'preferred'? This is a lot of work for seemingly little benefit.

**Comment by WillBrubaker** [comment]
@mikejolley this came in via live chat, the person I was chatting with has the link to this issue so hopefully they will chime in here. As I understand it, they would expect that the way that the refund is presented to the customer should reflect the portion of the tax that was refunded as well with the original amount struck through and the total amount of tax paid (after the refund) shown - basically mimicking what is shown on the order in the admin.

**Comment by mikejolley** [comment]
I see, thanks for explaining. This looks a little more involved due to the way emails are structured so we should probably roll this into https://github.com/woocommerce/woocommerce/issues/10704 and do it all at once (requires template changes anyway). We'll prioritise that/roadmap it in the near future.

For now this this won't be changed, however since one view is primarily for customers, and one is for admin, it probably won't be noticed anyway unless you're testing stuff :)
