### ISSUE TITLE
Shipping Method stays un-selected #3

### ISSUE THREAD

**Issue by TarasDerenko** [woocommerce/woocommerce#16187]
Hi guys,
After update woocommerce I have this:
standart theme "Twenty Fifteen"
https://drive.google.com/file/d/0B34ArrGZnLmlRlNTX0FSbWZuMEE/view
Please help!
Thanks

**Comment by mikejolley** [comment]
Please don't ignore the details required on the new issue form - it just means I want to label this invalid and close :)

My guess, the ajax endpoint is not working. Without a link I cannot check. Usually settings > permalinks and save will resolve it.

**Comment by TarasDerenko** [comment]
Very sorry!
I did everything that you wrote but do not work again.I Disconnected all the plugins except the woocommerce, the same.
When I return to the old database, it works. But this does not suit me, many new products and posts are added. Thank you!

**Comment by TarasDerenko** [comment]
And "$chosen_method" in "checked( $method->id, $chosen_method, false )" always return NULL
