### ISSUE TITLE
get_product() deprecated message and template content (order/order-details.php).

### ISSUE THREAD

**Issue by jobst** [woocommerce/woocommerce#16194]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce
- [ x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
  sorry I do not have the time in the moment, also I have problems with my github repos.

## Steps to reproduce the issue

1. edit PLUGINDIR/woocommerce/templates/order/order-details.php
2. goto line 51
3. $product = apply_filters( 'woocommerce_order_item_product', $item->get_product(), $item );
4. raises deprecated error

## Expected behavior and actual behavior

I have copied this template to my theme directory as IS and made some changes.
It raises "The get_product function is deprecated ... "

It should be:
$product = apply_filters( 'woocommerce_order_item_product', wc_get_product, $item );

## Environment

N/A 

## Isolating the problem

N/A

**Comment by mikejolley** [comment]
`get_product` function is deprecated, but `$item->get_product()` is not. You'd get the notice before copying the template across if it were a problem. Maybe you have changed the template, or you're using `woocommerce_order_item_product` filter somewhere?
