### ISSUE TITLE
How to set Sequential Order Numbers to Woocommerce orders without plugin(using source code)

### ISSUE THREAD

**Issue by sudhakar1207** [woocommerce/woocommerce#16197]

**Comment by mikejolley** [comment]
This is not the place to ask for customisations. There are plugins for a reason.

**Comment by sudhakar1207** [comment]
I already used more plugins due to this my website is very slow thatsway i asked to help me with source code

**Comment by mikejolley** [comment]
Code in a plugin is no different to code of your own doing.

**Comment by sudhakar1207** [comment]
ok
can you suggest me

**Comment by sudhakar1207** [comment]
ok
