### ISSUE TITLE
Product feed issues

### ISSUE THREAD

**Issue by laravelcoder** [woocommerce/woocommerce#16207]
I have tried to use your woocommerce feed url format and it works for the most part but it only displays 5 products and we have alot more then that. 

https://www.oursite.com/feed/?post_type=product

do you have any documentation on this so i can trouble shoot why they all do not display?

also is there a way to include reviews on the feed?

**Comment by mikejolley** [comment]
This feed is generated by WordPress. We don't fully control the content - I know you can use filters to insert other content however.

Per page is set by Settings > Reading > Syndication feeds show the most recent.

You can also pass 'posts_per_page' to the querystring.

If you want more data, use the REST API instead.
