### ISSUE TITLE
WC_Product_Variation::get_attributes is the same as WC_Product::get_attributes. Unnecessary?

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce#16206]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Look at [get_attributes](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-variation.php#L435-L437) in Product variation
2. See that the method is [not redeclared in its parent class](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-simple.php) (`WC_Product_Simple`)
3. See that the same method is [exactly the same on its second ancestor](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L515-L517), in the abstract `WC_Product`

## Expected behavior and actual behavior

It's mostly a question on why that specific method is redeclared. If it wasn't there, the abstract's version would be inherited anyways in the same manner.

**Comment by mikejolley** [comment]
They differed in a previous version, so yes it's unnecessary now. Feel free to PR these types of things.

Fixed in https://github.com/woocommerce/woocommerce/pull/16213

**Comment by javorszky** [comment]
Thank you. I will in the future. I thought I missed something, hence the question without the PR.
