### ISSUE TITLE
Public API for WC_Auth::create_keys()

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#16208]
I'd like to suggest a public API or wrapper for the protected method `WC_Auth::create_keys()`. There's also `WC_Ajax::update_api_key` for creating a key/secret pair for API authentication, but it seems hard to use as a PHP callback. I'm attempting to generate a key pair on plugin activation for a service integration, and `WC_Auth::create_keys()` would be perfect except that it's protected.

**Comment by javorszky** [comment]
Would be a great candidate for a `wc_` function. Currently I'd copy the functionality that's in `WC_Ajax::update_api_key` to achieve the same result, which would break as soon as the method changes and I haven't updated my copy of it.

**Comment by helgatheviking** [comment]
Yeah, copying the function is what I'm trying to avoid for exactly the reason @javorski outlined.

**Comment by mikejolley** [comment]
This will be covered by https://github.com/woocommerce/woocommerce/issues/15601 since it will include getters, setters, and helpers once implemented. That other issue lacks description though I know :)

**Comment by helgatheviking** [comment]
Great, thanks Mike.
