### ISSUE TITLE
Rest API with attribute

### ISSUE THREAD

**Issue by fgauttron** [woocommerce/woocommerce#16216]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. https://www.example.org/wp-json/wc/v2/products?attribute_term=165&consumer_key=ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&consumer_secret=cs_yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
2. The parameters attribute or attribute_term are not recognized. The other parameters like category are recognized

**Comment by mikejolley** [comment]
```
attribute | string | Limit result set to products with a specific attribute.

attribute_term | string | Limit result set to products with a specific attribute term ID (required an assigned attribute).
```

Both are required. Your request has just attribute_term.

**Comment by fgauttron** [comment]
Thank you you solved my problem.
