### ISSUE TITLE
Font size of category

### ISSUE THREAD

**Issue by Reihorlicks** [woocommerce/woocommerce#16210]
I have an issue of changing my font size for my product category

Currently i have a to change the outlook of my category.  How can i change my font size?

.products li.product-category {
display:inline-block;
margin:5px;
padding: 1%;
width: 15%;   
clear:none !important ;
vertical-align: top;
text-align: center;
font-size: 0.8em;
}
@media screen and (max-width:480px) {
.products li.product-category {
display:inline-block;
margin:10px;
padding: 1%;
width: 15%;   
clear:none !important ;
vertical-align: top;
text-align: center;

}
}

**Comment by mikejolley** [comment]
> This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)

CSS font size property will work, you just need to be targeting the correct element. 

http://www.wpbeginner.com/wp-tutorials/basics-of-inspect-element-with-your-wordpress-site/
