### ISSUE TITLE
Bookable product - availability check fails

### ISSUE THREAD

**Issue by sbehrendt81** [woocommerce/woocommerce#16217]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. fresh installation of WP 
2. fresh installation and activation of woocommerce and woocommerce bookings
3. creation of a bookable product "Training Session" (duration of slot: 20 minutes)
4. opening the product page in frontend (loading time is good)
5. selection of date and timeslot of bookable product
6. booking product (hitting the button)

## Expected behavior and actual behavior

When I follow those steps, I see...
- loading of product page for all bookable products takes 2 minutes and longer when one booking of a bookable product has occurred 
- whole day (selected by customer above) is blocked and cannot be selected for booking further appointments
- product pages for other product types (e.g. simple product) still load fast

I was expecting...
- only selected timeslot is blocked. day can still be selected in calendar for booking other appointments
- fast loading of product page

## Environment

!!!! when doing this on a local machine, everything works fine. doing this on the live server results in the error. only two differences are
- php version: 5.6.31 on live server -- 5.6.8 on localhost
- PHP Time Limit: 0 on live sever -- 30 on localhost

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
`
### WordPress Environment ###

Home URL: https://liemafit-personal-training.de
Site URL: https://liemafit-personal-training.de
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.2.31 (Unix)
PHP Version: 5.6.31
PHP Post Max Size: 48 MB
PHP Time Limit: 0
PHP Max Input Vars: 4000
cURL Version: 7.50.3
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp2_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Bookings: von Automattic – 1.10.5
WooCommerce: von Automattic – 3.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #4 - /shop/
Warenkorb: #5 - /warenkorb/
Kasse: #6 - /kasse/
Mein Konto: #7 - /mein-konto/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://de.wordpress.org/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
```
[x ] This is not a usage question (Those should be directed to the community, unless this is a question about a premium plugin in which you should use the helpdesk for official extensions or contact the author of 3rd party extensions)
```

**Comment by sbehrendt81** [comment]
sorry. the website 
https://woocommerce.com/my-account/create-a-ticket/ 
showed no ticket option when using chrome. only able to open ticket in intenet explorer.
firefox shows chat option. 
thats confusing
