### ISSUE TITLE
WC 3.1.1 Adding an image to a Product Category fails, with no image being added.

### ISSUE THREAD

**Issue by lifeforceinst** [woocommerce/woocommerce#16222]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question 
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. On Site with latest WP & WC installed.
2.  Make sure all plugins are disabled except for WC.
3. Change theme to 2017.
4. Goto WooCommerce > Status > Tools and perform following actions to clear transients, reset most items just to make sure nothing could be causing problems.
5. Goto WooCommerce > Status > Check all is green
6. Goto Products > Categories
7.  With no categories present create a new category, by typing in: test1 as the name, test 1 as the slug, then This is a test category as the description.  Then click Add new category.
8. Then click on the category and select edit. (screen image included).
![wc-201707categorybug-1-before](https://user-images.githubusercontent.com/27138365/28489877-471506d0-6ec5-11e7-9dfb-0d25f229d463.jpg)
9. In the thumbnail section, click on the Upload/add image button.
10. Then either select an image from the media library or upload a new one.  In this case I used a 150x150 pixel jpg image.
11. After selecting the image, it is now displayed in the thumbnail section of the page (screen image  included)
![wc-201707categorybug-2-loadimage](https://user-images.githubusercontent.com/27138365/28489878-471751ec-6ec5-11e7-8d4a-e5c003babd83.jpg)

12. Now click or press the Update button
13. Now the thumbnail image dissapears when the page refreshes
(screen image included)
![wc-201707categorybug-3-afterupdate](https://user-images.githubusercontent.com/27138365/28489879-471b63fe-6ec5-11e7-876d-4ee1fd7f82e0.jpg)

No mater which way you try to add an image, after pressing update the image will vanish and not be added to the category.  Either this is not being added to the database correctly or there is some image requirement which is not being meet, but is not being reported as an error.

## Expected behavior and actual behavior
When I follow those steps, I see...
after pressing the update button the image disappears to be replaced by the empty placeholder image.
I was expecting...
that the image should be correctly added to the product category.

The problem can also be reproduced if you try to add the image in a single step rather than creating the category and adding the image later.

## Environment

<details>
```php

### WordPress Environment ###
Home URL: https://t2.example.com
Site URL: https://t2.example.com/subdir
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
### Server Environment ###
Server Info: Apache
PHP Version: 7.0.18-0ubuntu0.16.04.1
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g
SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
### Database ###
WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔
### Security ###
Secure connection (HTTPS): ✔
Hide errors from visitors: ✔
### Active Plugins (2) ###
WooCommerce: by Automattic – 3.1.1
### Settings ###
API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: 
Taxonomies: Product Visibility: 
### WC Pages ###
Shop base: #187 - /shop/
Basket: #188 - /shop/basket/
Checkout: #189 - /shop/checkout/
My account: #190 - /shop/my-account/
### Theme ###
Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔
### Templates ###
Overrides: –

```
</details>

## Isolating the problem
- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
Seems to be working here so I think it may be your database. See if you have a table called wp_term_meta, and check it has contents.

**Comment by lifeforceinst** [comment]
Hi,

I have checked the database tables and it seems that in my case, no information regarding the image is being written to wp_termmeta.  If I look into the database, I see:

In wp_terms there is an entry with an ID of 57 created for this item.
In wp_term_taxonomy there is an entry with term_ID of 57 for the description
In _termmeta (not term_meta) there is one entry which has a corresponding term_ID of 57 and a meta_key of order and meta_value of 0.  There is nothing else in that table.

Any ideas how we can further debug this issue?

**Comment by mikejolley** [comment]
termmeta is the one. And thumbnail_id is the key: https://dl.dropboxusercontent.com/s/j6ftqlz8aau9z2y/2017-07-24%20at%2010.40.png

After adding a new image, is it shown in the media library?

**Comment by lifeforceinst** [comment]
I have tried this on two systems, one which I just reinstalled WP and then just WC and they both are doing the same. When I add a category, we they add _terms and they never add anything to _termmeta table.

Is there some kind of check being performed in the WC code as to the file type, image size etc before it adds the image to the database?  

If you let me know which code is in which doing this add to the database, I can look to add in some debugging statements around the code to see which parts of the code are executing.  So that way we can try to ascertain the root cause

**Comment by mikejolley** [comment]
The update is done here https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/admin/class-wc-admin-taxonomies.php#L286-L288

**Comment by lifeforceinst** [comment]
Thanks for the info, I have spent the afternoon working on debugging thing on my side, adding in echo statements and such throughout different parts of the code to prove that certain steps were working.

After pressing update:
- the function save_category_fields( $term_id, $tt_id = '', $taxonomy = '' ) is called. = Good
- then update_woocommerce_term_meta( $term_id, 'thumbnail_id', absint( $_POST['product_cat_thumbnail_id'] ) ); is called = Good.
- Then function update_woocommerce_term_meta starts = Good.
- Then function_exists( 'update_term_meta' ) returns true because running WP 4.8 = Good.
- So this calls the WP function update_term_meta to insert the information into the table = Good.

If I turn on database debugging I see
INSERT INTO `wp_termmeta` (`term_id`, `meta_key`, `meta_value`) VALUES (21, 'thumbnail_id', '33')

But then there is some underlying database issue, when I look at the debug log which reports:
[24-Jul-2017 16:29:15 UTC] WordPress database error Duplicate entry '0' for key 'PRIMARY' for query INSERT INTO `wp_termmeta` (`term_id`, `meta_key`, `meta_value`) VALUES (21, 'thumbnail_id', '33') made by wp_update_term, do_action('edit_term'), WP_Hook->do_action, WP_Hook->apply_filters, 

So this then indicating to me some corruption of the table _termmeta though the strange thing is this happens even with a new database.  I am investigating how to repair the table with phpmyadmin



I also verified that when I add a new image, either jpg or png, then yes it is present in the media library and can be access by WP and if I use the permalink I can display the image.  

Then I decided to turn on debugging in WordPress to the max and found some debug messages from the database

**Comment by mikejolley** [comment]
Ah, Ive seen this before. I don't know what could have caused it (this is not a WooCommerce table) but you need to edit your database schema and make the `meta_id` column have auto_increment. A plugin may have broken this so review whats installed.
