### ISSUE TITLE
WooCommerce Cart Missing on Simple Product

### ISSUE THREAD

**Issue by jamieukk** [woocommerce/woocommerce#16220]
Hi, I have had issues with a site using the Bazar theme and WooCommerce. I had missing prices in 'Variable Products' and the cart is missing on 'Simple Products' 
I found out that by default if you have the same price for variations woocommerce hides the price, so I added this code in the functions.php :+1: 

 _add_filter('woocommerce_show_variation_price',      function() { return TRUE;});_

**Problem 1 solved :)**

The next problem was the cart button missing on simple products. I disabled plugins and deleted my custom CSS, with no joy, then I switched to a default theme and the buttons worked. Great I had a theme issue. So I tried rolling back versions of everything and updating themes etc etc. Nothing has worked. My questions is does anyone know a fix to this, has anyone come across this? I am reluctant to revert back to an old backup as the client has uploaded products daily and will lose the latest product updates. Any ideas would be greatly appreciated.

**Comment by mikejolley** [comment]
Bazar theme is premium; I don't have access, and we support core here only. May be best to see if the theme author can advise?
