### ISSUE TITLE
product visibility = hidden are not being hidden

### ISSUE THREAD

**Issue by c2t-webmaster** [woocommerce/woocommerce#16229]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce
- [X] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Marking a product with visibility = hidden via product edit.

Hidden products appear in catalog display with value of 'visible' in spite of product admin edit showing hidden.

## Expected behavior and actual behavior

In my environment, the get_the_terms() call in read_visibility() in class-wc-product-data-store-cpt.php returns an empty array and thus the rest of the logic result in catalog_visibility being set to 'visible' in spite of how the product is configured in admin.

protected function read_visibility( &$product ) {
//              $terms           = get_the_terms( $product->get_id(), 'product_visibility' );
$terms = wp_get_object_terms( $product->get_id(), 'product_visibility' );

"fixes" the behavior.   I've seen at least 1 reports of plugin conflict be a potential cause, but it wasn't clear what version of WC that was (about a year ago, so probably not WC 3.x).   Given this issue is alleged to be new with WC 3.x, I'm reporting it as a potential edge condition bug. 

The latest master branch of code that I hacked to workaround is the unchanged.  However, a solution could exist somewhere else in the code for all I know.

## Environment
<details>

### WordPress Environment ###

Home URL: https://www.create2thrive.com
Site URL: https://www.create2thrive.com
WC Version: 3.0.9
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 128 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.9
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (56) ###

Advanced Cron Manager: by Kuba Mikita – 1.5
All In One SEO Pack: by Michael Torbert – 2.3.13.2
All In One WP Security: by Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.2.8

HTML in Category Descriptions: by Arno Esterhuizen – 1.2.1.1
bbPress: by The bbPress Community – 2.5.12
Better Delete Revision: by Galerio & Urda – 1.6.1
Broken Link Checker: by Janis Elsts
Vladimir Prelovac – 1.11.3

C2T WP REST API: by Create2Thrive
Inc. – 1.0.0

C2T WooCommerce Ravelry Integration: by Create2Thrive
Inc. – 1.3.0

Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

Custom Related Products for WooCommerce: by Scott Nelle – 1.3
Enhanced Media Library: by wpUXsolutions – 2.4.5
Export Users Data to CSV for MS Excel: by Penzin Konstantin – 1.0.0
Forum Beginner Posts: by Fidgety Lizard – 1.1.0
GD bbPress Attachments: by Milan Petrovic – 2.4
Google Analyticator: by SumoMe – 6.5.3
Google XML Sitemaps: by Arne Brachhold – 4.0.8
Groups 404 Redirect: by itthinx – 1.3.1
Groups WooCommerce: by itthinx – 1.11.3
Groups: by itthinx – 2.2.0
Media Tags: by Paul Menard – 3.2.0.2
Meta Slider: by Team Updraft – 3.5.1
Newsletter - Amazon SES: by The Newsletter Team – 1.1.0
Newsletter - Reports: by The Newsletter Team – 4.1.3
Newsletter: by Stefano Lissa & The Newsletter Team – 4.9.8
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.0
Redirection: by John Godley – 2.6.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
REST API Toolbox: by Pete Nelson – 1.4.2
WP REST API: by WP REST API Team – 2.0-beta15
Fast Secure Contact Form: by fastsecure – 4.0.52
Social Media Widget: by Noah Kagan – 4.0.6
Simple Vimeo Shortcode: by Grant Kimball – 2.9.1
TinyMCE Advanced: by Andrew Ozz – 4.6.3
Ultimate FAQ: by Etoile Web Design – 1.5.37
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.4

Visitor Maps Geolocation Addon: by Mike Challis – 1.0
Visitor Maps and Who's Online: by fastsecure – 1.5.8.14
Weaver Xtreme Theme Support: by wpweaver – 3.1.7
Easy SMTP Mail: by priyanshu.mittal – 1.7
Advanced Order Export For WooCommerce: by AlgolPlus – 1.4.0
WooCommerce - Coupon Column: by Pross – 0.2
WooCommerce EU VAT Number: by WooCommerce – 2.3.0
WooCommerce Group Coupons: by itthinx – 1.7.1
Booster for WooCommerce: by Algoritmika Ltd – 2.8.2
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.6.0

WooCommerce Predictive Search LITE: by a3rev Software – 4.0.3
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2
WooCommerce: by Automattic – 3.0.9 – 3.1.1 is available
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
WordPress HTTPS: by Mike Ems – 3.3.6
Nested Pages: by Kyle Phillips – 1.7.1
REST API Log: by Pete Nelson – 1.6.4
WP Video Lightbox: by Tips and Tricks HQ
Ruhul Amin – 1.8.4

Custom Product Tabs for WooCommerce: by YIKES
Inc – 1.5.15

YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-3 (rated-3-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

### WC Pages ###

Shop base: #440 - /
Cart: #441 - /shop/cart/
Checkout: #442 - /shop/checkout/
My account: #443 - /shop/my-account/

### Theme ###

Name: Weaver Xtreme Child Demo
Version: 1.0
Author URL: //weavertheme.com/about
Child Theme: ✔
Parent Theme Name: Weaver Xtreme
Parent Theme Version: 3.1.7 – 3.1.8 is available
Parent Theme Author URL: //weavertheme.com/about
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: weaver-xtreme-child/woocommerce/cart/cart.php
weaver-xtreme-child/woocommerce/emails/customer-reset-password.php
weaver-xtreme-child/woocommerce/emails/email-header.php
weaver-xtreme-child/woocommerce/global/form-login.php
weaver-xtreme-child/woocommerce/myaccount/dashboard.php
weaver-xtreme-child/woocommerce/myaccount/form-login.php
weaver-xtreme-child/woocommerce/myaccount/form-lost-password.php
weaver-xtreme-child/woocommerce/single-product/add-to-cart/simple.php

`</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently

Disabling plugins and changing themes will nice thought to do is unrealistic to test in a production environment.   I could go there eventually, but I'd rather not.

**Comment by mikejolley** [comment]
`wp_get_object_terms` is uncached. Thats the main difference to get_the_terms.

The issue is in this section:

```
Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-3 (rated-3-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)
```

Something (bad update? download/upgrade multiple times?) has caused duplicate terms to be created.

To fix:

1. Edit this line to true: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-post-types.php#L72
2. Go to Products > Product Visibility in the admin UI
3. Remove the duplicate terms (slugs will be appended -2)
4. If the products are still visible, change the visibility visible and back to hidden.

There is some SQL to bulk set the terms again if needed.

**Comment by jawinn** [comment]
This worked. I had the same issue with a WC 3.0.7 site. 

Note that step 1 should be changing `show_ui` to true for the link to appear in the WP Admin panel (this line may have changed from what was originally linked). For this version, the new nav item link was another one just called 'Tags' but with "taxonomy=product_visibility" in the URL.
