### ISSUE TITLE
Woocommerce update 3.1.1 "Internal Server Error"

### ISSUE THREAD

**Issue by cashoncommand** [woocommerce/woocommerce#16226]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce
- [x ] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [x ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. I am currently running Woocommerce 3.0.5, when I tried to update to 3.1.1.  I get the error "Internal Server Error"
2. I have updated all other plugins individually and in various orders to see which one is causing the error, it has come down to Woocommerce update 3.1.1.  All other scenarios worked fine until I run the 3.1.1 update.
3.

## Expected behavior and actual behavior

As above..  I have tested each plugin separately and it only occurs when updating Woocommerce 3.0.5

I would like to try the individual updates from 3.0.5 to 3.1.1 to see which update is causing the issue, but can't find the link to do so..

If anyone could help, that would be great.

WP = 4.8
Woocommerce = 3.0.5
Also, I am using Bookly = 13.7

**Comment by mikejolley** [comment]
Since 3.1.1 is a patch release/minor, I don't think it will be directly responsible. I think you're hitting a memory limit: https://docs.woocommerce.com/document/increasing-the-wordpress-memory-limit/

Your server error logs could help confirm this.

**Comment by cashoncommand** [comment]
HI Mike. 

Do you know where I can get the previous updates from 3.0.5, so that I can test the different updates.

Thanks
Kristina Suh
cashoncommand@gmail.com

**Comment by mikejolley** [comment]
Here https://github.com/woocommerce/woocommerce/tags but as I said, checking logs would be better because if it's memory related it could trigger with random plugin updates or combinations of plugins. Your system status report will tell you how much memory is allocated - WC > System Status.

Let us know what you find.

**Comment by JarodFroneman** [comment]
Hey guys. I know I'm commenting a bit late. I had the same internal server error on the WooCommerce check. Basically, Woocommerce won't let you use internal payment gateways ((such as Cash on Delivery, BACS etc.) if you don't have a SSL certificate installed on your Woocommerce store.  As soon as I bought (Comodo has a free 90 day SSL here: https://ssl.comodo.com/free-ssl-certificate.php) and installed an SSL certificate, my issue was resolved. I hope this helps.
