### ISSUE TITLE
how can i locate which WC plugin is doing this error 

### ISSUE THREAD

**Issue by alaric1** [woocommerce/woocommerce#16228]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
(https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

So i have this bug... when i look in my Apache error log i get:

GET /?wc-api=software-api&request=deactivation&email=&licence_key=&product_id=123&instance=&platform= HTTP/1.0

Code: 503

i get this every 30mins to 7day to 1 month, its never at the same time either.

i can't seem to find what is calling this script. i would like to know so i can remove what ever is doing this.

i don't have any cracked plugins either, but i do have free plugins from WP plugin download page.

i did try to turn off some plugins to see which is doing this but can't seem to find it.

Any help would be appreciated.

**Comment by mikejolley** [comment]
I think that would be https://docs.woocommerce.com/document/software-add-on/

Maybe it's not on your site, maybe it's someone calling the URL on your store from elsewhere?

Hope that steers you in the right direction.
