### ISSUE TITLE
Variable Product show "Sorry, this product is unavailable. Please choose a different combination."

### ISSUE THREAD

**Issue by roenardi** [woocommerce/woocommerce#16227]
WP v4.8 , WC v3.1.1
1. change product to "variable product"
2. add attributes, ex: size. checked both "visible on the product page" and "Used for variations".
3. add variations. ex: each size with quantity 300.
4. view product and choose size. it will show "Sorry, this product is unavailable. Please choose a different combination."

5. when i change the product to "simple product", it can't show "add cart button".
(in inventory->stock status = "out of stock", even after i change the quantity to 1000 and status to "in stock", "add cart button" still not show).

https://blissfullyminecollection.mystagingwebsite.com/product/product01/

Please fix this.
Muji

**Comment by mikejolley** [comment]
As it looks like you've worked out already, variations will not display until they are given regular prices. Prices are mandatory. This will be clearer in future UI updates.
