### ISSUE TITLE
set_variation() null PHP Warning

### ISSUE THREAD

**Issue by turtlepod** [woocommerce/woocommerce#16232]
I got this PHP Warning:
```
[24-Jul-2017 02:00:33 UTC] PHP Warning:  Invalid argument supplied for foreach() in C:\xampp\htdocs\_play\listify.play\wp-content\plugins\woocommerce\includes\class-wc-order-item-product.php on line 169
```
This code:
```
	/**
	 * Set variation data (stored as meta data - write only).
	 *
	 * @param array $data Key/Value pairs
	 */
	public function set_variation( $data ) {
		foreach ( $data as $key => $value ) {
			$this->add_meta_data( str_replace( 'attribute_', '', $key ), $value, true );
		}
	}
```
I think it should check if the data is empty/null:
```
/**
 * Set variation data (stored as meta data - write only).
 *
 * @param array $data Key/Value pairs
 */
public function set_variation( $data ) {
	if ( ! $data ) {
		return;
	}
	foreach ( $data as $key => $value ) {
		$this->add_meta_data( str_replace( 'attribute_', '', $key ), $value, true );
	}
}
```

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce
- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

<details>
```
Grab the system status report from WooCommerce > System Status and paste it here.
```
</details>

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
It could yes, however, whatever plugin is calling this should not be sending a null/empty value to `set_variation`.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16233
