### ISSUE TITLE
Too many redirects: Customizer view

### ISSUE THREAD

**Issue by MBfromOK** [woocommerce/woocommerce#16231]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce 

> ?? newest version ?? - where would I find the master branch?

- [x] This is not a usage question (Those should be directed to the [community](https://wordpress.org/support/plugin/woocommerce), unless this is a question about a premium plugin in which you should [use the helpdesk](https://woocommerce.com/my-account/tickets/) for official extensions or contact the author of 3rd party extensions)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Browse to site address (https://www.torahgear.net/store/)
2. Login (Administrator Account)
3. Click Home
4. Click customize on admin bar

## Expected behavior and actual behavior

When I follow those steps, I see...

Customizer pane on left and on the right: "www.torahgear.net redirected you too many times."
Address bar shows: https://www.torahgear.net/store/wp-admin/customize.php?url=https%3A%2F%2Fwww.torahgear.net%2Fstore%2F

I was expecting...

Customizer pane on the left & a preview of my site for header, typography and other customizations.

## Environment

<details>

```

`

### WordPress Environment ###

Home URL: https://www.torahgear.net/store
Site URL: https://www.torahgear.net/store
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.7
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Homepage Control: by WooThemes – 2.0.2
Sharing buttons shortcode for Jetpack: by Jeremy Herve – 1.2.1
Jetpack by WordPress.com: by Automattic – 5.1
Meta Slider: by Team Updraft – 3.5.1
Simple Sales Tax: by Simple Sales Tax – 4.7
Storefront Sticky Add to Cart: by WooThemes – 1.1.6
Title Toggle for Storefront Theme: by Wooassist – 1.2.3
WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0
WooCommerce Pre-Orders: by WooCommerce – 1.5.1 – 1.5.2 is available
WooCommerce Services: by Automattic – 1.6.2
WooCommerce: by Automattic – 3.1.1
X-tra Ordinary WooCommerce Product Carousel and Slider: by Arung Isyadi – 3.1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: My Storefront
Version: 2.0
Author URL: https://www.torahgear.net/store/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.4
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

`

```

</details>

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/) 

> **I am using a StoreFront CHILD THEME** - Just CSS Changes, and some minor functions.php changes here:
<details>

```
add_filter( 'storefront_credit_link', 'hide_storefront_credit_link', 10, 1 );
function hide_storefront_credit_link( $bool ){
   return false;
}
/*
function hide_sidebar_for_empty_carts() {
	if ( WC()->cart->get_cart_contents_count() === 0 ) {
        	remove_action( 'storefront_sidebar', 'storefront_get_sidebar', 10 );
	}
}
*/
add_action( 'init', 'custom_remove_footer_credit', 10 );
function custom_remove_footer_credit () {
    remove_action( 'storefront_footer', 'storefront_credit', 20 );
    add_action( 'storefront_footer', 'custom_storefront_credit', 20 );
} 
function custom_storefront_credit() {
	?>
	<div class="site-info">
		&copy; <?php echo get_bloginfo( 'name' ) . ' ' . get_the_date( 'Y' ); ?>
	</div><!-- .site-info -->
	<?php
}

/*
add_action( 'init', 'hide_sidebar_for_empty_carts', 0 );
*/
/*
add_action('woocommerce_before_main_content', 'remove_sidebar' );
function remove_sidebar()
    {
        if( is_checkout() || is_cart() || is_product()) { 
         remove_action( 'woocommerce_sidebar', 'woocommerce_get_sidebar', 10);
       }
    }
*/
```
</details>

- [x] I can reproduce this bug consistently

**Comment by mikejolley** [comment]
@MBfromOK Since this is a customiser issue (something not added by WooCommerce), did you confirm if it works or not when WooCommerce is OFF?

**Comment by MBfromOK** [comment]
Will check tomorrow, unable to do so today.

**Comment by mikejolley** [comment]
Were you able to narrow this down? We're not able to replicate unfortunately.

**Comment by MBfromOK** [comment]
Sorry, the website went down and took precedence.  I was able to verify that everything works as expected with WooCommerce disabled.  When re-enabled (as the only plugin) the problem returns.

I think that it might have been caused either by the storefront child theme I am using or my CSS style sheets (my current project). I am loading a custom functions.php and 4 stylesheets in the child theme, and didn't see the problem with the default storefront theme.
