### ISSUE TITLE
Refund not allowed in custom payment gateway if order total is zero.

### ISSUE THREAD

**Issue by sagaraloha** [woocommerce/woocommerce#16234]
I am building custom payment gateway such as 'gift card'.

In this custom payment gateway, I am allowed to do partial payment.

Consider one scenario, Suppose order total is 100$ and I am doing payment via 'gift card' custom payment gateway. then i am subtracting gift card redeemed amount from order total. so, now order total is 0$.

and when i want to refund gift card amount, it does not allow me to do that. it say's 'Total available to refund: 0$' i. e. equal to order total. but i paid through gift card, and i want to refund it into gift card balance. how can i achieve this? please help me.

**Comment by mikejolley** [comment]
If the order total is 0, there is nothing to refund. If you're treating gift card as cash, and have a GATEWAY for doing this, don't change the order totals.

Gift cards are not build into core so I don't think we can 'fix' or change this.

**Comment by sagaraloha** [comment]
Then, how can i make partial payment such as, 50$ from gift card and 50$ by credit card.

If after applying gift card, i am order total remains same, then credit card takes total amount '100$' but not '50$'. how can i solve this?

**Comment by mikejolley** [comment]
That would require a credit card gateway right?

So the refund would be for any cash payment. You cannot 'refund' a payment which never occurred. Maybe your gift card plugin lets you increase the users balance?

**Comment by sagaraloha** [comment]
Credit card as an example for another payment gateway. it can be 'check payments/ Cach on delivery'.

I want to refund gift card amount to 'particular gift card'  as balance. so when i order it redeems amount of 50$ and when i refund, then it credits 50$ into gift card balance.

**Comment by mikejolley** [comment]
That would need to be custom coded, I don't have examples to hand. It's not a core feature.
