### ISSUE TITLE
Cant create product variations in the create products request 

### ISSUE THREAD

**Issue by eladvider-softangible** [woocommerce/woocommerce#16248]
I'm using rest api v2 for woocommerce 3.

I trying to insert products with variations in the same request, can i do it with v2 rest api version ?

this is my request:

`  {
      "create": [
        {
          "name": "9325400137",
          "type": "variable",
          "sku": "93254",
          "status": "pending",
          "id": "",
          "attributes": [
            {
              "position": 0,
              "name": "color",
              "slug": "color",
              "options": [
                "black",
                "red"
              ],
              "variation": true,
              "visible": true
            },
            {
              "position": 0,
              "name": "size",
              "slug": "size",
              "options": [
                "37",
                "40",
                "39",
                "38",
                "41",
                "36"
              ],
              "variation": true,
              "visible": true
            }
          ],
          "variations": [
            {
              "id": "234234",
              "sku": "9325400137",
              "manage_stock": true,
              "regular_price": "50",
              "stock_quantity": 0,
              "in_stock": false,
              "status": "pending",
              "attributes": [
                {
                  "id": "233423",
                  "name": "color",
                  "option": "black"
                },
                {
                  "id": "2342342",
                  "name": "size",
                  "option": "37"
                }
              ]
            }
          ]
        }
      ]   
    }
`

the response is empty variations array.

"variations": []

**Comment by mikejolley** [comment]
No, variations have a dedicated endpoint. Create the variable product first, then create variations https://woocommerce.github.io/woocommerce-rest-api-docs/#product-variations

**Comment by eladvider-softangible** [comment]
Thanks,
so i understood that this options is deprecated?, its was working fine in v1

**Comment by mikejolley** [comment]
@eladvider-softangible Different versions of the API are not the same, thats why we have versioning. The endpoint did not exist in v1.

**Comment by kdenno** [comment]
@mikejolley thanks for the help but again how do i get the id of that newly created product so i can attach variations to that product. i am talking from a stand point where i have a simple GUI for my clients and everything has to happen in the background and in one go in the end all i show them is 'product created successful '
