### ISSUE TITLE
Product Import too slow when category column has value

### ISSUE THREAD

**Issue by gladysobmerga** [woocommerce/woocommerce#16246]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to Admin > Products
2. Attach a csv file in which the category column has a lot of values
3. Proceed to importing products

## Expected/actual behavior

When I follow those steps, I see that the csv file is not importing whenever i have a lot of values in category column. but when i leave it blank, csv file is easily imported

I was expecting to see a success or maybe a error log after import. but it just takes a lot of time to load.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.


```
</details>

**Comment by gladysobmerga** [comment]
Hi, just a follow up. the issue is because of the "&" "and" character. Please help

**Comment by mikejolley** [comment]
This then? https://github.com/woocommerce/woocommerce/issues/16250 Let me know if it's something different, and please provide your CSV in the other issue so I can try it. 

Thanks
