### ISSUE TITLE
Shipping Tax applied to non-taxable products

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#16241]
On a product, you can set the tax status to taxable, shipping only, or none: http://cld.wthms.co/spPULc. The issue I'm reporting is that there is no difference between "shipping only" and "none". When set to "none", shipping is still taxed.

Product settings: http://cld.wthms.co/xLxyIE
Tax settings: http://cld.wthms.co/1mBYQ6
Tax rate: http://cld.wthms.co/PHBVYs
Shipping method: http://cld.wthms.co/fJQDL0

When I add that product to the cart, I would expect no taxes. But instead, shipping is taxed: http://cld.wthms.co/aC9FJ. The same result happens when I select "shipping only" for the product. 

As a temporary workaround, I can create a "no taxes" tax class and assign it to the product in question. But this still seems like a bug, or the settings need to be changed around.

601485-zd-woothemes

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16336
