### ISSUE TITLE
woocommerce_wp_text_input and global $post and global $thepostid

### ISSUE THREAD

**Issue by andreagrillo** [woocommerce/woocommerce#16244]
This is similar related to this issue request: https://github.com/woocommerce/woocommerce/issues/15047 

Similar to what I wrote in issue request 15047, the method output of WC_Meta_Box_Order_Data (line 139) require a WP_Post $post param. I use this method to retrieve the billing and shipping information and edit form. All working fine but if I try to edit the information all form fields is empty. The reason of this is that in the function `woocommerce_wp_select` and ` woocommerce_wp_text_input`  (look the method output at line 327 - 330) use the global $thepostid, $post; instead of $post that I use in output method, and this cause the issue.

The reason of this is that I use the method output inside a shortcode in a page and, in this case, the global $post and global $thepostid are related to the page that the user see and not to the specific shop order. 

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

open the filewp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php at look at line139

To reproduce the issue try to call WC_Meta_Box_Product_Data::output( $post ); and use a different $post object Compared with the global $post; object. 
All works fine inside method output but if you add a var_dump/error_log inside the woocommerce_wp_text_input function and try to show the value of $post or $post->ID or global $thepostid you can see that only global $post; object are using and not our $post object.

## Expected/actual behavior

When I follow those steps, I see a blank edit form if I click on pencil icon

I was expecting to see the previous value instead of empty fields

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://support.dev
Site URL: http://support.dev
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.7
PHP Version: 7.0.14-2+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn – 2.13.4
Members: by Justin Tadlock – 2.0.0
User Switching: by John Blackbourn – 1.0.9
WooCommerce: by Automattic – 3.1.1
YITH Frontend Manager for WooCommerce Premium: by YITHEMES – 1.0.10
YITH WooCommerce Multi Vendor Premium: by YITHEMES – 2.0.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
@andreagrillo This one does not look like it can/should be fixed as it would involve either messing with globals in admin, or passing `$post` around which could break BW compatibility.

FWIW the meta box related functions are due refactor, but there is no point doing this until we see what direction WP admin is going. Globals are just something we have to live with in admin right now.

Unless you see a non-breaking quick fix?

**Comment by andreagrillo** [comment]
ummmm, like you wrote on previous reply It's not easy....for now I find a workaround and I have added it in my plugin....

I'll do some test, if I find some "non-breaking" idea I'll let you know.

Thanks for your time

AG

**Comment by mikejolley** [comment]
Thanks 👍 Let me know.
