### ISSUE TITLE
Woocommerce API returns HTTP ERROR 500

### ISSUE THREAD

**Issue by redoxate** [woocommerce/woocommerce#16245]
Hi, 
I just think that I did everything right,
1.     donwloaded the woocommerce API using composer (php composer.phar require automattic/woocommerce)
2.    moved the files to my MAMP htdocs 
3.    Created this php file (with the right keys for sure & the vendor directory is in the same folder )
 `require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://www.xxxxx.com/',
    'ck_88xxxxxxxx83b2',
    'cs_faxxxxxxxxxxfb1',
    [
        'wp_api' => true,
        'version' => 'wc/v2',
    ]
);

print_r($woocommerce->get('products'));`

I just don't get, could you please help me out ...
Thanks <3

**Comment by mikaelz** [comment]
Hi,
I tested [automattic/woocommerce](https://github.com/woocommerce/wc-api-php) with WooCommerce 3.1.0 (WP 4.8) install and the following code 
[worked](https://user-images.githubusercontent.com/454800/28579167-237b4ace-715c-11e7-9f0d-21b78b0f113b.jpg):
```
<?php

use Automattic\WooCommerce\Client;

require __DIR__.'/vendor/autoload.php';

$woocommerce = new Client(
    'http://localhost/rigel/',
    'ck_82f951ffe2e64f8f0fe8c59dcf8b4ee220c5cddb',
    'cs_bfd44e7cac1692d4dc7dcad30ec2fe8ad946efd9',
    array(
        'verify_ssl' => false,
        'wp_api' => true,
        'version' => 'wc/v2',
    )
);

echo '<pre class="debug">';
print_r($woocommerce->get('products'));
echo "</pre>";
```
Maybe https://github.com/mikaelz/wordpress-related/tree/master/woocommerce-api-test helps.

**Comment by mikaelz** [comment]
To debug the HTTP error 500 you might try `print_r($this->request);` at line https://github.com/woocommerce/wc-api-php/blob/master/src/WooCommerce/HttpClient/HttpClient.php#L231 to see the request.
For me it was `http://localhost/rigel/wp-json/wc/v2/products?oauth_consumer_key=ck_82f951ffe2e64f8f0fe8c59dcf8b4ee220c5cddb&oauth_nonce=1696badae3fb050450a5e50771a9dcafce68ca87&oauth_signature=j4omCpiaNGRsToCwYpInnoCKpxWs14gVcKgsS3GNrOY%3D&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1500995567`
