### ISSUE TITLE
No Flex Slider Arrows?

### ISSUE THREAD

**Issue by anteksiler** [woocommerce/woocommerce#16247]
Product image slider enabled on the latest version do not have arrows, only thumbnail navigation.

**Comment by mikejolley** [comment]
Intended AFAIK. There are filters to allow customisation to flexslider init. https://github.com/woocommerce/woocommerce/blob/a7582d50da833fa44618c0c9389724bbf1bf8bcf/includes/class-wc-frontend-scripts.php#L475

**Comment by anteksiler** [comment]
Yeap, found this snippet for others:
`add_filter( 'woocommerce_single_product_carousel_options', function( $options ) {
	$options['directionNav'] = true;
	return $options;
} );`
