### ISSUE TITLE
Sipping Adress is missing in woocommerce / Settings 

### ISSUE THREAD

**Issue by swissteam** [woocommerce/woocommerce#16259]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Basically, the shipping address is just missing.

## Expected/actual behavior

well before we could add a shipping address, now we don't even have that option in the backend.

I was expecting to see...
shipping address. 

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://koerperreinigung.ch
Site URL: https://koerperreinigung.ch
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 256 MB
PHP Time Limit: 60
PHP Max Input Vars: 20000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.9
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

AffiliateWP - Lifetime Commissions: von Pippin Williamson and Andrew Munro – 1.2.4
AffiliateWP: von AffiliateWP
LLC – 2.1.3.1

AffiliateWP - Affiliate Product Rates: von Pippin Williamson and Andrew Munro – 1.0.4
AffiliateWP - Custom Affiliate Slugs: von Pippin Williamson and Andrew Munro – 1.0.1
AffiliateWP - Direct Link Tracking: von AffiliateWP – 1.1.1
AffiliateWP - Order Details For Affiliates: von AffiliateWP – 1.1.3
Ban Hammer: von Mika Epstein – 2.6
Comet Cache: von WebSharks
Inc. – 170220

WordPress Editorial Calendar: von Colin Vernon
Justin Evans
Joachim Kudish
Mary Vogt
and Zack Grossbart – 3.6.4

Huge IT Lightbox: von Huge-IT – 2.1.0
Member Access: von Chris Abernethy – 1.1.6
VarkTech Minimum Purchase for WooCommerce: von Vark – 1.09.8
MyMail - Email Newsletter Plugin for WordPress: von revaxarts.com – 2.1.27
PixelYourSite: von PixelYourSite – 5.0.5.2
Quick Page/Post Redirect Plugin: von anadnet – 5.1.8
Search By SKU - for Woocommerce: von Matthew Lawson – 0.6.1
Simple Tags: von Amaury BALMER – 2.4.7
Tag Pages: von Bjorn Wijers  – 1.0.1
User Role Editor: von Vladimir Garagulya – 4.35.3
WooCommerce Product Feed: von WebAppick – 2.1.9
Widgetkit: von YOOtheme – 1.5.8
WooCommerce Checkout Manager: von Visser Labs – 4.1.3
Währungs-Umschalter: von realmag777 – 1.1.9
WooCommerce Print Invoice & Delivery Note: von Triggvy Gunderson – 4.1.5
WooCommerce PayPal Express Checkout Gateway: von WooCommerce – 1.4.2
WooCommerce Stripe Gateway: von WooCommerce – 3.2.2
WooCommerce Simply Order Export: von Ankit Gade – 2.1.7
WooCommerce - Store Exporteur Deluxe: von Visser Labs – 2.3.5.1
WooCommerce: von Automattic – 3.1.1
Yoast SEO: von Team Yoast – 5.0.2
WP-DraftsForFriends: von Lester 'GaMerZ' Chan – 1.0.2
WP Statistics: von WP-Statistics Team – 12.0.9
WP Ultimate Recipe Premium: von Bootstrapped Ventures – 3.7.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #787 - /shop/
Warenkorb: #788 - /wunschliste/
Kasse: #789 - /wunsch-erfuellen/
Mein Konto: #790 - /mein-konto/

### Theme ###

Name: Eat
Version: 1.0.8
Author URL: http://www.yootheme.com
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Templates ###

Scheduled Export to FTP: ✔
Scheduled Export to SFTP: ❌ The required SFTP functions are not available
`
</details>

**Comment by mikejolley** [comment]
Looking at https://koerperreinigung.ch/wunschliste/, there is no shipping configured. For the shipping address fields to display, you need:

- Shipping enabled in WC > Settings > "Shipping locations"
- A shipping method configured (can be free shipping if thats all you want)
- Products must not be virtual. Virtual products do not ship.

Satisfy the above criteria, and shipping address will be collected.

**Comment by swissteam** [comment]
Could fix it. Thx.

maybe you can give me a hint for this issue as well. Before we could click in wp-admin/edit.php?post_type=shop_order to see with one click what the client ordered. Now we need to open the specific order to see the products that was ordered. Is there a button to turn that function on to see it in order overview? Thx. again

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/14121
