### ISSUE TITLE
Tax Applied After Being Removed

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#16258]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Place a new order which includes a tax
2. Edit the order, remove the tax using the `x` from the tax column: http://cld.wthms.co/6EAlmT
3. Click on Recalculate

## Expected/actual behavior

When I follow those steps, the tax class that I just removed is added back again.

I was expecting it to not be added.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

#596883-zen

**Comment by mikejolley** [comment]
"recalculate" does totals + taxes, so recalculating  in this case it right to change, add, or remove tax columns depending on the products, user address, and tax settings.

**Comment by paulschaeff** [comment]
Hi Mike,
I understand I can use the "Update" button after removing a tax column to have it only update the total and not recheck taxes, but it is a crazy non-intuitive workaround for working with tax-exempt organizations or business to business sales. Is there any plan to be able to designate users as tax-exempt to avoid this problem all together?
Thanks.

**Comment by mikejolley** [comment]
No but that would be a good addition.
