### ISSUE TITLE
'woocommerce_add_to_cart_handler_' . $add_to_cart_handler action passing $url instead of $product_id

### ISSUE THREAD

**Issue by ty2u** [woocommerce/woocommerce#16268]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a new custom product type, for example customproducttype.
2. Add a filter like so: add_filter( 'woocommerce_add_to_cart_handler_customproducttype', 'custom_add_to_cart_handler' );
3. custom_add_to_cart_handler can be a copy of add_to_cart_handler_simple https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L743
4. Add a new custom product and try adding it to the cart.

## Expected/actual behavior

When I follow those steps, I see...
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L717
$url is false that gets passed and the $product_id isn't passed to the custom_add_to_cart_handler function.

I was expecting to see...

$product_id being passed to the custom_add_to_cart_handler function.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
`do_action( 'woocommerce_add_to_cart_handler_' . $add_to_cart_handler, $url );` does not pass ID, it passes the URL to redirect to after adding to cart. Everything you need is in `$_REQUEST`. Changing this would break backwards compatibility at this point, so it cannot happen.
