### ISSUE TITLE
Only variations with assigned attributes displaying ("Any [attribute]" not displaying)

### ISSUE THREAD

**Issue by juliajonesltd** [woocommerce/woocommerce#16261]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add 3 attributes to a new variable product
2. Add 2 variations, one set to a specific attribute, the other set to "any"
3. View the product page, only the specifically set attribute will display

## Expected/actual behavior

When I follow those steps, I see... Only the attributes explicitly set as variations will display, the rest that would normally display because of setting "any attribute" are not visible

I was expecting to see... "Any attribute" should display all remaining attributes (otherwise it's useless)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost/[mysite]
Site URL: http://localhost/[mysite]
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 500 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.0.15
PHP Version: 7.0.15
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: jj_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (8) ###

Redirection: by John Godley – 2.6.5
Theme Customisations: by WooThemes – 1.0.0
Woocommerce Advanced Bulk Edit: by George Iron – 4.0.4
Woocommerce Product Slider: by Kiran Polapragada – 1.5.2
WooCommerce: by Automattic – 3.1.1
WooSlider: by WooThemes – 2.2.0 – 2.4.2 is available
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /cart/
Checkout: #6 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/cart\cart-shipping.php
storefront/woocommerce/single-product\product-attributes.php
storefront/woocommerce/single-product\tabs\description.php

`
```
</details>

**Comment by mikejolley** [comment]
Online example? Screenshot of your setup? "Any" works here - as long as a variation has any, all attributes are shown in dropdowns. Does your any variation have a price?

**Comment by juliajonesltd** [comment]
Finally figured it out! It depends on the order in which the variations are added, so it will only show all the attributes if "any" is assigned to the first variation added (i.e. in my example above, reassigning "Any" to the variation #53311). 

This is somewhat counter-intuitive as the "Any" variation is usually at the bottom, so it's expected behaviour at least some of the time for it to be added last. Regardless, it's clearly behaviour that should be corrected.

**Comment by mikejolley** [comment]
You may need to contact support about this to give access. I tested this with 'any' at the bottom and all attributes were shown. If a non-selected attribute was selected, it matched the 'any' variation no problem.
