### ISSUE TITLE
cannot save changes shipping methodes

### ISSUE THREAD

**Issue by wvdbroek** [woocommerce/woocommerce#16277]
I cannot save in any way the changes to the shipping methodes 
i created a zone, add flat rate. Press change, renamed the flat rate and give it a rate .
press save and there its stuck !!

**Comment by wvdbroek** [comment]
### WordPress Environment ###

Home URL: http://webshoptest.pc-allin.nl/webshoptest
Site URL: http://webshoptest.pc-allin.nl/webshoptest
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Microsoft-IIS/7.0
PHP Version: ❌ 5.5.11 - Wij raden minimaal PHP-versie 5.6 aan. Zie: Hoe je PHP-versie bijwerken
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.36.0
OpenSSL/1.0.1g

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.28 - Wij adviseren een minimum MySQL-versie 5.6. Bekijk: WordPress vereisten
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Jouw winkel gebruikt geen HTTPS. Leer meer over HTTPS en SSL-certificaten.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: door Automattic – 3.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Winkelbasis: #5 - /index.php/winkel/
Winkelmand: #6 - /index.php/winkelmand/
Afrekenen: #7 - /index.php/afrekenen/
Mijn account: #8 - /index.php/mijn-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
The save button is greyed out when save is not required https://github.com/woocommerce/woocommerce/issues/13683. We know this can be confusing and it will be improved in future updates. The method should be saved though!

**Comment by wvdbroek** [comment]
thats just it it doesnt ,nothing is saved to the wp-options in the DB

**Comment by mikejolley** [comment]
It's not saved to wp-options, there is a shipping zones/methods table.

**Comment by wvdbroek** [comment]
yes thats true for the methods self, but not for a name change or price this is stored in wp-options. And there is my problem. I have found that the problem is at my hoster. I installed XAMPP local and there the probem doesnt exists.
