### ISSUE TITLE
incorrect access level in class-wc-product-variation.php

### ISSUE THREAD

**Issue by Valks** [woocommerce/woocommerce#16272]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ~ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. in includes/class-wc-product-variation.php on line 23 $post_type is public, it should be protected because of base class WC_Product

## Isolating the problem

- [ X ] This bug happens with only WooCommerce plugin active
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X ] I can reproduce this bug consistently using the steps above

There is a pull request fixing this issue: #16267

**Comment by mikejolley** [comment]
A PR is enough, we don't need an issue logged too :) Thanks

**Comment by Valks** [comment]
Fair enough, some ask for both.
