### ISSUE TITLE
error 500 "create pending renewal"

### ISSUE THREAD

**Issue by vbarrier** [woocommerce/woocommerce#16274]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a subscription using woo commerce subscription
2. from subscription details in the backend hit "create pending renewal" 
3. error 500 

## Expected/actual behavior

When I follow those steps, I see...

[27-Jul-2017 08:50:03 UTC] PHP Fatal error:  Call to a member function meta_exists() on null in /home/web/icescrum.com/www/wp-content/plugins/woocommerce/includes/class-wc-checkout.php on line 1029

I was expecting to see...

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://www.icescrum.com
Site URL: https://www.icescrum.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.6.2
PHP Version: 5.6.30-1~dotdeb+7.1
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.26.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Admin Menu Editor: by Janis Elsts – 1.8
All In One SEO Pack: by Michael Torbert – 2.3.14.2
bbPress: by The bbPress Community – 2.5.13
Kagilum: by Kagilum SAS Team – 1.2
Kanalytics v2: by Kagilum SAS Team – 1.0
Latest Tweets Widget: by Tim Whitlock – 1.1.4
Livemesh SiteOrigin Widgets Pro: by Livemesh – 1.4.9
Shortcodes Ultimate: by Vladimir Anokhin – 4.10.2
Page Builder by SiteOrigin: by SiteOrigin – 2.5.8
SiteOrigin Premium: by SiteOrigin – 1.0.3
WPML Multilingual CMS: by OnTheGoSystems – 3.7.1
SiteOrigin Widgets Bundle: by SiteOrigin – 1.9.5
SyntaxHighlighter Evolved: by Alex Mills (Viper007Bond) – 3.2.1
User Switching: by John Blackbourn – 1.0.9
WooCommerce Bookings: by Automattic – 1.10.6
WooCommerce Customer Relationship Manager: by Actuality Extensions – 3.3.2
WooCommerce Email Customizer: by WooCommerce – 1.1.6
WooCommerce Emails Preview: by Vincent Barrier (Kagilum team) – 1.0
WooCommerce EU VAT Number: by WooCommerce – 2.3.0 – 2.3.1 is available
WooCommerce Filter Orders by Product: by Md. Kowsar Hossain – 2.0.7
Follow-Up Emails: by WooCommerce – 4.4.20
WooCommerce Stripe Gateway: by WooCommerce – 3.2.2
WooCommerce Multilingual: by OnTheGoSystems – 4.2.0
WooCommerce One Page Checkout: by Prospress Inc. – 1.5.2
WooCommerce Order Status Control: by SkyVerge – 1.8.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.0.4
Woocommerce Payment Gateway Per Product: by Dreamfox Media – 1.3.2
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.2
Woocommerce Subscriptions Pricing Table: by Vincent Barrier (Kagilum team) – 1.0
WooCommerce Subscriptions: by Prospress Inc. – 2.2.10
WooCommerce: by Automattic – 3.1.1
WordPress Importer: by wordpressdotorg – 0.6.3
WP OAuth Server - Pro: by WP OAuth Server – 3.4.1
WP Retina 2x: by Jordy Meow – 5.0.5
WP SAML Auth: by Pantheon – 0.3.1
WP Super Cache: by Automattic – 1.5.2
WPML Media: by OnTheGoSystems – 2.2.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: icescrum
Version: 1.5.6
Author URL: http://www.kagilum.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: icescrum/woocommerce/checkout/cart-errors.php
icescrum/woocommerce/checkout/form-checkout.php
icescrum/woocommerce/checkout/form-coupon.php
icescrum/woocommerce/checkout/form-pay.php
icescrum/woocommerce/checkout/payment.php
icescrum/woocommerce/checkout/review-order.php
icescrum/woocommerce/checkout/terms.php
icescrum/woocommerce/checkout/thankyou.php
icescrum/woocommerce/myaccount/form-edit-account.php
icescrum/woocommerce/myaccount/form-edit-address.php
icescrum/woocommerce/myaccount/form-login.php
icescrum/woocommerce/myaccount/form-lost-password.php
icescrum/woocommerce/myaccount/form-reset-password.php
icescrum/woocommerce/myaccount/lost-password-confirmation.php
icescrum/woocommerce/myaccount/my-account.php
icescrum/woocommerce/myaccount/my-orders.php
icescrum/woocommerce/myaccount/navigation.php
icescrum/woocommerce/myaccount/orders.php
icescrum/woocommerce/notices/error.php
icescrum/woocommerce/notices/notice.php
icescrum/woocommerce/notices/success.php
icescrum/woocommerce/single-product/add-to-cart/simple.php

### subscriptions ###

WCS_DEBUG: ❌ Yes
Subscriptions Mode: ✔ Live
`</details>

**Comment by mikejolley** [comment]
Please log this via the helpdesk so the subscriptions developers can be looped in.
