### ISSUE TITLE
Key with Read/Write permission can't update or delete resource, returns 401 

### ISSUE THREAD

**Issue by maantje** [woocommerce/woocommerce#16283]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
(I found a bunch of issues with the same problem but no fix was found.)
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. cd to working directory
2. composer init
3. composer require automattic/woocommerce
4. touch index.php
5. Create customer key and secret with read and **write** permissions
![screen shot 2017-07-28 at 16 04 57](https://user-images.githubusercontent.com/9058265/28720967-f6eb0bac-73ae-11e7-903b-6804185070dc.png)

6. Write the following code into index.php

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$customerKey = "ck_xxxxxxxxxxxxxxxxxxxxxxx216e96064cd63d896";
$customerSecret = "cs_xxxxxxxxxxxxxxxxxxxxxxx168c15706943b2ef";
$host = 'http://xxxxxxxx.nl';
$apiOptions = [
    'wp_api' => true,
    'version' => 'wc/v2',
];

$client = new Client($host, $customerKey, $customerSecret, $apiOptions);

$client->delete('products/588', ['force' => true]);
```
7. php index.php

## Expected/actual behavior

```
PHP Fatal error:  Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Sorry, you cannot view this resource. [woocommerce_rest_cannot_view] in WooCommerce/HttpClient/HttpClient.php:324
```

I was expecting the product to get deleted.

### Postman
I tried to see if it was some issue with the package by making the request with postman but that does not seem to change the result.

![screen shot 2017-07-28 at 16 15 52](https://user-images.githubusercontent.com/9058265/28721421-90278664-73b0-11e7-9466-117ed14af769.png)
### Other types of request
As the title suggest delete and update are both hit with this issue, getting all the products or a specific product works as expected. My costumer key has write access as seen in the screenshot of step 5, also tried to create a new one but that also did not change anything.
## Isolating the problem

- [n/a] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
### WordPress Environment ###

Home URL: http://xxxxxxx.xx
Site URL: http://xxxxxx.xx
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2
PHP Version: 5.6.9
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.42.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.24
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (10) ###

Contact Form 7: by Takayuki Miyoshi – 4.6
Duplicator: by LifeInTheGrid – 1.1.26
Hide Title: by Brandon Kraft & Randall Runnels – 1.0.4
Logo Slider: by Enigma Plugins – 1.4.7
Opportune Grid: by Shaped Pixels – 1.0.0
Opportune Shortcodes: by Shaped Pixels – 1.0.0
Real 3D Flipbook: by zlac – 2.13
WooCommerce PayPal Express Checkout Gateway: by Automattic – 1.1.2
WooCommerce: by Automattic – 3.1.1
Yoast SEO: by Team Yoast – 4.0.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #573 - /winkel/
Cart: #574 - /winkelmand/
Checkout: #575 - /afrekenen/
My account: #576 - /mijn-account/

### Theme ###

Name: Opportune Pro
Version: 1.0.1
Author URL: http://www.shapedpixels.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: opportune-pro/woocommerce/archive-product.php
opportune-pro/woocommerce/global/breadcrumb.php
opportune-pro/woocommerce/global/form-login.php
opportune-pro/woocommerce/global/quantity-input.php version 2.1.0 is out of date. The core version is 2.5.0
opportune-pro/woocommerce/global/sidebar.php
opportune-pro/woocommerce/global/wrapper-end.php
opportune-pro/woocommerce/global/wrapper-start.php
opportune-pro/woocommerce/loop/pagination.php
opportune-pro/woocommerce/notices/error.php
opportune-pro/woocommerce/notices/notice.php
opportune-pro/woocommerce/notices/success.php
opportune-pro/woocommerce/single-product/review.php version 2.1.0 is out of date. The core version is 2.6.0
opportune-pro/woocommerce/single-product-reviews.php
opportune-pro/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
</details>

**Comment by mikejolley** [comment]
I think it's because you're using basic auth over http. Use https.

Auth over http is more complicated: https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

If it works over https, maybe log an issue for the client so it errors more gracefully https://github.com/woocommerce/wc-api-php/issues

Thanks

**Comment by maantje** [comment]
Hey, @mikejolley sorry for the delay but we got everything over to https and now the error is gone. but the resource does not actually update, same for delete. this is using the Automattic\WooCommerce package. Trying it in postman over https I still get the same error

``` json
{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot view this resource.",
  "data": {
    "status": 401
  }
}
```

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#server-does-not-support-postdeleteput

**Comment by maantje** [comment]
@mikejolley I followed the link you sent me. Adding the ?_method=DELETE did not change anything on OAuth 1.0, Also tried it on Basic Auth then I don't get an error but I get the resource returned as JSON but it is still not deleted. Also tried to remake the consumre secret and key a couple times but that also did not do anything. Any more ideas what this could probably be?

**Comment by mikejolley** [comment]
Is there a specific user/role creating these keys?

Can you shown the non-domain part of the request URL made to postman too? Use the headers for auth, not query string.

**Comment by maantje** [comment]
I am creating the keys with one of the two admin users that are available. 

Here is the request made by Postman

![screen shot 2017-08-21 at 11 20 56](https://user-images.githubusercontent.com/9058265/29512692-3816e530-8663-11e7-8df8-6cbea35dfc85.png)

**Comment by mikejolley** [comment]
I'm not sure what to suggest. I'm using the same request as you locally. If I run it twice, the next response states "woocommerce_rest_already_trashed".

I can only assume something else installed is blocking access to this.

You could do some debugging around the `wc_rest_check_post_permissions` function. See what user it is checking/what caps are failing.

**Comment by maantje** [comment]
I am currently pretty sure it has something to do specifically with the server it is currently running on, I tried to install Wordpress and Woocommerce locally there everything seems to work as expected. 

We are probably going to migrate everything over now to a different server as this will probably be faster than debugging the current one. 

When I have some more time I'll try and see if I can find what is causing it, I will update this issue if I find anything. 

Thanks for your time and help!
