### ISSUE TITLE
Variations Conflict

### ISSUE THREAD

**Issue by contactbecker** [woocommerce/woocommerce#16285]
Hi there,
I just upgraded to 3.1.1 and can not get into my variations pricing now.  It just hangs.  This is the error code I see when using chrome console below:
![screen shot 2017-07-28 at 11 12 37 am](https://user-images.githubusercontent.com/760055/28730623-c90133fc-7385-11e7-9e42-04f12754fa83.png)
------
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:9 JQMIGRATE: Migrate is installed, version 1.4.1
wc-enhanced-select.min.js:1 Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.js:21)
    at Function.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2)
    at d.prepareOpts (select2.js:21)
    at d.prepareOpts (select2.js:21)
    at d.init (select2.js:21)
    at HTMLSelectElement.<anonymous> (select2.js:22)
    at Function.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2)
    at a.fn.init.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:2)
    at a.fn.init.a.fn.select2 (select2.js:22)
    at HTMLSelectElement.<anonymous> (wc-enhanced-select.min.js:1)
plugin.min.js?ver=4603-20170530:1 Deprecated TinyMCE API call: <target>.onChange.add(..)

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by contactbecker** [comment]
Here is the next error code when clicking on variations tab:
![screen shot 2017-07-28 at 11 15 11 am](https://user-images.githubusercontent.com/760055/28730766-350c0158-7386-11e7-89f0-74cfa041246f.png)

**Comment by mikejolley** [comment]
Please see https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x
