### ISSUE TITLE
Quick Edit doesn't allow Variable products to be moved from "Out of Stock"

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#16287]
If I have a variable product where stock is managed on the product level, I can put it out of stock and change the quantity in stock with quick edit, but to move it from Out of Stock to In Stock, I need to open the product and do it from that page.

Mini screencap/gif: http://recordit.co/lNLo7U1b9H

I can provide admin creds to the test site this is configured on if you need - just ping me on Slack. 👍 

609856-zd-woothemes

**Comment by EdithKarnitsch** [comment]
For [16300](https://github.com/woocommerce/woocommerce/issues/16300), please note that this was tested with a simple product, not variable, hence why I submitted it separately. apologies for duplication.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16367
