### ISSUE TITLE
Random Items appearing in woocommerce orders at checkout, Need help!

### ISSUE THREAD

**Issue by Aaronomary** [woocommerce/woocommerce#16282]
I'm having this exact issue - https://github.com/woocommerce/woocommerce/issues/15671

Basically, at checkout my customers get 1 random item added to the order. It doesn't charge them any extra for it, but it does stay on the order checklist - so if it does get in their order, they get 1 free item. It's a horrible problem, customers complains have sky rocketed, all asking why they are being charged for a product they never purchased etc etc etc. it's real bad.

**Comment by mikejolley** [comment]
If you don't provide the details requested on the 'new issue' screen this will be closed. https://github.com/woocommerce/woocommerce/issues/new

**Comment by Aaronomary** [comment]
just close it thanks

**Comment by mikejolley** [comment]
@Aaronomary Why? Did you find the issue?

**Comment by Aaronomary** [comment]
Sorry, I just couldn't figure out that form - but I read this line
 " If you need technical support from a human being, please submit a ticket via the helpdesk instead: https://woocommerce.com/contact-us/ -->" 
And I think that's my best bet right now.
Thanks

**Comment by mikejolley** [comment]
Ok 👍 Yeah, if support can find the issue they can report it instead. Thanks!
