### ISSUE TITLE
Sorry, your session has expired. Return to shop

### ISSUE THREAD

**Issue by eselim03** [woocommerce/woocommerce#16298]
Whenever i am trying to checkout from my website its showing a red notification telling "Sorry, your session has expired. Return to shop"  i tried resolving by deactivating all plugins but i found it same.Can anyone help please ???

**Comment by mikejolley** [comment]
> Hi there! This form is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. If you need technical support from a human being, please submit a ticket via the helpdesk instead: https://woocommerce.com/contact-us/
