### ISSUE TITLE
[Include my solution] Bug : Failed of product import with multiple image urls

### ISSUE THREAD

**Issue by aonzzung** [woocommerce/woocommerce#16299]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Download sample csv : http://docs.woocommerce.com/wp-content/uploads/2015/02/WooCommerce-Sample-Products.csv
2. Add "images" column to it.
3. Enter image url of external site with pipe separation

**Modified Sample csv**

[WooCommerce-Sample-Products.zip](https://github.com/woocommerce/woocommerce/files/1187370/WooCommerce-Sample-Products.zip)

## Expected/actual behavior

When I follow those steps, I see...

- Failed to import product. Unable to download images

I was expecting to see...
- The product must be correctly imported.
- Try both "|" and " | " (pipe with spaces) and the import still failed
- A product with only one image url can be imported. No problem with it.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Wordpress version : 4.8
WC version: 3.1.1
WC Database Version: 3.1.1
```
</details>

**Comment by aonzzung** [comment]
**class-wc-product-csv-importer.php**
`public function parse_images_field( $field ) {
		if ( empty( $field ) ) {
			return array();
		}

		return array_map( 'esc_url_raw', array_map( 'trim', explode( ',', $field ) ) );
	}`

I noticed that the explode uses ',' instead of '|' as documented ?

**Comment by aonzzung** [comment]
I modified it to `explode( '|', $field )` and the upload works!

Please fix this 

Thanks

**Comment by mikejolley** [comment]
Should not be using pipes.

https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

**Comment by claudiosanches** [comment]
This is not the correct sample file: Download sample csv : http://docs.woocommerce.com/wp-content/uploads/2015/02/WooCommerce-Sample-Products.csv

You can get the correct one inside the WooCommerce folder after download on WordPress.org or here in GitHub: https://raw.githubusercontent.com/woocommerce/woocommerce/master/dummy-data/dummy-data.csv

**Comment by Radmation** [comment]
The documentation here: https://docs.woocommerce.com/document/product-csv-import-suite-column-header-reference/ doesn't match this documentation: https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema which caused me grief... 

Any idea on how we can request or report issues with the https://docs.woocommerce.com/?

**Comment by mikejolley** [comment]
Thats a different import plugin.
