### ISSUE TITLE
Mark product reviews with the "review" type

### ISSUE THREAD

**Issue by Sophivorus** [woocommerce/woocommerce#16297]
When a user posts a review to a product,  it's stored in the database as a comment with no specific comment_type. Now I'm trying to develop a plugin that allows users to post questions about the products. I'm storing these questions as comments to the product, with the comment_type "question". But the questions show under the Reviews tab of the product, because WooCommerce simply displays all comments to the product as reviews, regardless of comment_type. WooCommerce should mark reviews with the comment_type "review", and display ONLY reviews under the Reviews tab.

**Comment by mikejolley** [comment]
Reviews have no specific type because they **are** comments. The review/rating is meta data. Creation of reviews/comments is left to WordPress.

Filters can be used to filter out custom comment types when they are retrieved. You can use this to prevent it outputting questions, and output them separately.

**Comment by justinshreve** [comment]
@mikejolley I'm running into an issue with this myself. There is no way to figure out if a comment is a review unless you check the parent post to see if it is a product. Other comment types (web hook deliveries or order notes) both contain a proper type in the table. For reviews, this field is just empty. Even though reviews are comments, it does feel a bit odd that the `comment_type` for these is just blank.

It also seems like some parts of the code base assume a type is set when there is none: [example 1](https://github.com/woocommerce/woocommerce/blob/62800a68f961c1fd00f01f4626e848d582d5f55c/includes/class-wc-comments.php#L265), [example 2](https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/api/v1/class-wc-rest-product-reviews-controller.php#L455).
