### ISSUE TITLE
Documentation Issue: woothemes_queue_update

### ISSUE THREAD

**Issue by Ipstenu** [woocommerce/woocommerce#16304]
There have been a lot (5 today) of plugins submitted to the .org directory that all use woothemes_queue_update and are set up for updates that way.

I can only presume that they don't realize they DON'T need any self-update magic if they're going to be hosted on .org. Can you perhaps update the documentation to let them know about this? It would make their reviews go faster and they'd be happier :)

**Comment by mikejolley** [comment]
@Ipstenu This function has no documentation - I think the only way people would use it is if they were blindly copying premium extensions? It's not included in new extensions FWIW.

Not sure where this would need to documented, nor if it would have any impact :)

**Comment by Ipstenu** [comment]
Well foo. People were saying "But the documentation I read..." and in lieu of them telling me _where_ that doc was I did the default hope... Ah well. Thank you anyway!
