### ISSUE TITLE
Coupon discounted cart total is a penny off when tax is also applied 

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#16305]
#### Affected ticket(s)

602130-zd-woothemes

Tested with latest master

#### What I expected

This is very specific to when total price - discount % = a sub total that has three decimal places and should get rounded up.

For example, you have a $51.86 product in cart. Add a 40% coupon, for a discount of $20.744.
51.86 - 20.744 = 31.116 

It should round to 31.12. It does if tax is not involved:

![](http://cld.wthms.co/gJbVt+)
Link to screenshot: http://cld.wthms.co/gJbVt

When tax is added (one that needs to be rounded up by the third decimal), like 8.25% tax, the cart total breaks down calculations so it should look like:

$51.86 - $20.74 = 31.12
31.12 + 2.57 = 33.69

#### What happened instead

However, it's one cent off:

![](http://cld.wthms.co/VPJ8pG+)
Link to screenshot: http://cld.wthms.co/VPJ8pG

it's possible I'm not understanding the rules we have for rounding...let me know!

@claudiosanches

**Comment by mikejolley** [comment]
@claudiulodro I wouldn't "fix" this until we do the discounts API, but can you add a test for this one like we do the others?

**Comment by mikejolley** [comment]
@yukikatayama Discounts get split across all products which is why small rounding errors occur like this. @claudiulodro has added a test for this case specifically so we'll have it fixed (or documented) in 3.2. Thanks.
