### ISSUE TITLE
WooCommerce 3.1.1 - New order emails 

### ISSUE THREAD

**Issue by MattRussell92** [woocommerce/woocommerce#16310]
Hi, 

Has anyone else had any issues with the new WooCommerce and not receiving new order emails. All other emails come through fine, just the initial new order email to the vendor. 

Absolutely Stumped. 

Cheers

**Comment by jbrenner99** [comment]
Look at https://github.com/woocommerce/woocommerce/issues/15664 Maybe this is the situation you are having

**Comment by mikejolley** [comment]
Yeah that ^ See https://docs.woocommerce.com/document/email-faq/
