### ISSUE TITLE
Add product image in rest api order call 

### ISSUE THREAD

**Issue by RichPert** [woocommerce/woocommerce#16315]
Hello , im making an app which use woocommerce rest api .

I need to insert the image of the product in the order response . Im using the woocommerce rest api for 2 days and i dont know how to to that . 

I have edited the class-wc-api-orders.php and inserted the wp_get_attachment_url( get_post_thumbnail_id( $product->get_id() ) ), but it dont work . 

I hope you can help me .

Best regards

**Comment by mikejolley** [comment]
You need to use the product endpoint to update a product image. See supported props here https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

**Comment by RichPert** [comment]
I haven't explained well the problem .I need to insert the image src in my json response in the wp-json/wc/v2/orders call . There is a way to do that? 

Thanks for the support

**Comment by kolonuk** [comment]
I can't find any way to load images to the filesystem, so I'm thinking about converting all my images to base64 and storing them in the database that way...

`<img src="data:image/png;base64,**YourBase64EncodedPNGImage**">`

**Comment by sakthivelr** [comment]
Hi, I am also waiting this result

**Comment by AniketMalik** [comment]
> I haven't explained well the problem .I need to insert the image src in my json response in the wp-json/wc/v2/orders call . There is a way to do that?
> 
> Thanks for the support

Did you manage to do it ? If yes, please share the way to implement it.
Thanks

**Comment by kolonuk** [comment]
The orders API doesn't have an image property.  See the API documentation: https://woocommerce.github.io/woocommerce-rest-api-docs/#orders

You can use the order meta data property: https://woocommerce.github.io/woocommerce-rest-api-docs/#order-meta-data-properties

If that doesn't work for you, you will need to create your own custom API call, or edit the existing API call.
