### ISSUE TITLE
GeoIP uses Proxy IP instead of Customer-IP

### ISSUE THREAD

**Issue by DavidSteinbauer** [woocommerce/woocommerce#16319]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Nginx Proxy in Forein Country with X-forward-for Variable
2. Defining Proxy Varibales in wp-config.php https://gist.github.com/anonymous/3b32eb47319c1489211d293212dc0d97
3. Analysing GeoIp Country Code with `WC()->customer->get_billing_country();`

## Expected/actual behavior

When I follow those steps, I see the country of my proxy location

I was expecting to see to see my own country

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://www.annakateshop.com
Site URL: http://www.annakateshop.com
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.14-nmm1
PHP Post Max Size: 200 MB
PHP Time Limit: 0
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.0
WC Database Prefix: JntVx_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (27) ###

All-in-One WP Migration: by ServMask – 6.50
Amazon Web Services: by Delicious Brains – 1.0.3
Duplicate Post: by Enrico Battocchi – 3.2
Favicon by RealFaviconGenerator: by Philippe Bernard – 1.3.10
GitHub Updater: by Andy Fragen – 6.3.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
InfiniteWP - Client: by Revmakx – 1.6.5
Password Protected: by Ben Huson – 2.0.3
Popup Maker: by WP Popup Maker – 1.6.3
Rename wp-login.php: by Ella Iseulde Van Dorpe – 2.5.5
SI Captcha Anti-Spam: by fastsecure – 3.0.0.20
WPML Multilingual CMS: by OnTheGoSystems – 3.7.1
Widget Logic: by wpchefgadget
alanft – 5.8.2

Woo Preview Emails: by Digamber Pradhan – 1.2.8
WooCommerce Stripe Gateway: by WooCommerce – 3.2.1
WooCommerce MailChimp: by Saint Systems – 2.1.0
WooCommerce Multilingual: by OnTheGoSystems – 4.2.0
WooCommerce PDF Invoices: by Andrew Benbow – 3.7.2 – 3.7.5 is available
WooWaitlist: by WPCream.com – 4.0.3
WooCommerce: by Automattic – 3.1.0 – 3.1.1 is available
Yoast SEO: by Team Yoast – 5.0.1
WP LESS: by Oncle Tom – 1.8.0
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP Migrate DB: by Delicious Brains – 0.9.2
WPML Media: by OnTheGoSystems – 2.2.0
WPML String Translation: by OnTheGoSystems – 2.5.4
WPML Translation Management: by OnTheGoSystems – 2.3.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #759 - /shop/
Cart: #507 - /cart/
Checkout: #28 - /checkout/
My account: #29 - /my-account/

### Theme ###

Name: Enfold Child
Version: 1.0.0
Author URL: http://www.innovie.de
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.1
Parent Theme Author URL: http://www.kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: enfold-child/woocommerce/emails/customer-completed-order.php
enfold-child/woocommerce/emails/customer-new-account.php
enfold-child/woocommerce/emails/customer-on-hold-order.php
enfold-child/woocommerce/emails/customer-processing-order.php
enfold-child/woocommerce/emails/email-addresses.php
enfold-child/woocommerce/emails/email-header.php
enfold-child/woocommerce/emails/email-order-details.php
enfold-child/woocommerce/emails/email-styles.php

`
```
</details>

**Comment by mikejolley** [comment]
I'm not convinced there is a way around that - isn't this one of the reasons people use proxies? To mask real IPs?

> With the ease of setting up and joining/using proxying services (especially those specializing in providing anonymity, such as Tor), it would be impossible for any company to legitimately claim to be able to "unmask" someone behind a proxy based on having some kind of relationship with ISPs and proxy services, to say nothing of the sheer volume of those and how monumental a task it would be to form those relationships in the first place.

https://superuser.com/questions/284927/how-to-get-the-real-ip-address-of-someone-using-a-proxy

It seems we do the best we can with the given data. See https://github.com/woocommerce/woocommerce/blob/66f2ea25e966981211877cc21ebb602aa238767b/includes/class-wc-geolocation.php#L100-L111

Please correct me if I'm wrong with any of the above.

**Comment by DavidSteinbauer** [comment]
Sorry, I didn't explained it correct. It is always taking *my nginx reverse proxy servers* IP address. instead of the X-Real-IP.

My Nginx Proxy Config looks like this:

`	proxy_set_header		X-Real-IP			$remote_addr;
`
still getting Austria as my Customer Country (even the user [myself] is in Germany)

**Comment by DavidSteinbauer** [comment]
I think, i found the error:

Could it be that PHP uses $_SERVER['HTTP_X_REAL_IP'] not $_SERVER['X-Real-IP'] ?

ref: https://easyengine.io/tutorials/nginx/forwarding-visitors-real-ip/

**Comment by claudiulodro** [comment]
> Could it be that PHP uses $_SERVER['HTTP_X_REAL_IP'] not $_SERVER['X-Real-IP'] ?

Good catch. We'll have that fixed in an upcoming release.

I think you also need `proxy_set_header X-Real-IP $remote_addr;` to use that with your reverse proxy. ([ref](https://ypereirareis.github.io/blog/2017/02/15/nginx-real-ip-behind-nginx-reverse-proxy/)) Otherwise it will just be the address of the proxy server. ([ref](https://gtranslate.io/forum/http-real-http-forwarded-for-t2980.html#p12334))

It looks like the X-Forwarded-For should be working correctly, though. Can you check your logs and confirm that the first IP address in the X-Forwarded-For after it goes through the reverse proxy is the client ip? ([ref](https://en.wikipedia.org/wiki/X-Forwarded-For#Format))

**Comment by DavidSteinbauer** [comment]
in my case i have to 

```unset($_SERVER['GEOIP_COUNTRY_CODE']);```

otherwise the IP will not be resolved.

Due to: 
https://github.com/woocommerce/woocommerce/blob/6995e6ec84ae981b7f5233404e12b07befab78ce/includes/class-wc-geolocation.php#L202
