### ISSUE TITLE
get_item() function returns false

### ISSUE THREAD

**Issue by aashayshah** [woocommerce/woocommerce#16314]
With WooCommerce 3.1.1

Consider the following code in my plugin:

```
$order = wc_get_order($order_id);
$id= 27;
var_dump($order->get_item($id));
```
the var_dump gives me `bool(false)`. 

I have checked the database and the order and the item exists.

Also, `var_dump($order)` returns the entire WC_Order object with all the items.

So basically, only the function `get_item` does not seem to work.

I don't believe that looping through `$order->get_items()` in a foreach loop makes sense.

Is this a bug?

**Comment by mikejolley** [comment]
This can happen if the item has an unrecognised type. Do some debugging in `get_order_item` method which is part of `class-wc-order-factory.php`

https://github.com/woocommerce/woocommerce/blob/6dfdc861112e5fbe7e01ec4be3072d5a23208850/includes/class-wc-order-factory.php#L58
