### ISSUE TITLE
Import of Products with attributes

### ISSUE THREAD

**Issue by bpgs** [woocommerce/woocommerce#16322]
I use WP 4.7.5 and WooCommerce 3.1.1. I use this for a tiny online-bookshop. I've a lot of attributes for my products. When I import (with a ` ;` as CSV-Seperator)
`"Attribute 1 name";"Attribute 1 value(s)";"Attribute 1 visible";"Attribute 1 global";`
`"Publishing";"Lenos Verlag, Basel";1;1;`
then I get the result Basel | Lenos Verlag
As well the import of a product with a category, that contains a` ,`; e.g. the result of
"Categories"
Schwank, Anekdote und Witz
are two seperated categories, one _Schwank_ and the other _Anekdote und Witz_

**Comment by mikejolley** [comment]
Categories/attributes with commas will be supported in 3.2. When thats out you'll be able to wrap each string with quotes e.g. `Lenos Verlag, Basel, "Schwank, Anekdote und Witz"`

Thanks
