### ISSUE TITLE
Custom Meta Boxes and API

### ISSUE THREAD

**Issue by amjad** [woocommerce/woocommerce#16320]
Is it possible to add custom meta boxes to products and have them viewable via the REST API? Any plugin that can do this?

**Comment by mikejolley** [comment]
No. But the rest api can be extended separately.

**Comment by amjad** [comment]
I was able to do this with ACF Pro.

**Comment by el-rotny** [comment]
@amjad We are using a combination of ACF and ACF-to-Rest-API . Trying to figure out a way to make that work. I would expect the WC API to work the same way the WP API works, but it doesnt seem like thats the case.

**Comment by amjad** [comment]
ACF works perfectly for me with the WC API. I did not install that ACF-to-Rest-API plugin.
