### ISSUE TITLE
Variable product not working in quick view

### ISSUE THREAD

**Issue by presslayouts** [woocommerce/woocommerce#16328]
Hello Mike,

When i open variable product in our quick view popup then product variation not working and not change product images.

```
setTimeout(function() {
	if ( $( '.product-quickview form' ).hasClass( 'variations_form' ) ) {
		$( '.product-quickview variations_form' ).wc_variation_form();
		$( '.product-quickview select' ).trigger( 'change' );
	}
}, 100);
```
Display js error wc_variation_form() function not founded.

So please give me hint for our mistack/problem.

Thank you,
PressLayouts.

**Comment by mikejolley** [comment]
Your plugin needs to a) check the function exists first and b) enqueue the variation JS. This is not a core issue.
