### ISSUE TITLE
Updating status of order with a large number of items takes too long (500 items) can be over 2 mins

### ISSUE THREAD

**Issue by iosdevel** [woocommerce/woocommerce#16326]
Hi there,
Another issue with handling large orders.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue
1. Update status of an order which contains 500 items can take up to 2mins on a very fast server, no plugins. This is the same from either within the order page, just selecting a single order and doing a bulk action or calling $order->update_status().

2. This is also the case on checkout when a new order is created.

Updating the status using a standard post status update is super quick. It must be something to do with the amount of order items but that should really have nothing to do with simply updating the parent order status.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by pmgarman** [comment]
This is potentially happening [here](https://github.com/woocommerce/woocommerce/blob/3939f50ceda0229b4df7e06f86862acbc4151842/includes/class-wc-order.php#L1358-L1375).

`update_status()` > `set_status()` > `maybe_set_date_paid()` > `needs_processing()`

The order is checking if it _needs processing_ which means it loops every order item in the order, gets the product object, checks if it is downloadable, checks if it is virtual, then runs the `woocommerce_order_item_needs_processing` filter on the result to allow for third party code to tap in here as well.

Even with a decent infrastructure here, the sheer volume of queries that is going to be created from 500 products on an order to gather all the products and relevant data...

(napkin math)

500 products * 0.1 seconds / product = 50 seconds

When most hosts default to around a 30 second timeout, this will turn into 502 timeout errors, could lead to 500 hitting memory limit errors.

It's certainly an edge case, I'm not sure of the best way to try to approach resolving. One thought is to write to the order item meta if a product is virtual or downloadable, benefits here is simpler querying, downside being when a product is later modified something would either need to automatically or through manual intervention be run to go back and re-apply that order item meta. In that scenario I think a manual click of a button that appears in a notice or somewhere after editing the product "apply this change to past orders" which triggers a background process of applying that update similar to how the WC database migrations are handled which would help ensure it runs well on large installs.

**Comment by iosdevel** [comment]
Hi there,

Thanks for the reply. I did some logging and it seems the most amount of time is spent in abstract-wc-order -> save_items() function. I guess this might be needed when posting data from the orders screen(potentially) but is it necessary from the orders list as a bulk action to update status or even just calling $order->update_status() ?
Also, is it the case the the metadata is always written to the db even if there was no change? If so, this is surely an unnecessary (and expensive) operation.
Just as an FYI, the majority (99.99%) of our sales are for phyical goods so the needs_processing() is not really an issue in terms of how long it takes in our case.
Right now, for my custom methods, I'm just updating the order status (using custom order statuses) with the standard post status update function to avoid all the time consuming operations as they aren't linked to any order payment methods. However, this feels like a bit of a hack really. Do you have any thoughts?

**Comment by mikejolley** [comment]
Since this spans a few items I've logged here: https://github.com/woocommerce/woocommerce/issues/16366 There are a few things we can change to resolve this.
