### ISSUE TITLE
wc_get_orders returning empty objects

### ISSUE THREAD

**Issue by davetgreen** [woocommerce/woocommerce#16321]
I'm doing some work with a custom endpoint to expose some high level store stats, and encountering a problem where `wc_get_orders` returns an array of empty objects.

## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Example code that highlights the issue...

```
function register_davetgreen_rest_routes() {

	register_rest_route( 'davetgreen/v1', '/stats/', array(
		'methods' => 'GET',
		'callback' => 'davetgreen_stats_endpoint_callback'
	) );
};
add_action( 'rest_api_init', 'register_davetgreen_rest_routes' );

function davetgreen_stats_endpoint_callback( \WP_REST_Request $request ) {

	// Validate the required endpoint argument.
	$after = $request['after'];

	if ( empty( $after ) ) {
		return new WP_Error( 'davetgreen_no_period', 'No date period provided.', array( 'status' => 401 ) );
	}

	$orders = wc_get_orders( [
		'type'    => 'shop_order',
		'date_created' => '>=' . strtotime( $after ), // $after is an ISO8601 string
	] );

	return $orders;
}
```

Worth noting here that the problem occurs regardless of whether `date_created` is passed in, and actually works if you set `'return' => 'ids` in the arguments. Using `WC_Order_Query` makes no difference.

## Expected/actual behavior

When I follow those steps, I see...**an array of empty objects**

I was expecting to see...**an array of order objects**

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://local.woocommerce.dev
Site URL: http://local.woocommerce.dev
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.13.1
PHP Version: 7.0.19-1+deb.sury.org~trusty+2
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

ShopKeep: by Dave Green  – 0.1.0
WooCommerce: by Automattic – 3.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
I suspect you're using this too early, before the order post types are registered. @claudiulodro can you confirm? If this is the case it will need to return an error I assume, unless you request ids.

**Comment by davetgreen** [comment]
thanks @mikejolley I had a hunch it was that but wanted to raise it anyway.

**Comment by claudiulodro** [comment]
I've investigated this. The order post types are registered and ready. If you put a `var_dump( $orders );` before the orders are returned you'll see all of the order objects are present. 

I think you're not getting anything useful out of it because Order objects won't automatically convert to JSON. You need something [like this](https://github.com/woocommerce/woocommerce/blob/master/includes/api/v1/class-wc-rest-orders-controller.php#L127) to convert an Order into something that can be output as JSON. You can probably just use that method, or copy+paste the parts you need. :)
