### ISSUE TITLE
Date / Time hover in orders list

### ISSUE THREAD

**Issue by amjad** [woocommerce/woocommerce#16331]
In 2.6.x when you hover over the date in the orders list on dashboard, it gave the time stamp, this was very useful to quickly check the time of the order without opening the order. 

In 3.x this does not work anymore. Is there a way to enable this back again? Thanks.

**Comment by amjad** [comment]
?

**Comment by claudiosanches** [comment]
@amjad thanks for let us know about it, this as been closed and solved by this commit: https://github.com/woocommerce/woocommerce/commit/958bd092bae566e2154d31fd38911ef8bdddad11
