### ISSUE TITLE
order status is showing pending even after the payment is received

### ISSUE THREAD

**Issue by Gowsalayadevi** [woocommerce/woocommerce#16333]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Expected/actual behavior
Hi , I updated my wordpress website to the newest wordpress(4.8) and woocommerce(3.1.1) version. The order status is pending when the customer paying through paypal account even if I am getting the payment. 
Could you please let me know how to fix this issue

## Isolating the problem

- [ X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://ceilingfanswarehouse.com.au
Site URL: https://ceilingfanswarehouse.com.au
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 900 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 20 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

All In One Schema.org Rich Snippets: by Brainstorm Force – 1.5.1
CategoryTinymce: by Kevin Heath – 3.6.4
Contact Form 7: by Takayuki Miyoshi – 4.8.1
Display Posts Shortcode: by Bill Erickson – 2.8.0
Google Customer Reviews for WooCommerce: by eCreations – 1.0.4
Eggplant 301 Redirects: by Shawn Wernig http://www.eggplantstudios.ca – 2.3.0
Excel Like Price Change for WooCommerce and WP E-commerce - Light: by Holest Engineering – 2.1.4
Follow up email: by Hungnam – 3.2.0
HS Social Media Buttons: by Helios Solutions – 2.0.7
Improved Sale Badges - Free Version: by Mihajlovic Nenad – 1.0.1
JS & CSS Script Optimizer: by Yevhen Kotelnytskyi – 0.3.3
Max Mega Menu - Pro Addon: by Tom Hemsley – 1.6.2.1
Max Mega Menu: by Tom Hemsley – 2.3.7.1
Recover Abandoned Cart: by Fantastic Plugins – 13.2
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Relevanssi: by Mikko Saari – 3.5.11.1
Revision Control: by Dion Hulse – 2.3.2
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1
Fast Secure Contact Form: by fastsecure – 4.0.54
Transients Manager: by Pippin Williamson – 1.7.3
WC Show Line Total: by Coen Jacobs –
WooCommerce Save & Share Cart: by cxThemes – 2.07
WooCommerce Filter Search: by Pinch Of Code – 1.0.2
WooCommerce ANZ eGate Gateway: by WooCommerce – 2.1.5
WooCommerce Inecom Integration: by OPMC – 1.0.0
WooCommerce Pre-Sales / Time offers: by Lagudi Domenico – 5.8
WooCommerce Sequential Order Numbers Pro: by WooThemes / SkyVerge – 1.8.0 – 1.11.2 is available
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.4
WooCommerce: by Automattic – 3.1.1
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 5.1
Wordpress Login Delay: by Mike – 1.2
WP Maintenance Mode: by Designmodo – 2.0.9
WP Super Cache: by Automattic – 1.5.3
WPS Hide Login: by Remy Perona for WPServeur – 1.1.7
YITH WooCommerce Tab Manager: by YITHEMES – 1.1.8

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #8 - /shop/
Basket: #9 - /cart/
Checkout: #10 - /checkout/
My account: #12 - /my-account/

### Theme ###

Name: SuperStore Child Theme
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Superstore
Parent Theme Version: 1.2.18
Parent Theme Author URL: http://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: superstore/woocommerce/archive-product.php
superstore/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.0.0
superstore/woocommerce/content-product_cat.php
superstore/woocommerce/emails/admin-cancelled-order.php version 2.4.0 is out of date. The core version is 2.5.0
superstore/woocommerce/emails/admin-new-order.php version 2.4.0 is out of date. The core version is 2.5.0
superstore/woocommerce/emails/customer-completed-order.php version 2.4.0 is out of date. The core version is 2.5.0
superstore/woocommerce/emails/customer-invoice.php version 2.4.0 is out of date. The core version is 2.5.0
superstore/woocommerce/emails/customer-new-account.php
superstore/woocommerce/emails/customer-note.php version 2.4.0 is out of date. The core version is 2.5.0
superstore/woocommerce/emails/customer-processing-order.php version 2.4.0 is out of date. The core version is 2.5.0
superstore/woocommerce/emails/customer-refunded-order.php version 2.4.0 is out of date. The core version is 2.5.0
superstore/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
Please see the steps in https://docs.woocommerce.com/document/paypal-standard/. Several solutions/troubleshooting steps are documented already.

**Comment by portraitflip** [comment]
got it
