### ISSUE TITLE
Prevent caching on cart actions

### ISSUE THREAD

**Issue by oscargare** [woocommerce/woocommerce#16337]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add next directive to .htaccess:
```
<IfModule mod_expires.c>
ExpiresDefault "access 2 days"
</IfModule>
```
2. Add a simple product to cart.
2. Go to cart.
2. Remove item from cart.
3. Return to shop and add the same product to cart.
4. Try to remove item from cart, the item is not removed.

The headers of ***/cart/?remove_item=9ae568c605ef56fbb93727dddd855f62&_wpnonce=746cdea9c6

Server:"nginx"
Date: "Thu, 03 Aug 2017 08:37:57 GMT"
Content-Type: "text/html; charset=UTF-8"
Content-Length: "0"
Location: "***/cart/?removed_item=1"
**Cache-Control: "max-age=172800"**
Expires: "Sat, 05 Aug 2017 08:37:57 GMT"
host-header: "192fc2e7e50945beb8231a492d6a8024"
x-proxy-cache: "BYPASS"

The browser is caching the page because 'update_cart_action' is hooked on' wp_loaded' and is runned before 'prevent_caching' that is hooked on 'wp'. After remove the item, 'update_cart_action'  function does a redirect, so prevent_caching is not runned.
The same problem occurs with 'add_to_cart_action

## Expected/actual behavior

Moving 'update_cart_action' and 'add_to_cart_action' to template_redirect should fix the problem.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: ***
Site URL: ***
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.21
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (11) ###

Awesome Support WooCommerce for PBC: by Oscar Gare – 1.0.0
Awesome Support: by ThemeAvenue – 3.3.1
Page Builder by SiteOrigin: by SiteOrigin – 2.5.9
SiteOrigin Widgets Bundle: by SiteOrigin – 1.9.5
WooCommerce Cookie Consent: by Oscar Gare – 1.0.0
WooCommerce Stripe Gateway: by WooCommerce – 3.2.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce Plugin API: by Oscar Gare – 1.0.1
WooCommerce Widgets Template for Site Origin: by Oscar Gare – 1.0.1
WooCommerce: by Automattic – 3.1.1
Yoast SEO: by Team Yoast – 4.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #99 - /addons/
Cart: #100 - /cart/
Checkout: #101 - /checkout/
My account: #102 - /my-account/

### Theme ###

Name: Storefront Price Based Country
Version: 1.1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 1.6.1 – 2.2.4 is available
Parent Theme Author URL: http://www.woothemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/emails/customer-completed-order.php
storefront-child/woocommerce/emails/email-order-details.php
storefront-child/woocommerce/emails/email-order-items.php
storefront-child/woocommerce/emails/email-styles.php
storefront-child/woocommerce/myaccount/form-login.php
storefront-child/single-product.php

`
```
</details>

**Comment by oscargare** [comment]
I added a pull request
https://github.com/woocommerce/woocommerce/pull/16342

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16360

**Comment by AndyRLockhart** [comment]
Hi

We are having cart caching issues, order placed and cart still has content.  Will this code work for this do you think.

**Comment by nvtho** [comment]
I think it be cache but not sloved!
