### ISSUE TITLE
BUG 4 decimal and Subscription not working

### ISSUE THREAD

**Issue by vucumbra** [woocommerce/woocommerce#16344]
Hi
if my ecommerce have 4 decimal and if i have subscription product, paypal get a error about the price and customer can't finish order
please help

**Comment by mikejolley** [comment]
You didn't say which subscription plugin - if it's the one from WooCommerce.com, please use the helpdesk. If it's not, contact the developer who made it.

We already had 2 dp in core https://github.com/woocommerce/woocommerce/blob/master/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L407 so it may be specific to that plugin.

**Comment by vucumbra** [comment]
of course is woocommerce subscription....
https://woocommerce.com/products/woocommerce-subscriptions/

**Comment by mikejolley** [comment]
"of course is woocommerce subscription...."

Well unless you say so we don't know :) Please use the helpdesk then.
