### ISSUE TITLE
Fatal error on choosing payment default gateway

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#16347]
I am just a user who setup a new site with wc 3.1.1. I have set up as payment options Stripe and COD on my site. In case Stripe is active, I see under my account a payment setting tab. In there I am able to default to credit card by stripe but I saw also COD. As I checked that for default payment, I got this fatal error:

Fatal error: Uncaught Error: Call to undefined method WC_Gateway_COD::add_payment_method() in /www/htdocs/w00ffce5/atelier-an-der-muehle.de/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php:375 Stack trace: #0 /www/htdocs/w00ffce5/atelier-an-der-muehle.de/wp-includes/class-wp-hook.php(298): WC_Form_Handler::add_payment_method_action(Object(WP)) #1 /www/htdocs/w00ffce5/atelier-an-der-muehle.de/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #2 /www/htdocs/w00ffce5/atelier-an-der-muehle.de/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #3 /www/htdocs/w00ffce5/atelier-an-der-muehle.de/wp-includes/class-wp.php(746): do_action_ref_array('wp', Array) #4 /www/htdocs/w00ffce5/atelier-an-der-muehle.de/wp-includes/functions.php(955): WP->main('') #5 /www/htdocs/w00ffce5/atelier-an-der-muehle.de/wp-blog-header.php(16): wp() #6 /www/htdocs/w00ffce5/atelier-an-der-muehle.de/index.php(17): require('/www/htdocs/w00...') #7 {main} thrown in /www/htdocs/w00ffce5/atelier-an-der-muehle.de/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php on line 375

**Comment by mikejolley** [comment]
COD should not be listed; it does not support this. Something installed must be forcing this to show. I can fix core to prevent the error, but I cannot fix the reason or it being shown.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16361

**Comment by ajgw** [comment]
Hi Mike, you are right as it is related to a payment gatenway plugin. Thanks.

Mit Gruss aus Bremerhaven an der Nordsee,
Adrian Wackernah

Wackernah Bildmanufaktur
Lüneburger Str. 32
27572 Bremerhaven

Atelier An der Mühle
An der Mühle 45
27570 Bremerhaven

Tel. 0471-4836 5189
Tel. 0151-2404 3961

Web: https://bildmanufaktur-wackernah.de <https://bildmanufaktur-wackernah.de/>
