### ISSUE TITLE
How can I add category and isRelatedTo to class-wc-structured-data.php

### ISSUE THREAD

**Issue by herogo1** [woocommerce/woocommerce#16349]
Hello

I want to add category and isRelatedTo to class-wc-structured-data.php

http://schema.org/Product

Can anyone help me?

Thank you

**Comment by opportus** [comment]
Hi @herogo1, not sure to understand what you mean...
Structured data on product categories is already generated.
About 'isRelatedTo', I assume you mean SD for related products on single product, I don't think there is a point doing that...

**Comment by opportus** [comment]
@herogo, you can use `wc_structured_data_product` filter hook.
For futur, please, ask this kind of question on support forum instead.
