### ISSUE TITLE
All WooCommerce pages are blank because of third party script from fast.wistia.net

### ISSUE THREAD

**Issue by komarovartem** [woocommerce/woocommerce#16341]
Hello. Today the site fast.wistia.net was not responded for around 10 minutes. During all that time it was impossible to open any WooCommerce pages in admin area since fast.wistia.net/assets/external/E-v1.js was loading without ending. (at least in Safari) so all woo pages were blank.

I suppose it is not ok that whole admin area depends on the small third party script. 

Thanks.

**Comment by mikejolley** [comment]
Fix is here if it happens: https://github.com/woocommerce/woocommerce/pull/16288
