### ISSUE TITLE
Create a searchable select box of cities on the checkout page

### ISSUE THREAD

**Issue by jonathan-kosgei** [woocommerce/woocommerce#16355]
I'm using the following snippet to customize the Town/City field on checkout to be a drop down.

The thing is I have over 500 towns/cities for users to chose from and therefore need for this select box to be searchable in the same way the Country field is searchable.

Basically I need this:
![image](https://user-images.githubusercontent.com/6712914/29004559-cadac280-7ad1-11e7-99ba-8f5eb66c5edd.png)

For this:
![image](https://user-images.githubusercontent.com/6712914/29004561-d7f591a2-7ad1-11e7-8e42-bd91cee83f82.png)

**Comment by mikejolley** [comment]
You need to add select2 to the field. Either add the wc-enhanced-select class to the input, or call it manually with Javascript code. We don't support customisations here.
