### ISSUE TITLE
get_current_endpoint() - Endpoints Not Properly Detected

### ISSUE THREAD

**Issue by AlexandruDoda** [woocommerce/woocommerce#16353]
Hey,

When trying to use `get_current_endpoint()` to get the endpoint for the My Account pages, the following do not get properly detected:
`my-account/edit-addresses/billing`
`my-account/edit-addresses/shipping`

Instead, they both return the endpoint for `my-account/edit-addresses`

I am trying to leverage `get_current_endpoint()` to build a custom breadcrumb component and here's how it renders because of the bug:

<img width="1175" alt="screenshot 2017-08-06 13 44 02" src="https://user-images.githubusercontent.com/8274669/29002527-5571687e-7aad-11e7-9484-c986e56aeaae.png">

<img width="922" alt="screenshot 2017-08-06 13 44 23" src="https://user-images.githubusercontent.com/8274669/29002531-600c3b2e-7aad-11e7-9b29-62c93629e9cc.png">

See that the breadcrumb doesn't see the "Billing" as well and just stops at "Addresses". Same issue with the Subscriptions plugin when trying to view the Subscriptions (I know that's for a different plugin but just worth mentioning).

**Comment by mikejolley** [comment]
The endpoint is correct to be `my-account/edit-addresses`. `billing` and `shipping` are not endpoints, but they are values for `my-account/edit-addresses`.

Compare it to something like the `view-order` endpoint. For example `view-order/100`, the endpoint is `view-order`, not `100` as that's just a value.

The current value can be obtained from `$wp->query_vars` e.g. `$wp->query_vars['edit-address']`. This will contain either `billing` or `shipping` or nothing, if no address is being edited.

Hope that makes sense.

**Comment by AlexandruDoda** [comment]
Got it, thank you! :D
