### ISSUE TITLE
502 Backend Error

### ISSUE THREAD

**Issue by Basilakis** [woocommerce/woocommerce#16352]
Hello,

I get the following error:
id was called incorrectly. Order properties should not be accessed directly. Backtrace: do_action('wp_ajax_woocommerce_mark_order_status'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::mark_order_status, WC_Order->update_status, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_processing'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Emails::send_transactional_email, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Email_Customer_Processing_Order->trigger, WC_Email->get_content, WC_Email_Customer_Processing_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-processing-order.php'), do_action('woocommerce_email_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Emails->order_details, wc_get_template, include('/plugins/woocommerce/templates/emails/email-order-details.php'), do_action('woocommerce_email_before_order_table'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Shipment_Tracking_Actions->email_display, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0., referer: https://domain.com/wp-admin/edit.php?post_type=shop_order

Which is on the backend.
I have disabled plugins, I have changed theme but the error is still there on backend.
It is happening when I try to paginate at page to, when at orders on backend.

The issue is happening to different sites - and not just one with different themes and plugins ( same is happening not only at orders but at products also ). They are also different servers. One is siteground and the other one is wpengine

**Comment by mikejolley** [comment]
Old version of Shipment tracking. Debug output has:

```
WC_Shipment_Tracking_Actions->email_display
```

If shipment tracking was disabled, this notice would not be logged.

Note 502 is a timeout so it could be a combination of the above and other plugins causing pages to load slowly, depending on what is being done, what else is present, and how much data is being dealt with. This would need a deeper debug by a developer if fixing `WC_Shipment_Tracking` does not fully solve the issue.

Thanks
