### ISSUE TITLE
Product page shortcode does not work with 3.x gallery zoom, lightbox or slider

### ISSUE THREAD

**Issue by zmonteca** [woocommerce/woocommerce#16357]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Include a product anywhere on a site using the product_page shortcode
`<?php echo do_shortcode( '[product_page id="371"]', false ); ?>`
2. Ensure theme support is added for lightbox, zoom and / or slider
3. None of the above items are loaded or triggered.

## Expected/actual behavior

When I follow those steps, I see the correctly displaying product and elements.

I was expecting to see the correctly displaying product and elements with the product image either lightboxable or zoomable or sliding per the new gallery specs of WP 3.x

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Home URL: http://localhost
Site URL: http://localhost
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.6
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.12
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.2.0-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #367 - /shop/
Cart: #368 - /cart/
Checkout: #369 - /checkout/
My account: #370 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
Scripts can only be enqueued where WC/WP knows they are needed. So thats actual product pages, or where the shortcode is visible within post content.

If you're outputting manually via PHP, WC has no way to know the scripts will be needed. So you'd need to manually enqueue all required scripts.  This is not a bug.

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-frontend-scripts.php#L394-L407

**Comment by zmonteca** [comment]
@mikejolley Terrific explanation. Does make sense. Thank you.

I will say, it might be nice if this is documented somehow.

**Comment by theoplaticatoptal** [comment]
I just found a fix here: [https://ddgpress.com/fix-woocommerce-thumbnail-gallery-error/](https://ddgpress.com/fix-woocommerce-thumbnail-gallery-error/)

```
add_action( 'after_setup_theme', 'add_woo_single_product_gallery_support' );

function add_woo_single_product_gallery_support() {
    add_theme_support( 'wc-product-gallery-zoom' );
    add_theme_support( 'wc-product-gallery-lightbox' );
    add_theme_support( 'wc-product-gallery-slider' );
}
```
