### ISSUE TITLE
Product gallery

### ISSUE THREAD

**Issue by xttn** [woocommerce/woocommerce#16358]
Hi, I have a problem with product gallery
This product not have product gallery image:
http://i.imgur.com/WOhQPQ9.png
but in
```woocommerce/single-product/product-image.php```
i have
```$gallery_ids = $product->get_gallery_image_ids();```
`$gallery_ids` still have a value is
```php
array(
    [0] => 39
)
```
I checked, that `id=39` not the `id` of any product image, then i try reload page several times `$gallery_ids` return `array()` ?? I think it is bug. Can you check it?

Woocommerce: 3.1.1
// sorry my bad english

**Comment by mikejolley** [comment]
If the image was deleted from the media library, or you did an import, the ID 39 could simply be a remnant of that which corrected itself after read. Thats not an issue. The ID will do nothing if it does not exist.

It's correct to be empty. You have main image (get_image_id()) but not gallery items.
