### ISSUE TITLE
Shop page - Sort by Price in variable products in woocommerce 3.11

### ISSUE THREAD

**Issue by Broomspun** [woocommerce/woocommerce#16354]
issue: When selecting the sort by price in Shop page,  there is problem with all the variation products.
it is not shown variable products.
Woocommerce version is 3.11 and theme is Enfold.

Is there a way to sort the products low to high/high to low and use the variable products lowest price when sorting?
Url: http://enfold.storm-east.com/index.php/shop/?product_order=price

**Comment by mikejolley** [comment]
Theme has custom sorting code. `product_order` does not exist in WooCommerce core. Orderby does, and this does use lowest/highest price depending on direction.
