### ISSUE TITLE
Items removed from previous order and added to current order after 2.x to 3.1.1 update

### ISSUE THREAD

**Issue by sethpjohnson** [woocommerce/woocommerce#16370]
We're having a random issue with our install that is extremely hard to track down. We cannot replicate this staging and it happens randomly in production. These issues seemed to happen after we updated to 3.1.1 and only happen randomly. Orders were processed all weekend without issue and we've had 3-4 now in a row that went off the rails. 

I found this [posting and posted at the bottom last week](https://github.com/woocommerce/woocommerce/issues/16282) which seemed extremely similar to what we thought we were seeing. This morning we are able to determine that the products are actually being moved. 

We've worked with WPEngine to remove caching as much as possible. We've tested everything in staging and cannot replicate this -- it only seems to be happening on production where we cant disable all plugins or theme. 

Just looking for some clue on how to solve this. Or where to start looking.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Customer goes through check out
2. Item is removed from previous order and added to the new order
3. Check orders and cry

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

### WordPress Environment ###

Home URL: https://www.blackwiredesigns.com
Site URL: https://www.blackwiredesigns.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.18-0ubuntu0.16.04.1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (72) ###

Gravity Perks: by Gravity Wiz – 1.2.25
Gravity Forms: by rocketgenius – 2.2.3
Olark In WP: by Nose Graze – 1.0
Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.13
Admin Menu Editor: by Janis Elsts – 1.8
Awesome Support: Custom Fields: by The Awesome Support Team – 1.0.8
Awesome Support: Custom Status: by Awesome Support – 1.0.3
Awesome Support: E-Mail Support: by The Awesome Support Team – 5.0.2
Awesome Support: Gravity Forms: by Awesome Support – 1.0.5
Awesome Support: Notifications: by The Awesome Support Team – 0.3.0
Awesome Support: Private Notes: by The Awesome Support Team – 0.1.2
Awesome Support: Power-Pack (Productivity): by Awesome Support – 3.0.0
Awesome Support: WooCommerce: by Awesome Support Team – 1.4.1
Awesome Support: by Awesome Support Team – 4.0.5
Backbone for Black Wire Designs: by Feroz Jaffer – 3.0
WooCommerce Back In Stock Notifier: by Fantastic Plugins – 9.7
License Manager: by Blackwire – 1.1
JAD-2-Savant: by Seth Johnson – 0.1.0
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

Core Control: by Dion Hulse – 1.2.1
Delete Expired Transients: by WebAware – 2.0.6
Disable XML-RPC: by Philip Erb – 1.0.1
GP Auto List Field: by Gravity Wiz – 0.9.1
GP Preview Submission: by David Smith – 1.2.7
GP Unique ID: by David Smith – 1.3.7
Gravity Forms: Force SSL: by Timothy Wood (@codearachnid) – 1.4.1
Gravity Forms Debug Add-On: by rocketgenius – 1.0.beta7
Gravity Forms Logging Add-On: by rocketgenius – 1.3
Gravity Forms Polls Add-On: by Rocketgenius – 3.1.1
Gravity Forms Signature Add-On: by Rocketgenius – 3.3
Gravity Forms Trello Add-On: by rocketgenius – 1.2
Gravity Forms User Registration Add-On: by rocketgenius – 3.7
GP Copy Cat: by David Smith – 1.4.21
GP Limit Checkboxes: by David Smith – 1.2.1
GP Read Only: by David Smith – 1.3
GP Terms of Service: by David Smith – 1.3.7
If Menu: by Andrei Igna – 0.6
iThemes Security Pro: by iThemes – 4.1.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.2
Plugins Garbage Collector: by Vladimir Garagulya – 0.10.3
Postman SMTP: by Jason Hendriks – 1.7.2
PressApps Knowledge Base: by PressApps – 2.2.0
Recover Abandoned Cart: by Fantastic Plugins – 17.3
Sendy Widget Pro: by Aman Saini – 1.8.1
Simple 301 Redirects: by Scott Nellé – 1.07
Smart WP Login: by Nishant Kumar – 1.0.2
Username Changer: by Daniel J Griffiths – 3.1.0
Product Customer List for WooCommerce: by Kokomo – 2.5.1
WC Vendors Pro: by WC Vendors – 1.4.4
WC Vendors: by WC Vendors – 1.9.12
Webgility: by Webgility – v352
Woocommerce Advanced Bulk Edit: by George Iron – 4.2.2
WooCommerce Attach Me!: by Lagudi Domenico – 11.0
WooCommerce Extended Coupon Features PRO: by Soft79 – 2.5.3
WooCommerce Extended Coupon Features: by Soft79 – 2.5.1
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.5
WooCommerce Custom Fields: by RightPress – 2.2
WooCommerce Dashboard Widgets Stats: by Lagudi Domenico – 3.9
WooCommerce Email Customizer: by cxThemes – 3.12
WooCommerce USA ePay Gateway: by SkyVerge – 1.8.0
WooCommerce PDF Invoice: by RightPress – 3.1.6
WooCommerce Product Add-ons: by WooCommerce – 2.9.0
WooCommerce Quote: by RightPress – 1.0.4
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.1
WooCommerce Shipment Tracking: by WooCommerce – 1.6.8
WooCommerce FedEx Shipping: by WooCommerce – 3.4.9
WooCommerce UPS Shipping: by WooCommerce – 3.2.4
WooCommerce Store Credit: by WooCommerce – 2.1.8
WooCommerce Warranty Requests: by WooCommerce – 1.8.7
WooCommerce: by Automattic – 3.1.1
WooShip: by RightPress – 1.3.2
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /store/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.5
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.7
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome3/woocommerce/archive-product.php
flatsome3/woocommerce/cart/cart-empty.php
flatsome3/woocommerce/cart/cart.php
flatsome3/woocommerce/checkout/form-checkout.php
flatsome3/woocommerce/checkout/form-coupon.php
flatsome3/woocommerce/checkout/thankyou.php
flatsome3/woocommerce/content-product.php
flatsome3/woocommerce/content-product_cat.php
flatsome3/woocommerce/content-single-product.php
flatsome3/woocommerce/global/breadcrumb.php
flatsome3/woocommerce/global/quantity-input.php
flatsome3/woocommerce/global/wrapper-end.php
flatsome3/woocommerce/global/wrapper-start.php
flatsome3/woocommerce/loop/loop-end.php
flatsome3/woocommerce/loop/loop-start.php
flatsome3/woocommerce/loop/orderby.php
flatsome3/woocommerce/loop/pagination.php
flatsome3/woocommerce/loop/result-count.php
flatsome3/woocommerce/loop/sale-flash.php
flatsome3-child/woocommerce/myaccount/form-login.php
flatsome3/woocommerce/myaccount/navigation.php
flatsome3/woocommerce/notices/error.php
flatsome3/woocommerce/notices/notice.php
flatsome3/woocommerce/notices/success.php
flatsome3/woocommerce/product-searchform.php
flatsome3/woocommerce/single-product/photoswipe.php
flatsome3/woocommerce/single-product/price.php
flatsome3/woocommerce/single-product/product-image.php
flatsome3/woocommerce/single-product/product-thumbnails.php
flatsome3/woocommerce/single-product/related.php
flatsome3/woocommerce/single-product/review.php
flatsome3/woocommerce/single-product/sale-flash.php
flatsome3/woocommerce/single-product/share.php
flatsome3/woocommerce/single-product/short-description.php
flatsome3/woocommerce/single-product/tabs/tabs.php
flatsome3/woocommerce/single-product/title.php
flatsome3/woocommerce/single-product/up-sells.php
flatsome3/woocommerce/single-product-reviews.php
flatsome3/woocommerce/single-product.php

### WC Vendors Pro ###

Theme Compatability: -
Pro Dashboard Page: - #106681
Feedback form page: - #106682
Vendor Shop Permalink: - partners

### Templates ###

Overrides: –

</details>

**Comment by mikejolley** [comment]
See the logic here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L281-L295

If this is happening, it's likely that session data is not being cleared and the older order is still unpaid `pending` status:

```
$order_id           = absint( WC()->session->get( 'order_awaiting_payment' ) );
$cart_hash         = md5( json_encode( wc_clean( WC()->cart->get_cart_for_session() ) ) . WC()->cart->total );
```

After payment, the gateway should update the order to `processing` and clear the session variable `WC()->session->get( 'order_awaiting_payment' )`. Once this is done, next checkout creates a brand new order.

Given the number of plugins you're running it's impossible for me to pinpoint the issue itself, but I'd suggest you start by trying a different payment gateway to see if it's that, otherwise work through the "Isolating the problem" section above. Otherwise we cannot rule out a plugin conflict. I don't think this is the same as the other ticket you found, nor do I think this is caused by core itself.

Thanks

**Comment by sethpjohnson** [comment]
Thank you. What I figured anyway. The payment processor (and we've been through 2 of them) is unseating the session

```
				$order->payment_complete();
				WC()->cart->empty_cart();

				// Empty awaiting payment session
				unset( WC()->session->order_awaiting_payment );
```

So its off to dig through the other 900 plugins to find this error.

**Comment by mikejolley** [comment]
Also check the order is not pending status. If it is, the above code is not running.

**Comment by sethpjohnson** [comment]
That isn't happening as far as I can tell. What we have discovered is it does not happen during slow periods. Only when we have 2 orders go through around the same time frame (within a few minutes in our case). If orders are trickling in we do not experience this issue. 

If we were a busier site I'd say that it might be related to the duplicate/locking issues you are having on 3.0 but I don't think these transactions are happening on top of each other.

**Comment by mikejolley** [comment]
And WP Engine configured/disabled their varnish cache?

**Comment by sethpjohnson** [comment]
This was my first thought.. They claim to have done this. I'll get back on with their chat and figure out the details. I know cart and checkout were excluded.

**Comment by sethpjohnson** [comment]
I worked extensively with WPEngine and they did admit to finding something that wasn't configured correctly (not that they said what it was) however that has not helped our issue. A slow/steady day of orders yesterday there were no issues. Two orders made within a few minutes of each other this morning were both messed up. Both had product the customer did not order added to the order (at no cost). 

We've been slowly disabling plugins one at a time and waiting to see if it makes any difference.

**Comment by cdesewell** [comment]
Hi @sethpjohnson did you get to the bottom of your issue? I am experiencing a similar problem to yourself.

**Comment by BlackWireDesigns** [comment]
@cdesewell it was 100% a caching issue from WPEngine.  Make sure to have WPEngine not cache the following pages.

/cart/
/checkout/
/wc-api/
/product/
/product-category/
/my-account/
/store/    (this is the name we are using for the store in WC)

**Comment by cdesewell** [comment]
Thanks @BlackWireDesigns we are using AWS CloudFront so ill attempt to implement the equivalent and post back my results.
