### ISSUE TITLE
Invalid value posted for <variation> 

### ISSUE THREAD

**Issue by creativiousa** [woocommerce/woocommerce#16375]
Hi, I woild like to explain my error which happen for my woocommerce for GDORA product: https://gdora.my/product/test-1/ which appear to error "Invalid value posted for bead" I already upload the latest update of the theme and plugin. 

I have install the https://gist.github.com/mikejolley/3498250299c7cf7b24e973cbbce7a80c which cant fix the problem too. Can you verify what is happening for my website which occur to be error?

I can give u an access to my website.

**Comment by mikejolley** [comment]
The inspector shows that there are 2 fields named "attribute_pa_bead" being posted and the second has no value. It looks like it could be the select box customisation.

Inspector also shows a bunch of JS errors in the console so you should look at that also.

**Comment by creativiousa** [comment]
and another thing more there why I cant access the woocommerce setting? the error show "Action failed. Please refresh the page and retry."

**Comment by mikejolley** [comment]
Thats usually nonce related, but it could be added by any installed plugin

**Comment by creativiousa** [comment]
ok sir i will try take a look.. thanks for the answer ^_^

**Comment by creativiousa** [comment]
hyep after i change the SELECT> TEXT it works.. after i a while it become similar problem again..

**Comment by mikejolley** [comment]
Like I said there are 2 inputs on the page which is wrong. I think it's your select box customisation.
