### ISSUE TITLE
Carrinho não aparece

### ISSUE THREAD

**Issue by wfranca** [woocommerce/woocommerce#16387]
Pessoal,

o meu carrinho não está aparecendo...

![image](https://user-images.githubusercontent.com/30848541/29099486-15d0010a-7c7c-11e7-815d-cc563447f84d.png)

O que pode ser?

**Comment by claudiosanches** [comment]
Seria melhor publicar em inglês aqui, além de seguir o template de para os issues.
Mas no caso isso não esta funcionando porque falta o shortcode `[woocommerce_cart]` na página do carrinho, basta clicar em "Carrinho" nesse menu que você mostrou da foto e colocar o shortcode e salvar.
Note também que aqui não é um canal de suporte e questões assim como estas que não são bugs no WooCommerce devem ser publicadas em https://wordpress.org/support/plugin/woocommerce ou se quiser em português também existe o https://br.wordpress.org/support
