### ISSUE TITLE
all products not equal to published products total

### ISSUE THREAD

**Issue by maltonge** [woocommerce/woocommerce#16381]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
> Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action

FWIW this is most commonly the result of a bad import using an importing plugin e.g. bad post statuses or types.

**Comment by maltonge** [comment]
Steps to reproduce error.

install wordpress 4.8.1
install Woocommerce 3.1.1
uploaded 50k products via the woocommerce built in import tool.

wp-admin/ products  shows discrepancies in the amount of all products and the amount of published products.  its like a few hundred products disappeared but I really don't know where they disappeared to.  all products 50,000  published products 49,473  There is zero draft products,  the import was 50k products.

this is a fresh install of both wordpress and woocommerce using twenty seventeen theme.  no other themes or plugins installed.

I created this fresh install as a test because the same issue existed on the original site.  I thought it was to do with the woocommerce database update on the original install.  but this problem still exists even on the latest wp and woo installs.

zero errors are reported from this.  im not sure if this is a product reporting issue.

I can give access to the dev address which is used for testing only.

I have searched all over the internet for a few weeks now about this issue and even after a full fresh install this error still persists.

If you require dev address username and password please let me know. you are welcome to use for test purposes.

If just a reporting issue from woocommerce i don't mind to much but if not it means something is wrong with the database and that could lead to all sorts of implications in the future.

look forward to your reply

Thanks Malcolm

**Comment by mikejolley** [comment]
@maltonge Can you share the CSV file?

**Comment by maltonge** [comment]
yes csv is 180mb could not upload more than 10mb here so ive zipped it and put here https://dev.hobbygiant.co.uk/woocommerce-product-export (Autosaved).zip for your convience its zipped  down to 33mb hope this helps.  I have gone through every line took absolute age.

The amount of products are not exact as put above its 53k+ products but not all are recognised in the published products section.

**Comment by mikejolley** [comment]
Can you send a working link? Before I dive in, you should probably look at the WP_Posts database table and see if there are any unrecognised statuses there? e.g. placeholder

**Comment by maltonge** [comment]
@mikejolley sorry the link is correct above but some reason a space was put in between after commenting.
i made the link again here.
https://dev.hobbygiant.co.uk/woocommerce-import.zip  I have changed to file name and link to take away the space.  I will check again through the database again as i have not done that with the fresh install however i spent a few days searching the database on the original install and could not find the issue.  I will take a closer look at the new database now and will get back to you ASAP

**Comment by maltonge** [comment]
@mikejolly ok i just looked into the database and there are some place holders with importing status.  hmm.  I wonder if this is due to connection issue during import and because it does multiple product imports at the same time it only part finished some product imports and just left them open and unfinished.  I am going to test the full import again but i will split the csv file into 10k products each and see if this make a difference which i think it will.  I think there is maybe a few tweaks need doing to the import software to secure the database incase of connection issues.  This only my opinion on the matter.  Maybe you can shed some light from the issue.

**Comment by mikejolley** [comment]
@maltonge The final step should clear those out, so it may be that it didn't complete or as you say, some processes didn't finish. Did the final step list any failures?

**Comment by maltonge** [comment]
@mikejolley  Hi Mike i finally got the discrepancies sorted out.  I think the confusion with product IDs being replaced by woocommerce caused a great deal of confusion.  I was not aware that woocommerce was ignoring the ID column when importing,  and instead creating its own product ID.  I have tried a few times to get woocommerce to use our IDs but still it creates its own IDs.  now i am using sku code instead but this has just made the database increase in size when not required.  is there any way to get woocommerce to use the product ID i choose during import?  We did use product ids for updating, now updating creates duplicate posts.  its not ideal really but for now it looks like each product needs 2 identifiers which with table scans, page load is increased without need.  is there any reason why woocommerce is ignoring the ID column on import?

**Comment by mikejolley** [comment]
Yeah there are reasons. Products are a custom post type, so they share the same DB table as posts, pages, orders, etc. If we allowed IDs to be defined, it would most likely cause conflicts and overwrites of existing data. Something that should be avoided.
