### ISSUE TITLE
Webhooks response line_items meta_data

### ISSUE THREAD

**Issue by slier81** [woocommerce/woocommerce#16388]
Excerpt response from webhooks Order created :

<pre><code>
Array
(
    [id] => 34
    [parent_id] => 0
    [number] => 34
    ...

    [payment_method] => cod
    [payment_method_title] => Cash on delivery
     ...
    [meta_data] => Array
        (
            [0] => Array
                (
                    [id] => 1165
                    [key] => _download_permissions_granted
                    [value] => yes
                )
               ...
        )

    [line_items] => Array
        (
            [0] => Array
                (
                    [id] => 38
                    [name] => WT2401 Trendy Top Red
                    [product_id] => 17
                    ...
                    [taxes] => Array
                        (
                        )

                  <b> [meta_data] => Array
                        (
                        ) </b>

                    [sku] => 
                    [price] => 23.32
                )

        )

     ...

)

</code></pre>

Is there is a way to get order items meta data `line_items[meta_data]` from the Order created webhooks?
I have set custom meta data on a product i created.
So i plan to get this meta data back when an order were made consisting this items.
Is this even possible?

**Comment by claudiosanches** [comment]
It's possible, but for sure you are getting it before save any metadata to the `line_items`.
This issue is missing a lot of information, like steps to reproduce and so on, better not ignore the issue template, since that template can help us debug it... However looks like you should look for `order.updated` webhook that should have the information you need.

**Comment by slier81** [comment]
@claudiosanches 
sorry about ignoring the templates..
I thought this is not bug related, that is why im completely ignoring the template
Btw, as u suggested, im using order.updated hooks, still i didnt get product meta data `line_items[meta_data]`

Should i open new issue?

**Comment by claudiosanches** [comment]
The template is important for any issue, there we have steps to reproduce and all kind of informations to make we able to reproduce the issue.
