### ISSUE TITLE
Coupon Codes not working properly but sometimes....

### ISSUE THREAD

**Issue by Swftkik** [woocommerce/woocommerce#16394]
Let me break down what is going on.

I have several coupon codes for woocommerce. For this issue we will be using two to recreate it. "Save10" is a coupon we use for our customers to save 10% on their first online order. That code works perfectly. Set up as a fixed cart discount with one time use. Our next coupon code is "ONUS" where customers receive a specific item for free. Due to being unable to apply the code and then the product gets added to the cart. We have set it up for the customer to add the product to the cart and then the code will take the exact pricing ($5) off of the cart total. So the code is set at fixed product discount in order to take the exact price off of the product we are offering for free. The issue we have is when customers are allowed to stack both of those coupons. Normally this is not a problem. The reason I find this an issue is that when a customer applies "ONUS" first then "Save10", the cart reflects those discounts correctly. (taking the free item price off, and then 10% off the rest of the cart.) When the coupons are reversed it takes 10% off the cart total, when the second code is used it matches the 10% discount instead of the fixed price we set it at. The order we tested this on was a $45 or with two items. (item 1 is a normal item $40 and item 2 is the free item $5). 

Test 1: "ONUS" then "Save10" Item 2 becomes free and 10% off item 1. new total 36
Test 2: "Save10" then "ONUS" First coupon takes $4.50 off of a $45 order then the second code takes $4.50 off of item 2. Which is incorrect since the $5 item is supposed to be free. 

Test 3: Used "Save10" then "ONUS" on a $50 order. Coupon codes worked perfectly.
Test 4: "Save10" then "ONUS" on a $55 order. Coupon codes worked perfectly.

That leaves it to believe that there is a bug in the coding somewhere. Ideas?

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16400
