### ISSUE TITLE
[3.1.1] wc_get_order() is returning false for an existing shop_order

### ISSUE THREAD

**Issue by renatonagliati** [woocommerce/woocommerce#16395]
Hi,

I'm having a very similar issue of #15616 (but I can't reopen it). Could you check the following details, please?

Thanks,
Renato

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Explanation ##
Basically I'm getting all "processing orders created after 2017-07-01" and passing through a loop. I'm having two issues on this process:

1. The WC_Order_Query returns the orders only if the parm 'return' is defined - without this parm, I'm getting an empty array;

```
$query = new WC_Order_Query( array(
	'limit' => -1,
	'type' => 'shop_order',
	'status' => 'processing',
	'date_created' => '>2017-07-01',
	'return' => 'ids', //if I comment this line, the result will be empty
) );
$processing_orders = $query->get_orders();
```

2. With the $processing_orders [on my DB I have only 1 order; with ID 213], the wc_get_order is returning false:

```
if(!empty($processing_orders)){

	foreach($processing_orders as $order_id){
		$order = wc_get_order( $order_id );
		var_dump( $order ); //is returning bool(false)
	}
	
}
```
## Print Screen ##
Query: SELECT * FROM `wp_posts` WHERE post_type = 'shop_order'
Result: 
![image](https://user-images.githubusercontent.com/7807925/27932408-0c75d714-6274-11e7-96af-53160045443b.png)

WooCommerce > Orders
![image](https://user-images.githubusercontent.com/7807925/27932459-38467b14-6274-11e7-96b9-d2d464bcbcc0.png)

PS.: I'm running this code on a plugin through the plugins_loaded action.

## Expected/actual behavior

When I follow those steps, I see bool(false).

I was expecting to see the order passed as parm.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://wordpressexpress.com.br/nosebbo
Site URL: http://wordpressexpress.com.br/nosebbo
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - Nós recomendamos utilizar pelo menos a versão 5.6 do MySQL. Mais informações: Requerimentos do WordPress
Max Upload Size: 64 MB
Default Timezone is UTC: ❌ O fuso horário padrão é America/Sao_Paulo - deve ser UTC
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Sua loja não está usando HTTPS. Saiba mais sobre HTTPS e certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (14) ###

Fix Image Orientation: por Tim Carr – 1.0.0
CMB2: por CMB2 team – 2.2.5.2
noSebbo: por WC Marketplace
The Grey Parrots – 2.7.5

Tradução (Loco): por Tim Whitlock – 2.0.15
Ninja Forms: por The WP Ninjas – 3.1.9
Postman SMTP: por Jason Hendriks – 1.7.2
Slider Revolution: por ThemePunch – 5.4.3.1
Super Socializer: por Team Heateor – 7.9.4
WC Password Strength Settings: por Daniel Santoro – 1.1.0
Woo - Autocomplete Orders after x days: por Renato Nagliati – 0.1
WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.6.0
WooCommerce: por Automattic – 3.1.1
WooDiscuz - WooCommerce Comments: por gVectors Team (A. Chakhoyan
G. Zakaryan
H. Martirosyan) – 2.0.12

WCMp Consider taxes on commission calculation: por Renato Nagliati – 1.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BRL (R$)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base da loja: #4 - /loja/
Carrinho: #5 - /carrinho/
Finalizar compra: #6 - /finalizar-compra/
Minha conta: #7 - /minha-conta/

### Theme ###

Name: WordPressExpress noSebbo
Version: 1.0
Author URL: http://wordpressexpress.com.br/
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema pai. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: wpexp_tema_nosebbo/woocommerce/archive-product.php
wpexp_tema_nosebbo/woocommerce/content-product.php
wpexp_tema_nosebbo/woocommerce/loop/loop-start.php
wpexp_tema_nosebbo/woocommerce/single-product.php

`
</details>

**Comment by mikejolley** [comment]
`plugins_loaded ` is too early.

From the source/notice:

> wc_get_order should not be called before post types are registered (woocommerce_after_register_post_type action)'

basically, after `init`

**Comment by renatonagliati** [comment]
Many thanks for the reply, Mike. Sorry for the hesitation...

**Comment by EnricoSignori** [comment]
I'm having the same problem, however I'm calling the method in the theme function with an existing order id and only get the false return.

**Comment by rafaelbuiu** [comment]
@EnricoSignori run your function inside the init action.. it will work..
```
add_action('init', 'runOnInit', 10, 0);
function runOnInit() { 
    your code 
}
```

**Comment by Kaji01** [comment]
I'm getting the same error when I try running it in a function that's part of a custom action I have hooked onto `wp_footer`.  I've even verified with `did_action('init');` to be certain, so it's not a matter of hooking it too early.  And the order number being submitted is an exact match for existing order IDs in the back end.
