### ISSUE TITLE
.woocommerce-product-gallery__wrapper needs margin:0 ?

### ISSUE THREAD

**Issue by git-e-up** [woocommerce/woocommerce#16396]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. The images in the product gallery seem to float right of the container in my theme with the zoom, lightbox, and slider features enabled. This also served to cut off the right side of the product image. Both Firefox and Chrome add margins to the `<figure class="woocommerce-product-gallery__wrapper">` element, but it took me a little while to isolate the problem. I'm not a css master, but just thought this may help others. 
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
@git-e-up Can you send an example link? It would affect all themes if it were a default browser style?

**Comment by git-e-up** [comment]
Unfortunately, I cannot until the site I'm working on launches. Should be in the next couple weeks. This is my first experience with the new gallery so I don't know what the effect would be on other themes. Apologies for the vagueness, but I just wanted to put it on the radar and I didn't know where else to submit the suggestion.

**Comment by mikejolley** [comment]
Hmm well whilst I don't see margin, the browser stylesheet does have `-webkit-margin` props. Let's zero those out.
