### ISSUE TITLE
Individual add to carts on grouped products

### ISSUE THREAD

**Issue by fragglefusion** [woocommerce/woocommerce#16393]
Since updating to woocommerce 3.x, my store does not have individual add to cart buttons on each product within a grouped products. How can I fix this?

**Comment by mikejolley** [comment]
Are you going to provide a link and the details requested on the new issue form?

> Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action

**Comment by fragglefusion** [comment]
https://thedocumentrecordsstore.com/product/docd-5002/

It has a checkbox for each rather than a add to cart button for each product like it used too.

**Comment by mikejolley** [comment]
What you're seeing is how core should be outputting them - it allows you to add many to the cart in one go. Thats why we have grouped products. If you want buttons, you need to customise the template files to do so.
