### ISSUE TITLE
Woocommerce shop page issues

### ISSUE THREAD

**Issue by deveshpal** [woocommerce/woocommerce#16399]
Not able to see any added/modified/removed products or items from shop/ page. I have tried re-activating the plugins. Cleared the theme cache. Permalinks saved. But still not showing up.

Please help as this is really urgent. Any help will be appreciated. Many thanks in advance.

**Comment by mikejolley** [comment]
>  Hi there! This form is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. If you need technical support from a human being, please submit a ticket via the helpdesk instead: https://woocommerce.com/contact-us/

> Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action.
