### ISSUE TITLE
I Don't Find any item/Product  in Database Created By Woocommerce Plugin in my web Application

### ISSUE THREAD

**Issue by deepandharia** [woocommerce/woocommerce#16404]
Hello,I have Created An E-Commerce Site by woocommerce plugin in wordpress. Now I have created Many Product as an item for selling .I Don't Find any of Item/Product as an entry  that  i added in database created by the woocommerce at the time of installation.Pleas help me to find list of Items/Product  or name of table in database created by woocommerce plugin.

**Comment by mikejolley** [comment]
Products are a custom post type. wp_posts. https://github.com/woocommerce/woocommerce/wiki/Database-Description

**Comment by deepandharia** [comment]
i really satisfied from your answer,Thank u.
