### ISSUE TITLE
Variations info show in cart and checkout even we have it in item title, because we have "-" in variation name

### ISSUE THREAD

**Issue by roonex** [woocommerce/woocommerce#16402]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add custom attribute to product with "-" in values for it for example Medium | Large | X-Large | 3X-Large
2. Add variations with values for this attribute
3. Add one product with Large variation and one with 3X-Large variation

## Expected/actual behavior

I was expecting to see in cart only product name without additional info for variation, because Variation values are shown only if they are not found in the title as of 3.0.

It shows additional info only for product with 3X-Large variation, because we have "-" in variation name: http://prntscr.com/g6yaoo

This happens because function get_item_data in WC_Cart class.
On line 562 we have this check: if ( '' === $value || stristr( $cart_item['data']->get_name(), $value ) )
When variation have "-" in name $value is "3X-Large" but $cart_item['data']->get_name() return "3X Large" and they are different so it shows additional variation info even we have variation name in title.

So instead equal behavior for all variable products in the cart, we receive different behavior because the "-" in the variation name

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
`
### WordPress Environment ###

Home URL: http://codeable.roonex.com
Site URL: http://codeable.roonex.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.0
PHP Post Max Size: 30 MB
PHP Time Limit: 180
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.52 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wpfb_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (7) ###

Advanced Custom Fields: Repeater Field: by Elliot Condon – 1.1.1
Advanced Custom Fields: by Elliot Condon – 4.4.11
Contact Form 7: by Takayuki Miyoshi – 4.8.1
Displet RETS/IDX: by Displet – 2.2.4
PHP Compatibility Checker: by WP Engine – 1.4.3
WooCommerce: by Automattic – 3.1.1
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: codeable (codeable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
rated-5 (rated-5-2)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Fifteen
Version: 1.8
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by claudiosanches** [comment]
This should be fixed by https://github.com/woocommerce/woocommerce/pull/16091

**Comment by claudiosanches** [comment]
Just tested and looks like it's fixed now.
Thanks for reporting it.
