### ISSUE TITLE
Importing variable product and then exporting again fails to export variations

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#16409]
When Importing a variable product (which was previously exported). The product imports without any errors and the product works as intended.

However when exporting this product again using a filter for specific product types it doesn't include all the variations. I'm exporting both the variable products and variations. If I export all the products then it does include the variations.

I checked the database to see why the variations weren't being included. It seems the following query is used for returning all the results:

```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts 
LEFT JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id)
WHERE 1=1 AND ( ( wp_term_relationships.term_taxonomy_id IN (4) 
OR NOT EXISTS ( 
	SELECT 1 
	FROM wp_term_relationships 
	INNER JOIN wp_term_taxonomy ON wp_term_taxonomy.term_taxonomy_id = wp_term_relationships.term_taxonomy_id 
	WHERE wp_term_taxonomy.taxonomy = 'product_type' 
	AND wp_term_relationships.object_id = wp_posts.ID
) ) )
AND wp_posts.post_type IN ('product_variation', 'product')
AND ((wp_posts.post_status = 'publish' OR wp_posts.post_status = 'private'))
GROUP BY wp_posts.ID
ORDER BY wp_posts.ID ASC
LIMIT 0, 50
```

This will get all product_variation, product posts which either have the term product_type = variable or do not have any product_type set (which should be the case for a variation).

However after the import of the variable product each of the variations is assigned the product_type = simple. Which prevents them from being included in this query. If I manually remove the term relationship then they are included in the export again.

Tested originally with version 3.1.1. Also tested with the latest master, same results.

Attached the file I was using containing the variable product:
[Export.zip](https://github.com/woocommerce/woocommerce/files/1217598/Export.zip)

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/16410 The data store needs to remove the type. Placeholders are created during import which are 'simple'.
