### ISSUE TITLE
No access right for Webhook api 

### ISSUE THREAD

**Issue by KingWu** [woocommerce/woocommerce#16406]
Hi, i just enhance the wordpress security. Upgrade to https. After that, i found the Rest api for webhook not working.

I used a admin role to generate a key with Read/Write permission. Also, i created a hardcode webhook manually. 

Then, i use the Webhook V3 api to get the webhook detail with a specific webhook post id.

But it throw the following error.
`{
    "errors": [
        {
            "code": "woocommerce_api_user_cannot_read_webhook",
            "message": "You do not have permission to read this webhook"
        }
    ]
}`

Any specific role access right for webhook api?

WordPress Environment
--
WC Version: |   | 2.5.5
Log Directory Writable: |   | ✔ /home2/dokicom/public_html/wp-content/uploads/wc-logs/
WP Version: |   | 4.5.2
WP Multisite: |   | –
WP Memory Limit: |   | 512 MB
WP Debug Mode: |   | –
Language: |   | en_US

**Comment by mikejolley** [comment]
Without seeing the actual requests made it's hard to say. I'd guess it's to do with the auth method you're using. 

https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API
https://woocommerce.github.io/woocommerce-rest-api-docs/v3.html#authentication

I did a test to make sure v3 api still works:

<img width="1070" alt="2017-08-11 at 12 48" src="https://user-images.githubusercontent.com/90977/29211872-7d317e28-7e93-11e7-9dcb-d38895713686.png">

So it appears to be fine. I am using a more recent version however. 2.5.5 is not current.

Thanks

**Comment by KingWu** [comment]
I use api  `/wc-api/v3/webhooks/count`. Return the count is 1.

But, use an api `/wc-api/v3/webhooks`. Return a empty list.

is the upgrade process from http to https causing the issu?

**Comment by KingWu** [comment]
Thanks @mikejolley. Finally, i found that Avada theme unregister the post type - webhook. So, it case the above issue.

**Comment by mikejolley** [comment]
![1u27o3](https://user-images.githubusercontent.com/90977/29268125-6e6d513a-80e3-11e7-9935-89874e5317fe.jpg)
