### ISSUE TITLE
Payment Methods Page (My account) and Stripe

### ISSUE THREAD

**Issue by ateliersimon** [woocommerce/woocommerce#16417]
Hi,

I want to find a solution to fix the following problem : I'm testing Stripe payment gateway with Woocommerce, and I decided to disable the "Save Cards" option. I excepted no more possibilities to register a credit card in "payment method" page in "my account". But I discover it was still possible to add a default payment method for Stripe. When I click and "add a payment method", I can add a payment method for "Stripe". When I click on the button, the Stripe checkout window opens with "add a credit card", but the message is not display properly. (Picture)

![image](https://user-images.githubusercontent.com/12834916/29223139-c4f8dfbc-7ec5-11e7-852c-5482698d3c45.png)

It's something I don't understand and don't approve (for professionnal reasons). If I disable "Save Credit Card" option, I expect no payment registration in user's account. Then, it's not really clear for me if the credit card is going to be "tokenised" or store inside my database. For professionnal reasons, I think it will be better for store owner to disable the possibility to register a credit card. Especially in case an hacker break into the website, and use credit cards to buy products. 

I will be happy if I can find a solution to not store credit card informations inside my website. Let me know if I just need to switch to another payment method like PayPal to avoid this problem. 

Best regards,

SC

## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Disable "Save Card" and enable "Stripe Checkout", in Stripe configuration
2. Go to "my account", then "payment method"
3. Add a payment method to Stripe, then Strip checkout window opens

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
Stripe issues should be logged here https://github.com/woocommerce/woocommerce-gateway-stripe/issues but I will say that any 'save card' action performed in the stripe extension uses tokenisation, the option itself only applies to the checkout (checkbox), and some extensions that rely on tokenisation (such as subscriptions) force it on because without it they could not function.

Thanks!

**Comment by ateliersimon** [comment]
Hi,

Thank you for reply ! I find a solution here : https://stackoverflow.com/questions/39287308/woocommerce-remove-downloads-from-menu-in-my-account-page

If you want to remove some pages in "my account", you just need to remove the endpoints in Woocommerce settings.
