### ISSUE TITLE
How can i find my Item/product Details like price Desc etc

### ISSUE THREAD

**Issue by deepandharia** [woocommerce/woocommerce#16414]
How can i find  my product Details like Price, Description in database Created by Woocommerce.

**Comment by ateliersimon** [comment]
Documentation here : https://github.com/woocommerce/woocommerce/wiki/Database-Description

**Comment by deepandharia** [comment]
ya but i didn't find in that

**Comment by mikejolley** [comment]
It’s post meta. You need to understand how custom post types work in WordPress to know where to find certain data. You can also look at the ‘data-store’ classes in WooCommerce to know where meta goes. Descriptions are all in the wp_posts table.

Please note, Github is not a support forum, and the issues you are logging are not bugs.

**Comment by deepandharia** [comment]
OK thanks,  for giving me this info.Can you give me further tips to debug How Wordpress  Actually  work.

**Comment by mikejolley** [comment]
Not really. Use wordpress.org forums or stackoverlow if you want general WP advice.
