### ISSUE TITLE
Shipping "is available" Filters break with > 1 Method Instance

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#16420]
This may be easier to show than explain, sorry :)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional) **(Sort of)**

## Expected/actual behavior

When filtering shipping method availability, if you have more than one instance of a shipping method in a zone, it now becomes impossible to filter availability accurately. This is because the filters for that zone operate on a **method ID** basis, rather than an **instance ID** basis. So, if you try to filter availability for one free shipping method, you are by nature always filtering availability for all free shipping instances in that zone, not allowing you granular control.

This is because the filter used to adjust availability is:
`"woocommerce_shipping_{$method->id}_is_available"` 

If there's more than one method with that ID (possible, for example, if you have 2 free shipping methods in a zone or 2 flat rates), [this filter](https://github.com/woocommerce/woocommerce/blob/4ea14a35e26365b90a75dcfd9201b64f72b92e5e/includes/abstracts/abstract-wc-shipping-method.php#L361) does not provide you with the _instance_ you're looking at.

This forces you to loop through all available methods for the package if you want to check anything related to that method, such as its settings. Because of this, you're never modifying availability _for a specific instance only_ of that shipping method; instead, you're always globally modifying availability for all instances of that method.

Passing the instance of the shipping method to all occurrences of the availability filter would allow actors to (1) more directly check the settings of that method for its availability, and (2) resolves this issue by ensuring you're only modifying availability for a particular instance of that method.

When the instance as passed as an additional param for that filter, you can simplify your 3pd code to something like this:

```
function modify_free_shipping_availability( $available, $package, $method ) {

	if ( $method instanceof WC_Shipping_Free_Shipping && 'yes' === $method->enabled && 'account' === $method->requires ) {
		$available = (bool) get_current_user_id();
	}

	return $available;
}
```

and it will now work flawlessly.

## Steps to reproduce the issue

 1. [Install / activate this plugin](https://gist.github.com/bekarice/70674f1d5980f7de15396792e7800b63)

 2. Set up 2 free shipping rates in a zone -- the first using a min amount of $50, the next using the new "requires" option to limit it to signed in users: [See screenshot](https://user-images.githubusercontent.com/4983547/29230380-cd9e72cc-7eb0-11e7-9185-f3f4fac3bc3f.png)

 3. Visit checkout as a guest with > $50 in your cart. Notice you're not offered the free shipping based on amount. [See screenshot](https://user-images.githubusercontent.com/4983547/29230418-f633c6ec-7eb0-11e7-88c6-fed9cc077517.png)
   This is because we're trying to filter the free shipping for the _next_ instance, and it will return false. This `false` for the availability will therefore extend to **all** free shipping instances.

 4. Now log in. Observe that if your cart _does not_ meet the amount criteria for the min order amt free shipping, you still see it anyway. This is because the second instance is attempting to filter free shipping to "true" so it applies to both. [See screenshot](https://user-images.githubusercontent.com/4983547/29230472-32809b34-7eb1-11e7-948b-fb88dc1ea1e7.png)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active   
  (**can't really do this, by nature it's when filtering**)
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

WC 3.1.1 + custom plugin

**Comment by mikejolley** [comment]
Code will need to ensure the $method/$this is passed since some extensions may be using this filter without passing it. Just an FYI.
