### ISSUE TITLE
Logging every manual order change in comments not just status change

### ISSUE THREAD

**Issue by tonybahama** [woocommerce/woocommerce#16426]
**Problem**: We have several shop managers that manually adjust orders. Changing attributes from size M to L, changing shipping address, adding discounts. It is only 10% of the orders maybe. These things never get logged so if someone makes a mistake we will never no who is responsible.

**Solution**: Logging not only status changes but every change as well. Like:
"Product 15 Size changed from L to M" - 15:12, July 30, 2017 - Adrian
"Shipping address changed from "10001 New York .... etc to 111111 Washington" - 15:12, July 30, 2017 - Adrian

Any thoughts?

**Comment by mikejolley** [comment]
What you’re after is an audit log solution. We’re not planning on doing this in core, but there are I think some existing audit log plugins out there, and some others coming soon I know of. Feel free to log this on ideas.woothemes.com to further validate the idea so it gets more priority. Thanks.
