### ISSUE TITLE
Conflict between Printful and Woocommerce Version 3.1.1

### ISSUE THREAD

**Issue by miketrikebike** [woocommerce/woocommerce#16424]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.Using Printful (printful.com) plugin version 1.2.8 (latest) with Woocommerce 3.1.1
2.Deactivated all plugins except Printful and Woocommerce and still had errors adding items to my store.
3.After uninstalling Woo 3.1.1 and reinstalling Woo 3.04 with it's database I was able to add products to my store again.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://gunshirts.com
Site URL: https://gunshirts.com
WC Version: 3.0.4
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: ❌ 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.4
WC Database Prefix: wp_an1jx123n6_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Advanced Ads: by Thomas Maier – 1.8.3
All In One SEO Pack Pro: by Michael Torbert – 2.4.15.3
Better Internal Link Search: by Cedaro – 1.3.0
Black Studio TinyMCE Widget: by Black Studio – 2.4.2
Contact Form 7: by Takayuki Miyoshi – 4.8.1
Duplicate Post: by Enrico Battocchi – 3.2
Jetpack by WordPress.com: by Automattic – 5.2.1
MailChimp for WordPress: by ibericode – 4.1.6
Media File Renamer: by Jordy Meow – 3.6.0
Pootle Pagebuilder (Premium): by Pootlepress – 4.1.1
Post Type Switcher: by John James Jacoby – 3.0.0
Printful Integration for WooCommerce: by Printful – 1.2.8
Projects: by WooThemes – 1.5.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Storefront Pro (Premium): by pootlepress – 4.4.0
TablePress Extension: Change Table Shortcode: by Tobias Bäthge – 1.0
TablePress Debug Extension: by Tobias Bäthge – 1.0
TablePress: by Tobias Bäthge – 1.8
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.5

WooCommerce - Store Exporter: by Visser Labs – 1.9.1.1
WooCommerce Stripe Gateway: by WooCommerce – 3.2.2
WooCommerce: by Automattic – 3.0.4 – 3.1.1 is available
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Wordfence Security: by Wordfence – 6.3.16

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by michaeltieso** [comment]
Hey. I imagine this might be a compatibility issue. Have you tried reaching out to Printful as well? [I'm not seeing any recent reports of issues on their forum](https://wordpress.org/support/plugin/printful-shipping-for-woocommerce).

**Comment by mikejolley** [comment]
Please report this to Printful because it's 3rd party and I cannot be tested by myself without an account/API key. Simply installing the printful extension made no difference to product creation for me.

There are no database changes in 3.1 FWIW, but if you had an error log (php error log) I could at least tell you what seems to be causing it and what would need fixing.

https://calderaforms.com/2016/05/wordpress-debug-logging/ for example.

Let me know if you can provide this, or if Printful were able to solve it.

Thanks

**Comment by miketrikebike** [comment]
Mike,
Sorry I am just getting to this.  I have my site hosted with Godaddy and they said that they didn’t have any error logs and weren’t able to get them for me.
Printful told me to get the logs from Godaddy… so there I am.  I had a backup copy to an earlier version of Woocommerce and used the older database as well and everything worked.
I’m not a programmer. 
Anyway, let me know if there is any other info I can get for you.
I did see that the issue was closed.
Mike

**Comment by miketrikebike** [comment]
Michael,
I did try reaching out to Printful.  They wanted my error log, but I wasn’t sure how to go about that. I called my host (go daddy) and they told me they couldn’t get them for me and that’s just the way “managed wordpress” was…..no access to error logs.  Printful wanted error logs so I wasn’t much help to them and godaddy wasn’t much help to me.
I reverted to an older version of woo and an older version of the database and now it’s working.
Mike

**Comment by mikejolley** [comment]
Do they allow access to the files in wp-content? And wp-config.php? if so you could enable WP_DEBUG. I'm not sure how it works on Godaddy.

**Comment by miketrikebike** [comment]
Yes, I have ftp’d into that area and can access wp-config.
I am not a programmer, but the info you sent  me (web link) looks like that will help.
Enabling WP_DEBUG will tell me what the issue is for sure?

**Comment by mikejolley** [comment]
Unsure unless you try it.

**Comment by miketrikebike** [comment]
Hi Mike,
I was able to create a debug.log file.
I’ve attached it here along with a screenshot of the error I’m getting when trying to add a product to one of my stores. 
I am using the Printful site to do this.
I am using the latest version of Woocommerce plugin as well.  When using an older version 3.0.4 I had no problem adding
items to my store, after upgrading to version 3.1.2 I wasn’t able to add product any longer.
All of my Plugins are updated and I am using the latest Printful plugin ( vs.1.2.8 ).
Hope this helps.
Mike

**Comment by mikejolley** [comment]
@miketrikebike Come upload it on github. No attachment shows up.

**Comment by miketrikebike** [comment]
Ok. .. Will do it later this afternoon

**Comment by miketrikebike** [comment]
Mike,
Hope this helps.
![screen shot 2017-08-30 at 7 06 31 pm](https://user-images.githubusercontent.com/22209714/29950813-1906823c-8e73-11e7-82b4-e270491f1c1f.png)
[debug.log.zip](https://github.com/woocommerce/woocommerce/files/1268847/debug.log.zip)

**Comment by mikejolley** [comment]
It's coming from a caching plugin

https://wordpress.org/plugins/apc/

If thats no longer installed and this isn't a feature from your host, remove object-cache.php from wp-content directory.

**Comment by miketrikebike** [comment]
I appreciate the help Mike.

**Comment by Ground29** [comment]
Hi, I have been searching everywhere for issues with printful and woo. How did you fix this issue?

Thanks

**Comment by thankful999** [comment]
FOUND A FIX FOR THIS ERROR WHEN NOT ABLE TO PUSH PRINTFUL PRODUCTS TO WOOCOMMERCE STORE OR IF IT STOPS WORKING INTERMITANTLY 

500 Internal Server Error occurred! Please check your server logs for a detailed issue description.

1.	Hostgator increased my memory limit to 512 (Hostgator figured that would be overkill for my VPS server (not shared server), that didn’t work.   
2.	Hostgator changed the execution time from 30 seconds to 5 minutes (Hostgator figured that would be over estimating as well, but wanted to give enough time)
3.	Hostgator left memory time to 512 because I have VPS hosting (not shared hosting).  (This was a just-in-case decision).
