### ISSUE TITLE
Single Product: Trigger resize after main image loads results in jQuery.Deferred exception

### ISSUE THREAD

**Issue by thorge** [woocommerce/woocommerce#16429]
Hello,

I'm using Woocommerce with the Woocommerce gallery functionality and an own custom theme based on MaterializeCSS.
When viewing single items it results in a jQuery exception and the product images seem to have issues with the magnifier/reading glass icon. It is no real issue, because it only appears in combination with third-party plugin materializecss and of course you don't need to support, but maybe you can help me on finding an answer. Actual stable and dev versions are affected, I didn't recognize any problems with early v3 versions.

I could break it down to this code section in _assets/js/frontend/single-product.js_:

            // Trigger resize after main image loads to ensure correct gallery size.
		$( '.woocommerce-product-gallery__wrapper .woocommerce-product-gallery__image:eq(0) .wp-post-image' ).one( 'load', function() {
			var $image = $( this );

			if ( $image ) {
				setTimeout( function() {
					var setHeight = $image.closest( '.woocommerce-product-gallery__image' ).height();
					var $viewport = $image.closest( '.flex-viewport' );

					if ( setHeight && $viewport ) {
						$viewport.height( setHeight );
					}
				}, 100 );
			}
		} ).each( function() {
			if ( this.complete ) {
				$( this ).load();
			}
		} );

This code should get called when viewing single-products. A default WC installation works fine in the first moment, but when I reexecute this code with developer console it results in a jQuery.Deferred exception.  I can't find the overloaded functionality of $( this ).load(). It seems to me that at runtime there is no more functionality.

I experience the same problem when I have my custom theme enabled, but I get this error even when loading the page and not only when I rexecute the code.

Can you tell me why the default version is working and load() is overloaded?

The exception I get:
`jQuery.Deferred exception: a is undefined r.fn.load@https://mydomain.com/wp-content/themes/mydomain/assets/js/jquery-3.2.1.min.js:4:18890
ProductGallery.prototype.initFlexslider/<@https://mydomain.com/wp-content/plugins/woocommerce/assets/js/frontend/single-product.min.js?ver=3.2.0:164:5
each@https://mydomain.com/wp-content/themes/mydomain/assets/js/jquery-3.2.1.min.js:2:2713
each@https://mydomain.com/wp-content/themes/mydomain/assets/js/jquery-3.2.1.min.js:2:1001
ProductGallery.prototype.initFlexslider@https://mydomain.com/wp-content/plugins/woocommerce/assets/js/frontend/single-product.min.js?ver=3.2.0:149:3
ProductGallery@https://mydomain.com/wp-content/plugins/woocommerce/assets/js/frontend/single-product.min.js?ver=3.2.0:112:4
$.fn.wc_product_gallery@https://mydomain.com/wp-content/plugins/woocommerce/assets/js/frontend/single-product.min.js?ver=3.2.0:279:3
@https://mydomain.com/wp-content/plugins/woocommerce/assets/js/frontend/single-product.min.js?ver=3.2.0:287:3
each@https://mydomain.com/wp-content/themes/mydomain/assets/js/jquery-3.2.1.min.js:2:2713
each@https://mydomain.com/wp-content/themes/mydomain/assets/js/jquery-3.2.1.min.js:2:1001
@https://mydomain.com/wp-content/plugins/woocommerce/assets/js/frontend/single-product.min.js?ver=3.2.0:286:2
j@https://mydomain.com/wp-content/themes/mydomain/assets/js/jquery-3.2.1.min.js:2:29997
g/</k<@https://mydomain.com/wp-content/themes/mydomain/assets/js/jquery-3.2.1.min.js:2:30313`

**Comment by mikejolley** [comment]
Your theme is loading a non-core version of jQuery into the page. This could be part of the issue - our's is only tested against the version of jQuery included in WordPress. You don't need to include your own.

I'd suggest enabling SCRIPT_DEBUG to help track down the issue; the scripts are minified so it can make working out issues like this difficult. 

https://codex.wordpress.org/Debugging_in_WordPress#SCRIPT_DEBUG

Good luck :)
