### ISSUE TITLE
how to add Schema for google reviews in the product page

### ISSUE THREAD

**Issue by Gowsalayadevi** [woocommerce/woocommerce#16437]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [x ] I have included a failing test as a pull request (Optional)

## Expected/actual behavior

Hi,
I am using woo-commerce 3.1.1 version and I am using google certified third party reviewers Feefo to get customer reviews.
The issue is woo-commerce built-in structured data is not recognising these reviews and not adding in the mark up. I tried adding my own code to over write the one generated by woo-commerce but I couldn't. 

Is there any way I could add the schema for google customer reviews in woo-commerce 

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
Our schema only recognises WordPress comments (which we use for reviews). Reviews being pulled in from another platform would need to be marked up yourself, or by the platform. You'll need to have a developer customise this if it's not supported by Feefo.
