### ISSUE TITLE
Address changed form account page but tax still displayed on cart page

### ISSUE THREAD

**Issue by zestard-ankit** [woocommerce/woocommerce#16430]
i set up a store for **UK** and customers from **UK** has to pay **20% vat**. i follow this tutorial https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/
i get issue while changing address from my account page. 

1.) i set address inside **UK** while registering in my site form front side.
2.) go to product page add one product in cart.
3.) on cart page tax is visible which is correct because i registering my account for **UK** address.
4.) now i go to my account page, in addresses tab edit my address and change it to **US**.
5.) again go to cart page i show tax is still visible.

could you pls help me to get out of this.

**Comment by mikejolley** [comment]
The tax will update when the user updates his address on either the cart or checkout. I believe the issue of carrying across account address changes to the current session is resolved in 3.2/master.

That said, it depends on your tax settings. They need to be based on customer address and not the shop base for it to work how you describe.

Thanks
