### ISSUE TITLE
Session data not being overwritten when it should be

### ISSUE THREAD

**Issue by partounian** [woocommerce/woocommerce#16436]
I noticed in the history [here](https://github.com/woocommerce/woocommerce/commits/master/includes/data-stores/class-wc-customer-data-store-session.php) it seems that a fix for sessions was reverted with another put in place, but the new fix does not actually fix the issue (in my case at least) with data when it should be overwriting session data. For example, user updates address in my account section, and it shows fine, but when they go to checkout it does not show the updated info.

**Comment by WM4362** [comment]
Just confirming the described issue is still present - tested on a vanilla install of WordPress 4.8.1, WooCommerce 3.1.1 & Storefront 2.2.4.

To clarify, address changes at the Checkout for Account users are reflected back under My Account, but as @partounian described, changes under My Account are not reflected at the Checkout.

**Comment by mikejolley** [comment]
This is why the new issue form suggests testing against master before reporting bugs. It's fixed for 3.2. https://github.com/woocommerce/woocommerce/commit/57ee9f58cfbacbb4e192f65fc1fe7a736113a825
