### ISSUE TITLE
The product overview ignores the product_shipping_class taxonomy argument

### ISSUE THREAD

**Issue by kallehauge** [woocommerce/woocommerce#16435]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Vanilla install of WordPress + WooCommerce.
2. Import dummy-data provided by WooCommerce.
3. Go to `WooCommerce > Settings > Shipping > Shipping classes`.
4. Click the "count number" to get to a "broken overview".

## Expected/actual behavior

When I follow those steps, I see a product overview where the links above the overview table ignores the `product_shipping_class` argument in the URL (`All`, `Published`, `Draft`).
There is also a difference in what is expected to be displayed. The Shipping classes count shows the amount of published product with the shipping class but it link to the "All products" list instead of the "published".

I expected to see a product overview with only published products with the shipping class and links that respect and include the `product_shipping_class` taxonomy _(the reason why I expect it to be the published products is because the "count" on the "Shipping classes" page only count "published")._

_Notice: the "3" in product count:_
![screen shot 2017-08-13 at 23 52 01](https://user-images.githubusercontent.com/3846700/29253685-85dc6554-8084-11e7-9abf-98f075cc0bb6.png)

_Notice: there is actually 4 products being displayed but the top one is a draft. Also notice the "All (23)" link. This ignores the taxonomy in the URL._
![screen shot 2017-08-13 at 23 52 16](https://user-images.githubusercontent.com/3846700/29253686-8943a78e-8084-11e7-97c9-600619cdd9f0.png)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://woocommerce.dev
Site URL: http://woocommerce.dev
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Unix) PHP/5.6.16 LibreSSL/2.2.6
PHP Version: 5.6.16
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.43.0
SecureTransport

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

Debug Bar ElasticPress: by 10up – 1.2
Debug Bar: by wordpressdotorg – 0.9
R WC Autocomplete City by Zip-code: by Rommel ApS – 1.0.3
WooCommerce: by Automattic – 3.1.1
Yoast SEO: by Team Yoast – 5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.2 – 2.2.4 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
This is all controlled by WP and matches posts and post categories exactly. Drafts are not counted, and the 'all' 'draft' link etc at the top of the screen to not pass this query arg through.

You can create a post category and assign to a published post and draft post to see the same behaviour.

**Comment by kallehauge** [comment]
Thank you very much for the fast respond Mike :)
