### ISSUE TITLE
manage_stock not selectable from mapping menu

### ISSUE THREAD

**Issue by apb1963** [woocommerce/woocommerce#16431]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Import new product with zero stock, as the first product of the CSV file; using builtin CSV importer
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

 Neither stock nor stock_status have sample values; presumably it's because my first product listed has zero stock but I haven't verified the reason. **More importantly,** I added manage_stock to my CSV file, but it's not selectable from the menu; i.e. it doesn't exist on the menu, so I can't import it.

I was expecting to see...
A field on the mapping menu enabling a mapping between that field & manage_stock

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://greetonix.com
Site URL: https://greetonix.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 96 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.21
PHP Post Max Size: 6 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.57 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: [redacted]
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

WooCommerce Category Images Modification: by Ashfame – 0.1.2
affilinet Performance Ads: by affilinet – 1.8.7
Akismet Privacy Policies: by Inpsyde GmbH – 1.1.2
Akismet Anti-Spam: by Automattic – 3.3.4
Code Snippets: by Shea Bunge – 2.8.6
Contact Form 7: by Takayuki Miyoshi – 4.8.1
TinyMCE Advanced: by Andrew Ozz – 4.6.3
Woocommerce Table Rate Shipping: by JEM Plugins – 1.2.3
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.4
WooCommerce: by Automattic – 3.1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart
Checkout: #7 - /checkout
My account: #8 - /my-account

### Theme ###

Name: Storefront Child
Version: 1.0.0
Author URL: http://greetonix.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.4
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

Set stock to a value to have stock management enabled, or leave blank to have stock management off. There is a bug with assignments of 0 however already fixed in 3.2/3.1.2.

**Comment by philippbara** [comment]
Hi @mikejolley! I am managing my product lists thorugh Excel outside of Woocommerce environment and on changes I import the excel with the woocommerce default importer. I am also managing my stock with [Woocommerce Stock Manager](https://wordpress.org/plugins/woocommerce-stock-manager/) plugin. In the Excel I set:

1. The Column "In Stock" to 1
2. The column "Stock" to "Yes" 
3. The column "Backorders allowed?" to 1

The problem that I am facing is that when I change the stock of a product through the plugin this changes are overwritten on the next import. Is there a way to map the column "Stock" only to "manage_stock" so that the "stock" parameter is not overwritten on every import?
