### ISSUE TITLE
Webhooks response line_items meta_data

### ISSUE THREAD

**Issue by slier81** [woocommerce/woocommerce#16433]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product with meta data using REST API

```
curl -X POST https://foo.dev/wp-json/wc/v2/products \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "name": "Premium Quality",
  "type": "simple",
  "regular_price": "21.99",
  "description": "Foobar long desc.",
  "short_description": "Foobar short desc.",
  "categories": [
    {
      "id": 9
    }
  ],
  "images": [
    {
      "src": "http://site.com/image.jpg",
      "position": 0
    }
  ],
  "meta_data" :[
     {
      "key" : "vendor",
       "value": "1"
     }
  ]
}'
```
2.Create webhook for topic `order.created`
3.Make an orders with product that have meta data

## Expected/actual behavior

When I follow those steps, I see the following response from the `order.created` webhook response:
<pre><code>
Array
(
    [id] => 34
    [parent_id] => 0
    [number] => 34
    ...

    [payment_method] => cod
    [payment_method_title] => Cash on delivery
     ...
    [meta_data] => Array
        (
            [0] => Array
                (
                    [id] => 1165
                    [key] => _download_permissions_granted
                    [value] => yes
                )
               ...
        )

    [line_items] => Array
        (
            [0] => Array
                (
                    [id] => 38
                    [name] => WT2401 Trendy Top Red
                    [product_id] => 17
                    ...
                    [taxes] => Array
                        (
                        )

                  <b> [meta_data] => Array
                        (
                        ) </b>

                    [sku] => 
                    [price] => 23.32
                )

        )

     ...

)

</code></pre>

I was expecting to see :
<pre><code>
Array
(
    [id] => 34
    [parent_id] => 0
    [number] => 34
    ...

    [payment_method] => cod
    [payment_method_title] => Cash on delivery
     ...
    [meta_data] => Array
        (
            [0] => Array
                (
                    [id] => 1165
                    [key] => _download_permissions_granted
                    [value] => yes
                )
               ...
        )

    [line_items] => Array
        (
            [0] => Array
                (
                    [id] => 38
                    [name] => WT2401 Trendy Top Red
                    [product_id] => 17
                    ...
                    [taxes] => Array
                        (
                        )

                  <b> [meta_data] => Array
                        (
                            [0] => Array
                                 (
                                   [key] => vendor
                                   [value] => 1
                                 )
                        ) </b>

                    [sku] => 
                    [price] => 23.32
                )

        )

     ...

)

</code></pre>

## Aditional info
I have create a product with custom meta-data.
When the order were created and triggered topic `order.created`, the webhooks response contain `line_items[meta_data]` key but with empty value. Why is that? I assume it will contain my product meta data, but unfortunately its not.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://woo.dev
Site URL: http://woo.dev
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Ubuntu)
PHP Version: 5.6.30-1+deb.sury.org~trusty+1
PHP Post Max Size: 150 MB
PHP Time Limit: 300
PHP Max Input Vars: 9000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.2
WooCommerce: by Automattic – 3.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: MYR (RM)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #7 - /
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: ❌ Page does not contain the shortcode.

### Theme ###

Name: AcmePhoto
Version: 1.1.0
Author URL: https://www.acmethemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
You are adding meta data to a product object. Meta data in products is not automatically copied across to line items. They are not the same thing.

**Comment by slier81** [comment]
So how can i obtain product meta data through web hooks `order.created`?

**Comment by mikejolley** [comment]
Grab product ID from the line item, then use the products endpoint.

**Comment by slier81** [comment]
I'm trying to filter own product [product created by admin] from vendor product [created by supplier] and push to woocommerce store.
Let say customer bought 5 item..i want to only save an order with vendor item.
So that mean i need to do curl to product endpoint like 5 times? 
Is there a better way?

**Comment by mikejolley** [comment]
- Extend API to show that data 
- Add meta data to line items when creating an order

That’s all really. Showing all product data with line items would be inefficient.

**Comment by slier81** [comment]
@mikejolley 

Regarding suggestion number 1, may i know how to extend the api to show that data?

For suggestion number 2, i assume i have to make plugin for that.Am i right?

**Comment by mikejolley** [comment]
Both would require a custom plugin.

**Comment by vekikive** [comment]
@slier81 
Have you found the solution? I'm experiencing the same problem

**Comment by axeloz** [comment]
> So what is `line_items[meta_data]`?

I have the exact same question. The `meta_data` object exists in each line item but is empty. I did set an attribute on each product though.
