### ISSUE TITLE
CLI command "wp wc tool" not working

### ISSUE THREAD

**Issue by maxhetfeld** [woocommerce/woocommerce#16432]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. run `wp wc tool` from ssh
2. get an error "Error: 'tool' is not a registered subcommand of 'wc'. See 'wp help wc'."

## Expected/actual behavior

When I follow those steps, I see... error

I was expecting to see... wp wc tool working

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
WordPress 4.8.1 , WooCommerce 3.11
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16439
