### ISSUE TITLE
[3.1.1] variation issue (wrong combination when combination is over 30)

### ISSUE THREAD

**Issue by imslee100** [woocommerce/woocommerce#16453]
This problem occurs in WooCommerce 3.1.1. I tried to check it several times with fresh WordPress installation and the default theme (2017), with only WooCommerce plugin activated.

The dropdown always shows the wrong combination when combination is over 30 (over 30th combinations). 

For example:

I setup a variable product with 2 attributes: "Trans" and "Shade" and add following combinations:

Trans: HT, LT, MO
Shade for HT : A1, A2, A3, A3.5, B1, B2, W1, W2, W3, W4
Shade for LT : A1, A2, A3, A3.5, B1, B2, B3, B4, C1, C2, C3, C4, D2, D3, D4, W1, W2, W3, W4
Shade for MO : MO0, MO1, MO2, MO3, MO4

When I pick trans HT, the shade attribute still shows all shades of A,B,C,D,W,M for select. It is wrong. 
If the combination is not over 30, it only shows 'A1, A2, A3, A3.5, B1, B2, W1, W2, W3, W4'

How can I fix this issue?

**Comment by mikejolley** [comment]
https://elvtn.com/woocommerce/overridng-woocommerce-ajax-variations-limit/
