### ISSUE TITLE
Breadcrumbs display child category twice instead of parent category

### ISSUE THREAD

**Issue by thehoodDE** [woocommerce/woocommerce#16455]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a new post
2. While editing the post create a new category and choose a parent category for it from the drop down menu
3. Assign the post to the new category and publish the post
4. Open the page of the new category e.g. http://yourpage.com/category/parent-cat/child-cat/
5. Make sure your theme uses woocommerce_breadcrumb() to display breadcrumbs on the category page

## Expected/actual behavior

When I follow those steps, I see that the breadcrumbs display the child category twice: 
Home / Child Category / Child Category

I was expecting to see the breadcrumbs like this:
Home / Parent Category / Child Category

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```

WC Version: 3.1.1
WP-Version: 4.8.1
WP Multisite:  –
WP Memory Limit: 256 MB
WP Debug-Modus: –
Sprache: de_DE

```
</details>

**Comment by mikejolley** [comment]
Not sure why you removed the system status about plugins + themes. Very relevant.

<img width="668" alt="2017-08-15 at 11 30" src="https://user-images.githubusercontent.com/90977/29312435-35ee60d6-81ad-11e7-9aad-8be2e4abed0c.png">

No issue my side. Look at conflicts. I tested with a new category too - same output.

**Comment by thehoodDE** [comment]
I can reproduce it with a brand new installation of wordpress, woocommerce and the storefront theme.

Maybe it works for product categories in the shop but it does not for standard post categories.

![breadcrumbs_bugreport](https://user-images.githubusercontent.com/18501099/29316268-a9edc868-81c7-11e7-8e92-ab46b3bac871.jpg)

**Comment by mikejolley** [comment]
Ok I thought you meant products.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16476
