### ISSUE TITLE
CLI needs ability to circumvent pagination requirements

### ISSUE THREAD

**Issue by treyrich** [woocommerce/woocommerce#16450]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Run a `list` command via the CLI on a large dataset with the `per_page` argument as a number greater than 100 (or -1 which I would expect to give all results)

## Expected/actual behavior

When I follow those steps, I see an error `Invalid parameter(s): per_page {"status":400,"params":{"per_page":"per_page must be between 1 (inclusive) and 100 (inclusive)"}}`

I was expecting to see the ability to get the larger dataset

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

I realize that this is an enhancement, but in the past with the CLI you were able to run large reports on the data very quickly and easily, by fetching all results in a single query. Now you have to just POUND your database to run a report that should be very fast. For example, if you want to get details about all of your customers and you run:
`wp wc customer list --fields=billing,orders_count,total_spent --per_page=-1 --user=admin`
you get an error, so for a site with 86083 customers (real world example) it involves writing a bash script to loop through increments of 100 to retrieve all customers. What should take less than 1 minute ends up taking close to 5 hours on quite powerful hardware.

I recognize the need for there to be reasonable limits on the REST API but it seems unnecessary in the CLI.

**Comment by mikejolley** [comment]
Sounds like something you could write a pull request for if you wanted it in core short term?

**Comment by claudiosanches** [comment]
This comes from REST API, and by default on WP REST API is allowed only from 1 to 100 to not overload any endpoint.
So better keep this like is on WP REST API, and not allow a big number of results, not to mention that you can get more results from other pages too, creating a bash script looping for all pages.

**Comment by treyrich** [comment]
Just to confirm, there's no interest in a PR supporting CLI result sets larger than 100?

**Comment by claudiosanches** [comment]
@treyrich CLI is based on the REST API, and on WP REST API only allow max 100 results, if you need more you need to do more than one request.
My interest is to not go away from the the WP REST API does.

**Comment by claudiosanches** [comment]
This is where the limit of `100` comes from: https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/endpoints/class-wp-rest-controller.php#L286-L320

**Comment by treyrich** [comment]
Right, I understand where it comes from, and why it's there. My argument was simply that it seems fairly arbitrary to impose on the CLI. I completely agree that it should be enforced when accessing the REST API via HTTP, but I think that anyone using the CLI should be allowed to set their own limits.

I understand if the decision is that the CLI should not diverge from the REST API in any way, and I can accept that as an answer and even see the logic in the philosophy, but, for the record, I do disagree with the limitation being placed on the CLI in practice.

**Comment by fitzg2** [comment]
Why don't you modify the file?

**Comment by Solarbotics** [comment]
I am finding this limit frustrating as well. What is the point of the CLI if not to enable admins to take control of the installation?

**Comment by bbceg** [comment]
Hoping this can be reconsidered with the follow use-case:

Occasionally it's useful to pull down copies of a live site for use in development and elsewhere (e.g. a staging environment). Naturally I don't want any customer/order data to be included in these environments.

It's really helpful to have a few simple commands to delete this data. I suppose I could write some loops to keep checking until the "wp wc ... list" commands return nothing but it seems overly complex for a development environment that does not have the same limitations as a production environment.

Also, when I attempt to delete orders using the below snippet, it will happily delete more than 100:

`wp post list --field=ID --post_type=shop_order | xargs -r wp post delete --force`

This suggests that the 100 limit perhaps doesn't apply to the core wp cli, even if it does apply to the REST endpoint (or perhaps I'm missing something here).

Thoughts welcome. Perhaps there is a better way to do what I need.
