### ISSUE TITLE
Upgrade Admin Alert Should Only Appear Once

### ISSUE THREAD

**Issue by dimensionmedia** [woocommerce/woocommerce#16461]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Upgrade WooCommerce (I upgraded from 3.1.1 to 3.2.0-dev)
2. Notice the admin notice to upgrade the database (which may run in the background)
3. After completion, the alert appears on nearly every admin screen until it is dismissed.

## Expected/actual behavior

I was expecting to see this only appear once when it was actually completed, with further mention maybe in WooCommerce specific pages/settings.

This ticket was made at the request of Doug (see https://twitter.com/WooCommerce/status/897351219412439041 ) in the context of reducing noise of admin alert boxes in the WordPress backend.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://enviragallerytest.dev
Site URL: http://enviragallerytest.dev
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.50.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.28
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (15) ###

Beaver Builder Plugin (Lite Version): by The Beaver Builder Team – 1.10.7
Debug Bar Actions and Filters Addon: by Subharanjan – 1.5.2
Debug Bar: by wordpressdotorg – 0.9
Envira Gallery - Albums Addon: by Envira Gallery Team – 1.4.4
Envira Beaver Builder Test: by David Bisset – 1.0
Envira Gallery - Dynamic Addon: by Envira Gallery Team – 1.2.9
Envira Gallery: by Envira Gallery Team – 1.6.1.5
Envira Gallery - Multisite Updater Addon: by Envira Gallery Team – 1.0.0
Envira Gallery - Proofing Addon: by Envira Gallery Team – 1.1.8
Envira Gallery - Social Addon: by Envira Gallery Team – 1.3.8
Envira Gallery - Tags Addon: by Envira Gallery Team – 1.5.0
Envira Gallery - Videos Addon: by Envira Gallery Team – 1.2.9.2
Envira Gallery - WooCommerce Addon: by Envira Gallery Team – 1.1.7
WooCommerce: by Automattic – 3.1.1
Yoast SEO: by Team Yoast – 5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Cart: #392 - /cart/
Checkout: ❌ Page does not contain the shortcode.
My account: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
@dimensionmedia Just talking about the updated notice right?

The other (wooconf) is not in core. Saw that was what the thread was about...

**Comment by dimensionmedia** [comment]
I could only write the ticket about the update notice because after i replaced WooCommerce plugin it’s the only notice that appeared.

If you want me to attempt viewing the other admin notice (that one simply didn’t have a traditional dismiss notice and I thought maybe it should) with the WooCommerce plugin I had before, let me know. But you know which dialog i’m speaking of.

Thank you! :-)

**Comment by mikejolley** [comment]
@dimensionmedia So the one that has no dismiss button (update nag) is mandatory. The data update needs to happen in order to keep our DB running correctly. The only reason it's a nag vs just doing it is to give users a chance to backup and understand first - some update processes can take a while.

During update, the notice is kept around so you know it's processing. This also lets you run all processes right away in case it stops for whatever reason.

When it's finished, the user is again notified. A dismiss button in this case is correct and is pretty standard across all WP notices. As such, this won't be changing.

> in the context of reducing noise of admin alert boxes in the WordPress backend.

We have a separate idea for this which we're hoping to start working on in Q4. Basically, a single admin screen specific to WC where we can group all notices, alerts, and nags without cluttering other pages in WP Admin. That will be better than nixing one alert :)

Thanks!
