### ISSUE TITLE
Image Zoom - Image disappears

### ISSUE THREAD

**Issue by sterenas** [woocommerce/woocommerce#16471]
On the latest (just updated) version of WooCommerce if you zoom in a product/variation image by pressing the zoom icon (that shows on the top right of the image) and then zoom in to the max (on the iPhone by double tapping the image or spreading your fingers), the image disappears.  Tested both on a notebook and iPhone, you get a full black screen.
Previous WooCommerce version doesn't show this behavior using the same plugins.

**Comment by mikejolley** [comment]
This is not specific to latest, it happens on all versions of 3.x

**Comment by mikejolley** [comment]
Also specific to 2017 theme it seems.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/16475
