### ISSUE TITLE
update product api not working using .net SDK

### ISSUE THREAD

**Issue by sagaraloha** [woocommerce/woocommerce#16474]
WooCommerceNET, Version= 0.7.2

When i am trying to update the product, it updates successfully. but it throws an exception. 'HTTP/1.1 500 Internal Server Error'

Request details:

POST http://59e.e22.myftpupload.com/wp-json/wc/v2/products/389?oauth_consumer_key=ck_0f48ef6e23336a83dc40ba7263f2c6a928ec8a8e&oauth_nonce=adce1ae6ea4946e69a25171f96dda1cf&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1502722578&consumer_key=ck_0f48ef6e23336a83dc40ba7263f2c6a928ec8a8e&consumer_secret=cs_1379285e7f1b8530c132c65007b795e0e582698f%26&oauth_signature=EzRhXRTj36wnknfN0Ok3s0JEu9RGRaWcsnLUMjyp%2FGo%3D HTTP/1.1
Content-Type: application/json
Host: 59e.e22.myftpupload.com
Content-Length: 41
Expect: 100-continue
Connection: Keep-Alive

Parameters: {"manage_stock":true,"stock_quantity":10}

Response details:
HTTP/1.1 500 Internal Server Error
Date: Mon, 14 Aug 2017 14:56:20 GMT
Server: Apache
X-Robots-Tag: noindex
Link: <http://59e.e22.myftpupload.com/wp-json/>; rel="https://api.w.org/"
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization, Content-Type
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Set-Cookie: woocommerce_items_in_cart=1; path=/
Set-Cookie: woocommerce_cart_hash=24d7c8862cce1686be909659f526805e; path=/
Set-Cookie: wp_woocommerce_session_a42e6e3abf16daf4188bc07aa1a12c96=3%7C%7C1502895381%7C%7C1502891781%7C%7C23fdf68a1d8ad72cadb92d4652b1d589; expires=Wed, 16-Aug-2017 14:56:21 GMT; Max-Age=172800; path=/
Content-Length: 0
Content-Type: application/json; charset=UTF-8
X-Port: port_10727

Please help me regarding this.

Thanks,

**Comment by mikejolley** [comment]
`500 Internal Server Error` is generic. If you want to know the cause you'll need to look at the server php error logs and see what is there. It could literally be anything; memory limit, plugin conflict, etc etc. The logged error should give you enough info to work with.

**Comment by sagaraloha** [comment]
I am not getting any errors in PHP error logs, please give me some another solution.

**Comment by mikejolley** [comment]
Maybe you need to enable logging then? 500 is not enough to work with.

**Comment by sagaraloha** [comment]
We have enable the logging. But we are not able to find any log for this case. Also we have called this API using RestClient in this case. It's working fine.

But, when we are calling .Product.Add(Product) API using in .net SDK. It's returning error. Because we need to implement our integration in .net technology. 

Please let us know your thoughts on this.

**Comment by sagaraloha** [comment]
Did you get chance to look into this.

**Comment by mikejolley** [comment]
I cannot look into this - I don't have access to your server.

**Comment by sagaraloha** [comment]
Hi,

It's returning 500 error. here is error message, 

   at WooCommerceNET.RestAPI.<SendHttpClientRequest>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WooCommerceNET.RestAPI.<PostRestful>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WooCommerceNET.Base.WCItem`1.<Update>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Please review this. It may be helpful for you. 

Thanks,
