### ISSUE TITLE
No way to get shipping zone instance ID on the checkout page

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#16479]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Issue description

As far as I can tell, there's no way that JavaScript code running on the checkout can *reliably* determine, for a shipping method with an instance ID, what that instance ID is. I've read through the shipping developer documentation in the Github wiki.

*Normally* it's there, in the value of the input:

```
<input name="shipping_method[0]" data-index="0" id="shipping_method_0_flat_rate18" value="flat_rate:18" class="shipping_method" type="radio">
```

*But*, apparently, that's no reliable. This official Woo extension, in its changelog, says that it supports shipping zones - https://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-distance-rate-shipping/changelog.txt . But the input, for this one, has:

```
<input name="shipping_method[0]" data-index="0" id="shipping_method_0_distance_rate" value="distance_rate" class="shipping_method" checked="checked" type="radio">
```

There's nothing else I can see elsewhere either.

My problem then is that, in my code, I can allow the site owner to create settings that correspond to each shipping instance on the backend.... but when it comes to the checkout itself, there's nothing I can do to find out the particular instance that each shipping method available in the DOM corresponds to.

Or is this a bug in that extension? Since it's an official one, I'm working with the assumption that it's "doing it right".

**Comment by claudiulodro** [comment]
It's not really a bug in anything if it doesn't make it easy for you to get the shipping zone ID using JavaScript . . .

There are a few ways you can set up the forms if you need a way to get the ID using JS. One simple one: You can add a filter to `'woocommerce_form_field_radio'` and add a `data-zoneID` attribute to the radio elements.
