### ISSUE TITLE
'ORDERS' section will NOT load...

### ISSUE THREAD

**Issue by dreamesper** [woocommerce/woocommerce#16472]
Latest release of WooCommerce, 3.1.2 seems to have trouble loading the orders section. If someone could comment and/or assist, I would appreciate it. Thanks.

**Comment by mikejolley** [comment]
I'm not seeing any related changes in the fix release (https://github.com/woocommerce/woocommerce/compare/3.1.1...3.1.2). It's also loading here just fine and I've seen no other reports. e2e and unit tests have also passed.

Go through the "isolating your issue' steps on the new issue form, and see if you have an error log. It may be memory related. If you do post back, include all requested information or we don't have much to go on.

Thanks!
