### ISSUE TITLE
Variations need additional update logic.

### ISSUE THREAD

**Issue by digamber89** [woocommerce/woocommerce#16477]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

I encountered a very odd error with Variations today. 

1. Lets take for example you have a single attribute used for variaton. Lets say color : Black, Green, Blue.
2. Then you create variations from all attributes this will create 3 variations from the available attributes. 
3. Then if you click add a variation again, I believe there should be atleast a prompt warning the user that all possible variations have been added.
4. Otherwise what happens is an additional / unusuable variation is added.

In 3 variations it is very easy to track down that there are a finite number of variations. However when there are multiple attributes and multiple variations it is very difficult to track down. 

This issue occurred yesterday. And what happens in the front end is that it says 

`Sorry, this product is unavailable. Please choose a different combination.`
![test variations generic woocommerce](https://user-images.githubusercontent.com/6367450/29359662-4b3d583c-829f-11e7-90d4-2768b9d9b050.png)
![variations-extra-added](https://user-images.githubusercontent.com/6367450/29359663-4c7a7e00-829f-11e7-9dff-d349ce43309f.png)
![attributes](https://user-images.githubusercontent.com/6367450/29359664-4d8c65c4-829f-11e7-83c9-461e264d99b6.png)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://202.166.207.19/general-woocommerce
Site URL: http://202.166.207.19/general-woocommerce
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.6.16
PHP Version: 5.6.16
PHP Post Max Size: 6 GB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.54.0
NSS/3.28.1

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 5 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: gcomm_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

User Switching: by John Blackbourn – 1.0.9
Woo Preview Emails: by Digamber Pradhan – 1.2.9
WooCommerce: by Automattic – 3.1.1 – 3.1.2 is available

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #27 - /
Cart: #28 - /cart/
Checkout: #29 - /checkout/
My account: #30 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.2 – 1.3 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
We're aware of the usability issues with this. It's being redesigned from scratch. The issue has not been fully scoped yet, but when details are available we'll add them to https://github.com/woocommerce/woocommerce/issues/13085

Thanks!
