### ISSUE TITLE
API v2 does not fetch variation products linked items

### ISSUE THREAD

**Issue by dkalinai** [woocommerce/woocommerce#16473]
Can anyone help me understand why in v1 I get the header product and the subproducts with all of the information and quantities and in v2 I just get references to the sub items ids. What If I need to check 100 products and each having 5 sub products I would make over 200 server requests to do so instead of 1 with v1.

**Comment by mikejolley** [comment]
v2 has a dedicated variation endpoint for getting all variation data. Loading all data on 1 product endpoint is not efficient. If you have the variation ID, use it directly. No need to go via parent product.

**Comment by dkalinai** [comment]
I don't agree here. If I have 100 products with 5 variations inside in v1 I could make 1 call, even if it took a minute to execute and get all of the data I needed for my Application, which I can work with there. With v2 you are basically saying that I need to make 100 server requests. How efficient is that? I need to fetch all info for the 100 products and if the only way to load variation data is via the dedicated method then I will need to make the initial request to get all of the variation id's and then use the dedicated method per item. Honestly don't see the logic behind this change. Will keep using v1 as it is so much more efficient.

**Comment by mikejolley** [comment]
What is your actual use case for doing that?

**Comment by dkalinai** [comment]
So here is the thing. I got a shop where I have various T-shirts. Say T-Shit Black, T-Shirt-Blue, T-Shirt etc. Each shirt has a size - XS, S, M, L, XL etc. I am writing my own software so that for example I can fetch all T-shirts which I have, and their sizes in amounts an show it in a nice table. That means that compared to v1 in v2 I can do this row by row only now which is not that good of a solution, compared to v1 where I could fetch everything in bulk. And yes I already use the GET link and cut it down by category etc, but I am still left with quite a bit of items coming back and I need to know all sizes of it. This helps a lot in future purcahses etc. Also it has another use case where I can fetch all of this data and show for instance only T-shirts which have S size only. Hopefully that sheds more light.

**Comment by mikejolley** [comment]
@claudiosanches Do we need an 'expand' option for this?

**Comment by claudiosanches** [comment]
No, we removed it to reduce the overload and the compressibility.

> What If I need to check 100 products and each having 5 sub products I would make over 200 server requests to do so instead of 1 with v1.

You can query by every variable product at once, there is endpoints for it and you can filter products by ID too.

**Comment by dkalinai** [comment]
Can you elaborate on your answer @claudiosanches ? How does one query 100 products and get the v1 experience? say if my current flow in v1 is "v1/products?category=208&per_page=100" this fetches me all variable products at once for category 208 but in v2 instead of fetching variations this same line just shows "related_ids" so what is the correct way to not do 100 requests and do in v2 what i can in v1?

**Comment by claudiosanches** [comment]
@dkalinai forget about the v1 experience. This is the first step. 

> say if my current flow in v1 is "v1/products?category=208&per_page=100" this fetches me all variable products at once for category 208 

Yes and this cause a big overload of data if you have too many variations, can slow down your store and so on.
That's why is better break it into small requests, you can get all variable IDs too from `products?category=208&per_page=100` and query by ID after using `products/<product_id>/variations`.

> ut in v2 instead of fetching variations this same line just shows "related_ids"

Not true, in v2 display `variations` and not `related_ids`.

I'm open for new ideas and ways to improve it, but not to give a step back and do like v1, that's why is not more v1 and now is v2, because is getting improved, for you maybe is not what you prefer, but is a performance improvement, not to mention how is more easy to create and manipulate variations in v2.

**Comment by jarmosiim** [comment]
Reading this thread, I'd love to understand one simple thing - how can I get the data of a product + all its variations (and its quantities) in one server request?

**Comment by claudiosanches** [comment]
@jarmosiim you need more than one request, but soon I plan have some advanced report endpoints, in especial for stock/quantities. And it's always possible to extend the REST API, since our REST API is just extending the WordPress REST API.

**Comment by jarmosiim** [comment]
@claudiosanches Okay.. what's the timeline for this? And could you get back to me on the question? :)

**Comment by claudiosanches** [comment]
@jarmosiim there is no timeline, but we are working on REST API v3 in: https://github.com/woocommerce/wc-api-dev
Please feel free to help.

**Comment by jarmosiim** [comment]
@claudiosanches Okay then that is quite a way off. Could you help me with the question I had?

**Comment by claudiosanches** [comment]
@jarmosiim what question? About one request? It's not possible in v2, we removed it because the overload of data generated at once.

**Comment by jarmosiim** [comment]
@claudiosanches Okay, so it is indeed true what @dkalinai said that you might need hundreds of requests to do what was possible before with just one? Is there any way around it? And if so then what is the way?

**Comment by claudiosanches** [comment]
@jarmosiim Please read my answers, I already replied about it.

**Comment by jarmosiim** [comment]
@claudiosanches I'm just probably thick but I haven't seen a simple instruction to achieve this...

**Comment by dkalinai** [comment]
@jarmosiim That's because there is none most probably. Instead of allowing me to worry about performance related things they just take the functionality away assuming nobody needs it. And then want to reinvent the wheel to an extent in v3. I don't get this approach personally. I fail to see how 100 server requests (and we are talking about 1 page of data here) will be better. Arent you afraid that this approach might actually result in the requests bouncing back?

**Comment by dkalinai** [comment]
@claudiosanches So I counted roughle a page fetches in 35 seconds, each variable product fetches in 2.5 seconds. So to sum up 4 pages of data 319 records fetch in around 13 minutes. 

My question is how log will v1 be around? I cant allow the app to wait for 13 minutes without sequencing 319 parallel requests at the same time. Is there a timeline for v1 deprecation and if so when. v2 is good for customer stuff but bad for product fetching. If i  can cut this time down even by half via v1 I will do so.

**Comment by claudiosanches** [comment]
@dkalinai You can check our deprecated plans on: https://github.com/woocommerce/woocommerce/wiki/Contributing-to-the-WooCommerce-REST-API#deprecation-of-older-versions

**Comment by ChristianGerdes** [comment]
Any progress in this regard? I'm also interested in fetching all products with all variations in one request instead of hundreds
