### ISSUE TITLE
Improved label for `Account Password`

### ISSUE THREAD

**Issue by Mte90** [woocommerce/woocommerce#16481]
I got a report from an user of an e-commerce that when is doing a checkout Woocommerce ask for Account Password but for him wasn't clear that he need to do a registration on the portal (flag enabled on woocommerce for registration on checkout).

So looking on https://plugins.trac.wordpress.org/browser/woocommerce/tags/3.1.2/includes/class-wc-checkout.php#L219

It is clear that this label is showed only in case of registration so maybe is better to replace with `Create Account Password` in that way there will be not anymore issues.
Looking at the code probably if the option for the username and this one are together enabled this issues have no sense.
So maybe is better to add an if statement for a different string in case of only password (screen in italian that created the problem):
![schermata_2017-08-16_alle_14 50 31](https://user-images.githubusercontent.com/403283/29366805-552db642-829b-11e7-8bb3-d1ddd923abd8.png)

**Comment by claudiulodro** [comment]
Alternate solution maybe worth exploring: Add a tooltip or notice explaining an account is going to be created.

This does look like it's asking for a password and not creating a password:
<img width="338" alt="screen shot 2017-08-17 at 11 43 27 am" src="https://user-images.githubusercontent.com/7317227/29428270-71a011b6-8341-11e7-87ce-63da7a1ffbc5.png">

**Comment by Mte90** [comment]
A tooltip is not so much visible often and a text label is more friendly

**Comment by mikejolley** [comment]
Wording makes sense to me, see https://github.com/woocommerce/woocommerce/pull/16523
