### ISSUE TITLE
Wrong path to debug.log on wiki

### ISSUE THREAD

**Issue by stas-lesiuk** [woocommerce/woocommerce#16494]
Hello, it seems that this wiki page has a mistake: https://github.com/woocommerce/woocommerce/wiki/Using-WP_DEBUG_LOG-to-log-errors 
It says errors would appear in `wp-config/debug.log`, while this link: https://codex.wordpress.org/Debugging_in_WordPress says they would appear in `wp-content/debug.log`

**Comment by claudiosanches** [comment]
I just fixed, thanks for report it.
