### ISSUE TITLE
Can't do refunds with PayPal Standard in Sandbox mode

### ISSUE THREAD

**Issue by brezocordero** [woocommerce/woocommerce#16491]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Site with PayPal standard on sandbox mode with correct API Sandbox credentials. IPN is set up on PayPal.

1. Place an order and pay using the PayPal standard on sandbox mode. 
2. On order notes, IPN payment is completed, payment processing.
3. Edit the order, click on refund, refund via PayPal.
## Expected/actual behavior

When I follow those steps, I see...

Error message: Transaction ID is not valid
On the logs: 
```
2017-08-17T09:36:58+00:00 INFO Refund Result: stdClass Object
(
    [TIMESTAMP] => 2017-08-17T09:36:58Z
    [CORRELATIONID] => 51b2f6d3ee4ce
    [ACK] => Failure
    [VERSION] => 84.0
    [BUILD] => 37719150
    [L_ERRORCODE0] => 10004
    [L_SHORTMESSAGE0] => Transaction refused because of an invalid argument. See additional error messages for details.
    [L_LONGMESSAGE0] => The transaction id is not valid
    [L_SEVERITYCODE0] => Error
    [REFUNDSTATUS] => None
    [PENDINGREASON] => None
)
```

I was expecting to see...

Order is refunded

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

Tagging @tommyshellberg in case he would like to add some clarifications

Reported in 618734-zd-woothemes

`
### WordPress Environment ###

Home URL: 
Site URL: 
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.22
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.54.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Akismet Anti-Spam: by Automattic – 3.3.4
Jetpack by WordPress.com: by Automattic – 5.2.1
WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.4
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Just tested this one and it worked as expected. Ensure you actually have a 'Transaction ID' set on the order, and that the order was placed in sandbox too, and captured, not authorised.

On the account side, the payment also needs to be accepted not pending. I had the option to accept payments in IPN settings for the business account testing with.

I couldn't try IPN because i'm on local host, but I enabled PDT.

<img width="1345" alt="2017-08-18 at 16 28" src="https://user-images.githubusercontent.com/90977/29465802-6fcb3ff4-8432-11e7-801d-f90d34170b84.png">

This was testing on `master` also but PayPal code base has not been touched in a while.
