### ISSUE TITLE
Attributes looping do not save

### ISSUE THREAD

**Issue by Mtcva1** [woocommerce/woocommerce#16495]
Attributes looping indefinitely and do not save. Cross selling and up sells do not display.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Added attributes do not load and loop indefinitely.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...
deactivated plugins but nothing changes
I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Select2```
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x
