### ISSUE TITLE
"woocommerce_product_thumbnails" hook

### ISSUE THREAD

**Issue by BusinessBloomer** [woocommerce/woocommerce#16492]
File: `woocommerce\templates\single-product\product-image.php`

Original PHP (line 60+):

```
do_action( 'woocommerce_product_thumbnails' );
// close PHP
// close figure
// close div
```

Problem: the new product gallery replaces the `<figure></figure>` entirely if I'm not wrong. Hooking into `woocommerce_product_thumbnails` is therefore not possible anymore.

Can this be moved outside?

```
// close PHP
// close figure
do_action( 'woocommerce_product_thumbnails' ); 
// close div
```

**Comment by claudiulodro** [comment]
Confirmed. If you output anything on the 'woocommerce_product_thumbnails' action it will get hidden by the gallery JS.

**Comment by mikejolley** [comment]
We need `woocommerce_product_thumbnails` where it is to insert our gallery thumbnails - thats what this hook is for, the gallery.

`woocommerce_before_single_product_summary` might be a good alternative as this is what the gallery itself is output on.

If not, we'll need a new hook possibly. If you can justify this, please send a PR.

Thanks

**Comment by webprom** [comment]
any news on missing hook there?

**Comment by oliverwh** [comment]
Any word here?

**Comment by mikejolley** [comment]
If someone wants to raise a PR they can, but the existing hooks need to be left alone.
