### ISSUE TITLE
Missing Select2 sortable inputs for enhanced select

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#16493]
@mikejolley @claudiosanches I found that select2 sortable works great with product and customer AJAX search but it doesn't support for `wc-enhanced-select` passing `data-sortable="true"` over there. Any help would be appereciated. OR is it supposed to work only with AJAX way :)

**Comment by mikejolley** [comment]
@claudiulodro is working on sorting/sortable here https://github.com/woocommerce/woocommerce/pull/16486
