### ISSUE TITLE
Helper: Shop manager role can access & interact with WooCommerce.com Subscriptions tab

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#16496]
When a shop manager role access the WP Dashboard, they have no access to the plugins/themes section of the Dashboard, but when they go to WooCommerce > Extensions > WooCommerce.com Subscriptions, they can 

* Download extensions (not to the site but to their computer)
* Enable or disable downloaded extensions

This should not be the case, especially the last one is problematic.

The easiest solution would be to just hide this sections for shop managers. Another solution would be to disable any interaction with this tab.

cc @garymurray

**Comment by jobthomas** [comment]
Update, it just disables (re)activating licenses, not the actual extension.

Suggested solution:

Change this text:

"To receive plugin updates please make sure the product is installed, activated and connected to your WooCommerce.com account."

To:

"To receive plugin updates please make sure the product subscription is installed, activated and connected to your WooCommerce.com account. Extension activation happens in Plugins."

**Comment by jobthomas** [comment]
And maybe a feature request: upon connecting to WooCommerce.com the person connecting can change the settings to share their woocommerce.com account with the other users or not.

**Comment by DavidAnderson684** [comment]
Relevant: https://github.com/woocommerce/woocommerce/issues/15987

Then (last month) Mike J said, concerning shutting off access to this tab:

> "This is simply exposing public data. If we ever did add something which would install a plugin, this would certainly need to check the role. In fact we do that in some places now for things which use our background installer such as ... Since this has not changed in 3.0 I vote we leave as-is and revisit if installing/downloading is ever added to the helper."
