### ISSUE TITLE
Product Attributes Custom Ordering Bug

### ISSUE THREAD

**Issue by GTO-1** [woocommerce/woocommerce#16504]
Hello

suddenly my product attributes (size) are not any longer in the custom order i set them too. 
Disabled all Plugins except WC and Used the 2017 WP Theme but still the same bug.

I have recorded a screencast for you to demonstrate the bug:

http://recordit.co/JxK7qlRfIl

My System Log:

` 
### WordPress Environment ###

Home URL: https://www.gtoclothing.com 
Site URL: https://www.gtoclothing.com 
WC Version: 3.1.2 
Log Directory Writable: ✔ 
WP Version: 4.8.1 
WP Multisite: – 
WP Memory Limit: 256 MB 
WP Debug Mode: – 
WP Cron: ✔ 
Language: en_US

### Server Environment ###

Server Info: Apache 
PHP Version: 7.0.2 
PHP Post Max Size: 100 MB 
PHP Time Limit: 180 
PHP Max Input Vars: 10000 
cURL Version: 7.48.0 
OpenSSL/1.0.1u

SUHOSIN Installed: – 
MySQL Version: 5.6.33 
Max Upload Size: 100 MB 
Default Timezone is UTC: ✔ 
fsockopen/cURL: ✔ 
SoapClient: ✔ 
DOMDocument: ✔ 
GZip: ✔ 
Multibyte String: ✔ 
Remote Post: ✔ 
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1 
WC Database Prefix: wp_ 
woocommerce_sessions: ✔ 
woocommerce_api_keys: ✔ 
woocommerce_attribute_taxonomies: ✔ 
woocommerce_downloadable_product_permissions: ✔ 
woocommerce_order_items: ✔ 
woocommerce_order_itemmeta: ✔ 
woocommerce_tax_rates: ✔ 
woocommerce_tax_rate_locations: ✔ 
woocommerce_shipping_zones: ✔ 
woocommerce_shipping_zone_locations: ✔ 
woocommerce_shipping_zone_methods: ✔ 
woocommerce_payment_tokens: ✔ 
woocommerce_payment_tokenmeta: ✔ 
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔ 
Hide errors from visitors: ✔

### Active Plugins (37) ###

Elite Video Player: by _CreativeMedia_ – 2.3.0 
WooCommerce Order Status & Actions Manager: by Actuality Extensions – 1.7.4 
Contact Form 7: by Takayuki Miyoshi – 4.8.1 
Enable Media Replace: by Måns Jonasson – 3.1.1 
Envato Market: by Derek Herman – 1.0.0-RC2 
Anti-Malware Security and Brute-Force Firewall: by Eli Scheetz – 4.17.29 
Improved Variable Product Attributes for WooCommerce: by Mihajlovic Nenad – 3.3.0 
My WordPress Health Check: by Frank Corso – 1.4.2 
Nextend Facebook Connect: by Nextendweb – 2.0.2 
Nextend Google Connect: by Roland Soos 
Jamie Bainbridge – 1.6.1

WooCommerce Product Filter: by Mihajlovic Nenad – 6.3.0 
Product Sizing Guide: by Daniel Mueller – 1.0.1 
WP Real Media Library: by Matthias Günter – 3.0.1 
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6 
Compress JPEG & PNG images: by TinyPNG – 2.2.4 
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos 
SevenSpark – 3.2.7

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com 
DavidAnderson – 1.13.5

Woocommerce Advanced Bulk Edit: by George Iron – 4.2.2 
WooCommerce Email Customizer: by cxThemes – 3.13 
WooCommerce Stripe Gateway: by WooCommerce – 3.2.2 
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 
WooCommerce PDF Invoice: by RightPress – 3.1.6 
WooCommerce Shipping Tracking: by Lagudi Domenico – 12.3 
WooCommerce Shop as Customer: by cxThemes – 2.10 
SOFORT Banking for WooCommerce: by Awesome UG & MarketPress – 1.1.17 
WooCommerce Table Rate Shipping: by Bolder Elements – 4.0.3 
WooCommerce: by Automattic – 3.1.2 
WooSidebars: by WooThemes – 1.4.3 
Wordfence Security: by Wordfence – 6.3.16 
Yoast SEO Premium: by Team Yoast – 5.2 
WP First Letter Avatar: by Dev49.net – 2.2.8 
WP-Lister Pro for eBay: by Matthias Krok – 2.0.24 
WP-Memory-Usage: by Alex Rabe – 1.2.2 
WP-Optimize: by David Anderson 
Ruhani Rabin 
Team Updraft – 2.1.1

WP Rocket: by WP Media – 2.10.7 
Yoast SEO: WooCommerce: by Team Yoast – 5.2 
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔ 
Force SSL: ✔ 
Currency: USD ($) 
Currency Position: left_space 
Thousand Separator: ' 
Decimal Separator: . 
Number of Decimals: 2 
Taxonomies: Product Types: downloadable (downloadable) 
external (external) 
grouped (grouped) 
simple (simple) 
variable (variable) 
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog) 
exclude-from-search (exclude-from-search) 
featured (featured) 
outofstock (outofstock) 
rated-1 (rated-1) 
rated-2 (rated-2) 
rated-3 (rated-3) 
rated-4 (rated-4) 
rated-5 (rated-5)

### WC Pages ###

Shop base: #11425 - / 
Cart: #10263 - /cart/ 
Checkout: #3260 - /checkout/ 
My account: #3261 - /my-account/

### Theme ###

Name: Flatsome Child Theme 
Version: 2.5 
Author URL: http:%20//www.uxthemes.com/ 
Child Theme: ✔ 
Parent Theme Name: Flatsome 
Parent Theme Version: 3.3.7 
Parent Theme Author URL: http://www.uxthemes.com/ 
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php 
flatsome/woocommerce/cart/cart-empty.php 
flatsome/woocommerce/cart/cart.php 
flatsome/woocommerce/checkout/form-checkout.php 
flatsome/woocommerce/checkout/form-coupon.php 
flatsome/woocommerce/checkout/thankyou.php 
flatsome/woocommerce/content-product.php 
flatsome/woocommerce/content-product_cat.php 
flatsome/woocommerce/content-single-product.php 
flatsome/woocommerce/global/breadcrumb.php 
flatsome/woocommerce/global/quantity-input.php 
flatsome/woocommerce/global/wrapper-end.php 
flatsome/woocommerce/global/wrapper-start.php 
flatsome/woocommerce/loop/loop-end.php 
flatsome/woocommerce/loop/loop-start.php 
flatsome/woocommerce/loop/orderby.php 
flatsome/woocommerce/loop/pagination.php 
flatsome/woocommerce/loop/result-count.php 
flatsome/woocommerce/loop/sale-flash.php 
flatsome/woocommerce/myaccount/form-login.php 
flatsome/woocommerce/myaccount/navigation.php 
flatsome/woocommerce/notices/error.php 
flatsome/woocommerce/notices/notice.php 
flatsome/woocommerce/notices/success.php 
flatsome/woocommerce/product-searchform.php 
flatsome/woocommerce/single-product/photoswipe.php 
flatsome/woocommerce/single-product/price.php 
flatsome/woocommerce/single-product/product-image.php 
flatsome/woocommerce/single-product/product-thumbnails.php 
flatsome/woocommerce/single-product/related.php 
flatsome/woocommerce/single-product/review.php 
flatsome/woocommerce/single-product/sale-flash.php 
flatsome/woocommerce/single-product/share.php 
flatsome/woocommerce/single-product/short-description.php 
flatsome/woocommerce/single-product/tabs/tabs.php 
flatsome/woocommerce/single-product/title.php 
flatsome/woocommerce/single-product/up-sells.php 
flatsome/woocommerce/single-product-reviews.php 
flatsome/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
> suddenly

What have you been doing?

Does your site have a termmeta table in the database, and is it empty?

**Comment by GTO-1** [comment]
> What have you been doing?

Well, nothing i know off. The last thing was the WP 4.8.1 update but did not check right after that and just saw it today and testing now since 4 hours without any success.

> Does your site have a termmeta table in the database, and is it empty?

Not too experienced when it comes to database editing, will have to google and check if this is the case. Will post you an answer about it later on.

**Comment by mikejolley** [comment]
If you've updated WordPress, depending on what version from, termmeta is built in. That table may be missing on your install.

**Comment by GTO-1** [comment]
> depending on what version from
I update daily and therefore the last version was probably 4.8.0

> That table may be missing on your install.
Where would i have to check this? In the SQL database?

Strange is, that custom ordering has worked before and it still does on other product attributes i have created (i.E. Color, Brand). 
It only behaves crazy (as far as i have tested) on the Size attribute and whenever i drag and drop it re-orders terms randomly.

**Comment by GTO-1** [comment]
Hurray!

Found the issue and it should be documented as others will/could come across the same bug!

1. Had a hierarchy for sizes set up in WC 2.X
2. WC 3.x removed this hierarchy ability for terms and i could not see the hierarchy anyomore.
3. Custom ordering did not work as there where terms with hierarchy and messed it completely up.
4. Used the snippet from here: https://github.com/woocommerce/woocommerce/issues/14417 to bring back the "parent term" option and released all child terms from it's parents.
5. voilà - everything works fine again!

You should definitely look into this or document it anywhere as i spent half a day to find the issue.

Thanks Mike.

**Comment by mikejolley** [comment]
👍 Just note nesting for attributes is not officially supported.
