### ISSUE TITLE
Sorry, you cannot list resources

### ISSUE THREAD

**Issue by Nitesh9827** [woocommerce/woocommerce#16505]
Hello Support,

We are a third party app and trying to access WooCommerce store through API credentials but getting an unexpected error.

{
    "code": "woocommerce_rest_cannot_view",
    "message": "Sorry, you cannot list resources.",
    "data": {
        "status": 401
    }
}

version of store API is 3.1.1 
can you please suggest what is going wrong with this one. 

Thanks

**Comment by claudiosanches** [comment]
Please before starting an issue you need to fill the issue template.

On the template you can find a lot of good informations, like:

> Hi there! This form is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. If you need technical support from a human being, please submit a ticket via the helpdesk instead: https://woocommerce.com/contact-us/

It's missing a lot of steps to reproduce the issue and not sounds like an issue with WooCommerce... Sounds like that the authentication is not properly set up.

You can find instruction of how work with authentication on https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication

**Comment by potenzatk** [comment]
Hello

http://prntscr.com/nf8iyu
http://prntscr.com/nf8kij
http://prntscr.com/nf8krw

After updating woocommerce new version 3.6.1 API, not working.
wp-json/wc/v2/products
wp-json/wc/v2/products/85/variations 

wp-json/wc/v3/products
wp-json/wc/v3/products/85/variations 

Please fix the API issue and reply to me soon.

Thanks and regards
Tushar Katariya
