### ISSUE TITLE
Saved "Addresses" not immediately available at Checkout

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce#16500]
When updating a current address or saving a new address in the "Addresses" section of the "My Account" page, those updated addresses aren't immediately available on the checkout page.

![Addresses tab](http://cld.wthms.co/TETgru+)
Direct Link: http://cld.wthms.co/TETgru 

I know that the last used address is saved in the user's session data, but is there any way we can make saving a new address or updating an existing address clear that information up?

**Comment by mikejolley** [comment]
Hey @zwiesman31 We have a fix for this in master - it will be part of 3.2! :)
