### ISSUE TITLE
To Implement: Split States/countries to billing and/or shipping

### ISSUE THREAD

**Issue by carmenates09** [woocommerce/woocommerce#16503]
On the checkout page, it would be nice to have two **_wc_country_select_params_** js variables, one for billing and one for shipping.

At the moment I am trying in the shipping that only you can select the states, shipping_state, to which the shipping is done and that they are in Zone Shipping.

I know that this variable I can modify using the "**_woocommerce_states_**" hook but if in this I make some modification also it modified the billing (country / state).

At the moment I have no idea how to solve this problem technically that is why I have them to keep in mind in future versions, I have reviewed all the files of woocommerce associated with my problem and I do not see how to be able to make said change without being Affect both shipping and billing.

Jose Carlos Ramos Carmenates
A hug.

**Comment by claudiulodro** [comment]
I'm not 100% sure exactly what you are trying to do. Would the [woocommerce_checkout_fields filter](https://github.com/woocommerce/woocommerce/blob/0a5cbae50648e48b8ad90bff7f56a102c53c6cea/includes/class-wc-checkout.php#L225) work for you? It lets you modify the shipping and billing address fields separately.

**Comment by mikejolley** [comment]
Splitting wc_country_select_params doesn't sound like a good solution. That filter does not control the displayed states anyway, `woocommerce_states` is on the PHP side and is used globally by more than just this form.

I don't have a good solution; you could look at adding a custom state field using the filter Claudiu mentioned. Or I guess you could filter the list with javascript if needed. This doesn't seem like a common enough problem to tackle in core itself, but you could log on ideas.woocommerce.com if you wanted anyhow.

Thanks

**Comment by carmenates09** [comment]
The problems is change the countries and states, predefined by woocommerce. For example if I want limit shipping to Spain (as country) and set only, limited, to Malaga (as province/state) on the select I can't do that because the woocommerce show all provinces/states on both shipping and billing.

It is getting from wc_country_select_params js var, and it is used on shipping and billing, and it is bad because I need to do that limited but only on shipping.

Why close the issue as new feature? I sure with you @mikejolley the solutions is not duplicate, it was a bad Idea but it can be a solution. I trust on the community to search a best solution, but it's a real problem.

**Comment by carmenates09** [comment]
I tried create a custom field:

```
            <?php woocommerce_form_field('shipping_state', array(
                'label' => __('State', 'woocommerce'),
                'autocomplete' => false,
                'type' => 'select',
                'options' => array(
	                'ma' => __('Málaga', 'woocommerce' )),
                'required' => true,
                'default' =>  'MA',
                'priority' => 80,
                'class' => array('form-row-wide'),
                'input_class' => array('form-control', 'input-lg'),
                'clear' => true,
                'validate' => array(''),
                'country_field' => 'shipping_'
            ), $checkout->get_value('shipping_state')); ?>
```

But woocomerce js are overwrite always, I tested set type as text, select and nothing, it overwrite and put your default select.

Thanks Thanks.

**Comment by mikejolley** [comment]
It would need a unique name so it’s not treated like regular state field. 

Even if states are selectable, zone logic will only ship where allowed?

We don’t tend to leave feature requests on here unless we plan to work on it short term. That’s why there is an idea board to gauge demand.

**Comment by carmenates09** [comment]
To me it seems that woocommerce should leave the possibility of restricting the state / province selectable list in the shippinng.

Since now any limitation made in state / province is affected in the billing and shipping.

The idea is that you can modify from the backend the list of states / provinces and country and that this is different in both billing and shipping.

For example, suppose I only want to sell my products in the USA, as a country, and in Florida, as a state. It is not convenient that in the shipping is allowed to select the customer another state within the USA, only must appear florida. But of course this in the billing the client can say that he is, for example, the USA, New York.

I do not think it's a good idea I create another field in the shipping because at the end woocommerce in validation will throw me an error saying that shipping is not made to the selected state, so why not limit it from the beginning?

I totally agree with what you tell me, and I did not know where to put my recommendation, that right now for me is a big problem because I will have to invent with javascript to give said solution, when this is something from the backend I could measure a hook `woocommerce_shipping_states` I can make my custom changes.

Thank you very much for your time.

**Comment by mikejolley** [comment]
If you can find a non-breaking way to do it via the hooks you could send a PR?
