### ISSUE TITLE
[Import] CSV product import creates duplicated meta_key instead of updating the existing one

### ISSUE THREAD

**Issue by aonzzung** [woocommerce/woocommerce#16510]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

I tested with **total_sales** meta
1. Delete all "total_sales" meta from target products to test
2. Now, those products were automatically initialized with "total_sales = 0"
3. Import csv to update "total_sales" of those existing products
[test_updt_totalsales.zip](https://github.com/woocommerce/woocommerce/files/1234157/test_updt_totalsales.zip)

4. A new meta key was created instead of updating the existing one. The number of them equals to the number of times we do the import.
![duplicate_meta_key](https://user-images.githubusercontent.com/3109162/29455539-b47b5b12-843b-11e7-8c7b-7151f0d5b3b4.png)
5. Even though the duplication is intended, the usage is still incorrect.
On the shop page, "sort by popularity" uses first value of "total_sales" instead of the latest value. ("0" instead "999999" according to the screenshot above)

## Expected/actual behavior

When I follow those steps, I see...
Duplication meta keys and incorrect usage of it

I was expecting to see...
- No duplication of meta key
- Correct usage of meta key (i.e. sort by popularity)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost
Site URL: http://localhost
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.7 (Win32) PHP/5.5.8
PHP Version: ❌ 5.5.8 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.30.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.15
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: test_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: THB (฿)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
variable (variable-2)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #11913 - /shop/
Cart: #11914 - /cart/
Checkout: #13 - /checkout/
My account: #14 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
`total_sales` is internal and should not be editable. I'll fix the check to prevent it setting.

**Comment by mikejolley** [comment]
Nevermind :) It's already fixed in master. This won't happen from 3.2 onwards.

Thanks
