### ISSUE TITLE
Possibly unintended update_checkout behaviour 

### ISSUE THREAD

**Issue by EmilEriksen** [woocommerce/woocommerce#16518]
On our checkout page we have a fragment that is refreshed during the `update_checkout` action. In order to block interaction we have a function attached to the `update_checkout` event that blocks the elements while the fragments are refreshed. This works but has the unintended consequence that when focus is lost from an address field (the change event is fired) the fragment being blocked is blocked 1 second prematurely and then blocked again when `wc_checkout_form.maybe_update_checkout` is finally called after the timeout [here](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L137). In other words the `update_checkout` event is being triggered without `update_checkout_action()` running under certain circumstances.

This seems to be because of the following. `wc_checkout_form.maybe_input_changed()` and `wc_checkout_form.this.queue_update_checkout()` are both attached to the change event in that order [here](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L43-L44). When input is changed in an address field, focus is lost and thus the change event fired `wc_checkout_form.dirtyInput !== false` meaning `maybe_input_changed()` calls a few functions and eventually `update_checkout` is triggered. Then `wc_checkout_form.update_checkout()` is called and sets a 5 ms timer that calls `wc_checkout_form.update_checkout_action()` only this never happens since `wc_checkout_form.this.queue_update_checkout()` is called after `wc_checkout_form.maybe_input_changed()` but before the timer is up. `wc_checkout_form.maybe_input_changed()` calls `wc_checkout_form.reset_update_checkout_timer()` and thus `wc_checkout_form.update_checkout_action()` isn't called.

Afterwards `wc_checkout_form.this.queue_update_checkout()` sets a timeout of 1 second before `wc_checkout_form.maybe_update_checkout()` is called. This is what caused my fragment to be blocked 1 second "prematurely".

**Comment by mikejolley** [comment]
Nice riddle there :D 

What are the consequences of the above without your custom code in place? I.e. what am I supposed to be fixing here? Might it be easier to submit a PR since you understand what is happening?

**Comment by EmilEriksen** [comment]
Yeah I know, sorry 😅 I realised how complicated it was getting as I was writing it, but it's Friday and I wanted to get it posted. I'll see if I can't simplify it on Monday (or maybe Sunday) - maybe make a step by step of how to reproduce.

Maybe I can figure out a solution and if I can I'll submit a PR but it'll most likely involve changes to `wc_checkout_form.update_checkout()` which is called in quite a lot of places (as well as by the update_checkout event from who knows where) so I'm afraid I might not understand all of the implications.

**Comment by EmilEriksen** [comment]
Okay, I had another look today. First, steps to reproduce:

1. Add an event listener to the `update_checkout` event to see what's going on. E.g. something like:
```js
jQuery( document.body ).on( 'update_checkout', function() { console.log( 'update_checkout' ); } );
```
2. Go to checkout and fill out all the address fields
3. Change the value of an address field and quickly (within the 1s timeout set in `queue_update_checkout()`) click outside the form so that the field loses focus
4. Observe that `update_checkout` is triggered immediately but that the checkout isn't updated until after 1s when `update_checkout` is triggered again

Note: This is one aspect of the `update_checkout` behaviour. I will cover another one later in this comment.

This isn't necessarily a bug - it depends on how you interpret the `update_checkout` event; i.e. should an `update_checkout` event imply that the checkout will be updated or does it just mean that the `update_checkout()` function will be fired. If it's the former which I personally think would make the most sense, it's a bug. If not it would be really helpful for developers to have an event that **only** fires when the checkout is actually updated. This event could simply be triggered in the `update_checkout_action()` function.

Simply switching [these](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L43-L44) two lines seems to fix the issue but I don't know if it has any unintended consequences. It also means that the checkout will be updated immediately after the change event is fired rather than after 1s like it is now. I could try to explain why this works but I'm afraid it wouldn't be any easier to understand than the riddle I posted in my OP (and it is fairly easy to understand if you figure out that riddle first). This also doesn't seem like the cleanest fix since it still depends on certain things being fired before certain timeouts. I would like to emphasize that this is also the state of things now - `maybe_input_changed()`, `queue_update_checkout()` and `update_checkout()` sort of have internal battles setting and clearing eachother's timeouts which is why this issue seems like a riddle to understand.

The other aspect related to this issue I wanted to discuss, is the fact that the checkout is sometimes updated because of "changes" to the address fields even if their values haven't changed. This can be observed by following the steps above but after changing the value of an address field wait 1s for the checkout to update then click outside the form to lose focus from the field. This will cause the checkout to update again. This is because `queue_update_checkout()` is attached to the change event and the keydown event. The keydown event is fired as you type but the change event is only fired when focus is lost. I believe addressing this issue would also fix the other issue.

**Comment by mikejolley** [comment]
Looks like we can fix this with some event tweaks. I'll raise a PR.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16564
