### ISSUE TITLE
Use the proper Yoda Condition in class-wc-autoloader.php in autoload() 

### ISSUE THREAD

**Issue by Umangvaghela** [woocommerce/woocommerce#16515]
Yoda condition is not proper in autoload().

**Comment by mikejolley** [comment]
@Umangvaghela If you're sending PRs, please send related ones together. Also no need to log an issue for each if you're adding a description to the PR :)

**Comment by Umangvaghela** [comment]
@mikejolley 

I am new and I have no idea of direct PR request but in future, I will take care of it 

Can you tell me my solution is sufficient or not?

**Comment by Umangvaghela** [comment]
@mikejolley 

In WooCommerce Plugin many places where Yoda condition is wrong. A couple of places need to use proper Yoda condition.

**Comment by mikejolley** [comment]
@Umangvaghela We're aware - we're fixing them gradually rather than all at once. We have a PR to implement PHPCS https://github.com/woocommerce/woocommerce/pull/15798
