### ISSUE TITLE
Wrong tax display on "Orders>Edit Order" for price and tax values <0

### ISSUE THREAD

**Issue by brezocordero** [woocommerce/woocommerce#16524]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a simple product with price 0.1
2. Set up standard tax rate of value <0
![http://cld.wthms.co/5celeL](http://cld.wthms.co/5celeL+)
Link to image here: http://cld.wthms.co/5celeL.
3. Place an order
The tax is calculated as expected and displayed properly on the front-end
![http://cld.wthms.co/M9tWEU](http://cld.wthms.co/M9tWEU+)
Link to image here: http://cld.wthms.co/M9tWEU.
4. Open the order on WooCommerce > Orders

## Expected/actual behavior

When I follow those steps, I see...
![http://cld.wthms.co/4FqTJn](http://cld.wthms.co/4FqTJn+)
Link to image here: http://cld.wthms.co/4FqTJn.
Incorrect tax values at line level. (It is correct at order level)
I was expecting to see...
Correct values

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: 
Site URL:
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.22
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.54.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Akismet Anti-Spam: by Automattic – 3.3.4
Jetpack by WordPress.com: by Automattic – 5.2.1
VaultPress: by Automattic – 1.9.2
WooCommerce Services: by Automattic – 1.6.2
WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

Reported in 638915-zd-woothemes
@mikejolley

**Comment by mikejolley** [comment]
There should also be no tax on a 0.01p product.

**Comment by mikejolley** [comment]
Ok, pretty sure it's the commas used in the tax rate field due to number input.

**Comment by mikejolley** [comment]
Can you try and reply to https://github.com/woocommerce/woocommerce/pull/16548? I think that should prevent it; the rates will need saving.

I think the browser enforces `,`, even though we want `.` and need to match the store locale settings.

Thanks

**Comment by brezocordero** [comment]
Replied, Thank you!
