### ISSUE TITLE
Variation product titles missing attributes  [Order/Cart/Checkout]

### ISSUE THREAD

**Issue by ShopLancaster** [woocommerce/woocommerce#16521]
We are also facing this issue mentioned here:
[15225](https://github.com/woocommerce/woocommerce/issues/15225)
[15555](https://github.com/woocommerce/woocommerce/issues/15555)

We have a couple products that are still using the old formatting with variations listed below the product title. What's odd is that it only affects a certain few products. All the rest display using the new variation in title formatting.

We have tried duplicating the product and it still faces the same issue. We have also created the product from scratch using all new SKUs and IDs with no luck. When comparing items in the database all meta data is exactly the same. Until there is a fix, how would you suggest we resolve this issue? 

<img width="292" alt="correct" src="https://user-images.githubusercontent.com/10392998/29421924-9133df64-8344-11e7-8ee4-b2fd937afb72.png">
<img width="258" alt="incorrect" src="https://user-images.githubusercontent.com/10392998/29421925-913bbcfc-8344-11e7-9d3d-54ab7e4a6962.png">
<img width="627" alt="screen shot 2017-08-17 at 12 56 21 pm" src="https://user-images.githubusercontent.com/10392998/29423914-94339a2c-834b-11e7-9db7-5faf60c7beea.png">

Thank you!

``
### WordPress Environment ###

Home URL: https://www.howmuchyabench.net
Site URL: https://www.howmuchyabench.net
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 7.0.22-0ubuntu0.16.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1500
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

WooCommerce Blacklister: by Aelia – 0.9.7.170517
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.45
Contact Form 7: by Takayuki Miyoshi – 4.8.1
Elfsight Yottie: by Elfsight – 2.4.1
Groups: by itthinx – 2.3.0
MailChimp Forms by MailMunch: by MailMunch – 3.0.5
Post Types Order: by Nsp Code – 1.9.3.3
Sticky Menu (or Anything!) on Scroll: by Mark Senff – 2.0.1
Aelia Foundation Classes for WooCommerce: by Aelia – 1.8.9.170629
WooCommerce Product Subtitle: by Varun Sridharan – 2.3
WooCommerce Extended Coupon Features PRO: by Soft79 – 2.5.3
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.2.7 – 1.2.8 is available
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.1.5
WooCommerce Stripe Gateway: by WooCommerce – 3.2.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.0.4
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout Fernhout – 2.1.12
WooCommerce Role Based Methods: by WPBackOffice – 2.0.8 – 2.1.4 is available
WooCommerce Shipment Tracking: by WooCommerce – 1.6.8
WooCommerce UPS Shipping: by WooCommerce – 3.2.4
WooCommerce USPS Shipping: by WooCommerce – 4.4.8
WooCommerce Warranty Requests: by WooCommerce – 1.8.7
WooCommerce: by Automattic – 3.1.1 – 3.1.2 is available
Yoast SEO: by Team Yoast – 5.2
YITH Live Chat Premium: by YITHEMES – 1.2.2
YITH WooCommerce Email Templates Premium: by YITHEMES – 1.3.2
YITH WooCommerce Gift Cards Premium: by YITHEMES – 1.6.9

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #15 - /shop/
Cart: #16 - /cart/
Checkout: #17 - /checkout/
My account: #18 - /my-account/

### Theme ###

Name: HMYB Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: HMYB 2017
Parent Theme Version: 3.3.7
Parent Theme Author URL: http://www.switchitupdesigns.com/
WooCommerce Support: ✔

### Templates ###

Overrides: hmyb2017/woocommerce/archive-product.php
hmyb2017/woocommerce/cart/cart-empty.php
hmyb2017/woocommerce/cart/cart.php
hmyb2017/woocommerce/checkout/form-checkout.php
hmyb2017/woocommerce/checkout/form-coupon.php
hmyb2017/woocommerce/checkout/thankyou.php
hmyb-child/woocommerce/content-product.php
hmyb2017/woocommerce/content-product_cat.php
hmyb2017/woocommerce/content-single-product.php
hmyb2017/woocommerce/global/breadcrumb.php
hmyb2017/woocommerce/global/quantity-input.php
hmyb2017/woocommerce/global/wrapper-end.php
hmyb2017/woocommerce/global/wrapper-start.php
hmyb2017/woocommerce/loop/loop-end.php
hmyb2017/woocommerce/loop/loop-start.php
hmyb2017/woocommerce/loop/orderby.php
hmyb2017/woocommerce/loop/pagination.php
hmyb2017/woocommerce/loop/result-count.php
hmyb2017/woocommerce/loop/sale-flash.php
hmyb2017/woocommerce/myaccount/form-login.php
hmyb2017/woocommerce/myaccount/navigation.php
hmyb2017/woocommerce/notices/error.php
hmyb2017/woocommerce/notices/notice.php
hmyb2017/woocommerce/notices/success.php
hmyb2017/product-searchform.php version - is out of date. The core version is 2.5.0
hmyb2017/woocommerce/single-product/photoswipe.php
hmyb2017/woocommerce/single-product/price.php
hmyb2017/woocommerce/single-product/product-image.php
hmyb2017/woocommerce/single-product/product-thumbnails.php
hmyb2017/woocommerce/single-product/related.php
hmyb2017/woocommerce/single-product/review.php
hmyb2017/woocommerce/single-product/sale-flash.php
hmyb2017/woocommerce/single-product/share.php
hmyb2017/woocommerce/single-product/short-description.php
hmyb2017/woocommerce/single-product/tabs/tabs.php
hmyb2017/woocommerce/single-product/title.php
hmyb2017/woocommerce/single-product/up-sells.php
hmyb2017/woocommerce/single-product-reviews.php
hmyb2017/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
``

**Comment by mikejolley** [comment]
The new formatting doesn't shown in some cases depending on the number of attributes. If there are too many, showing all in the title becomes unwieldy. 

2 attributes is the limit it seems.

Force it on with this code in theme functions.php:

```
add_filter( 'woocommerce_product_variation_title_include_attributes', '__return_true' );
```

Thanks

**Comment by ShopLancaster** [comment]
Beautiful! Thanks Mike

**Comment by boka003** [comment]
Hi,
@mikejolley 

Is there any option that i can force funcions.php to use old format ?
Old format is way better for me.

Thank You
