### ISSUE TITLE
Prices are not changing when a product is added in wooecommerce.

### ISSUE THREAD

**Issue by Alfred8707** [woocommerce/woocommerce#16531]
When I try to add a product the correct price is not reflected.
https://www.screencast.com/t/7I9uIxfHx8r
I tried a total purge of caches already with the same result. I tried adding another product with the same price and receive the same result. The price should not be 20.55 but 21.99 as reflected on the product details.

## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

[Bug with Prices Hydrahaircare.docx](https://github.com/woocommerce/woocommerce/files/1236015/Bug.with.Prices.Hydrahaircare.docx)
(URl:http://www.hydrahaircare.com/product/curlformer/)
When I try to add a product the correct price is not reflected.
https://www.screencast.com/t/7I9uIxfHx8r
I tried a total purge of caches already with the same result. I tried adding another product with the same price and receive the same result. The price should not be 20.55 but 21.99 as reflected on the product details.

## Expected/actual behavior

When I follow those steps, I see the price I set on the dashboard and on the webpage.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
The price will be displayed based on estimated taxes if your prices are defined 'including tax'. Thats in tax settings.

If you still want to use this setting, set the default customer location (again in settings) to "store base location" instead of using geolocation.

WC > Settings > Tax
