### ISSUE TITLE
Cannot "Copy File To Theme" in Active Child Theme 

### ISSUE THREAD

**Issue by tpjay** [woocommerce/woocommerce#16539]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.Go to Woocommerce>Settings>Email (tab)>Vendor Registration> Copy File to Theme
2.Try to edit the theme file in Vendor Registration page and it "Could not write to template file."
3.Visit the template editor. (Appearance>Editor> Storefront Child Theme) No Vendor Registration email template there to edit.

## Expected/actual behavior

When I follow those steps, I see...
"Could not write to template file." or No template file in Appearance>Editor>Storefront Child Theme
I was expecting to see...
**woocommerce-product-vendors/templates/emails/vendor-registration-email-to-vendor.php** file in Editor>Storefront Child Theme

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://notseenonamazon.com
Site URL: https://notseenonamazon.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.22
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.54.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_134052781_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

VaultPress: by Automattic – 1.9.2
Akismet Anti-Spam: by Automattic – 3.3.4
AMP: by Automattic – 0.5.1
Child Theme Configurator: by Lilaea Media – 2.2.8.1
GeoIP Detection: by Yellow Tree (Benjamin Pick) – 2.7.0
Homepage Control: by WooThemes – 2.0.2
Jetpack by WordPress.com: by Automattic – 5.2.1
Storefront Powerpack: by WooCommerce – 1.4.1
Storefront Product Sharing: by WooThemes – 1.0.4
WooCommerce Cart Tab: by jameskoster – 1.1.1
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.4
WooCommerce Stripe Gateway: by WooCommerce – 3.2.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce Product Vendors: by WooCommerce – 2.0.38 – 2.0.39 is available
WooCommerce Services: by Automattic – 1.7.0
WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #23 - /shop/
Cart: #24 - /cart/
Checkout: #25 - /checkout/
My account: #26 - /my-seller-account/

### Theme ###

Name: Storefront Child Theme
Version: 1.0.0
Author URL: http://stuartduff.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.4
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off
`
</details>

**Comment by mikejolley** [comment]
Using child theme or a parent theme, and with vendors or core emails, this is copying correctly my side.

Sounds like a file permission issue. I'll improve the checks in core.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16546
