### ISSUE TITLE
Shipping form template - brackets misplaced

### ISSUE THREAD

**Issue by programmierstube** [woocommerce/woocommerce#16538]
The form-shipping.php contains misplaced brackets, so that it is currently not possible to hide the additional information fields.

https://github.com/woocommerce/woocommerce/blob/56b8829f46e1d68ec7d64f339c94755525f264b8/templates/checkout/form-shipping.php#L59

Correct way:
`
	<?php if ( apply_filters( 'woocommerce_enable_order_notes_field', 'yes' ) === get_option( 'woocommerce_enable_order_comments', 'yes' ) ) : ?>
`

**Comment by claudiulodro** [comment]
No; it's correct. For this example, let's assume the 'woocommerce_enable_order_comments' option is 'yes'. Let's break it down by steps:

1. `if ( apply_filters( 'woocommerce_enable_order_notes_field', 'yes' === get_option( 'woocommerce_enable_order_comments', 'yes' ) ) )`

2. `if ( apply_filters( 'woocommerce_enable_order_notes_field', 'yes' === 'yes' ) )`

3. `if ( apply_filters( 'woocommerce_enable_order_notes_field', true ) )`

**Comment by programmierstube** [comment]
Oh ok, yes that's right. I was assuming somehow the woocommerce_enable_order_notes_field filter is supposed to return 'yes' or 'no' instead of true / false.
Thank you!
