### ISSUE TITLE
Mobile Select2 Issue on State/Country Dropdown

### ISSUE THREAD

**Issue by digisavvy** [woocommerce/woocommerce#16535]
Hey folks,
It seems like there's an issue on mobile (iOS) devices with the select2 menu. 

The issue
On iOS it's difficult to pick state or country. The text of the dropdown overlaps the text below without a background making it hard to read.

Reproduce

Possible fix
I noted the compiled css here: https://github.com/woocommerce/woocommerce/blob/master/assets/css/select2.css - If you search for `results__options`, the second result will show overflow-y is missing a semi-colon. Correcting that seems to help a little.

## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to a woocommerce shop
2. Add product to cart
3. Go to cart and click checkout
4. Try to select a state or country. Better to try to select different countries or states.

## Expected/actual behavior

I would expect that there would be no jumping around and that when you expand the state and country dropdowns that it is clear what state/country you are selecting.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiulodro** [comment]
<img width="236" alt="screen shot 2017-08-22 at 2 17 18 pm" src="https://user-images.githubusercontent.com/7317227/29588002-b5d75d56-8744-11e7-86a0-2de9b42e5a6b.png">

Looks and works fine as far as I can tell. Can I get a screenshot and/or link and/or the system status report where this happens? 

> Possible fix
I noted the compiled css here: https://github.com/woocommerce/woocommerce/blob/master/assets/css/select2.css - If you search for results__options, the second result will show overflow-y is missing a semi-colon. Correcting that seems to help a little.

> `[...].select2-results__options{max-height:200px;overflow-y:auto}`

This is valid CSS. It's a minified form of [this SCSS](https://github.com/woocommerce/woocommerce/blob/master/assets/css/select2.scss#L258-L260). [Semicolons are only required **in-between** CSS declarations](https://www.w3.org/TR/CSS2/syndata.html#declaration). Adding a semicolon at the end does nothing.

**Comment by mikejolley** [comment]
Same here; let us know if you can provide more details or narrow it down to a theme/plugin.

Closing as this is not reproducible and the bug report isn't a bug, it's valid minified CSS.
