### ISSUE TITLE
Free shipping is not available when using min_amount

### ISSUE THREAD

**Issue by mihaigrigori** [woocommerce/woocommerce#16547]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Enable free shipping and set min_amount required to 100
2. Add one or more products to the cart so their total cost is over 100
3. Go to the cart. 

## Expected/actual behavior

When I follow those steps, I see... Free shipping is not available

I was expecting to see... Free shipping available as min_amount requirement was met

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

In `\WC_Shipping_Free_Shipping::is_available` there is a line that references a property that was removed from the `WC_Cart` class

`if ( in_array( $this->requires, array( 'min_amount', 'either', 'both' ) ) && isset( WC()->cart->cart_contents_total ) ) {` (line 162)

This is the likely cause of the problem since it will always be false and `$has_met_min_amount` will always be `false`

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16549

Thanks
