### ISSUE TITLE
REST - Creating a refund causes a 500 internal server error.

### ISSUE THREAD

**Issue by larssn** [woocommerce/woocommerce#16545]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Made an order via rest.
2. Verified that the order was there: `GET wp-json/wc/v2/orders/393` (it was)
3. Tried to refund the whole amount of that order: `POST wp-json/wc/v2/orders/393/refunds` with the body `{ "amount": "92" }`

## Expected/actual behavior

When I follow those steps, I see...
Server returns a 500. Checked the wordpress debug log and the php error log. No error there.

I was expecting to see...
A 200 OK.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: da_DK

### Server Environment ###

Server Info: nginx/1.12.0
PHP Version: 7.0.19-1+deb.sury.org~xenial+2
PHP Post Max Size: 130 MB
PHP Time Limit: 240
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Din server har ikke SoapClient klasse aktiveret - nogle gateway plugins
der bruger SOAP
virker muligvis ikke som forventet.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: nuvo_14_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: af Automattic – 3.1.2
ap.koponen – 1.0.1

Jetpack af WordPress.com: af Automattic – 5.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop basisside: #3 - /butik/
Kurv: #4 - /kurv/
Checkout: #5 - /kasse/
Min konto: #6 - /min-konto/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – Hvis du redigerer WooCommerce i et hoved-tema
som du ikke selv har udviklet
anbefaler vi at du anvender et undertema (child theme). Se: Hvordan du opretter et undertema

WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by larssn** [comment]
Ok, so I've already isolated the problem.
The only payment gateway we have activated is the "Cash on delivery" one (and a few custom ones, normally).

When we set the body to:
```
{
"amount": "92"
"api_refund": false
}
```

The refund goes through. I'll keep this open for visibility for now.

**Comment by mikejolley** [comment]
👍 I checked the code, and 500 is triggered if you try to do a refund on a gateway which does not support it. This includes manual gateways.

cc @claudiosanches
