### ISSUE TITLE
Product CSV Importer does not set the given product ID from csv

### ISSUE THREAD

**Issue by foxarell** [woocommerce/woocommerce#16552]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install Wordpress v4.8.1
2. Install WC v3.1.2
3. Install Storefront 2.2.4
3. Import the provided dummy-data.csv from docs.woocommerce.com with the _Product CSV Importer and Exporter_

## Expected/actual behavior

When I follow those steps, I see a wrong imported product id.
The product ID in woocommerce after importing from the given csv table is not the same like the one in the csv table.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://localhost/timomuetze.com
Site URL: https://localhost/timomuetze.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/5.6.30 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version: 5.6.30
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ Die MaxMind GeoIP Datenbank existiert nicht - Die Ortung (Geolokalisierung) wird nicht funktionieren. Du kannst sie manuell installieren von http://dev.maxmind.com/geoip/legacy/geolite/ zu dem Pfad: . Scrolle einfach nach unten bis zu "Downloads" und lade die Datei "Binary / gzip" vom Typ "GeoLite Country" herunter. Denke bitte daran
die Datei GeoIP.dat.gz zu entpacken und nur die entpackte Datei GeoIP.dat hochzuladen.


### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce PayPal Express Checkout Gateway: von WooCommerce – 1.4.3
WooCommerce: von Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop-Basis: #5 - /?page_id=5
Warenkorb: #6 - /?page_id=6
Kasse: #7 - /?page_id=7
Mein Konto: #8 - /?page_id=8

### Theme ###

Name: Storefront
Version: 2.2.4 – 2.2.5 ist verfügbar
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
"Product CSV Importer and Exporter" is an extension. The CSV from that plugin will not be compatible. See the /dummy-data/ directory in WooCommerce for a working example CSV.

Also, after import, a new ID is given. IDs are auto-incrementing, so it's not always possible to hardcode it to one you provide.

**Comment by foxarell** [comment]
Sorry, but maybe we are at cross-purposes?
I'm using the csv importer in WC3.1 and not a plugin. So the table should be compatible, because it is the working example provided by WC.
Anyway, so it is not possible to import product ID's with the WC 3.1 Product CSV Importer and Exporter?

I apologies for any inconvenience caused.
Cheers

**Comment by mikejolley** [comment]
I think the CSV you’re using is not designed for the new importer. Look at the dummy data one I said about.

And no, product IDs are not imported.

**Comment by lkol** [comment]
So the UI suggests the user to choose a mapping for the IDs, but then mapping is silently ignored? Pretty misleading I must say. In that case the mapping should be either hidden from the UI or preferably fixing the import to preserve IDs.

![mapping](https://user-images.githubusercontent.com/1440574/42691844-45c58fba-86b2-11e8-863c-5fb53a4eff9b.png)

**Comment by claudiosanches** [comment]
@lkol if it's not the same ID from WordPress database, will try update wrong objects, like posts or pages.

**Comment by claudiosanches** [comment]
@lkol no still does not understand, IDs are shared with posts, pages, orders and so on, so it's not possible.

> Maintaining product IDs helps linking other entities, such as orders.

Just use SKUs instead, with SKUs there is no mistake.

**Comment by tnchuntic** [comment]
@claudiosanches as what @lkol said that will just say we have empty DB and I have to totally migrate the products and orders which is IMPORTANTLY needing to preserved the Product ID to mapped-out with the Orders and products. 

How do I keep the ID as what is in the CSV instead of using a new ID. Is this possible? If not why would it be theres an option in the import section to choose which field will be assign for the ID? I think it should be removed if its not usable.

**Comment by evele** [comment]
@lkol 09/2020 and still not working. Still with the ID option that didnt work..

**Comment by dougtracey** [comment]
Just to give this another push as I agree with what @lkol  has said, the import tool is very misleading as suggests that you will import all mapped product IDs as per the preview data). 

I'm finding the same issue when I try to import an existing website which has about 160 variable products (800+ variations) and all historical orders (over 9,000 orders - yes the DB is over 5GB!!) into a new WooCommerce build. The IDs are completely different when I import so none of the previous orders link to products that exist. Is there no way around this or a plugin I can use that will force import the original Product IDs? Could I maybe do it in PHPMyadmin, but which tables would I need to import/export?

**Comment by umershaikh** [comment]
Hi,
How can i get product ids after import done, is there any action ?
Kindly suggest..

**Comment by tkuisma** [comment]
Hmm, I wonder why this issue is Closed, since this problem still exists, even with the newest WooCommerce 6.7 version.

I.e. the mapped ID won't be assigned as the Product ID, but WooCommerce creates a new ID (i.e. Post ID) for each imported product. The ID import doesn't work even when the ID values DO NOT conflict with current WordPress post ID's.

Has anyone been able to import product ID's to WooCommerce?

If WordPress doesn't allow importing of Post ID's (which the products actually are), then WooCommerce import should NOT even show this ID field as importable.

**Comment by dougtracey** [comment]
I've just had the exact same problem as above, but now with importing orders as they haven't connected to the specific products and are just greyed out! I wish there was a way to override product IDs. I've even tried importing using PHPMyAdmin

**Comment by lolbat** [comment]
I am also having the same issue. I don't know if the Woocommerce team is aware of it but some e-commerce apps cross-link things like descriptions, images, tags, categories and other items from different tables keyed to the product id. So if Woocommerce doesn't add the product ID from my .csv import then I can't finish importing the rest of my data.

Which makes Woocommerce totally unusable.
