### ISSUE TITLE
Fatal Error!

### ISSUE THREAD

**Issue by djakuza** [woocommerce/woocommerce#16551]
After I implementet this code to the class-wc-countries.php i got a Fatal Error and after reuploading the original file it's still there. HELP :S

Fatal error: Uncaught Error: Call to undefined function wc_gzd_get_hook_priority() in /homepages/10/d622659253/htdocs/clickandbuilds/GentleZeusShop/wp-content/themes/shopkeeper/functions.php:1071 Stack trace: #0 /homepages/10/d622659253/htdocs/clickandbuilds/GentleZeusShop/wp-content/themes/shopkeeper/functions.php(1096): germanized_compatibility() #1 /homepages/10/d622659253/htdocs/clickandbuilds/GentleZeusShop/wp-settings.php(424): include('/homepages/10/d...') #2 /homepages/10/d622659253/htdocs/clickandbuilds/GentleZeusShop/wp-config.php(80): require_once('/homepages/10/d...') #3 /homepages/10/d622659253/htdocs/clickandbuilds/GentleZeusShop/wp-load.php(37): require_once('/homepages/10/d...') #4 /homepages/10/d622659253/htdocs/clickandbuilds/GentleZeusShop/wp-blog-header.php(13): require_once('/homepages/10/d...') #5 /homepages/10/d622659253/htdocs/clickandbuilds/GentleZeusShop/index.php(17): require('/homepages/10/d...') #6 {main} thrown in /homepages/10/d622659253/htdocs/clickandbuilds/GentleZeusShop/wp-content/themes/shopkeeper/functions.php on line 1071

**Comment by mikejolley** [comment]
`Fatal error: Uncaught Error: Call to undefined function wc_gzd_get_hook_priority()`

wc_gzd_get_hook_priority is not part of WooCommerce.

**Comment by claudiosanches** [comment]
That function comes from `WooCommerce Germanized`.
