### ISSUE TITLE
Product CSV Importer and Exporter - Menu Order missing

### ISSUE THREAD

**Issue by yatgirl** [woocommerce/woocommerce#16554]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Menu Order column does not exist in Product Export CSV
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...
a menu order column in the product export csv

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by yatgirl** [comment]
Menu order column is missing from CSV Importer and Exporter.  I am moving my site from oscommerce to woocommerce and presently in development stage.  I have 17000 products to import, more than 1/2 require the menu order option to sort my products correctly.  This capability was one of the main reasons I chose woocommerce.   Hoping this is just an oversight and would like to have this investigated and hopefully rectified.

**Comment by mikejolley** [comment]
Sorting 17000 products manually sounds unmanageable. `menu_order` itself is not user friendly - it's one thing that is under consideration to remove or move to a separate plugin https://github.com/woocommerce/woocommerce/issues/13072

We can add it for now though.

**Comment by yatgirl** [comment]
Thanks - for now I have added it to the product exporter importer with the custom menu code so I can use it.  Respectfully, the option is quite hidden, I dont see the need to remove it.  It is definitely an useful option that store owners can use, or easily ignore if they dont want it.  It is very useful and crucial for my store as I need to set a large group of products to the end of each of my 100 categories - not having that option would be make things very messy in my store. Thanks for everything !
