### ISSUE TITLE
500 error on payment link for deleted orders

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce#16555]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an order or use an existing "Pending Payment" order
2. Send the customer an invoice to pay the order
3. If the order is then permanently deleted (not left in trash) you get a 500 server error

## Expected/actual behavior

When I follow those steps, I see...

500 server error

I was expecting to see...

A more user-friendly error that the order is no longer available (similar to when the order is in the trash).

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

WordPress - Version 4.8.1
WooCommerce - Version 3.1.2

**Comment by FreshPhil** [comment]
636139-zd-woothemes

**Comment by mikejolley** [comment]
> The issue still exists against the latest master branch of WooCommerce on Github

Not sure if you did this or not, but I can say it is fixed in master. Improving the pay page was something done for 3.2.

Thanks
