### ISSUE TITLE
Incorect data when adding my own add_to_cart_handler

### ISSUE THREAD

**Issue by griffj** [woocommerce/woocommerce#16567]
I see that the custom woocommerce_add_to_cart_handler_ is called with:
do_action( 'woocommerce_add_to_cart_handler_' . $add_to_cart_handler, $url );

in includes/class-wc-form-handler.php, line 742 (in master branch)

Surely this should be:
do_action( 'woocommerce_add_to_cart_handler_' . $add_to_cart_handler, $product_id );

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

used the following snipet:
function add_to_cart_handler( $type, $add_to_cart ) {

        $type = "my_add_to_cart";
        return $type;
}

function my_add_to_cart ($url ) {
        error_log("XXXX url=>$url");
}

add_filter( 'woocommerce_add_to_cart_handler', 'add_to_cart_handler', 10, 2);
add_action( 'woocommerce_add_to_cart_handler_my_add_to_cart', 'my_add_to_cart', 10, 1 );

## Expected/actual behavior

When I follow those steps, I see...
No value passed in the $url variable:
[22-Aug-2017 14:40:50 UTC] XXXX url=>
I was expecting to see...
the product id.  If I change the line from $url to $product_id (line 742), I get:
[22-Aug-2017 14:40:05 UTC] XXXX url=>46933

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://tkouat.totalknockout.co.uk
Site URL: http://tkouat.totalknockout.co.uk/tko
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.53.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: tko_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (8) ###

Elegant Builder: by Elegant Themes – 2.3
ET Shortcodes: by Elegant Themes – 1.2
HTML5 Responsive FAQ: by Aman Verma – 2.5.3
OptionTree: by Derek Herman – 2.6.0
Popup by Supsystic: by supsystic.com – 1.9.6
My Test: by Julian Griffiths – 0.1
WooCommerce: by Automattic – 3.1.2
JackBox: by CodingJack – 1.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: configurable (configurable)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page does not contain the shortcode.
Checkout: #34560 - /checkout-2/
My account: #34561 - /my-account-2/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by mikejolley** [comment]
You can get the product ID from POST/GET like the other endpoints. This won't be changed as it will break backwards compatibility.

Thanks
