### ISSUE TITLE
Regular price can be small than sale price

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#16560]
Steps:

1. Set the Regular price to 100
2. Set the Sale price to 99 (which will valid)
3. Again lets change the Regular price to 10 (IMO this should throw the error tip)

Changed regular price is saved and displayed perfectly.
@claudiosanches @mikejolley Is this intentional or not?

**Comment by mikejolley** [comment]
The error tip is on the sale price field, not the regular price field, as of now.

**Comment by shivapoudel** [comment]
Can sale price be greater than regular price. I know that there is no error tip for regular price but I mean to say saving greater sale price is acceptable in this scenerio or not :)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16563

**Comment by claudiulodro** [comment]
[Clearly you guys have never shopped in American retail stores. ;-)](http://www.nbcnews.com/business/consumer/fake-sales-trick-customers-major-stores-study-says-n366676)

I don't want to encourage that sort of behavior, though, so we should prevent it.
