### ISSUE TITLE
Allow sorting on search results page, but default to relevance

### ISSUE THREAD

**Issue by marijnkortstra** [woocommerce/woocommerce#16565]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Search for a product (domain.tld/?s=existingproduct&post_type=product)

## Expected/actual behavior

When I follow those steps, I don't see the dropdown menu for catalog ordering.

I was expecting to see, the dropdown menu for catalog ordering.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://www.beldev.bellustoys.com
Site URL: http://www.beldev.bellustoys.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.0.13
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.50.3
OpenSSL/1.0.1e

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Jouw winkel gebruikt geen HTTPS. Leer meer over HTTPS en SSL-certificaten.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: door Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Winkelbasis: ❌ De pagina moet als Openbaar zijn ingesteld
Winkelmand: #6 - /cart/
Afrekenen: #7 - /checkout/
Mijn account: #8 - /mijn-account/

### Theme ###

Name: Twenty Fifteen
Version: 1.8
Author URL: https://nl.wordpress.org/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
Search results sort by relevance and this is forced. Because of this, the sorting option is hidden (as it would do nothing if visible).

Thanks

**Comment by marijnkortstra** [comment]
Why is this changed since WooCommerce 3.0? Until version 2.7 of WooCommerce the search result page showed relevant products and you could sort them based on your personal preferences (like price low-high or popularity).

There are plenty scenarios where this feature is desirable. Eg: when you search for a product and there are multiple matches that fit your search query but you want to see the cheapest product. There is no major e-commerce store which doesn't offer this functionality to their customers, and WooCommerce used to offer this it too.

I'm well aware that I have little to no voice in decisions like this, since we don't actively contribute to WooCommerce, but I think many people would be helped if at least there would be an option to toggle catalog ordering for search results.

Would love to hear the thoughts behind this decision, maybe I'm missing/overlooking an obvious reason to hide this feature on the search result page.

**Comment by mikejolley** [comment]
Sorting by relevance was a feature request in itself, and makes a lot of sense as a default.

> I'm well aware that I have little to no voice in decisions like this, since we don't actively contribute to WooCommerce, but I think many people would be helped if at least there would be an option to toggle catalog ordering for search results.

It could be submitted as a pull request if you wanted, or on the ideas board. We'd need to work out how we handle 'defaults' vs search results though, since IMHO search results need to default to relevance ..

**Comment by marijnkortstra** [comment]
I completely agree with you that it should default on relevance. It would be nice however to have the addition of the dropdown menu with different sorting options, so that a user can switch sorting if they need it (eg. for the example scenario I described).

Could you advise me where to post this suggestion (pull request or ideas board)?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16593

**Comment by felixgoldstein** [comment]
If you set your default sorting to popularity, it will show "Relecance" in the dropdown when sorting by popularity

**Comment by Ferguson230** [comment]
> If you set your default sorting to popularity, it will show "Relecance" in the dropdown when sorting by popularity

@felixgoldstein @mikejolley Is it possible to change the default sorting on search results to popularity and not relevance using a hook or in functions.php of my child theme?
