### ISSUE TITLE
Woocommerce product search in admin is not working

### ISSUE THREAD

**Issue by Gowsalayadevi** [woocommerce/woocommerce#16576]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

Hi,
i recently updated the Woo Commerce to the latest version 3.1. After the updating, The product search in the back end is not working. It is showing the number of items matching the term but not listing the products.
![image](https://user-images.githubusercontent.com/23442341/29596073-a6ee04c4-87fe-11e7-943b-e435e8f83b43.png)

Please let me know how to fix this issue.

## Isolating the problem

- [ X] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
I can see from the screenshot this wasn't tested with only WC active, and you've not provided the system status report.

Please follow the instructions and narrow down the cause before logging issues here. This is most likely a plugin conflict since no one else seems affected.

Thanks!

**Comment by lewisryder** [comment]
I've had this exact same issue for a couple months now. Lots of searching, and I can not find much on this. Did you find the problem or a fix?
Thanks,
Lewis

**Comment by Chargin** [comment]
I too have this problem, I do have a lot of plugins. Ive just updated to the latest version of WC as at 7 Feb 2018 and the issue remains.

**Comment by tremblayly** [comment]
Same issue at my end after I just upgraded WC.

**Comment by mikejolley** [comment]
It's known in 3.3. Separate issue. There is a release candidate for 3.3.2 on wordpress.org with the fix if you want it now. You can use WP Rollback plugin to 'roll forward' to this pre-release, or you can wait for the final version.

**Comment by tremblayly** [comment]
Thank you Mike for the quick response. I will wait for the final version until next week and if takes longer, I will download the pre-release version.

**Comment by saqib59** [comment]
Any fix?
