### ISSUE TITLE
bug in api v2 while logged in wordpress

### ISSUE THREAD

**Issue by youasl** [woocommerce/woocommerce#16582]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

While i was using the woocommerce-api and logged in wordpress I couldn't use the api.

Example 1:
https://example.com/ NOT LOGGED IN WORDPRESS
Going to https://example.com/wp-json/wc/v2/products/794?consumer_key=123&consumer_secret=456 results this JSON:

{
  "id": 794,
  "name": "Premium Quality",
  "slug": "premium-quality-19",
  "permalink": "https://example.com/product/premium-quality-19/",
  "date_created": "2017-03-23T17:01:14",
  "date_created_gmt": "2017-03-23T20:01:14",
  "date_modified": "2017-03-23T17:01:14",
  "date_modified_gmt": "2017-03-23T20:01:14",
 ......
}
  
Everything is working as intended.

Example 2:
https://example.com/ LOGGED IN WORDPRESS
Going to https://example.com/wp-json/wc/v2/products/794?consumer_key=123&consumer_secret=456 results this JSON:

{ 
 "code": "woocommerce_rest_cannot_view", "message": "Sorry, you can not list the resources.", "data": { "status": 401 } 
}
  
It's not working as intended when i'm also logged in in wordpress in the same browser.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
-Wordpress 4.8.1
-WooCommerce 3.1.2
```
</details>

**Comment by mikejolley** [comment]
@youasl How is this an issue? The API is not consumed through the browser like that ^

**Comment by youasl** [comment]
Hello @mikejolley I'm not sure if i'm doing it correct though. For example: If there is a web-app where you can manage your products/orders with your api key and secret. The web-app cant work if you are logged in your wordpress environment.

**Comment by claudiosanches** [comment]
Logged in with an admin?
Because maybe the current user permissions is overing the API Keys.

**Comment by mikejolley** [comment]
A web app is fine; the web app is making API calls to the API and isn't logged in.

With that said, I just tried this myself whilst logged in as a customer. The endpoint was not blocked. I suspect a plugin or another auth method is present on your install. I had the error until I used correct keys, and the keys belonging to admin.
