### ISSUE TITLE
Product CSV Importer - Imported images are missing titles

### ISSUE THREAD

**Issue by non-entity9** [woocommerce/woocommerce#16587]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. Import a new product or update an existing one 
2. Include the 'Images' field in CSV
3. View images in Media Library

## Expected/actual behavior
When I import a product or update an existing one, any images imported with it are missing titles in the media library. They all just show as '(no title)'. This happens with both locally and externally hosted images. 

I was expecting to see them titled as the filename.

## Isolating the problem
- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16592
