### ISSUE TITLE
Price is not getting displayed using wooCommerce for simple product

### ISSUE THREAD

**Issue by krishna5895** [woocommerce/woocommerce#16585]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiosanches** [comment]
You not filled all fields of the issue template.
It's missing "Steps to reproduce the issue" and "Expected/actual behavior", and not tried to isolate the problem too.
I just tested and looks good, that's why I'm closing. Thanks for reporting.

**Comment by krishna5895** [comment]
For me price is not displaying
what should I do?
