### ISSUE TITLE
New product:  Attach images to new product

### ISSUE THREAD

**Issue by czarcar** [woocommerce/woocommerce#16589]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  Create a new product
2.  Select image (or upload) image from image gallery.
3.  Update/Publish product
4.  Click All Products
5.  Notice image is not attached to product.
6.  Pre/View product no image displayed.

## Expected/actual behavior

When I follow those steps, I see...
A blank where the image should be.
I was expecting to see...
An image from the image gallery

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

Home URL: |   | http://128.2c7.myftpupload.com
-- | -- | --
Site URL: |   | http://128.2c7.myftpupload.com
WC version: |   | 3.1.2
Log directory writable: |   | /home/content/a2pewpnaspod04_data04/41/41305541/html/wp-content/uploads/wc-logs/
WP version: |   | 4.8.1
WP multisite: |   | –
WP memory limit: |   | 256 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US

Home URL: |   | http://128.2c7.myftpupload.com
-- | -- | --
Site URL: |   | http://128.2c7.myftpupload.com
WC version: |   | 3.1.2
Log directory writable: |   | /home/content/a2pewpnaspod04_data04/41/41305541/html/wp-content/uploads/wc-logs/
WP version: |   | 4.8.1
WP multisite: |   | –
WP memory limit: |   | 256 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US

</details>

All other plugins have been deleted.
Tried changing templates.
Duplicated on "staging" server.

**Comment by mikejolley** [comment]
You need to set the 'featured image' too. We plan on combining gallery and featured image in a future update to make it clearer.

Thanks

**Comment by czarcar** [comment]
Thank you.  "Featured Image" was unchecked by the owner? in display options.  Unfamiliar w/ WP and WC.   Sometimes making everything a setting is not a good idea (K.I.S.S. principle)
