### ISSUE TITLE
“registration” field in Woocommerce checkout does not show

### ISSUE THREAD

**Issue by linuskom** [woocommerce/woocommerce#16588]
There seems to be a bug in WooCommerce!
The problem is “registration” field in Woocommerce checkout does not show.
Tested with different theme, same problem appears.
Deactivated all my plugin one by one and still the same problem.

## Steps to reproduce the issue

[1]. “Checkout”  >> Enable guest checkout     (is unchecked, so it’s not enabled) [X]
[2].  “Accounts” >>  Enable customer registration on the "Checkout" page.   (this is checked, so its enabled) [x]

## Isolating the problem

WordPress environment
--
Home URL: |   | https://healthsmartnutra.com
Site URL: |   | https://healthsmartnutra.com
WC version: |   | 3.1.2
Log directory writable: |   | /home/heal6164/public_html/wp-content/uploads/wc-logs/
WP version: |   | 4.8.1
WP multisite: |   | –
WP memory limit: |   | 768 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US

Server environment
--
Server info: |   | Apache
PHP version: |   | 7.0.22
PHP post max size: |   | 128 MB
PHP time limit: |   | 120
PHP max input vars: |   | 3000

cURL version: |   | 7.53.0, OpenSSL/1.0.2k
-- | -- | --
SUHOSIN installed: |   | –
MySQL version: |   | 5.6.36
Max upload size: |   | 128 MB
Default timezone is UTC: |   |  
fsockopen/cURL: |   |  
SoapClient: |   |  
DOMDocument: |   |  
GZip: |   |  
Multibyte string: |   |  
Remote post: |   |  
Remote get: |   |  

Database
--
WC database version: |   | 3.1.2
Database prefix |   | wplt_
woocommerce_sessions |   |  
woocommerce_api_keys |   |  
woocommerce_attribute_taxonomies |   |  
woocommerce_downloadable_product_permissions |   |  
woocommerce_order_items |   |  
woocommerce_order_itemmeta |   |  
woocommerce_tax_rates |   |  
woocommerce_tax_rate_locations |   |  

woocommerce_shipping_zones |   |  
-- | -- | --
woocommerce_shipping_zone_locations |   |  
woocommerce_shipping_zone_methods |   |  
woocommerce_payment_tokens |   |  
woocommerce_payment_tokenmeta |   |  
MaxMind GeoIP database: |   | The MaxMind GeoIP Database does not exist - Geolocation   will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/   to the path: /home/heal6164/public_html/wp-content/uploads/GeoIP.dat.   Scroll down to "Downloads" and download the "Binary /   gzip" file next to "GeoLite Country". Please remember to   uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

Security
--
Secure connection (HTTPS): |   |  
Hide errors from visitors |   |  

Active plugins (15)
--
ARMember |   | by Repute InfoSystems – 1.8.1
Astra Pro |   | by Brainstorm Force – 1.0.0-beta.11
Astra Hooks |   | by Brainstorm Force – 1.0.0
Beaver Builder Plugin (Pro Version) |   | by The Beaver Builder Team – 1.10.7.1
Ultimate   Addon for Beaver Builder |   | by Brainstorm Force – 1.6.2
dflip |   | by Deepak Ghimire – 1.2.8
Jetpack by   WordPress.com |   | by Automattic – 5.2.1
WooCommerce   Custom Thank You Page |   | by Jelly Pixel Studio – 1.6

MailPoet   3 Premium (new) |   | by MailPoet – 3.0.0-rc.1.0.2
-- | -- | --
MailPoet   3 (new) |   | by MailPoet – 3.0.0-rc.1.0.4
SG Optimizer |   | by SiteGround – 3.3.2
Thrive   Quiz Builder |   | by Thrive Themes –   2.0.1
Woocommerce   Add-to-Cart Custom Redirect |   | by Ren Ventura – 1.2
WooCommerce Stripe Gateway |   | by WooCommerce – 3.2.3
WooCommerce |   | by Automattic – 3.1.2

Settings
--
API enabled: |   |  
Force SSL: |   |  
Currency |   | USD ($)
Currency position |   | left
Thousand separator |   | ,
Decimal separator |   | .
Number of decimals |   | 2
Taxonomies: Product types |   | external (external), grouped (grouped), simple (simple),   variable (variable)
Taxonomies: Product visibility |   | exclude-from-catalog (exclude-from-catalog),   exclude-from-search (exclude-from-search), featured (featured), outofstock   (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3),   rated-4 (rated-4), rated-5 (rated-5)

WC pages
--
Shop   base: |   | #5 - /shop/
Cart: |   | #6 - /cart/

Checkout: |   | #7 - /checkout/
-- | -- | --
My   account: |   | #8 - /my-account/

Theme
--
Name: |   | Astra Child
Version: |   | 1.0.0
Author URL: |   | https://www.brainstormforce.com/
Child theme: |   |  
Parent theme name: |   | Astra
Parent theme version: |   | 1.0.17
Parent theme author URL: |   | http://wpastra.com/about/
WooCommerce support: |   |  

Templates
--
Overrides |   | astra-child-master/woocommerce/checkout/form-checkout.php

form-checkout.php
============
<?php
/**
 * Checkout Form
 *
 * This template can be overridden by copying it to yourtheme/woocommerce/checkout/form-checkout.php.
 *
 * HOWEVER, on occasion WooCommerce will need to update template files and you
 * (the theme developer) will need to copy the new files to your theme to
 * maintain compatibility. We try to do this as little as possible, but it does
 * happen. When this occurs the version of the template file will be bumped and
 * the readme will list any important changes.
 *
 * @see 	    https://docs.woocommerce.com/document/template-structure/
 * @author 		WooThemes
 * @package 	WooCommerce/Templates
 * @version     2.3.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

wc_print_notices();

do_action( 'woocommerce_before_checkout_form', $checkout );

// If checkout registration is disabled and not logged in, the user cannot checkout
if ( ! $checkout->is_registration_enabled() && $checkout->is_registration_required() && ! is_user_logged_in() ) {
	echo apply_filters( 'woocommerce_checkout_must_be_logged_in_message', __( 'You must be logged in to checkout.', 'woocommerce' ) );
	return;
}

?>

<form name="checkout" method="post" class="checkout woocommerce-checkout" action="<?php echo esc_url( wc_get_checkout_url() ); ?>" enctype="multipart/form-data">

	<?php if ( $checkout->get_checkout_fields() ) : ?>

		<?php do_action( 'woocommerce_checkout_before_customer_details' ); ?>

		<div class="col1-set" id="customer_details">
			<div class="col-1">
				<?php do_action( 'woocommerce_checkout_billing' ); ?>
			</div>

			<div class="col-1">
				<?php do_action( 'woocommerce_checkout_shipping' ); ?>
			</div>
		</div>

		<?php do_action( 'woocommerce_checkout_after_customer_details' ); ?>

	<?php endif; ?>

	<h3 id="order_review_heading"><?php _e( 'Your order', 'woocommerce' ); ?></h3>

	<?php do_action( 'woocommerce_checkout_before_order_review' ); ?>

	<div id="order_review" class="woocommerce-checkout-review-order">
		<?php do_action( 'woocommerce_checkout_order_review' ); ?>
	</div>

	<?php do_action( 'woocommerce_checkout_after_order_review' ); ?>

</form>

<?php do_action( 'woocommerce_after_checkout_form', $checkout ); ?>

</details>

**Comment by supernovia** [comment]
On "Account Creation" are you automatically generating a username from the email?

**Comment by linuskom** [comment]
Sure it is enabled, see below;

[image: Inline image 1]

**Comment by mikejolley** [comment]
When you disable guest checkout, no checkbox for registration is needed because it needs to happen. Since you're auto-generating user names too, it will all be automatic. The user will be registered.

**Comment by linuskom** [comment]
Mike,





You "make no sense", you should read the semantic lexicon you use in your
statement.





You chose a convenient path and went ahead to closed the ticket.



Lacking cognition, you wash *your* hands like *Pontius* *Pilate. *



*I just wonder who supervises people like you!*



*I actually found the “issue”. *

*You would have as well if only you had a grain of “investigative courage”
and “intellectual curiosity”.*



*Unfortunately, it’s just so sad for Woocommerce having people like you.
It’s a right recipe to ruin a brand.*



*Neil*



*Sydney*

*AUSTRALIA*

**Comment by mikejolley** [comment]
@linuskom There is no need to make this personal Neil. If you don't understand my reply, ask. There is no need to attack people who try to help.

**Comment by linuskom** [comment]
First you “hastily close the ticket” without discovering where the issue
was, “and let me tell you it was nothing what you discovered” or even the
“slightest” bit of your statement. You have no clue, not even the size of
mustard grain what the problem was!



Your business process is defective. I feel sorry for existing and future
customer of woocommerce who will experience possibly the something as I
did.



I just wonder is this what defines the woocommerce philosophy of
“interactive-help and problem resolution”?



When blatant fact is put in front of you, you act like a petulant baby
showing your sensitivity rather than cognition of the issue.



 Neil

Sydney

AUSTRALIA

**Comment by mikejolley** [comment]
@linuskom 👍
