### ISSUE TITLE
Manual coupons and recalculation

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#16594]
Support coupons which use `woocommerce_coupon_get_discount_amount` and `woocommerce_get_shop_coupon_data` when doing re-calculation in admin. This happens when removing an coupon from an order.

Add filters so the plugin can do it's own recalculation, and fallback to the original coupon details if possible.

This can also allow us to support deleted, no longer existing coupons.

**Comment by bor0** [comment]
Test case:
Mike Jolley [3:55 PM] 
1. Add manual coupon to cart
2. Add regular coupon to cart
3. Place order
4. Remove regular coupon from order
5. Witness all discounts wiped out
