### ISSUE TITLE
multiple new order emails

### ISSUE THREAD

**Issue by bigredpanda** [woocommerce/woocommerce#16595]
Hi, i have woocommerce v 2.5.2 and i have a problem. When new order is created it sends me multiple "NEW ORDER" emails. Will the update to the latest version will solve the problem or is there any fast solution without update?

Thank you.

**Comment by mikejolley** [comment]
Being such an old version it's hard to say. It could even be a plugin conflict? I don't recall such a bug.

2.5.2 is over a year old and no longer receiving patches - maybe setup a staging site and test the latest versions?

Thanks
