### ISSUE TITLE
Shop view product sorting by price

### ISSUE THREAD

**Issue by parkinep** [woocommerce/woocommerce#16591]
In looking into the speed of the sorting of products in the shop view I found that the query can be significantly optimized with noticeable effects especially in large shops, our current shop has 33 000 products at the moment, will increase to 600 000+ in the future.

I found that the price_query derived table does not filter its query based on the active category and thus selects the '_price' product meta field for *every* product in the shop whether relevant or not.

Here below I have provided samples of the queries, first a query sorting a category that has only 22 product, by price. The default query takes 8.5 seconds and has to handle a derived table of 101178 rows. This is the same amount as if sorting the entire shop 33 000+ products as is shown in the next query and its EXPLAIN.

<details>
My optimization, the last query below, modifies the price_query derived table by joining it with another derived table that contains only the object_ids from the term_relationships table for the relevant category/categories: 

(
    SELECT lvup_term_relationships.object_id
    FROM lvup_term_relationships
    WHERE 1=1
    AND lvup_term_relationships.term_taxonomy_id IN (4122)
) as active_prods

This is a quite a serious usability issue as our 600k+ test shop takes 75.62 sec to sort a category of 277 products and 0.10 sec to do it with my optimization.

**SMALL CAT QUERY BY PRICE**

MariaDB [ds_wp]> SELECT SQL_CALC_FOUND_ROWS lvup_posts.ID
    -> FROM lvup_posts
    -> LEFT JOIN lvup_term_relationships
    -> ON (lvup_posts.ID = lvup_term_relationships.object_id)
    -> INNER JOIN (
    -> SELECT post_id, max( meta_value+0 ) price
    -> FROM lvup_postmeta
    -> WHERE meta_key='_price'
    -> GROUP BY post_id ) as price_query
    -> ON lvup_posts.ID = price_query.post_id
    -> WHERE 1=1
    -> AND ( lvup_posts.ID NOT IN (
    -> SELECT object_id
    -> FROM lvup_term_relationships
    -> WHERE term_taxonomy_id IN (48) )
    -> AND lvup_term_relationships.term_taxonomy_id IN (4122) )
    -> AND lvup_posts.post_type = 'product'
    -> AND (lvup_posts.post_status = 'publish'
    -> OR lvup_posts.post_status = 'acf-disabled'
    -> OR lvup_posts.post_status = 'private')
    -> GROUP BY lvup_posts.ID
    -> ORDER BY price_query.price DESC
    -> LIMIT 0, 25;
+--------+
| ID     |
+--------+
| 185954 |
| 185956 |
| 185886 |
| 185894 |
| 185896 |
| 172127 |
| 164905 |
| 164901 |
| 164907 |
| 164913 |
| 164558 |
| 164911 |
| 164909 |
| 159629 |
| 172188 |
| 172201 |
| 164903 |
| 176110 |
| 135650 |
| 159636 |
| 141418 |
| 186722 |
+--------+
22 rows in set (8.50 sec)

*************************** 1. row ***************************
           id: 1
  select_type: PRIMARY
        table: lvup_term_relationships
         type: ref
possible_keys: PRIMARY,term_taxonomy_id
          key: term_taxonomy_id
      key_len: 8
          ref: const
         rows: 22
        Extra: Using where; Using index; Using temporary; Using filesort
*************************** 2. row ***************************
           id: 1
  select_type: PRIMARY
        table: lvup_posts
         type: eq_ref
possible_keys: PRIMARY,type_status_date
          key: PRIMARY
      key_len: 8
          ref: ds_wp.lvup_term_relationships.object_id
         rows: 1
        Extra: Using where
*************************** 3. row ***************************
           id: 1
  select_type: PRIMARY
        table: <derived2>
         type: ref
possible_keys: key0
          key: key0
      key_len: 8
          ref: ds_wp.lvup_term_relationships.object_id
         rows: 10
        Extra:
*************************** 4. row ***************************
           id: 3
  select_type: DEPENDENT SUBQUERY
        table: lvup_term_relationships
         type: unique_subquery
possible_keys: PRIMARY,term_taxonomy_id
          key: PRIMARY
      key_len: 16
          ref: func,const
         rows: 1
        Extra: Using index; Using where; Full scan on NULL key
*************************** 5. row ***************************
           id: 2
  select_type: DERIVED
        table: lvup_postmeta
         type: ref
possible_keys: meta_key
          key: meta_key
      key_len: 767
          ref: const
         rows: 101178
        Extra: Using where; Using temporary; Using filesort

**FULL SHOP QUERY BY PRICE**

MariaDB [ds_wp]> SELECT SQL_CALC_FOUND_ROWS lvup_posts.ID
    -> FROM lvup_posts
    -> INNER JOIN (
    -> SELECT post_id, max( meta_value+0 ) price
    -> FROM lvup_postmeta
    -> WHERE meta_key='_price'
    -> GROUP BY post_id ) as price_query
    -> ON lvup_posts.ID = price_query.post_id
    -> WHERE 1=1
    -> AND ( lvup_posts.ID NOT IN (
    -> SELECT object_id
    -> FROM lvup_term_relationships
    -> WHERE term_taxonomy_id IN (48) ) )
    -> AND lvup_posts.post_type = 'product'
    -> AND (lvup_posts.post_status = 'publish'
    -> OR lvup_posts.post_status = 'acf-disabled'
    -> OR lvup_posts.post_status = 'private')
    -> GROUP BY lvup_posts.ID
    -> ORDER BY price_query.price DESC
    -> LIMIT 0, 25;
+--------+
| ID     |
+--------+
| 377039 |
| 377048 |
| 377227 |
| 377068 |
| 377126 |
| 377040 |
| 377077 |
| 377135 |
| 377217 |
| 377049 |
| 377198 |
| 377069 |
| 377228 |
| 377029 |
| 377078 |
| 377097 |
| 377041 |
| 377218 |
| 377127 |
| 377106 |
| 377070 |
| 377050 |
| 377208 |
| 377108 |
| 377229 |
+--------+
25 rows in set (8.57 sec)

*************************** 1. row ***************************
           id: 1
  select_type: PRIMARY
        table: <derived2>
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 101178
        Extra: Using where; Using temporary; Using filesort
*************************** 2. row ***************************
           id: 1
  select_type: PRIMARY
        table: lvup_posts
         type: eq_ref
possible_keys: PRIMARY,type_status_date
          key: PRIMARY
      key_len: 8
          ref: price_query.post_id
         rows: 1
        Extra: Using where
*************************** 3. row ***************************
           id: 3
  select_type: MATERIALIZED
        table: lvup_term_relationships
         type: ref
possible_keys: PRIMARY,term_taxonomy_id
          key: term_taxonomy_id
      key_len: 8
          ref: const
         rows: 38794
        Extra: Using index
*************************** 4. row ***************************
           id: 2
  select_type: DERIVED
        table: lvup_postmeta
         type: ref
possible_keys: meta_key
          key: meta_key
      key_len: 767
          ref: const
         rows: 101178
        Extra: Using where; Using temporary; Using filesort

**MODIFIED SMALL CAT QUERY BY PRICE**

MariaDB [ds_wp]> SELECT SQL_CALC_FOUND_ROWS lvup_posts.ID
    -> FROM lvup_posts
    -> LEFT JOIN lvup_term_relationships
    -> ON (lvup_posts.ID = lvup_term_relationships.object_id)
    -> INNER JOIN (
    -> SELECT post_id, max( meta_value+0 ) price
    -> FROM lvup_postmeta
    -> INNER JOIN (SELECT lvup_term_relationships.object_id
    -> FROM lvup_term_relationships
    -> WHERE 1=1
    -> AND lvup_term_relationships.term_taxonomy_id IN (4122)
    -> ) as active_prods
    -> ON lvup_postmeta.post_id = active_prods.object_id
    -> WHERE meta_key='_price'
    -> GROUP BY post_id ) as price_query
    -> ON lvup_posts.ID = price_query.post_id
    -> WHERE 1=1
    -> AND ( lvup_posts.ID NOT IN (
    -> SELECT object_id
    -> FROM lvup_term_relationships
    -> WHERE term_taxonomy_id IN (48) )
    -> AND lvup_term_relationships.term_taxonomy_id IN (4122) )
    -> AND lvup_posts.post_type = 'product'
    -> AND (lvup_posts.post_status = 'publish'
    -> OR lvup_posts.post_status = 'acf-disabled'
    -> OR lvup_posts.post_status = 'private')
    -> GROUP BY lvup_posts.ID
    -> ORDER BY price_query.price DESC
    -> LIMIT 0, 25;
+--------+
| ID     |
+--------+
| 185954 |
| 185956 |
| 185886 |
| 185894 |
| 185896 |
| 172127 |
| 164905 |
| 164901 |
| 164907 |
| 164913 |
| 164558 |
| 164911 |
| 164909 |
| 159629 |
| 172188 |
| 172201 |
| 164903 |
| 176110 |
| 135650 |
| 159636 |
| 141418 |
| 186722 |
+--------+
22 rows in set (0.00 sec)

*************************** 1. row ***************************
           id: 1
  select_type: PRIMARY
        table: lvup_term_relationships
         type: ref
possible_keys: PRIMARY,term_taxonomy_id
          key: term_taxonomy_id
      key_len: 8
          ref: const
         rows: 22
        Extra: Using where; Using index; Using temporary; Using filesort
*************************** 2. row ***************************
           id: 1
  select_type: PRIMARY
        table: lvup_posts
         type: eq_ref
possible_keys: PRIMARY,type_status_date
          key: PRIMARY
      key_len: 8
          ref: ds_wp.lvup_term_relationships.object_id
         rows: 1
        Extra: Using where
*************************** 3. row ***************************
           id: 1
  select_type: PRIMARY
        table: <derived2>
         type: ref
possible_keys: key0
          key: key0
      key_len: 8
          ref: ds_wp.lvup_term_relationships.object_id
         rows: 10
        Extra:
*************************** 4. row ***************************
           id: 4
  select_type: DEPENDENT SUBQUERY
        table: lvup_term_relationships
         type: unique_subquery
possible_keys: PRIMARY,term_taxonomy_id
          key: PRIMARY
      key_len: 16
          ref: func,const
         rows: 1
        Extra: Using index; Using where; Full scan on NULL key
*************************** 5. row ***************************
           id: 2
  select_type: DERIVED
        table: lvup_term_relationships
         type: ref
possible_keys: PRIMARY,term_taxonomy_id
          key: term_taxonomy_id
      key_len: 8
          ref: const
         rows: 22
        Extra: Using index; Using temporary; Using filesort
*************************** 6. row ***************************
           id: 2
  select_type: DERIVED
        table: lvup_postmeta
         type: ref
possible_keys: post_id,meta_key
          key: post_id
      key_len: 8
          ref: ds_wp.lvup_term_relationships.object_id
         rows: 5
        Extra: Using where
</details>

**Comment by mikejolley** [comment]
@parkinep This would be great if it were possible. It's fine when you're building queries manually but we're not, we're extending WordPress core queries.

The active_prods parts needs to know the query for the current page e.g. what terms are in the where clause. But there is no way to pull just this part to know how to narrow down the results. The `where` clause we can see is just a string and made up of the term_taxononomy queries and where clause for posts.

See `order_by_price_asc_post_clauses`.

https://github.com/woocommerce/woocommerce/blob/3522857d23051844bea742a37a1b0b242f7850af/includes/class-wc-query.php#L499

If you found a way to improve this in the context of that function, great, please let me know how or send in a PR. Otherwise it doesn't look like this can be modified sadly.

Our recent changes implementing CRUD for all objects will eventually allow us to move all product data out of meta, into a dedicated table. When this happens, the joins required should be way more sensible (we hope) to speed this up.

**Comment by mikejolley** [comment]
Just putting this in front of @kloon and @rodrigoprimo for reference since this is performance related, but I don't see this as a solution. Cheers.

**Comment by parkinep** [comment]
You asked if I could make it work in the scope of that one function, I did:
`public function order_by_price_desc_post_clauses( $args ) {
		global $wpdb, $wp_query;

		//Check that queried object indeed is term
		if($wp_query->queried_object INSTANCEOF WP_Term){
			//Get child terms if any
			$tax_decs = get_term_children($wp_query->queried_object->term_taxonomy_id, $wp_query->queried_object->taxonomy);

			//Put the queried term into the array of child terms
			array_unshift($tax_decs, $wp_query->queried_object->term_taxonomy_id);

			//Stringify the array for use in query
			$tax_decs_s = implode(",", $tax_decs);
			
			$args['join']    .= " INNER JOIN ( 
			SELECT post_id, max( meta_value+0 ) price FROM $wpdb->postmeta INNER JOIN ( SELECT lvup_term_relationships.object_id FROM lvup_term_relationships WHERE 1=1 AND lvup_term_relationships.term_taxonomy_id IN ($tax_decs_s) ) as active_prods ON lvup_postmeta.post_id = active_prods.object_id WHERE meta_key='_price' GROUP BY post_id ) as price_query ON $wpdb->posts.ID = price_query.post_id ";
		}else{
			$args['join']    .= " INNER JOIN ( SELECT post_id, max( meta_value+0 ) price FROM $wpdb->postmeta WHERE meta_key='_price' GROUP BY post_id ) as price_query ON $wpdb->posts.ID = price_query.post_id ";
		}
		$args['orderby'] = " price_query.price DESC ";
		return $args;
	}`

**Comment by mikejolley** [comment]
Hmm So this would speed up term pages only? I assume you get slow results on the main shop page still with this?

**Comment by parkinep** [comment]
As the speedup is achieved by pruning the query from products that are not relevant, i.e. not in the hierarchy of that term, yes. The main shop has to look up *all* products, categories don't.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/16694
