### ISSUE TITLE
Total calculation not correct after apply coupon

### ISSUE THREAD

**Issue by mytc** [woocommerce/woocommerce#16590]
This is strange problem where when customer add multiple items into cart and apply the total amount will not add up correctly. It will always calculated $1 dollar more. 

Eg:
![tax](https://user-images.githubusercontent.com/3824518/29654879-8d0d77f4-88e1-11e7-90a3-3e1a217fc290.png)

The coupon is 25% cart discount, and the total amount should be NT$225, but instead it shows NT$226. 
The tax rate configuration is 5% inclusive and it is zero decimal currencies. 

But if I add only one item into cart, then it will calculated correctly. 

Any idea why?

By the way, when I try to debug the items in the cart, by printing the object, I little confused with this:
 ```
[quantity] =>; 5
                    [line_total]  => 238.095238095
                    [line_tax]  => 11.9047619048
                    [line_subtotal]  => 238.095238095
                    [line_subtotal_tax]  => 11.9047619048
                    [line_tax_data]  =>Array
                        (
                            [total]  => Array
                                (
                                    [1]  => 11.9047619048
                                )

                            [subtotal]  => Array
                                (
                                    [1] =&gt; 11.9047619048
                                )

                        )
```

Why line total, subtotal, above got so many decimal points? Since it is zero decimal currency and the tax rate is 5%. I can't calculate the amount as shows in above.

**Comment by mikejolley** [comment]
Unable to replicate this one I'm afraid:

<img width="826" alt="2017-08-24 at 12 41" src="https://user-images.githubusercontent.com/90977/29664936-b329b794-88c9-11e7-95dd-688209f19467.png">

Thats a 25% coupon. All prices entered with 0 DP. Prices set to 0 DP. Tax inclusive at 5% for everywhere.

If I var dump, my totals are rounded.

This was tested on 3.1.1 and master.
