### ISSUE TITLE
New Customer Registration Password  

### ISSUE THREAD

**Issue by ayushsingh007** [woocommerce/woocommerce#16603]
Considering to add some php based validation too, during the registration process because a customer can register using a low strength password by removing disabled class from "Register" button. That's a security threat.

**Comment by mikejolley** [comment]
The password strength is a guideline. The meter is also JS based so including a PHP based method too would be extra overhead and I don't think it's something we should add.

Looking at WordPress itself, you can use weak passwords. Not by removing markup, but by checking a box to confirm use of a weak password. I see this as being no different. The user makes a conscious choice of doing this.

Also to point out, our checkout doesn't stop a user placing an order with a weak password - they are noticed, but not blocked from submission. We don't want to stop conversions.

Also to note, despite it only being a guideline, there are lots of moans about this already affecting conversions. We've stood our ground about keeping the guideline in place, but I think forcing it server side would anger lots of users. Have a search of github to find some examples of this :)

Thanks!
