### ISSUE TITLE
Variation_id not being generated

### ISSUE THREAD

**Issue by shehrozsheikh** [woocommerce/woocommerce#16605]
Variation_id is showing 0, even if I have that variation in my variations. 

![screenshot_39](https://user-images.githubusercontent.com/17910552/29710671-b865bdc0-89aa-11e7-8d1d-88b43ae12809.png)

It keeps loading and after some time, it starts showing an error: "Sorry , NO PRODUCTS MATCHED YOUR SELECTION. PLEASE CHOOSE A DIFFERENT COMBINATION".

**Comment by ayushsingh007** [comment]
Variation_id shows 0 on page load, since no variations are selected by default. But, once you select a variation, variation_id will change as per the variation selected. So, if on selection, still you are getting variation_id 0 that means there is some issue in your js file and that is blocking the default woocommerce functionality.

**Comment by shehrozsheikh** [comment]
@ayushsingh007 I've passed parameters for all the values in GET, params are also correct (I verified it). JavaScript doesn't apply in source code so JS cannot make changes to the variation_id. 

Thanks for your reply, but that's not the case here, this issue is occurring only for few products.

**Comment by ayushsingh007** [comment]
Share your website's url to explore the issue.

**Comment by claudiulodro** [comment]
> JavaScript doesn't apply in source code so JS cannot make changes to the variation_id

JavaScript won't change the source code, but it can very much change the value of an input element. Use your browser's element inspector to see what the current value is.

We can't do anything with the information you have given us. We need a system status report or useful debugging information. I'll reopen this if you come back with more info.
