### ISSUE TITLE
Allow get_products used args to be extendable

### ISSUE THREAD

**Issue by MahmudHamid** [woocommerce/woocommerce#16607]
As I can see the the get_products function takes all passed args and limit them to some hand picked args without allowing to extend those hand picked args. So is it possible to add a filter on:
	
$wp_query_args = array (
	'post_status'    => $args['status'],
	'posts_per_page' => $args['limit'],
	'meta_query'     => array(),
	'orderby'        => $args['orderby'],
	'order'          => $args['order'],
	'tax_query'      => array(),
);

So we can extend it to accept for example "author"

**Comment by claudiulodro** [comment]
Starting WC 3.2 you can filter the query args for wc_get_products [here](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L1519).

There are also [many new options](https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query), so you may not have to filter at all.
