### ISSUE TITLE
Woocommerce permalinks are not SEO friendly

### ISSUE THREAD

**Issue by TFD777** [woocommerce/woocommerce#16602]
Hello, so recently I have decided to create my own e-shop and I have chosen to work with woocommerce because it is very popular at the moment. As soon as I installed everything, I was really overwhelmed with all the features and I was very happy. However I have noticed weird issue with permalinks.
The structure that I intended to have was:
**Home** -> **Accessories** -> **Bracelets** -> **Leather Bracelet**
"Accessories" was supposed to be the shop page with categories only, then "Bracelets" was supposed to be one of the categories with all the items of that category, and the "Leather Bracelet" was supposed to be the item preview page.
For the best SEO results the expected logic of URL was supposed to be:
**mydomain.com** -> **mydomain.com/accessories** -> **mydomain.com/accessories/bracelets** -> **mydomain.com/accessories/bracelets/leather-bracelet**
However, for some reason Woocommerce doesn't approve such logic and instead works like that:
**mydomain.com** -> **mydomain.com/accessories** -> **mydomain.com/product-category/bracelets** -> **mydomain.com/product/leather-bracelet**
Now please tell me, who thought of this structure?
Not only it is SEO unfriendly, but it is also really confusing because even the Breadcrumb is showing:
**Home** -> **Bracelets** -> **Leather bracelet** (it skips the category page, tho).  
Now the funniest part - apparently if you try to fix the structure by modifying the "Permalinks" settings, it causes the 404 errors in various places. As I understood, this is being caused because of some kind of conflict. So, I have spent hours on trying to fix that and I wanted to tell the results of my analysis that may help you to fix the conflict with permalinks.
So, I started by changing the product category slug from **product-category** to **accessories**, the other permalink settings were kept on default (**Common Settings -> Custom Structure: /%category%/%postname%/ , Product permalinks -> Default**). Then I tried to navigate to my product and here's the structure that I got:

URL navigation:
**mydomain.com** -> **mydomain.com/accessories** -> **mydomain.com/accessories/bracelets** -> **mydomain.com/product/leather-bracelet**

Breadcrumb navigation:
"**Home > Accessories**"  ->  "**Home > Bracelets**"  ->  "**Home > Bracelets > Leather bracelet**"

As you can see, the URL navigation is much better, however, the product url is mydomain.com/product/leather-bracelet instead of mydomain.com/accessories/bracelets/leather-bracelet . Also the Breadcrumb navigation skips the Accessories page as soon as you enter the product category, so this is not the result we expect.
So, next I have changed the Product permalinks from '**Default**" to "**Shop base with category**" which is **/accessories/%product_cat%/** . So now by following the logic principles everything should be fine, however here are the navigation results:

URL navigation:
**mydomain.com** -> **mydomain.com/accessories** -> **Error 404 on mydomain.com/accessories/bracelets** -> **mydomain.com/accessories/bracelets/leather-bracelet**

Breadcrumb navigation:
"**Home > Accessories**"  ->  "**Home > Error 404**"  ->  "**Home > Accessories > Bracelets > Leather bracelet**"

Now there is something interesting that I have noticed. Even though the **mydomain.com/accessories/bracelets** failed to open, but when I have opened the product directly, I got the results that I wanted - perfect URL and perfect Breadcrumb.

Now the most interesting part. I have changed the **Custom settings** from /**%category%/%postname%/** to **/%product_cat%/** and _VOILÀ_, here are the navigation results:

URL navigation:
**mydomain.com** -> **mydomain.com/accessories** -> **mydomain.com/accessories/bracelets** -> **mydomain.com/accessories/bracelets/leather-bracelet**

Breadcrumb navigation:
"**Home > Accessories**"  ->  "**Home > Accessories > Bracelets**"  ->  "**Home > Accessories > Bracelets > Leather bracelet**"

Perfect results! Exactly what I wanted, HOWEVER, now **all the other pages except the shop are showing Error 404**. Oh, the irony... But as you can see it is possible to have a shop with perfect links so that means there should be a workaround for this. And that's the main reason why I am sitting here and writing this post for almost an hour in order to address this issue and I really believe that you can fix it, and I have provided as much information as possible to make it easier for you, so please do something about this issue, this URL structure should have been set by default because it is crucial for a good SEO and I can guarantee that a lot of people will switch to woocommerce from other eCommerce platforms as soon as this issue is fixed.

*EDIT: Added Markdown for easier reading

**Comment by mikejolley** [comment]
Hi there,

WordPress controls permalinks, and due to the way it's setup it needs a unique base on either products or categories in order to know what 'type' of thing to show. If permalinks conflict (as you've experienced) it will 404. In your case, it doesn't know if it's showing another 'category' or a 'product'.

You can have a category base for products, e.g. `/top-cat/sub-cat/product`, however, then you need a unique base for categories, e.g. `category-base/top-cat/sub-cat` Without this, it doesn't know if `product` in this example is actually a product.

Unfortunately it's not possible to change this without quite a bit of WordPress 'hacking', and as such it's not a solution we can offer generally. It will conflict on certain sites. It will cause 404s for users.

This is not a new problem, and this is something you can try to 'fix' at your own risk. Further reading:

https://jonnyjordan.com/blog/how-to-remove-category-from-your-urls-in-wordpress/
https://github.com/woocommerce/woocommerce/issues/1178

Thanks!

p.s.  Where is it stated that breadcrumbs must match the permalink exactly for SEO? Surely the keywords are more important? I'd be surprised if this had an noticeable effect on google page ranks. Would be better invest time in proper keywords etc.

**Comment by opportus** [comment]
Hi @TFD777,

If might be interesting for Google to make the distinction between different type of content on your site, as it could help also users to understand more easily the type of content they're actually on.
Indeed, how would you make the difference betwwen a blog category or a product category from its URL? How Google could make this difference? The same way you have also to diferenciate a product from a post.

Anyway if you still want to do that, WPSEO plugin might help you with this. But I don't recommend it. From SEO as much as from developper point of view.

**Comment by TFD777** [comment]
@mikejolley Thanks for the reply. Breadcrumb has nothing to do with SEO but it was skipping the product category page for some reason. The ideal Breadcrumb navigation in my case would be:
"**Home > Accessories**" -> "**Home > Accessories > Bracelets**" -> "**Home > Accessories > Bracelets > Leather bracelet**" , however the current navigation is:
"**Home > Accessories**" -> "**Home > Bracelets**" -> "**Home > Bracelets > Leather bracelet**", it doesn't show the link to the shop. Anyways, I thought the information that I have provided would help you to fix this issue, but if it's still complicated then I guess I will have to keep it as it is.

**Comment by TFD777** [comment]
@opportus Thanks, I will take a look. 👍

**Comment by TFD777** [comment]
@mikejolley Thank you, By the way, one more question, why I cannot have Product permalinks set to "/%product_cat%/? When I do this, it automatically changes to /product/%product_cat%/ .

**Comment by mikejolley** [comment]
They need a unique base to distinguish them from posts/pages etc.

**Comment by opportus** [comment]
@TFD777 , `/%product_cat%/` is the product category **base**, not the product category itself...

**Comment by TFD777** [comment]
@mikejolley Alright, thanks a lot!

**Comment by ThemesMatic** [comment]
The unique product base... should be the _/%product_cat%/_.
With "-2" added in the case of a duplicate url. This is the same way WordPress handles it.

Coincidentally, by removing _product_ as a base and replacing it with the user created _/%product_cat%/_ (using -2 on duplicates) this simple solution mirrors WordPress URL structures.
It also creates very good/clean SEO URLs as any other big eCommerce retailer.
