### ISSUE TITLE
Does original post title need to be output on all post type?

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#16609]
https://github.com/woocommerce/woocommerce/blob/3b3ceebc1fb7d4c7722e7a65d1fb41617d18e15a/includes/admin/class-wc-admin-post-types.php#L1742

CC @mikejolley

**Comment by claudiulodro** [comment]
[It's used when updating variation names](https://github.com/woocommerce/woocommerce/blob/18873ac9a7372c75eea6eee2d49e65c64a0e027d/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L377).

You do need it on all types. A user can change the product name and the product type to Variable and it needs to be used right then to update the variation names.
