### ISSUE TITLE
Returning a line item product meta on Orders API

### ISSUE THREAD

**Issue by echogit** [woocommerce/woocommerce#16619]
Hi, I had this working on WC 2.1. After I updated WC, the product meta stopped coming on the API. How should I make for the product meta appear on the order line item API result?

On my functions.php I have:

- Saving the meta (this works fine)
```
function save_product_ncm() {
	  global $post;
  $post_id=get_the_ID();
  if (get_post_type($post_id) == 'product') {
  $ncm_meta['_ncm'] = $_POST['_ncm'];
		foreach ($ncm_meta as $key => $value) { 
			if( $post->post_type == 'revision' ) return; // Don't store custom data twice
			$value = implode(',', (array)$value); // If $value is an array, make it a CSV (unlikely)
			if(get_post_meta($post->ID, $key, FALSE)) { // If the custom field already has a value
				update_post_meta($post->ID, $key, $value);
			} else { // If the custom field doesn't have a value
				add_post_meta($post->ID, $key, $value);
			}
			if(!$value) delete_post_meta($post->ID, $key); // Delete if blank
		}
   }
}
```

- Adding the meta to the api:

```
add_filter( 'woocommerce_api_order_response', 'custom_woocommerce_api_order_response', 1);
function custom_woocommerce_api_order_response($order_data){
        for ($i=0; $i<count($order_data['line_items']); $i++) {
            $order_data['line_items'][$i]['ncm'] = get_post_meta( $order_data['line_items'][$i]['product_id'], '_ncm', true );; 
        }
        return $order_data;
}
```

**Comment by claudiulodro** [comment]
Assuming you are still using the legacy v1 API introduced in 2.1 and you haven't upgraded to the newest version of the API, it looks like what you're doing should still be working. [The hook is still available in the legacy v1 API](https://github.com/woocommerce/woocommerce/blob/master/includes/api/legacy/v1/class-wc-api-orders.php#L233) and the order response is still structured the same way.

I would test and make sure `custom_woocommerce_api_order_response` is still getting called by putting some logging or something in there.

**Comment by echogit** [comment]
Actually I'm using the v2, with latest WP and WC. On the latest versions of v2, what's the correct way to add an existing meta to the API?
