### ISSUE TITLE
Dropdowns dissapear + fields doubble

### ISSUE THREAD

**Issue by dotstijn** [woocommerce/woocommerce#16615]
i there,

Since woocommerce 3 there’s something strange with the layout of my settings or order fields. When the pages loads i see dropdown field but it quicly changes upon loading to a free text field. The fields are also twice displayed.

This is what i get when the page loads:
[image 0](http://i.imgur.com/VmudlOX.png)

this is the result after loading:
[image 1](http://i.imgur.com/a8qeazs.png)

So i’m no longer able to change to options set by a dropdown pick-list field.
Same problem on another computer.
Settings for wordpress display is ok.

Thanks for the help

### WordPress Environment ###

Home URL: http://angelodorny.be
Site URL: http://angelodorny.be
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.52.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Jouw winkel gebruikt geen HTTPS. Leer meer over HTTPS en SSL-certificaten.
Hide errors from visitors: ✔

### Active Plugins (28) ###

WooCommerce Order Export and More PRO: door JEM Plugins – 1.4.3
Contact Form 7: door Takayuki Miyoshi – 4.8.1
Download Plugin: door IndiaSan – 1.0.2
EU Cookie Law: door Alex Moss
Marco Milesi
Peadig
Shane Jones – 2.10

Featured Video Plus: door Alexander Höreth – 2.3.3
Loco Translate: door Tim Whitlock – 2.0.15
MailChimp for WordPress: door ibericode – 4.1.6
MailChimp for WooCommerce: door MailChimp – 2.0.1
WooCommerce Pushover Integration: door Shop Plugins – 1.0.12
Quick Page/Post Redirect Plugin: door anadnet – 5.1.8
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 2.2.6
SeedProd Coming Soon Page Pro: door SeedProd – 5.4.2
SendCloud | Smart Shipping Service: door SendCloud B.V. – 1.0.13
Stop Spam Comments: door Pino Ceniccola – 0.2.1.2
UpdraftPlus – Backup/Restore: door UpdraftPlus.Com
DavidAnderson – 2.13.5.21

Woo Store Vacation: door Mahdi Yazdani – 1.1.0
WooCommerce Advanced Review Reminder: door kodemann.com – 2.0
WooCommerce Email Customizer: door cxThemes – 3.13
WooCommerce MailChimp: door Saint Systems – 2.1.1
WooCommerce Payment Fees Lite: door Pinch Of Code – 1.5.2
Woocommerce Pay.nl Payment Methods: door Pay.nl – 3.1.2
WooCommerce Facturen en Pakbonnen afdrukken: door SkyVerge – 3.3.1 – 3.3.2 is beschikbaar
WooCommerce: door Automattic – 3.1.2
WooSidebars: door WooThemes – 1.4.3
WordPress Importeerder: door wordpressdotorg – 0.6.3
Yoast SEO: door Team Yoast – 5.2
WP Mail Logging: door Christian Zöller – 1.8.1
WP Statistics: door WP-Statistics Team – 12.0.10

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator:
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #1282 – /webshop/
Winkelmand: #851 – /cart/
Afrekenen: #852 – /checkout/
Mijn account: #853 – /my-account/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL:
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.7
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

The page I need help with: http://www.angelodorny.be

## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ]x The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] xI have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. go to wocommerce settings
2.
3.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiulodro** [comment]
It looks something (99% chance one of your other plugins) is using an old version of the select2 library or broke select2 in some way.

This is what it should look like:
<img width="673" alt="screen shot 2017-08-28 at 11 29 16 am" src="https://user-images.githubusercontent.com/7317227/29787599-615fae78-8be4-11e7-861b-c7daaf255096.png">

You can figure out which plugin is causing problems by turning off all plugins except WooCommerce. Turn them on one-by-one and check after each one. When the inputs break, that's the problem plugin.

**Comment by dotstijn** [comment]
Thanks for the help! I check the java console and there was an error for the "order export" plugin. After disabling this plugin the problem was solved.
