### ISSUE TITLE
 WooCommerce not sending emails (New/Cancelled/Failed Order)

### ISSUE THREAD

**Issue by BRG2410** [woocommerce/woocommerce#16617]
Hi there,

I am using the latest WordPress (4.8.1) and WooCommerce (3.1.2), and having an issue setting up the WooCommerce ‘New/Cancelled/Failed Order’ emails. I have configured all correctly within the ‘Email notifications’ section. The problem is that the emails are not automatically sent. When an new order / cancelled order / failed order happens I can see the details in the ‘orders’ section and can manually ‘resend’ them but they just do not automatically send. I did some research and tried adding the following snippet of code on the functions.php:

/**
* Code goes in theme functions.php.
*/
add_filter( ‘woocommerce_defer_transactional_emails’, ‘__return_false’ );

… but unfortunately this did not fix the problem.

Any suggestions on how to fix?

**Comment by mikejolley** [comment]
See https://docs.woocommerce.com/document/email-faq/
