### ISSUE TITLE
price_html is empty in variations when all variations have the same price

### ISSUE THREAD

**Issue by alaarihan** [woocommerce/woocommerce#16618]
Hi,

I noticed when I add the same prices for all variations in a variable product and call this function:
$product->get_available_variations();

I get array of variations object with all info but price_html is empty!
When I make any variation price different than other variations then I get the correct price_html value (not empty).
I use the latest WooCommerce release 3.1.2

**Comment by mikejolley** [comment]
This is intentional. Variable product pages show a price below the title (for all variations) and then a specific variation price after selection. If this are the same and match the variable price, it's not shown as it would be duplicate info.

Thanks
