### ISSUE TITLE
Coupon Export generated instead of Order Export 

### ISSUE THREAD

**Issue by crinog1** [woocommerce/woocommerce#16622]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [don't know ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. go to  order export
2. Select minimum fields
3. generate report

## Expected/actual behavior

When I follow those steps, I see... a coupon export xlsx

I was expecting to see... a order export xlsx

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
`
### WordPress Environment ###

Home URL: https://fba-hero.com
Site URL: https://fba-hero.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30-nmm1
PHP Post Max Size: 200 MB
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: ZDUMr_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

Gravity Forms: by rocketgenius – 2.2.5
The7 LayerSlider WP: by Kreatura Media – 6.5.7
The7 Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.15
AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.1.7
AffiliateWP: by AffiliateWP
LLC – 2.0.10.1

AffiliateWP - Affiliate Forms For Gravity Forms: by AffiliateWP
LLC – 1.0.15

Broken Link Checker: by Janis Elsts
Vladimir Prelovac – 1.11.5

Connects - Contact Form 7 Addon: by Brainstorm Force – 1.0.3
Connects - Mailchimp Addon: by Brainstorm Force – 2.0.3.3
Contact Form 7: by Takayuki Miyoshi – 4.9
ConvertPlus Addons for Visual Composer: by Brainstorm Force – 1.1.3
ConvertPlus: by Brainstorm Force – 3.0.0
The7 Elements: by Dream-Theme – 1.2.4.1
EWWW Image Optimizer: by Shane Bishop – 3.6.1
Go Pricing - WordPress Responsive Pricing Tables: by Granth – 3.3.7
Yet Skin - Add-on for Go Pricing: by Granth – 1.0.0
InfiniteWP - Client: by Revmakx – 1.6.5
Jetpack by WordPress.com: by Automattic – 5.2.1
The7 Visual Composer: by Michael M - WPBakery.com – 5.2.1
My Custom Functions: by Arthur Gareginyan – 4.6
PixelYourSite: by PixelYourSite – 5.0.7
The7 Slider Revolution: by ThemePunch – 5.4.5.2
SI Captcha Anti-Spam: by fastsecure – 3.0.2
Social Icons Widget by WPZOOM: by WPZOOM – 3.0.1
TablePress: by Tobias Bäthge – 1.8
Tracking Code Manager: by IntellyWP – 1.11.1
Ultimate Posts Widget: by Boston Dell-Vandenberg – 2.0.6
Woo Failed Payments Log: by Atul Rana – 1.0
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.6
WooCommerce EU VAT Number: by WooCommerce – 2.3.1
WooCommerce Export Customer Email: by MH Mithu – 1.3
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.6
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3
WooCommerce - Store Exporter Deluxe: by Visser Labs – 2.3.8
WooCommerce - Store Toolkit: by Visser Labs – 1.7.5
WooCommerce Subscriptions: by Prospress Inc. – 2.2.11
WooCommerce: by Automattic – 3.1.2
Yoast SEO: by Team Yoast – 5.3.2
WP Rocket: by WP Media – 2.10.7

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #239 - /cart/
Checkout: #241 - /checkout/
My account: #243 - /my-account/

### Theme ###

Name: The7
Version: 5.4.2
Author URL: http://dream-theme.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: dt-the7/woocommerce/cart/cart.php
dt-the7/woocommerce/cart/cross-sells.php
dt-the7/woocommerce/checkout/form-billing.php
dt-the7/woocommerce/checkout/form-checkout.php
dt-the7/woocommerce/checkout/form-coupon.php
dt-the7/woocommerce/checkout/form-login.php
dt-the7/woocommerce/checkout/form-shipping.php
dt-the7/woocommerce/checkout/review-order.php
dt-the7/woocommerce/checkout/thankyou.php
dt-the7/woocommerce/content-product.php
dt-the7/woocommerce/content-product_cat.php
dt-the7/woocommerce/global/breadcrumb.php
dt-the7/woocommerce/global/form-login.php
dt-the7/woocommerce/global/quantity-input.php
dt-the7/woocommerce/loop/loop-end.php
dt-the7/woocommerce/loop/loop-start.php
dt-the7/woocommerce/loop/orderby.php
dt-the7/woocommerce/loop/pagination.php
dt-the7/woocommerce/myaccount/form-login.php
dt-the7/woocommerce/notices/error.php
dt-the7/woocommerce/notices/notice.php
dt-the7/woocommerce/notices/success.php
dt-the7/woocommerce/order/order-details-customer.php
dt-the7/woocommerce/order/order-details.php
dt-the7/woocommerce/single-product/meta.php
dt-the7/woocommerce/single-product/price.php
dt-the7/woocommerce/single-product/related.php
dt-the7/woocommerce/single-product/up-sells.php

### Templates ###

thumbnail: 
medium: 
medium_large: 
large: 
shop_thumbnail: 
shop_catalog: 
shop_single: 

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Templates ###

Debugging mode for Store Exporter Deluxe: ✔
Extended logging mode for Store Exporter Deluxe: ✔
Scheduled Export to FTP: ✔
Scheduled Export to SFTP: ❌ The required SFTP functions are not available; ssh2_connect()
ssh2_auth_password()
ssh2_sftp(). Contact your hosting provider.

`
</details>

**Comment by claudiulodro** [comment]
WooCommerce doesn't have the ability to export xlsx files like you describe. This is a bug in your Store Exporter Deluxe plugin.
