### ISSUE TITLE
Edit order does not work

### ISSUE THREAD

**Issue by cornarie** [woocommerce/woocommerce#16624]
When want to edit an order the little pencils on the right hand corner are not clickable?

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiulodro** [comment]
They work properly in my testing. You may have plugins or something else breaking them. Are there any errors in your JavaScript console? 

If you want us to investigate this further, I need you to actually do the Prerequisites/Isolating the problem/WordPress Environment stuff in the issue template and provide that information. If you've done those go ahead and open a new issue and I can take another look.
