### ISSUE TITLE
qTranslateX multilingual variable product attribute fix

### ISSUE THREAD

**Issue by wywarren** [woocommerce/woocommerce#16623]
Brancing off from this post: https://github.com/qTranslate-Team/qtranslate-x/issues/277

qTranslateX out of the box is compatible with WooCommerce but there seems to be some issues with multilingual support for variable product attributes. For qTranslateX the standard syntax for multilingual text fields is :

[:en]English Text[de:]German text[:]

Where [:] denotes the end of the field and en and de are the respective internal language codes.

From the forum post above, there was a hack made to v2.x of WooCommerce but in v3.x the code has changed.

To remedy this, currently, I'm changing line 211 in includes/class-wc-product-variable.php from:

public function get_variation_attributes() {
	return __($this->variation_attributes);
}

to:

public function get_variation_attributes() {
	__(return __($this->variation_attributes));
}

This fixes it for the front end drop down select boxes. However, in one of the languages I'm still getting a warning:

Warning: Illegal offset type in isset or empty in /var/www/html/shuyo/wp-includes/pomo/translations.php on line 85

I hope this change can be appended as a bug fix for upcoming WooCommerce releases.

## Prerequisites
- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install the latest WooCommerce and qTranslateX plugin
2. Go to Settings > Languages > Languages Tab, and enable at least one other language.
3. Create a product and change its type to variable product.
4. Go to the attributes tab and add an attribute for the variable product.
5. Conform to the qTranslateX syntax for inputting multiple languages and enter in as sample data:
Name: [:en]Size[:tw]尺寸[:]
Value(s): [:en]Small[:tw]小[:] | [:en]Medium[:tw]中[:] | [:en]Large[:tw]大[:]
6. Be sure to check off "Visible on the product page" and "Used for variations"
7. Go to the variations tab and "Create variations from all attributes". You should get 3 variants with the values posted above.
8. Publish the product and goto the product page.

## Expected/actual behavior

When I follow those steps, I see an empty drop down box for the variation.

I was expecting to see language specific attribute selections.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://shop.sellerlinx.com/shuyo
Site URL: https://shop.sellerlinx.com/shuyo
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 5.6.30-7+deb.sury.org~xenial+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ❌ Your server does not have the DOMDocument class enabled - HTML/Multipart emails
and also some extensions
will not work without DOMDocument.

GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.8
WC Database Prefix: slwp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

CloudFlare Flexible SSL: by iControlWP – 1.2.2
JSON Basic Authentication: by WordPress API Team – 0.1
Advanced Custom Fields: qTranslate: by funkjedi – 1.7.23
ACF to REST API: by Aires Gonçalves – 2.2.1
Advanced Custom Fields: by Elliot Condon – 4.4.11
Allpay AIO for Woocommerce: by 因創科技 – 1.1.4
Cimy User Extra Fields: by Marco Cimmino – 2.7.2
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.1

CPT-onomies: Using Custom Post Types as Taxonomies: by Rachel Carden – 1.3.6
Google Tag Manager for Wordpress: by Thomas Geiger – 1.7.1
Google XML Sitemaps: by Arne Brachhold – 4.0.9
Hide Admin Bar: by Shelby DeNike – 0.3.8.1
InfiniteWP - Client: by Revmakx – 1.6.4
PixelYourSite: by PixelYourSite – 5.0.7
qTranslate-X: by qTranslate Team – 3.4.6.8
WP REST API: by WP REST API Team – 2.0-beta15
Sales Rep: by Warren Wang @ Qoobit – 1.0
Sellerlinx REST API Extension: by Warren Wang @ Sellerlinx – 1.0
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.1.9
WooCommerce Customer Relationship Manager: by Actuality Extensions – 3.1.6
WooCommerce Dynamic Pricing: by Lucas Stark – 3.0.8 – 3.0.12 is available
WooCommerce AdWords Conversion Tracking: by Wolf+Bär GmbH – 1.3.5
WooCommerce AdWords Dynamic Remarketing: by Wolf + Bär GmbH – 1.3.3
WooCommerce & qTranslate-X: by qTranslate Team – 1.3
WooCommerce Social Login: by WooThemes / SkyVerge – 2.0.4 – 2.3.1 is available
WooCommerce WishLists: by Lucas Stark – 1.11.2 – 2.0.10 is available
WooCommerce: by Automattic – 3.1.2
WP Admin UI Customize: by gqevu6bsiz – 1.5.10
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP REST API Controller: by YIKES
Inc.
Evan Herman
yikesitskevin – 1.4.1

Customizer Field EndPoint: by Bishal Basnet – 1.0.0
WPFront User Role Editor: by Syam Mohan – 2.13.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Sellerlinx Storefront Theme
Version: 1.0.0
Author URL: https://qoobit.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.3 – 2.2.5 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: sellerlinx-storefront-theme/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0
sellerlinx-storefront-theme/woocommerce/cart/cart-item-data.php
sellerlinx-storefront-theme/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.1.0
sellerlinx-storefront-theme/woocommerce/cart/cart-totals.php
sellerlinx-storefront-theme/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.1.0
sellerlinx-storefront-theme/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.1.0
sellerlinx-storefront-theme/woocommerce/cart/proceed-to-checkout-button.php
sellerlinx-storefront-theme/woocommerce/cart/shipping-calculator.php
sellerlinx-storefront-theme/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/single-product/add-to-cart/external.php
sellerlinx-storefront-theme/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.7
sellerlinx-storefront-theme/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/single-product/add-to-cart/variation.php
sellerlinx-storefront-theme/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.1.0
sellerlinx-storefront-theme/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.1.0
sellerlinx-storefront-theme/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.1.0
sellerlinx-storefront-theme/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.1.0
sellerlinx-storefront-theme/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/single-product/review-meta.php version 2.6.0 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/single-product/review-rating.php version 2.6.0 is out of date. The core version is 3.1.0
sellerlinx-storefront-theme/woocommerce/single-product/review.php
sellerlinx-storefront-theme/woocommerce/single-product/sale-flash.php
sellerlinx-storefront-theme/woocommerce/single-product/share.php
sellerlinx-storefront-theme/woocommerce/single-product/short-description.php
sellerlinx-storefront-theme/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/single-product/tabs/description.php
sellerlinx-storefront-theme/woocommerce/single-product/tabs/tabs.php
sellerlinx-storefront-theme/woocommerce/single-product/title.php
sellerlinx-storefront-theme/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
sellerlinx-storefront-theme/woocommerce/single-product-reviews.php
sellerlinx-storefront-theme/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
`get_variation_attributes` returns an array. `__()` supports strings. Your code change is invalid in both cases.

If the developers of Qtranslate X want to request extra filters or changes, please send them here to log an issue. I expect they may need something changed when these values eventually get displayed, but not here. And generally, I don't think wrapping variables in `__()` is a good idea since translation tools cannot parse variables.

Thanks

**Comment by armag3dd0n** [comment]
Hello,
Currently I'm working on a e-shop in Wordpress 4.9.1, WooCommerce 3.2.5 and the qTranslate 3.4.6.8 .

I want to use 2 languages, for example English, Greek.

The problem I'm facing is when I'm adding attributes and variations for a product I don't have any option to select in the product's page.

My steps :

Attributes
Name: [:en]Flavor[:el]greek_word[:]
Value(s) : [:en]Classic[:el]greek_word[:] | [:en]Almond[:el]greek_word[:]
Visible on the product page and Used for variations are ticked

Variations
Create variations for all attributes -> 2 variations added
I changed the Regular price for both variations, save changes.

When I refresh the page for the specific item, there is no option in the dropdown box.

Any help?

Thank you

**Comment by claudiosanches** [comment]
@armag3dd0n you should try a qTranslate support channel.
