### ISSUE TITLE
Related products priority

### ISSUE THREAD

**Issue by Ninos** [woocommerce/woocommerce#16630]
Hey there,
currently for getting related products there's no priority like category over tag. Atm category and tag id's are merged and you get all products which are related to one of this term_id:
https://github.com/woocommerce/woocommerce/blob/bdba4f76362c3b3646c775c10e87f32dd062a25c/includes/data-stores/class-wc-product-data-store-cpt.php#L1023

Normally it should be something like that:
1. Category has a higher priority than tags
2. If tag is matching to products in one of the category ids, then tag is also relevant
3. If no related product is available, do a research based on tag ids

This makes much more sense and you'll get better results for related products :-)

**Comment by mikejolley** [comment]
I don't think it is safe to assume one is more important than the other; this is going to differ between users. Luckily the query is filterable so if an extension wants to give more control over this, it's possible already.
