### ISSUE TITLE
Duplicating product and reviews

### ISSUE THREAD

**Issue by noopurk** [woocommerce/woocommerce#16643]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product duplicate of a product with reviews
2. Check for the reviews

## Expected/actual behavior

When I follow those steps, I see... that the product is duplicated but the reviews of the product are not

I was expecting to see... the duplicated product would have same reviews as the original product

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###
WC Version: 3.1.0
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

</details>

**Comment by claudiulodro** [comment]
This is intentional. Most people duplicate a product so they don't have to set everything up from scratch when creating a new product, so having the reviews duplicated is not wanted. Duplicating a product should not duplicate the reviews. See #14366

**Comment by kraken8585** [comment]
Hi, is it possible to duplicate the reviews if we want to?
