### ISSUE TITLE
WooCommerce USPS Shipping Method Plugin

### ISSUE THREAD

**Issue by bpm125** [woocommerce/woocommerce#16652]
Has anyone ever used this plugin? 

WooCommerce USPS Shipping Method Plugin 

If so, how come I never have First Class mail rate showing as an option on the checkout page?  I've checked all the services in the settings and the only options I get are Priority Mail and Priority Mail Express.  

What am I doing wrong?

**Comment by claudiulodro** [comment]
> This repository is not suitable for support. Please don't use our issue tracker for support requests, but for core, WooCommerce issues only. Support can take place through the appropriate channels:
> The WooCommerce premium support portal for customers who have purchased themes or extensions.
> Our community forum on wp.org which is available for all WooCommerce users.
> Support requests in issues on this repository will be closed on sight.
