### ISSUE TITLE
Variable Product bulk setting sales price but canceling removes all existing sales prices

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#16658]
When you select to bulk set a sales price but cancel the process on a variable product all existing sales prices on variations are removed.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create some variations on a product and put a regular price and a sales price on them all.
2. Select to update all sales prices on variations.

<img width="825" alt="rb6rvd" src="https://user-images.githubusercontent.com/1190565/29915086-9d3ec5f0-8e32-11e7-9f1d-546776046b09.png">

## Expected/actual behavior

When I follow those steps, I see all pre existing sales prices being removed.
 
**Animated Gif of test results** http://cld.wthms.co/1DLFvW

I was expecting to see all pre-existing sales prices retained.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/16660
