### ISSUE TITLE
Grouped Products Bug

### ISSUE THREAD

**Issue by arymaynart** [woocommerce/woocommerce#16650]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a Single Product with price at $100 bucks and publish it.
2. Add 2 single produtcts and publish it. First product with $80 and second with $30 bucks.
3. Edit the first single product (the $100 busck one) and make it a grouped product grouping the other two single products and update.
4. See the frotn end to be shure that its Ok.
5. Go back to dashboard and edit again the $100 bucks product.
6. Remove the grouped products from the grouped field. First the $80 product, then the $30 product and then make it a single product again and press update.

## Expected/actual behavior

When I follow those steps, I see...

When you change the product to a single one again, the price field is filled with the price when it was a single product ($100).
Even so, on the frontend the user will buy the product for one of the grouped products before ($80 or $30).

I was expecting to see...
The price of the product must be $100 bucks.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`### WordPress Environment ###

Home URL: https://www.********.com.br
Site URL: https://www.********.com.br
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 512 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - Nós recomendamos utilizar pelo menos a versão 5.6 do MySQL. Mais informações: Requerimentos do WordPress
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: mota478654_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Akismet Anti-Spam: por Automattic – 3.3.4
Cielo Loja - Solução Webservice: por Gabriel Reguly
Claudio Sanches
Paulo Vieira – 4.0.14
Contact Form 7: por Takayuki Miyoshi – 4.9
Duplicate Post: por Enrico Battocchi – 3.2
Force Regenerate Thumbnails: por Pedro Elsner – 2.0.6
Jetpack por WordPress.com: por Automattic – 5.2.1
Tradução (Loco): por Tim Whitlock – 2.0.15
Popups - WordPress Popup: por Damian Logghe – 1.7.3
Woo Mercado Pago Module: por Mercado Pago – 2.2.13
Woocommerce Correios: por Claudio Sanches – 3.4.1
Woocommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.6.0
Woocommerce: por Automattic – 3.1.2
Wordfence Security: por Wordfence – 6.3.17

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base da loja: #2520 - /loja/
Carrinho: #2433 - /carrinho/
Finalizar compra: #2434 - /finalizar-compra/
Minha conta: #2449 - /minha-conta/

### Theme ###

Name: Betheme
Version: 20.4.2
Author URL: http://muffingroup.com/
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o Loja em um tema pai. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: betheme/woocommerce/archive-product.php
betheme/woocommerce/cart/cart.php
betheme/woocommerce/cart/mini-cart.php
betheme/woocommerce/content-product.php
betheme/woocommerce/content-single-product.php
betheme/woocommerce/loop/loop-end.php
betheme/woocommerce/loop/loop-start.php
betheme/woocommerce/loop/no-products-found.php
betheme/woocommerce/loop/pagination.php
betheme/woocommerce/notices/error.php
betheme/woocommerce/notices/notice.php
betheme/woocommerce/notices/success.php
betheme/woocommerce/single-product/add-to-cart/external.php
betheme/woocommerce/single-product/product-image.php
betheme/woocommerce/single-product/product-thumbnails.php
betheme/woocommerce/single-product/sale-flash.php
betheme/woocommerce/single-product/tabs/additional-information.php
betheme/woocommerce/single-product/tabs/description.php
betheme/woocommerce/single-product/tabs/tabs.php
betheme/woocommerce/single-product/title.php

</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16651
