### ISSUE TITLE
PHP Warnings when creating a variable product programmatically

### ISSUE THREAD

**Issue by jesucarr** [woocommerce/woocommerce#16653]
I'm getting PHP warnings with Woocommerce 3.1.2 when creating a variable product programmatically:

$product = new WC_Product_Variable();
...
$parent_id = $product->save(); // This creates the warnings
// I need the parent id for to add the variations
$variation = new WC_Product_Variation();
$variation->set_parent_id( $parent_id );
...

When I follow those steps, I see in the PHP error log:
PHP Notice:  Undefined index: regular_price in .../wp-content/plugins/woocommerce/includes/class-wc-product-variable.php on line 430
PHP Notice:  Undefined index: sale_price in .../wp-content/plugins/woocommerce/includes/class-wc-product-variable.php on line 430

The problem is on the is_on_sale function, which is called on save, when trying to call the get_variation_prices function, which doesn't return the regular_price or sale_price because it still doesn't have variation products assigned.

**Comment by mikejolley** [comment]
That function does return those values. Even if there are no variations, the array keys are set here before passing to a transient. 

https://github.com/woocommerce/woocommerce/blob/48cfff4ab17a50d2667a1ca89d800c43a6fc9f8e/includes/data-stores/class-wc-product-variable-data-store-cpt.php#L214-L220

Maybe you have something else changing these values via the filter. Possibly extension.

I've adding a unit test to prove core is not at fault. The array values exist, and the ID is set without a notice being thrown. As long as that test passes, we're good.

Thanks
