### ISSUE TITLE
CART PROBLEM

### ISSUE THREAD

**Issue by kenzodailright** [woocommerce/woocommerce#16655]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
HI I HAVE A PROBLEM WITH THE CART.... AS U CAN SEE (https://www.primogroup.eu/store/carrello/) THE CART LAYOUT ISN'T GOOD AND I DON'T KNOW HOW TO DO IT BETTER....
```
</details>

**Comment by mikejolley** [comment]
If it's just styling, you need a developer/designer to customise it. If the formatting looks broken, see https://docs.woocommerce.com/document/woocommerce-shortcodes/#section-21
