### ISSUE TITLE
[3.2] Filter 'woocommerce_email_format_string_replace' not backward compatible

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#16659]
Hi,

In version 3.1, the filter `woocommerce_email_format_string_replace` passes an associative array. 

Since https://github.com/woocommerce/woocommerce/commit/28cb0909c84508b30dbae4c41ac82a4cddcb7d5e, and the call to `array_values()` the filter passes an array with numeric keys. Apart from the backward compatibility issue, we are not sure that `$this->placeholders[0]` will always be the site title.

**Comment by mikejolley** [comment]
Should be sorted in https://github.com/woocommerce/woocommerce/pull/16662
