### ISSUE TITLE
Woocommerce Form Field Radio Adjusts to the same value for all radio buttons after refresh

### ISSUE THREAD

**Issue by daudimeck** [woocommerce/woocommerce#16657]
Code to Add Radio Buttons

```
add_action('woocommerce_checkout_before_customer_details', 'eth_protduct_switch');
 
function eth_protduct_switch() {
    global $wp_query;
    global $woocommerce;
    $cart = $woocommerce->cart->get_cart();
    $currentProduct;


    foreach ($cart as $key => $cartItem) {
        $currentProduct = $cartItem['product_id'];
    }


    //get all products on subscription
    remove_action( 'pre_get_posts', 'ethnovino_pre_get' );
    $args = array(
            'post_type' => 'product',
            'posts_per_page'=> -1,
            'order'=>'DESC',
            'order_by'=>'title',

            'tax_query' => 
            array(
                array(
                'taxonomy' => 'product_cat',
                'field' => 'slug',
                'terms' => 'subscription', 
                )
            )
    );

    $groupedProducts = get_posts($args);
    echo "<div class='row checkout-subscription'><span class='slogan'>Choose your Preferred Mode</span>";
    $i=1;
    foreach($groupedProducts as $productgroup):
        echo "<div class='col".($i % 2 == 0 ? ' even':' odd')."'>
            <h4 class='title'>".$productgroup->post_title."</h4>";
            echo "<div class='row'>";
            $args = array(
                'post_type'=>'product',
                'post_parent' => $productgroup->ID,
                'posts_per_page'=>-1,
                'order'=>'ASC',
                'order_by'=>'title',
            );
            $children = get_posts($args);
            $options=array();
            foreach($children as $child):
                    $prod = wc_get_product( $child->ID );
                   $options[$child->ID] = $child->post_title.'<span class="prc">'.'<sup>'.get_woocommerce_currency().'</sup>'.$prod->get_price().' every '.ucwords(trim(str_replace('subscription','',strtolower($child->post_title)))).'</span>';

          
            endforeach;
             woocommerce_form_field(
                     'product_subscription', array(
                             'type'          => 'radio',
                             'class'         => array('input-radio'),
                             
                             'options'=> $options,
                             'required'  => true,
                    ), 
                    $currentProduct
                    );


           

        echo "</div></div>";
    $i++;
    endforeach;
    echo "</div>";
    add_action( 'pre_get_posts', 'ethnovino_pre_get' );

}
```

Before Refresh the Html Output is as below

```
<p class="form-row form-row input-radio validate-required" id="product_subscription_field"><input type="radio" class="input-radio " value="2257" name="product_subscription" id="product_subscription_2257" checked="checked">
<label for="product_subscription_2257" class="radio ">4 Months  Subscription<span class="prc"><sup>KES</sup>30000 every 4 Months</span></label>
<input type="radio" class="input-radio " value="2258" name="product_subscription" id="product_subscription_2258"><label for="product_subscription_2258" class="radio ">6 Month Subscription<span class="prc"><sup>KES</sup>35000 every 6 Month</span></label>
<input type="radio" class="input-radio " value="2261" name="product_subscription" id="product_subscription_2261"><label for="product_subscription_2261" class="radio ">12 Months Subscription<span class="prc"><sup>KES</sup>60000 every 12 Months</span></label></p>
```

After Refresh

```
<p class="form-row form-row input-radio validate-required" id="product_subscription_field"><input type="radio" class="input-radio " value="2258" name="product_subscription" id="product_subscription_2257" checked="checked">
<label for="product_subscription_2257" class="radio ">4 Months  Subscription<span class="prc"><sup>KES</sup>30000 every 4 Months</span></label>
<input type="radio" class="input-radio " value="2258" name="product_subscription" id="product_subscription_2258"><label for="product_subscription_2258" class="radio ">6 Month Subscription<span class="prc"><sup>KES</sup>35000 every 6 Month</span></label>
<input type="radio" class="input-radio " value="2258" name="product_subscription" id="product_subscription_2261"><label for="product_subscription_2261" class="radio ">12 Months Subscription<span class="prc"><sup>KES</sup>60000 every 12 Months</span></label></p>
```

Note the value change after refresh

<details>
`
### WordPress Environment ###

Home URL: http://env.dev/cellar254
Site URL: http://env.dev/cellar254
WC Version: 2.5.5
Log Directory Writable: ✔
WP Version: 4.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.22-2+ubuntu16.04.1+deb.sury.org+4
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✕ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
: 
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_termmeta: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔

### Active Plugins (48) ###

WooCommerce Wishlist Plugin: by TemplateInvaders – 1.3.2
ABD Dashboard Widget Manager: by ABD Web Design – 1.1
Custom User Contact Methods: by Remi Corson – 1.0
ITRO Popup Plugin: by ITRO Team – 5.0
MailChimp for WordPress: by ibericode – 3.1.7
Mobile Menu: by Takanakui – 2.4
Nav Menu Roles: by Kathy Darling – 1.8.6
Perth Portfolio: by aThemes – 1.0
Posts By Tag: by Sudar – 3.2
Query Posts: by Justin Tadlock – 0.3.2
Say What?: by Lee Willis – 1.7.1
Schema: by Hesham – 1.6.5
Simple MemberDeliver Form Shortcode: by wp.insider – 1.1
Simple WordPress MemberDeliver: by smp7
wp.insider – 3.2.5

Site Offline or Coming Soon: by wpecommerce – 1.6.6
Smart Slider 3: by Nextend – 3.0.31
SiteOrigin Widgets Bundle: by SiteOrigin – 1.5.6
TheBunch KE Pesapal Woocommerce: by rixeo – 1.0.3
Ultimate Coming Soon Page: by SeedProd – 1.16.0
WC Product Bundles: by Saravana Kumar K – 1.0.7
Widget Logic: by Alan Trewartha – 0.57
Woocommerce Email Verification: by Sandeep – 2.4.1
Advanced AJAX Product Filters for WooCommerce: by BeRocket – 1.1.4
Woocomerce Brands: by Proword – 0.1
Woocommerce Bulk Attribute Manager: by Varun Sridharan – 2.2.1
WooCommerce Cellar254 Customizer: by Tiplex Ltd – 1.0.0
Woocommerce CSV Import: by Allaerd Mensonides – 3.1.4
WooCommerce Customizer: by SkyVerge – 2.2.0
Woocommerce Dropdown Cart: by Phuc Pham – 2.1.1
WooCommerce Express Delivery Options: by Tiplex Ltd – 1.1.0
Fargo courier Delivery for Woocommerce: by Tom Mwenda – 1.0.0
Filter Button Widget: by  –
WooCommerce Google Analytics Integration: by WooThemes – 1.4.0
WooCommerce Guest Checkout Customized: by Tiplex Ltd – 0.0.1
WooCommerce Product Stock Alert: by WC Marketplace
The Grey Parrots – 1.3.2

WOOF - WooCommerce Products Filter: by realmag777 – 1.1.4.1
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2
WooCommerce payment reminder email: by Tom Mwenda – 0.1
WooCommerce Review Reminder: by Pixelix – 2.0.2
WooCommerce Simply Order Export: by Ankit Gade – 2.1.6
WooCommerce Stock Manager: by Vladislav Musílek – 1.0.7
WooCommerce: by WooThemes – 2.5.5
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 4.7.1
WP Clone by WP Academy: by WP Academy – 2.2.2
WP-Pro-Quiz: by Julius Fischer – 0.37
WPFront Notification Bar: by Syam Mohan – 1.7
YITH WooCommerce Subscription: by YITHEMES – 1.1.1

### Settings ###

Force SSL: –
Currency: KES (KShs)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2

### API ###

API Enabled: ✔
API Version: 3.1.0

### WC Pages ###

Shop Base: #591 - /all-wines/
Cart: #563 - /cart/
Checkout: #564 - /checkout/
My Account: #565 - /my-account/

### Taxonomies ###

Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)

### Theme ###

Name: GloballyKenyan-Ethnovino
Version: 1980.02
Author URL: http://globallykenyan.com
Child Theme: ✕ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: perth/woocommerce/archive-product.php
perth/woocommerce/cart/cart-empty.php
perth/woocommerce/cart/cart-item-data.php
perth/woocommerce/cart/cart-shipping.php
perth/woocommerce/cart/cart-totals.php
perth/woocommerce/cart/cart.php
perth/woocommerce/cart/cross-sells.php
perth/woocommerce/cart/mini-cart.php
perth/woocommerce/cart/proceed-to-checkout-button.php
perth/woocommerce/cart/shipping-calculator.php
perth/woocommerce/checkout/cart-errors.php
perth/woocommerce/checkout/form-billing.php
perth/woocommerce/checkout/form-checkout.php
perth/woocommerce/checkout/form-coupon.php
perth/woocommerce/checkout/form-login.php
perth/woocommerce/checkout/form-pay.php
perth/woocommerce/checkout/form-shipping.php
perth/woocommerce/checkout/payment-.php
perth/woocommerce/checkout/payment-method-.php
perth/woocommerce/checkout/payment-method.php
perth/woocommerce/checkout/payment.php
perth/woocommerce/checkout/review-order-.php
perth/woocommerce/checkout/review-order.php
perth/woocommerce/checkout/terms.php
perth/woocommerce/checkout/thankyou.php
perth/woocommerce/content-product.php
perth/woocommerce/content-single-product.php
perth/woocommerce/emails/customer-reset-password.php
perth/woocommerce/product-searchform.php
perth/woocommerce/single-product/add-to-cart/external.php
perth/woocommerce/single-product/add-to-cart/grouped.php
perth/woocommerce/single-product/add-to-cart/simple.php
perth/woocommerce/single-product/add-to-cart/variable.php
perth/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
perth/woocommerce/single-product/add-to-cart/variation.php
perth/woocommerce/single-product/meta.php
perth/woocommerce/single-product/price.php
perth/woocommerce/single-product/product-attributes.php
perth/woocommerce/single-product/product-image.php
perth/woocommerce/single-product/product-thumbnails.php
perth/woocommerce/single-product/rating.php
perth/woocommerce/single-product/related.php
perth/woocommerce/single-product/review.php
perth/woocommerce/single-product/sale-flash.php
perth/woocommerce/single-product/share.php
perth/woocommerce/single-product/short-description.php
perth/woocommerce/single-product/tabs/additional-information.php
perth/woocommerce/single-product/tabs/description.php
perth/woocommerce/single-product/tabs/tabs.php
perth/woocommerce/single-product/title.php
perth/woocommerce/single-product/up-sells.php
perth/woocommerce/single-product.php

### TI WooCommerce Wishlist Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
Your code is generating `$options`, not `woocommerce_form_field`. `woocommerce_form_field` will use the options you provide.

I thought it may have been our payment script which sets 'values' after a checkout refresh but I found that a) it only affects fields in the payment area and b) it has special handling for radio buttons.

Also, the area you have inserted this into (`woocommerce_checkout_before_customer_details`) does not refresh via AJAX. That area is static.

This seems to be something on your site. Since this is custom code, I cannot do in depth debugging for you. I'd suggest you look into javascript which could be setting the value after load/display. The php side (rendering) looks fine - the IDs of your inputs still use the correct IDs.

Thanks
