### ISSUE TITLE
Prompt user before deleting products

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#16676]
Reported in https://github.com/Automattic/woothemes.com/issues/2102

Since products are linked to orders, removing them can disable some functionality such as re-ordering in core. Extensions using products in orders may suffer also but in ways we don't know about.

As such, we should ensure the admin user understands that deleting a product can have side effects for existing orders, so removing from view/sale is preferred.

We can show a notice on clicking delete. We just need some useful copy.

@kloon @rodrigoprimo

**Comment by dominic-ks** [comment]
Hello, looking to get involved with Hacktoberfest! I've never contributed to anything on GitHub before so this seems like a reasonable one to start on?

Any preference as to the styling of the notice or pre-existing admin notices in Woocommerce? Can't think of any existing examples.

**Comment by mikejolley** [comment]
I think I'd be happy enough with a confirm dialog (JavaScript).
