### ISSUE TITLE
Multidimensional arrays still fails at level 3 - Rest Api queries

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#16679]
Ref: https://github.com/woocommerce/woocommerce/issues/15395

Multidimensional arrays still fails at level 3: (three dimensions)

Example of post request to http://localhost:9001/wp-json/wc/v2/products?...

**Whole url:**
`http://localhost:9001/wp-json/wc/v2/products?attributes[0][id]=1&attributes[0][name]=hfgd&attributes[0][options][0]=green&attributes[0][options][1]=yellow&attributes[0][options][2]=yuo&attributes[0][position]=1&attributes[0][variation]=true&attributes[0][visible]=false&attributes[1][id]=0&attributes[1][name]=hey&attributes[1][options][0]=he&attributes[1][options][1]=dfg&attributes[1][position]=1&attributes[1][variation]=true&attributes[1][visible]=true&backorders=no&catalog_visibility=visible&download_expiry=-1&download_limit=-1&downloadable=false&featured=false&in_stock=true&manage_stock=false&menu_order=-3&name=test2&oauth_consumer_key=ck_dc93c4ff0c9e7c383208694dd897990e45604803&oauth_nonce=Ewh9QN&oauth_signature=Q1Hwxbd4BJY9XvcEglseO45HekA=&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1504282097&oauth_version=1.0&parent_id=0&reviews_allowed=true&slug=test&sold_individually=false&status=draft&tax_status=taxable&type=simple&virtual=false`

**Params:**
```
attributes[0][id]:1
attributes[0][name]:color
attributes[0][options][0]:green
attributes[0][options][1]:yellow
attributes[0][options][2]:blue
attributes[0][position]:1
attributes[0][variation]:true
attributes[0][visible]:false
attributes[1][id]:0
attributes[1][name]:size
attributes[1][options][0]:small
attributes[1][options][1]:large
attributes[1][position]:1
attributes[1][variation]:true
attributes[1][visible]:true
backorders:no
catalog_visibility:visible
download_expiry:-1
download_limit:-1
downloadable:false
featured:false
in_stock:true
manage_stock:false
menu_order:-3
name:My-Product
oauth_consumer_key:ck_dc93c4ff0c9e7c383208694dd897990e45604803
oauth_nonce:Ewh9QN
oauth_signature:Q1Hwxbd4BJY9XvcEglseO45HekA=
oauth_signature_method:HMAC-SHA1
oauth_timestamp:1504282097
oauth_version:1.0
parent_id:0
reviews_allowed:true
slug:my_product
sold_individually:false
status:draft
tax_status:taxable
type:simple
virtual:false
```

It fails when adding attributes because it has 3 levels [0][options][0] etc...

**Response:**

> Invalid signature - provided signature does not match.

It works fine with twodimensional

@mikejolley 

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

**Comment by mikejolley** [comment]
Why is this not being POSTed?

**Comment by steffanhalv** [comment]
@mikejolley 

See #15395 - #15218 and #14987

When accessing wc-api from cross origin through browser over http, preflight is generated by browser when POST request is used with content-type application/json in header & this options request is not accepted for all servers.

But when leaving body blank with no headers, preflight is not created on POST request, and the query params is fetched Almost correctly, just not threedimensional arrays this time

**Comment by claudiosanches** [comment]
Need to check if is has been changed on WP oAuth plugin too, since we use the same codebase.

**Comment by mikejolley** [comment]
This took ages to even get to a point of trying to reproduce - unit tests would be better if you find a problem. It's a pain to setup for these edge cases, and since you have the code running already debugging would be easier from your side.

I used our PHP library, and I forced the 'get' request to use POST method, dumped the URL, and used that in my client. 

That generated something like:

```
http://local.wordpress.dev/wp-json/wc/v2/products?attributes%5B0%5D%5Bid%5D=1&attributes%5B0%5D%5Bname%5D=color&attributes%5B0%5D%5Boptions%5D%5B0%5D=green&attributes%5B0%5D%5Boptions%5D%5B1%5D=yellow&attributes%5B0%5D%5Boptions%5D%5B2%5D=blue&attributes%5B0%5D%5Bposition%5D=1&attributes%5B0%5D%5Bvariation%5D=1&attributes%5B0%5D%5Bvisible%5D=0&attributes%5B1%5D%5Bid%5D=0&attributes%5B1%5D%5Bname%5D=size&attributes%5B1%5D%5Boptions%5D%5B0%5D=small&attributes%5B1%5D%5Boptions%5D%5B1%5D=large&attributes%5B1%5D%5Bposition%5D=1&attributes%5B1%5D%5Bvariation%5D=1&attributes%5B1%5D%5Bvisible%5D=1&backorders=no&catalog_visibility=visible&download_expiry=-1&download_limit=-1&downloadable=0&featured=0&in_stock=1&manage_stock=0&menu_order=-3&name=My-Product&oauth_consumer_key=ck_5d91ee8380f1b6e8dbc210d818654b499b1ebc77&oauth_nonce=fc6b32aa9931e76814feb020a645902845f21217&oauth_signature=BZmnqUEK7Ixb3yePioMsWVGtK6ogjd3VazpcdtGUKDY%3D&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1504672393&parent_id=0&reviews_allowed=1&slug=my_product&sold_individually=0&status=draft&tax_status=taxable&type=simple&virtual=0
```

At first I had signature errors on localhost because I was forcing http on a site configured for https (fixed here https://github.com/woocommerce/woocommerce/pull/16743), but then I found that I wasn't normalising my params correctly.

From the docs:

> These values need to be encoded into a single string which will be used later on. The process to build the string is very specific:

https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

Once I used strings for bools and ints, the request worked and the signatures matched. The array did not break. It's handled correctly and matches https://github.com/WP-API/OAuth1

🐰

**Comment by steffanhalv** [comment]
Thx, I will try this out!
