### ISSUE TITLE
Price value in filter wc_price off by factor 1000 

### ISSUE THREAD

**Issue by Drivingralle** [woocommerce/woocommerce#16674]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Setup WooCommerce to use Indonesian rupiah (Rp)
2. Setup WooCommerce to use . as decimal separator
3. Setup WooCommerce to use , as thousand separator
4. Add a product with a price like RP 400000 or RP 4000000 
5. Open `/woocommerce/includes/wc-formatting-functions.php`, go to method `wc_price()`
6. Add logging to the top of the method for $price
7. Add logging to to bottom next to the filter `wc_price`. To monitor `$price * 1 ` or `floatval( $price )` or `intval( $price )`

## Expected/actual behavior
When I follow those steps, I see that the value passed into the filter by $price is a string and as PHP (auto) converts it back to a float/int the value is off by factor 1000. 
The real price 400000 is now just 400. 

![bildschirmfoto 2017-09-01 um 14 05 55](https://user-images.githubusercontent.com/1727269/29969051-bc7d2064-8f1e-11e7-8dfa-c39365c42ef2.jpg)

I was expecting to see that the price passed into the filter at the end of the method is a reliable float/int value, to allow plugins to hook into the filter and run custom calculations based on the price or replace the output completely.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
WP: 4.8.1
WC: 3.1.2
PHP: 7.0.20
Apache on DomainFactory and Apache on diff. MAMP Setups
</details>

**Comment by Drivingralle** [comment]
Behavior also shows up on one of my test setups using € and price format 1.000,00 for a cost of one thousand.

**Comment by mikejolley** [comment]
The bug is in your logging, not the function.

You are logging the value AFTER we have used number_format. The value when you `*1` or convert to float is `400,000` so yes, if you convert that to int it will be 400.  This function deals with strings and is working as expected.

**Comment by Drivingralle** [comment]
And the filter at the end of the method should enable plugins to overwrite the whole `$return` string with custom code. Or not?

To do that I need the price as a float/int not a formatted string.

**Comment by mikejolley** [comment]
Maybe I misunderstood your report. If thats the case though, the arg the function accepts should be $raw_price and none of the other code should change it. I think in your PR you passed it through the raw_woocommerce_price filter.

**Comment by Drivingralle** [comment]
I tried to save on creating an extra var just to save the float/int to pass it into the filter later.

I'll try to create a new PR. That makes it more clear.

**Comment by Drivingralle** [comment]
Attached new PR
