### ISSUE TITLE
Postcodes are not updated on checkout page after editing them on My Account page

### ISSUE THREAD

**Issue by CasperBraske** [woocommerce/woocommerce#16671]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install WC as usual
2. Create a test user with a sample postcode (say _15000-000_)
3. Add a product to the cart
4. Proceed to checkout (your postcode should be the same as provided in your addresses list)
5. Go back to your account page and change your postcode to _16000-000_ or whatever is different from _15000-00_
6. Repeat step 4

## Expected/actual behavior

When I follow those steps, I see that the postcode on the checkout form is _15000-000_.

I was expecting to see the postcode on the checkout form as _16000-000_.

My Account page:
![screenshot-2017-9-1 my account woocommerce test](https://user-images.githubusercontent.com/700448/29959669-ceed2622-8ece-11e7-9a5c-a5e21969d483.png)

Checkout form:
![screenshot-2017-9-1 checkout woocommerce test](https://user-images.githubusercontent.com/700448/29959668-ce81465a-8ece-11e7-824b-e23904f11eed.png)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://wootest
Site URL: http://wootest
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.22-0ubuntu0.16.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/16500
https://github.com/woocommerce/woocommerce/issues/16436

If you really did test master as your report stated, please let me know..

**Comment by CasperBraske** [comment]
Right. Thanks. For some reason I misinterpreted the "master" part.
It's working fine now _using the "real master branch" not the latest version from the WP repo_.

As a side note, maybe you could add a small observation on that and also removing the space in the check boxes. I saw many people using it like `[ x]` or `[x ]`.

Best regards.

**Comment by mikejolley** [comment]
Github doesn't format as a checkbox without the space :(
