### ISSUE TITLE
Cyrillic Arrtibute Name in Attribute Archive URL

### ISSUE THREAD

**Issue by dido76bg** [woocommerce/woocommerce#16673]
Hi,

When I enter a name slug with cyrillic characters the link to product arrchive page leads to global archive page and when it is entered with latin characters every thing works fine.

Is it possible to point a sollution.

See the image for more details.

Thank you!
![woosample](https://user-images.githubusercontent.com/31537121/29969246-ebd6be52-8f27-11e7-983c-97d6f6210ea2.jpg)

**Comment by claudiosanches** [comment]
Can you paste the attribute and slug name?
So I can copy and try reproduce the issue.

**Comment by dido76bg** [comment]
Hi,

Thank you for your answer.

Term Name for example : Био Сертификат -> the translation in EN is "Organic
Certificate"

Term Slug : био-сертификат

You can try it with one word attribute name, but the result is the same.

Thank you once again.

**Comment by mikejolley** [comment]
This is a WordPress core issue. I've logged here and submitted a patch: https://core.trac.wordpress.org/ticket/41791

Thanks
