### ISSUE TITLE
wc_get_orders, date filter not working as expected

### ISSUE THREAD

**Issue by 1manfactory** [woocommerce/woocommerce#16683]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

```
$args = array(
    'date_paid' => '2017-09-02',
);
$orders = wc_get_orders( $args );
print_r($orders[0]->get_date_paid());
```
gives me this

```
WC_DateTime Object
(
    [utc_offset:protected] => 0
    [date] => 2017-09-01 19:36:20.000000
    [timezone_type] => 3
    [timezone] => Europe/Berlin
)
```

## Expected/actual behavior

As you can see: the filter date does not fit with the returned date.

This is bad because I really depend on a reliable date filter as I need this to fill my custom monthly reports.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://masch1/null-papier.de
Site URL: http://masch1/null-papier.de
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE_formal

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.0.19-1
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Ihr Shop benutzt kein HTTPS. Erfahren Sie mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ❌Fehlermeldungen sollten Besuchern nicht angezeigt werden.

### Active Plugins (18) ###

Autoptimize: von Frank Goossens (futtta) – 2.2.2
Comet Cache: von WebSharks
Inc. – 170220

Contact Form 7: von Takayuki Miyoshi – 4.8
Cookie Notice: von dFactory – 1.2.38
Language Fallback: von Bernhard Kau – 1.0.3
Loco Translate: von Tim Whitlock – 2.0.14
Newsletter: von Stefano Lissa & Das Newsletter Team  – 4.9.8
Null Papier Tools: von Jürgen Schulze – 1
Popup Maker: von WP Popup Maker – 1.6.3
Recent Posts Widget Extended: von Satrya – 0.9.9.6
Related Posts for WordPress: von Never5 – 2.0.0
Remote Bypass API: von Jürgen Schulze (1manfactory.com) – 0.6.1
Responsive Menu: von Peter Featherstone – 3.1.4
Search & Replace: von Inpsyde GmbH – 3.1.2
WooCommerce Wishlist Plugin: von TemplateInvaders – 1.3.4
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 1.6.5
WooCommerce: von Automattic – 3.1.2
WP-Mail-SMTP: von Callum Macdonald – 0.10.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop-Basis: #2871 - /?page_id=2871
Warenkorb: #2738 - /?page_id=2738
Kasse: #2739 - /?page_id=2739
Mein Konto: #2740 - /?page_id=2740

### Theme ###

Name: Virtue Premium Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Virtue - Premium
Parent Theme Version: 4.3.1
Parent Theme Author URL: https://www.kadencethemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: virtue_premium/woocommerce/archive-product.php
virtue_premium-child/woocommerce/checkout/thankyou.php
virtue_premium/woocommerce/content-product.php
virtue_premium/woocommerce/content-product_cat.php
virtue_premium/woocommerce/content-single-product.php
virtue_premium-child/woocommerce/emails/customer-on-hold-order.php
virtue_premium-child/woocommerce/emails/email-header.php
virtue_premium-child/woocommerce/emails/email-styles.php
virtue_premium/woocommerce/loop/loop-end.php
virtue_premium/woocommerce/loop/loop-start.php
virtue_premium/woocommerce/loop/rating.php
virtue_premium/woocommerce/loop/sale-flash.php
virtue_premium-child/woocommerce/myaccount/orders.php
virtue_premium-child/woocommerce/order/order-details-item.php
virtue_premium/product-searchform.php
virtue_premium/woocommerce/single-product/add-to-cart/external.php
virtue_premium/woocommerce/single-product/add-to-cart/grouped.php
virtue_premium/woocommerce/single-product/add-to-cart/simple.php
virtue_premium/woocommerce/single-product/add-to-cart/variable.php
virtue_premium/woocommerce/single-product/product-image.php
virtue_premium/woocommerce/single-product/product-thumbnails.php
virtue_premium/woocommerce/single-product/related.php
virtue_premium/woocommerce/single-product/sale-flash.php
virtue_premium/woocommerce/single-product/title.php
virtue_premium/woocommerce/single-product/up-sells.php
virtue_premium/woocommerce/single-product.php
virtue_premium/woocommerce/taxonomy-product_cat.php
virtue_premium/woocommerce/taxonomy-product_tag.php


### TI WooCommerce Wishlist Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#date

See site timezone vs UTC timestamp notes.

**Comment by 1manfactory** [comment]
Sorry, I don't see this as a closed issue.

I solved the problem now with calculating unix timestamps as borders.

But when I use a daily filter I expect it to work on the stored date inside the database which is the date I use in my shop and not any other time zone.

As I said: **filter does not fit with filtered objects**, hence this is an error.

**Comment by mikejolley** [comment]
@1manfactory If you see the link I posted, it states that timestamps are treated as UTC, and string based dates are treated in local timezone. So if you view the date object you're viewing UTC, not site timezone, so it won't match depending on your query.

**Comment by majidparan** [comment]
[طراحی سایت در شیراز](http://aracode.ir)
my woocommerce order page go to white screen after click on filter button :(

**Comment by RubiousShaun** [comment]
I too am having this issue and your response doesn't really help.

How do I format this query to get orders from today (in my timezone)? It currently returns orders from the day before!

    $args = array(
        'date_completed' => '2018-06-06',
    );
    $orders = wc_get_orders( $args );

**Comment by finzend** [comment]
As @FellowshipAgency commented, this issue is still not resolved, it consequently returns the orders a day before the given date. I'm also using YYYY-MM-DD and it should be the site timezone.

**Comment by badpenguin** [comment]
> @1manfactory If you see the link I posted, it states that timestamps are treated as UTC, and string based dates are treated in local timezone. So if you view the date object you're viewing UTC, not site timezone, so it won't match depending on your query.

It does not work using YYYY-MM-DD...YYYY-MM-DD return the wrong days.
Also it does not seems a problem related to timezone, I've got order listed outside of the boundary of the difference between localtime and UTC.
I've to check WC code but from what I observe from the outside the dates are just converted to the wrong day before been used for a comparison.

**Comment by teledirigido** [comment]
Same problem here: Even doing UTC or YYYY-MM-DD...YYYY-MM-DD. `wc_get_orders` retrieves wrong orders

**Comment by fmerlat-choosit** [comment]
For me, neither YYYY-MM-DD...YYYY-MM-DD nor YYYY-MM-DD work for my date_paid data.
Any idea ?

**Comment by srikanthkoneru** [comment]
Still not working, I used the dates from that url posted :

```
$args = array(
    'date_completed' => '1494971177...1494938777',
);
$orders = wc_get_orders( $args )
```

which is the year 2017 and I get all orders in the newly created test shop.
