### ISSUE TITLE
Cannot Map Custom Taxonomies

### ISSUE THREAD

**Issue by fahaddsheikh** [woocommerce/woocommerce#16689]
I have a custom taxonomy for products by the name suppliers. When I import through csv there is no way to map this custom taxonomy just like there is for categories and tags...

**Comment by mikejolley** [comment]
If you have a custom taxonomy not part of core, you need to include support in the importer for it. See https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Importer-&-Exporter#adding-custom-import-columns-developers

**Comment by vincenzoquarta** [comment]
Hi, 
I have the same problem.
where I have to add code this code?
Thanks.

**Comment by mikejolley** [comment]
We don't provide custom code here.
