### ISSUE TITLE
Payment remeinder for PayPal

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#16688]
Sometime payment through paypal is not processed imidiatly.
WC IPN says the follow:
`Payment pending: echeck Order status changed from Pending Payment to On Hold.`

I have many customers such as this and when i spoke to some of them they were unaware of the issue.
Is it possible that WC will send this customers a message letting them know that PayPal did not approve their payment and they should speak with paypal about it?

Weirdly WC send this customers invoice ("Thank you for your order" - "Your order has been received and is now being processed. Your order details are shown below for your reference:") when they complete the purchase regardless if the IPN said that the payment is completed... This is what causes the confusion.... the customer thinks that everything is OK but in fact no payment was received.

Please add a fix to let the customer know that there was an issue with this payment and he should speak with PayPal to solve it.

**Comment by mikejolley** [comment]
On-hold payment is not your customers responsibility to check, it's yours. Read the order notes, and view orders by status.

**Comment by UserName011** [comment]
@mikejolley The on hold is WC status.. The payment status in PayPal is "Pending" this happens because the payment card or check is not verified.. it can take up to 30 days for paypal to process it but if customer contact paypal they can handle it faster. However this is not the issue. The issue is that the customer receive email from WC that says "Thank you for your order" - "Your order has been received and is now being processed. Your order details are shown below for your reference:"   Nothing in this email mention payment problem!  More than one of my costumers contact me with question about "why the item was not shipped" they were completely unaware of the payment problem.

**Comment by mikejolley** [comment]
You can contact customers if payment is on-hold. I don't think we can make a generic enough email to meet all possibly cases of a payment on hold. It won't be useful.

On-hold can be triggered for multiple reasons, such as mismatch in totals. Thats not the customers problem.

**Comment by UserName011** [comment]
True... but you can prevent sending confirmation emails that the order is accepted if the payment isn't completed... 

May I also suggest that if that is the case maybe you should consider breaking On Hold to more than one status.... I think that status of "Paid - Await confirmation" can be helpful here... then you can  create a mail template relevant for these cases where customer payed but the payment was not completed. 

You should note that some stores handle 1000+ orders per day.. it's very hard to go through all the "On Hold" statuses...

**Comment by mikejolley** [comment]
We want to break the statuses into payment and fulfilment, but it's a major change which needs to wait for a major update.

**Comment by UserName011** [comment]
@mikejolley  Major as in 4.x.x?

**Comment by claudiosanches** [comment]
@UserName011Major as `4.0.0`.
