### ISSUE TITLE
Woo Bug?  Or?  In stock indicator not changing when stock = 0

### ISSUE THREAD

**Issue by elephantusa** [woocommerce/woocommerce#16684]
Hi.  I am not a coder :-(   But I can't seem to get any woosupport.  I was wondering if anyone knew about this issue.  

I used to get emails when my stock ran to 0. I do not get them. That maybe me wonder. Also, when someone buys something on my site, and the inventory runs to zero, the in stock label remains on the product page and the product shows still in stock on the product page, even though the quantity is zero. I have tried making some sample products, to test the issue I get the same issue.   Obviously, a big issue when trying to run a store.

Any ideas or steps I could try?

I am running the most current version of Woo.

My options for inventory are

Manage stock?

Enable stock management at product level YES

Stock quantity I SET THIS TO 1 FOR MY PRODUCTS SINCE I ONLY HAVE ONE OF EACH

Allow backorders? NO

Stock status THIS DOES NOT CHANGE WHEN A PURCHASE IS COMPLETE.

Sold individually Enable this to only allow one of this item to be bought in a single order THIS IS CURRENTLY CHECKED

Any ideas? Very strange.

### WordPress Environment ###

Home URL: https://www.elephantartgallery.com
Site URL: https://www.elephantartgallery.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.22-0ubuntu0.16.04.1
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Redux Framework: by Team Redux – 3.6.5
BackupBuddy: by iThemes – 8.0.0.3
CMB2: by WebDevStudios – 2.2.4
Contact Form 7: by Takayuki Miyoshi – 4.9
Content Views: by PT Guy – 1.9.9.1
Custom Sidebars: by WPMU DEV – 3.0.9
Duplicate Page: by mndpsingh287 – 2.3
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.1.0
Envato Market: by Derek Herman – 1.0.0-RC2
Essential Grid: by ThemePunch – 2.1.5.1
EWWW Image Optimizer: by Shane Bishop – 3.6.1
Facebook for WooCommerce: by Facebook – 1.4.2
Finale - WooCommerce Sales Countdown Timer & Discount Plugin: by XLPlugins – 1.2.0
GetBowtied Tools: by GetBowtied – 2.0.1
Google Analytics: by ShareThis – 2.1.3
Hello Dolly: by Matt Mullenweg – 1.6
Hide Title: by Brandon Kraft & Randall Runnels – 1.0.4
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.2
Layered Popups: by Halfdata
Inc. – 5.90

MailChimp for WooCommerce: by MailChimp – 2.0.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SEO Friendly Images: by Vladimir Prelovac – 3.0.5
Ultimate Posts Widget: by Boston Dell-Vandenberg – 2.0.6
WooCommerce Display Products by Tags: by Sebs Studio – 1.0.0
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3
WooCommerce Pretty Emails: by MB Création – 1.8.3
WooCommerce Product Add-ons: by Automattic – 2.7.26 – 2.9.0 is available
WooCommerce - ShipStation Integration: by WooThemes – 4.1.7 – 4.1.18 is available
WooCommerce: by Automattic – 3.1.2
Yoast SEO: by Team Yoast – 5.3.3
WP All Import Pro: by Soflyy – 4.4.9
WP Hide Title: by Riyad Arefin – 0.1.1
WP-Mail-SMTP: by Callum Macdonald – 0.10.1
WP Meta and Date Remover: by Prasad Kirpekar – 1.5
WP Product Feed Manager: by Michel Jongbloed – 1.6.1
WP Recent Posts From Category: by Daniele De Santis – 1.1.0
WP Rocket: by WP Media – 2.10.6
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.7
YITH WooCommerce Gift Cards Premium: by YITHEMES – 1.6.13
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /paintings/
Cart: #724 - /cart-3/
Checkout: #2767 - /checkout-3/
My account: #730 - /my-account-3/

### Theme ###

Name: The Retailer
Version: 2.7.1
Author URL: https://www.getbowtied.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: theretailer/woocommerce/archive-product.php
theretailer/woocommerce/content-product.php
theretailer/woocommerce/content-product_cat.php
theretailer/woocommerce/content-single-product.php
theretailer/woocommerce/global/breadcrumb.php
theretailer/woocommerce/loop/orderby.php
theretailer/woocommerce/loop/price.php
theretailer/woocommerce/loop/result-count.php
theretailer/woocommerce/myaccount/form-login.php
theretailer/woocommerce/order/form-tracking.php
theretailer/woocommerce/single-product/price.php
theretailer/woocommerce/single-product/product-image.php
theretailer/woocommerce/single-product/product-thumbnails.php
theretailer/woocommerce/single-product/rating.php
theretailer/woocommerce/single-product/related.php
theretailer/woocommerce/single-product/short-description.php
theretailer/woocommerce/single-product/tabs/description.php
theretailer/woocommerce/single-product/tabs/tabs.php
theretailer/woocommerce/single-product/title.php
theretailer/woocommerce/single-product/up-sells.php
theretailer/woocommerce/single-product.php

`

**Comment by opportus** [comment]
That bug might be introduced by one of your plugins. Try deactivating WC related plugins one after the other and check if the bug is still present.

**Comment by elephantusa** [comment]
I did troubleshoot this and found that the WooCommerce plug in - **Product Add-ons** was causing the issue.  When disabled I have no inventory issue.  Does anyone know if this is a problem for other users?

**Comment by elephantusa** [comment]
I did troubleshoot this and found that the WooCommerce plug in - **Product Add-ons** was causing the issue.  When disabled I have no inventory issue.  Does anyone know if this is a problem for other users?

**Comment by elephantusa** [comment]
I did troubleshoot this and found that the WooCommerce plug in - **Product Add-ons** was causing the issue.  When disabled I have no inventory issue.  Does anyone know if this is a problem for other users?

**Comment by opportus** [comment]
You should post this question on the plugin's support forum. Here is for WooCommerce.

**Comment by mikejolley** [comment]
Product addons is premium, so login to your account and ask here https://woocommerce.com/my-account/tickets/ Note you have an old version installed too - update first.
