### ISSUE TITLE
Setup packagist.org GitHub hooks so packagist.org can automatically keep updated

### ISSUE THREAD

**Issue by pmgarman** [woocommerce/woocommerce#16686]
Today is 9/2, https://packagist.org/packages/woocommerce/woocommerce shows that it was last updated on 8/15. This means 3.2 beta 1 isn't showing up as a version for composer because packagist doesn't know it exists.

If packagist is going to be connected and used, may as well keep it updated :)

![](http://c.pmgr.mn/OuyAF9+)

**Comment by mikejolley** [comment]
It's there now.. wasn't me.
