### ISSUE TITLE
how to support the cart functionality using the woocommerce rest api

### ISSUE THREAD

**Issue by venkatTammareddy** [woocommerce/woocommerce#16695]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
> how to support the cart functionality using the woocommerce rest api

Build it from scratch :) Because we don't offer this functionality in the REST API.

**Comment by claudiosanches** [comment]
You can store sessions on your app and use the orders endpoint after checkout.
