### ISSUE TITLE
Backend: WooCommerce Add Order - add Products not working

### ISSUE THREAD

**Issue by Maragoo** [woocommerce/woocommerce#16693]
Hi

When adding manually an order in the backend, then currently no prodcucts can be added to the order as instead of the search box, there is only a empty drop down box popping up.
In the last versions there products could be searched by text.

Best regards
Rolf

**Comment by mikejolley** [comment]
It's this https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x
