### ISSUE TITLE
Order Failed Notification for Customers

### ISSUE THREAD

**Issue by doshisahil95** [woocommerce/woocommerce#16697]
Hi,

Im trying to figure out how to send an order failed notification to customers. Currently, woocommerce only sends it to the admin. 

I tried changing the class-wc-email-failed-order.php and add the customer email in the recepients. That didnt work

Tried adding another custom email into woocommerce, but it doesnt send to the customers, rather sends to the admin.

Any other ideas?

Thanks

**Comment by mikejolley** [comment]
Why do you need to email a customer? They will be on site doing the payment when it fails; thats why WC core does not send an email out for this event.

It's possible to listen for the `woocommerce_order_status_pending_to_failed` action and send an email at that point, but I don't have an example code snippet for you. You'll need a developer if no pre-made solutions exist.

Thanks
