### ISSUE TITLE
Purchase note column's colspan attribute

### ISSUE THREAD

**Issue by cyrildc** [woocommerce/woocommerce#16698]
In the templates/order/order-details-item.php file, the colspan attribute for the purchase note should be 2 instead of 3 as there are only 2 columns in the table. Currently, it can break the table design depending on the css styling.
```
<tr class="woocommerce-table__product-purchase-note product-purchase-note">
<td colspan="2"><?php echo wpautop( do_shortcode( wp_kses_post( $purchase_note ) ) ); ?></td>
</tr>
```

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/16701
