### ISSUE TITLE
Make /wp-json/wc/v2/customers/<id>/downloads editable

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#16691]
The REST API v2 customers downloads endpoint:

/wp-json/wc/v2/customers/<id>/downloads

is currently read-only. We need the ability to edit the 'Downloads remaining' and 'Access expires' values for individual customer downloads and cannot currently do this via the REST API.

**Comment by mikejolley** [comment]
Logged here https://github.com/woocommerce/wc-api-dev/issues/49 Feel free to contribute it.
