### ISSUE TITLE
Conflict- woocommerce order section bug...

### ISSUE THREAD

**Issue by dreamesper** [woocommerce/woocommerce#16704]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

System statusToolsLogsSystem status
Please copy and paste this information in your ticket when contacting support:
Get system report Understanding the status report
WordPress environment
Home URL:		https://dreamesper.com
Site URL:		https://dreamesper.com
WC version:		3.2.0
Log directory writable:		/home/content/p3pnexwpnas12_data02/46/3796746/html/wp-content/uploads/wc-logs/
WP version:		4.8.1
WP multisite:		–
WP memory limit:		256 MB
WP debug mode:		–
WP cron:		
Language:		en_US
Server environment
Server info:		Apache
PHP version:		5.6.30
PHP post max size:		65 MB
PHP time limit:		30
PHP max input vars:		1000
cURL version:		7.45.0, OpenSSL/1.0.1e
SUHOSIN installed:		–
MySQL version:		5.6.32
Max upload size:		64 MB
Default timezone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
WC database version:		3.2.0
Database prefix	 	wp_akyx8yatq1_
MaxMind GeoIP database:		/home/content/p3pnexwpnas12_data02/46/3796746/html/wp-content/uploads/GeoIP.dat
Total Database Size	 	4.37MB
Database Data Size	 	0.77MB
Database Index Size	 	5.14MB
wp_akyx8yatq1_woocommerce_sessions	 	Data: 1.02MB + Index: 0.02MB
wp_akyx8yatq1_woocommerce_api_keys	 	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_attribute_taxonomies	 	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_woocommerce_downloadable_product_permissions	 	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_order_items	 	Data: 0.02MB + Index: 0.01MB
wp_akyx8yatq1_woocommerce_order_itemmeta	 	Data: 0.11MB + Index: 0.09MB
wp_akyx8yatq1_woocommerce_tax_rates	 	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_woocommerce_tax_rate_locations	 	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_shipping_zones	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_shipping_zone_locations	 	Data: 0.02MB + Index: 0.05MB
wp_akyx8yatq1_woocommerce_shipping_zone_methods	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_payment_tokens	 	Data: 0.02MB + Index: 0.02MB
wp_akyx8yatq1_woocommerce_payment_tokenmeta	 	Data: 0.02MB + Index: 0.03MB
wp_akyx8yatq1_woocommerce_log	 	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_commentmeta	 	Data: 0.02MB + Index: 0.01MB
wp_akyx8yatq1_comments	 	Data: 0.04MB + Index: 0.03MB
wp_akyx8yatq1_links	 	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_nf3_actions	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_action_meta	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_fields	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_field_meta	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_forms	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_form_meta	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_objects	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_object_meta	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_relationships	 	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_options	 	Data: 2.11MB + Index: 0.06MB
wp_akyx8yatq1_postmeta	 	Data: 0.67MB + Index: 0.31MB
wp_akyx8yatq1_posts	 	Data: 0.09MB + Index: 0.05MB
wp_akyx8yatq1_termmeta	 	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_terms	 	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_term_relationships	 	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_term_taxonomy	 	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_usermeta	 	Data: 0.01MB + Index: 0.01MB
wp_akyx8yatq1_users	 	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_yith_wcwl	 	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_yith_wcwl_lists	 	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_yoast_seo_links	 	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_yoast_seo_meta	 	Data: 0.00MB + Index: 0.00MB
Post Type Counts
al_product	 	1
attachment	 	101
jetpack_migration	 	2
nav_menu_item	 	6
owl-carousel	 	1
page	 	15
post	 	1
product	 	46
product_variation	 	4
revision	 	55
shop_order	 	107
shop_order_refund	 	16
woocarousel	 	1
Security
Secure connection (HTTPS):		
Hide errors from visitors		
Active plugins (26)
WooCommerce added to cart popup (Ajax)	 	by XootiX – 1.3 – Not tested with the active version of WooCommerce
Akismet Anti-Spam	 	by Automattic – 3.3.4
CMB2	 	by CMB2 team – 2.2.5.3
Comet Cache	 	by WebSharks, Inc. – 170220
Contact Widgets	 	by GoDaddy – 1.4.1
DHL (BASIC) WooCommerce Extension	 	by XAdapter – 1.1.16 – Not tested with the active version of WooCommerce
PayPal Express Checkout for WooCommerce	 	by wpgateways – 2.0.2 – Not tested with the active version of WooCommerce
FedEx WooCommerce Extension (BASIC)	 	by XAdapter – 2.0.8 – Not tested with the active version of WooCommerce
GoDaddy Email Marketing	 	by GoDaddy – 1.2.0
Google Analytics for WordPress by MonsterInsights	 	by MonsterInsights – 6.2.2
Kirki Toolkit	 	by Aristeides Stathopoulos – 3.0.9
Ninja Forms	 	by The WP Ninjas – 3.1.9
WooCommerce Product Carousel Slider	 	by ADL Plugins – 2.1 – Not tested with the active version of WooCommerce
Storefront Sticky Add to Cart	 	by WooThemes – 1.1.6
Woo Empty Cart Button	 	by WPCodelibrary – 1.0.2
USPS (BASIC) WooCommerce Shipping	 	by XAdapter – 1.1.13 – Not tested with the active version of WooCommerce
Woocommerce Dropdown Cart	 	by Phuc Pham – 2.1.1 – Not tested with the active version of WooCommerce
WooCommerce Amazon Pay Gateway	 	by WooCommerce – 1.7.3 – Not tested with the active version of WooCommerce
WooCommerce Services	 	by Automattic – 1.7.0 – Not tested with the active version of WooCommerce
WooCommerce Shortcodes	 	by WooThemes, Claudio Sanches – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce	 	by Automattic – 3.2.0-beta.1
Yoast SEO	 	by Team Yoast – 5.3.3
WP101 Video Tutorials	 	by WP101Plugin.com – 0.3
YITH WooCommerce Compare	 	by YITHEMES – 2.2.1 – Not tested with the active version of WooCommerce
YITH WooCommerce Quick View	 	by YITHEMES – 1.2.1 – Not tested with the active version of WooCommerce
YITH WooCommerce Wishlist	 	by YITHEMES – 2.1.2 – Not tested with the active version of WooCommerce
Settings
API enabled:		
Force SSL:		
Currency		USD ($)
Currency position		left
Thousand separator		,
Decimal separator		.
Number of decimals		2
Taxonomies: Product types		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WC pages
Shop base:		#5 - /shop/
Cart:		#6 - /cart/
Checkout:		#7 - /checkout/
My account:		#8 - /my-account/
Terms and conditions:		 Page not set
Theme
Name:		Alpha Store
Version:		1.4.0
Author URL:		http://themes4wp.com
Child theme:		 – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce support:		
Templates
Archive template:	 	Your theme has a woocommerce.php file, you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides:	 	–

**Comment by dreamesper** [comment]
I have just updated to the latest beta woocommerce version... unfortunately, the bug still exists.

Urgent isnt even the word im looking to describe to anyone willing to help since i cannot access customer information through their orders, etc.

Thanks!

**Comment by mikejolley** [comment]
> This bug happens with only WooCommerce plugin active

This is pretty important. This is most likely a plugin conflict because a bug in all versions would affect all users.

Please carry out troubleshooting steps before logging issues. If when all plugins are off, and the default WP theme is active, it still happens, take a new system status report, and see if you can find error logs on the server. Post back with that and I'll reopen this.
