### ISSUE TITLE
Cut Text In Variations Tab

### ISSUE THREAD

**Issue by Umangvaghela** [woocommerce/woocommerce#16706]
**Cut Text In Variations Tab**

![screenshot-1](https://user-images.githubusercontent.com/26810472/30050788-4f83e778-923d-11e7-877b-a6e63a51a990.png)

**Comment by Umangvaghela** [comment]
Add padding 6px to 5px.

.form-row input[type=number], .form-row input[type=text], .form-row select, .form-row textarea {
    width: 100%;
    vertical-align: middle;
    margin: 2px 0 0;
    padding: 5px;
}

**Comment by claudiosanches** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/16712

**Comment by Umangvaghela** [comment]
@claudiosanches 
 
Hello claudiosanches in variation tab regular price is required.If not so We can remove it in regular price text field.

Thanks

Umang
