### ISSUE TITLE
Liechtenstein: "Calculate shipping" in the cart doesn't hide/change the State field to Municipality

### ISSUE THREAD

**Issue by danieldudzic** [woocommerce/woocommerce#16727]
On the Checkout page, when you select "Liechtenstein" it changes the "State Field" to "Municipality".

Is there a reason why the same thing isn't happening in the Cart?

**Checkout:**
![checkout](https://cldup.com/v-PTqZhDZq.png)

**Cart:**
![checkout](https://cldup.com/3fz873Ei0I.png)

**Comment by masteradhoc** [comment]
+1 for a bugfix ;)
