### ISSUE TITLE
Editing an order using the legacy API on WooCommerce 3.0+ overwrites the order currency

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#16736]
## Issue description
Calling the legacy API to edit an order, for example to change its status, has the side effect of replacing the order currency with whatever currency is active when the API operation is performed. This is more evident in multi-currency configurations, but it happens even in "vanilla" setups (it's simply harder to spot, because there is only one currency).

A second side effect of this issue is that trying to change the order currency via the legacy API doesn't work, as the new currency is overwritten by the API, which still takes the active one.

## Affected versions
This issue occurs only with the legacy API, and only in WooCommerce 3.0 or later. The new API, or the legacy API in WooCommerce 2.6 and earlier are not affected.

### Preparation
**Note**: no need to install a multi-currency solution.
1. In WooCommerce > Settings, set the WooCommerce currency to **USD**.
2. Create an order. The products and amounts are unimportant.
3. The order list should show the order, with the currency being **USD**.
4. In WooCommerce > Settings, set the WooCommerce currency to GBP.

### How to trigger the issue of currency changing unexpectedly
Using the legacy API, change the order status to "completed".
~~~
curl -X PUT \
  'https://example.org/wc-api/v2/orders/123?consumer_key=<consumer key>&consumer_secret=<consumer secret>' \
  -H 'content-type: application/json' \
  -d '{ "order": { "status": "completed" } }'
~~~

**Expected result**: order status changes to "_completed_".
**Actual result**: order status changes to "_completed_" and its currency changes to GBP (i.e. the currency active when the API call was made).

### How to trigger the issue of currency setting being ignored.
Using the legacy API, try to change the order currency back to **USD**.
~~~
curl -X PUT \
  'https://example.org/wc-api/v2/orders/123?consumer_key=<consumer key>&consumer_secret=<consumer secret>' \
  -H 'content-type: application/json' \
  -d '{ "order": { "currency": "USD" } }'
~~~

**Expected result**: order currency changes to USD.
**Actual result**: order currency remains GBP.

## Cause
The cause is to be found in the legacy API that has been updated to work in WooCommerce 3.0+. The flow is the following:
1. Editing an order calls method `WC_API_Orders::edit_order()`. This method checks if a currency was passed with the request, as it happens in our second test. If there is a currency, the method saves it agains the order (but it will be overwritten anyway, see below).
2. That method calls function `wc_update_order()`
3. The function calls `wc_create_order()`, which contains the following code:
~~~
// Update other order props set automatically
$order->set_currency( get_woocommerce_currency() );
$order->set_prices_include_tax( 'yes' === get_option( 'woocommerce_prices_include_tax' ) );
$order->set_customer_ip_address( WC_Geolocation::get_ip_address() );
$order->set_customer_user_agent( wc_get_user_agent() );
$order->save();
~~~

The call to `$order->set_currency()` takes the **active** currency, which is not necessarily the one from the order. This overwrites the original order currency, and even the one passed explicitly with the API call.

In a single-currency system, this bug may go unnoticed, because, normally, the order currency and the active currency are the same. However, if the currency changed in the WooCommerce settings, like in our test scenario, or if any of the many multi-currency solutions is running, the active currency and the order currency won't necessarily match.

## Why WC 2.6 and earlier are not affected
The earlier versions of WooCommerce included an extra check in function `wc_update_order()`, which prevented the call from replacing the order currency when an order is being modified. Here's the code from WC 2.6:
~~~
if ( ! $updating ) {
	update_post_meta( $order_id, '_order_key', 'wc_' . apply_filters( 'woocommerce_generate_order_key', uniqid( 'order_' ) ) );
	update_post_meta( $order_id, '_order_currency', get_woocommerce_currency() );
	update_post_meta( $order_id, '_prices_include_tax', get_option( 'woocommerce_prices_include_tax' ) );
	update_post_meta( $order_id, '_customer_ip_address', WC_Geolocation::get_ip_address() );
	update_post_meta( $order_id, '_customer_user_agent', isset( $_SERVER['HTTP_USER_AGENT'] ) ? $_SERVER['HTTP_USER_AGENT'] : '' );
	update_post_meta( $order_id, '_customer_user', 0 );
	update_post_meta( $order_id, '_created_via', sanitize_text_field( $args['created_via'] ) );
	update_post_meta( $order_id, '_cart_hash', sanitize_text_field( $args['cart_hash'] ) );
}
~~~

When the order is being updated, attributes like order key, currency, and customer information are left untouched. If the legacy API changed them before calling the function, the changes are maintained.

**Comment by claudiulodro** [comment]
This bug report was excellent. Great detail!

**Comment by daigo75** [comment]
Thanks. I spent over 12 hours dealing with the issue, trying to find the cause, and being blamed by some fulfilment companies for it because it was visible only when my Aelia Currency Switcher was active (of course, with a single currency it's practically invisible), so I thought of using the mountain of information I collected to make at least your life a bit easier. :smile:
