### ISSUE TITLE
Coupon validity bad error message

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce#16733]
Using WooCommerce brands, when applying a coupon that has excluded brands, we get a wrong error message:

Latest master:
<img width="803" alt="screen shot 2017-09-07 at 09 44 45 am" src="https://user-images.githubusercontent.com/1620929/30151783-332eee4a-93b1-11e7-835c-c011b09a44e2.png">

3.0.0:
<img width="803" alt="screen shot 2017-09-07 at 09 44 19 am" src="https://user-images.githubusercontent.com/1620929/30151778-28af6d5a-93b1-11e7-8458-9bd9ee77c9d6.png">

This happens due to the introduction of `is_coupon_valid` and catching exceptions. Starts from [here](https://github.com/woocommerce/woocommerce-brands/blob/9f2647f/includes/class-wc-brands.php#L323).

**Comment by mikejolley** [comment]
@bor0 I'm not sure why that plugin is using exceptions when the filter is meant to return true or false. This is incorrect usage. We can attempt to workaround but this is only working by luck :)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16738
