### ISSUE TITLE
Woocommerce new gallery features don't work with single product page shortcode

### ISSUE THREAD

**Issue by gubbigubbi** [woocommerce/woocommerce#16730]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. When showing a single product with the single product page shortcode, for example: [product_page id="1790"]

## Expected/actual behavior

I am expecting the 3.0 gallery to work

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

`
### WordPress Environment ###

Home URL: https://24kgoddess.com
Site URL: https://24kgoddess.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.6.1
Akismet Anti-Spam: by Automattic – 3.3.4
Better Search Replace: by Delicious Brains – 1.3
Contact Form 7: by Takayuki Miyoshi – 4.9
eWAY Payment Gateway: by WebAware – 4.0.2
Pixel Cat Lite: by Fatcat Apps – 2.1.0
Feed Them Instagram: by SlickRemix – 1.0.2
Feed Them Social Premium: by SlickRemix – 1.6.0
Google Analytics: by ShareThis – 2.1.3
Insert Headers and Footers: by WPBeginner – 1.4.2
Jetpack by WordPress.com: by Automattic – 5.3
MailChimp: by MailChimp – 1.5.7
Post Duplicator: by Metaphor Creations – 2.20
Post Types Order: by Nsp Code – 1.9.3.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.4.1
Page Builder by SiteOrigin: by SiteOrigin – 2.4.23
SiteOrigin Widgets Bundle: by SiteOrigin – 1.9.9
WooChimp: by RightPress – 2.0.1
WooCommerce Afterpay Gateway: by AfterPay – 1.3.1
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.3
WooCommerce Payment Methods: by vendocrat – 1.1.2
WooCommerce Tab Manager: by WooThemes / SkyVerge – 1.7.2 – 1.8.3 is available
WooCommerce: by Automattic – 3.1.2
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 5.4
WP Migrate DB: by Delicious Brains – 1.0
WP Rollback: by WordImpress – 1.5
WP Smush: by WPMU DEV – 2.7.4.1
WP Speed of Light: by JoomUnited – 2.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6 - /24k-gold-eye-masks-shop/
Cart: #1745 - /basket/
Checkout: #1746 - /checkout/
My account: ❌ Page not set

### Theme ###

Name: ngaire2.0
Version: 1.0.0
Author URL: http://breezydesigns.com.au
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: ngaire-2-0/woocommerce/archive-product.php
ngaire-2-0/woocommerce/emails/customer-completed-order.php
ngaire-2-0/woocommerce/single-product.php

</details>

**Comment by mikejolley** [comment]
> I have included a failing test as a pull request (Optional)

Please don't just tick all the boxes on the new issue form without reading/doing the step first. 

This is going to be theme dependent. It looks like this theme has a variant of the gallery, some of the features are disabled. 

I tested a shortcode on a page in Twenty Twelve theme and Storefront to be sure. Both functioned normally. Testing on master.

Confirm by swapping themes, then report to the author please.
