### ISSUE TITLE
Broken image links

### ISSUE THREAD

**Issue by dima-stefantsov** [woocommerce/woocommerce#16737]
https://github.com/woocommerce/woocommerce/pull/16735

Woocommerce 3.0.0 introduced force replace https:// to //. This breaks my use case, where shop page is http, while images are stored in CDN and are only available over https.

This is the image url, returned by woocommerce logic, with all it's filters applied. No need to forcefully override what woocommerce and filters decided URL to be, and break it.

If by some obscure reason you still want to override earlier decisions, please at least introduce a filter, action or flag to change it. Currently there are no filters below, only above this wrong replace.

Good solution would be to revert this piece of code logic to how it was before 3.0.0: no forceful replace.
If you still need it, **please allow to disable it**.

**Comment by mikejolley** [comment]
We just need to ensure https sites force https images, regardless of your CDN limitations.

**Comment by dima-stefantsov** [comment]
Please note you say "force https images for https sites", while case I described is backwards: http site, https images.

Wouldn't default wordpress pipeline already return https image urls for https site?
Isn't the only way to get images scheme inconsistent with current site scheme - is when one manually overrides it using filters? And if I've done it myself, maybe I know what I'm doing, why are you forcefully breaking my urls?

In any case, please let me disable it, if you just have to break it.

return apply_filters('mike-disable-bug', true) ? str_replace(break_stuff_force_http, $image) : $image;

Oh great king of woocommerce, have mercy, allow me to modify my image urls like I want them.

**Comment by mikejolley** [comment]
As great king I can also disable comments from sarcastic commenters.

CDNs is one such example of why forcing may be needed. Relative URLs ensure the same scheme is used.

Protocol relative is also needed when you have widgets being cached and that cached being accessed on https or http pages. [If you looked at the history you'd see where/why this was introduced.](https://github.com/woocommerce/woocommerce/issues/11884)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16744
