### ISSUE TITLE
CSV Import: New products not added when set to update existing products (by SKN)

### ISSUE THREAD

**Issue by stl99** [woocommerce/woocommerce#16740]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Prepare CSV file with existing products as well as new products
2. Import CSV file with the option checked to update existing products

## Expected/actual behavior

When I follow those steps, I see...

...existing products being updated (by SKN), new products being skipped

I was expecting to see...

... existing products being updated (by SKN), new products (SKN doesn't exist yet) being added

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## Notes

I tried importing new products with and without a unique SKN set. Both times the new products in the CSV file are skipped, only the old ones already existing in the WordPress installation are updated.

Or do we have to split the CSV files for updating/adding products via the importer?

**Comment by mikejolley** [comment]
Needs to be split. See https://github.com/woocommerce/woocommerce/issues/16641

We'll update the wording.
