### ISSUE TITLE
Possible to display all prices INCLUDING tax in order admin view?

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [woocommerce/woocommerce#16747]
Currently it seems impossible to view an order in wp admin with all prices including taxes (with added taxes shown separately).

I find this to be very confusing for shop managers who assist their customers over the phone. 
When the option to display all prices inlcuding taxes in shop fronted AND the entry of prices is set to be including taxes, why would we want to see confusing excl. prices in order view?

Could you please do something about this?

This becomes also a huge problem, when shop managers try to take an order over the phone... they can't simply set up an order via "new order" in wp admin... no.. because net pricing.. its a pain..

They have to complete the order as a customer via shop frontend. This could be fine, but as soon as they need to edit anything in the order later on once it has been completed we return to the net pricing problem, which is a source of mistakes...

Please make it possible to simply set up a new order in wp admin with incl tax pricing!

Thanks!

**Comment by mikejolley** [comment]
When you setup a manual order, the price may well be added excluding tax, however, as soon as you input the customer's shipping/billing address and recalc, the taxes will be applied. I'm unsure why this is confusing unless you're editing prices manually. If you're just adding products to the order, there is nothing manual to do or calculate.

> why would we want to see confusing excl. prices in order view?

Mainly because the tax amount is input separately - if the price column was shown inc tax, you'd have to edit both and ensure they match up. It would also add extra hurdles for developers working with orders because they'd have to handle tax inc/tax ex orders completely differently.

I guess it may be possible to display them in the inputs inc tax and handle that before save, but it would get pretty complex. I worry it would introduce other errors or confusion. [The calculations for prices including tax are not straightforward as those for ex. tax prices.](https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#tax-calculations-simplified)

I'd suggest logging this on the ideas board. Have a search to see if anything matches your requirements, I think http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/3885796-prices-display-including-tax-in-the-order-edit-scr may be the one. If there is enough demand we'll take it on,  but it's not something we'll commit to doing without demand due to complexity.

Thanks

**Comment by scrobbleme** [comment]
I would like to see this as well. Why not just add a new column showing the price including tax?

**Comment by sergiustatache** [comment]
> I would like to see this as well. Why not just add a new column showing the price including tax?
> 
> ![image](https://user-images.githubusercontent.com/504835/63413918-08999000-c3fb-11e9-958a-70a00337609c.png)

What sollution did you find to this? :D I need to display that total column too.

**Comment by ernitish** [comment]
> > I would like to see this as well. Why not just add a new column showing the price including tax?
> > ![image](https://user-images.githubusercontent.com/504835/63413918-08999000-c3fb-11e9-958a-70a00337609c.png)
> 
> What sollution did you find to this? :D I need to display that total column too.

Try this code

function action_woocommerce_admin_order_item_values( $null, $item, $absint ) {
    $val = ($item['type'] == 'line_item' || $item['type'] == 'shipping') ? $item['total'] + $item['total_tax'] : '&nbsp;';
    $valdecimal = wc_format_decimal( $val, $dp='', $trim_zeros );
    ?>
    <td class="item_cost" data-sort-value="<?php echo $val; ?>">
        <div class="view" style="">
            <?php if ($val>0) echo '$'; echo $valdecimal;?>
        </div>
    </td>
    <?php
}
add_action( 'woocommerce_admin_order_item_values', 'action_woocommerce_admin_order_item_values', 10, 3 );


function action_woocommerce_admin_order_item_headers( $order ) {
    echo '<th class="item_cost sortable" data-sort="float" style="width: 13%;">Cost (inc VAT)</th>';
}
add_action( 'woocommerce_admin_order_item_headers', 'action_woocommerce_admin_order_item_headers', 10, 3 );

**Comment by ernitish** [comment]
> > I would like to see this as well. Why not just add a new column showing the price including tax?
> > ![image](https://user-images.githubusercontent.com/504835/63413918-08999000-c3fb-11e9-958a-70a00337609c.png)
> 
> What sollution did you find to this? :D I need to display that total column too.

Try this code
https://pastebin.com/VSiUBvN3

**Comment by runmaromat** [comment]
Thanks a lot! I've been searching for something like this for quite a long time.

**Comment by jancikviktor** [comment]
> > > I would like to see this as well. Why not just add a new column showing the price including tax?
> > > ![image](https://user-images.githubusercontent.com/504835/63413918-08999000-c3fb-11e9-958a-70a00337609c.png)
> > 
> > 
> > What sollution did you find to this? :D I need to display that total column too.
> 
> Try this code
> https://pastebin.com/VSiUBvN3

Hello, it's your code? I have one issue with them, could we talk about freelance help wi this?
If I enable this code, I get an error after refunding something in order;

`Automattic\WooCommerce\Admin\Overrides\OrderRefund as array in /var/www2/p4635/web.sk/web/wp-content/plugins/code-snippets/php/snippet-ops.php(446) : eval()'d code:2
Stack trace:
#0 /var/www2/p4635/web.sk/web/wp-includes/class-wp-hook.php(287): action_woocommerce_admin_order_item_values()
#1 /var/www2/p4635/web.sk/web/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#2 /var/www2/p4635/web.sk/web/wp-includes/plugin.php(484): WP_Hook->do_action()
#3 /var/www2/p4635/web.sk/web/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-order-refund.php(50): do_action()
#4 /var/www2/p4635/web.sk/web/wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-order-items.php(92): include('/var/www2/p4635...')
#5 /var/www2/p4635/web.sk/web/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-items.php(41): include('/var/www2/p4635...')
#6 /var/www2/p4635/sp`

and wordpress goes to Fatal error..

Thank you much :)

**Comment by ernitish** [comment]
> rrides\OrderRefund as array in /var/www2/p4635/web.sk/web/wp-content/plugins/code-snippets/php/snippet-ops.php

Can you share full error log file here so i can see, exact fatal error. I have used that code and that was working perfectly.
You can contact me over skype @webcast.technology

**Comment by geddyshop** [comment]
Hi ernitish! I have been looking for a solution for this and came across your code. I have been managing 3 stores, all in opencart where this is a standard feature. Recently changed to woocommerce and it's very difficult for me to manage my orders without seeing the complete price. I am not a developer but I have access to my  cpanel. Where do I paste this piece of code? And if it doesn't work for me, what do I do? Just delete it? Sorry for the totally novice approach, but I have already asked some developers here in Greece and they couldn't come up with a solution. Thanks!

**Comment by ernitish** [comment]
Hi, @geddyshop, you can login into wp-admin and install [code snippet](https://wordpress.org/plugins/code-snippets/) plugin and there you can add snippet with this code.
https://pastebin.com/VSiUBvN3

if something not working or broken, you can disable that snippet.
You can contact with me via skype @webcast.technology for further help.

**Comment by CreedHub** [comment]
@ernitish - thanks a lot for the snippet from pastebin!
However, it gives out an error.
Replace
`$valdecimal = wc_format_decimal( $val, $dp='', $trim_zeros );`
by
`$valdecimal = wc_format_decimal( $val, $dp = '', $trim_zeros = false );`

**Comment by CreedHub** [comment]
I found out that that code snippet from pastebin gives out an error if you have product items with zero quantity (only possible modified core files).

In that situation, this plugin works perfectly:
https://github.com/AashikP/item-total-for-wc

**Comment by romfeo** [comment]
> > > I would like to see this as well. Why not just add a new column showing the price including tax?
> > > ![image](https://user-images.githubusercontent.com/504835/63413918-08999000-c3fb-11e9-958a-70a00337609c.png)
> > 
> > 
> > What sollution did you find to this? :D I need to display that total column too.
> 
> Try this code
> https://pastebin.com/VSiUBvN3

What if I need to remove the default woocommerce columns (cost, qty, total, tax) and only use my custom columns?

**Comment by ernitish** [comment]
Hi,
you can unset those columns which you don't want to display.

**Comment by CreedHub** [comment]
Update: with this plugin it is not possible to save modifications in the order any more:
https://github.com/AashikP/item-total-for-wc
Maybe because I use another plugin (making decimal quantity)

**Comment by xtra-dev** [comment]
@ernitish thanks a lot for the code example on Pastebin. Works like a charm! Just one question. For me, the manually added gross price displays not as the last column, it is hooked into the middle of the columns. I would like to display the custom column at last as depicted in the screenshot from @scrobbleme. Is there a way to programmatically define the order so it is added as the last column?

![image](https://user-images.githubusercontent.com/25582052/132134664-be839f9f-a945-468c-899a-9928f7cd9421.png)

**Comment by ernitish** [comment]
> @ernitish thanks a lot for the code example on Pastebin. Works like a charm! Just one question. For me, the manually added gross price displays not as the last column, it is hooked into the middle of the columns. I would like to display the custom column at last as depicted in the screenshot from @scrobbleme. Is there a way to programmatically define the order so it is added as the last column?
> 
> ![image](https://user-images.githubusercontent.com/25582052/132134664-be839f9f-a945-468c-899a-9928f7cd9421.png)

Hi,
Sorry, but there no action/hook for showing this at the end of columns.
You can try to do with this CSS.

Thanks

**Comment by kyote73** [comment]
> > rrides\OrderRefund as array in /var/www2/p4635/web.sk/web/wp-content/plugins/code-snippets/php/snippet-ops.php
> 
> Can you share full error log file here so i can see, exact fatal error. I have used that code and that was working perfectly. You can contact me over skype @webcast.technology

I also get this fatal error when using the code and viewing an order that has a refund.  Is there a workaround for this by chance... not displaying inc tax is driving my accounts person crazy!

**Comment by camper2020** [comment]
Hi all, I came across this Github issue while searching for a solution for this very problem or seeing pricing of line items including tax in the admin order edit screen. Furthermore we wanted the ability to edit the line items with the inclusive pricing to make it easier to set and calculate discounts. I've since written a plugin to do just this if anyone is interested, you can install it here: https://wordpress.org/plugins/rd-wc-order-modifier

If you do use it, please let me know if there are any bugs or problems that you experience or if it works. Thanks for your time!
