### ISSUE TITLE
Woocommerce orders always pending after making payment with lemonway

### ISSUE THREAD

**Issue by shraddha27** [woocommerce/woocommerce#16745]
I use lemonway payment gateway with woocommerce 3.1.1 for wordpress. After successful payment with transactpro payment the orders still remain pending. Please help.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
HI @shraddha27 

This is the issue tracker for core. I think you'll need to contact the developers of lemonway for help with this - we don't maintain that extension.

Thanks
