### ISSUE TITLE
Broken links 2

### ISSUE THREAD

**Issue by dima-stefantsov** [woocommerce/woocommerce#16746]
To fix this edge case https://github.com/woocommerce/woocommerce/issues/11884 , where a user have weird setup to serve site over http and https both, and uses some non-default cache, and where he didn't bothered to just filter urls himself, you have introduced a forceful // replace.

Now I have a site where images are stored by 3rd party shop provider. It's http. I can't help it.

My site is https. I know page with mixed content is unsafe. I know browsers will show warnings.
But at least images will be displayed. Most users will notice it.

You have built code in a way, where I can filter urls in many ways, for example filter 'woocommerce_placeholder_img', 'woocommerce_placeholder_img_src'... But then you just override decisions of my filters, not giving me an option to change it back anymore.

It c an be coded any way you want. It may be a flag to disable this http replace. It may be a filter to further alter a result (which would be bad because I'd have to query $product for it's url attribute again, but it will work). But you decide to decline a pull request and close an issue.

Issue you fixed is where developer was lazy to modify his urls for his weird edge case.

My issue is when you don't let me use urls I want. You want to have his case remain fixed? Fine. Allow to customize this. A filter. A flag. An action. Anything.

I would also love if you would not close topics immediately after stating your final and only right decision, allow a discussion where I could offer you any kind of code you want, just so it fixes my issue.

I'm not asking you to fix it. I'm begging you to allow me fix it. Just say how you want it done, I'll do it. This is madness.

**Comment by dima-stefantsov** [comment]
https://github.com/woocommerce/woocommerce/pull/16735/commits/871dd6e4d1e3f3c2626c8c23b045a059e2b21973 this is the original declined pull request, and issue described.

**Comment by mikejolley** [comment]
@dima-stefantsov Your previous issue is unlocked. And we already submitted https://github.com/woocommerce/woocommerce/pull/16744 - what is the issue with that?

You may know how to use filters, but the average user does not. They just see mixed content warnings and breakage. If this can prevent that, what is the problem?

**Comment by mikejolley** [comment]
OP issue: https://github.com/woocommerce/woocommerce/issues/16737

This is the original caching issue which would be broken by your rejected PR: https://github.com/woocommerce/woocommerce/issues/11884

> CDNs are one such example of why forcing may be needed. Relative URLs ensure the correct scheme is used. This code is there to prevent mismatches when viewing the store over https. We want to avoid warnings in the browser.
>
> Protocol relative is also needed when you have widgets being cached and that cached being accessed on https or http pages. If you looked at the history you'd see where/why this was introduced.. In that case, the widget was cached on http, then displayed on https causing the warnings.

Your comment:

> where a user have weird setup to serve site over http and https both, and uses some non-default cache, and where he didn't bothered to just filter urls himself, you have introduced a forceful // replace.

It's not a non-default cache at all. It's transient cache. And sites that are affected are those which use http for the main site, and https for certain pages like checkout. Thats why relative URLs fix those cases.

**Comment by mikejolley** [comment]
From email:

> Sadly, it does not. return str_replace( 'http://', '//', $image ); still makes my http links relative, on https site it's treated as https, while 3rd party server only has http.

So in this case, you will have an error (from the browser) about mixed content anyway. This is not the original issue you reported, this is something hypothetical.

If you're on a HTTPS site, resources should be forced to HTTPS. I don't think there is anything wrong with that behaviour. @claudiulodro

**Comment by dima-stefantsov** [comment]
@mikejolley all right, change introduced in 3.0.0 is good for some cases (why I call it weird? If you can have https over some pages, why would you have http over the rest; performance? negligible, but it's up the them, that's not my concern)

But it breaks my case. I need site https, while images http. Yes it's bad, browser unsafe content warnings. I do not have control over 3rd party that has images. But images will be displayed.

```
Here's the real working code, 
                 return apply_filters( 'woocommerce_product_image_relative', true ) ? str_replace( array( 'https://', 'http://' ), '//', $image ) : $image;
it's a bit ugly, but it's much prettier than overriding templates. May as well pass arguments $size, $attr, $placeholder there.

Less desirable is this code: 
		$image = str_replace( array( 'https://', 'http://' ), '//', $image );
		return apply_filters( 'woocommerce_product_image', $image, $size, $attr, $placeholder );

But it will work as well.
```

**Comment by dima-stefantsov** [comment]
Let me tell you again.

I have https site.
I serve images from 3rd party I do not control.
Lots of gigabytes of images.

Usually 3rd party has https as well, then it's good.
But sometimes they don't. And when I say "this is http" it should stay http.

Here is real working example that would allow me to either disable your force-relative-replace, or filter it again and override it later:

1st:
```
return apply_filters( 'woocommerce_product_image_relative', true ) ? str_replace( array( 'https://', 'http://' ), '//', $image ) : $image;
```

2nd:
```
$image = str_replace( array( 'https://', 'http://' ), '//', $image );
return apply_filters( 'woocommerce_product_image', $image, $size, $attr, $placeholder );
```

http://4.stefantsov.com/s/2017.09.07_19.52.29_l6bjtebg.png

**Comment by dima-stefantsov** [comment]
> If you're on a HTTPS site, resources should be forced to HTTPS. I don't think there is anything wrong with that behaviour.

There is something wrong. I am on https site, but **IT'S EXTERNAL RESOURCES!** And they don't have https.

Alright. Force https all you want, allright! Just let me change your decision in code. Make a filter, anything. Let me make a filter. Let me solve it with code.
Why do I have to say it more than once? I have a problem, I am providing a code to solve it, why is it so hard to have it fixed? Why do I have to waste hours proving you an obvious thing: you are changing a string after all the filters, you don't let me change it. Isn't it obvious a user must be able to change his own image urls? Why is it so hard?!

**Comment by dima-stefantsov** [comment]
Maybe it will be easier with example.

I have https://test.com. I'm using only https.

All images I want to display are on http://imagesprovider.ru. And they only have http. What a barbarians. But such is life.

Now I have few options:

1. Download all the images. That would make me bankrupt on server costs.
2. Do not serve any images. That would kill user experience.
3. Make my site http only. This would be less secure, and it would be hard to change existing pipelines.
4. Have my https://test.com site run https, while images are served from http://imageprovider.ru over http. Downside is it's unsafe mixed content. Browser developer console will give warnings. Other than that, visitors will not see any difference.

I'm going with 4.
That's why I need images to be http://imageprovider.ru/imgpath.jpg, not https://imageprovider.ru/imgpath.jpg , https image will simply not work.
It was ok until you introduced 3.0.0 changes, which forces scheme. I'm not happy with it, but I'll just filter it... Oh wait, I can't. It's the end point. Now my only option is to beg on support forums for fixes.

Can you please allow me to change image url the way I need it to be? A filter maybe?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/16760
