### ISSUE TITLE
Creating variable products using WC's rest api v2

### ISSUE THREAD

**Issue by xeektech** [woocommerce/woocommerce#16750]
Hi, I am trying to create a variable product using rest api v2 while following the two step process: 
**1- create product (success)** 

Create product request json is as follows:
```
{
  "sku": "OG_TESTPRDC",
  "type": "variable",
  "description": "<p>LONG DESCRIPTION.</p>\n",
  "short_description": "<p>SHORT DESCRIPTION.</p>\n",
  "categories": [
    {
      "id": "116"
    }
  ],
  "attributes": [
    {
      "name": "Fabric Type",
      "visible": true,
      "variation": true,
      "options": [
        [
          "Breathe Black",
          "Breathe Lime Green",
          "Breathe Royal Blue",
          "Breathe Tomato Red"
        ]
      ]
    }
  ],
  
  "name": null,
  "slug": "item_someitem-og_testprdc_b",
  "featured": false,
  "catalog_visibility": "visible",
  "regular_price": "60",
  "tax_status": "taxable",
  "tax_class": null,
  "manage_stock": false,
  "stock_quantity": "0",
  "in_stock": true,
  "weight": "2",
  "length": "0",
  "width": "0",
  "height": "0",
  "shipping_required": true,
  "shipping_taxable": true,
  "shipping_class": null,
  "shipping_class_id": null
}


```

**2- Create variation:** on top of the newly created product (using batch mode as I have more than one variation using url: https://someserver/wp-json/wc/v2/products/< productid >/variations/batch). 

The variation create request looks like this:

```
{
  "create": [
    {
      "sku": "OG_VAR_BB",
      "visible": true,
      "manage_stock": false,
      "stock_qty": "null",
      "in_stock": false,
      "weight": "2.000000000000",
      "dimensions": {
        "length": "0.000000000",
        "width": "0.000000000",
        "height": "0.000000000"
      },
      "attributes": [
        {
          "id": "18",
          "option": "Breathe Black"
        }
      ]
    },
    {
      "sku": "OG_VAR_BG",
      "visible": true,
      "manage_stock": false,
      "stock_qty": "null",
      "in_stock": false,
      "weight": "2.000000000000",
      "dimensions": {
        "length": "0.000000000",
        "width": "0.000000000",
        "height": "0.000000000"
      },
      "attributes": [
        {
          "id": "18",
          "option": "Breathe Lime Green"
        }
      ]
    },
    {
      "sku": "OG_VAR_BR",
      "visible": true,
      "manage_stock": false,
      "stock_qty": "null",
      "in_stock": false,
      "weight": "2.000000000000",
      "dimensions": {
        "length": "0.000000000",
        "width": "0.000000000",
        "height": "0.000000000"
      },
      "attributes": [
        {
          "id": "18",
          "option": "Breathe Tomato Red"
        }
      ]
    },
    {
      "sku": "OG_VAR_BRB",
      "visible": true,
      "manage_stock": false,
      "stock_qty": "null",
      "in_stock": false,
      "weight": "2.000000000000",
      "dimensions": {
        "length": "0.000000000",
        "width": "0.000000000",
        "height": "0.000000000"
      },
      "attributes": [
        {
          "id": "18",
          "option": "Breathe Royal Blue"
        }
      ]
    }
  ]
}
```
The variations are also created successfully but the "attributes" tag returned in the response json is an empty array. True for each and every variation in the batch (screenshot enclosed).

![image](https://user-images.githubusercontent.com/25024982/30181732-b5dc8524-942d-11e7-9e6a-91737ca89169.png)

I am assuming the variations are not getting properly linked with the attributes. Besides, I don't have access on the wp dashboard UI therefore I cannot verify/tweak anything there. API access is all I have and thats why I have to rely on the response jsons messages (I am attaching complete request and response jsons for your review).

Your help in this regard is greatly appreciated.

Thanks, -Sam
Note: I have changed the values (such as sku, slug, url etc. in an effort to obfuscate the actual business data)

[requestresponse.zip](https://github.com/woocommerce/woocommerce/files/1285903/requestresponse.zip)

**Comment by mikejolley** [comment]
Just a small mistake. In the variation code, you need to pass the attribute name - ID 18 does not exist.

```
 "attributes": [
        {
          "name": "Fabric Type",
          "option": "Breathe Black"
        }
      ]
```

**Comment by xeektech** [comment]
Hi Mike,
Thanks for your response. I tried your suggestion but it appears to not have done the trick. I am attaching the request and response samples for your review. Thanks

**Comment by caesaram** [comment]
@xeektech Hi! Could you solve the empty attribute array problem? 
I have tried to add variations in batch and also doing post for each variation, but in all cases the result of the variant returns attributes: []
I've used 
`attributes : { id: integer, option: "some value" }`
and also 
`attributes : { name: "some name", option: "some value" }`
**I've double checked that the attributes exist and if the IDs were correct**
But it's allways returning an empty array of attributes.
Please i need a tiny help, i've been trying since 2 or 3 days ago. There must be something that do the trick.
Thank you!
