### ISSUE TITLE
Checkout is loading shipping method before fill an address or state

### ISSUE THREAD

**Issue by clamas** [woocommerce/woocommerce#16754]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. As guest or logged user, add a product to cart.
2. Go to cart and proceed with payment.
3. Before filling any input, checkout reload and show a shipping message: "There are no shipping method available....."

## Expected/actual behavior

When I follow those steps, I see that message "There are no shipping method available..." I have configured one zone with certains state. And chackout should show shipping method before full address completed.

I was expecting to see my shipping methods after complete all address input. Most important, State.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://www.dimor.cl
Site URL: https://www.dimor.cl
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.31
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.55.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Anti-Spam by CleanTalk: por СleanTalk  – 5.74.2
Comunas de Chile para WooCommerce: por Anyda SRL  – 0.1
Contact Form 7: por Takayuki Miyoshi – 4.9
Gmail SMTP: por naa986 – 1.1.5
Nextend Facebook Connect: por Nextendweb – 2.0.2
Nextend Google Connect: por Roland Soos
Jamie Bainbridge – 1.6.1

Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 2.2.6
WooCommerce: por Automattic – 3.1.2
WooSidebars: por WooThemes – 1.4.3
Yoast SEO Premium: por Equipo Yoast – 5.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CLP ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base de la tienda: #62 - /productos/
Carrito: #61 - /cart/
Finalizar compra: #60 - /checkout/
Mi cuenta: #59 - /my-account/

</details>

**Comment by mikejolley** [comment]
Seemed related to https://github.com/woocommerce/woocommerce/issues/16757

**Comment by kane0404** [comment]
Im having same issues with " no shipping method available", But i can see that my shipping methods are enable. Please help.

**Comment by mikejolley** [comment]
Perhaps added to the wrong zones? Post to the helpdesk if you need some assistance.
