### ISSUE TITLE
UX messaging on the checkout page makes an impression that International shipping is not available.

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce#16757]
## Summary:
Even though international shipping is available, when only the foreign country is selected from the country dropdown we get a message that not shipping method is available which is not very accurate.

## Demo:

![](http://cld.wthms.co/wL31iv+)
[direct link](http://cld.wthms.co/wL31iv)

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Actual behavior
0. Ensure you have a shipping zone with shipping methods targeting foreign countries.
1. Add a product to cart.
2. Goto checkout page and select a foreign country [other than the home country].
3. Now you will see the message that no shipping method is available.
4. Please note that when the complete address is filled up then the rates are displayed but this scenario can cause confusion.

## Code causing this behavior:
https://github.com/woocommerce/woocommerce/blob/e143a51cc741c127476e4a919b75905f7408701f/templates/cart/cart-shipping.php#L50

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

670683-zd-woothemes

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: https://woocommerce.mystagingwebsite.com
Site URL: https://woocommerce.mystagingwebsite.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.23
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.55.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Email Log: by Sudar – 2.0.2
Test Payment Module for Woocommerce: by Sean Barton (Tortoise IT) – 1.5
WooCommerce: by Automattic – 3.1.2
WP Crontrol: by John Blackbourn & contributors – 1.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #2 - /
Cart: #3 - /cart/
Checkout: #5 - /checkout/
My account: #77 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by clamas** [comment]
Thanks for reply. I've noticed this behavior in other threads, but there is a way to change it? This is causing a little confution to customers, above all if in cart shows a message that says shipping costs will be calculated after entered an address. If there is a way to 'update_checkout' or hide that message until State are filled, would be nice. Maybe a snippet or code changing?. I'll really appreciate a temporally solution, I been days looking for solution. Thanks!. Greetings.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16763
