### ISSUE TITLE
{"errors":[{"code":"woocommerce_api_authentication_error","message":"Consumer key is invalid."}]}

### ISSUE THREAD

**Issue by jig4physics** [woocommerce/woocommerce#16769]
Hello all,

I am Using 

WP=4.8.1
OAuth1.0a Server= 0.3.0
WC=3.1.2
Protocol: HTTP 

I Authorize my App usign POSTMAN When I fire full string as given below it shows the error of "**{"errors":[{"code":"woocommerce_api_authentication_error","message":"Consumer key is invalid."}]}**". 

http://static-ip:82/ifuture/wc-api/v3/products?
oauth_consumer_key=LFZ9lnZ6z3mL&oauth_token=FupNAjUIwtKtqSHd66mJS4vD&oauth_signatu
re_method=HMAC-SHA1&oauth_timestamp=1505020330&oauth_nonce=Z9nZ0GbCggX&oauth_version=1.0&oauth_
signature=2bqD8fhFJKj3l/OoCMTgCd8/I4M=&oauth_verifier=ESwgoJ2XPIOOJXZdvtZrKBiF&oaut
h_token=460FGrrvevMcDtcF84FKrQjd&oauth_token_secret=IPCt9CumQPI6RvFNJi9IANDSq9QV7F
4ymrNi1o9TYJXx1wVF

I read previous threads also, but still, I am getting the same error. Consumer key created in OAuth, not in WC->settng->API.

**Comment by mikejolley** [comment]
We have specific requirements for signature generation if using our authentication. See nhttps://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

Use HTTPS to avoid the need to generate signatures. Or you have use our PHP library which does it for you.

Also note, there is no v3 API in WooCommerce yet. Not sure how you're using this.

Thanks
