### ISSUE TITLE
Ability to update cart_item_data in cart_contents

### ISSUE THREAD

**Issue by ThomasSultana** [woocommerce/woocommerce#16766]
Hi,

Im not sure where to place this however id like some input on the following issue. At the moment i can programatically add an item to the cart using add_to_cart. At this point i can add custom cart_item_data. I have taken a look at the WC_Cart class and I can't seem to find a safe and easy way to be able to update cart_item_data without having to remove/re-add the product to the cart. My current workflow is: 

1. Run: woocommerce_update_cart_validation filter and validate if custom inputs on cart page pass validation.
2. If validation passes i would like to update cart_item_data at this point.

If this is not possible, what alternatives do i have? Im thinking to possibly use WC_Session to save data as a temporary measure.

Thank you

**Comment by mikejolley** [comment]
Thats the only way - we don't have a way to update them. Data on cart items usually persists and is not changed.

By removing and re-adding it ensures that duplicate cart items can never exist.

Thanks
