### ISSUE TITLE
problems with variable products 

### ISSUE THREAD

**Issue by ismtheman** [woocommerce/woocommerce#16777]
im using woocommerce Version 3.1.2.

when i change a product to variable, i cannot see the options for bulk editing, and on the site the products appear as out of stock or unavailable. 

any ideas whats wrong?

**Comment by mikejolley** [comment]
You need to go to the 'attributes' tab, add some, then go to the 'variations' tab and add some variations. 

See https://docs.woocommerce.com/document/variable-product/
