### ISSUE TITLE
Invalid signature - provided signature does not match

### ISSUE THREAD

**Issue by gespejo12** [woocommerce/woocommerce#16770]
Hi, I was trying to update product stock using woocommerce API via postman. I'm using Oauth for authentication, when I'm using GET method to fetch specific products the request is success but when I'm trying to update product I'm getting this error **Invalid signature - provided signature does not match** 

<img width="980" alt="screen shot 2017-09-10 at 5 29 28 pm" src="https://user-images.githubusercontent.com/25280622/30247771-c6a7ea20-964d-11e7-831a-fd4eae9e6fe4.png">
<img width="982" alt="screen shot 2017-09-10 at 5 30 19 pm" src="https://user-images.githubusercontent.com/25280622/30247772-c6e0a680-964d-11e7-95eb-50622f7bda6f.png">

**Comment by mikejolley** [comment]
Using GET/PUT/POST also affects how the signature should be generated. Please see https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http or use HTTPS auth which is much easier.
