### ISSUE TITLE
Unnecessary divs/classes?

### ISSUE THREAD

**Issue by glvr** [woocommerce/woocommerce#16771]
An earlier issue (#12191) concerned 'remove this unnecessary div' - because the div was breaking the layout.

Although I can understand and agree with the reasoning for it being something which won't be changed, the amount of divs/classes often seems unnecessary large...

> class="post-9032 product type-product status-publish has-post-thumbnail product_cat-shows first instock virtual taxable shipping-taxable purchasable product-type-simple"

For over-riding, it makes targeting difficult, and when WC css is disabled the source code remains 'less clean' than it should be.

And, although I can understand and agree with the reasoning for this being something which won't be changed, supplementing the docs with an appropriate filter/function to remove all classes will be useful.

**Comment by willgorham** [comment]
I understand the need to maintain legacy CSS classes to ensure backward compatibility. It certainly would be a nice feature though to be able to disable all legacy classes and have a 'clean-slate' type HTML structure, especially if you're dequeueing the CSS already.

**Comment by mikejolley** [comment]
These classes are mostly added by WordPress - https://codex.wordpress.org/Function_Reference/post_class I believe. It's filterable if you want to remove them :) We use the filter to add some product specific css classes we need for styling.

There is a filter example in the codex.

Functionality wise, these classes have no negative impact on the page really. And wrapping **all** classes throughout the entire codebase would be a bit overkill. You can override all templates if it really bothers you.

Thanks!
