### ISSUE TITLE
Stock changes are erased by admin edition

### ISSUE THREAD

**Issue by guilro** [woocommerce/woocommerce#16780]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a simple product with managed stock, set stock to 2, save it, close the edit page.
2. Re-open the edit page of this product.
3. In another browser tab, buy the product in the shop.
4. In the edit tab, change something in the description, and save.
5. Stock is set to 2, where as you can see in the order created at step 3 that it was reduced to 1.

## Expected/actual behavior

Editing a product in the admin should not create a race condition if someone is ordering the product at the same time. In reality, you don't "set your stock" to a certain number, you add a certain number of items if you have new supplies, or you remove some if you reallocate.

Proposals :
* a field to "add" or "remove" a given quantity
* alternatively, if the UX should not be changed, their could be a hidden field with the previous stock, and at saving, the difference between the previous stock and the new one is added to the current stock in database, so changed cause by orders are not erased

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
This is prevented in 3.2 -  if stock level changes, your update will be rejected.
