### ISSUE TITLE
WC2.6 with WP4.8

### ISSUE THREAD

**Issue by arzuhuseyn** [woocommerce/woocommerce#16786]
Hi there. I`m using woocommerce 2.6 with wordpress 4.8.1. There is some issues with my wp-admin`s search. When I try to search products it shows "No Products Found" . Please can you guide me about it?
I can`t fix it

**Comment by arzuhuseyn** [comment]
I have updated it to the 3.1 and nothing changed. Can my template affect it?

**Comment by mikejolley** [comment]
Plugins and themes can affect this which is why we ask you rule out conflicts before posting issues here. Please do so and follow the steps on the 'new issue' page.

Thanks
