### ISSUE TITLE
Tax not being calculated

### ISSUE THREAD

**Issue by kaustubh3692** [woocommerce/woocommerce#16788]
Hi there,

I am using WC version 2.5. I have setup NAB transact payment gateway which was working fine till now. 
When a payment has failed the customers login on their account to pay and change Credit Card however the amount is calculated less 10% which is the tax rate set for all. When the payments are successful we don't have this issue. @mikejolley Any idea about this?
Any help will be appreciated.

**Comment by mikejolley** [comment]
Tax calculation is not affected by gateway choice. Taxes are shown in the cart/checkout page. If this is the amount in NAB which is wrong, the gateway itself may not be passing the taxes across. You'll need to look into that. 

FYI we don't support 2.5 since it's over a year old.

Thanks
