### ISSUE TITLE
Issue with receiving incorrect amount 

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#16789]
I'm using Standard Paypal Payment gateway. Recently i switched to a different theme and accept multiple currencies. However, i got the order with wrong amount in different currency. 

I got the warning from WooCommerce:

> Payment pending (multi_currency). Order status changed from Pending payment to On hold.

This is the amount i expected to receive in AUD.
![screen shot 2017-09-12 at 8 11 09 am](https://user-images.githubusercontent.com/2909982/30326688-49814a1e-9797-11e7-929d-af0fcf1a60b9.png)

But I received this amount instead. 
![screen shot 2017-09-12 at 8 11 24 am](https://user-images.githubusercontent.com/2909982/30326699-5bdaebd4-9797-11e7-85e3-9ae096415203.png)

> `
### WordPress Environment ###

Home URL: https://domain.com
Site URL: https://domain.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.12.1
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 2000
cURL Version: 7.38.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

AliDropship Woo Plugin: by Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin – 0.6
Contact Form 7: by Takayuki Miyoshi – 4.9
Google Authenticator: by Henrik Schack – 0.48
Imagify: by WP Media – 1.6.9.1
JanStudio Addons: by JanStudio – 1.1.2
MailChimp for WordPress: by ibericode – 4.1.8
McAfee SECURE: by McAfeeSECURE – 1.7.7
Meta Slider: by Team Updraft – 3.5.1
Woocommerce Products Price Bulk Edit: by Mostafa Qanbari – 2.0
Perfect WooCommerce Brands: by Alberto de Vera Sevilla – 1.5.2
PixelYourSite PRO: by PixelYourSite – 6.2.4
Prettify reviews: by Freddy Muriuki – 1.0
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.3.1
Recover Abandoned Cart: by Fantastic Plugins – 17.9.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
SEO Optimized Images Business With WooCommerce: by priyanshu.mittal – 1.5.2
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3
Google Address Autocomplete for WooCommerce: by MB Création – 2.3.3
WooCommerce Google Product Feed: by Lee Willis – 7.1.4 – 7.1.10 is available
WooCommerce Shipment Tracking: by WooCommerce – 1.6.8
WooCommerce Table Rate Shipping: by Bolder Elements – 4.0.3
WooCommerce: by Automattic – 3.1.2
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 5.4
WP Rocket: by WP Media – 2.10.7
WooCommerce Variation Swatch: by WPAddon – 1.0.0
Yoast SEO: WooCommerce: by Team Yoast – 4.7
Custom Product Tabs for WooCommerce: by YIKES
Inc – 1.5.17

YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.4.3
YITH WooCommerce Popup: by YITHEMES – 1.1.1
YITH WooCommerce Review Reminder Premium: by YITHEMES – 1.3.1
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Gecko Child
Version: 1.0.0
Author URL: http://www.janstudio.net
Child Theme: ✔
Parent Theme Name: Gecko
Parent Theme Version: 1.5.1
Parent Theme Author URL: http://www.janstudio.net
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`

**Comment by mikejolley** [comment]
WooCommerce core does not handle multi-currency, so if you have this feature on your store it will be a plugin/theme feature.

R/e the message from PayPal, the account needs to be configured to auto-accept other currencies. See https://stackoverflow.com/questions/28594854/paypal-ipn-sending-pending-with-multi-currency-as-reason

You may also want to check the paypal account itself does not calculate shipping and handling (there are paypal account settings for this) since that will wipe out any costs WooCommerce sends.

Thanks!
