### ISSUE TITLE
Please fix order email and discount output

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [woocommerce/woocommerce#16785]
Hello there!
Could you please consider fixing the output of discounts in order emails?
Currently all applied coupons/discounts get summed up in the order email and output in a single row.

However in checkout and cart we see correct coupon application output - same is desired for order emails.
checkout:
![checkout-revieworder](https://user-images.githubusercontent.com/3524165/30312237-e2123616-9798-11e7-9366-89d0613791cd.jpg)

order email discrepancy:

![email-order](https://user-images.githubusercontent.com/3524165/30312387-9429a4f6-9799-11e7-8a31-4671163a6870.jpg)

Thanks for fixing this in advance :)

**Comment by MartinBalerio** [comment]
This bug was introduced in 3.1.2, while they dont fix it I was forced to downgrade to 3.1.1 in order to avoid customers complaining for wrong totals in emails.

**Comment by mikejolley** [comment]
This is not a bug nor something changed recently. Discounts are not broken down by coupon for a few reasons, but mostly because that total comes from the line item costs. Admin can change line item costs manually, so this total reflects that too.

I don't think this would be a quick fix or desirable for all users. I'd suggest requested this on ideas.woocommerce.com. I'll also flag it for consideration during #10704 because we want to look at how emails are presented when we take care of that.

Thanks

**Comment by MartinBalerio** [comment]
Hey Mike, first, thanks for replying, you are correct I misread the original post and thought we were having the same issue.

My issue is that when upgrading from 3.1.1 to 3.1.2 woocommerce started adding some weird stuff as seen on the screenshot below:

![32933f2ac1f39a4dd980cd5ee4fa9b4c _captura de tela 2017-09-14 as 02 40 37](https://user-images.githubusercontent.com/10700730/30413810-c547f89a-98f6-11e7-99a7-17eb9117da69.png)

Before 3.1.2 it showed values as it should: 

Discount: 89.00
Shipping 49.90
Total  227.90

This wrong calculation is shown on customers e-mails, obviously generating complains.

All orders all received using the v2 API so I wonder if something has changed.

thank you.

**Comment by s-a-s-k-i-a** [comment]
@mikejolley 
Hi Mike and thanks for your reply!

The thing is, in Germany the tax regulations are very strict. Almost everything is regulated and so are handling and display of discounts.

Discount amount may be handled differently according to coupon type:

Example 1
Value coupon.
A customer buys a voucher of a certain EURO value form my woocommerce store. When this value voucher of lets say 50 Euro is purchased, I do not have to pay taxes for that turn over. Because according to german tax regulations, I have not generated an exchange of products/services during that process.
Only when the customer uses the purchased coupon code (value 50 euro) in my woocommerce store, I must pay VAT for that used voucher. So as a store owner in germany I must be able to see immediately which value has been applied by that specific coupon code.
Because I must pay VAT to my tax office in the moment the amount was cashed into my shop so to say.
Problem with how woocommerce displays the summed up discount value right now is furthermore:
a store credit could be set up like this:
value 100 euro
unlimited usage times (until value = 0)

So my customer could apply the coupon more than once to different orders. I must pay taxes for the amount redeemed. So I must be able to see the amount right away.

This applies to all german shop owners who sell value vouchers. - online AND offline.
legal infos here:
1. https://www.ecommerce.jetzt/null-prozent-mehrwertsteuer-auf-gutscheine/
I learned that the UK also handles vouchers the way we do in Germany (english text with perfect description of the VAT issue, yay!):
2. https://www.taxinsider.co.uk/690-How_Vouchers_Affect_the_Amount_of_VAT_Due.html

Since customers can use more than one type of voucher in the same order, we must be able to see the different amounts redeemed and which voucher code (and tbh also: which voucher type) each amount belongs to.

Link No. 2 describes perfectly why we need that output.. and I wonder why noone filed a bug report/or improvement request yet.

**Comment by mikejolley** [comment]
WC core only has one coupon type - that in example 1. Product discount coupons. 

As I said, we can look at this when we do the emails since they all share templates.

**Comment by s-a-s-k-i-a** [comment]
Hello there!

Which is exaclty why this should be looked at a little closer. 
It is possible to sell coupon codes as virtual products with woocommerce core functionality and thus these coupon codes have to handled like above article taxinsider explains. 

Even if not using different coupon types that were added by third party plugins.

Now what do we do with that and the legal obligations?

Logical conclusion would be to look into it and improve the coupon functionality and output in core.

I am glad to hear that it will be looked at in any case of the outcome

Thanks, Mike

**Comment by mikejolley** [comment]
You cannot sell coupons with core alone; virtual products grant nothing. Extensions can.

**Comment by s-a-s-k-i-a** [comment]
Of course you can.. 
Set up a text file containing the value coupon code. 
Set up a virtual, downloadable product with price of value of the coupon.
Add the txt file with coupon code to the product and your are good to go.
