### ISSUE TITLE
Undisclosed tracking via Wistia / Mux

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#16783]
WC admin pages load the third-party JavaScript file //fast.wistia.net/assets/external/E-v1.js :
https://github.com/woocommerce/woocommerce/blob/419244051e893501ff8755a1a568aae7e7e49132/includes/admin/class-wc-admin-help.php#L183 (verified in browser developer tools). This is for the 'Guided Tour' videos in the 'Help' section.

This, in turn, loads //src.litix.io/core/2/mux.js (which you can verify by reading the source or using developer tools in the browser).

And that script's reason for existing appears to be user tracking (as described at https://mux.com, mux.com being the owners of the domain litix.io; and as suggested by a quick read of the code).

WordPress plugin directory rules require all user tracking to be explicit opt-in (https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/ - section 7; "Users may be asked to submit information but it cannot be automatically recorded without explicit confirmation from the user"; "In the interest of protecting user privacy, plugins may not contact external servers without the explicit consent of the user"; also note "The sole exception" further down, making it clear that anything else is covered). That's not currently the case in WooCommerce for this script. It appears to be loading unconditionally, and not including any facility for requesting user consent for the tracking.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16924. Wistia do not allow this to be disabled.
