### ISSUE TITLE
question

### ISSUE THREAD

**Issue by AladinDridi** [woocommerce/woocommerce#16781]
Hello , please i need help to make my this code have solution for thank you page for each products that i choose ... 
it was working ,, but i have client want redirect page for some products with one type of gateway 
, so because github is a tool for help developers , wish you give me any help thanks :) 
this is my solution https://gist.github.com/AladinDridi/5a165f1c782938ff47d84ad821234172

**Comment by AladinDridi** [comment]
because no one help me , any where i found solution by my self : 
add_action( 'woocommerce_thankyou', 'aladin_redirectcustom');
 
function aladin_redirectcustom( $order_id ){
    global $current_user;
    $order = new WC_Order( $order_id );
    $items = $order->get_items();
     $product_id=223074;
     $product_id2=223076;
  foreach ( $items as $item ) {

    $url =''; 
    $url2='';
 if (($order->status!='failed')&&($order->payment_method =='other_payment')&&(( user_can( $current_user, "7eme")))&&($product_id==$item['product_id'])) {
        wp_redirect($url);
        exit;
    }
 else if (($order->status!='failed')&&($order->payment_method =='other_payment')&&(( user_can( $current_user, "7eme")))&&($product_id2==$item['product_id'])) {
     wp_redirect($url2);
     exit;
    }
  }
}

**Comment by mikejolley** [comment]
Please note Github is not a support forum - we don't help with custom code here.

**Comment by AladinDridi** [comment]
okay sorry
