### ISSUE TITLE
woocommerce admin produce page messed up if you have to many option shown from plugins.

### ISSUE THREAD

**Issue by raykai** [woocommerce/woocommerce#16792]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. install WP,  WC,
2. install all the plugins of WMPL v3.8.1
3. install plugin Google Analytics Dashboard for WP (GADWP) or any other addon that adds info in the WC admin all product page.
3. then activate all plugins
4. setup WC
5. setup WMPL with 2 languages
6. go in WMPL > languages > Translation Feedback: turn on Enable Translation Feedback module.
7. go to WC >  products > all Products > setup 1-2 products.

you will see the page messing up as there is not enough room on one line to show all the info:

<a href="https://ibb.co/h3PgDa"><img src="https://preview.ibb.co/jEZ3Rv/Products_Word_Press.jpg" alt="Products Word Press" border="0" /></a>

## Expected/actual behavior

I was expecting to see... a slider bar at the top of the page/line so we could scroll left right when to many info is being shown. a bit like in excel. you can scroll sideways left right to see the rest of the page.

this would be useful for ppl that use some plugins that they need. and see the info at all times.

<a href="https://ibb.co/fwuweF"><img src="https://image.ibb.co/d09UzF/Products_addon_off_Word_Press.jpg" alt="Products_addon_off_Word_Press" border="0"></a>

this side scroll bar could be added to other pages of WC too would be nice to have.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by willgorham** [comment]
This is caused by WordPress. I don't think there is anything WooCommerce can really do here. You can turn off any unused columns in the 'Screen Options' dropdown at the top, which will help.

**Comment by raykai** [comment]
ya that's what im doing in the time being but it's a pain as many if this info is needed for me... i always need to go turn on/ off some option using the 'Screen Options' there to see what i need at every order etc... would be so much faster having all the info we need at ones.

**Comment by raykai** [comment]
on a side note is there a way to let WordPress this idea to fix this?

**Comment by willgorham** [comment]
Submit a Trac ticket https://core.trac.wordpress.org/

**Comment by mikejolley** [comment]
^ thanks. Yes this is WP. You can disable columns in 'screen options' if needed too.
