### ISSUE TITLE
Variations ID's missing on product page

### ISSUE THREAD

**Issue by MilSpecVehicles** [woocommerce/woocommerce#16799]
Hi developers,

Just as others, I am having trouble with the variations part after the last couple of updates of WC. However, I cannot find the same problem, or solution. I do not have the "spinning" ball. It just opens the variation tab. But then I cannot select "expand" all the different variation option codes are "missing" or at least not readable by the tab. I can make a new one, which then shows the ID, but all others are gone, somewhere in the database. So I am not seeing the original files. They do however still function, as the website shows them correctly. They can only not be edited anymore.
![image](https://user-images.githubusercontent.com/31920609/30370945-60b8846c-9879-11e7-892e-095273a9d80a.png)

## Steps to reproduce the issue

1. Open WP/WC
2. Go to product which has "variations"
3. Go to variation tab
4. No variations visible.

## WordPress Environment

`
### WordPress Environment ###

Home URL: https://www.milspecvehicles.nl
Site URL: https://www.milspecvehicles.nl
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Contact Form 7 Honeypot: by Nocean – 1.10
Contact Form 7: by Takayuki Miyoshi – 4.9
e-Boekhouden.nl: by e-Boekhouden.nl – 2.0.8
Google XML Sitemaps: by Arne Brachhold – 4.0.9
Salient Visual Composer: by Michael M - WPBakery.com | Modified by ThemeNectar – 5.0.11
Loginizer: by Raj Kothari – 1.3.7
PayPro Gateways - WooCommerce: by PayPro – 1.2.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
WPML Multilingual CMS: by OnTheGoSystems – 3.8.0
WooCommerce Weight Based Shipping +: by weightbasedshipping.com – 5.1.4
WooCommerce Availability Notifications: by ThemePlugger – 1.1.5
Woocommerce CSV Import: by Allaerd Mensonides – 3.3.6
WooCommerce Multilingual: by OnTheGoSystems – 4.2.3
WooCommerce Parcel Pro: by Ruben van den Ende – 1.1.1
WooCommerce Pay for Payment: by Karolína Vyskočilová – 2.0.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.0.9
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout Fernhout – 2.5.1
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.2
WooCommerce: by Automattic – 3.1.2
WP Related Items (WRI) by WebshopLogic: by WebshopLogic – 1.2.4
WPFront Notification Bar: by Syam Mohan – 1.7
WPML Media: by OnTheGoSystems – 2.2.1
WPML String Translation: by OnTheGoSystems – 2.6.0
WPML Translation Management: by OnTheGoSystems – 2.4.0
WP Overnight Sidekick: by Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.0.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/

### Theme ###

Name: Salient
Version: 8.0.16
Author URL: http://themenectar.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: salient/woocommerce/cart/cart-shipping.php
salient/woocommerce/cart/cart-totals.php
salient/woocommerce/cart/cart.php
salient/woocommerce/cart/shipping-calculator.php
salient/woocommerce/checkout/form-checkout.php
salient/woocommerce/checkout/review-order.php
salient/woocommerce/checkout/terms.php version 3.1.0 is out of date. The core version is 3.1.1
salient/woocommerce/content-product.php
salient/woocommerce/content-single-product.php
salient/woocommerce/loop/add-to-cart.php
salient/woocommerce/loop/loop-start.php
salient/woocommerce/myaccount/form-login.php
salient/woocommerce/single-product/product-image.php
salient/woocommerce/single-product/tabs/description.php
salient/woocommerce/single-product/tabs/tabs.php

Outdated Templates: ❌Learn how to update
`
I hope you could help out on a solution.

**Comment by mikejolley** [comment]
Hi,

As with other similar closed issues, this is no doubt an extension conflict. 

```
## Isolating the problem

<!-- Mark completed items with an [x] -->

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above
```

I'd guess related to WPML but you'll need to narrow this down yourself. We cannot access your store or do this for you.

Thanks

**Comment by MilSpecVehicles** [comment]
I deactivated all WPML plugins and reactivated, and somehow I can have anything activated again without the previous confilct. strange but it works again. Thank you for the tip!
