### ISSUE TITLE
Cannot edit attributes or variations 

### ISSUE THREAD

**Issue by bsparn** [woocommerce/woocommerce#16790]
All of our users are having problems with Woo Commerce when adding variations or editing attributes. The spinning ball loading icon appears and then never stops. 

I have used this feature for months and it has suddenly stopped working.

I have increased the memory and deactivated some plugins and the problem still exist.

![capture](https://user-images.githubusercontent.com/31777230/30333201-61a92fe0-97aa-11e7-88ec-8a358e95669e.PNG)

**Comment by mikejolley** [comment]
Possibly related to https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x but will be a conflict. **Please rule out conflicts with themes and plugins before posting here** as asked on the new issue page.
