### ISSUE TITLE
[3.2] Backwards incompatible order of cart totals calculation when adding fees

### ISSUE THREAD

**Issue by ChaseWiseman** [woocommerce/woocommerce#16794]
Prior to v3.2, `WC_Cart::$cart_contents_total` is set when calculating the cart item totals, which happens before `WC_Cart::calculate_shipping()` and `WC_Cart::calculate_fees()`. In master, this will no longer be set until the [end of calculation](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart-totals.php#L758) with the other totals.

This will break code that is hooking into `woocommerce_cart_calculate_fees` and setting the fee cost based on the contents total, as would be the case for percentage fees.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Hook into the `woocommerce_cart_calculate_fees` action to add a custom fee
2. Define that fee's cost based on the value of `WC_Cart::$cart_contents_total`, i.e. `$cost = $cart->cart_contents_total * 0.5;`

## Expected/actual behavior

When I follow those steps, I see...

On v3.1.2 or earlier, the fee's cost is added appropriately
On `master` the fee is $0

I was expecting to see...

Consistent behavior in all versions

Could we call `WC_Cart::set_cart_contents_total()` within `WC_Cart_Totals::calculate_item_totals()` instead?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16831
