### ISSUE TITLE
Product importer don't support multi valued fields with commas in the values

### ISSUE THREAD

**Issue by frgmatos** [woocommerce/woocommerce#16804]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product attribute having one or more commas on its name
2. Create a product using this attribute
3. Export products
4. Import products

## Expected/actual behavior

When I follow those steps, the substrings before and after the comma were imported as new attributes.

I was expecting to see the original attribute imported instead. IMO another character could be used to separate multi valued fields (such as tab). Alternatively, there could be support for escaping commas in a multi valued field.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
From 3.2, you can wrap values in quotes if they contain commas. That should solve this.

**Comment by mikejolley** [comment]
Confirmed the exporter escapes also.
