### ISSUE TITLE
Unable to get products based on `attribute`

### ISSUE THREAD

**Issue by saikumar-madana** [woocommerce/woocommerce#16801]
I am trying to retrieve products based on `attributes`. What I am trying to do is

`https://somedomain.com/someapp/wp-json/wc/v2/products?Attributes=Recommended`

But. I can't able to access the data. 

I have gone through so many links. But, I did not find anything related to me.

![untitled](https://user-images.githubusercontent.com/17292167/30374841-f4aea0c8-98a3-11e7-94fa-ef4b50e768ce.png)

Help me solve this.

**Comment by mikejolley** [comment]
Supported params are listed in the docs https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products Attributes is not one of them.

**Comment by saikumar-madana** [comment]
`attribute` parameter is also there. But, I can't get products based on that.

**Comment by mikejolley** [comment]
Thats used in conjunction with other props.
