### ISSUE TITLE
Group Product API issue

### ISSUE THREAD

**Issue by ayushsingh007** [woocommerce/woocommerce#16813]
In case of Woocommerce Product API we are using :-
'on_sale' => $product->is_on_sale()

In case of group product, it shows 
'on_sale' => true

Though, there is no meaning of sale price in case of group product and hence, creating issue while creating app. So, its a suggestion to put a check on it like maybe like this 

'on_sale'            => ($product->product_type == 'grouped') ?  'false' : $product->is_on_sale()

**Comment by mikejolley** [comment]
Doesn't this show on_sale based on children?

**Comment by mikejolley** [comment]
Confirmed. This is read only, and for grouped products they will be on sale if a child is on sale.
