### ISSUE TITLE
Bug: post_title it is deleted by the instance of the class WC_Product_Variation

### ISSUE THREAD

**Issue by zjkiza** [woocommerce/woocommerce#16818]
Hi, 
I'm using Woo commerce 3.1.2 with Wordpress 4.8.1.
if you create instance of the class WC_Product_Variation for product who has 
post_type='product' , then it delete post_title for this product. In version woocommerce 3.0.9 and down, It did not happen.

The problem is in class WC_Product_Variation_Data_Store_CPT , function read( &$product ). 

Currently the solution to this problem : before making a instance of the class, check if it's an article post_type='product', if so, do not allow to create istance for this product.

**Comment by mikejolley** [comment]
Variations do not have user defined titles so we should not need to add title handling code for them. 

Simple fix; don't use classes directly. Use the `wc_get_product` function. It handles instantiation for you and returns the correct class.

We could fix this ( @kloon  ) by preventing products from being used with WC_Product_Variation class but this would return an exception and be a breaking change. It also wouldn't help you :)

**Comment by zjkiza** [comment]
The moment you make an instance for product, in database your post_title (name of product) for this product is deleted !!!

**Comment by mikejolley** [comment]
Because variation titles are auto generated. Use `wc_get_product`.

**Comment by zjkiza** [comment]
As soon as you do not get the results you need to get. Here are the comparisons.

-------------------------------------------------------------------
$product = new WC_Product_Variation(31);
$product1->get_attributes()

// get_attributes for post_type='product_variation' 

Array
(
    [pa_size] => 44
    [pa_color] => white
)

-------------------------------------------------------------------
$product = new WC_Product_Variation(30);
$product1->get_attributes()

// get_attributes for post_type='product'

Array
(
)

-------------------------------------------------------------------

If we make the call of the function you have suggested, we can not get the results we expect

-----------------------------------------------------------------
$product1 = wc_get_product(30);
$product1->get_attributes()

// get_attributes for post_type='product'

Array
(
    [pa_size] => WC_Product_Attribute Object
        (
            [data:protected] => Array
                (
                    [id] => 4
                    [name] => pa_size
                    [options] => Array
                        (
                            [0] => 28
                            [1] => 27
                            [2] => 26
                        )

                    [position] => 0
                    [visible] => 1
                    [variation] => 1
                )

        )

    [pa_color] => WC_Product_Attribute Object
        (
            [data:protected] => Array
                (
                    [id] => 5
                    [name] => pa_color
                    [options] => Array
                        (
                            [0] => 29
                            [1] => 30
                        )

                    [position] => 1
                    [visible] => 1
                    [variation] => 1
                )

        )

    [pa_ean] => WC_Product_Attribute Object
        (
            [data:protected] => Array
                (
                    [id] => 3
                    [name] => pa_ean
                    [options] => Array
                        (
                            [0] => 31
                        )

                    [position] => 2
                    [visible] => 1
                    [variation] => 
                )
        )
)
-------------------------------------------------------------------
As you can see, you are wrong!

wc_get_product can not replace WC_Product_Variation . 
This worked to the version of woocommerce 3.0.9 and lower.

**Comment by mikejolley** [comment]
Ok let me ask you a question. Why are you using the WC_Product_Variation class for a product when **a product is not a variation**?

The usage is wrong?

**Comment by zjkiza** [comment]
Do not use it wrong!
If the product is single, then function it should return an empty array.

And from version 3.1 and higher, it will return an empty array but you also delete the name of the article (post_title in wp_post) ! This is a serious mistake.

**Comment by mikejolley** [comment]
If the product is simple, WC_Product_Variation is not appropriate. The class is WC_Product_Simple. Thats what wc_get_product will return.

**Comment by zjkiza** [comment]
Appropriate or not, the post title is deleted.

The error is obvious!

**Comment by mikejolley** [comment]
I know what you're saying but as I said earlier:

> variation titles are auto generated.

On read, if the variation title is not in the correct format it's changed and written. You would not see this error if you were using the product classes as intended.
