### ISSUE TITLE
Products with Emoticons in the Title

### ISSUE THREAD

**Issue by baddel73** [woocommerce/woocommerce#16810]
If you use emoticons in a product title, the product is not added to the order. 

## Steps to reproduce the issue

1. Add a Product with an emoticon in the title
2. Add the product to the cart (it shows in the cart)
3. Finnisch the Order. The Product will add to the total price and will be shown in the order during checkout, but will not show up in the confirmation, nor in the back office.
4. You also cannot add an item with an emoticon in the title to an order manually.

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://www.sewingkitchen.de
Site URL: http://www.sewingkitchen.de
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.15
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.46.0
OpenSSL/1.0.2e

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ✔

### Active Plugins (24) ###

amr event lists with ical files: von anmari – 5.0
Blog2Social: Social Media Auto Post & Scheduler: von Blog2Social
Adenion – 4.3.2

Contact Form 7: von Takayuki Miyoshi – 4.9
Duplicate Post: von Enrico Battocchi – 3.2
Enable Media Replace: von Måns Jonasson – 3.1.1
Envato WordPress Toolkit: von Envato – 1.7.3
Flamingo: von Takayuki Miyoshi – 1.7
Google Analyticator: von SumoMe – 6.5.4
My Private Site: von David Gewirtz – 2.14.1
Loco Translate: von Tim Whitlock – 2.0.15
Nextend Facebook Connect: von Nextendweb – 2.0.2
Nextend Google Connect: von Roland Soos
Jamie Bainbridge – 1.6.1

Woocommerce Onsale Page: von wpgenie – 1.0.9
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 2.2.6
UpdraftPlus - Backup/Restore: von UpdraftPlus.Com
DavidAnderson – 1.13.7

Vendidero Helper: von Vendidero – 1.1.4
WooCommerce Germanized Pro: von Vendidero – 1.8.1
WooCommerce Germanized: von Vendidero – 1.9.1
WooCommerce Preisberechner für Abmessungen (Fläche, Gewicht, Volumen): von SkyVerge – 3.12.1
WooCommerce Min/Max Quantities: von WooCommerce – 2.3.18
WooCommerce Google Product Feed: von Lee Willis – 7.0.8 – 7.1.10 ist verfügbar
WooCommerce: von Automattic – 3.1.2
WooSidebars: von WooThemes – 1.4.3
YITH WooCommerce Wunschliste: von YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #4 - /shop/
Warenkorb: #5 - /shop/warenkorb/
Kasse: #6 - /shop/kasse/
Mein Konto: #7 - /mein-konto/

### Theme ###

Name: Flatsome
Version: 3.3.8
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`
</details>

**Comment by mikejolley** [comment]
Could be a plugin issue or different DB encoding. Emjois are supported. Example:

<img width="947" alt="2017-09-15 at 17 08" src="https://user-images.githubusercontent.com/90977/30507370-beff2fe2-9a38-11e7-9bd8-35cffa4ee8ce.png">

I tested checkout as well as adding items to an order manually. Works as expected.
