### ISSUE TITLE
Product attribute permalink doesn't work

### ISSUE THREAD

**Issue by aonzzung** [woocommerce/woocommerce#16825]
Normally, I can filter product by attribute via browsing **"mysite.com/shop/?filter_brand=tesla"**

However, when I tried to call it via "mysite.com/brand/tesla" but it doesn't work and show 404 not found error.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Pre-init: a product to test already has global attribute "brand=tesla"

**Case 1 :**
1.  Leave the default setting 
![fkjkl](https://user-images.githubusercontent.com/3109162/30468051-12920042-9a13-11e7-8040-062a52c762cf.png)

2. Browse : mysite.com/brand/tesla

**Case 1 :**
1.  Enter 'Product attribute base' option : let's say "myattr"

2. Browse : mysite.com/myattr/brand/tesla

Both cases show 404 not found error

## Expected/actual behavior

When I follow those steps, I see...
>>>404 not found error

I was expecting to see...
>>> Ability to filter by product attribute permalink

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost
Site URL: http://localhost
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 1,000 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.32 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.1.6 mod_ssl/2.2.32 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.1.6
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: tagm_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: THB (฿)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
variable (variable-2)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #11912 - /%e0%b9%80%e0%b8%8a%e0%b9%87%e0%b8%84%e0%b8%a3%e0%b8%b2%e0%b8%84%e0%b8%b2%e0%b8%a5%e0%b9%88%e0%b8%b2%e0%b8%aa%e0%b8%b8%e0%b8%94/
Cart: #11913 - /cart/
Checkout: #11914 - /checkout/
My account: #14 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
Go to Attributes > Brand, edit the attribute, then enable the archive (there is an option), and finally re-save permalinks.

If it 404s from then, ensure there is no page or other taxonomy called 'brand' because it will conflict. Test another attribute if unsure.

Thanks
