### ISSUE TITLE
Sale price end day doesn't work

### ISSUE THREAD

**Issue by kenniswong** [woocommerce/woocommerce#16827]
The scheduled sale price end date doesn't work anymore. It passes the sale end date without going back to the original price.

**Comment by mikejolley** [comment]
Usually cron related if this fails: https://nicola.blog/2016/11/01/scheduled-events-wordpress-cron-jobs/

Could also be a conflict but I'm not sure what else you're running. Please use the helpdesk if you need help with debugging this on your store.

> Hi there! This form is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. If you need technical support from a human being, please submit a ticket via the helpdesk instead: https://woocommerce.com/contact-us/ 
> 
> Usage questions can also be directed to the public support forum here: https://wordpress.org/support/plugin/woocommerce, unless this is a question about a premium extension in which case you should use the helpdesk.
> 
> If you have a feature request, submit it to: http://ideas.woocommerce.com/forums/133476-woocommerce 
> 
> Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action. -->

**Comment by endtone** [comment]
#22069
