### ISSUE TITLE
every thin go blank after installing woocommerce

### ISSUE THREAD

**Issue by salajimo** [woocommerce/woocommerce#16828]
hi every one
i've installed woocommerce for wordpress 4.8.1 then if i change the language from english to french or any other lang every thin go blank 
i can't eve access my dashbord so every time i change the language i need to open FTP and manualy delet the woocommerce plugin the change th lung to english and install the plugin again

**Comment by mikejolley** [comment]
Please see the message on https://github.com/woocommerce/woocommerce/issues/new - this issue lacks details, and sounds like a problem with 3rd party code. Narrow the issue down to core before logging here, or contact support.

Thanks
