### ISSUE TITLE
Terms & Conditions link target=_self

### ISSUE THREAD

**Issue by sybrew** [woocommerce/woocommerce#16832]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Issue description

**This is a regressive issue**

The terms & conditions link open within the same window, directing the customer from the page.

In earlier versions, the link was annotated with `target=_blank`.

<kbd>CTRL+F</kbd> or <kbd>CMD+F</kbd> to easily find the changes in the code below:
`<a href="%s"`

## Issue location 2.6.13

https://github.com/woocommerce/woocommerce/blob/bff95262cb17e6bdadd027a3e5223f2d2947b331/templates/checkout/terms.php#L17

## Issue location 3.2.0

https://github.com/woocommerce/woocommerce/blob/83f60c68abd6fbd5b3311937fa78ad6a146422aa/templates/checkout/terms.php#L26

## Solution

Add `target=_blank` back, or make it at least filterable/optional.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16836
