### ISSUE TITLE
Customizer: Price Filter not loading when adding widget the first time.

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce#16834]
When adding the Price Filter widget the first time, in the Customizer, to a Sidebar location, it does not show properly:
<img width="345" alt="screen shot 2017-09-15 at 3 28 07 pm" src="https://user-images.githubusercontent.com/3220162/30505644-d5070034-9a2a-11e7-9fff-a1537102090c.png">

## Steps to reproduce the issue

1. Open up the Customizer
2. Add the Price Filter 
3. You will see a broken price filter
4. Save it and Refresh, then the price filter will show up correctly:
<img width="322" alt="screen shot 2017-09-15 at 3 36 18 pm" src="https://user-images.githubusercontent.com/3220162/30505770-a3999a88-9a2b-11e7-9f3e-6e656fd33697.png">

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16838
