### ISSUE TITLE
Hidden order, report show 15.000$ too much

### ISSUE THREAD

**Issue by EllingP** [woocommerce/woocommerce#16837]
Hei! On 15.09 the report show 15.000$ too much, my actual sale that date was 3.000$, but the report shows 18.000$. I have tried to set all orders "On hold", update total, but that didn't help.

Anyone seen this before?

**Comment by kloon** [comment]
This is usually related to the data being cached. If you perhaps removed or changed the status of some orders I'd wait it out for a day for the reporting data to update.

Also worth noting that totals included in the sales are for different order statuses, processing, completed and processing.
