### ISSUE TITLE
[master] API key/secret "Copy" buttons not working properly.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#16845]
This happens using the master branch in both Chrome and Firefox on Mac. Opening an issue so I don't forget.

1. Clicking the "Copy" button to copy an API key or secret does not copy anything.

2. I see in the inspector that the "data-tip" on the element changes to "Copied!" when clicked, but there is no visual notification of this. Hovering over the button or anywhere else does not show "Copied!".

EDIT: I have done some more research. It looks like the ZeroClipboard library uses Flash for everything. Flash is blocked by default on all major browsers now. We're going to have to switch to something like https://clipboardjs.com/ if we want to use a library or https://stackoverflow.com/a/30810322 if we want to do it with regular JS.

**Comment by MillerMedia** [comment]
Submitted a pull request for an update to this #16876
