### ISSUE TITLE
No taxes and shipping shown for guest users

### ISSUE THREAD

**Issue by Mrittikacraft** [woocommerce/woocommerce#16842]
Hi!

I recently developed my e-commerce website using Woocommerce and added in shipping and taxes. Everything was functioning well until last evening when suddenly the website stopped displaying taxes and shipping options for guest users. I now have to force all my users to sign up and fill out their addresses under their accounts, after which, I do not have any problem at all- the taxes and shipping show up exactly as they are supposed to. Earlier, this information was available on the basket and checkout pages for all users (guest or registered).

My default customer location is set to Geolocate (with page caching support)

I have tried almost every solution offered online but nothing seems to work. As of now, Guest Checkout is disabled on my website. Any help on this issue is appreciated. Thank you!

Please find my website at http://www.mrittika.co.in

Below is my system status report:

`
### WordPress Environment ###

Home URL: http://www.mrittika.co.in
Site URL: http://www.mrittika.co.in
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.22
PHP Post Max Size: 512 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wptq_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (19) ###

WooCommerce PayUMoney and Citrus combined: by Citruspay – 2.0
AfterShip - WooCommerce Tracking: by AfterShip – 1.7.1
Akismet Anti-Spam: by Automattic – 3.3.4
CodeGuard Website Backups: by The CodeGuard Team – 0.66
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.14
WooCommerce Customizer(with Genesis support): by DevelopersQ – 5.1
Homepage Control: by WooThemes – 2.0.2
Jetpack by WordPress.com: by Automattic – 5.3
Meta Slider: by Team Updraft – 3.5.1
Page Links To: by Mark Jaquith – 2.9.9
SOFT79 Cart Links for WooCommerce: by Jos Koenis – 1.1.3
Styleguide - Custom Fonts and Colors: by BinaryMoon – 1.6.1
Super Socializer: by Team Heateor – 7.9.4
WC Paytm Gateway: by Varun Sridharan – 1.1
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.2.1
Advanced Order Export For WooCommerce: by AlgolPlus – 1.4.5
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.3
WooCommerce: by Automattic – 3.1.2
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1303 - /shop/
Basket: #1304 - /basket/
Checkout: #1305 - /checkout/
My account: #1306 - /my-account/

### Theme ###

Name: Deli
Version: 2.0.9
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Could you ask this on the helpdesk so someone could login and check settings? I think it's more likely config related than a core bug.

https://docs.woocommerce.com/ - support link.

Thanks

**Comment by Mrittikacraft** [comment]
Hello Mike,

I initially posted my query there and provided login details as well
following which, I was redirected to the woocommerce forum. I don't know
what to do now. Will be glad for any help.

Best,

Nandini

**Comment by Mrittikacraft** [comment]
I'm sorry. That was a WordPress.org forum. I have raised a ticket on the
woocommerce website and am waiting for a response. Apologies for the
confusion.

Best,

Nandini

**Comment by marguy1** [comment]
Guests likely need to enter an address before shipping rates will show. When not logged in, there is no address yet attached to the user. The shipping rates should show up me once the guest enters an address.
