### ISSUE TITLE
Escaping for the like clause in the background process class is incorrect

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce#16846]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Look at SQL statement after it comes out of `$wpdb->prepare()` [here](https://github.com/woocommerce/woocommerce/blob/master/includes/libraries/wp-background-process.php#L272-L278)
2. Notice that underscores aren't escaped, though they should be as the variable part of the query string is the `%`, everything else stays the same.

## Expected/actual behavior

`$this->identifier` is `$this->prefix . $this->action_name`, so the query will end up being

```
SELECT * FROM wp_options WHERE option_name LIKE 'wp_name_of_action_batch_%' ORDER BY option_id ASC LIMIT 1;
```

Problem there is that since `_` is a wildcard, MySQL will stop using more than 2 characters in the index, which will make it work a lot more than necessary.

Instead the SQL query should be:

```
SELECT * FROM wp_options WHERE option_name LIKE 'wp\_name\_of\_action\_batch\_%' ORDER BY option_id ASC LIMIT 1;
```

The referenced code should be:

```
		$key = $wpdb->esc_like( $this->identifier . '_batch_' ) . '%';

		$query = $wpdb->get_row( $wpdb->prepare( "
		SELECT *
		FROM {$table}
		WHERE {$column} LIKE %s
		ORDER BY {$key_column} ASC
		LIMIT 1
		", $key ) );
```

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

not important for this bug

I would create a PR, but don't actually know where (which repository) to put it as the file is part of a library, and many plugins seem to share it.

**Comment by mikejolley** [comment]
Thanks, I've submitted a PR to the library. We'll keep our version up to date anyhow.
