### ISSUE TITLE
Add Column "Brand" to import & export

### ISSUE THREAD

**Issue by artdias90** [woocommerce/woocommerce#16849]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to Products -> Click  or "Import"
2. Upload a CSV file
3. Check the column mappings

## Expected/actual behavior

**When I follow those steps, I see...**
No "Brand" option for mappings
**I was expecting to see...**
"Brand" option for mappings to map product Brands

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

WooCommerce: |   | 3.1.2
WordPress: |   | 4.8.1

</details>

**Comment by artdias90** [comment]
I have come as far as adding a parser: 
```
			/**
	 * Parse a brand field from a CSV.
	 *
	 * @param  string $value Field value.
	 * @return array
	 */
	public function parse_brands_field( $value ) {
		if ( empty( $value ) ) {
			return array();
		}

		$names = array_map( 'trim', explode( ',', $value ) );
		$brands  = array();

		foreach ( $names as $name ) {
			$term = get_term_by( 'name', $name, 'brand' );

			if ( ! $term || is_wp_error( $term ) ) {
				$term = (object) wp_insert_term( $name, 'brand' );
			}

			if ( ! is_wp_error( $term ) ) {
				$brands[] = $term->term_id;
			}
		}

		return $brands;
	}
```

but the relationship to the product is not being made. Not sure the next step

**Comment by mikejolley** [comment]
Extensions (like brands) need to add support for the importer. This will not be added to core.

I see an issue is already logged in the brands extension so it's on our radar.

Thanks
