### ISSUE TITLE
[3.2 Beta] Coupon Spend Restrictions are Broken

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#16840]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a coupon for any discount
1. Set a usage restriction: minimum spend = $50
1. Create a cart with total > $50
1. Try to apply coupon and see that it won't apply: http://cloud.skyver.ge/19342H2m0123

You'll also see this with max spend: limit max spend at $30, cart is $60 -- coupon still applies

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

WooCommerce 3.2 master as of this morning

**Comment by kloon** [comment]
Did some tests and getting the same results.

The [validate_coupon_minimum_amount and validate_coupon_maximum_amount methods](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-discounts.php#L586-L611) takes a subtotal parameter that is never passed when calling these methods via [is_coupon_valid](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-discounts.php#L834) resulting in the checks always failing.

**Comment by mikejolley** [comment]
👍 Should be fixed in https://github.com/woocommerce/woocommerce/pull/16866
