### ISSUE TITLE
webhook not working when add apache authentication basic

### ISSUE THREAD

**Issue by CaryQY** [woocommerce/woocommerce#16848]
Hi all, sorry to add new issue 

our website is under building , we donnot want to show public now ,so we added apache  password authentication. 

we want when order status updated then webhook send info to another server to handle orders

we also have a local area network test server . both of them webhook cannot work when config apache authentication basic.

I wonder apache authentication will work when get IN request why OUT request also been  effected.

## Steps to reproduce the issue

1.   htpasswd -c /var/woopass woo
2.   vim .htaccess
3.    add  

```
AuthType Basic
AuthName "Restricted Files"
AuthUserFile /var/woopass
Require user woo

```

4.  change any order status 

## Expected/actual behavior

When I follow those steps,  another server cannot get the request from webhook

**Comment by mikejolley** [comment]
The other server needs to access the API I presume. The REST API will also be restricted with the above code.

I've not tried to setup this before, but you could look at https://stackoverflow.com/questions/30629853/htaccess-authentication-rest-api-methods

Either way, this isn't a 'bug', just a server config issue.
