### ISSUE TITLE
Woocommerce pricing display for single and variations

### ISSUE THREAD

**Issue by decimoseptimo** [woocommerce/woocommerce#16847]
In regard to CSS styling there is not separation from the 'price' of a product, and the 'price ranges' from above the 'variations price' in a variation product.

There should be a way of targeting them separately. As of now, whatever style you apply to a 'price range' in a variation product, becomes the styling of the 'price' in another single product.

**Comment by mikejolley** [comment]
You can target specific product types right now. e.g. `.product-type-variable .price` for variable prices and so on.

**Comment by decimoseptimo** [comment]
Not so sure.
In a variation product, counting from `.summary`

a)When there are different prices:
(title) `div.summary.entry-summary > h1`
(price range) `div.summary.entry-summary > form > p.price`
(variation price) `div.summary.entry-summary > form > div.woocommerce-variation.single_variation > div.woocommerce-variation-price > span`

b)When all prices are the same:
(title) `div.summary.entry-summary > h1`
(price range) none, as expected?
(variation price) `div.summary.entry-summary > form > p.price` wait! same markup as price range?

This is bad because the same markup is used for different things.

My current solution is to always show variation prices:
```php
function ssp_always_show_variation_prices($show, $parent, $variation) {
    return true;
}
add_filter( 'woocommerce_show_variation_price', 'ssp_always_show_variation_prices', 99, 3);
```

**Comment by mikejolley** [comment]
You can still target each with different selectors no? The .price markup is used for all prices ran though wc_price function.

**Comment by decimoseptimo** [comment]
From an HTML/CSS perspective. A 'price range' and a 'price', each should have a markup and/or styling that's predictable through different pages.

I achieved this only after configuration, not by default.

**Comment by mikejolley** [comment]
Maybe submit a PR showing what you're after in that case?
