### ISSUE TITLE
Update Woocommerce Order API using Guzzle returns woocommerce_api_missing_callback_param

### ISSUE THREAD

**Issue by itzRamkumar** [woocommerce/woocommerce#16851]
Hi all,
I can able to get the Order Details using guzzle. But i can't able to update the Order.

Here is my code:

<pre>use stdClass;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;

$data = new stdClass();
$data->fulfillment = new stdClass();

$trackingUrl = "123456789";

$shopUrl = "localhost/Test";
$consumerKey = "cs_mykey";
$consumerSecret = "ck_mykey";
$orderId = "123";

$subPath = "/wc-api/v2/orders/".$orderId;

$data->fulfillment->tracking_url = $trackingUrl;
$data->fulfillment->status = 'completed';

$headers = array(
   'Content-Type: application/json'
);

$method = "POST";

$url = "http://localhost/Test/wc-api/v2/orders/123?oauth_consumer_key=ck_mykey&consumer_key=ck_mykey&consumer_secret=cs_mykey&oauth_timestamp=1505544895&oauth_nonce=9ecd49e80860e09ddaf91f148451532620976b8d&oauth_signature_method=HMAC-SHA256&oauth_signature=mysignature";

$Result = callApi($url, json_encode($data), $headers, $method);

print_r($Result);

function callApi($url = NULL, $body = NULL, $headers = array(), $requestType = "POST")
{
   $client = new GuzzleHttp\Client();
   $body = $body ? $body : new stdClass();
   $request = $client->Request($requestType, $url, $headers, json_encode($body));
   if($requestType == "POST")
      $response = $client->send($request, ['timeout' => 10]);
   if($requestType === 'DELETE') {
      return $httpCode = $response->getStatusCode();
   } else {
      $data = $request->getBody()->getContents();
      return json_decode($data);
   }
}
</pre>
Using the above code i will get the error as below

resulted in a 400 Bad Request response: {"errors":[{"code":"woocommerce_api_missing_callback_param","message":"Missing parameter data"}]} ' in C:\xampp\htdocs\Guzzle\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:113 Stack trace: #0 C:\xampp\htdocs\Guzzle\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response)) #1 C:\xampp\htdocs\Guzzle\vendor\guzzlehttp\promises\src\Promise.php(203): in C:\xampp\htdocs\Guzzle\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line 113

I don't know what i missed in above. Help me to sort out.

Thanks.

**Comment by mikejolley** [comment]
Look at the raw data you are sending to the endpoint. It needs to be sent as valid JSON, with JSON headers.

https://stackoverflow.com/questions/22244738/how-can-i-use-guzzle-to-send-a-post-request-in-json

The logged issue is related to your code rather than the API itself it seems. Please don't log specific client errors here unless the same error occurs on multiple clients :) We show how to use Insomcia here for example over https https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API 

Thanks
