### ISSUE TITLE
Support for Hierarchical Attributes

### ISSUE THREAD

**Issue by skills-up** [woocommerce/woocommerce#16855]
Hi,

I am looking for a feature which looks like as if it was available earlier, but is no longer there. It is related to attribute hierarchy, specially hierarchical colors. I didn't see this being dropped in any change log, but a web lookup suggests that it is not officially supported (in fact, never was).

On a fashion website, we earlier used to group the wide variety of colors under a few generic color names, such as, **_Sky Blue_**, **_Navy Blue_**, **_Royal Blue_** etc. would all be children of **_Blue_**. This allowed for easy filtering of products, both using generic (parent) attribute **_Blue_**, and the specific (child) attributes such as **_Navy Blue_**.

We either seem to have lost the relationship WC 3.x onwards, or the underlying relationship structure doesn't support it anymore. So, now a search for Blue, won't return products with Navy Blue or Sky Blue color.

Request you to please (re) add support for hierarchical attributes.

Thanks,
Gaurav

**Comment by mikejolley** [comment]
It was enabled by accident in older versions, but was not exposed in the UI of variations/products. Those have always used a flat structure.

We don't have short term plans to support hierarchical attributes, but you can upvote it on the ideas board. I think this is the closest thing to what you're asking for http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/3368079-attribute-groups-for-woocommerce

Thanks
