### ISSUE TITLE
[3.2 Beta] Breaking changes to conditions under which the 'woocommerce_shipping_method_chosen' action is triggered

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#16853]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

With 3.2-beta-2, the `'woocommerce_shipping_method_chosen'` action is no longer being triggered under the same conditions as it would be in prior versions due to changes with how the chosen shipping method is determined.

This is because the [conditional check to fallback to default shipping method in WC 3.2](https://github.com/woocommerce/woocommerce/blob/3.2.0-beta.2/includes/wc-cart-functions.php#L416) removes a condition found in the 3.1.2 equivalent condition ([here](https://github.com/woocommerce/woocommerce/blob/3.1.2/includes/class-wc-shipping.php#L293)). Specifically, the final check for `sizeof( $package['rates'] ) !== $method_count` is no longer removed (props @james-allan for this diagnosis).

While the new approach is much cleaner, it can lead to breakages in plugins like: 
 https://github.com/Prospress/woocommerce-subscriptions/issues/2344#issuecomment-330131341

We're working on fixing that in Subscriptions in https://github.com/Prospress/woocommerce-subscriptions/pull/2345, but I wanted to point out the breaking change.

A quick scan of the 3.2.0 codebase also shows the `'shipping_method_counts'` session value has been removed entirely from 3.2.0, which could also be considered a breaking change as it was public data that could be accessed by 3rd party plugins in prior version.

**Comment by mikejolley** [comment]
I've added this back in https://github.com/woocommerce/woocommerce/pull/16867

It's not really necessary to keep around so we'll nuke it in 4.0.
