### ISSUE TITLE
Invalid XHR response - BOM character

### ISSUE THREAD

**Issue by Smilebags** [woocommerce/woocommerce#16854]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Visit https://www.pressingmatters.com.au/shop/
2. Open Dev Tools and view network activity
3. Press any Add to Cart button and view XHR response

## Expected/actual behavior

When I follow those steps, I see a misplaced BOM character \ufeff in the JSON response

I was expecting to see a non-corrupt response.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment
Home URL: https://www.pressingmatters.com.au
Site URL: https://www.pressingmatters.com.au
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Microsoft-IIS/8.5
PHP Version: 5.6.31
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Disable Comments: by Samir Shah – 1.7
Google Analytics: by ShareThis – 2.1.3
Meeting Scheduler by vCita: by vCita.com – 3.14.2
Ninja Forms: by The WP Ninjas – 3.2.1
Pinterest Pin It Button For Images: by Canha – 1.1.0
Redirection: by John Godley – 2.7.3
Page Builder by SiteOrigin: by SiteOrigin – 2.5.12
SiteOrigin Masonry: by Greg Priday – 1.0.3
Toggle The Title: by Avner Komarow – 1.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.7

WooCommerce Checkout Manager: by Visser Labs – 4.1.6
WooCommerce eWAY Payment Gateway: by WooThemes – 3.1.13
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce jQuery Cookie Fix: by Splashing Pixels (Roy Ho) – 1.0
WooCommerce Product Details Customiser: by jameskoster – 0.2.0
WooCommerce: by Automattic – 3.1.2
Wordfence Security: by Wordfence – 6.3.18
Yoast SEO: by Team Yoast – 5.4
WP-Mail-SMTP: by Callum Macdonald – 0.10.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #467 - /shop/
Cart: #468 - /cart/
Checkout: #469 - /checkout/
My account: #470 - /my-account/

### Theme ###

Name: Vantage Premium
Version: 2.4.2
Author URL: http://siteorigin.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
Since this is only being inserted on your store, I don't think it's core. We'd see the BOM char on all sites if it were core.

https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=ufeff&type=

This BOM char does not appear in our codebase.

>  This bug happens with only WooCommerce plugin active

I'm not sure if you really checked this, but you'll want to do the same for the theme. 

If it still shows up, you may want to reinstall WordPress and ensure files like wp-config.php and anything else that has been customised have not had a space/char inserted accidentally.

Either way, it's likely the space char has been inserted accidentally into a file on your site. Thats happened to me before :)

Thanks
