### ISSUE TITLE
issue in error message of woo commerce customers REST API in multilingual

### ISSUE THREAD

**Issue by ronakganatra9** [woocommerce/woocommerce#16858]
I have a multilingual site and its REST API enabled when I am using customers API( provided by default in WooCommerce REST API) and it returns any error then it returns an error message in the English language always. If I pass language French though it returns an error message in English only.

**Comment by mikejolley** [comment]
The API is not multilingual unless your multilingual adds support for it. Since it's an API, language should be irrelevant anyway. Use the error codes and localise in your app.
