### ISSUE TITLE
Another calculation error.

### ISSUE THREAD

**Issue by Flyingsirkus** [woocommerce/woocommerce#16863]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product withe a price of 6.42 and a tax-rate of 20%.
2. Buy two

## Expected/actual behavior
Total should be 15.40, but is 15.41

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://silvere.test/woocommerce
Site URL: http://silvere.test/woocommerce
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.0 mod_ssl/2.2.29 OpenSSL/0.9.8zg DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version: 7.0.0
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/0.9.8zd

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.42 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 35: Unsupported SSL protocol version
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. 200

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
Total Database Size: 2.51MB
Database Data Size: 1.68MB
Database Index Size: 0.83MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.08MB + Index: 0.02MB
wp_postmeta: Data: 0.09MB + Index: 0.06MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 18
customize_changeset: 1
page: 7
post: 2
product: 16
revision: 2
shop_coupon: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: par Automattic – 3.2.0-beta.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base boutique: #4 - /shop/
Panier: #5 - /cart/
Commande: #6 - /checkout/
Mon compte: #7 - /my-account/
Terms and conditions: ❌ Page non définie

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
6.42 + 6.42 = 12.84 * 1.2 = 15.408

Rounded up to 15.41. Taxes calculate on the line. Not per item.

https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce

**Comment by Flyingsirkus** [comment]
Hi.

I mus be missing something here.

If the displayed price for one item is 7.70, the price for two item must be 14.40 whatever the tax calculation method.
**Doing otherwise is very ILLEGAL (in France anyway).**

The shop will very likely get sued for this.

Thanks

**Comment by mikejolley** [comment]
Do you have an official document saying tax calculation per line is wrong? 

HMRC allows either way as long as you keep things consistent. Line-item tax rounding is valid. If it were illegal I would have thought it would have been mentioned before now - it's been like this for several years.

**Comment by Flyingsirkus** [comment]
This is not exactly what I said.

In France, the displayed price is the price the customer has to pay. Taxes and tax calculation is not a customer concern, only the seller has to deal with that.

If the displayed price is 7.70 the customer will pay 14.40 for two products and 77.00 for ten.
There is no going around that.

HMRC does not have jurisdiction over French lows.
What you should look into are article 1103 and 1104 of French civil code:
1. https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006070721&idArticle=LEGIARTI000006436088
2. https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006070721&idArticle=LEGIARTI000006436089

Thanks for your time.

**Comment by mikejolley** [comment]
Do those articles do deeper? They don't seem to mention pricing at all. 

Maybe consider displaying AND defining prices inclusive of tax. That way the price you define will be the charged price. Only the tax amount may change.

**Comment by Flyingsirkus** [comment]
Hi.

Sorry for the late answer.

No, those texts are not about taxes, they are about "good faith" and "contract as a low".

Once again, it is not about the taxes, French customers do not have to know about taxes and taxes calculation, if de displayed price is 7.70 then two products cost 15.40. For the displayed price becomes the low that de seller has to respect in good faith.
And that is it.

When I asked my legal councils a regulation about taxes calculations, they were a bit surprised. To us, it is like saying "I know that murder is illegal, but who says I can't stab you to death?"

When a French shops displays a price that is the price to pay. No calculation, no hidden taxes, no rounding up or down.



As for displaying and defining prices inclusive of tax, I considered that option. However, Bordeaux Select is planning on going international after a few months test period, then need to enter prices excluding taxes and then applying taxes per country.

Thanks

**Comment by mikejolley** [comment]
Inclusive can still work; for international, it can either remove base taxes and apply country taxes, or you can configure it to keep the same price and adjust the tax amount.

Unless you can present something on tax calculation stating per line is not allowed and per item calculation must be used, I don’t think we’ll be changing core.

**Comment by Flyingsirkus** [comment]
For the sake of argument.

In France, if you display this, you get sued. Regardless of any other consideration.
http://bordeauxselect.com/_a_jeter/woocommerce/panier.png
In France, if you get someone to pay that extra cent, you get sued. Regardless of any other consideration.

I do understand it is uncomfortable for you, but the fact remains.

Have a nice day.

**Comment by mikejolley** [comment]
As I said, I need some documentation on this other than your word to take action. Cc @corsonr

**Comment by Flyingsirkus** [comment]
https://www.economie.gouv.fr/dgccrf/Publications/Vie-pratique/Fiches-pratiques/L-information-sur-les-prix
https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006069565&idArticle=LEGIARTI000032227331
https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000032226876&cidTexte=LEGITEXT000006069565

**Comment by mikejolley** [comment]
@Flyingsirkus The prices are still shown/calculated in advance on the cart page before sale/paying. Do you have any resources specific to ecommerce and this example?

**Comment by Flyingsirkus** [comment]
If you think that you could explain, in good faith, and with simple calculation, why 7.70 * 2 = 15.41.
Not to mention de fact that it is stupid that products are more expensive by two than by one.

I think what you're looking for is a legal council, which I'm not.

**Comment by Flyingsirkus** [comment]
IANAL

**Comment by mikejolley** [comment]
Showing prices excluding tax as entered is also a way to stop it appearing wrong to the customer. 

https://dl.dropboxusercontent.com/s/dwqcbchypv701nh/2017-09-25%20at%2012.11.png

FWIW if you did the tax calc on the 6.42, the tax is 7.704, which rounds down to 7.7. 
On 12.84 the tax is 15.408 which rounds up to 15.41 (as we're doing now).

I worry a blanket setting for this to do it per item would result in underpaying tax, which would also be serious.

It's all due to a mix of rounding and taxes per item vs per line. I've suggested 2 workarounds; do with those what you want :) (show and enter prices inc. tax, or show prices ex. tax).

**Comment by Flyingsirkus** [comment]
As for the solution.
We decided to enter prices including taxes.

**Comment by Flyingsirkus** [comment]
As for your calculation and explanation, they are correct and understood.

**Comment by Flyingsirkus** [comment]
As for the French low.

The price MUST be displayed including taxes.
It would be legal to display both (including AND excluding taxes) but would be considered strange in a B to C context.

**Comment by Flyingsirkus** [comment]
Maybe the solution to this situation is a simple warning on an including taxes / excluding taxes setting.

**Comment by Flyingsirkus** [comment]
Thanks for your time.
