### ISSUE TITLE
"Eircode" not changing into "Postcode / ZIP" after switching from "Ireland" to "Netherlands" on checkout

### ISSUE THREAD

**Issue by RobinvanderVliet** [woocommerce/woocommerce#16868]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. Select Ireland during checkout.
![checkout_ _yoast](https://user-images.githubusercontent.com/692029/30648093-7f195194-9e1d-11e7-86de-1919b0985e68.png)
2. Now choose the Netherlands.
3. It still shows a field for "Eircode".
![checkout_ _yoast](https://user-images.githubusercontent.com/692029/30648129-9c328868-9e1d-11e7-95a3-c112c1e60cd5.png)

## Expected/actual behavior
When I follow those steps, I see a field for "Eircode". I was expecting to see a field for "Postcode / ZIP".

## Isolating the problem
- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16870
