### ISSUE TITLE
Cart does not allow me to change delivery method

### ISSUE THREAD

**Issue by pao13** [woocommerce/woocommerce#16864]
Hi,
I faced a problem when trying to change delivery method on cart. I am not allowed to change the checked radio button to my second delivery method. The first delivery method is checked (no matter which one i put first) and cannot change. However when i move to cashier i CAN change it. This will confuse my customers thinking they can only recieve my products on store or paid home delivery only depending on the one i rank first. please help

**Comment by mikejolley** [comment]
This is a template issue - I've seen it before. The theme may have an outdated or customised template file which is handling shipping display. Update/change themes.
