### ISSUE TITLE
[3.2 Beta] Breaking changes to taxes and fees WC_Cart properties

### ISSUE THREAD

**Issue by ChaseWiseman** [woocommerce/woocommerce#16861]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

As of 3.2-beta-2, certain `WC_Cart` properties can no longer be modified as they could in 3.1.x and lower. So far I've found issues with these in my testing:

- `WC_Cart::$taxes`
- `WC_Cart::$fees`
- `WC_Cart::$shipping_taxes`

Getting and setting these properties directly works as expected, but their array values cannot be modified, i.e. `$cart->taxes['custom-rate'] = 100;`. This will throw a `Indirect modification of overloaded property WC_Cart::$taxes has no effect` notice and the modification will be lost. This is due to those properties now being overloaded.

## Steps to reproduce the issue

1. Hook into `woocommerce_after_calculate_totals`
2. Add an extra tax rate using `$cart->taxes['custom-rate'] = 100;`
3. See that nothing sticks, and the notice is logged

It's a fairly easy fix in custom code by just assigning `$cart->taxes` to a variable and setting it back after modification, but this is still a breaking change unfortunately.

**Comment by thomas-zg** [comment]
In Switzerland, the smalest coin is 5 cent, that's the reason why I have to add a custom rounding to the next 5 cent. Up to 3.1.x, I did it with the woocommerce_calculate_totals action.
From 3.2, the calculation of the totals was moved to [https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart-totals.php](url) and this will break my current logic too.

**Comment by mikejolley** [comment]
Looking into this but going to point out now, that if you change taxes like this manually, the changes will never stick as soon as order/cart triggers recalc. Saving an order for example may recalc and these changes are then wiped. So doing this is not advised.

**Comment by mikejolley** [comment]
@thomas-zg You can add fees without needing to work out totals manually...

**Comment by thomas-zg** [comment]
@mikejolley this is what I did before 3.2 with the woocommerce_calculate_totals action.
	function round_totals_5cent( $cart_instance ){
		if ( is_admin() && ! defined( 'DOING_AJAX' ) )
		return;

	
		$surcharge = $this->get_round_difference( 
			$cart_instance->cart_contents_total + $cart_instance->shipping_total + 
			$cart_instance->tax_total + $cart_instance->shipping_tax_total + $cart_instance->fee_total );
		$cart_instance->add_fee( __('Rundungsdifferenz'), $surcharge, false, '' );
		$cart_instance->fee_total += $surcharge;
	}

For COD orders, I need to have a total rounded to the next 5 cent. This code does not work anymore in 3.2.

**Comment by mikejolley** [comment]
@thomas-zg This is unrelated. You should be using the correct action ( woocommerce_cart_calculate_fees ) and letting the cart work out the fee total. Doing it manually seems wrong.

**Comment by mikejolley** [comment]
@ChaseWiseman Please take a look at https://github.com/woocommerce/woocommerce/pull/16869/files

Seems references are the only way to support arrays via getters/setters. These props should be removed completely in 4.0.

**Comment by thomas-zg** [comment]
@mikejolley The action is raised to early for my case, the already existings fees will be calculated after the action, but I need the total of the fees too. After all calculation(items, shipping, fees, tax) I need to round the total to the next 5 cent. The rounding difference must be shown on the order/invoice.

This is what I need to have:
![grafik](https://user-images.githubusercontent.com/25877146/30652506-d7293dc6-9e28-11e7-8b06-e3d6f793fb99.png)

**Comment by ChaseWiseman** [comment]
@mikejolley I just tested that branch against the custom code and it did the trick, thanks! 🍻 Only saw an issue with the deprecated notice https://github.com/woocommerce/woocommerce/pull/16869/files#r140283087
