### ISSUE TITLE
Autofill on registration form returns "Anti-spam field was filled in"

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#16862]
Ticket: 673995-zd-woothemes

When using auto fill (on desktop or phone) to fill in the email field in My Account > Register form, the error "Anti-spam field was filled in" appears after registering. Clicking register button again let's users register successfully.

![](http://cld.wthms.co/OYfIvY+)
Link to screenshot: http://cld.wthms.co/OYfIvY

**Comment by mikejolley** [comment]
This is the field HTML:

```
<div style="<?php echo ( ( is_rtl() ) ? 'right' : 'left' ); ?>: -999em; position: absolute;"><label for="trap"><?php _e( 'Anti-spam', 'woocommerce' ); ?></label><input type="text" name="email_2" id="trap" tabindex="-1" autocomplete="off" /></div>
```

This uses `autocomplete="off"` to deter filling. Background https://stackoverflow.com/questions/9501120/how-can-i-prevent-ie-form-auto-fill-from-filling-in-a-honeypot-field

But we could probably leave the spam protection to extensions (general WP registration/spam protection plugins should work here). I'll remove the code. It wouldn't be hard for a bot to circumvent this field anyway.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16865
