### ISSUE TITLE
Redirect from checkout if cart is empty

### ISSUE THREAD

**Issue by glvr** [woocommerce/woocommerce#16883]
I understand this can be useful (in possibly saving a click), but isn't it more logical to remove the redirect and have the 'Checkout is not available whilst your cart is empty.' message display on the checkout page?

**Comment by mikejolley** [comment]
The cart page shows a notice like this already, after the redirect.

<img width="1178" alt="2017-09-25 at 12 41" src="https://user-images.githubusercontent.com/90977/30806749-e78fbf7c-a1ee-11e7-9292-3bb8122315f4.png">
