### ISSUE TITLE
CDN Issue while serving Image Assets over HTTP

### ISSUE THREAD

**Issue by pareshchouhan** [woocommerce/woocommerce#16897]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set URL to Blog in Settings > General -> (http://somesite.com)
2. Download and Enable KeyCDN > set CDN to http url  (http://cdn.somesite.com)

## Expected/actual behavior

When I follow those steps, I see...
Check Image URLs on front page -> they are //somesite.com

I was expecting to see...
Check Image URLs on front page -> should be //cdn.somesite.com

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
</details>

**Comment by claudiulodro** [comment]
That's going to be something in how the CDN plugin works and not WooCommerce. You can see [here](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L1736-L1747) is the function that gets a product image, and [here](https://github.com/woocommerce/woocommerce/blob/fcb7da5599f85df37e423e8195810f1e81bbae83/includes/wc-core-functions.php#L1868-L1870) is the function that strips "http:" off the URL. We're just using regular `get_the_post_thumbnail` to fetch images.
