### ISSUE TITLE
External images for WooCommerce Products?

### ISSUE THREAD

**Issue by phantanvietpk** [woocommerce/woocommerce#16892]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. The imported products using external images 
2. Images have download to Media
3.

## Expected/actual behavior

I want using External images for WooCommerce Products. Because i have ~10000 product my hosting will be unbearable.

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
External images are not supported. You cannot use external images from the admin screens either (for any post type). Use a CDN plugin if concerned about bandwidth and speed.

**Comment by phantanvietpk** [comment]
They can do that: [https://fazostore.com/ ](https://fazostore.com/ )
You can tutorial, I can edit the code.
