### ISSUE TITLE
Setup Wizard does not use store location set to change default weight unit and dimension unit settings

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce#16898]
On the current setup wizard, if you set the store location as say one that is in the United States, the default options set on the shipping stage, does not change for the weight and dimension units which is set as metric, whilst the US would be set to use imperial.

So if the store location is set within the United States then set shipping stage defaults as

Weight Unit: lbs
Dimension Unit: in

![wc setup wizard shipping default](https://user-images.githubusercontent.com/5797332/30756661-da202362-9f88-11e7-8d0b-63357e7f29e0.png)

**Comment by mikejolley** [comment]
@jeffstieler covered in new update?

**Comment by jeffstieler** [comment]
> @jeffstieler covered in new update?

@mikejolley the behavior in the new update defaults the units to `in`/`oz` if the country is `US` but only if the units hadn't been previously set.

**Comment by mikejolley** [comment]
Thats what I though 👍 And that makes sense.

As I mentioned in the other PR, we should stop users running the wizard twice. That means removing the 'help tab' re-run button if the wizard was completed. I'll do that once your PR is merged.

**Comment by allendav** [comment]
How was this fixed exactly?

**Comment by jeffstieler** [comment]
@allendav https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-setup-wizard.php#L758-L766
