### ISSUE TITLE
Post Was Called Incorrectly

### ISSUE THREAD

**Issue by FrankieBrown** [woocommerce/woocommerce#16896]
Hello,

I am receiving this error code on my Single Product pages. Notice: post was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce/templates/single-product.php'), wc_get_template_part, load_template, require('/plugins/woocommerce/templates/content-single-product.php'), do_action('woocommerce_before_single_product'), WP_Hook->do_action, WP_Hook->apply_filters, WCV_Vendor_Shop::vendor_mini_header, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in /homepages/27/d433139901/htdocs/clickandbuilds/TheDriveGurus/wp-includes/functions.php on line 4139

I have read about deprecated code but I cannot see where I need to go to update (and even if that is the best course of action). Any help would be much appreciated.

I have deactivated all "conflicting" plugins that are not crucial so recreating this error message. I have tried a different theme and I still get the error.

**Comment by claudiulodro** [comment]
> `WCV_Vendor_Shop::vendor_mini_header`

Looks like the `vendor_mini_header` method from the `WCV_Vendor_Shop` class is the one with the problem. That's going to be a third-party plugin you are using. You should get an updated version of the plugin if one has been released or hassle the plugin author if an update hasn't been released.
