### ISSUE TITLE
CSV upload variations issue: when 'stock' goes to 0 does not kick 'in stock?' status into 'out to stock'

### ISSUE THREAD

**Issue by xingxu21** [woocommerce/woocommerce#16906]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Uploaded CSV for 1 product with 2 variations for sizes S (small) and M (medium) with "In stock?" column empty and "stock" as 1 (https://drive.google.com/open?id=0BxIDVPYrPF7HOWk1MFduRWM1N28)

2. Logged out of admin account, went to website as new customer

3. Product shows on shop page with S and M options to add to cart, added S to cart and checked out

4. Checked shop page and both S and M are available showing "in stock" for both. When added S to cart, error message: 

"You cannot add that amount of "Colorblock Striped Pencil Dress - S" to the cart because there is not enough stock (0 remaining)."

This is good that it stops the customer from ordering something I don't have, but it's not good that it shows as even an option for the user to try to add to cart when it is no longer in stock.

5. Logged back into admin account, went to products > DXBLU0001 > variations > expand
(https://drive.google.com/open?id=0BxIDVPYrPF7HM1luUEVJZDJkWVU)

6. I see that the quantity for variation S = 0, BUT the "stock status" still says "in stock". This should have automatically moved to "out of stock" since quantity = 0. Funny thing is I receive an email notification as admin that I'm "out of stock" in this item. 

## Expected/actual behavior

When I follow those steps, I see...

7. WITHIN same woocommerce product screen from step 6 (no more CSV uploads): Tested what would happen if I MANUALLY changed the quantity of M that is at 1 to 0 and save changes >> automatically changed "stock status" to "out of stock". Good.

8. WITHIN same woocommerce product screen from step 7: Tested what would happen if I MANUALLY changed quantity of M back to 1 and saved changes >> automatically changed "stock status" to "in stock". Good.

I was expecting to see...

9. When an item goes down to quantity = 0 through an order, the "stock status" should automatically change to "out of stock" (and if the CSV is exported, the column "in stock?" should = 0. However, when exported, it shows as = 1). I should not have to manually go into the woocommerce product screen one product at a time to manually update quantities. 

10. Side note, when I place an order logged out of admin and as a new customer for the M that was manually changed in steps 7 & 8, stock quantity goes to 0 AND stock status CHANGES to out of stock! So thinking the issue is happening when the CSV file is data originator (though I would not want to manually update all my stock all the time... defeats the purpose of having CSV importing!)

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

`
### WordPress Environment ###

Home URL: http://www.new.bellanove.com
Site URL: http://www.new.bellanove.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (25) ###

CB Change Mail Sender: by Md Abul Bashar – 1.1
Contact Form 7: by Takayuki Miyoshi – 4.9
createIT Advanced Filters: by createIT – 1.3
Easy Google Fonts: by Titanium Themes – 1.4.3
Facebook for WooCommerce: by Facebook – 1.4.5
Helios Solutions WooCommerce Hide Price and Add to Cart button: by heliossolutions – 2.0.2
Jilt for WooCommerce: by Jilt – 1.2.0
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Membership 2 Pro: by WPMU DEV – 1.1.1
VarkTech Min and Max Purchase for WooCommerce: by Vark – 1.08.1
VarkTech Min and Max Purchase Pro for WooCommerce: by VarkTech – 1.07.8
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution: by ThemePunch – 5.4.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.7

WooCommerce Stripe Gateway: by WooCommerce – 3.2.3
WooCommerce Image Zoom: by wpbean – 1.02.4
WooCommerce MailChimp: by Saint Systems – 2.1.2
Woocart Popup Lite for WooCommerce: by Festi-Team – 1.1
WooCommerce: by Automattic – 3.1.2
Wordpress Page Widgets: by CodeAndMore – 3.5
WPMU DEV Dashboard: by WPMU DEV – 4.3.2
Easy Forms for MailChimp: by YIKES
Inc. – 6.3.25

YITH WooCommerce Authorize.net Payment Gateway: by Yithemes – 1.1.0
YITH WooCommerce Quick View: by YITHEMES – 1.2.1
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #8621 - /shop/
Cart: #2557 - /cart/
Checkout: #742 - /checkout-2/
My account: #2143 - /my-account/

### Theme ###

Name: Sienna
Version: 2.0
Author URL: http://www.elusivethemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Jilt ###

Plugin Version: 1.2.0
API Version: v1
API Connected: ✕ Please ensure the plugin is properly configured with your Jilt secret key.
Linked to Jilt: ✕ Please ensure the plugin is properly configured with your Jilt secret key.
Enabled: ✕
`

```
</details>

**Comment by mikejolley** [comment]
> When an item goes down to quantity = 0 through an order, the "stock status" should automatically change to "out of stock" (and if the CSV is exported, the column "in stock?" should = 0

This case is working in my tests. I'm using 3.2 which has had some CSV fixes so I'm thinking this has been rectified already. 

One error however I will point out in your CSV, for the variable product you have set `stock` to `0`. Please note that when you set a value, stock management will be turned on at product level too. This cell should be left blank in your case. You only want stock management per variation.

Thanks!

**Comment by fistukidz** [comment]
Hi, 
i see this post is set to closed. but i have the same issue. 
all my 300 products were imported from cart 2 cart site (wix to woocommerce) and i have the same issue that after an item is bought it changes to 0 but stay in stock. 
i have the latest version of wordpress and woocommerce. 

can you help me to solve this issue. 
thanks.
