### ISSUE TITLE
REST API Product Requests w/ Category Parameter, pulls wrong info.

### ISSUE THREAD

**Issue by icircletech** [woocommerce/woocommerce#16900]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. I create a basic Request using the PHP library for V2 of the WooCommerce REST Api 
2. I request to pull a list of Products with "Catergory" as the only parameter ( I request one Category ID '226') 
3.The data returned, sends me a totally different Category ID (example shows '241')
4.Sometimes it works with some Category ID's, sometimes it doesn't with others.
5. Everything Else seems to work fine (Everything is authenticated)

## Expected/actual behavior

When I follow those steps, I see...

***************************************************************

Array ( [product-id] => 44586 [product-name] => Ear Speaker Repair - iPhone 8 (Copy) [product-slug] => [category-id-241] => Array ( [category-id] => 241 [category-name] => iPhone 7 Repairs [category-slug] => apple-iphone-7-repairs ) ) 

Array ( [product-id] => 44585 [product-name] => Volume Control Button Repair - iPhone X [product-slug] => volume-control-button-repair-iphone-x [category-id-241] => Array ( [category-id] => 241 [category-name] => iPhone 7 Repairs [category-slug] => apple-iphone-7-repairs ) ) 

Array ( [product-id] => 44584 [product-name] => Wi-Fi Antenna Repair - iPhone X [product-slug] => wi-fi-antenna-repair-iphone-x [category-id-241] => Array ( [category-id] => 241 [category-name] => iPhone 7 Repairs [category-slug] => apple-iphone-7-repairs ) ) 

Array ( [product-id] => 44583 [product-name] => Rear Camera Lens Repairs - iPhone X [product-slug] => rear-camera-lens-repairs-iphone-x [category-id-241] => Array ( [category-id] => 241 [category-name] => iPhone 7 Repairs [category-slug] => apple-iphone-7-repairs ) ) 

Array ( [product-id] => 44582 [product-name] => Rear Camera Repair - iPhone X [product-slug] => rear-camera-repair-iphone-x [category-id-241] => Array ( [category-id] => 241
241 [category-name] => iPhone 7 Repairs [category-slug] => apple-iphone-7-repairs ) ) 

Array ( [product-id] => 44581 [product-name] => Internal Loud Speaker Repair - iPhone X [product-slug] => internal-loud-speaker-repair-iphone-x [category-id-241] => Array ( [category-id] => 241 [category-name] => iPhone 7 Repairs [category-slug] => apple-iphone-7-repairs ) ) 

Array ( [product-id] => 44580 [product-name] => Power / Sleep Button Repair - iPhone X [product-slug] => power-sleep-button-repair-iphone-x [category-id-241] => Array ( [category-id] => 241 [category-name] => iPhone 7 Repairs [category-slug] => apple-iphone-7-repairs ) ) 

Array ( [product-id] => 44579 [product-name] => Screen Repair (Black) - iPhone X [product-slug] => screen-repair-black-iphone-x [category-id-241] => Array ( [category-id] => 241 [category-name] => iPhone 7 Repairs [category-slug] => apple-iphone-7-repairs ) ) 

Array ( [product-id] => 44577 [product-name] => Chargeport Repair (White) - iPhone X [product-slug] => chargeport-repair-white-iphone-x [category-id-241] => Array ( [category-id] => 241 [category-name] => iPhone 7 Repairs [category-slug] => apple-iphone-7-repairs ) ) 

Array ( [product-id] => 44576 [product-name] => Front Camera / Proximity / Mic Repair - iPhone X [product-slug] => front-camera-proximity-mic-repair-iphone-x [category-id-241] => Array ( [category-id] => 241 [category-name] => iPhone 7 Repairs [category-slug] => apple-iphone-7-repairs ) ) 
**********************************************************************************

I was expecting to see...
 
A Different Data Set with the actual category ID's I requested

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://icircletech.com
Site URL: https://icircletech.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 256 MB
PHP Time Limit: 4000
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔  3 active Zapier Feeds.
Zapier Integration - Cron Tasks: ✔  0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔  New Order Zap - Twilio
Zapier Feed #1 Webhook URL: ✔  https://hooks.zapier.com/hooks/catch/1917752/5otcro/
Zapier Feed #1 Trigger: ✔  New Order
Zapier Feed #1 Test Result: ✔  Successfully sent sample data to https://hooks.zapier.com/hooks/catch/1917752/5otcro/.
Zapier Feed #2 Name: ✔  WooCommerce to Quickbooks - Order Status Change
Zapier Feed #2 Webhook URL: ✔  https://hooks.zapier.com/hooks/catch/1917752/h3omfh/
Zapier Feed #2 Trigger: ✔  New Order Status Change
Zapier Feed #2 Test Result: ✔  Successfully sent sample data to https://hooks.zapier.com/hooks/catch/1917752/h3omfh/.
Zapier Feed #3 Name: ✔  New Order - Add Customer
Zapier Feed #3 Webhook URL: ✔  https://hooks.zapier.com/hooks/catch/1917752/rhwkoo/
Zapier Feed #3 Trigger: ✔  New Order
Zapier Feed #3 Test Result: ✔  Successfully sent sample data to https://hooks.zapier.com/hooks/catch/1917752/rhwkoo/.

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_nz8hrvqk4c_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

JSON Basic Authentication: by WordPress API Team – 0.1
The7 Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.16
Akismet Anti-Spam: by Automattic – 3.3.4
WooCommerce Character Case Correction: by Actuality Extensions – 1.1
Contact Form 7: by Takayuki Miyoshi – 4.9
The7 ConvertPlus: by Brainstorm Force – 3.0.0
The7 Elements: by Dream-Theme – 1.3.0
Facebook for WooCommerce: by Facebook – 1.4.5
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.1.1.1
Google XML Sitemaps: by Arne Brachhold – 4.0.9
The7 Visual Composer: by Michael M - WPBakery.com – 5.2.1
MailChimp for WooCommerce: by MailChimp – 2.0.1
Mailgun: by Mailgun – 1.5.8.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Slider Revolution Before/After Add-On: by ThemePunch – 1.0.1
The7 Slider Revolution: by ThemePunch – 5.4.5.2
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.1.1
Instagram Feed WD: by WebDorado – 1.2.5
Woocommerce Advanced Bulk Edit: by George Iron – 4.1.1
WooCommerce Customer Relationship Manager: by Actuality Extensions – 3.3.5
WooCommerce Deposits: by Automattic – 1.3.1
WooCommerce Force Sells: by WooCommerce – 1.1.13
WooCommerce Elavon Converge Gateway: by SkyVerge – 2.2.0 – 2.2.1 is available
OneSaas Connect: by OneSaas – 2.0.6.43
WooCommerce Order Rules & Filters: by Actuality Extensions – 1.5.1
WooCommerce Payment Status: by Actuality Extensions – 1.5.0
WooCommerce Point of Sale: by Actuality Extensions – 4.1.8.14
WooCommerce Pre-Orders: by WooCommerce – 1.5.3
WooCommerce Product Bundles: by SomewhereWarm – 5.4.3
WooCommerce Order Status & Actions Manager: by Actuality Extensions – 2.2.4
WP All Import - WooCommerce Add-On: by Soflyy – 1.3.6
WooCommerce Zapier Integration: by OM4 – 1.6.9
WooCommerce: by Automattic – 3.1.2
WP All Import: by Soflyy – 3.4.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
rated-5 (rated-5-2)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/

### Theme ###

Name: the7dtchild
Version: 1.0.0
Author URL: http://dream-theme.com/
Child Theme: ✔
Parent Theme Name: The7
Parent Theme Version: 5.5.0.1
Parent Theme Author URL: http://dream-theme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: dt-the7/woocommerce/cart/cart.php
dt-the7/woocommerce/cart/cross-sells.php
dt-the7/woocommerce/checkout/form-billing.php
dt-the7/woocommerce/checkout/form-checkout.php
dt-the7/woocommerce/checkout/form-coupon.php
dt-the7/woocommerce/checkout/form-login.php
dt-the7/woocommerce/checkout/form-shipping.php
dt-the7/woocommerce/checkout/review-order.php
dt-the7/woocommerce/checkout/thankyou.php
dt-the7/woocommerce/content-product.php
dt-the7/woocommerce/content-product_cat.php
dt-the7/woocommerce/global/breadcrumb.php
dt-the7/woocommerce/global/form-login.php
dt-the7/woocommerce/global/quantity-input.php
dt-the7/woocommerce/loop/loop-end.php
dt-the7/woocommerce/loop/loop-start.php
dt-the7/woocommerce/loop/orderby.php
dt-the7/woocommerce/loop/pagination.php
dt-the7/woocommerce/myaccount/form-login.php
dt-the7/woocommerce/notices/error.php
dt-the7/woocommerce/notices/notice.php
dt-the7/woocommerce/notices/success.php
dt-the7/woocommerce/order/order-details-customer.php
dt-the7/woocommerce/order/order-details.php
dt-the7/woocommerce/single-product/meta.php
dt-the7/woocommerce/single-product/price.php
dt-the7/woocommerce/single-product/related.php
dt-the7/woocommerce/single-product/up-sells.php

### Elavon Converge Credit Card ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off
`
</details>

**Comment by mikejolley** [comment]
You didn't share the request itself. Did you spell it like above? `Catergory` is wrong.

The docs state https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products that `category` can be used to specify a single category ID to find products within. 

This filter appears to be working:

<img width="1144" alt="2017-09-25 at 13 18" src="https://user-images.githubusercontent.com/90977/30807983-2364b6b0-a1f4-11e7-9c57-9bec97dc094a.png">
