### ISSUE TITLE
Woocommerce Product CSV Important improperly handles non-upload-dir URLs

### ISSUE THREAD

**Issue by urikanonov** [woocommerce/woocommerce#16905]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. The bug was introduced in the following commit in line 507:
https://github.com/woocommerce/woocommerce/commit/90f0a835b10bdd0ba701ae95a76e92ee55a0b09b#diff-ca3815d9d9e2ceab34d752a05a99f7f1
2. The "!==" in "false !== strpos( $url, $base_url )" became "===" and now upload dir URLs are redirected to the "else" clause and vice versa.
3. To reproduce just import a product with a non-uploads dir URL.

See screenshot of buggy code:
![wcimporturlcachingbug](https://user-images.githubusercontent.com/22576177/30773192-4a07cbe4-a074-11e7-99e7-5b1dbf6abd5a.PNG)

## Expected/actual behavior

When I follow those steps, I see that non-uploads URLs are not cached with previous imports whereas I expect them to be...

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

### WordPress Environment ###

Home URL: https://www.valltasy.com
Site URL: https://www.valltasy.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.23
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wpxx_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (35) ###

Contact Form 7 - Dynamic Text Extension: by Chris Mavricos
SevenSpark – 2.0.2.1

Contact Form 7: by Takayuki Miyoshi – 4.9
Custom Permalinks: by Sami Ahmed Siddiqui – 1.1
Debug Bar Actions and Filters Addon: by Subharanjan – 1.5.4
Debug Bar: by wordpressdotorg – 0.9
Flamingo: by Takayuki Miyoshi – 1.7
Image Regenerate & Select Crop: by Iulia Cazan – 4.1
Kint Debugger: by Brian Fegter
Chris Dillon – 1.2

Load More Products for WooCommerce: by BeRocket – 1.0.8
MailChimp for WooCommerce: by MailChimp – 2.0.1
MailChimp for WordPress: by ibericode – 4.1.9
Media Cleaner: by Jordy Meow – 4.1.0
Admin Bookmarks: by Brad Vincent – 1.0.0
Nextend Facebook Connect: by Nextendweb – 2.0.2
Nextend Google Connect: by Roland Soos
Jamie Bainbridge – 1.6.1

Optimize Images Resizing: by OriginalEXE – 1.4.1
Really Simple SSL: by Rogier Lankhorst – 2.5.20
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
WP REST API - Meta Endpoints: by WP REST API Team – 0.1.0
WP REST API - OAuth 1.0a Server: by WP REST API Team – 0.3.0
SG Optimizer: by SiteGround – 3.3.3
Simple Image Sizes: by Rahe – 3.1.1
Use Any Font: by Dinesh Karki – 4.7.3
Woocommerce CSV import variable products: by Allaerd Mensonides – 3.1.5
Woocommerce CSV Import: by Allaerd Mensonides – 3.3.6
WooCommerce - Store Exporter: by Visser Labs – 1.9.3
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.3
WooCommerce: by Automattic – 3.1.2
WOOCSV - Import comments: by Allaerd Mensonides – 1.0.1
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 5.4.2
WP REST API Controller: by YIKES
Inc.
Evan Herman
yikesitskevin – 1.4.1

YITH WooCommerce Gift Cards Premium: by YITHEMES – 1.6.15
YITH WooCommerce Tab Manager: by YITHEMES – 1.1.8
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7379 - /shop/
Cart: #7380 - /cart/
Checkout: #7381 - /checkout/
My account: #7382 - /my-account

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.3.8
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome-child/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome-child/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome-child/woocommerce/loop/rating.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome-child/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome-child/woocommerce/single-product/tabs/tabs.php
flatsome-child/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome-child/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`

</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/16916
