### ISSUE TITLE
3.1.2 merging random orders

### ISSUE THREAD

**Issue by xpafiolis** [woocommerce/woocommerce#16908]
Upgraded woocommerce to 3.1.2 on production as everything seemed fine on test site. 

48 hours later we find out over a dozen orders have randomly been merged. Out of hundreds. 

For whatever reason 2 random orders are being merged at a time. Each person gets same order number confirmation. Admin has email record of both different orders with same order number. Woocommerce only has 1 order, and merges the contact info billing/ address/ email. Products on the order are usually from one and ignore the other. 

What’s crazy and allowed us to catch this is when the order synced to stitch labs it shows all products from both orders!??!?

Not sure how do debug but in the meantime we rolled back to 3.1.1 and problem seems to be solved. 

Any thoughts?

**Comment by mikejolley** [comment]
Viewing the diff there are no related changes I can see https://github.com/woocommerce/woocommerce/compare/3.1.1...3.1.2 

Without a status report I cannot see what you're running either, but if I had to guess I'd say this is related to cache on your server and 3.1.1 is probably just as affected, you've just never noticed.

Orders merge is the same user pays for the same order, and the previous order is unpaid or failed. You can see the logic for this here: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L287

So if the merged orders are from the same user, same contents, **check the payment gateway is working correctly.**

If the merged orders are from different users, look into **caching** on your server https://docs.woocommerce.com/document/configuring-caching-plugins/

Good luck.

**Comment by xpafiolis** [comment]
Thanks Mike, will look into the caching again.
