### ISSUE TITLE
UI: Webfont enhancements; drop IE8 support and implement gridicons

### ISSUE THREAD

**Issue by pipdig** [woocommerce/woocommerce#16903]
It looks like WC is still supporting IE8 with the [webfont file types](https://github.com/woocommerce/woocommerce/blob/master/assets/css/_fonts.scss) included. Is it time to move to [this approach](https://css-tricks.com/snippets/css/using-font-face/#article-header-id-2)? Or is IE8 still officially supported?

As an example, star.woff is 1.3kb, whereas [star.woff2](https://github.com/woocommerce/woocommerce/files/1326442/star.zip) is reduced to 0.6kb. It would be good to at least include a woff2 in the fonts files.

**Comment by claudiulodro** [comment]
We should not continue supporting IE8 since WP doesn't any more. https://wptavern.com/wordpress-4-8-will-end-support-for-internet-explorer-versions-8-9-and-10

**Comment by jameskoster** [comment]
I think this should be part of a larger UI tidy up. There are quite a few examples superfluous icon use that we can definitely improve.

We should also consider adopting [gridicons](https://github.com/Automattic/gridicons). Gridicons can be viewed [here](http://automattic.github.io/gridicons/).

Here's a list of our current icons and possible Gridicon alternatives. But like I said, some of these can probably be removed anyway.

**General icons**
* Tooltip -> `gridicons-info-outline`
* Leave a rating -> `gridicons-star`

**Nav icons**
* WooCommerce menu -> Rename to "Orders" -> Will need a new icon
* Products menu -> `gridicons-product`

**Orders**
* Order preview button -> `gridicons-visible`
* Address edit icon -> `gridicons-pencil`
* Confirm action icon -> Suggest replace this with "Confirm" text.
* Shipping icon -> `gridicons-shipping`

**Coupons**
* General settings icon -> `gridicons-coupon`
* Usage restriction settings icon -> `gridicons-block`
* Usage limit settings icon -> Would need a new icon

**Reports**
* Export icon -> `gridicons-cloud-download`

**Settings**
* Zones globe -> `gridicons-globe`
* Payment method enabled -> `gridicons-checkmark-circle`
* "Manually sent" email icon -> We probably don't need this
* Email settings button -> Could just `gridicons-cog` but may be better to just use text for this.

**Products**
* Image icon -> We could just remove this
* Featured off -> `gridicons-star-outline`
* Featured on -> `gridicons-star`
* Product types -> We have icons for each except Variable and Grouped which proved tricky. We could consider removing this column or using text.
* General settings icon -> `gridicons-product`
* Inventory icon -> `gridicons-clipboard`
* Shipping icon -> `gridicons-shipping`
* Linked products icon -> `gridicons-link`
* Attributes icon -> `gridicons-types`
* Advanced icon -> `gridicons-cog`

**Categories**
* Re-order handle -> `gridicons-menu`

I think that's all of 'em!

**Comment by GlennMartin1** [comment]
As a related WOFF/WOFF2 issue, Woo Canvas theme creates the following issue on WP Engine's page performance report.

![woff2](https://user-images.githubusercontent.com/30901407/30816111-0168ecea-a1e3-11e7-98e1-098ac2a8dafd.jpg)

**Comment by claudiosanches** [comment]
@GlennMartin1 This is the _core_ issue tracker. Please use the helpdesk to report issues with Canvas https://woocommerce.com/my-account/tickets/

**Comment by GlennMartin1** [comment]
@claudiosanches Got it - still very new to all this - thanks much.

**Comment by Visovsiouk** [comment]
I'd like to try my hand at this. Where and how do I get started?

**Comment by jameskoster** [comment]
@Visovsiouk which approach are you planning to use?

You get started by cloning and forking this repo :)

**Comment by Visovsiouk** [comment]
@jameskoster I forked and cloned the repo, Slightly Deeper Browser Support seems like a more reasonable way to approach this.

**Comment by Visovsiouk** [comment]
@jameskoster Is there a WooCommerce.woff2 file to be included? Also, what is the scope of the enhancement? Should I stick to changing _fonts.scss, or every file including .woff files (e.g. admin-rtl.css)?

**Comment by jameskoster** [comment]
> Is there a WooCommerce.woff2 file to be included?

Nope, not as yet. But we created the font using [IcoMoon](https://icomoon.io/) which I believe has an import feature, so you might be able to do so yourself.

> Also, what is the scope of the enhancement?

We haven't explored it in any great detail yet. As I said above I think we should explore moving away from fonts and towards a more actively developed icon set - like [Gridicons](https://github.com/Automattic/gridicons). But that's not final.

> Should I stick to changing _fonts.scss, or every file including .woff files (e.g. admin-rtl.css)?

Editing .scss files should be sufficient. The .css files will be generated by our build task.

**Comment by Visovsiouk** [comment]
Unfortunately, only premium accounts can export .woff2 files through IcoMoon. The WooCommerce.woff2 should be added when available.

**Comment by jameskoster** [comment]
That's a shame. We might just end up skipping directly to using Gridicons in that case. This certainly isn't a high priority item right now. I'm excited that you want to help though :)

**Comment by mikejolley** [comment]
Punting this one to 3.4 as it's not critical.

**Comment by willgorham** [comment]
I'm interested in giving this a shot. I'll open a PR to get some initial feedback.

**Comment by mikejolley** [comment]
This is being tracked in https://github.com/woocommerce/woocommerce/pull/18298

👍
