### ISSUE TITLE
Shipping method and instance id

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce#16912]
Discovered with @gedex while reviewing https://github.com/woocommerce/woocommerce-follow-up-emails/pull/389.

`WC_Shipping::instance()->get_shipping_methods()` has e.g. id `free_shipping`
but
`WC_Order::get_shipping_methods()` has e.g. id `free_shipping:2`

So the order includes the instance id, which is good. But in my opinion this shouldn't be stored as a "serialized" string. Ideally, the instance id should be stored in a separate field with its own getter/setter.

Core already uses the `explode` approach. See [this](https://github.com/woocommerce/woocommerce/blob/e38d01b/includes/class-wc-order.php#L1286).

See [this](https://github.com/woocommerce/woocommerce/blob/185934f/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php#L200) how it can cause issues. Someone can set the id using weird strings to confuse the `explode` of the colon.

**Comment by mikejolley** [comment]
Any idea how to do this non-breaking? 

Other issues; the shipping line item select box for method needs to handle these.

**Comment by bor0** [comment]
> Any idea how to do this non-breaking?

Not really. This should probably be done in a major version, by introducing new methods and deprecating the old ones. We could re-consider it as it's not really that big of a deal.

The effort to refactor is higher than the severity of the issue itself, but it'd be good to have the logic done in a cleaner way.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18483
