### ISSUE TITLE
Problems clearing a value in PayPal Express Checkout

### ISSUE THREAD

**Issue by moorscode** [woocommerce/woocommerce#16915]
The API `get_option` method does not allow for empty string value.
See  https://github.com/woocommerce/woocommerce/blob/46d3638089b58b51a2321b67443b83f409c6b4ec/includes/abstracts/abstract-wc-settings-api.php#L260-L262

This is causing problems with overriding a default setting with an empty string in the WooCommerce PayPal Express Checkout plugin.

Please note that `$empty_value` is not an `empty value` but the default to use.

Place where this code is being called: 
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/792fbdab3c8e013ac153361feefd099bac2ae792/includes/abstracts/abstract-wc-gateway-ppec.php#L53

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. In WooCommerce PayPal Express Checkout try to clear the `Invoice Prefix` field:
`/wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppec_paypal`

## Expected/actual behavior

When I follow those steps, I see the default value of `WC-` return after saving when clearing the field.

I was expecting to see the option being empty after saving.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

(Removed section as I don't deem it relevant for this issue)

**Comment by mikejolley** [comment]
It looks like `$empty_value` is meant to kick in whenever the option is empty (``), in which case removing the content of invoice prefix will set it to default. Maybe invoice prefix is required?

> Please note that $empty_value is not an empty value but the default to use.

Assumption?

Right or wrong, intended or otherwise, changing the behaviour now would be a breaking change and may be relied upon by developers. This settings API has been around a very long time.

**Comment by moorscode** [comment]
Fair enough, I'll make an issue on the specific repository that I expected different behaviour.
