### ISSUE TITLE
Customer invoice is not sending

### ISSUE THREAD

**Issue by hawafi** [woocommerce/woocommerce#16919]
Hi,

The Customer invoice is not sending and it is set to manually when I opened the page I noticed that the "Enable this email notification" checkbox is missing.

All other emails are sending, I'm using the latest version of WordPress and Wocommerce.

Regards.

**Comment by mikejolley** [comment]
Customer invoice is manually sent from the orders screen. It's not automatic so no checkbox is needed.

https://docs.woocommerce.com/document/email-faq/

**Comment by hawafi** [comment]
Hi,
Thanks for your reply.

Before it was automatic! How to send it manually, please?

Thanks.

**Comment by hawafi** [comment]
is it possible to make it automatic as it was before?

**Comment by mikejolley** [comment]
Read the email FAQ.

**Comment by hawafi** [comment]
Hi,

Even Manually is not sending. The "Your order is complete" email didn't send also.

Thanks.

**Comment by mikejolley** [comment]
Right, so read the FAQ for debugging steps. Github is not a support forum.

**Comment by hawafi** [comment]
Ok. Thanks.
