### ISSUE TITLE
Enhancement: Add context to "Add to Cart" link text

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce#16925]
From the WordPress Theme Review Requirements:

> Links must avoid repetitive non-contextual text strings such as ‘read more…’ and should make sense if taken out of context. Bare urls must not be used as links. Supporting text may use a screen reader class to hide text visually.

`Add to Cart` does not really make sense taken out of context - we should add more context to these actions like `Add Pogo Stick to your cart` for example.

This would also apply to `Read More`, `View Products`, and `Select Options` which occur on the Shop page and also need additional context.

@jameskoster had a good suggestion of wrapping the additional text in a `span` with a `screen-reader-text` class.

**Comment by mikejolley** [comment]
https://www.w3.org/WAI/GL/wiki/Using_aria-label_for_link_purpose
