### ISSUE TITLE
Checkout Loader icon does not display for TwentySeventeen theme

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#16921]
Generally when the checkout is processed, a semi transparent block and the loading icon is overlayed over the checkout form.

The loading icon is set by the following CSS: https://github.com/woocommerce/woocommerce/blob/3.1.2/assets/css/woocommerce.scss#L56-L59

This is enqueued in the stylesheet `woocommerce-general`. But there is some specific compatibility included in WooCommerce for the TwentySeventeen where the `woocommerce-general` stylesheet is removed and replaced with an alternative. See: https://github.com/woocommerce/woocommerce/blob/3.1.2/includes/theme-support/class-wc-twenty-seventeen.php#L35

It would be nice to include the loading icon in the alternative CSS so it can still be shown when the checkout is processed.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16922
