### ISSUE TITLE
Inconsistent number of parameters in `woocommerce_email_header` action.

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#16936]
From this [search](https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=woocommerce_email_header&type=) you'll get list of `woocommerce_email_header` hooks from various template files and all of them have two parameters passed:

```php
do_action( 'woocommerce_email_header', $email_heading, $email );
```

However, in `class-wc-emails.php` only one parameter, `$email_heading`, is passed:

https://github.com/woocommerce/woocommerce/blob/46d3638089b58b51a2321b67443b83f409c6b4ec/includes/class-wc-emails.php#L263-L277

Fatal error will be thrown from the extension that expects two params.

**Comment by mikejolley** [comment]
It's correct to be missing, but we should pass empty string. No email arg.
