### ISSUE TITLE
Date Picker not reflecting the store's timezone

### ISSUE THREAD

**Issue by MillerMedia** [woocommerce/woocommerce#16935]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set WordPress/store's timezone to a timezone more east than your current computer's time zone
2. Place an order after 12AM midnight for the timezone the store is set to while your current timezone is before 12AM midnight
3. Check the reporting and note that you will not be able to choose the 'next day' in the datepicker (the current day in the time zone east of yours but the 'next day' in your current timezone)

## Expected/actual behavior

When I follow those steps, I see...

...I do **not** see the option to pick the day that order was placed in. The WooCommerce reporting appears to detect the computer's current timezone and does not allow you to choose that date in the datepicker until your current timezone passes midnight. You can, however, manually type the day in and access it that. You can also see the current day on the general week overview when you first go to the reporting page. The issue is when you want to isolate that specific day to see the number of orders, revenue etc.

I was expecting to see...

All available dates in the date picker relative to the timezone that the store is set to.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://localhost/~mattmiller/woocommerce
Site URL: http://localhost/~mattmiller/woocommerce
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) PHP/5.6.30
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
SecureTransport

SUHOSIN Installed: –
MySQL Version: 5.7.13
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.37MB
Database Data Size: 1.55MB
Database Index Size: 0.82MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.05MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 1
page: 5
post: 2
product: 2
product_variation: 2
revision: 6
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.2.0-beta.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #20 - /shop/
Cart: #9 - /cart/
Checkout: #11 - /checkout/
My account: #4 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
This is indeed an edge case bug, but not one which can be fixed directly, not without hacking the jquery UI scripts. 

Some background here: https://stackoverflow.com/questions/24666321/jquery-ui-datepicker-change-highlighted-today-date

And the datepicker js source code here: https://github.com/jquery/jquery-ui/blob/master/ui/widgets/datepicker.js#L1663-L1665

jQuery UI sets 'today' to a `new Date()` object. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date This will reflect the clients current local time. There is no way to change this.

jQuery UI has no option or mechanism for setting the current time to a custom value. It's all handled in it's `_generateHTML` method. The trac issue was rejected to control this https://bugs.jqueryui.com/ticket/5427

I don't believe this is a common enough issue to warrant swapping scripts or making a custom version. As a workaround we can just make reports allow 1D into the future.
