### ISSUE TITLE
Are refunds surely handled correct in the tax report?

### ISSUE THREAD

**Issue by jgangso** [woocommerce/woocommerce#16937]
Would like to be enlightened about the following:

The piece of code I'm questioning:
https://github.com/woocommerce/woocommerce/blob/5427d0993b06bdd388a6244010b5f14482a7f27c/includes/admin/reports/class-wc-report-taxes-by-date.php#L123

Considering the large amount of WC shops out there I highly doubt myself, but still to me it seems there is a mistake that the fully refunded orders are excluded from the tax report.

First it might seem obvious that it doesn't make sense to include them since their effect would be zero. But consider the situation where the sale occurs in the end of month, but the (full) refund takes place in the beginning of next month.

The accountant gets sales report of, say July, which includes the sale and the appropriate sales tax. Now when pulling out the August report, if the order got fully refunded, those refund lines wouldn't get included in the calculation since the post_parent has the status *wc-refunded*.
That would mean that in July the taxes are paid as if the sale happened (as it did), but in August the refund would not deduct the payable tax (as it should according to my understanding).

To make the tax report accurate for any given time period, I think we should always include all order_item lines (even those of refunded orders) and SUM them together to get the most correct amount for the given period.

Does anyone understand what I'm trying to explain? If so, are you able to either confirm it or explain me how things go correctly.

Cheers!

**Comment by mikejolley** [comment]
Are you reading code or seeing invalid reports? What version?

The query above that one `$tax_rows_orders = $this->get_order_report_data( array(` should include refunds, so any negative totals are reflected. That may be the bug.

The comment on the line you quoted states: 

> Partial refunds inside refunded orders should be ignored

Which is true. Including partial refunds from refunded orders would mean those refunds are included twice in the report.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16944

**Comment by jgangso** [comment]
Thanks for addressing the issue.
Got invalid reports and found this piece of code by debugging.

:+1: for #16944 

I'm on 3.1.2 btw. Sorry forgot to include that.
