### ISSUE TITLE
Update Product Not Deleting Images

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#16930]
I'm doing a PUT to update a Product on WooCommerce Version 3.1.2:

PUT /wp-json/wc/v2/products/<id>

The Product currently has one image which I would like to remove so I'm including an empty image array:

`"images": [], `

but the image is not deleted and the response includes the details for the existing image:

`"images": [
    {
      "alt": "", 
      "date_created": "2017-09-14T04:59:50", 
      "date_created_gmt": "2017-09-13T08:59:50", 
      "date_modified": "2017-09-14T04:59:50", 
      "date_modified_gmt": "2017-09-13T08:59:50", 
      "id": 3330, 
      "name": "", 
      "position": 0, 
      "src": "https://mywebsite/wp-content/uploads/2017/09/tshirt_PNG5453-2.png"
    }
  ], `

**Comment by mikejolley** [comment]
Maybe the JSON was malformed? Just tested this and it's working. It sets the placeholder image:

<img width="1114" alt="2017-09-26 at 11 43" src="https://user-images.githubusercontent.com/90977/30856363-0761c626-a2b0-11e7-9e42-253a9737ac60.png">

This shows it working acting on dummy data.
