### ISSUE TITLE
Products API: on_sale=true returns all products if none are on sale.

### ISSUE THREAD

**Issue by coderkevin** [woocommerce/woocommerce#16933]
## Prerequisites

Make a store with several products, but none with sale prices.

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

0. Ensure you have products, but none with a sale price.
1. Perform a GET: `/wc/v3/products?on_sale=true`
2. Observe that you receive a complete list of products (or at least the first page)

## Expected/actual behavior

When I follow those steps, I see...

A complete list of products, none of which are "on sale"

I was expecting to see...

An empty list of products, since no products are "on sale".

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: <test site>
Site URL: <test site>
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.9-alpha-41594
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.23
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.55.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Developer: by Automattic – 1.2.6
Jetpack by WordPress.com: by Automattic – 5.1
Log Viewer: by Markus Fischbacher – 14.05.04
REST API Console: by WP REST API Team – 2.1
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 1.4.0
WooCommerce API Dev: by Automattic – 0.8.6
WooCommerce Stripe Gateway: by WooCommerce – 3.2.2
WooCommerce Services: by Automattic – 1.6.2
WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by gedex** [comment]
This comes from `WP_Query`, see [this](https://github.com/WordPress/WordPress/blob/0860bb2771ea82a37c08e8cb7ce54989ebf4c6f2/wp-includes/class-wp-query.php#L1917-L1920). If `post__in` is an empty array, mysql `IN` comparison is not added into the query. Same goes to `post__not_in`. Also, [an old ticket on core](https://core.trac.wordpress.org/ticket/28099) about this and marked as wontfix.

A hacky workaround for this in WC would be to use nonexistent post ID (e.g. `array( 0 )`) when `wc_get_product_ids_on_sale` returns empty array. Or, if we follow core behavior, the API consumer should handle post-checking of `on_sale` attribute of returned results.
