### ISSUE TITLE
Error Log reporting add_to_cart_fragment And WC_Product::adjust_price issue

### ISSUE THREAD

**Issue by legendxu** [woocommerce/woocommerce#16931]
Woocommerce Updated to v3.1.2 and my logs are showing the following error every 2 - 5 minutes:
The The "add_to_cart_fragments" hook uses out of date data structures and function is deprecated since version 3.1.2. Replace with woocommerce_add_to_cart_fragments.

[26-Sep-2017 00:54:42 UTC] The WC_Product::adjust_price function is deprecated since version 3.0. Replace with WC_Product::set_price / WC_Product::get_price.

`
### WordPress Environment ###
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: qy3x_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###
Gravity Forms: by rocketgenius – 1.9.12.1
Access Denied: by wpkids – 1.0
All In One SEO Pack: by Michael Torbert – 2.3.16
Sergey Yakovlev – 2.5
Tim Berneman – 3.5.1
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.1.2
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
McAfee SECURE: by McAfeeSECURE – 1.7.7
No Category Parents: by Sergio Milardovich – 0.2.4.1
Official StatCounter Plugin: by Aodhan Cullen – 2.0.1
Really Simple SSL: by Rogier Lankhorst – 2.5.20
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
SEO SearchTerms Tagging 2: by Purwedi Kurniawan – 1.535
Shareaholic | share buttons, analytics, related content: by Shareaholic – 8.4.4
Text Modules: by Thorsten Frommen – 1.0.1
WooCommerce - All in One SEO Pack: by Visser Labs – 1.3.4
WooCommerce Custom Product Tabs Lite: by SkyVerge – 1.6.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3
WooCommerce - Gravity Forms Product Add-Ons: by Lucas Stark – 2.9.1 – 3.1.11 is available
WooCommerce ShareThis Integration: by WooThemes – 1.0
WooCommerce: by Automattic – 3.1.2
Woopin: by Isaac Oyelowo – 3.1
WooSidebars: by WooThemes – 1.4.3
WP Video Lightbox: by Tips and Tricks HQ
Ruhul Amin – 1.8.4

YITH WooCommerce Wishlist: by YITHEMES – 2.1.2
Elfsight Yottie Lite: by Elfsight – 1.3.0

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #704 - /shop/
Cart: #156 - /cart/
Checkout: #158 - /checkout/
My account: #160 - /my-account/

### Theme ###

Name: Mystile
Version: 1.3.3 – 1.3.19 is available
Author URL: http://www.woothemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by legendxu** [comment]
error_log
![1](https://user-images.githubusercontent.com/7474954/30838274-1eb284cc-a29d-11e7-9ea4-da13ef51bb63.png)

**Comment by legendxu** [comment]
Is this plugin Gravity Forms: by rocketgenius – 1.9.12.1 has questions?

**Comment by mikejolley** [comment]
It's one of the extensions that will need an update. See https://github.com/woocommerce/woocommerce/wiki/Deprecation-in-core#warnings-in-production-store-owners-read-this

**Comment by legendxu** [comment]
https://github.com/woocommerce/woocommerce/wiki/Deprecation-in-core#warnings-in-production-store-owners-read-this
Is this plugin Gravity Forms: by rocketgenius – 1.9.12.1 has questions? If yes, I'll update it.

Thanks!
