### ISSUE TITLE
Filtering Logged-Out Nonces Should be Scoped by Action

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#16940]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

I'm not sure how much refactoring would be needed to resolve this issue, but given WooCommerce core has used the same background processing class that we have in plugins, I wanted to report it.

You can find a full writeup here: https://github.com/skyverge/wc-plugin-framework/pull/243

Essentially, the steps to the issue are this:

- if you create a nonce in a cron context, this nonce is created with user id of 0
- if you then make a request to the site, WC _tries_ to set a session for the server with this request (like the `dispatch()` method in the background processing library)
- even though it can't really create a session, it [sets a flag for `has_cookie`](https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/class-wc-session-handler.php#L45-L48) to indicate it has done so
- if you do _anything else_ within the scope of this same request, this instance of the class now thinks the server has a session, but is logged out. In my case, this means that when we handle the job to start it, and validate the nonce, now WC thinks the server has a session with a user ID of 0
- WC therefore [filters the user ID for the nonce](https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/class-wc-session-handler.php#L67-L69), causing verification to fail.

This is pretty difficult to replicate as I've not often seen sites where we see the nonce verification fail consistently. I figured I'd report it because
 (a) the filtering of those nonces should likely only be scoped to nonces WC creates itself to avoid interfering with third-party code like this, and
 (b) WC itself uses that background processing library, so likely it's had the same issue if you ever tried to start a db upgrade and it never started processing.

(This means there are 2 candidates for that behavior: the host disallowing loopback connections, and this issue.)

## Expected/actual behavior

To not interfere with other plugins' nonce verification 😄 

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active - _I haven't tried to replicate it with just WC, but see how it could_
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above - _Negative, see notes above_

## WordPress Environment

WC 3.1.2, WooCommerce Customer / Order XML Export 2.2.6 in this case, but I've seen the same issue with our CSV Export / CSV Import plugins, all related to background processing.

**Comment by mikejolley** [comment]
Should also investigate why sessions are required for cron requests. That may not be needed.

**Comment by mikejolley** [comment]
Looking at how WP defines DOING_CRON, I think we're wrong to init a session here.

I'm going to work on removing that during cron events, and then fix https://github.com/woocommerce/woocommerce/issues/7183 in a different way since that was broken before.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18193
