### ISSUE TITLE
woocommercce figure not showing 

### ISSUE THREAD

**Issue by cahyo9823** [woocommerce/woocommerce#16951]
**MY ISSUE** 
i just update woocommerce and firgure not showing 
![problem](https://user-images.githubusercontent.com/32321288/30898997-3724c074-a388-11e7-96ef-ba3cb87e9cd6.jpg)

and also this  if look in mobile 
![mobile](https://user-images.githubusercontent.com/32321288/30899060-7f7a21ca-a388-11e7-8364-43673b25906d.jpg)

**Comment by mikejolley** [comment]
Your theme lacks support for the new gallery it seems. 

https://github.com/woocommerce/woocommerce/wiki/Enabling-product-gallery-features-(zoom,-swipe,-lightbox)-in-3.0.0

See if there are theme updates/contact the author.

Thanks
