### ISSUE TITLE
[WC3.2] Applying coupon from edit order screen issues

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce#16952]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a coupon which is restricted to a particular product (screenshot: https://cldup.com/b2Cw5j4PZj.png)
2. Manually add a new order from the **WooCommerce > Orders** table clicking the **"Add order"** button.
3. Add the product you restricted the coupon to (screenshot: https://cldup.com/NlW6cDxRmi.png).
4. Attempt to apply the coupon using the **"Apply coupon"** button.

## Expected/actual behavior

When I follow those steps, I see no coupon being applied and no error (video: https://cldup.com/zMgJ9tWbqg.gif)

I was expecting to see a coupon and discount being applied. 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

The issue appears to be two-fold. 

1. When WC attempts to apply the coupon via AJAX [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L932), it looks as though it's expecting an exception to be thrown if the coupon fails to be applied (note the try catch block), however, `$order->apply_coupon()` returns `WP_Error` objects ([here](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L914) for example) when it fails. So basically when the coupon isn't applied, the AJAX request silently fails to apply the coupon and returns a successful result.

2. The AJAX request calls [`$order->apply_coupon()`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L932), which calls [`$coupon->is_valid()`](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L903), which uses the [cart object](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-coupon.php#L778-L779) to validate the coupon rather than the order. Because the cart doesn't contain the product, it returns false and so the coupon isn't applied. 

## WordPress Environment
<details>
### WordPress Environment ###

Home URL: http://localhost/trial
Site URL: http://localhost/trial
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.0.15 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.0.15
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.5.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 91.51MB
Database Data Size: 59.59MB
Database Index Size: 31.92MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 1.52MB
wp_woocommerce_order_itemmeta: Data: 8.52MB + Index: 10.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.09MB + Index: 0.03MB
wp_comments: Data: 5.52MB + Index: 5.17MB
wp_email_log: Data: 20.52MB + Index: 0.00MB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB
wp_groups_group: Data: 0.02MB + Index: 0.02MB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 7.02MB + Index: 0.17MB
wp_postmeta: Data: 14.09MB + Index: 13.11MB
wp_posts: Data: 1.28MB + Index: 0.66MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_subscription_dates: Data: 0.02MB + Index: 0.11MB
wp_subscription_related_orders: Data: 0.02MB + Index: 0.11MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.25MB + Index: 0.23MB
wp_users: Data: 0.05MB + Index: 0.05MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB
wp_wpeditor_settings: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 39
customize_changeset: 5
follow_up_email: 1
forum: 1
global_product_addon: 1
nav_menu_item: 9
page: 30
payment_retry: 351
post: 4
product: 285
product_variation: 454
revision: 94
scheduled-action: 1386
shop_coupon: 22
shop_order: 402
shop_order_refund: 40
shop_subscription: 463
shop_webhook: 2
topic: 1
wc_membership_plan: 5
wc_order_status: 7
wc_pickup_location: 3
wc_product_tab: 1
wc_user_membership: 2
wccpf: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.0-beta.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.4 – 2.2.5 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/16956
