### ISSUE TITLE
WooCommerce, PayPal Order Cancelled.

### ISSUE THREAD

**Issue by svaibhav15** [woocommerce/woocommerce#16950]
Hi
I opened this new issue as you closed my previuos issue and I am not aware if you get any notification afetr I updated the issue number 16947. Sorry for inconvenience, but I am facing this issue and it is causing huge loss to my business.
I am using WordPress version 4.8.2, , Woo commerce: Version 3.1.2 .
Some payments are getting cancelled, some are successful.
These are Order notes:
Order cancelled by customer. Order status changed from Pending payment to Cancelled.

Although customer did not cancelled the order, he said he paid and then got cancellation email.

Please help with it is causing business loss.

**Comment by svaibhav15** [comment]
Please see below system status report

**Comment by svaibhav15** [comment]
WordPress Environment

Home URL: https://buytruefollowers.com
Site URL: https://buytruefollowers.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Server Environment

Server Info: Apache
PHP Version: ❌ 5.5.38 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Database

WC Database Version: 3.1.2
WC Database Prefix: wpnj_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Security

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔
Active Plugins (30)

Ultimate Addons for Visual Composer: by Brainstorm Force – 3.16.10
AddToAny Share Buttons: by AddToAny – 1.7.19
iThemes Security: by iThemes – 6.6.1
Contact Form 7: by Takayuki Miyoshi – 4.9
Disable Variable Product Price Range Woocommerce: by Geek Web Solution – 1.0
Duplicate Post: by Enrico Battocchi – 3.2
Dynamic Featured Image: by Ankit Pokhrel – 3.6.1
WooCommerce Email Customizer: by cxThemes – 3.07
EWWW Image Optimizer: by Shane Bishop – 3.6.1
Flexible Checkout Fields: by WP Desk – 1.5.2
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.1.1.2
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
MyLiveChat: by MyLiveChat – 2.0.1
Ninja Forms: by The WP Ninjas – 3.2.1
Porto Content Types: by SW-THEMES – 1.3.1
Porto Shortcodes: by SW-THEMES – 1.6.6
Porto Widgets: by SW-THEMES – 1.3.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
Slider Revolution: by ThemePunch – 5.4.1
WooCommerce - Instamojo: by instamojo – 1.0.7
WooCommerce 2Checkout Payment Gateway Free: by Najeeb Ahmad – 2.0
WooCommerce - Country Based Payments: by Ivan Paulin – 1.1.8
Woocommerce Product Custom Options Lite: by phoeniixx – 1.7.5
WooCommerce PayU India (PayUmoney & PayUbiz): by _KDC-Labs – 2.1.0
WooCommerce Price Based on Country (Basic): by Oscar Gare – 1.6.19
WooCommerce: by Automattic – 3.1.2
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO: by Team Yoast – 5.5
WP Sitemap Page: by Tony Archambeau – 1.6
Settings

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
WC Pages

Shop base: #207 - /shop/
Cart: #9896 - /cart/
Checkout: #9898 - /checkout/
My account: ❌ Page visibility should be public
Theme

Name: Porto
Version: 3.5
Author URL: http://www.newsmartwave.net/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔
Templates

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.1.0
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.1.0
porto/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
porto/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.1.0
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
porto/woocommerce/content-product_cat.php
porto/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
porto/woocommerce/content-widget-product.php
porto/woocommerce/emails/customer-processing-order.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php version 2.0.0 is out of date. The core version is 3.0.0
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/downloads.php version 2.6.0 is out of date. The core version is 3.0.0
porto/woocommerce/myaccount/form-add-payment-method.php version 2.6.0 is out of date. The core version is 3.0.0
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php version 2.6.0 is out of date. The core version is 3.0.9
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php version 2.6.0 is out of date. The core version is 3.0.0
porto/woocommerce/myaccount/form-reset-password.php version 2.6.0 is out of date. The core version is 3.0.0
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/orders.php version 2.6.0 is out of date. The core version is 3.0.0
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php version 2.6.0 is out of date. The core version is 3.0.0
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/order-details.php version 2.6.0 is out of date. The core version is 3.0.0
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/external.php
porto/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.7
porto/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
porto/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
porto/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
porto/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.1.0
porto/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.1.0
porto/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.1.0
porto/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.1.0
porto/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
porto/woocommerce/single-product/review-meta.php version 2.6.0 is out of date. The core version is 3.0.0
porto/woocommerce/single-product/review-rating.php version 2.6.0 is out of date. The core version is 3.1.0
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/share.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
porto/woocommerce/single-product-reviews.php

Outdated Templates: ❌Learn how to update
PBC Settings

Base location: US:CA
Price Based On: billing
Shipping: –
Test mode: –
Test country: IN
Zone Pricing Indian

slug: indian
name: Indian
countries: IN
currency: INR
exchange_rate: 64.04

**Comment by svaibhav15** [comment]
[System Status Report.txt](https://github.com/woocommerce/woocommerce/files/1335721/System.Status.Report.txt)

**Comment by svaibhav15** [comment]
These are PayPal logs since yesterday. These are Order ids which were cancelled : 10897, 10895 , 10893, 10890, 10889, 10886, 10884, 10883 , 10882, 10881, 10879, 10877.
I also saw this error in logs: 2017-09-27T02:22:17+00:00 ERROR Order Keys do not match.

**Comment by svaibhav15** [comment]
[paypal-502763d3a03ce8147822561ff75a31f8.log](https://github.com/woocommerce/woocommerce/files/1335725/paypal-502763d3a03ce8147822561ff75a31f8.log)

**Comment by mikejolley** [comment]
1.  if an order is cancelled in WC, it won't touch any funds in PayPal. **Verify the transactions occurred.**

2. "Some payments are getting cancelled, some are successful." shows that the gateway is working, but some users may be sending fraudulent requests. Again, **verify the transactions occurred in your PayPal account.**

3. As @claudiulodro pointed out yesterday, "Order cancelled by customer" can only be triggered manually, by the customer. They go to their account page and click 'cancel' on an unpaid order and it will cancel the order in WooCommerce. So to be frank, I think your "customer" may be lying to you :)

4. The logged error "Order Keys do not match" shows that the IPN request may have been tampered with, or you could have an extension conflict. So again again, verify the transaction in PayPal, if it's there do tests with other plugins off and the default theme enabled.

This doesn't appear to be a bug, but potential misuse by the customer. Hope this helps narrow it down. If in doubt, run a test transaction yourself.

**Comment by svaibhav15** [comment]
Hi
Customers are repeated customers from long time.
There are no transactions in PayPal for Cancelled Order.

**Comment by mikejolley** [comment]
> There are no transactions in PayPal for Cancelled Order.

Which means they didn't pay.

**Comment by svaibhav15** [comment]
I observed that for cancelled orders Logs came like this: 

2017-09-27T00:35:59+00:00 INFO Generating payment form for order 10895. Notify URL: https://buytruefollowers.com/wc-api/WC_Gateway_Paypal/
2017-09-27T00:35:59+00:00 INFO PayPal Request Args for order 10895: cmd=_cart&business=support%40buytruefollowers.com&no_note=1&currency_code=USD&charset=utf-8&rm=2&upload=1
&return=https%3A%2F%2Fbuytruefollowers.com%2Fcheckout%2Forder-received%2F10895%3Fkey%3Dwc_order_59caf1bab0b41%26utm_nooverride%3D1&cancel_return=https%3A%2F%2Fbuytruefollowers.com%3F
cancel_wp_id%3DaHR0cHM6Ly9idXl0cnVlZm9sbG93ZXJzLmNvbS9jYXJ0Lz9jYW5jZWxfb3JkZXI9dHJ1ZSZvcmRlcj13Y19vcmRlcl81OWNhZjFiYWIwYjQxJm9yZGVyX2lkPTEwODk1JnJlZGlyZWN0Jl93cG5vbmNlPWQwNGI1YTBiNGU&
page_style=&image_url=&paymentaction=sale&bn=WooThemes_Cart&invoice=WC-10895&custom=%7B%22order_id%22%3A10895%2C%22order_key%22%3A%22wc_order_59caf1bab0b41%22%7D&
notify_url=https%3A%2F%2Fbuytruefollowers.com%2Fwc-api%2FWC_Gateway_Paypal%2F&first_name=Uyen&last_name=Tran&address1=&address2=&city=&state=&zip=&country=US&
email=peheoiuck4ever%40yahoo.com&night_phone_a=832&night_phone_b=807&night_phone_c=1156&no_shipping=1&tax_cart=0.00&
item_name_1=Facebook+Followers+-+100+Followers+%242+%28Facebook+Followers%3A+100+Followers+-+%242%2C+Facebook+Profile+URL%3A+https%3A%2F%2Fm.facebook.com%2F...&quantity_1=1&
amount_1=2&item_number_1=

**Comment by mikejolley** [comment]
No transaction = no payment. That combined with the bad IPN request means they are likely trying to send fraudulent orders.

**Comment by svaibhav15** [comment]
while for successful transactions logs shows IPN check and response: 
2017-09-27T00:39:33+00:00 INFO Generating payment form for order 10896. Notify URL: https://buytruefollowers.com/wc-api/WC_Gateway_Paypal/
2017-09-27T00:39:33+00:00 INFO PayPal Request Args for order 10896: cmd=_cart&business=support%40buytruefollowers.com&no_note=1&currency_code=USD&charset=utf-8&rm=2
&upload=1&return=https%3A%2F%2Fbuytruefollowers.com%2Fcheckout%2Forder-received%2F10896%3Fkey%3Dwc_order_59caf344d1815%26utm_nooverride%3D1&cancel_return=https%3A%2F%2Fbuytruefollowers.com
%3Fcancel_wp_id%3DaHR0cHM6Ly9idXl0cnVlZm9sbG93ZXJzLmNvbS9jYXJ0Lz9jYW5jZWxfb3JkZXI9dHJ1ZSZvcmRlcj13Y19vcmRlcl81OWNhZjM0NGQxODE1Jm9yZGVyX2lkPTEwODk2JnJlZGlyZWN0Jl93cG5vbmNlPWQwNGI1YTBiNGU
&page_style=&image_url=&paymentaction=sale&bn=WooThemes_Cart&invoice=WC-10896&custom=%7B%22order_id%22%3A10896%2C%22order_key%22%3A%22wc_order_59caf344d1815%22%7D&
notify_url=https%3A%2F%2Fbuytruefollowers.com%2Fwc-api%2FWC_Gateway_Paypal%2F&first_name=Uyen&last_name=Tran&address1=&address2=&city=&state=&zip=&country=US&
email=peheoiuck4ever%40yahoo.com&night_phone_a=832&night_phone_b=807&night_phone_c=1156&no_shipping=1&tax_cart=0.00&
item_name_1=Facebook+Followers+-+100+Followers+%242+%28Facebook+Followers%3A+100+Followers+-+%242%2C+Facebook+Profile+URL%3A+https%3A%2F%2Fm.facebook.com%2F...&quantity_1=1&
amount_1=2&item_number_1=



2017-09-27T00:40:00+00:00 INFO Checking IPN response is valid
2017-09-27T00:40:00+00:00 INFO IPN Request: Array
(
    [body] => Array
        (
            [mc_gross] => 2.00
            [invoice] => WC-10896
            [protection_eligibility] => Eligible
            [item_number1] => 
            [payer_id] => 3LZ4BKUKPXFVA
            [tax] => 0.00
            [payment_date] => 17:39:53 Sep 26, 2017 PDT
            [payment_status] => Completed
            [charset] => windows-1252
            [first_name] => Uyen
            [mc_fee] => 0.39
            [notify_version] => 3.8
            [custom] => {"order_id":10896,"order_key":"wc_order_59caf344d1815"}
            [payer_status] => unverified
            [business] => support@buytruefollowers.com
            [num_cart_items] => 1
            [verify_sign] => Anew95gxNtCzg1X9d-VO9MBeNGgrAQvHgKUCFrtFKVZG3fFizama93yY
            [payer_email] => peheoiuck4ever@yahoo.com
            [txn_id] => 55362949YE565000U
            [payment_type] => instant
            [last_name] => Tran
            [item_name1] => Facebook Followers - 100 Followers $2 (Facebook Followers: 100 Followers - $2, Facebook Profile URL: https://m.facebook.com/...
            [receiver_email] => support@buytruefollowers.com
            [payment_fee] => 0.39
            [quantity1] => 1
            [receiver_id] => 5KTY3JDXVFM3C
            [txn_type] => cart
            [mc_gross_1] => 2.00
            [mc_currency] => USD
            [residence_country] => US
            [transaction_subject] => 
            [payment_gross] => 2.00
            [ipn_track_id] => 7a4a8631aca7b
            [cmd] => _notify-validate
        )

    [timeout] => 60
    [httpversion] => 1.1
    [compress] => 
    [decompress] => 
    [user-agent] => WooCommerce/3.1.2
)

2017-09-27T00:40:00+00:00 INFO IPN Response: Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [server] => Apache
                    [x-frame-options] => SAMEORIGIN
                    [http_x_pp_az_locator] => dcg11.slc
                    [content-encoding] => gzip
                    [paypal-debug-id] => 1bec31587a4f5
                    [cache-control] => max-age=0, no-cache, no-store, must-revalidate
                    [pragma] => no-cache
                    [content-type] => text/html; charset=UTF-8
                    [dc] => slc-b-origin-www-2.paypal.com
                    [content-length] => 34
                    [x-edgeconnect-midmile-rtt] => 1
                    [x-edgeconnect-origin-mex-latency] => 491
                    [date] => Wed, 27 Sep 2017 00:40:00 GMT
                    [vary] => Accept-Encoding
                    [set-cookie] => Array
                        (
                            [0] => cwrClyrK4LoCV1fydGbAxiNL6iG=Cz-90JmAD2hOmVh5lmrikfqjX8AW9j0RX7QznA0WBGYmcVpoJO16YD0GDwm4cxvY7Rm1MXg08fFTCgtVyJn9qGBdaRvPyXkAtJKB0s2NCYm-5c-sG-HibNxraOudKTtpfA3A9lftAFVyO8UuZQPiVcuwEkLrto3rxD44TV4Gxay-dvoQ2m_Ol4rznjadL8yAypivh5GQT68Q6qfGnrTH5ZrpmxRSS8N1c5xtZ-ToZ9dYQZNXLxd17jg_TdyK_bOD2prvglmBX7ABpw4P9xRmAhMpYBuAPbOhfZFRPXZfPmqV4xF8n0PNpc8VkkZEuUl-oOQr72Nbz8fIYh731arbLjrhBTHA78ojEjd8vLIMw_cec5rWdveQrKRFEVY2FUuArfRKHwdYXp6afrTVg8G2Jl3S9bFluOTrq0FbWXVD_oqMmtazO7dyyMnZ-Bq; domain=.paypal.com; path=/; Secure; HttpOnly
                            [1] => cookie_check=yes; expires=Sat, 25-Sep-2027 00:40:00 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
                            [2] => navcmd=_notify-validate; domain=.paypal.com; path=/; Secure; HttpOnly
                            [3] => navlns=0.0; expires=Fri, 27-Sep-2019 00:40:00 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
                            [4] => X-PP-SILOVER=name%3DLIVE6.WEB.1%26silo_version%3D880%26app%3Dappdispatcher%26TIME%3D1626589785%26HTTP_X_PP_AZ_LOCATOR%3Ddcg11.slc; Expires=Wed, 27 Sep 2017 01:10:00 GMT; domain=.paypal.com; path=/; Secure; HttpOnly
                            [5] => X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT
                            [6] => AKDC=slc-b-origin-www-2.paypal.com; expires=Wed, 27-Sep-2017 01:10:00 GMT; path=/; secure
                            [7] => akavpau_ppsd=1506473400~id=a60a223bd4cbf6b3997b1aa17c36eba2; Path=/
                        )

                    [strict-transport-security] => max-age=63072000
                )

        )

**Comment by mikejolley** [comment]
So again, no payment. Read my replies again - there is no issue here. The issue is your customer.

**Comment by svaibhav15** [comment]
They tried to pay but got the canceled response. Many of them are repeated customers from long time.

**Comment by svaibhav15** [comment]
For 1 or 2 customers I could understand but it happened with 70+ customers within 48 hours.

**Comment by svaibhav15** [comment]
I have sucuri firewall, could that cause the issue ? Althoug sucuri support has denied it.

**Comment by svaibhav15** [comment]
When I send them invoice most paid of them paid it.

**Comment by svaibhav15** [comment]
Please help.

**Comment by mikejolley** [comment]
Why not do some test transactions yourself, or turn off firewall and let them retry?

**Comment by mikejolley** [comment]
Fact is; cancel note is only posted when they cancel, either from their account page, or by clicking the cancel link on paypal website.

**Comment by svaibhav15** [comment]
Just now turned off the firewall, will see if it helps.
I did test transactions all are successful. Some other customers also were able to pay.

**Comment by svaibhav15** [comment]
@mikejolley  1 hour back One customer paid for two services, first payment was success and second one cancelled. I think not all customers are trying fraudulent payment. As I already mentioned many are repeated customers from long time, the chances that they do fraudulent is 100% zero.

**Comment by svaibhav15** [comment]
@mikejolley  Issue is somewhere else and I and my developer is very confused how to troubleshoot. Please advice.

**Comment by mikejolley** [comment]
You should ask them what happened on the PayPal side.

**Comment by svaibhav15** [comment]
@mikejolley  
Does Woocomerce use REST API or SOAP & NVP API ?
I saw this notification on PayPal website. Can this be source of error ?

Initial Notification: We are experiencing an issue which is affecting ExpressCheckout calls on the Production environment. PayPal Merchants may be experiencing a higher than usual error rate in SetExpressCheckout API calls with error code: 

11601 - DISABLED_ADDRESS_ENHANCEMENTS_PHASE1_FOR_MERCHANT

Our technical teams have been engaged and are actively troubleshooting the issue.

**Comment by mikejolley** [comment]
NVP

**Comment by svaibhav15** [comment]
@mikejolley 
Hi Mike,
I now have installed PayPal Express Checkout, that is working fine for all transactions but buyer's who tries with PayPal standard are getting Order cancellation issue.
Please advice what can be done for PayPal standard error. 
Is there a provision in Woocommerce plugin to use PayPal REST API instead of using PayPal Standard to make payment ?

**Comment by svaibhav15** [comment]
Or may be it was happening since I had PayPal individual account  and yesterday I switched to business account ?

**Comment by mikejolley** [comment]
There are other paypal plugins if you don't want to use Standard. But everything I've seen so far has indicated an intentional cancellation. Ask PayPal?

**Comment by leeapogee** [comment]
I seem to be having this issue on a site suddenly too, customer places order, immediately set to cancelled, but customer taken to paypal and payment made OK then order status changed. Did anyone get to the bottom of this? Definitely not customer cancelled (2 different customers in a few days)

Thanks

**Comment by TomasHurtz** [comment]
I also see this issue on occasion and the customer calls through to say PayPal keep cancelling the transaction. I think something funny is going on at PayPal but they don't always share issues in their Status.

Seems odd that it works fine for a while, then one day, several cancelled orders where the customer have then contacted us to ask what's going on.

On stores where I use Stripe - there appears no such issue.

**Comment by svaibhav15** [comment]
@leeapogee @TomasHurtz  This error comes because of technical issue with PayPal. It happens mostly with PayPal individual accounts. After switching to PayPal business account I never faced the cancellation issue.
But with individual account this issue may come sometime.

**Comment by TomasHurtz** [comment]
@svaibhav15 thanks for the reply - the site uses a PayPal business account and I am noticing some orders are getting duplicated - and also some orders are automatically cancelling, but the customer says they didn't cancel.  I'm going to ditch PayPal and go to Stripe as I don't notice this issue with any Stripe store.

**Comment by masiorama** [comment]
I'm having the same issue, with a PayPal Business account. Some order are cancelled, some are not.
