### ISSUE TITLE
Remove all data silently disappeared?

### ISSUE THREAD

**Issue by kieranbarnes** [woocommerce/woocommerce#16964]
What happened to "Remove All Data" from the Tools page?

![image](https://user-images.githubusercontent.com/1001484/30929452-861acd1c-a3b6-11e7-957e-fece9f2206e0.png)

It exists on WC2 but is not longer visible on WC3. No mention in the change log of it being removed.

It was a useful feature.

**Comment by mikejolley** [comment]
It's a dangerous option :) You can use the constant `WC_REMOVE_ALL_DATA` if you want this to be enabled/default.

**Comment by kieranbarnes** [comment]
Awesome @mikejolley. Appreciate it.
