### ISSUE TITLE
class-wc-query.php version not updated.

### ISSUE THREAD

**Issue by dcelsey** [woocommerce/woocommerce#16963]
Just wanted to let you know that the file call-wc-query.php in woo 3.1.2 doesn't match the version in the online docs (https://docs.woocommerce.com/wc-apidocs/source-class-WC_Query.html#427-486)

They both say version 2.6.0 at the top but the function get_catalog_ordering_args is different - specifically the code for the order_by price has changed from using the $args parameters to adding a filter to posts_clauses. There may be other differences as well. 

I was trying to fix a problem looking at the version in the online docs so this had me confused for a while.

Also for info the switch to using add_filter('post_clauses'... has the potential to impact anyone who is using the woocommerce_get_catalog_ordering_args (like me!) as that filter becomes irrelevant for any orderbys that use the filter hook.

**Comment by claudiosanches** [comment]
I just updated the version on the file.
Thanks for report it.

**Comment by dcelsey** [comment]
Thanks. The online docs for 3.0 WC_Query still links to an old version of the file tho...

https://docs.woocommerce.com/wc-apidocs/source-class-WC_Query.html#427-486

**Comment by claudiosanches** [comment]
@dcelsey yes, because we need to build it again and deploy. Something that we are doing only before release 3.2.
