### ISSUE TITLE
Rounding/Calculation Error

### ISSUE THREAD

**Issue by sanderdekroon** [woocommerce/woocommerce#16968]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

**Note:** As far as I know this only occurs with complex and big orders.

I have a fairly big order where multiple items are ordered multiple times. On top of that, there are three coupons applied to the order. This will create a difference between the total of all lines and what WooCommerce says the order total is. Note that the prices are entered including tax.

**The order:**
There are three discounts applied to the whole order, 10% off, €10 off, 8% off. In that order.

The items that are within the order are:

Item A, costs €2.50 (including 6% BTW (VAT)).
Ordered 9. Including tax and with discounts applied it's €16.85

Item B, costs €1.30 (including 6% BTW (VAT)).
Ordered 7. Including tax and with discounts applied it's €6.81

Item C, costs €1.50 (including 6% BTW (VAT)).
Ordered 11. Including tax and with discounts applied it's €12.35

Item D, costs €2.50 (including 6% BTW (VAT)).
Ordered 6. Including tax and with discounts applied it's €11.23

Item E, costs €2.50 (including 6% BTW (VAT)).
Ordered 3. Including tax and with discounts applied it's €5.62

Item F, costs €4 (including 6% BTW (VAT)).
Ordered 11. Including tax and with discounts applied it's €32.94

Item G, costs €1.35 (including 6% BTW (VAT)).
Ordered 4. Including tax and with discounts applied it's €4.04

Item H, costs €1.60 (including 6% BTW (VAT)).
Ordered 8. Including tax and with discounts applied it's €9.58

Item I, costs €1.50 (including 6% BTW (VAT)).
Ordered 5. Including tax and with discounts applied it's €5.62

**The problem:**
According to WooCommerce the total is €105,05. 
But when adding all the totals of all line items together, I get €105,04.

I noticed this when I was exporting this order to external invoice software. This software (WeFact) did calculate the total correctly, but it looks like WooCommerce doesn't.

[A screenshot of the back-end order can be found here.](https://imgur.com/a/CgEee)

## Example
```php
<?php
$order = wc_get_order(37279);
$items = $order->get_items();

$total = 0;

foreach ($items as $item) {
    $total += $item->get_total() + $item->get_total_tax();
}

if ($total == $order->get_total()) {
    // This should happen
} else {
    // But but instead, this is happening
    printf('Calculated total: %f, WooCommerce total: %s', $total, $order->get_total());
}
```

## Isolating the problem
- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

What could be happening here?

**Comment by mikejolley** [comment]
<img width="1031" alt="2017-09-28 at 12 23" src="https://user-images.githubusercontent.com/90977/30964124-eef42932-a447-11e7-91f4-86e74ac6ec40.png">

Frontend adds up correctly. Subtotal - the discounts = 105.05

Also seems correct on backend in my test on master (3.2).

16.05+6.06+11.10+10.75+5.38+32.37+3.61+8.70+5.09+0.96+0.36+0.67+0.64+0.32+1.94+0.22+0.52+0.31=105.05

https://dl.dropboxusercontent.com/s/ys2cdme4dcyeego/2017-09-28%20at%2012.26.png

I think it's likely one of the line items has > 2 dp, so when you add up the ROUNDED values you get a discrepancy. 

But it won't be an issue in **3.2** since the discount rounding logic has changed to avoid fractions.
