### ISSUE TITLE
Variation Image Replaces Product Image

### ISSUE THREAD

**Issue by ymsstudios** [woocommerce/woocommerce#16978]
When choosing a product variation on a variable product, the variation image replaces the product image both in the image view and thumbnail and there is no way of viewing the product image again.

This is very frustrating for shoppers and makes product variation images very hard to use or sometimes unuseful for a lot of shop owners.

For example, Let's say I sell shirts and I have a white shirt with 3 variations - blue buttons, red buttons and green buttons. The main image is the full shirt and each variation has a close-up image of the buttons, once you choose a variation you can't view the main image of the full shirt.

It will get even more annoying if you sell something like light bulbs and you have one bulb with different color temperatures as variations. The main product image is the bulb itself and the variations have images how the particular color temperature looks in a room, once you choose a color temperature there is no way to view the image of the bulb.

The simple fix would be to just update the main image in the image view and not to update thumbnail where shoppers will still be able to choose the main product image again or to add another image to the thumbnail gallery when choosing a product variation.

**Comment by kloon** [comment]
This sounds like an issue with your theme, when you have images assigned to variations it will change the main image to that set on your variation and then simply select the tumbnail based on the variation image leaving all the other thumbnails in place.

![Variation Images Frontend](https://cdn-pro.dprcdn.net/files/acc_403010/BieiOh)

Also, check that all the images you are using on the variations are part of the image gallery on the product edit page, although this is not mandatory as variation images are automatically added hence why I say this is an issue with your theme.

![Image Gallery Setting](https://cdn-pro.dprcdn.net/files/acc_403010/YxQ1pp)

**Comment by ymsstudios** [comment]
I contacted the theme developer and he sent me this video showing how he tries this with a few themes and all have the same issue.

See his video here: [https://www.useloom.com/share/4c5be492afb04367b99ddfe2cb057f7a](https://www.useloom.com/share/4c5be492afb04367b99ddfe2cb057f7a)

Here is a video of me explaining the issue: [https://www.useloom.com/share/e6f46c0ec2724e638d67307a8aeace55](https://www.useloom.com/share/e6f46c0ec2724e638d67307a8aeace55)
