### ISSUE TITLE
Enhancement: Store both Live and Sandbox details for PayPal

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#16975]
The PayPal gateway shipped with WooCommerce has an option to enable "Sandbox" mode, but requires admins to update the API credentials each time they do so.

The Stripe gateway on the other hand, toggles the credential fields allowing you to store both the live and test details.

Considering the code for both gateways is very similar and to promote conformity, would probably make sense to add the missing fields for Sandbox details.

**Comment by mikejolley** [comment]
Seems like a small, low impact enhancement. Want to send a PR? I'll mark it for first contributors.

**Comment by mikejolley** [comment]
Thanks, let's discuss in https://github.com/woocommerce/woocommerce/pull/16986
