### ISSUE TITLE
Billing State not matching Mexico Valid States list on Order Detail

### ISSUE THREAD

**Issue by aerojun** [woocommerce/woocommerce#16977]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Generate a order and in the checkout, select "Guerrero" state.
2. Place order.
3. Go to order and edit the billing data. The selected state in the dropdown is not "Guerrero".

## Expected/actual behavior

When I follow those steps, I see... It automaticaly selects "Nuevo León" state.

I was expecting to see... The state "Guerrero".

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

When creating an order in the checkout, I select the state "Guerrero" from the dropdown and palce the order. But when I go to the order details and edit the billing information, the state select is not the right one.

Attached screenshots:
[The billing information is correct when looking at the order detail but is uppercase.](https://i.imgur.com/XMjpnrz.png)
[The billing_state in the DB is in uppercase](https://i.imgur.com/JlSrMN3.png)
[It selects another state when editing the billing details](https://i.imgur.com/saU3y4x.png)

**Comment by claudiulodro** [comment]
Which version of WooCommerce is this on? The upcoming 3.2 release has some fixes for MX states,  and I don't have any of these problems when I test on that.

**Comment by aerojun** [comment]
@claudiulodro WordPress 4.8.2 Woocommerce 3.1.2

**Comment by kloon** [comment]
As Claudiu states there were some changes made to MX states in the upcomming 3.2 release. I have just tested this with 3.2 RC 1 and cannot reproduce the error there.

I'd suggest you if you can test this on 3.2 RC 1 then please do to confirm that it is working for you.
