### ISSUE TITLE
Some WooCommerce strings not translated 

### ISSUE THREAD

**Issue by yogadeployer** [woocommerce/woocommerce#16980]
Hi,

I have the same issue as https://github.com/woocommerce/storefront/issues/611 which was closed b/c it was posted to /storefront instead of /woocommerce ...

In short, the theme I am using tries – imho correctly – to get a translation by e. g. `esc_attr_e('Apply Coupon', 'woocommerce');` As German WooCommerce is properly translated (I checked that in Loco Translate), I expect to see "Gutschein anwenden" – but it still outputs "Apply Coupon".

Other strings that behave the same are e. g. 
- Cart totals
- Customer details
- Update cart

Any ideas, why?

**Comment by claudiosanches** [comment]
Hello, you need to translate in https://translate.wordpress.org/projects/wp-plugins/woocommerce
You can find more details about it in https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md#contribute-to-localizing-woocommerce

Thanks.

**Comment by yogadeployer** [comment]
Hi,

German WooCommerce is 100% translated, so this should definitely work.

Thanks

**Comment by mikejolley** [comment]
The string is correctly localised in core. esc_attr_e works the same as _e.

**Comment by yogadeployer** [comment]
OK – any ideas, why it's not showing the translated string then?

**Comment by claudiosanches** [comment]
@yogadeployer maybe coming from other plugin or using outdated translation files.

**Comment by mikejolley** [comment]
Right; the string may have a different textdomain if output by something else.
