### ISSUE TITLE
Active menu CSS classes are missing from some Woocommerce shop pages

### ISSUE THREAD

**Issue by lightbox000** [woocommerce/woocommerce#16989]
Hi there,

This is a very minor issue, but the active menu CSS classes, for example "current-page-parent", "current-page-ancestor", "current_page_parent", "current_page_ancestor" etc, appear to be missing from the shop menu item when on shop taxonomy pages (product tags archives, product attribute archives, shipping class archives, etc)  and also when on category pages that are more than 1 level deep (subcategories).

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Visit a shop taxonomy page or subcategory page.
2. Inspect the shop link/menu item CSS and note the missing active classes.

## Expected/actual behavior

The menu item should have CSS classes that look something like:

"menu-item menu-item-type-post_type menu-item-object-page **current-menu-ancestor current-menu-parent current_page_parent current_page_ancestor** menu-item-has-children  menu-item-1185 has-dropdown"

Example missing CSS classes in bold.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
WP 4.8.2 & Woocommerce 3.1.2
</details>
<br>
Thank you!

**Comment by mikejolley** [comment]
These classes show the hierarchy/structure. Shop is a page. Taxonomies are not pages. Therefore, WordPress will not generate these classes for the shop menu item.

Only sub-pages (actual pages) under 'shop' will get these classes.

**Comment by lightbox000** [comment]
Hi Mike,

Thanks for your reply. One question though, how come categories and product pages seem to get these classes, yet subcategories (and taxonomies) don't?

**Comment by mikejolley** [comment]
Looks like https://github.com/woocommerce/woocommerce/blob/d56d11f1aaf500a6927a0f7bf74a38db4d92d9d5/includes/wc-page-functions.php#L143 handles products specifically.
