### ISSUE TITLE
Producta data dropdown menu tab is unresponsive on tablets

### ISSUE THREAD

**Issue by Lovrata** [woocommerce/woocommerce#16987]
Hi everyone!

So the problem is with Woocommerce plugin that Producta data tab is unresponsive on tablet. ( in this case is 5.1 Android and also 4.2 Android). While when working on Desktop PC's ( Linux and Win7) everything is working perfect.

Meaning it is working just fine when you add Simple product ( on tablet) . But when it comes that you need to ad Variable product and you tap with finger on dropdown menu "Simple product" nothing happens ( on tablet) . Dropdown menu is not working ( on tablet) and you can not select Variable product.

**Comment by mikejolley** [comment]
Do you have 'request desktop site' checked in chrome settings on the tablet?

Works perfect for me on android mobile, unless I check that in which case it breaks I think due to some scripts included by WP itself.

**Comment by Lovrata** [comment]
Thank you for tip. :) I will use that next time.
