### ISSUE TITLE
Ajax endpoint url broken in 3.2.0-RC.1 if using subdirectory

### ISSUE THREAD

**Issue by electrokit** [woocommerce/woocommerce#16988]
Hi,

Commit 5721bc6044eed3f17b6b9e290efb6166b633b8fe breaks WC_AJAX->get_endpoint() if the wordpress install is not in the root directory.
Example
Wordpress install directory: http://example.com/wordpress/dir/
home_url(wp_unslash($_SERVER['REQUEST_URI'])) then returns
http://example.com/wordpress/dir/wordpress/dir/

This breaks all ajax requests that use WC_AJAX->get_endpoint()
Using mod_proxy may fix this, but I suppose that's not a requirement for running WC.
I guess the commit was made to get the absolute url, instead of the root-relative.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/16991
