### ISSUE TITLE
Ajax shipping costs not updating

### ISSUE THREAD

**Issue by Saschaeh** [woocommerce/woocommerce#16999]
Hi there,

I setup two shipping zones. 1: The global/Default zone and 2) City specific zone for which I have entered all the relevant zip/postcodes. 

**The problem:** 
As you enter the the address, specifically country field, it displays the global shipping costs and stays that way even after I put in the more accurate zip/postcodes. 

Only when I click on the actual shipping options do the prizes update specific to the postcode.  

This is of course not ideal especially when the the global/default shipping costs are significantly higher than the city specific shipping cost. 

**Id like to:**
Only show shipping costs once the zip/postcode is entered (prevent it from showing non relevant shipping cost). Id be happy to disable Ajax if that helps. 

I have played around with different themes so it is not that. Everything is up to date. Running RnB, Booster and Jetpack no other plugins. 

Thanks for you help,
Sascha

**Comment by claudiulodro** [comment]
I believe we've addressed this in #16763 (Original issue: #16757). Starting in WooCommerce 3.2, the shipping costs will recalculate as soon as the required address fields are filled out and keep recalculating when address fields are changed.

**Comment by Saschaeh** [comment]
Hi thanks - but the threads you refer me too are saying shipping are not showing at all. Whereas I am getting only international/default and only the local shipping when you try select one of the more expensive international options... It should update as you enter the postcode... in-fact i would prefer it only update/show once postcode is added as to not mislead the client.

**Comment by claudiulodro** [comment]
The latest version will show the country shipping rate when the country is selected, but as soon as the address is filled out it will automatically update to show the city/postcode rate. That should work for you, no?

**Comment by Saschaeh** [comment]
nope exactly the problem. this is not happening. 

I have to actually select the radio buttons and only then does it update. So its seems the Ajax is not working. I changed themes, different browsers.. still it only show default shipping costs until i select one of the shipping options, then seems to reference  postcode andit refreshes and i see the proper costs.

**Comment by claudiulodro** [comment]
Just tested it on WC 3.1 and the WC 3.2 RC and I haven't been able to reproduce the problem. The auto-price-updating work great as far as I can tell. 

After all the address fields are filled out you should be able to see ajax calls to `checkout/?wc-ajax=update_order_review` in the browser's network inspector when changing address fields. I would check and make sure those are getting sent out. If RnB adds new checkout fields it may be interfering with that. It's hard to tell without seeing the site. Do you have a live link I can take a look at?

**Comment by Saschaeh** [comment]
yhea i am on Version 3.1.2 
http://staging.instrumentrentalbarcelona.com/product/superior-electric-acoustic-guitar-for-rent/
Adress sample Spain Barcelona, postcode example: 080*
shipping should say: (BCN Metro) not (Outside BCN Metro)

Sorry bit of a nub but how do i check if it is calling ze ajax? 

Quite possible it is RnB - can chase them up on this.

Thank you so much!

**Comment by Saschaeh** [comment]
Sorry anyone manage to resolve this?

**Comment by claudiulodro** [comment]
Just tested it on your site. It works how it should. The shipping cost auto-updated as soon as I filled out all of the required fields (ones with a "*").

**Comment by noman-work** [comment]
I'm facing the same issue.
