### ISSUE TITLE
Woocommerce rest api authorization issue

### ISSUE THREAD

**Issue by ninexus-rajender** [woocommerce/woocommerce#16990]
I'm using woocommerce api to read/write customers and I've read/write  permission in the woocommerce api in the wordpress backend, the issue  I'm facing is when I do the retrive customer request as  below:

      ` <?php print_r($woocommerce->get('customers',['email','someemail@example.com'])); ?>`

then it return the proper result and then when I refresh again it  shows error and after 2 or 3 time refresh it again load up the data. The  error I'm getting is as mentioned below:
     `Array    (  
        [code] => woocommerce_rest_cannot_view 
         [message] => Sorry, you cannot list resources.          
        [data] => Array          (  
            [status] => 401 
         ) 
    ) `

 Even in my old server if I run the same request it works fine no  matters how many times I send the request, what would be the problem  that's causing woocommerce auth not working properly,   FYI, I've even installed the basic auth plugin, but in my old website  where it's working fine I'm not using any basic auth plugin and still  it's working fine.

**Comment by claudiulodro** [comment]
If it's working fine on your old server but not on your new one this is going to be an issue with your server. I think most likely something to do with the way your server is set up is not working well with the [timestamp or nonce checking](https://github.com/woocommerce/woocommerce/blob/419244051e893501ff8755a1a568aae7e7e49132/includes/api/class-wc-rest-authentication.php#L452).

**Comment by ninexus-rajender** [comment]
Thanks for your response, the issue was with the cloudflare, it was not bypassing the API requests that's why It's wasn't working, Now I've fixed it.
