### ISSUE TITLE
Won't let me export CSV

### ISSUE THREAD

**Issue by leeeouk** [woocommerce/woocommerce#16994]
Hi there,

I am having an issue exporting products. It worked a month ago, I tried again and it just stops at the Export products to a CSV file page.

Could do with any help.

**Comment by mikejolley** [comment]
There are not enough details in this issue to replicate or assist. This is working our side.

Please read the description on https://github.com/woocommerce/woocommerce/issues/new for things you should do prior to submitting bugs, how to rule out extensions, or use the support areas.

Thanks
