### ISSUE TITLE
[WC 3.2 RC] Meta data attribute in API order endpoints full of empty arrays

### ISSUE THREAD

**Issue by bryceadams** [woocommerce/woocommerce#17003]
👋 With the 3.2 RC 1, it looks like the `meta_data` attribute in an order object returned by the API is full of empty arrays.

```
       "meta_data" => [
         [],
         [],
         [],
       ],
```

Confirmed this on both the `/orders` index and a single order.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17017

**Comment by bryceadams** [comment]
![giphy-downsized-large](https://user-images.githubusercontent.com/1532482/31104464-d29139da-a828-11e7-93fd-b807e0f37848.gif)

**Comment by mikejolley** [comment]
This could be us @bryceadams

**Comment by bryceadams** [comment]
🙏 for it @mikejolley
