### ISSUE TITLE
Woo Layered Nav Widget Filter Bug

### ISSUE THREAD

**Issue by murrayac** [woocommerce/woocommerce#17002]
I've noticed when selecting an attribute from the Layered Nav Widget, if the product attribute has sold but still has other unsold attributes it still shows.

e.g
Scarlet Sky Strap Off Shoulder Ruffle Top has sold in size 10 but still displays on page.

https://sonlia.com.au/product-category/other-label-clothing/?filter_size=10

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/6574#issuecomment-59935855
https://github.com/woocommerce/woocommerce/issues/5840#issuecomment-50601474

tl;dr this would be too query intensive.
