### ISSUE TITLE
"Copy for support" button on System Status Report page doesn't work 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#17009]
**Copy for support** button on System Status Report page doesn't work. 

**STEPS TO REPRODUCE:**

1. Navigate to **WooCommerce > Status > System Status** page
2. Click on **Get system report** button:

![](https://cloudup.com/cvQrJAEy5oX+)
Image Link: https://cloudup.com/cvQrJAEy5oX

3. Then click on **Copy for support** button:

![](https://cloudup.com/c4-oWSuuQCJ+)
Image Link: https://cloudup.com/c4-oWSuuQCJ

4. Try to paste the text somewhere. You will see that the text hadn't been copied.

**Comment by pmgarman** [comment]
I tested this on WC `3.1.2` and `3.2.0-rc.1` and master (`7e9e58d75f7d8e0da9020165a0352afe090c0957`) and could not replicate this issue.

**Comment by pmgarman** [comment]
My guess is from the screenshot and the OMG ALL THE NOTICES and all the admin menu items there is likely a theme or plugin JS that is breaking the admin and it is a site specific issue not WC.

**Comment by juliaamosova** [comment]
@pmgarman thanks! I work in WooCommerce and this is my test site hence all the notices. Let me disable the plugins causing the notices and test again. Will report back.

**Comment by juliaamosova** [comment]
Tried testing on a "cleaner" site (not the same as above) and the issue still persists. Gif below:

![Testing Copy button Gif](https://cloudup.com/cB71iOVdkM6)

At the end of the gif I was able to copy paste system status report using keyboard shortcode. The button still didn't work for me. 

Console showed no JS errors:

![](https://cloudup.com/cxf8JqV9hpM+)
Image Link: https://cloudup.com/cxf8JqV9hpM

Could be still something on my end though since you can't reproduce it @pmgarman. I'll test more tomorrow when more folks who I work with are around to see if anyone else has any issues and if we can find patterns.

**Comment by pmgarman** [comment]
Deactivate *everything* and try - for WC bugs it should be tested with *nothing* but WC enabled. The issue template that shows up when you click new issue has the steps to be tested when opening an issue: [issue template](https://github.com/woocommerce/woocommerce/blob/master/.github/ISSUE_TEMPLATE.md). Then if it works with everything disabled re-enable things one at a time until the issue comes back, now you know where your conflict is.

**Comment by juliaamosova** [comment]
Tested this further with only WooCommerce being active and the issue still persists:

https://cloudup.com/cjyT6HyNkTC

I will test this later on when I get a chance to restart my computer and see if it helps.

**Comment by mikejolley** [comment]
3.2 uses a fixed clipboard script. 3.1 script requires flash.

**Comment by juliaamosova** [comment]
@mikejolley thanks! I'll leave it up to you to close the issue now or leave it open until 3.2 release. Also to modify the issue tags as well.

**Comment by dougaitken** [comment]
> 3.2 uses a fixed clipboard script. 3.1 script requires flash.

This is what I guessed when I spoke to Julia. 

Tested on 3.2, works 💯 

I see you've also caught it for the API keys, ta!
