### ISSUE TITLE
Webhook durations are inaccurate or poorly described

### ISSUE THREAD

**Issue by pmgarman** [woocommerce/woocommerce#17010]
Webhooks have a duration, I'm assuming this duration is the amount of time it takes to send the webhook (the http request), but it doesn't incorporate the amount of time spent gathering all the data to send the webhook.

Example: The customer updated webhook is showing me a duration of `0.21255` which does match up with the `~0.251` which New Relic shows for the cron request at about the same time. Yet if you look at the request it also spent `~3.7` seconds just to build the data for the webhook.

![](http://c.pmgr.mn/n2T6W4+)

**Comment by mikejolley** [comment]
The logged duration is the time it took to deliver the webhook via remote post to the external server. It does not include request times of your own server.

We could potentially log both.

Added to https://github.com/woocommerce/woocommerce/issues/12439
