### ISSUE TITLE
Notice: Undefined property: stdClass::$url - when logged out

### ISSUE THREAD

**Issue by Muazhesam** [woocommerce/woocommerce#17014]
I am facing an error when the user is logged out and WP_DEBUG is true.

Notice: Undefined property: stdClass::$url in .........../wp-content/plugins/woocommerce/includes/wc-page-functions.php on line 123

I tried using : 
if(!is_user_logged_in()){return}
but not works

**Comment by mikejolley** [comment]
Looks like some customisation of nav menu items. This filter is working on `wp_nav_menu_objects` - someone must have left `url` out.
