### ISSUE TITLE
Chrome auto-populating fields doesn't cause tax refresh

### ISSUE THREAD

**Issue by themightymo** [woocommerce/woocommerce#17020]
When Chrome browser auto-populates address fields, the tax does not refresh, and I am able to checkout without paying the required tax.

The solution is to manually type the zip code AGAIN (which would never happen for obvious reasons).

**Comment by mikejolley** [comment]
This has been logged in the past but has not been reproducible. Your report lacks steps to reproduce, system status, affected URL etc. Please provide more information or or will be closed.

Thanks

**Comment by mikejolley** [comment]
Let me know if you can provide more details/a site to test this. Or if you can reproduce on woo.com.
