### ISSUE TITLE
Disabling Single Product Zoom Feature will remove PhotoSwipe Modal Icon

### ISSUE THREAD

**Issue by romi-getbowtied** [woocommerce/woocommerce#17034]
I think this is a bug: when we disable the single product zoom feature (but not also the photoswipe modal feature), the photoswipe modal icon (magnifier) will disappear. 

https://www.screencast.com/t/2QvKyFqgPoo3

Since zoom and modal are independent features, we think the modal icon should stay.

Thanks.

**Comment by mikejolley** [comment]
When zoom is disabled, we no longer need a dedicated icon because the entire image can be clickable. Click the image itself.
