### ISSUE TITLE
My Account Dashboard Template: Move printed text to hook

### ISSUE THREAD

**Issue by ErikBernskiold** [woocommerce/woocommerce#17032]
## Prerequisites
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Issue
In `templates/myaccount/dashboard.php` there are two lines of text being printed before the hook, `woocommerce_account_dashboard`.

This reduces the possibilities of tweaking the dashboard template without having to duplicate the file. Additionally, since the two <p> tags have no class, they require specific `nth-child` or `nth-of-type` CSS selectors to target, which is not ideal.

There are plenty of reasons why one might one to either style them, or want to change the dashboard layout not including these paragraphs or links. Since we have a navigation too (which we can change to remove items), removing the links here should be possible too.

## Suggested Fix
I propose two changes:

1. Move the two paragraphs (preferably separately) to be hooked into  `woocommerce_account_dashboard` which fires after. This, making them accessible to developers.
2. Adding a class to each of the paragraphs, making them accessible for CSS without `nth-*` selectors.

**OR**
Filtering the text through `apply_filters` to make it changeable by the user. Or a combination of the three. I believe a proper solution here would solve the three potential needs:

1. Just wanting to style the text. (Theme)
2. Just wanting to change the text (User/Theme/Developer)
3. Wanting to customize the screen completely (Theme/Developer)

**Side note:** I would love to submit a pull request with this, for a suggested solution, but currently do not have the time. I therefore have to settle with reporting the issue and a suggested solution via text.

**Comment by reigelgallarde** [comment]
Interesting... But if I were to suggest a fix, this is how I would go with this.
I'd wrap it with an `if` statement like this.
````
do_action( 'woocommerce_dashboard_welcome_message', $current_user );
if ( !has_action( 'woocommerce_dashboard_welcome_message' ) ):
?>

<p><?php
	/* translators: 1: user display name 2: logout url */
	printf(
		__( 'Hello %1$s (not %1$s? <a href="%2$s">Log out</a>)', 'woocommerce' ),
		'<strong>' . esc_html( $current_user->display_name ) . '</strong>',
		esc_url( wc_logout_url( wc_get_page_permalink( 'myaccount' ) ) )
	);
?></p>

<p><?php
	printf(
		__( 'From your account dashboard you can view your <a href="%1$s">recent orders</a>, manage your <a href="%2$s">shipping and billing addresses</a> and <a href="%3$s">edit your password and account details</a>.', 'woocommerce' ),
		esc_url( wc_get_endpoint_url( 'orders' ) ),
		esc_url( wc_get_endpoint_url( 'edit-address' ) ),
		esc_url( wc_get_endpoint_url( 'edit-account' ) )
	);
?></p>
<?php endif; ?>


...... rest of the codes ....
````

this way, I can

**1.**  remove them completely with `add_action( 'woocommerce_dashboard_welcome_message', '__return_false' );`
**2.** Add my own welcome message.

````
	add_action( 'woocommerce_dashboard_welcome_message', 'my_dashboard_welcome_message' );
	
	function my_dashboard_welcome_message( $current_user ) {
		echo 'hello ' . $current_user->display_name;
	}

````

**Comment by claudiosanches** [comment]
We had some discussion about it and we create a new guideline for this kind of change:
https://github.com/woocommerce/woocommerce/wiki/Core-template-guidelines

Since it's a structural change you should replace the template into your theme.
Thanks for raise this issue.
