### ISSUE TITLE
Woocommerce Page Issue

### ISSUE THREAD

**Issue by mond044** [woocommerce/woocommerce#17031]
There's an unnecessary post/banner on my woocommerce page. What happened was I created an html banner and added it to my homepage but it also appeared in all the woocommerce page (shop, cart and checkout). I tried to removed the banner in my homepage but still showing on my woocommerce page. I also tried to uninstalled and reinstalled the woocommerce plugin but still same issue. Can some help me on this.. Thank you in advance!! Please see attached file for the screenshot.
![shop](https://user-images.githubusercontent.com/32475550/31111018-06047122-a81c-11e7-8232-c61884581328.png)

**Comment by mond044** [comment]
Please disregard, this issue has been solved. Thanks!

**Comment by dougaitken** [comment]
> Please disregard, this issue has been solved. Thanks!

closing.
