### ISSUE TITLE
Site title can easily become out of sync with emails

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#17039]
There are two email settings that use the site title. The subject name and email footer. If you change your site title later, these settings easily come out of sync. This is especially annoying if they are literally left as `Site title`. 

Per [this comment](https://github.com/woocommerce/wc-api-dev/pull/32#issuecomment-317852090), a potential solution is having a replacable string:

> I think a more ideal fix for core would be for the inclusion of the site title to be something that happens as a replacement in the user defined string so that it stays in sync unless the user removes the replacement marker.

**Comment by claudiulodro** [comment]
This seems like more of an enhancement with 2 parts than a bug. 
- Add support for the `{site_title}` syntax used in the email Subject settings field to the email Footer Text and "From" Name settings fields.
- Make `{site_title}` the default From setting and `{site_title} - Powered by WooCommerce` the default email Footer setting.
