### ISSUE TITLE
Invalid argument supplied for foreach() in wc-template-functions.php on line 2274

### ISSUE THREAD

**Issue by ahmed-sigmalux** [woocommerce/woocommerce#17044]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install PHP 7.1.10, WordPress 4.8.2, WooCommerce 3.1.2, and Storefront 2.2.5
2. Enable debug logging
3. Check debug.log

## Expected/actual behavior

Debug log shows the following entry repeatedly:

`PHP Warning:  Invalid argument supplied for foreach() in /var/www/mysite.com/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 2274`

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

# WordPress Environment

<details>

### WordPress Environment ###

Home URL: https://mysite.com
Site URL: https://mysite.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: 
PHP Version: 7.1.10-1+0~20170929170818.9+stretch~1.gbp501135
PHP Post Max Size: 10 MB
PHP Time Limit: 120
PHP Max Input Vars: 4096
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 6: Could not resolve host: www.paypal.com
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. cURL error 6: Could not resolve host: woocommerce.com

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

AMP: by Automattic – 0.5.1
Glue for Yoast SEO & AMP: by Joost de Valk – 0.4.2
MultilingualPress: by Inpsyde GmbH – 2.9.1
Redis Object Cache: by Till Krüss – 1.3.5
SendGrid: by SendGrid – 1.11.7
WooCommerce: by Automattic – 3.1.2
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.4
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3
Yoast SEO: by Team Yoast – 5.5.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: My Theme
Version: 2.2.5
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by claudiulodro** [comment]
Do you have the full stack trace from that debug message? Without that information or other further information this is impossible to debug. The global `$wp` doesn't appear to have any query vars ([ref](https://github.com/woocommerce/woocommerce/blob/release/3.1/includes/wc-template-functions.php#L2274)), but without more information it's impossible to tell what's causing that.

I see that you checked the boxes for "This bug happens with only WooCommerce plugin active" and "This bug happens with a default WordPress theme active, or Storefront", but I see other plugins active in the status report and you are using some sort of custom child theme. Just checking again, but you have this problem with only the WooCommerce plugin active and only a standard theme?

**Comment by mikejolley** [comment]
`foreach ( $wp->query_vars as $key => $value ) {`

Some plugin must be unsetting these.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17060

**Comment by dchenk** [comment]
I'm getting the same error.
