### ISSUE TITLE
WooCommerce Category Page Title

### ISSUE THREAD

**Issue by kitchen4ever** [woocommerce/woocommerce#17040]
Hi, everybody, I’got a bag of WooCommerce title page: somehow the loop goes through all the titles of the category products and puts them as the page title:
http://kitchen4ever.com/product-category/kitchens/
I know that the theme is not WC friendly and the loop had been integrated into it.
Maybe any body would be so kind to suggest any fix for this issue? 

![default](https://user-images.githubusercontent.com/32495850/31145384-4b029db0-a88c-11e7-9765-95b8cd65d674.png)

Thanks in advance.

**Comment by claudiulodro** [comment]
Sorry, the GitHub issues area is only for bugs in the core WooCommerce plugin. This is an issue with your theme. I recommend posting in [the support forum](https://wordpress.org/support/plugin/woocommerce) if you need advice on how best to develop your theme. We also have some [documentation](https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/) that may help.

**Comment by kitchen4ever** [comment]
Thank you for help. I'll post in support
