### ISSUE TITLE
Bug - You can pick different shipping class for a product variation with a defined shipping class

### ISSUE THREAD

**Issue by werta600** [woocommerce/woocommerce#17051]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [X] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product with at least 2 product variations.
2. Select a different shipping class for those variations (with different prices so you get to see the difference).
3. When you add to the cart that product with variation, you can pick a shipping class different to the one set on that variation.

## Expected/actual behavior

When I follow those steps, I see i can pick different shipping class for that variation.

I was expecting to see only the shipping class set for that variation to appear, or if the others appeared, they should be greyed out or something.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

The store is using Woocommerce 3.0.7 and wordpress 4.7

**Comment by mikejolley** [comment]
I think you're expecting shipping classes to do something they don't do. Shipping classes are for grouping - some shipping methods use them, others do not. There is no direct link between a shipping class and a shipping method. Shipping classes do not limit what shipping methods are shown or offered.

**Comment by werta600** [comment]
@mikejolley so i cannot set a particular shipping for a variation? customers can cheat out the shipping on a variation set for "local pick" because in the cart you can change the shipping regardless the variation and class you set on admin

**Comment by mikejolley** [comment]
If local pickup is enabled, they can choose it. You don't need to have it enabled.
