### ISSUE TITLE
custom_add_to_cart_redirect filter not working

### ISSUE THREAD

**Issue by mesa-sane** [woocommerce/woocommerce#17050]
Hi,
I had used 'custom_add_to_cart_redirect' filter previously for redirecting purposes But after update Woocoomerce to the latest version. it doesn't work anymore.

P.S: I don't want 'the cart redirect' option that is located in Settings->products->display because I want to redirect to a custom page.

any help, please.

**Comment by kloon** [comment]
Filter is woocommerce_add_to_cart_redirect and still working fine.
