### ISSUE TITLE
Payment gateway: `init_form_fields` called on checkout page

### ISSUE THREAD

**Issue by Roemerb** [woocommerce/woocommerce#17056]
First of all, I tried to initially contact support about this, but I don't have access to my companies WooCommerce account which is a paying customer, therefore I could not contact support. This might actually be a bug though.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

My payment gateway plugin needs to call our API to fetch the `account` and `organisation` under which payments should be processed. This is a feature of our PSP that allows our customers to separate different revenue streams.

1. This problem occurs in my payment gateway plugin. See the `spryngpayments/woocommerce` repo
2. When I enter the payment page, I notice that the `?wc-ajax=update_order_review` call takes quite long, making the checkout page less responsive. To reproduce this issue, one would just have to enter the payment page.

Using `debug_backtrace` I traced back the issue to `apply_filters` in `WC_Hook`. This function somehow calls the `init_form_fields` function from my payment gateway whenever `update_order_review` is called. I checked if this was just because I was using an admin account and `process_admin_options` was called, but this is not the case as I tested with a regular account.

## Expected/actual behavior

When I enter the checkout page, I expect that only the `__construct`, `is_available` and `payment_fields` methods run.

When I follow those steps, I see...

That the `init_form_fields` also runs.

I was expecting to see...

That this method does not run.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
### WordPress Environment ###

Home URL: http://wp.app
Site URL: http://wp.app
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: nginx/1.13.3
PHP Version: 7.1.9-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

AfterShip - WooCommerce Tracking: by AfterShip – 1.7.1
Spryng Payments WooCommerce: by Roemer Bakker
Complexity – 1.5.9

WooCommerce Subscriptions: by Prospress Inc. – 2.2.8 – 2.2.12 is available
WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
</details>

**Comment by mikejolley** [comment]
`update_order_review` I believe updates displayed Payment methods.

Payment methods use a settings API.

The settings API calls `init_form_fields` to know whats settings it owns, and uses these to load the settings from the DB.

So yes; whenever gateways are loaded/called/displayed, `init_form_fields` will run as part of that. Remove heavy logic from `init_form_fields` or cache whatever you're doing. `init_form_fields` should be for admin settings only.

Thanks

**Comment by claudiosanches** [comment]
> When I enter the checkout page, I expect that only the `__construct`, `is_available` and `payment_fields` methods run.

Well, but you have the `init_form_fields()` inside the `__construct()`:

https://github.com/spryngpayments/woocommerce/blob/4a6f8784d0d3442c1e6a5b1324a94f6db0bcbae5/gateways/abstract.php#L21-L50

So each time that your payment gateway is loaded will try fetch data from the REST API again.
And this not happens only in the checkout, will happens in the admin too.

Note that this is not an issue or something related to WooCommerce, this is something that you are doing into your own plugin.

So my tip is to you try remove it or if it's really necessary, so you should save the REST API results with transients: https://codex.wordpress.org/Transients_API

**Comment by Roemerb** [comment]
@mikejolley @claudiosanches Hey guys, thanks for the reply. I guess what Mike says sounds logical, but I have to ask: Why doesn't it just call `init_settings`? That's what actually loads the settings for the database right? `init_form_fields` just defines what the inputs should look like.

And Claudio, I don't have my `init_form_fields` inside my `__construct` anymore, I tried to avoid it being called by the checkout page. Instead I use the `woocommerce_settings_api_form_fields_{gateway_id}` filter, which works great. Sorry, this is not pushed to the repo yet. 

Thanks for your recommendation of the Transients API, that could be really useful. I think I might try to load the API data with AJAX. That might be easier than dealing with caches.

Sorry if I might have wasted you guys' time by opening this issue. That was not my intension.

**Comment by claudiosanches** [comment]
@Roemerb

> Why doesn't it just call init_settings? That's what actually loads the settings for the database right? init_form_fields just defines what the inputs should look like.

This will load `$this->form_fields`, what is used in some places, most of the time only in admin.
Still fetching something from an API every time that the calls `$this->form_fields` is not good.
That's why should be avoided or moved into transients to prevent multiple requests.
Even using the `woocommerce_settings_api_form_fields_{gateway_id}` filter should make requests.
You could also use our WooSelect input to make ajax requests, so we don't need to load all results at once, only when the user is searching for a new organization or account.
