### ISSUE TITLE
Consider removing "Powered by WooCommerce" in email template

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#17053]
This credit message doesn't benefit the recipient whether it's the store owner or a customer. It probably doesn't benefit us much either (not sure if we're tracking). It feels a bit smalltime to include it at this point xD

What say y'all?

Related: https://github.com/Automattic/wp-calypso/issues/15040#issuecomment-333630448

**Comment by mikejolley** [comment]
Kill it with fire 👍
