### ISSUE TITLE
Problem with  woocommerce_available_payment_gateways hook

### ISSUE THREAD

**Issue by MarieComet** [woocommerce/woocommerce#17062]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Hook on woocommerce_available_payment_gateways a simple action that trigger the checkout page refresh
2. Make a change on the cart that trigger that change

## Expected/actual behavior

Hello,
I'm using `woocommerce_available_payment_gateways` hook to enable COD gateway only when user use coupon code in the checkout page.
I've wrote a simple condition for that but it can be reproduced for example on a product quantity which inscrease from 1 to 2.
It's working well, the COD gateway showing at the right moment, but I have a problem with the COD gateway checkbox : in the source code (inspector) the checkbox is checked but in the CSS (what I really see at front office) it's the checkbox of the previous payement gateway which was selected, because a CSS rule on the input:checked state.
I don't understand why it's happening because the page reload, so thé CSS will do the same and target the right input (COD)
I don't think it's a session problem, maybe JavaScript Sync.

I would appreciate any advice or help.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiosanches** [comment]
> I'm using woocommerce_available_payment_gateways hook to enable COD gateway only when user use coupon code in the checkout page.
> I've wrote a simple condition for that but it can be reproduced for example on a product quantity which inscrease from 1 to 2.

Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
