### ISSUE TITLE
price does not sync when regular_price or sale_price updated with api

### ISSUE THREAD

**Issue by wgillin** [woocommerce/woocommerce#17068]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [x ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Call PUT wp-json/wc/v2/products/<id>?consumer_key=xxxx&consumer_secret=xxxx
{"sale_price":"5.95"}
2. Call GET  wp-json/wc/v2/products/<id>?consumer_key=xxxx&consumer_secret=xxxx
3. JSON returned 
"price":"10.95","regular_price":"39.95","sale_price":"5.95"

## Expected/actual behavior

When I follow those steps, I see...
"price" value reflects the previous sale price value - last price set when manually editing the product in wordpress.

I was expecting to see...
"price" should equal "sale_price" of 5.95

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://dev.jackalsgym.com
Site URL: https://dev.jackalsgym.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_304nnq2192_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (9) ###

Contact Form 7: by Takayuki Miyoshi – 4.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
Search Engine Visibility: by GoDaddy – 0.5
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.15.2
WooCommerce Wholesale Prices: by Rymera Web Co – 1.5.2
WooCommerce: by Automattic – 3.1.2
WooSidebars: by WooThemes – 1.4.3
WP101 Video Tutorials: by WP101Plugin.com – 0.3
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #73 - /cart/
Checkout: #72 - /checkout/
My account: #71 - /my-account/

### Theme ###

Name: Flatsome
Version: 3.3.5
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0
flatsome/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.1.0
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php version 3.0.2 is out of date. The core version is 3.1.0
flatsome/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date. The core version is 3.1.0
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
```
</details>

**Comment by mikejolley** [comment]
You have plugins active related to prices; I think these may be affecting it.

In testing, there was no issue as seen here:

<img width="1062" alt="2017-10-05 at 12 56" src="https://user-images.githubusercontent.com/90977/31226068-b82fac8e-a9cc-11e7-8a34-8e6bccbe5606.png">

Let me know if ^ looks wrong.

**Comment by wgillin** [comment]
With all plugins deactivated this is still an issue.

Results and system report follows:
wp-json/wc/v2/products/1136?consumer_key=XXXX&consumer_secret=XXXX

"id":1136,"price":"9.95","regular_price":"39.95","sale_price":"4.95"
`
===============================================
### WordPress Environment ###

Home URL: https://dev.jackalsgym.com
Site URL: https://dev.jackalsgym.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_304nnq2192_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #73 - /cart/
Checkout: #72 - /checkout/
My account: #71 - /my-account/

### Theme ###

Name: Flatsome
Version: 3.3.5
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0
flatsome/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.1.0
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php version 3.0.2 is out of date. The core version is 3.1.0
flatsome/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date. The core version is 3.1.0
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`

**Comment by wgillin** [comment]
This happens with all plugins deactivated as well.  Full report added as a comment to the closed ticket. Please reopen.

 

"id":1136,"price":"9.95","regular_price":"39.95","sale_price":"4.95"

**Comment by mikejolley** [comment]
I'm not reopening this because as I demonstrated, it works. What are you making the requests with? Are you certain the JSON is actually sending to the server?

**Comment by wgillin** [comment]
Yes absolutely.  I’m able to change all other values.  Obviously I can change regular_price and sale_price.  Price is RO so can’t be directly changed but is computed from some trigger.  When I manually change the value in wordpress GUI the price value is updated immediately.  The issue is REST calls to update regular_price and/or sale_price do not set the trigger to update price.  There is an issue here that should be addressed.  It’s been demonstrated with no plugins active.  The output I sent is clear – price is > sale_price and <> regular_price, that itself is a logic error!

 

Regards,

 

Wade

**Comment by mikejolley** [comment]
Well you also checked:

> The issue still exists against the latest master branch of WooCommerce on Github (this is not the same version as on WordPress.org!)

Did you really do this? I'm running master/3.2.

**Comment by wgillin** [comment]
WC 3.1.2 in WP 4.8.2

**Comment by mikejolley** [comment]
Does not appear to be happening on `release/3.1` branch either. Show us the full request + response.

Do you think you can reply on github also so we don't have to read the entire email thread in your replies? Thanks.
