### ISSUE TITLE
Error using hook "woocommerce_before_calculate_totals" and endless checkout

### ISSUE THREAD

**Issue by werta600** [woocommerce/woocommerce#17073]
So, title, if i use `add_filter("woocommerce_before_calculate_totals", "my_func");`

Checkout will be endless loading, even if i only insert in the function a simple "var_dump" or "echo"... I have no idea why this happens... I was trying to modify the price of some products, worked nice on the cart, but checkout will get the endless loading.

EDIT: Website is using woocommerce 3.0.7 and wordpress 4.7

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create the filter "woocommerce_before_calculate_totals" in the theme functions
2. Try to buy something
3. Checkout will have endless spinning animation with no errors in console

## Expected/actual behavior

When I follow those steps, I see the endless checkout animation

I was expecting to see the proper checkout update

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
Because if you dump content, you invalidate the JSON response. This is a bug, with your code :)

I suspect the code you have on your callback is throwing notices or warnings which also invalidates JSON. View the console in your browser and look at the responses. https://mikejolley.com/2015/11/12/debugging-unexpected-token-in-woocommerce-2-4/

Thanks
