### ISSUE TITLE
Stripe pupop bug

### ISSUE THREAD

**Issue by alnux** [woocommerce/woocommerce#17072]
hi,

with the stripe popup option on frontend checkout option when new customer put his information on "Billing details" form the popup Stripe does not work if customer put his email, if it is erease the forms works but as you know it calls for email.
 
regards

**Comment by mikejolley** [comment]
Stripe issues should be logged on https://github.com/woocommerce/woocommerce-gateway-stripe/issues **Please include your system status report.**

Thanks
