### ISSUE TITLE
Not able to delete a product when creating a manual order on an iPad

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#17079]
Not able to delete a product when creating a manual order on an iPad. Once product had been added it can't be deleted.

**TESTING ENVIRONMENT:**

- iPad Pro 12.9-inch display
- iOS - 11.0.1
- WooCommerce - 3.1.2

**STEPS TO REPRODUCE:**

I made a recording of the steps I took with an explanation:

https://cloudup.com/cnvJg9jDW4u

Confirmed this behavior on 3 different test sites. 

The 1st part of the video is related to another issue - https://github.com/woocommerce/woocommerce/issues/17078

The issue had been originally submitted by the user - 717559-zen.

**Comment by mikejolley** [comment]
Tested and working on 3.2. Was broken on 3.1 so I assume it was fixed :)
