### ISSUE TITLE
Product Importer matches incorrect image

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#17088]
When importing images (generally during a merge) it is possible to use image names without the full path. In this case it will check to see if the image already exists in the Media Library. It uses a query for this which isn't very specific, see: https://github.com/woocommerce/woocommerce/blob/3.1.2/includes/import/abstract-wc-product-importer.php#L515-L521

If we have one image which was stored with the name `image-a.jpg` and a second one called `a.jpg`. When we want to use `a.jpg` as an image. It will match both results and the first one will be used. If `image-a.jpg` happens to have been created earlier in the database then it will be matching this as the first one. This can cause problems when users use short names for their images. Can also happen for files like `22.jpg` and `2.jpg`

When a media file is saved with the option `Organize my uploads into month- and year-based folders` enabled the meta key `_wp_attached_file` is saved as:

`2017/06/image-a.jpg`

Without it enabled it is stored as:

`image-a.jpg`

So we could rewrite the meta query to either equal the value or to have a / as a prefix. Something like this:

```
'meta_query'  => array(
	'relation' => 'OR',
	array(
		'value'   => $file,
		'key'     => '_wp_attached_file',
	),
	array(
		'value'   => '/' . $file,
		'compare' => 'LIKE',
		'key'     => '_wp_attached_file',
	),
),
```

Would probably be better if the LIKE could match only the end of the string. But I don't see any way to do that with meta_query unless you create the query manually.

Does this cover all the use cases? Or am I missing something?

If rewriting the query is not an option. Then maybe looping through all the results and finding the best match using a regular expression might work as well. Instead of just using `$id = current( $ids );`

**Comment by mikejolley** [comment]
Need to verify filename upload works in 3.2.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/17164
