### ISSUE TITLE
Review custom database table indexes

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#17084]
Ensure indexes are useful, and used in our queries throughout the codebase.

**Comment by surferking** [comment]
An example of Woocommerce with 800,000 products searched & filtered in ~0.5s on a $40 Digital Ocean droplet for inspiration ;)

https://foundthru.com/

**Comment by mikejolley** [comment]
I don't see a need to track this in an issue; it's ongoing/part of woo.com work :)
