### ISSUE TITLE
[3.2.0 RC 2] Select2 of layered filter are not "clearable" anymore

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#17085]
When using a layered filter for an attribute to narrow down the search, users had the possibility to reset the filter in 3.1 if they wanted to broaden the search again, for example  ('beliebige Hersteller' == 'any supplier' ). The screenshot is for a simple filter in "AND" mode. After the selection we got in 3.1:
![elos_1](https://user-images.githubusercontent.com/25102786/31272242-92024422-aa8a-11e7-8ed2-5782cc53bfae.jpeg)
In 3.2.0 however, the use of select2 on the same select doesn't give us either the possibility to clear the select or to select the empty entry in order to broaden/reset the filter again. So we are stuck in the level of filter we are, without possibility to come back:
![elos_2](https://user-images.githubusercontent.com/25102786/31272302-c5488b02-aa8a-11e7-9836-6d225b4f9adb.jpeg)
I can see in the html markup of the page select the empty option, but select2 doesn't give me the possibility to select it, neither can I clear my selection.

**Comment by mikejolley** [comment]
FWIW there is a layered nav filters widget to clear any value.

**Comment by pierrebuet** [comment]
@mikejolley Thanks for the hint, and I agree with you when using one filter. However this is not really a user-friendly substitute for the old behaviour, if I have more than one filter two narrow down search on technical product, for example.

**Comment by pierrebuet** [comment]
@claudiulodro Claudio, I'm not sure if I should open a new issue or comment on this one. So please apologize if I did something wrong. Your patch for the allow clear works well, but a small issue remains with the localization of the select2 strings used by select2. 
![localization](https://user-images.githubusercontent.com/25102786/31333437-6622232e-acea-11e7-8376-bc554c0c44a4.jpeg)
 For other select2 selects like wc-country-select, the error string gets overridden with "i18n_no_matches" which I can in turn localize. In the actual layered nav widget, the noResults function of selectWoo is not overridden meaning I can't translate it

**Comment by claudiulodro** [comment]
@pierrebuet good catch. #17109 should fix this.

In the future one issue for each problem is best, but all good this time. 👍
