### ISSUE TITLE
Research: how do extensions use the `author` field for orders?

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#17087]
Let's see how `author` is used in plugins e.g. vendor plugins. If not used, we could potentially use this for the customer_id which will speed up queries. Core only sets ID 1 for author right now.

Nothing should be changed unless certain this won't affect extensions.

**Comment by digitalchild** [comment]
In WC Vendors I only use the post_author fields for products and coupons. Orders can have multiple vendors so we do not store the vendor id in the post_author for orders. I create sub orders (separate post type) and set the post_author there.

**Comment by mikejolley** [comment]
@digitalchild Do those extend our system in any way? If we used post author for the customer in orders, would it affect you?

**Comment by digitalchild** [comment]
@mikejolley no this won't affect us. So long as products, coupons post_author stays untouched it will have no impact on my plugin. If anything it might make things a bit easier for display.

**Comment by mikejolley** [comment]
Closing this in favour of https://github.com/woocommerce/woocommerce/pull/17895 which could be 3.3/3.4 based on scope.

**Comment by lkraav** [comment]
@mikejolley was it ever determined how core came to the `_customer_user` meta decision in the first place? Why not `post_author` from the start; what were the fears back then that apparently never ended up materializing?

**Comment by mikejolley** [comment]
Likely concerns over how ID 0 for post author would work.
