### ISSUE TITLE
"orders_count" value from customer request has wrong value

### ISSUE THREAD

**Issue by freebeans** [woocommerce/woocommerce#17081]
_Using:
Woocommerce 3.1.1
Wordpress 4.8.2_

We're having problems with the **orders_count** field.
On a daily basis, we request all open orders from both our ERP system and our Woocommerce store.
We do highly customized work on our customers items, and we use the **orders_count** field from the response of the customer request for that matter.

I've noticed that sometimes, responses both from the **customer** request and the **order** request return **orders_count = 0**!

I haven't found any errors on the request's responses and re-doing the requests after some time yields the correct values.

As a provisional solution, can I re-do the requests until I get a non-zero value?
Can a plugin be causing this temporary wrong value?

**Comment by kloon** [comment]
I am going to need some more information regarding this. Could you please update your issue with the information requested via the template when you initially logged this?

I have no idea what you are doing to get the orders_count value, is it an API request, if so what endpoint are you hitting, is this done via a plugin. I would suggest you try testing this with just WooCommerce and the default theme enabled to see if this makes any difference, this is all requested via the initial template when you log an issue.

**Comment by mikejolley** [comment]
We'd need examples of the requests. orders_count is cached; and if 0, recalculated on the fly. Code looks ok in this instance - I'd rule out conflicts before logging here.

You can see the query in the customer data store, `get_order_count` method.

Thanks

**Comment by freebeans** [comment]
Sorry for the delay.

I was using a Node.js library which defaults to the legacy v3 API.
After I changed the API version in use, it all went well.

I'm very sorry, thank you for your time.
