### ISSUE TITLE
[3.2.0 RC 2] is_checkout() returns false during AJAX requests

### ISSUE THREAD

**Issue by ChaseWiseman** [woocommerce/woocommerce#17094]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

It seems that `is_checkout()` can no longer be relied upon during AJAX requests as of 3.2 RC 2. It will be accurate during initial page load, but if something is refreshed via AJAX then any calls to `is_checkout()` within the AJAX request will be false.

## Steps to reproduce the issue

1. Hook into `woocommerce_calculate_totals` or any action that runs during Checkout AJAX refresh
2. Log the result of `is_checkout()` in `master` vs. v3.1.2

## Expected/actual behavior

It's easy enough (and probably better practice) to check the `WOOCOMMERCE_CHECKOUT` constant instead, but there's still a backwards compatibility issue here.

It seems that the issue stems from this change: https://github.com/woocommerce/woocommerce/commit/fbe6db5c02077a548eb1a386076d59261017145f

Previously that would return `https://example.com/checkout/?wc-ajax=%%endpoint%%` but now returns `https://example.com/?wc-ajax=%%endpoint%%`. Presumably the same issue would apply to the other conditional functions that check `is_page()` but I only tested `is_checkout()`.

`is_cart()` isn't affected because that function directly checks `WOOCOMMERCE_CART`, so maybe the quick solution would be to do the same for `is_checkout()`? I'm not sure of the best approach.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
@ChaseWiseman Are you relying on this? The inline documentation says:

> is_checkout - Returns true when viewing the checkout page.

Ajax requests do not meet this criteria, so I think it being true is really just a fluke, and forcing this true using constants may be hacky.

**Comment by mikejolley** [comment]
Also to note, `?wc-ajax=` works on any URL.

**Comment by mikejolley** [comment]
@claudiosanches thoughts?

**Comment by ChaseWiseman** [comment]
@mikejolley nope it's nothing I'm relying on, as checking `WOOCOMMERCE_CHECKOUT` directly in custom code seemed to be the better option. As you noted, that it worked previously is likely a fluke but I wanted to report it anyway since I noticed the change in behavior.

**Comment by claudiosanches** [comment]
I don't see that it was our intention to make conditional functions work during AJAX calls.
This is one of the reasons that I prefer have a dedicated endpoint for it, but we changed it allowing requests in any page...
