### ISSUE TITLE
Auto change status using API

### ISSUE THREAD

**Issue by ebisbe** [woocommerce/woocommerce#17090]
I'm currently using v3.1.2 and I have an issue when sending a new order with status 'on-hold'.  It changes automatically to 'pending' but it should wait. I use it for bank transfer sells that need to be reviewed in the bank to actually see the money.
What I'm doing wrong?

**Comment by mikejolley** [comment]
"pending" is unpaid. "processing" comes after on-hold.

And what does this have to do with the API?

**Comment by ebisbe** [comment]
Reading the docs was not clear how to use the status. It's clear now.
