### ISSUE TITLE
REST API -Base64 encoded image upload support

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#17100]
The REST API currently only supports uploading of images by reference to an external URL via the `src` attribute or the `id` attribute for existing images:

http://woocommerce.github.io/woocommerce-rest-api-docs/#product-images-properties

Would love to see it also support image uploads via Base64 encoded text where you have large numbers of images stored locally that you would like to upload to WooCommerce via the REST API.

**Comment by mikejolley** [comment]
Upload an image using the WP Rest API media endpoint, then use the media you uploaded in our API.

https://www.wpsaga.info/wp-rest-api-upload-image-media/
