### ISSUE TITLE
Searching for customers first + last names requires space to be encoded as %20

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#17104]
Searching customers for first and last name has encoding issues with spaces.

For example:

Searching *Andrew* works
![image](https://user-images.githubusercontent.com/1001935/31339372-fbf67220-ad02-11e7-9fc5-c24ee4465066.png)

Searching *Andrew Smith* fails
![image](https://user-images.githubusercontent.com/1001935/31339404-0a6a0a6a-ad03-11e7-91a5-7837e17c9c61.png)

Searching *Andrew%20Smith* works
![image](https://user-images.githubusercontent.com/1001935/31339417-161701c4-ad03-11e7-9fbd-e560b85dcc1e.png)

## WordPress Environment

<details>
```
Woocommerce 3.1.2
```
</details>

**Comment by mikejolley** [comment]
Well, since there is no full name field, this cannot work anyway. %20 is stripped, so your search term is andrewsmith, which matches the username probably.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17110
