### ISSUE TITLE
Duplicate pictures in WooCommerce

### ISSUE THREAD

**Issue by CarlosYalfa** [woocommerce/woocommerce#17118]
Hello I have a problem with the export / import (1) default of woocomerce. When I upload datas, it is making double all the pictures in the product.

When I set the url off the products (correct url) (1) and I upload the table later (3) with the correct url (4), in the product view (5) it is a picture which is exactly the same picture I already upload, but with a "-1" at the end.

I am worried about it because it could affect my SEO, my space and my gallery (6).

![1](https://user-images.githubusercontent.com/32664975/31373419-476e89a8-ad9a-11e7-919e-4df9929a8f0c.png)
![2](https://user-images.githubusercontent.com/32664975/31373420-478713ec-ad9a-11e7-9b1e-abd0f1a60ef1.png)
![3](https://user-images.githubusercontent.com/32664975/31373421-479f1230-ad9a-11e7-86b7-49b522b57aea.png)
![4](https://user-images.githubusercontent.com/32664975/31373422-47b9312e-ad9a-11e7-9f79-7db9e0c0d752.png)
![5](https://user-images.githubusercontent.com/32664975/31373423-47d317ba-ad9a-11e7-8445-909d2a0ad90d.png)
![6](https://user-images.githubusercontent.com/32664975/31373424-47eb7530-ad9a-11e7-8375-0395abd2a244.png)

How could I fix it?

## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Make some products with woocommerce (at least 2 of them with the same picture
2. Use the default export-import csv tool
3. Try to import and your pictures will be duplicate

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
I don't think image filenames would have any affect on seo - you can set title, caption, description from the media library. 

If you provide just the filename of an image in your media library, it will link instead of uploading a copy. It will upload a copy if it cannot detect the existing image in your gallery by URL/filename.

If you're merging data remember you can leave the image column out if you're leaving it as-is.

Some logic around this has also been fixed in 3.2 which is due for release this week. Please test that version once updated.

Thanks!

**Comment by CarlosYalfa** [comment]
Mike, it is affect to the url, because it duplicate the file and also change the name of the file.

It makes duplicities of every picture in the products and several times.

As you can see I set the proper link in the csv, you can see also in the screenshots I uploaded ehre for first time.

And I do not wanna leave the image column if in fact I want to change a lot of images of a lot of products.

I am working with the last version of WooCommerce
![1](https://user-images.githubusercontent.com/32664975/31430620-b641316e-ae71-11e7-8d77-0c5433679466.jpg)
![2](https://user-images.githubusercontent.com/32664975/31430622-b65e9c7c-ae71-11e7-87ad-8dfeda689c42.jpg)
![3](https://user-images.githubusercontent.com/32664975/31430623-b6d7bb5c-ae71-11e7-99b5-2ec2a40c9b09.jpg)
![4](https://user-images.githubusercontent.com/32664975/31430624-b70e6954-ae71-11e7-9573-12d7e1ebc851.jpg)

**Comment by mikejolley** [comment]
After the first import, WC records the filename to prevent it adding the image again in future uploads. But as I said, these routines have been updated in 3.2 which is out later this week. I'm not talking about 3.1.2.

**Comment by claudiosanches** [comment]
Ohhh, there is no sub directories inside `uploads`? This can generate problems for your server indexing all the images in just one directory.
