### ISSUE TITLE
Customer Address Template Error

### ISSUE THREAD

**Issue by bencong** [woocommerce/woocommerce#17115]
I'm trying to customize WooCommerce template to match my site's design but I'm getting error on "My Account > Addresses". I copy "/woocommerce/templates/myaccount/my-address.php" to my theme's "/themename/woocommerce/myaccount/my-address.php" and it throw this error:

Fatal error: Uncaught Error: Call to undefined function wc_get_account_formatted_address() in ....

Same issue when I'm using TwentySeventeen theme and copy the "my-address.php" to the theme folder.

## Steps to reproduce the issue
Copy "/woocommerce/templates/myaccount/my-address.php" to my theme's "/themename/woocommerce/myaccount/my-address.php"

## WordPress Environment
WordPress 4.8.2 with multisite enabled, running on Ubuntu 16.04

**Comment by mikejolley** [comment]
Maybe you have an old version of WC active before the function existed?

Tested with your instructions; no error. The function is valid.
