### ISSUE TITLE
When billing_country field is unset, checkout cannot be fullfilled

### ISSUE THREAD

**Issue by avagp** [woocommerce/woocommerce#17116]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to functions.php of storefront theme
2. Write the following on the bottom (as the [documentation](https://docs.woocommerce.com/document/tutorial-customising-checkout-fields-using-actions-and-filters/) says):
```
add_filter( 'woocommerce_checkout_fields' , 'custom_override_checkout_fields' );
function custom_override_checkout_fields( $fields ) {
	 unset($fields['billing']['billing_country']);
     return $fields;
}
```
3. Go to the checkout, and the country field should not be there.
4. Fill all the mandatory fields and clic on place order button  

## Expected/actual behavior

Place an order.

## What actually happends

The order cannot be placed, because it says i need to write an address in order to continue.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://juegamalaleche.cl
Site URL: http://juegamalaleche.cl
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 16 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: 5.6.36
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wpqj_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (13) ###

Akismet Anti-Spam: por Automattic – 4.0
Beaver Builder Plugin (Lite Version): por The Beaver Builder Team – 1.10.8.3
Comunas de Chile para WooCommerce: por Anyda SRL  – 0.1
Google Tag Manager para Wordpress: por Thomas Geiger – 1.7.1
Enhanced E-commerce for Woocommerce store: por Tatvic – 1.1.2
Loco Translate: por Tim Whitlock – 2.0.16
Ninja Forms: por Los WP Ninjas – 3.2.1
PixelYourSite: por PixelYourSite – 5.0.8
Simple History: por Pär Thernström – 2.18
Simple IP Ban: por Sandor Kovacs – 1.3.0
Smart Slider 3: por Nextend – 3.2.8
WooCommerce MailChimp: por Saint Systems – 2.1.2
WooCommerce: por Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CLP ($)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base de la tienda: #7 - /tienda/
Carrito: #8 - /carrito/
Finalizar compra: #9 - /finalizar-comprar/
Mi cuenta: #10 - /mi-cuenta/

### Theme ###

Name: Mala Leche
Version: – 0 está disponible
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
````
</details>

**Comment by mikejolley** [comment]
Country is mandatory, this is not a bug. If you use a checkout field editor plugin it warns you this much. 

Without a country, shipping, taxes etc would all be impossible.

If you change the 'sell to' country setting and select only 1 country, the field will be hidden from view.

**Comment by avagp** [comment]
This is the setting i have: ![screenshot 2017-10-10 at 22 25 02](https://user-images.githubusercontent.com/11801254/31418044-f278f9e0-ae09-11e7-9663-c01dea751f37.png)

**Comment by mikejolley** [comment]
It's not a field, just text. What's wrong with that? You may get non-US folks attempting checkout without it?

**Comment by avagp** [comment]
I only sell and promote my ads only in my country, but is redundant to have a text in place of a field, in between a checkout form.

Before 3.0, the above configuration worked to hide the country field completely (while having only one country available on the settings) and letting the users finish the checkout without errors. 

Sorry Mike for the late response.

**Comment by mikejolley** [comment]
You can hide it with CSS.

**Comment by avagp** [comment]
Well, that should work 👍 

Thank you for your patience.
