### ISSUE TITLE
Editing a product using the legacy API on WooCommerce 3.0+ may overwrite the product price with an incorrect one

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#17125]
## Issue description
Calling the legacy API to edit a product, for example to set its inventory, has the side effect of replacing the product's standard prices with the price in whatever currency is active when the API operation is performed.

This is clearly visible in multi-currency configurations, or in any scenario involving plugins that alter product prices on the fly. but it happens even in single-currency, "plain" systems. The only difference is that, in plain configurations, the prices being fetched are the same ones already in the database, therefore the bug has no actual effect.

## Affected versions
This issue occurs only with the legacy API, and only in WooCommerce 3.0 or later. The new API, or the legacy API in WooCommerce 2.6 and earlier are not affected.

### Preparation
Note: it's easier to spot the issue with a multi-currency solution, but the issue can be reproduced with a simple filter (see below).

1. Create a product and assign it a regular price of 100. Leave the sale price empty.
2. View the product on the frontend. The price will be 100.
3. Add this filter to the site's functions.php file. It simulates, very roughly, what a multi-currency solution does, i.e. changing the price on the fly, depending on the active currency. In this case, we are simulating that the price in a hypothetical currency is 333.
~~~
add_filter( 'woocommerce_product_get_regular_price', function( $price, $product ) {
  if( !is_admin() && !defined( 'DOING_AJAX' ) ) {
    // Simulate the condition in which the price for the product, in the active 
    // currency, is "333" on the frontend, or during API calls
    $price = 333;
  }
  return $price;
}, 10, 2 );
~~~
4. View the product on the frontend. The price will be 333 (forced by the filter).

### How to trigger the issue of product prices being overwritten
Using the legacy API, change a product attribute, such as the inventory.
~~~
curl -X PUT \
  'https://example.org/wc-api/v3/products/123?consumer_key=<consumer key>&consumer_secret=<consumer secret>' \
  -H 'content-type: application/json' \
  -d '{ "product": { "stock_quantity": "999" } }'
~~~

**Expected result**: product stock changes to 999.
**Actual result**: product stock changes to 999 and its price changes to 333 (i.e. the price in the currency active when the API call was made).

## Cause
The cause is to be found in the legacy API that has been updated to work in WooCommerce 3.0+. The flow is the following:

1. Editing a product order calls method `WC_API_Products::save_product_meta`. This method checks if a regular and sale prices were passed with the request. If those prices exist, the method takes them. If not, the method gets the prices as follows:
~~~
$regular_price = $product->get_regular_price();
$sale_price = $product->get_sale_price();
~~~
The API seems to be designed with the assumption the values from the above call will be the ones contained in `_regular_price` and `_sale_price` meta, which are the prices in shop's **base** currency. This is not necessarily the case. In a multi-currency configuration, those calls return the prices in the **active** currency.

These calls trigger the filters attached the the product prices, such as the one we added earlier. As a result, the above call returns a `$regular_price` of `333`. Of course, in a multi-currency scenario, the returned value depends on the active currency, which the multi-currency solution can select it automatically, depending on the visitor who performed the call.
2. The API changes the product prices:
~~~
$product->set_regular_price( $regular_price );
$product->set_sale_price( $sale_price );
~~~
This sets the product meta, saving the values of `$regular_price` and `$sale_price` against `_regular_price` and `_sale_price` meta. The regular price is now 333.
3. The API uses the values of `$regular_price` and `$sale_price` to determine the product price. The final price is now 333 as well.

### Other example scenarios in which the issue can occur
In a a simple, single-currency system, without additional plugins, this bug is necessarily always visible, because the prices returned by `$product->get_regular_price()` and `$product->get_sale_price()` **may** come directly from the product meta, and saved against the same meta.

However, this issue could affect any plugin or code that alters product prices dynamically. For example, a discount plugin might reduce the product price by 10%. In such case, we could see the following:
1. The API call is made.
2. The product price is retrieved. The call to $product->get_regular_price() returns a value of 90 (i.e. the original price of 100 with a 10% discount.
3. The product price (now 90) is saved against the product.
4. Customers now see a price of 81 in the frontend (90 minus 10% discount).

## Why WC 2.6 and earlier are not affected
Earlier versions of WooCommerce fetched the product prices directly from the database, skipping filters. Here's the code from WC 2.6:
~~~
// Regular Price
if ( isset( $data['regular_price'] ) ) {
  $regular_price = ( '' === $data['regular_price'] ) ? '' : $data['regular_price'];
} else {
  $regular_price = get_post_meta( $product_id, '_regular_price', true );
}

// Sale Price
if ( isset( $data['sale_price'] ) ) {
  $sale_price = ( '' === $data['sale_price'] ) ? '' : $data['sale_price'];
} else {
  $sale_price = get_post_meta( $product_id, '_sale_price', true );
}
~~~
If no price is passed, the prices are loaded from `_regular_price` and `_sale_price meta`, and saved back against that meta. The values are not filtered, so they don't change unexpectedly.

**Comment by mikejolley** [comment]
This has already been fixed for 3.2 https://github.com/woocommerce/woocommerce/pull/16844

**Comment by daigo75** [comment]
Thanks @mikejolley. I looked for a previous issue, but I couldn't find it, hence my submission. I must have searched using the wrong query. Good to know that iit has been fixed. :+1:

**Comment by daigo75** [comment]
Sorry for reopening this conversation. A client reported that the issue is still present in WooCommerce 3.2. I looked at the code, the bug seems to be in class `WC_API_Products`, line 1569:
~~~
if ( $product->is_on_sale() ) {
  $product->set_price( $product->get_sale_price() );
} else {
  $product->set_price( $product->get_regular_price() );
}
~~~

The above calls will fetch the sale price or the regular price after it has been processed by the filters, as per the example I posted. That is, if a product's regular price, in the database, is 100, but there are filters that change it on the fly, the call to `$product->get_regular_price()` will return the modified price, which will then be set against product's `_price` meta.

A possible fix (untested, as I'm on a mobile phone at the moment) would be to set the product price if either the regular or sale price have been passed, and fetching those prices with calls like `$product->get_regular_price( 'edit' )`, to skip filters.

**Comment by daigo75** [comment]
I'm going to submit a new PR in relation to this issue. There's still a call to `$product->is_on_sale()` that uses the `view` context, and that triggers the calls to `$product->get_regular_price()` and `$product->get_sale_price()` in that context. That causes the same issue that the changes from [commit 6e5cdc6](https://github.com/woocommerce/woocommerce/commit/6e5cdc60e8a2b80520e73f1871c12bfc377fd420) should prevent.
