### ISSUE TITLE
WooCommerce Services - No Shipping Label option showing up on orders outside of USA

### ISSUE THREAD

**Issue by Vickie12** [woocommerce/woocommerce#17126]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

When using the WooCommerce Services plugin i don't have a Shipping Label option showing up on orders outside of USA. I have attempted to check all rate options and did a test order to assure they do appear upon checkout. 

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://rimemsk.com
Site URL: http://rimemsk.com
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.51 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (16) ###

WooCommerce Conditional Shipping and Payments: by WooThemes – 1.1.10
BE Page Builder: by Brandexponents – 4.6.1
BE Portfolio Post: by Brandexponents – 1.1
BE one click import: by BrandExponents – 3.0.1
Contact Form 7: by Takayuki Miyoshi – 4.9
Jetpack by WordPress.com: by Automattic – 5.4
Master Slider Pro: by averta – 3.0.4
Meta Box Conditional Logic: by Tan Nguyen – 1.3
Meta Box Show Hide: by Rilwis – 1.0.2
Meta Box Tabs: by Rilwis – 1.0.0
MOJO Marketplace: by Mike Hansen – 0.7.1
Slider Revolution: by ThemePunch – 5.2.6
Scalable Vector Graphics (SVG): by Sterling Hamilton – 3.4
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.4
WooCommerce Services: by Automattic – 1.7.1
WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3632 - /index.php/shop/
Cart: #2695 - /index.php/cart-2/
Checkout: #2696 - /index.php/checkout-2/
My account: #2697 - /index.php/my-account-2/

### Theme ###

Name: Oshin
Version: 4.6
Author URL: http://www.brandexponents.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Save to Log

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Save to Log
`
</details>

**Comment by claudiulodro** [comment]
Sorry we can only handle bugs for the core WooCommerce plugin on GitHub and not for WooCommerce extensions. Please [open a support ticket](https://woocommerce.com/my-account/tickets/) and the WooCommerce Services team will investigate. Thanks.
