### ISSUE TITLE
Potential performance improvement on heavily variable products.

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce#17120]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a variable product with variations based on 2 or more attributes - I've used 3 in the example below.
2. Note the ID of the main product
3. In a wp-cli shell, run the following (replacing 42 with your product ID):

```
$ global $wpdb;
$ $p = wc_get_product( 42 );
$ count( $wpdb->queries );
```
Note the number returned here. For me on my test product, it is 32.
```
$ wc_get_product( 42 );
$ count( $wpdb->queries );
```
Note the number returned here. For me on my test product, it is 35.
```
$ wc_get_product( 42 );
$ count( $wpdb->queries );
```
Note the number returned here. For me on my test product, it is 38.

Each time a variable product is retrieved, most information is retrieved through WP APIs and therefore no additional queries need to run to load it again. However, for each attribute set on a variable product a direct DB query is run, the results of which aren't cached in any way. This leads to multiple loads of a product generated additional queries. One query will be run for each attribute associated with variations. In my example above, the product has variations based on 3 attributes, so three queries are run each time the product is loaded. 

Example query (on a product with 256 variations)

```sql
SELECT meta_value FROM wp_postmeta WHERE meta_key = 'attribute_pa_colour' AND post_id IN (1139,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934)
```

This can hurt performance if a product is accessed multiple times in the same request (especially since multiple queries run each time, and they aren't necessarily particularly "nice" queries either!).

The queries are generated inside `WC_Product_Variable_Data_Store_CPT::read_variation_attributes()`

## Expected/actual behavior

Multiple loads of a product within the same request do not require additional database queries.

**Comment by kevin25** [comment]
That is right. I have 90 variants and always takes so long to load all of them.

**Comment by tonybahama** [comment]
We have 60-80 variations mostly, selling T-shirts and this could be improved yes! Even with good hosting.

**Comment by kevin25** [comment]
@tonybahama  Did you apply this to your site?

**Comment by tonybahama** [comment]
@kevin25 No, not yet. I always wait for a stable release.

**Comment by kevin25** [comment]
I git this file and test on live site. It worked without issue.

**Comment by tonybahama** [comment]
I saw it works fine! Glad you guys solved this problem! Any change it gets into 3.2.2 or is there a reason it must wait for 3.3.0?

**Comment by rodrigoprimo** [comment]
@tonybahama, a patch version, like 3.2.2, is for bug fixes only. Enhancements that are backward compatible, like this one, should be in a minor version and the next minor version is 3.3.0. For more information about WC versioning see: https://woocommerce.wordpress.com/2017/03/13/important-update-regarding-the-upcoming-woocommerce-release-2-7-will-be-3-0-0/

**Comment by tonybahama** [comment]
Oh sorry my mistake I know that! 

I was just eager to see some performance improvement before the holiday season.

Üdv,
K.Szabó Levente

**Comment by kevin25** [comment]
This works perfectly for me on WooCommerce 3.1.2.

**Comment by kevin25** [comment]
@mikejolley @leewillis77 can we also cache it on categories?

I saw this whenever customers browses the categories:

> /product-category/for-men/?wc-ajax=get_refreshed_fragments

**Comment by tonybahama** [comment]
@kevin25 Thanks for the feedback. 
Sorry I am not familiar with how one can replace a core file from a github pr. How can I download those files changes?
