### ISSUE TITLE
woocommerce_my_account shortcode order_count=-1 does not work as documented

### ISSUE THREAD

**Issue by kontur** [woocommerce/woocommerce#17135]
I'm using WooCommerce 3.1.2. Using the order_count attribute on the account page like so

`[woocommerce_my_account order_count=-1]`
( or equally `[woocommerce_my_account order_count="-1"]`)

does not result in displaying all orders on my test account. There still is a pagination splitting the orders into a list of ten items.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Place more than 10 orders
2. Browser to your account > Orders page

## Expected/actual behavior

When I follow those steps, I see... a pagination.

I was expecting to see... no pagination and a list of all orders.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/) - Twenty Seventeen tested
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://--clientname--.dev
Site URL: http://--clientname--.dev
WC Version: 3.1.2
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) PHP/7.0.15
PHP Version: 7.0.15
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
SecureTransport

SUHOSIN Installed: –
MySQL Version: 5.6.20
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.6.1
Fontsampler: by Johannes Neumeier – 0.3.6
Aelia Foundation Classes for WooCommerce: by Aelia – 1.8.9.170629
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.6
WooCommerce EU VAT Assistant: by Aelia – 1.7.10.170711
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.0.13
WooCommerce Typeface Product Type: by Johannes Neumeier – 0.0.1
WooCommerce: by Automattic – 3.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
typeface_product (typeface_product)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #245 - /shop/
Cart: #287 - /cart/
Checkout: #247 - /checkout/
My account: ❌ Page does not contain the shortcode.

### Theme ###

Name: 
Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: --clientname--/woocommerce/archive-product.php
--clientname--/woocommerce/cart/cart-totals.php
--clientname--/woocommerce/cart/cart.php
--clientname--/woocommerce/content-product.php
--clientname--/woocommerce/myaccount/orders.php
--clientname--/woocommerce/order/order-details-item.php

`
```
</details>

When I remove the order_count attribute from the shortcode the line in above report stating that the "Page does not contain the shortcode" is not present - the account page works, either way, but with the pagination.

On a sidenote, the actual [documentation](https://docs.woocommerce.com/document/woocommerce-shortcodes/#section-4) does not even state clearly how this attribute (what is it's name?) should be applied. I've found this information on Stackoverflow and [another site](https://marketpress.com/2015/woocommerce-shortcodes-list/)

**Comment by mikejolley** [comment]
This param was deprecated in 2.6. The `woocommerce_my_account_my_orders_query` filter controls the query for orders and can be used instead.

https://github.com/woocommerce/woocommerce/blob/8b0400c348783095405a22634c2b814ef43d8e6b/includes/wc-template-functions.php#L2337

**Comment by kontur** [comment]
Thanks for the info. The documentation should reflect this :)

**Comment by mikejolley** [comment]
Which docs are you looking at?

**Comment by kontur** [comment]
https://docs.woocommerce.com/document/woocommerce-shortcodes/#section-5

> Shows the ‘my account’ section where the customer can view past orders and update their information. You can specify the number of orders to show. By default, it’s set to 15 (use -1 to display all orders.)

Alas, despite mentioning the number of orders to show, it doesn't say it has such an attribute. This is confusing, and I did give credence to another guide listing the order_count attribute, since the documentation does mentions you can set the number.

**Comment by claudiosanches** [comment]
Docs updated.
