### ISSUE TITLE
VAT sort order doesn't take into account post code and city fields

### ISSUE THREAD

**Issue by atimmer** [woocommerce/woocommerce#17138]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Configure a VAT rate for a country that is non-zero, such as Germany: DE, 19%.
2. Configure an exception on this VAT rate for a certain post code, such as Germany: DE, 27498; 78266, 0%.
3. Now when you use this post code in the checkout 19% is used as VAT.

If you swap steps 1 and 2 then it does work. This is because the VAT sort first sorts based on these heuristics:
1. Priority
2. City
3. State
4. ID

In my provided example we fall back to the ID sort.

## Expected/actual behavior

When I follow those steps, I see...

* 19% VAT for Germany and my selected postcodes.

I was expecting to see...

* 0% VAT for Germany and my selected post codes.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by atimmer** [comment]
Seems this was introduced with https://github.com/woocommerce/woocommerce/pull/11540.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17160
