### ISSUE TITLE
Sorting bookable product issue

### ISSUE THREAD

**Issue by TVu95** [woocommerce/woocommerce#17136]
Hi all, I'm currently experiencing a problem regarding sorting my bookable products in ascending/descending order. Sorting seems to only not work correctly with bookable products but works correctly with affiliate products.

I've attached two images where the products are being sorted in ascending order. One being a page full of bookable products with the top three products being bookable products and another screenshot being full of bookable products not correctly sorted.

Bookable products
<img width="956" alt="adventure" src="https://user-images.githubusercontent.com/16736765/31439150-0ba17ec8-ae83-11e7-9465-165b537d50eb.png">

Affiliate products with three bookable products at the top
<img width="958" alt="tourism" src="https://user-images.githubusercontent.com/16736765/31439151-0c0bb6bc-ae83-11e7-87f0-505bab6b53af.png">

**Comment by mikejolley** [comment]
We only handle core issues on this issue tracker.

Please use the helpdesk so the bookings team can look into this if needed https://woocommerce.com/my-account/tickets/ The _price field may be wrongly stored and need investigation.

Thanks

cc @mattyza
