### ISSUE TITLE
[RC.2] Problem with `woocommerce_review_order_after_shipping` action

### ISSUE THREAD

**Issue by DawidUrbanski** [woocommerce/woocommerce#17133]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use this simple plugin:
```
<?php
/**
 * Plugin name: Test plugin WooCommerce
 */

add_action( 'woocommerce_review_order_after_shipping', function(){
  var_dump( is_checkout() );
});
```

2. Set any flat rate shipping (or any shipping).
3. Add anything to cart and go to checkout.

## Expected/actual behavior

When I follow those steps, I see...

First of all, for some reason this action triggers twice. On all of tested instances.

Secondly, in `v3.2.0-beta.1`, `v3.2.0-rc.1` i Get:
```
/var/www/html/web/app/plugins/test/test.php:7:boolean true
/var/www/html/web/app/plugins/test/test.php:7:boolean true
```

In `v3.2.0-rc.2` however its:
```
/var/www/html/web/app/plugins/test/test.php:7:boolean true
/var/www/html/web/app/plugins/test/test.php:7:boolean false
```

Which causing check for checkout fails and proper code is not executed.

I was expecting to see...

The same behaviour in all versions.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
### WordPress Environment ###

Home URL: http://wc32.localhost
Site URL: http://wc32.localhost/wp
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.9
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 2.08MB
Database Data Size: 1.22MB
Database Index Size: 0.86MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.50MB + Index: 0.02MB
wp_postmeta: Data: 0.16MB + Index: 0.09MB
wp_posts: Data: 0.06MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 51
page: 5
post: 2
product: 23
product_variation: 4

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Test plugin WooCommerce: by  –  – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.0-rc.2
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by claudiulodro** [comment]
#17103 should solve the inconsistent behavior. I always get true running the latest version of the `release/3.2` branch. 

Still need to investigate why it's firing twice, and whether it should be firing twice (probably shouldn't be).

**Comment by claudiulodro** [comment]
`woocommerce_review_order_after_shipping` actually fires many times! Once on the initial load when the page is rendered and again each time an ajax call to update the order review contents is sent out.

The output of `var_dump` isn't going to get cleaned up by the frontend code that handles the order review updating, so new `var_dump` output is going to appear each time the order review gets updated. Everything is working correctly there.
