### ISSUE TITLE
Incorrect Validation Error - The city field is required REFID:#### 

### ISSUE THREAD

**Issue by tanmad21** [woocommerce/woocommerce#17142]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use Woocommerce Plugin with Network Merchant Plugin
2. Attempt to Purchase
3. An error occurs - The city field is required REFID:*** - see attached screenshot

I checked the network tab of chrome's debugger tools and confirmed that billing_city is sent but it is still failing validation for some reason.
Screen Shot 2017-10-11 at 12.59.11 P
![screen shot 2017-10-11 at 12 59 11 pm](https://user-images.githubusercontent.com/11345603/31460763-a13a2060-ae84-11e7-862c-d2457169fdfd.png)

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

```
WordPress environment
--
Home URL: |   | http://pureblendoils.com
Site URL: |   | http://pureblendoils.com
WC version: |   | 3.1.2
Log directory writable: |   | /nas/content/live/cpureblendoils/wp-content/uploads/wc-logs/
WP version: |   | 4.8.2
WP multisite: |   | –
WP memory limit: |   | 512 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US


```
</details>

**Comment by claudiulodro** [comment]
Hi there! GitHub is for reporting bugs and issues specific to the WooCommerce plugin. Your issue seems to be caused by the Network Merchant plugin. Please contact the author directly for support.
