### ISSUE TITLE
Email template overrides link color issue when using white as a Base Color

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#17140]
## Steps to reproduce the issue

1. Under WooCommerce > Settings > Email set the **Base Color** to #ffffff
2. Sign up for new account and the _New Account_ email will contain a link in the body using the base color.

Image of link using Base Color setting:
![Screenshot](http://cld.wthms.co/WdJK9H+)
Image Link: http://cld.wthms.co/WdJK9H

## Expected/actual behavior

It would be better if the link took on the **Body text color** or if there was an option to specify a link color.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17153
