### ISSUE TITLE
woocommerce_guided_tour_tab loads JavaScript unconditionally

### ISSUE THREAD

**Issue by szepeviktor** [woocommerce/woocommerce#17145]
Hello!

Admin pages are much slower because of the JavaScript of `woocommerce_guided_tour_tab` videos.

Is there a nicer way to get back speed?

```php
add_action( 'current_screen', function () {
    get_current_screen()->remove_help_tab( 'woocommerce_guided_tour_tab' );
}, 51 );
```

**Comment by mikejolley** [comment]
@ryanr14 Maybe we need plan b then - no embeds :(

**Comment by mikejolley** [comment]
https://webdesign.tutsplus.com/tutorials/how-to-lazy-load-embedded-youtube-videos--cms-26743

**Comment by szepeviktor** [comment]
FYI Yoast solved the very same issue.

**Comment by ryanr14** [comment]
It does make my work a bit easier if there are no embeds within WooCommerce core, linking to docs should still hopefully help. :P

It would also make sense to not load the content until the help tab is actually used/opened. So either lazy loading or looking at what Yoast does?

**Comment by szepeviktor** [comment]
Thank you.
