### ISSUE TITLE
Variation taxes missing or doubled

### ISSUE THREAD

**Issue by kloon** [woocommerce/woocommerce#17147]
When you have a variable product with the variations' tax class set to `Same as parent` it either doubles the tax calculations or does not add any taxes depending on whether your shop defines prices inclusive or exclusive of tax.

[UPDATE]
The missing taxes seems to be related to the tax rates not being synced/cache cleared when you change a variation. When you change the parent tax class to something else, save and change it back to standard and save again, the rates start showing right.
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. Enable taxes on your store and set a tax rate under the standard class.
2. Set up a variable product with a variation, set the variable product tax class to `Standard` and then the variation to `Same as parent`
3. Add the variation to cart and proceed to checkout
4. Notice either double tax or no tax

## Expected/actual behavior

I expect to see the standard tax rate applied only once.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by Mikk3lRo** [comment]
Experiencing the same symptom here. Happened after updating. I have lots of product that do not show the behaviour though. Changing the parent tax class back and forth does not fix it for me.

**Comment by Aky-lesh** [comment]
Hi All, 

i am not sure why i am getting this error in 2021.

Theme Used: OceanWP Version: 2.1.1
Wordpress Ver: 5.7.2
woocommerce ver: 5.5.1
