### ISSUE TITLE
When I click Variations on a variable product it times out and I can't edit it

### ISSUE THREAD

**Issue by el-presidente** [woocommerce/woocommerce#17146]
Just updated to 3.2 and I can't edit all my variation products - when I click Variations it keeps loading or times out so I cannot edit them:

![screen shot 2017-10-12 at 09 45 07](https://user-images.githubusercontent.com/937382/31484904-4cf22080-af32-11e7-9591-1e7ec5e88c2c.png)

**Comment by el-presidente** [comment]
Also if I try and remove a Attribute it times out:

![screen shot 2017-10-12 at 09 51 25](https://user-images.githubusercontent.com/937382/31485111-fb2668e6-af32-11e7-9bb1-e236af413403.png)

**Comment by el-presidente** [comment]
Tried different domains with same result - I can remove Attributes even though it shows the time out animated gif - but I'm not allowed to click and edit Variations.

**Comment by mikejolley** [comment]
What was it @el-presidente ?
