### ISSUE TITLE
Localize scrollTop offset in checkout.js

### ISSUE THREAD

**Issue by diggy** [woocommerce/woocommerce#17156]
Hardcoded value does not always play nice with sticky/fixed site headers.

https://github.com/woocommerce/woocommerce/blob/213bfabb2474e9a0e22b93067a225f7a451bf34d/assets/js/frontend/checkout.js#L389

**Comment by mikejolley** [comment]
This scrolls to 100px above the checkout form. Why would the header affect this at all?

**Comment by diggy** [comment]
![screen shot 2017-10-12 at 15 38 59](https://user-images.githubusercontent.com/1071337/31499260-910a3bb8-af64-11e7-8eb7-014818182056.png)

**Comment by mikejolley** [comment]
What is needed? Want to send a PR?

**Comment by diggy** [comment]
Sure, will take a closer look asap :)

**Comment by nishitlangaliya** [comment]
Submitted PR https://github.com/woocommerce/woocommerce/pull/17220

**Comment by diggy** [comment]
closed in #17500
