### ISSUE TITLE
Regression in new unified shortcode

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/woocommerce#17159]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. create a page with the new shortcode [products category="folder" limit="16" columns="4"]
2. create a page with the old shortcode [product_category category="folder" per_page="16" columns="4"]
3.

## Expected/actual behavior

On the page with the new shortcode, the last product on the first row seems to "drop down" a bit. All following rows are OK. 
The page with the old shortcode is fine. 
Applying the new shortcode on the homepage, shows this "dropping" on all products on the first row. Each one  bit lower.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

Site: https://speldorado.vandenbussche.nl/
Goto https://speldorado.vandenbussche.nl/test-old and test-new to see.

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
![new-shortcode](https://user-images.githubusercontent.com/7521869/31497105-304a2eba-af5e-11e7-9954-c0306ff51e97.png)
![old-shortcode](https://user-images.githubusercontent.com/7521869/31497106-3061daba-af5e-11e7-9aac-36f38b4b1163.png)
Your account: woo-support / Sh0rtC0de

**Comment by EgbertJan** [comment]
Forget my remark about the homepage. It is OK now using [products visibility="featured"]
Egbert Jan

**Comment by mikejolley** [comment]
Your shortcode is wrapped in `code` tags. Thats all.

**Comment by EgbertJan** [comment]
Sorry??? How can I see what you mean? Ik did a cut/paste of the shortcode in the page editor.

**Comment by mikejolley** [comment]
In the editor, view the HTML.

**Comment by EgbertJan** [comment]
Ah. TEXT mode revealed the <code> shit. Now it works. Thanks. Pse close ticket.
