### ISSUE TITLE
Filtering orders by date range through API

### ISSUE THREAD

**Issue by xiangrana2** [woocommerce/woocommerce#17166]
Hello, Today I have tried to filter orders by creation date using the params "before" and "after" but I am getting orders a datetime different than the date range given
e.g
1) 
GET request to /wc-api/v3/orders?&after=2017-09-20&before=2017-09-21
or
GET request to /wc-api/v3/orders?&after=2017-09-20T00:00:00&before=2017-09-21T00:00:00

Result in both requests: orders created in different dates like 2017-10-06

What do we have to do to filter orders created given a datetime ranges correctly through the API?
Thanks in advance

## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Using after and before params within the URL "/wc-api/v3/orders"

## Expected/actual behavior

Orders created in different dates outside the date range given in "before" and "after" params.

I was expecting to see...

Orders created in the date range given in "before" and "after" params.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
1.  There is no v3 api yet
2.  The first example tells you the dates are invalid. ISO must be used.
3. https://local.wordpress.dev/wp-json/wc/v2/orders?after=2017-09-20T00:00:00&before=2017-09-21T00:00:00 works. I've just confirmed locally. Maybe some confusion around local Wp timezone and UTC timestamps?

**Comment by xiangrana2** [comment]
The problem was the python library actually (https://pypi.python.org/pypi/WooCommerce), it was using by default the url wp-json/wc/v2/orders  instead of /wp-json/wc/v2/orders for some reason. Im doing the requests directly with the given URL without using the official python library. It works now. Thanks
