### ISSUE TITLE
"Quantity" label showing in cart

### ISSUE THREAD

**Issue by Garconis** [woocommerce/woocommerce#17173]
The "Quantity" label that was added above the input in the Cart, is showing, even though the `screen-reader-text` class is on it.

https://i.gyazo.com/085262b6284e7acd692c94a16c246fad.png

**Comment by claudiulodro** [comment]
`screen-reader-text` support is done by the theme, so this is going to be an issue in your theme. Easiest fix would be to add [this CSS](https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentytwelve/style.css#L504-L531) to your theme's stylesheet if it's a custom theme, or you can use the customizer and add it as a css snippet.
