### ISSUE TITLE
WC_ABSPATH in wc-core-functions.php not valid. Webshop not loading due to errors 

### ISSUE THREAD

**Issue by HansPrins** [woocommerce/woocommerce#17175]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiulodro** [comment]
You have given me no details or anything about this issue, so I can not effectively troubleshoot it. I'll reopen this issue and investigate if you provide the steps to reproduce the issue and the system status report. I recommend following the steps in the [Troubleshooting Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see where your site's issues are coming from.

**Comment by HansPrins** [comment]
Please open again. I was still typing the issue
