### ISSUE TITLE
Subtotals missing from inside order admin area

### ISSUE THREAD

**Issue by lorrinevil** [woocommerce/woocommerce#17172]
Since last night's update the only thing showing on the bottom of the order is the total
(Sales tax is showing if it's an order we need to collect sales tax on)
![image](https://user-images.githubusercontent.com/27705367/31511713-37222f90-af4e-11e7-983e-cc68254ebf92.png)

The email invoice to us and the customer does have it broken down
![image](https://user-images.githubusercontent.com/27705367/31511674-18cecd78-af4e-11e7-9d86-789d3d7bea1b.png)

**Comment by mikejolley** [comment]
Pretty sure these were removed on purpose to reduce clutter in admin. They serve no apparent purpose and can be misleading when the excl. tax display prices in admin differ from your store's incl. tax displays. 

I don't think we need to add them back without good reason. The order total is the most important thing.

Thanks

**Comment by lorrinevil** [comment]
They serve plenty of purposes for those managing the stores.. If a discount is applied - they want to see it on the bottom line of the order, not have to go hunt through the emails to see what is what - people want to see their break down of subtotal, discount, tax & shipping.
I have multiple clients that use this for their own purposes and have had 8 calls this morning from unhappy people wanting to know what the problem is.

**Comment by lorrinevil** [comment]
seriously - just closed this without a response? Not a good thing to remove...I guess I'll need to wait for someone to write a plugin to put back in?

**Comment by mikejolley** [comment]
@lorrinevil 

>  If a discount is applied - they want to see it on the bottom line of the order

Thats not represented by the subtotal. Shipping and per line discounts are all shown above with the items themselves.

Showing a dedicated discount line is also misleading because of the way you can edit line item prices - they don't always correspond to coupons in the order.

You can hover over applied coupons FWIW to get a breakdown of individual discounts. As you may have read, you can now remove/add coupons via that interface. 

![edit order local wordpress dev wordpress 2017-10-12 19-26-11](https://user-images.githubusercontent.com/90977/31512534-3a9ddb1c-af83-11e7-8e44-bd31daa3a9e3.png)

I doubt someone new to the system would even notice this. I think you may have just been notified because it looks different to what they have seen in the past.

> seriously - just closed this without a response? Not a good thing to remove...I guess I'll need to wait for someone to write a plugin to put back in?

um. I did respond. The issue has not gone anywhere. I can still read replies.

**Comment by lorrinevil** [comment]
It's marked closed.
![image](https://user-images.githubusercontent.com/27705367/31513306-96863576-af53-11e7-8f6b-9bf38fe68189.png)

And "being used to" carries a lot of weight if you consider your users and how they might work their business.  These ARE important to my clients.
I can tell you that with the first client that brought it to my attention it is important.
I know this not only because they say it is, but because I just spent last year and half back and forth onsite working with them and their business implementing specific things to streamline.
I converted one of the sites from x-cart (they have 2) - I think that just assuming it doesn't affect your end users is a mistake.
Coupons are NOT used on this particular site.  There are reps and we have a plugin that connects them to get discounts up front - it's important for a rep to be able to see their discount when creating their invoice for their customers when delivering the product and collection up front.
It's a simple "look and see" at the bottom - scrolling through and having to add up each item added to the cart that might have been discounted is going to get phone calls coming in and complaining wasting time better spent elsewhere. The idea that something at the bottom of the internal order would clutter the admin area makes no sense to me. It will be interesting to see as people realize it's gone if others feel the same.

**Comment by lorrinevil** [comment]
bottom line is we want these in there. Have been here looking at all the changes, but don't see the removal of this addressed. it would be helpful if you could guide me to where I can put them back in for the clients that need them. TIA https://woocommerce.wordpress.com/2017/10/11/woocommerce-3-2/

**Comment by mikejolley** [comment]
I've asked Claudiu to take a look. there are some related issues which need looking at first though. as I said, the totals do not always make sense.

**Comment by claudiulodro** [comment]
@lorrinevil opened a pull request with some code to add the lines back. See #17174

**Comment by lorrinevil** [comment]
thank you Mike.  I've never had that issue (not that it's been reported anyway) - but we don't include taxes in with the prices - we enter price exclusive of tax since we are only required to collect in a couple of states.  I am going to check out the jetpack option though - I noticed that with a new client using it and and marked it for further investigation. Thank you for listening to this side of it...

**Comment by vidishpurohit** [comment]
@lorrinevil  I was also looking for the same thing. So, I figured out a solution to this. Have a look here: [Add subtotal to edit order admin](https://www.wooextend.com/add-subtotal-to-edit-order-admin-woocommerce/)

**Comment by lorrinevil** [comment]
@vidishpurohit thank you! I was just having to revisit this thread because of any issue synching with qb's online with a partial refund (So the error QB is giving us is due to the discount being greater than the subtotal because it's not seeing original total prior to discount) - I'm going to go test your fix now - I didn't see it when you originally posted thank you! crossing fingers.

**Comment by lorrinevil** [comment]
@vidishpurohit - okay - it worked, but it's coming in below the discount. Thoughts?
![image](https://user-images.githubusercontent.com/27705367/38647207-b5805d26-3db0-11e8-8bf6-b01f83a7f88f.png)

**Comment by vidishpurohit** [comment]
@lorrinevil  That was the first place where woocommerce allows us to put any custom stuff! It's the first available hook in that order! It offers a bunch of hooks after each subsequent total position though!

**Comment by lorrinevil** [comment]
@vidishpurohit I updated the issue back when this started and some lines were put back in - hopefully we will get it figured out - without seeing the subtotal - quickbooks is only seeing that the discount is higher than the total so the math doesn't work for a refund. Do appreciate the response though.
https://github.com/woocommerce/woocommerce/pull/17174

**Comment by mgason** [comment]
This is great but I was hoping to show the order sub total minus any coupon discounts at that point. I am not having much luck. I actually need to show that but given the display positioning issue you mentioned it would actually make more sense to display that there.

**Comment by vidishpurohit** [comment]
@mgason  If you see in arguments, you are getting order id there. So you can get order total and & coupon total and perform mathematical operations there and display the amount as you wish. Doesn't it work that way?
