### ISSUE TITLE
Order details customer template is badly formatted

### ISSUE THREAD

**Issue by lutrov** [woocommerce/woocommerce#17179]
The file `woocommerce/templates/order/order-details-customer.php` is badly formatted which makes it difficult to understand and therefore difficult to customise. The `if` conditional logic looks confusing as a result of the bad formatting.

This is related to [#17177](https://github.com/woocommerce/woocommerce/issues/17177) which was closed due to "incorrect wording" of the issue.

**Comment by kloon** [comment]
We need to be careful with template changes as it has the potential to break things where customers have overridden them. I'm happy with just a formatting change here, making sure everything is indented properly and looks clean.

**Comment by garethmcc** [comment]
Are there any specific style guidelines to follow?

**Comment by kloon** [comment]
@garethmcc just stick to general WordPress guidelines https://make.wordpress.org/core/handbook/best-practices/coding-standards/html/#indentation

IE. Make sure the endif's match up with the opening if's.

**Comment by garethmcc** [comment]
Submitted a PR

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17233
