### ISSUE TITLE
product image on the product page is not displayed

### ISSUE THREAD

**Issue by yehudamor** [woocommerce/woocommerce#17171]
After updating the product image on the product page is not displayed, how can I fix it?

**Comment by claudiulodro** [comment]
Hi there. This is not really enough information to troubleshoot the problem. What version of WooCommerce were you running before? Also can you copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here?

**Comment by mikejolley** [comment]
Please provide all details on the new issue form, and go through the troubleshooting steps listed on https://github.com/woocommerce/woocommerce/issues/new before submitting as a new issue.

Thanks
