### ISSUE TITLE
After the update to 3.2.0 webshop not working due to errors with WC_ABSPATH variable

### ISSUE THREAD

**Issue by HansPrins** [woocommerce/woocommerce#17176]
Prerequisites

 I have searched for similar issues in both open and closed tickets and cannot find a duplicate

 The issue still exists against the latest  master  branch of WooCommerce on Github (this is not the same version as on WordPress.org!)

 I have attempted to find the simplest possible steps to reproduce the issue

 I have included a failing test as a pull request (Optional)

Steps to reproduce the issue

This happens after the update to version 3.2.0.
1.All lines starting from line 18 the includes dosnot work because WC_ABSPATH is not valid
 // Include core functions (available in both admin and frontend).
 include( WC_ABSPATH . 'includes/wc-conditional-functions.php' );
 include( WC_ABSPATH . 'includes/wc-coupon-functions.php' );
 include( WC_ABSPATH . 'includes/wc-user-functions.php' );
 include( WC_ABSPATH . 'includes/wc-deprecated-functions.php' );
 include( WC_ABSPATH . 'includes/wc-formatting-functions.php' );
 include( WC_ABSPATH . 'includes/wc-order-functions.php' );
 include( WC_ABSPATH . 'includes/wc-order-item-functions.php' );
 include( WC_ABSPATH . 'includes/wc-page-functions.php' );
 include( WC_ABSPATH . 'includes/wc-product-functions.php' );
 include( WC_ABSPATH . 'includes/wc-stock-functions.php' );
 include( WC_ABSPATH . 'includes/wc-account-functions.php' );
 include( WC_ABSPATH . 'includes/wc-term-functions.php' );
 include( WC_ABSPATH . 'includes/wc-attribute-functions.php' );
 include( WC_ABSPATH . 'includes/wc-rest-functions.php' );
 include( WC_ABSPATH . 'includes/wc-widget-functions.php' );
 include( WC_ABSPATH . 'includes/wc-webhook-functions.php' );
2.On the webshop site you will see a blank page with Warnings for each line above like
 Warning:include(WC_ABSPATHincludes/wc-conditional-functions.php): failed to open stream: No such file or directory in /home/"sitename"/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 18
 etc, etc
 3.I removed the WC_ABSPATH . form each line and all is well again.

 This bug happens with only WooCommerce plugin active

 This bug happens with a default WordPress theme active, or Storefront

 I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
Running the woo multi currency plugin? It includes core files before woocommerce loads. It needs to be fixed by the author.

**Comment by HansPrins** [comment]
Yes, the woo multicurrency plugin is running. To understand this correctly you say that the WC_ABSPATH is destroyed by the woo multicurrency plugin?

**Comment by mikejolley** [comment]
They are loading a core file before WooCommerce is loaded by WordPress, and before `WC_ABSPATH` is defined. Plugins should not do this, it's bad practice. They should wait for WC to load properly.

Notified them here: https://wordpress.org/support/topic/woocommerce-3-2-0/ You will need to deactivate it until a fix is provided.

thanks
