### ISSUE TITLE
Order details customer template has incorrect structure & logic

### ISSUE THREAD

**Issue by lutrov** [woocommerce/woocommerce#17177]
It looks like the file `woocommerce/templates/order/order-details-customer.php` has incorrect structure & logic.

* The `endif statement on line 31 has no corresponding `if` statement.
* The `if` statement on line 45 has no corresponding `endif` statement.

**Comment by mikejolley** [comment]
it does - https://github.com/woocommerce/woocommerce/blob/master/templates/order/order-details-customer.php#L25 it's just indented weirdly. It's not a bug - if there were errors the template would not be functional.

thanks

**Comment by lutrov** [comment]
Have you fixed the weird intending then? Because the way it's structured now makes it almost impossible to understand and that makes it much more difficult to customise than necessary.

**Comment by mikejolley** [comment]
I have not, no, not yet. But the issue you've logged is not accurate. the if/endif's are all there.

1. https://github.com/woocommerce/woocommerce/blob/master/templates/order/order-details-customer.php#L25-L31

2. https://github.com/woocommerce/woocommerce/blob/master/templates/order/order-details-customer.php#L45-L61

Feel free to send a PR before I start in the morning :)
