### ISSUE TITLE
New categories widget depth option

### ISSUE THREAD

**Issue by wayheming** [woocommerce/woocommerce#17184]
After I specify the maximum depth of child categories, this option works, but the parent still has a class, although the category does not yet have a child element, and it breaks the widget's style.

[Screenshot](http://prntscr.com/gwtubn)

Sorry for my English

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17190

**Comment by wayheming** [comment]
Thx
