### ISSUE TITLE
Shortcodes 3.2+ 

### ISSUE THREAD

**Issue by BurlesonBrad** [woocommerce/woocommerce#17180]
per docs: https://docs.woocommerce.com/document/woocommerce-shortcodes/3-1-earlier/
uses `[product id="99"]` & new**er** shortcodes docs https://docs.woocommerce.com/document/woocommerce-shortcodes/ indicate using shortcode `[products]` _(with**OUT** the additional **S** added)_

test URL ---> https://stage.dunorthdesigns.com/shortcode-test/
created using the following:
```[product id="78619"]
[product id="78619,80339,74600,79532"]
[product id="78619,80339,74600,79532" per_page="12" columns="3"]
[product id="78619,80339,74600,79532" limit="12" columns="3"]

[products id="78619"]
[products id="78619,80339,74600,79532"]
[products id="78619,80339,74600,79532" per_page="12" columns="3"]
[products id="78619,80339,74600,79532" limit="12" columns="3"]
```

Please revisit either the docs or the complete functionality of the shortcode changes in WC 3.2

**Comment by kloon** [comment]
Im not sure I understand exactly what the issue is you are having here as you do not mention what is wrong?

Both are supported in 3.2 but we would prefer if you move over to use products instead, products replace product and multiple other shortcodes.

**Comment by mikejolley** [comment]
Fixed up the docs for `[products]`. It should be `ids` like 3.1.

Using `[product]` and `id` works in 3.2, but is backwards compatibility because id is mapped to ids.

New shortcode format should be:

`[products ids="78619"]`

**Comment by BurlesonBrad** [comment]
dang, boo.  i was still replying

**Comment by BurlesonBrad** [comment]
```
[product id="78619"]
[products ids="78619,80339,74600,79532" columns="4"]
[product_category category="leggings" limit="12" columns="3"]
[recent_products per_page="12" columns="4"]

[products ids="78619"]
[products ids="78619,80339,74600,79532"]
[products limit="8" columns="4" category="leggings"]
[products limit="3" columns="3" best_selling="true" ]
```
https://stage.dunorthdesigns.com/shortcode-test/
## **MUCH BETTER!** 👍 👍 👍
