### ISSUE TITLE
Since recent update, both my WooCommerce sites aren't including tax, but adding it.

### ISSUE THREAD

**Issue by mrdigitalau** [woocommerce/woocommerce#17182]
My sites are both with the GST setting show prices including GST.

Eg. Cake was $30 inc gst. (Which is 10%)

Now after update, cake still says $30 but when added to cart, it shows price as $33.

It is adding the 10% to the total even when the setting says tax is included in the price.

Is this just me or is it a bug?

**Comment by kloon** [comment]
We are aware of an issue where tax is double charges for variations with the variation set to use parent tax class. This was fixes and we will release it soon. In the meantime you can either update all your variations to use the standard tax class or apply this patch https://github.com/woocommerce/woocommerce/pull/17149
