### ISSUE TITLE
Order number missing from customer and store admin emails

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce#17199]
Tested with default Storefront:

Using WooCommerce 3.2:
New Order Email to Customer:
![](http://cld.wthms.co/369G1X+)Image Link: http://cld.wthms.co/369G1X

New Order Email to Store Admin:
![](http://cld.wthms.co/Ew8ZOS+)Image Link: http://cld.wthms.co/Ew8ZOS

With WooCommerce 3.1.2
![](http://cld.wthms.co/Ew8ZOS+)Image Link: http://cld.wthms.co/Ew8ZOS
![](http://cld.wthms.co/FdyCul+)Image Link: http://cld.wthms.co/FdyCul

733960-zen
733409-zen

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17170
