### ISSUE TITLE
Woocomerce Composite Products Version 3.9.4 - Product on webpage shows Loading...

### ISSUE THREAD

**Issue by MartinaOnlineshop** [woocommerce/woocommerce#17191]
Hi,

in my composite product is the product selection on the webpage not working.
The section where usually the selection module shown says just "loading...."

Attached you can see the picture of the element on the page.

![screenshot2](https://user-images.githubusercontent.com/32768802/31544737-8fba5780-b01c-11e7-8003-973c06e362e6.JPG)

In the composite product editor it looks fine - attached the picture of the main part of this section.
![screenshot3](https://user-images.githubusercontent.com/32768802/31544929-7da0a9fe-b01d-11e7-8001-c2ee378614c6.JPG)

Product was working a few days before and I referted back my last changes as well.
I have copied this product and created a new composite product. 
Does somebody had this kind of issue already? have not really found similar descritons.

best regards
Martina

**Comment by mikejolley** [comment]
Please post this to the helpdesk since it's a premium extension and not core. 

https://woocommerce.com/my-account/tickets/

They will likely need your status report and a login to help.

Thanks!
