### ISSUE TITLE
Email Placeholder Regression

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#17200]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use `{blogname}` as a placeholder in an email
2. Send the email
3. See this isn't replaced
4. Do the same in WC <= 3.1
5. See `{blogname}` is replaced with the site name (it was treated the same way as `{site_title}`

## Expected/actual behavior

For the same email placeholders to be supported

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

WooCommerce 3.2.0, Storefront theme

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17201
