### ISSUE TITLE
Update notification sticky needs to scroll

### ISSUE THREAD

**Issue by seb86** [woocommerce/woocommerce#17208]
When the major update notification is displayed it is not possible to scroll down to view them all, confirm or close the notification. You may have to adjust the CSS in order to allow scrolling.

![Major Update Notification](https://cldup.com/xEWAC7X2xT.png)

Let me know if you need any further information.

**Comment by myvcc657** [comment]
`reslove all`

**Comment by nishitlangaliya** [comment]
Submited PR : https://github.com/woocommerce/woocommerce/pull/17211
