### ISSUE TITLE
Product gallery not displaying in RTL since 3.2 update

### ISSUE THREAD

**Issue by salar90** [woocommerce/woocommerce#17219]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. activate the default 2017 theme
2. go to admin > setting, set Persian(فارسی) as your site language 
3. Open site shop page and navigate to a product with some pictures. you will see the large product image not visible even when you click the thumbnails.

I've tested with disabling all the plugins. and with default and production themes. result was the same.

==============
What I've discovered:
in flex slider structure, there is a div with class **woocommerce-product-gallery__image** which has different inline style when its on LTR:
one is : **margin-left: 0px; float: right;**
while the other is: **margin-right: 0px; float: left;**

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://127.0.0.1/sdfull
Site URL: http://127.0.0.1/sdfull
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 5 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: fa_IR

### Server Environment ###

Server Info: Apache/2.4.23 (Win64) PHP/7.0.10
PHP Version: 7.0.10
PHP Post Max Size: 800 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.50.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 800 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
Total Database Size: 805.59MB
Database Data Size: 405.06MB
Database Index Size: 400.53MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.31MB
wp_woocommerce_order_itemmeta: Data: 5.52MB + Index: 4.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_cfs_sessions: Data: 0.01MB + Index: 0.00MB
wp_cfs_values: Data: 0.19MB + Index: 0.29MB
wp_commentmeta: Data: 1.52MB + Index: 2.02MB
wp_comments: Data: 10.52MB + Index: 6.58MB
wp_email_notifications: Data: 0.02MB + Index: 0.01MB
wp_ewwwio_images: Data: 7.88MB + Index: 4.29MB
wp_gd_lightbox_settings: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mywebtonetperfstatsresults: Data: 0.00MB + Index: 0.00MB
wp_mywebtonetqtest: Data: 0.00MB + Index: 0.00MB
wp_newsletter: Data: 0.00MB + Index: 0.00MB
wp_newsletter_emails: Data: 0.00MB + Index: 0.00MB
wp_newsletter_sent: Data: 0.00MB + Index: 0.00MB
wp_newsletter_stats: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 2.36MB + Index: 1.09MB
wp_pollsa: Data: 0.00MB + Index: 0.00MB
wp_pollsip: Data: 0.00MB + Index: 0.01MB
wp_pollsq: Data: 0.00MB + Index: 0.00MB
wp_postmeta: Data: 81.56MB + Index: 36.00MB
wp_posts: Data: 13.52MB + Index: 6.03MB
wp_relevanssi: Data: 8.01MB + Index: 13.91MB
wp_relevanssi_log: Data: 0.01MB + Index: 0.01MB
wp_relevanssi_stopwords: Data: 0.01MB + Index: 0.01MB
wp_revslider_css: Data: 0.02MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_settings: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.00MB + Index: 0.00MB
wp_revslider_slides: Data: 0.00MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_rg_form: Data: 0.00MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.01MB + Index: 0.00MB
wp_rg_form_view: Data: 0.00MB + Index: 0.00MB
wp_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB
wp_rg_lead: Data: 0.00MB + Index: 0.00MB
wp_rg_lead_detail: Data: 0.00MB + Index: 0.00MB
wp_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.00MB + Index: 0.00MB
wp_rg_lead_notes: Data: 0.00MB + Index: 0.00MB
wp_statistics_exclusions: Data: 0.03MB + Index: 0.03MB
wp_statistics_historical: Data: 0.06MB + Index: 0.09MB
wp_statistics_pages: Data: 123.02MB + Index: 223.99MB
wp_statistics_search: Data: 6.58MB + Index: 3.68MB
wp_statistics_useronline: Data: 0.00MB + Index: 0.00MB
wp_statistics_visit: Data: 0.01MB + Index: 0.01MB
wp_statistics_visitor: Data: 108.14MB + Index: 71.39MB
wp_termmeta: Data: 0.62MB + Index: 0.39MB
wp_terms: Data: 2.52MB + Index: 4.03MB
wp_term_relationships: Data: 2.52MB + Index: 2.52MB
wp_term_taxonomy: Data: 1.52MB + Index: 0.94MB
wp_usermeta: Data: 13.52MB + Index: 11.03MB
wp_users: Data: 1.52MB + Index: 0.52MB
wp_wfbadleechers: Data: 0.00MB + Index: 0.00MB
wp_wfblockediplog: Data: 0.01MB + Index: 0.01MB
wp_wfblocks: Data: 0.00MB + Index: 0.00MB
wp_wfblocksadv: Data: 0.00MB + Index: 0.00MB
wp_wfconfig: Data: 1.40MB + Index: 0.01MB
wp_wfcrawlers: Data: 0.01MB + Index: 0.01MB
wp_wffilemods: Data: 0.00MB + Index: 0.00MB
wp_wfhits: Data: 0.47MB + Index: 0.07MB
wp_wfhoover: Data: 0.00MB + Index: 0.00MB
wp_wfissues: Data: 0.03MB + Index: 0.00MB
wp_wfknownfilelist: Data: 3.01MB + Index: 0.43MB
wp_wfleechers: Data: 0.02MB + Index: 0.01MB
wp_wflockedout: Data: 0.00MB + Index: 0.00MB
wp_wflocs: Data: 0.00MB + Index: 0.00MB
wp_wflogins: Data: 0.15MB + Index: 0.03MB
wp_wfnet404s: Data: 0.00MB + Index: 0.00MB
wp_wfnotifications: Data: 0.00MB + Index: 0.00MB
wp_wfpendingissues: Data: 0.00MB + Index: 0.00MB
wp_wfreversecache: Data: 0.00MB + Index: 0.00MB
wp_wfscanners: Data: 0.03MB + Index: 0.05MB
wp_wfsnipcache: Data: 0.00MB + Index: 0.00MB
wp_wfstatus: Data: 0.08MB + Index: 0.04MB
wp_wfthrottlelog: Data: 0.00MB + Index: 0.00MB
wp_wfvulnscanners: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_ir: Data: 0.02MB + Index: 0.00MB
wp_woo_iran_cities_by_hannanstd: Data: 0.23MB + Index: 0.00MB
wp_wpclone: Data: 0.00MB + Index: 0.00MB
wp_wpmelon_advbedit_temp: Data: 0.01MB + Index: 0.01MB
wp_wp_seo_404_links: Data: 6.06MB + Index: 6.11MB
wp_wp_seo_cache: Data: 0.00MB + Index: 0.00MB
wp_wp_seo_redirection: Data: 0.00MB + Index: 0.00MB
wp_wp_seo_redirection_log: Data: 0.00MB + Index: 0.00MB
wp_wysija_campaign: Data: 0.00MB + Index: 0.00MB
wp_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB
wp_wysija_custom_field: Data: 0.00MB + Index: 0.00MB
wp_wysija_email: Data: 0.03MB + Index: 0.00MB
wp_wysija_email_user_stat: Data: 0.00MB + Index: 0.00MB
wp_wysija_email_user_url: Data: 0.00MB + Index: 0.00MB
wp_wysija_form: Data: 0.00MB + Index: 0.00MB
wp_wysija_list: Data: 0.00MB + Index: 0.00MB
wp_wysija_queue: Data: 0.00MB + Index: 0.00MB
wp_wysija_url: Data: 0.00MB + Index: 0.00MB
wp_wysija_url_mail: Data: 0.00MB + Index: 0.00MB
wp_wysija_user: Data: 0.54MB + Index: 0.27MB
wp_wysija_user_field: Data: 0.00MB + Index: 0.00MB
wp_wysija_user_history: Data: 0.00MB + Index: 0.00MB
wp_wysija_user_list: Data: 0.09MB + Index: 0.09MB
wp_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 7323
cfs: 5
gf_live_preview: 1
json_consumer: 1
mc4wp-form: 2
nav_menu_item: 96
page: 26
partner: 1
popup: 1
popup_theme: 6
post: 594
product: 1859
product_variation: 3645
redirect_rule: 22
revision: 273
robo_gallery_table: 1
shop_coupon: 1
shop_order: 3301
shop_order_refund: 204
shop_webhook: 1
spucpt: 2
testimonial: 3
tm_global_cp: 3
vc_grid_item: 1
wpcf7_contact_form: 4
wysijap: 1

### Security ###

Secure connection (HTTPS): ❌فروشگاه شما از HTTPS استفاده نمی کند. اطلاعات بیشتر درباره HTTPS و SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

ووکامرس: توسط خودکار – 3.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
simple (simple-fr)
simple (simple-ar)
variable (variable)
variable (variable-fr)
variable (variable-ar)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

پایگاه فروشگاه: 8 - /shop/
سبد خرید: 22 - /cart/
پرداخت: 10 - /checkout/
حساب کاربری من: 24 - /my-account/
شرایط و ضوابط: 12303 - /%d9%82%d9%88%d8%a7%d9%86%db%8c%d9%86-%d9%88-%d9%85%d9%82%d8%b1%d8%b1%d8%a7%d8%aa/

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – اگر شما در حال ویرایش و شخصی سازی ووکامرس روی قالب والد هستید پیشنهاد می کنیم از قالب فرزند استفاده کنید. ببینید : چگونه یک قالب فرزند بسازیم
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by salar90** [comment]
for more information you can simply diff the WC-3.1 and WC-3.2 version of this file:
`woocommerce/assets/js/flexslider/jquery.flexslider.js`

see the RTL supporting code has been removed.

**Comment by mikejolley** [comment]
Looks like it was custom in our version @jeffikus 

https://github.com/woocommerce/woocommerce/compare/release/3.1...release/3.2#diff-ad8687d554accb5f30b1ac19f85c36ba

We should update it again and file a PR for flexslider.

**Comment by jeffikus** [comment]
@mikejolley I can set some time aside on Friday to look at this?

**Comment by geeklore** [comment]
Similar report in LiveChat. Site is in Hebrew and the Featured Image is hidden. Switch to English and it shows as expected.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17263

**Comment by jeffikus** [comment]
@mikejolley have started, will have to continue on Monday.

**Comment by ahmedadelnew** [comment]
@mikejolley @jeffikus 

I have the same problem in Woocommerce 3.4.1 when changing site language to Arabic
this is my problem link
https://wordpress.org/support/topic/product-page-main-image-not-appear-with-rtl-mode/
and found @amerabdo get the same issue and this is his problem link
https://github.com/woocommerce/woocommerce/issues/20311

![40738458-e92c635e-6443-11e8-89a1-e7ab3788f5a5](https://user-images.githubusercontent.com/39780418/40753416-46090dcc-6474-11e8-935b-512436cf5272.jpg)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39780418/40753417-462f1fb2-6474-11e8-8651-cec45ee91450.gif)
