### ISSUE TITLE
Update notification "major" wording

### ISSUE THREAD

**Issue by douglsmith** [woocommerce/woocommerce#17216]
The new update notification for plugins is showing "this is a major update" even for the minor update from 3.2.0 to 3.2.1.

<img width="992" alt="screen shot 2017-10-14 at 11 21 34 am" src="https://user-images.githubusercontent.com/2446310/31577334-33f1d138-b0d2-11e7-8ddc-93a566554276.PNG">

**Comment by claudiulodro** [comment]
That modal should only show during major updates and not minor or patch updates.

**Comment by nishitlangaliya** [comment]
Hi @claudiulodro,

What should be check to confirm that weather the update is major or minor ? I mean criteria of version check.

Thanks

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/17245
