### ISSUE TITLE
Woocommerce Pay for Payment

### ISSUE THREAD

**Issue by fogunkoya** [woocommerce/woocommerce#17214]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install Woocommerce pay for payment plugin
2. Add a booking fee for card payments
3. Add product to cart

## Expected/actual behavior

The booking fee should be shown with subtotal then added to form order total

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

### WordPress Environment ###

</details>

**Comment by mikejolley** [comment]
Hi,

We don't maintain that payment plugin. The forum for that is here: https://wordpress.org/support/plugin/woocommerce-pay-for-payment

Fees in general are not added to subtotal, they are added below the subtotal as a totals line and then added to the grand total.

Thanks
