### ISSUE TITLE
Version 3.2.0 prevent caching for logged-in users in WP Rocket

### ISSUE THREAD

**Issue by Tabrisrp** [woocommerce/woocommerce#17210]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x ] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Activate WooCommerce and WP Rocket with user cache option
2. Navigate on front-end, no cache is created
3. When commenting `add_filter( 'nocache_headers', array( __CLASS__, 'set_nocache_constants' ) );` in `WC_Cache_Helper`, cache is created correctly

## Expected/actual behavior

Hi I'm WP Rocket lead developer.

Cache is supposed to work except for cart/checkout/account page. Since the change in this commit af1dce35446e6b3fbdf3006d25f9730bb85e1e01 the cache for logged-in user doesn't work anymore.

This is because the `nocache_headers` hook filter is used in `wp_get_nocache_headers()`, which in turn is used by `WP::send_headers()` like this:

```
if ( is_user_logged_in() )
        $headers = array_merge($headers, wp_get_nocache_headers());
}
```

So with the change, you're setting `DONOTCACHEPAGE` to true whenever someone is logged-in, preventing the cache creation on regular pages too.

## Isolating the problem

- [ x ] This bug happens with only WooCommerce plugin active
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x ] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
@Tabrisrp Before I change anything maybe you can explain this to be better.

Looking at `wp_get_nocache_headers` (https://developer.wordpress.org/reference/functions/wp_get_nocache_headers/) the documentation states:

> Get the header information to prevent caching.

Our `set_nocache_constants` method does this by setting those constants to prevent caching. If these pages are really allowed to be cached, why does WP bother to call `wp_get_nocache_headers()`? Are we really in the wrong here?

**Comment by Tabrisrp** [comment]
I understand where you're coming from with that, and why WP by default would want to prevent browser caching.

Still, preventing caching for all pages when logged-in is, in my opinion and experience, too much.

Our customers using this feature have their pages identical to the not logged-in version, and also the special pages that should never be cached are excluded by default in WP Rocket, so they're benefiting from a quicker websites for their own customers without issue in term of WooCommerce functionalities.

We can't tell them overnight that WooCommerce decided there should not be cache when logged-in and the feature they used will not work anymore.

I'd rather work out a middle ground solution with you on this, instead of unregistering the new filter in our plugin to be sure our feature still work for our customers.

**Comment by mikejolley** [comment]
I guess the question is; is WP **supposed** to be disabling caching on these requests, if so why, and if so is it something that should be respected or configured from caching plugins. 

If we removed this code entirely, would plugins like yours try to cache dynamic pages like cart/checkout? Whats the best way to prevent this?

I reckon we could do this conditionally, but I'd need to look into it.

**Comment by Tabrisrp** [comment]
For WP Rocket, even before you added this code, we automatically excluded the cart/checkout/account pages, and any page using a query string (like the add-to-cart one), to prevent any issue. This is true for logged-in and non logged-in users.

And also, for our plugin, the cache for logged-in users is off by default, the admin can decide to activate it in the settings.

Adding the `DONOTCACHEPAGE` constant for those pages is a standard, and I think most caching plugins comply with that. For the others pages, I think deciding to activate or not caching for logged-in users is up to the admin & the caching plugin they use.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17244

**Comment by Tabrisrp** [comment]
thank you!
