### ISSUE TITLE
Getting serialization error with REST API getting orders.

### ISSUE THREAD

**Issue by novashorts** [woocommerce/woocommerce#17222]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by novashorts** [comment]
I have been using WooCommerceNET also on Github for a long time using version 2 of REST API.  This recent release has broken some thing with getting orders.

There was an error deserializing the object of type System.Collections.Generic.List`1[[WooCommerceNET.WooCommerce.v2.Order, WooCommerceNET, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null]]. End element 'value' from namespace '' expected. Found element 'id' from namespace ''.

**Comment by mikejolley** [comment]
same as https://github.com/woocommerce/woocommerce/issues/17223 I think
