### ISSUE TITLE
Product zoom only show default product for variable product on WC 3.2.1

### ISSUE THREAD

**Issue by sayful1** [woocommerce/woocommerce#17227]
Product zoom not working for variable product. On product single page, when I change product variation and hover on product image it only show default product.

I also found a javaScript error on browser console.

```
Uncaught TypeError: Cannot read property 'flexAnimate' of undefined
    at a.fn.init.e.fn.flexslider (jquery.flexslider.min.js?ver=2.6.3:1)
    at t.onResetSlidePosition (single-product.min.js?ver=3.2.1:1)
    at HTMLDivElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDivElement.r.handle (jquery.js?ver=1.12.4:3)
    at Object.trigger (jquery.js?ver=1.12.4:3)
    at Object.a.event.trigger (jquery-migrate.min.js?ver=1.4.1:2)
    at HTMLDivElement.<anonymous> (jquery.js?ver=1.12.4:3)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.trigger (jquery.js?ver=1.12.4:3)
```

I check deactivate all plugin except WooCommerce. I also check with Storefront theme.

**Comment by mikejolley** [comment]
This is working my side. We need systems status and example URL or this will be closed.

Thanks

**Comment by sayful1** [comment]
My site still not available for public. So you cannot access it. But server information as follow.`

### WordPress Environment ###

WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 7.0.22-0ubuntu0.16.04.1
PHP Post Max Size: 256 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WP Offload S3 Lite: by Delicious Brains – 1.2
Amazon Web Services: by Delicious Brains – 1.0.3
WooCommerce: by Automattic – 3.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #1446 - /shop/
Cart: #39 - /cart/
Checkout: #40 - /checkout/
My account: #41 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Can you make it public? Without this I cannot verify an issue. As I said, no JS errors my side.

**Comment by Arry76** [comment]
Hi Mike,
I also come across the same javaScript error on browser console.  Site is public, here is a link to a product;
https://www.clath.uk/product/norse-projects-niels-standard-t-shirt-black/ 
Regards,
Aaron.

**Comment by mikejolley** [comment]
Looks like cache needs to be cleared - the script is https://www.clath.uk/wp-content/cache/busting/1/wp-content-plugins-woocommerce-assets-js-flexslider-jquery.flexslider.min-2.6.3.js

**Comment by theictgirl** [comment]
Same issue here: https://shop.vanmaanenvakantiehuizen.nl/product/wit-mannen-polo-shirt/
Have changed theme, disabled plugins, no caching available as far as I know.

**Comment by mikejolley** [comment]
https://wordpress.org/support/topic/product-gallery-issue-with-variants/ confirmed

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17263
