### ISSUE TITLE
Woocommerce - Tax function is broken

### ISSUE THREAD

**Issue by Miq84** [woocommerce/woocommerce#17221]
Hi,

Changed a field in the taxes area in Woocommerce, I think it was (no_tax_included) not sure but now its broke

`
### WordPress Environment ###

Home URL: https://sextoysbooth.com
Site URL: https://sextoysbooth.com
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.0.19
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.19.1 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.9
WC Database Prefix: wp_
Totale databasegrootte: 165.86MB
Database datagrootte: 123.94MB
Database index grootte: 41.92MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.06MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 4.03MB + Index: 2.48MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.05MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.52MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.05MB + Index: 0.00MB
wp_postmeta: Data: 86.17MB + Index: 26.17MB
wp_posts: Data: 21.30MB + Index: 8.05MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.08MB + Index: 0.00MB
wp_revslider_slides: Data: 0.33MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.08MB + Index: 0.06MB
wp_terms: Data: 0.06MB + Index: 0.03MB
wp_term_relationships: Data: 9.02MB + Index: 4.50MB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB

### Post Type Counts ###

attachment: 20177
custom_css: 1
customize_changeset: 54
nav_menu_item: 235
page: 123
portfolio: 17
post: 35
product: 8006
revision: 190
shop_coupon: 2
staff: 15
templatera: 1
testimonials: 10
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Cache Enabler: door KeyCDN – 1.2.2
Contact Form 7: door Takayuki Miyoshi – 4.9
WPBakery Visual Composer: door Michael M - WPBakery.com – 5.1.1
Slider Revolution: door ThemePunch – 5.4.3.1
SSL Insecure Content Fixer: door WebAware – 2.4.0
Templatera: door WPBakery – 1.1.12
WooCommerce: door Automattic – 3.2.1
WordPress Importeerder: door wordpressdotorg – 0.6.3
Yoast SEO: door Team Yoast – 5.6.1
WP All Import Pro: door Soflyy – 4.5.0
WP Fastest Cache: door Emre Vona – 0.8.7.3
WP All Import - WooCommerce Add-On Pro: door Soflyy – 2.3.7 – Niet getest met de actieve versie van WooCommerce
WP All Import - Yoast WordPress SEO Add-On: door Soflyy – 1.1.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #39899 - /
Winkelmand: #41 - /winkelwagen
Afrekenen: #42 - /checkout
Mijn account: #43 - /my-account
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Total
Version: 4.2.1
Author URL: https://themeforest.net/user/wpexplorer
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Archive Template: Jouw thema heeft een woocommerce.php bestand. Je zal het woocommerce/archive-product.php template niet kunnen overschrijven omdat woocommerce.php prioriteit heeft over archive-product.php. Dit is bedoeld om weergave-problemen te voorkomen.
Overrides: Total/woocommerce/archive-product.php
Total/woocommerce/content-product.php
Total/woocommerce/content-widget-product.php
Total/woocommerce/loop/loop-start.php
Total/woocommerce/loop/pagination.php
Total/woocommerce/single-product/add-to-cart/variable.php
Total/woocommerce/single-product/title.php

`
![1](https://user-images.githubusercontent.com/32822437/31588867-6083f3e4-b1f8-11e7-8a15-a5c7fe57a469.JPG)

**Comment by mikejolley** [comment]
no_tax_included is not a setting, and the fatal errors your screenshot are coming from wp-all-import.

Please explain the actual issue in more detail. i.e. what is broken, what steps you're taking etc.

**Comment by Miq84** [comment]
Hi Mike,

I went to the settings woocommerce then to the tab Taxes and changed the field where they say (manually type what you want behind the Tax, for example Tax included"

I entered not_included_tax in that specific field and from the I cannot acces the tax field in Woocommerce

![knipsel](https://user-images.githubusercontent.com/32822437/31633378-7ee7f646-b2c0-11e7-8eb9-0e1936416002.JPG)

**Comment by mikejolley** [comment]
What did you type in the field exactly? `(`?

**Comment by Miq84** [comment]
Dont now exactly

If I had a clean Woocomerce I could show you because when I hovered it says something about "or you can fill in no_tax_included" also with the underscores so that is what I entered and then I didn't had the option anymore to change it deleted it or see the other settings

**Comment by mikejolley** [comment]
I'll look into it.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17247
