### ISSUE TITLE
REST API getting order mata_data part is empty

### ISSUE THREAD

**Issue by yloz** [woocommerce/woocommerce#17223]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. 
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

since the last update rest api v2 gives back empty order meta_data.
in previous versions it gave back all data stored there (custom checkout fields, pro-forma bill details, etc...).
sample:

...

	"date_paid_gmt": null,
	"date_completed": null,
	"date_completed_gmt": null,
	"cart_hash": "11f8d3f0ecfb9531b10017c255d2dd0d",
	"meta_data": [{
		
	},
	{
		
	},
	{
		
	},
	{
		
	}],
	"line_items": [{
		"id": 83,
		"name": "asdf",
		"product_id": 0,
		"variation_id": 0,
		"quantity": 4,
		"tax_class": "",
		"subtotal": "12441",
		"subtotal_tax": "3359",
		"total": "12441",
		"total_tax": "3359",
		"taxes": [{
			"id": 1,
			"total": "3359.0592",
			"subtotal": "3359.0592"
		}],
		"meta_data": [],
		"sku": null,
		"price": 3110.24
	},
...

I was expecting to see...

i shold see there the key, value pairs.

(not deserialization problem. checked the recieved string and missing there too.)

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
WooCommerceNET.WooCommerce.v2.Order, WooCommerceNET

</details>

**Comment by mikejolley** [comment]
Meta data is fine - check in your client.

```
"meta_data": [
		{
			"id": 1199,
			"key": "_order_stock_reduced",
			"value": "yes"
		},
		{
			"id": 1200,
			"key": "_download_permissions_granted",
			"value": "yes"
		}
	],
```

https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

This seems specific to the NET library you're using so check there.

**Comment by yloz** [comment]
checked it with postman. still empty.

![pic](https://user-images.githubusercontent.com/32835654/31629426-e05b64b0-b2b3-11e7-8672-ee696188b664.png)

with phpmyadmin i see them all

![image](https://user-images.githubusercontent.com/32835654/31629864-2c84a0ee-b2b5-11e7-9889-3d2942900a09.png)

before the last update it worked fine.

**Comment by claudiosanches** [comment]
@yloz using WooCommerce 3.2.1?

**Comment by yloz** [comment]
yes 3.2.1 and the wp is 4.8.2. with an up to date divi child the.

**Comment by mikejolley** [comment]
This was a bug in 3.2-RC/beta. It was fixed.

**Comment by claudiosanches** [comment]
@yloz please check again or try to reinstall, because we fixed it already.

**Comment by yloz** [comment]
i think i found it.
it will be a wordpress and php version issue. :(
wp_json_encode fails on php 5.4.45.

**Comment by claudiosanches** [comment]
@yloz `wp_json_encode()` is made to not fail in any PHP version, that's why the function exists... And in this particular issue is only possible to reproduce using a not patched version of WooCommerce, like on WooCommerce 3.1 or 3.0.

**Comment by yloz** [comment]
@claudiosanches 

i know that, but something changed.
if i skip this lines it works as before.

//	try {
//		$args[0] = _wp_json_sanity_check( $data, $depth );
//	} catch ( Exception $e ) {
//        return false;
//	}

**Comment by yloz** [comment]
wp-inculudes/functions.php function wp_json_encode( $data, $options = 0, $depth = 512 ) {...}

return var_dump($args[0]["meta_data"]); //it's OK
	try {
		$args[0] = _wp_json_sanity_check( $data, $depth );
	} catch ( Exception $e ) {
        return false;
	}

array(20) {
  [0]=>
  object(WC_Meta_Data)#13471 (2) {
    ["current_data":protected]=>
    array(3) {
      ["id"]=>
      int(9063)
      ["key"]=>
      string(16) "_billing_kerulet"
      ["value"]=>
      string(0) ""
    }
    ["data":protected]=>
    array(3) {
      ["id"]=>
      int(9063)
      ["key"]=>
      string(16) "_billing_kerulet"
      ["value"]=>
      string(0) ""
    }
  }
  [1]=>
  object(WC_Meta_Data)#13476 (2) {
    ["current_data":protected]=>
    array(3) {
      ["id"]=>
      int(9064)
      ["key"]=>
      string(24) "_billing_kozterulet_neve"
      ["value"]=>
      string(6) "rtzrtz"
    }
    ["data":protected]=>
    array(3) {
      ["id"]=>
      int(9064)
      ["key"]=>
      string(24) "_billing_kozterulet_neve"
      ["value"]=>
      string(6) "rtzrtz"
    }
  }
.... contains all data

	try {
		$args[0] = _wp_json_sanity_check( $data, $depth );
	} catch ( Exception $e ) {
        return false;
	}
return var_dump($args[0]["meta_data"]); //it's NOT OK

array(20) {
  [0]=>
  object(stdClass)#13448 (0) {
  }
  [1]=>
  object(stdClass)#13386 (0) {
  }
  [2]=>
  object(stdClass)#13435 (0) {
  }
  [3]=>
  object(stdClass)#13429 (0) {
  }
  [4]=>
  object(stdClass)#13474 (0) {
  }
.... empty objects

**Comment by yloz** [comment]
PHP 5.6 solved the issue.
thank you for the help!

**Comment by claudiosanches** [comment]
@yloz well, if the problem is with a WordPress funcion in an specific PHP version, so you should report it on the WordPress core Trac, for sure they will be happy to fix it.

**Comment by razorsharpshady** [comment]
@yloz  thanks man, I was having the same issue. 
on local it was working but not on live server.  And you are right it is a problem with wp_json_encode().
