### ISSUE TITLE
REST API return 401 error!

### ISSUE THREAD

**Issue by shangdev** [woocommerce/woocommerce#17225]
Detail:
` $.post( '/wp-json/wc/v2/products/' + $post_id, {'menu_order': $menu_order}, function (data) {
         console.log(data);
 } );`
`{"code":"woocommerce_rest_cannot_edit","message":"Sorry, you are not allowed to edit this resource.","data":{"status":401}}`

and.
The REST API has been enabled.

WooCommerce version:3.2.1;
WordPress version:4.8.2;

**Comment by mikejolley** [comment]
It means you're not using auth correctly. See https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API and run though those examples to ensure it's working and API keys etc are correct.
