### ISSUE TITLE
No shipping method id when adding manual orders

### ISSUE THREAD

**Issue by tonybahama** [woocommerce/woocommerce#17238]
Hi!

When creating and editing orders manually the shipping method id is not added. This makes is difficult to filter exports to different couriers based on method_id. 
Solution 1: save method title to meta, not just as "order item name"
Solution 2: introduce a normal shipping editing on the backend. Why do we have to manually enter the method title anyways? It is already defined what is available.

<img width="773" alt="screen shot 2017-10-16 at 22 49 13" src="https://user-images.githubusercontent.com/19731470/31634686-a6f61e3e-b2c4-11e7-9a9f-88bac4dc6356.png">
<img width="467" alt="screen shot 2017-10-16 at 22 49 06" src="https://user-images.githubusercontent.com/19731470/31634687-a7115d5c-b2c4-11e7-9dda-199924cde58b.png">

**Comment by mikejolley** [comment]
Method ID is stored to the order item meta. In your case, method id is 'flat_rate'. I've confirmed this is set for manual orders.

If you mean instance ID, we're going to standardise how it gets stored in https://github.com/woocommerce/woocommerce/issues/16912, but manual orders won't get this because shipping quotes are not generated by WC in the admin area so there is no way to know what instance ID to choose/set.

> Why do we have to manually enter the method title anyways? It is already defined what is available.

Mainly so you can control which method you want or add notes, since there is no 'quote' system in the backend. That may come in a future update, but it's not a priority right now and doesn't appear to have had much demand.

Hope this makes sense.

**Comment by tonybahama** [comment]
Thanks for the answer!

It still does not solve the problem, which is that we cannot differentiate couriers since they are all flat rate. This gives an error and cannot export to the correct slot.
The only way to solve this is to _not_ use the basic Shipping Methods and hack together different methods for different couriers.
But that is not convenient.

Same goes for the notes. I do not know how many users take advantage of this flexibility. That is what "customer notes" are for.
Every time we create/modify shipping and this is the same for every single Woo user I suppose we *have to* manually *type* the method title. That is human error possibility right there. That is lack of efficiency for the sake of 0.01% of flexibility. You can add custom notes to the shipping, that is what meta is used for, anyone can add a custom meta field.

I am not talking about quoting, the price does not have to be calculated automatically, that is fair. I am talking about unnecessary typing.

**Comment by tonybahama** [comment]
Okay!

Will it be possible to select instance as well on the admin?

Üdv,
K.Szabó Levente

**Comment by mikejolley** [comment]
I'm not sure how workable it would be. Potentially yes, but it would be a long list of all zone methods. Could be grouped by zone. Maybe worth sending an experimental PR?

**Comment by tonybahama** [comment]
The thing is, I am not a dev myself just love Woo and love having an efficient store.

If there is someone with this issue as well I hope others can join too.

**Comment by jnicotra** [comment]
I am having this issue also. It USED to work no problem. Now since the new update the shipping method only shows the title and not the description. This is important for us as it will send the customer information on the shipping details.

For example: 

When we create a manual order in the admin, we will select the shipping type as "Free Shipping". Previously this would send the email with the full info of "Free Shipping: 7-10 Business Days"

How do we bring this functionality back?

**Comment by mikejolley** [comment]
It never was functionality... Certainly not since zones existed.

**Comment by jnicotra** [comment]
Respectfully, 

I have kept up-to-date with the releases of Woocommerce within 2 weeks of release consistently. I am not sure WHY this happened in this way, but what I CAN assure you of, is that it DID work in this way. At least before 3.2

I understand if it was never intended functionality, but it did operate in this way. Myself and others would not be raising this issue if something had not changed.

Prior to 3.2 the shipping method chosen in the back-end would show the TITLE of that shipping method (based on the zones).
After 3.2 selecting the shipping only shows the shipping type, not the title.

We have a shipping zone for the contiguous United States, the only shipping method available by that zone is titled "Free Shipping: 7-10 Business Days". The only other zone we have is for the rest of the world. 

The other shipping methods we have are USPS and DHL. 

Again, when entering the order in admin it will only show as "Free Shipping", not by the title. The other shipping methods (USPS and DHL) are also options and will thus show those titles.

Will there be a resolution or workaround for this issue?

**Comment by mikejolley** [comment]
Well the other person was making a feature request - not asking something to be put back. Shipping did not change in 3.2, and afaik you've never been able to choose an INSTANCE there, just a method e.g. flat rate.

**Comment by tonybahama** [comment]
Acutally my request was fulfilled prior to WC 2.6 when new shipping zones etc was introduced. We just selected what method we use, with every data, nothing to mess up. Now the problem is that on the backend we **lack** a lot of functions we have on the front end. 

This is a perfect place for human error, and also right now we are technically not able to export orders to different couriers.

We have a 
- flat_rate:1 --> MPL
- flat_rate:2 --> GLS

But on the admin orders (or basically ANY SHIPPING CHANGE) just saves flat:rate. We cannot differentiate those orders any more. So when we export we just don't know what the customer originally selected.

**Comment by mikejolley** [comment]
As I said earlier, we don't get quotes in the backend. You can get your quote externally and TYPE the price and method title. This is not limited right now.

> So when we export we just don't know what the customer originally selected.

Your export could pull the title and method if it was coded to do so..

**Comment by jnicotra** [comment]
I just purchased this plugin to solve my issue, and it seems to work very well:
http://ignitewoo.com/woocommerce-extensions-plugins-themes/woocommerce-phone-orders-manual-orders/

@tonybahama 
perhaps this would solve your issue also?

@mikejolley 
Is there any hope for a similar solution made native to woocommerce? An order screen like this? It would remove many issues with manual orders and would remove the need for another plugin.

Thank you for your help so far

**Comment by mikejolley** [comment]
We're hoping to have shipping quotes in the backend in the future, but our priority is performance improvements for the next quarters.

**Comment by tonybahama** [comment]
@jnicotra Does not help, still cannot modify orders. I am happy that you solved your issue though, good luck!

@mikejolley Sure, that was clear. I just thought there might be a solution until then. Yes, I am aware of that, I am a big fan of performance myself!

**Comment by tousif123** [comment]
Is there any way of achieving this

**Comment by jnicotra** [comment]
@tousif123 
I haven't found any other way than the manual orders I mentioned before unfortunately.

If anyone else has found a better solution, I'd love to hear it as well.

**Comment by JapeNZ** [comment]
Any update on this?
