### ISSUE TITLE
Woocommerce tablet issue

### ISSUE THREAD

**Issue by Kenmercermusic** [woocommerce/woocommerce#17230]
Woocommerce plugin is not working when a customer makes a purchase for a digital download with an iPad or Samsung tablet. The purchase goes through without issues but the download is not given.

**Comment by mikejolley** [comment]
Hi,

Browser or device has no effect on the generation of downloads - that part is all server side. Sounds like they just hit the confirmation step before payment was confirmed and download generation was complete.

Please remember when you log issues we need full steps to reproduce an issue, and status reports etc. It also needs to be reproducible with core only (ruling out extensions).

The new issue form lists everything that should be done. Let me know if you can reproduce a bug after going through everything there.

Thanks

**Comment by myvcc657** [comment]
`reslove`
