### ISSUE TITLE
Broke grouped product sync price method on Data Store class

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#17239]
Since 3.0 we are not using `post_parent` for grouped products:

> * Grouped products are linked from the parent rather than the children. Children can be in more than one group.

Still in your `WC_Product_Grouped_Data_Store_CPT->sync_price` still try look for `post_parent`:

https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-grouped-data-store-cpt.php#L66-L92

Or maybe this code just need to be removed.

**Comment by nishitlangaliya** [comment]
@claudiosanches ,

Do you mean just to remove `post_parent' => $product->get_id()` from argument  from $children_ids array ? 

Thanks.

**Comment by claudiosanches** [comment]
@nishitlangaliya no, need to be deprecated the entire method, and other methods that use it.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17259
