### ISSUE TITLE
When a order is moved to trash no status icon is displayed

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#17246]
![orders themegrill wordpress](https://user-images.githubusercontent.com/3774827/31647429-d6abe9f2-b327-11e7-948c-8cd65e780f9e.png)

**Comment by mikejolley** [comment]
Trashed orders have no status; the post status is 'trashed'. The original status is not present. This is being revised in https://github.com/woocommerce/woocommerce/pull/16700 anyhow.
