### ISSUE TITLE
Order total miscalculated 

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce#17248]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a simple product with rate as $4.79
2. Create the tax settings like this ![](http://cld.wthms.co/MngxJx+)
3. Create a flat rate shipping cost like this ![](http://cld.wthms.co/2wgVd+)
4. Now let's execute an order like this for destination `Quebec J1R 0B5`
5. Here is what we get with a rate difference ![](http://cld.wthms.co/NNPXRz+)
6. This is difference is causing issue with external payment gateways like PayPal advanced

## Expected/actual behavior

When I follow those steps, I was expecting to see $8.94

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

### WordPress Environment ###

Home URL: https://woocommerce.mystagingwebsite.com
Site URL: https://woocommerce.mystagingwebsite.com
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.24
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.56.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
Total Database Size: 29.22MB
Database Data Size: 18.39MB
Database Index Size: 10.83MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.14MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 1.52MB + Index: 0.05MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_aryo_activity_log: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.14MB + Index: 0.03MB
wp_comments: Data: 0.19MB + Index: 0.09MB
wp_email_log: Data: 0.33MB + Index: 0.00MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.09MB + Index: 0.09MB
wp_popover_ip_cache: Data: 0.02MB + Index: 0.02MB
wp_postmeta: Data: 6.08MB + Index: 6.05MB
wp_posts: Data: 2.08MB + Index: 0.16MB
wp_pv_commission: Data: 0.02MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.05MB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_comments: Data: 0.05MB + Index: 0.08MB
wp_tmp_update_email_log: Data: 0.08MB + Index: 0.00MB
wp_tmp_update_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_tmp_update_followup_customer_carts: Data: 0.03MB + Index: 0.03MB
wp_tmp_update_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_followup_email_orders: Data: 0.17MB + Index: 0.09MB
wp_tmp_update_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_tmp_update_followup_followup_history: Data: 0.09MB + Index: 0.05MB
wp_tmp_update_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_links: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_options: Data: 0.28MB + Index: 0.05MB
wp_tmp_update_postmeta: Data: 0.31MB + Index: 0.30MB
wp_tmp_update_posts: Data: 0.16MB + Index: 0.09MB
wp_tmp_update_pv_commission: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_termmeta: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_terms: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_usermeta: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_users: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfConfig: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfFileMods: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfHits: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfStatus: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wp_tmp_update_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_tmp_update_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_usermeta: Data: 0.08MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.02MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 0.02MB + Index: 0.00MB
wp_wfHits: Data: 0.02MB + Index: 0.03MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfStatus: Data: 0.02MB + Index: 0.03MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_wrd_discounts: Data: 0.02MB + Index: 0.02MB
wp_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 218
bookable_resource: 1
carts: 2
course: 1
follow_up_email: 18
global_product_addon: 1
inc_popup: 1
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
lesson: 1
nav_menu_item: 11
order_shipment: 2
page: 34
paypal_ipn: 2
post: 6
product: 2
project: 1
quiz: 1
revision: 98
scheduled-action: 7
shop_coupon: 1
shop_order: 214
shop_order_refund: 1
shop_subscription: 24
shop_webhook: 1
slide: 1
tt_font_control: 1
wc_booking: 4
wc_membership_plan: 1
wc_order_status: 8
wc_product_retailer: 3
wc_product_tab: 4
wc_user_membership: 1
wc_voucher: 2
wc_voucher_template: 2
wc_zapier_feed: 1
wccc: 1
wishlist: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Email Log: by Sudar – 2.2.0
Server-Mail-Check: by praveen – 1.0
Test Payment Module for Woocommerce: by Sean Barton (Tortoise IT) – 1.5 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2 - /
Cart: #3 - /cart/
Checkout: #5 - /checkout/
My account: #77 - /my-account/
Terms and conditions: #820 - /subscribe-to-our-dental-plan-click-here-for-more-info/

### Theme ###

Name: Beaver Builder Theme
Version: 1.6.2
Author URL: http://www.wpbeaverbuilder.com/?utm_medium=bb-pro&utm_source=bb-theme&utm_campaign=themes-admin-page
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by mikejolley** [comment]
2.98*0.14975 = 0.446255
4.79*0.14975 = 0.7173025

0.7173025+0.446255 = 1.1635575

So tax is correct at 1.16.

4.79 + 2.98 + 1.16 = 8.93

This also matches.

You're expecting rounded taxes to be added together which is not what we do. You're viewing the individual line taxes rounded up causing a 1p discrepancy.

I compared this to v3.1 and it's the same, so this has not changed in 3.2.

Plugins like PayPal Advanced should check totals and handle 1p diffs if needed, if they need to send line items instead of a single total. Thats what we do in PayPal Pro.

Thanks
