### ISSUE TITLE
Rest API missing is_enabled for product variations.

### ISSUE THREAD

**Issue by warwolf** [woocommerce/woocommerce#17249]
The rest API for product variations is missing the "Enabled" property, currently you have to delete and add product variations instead if you want to temporarly remove a variation thru rest API.

Also when you get a variation that has no own SKU the parents SKU is recived instead.
However if you try to save the the exact data you did recive you will fail as you will get a duplicate SKU error.
Perhaps it would be good to be able to save the variation using the parents SKU.

**Comment by mikejolley** [comment]
Moved to https://github.com/woocommerce/wc-api-dev/issues/64 for feedback. Feel free to contribute there also.

**Comment by claudiosanches** [comment]
@warwolf you can do it using the `visible` param to enable or disable.
