### ISSUE TITLE
WooCommerce Cart shows TOTAL TAX instead of TOTAL PRICE

### ISSUE THREAD

**Issue by noboospj** [woocommerce/woocommerce#17250]
Hi, I have a strange behavior on our site. When a product is added to the cart, it's price is not displayed in the total price of items in the cart. Instead I can see a total tax calculated from the products in the cart, how to overcome this and fix it?

PS. You can observe this issue on https://mobelsport.pl

**Comment by rudilast** [comment]
The same behavior on our site : https://wereldprint.nl

This happened after the last woocommerce update tot 3.2.0 .

**Comment by noboospj** [comment]
We also use WPML and when we switch language it seems to work fine. Maybe there is a problem with configuration of taxes in Woo, however I tested a few variants and it did not help.

**Comment by rudilast** [comment]
Change the language is not the solution for our website unfortunately. I can't find a workaround for it.

**Comment by mikejolley** [comment]
The cart page is correct. The cart widget is not powered by WooCommerce. Thats the theme. I'm not sure what function is being used there but you should look at the template files/report to the author so they can investigate.

Thanks
