### ISSUE TITLE
Order payment_complete and update_status can result in partial order updates.

### ISSUE THREAD

**Issue by herregroen** [woocommerce/woocommerce#17251]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Currently still figuring out how exactly to reproduce the issue.

It seems related to the `save` function in `WC_Order` which is wrapped in a `try`, `catch` from `payment_complete`. The database update of the order itself will trigger, causing the order to update to completed while the notes and hooks from a status transition are not triggered.

We expect an error is raised during `save_items` which is caught by the catch block in `payment_complete` which then returns false.

Unfortunately not a single instance where `payment_complete` is used, beyond the tests, actually does anything at all with the return value thus this error is swallowed silently, the order itself is updated to completed but the associated note is never created and the associated actions never trigger.

## Expected/actual behavior

When I follow those steps, I see nothing at all. The error is swallowed silently.

I was expecting to see some kind of error log, a rollback of the order since the update failed or something of the like.

## Isolating the problem

The problem is endemic to the code of WooCommerce. Whenever `payment_complete` and `update_status` methods are called nothing is done with the return value even though this may be false.

Either these methods should have no return value and the error should be handled in the `catch` block, even if it's just by logging the error, or every single call to these methods should handle the return value.

**Comment by atimmer** [comment]
The results of this mean that the order completion results aren't correctly applied. Subscriptions are not set to `Active` and any other action that needs to happen isn't correctly executed.

**Comment by mikejolley** [comment]
I've merged that logging change, but I'll leave this open since those false return values should probably be handled with some kind of rollback if possible.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18175
