### ISSUE TITLE
Theming: <button> instead of <input>

### ISSUE THREAD

**Issue by myph** [woocommerce/woocommerce#17254]
It will be a good practice to use modern **`<button type="submit"></button>`** html semantics instead of  **`<input type="submit"/>`** in all frontend forms of WooCommerce.

The main reason that WP themes will have more control to customize `<button>` elements via CSS. It's possible add inner HTML content (`<span>`, `<strong>` or even `<img>`), and make use of `:after` and `:before` pseudo-element to achieve complex rendering while `<input>` only accepts a text value attribute.

At the moment all buttons are presented by `<a>`, `<buttons>`, `<input type="submit">`. It's okay to use `<a>`, but using of `<input type="submit">` is not consistent with `<button>`s. Also WooCommerce doesn't allow to change all buttons semantics via actions.

**Comment by mikejolley** [comment]
For us, some of our forms contain multiple actions. A good example is the cart form. This has an action for applying a coupon, and a button for updating the quantities. We need to know which "button" is pressed in order to handle the form correctly. So if this was changed we'd need to ensure that still functions.

Asking @jameskoster for feedback.

**Comment by jameskoster** [comment]
Consistency would be best, especially as some browsers can render these elements slightly differently regardless of whether they have identical style properties. That's in addition to the benefits highlighted in the OP.

We can't go _all in_ on `a` or `button` and will need to continue to use both, but replacing `input` buttons with `button` would be a win.

**Comment by myph** [comment]
Hello!

I checked all buttons in WooCommerce version 3.3 and found the button, which wasn't changed to a `<button>` instead of `<input>`. It's a "**Apply coupon**" button on the Cart page.

Hope you'll fix it in the next minor release.
