### ISSUE TITLE
Sort Orders by date modified

### ISSUE THREAD

**Issue by natesholland** [woocommerce/woocommerce#17262]
### EXPLANATION OF THE ISSUE

This is a feature request. We would like to see the ability to filter orders by date_modified instead of date created. I looked at the documentation and saw that there is an `after` parameter and an `orderby` parameter but both of these work on `date_created`. I would like to see a way to filter by `date_modified` since I think this would be useful for a number of integrations and would save us from having to make a bunch of extra calls to the WooCommerce API.

### STEPS TO REPRODUCE THE ISSUE

See [the documentation](http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders) for the current api endpoint.

### WHY WE SHOULD ADD THIS FEATURE

I think that this would be a useful thing to have for multiple use cases.
The current use case I have is that I would like to look at a list of orders modified after a certain point.
This could additionally be useful for integrations with products so that they could check for changes in a product catalog without having to scan the entire product catalog again.
It looks like one way to solve this would be to put in a code change around [here](https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/abstracts/abstract-wc-rest-crud-controller.php#L544) to add the ability to filter by `date_modified`.

Additionally this change can be an addition to the existing API and is not a breaking change so it wouldn't require any versioning issues and wouldn't break anyone's existing integrations.

I requested this a few months ago and you all said you wanted to work on it. So I'm making a new ticket to see what the progress is since I've had no response on the old ticket and it got closed without being worked on.

**Comment by claudiosanches** [comment]
Moved to your feature plugin for REST API v3.
Thanks for your suggestion.

https://github.com/woocommerce/wc-api-dev/issues/65
