### ISSUE TITLE
wc_add_order_item_meta not working in 3.2.1

### ISSUE THREAD

**Issue by plinnet** [woocommerce/woocommerce#17261]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. wc_add_order_item_meta($key, 'product_label', $meta_value); does not result in any value being added in metadata for the orderitem. Updating to WC 3.2.1 from version 3.2.0 was all I did

## Expected/actual behavior
wps6_woocommerce_order_itemmeta did not contain the added metadata
When I follow those steps, I see...

I was expecting to see...
wps6_woocommerce_order_itemmeta containing the metadata

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://navnelabels.nu
Site URL: https://navnelabels.nu
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wps6_
MaxMind GeoIP Database: ✔
Total databasestørrelse: 6.23MB
Database datastørrelse: 4.54MB
Database indexstørrelse: 1.69MB
wps6_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wps6_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wps6_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wps6_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wps6_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wps6_woocommerce_order_itemmeta: Data: 0.17MB + Index: 0.14MB
wps6_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wps6_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wps6_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wps6_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wps6_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wps6_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wps6_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wps6_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wps6_b2t_backgroundpic: Data: 0.02MB + Index: 0.00MB
wps6_b2t_backgroundtabs: Data: 0.02MB + Index: 0.02MB
wps6_b2t_fonts: Data: 0.02MB + Index: 0.02MB
wps6_b2t_iconpic: Data: 0.02MB + Index: 0.00MB
wps6_b2t_icontabs: Data: 0.02MB + Index: 0.02MB
wps6_b2t_labelfonts: Data: 0.02MB + Index: 0.00MB
wps6_b2t_labels: Data: 0.02MB + Index: 0.02MB
wps6_commentmeta: Data: 0.08MB + Index: 0.09MB
wps6_comments: Data: 0.28MB + Index: 0.09MB
wps6_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wps6_feedmanager_channel: Data: 0.02MB + Index: 0.03MB
wps6_feedmanager_country: Data: 0.02MB + Index: 0.03MB
wps6_feedmanager_errors: Data: 0.02MB + Index: 0.00MB
wps6_feedmanager_feed_status: Data: 0.02MB + Index: 0.03MB
wps6_feedmanager_field_categories: Data: 0.02MB + Index: 0.00MB
wps6_feedmanager_product_feed: Data: 0.02MB + Index: 0.02MB
wps6_feedmanager_product_feedmeta: Data: 0.02MB + Index: 0.03MB
wps6_feedmanager_source: Data: 0.02MB + Index: 0.03MB
wps6_links: Data: 0.02MB + Index: 0.02MB
wps6_options: Data: 2.33MB + Index: 0.08MB
wps6_postmeta: Data: 0.17MB + Index: 0.11MB
wps6_posts: Data: 0.27MB + Index: 0.06MB
wps6_redirection_404: Data: 0.02MB + Index: 0.06MB
wps6_redirection_groups: Data: 0.02MB + Index: 0.03MB
wps6_redirection_items: Data: 0.02MB + Index: 0.08MB
wps6_redirection_logs: Data: 0.02MB + Index: 0.08MB
wps6_revslider_css: Data: 0.13MB + Index: 0.00MB
wps6_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wps6_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wps6_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wps6_revslider_slides: Data: 0.06MB + Index: 0.00MB
wps6_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wps6_termmeta: Data: 0.02MB + Index: 0.03MB
wps6_terms: Data: 0.02MB + Index: 0.03MB
wps6_term_relationships: Data: 0.02MB + Index: 0.02MB
wps6_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wps6_usermeta: Data: 0.08MB + Index: 0.03MB
wps6_users: Data: 0.02MB + Index: 0.05MB
wps6_woocommerce_scanpay_seq: Data: 0.02MB + Index: 0.02MB
wps6_wpeditor_settings: Data: 0.02MB + Index: 0.00MB
wps6_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wps6_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 344
nav_menu_item: 5
page: 11
post: 5
product: 1
revision: 79
shop_coupon: 3
shop_order: 51
shop_order_refund: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Autoptimize: af Frank Goossens (futtta) – 2.2.2
B2T Labels: af Peter Linnet – 1.0.10
CWS Builder: af  – 1.2.1
Disable XML-RPC: af Philip Erb – 1.0.1
Google Tag Manager for Wordpress: af Thomas Geiger – 1.7.1
Fusion Core: af ThemeFusion – 2.0.3
Invisible reCaptcha: af Mihai Chelaru – 1.1
Loco Translate: af Tim Whitlock – 2.0.16
Media Library Assistant: af David Lingren
Fair Trade Judaica – 2.62

Redirection: af John Godley – 2.7.3
SG Optimizer: af SiteGround – 3.3.3
WooCommerce Order Test: af WP Fix It – 1.4 – Ikke tested med den aktive version af WooCommerce
WooCommerce QuickPay: af Perfect Solution – 4.8.2 – Ikke tested med den aktive version af WooCommerce
WooCommerce TM Extra Product Options: af themecomplete – 4.5.4 – Ikke tested med den aktive version af WooCommerce
WooCommerce: af Automattic – 3.2.1
Yoast SEO: af Team Yoast – 5.6.1
WP Editor: af Benjamin Rojas – 1.2.6.3
WP Product Feed Manager: af Michel Jongbloed – 1.7.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: DKK (DKK)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop basisside: #6 - /shop/
Kurv: #7 - /cart/
Checkout: #8 - /checkout/
Min konto: #9 - /my-account/
Handelsbetingelser: #893 - /handelsbetingelser/

### Theme ###

Name: Happy Kids Child Theme
Version: 1.0.0
Author URL: http://www.creaws.com
Child Theme: ✔
Parent Theme Name: Happy Kids - Children WordPress Theme
Parent Theme Version: 3.4.4
Parent Theme Author URL: http://www.creaws.com
WooCommerce Support: ✔

### Templates ###

Overrides: happykids/woocommerce/archive-product.php
happykids-child/woocommerce/cart/cart.php
happykids-child/woocommerce/cart/mini-cart.php version 3.1.0 er udgået. Kerneversionen er 3.2.0
happykids-child/woocommerce/checkout/review-order.php
happykids/woocommerce/content-product.php
happykids/woocommerce/content-product_cat.php
happykids-child/woocommerce/content-single-product.php
happykids/woocommerce/loop/pagination.php
happykids-child/woocommerce/order/order-details-item.php
happykids-child/woocommerce/order/order-details.php version 3.0.0 er udgået. Kerneversionen er 3.2.0
happykids/woocommerce/single-product/product-image.php
happykids/woocommerce/single-product/product-thumbnails.php
happykids/woocommerce/single-product/tabs/tabs.php
happykids/woocommerce/single-product.php

Outdated Templates: ❌Lær hvordan man opdaterer
</details>

**Comment by mikejolley** [comment]
This is covered in unit tests https://github.com/woocommerce/woocommerce/blob/f1dab3fdce247a52f6452fe73a0259fd8d935030/tests/unit-tests/order-items/functions.php#L41

3.2.1 made no changes to the function from 3.2.

**Comment by plinnet** [comment]
Hi Mike,

Thanks for the feedback!!! It is much appreciated.

I will explore other avenues in order to solve my problem.
