### ISSUE TITLE
/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php 

### ISSUE THREAD

**Issue by vuchastyi** [woocommerce/woocommerce#17264]
An error occurred during the installation

```
Warning: call_user_func() expects parameter 1 to be a valid callback, no array or string given in /sata1/home/users/domplus/www/www.promobile.in.ua/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php on line 279
```

PHP 5.3, Apache2

**Comment by mikejolley** [comment]
I've checked this and all wizard steps have a 'view' callback. The only way this would happen is if an extension or custom code was filtering on `woocommerce_setup_wizard_steps` and removing the 'view' values or changing the callbacks. You didn't provide a system status report so I cannot see what you're running here.

https://github.com/woocommerce/woocommerce/pull/17267 will remove the notice.
