### ISSUE TITLE
Unable to created Taxonomy based Product Attributes programatically

### ISSUE THREAD

**Issue by parkinep** [woocommerce/woocommerce#17269]
I am unable to create Taxonomy based Product attributes in code using WC 3.X CRUD classes. Creating Product local text attributes works fine. I have created a script that, when run from the wordpress root, illustrates the issue by first attempting to add a Taxonomy attribute using CRUD classes, and then does it via WPs own taxonomy functions.

```php
<?php
require 'wp-load.php';
ini_set('display_errors', 1);
ini_set('html_errors', 0);
header("Content-Type: text/plain");

//Create new product
$p = new WC_Product_Simple();

$p->set_name('Testituote');

$p->set_regular_price(1);

//Get the taxonomy ID
$valmistaja_tax_id = wc_attribute_taxonomy_id_by_name('pa_valmistaja');

//Create the Product Attribute object
$v_a = new WC_Product_Attribute();
$v_a->set_id($valmistaja_tax_id);
$v_a->set_name('Valmistaja');
$v_a->set_options(array('wc_testivalmistaja'));
$v_a->set_visible(true);

$atts = array();
$atts['ds_valmistaja'] = $v_a;

$p->set_attributes($atts);

$p->save();

//Manually creating the taxonomy term
wp_insert_term('wp_testivalmistaja', 'pa_valmistaja');

//Manually assigning the term
wp_set_object_terms($p->get_id(), 'wp_testivalmistaja', 'pa_valmistaja', true);

echo "WC Attribute:".PHP_EOL;
print_r($p->get_attribute('ds_valmistaja')); //Returns nothing with either 'valmistaja' or 'pa_valmistaja' as the attribute name

echo "WP Attribute:".PHP_EOL;
print_r(wp_get_object_terms( $p->get_id(), 'pa_valmistaja' )); //Returns WP_Term_object for 'wp_testivalmistaja' as expected
?>
```

**Comment by mikejolley** [comment]
The product data store `update_attributes` method will handle term assignment.  You don't need to do this manually.

And the `WC_Product_Attribute` class will handle term creation if a term does not exist and you're passing term names to it. Take a look at it's `get_terms` method which is used in the update routine.

I'd look there and avoid handling terms manually. The CRUD is there to do this for you.

Core itself uses the CRUD and this example may help https://github.com/woocommerce/woocommerce/blob/0146c7d240d0b222d1c16bb5592dec05dba93526/includes/import/abstract-wc-product-importer.php#L298

Thanks

**Comment by parkinep** [comment]
Thanks, I found the error: I was not setting the name correctly.

Requiring the name to be set by the user even though an ID has been provided seems redundant as the name *has* to match the taxonomy the ID is pointing to in order for the class to be able to same the terms. It shouldn't be a huge change to have the WC_Product_Attribute class check the name from the ID if the name is empty. 
Not a *huge* issue, but it certainly confused me and probably others as well.

**Comment by mikejolley** [comment]
Yeah I guess it could be auto-set. Want to send a PR?

**Comment by eddr** [comment]
any update? confused me as well, especially as a good enough docs are not easy to reach
