### ISSUE TITLE
Wizard not defaulting to country's measurement units in Shipping step

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce#17260]
The functionality (introduced by https://github.com/woocommerce/woocommerce/commit/e940544a2a364ffae366ebbaa327cb5172af49a8) of defaulting the setup wizard's "Shipping" step to "oz" and "in." units for US stores: https://github.com/woocommerce/woocommerce/blob/2b3f524d351cfa591f3a47a8da218eea12bfd05c/includes/admin/class-wc-admin-setup-wizard.php#L708-L716

...seems to be unreachable in typical usage. The options appear to be already set by the installation script: https://github.com/woocommerce/woocommerce/blob/7eedf1c5134607c3d38b085fc88721fc5d2d14af/includes/class-wc-install.php#L420

...to the default values: https://github.com/woocommerce/woocommerce/blob/7eedf1c5134607c3d38b085fc88721fc5d2d14af/includes/admin/settings/class-wc-settings-products.php#L430 https://github.com/woocommerce/woocommerce/blob/7eedf1c5134607c3d38b085fc88721fc5d2d14af/includes/admin/settings/class-wc-settings-products.php#L447

Tested with fresh installs. The only way I'm able to trigger the default units conditional on country is to delete (one of) the options. Not sure how it worked to begin with or if there are cases where it still does work.

**Comment by dechov** [comment]
Short of sacrificing either defaults set on install or defaults in the wizard differentiated by country, the only solutions that come to mind — a) wizard ignoring existing values, or b) keeping track of whether country has been deliberately set and only then using existing values — fail to explain how this previously worked, which would be nice to understand.

**Comment by mikejolley** [comment]
We don't want to wizard to be ran multiple times, so I'd be happy with:

> wizard ignoring existing values

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17298
