### ISSUE TITLE
Terms and Conditions error notice takes user away from Terms and Conditions acceptance

### ISSUE THREAD

**Issue by Jon007** [woocommerce/woocommerce#17266]
When user presses button to pay but has not accepted terms and conditions there is an error message like "You must accept our Terms & Conditions."

However the message is right at the top of the screen (and not readily movable by template)
but Terms & Conditions box does belong right at the bottom of the screen with the Place Order button, several screen page-scrolls away (depending on your screen size, layout, and size of order, but on a mobile for example, it's a reaally long way away).

This is silly but annoying from customer perspective, and some customers complain or are too confused to continue.

In some setups affected by the #17156 scrolltop issue, the user will be returned to the top of the screen with the error message not visible and no idea what has happened, whereas actually they need to go all the way to the bottom of the screen to check the box.

Rather than re-engineering the message process, why not disable the Pay button until the Terms and Conditions box is selected?  
or as the first javascript action, check that the terms is selected if present and if not, show a simple alert and cancel processing?  (so the user isn't moved away to the top of the screen)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)  I have tested on 3.2.1
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  current installation on latest wordpress, wooCommerce 3.x (tested 3.2.1) and latest Storefront
2.  configure Terms and Conditions page
3. go to check out
4. press Place Order without check the box "I’ve read and accept the terms & conditions "

## Expected/actual behavior

When I follow those steps, I am taken back to the top of the screen

I was expecting that the screen should not move and instead highlight the "I’ve read and accept the terms & conditions" as in need of acceptance.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost:8888/woo3test
Site URL: http://localhost:8888/woo3test
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.0.15 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.0.15
PHP Post Max Size: 32 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.71MB
Database Data Size: 1.80MB
Database Index Size: 0.91MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.03MB + Index: 0.02MB
wp_postmeta: Data: 0.19MB + Index: 0.14MB
wp_posts: Data: 0.08MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 49
nav_menu_item: 3
page: 5
polylang_mo: 2
post: 2
product: 26
product_variation: 8
revision: 1
shop_coupon: 3
shop_order: 6

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #34 - /shop/
Basket: #35 - /cart/
Checkout: #36 - /checkout/
My account: #37 - /my-account/
Terms and conditions: #2 - /sample-page/

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
This is a valid concern. I do however worry a disabled pay button without a message asking them to accept terms would be just as confusing.

An option, although I'm not a legal person so don't take this without checking, could be to show a message stating that to place order you accept TOS. 

Either way, this issue here is being started this quarter: https://github.com/woocommerce/woocommerce/issues/10672 So this and other checkout issues will be tackled at the same time, design first :) It's coming.

**Comment by Jon007** [comment]
Yes I noticed 10672.

The thing is there is already a message asking customers to accept terms when WooCommerce, Settings, Terms and conditions is set..
But if a user forgets to click on it before hitting the place order, they get zoomed off to the top of the page, away from where they need to be.

That's a fairly simple issue that doesn't need to wait many months for a redesigned process.

**Comment by mikejolley** [comment]
A small change to the way TOS works means extra dev time (for something that will likely be thrown away in a few months) and themes have to update templates twice. I'd rather wait for the other issue tbh and get it done right. 

The current TOS setup has been in core for years with relatively little feedback so I don't think it's high priority either.

**Comment by Jon007** [comment]
Yes, agreed, the current process is wrong so no point fixing. 
There should not be a checkbox to accept terms and conditions, just a notice that by pressing the place order button you accept them, and if you don't agree, don't order.

As an example:
> By placing your order, you agree to Amazon.co.uk's Privacy Notice, Conditions of Use & Sale and Cookies & Internet Advertising

[Laws about notices may also be different in some countries so probably not one solution for everyone.]
