### ISSUE TITLE
woocommerce_before_shop_loop & woocommerce_shortcode_before_products_loop rendered content is not identical!

### ISSUE THREAD

**Issue by dameer** [woocommerce/woocommerce#17265]
`woocommerce_before_shop_loop` and `woocommerce_shortcode_before_products_loop` actions are used to render content of the “content-product.php”.
Formal does it for product archives page(s) while the latter one for product shortcodes.
Once again, both use “content-product.php” to render single product in loop.
How come is possible that the final HTML differs?!?

For example, here’s the chunk of HTML rendered by `woocommerce_before_shop_loop`:

```
<a href="http://whatever..." class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
	<span class="onsale">Sale!</span>
</a>
<a href="//whatever..." title="whatever...">
	<img src="whatever..." class="whatever..." alt="" srcset="whatever..." sizes="whatever..." width="whatever..." height="whatever...">
</a>
```

… and here’s what comes out of `woocommerce_shortcode_before_products_loop`:

```
<a href="http://whatever..." class="woocommerce-LoopProduct-link woocommerce-loop-product__link">
	<span class="onsale">Sale!</span>
	<img src="//whatever" class="whatever..." alt="" srcset="//whatever..." sizes="whatever..." width="whatever..." height="whatever...">
</a>
```

I wasn't able to figure out what code makes the difference so I suppose it's a bug.

**Comment by mikejolley** [comment]
These are actions where you're controlling what HTML is output, so a core bug it cannot be. They are regular WP actions and nothing special is being done as can be seen in the codebase. You should however remember that content is subject to filters from WP depending on where it is. e.g. shortcodes are inside post content, which itself is filtered.

It can also be affected by themes filtering or running wpautop on the content. Line breaks in your html can be affected. 

I'd guess it's just that.

The other thing it could be is broken or invalid markup in your action. I don't know what the original was for the above so I cannot say.

Good luck

**Comment by dameer** [comment]
OK Mike, your answer made sense and that's why I checked each and every line of code once again. (I should have check one of WP's default themes in order to figure that out by myself, sorry for being lame.)

Of course I found source of the problem!

No matter what I still believe that the way single product (content-product.php) HTML is composed may cause the above mentioned issue.

WP's `post_thumbnail_html` filter/hook allows modification of post thumbnail HTML. Product's SALE element and thumbnail are wrapped by A tag by default.
In my case, the theme used the following to auto-link featured image:

```
function wps9914_autolink_featured_images( $html, $post_id, $post_image_id ) {

	if( ! is_singular() ) { 
		
		$html = '<a href="' . get_permalink( $post_id ) . '" title="' . esc_attr( get_the_title( $post_id ) ) . '">' . $html . '</a>';
		return $html;
	
	} else { 
	
		return $html;
	
	}

}
add_filter( 'post_thumbnail_html', 'wps9914_autolink_featured_images', 10, 3 );
```
...and which caused problems I mentioned above.

Please take this into consideration!

Thanks!
