### ISSUE TITLE
Shop address empty

### ISSUE THREAD

**Issue by keeslamper** [woocommerce/woocommerce#17268]
Hi, 

I've seen in a few webshops of my customers after updating to the newest Woo 3.2.1 the shop address is empty.

Regards,
Kees
`
### WordPress Environment ###

Home URL: https://sanitairkiezer.nl
Site URL: https://sanitairkiezer.nl
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2
PHP Version: 5.6.30
PHP Post Max Size: 256 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 7.52.1
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.26
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: sani_
Totale databasegrootte: 53.25MB
Database datagrootte: 39.38MB
Database index grootte: 13.87MB
sani_woocommerce_sessions: Data: 2.02MB + Index: 0.02MB
sani_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
sani_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
sani_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
sani_woocommerce_order_items: Data: 0.26MB + Index: 0.17MB
sani_woocommerce_order_itemmeta: Data: 1.80MB + Index: 1.33MB
sani_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
sani_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
sani_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
sani_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
sani_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
sani_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
sani_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
sani_woocommerce_log: Data: 0.02MB + Index: 0.02MB
sani_cleanup_optimizer_block_range_ip: Data: 0.02MB + Index: 0.00MB
sani_cleanup_optimizer_block_single_ip: Data: 0.02MB + Index: 0.00MB
sani_cleanup_optimizer_db_scheduler: Data: 0.02MB + Index: 0.00MB
sani_cleanup_optimizer_licensing: Data: 0.02MB + Index: 0.00MB
sani_cleanup_optimizer_login_log: Data: 0.02MB + Index: 0.00MB
sani_cleanup_optimizer_plugin_settings: Data: 0.02MB + Index: 0.00MB
sani_cleanup_optimizer_wp_scheduler: Data: 0.02MB + Index: 0.00MB
sani_cloudinvoiceclient: Data: 0.02MB + Index: 0.00MB
sani_commentmeta: Data: 0.46MB + Index: 0.09MB
sani_comments: Data: 2.03MB + Index: 0.84MB
sani_cp_feeds: Data: 0.02MB + Index: 0.00MB
sani_fmet_product_dtabs: Data: 0.02MB + Index: 0.00MB
sani_fmet_product_gtabs: Data: 0.02MB + Index: 0.00MB
sani_fmet_product_tabs: Data: 0.02MB + Index: 0.00MB
sani_fmet_temp_dtabs: Data: 0.02MB + Index: 0.00MB
sani_fmet_temp_gtabs: Data: 0.02MB + Index: 0.00MB
sani_fmet_temp_tabs: Data: 0.02MB + Index: 0.00MB
sani_fmet_use_gtabs: Data: 0.02MB + Index: 0.00MB
sani_ishouty_rsm_audit: Data: 0.02MB + Index: 0.00MB
sani_iwp_backup_status: Data: 0.02MB + Index: 0.00MB
sani_layerslider: Data: 0.08MB + Index: 0.00MB
sani_layerslider_revisions: Data: 0.02MB + Index: 0.00MB
sani_links: Data: 0.00MB + Index: 0.00MB
sani_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB
sani_nf_objectmeta: Data: 0.00MB + Index: 0.00MB
sani_nf_objects: Data: 0.00MB + Index: 0.00MB
sani_nf_relationships: Data: 0.00MB + Index: 0.00MB
sani_ninja_forms: Data: 0.00MB + Index: 0.00MB
sani_ninja_forms_fav_fields: Data: 0.02MB + Index: 0.00MB
sani_ninja_forms_fields: Data: 0.00MB + Index: 0.00MB
sani_options: Data: 3.48MB + Index: 0.27MB
sani_podsrel: Data: 0.02MB + Index: 0.06MB
sani_postmeta: Data: 16.63MB + Index: 6.43MB
sani_posts: Data: 3.83MB + Index: 0.78MB
sani_ppgc_customers: Data: 0.06MB + Index: 0.01MB
sani_rac_abandoncart: Data: 0.29MB + Index: 0.01MB
sani_rac_email_logs: Data: 0.02MB + Index: 0.01MB
sani_rac_templates_email: Data: 0.00MB + Index: 0.00MB
sani_redirection_404: Data: 1.02MB + Index: 1.27MB
sani_redirection_groups: Data: 0.02MB + Index: 0.03MB
sani_redirection_items: Data: 0.09MB + Index: 0.11MB
sani_redirection_logs: Data: 5.52MB + Index: 1.28MB
sani_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
sani_rsm_stock_woocommerce_product_table: Data: 0.02MB + Index: 0.03MB
sani_taxonomymeta: Data: 0.00MB + Index: 0.01MB
sani_termmeta: Data: 0.06MB + Index: 0.04MB
sani_terms: Data: 0.04MB + Index: 0.09MB
sani_term_relationships: Data: 0.15MB + Index: 0.34MB
sani_term_taxonomy: Data: 0.04MB + Index: 0.04MB
sani_usermeta: Data: 0.51MB + Index: 0.32MB
sani_users: Data: 0.02MB + Index: 0.03MB
sani_wc_poin_of_sale_grids: Data: 0.02MB + Index: 0.00MB
sani_wc_poin_of_sale_outlets: Data: 0.02MB + Index: 0.00MB
sani_wc_poin_of_sale_receipts: Data: 0.02MB + Index: 0.00MB
sani_wc_poin_of_sale_registers: Data: 0.02MB + Index: 0.00MB
sani_wc_poin_of_sale_tiles: Data: 0.02MB + Index: 0.00MB
sani_webwinkelkeur_invite_error: Data: 0.00MB + Index: 0.00MB
sani_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
sani_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
sani_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB
sani_wpmelon_advbedit_temp: Data: 0.17MB + Index: 0.00MB
sani_yith_wcwl: Data: 0.00MB + Index: 0.00MB
sani_yith_wcwl_lists: Data: 0.00MB + Index: 0.00MB
sani_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
sani_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 3308
avia_framework_post: 7
blocks: 2
nav_menu_item: 143
page: 19
post: 14
pos_custom_product: 1
pos_temp_register_or: 4
product: 682
product_variation: 567
revision: 605
shop_coupon: 1
shop_order: 1452
shop_order_refund: 40
shop_webhook: 1
spucpt: 2
tekstblokken: 1
_pods_field: 1
_pods_pod: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

AdvertentiePlanet: door EasyAds – 0.1 – Niet getest met de actieve versie van WooCommerce
Akismet Anti-Spam: door Automattic – 4.0
Black Studio TinyMCE Widget: door Black Studio – 2.5.1
cloudinvoiceclient: door Sophie Fischer – 2.4.1 – Niet getest met de actieve versie van WooCommerce
Duplicate Page And Post: door pluginsforwp – 2.1.1
Google Tag Manager for Wordpress: door Thomas Geiger – 1.7.1
Enhanced E-commerce for Woocommerce store: door Tatvic – 1.1.2 – Niet getest met de actieve versie van WooCommerce
EU Cookie Law: door Alex Moss
Marco Milesi
Peadig
Shane Jones – 2.10

Facebook for WooCommerce: door Facebook – 1.2.6 – Niet getest met de actieve versie van WooCommerce
WooBought Pro: door Maarten Belmans – 1.0.9
MainWP Child: door MainWP – 3.4.3
Mollie Payments for WooCommerce: door Mollie – 2.7.0
No Slug Product Post Types: door Devin Price – 1.0.0 – Niet getest met de actieve versie van WooCommerce
PixelYourSite: door PixelYourSite – 5.0.8 – Niet getest met de actieve versie van WooCommerce
Pods - Custom Content Types and Fields: door Pods Framework Team – 2.6.11
Popups - WordPress Popup: door Damian Logghe – 1.7.3
WooCommerce Product Filter: door Mihajlovic Nenad – 6.4.5 – Niet getest met de actieve versie van WooCommerce
Recover Abandoned Cart: door Fantastic Plugins – 11.5 – Niet getest met de actieve versie van WooCommerce
Redirection: door John Godley – 2.7.3
UpdraftPlus - Backup/Restore: door UpdraftPlus.Com
DavidAnderson – 2.13.11.22

WebwinkelKeur: door Albert Peschar – 1.4.4 – Niet getest met de actieve versie van WooCommerce
WOOATM - WooCommerce Accordions & Tabs Manager: door Magnigenie – 1.0 – Niet getest met de actieve versie van WooCommerce
Woocommerce Advanced Bulk Edit: door George Iron – 3.6 – Niet getest met de actieve versie van WooCommerce
WooCommerce Availability Notifications: door ThemePlugger – 1.1.4 – Niet getest met de actieve versie van WooCommerce
WooCommerce COD Advanced: door AheadZen – 1.3.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Conditional Shipping and Payments: door WooThemes – 1.2.5 – 1.2.8 is beschikbaar – Niet getest met de actieve versie van WooCommerce
WooCommerce Cost of Goods: door SkyVerge – 2.3.1 – 2.5.0 is beschikbaar – Niet getest met de actieve versie van WooCommerce
WooCommerce MailChimp: door Saint Systems – 2.1.2 – Niet getest met de actieve versie van WooCommerce
Jet Verzendt - WooCommerce Shipping plugin: door Jet Verzendt – 0.1.7 – Niet getest met de actieve versie van WooCommerce
WooCommerce Point of Sale: door Actuality Extensions – 4.1.8.7 – Niet getest met de actieve versie van WooCommerce
Woocommerce Rapid Stock Manager: door ishouty – 2.0.2 – Niet getest met de actieve versie van WooCommerce
WooCommerce Remove /product & /product-category: door Tim – 2.0.2 – Niet getest met de actieve versie van WooCommerce
WooCommerce: door Automattic – 3.2.1
Yoast SEO: door Team Yoast – 5.6.1
WP Fastest Cache: door Emre Vona – 0.8.7.3
WP-Mail-SMTP: door Callum Macdonald – 0.10.1
WP Rollback: door WordImpress – 1.5
YITH WooCommerce Ajax Search: door YITHEMES – 1.5.3 – Niet getest met de actieve versie van WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #506 - /shop/
Winkelmand: #507 - /cart/
Afrekenen: #2836 - /checkout/
Mijn account: #2798 - /my-account/
Algemene voorwaarden: #8103 - /algemene-voorwaarden/

### Theme ###

Name: Enfold Child
Version: 1.0
Author URL: http://www.kriesi.at
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.1
Parent Theme Author URL: http://www.kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by GlennMartin1** [comment]
The shop address fields are new in 3.2.0. They're empty until you first complete those fields.
