### ISSUE TITLE
Admin Dashboard loads extremely slowly once time in <TIME SPAN> in a large shop

### ISSUE THREAD

**Issue by parkinep** [woocommerce/woocommerce#17270]
WP Admin dashboard takes 30+ seconds to load in a 60k+ product shop. I suspect the issue is the dashboard widget displaying number of low/out of stock products checking the number of each.

**Comment by kloon** [comment]
Although we try our best to cache the data we do need to refresh it at some point in time to provide accurate stats.

If you feel you do not need these widgets you can remove them which will eliminate the slow initial loading.

Try
```
remove_meta_box( 'woocommerce_dashboard_status', 'dashboard', 'none' );
remove_meta_box( 'woocommerce_dashboard_recent_reviews', 'dashboard', 'none' );
```
