### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by carlazw** [woocommerce/woocommerce#17271]
Hello,

I am getting this error when I use woocommerce rest api with basic authentication, because I have SSL:
{
    "code": "woocommerce_rest_cannot_view",
    "message": "Sorry, you cannot list resources.",
    "data": {
        "status": 401
    }
}
Kindly note that I am using postman to test rest api and I don't have any plugin on the website except woocommerce, and I am using theme twenty seventeen.
N.B. I get data if I put consumer key and consumer secret in link, and I am trying with rest api version 1.
Woocommerce: 3.0.1
Wordpress: 4.8.2

Thank you.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#common-connection-issues Some servers/hosts are not configured to work with the auth headers and need to use query-string.
