### ISSUE TITLE
[API] line_items has net prices also if prices_include_tax is set to true

### ISSUE THREAD

**Issue by Aerendir** [woocommerce/woocommerce#17276]
I'm retrieving data of orders from the API.

In my backend prices are set as taxes included.

But the API returns `line_items` without taxes.
The order key `prices_include_tax` correctly is set to `true` and effectively the `total` is grossed, but prices of single `line_items` aren't.

I expect that if `prices_include_tax` is set to `true` all amounts returned by the API are returned accordingly, but this is not true for `line_items` that simply ignore the setting.

Am I doing something wrong or is this effectively a bug of the API?

**Comment by mikejolley** [comment]
Showing different results based on store settings would make the API more difficult to consume. Tax is sent as a separate value. See https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

e.g. total and total_tax, subtotal and subtotal_tax. All line totals excl. tax.

Thanks
