### ISSUE TITLE
Major update warning not scrollable

### ISSUE THREAD

**Issue by iMazed** [woocommerce/woocommerce#17277]
I tried to update to WooCommerce 3.2.1 on my staging site (which has a lot of plugins installed), I get the 'Major Update' warning. Since it's not scrollable, I can't actually continue updating, or click the button at the bottom of the prompt. Might be a little edge case as it's a *lot* of plugins, but wanted to make note of it. 

Screencast:

![wc-update](https://user-images.githubusercontent.com/3907432/31735109-2aad0a26-b441-11e7-8871-cb0fa42c4b8c.gif)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Have a ton of plugins installed on your site (I have around 120 - and yes, planning on nuking it soon)
2. Update from Woo 3.2.0 to 3.2.1
3. Try to run the update from Dashboard > Updates

A manual update works.

**Comment by GlennMartin1** [comment]
This is a known issue being address in 3.2.2.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/17208
