### ISSUE TITLE
Product discount coupons not working in specific scenario

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#17275]
Scenario:

1\. Create product `one` with a cost of 10
2\. Create coupon `one` with the following settings:
- Fixed Product Discount
- Coupon amount = 10
- Restrict coupon to product `one`
- Limit usage to X items = 1
- Usage limit per user = 1
3\. Create coupon `two` with the same settings as the previous coupon
4\. Add product `one` to the cart with a quantity of 2
5\. Apply coupon `one`
6\. Apply coupon `two`

In this scenario only one of the coupons is applied. It seems to be that they are both matching the same item and the discount can only be applied once.

![image](https://user-images.githubusercontent.com/11388669/31731936-a24f919c-b42e-11e7-8f09-4e8ce82d155c.png)

What I would expect to happen is that each coupon can apply to each item separately, and the order total would end up being 0.

I also tested this with an older version of WooCommerce (3.0.7). There both coupons were applied with exactly the same settings.

Affected ticket: 742547-zd-woothemes

**Comment by mikejolley** [comment]
should be fixed by https://github.com/woocommerce/woocommerce/pull/17331 but was more complicated than hoped. We don't apply discounts per qty item, but per line item.
