### ISSUE TITLE
Payment Request API Enabled Prevents Other Payment Methods From Being Used

### ISSUE THREAD

**Issue by co50** [woocommerce/woocommerce#17282]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Enable Payment Request API in Stripe payment method.
2. Checkout
3. On Chrome, user is forced to pay via Google if they are logged in. If the store offers Paypal or any other payment method, they are never offered because the Payment Request API to the browser comes before it.

## Expected/actual behavior

When I follow those steps, I see...

Chrome pop-up prompt to confirm saved Google payment info to use as payment. 

I was expecting to see...

Choice of payment method (Credit Card, Paypal)

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

`
### WordPress Environment ###

Home URL: https://mantispinball.com
Site URL: https://mantispinball.com
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.10
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 31.11MB
Database Data Size: 25.95MB
Database Index Size: 5.16MB
wp_woocommerce_sessions: Data: 1.17MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB
wp_woocommerce_order_itemmeta: Data: 0.39MB + Index: 0.34MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.20MB + Index: 0.28MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 4.47MB + Index: 0.14MB
wp_postmeta: Data: 12.52MB + Index: 3.03MB
wp_posts: Data: 5.52MB + Index: 0.25MB
wp_realmedialibrary: Data: 0.02MB + Index: 0.00MB
wp_realmedialibrary_debug: Data: 0.02MB + Index: 0.00MB
wp_realmedialibrary_meta: Data: 0.02MB + Index: 0.03MB
wp_realmedialibrary_order: Data: 0.02MB + Index: 0.02MB
wp_realmedialibrary_posts: Data: 0.02MB + Index: 0.02MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.05MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.25MB + Index: 0.20MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_recommendations: Data: 0.34MB + Index: 0.00MB
wp_woocommerce_session_activity: Data: 0.27MB + Index: 0.00MB
wp_woos_search_analytics: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 321
nav_menu_item: 47
page: 6
postman_sent_mail: 250
product: 159
revision: 1
shop_coupon: 3
shop_order: 300
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

ManageWP - Worker: by ManageWP – 4.2.24
Gravity Forms: by rocketgenius – 2.2.5
Admin Menu Editor Pro: by Janis Elsts – 2.5.1
Akismet Anti-Spam: by Automattic – 4.0
Imagify: by WP Media – 1.6.11
Mobile Address Bar Changer: by Anshul Labs – 2.0
My Custom Functions: by Arthur Gareginyan – 4.10
Postman SMTP: by Jason Hendriks – 1.7.2
WP Real Media Library: by Matthias Günter – 3.2.2
Really Simple SSL: by Rogier Lankhorst – 2.5.22
WP Rocket Footer JS: by Derrick Hammer – 2.0.0
Smart Cleanup Tools: by Milan Petrovic – 4.2
SO Hide SEO Bloat: by SO WP – 3.3.0
Woo Checkout Editor: by Themeco – 2.0.0 – Not tested with the active version of WooCommerce
Tracking Code Manager: by IntellyWP – 1.11.6 – Not tested with the active version of WooCommerce
Ultimate Branding: by WPMU DEV – 1.8.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.13.11.22

Woo Search Box: by Guaven Labs – 1.7.3
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooCommerce – 1.6.8 – Not tested with the active version of WooCommerce
WooCommerce USPS Shipping: by WooCommerce – 4.4.10
WooCommerce: by Automattic – 3.2.1
WooSwipe: by Website Design – 1.1.6.6
Yoast SEO: by Team Yoast – 5.6.1
WP Rocket: by WP Media – 2.10.9
Yoast SEO: WooCommerce: by Team Yoast – 5.5 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #13 - /
Cart: #14 - /cart/
Checkout: #15 - /checkout/
My account: #16 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Pro
Version: 1.2.3
Author URL: http://theme.co/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: pro/woocommerce/cart/cross-sells.php
pro/woocommerce/loop/loop-end.php
pro/woocommerce/loop/loop-start.php
pro/woocommerce/loop/pagination.php
pro/woocommerce/notices/error.php
pro/woocommerce/notices/notice.php
pro/woocommerce/notices/success.php
pro/woocommerce/single-product/related.php
pro/woocommerce/single-product/tabs/tabs.php
pro/woocommerce/single-product/up-sells.php
pro/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 3.2.0

Outdated Templates: ❌Learn how to update
`

</details>

**Comment by mikejolley** [comment]
This needs to be logged to https://github.com/woocommerce/woocommerce-gateway-stripe/issues

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/382
