### ISSUE TITLE
Make email address on Checkout wider or move it for better visibility

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce#17288]
This was reported on the WPcom Store here: https://github.com/Automattic/wp-calypso/issues/18954, however seems that makes sense to report it here as well so can be fixed from WooCommerce core as per the comments in that issue:

> It looks like we could fix this for Stores on .com by hooking in here:
>https://github.com/woocommerce/woocommerce/blob/0510714abf22a736b29556a5a8730c525e03ccbd/includes/class-wc-countries.php#L1147-L1174
>And remove the CSS classes for email/phone.

When going through the checkout process, the text field reserved for the email is too short and regular or long emails are not displayed fully. Cutting this value on online purchases seems arbitrary if we take into account that the ZIP code text field has double the width and will be certainly always shorter than this value.

This can be seen here: p90Yrv-es-p2 on the minute 25:12

<img width="1077" alt="screen shot 2017-10-18 at 14 23 25" src="https://user-images.githubusercontent.com/3812076/31719258-1b0d1102-b413-11e7-8b15-ccf4a99e9116.png">

**How to replicate:**

- Go through the process of purchasing a product.
- Go to the checkout page, for example https://domain.com/checkout
- See how the email address text field got cut in the checkout page

**What I expected:**

- To see my full email address, or most of it.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17323
