### ISSUE TITLE
Duplicate Product no longer duplicates postmeta (ACF issue)

### ISSUE THREAD

**Issue by elliotcondon** [woocommerce/woocommerce#17281]
Hi @mikejolley,

Hope you are well. Elliot here from ACF.

I just got notified about an "issue" introduced in WC 3.2 where postmeta is no longer copied across during the 'duplicate product' action (screenshot to illustrate duplicate button).
![screen shot 2017-10-19 at 11 28 22 am](https://user-images.githubusercontent.com/2296425/31748720-6b2b6d64-b4b8-11e7-901a-22b6578136dc.png)

I had a look through the [class-wc-admin-duplicate-product.php](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-duplicate-product.php) class and can see that the previous `duplicate_post_meta()` function has been removed.

I'm sure this was changed for a good reason, but has left some ACF user's a bit frustrated. Previously, any ACF values (postmeta) would be copied across to the new product, but now none are.

Any chance we can get the post's postmeta copied across during product duplication again?
This would help out a lot of existing WC + ACF projects 😄👍.

Cheers
Elliot

**Comment by mikejolley** [comment]
it's solved in master. 3.2.2 will have it.

**Comment by elliotcondon** [comment]
Legend 👍

**Comment by mgason** [comment]
Any ideas on when 3.2.2 might drop? We duplicate a lot, this drops all of our custom fields, our shipping plugin pricing, Yoast seo entries etc.

**Comment by mikejolley** [comment]
Sometime next week.

**Comment by alonazisser** [comment]
Hi!

Are the any news about the update release?

**Comment by mikejolley** [comment]
Beyond my last comment...no...
