### ISSUE TITLE
Problem with export of the csv

### ISSUE THREAD

**Issue by Toregam** [woocommerce/woocommerce#17293]
Hi,
My name is Salvo. I have a problem with a plugin. It plugin’s name is <h3> Wc Role Based Price.</h3>
The problem is:
When i do the export of the CSV of the prodocts, the plugin crashes.
What can i do for risolve this problem?
Please help me!!!!

**Comment by jesinwp** [comment]
You should start a topic here - <https://wordpress.org/support/plugin/woocommerce-role-based-price>
