### ISSUE TITLE
WC_Cart -> get_item_data returns attribute slug instead of name

### ISSUE THREAD

**Issue by RJRISO** [woocommerce/woocommerce#17294]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add product attribute with different slug and display value
2. Add product to cart
3. Programmatically get cart 
```
foreach (WC()->cart->get_cart() as $cart_item_key => $cart_item) {
   ...
   WC()->cart->get_item_data($cart_item, false);
   ...
} 
```  

## Expected/actual behavior

When I follow those steps, I see...
The correct Attribute label followed by the slug of the variation, i.e.:
Color: Midnight Blue
I was expecting to see...
The correct Attribute label followed by the display term of the variation, i.e.:
Color: mid-blue

## Isolating the problem

- [ X] This bug happens with only WooCommerce plugin active
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

In reviewing the WC_Cart class function get_item_data I noticed line 813:
$taxonomy = wc_attribute_taxonomy_name( str_replace( 'attribute_pa_', '', urldecode( $name ) ) );
but when I look in the wp_term_taxonomy table, I see product attributes prefaced with 'pa_', not 'attribute_pa_'. 
If I change line 813 to read:
$taxonomy = wc_attribute_taxonomy_name( str_replace( 'pa_', '', urldecode( $name ) ) );
the taxonomy is found and the proper values are returned by get_item_data.

Checking the storefront theme, it does not seem to be impacted by the change.

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost
Site URL: http://localhost
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.22-0ubuntu0.16.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
Total Database Size: 6.04MB
Database Data Size: 4.71MB
Database Index Size: 1.33MB
wp_woocommerce_sessions: Data: 0.13MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.05MB + Index: 0.02MB
wp_posie_billing_names: Data: 0.00MB + Index: 0.00MB
wp_posie_orders: Data: 0.00MB + Index: 0.00MB
wp_posie_product_search: Data: 0.00MB + Index: 0.00MB
wp_posie_shipping_names: Data: 0.00MB + Index: 0.00MB
wp_postmeta: Data: 0.19MB + Index: 0.20MB
wp_posts: Data: 0.06MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.25MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 1.52MB + Index: 0.00MB
wp_wfHits: Data: 0.23MB + Index: 0.09MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_wfKnownFileList: Data: 0.30MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.14MB + Index: 0.11MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 16
page: 8
post: 2
product: 12
product_variation: 42
revision: 11
shop_order: 8

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (4) ###

Woocommerce Products Price Bulk Edit: by Mostafa Qanbari – 2.0 – Not tested with the active version of WooCommerce
POSie-POS: by RisoSystems – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.1
Wordfence Security: by Wordfence – 6.3.20

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #96 - /posie/
Checkout: ❌ Page does not contain the shortcode.
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
`get_item_data` is used to **display** attributes, so the display value should not be a slug.

I tested this and get the 'name' back rather than the slug which is what I was expecting. 

Attribute was global and called 'Color'. Attribute was `Blackkkkk` and `black`. Your code returned `Color: Blackkkkk`. This seems correct.

You could look at the $cart_item directly if you need the slugs.

Thanks

**Comment by RJRISO** [comment]
Mike you miss read my comments. I also wanted to get the name and not the slug. But when I test it here I see the slug. I also see it in the storefront theme.

⁣RisoSystems​

**Comment by RJRISO** [comment]
Further investigation shows that the dummy data provided for Woocommerce includes data with the "attribute_pa" prefix: `<ap:meta_key>attribute_pa_color</wp:meta_key>` which may not reflect current standards, and would account for the correct display of that data which I do not see using original data.

**Comment by mikejolley** [comment]
@RJRISO are you saying it only happens with dummy data, not new products? What about importing via the CSV instead of the XML?

**Comment by RJRISO** [comment]
Mike I'm in the middle of another project just this second. I will investigate it tomorrow and get back to you with a more defined statement of the problem.

⁣RisoSystems​

**Comment by RJRISO** [comment]
Mike,
I have just gotten back to the problem, and have some information for you to consider.
In reviewing the WooCommerce plugin, I find the only reference to "attribute_pa_" occurs in 2 classes:
WC_REST_Products_Controller
WC_Cart
It also appears in wc-attribute-functions.php

References to "pa_" on the other hand, are pervasive - some 60+ references in about 20 classes.

I also find 5 copies of this note in WC_API_Products and WC_REST_Products_Controller:

**"// taxonomy-based attributes are prefixed with `pa_`, otherwise simply `attribute_`**

The current WooCommerce code correctly parses custom attributes which are defined on a product. But the function in question does not correctly parse global attributes which are attached to a product definition (a "taxonomy-based attribute").

Changing line 813 of the WC_Cart class from

**$taxonomy = wc_attribute_taxonomy_name(str_replace('attribute_pa_', '', `urldecode($name)));**

to

**$taxonomy = wc_attribute_taxonomy_name(str_replace('attribute_pa_', '', `urldecode($name)));**

corrects the cart contents display problem for taxonomy-based attributes.

My code does not make use of WC_REST_Products_Controller class, but I suspect that reference may cause problems as well.

**Comment by mikejolley** [comment]
The add to cart methods use `attribute_pa_`, and the cart class handles this. Rest API does not handle carts, so handling may be different. I don't want to change anything until it's replicated my end.

> @RJRISO are you saying it only happens with dummy data, not new products? What about importing via the CSV instead of the XML?

**Comment by RJRISO** [comment]
The dummy data thing was a red herring. To replicate the problem, create a global, taxonomy-based attribute, create a product, add a custom attribute to the product, and add the global attribute to the product. Build variations from the attributes and add one of the variations to a cart. You will see the custom attribute render correctly, and the global attribute render incorrectly.

Attached are two images of a cart with an item which has both a global and a custom attribute rendered with the current code and rendered with the patch I suggest.
![cart_patched](https://user-images.githubusercontent.com/6471952/31944119-dd5e32d4-b87f-11e7-8ee2-b71efe3562db.jpg)
![cart_error](https://user-images.githubusercontent.com/6471952/31944121-dd781096-b87f-11e7-9316-88b8baa7aeca.jpg)

**Comment by RJRISO** [comment]
I reviewed the add_to_cart function and the only reference I find to "attribute_" as a prefix apart from line 813, is in 824, which deals with labels for custom option slugs, not taxonomy-based attributes.

Examining the data tables, I find that wp_postmeta uses the "pa_" prefix in arrays in the meta_value column, and wp_term_taxonomy uses the "pa_" prefix in the taxonomy column.

Once again I refer you to the notes in WC_API_Products and WC_REST_Products_Controller. While as you say they do not handle carts, they do handle attributes. It is attribute handling that is the problem here.

**Comment by mikejolley** [comment]
![cart local wordpress dev 2017-10-24 16-41-33](https://user-images.githubusercontent.com/90977/31953109-3f389d32-b8da-11e7-85bc-1534b7e2c9ce.png)

Still fine with your new instructions. Used rtl/backwards exactly like you said.

**Comment by RJRISO** [comment]
I don't know what to tell you, Mike. I'm getting the error here consistently - you've seen the screen shots. How are the items being written in your tables?

**Comment by mikejolley** [comment]
I'm also aware you've been tinkering with code and don't want to waste more time debugging an issue that cannot be reproduced.

Cart item var dump shows `attribute_pa_color` which is my global attribute, with value of `rtl`.

`
$taxonomy = wc_attribute_taxonomy_name( str_replace( 'attribute_pa_', '', urldecode( $name ) ) );
`

returns `pa_color` which is the taxonomy name.

This taxonomy exists so logically the term is retrieved and displayed.

This is the code path taken: https://github.com/woocommerce/woocommerce/blob/fecf950a98669a9f00c2de33220693cf54abb9de/includes/class-wc-cart.php#L814-L822

The code basically takes the attributes in the cart item, `attribute_pa_` is removed, and then `wc_attribute_taxonomy_name` prefixes the given name with `pa_`. It's working.

**Comment by RJRISO** [comment]
With the unpatched code, when I deactivate every plugin except Woocommerce, I still see the problem.

My original solution was to write two string replacement lines - the first for "attribute_pa" and the second for "pa_". The results of the first would be passed to the second, and the second would do any remaining cleanup.

$temp_string = wc_attribute_taxonomy_name( str_replace( 'attribute_pa_', '', urldecode( $name ) ) );
$taxonomy = wc_attribute_taxonomy_name(str_replace('pa_', '', $temp_string));

I don't believe in putting in code without understanding what it's fixing, and I suspect you don't, either. But clearly we're seeing different things.

**Comment by mikejolley** [comment]
I suggest you download a fresh copy of WC to get rid of all of your changes, then var dump the $cart_item like I said originally https://github.com/woocommerce/woocommerce/issues/17294#issuecomment-338346919

**Comment by RJRISO** [comment]
I'll apply a fresh copy of WC just to be sure.

I'm looking at wc-attribute-functions.php and noticed something interesting:
Lines 65-84, 
wc_attribute_taxonomy_name returns the prefix 'attribute_'
wc_variation_attribute_name returns the prefix 'pa_'

When you did your test, did you apply a global attribute to a single product or to a product then generate variations based on that attribute?

**Comment by mikejolley** [comment]
Created variable, assigned attributes, generated all.

**Comment by mikejolley** [comment]
`wc_attribute_taxonomy_name` adds `pa_` prefix. NOT `attribute_`.

`wc_variation_attribute_name` adds `attribute_` prefix, used in admin, which means the meta keys are stored as `attribute_pa_something`.

**Comment by RJRISO** [comment]
I just completely removed and reinstalled Woocommerce. I cleared the cart and used the storefront theme to add items to the cart and voila! everything's working again.

One of life's mysteries, I guess. Thank you for sticking with it. Let's close it, but I'll let you know if it starts acting up again.

Please note: I didn't patch the WC_Cart class until I started seeing the problem - I don't touch core code.

**Comment by jordan314** [comment]
I'm having this issue as well, and am using CSS to solve it for now
```
		.cart_item .variation-Size p{
			text-transform: uppercase;
		}

		.cart_item .variation-Color p{
			text-transform: capitalize;
		}
```
