### ISSUE TITLE
<?php _e( 'Shipping', 'woocommerce' ); ?> trying to add a new text under the shipping label 

### ISSUE THREAD

**Issue by SFaraji** [woocommerce/woocommerce#17297]
<tr class="shipping">
     <th><?php _e( 'Shipping', 'woocommerce' ); ?><br><?php echo 'est. Apr/May 2018'; ?></th>
     <td data-title="<?php esc_attr_e( 'Shipping', 'woocommerce' ); ?>"><?php woocommerce_shipping_calculator(); ?></td>
</tr>

This is what I'm trying to add after the shipping label on the cart page, but it doesn't work: (est. Apr/May 2018)

**Comment by mikejolley** [comment]
> Usage questions can also be directed to the public support forum here: https://wordpress.org/support/plugin/woocommerce, unless this is a question about a premium extension in which case you should use the helpdesk.

We don't provide customisations here.  Github should only be used for reporting bugs :)

Maybe take a look at https://docs.woocommerce.com/document/template-structure/, or see if actions/filter hooks are available.

Thanks
