### ISSUE TITLE
sale_price returns "" for both 0 and null [REST API]

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#17302]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product with sale_price 0 and get the {product_id}
2. Send PUT request to /wp-json/wc/v2/products/{product_id} with sale_price = null
3. Now woocommerce updates on_sale to false
4. Send returned sale_price back again with PUT request to /wp-json/wc/v2/products/{product_id}
5. Now woocommerce updates on_sale to true
6. Look at the response property sale_price, its always equal..

## Expected/actual behavior

**Expected behaviour:**
sale_price should be '0'

**Actual behaviour:**
sale_price is ''

**Why this is a problem?**
Update a product with `sale_price = null` sets `on_sale = false` and returns `sale_price: ''`
Update a product with `sale_price = 0` sets `on_sale = true` and returns `sale_price: ''`
Update a product with `sale_price = ''` sets `on_sale = true` and returns `sale_price: ''`

_A deeper look:_

1. You set `sale_price = null`
2. woocommerce returns `sale_price = ''`
3. You send the response you got back to woocommerce `sale_price = ''`
4. woocommerce still returns `sale_price = ''`

Now it looks like everything is ok but in the background woocommerce has been doing the following:

1. on_sale = false
2. ok
3. on_sale = true
4. ok

So the product is set back to on_sale which I find could be a critical issue

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiosanches** [comment]
Note that `on_sale` is a read-only parameter. So it's impossible to set `on_sale` by the REST API.

I just tested:

```bash
curl -X PUT -u ck_123:cs_123 -k https://woo.dev/wp-json/wc/v2/products/95 -H "Content-Type: application/json" -d '{"sale_price": "10"}' | json_pp | grep \"on_sale\"
```

output:

```
   "on_sale" : true,
```

And then removing the sale price:

```bash
curl -X PUT -u ck_123:cs_123 -k https://woo.dev/wp-json/wc/v2/products/95 -H "Content-Type: application/json" -d '{"sale_price": ""}' | json_pp | grep \"on_sale\"
```

output:

```
   "on_sale" : false,
```

So it's working as it suppose to work.
