### ISSUE TITLE
All ajax requests target home page

### ISSUE THREAD

**Issue by abarrak** [woocommerce/woocommerce#17307]
**WooCommerce** latest version `3.2.1` does not submit ajax request to the same page the originated from.

This effects many aspects of our development, as we do custom logic upon receiving ajax request like processing orders, etc. Now it isn't possible without some kind of [workaround](https://stackoverflow.com/questions/46764004/woocommerce-ajax-submission-to-same-checkout-page-does-not-work).

The issue is caused by [this latest commit change](https://github.com/woocommerce/woocommerce/commit/fbe6db5c02077a548eb1a386076d59261017145f#diff-133db5662c51f5686d87611121a05a3b) maid in`includes/class-wc-ajax.php` by using `home_url` for all ajax request in the shop instead of `request_url`.

*Recommendation:* restore `#get_endpoint` to its original implementation.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

Assuming we have woo commerce on `https://my_website.com`:
1. Issue any Ajax request from a specific page in the app (like: `https://my_website.com/checkout`).
2. requests will be targeting (`https://my_website.com/?wc-ajax=checkout`) and not (`https://my_website.com/checkout?wc-ajax=checkout`).

## Expected/actual behavior

When I follow those steps, I see ajax requests all are routed to main page. 
I was expecting ajax request to hit the origin page of the request.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
I assume you're using page based conditionals?  These should not work on ajax requests because you're not showing a page, you're doing a request.

Also related, the requests run on any endpoint, so the 'current' page is not reliable or guaranteed.

The actual change was a security fix, and we need to keep it going to that homepage URL. I'd suggest running your code based on the name of the ajax request, not the 'page' the endpoint is ran on. 

Thanks

**Comment by tsteur** [comment]
A problem as well is that all URL parameters are no longer forwarded @mikejolley which breaks plugins like the WooCommerce Subscriptions plugin. It used to forward for example parameters like these in the ajax request:

```
/checkout/?attribute_foo=MyPlan&attribute_bar=baz&switch-subscription=505&item=469&_wcsnonce=abcdef&currency=EUR&auto-switch=1&wc-ajax=%%endpoint%%
```

I did not have a look at what the security issue exactly was, but is it possible to keep behaviour of adding the URL parameters again? Should I create rather a new issue?

**Comment by tsteur** [comment]
BTW: We had trouble with those ajax requests going to the homepage as we are redirecting `/` by default to another website and only allow requests to eg `/shop/*`.

**Comment by mikejolley** [comment]
it would be better to pass these yourself in your javascript function.

**Comment by tsteur** [comment]
In our javascript function? I was for example referring to the `wc_checkout_params.wc_ajax_url`  and the checkout form XHR defined in woocommerce itself. I reckon the workaround for such plugin developers be to hook to `woocommerce_ajax_get_endpoint` and add back all the URL parameters?

**Comment by mikejolley** [comment]
Yes but you must have code using the endpoint, which can post the values you need instead.

**Comment by abarrak** [comment]
> I assume you're using page based conditionals? These should not work on ajax requests because you're not showing a page, you're doing a request.
>
> Also related, the requests run on any endpoint, so the 'current' page is not reliable or guaranteed.
>
> The actual change was a security fix, and we need to keep it going to that homepage URL. I'd suggest running your code based on the name of the ajax request, not the 'page' the endpoint is ran on.

I was using the URL of current page targeted by AJAX _(checkout page)_ to be passed to another system for payment processing. Then landing again to same order for completion and pending status removal.

It's feasible to refactor structure to resolve its issue, but it will create conflicts for different wooCommerce versions used by our system.

**Comment by mikejolley** [comment]
AJAX endpoints should really run independently. The fact this was passing though query args from the parent page is a bug. AJAX runs on any URL/endpoint - all it needs is the wc-ajax property. In the payment gateway example, the gateway can pass values via hidden fields in the checkout form if you don't want to touch JS.

**Comment by iabidali** [comment]
I have same issue as OP described. I at least want it to call ajax using full URL if it has to target homepage.

I want it to call `https://example.com/index.php?wc-ajax=get_refreshed_fragments` 
and not `https://example.com/?wc-ajax=get_refreshed_fragments`

Any idea or workaround?

**Comment by abarrak** [comment]
The only workaround when advised clients on is to restore old imlpementation to get_endpoint method mentioned above. 

It's editable from WP plugins editor too.

**Comment by iabidali** [comment]
I have changed homepage URL from `home_url( '/' )` to `home_url( '/index.php' )` and it works now. 

It really should be on to the page where is needs to be loaded. This is not a solid solution as an update to woocommerce will make it again to same state.

**Comment by mikejolley** [comment]
`wp-ajax` has it's own endpoint and developers make do with that. Why should this be any different?

**Comment by iabidali** [comment]
Why it always loads from homepage and not from the page it is required?

I can see it loads well when we check `/checkout/?wc-ajax`

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/17307#issuecomment-338244452 answers this.
