### ISSUE TITLE
Remove anchor tags from url on add to cart

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/woocommerce#17303]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. View a product page containing a review and click the `1 customer review` link. `#reviews` is added to the url and the page jumps down to the reviews section.
2. Scroll back up and click the Add to Cart button.

## Expected/actual behavior

When I follow those steps, I see that when the page refreshes, the `#reviews` tag is still in the url, and the page jumps down to the reviews section again.

I was expecting the page to reload at the top of the page so I could see the “X has been added to your cart." message.

Here's a demonstration:

![suyzu9](https://user-images.githubusercontent.com/1990037/31816309-b9298044-b587-11e7-9e32-07ddac4411f3.gif)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

744282-zen

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/17280
