### ISSUE TITLE
Images won't show on product page when adding more than one image

### ISSUE THREAD

**Issue by ronenla** [woocommerce/woocommerce#17301]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Adding one product image, in addition to the lead product image (in gallery) causes the product page images to disappear. tried with 300x300 images. removing galery images, keeping only one lead product image works fine.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...
1. Create new product 
2.  Add 300x300 image (tested with other sizes as well)
3. Add 300x300 second image to galery of the same product.
(*) Also happens for old products when upgrading to 3.2.0 and on for products that have more than the lead product image.

I was expecting to see...
on Product page, I was expecting to see the images. Instead, the big chosen image is missing.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
[woo_status.txt](https://github.com/woocommerce/woocommerce/files/1400966/woo_status.txt)

**Comment by kloon** [comment]
I tested on the current release and are not able to recreate this. Created a new product with an image set and then added another image to the product gallery and it loads the product page fine.

![Admin Image Setup](http://cld.wthms.co/XLVnSj+)

![Multiple Product Images](http://cld.wthms.co/atktjL+)

I'd double check to make sure you have tested this with all plugins disabled and also switched to a default theme as this is likely caused by an outdated plugin or theme that overrides the image functionality.

**Comment by ronenla** [comment]
There is one more parameter I missed.
Indeed this works when wordpress settings are default (english), but when adding Hebrew package: https://he.wordpress.org/releases/
and changing site language to hebrew, pictures disappear. They appear again when re-setting to english.
