### ISSUE TITLE
Error: Sorry, no resources can be listed 

### ISSUE THREAD

**Issue by gesenlik** [woocommerce/woocommerce#17305]
Hello,

my endpoints are :
    /wp-json/wc/v1/products
   /wp-json/wc/v1/orders 
   
But everytime api response is **Error: Sorry, no resources can be listed**. My shop api settings re right. I dont understand this problem. Please help me!!!

**Comment by mikejolley** [comment]
Hi there,

I'd suggest going though this tutorial: https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

Usually the error is missing auth details. If you go through the wiki entry, it should help you get started. Using a client like postman or insomnia to test.

Thanks

**Comment by gesenlik** [comment]
Hi mikejolley,

I tried everthing but it does not work.
I think there is a problem shops plugins.
Thanks.

**Comment by mikejolley** [comment]
Did you test with the client I mentioned?

**Comment by gesenlik** [comment]
Yes and I get data three different shops but it is not in the market.

**Comment by mikejolley** [comment]
Can you screenshot your insomnia client with the request/response? And did you populate the 'auth' tab?

**Comment by gesenlik** [comment]
![einhorn3](https://user-images.githubusercontent.com/32957634/31840852-c8780666-b5ef-11e7-889d-7cfd01f59d4b.PNG)

**Comment by mikejolley** [comment]
What headers are being set there too?

**Comment by gesenlik** [comment]
![einhorn4](https://user-images.githubusercontent.com/32957634/31851237-7294c808-b66a-11e7-8941-0bde1c1fbfe6.PNG)

**Comment by mikejolley** [comment]
I'm not sure you need to provide this as well as the data on the 'authorization' tab? Not sure how postman works - I use Insomnia client.

**Comment by gesenlik** [comment]
![einhorn](https://user-images.githubusercontent.com/32957634/31946812-80c1a086-b8db-11e7-869e-d677459ed03f.PNG)

That is curl request and reponse.

**Comment by mikejolley** [comment]
Go back to https://github.com/woocommerce/woocommerce/issues/17305#issuecomment-338384371

Leave creds in authentication tab.

Remove the custom header from headers tab.

Retry. 

If it fails, your server does not support the headers. The wiki article I posted earlier shows what to do in those cases. Use query string.

**Comment by gesenlik** [comment]
Oke, thank you so much..
