### ISSUE TITLE
remove_taxes was deprecated as being a never used function but was useful. 

### ISSUE THREAD

**Issue by witchblade32** [woocommerce/woocommerce#17319]
remove_taxes was deprecated indicating that it was unused which is NOT correct.
 
In Pennsylvania, shipping is taxable if any product being shipped is taxable, but shipping is NOT taxable if none of the items being shipped is taxable. For stores that offer both taxed and untaxed items, we used a function that checked the tax status of all products in the cart and if nothing was taxable we called remove_taxes.  

I'm having problems replicating this functionality now.  

class-wc-legacy-cart.php 

	/**
	 * Remove taxes.
	 *
	 * @deprecated 3.2.0 Taxes are never calculated if customer is tax except making this function unused.
	 */
	public function remove_taxes() {
		wc_deprecated_function( 'WC_Cart::remove_taxes', '3.2', '' );
	}

**Comment by kloon** [comment]
There's a bunch of setters and getters you can use on the WC_Cart class to set and retrieve taxes. To set shipping taxes can simply call WC_Cart::set_shipping_taxes and for cart content taxes you can use WC_Cart::set_cart_contents_taxes

You should definitely be able to replicate the functionality you are after with those.
