### ISSUE TITLE
usability issues when searching for and adding products (back end)

### ISSUE THREAD

**Issue by nuclearape** [woocommerce/woocommerce#17310]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Open the search dialogue in the edit order screen.
2. Immediately start typing. **Or,** 
3. Search for a product and hit enter when the product is selected. **Or,** 
4. Search for a product, select it by clicking and immediately start typing again.  **Or,** 
5. Add the selected product(s) to the order.

## Expected/actual behavior

**For step 2 above:** I expect the search field to be in focus by default and the characters I type to appear in the search box. They don't.

**For step 3 above:** I expect the highlighted product to be selected. It doesn't - the page just reloads.

**For step 4 above:** I expect the focus to still be in the search box so that the characters I type appear in the search box. They don't - I have to click in the search box again.

**For step 5 above:** I expect the "add items" set of buttons: add products, fee, shipping, tax etc. to still be available. They are not, I have to click "add items" to access them again.

I know these are very minor bugs but they are still a bit irritating.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://www.chucklinggoat.co.uk
Site URL: https://www.chucklinggoat.co.uk
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.28 (cPanel) OpenSSL/1.0.2k mod_bwlimited/1.4
PHP Version: 7.0.24
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.55.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
Total Database Size: 984.94MB
Database Data Size: 627.82MB
Database Index Size: 357.12MB
wp_woocommerce_sessions: Data: 2.95MB + Index: 0.11MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.05MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 16.12MB + Index: 9.22MB
wp_woocommerce_order_itemmeta: Data: 112.23MB + Index: 74.88MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.01MB + Index: 0.02MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_camera: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 6.70MB + Index: 3.86MB
wp_comments: Data: 105.16MB + Index: 54.09MB
wp_ebay_accounts: Data: 0.00MB + Index: 0.00MB
wp_ebay_auctions: Data: 0.01MB + Index: 0.01MB
wp_ebay_categories: Data: 1.00MB + Index: 0.71MB
wp_ebay_jobs: Data: 0.01MB + Index: 0.00MB
wp_ebay_log: Data: 0.04MB + Index: 0.00MB
wp_ebay_messages: Data: 0.00MB + Index: 0.00MB
wp_ebay_orders: Data: 0.10MB + Index: 0.00MB
wp_ebay_payment: Data: 0.00MB + Index: 0.00MB
wp_ebay_profiles: Data: 0.00MB + Index: 0.00MB
wp_ebay_shipping: Data: 0.01MB + Index: 0.00MB
wp_ebay_sites: Data: 0.03MB + Index: 0.00MB
wp_ebay_store_categories: Data: 0.00MB + Index: 0.00MB
wp_ebay_transactions: Data: 0.17MB + Index: 0.00MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Data: 0.60MB + Index: 0.00MB
wp_options: Data: 12.26MB + Index: 2.48MB
wp_postmeta: Data: 286.68MB + Index: 166.98MB
wp_posts: Data: 23.99MB + Index: 7.83MB
wp_po_plugins: Data: 0.00MB + Index: 0.01MB
wp_queue: Data: 0.07MB + Index: 0.01MB
wp_QuoteRotator: Data: 0.00MB + Index: 0.00MB
wp_redirection_404: Data: 0.70MB + Index: 0.40MB
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB
wp_redirection_items: Data: 0.01MB + Index: 0.01MB
wp_redirection_logs: Data: 0.14MB + Index: 0.06MB
wp_smush_dir_images: Data: 0.04MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.01MB + Index: 0.02MB
wp_term_relationships: Data: 0.06MB + Index: 0.11MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 54.70MB + Index: 33.13MB
wp_users: Data: 3.07MB + Index: 2.97MB
wp_wangguardcronjobs: Data: 0.00MB + Index: 0.00MB
wp_wangguardquestions: Data: 0.00MB + Index: 0.00MB
wp_wangguardreportqueue: Data: 0.00MB + Index: 0.00MB
wp_wangguardsignupsstatus: Data: 0.00MB + Index: 0.00MB
wp_wangguarduserstatus: Data: 0.00MB + Index: 0.00MB
wp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_bundled_itemmeta: Data: 0.01MB + Index: 0.02MB
wp_woocommerce_bundled_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 0.86MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.00MB + Index: 0.00MB
wp_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

acf: 6
acf-field: 73
acf-field-group: 16
attachment: 675
customize_changeset: 1
follow_up_email: 1
forum: 15
mc4wp-form: 1
nav_menu_item: 59
page: 38
payment_retry: 1816
post: 2
ppm-testimonial: 177
product: 25
product_variation: 12
qa_faqs: 10
reply: 64
revision: 63
scheduled-action: 6225
shop_coupon: 20
shop_order: 74435
shop_order_refund: 1196
shop_subscription: 4918
shop_webhook: 16
themedia: 59
topic: 46
tribe_events: 19
tribe_venue: 1
wc_order_email: 4
wc_order_status: 15
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (45) ###

Admin Menu Editor: by Janis Elsts – 1.8
Adminimize: by Frank Bültge – 1.11.2
Advanced Custom Fields PRO: by Elliot Condon – 5.6.3
Advanced Database Cleaner: by Younes JFR. – 2.0.0
Akismet Anti-Spam: by Automattic – 4.0
Admin Columns: by AdminColumns.com – 3.0.3
Contact Form 7: by Takayuki Miyoshi – 4.9
Export User Data: by Q Studio – 1.3.1
Facebook for WooCommerce: by Facebook – 1.6.4 – Not tested with the active version of WooCommerce
GrowSumo: by GrowSumo – 1.0.0
Invisible reCaptcha: by Mihai Chelaru – 1.1
Members: by Justin Tadlock – 2.0.1
Metorik Helper: by Metorik – 0.11.0 – Not tested with the active version of WooCommerce
App look-alike menus: by Fred Heusschen – 2.4.1
Q and A FAQ and Knowledge Base for WordPress: by Raygun – 1.0.6.2
Query Strings Remover: by Atul Kumar Pandey – 1.1
Redirection: by John Godley – 2.8
Set Cookie Expire: by WordPress Development Stack Exchange – 0.1
The Media: by Nuclear Ape – 1.0000000000
WooCommerce Dynamic Pricing & Discounts: by RightPress – 1.1 – Not tested with the active version of WooCommerce
White Label CMS: by www.videousermanuals.com – 1.6.1
WooChimp: by RightPress – 2.0.1 – Not tested with the active version of WooCommerce
WooCommerce Checkout Add-Ons: by SkyVerge – 1.11.0 – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.2.9
WooCommerce Create Customer on Order: by cxThemes – 1.33 – Not tested with the active version of WooCommerce
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.3.7 – Not tested with the active version of WooCommerce
WooCommerce Display Order Count: by SkyVerge – 1.1.0 – Not tested with the active version of WooCommerce
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.4 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce New Customer Report: by SkyVerge – 1.1.0 – Not tested with the active version of WooCommerce
WooCommerce Order Status Manager: by SkyVerge – 1.7.3
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.3.4
WooCommerce Product Bundles: by SomewhereWarm – 5.5.1
WooCommerce Google Product Feed: by Lee Willis – 7.3.0
WooCommerce Subscription Reminders: by Calvin NGUYEN – 1.0.1 – Not tested with the active version of WooCommerce
WooCommerce Sales By Location Report: by ChuckMac Development – 1.3.2 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.3 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions CSV Importer and Exporter: by Prospress Inc – 2.0-beta – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.2.13 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.4 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.1
WP-Lister Pro for eBay: by Matthias Krok – 2.0.26
WP Smush: by WPMU DEV – 2.7.6
WP Super Cache: by Automattic – 1.5.7.1
WP Sync DB: by Sean Lang – 1.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1-2)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

### WC Pages ###

Shop base: #90 - /shop/
Cart: #91 - /shop/cart/
Checkout: #92 - /shop/checkout/
My account: #93 - /shop/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: The Nuclear Ape Theme
Version: – 0 is available
Author URL: http://www.nuclear-ape.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: the_nuclear_ape_theme/woocommerce/archive-product.php
the_nuclear_ape_theme/woocommerce/cart/cart-totals.php
the_nuclear_ape_theme/woocommerce/checkout/form-checkout.php
the_nuclear_ape_theme/woocommerce/checkout/form-login.php
the_nuclear_ape_theme/woocommerce/checkout/form-shipping.php
the_nuclear_ape_theme/woocommerce/content-single-product.php
the_nuclear_ape_theme/woocommerce/emails/customer-completed-order.php
the_nuclear_ape_theme/woocommerce/emails/customer-note.php
the_nuclear_ape_theme/woocommerce/emails/customer-processing-order.php
the_nuclear_ape_theme/woocommerce/emails/email-footer.php
the_nuclear_ape_theme/woocommerce/emails/email-header.php
the_nuclear_ape_theme/woocommerce/emails/email-styles.php
the_nuclear_ape_theme/woocommerce/single-product/tabs/description.php
the_nuclear_ape_theme/woocommerce/single-product/tabs/tabs.php
the_nuclear_ape_theme/woocommerce/single-product.php

### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Brand: Defaults to "Chuckling Goat".
Manufacturer Part Number (MPN): Pre-populates from "sku taxonomy".
Product Type: 
Google Product Category: 

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: No

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Off

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Save to Log

</details>

**Comment by mikejolley** [comment]
Related https://github.com/woocommerce/selectWoo/issues/9
