### ISSUE TITLE
Building webshop

### ISSUE THREAD

**Issue by LIVEreklam** [woocommerce/woocommerce#17311]
I’m building an online store at https://reklamhornet.se/alfons-aberg-produkter/ and https://reklamhornet.se/profilprodukter/
We would like to show the price incl. Excl. VAT. On the simple product pages, both appear and are correct, but on a variable product, the price shows  Excl. VAT. How can I solve this?

**Comment by mikejolley** [comment]
Hi

Usage questions can also be directed to the public support forum here: https://wordpress.org/support/plugin/woocommerce, unless this is a question about a premium extension in which case you should use the helpdesk.

If you're adding text with hooks, note, variations have different hooks that the other product types and may need special handling.

Thanks
