### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of undefined - error when installing Photoswipe

### ISSUE THREAD

**Issue by anish24** [woocommerce/woocommerce#17326]
Hi,

I've updated to woocommerce 3.0 on my staging site and added functionality to add the lightbox using this:

add_theme_support( 'wc-product-gallery-lightbox' );

I've now done that but i'm getting a console error when clicking my images on the product page which says:

Uncaught TypeError: Cannot read property 'x' of undefined

Here is the link to the product page so you can see the issue yourself: 
http://noblefineart.staging.wpengine.com/product/amore/

I've done some research and said something about removing height and widths from the images but tried that but didn't work.

Any help would be much appreciated

**Comment by mikejolley** [comment]
There are other errors on the page, and it also takes more than simply adding that script to a non-compatible theme to get the gallery working. I suspect this theme has custom gallery/image template files and these are missing some tags/content.

Before adding the scripts, ensure the template files have not been modified, or if they have, update them to the core versions so the gallery can function.

Thanks
