### ISSUE TITLE
Date not correctly localized in transactional email's subject

### ISSUE THREAD

**Issue by decimoseptimo** [woocommerce/woocommerce#17324]
In transactional emails, 

- The date is not correctly localized in the mail's subject (according to the site's language)
 - The date is correctly localized in the mail's content.

Formatting is corrrect in both.
![inbox 2 jose867584585 gmail com gmail](https://user-images.githubusercontent.com/16873203/31848066-7c3124ba-b5de-11e7-882f-d8fa7d3f5ff1.png)
The date should be: 19 Octubre, 2017

I really tried the source, but was only able to 
 disable formating ```https://github.com/woocommerce/woocommerce/blob/3.2.1/includes/emails/class-wc-email-customer-invoice.php#L120```

**Comment by decimoseptimo** [comment]
I've been testing, this are my findings.

With my site's language is set to spanish, but my user (admin) profile language is set to english (how I prefer the UI).

When emails are sent to the customer, as a consequence of my actions (e.g. change the order status, manually "email order details to customer"). The date (if present) in the email subject won't be localized, and the data attached (if present) to the emails body by plugins (tested with wc warranties, and wc shipping) won't be translated.

Any of this happens, when my users profile language matches the site's language.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17352
