### ISSUE TITLE
Not able to search uncategorized in filter by category 

### ISSUE THREAD

**Issue by 8ATE** [woocommerce/woocommerce#17321]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to product list
2. Type uncategorized in filter by category search
3. No matches are found

## Expected/actual behavior

When I follow those steps, I see no matches found

I was expecting to see the uncategorized category to be listed.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
`
### WordPress Environment ###

Home URL: https://www.8erotic.com
Site URL: https://www.8erotic.com
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Unix) mod_hive/6.6 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 5.6.31
PHP Post Max Size: 32 MB
PHP Time Limit: 45
PHP Max Input Vars: 1000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 24 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 478.31MB
Database Data Size: 393.96MB
Database Index Size: 84.35MB
wp_woocommerce_sessions: Data: 147.03MB + Index: 3.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.14MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.13MB + Index: 0.22MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.11MB + Index: 0.09MB
wp_cpf_custom_products: Data: 0.02MB + Index: 0.02MB
wp_cp_feeds: Data: 0.02MB + Index: 0.00MB
wp_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB
wp_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB
wp_ewwwio_images: Data: 12.02MB + Index: 17.13MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 109.41MB + Index: 3.05MB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 1.52MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.11MB + Index: 0.00MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.06MB + Index: 0.00MB
wp_pmxi_posts: Data: 1.52MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.30MB + Index: 0.00MB
wp_popover_ip_cache: Data: 0.02MB + Index: 0.02MB
wp_postmeta: Data: 73.14MB + Index: 44.19MB
wp_posts: Data: 25.09MB + Index: 5.70MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 1.52MB + Index: 0.81MB
wp_terms: Data: 1.52MB + Index: 3.03MB
wp_term_relationships: Data: 5.52MB + Index: 3.34MB
wp_term_taxonomy: Data: 1.52MB + Index: 0.77MB
wp_usermeta: Data: 0.18MB + Index: 0.11MB
wp_users: Data: 0.01MB + Index: 0.02MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wdslayer: Data: 0.02MB + Index: 0.00MB
wp_wdsslide: Data: 0.02MB + Index: 0.00MB
wp_wdsslider: Data: 0.02MB + Index: 0.00MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.27MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 3.52MB + Index: 0.00MB
wp_wfHits: Data: 3.52MB + Index: 2.05MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLeechers: Data: 1.02MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.13MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.14MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.13MB + Index: 0.09MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB
wp_wpmcleaner: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 11320
custom_css: 1
feedback: 4
inc_popup: 1
jp_img_sitemap: 11
jp_img_sitemap_index: 2
jp_sitemap: 2
jp_sitemap_master: 2
mc4wp-form: 1
nav_menu_item: 15
page: 19
post: 1
product: 9594
product_variation: 1586
revision: 46
shop_coupon: 12
shop_order: 113
shop_order_refund: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (21) ###

EWWW Image Optimizer: by Shane Bishop – 4.0.0
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.1.2
Google XML Sitemaps: by Arne Brachhold – 4.0.9
Homepage Control: by WooThemes – 2.0.2
Jetpack by WordPress.com: by Automattic – 5.4
MailChimp for WooCommerce: by MailChimp – 2.0.2 – Not tested with the active version of WooCommerce
MailChimp for WordPress: by ibericode – 4.1.10
MailChimp for WordPress - Top Bar: by ibericode – 1.2.16
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
Scripts-To-Footer: by Joshua David Nelson – 0.6.1
Slider WD: by WebDorado – 1.1.92
Storefront Footer Bar: by WooThemes – 1.0.3
WooCommerce Category Accordion.: by TechieResource – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce Free Gift Coupons: by Kathy Darling – 1.2.3 – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Lee Willis – 7.3.0
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.2 – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by WooCommerce – 3.3.7 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.1
Wordfence Security: by Wordfence – 6.3.20
WP All Import Pro: by Soflyy – 4.5.0
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.7 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #84875 - /
Cart: #85022 - /cart/
Checkout: #85023 - /checkout/
My account: #8 - /my-account-2/
Terms and conditions: #8491 - /terms-of-service/

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Condition: Defaults to "new".
Brand: Defaults to "Unbranded". Pre-populates from "pa_brand taxonomy".
Manufacturer Part Number (MPN): Pre-populates from "pa_mpn taxonomy".
Product Type: Defaults to "Mature > Erotic > Sex Toys".
Google Product Category: Defaults to "Mature > Erotic > Sex Toys".
Global Trade Item Number (GTIN): 
Age Group: Defaults to "adult".
Colour: Pre-populates from "pa_color taxonomy".
Size: Pre-populates from "pa_size taxonomy".
Bing Category: Defaults to "Arts & Entertainment > Adult Entertainment".

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: No
`

**Comment by mikejolley** [comment]
WP has a real "uncategorized" category to assign posts to in the posts section. Product categories do not have this, so the filter is not possible. 

This could be posted on the ideas board here http://ideas.woocommerce.com/forums/133476-woocommerce There are no requests for an uncategorized category yet however so I'm not sure if it's popular or too niche to include in core.

If you wanted to add this custom, `woocommerce_json_search_found_categories` hook could be used to return it, and then you could customise the search.

Thanks!

**Comment by 8ATE** [comment]
Prior to the recent update, uncategorized was an option in the filter by
category when it was a drop down menu and now it's not.

**Comment by 8ATE** [comment]
Also, we are no longer able to sort on uncategorized products with this new update.

**Comment by mikejolley** [comment]
Right, before it was made performant using ajax. Bringing a uncategorized option after this change would require the category as stated in my previous comment.

**Comment by Bojan121** [comment]
I don't understand how something like this can be simply removed without an alternative with a single update... 
So let's say I deleted a category. Now all products in that category are ghosts, they cannot be found in the products admin page because we can't filter by empty category and we can't sort by category either.

**So let's say I have 20k products, The question is, how can I find the products with no category, other than directly messing with the DB?**

And WP already having "uncategorized" category is not an issue, the category name can simply be different.

**Comment by gadgetmanmatt** [comment]
I agree with Bojan121, I have a customer spitting fire because the 'uncategorized' selector has been removed and 'when is it going to be put back again'. What do I tell them?

**Comment by 8ATE** [comment]
We think this ticket had been closed. Have everyone start telling them.
It's such a hardship for us right now and we're a small business.

On Nov 8, 2017 9:21 AM, "gadgetmanmatt" <notifications@github.com> wrote:

I agree with Bojan121, I have a customer spitting fire because the
'uncategorized' selector has been removed and 'when is it going to be put
back again'. What do I tell them?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/woocommerce/woocommerce/issues/17321#issuecomment-342831422>,
or mute the thread

**Comment by gadgetmanmatt** [comment]
Same here, chasing around the ether over problems like this are the last thing I want to be doing and removing functionality is very irritating.

**Comment by mikejolley** [comment]
Any of you folks with clients are welcome to submit a PR - you can resolve https://github.com/woocommerce/woocommerce/issues/17348 whilst at it, since it's related :)

**Comment by gadgetmanmatt** [comment]
@mikejolley I wouldn't know where to start?? Can you give a quick overview of what I would need to do?

**Comment by mikejolley** [comment]
To raise a PR or code it?

**Comment by gadgetmanmatt** [comment]
To raise a PR

**Comment by mikejolley** [comment]
This covers it I think https://help.github.com/articles/creating-a-pull-request/ You need to fork and make the code changes first.

**Comment by Radfoot** [comment]
Mike Jolleys you have for make confusion for me. I am no longer have filters for uncatagory product (in another way I mean filter for a list of product that is for the current not in a category). I in the past have able for this properly but you remove it, maybe you are angry about something? Why you remove it? I want this back so how can I have this back as it is very important for me? You say I have to write a press release or fix it by write code myself? I cannot do this. Help me,
I forget to say please so here it is...please. Thank

**Comment by mikejolley** [comment]
PR is not a "press release", it's a pull request. To contribute code to WooCommerce core. Anyhow, we've already tackled this in v3.3 due out next year,
