### ISSUE TITLE
Big problem in display product images in RTL

### ISSUE THREAD

**Issue by parsmizban** [woocommerce/woocommerce#17325]
Hi,

There is a big problem when we use image gallery in RTL for single product view,

When we add more than 1 image to the gallery, WooCommerce displays just thumbnails in bottom and no full size in top of them

I tested this on other themes, like Storefront, The issue is same in those themes too
But there isn’t any problem in Left to Right
This happen just in Right To Left languages

But when I add just 1 image to the gallery, This problem doesn’t happen
Please check this ASAP because many RTL sites have this problem

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17263
