### ISSUE TITLE
Media Library loads very slowly on v >= 3.1.0

### ISSUE THREAD

**Issue by ahtcx** [woocommerce/woocommerce#17337]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install any WooCommerce version >= 3.1.0
2. Click on any UI area that opens the Media Library UI (such as the "Add Media" button on HTML input boxes)

## Expected/actual behavior

When I follow those steps, when using the media library UI to add images to articles, it takes about 50 seconds to load the previews for about 150 images.

I was expecting to see it load very fast.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

### WordPress Environment ###

Home URL: https://www.gaigeard.fr
Site URL: https://www.gaigeard.fr
WC Version: 3.0.9
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.57 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.9
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Redux Framework: par Team Redux – 3.6.7.7
Ultimate Addons for Visual Composer: par Brainstorm Force – 3.16.18
Akismet Anti-Spam: par Automattic – 4.0
Cloudflare: par John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.1

Contact Form 7: par Takayuki Miyoshi – 4.9
WooCommerce Continue Shopping: par HappyKite – 1.2
Easy WP SMTP: par wpecommerce – 1.3.0
Editor Menu and Widget Access: par Guy Primavera – 2.3.2
Envato Market: par Derek Herman – 1.0.0-RC2
WPBakery Page Builder: par Michael M - WPBakery.com – 5.4.2
Loco Translate: par Tim Whitlock – 2.0.16
MailChimp for WordPress: par ibericode – 4.1.10
Really Simple SSL: par Rogier Lankhorst – 2.5.22
W3 Total Cache: par Frederick Townes – 0.9.5.4
WC Fields Factory: par Saravana Kumar K – 1.4.0
WooCommerce Checkout Manager: par Visser Labs – 4.1.6
WooCommerce Stripe Gateway: par WooCommerce – 3.2.3
WooCommerce Membership: par RightPress – 2.2.3
WooCommerce Local Pickup Plus: par SkyVerge – 2.3.0
WooCommerce: par Automattic – 3.0.9 – 3.2.1 est disponible
WooCommerce Helper: par WooCommerce – 1.7.2 – Réseau activé
Wowmall Fontello Icons Importer: par  – 1.0.1
Wowmall Shortcodes: par  – 1.3.8
WP Rollback: par WordImpress – 1.5
WP Smush: par WPMU DEV – 2.7.6

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base boutique: #25 - /boutique/
Panier: #32 - /panier/
Commande: #34 - /commande/
Mon compte: #41 - /compte/

### Theme ###

Name: Gaigeard
Version: 1.0.0
Author URL: https://htcx.co/
Child Theme: ✔
Parent Theme Name: Wowmall
Parent Theme Version: 1.3.8
Parent Theme Author URL: https://themeforest.net/user/etheme/portfolio
WooCommerce Support: ✔

### Templates ###

Overrides: wowmall/woocommerce/archive-product.php
wowmall/woocommerce/cart/cart-empty.php
wowmall/woocommerce/cart/cart-totals.php
wowmall/woocommerce/cart/cart.php
wowmall/woocommerce/cart/cross-sells.php
wowmall/woocommerce/cart/mini-cart.php
wowmall/woocommerce/cart/proceed-to-checkout-button.php
wowmall/woocommerce/cart/shipping-calculator.php
wowmall/woocommerce/checkout/form-billing.php
wowmall/woocommerce/checkout/form-checkout.php
wowmall/woocommerce/checkout/form-coupon.php
wowmall/woocommerce/checkout/form-login.php
wowmall/woocommerce/checkout/form-shipping.php
wowmall/woocommerce/checkout/review-order.php
wowmall/woocommerce/content-widget-product.php
wowmall/woocommerce/global/form-login.php
wowmall/woocommerce/global/quantity-input.php
wowmall/woocommerce/loop/loop-end.php
wowmall/woocommerce/loop/loop-start.php
wowmall/woocommerce/loop/no-products-found.php
wowmall/woocommerce/loop/pagination.php
wowmall/woocommerce/myaccount/downloads.php
wowmall/woocommerce/myaccount/form-edit-account.php
wowmall/woocommerce/myaccount/form-edit-address.php
wowmall/woocommerce/myaccount/form-login.php
wowmall/woocommerce/myaccount/form-lost-password.php
wowmall/woocommerce/myaccount/form-reset-password.php
wowmall/woocommerce/myaccount/lost-password-confirmation.php
wowmall/woocommerce/myaccount/my-account.php
wowmall/woocommerce/myaccount/my-address.php
wowmall/woocommerce/myaccount/orders.php
wowmall/woocommerce/order/order-again.php
wowmall/woocommerce/order/order-details-customer.php
wowmall/woocommerce/order/order-details-item.php
wowmall/woocommerce/order/order-details.php
wowmall/woocommerce/product-searchform.php
wowmall/woocommerce/single-product/add-to-cart/external.php
wowmall/woocommerce/single-product/add-to-cart/grouped.php
wowmall/woocommerce/single-product/add-to-cart/simple.php
wowmall/woocommerce/single-product/add-to-cart/variable.php
wowmall/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
wowmall/woocommerce/single-product/product-image.php
wowmall/woocommerce/single-product/related.php
wowmall/woocommerce/single-product/review-meta.php
wowmall/woocommerce/single-product/up-sells.php
wowmall/woocommerce/single-product-reviews.php
</details>

## Information

Some change between 3.0.9 and 3.1.0 causes the Media Library UI to be very slow to load the thumbnails. This is still true with all other plugins disabled and the default Storefront theme. When on version 3.0.9 the Media Library is perfectly fine though. I'm not the only person to have this problem, I found 1 other occurence on a (now deleted) WordPress Stack Exchange question [here](https://webcache.googleusercontent.com/search?q=cache:b5LNjrWvy6cJ:https://wordpress.stackexchange.com/questions/278448/woocommerce-is-slowing-down-media-library/278464+&cd=2&hl=en&ct=clnk&gl=us).

**Comment by mikejolley** [comment]
Thats funny, the Stack Exchange question is newer than this issue.

**Comment by ahtcx** [comment]
@mikejolley it isn't, that's just how Google cached the page, I link to the cached page because it got deleted. If you hover over the "3 minutes ago" 2017-08-29.

**Comment by mikejolley** [comment]
May be related to these after tracing back https://github.com/woocommerce/woocommerce/compare/253bb07...984ed08

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17358
