### ISSUE TITLE
Cents added to discount when the woocommerce_coupon_get_discount_amount filter is used.

### ISSUE THREAD

**Issue by soft79** [woocommerce/woocommerce#17330]
Hi,

I have a plugin that allows coupon-discounts to be limited. For example: Limit discount to every 3rd item in the cart. This plugin uses woocommerce_coupon_get_discount_amount to achieve this. Since WC 3.2 the discount is a couple of cents off. 

I found that the issue occurs because WC_Discounts::apply_coupon_remainder() is called from WC_Discounts::apply_coupon_percent().

## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a 20% discount coupon
2. Create a filter that limits the applied discount; e.g. this will divide the discount by two:
`add_filter('woocommerce_coupon_get_discount_amount', function ( $discount ) { return $discount / 2; });`
3. Add some products to the cart and apply the coupon.

## Expected/actual behavior

Expected: A discount of exactly 10%. If the cart total is for example $ 200.00 the expected discount should be $ 20. 

Actual: Instead $ 20.04 is discounted. (one cent extra for every item in the cart)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Latest WC master from Github. On WP 4.8.2 / PHP 7.0.24.
```
</details>

**Comment by mikejolley** [comment]
Won't have time to look at this one yet but it would be good to get a little more detail to reproduce, i.e. what plugin. Otherwise someone has to write custom code just to replicate the issue....

Is it yours? Have you considered trying to fix it and submitting a PR, if your plugin relies on this logic?

**Comment by soft79** [comment]
The plugin is not needed to reproduce; the add_filter I provided in 'steps to reproduce' is enough. I  hope next weekend I can find some time to find a solution...

**Comment by mikejolley** [comment]
I'll handle it.

**Comment by mikejolley** [comment]
Handled in https://github.com/woocommerce/woocommerce/pull/17331/files

**Comment by soft79** [comment]
Great! Thanks, I'll check it out.
