### ISSUE TITLE
Aramex Shipping Method not calculating the rates correctly.

### ISSUE THREAD

**Issue by Tashhalfpint** [woocommerce/woocommerce#17336]
I am hoping someone on this forum can help me...

I have created a wordpress website fabscraps.com and the store sells scrapbooking equipments including papers and materials. 

Although it is giving me issues when the shipping method starts.

As a visual example:
If you purchase 10 pieces of paper the shipping is being calculated as if the pieces of paper are being sent in a thin box laid out next to each other rather than the 10 sheets being stacked ontop of eachother therefore it is coming up with ridiculously high rates for shipping because the surface area is so much bigger than the pages being stacked. 

Are there any solutions to this or should i be using a different platform to make the website and not woocommerce? The company has requested i use the Aramex plugin as that is who they use for their shipping needs. Please if anyone can help or give me solutions, i am so so desparate.

**Comment by kloon** [comment]
Please contact the developers of the Aramex Shipping Calculator for support on this. This is only for issues related to WooCommerce Core and not extensions or any customisations.
