### ISSUE TITLE
Migrate / Export / Import Global Product Attributes

### ISSUE THREAD

**Issue by surferking** [woocommerce/woocommerce#17338]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have Googled a lot
- [x] I have had a chat with a Woocommerce agent on Livechat
- [x] I've been recommended to report the issue here
- [x] I really only ever post anything as a last resort

## Steps to reproduce the issue

Try and export (global) Attributes from one Woocommerce install and import to another:
/wp-admin/edit.php?post_type=product&page=product_attributes

## Expected/actual behavior

I was hoping there would be a quick way to do this, but a simple copy of the '_woocommerce_attribute_taxonomies' table values does not seem to be sufficient to re-register the Attributes with the site imported to. Documentation doesn't seem to be enlightening.

I have 94 Glocal Attributes to migrate, I hope it is reasonable to expect there to either be a Export/Import solution or for the data structure and registration to be standardised to Wordpress conventions in a way that other common export & import plugins can work with it.

All export / import solutions will get the data out and back into '_woocommerce_attribute_taxonomies' but that does not seem to be sufficient to register them as available to use as custom taxonomies again.

The Product Export / Import will re-create all Attributes as Local without the Global ones registered first, which is a large amount of unnecessary duplicate data that loses the benefit of Global Attributes.

## Isolating the problem

I tried a simple export of a single product with many Attributes & Values and then re-importing - but Global Attributes still have to be re-created manually.

WP Export doesn't support this custom data structure.

## WordPress Environment

All the latest versions, I believe it is a design issue and not a version or conflict issue.

Happy to copy to Feature Requests - but it could be that there's an opportunity to review the data-structure, process and documentation from this ticket given the difficulty I seem to have found in seeking a solution due to the custom data structure and see if could be normalised to within the standard Wordpress ways that would enable Export & Import (perhaps in a similar way that Metabox.io's free open-source plugins [MB Custom Taxonomies](https://wordpress.org/plugins/mb-custom-taxonomy/) & [MB Custom Post Types](https://wordpress.org/plugins/mb-custom-post-type/) do)

**Comment by mikejolley** [comment]
Hi

1. There is no standard WP way to define custom **user defined** taxonomies.
2. The product importer/exporter will create global attributes after importing products if you define the 'global column for each attribute. See https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema If used, the taxonomy/attribute will be created.
3. Import the dummy data (CSV) for an example in action.
4. The XML importer tool also creates global attributes if present in a similar way.
5. You can import the table via the database, but transient cache will need to be flushed to see the new attributes after import. You can clear caches in WC > System > Tools

I think we've covered everything.

Thanks

**Comment by itsgauravjain22** [comment]
While importing products, the previous importing map was good for custom attributes. Now woocommerce make the process of importing products much more cumbersome. A repeating column name in custom attribute in every row makes no sense of improvement and easier importing.

**Comment by mikejolley** [comment]
Find an alternative importer that suits your needs in that case. Both ways have pros and cons.
