### ISSUE TITLE
Image zoom / custom options

### ISSUE THREAD

**Issue by martinsnajdr** [woocommerce/woocommerce#17349]
There should be a possiblity to tweak the image zoom (jQuery plugin) options. Right now you can only disable / enable the zoom functionality itself, but for example you are not able to change the mouseover trigger to something else (click / toggle etc.) or the magnify value. 

It should be filterable like the flexslider options.

**Comment by mikejolley** [comment]
Why not send a PR then?

**Comment by mikejolley** [comment]
@martinsnajdr @pawelkmpt Is someone interested in submitting a PR for this? Semi related to https://github.com/woocommerce/woocommerce/issues/17656

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/17656
