### ISSUE TITLE
WooCommerce Order Search not working ? I don't know why ? 

### ISSUE THREAD

**Issue by MuhammadUmairghufran** [woocommerce/woocommerce#17343]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to Woo commerce >> Order
2.  Search any query " "
3.  they response nothing 

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by kloon** [comment]
Not getting the same results with 3.2.1 or the master branch. I'd suggest you disable all plugins on your site and switch your theme to a default one and test. Changes are a plugin or theme is causing this on your site.
