### ISSUE TITLE
Inserting 3 new hooks for shop_orders  management

### ISSUE THREAD

**Issue by franciscof5** [woocommerce/woocommerce#17340]
Woocommerce is great, but some users want shop_orders to have it's own table on database, that is a special case scenario and tons of discussions about how and what to do in the following scenario: overwriting local changes to production server overwrites (erases) shop_orders, it is technically not possible to get changes and then upload because of the AUTO_INCREMENT conflicts problems.

`CASE 1: Shop manager inserted new product in woocommerce and want to upload it to remote server, it is impossible, conflicts with ID of posts may surge.`
`CASE 1 SOLUTION: separated shop_orders, shop manager can safely create and modify local products and then upload it to production server without loose any shop_order.`

After lots of tests I found 3 simple hooks for order management to **$wpdb->posts** and **$wpdb->postmeta** tables to point to a different table, then returning to regular tables. It is working very well with help of my custom plugin that take cares of data management, f5sites shared posts tables and upload folder (open source on github as well)

Hooked functions: set_product_id, wc_get_order, wc_get_orders, get_order_report_data

RESUME: I need to insert 3 new hooks on woo core, I know this is more like a hacking solution, changing woocommerce core functions and wordpress data management principles, but works, I don’t want to replace that hooks every time I update woocommerce.

**Comment by kloon** [comment]
Datastores are your friend 😄  We built them just for this scenario. You will need to extend the the product data store via the filter woocommerce_data_stores.

See https://github.com/woocommerce/woocommerce/blob/a4d3518a61981adab3352195e36a97ba6bc42ae7/includes/class-wc-data-store.php#L73 and as an example of how we override it via our unit tests see https://github.com/woocommerce/woocommerce/blob/71d0702523bcc365403dd3b84b945da5218d88b4/tests/unit-tests/crud/data-store.php#L79

By following that you will be able to create, read, update and delete from your own tables.
