### ISSUE TITLE
Images won't show on product page when adding more than one image #17301

### ISSUE THREAD

**Issue by ronenla** [woocommerce/woocommerce#17346]
Issue #17301 was closed and I'm not sure if it is still followed - adding here a follow up in case there's a way to re-open:

There was one key element missing in the description of reproducing the item that I added in comments after issue was closed:

It only happens with wordpress version of RTL language, in my case hebrew ( https://he.wordpress.org/releases/ ).
This important info was missing before issue was closed.
Enabling English hides the issue.

Can you please take a look again in the description of issue #17301 ?

Thanks.

**Comment by kloon** [comment]
Thanks for clarifying it was related to RTL. This was fixed in #17263. I just tested it to confirm. If you are confident you can apply that patch manually in the meantime, we will be releasing it with 3.2.2 this week.
