### ISSUE TITLE
productadmin: category sorting (wc 3.2) 

### ISSUE THREAD

**Issue by oblaum** [woocommerce/woocommerce#17348]
wc 3.2 introduces in the product admin list the category ajax search. this is good for large project for performance reasons.

for smaller projects working with the ajax search is now much slower than the previous category list.
as i have to type 3 letters, wait for the result, click on the category word. instead of just seeing all categories as a tree.

it would be good to have a setting to choose which solution (search or list) works best for each project. or at least a recent search list.

or is there a function for this?

**Comment by mikejolley** [comment]
Solution:

- Add threshold filter
- Render as category dropdown if lower than threshold, or AJAX if above.

**Comment by oblaum** [comment]
that would be great!

**Comment by oblaum** [comment]
hello mike,

3.3.0 is scheduled for 10th jan 2018+

is there any chance for a quick solution? e.g. copy/paste an old codesnipplet on the place of the new one?

thanks
oli

**Comment by mikejolley** [comment]
You can do it yourself and take the code from 3.1, but I don't have a snippet to give you.
