### ISSUE TITLE
Updated user's address in admin isn't updated in checkout

### ISSUE THREAD

**Issue by oliverstapelfeldt** [woocommerce/woocommerce#17354]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Place an order
2. In admin change user's billing first name

## Expected/actual behavior

When I follow those steps, I see...

In checkout the name isn't updated because of the session

I was expecting to see...

The updated name

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost:8888/master/wordpress
Site URL: http://localhost:8888/master/wordpress
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.0.15 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.0.15
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.49MB
Database Data Size: 0.69MB
Database Index Size: 0.80MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.19MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 1
page: 5
post: 2
product: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://de.wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
Why would the admin do this for another user? How would the user feel if they were checking out and someone changed their address during this process?

Seems edge case to me.

**Comment by oliverstapelfeldt** [comment]
Hello Mike,

the use case is B2B where the customers aren't allowed to change their address.

**Comment by mikejolley** [comment]
Presumably the checkout fields are still editable so how does that even work without customisation?

**Comment by oliverstapelfeldt** [comment]
I check if the user has entered the address (he can for the first time) and if I set the fields readonly.

**Comment by mikejolley** [comment]
Readonly fields are still editable with a little knowledge of the DOM. It sounds like really you need to remove these fields and hardcode the address for the user, disallowing user input entirely. This is further to your current customisation.

Generally, I don't think this should be changed. If the data can be changed by someone else without knowledge, it could lead to errors.

FWIW we do already handle cases where the checkout fields are updated if the user changes their own address.

Thanks

**Comment by oliverstapelfeldt** [comment]
Hello Mike,

what errors do you mean?

**Comment by mikejolley** [comment]
My example of an address being changed mid-checkout so the submitted data does not match what the user wanted to submit.

**Comment by oliverstapelfeldt** [comment]
I see, but don't you think that an address which isn't updated when changed for good reason weighs more than a malicious change?

**Comment by mikejolley** [comment]
TBH I think this request is specific to your use case and customisation.

**Comment by oliverstapelfeldt** [comment]
👍

Could you then please show me/my client the best solution to get it updated?
Deleting all sessions in tools works but isn't good because of the carts. Deleting only the user-session in users works, too and the cart remains but therefor the user hast to be logged in.

**Comment by mikejolley** [comment]
The session is specific to the user, so I don't think clearing those will work. As I suggested earlier, you should remove those fields from checkout and set the values once the order gets placed.

**Comment by oliverstapelfeldt** [comment]
Thank you so far!

Will it then be updated everytime my client changes it in admin?

**Comment by oliverstapelfeldt** [comment]
Hello Mike,

I've tested it through:

- The new address is shown in checkout if you update it in admin while there's no session for this user in woocommerce_sessions
- If there's a session the new address is shown in checkout if you update it in admin and in the session

What do you think of this compromise?
- Only while logging in check if there's a session
- Update the session with the data in admin

Could you please implement this in favor of whatever reasons shop owners have for changing customer's data?

Thank you, Olli
