### ISSUE TITLE
WC_Cart->fees and WC_Cart::get_checkout_url is deprecated

### ISSUE THREAD

**Issue by warrentaniza** [woocommerce/woocommerce#17357]
![capture](https://user-images.githubusercontent.com/25402500/31951114-cb9929ba-b90f-11e7-8e5d-1af45b7d416a.PNG)

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Due to an outdated extension.

https://github.com/woocommerce/woocommerce/wiki/Deprecation-in-core#warnings-in-production-store-owners-read-this
