### ISSUE TITLE
Import CSV and Column headers vs import tool headers

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#17351]
From 750088-zen. Looks like the wiki just needs a little updating. 

---

Hi there,

I started exploring the builtin CSV product import in woocommerce. I found inconsistencies in the documentation vs the import tool. Im running a default WP site with only woocommerce plugin active on the default storefront theme.

Column headers vs the docs ! 
The docs (https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema) are incomplete or not updated. The import tool has more columns/different naming. 
For example in the import tool there is a header called "Position". This has not been explained in the docs....

Column headings in csv file are also inconsistent 
For example (in the dummy csv sample) you find a column called "status". In the docs you find this : 
CSV Column Name . Product Properties 
Published status

This should be reversed imho.

Plus, the order of the columns in the import tool SELECT dropdown is different then the docs.
Here is the Import tool SELECT dropdown order:

ID 
Type 
SKU 
Name 
Published 
Is featured? 
Visibility in catalog 
Short description 
Description 
Regular price 
Sale price 
Date sale price starts 
Date sale price ends 
Tax status 
Tax class 
In stock? 
Stock 
Backorders allowed? 
Sold individually? 
Weight (g) 
Length (cm) 
Width (cm) 
Height (cm) 
Categories 
Tags 
Shipping class 
Images 
Parent 
Upsells 
Cross-sells 
Grouped products 
External URL 
Button text 
Download name 
Download URL 
Download limit 
Download expiry days 
Attribute name 
Attribute value(s) 
Is a global attribute? 
Attribute visibility 
Default attribute 
Allow customer reviews? 
Purchase note 
Import as meta 
Position

**Comment by mikejolley** [comment]
There is no 'status' column in dummy data. Updating wiki with position. You should also have wiki editing access if needed.
