### ISSUE TITLE
Extra padding in order table in email template

### ISSUE THREAD

**Issue by Jpegtobbe** [woocommerce/woocommerce#17362]
## Steps to reproduce the issue

When looking on the email reciept of the order in Outlook, there is an extra padding in the order rows cells.
In the template file email-order-details.php there is this row:
`<table class="td" cellspacing="0" cellpadding="6" style="width: 100%; font-family: 'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif; margin-bottom: 40px;" border="1">`

That margin-bottom:40px will be inherited in the td:s in the table. And it acts as if it was a padding-bottom:40px in all the td:s .. so it looks lika a lot of spacing in the order table. It looks correct in Gmail but not in Microsoft clients as Outlook.

## WordPress Environment

<details>
WooCommerce 3.2.1
</details>

**Comment by mikejolley** [comment]
Inline styles are not inherited by child elements.

Screenshot?

**Comment by Jpegtobbe** [comment]
No normally they are not inherited. But in Outlook it seams there is a bug.
I have a screenshot here: https://www.dropbox.com/s/lkj4vtwo1xtcc9c/WooCommerce_email_bug_Outlook.png?dl=0

I preview the email before and after in Word, as that is the same HTML engine as in Outlook.

After removing the newly added margin-bottom:40px the email template works again for outlook clients.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17395
