### ISSUE TITLE
wc_get_product_terms returns outdated data from cache.

### ISSUE THREAD

**Issue by smazur** [woocommerce/woocommerce#17369]
https://github.com/woocommerce/woocommerce/blob/f8552ebbad227293c7b819bc4b06cbb6deb2c725/includes/wc-term-functions.php#L81

Whe user changes product attributes wc_get_product_terms returns old data. Looks like there no cache invalidation. Please check.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/17372
