### ISSUE TITLE
Undefined index: tax thrown by Query Monitor

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#17367]
If we disable taxes and view `admin.php?page=wc-settings&tab=tax` although the nav is not available but some addon may link those. See query monitor error message for screen-reader-text in settings page HTML :)

![capture](https://user-images.githubusercontent.com/3774827/31981161-19efa484-b971-11e7-96b6-86133d1b8ffb.PNG)

**Comment by mikejolley** [comment]
You can go to any tab to replicate. e.g. `http://local.wordpress.dev/wp-admin/admin.php?page=wc-settings&tab=derp`

**Comment by shivapoudel** [comment]
Exactly but if we go to tax tab then the there is a output of all the setting althouth we haven't enable tax. Something to prevent that settings field would be appreciated :)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17371
