### ISSUE TITLE
Wizard: Remove PayPal Standard from payment step

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce#17374]
~We should add copy to explain the difference between the two PayPal options we display in the wizard, and inform them which is best to choose.~

@pmaiorana also suggested removing one of them in certain circumstances - "remove Standard from the wizard"

**Comment by pmaiorana** [comment]
Actually, I think we should create a new issue or rewrite this one -- we're going to remove PayPal Standard entirely.

**Comment by mikejolley** [comment]
@pmaiorana Timeline on that?

**Comment by v18** [comment]
cc @jeffstieler - this sounds like it would be in the realm of Hydra's wizard responsibility

**Comment by pmaiorana** [comment]
Heh I was going to ping @jeffstieler and see if that's something we can do this quarter for release with 3.3. Seems like a pretty small thing?

**Comment by v18** [comment]
@pmaiorana yeh, it is 👍

**Comment by mikejolley** [comment]
@dechov PayPal Standard can be removed in all cases except where a user cannot install plugins. In this case, Express Checkout is hidden.

`get_wizard_in_cart_payment_gateways` is looking a bit messy right now. This could use a refactor when making the above change.

**Comment by dechov** [comment]
One thing to confirm about "featured" gateways, the ones at the top that were meant to stand out from the rest:

Right now the only "featured" gateway is Stripe, and only if it's opt-out at the top:

<img width="664" alt="screen shot 2017-12-12 at 1 50 36 pm" src="https://user-images.githubusercontent.com/1867547/33903392-3c4290fa-df46-11e7-9368-fb98eb60a737.png">

If Klarna or Square is at top (and emphasized with a black background), then nothing is "featured":

<img width="662" alt="screen shot 2017-12-12 at 1 52 42 pm" src="https://user-images.githubusercontent.com/1867547/33903400-47633e94-df46-11e7-8851-92320c32ef9a.png">

If we omit PayPal Standard (as in https://github.com/woocommerce/woocommerce/pull/18123), the top two options are both opt-out but each one is isolated:

<img width="656" alt="screen shot 2017-12-12 at 2 01 15 pm" src="https://user-images.githubusercontent.com/1867547/33903584-d0727d80-df46-11e7-9504-488027eefacd.png">

Any changes called for? (cc @kellychoffman)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18123 Just needs tests.
