### ISSUE TITLE
Woocommerce / Unable to check out on mobile

### ISSUE THREAD

**Issue by traingoo** [woocommerce/woocommerce#17370]
Hello
Our site is using Woocommerce shopping cart, we have received customer report they were unable to fill the Phone and Email address column on mobile since 27Sep, we have updated to newest version but it is still the same, please help to figure it out where is the problem/bugs
Sorry for inconvenience, but I am facing this issue and it is causing huge loss to my business.
I am using WordPress version 4.8.2, , Woo commerce: Version 3.1.2 .

http://www.joinfit.hk/
Please help with it is causing business loss.

**Comment by mikejolley** [comment]
The mobile experience is highly dependent on the theme you're using. That said, I just tested and could proceed to paypal as expected. I suggest you work with the customer to find out what problem they had exactly.

Thanks

**Comment by traingoo** [comment]
May i know if you used mobile to check out? Thanks.

**Comment by mikejolley** [comment]
Yes, I used chrome on android.
