### ISSUE TITLE
Password Reset is outputting a warning Headers already sent in case invalid token

### ISSUE THREAD

**Issue by B1-0S** [woocommerce/woocommerce#17379]
**Steps to reproduce:**
1. Click on my account
2. Click on forgot password link and reset your password.
3. Reset the password by clicking the link in mail and input the new password
4. Click again on the same reset password link from the mail

Expected result:  "Invalid key" Error message is displayed for expired reset password link.
Actual result: **Warning!** and "Invalid key" messages are displayed.

Note: The error output below is from a WAMP but the behavior for a server env. is the same.
         The test is done on clean WP, Latest WC (3.2.1) and Twenty Seventeen Theme

**Output**
Warning: Cannot modify header information - headers already sent by (output started at C:\wamp64\www\TESTWC\wp-includes\class.wp-styles.php:237) in C:\wamp64\www\TESTWC\wp-content\plugins\woocommerce\includes\shortcodes\class-wc-shortcode-my-account.php on line 353

1 | 0.0001 | 365728 | {main}( ) | ...\index.php:0
2 | 0.0002 | 367768 | require( 'C:\wamp64\www\TESTWC\wp-blog-header.php' ) | ...\index.php:17
3 | 0.3642 | 38748592 | require_once( 'C:\wamp64\www\TESTWC\wp-includes\template-loader.php' ) | ...\wp-blog-header.php:19
4 | 0.3676 | 38753992 | include( 'C:\wamp64\www\TESTWC\wp-content\themes\twentyseventeen\page.php' ) | ...\template-loader.php:74
5 | 0.3933 | 38971552 | get_template_part( ) | ...\page.php:27
6 | 0.3933 | 38972128 | locate_template( ) | ...\general-template.php:167
7 | 0.3936 | 38972256 | load_template( ) | ...\template.php:647
8 | 0.3939 | 38976144 | require( 'C:\wamp64\www\TESTWC\wp-content\themes\twentyseventeen\template-parts\page\content-page.php' ) | ...\template.php:690
9 | 0.3946 | 38977000 | the_content( ) | ...\content-page.php:22
10 | 0.3947 | 38977120 | apply_filters( ) | ...\post-template.php:240
11 | 0.3947 | 38977520 | WP_Hook->apply_filters( ) | ...\plugin.php:203
12 | 0.3949 | 38979200 | do_shortcode( ) | ...\class-wp-hook.php:298
13 | 0.3950 | 38982272 | preg_replace_callback ( ) | ...\shortcodes.php:223
14 | 0.3950 | 38982912 | do_shortcode_tag( ) | ...\shortcodes.php:223
15 | 0.3950 | 38982912 | WC_Shortcodes::my_account( ) | ...\shortcodes.php:345
16 | 0.3950 | 38983288 | WC_Shortcodes::shortcode_wrapper( ) | ...\class-wc-shortcodes.php:119
17 | 0.3963 | 39129352 | WC_Shortcode_My_Account::output( ) | ...\class-wc-shortcodes.php:76
18 | 0.3963 | 39129384 | WC_Shortcode_My_Account::lost_password( ) | ...\class-wc-shortcode-my-account.php:55
19 | 0.3969 | 39100384 | WC_Shortcode_My_Account::set_reset_password_cookie( ) | ...\class-wc-shortcode-my-account.php:220
20 | 0.3969 | 39100584 | setcookie ( ) | ...\class-wc-shortcode-my-account.php:353

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/17396
