### ISSUE TITLE
WooCommerce Tax Issue ?

### ISSUE THREAD

**Issue by dashpatel21** [woocommerce/woocommerce#17387]
Since I have developed my website, It was going so good, but finally when I came on the Tax module, I have configures all the settings as it should be, but I am unable to see the tax that has been added in the product.

Hope for the best solution.

**Comment by mikejolley** [comment]
Check the 'default customer location' setting and set this to 'store base location'. This will make taxes match your store address, rather than the geolocated address. Either way, taxes will update during checkout when the customer provides their actual address.

Thanks
