### ISSUE TITLE
woocommerce API ionic POST error 401  Ask

### ISSUE THREAD

**Issue by HarounOujihi** [woocommerce/woocommerce#17386]
Hi, i use woocommerce api on ionic app
(using nodejs module https://www.npmjs.com/package/woocommerce-api )
**# and all GET works but POST dosen't !!**
i've tried :

```
wc.postAsync('products', data).then((data) =>  {
       ...
}, (err) => { console.log('Error : ', err);  });
```
and i get 401 error
my you help me to fix that ?
thanks :)

**Comment by mikejolley** [comment]
As stated in past issues, ionic is from a third party and we provide no direct support for this. You should ask them.

**Comment by HarounOujihi** [comment]
Mr @mikejolley , i cant even make it with post man :/

is there anything i do it wrong ?

**Comment by HarounOujihi** [comment]
@mikejolley , @claudiosanches can you please help me to fix this ?
i try get with postman and its ok

but i couldn't make post !

this is what i have done :

![screenshot from 2017-10-26 15-10-14](https://user-images.githubusercontent.com/8462394/32052151-faf114f6-ba5f-11e7-9f83-2db6c685158c.png)

![screenshot from 2017-10-26 15-10-22](https://user-images.githubusercontent.com/8462394/32052162-03109634-ba60-11e7-8679-7f872dc26dab.png)

Thank you to save my life :)

**Comment by claudiosanches** [comment]
@HarounOujihi so maybe something wrong on your server, since I just tested it and works just fine.

**Comment by HarounOujihi** [comment]
@claudiosanches, thank you for your answer
i've tried to send post and dump it and its ok

is that how to test my server side ?
this is the subdomain i make my wc project
**shine-food**.apps.pql.me

**Comment by mikejolley** [comment]
Follow the instructions and troubleshooting steps in https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API The API is working.
