### ISSUE TITLE
Cart page keeps refreshing after updating to 3.2.1

### ISSUE THREAD

**Issue by rafaelcmrj** [woocommerce/woocommerce#17393]
My cart page (only the cart page) keeps refreshing after updated to 3.2.1. I already changed the Geolocation thing in the admin but the problem persists. I did see that the cart.js file has an if statement to check if .woocommerce-cart-form exists. I double-checked my cart page and the class is there.

**Comment by mikejolley** [comment]
Please read the content on https://github.com/woocommerce/woocommerce/issues/new - you're missing a tonne of details in this report. There is no where near enough info here for us to look into.

System status report
How to reproduce
Site URL

**Comment by rafaelcmrj** [comment]
@mikejolley sorry for missing information. Here we go:

How to reproduce: Just go to my cart page: https://staging.beckertime.com/cart
Site URL: https://staging.beckertime.com or Shop Page https://staging.beckertime.com/buy-used-rolex

System status report:

`
### WordPress Environment ###

Home URL: https://staging.beckertime.com
Site URL: https://staging.beckertime.com
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.4.2
WP Multisite: –
WP Memory Limit: 10 GB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.0
PHP Version: 7.0.4-7ubuntu2.1
PHP Post Max Size: 60 MB
PHP Time Limit: 60
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 60 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.8
WC Database Prefix: ec_
Total Database Size: 2208.09MB
Database Data Size: 1673.61MB
Database Index Size: 534.48MB
ec_woocommerce_sessions: Data: 315.78MB + Index: 15.52MB
ec_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
ec_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
ec_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
ec_woocommerce_order_items: Data: 1.52MB + Index: 0.33MB
ec_woocommerce_order_itemmeta: Data: 4.52MB + Index: 5.03MB
ec_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
ec_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
ec_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
ec_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
ec_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
ec_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
ec_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
ec_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ec_commentmeta: Data: 1.52MB + Index: 4.55MB
ec_comments: Data: 4.52MB + Index: 4.44MB
ec_ebay_accounts: Data: 0.02MB + Index: 0.00MB
ec_ebay_auctions: Data: 82.56MB + Index: 0.80MB
ec_ebay_categories: Data: 2.52MB + Index: 3.03MB
ec_ebay_jobs: Data: 14.52MB + Index: 0.00MB
ec_ebay_log: Data: 70.56MB + Index: 2.31MB
ec_ebay_messages: Data: 7.52MB + Index: 0.00MB
ec_ebay_orders: Data: 90.56MB + Index: 0.36MB
ec_ebay_payment: Data: 0.02MB + Index: 0.00MB
ec_ebay_profiles: Data: 0.19MB + Index: 0.00MB
ec_ebay_restriction: Data: 0.02MB + Index: 0.06MB
ec_ebay_shipping: Data: 0.02MB + Index: 0.00MB
ec_ebay_sites: Data: 0.05MB + Index: 0.00MB
ec_ebay_store_categories: Data: 0.05MB + Index: 0.03MB
ec_ebay_transactions: Data: 123.52MB + Index: 0.77MB
ec_et_social_stats: Data: 0.02MB + Index: 0.00MB
ec_ewwwio_images: Data: 59.61MB + Index: 38.13MB
ec_facetwp_index: Data: 8.48MB + Index: 6.95MB
ec_gf_addon_feed: Data: 0.00MB + Index: 0.00MB
ec_links: Data: 0.02MB + Index: 0.02MB
ec_masterslider_options: Data: 0.00MB + Index: 0.00MB
ec_masterslider_sliders: Data: 0.00MB + Index: 0.00MB
ec_options: Data: 297.75MB + Index: 41.13MB
ec_pl_product_templates: Data: 0.03MB + Index: 0.00MB
ec_pl_product_templates_attributes: Data: 74.33MB + Index: 0.01MB
ec_pl_product_templates_descriptions: Data: 0.05MB + Index: 0.00MB
ec_pl_product_templates_short_descriptions: Data: 0.02MB + Index: 0.00MB
ec_postmeta: Data: 188.69MB + Index: 72.22MB
ec_posts: Data: 80.63MB + Index: 31.14MB
ec_redirection_groups: Data: 0.02MB + Index: 0.03MB
ec_redirection_items: Data: 0.02MB + Index: 0.08MB
ec_redirection_logs: Data: 0.02MB + Index: 0.08MB
ec_redirection_modules: Data: 0.02MB + Index: 0.03MB
ec_relevanssi: Data: 0.00MB + Index: 0.00MB
ec_relevanssi_log: Data: 0.00MB + Index: 0.00MB
ec_relevanssi_stopwords: Data: 0.01MB + Index: 0.01MB
ec_rg_form: Data: 0.02MB + Index: 0.00MB
ec_rg_form_meta: Data: 0.05MB + Index: 0.00MB
ec_rg_form_view: Data: 0.42MB + Index: 0.33MB
ec_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
ec_rg_lead: Data: 0.36MB + Index: 0.09MB
ec_rg_lead_detail: Data: 1.52MB + Index: 2.22MB
ec_rg_lead_detail_long: Data: 0.16MB + Index: 0.00MB
ec_rg_lead_meta: Data: 0.09MB + Index: 0.13MB
ec_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
ec_so_tracking: Data: 0.02MB + Index: 0.03MB
ec_swp_cf: Data: 74.55MB + Index: 127.69MB
ec_swp_index: Data: 114.61MB + Index: 112.06MB
ec_swp_log: Data: 0.06MB + Index: 0.05MB
ec_swp_tax: Data: 11.52MB + Index: 20.55MB
ec_swp_terms: Data: 3.52MB + Index: 7.55MB
ec_termmeta: Data: 6.15MB + Index: 0.27MB
ec_terms: Data: 0.17MB + Index: 0.17MB
ec_term_relationships: Data: 7.52MB + Index: 7.52MB
ec_term_taxonomy: Data: 0.31MB + Index: 0.28MB
ec_usermeta: Data: 18.55MB + Index: 25.09MB
ec_users: Data: 2.52MB + Index: 3.03MB
ec_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB

### Post Type Counts ###

acf: 41
action-claim: 5
attachment: 65367
braintree_log: 1
ccpurge_log_entries: 614
follow_up_email: 7
frm_form_actions: 24
frm_styles: 1
global_product_addon: 6
glossary: 483
nav_menu_item: 156
page: 84
post: 674
product: 3780
revision: 2010
shop_coupon: 64
shop_order: 6731
shop_order_refund: 63
sidebar: 1
social-locker: 1
wc_product_tab: 7
wpseo_crawl_issue: 836

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Query Monitor: by John Blackbourn – 2.13.2
VaultPress: by Automattic – 1.8.5
Gravity Forms: by rocketgenius – 2.0.6
Advanced Custom Fields: Options Page: by Elliot Condon – 1.2.0
Advanced Custom Fields: Repeater Field: by Elliot Condon – 1.1.1
Advanced Custom Fields: by Elliot Condon – 4.4.8
Auto Terms of Service and Privacy Policy: by TourKick (Clifford P) – 1.8
BeckerTime Certificates Plugin: by Rafael Costa – 1.0.0
Cache Optimizer: by Rafael Costa – 1.0.0
CloudFlare(R) Cache Purge: by Bryan Shanaver @ fiftyandfifty.org – 1.2
CloudFlare: by Ian Pye
Jerome Chen
James Greene
Simon Moore
David Fritsch
John Wineman (CloudFlare Team) – 1.3.24

Disqus Comment System: by Disqus  – 2.85
FacetWP: by FacetWP
LLC – 2.8

GF Upload to Email Attachment: by Greg Whitehead – 2.1
Gravity Forms: Notification Attachments: by Timothy Wood (@codearachnid) – 1.5
Gravity Forms MailChimp Add-On: by rocketgenius – 3.7.1
Monarch Plugin: by Elegant Themes – 1.2
Optimus: by KeyCDN – 1.4.9
Price Monitor: by Rafael Costa – 1.0.0
Product Lister: by Rafael Costa – 1.0.0
SearchWP WooCommerce Integration: by SearchWP
LLC – 1.1.10 – Not tested with the active version of WooCommerce

SearchWP: by SearchWP
LLC – 2.8.10b2

Separator Shortcode And Widgets: by OTWthemes.com – 1.4
Simple 301 Redirects: by Scott Nellé – 1.07
What The File: by Never5 – 1.5.3
WooCommerce Ecommerce tracking for Google and Facebook: by Multidots – 1.0.1 – Not tested with the active version of WooCommerce
WooCommerce Braintree Payment Gateway: by Tomislav Leljak – 1.2.0 – Not tested with the active version of WooCommerce
WooCommerce Custom Field Product Search: by Alvaro Neto – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Affirm Gateway: by WooThemes – 1.0.0 – 1.1.0 is available – Not tested with the active version of WooCommerce
WooCommerce Amazon Pay Gateway: by WooCommerce – 1.7.3 – Not tested with the active version of WooCommerce
WooCommerce PayPal Express Gateway: by WooThemes / SkyVerge – 3.6.0 – 3.7.2 is available – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooThemes – 1.10.2 – 1.10.16 is available – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Lee Willis – 5.2.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.1
Yoast SEO: by Team Yoast – 3.9
WP-Lister Pro for eBay: by Matthias Krok – 2.0.9.20
WP-Mail-SMTP: by Callum Macdonald – 0.9.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #40325 - /shop/
Cart: #1160 - /cart/
Checkout: #1161 - /checkout/
My account: #1163 - /my-account/
Terms and conditions: #26 - /terms-and-conditions/

### Theme ###

Name: 
Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: awesome-beckertime/woocommerce/archive-product.php
awesome-beckertime/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.2.0
awesome-beckertime/woocommerce/cart/cart-totals.php
awesome-beckertime/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.1.0
awesome-beckertime/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/cart/proceed-to-checkout-button.php
awesome-beckertime/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.2.0
awesome-beckertime/woocommerce/checkout/cart-errors.php
awesome-beckertime/woocommerce/checkout/form-billing.php version 2.1.2 is out of date. The core version is 3.0.9
awesome-beckertime/woocommerce/checkout/form-checkout.php
awesome-beckertime/woocommerce/checkout/form-coupon.php
awesome-beckertime/woocommerce/checkout/form-login.php
awesome-beckertime/woocommerce/checkout/form-pay.php
awesome-beckertime/woocommerce/checkout/form-shipping.php
awesome-beckertime/woocommerce/checkout/payment-method.php
awesome-beckertime/woocommerce/checkout/payment.php
awesome-beckertime/woocommerce/checkout/review-order.php
awesome-beckertime/woocommerce/checkout/terms.php version 2.5.0 is out of date. The core version is 3.1.1
awesome-beckertime/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.2.0
awesome-beckertime/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/content-single-product.php
awesome-beckertime/woocommerce/global/breadcrumb.php
awesome-beckertime/woocommerce/global/quantity-input.php
awesome-beckertime/woocommerce/global/sidebar.php
awesome-beckertime/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/loop/orderby.php version - is out of date. The core version is 2.2.0
awesome-beckertime/woocommerce/loop/pagination.php
awesome-beckertime/woocommerce/loop/price.php
awesome-beckertime/woocommerce/loop/result-count.php version 2.0.0 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/myaccount/downloads.php
awesome-beckertime/woocommerce/myaccount/form-edit-account.php version 2.5.1 is out of date. The core version is 2.6.0
awesome-beckertime/woocommerce/myaccount/form-edit-address.php
awesome-beckertime/woocommerce/myaccount/form-login.php version 2.2.6 is out of date. The core version is 3.2.0
awesome-beckertime/woocommerce/myaccount/form-lost-password.php
awesome-beckertime/woocommerce/myaccount/form-reset-password.php
awesome-beckertime/woocommerce/myaccount/lost-password-confirmation.php
awesome-beckertime/woocommerce/myaccount/my-account.php
awesome-beckertime/woocommerce/myaccount/my-address.php version 2.2.0 is out of date. The core version is 2.6.0
awesome-beckertime/woocommerce/myaccount/my-orders.php
awesome-beckertime/woocommerce/myaccount/view-order.php version 2.2.0 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/notices/error.php
awesome-beckertime/woocommerce/notices/notice.php
awesome-beckertime/woocommerce/notices/success.php
awesome-beckertime/woocommerce/order/order-again.php
awesome-beckertime/woocommerce/order/order-details-customer.php
awesome-beckertime/woocommerce/order/order-details-item.php
awesome-beckertime/woocommerce/order/order-details.php
awesome-beckertime/woocommerce/order/order-downloads.php
awesome-beckertime/woocommerce/single-product/add-to-cart/external.php
awesome-beckertime/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.7
awesome-beckertime/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/single-product/add-to-cart/variation.php
awesome-beckertime/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.1.0
awesome-beckertime/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.1.0
awesome-beckertime/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.1.0
awesome-beckertime/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.1.0
awesome-beckertime/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/single-product/review-meta.php version 2.6.0 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/single-product/review-rating.php version 2.6.0 is out of date. The core version is 3.1.0
awesome-beckertime/woocommerce/single-product/review.php
awesome-beckertime/woocommerce/single-product/sale-flash.php
awesome-beckertime/woocommerce/single-product/share.php
awesome-beckertime/woocommerce/single-product/short-description.php
awesome-beckertime/woocommerce/single-product/title.php
awesome-beckertime/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
awesome-beckertime/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 3.2.0
awesome-beckertime/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`

**Comment by mikejolley** [comment]
Your page seems find. It does not refresh at all. Try logging out? 

You should rule out plugin and theme conflicts on staging also - if you do see the issue (I don't) it's likely a conflict.

Thanks
