### ISSUE TITLE
missing "Manage stock?" in the Woocommerce 3.1 product importer 

### ISSUE THREAD

**Issue by ChristianJules** [woocommerce/woocommerce#17392]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. go to Products > All Products > Import
2. choose a csv file + update
3. on the "Map CSV fields to products", in the drop down list that allows to choose the updated fields the "Manage stock?" is not available (though "Stock" and "In stock" are available) 

## Expected/actual behavior
The "Manage stock?" should be in the import fields.
Same issue for the product exporter, the "Manage stock?" is not exported in the csv file.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

`
### WordPress Environment ###

Home URL: https://mapscompany.com
Site URL: https://mapscompany.com
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.24-1~dotdeb+8.1
PHP Post Max Size: 20 MB
PHP Time Limit: -1
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
Total Database Size: 486.15MB
Database Data Size: 384.20MB
Database Index Size: 101.95MB
wp_woocommerce_sessions: Data: 141.45MB + Index: 2.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.28MB
wp_woocommerce_order_itemmeta: Data: 5.52MB + Index: 6.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_cart_notices: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 1.52MB + Index: 0.45MB
wp_comments: Data: 17.28MB + Index: 9.08MB
wp_custommaps: Data: 0.02MB + Index: 0.00MB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB
wp_icl_currencies: Data: 0.02MB + Index: 0.00MB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.14MB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB
wp_icl_node: Data: 0.02MB + Index: 0.00MB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB
wp_icl_strings: Data: 0.02MB + Index: 0.03MB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB
wp_icl_string_translations: Data: 0.02MB + Index: 0.02MB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB
wp_icl_translations: Data: 1.52MB + Index: 0.86MB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 12.22MB + Index: 2.78MB
wp_pmxe_exports: Data: 0.30MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 1.52MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.06MB + Index: 0.00MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 1.45MB + Index: 0.00MB
wp_pmxi_posts: Data: 2.06MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.14MB + Index: 0.00MB
wp_postmeta: Data: 140.70MB + Index: 60.91MB
wp_posts: Data: 24.52MB + Index: 8.05MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.27MB + Index: 0.23MB
wp_terms: Data: 0.38MB + Index: 0.56MB
wp_term_relationships: Data: 2.44MB + Index: 1.42MB
wp_term_taxonomy: Data: 0.45MB + Index: 0.47MB
wp_usermeta: Data: 2.52MB + Index: 4.03MB
wp_users: Data: 0.13MB + Index: 0.14MB
wp_wc_gpf_render_cache: Data: 15.05MB + Index: 1.52MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.05MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 1.52MB + Index: 0.00MB
wp_wfHits: Data: 3.52MB + Index: 2.05MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.27MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.05MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.05MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.17MB + Index: 0.13MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 2.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB
wp_wpmelon_advbedit_temp: Data: 0.05MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.31MB + Index: 0.00MB

### Post Type Counts ###

algolia_log: 49
amn_wpforms-lite: 1
attachment: 17764
carts: 81
essential_grid: 22
export_template: 2
grid_template: 7
kt_gallery: 1
nav_menu_item: 554
page: 17
portfolio: 1
post: 4
postman_sent_mail: 250
product: 4798
revision: 219
scheduled_export: 3
shop_coupon: 37
shop_order: 4856
shop_order_refund: 168
shop_webhook: 4
spucpt: 1
wc_zapier_feed: 1
wpforms: 2
wpseo_crawl_issue: 692

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (43) ###

Algolia Search for WooCommerce: by Algolia – 0.5.1 – Not tested with the active version of WooCommerce
WP Offload S3: by Delicious Brains – 1.5
Amazon Web Services: by Delicious Brains – 1.0.3
Antispam Bee: by pluginkollektiv – 2.7.1
Easy WP SMTP: by wpecommerce – 1.3.0
Google Customer Reviews for WooCommerce: by eCreations – 1.2 – Not tested with the active version of WooCommerce
Enable WooCommerce GPF feed item cache.: by Lee Willis – 1.0 – Not tested with the active version of WooCommerce
MonsterInsights - eCommerce Addon: by MonsterInsights Team – 7.0.5
MonsterInsights Pro: by MonsterInsights – 6.2.4
Imagify: by WP Media – 1.6.12
MonsterInsights - Performance Addon: by MonsterInsights Team – 1.2.1
Recently Registered: by Mika Epstein – 3.4.3
Say What?: by Lee Willis – 1.9.1
Search by Algolia – Instant & Relevant results: by Algolia – 2.8.1
Page Builder by SiteOrigin: by SiteOrigin – 2.5.13
SiteOrigin Widgets Bundle: by SiteOrigin – 1.10.2
WooCommerce Order Search Admin powered by Algolia: by Raymond Rutjes – 1.1.1 – Not tested with the active version of WooCommerce
Woocommerce Fulfillment Location: by leoncustodio – 0.2 – Not tested with the active version of WooCommerce
Woocommerce Advanced Bulk Edit: by George Iron – 4.2 – Not tested with the active version of WooCommerce
WooCommerce Brands: by WooCommerce – 1.5.2 – Not tested with the active version of WooCommerce
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.10
WooCommerce Cart Notices: by SkyVerge – 1.7.1 – Not tested with the active version of WooCommerce
WooCommerce Cart Reports: by WooCommerce – 1.1.20 – Not tested with the active version of WooCommerce
WooCommerce Cost of Goods: by SkyVerge – 2.5.0 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce AdWords Conversion Tracking: by Wolf+Bär Agency – 1.4.7
WooCommerce PDF Invoices: by Andrew Benbow – 3.7.6 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.16 – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Lee Willis – 7.3.0
WooCommerce Reorder Manager: by Objects – 1.2 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.3 – Not tested with the active version of WooCommerce
WooCommerce Stock Manager: by Vladislav Musílek – 1.2.0 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.4 – Not tested with the active version of WooCommerce
WP All Import - WooCommerce Add-On: by Soflyy – 1.3.7
WooCommerce: by Automattic – 3.2.1
Yoast SEO Premium: by Team Yoast – 5.7.1
WP All Export Pro: by Soflyy – 1.4.7
WP All Import Pro: by Soflyy – 4.5.0
WP Gallery Custom Links: by johnogg – 1.12
WP Rocket: by WP Media – 2.10.10
WPForms Lite: by WPForms – 1.4.1.1
Yoast SEO: WooCommerce: by Team Yoast – 5.7 – Not tested with the active version of WooCommerce
WPtouch Pro: by WPtouch – 4.3.18

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #26745 - /terms-conditions/

### Theme ###

Name: virtue_premium Child
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Virtue - Premium
Parent Theme Version: 4.3.4
Parent Theme Author URL: https://www.kadencethemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: virtue_premium/woocommerce/archive-product.php
virtue_premium/woocommerce/content-product.php
virtue_premium/woocommerce/content-product_cat.php
virtue_premium/woocommerce/content-single-product.php
virtue_premium-child/woocommerce/emails/email-styles.php
virtue_premium/woocommerce/loop/loop-end.php
virtue_premium/woocommerce/loop/loop-start.php
virtue_premium/woocommerce/loop/rating.php
virtue_premium/woocommerce/loop/sale-flash.php
virtue_premium/product-searchform.php
virtue_premium/woocommerce/single-product/add-to-cart/external.php
virtue_premium/woocommerce/single-product/add-to-cart/grouped.php
virtue_premium/woocommerce/single-product/add-to-cart/simple.php
virtue_premium/woocommerce/single-product/add-to-cart/variable.php
virtue_premium/woocommerce/single-product/product-image.php
virtue_premium/woocommerce/single-product/product-thumbnails.php
virtue_premium/woocommerce/single-product/related.php
virtue_premium/woocommerce/single-product/sale-flash.php
virtue_premium/woocommerce/single-product/title.php
virtue_premium/woocommerce/single-product/up-sells.php
virtue_premium/woocommerce/single-product.php
virtue_premium/woocommerce/taxonomy-product_cat.php
virtue_premium/woocommerce/taxonomy-product_tag.php

### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Condition: Defaults to "new".
Brand: Defaults to "MapsCompany". Pre-populates from "product_brand taxonomy".
Manufacturer Part Number (MPN): Pre-populates from "sku taxonomy".
Product Type: Defaults to "Printed map".
Google Product Category: Defaults to "Media > Books > Non-Fiction > Travel Books".
Global Trade Item Number (GTIN): Pre-populates from "sku taxonomy".
Bing Category: Defaults to "Travel|Maps".

### WooCommerce Google Product Feed options ###

Include variations in feed: No
Send item_group_id: No
`

</details>

**Comment by mikejolley** [comment]
The stock field is used for both. See the docs here https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema
