### ISSUE TITLE
woocommerce-bookings: Resource bookings overlapping when automatically assigned with customer defined blocks

### ISSUE THREAD

**Issue by ad-on-is** [woocommerce/woocommerce#17391]
Before I describe the problem, let me first explain the use-case. 
We have 2 bowling alleys (Stand 1, Stand 2) that can be booked in 30-minute-blocks. I.E. the user can book an alley from 8:00 and set the duration to i.e. 3 x 30 minutes. 

**The bookable product is configured as follows:**

General
![image](https://user-images.githubusercontent.com/9553253/32027599-39592e8e-b9ea-11e7-8874-90367acce6a0.png)

Availability
![image](https://user-images.githubusercontent.com/9553253/32027633-601a5016-b9ea-11e7-8132-2e1987e73926.png)

Resources
![image](https://user-images.githubusercontent.com/9553253/32027681-a4dec4b6-b9ea-11e7-87cc-80e510bf58fa.png)

**Each of the 5 resources is configured as follows:**

![image](https://user-images.githubusercontent.com/9553253/32027655-7db06b56-b9ea-11e7-955d-86cb27b49c17.png)

**Now let's assume the following bookings are done:**
1. Booking from 08:00 - 09:30  (click on 08:00 and set duration to 3)
2. Booking from 09:00 - 09:30 (click on 09:00 and leave duration at 1)
3. Booking from 08:00 - 09:30 (click on 08:00 and set duration to 3)

**Actual behaviour:**
1. Booking assigned to Stand 1 (OK)
2. Booking assigned to Stand 2 (OK)
3. Booking assigned to Stand 2 (WRONG)

**Expected behaviour:**
1. Booking assigned to Stand1
2. Booking assigned to Stand2 (because Stand 1 is already booked at 09:00)
3. Booking (or increasing the duration) should NOT be possible since Stand 2 is already booked from 09:00 - 09:30 and can't be booked from 08:00 - 09:30 at the same time

Cheers,
Adis

**Comment by mikejolley** [comment]
Hi,

This is not the place for bookings questions.

> Usage questions can also be directed to the public support forum here: https://wordpress.org/support/plugin/woocommerce, unless this is a question about a premium extension in which case you should use the helpdesk.

https://woocommerce.com/my-account/tickets/

Thanks
