### ISSUE TITLE
Woocommerce completed order email changes not working

### ISSUE THREAD

**Issue by Ruandl** [woocommerce/woocommerce#17398]
I am trying to change my Woocommerce email that my client receives. I have tried changing a few things in the themes files etc. but no luck. Could someone please be kind enough to help me? This is for a NGO that helps abused and neglected young kids and they are letting people donate gifts.

They have been receiving email that are complaining about the fact that their completed order email says product and it looks like they are selling kids and it looks bad and so on. I would like to change "Product" to "Wish", see attached image.

https://imgur.com/a/pUrlw - Image of the email donators receive, the red line will show what I want to change.

Please help me, I have tried everything to help them but I can' seem to crack it.

**Comment by claudiulodro** [comment]
You are going to want to override the [email order details template](https://github.com/woocommerce/woocommerce/blob/master/templates/emails/email-order-details.php#L37) in your theme.

You can read about how to override the template in your theme [here](https://docs.woocommerce.com/document/template-structure/) right above the purple example block. Copy + paste the whole template over then modify it how you want.
