### ISSUE TITLE
Add downloadable email headers for completed email back to core

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce#17401]
Raised in 752902-zd

WooCommerce 3.0.9 had the option to set sperate email headers and subject lines for downloadable products from WooCommerce core and this feature was taken out starting with WooCommerce 3.1

![](http://cld.wthms.co/CI3nap+)Image Link: http://cld.wthms.co/CI3nap

I was unable to find any notes in the release blogs or changelog as to why this was removed. Is it possible to re-introduce this feature?

**Comment by mikejolley** [comment]
I'll update the readme. The defaults were made more generic, and all emails contain download links, so these options were no longer necessary.
