### ISSUE TITLE
Decimal separator [Flat Rate Box Shipping plugin]

### ISSUE THREAD

**Issue by nagybal** [woocommerce/woocommerce#17405]
The plugin **Flat Rate Box Shipping** does not accept the comma character as a Decimal separator.
> ,

If I use dot instead, it does work.

It is really inconvenient when updating prices.
![kepernyofoto 2017-10-27 - 11 03 30](https://user-images.githubusercontent.com/27618042/32096442-c2f921d6-bb06-11e7-8619-cc3c8512e5f9.png)
![kepernyofoto 2017-10-27 - 11 04 03](https://user-images.githubusercontent.com/27618042/32096444-c31ddc10-bb06-11e7-9169-5fd4ba12dd87.png)

**Comment by mikejolley** [comment]
> Usage questions can also be directed to the public support forum here: https://wordpress.org/support/plugin/woocommerce, unless this is a question about a premium extension in which case you should **use the helpdesk**.

Please use the helpdesk as instructed - this is not a core issue.

Thanks

**Comment by nagybal** [comment]
This is not a question. This is a fact, a statement. I did provide screenshot as well. Please reopen the ticket and forward to the dev team.

**Comment by mikejolley** [comment]
Whatever it is, this is not the place to report issues with extensions so I will not be reopening this. Use the helpdesk so the relevant people can be notified directly.
