### ISSUE TITLE
Remove 'woocommerce_lock_down_admin' option [suggest]

### ISSUE THREAD

**Issue by JeroenSormani** [woocommerce/woocommerce#17410]
In name of mini (micro?) optimizations, it can be considered to remove the `woocommerce_lock_down_admin` option code uses. The option doesn't seem to exist in the database, at least not for quite some time and only used in the code twice. 

Because it doesn't exist in the options table WP will do a direct SQL query to attempt to get this option from the database. 

Code uses:
1) https://github.com/woocommerce/woocommerce/blame/3f1144cf06fba8fb78cb48e4f69c88c1c612ada0/includes/wc-user-functions.php#L20
4 years ago - The text was added that the option is deprecated.

2) https://github.com/woocommerce/woocommerce/blob/974f402017e827d4eadac557197e303c463a4f10/includes/admin/class-wc-admin.php#L162-L162
This one didn't have such notice. There is a chance people used this, but they should've used the filter a few lines lower instead.

Doing some Googling it doesn't seem that the 'woocommerce_lock_down_admin' option has been mentioned a lot on the web.

Happy to provide a PR if the suggestion is accepted.

**Comment by claudiosanches** [comment]
Yeah, already time to remove this old option, for sure there is more deprecated options that we could remove. Let's have it for 4.0.

But I can see already issues here with people saying that the admin bar vanished xD

**Comment by mikejolley** [comment]
@JeroenSormani You can still send a PR, but it won't be merged until 4.0 cycle.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17796
