### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by Ammopeak** [woocommerce/woocommerce#17415]
Hello,

I was hired on with a company. The previous guy who set up Woocommerce  longer works there and  left the company with no information or login details for ANYTHING. I was not given login or password   to anything.  We have the wordpress.org website,but we don't have the wordpress.com login information. 

I need to be able to access my Woocomerce account. Ask questions, maybe even upgrade! 

I found that there are two options. 
1. Change Hosts ( did not provide access to the host information)
2. Work with not having access to that account
3. Try and link a new wordpress.com account with that account

What are the best options. What can I do.

**Comment by mikejolley** [comment]
We cannot really help you here, this is a public issue tracker.

I'd get in contact with the accounts team so they can review your case. Go here: https://woocommerce.com/contact-us/

Thanks

**Comment by Ammopeak** [comment]
Hey,

I did send them a ticket. I 4x have no heard a reply ( for paying customers ) . I am a paying customer with no access to the account. I had to create a separate wordpress.com account to submit the ticket that is not attached to the site in question. Which means they will not help cause the account is not attached to the wordpress.com account. I am stuck.

**Comment by mikejolley** [comment]
Ticket ID? How long ago?

> I am a paying customer

I guess if the person who left was the account holder, there isn't much you can do.. It's theirs.

**Comment by Ammopeak** [comment]
but if we paid for the domain and switched it to use its ours. Which means we should have access to a product that we are being charged for...but since we have no access to the account.. how can we know.
