### ISSUE TITLE
Variation Displayed in Cross-Sell and Upsells with Parent's Post Status set to 'draft' and 'pending review'

### ISSUE THREAD

**Issue by TimBHowe** [woocommerce/woocommerce#17413]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. Set a variable product's post status to 'draft' or 'pending review'.
2. Add one of the variable product's variation as a cross-sell or upsell on another product.
3. View the product with the cross-sell or upsell and you will see the variation with the non-SEO friendly URL and it will return a 404.

## Expected/actual behavior
You are able to add variations to the cross-sells and upsell of other products even if the variable product's post status is set to 'draft' or 'pending review'. This also causes the product to use the non-SEO friendly URL.

We would expect the product to be filtered out of the cross-sell and upsells based on the parent variable product post status.

It appears the issue is with the [`wc_products_array_filter_editable`](https://github.com/woocommerce/woocommerce/blob/fe819a8be24fba86148557a693953b4192cb3e0a/includes/wc-product-functions.php#L1016) filter. The filter isn't checking the parent posts status.

We are also not sure if the filter should take the parent's post visibility or product catalog visibility into consideration.

We discovered this issue while working on a client's site, but we set up a test environment to make sure we understood and could replicate the issue.

We are going to look into submitting a patch for this issue. Please let us know if you need any more information.

Thanks.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

### WordPress Environment ###

Home URL: http://local.dev
Site URL: http://local.dev
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.28 (Unix) OpenSSL/1.1.0f PHP/7.1.10
PHP Version: 7.1.10
PHP Post Max Size: 500 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.56.0
OpenSSL/1.1.0f

SUHOSIN Installed: –
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 4.23MB
Database Data Size: 3.05MB
Database Index Size: 1.18MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.05MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.03MB + Index: 0.05MB
wp_postmeta: Data: 0.19MB + Index: 0.16MB
wp_posts: Data: 0.16MB + Index: 0.06MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 52
page: 22
post: 40
product: 24
product_variation: 4

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Gravity Forms: by rocketgenius – 2.2.5
WooCommerce: by Automattic – 3.2.1
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6271 - /shop/
Cart: #6272 - /cart/
Checkout: #6273 - /checkout/
My account: #6274 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by mikejolley** [comment]
> We are going to look into submitting a patch for this issue. Please let us know if you need any more information.

I would not change `wc_products_array_filter_editable`. Being able to setup variations as cross sells before publish may be desired.

It should be fixed in `wc_products_array_filter_visible`, or the product/variation `is_visible` method.

**Comment by TimBHowe** [comment]
Thanks for the info. We are going to look into adding some additional check to the `is_visible` function, review and test.

**Comment by mikejolley** [comment]
Added feedback to https://github.com/woocommerce/woocommerce/pull/17423#pullrequestreview-72822425 - let's continue there.
