### ISSUE TITLE
Dummy data

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#17418]
Continuing from https://github.com/woocommerce/woocommerce/pull/16483

Include:

- Files for downloadable products
- A group (group the downloadable products?)
- External product

**Comment by claudiosanches** [comment]
Need samples of variations with product based attributes too.

- Variable products with global attributes only
- Variable products with product based attributes only
- Variable products with product based attributes and global attributes

**Comment by jobthomas** [comment]
* For the files for downloadable products - I'd just use the images for those products

* For the group: do we know when users use those?

* @claudiosanches we can add "Designer" as product level attributes to those clothes that have a graphic on that. Sounds good?
 * Designer = Woo (for example)
 * Designer = Automattic

**Comment by claudiosanches** [comment]
> For the files for downloadable products - I'd just use the images for those products

We should try `.ogg` or some other media file as before, so we can use to test the `force download` option.

> For the group: do we know when users use those?

https://docs.woocommerce.com/document/managing-products/#section-11

In my previous CSV file I made an example with grouping all singles into one product, so you could buy all at the same time.

> @claudiosanches we can add "Designer" as product level attributes to those clothes that have a graphic on that. Sounds good?

No, if this is going to go with variations, probably then include "Size", so we can fake that you can pick a t-shirt by color and size. Again, there is an example of it in the previous CSV file.

Please do not forget about my commet in the previous issue: https://github.com/woocommerce/woocommerce/issues/15723#issuecomment-310178768

**Comment by jobthomas** [comment]
> No, if this is going to go with variations, probably then include "Size", 

"Size" just seems like a very odd attribute to have on a product and not on a global level.

**Comment by mikejolley** [comment]
For a non-global attribute we can use 'logo'/'no logo'. As I said, @kellychoffman  is prepping graphics. Leave until those are ready :p

**Comment by jobthomas** [comment]
Related to the products with multiple images @claudiosanches - there are two products who already have that:

![http://cld.wthms.co/5ifkOZ](http://cld.wthms.co/5ifkOZ+)
Link to image here: http://cld.wthms.co/5ifkOZ.
