### ISSUE TITLE
Wizard: Preselect weight and units based on country selected

### ISSUE THREAD

**Issue by kellychoffman** [woocommerce/woocommerce#17429]
Feedback about the first page of the wizard from the user research lab at WooConf:

These are defaulted to European units and if a person chose US as a location for example, they had to change the units on the shipping step. Weight and units should be preselected based on the country selected.

**Comment by dechov** [comment]
Fixed by https://github.com/woocommerce/woocommerce/issues/17429 — after having been originally implemented in https://github.com/woocommerce/woocommerce/pull/15310 and somehow lost.
