### ISSUE TITLE
Shipping price included in cart total

### ISSUE THREAD

**Issue by iceHub82** [woocommerce/woocommerce#17436]
Hi there,

I have encounterd a problem after a woocommerce update. On my cartpage I have disabled shipping in the woocommerce settings, but the shipping prize is still calculated in the total. This leads to confusion for the customer as he is presented with two total amounts. Please check out the image below

![cartbug](https://user-images.githubusercontent.com/29539072/32132450-f9423d00-bbc3-11e7-9a0a-d50a46c3faa7.PNG)

Is this a known bug and is there a workaround?

Best regards
Örvar

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17414

**Comment by iceHub82** [comment]
Thanks for the help!
