### ISSUE TITLE
Wizard: Going back and next steps

### ISSUE THREAD

**Issue by kellychoffman** [woocommerce/woocommerce#17430]
Feedback about the first page of the wizard from the user research lab at WooConf:

- [ ] Once you finish the setup wizard, adding products is the only “next step” really offered. People also like to review settings, go to the main dashboard, and work on their theme/appearance. We should make these more obvious.
- [ ] There is no back-button, and the steps at the top of the wizard are not clickable, so there is no easy way to get to a previous step. We should bring back the back button!

**Comment by mikejolley** [comment]
cc @jeffstieler @olaolusoga

**Comment by kellychoffman** [comment]
> There is no back-button, and the steps at the top of the wizard are not clickable, so there is no easy way to get to a previous step. We should bring back the back button!

We should do this two fold: Make the completed steps at the top of the wizard and add a `< Back` link in the same place as the `Not right now` link is on the first step.

**Comment by kellychoffman** [comment]
>  Once you finish the setup wizard, adding products is the only “next step” really offered. People also like to review settings, go to the main dashboard, and work on their theme/appearance. We should make these more obvious.

For this, we should add a third section below importing with three buttons: 

<img width="683" alt="screen shot 2017-12-14 at 11 00 32 am" src="https://user-images.githubusercontent.com/5835847/34007184-1efd19ba-e0be-11e7-9287-27314dcfbe12.png">

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18389
