### ISSUE TITLE
Coupon Bug: Max limit Reached when unlimited uses

### ISSUE THREAD

**Issue by shreyans94** [woocommerce/woocommerce#17437]
After a coupon is used 189 times, It cannot be used anymore and gives an error of maximum usage limit reached. 

My settings are: 
Usage limit per coupon: empty (unlimited)
Usage limit per user: 1
Discount Type: Percentage
Discount Amount: 5%

PS: It was a completely new account that I was trying to use it on so I was not being stopped by the condition Usage limit per user: 1

**Comment by mikejolley** [comment]
This is patched in master and will be part of 3.2.2 release this week.
