### ISSUE TITLE
Shipping tax calculation based on product instead of order item

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#17449]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set shipping tax to be calculated based on cart items
2. Add product with reduced rate to order, save order
3. Delete product just added to the order
4. Add shipping item
5. Recalculate taxes

## Expected/actual behavior

When I follow those steps, I see shipping gets 'standard' tax rate rather than reduced tax rate (as based on order items). Looking at the code I see that the `$order->get_items_tax_classes()` method actually looks at the product tax & tax classes rather than the item tax class.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17455
