### ISSUE TITLE
UPDATE CART cannot translate.

### ISSUE THREAD

**Issue by kianseng** [woocommerce/woocommerce#17441]
only “updated cart” can’t translate to other language. 

screenshot : https://imgur.com/a/2Tl1o

**Comment by mikejolley** [comment]
Missing translations are in your translation files. All strings are translatable. See https://wordpress.org/support/topic/updating-translations-after-updates/

**Comment by kianseng** [comment]
i have check it using poedit, it already translated in .po file but i just don't know why it wont translate.

**Comment by mikejolley** [comment]
Case sensitive.
