### ISSUE TITLE
Include parameter skips first id given in array

### ISSUE THREAD

**Issue by REA70R** [woocommerce/woocommerce#17447]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [X] I have included a failing test as a pull request (Optional)

I'm using WooCommerce rest api in android its working fine but I have seen a weird  behavior of `include` parameter. it skips first id always.
Here is my url

       http://codiixx.com/wp-json/wc/v2/products?include=[19,60,307,34,31]

it skips product with id 19. Rest other products are showing. 

it tried with this parameter

     http://codiixx.com/wp-json/wc/v2/products?include[]=19&include[]=60

I got authentication error,

 Im using oAuth1 works perfectly.
Id is not incorrect. help me how to use include api properly.

**Comment by claudiosanches** [comment]
You should just pass as:

```
http://codiixx.com/wp-json/wc/v2/products?include=19,60,307,34,31
```

Works in the same way that the WordPress REST API.

**Comment by IntelliJAbhishek** [comment]
I forgot to reply. Thanks for you response @claudiosanches . Its working fine
