### ISSUE TITLE
Product Data is not displaying all the related content-- how to fix this issue?

### ISSUE THREAD

**Issue by YKPappu** [woocommerce/woocommerce#17446]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. We are using WooCommerce plugin in our website.
2. In starting Product-data was working fine.
3. But after some days, we are unable to access the product data feature.
4. If we click product data, then all related features like (General , Inventory, Shipping, Linked Products, Attributes, Advanced) is showing blank or it is not showing its related content. 

## Expected/actual behavior

When I follow those steps of woocommerce, I were able to see all content of product data in beginning.
But after-some days, we are unable to find Product-Data content.  
I was expecting to see all related content of product-data.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
This is a javascript error/plugin conflict.

To find the conflict, open up (in chrome) View > Developer > Javascript console. An error message will be shown. It should contain clues to find the plugin responsible e.g. it may be a script from a certain plugin. 

Possibly related https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x

Thanks
