### ISSUE TITLE
Exporting reports as CSV - Unicode no BOM

### ISSUE THREAD

**Issue by jyourstone** [woocommerce/woocommerce#17454]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Export a report as CSV that contains special characters (such as åäö)
2. Open the CSV-file in Microsoft Excel
3. The special characters are not displayed properly

## Expected/actual behavior

When I open a CSV-file I expect to see all special characters properly formated. It seems the CSV-files are marked as no BOM, if I change them to BOM in a text editor, Microsoft Excel displays everything correct.

I know I can import the CVS in Excel and select the correct encoding format, but it takes time to do that for each report, ideally Excel should display the reports correctly when opening.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://snabblunch.se/laxbutikenheberg
Site URL: http://snabblunch.se/laxbutikenheberg
WC Version: 3.2.1
Log Directory Writable: ✔
WP Version: 4.8.2
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.10
PHP Post Max Size: 50 MB
PHP Time Limit: 90
PHP Max Input Vars: 3000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.1
WC Database Prefix: wphw_2_
Total databasstorlek: 12.74MB
Datastorlek för databas: 10.84MB
Indexstorlek för databas: 1.90MB
wphw_2_woocommerce_sessions: Data: 0.02 MB + Index: 0.02 MB
wphw_2_woocommerce_api_keys: Data: 0.02 MB + Index: 0.03 MB
wphw_2_woocommerce_attribute_taxonomies: Data: 0.02 MB + Index: 0.02 MB
wphw_2_woocommerce_downloadable_product_permissions: Data: 0.02 MB + Index: 0.05 MB
wphw_2_woocommerce_order_items: Data: 0.02 MB + Index: 0.02 MB
wphw_2_woocommerce_order_itemmeta: Data: 0.02 MB + Index: 0.03 MB
wphw_2_woocommerce_tax_rates: Data: 0.02 MB + Index: 0.06 MB
wphw_2_woocommerce_tax_rate_locations: Data: 0.02 MB + Index: 0.03 MB
wphw_2_woocommerce_shipping_zones: Data: 0.02 MB + Index: 0.00 MB
wphw_2_woocommerce_shipping_zone_locations: Data: 0.02 MB + Index: 0.03 MB
wphw_2_woocommerce_shipping_zone_methods: Data: 0.02 MB + Index: 0.00 MB
wphw_2_woocommerce_payment_tokens: Data: 0.02 MB + Index: 0.02 MB
wphw_2_woocommerce_payment_tokenmeta: Data: 0.02 MB + Index: 0.03 MB
wphw_2_woocommerce_log: Data: 0.02 MB + Index: 0.02 MB
wphw_2_commentmeta: Data: 0.02 MB + Index: 0.03 MB
wphw_2_comments: Data: 0.02 MB + Index: 0.09 MB
wphw_2_links: Data: 0.02 MB + Index: 0.02 MB
wphw_2_options: Data: 1.14 MB + Index: 0.05 MB
wphw_2_postmeta: Data: 4.50 MB + Index: 0.17 MB
wphw_2_posts: Data: 1.52 MB + Index: 0.06 MB
wphw_2_say_what_strings: Data: 0.02 MB + Index: 0.00 MB
wphw_2_termmeta: Data: 0.02 MB + Index: 0.03 MB
wphw_2_terms: Data: 0.02 MB + Index: 0.03 MB
wphw_2_term_relationships: Data: 0.02 MB + Index: 0.02 MB
wphw_2_term_taxonomy: Data: 0.02 MB + Index: 0.03 MB
wphw_blogs: Data: 0.02 MB + Index: 0.03 MB
wphw_blog_versions: Data: 0.02 MB + Index: 0.02 MB
wphw_commentmeta: Data: 0.02 MB + Index: 0.03 MB
wphw_comments: Data: 0.02 MB + Index: 0.09 MB
wphw_links: Data: 0.02 MB + Index: 0.02 MB
wphw_options: Data: 1.44 MB + Index: 0.05 MB
wphw_postmeta: Data: 0.05 MB + Index: 0.03 MB
wphw_posts: Data: 0.16 MB + Index: 0.06 MB
wphw_registration_log: Data: 0.02 MB + Index: 0.02 MB
wphw_signups: Data: 0.02 MB + Index: 0.06 MB
wphw_site: Data: 0.02 MB + Index: 0.02 MB
wphw_sitemeta: Data: 0.13 MB + Index: 0.03 MB
wphw_termmeta: Data: 0.02 MB + Index: 0.03 MB
wphw_terms: Data: 0.02 MB + Index: 0.03 MB
wphw_term_relationships: Data: 0.02 MB + Index: 0.02 MB
wphw_term_taxonomy: Data: 0.02 MB + Index: 0.03 MB
wphw_usermeta: Data: 0.02 MB + Index: 0.03 MB
wphw_users: Data: 0.02 MB + Index: 0.05 MB
wphw_woocommerce_api_keys: Data: 0.02 MB + Index: 0.03 MB
wphw_woocommerce_attribute_taxonomies: Data: 0.02 MB + Index: 0.02 MB
wphw_woocommerce_downloadable_product_permissions: Data: 0.02 MB + Index: 0.05 MB
wphw_woocommerce_log: Data: 0.02 MB + Index: 0.02 MB
wphw_woocommerce_order_itemmeta: Data: 0.02 MB + Index: 0.03 MB
wphw_woocommerce_order_items: Data: 0.02 MB + Index: 0.02 MB
wphw_woocommerce_payment_tokenmeta: Data: 0.02 MB + Index: 0.03 MB
wphw_woocommerce_payment_tokens: Data: 0.02 MB + Index: 0.02 MB
wphw_woocommerce_sessions: Data: 0.02 MB + Index: 0.02 MB
wphw_woocommerce_shipping_zones: Data: 0.02 MB + Index: 0.00 MB
wphw_woocommerce_shipping_zone_locations: Data: 0.02 MB + Index: 0.03 MB
wphw_woocommerce_shipping_zone_methods: Data: 0.02 MB + Index: 0.00 MB
wphw_woocommerce_tax_rates: Data: 0.02 MB + Index: 0.06 MB
wphw_woocommerce_tax_rate_locations: Data: 0.02 MB + Index: 0.03 MB
wp_923_snabblunch_se_aiowps_events: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_aiowps_failed_logins: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_aiowps_global_meta: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_aiowps_login_activity: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_aiowps_login_lockdown: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_aiowps_permanent_block: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_commentmeta: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_comments: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_links: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_options: Data: 0.52 MB + Index: 0.00 MB
wp_923_snabblunch_se_postmeta: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_posts: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_termmeta: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_terms: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_term_relationships: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_term_taxonomy: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_usermeta: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_users: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_woocommerce_api_keys: Data: 0.02 MB + Index: 0.00 MB
wp_923_snabblunch_se_woocommerce_attribute_taxonomies: Data: 0.02 MB + Index: 0.00 MB

### Post Type Counts ###

attachment: 11
custom_css: 2
customize_changeset: 41
nav_menu_item: 5
page: 12
post: 6
postman_sent_mail: 133
product: 23
product_variation: 2
revision: 88
shop_order: 6

### Security ###

Secure connection (HTTPS): ❌Din butik använder inte HTTPS. Lär dig mer om HTTPS och SSL-certifikat.
Hide errors from visitors: ✔

### Active Plugins (15) ###

Cookie meddelande: av dFactory – 1.2.39
Enhanced E-commerce for Woocommerce store: av Tatvic – 1.2.0 – Inte testat med den aktiva versionen för WooCommerce
MailChimp for WordPress: av ibericode – 4.1.10
Post SMTP: av Jason Hendriks
Yehuda Hassine – 1.7.7

Say What?: av Lee Willis – 1.9.1
WooCommerce Stripe Gateway: av WooCommerce – 3.2.3 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Swish Ecommerce Gateway: av Redlight Media – 2.0.1
WooCommerce Opening Hours / Delivery Times: av DavidAnderson – 1.7.19
WooCommerce Print Orders: av David Anderson – 2.7.5
WooCommerce Twilio SMS Notifications: av SkyVerge – 1.9.0 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce: av Automattic – 3.2.1
WP-SpamShield: av Red Sand Media Group – 1.9.21
Google Analytics Dashboard för WP (GADWP): av Alin Marcu – 5.1.2.2
Storefront Powerpack: av WooCommerce – 1.4.3
WooCommerce Product Table: av Barn2 Media – 1.8.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Butikbas: #361 - /butik/
Varukorg: #5 - /varukorg/
Kassan: #6 - /kassan/
Mitt konto: #7 - /mitt-konto/
Allmänna villkor: #128 - /kopvillkor/

### Theme ###

Name: Storefront Blank Child Theme
Version: 1.0
Author URL: http://www.pootlepress.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/emails/customer-processing-order.php
`
</details>

**Comment by mikejolley** [comment]
I've checked this and both batch and standard imports include BOM. Confirmed in hex editor.

https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=chr%28+239+%29+.+chr%28+187+%29+.+chr%28+191&type=

**Comment by jyourstone** [comment]
Hmm so how come when I open a report in EditPad it says "no BOM"? If I open it in Excel it doesn't display special characters such as åäö.
And when I set it to BOM in EditPad Excel can read it just fine?

**Comment by mikejolley** [comment]
If you open in a hex editor, the first chars you should see are `EF BB BF`. This is the BOM. I used http://ridiculousfish.com/hexfiend/

**Comment by jyourstone** [comment]
If I export a report as CSV and open it in a hex editor (I used HxD), it doesn't display the chars EF BB BF. 
If I open the file in EditPad and change it to BOM, then I can see the chars EF BB BF in HxD.

**Comment by mikejolley** [comment]
You're on an old version https://github.com/woocommerce/woocommerce/commit/5c2a69c668a594e6dc703f601d0077c975045e68#diff-45fcd18836f3747c999c8048b7453bc2

**Comment by mikejolley** [comment]
See if you have that code present. I'm not seeing an issue in my exports.

**Comment by jyourstone** [comment]
I'm using WooCommerce 3.2.5

This is in my abstract-wc-csv-exporter.php:

	/**
	 * Do the export.
	 *
	 * @since 3.1.0
	 */
	public function export() {
		$this->prepare_data_to_export();
		$this->send_headers();
		$this->send_content( chr( 239 ) . chr( 187 ) . chr( 191 ) . $this->export_column_headers() . $this->get_csv_data() );
		die();
	}

**Comment by mikejolley** [comment]
Can you send a sample CSV?

**Comment by jyourstone** [comment]
Sure, I just exported the attached report.

[report-custom-2017-12-07.zip](https://github.com/woocommerce/woocommerce/files/1539495/report-custom-2017-12-07.zip)

**Comment by mikejolley** [comment]
Ok, I was looking at the product exports.
