### ISSUE TITLE
Orders index has a default "hidden" class

### ISSUE THREAD

**Issue by netpoe** [woocommerce/woocommerce#17459]
Using **Wordpress 4.8.2**, **WC 3.2.1**

While logged in as the site admin, the orders index is hidden:

![screen shot 2017-10-30 at 12 34 54](https://user-images.githubusercontent.com/4053518/32188920-c7635d3a-bd6e-11e7-9295-8d834260448e.png)

It seems that is is only a `display` issue because the `tr` elements exist: 

```html
<tbody id="the-list">
				<tr id="post-78" class="iedit author-self level-0 post-78 type-shop_order status-wc-on-hold post-password-required hentry">
			<th scope="row" class="check-column">			<label class="screen-reader-text" for="cb-select-78">Elige Order – octubre 26, 2017 @ 06:50 PM</label>
			<input id="cb-select-78" type="checkbox" name="post[]" value="78">
			<div class="locked-indicator">
				<span class="locked-indicator-icon" aria-hidden="true"></span>
				<span class="screen-reader-text">“Order – octubre 26, 2017 @ 06:50 PM” está bloqueado</span>
			</div>
		</th><td class="order_status column-order_status hidden" data-colname="Estado"><mark class="on-hold tips">En espera</mark></td><td class="order_title column-order_title has-row-actions column-primary hidden" data-colname="Pedido"><a href="http://ec2-54-202-0-241.us-west-2.compute.amazonaws.com/wp-admin/post.php?post=78&amp;action=edit" class="row-title"><strong>#78</strong></a> por <a href="user-edit.php?user_id=1">Poteriafina</a><small class="meta email"><a href="mailto:gus@poteriafina.com">gus@poteriafina.com</a></small><button type="button" class="toggle-row"><span class="screen-reader-text">Mostrar más detalles</span></button><div class="row-actions"><span class="edit"><a href="http://ec2-54-202-0-241.us-west-2.compute.amazonaws.com/wp-admin/post.php?post=78&amp;action=edit" aria-label="Editar “Order – octubre 26, 2017 @ 06:50 PM”">Editar</a> | </span><span class="trash"><a href="http://ec2-54-202-0-241.us-west-2.compute.amazonaws.com/wp-admin/post.php?post=78&amp;action=trash&amp;_wpnonce=42d953cf6d" class="submitdelete" aria-label="Mover “Order – octubre 26, 2017 @ 06:50 PM” a la Papelera">Papelera</a></span></div><button type="button" class="toggle-row"><span class="screen-reader-text">Muestra más detalles</span></button></td><td class="billing_address column-billing_address hidden" data-colname="Facturación">Gustavo Ibarra, PoteriaFina, Villa Vistana, Z. 13, Guatemala, Guatemala, 010013<small class="meta">Teléfono: 49508708</small></td><td class="shipping_address column-shipping_address hidden" data-colname="Envíar a">–</td><td class="customer_message column-customer_message hidden" data-colname="Mensaje del cliente"><span class="na">–</span></td><td class="order_notes column-order_notes hidden" data-colname="Notas del pedido"><span class="note-on tips">Sí</span></td><td class="order_date column-order_date hidden" data-colname="Fecha"><time datetime="2017-10-26T18:50:29+00:00" title="octubre 26, 2017 6:50 pm">octubre 26, 2017</time></td><td class="order_total column-order_total hidden" data-colname="Total"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>1,199.00</span><small class="meta">Vía PayPal</small></td><td class="order_actions column-order_actions hidden" data-colname="Acciones"><p>
					<a class="button tips processing" href="http://ec2-54-202-0-241.us-west-2.compute.amazonaws.com/wp-admin/admin-ajax.php?action=woocommerce_mark_order_status&amp;status=processing&amp;order_id=78&amp;_wpnonce=0009bcf5f2">Procesando</a><a class="button tips complete" href="http://ec2-54-202-0-241.us-west-2.compute.amazonaws.com/wp-admin/admin-ajax.php?action=woocommerce_mark_order_status&amp;status=completed&amp;order_id=78&amp;_wpnonce=0009bcf5f2">Completo</a><a class="button tips view" href="http://ec2-54-202-0-241.us-west-2.compute.amazonaws.com/wp-admin/post.php?post=78&amp;action=edit">Ver</a>				</p></td>		</tr>
		</tbody>
```

I found that some of the `td` elements have a `billing_address column-billing_address hidden`  class. Why is this? 

I logged in with another user with a `Vendor Admin` role and the orders display normally.

**Comment by rodrigoprimo** [comment]
I was not able to reproduce this issue on a clean WC 3.2.1. It looks like this could be a conflict caused by another plugin that you have enabled. If you disable all plugins and leave only WooCommerce active, do you still experience this problem? If so, please feel free to reopen this issue.

> I found that some of the td elements have a billing_address column-billing_address hidden class. Why is this?

The billing address column is hidden by default. To check it, check the page "Screen Options".

**Comment by rodrigoprimo** [comment]
Maybe what is causing this issue for you is that the WP screen options are set to hide all the columns?

**Comment by phlegx** [comment]
Hi!

I have the same problem. Column `cb` and  `name` are not listed in the "Screen Options" and in the table both has class `hidden`. So, how can activate this two columns? I have found another user, that has the same problem: https://stackoverflow.com/questions/45081423/woocommerce-product-listing-name-column-is-hidden-by-default

Any idea?

**Comment by peterfabian** [comment]
Hi @phlegx 

Columns `cb` and `name` are handled a bit differently and are excluded from the screen options, so it should not be possible to hide them from the Screen Options GUI. 

There are two filters that could interfere, if there are other plugins activated:
- `default_hidden_columns`
- `hidden_columns`

So I would first check if there are no plugins interfering. 

If not, then if you have access to the db, please try to check if you have any records for your user when you run this query:
`SELECT * FROM wp_usermeta where meta_key = 'manageedit-productcolumnshidden'`.
If you do, please try to delete these records.
