### ISSUE TITLE
Shipping Zones disappeared from backoffice and frontoffice after update to woocommerce 3.2.1

### ISSUE THREAD

**Issue by RAMI15** [woocommerce/woocommerce#17464]
Hi WooTeam,

I'm facing  a problem with the shipping zone after pasing to the 3.2.1 version of Woocommerce.
In fact, i don't find the list of the shipping zones(they still stored on the database but not displayed in back) and if i try to add new zones it doesn't work.

Version WC : |   | 3.2.1

Base de données
--
WC version base de données: |   | 3.2.1
Préfixe de base de données |   | wpcm_
Base de données GeoIP de MaxMind: |   | /var/www/collectivedeco/web/wp-content/uploads/GeoIP.dat
Total Database Size |   | 430.71MB
Database Data Size |   | 305.38MB
Database Index Size |   | 125.33MB
wpcm_woocommerce_sessions |   | Data: 5.02MB + Index: 0.02MB
wpcm_woocommerce_api_keys |   | Data: 0.02MB + Index: 0.03MB
wpcm_woocommerce_attribute_taxonomies |   | Data: 0.02MB + Index: 0.02MB
wpcm_woocommerce_downloadable_product_permissions |   | Data: 0.02MB + Index: 0.05MB
wpcm_woocommerce_order_items |   | Data: 0.02MB + Index: 0.02MB
wpcm_woocommerce_order_itemmeta |   | Data: 0.11MB + Index: 0.14MB
wpcm_woocommerce_tax_rates |   | Data: 0.02MB + Index: 0.06MB
wpcm_woocommerce_tax_rate_locations |   | Data: 0.02MB + Index: 0.05MB
wpcm_woocommerce_shipping_zones |   | Data: 0.02MB + Index: 0.00MB
wpcm_woocommerce_shipping_zone_locations |   | Data: 0.02MB + Index: 0.05MB
wpcm_woocommerce_shipping_zone_methods |   | Data: 0.02MB + Index: 0.00MB
wpcm_woocommerce_payment_tokens |   | Data: 0.02MB + Index: 0.02MB
wpcm_woocommerce_payment_tokenmeta |   | Data: 0.02MB + Index: 0.03MB
wpcm_woocommerce_log |   | Data: 0.00MB + Index: 0.00MB
wpcm_commentmeta |   | Data: 0.02MB + Index: 0.03MB
wpcm_comments |   | Data: 0.08MB + Index: 0.09MB
wpcm_datalist |   | Data: 0.00MB + Index: 0.00MB
wpcm_dropwp_bigbuy_categories_cache |   | Data: 0.03MB + Index: 0.01MB
wpcm_dropwp_bigbuy_images |   | Data: 12.28MB + Index: 9.29MB
wpcm_dropwp_bigbuy_jobs |   | Data: 0.21MB + Index: 0.02MB
wpcm_emc_addresses |   | Data: 0.00MB + Index: 0.00MB
wpcm_emc_categories |   | Data: 0.02MB + Index: 0.00MB
wpcm_emc_dimensions |   | Data: 0.02MB + Index: 0.00MB
wpcm_emc_operators |   | Data: 0.02MB + Index: 0.00MB
wpcm_emc_operators_authorized_contents |   | Data: 0.01MB + Index: 0.01MB
wpcm_emc_pricing |   | Data: 0.00MB + Index: 0.01MB
wpcm_emc_services |   | Data: 0.08MB + Index: 0.00MB
wpcm_eum_logs |   | Data: 0.00MB + Index: 0.00MB
wpcm_hook_list |   | Data: 0.00MB + Index: 0.00MB
wpcm_itsec_lockouts |   | Data: 0.00MB + Index: 0.01MB
wpcm_itsec_log |   | Data: 0.50MB + Index: 0.08MB
wpcm_itsec_temp |   | Data: 0.04MB + Index: 0.03MB
wpcm_links |   | Data: 0.02MB + Index: 0.02MB
wpcm_options |   | Data: 99.31MB + Index: 4.45MB
wpcm_postmeta |   | Data: 124.67MB + Index: 93.20MB
wpcm_posts |   | Data: 50.59MB + Index: 9.78MB
wpcm_pv_commission |   | Data: 0.00MB + Index: 0.00MB
wpcm_revslider_css |   | Data: 0.13MB + Index: 0.00MB
wpcm_revslider_layer_animations |   | Data: 0.02MB + Index: 0.00MB
wpcm_revslider_navigations |   | Data: 0.02MB + Index: 0.00MB
wpcm_revslider_sliders |   | Data: 0.02MB + Index: 0.00MB
wpcm_revslider_slides |   | Data: 0.38MB + Index: 0.00MB
wpcm_revslider_static_slides |   | Data: 0.02MB + Index: 0.00MB
wpcm_rm_fields |   | Data: 0.01MB + Index: 0.00MB
wpcm_rm_forms |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_front_users |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_notes |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_paypal_fields |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_paypal_logs |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_rules |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_sent_mails |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_sessions |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_stats |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_submissions |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_submission_fields |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_tasks |   | Data: 0.00MB + Index: 0.00MB
wpcm_rm_task_exe_log |   | Data: 0.00MB + Index: 0.00MB
wpcm_termmeta |   | Data: 0.16MB + Index: 0.23MB
wpcm_terms |   | Data: 0.52MB + Index: 0.61MB
wpcm_term_relationships |   | Data: 8.52MB + Index: 5.52MB
wpcm_term_taxonomy |   | Data: 1.52MB + Index: 0.59MB
wpcm_usermeta |   | Data: 0.14MB + Index: 0.14MB
wpcm_users |   | Data: 0.02MB + Index: 0.05MB
wpcm_wcpdf_invoice_number |   | Data: 0.00MB + Index: 0.00MB
wpcm_wcv_feedback |   | Data: 0.00MB + Index: 0.00MB
wpcm_wc_points_rewards_user_points |   | Data: 0.02MB + Index: 0.03MB
wpcm_wc_points_rewards_user_points_log |   | Data: 0.05MB + Index: 0.05MB
wpcm_woocommerce_extra_flat_rates |   | Data: 0.00MB + Index: 0.00MB
wpcm_woof_query_cache |   | Data: 0.00MB + Index: 0.00MB
wpcm_yith_wcwl |   | Data: 0.02MB + Index: 0.02MB
wpcm_yith_wcwl_lists |   | Data: 0.02MB + Index: 0.03MB
wpcm_yoast_seo_links |   | Data: 0.27MB + Index: 0.25MB
wpcm_yoast_seo_meta |   | Data: 0.27MB + Index: 0.29MB

**Comment by kloon** [comment]
Please test this with just the woocommerce plugin active as well as on a default theme like twentyseventeen or storefront. Just tested 3.2.1 and shipping zones save and load fine for me.

**Comment by RAMI15** [comment]
No it doesn't work, could it be because of compatibility issues, like these

Advanced Product Labels for WooCommerce |   | par BeRocket – 1.1.1 – Not tested with the active version of WooCommerce

Custom Related Products for WooCommerce |   | par Scott Nelle – 1.3 – Not tested with the active version of WooCommerce

Disable WooCommerce Reviews |   | par pipdig – 1.1 – Not tested with the active version of WooCommerce

MANGOPAY WooCommerce plugin |   | par Yann Dubois, MANGOPAY – 2.4.0 – Not tested with the active version of WooCommerce

Product Brands For WooCommerce |   | par Varun Sridharan – 0.7 – Not tested with the active version of WooCommerce

WooCommerce Weight Based Shipping |   | par weightbasedshipping.com – 5.1.4 – Not tested with the active version of WooCommerce

WooCommerce Product Feed PRO |   | par AdTribes.io – 1.6.8 – Not tested with the active version of WooCommerce

WooCommerce Checkout Field Editor |   | par WooThemes – 1.4.10 – 1.5.7 est disponible – Not tested with the active version of WooCommerce

WooCommerce Cost of Goods |   | par SkyVerge – 2.5.0 – Not tested with the active version of WooCommerce

WooCommerce Google Analytics Integration |   | par WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce

WooCommerce Leetchi payment |   | par Symbioseo – 1.0.0 – Not tested with the active version of WooCommerce

WooCommerce MultiStep Checkout |   | par Mubashir Iqbal – 2.3.8 – Not tested with the active version of WooCommerce

WooCommerce PDF Invoices & Packing Slips |   | par Ewout Fernhout – 2.0.13 – Not tested with the active version of WooCommerce

WooCommerce Points and Rewards |   | par WooThemes – 1.5.13 – 1.6.7 est disponible – Not tested 
Custom Product Tabs for WooCommerce |   | par YIKES, Inc. – 1.6.2 – Not tested with the active version of WooCommerce

YITH WooCommerce Wishlist |   | par YITHEMES – 2.1.2 – Not tested with the active version of WooCommerce

**Comment by kloon** [comment]
Please disable all those plugins and only test with WooCommerce activated. If it works then the issue is with one of the above listed plugins.

**Comment by RAMI15** [comment]
Sorry, i alreday did that but it doesn't work, i get no delivery method
