### ISSUE TITLE
Woocommerce not showing sales price

### ISSUE THREAD

**Issue by desophea** [woocommerce/woocommerce#17463]
![capture 2](https://user-images.githubusercontent.com/33245538/32208899-764e9414-be40-11e7-85c6-c0ddf6ff8083.PNG)

![capture](https://user-images.githubusercontent.com/33245538/32208895-71562b34-be40-11e7-8d73-15590d62a2f8.PNG)
i have product variation enable in my product. but its not showing sales price. 

Eg: if my regular Price is 259 & i make the sales price to 150, i can set the price to 150. But its not showing in my website as 150. Its only show 259 without strike out.

**Comment by kloon** [comment]
Please test this with a default theme, this works fine for me using the lastest WooCommerce on a standard theme such as twentyseventeen or storefront.

I am sure the issue is due to your theme overriding some of the template and does not support the latest version of WooCommerce yet.
