### ISSUE TITLE
Attribute filter is displayed unnecessarily

### ISSUE THREAD

**Issue by petersjeroen** [woocommerce/woocommerce#17466]
_@mikejolley - I don't know if this issue is relating to the same caching issue (https://github.com/woocommerce/woocommerce/issues/17465) but I thought I'll let you know._

Please take a look at this video: https://www.youtube.com/watch?v=4u-Cm2t2B38

As you can see, the "Size" Attribute shows the "S" term. However, there are no products in this category that contain this term.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate

## Steps to reproduce the issue

1. Install Wordpress + WooCommerce (fresh installation, without any plugins)
2. Import sample data
3. Make a new Attribute, called "Size"
4. Add some terms to this attribute: "S", "M", "L", "XL"
3. Make a new category
4. Make a new product in this category
5. Provide this product with the attribute Size, with the term: "S"
6. Activate the "Filter Products by Attribute" widget in the sidebar. Title: Size, Attribute: size, Display type: List, Query Type: AND - Save
7. Watch the category page - _Everything looks normal for now_
8. Remove the "Size" Attribute from the product you made
9. Watch the category page again
10. The size filter is still visible. However, there are no products in this category that contain this term.

**Comment by mikejolley** [comment]
@petersjeroen 

> I don't know if this issue is relating to the same caching issue (#17465) but I thought I'll let you know.

This is why the new issue form asks details such as:

> The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)

I don't think you've gone through any of the steps there. If you go though the steps, it saves us both time in trying to reproduce an issue which is likely patched.

Wait for the 3.2.2 update. It fixes count caches, which things such as this rely on.

Thanks
