### ISSUE TITLE
how to set download method in "force" but view file in browser

### ISSUE THREAD

**Issue by ehsankhorasani** [woocommerce/woocommerce#17469]
Hi
I want to sell movie file and I do not want to show file link to buyer.
for this purpose i set download method in "Forced" option.
So far, everything works fine. But I have a problem.
I want to user see online the movie in its browser as soon as the download button is clicked.
At this time, all files in this case have to be downloaded.

**Comment by mikejolley** [comment]
Not possible. Forcing the download does exactly what it says. To see the movie right away, you'd have to reveal where the movie is stored (link) using the redirect method.

**Comment by ehsankhorasani** [comment]
@mikejolley 
But the user can see the direct link to the file

**Comment by mikejolley** [comment]
To see it in their browser, that has to happen.
