### ISSUE TITLE
3.2.2 MAJOR BUG for Update

### ISSUE THREAD

**Issue by shreyans94** [woocommerce/woocommerce#17478]
Cant update. Cant click on save or anything.

See this quick video screen record

https://www.useloom.com/share/31b2b277b4904691b2400b1bb92daf79

**Comment by mikejolley** [comment]
This one is fixed in 3.2.2 (for future updates). Just go to the main plugins screen, not the bulk updates screen, to avoid the modal.

Or hit "escape" on your keyboard to dismiss it.

Thanks

**Comment by shreyans94** [comment]
ah thanks mike
