### ISSUE TITLE
Update Warnings Do Not Scroll

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#17473]
Hey all,

Sorry if this is already out there - I tried searching but couldn't find it.

When updating, the newest versions warning in the update screen can scroll past the bottom of the window, making it impossible to proceed:

![http://cld.wthms.co/4dbEeh](http://cld.wthms.co/4dbEeh+) 
Full Size: http://cld.wthms.co/4dbEeh

I would have included a GIF, but my recorder is broken today. Updating from WC 3.2.1.

**Comment by GlennMartin1** [comment]
After 3.2.2, this will not occur again. 3.2.2 addresses it for going forward.
