### ISSUE TITLE
Product export/import CSV inconsistencies and no support for commas in fields

### ISSUE THREAD

**Issue by wywarren** [woocommerce/woocommerce#17479]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product with commas in the title, description and short description fields
2. Export product list
3. Open CSV in excel or open office

## Expected/actual behavior

When I follow those steps, I see...

improper CSV separations causing misalignment of data for reimporting

I was expecting to see...

proper delimiters splits or the option to select my delimiter on export, since importing supports optional delimiters but not export. Either that or convert existing commas in fields to a proxy character so it doesn't mess with the CSV formatting.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
`
### WordPress Environment ###

Home URL: https://shop-apc.com
Site URL: https://shop-apc.com/wp
WC Version: 3.2.2
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: zh_TW

### Server Environment ###

Server Info: Apache/2.4.28 (Unix) OpenSSL/1.0.1f
PHP Version: 5.6.31
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.58 - 我們建議 MySQL 版本至少要是 5.6。請見： WordPress 需求
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.2
WC Database Prefix: apcwp_
MaxMind GeoIP Database: ✔
Total Database Size: 30.38MB
Database Data Size: 26.63MB
Database Index Size: 3.75MB
apcwp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
apcwp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
apcwp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
apcwp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
apcwp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
apcwp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
apcwp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
apcwp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
apcwp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
apcwp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
apcwp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
apcwp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
apcwp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
apcwp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
apcwp_ac_abandoned_cart_history: Data: 0.02MB + Index: 0.00MB
apcwp_ac_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
apcwp_ac_email_templates: Data: 0.02MB + Index: 0.00MB
apcwp_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB
apcwp_ac_guest_abandoned_cart_history: Data: 0.02MB + Index: 0.00MB
apcwp_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
apcwp_ac_link_clicked_email: Data: 0.02MB + Index: 0.00MB
apcwp_ac_opened_emails: Data: 0.02MB + Index: 0.00MB
apcwp_ac_sent_history: Data: 0.02MB + Index: 0.00MB
apcwp_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB
apcwp_commentmeta: Data: 0.02MB + Index: 0.03MB
apcwp_comments: Data: 0.02MB + Index: 0.09MB
apcwp_links: Data: 0.02MB + Index: 0.02MB
apcwp_options: Data: 2.08MB + Index: 0.05MB
apcwp_postmeta: Data: 11.48MB + Index: 2.72MB
apcwp_posts: Data: 5.30MB + Index: 0.27MB
apcwp_termmeta: Data: 0.02MB + Index: 0.03MB
apcwp_terms: Data: 0.02MB + Index: 0.03MB
apcwp_term_relationships: Data: 0.05MB + Index: 0.02MB
apcwp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
apcwp_usermeta: Data: 7.05MB + Index: 0.03MB
apcwp_users: Data: 0.02MB + Index: 0.05MB
apcwp_woof_query_cache: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

acf: 2
attachment: 960
customize_changeset: 94
nav_menu_item: 22
page: 17
post: 6
product: 150
revision: 38
shop_order: 8
wc_product_tab: 3
wishlist: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

CloudFlare Flexible SSL: 由 iControlWP – 1.2.2
JSON Basic Authentication: 由 WordPress API Team – 0.1
spgateway: 由 智付通 spgateway – 1.0.0
Advanced Custom Fields: qTranslate: 由 funkjedi – 1.7.23
ACF to REST API: 由 Aires Gonçalves – 3.1.0
AddToAny Share Buttons: 由 AddToAny – 1.7.21
Advanced Custom Fields: 由 Elliot Condon – 4.4.12
APC REST API Extension: 由 Warren Wang @ Qoobit Productions Inc. – 1.0
Cloudflare: 由 John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.1

Coming Soon Page & Maintenance Mode by SeedProd: 由 SeedProd – 5.0.14
聯絡表單7: 由 Takayuki Miyoshi – 4.9.1
CPT-onomies: Using Custom Post Types as Taxonomies: 由 Rachel Carden – 1.3.6
Google XML Sitemaps: 由 Arne Brachhold – 4.0.9
Hide Admin Bar: 由 Shelby DeNike – 0.3.8.1
jQuery Updater: 由 Ramoonus – 3.2.1
WPBakery Visual Composer & qTranslate-X: 由 qTranslate Team – 1.0
WPBakery Page Builder: 由 Michael M - WPBakery.com – 5.3
QOO - Banners: 由 Warren Wang @ Qoobit Productions Inc. – 1.0
QOO - Branding: 由 Warren Wang @ Qoobit Productions Inc. – 1.0
QOO - Social Links: 由 Warren Wang @ Qoobit Productions Inc. – 1.0
qTranslate-X: 由 qTranslate Team – 3.4.6.8
Regenerate Thumbnails: 由 Alex Mills (Viper007Bond) – 2.3.1
WP REST API: 由 WP REST API Team – 2.0-beta15
Storefront Checkout Customiser: 由 WooThemes – 1.1.4 – Not tested with the active version of WooCommerce
Storefront Designer: 由 WooThemes – 1.8.4
Storefront Mega Menus: 由 WooThemes – 1.3.4 – 1.5.0 可用 – Not tested with the active version of WooCommerce
店面固定新增至購物車: 由 WooThemes – 1.1.7
Storefront WooCommerce Customiser: 由 WooThemes – 1.9.2 – Not tested with the active version of WooCommerce
User Role Editor: 由 Vladimir Garagulya – 4.36.1
Facebook Open Graph, Google+ and Twitter Card Tags: 由 Webdados – 2.1.3
Woo Checkout Field Editor Pro: 由 ThemeHiGH – 1.2.3 – Not tested with the active version of WooCommerce
Advanced Order Export For WooCommerce: 由 AlgolPlus – 1.5.0
WooCommerce Search by Product SKU: 由 Clayton Kriesel [Three Remain Production] – 1.0 – Not tested with the active version of WooCommerce
Abandoned Cart Pro for WooCommerce: 由 Tyche Softwares – 7.1
WooCommerce複製帳單地址: 由 Andrew Schultz – 1.16 – Not tested with the active version of WooCommerce
WooCommerce Dynamic Pricing: 由 Lucas Stark – 3.1.0 – 3.1.2 可用 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: 由 WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce Multiple Free Gift PRO: 由 Ankit Pokhrel – 1.2.9 – Not tested with the active version of WooCommerce
WOOF - WooCommerce Products Filter: 由 realmag777 – 1.1.7 – Not tested with the active version of WooCommerce
WooCommerce & qTranslate-X: 由 qTranslate Team – 1.3 – Not tested with the active version of WooCommerce
WooCommerce Smart Refunder: 由 StoreApps – 1.1.1 – Not tested with the active version of WooCommerce
WooCommerce Social Login: 由 SkyVerge – 2.3.2 – Not tested with the active version of WooCommerce
WooCommerce Tab Manager: 由 SkyVerge – 1.8.4
WooCommerce WishLists: 由 Lucas Stark – 2.0.11 – 2.1.0 可用 – Not tested with the active version of WooCommerce
WooCommerce: 由 Automattic – 3.2.2
WP Mail SMTP: 由 WPForms – 0.11.1
WP REST API Controller: 由 YIKES
Inc. – 1.4.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: TWD ( NTD)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

商店起點: #4 - /
購物車: #5 - /cart/
結帳: #6 - /checkout/
我的帳號: #7 - /my-account/
Terms and conditions: ❌ 未設定頁面

### Theme ###

Name: APC Storefront
Version: 1.0
Author URL: http://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: apc-storefront/content-single-product.php
apc-storefront/woocommerce/emails/admin-cancelled-order.php
apc-storefront/woocommerce/emails/admin-failed-order.php
apc-storefront/woocommerce/emails/admin-new-order.php
apc-storefront/woocommerce/emails/customer-completed-order.php
apc-storefront/woocommerce/emails/customer-invoice.php
apc-storefront/woocommerce/emails/customer-new-account.php
apc-storefront/woocommerce/emails/customer-note.php
apc-storefront/woocommerce/emails/customer-on-hold-order.php
apc-storefront/woocommerce/emails/customer-processing-order.php
apc-storefront/woocommerce/emails/customer-refunded-order.php
apc-storefront/woocommerce/emails/customer-reset-password.php
apc-storefront/single-product/meta.php
apc-storefront/single-product/title.php

`
</details>

**Comment by kloon** [comment]
There was an issue with commas in attributes and variations which we fixed in 3.2.2. However this has always been working fine on the title, description and short description as those all values that are quoted in the export file.

I just tested this against master branch as well as 3.2.2 and it imported the title, description and short description file with commas.

Do you perhaps have a sample import file to inspect and test?

[wc-product-export-2017-11-01.txt](https://github.com/woocommerce/woocommerce/files/1433330/wc-product-export-2017-11-01.txt)

Attached is my file in case you want to test on your end.

**Comment by wywarren** [comment]
Thanks for the reply kloon.
After closer inspection, it seems the problem is with commas appearing in my meta data (custom fields) inside the exported CSV.

[wc-product-export-2017-10-31.txt](https://github.com/woocommerce/woocommerce/files/1434271/wc-product-export-2017-10-31.txt)

First instance happens in my file at line 30 on my 'Meta: related_documents'. Is there a way to allow support for comma exports in metas as well? How are commas handled in the other fields? Do they get replaced with a different character and then on import does it get swapped back? If so, then I can try to modify the exporter/importer as such for the other use case scenarios for this feature.

**Comment by wywarren** [comment]
After looking at my own exports of products (without meta data), it seems the convention is that fields with commas in them are wrapped in quotes ie. "Product 1,2,3,4" as per the CSV standard. So it just seems that exported meta values need to be wrapped in quotes which is missing from the current exporter. I will try to narrow it down as to which file is actually responsible for exporting this.

**Comment by wywarren** [comment]
Nevermind sorry guys. It was my fault for trying to open the CSV in OpenOffice. Have to use Microsoft Excel specifically. I will close this thread.

**Comment by wywarren** [comment]
So to follow up in case anyone falls into the same trap as me. CSV files (regardless of exports from woocommerce or not) does not natively support saving to UTF-8 in any of the default excel CSV save options. 

**What does this mean?**

It means if you have an exported CSV with foreign non latin characters, and you open the file, make edits and save it, all the foreign characters encoded in UTF-8/Unicode will be coverted to question marks (?) causing you to lose all your data. So here is my current workaround:

1. Export products CSV from woocommerce
2. Open CSV in notepad and replace all tabs with spaces (this is important for step 6,7)
3. Save sanitized CSV in notepad as UTF-8
4. Open sanitized CSV in excel and save as xlsx first. This allows you to repeatedly save without data being lost and converted to question marks (?).
5. Make edits on xlsx as required and save.
6. Save As the xlsx as Unicode txt in Excel instead. This turns it into TSV text file.
7. Open the Unicode TSV text file in notepad and replace all tabs with commas. (since we already sanitized and replaced all prior tab instances back in step 2, all tabs in this file are legitimate separators).
8. Save Unicode TSV text file as .csv format.
9. Reimport CSV into woocommerce products for delta merge changes

This is tedious but is the only manual labour pipeline for woocommerce data sets in foreign languages.

**Can this be sped up?**

2,3,4 can be delegated to a python script and 6,7,8 can probably be delegated to another python script, but this is still a hassle.

**What else can we do?**

Write our own products exporter/import or suggest a feature for products export as xlsx or tsv instead of csv. 

An alternative feature that might be useful would be just to allow updating of product quantities by deltas instead of absolute values. That way when shipments arrive, you can enter in the new received quantities instead of replacing the value inside the current quantity value.
