### ISSUE TITLE
Checkout Postcode / Zip validation error message missing Billing / Shipping Identification

### ISSUE THREAD

**Issue by tregenza** [woocommerce/woocommerce#17474]
When validating the billing and shipping addresses, all error messages except the Postcode / Zip message identify the field which is wrong. Failure to identify which Postcode/Zip field is incorrect leads to user confusion.

https://github.com/woocommerce/woocommerce/blob/b11ed6e3dba2a05369dc89bdd611a029ed5c547c/includes/class-wc-checkout.php#L634

Suggested edit (untested):

```php
$errors->add( 'validation', sprintf( __( '%s is not a valid postcode / ZIP.', 'woocommerce' ), '<strong>' . esc_html( $field_label ) . '</strong>' ) );
```

**Comment by claudiosanches** [comment]
Edited your comment to help people patch it.
Thanks for your contribution.
