### ISSUE TITLE
Allow adding multiple products to the cart via the add-to-cart query string

### ISSUE THREAD

**Issue by jtsternberg** [woocommerce/woocommerce#17477]
I have written a tutorial for doing this (in a bit of hacky way, due to `WC_Form_Handler`'s private methods), but this seems like prime territory for WC core. If this is considered blessed, I can start on a PR for it along the lines of the code in the tutorial.

https://dsgnwrks.pro/snippets/woocommerce-allow-adding-multiple-products-to-the-cart-via-the-add-to-cart-query-string/

**Comment by mikejolley** [comment]
Related https://github.com/woocommerce/woocommerce/pull/16742

**Comment by jtsternberg** [comment]
Well looky there... it's my tutorial. We can close this issue if you want to keep the thread in one place?

**Comment by jtsternberg** [comment]
A summary from #16742:

> What I'd rather see is either:

- [ ] handling for multiple products in core
OR
- [ ] splitting/refactoring the methods for easier reuse. 

> A new query param is one option.

**Comment by claudiulodro** [comment]
Feel free to submit a pull request for this! A new query param is probably the easiest solution, since it's a bonus feature not directly used in core.

**Comment by yangkennyk** [comment]
3.2 seems to have broken ability to add multiple variable products with this snippet as well.

**Comment by wloske** [comment]
Ok, I'll add a use case for this: We have rewritten the looks of a variable product in the store so that two attributes ("Side" with left and right and "Color" with a list of colors as choices) are not displayed as a "Side" pulldown and a "Color" pulldown but as a fixed row "Left" and fixed row "Right" with a color pulldown for each. As it is currently implemented we have to add an order button to both lines and purchase two single items of the same product on one screen but the product is intended as a pair so only a single button would be nice - the basket still could and should have to single products. We call this a "matrix" product.

Perhaps we are thinking too complicated here for this use case. If anyone has a suggestion for this, it would be very welcomed.

**Comment by jtsternberg** [comment]
@mikejolley How do you feel about the curie notation for defining the product ids/quantities? e.g. 

```
?items-to-cart=<product1-id>:<product1-qty>,<product2-id>:<product2-qty>
```

Background: https://dsgnwrks.pro/snippets/woocommerce-allow-adding-multiple-products-to-the-cart-via-the-add-to-cart-query-string/#comment-12236

(I'm envisioning doing a simple version of the same thing for varations: `<variation1-id>:<variation1-qty>`)


I think the alternative would possibly be multiple params, e.g.

```
?items-to-cart=<product1-id>,<product2-id>&quantities=<product1-qty>,<product2-qty>
```

**Comment by mikejolley** [comment]
I guess thats an option :) Did you see how grouped products do it?

**Comment by jtsternberg** [comment]
Yah, was working through that now actually. Appears to be an array with `$item => $quantity`, where I presume `$item` is the product id. Is that preferred then? The main reason I'm not a fan of that is the URL can get quite long as you have to do something like:

```
?items-to-cart[<product1-id>]=<product1-qty>&items-to-cart[<product2-id>]=<product2-qty>
```

But if we use a custom query var, I guess I we can make it a smaller query var for the ids/quantities, e.g.

```
?items-to-cart=1&add[<product1-id>]=<product1-qty>&add[<product2-id>]=<product2-qty>
```

**Comment by jtsternberg** [comment]
(oops)

**Comment by mikejolley** [comment]
Is the main goal to have a short url, or to just support it across product types? And query string only, or support post/forms too?

**Comment by jtsternberg** [comment]
@mikejolley ideally all of the above, I guess. #17855 ready for review.

**Comment by mikejolley** [comment]
Let's continue discussion in https://github.com/woocommerce/woocommerce/pull/17855

Thanks
