### ISSUE TITLE
Woo 3.2 update not compatible with homepage redirecting

### ISSUE THREAD

**Issue by elijah-martens** [woocommerce/woocommerce#17472]
Greetings Woo Team
 
After applying the WooCommerce version 3.2 patch, we noticed our checkout process is failing during order submission.   The checkout process is attempting to Ajax post update_order_review to giftcatalog?wc-ajax=update_order_review.  It looks like in order to work, it needs to post to ?wc-ajax=update_order_review off the base site url, but we’ve designated the /giftcatalog domain as our homepage.   

We can see the commit that broke this here:
https://github.com/woocommerce/woocommerce/commit/75cc4f91b534ce3114d19da80586bacd083bb5a8

Do you plan on making any accommodation for developers who are redirecting the homepage?

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Have a Woo store that is redirecting the homepage
2. Complete Checkout
3. You will see the following console error, and checkout will not complete: 

giftcatalog?wc-ajax=update_order_review Failed to load resource: the server responded with a status of 403 (Forbidden)

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Your redirect will need to be conditional I think. There are multiple uses for the 'home url' e.g. ajax endpoints, WordPress API etc.

> Do you plan on making any accommodation for developers who are redirecting the homepage?

I don't see how we can; there is no way to know if you're doing a redirect of your own!

**Comment by kloon** [comment]
Closing this, as Mike mentioned use a conditional check when you do your redirect. Assuming you are using WordPress to handle your redirect you can use the conditional wp_doing_ajax and WC_DOING_AJAX constant to check whether an ajax request is running.
