### ISSUE TITLE
Make the Extensions tab smarter based on your connected WooCommerce.com account

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce#17488]
We would like to make this area 'smarter' by using a users connected account we should be able to improve the user experience by things like:

- Not showing them extensions they have either already bought and/or installed on the connected site
- Not showing them extensions which will not work based on certain WooCommerce settings like store location, selling location, shipping location for instance

By doing so we aim to make this section less of a 'here are all the things you could possibly buy' to one that is rather custom and tailored to the type of store a user is trying to create.

The proposed functionality is to keep the code that does this on WooCommerce.com itself, and just get Core itself to request an API endpoint on WooCommerce.com to show the relevant extensions based on the connected account.

**Comment by mikejolley** [comment]
Resolved by https://github.com/woocommerce/woocommerce/pull/17955 I believe.
