### ISSUE TITLE
Adding sales tax to WC coupon - bug

### ISSUE THREAD

**Issue by WhoopDav** [woocommerce/woocommerce#17485]
Hello,

I have reported this bug via live chat to WooCommerce, and they admitted this is a bug. However it has not been corrected in the latest WC update released yesterday.

In checkout when applying a coupon, the system adds VAT (sales tax) to the coupon, which it should not. So Instead of removing 30% from the total cart value (or from a product), it removes 30% + VAT. We require a fix ASAP as this is loosing us money!

This was not an issue in WooCommerce 3.1.2. The issue seems to have arisen in 3.2.1.

We have no other coupon plugin running. This is an issue with the core WC coupon system.
Thanks

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by WhoopDav** [comment]
To reproduce the issue:

1. Make sure latest WC installed.
2. Create a coupon (% off product x, when product y in cart).
3. Go to checkout, apply coupon. You will see the % + sales tax is discounted from the cart value. However only the % should be discounted, not the sales tax. On coupons there is no sales tax.

**Comment by kloon** [comment]
I think you might be having an issue with an extension here and not core. I just tested with the 3.2.2 and our master branch and in both cases discount was applied before tax http://cld.wthms.co/9Nziih <-- That is for 10% discount.

You also mention 

> Create a coupon (% off product x, when product y in cart).

That is not something that is supported in core which makes me think this is definitely an extension that is causing the issue.

I suggest you follow the instructions you received when creating the issue again and disable all plugins except WooCommerce and also switch to a default theme like Storefront or Twentyseventeen to test this with.

Again, as shown in my screenshot discounts are applied before taxes in 3.2.2 and on the master branch of WooCommerce.

**Comment by WhoopDav** [comment]
No this is not a bug caused by another plugin. This is an issue with WooCommerce, which has already been confirmed by a member of the WooCommerce support team. The only issue is I did not explain myself properly.

The problem has nothing to do with a coupon being applied before or after taxes, as you mentioned in your reply. The problem is that WooCommerce is adding sales tax on to the coupon value, which it should not. Coupons should never have sales tax added to their "value".

You can check this by setting up a 10% coupon, which is applied to product X, if Product X + product Y are in the cart. Let's say product X costs 100€, then a 10% coupon discount will by 10€. So therefore customer should get product X for 90€ (if product Y also in their cart).

However since version 3.2.1, it will actually calculate the coupon value at "10% + sales tax on that 10% coupon". So in the end it is giving the customer a discount on product X of 11,90€ (based on 19% sales tax in DE), rather than 10€. This is completely wrong.

Please look at this again and you will see this issue. As I said, someone from WooCommerce support already reproduced the issue and confimed it was a bug.

BR

**Comment by WhoopDav** [comment]
In communication with WooCommerce again about this to check if there is any plugin conflict. Will report back after I hear back from WooCommerce support.

Cheers

**Comment by WhoopDav** [comment]
OK - with the latest WC update 3.2.3 this problem has now been fixed. So it seems there was an issue WooCommerce end, but happy all now is working. Thanks again
