### ISSUE TITLE
Inline style is removed by woocommerce 3.2.2 in shop page 

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#17498]
Why is my issue brutally closed without even looking properly at it?

The changes in woo 3.2.2 are causing code to be stripped from the shop page which is not ok. See my reply here 

 if i change line 712 in woocommerce/includes/wc-templates-functions.php to a line without wp_kses_post($description) it works like it did before.

https://github.com/woocommerce/woocommerce/issues/17492

**Comment by mikejolley** [comment]
We can respond to closed comments. Don't abuse the issue tracker.
