### ISSUE TITLE
Allow customers to use search on the Extensions tab

### ISSUE THREAD

**Issue by garymurray** [woocommerce/woocommerce#17490]
To improve a users experience in the Extensions tab in core, we would like to start by adding a basic search functionality that will allow a customer to be able to search based on an extensions title, i.e. a search for `Subscriptions` would return WooCommerce Subscriptions, `Facebook` would return Facebook for WooCommerce for instance etc.

This will improve the current experience which relies on a user having scroll and visually search amongst the extensions shown.

**Comment by garymurray** [comment]
I propose we add a search field to the screen as per the following design - the search field would stay consistent across all the categories there (i.e. Featured, Popular, Payment Gateways etc) and would replace the extensions shown on that tab with the results. This search will be based the names of the extensions to start.

Showing the persistent search field:
![search in core](https://user-images.githubusercontent.com/10805911/32499120-5284ab8c-c3da-11e7-8b91-4d2bed0f889e.png)

Showing a search result:
![search results](https://user-images.githubusercontent.com/10805911/32499150-6d6e326a-c3da-11e7-8c70-c032c4b1fdd4.png)

Clearing the search term should return the items originally on that tab. Any comments/concerns @belcherj

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17926
