### ISSUE TITLE
One more paramter for filter woocommerce_adjust_non_base_location_prices

### ISSUE THREAD

**Issue by stiletagegmbh** [woocommerce/woocommerce#17495]
Your filter 'woocommerce_adjust_non_base_location_prices' has only one parameter that is boolean, so that the prices can be adjusted only in general, e.g. the function works only for all products or is not applied at all.

We would like to decide whether to return true or false depending on the product.

Use Case: By European law, if your shop base country is an EU country, the product is downloadable and the customers billing country is also an EU country (but a different country than the shop base country), then the taxes of the billing country have to be applied. In that case some shop admins want that the price including tax (gross) of the product is always the same (the filter 'woocommerce_adjust_non_base_location_prices' should return false) but in any other case (the product is not downloadable) the filter should return true.

Adding this filter would make it much easier with less code for us to implement the use case. Currently, we have to recalculate the taxes and prices with a lot of code by hooking into several filters and actions.

We suggest a PR in some moments.

**Comment by mikejolley** [comment]
@stiletagegmbh I'd like to reject this one - I'll add some comments in #17496 to keep the comments in one place.
