### ISSUE TITLE
Inline style is removed in shop ,page nin v 3.2.2 pls provide a fix

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#17492]
Hi

I have issues with woocommerce shop page.

We have a shortcode for a carousel which adds inline style like this into the page content.

`<style>
#carousel_666fcf1eec4d8de0cdb32bc8109a0a25 > ul > li {
	width: 100px;
	height: 132px;
}
</style>`

It works in every page but not in the shop page. In the shop page the &lt;style&gt; and &lt;/style&gt; are removed.

How to prevent this from happening?  This mworks just fine in 3.2.1 of woocommerce. But in 3.2.2. the style tags are gone and i get the css.

How can i get this to work again?

**Comment by mikejolley** [comment]
This was not changed in 3.2.2. if this is category description, it's correct to be filtered out. Data validation may strip content like this. 

> How to prevent this from happening? 

Don't add CSS inline in post content. Add it to your theme css/custom.css file if it exists/or footer template. There are also plugins to add custom css to your site. Use those - it's cleaner.

Thanks

**Comment by BackuPs** [comment]
Hi

Are you kidding me? That is too simple for a answer. The inline style is added based on settings in a shortcode. **And yes it was changed in 3.2.2** if i change line 712 in woocommerce/includes/wc-templates-functions.php to a line without wp_kses_post($description)  it works like it did before.

// Woocommerce 3.2.2 workaround to for wp_kses_post \plugins\woocommerce\woocommerce.3.2.2\woocommerce\includes\wc-template-functions.php line 712

Please revert the change as the woocommerce shop page can have valid code inline code etc before woo adds its shop articles.

**Comment by BackuPs** [comment]
And why are you closing this thread without even looking at my problem and just saying that code was not changed?  I can pinpoint where the cause is in the latest woo build.

**Comment by mikejolley** [comment]
I see where you mean now. https://github.com/woocommerce/woocommerce/commit/f9cff6e3f8b2993a09a66cf50fe2f35c99ec33df

vs https://github.com/woocommerce/woocommerce/blob/3.2.1/includes/wc-template-functions.php#L701

wp_kses_post seems appropriate, but I see regular posts do output style tags.

@claudiosanches Can you take a look?

Either way, I stand by my comment - styles should not be added inside content.

**Comment by mikejolley** [comment]
> I can pinpoint where the cause is in the latest woo build.

Maybe include this in your report next time then :)

**Comment by BackuPs** [comment]
Hi

I did add this in my comment as a second reply. I dont know where that went.

Shortcodes cab add dynamic styles on executing the shortcode. Since there are more then one carousel to be added, if the user desires such, i can only add the styles dynamically and apply them to the individual carousels by inline style and target their ID. They are unfortunately added in the page content.

There are also scripts added into page content for f.e. google adds. It very normal todo such and there are many examples more that do so.

I will wait on the next reply from claudio.

**Comment by mikejolley** [comment]
You can add styles to your footer. Store them and output them in wp_footer action. Then you're not hindered by sanitisation.

**Comment by claudiosanches** [comment]
I prefer keep the `wp_kses_post()`, this is a pluggable function, so easy to change into the theme or by a plugin.

@BackuPs you can include it into your theme's (or child theme) `functions.php` and will solve the problem:

```php
/**
 * Show a shop page description on product archives.
 */
function woocommerce_product_archive_description() {
	// Don't display the description on search results page.
	if ( is_search() ) {
		return;
	}

	if ( is_post_type_archive( 'product' ) && 0 === absint( get_query_var( 'paged' ) ) ) {
		$shop_page = get_post( wc_get_page_id( 'shop' ) );
		if ( $shop_page ) {
			$description = wc_format_content( $shop_page->post_content );
			if ( $description ) {
				echo '<div class="page-description">' . $description . '</div>';
			}
		}
	}
}
```

**Comment by BackuPs** [comment]
So if i have a hundred shortcodes i need to store the css and scripts etc etc.  and then add them into the footer. How does that work? store where? and how to add them into the footer?


Thank you  i already had that solution figured out. But i would prefer a better solution because now i have to check on every update of woo if you changed that function and redo your changes into that function in my theme common functions file.

There will be more themes and plugins that will have issues with this change. Please provide a better fix 

thank you !

**Comment by mikejolley** [comment]
> So if i have a hundred shortcodes i need to store the css and scripts etc etc. and then add them into the footer. How does that work? store where? and how to add them into the footer?

> Shortcodes cab add dynamic styles on executing the shortcode. 

Store the dynamic styles at runtime to a variable.

Hook into wp_footer.

Output your dynamic styles all at once, in the footer.

**Comment by BackuPs** [comment]
> I prefer keep the wp_kses_post(), this is a pluggable function, so easy to change into the theme or by a plugin.

@claudiosanches   do you have a example?

**Comment by BackuPs** [comment]
@claudiosanches I thought you ment change the wp_kses_post behaviour. The function i already did add after i found the cause. But as said now i have to check on every woo update if you guys added code to that function in order to keep my changed function working.

There will be more users running into this issue

**Comment by claudiosanches** [comment]
@BackuPs I said that our function is pluggable and can be changed.
But yeah, I'm going to remove the `wp_kses_post()` because will remove any embed from there.

**Comment by BackuPs** [comment]
That you very much for understanding my issue and point ! Have a great day
