### ISSUE TITLE
Keyboard issue on checkout/Cred

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#17494]
Hey guys

I'm using WooCommerce 3.1.2. Recently We've received noticed about Credit Issue. There is no "/" on the Expiry. So Customers can't type something like 09/18. As the result, they can't place orders on mobile with Stripe.

The workaround is to remove type=”tel”  in woocommerce/includes/gateways/class-wc-payment-gateway-cc.php

I expected it should have full keyboard or automatically add "/"

![img_5380](https://user-images.githubusercontent.com/2909982/32279131-2e8b0294-beee-11e7-803d-8cfc1f6a51b5.PNG)

**Comment by mikejolley** [comment]
Tel is correct and something the library we're using (from Stripe) recommends.

> I expected it should have full keyboard or automatically add "/"

The / is automatically added. If you're not seeing this, it could be that the credit card form scripts are missing from your store, or the gateway has not implemented them correctly. 

I suggest you do proper testing with extensions disabled, and raise this with the gateway you're using. I don't think you're using our Stripe gateway based on the description in the screenshot but you may have customised it. If it is ours, once ruling out conflicts with the theme and other extensions you can log an issue on https://github.com/woocommerce/woocommerce-gateway-stripe

Please in future include all details, including the system status report as requested.

Thanks

**Comment by kevin25** [comment]
I saw this 

https://wordpress.org/support/topic/checkout-expiry-date-requirement/

**Comment by mikejolley** [comment]
@kevin25 They are reporting the symptoms, not the cause. Tel is not the problem here. The script handles formatting.
