### ISSUE TITLE
Available plugins when connecting a collaborator account

### ISSUE THREAD

**Issue by hedqvist** [woocommerce/woocommerce#17503]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Be added as a collaborator to a WooCommerce.com account.
2. Connect collaborator account to WooCommerce -> Extensions (Plugins)
3. Available plugins to download is show for the entire collaborator account.

## Expected/actual behavior

When I follow those steps, I see all plugins releated to my collaborator account and all my clients, as expected.

I would like to have the option to only show the clients available plugins, perhaps to pass the email of the client to a filter? or have a setting when connecting the WooCommerce.com account to choose the clients account.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
Can you explain that again? Steps to reproduce shows how collab accounts work. What is the bug?

If you want to only give them certain plugins, there is a new 'share' feature on woocommerce.com.

**Comment by hedqvist** [comment]
@mikejolley I wouldnt call this a  bug, but more like a enhancement.

Since we are added as collaborator on multiple accounts we have access to somewhat 40 plugins from the WooCommerce.com site.

When we connect our collaborator account, the plugin section show all clients plugins, here we would like to limit what extensions that are shown so our client doesnt see all our other clients plugins.

Attaching screenshot.
![naturesforlife se-wp-admin-admin php-page wc-addons section helper filter all 1](https://user-images.githubusercontent.com/10596704/32288484-5e367d7a-bf34-11e7-8670-acdc0a32847b.png)

**Comment by mikejolley** [comment]
If you share plugins with clients, this won't happen? I think that feature was added to avoid the above.

**Comment by hedqvist** [comment]
@mikejolley That requires us to handle the payment and subscription right? Since we would like the client to own their plugins and handle renewals by themself and we handle installation and setting up WooCommerce. If there is a better way around this, we are happy to change :)

**Comment by dougaitken** [comment]
Ideal scenario @hedqvist would be that your client purchases the subscription and you are added as a collaborator onto their account, right? 

Their WooCommerce.com account is then connected to that screen and _only_ their extensions are seen. You are a collaborator can download the extensions from _your_ WooCommerce.com account, and since their account is connected to the [manage extensions](https://docs.woocommerce.com/document/managing-woocommerce-com-subscriptions) section, you can update and activate extensions for them as needed.

**Comment by hedqvist** [comment]
@dougaitken That is correct. But when the client for some reason doesnt manage to connect their account we sometimes solve it by connecting our account, where we are added as a collaborator.

So a way to filter out all our other clients would perhaps be doable via a filter where we only filter out our clients email and display plugins connected to the clients account.

Or have it ask when creating the connection to the WooCommerce.com account if you want to connect a clients account where we have been added as collaborator.

**Comment by mikejolley** [comment]
Looks like this feature request is being worked on internally for a future update.

Internal ref: https://github.com/Automattic/woocommerce.com/issues/2602

Thanks

**Comment by dougaitken** [comment]
Sure @hedqvist, this is work involved with WooCommerce.com rather than the plugin as Mike mentioned. 

> But when the client for some reason doesnt manage to connect their account we sometimes solve it by connecting our account, where we are added as a collaborator.

If this is the case, get your client to open a ticket - we'd rather everyone was able to connect their accounts and manage subscriptions correctly than you having to use these workarounds. Reach out via WooCommerce.com/my-account at any time! 👍

**Comment by hedqvist** [comment]
@dougaitken Perfect! Thanks for the fast replies and it sounded like Mike had an internal issue on this as well 👍
