### ISSUE TITLE
Apply filters to "registration-error-email-exists" error.

### ISSUE THREAD

**Issue by jdmadison** [woocommerce/woocommerce#17505]
The default error message can be confusing to users on multisite installations, particularly those serving multiple domains. Calling `apply_filters` on the message and passing the email address as a parameter lets me display a more informative error message that includes the name/domain of the site where the user has already registered.

Submitting a PR and will reference this issue as per the contributor guidelines.

**Comment by mikejolley** [comment]
Closed in favour of https://github.com/woocommerce/woocommerce/pull/17507
