### ISSUE TITLE
Sidebar moved from right to the bottom of the products page.

### ISSUE THREAD

**Issue by Hayko1994** [woocommerce/woocommerce#17506]
After moving the theme from one subdomain to another one WoCommerce was destroyed. After the theme installation sidebar moved from the right to the bottom of the products page. How can this issue be solved?

**Comment by mikejolley** [comment]
You may have lost some customisations you had made.

See https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/

Non-supported themes require that you add the 'wrapper' templates so it knows how to markup the page.

Thanks
