### ISSUE TITLE
Prompt Connection to WooCommerce.com for Updates

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#17501]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

When WooCommerce + a WooCommerce.com plugin is active, no notice is displayed to the user to get updates: http://cloud.skyver.ge/2S1a0M1x172B

1. Install a WooCommerce.com extension
2. See there's no notice to connect to your account

## Expected/actual behavior

Previously, users were prompted to connect to the Woo helper for updates. Now, new customers don't know that they should connect via the extensions tab to get updates, so we've had several tickets lately where customers didn't even know updates were available and that they should connect their site.

This should likely show a persistent notice if the `woothemes_queue_update` function exists on the site and the site isn't connected to WooCommerce.com, similar to the persistent Woo helper notice. I see [this is always removed now](https://github.com/woocommerce/woocommerce/blob/d1ad5a92d218931a230a265f406da09031f9ac02/includes/admin/helper/class-wc-helper-compat.php#L24), when instead, a new notice should replace this.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
@garymurray
