### ISSUE TITLE
Order address indexes update : search still not working

### ISSUE THREAD

**Issue by contremaitre** [woocommerce/woocommerce#17504]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

1. update database with : "Order address indexes" (it says 18267 indexes added for me)
2. search for an order with for example the city of an address
3. no results found if the order was created before WC 3

**Comment by mikejolley** [comment]
Using this method, only billing first and last name get re-indexed. Doing it for all fields would be a very slow, resource intensive process. You can do this yourself if you want using SQL/PHP. Base it on:

https://github.com/woocommerce/woocommerce/blob/1d165009d09cec29f6ea6382545a6ea0a58f59d9/includes/api/class-wc-rest-system-status-tools-controller.php#L403-L419

New orders will have full indexes, as well as old orders which are edited.
