### ISSUE TITLE
html showing on front end

### ISSUE THREAD

**Issue by tiredasamomma** [woocommerce/woocommerce#17514]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Updated to latest version
2. Front page html or text is showing on visual 
3. deactivate and it disappers
4. activate woocommerce and text tab/ html is showing on front end/visual

deactivated all plugins, it is woocommerce.

## Expected/actual behavior

When I follow those steps, I see...
deactivate it returns to normal
I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
`
### WordPress Environment ###

Home URL: http://enchantedaccents.com
Site URL: http://enchantedaccents.com
WC Version: 3.2.2
Log Directory Writable: 
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: 
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.10
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.23
Max Upload Size: 2 MB
Default Timezone is UTC: 
fsockopen/cURL: 
SoapClient: 
DOMDocument: 
GZip: 
Multibyte String: 
Remote Post: 
Remote Get: 

### Database ###

WC Database Version: 3.2.2
WC Database Prefix: wp0s_
Total Database Size: 9.53MB
Database Data Size: 7.99MB
Database Index Size: 1.54MB
wp0s_woocommerce_sessions: Data: 4.02MB + Index: 0.02MB
wp0s_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp0s_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp0s_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp0s_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp0s_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp0s_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp0s_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp0s_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp0s_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp0s_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp0s_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp0s_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp0s_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp0s_commentmeta: Data: 0.02MB + Index: 0.03MB
wp0s_comments: Data: 0.02MB + Index: 0.09MB
wp0s_ewwwio_images: Data: 0.27MB + Index: 0.22MB
wp0s_links: Data: 0.02MB + Index: 0.02MB
wp0s_options: Data: 1.19MB + Index: 0.11MB
wp0s_postmeta: Data: 1.52MB + Index: 0.34MB
wp0s_posts: Data: 0.36MB + Index: 0.06MB
wp0s_termmeta: Data: 0.05MB + Index: 0.03MB
wp0s_terms: Data: 0.06MB + Index: 0.03MB
wp0s_term_relationships: Data: 0.06MB + Index: 0.05MB
wp0s_term_taxonomy: Data: 0.06MB + Index: 0.06MB
wp0s_usermeta: Data: 0.02MB + Index: 0.03MB
wp0s_users: Data: 0.02MB + Index: 0.05MB
wp0s_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp0s_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 179
custom_css: 1
mailmunch_page: 2
nav_menu_item: 10
page: 7
post: 42
product: 93
revision: 82

### Security ###

Secure connection (HTTPS): Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: 

### Active Plugins (3) ###

A2 Optimized WP: by A2 Hosting – 2.0.9.4
Rename wp-login.php: by Ella Iseulde Van Dorpe – 2.5.5
WooCommerce: by Automattic – 3.2.2

### Settings ###

API Enabled: –
Force SSL: 
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #51 - /
Cart: #43 - /wishlist/
Checkout: #42 - /submitlist/
My account:  Page does not contain the shortcode.
Terms and conditions: #590 - /rental-policies-faq/

### Theme ###

Name: Vogue
Version: 10.4.3
Author URL: https://kairaweb.com/
Child Theme:  – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: 

### Templates ###

Overrides: –
`


```
</details>

**Comment by galbaras** [comment]
A link to the page will help and a pointer as to where the HTML appears. I cannot see a similar thing on my sites.

Also, what version did you first see it with?

**Comment by galbaras** [comment]
The HTML code seems to be for Google Analytics (at least on your home page). Do you have a plugin the injects this code, or a snippet from Google Tag Manager in a filter?

Searching this repo for "gtag" comes up empty, so it's not likely WooCommerce.

**Comment by tiredasamomma** [comment]
Hi

Link:
https://enchantedaccents.com
It's only on front page.
It happened when I updated to 
Version 3.2.2

-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 11/2/17, 1:18 AM Gal Baras <notifications@github.com> wrote:
A link to the page will help and a pointer as to where the HTML appears. I cannot see a similar thing on my sites.
Also, what version did you first see it with?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/woocommerce/woocommerce","title":"woocommerce/woocommerce","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/woocommerce/woocommerce"}},"updates":{"snippets":[{"icon":"PERSON","message":"@galbaras in #17514: A link to the page will help and a pointer as to where the HTML appears. I cannot see a similar thing on my sites.\r\n\r\nAlso, what version did you first see it with?"}],"action":{"name":"View Issue","url":"https://github.com/woocommerce/woocommerce/issues/17514#issuecomment-341320302"}}}

**Comment by mikejolley** [comment]
Please apply this - https://github.com/woocommerce/woocommerce/pull/17499

**Comment by tiredasamomma** [comment]
is there a way to regress.. and go back to an older version to solve this?
Its only when I deactivate woocommerce, the very last one that it goes away.

**Comment by mikejolley** [comment]
You could,  but it would be good it you could apply the above patch to confirm it resolves the issue before we other pushing another update.

**Comment by tiredasamomma** [comment]
ugh, no idea to get that done.
on plugin / webhooks?
or theme;  no child

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17499/files

Edit woocommerce/includes/wc-template-functions.php line 710

Change `wp_kses_post( $description )` to `$description`

**Comment by tiredasamomma** [comment]
Can't find it, not sure what I'm missing.

**Comment by tiredasamomma** [comment]
Finally, yes that was it... whew, you can send the check to the above.. 
hehe... thanks
