### ISSUE TITLE
Filter products by attribute

### ISSUE THREAD

**Issue by QuAzI** [woocommerce/woocommerce#17518]
I fill products, attributes (features and variations), and terms through API.
But I can't use filters. I must fill wp_term_relationship table manually and set wp_term_taxonomy.count = 1.
How it can be filled via API? I can't find this code. Without it even if product visually completed, filters doesn't work properly.

WC version: 3.2.2
WP version: 4.8.3
API V2

**Comment by mikejolley** [comment]
I'm not sure how you expect anyone to properly advise without seeing the API requests you're making :)

To test this I added a new term to the attribute 'color' when creating a new product.

- Term was created and backend showed count 1.
- Frontend filter was updated and also showed count 1.
- Filter worked when clicked.

JSON I used:

```
{
  "name": "Premium Quality",
  "type": "simple",
  "regular_price": "21.99",
  "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
  "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
  "attributes": [
			{
				"id": 1,
				"name": "Color",
				"position": 0,
				"visible": true,
				"variation": false,
				"options": [
					"Testing-17518"
				]
			}
		]
}
```

Seems to be fine.
