### ISSUE TITLE
Shop Owner Email: Order information shows invalid Price for Discounted Products and shows invalid subtotal 

### ISSUE THREAD

**Issue by Grauen** [woocommerce/woocommerce#17511]
Woocommerce 3.2.2

We had an order which included one non sale product and one sale product. The customer also used a coupon.

If a customer submits an order, woocommerce will sent an email to the shop owner. In this email it will list the ordered products, the subtotal excluding discounts, the amount of the discount, if the customer used a coupon, and the total amount the customer has paid for this order.

At this moment the price of the sale products and the amount excluding discount are not correct. Only the final total amount and the discount are correct.

In our case we had a product with a regular price of 8,90€ including taxes and the discount price was 1€ including taxes.

The amount of the product listed in the store owners confirmation mail is 7,27€ instead of 1.00€. This incorrect amount will also be used to calculate the Subtotal.

**Comment by mikejolley** [comment]
Sounds related to https://github.com/woocommerce/woocommerce/issues/17517
