### ISSUE TITLE
Woocommrece Rest Api V2 Sorting Product with default WordPress Options

### ISSUE THREAD

**Issue by REA70R** [woocommerce/woocommerce#17515]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [X] I have included a failing test as a pull request (Optional)

I'm using woocommerce RestApi v2 in Android. There is sorting options: `date`, `id`, `include`, `title` and `slug`. Default is `date`.

1) I want to know that how to do sorting by  `Default Sorting` ,`Sort By Popularity`,`Sort By Average Rating`,`Sort by newness`,`Sort by Price: low to high`,`Sort By Price:high to low` . These option is by default availabe at shop page but how to do in api?

2) How to get country [ Name,Code] and its states?
I got in php we can do this-

       global $woocommerce;
       $countries_obj   = new WC_Countries();
       $countries   = $countries_obj->__get('countries');
       $default_country = $countries_obj->get_base_country();
       $default_county_states = $countries_obj->get_states( $default_country );`

how can I do this via rest api? without using php api?

**Comment by mikejolley** [comment]
If it's not documented, it's not possible in this version of the API. 

You can extend the API with code via a plugin to add support for these additional options, or if you want you can contribute to the next API version here:

https://github.com/woocommerce/wc-api-dev

All API feature requests and API contributions can go there.

Thanks!

**Comment by dliver-more** [comment]
@IntelliJAbhishek did you ever find a workaround for this? I'm dealing with the same right now and it doesn't appear to be supported in V3 of the API either.

**Comment by IntelliJAbhishek** [comment]
@dliver-more we have created custom rest api for this purpose.
