### ISSUE TITLE
adjust_non_base_location_price function in Class WC_Cart_Totals fails array compare

### ISSUE THREAD

**Issue by nickrigby** [woocommerce/woocommerce#17517]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Noticed a bug in a UK based store, where coupon discounts are incorrectly calculated when non-base location is chosen for shipping and a coupon is applied. The grand total of the order ends up being less than it should be, because a tax amount is added to the discount, even though the discount displays as the correct amount.

1. Enable taxes *checked*
2. Prices entered with tax *checked*
3. Calculate shipping price based on *customer shipping address*
4. Store address country set to United Kingdom (GB)
5. Default customer location set to *shop base address*
6. Standard tax rate for "GB" set to 20%, priority 1, no shipping tax, no compounds.
7. Standard tax rate for another EU country e.g. Greece, where the tax is also set to 20%, priority 1, no shipping tax, no compounds.
8. Add a product to the cart
9. Apply a discount (percentage or fixed

## Expected/actual behavior

When I follow these steps, and add 1 product totaling £170 to my cart, plus a 10% coupon, I expect to see:
- Subtotal: £170
- Discount: £17
- Shipping: £6.95
- Order total: £159.95

When my shipping address matches the store base location, everything tallies up.

When I choose "Greece" (from step 7 above), which has an identical tax setup as GB at 20%, the discount amount is displayed correctly, but order total is incorrect, by the amount of 20% (the tax rate) added to the discount. E.g. 1 product in cart at £170. Discount of 10% (£17) applied. Shipping is £6.95, the total incorrectly displays as £156.55, which is £3.40 less than it should be (it should be £159.95). The discrepancy of £3.40 is 20% of the discount amount, which is exactly the tax rate. If you change the tax rate for Greece to 10%, the discrepancy will be 10% of the discount amount.

It appears that the issue is on line 454 of `includes/class-wc-cart-totals`. An array comparison is made, but because the keys are different, the condition fails, even when tax rates are identical. My two example arrays from above that should match:

`$item->tax_rates`
```php
Array
(
    [2] => Array
        (
            [rate] => 20.0000
            [label] => VAT
            [shipping] => no
            [compound] => no
        )

)
```

`$base_tax_rates`
```php
Array
(
    [1] => Array
        (
            [rate] => 20.0000
            [label] => VAT
            [shipping] => no
            [compound] => no
        )

)
```
Wondering if the code should be modified to only compare the array valiues:
```php
if ( array_values($item->tax_rates) !== array_values($base_tax_rates) ) {
```
## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://localhost.dev
Site URL: https://localhost.dev
WC Version: 3.2.2
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.27 (Unix) OpenSSL/1.0.2l PHP/7.0.22
PHP Version: 7.0.22
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
SecureTransport

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.2
WC Database Prefix: wp_
Total Database Size: 40.38MB
Database Data Size: 20.60MB
Database Index Size: 19.78MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.19MB + Index: 0.19MB
wp_comments: Data: 1.52MB + Index: 0.67MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mage_migrate_customers: Data: 0.27MB + Index: 0.00MB
wp_options: Data: 0.23MB + Index: 0.02MB
wp_pantheon_sessions: Data: 0.02MB + Index: 0.03MB
wp_postmeta: Data: 3.52MB + Index: 4.48MB
wp_posts: Data: 1.50MB + Index: 0.27MB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_tinvwl_items: Data: 0.14MB + Index: 0.00MB
wp_tinvwl_lists: Data: 0.48MB + Index: 0.00MB
wp_usermeta: Data: 10.52MB + Index: 12.03MB
wp_users: Data: 1.52MB + Index: 1.17MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB
_pantheon_heartbeat: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 161
acf-field-group: 24
attachment: 53
customize_changeset: 2
nav_menu_item: 8
page: 14
post: 4
product: 726
revision: 104
shop_coupon: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (14) ###

Native PHP Sessions for WordPress: by Pantheon – 0.6.4
Advanced Custom Fields PRO: by Elliot Condon – 5.6.3
Contact Form 7: by Takayuki Miyoshi – 4.9
LiveChat WooCommerce: by LiveChat – 1.1.10 – Not tested with the active version of WooCommerce
Mage Migrate: by Nick Rigby – 1.0 – Not tested with the active version of WooCommerce
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.11
Timber: by Jared Novack + Upstatement – 1.5.2
WooCommerce Brands: by WooCommerce – 1.5.2 – Not tested with the active version of WooCommerce
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.4
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Points and Rewards: by WooCommerce – 1.6.7 – 1.6.8 is available
WooCommerce: by Automattic – 3.2.2
Yoast SEO: by Team Yoast – 5.6.1
WP Redis: by Pantheon
Josh Koenig
Matthew Boynes
Daniel Bachhuber
Alley Interactive – 0.7.0


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #11 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by nickrigby** [comment]
Thinking about it more, even though I believe the array compare should potentially be done on the array values, there is still something not quite right within that conditional (lines 455-460), since even if that conditional fails, my tax rates are identical, so the outcome of calculations should be identical.

If I can provide any further detail, please let me know.

**Comment by mikejolley** [comment]
Please check https://github.com/woocommerce/woocommerce/pull/17529 for us.

**Comment by nickrigby** [comment]
@mikejolley Thank you, Mike. Tested the release and this issue is now resolved. Many thanks for the fast turnaround!
