### ISSUE TITLE
WooCommerce Plugin crashes the site

### ISSUE THREAD

**Issue by randayousef** [woocommerce/woocommerce#17513]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. The site started crashing this morning after the latest WooCommerce update was made (v 4.2.2). There were no update errors coming up anymore.
2. We are using a theme for the site (dash theme: https://themeforest.net/item/dash-handmade-furniture-marketplace-theme/12650747) and we assumed the issue was there, so we deactivated all plugins relevant to the dash theme and we tried to trace any errors why the site was crashing
3. After de-activating all plugins and re-activating one at a time, everytime WooCommerce is activated, it crashes the entire site,
4. We have not made any changes anywhere else and it was working just fine before the roll out of this update. 
5. The errors or notifications on the WooCommerce Status log are attached for reference.
[WooCommerce_Error_Log.txt](https://github.com/woocommerce/woocommerce/files/1436423/WooCommerce_Error_Log.txt)

## Expected/actual behavior

When I follow those steps, I see...
Nothing - white screen - site down.

I was expecting to see...
Products being displayed as they were before the new update 4.2.2

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
Home URL: http://coedist.staging.wpengine.com
Site URL: http://coedist.staging.wpengine.com
WC Version: 3.2.2
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
</details>

**Comment by mikejolley** [comment]
Since you're using page builders, it's likely related to https://github.com/woocommerce/woocommerce/pull/17499 Apply that patch.

If it's a real 'crash'/error, we'll need to see the wordpress error log. You sent the system status report, not the error logs. You can also view errors in WC > System > Logs

Let me know.

Thanks

**Comment by randayousef** [comment]
Yes by white screen I am referring to an actual error. Everything goes blank, even the back end editor, we can't edit pages or posts, everything crashes. 

For some reason this patch did not work for us - not sure if we're doing something wrong or if we have a different scenario.

I attached the error logs in case that helps.
The errors we trace started off stating that the Page builder plugin we are using on our theme is the reason there are issues. We de-activated all plugins and went through them one at a time to activate separately until it came down to the page builder and woo-commerce. When woo-commerce is deactivated, everything crashes. But when page-builder is de-activated, nothing happens.


Thank you!
[coedist_staging_error_logs-2017-11-02_13-43-17.txt](https://github.com/woocommerce/woocommerce/files/1438147/coedist_staging_error_logs-2017-11-02_13-43-17.txt)

**Comment by mikejolley** [comment]
I see a memory limit error, and a problem in `/wp-content/themes/dash-child/footer.php` Anything wc related in there?

**Comment by randayousef** [comment]
[footer-php.txt](https://github.com/woocommerce/woocommerce/files/1438391/footer-php.txt)
We contacted wpengine about the memory limit error and we had this increased to 512MB, which they said is the absolute maximum RAM any WordPress instance can have on their installs.

And I checked the footer.php file but no wc references there - attached for confirmation.

**Comment by randayousef** [comment]
Not sure if this screenshot from the WooCommerce status page is helpful as well - attached.
![woocommerce_errors](https://user-images.githubusercontent.com/33304883/32336029-95b7f112-bfc4-11e7-8fcb-7119aa036b12.png)

**Comment by mikejolley** [comment]
The `if(is_product()){` call in there will break when WooCommerce is deactivated.
