### ISSUE TITLE
Issue fetching price with/without tax

### ISSUE THREAD

**Issue by lvl99** [woocommerce/woocommerce#17519]
I'm attempting to write a filter that modifies the price suffix depending on if the viewing user is in a taxable zone (i.e. saying if the price is with or without tax). This should work for all types of products (I'm testing with variable products which have no price ranges, i.e. all variations are the same price):

```php
  /**
   * Show "incl./excl. VAT" label for taxable prices
   *
   * @param string $html
   * @param \WC_Product $wc_product
   * @param string $price
   * @param number $qty
   * @return string
   */
  function add_tax_labels_to_price ( $html, $wc_product, $price, $qty )
  {
    if ( wc_tax_enabled() && 'taxable' === $wc_product->get_tax_status() )
    {
      if ( '' === $price ) {
        $price = $wc_product->get_price();
      }
      $price = floatval( $price );
      $price_incl_tax = wc_get_price_including_tax( $wc_product, array( 'qty' => $qty, 'price' => $price ) );
      $price_excl_tax = wc_get_price_excluding_tax( $wc_product, array( 'qty' => $qty, 'price' => $price ) );

      // Since all prices are including tax already, I've made it so the message only shows when it's excluded
      if ( $price >= $price_excl_tax )
      {
        $suffix = ''; // _x( '(incl. %s)', 'Price suffix: including Tax/VAT', 'mywebsite' );
      }
      else
      {
        $suffix = _x( '(excl. %s)', 'Price suffix: excluding Tax/VAT', 'mywebsite' );
      }

      // Add the tax/VAT abbr.
      $suffix = sprintf( $suffix, WC()->countries->tax_or_vat() );

      if ( ! empty( $suffix ) )
      {
        $html = ' <small class="price-suffix">' . wp_kses_post( $suffix ) . '</small>';
      }
      else
      {
        $html = '';
      }
    }

    return $html;
  }
  add_filter( 'woocommerce_get_price_suffix', __NAMESPACE__ . '\\add_tax_labels_to_price', PHP_INT_MAX, 4 );
```

I'm finding that both the prices with/without tax are the same (this is after clearing the transients). My viewing user has a billing and shipping address set to a country outside the taxable zones, and all prices are entered inclusive of tax in the store. The default is to show prices with tax, using the store's location (within one of the taxable zones) as the tax base, unless the viewing user has a shipping address filled in.

I originally had only two tax rates but have now updated it to a full EU VAT standard rates table here: https://gist.github.com/lvl99/2c843df32b9ce3c7fe9a5f40439adb4f

The test product should have value of 500 incl. VAT and 416.67 excl. VAT (using FR address with tax rate of 20%, and US address when outside EU taxable zone).

The behaviour I expected is that the `wc_get_price_including_tax` and `wc_get_price_excluding_tax` would do as function names claim. It seems `wc_get_price_excluding_tax` works OK but `wc_get_price_including_tax` seems to be location-aware and returns a price excluding tax if the viewing user is outside the taxable zone (regarding return values: `wc_get_price_excluding_tax` returns 416.6667 🤘, whereas `wc_get_price_including_tax` returns 416.67).

I've tested when the viewing user is within a taxable zone that `wc_get_price_including_tax` works correctly (I get a value of 500) and `wc_get_price_excluding_tax` returns the same value as above (416.6667 🤘).

Here's debug results with viewing user outside taxable zone:
![image](https://user-images.githubusercontent.com/238480/32320819-50111238-bfbf-11e7-8a05-f67b2954094e.png)

And here's debug results with viewing user inside taxable zone:
![image](https://user-images.githubusercontent.com/238480/32320662-d52ba1d2-bfbe-11e7-83b8-a10a7c4f17ed.png)

One hackish workaround I did was to modify the expression checking the price, as I noticed that the `$price` value that flows through the `woocommerce_get_price_suffix` filter is the full original price of the product (in my shop's case including tax) regardless of taxable zone (e.g. 500), but this is not the actual price value which is being outputted via the `get_price_html` function (the value is both 500 when viewing as user in FR and in US). Since `wc_get_price_including_tax` is location-aware (as in, it seems to get the price value which is affected by if the user is in/out of the taxable zone) and `$wc_product->get_price()` gets the raw price value, I can make a not-so-great-but-works-ok assumption that the value returned by `wc_get_price_including_tax` will be representative of the output price and adjust the suffix message to be relative to that:

```php
/**
 * Show "incl./excl. VAT" label for taxable prices
 *
 * @param string $html
 * @param \WC_Product $wc_product
 * @param string $price
 * @param number $qty
 * @return string
 */
function add_tax_labels_to_price ( $html, $wc_product, $price, $qty )
{
  if ( wc_tax_enabled() && 'taxable' === $wc_product->get_tax_status() )
  {
    if ( '' === $price )
    {
      $price = $wc_product->get_price();
    }
    $price = floatval( $price );
    $price_incl_tax = wc_get_price_including_tax( $wc_product, array( 'qty' => $qty, 'price' => $price ) );
    $price_excl_tax = wc_get_price_excluding_tax( $wc_product, array( 'qty' => $qty, 'price' => $price ) );

    // Modified this check to rely on difference between location-aware $price_incl_tax vs raw unfiltered $price
    if ( $price_incl_tax < $price )
    {
      $suffix = _x( '(excl. %s)', 'Price suffix: excluding Tax/VAT', 'mywebsite' );
    }
    else
    {
      $suffix = ''; // _x( '(incl. %s)', 'Price suffix: including Tax/VAT', 'mywebsite' );
    }

    if ( ! empty( $suffix ) )
    {
      // Add the tax/VAT abbr.
      $suffix = sprintf( $suffix, WC()->countries->tax_or_vat() );
      $html = ' <small class="price-suffix">' . wp_kses_post( $suffix ) . '</small>';
    }
    else
    {
      $html = '';
    }
  }

  return $html;
}
add_filter( 'woocommerce_get_price_suffix', __NAMESPACE__ . '\\add_tax_labels_to_price', PHP_INT_MAX, 4 );
```

So I'm assuming that `wc_get_price_including_tax` is not working correctly? Am I wrong to assume that it should always produce the price of the product including tax? Looking at the function now it seems that it specifically removes the tax from the price if the viewing user is outside the taxable zones. Isn't that misleading?

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set up shop tax config to enter prices including tax and to show prices including tax
2. Set up shop tax rates as per https://gist.github.com/lvl99/2c843df32b9ce3c7fe9a5f40439adb4f
3. Incorporate `add_tax_labels_to_price` function into theme (be aware that I use namespaces, maybe you don't)
4. Create a variable product with one variation priced at 500
5. Modify viewing user billing/shipping address to be outside taxable zone (e.g. US)
6. View product price (should be "416.67 (excl. VAT)")
7. Modify viewing user billing/shipping address to be inside taxable zone (e.g. FR)
8. View product price (should be 500)

## Expected/actual behavior

* When I use `wc_get_price_including_tax` it should give me the price of the product including tax, regardless of the viewing user's location.
* When I use the filter `woocommerce_get_price_suffix` I expect the `$price` being fed through to be the price which is being displayed, i.e. the output price in `get_price_html`

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Not added due to confidential info
```
</details>

**Comment by mikejolley** [comment]
Before diving in, I will just say changing any of the logic in these methods would be a huge backwards incompatibility break so we're unlikely to change how these methods act :)

> wc_get_price_including_tax seems to be location-aware and returns a price excluding tax if the viewing user is outside the taxable zone

This is correct. Including tax **based on the current taxable location**. This is dependent on the current user - have they added an address yet? What is the default customer address in settings? Geolocation data?

By default, if outside of the base location, base taxes are removed, and 'local' (to the customer) taxes are added as outlined in https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce

This is so prices in the store can be shown relevant to the actual customer viewing them. 

So to address your expectations:

> When I use wc_get_price_including_tax it should give me the price of the product including tax, regardless of the viewing user's location.

This is not how this particular method works. It's not a bug. If you want the price including tax you can do it conditionally based on price includes tax setting, and look at either the price as stored in the DB, or do a calculation using the store base address.

> When I use the filter woocommerce_get_price_suffix I expect the $price being fed through to be the price which is being displayed, i.e. the output price in get_price_html

This is not how this filter works, it gives you the actual product price as input in the backend. What is done with that is up to you. In this particular function, it does the inc/ex calculations inline:

```
$replacements = array(
				'{price_including_tax}' => wc_price( wc_get_price_including_tax( $this, array( 'qty' => $qty, 'price' => $price ) ) ),
				'{price_excluding_tax}' => wc_price( wc_get_price_excluding_tax( $this, array( 'qty' => $qty, 'price' => $price ) ) ),
			);
```

If those methods need additional documentation inline, please let me know or raise a PR.

Thanks
