### ISSUE TITLE
In the cart, the dot marking the selected shipping method disappears

### ISSUE THREAD

**Issue by yaronzak** [woocommerce/woocommerce#17528]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by yaronzak** [comment]
![image](https://user-images.githubusercontent.com/25738592/32337337-6339f024-bffa-11e7-9f64-03b1f806b670.png)

**Comment by mikejolley** [comment]
As instructed in the new issue form, you need to rule out conflicts with theme + plugins. I've just tested this, with RTL enabled, and had no such problem:

![cart local wordpress dev 2017-11-02 16-48-07](https://user-images.githubusercontent.com/90977/32338789-b4e49e90-bfed-11e7-902c-fa4fd082fd7d.png)

Thanks

**Comment by yaronzak** [comment]
OK,
I changed the theme to: storefront
I changed the language to english (ltr) 
I deactivate all the plugins.
and this problem remains.

![image](https://user-images.githubusercontent.com/25738592/32350347-cd12d862-c022-11e7-848c-0102cbe18f41.png)

**Comment by mikejolley** [comment]
Need a screenshot of your shipping zones/rates. I just tried again with UTF characters to rule those out and they are fine also.

**Comment by yaronzak** [comment]
OK, resolved,
The cause was the pluging : Beautiful permalink
