### ISSUE TITLE
Woocommerce additional variation images error

### ISSUE THREAD

**Issue by abelchanhp** [woocommerce/woocommerce#17531]
Hi,

I'm having some issues with my website. The image gallery for variable products keep displaying vertically(literally). Instead of a big image, followed by many smaller images. 

https://www.dropbox.com/s/ylqg86o9p2wu0su/error.png?dl=0

I'm currently using Oceanwp theme, with lingirie demo template. I have woocommerce additional variation image plugins.

**Comment by mikejolley** [comment]
The theme either does not support, or has no styling for the gallery. We cannot fix this our side - it's a theme issue. See if it has updates with support, or consider switching.

Thanks

**Comment by ashique-hussain** [comment]
I have the issue with variation image zooming. When I hover on feature image it's zooming well but when I select another image and then I move the mouse over the image I am seeing zoom in and zoom out ideally it should not.  I added this in my function for zoom as after installing wocommerce additional variation image plugin.
add_action( 'after_setup_theme', 'fitsparetheme_setup' );

function fitsparetheme_setup() {
    add_theme_support( 'wc-product-gallery-zoom' );
    add_theme_support( 'wc-product-gallery-lightbox' );
   add_theme_support( 'wc-product-gallery-slider' );
}
