### ISSUE TITLE
Issue with data-options on latest WooCommerce version

### ISSUE THREAD

**Issue by jchrislemmer** [woocommerce/woocommerce#17537]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Scenario 1:
1. Activate WooCommerce Plugin.
2. Add a video using the WordPress video video. Add the video in any widget area. The video must be on a WooCommerce system page. Example: Category or Store page. It doesn't happen on the checkout or cart pages where the shortcodes are used.
3. Load the page and see what happens to the video widget.

Scenario2:
1. Activate WooCommerce Plugin.
2. Install https://wordpress.org/plugins/instagram-feed/
3. Add this shortcode to the store page: [instagram-feed type="hashtag" hashtag="#themattresswarehouse"]
4. Load the page and see. The feed never loads.
5. Add this same shortcode to any other pages. You'll see it loads. This happens because the data-options are removed as explained below.

I have the same problem with the https://wordpress.org/plugins/instagram-feed/ plugin on a page. When I try and use this plugin on the store or category pages, WooCommerce removes the **data-options** from the DIV.

The data options to load the feed should be:

data-options="{"showcaption": "1", "captionlength": "50", "captioncolor": "", "captionsize": "13", "showlikes": "1", "likescolor": "", "likessize": "13", "sortby": "none", "hashtag": "themattresswarehouse", "type": "hashtag", "hovercolor": "0,0,0", "hovertextcolor": "0,0,0", "hoverdisplay": "username,icon,date,instagram,", "hovereffect": "fade", "headercolor": "", "headerprimarycolor": "517fa4", "headersecondarycolor": "eeeeee", "disablelightbox": "false", "captionlinks": "false", "disablecache": "false", "location": "", "coordinates": "", "single": "", "nummobile": "20", "colsmobile": "auto",  "lightboxcomments": "true","numcomments": "20","maxrequests": "5", "headerstyle": "circle", "showfollowers": "true", "showbio": "true", "carousel": "[false, false, true, false, 5000]", "imagepadding": "5", "imagepaddingunit": "px", "media": "all", "showusers": "", "includewords": "", "excludewords": "", "sbiCacheExists": "true", "sbiHeaderCache": "false", "sbiWhiteList": "", "sbiWhiteListIds": ""}"

However, on the "Store" or "Category" pages for WooCommerce, it gets removed. This only happened with the latest version of WooCommerce.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://www.themattresswarehouse.co.za
Site URL: https://www.themattresswarehouse.co.za
WC Version: 3.2.2
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_ZA

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.10
PHP Post Max Size: 32 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.29.0
NSS/3.28.4

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.2
WC Database Prefix: tmw_web_
MaxMind GeoIP Database: ✔
Total Database Size: 175.41MB
Database Data Size: 111.11MB
Database Index Size: 64.30MB
tmw_web_woocommerce_sessions: Data: 7.02MB + Index: 0.02MB
tmw_web_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
tmw_web_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
tmw_web_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
tmw_web_woocommerce_order_items: Data: 1.52MB + Index: 0.28MB
tmw_web_woocommerce_order_itemmeta: Data: 4.52MB + Index: 6.03MB
tmw_web_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
tmw_web_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
tmw_web_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
tmw_web_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
tmw_web_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
tmw_web_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
tmw_web_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
tmw_web_woocommerce_log: Data: 0.02MB + Index: 0.02MB
tmw_web_aiowps_events: Data: 0.02MB + Index: 0.00MB
tmw_web_aiowps_failed_logins: Data: 0.02MB + Index: 0.00MB
tmw_web_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB
tmw_web_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB
tmw_web_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB
tmw_web_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB
tmw_web_commentmeta: Data: 0.02MB + Index: 0.03MB
tmw_web_comments: Data: 3.52MB + Index: 2.11MB
tmw_web_gglcptch_whitelist: Data: 0.02MB + Index: 0.00MB
tmw_web_links: Data: 0.02MB + Index: 0.02MB
tmw_web_options: Data: 11.17MB + Index: 0.09MB
tmw_web_plugin_logic: Data: 0.02MB + Index: 0.00MB
tmw_web_postmeta: Data: 57.59MB + Index: 42.16MB
tmw_web_posts: Data: 16.52MB + Index: 4.88MB
tmw_web_redirection_404: Data: 1.02MB + Index: 0.55MB
tmw_web_redirection_groups: Data: 0.02MB + Index: 0.03MB
tmw_web_redirection_items: Data: 0.02MB + Index: 0.08MB
tmw_web_redirection_logs: Data: 0.02MB + Index: 0.08MB
tmw_web_revslider_css: Data: 0.02MB + Index: 0.00MB
tmw_web_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
tmw_web_revslider_navigations: Data: 0.02MB + Index: 0.00MB
tmw_web_revslider_sliders: Data: 0.02MB + Index: 0.00MB
tmw_web_revslider_slides: Data: 0.02MB + Index: 0.00MB
tmw_web_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
tmw_web_termmeta: Data: 0.08MB + Index: 0.09MB
tmw_web_terms: Data: 0.19MB + Index: 0.25MB
tmw_web_term_relationships: Data: 1.52MB + Index: 1.52MB
tmw_web_term_taxonomy: Data: 0.38MB + Index: 0.20MB
tmw_web_usermeta: Data: 2.52MB + Index: 5.03MB
tmw_web_users: Data: 0.16MB + Index: 0.16MB
tmw_web_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
tmw_web_woocommerce_gpf_google_taxonomy: Data: 2.02MB + Index: 0.00MB
tmw_web_woocommerce_termmeta: Data: 0.13MB + Index: 0.09MB
tmw_web_wrd_discounts: Data: 0.02MB + Index: 0.02MB
tmw_web_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB
tmw_web_wsal_metadata: Data: 0.02MB + Index: 0.02MB
tmw_web_wsal_occurrences: Data: 0.02MB + Index: 0.02MB
tmw_web_wsal_options: Data: 0.02MB + Index: 0.00MB
tmw_web_yith_ywrac_email_log: Data: 0.02MB + Index: 0.00MB
tmw_web_yoast_seo_links: Data: 0.36MB + Index: 0.14MB
tmw_web_yoast_seo_meta: Data: 0.13MB + Index: 0.00MB

### Post Type Counts ###

attachment: 7489
customize_changeset: 10
display_type: 7
gal_display_source: 5
lightbox_library: 7
nav_menu_item: 121
page: 59
post: 183
product: 2000
product_variation: 1722
revision: 294
shop_coupon: 57
shop_order: 3794
ttshowcase: 40
wc_product_tab: 1066
wpcf7_contact_form: 5
ywrac_cart: 18
ywrac_email: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

Accelerated Mobile Pages: by Ahmed Kaludi
Mohammed Kaludi – 0.9.66.1

AddToAny Share Buttons: by AddToAny – 1.7.21
Akismet Anti-Spam: by Automattic – 4.0
All In One WP Security: by Tips and Tricks HQ
Peter
Ruhul
Ivy – 4.2.9

Append extensions on Pages: by Suresh Kumar Mukhiya – 1.1.2
Contact Form 7: by Takayuki Miyoshi – 4.9.1
Crazy Egg: by Crazy Egg – 2.0
Email Notifications for WP Security Audit Log: by WP White Security – 2.2.1
External DB for WP Security Audit Log: by WP White Security – 1.2.0
Facebook Auto Publish: by xyzscripts.com – 1.4.4
Facebook Reviews Pro: by RichPlugins  – 1.2
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.1.2.2
Google Authenticator: by Henrik Schack – 0.48
Google Captcha (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.32
Instagram Feed Pro Personal: by Smash Balloon – 2.8.1
WooCommerce Search Plugin by Instant Search +: by WooCommerce Search by Fast Simon Inc – 1.9.12 – Not tested with the active version of WooCommerce
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.2
Max Mega Menu: by Tom Hemsley – 2.4
PixelYourSite PRO: by PixelYourSite – 6.3.4 – Not tested with the active version of WooCommerce
Plugin Logic: by simon_h – 1.0.7
Post Ratings: by dFactory – 3.0
Product Catalog Feed by PixelYourSite: by PixelYourSite – 1.0.4 – Not tested with the active version of WooCommerce
Redirection: by John Godley – 2.8.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
Reports for WP Security Audit Log: by WP White Security – 2.1.2
Search for WP Security Audit Log: by WP White Security – 2.0.1
ShoppingFeeder: by ShoppingFeeder – 1.1.6 – Not tested with the active version of WooCommerce
Shortcode Pagination for WooCommerce: by James Kemp – 1.0.7 – Not tested with the active version of WooCommerce
TablePress: by Tobias Bäthge – 1.8.1
User Role Editor: by Vladimir Garagulya – 4.36.1
Users Sessions Management for WP Security Audit Log: by WP White Security – 1.0.6
WooCommerce Virtual Card Services Gateway: by WooCommerce – 1.1.8 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.5 – Not tested with the active version of WooCommerce
WooCommerce AdWords Dynamic Remarketing: by Wolf+Bär Agency – 1.4.5 – Not tested with the active version of WooCommerce
WooCommerce Pre-Orders: by WooCommerce – 1.5.4 – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Lee Willis – 7.3.0 – Not tested with the active version of WooCommerce
WooCommerce Product Reviews Pro: by SkyVerge – 1.8.1 – Not tested with the active version of WooCommerce
WooCommerce Review for Discount: by WooCommerce – 1.6.4 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.3 – Not tested with the active version of WooCommerce
WooCommerce Social Login: by SkyVerge – 2.3.2 – Not tested with the active version of WooCommerce
WooCommerce Subscribe to Newsletter: by WooCommerce – 2.3.10 – Not tested with the active version of WooCommerce
WooCommerce Tab Manager: by SkyVerge – 1.8.4 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.2
Yoast SEO Premium: by Team Yoast – 5.7.1
WP Security Audit Log: by WP White Security – 2.6.8
WP Super Cache: by Automattic – 1.5.7.1
YITH WooCommerce Recover Abandoned Cart Premium: by YITHEMES – 1.1.8 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-4 (rated-4)
rated-5 (rated-5)
rated-5 (rated-5-2)

### WC Pages ###

Shop base: #14 - /
Basket: #90 - /cart.html
Checkout: #92 - /checkout.html
My account: #94 - /my-account.html
Terms and conditions: ❌ Page not set

### Theme ###

Name: TheMattressWarehouse Child
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Seller
Parent Theme Version: 1.2.1
Parent Theme Author URL: http://rohitink.com
WooCommerce Support: ✔

### Templates ###

Overrides: tmw_theme/woocommerce/archive-product.php
tmw_child_theme/woocommerce/checkout/form-checkout.php
tmw_theme/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
tmw_child_theme/woocommerce/emails/customer-on-hold-order.php
tmw_child_theme/woocommerce/emails/customer-processing-order.php
tmw_child_theme/woocommerce/order/order-details.php version 3.0.0 is out of date. The core version is 3.2.0
tmw_child_theme/woocommerce/single-product/price.php
tmw_theme/woocommerce/single-product/tabs/description.php
tmw_theme/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update

### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Brand: 
Manufacturer Part Number (MPN): 
Product Type: 
Google Product Category: 
Size system: 

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: No
`
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17499
