### ISSUE TITLE
Bug with GeoIP class when GeoIP.dat is empty

### ISSUE THREAD

**Issue by r007** [woocommerce/woocommerce#17539]
Hello,

Here's my local dev host, I have installed:
- **Ubuntu** 17.10
- **Apache** 2.4.27
- **PHP** 7.1.8
- **WordPress** 4.8.3 without populated data (a brand new installation)
- **Storefront** 2.2.5 (latest from Wordpress.org repository)
- **WooCommerce** 3.3-dev (latest from `master branch`, only one plugin active)

**WP DEBUG** - enabled.

When I open the main page, I see this:

![notices](https://user-images.githubusercontent.com/78280/32356889-3aaf97ea-c049-11e7-8004-69116d69c60a.png)

These notices are being showed on all pages. Also, when I am trying to log out, I see this:

![logout](https://user-images.githubusercontent.com/78280/32357037-2eafb910-c04a-11e7-8c4a-4ed9f1ab318b.png)

After log out it's impossible to log in again, because it throws warnings **Cannot modify header information - headers already sent by**.

![login](https://user-images.githubusercontent.com/78280/32357209-b4ffc162-c04b-11e7-8eee-e8f94da2d5cd.png)

So every time when it happens, I have to rename **woocommerce** folder to something else. After deactivation of plugin all the notices and warnings disappear and I can log in and log out freely.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an empty GeoIP.dat in ``wp-content/uploads``

## Expected/actual behavior

I was expecting to see clear page, but instead I see these notices:

**Notice: Uninitialized string offset: 0 in /var/www/html/wordpress/wp-content/plugins/woocommerce/includes/class-wc-geo-ip.php on line 1592**

**Notice: Uninitialized string offset: 1 in /var/www/html/wordpress/wp-content/plugins/woocommerce/includes/class-wc-geo-ip.php on line 1592**

**Notice: Uninitialized string offset: 2 in /var/www/html/wordpress/wp-content/plugins/woocommerce/includes/class-wc-geo-ip.php on line 1592**

**Notice: Uninitialized string offset: 3 in /var/www/html/wordpress/wp-content/plugins/woocommerce/includes/class-wc-geo-ip.php on line 1592**

**Notice: Uninitialized string offset: 4 in /var/www/html/wordpress/wp-content/plugins/woocommerce/includes/class-wc-geo-ip.php on line 1592**

Line 1592 itself:

```php
$x[ $i ] += ord( $buf[ $this->record_length * $i + $j ] ) << ( $j * 8 );
```

The ``$buf`` variable is empty, var_dump shows ``string(0) ""``. It seems like the GeoIP database has not been read, that's why string offset on buffer shows a warning. Code just before the problematic loop:

```php
// Reading of the database
if ( $this->flags & self::GEOIP_MEMORY_CACHE ) {
    // Skipped...
} elseif ( $this->flags & self::GEOIP_SHARED_MEMORY ) {
    // Skipped...                                
} else {
    if ( 0 != fseek( $this->filehandle, 2 * $this->record_length * $offset, SEEK_SET ) ) {
         break;
     }

     // Empty buffer here, $this->record_length equals 3.
     $buf = fread( $this->filehandle, 2 * $this->record_length );
}
```

Filehander points to an empty file:
```php
// File name: /var/www/html/wordpress/wp-content/uploads/GeoIP.dat, file exists but it's empty
if ( $this->filehandle = fopen( $filename, 'rb' ) ) {
    // ...Reading of the GeoIP.dat goes here...
} else {
    $this->log( 'GeoIP API: Can not open ' . $filename, 'error' );
}
```

When I replace empty GeoIP database with normal file, the bug disappears.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://127.0.0.1/wordpress
Site URL: http://127.0.0.1/wordpress
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.27 (Ubuntu)
PHP Version: 7.1.8-1ubuntu1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: 5.7.20
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 1.49MB
Database Data Size: 0.70MB
Database Index Size: 0.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.20MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

customize_changeset: 1
page: 7
post: 2
product: 1
revision: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: RUB (₽)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /index.php/shop/
Cart: #5 - /index.php/cart/
Checkout: #6 - /index.php/checkout/
My account: #7 - /index.php/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17541
