### ISSUE TITLE
Woocommerce reports "Taxes by date" doubles "Number of orders"

### ISSUE THREAD

**Issue by Gerardino42** [woocommerce/woocommerce#17544]
Hi,

I just stumbled upon the following issue.
When viewing the Woocommerce reports tab, I go to "Taxes by date" and the "Number of orders" has doubled..

The rest of the information on this page (Total sales - Total shipping - Total tax - Net profit) is correct, but only the amount of order number has doubled so my tax reports are now a mess.

Is this a current bug?
When will this be solved?

Kind regards, Gerardino

**Comment by mikejolley** [comment]
Are you going to include status report etc as requested?

**Comment by Gerardino42** [comment]
The status report contains a lot of privacy sensitive information for me to just upload it here on the internet.

For your information, I'm using WC version 3.2.3 with WP 4.8.3.

The information used to be correct in these tax overviews, but today I noticed this issue.
So I'm wondering if this is a know issue of if you're able to somehow reproduce this issue?

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/17590
