### ISSUE TITLE
Update broke State field in checkout

### ISSUE THREAD

**Issue by thecolorbreak** [woocommerce/woocommerce#17545]
After updating to the latest version of WooCommerce the State field is now broken in checkout. When you open the dropdown it just says "Array" over & over again. This is an issue because sales tax & shipping are no longer calculated. Please help!

**Comment by mikejolley** [comment]
Without a link and the status report we can do nothing. The state field has not been changed afaik. Don't know what version you were on prior.

**Comment by thecolorbreak** [comment]
I have been updating regularly, so I was on the previous version, updating to the most recent this morning. Here is a screenshot: http://www.thecolorbreak.com/wp-content/uploads/2017/11/Capture.jpg

**Comment by claudiulodro** [comment]
Seems to be coming from the PHP side:
`
<select name="billing_state" id="billing_state" class="state_select " autocomplete="address-level1" placeholder="">
  | <option value="">Select a state&hellip;</option><option value="AF" >Array</option><option value="AT" >Array</option><option value="AX" >Array</option><option value="BE" >Array</option><option value="BI" >Array</option><option value="CZ" >Array</option><option value="DE" >Array</option><option value="DK" >Array</option><option value="EE" >Array</option><option value="FI" >Array</option><option value="FR" >Array</option><option value="GP" >Array</option><option value="GF" >Array</option><option value="IS" >Array</option><option value="IL" >Array</option><option value="KR" >Array</option><option value="KW" >Array</option><option value="LB" >Array</option><option value="MQ" >Array</option><option value="NL" >Array</option><option value="NO" >Array</option><option value="PL" >Array</option><option value="PT" >Array</option><option value="RE" >Array</option><option value="SG" >Array</option><option value="SK" >Array</option><option value="SI" >Array</option><option value="LK" >Array</option><option value="SE" >Array</option><option value="VN" >Array</option><option value="YT" >Array</option><option value="US" >Array</option></select>
`

**Comment by mikejolley** [comment]
I'd bet something else is filtering the state names for it only to affect one person.

**Comment by thecolorbreak** [comment]
Any ideas how to fix this? I am not a coding wiz, so I would need kind of dumbed down speech, but I do know how to edit current files if I know the steps to do it without screwing something else up. I restored to a backup & it was still doing it, so now I'm starting to wonder if it may actually be something with the newest wordpress update...

**Comment by mikejolley** [comment]
I think you'll find its another plugin you have installed. State names can be changed in the code. Rule them out?

**Comment by thecolorbreak** [comment]
That's what I thought, so I restored all of my plugins to their previous versions & it is still happening. This is why I worry that it may be wordpress itself.

**Comment by thecolorbreak** [comment]
@claudiulodro where did you find this php? I cannot locate it in any of the files I have access to

**Comment by claudiulodro** [comment]
It's in the HTML source of http://www.thecolorbreak.com/checkout/ . You can right-click on the page and select "View Page Source" to see the source for the page.

**Comment by thecolorbreak** [comment]
@claudiulodro thank you I've found it; any thoughts on what might be causing this? I tried adding this snippet from https://www.xadapter.com/woocommerce-change-the-default-country-and-state-on-checkout-page-set-empty/ at another person's recommendation to force a state into the field, and it does work & the dropdown is then showing correctly with the states, except that it's then saying "there are no shipping methods available" when there definitely are & it was calculating shipping a couple days ago

**Comment by mikejolley** [comment]
> That's what I thought, so I restored all of my plugins to their previous versions & it is still happening. This is why I worry that it may be wordpress itself.

Rather than restore, since you don't know when the problem occurred or what caused it, **perform the isolation steps we outline on the new issue form.**

```
- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
```

I'm confident as soon as you take the time to do this, you'll find the conflict. No other users have experienced anything like this issue.

**Comment by thecolorbreak** [comment]
I just figured it out, so for anyone who has this issue in the future, it is because in the WooCheckout - Billing & Shipping sections I had the Country fields removed.
