### ISSUE TITLE
Update Belarusian ruble from BYR to BYN

### ISSUE THREAD

**Issue by danjjohnson** [woocommerce/woocommerce#17552]
Since December 2016, the ISO code for Belarusian rubles should be BYN, not BYR

https://github.com/woocommerce/woocommerce/blob/787bb7f0c0fead3a6fe8f67b60261bebe20a2803/includes/wc-core-functions.php#L318

See: https://en.wikipedia.org/wiki/Belarusian_ruble#Third_ruble.2C_2016_-_present

Reported in 769582-zen

**Comment by MounirHamani** [comment]
Should the new currency code be introduced and the old one removed in a futur version or should it just be a replacement ?

**Comment by claudiosanches** [comment]
@MounirHamani need to replace the old one and create a upgrade script to update all database too.

Here an exemple of upgrade script: https://github.com/woocommerce/woocommerce/blob/eb594b05efbaadae46372bb6f86a405f3b7aa096/includes/wc-update-functions.php#L956-L981

**Comment by MounirHamani** [comment]
@claudiosanches According to the Wiki article, 1 BYN = 10,000 BYR, and some websites might have their prices still in the old currency, so I'm not sure that just replacing the currency code is good enough.

**Comment by claudiosanches** [comment]
@MounirHamani ohhhh, so yeah, probably better include as a new currency

**Comment by MounirHamani** [comment]
@claudiosanches 
Okay.
Also, what do you think about an admin notice telling those who have BYR as currency to update it to the new one and update their prices ?

And regarding this notice, should it be dismissable or non-dismissable ? And in which file should it be added ?

If you think that a notice is not needed, you can ignore my last two questions.

**Comment by claudiosanches** [comment]
I don't think that a notice should be a good idea, we already trying to get off a lot of admin notices.

**Comment by iamgabrielma** [comment]
I'm re-opening this as the currency selection does not shows BYN but BR ( the selection is only between `br(old)` and 'br`)

<img width="780" alt="Screen Shot 2019-08-17 at 16 23 12" src="https://user-images.githubusercontent.com/3812076/63209524-2e2d4d80-c10c-11e9-83e9-fdfa314f9889.png">

I understand from https://github.com/woocommerce/woocommerce/blob/d33505b33ae710d076e76aa84cc3ebfd6334fc4c/includes/wc-core-functions.php#L358 that this should be shown, but doesn't seem to be the case:

```
'BYR' => 'Belarusian ruble (old)',
'BYN' => 'Belarusian ruble',
```

Reference: 2279487-zen

**Comment by MounirHamani** [comment]
That's not a bug, it's a feature. :)

Look at the following code line to understand:
https://github.com/woocommerce/woocommerce/blob/d33505b33ae710d076e76aa84cc3ebfd6334fc4c/includes/wc-core-functions.php#L543

For example, in the case of Euro (EUR), you would have (€), and in the case of Algerian Dinar (DZD), you would have (دج). Same thing for Belarusian ruble (BYN or BYR), you will have (Br).

It's just the human readable form.

**Comment by iamgabrielma** [comment]
Thanks for the clarification @MounirHamani  , I understand that in this case if somebody wants to change the output (from `br` to `BYR`) should apply a filter like this one: https://gist.github.com/woogists/326d883e678ac8d15e3dbfef84ca1389#file-wc-change-currency-symbol-php

Is that correct?

**Comment by kloon** [comment]
@iamgabrielma that is correct, you can use that gist and just target BYR instead of AUD as in the code.
