### ISSUE TITLE
Expired coupons stuck in cart when coupon functionality is disabled

### ISSUE THREAD

**Issue by MindyPostoff** [woocommerce/woocommerce#17553]
## Steps to reproduce the issue

1. Create a coupon with an expiration date in the future.
2. Add the coupon to an existing cart, but don't complete the checkout process.
3. Change the expiration date of the coupon to be in the past.
4. Disable coupons in Checkout > Settings.
5. Refresh your cart page. 

## Expected/actual behavior

When I follow those steps, I see that the coupon is now invalid, but since the coupon functionality is disabled, it's not possible to remove the coupon from the cart. Even if there is no expiration date for the coupon, or it expires in the future, I'm unable to remove the coupon from the cart. 

![see screen shot](http://cld.wthms.co/8BB9oM+)

I was expecting to see that the invalid coupon is successfully removed, based on the fact that coupon functionality is now disabled. 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by claudiulodro** [comment]
While this is a bug, has it ever happened to a customer in the wild? :)

**Comment by MindyPostoff** [comment]
Yes, reported in 770076-zen
