### ISSUE TITLE
A way to upload an image file to the product by api

### ISSUE THREAD

**Issue by renan-acmix** [woocommerce/woocommerce#17556]
HI,
I have not found a way to send an image of the product through the api, in addition to a URL. I would like to upload a local file. It can be an array of bytes, a base64 string, or otherwise, which does not have to load the file into a URL before sending it to the API

Thanks.

**Comment by mikejolley** [comment]
Uploading to the media library is not part of our API, but WordPress' REST API.

See:

http://v2.wp-api.org/reference/media/
https://github.com/WP-API/WP-API/issues/1768
https://www.wpsaga.info/wp-rest-api-upload-image-media/

Thanks

**Comment by renan-acmix** [comment]
@mikejolley 

Oww, thank you very mutch.

**Comment by steffanhalv** [comment]
Please note that this requires additional authentication through nonces or to install another plugin as JWT Authentication.

This functionality is not available with authorization from WooCommerce API, so in case you only have authorization through WC Api and not WP Api sideupload through url is currently the only option.

**Comment by haseebmukhtar** [comment]
Hi
For same issue, I used FTP, upload image from local machine to ftp site.  You can use public ftp or image hosting service, just need to upload image temp.

I used FluentFTP to upload image to ftp site in C#.

Once the image is uploaded you can use product.images.add(new ProductImage(){ src = [FTP PATH]})
or
               **_ProductImage image = new ProductImage();
               image.src = [Image web path];

              product.images.add(image);_**

When woocommerce api adding image on a product, it will automatically add a copy of image in media (in wp upload dir).

Thanks

**Comment by rickdroio** [comment]
> Once the image is uploaded you can use product.images.add(new ProductImage(){ src = [FTP PATH]})

currently this is best solution I have found to upload images! thanks
