### ISSUE TITLE
Grouped products not importing properly

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#17558]
If Simple products are imported with the `Parent` column set for a Grouped product's SKU (and assumed ID), the Simple product is not properly linked as part of the Grouped product. 

## Steps to reproduce the issue

1. Import: [wc-product-import-2017-11-03.csv.zip](https://github.com/woocommerce/woocommerce/files/1442345/wc-product-import-2017-11-03.csv.zip)
2. View the product listing and the Simple products will appear linked to the Grouped product.
3. Edit the Grouped product and the Simple products are not listed in Grouped products under Linked Products.

![](http://cld.wthms.co/PXvADl+)
Image Link: http://cld.wthms.co/PXvADl

![](http://cld.wthms.co/Y19EbX+)
Image Link: http://cld.wthms.co/Y19EbX

## Expected/actual behavior

Would have expected this to link the Simple products to the Grouped products.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

```

### WordPress Environment ###

Home URL: http://importer.dev
Site URL: http://importer.dev
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.13
PHP Version: 7.0.17-3+deb.sury.org~trusty+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.73MB
Database Data Size: 0.94MB
Database Index Size: 0.79MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.44MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 9
page: 5
post: 2
product: 3

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.2.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
@jessepearson If we are documenting somewhere that setting 'parent' is how to import grouped products, this needs re-writing. 3.0 does not use parent. There is a 'grouped product' column and it's set on the parent row.

https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

@claudiulodro

**Comment by claudiulodro** [comment]
That's what I thought, but the parent column description in the schema has: `Set parent ID. Used for simple products in a group and variations.` :)

**Comment by mikejolley** [comment]
I'll fix it 👍

**Comment by anderson-app** [comment]
Hi @mikejolley I'm having the same problem, any news on the fix?

**Comment by mikejolley** [comment]
Read the updated docs - there is nothing to fix in the code.

**Comment by boneishi** [comment]
Hi, would someone please provide a link to docs relating to importing grouped products.
From what ive read, the correct way to do it is to set up as described by Jesse at start of the thread which i am doing but am also having the same issue and theyre not importing as i would expect.

sorry im a newbie at this and would appreciate a bit of help :)

**Comment by claudiulodro** [comment]
@boneishi it seems to be missing from [the wiki document](https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema#csv-columns-and-formatting), but the correct column name is `"Grouped products"` and you can put in a comma-separated list of SKUs for the column value. See [this example](https://github.com/woocommerce/woocommerce/blob/master/tests/unit-tests/importer/sample.csv)
