### ISSUE TITLE
Discount out by 1 cent

### ISSUE THREAD

**Issue by scottalreadytaken** [woocommerce/woocommerce#17569]
Greetings, 

I’ve found a number precision error which is related to many other issues both closed and open but I couldn’t find an exact match. 
If I apply a coupon worth 24.45 to a cart with one item with a total of 19.99 the customer ends up owing 1 cent rather than 0. 
The issue appears to arise in class-wc-discounts in the method get_discounted_price_in_cents( $item ) (line 214) . 
```
public function get_discounted_price_in_cents( $item ) {
return absint( $item->price - $this->get_discount( $item->key, true ) );
}
```
The absint function turns the price 1999, which is really a double, and is something like this 1,998.99999999999977262632, into 1998. 
Which looks like this in practice:
Product/Cart price: $19.99
Discount: - $19.98
Total: $0.01
Obviously given the coupon was actually worth more than the cart it needs to be zero. 

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

**Comment by GlennMartin1** [comment]
What version of WC are you running?

**Comment by scottalreadytaken** [comment]
So in prod I'm running Version 3.2.1 in dev where I did my debugging I
pulled the latest from github yesterday.  If you have doubts about it being
in 3.2.3 I'll be using that in a few hours so I can let you know if it's
still there.

Sorry I forgot to add that to the post.

**Comment by scottalreadytaken** [comment]
More environment details:
### WordPress Environment ###

WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.22-0ubuntu0.16.04.1


### Database ###

WC Database Version: 3.2.3

In case it's important Booster for WooCommerce is also present:
Booster for WooCommerce: by Algoritmika Ltd – 3.2.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by spraveenitpro** [comment]
@mikejolley @claudiosanches  I was able to replicate this behavior:

![](http://cld.wthms.co/vq7fDQ+)
[Direct Link](http://cld.wthms.co/vq7fDQ+)

The coupon applied above is worth $20. The same issue does happen when the coupon is applied from the backend:

![](http://cld.wthms.co/UBSE8r+)
[Direct Link](http://cld.wthms.co/UBSE8r+)

zen-768336

**Comment by mikejolley** [comment]
This is fixed by and resolved in https://github.com/woocommerce/woocommerce/pull/17603
