### ISSUE TITLE
 Warning: Invalid argument supplied for foreach() in /plugins/woocommerce/includes/wc-page-functions.php on line 122

### ISSUE THREAD

**Issue by dnanasi** [woocommerce/woocommerce#17565]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Enabling the wordpress and tickera plugins causes this error in the wc plugin appearing at the top of every page on my site
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```

`
### WordPress Environment ###

Home URL: https://www.cookingwithshoshana.com
Site URL: https://www.cookingwithshoshana.com
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: wp_98jumd_
MaxMind GeoIP Database: ✔
Total Database Size: 2.67MB
Database Data Size: 1.85MB
Database Index Size: 0.82MB
wp_98jumd_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_98jumd_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_98jumd_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_98jumd_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_98jumd_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_98jumd_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_98jumd_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_98jumd_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_98jumd_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_98jumd_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_98jumd_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_98jumd_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_98jumd_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_98jumd_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_98jumd_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_98jumd_comments: Data: 0.02MB + Index: 0.09MB
wp_98jumd_links: Data: 0.02MB + Index: 0.02MB
wp_98jumd_options: Data: 1.03MB + Index: 0.02MB
wp_98jumd_postmeta: Data: 0.08MB + Index: 0.03MB
wp_98jumd_posts: Data: 0.28MB + Index: 0.06MB
wp_98jumd_termmeta: Data: 0.02MB + Index: 0.03MB
wp_98jumd_terms: Data: 0.02MB + Index: 0.03MB
wp_98jumd_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_98jumd_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_98jumd_usermeta: Data: 0.02MB + Index: 0.03MB
wp_98jumd_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

amn_wpforms-lite: 1
attachment: 14
custom_css: 1
customize_changeset: 16
et_pb_layout: 32
nav_menu_item: 6
page: 19
post: 1
revision: 47
tc_api_keys: 1
tc_templates: 1
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Tickera: by Tickera.com – 3.2.7.7
Divi Builder: by Elegant Themes – 2.0.48
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.4
WooCommerce: by Automattic – 3.2.3
WPForms Lite: by WPForms – 1.4.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #156 - /shop/
Cart: #157 - /cart/
Checkout: #158 - /checkout/
My account: #159 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi
Version: 3.0.51
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
Sounds like tickera may be filtering `wp_nav_menu_objects` and breaking something. We can workaround but the issue will be outside of WooCommerce.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17588
