### ISSUE TITLE
v3.2.3 - Variable products displaying as out of stock even when stock quantity present.

### ISSUE THREAD

**Issue by MurphSmurf** [woocommerce/woocommerce#17568]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create or import a NEW variable product. 
2. Set the stock quantity to a number other than zero.
3. Publish the product. 
4. Product appears as out of stock whereas on a scroll-down the product header up top shows the product in stock (which is correct).

![image](https://user-images.githubusercontent.com/33380943/32419277-4cdd2856-c26f-11e7-928f-9ebc079bdd7f.png)

![image](https://user-images.githubusercontent.com/33380943/32419283-5f0317de-c26f-11e7-8a35-b790b0522aaa.png)

## Expected/actual behavior

When I follow those steps, I see...
This product is out of stock
I was expecting to see...
Product in stock

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
version 4.8.3 running storefront theme WooCommerce 3.2.3
</details>

**Comment by mikejolley** [comment]
You've set stock at product level, but that message indicates no variations are available. We know this can be confusing and have separate issues logged.

Check the variations INSIDE this variable product. If they are missing PRICES, or have stock management enabled and 0 stock, this message will be shown.

Also, you should probably disable stock management at the product level. In your use case I expect the variations are stock managed, not managed as a group.

Thanks
