### ISSUE TITLE
Help wanted! Auto scroll on single product page

### ISSUE THREAD

**Issue by jac0b95** [woocommerce/woocommerce#17562]
Hi, i have a problem with auto scrolling when single product is loaded. It is scrolling to product description tabs. 

When i removed tabs from product scrolling stops, . I tried to localize script by targeting animation and scroll control in chrome console without results. Also tried to remove every custom .js code. Nothing helps. Theme is _undescore boilerplate and there is no hashtags in url.

**Comment by glorb** [comment]
@jac0b95 have you found a solution for this? I'm having the same issue.

**Comment by jac0b95** [comment]
@glorb Yes, i had issue because of JS code. In my template there was a jQuery code for menu scrolling. This code was taking #tag from url if it was set and scroll to element that had this id.

**Comment by Imtiazjaleem** [comment]
How to fix it ?

**Comment by megamediamagic** [comment]
Did you guys come up with solution for that problem, currently been having the same issue, thanks.

**Comment by plue** [comment]
A quick workaround:

```
jQuery(function($){
    $('.woocommerce-tabs').slideUp(0);
	setTimeout(function(){
		$('.woocommerce-tabs').slideDown();
	}, 1000);
});
```
