### ISSUE TITLE
get product by id

### ISSUE THREAD

**Issue by gesenlik** [woocommerce/woocommerce#17579]
Hi,

I try to get product by sku and everything ok.
![search](https://user-images.githubusercontent.com/32957634/32436654-d4b80a94-c2f5-11e7-936a-910b48a7a184.PNG)

But I try to get product by id and 
![update](https://user-images.githubusercontent.com/32957634/32436818-53265f2a-c2f6-11e7-8695-c1a0fc002c06.PNG)
what's problem?

**Comment by mikejolley** [comment]
It's a variation not a product. There is a separate endpoint for these.

**Comment by gesenlik** [comment]
Thanks mikejolley...
