### ISSUE TITLE
Shipping calculator field(s) contain backslashes after Update totals

### ISSUE THREAD

**Issue by bobbingwide** [woocommerce/woocommerce#17575]
In the Shipping calculator the `calc_shipping_state` field doesn't cater for special characters which are escaped leading to unwanted backslashes.

This problem is similar to #16872. The fix is similar.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a product to the cart 
2. View the cart 
3. Click on Calculate shipping
4. For the State / County field enter a string containing single quote, double quote or backslash e.g. Hampsh're
5. Click on Update totals
6. Click on Calculate shipping
7. Notice the State / County field now contains Hampsh\'re.
8. Repeat clicking Update Totals and Calculate shipping to watch the number of back slashes increase.

## Expected/actual behavior

When I follow those steps, I see...
Unexpected backslashes appearing.

I was expecting to see...
The string I entered.

## Problem analysis
The $_POST array contains the fields which have the unwanted backslashes. They need to be removed using stripslashes or similar. The simplest fix for this particular problem is to call stripslashes when assigning the $state field to $billing['state'] in WC_Customer::set_shipping_location.
e.g. change 
```
$shipping['state']    = $state;
```
to 
```
$shipping['state']    =  stripslashes( $state );
```

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active....
well, I'm also using a shipping plugin ( oik-weight-zone-shipping )
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
as for #17570
```
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17586
