### ISSUE TITLE
CSV export: Unique attribute columns needed

### ISSUE THREAD

**Issue by stl99** [woocommerce/woocommerce#17574]
The CSV file created by the built-in export feature creates mixed up attribute columns. Individual columns contain varying attributes depending on what's available for a product.

Example: Attribute column 1 provides the shirt size for product 1 but the mug color for product 2 in the following row.

To be really useful the exported the CSV file should provide unique columns for each attribute. If no attribute is available for a product the cell should be empty instead of filled with another attribute.

**Comment by mikejolley** [comment]
It could have been coded either way. The disadvantage in your suggestion is you get a column for every attribute, and of all products have wildly different attributes thats lots of blank column data.

Sorry, but we have no plans to change from current schema https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

**Comment by stl99** [comment]
Maybe you can add an option to use empty columns instead of mixing it up?

With the current CSV export managing the products (sorting, filtering etc.) is - depending on the goal/product portfolio - a huge effort...

**Comment by mikejolley** [comment]
Feel free to extend it if you want some other non-core handling.
