### ISSUE TITLE
Ensure order items are still stocked not valid

### ISSUE THREAD

**Issue by elnemr84** [woocommerce/woocommerce#17584]
Hi,

While I'm trying to pay an order from my-orders page, it says that the product is out of stock, it's correct its out of stock now, but when the order made there was 1 item and it's reserved for this order, so I must have the option to pay for my order as it's reserved for me, correct ?

**Comment by mikejolley** [comment]
Whilst the order is 'pending payment' status, you can pay again from the account page, and stock is held.

Once that status is removed (WC cleans these orders up periodically) the stock is freed and order cancelled.
