### ISSUE TITLE
Problem with Items and Orders with <0.0001 Value

### ISSUE THREAD

**Issue by Spikarija** [woocommerce/woocommerce#17581]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install latest version of WordPress and current WooCommerce Github master (6. Nov 2017)
2. Go through Store setup wizard (default values plus the following): Where is your store based: UK; Address: Westminster; City: London; Postcode/ZIP: SW1A 1AA; What currency do you use: Bitcoin; What type of product do you plan to sell: I plan to sell both physical and digital products; Payment wizard: Stripe disabled, Check Enabled; Shipping: Free Shipping in all zones Enabled; Extras: Storefront Theme Disabled; Activate: Skip this step; Ready!: Return to your dashboard; Go to WooCommerce->Settings and set the number of decimal places to 8 (note: wc_get_price_decimals() properly outputs 8 and wc_get_rounding_precision() outputs 10, as expected)
3. Products->Add New; create a test product valued at anything less than 0.0001, e.g. 0.00001 or 0.000002...
4. Visit Store, add the test product(s) to cart and make sure the total is less than 0.0001, go to checkout and place order; in "thank you"/order received page see unexpected values for line item(s), subtotal and order total.

![image](https://user-images.githubusercontent.com/31689626/32438802-2614e2fe-c2ec-11e7-968a-987e930adc4b.png)

## Expected/actual behavior

When I follow those steps, I see line items that were previously displayed properly on product pages and in cart/cart checkout pages get somehow converted to whole numbers, i.e. line item valued at 0.00001 becomes 1; another item valued at 0.000002 becomes 2, 0.0000001 becomes 1, 0.00000005 becomes 5; values for subtotal and order total are consequently wrong. It does not matter whether tax is turned on or off, the results are wrong in both cases.

I was expecting to see the above values being unaltered; a thing to note is that if the cart total exceeds 0.0001 there is only a visual issue, as in the order total is correct whereas the line items and subtotal may still be displayed wrong, for instance if the line item (qty*price) is less than 0.0001.

See attached picture above for two simple and reproductible scenarios.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://192.168.0.161
Site URL: http://192.168.0.161
WC Version: 3.2.0
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.24
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.75MB
Database Data Size: 0.95MB
Database Index Size: 0.80MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.45MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 1
page: 5
post: 2
product: 1
shop_order: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: BTC (฿)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 8
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/17602
