### ISSUE TITLE
Cart totals calculating on every page load, even when no cart or session

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/woocommerce#17583]
Since version 3.2 it seems that cart totals are calculated on every page load even in a totally clean session. The calculate_totals() method is being called from WC_Cart_Session::get_cart_from_session() which runs on wp_loaded. 

Sorry if this was a deliberate change, but it seems strange to me.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Do backtrace from WC_Cart::calculate_totals()
2. New private browser tab, refresh the page once or twice

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
It's called on session read, and other cart events. 

I've checked and when the cart is empty, no calculations are performed so there should be no overhead here. It just ensures any session data (0 values) are set so they are available for code reading them.

Let me know if there is a related problem - looks fine to me.

**Comment by danielbitzer** [comment]
Ok no problem. I just noticed because, after the totals are calculated, hooks are fired like 'woocommerce_cart_updated' and 'woocommerce_after_calculate_totals'. I was hooked in to woocommerce_cart_updated expecting that event to be when a cart is changed and I feel like a lot of other devs would be hooking into these two actions. Is there some another hook that we should be using?

**Comment by mikejolley** [comment]
`woocommerce_cart_updated` is updated after any session load, not on cart change.

**Comment by danielbitzer** [comment]
But in WC_Cart_Session line 50 the persistent_cart_update method is tied to the woocommerce_cart_updated action. So it seems that user meta is being updated on every page load.

**Comment by mikejolley** [comment]
You're right. However, if we did have a dedicated event for cart being updated for reals, what if a 3rd party adjusted the cart via a hook not being monitored?

**Comment by danielbitzer** [comment]
Fair enough, up to you. I just wanted to confirm that this is deliberate because in the past I have used woocommerce_cart_updated as a change event and it seemed ok, but I can work out another solution

**Comment by mikejolley** [comment]
@danielbitzer Do you know what version it was change only under? Need to look it up in code.

**Comment by danielbitzer** [comment]
I think it's 3.2, the if statement at the bottom of the `get_cart_from_session` method changed in 3.2.

**Comment by mujuonly** [comment]
> woocommerce_cart_updated  Hook is getting called on all pages if something is there on cart.
Is there any other options to restrict like screen_ids that this hook should be fired.
