### ISSUE TITLE
AJAX multiselect issue with SelectWoo

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#17592]
While adding products on orders panel which utilizes SelectWoo AJAX multiselect is being more tedious. 

I can select products from the search box but while removing one backspace hit is not enough. If I am not clear please have a time and watch this video reference.

https://cldup.com/l0E4GQMBBc.webm

- Additionally see how border suits and is tidy :)

![capture-1](https://user-images.githubusercontent.com/3774827/32453422-408fcf38-c344-11e7-8f0d-bdba327a09be.PNG)

- But while searching boder is too much :)

![capture](https://user-images.githubusercontent.com/3774827/32453437-48023e22-c344-11e7-96b7-cb873e6774b8.PNG)

CC @claudiulodro @mikejolley

**Comment by claudiulodro** [comment]
Upon further investigating, this is actually how it's supposed to work. The way it behaved in the previous version of select2 we were using (where it would delete all of the text) was actually a bug. ([ref](https://github.com/woocommerce/selectWoo/commit/395e06aff52059f654aff47f03a26cad8955a092))
