### ISSUE TITLE
"My Account" Downloads Table Needs Responsive Styles

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#17597]
On Storefront with a clean install, if you go to **My Account > Downloads** on a mobile device the downloads table is too wide and doesn't fit on the screen in Portrait mode:

![http://cld.wthms.co/yj68hb](http://cld.wthms.co/yj68hb+) 
Full Size: http://cld.wthms.co/yj68hb

Going to Landscape does fix it on an iPhone 6 equivalent:

![http://cld.wthms.co/TWiTn4](http://cld.wthms.co/TWiTn4+) 
Full Size: http://cld.wthms.co/TWiTn4

It looks like this also happens on Android - tested on Pixel 2 XL (woo!) with a 1440px portrait width, still couldn't get to the download button in portrait.

Is this something we could fix by moving away from tables and using divs or accordion boxes instead? i.e.

![http://cld.wthms.co/6Pxyle](http://cld.wthms.co/6Pxyle+) 
Full Size: http://cld.wthms.co/6Pxyle

771059-zen

**Comment by douglsmith** [comment]
This is not limited to the downloads table. It also can happen with the orders table or others added by extensions. For example, the Wishlists and Help Scout extensions also add tables to the My Account page that are affected.
