### ISSUE TITLE
having an error while clicking the place order in checkout page using woocommerces and avada theme version 4.0.2 

### ISSUE THREAD

**Issue by vigneshrvicky** [woocommerce/woocommerce#17608]
I try to order the food in my website..after completing all the procedure, when i click the "place-order"button it not moving to payment page..it stay on same page and display the following error

"SyntaxError: Unexpected token < in JSON at position 0"

And also In console tabs,i got the error
"Unable to fix malformed JSON".

Along with that in network tab i have
"?wc-ajax=update_order_review".

i attached the screenshot here
![pc](https://user-images.githubusercontent.com/33368102/32483793-76377bd4-c3c3-11e7-845c-59a47048a110.png)
![pc1](https://user-images.githubusercontent.com/33368102/32483808-8359f008-c3c3-11e7-8afd-a81f0bf66ab9.png)

**Comment by kloon** [comment]
Can you please follow the [issue logging guidelines](https://github.com/woocommerce/woocommerce/blob/1d2c6d8b20969327c50000ad99f177424a82b590/.github/ISSUE_TEMPLATE.md) and test with a default theme like twentyseventeen or storefront and if the issue persist you are welcome to re-open this issue.

This is not reproducable on the 3.2.3 or master branches when using a default theme.
