### ISSUE TITLE
Link Previous Order doesn't add downloadable product permissions

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce#17600]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a downloadable product
2. Open an incognito window
3. Add the product from step 1 to your cart
4. Checkout using a new email, but make sure it's a Guest Checkout (doesn't matter what product)
5. Make the Order Processing
6. Go buy another product using that same email, this time check "Create an account" at Checkout
7. Go to WooCommerce > Reports > Customers > Customer List
8. Click the "Link Previous Orders" button:
![screen shot 2017-11-06 at 11 05 59 am](https://user-images.githubusercontent.com/3220162/32458820-809c485c-c2e2-11e7-88eb-1f0b4e54c408.png)
9. Now go to your My-Account page for the new account you created, and you will see the first order there! 
10. Go to your Downloads, you will NOT see any downloadable products there.

## Expected/actual behavior

When I linked an old Order that had downloadable product permissions, that it would add those permissions to the user that I linked it to.

As a workaround, you can re-add the product permissions, but ideally, it would do that automatically when linking an old Order.

## Isolating the problem
- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by rodrigoprimo** [comment]
I was able to reproduce this problem. I added it to the 3.3.0 milestone as I'm assuming this is not a regression bug, please correct me if I'm wrong, @mikeyarce. Also, cc @claudiosanches to hear from someone else from the team if this should go 3.3.0 or 3.2.4.

To fix this bug, I imagine it will be necessary to add some logic to update the `user_id` field of the downloadable product files for the updated orders in the function `wc_update_new_customer_past_orders()` (https://github.com/woocommerce/woocommerce/blob/8fd6864a234405d4d0c86c22115316b8e45ea455/includes/wc-user-functions.php#L150).

**Comment by mikeyarce** [comment]
> as I'm assuming this is not a regression bug

@rodrigoprimo what do you mean by regression bug?

**Comment by rodrigoprimo** [comment]
@mikeyarce, I was wondering if you know, off the top of your head, if linking previous order used to add downloadable product permissions in previous WC versions and, at some point, this stopped working or if this is something that never worked since this feature was introduced.

**Comment by mikeyarce** [comment]
@rodrigoprimo ahh ok - no, I don't know if that used to work at some point.  My guess is this might have changed with this change in 3.0.0?
`* Performance - Removed the feature where old orders get access to new downloads on product edit. Looping potentially thousands of orders to do this is too much of a performance burden for stores and this can sometimes be unexpected behavior too. This does however updates *edited* downloads.`
