### ISSUE TITLE
Price in header cart, changes to 0,00€ after 2 seconds web is loaded

### ISSUE THREAD

**Issue by Vintitrenta** [woocommerce/woocommerce#17612]
After change theme to other and uninstall all plugins (no Woocommerce), and clear all server and browser cache, the issue is no t solved.
Because of this, I think is a Woocommerce bug,

what you think?

**Comment by mikejolley** [comment]
WooCommerce core does not have a 'header cart' so I'm not sure how you can change themes and say the issue still occurs. The header cart comes from your theme, and the update will be the 'fragments' code. I'd guess your theme is not using those correctly if the price is 0.

Test the cart widget. If that works, WC is not at fault.

**Comment by Vintitrenta** [comment]
Thanks a lot Mike,
I try the widget and works but is not the same. The theme is Storefront and when i change to any other theme, there is no any change. I test in other themes and uninstalling all plugins except Woo, and continue the issue.
Thanks a lot

**Comment by mikejolley** [comment]
Version of storefront?

**Comment by Vintitrenta** [comment]
Version: 2.2.5
I am sorry to insist, but if I change to any other template in the repository, the same thing happens
thanks!

**Comment by mikejolley** [comment]
As I said, other themes don't have header cart. Unless you're using a plugin for that?

I just tested Storefront and it pulls the correct subtotal.

**Comment by Vintitrenta** [comment]
Ok, but, If I uninstall all plugins excpet Woocommerce, uninstall storefront and reinstall again (clean Storefront theme active), reinstall wordpress (updating again), uninstall Woocommerce and reinstalling again (clean Woocommerce)… what can be the culprit if it's not woocommerce?

**Comment by Vintitrenta** [comment]
Hello again. The issue is solved! But I think maybe is a Storefront issue:
To solve what I do is install the theme named "Retailer" (a theme that have price in header like storefront) = the price is working again, and then I return to Storefront and works fine. 
Because of this I think the Storefront have something wrong in BBDD. When I changed to a theme that have the price in header, this BBDD fragment is reseted = working again.
Because of this I think in some situations Storefront can do this bug in BBDD.
I want to agree so much your support for this. Thants again!
Regards
