### ISSUE TITLE
Double wp_autop in woocommerce_taxonomy_archive_description

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#17616]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

I'm experiencing weird output issues for the description of a taxonomy archive when I use a shortcode in the description itself. After some research I do believe to have found the cause but I can't unfortunately deliver a fix for sure.

Before output, the result of the term_description() function is passed to wc_format_content() which was intended for the filtering/manipulation of the short description field. A bunch of filters are added there, like wp_autop. Unfortunately, the term_description() function of Wordpress already includes a serie of filters, like wp_autop. The two wp_autop are then leading to a weird formatting.

For me, the overriding of the function woocommerce_taxonomy_archive_description() works well if I output the result of term_description() directly, without passing it again through wc_format_content(), but I cannot be sure this would be good for everybody.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17640
