### ISSUE TITLE
Updating product creation date does not update variations creations date

### ISSUE THREAD

**Issue by sgerardiello** [woocommerce/woocommerce#17611]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a product with at least one virtual variation and pubblish
2. Change the product date via wordpress to a past date and update
3. The post_date of the product was updated, the variation equivalent post does not.

## Expected/actual behavior

When I follow those steps, I see that variation post has not an updated date

I was expecting to see is an updated post_date

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Variations are separate objects to the parent product. The dates do not sync. The variation post_date is not exposed anywhere in the UI or used anywhere in the code, so this is a non-issue it seems.

**Comment by claudiulodro** [comment]
Seconding Mike's comment. Why do you need separate dates for e.g. blue shirts and red shirts or size 10 and size 11 shoes?

**Comment by amouratoglou** [comment]
hi I have the same problem, the main product updated date is updated when I query API.
(updated_at ) but the variations display older date! this is very bad because my shop feeds via the API a marketplace where my products are shown. how can I make the dates of the variations to match the main product updated at date?
