### ISSUE TITLE
REST API: Can't add and delete line_items from an existing order via API

### ISSUE THREAD

**Issue by ryelle** [woocommerce/woocommerce#17624]
As part of order management in Calypso, https://github.com/Automattic/wp-calypso/issues/15681, I'm trying to edit an existing order by adding and/or deleting products. See https://github.com/Automattic/wp-calypso/pull/19243 for the up-to-date work.

I've run into trouble when adding and deleting `line_items` in the same API request. It seems to not remove the item before recalculating the order total, leaving the total mismatched from the sum of the products. I can delete a product, and it works; add a product, and it works, but trying to do both in one request triggers this issue. I've tried adding some CURL commands so you can try to reproduce:

Create an order with some items (with your URL and Auth token, using product IDs that exist on the site):

	curl --request POST \
		--url [URL]/wp-json/wc/v3/orders/ \
		--header 'authorization: [AUTH]' \
		--header 'content-type: application/json' \
		--data '{"line_items": [{"product_id": 71,"total": "25.00"},{"product_id": 193,"total": "25.00"}]}'

This is creating a new order with 2 line_items. It successfully creates an order with 2 products, for a total of $50 (or thereabouts, if you have taxes enabled).

Update the order (same as above, along with the new order's ID)

	curl --request POST \
		--url [URL]/wp-json/wc/v3/orders/[ID] \
		--header 'authorization: [AUTH]' \
		--header 'content-type: application/json' \
		--data '{"line_items": [{"id": 92,"product_id": 71,"quantity": 0,"total": "25.00"}, {"product_id": 195,"total": "50.00"}]}'

The data passed above looks like this:

```js
{
  "line_items": [
    {
      "id": 92,
      "product_id": 71,
      "quantity": 0,
      "total": "25.00"
    }, {
      "product_id": 195,
      "total": "50.00"
    }
  ]
}
```

Which means we're removing 1 $25 item, and adding a $50 item, so the order total should now be $75. Instead, it's $100 -- like the deleted item is still there. But it's not, if you look at the order result - only two items in `line_items`. Same on the order page in wp-admin, $100 total but only two items. If you recalculate, or update anything else that triggers a recalc, it goes back to normal. I've only managed to trace this back to `WC_Abstract_Order::calculate_totals`, which _does_ still see the deleted `line_item`. Could the delete be happening after calculate_totals? But just deleting an item correctly updates the price. It's only when delete + add happen on the same request.

If it turns out I'm sending a bad request to the API (possible 🤷🏼‍♀️), let me know what the correct format is - most of this was gleaned by looking at the API code 😅

**Comment by mikejolley** [comment]
Looks like null or qty 0 is handled here in the code: https://github.com/woocommerce/woocommerce/blob/3522857d23051844bea742a37a1b0b242f7850af/includes/api/class-wc-rest-orders-controller.php#L436-L440

`remove_item` seems to unset the item from the order object and requires save to take effect.

`set_item` either adds the item to the order (on create) or updates and saves it directly.

I think this is likely why the totals are messing up; they are interacting with the orders separately, so one update/save/recalc may not see all of the changes.

I'll see if we can change the way it updates line items.

**Comment by mikejolley** [comment]
Further debug this looks like caching too, although I added a non-api unit test and it worked there. Looks like when you remove an item, rather than use the locally stored item in the order, it loads it from the DB. So it's sort of a weird syncing issue?

I have a fix anyway. Pushing shortly.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17628
