### ISSUE TITLE
wp wc tool update-db? or how to automate the db upgrade upon plugin update via wp-cli?

### ISSUE THREAD

**Issue by lordspace** [woocommerce/woocommerce#17626]
Hi,

Is there a way to automate the db upgrade upon plugin update via wp-cli?
![image](https://user-images.githubusercontent.com/137558/32524656-7cacb1a8-c429-11e7-8fba-476362ee72a2.png)

Is there such as function?
wp wc tool update-db?

**Comment by kloon** [comment]
`wp wc update` that will perform the same task as running the updater via that button. If you have a large site I suggest you use the wp-cli command instead of running it via the wp-admin.
