### ISSUE TITLE
Unicode characters not recognised

### ISSUE THREAD

**Issue by eljkmw** [woocommerce/woocommerce#17627]
https://github.com/woocommerce/woocommerce/blob/e90819f92e2efbfbef611a01d5a315326e4d8c92/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L416

I brought this issue up in WordPress.org months ago, but looks like no one has looked into it.  Any unicode characters present in the **Customer Provided Note** meta box order will appear as HTML-code.

Hence adding htmlspecialchars_decode() like so will solve this issue.
`echo '<p><strong>' . __( 'Customer provided note:', 'woocommerce' ) . '</strong> ' . htmlspecialchars_decode( nl2br( esc_html( $post->post_excerpt ) ) ) . '</p>';`

**Comment by mikejolley** [comment]
I'm not seeing a problem. If you can provide proper reproduction steps, please do. I tested an accented character, and an emoji which can be seen working here:

![edit order local wordpress dev wordpress 2017-11-08 13-24-27](https://user-images.githubusercontent.com/90977/32551358-2e6787b6-c488-11e7-8f19-d94a9df0dd82.png)

**Comment by eljkmw** [comment]
Well, the problem is happening to me whenever there is a "&".  When I view the order it shows `&amp;` instead.

**Comment by mikejolley** [comment]
![edit order local wordpress dev wordpress 2017-11-08 13-42-01](https://user-images.githubusercontent.com/90977/32552091-b0b17bc6-c48a-11e7-94ab-a14f50e2a474.png)

**Comment by eljkmw** [comment]
Did you enter the text via admin order, or at checkout ?

**Comment by mikejolley** [comment]
I placed a new order via checkout.

**Comment by eljkmw** [comment]
Very strange indeed.  But will adding htmlspecialchars_decode() cause any unforeseen problems?  I may or may not the only one encountering this issue, and perhaps implementing this can be a good approach.

**Comment by mikejolley** [comment]
I think it could be a security issue since the output is already escaped. Have you ruled out conflicting plugins in this?

**Comment by eljkmw** [comment]
I doubt other plugins may intercept WooCommerce.  Just wondering if a device type may cause unicode characters to convert to HTML code.

**Comment by mikejolley** [comment]
What device are you testing on to ask that?

**Comment by eljkmw** [comment]
My client's customers could using a mix of smartphones, iPads, and other OS computers.
I've tested the following with my old MacBook, and it shows the following.

![screen shot 2017-11-08 at 11 48 54 pm](https://user-images.githubusercontent.com/33481926/32558385-96fed25a-c4df-11e7-93b5-b1ce739fafc3.png)

**Comment by mikejolley** [comment]
Right but I'm just asking what you're testing on :) I was testing on Chrome desktop - is that affected or not (for you)?

**Comment by eljkmw** [comment]
I've been running some tests over the last couple of days, and the different web browser uses are insignificant.  However when I tested on a demo website that uses the same theme with WooCommerce but slightly different WP plugins, it didn't reproduce this issue.  Hmmm ... I'm running out of clues or ideas on what could be causing this issue to the live website.

**Comment by mikejolley** [comment]
If you look at the database, what encoding does the postmeta table use? utf8? utf8mb4?

**Comment by eljkmw** [comment]
Collation is utf8mb4_unicode_520_ci

**Comment by eljkmw** [comment]
Looks like this thread has turned cold.  I'm awaiting advice on which encoding, either utf8 or utf8mb4, should be used for WooCommerce.
My website's wp-config.php contains
```
/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8mb4');
```

**Comment by mikejolley** [comment]
Doesn't WP use utf8mb4_unicode_ci by default now?

**Comment by eljkmw** [comment]
Since WP 4.2, its DB_CHARSET is utf8mb4.  I guess utf8mb4_unicode_ci is DB_COLLATE.  Yes?

Then there is utf8mb4_unicode_520_ci.  What's the difference between the two collation?

**Comment by mikejolley** [comment]
I'm not totally sure about that - I think it limits which chars can be used. https://codex.wordpress.org/Editing_wp-config.php#Database_collation Default value is blank there.

**Comment by eljkmw** [comment]
After looking through my database, I noticed that all products with ampersand (&) are showing as &amp;  The same is true for pages, posts, and even orders.  I truly don't understand why the ampersand (as well as other special characters, such as single/double quotes, less-than/greater-than brackets) aren't decoded to their characters.  But instead, they're encoded to their HTML entity.

**Comment by eljkmw** [comment]
I found the Checkout page textarea text is inputed into the esc_textarea() function.  This is evident in /includes/wc-template-functions.php (on line 2089).  Unfortunately, [esc_textarea](https://codex.wordpress.org/Function_Reference/esc_textarea) returns the encoded text with HTML entities, which is encoding the ampersand (&) into `&amp;`, as well as, other special characters into HTML entities.

Is there a way to override this, without hacking the core of WooCommerce v3.2.6 ?
Please advise.  Thank you.
