### ISSUE TITLE
Garden care wordpress theme issue on php line 76

### ISSUE THREAD

**Issue by charliemenruna** [woocommerce/woocommerce#17634]
Warning: printf(): Too few arguments in /homepages/23/d180239994/htdocs/clickandbuilds/RiversSourceBotanicals/wp-content/themes/gardencare/woocommerce/cart/cart-totals.php on line 76

**Comment by mikejolley** [comment]
You'll need to report this to the author of the gardencare theme. It's not our code or under our control.
