### ISSUE TITLE
add_fee dont work to load pay page

### ISSUE THREAD

**Issue by gleonp** [woocommerce/woocommerce#17636]
Hi, I have this code:

function woo_add_cart_fee() { 
  $name	= 'Valor de envío';
  $fee = $_GET["costoenvio"];
  WC()->cart->add_fee( $name, $fee, false );	
}
add_action( 'woocommerce_cart_calculate_fees', 'woo_add_cart_fee' );

The value take from input text in the checkout page, in review order the value is add to total, but when I click in pay this value is lose. 

Somebody have any idea?

Thanks!

**Comment by mikejolley** [comment]
The fees API is not persistent. You need to add your fee everytime the woocommerce_cart_calculate_fees hook runs or it will be lost.

**Comment by gleonp** [comment]
Hello, in my code how could I do it? There are some things that are not understood very well, but if you give me directions I could solve it.

**Comment by claudiosanches** [comment]
@gleonp better use the support forum: https://wordpress.org/support/plugin/woocommerce

**Comment by gleonp** [comment]
Ok, thanks for the link!
