### ISSUE TITLE
Webhooks pararam de disparar chamadas

### ISSUE THREAD

**Issue by MpBling** [woocommerce/woocommerce#17633]
Boa tarde,

Sou leigo em woocommerce e wordpress. Apenas desenvolvo integrações com a API REST do woocommerce para outros sistemas. Além disso, utilizo as funcionalidades dos webhooks para que esses sistemas recebam chamadas de criação ou alteração de pedidos de venda e produtos. Vários clientes estão utilizando e operando normalmente, no entanto, para um cliente em específico, os webhooks simplesmente pararam de executar as chamadas. 
Ao consultar os logs de chamadas (deliveries) desses webhooks, verifiquei que a última chamada foi realizada no último dia 04/11, por volta das 22:34. Já tentei desativar/ativar, já criei novos webhooks, e mesmo assim os eventos de criação ou alteração são disparam as chamadas dos webhooks. Alguém utiliza esse recurso? Já teve algum problema semelhante?

Obrigado.
Att, Mateus.

**Comment by mikejolley** [comment]
> I am a layman in woocommerce and wordpress. I only develop integrations with the REST API of woocommerce for other systems. In addition, I use the webhooks features so that these systems receive calls to create or change sales orders and products. Several customers are using and operating normally, however, for a particular customer, webhooks simply stopped running the calls.
> When I looked up the webhooks' deliveries logs, I noticed that the last call was made on 04/11, about 22:34. I have already tried to disable / activate, I have created new webhooks, and yet the creation or change events are triggering webhook calls. Does anyone use this feature? Have you ever had a similar problem?

Webhooks run on CRON. You need to ensure cron is running on the affected site. There are plugins to view cron jobs if you need to debug this.

Thanks
