### ISSUE TITLE
Consider adding a filter for adjusting cart item calculated price

### ISSUE THREAD

**Issue by ragulka** [woocommerce/woocommerce#17647]
Calculated line price can sometimes lead to 1 penny off issues since WC 3.2.0. When cart totals are calculated, the line item ["price" (or rather, the "sum") is calculated here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart-totals.php#L230), by simply doing `$product->get_price() * $quantity`.

The result of this operation may sometimes be a number with 3 or more decimal places. When using tax-inclusive pricing, this can cause 1 penny difference in cart subtotal and total, depending on other cart contents as well. I stumbled upon this when working on a support ticket with Measurement Price Calculator, which uses calculated quantities, which may sometimes have decimals, such as `0.5`.

In my testing, I have found that if the result of `$product->get_price() * $quantity` would be rounded to 2 decimals, it would work around the 1 penny off issue. 

An example:
* Product price: `$2.55`, tax: 5.5%, prices are tax-inclusive (also displayed including tax in cart and shop)
* Quantity in cart: `0.5`

The result is: `2.55 * 0.5 = 1.275`. `1.275` will be _displayed_ as `$1.28` in cart, yet `1.275` will be used to calculate line subtotal and taxes. As mentioned above, this _can_ cause 1 penny off issues between cart subtotal and total. Given the example above, the line subtotal and tax are worked out as: 

```
[line_subtotal] => 1.2085308056872
[line_subtotal_tax] => 0.066469194312796
[line_total] => 1.2085308056872
[line_tax] => 0.066469194312796
```

Because one cannot pay half a penny/cent values, the customer would have to pay $1.28 instead of $1.275 anyway - so perhaps it would make sense to simply round up the line total to begin with. This would make sure that when line subtotal and tax are calculated backwards from the price, the results would be as expected. These are the results when simply rounding the result as follows:

```php
round( wc_add_number_precision_deep( $cart_item['data']->get_price() ) * $cart_item['quantity'] )
```

```
[line_subtotal] => 1.2132701421801
[line_subtotal_tax] => 0.066729857819905
[line_total] => 1.2132701421801
[line_tax] => 0.066729857819905
```

Note that the 1 penny off issue is not triggered/apparent with all carts, it sometimes takes some playing around to see this glitch. I have attached below two screenshots of the same cart without and with the rounding. Note that since WooCommerce does not allow floating quantities by default, the examples below use Measurement Price Calculator products. While the price and quantity are displayed as $1.28 and 1, the cart contents _actually_ are $2.55 and 0.5 respectively.

**Without rounding:**

![fireshot capture 9 - cart skyverge plugins - http___plugins skyverge dev_cart_](https://user-images.githubusercontent.com/593267/32648760-a0ae37e6-c5f7-11e7-8eb8-42b5c4757c3f.png)

**With rounding:**

![fireshot capture 10 - cart skyverge plugins - http___plugins skyverge dev_cart_](https://user-images.githubusercontent.com/593267/32648766-a7074d9e-c5f7-11e7-8ed8-4b365258c871.png)

**Notes**

Pre 3.2.0, this issue was not apparent, because WooCommerce [rounded the calculated line subtotal and line subtotal tax](https://github.com/woocommerce/woocommerce/blob/3.1.2/includes/class-wc-cart.php#L1263), which incidentally rounded the subtotal and tax to 1.21 and 0.07 for the example above, giving a total of 1.28 instead of 1.275.

**Proposals**

I see a few different ways of addressing this:

1. Always round the [calculated line price](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart-totals.php#L230) _when_ using tax-inclusive pricing. The reasoning is that the customer will need to pay the rounded value anyway, so it makes little sense to use unrounded values for tax calculation. Ie:

    ```php
    $price = wc_add_number_precision_deep( $cart_item['data']->get_price() ) * $cart_item['quantity'];

    if ( $item->price_includes_tax ) {
        $price = round( $price );
    }

    $item->price = $price;
    ```

2. Add a filter to toggle whether the calculated price should be rounded or not. Ie something like:

    ```php
    $price = wc_add_number_precision_deep( $cart_item['data']->get_price() ) * $cart_item['quantity'];

    if ( true === apply_filters( 'wc_round_calculated_line_price', false, $price, $cart_item ) ) {
        $price = round( $price );
    }

    $item->price = $price;
    ```

3. Add a filter that allows adjusting the calculated line price, ie:

    ```php
    $price = wc_add_number_precision_deep( $cart_item['data']->get_price() ) * $cart_item['quantity'];

    $item->price = apply_filters( 'wc_cart_item_calculated_price', $price, $cart_item );
    ```

**Comment by mikejolley** [comment]
@ragulka 

> Always round the calculated line price when using tax-inclusive pricing. The reasoning is that the customer will need to pay the rounded value anyway, so it makes little sense to use unrounded values for tax calculation.

I don't think thats true. Take a use case like Australia where the tax rate is 10% across most states.

With rounding, if your base state has 10% tax, and the state you're calculating for has 10%, the end result will be different depending on if you're in or out of base. Does that make sense?

I think what I'm trying to say is, to calculate the new tax accurately, you need to calc the tax on the unrounded amount. Maybe thats right or wrong but thats the assumption core is making right now. The unit tests right now are passing with that scenario in mind.

**Comment by ragulka** [comment]
> I don't think thats true. Take a use case like Australia where the tax rate is 10% across most states.
> 
> With rounding, if your base state has 10% tax, and the state you're calculating for has 10%, the end result will be different depending on if you're in or out of base. Does that make sense?

@mikejolley can you give me a an example with specific numbers where that would yield different results with the same tax rate?

But in any case, for cases where the tax rate is included in price and the tax rate does not change depending whether you're in or out of base, rounding the line total to store decimals does make a lot of sense. So at the minimum, a filter here would be really useful, if not an option.

**Comment by mikejolley** [comment]
Re-reading maybe you're not talking about the out of base logic - I didn't notice you were use half-quantities. 

Raise a PR if it doesn't break existing tests :)

**Comment by mikejolley** [comment]
@ragulka This came from a suggestion from another user: https://github.com/woocommerce/woocommerce/pull/17864

With your `2.55 * 0.5 = 1.275` example, before the patch and adding precision this would end up:

`127.5`

After the patch, this will be an integer:

`128`

So it's rounded and effectively the same as what you had done in your PR, just without the added hooks. 

We should avoid adding new hooks until https://github.com/woocommerce/woocommerce/issues/17863 because it may cause BW compatibility issues.
