### ISSUE TITLE
out of stock 

### ISSUE THREAD

**Issue by kianseng** [woocommerce/woocommerce#17645]
hi,  i have a stock quantity problem on simple and variable product >
manage stock : yes
Stock quantity : 99

customer purchase 1 , stock quantity should be 98, but after sales in the product page show out of stock.
WooCommerce > Settings > Product > Out of stock threshold is 0.
Order note didn't decreased by one, it showing stock 0 to -1

i already ask on support forum but no answer, just wanna know is this woocommerce bug or my site problem? 

## Steps to reproduce the issue

1. set up stock quantity ( simple product or variable product )
2. test order for that product
3. after sales the product go to out of stock.

### WordPress Environment ###

Home URL: https://www.mysite.com
Site URL: https://www.mysite.com
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.7.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: zh_CN

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.1.11
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: p8zx_
MaxMind GeoIP Database: ✔
Total Database Size: 2.83MB
Database Data Size: 1.97MB
Database Index Size: 0.86MB
p8zx_woocommerce_sessions: Data: 0.30MB + Index: 0.02MB
p8zx_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
p8zx_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
p8zx_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
p8zx_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
p8zx_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.03MB
p8zx_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
p8zx_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
p8zx_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
p8zx_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
p8zx_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
p8zx_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
p8zx_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
p8zx_woocommerce_log: Data: 0.02MB + Index: 0.02MB
p8zx_apsl_users_social_profile_details: Data: 0.02MB + Index: 0.03MB
p8zx_commentmeta: Data: 0.00MB + Index: 0.01MB
p8zx_comments: Data: 0.01MB + Index: 0.01MB
p8zx_custom_fields: Data: 0.02MB + Index: 0.00MB
p8zx_custom_fields_meta: Data: 0.02MB + Index: 0.00MB
p8zx_links: Data: 0.00MB + Index: 0.00MB
p8zx_litespeed_optimizer: Data: 0.02MB + Index: 0.03MB
p8zx_options: Data: 0.62MB + Index: 0.05MB
p8zx_postmeta: Data: 0.32MB + Index: 0.21MB
p8zx_posts: Data: 0.13MB + Index: 0.04MB
p8zx_revslider_css: Data: 0.02MB + Index: 0.00MB
p8zx_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
p8zx_revslider_sliders: Data: 0.02MB + Index: 0.00MB
p8zx_revslider_slides: Data: 0.02MB + Index: 0.00MB
p8zx_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
p8zx_termmeta: Data: 0.02MB + Index: 0.03MB
p8zx_terms: Data: 0.01MB + Index: 0.04MB
p8zx_term_relationships: Data: 0.01MB + Index: 0.02MB
p8zx_term_taxonomy: Data: 0.01MB + Index: 0.02MB
p8zx_usermeta: Data: 0.03MB + Index: 0.02MB
p8zx_users: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

ad: 4
attachment: 36
client: 4
custom_field: 4
nav_menu_item: 7
page: 29
post: 8
product: 46
product_variation: 26
shop_order: 33
tm_global_cp: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Redux 开发框架: by Team Redux – 3.6.7.7
Social Login WordPress Plugin - AccessPress Social Login Lite: by AccessPress Themes – 3.2.8
Classifieds Custom Post Types: by pebas – 1.0
Envato Market: by Derek Herman – 1.0.0-RC2
Featured Image From URL Premium: by Marcel Jacques Machado – 1.8.9 – Not tested with the active version of WooCommerce
Google XML Sitemaps: by Arne Brachhold – 4.0.9
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
LiteSpeed Cache: by LiteSpeed Technologies – 1.6.2.1
Smeta: by S Web Design Studio – 1.1
WooCommerce - Sales Reporter and Exporter: by Apin Chaudhary – 1.3.0 – Not tested with the active version of WooCommerce
WooCommerce TM Extra Product Options: by themecomplete – 4.6.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3
WP User Avatar: by flippercode – 2.0.8
WPFront Scroll Top: by Syam Mohan – 1.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: MYR (RM)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #1231 - /terms-conditions/

### Theme ###

Name: Classifieds
Version: 1.0
Author URL: http://mysite.com/
Child Theme: ✔
Parent Theme Name: mysite
Parent Theme Version: 2.5.1
Parent Theme Author URL: http://mysite.com/
WooCommerce Support: ✔

### Templates ###

Overrides: classifieds-child/woocommerce/archive-product.php
classifieds-child/woocommerce/cart/cart.php
classifieds-child/woocommerce/content-product.php
classifieds-child/woocommerce/single-product/product-image.php
classifieds-child/woocommerce/single-product/product-thumbnails.php
classifieds-child/woocommerce/single-product.php

`

**Comment by kloon** [comment]
I am not able to reproduce the issue using WooCommerce 3.2.3 or the master branch using a standard theme like TwentySeventeen or Storefront.

My suggestion would be to try and switch to a default theme like Storefront and then also disable all plugins except WooCommerce and see if the problem persists. If it does then please reopen the issue for further investigation.
