### ISSUE TITLE
Remove Feed URL

### ISSUE THREAD

**Issue by grosssmutttr** [woocommerce/woocommerce#17651]
Hi there,

just saw links to myshop.com/product-category/my-category**/feed/** in the Google search results.
If I visit this URL the standard shop-category page appears instead of a 404 page.

So I already tried to disable the feeds via:
```
function remove_disable_feed() {
wp_die( __('No feed available,please visit our <a href="'. get_bloginfo('url') .'">homepage</a>!') );
}
 
add_action('do_feed', 'remove_disable_feed', 1);
add_action('do_feed_rdf', 'remove_disable_feed', 1);
add_action('do_feed_rss', 'remove_disable_feed', 1);
add_action('do_feed_rss2', 'remove_disable_feed', 1);
add_action('do_feed_atom', 'remove_disable_feed', 1);
add_action('do_feed_rss2_comments', 'remove_disable_feed', 1);
add_action('do_feed_atom_comments', 'remove_disable_feed', 1);


remove_action( 'wp_head', 'feed_links_extra', 3 );
remove_action( 'wp_head', 'feed_links', 2 );
```
The first lines have no impact on the /feed/ URL and the wp_die is not called.

The last two lines remove the following out of the `<head>` section:
`<link rel="alternate" type="application/rss+xml" title="My Page &raquo; Mycategory Category Feed" href="https://myshop.com/product-category/my-category/feed/" />`

Unfortunately the links are already generated and indexed by google so there must be a possibility to redirect the existing urls containing /feed/ to the URL without /feed/.

Completely removing the wordpress standard feeds out of the woocommerce pages would be best practice?

**Comment by kloon** [comment]
Unfortunately, we cannot just remove it as there are users making use of the feature.

You can use a plugin like Redirect Manager to add redirect rules for certain urls.

**Comment by grosssmutttr** [comment]
@kloon But there is no feed available under this url it simply shows the product category page so this creates duplicate content...

**Comment by kloon** [comment]
I just tested with the lastest version of WooCommerce and there are feeds in my standard installations. If there are nothing showing then a plugin, your theme or some custom code might be removing it http://cld.wthms.co/rWR9oU

**Comment by shmaltz** [comment]
I just noticed the same thing, that Google is indexing all my /product/feed/ URLs. Is there a hook that will allow me to add a NoIndex to all the feed pages? Or can I just disable these pages somehow? Thanks!
