### ISSUE TITLE
Some cart text i want to change

### ISSUE THREAD

**Issue by funk1988** [woocommerce/woocommerce#17657]
Hi Everyone,

I have a question about my website/woocommerce what i cant figure out by myself.
So if anyone could help me with this i would apreciate it.
Im trying to change some items name in the shop cart.
I was able to change some words but not everything.
I want to change the titles: Product, price, status,qty, total, remove.
The In Stock text and the coupon titles.
Continue shopping and update cart button.

I tried to look for it in the php files and thought i changed them but there was no result on the website.
Any help would be apreciated!

![cart](https://user-images.githubusercontent.com/33552771/32667846-2dee7708-c63c-11e7-91fa-6201aa44f266.jpg)

**Comment by claudiulodro** [comment]
You can modify those by changing [the cart template](https://github.com/woocommerce/woocommerce/blob/master/templates/cart/cart.php). Follow the instructions at the top of the file.

Next time, please post questions or things you're looking for help with on [the forums](https://wordpress.org/support/plugin/woocommerce). GitHub is only for bugs in the core WooCommerce plugin. Thanks.

**Comment by funk1988** [comment]
Im sorry.
Didnt know that.
I did what you said. Changed it in the php but nothing happend on the website.
It is still the same
