### ISSUE TITLE
3.2.3 "AND" operator not working as specified in Shortcodes included doc

### ISSUE THREAD

**Issue by slwinter** [woocommerce/woocommerce#17658]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  Per the shortcodes included doc, the operator "AND" can be used to include multiple categories on the cart page.  If [products limit="8" columns="4" category="hoodies, tshirts" cat_operator="AND"] is used, I would see not products.  However, if [products limit="8" columns="4" category="hoodies"] is used, I see the expected results.  I am using 3.2.3.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

no products/categories

I was expecting to see...

Two categories of products.  I have products in both categories I am specifying.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
`
### WordPress Environment ###

Home URL: http://weimfundraising.com
Site URL: http://weimfundraising.com
WC Version: 3.2.3
Log Directory Writable: ❌ To allow logging
make /home/weimfund/public_html/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.21
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 2000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 33.96MB
Database Data Size: 28.90MB
Database Index Size: 5.06MB
wp_woocommerce_sessions: Data: 2.61MB + Index: 0.13MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.03MB
wp_woocommerce_order_itemmeta: Data: 0.39MB + Index: 0.30MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_bp_activity: Data: 0.02MB + Index: 0.03MB
wp_bp_activity_meta: Data: 0.00MB + Index: 0.01MB
wp_bp_follow: Data: 0.00MB + Index: 0.00MB
wp_bp_friends: Data: 0.00MB + Index: 0.00MB
wp_bp_groups: Data: 0.00MB + Index: 0.00MB
wp_bp_groups_groupmeta: Data: 0.00MB + Index: 0.00MB
wp_bp_groups_members: Data: 0.00MB + Index: 0.00MB
wp_bp_messages_messages: Data: 0.00MB + Index: 0.00MB
wp_bp_messages_meta: Data: 0.00MB + Index: 0.01MB
wp_bp_messages_notices: Data: 0.00MB + Index: 0.00MB
wp_bp_messages_recipients: Data: 0.00MB + Index: 0.01MB
wp_bp_notifications: Data: 0.00MB + Index: 0.01MB
wp_bp_notifications_meta: Data: 0.00MB + Index: 0.00MB
wp_bp_user_blogs: Data: 0.00MB + Index: 0.00MB
wp_bp_user_blogs_blogmeta: Data: 0.00MB + Index: 0.01MB
wp_bp_xprofile_data: Data: 0.01MB + Index: 0.01MB
wp_bp_xprofile_fields: Data: 0.00MB + Index: 0.01MB
wp_bp_xprofile_groups: Data: 0.00MB + Index: 0.00MB
wp_bp_xprofile_meta: Data: 0.00MB + Index: 0.01MB
wp_charitable_campaign_donations: Data: 0.00MB + Index: 0.00MB
wp_charitable_donors: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.13MB + Index: 0.08MB
wp_cp_contact_form_paypal_discount_codes: Data: 0.00MB + Index: 0.00MB
wp_cp_contact_form_paypal_posts: Data: 0.00MB + Index: 0.00MB
wp_cp_contact_form_paypal_settings: Data: 0.00MB + Index: 0.00MB
wp_formmaker: Data: 0.04MB + Index: 0.00MB
wp_formmaker_backup: Data: 0.02MB + Index: 0.00MB
wp_formmaker_blocked: Data: 0.02MB + Index: 0.00MB
wp_formmaker_query: Data: 0.02MB + Index: 0.00MB
wp_formmaker_sessions: Data: 0.00MB + Index: 0.00MB
wp_formmaker_submits: Data: 0.00MB + Index: 0.00MB
wp_formmaker_themes: Data: 0.56MB + Index: 0.00MB
wp_formmaker_views: Data: 0.00MB + Index: 0.00MB
wp_give_customermeta: Data: 0.00MB + Index: 0.00MB
wp_give_customers: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_newsletter: Data: 0.00MB + Index: 0.01MB
wp_newsletter_emails: Data: 0.09MB + Index: 0.00MB
wp_newsletter_sent: Data: 0.00MB + Index: 0.00MB
wp_newsletter_stats: Data: 0.01MB + Index: 0.01MB
wp_options: Data: 4.69MB + Index: 0.18MB
wp_postmeta: Data: 4.98MB + Index: 1.27MB
wp_posts: Data: 1.74MB + Index: 0.28MB
wp_pv_commission: Data: 0.03MB + Index: 0.01MB
wp_recommendposts_votes: Data: 0.00MB + Index: 0.00MB
wp_signups: Data: 0.02MB + Index: 0.02MB
wp_simple_auction_log: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.01MB + Index: 0.02MB
wp_terms: Data: 0.01MB + Index: 0.03MB
wp_term_relationships: Data: 0.03MB + Index: 0.06MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.02MB
wp_ufbl_entries: Data: 0.00MB + Index: 0.00MB
wp_ufbl_forms: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.31MB + Index: 0.20MB
wp_users: Data: 0.01MB + Index: 0.02MB
wp_wcd_charity: Data: 0.00MB + Index: 0.00MB
wp_wcv_feedback: Data: 0.00MB + Index: 0.00MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.08MB + Index: 0.07MB
wp_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 1.83MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB
wp_wfFileMods: Data: 4.02MB + Index: 0.86MB
wp_wfHits: Data: 1.12MB + Index: 0.23MB
wp_wfHoover: Data: 2.83MB + Index: 0.38MB
wp_wfIssues: Data: 0.04MB + Index: 0.00MB
wp_wfKnownFileList: Data: 2.02MB + Index: 0.26MB
wp_wfLeechers: Data: 0.03MB + Index: 0.03MB
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.01MB
wp_wfLogins: Data: 0.18MB + Index: 0.04MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.01MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_wfScanners: Data: 0.03MB + Index: 0.03MB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.86MB + Index: 0.33MB
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_wsluserscontacts: Data: 0.00MB + Index: 0.00MB
wp_wslusersprofiles: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.01MB + Index: 0.00MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 910
bp-email: 16
campaign: 1
cf7_style: 9
fmemailverification: 1
forum: 4
give_forms: 2
gpages: 3
mc4wp-form: 1
nav_menu_item: 9
omapi: 6
page: 33
post: 8
product: 303
product_variation: 182
reply: 21
revision: 324
ris_gallery: 1
shop_order: 183
shop_order_vendor: 261
stc: 1
topic: 13
tribe_events: 11
tribe_organizer: 8
tribe_venue: 4
woo_product_bages: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (28) ###

Akismet Anti-Spam: by Automattic – 4.0
bbPress: by The bbPress Community – 2.5.14
BP Remove Profile Links: by @bphelp – 1.2
MarketPlace: by BuddyBoss – 1.4.2
BuddyPress: by The BuddyPress Community – 2.9.2
Color Filters for WooCommerce: by Elementous – 1.2.2 – Not tested with the active version of WooCommerce
Easy Social Share Buttons for WordPress: by CreoApps – 3.5 – Not tested with the active version of WooCommerce
Easy WP SMTP: by wpecommerce – 1.3.0
The Events Calendar PRO: by Modern Tribe
Inc. – 4.4.19

GD bbPress Attachments: by Milan Petrovic – 2.5
IgniteWoo Updater: by IgniteWoo.com – 2.1.9
Image Widget Deluxe: by Rommel – 1.0.6
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.11.2.1
Newsletter: by Stefano Lissa & The Newsletter Team – 5.1.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
vendocrat Server Monitor: by vendocrat – 0.2.1
Subscribe To Comments: by Mark Jaquith – 2.3
The Events Calendar: by Modern Tribe
Inc. – 4.6.3

Ultimate Form Builder Lite: by AccessPress Themes – 1.3.7
Ultimate Responsive Image Slider: by Weblizar – 3.0.10
WC Vendors Pro Simple Auctions: by WC Vendors – 1.0.3 – Not tested with the active version of WooCommerce
WC Vendors Pro: by WC Vendors – 1.4.3
WC Vendors: by WC Vendors – 1.9.12
WooCommerce Simple Auction: by wpgenie – 1.2.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3
Wordfence Security: by Wordfence – 6.3.21
Yoast SEO: by Team Yoast – 5.7.1
WordPress Social Login: by Miled – 2.3.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: auction (auction)
donation (donation)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #58 - /shop/
Cart: #59 - /cart/
Checkout: #60 - /checkout/
My account: #61 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: OneSocial Child Theme
Version: 1.0.7
Author URL: http://www.buddyboss.com
Child Theme: ✔
Parent Theme Name: OneSocial
Parent Theme Version: 1.4.0
Parent Theme Author URL: https://www.buddyboss.com
WooCommerce Support: ✔

### Templates ###

Overrides: onesocial/woocommerce/product-searchform.php

### WC Vendors Pro ###

Theme Compatability: -
Pro Dashboard Page: - #646
Feedback form page: - #978
Vendor Shop Permalink: - rescues/

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
AND means the product must be both a hoody and a t-shirt.

**Comment by slwinter** [comment]
I feel stupid.  Thank you.
