### ISSUE TITLE
403 /?wc-ajax=update_order_review 

### ISSUE THREAD

**Issue by ottybrad** [woocommerce/woocommerce#17655]
currently getting a 403 /?wc-ajax=update_order_review 

which only happens when existing users login at oint of checkout using Returning customer login.

the shipping and payment method just wont load so customers can not check out, i have read all previous issue with this on git and most say htaccess or modsecurity, ive regenerated my htaccess and wpengine have told me they do not use ModSec. 

Turned of all plugins apart from woocommerce and also switch theme to 2017 and still the same. my host has been trying to resolve this for a week now and we are getting now where 

### WordPress Environment ###
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31-4+wpengine10
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 66.11MB
Database Data Size: 35.43MB
Database Index Size: 30.68MB
wp_woocommerce_sessions: Data: 1.14MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.20MB + Index: 0.08MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.94MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.14MB + Index: 0.03MB
wp_comments: Data: 1.52MB + Index: 1.02MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
wp_followup_customers: Data: 0.09MB + Index: 0.17MB
wp_followup_customer_carts: Data: 0.34MB + Index: 0.11MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.08MB + Index: 0.05MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.16MB + Index: 0.09MB
wp_followup_email_orders: Data: 1.52MB + Index: 0.30MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.09MB + Index: 0.11MB
wp_followup_followup_history: Data: 1.52MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.09MB + Index: 0.11MB
wp_followup_order_items: Data: 0.09MB + Index: 0.14MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.22MB + Index: 0.27MB
wp_postmeta: Data: 15.55MB + Index: 19.06MB
wp_posts: Data: 2.52MB + Index: 0.75MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.08MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.28MB + Index: 0.03MB
wp_rg_lead_detail: Data: 1.52MB + Index: 1.13MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_snp_log: Data: 0.02MB + Index: 0.00MB
wp_snp_stats: Data: 0.02MB + Index: 0.05MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.08MB + Index: 0.09MB
wp_term_relationships: Data: 0.19MB + Index: 0.11MB
wp_term_taxonomy: Data: 0.08MB + Index: 0.09MB
wp_usermeta: Data: 3.52MB + Index: 3.98MB
wp_users: Data: 0.16MB + Index: 0.16MB
wp_wp_optimisation_sizes_info: Data: 0.02MB + Index: 0.00MB
wp_yith_ywrac_email_log: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 586
customize_changeset: 2
follow_up_email: 2
nav_menu_item: 25
page: 12
post: 3
product: 172
product_variation: 1207
revision: 52
scheduled-action: 481
shop_coupon: 25
shop_order: 1080
shop_order_refund: 9
shop_webhook: 1
snp_popups: 1
wc_order_email: 1
wc_order_status: 9
yith-wccos-ostatus: 1
ywrac_cart: 1
ywrac_email: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Gravity Forms: by rocketgenius – 2.2.3.5
Facebook for WooCommerce: by Facebook – 1.4.5 – Not tested with the active version of WooCommerce
GetBowtied Tools: by GetBowtied – 2.3.1
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.2
User Switching: by John Blackbourn – 1.2.0
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.3.7 – 4.4.0 is available – Not tested with the active version of WooCommerce
Follow-Up Emails: by WooCommerce – 4.5.1 – 4.5.2 is available – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.16 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by Bolder Elements – 4.0.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3
YITH WooCommerce Custom Order Status Premium: by YITHEMES – 1.0.21 – Not tested with the active version of WooCommerce
Zendesk Chat Widget: by Zopim – 1.4.11

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /basket/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Shopkeeper
Version: 2.3.2
Author URL: https://www.getbowtied.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php
shopkeeper/woocommerce/cart/cart-empty.php
shopkeeper/woocommerce/cart/mini-cart.php
shopkeeper/woocommerce/checkout/form-coupon.php
shopkeeper/woocommerce/checkout/form-login.php
shopkeeper/woocommerce/content-product.php
shopkeeper/woocommerce/content-product_cat.php
shopkeeper/woocommerce/content-single-product.php
shopkeeper/woocommerce/global/quantity-input.php
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/loop/loop-end.php
shopkeeper/woocommerce/loop/loop-start.php
shopkeeper/woocommerce/loop/no-products-found.php
shopkeeper/woocommerce/myaccount/form-login.php
shopkeeper/woocommerce/myaccount/my-downloads.php
shopkeeper/woocommerce/order/form-tracking.php
shopkeeper/woocommerce/single-product/product-image.php
shopkeeper/woocommerce/single-product/product-thumbnails.php
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product.php

### Customer/Order CSV Export ###

Order Export Format: custom
Customer Export Format: custom
Automatically Export Orders: disabled
Automatically Export Customers: disabled
`

**Comment by mikejolley** [comment]
Your homepage is being cached - add an exclusion rule in W3 total cache for `wc-ajax`

**Comment by ottybrad** [comment]
unfortunately we are not allowd to use caching plugins on wp-engine 
    WP Super Cache
    WP File Cache
    W3 Total Cache
    WordFence
all disallowed plugins

**Comment by mikejolley** [comment]
Ah nvm I was looking at the theme author's URL. What is your store URL? Can't check without seeing it.

**Comment by ottybrad** [comment]
glamzoo.com

**Comment by mikejolley** [comment]
When logged in, what does `https://glamzoo.com/?wc-ajax=update_order_review` show?

**Comment by ottybrad** [comment]
-1

**Comment by ottybrad** [comment]
this was cause by a define cookie path in wp config now resolved

**Comment by boethius** [comment]
@bradholmes-studio what did you do to resolve it?

**Comment by ChaosFreak** [comment]
@bradholmes-studio,
It is customary to post how you solved a problem so that the entire community can benefit. This is not a one-on-one support channel, but a community designed to help everyone.
Could you please post how you were able to resolve this issue? There are many other people who need the solution.

**Comment by DieWebmacherin** [comment]
I think I found the complete solution in another support thread (https://wordpress.org/support/topic/wc-ajaxupdate_order_review-403-error/).

You need to check your wp-config.php for the following lines an remove them:
`define( 'ADMIN_COOKIE_PATH', '/' );`
`define( 'COOKIE_DOMAIN', 'false' );`
`define( 'COOKIEPATH', '' );`
`define( 'SITECOOKIEPATH', '' );`

These lines are a fix for cookie/login issues on multisites (as described here: https://kinsta.com/blog/wordpress-multisite/#how-to-fix-the-wordpress-multisite-cookies-error).

Unfortunately I haven't found a way to fix both issues yet. I may have to split up my multisite into separate installations.

Edit: I may have found the solution for a multisite with Woocommerce (described here: https://woomultistore.com/solution-error-cookies-are-blocked-or-not-supported-by-your-browser-you-must-enable-cookies-to-use-wordpress/).

You only need one line from the multisite fix above in your wp-config.php. This fixes the multisite cookie/login error and doesn't break Woocommerce:
`define('COOKIE_DOMAIN', false);`

**Comment by uglyeoin** [comment]
For me this turned out to be a mod_security setting being triggered by an overzealous firewall (false positive).  Hope that helps someone.
