### ISSUE TITLE
Posting a new product through the API ignores category

### ISSUE THREAD

**Issue by ZohraS** [woocommerce/woocommerce#17668]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Make a post request to /wc/v2/products with the category as 
`"categories": [{id:1}]`
 
2. Check out the response and watch it being ignored

## Expected/actual behavior

When I follow those steps, I see...

The categories I get back in the response are an empty array.

I was expecting to see...

The array with the id, name and slug

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

I just updated from v1 to  v2, and that stopped working. It used to work fine on v1 before my update.

I have an app pretty much  ready for a client, but I need this to work. Help?

**Comment by mikejolley** [comment]
![insomnia local create product 2017-11-13 11-16-05](https://user-images.githubusercontent.com/90977/32723085-12eb9a74-c864-11e7-8c14-a3f5e66bdccb.png)

No issue here, works as intended. I'm sure your example was purely an example, but you need to ensure that ID exists or it won't link with the product.

Thanks
