### ISSUE TITLE
Incorrect URL on multsite in Woocommerce Extensions page

### ISSUE THREAD

**Issue by gareth-gillman** [woocommerce/woocommerce#17665]
Not a massive issue just a broken url, If you install Multisite, install Woocommerce then go to woocommerce > extensions and click install for storefront, the url takes you to domain.com/wp-admin/theme-install.php?theme=storefront where as it should be domain.com/wp-admin/network/theme-install.php?theme=storefront, while doing that I guess you need to check if the person viewing the page is the network admin.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17675
