### ISSUE TITLE
Stuck on Variables Loading Screen

### ISSUE THREAD

**Issue by Walnutmill** [woocommerce/woocommerce#17661]
Trying to create a variable product and it gets stuck on loading screen. We select create variations from all attributes and click the submit button and the screen just shows loading icon forever. We have the most current version of Woocommerce installed and have tried multiple plugin deactivation's as well. In addition we have increased memory limits on the site and increased the number of variations allowed thinking that these might all be issues. Is there maybe something we are missing yet?

**Comment by mikejolley** [comment]
We cannot really do much without steps to reproduce or debugging data, but what you need to do is find the source of the problem by looking at the error logs.

There are 2 places you may find information:

1. WooCommerce > System Status > Logs - there is a 'fatal error' log. See if there is anything related there.
2. Check the PHP error log on your server after triggering the error.

I think it's likely either a plugin conflict or memory issue.  "increased the number of variations allowed" --> if it's memory you should reduce this so less are created per run. That said, if you have a variation with this volume of attributes and combinations, other approaches may be needed. 

Let us know what you find.
Thanks

**Comment by Walnutmill** [comment]
Hi Mike,

We will check the logs and thanks for the ideas. As for the memory issue we
increased it to try to give more memory with no luck. I can see how to much
memory can cause issues at times. The runs were originally at the default
of 50, but here is the problem we encountered. We have almost 400
variations for our gift basket. So we originally thought we would do it in
50 or less runs. The problem we encountered doing it this way was that when
we added new variations the drop downs that were displayed on the page
would change to whatever we had just run and the drop downs from the
previous runs would disappear. Now when you looked at the back end you
would see the runs in the variations from all runs, but none of these would
show on the page of the gift basket. We had no such issue with the previous
versions of Woocommerce. It wasn't until the version right before this most
current that we noticed that all of our variations were missing from our
page and that the item was always showing as out of stock. So given this if
the logs do not show anything how can we get around this problem that is
happening.

Thanks,

Kevin Grames

**Comment by mikejolley** [comment]
If missing, usually thats due to missing data e.g. prices, or variations in the 'wrong' order. It's hard with that volume of variations though.

Wouldn't something like product add-ons be more suitable if you're dealing with many attributes? Or bundles/composite products?

**Comment by Walnutmill** [comment]
If there is a better way I am ok with this. The customer simply has to be
able to build their basket with the items they want. So they choose 3
soaps, 3 bath bombs, 1 lotion or body butter. They have the options of
fragrances so that upon checkout we would receive a packing list with their
choices.

Thanks

Kevin

**Comment by mikejolley** [comment]
Take a look at https://docs.woocommerce.com/document/group-bundle-products-woocommerce/

**Comment by Walnutmill** [comment]
Hi Mike,

I finally got the drop downs to work. However, I get this message when we
select the items to make the basket. Sorry, this product is unavailable.
Please choose a different combination.

I am including a screen shot for you. I have not figured out how to set the
pricing yet for the overall price, but this is a step in the right
direction. We want to price our basket at 49.95, but I have not seen how to
get that to work now.

Thanks,

Kevin
