### ISSUE TITLE
Attributes not consistently saving.

### ISSUE THREAD

**Issue by RiaanKnoetze** [woocommerce/woocommerce#17672]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

* Create a product category: attributes-test 
* Create an attribute: test-attribute 
* Create attributes: attribute-8, attribute-9 
* Create a products with attributes: attribute-8, attribute-9 
* Check the box to make attributes visible on product page 
* Click the UPDATE button to save the product. 
* Create a page using the following shortcode: ```[products category="attributes-test" attribute="test-attribute" terms="attribute-9"]```
* View page - Product will appear 
* Edit product - View Attributes - Delete attribute-9 - Click SAVE ATTRIBUTES 
* Refresh page 
* Product will still be there. If you check the ADDITIONAL INFO tab, you will see that attribute-9 is not there. 
* Go back to the product page and click the UPDATE button. 
* Refresh the page. The product will now disappear.

## Expected/actual behavior

When I follow those steps, I see that products created when clicking on the "Publish/Update" button doesn't always save the data. Clicking "Save Attributes" works consistently. I expected both buttons to save all the data.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

Ticket: 786530

**Comment by mikejolley** [comment]
Going through the steps exactly as you outlined:

> Product will still be there. If you check the ADDITIONAL INFO tab, you will see that attribute-9 is not there.

At this point the product was removed from the shortcode output. So this is working for me, however, I think it's just a cache clearing issue anyway and one we should be able to mitigate with a small code change. PR to follow.
