### ISSUE TITLE
"Billing email is a required field." error

### ISSUE THREAD

**Issue by VacBargain** [woocommerce/woocommerce#17688]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by VacBargain** [comment]
![screenshot 268](https://user-images.githubusercontent.com/33642519/32756806-1a8777f4-c930-11e7-843a-2e23dcd5e234.png)
Any solution, please help

**Comment by mikejolley** [comment]
Judging by your screenshot you have a **custom checkout form** which is likely not removing these fields correctly so they are still validated. You need to look into what is generating that and remove/inform the author. The checkout pictured is not WooCommerce core.
