### ISSUE TITLE
Prices on productline

### ISSUE THREAD

**Issue by OnlineAdvisor** [woocommerce/woocommerce#17689]
Hi everyone

After upgrading to the new WooCommerce version 3.2.3 I have been fighting with a technical issue because my shop doesn't show productprices in the confirmations, but only subtotal. Don't know how to fix this.

Thanks in advance. 

Best Regards

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Without details (status report etc) _as requested_ when you submit the report, there are zero clue to go by. It could be a plugin conflict or it could be the email templates in your theme if they have been overridden. See the 'isolating the problem' steps above.

Thanks

**Comment by OnlineAdvisor** [comment]
Hi Mike

Thanks for quick response. 

I forgot the system report, but here it is:

`
### WordPress Environment ###

Home URL: http://amladcykler.dk
Site URL: http://amladcykler.dk
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.23
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: clk_2977857393_wp_
MaxMind GeoIP Database: ✔
Total databasestørrelse: 42.41MB
Database datastørrelse: 31.48MB
Database indexstørrelse: 10.93MB
clk_2977857393_wp_woocommerce_sessions: Data: 3.41MB + Index: 0.06MB
clk_2977857393_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
clk_2977857393_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
clk_2977857393_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
clk_2977857393_wp_woocommerce_order_items: Data: 0.23MB + Index: 0.08MB
clk_2977857393_wp_woocommerce_order_itemmeta: Data: 2.52MB + Index: 2.00MB
clk_2977857393_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
clk_2977857393_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
clk_2977857393_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
clk_2977857393_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
clk_2977857393_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
clk_2977857393_wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
clk_2977857393_wp_commentmeta: Data: 0.02MB + Index: 0.03MB
clk_2977857393_wp_comments: Data: 0.19MB + Index: 0.16MB
clk_2977857393_wp_fmeasl_stores: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_circles: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_maps: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_mapstyles: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_markercategories: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_markers: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_options: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_polygons: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_polylines: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_rectangles: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_shortcodes: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_gmwd_themes: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_limit_login: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_links: Data: 0.02MB + Index: 0.02MB
clk_2977857393_wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_nf3_field_meta: Data: 0.05MB + Index: 0.00MB
clk_2977857393_wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_nf3_object_meta: Data: 0.13MB + Index: 0.00MB
clk_2977857393_wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_ngg_album: Data: 0.02MB + Index: 0.02MB
clk_2977857393_wp_ngg_gallery: Data: 0.02MB + Index: 0.02MB
clk_2977857393_wp_ngg_pictures: Data: 0.11MB + Index: 0.02MB
clk_2977857393_wp_options: Data: 1.52MB + Index: 0.09MB
clk_2977857393_wp_postmeta: Data: 4.52MB + Index: 3.03MB
clk_2977857393_wp_posts: Data: 7.52MB + Index: 0.45MB
clk_2977857393_wp_termmeta: Data: 0.02MB + Index: 0.03MB
clk_2977857393_wp_terms: Data: 0.08MB + Index: 0.09MB
clk_2977857393_wp_term_relationships: Data: 0.09MB + Index: 0.06MB
clk_2977857393_wp_term_taxonomy: Data: 0.09MB + Index: 0.09MB
clk_2977857393_wp_usermeta: Data: 0.05MB + Index: 0.03MB
clk_2977857393_wp_users: Data: 0.02MB + Index: 0.05MB
clk_2977857393_wp_wpgmza: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_WP_SEO_404_links: Data: 9.57MB + Index: 3.78MB
clk_2977857393_wp_WP_SEO_Cache: Data: 0.00MB + Index: 0.00MB
clk_2977857393_wp_WP_SEO_Redirection: Data: 0.03MB + Index: 0.03MB
clk_2977857393_wp_WP_SEO_Redirection_LOG: Data: 0.16MB + Index: 0.01MB
clk_2977857393_wp_yith_wapo_groups: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_yith_wapo_types: Data: 0.02MB + Index: 0.00MB
clk_2977857393_wp_yoast_seo_links: Data: 0.05MB + Index: 0.02MB
clk_2977857393_wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB
clk_ae75e0e6a2_wp_commentmeta: Data: 0.02MB + Index: 0.03MB
clk_ae75e0e6a2_wp_comments: Data: 0.02MB + Index: 0.08MB
clk_ae75e0e6a2_wp_links: Data: 0.02MB + Index: 0.02MB
clk_ae75e0e6a2_wp_options: Data: 0.02MB + Index: 0.02MB
clk_ae75e0e6a2_wp_postmeta: Data: 0.02MB + Index: 0.03MB
clk_ae75e0e6a2_wp_posts: Data: 0.02MB + Index: 0.06MB
clk_ae75e0e6a2_wp_termmeta: Data: 0.02MB + Index: 0.03MB
clk_ae75e0e6a2_wp_terms: Data: 0.02MB + Index: 0.03MB
clk_ae75e0e6a2_wp_term_relationships: Data: 0.02MB + Index: 0.02MB
clk_ae75e0e6a2_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
clk_ae75e0e6a2_wp_usermeta: Data: 0.02MB + Index: 0.03MB
clk_ae75e0e6a2_wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 318
customize_changeset: 4
displayed_gallery: 14
nav_menu_item: 44
nf_sub: 123
ngg_gallery: 24
ngg_pictures: 196
page: 37
polylang_mo: 2
post: 27
product: 121
revision: 1509
shop_order: 702
shop_webhook: 1
sidebar: 2
wafs: 1

### Security ###

Secure connection (HTTPS): ❌Din shop bruger ikke HTTPS. Få mere information om HTTPS og SSL Certifikater.
Hide errors from visitors: ✔

### Active Plugins (16) ###

Polylang: af Frédéric Demarle – 2.2.5
Advanced Mail Recipients for Woo: af TOGI Data ApS – 1.0
All In One Schema.org Rich Snippets: af Brainstorm Force – 1.5.1
Envato WordPress Toolkit: af Envato – 1.7.3
Lingotek Translation: af Lingotek and Frédéric Demarle – 1.3.3
Ninja-formularer: af The WP Ninjas – 3.2.4
SEO Redirection: af Fakhri Alsadi – 4.8
Compress JPEG & PNG images: af TinyPNG – 2.2.6
UpdraftPlus - Backup/Restore: af UpdraftPlus.Com
DavidAnderson – 1.13.12

W3 Total Cache: af Frederick Townes – 0.9.5.4
WooCommerce AdWords Dynamic Remarketing: af Wolf+Bär Agency – 1.4.5 – Ikke testet med den nuværende version af WooCommerce
WooCommerce: af Automattic – 3.2.3
Yoast SEO: af Team Yoast – 5.7.1
WP Limit Login Attempts: af Arshid – 2.6.2
WPML to Polylang: af Frédéric Demarle – 0.2.4
YITH WooCommerce Product Add-Ons: af YITHEMES – 1.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop basisside: #10 - /shop/
Kurv: #1028 - /indkoebskurv-2/
Checkout: #12 - /til-kassen/
Min konto: ❌ Side synlighed skal være offentlig
Handelsbetingelser: #38 - /salgs-leveringsbetingelser/

### Theme ###

Name: Flatsome
Version: 3.4.0
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – Hvis du redigerer WooCommerce i et hoved-tema
som du ikke selv har udviklet
anbefaler vi at du anvender et undertema (child theme). Se: Hvordan du opretter et undertema

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

**Comment by mikejolley** [comment]
Test without Polylang enabled, and repeat for others if it's not that.
