### ISSUE TITLE
Woocommerce Product Gallery Slider Performance

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#17695]
Currently Woocommerce product gallery slider are using the separate product images. This means it will request images separately from server. Imagine that i have 99 variants with 99 images. The Woocommerce product gallery slider will request the same amount as variants

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to product details
2. Check the product image requests

## Expected/actual behavior

Woocommerce product gallery slider will use the variant's product images instead of its own gallery to minimize the image request and make it flexible for developers. 

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Look at the code https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js#L547-L600

The images are not all loaded in the page - not until variation changes. When variation changes, if the image IS IN THE GALLERY, it will use it. If not, it will update the image SRC. This is expected.

> Imagine that i have 99 variants with 99 images

If you had this scenario and were worried about images loading on the page, you simply wouldn't set variation images... it's not mandatory.

> This means it will request images separately from server

How else can you do it. Images are separate objects...

If you have a solution or I'm not understanding your problem (not apparent from the above issue) let me know.

**Comment by kevin25** [comment]
@mikejolley I checked on my woo sites, they load all images at a time. We export T-Shirts from 3rd fulfillment. Each color has its own image. 

Loading images from variant instead of gallery is what shopify do. That will help us avoid so many query at a time and easy to do something like click on images to select variants automatically. We should learn something from them.

**Comment by mikejolley** [comment]
Show me an example page?

**Comment by kevin25** [comment]
I can't put it here. Can I send you via email?

**Comment by mikejolley** [comment]
If you like but a website isn't exactly private :)

**Comment by kevin25** [comment]
I'm sorry, Mike. I have many competitors and copycats out there.
