### ISSUE TITLE
Duplicating products in storefront

### ISSUE THREAD

**Issue by Ground29** [woocommerce/woocommerce#17706]
Hi, I am getting double post now and in backend of store looks fine, just the front of store where I am seeing doubles. I'm using printful to upload my products. Printful side looks fine too. When I upload to store from printful everything looks fine but when I go to storefront I see double and when it doubles it take a place on a older product and hides it. In backend everything looks normal. Need help please been trying to fix this for weeks now. Thanks

**Comment by claudiulodro** [comment]
Are you on the latest version of Storefront? If so, this is going to be an issue with the Printful plugin or one of your other plugins and not with the core WooCommerce plugin. To figure out which plugin is causing the problem you should disable all of your plugins except for WooCommerce and enable them 1-by-1 until the problem starts happening again.

GitHub is just for bugs in the core WooCommerce plugin, so if you are unable to figure the problem out you should try [the forums](https://wordpress.org/support/plugin/woocommerce). Good luck!

**Comment by Ground29** [comment]
I'm using version 2.2.5 Storefront theme. I think it's the newest version.
I have not received any notices to update theme. Yesterday I disabled all
my plug in except the must haves, Tax Jar, and woo commerce. I still had
doubles showing up. Printful says it's not on their side.

Thanks

**Comment by Ground29** [comment]
Oh I see you closed this, Thanks aways

**Comment by mikejolley** [comment]
You need to do all of them to isolate a problem properly. Including the theme, just in case.

**Comment by Ground29** [comment]
Even the Must-use ones? There 4 in there but only one tab to disable.

**Comment by Ground29** [comment]
OK I disabled all plugins even the 4 Must-use except for woo and printful, changed to child theme and tried the twenty seventeen and still shows duplicates. I can't disable printful right now because of a order I have in process. So does this tell me it's woo or printful?

**Comment by Ground29** [comment]
Hi, I did finally disable printful plug in after talking to them to make
sure my orders would not be effected and I still have doubles showing.

**Comment by Ground29** [comment]
I found the problem it was in settings not a plugin. Under  WooCommerce >
Settings > Products, I Changed it back to the Default Product Sorting
to Default
Setting (custom ordering + name): and it looks like all the doubles are
gone. Maybe woo can fix this because I would like to be able to use
the descending
for ordering of product.

Thanks

**Comment by mikejolley** [comment]
What was it sorting by before?

**Comment by Ground29** [comment]
Descending

**Comment by mikejolley** [comment]
Descending by what? Thats not a valid option.

**Comment by Ground29** [comment]
Short by price (desc) See attachment if needed.

**Comment by Ground29** [comment]
![screen shot 2017-11-15 at 4 18 39 am](https://user-images.githubusercontent.com/33598576/32835880-a8705eaa-c9bc-11e7-9355-fc1b988e0bf2.png)

**Comment by mikejolley** [comment]
This sorting option is working fine my end. Does it only happen on certain pages? Shop page? Category pages?

**Comment by Ground29** [comment]
It happens in shop pages and in categories. Could it be storefront theme? I was going to come back here and read if it got fixed and seen your post.
