### ISSUE TITLE
Hyphen character in order data breaking OneSaas sync

### ISSUE THREAD

**Issue by instadesign** [woocommerce/woocommerce#17725]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Connect WooCommerce site with OneSaas
2. Set up two tax rates and one product for each
3. Create an order that has both products
4. Sync with OneSaas

## Expected/actual behavior

When I follow those steps, I see hyphen characters in the order for the non-applicable tax rates, and these are passed to OneSaas causing an error.

We opened a ticket with OneSaas, this is what they say:

> We've receive an update fro our tech team regarding the order sync fails you are facing. 
This is caused by incorrect information being returned as part of tax amount on some orders. 
E.g. Order: 11017

> When we request tax info on line items we are being returned: "-" which is odd as these have a 20% tax rate applied.

`<ProductCode>2124</ProductCode>`
`<ProductName>The Original Veg Box</ProductName>`
`<Quantity>1</Quantity>`
`<Price>12.60</Price>`
`<UnitPriceExTax>10.50</UnitPriceExTax>`
`<Tax>`
`<TaxName>VAT</TaxName>`
`<TaxRate>0.2</TaxRate>`
`<TaxAmount>-</TaxAmount>`
`</Tax>`

Having just had a chat with Riaan at WooCommerce, he's identified the lines of code in WooCommerce core that are generating the hyphens:

https://github.com/woocommerce/woocommerce/blob/8dcd7f5b598109155d519d8fd79a9ac7403b1951/includes/admin/meta-boxes/views/html-order-item.php#L120

https://github.com/woocommerce/woocommerce/blob/4ec3fe61f9ba3e14195cb3b774a476a4f9c23a2d/includes/admin/meta-boxes/views/html-order-fee.php#L60

I understand the logical difference between 0 and - however I also see why OneSaas is not accepting the hyphen as a value.

Any help would be greatly appreciated.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://regather.net
Site URL: http://regather.net
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.28 (Unix) OpenSSL/1.0.2g
PHP Version: 7.0.25
PHP Post Max Size: 1 GB
PHP Time Limit: -1
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.20
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 181.68MB
Database Data Size: 127.22MB
Database Index Size: 54.46MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.44MB
wp_woocommerce_order_itemmeta: Data: 58.56MB + Index: 8.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.36MB + Index: 0.61MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.09MB + Index: 0.09MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_667d35472e_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_667d35472e_comments: Data: 0.02MB + Index: 0.08MB
wp_667d35472e_links: Data: 0.02MB + Index: 0.02MB
wp_667d35472e_options: Data: 1.52MB + Index: 0.02MB
wp_667d35472e_postmeta: Data: 0.02MB + Index: 0.03MB
wp_667d35472e_posts: Data: 0.02MB + Index: 0.06MB
wp_667d35472e_termmeta: Data: 0.02MB + Index: 0.03MB
wp_667d35472e_terms: Data: 0.02MB + Index: 0.03MB
wp_667d35472e_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_667d35472e_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_667d35472e_usermeta: Data: 0.02MB + Index: 0.03MB
wp_667d35472e_users: Data: 0.02MB + Index: 0.05MB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 10.52MB + Index: 10.09MB
wp_eg_grids: Data: 0.13MB + Index: 0.02MB
wp_eg_item_elements: Data: 0.02MB + Index: 0.02MB
wp_eg_item_skins: Data: 1.52MB + Index: 0.03MB
wp_eg_navigation_skins: Data: 0.06MB + Index: 0.02MB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wp_itsec_log: Data: 0.44MB + Index: 0.09MB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mergebot_changesets: Data: 0.02MB + Index: 0.00MB
wp_mergebot_conflicts: Data: 0.02MB + Index: 0.00MB
wp_mergebot_deployment_inserts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 7.41MB + Index: 1.50MB
wp_osapi_last_modified: Data: 0.02MB + Index: 0.00MB
wp_pmxe_exports: Data: 2.52MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 0.28MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.31MB + Index: 0.00MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.16MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 27.56MB + Index: 23.94MB
wp_posts: Data: 3.48MB + Index: 1.09MB
wp_psn_limitations: Data: 0.00MB + Index: 0.00MB
wp_psn_log: Data: 2.52MB + Index: 0.00MB
wp_psn_mail_queue: Data: 0.00MB + Index: 0.00MB
wp_psn_mail_queue_log: Data: 0.00MB + Index: 0.00MB
wp_psn_mail_templates: Data: 0.03MB + Index: 0.00MB
wp_psn_recipients_lists: Data: 0.00MB + Index: 0.00MB
wp_psn_rules: Data: 0.00MB + Index: 0.00MB
wp_r52395_node: Data: 0.02MB + Index: 0.00MB
wp_r52395_redirect301: Data: 0.02MB + Index: 0.00MB
wp_r52395_url_alias: Data: 0.02MB + Index: 0.00MB
wp_r52395_users: Data: 0.02MB + Index: 0.00MB
wp_redirection_404: Data: 1.02MB + Index: 2.31MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_redirection_logs: Data: 0.06MB + Index: 0.08MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.05MB + Index: 0.00MB
wp_revslider_slides: Data: 0.08MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.08MB + Index: 0.00MB
wp_rg_form_view: Data: 0.06MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.06MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.11MB + Index: 0.27MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_sg_action: Data: 0.02MB + Index: 0.00MB
wp_sg_config: Data: 0.02MB + Index: 0.00MB
wp_sg_schedule: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.05MB + Index: 0.03MB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wp_tg_item_elements: Data: 0.02MB + Index: 0.03MB
wp_tg_item_skins: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 2.52MB + Index: 3.03MB
wp_users: Data: 0.09MB + Index: 0.05MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wdap_collection: Data: 0.02MB + Index: 0.00MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.02MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 0.02MB + Index: 0.00MB
wp_wfHits: Data: 0.02MB + Index: 0.05MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_wfKnownFileList: Data: 0.02MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.02MB + Index: 0.03MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_bundled_itemmeta: Data: 0.08MB + Index: 0.13MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_wpgmza: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB
wp_wplnst_scans: Data: 0.02MB + Index: 0.08MB
wp_wplnst_scans_objects: Data: 0.02MB + Index: 0.05MB
wp_wplnst_urls: Data: 0.08MB + Index: 0.22MB
wp_wplnst_urls_locations: Data: 0.09MB + Index: 0.28MB
wp_wplnst_urls_locations_att: Data: 0.02MB + Index: 0.06MB
wp_wplnst_urls_status: Data: 0.14MB + Index: 0.23MB
wp_wpmelon_advbedit_temp: Data: 0.02MB + Index: 0.00MB
wp_yith_ywsbs_activities_log: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 930
bookable_resource: 8
cs_user_templates: 1
customize_changeset: 1
gift_card: 2
lshowcase: 6
mc4wp-form: 1
nav_menu_item: 85
page: 41
payment_retry: 149
post: 29
postman_sent_mail: 32
product: 82
product_variation: 311
revision: 6
scheduled-action: 662
shop_coupon: 2
shop_order: 2331
shop_order_refund: 238
shop_subscription: 401
tm_global_cp: 1
tm_product_cp: 1
tribe_events: 141
tribe_organizer: 5
tribe_rsvp_attendees: 175
tribe_rsvp_tickets: 9
tribe_venue: 5
tribe_wooticket: 219
ttshowcase: 4
wc_booking: 6
wc_user_membership: 1
wpcf7_contact_form: 1
ywsbs_subscription: 3

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (44) ###

Gravity Forms: by rocketgenius – 1.9.19.4
API KEY for Google Maps: by GeoDirectory – 1.1.0
Conditional Woo Checkout Field Pro: by Scott DeLuzio – 3.6.2 – Not tested with the active version of WooCommerce
Contact Form 7: by Takayuki Miyoshi – 4.9.1
Cornerstone: by Themeco – 2.1.6
Custom Post Type UI: by WebDevStudios – 1.5.6
Custom Related Products for WooCommerce: by Scott Nelle – 1.3 – Not tested with the active version of WooCommerce
Easy WP SMTP: by wpecommerce – 1.3.0
Essential Grid: by ThemePunch – 2.1.6.2
Event Tickets Plus: by Modern Tribe
Inc. – 4.6

Event Tickets: by Modern Tribe
Inc. – 4.6

The Events Calendar PRO: by Modern Tribe
Inc. – 4.4.19

Hotjar Connecticator: by Blue Medicine Labs – 1.1.1
iThemes Security Pro: by iThemes – 4.6.3
Logos Showcase: by Carlos Moreira – 1.4.4.1
MailChimp for WordPress: by ibericode – 4.1.11
Mergebot: by Delicious Brains – 1.1.0
PixelYourSite: by PixelYourSite – 5.0.8 – Not tested with the active version of WooCommerce
Redirection: by John Godley – 2.9.2
The Events Calendar: Filter Bar: by Modern Tribe
Inc. – 4.5.1

The Events Calendar: by Modern Tribe
Inc. – 4.6.4

UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.3.1

Cookie Consent: by Catapult_Themes – 2.3.4
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.2.8 – 1.2.9 is available – Not tested with the active version of WooCommerce
WooCommerce Deposits: by Automattic – 1.3.2 – 1.3.3 is available
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.6 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
OneSaas Connect: by OneSaas – 2.0.6.41 – Not tested with the active version of WooCommerce
WooCommerce PDF Watermark: by WooCommerce – 1.1.0 – 1.1.1 is available – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by SomewhereWarm – 5.5.2 – 5.6.0 is available
WooCommerce Royal Mail: by Automattic – 2.5.5 – Not tested with the active version of WooCommerce
WooCommerce Store Credit: by WooCommerce – 2.1.8 – 2.1.10 is available – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.2.13 – 2.2.15 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3
Yoast SEO Premium: by Team Yoast – 5.7.1
WP All Export Pro: by Soflyy – 1.4.7
WP Google Maps: by WP Google Maps – 6.4.06
WP Migrate DB Pro: by Delicious Brains – 1.8.1
WP Nag Hide: by Milton Keynes Web Design – 1.0
WP-SpamShield: by Red Sand Media Group – 1.9.21
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.8
YITH WooCommerce Anti-Fraud Premium: by YITHEMES – 1.1.1 – Not tested with the active version of WooCommerce
YITH WooCommerce Customize My Account Page: by YITHEMES – 2.2.3 – Not tested with the active version of WooCommerce
YITH WooCommerce Gift Cards Premium: by YITHEMES – 1.7.4 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #409 - /shop/
Basket: #410 - /basket/
Checkout: #411 - /checkout/
My account: #412 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: X – Child Theme
Version: 1.0.0
Author URL: http://theme.co/
Child Theme: ✔
Parent Theme Name: X
Parent Theme Version: 5.2.4
Parent Theme Author URL: http://theme.co/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: x-child/woocommerce/cart/cross-sells.php
x-child/woocommerce/content-single-product.php
x-child/woocommerce/emails/admin-new-order.php
x-child/woocommerce/emails/customer-on-hold-order.php
x-child/woocommerce/emails/customer-processing-order.php
x-child/woocommerce/loop/loop-end.php
x-child/woocommerce/loop/loop-start.php
x-child/woocommerce/loop/pagination.php
x-child/woocommerce/notices/error.php
x-child/woocommerce/notices/notice.php
x-child/woocommerce/notices/success.php
x/woocommerce/single-product/related.php
x/woocommerce/single-product/tabs/tabs.php
x/woocommerce/single-product/up-sells.php
x/woocommerce/single-product-reviews.php
x-child/woocommerce/single-product.php

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure
`
</details>

**Comment by mikejolley** [comment]
These are hyphens indicating no tax/value is applicable. This isn't your issue however - the "OneSaas Connect" plugin should format data so it is compatible. i.e. rather than send - it should send 0. Thats not under WooCommerce control. The developer of `OneSaas Connect` should resolve this.

Thanks

**Comment by PauloOneSaas** [comment]
@mikejolley Just a quick follow up on this one. 
The line item has both a valid TaxName and TaxRate associated with it. If the TaxAmount value is "-" (or 0) when the TaxRate is greater than 0, it feels like we are getting contradicting information.

From WooCommerce's perspective, does the TaxAmount trump the other 2 fields is these situations? So in the above example, since the TaxAmount is 0 do we treat it as if there is no Tax applied regardless of what TaxRate and TaxName state?

Thanks

**Comment by mikejolley** [comment]
Hi @PauloOneSaas 

Can you show what endpoint/data you're pulling? The paste from the user in the OP had several fields like `ProductCode` which are not from our API, so I'm assuming the OneSaas connect plugin is creating it's own endpoints and generating it's own data with `-`.

**Comment by instadesign** [comment]
Hi all, just to throw this in, as I think it is related (though admittedly maybe a separate issue to do with WooCommerce Subscriptions).

When I go to edit a Subscription that existed before the site had tax switched on, this is what happens:

- I hit Recalculate, and incorrect tax data comes up (in this case VAT @ 20% instead of Z @ 0%).
- I then can only get the correct tax data by removing the product(s) and re-adding it/them.

I made a gif to show this more clearly:

![ezgif-5-91f08ceffb](https://user-images.githubusercontent.com/5031353/33129489-ed60f9ae-cf87-11e7-815b-fc292e66aa2b.gif)
