### ISSUE TITLE
Fix - Fixed conflict between global attributes and custom attributes with the same names.

### ISSUE THREAD

**Issue by cbarnes353** [woocommerce/woocommerce#17720]
I keep having the issue of some of my variations on the front end disappear, but they are set on the back end.  It looks like this was resolved in 3.0.6 update, but I keep having the issue.  How can I prevent this from happening?  I can't reproduce it myself, it happens sporadically on its own.  I have the custom variation "Size".  

Example of a broken one:
https://sofydecor.com/product/4th-dimension-throw-pillows/
Should Have sizes:
14x14, 16x16, 18x18, 20x20, 26x26, 14x20

Example of a correct one:
https://sofydecor.com/product/navy-rubix-throw-pillows/

## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ X] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

WordPress environment
--
Home URL: |   | https://sofydecor.com
Site URL: |   | https://sofydecor.com
WC version: |   | 3.2.3
Log directory writable: |   | /home2/b8d8m2n2/public_html/wp-content/uploads/wc-logs/
WP version: |   | 4.8.3
WP multisite: |   | –
WP memory limit: |   | 256 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US


```
</details>

**Comment by mikejolley** [comment]
If the products are new, the only thing it could be is: 
https://github.com/woocommerce/woocommerce/pull/17629

However, I notice you have default attributes set, so non-valid combinations are hidden. If you reset, more options appear.

If combinations are missing, some of the variations in your product may be missing:

- regular price
- enabled checkbox
- OR, may be out of stock

Any of that would hide the variation from view.

Hope that helps :)

**Comment by cbarnes353** [comment]
The products are not new though.  These products have been loaded, with the variations working correctly, and then days or weeks later I find them broken.  Broken being.... not showing the variations on the front end, but still having the correct setup in the back end.


Attributes:[cid:80b39a2c-95eb-4237-8c93-e42cdb5d8262]


variations:

[cid:1e05ed16-fd97-4159-a45b-5ddac0dc0a6c]


Global:

[cid:5958b2f6-a8ed-4998-8487-c162a1a3655f]

________________________________

**Comment by mikejolley** [comment]
Check my other notes. If it's an issue with global attributes being lost, perhaps something is editing them?
