### ISSUE TITLE
Slug verification for reserved terms should use the slug to verify not the name

### ISSUE THREAD

**Issue by achadee** [woocommerce/woocommerce#17723]
using wc/v2

on this line:
https://github.com/woocommerce/woocommerce/blob/83b570e3e1ef2338985a48b5740e5dd19932b66e/includes/admin/class-wc-admin-attributes.php#L100

sending something like this:

```
{ create: [ { name: 'Type', slug: 'pa_type' } ] }
```

to 

```
/wp-json/wc/v2/products/attributes/batch
```

Still fails because it is not looking at the custom slug I have given it. Is this intentionally designed this way?

error:

```
{"create":[{"id":0,"error":{"code":"woocommerce_rest_invalid_product_attribute_slug_reserved_name","message":"Slug \"type\" is not allowed because it is a reserved term. Change it, please.","data":{"status":400}}}]}
```

**Comment by mikejolley** [comment]
> Slug "%s" is not allowed because it is a reserved term.

type is not allowed, as the error states.

```
$reserved_terms = array(
		'attachment',
		'attachment_id',
		'author',
		'author_name',
		'calendar',
		'cat',
		'category',
		'category__and',
		'category__in',
		'category__not_in',
		'category_name',
		'comments_per_page',
		'comments_popup',
		'cpage',
		'day',
		'debug',
		'error',
		'exact',
		'feed',
		'hour',
		'link_category',
		'm',
		'minute',
		'monthnum',
		'more',
		'name',
		'nav_menu',
		'nopaging',
		'offset',
		'order',
		'orderby',
		'p',
		'page',
		'page_id',
		'paged',
		'pagename',
		'pb',
		'perm',
		'post',
		'post__in',
		'post__not_in',
		'post_format',
		'post_mime_type',
		'post_status',
		'post_tag',
		'post_type',
		'posts',
		'posts_per_archive_page',
		'posts_per_page',
		'preview',
		'robots',
		's',
		'search',
		'second',
		'sentence',
		'showposts',
		'static',
		'subpost',
		'subpost_id',
		'tag',
		'tag__and',
		'tag__in',
		'tag__not_in',
		'tag_id',
		'tag_slug__and',
		'tag_slug__in',
		'taxonomy',
		'tb',
		'term',
		'type',
		'w',
		'withcomments',
		'withoutcomments',
		'year',
	);
```

**Comment by haszari** [comment]
I saw this error in the UI when importing a products csv that has a product attribute with slug `type`. I think we could make the error message clearer in this case.

<img width="1015" alt="136449279-d4769049-eb3a-48bc-81ce-02fdc7301569" src="https://user-images.githubusercontent.com/4167300/136711171-ca60fc6d-4fab-4894-9228-ec98458532de.png">

[wc-product-export-6-10-2021-1633568748015.csv.zip](https://github.com/woocommerce/woocommerce/files/7318146/wc-product-export-6-10-2021-1633568748015.csv.zip)
