### ISSUE TITLE
Incorrect Enddate on Reports

### ISSUE THREAD

**Issue by 4443** [woocommerce/woocommerce#17731]
File:
https://github.com/woocommerce/woocommerce/blob/v2.2.3/includes/admin/reports/class-wc-admin-report.php

Methode:
calculate_current_range

The range is not correctly calculated.
It misses the last Day on all range types.

Workaround: 
`$rangeArray['end_date'] += (24 * 3600) - 1;`

**Comment by 4443** [comment]
Complete Code, I use for my workaround:
`public function calculate_current_range( $current_range )
    {

        $rangeArray = [];

        switch ($current_range) {

            case 'custom' :

                $rangeArray['start_date'] = max(strtotime('-20 years'), strtotime(sanitize_text_field($_GET['start_date'])));

                if (empty($_GET['end_date'])) {
                    $rangeArray['end_date'] = strtotime('midnight', current_time('timestamp')) + (24 * 3600) - 1;
                } else {
                    $rangeArray['end_date'] = strtotime('midnight', strtotime(sanitize_text_field($_GET['end_date']))) + (24 * 3600) - 1;
                }

                $interval = 0;
                $min_date = $rangeArray['start_date'];

                while (($min_date = strtotime("+1 MONTH", $min_date)) <= $rangeArray['end_date']) {
                    $interval++;
                }

                // 3 months max for day view
                if ($interval > 3) {
                    $rangeArray['chart_groupby'] = 'month';
                } else {
                    $rangeArray['chart_groupby'] = 'day';
                }
                break;

            case 'year' :
                $rangeArray['start_date'] = strtotime(date('Y-01-01', current_time('timestamp')));
                $rangeArray['end_date'] = strtotime('midnight', current_time('timestamp')) + (24 * 3600) - 1;
                $rangeArray['chart_groupby'] = 'month';
                break;

            case 'last_month' :
                $first_day_current_month = strtotime(date('Y-m-01', current_time('timestamp')));
                $rangeArray['start_date'] = strtotime(date('Y-m-01', strtotime('-1 DAY', $first_day_current_month)));
                $rangeArray['end_date'] = strtotime(date('Y-m-t', strtotime('-1 DAY', $first_day_current_month))) + (24 * 3600) - 1;
                $rangeArray['chart_groupby'] = 'day';
                break;

            case 'month' :
                $rangeArray['start_date'] = strtotime(date('Y-m-01', current_time('timestamp')));
                $rangeArray['end_date'] = strtotime('midnight', current_time('timestamp')) + (24 * 3600) - 1;
                $rangeArray['chart_groupby'] = 'day';
                break;

            case '7day' :
                $rangeArray['start_date'] = strtotime('-6 days', strtotime('midnight', current_time('timestamp')));
                $rangeArray['end_date'] = strtotime('midnight', current_time('timestamp')) + (24 * 3600) - 1;
                $rangeArray['chart_groupby'] = 'day';
                break;
        }

        return $rangeArray;
    }`

**Comment by mikejolley** [comment]
The query for end date does +1 day so this fix/change is not needed. At least in our latest version...2.2.3 is way out of date.
