### ISSUE TITLE
Template function wc_body_class() ignores custom endpoints

### ISSUE THREAD

**Issue by MaffooClock** [woocommerce/woocommerce#17733]
The [wc_body_class()](https://github.com/woocommerce/woocommerce/blob/40fdff510c486a8c42fb1bf51df9255e2fda351b/includes/wc-template-functions.php#L262) template function uses `WC()->query->query_vars` instead of `WC()->query->get_query_vars()`, which prevents custom endpoint slugs from being added as CSS class names on the `<body>`.

This is related to issue #13178, in which PR #13179 added a new `woocommerce_get_query_vars` filter.

##
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request

**Comment by mikejolley** [comment]
cc @helgatheviking
