### ISSUE TITLE
Demorando para adicionar produto via ajax

### ISSUE THREAD

**Issue by pandacreative** [woocommerce/woocommerce#17732]
Já aconteceu com alguém isso? Clico em adicionar produto e demora muito para ele dar a mensagem de ver carrinho e atualizar o valor no carrinho, mais ou menos uns 2 a 3 segundos. O que será que pode ta acontecendo? Vlw galera abraços

Site: www.facafeira.com

**Comment by mikejolley** [comment]
> Taking time to add product via ajax

> Has anyone ever happened to that? I click on add product and it takes a lot for it to give the message of view cart and update the value in the cart, about 2 to 3 seconds. What could be happening? Vlw guys hugs

For me it took just 2 seconds to add. 

Speed could be affected by anything really; the round trip from client to server, load from plugins/theme, server power etc. I'd suggest having a search or asking other store owners if you want tips and advice. Github is here for bug reports only.

Thanks :)

**Comment by pandacreative** [comment]
Ok, obrigado.
