### ISSUE TITLE
Coupon Used Beyond Usage limit

### ISSUE THREAD

**Issue by meshal500** [woocommerce/woocommerce#17736]
Hi,

I am using WC 3.2.3 and I am having an issue with Coupons Limit. I have the limit set to 1 Usage limit per coupon. However I am able to use it many times through the API. Haven't tested it otherwise.

![couponwc](https://user-images.githubusercontent.com/3997932/32900549-c3b13b42-cafe-11e7-90d6-aa3d0a5c34a9.jpg)

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue

## WordPress Environment

`
### WordPress Environment ###

Home URL: https://www.weqaytec.com
Site URL: https://www.weqaytec.com
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: 

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.32
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.55.1
OpenSSL/1.0.2m

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 12.55MB
Database Data Size: 10.97MB
Database Index Size: 1.58MB
wp_woocommerce_sessions: Data: 0.74MB + Index: 0.08MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.01MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.09MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.03MB + Index: 0.02MB
wp_layerslider: Data: 0.18MB + Index: 0.00MB
wp_layerslider_revisions: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.99MB + Index: 0.17MB
wp_postmeta: Data: 3.47MB + Index: 0.29MB
wp_posts: Data: 0.82MB + Index: 0.06MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.12MB + Index: 0.10MB
wp_users: Data: 0.01MB + Index: 0.01MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.05MB + Index: 0.04MB
wp_wfBlocks: Data: 0.02MB + Index: 0.01MB
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 0.93MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB
wp_wfFileMods: Data: 1.55MB + Index: 0.31MB
wp_wfHits: Data: 0.53MB + Index: 0.14MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.01MB + Index: 0.00MB
wp_wfKnownFileList: Data: 0.84MB + Index: 0.10MB
wp_wfLeechers: Data: 0.03MB + Index: 0.03MB
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.01MB + Index: 0.00MB
wp_wfLogins: Data: 0.05MB + Index: 0.01MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.01MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_wfScanners: Data: 0.00MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.16MB + Index: 0.06MB
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_wpml_mails: Data: 0.29MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 84
custom_css: 1
customize_changeset: 1
nav_menu_item: 10
page: 2
post: 8
product: 13
revision: 143
shop_coupon: 203
shop_order: 44

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Admin Locale: by Louy Alakkad – 1.1
Contact Form 7: by Takayuki Miyoshi – 4.9.1
WooCommerce Coupon Generator: by Jeroen Sormani – 1.0.1 – Not tested with the active version of WooCommerce
Envato Market: by Derek Herman – 1.0.0-RC2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.4
JSON API Auth: by Ali Qureshi – 1.8
JSON API: by Dan Phiffer – 1.1.1
LayerSlider WP: by Kreatura Media – 6.6.1
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by XAdapter – 1.2.5 – Not tested with the active version of WooCommerce
Unyson: by ThemeFuse – 2.7.10
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.12

WC Product Bundles: by Saravana Kumar K – 1.0.7 – Not tested with the active version of WooCommerce
WooCommerce Cost of Goods: by SkyVerge – 2.5.0 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices: by Bas Elbers – 2.9.10
WooCommerce: by Automattic – 3.2.3
Wordfence Security: by Wordfence – 6.3.21
Yoast SEO: by Team Yoast – 5.8
WP Mail SMTP: by WPForms – 0.11.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SAR ()
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-4 (rated-4)
rated-5 (rated-5)
rated-5 (rated-5-2)

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Delicous
Version: 1.0.8
Author URL: https://www.metaphorcreations.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
WC only lets you apply coupons via the cart - there is no API for this. If you have code applying coupons yourself, your code would have to check the limits. It won't be done for you.

Thanks
