### ISSUE TITLE
WooCommerce API response has 2 empty lines at the top

### ISSUE THREAD

**Issue by sergiytravnikov** [woocommerce/woocommerce#17749]
WooCommerce API response has 2 empty lines at the top
![image001a](https://user-images.githubusercontent.com/24939917/32920694-e62ceef0-caef-11e7-8d60-1d4512850cd9.png)

**Comment by DavidAnderson684** [comment]
Look at the HTML source of your home page. Same 2 blank lines there. It's nothing to do with the WooCommerce API.

**Comment by sergiytravnikov** [comment]
I don't have home page. I call WooCommerce API method in address line of browser. It was working good 1 month ago. Now it inserts two empty lines at the top of response. We have to stop work of our web store https://hollyhillvitamins.com, because of that API bug.

**Comment by kloon** [comment]
I am not getting the same results with master or the latest release. As David mentioned this is probably caused by your theme or a plugin.

I suggest you test this with all plugins disabled except WooCommerce and also with a default theme like Storefront or Twentyseventeen.

**Comment by sergiytravnikov** [comment]
I think you misunderstand. I don't use themes, I don't use plugins. This is Web API. I execute it in address line of browser. I do not execute it at WooCoomerce web site. This is a bug of Web API method.

**Comment by sergiytravnikov** [comment]
I think you misunderstand. I don't use themes, I don't use plugins. This is Web API. I execute it in address line of browser. I do not execute it at WooCoomerce web site. This is a bug of Web API method.
Serge  

17 November 2017, 10:36:19, by Gerhard Potgieter <notifications@github.com>: 


I am not getting the same results with master or the latest release. As David mentioned this is probably caused by your theme or a plugin.

I suggest you test this with all plugins disabled except WooCommerce and also with a default theme like Storefront or Twentyseventeen.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.







---------------
Sincerely yours,
Serge Travnikov
