### ISSUE TITLE
Possible to add variable product without selecting variation

### ISSUE THREAD

**Issue by Mapteg34** [woocommerce/woocommerce#17743]
## Steps to reproduce the issue

1. Disable js
2. Go to variable product page
3. No select options, but add product to cart

## Expected/actual behavior

When I follow those steps, I add variable product to cart without options.

I was expecting to see error, sample: "Product add to cart fail because you not select options"

## Isolating the problem

This bug happens with only WooCommerce plugin active

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://www.***.com
Site URL: https://www.***.com
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.11.6
PHP Version: 7.1.5
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
***

### Post Type Counts ###

acf: 5
acf-field: 73
acf-field-group: 4
attachment: 5255
e_campaign: 2
look: 337
measurement: 47
model: 8
nav_menu_item: 15
page: 25
post: 10
product: 465
product_variation: 759
revision: 296
shop_coupon: 10
shop_order: 41
shop_order_refund: 3
simple_item: 516
video: 97
videoplayer: 1
wishlist: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.5.11
Advanced Custom Fields: by Elliot Condon – 4.4.11
All In One SEO Pack: by Michael Torbert – 2.3.12.5
All-in-One WP Migration: by ServMask – 6.40
Anti-Spam by CleanTalk: by СleanTalk  – 5.80
*** WP Plugin Ajax Cart: by Malahov Artem (***) – 1.4
***-Wordpress-Plugin-Auth: by *** – 1.1.4
Email Campaigns Composer: by *** – 0.1.8.1
Looks: by the *** – 1.5
Plugins List API: by *** – 0.0.2
CMB2: by CMB2 team – 2.2.6
Facebook for WooCommerce: by Facebook – 1.6.6 – Not tested with the active version of WooCommerce
GitHub Updater: by Andy Fragen – 7.4.3
HTML5 Video: by the *** – 1.2
Measurement: by the *** – 1.2
Members: by Justin Tadlock – 1.1.3
Models: by the *** – 1.1
PopUp by Supsystic PRO: by supsystic.com – 1.9.0
Popup by Supsystic: by supsystic.com – 1.9.12
reCAPTCHA for WooCommerce: by WPElite Plugins – 1.0.2 – Not tested with the active version of WooCommerce
WP REST API - OAuth 1.0a Server: by WP REST API Team – 0.3.0
WP REST API: by WP REST API Team – 2.0-beta15
SendGrid: by SendGrid – 1.10.7
Simple-items: by *** – 2.1.0
Simple Post Like: by the *** – 1.2
Swift Mailer: by  – 5.4.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.12.35

WC API Product Thumbnails: by *** – 0.0.4
Facebook Open Graph, Google+ and Twitter Card Tags: by Webdados – 2.1.3
WooCommerce Brands: by WooThemes – 1.5.0 – 1.5.2 is available – Not tested with the active version of WooCommerce
WooCommerce Email Verification Pro: by subhansanjaya – 1.5.8 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 3.0.7 – Not tested with the active version of WooCommerce
WooCommerce Mixpanel: by SkyVerge – 1.11.0 – 1.11.1 is available – Not tested with the active version of WooCommerce
WOOF - WooCommerce Products Filter: by realmag777 – 1.1.6.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3
YITH WooCommerce Multi Vendor Premium: by YITHEMES – 1.11.2 – Not tested with the active version of WooCommerce
YITH WooCommerce Multi Vendor Premium: by YITHEMES – 1.12.0 – Not tested with the active version of WooCommerce
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: ***
Version: 0.4.1.18
Author URL: http://***.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: ***/woocommerce/archive-product.php
***/woocommerce/cart/cart-item-data.php
***/woocommerce/cart/cart-totals.php
***/woocommerce/cart/cart.php
***/woocommerce/checkout/form-billing.php
***/woocommerce/checkout/form-checkout.php
***/woocommerce/checkout/form-pay.php
***/woocommerce/checkout/payment-method.php
***/woocommerce/checkout/payment.php
***/woocommerce/checkout/review-order.php
***/woocommerce/content-product.php
***/woocommerce/content-single-product.php
***/woocommerce/global/breadcrumb.php
***/woocommerce/global/form-login.php
***/woocommerce/global/quantity-input.php
***/woocommerce/loop/add-to-cart.php
***/woocommerce/loop/loop-end.php
***/woocommerce/loop/loop-start.php
***/woocommerce/loop/pagination.php
***/woocommerce/loop/price.php
***/woocommerce/loop/sale-flash.php
***/woocommerce/myaccount/dashboard.php
***/woocommerce/myaccount/form-add-payment-method.php
***/woocommerce/myaccount/form-edit-account.php
***/woocommerce/myaccount/form-edit-address.php
***/woocommerce/myaccount/form-login.php
***/woocommerce/myaccount/my-account.php
***/woocommerce/myaccount/my-address.php
***/woocommerce/myaccount/my-orders.php
***/woocommerce/myaccount/orders.php
***/woocommerce/myaccount/payment-methods.php
***/woocommerce/myaccount/view-order.php
***/woocommerce/notices/error.php
***/woocommerce/notices/success.php
***/woocommerce/order/order-details-customer.php
***/woocommerce/order/order-details-item.php
***/woocommerce/order/order-details.php
***/woocommerce/single-product/add-to-cart/variable.php
***/woocommerce/single-product/meta.php
***/woocommerce/single-product/price.php
***/woocommerce/single-product/product-image.php
***/woocommerce/single-product/product-thumbnails.php
***/woocommerce/single-product/short-description.php
***/woocommerce/single-product/title.php
***/woocommerce/single-product.php
</details>

**Comment by mikejolley** [comment]
@Mapteg34 Just tested this and it says you need to select options if you leave the select fields empty. Give more context/steps to reproduce or I'll have to close this :)

![hoodie local wordpress dev 2017-11-16 17-55-38](https://user-images.githubusercontent.com/90977/32907272-655328f0-caf7-11e7-82e3-ec77b3d7f739.png)

Thanks

**Comment by Mapteg34** [comment]
Problem not replay (
