### ISSUE TITLE
Woocommerce is not sending mails to end user as well as admin also. 

### ISSUE THREAD

**Issue by kundan87** [woocommerce/woocommerce#17754]
Woocommerce is not sending emails to either user while placing order or even at the time of registration of new user. Below is the woocommerce status.

`
### WordPress Environment ###

Home URL: http://jetfire.in
Site URL: http://jetfire.in
WC Version: 3.2.4
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.23
PHP Post Max Size: 512 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.4
WC Database Prefix: wpkv_
MaxMind GeoIP Database: ✔
Total Database Size: 1.31MB
Database Data Size: 1.08MB
Database Index Size: 0.23MB
wpkv_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wpkv_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB
wpkv_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpkv_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpkv_commentmeta: Data: 0.00MB + Index: 0.00MB
wpkv_comments: Data: 0.01MB + Index: 0.01MB
wpkv_links: Data: 0.00MB + Index: 0.00MB
wpkv_options: Data: 0.86MB + Index: 0.08MB
wpkv_postmeta: Data: 0.10MB + Index: 0.06MB
wpkv_posts: Data: 0.06MB + Index: 0.02MB
wpkv_termmeta: Data: 0.00MB + Index: 0.01MB
wpkv_terms: Data: 0.00MB + Index: 0.01MB
wpkv_term_relationships: Data: 0.00MB + Index: 0.00MB
wpkv_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wpkv_usermeta: Data: 0.01MB + Index: 0.01MB
wpkv_users: Data: 0.00MB + Index: 0.01MB
wpkv_wc_cancel_orders: Data: 0.02MB + Index: 0.00MB
wpkv_wpml_mails: Data: 0.00MB + Index: 0.00MB
wpkv_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wpkv_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
wpkv_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wpkv_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 25
customize_changeset: 19
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 17
page: 11
post: 5
product: 13
product_variation: 5
revision: 4
shop_coupon: 1
shop_order: 8
shop_order_refund: 1
wpcf7_contact_form: 2
yith-wcpsc-wc-chart: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (9) ###

Contact Form 7: by Takayuki Miyoshi – 4.9.1
Jetpack by WordPress.com: by Automattic – 5.5
One Click Demo Import: by ProteusThemes – 2.4.0
WC Cancel Order: by Vikram Singh – 2.4 – Not tested with the active version of WooCommerce
WooCommerce - Instamojo: by instamojo – 1.0.7 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.4
Yoast SEO: by Team Yoast – 5.8
YITH Product Size Charts for WooCommerce: by YITHEMES – 1.1.1
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #93 - /
Cart: #95 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Best Commerce
Version: 1.0.2
Author URL: https://axlethemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by kloon** [comment]
Please see the email FAQ regarding why emails would not be delivered and try the suggestions there.
