### ISSUE TITLE
product bundle error after upgrading to php 7.1 with wp version 4.9

### ISSUE THREAD

**Issue by YammYcoding** [woocommerce/woocommerce#17752]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. install wp 4.9, products bundled and php 7.1
2. click to see coupons page /wp-admin/edit.php?post_type=shop_coupon
3. error happens

## Expected/actual behavior

When I follow those steps, I see...

Fatal error: Uncaught ArgumentCountError: Too few arguments to function wcpb_product_interface::wcpb_add_product_bundle_type(), 1 passed in /public_html/www/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /public_html/www/wp-content/plugins/wc-product-bundles/classes/admin-form.php:20 Stack trace: #0 /public_html/www/wp-includes/class-wp-hook.php(286): wcpb_product_interface->wcpb_add_product_bundle_type(Array) #1 /public_html/www/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /public_html/www/wp-content/plugins/woocommerce/includes/wc-product-functions.php(500): apply_filters('product_type_se...', Array) #3 /public_html/www/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-assets.php(303): wc_get_product_types() #4 /public_html/www/wp-includes/class-wp-hook.php(286): WC_Admin_Assets->admin_scripts('edit.php') #5 /public_html/www/wp-includes/class-wp-hook.php( in /public_html/www/wp-content/plugins/wc-product-bundles/classes/admin-form.php on line 20

I was expecting to see...

the coupons list page...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by kloon** [comment]
This issue is not related to WooCommerce but the product bundles extensions. Chances are you will need to update your products bundle extension to be compatible with the latest versions.

I suggest you contact support of where you purchase the product bundles extensions. This is only for issues related to WooCommerce core.

**Comment by YammYcoding** [comment]
i tried at the plugin page, he does not reply :/

**Comment by franticpsyx** [comment]
Doesn't look like it's the official PB on woocommerce.com :)
