### ISSUE TITLE
Custom order items not displayed in subtotal

### ISSUE THREAD

**Issue by urosmil** [woocommerce/woocommerce#17758]
https://github.com/woocommerce/woocommerce/blob/885d0aa41588c79f3815e13513ce9abc997278f8/includes/abstracts/abstract-wc-order.php#L1604

Hi, I am opening this issue related to checkout page. After creating custom order items that extend order item object, there is no filter inside get_subtotal_to_display function. I suggest adding filter for overriding line items inside get_items on mention line to look like
$items = apply_filters( 'woocommerce_order_item_types', 'line_item' );
foreach ( $items as $item ) {

I also think that this should be applied all over the order class as this is the wall where you hit when creating custom product objects.

**Comment by mikejolley** [comment]
How about submitting a PR yourself instead to add a filter?

**Comment by urosmil** [comment]
Hi and thanks for your answer. I have submitted a pull request #17759 

I wanted to mention overall issue as there are a lot of places through code where only allowed value for get_items function is line_item so users that create custom product classes can't affect them. This is just one of a kind. It will solve our use case problem but it would be good to have this recorded if other users face similar issue at some point of time.

Thanks

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17759
