### ISSUE TITLE
Orders API - retrieving less orders than expected

### ISSUE THREAD

**Issue by xiangrana2** [woocommerce/woocommerce#17750]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Request using the GET method to /wp-json/wc/v2/orders?after=2017-10-31T09:00:00&before=2017-10-31T10:00:00&status=processing

## Expected/actual behavior
Expecting 16 orders with processing status created between 2017-10-31T09:00:00 and 2017-10-31T10:00:00.

Getting only 10 of them.

When I follow those steps, I see...
Only 10 orders retrieved through the API
I was expecting to see...
16 orders retrieved through the API

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by kloon** [comment]
The API paginates the results, you can pass a per_page param to return more results. See the pagination section in the API docs https://woocommerce.github.io/woocommerce-rest-api-docs/#pagination
