### ISSUE TITLE
How to call Amazon Lex chatbot functionality in my custom plugin - Wordpress

### ISSUE THREAD

**Issue by surbhi290391** [woocommerce/woocommerce#17757]
Hello,
I have a question please lets share your reviews.
I want to call Amazon Lex (Like Alexa) Chatbot functionality in my custom plugin in wordpress, please let me know how to call API's & its Paid or Free.

Thanks.

**Comment by mikejolley** [comment]
Why are you asking on the WooCommerce issue tracker?
