### ISSUE TITLE
Woocommerce Image Size BUG

### ISSUE THREAD

**Issue by edgarscr** [woocommerce/woocommerce#17751]
i have a problem updating the image size of product. when i change he said "Saved" but if i reload the page i get the default settings of woocmmerce image size. some one can help me? 

![image](https://user-images.githubusercontent.com/33737821/32922964-5508f9c0-cb0b-11e7-8a33-8dfb7c9919df.png)

i need to change to boxed size  270x270 and i can update that size's

please ?

**Comment by kloon** [comment]
Chances are your theme is overriding the settings. We have made some changes to image sizes in the upcoming 3.3 release which will hide these settings when a theme overrides them and we will also resize images when you update the settings when available to you.
