### ISSUE TITLE
How to get all variations by rest api

### ISSUE THREAD

**Issue by REA70R** [woocommerce/woocommerce#17756]
The maximum limit for one page is 100, but what if variations is more than 100 we need to use `page=2`, `page=3` and so on . lets suppose i put `per_page=100` and used page number for variation. but how can i exactly know the number of variation pages so that I can put then in loop and get all variation? I'm creating api and i need to send response as all variation of a product.

**Comment by kloon** [comment]
You can keep incrementing the page number until you receive an empty response, then you know there are no more pages to process.
