### ISSUE TITLE
Apostrophe in product search breaks nav filters (invalid characters in hrefs & form data)

### ISSUE THREAD

**Issue by MadBelette** [woocommerce/woocommerce#17762]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. On admin, build 2 products entitled "white man's shoes" and "black man's shoes"
2. On frontend, search for "Man's shoes" -> You get the result page with the 2 products
3. Click on a nav filter to filter by price or attribute -> No result found
(there are invalid characters generated in hrefs and input hidden fields)

## Expected/actual behavior

When I follow those steps, I see no result on search page.

I was expecting to see results filtered.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

Note : i'll provide a PR to propose a fix.

**Comment by mensmaximus** [comment]
The price filter widget uses `wc_query_string_form_fields()` to append the search parameter as a hidden input field to the form. `wc_query_string_form_fields()` is escaping keys and values for security reasons with `esc_attr`. The search parameter already is escaped and slashes need to be stripped.

**Comment by mikejolley** [comment]
@mensmaximus Do you want to submit a PR for this also?

If you're not comfortable with command line there is an app,  but it's quite easy once you get the hang of things anyway :)

**Comment by mensmaximus** [comment]
I'll send a PR

**Comment by MadBelette** [comment]
Hi guys,

Thx mensmaximus.
But that's not enough to fix the whole issue. We also have to fix 👍 
./includes/widgets/class-wc-widget-layered-nav.php
./includes/widgets/class-wc-widget-layered-nav-filters.php

rawurlencode( htmlspecialchars_decode( get_search_query() ) ) -> rawurlencode( htmlspecialchars_decode( get_search_query(false) ) )

**Comment by mensmaximus** [comment]
@MadBelette saw your comment to late. Sorry.

**Comment by MadBelette** [comment]
@mensmaximus. No problem! Thx for your investigations. Have a nice day
