### ISSUE TITLE
[Responsive] - WooCommerce admin area table fields

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#17761]
@jameskoster Is there any milestone/discussion set for WooCoommerce admin are to support mobile devices. Not a major design issue but some table fields need some improvement to support small screen devices first.

**Comment by jameskoster** [comment]
Not that I'm aware of. Our design team is stretched thin atm so any PR's would be appreciated ;)

**Comment by mikejolley** [comment]
Which tables specifically? Because list tables are in WP's realm.
