### ISSUE TITLE
Loop through attributes in export file (csv/xml)

### ISSUE THREAD

**Issue by ThomasVeld** [woocommerce/woocommerce#17763]
Hi,

how do I loop through the attributes in the xml/csv export?

`    "attribute_name_color" => "Color"
    "attribute_value_color" => null
    "attribute_in_variations_color" => "no"
    "attribute_is_visible_color" => "no"
    "attribute_is_taxonomy_color" => "no"
    "attribute_name_kleur" => "Kleur"
    "attribute_value_kleur" => null
    "attribute_in_variations_kleur" => "no"
    "attribute_is_visible_kleur" => "no"
    "attribute_is_taxonomy_kleur" => "no"
    "attribute_name_maat" => "Maat"
    "attribute_value_maat" => null
    "attribute_in_variations_maat" => "yes"
    "attribute_is_visible_maat" => "yes"
    "attribute_is_taxonomy_maat" => "no"
    "attribute_name_size" => "Size"
    "attribute_value_size" => null
    "attribute_in_variations_size" => "no"
    "attribute_is_visible_size" => "no"
    "attribute_is_taxonomy_size" => "no"
    "shipping_class" => null
    "image_url" => null
    "image_title" => null
    "image_caption" => null
    "image_description" => null
    "image_alt_text" => null
    "attachment_url" => null
    "product_type" => "variable"
    "tags" => null
    "productcategorieen" => "Kernboren &amp; Lassen"
    "producttags" => "Inventus|Mrinvent"
    "status" => "publish"
    "author" => 1.0
    "slug" => "variable-product"
    "format" => null
    "template" => null
    "parent_slug" => 0.0
    "order" => 0.0
    "comment_status" => "open"
    "ping_status" => "closed"
    "post_modified_date" => 20171110.0
    "downloadable" => "no"
    "virtual" => "no"
    "purchase_note" => null
    "featured" => "no"
    "weight" => 25.0
    "length" => 50.0
    "width" => 50.0
    "height" => 100.0
    "sale_price_dates_from" => null
    "sale_price_dates_to" => null
    "sold_individually" => "no"
    "manage_stock" => "yes"
    "up_sells" => 23474.0
    "cross_sells" => null
    "downloadable_files_paths" => null
    "downloadable_files_names" => null
    "download_limit" => -1.0
    "download_expiry" => -1.0
    "download_type" => null
    "button_text" => null
    "backorders" => "no"
    "tax_status" => "taxable"
    "tax_class" => "standard"
    "product_image_gallery" => null
    "default_attributes" => "a:0:{}"
    "product_attributes" => "a:1:{s:4:"maat";a:6:{s:4:"name";s:4:"Maat";s:5:"value";s:9:"S | L | M";s:8:"position";i:0;s:10:"is_visible";i:1;s:12:"is_variation";i:1;s:11:"is_taxonomy";i:0;} ▶"
    "product_version" => "3.2.1"
    "variation_description" => null
    "wc_rating_count" => "a:0:{}"
    "wc_review_count" => 0.0`

Also, the product_attributes string at the bottom does not make sense to me.
I'm working on a import function for products with custom php code.

Thanks in advance.

**Comment by mikejolley** [comment]
Why not look at the built in importer which is PHP based? We cannot help you with custom coding here-it's an issue tracker.

Thanks
