### ISSUE TITLE
Can you explain how can API depend on UI, if I execute API in address line of browser, or from javascript, or from another application, not from Woo

### ISSUE THREAD

**Issue by sergiytravnikov** [woocommerce/woocommerce#17768]
Can you explain how can API depend on UI, if I execute API in address line of browser, or from javascript, or from another application, not from Woo? Why do you close ticket if it's not solved?

What files should I check for white space?

"This is the 2nd time you opened this? Your homepage has the same blank lines which means you've probably added white space in your wp-config file or something.

view-source:https://hollyhillvitamins.com/

This is nothing to do with WooCommerce.

    I receive error in API.
    WooCommerce and WooCommerce API are absolutely different applications.

Wrong. Same codebase. Still running on WordPress.

Check your files for white space."

**Comment by mikejolley** [comment]
@sergiytravnikov You need to stop opening new issues for the same thing. Several people have told you there is white space on all pages on your site and you've been instructed to check your files and remove it. This is a problem on your install, not with WooCommerce.
