### ISSUE TITLE
API returns two empty lines at the top

### ISSUE THREAD

**Issue by sergiytravnikov** [woocommerce/woocommerce#17764]
https://hollyhillvitamins.com/wp-json/wc/v2/products/categories
https://hollyhillvitamins.com/wp-json/wc/v2/products
and other API methods return response with two empty lines at the top. 
Screenshot is attached.
![image001a](https://user-images.githubusercontent.com/24939917/32956716-2bb8cf4a-cb7f-11e7-9e20-46b757844be8.png)

Firefox browser returns error message: "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data". Response has two empty lines. 
In other browsers Response has two empty lines too. 
I tested API in browser. I don't use woocomerce for testing.
The advice to deactivate all plugins did not help.
I think you misunderstand. Plugins are working in WooCommerce. I receive error in API.
WooCommerce and WooCommerce API are absolutely different applications. API can not depend on plugins.
Just API developer has to remove empty lines from the request. It's easy to fix.
Who is an API developer? How to contact API developers?
Please, send me an email of API expert?

**Comment by mikejolley** [comment]
This is the 2nd time you opened this? Your homepage has the same blank lines which means you've probably added white space in your wp-config file or something. 

[view-source:https://hollyhillvitamins.com/](view-source:https://hollyhillvitamins.com/)

This is nothing to do with WooCommerce.

>  I receive error in API.
WooCommerce and WooCommerce API are absolutely different applications. 

Wrong. Same codebase. Still running on WordPress. 

Check your files for white space.

**Comment by sergiytravnikov** [comment]
You write: "This is nothing to do with WooCommerce.

    I receive error in API.
    WooCommerce and WooCommerce API are absolutely different applications.

Wrong. Same codebase. Still running on WordPress.

Check your files for white space."
 If it's running on WordPress, then where is source code.
WooCommerce API is a separate application. It does not depend on UI.
Why do you close that ticket, if it's not fixed?

**Comment by mikejolley** [comment]
I closed this because it's an error on your install. Read my answer - check for white space in your config files. If it was the API at fault, you wouldn't have white space at the top of your main website either! View the source to see it.
