### ISSUE TITLE
New orders not sending emails

### ISSUE THREAD

**Issue by edgarscr** [woocommerce/woocommerce#17788]
Hello, i have a problem with the new orders not sending mails to client and to owner. 

WooCommerce send status order and more but the New Orders no sending nothing. can you help me with that? 

you are free to check by yourself here: https://garaje33.com/ 

i have a sample product here too https://garaje33.com/shop/bmw/f650-gs/producto-de-prueba/

u can buy like invited user

![image](https://user-images.githubusercontent.com/33737821/32983318-1b36e2fc-cc69-11e7-8a9b-524128b8aa69.png)

please help me.

**Comment by mikejolley** [comment]
This is not a support forum.

See https://docs.woocommerce.com/document/email-faq/
