### ISSUE TITLE
Orders stuck with on-hold status

### ISSUE THREAD

**Issue by Chunkford** [woocommerce/woocommerce#17783]
Using WP 4.9

WC 3.2.4 - All orders are kept as on-hold
WC 3.1.2 - Rolling back to this version changes order to processing.

Payment Gateway Paypal Pro

I am receiving the IPN as the stock is reduced.

From the logs:
This is when using 3.1.2
```
...
2017-11-18T14:31:00+00:00 INFO Received valid response from PayPal
2017-11-18T14:31:00+00:00 INFO Found order #20129
2017-11-18T14:31:00+00:00 INFO Payment status: completed
2017-11-18T14:34:01+00:00 INFO Generating payment form for order 20130. Notify URL: http://dev.xxxxxxxxxx.com/wc-api/WC_Gateway_Paypal/
...
```

This is when using 3.2.4
```
...
2017-11-18T14:35:29+00:00 INFO Received valid response from PayPal
2017-11-18T14:35:29+00:00 INFO Found order #20130
2017-11-18T14:35:29+00:00 INFO Payment status: pending
```

With 3.2.4 it ends at `2017-11-18T14:35:29+00:00 INFO Payment status: pending` with nothing more after it.

Let me know if you need more information.

**Comment by mikejolley** [comment]
Please send this via the helpdesk since it concerns PayPal Pro. https://woocommerce.com/my-account/tickets/

Cheers

**Comment by Chunkford** [comment]
@mikejolley I'm not using the Paypal Pro plugin. That's the account I have with Paypal.
I'm using the standard Paypal options that come with WooCommerce

**Comment by mikejolley** [comment]
> Payment Gateway Paypal Pro

**Comment by Chunkford** [comment]
Sorry, I'll adjust the original message.

**Comment by mikejolley** [comment]
What do order notes say, if it's pending? Might be a reason.

**Comment by Chunkford** [comment]
For WC 3.2.4
```
<Product> stock reduced from 93 to 92.
added on 18th November 2017 at 2:31 pm Delete note

Order status changed from Pending payment to Processing.
added on 18th November 2017 at 2:31 pm Delete note

IPN payment completed
added on 18th November 2017 at 2:31 pm Delete note
```

For WC 3.1.2
```
<product> stock reduced from 57 to 56.
added on 18th November 2017 at 2:35 pm Delete note

Payment pending (multi_currency). Order status changed from Pending payment to On hold.
added on 18th November 2017 at 2:35 pm Delete note
```

The difference I have changed is the version of WC being used.

**Comment by Chunkford** [comment]
@mikejolley 
(multi_currency) was the giveaway.

I had the sandbox merchant account set up as US.
So I created another as GB and it now works.

But, there was a reason for the sandbox account setup as US.
I use a Paypal Pro and WC Subscriptions with reference transactions for Paypal payments.
But I was told by Paypal themselves that the only way to test reference transactions for card payments is to have a US account. Any other account will not work.
I have no idea if this is still the case as I haven't gotten around to testing reference transactions for card payments (I'm looking to build a payment gateway so I can use Spreedly), but from the looks of it WC does things properly now so it might cause some issues if this is still the case.

Just thought I'd let you know.

**Comment by mikejolley** [comment]
You can configure any account to auto accept currencies.

**Comment by jaydge** [comment]
This problem can happen if your paypal account's email address hasn't been confirmed yet. It happened to me with one of my clients and I spent hours before realizing that was the issue. Posting here in case it helps someone!
