### ISSUE TITLE
WC_Order::get_refunds() api_refund not recorded

### ISSUE THREAD

**Issue by alexminza** [woocommerce/woocommerce#17795]
When performing a refund from the Edit order page (either Manual or via Payment Gateway) the type of refund `api_refund` is not stored in the database and is not accessible via the `WC_Order_Refund` class members.

In result, reporting for accounting purposes cannot properly provide information on manual and payment gateways refunds in case an order has several refunds of different types.

**Comment by mikejolley** [comment]
@claudiosanches Should we add meta to indicate this in core?

**Comment by claudiosanches** [comment]
@mikejolley yes, should include meta data, and probably improve refund descriptions on order edit screen, something like `Refund #188 (Manual) - November 20, 2017, 2:21 pm by Claudio`.

**Comment by mikejolley** [comment]
Made a PR here for 3.4. https://github.com/woocommerce/woocommerce/pull/18196 Still needs tests but it will satisfy this issue.

**Comment by alexminza** [comment]
@mikejolley 'refunded_payment' field name seems confusing for 'If the payment was refunded via the API.'
