### ISSUE TITLE
Free Shipping includes Taxes.woocommerce

### ISSUE THREAD

**Issue by nhui77777777** [woocommerce/woocommerce#17797]
Free shipping requires... | Free shipping Minimum order amount so why it calculates it on tax amount too.A option should be provided so as to exclude shipping as well taxes.I was able to remove shipping but taxes still appear using woocommerce_shipping_free_shipping_is_available filter.Should see this

**Comment by mikejolley** [comment]
It goes on the displayed subtotal. If you display cart totals Inc tac, it will include the taxes in this calculation too. Change that setting, or use the filter to replace our min amount check with a custom one :)
