### ISSUE TITLE
No se graban las variaciones.

### ISSUE THREAD

**Issue by Fundasofas** [woocommerce/woocommerce#17809]
Al incluir variaciones en un producto y pulsar en el botón "Guardar variaciones" los atributos elegidos se borran.

**Comment by mikejolley** [comment]
> When you include variations in a product and click on the "Save variations" button, the chosen attributes are deleted.

https://github.com/woocommerce/woocommerce/pull/17781

**Comment by Fundasofas** [comment]
Yes. I can not introduce variations in the products because they are not recorded and they also give errors when I see them in the store. This happens since the last update was posted. Before the last update it worked well for me.

**Comment by mikejolley** [comment]
The fix is in the PR I linked to.

**Comment by Fundasofas** [comment]
Thank you very much.
