### ISSUE TITLE
Zipcode Data Validation - says invalid but it is valid zip code 

### ISSUE THREAD

**Issue by Saschaeh** [woocommerce/woocommerce#17801]
Hi there,

I have a problem when i try to checkout a product it says "Please enter a valid postcode / ZIP." I have entered a valid Spanish Barcelona zip/post code. 

Its not the theme and but it looks to be RnB plugin. I have no idea how to fix this?  Anyone had the same problem? 

Thanks,
Sascha

**Comment by mikejolley** [comment]
The validation logic in core is:

```
$valid = (bool) preg_match( '/^([0-9]{5})$/i', $postcode );
```

Barcelona use 5 digits, so this is correct and I've confirmed it's working.

Maybe that plugin has added it's own validation logic? You should contact the developer.

Thanks
