### ISSUE TITLE
Proper way to setup CTP for sale so data is stored properly

### ISSUE THREAD

**Issue by wammy21** [woocommerce/woocommerce#17816]
I've been doing research and found a number of posts about this but none that laid the whole process out.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Register a CPT as a product using `wc_register_order_type`
2. Implement WC_MyProduct, WC_MyProduct_Simple, WC_MyProduct_Data_Store_CTP, WC_Order_Item_MyProduct
3. Create custom post and set price/shipping etc. All appears to work properly.
4. On the front-end, go to custom product listing and add to cart
5. Proceed to check out.
6. After check out, on action `woocommerce_thankyou`, looping through products returns the line item to have product_id = 0.

```
<?php

class LTPWC {
    public function __construct() {
        add_action('woocommerce_thankyou', [$this, 'order_submitted']);
        add_filter('woocommerce_data_stores', [$this, 'ltp_data_store']);
        add_filter('woocommerce_product_class', [$this, 'myproduct_product_class'], 10, 4);
        add_filter('woocommerce_get_order_item_classname', [$this, 'myproduct_order_item_classname'], 10, 3);
        add_filter('woocommerce_order_line_item', [$this, 'myproduct_order_line_item'], 10, 2);
    }

    public function myproduct_order_line_item($item, $product) {
        if (is_a($product, 'WC_MyProduct_Simple')) {
            return new WC_Order_Item_MyProduct();
        } else {
            return $item;
        }
    }

    public function myproduct_order_item_classname($classname, $item_type, $id) {
        $item = new WC_Order_Item_MyProduct($id);
        $product_id = $item->get_product_id();
        if (get_post_type($product_id) == 'myproduct') {
            return 'WC_Order_Item_MyProduct';
        } else {
            return $classname;
        }
    }

    public function myproduct_product_class($classname, $product_type, $post_type, $product_id) {
        if (get_post_type($product_id) == 'myproduct') {
            $classname = 'WC_MyProduct_Simple';
        }
        return $classname;
    }

    public function ltp_data_store($stores) {

        $stores['myproduct'] = 'WC_MyProduct_Data_Store_CPT';

        return $stores;
    }

    public function order_submitted($order_id) {
        $order = wc_get_order($order_id);
        //Items are WC_Order_Item_Product, instead of WC_Order_Item_MyProduct, product_id is 0
        foreach ($order->get_items() as $item) {
            
            $product = $item->get_product();

            print_r($product); // returns false
            if ($product !== false) {
                //do something with product (notifications,etc)
            }
        }
    }

}

```

## Expected/actual behavior

I am expecting to be able to reference the product_id from the items in order_sumitted

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

From current dev environment
```
Home URL: 
Site URL: 
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.25 mod_wsgi/4.4.21 Python/3.5.2
PHP Version: 5.6.25
PHP Post Max Size: 420 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.50.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.6.31
Max Upload Size: 400 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 4.08MB
Database Data Size: 2.73MB
Database Index Size: 1.35MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.06MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.05MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.08MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.05MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.14MB + Index: 0.05MB
wp_postmeta: Data: 0.25MB + Index: 0.25MB
wp_posts: Data: 0.20MB + Index: 0.06MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.03MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 7
breed: 1
litter: 1
nav_menu_item: 11
page: 20
parent: 5
post: 2
puppy: 8
review: 9
revision: 32
shop_coupon: 1
shop_order: 57

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (13) ###

ManageWP - Worker: by ManageWP – 4.2.25
Gravity Forms: by rocketgenius – 2.2.5
Email Templates: by Damian Logghe – 1.2
Gravity Forms - Placeholders add-on: by Joan Piedra – 1.2.1
Show Current Template: by JOTAKI Taisuke – 0.3.0
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.3.1

Community Finance: by Community Finance – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.8.2 – Not tested with the active version of WooCommerce
WooCommerce Shipping Per Product v2: by WooThemes – 2.2.10 – Not tested with the active version of WooCommerce
WooCommerce Custom Post Type Manager: by Reigel Gallarde – 3.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3 – 3.2.4 is available
Yoast SEO: by Team Yoast – 5.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #105 - /shop/
Cart: #106 - /cart/
Checkout: #107 - /checkout/
My account: #41 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: UnderStrap Child
Version: 0.3.2
Author URL: http://www.holgerkoenemann.de
Child Theme: ✔
Parent Theme Name: UnderStrap
Parent Theme Version: 0.6.5
Parent Theme Author URL: http://www.holgerkoenemann.de
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: understrap/woocommerce/archive-product.php
understrap-child/woocommerce/cart\cart-empty.php
understrap-child/woocommerce/cart\cart.php
understrap-child/woocommerce/cart\mini-cart.php version 3.1.0 is out of date. The core version is 3.2.0
understrap/woocommerce/cart\proceed-to-checkout-button.php
understrap/woocommerce/checkout\form-checkout.php
understrap/woocommerce/checkout\form-coupon.php
understrap/woocommerce/checkout\form-pay.php
understrap/woocommerce/checkout\payment.php
understrap/woocommerce/global\form-login.php
understrap/woocommerce/global\quantity-input.php version 3.1.0 is out of date. The core version is 3.2.0
understrap/woocommerce/global\wrapper-end.php
understrap/woocommerce/global\wrapper-start.php
understrap/woocommerce/loop\add-to-cart.php
understrap/woocommerce/loop\orderby.php
understrap/woocommerce/myaccount\downloads.php version 3.1.0 is out of date. The core version is 3.2.0
understrap/woocommerce/myaccount\form-edit-account.php
understrap-child/woocommerce/myaccount\form-edit-address.php
understrap-child/woocommerce/myaccount\form-login.php version 2.6.0 is out of date. The core version is 3.2.0
understrap/woocommerce/myaccount\form-lost-password.php
understrap/woocommerce/myaccount\form-reset-password.php
understrap/woocommerce/myaccount\my-address.php
understrap/woocommerce/myaccount\my-orders.php
understrap-child/woocommerce/myaccount\navigation.php
understrap/woocommerce/myaccount\orders.php version 3.1.0 is out of date. The core version is 3.2.0
understrap/woocommerce/product-searchform.php
understrap/woocommerce/single-product\add-to-cart\simple.php
understrap/woocommerce/single-product\add-to-cart\variation-add-to-cart-button.php
understrap-child/woocommerce/single-product\product-thumbnails.php
understrap-child/woocommerce/single-product\rating.php
understrap-child/woocommerce/single-product\review-rating.php
understrap/woocommerce/single-product\short-description.php

Outdated Templates: ❌Learn how to update
```
</details>

**Comment by wammy21** [comment]
Aside from some stackoverflow posts, the most I found was #14302

**Comment by mikejolley** [comment]
@wammy21 It's impossible to know why product ID is 0 from your example -  I have no idea what is inside `WC_Order_Item_MyProduct` or what it extends. Also have no idea what `WC_MyProduct_Simple` is doing... This is all from your custom plugin so listing it in "Steps to reproduce the issue" does not help us :)

Your custom data store needs to store a 'product ID' somewhere, read it, and pass it to your `WC_Order_Item_MyProduct` class. Without doing this, it will of course be 0 as no data would have been read.

You can refer to our data stores to see how this is done in core. 

Product line item object: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order-item-product.php

Product line item data store:
https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-order-item-product-store.php

Product ID is stored as meta data https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-order-item-product-store.php#L53

If you're extending products (not sure why a CPT would be needed for that) you won't need new line items and line item data stores because the existing classes will handle it.

If you do need your custom store, maybe add some debugging inside it to know if it's actually being used/called, and check your DB to ensure that meta is being set (if thats how you choose to store the data in the data store - thats your choice).

I appreciate you may be stuck with this, but this is not a support forum. The process will have only been 'laid out' if someone coded a solution like yours and shared it with the world. We don't have pre-made examples for this type of customisation...we've just provided the hooks and made sure things can be extended where needed.

Good luck with this and if you do find the existing hooks lacking, feel free to submit a PR for consideration :)

Thanks

**Comment by wammy21** [comment]
@mikejolley I appreciate your response. 

I understand product_id is stored as metadata, I went down the road of implementing the WC_ classes when I originally encountered the problem, and after doing research which lead me to #14302 I thought perhaps I was not implementing the CTP properly,, even then I am extending off the same base classes as WC Product (etc) and changing the methods that have hard coded references to 'product' as the post_type. (leaving the rest as is)

> If you're extending products (not sure why a CPT would be needed for that) you won't need new line items and line item data stores because the existing classes will handle it.

Even without all of that, my original issue was the a custom post type (say in my instance 'puppy') even if I properly enable it for WC (via `wc_register_order_type` which I believe is the way to do it?) I was still getting product_id = 0; (it is also 0 in the order item meta table). 

I appreciate you pointing me to the classes, I have already read through them before I submitted this. I understand this is not a support forum, I did not feel this was a support request as I am asking for the proper way to use the APIs, not how to use the cart itself. If there is another venue on how to get this information please let me know. I've been fighting with this for two weeks, attempting different methods I have found online on how to make this work but in the end I am still left with an empty product_id at checkout.

I appreciate that the class files in WC are documented, but that doesn't help from the outside if I don't know how to use them. Is there any other documentation you could point me to that could help me figure this out?

**Comment by mikejolley** [comment]
@wammy21 I think you're looking a the wrong thing if using `wc_register_order_type`. Those are for **orders** e.g. subscriptions uses it for subscription orders. These are not for **products**.

**Comment by wammy21** [comment]
@mikejolley Understood, one of those things I added after encountering the original problem based on what I found. I am just at a loss on how to proceed.

**Comment by mikejolley** [comment]
What are you actually trying to accomplish?

**Comment by wammy21** [comment]
@mikejolley I have a CPT that we are selling through WC, after the order is submitted I need to update/change some meta on the CPT, but when I loop through the order items, the item that has the CPT has product_id set to 0 (same in the DB, etc) so I can't reference back to the original CPT to update meta. 

As I've been reading it seems that with the info from the pull request I reference before, and some other documentation I found on the wiki on here, I am going to have to implement my own data stores as the default ones check for post_type == product, which I believe is why the meta is not being saved in the order line item. 

Everything else so far appears to work fine with the CPT as a product, except the checkout.

**Comment by wammy21** [comment]
@mikejolley I think I was able to figure it all out. I am still testing but this seems to have done it, please let me know if I am doing anything incorrectly or if there is a better way.

I essentially copied the WC_ classes changing the references from 'product' to 'myproduct' on post_type

Implement `WC_MyProduct` (from WC_Product)
Implement `WC_MyProduct_Data_Store_CPT` (from WC_Product_Data_Store_CPT)
Implement `WC_MyProduct_Simple` (from WC_Product_Simple)
Implement `WC_Order_Item_MyProduct` (from WC_Order_Item_Product)

Setup the data store via `woocommerce_data_stores` filter
Setup the product class via `woocommerce_product_class` filter
Setup the order item class via `woocommerce_get_order_item_classname` filter
Setup the new order item via `woocommerce_checkout_create_order_line_item_object` filter
Setup the items key via `woocommerce_get_items_key` filter.

With all of this in place I was able to properly purchase my CPT product and properly reference it on `woocommerce_thankyou` action. 

Here is how I implemented the filters:

```php
class LTPWC {

    public function __construct() {
        add_action('woocommerce_thankyou', [$this, 'order_submitted']);
        add_filter('woocommerce_data_stores', [$this, 'ltp_data_store']);
        add_filter('woocommerce_product_class', [$this, 'myproduct_product_class'], 10, 4);
        add_filter('woocommerce_get_order_item_classname', [$this, 'myproduct_order_item_classname'], 10, 3);
        add_filter('woocommerce_checkout_create_order_line_item_object', [$this, 'myproduct_order_line_item'], 10, 4);
        add_filter('woocommerce_get_items_key', [$this, 'order_item_key'], 10, 2);
    }

    public function order_item_key($default, $item) {
        if (is_a($item, WC_Order_Item_MyProduct)) {
            return 'line_item';
        }
        return $default;
    }

    public function myproduct_order_line_item($item, $cart_item_key, $values, $order) {

        if (is_a($values['data'], WC_MyProduct_Simple)) {
            return new WC_Order_Item_MyProduct();
        } else {
            return $item;
        }
    }

    public function myproduct_order_item_classname($classname, $item_type, $id) {
        $item = new WC_Order_Item_MyProduct($id);
        $product_id = $item->get_product_id();
        if (get_post_type($product_id) == 'myproduct') {
            return 'WC_Order_Item_MyProduct';
        } else {
            return $classname;
        }
    }

    public function myproduct_product_class($classname, $product_type, $post_type, $product_id) {
        if (get_post_type($product_id) == 'myproduct') {
            $classname = 'WC_MyProduct_Simple';
        }
        return $classname;
    }

    public function ltp_data_store($stores) {
        $stores['myproduct-simple'] = 'WC_MyProduct_Data_Store_CPT';
        return $stores;
    }

    public function order_submitted($order_id) {
        $order = wc_get_order($order_id);
        foreach ($order->get_items() as $item) {
            $product = $item->get_product();
            if ($product !== false && get_post_type($product->get_id()) == 'myproduct') {
                //Update CPT meta and other actions here. 
            }
        }
    }
}
```

One thing I was thinking while going through all of this is this: If using another CPT as a product is essentially the same as WC using 'product'. If the WC_* classes had a property for $post_type, it would be much easier to extend the WC_* classes and just set the $post_type without having to re-implement everything, it would also make it easier to have a $data_store_key property perhaps. Would have been much easier to do something like:

```php
class WC_MyProduct extends WC_Product {
    function __construct($product = 0) {
        //set post_type and data_store_key

        $this->post_type = 'myproduct';
        $this->data_store_key = 'myproduct-simple';
        //WC_Product constructor could check if $this->data_store_key is set and use that instead of the default?
        parent::__construct($product);
    }
}
````

Same thing would apply to WC_Product_Data_Store_CPT ($post_type property).

I did notice that some classes (I think it was WC_Product, but maybe it was the datastore) have a protected $post_type property, but I didn't see that this was being used.

If this is something that would be considered I can make an attempt to implement this and submit a PR.

**Comment by mikejolley** [comment]
The thing I don't understand is why that CPT was needed instead of extending products themselves.  I don't think adding post type args to the data stores would be a good idea because it would cause difficulties down the line when we move to custom tables (I think).
