### ISSUE TITLE
multiple issues with new orders - showing as cancelled and stock levels not changing. 

### ISSUE THREAD

**Issue by Lynchie48** [woocommerce/woocommerce#17819]
I'm using Woo Commerce 3.2.4 and word press 4.9

When a new order comes in it

1:  is showing as order cancelled - I manually have to change to processing or cancelled
2: stock levels don't decrease with any new order, I have manage stock ticked at both points (in variable product and at the main page)
3: I am not receiving new customer emails (with customer shipping info), the notification I receive is a paypal notification
4: my customers aren't getting any emails from me with updates on their orders.

I use PayPal (no plug ins)

I'm not technical and understand the fault might be with PayPal but I don't know what to do to change it.   This all worked fine a few months ago.
Any ideas???

**Comment by mikejolley** [comment]
All of these will be related to IPN. See https://docs.woocommerce.com/document/paypal-standard/#section-21

You can also try https://github.com/woocommerce/woocommerce/pull/17800/files which may be related but unsure yet.

**Comment by mikejolley** [comment]
Ignore that PR link, it doesn't apply to 3.2.

The IPN doc should be all you need. Remember you can also enable PDT if IPN doesn't work on your server.

Thanks
