### ISSUE TITLE
Fees Tax Class Not Displayed

### ISSUE THREAD

**Issue by whatthefork** [woocommerce/woocommerce#17815]
When fees are added to the cart they can be set as taxable and a tax class can be assigned. This works fine, and on the cart and checkout pages the fees and associated taxes display. When the order is written into the database the fee and tax class are recorded. 

BUT, when the shoppers lands on the Thank You page the fee displays but its fee tax and its tax class label don't display. Nor does that information display in the order details when viewed in the admin area. 

This is on a site running 3.2.4 with taxes set to display as itemized.

**Comment by mikejolley** [comment]
> fee tax and its tax class label don't display

What are you talking about here? Provide a screenshot - I wasn't aware tax classes were shown to users!

**Comment by mikejolley** [comment]
@whatthefork

**Comment by whatthefork** [comment]
Apologies if I wasn't clear enough. Tax class is probably the wrong way to explain what's not appearing. 

I'm referring to the tax amount and tax label associated when associated with a fee. For example, I create a new tax class in the admin area WC settings and call it "XYZ" (for sake of example), then in that class I add taxes with labels. Then, in my code, when adding a fee to the cart I specify that the fee is taxable and has a tax class of XYZ. WC calculates the taxes correctly and the tax appears in the cart and checkout order review. But the tax and label do not appear in the order details of the order receipt email, nor the thank you page order review, nor the in the order details as seen in the admin area. The overall totals are correct though.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17835
