### ISSUE TITLE
No ALT text on Single Product Page thumbnails.

### ISSUE THREAD

**Issue by webprom** [woocommerce/woocommerce#17824]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. go to single product page
2. check source of product thumbnails 
3. no ALT text on images!

## Expected/actual behavior

When I follow those steps, I see...
There is no alt text
I was expecting to see...
ALT text on thumbnails was present before version 3

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
`
### WordPress Environment ###

Home URL: https://www.caspicards.com
Site URL: https://www.caspicards.com/art
WC Version: 3.2.4
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.25
PHP Post Max Size: 25 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.55.1
OpenSSL/1.0.2m

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.4
WC Database Prefix: wp_
Total Database Size: 56.93MB
Database Data Size: 44.31MB
Database Index Size: 12.62MB
wp_woocommerce_sessions: Data: 0.66MB + Index: 0.03MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.22MB + Index: 0.12MB
wp_woocommerce_order_itemmeta: Data: 1.45MB + Index: 1.06MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.09MB + Index: 0.07MB
wp_comments: Data: 0.60MB + Index: 0.27MB
wp_groups_capability: Data: 0.01MB + Index: 0.02MB
wp_groups_group: Data: 0.00MB + Index: 0.00MB
wp_groups_group_capability: Data: 0.00MB + Index: 0.00MB
wp_groups_user_capability: Data: 0.00MB + Index: 0.00MB
wp_groups_user_group: Data: 0.00MB + Index: 0.01MB
wp_itsec_lockouts: Data: 0.00MB + Index: 0.00MB
wp_itsec_log: Data: 0.00MB + Index: 0.00MB
wp_itsec_temp: Data: 0.03MB + Index: 0.03MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 6.18MB + Index: 0.55MB
wp_postmeta: Data: 17.96MB + Index: 4.12MB
wp_posts: Data: 2.52MB + Index: 0.51MB
wp_relevanssi: Data: 2.03MB + Index: 2.78MB
wp_relevanssi_log: Data: 0.00MB + Index: 0.00MB
wp_relevanssi_stopwords: Data: 0.01MB + Index: 0.01MB
wp_slp_extendo_meta: Data: 0.00MB + Index: 0.00MB
wp_slp_rep_query: Data: 0.64MB + Index: 0.02MB
wp_slp_rep_query_results: Data: 0.22MB + Index: 0.32MB
wp_smush_dir_images: Data: 0.06MB + Index: 0.06MB
wp_store_locator: Data: 0.04MB + Index: 0.41MB
wp_termmeta: Data: 0.03MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.05MB
wp_term_relationships: Data: 0.17MB + Index: 0.31MB
wp_term_taxonomy: Data: 0.04MB + Index: 0.02MB
wp_unitegallery_categories: Data: 0.02MB + Index: 0.00MB
wp_unitegallery_galleries: Data: 0.02MB + Index: 0.00MB
wp_unitegallery_items: Data: 0.05MB + Index: 0.00MB
wp_usermeta: Data: 0.61MB + Index: 0.32MB
wp_users: Data: 0.03MB + Index: 0.04MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.07MB + Index: 0.06MB
wp_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 0.23MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.01MB + Index: 0.01MB
wp_wfFileMods: Data: 5.53MB + Index: 0.89MB
wp_wfHits: Data: 0.50MB + Index: 0.11MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.03MB + Index: 0.00MB
wp_wfKnownFileList: Data: 3.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.07MB + Index: 0.07MB
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.00MB + Index: 0.00MB
wp_wfLogins: Data: 0.12MB + Index: 0.03MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.06MB + Index: 0.02MB
wp_wfScanners: Data: 0.01MB + Index: 0.01MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.08MB + Index: 0.04MB
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_xyz_cfm_form: Data: 0.09MB + Index: 0.00MB
wp_xyz_cfm_form_elements: Data: 0.02MB + Index: 0.00MB
wp_xyz_cfm_sender_email_address: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 3012
global_product_addon: 11
nav_menu_item: 89
page: 34
post: 22
product: 795
product_variation: 1408
question: 19
revision: 19
shop_coupon: 22
shop_order: 885
shop_order_refund: 1
sidebar: 3
sm-location: 2
vtmin-rule: 1
wishlist: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Akismet Anti-Spam: by Automattic – 4.0.1
Anti-spam: by webvitaly – 4.4
iThemes Security: by iThemes – 6.7.0
Contact Form Manager: by xyzscripts.com – 1.4.5
Email Encoder Bundle - Protect Email Address: by Victor Villaverde Laan – 1.4.6
Envato Market: by Derek Herman – 1.0.0-RC2
Homepage Control: by WooThemes – 2.0.2
Complete Analytics Optimization Suite (CAOS): by Daan van den Bergh – 1.44
Imagify: by WP Media – 1.6.13.1
VarkTech Minimum Purchase for WooCommerce: by Vark – 1.09.81
Relevanssi: by Mikko Saari – 3.6.2.2
Optimize Database after Deleting Revisions: by CAGE Web Design | Rolf van Gelder
Eindhoven
The Netherlands – 4.4.1

Store Locator Plus: by Store Locator Plus – 4.8.7
Storefront Footer Bar: by WooThemes – 1.0.3
Unite Gallery: by Valiano – 1.7.44
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.12

User Role Editor: by Vladimir Garagulya – 4.37
W3 Total Cache: by Frederick Townes – 0.9.5.4
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.2
WooCommerce MailChimp: by Saint Systems – 2.1.2 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 2.9.0 – Not tested with the active version of WooCommerce
WooCommerce UPS Shipping: by WooCommerce – 3.2.6
WooCommerce Show Attributes: by Isabel Castillo – 1.6.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.4
WooSidebars: by WooThemes – 1.4.3
Wordfence Security: by Wordfence – 6.3.21
WordPress FAQ Manager: by Andrew Norcross – 1.331
Yoast SEO: by Team Yoast – 5.8
WP Font Awesome Share Icons: by Spyros Vlachopoulos – 1.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Judaica2
Version: 2.0.0
Author URL: http://www.web-design.co.il
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
Same as https://github.com/woocommerce/woocommerce/issues/15564#issuecomment-307751904 Alt text is present, you just won't see it in the gallery slider thumbnails when inspecting markup - that is generated dynamically by FlexSlider.

My screenshot link is dead in that issue, but you can view your page source to confirm. Look for the `woocommerce-product-gallery__wrapper`.

If the alt text tag is still empty even there, go to the media library, click the image, and ensure the 'alt text' field actually has a value.

Thanks :)

**Comment by webprom** [comment]
Besides code it was a helpful addition to users, they were able to see the alt text in browser in previous version :( Any way to add it there as ALT or title?

**Comment by mikejolley** [comment]
FlexSlider doesn't support it in the gallery view it renders. It's all powered by JavaScript.

**Comment by webprom** [comment]
I see, maybe you can update flexslider in the future, it's now owned by woocommerce :)

**Comment by mikejolley** [comment]
Yup :) But I'm not sure how important that is, as I said, the alt text is in the markup anyway :) SEO etc is unaffected which was a concern of some.

**Comment by laptopleon** [comment]
(It took me quite a while to find this.) I struggle with this too. Google looks further than just the HTML / other code. For example it evaluates if text is visible and to what degree. For example: Is it white on an almost white background or is it in big, bold letters with a lot of contrast?

The fact that the alt tag is in the HTML does not automatically mean Google is valuing it the same as a page where is actually rendered. I'm trying to find out more about this but it's hard.

I would very much appreciate it if it would just render like it's supposed to. Even if it was just for people who have a hard time seeing images.

**Comment by laptopleon** [comment]
It look like this can be fixed by adding the right alt tag text to the zoomImg class instance that floats above the actual image on hover.

**Comment by laptopleon** [comment]
You are right, so I made a request for [FlexSlider](https://github.com/woocommerce/FlexSlider/issues/1718).

**Comment by Ooops-404** [comment]
@mikejolley  
I agree that this _should not_ have any toll to the SEO BUT fact is that even Google website audit tools flag those images as missing the alt text, so one wonders how that plays out with Google algorithm. If we go by Google own audit tools, then I'd say that it does take a toll to SEO.

Plus that's not all, website owners are getting more and more aware of the free (and commercial) website auditors that are all around the web, and when they look at those warnings they get pissed, and they don't' accept an "it shouldn't be of concern because it's in the source code anyway".

:(
