### ISSUE TITLE
How to create api with out verify consumerkey

### ISSUE THREAD

**Issue by nhoctanker** [woocommerce/woocommerce#17832]
Hi to day i try install plugin rest-api ( wordpress ) . And write new api update status order without consumerkey . Current i using Bearer token to auth . But when using method PUT . we not get anything params request . But if i using consumer_key that working . Please give me exmple

 I have router  PUT /wc/mybase/orders/{id}/update-status

**Comment by mikejolley** [comment]
Supported auth is explained here https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication

You can add additional plugin based methods if needed. We don't support this directly. 

If certain methods like PUT are not working, the server may lack support. See https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#server-does-not-support-postdeleteput

Thanks
