### ISSUE TITLE
Flat Rate Shipping Doubled

### ISSUE THREAD

**Issue by vmarsman** [woocommerce/woocommerce#17830]
## Prerequisites

- [ X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. http://www.paulettebodeman.com/product/open-to-grace-card-deck/
2. Click Add to Cart
3. Click View Cart

## Expected/actual behavior

When I follow those steps, I see... flat rate shipping as $14.40

I was expecting to see... flat rate shipping as $7.20 (with per order setting)

## Isolating the problem

- [ X ] This bug happens with only WooCommerce plugin active
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X ] I can reproduce this bug consistently using the steps above
- [ X ] Tried Changing settings to Per Order vs. Per Class
![screenshot_2](https://user-images.githubusercontent.com/15950040/33050778-da40d688-ce23-11e7-9db5-cfe435ad6883.png)
![screenshot_3](https://user-images.githubusercontent.com/15950040/33050779-da525f48-ce23-11e7-9ed9-6fc9c614ef32.png)

## WordPress Environment

<details>
```
Home URL: |   | http://www.paulettebodeman.com
-- | -- | --
Site URL: |   | http://www.paulettebodeman.com
WC version: |   | 3.2.4
Log directory writable: |   | /home/pbcpanel15/public_html/wp-content/uploads/wc-logs/
WP version: |   | 4.9
WP multisite: |   | –
WP memory limit: |   | 512 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en
```
</details>

**Comment by mikejolley** [comment]
You've set two prices; both 7.20 so it's not really doubled, it's just summing the costs input. 

Set the 'cost' field to 0 if you just want to base it on shipping class.

**Comment by vmarsman** [comment]
I don't think it's suppose to "sum" the costs when the setting is "per order: charge shipping for highest..."? I guess I may just be misunderstanding the documentation? Perhaps when the items are the same price then it will keep summing? Still seems like a flaw, should have an option to only charge shipping once in case you have items in the cart with different classes that are the same price.

**Comment by mikejolley** [comment]
The class costs are separate to the main cost. As I said, set the main cost to 0 to just use those down the bottom.

**Comment by izakman** [comment]
This just tripped me up as well. Spent ages trying to figure out what was going on :)  Not sure if the docs or the description in the admin make this clear enough.

**Comment by hightreeR** [comment]
Same issue here! I spent a week figuring out what was going on. Weird thing though: when using multilingual plugins (Polylang and WPML), the costs only doubled for primary languages...
