### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by addedlovely** [woocommerce/woocommerce#17837]
What are the plans for GDPR compliance?

This seems like a wider issue that affects WordPress as a whole, rather than WooCommerce - but was wandering if there was any planning taking place at an Automattic level.

Reading the ICO's (UK body) [guideance](https://ico.org.uk/for-organisations/data-protection-reform/guidance-what-to-expect-and-when/) it seems there would need to be a few changes:

- **Consent** - 'There must be a positive opt-in – consent cannot be inferred from silence, pre- ticked boxes or inactivity. It must also be separate from other terms and conditions, and you will need to have simple ways for people to withdraw consent. Public authorities and employers will need to take particular care. Consent has to be verifiable and individuals generally have more rights where you rely on consent to process their data." - _would assume this would mean another checkbox on the checkout flow in addition to the terms and conditions checkbox._

- **Individuals’ rights** - 'You should check your procedures to ensure they cover all the rights individuals have, including how you would delete personal data or provide data electronically and in a commonly used format'  - Rights: erasure / restrict processing / data portability / not to be subject to automated decision-making including profiling - _would assume here a tool to delete / download data and a role / setting on a user for their preference in terms of automated decision making._

At a broader level, can't help but think this needs managing at the WordPress level, via an API that plugins hook into and respect to access user data. This could then be used to generate audit logs, pass data with users rights respected and then help with deletion requests.

Apologies if this is the incorrect place for the query, but couldn't find any GPDR posts on the ideas board, and forum [posts](https://wordpress.org/support/topic/woocommerce-gdpr/) seem to go unanswered. Also Ipstenu [suggests](https://wordpress.org/ideas/topic/gdpr) this be resolved by plugins, but my initial thoughts would be this should be handled in core.  The only [plugin](https://wordpress.org/plugins/wp-gdpr-compliance/) I can find is about offering guideance. 

Thanks.

Ian.
[preparing-for-the-gdpr-12-steps.pdf](https://github.com/woocommerce/woocommerce/files/1491257/preparing-for-the-gdpr-12-steps.pdf)

## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)

**Comment by mikejolley** [comment]
Hi Ian,

Automattic are investigating this themselves (https://en.support.wordpress.com/automattic-gdpr/). It's likely that as this develops, guidance for site and store owners will be shared and posted. We've already discussed what core, plugins and services store and this is being looked over by legal.

For eCommerce, there are posts appearing like this one https://www.e-xanthos.co.uk/blog/gdpr-means-ecommerce-businesses-prepare-2018/ It mainly explains what store owners need to do.. privacy policies, opt-in vs opt-out etc. Reminds me of the cookie policies people were worried about a few years ago :) Looks similar to the plugin you found - guidance only.

To answer the question "What are the plans for GDPR compliance?" - we'll let the legal team do their due diligence, and then review if changes or extra tools are needed, or see in what ways we can help.

Right now from the code side, to my knowledge no action is required. Self-hosted stores are responsible for their own data and business practices. IANAL though :) 

p.s. closing this as it's not a code related issue, yet. Will pass it on just so others are aware concerns are growing.

**Comment by addedlovely** [comment]
@mikejolley Thanks for the update Mike. Good to hear Automattic are working on this.

Another user just posted this on the .org forums, looks like a great idea:
[https://www.gdprwp.com/](https://www.gdprwp.com/)

**Comment by Shantel444** [comment]
Nice thread and useful links! Thanks for sharing, guys! I'm also interested in this question and found a good article on [https://diceus.com/gdpr-compliance-top-agenda-2018/](https://diceus.com/gdpr-compliance-top-agenda-2018/) that explains much on this topic. In short, firm demands of the upcoming legal rules include limiting the goals of information gathering and measuring, and minimizing individual data treatment. But we have time as companies must be able to show compliance by May 25, 2018.

**Comment by dougaitken** [comment]
To add to @Shantel444's comment. 

Anyone coming here after searching the repo, we have started to post blog updates about WooCommerce and GDPR, have a look at the tag from time to time - https://woocommerce.com/tag/gdpr/ - or follow the blog for more great news.

**Comment by robin-scott** [comment]
Just got a link to this dropped to me by someone on Slack. Since this was posted (I know, its closed, but ppl are landing here) quite a lot more has happened on the GDPR in relation to WordPress and WooCommerce.

There's an effort happening on both to assist sites to become compliant.

It is up to the webmaster him or herself ultimately, but understanding the basic parameters is a good place to start. We posted the following for devs and site owners at Silicon Dales:

https://silicondales.com/whitepapers/silicon-dales-guide-gdpr/

The WordPress effort is going on apace too, and there's a working group setup there too, see here:

https://wordpress.org/news/2018/04/gdpr-compliance-tools-in-wordpress/

Also see this Github which contains lots of links and also roadmaps and other stuff about what's coming:

https://wordpress.org/news/2018/04/gdpr-compliance-tools-in-wordpress/

I would encourage anyone interested in helping to join the chat on the WP slack, where you will also see a few WooCommerce faces, who can help guide where things are happening this side too.... Hope this helps anyone looking for actual info on GDPR escape some FUD today.

**Comment by HelenB13** [comment]
I don't know much about GDPR, but I remember that it was about to be enforced, all business owners worried about the compliance as in case of non-compliance with new requirements, they would be slapped with a fine of 4% of annual turnover. Thanks for sharing this info and enlightening me!
