### ISSUE TITLE
Disable Coupon

### ISSUE THREAD

**Issue by shreyans94** [woocommerce/woocommerce#17839]
I can trash a coupon but not deactivate or disable it.

My coupons are restricted to single use by a user only. If I delete it and recreate, then those coupon stats will be lost forever. No way to temporarily deactivate it without losing coupon stats

**Comment by claudiosanches** [comment]
![screenshot from 2017-11-21 11-10-05](https://user-images.githubusercontent.com/1264099/33074227-8cfdeee0-ceac-11e7-9e2c-db395a360fad.png)

Just use Coupon usage limit options.

> My coupons are restricted to single use by a user only.

Looks like need to restrict the user and usage to just 1.
