### ISSUE TITLE
Corrupted single product page

### ISSUE THREAD

**Issue by finnvid** [woocommerce/woocommerce#17831]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [X] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product with a short description but and a blank "long" description
2. Make shure that the product does not have any attributes, size or wight
3. Turn off comments for the product

Now this product does not have any items to be displayed in tabs so the "woocommerce_default_product_tabs" will not return any tabs.

## Expected/actual behavior

When viewing the product on the single product page the "similar products" headline is wrongly displayed between the product image and the short description.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

`
### WordPress Environment ###

Home URL: https://swedishembroidery.com
Site URL: https://swedishembroidery.com
WC Version: 3.2.4
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.25
PHP Post Max Size: 50 MB
PHP Time Limit: 90
PHP Max Input Vars: 3000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.4
WC Database Prefix: wpmc_
MaxMind GeoIP Database: ❌ MaxMind GeoIP-databasen saknas – Geolokalisering kommer inte att fungera. Du kan ladda ned den och installera manuellt från http://dev.maxmind.com/geoip/legacy/geolite/ till adressen: . Bläddra ned till ”Nedladdningar” och ladda ned den ”binära/gzip”-filen intill ”GeoLite Country”. Kom ihåg att packa upp filen GeoIP.dat.gz och sedan endast ladda upp GeoIP.dat.
Total databasstorlek: 2.57MB
Datastorlek för databas: 1.97MB
Indexstorlek för databas: 0.60MB
wpmc_woocommerce_sessions: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_api_keys: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_attribute_taxonomies: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_downloadable_product_permissions: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_order_items: Data: 0.00 MB + Index: 0.01 MB
wpmc_woocommerce_order_itemmeta: Data: 0.03 MB + Index: 0.02 MB
wpmc_woocommerce_tax_rates: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_tax_rate_locations: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_shipping_zones: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_shipping_zone_locations: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_shipping_zone_methods: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_payment_tokens: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_payment_tokenmeta: Data: 0.00 MB + Index: 0.00 MB
wpmc_woocommerce_log: Data: 0.00 MB + Index: 0.00 MB
wpmc_commentmeta: Data: 0.00 MB + Index: 0.00 MB
wpmc_comments: Data: 0.01 MB + Index: 0.01 MB
wpmc_links: Data: 0.00 MB + Index: 0.00 MB
wpmc_options: Data: 0.61 MB + Index: 0.04 MB
wpmc_postmeta: Data: 0.63 MB + Index: 0.37 MB
wpmc_posts: Data: 0.67 MB + Index: 0.08 MB
wpmc_termmeta: Data: 0.00 MB + Index: 0.01 MB
wpmc_terms: Data: 0.00 MB + Index: 0.01 MB
wpmc_term_relationships: Data: 0.01 MB + Index: 0.02 MB
wpmc_term_taxonomy: Data: 0.00 MB + Index: 0.01 MB
wpmc_usermeta: Data: 0.01 MB + Index: 0.01 MB
wpmc_users: Data: 0.00 MB + Index: 0.01 MB
wpmc_wc_download_log: Data: 0.00 MB + Index: 0.00 MB

### Post Type Counts ###

attachment: 124
custom_css: 1
customize_changeset: 47
et_pb_layout: 57
mc4wp-form: 2
nav_menu_item: 16
page: 23
post: 2
product: 118
product_variation: 92
revision: 126
shop_order: 40

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

PaysonCheckout 2.0 för WooCommerce: av Krokedil – 1.1.10 – Inte testat med den aktiva versionen för WooCommerce
Lösenordsskyddat: av Ben Huson – 2.1
PDF Catalog: av ovologics – 1.0.13 – Inte testat med den aktiva versionen för WooCommerce
Reset WP: av Nikunj Soni – 1.1
WooCommerce: av Automattic – 3.2.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Butikbas: #39 - /?page_id=39
Varukorg: #40 - /?page_id=40
Kassan: #41 - /?page_id=41
Mitt konto: #42 - /?page_id=42
Allmänna villkor: ❌ Sida har inte valts

### Theme ###

Name: Divi
Version: 3.0.89
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
This will be due to a missing 'clearfix' in the theme's CSS and is not caused by WooCommerce itself. You should report this to the theme developer.

Thanks
