### ISSUE TITLE
Show only allowed Countries for billing address too!

### ISSUE THREAD

**Issue by KainLaVey** [woocommerce/woocommerce#17836]
Hi there,

i have a limited list of countries we are shipping to.

On the checkout it only works for the shipping address. For the billing address the user still can choose any country he want. But i want the user only can choose from the allowed countries for billing address too.

There must be an way to do that, right?

Thx for your help <3

**Comment by mikejolley** [comment]
Settings has an option called 'sell to countries'. WC > Settings > General.
