### ISSUE TITLE
Filter Products by Attibute widget slug url encoding-decoding issue (When the display type is Dropdown)

### ISSUE THREAD

**Issue by danos5d5** [woocommerce/woocommerce#17845]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an attribute for a product
2. Create an attribute term using international characters (in my case Greek)
3. I left the slug value empty (It was created by woocommerce)
3. Set the "Display Type" in "Filter Products by Attibute" widget "Dropdown"
4. In shop archive page try to filter the products using the widget and the term you created in step 2

## Expected/actual behavior

When I follow those steps, I see...
I created an attribute named "Είδος κάρτας" (Card type in english)
I created an attribute term "κάρτες ηλεκτρολόγων" (electrician cards in english)
In the shop page I placed the "Filter Products by Attibute" widget with Display Type: Dropdown
When I select the created term all items are displayed, not only the one with the attribute term I selected.

In the address bar I noticed the url has escape characters (see screenshot01 and screenshot02).
![screenshot01](https://user-images.githubusercontent.com/6008212/33083169-4f2aa9ba-cee7-11e7-93b7-624d81762c63.png)
![screenshot02](https://user-images.githubusercontent.com/6008212/33083170-4f4a3ece-cee7-11e7-88fc-08b10450e887.png)

I also tried in the debugger to change the slug manually. In that case it the filter works just fine. 
(see screenshot03)
![screenshot03](https://user-images.githubusercontent.com/6008212/33083354-d7cb7e5c-cee7-11e7-92f4-9fb1d4a9a3ba.png)

Note: The the filter works fine if I change the display type to list.  Also, if I manually fill in the slug field with latin characters works fine in both types. 

In my opinion, it seem like the the script encodes the the slug name twice. 
This is the stings I get in my address bar: 
%25ce%25ba%25ce%25ac%25cf%2581%25cf%2584%25ce%25b5%25cf%2582-%25ce%25b7%25ce%25bb%25ce%25b5%25ce%25ba%25cf%2584%25cf%2581%25ce%25bf%25ce%25bb%25cf%258c%25ce%25b3%25cf%2589%25ce%25bd

If you try to decode it here: https://meyerweb.com/eric/tools/dencoder/ 
you will have to run the decoder two times.  
 

I was expecting to see...
Only the item(s) with the attribute term I selected.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment
`
### WordPress Environment ###

Home URL: http://localhost/wpdemo
Site URL: http://localhost/wpdemo
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/5.6.30
PHP Version: 5.6.30
PHP Post Max Size: 8 MB
PHP Time Limit: 200000
PHP Max Input Vars: 1860
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 2.84MB
Database Data Size: 2.02MB
Database Index Size: 0.82MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.50MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 2
page: 5
post: 2
product: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17846
