### ISSUE TITLE
Woo commerce Checkout Error

### ISSUE THREAD

**Issue by bigbubbastrailers** [woocommerce/woocommerce#17856]
When Checking out. All of the line items are present and the total is correct.  View below.
<img width="1120" alt="screen shot 2017-11-21 at 8 10 56 pm" src="https://user-images.githubusercontent.com/33886403/33108537-f9732e80-cef9-11e7-87de-46256335593f.png">
However, after submitting the payment, one of the line items is missing. (Dealer Documentation Fee Tax"). However, the total is still correct. Is there a bug in the system?

<img width="1121" alt="screen shot 2017-11-21 at 8 10 00 pm" src="https://user-images.githubusercontent.com/33886403/33108571-25c5e0fe-cefa-11e7-8444-9330aa5a1425.png">

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17835
