### ISSUE TITLE
Nonce-checking on sales reports with custom date ranges breaks bookmarks

### ISSUE THREAD

**Issue by thpani** [woocommerce/woocommerce#17850]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

#13853 (more specifically [this commit](https://github.com/woocommerce/woocommerce/pull/13853/commits/b50312a1d895db4da0e2be3a1a76d89f05c2407d)) introduces nonce-checking for custom date ranges in sales reports.

I have bookmarks to custom date ranges for previous sales periods, so I don't have to re-select dates in the calendar widget over and over again. #13853 causes such bookmarks to fail silently when the bookmarked nonce expires (or when passing no nonce at all).

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
@thpani Suggestions? Show an error message?

Removing the nonce checks isn't a solution here - security first.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17866
