### ISSUE TITLE
Woocommerce Product Vendors - global commission includes non vendors

### ISSUE THREAD

**Issue by kepkas** [woocommerce/woocommerce#17869]
Hello!
When global commission set by default for vendors, non vendors like shop manger also get that commission set for their products, but that is no right because all non vendors should not be included in vendor commission settings.

It seems to be a bug.

**Comment by mikejolley** [comment]
> Usage questions can also be directed to the public support forum here: https://wordpress.org/support/plugin/woocommerce, unless this is a question about a premium extension in which case you should use the helpdesk.

https://woocommerce.com/my-account/tickets/

Thanks
