### ISSUE TITLE
Woo Rounding Wrong

### ISSUE THREAD

**Issue by babylines** [woocommerce/woocommerce#17860]
Line 230 class-wc-cart-totals.php

**Here's the problem:** - (some plugins use high precision pricing and large quantity)
$item->price                   = wc_add_number_precision_deep( $cart_item['data']->get_price() ) * $cart_item['quantity'];

**Here's the Probable Solution**
$item->price                   = wc_add_number_precision_deep( $cart_item['data']->get_price()  * $cart_item['quantity']);

**EDIT**
Tested. DEFINITE solution.

**Comment by mikejolley** [comment]
Core only allows prices input to the DP setting, but I see plugins could affect this or be affected. The change won't hurt core and doesn't affect tests so should be ok to include.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/17864/files
