### ISSUE TITLE
Taxes are never rounded at line level

### ISSUE THREAD

**Issue by ragulka** [woocommerce/woocommerce#17863]
I noticed that toggling `woocommerce_tax_round_at_subtotal` has absolutely no effect on tax calculations, at least not since 3.2.0 (I didn't test with earlier versions yet). I found that taxes are _always_ rounded at subtotal, rather than line level, regardless if that option is enabled or not. Maybe I am missing something here, but the numbers simply don't add up.

When cart totals are calculated, the calculation is done in the new `WC_Cart_Totals` class introduced in 3.2.0. Here we have a method `calculate_item_totals()`, which first calculates all the taxes, then sums them up:

https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/includes/class-wc-cart-totals.php#L639-L640

... and if rounding at subtotal is disabled, it seemingly rounds the tax total here:
https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/includes/class-wc-cart-totals.php#L643

But there are multiple issues at play here:
1. Line tax total is not actually rounded on line 643, because it's rounding the tax amount, which is **_already_ in cents** to the WC rounding precision, which has absolutely no effect. What it  probably _should_ do, is round to a full integer there, ie `$item->total_tax = wc_round_tax_total( $item->total_tax, 0 )`
2. The modified item (with the calculated `total`, `taxes` and `total_tax` properties) is not set back to `$this->items`, which means the calculated values have no effect here:
    https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/includes/class-wc-cart-totals.php#L656-L657

    There should be a line like `$this->items[ $item_key ] = $item;` somewhere here:
 https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/includes/class-wc-cart-totals.php#L649-L653

3. Even if the above 2 points are addressed, these values are actually never used when calculating the cart subtotal and total - rather, `$this->get_merged_taxes( false, 'items' )` is used:
 https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/includes/class-wc-cart-totals.php#L660-L661

    and here:
 https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/includes/class-wc-cart-totals.php#L819-L820

There is no issue with using `get_merged_taxes()` per se - it simply uses the results from previous tax calculations. Those rely on `WC_Tax::calc_tax()`, which, however suffers from the same issue that it actually never rounds the line taxes at line level.

https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/includes/class-wc-tax.php#L65-L93

What happens, at least when this method is called from [here](https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/includes/class-wc-cart-totals.php#L639), is that a price _in cents_ (such as `213` for `$2.13`) is passed in, and then that is "precision-adjusted" to `2130000` on line 75. Then, taxes are calculated, which results in a number like `117150` for the given price, and this is "rounded" on line 85... well the fact is that 117150 rounded is still 117150, and when precision is removed, it becomes `11.715`, which is yet again later converted to `0.11715`, and never again rounded.

So, instead of an expected `$0.12` tax (rounded at line level), the result is `$0.11715`. When purchasing an individual item, this doesn't make a difference, but if there are multiple items in cart, then it starts to add up. I personally experienced a 2-cent difference between the line item totals and cart total. 

I have written a failing cart unit test case for a cart configuration where this issue is very apparent. I then tried to look at ways of fixing the issue, but I'm not sure I understand enough of the reasoning behind a lot of the code and decisions that affect this.

Having said that, it seems to me that `WC_Tax:: calc_tax()` is the main culprit here. It needs to either remove the rounding precision before actually rounding [here](https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/includes/class-wc-tax.php#L85), or an argument to toggle whether the price should be even adjusted for prevision at all. I noticed quite a few methods since 3.2.0 have an `$in_cents` argument, so perhaps this was simply neglected to add to this method?

FWIW, I did exactly that to see if that would fix my failing test case, and it did. The only issue is that other tests started to fail. I looked into those tests and I'm not sure if the assertions are correct (but correct me if I'm wrong). For example:

* [This test](https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/tests/unit-tests/tax/tax.php#L176-L210) expects that the calculated tax is `1.665`, which would be true, if you're rounding taxes at subtotal level. However, rounding on line level, the result should be `1.67`. And by looking at the test setup, it seems that rounding at subtotal level is never turned on, and WooCommerce itself defaults to rounding tax at line level.

* The same is true for the [next test](https://github.com/woocommerce/woocommerce/blob/16152bfcf0e1a6917ebf84f8f5d6f6dbe008e6e4/tests/unit-tests/tax/tax.php#L264), where the expected outcomes would be `5.00` and `8.93`

Note that the above assumptions on expected results are based on the default decimal and rounding precision (2 and 4). Having said that, I am not sure I fully understand the purpose of `wc_get_rounding_precision()`, at least not in the context of calculating taxes. If the line item price is adjusted for precision (for 2 decimal places 2.13 becomes 213), then why would an additional rounding precision (with 4 decimals) be used at all? It doesn't seem to make any sense.

@mikejolley @claudiosanches curios to hear your thoughts on the above.

PS: probably a good read on calculating totals (article talks about invoices, but this applies to carts, orders, etc as well): https://makandracards.com/makandra/1505-invoices-how-to-properly-round-and-calculate-totals

**Comment by mikejolley** [comment]
There was some feedback a while back that we should adjust to round line totals more aggressively so 'invoices' add up. This is mainly a problem with tax inclusive prices. It's likely tests will need adjusting after this *if the new logic makes mathematical sense*.

A note on:

> However, rounding on line level, the result should be 1.67.

Note that with tax inclusive prices we round taxes halve down, to 1.66 in this case. This is so you don't end up with a price such as 8.325 and tax 1.665 ending in total 10 instead of defined 9.99. Those tests are testing the unrounded value, in which 1.665 is correct.

> I noticed quite a few methods since 3.2.0 have an $in_cents argument, so perhaps this was simply neglected to add to this method?

Tax class does not need to handle cent conversion because it will be passed the value in cents. It just calculates the tax on whatever you give it?

Need to also be wary of rounding too early. E.g. if the tax lines (individual taxes) are rounded, the tax total will be different than if you sum the unrounded tax lines and round the tax total.

Luckily most of the logic is in a single class now so this can be improved in isolation.

**Comment by mikejolley** [comment]
@ragulka are you on WC slack? Happy to collab on this for future release.

**Comment by ragulka** [comment]
@mikejolley I'm on the A8C slack, not sure if that's what you mean? :)

**Comment by ragulka** [comment]
@mikejolley sorry, I realized your probably meant https://woocommerceslack.herokuapp.com/ - joined now :)

**Comment by ragulka** [comment]
> This is mainly a problem with tax inclusive prices.

In this instance, the issue is mainly with tax-exclusive pricing - the cases reported here are all with tax-exclusive pricing. That being said, I do think they also affect tax-inclusive pricing.

> Note that with tax inclusive prices we round taxes halve down, to 1.66 in this case. This is so you don't end up with a price such as 8.325 and tax 1.665 ending in total 10 instead of defined 9.99. Those tests are testing the unrounded value, in which 1.665 is correct.

Got it on rounding mode (up vs down). I also understand that the tests are testing for the unrounded  tax per line - however, since WC by default rounds taxes per line, then really that test should either enabled rounding at subtotal or test for the rounded value. It just happens so that the assumption in that test is that the result should be unrounded, and it is, but it shouldn't - or at least that's how I see it.

> Tax class does not need to handle cent conversion because it will be passed the value in cents. It just calculates the tax on whatever you give it?

Probably, so not sure why it's converting now?

> Need to also be wary of rounding too early. E.g. if the tax lines (individual taxes) are rounded, the tax total will be different than if you sum the unrounded tax lines and round the tax total.

After chatting in Slack, I realize that this _may_ be a law/requirement in some jurisdictions, so I'm contacting a few accountants for their input on this. In any case though, I believe we want to fix rounding at line level, and also keep support for rounding at subtotal level.

**Comment by gconline** [comment]
Hi,

I run an Australian WooCommerce store and I'm also having the same issues.

My prices are tax exclusive (I have tried tax inclusive but have the same issue)

We pull the invoices into Xero and they're always 1c out due the rounding issue (eg line_subtotal_tax not rounding to 2 decimals)

EG GST Calculation:
By WooCommerce:
51.816
40.908
13.635
1.18
Tax Total = 107.539 (Rounded to 107.54)

By Xero:
51.82
40.91
13.64
1.18
Tax Total = 107.55

Is there anything I can do to fix this or wait for a new WooCommerce update?

**Comment by ragulka** [comment]
FWIW, I have talked to 2 different accountants and they both said that from taxation and tax reporting perspective, it doesn't really matter if taxes are rounded at line level or subtotal level, as the difference is so small (1 cent), at least in Estonia. Their advice was to do whatever makes more sense for the customer. Please note that this is not official legal advice.

**Comment by mikejolley** [comment]
@ragulka Opened https://github.com/woocommerce/woocommerce/pull/18008 for feedback and collab. I found we still needed to store unrounded values so taxes can be recalculated later (losing precision breaks that), but I've made it round before totalling things up. Let's move the conversation there please :)
