### ISSUE TITLE
Accessibility/usability of country and state controls in Woo 3.2.5

### ISSUE THREAD

**Issue by cgrabo73** [woocommerce/woocommerce#17876]
I use a screen reader as I am totally blind.  I also teach usrs on web browsing.  I am famiiliar with WC 2.6.1.4 so will be comparing the usability when checking outt using a screen reader with 3.2.5.
In 2.6.1.4 when tabbing from  name address etc, one comes to the country and/or state fields.  2.6.1.4 says they are buttons.  So a screen reader user knows to press space or enter on them.  Once the screen reader user activates the control, they can up and down arrow or start typing the country or state in question.  When they locate the one they want, they can just press tab to move to the next control.
In 3.2.5 the screen reader calls them combo edit boxes.  If one knows how to interact with the boxs they would normally just press up/down arrow to move through the items in the list until they locate the one in question and press tab, however with WC 3.2.2, 3.2.3, 3.2.4, and 3.2.5 a user must press space or enter to activate this combo box.  They can press up/down arrow or start typing to locate the country/state they want.  However if they just tab off of the control the control resets to whatevver their previous selection is, IE if I had New York selected from a previous session and I waanted to change to North Carolina I would first press space on the combo box, arrow to NC and prss enter to accept NC.  If I forget to press enter on NC my selection gets reset to NY.
It brakes the flow of filling out the form and most users wouldn't think to press enter after selecting their country/state.

**Comment by claudiulodro** [comment]
I believe the way it behaved in versions of WooCommerce before 3.2 was incorrect. WooCommerce 3.2 and up uses the selectWoo library we developed specifically to make the fields properly accessible and follow accessibility best practices.

Combobox is the correct type of element for the country/state inputs. Wikipedia defines a combobox as "a combination of a drop-down list or list box and a single-line editable textbox, allowing the user to either type a value directly or select a value from the list."

Combobox and dropdown elements should not select the current element when you press the tab key. If the list is open, the tab key should cancel and close the list. Here is an official example of how an accessible combobox should work from Webkit (Apple's Safari web browser): https://webkit.org/blog-files/aria1.0/combobox_with_live_region_status.html

**Comment by cgrabo73** [comment]
This is still an issue with our customers.  On no other e-commerce solution one just needs to navigate to the country and state in question and tab off.  When you tab off it selects the last item you were focused on.  One doesn't press enter to confirm the selection in a combo box.  I have been using assistive technology and teaching it for the past 25 years.  As someone that uses assistive technology on a daily basis, I find the new checkout flow brakes the user experience and confuses customers while checking out.  My colleague just saw this new checkout process yesterday and it threw her for a loop as she expected her state to stay where it was when she tabbed to the zip code field.
She has also been using assistive technology for over 20 years.
Try using a combo box from the keyboard in Windows and just tab off of your selection.  The selection you just made is maintained.  You can press enter but it is not a requirement.  In Woocommerce 3.2 it is a requirement.
Please consider making the change to allow those fields to function when pressing tab to confirm the selection.
Think of it this way.  I'm going through the checkout process I type my name and tab to the next field. 
 I need not press enter to confirm my name.  I continue to tab through the form, when I get to my address, I type in my address and press tab.  I don't need to press enter to confirm that I want my address and street name in the edit box.  I then tab to the state field and arrow to New York for example.  I then tab off without pressing enter and without my knowledge the state field resets back to the previous selection and I type in my zip code as I assumed the state I selected in the previous step was taken.  This can cause lots of frustration.  

Try and find a non woocommerce site that makes you press enter for country and state.  It isn't going to happen.
So again, Please make the changes as it would assist  the flow for screen reader users when checking out in Woocommerce 3.x and above.

**Comment by LotusDreamer** [comment]
Agreed -- I have been a daily screen reader user for 20 years, and have never encountered this behavior until now. I know many other screen reader users who would concur with me. this is the only element in the checkout process where pressing Enter prior to tabbing off is necessary... it's both unexpected (and again, I speak as someone who uses a screen reader daily professionally and personally) and inconsistent for the user.

**Comment by mikejolley** [comment]
> Try and find a non woocommerce site that makes you press enter for country and state. It isn't going to happen.

Amazon. It makes you hit enter. It disables tab. Try to enter a new address on Amazon and change the country.

**Comment by cgrabo73** [comment]
You are right, amazon does this in the new address for country.  However using a screen reader only reads once and I'm not able to use my arrow keys to move to the other options.  Tried it with JAWS 2018 with Firefox and NVDA with Google Chrome.
Amazon does however allow you to type in your state in an edit box without having to select it from a list.

Having to press enter, then tab brakes the flow of the checkout process especially when the previous item is selected.

It is more intuitive when just tabbing through and making your selections.
I just want to say, I am and have been a user of assistivve technology for 25 years as well as training other users in that time.
If I am selecting my state, the screen reader says new york, I press tab as I have done for every other control in the checkout form.  The site resets and I don't know it then the site throws an error when I press the place order button.  I need to then waste time and try to figure out what went wrong, or the business loses sales because I abort the order.  Or worse I send a package to another address because the wrong state was selected.  

Frankly the way it is done in 2.6.1.4 is a better experience from a keyboard users perspective.  Also one thing to keep in mind, a good majority of screen reader users  are not as competent browsing the internet and that will trip them up.
And the amazon example, for me it was set to US, so I would have no need personally to change the option.

Thanks for reading.

**Comment by claudiulodro** [comment]
> If I am selecting my state, the screen reader says new york, I press tab as I have done for every other control in the checkout form. The site resets and I don't know it then the site throws an error when I press the place order button. I need to then waste time and try to figure out what went wrong, or the business loses sales because I abort the order. Or worse I send a package to another address because the wrong state was selected.

This is a good point. I think that is likely why Amazon doesn't really do anything when you tab with the options open. In the example select from [the WebAIM accessible forms examples](https://webaim.org/techniques/forms/controls#select) tab also does nothing with the options open on my computer. 

I realize that it may be a better experience for you to have tab select the option when pressed, but it doesn't seem to be the technically correct and widely-used behavior. I think (especially for users on screen readers) it would be better if there was a consistent experience across the whole web. I believe the correct behavior is a third option we haven't really been discussing: do nothing when tab is pressed. If the user has to press Enter when selecting an option the user knows they selected the correct option. I'll have to do some more research.

**Comment by cgrabo73** [comment]
If you go to this link, you'll see a combo box with states that I can either tab off of, or press enter and tab.  The result is still the same.

https://ipostal1.com/choose-digital-mailbox-location.php

This is how the majority of state fields work for me when I am online filling out forms.  As I have said I am a screen reader user and have been browsing and teaching web navigation using screen readers for 20 years.
I have also spoken to sighted users that use the keyboard to fill out forms and pressing enter to accept the combo box slows them down too.
Thanks,

**Comment by mikejolley** [comment]
I think it would be easier to mirror the Amazon behaviour and disable tabbing if the user has already opened up the list. But I'll leave this to @claudiulodro to make the final call.

@claudiulodro Can you add how we should tackle this and move to the 'ready' pipeline afterwards?

**Comment by claudiulodro** [comment]
Let's disable tabbing if the dropdown is open. That's the technically correct way of handling it.

**Comment by cgrabo73** [comment]
I really wish you would reconsider making the tab key close and move on.  If it were just me, I could really care less and wouldn't make such a big deal of this.  It isn't just me, it is lots of screen reader users that are not confident to begin with on the Internet and will be confused when they come to one or two random shops that behave this way.  including mine where probably 85% of my customers use screen readers or some form of assistive technology.  I understand it is technically the way to do it but it is going to brake the flow when using the keyboard.
Lets go back to that Amazon example, the only time it is an issue is when one needs to change their country.  My guess is Amazon Geo locates you so changing the country is probably not an issue for most people, sighted or not.  Also considering the Amazon example, the combo box doesn't even read properly, I think I got it to read once or twice before it stopped.

On PayPal.com/shipnow they use a combo box and arrowing to the state, using first letter navigation, than tabbing off keeps the state the customer selected.  I use PayPal shipping all of the time as a screen reader user.

Have you tried tabbing through the checkout process to see how it would be as someone using a screen reader?

**Comment by lutrov** [comment]
Amazon is weird because it uses the TAB key to navigate to the next item in the list. I have just checked 4 random sites for Aussie consumers:

* fishpond.com.au
* ebay.com.au
* lumoenergy.com.au
* paypal.com.au

They all (1) keep the selected item and (2) move to the next field when the TAB key is pressed in the list. I'd say the way Woocommerce does it is wrong.

**Comment by claudiulodro** [comment]
I see. Testing those sites the behavior seems to be dependent on the browser used. On Chrome the tab key does nothing when a dropdown is open on the Checkout page of those sites, but on Firefox the tab key selects the current element.

**Comment by anant1811** [comment]
I believe this bug has re-surfaced. Details in the screenshots below: 

![https://d.pr/i/aT2Fpc](https://d.pr/i/aT2Fpc+) 
Full Size: https://d.pr/i/aT2Fpc

![https://d.pr/i/vQ7zxJ](https://d.pr/i/vQ7zxJ+) 
Full Size: https://d.pr/i/vQ7zxJ
