### ISSUE TITLE
update on postman

### ISSUE THREAD

**Issue by christianhr** [woocommerce/woocommerce#17879]
Hi, I follow all the steps but when you have to enter the keys with basic auth don't work, i try using oauth1 and it works, like next image, if someone have the same problem as I, try using oauth1
<img width="973" alt="captura de pantalla 2017-11-22 a la s 16 31 37" src="https://user-images.githubusercontent.com/20073816/33152607-144cdb80-cfa3-11e7-9cad-c865e1c4d27a.png">

**Comment by claudiulodro** [comment]
Basic auth is only allowed for https, otherwise anyone could read the API credentials when you send them.
