### ISSUE TITLE
jQuery-independent frontend

### ISSUE THREAD

**Issue by valdrinkoshi** [woocommerce/woocommerce#17877]
WooCommerce frontend currently relies on jQuery to interact with the DOM. Many of these interactions should be easy to replace with native DOM APIs, and eventually free WooCommerce frontend from the jQuery dependency.

The benefits of using the native DOM APIs would translate in faster page loading and faster time-to-interactive (as similarly suggested in https://github.com/woocommerce/storefront/issues/631). I've tested WooCommerce w/ a theme that doesn't require jQuery, and got a whole second faster  by removing jQuery:

| with jQuery | without jQuery |
|----------|--------|
| <img alt="with jquery" src="https://user-images.githubusercontent.com/6173664/33149713-925e5008-cf85-11e7-96df-f2f96890758b.png"> | <img alt="no jquery" src="https://user-images.githubusercontent.com/6173664/33149734-a400234a-cf85-11e7-8b7e-9fb6f312e64e.png"> |

Would you be interested in exploring this?

There are ~24 files directly using jQuery, they could be updated one by one in separate PRs.
The removal of the jquery dependency might affect plugins or themes that implicitly rely on it (e.g. enqueuing their scripts to WooCommerce ones instead of jquery). That could be left as a last step of this update, and in the meantime users of WooCommerce could dequeue the jQuery script themselves.

**Comment by mikejolley** [comment]
Sounds like a nice idea. I admit we rely on it a little much because we're not JS developers :)

Which scripts would have the biggest impact? I'd suggest starting with cart/checkout - those use ajax heavily so I'd be curious how those would look without the magic/easy jquery ajax methods being in place. Could this lead to more browser incompatibilities?

**Comment by studio404pl** [comment]
@mikejolley there's a lot of alternative libraries that are for ajax and weights a lot less, ie:
https://github.com/yanatan16/nanoajax

i have to admit that jQuery is bloated these days and i am developing entire shop without jQuery but have to embed it only on Woocommerce pages like product page, cart and checkout.

It would be good to have some alternative to make Woocommerce core non dependent on jQuery, rest is in developers hands (when it comes to plugins and further integrations).

**Comment by spencerfinnell** [comment]
What are the odds of having an install that doesn't enqueue jQuery via the theme or another plugin? Seems almost impossible. 

WordPress core uses jQuery for REST API AJAX requests (https://github.com/WordPress/WordPress/blob/master/wp-includes/js/api-request.js) which would reenqueue jQuery if WooCommerce switched any frontend requests to use the `/wc` endpoints.

I'm sure there are some selector optimizations and caching that can be done but trying to completely remove the dependency seems like it will almost always be "undone" by the rest of the environment.

**Comment by valdrinkoshi** [comment]
@mikejolley glad to see there is interest! A very useful resource for this migration away from jquery is www.youmightnotneedjquery.com, which provides battle-tested alternatives for almost all usages I’ve seen in this project. It’s important to know what is the matrix of supported browsers and their minimum version. I couldn’t find this information in the repository, could you point me to the right direction?

@spencerfinnell I agree that chances are that some plugin somewhere will enqueue jQuery, and even the very WordPress ensures jQuery is included when logged in as admin (see [`wp_deregister_script` implementation](https://github.com/WordPress/WordPress/blob/master/wp-includes/functions.wp-scripts.php#L218)). My point is that by making WooCommerce jQuery-independent, we allow users that carefully choose/build jQuery-free plugins or themes to rely on WooCommerce. As of today, I can remove jQuery scripts with `if ( !is_admin() ) wp_deregister_script('jquery');`.
I’d like to be able to rely on WooCommerce default theme working independently from jQuery.

**Comment by claudiosanches** [comment]
@valdrinkoshi for what I'm seen, looks like we are going to write our own "jQuery" library, but sounds good.
About "IE" usage, I think we can start with 9+.

**Comment by belcherj** [comment]
Ajax methods should use `fetch`:  https://fetch.spec.whatwg.org/ . There is a great polyfil until IE support can be dropped.

**Comment by mikejolley** [comment]
Moved these tasks to a single issue https://github.com/woocommerce/woocommerce/issues/18395
