### ISSUE TITLE
[qty] parameters not count cart total quantity.

### ISSUE THREAD

**Issue by maheshprajapati** [woocommerce/woocommerce#17884]
Shipping [qty] parameters not working properly. It's is counting only first product quantity. see screenshot.

shipping screenshot: http://ibb.co/jNhuTR
Screenshot: http://ibb.co/bPuGsm

 
`
### WordPress Environment ###

Home URL: http://localhost/wooconditional
Site URL: http://localhost/wooconditional
WC Version: 3.2.4
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Win64) PHP/5.6.25
PHP Version: 5.6.25
PHP Post Max Size: 8 MB
PHP Time Limit: 1200
PHP Max Input Vars: 2500
cURL Version: 7.50.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.68MB
Database Data Size: 1.30MB
Database Index Size: 0.38MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_icl_content_status: Data: 0.00MB + Index: 0.00MB
wp_icl_core_status: Data: 0.00MB + Index: 0.00MB
wp_icl_flags: Data: 0.00MB + Index: 0.00MB
wp_icl_languages: Data: 0.00MB + Index: 0.01MB
wp_icl_languages_translations: Data: 0.10MB + Index: 0.10MB
wp_icl_locale_map: Data: 0.00MB + Index: 0.00MB
wp_icl_message_status: Data: 0.00MB + Index: 0.00MB
wp_icl_node: Data: 0.00MB + Index: 0.00MB
wp_icl_reminders: Data: 0.00MB + Index: 0.00MB
wp_icl_strings: Data: 0.01MB + Index: 0.02MB
wp_icl_string_packages: Data: 0.00MB + Index: 0.00MB
wp_icl_string_positions: Data: 0.00MB + Index: 0.00MB
wp_icl_string_status: Data: 0.00MB + Index: 0.00MB
wp_icl_string_translations: Data: 0.00MB + Index: 0.00MB
wp_icl_translate: Data: 0.01MB + Index: 0.00MB
wp_icl_translate_job: Data: 0.00MB + Index: 0.00MB
wp_icl_translations: Data: 0.01MB + Index: 0.02MB
wp_icl_translation_batches: Data: 0.00MB + Index: 0.00MB
wp_icl_translation_status: Data: 0.01MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.91MB + Index: 0.05MB
wp_pmxi_files: Data: 0.00MB + Index: 0.00MB
wp_pmxi_history: Data: 0.00MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.00MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.00MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.00MB + Index: 0.00MB
wp_postmeta: Data: 0.18MB + Index: 0.09MB
wp_posts: Data: 0.05MB + Index: 0.03MB
wp_simple_auction_log: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.01MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.01MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wcextraflatrate_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_wcextraflatrate_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_wcextraflatrate_user_zone: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 60
customize_changeset: 1
nav_menu_item: 16
page: 9
post: 3
product: 28
product_variation: 12
revision: 5
shop_coupon: 1
shop_order: 3
wc_afrsm: 3
wc_conditional_fee: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

WP Template Name: by Afzal Multani – 1.0
Hello Dolly: by Matt Mullenweg – 1.6
Woocomerce Brands lite: by Proword – 2.0 – Not tested with the active version of WooCommerce
Woocommerce Category Banner Management: by thedotstore – 1.4.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.4 – 3.2.5 is available

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: auction (auction)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Sixteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Your screenshot links are dead.

Tested this and it increased by 10 for every quantity added:

![woocommerce settings local wordpress dev wordpress 2017-11-23 10-49-34](https://user-images.githubusercontent.com/90977/33169297-0c89d486-d03c-11e7-8eee-6e5b0efbcc0c.png)
