### ISSUE TITLE
Variants images external

### ISSUE THREAD

**Issue by hohuuhau** [woocommerce/woocommerce#17881]
Hello,
I created product and variants with external images URL with but images will re-upload in my server.
In variants, i'm tried to use meta_data with other plugin, but can't load images by color.
It's possible or not? And how can i do it?
Note: API version 2.

Many thanks,
Tomy Ho

**Comment by mikejolley** [comment]
WordPress does not support external images in the media library. Images assigned to products must be in the media library.

Thanks
