### ISSUE TITLE
want to add param WC_REST_Products_Controller::get_collection_params();

### ISSUE THREAD

**Issue by gauravmillipixels** [woocommerce/woocommerce#17886]
Can you please help me on this is there any function for api where i can add params in function before action 

My motive is that i doesn't want custom coding in that file 

Is there any way to extend this function Before action take place

**Comment by mikejolley** [comment]
Please don't use github for support reasons :)

See https://github.com/woocommerce/woocommerce/blob/4f6a3afc2aa48588a01a143701f0803c4aecf265/includes/abstracts/abstract-wc-rest-crud-controller.php#L298 . 

That filter is all you need.
