### ISSUE TITLE
Cart price reduced for non-taxable product when outside base location

### ISSUE THREAD

**Issue by LCmry** [woocommerce/woocommerce#17880]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Settings: 
**General**: Enable taxes; set the store base to be different from where you are located.
**Tax**: Select "Yes, I will enter prices inclusive of tax"; have a tax class that applies to base location with a rate > 0%.
2. Create a simple product that has a "Tax Status" of "None".
3. Do not log in as a customer and check that the checkout doesn't have any saved information - aim is to be a blank slate guest.
4. Add the product to the cart and go to the cart page (or do not enter location information at checkout).
5. Note that the price in the cart is less than the item price. For example a $3.00 product showing up as costing $2.79 in the cart (the amount reduced would have been tax). (Ex: https://cloudup.com/cHGuYPYiM6V)

## Expected/actual behavior

It seems that since this is a non-taxable product, there should be no reduction in the cost.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/17887
