### ISSUE TITLE
WC 3.2 - Class WC_Cart loads the `tax_display_cart` option too early

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#17897]
Ref. original discussion: https://github.com/woocommerce/woocommerce/issues/17894

In WC 3.2, the `WC_Cart` class loads the `tax_display_cart` option from within the `__construct()` method. 
~~~
/**
 * Constructor for the cart class. Loads options and hooks in the init method.
 */
public function __construct() {
  // Other code
  $this->tax_display_cart = get_option( 'woocommerce_tax_display_cart' );
  // Other code
}
~~~

This causes side effects on any filter that might need to alter the value of such option dynamically, and that might only be able to do so after both the `WC()->cart` and the `WC()->customer` are loaded.
I couldn't find an explanation for the the early loading of the option, but I guess it was presumably done for performance reasons, and to avoid calling `get_option()` too often.

Proposed fix
==
It's still possible to achieve good performance while keeping the "lazy loading" used until WC 3.1, so that the option is loaded only after WooCommerce objects have been initialised. That will allow the cart to work as it should, while preventing conflicts. I'm going to submit a pull request for this purpose.

**Comment by mikejolley** [comment]
hmm. Once shouldn't rely on settings being called at certain times. Due to the nature of settings, they can and will be loaded at any point in time.

If this really needs to be filterable, should there not be a filter when used, vs hacking options?

**Comment by daigo75** [comment]
The issue is that the value of that specific option (and other options too, actually) changes depending on a set of factors. There isn't a filter for it so far, so we need to rely on the core WordPress filters to intercept the raw option value.

If you can add a filter for that option, so that the value can be changed on the fly only when it's used, that would be ok as well, as the actual usage occurs at the right time (i.e. after WooCommerce has been initialised). I'm just afraid that this would require more extensive changes, as the option could be used in multiple places, which is why I opted for a quicker patch.

**Comment by daigo75** [comment]
I don't know if I was clear. I meant that a filter would definitely be a good solution, but it would take more work, so I proposed a short term patch.

**Comment by daigo75** [comment]
If it may help evaluating a more elegant solution, here are two filters I need to use at the moment (pseudo-code):
~~~
add_filter('option_woocommerce_tax_display_shop', 'some_function');
add_filter('option_woocommerce_tax_display_cart', 'some_function');
~~~

These are low level filters, triggered by WordPress itself as soon as the options are loaded. Having a filter for those options would make my life easier, and avoid issues in the future, as I actually need to determine their values when they are **used**, not loaded. 

Of course, the key aspect is that the entity that uses them should call the filter at the time of **usage**, not at the time of loading. If the filter is called only once, during the `__construct()`, we'll end up having to the same issue I'm trying to fix. :smile:

**Comment by kloon** [comment]
@daigo75 feel free to submit a pull request with the proposed changes and we can guide you from there.

**Comment by mikejolley** [comment]
@claudiulodro I think this needs to be in 3.3 - missed it.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18189
