### ISSUE TITLE
shipping zone postalcode

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#17896]
Hi

How can i add a postal zipcode range?

We have these zipcodes 1000AA 1900ZZ for f.e. Amsterdam

How can i add a range for those zipcodes in the shipping zones?  If i add

1000*...1900*  it works, but it will interfer with  other countries.  How do i enter a range that works

f.e. 1000A*...1900ZZ

**Comment by mikejolley** [comment]
> fully numeric ranges 

A mix of numbers and letters won't be supported by ranges. They need to be listed I'm afraid..

**Comment by BackuPs** [comment]
Thats a bummer.....  you know how many zipcodes there are? Only amsterdam 999 x 26 x 26. That is undone. This is really bad.... There are more countries that have alphanumeric zipcodes.

**Comment by mikejolley** [comment]
Depending on what you're actually doing you could go exclusive rather than inclusive, if the zone with postcodes is above the regular Amsterdam zone?

Wildcards work. Ranges do not.
