### ISSUE TITLE
woocommerce_scheduled_sales cron set to wrong time

### ISSUE THREAD

**Issue by batesy87** [woocommerce/woocommerce#17903]
Hi, not sure if a bug but might happen to other people.

We had a black Friday sale going live at midnight I set all the sale prices up before hand and set the schedules from 24/11/2017 to 28/11/2017, the prices didn't update at midnight but the frontend showed for example ~~£9.99~~ £9.99

I figured out this morning why that happened, the cron time for wc_scheduled_sales() was set to have it's next run at 2017-11-24 23:00:00 which means everything was a day behind since price schedules are midnight to midnight.

I used WP Control to modify the cron time and I can only assume the cron was created whilst we we're in Bristish Summer Time, hence the hour difference.

**Comment by claudiosanches** [comment]
This could be related to your store settings?

Since this is how we set that CRON:

https://github.com/woocommerce/woocommerce/blob/cc5c182f9d937530951f55249e1f753b2b90f89b/includes/class-wc-install.php#L352-L354

**Comment by batesy87** [comment]
Yea I found that part, I assume since the store is a couple of years old it
was created differently back then or the settings were wrong at some point

**Comment by claudiosanches** [comment]
Looks fine now, probably something already set in an old version as you said.
At least you could fix it using "WP Control".
Closing since I'm not able to reproduce.
