### ISSUE TITLE
WC CLI install_pages command not working

### ISSUE THREAD

**Issue by kmligue** [woocommerce/woocommerce#17902]
I run this command `php wp-cli.phar wc tool install_pages --user=1` but I get

> Error: 'install_pages' is not a registered subcommand of 'wc tool'. See 'wp help wc tool' for available subcommands.

**Comment by claudiosanches** [comment]
It's missing `run` command, here how to execute it:

```bash
php wp-cli.phar wc tool run install_pages --user=1
``
