### ISSUE TITLE
WooCommerce reviews not showing on front end

### ISSUE THREAD

**Issue by uneebmeer** [woocommerce/woocommerce#17900]
i have been struggling with this issue for hours now i am not being able to show comments on products individual page here are some steps i did incase someone else has one of these issues

    deactivated each and every plugin other than wooCommerce plugin
    activated comments from the Settings -> discussion
    reviews are activated for every product from quick edit option inside products page the comments are being posted from backend and shows on backend successfully but not on front end

i have tried the most popular issues on the internet still in my case it doesn't if some one can point out some other things to do i can highly highly appreciate it. thanks in advance

**Comment by kloon** [comment]
I going to need some more information from you, it would be very helpful if you followed the guidelines when opening the issue and provided us with all the information requested.

When I test this on WooCommerce 3.2.5 and on the 3.3 version under development in the master branch I get the reviews in both cases http://cld.wthms.co/0rdjt7

My suggestion would be to try and switch to another theme like Twentyseventeen or Storefront and see if that makes a difference for you. I tested with both themes as well and got the reviews.
