### ISSUE TITLE
Feature request: make woocommerce_wp_select support multi select

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#17908]
You can *almost* use `woocommerce_wp_select()` for enhanced selects like product searches, except that the part where the function checks if the option is meant to be `selected`

```
foreach ( $field['options'] as $key => $value ) {
		echo '<option value="' . esc_attr( $key ) . '" ' . selected( esc_attr( $field['value'] ), esc_attr( $key ), false ) . '>' . esc_html( $value ) . '</option>';
	}
```

If that part were tweaked a bit, then you could use it in core in places where you run an enhanced product search, and in extensions like Mix and Match that also need enhanced product searches.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18536
