### ISSUE TITLE
Add new line item of an existing order from front-end

### ISSUE THREAD

**Issue by wildrain** [woocommerce/woocommerce#17913]
I have already placed an order. so i have the order id. 
Now i want to add a product on that order and when i will click place order button from checkout page it will not create new order . it will update the previous order with newly line item. 

Is there anyone who can help me regarding this ?

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
