### ISSUE TITLE
_stock_quantity appears not in use

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce#17910]
Not sure if this the right way to get in touch? 

On https://github.com/woocommerce/woocommerce/wiki/Product-Data-Schema it mentions "stock_quantity" but this appears to be "stock" when I check my DB. 

Best regards,
Edith 

<img width="586" alt="screen shot 2017-11-25 at 08 10 16" src="https://user-images.githubusercontent.com/19706428/33228659-1c9f5a4e-d1b8-11e7-89f9-40a07b6d0a86.png">

**Comment by claudiosanches** [comment]
That Product Data Schema does not describes the database... Describes only our CRUD methods and internal params.

And that's the idea of CRUD, you don't need to care about how is saved on database, not to mention that we are working on a feature plugin to save several of products meta data into a new database, like a `products_meta` database, where `stock_quantity` and other values will turn into columns.
