### ISSUE TITLE
Coupon Code Issue, Usage Restriction Cannot Select Scheduled Products

### ISSUE THREAD

**Issue by endurtech** [woocommerce/woocommerce#17918]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. schedule a product for posting.
2. create a related coupon code.
3. attempt to reference the product from the usage restriction section.
4. discover that it cannot be done so you have to set product to private and try again.
5. realize you've had one too many cups of wine to give a fuck.

## Expected/actual behavior

When I follow those steps, I see...
oblivion.

I was expecting to see...
divine intelligence.

Christ, it would be faster for me to just code the solution myself than point it out. But today is not that day.

But I will say, great work on woocommerce. And thank you.

**Comment by claudiosanches** [comment]
@endurtech feel free to come back here using a more polite way to write and I'll be happy to help you. Until then I hope you get better from the hangover.

**Comment by endurtech** [comment]
## Steps to reproduce the issue

1. "schedule" a product for posting. (set a future date of publication)
2. create a coupon code and attempt to reference that product from the usage restriction section. you will see that it cannot be referenced.
3. a work around I discovered is to set the product to private (this way it isn't publicly visible), then create the coupon code and reference the product, you can then go back and set the product to be "scheduled". Looks like the usage restriction field query is missing "include scheduled products".

Thank you.
