### ISSUE TITLE
After date filter not working in woocommerce rest api (order, customers, products)

### ISSUE THREAD

**Issue by Subh01** [woocommerce/woocommerce#17911]
## Steps to reproduce the issue

1.Use rest api to get products, orders or customers in woocommerce using the after date filter.
2.Use the following URL : v1/orders?after=YYYY-MM-DD HH:MM:SS

## Expected/actual behavior

When I follow those steps, I see the products, orders or customers get filtered by the date.

I was expecting to see the products, orders or customers getting filtered by time also.

## WordPress Environment

<details>

WC version: 3.0.7
WP version:  4.7.7

</details>

**Comment by claudiosanches** [comment]
Not able to reproduce it.
Make sure that you are using the properly endpoint.
`after` should only works on `wp-json/wc/v1/orders` or `wp-json/wc/v2/orders` and not on our legacy REST API.
