### ISSUE TITLE
WC_Background_Emailer broken on multisite

### ISSUE THREAD

**Issue by xpd** [woocommerce/woocommerce#17915]
We did a brief run with *woocommerce_defer_transactional_emails* enabled on our rather big WooCommerce *multisite* install.

Certain customers got new order confirmations for old orders, caused by the order ids of the different sites getting mixed up. The same issue also showed up in the Product Bundles plugin that uses the same class.

## Steps to reproduce
1. Setup two WooCommerce installs in a multisite with woocommerce_defer_transactional_emails enabled.
2. Add a large number of orders on site 1 and complete them
3. Spam both site 1 and 2 with new orders
4. Monitor if old customers on site 1 gets a new confirmation

**Comment by claudiosanches** [comment]
`woocommerce_defer_transactional_emails` is experimental, that's why is disable by default, and should be fixed/improved by https://github.com/woocommerce/woocommerce/issues/16971

**Comment by xpd** [comment]
Any chance this will be fixed in advance of the new queue, or do we need to create an alternate solution? Sounds like something that would be reasonably easy and worthwhile to fix if it is simply a matter of queues getting mixed up.

**Comment by claudiosanches** [comment]
@xpd Feel free to submit a Pull Request.

**Comment by mikejolley** [comment]
@xpd See https://github.com/woocommerce/woocommerce/pull/18060 - if you can help test that would be great. Please leave feedback in the PR.
