### ISSUE TITLE
Can't create more than one variation with variations end point--woocommerce

### ISSUE THREAD

**Issue by kdenno** [woocommerce/woocommerce#17912]
the end point /wp-json/wc/v2/products/<product_id>/variations allows for only one variation at a time  is there any way to  send an array of variations so that the product is updated with more that one variation in one request??

**Comment by claudiosanches** [comment]
You can use `/wp-json/wc/v2/products/<product_id>/variations/batch`, see more details on the REST API docs:

https://woocommerce.github.io/woocommerce-rest-api-docs/#batch-update-product-variations

**Comment by kdenno** [comment]
thanks for the response @claudiosanches but after using the wp-json/wc/v2/products/' + productID + '/variations/batch i get a 403(forbidden) response from the server

**Comment by kdenno** [comment]
i've tried to trace it and this is the response from the server
{code: "woocommerce_rest_cannot_batch",…}
code
:
"woocommerce_rest_cannot_batch"
data
:
{status: 403}
message
:
"Sorry, you are not allowed to batch manipulate this resource.

**Comment by claudiosanches** [comment]
@kdenno note that this is not a support forum, if you need help with REST API you should try https://wordpress.org/support/plugin/woocommerce
