### ISSUE TITLE
wc-trash post_status doesn't get listed in trash

### ISSUE THREAD

**Issue by mikaelz** [woocommerce/woocommerce#17916]
While in wp-admin and moving order to trash it's post_status is **trash**, but using update_status() method sets **wc-trash**
```
$order = new WC_Order( $order_id );
$order->update_status( 'trash', 'Trash test' );
```
Found in WooCommerce 3.2.3, also tested 3.2.5 https://youtu.be/UhiF92HGnVk

**Comment by claudiosanches** [comment]
WooCommerce uses status only for payment status.

But still is possible to send to trash using:

```php
$order = wc_get_order( $order_id );
$order->delete();
```

Or permanently delete with:

```php
$order = wc_get_order( $order_id );
$order->delete( true );
```
