### ISSUE TITLE
HttpOnly in cookies

### ISSUE THREAD

**Issue by brunorioch** [woocommerce/woocommerce#17920]
Not even really sure if this is an issue but I've been referred here by woocommerce support.

A website we've built has been audited by an external security firm on behalf of the client and we've been informed that two cookies that are set at checkout (woocommerce_cart_hash and wp_woocommerce_session) and they should be httponly and marked as secure, as should all cookies.

Is there any reason that they are not set as httponly and secure, and if we implemented all cookies to be httponly and secure do you know if anything would break or not work as it should?

**Comment by claudiosanches** [comment]
If all your store is under HTTPS you should not have any trouble changing it.

However should need some changes to make all `HttpOnly` and `secure`.
Try change this line:

https://github.com/woocommerce/woocommerce/blob/8801279c103c0bc77749d6e9163ede5ba0e8cf43/includes/wc-core-functions.php#L776

to:

```php
setcookie( $name, $value, $expire, COOKIEPATH ? COOKIEPATH : '/', COOKIE_DOMAIN, true, true );
```

Let me know if works for you, so I can include a filter and allow everyone change this behavior.

**Comment by claudiosanches** [comment]
I think you can set on your `php.ini` for all cookies at once too:

```
session.cookie_httponly = 1
session.cookie_secure = 1
```

**Comment by claudiosanches** [comment]
Note that `woocommerce_cart_hash` is used by JavaScript, so changing to `HttpOnly` will break it.

**Comment by brunorioch** [comment]
Thanks for this.
I've tried…
```
setcookie( $name, $value, $expire, COOKIEPATH ? COOKIEPATH : '/', COOKIE_DOMAIN, true, true );
```
which worked even though as you say it should really break.

Also tried without the httponly
```
setcookie( $name, $value, $expire, COOKIEPATH ? COOKIEPATH : '/', COOKIE_DOMAIN, true, false );
```
which works fine.
So a filter would be great.
Thanks for your help.

**Comment by kloon** [comment]
Opened a PR with the filter. I think the reason it still works is because the JS might still call it via an ajax request which is http. In cases where the cookie is read directly via JS and not via an ajax request this might break, leaving the value as false by default to ensure it does not break anything.

**Comment by claudiosanches** [comment]
@kloon PR looks good, but we'll need more filters to make more cookies secure.
