### ISSUE TITLE
When importing variable products attribute is not set

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#17923]
When importing a variable product which is not using global attributes, the variation is not selected.

Example import file: 
[importvar.csv.zip](https://github.com/woocommerce/woocommerce/files/1506497/importvar.csv.zip)

After importing it the variations show up without an attribute selected:

![image](https://user-images.githubusercontent.com/11388669/33275688-5186d24e-d38b-11e7-8e0b-9c25bdb80c90.png)

If I change the attribute to a global attribute then it is selected correctly. This issue seems similar to https://github.com/woocommerce/woocommerce/issues/17775

This was fixed in 3.2.5 but it still seems to be a problem when importing with WordPress 4.9 and WooCommerce 3.2.5

**Comment by claudiulodro** [comment]
Your CSV worked great when I tried it with 3.2.5 and the latest master branch. Have you tried on a clean install?

**Comment by mikkamp** [comment]
Thanks for looking into this. I had tried it both on 3.2.5 and on the latest master branch. But not on a clean install. On a clean install it does work.

It seems to be that this happens only when the attribute I'm using also exists as a global attribute. So on my test site I already had a global attribute called `Size`.

Should it still be possible to use a non global attribute with the same name as a global attribute?

**Comment by mikejolley** [comment]
@claudiosanches Should this look inside the product for a matching product level attribute before registering a new attribute? https://github.com/woocommerce/woocommerce/blob/baccd857934256ffefa6740cd46e5a4a19a1aad4/includes/import/abstract-wc-product-importer.php#L315-L318

**Comment by claudiosanches** [comment]
@mikejolley `taxonomy` in this case is bool and comes from "Attribute 1 Global".
So if true, should create a new attribute anyway.
