### ISSUE TITLE
Order with ShippingMethod REST-API

### ISSUE THREAD

**Issue by AbanoubNassem** [woocommerce/woocommerce#17932]
using `NodeJS` I'm trying to send the shipping method info to` Woocommerce v3.1.2` so it saves it with the order as follow:

```
let payload = {
      customer_id: user.id,
      set_paid: false,
      payment_method: 'cod',
......
 shipping_lines: [
        {
          id : user.shippingMethod.instance_id,
          method_id: user.shippingMethod.method_id,
          method_title: user.shippingMethod.method_title,
          total: +user.shippingMethod.settings.cost.value
        }
]
.....
}
```
the console log : 

```
id: 2
method_id: "flat_rate"
method_title: "سعر ثابت"
total: 24
```

but it's not working , how I'm I supposed to create and order with shipping rate?

**Comment by Jianli03** [comment]
i think no id required in shipping_lines and values of method_id, method_title and total should be String instead of number

**Comment by AbanoubNassem** [comment]
@Jianli03 it is, I have updated the issue!

**Comment by Jianli03** [comment]
woo.. did not expect a reply..  it was my first comment on github😄

2017-11-28 19:28 GMT+08:00 Abanoub Nassem <notifications@github.com>:

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting WooCommerce bugs and issues. This is not a support portal. For support, you could try the community support forum: https://wordpress.org/support/plugin/woocommerce

**Comment by AbanoubNassem** [comment]
@rodrigoprimo I know it's not a support portal , according to the docs , provided here , the order should be created , but instead it response with 402...

**Comment by rodrigoprimo** [comment]
cc @claudiosanches for a second opinion

**Comment by claudiosanches** [comment]
@AbanoubNassem "according to the docs , provided here , the order should be created , but instead it response with 402" in case of sucess should be created, if fails should return an error code.
So for what I can understand and after testing, this is not an issue with WooCommerce.
If you find some issue with our code base I'll happy to fix, but what you are reporting does not sound like a bug.
