### ISSUE TITLE
Individual Add To Cart button missing from grouped products child products

### ISSUE THREAD

**Issue by fragglefusion** [woocommerce/woocommerce#17937]
Since the update to 3.0 the individual products listed in grouped products have been replaced with checkboxes rather than individual "add to cart" buttons. Is there any code that I can replace that brings the individual add to carts back? 

I run the storefront theme if that makes any difference to the solution.

here is an example page https://thedocumentrecordsstore .com/product/docd-5001/

Thank you,

James

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiulodro** [comment]
The only way to really bring it back is to use [the old grouped product template](https://github.com/woocommerce/woocommerce/blob/9038247b29afa3953cc4fe83f8d98c76b1b87c6f/templates/single-product/add-to-cart/grouped.php), but that template needs to be updated to work without errors in the latest versions of WooCommerce.

The checkboxes are how it's going to be going forward. Have you noticed a drop in conversions or anything that makes you want to move back to the old template, or is it just aesthetic preference?

**Comment by fragglefusion** [comment]
Yes we have noticed a drop in conversions, thats the main reason I wanted to look into this. We sell to an older audience overall 40+ and we hear complaints about it quite a lot. I also use hotjar which lets me see how people navigate the site and can see that people really get confused about it. Is there anything that can be done at all?

Thanks for your response,

James

**Comment by claudiosanches** [comment]
> Since the update to 3.0 the individual products listed in grouped products have been replaced with checkboxes rather than individual "add to cart" buttons.

WooCommerce 2.x didn't had any individual "add to cart" buttons for products listed on grouped products, and updating to 3.x is not replaced b checkboxes either.

This is the default display for grouped products since WooCommerce 1.6.6:

![screenshot from 2017-11-29 10-03-44](https://user-images.githubusercontent.com/1264099/33374387-1e156a84-d4ed-11e7-9a91-aea9565e5ce0.png)

So what you are reporting is created by custom code on your store, probably someone changed directly on WooCommerce core files, so when you updated replaced all old files with the new ones.

> Is there anything that can be done at all?

Contact the developer to made changes in your store to redo his work, but this time do it properly on a child theme or using hooks.

**Comment by claudiulodro** [comment]
@claudiosanches if the product has "Sold Individually" it's a checkbox instead of a quantity input on grouped products.

**Comment by fragglefusion** [comment]
Yeah as I run a download store people don’t want 3 of the same MP3, they only want one, so they are marked as sold individually. I don’t have a developer, I pieced together the site myself and haven’t made any major development edits.

**Comment by claudiosanches** [comment]
@claudiulodro that's why I'm in that CSV war, we need all kinds of possibilities in our sample CSV.

**Comment by claudiosanches** [comment]
@fragglefusion this template should restore all for you:

```php
<?php
/**
 * Grouped product add to cart
 *
 * This template can be overridden by copying it to yourtheme/woocommerce/single-product/add-to-cart/grouped.php.
 *
 * HOWEVER, on occasion WooCommerce will need to update template files and you
 * (the theme developer) will need to copy the new files to your theme to
 * maintain compatibility. We try to do this as little as possible, but it does
 * happen. When this occurs the version of the template file will be bumped and
 * the readme will list any important changes.
 *
 * @see         https://docs.woocommerce.com/document/template-structure/
 * @author      WooThemes
 * @package     WooCommerce/Templates
 * @version     3.3.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

global $product, $post;

$parent_product_post = $post;

do_action( 'woocommerce_before_add_to_cart_form' ); ?>

<form class="cart" method="post" enctype='multipart/form-data'>
	<table cellspacing="0" class="group_table">
		<tbody>
			<?php
				foreach ( $grouped_products as $product_id ) :
					if ( ! $product = wc_get_product( $product_id ) ) {
						continue;
					}

					if ( 'yes' === get_option( 'woocommerce_hide_out_of_stock_items' ) && ! $product->is_in_stock() ) {
						continue;
					}

					$post    = get_post( $product->get_id() );
					setup_postdata( $post );
					?>
					<tr>
						<td>
							<?php if ( $product->is_sold_individually() || ! $product->is_purchasable() ) : ?>
								<?php woocommerce_template_loop_add_to_cart(); ?>
							<?php else : ?>
								<?php
									$quantites_required = true;
								woocommerce_quantity_input( array(
										'input_name'  => 'quantity[' . $product_id . ']',
										'input_value' => ( isset( $_POST['quantity'][$product_id] ) ? wc_stock_amount( $_POST['quantity'][$product_id] ) : 0 ),
										'min_value'   => apply_filters( 'woocommerce_quantity_input_min', 0, $product ),
										'max_value'   => apply_filters( 'woocommerce_quantity_input_max', $product->backorders_allowed() ? '' : $product->get_stock_quantity(), $product )
								) );
								?>
							<?php endif; ?>
						</td>

						<td class="label">
							<label for="product-<?php echo $product_id; ?>">
								<?php echo $product->is_visible() ? '<a href="' . esc_url( apply_filters( 'woocommerce_grouped_product_list_link', get_permalink(), $product_id ) ) . '">' . get_the_title() . '</a>' : get_the_title(); ?>
							</label>
						</td>

						<?php do_action ( 'woocommerce_grouped_product_list_before_price', $product ); ?>

						<td class="price">
							<?php
								echo $product->get_price_html();

								if ( $availability = $product->get_availability() ) {
									$availability_html = empty( $availability['availability'] ) ? '' : '<p class="stock ' . esc_attr( $availability['class'] ) . '">' . esc_html( $availability['availability'] ) . '</p>';
									echo apply_filters( 'woocommerce_stock_html', $availability_html, $availability['availability'], $product );
				}
							?>
						</td>
					</tr>
					<?php
				endforeach;

				// Reset to parent grouped product
				$post    = $parent_product_post;
				$product = wc_get_product( $parent_product_post->ID );
				setup_postdata( $parent_product_post );
			?>
		</tbody>
	</table>

	<input type="hidden" name="add-to-cart" value="<?php echo esc_attr( $product->get_id() ); ?>" />

	<?php if ( $quantites_required ) : ?>

		<?php do_action( 'woocommerce_before_add_to_cart_button' ); ?>

		<button type="submit" class="single_add_to_cart_button button alt"><?php echo esc_html( $product->single_add_to_cart_text() ); ?></button>

		<?php do_action( 'woocommerce_after_add_to_cart_button' ); ?>

	<?php endif; ?>
</form>

<?php do_action( 'woocommerce_after_add_to_cart_form' ); ?>
```

**Comment by foolsdoor** [comment]
@fragglefusion @claudiosanches  I know this discussion is old but I'd really like to know if an update could be available. 
There is not so much about custom grouped product layout... 

I'm getting this error "Illegal offset type in isset or empty" and it show a messy description/title

This result could be perfect https://thedocumentrecordsstore.com/product/docd-5001/

I'm also trying to get the grouped product children into a select plus Add to cart on the product archive grid items. Any idea?

Thank you
Fabio
