### ISSUE TITLE
Bug on Checkout Page: Overlapping Ids prevent field inputs

### ISSUE THREAD

**Issue by currybun** [woocommerce/woocommerce#17953]
See: https://honeycarrot.com

## Steps to reproduce the issue
1. Be on a smart phone (doesn't replicate on tablet or desktop)
2. Place an item in cart and view cart
3. Go to checkout
4. Try to enter a last name

## Expected/actual behavior

You're supposed to be able to input the last name into the field, but instead it skips and goes to the company name input field. When inspecting you can see the id="billing_company_field" overlaps the last name field so the user can't input their last name. 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```

`
### WordPress Environment ###

Home URL: https://honeycarrot.com
Site URL: https://honeycarrot.com
WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.25
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: wp_lftq_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 2.76MB
Database Data Size: 2.41MB
Database Index Size: 0.35MB
wp_lftq_woocommerce_sessions: Data: 0.03MB + Index: 0.00MB
wp_lftq_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_lftq_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_lftq_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_lftq_woocommerce_order_items: Data: 0.00MB + Index: 0.01MB
wp_lftq_woocommerce_order_itemmeta: Data: 0.03MB + Index: 0.02MB
wp_lftq_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_lftq_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_lftq_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_lftq_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_lftq_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_lftq_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_lftq_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_lftq_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_lftq_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_lftq_comments: Data: 0.03MB + Index: 0.02MB
wp_lftq_frm_fields: Data: 0.04MB + Index: 0.01MB
wp_lftq_frm_forms: Data: 0.01MB + Index: 0.00MB
wp_lftq_frm_items: Data: 0.00MB + Index: 0.01MB
wp_lftq_frm_item_metas: Data: 0.00MB + Index: 0.00MB
wp_lftq_icwp_wpsf_audit_trail: Data: 0.03MB + Index: 0.00MB
wp_lftq_icwp_wpsf_ip_lists: Data: 0.00MB + Index: 0.00MB
wp_lftq_icwp_wpsf_reporting: Data: 0.00MB + Index: 0.00MB
wp_lftq_icwp_wpsf_spambot_comments_filter: Data: 0.00MB + Index: 0.00MB
wp_lftq_icwp_wpsf_statistics: Data: 0.00MB + Index: 0.00MB
wp_lftq_icwp_wpsf_user_management: Data: 0.00MB + Index: 0.00MB
wp_lftq_links: Data: 0.00MB + Index: 0.00MB
wp_lftq_options: Data: 1.79MB + Index: 0.10MB
wp_lftq_postmeta: Data: 0.18MB + Index: 0.10MB
wp_lftq_posts: Data: 0.17MB + Index: 0.03MB
wp_lftq_revslider_css: Data: 0.09MB + Index: 0.00MB
wp_lftq_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_lftq_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wp_lftq_revslider_sliders: Data: 0.00MB + Index: 0.00MB
wp_lftq_revslider_slides: Data: 0.00MB + Index: 0.00MB
wp_lftq_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_lftq_termmeta: Data: 0.00MB + Index: 0.00MB
wp_lftq_terms: Data: 0.00MB + Index: 0.01MB
wp_lftq_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_lftq_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_lftq_usermeta: Data: 0.01MB + Index: 0.01MB
wp_lftq_users: Data: 0.00MB + Index: 0.01MB
wp_lftq_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wp_lftq_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 30
custom_css: 1
customize_changeset: 12
frm_form_actions: 8
frm_styles: 2
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 5
page: 8
post: 2
product: 10
revision: 69
shop_coupon: 1
shop_order: 27
shop_order_refund: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Shield Security: by iControlWP – 5.18.0
Akismet Anti-Spam: by Automattic – 4.0.1
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.16
Formidable Forms: by Strategy11 – 2.05.06
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.0
Jetpack by WordPress.com: by Automattic – 5.5.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.2.1
My Custom Functions: by Arthur Gareginyan – 4.12
PayPal for WooCommerce: by Angell EYE – 1.4.6.8
WooCommerce Email Test: by RaiserWeb – 1.9 – Not tested with the active version of WooCommerce
WooCommerce Max Quantity: by Isabel Castillo – 1.5.1 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.9.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.5
Yoast SEO: by Team Yoast – 5.8
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #17 - /cart/
Checkout: #18 - /checkout/
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: Weston
Version: 1.1.6
Author URL: http://themetrust.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: themetrust-weston/woocommerce/archive-product.php
themetrust-weston/woocommerce/content-single-product.php
themetrust-weston/woocommerce/emails/customer-completed-order.php
themetrust-weston/woocommerce/emails/customer-processing-order.php
themetrust-weston/woocommerce/global/form-login.php
themetrust-weston/woocommerce/global/sidebar.php
themetrust-weston/woocommerce/single-product/related.php
themetrust-weston/woocommerce/single-product.php

`

</details>

![screen shot 2017-11-29 at 7 03 03 am](https://user-images.githubusercontent.com/22899039/33376635-79335f54-d4dc-11e7-9721-1713e459f20e.png)

**Comment by claudiosanches** [comment]
This is a theme issue and not an issue with WooCommerce core.
Try contact your theme's author.

**Comment by claudiosanches** [comment]
You can try Storefront too.
