### ISSUE TITLE
products endpoint gives error notice when posting downloads

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#17954]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

**Endpoint:**
http://localhost:9001/wp-json/wc/v2/products/1146?_method=PUT

**Querystring params:**
```
_method:PUT
downloads[0][file]:http://localhost:9001/wp-content/uploads/2017/11/1600x1600___112808_1600x1600_v1-26.png
downloads[0][name]:1600x1600___112808_1600x1600_v1-26-png
downloads[1][file]:http://localhost:9001/wp-content/uploads/2017/11/1600x1600___pgs_es_spez_13_top_1600x1600_v1-167.png
downloads[1][name]:1600x1600___pgs_es_spez_13_top_1600x1600_v1-167-png
oauth_consumer_key:ck_c500d3cf60e3af49270064e51f778650ebe2a171
oauth_nonce:Y5q7cb
oauth_signature:/b22YDVHFa6Vfboq1IjMKCBfMiU=
oauth_signature_method:HMAC-SHA1
oauth_timestamp:1511972982
oauth_version:1.0
```

## Expected/actual behavior

**When I follow those steps, I see...**
`<b>Notice</b>:  Array to string conversion in <b>/usr/local/var/www/storepilot/woocommerce/wp-includes/class-wp.php</b> on line <b>305</b><br />
`

**I was expecting to see...**
Product object as json

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiosanches** [comment]
Sounds like an issue with WordPress core. Just checked and this happens before hit our REST API.
Not to mention that the same errors can happens in any URL.

Open it into your browser:

```
http://localhost:9001/?_method=PUT&downloads[0][file]=http://localhost:9001/wp-content/uploads/2017/11/1600x1600___112808_1600x1600_v1-26.png&downloads[0][name]=1600x1600___112808_1600x1600_v1-26-png&downloads[1][file]=http://localhost:9001/wp-content/uploads/2017/11/1600x1600___pgs_es_spez_13_top_1600x1600_v1-167.png&downloads[1][name]=1600x1600___pgs_es_spez_13_top_1600x1600_v1-167-png
```

Will log the same errors.

**Comment by steffanhalv** [comment]
Thx, I take it to WP

**Comment by steffanhalv** [comment]
https://core.trac.wordpress.org/ticket/42752
