### ISSUE TITLE
wc_customer_bought_product returns true for refunded item

### ISSUE THREAD

**Issue by brock-martin** [woocommerce/woocommerce#17959]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. create an order with multiple items
2. refund (return) one item
3. `wc_customer_bought_product` still returns `true` for that item

## Expected/actual behavior

I was expecting it to return `false` for a refunded item

## Isolating the problem

I'm using the `wc_customer_bought_product()` function to check if a customer purchased a digital product so that we can give them access to purchased content. We recently realized that if one product is refunded in a multiple item order, the `wc_customer_bought_product()` function still returns true for the returned product.

Looking at the code, this is because the order status is still "completed" because there are other items in the order that were not refunded. If it's only a single item, we could set the status to "refunded" and `wc_customer_bought_product()` would be false, however, with multiple items, we can't do that or all items would return false.

Any ideas to get around this?

## WordPress Environment

<details>
```

### WordPress Environment ###

WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

```
</details>

**Comment by brock-martin** [comment]
Here is an example order, running `wc_customer_bought_product` for the customer and refunded product still returns `true`:

![wc-order-product-refunded](https://user-images.githubusercontent.com/20828425/33397686-6adc6cfa-d51a-11e7-9626-a13cf5b9e5c5.PNG)

**Comment by claudiosanches** [comment]
`wc_customer_bought_product()` already performs a heavy query, changing it to check if products are refunded probably will cause more performance issues.

Currently we are doing a major refactory on this function, as you can check in #16604, so I'm logging it there to remember us about removing items if refunded if possible.

Still you can write your own query using the `woocommerce_pre_customer_bought_product` filter or try create your own functions for it, since `wc_customer_bought_product()` is not reliable for what you are trying to do.

**Comment by brock-martin** [comment]
Thanks for the reply! I'll keep an eye on #16604 as well.

**Comment by qwik3r** [comment]
Just ran into the same issue. I'm trying to restrict content based on product purchased but realized if someone bought the product and we refunded them it would result in them still having access. I haven't been able to find a plugin that can restrict access on a per page basis versus some over blown membership plugin. 

Any suggestions would be great on how to restrict content based on product purchased.

**Comment by wolffe** [comment]
3 years later, I have the same issue.

**Comment by brock-martin** [comment]
Hey @wolffe - we ended up creating a custom solution: 

- We have a "permissions" table that holds basic details about the permission (user_id, product_id, date, amount paid, etc). 
- We have a hook that looks for changes in order status and adds or removes permissions if needed (completed, processing, returned, etc)
- We have a page where we can manually add or remove permissions as needed. For example, if there are partial refunds or an issue with an order.
- We created a new function that checks for access based on this new permissions table

This system gives more control and way better performance that looking at Woo orders. It also allows us to change the access parameters anytime without having to rely on Woo functions or changes. Hopefully that helps!

**Comment by wolffe** [comment]
I also have a custom function and it's pretty slow. It's only accessed 1 in 100 visits, so I think it's fine.

I wanted something official, as I've been searching Google for the past 2 hours. Thanks for replying 👍

**Comment by cedricbdev** [comment]
Hello,

I got this issue too. I've found the following solution that seems to work in my case (we have a lot of orders but each customer have less than 10 orders)

The code is manly wc_customer_bought_product code with some modifications:

```PHP
function custom_wc_customer_bought_product( $customer_email, $user_id, $product_id ) {
	global $wpdb;

	$result = apply_filters( 'woocommerce_pre_customer_bought_product', null, $customer_email, $user_id, $product_id );

	if ( null !== $result ) {
		return $result;
	}

	$transient_name    = 'wc_customer_bought_product_' . md5( $customer_email . $user_id );
	$transient_version = WC_Cache_Helper::get_transient_version( 'orders' );
	$transient_value   = get_transient( $transient_name );

	if ( isset( $transient_value['value'], $transient_value['version'] ) && $transient_value['version'] === $transient_version ) {
		$result = $transient_value['value'];
	} else {
		$customer_data = array( $user_id );

		if ( $user_id ) {
			$user = get_user_by( 'id', $user_id );

			if ( isset( $user->user_email ) ) {
				$customer_data[] = $user->user_email;
			}
		}

		if ( is_email( $customer_email ) ) {
			$customer_data[] = $customer_email;
		}

		$customer_data = array_map( 'esc_sql', array_filter( array_unique( $customer_data ) ) );
		$statuses      = array_map( 'esc_sql', wc_get_is_paid_statuses() );

		if ( count( $customer_data ) === 0 ) {
			return false;
		}

                // START MODIFICATIONS.
                //
                //
                // -- 1 --
                // `INNER JOIN {$wpdb->postmeta} AS pm ON p.ID = pm.post_id`
                // is replaced by
                // `INNER JOIN {$wpdb->postmeta} AS pm ON ( p.ID = pm.post_id OR p.post_parent = pm.post_id )`
                // The query now gets also posts with p.post_parent == pm.post_id, which gives us the posts with post_type == 'shop_order_refund'.
                //
                // -- 2 --
                // `$result = $wpdb->get_col("SELECT im.meta_value`
                // is replaced by
                //
                // -- 3 --
                // `$object_result = $wpdb->get_results("SELECT im.meta_value as product_id, p.post_type`
                // We need an object with the product_id (like before) and the post type to detect 'shop_order_refund' posts.
                // `ORDER BY p.ID` is added to get the posts in order of creation.
		$object_result = $wpdb->get_results(
			"
                        SELECT im.meta_value as product_id, p.post_type
                        FROM {$wpdb->posts} AS p

			INNER JOIN {$wpdb->postmeta} AS pm ON ( p.ID = pm.post_id OR p.post_parent = pm.post_id )
			INNER JOIN {$wpdb->prefix}woocommerce_order_items AS i ON p.ID = i.order_id
			INNER JOIN {$wpdb->prefix}woocommerce_order_itemmeta AS im ON i.order_item_id = im.order_item_id
			WHERE p.post_status IN ( 'wc-" . implode( "','wc-", $statuses ) . "' )
			AND pm.meta_key IN ( '_billing_email', '_customer_user' )
			AND im.meta_key IN ( '_product_id', '_variation_id' )
			AND im.meta_value != 0
			AND pm.meta_value IN ( '" . implode( "','", $customer_data ) . "' )
			ORDER BY p.ID
		"
		);
                // $object_result is now an array of objects. Each of these objects contains the product_id and the post_type.
                // We prepare a tmp array to save products ids that have been bought, excluding products ids that have been refunded in an order with multiple lines (partial refunded order).
		$products_ids = array();
                // We now loop over the $object_result.
		foreach ( $object_result as $result_line ) {
                        // If the post type of the current result line is 'shop_order_refund'...
			if ( 'shop_order_refund' === $result_line->post_type ) {
                                // we unset (exclude) the product id of the current result line from the tmp array of product ids.
				unset( $products_ids[ $result_line->product_id ] );
				continue;
			}
                        // Else, we add the product id to the tmp array of product ids.
			$products_ids[ $result_line->product_id ] = true;
		}
                // We put the final products ids from the tmp array in the $result variable.
		$result = array_keys( $products_ids );

                // Note: I've used an tmp array with products ids as keys to unset them more easily when needed.
                //
                //
                // END MODIFICATIONS.

		$result = array_map( 'absint', $result );

		$transient_value = array(
			'version' => $transient_version,
			'value'   => $result,
		);

		set_transient( $transient_name, $transient_value, DAY_IN_SECONDS * 30 );
	}
	return in_array( absint( $product_id ), $result, true );
}
```

Once again, this solution seems to work nicely in my case. But maybe there are some huge issues I didn't notice yet.
