### ISSUE TITLE
Must Be Logged In to Download File Message

### ISSUE THREAD

**Issue by DustinHartzler** [woocommerce/woocommerce#17957]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a digital product with a downloadable file
2. Make sure your download settings are set to `Downloads require login`
3. Purchase your digital product in the store
4. Log out of your WordPress site
5. Click on the download link from the email message to download file
6. You will see `You must be logged in to download files.`
7. Sign into WooCommerce account
8.  Notice still appears at the top: `You must be logged in to download files.`

## Expected/actual behavior

**When I follow those steps, I see...**

<img width="1221" alt="screen shot 2017-11-29 at 12 32 37 pm" src="https://user-images.githubusercontent.com/2293077/33396574-ef049af6-d516-11e7-92a4-9e8c3b3a7195.png">

This is because the URL is still:
https://mystagingwebsite.com/my-account/?wc_error=You+must+be+logged+in+to+download+files.

Instead of 
https://mystagingwebsite.com/my-account/

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: https://d12h-wcc.mystagingwebsite.com
Site URL: https://d12h-wcc.mystagingwebsite.com
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.26
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.56.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
Total Database Size: 11.44MB
Database Data Size: 7.05MB
Database Index Size: 4.39MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.05MB + Index: 0.03MB
wp_comments: Data: 0.13MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.03MB + Index: 0.05MB
wp_postmeta: Data: 0.13MB + Index: 0.14MB
wp_posts: Data: 0.09MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.14MB + Index: 0.14MB
wp_users: Data: 0.06MB + Index: 0.05MB
wp_wclsi_items: Data: 1.52MB + Index: 1.14MB
wp_wclsi_item_attribute_sets: Data: 0.02MB + Index: 0.05MB
wp_wclsi_item_categories: Data: 0.02MB + Index: 0.02MB
wp_wclsi_item_e_commerce: Data: 0.02MB + Index: 0.02MB
wp_wclsi_item_images: Data: 0.42MB + Index: 0.55MB
wp_wclsi_item_prices: Data: 1.52MB + Index: 0.20MB
wp_wclsi_item_shops: Data: 1.52MB + Index: 1.34MB

### Post Type Counts ###

attachment: 1
event_ticket: 2
jp_sitemap: 3
jp_sitemap_master: 3
page: 8
post: 1
product: 5
product_variation: 14
revision: 9
shop_coupon: 1
shop_order: 14
wc_membership_plan: 3
wc_user_membership: 200

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

VaultPress: by Automattic – 1.9.3
Akismet Anti-Spam: by Automattic – 4.0.1
WooCommerce Enable Free Shipping on a Per Product Basis: by Patrick Rauland & eugenf – 1.0.2 – Not tested with the active version of WooCommerce
Jetpack by WordPress.com: by Automattic – 5.5.1
Storefront Powerpack: by WooCommerce – 1.4.1 – 1.4.3 is available
WooCommerce Box Office: by WooCommerce – 1.1.6 – 1.1.7 is available – Not tested with the active version of WooCommerce
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.4.1 – 3.4.3 is available – Not tested with the active version of WooCommerce
WooCommerce Dropshipping: by WooCommerce – 1.1.2 – 1.2.1 is available – Not tested with the active version of WooCommerce
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.6
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.3 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 3.2.2 – Not tested with the active version of WooCommerce
WooCommerce Help Scout: by WooCommerce – 1.3.4 – 1.3.5 is available – Not tested with the active version of WooCommerce
WooCommerce LightSpeed POS: by WooThemes – 1.4.6 – 1.5.1 is available – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.8.8 – 1.9.4 is available – Not tested with the active version of WooCommerce
WooCommerce Order Barcodes: by Automattic – 1.3.1
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.3.2 – 3.3.5 is available – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.9.0 – Not tested with the active version of WooCommerce
WooCommerce UPS Shipping: by WooCommerce – 3.2.4 – 3.2.6 is available – Not tested with the active version of WooCommerce
WooCommerce USPS Shipping: by WooCommerce – 4.4.8 – 4.4.10 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3 – 3.2.5 is available

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #30 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Outlet
Version: 2.0.10
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.4 – 2.2.5 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

```
</details>

**Comment by jjw8089** [comment]
We've been getting this issue on our website since about Woocommerce 3.0.1. It still happens, even though we're updated to WC 3.2.6.

We've been able to consistently reproduce the problem on our production site using the steps above.

We've tried deactivating all plugins apart from WC, switching to the Twenty Fifteen theme, and flushing the cache. However, we can still reproduce the problem after all that.

There's one interesting point to make. On our staging site, which is an exact copy of the production site but with caching disabled, we are unable to reproduce the problem. Our hosting is with WPEngine.

**Comment by jjw8089** [comment]
Just want to make sure that someone saw this :) @mikejolley @claudiosanches @DustinHartzler 

I already spoke to Woocommerce support, and they told me to add a comment here describing the issue.

**Comment by mikejolley** [comment]
Do you have the error in the URL/address bar as described above?

**Comment by jjw8089** [comment]
Hi Mike. Yes. When the error happens, the URL is https://www.website.com/my-account/?wc_error=You+must+be+logged+in+to+download+files.

**Comment by jjw8089** [comment]
Hi Mike, I don't see that filter anywhere. Additionally, the website still has this issue even when I deactivate all plugins apart from Woocommerce, switch to the Twenty Fifteen theme, and flush the cache.

**Comment by jjw8089** [comment]
OK. I copied the site over to another install. This is a live environment on WPEngine. I deactivated all plugins except for WC, switched to the 2015 theme, and flushed the cache. You are welcome to play around with this install if it helps. There's definitely something going on beyond plugins/themes.

I'd prefer not to post the URL here - is there another way to send it to you?

**Comment by jjw8089** [comment]
OK we figured this out. It was a caching issue at WPEngine. 

They excluded the ?download_file= argument, and the "wp_woocommerce_session_" cookie from caching. 

That seems to have fixed the problem for now.
