### ISSUE TITLE
Order can be created using parent id of variable product but we are not adding any variation id using api.

### ISSUE THREAD

**Issue by pardeepror** [woocommerce/woocommerce#17966]
[HI](url
![orde](https://user-images.githubusercontent.com/4181194/33419139-1c55e4ac-d5cf-11e7-927e-c2c2296670ab.png)
![orde1](https://user-images.githubusercontent.com/4181194/33419141-1c98b0fc-d5cf-11e7-9f9a-96cf9389adff.png)

)
We use Add to cart api.
For example if variable product id is 1 and it has variation id 2 than
We can add product id 1 to cart and can checkout it.
Order is successfully created.
I think it should not happen.
In order there no product id displayed then a customer which product will ship?

**Comment by claudiosanches** [comment]
Sounds like problems on your implementation of REST API, need to follow the [docs](https://woocommerce.github.io/woocommerce-rest-api-docs/), and if is a variable product, should pass the `variation_id` as well.
