### ISSUE TITLE
Product Import Interface Misleading and Lacking Features 

### ISSUE THREAD

**Issue by tregenza** [woocommerce/woocommerce#17968]
Woocommerce 3.2.4 -> Products -> Import

Currently the Import function has a checkbox with the following message
"Update existing products [ ]  If a product  being imported matches an existing product by ID or SKU, update the  existing product rather than creating a new product or skipping the row."

Problem: The message is ambiguous. 

1) It does not clearly tell the user what will happen to new products if the box is ticked  (new products are ignored in this instance).

2) The phrase "rather than creating a new product or skipping the row" suggests two possible behaviours - not creating a product or skipping a row - when in reality there is only one behaviour.

Proposed Fix: 

Reword the message to "Update existing products only. Do not import new products".

Problem: Import Functionality

The overall import functionality is sub-optimal. If it a user has an import with both new and updated products on it (a common occurrence when users manage prices on a separate spreadsheet) they must run the import twice. Once to import new products and once to update existing products.

Proposed Fix:

Replace existing checkbox with two checkboxes:

Create new products: [ ]
Update existing products: [ ]

If neither is ticked the import will not run. Otherwise the import creates / updates products as the user's choice.

**Comment by matthiaswagnerwy** [comment]
hy, i would like to add a wish to the import process: the chance to select if images should be duplicated if files with that name already exist or not. it is the same scenario: i have a spreadsheet where every change on products, prices, ... is made. after every import, all images are uploaded again (they are stored in a separate folder on the server and referenced with the full url in the spreadsheet).
if it is not possible soon in the gui, could you tell me if there is an appropriate filter to code that on my own?

i just made a post in the support forums (https://wordpress.org/support/topic/woocommerce-product-import-duplicating-images/#post-9739955), but felt it is better to post it here. please feel free to close that support-thread again ;)

+1 for the request of @claudiulodro

**Comment by claudiosanches** [comment]
@matthiaswagnerwy by default the importer try not duplicate images if already in the WordPress media library. If you uploaded in other location in your server, maybe duplicate just to send into WordPress media library, but after that will have the source link and know where media item should link too.

**Comment by mikejolley** [comment]
> The overall import functionality is sub-optimal. If it a user has an import with both new and updated products on it (a common occurrence when users manage prices on a separate spreadsheet) they must run the import twice. Once to import new products and once to update existing products.

There is a reason it doesn't do both; IDs. If you're updating products by ID and including new IDs, it won't know whether to create a new product or update. This is also a problem if importing from another store because the IDs in the CSV won't exist, but the IDs cannot be reused because they may overlap other post types. 

For our sanity I don't want to include this yet. I will update the wording however as suggested.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18018
