### ISSUE TITLE
PHP Fatal error: Uncaught Error

### ISSUE THREAD

**Issue by NCChef** [woocommerce/woocommerce#17974]
We are getting the following error in our logs when we try to login via the Event Espresso App on a mobile phone if Woocommerce is active. If we deactivate WooCommerce the app connects an no error is generated in the log. Also, the app connects using JSON form a password generated using the Application Passwords plugin. The user name would still be the one associated with the persons WP user name. Hope this helps some in figuring out a solution. Here is the complete error:

30-Nov-2017 16:03:04 UTC] PHP Fatal error: Uncaught Error: Call to a member function get_page_permastruct() on null in /home/deansfarmmarket/public_html/wp-includes/link-template.php:357
Stack trace:
#0 /home/deansfarmmarket/public_html/wp-includes/link-template.php(320): _get_page_link(Object(WP_Post), false, false)
#1 /home/deansfarmmarket/public_html/wp-includes/link-template.php(144): get_page_link(Object(WP_Post), false, false)
#2 /home/deansfarmmarket/public_html/wp-content/plugins/woocommerce/includes/wc-page-functions.php(72): get_permalink(Object(WP_Post))
#3 /home/deansfarmmarket/public_html/wp-content/plugins/woocommerce/includes/wc-account-functions.php(30): wc_get_page_permalink(‘myaccount’)
#4 /home/deansfarmmarket/public_html/wp-includes/class-wp-hook.php(288): wc_lostpassword_url(‘https://deansfa…’)
#5 /home/deansfarmmarket/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(‘https://deansfa…’, Array)
#6 /home/deansfarmmarket/public_html/wp-includes/general-template.php(508): apply_filters(‘lostpassword_ur…’, ‘https:/ in /home/deansfarmmarket/public_html/wp-includes/link-template.php on line 357

**Comment by kloon** [comment]
It is possible this is also related to your theme, could you perhaps do a test with a theme like twentyseventeen and see if the error persists?

Also would be good to provide more information as requested, ie your system status report.

**Comment by mikejolley** [comment]
Something will be calling the lost password URL too early before wp_rewrite is init. We can protect against this, but the bug is elsewhere.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18021
