### ISSUE TITLE
Rounding issue in WC 3.2.5

### ISSUE THREAD

**Issue by madebymartin** [woocommerce/woocommerce#17970]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

1. Store is set to enter product prices excluding tax
2. Front end displays prices including tax (typical for UK retail store)
3. Tax is 20% (UK vat) - applied to all products
4. Add 2 products whose retail prices (inc tax) are: £65, £50. Their net prices are therefore: £54.1666667 and £41.6666667. At this point, the products display the correct, rounded price of £65 and £50
5. Add both products to the cart (free shipping)

## Expected/actual behavior

When I follow those steps, the grand total in the cart is £115.01.
It should of course be £115 exactly (£65 + £50).

**If nothing was rounded until the final total, we would have the correct final total:**
+ £54.1666667 (net of £65)
+ £41.6666667 (net of £50)
+ £10.8333333 (tax element of £65)
+ £8.3333333 (tax element of £50)
–––––––––––––––––––––––––––––––––––
TOTAL £115 (exactly with no rounding needed)

**Equally, if everything was rounded (net AND tax) per line, we also get to the correct total:**
+ £54.17 (rounded net of £65)
+ £41.67 (rounded net of £50)
+ £10.83 (rounded tax of £65)
+ £8.33 (rounded tax of £50)
–––––––––––––––––––––––––––––––––––
TOTAL £115

**However it seems that each product net price is being rounded per line but the tax is not. The tax total is then rounded before being summed with the net product total - That's the only way I can get to a final total of £115.01 so I guess is where the issue is.**

_PRODUCTS_
+ £54.17 (rounded net of £65)
+ £41.67 (rounded net of £50)
–––––––––––––––––––––––––––––––––––
Net product total **£95.84**

_TAX_
+ £10.8333333 (non-rounded tax of £65)
+ £8.3333333 (non-rounded tax element of £50)
–––––––––––––––––––––––––––––––––––
Tax total **£19.1666666666**

Grand total if tax total is rounded before summing tax with net total: 
£115.01 (£95.84 + £19.17)

Grand total if tax total is left unrounded before summing with net total:
£115 (£95.84 + £19.6666667, then rounded) 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by simonfranzen** [comment]
I have the same issue with the following setup and this bug not just came with this Woocommerce version. We are struggling since month with that issue:

- Store is set to enter product prices **including** tax
- Front end displays prices including tax
- We also use a tool which uses the Woocommerce REST API
- Tax is 19% (DE vat) - applied to all products

create manually an order and add the following items without taxes:
- Add 1 product 125.33 €
- Add 1 shipping cost 4.12 € 
- Calculate taxes !
- product tax 23.81 €
- shipping tax 0.78 €
- All together: 125.33 + 4.12 + 23.81 + 0.78 = 154.04 €

- **BUT** cart totals are: 154.05 €

I also tested the API and wrote a small tool which displays rounding errors. Here is what I got for the API:

```
    [shipping_total] => 4.12
    [shipping_tax] => 0.78
    [cart_tax] => 23.81
    [total] => 154.05
    [total_tax] => 24.60
    [prices_include_tax] => 1
```
Expected Total Tax: 24.59

**Comment by mikejolley** [comment]
Needs more testing but please see https://github.com/woocommerce/woocommerce/pull/18008

Add feedback there and please help us test this some more :)

Thanks
