### ISSUE TITLE
Shipping Calculator not showing on Cart Page

### ISSUE THREAD

**Issue by chris-brighton** [woocommerce/woocommerce#17979]
We have a situation where:
(1) Shipping Calculator on Cart option is on
(2) Customer default location is "geolocate"
(3) Shipping locations is "Ship to Specific Countries only" (let's call them Countries A, B, C)
(4) "Hide shipping costs until an address is entered" is OFF.

Now if the site user surfs from Country A, the shipping calculator does show on cart page.
However, if the site user's IP address is from Country D (not a shippable country), the shipping calculator does not show. This should not be the case.

The shipping calculator should always show regardless of geolocation, because the Country D site user might want to ship to Country A (because he's actually from Country A and is currently in D, or he's on a VPN through Country D, or he's a relative of someone in Country A). The behavior in 3.1.2 was that the calculator always showed, regardless.

Now, if we turn ON "hide shipping costs until address is entered", it works. 

Seems the bug:
(1) because Shipping Location (according to Geolocate) has identified the customer as coming from an invalid shipping country, it does not honour the "show shipping calculator" option as it has no rates for that country. In fact it should show the shipping calculator regardless, because geolocation could be wrong, or the customer may be travelling, or buying for a friend/relative.
(2) If we hide calculator till address is entered, then it does show the shipping calculator. The shipping calculator is shown because it is not trying to show non-existent rates from an invalid country, since the customer hasn't entered an address.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18022/files
