### ISSUE TITLE
Missing trailing slash in the order received url

### ISSUE THREAD

**Issue by julme** [woocommerce/woocommerce#17978]
Hello,

I noticed that with the current version of woocommerce, the order received url is missing a trailing slash.
With a Nginx server this is a problem because there is a 301 redirect because Nginx automaticaly add the missing trailing slash.
It's annoying to make the page loading more difficult at this stage of the order.

On my site the order received generated by Woocommerce is:
/commande/order-pay/811?key=wc_order_5a0efe243ebb7

Nginx redirect this URL to:
/commande/order-pay/811/?key=wc_order_5a0efe243ebb7
                                           ^^^

Is it possible to modify the get_checkout_payment_url function to add the trailing slash?

Thanks

**Comment by kloon** [comment]
You can hook into the woocommerce_get_endpoint_url and just add a trailing slash via the [trailingslashit function](https://codex.wordpress.org/Function_Reference/trailingslashit)
