### ISSUE TITLE
woocommerce product import csv

### ISSUE THREAD

**Issue by Qualdevv** [woocommerce/woocommerce#17982]
Hey! admin

I have a issue while uploading .csv in woocommerce inbuilt product importer. when i uploading .csv then it could not import all product. for example if i upload 5000 products then it upload 4975 only. so please give sujjection to overcome from this error.

**Comment by claudiulodro** [comment]
When importing do you get a message like "Import complete. 4975 products imported"? If so, there should be a link to view the import log which will tell you why 25 products weren't able to be imported.

If a 5000 product CSV isn't working well, you can easily split it up into two 2500 product CSVs and that may work better.

Without any further info about this I can't really provide any more insight, so I'm closing this issue.
