### ISSUE TITLE
Payment Methods: Settings: Should entities actually be added?

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#17989]
This was surprising, but I guess it is possible it is by design?

If you include a character like a `&` in a field like the BACS Instructions field, whether by wp-admin or via the REST API, it is replaced by the HTML entity ( e.g. `&amp;`) both in wp-admin or the REST API response/subsequent GETs

<img width="1114" alt="pizza-and-pasta" src="https://user-images.githubusercontent.com/1595739/33497317-605b3c16-d682-11e7-9c08-ebf95f7dea5e.png">

<img width="930" alt="screen shot 2017-12-01 at 10 29 20 am" src="https://user-images.githubusercontent.com/1595739/33497363-874fbdc4-d682-11e7-8041-7e4351967273.png">

cc @timmyc @budzanowski

**Comment by claudiulodro** [comment]
I believe it's correct. I'll leave this open in case anyone wants to chime in or discuss. It's a textarea so the content is run through [esc_textarea](https://developer.wordpress.org/reference/functions/esc_textarea/) which adds the entities.

**Comment by mikejolley** [comment]
Seems legit and matches admin.
