### ISSUE TITLE
Compatibility with upcoming PayPal security upgrades

### ISSUE THREAD

**Issue by galbaras** [woocommerce/woocommerce#17980]
PayPal just announced upcoming changes to its security infrastructure, indicating that website changes are required as a result.

See https://epl.paypal-communication.com/H/2/v400000160109814229418866e966eb1e0/b0050578-04dc-4804-a931-4771017e52a9/HTML

Is WooCommerce compatible/ready for this?

If not, the PayPal payment gateway may need some changes.

**Comment by kloon** [comment]
@galbaras We are already adhering to all those specifications for quite some time.

* We only use HTTPS for all communication with PayPal.
* We force HTTP 1.1
* We only use NVP for refunds, that already uses POST within our codebase.
