### ISSUE TITLE
Products query meta_data returned as mix of array and dictionary responses

### ISSUE THREAD

**Issue by rrlime** [woocommerce/woocommerce#17997]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
	There IS a prior report of this issue without resolution #14907
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
	In production, version WC 3.2.5, WP 4.9.1, PHP 5.6.31, MySQL 5.6.36
- [X] I have attempted to find the simplest possible steps to reproduce the issue
	Cannot determine reason
- [ ] I have included a failing test as a pull request (Optional)
	Once a developer contacts me I will give them their own API key and site URL.

## Steps to reproduce the issue

1. Simply dump all products (/wp-json/wc/v2/products) with no parameters (other than API key/secret)

## Expected/actual behavior
Most items have the meta_data returned as array. This matches the documentation.
    "meta_data": [
      {
        "id": 19788,
        "key": "fb_visibility",
        "value": "1"
      },
      {
        "id": 19789,
        "key": "fb_product_group_id",
        "value": "1714979428512891"
      },
      {
        "id": 19790,
        "key": "fb_product_item_id",
        "value": "1714979435179557"
      }

Some items return a dictionary instead:
    "meta_data": {
      "0": {
        "id": 7124,
        "key": "_min_variation_price",
        "value": "25.00"
      },
      "1": {
        "id": 7125,
        "key": "_max_variation_price",
        "value": "25.00"
      },
      "2": {
        "id": 7126,
        "key": "_min_price_variation_id",
        "value": "705"
      },
      "3": {
        "id": 7127,
        "key": "_max_price_variation_id",
        "value": "705"
      },
      "4": {
        "id": 7128,
        "key": "_min_variation_regular_price",
        "value": "25.00"
      },
      "5": {
        "id": 7129,
        "key": "_max_variation_regular_price",
        "value": "25.00"
      },
      "6": {
        "id": 7130,
        "key": "_min_regular_price_variation_id",
        "value": "705"
      },
      "7": {
        "id": 7131,
        "key": "_max_regular_price_variation_id",
        "value": "705"
      },
      "12": {
        "id": 19998,
        "key": "fb_image",
        "value": ""
      },
      "13": {
        "id": 19999,
        "key": "fb_visibility",
        "value": "1"
      },
      "14": {
        "id": 20000,
        "key": "fb_product_group_id",
        "value": "1587604627998464"
      }
    },

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
	Not only, but AFTER installing the Facebook plugin.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
	Using Storefront theme
- [X] I can reproduce this bug consistently using the steps above

*** Seems to happen on 'Variable' products, not simple products. Does not happpen on ALL variable products.

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://lilylimes.com
Site URL: https://lilylimes.com
WC Version: 3.2.5
Log Directory Writable: ?
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ?
Language: en

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 2 MB
Default Timezone is UTC: ?
fsockopen/cURL: ?
SoapClient: ?
DOMDocument: ?
GZip: ?
Multibyte String: ?
Remote Post: ?
Remote Get: ?

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ?
Total Database Size: 4.72MB
Database Data Size: 3.59MB
Database Index Size: 1.13MB
wp_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.01MB
wp_comments: Data: 0.01MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.20MB + Index: 0.12MB
wp_postmeta: Data: 1.22MB + Index: 0.59MB
wp_posts: Data: 0.69MB + Index: 0.12MB
wp_termmeta: Data: 0.01MB + Index: 0.02MB
wp_terms: Data: 0.01MB + Index: 0.03MB
wp_term_relationships: Data: 0.01MB + Index: 0.03MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 0.02MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 496
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 20
nf_sub: 2
page: 9
post: 2
product: 71
product_variation: 276
revision: 39
shop_coupon: 1
shop_order: 14
shop_order_refund: 1
shop_webhook: 1

### Security ###

Secure connection (HTTPS): ?
Hide errors from visitors: ?

### Active Plugins (18) ###

Advanced WP Columns: by Vladica Savic – 2.0.6
Check Email: by Chris Taylor – 0.5.5
Column Shortcodes: by Codepress – 1.0
Contact Widgets: by GoDaddy – 1.4.1
Facebook for WooCommerce: by Facebook – 1.6.6 – Not tested with the active version of WooCommerce
Jetpack by WordPress.com: by Automattic – 5.5.1
Ninja Forms: by The WP Ninjas – 3.2.4
PlugnPay Payment Gateway For WooCommerce: by PlugnPay – 1.1.0 – Not tested with the active version of WooCommerce
Storefront Mega Menus: by WooThemes – 1.4.0 – 1.5.0 is available – Not tested with the active version of WooCommerce
Storefront Powerpack: by WooThemes – 1.3.1 – 1.4.3 is available
Storefront Product Pagination: by WooThemes – 1.2.2 – Not tested with the active version of WooCommerce
Storefront Product Sharing: by WooThemes – 1.0.4
Storefront Sticky Add to Cart: by WooThemes – 1.1.7
Twitter: by Twitter – 2.0.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.9.0 – Not tested with the active version of WooCommerce
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.10 – 4.1.18 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.5

### Settings ###

API Enabled: ?
Force SSL: ?
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ? Page not set

### Theme ###

Name: Boutique
Version: 2.0.11
Author URL: http://woocommerce.com
Child Theme: ?
Parent Theme Name: Storefront
Parent Theme Version: 2.2.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ?

### Templates ###

Overrides: –
`</details>

**Comment by claudiosanches** [comment]
Not able to reproduce it.
@mikejolley CRUD can generate indexes like that?
For what is been reported here, this happens when missing some indexes there... We can forge `array_values()` on REST API, but maybe better fix on CRUD side.

**Comment by mikejolley** [comment]
I couldn't repro either, but we can definitely add array values without consequence. Adding in a sec.

**Comment by rrlime** [comment]
Would you like a copy of my database?

**Comment by claudiosanches** [comment]
@rrlime no need, will be fixed in 3.3.0.

**Comment by mehrdaady** [comment]
I get the same problem when importing products with WP All Importer, one of the co workers report updating some plugins though, before updating everything was fine, interesting fact is that it does not happen on another website when importing the same data with All Importer.

**Comment by claudiosanches** [comment]
@mehrdaady better report to WP All Importer, no to mention that this issue is related to the REST API.
