### ISSUE TITLE
WooCommerce should use it's own language input settings?

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#17999]
Most of Woocommerce work with languages is display... there is little information on input languages.
In my case I can't process orders where the input given by the customer is not in Latin characters.
Sadly the WordPress support forum can not provide assistance : https://wordpress.org/support/topic/charchters-in-orders/#post-9736746

I can not process order in Japanese! Everytime I have to contact the customer and ask him to send me his information in English.

I think WooCommerce should not relay on wordpress for that... Allow the store owner to set his own preferences for accepted characters for orders.

**Comment by kloon** [comment]
I'm afraid this is not really a WooCommerce issue, but one relating to how your site is set up. WooCommerce relies on WordPress tables, which if you do not have your site set up correctly to accept non-latin there is nothing we can do about it.

[Have a look here for more details about changing your WP collation](https://codex.wordpress.org/Converting_Database_Character_Sets)

**Comment by UserName011** [comment]
@kloon  This has nothing to do with the database.
I can save non Latin chars in my DB if I wish...  This should be prevented on the Front End of the site. if the customer type non latin char than raise an error notice and don't let the input to be processed. This is a WC issue.

**Comment by kloon** [comment]
@UserName011 OK, maybe I misunderstood your issue initially, but it is still not a WooCommerce issue.

If I understand you correctly you are saying you want to prohibit users from using any non-latin supported language on your site? The only suggestion I can give you about that is to change your selling location to not sell to countries that use these languages.

That said, as what pointed out in the support ticket, this will still not solve the problem as some customers that live in countries using latin chars may still prefer to enter their names the non-latin character way, and it could be quite offensive to some if you force them.

If we were ever to implement something like this, which I highly doubt, this will not be built into the core plugin, but rather an extension.

Also from the sound of things your issue is not with WooCommerce but your shipping provider and external system which does not support this.

You are welcome to get a developer to develop some custom functionality for your site that listens on all inputs via JS and then disallows non-latin chars to be entered, starting point could be https://stackoverflow.com/questions/150033/regular-expression-to-match-non-english-characters

**Comment by UserName011** [comment]
@kloon  I didn't not ask to change the way woocommerce address this issues... I asked to give the store owner the option to choose. I will choose to use it, someone else will not.

There is nothing offensive about it. We are asking our customers for their details in English and not other language. Our delivery courier can not process shipments with letters he doesn't understand.  I can't send order to Japan with Japanese letters... I need the customer information in English. 

By the way - Amazon US doesn't allow for Japanese customer to enter their details in Japanese. Is this offensive? not at all.. it's a requirement. 

I am not a web developer, this is a core issue for WooCommerce. Some stores won't be able to function like this. As I said before you give many solutions for display languages... convert text between languages, translations etc.. you give less if any support for input languages. 

Can you give a good reason why the store owner shouldn't be able to choose what language is acceptable for input ? Why this has to be drawn from the WordPress definition? We are in the businesses of improving this system... then this is an important improvement.

**Comment by mikejolley** [comment]
WordPress and WC support unicode characters.

If you have a shipping gateway which does not support these characters, **the shipping plugin needs to take input from WooCommerce and convert it into a supported format before sending it to the shipping provider.**

> I will choose to use it, someone else will not.

Shipping plugins facilitate the communication between platforms. Thats why they are there, and thats why this is not a bug or 'feature' we should implement. It should be handled in the shipping method plugin.

**Comment by UserName011** [comment]
@mikejolley  There is no way that a plugin can convert ふいう to English. This is not an issue of in this encoding the letter is 48 and in other its 50 so you need to map it accordingly... The letters itself doesnt exists! there is no conversion!
WooCommerce should allow me to not accept this characters prior to order placement. 

In any case this is not a plugin issue... I don't use a plugin I copy paste the information in the UPS / DHL / Other providers sites... Not all of them support these letters! 

Am I really that unclear that you don't understand the problem?

**Comment by mikejolley** [comment]
So you'd have customers translate things instead of yourselve? What if they don't speak english? 

> Am I really that unclear that you don't understand the problem?

I understand the problem and still think it's something core should not accommodate. We're not going to add an option which prevents half the world using the checkout. Make a plugin.

**Comment by UserName011** [comment]
@mikejolley 

When you try to make a purchase on Ebay you can't put your details in: Hebrew,Arabic,Korean and many other languages. The system doesn't support it! How is that different?

I don't understand why you claim that it will prevent from half of the world to order? My site is in English and only in English. There are no translations to other languages. Why is it so problematic to let the store owner choose what he wishes to set?

May I ask what is the harm in letting the store owner decide about the setting? Make the default as it is now and if store owner wants to force specific language then he can. Where is the harm in that? 

Let me point that Amazon.com,Ebay,NewEGG,GearBest and many many many other site does not allow unrecognized letters. My request is implemented in many sites I simply ask that the option will exist in WooCommerce as well. 

Again, Right now I am forced to send email to the customers and ask them to send me the details in English. Then I need to edit their order and only then process it. So where is the benefit in leaving it as it is? I am frustrated, customers are frustrated, we are losing valuable time where a change in the settings can resolve this issue.

**Comment by mikejolley** [comment]
What about characters with accents? And what would the 'setting' even be? I think this is best tackled with code/plugin. This is the first ever request for such a thing. You are free to post to the ideas board if you feel others would need it too.

**Comment by UserName011** [comment]
@mikejolley  Any one can write his details in English no matter what sound/accent his name or his address has. Just like you can write your name Mike in Hebrew it will be: מייק . Asking you to write your name in English rather than your native language isn't offensive you will simply write Mike.  Any name in any language can be written using English or any other language in the world.
Think about it.. In English lesson won't the Japanese or the Chinese or the Korean or the Arabic write their name,address,city,country in English?

The setting is simple... Like you can choose which countries your site allows shipments to. Add a setting allows to select which languages your site accepts. If someone type Hebrew letters when Hebrew is not permitted a message will be shown and the order will not be accepted.

**Comment by kloon** [comment]
@UserName011 As Mike mentioned, this is not a bug! Please continue this discussion on another platform like the ideas board and if there's enough interest we may look into it but at present, we will not be implementing this functionality.

You are welcome to have this developed for you by someone if you feel it is urgent for your store.

**Comment by alexlii1971** [comment]
This might be not bug, but it is much trouble. Is there anyway to detect language input and show a hint?
