### ISSUE TITLE
Duplicated item download lines

### ISSUE THREAD

**Issue by tomedme** [woocommerce/woocommerce#17992]
As the downloadable items are picked by order_key+email+product_id, if a customer purchases >1 of the same product, the download details rows are duplicated by the number of items purchased.

Applying a filter at the return of WC_Order->get_downloadable_items() would allow affected users to add a filter to loop through the items are remove duplicates (for example, using the download_id as array keys)

**Comment by claudiosanches** [comment]
Should be duplicated, since has been already duplicated by the customer, if the customer have any reason to buy that again, should display from each order, not to mention about download limit and expiration that can be different form each downloadable item too.

cc @mikejolley

**Comment by mikejolley** [comment]
Correct. And once the downloads expire (limit or date), the next row will be used instead.
