### ISSUE TITLE
Rounding issue for tax_exempt customer and store prices are including tax

### ISSUE THREAD

**Issue by bome** [woocommerce/woocommerce#17996]
## Prerequisites
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

Tested with WC 3.2.5.

## Steps to reproduce the issue

1. Store uses prices including taxes. Germanized plugin checks European VAT ID entered by customer and sets the vat_exempt property accordingly.
2. For example, user purchases an item for EUR 199. Now when the user enters a valid VAT ID, the cart needs to convert all inclusive prices to prices without vat.
3. VAT rate is 19% (Germany)

## Expected/actual behavior

When I follow those steps, I see the line item price to be EUR 167.23, but Subtotal and Total to be 167.22 (off by one cent).

I was expecting to see line item, Subtotal and Total all to equal 167.23, because 199/1.19 is 167.2268, which should be rounded to 167.23.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

I have disabled as many plugins as possible, but I need to keep the Germanized Pro plugin for setting VAT exempt.

I could fix the problem by removing the down-rounding when removing taxes in this line:
[https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart-totals.php#L433](url)
from
``$item->price              = absint( $item->price - array_sum( $taxes ) );``
to
``$item->price              = $item->price - array_sum( $taxes );``

I don't think downrounding is correct here. Either round correctly, or keep the precision for rounding at subtotal level.

**Comment by mikejolley** [comment]
Pretty much identical issue to https://github.com/woocommerce/woocommerce/issues/17970 - resolving there.

**Comment by bome** [comment]
This bug is still present in WC 3.2.6.

**Comment by mikejolley** [comment]
This ended up turning into https://github.com/woocommerce/woocommerce/pull/18008

We round with absint so we have a valid price (in cents). Starting with a price with many decimals is asking for rounding bugs further down the line.

**Comment by bome** [comment]
Hi Mike, thanks for replying. I appreciate that you know much better how the rounding is supposed to work. but here, ``remove_item_base_taxes()`` definitely calculates a wrong price in cents.

With 19% VAT rate, this line:
   ``$item->price              = absint($item->price - array_sum( $taxes ));``
ends up being called with these values:
  ``$item->price              = absint(19900.0 - array_sum( {3177.31} ));``
--> = absint(16722,69)
--> = 16722
That is 1 cent off of the correct price without VAT: 199 / 1.19 = 167.23

Maybe it is assumed that the taxes are without decimals? But then you wouldn't need to use absint at all.
Correct rounding (up or down) instead of using absint() fixes this issue.

And, on a side note, using absint() seems strange for another reason: if the price is negative, it'll be turned into a positive price. That is bound to produce a wrong result (independent of the question if a product can have a negative price). I'd rather use intval() for truncating decimals.

Thanks for all your efforts!

**Comment by mikejolley** [comment]
Thats doing it essentially to 2dp though right? 199 - 31.77 tax? The rest of the decimal is ignored.

**Comment by bome** [comment]
As it is implemented in WC 3.2.6, first the taxes (with decimals) are deducted from the item price, and then it is floored using absint(). Using round() would make more sense to me and yields correct results:

``absint(19900-3177.31) = absint(16722.69) = 16722`` --> wrong
``round(19900-3177.31) = round(16722.69) = 16723`` --> correct

It seems to me that using absint()/intval()/ceil() will always cause wrong results in some situations.
Alternatively, you could round() the taxes before deducting from the item price...
Thanks

**Comment by mikejolley** [comment]
Need example product prices and rates so a unit test can be written.

**Comment by bome** [comment]
Hi Mike,
thanks for the reply. I'll list my use case here:

Prices are entered with VAT
Store is located in Germany.
For the sake of example, only one store VAT rate: 19%
Product: price incl. VAT: EUR 199

Now all EU customers pay the price including VAT -- except VAT exempt customers. I use the plugin _Germanized Pro_ which sets customers to VAT exempt if they enter a valid VAT ID and are located in a EU country different from the store country. But I believe it's sufficient to manually set the customer to VAT exempt in the unit test to trigger the bug.

Expected behavior:
price of the product without VAT is EUR 167.23, and so is the subtotal and total of the cart.

Actual behavior:
price of the product without VAT is EUR 167.22.

Please let me know if you need more information

Thanks,
Florian

**Comment by mikejolley** [comment]
Let's try a round there and see what tests break. Moving to milestone.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18372
