### ISSUE TITLE
Web API PUT method is not working in ecomdash.com

### ISSUE THREAD

**Issue by sergiytravnikov** [woocommerce/woocommerce#18000]
Woo Web API GET method is working from ecomdash.com to select product. Woo PUT method is not working from Ecomdash. It's impossible to update product quantity from ecomdash. Is it a permission problem?
Serge
https://hollyhillvitamins.com

**Comment by kloon** [comment]
Hi, you are not really providing much information for me here. What version of the API are you using are you getting any error messages etc?

When I test the v2 API, which is the latest, I can do PUT requests and update product quantities of products fine. Have you contacted ecomdash? It could also be something on their side?

**Comment by sergiytravnikov** [comment]
Ecomdash helpdesk can not answer such questions, because they are not programmers?
I don't know what version do they use. 



04 December 2017, 09:41:18, by Gerhard Potgieter <notifications@github.com>: 


Hi, you are not really providing much information for me here. What version of the API are you using are you getting any error messages etc?

When I test the v2 API, which is the latest, I can do PUT requests and update product quantities of products fine. Have you contacted ecomdash? It could also be something on their side?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.







---------------
Sincerely yours,
Serge Travnikov

**Comment by sergiytravnikov** [comment]
What parameter do you use: SKU or id
I think Ecomdash uses SKU parameter to update product.
Screenshot is attached 



04 December 2017, 09:41:18, by Gerhard Potgieter <notifications@github.com>: 


Hi, you are not really providing much information for me here. What version of the API are you using are you getting any error messages etc?

When I test the v2 API, which is the latest, I can do PUT requests and update product quantities of products fine. Have you contacted ecomdash? It could also be something on their side?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.







---------------
Sincerely yours,
Serge Travnikov
