### ISSUE TITLE
Webhooks don't hook randomly

### ISSUE THREAD

**Issue by kevin25** [woocommerce/woocommerce#18009]
We suffered the random issue with webhooks. We use the external fulfillment system. Once the order is placed, it will hook the external fulfillment system. However, sometimes webhooks doesn't fire anything. We set the cron up 5 mins.

> */5 * * * * /usr/bin/php /home/domain/public_html/wp-cron.php > /dev/null 2>&1

<img width="888" alt="screen shot 2017-12-04 at 8 55 22 pm" src="https://user-images.githubusercontent.com/2909982/33586348-fe725bee-d936-11e7-83b2-d2e125caafcb.png">

## Expected/actual behavior

it should fire whenever new orders are placed.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
`
### WordPress Environment ###

Home URL: https://domain.com
Site URL: https://domain.com
WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.8.3
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.12.2
PHP Version: 7.0.21
PHP Post Max Size: 100 MB
PHP Time Limit: 3000
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: wp_
Total Database Size: 516.65MB
Database Data Size: 339.21MB
Database Index Size: 177.44MB
wp_woocommerce_sessions: Data: 28.08MB + Index: 1.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.31MB
wp_woocommerce_order_itemmeta: Data: 5.52MB + Index: 4.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.13MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_ac_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wp_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB
wp_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wp_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB
wp_adsw_activities: Data: 0.02MB + Index: 0.00MB
wp_adsw_ali_meta: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 7.22MB + Index: 0.41MB
wp_comments: Data: 6.52MB + Index: 7.06MB
wp_cp_feeds: Data: 0.02MB + Index: 0.00MB
wp_et_bloom_stats: Data: 1.52MB + Index: 0.00MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_gglcptch_whitelist: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_nf_objectmeta: Data: 0.02MB + Index: 0.00MB
wp_nf_objects: Data: 0.02MB + Index: 0.00MB
wp_nf_relationships: Data: 0.02MB + Index: 0.00MB
wp_ninja_forms_fav_fields: Data: 0.05MB + Index: 0.00MB
wp_ninja_forms_fields: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 39.42MB + Index: 1.33MB
wp_pinterest_automatic: Data: 0.02MB + Index: 0.00MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.08MB + Index: 0.00MB
wp_pmxi_posts: Data: 2.52MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 184.72MB + Index: 137.38MB
wp_posts: Data: 34.56MB + Index: 20.05MB
wp_queue: Data: 15.55MB + Index: 0.00MB
wp_rac_abandoncart: Data: 5.52MB + Index: 0.00MB
wp_rac_email_logs: Data: 0.14MB + Index: 0.00MB
wp_rac_templates_email: Data: 0.02MB + Index: 0.00MB
wp_social_users: Data: 0.02MB + Index: 0.02MB
wp_termmeta: Data: 0.19MB + Index: 0.23MB
wp_terms: Data: 0.19MB + Index: 0.22MB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB
wp_term_taxonomy: Data: 0.19MB + Index: 0.22MB
wp_usermeta: Data: 1.52MB + Index: 3.00MB
wp_users: Data: 0.09MB + Index: 0.08MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB
wp_woof_query_cache: Data: 0.02MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.23MB + Index: 0.00MB
wp_ywrr_email_blocklist: Data: 0.02MB + Index: 0.00MB
wp_ywrr_email_schedule: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

attachment: 23628
blocks: 4
featured_item: 1
follow_up_email: 1
mb_woc_wheel: 1
mc4wp-form: 2
ml-slider: 1
nav_menu_item: 106
nf_sub: 24
page: 25
post: 6
product: 703
product_variation: 52139
raccartlist: 1239
racemailtemplate: 3
racmaillog: 4099
racrecoveredorder: 204
schat_offline_msg: 1
shop_coupon: 286
shop_order: 4760
shop_order_refund: 59
shop_webhook: 8
was: 4
wccaf: 1
wccpf: 1
wpcf7_contact_form: 1
yith-wcpsc-wc-chart: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Contact Form 7: by Takayuki Miyoshi – 4.9.1
Google Tag Manager for Wordpress: by Thomas Geiger – 1.7.2
ElasticPress: by Taylor Lovett
Matt Gross
Aaron Holbrook
10up – 2.4

Envato WordPress Toolkit: by Envato – 1.7.3
Google Authenticator: by Henrik Schack – 0.48
Google Captcha (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.33
JanStudio Addons: by JanStudio – 1.1.3
MailChimp for WordPress: by ibericode – 4.1.11
Woocommerce Products Price Bulk Edit: by Mostafa Qanbari – 2.0 – Not tested with the active version of WooCommerce
PixelYourSite PRO: by PixelYourSite – 6.3.4 – Not tested with the active version of WooCommerce
PixelYourSite Super Pack: by PixelYourSite – 1.2.1
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.3.3.1
Recover Abandoned Cart: by Fantastic Plugins – 18.6 – Not tested with the active version of WooCommerce
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
SEO Optimized Images Business With WooCommerce: by priyanshu.mittal – 1.5.2 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.0.0-rc-1
WooCommerce Notification: by Andy Ha (villatheme.com) – 1.3.2 – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Lee Willis – 7.1.4 – 7.4.1 is available – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by Bolder Elements – 4.0.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.5
WordPress Importer: by wordpressdotorg – 0.6.3
Yoast SEO Premium: by Team Yoast – 5.8
Wordpress Pinterest Automatic: by ValvePress – 4.6.1
WP Rocket: by WP Media – 2.10.12
WooCommerce Variation Swatch: by WPAddon – 1.0.2 – Not tested with the active version of WooCommerce
Yoast SEO: WooCommerce: by Team Yoast – 5.6 – Not tested with the active version of WooCommerce
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.4.6
YITH WooCommerce Review Reminder Premium: by YITHEMES – 1.3.4
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2 – Not tested with the active version of WooCommerce
Zendesk Chat Widget: by Zendesk – 1.4.12

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Gecko Child
Version: 1.0.0
Author URL: http://www.janstudio.net
Child Theme: ✔
Parent Theme Name: Gecko
Parent Theme Version: 1.6.2
Parent Theme Author URL: http://www.janstudio.net
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: gecko-child/woocommerce/cart/cross-sells.php
gecko-child/woocommerce/single-product/related.php
gecko-child/woocommerce/single-product/up-sells.php

`
</details>

**Comment by mikejolley** [comment]
> it should fire whenever new orders are placed.

This is not totally true. Your webhook is set to fire when it goes processing. If an order is not made processing e.g. on-hold or completed, this event will be skipped.

The logs will inform you of sending failures. If there is no event for an order, it either skipped the processing event, or you had an error somewhere else (error logs reveal anything?). Another possibility is that it fired but was not handled - we don't retry sending, hooks send once.

3.3 will include improved logs to help diagnose issues, and 3.4 will switch to custom tables to make deliveries more reliable without the use of cron.  An issue for this is already logged here: https://github.com/woocommerce/woocommerce/issues/18003 When thats coded you can apply it to your store to test and it should hopefully improve your situation.

Thanks

**Comment by kevin25** [comment]
We tried to debug but no luck. It happened randomly. We tried both WordPress cron jobs and server cron jobs but no luck.

**Comment by mikejolley** [comment]
Cron system is not very reliable which is why I want to change it in #18003 - this will create a table of webhooks to send out so deliveries cannot be skipped.

**Comment by kevin25** [comment]
Is there any ETA for this feature? I really need a quick workaround for this.

**Comment by mikejolley** [comment]
3.4 won't be here until ~Q2. There is no quick fix if it's due to the cron system. You didn't confirm if the status was being skipped however.

**Comment by kevin25** [comment]
I only need it to fire when the new orders are created and the statuses are processing. The only way I can do is to check one by one. Then I have to change the order status from processing to pending and back. That takes so much time when I have more than 200 order per day.

**Comment by mikejolley** [comment]
If it's first status is processing, there is no transition hook..

**Comment by kevin25** [comment]
It works that way. When customer place an order, it will hook to the external fulfillment app. About 98% will work properly. Some of them doesn't even fire hooks. I checked the webhooks and found out that. First time i thought it was cron jobs. But i was wrong.

**Comment by mikejolley** [comment]
Check the order notes of an order which did not send through and compare to one which did.

**Comment by kevin25** [comment]
There is no difference between them.

**Comment by pachalaa** [comment]
Same problem here. Sometimes the webhooks are not firing at all once in ten. The order is "processing", notes of orders have no difference with orders who worked and the webhook log show nothing, just the previous order and the next one. If I manually click on the "update" order button, this time the webhook fires two times.

**Comment by ahmedkandel** [comment]
Same problem here with WC version 3.3.5 one random order is skipped randomly and silently no trace in webhook logs or error logs or comments so it is very hard to debug or know the reason behind. have anyone solved this issue?

**Comment by delfniki** [comment]
Same issue here - https://www.Lekkerhoning.nl
Created ticket on wordpress.org and stackoverflow..
https://wordpress.org/support/topic/woocommerce-order-updated-webhook-not-always-triggered/
https://stackoverflow.com/questions/62913040/woocommerce-order-updated-webhook-not-always-triggered

My webhook is triggering at order.updated action

Any idea on possible solution?
