### ISSUE TITLE
Product importer documentation doesn't explain variations

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#18001]
[The importer documentaton](https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Importer-&-Exporter#adding-custom-import-columns-developers) gives examples of how to add custom meta to the importer, but it does not explain how to add variations custom meta to the importer, despite mentioning in the opening paragraph _**The importer and exporter support all types of products, including variations.**_ 

Would suggest updating documentation with example for variations

**Comment by mikejolley** [comment]
Variations are added in the same CSV and format as regular products. 

Meta works the same for variations and products, so no additional documentation is needed. 

For reference, variations and products both extend the same class, so meta handling is identical https://github.com/woocommerce/woocommerce/blob/1783953f15a1820d04aff6535f66c9d072fa6511/includes/abstracts/abstract-wc-data.php#L403

Thanks

**Comment by yratof** [comment]
Only thing changing then is suffixing the objet ID when importing form the CSV?

` $object->update_meta_data( '_barcode', $data['_newfield'][ $object->get_id() ] );`

**Comment by mikejolley** [comment]
Suffixes are not required. Suffixes hide meta from admin UI - for variations thats irrelevant.
