### ISSUE TITLE
Kount Standard (Direct) Fraud detection

### ISSUE THREAD

**Issue by ocdevops** [woocommerce/woocommerce#18004]
Hi,
I would like to integrate Kount Standard (Direct) Fraud detection on our site, but Braintree cannot tell us what we should use as Kount merchant ID.

I'm using this extension:
https://woocommerce.com/products/woocommerce-gateway-paypal-powered-by-braintree/

What should I use as Kount merchant ID? My Braintree Merchant ID or my Braintree public API key?

Thanks for your help.

**Comment by mikejolley** [comment]
Surely that would be obtained via https://www.kount.com/?

This is not related to core in anyway so I'm closing this issue. This is not a support forum.

Thanks
