### ISSUE TITLE
wp_insert_post not fired with current version of an Order on save

### ISSUE THREAD

**Issue by gravityrail** [woocommerce/woocommerce#18007]
## Steps to reproduce the issue

1. Write a micro-plugin to hook `wp_insert_post` and dump results into error_log
2. Update the status of an order, say from Processing to Completed
3. Note that no `wp_insert_post` action is fired with the correct final status

## Expected/actual behavior

Expected to be able to hook `wp_insert_post` and get event fired with new post_status

## Cause

This is caused by some logic in `abstract-wc-order-data-store-cpt.php`, in the `update( &$order )` method:

```php
/**
 * When updating this object, to prevent infinite loops, use $wpdb
 * to update data, since wp_update_post spawns more calls to the
 * save_post action.
 *
 * This ensures hooks are fired by either WP itself (admin screen save),
 * or an update purely from CRUD.
 */
if ( doing_action( 'save_post' ) ) {
	$GLOBALS['wpdb']->update( $GLOBALS['wpdb']->posts, $post_data, array( 'ID' => $order->get_id() ) );
	clean_post_cache( $order->get_id() );
} else {
	wp_update_post( array_merge( array( 'ID' => $order->get_id() ), $post_data ) );
}
```

On the final `update` of a post, I guess it's inside the `save_post` action and so it uses pure SQL to save the post.

**Comment by mikejolley** [comment]
Removing the above code would cause an infinite redirect. Can you not use the order specific actions/CRUD? wp_insert_post may be dropped eventually when we move to custom tables.

**Comment by gravityrail** [comment]
In my particular case, it is beneficial to intercept all post saves in the same way. That said, I have found a workaround, which is to reload the post when the `wp_insert_post` action fires, as it appears that the post instance injected into the last action is actually stale relative to what's on disk and can be substituted with a fresh version.

**Comment by mikejolley** [comment]
👍 Yeah it will be fired, just once.

You'll get the stale problem with many post types since most plugins will save data after save. If your code runs first, you'll lack what they add.
