### ISSUE TITLE
$( this ).load();

### ISSUE THREAD

**Issue by kickbk** [woocommerce/woocommerce#18005]
Be aware that woocommerce/assets/js/frontend/single-product.js (and min.js) use $( this ).load(); in flexSlider on line 175 which is throwing an error when used with jQuery 3.2. Replacing with $( this ).trigger('load'); solves it.

**Comment by kloon** [comment]
@kickbk Would you mind submitting a PR to fix this? This would be a good first change for someone to contribute.

**Comment by kloon** [comment]
@jeffikus Maybe something to fix in Flexslider instead?

**Comment by jeffikus** [comment]
@kloon interesting, i'll take a look at why that is the case and get back to you.

**Comment by jeffikus** [comment]
ok, so... .load() was deprecated in 1.8 and removed in 3.0 - the question here is what version do we want to support? WP core looks to be 1.12.4, so if you want to support 3.0.x and up, then that .load needs to change in single-product.js

**Comment by jeffikus** [comment]
Also, this won't just be a change in 1 place, https://github.com/woocommerce/woocommerce/search?l=JavaScript&q=.load%28&type=&utf8=%E2%9C%93

**Comment by kickbk** [comment]
I'm totally stating the obvious, but it all boils down to WP core not upgrading their jQuery, which they really should reexamine.
As for WooCommerce, you probably would want to avoid falling into the same bad practice by replacing outdated functions with cross-version compatible ones, if possible.
Have you considered extracting extensions like flexSlider as official plugins for WooCommerce to minimize your core dependencies?

**Comment by jeffikus** [comment]
@kickbk before I go any further with this from the Flexslider side, in what context is jQuery 3.2 being loaded where you picked this up? Is another plugin dequeueing the WP jQuery and loading the 3.2 version?

**Comment by kickbk** [comment]
@jeffikus yes, we use our own theme that removes the outdated WP core jQuery and enqueues the latest from CDN. We develop most plugins in-house. WooCommerce is obviously an exception.

**Comment by WPprodigy** [comment]
WP core has been moving away from `.load()` since it is deprecated in the version they are using. Example: https://core.trac.wordpress.org/ticket/25371

IMO, WooCommerce should definitely update these as well, especially if there is no threat to backwards compatibility. `.on()` was added in 1.7: http://api.jquery.com/on/, and `.trigger()` has been in it's current form since 1.3.

Related reading:
- https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed
- https://github.com/jquery/jquery/issues/2286

**Comment by mikejolley** [comment]
The event is deprecated but the ajax load (http://api.jquery.com/load/) is not. Only one instance needs updating.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18393
