### ISSUE TITLE
Variable product images not changing anymore

### ISSUE THREAD

**Issue by ArxaggelosAlexandros** [woocommerce/woocommerce#18014]
I honestly do not know what is going wrong. It must have been an automatic update that happened. I cannot roll back to a previous WC I assume. It worked for a whole year and then it stopped.

I am a university graduate for IT, BUT I do not know anything about coding in sites etc. I never got into this.

So if you decide to give me any advices regard me a total newbie that simply understands everything you tell him to do. I am computer savvy, just know absolutely nothing in woocommerce and I did my whole site by following a simple youtube tutorial

**Comment by mikejolley** [comment]
Without status report/link to the page thats broken there isn't much we can do or say. The https://github.com/woocommerce/woocommerce/issues/new page lists what steps you should take before logging issues to narrow a problem down. Feel free to reply back after doing that.

Thanks

**Comment by ArxaggelosAlexandros** [comment]
Well I 'll get someone who is savvy with woocommerce and pay him to solve my problem. I did my page by following a youtube tutorial. I know nothing of those things you ask.

thanks for your time.
