### ISSUE TITLE
Different VAT applied on shipping costs

### ISSUE THREAD

**Issue by LauraVink** [woocommerce/woocommerce#18016]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Woocommerce > Settings > VAT (Taxes?). I've made a VAT especially for books. In the Nederlands is this 6%, normal VAT is 21%. (We call VAT = BTW) I've checked the button 'Shippingmethods' and the very end of this row. 
2. For the product (a book), I've made sure that this type of VAT is applied and it has the correct shipping method.
3. When you add the book to cart, the VAT on the shippingcosts is the same as VAT on product, right? This happens when you add this book to cart. https://fotografielessen.vinkacademy.nl/product/reisfotografie-boek/ (Select Netherlands as country at checkout). VAT on shipping is also 6%. This in in Woocommerce 2.6.14
4. On the staging site we've updated to Woocommerce 3.2.5
When I now add the same product to the cart, I see at checkout that for the shipping the standard VAT is applied (21%), instead as the VAT of the book that is in your cart. None of the settings were changed.
https://test.vinkacademy.nl/product/reisfotografie-boek/ (Again, check the Nederlands in checkout)

## Expected/actual behavior

Because non of the settings were changed, I'm surprised to see that now a different VAT % is applied to the shipping costs. Is this a bug?

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://test.vinkacademy.nl
Site URL: https://test.vinkacademy.nl
WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.0.17
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_
Totale databasegrootte: 99.85MB
Database datagrootte: 72.56MB
Database index grootte: 27.29MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.28MB
wp_woocommerce_order_itemmeta: Data: 4.52MB + Index: 4.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
idealidealcheckout: Data: 0.02MB + Index: 0.00MB
wp_3wp_activity_monitor_index: Data: 0.23MB + Index: 0.02MB
wp_3wp_activity_monitor_user_statistics: Data: 0.01MB + Index: 0.01MB
wp_advanced_notifications: Data: 0.00MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_affiliatemeta: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_affiliates: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_creatives: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_referrals: Data: 0.02MB + Index: 0.00MB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_visits: Data: 0.47MB + Index: 0.08MB
wp_cloudinvoiceclient: Data: 0.00MB + Index: 0.00MB
wp_cloudinvoiceorders: Data: 0.01MB + Index: 0.01MB
wp_commentmeta: Data: 4.49MB + Index: 2.41MB
wp_comments: Data: 7.46MB + Index: 5.85MB
wp_em_bookings: Data: 0.00MB + Index: 0.00MB
wp_em_categories: Data: 0.00MB + Index: 0.01MB
wp_em_events: Data: 0.02MB + Index: 0.01MB
wp_em_locations: Data: 0.00MB + Index: 0.01MB
wp_em_meta: Data: 0.00MB + Index: 0.01MB
wp_em_tickets: Data: 0.00MB + Index: 0.00MB
wp_em_tickets_bookings: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_media_file_manager_log: Data: 0.02MB + Index: 0.00MB
wp_mgmlp_folders: Data: 0.03MB + Index: 0.03MB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB
wp_ngg_album: Data: 0.00MB + Index: 0.00MB
wp_ngg_gallery: Data: 0.00MB + Index: 0.00MB
wp_ngg_pictures: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 11.83MB + Index: 0.32MB
wp_pdf_stamped_files_tbl: Data: 0.00MB + Index: 0.00MB
wp_plugin_slickquiz: Data: 0.20MB + Index: 0.00MB
wp_plugin_slickquiz_scores: Data: 0.00MB + Index: 0.00MB
wp_podsrel: Data: 0.02MB + Index: 0.06MB
wp_postmeta: Data: 13.48MB + Index: 7.12MB
wp_posts: Data: 18.49MB + Index: 0.69MB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB
wp_redirection_items: Data: 0.01MB + Index: 0.01MB
wp_redirection_logs: Data: 0.01MB + Index: 0.02MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.01MB + Index: 0.02MB
wp_term_relationships: Data: 0.04MB + Index: 0.08MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_uji_counter: Data: 0.00MB + Index: 0.00MB
wp_uji_subscriptions: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 4.87MB + Index: 3.00MB
wp_users: Data: 0.22MB + Index: 0.16MB
wp_wlm_api_queue: Data: 0.00MB + Index: 0.00MB
wp_wlm_contentlevels: Data: 0.13MB + Index: 0.25MB
wp_wlm_contentlevel_options: Data: 0.00MB + Index: 0.00MB
wp_wlm_emailbroadcast: Data: 0.00MB + Index: 0.00MB
wp_wlm_email_queue: Data: 0.00MB + Index: 0.00MB
wp_wlm_options: Data: 0.51MB + Index: 0.05MB
wp_wlm_userlevels: Data: 0.04MB + Index: 0.14MB
wp_wlm_userlevel_options: Data: 0.23MB + Index: 0.31MB
wp_wlm_user_options: Data: 0.43MB + Index: 0.48MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_wp4fb_design: Data: 0.00MB + Index: 0.00MB
wp_wp4fb_facebook: Data: 0.00MB + Index: 0.00MB
wp_wp4fb_general: Data: 0.00MB + Index: 0.00MB
wp_wp4fb_google_track: Data: 0.00MB + Index: 0.00MB
wp_wp4fb_shortcodes: Data: 0.00MB + Index: 0.00MB
wp_wsal_metadata: Data: 2.60MB + Index: 1.18MB
wp_wsal_occurrences: Data: 0.16MB + Index: 0.15MB
wp_wsal_options: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

_pods_field: 1
_pods_pod: 1
acf: 1
attachment: 1747
certificate: 838
certificate_template: 5
course: 6
display_type: 7
displayed_gallery: 8
event: 65
feature: 30
follow_up_email: 3
gal_display_source: 5
lesson: 359
lightbox_library: 7
location: 8
mgmlp_media_folder: 55
nav_menu_item: 41
ngg_gallery: 6
ngg_pictures: 88
page: 46
post: 6
product: 15
product_variation: 48
question: 92
quiz: 421
revision: 954
sd2_custom_slide: 14
shop_coupon: 163
shop_order: 3038
shop_order_refund: 2
sidebar: 10
slide: 13
slidedeck2: 6
tekstblok: 11
tribe_events: 22
tribe_organizer: 1
tribe_venue: 8
tribe_wooticket: 149
wooframework: 424
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

Advanced Custom Fields: door Elliot Condon – 4.4.12
AffiliateWP: door AffiliateWP
LLC – 2.1.7

AffiliateWP - Affiliate Area Tabs: door AffiliateWP – 1.1.6
cloudinvoiceclient: door Sophie Fischer – 2.4 – Niet getest met de actieve versie van WooCommerce
Contact Form 7: door Takayuki Miyoshi – 4.9.1
Cookie Law Info: door Richard Ashby – 1.5.3
Calculators: door Cristian Kiesling – 1.0
Custom Permalinks: door Sami Ahmed Siddiqui – 1.2.8
Canvas Extension - Menu Customizer: door PootlePress – 2.2.0
Enhanced E-commerce for Woocommerce store: door Tatvic – 1.2.0.1 – Niet getest met de actieve versie van WooCommerce
FancyBox for WordPress: door Colorlib – 3.0.13
Features: door WooThemes – 1.5.0
Gettext override translations: door Ramon Fincken – 1.0.1
Google Analytics for WordPress by MonsterInsights: door MonsterInsights – 6.2.6
WP Hide Plugin Updates and Warnings: door Midland Web Company – 1.0
Loco Translate: door Tim Whitlock – 2.0.16
Mailchimp Subscriber Chiclet for WordPress: door Gavin Rehkemper – 1.0.2
Mollie Payments for WooCommerce: door Mollie – 2.7.0
Pinterest "Pin It" Button Lite: door Phil Derksen – 2.1.0.1
Pods - Custom Content Types and Fields: door Pods Framework Team – 2.6.11
Redirection: door John Godley – 2.10.1
Verander wp-login.php: door Ella Iseulde Van Dorpe – 2.5.5
Responsive Lightbox: door subhansanjaya – 1.3.2
Sensei Certificates: door WooThemes – 1.0.11 – 1.0.17 is beschikbaar
Shortcodes Ultimate: door Vladimir Anokhin – 5.0.1
SlickQuiz: door Julie Cameron – 1.3.7.1
Smart Offers: door Store Apps – 3.2.1
Sucuri Security - Auditing, Malware Scanner and Hardening: door Sucuri Inc. – 1.8.11
Uji Countdown: door Wpmanage.com – 2.0.8
Update Control: door George Stephanis
Chip Bennett – 1.5

WooCommerce Dynamic Pricing & Discounts: door RightPress – 1.0.13 – Niet getest met de actieve versie van WooCommerce
WooCommerce Product Subtitle: door Varun Sridharan – 2.3 – Niet getest met de actieve versie van WooCommerce
WishList Member™: door WishList Products – 2.90.3101
WooChimp: door RightPress – 1.4.2 – Niet getest met de actieve versie van WooCommerce
WooCommerce Advanced Notifications: door WooThemes – 1.2.0 – 1.2.11 is beschikbaar – Niet getest met de actieve versie van WooCommerce
WooCommerce Email Customizer: door cxThemes – 3.12 – Niet getest met de actieve versie van WooCommerce
WooCommerce EU VAT Number: door WooThemes – 2.1.14 – 2.3.3 is beschikbaar – Niet getest met de actieve versie van WooCommerce
WooCommerce Force Sells: door WooCommerce – 1.1.13 – Niet getest met de actieve versie van WooCommerce
WooCommerce MyParcel: door Ewout Fernhout – 2.4.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Product Bundles: door WooThemes – 5.0.2 – 5.6.1 is beschikbaar – Niet getest met de actieve versie van WooCommerce
WooCommerce Selective Registration: door Anthony Valera – 1.0.4 – Niet getest met de actieve versie van WooCommerce
WooCommerce Social Login: door SkyVerge – 2.3.1 – 2.3.3 is beschikbaar – Niet getest met de actieve versie van WooCommerce
WooCommerce Wishlist Member Integration: door WooThemes – 2.5.1 – 2.5.2 is beschikbaar – Niet getest met de actieve versie van WooCommerce
WooCommerce: door Automattic – 3.2.5
WooSidebars - Sidebar Manager to WooSidebars Converter: door WooThemes – 1.1.3
WooSidebars: door WooThemes – 1.4.3
Sensei: door WooCommerce – 1.9.14 – 1.9.19 is beschikbaar
Yoast SEO: door Team Yoast – 5.8
WP-Copyright-Protection: door Dave Ligthart – 1.4
WP Security Audit Log: door WP White Security – 2.6.9.1
WPFront Notification Bar: door Syam Mohan – 1.7

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR ()
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #5635 - /shop/
Winkelmand: #5636 - /winkelwagen/
Afrekenen: #5637 - /afrekenen/
Mijn account: #5638 - /mijn-account/
Algemene voorwaarden: #5674 - /algemene-voorwaarden/

### Theme ###

Name: Vink Academy (2017)
Version: 1.0
Author URL: https://lamper-design.nl
Child Theme: ✔
Parent Theme Name: Canvas
Parent Theme Version: 5.11.7
Parent Theme Author URL: http://www.woothemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: va-2017/woocommerce/emails/admin-new-order.php
va-2017/woocommerce/emails/customer-completed-order.php
va-2017/woocommerce/emails/customer-invoice.php
va-2017/woocommerce/emails/customer-new-account.php
va-2017/woocommerce/emails/customer-note.php
va-2017/woocommerce/emails/customer-processing-order.php
va-2017/woocommerce/emails/customer-reset-password.php
va-2017/woocommerce/emails/email-addresses.php versie 2.4.0 is verouderd. De hoofdversie is 3.2.1
va-2017/woocommerce/emails/email-order-items.php versie 2.1.2 is verouderd. De hoofdversie is 3.2.0
va-2017/woocommerce/emails/plain/admin-new-order.php
va-2017/woocommerce/emails/plain/customer-completed-order.php
va-2017/woocommerce/emails/plain/customer-invoice.php
va-2017/woocommerce/emails/plain/customer-new-account.php
va-2017/woocommerce/emails/plain/customer-note.php
va-2017/woocommerce/emails/plain/customer-processing-order.php
va-2017/woocommerce/emails/plain/customer-reset-password.php
va-2017/woocommerce/emails/plain/email-addresses.php versie 2.2.0 is verouderd. De hoofdversie is 3.2.1
va-2017/woocommerce/emails/plain/email-order-details.php versie 2.5.0 is verouderd. De hoofdversie is 3.2.0

Outdated Templates: ❌Leer hoe te updaten
`
</details>

**Comment by mikejolley** [comment]
2 things;

- can you screenshot your tax settings page for us, where it shows tax classes etc
- can you re-save those settings to see if it makes a difference. I wonder if something is unset and a default is being used somewhere.

**Comment by LauraVink** [comment]
Hi Mike, 
I already tried re-saving the settings. And unchecking it, saving. Checking, saving. But that didn't make a difference. I've attached the screenshots, is this all you need or do you need more?

<img width="1279" alt="schermafdruk 2017-12-05 16 02 27" src="https://user-images.githubusercontent.com/34271325/33613874-11075d1e-d9d6-11e7-8808-89725cf3e761.png">
Vat/Taxes set for books.
<img width="1280" alt="schermafdruk 2017-12-05 16 03 14" src="https://user-images.githubusercontent.com/34271325/33613879-149819be-d9d6-11e7-8c2f-908e4bd2adde.png">
I've set this tax for books in the product itself.
<img width="1280" alt="schermafdruk 2017-12-05 16 03 30" src="https://user-images.githubusercontent.com/34271325/33613916-30317742-d9d6-11e7-82af-38c6f17a840f.png">
The sendingclasses.

<img width="1276" alt="schermafdruk 2017-12-05 16 06 19" src="https://user-images.githubusercontent.com/34271325/33613960-4dcbff02-d9d6-11e7-9e86-c1109ea036df.png">
Their is still 21% on the shipping costs (instead all being 6%)

**Comment by mikejolley** [comment]
@LauraVink I need the main tax options screen, where it shows how prices are defined and what tax class to base shipping on.

**Comment by LauraVink** [comment]
Oh yeah, I see it now and found the right setting! No bug. Only good to know then that this setting was not 'saved' when upgrading from 2.6 to 3.2.4, but changed to default again.

You can close this thread :)

<img width="1280" alt="schermafdruk 2017-12-05 16 15 06" src="https://user-images.githubusercontent.com/34271325/33614415-9d903b92-d9d7-11e7-95ce-60adb1149278.png">
