### ISSUE TITLE
Woocommerce Product CSV upload Bug? - sale_date_ends column not updating

### ISSUE THREAD

**Issue by aboutautomation** [woocommerce/woocommerce#18019]
Hi, i am super new to github, and woo commerce, and barely understand a bit of PHP, CSS (learning as i go really) my current project is [About Automation](www.aboutautomation.com.au/shop/)

Uploading a bulk edit csv via import on woocommerce ( i have also tried using other plugins and they dont allow bulk edits or sale_date_ends column)  and when i attempt to update column Date sale price  ends nothing changes. 

I have already checked the pulls linked to #16028 and #16056 on older woocommerce versions and it appears the contributing files are already correct. and to be safe i followed up by deactivting woocommerce plugin. and ftp. the master zip. and issue still occurs.  ( i currently have almost 460 products that are showing as on sale, my only options are to delete sale prices, or to manually edit each product sale date to) 

when i export the csv reads like so in excel 2016. 

![image](https://user-images.githubusercontent.com/34267235/33609733-faed7a88-da14-11e7-9a24-b860d0df5fe4.png)

and i edit to 
![image](https://user-images.githubusercontent.com/34267235/33609809-3ab84382-da15-11e7-9b61-21a70bc3b45f.png)
and i have tried both as date, general and custom (like in export) trying different formats was after i checked the og github issues. 
i even have tried csv programs, in case it was excel formatting. and i have tried to change W.P time format. 

each time results to the same outcome. 

- [x]  I have searched for similar issues in both open and closed tickets and cannot find a duplicate ( i have found same issue but marked fix is already present

- [x] The issue still exists against the latest `master` branch of WooCommerce on Github 

- [x] I have attempted to find the simplest possible steps to reproduce the issue

- [ ]  I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Products->All Products ->Export
2. Save .csv file locally, including all meta
3. Open .csv file-> modify "Date sale price starts" and "Date sale price ends" fields, save as csv file. (have also tried other programs, file formats, colum formats - incase it was an excel error - and entered data in a different format - dd/mm.yy, yyyy/mm/dd,dd-mm-yy 00:00:00 ect)
4. Products->all products ->Import local .csv file.

## Expected/actual behavior

When I follow those steps, I see...
If sale price is present everything is on sale. (all 460 products) 
Unless sale_date_ends is already modified directly in product, then there is no change.
If sale price is not set product is not on sale
I was expecting to see...
sale price on each product set to row value. (eg sale ends 04/12/2017 00:00 and product will store sale price but will not show as on sale) 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront] twenty-seventeen
- [x] I can reproduce this bug consistently using the steps above

### WordPress Environment ###

Home URL: https://www.aboutautomation.com.au
Site URL: https://www.aboutautomation.com.au
WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 64 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.32
PHP Post Max Size: 64 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: wptd_
MaxMind GeoIP Database: ✔
Total Database Size: 15.81MB
Database Data Size: 13.05MB
Database Index Size: 2.76MB
wptd_woocommerce_sessions: Data: 0.04MB + Index: 0.00MB
wptd_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wptd_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wptd_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wptd_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wptd_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wptd_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wptd_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wptd_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wptd_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wptd_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wptd_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wptd_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wptd_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wptd_commentmeta: Data: 0.03MB + Index: 0.02MB
wptd_comments: Data: 0.01MB + Index: 0.01MB
wptd_links: Data: 0.00MB + Index: 0.00MB
wptd_loginizer_logs: Data: 0.14MB + Index: 0.11MB
wptd_options: Data: 2.34MB + Index: 0.28MB
wptd_postmeta: Data: 3.20MB + Index: 1.63MB
wptd_posts: Data: 5.76MB + Index: 0.34MB
wptd_revslider_css: Data: 0.09MB + Index: 0.00MB
wptd_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wptd_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wptd_revslider_sliders: Data: 0.16MB + Index: 0.00MB
wptd_revslider_slides: Data: 0.64MB + Index: 0.00MB
wptd_revslider_static_slides: Data: 0.01MB + Index: 0.00MB
wptd_spellcheck_dictionary: Data: 0.00MB + Index: 0.00MB
wptd_spellcheck_empty: Data: 0.00MB + Index: 0.00MB
wptd_spellcheck_grammar: Data: 0.00MB + Index: 0.00MB
wptd_spellcheck_grammar_options: Data: 0.00MB + Index: 0.00MB
wptd_spellcheck_ignore: Data: 0.00MB + Index: 0.00MB
wptd_spellcheck_options: Data: 0.00MB + Index: 0.00MB
wptd_spellcheck_words: Data: 0.07MB + Index: 0.01MB
wptd_termmeta: Data: 0.01MB + Index: 0.01MB
wptd_terms: Data: 0.02MB + Index: 0.05MB
wptd_term_relationships: Data: 0.05MB + Index: 0.12MB
wptd_term_taxonomy: Data: 0.03MB + Index: 0.04MB
wptd_UPCP_Catalogues: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_Catalogue_Items: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_Categories: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_Custom_Fields: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_Fields_Meta: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_Items: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_Item_Images: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_SubCategories: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_Tagged_Items: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_Tags: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_Tag_Groups: Data: 0.00MB + Index: 0.00MB
wptd_UPCP_Videos: Data: 0.00MB + Index: 0.00MB
wptd_usermeta: Data: 0.13MB + Index: 0.02MB
wptd_users: Data: 0.00MB + Index: 0.01MB
wptd_woof_query_cache: Data: 0.00MB + Index: 0.00MB
wptd_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wptd_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
wptd_yoast_seo_links: Data: 0.30MB + Index: 0.07MB
wptd_yoast_seo_meta: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 250
brands: 9
custom_css: 2
customize_changeset: 26
footer: 1
kc-section: 9
mc4wp-form: 1
megamenu_profile: 4
nav_menu_item: 33
nc_reference: 53
page: 24
post: 58
product: 464
product_variation: 4
revision: 1021
shop_coupon: 1
shop_order: 1
shop_order_refund: 1
team: 2
wc_product_tab: 841
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Akismet Anti-Spam: by Automattic – 4.0.1
All In One SEO Pack Pro: by Michael Torbert – 2.5.3
Amazon Associates Link Builder: by Amazon Associates Program – 1.5.2
Catch IDs: by Catch Themes – 1.4.7
Contact Form 7: by Takayuki Miyoshi – 4.9.1
Easy FancyBox: by RavanH – 1.6.2
Enhanced Media Library PRO: by wpUXsolutions – 2.4.5
KC Pro!: by King-Theme – 1.9
KingComposer: by King-Theme – 2.6.15
Loginizer: by Raj Kothari – 1.3.8
MailChimp for WordPress: by ibericode – 4.1.11
Meta Box: by MetaBox.io – 4.12.6
Nelio Content: by Nelio Software – 1.4.2
One-Click Child Theme: by tychay – 1.6
Post Thumbnail Editor: by sewpafly – 2.4.8
Slider Revolution: by ThemePunch – 5.4.6.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.13.15

Widget Importer & Exporter: by WP Ultimate – 1.5.2
WooCommerce Brands: by WooCommerce – 1.5.2 – Not tested with the active version of WooCommerce
WooCommerce Currency Switcher: by realmag777 – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.6
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.10
WooCommerce MailChimp Integration: by WooCommerce – 1.0.3 – Not tested with the active version of WooCommerce
WooCommerce Pre-Orders: by WooCommerce – 1.5.4
WOOF - WooCommerce Products Filter: by realmag777 – 2.1.7 – Not tested with the active version of WooCommerce
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.4 – Not tested with the active version of WooCommerce
WooCommerce - Store Toolkit: by Visser Labs – 1.7.5 – Not tested with the active version of WooCommerce
WooCommerce Tab Manager: by SkyVerge – 1.8.4
WooCommerce Xero Integration: by WooCommerce – 1.7.9 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.5
WordPress Importer: by wordpressdotorg – 0.6.3
WP Admin UI Customize: by gqevu6bsiz – 1.5.11
WPOPAL Framework For Themes: by WPOPAL – 1.3.10
YITH WooCommerce Compare: by YITHEMES – 2.2.2
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2 – Not tested with the active version of WooCommerce
ZigWidgetClass: by ZigPress – 0.8.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
external (external-ar)
grouped (grouped)
simple (simple)
simple (simple-ar)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /shop/cart/
Checkout: #9 - /shop/checkout/
My account: #10 - /my-account/
Terms and conditions: #2762 - /customer-services/terms-condition/

### Theme ###

Name: About Automation
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: bemart2
Parent Theme Version: 1.2
Parent Theme Author URL: http://bit.ly/Themelexus
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: bemart2/woocommerce/cart/cross-sells.php
bemart2/woocommerce/checkout/form-checkout.php
bemart2/woocommerce/checkout/form-shipping.php
bemart2/woocommerce/content-product.php
bemart2/woocommerce/content-product_cat.php
bemart2/woocommerce/content-single-product.php
bemart2/woocommerce/global/breadcrumb.php
bemart2/woocommerce/loop/add-to-cart.php
bemart2/woocommerce/loop/loop-end.php
bemart2/woocommerce/loop/loop-start.php
bemart2/woocommerce/loop/rating.php
bemart2/woocommerce/single-product/related.php
bemart2/woocommerce/single-product/review.php
bemart2/woocommerce/single-product/tabs/additional-information.php
bemart2/woocommerce/single-product/up-sells.php
bemart2/woocommerce/single-product-reviews.php

### Templates ###

thumbnail: 
medium: 
medium_large: 
large: 
brand-thumb: 
yith-woocompare-image: 
shop_thumbnail: 
shop_catalog: 
shop_single: 
post-thumbnail: 
`
</details>

PLEASE HELP ME! 
sincerely 
going insane.

**Comment by mikejolley** [comment]
Our date parser requires a specific format which Excel is likely borking. View the CSV in a text editor to confirm it's correct. I believe you can choose what format a column has in excel but I'm not 100% sure as I avoid it :)

https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

`date_on_sale_to` field. Example: 2013-06-07 10:53:15

The format needs to be YYYY-MM-DD otherwise the value will be ignored. Once you've changed that I'm confident it will import correctly :) If not send us an example CSV.

Thanks!

**Comment by aboutautomation** [comment]
Yes, im fairly certain ive tried that too.   i downloaded Ron's Editor. and tried that, i also tried as a straight txt file in notepad and making changes there. and i went through schema like 5 times to check i diddnt miss something, thats when i realised my wp deault is dd-mm-yy so i tried all variations of this format too.

**Comment by aboutautomation** [comment]
After retesting all variations, again and editing in just notepad, i am still getting the same issue

**Comment by mikejolley** [comment]
Should they be set to today? It would be over already - midnight.

**Comment by aboutautomation** [comment]
oh!    i see. thanks, that worked. i got confused and now i feel completely ignornant!  when editing the individual products you can back date the sales in the calendar and it works.  THANKS !!!!!

**Comment by Readbetweenthellime** [comment]
Hi! I'm still encountering this kind of error. Can someone help me, please? Thank you! here's the file that I've been using to upload.
