### ISSUE TITLE
Exclude Sales option for fixed cart discount coupon is discounting sale products

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#18028]
Ticket: 827698-zd-woothemes

## Steps to reproduce the issue

Tested with latest master:

1. Create a coupon with 
- Fixed Cart Discount
- coupon amount example $50
- Enable Exclude sale items
- Add a few products in Products (these will be regular prices items)
2. Add one of the regular priced items to cart
3. Add a sale priced item to cart
4. Add coupon code. 

## What happens instead 

Discount gets applied to both the sale and regular priced item.

## Expected/actual behavior

It's unclear if the expected behavior should be that only the regular priced item gets discounted or the coupon code is invalid completely when sale item is also in cart with one of the regular priced items. But would expect that one of these behaviors would be the expected one.

**Comment by kloon** [comment]
@yukikatayama I tried to replicate this on master but unable, I followed the steps as you mentioned.

* Create fixed discount coupon of 10
* Added a few regular prices products to the include section
* Checked exclude sale products box
* Saved

* Added to cart one of the regular priced products
* Added to cart an on-sale product, not in the include list
* Applied the coupon code
* Only one amount of 10 was discounted as it should.

http://cld.wthms.co/sJd3FW
http://cld.wthms.co/wrPTzP
http://cld.wthms.co/Wp67go

**Comment by mikejolley** [comment]
@yukikatayama I checked the zendesk ticket. How it's working is correct - the cart contains an eligible item (something not on sale). The discount amount is the same regardless- it wouldn't really be fair to prevent it applying because the same user could just place 2 separate orders and pay the same amount.

Wording in plugin states:

> Per-cart coupons will only work if there are items in the cart that are not on sale.

Which is the case here :)

**Comment by yukikatayama** [comment]
Hey @mikejolley aaaah, thanks for the clarification!
