### ISSUE TITLE
Webhook body is empty array

### ISSUE THREAD

**Issue by achadee** [woocommerce/woocommerce#18034]
using api: wc/v1, wc/v3.1.0 , wp/v 4.9.1

Please see attached screenshot:
![screen shot 2017-12-06 at 11 12 29 am](https://user-images.githubusercontent.com/5952918/33637741-d840985a-da76-11e7-8a94-59b1447b7b19.png)

**Comment by mikejolley** [comment]
Hi,

1. Ignoring the prerequisite steps, isolation of the problem, and failing to provide system status report is a good way to get your issue closed right away or ignored. This is not the first time you've logged something without important details. We ask for them for good reason.
2. Your report contradicts your screenshot. The screenshot clearly shows WC 3.2.3 with WordPress 4.8.4, not what you reported.
3. I did tests on latest stable release with all 3 versions of the API and updated a product via admin. All 3 events logged content as can be seen here:

![woocommerce settings local wordpress dev wordpress 2017-12-06 15-03-49](https://user-images.githubusercontent.com/90977/33668272-32a3df08-da97-11e7-9950-a7cb7218c29f.png)

This issue is not reproducible with the provided information it seems. cc @claudiosanches

**Comment by achadee** [comment]
hmmm not sure whats up with the versions, I copied them from the plugins page :s

sorry, I will keep to the template from now on

here is the system status report:

`
### WordPress Environment ###

Home URL: http://tonicuk.com
Site URL: http://tonicuk.com
WC Version: 3.2.3
Log Directory Writable: ✔
WP Version: 4.8.4
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 5.6.30-0+deb8u1
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.3
WC Database Prefix: wp_tonic_
Total Database Size: 60.28MB
Database Data Size: 37.11MB
Database Index Size: 23.17MB
wp_tonic_woocommerce_sessions: Data: 0.25MB + Index: 0.02MB
wp_tonic_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_tonic_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_tonic_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_tonic_woocommerce_order_items: Data: 0.13MB + Index: 0.06MB
wp_tonic_woocommerce_order_itemmeta: Data: 2.52MB + Index: 2.97MB
wp_tonic_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_tonic_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_tonic_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_tonic_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_tonic_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_tonic_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_tonic_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_tonic_woocommerce_log: Data: 0.02MB + Index: 0.02MB
sales_june_matched: Data: 0.05MB + Index: 0.00MB
sale_june: Data: 0.02MB + Index: 0.00MB
wp_tonic_commentmeta: Data: 1.17MB + Index: 0.09MB
wp_tonic_comments: Data: 1.52MB + Index: 0.72MB
wp_tonic_datalist: Data: 0.00MB + Index: 0.00MB
wp_tonic_links: Data: 0.02MB + Index: 0.02MB
wp_tonic_optins: Data: 0.02MB + Index: 0.03MB
wp_tonic_optin_meta: Data: 0.02MB + Index: 0.03MB
wp_tonic_options: Data: 4.36MB + Index: 1.23MB
wp_tonic_postmeta: Data: 12.48MB + Index: 9.88MB
wp_tonic_posts: Data: 3.42MB + Index: 1.17MB
wp_tonic_relevanssi: Data: 2.20MB + Index: 4.80MB
wp_tonic_relevanssi_log: Data: 0.02MB + Index: 0.00MB
wp_tonic_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB
wp_tonic_reorder_post_rel: Data: 0.06MB + Index: 0.00MB
wp_tonic_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_tonic_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_tonic_termmeta: Data: 0.02MB + Index: 0.03MB
wp_tonic_terms: Data: 0.02MB + Index: 0.03MB
wp_tonic_term_relationships: Data: 0.23MB + Index: 0.13MB
wp_tonic_term_taxonomy: Data: 0.05MB + Index: 0.03MB
wp_tonic_usermeta: Data: 0.19MB + Index: 0.13MB
wp_tonic_users: Data: 0.02MB + Index: 0.05MB
wp_tonic_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_tonic_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfConfig: Data: 0.27MB + Index: 0.00MB
wp_tonic_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfFileMods: Data: 3.52MB + Index: 0.00MB
wp_tonic_wfHits: Data: 1.02MB + Index: 1.14MB
wp_tonic_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_tonic_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_tonic_wfLeechers: Data: 1.02MB + Index: 0.00MB
wp_tonic_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfLogins: Data: 0.08MB + Index: 0.03MB
wp_tonic_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_tonic_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfPendingIssues: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_tonic_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_tonic_wfStatus: Data: 0.13MB + Index: 0.09MB
wp_tonic_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_tonic_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_tonic_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_tonic_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_tonic_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 25
acf-field-group: 10
attachment: 863
custom_banner: 3
custom_homepage: 11
custom_inspiration: 13
custom_widget: 6
flamingo_contact: 116
flamingo_inbound: 77
grid_template: 7
ig_campaign: 1
ig_message: 5
nav_menu_item: 61
page: 18
post: 5
product: 615
product_variation: 2719
revision: 556
shop_coupon: 12
shop_order: 1078
shop_order_refund: 38
shop_webhook: 5
stores: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (43) ###

AddToAny Share Buttons: by AddToAny – 1.7.22
Advanced Custom Fields PRO: by Elliot Condon – 5.6.7
Akismet Anti-Spam: by Automattic – 4.0.1
A4 Barcode Generator WooCommerce: by UkrSolution – 0.1.2 – Not tested with the active version of WooCommerce
Contact Form 7: by Takayuki Miyoshi – 4.9.1
Easy SwipeBox: by Leonardo Giacone – 1.1.0
Flamingo: by Takayuki Miyoshi – 1.7
Product Sales Report Pro for WooCommerce: by Potent Plugins – 2.1.4 – Not tested with the active version of WooCommerce
Icegram - Popups, Optins, CTAs & lot more...: by icegram – 1.10.14
Max Mega Menu - Pro Addon: by Tom Hemsley – 1.6.5
Max Mega Menu: by Tom Hemsley – 2.4
WooCommerce Product Filter: by Mihajlovic Nenad – 6.4.5 – Not tested with the active version of WooCommerce
Product Enquiry for WooCommerce: by WisdmLabs – 2.3 – Not tested with the active version of WooCommerce
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
Relevanssi: by Mikko Saari – 4.0.2
Remove Taxonomy Base Slug: by Alexandru Vornicescu – 2.1
ReOrder Post Within Categories: by Aurélien Chappard
Aurovrata Venet – 1.3.0

Say What?: by Lee Willis – 1.9.1
Simple Page Ordering: by Jake Goldman
10up – 2.2.4

SVG Support: by Benbodhi – 2.3.11
Template Bespoke Plugins: by Apex1 Studios - Ray Lau – 4.7
Template Setup Plugins: by Apex1 Studios - Ray Lau – 4.6
TinyMCE Advanced: by Andrew Ozz – 4.6.3
User Role Editor: by Vladimir Garagulya – 4.38
WooCommerce Brands: by WooThemes – 1.5.0 – 1.5.2 is available – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.6.0 – Not tested with the active version of WooCommerce

WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.0.15
WooCommerce POS Pro: by kilbot – 0.4.13 – Not tested with the active version of WooCommerce
WooCommerce POS: by kilbot – 0.4.15
WooCommerce Smart Coupons: by WooCommerce – 3.3.8 – Not tested with the active version of WooCommerce
WooCommerce Stock Manager: by Vladislav Musílek – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by Automattic – 3.0.2 – 3.0.4 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.3 – 3.2.5 is available
Wordfence Security: by Wordfence – 6.3.22
WordPress Importer: by wordpressdotorg – 0.6.3
Hustle: by WPMU DEV – 5.1.5.1
Yoast SEO: by Team Yoast – 5.8
WP Database Backup: by Prashant Walke – 4.5.2
WP-ShowHide: by Lester 'GaMerZ' Chan – 1.04
WP Smush: by WPMU DEV – 2.7.6
WP Tiles: by Mike Martel – 1.1.2
YITH WooCommerce Bulk Product Editing Premium: by YITHEMES – 1.2.6

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #28 - /clothing-accessories/
Basket: #29 - /cart/
Checkout: #30 - /checkout/
My account: #31 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Tonic V2.0
Version: 2.0
Author URL: http://www.dreamabstract.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: tonic2/woocommerce/emails/email-styles.php
`

**Comment by mikejolley** [comment]
If you have a clean install or staging, suggest you test there to confirm the hook works - then rule out installed plugins as source of conflict.

**Comment by achadee** [comment]
We have a clean staging where this integration is working 100%. Usually I would look into plugin issues but the weird thing is that its happening on multiple customer accounts. Which leads me to believe that the issue is to do with the v1 API. 

After diving into this issue a bit more, I've discovered that webhooks do in fact send after clicking "update" on the product admin page. However it is also triggering multiple empty array webhooks. I havn't yet determined if these webhooks are bound to the same event or a plugin, But it seems strange that we have over 5 customers experiencing this issue.

I will cross check the plugins on all the customers accounts to see if there are any similarities.

**Comment by jjxtra** [comment]
Seeing this as well after updating woocommerce plugins recently... :(

**Comment by jjxtra** [comment]
I think I figured out what causes this - when going into cancelled subscriptions and re-activating a subscription, the web hook comes back as an empty array. For new subscriptions it appears to work fine. Would love a fix soon!

**Comment by jjxtra** [comment]
Deactivating woocommerce and woocommerce subscriptions, then reactivating and re-doing the setup wizard fixed the issue. I have to do this everytime I update the woocommerce plugin, otherwise these errors start happening.
