### ISSUE TITLE
get_price_html does not output correct price in custom loop

### ISSUE THREAD

**Issue by danyob** [woocommerce/woocommerce#18037]
When using a custom query for products and hooking into woocommerce_get_price_html the price returned is the first product price for every instance in the query.

Example, in a custom query i do the following:

$product = wc_get_product( get_the_id() );
echo $product->id;
echo $product->get_price_html();

When outputting $product->id this obviously returns the same ID that was inputted into wc_get_product().

When outputting $product->get_price_html() this returns the price for the first product to be returned by the query. This same price is then shown for every product returned

**Comment by mikejolley** [comment]
Sounds like your hook into `woocommerce_get_price_html` is breaking it. You didn't show what code if running there. I have committed a unit test to prove this is not a problem and each get_price_html() call runs independently.

**Comment by danyob** [comment]
Hi Mike,

I have added code showing how i amend the price.

**Comment by mikejolley** [comment]
I think you need to read up on how filters work - your function does not return anything.
