### ISSUE TITLE
Built in import not placing variations under parent when id:### is used

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#18047]
As described in the title, when importing with the built in importer and using the `id:###` format in the Parent column, variations are not placed under the parent product. 

## Steps to reproduce the issue

*How I did it, at least*

1. Create a new variable product with Size attribute: `Small | Medium | Large`
2. Create variations from all attributes and set regular prices to 10
3. Publish
4. Export variations
5. Delete variations from product
6. Delete IDs from variations in CSV, confirm `Parent` column has `id:###` format
7. Import CSV, receive success message
8. View product, variations are not there

Reported in 817037-zen.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/18061
