### ISSUE TITLE
Unable to create product gallery via REST API v2

### ISSUE THREAD

**Issue by asFloppyDisk** [woocommerce/woocommerce#18041]
Hi! I hope that's the right place to post my issue. 
I'm trying to create a new product with variations and images and a product gallery via the REST API v2. The call is from an ERP-System.
The Post Method for creating a product works, the variations are created and for each one a image is set. But when i want to update the product to add a product gallery i always get the error code 400. 

## Steps to reproduce the issue

1. Upload each image via the endpoint: post /wp-json/wp/v2/media
Headervalues are: Authorization: Bearer + <token>; Content-Disposition: attachment; <filename>; Content-Type image/png or image/jpeg depending on the image to upload 
Body is just the image file - this upload is working

2. upload/create the product via: post /wp-json/wc/v2/products - is working

3. upload/create each variation with its image and attributes via: post /wp-json/wc/v2/products/<id>/variations - this is also working

4. Now i want to update the product and create a product gallery with the images from its variations via: put /wp-json/wc/v2/products/<id> . So i do not want to upload the images again, i just want to select the existing ones for the gallery by image id.
I tried different requests but all i get is the response 400 with no data change in the body.
this is one example of a request body: (the header contains the authorization)
{"images":[{"id":5123,"position":0},{"id":5125,"position":1},{"id":5127,"position":2}]}

another was with "source_url" instead of id and in the third i set the meta-data with:
 "meta_data":[{"key":"_product_image_gallery","value":"5123,5125,5127"}]

I really hope somebody can help me!

## WordPress Environment

<details>
Home URL: |   | https://werbeagenturoberoesterreich.at
Site URL: |   | https://werbeagenturoberoesterreich.at
WC Version: |   | 3.2.3
Log-Verzeichnis schreibbar: |   |✔ /homepages/14/d533559524/htdocs/clickandbuilds/Headdress/wp-content/uploads/wc-logs/
WP-Version: |   | 4.8.3
WP Multisite: |   | –
WP Memory Limit: |   | 256 MB
WP Debug-Modus: |   | –
WP Cron: |   |  ✔
Sprache: |   | de_DE

Server-Info: |   | Apache
-- | -- | --
PHP-Version: |   | 7.0.26
PHP Post Max Size: |   | 100 MB
PHP Time Limit: |   | 50000
PHP Max Input Vars: |   | 1000
cURL-Version: |   | 7.38.0, OpenSSL/1.0.1t
SUHOSIN installiert: |   | –
MySQL-Version: |   | 5.5.57 - Wir empfehlen mindestens MySQL-Version 5.6. Siehe: WordPress-Anforderungen
Maximale Upload-Größe: |   | 100 MB
Standard-Zeitzone ist UTC: |   |  ✔
fsockopen/cURL: |   |  ✔
SoapClient: |   |  ✔
DOMDocument: |   |  ✔
GZip: |   |  ✔
Multibyte-String: |   |  ✔
Remote Post: |   |  ✔
Remote Get: |   |  ✔

WC Datenbank-Version: |   | 3.2.3
Datenbankpräfix |   | IGEUwppQ
MaxMind GeoIP Datenbank: |   | /homepages/14/d533559524/htdocs/clickandbuilds/Headdress/wp-content/uploads/GeoIP.dat
Datenbank-Gesamtgröße |   | 52.07MB
Datenbank-Datengröße |   | 47.03MB
Datenbank-Indexgröße |   | 5.04MB
IGEUwppQwoocommerce_sessions |   | Daten: 0.04MB + Index: 0.00MB
IGEUwppQwoocommerce_api_keys |   | Daten: 0.00MB + Index: 0.01MB
IGEUwppQwoocommerce_attribute_taxonomies |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoocommerce_downloadable_product_permissions |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoocommerce_order_items |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoocommerce_order_itemmeta |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoocommerce_tax_rates |   | Daten: 0.00MB + Index: 0.01MB
IGEUwppQwoocommerce_tax_rate_locations |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoocommerce_shipping_zones |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoocommerce_shipping_zone_locations |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoocommerce_shipping_zone_methods |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoocommerce_payment_tokens |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoocommerce_payment_tokenmeta |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoocommerce_log |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQcommentmeta |   | Daten: 0.00MB + Index: 0.01MB
IGEUwppQcomments |   | Daten: 0.00MB + Index: 0.01MB
IGEUwppQlayerslider |   | Daten: 0.03MB + Index: 0.00MB
IGEUwppQlayerslider_revisions |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQlinks |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQoptions |   | Daten: 1.33MB + Index: 0.18MB
IGEUwppQpostmeta |   | Daten: 8.02MB + Index: 3.21MB
IGEUwppQposts |   | Daten: 34.66MB + Index: 0.49MB
IGEUwppQtermmeta |   | Daten: 0.02MB + Index: 0.02MB
IGEUwppQterms |   | Daten: 0.13MB + Index: 0.23MB
IGEUwppQterm_relationships |   | Daten: 0.10MB + Index: 0.24MB
IGEUwppQterm_taxonomy |   | Daten: 0.10MB + Index: 0.10MB
IGEUwppQusermeta |   | Daten: 0.06MB + Index: 0.02MB
IGEUwppQusers |   | Daten: 0.00MB + Index: 0.01MB
IGEUwppQwfBadLeechers |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfBlockedCommentLog |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfBlockedIPLog |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfBlocks |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfBlocksAdv |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfConfig |   | Daten: 0.25MB + Index: 0.01MB
IGEUwppQwfCrawlers |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfFileMods |   | Daten: 0.95MB + Index: 0.20MB
IGEUwppQwfHits |   | Daten: 0.20MB + Index: 0.05MB
IGEUwppQwfHoover |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfIssues |   | Daten: 0.07MB + Index: 0.00MB
IGEUwppQwfKnownFileList |   | Daten: 0.49MB + Index: 0.06MB
IGEUwppQwfLeechers |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfLockedOut |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfLocs |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfLogins |   | Daten: 0.01MB + Index: 0.00MB
IGEUwppQwfNet404s |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfNotifications |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfPendingIssues |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfReverseCache |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfScanners |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfSNIPCache |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfStatus |   | Daten: 0.11MB + Index: 0.05MB
IGEUwppQwfThrottleLog |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwfVulnScanners |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQwoof_query_cache |   | Daten: 0.00MB + Index: 0.00MB
IGEUwppQyoast_seo_links |   | Daten: 0.44MB + Index: 0.10MB
IGEUwppQyoast_seo_meta |   | Daten: 0.02MB + Index: 0.03MB

attachment |   | 653
-- | -- | --
avia_framework_post |   | 37
customize_changeset |   | 7
nav_menu_item |   | 37
page |   | 42
portfolio |   | 10
post |   | 13
product |   | 251
product_variation |   | 1497
revision |   | 1048
shop_order |   | 3
wpcf7_contact_form |   | 3

Sichere Verbindung (HTTPS): |   |  ✔
Fehler vor Besuchern verstecken |   |  ✔

Akismet Anti-Spam |   | von Automattic – 4.0.1
Better Search Replace |   | von Delicious Brains – 1.3.1
Capability Manager Enhanced |   | von Jordi Canals, Kevin Behrens – 1.5.7
Contact Form 7 |   | von Takayuki Miyoshi – 4.9.1
Cookie Notice |   | von dFactory – 1.2.40
Duplicate Post |   | von Enrico Battocchi – 3.2
Enable Media Replace |   | von Måns Jonasson – 3.1.1
Facebook Messenger for WordPress |   | von Brontobytes – 2.0
JWT Authentication for WP-API |   | von Enrique Chavez – 1.2.4
WP REST API |   | von WP REST API Team – 2.0-beta15
UpdraftPlus - Backup/Restore |   | von UpdraftPlus.Com, DavidAnderson – 2.13.13.22
WooCommerce Catalog Enquiry |   | von WC Marketplace, The Grey Parrots – 3.1.4
WOOF - WooCommerce Products Filter |   | von realmag777 – 1.1.7 – Nicht mit der aktiven Version von WooCommerce getestet
WooCommerce |   | von Automattic – 3.2.3 – 3.2.5 ist verfügbar
Yoast SEO Premium |   | von Team Yoast – 5.7.1
WhatsApp Chat WP |   | von Alexandre Caporal – 2.0

</details>

**Comment by claudiosanches** [comment]
I just made a test and works just fine.

![screenshot from 2017-12-06 18-43-11](https://user-images.githubusercontent.com/1264099/33684413-594b50aa-dab5-11e7-9ffd-87577a4d6164.png)

```json
	"images": [
		{
			"id": 197,
			"date_created": "2017-11-29T08:01:37",
			"date_created_gmt": "2017-11-29T12:01:37",
			"date_modified": "2017-11-29T08:01:37",
			"date_modified_gmt": "2017-11-29T12:01:37",
			"src": "https:\/\/woo.dev\/wp-content\/uploads\/2017\/11\/logo.jpg",
			"name": "logo.jpg",
			"alt": "",
			"position": 0
		},
		{
			"id": 195,
			"date_created": "2017-11-29T08:01:36",
			"date_created_gmt": "2017-11-29T12:01:36",
			"date_modified": "2017-11-29T08:01:36",
			"date_modified_gmt": "2017-11-29T12:01:36",
			"src": "https:\/\/woo.dev\/wp-content\/uploads\/2017\/11\/beanie-with-logo.jpg",
			"name": "beanie-with-logo.jpg",
			"alt": "",
			"position": 1
		},
		{
			"id": 193,
			"date_created": "2017-11-29T08:01:35",
			"date_created_gmt": "2017-11-29T12:01:35",
			"date_modified": "2017-11-29T08:01:35",
			"date_modified_gmt": "2017-11-29T12:01:35",
			"src": "https:\/\/woo.dev\/wp-content\/uploads\/2017\/11\/t-shirt-with-logo.jpg",
			"name": "t-shirt-with-logo.jpg",
			"alt": "",
			"position": 2
		}
	],
```

Sounds like an issue with your installation, maybe some plugin causing a conflict, but for what I'm testing, there is no problem on WooCommerce core, that's why I'm closing this issue.
