### ISSUE TITLE
Wrong redirection from user Profile View Link to Shop

### ISSUE THREAD

**Issue by gwgw** [woocommerce/woocommerce#18043]
Hello i have local installation of Wordpress 4.7 and WC lastest version
I created User with role customer for testing WP roles:
Username: customer
First Name: cathrine
Last Name: Customer
Nickname: customer
I know, this is really dummy-name for user testing,
now for this particular user url looks like this:
localhost/my/path/to/wp/author/customer/
When i'm  trying to click View link from All Users Menu its redirect me to shop page
Only for customer role,other links works just fine, no other plugins activated

Is word 'customer' not allowed as dummy nickname ?
Or  user role = customer  brokes my link to view user profile,not shop page?

**Comment by claudiosanches** [comment]
Customers are not authors, that's why is redirect to the shop main page.
This is the desired effect and is working as it should, since customers should not have any public "profile" in an store.
