### ISSUE TITLE
Too many untested plugins in a major update makes it impossible to proceed.

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18044]
![update](https://user-images.githubusercontent.com/8536129/33680859-868aab2e-da88-11e7-9277-1b85fcdf444c.png)

This pop-up doesn't scroll, so as a result if there are  a bunch listed you can end up "stuck" and unable to proceed based on your screen height.

The fix should be to look at the viewports height and implement a scroll instead I believe.

**Comment by claudiosanches** [comment]
What version?
We fixed it on 3.2 including a scroll bar.
See https://github.com/woocommerce/woocommerce/issues/17284#issuecomment-338257088

**Comment by WPprodigy** [comment]
Prolly fixed then, this is an older report I never got around too :)
