### ISSUE TITLE
Importer not importing global attributes

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#18057]
Just wiped out all the product attributes in the shop by selecting the right columns.

Not sure how the attributes are matched to the CSV, but there's no documentation on the matter or instructions about how to link them. 

Steps to reproduce:

Export **variable products with 1 or more global attributes** using the exporter:
`/wp-admin/edit.php?post_type=product&page=product_exporter`

Reimport the exact same `.csv` file back into the site with
`/wp-admin/edit.php?post_type=product&page=product_importer`

Check products that _had_ attributes

**Comment by mikejolley** [comment]
Related https://github.com/woocommerce/woocommerce/pull/18029 and https://github.com/woocommerce/woocommerce/issues/17923
