### ISSUE TITLE
Import should show preview product before confirming

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#18055]
wp-import-pro is a good example here. When I upload a CSV file, the only option i have is match the fields then cross my fingers.

Would be helpful to see another page that previews what data is coming into the right places. Always have an issue with importing the attributes wrong. Would be nice to see the mistakes before I import them

**Comment by mikejolley** [comment]
This one would require extensive refactoring and I'm not sure how useful it would be. It would still require importing of rows, but then you'd need a separate merge event to persist the data or additional steps and ways to 'view' a product which is not really a product. 

This could also introduce conflicts and other issues, as well as a reduction in performance and the risk of having ghost products sitting around filling up the DB. Probably best this goes to http://ideas.woocommerce.com/forums/133476-woocommerce and only gets tackled if there is a lot of demand.

Your other suggestion (remembering fields) is a good, quick, enhancement so I'll leave that open.
