### ISSUE TITLE
Hide out of stock fails on singule product page

### ISSUE THREAD

**Issue by dominic-p** [woocommerce/woocommerce#18051]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Enable "Hide out of stock items from the catalog" under Settings > Products > Inventory
2. Visit the permalink of an out-of-stock product

## Expected/actual behavior

When I follow those steps, I see...
The product page (without an add to cart button)

I was expecting to see...
404 page

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## Notes

I remember reading in the WC 3.x release notes that taxonomies were being leveraged more for increased performance. It appears a consequence of this is [WP Bug #24819](https://core.trac.wordpress.org/ticket/24819) is now an issue. Basically, the `tax_query` query var is never parsed for [singular queries](https://core.trac.wordpress.org/browser/tags/4.9.1/src/wp-includes/class-wp-query.php#L1960).

When I look at the global `$wp_query` var on a single product page for an out-of-stock product, I see that `WC_Query` parsed the query and added the appropriate `tax_query` to `$wp_query->query_vars`, but `$wp_query->tax_query` remains empty because the tax query was never parsed.

That WP bug is 4 years old and closed as wontfix, so I'm not really sure what the solution is here. Any ideas?

**Comment by mikejolley** [comment]
The setting "Hide out of stock items from the catalog" refers to archives/listings of products. The actual single product pages are never hidden and can be accessed directly. This was the case before the taxonomy change - these links never 404. Thats intended, and I suspect expected by many users who still want products visible direct or don't want to damage SEO.

If you want them removed completely, you'll need a script to look for out of stock products and delete/draft them.

**Comment by dominic-p** [comment]
Thanks for the explanation @mikejolley. I appreciate it.

I remember it working differently before, but that could just be my imagination. I can work around it by hooking into `template_redirect` and checking `$product->is_visible()`. It's not great for performance, but it does the trick.
