### ISSUE TITLE
New Order Email is not sending all of a sudden.

### ISSUE THREAD

**Issue by PaulAlfredBain** [woocommerce/woocommerce#18052]
Up until 3 days ago, we were receiving new order emails fine. Now we don't receive any. I changed the email recipient and it still doesn't work.
Please advise.

Thanks
Paul

**Comment by PaulAlfredBain** [comment]
I think this is due to a php7 upgrade? How do i fix this?

**Comment by kloon** [comment]
Please see https://docs.woocommerce.com/document/email-faq/
