### ISSUE TITLE
Variable products no longer change

### ISSUE THREAD

**Issue by ArxaggelosAlexandros** [woocommerce/woocommerce#18067]
Simple, the variable product custom images stopped working. I made new product fresh from the start, put custom photos and they do not work.

I contacted ninja forms customer help and they told me this is woocommerce bug not theirs.

In the end of the day how can I downgrade the woocommerce so it starts working again? Because it was an update that broke it.

**Comment by mikejolley** [comment]
I know you just pasted this question in multiple places like the FB group but you cannot expect help without providing basic details i.e. the status report and where the site is located. 

> Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action.

See the list on https://github.com/woocommerce/woocommerce/issues/new

Sounds like a theme issue anyhow?

Thanks
