### ISSUE TITLE
Taxes shown on Cart page when as per the settings they should not be shown

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce#18069]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Here are my tax settings ![](http://cld.wthms.co/yIsEZg+)
[Direct Link](http://cld.wthms.co/yIsEZg+)
2. Here is my tax rate for the destination ![](http://cld.wthms.co/Czg3cr+)
[Direct Link](http://cld.wthms.co/Czg3cr+)
3. Ensure that the user logged in has the address updated to `81 Pleasant St, ATTLEBORO, 02703` in the profile.
4. Here is the shipping setting ![](http://cld.wthms.co/GqakON+)
[Direct Link](http://cld.wthms.co/GqakON+)

## Expected/actual behavior

Now as per the above setting, even though I am logged in as the user with the above address set in the profile, when I add a product costing $8 to cart, it calculates the tax:

![](http://cld.wthms.co/C03UW5+)
[Direct Link](http://cld.wthms.co/C03UW5+)

Now let's use the  shipping calculator and select 07607/NJ:

![](http://cld.wthms.co/mtUUVO+)
[Direct Link](http://cld.wthms.co/mtUUVO+)

We can now see that the tax is not shown anymore.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

### WordPress Environment ###

Home URL: http://woo.dev
Site URL: http://woo.dev
WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.13.1
PHP Version: 7.0.20-2~ubuntu14.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 5.95MB
Database Data Size: 3.96MB
Database Index Size: 1.99MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.06MB + Index: 0.05MB
wp_postmeta: Data: 1.14MB + Index: 1.08MB
wp_posts: Data: 0.16MB + Index: 0.06MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 171
follow_up_email: 1
nav_menu_item: 5
page: 9
post: 6
product: 2
product_variation: 15
revision: 12
shop_coupon: 1
shop_order: 9
wc_booking: 1
wc_voucher: 2
wc_voucher_template: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (9) ###

Core Control: by Dion Hulse – 1.2.1
Loco Translate: by Tim Whitlock – 2.0.16
Server-Mail-Check: by Praveen – 1.0
Test Payment Module for Woocommerce: by Sean Barton (Tortoise IT) – 1.5 – Not tested with the active version of WooCommerce
WC Variations Radio Buttons: by 8manos – 2.0.0 – Not tested with the active version of WooCommerce
What Template Am I Using: by Eric King – 0.2.0
What Template: by ironprogrammer – 0.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.4 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2 - /sample-page/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-xyz/
Terms and conditions: #1011 - /terms/

### Theme ###

Name: Twenty Sixteen
Version: 1.3 – 1.4 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: twentysixteen/woocommerce/emails/email-order-details.php

</details>

821948-zen

**Comment by mikejolley** [comment]
> Now as per the above setting, even though I am logged in as the user with the above address set in the profile, when I add a product costing $8 to cart, it calculates the tax:

User has shipping address US, MA, ATTLEBORO, 02703
Tax is based on shipping address
Tax is for US, MA, ATTLEBORO, 02703
So the tax is correct to be showing.

If you changing to 07607/NJ, then tax is correct to now show because it doesn't match the rate.

Therefore your screenshots are all correct. 

The only thing I spotted locally is the shipping country was not imported from the user profile, but from shop base. This is a separate bug I'll fix now.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18076
