### ISSUE TITLE
WooCommerce Rest API - update order line item quantity.

### ISSUE THREAD

**Issue by shukiAnavi** [woocommerce/woocommerce#18062]
Hi!

I'm having a problem with the order API.

I've successfully created a new order using this request body:

{
    "set_paid": false,
    "billing": {
        "first_name": "John",
        "last_name": "Doe",
        "address_1": "969 Market",
        "address_2": "",
        "city": "San Francisco",
        "state": "CA",
        "postcode": "94103",
        "country": "US",
        "email": "john.doe@example.com",
        "phone": "(555) 555-5555"
    },
    "shipping": {
        "first_name": "John",
        "last_name": "Doe",
        "address_1": "969 Market",
        "address_2": "",
        "city": "San Francisco",
        "state": "CA",
        "postcode": "94103",
        "country": "US"
    },
    "line_items": [
        {
            "product_id": 10,
            **"quantity": 2**
        }
    ],
    "shipping_lines": [
        {
            "method_id": "flat_rate",
            "method_title": "Flat Rate",
            "total": "10"
        }
    ]
}

In this case the cart total is calculated correctly.

For example:
If the product cost is $200 and the quantity is 2, the total will be $400.

The problem occur when I want to update the item quantity.

I'm calling to this endpoint:

PUT /wp-json/wc/v2/orders/<id>

With the updated quantities (including the line item id of the order):

{
    "set_paid": false,
    "billing": {
        "first_name": "John",
        "last_name": "Doe",
        "address_1": "969 Market",
        "address_2": "",
        "city": "San Francisco",
        "state": "CA",
        "postcode": "94103",
        "country": "US",
        "email": "john.doe@example.com",
        "phone": "(555) 555-5555"
    },
    "shipping": {
        "first_name": "John",
        "last_name": "Doe",
        "address_1": "969 Market",
        "address_2": "",
        "city": "San Francisco",
        "state": "CA",
        "postcode": "94103",
        "country": "US"
    },
    "line_items": [
        {
            **"id": 10,**
            "product_id": 10,
            **"quantity": 4**
        }
    ],
    "shipping_lines": [
        {
            "method_id": "flat_rate",
            "method_title": "Flat Rate",
            "total": "10"
        }
    ]
}

I expected that the total will be  $800 (4*200=800) but instead the item cost in the cart is updating to $100 and the total is $400.

It seems that it takes the previous total ($400) and divides it by the new quantity (4).

Where am I wrong?

Wordpress version: 4.9.1
WooCommerce version: 3.2.5

**Comment by mikejolley** [comment]
Changing the quantity does not recalc line prices. https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties 

You need to send the subtotal, total, subtotal_tax, and total_tax also if changing costs at a later date.

Thanks

**Comment by shukiAnavi** [comment]
Thanks :beer:

**Comment by leojbchan** [comment]
"You need to send the subtotal, total, subtotal_tax, and total_tax also if changing costs at a later date."
- Thanks for this.  This works well when a discount is not applied.

However, when a discount is applied manually sending the subtotal and total overrides the automatic discount calculations.  Is there a way to update the line items and preserve the discounts?

**Comment by Balthazaar** [comment]
> Changing the quantity does not recalc line prices. https://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties
> 
> You need to send the subtotal, total, subtotal_tax, and total_tax also if changing costs at a later date.
> 
> Thanks

But why? why would someone build this sort of api like this? What's the purpose of changing the qty feature then?
