### ISSUE TITLE
When changing an existing attribute value, all of the variations of that value aren't updated

### ISSUE THREAD

**Issue by AJerm** [woocommerce/woocommerce#18078]
If you have a variable product, with multiple attributes and values. You then generate all the variations and assign prices.

If you edit one of the attribute values, when you save, all of the variations that have the changed value assigned get reset. 

Instead, they should automatically be updated to the new changed attribute value.

This would save having to go through and reassign each one manually, which is highly prone to human error when you have  lot of variations.

**Comment by WPprodigy** [comment]
I'm guessing you are using custom attributes defined at the product level, correct? When you "edit one of the attribute values" or switch up the order, there is really no way for it to keep it's assignment.

If you need to make edits like this, I would recommend using global attributes that are created at Products > Attributes.

**Comment by AJerm** [comment]
Hey WPP, 

Thanks for the reply :)

That's correct. I'm quite new to WooCommerce and this is one of the stock issues that seems to be arising regularly as I tweak and attempt to improve my listings. 

Thanks for pointing out the main Products -> Attributes page. I hadn't noticed that as I don't have enough products with attributes that will apply to more than one as of yet.

I note how it does say you can't rename attributes later on though. Wouldn't this negate my requirement to update the values, or is this just referencing the high level attribute name and not it's values? On a product level it seems you can rename attributes? It's just the attribute values that get lost in the variations references. 

It would be nice if when you renamed a product attribute value it updated all the variants that had previously referenced it.

**Comment by WPprodigy** [comment]
Hmm, never noticed that `Please note: you cannot rename an attribute later on.` line before. As far as I can tell, you can definiltey rename an attribute after it's created and it still stays connected to the product. Renaming/editing terms is also possible. CCing @mikejolley on that, think it could be removed unless I'm missing something.

> It would be nice if when you renamed a product attribute value it updated all the variants that had previously referenced and relied on it.

That is how it works :)

**Comment by mikejolley** [comment]
Calebs comment is correct. It wouldn't be possible to know what changed to what when using custom text attributes.

"Please note: you cannot rename an attribute later" can be removed.
