### ISSUE TITLE
Customizing the HTML data attributes on add-to-cart buttons

### ISSUE THREAD

**Issue by renventura** [woocommerce/woocommerce#18079]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

Hello!

For a project I'm working on, I'm attempting to add custom HTML data attributes to the add-to-cart buttons on product archives, the output for which is found [here](https://github.com/woocommerce/woocommerce/blob/426897ac2d3d2d198427a60e229219d5b2cd8618/templates/loop/add-to-cart.php#L25). The `woocommerce_loop_add_to_cart_link ` filter requires developers to deal with the entirety of the output. Normally, I wouldn't consider this a big deal, although I think it's unnecessary. 

However, this becomes an issue with the `$class` variable, as it's not available to the filter. Therefore, when overwriting the output, I'm stuck duplicating the `woocommerce_loop_add_to_cart_args` filter's defaults array, defined [here](https://github.com/woocommerce/woocommerce/blob/5b0df590c08799e8007f456b97cf595f26b8e3b9/includes/wc-template-functions.php#L848), and reapplying the filter. Here's my example code:

```php
add_filter( 'woocommerce_loop_add_to_cart_link', 'rv_add_cart_link_atts', 10, 2 );
function rv_add_cart_link_atts( $link, $product ) {

	// Get default button classes
	if ( $product ) {
		$defaults = array(
			'quantity' => 1,
			'class' => implode( ' ', array_filter( array(
				'button',
				'product_type_' . $product->get_type(),
				$product->is_purchasable() && $product->is_in_stock() ? 'add_to_cart_button' : '',
				$product->supports( 'ajax_add_to_cart' ) ? 'ajax_add_to_cart' : '',
			) ) ),
		);
	}
	$class = apply_filters( 'woocommerce_loop_add_to_cart_args', $defaults )['class'];

	// WC versions before 3.3 did not have the product description aria-label
	if ( version_compare( get_option( 'woocommerce_version' ), '3.3.0', '<' ) ) {

		$link = sprintf( '<a rel="nofollow" href="%s" data-quantity="%s" data-product_id="%s" data-product_sku="%s" data-custom_attribute="%s" class="%s">%s</a>',
			esc_url( $product->add_to_cart_url() ),
			esc_attr( isset( $quantity ) ? $quantity : 1 ),
			esc_attr( $product->get_id() ),
			esc_attr( $product->get_sku() ),
			esc_attr( 'some_value' ),
			esc_attr( isset( $class ) ? $class : 'button' ),
			esc_html( $product->add_to_cart_text() )
		);

	} else {

		$link = sprintf( '<a rel="nofollow" href="%s" data-quantity="%s" data-product_id="%s" data-product_sku="%s" data-custom_attribute="%s" class="%s" aria-label="%s">%s</a>',
			esc_url( $product->add_to_cart_url() ),
			esc_attr( isset( $quantity ) ? $quantity : 1 ),
			esc_attr( $product->get_id() ),
			esc_attr( $product->get_sku() ),
			esc_url( 'some_value' ),
			esc_attr( isset( $class ) ? $class : 'button' ),
			esc_attr( $product->add_to_cart_description() ),
			esc_html( $product->add_to_cart_text() )
		);
	}

	return $link;
}
```

In the very least, this can be solved by making `$args` ([here](https://github.com/woocommerce/woocommerce/blob/5b0df590c08799e8007f456b97cf595f26b8e3b9/includes/wc-template-functions.php#L858)) available to the `woocommerce_loop_add_to_cart_link` filter. Then, the process of duplicating the `$defaults` array and reapplying the `woocommerce_loop_add_to_cart_args` filter would not be needed.

Even better, I'd suggest assembling the add-to-cart link (`loop/add-to-cart.php`) from the `woocommerce_loop_add_to_cart_args` filter. Then, all that would be needed is to filter the default attributes - no need to copy the default output (DRY). I'd be happy to put together an example if anyone would like to take a look.

If anyone has a better solution to this than the one I came up with, or if I'm missing something, I'd appreciate any suggestions. Thanks for taking the time to read through this!

**Comment by WPprodigy** [comment]
Think I've come across this myself in the past. Passing $args to the `woocommerce_loop_add_to_cart_link` filter seems to be best case for now since it doesn't break anything.

I'm interested in what you have in mind for your second idea (assembling the link based on the filter), but keep in mind there will always be the need to give people the ability to fully override the markup. So if it's not done on this filter, there will just need to be another ¯\\\_(ツ)\_/¯

**Comment by renventura** [comment]
I agree that simply passing `$args` to the filter would be the easiest solution for now. 

Regarding my second idea: I also considered the need to override the markup, so it would still be filterable via the same filter; The only thing that would change is how the default markup is assembled. Here's a rundown of my thoughts (check the code comments)...

First, modify the `woocommerce_template_loop_add_to_cart` [function](https://github.com/woocommerce/woocommerce/blob/5b0df590c08799e8007f456b97cf595f26b8e3b9/includes/wc-template-functions.php#L844).

```php
function woocommerce_template_loop_add_to_cart( $args = array() ) {
	global $product;

	if ( $product ) {

		$defaults = array(
			'quantity' => 1, // This may be kept for backward compatibility???
			'data-quantity' => 1, // Introduce to reflect the attribute key
			'class'    => implode( ' ', array_filter( array(
				'button',
				'product_type_' . $product->get_type(),
				$product->is_purchasable() && $product->is_in_stock() ? 'add_to_cart_button' : '',
				$product->supports( 'ajax_add_to_cart' ) ? 'ajax_add_to_cart' : '',
			) ) ),
		);

		$args = apply_filters( 'woocommerce_loop_add_to_cart_args', wp_parse_args( $args, $defaults ), $product );

		// Assemble the HTML attributes from filterable $args
		$attributes = array();
		foreach ( $args as $att => $value ) {
			$attributes[] = sprintf( '%s="%s"', $att, $value );
		}

		// Make both $args and $attributes available
		// Although this changes the structure of the arguments passed to wc_get_template, 
		// those arguments aren't available in the woocommerce_loop_add_to_cart_link, so it shouldn't break backward compatibility (the default output becomes totally dynamic, so it won't matter there)
		wc_get_template( 'loop/add-to-cart.php', array( 'args' => $args, 'attributes' => $attributes ) );
	}
}
```

Then, adjust the `templates/loop/add-to-cart.php` [file](https://github.com/woocommerce/woocommerce/blob/426897ac2d3d2d198427a60e229219d5b2cd8618/templates/loop/add-to-cart.php#L23).

```php
global $product;

// The output is still filterable through the same filter
// $args and $attributes are made available to the filter
echo apply_filters(
		'woocommerce_loop_add_to_cart_link',
		sprintf( '<a rel="nofollow" href="%s" %s>%s</a>',
			esc_url( $product->add_to_cart_url() ),
			implode( ' ', $attributes ),
			$product->add_to_cart_text() ),
		$product, $args, $attributes
);
```

Finally, custom attributes can be added like so...

```php
/**
 * Filter just the args for adding a custom data attribute
 */
add_filter( 'woocommerce_loop_add_to_cart_args', 'filter_woocommerce_loop_add_to_cart_args', 10, 2 );
function filter_woocommerce_loop_add_to_cart_args( $args, $product ) {
	$args['data-custom_attribute'] = 'some_database_value_etc';
	return $args;
}
```

I did some brief testing for this, and it works the way I envisioned it. However, I noticed a hiccup when keeping the `quantity` array key for backward compatibility. Since my idea uses `woocommerce_loop_add_to_cart_args` filter to actually generate the attributes from the array keys, it would generate a `quantity="1"` in the output. That said, since neither `$args` nor `$quantity` are available to the output filter (they are only accessible to the default output), it seems that backward compatibility may not be an issue here, because `quantity` could be intercepted, reassigned to `data-quantity`, and unset.

In the long run, I believe a solution like this is cleaner, as it doesn't **require** directly modifying the output to add custom attributes. It requires only one step: filtering the `woocommerce_loop_add_to_cart_args`. 

Adding `$args` to the `woocommerce_loop_add_to_cart_link` filter will make it possible, but with two steps: 1) filtering `woocommerce_loop_add_to_cart_args` to add the data, and 2) modifying the output via `woocommerce_loop_add_to_cart_link`.
