### ISSUE TITLE
Need filter using total_sales

### ISSUE THREAD

**Issue by tapos007** [woocommerce/woocommerce#18077]
I need to sort my product using total_sales and also need me popular and featured product in API

**Comment by WPprodigy** [comment]
This default filtering view is already powered by that property: http://cld.wthms.co/bWYw1k - https://github.com/woocommerce/woocommerce/blob/804c7712969d4309ee5456be0792e6b6b4d67b4b/includes/class-wc-query.php#L475

Best selling and featured are also available attributes for shortcodes: https://docs.woocommerce.com/document/woocommerce-shortcodes/#section-7

With the REST API, you can filter by featured: https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-products-controller.php#L240.

Afaik, there isn't an option for best selling - but you can add extra arguments with this filter I believe: https://github.com/woocommerce/woocommerce/blob/4f6a3afc2aa48588a01a143701f0803c4aecf265/includes/abstracts/abstract-wc-rest-crud-controller.php#L298

**Comment by tapos007** [comment]
can u write this code for me I m not understand it , need only best selling product in rest api

**Comment by WPprodigy** [comment]
Sorry, I can't. I'd recommend contacting one of these services: https://woocommerce.com/customizations/
