### ISSUE TITLE
New admin orders page: Idea for better clarity 

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18086]
I'm really liking the new order listing page. With the effort to get rid of confusing icons that represented statuses and the more confusing icons for order actions, I think we succeeded.

But, also think we went back a little ways when this new guy was added: http://cld.wthms.co/0KErdb.

There is a lot of available space on this page now, so why not add even more clarity and just pop in some text along side / below the icon? Perhaps just allow the "Preview" text to show, or describe it with something like "Quick View"? No point in making our new user's guess what something does the first time they see it. Maybe even a button that would blend in with both text and icon: http://cld.wthms.co/SVZvyW ?

_____

And then this one might be more controversial, but I also think having "Edit Order" or "View Order" underneath the first column could contribute to a better UX as well. It's not abundantly clear for a new user what that does, and there will be some confusion for the people that used to always use the icons to the right to view an order.

Edit: Just noticed that you can now click anywhere in the row and the order will open up (but that was after looking at the code). I don't have any specific ideas, but wonder if some sort of highlighting or something could make it more clear to the user that they can just click on the row. A mouse pointer change isn't really enough. I'll see if I can find some example in other apps.

**Comment by jameskoster** [comment]
> But, also think we went back a little ways

Do you have any specific feedback that makes you say this? Or is it just like, your opinion, man? :lebowski: 

Reason I ask is because I'd rather we didn't change anything without actually identifying it as a pain point first. The same goes for your other feedback. We've not seen anybody confused by the clickable row on Store on WP.com.

**Comment by WPprodigy** [comment]
> Do you have any specific feedback that makes you say this? 

Not really, I'm just not a fan of icon-only buttons in applications. Text or text+icon actions/buttons are inherently more user friendly, especially for new users. For example, regardless of past experiences with WooCommerce, everybody that upgrades to 3.3 is going to need to "guess" what this button does the first time they click it (unless they read the dev blog...which is like...not a large percent).

On top of that, we are also taking away (or at least hiding by default) the button that many are used to using as a part of their order fulfillment/workflow. So making the change as easy as possible is in everybody's best interest.

> Or is it just like, your opinion, man? 

Just my opinion right now ;p

**Comment by jameskoster** [comment]
I think icon-only buttons are fine as long as the icon is obvious enough. Is this one? I don't know :) If folks aren't struggling to find the quick view feature then I suppose it's doing it's job just fine.

If this _does_ come up, let's revisit.
