### ISSUE TITLE
Chrome display issue of upsells when gallery is visible on the page

### ISSUE THREAD

**Issue by newkind** [woocommerce/woocommerce#18089]
Beggining from WooCommerce 3.2 I noticed a weird issue with my product page that only appears on Chrome. When you view the page - the Upsell products are hidden or visible depending on your position on the page. If you scroll the page to the bottom very slowly there is a moment when they appear.

I'm attaching a video to this issue to show you guys what it looks like.
[chrome_issue.mp4.zip](https://github.com/woocommerce/woocommerce/files/1546032/chrome_issue.mp4.zip)

The issue is visible in Chrome only and just like I said it's there since WC 3.2 up to the latest 3.2.5

I was able to find that the issue can be solved by removing `transform: translate3d(0px, 0px, 0px);` on the `<figure class="woocommerce-product-gallery__wrapper">` in the gallery images.

**Comment by willgorham** [comment]
I noticed this also - at a certain scroll point on Chrome, all of the images on a single product page would disappear. It seems to have gone away though; I haven't noticed it in a few days. 

@newkind Are you on the latest version of Chrome (63 I think)?

**Comment by newkind** [comment]
Now that you pointed that out I checked my Chrome and it was 62. After updating to 63 it seems to be resolved. Looks like it was a browser rendering issue not CSS. I'm going to close this issue. Thank you for pointing that out!
