### ISSUE TITLE
No new order Emails Sent To me or to the customer

### ISSUE THREAD

**Issue by happyherbalcare** [woocommerce/woocommerce#18081]
hello, after i updated to woocommerce  3.2.5 i started having problems with the emails, i dont get orders email notifications,

**Comment by WPprodigy** [comment]
This guide will help you debug your email issues: https://docs.woocommerce.com/document/email-faq/

This isn't really a good place to post for support requests like this though. Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooCommerce Support](https://docs.woocommerce.com/) page.
