### ISSUE TITLE
Product variation image not change aftert select option in mobile

### ISSUE THREAD

**Issue by presslayouts** [woocommerce/woocommerce#18092]
my theme error with mobile phone. if i select variation image in product, image can't move.

https://pusathobi.com/produk/feisty-pets-boneka-lucu-berubah-jadi-seram/

can you solved this problem?

**Comment by mikejolley** [comment]
This is a slider plugin implemented by your theme. Core uses flexslider. You'll need to ask the theme author.

Thanks

**Comment by presslayouts** [comment]
Sorry guys, I'm emallshop theme author not other. Emallshop theme is my own theme.

Completed working in pc but issue in mobile devices and we have no any changes / override code in mobile devices.

So please you tell what is issue and resolve it?

**Comment by mikejolley** [comment]
No I cannot tell you what the issue is with the custom slider you have implemented in your own theme.  Our scripts handle flexslider. If you want to use slick-carousel you'll need to code in your own handling.
