### ISSUE TITLE
State/Country Dropdowns do not work on Checkout Field

### ISSUE THREAD

**Issue by Tegan1234** [woocommerce/woocommerce#18090]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Order a product from my online shop at soulquartz.com
2. In the check out page for entering customer details
3. Check out the options for Country and State not visible

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

`
### WordPress Environment ###

Home URL: http://soulquartz.com.au
Site URL: http://soulquartz.com.au
WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: LiteSpeed
PHP Version: ❌ 5.4.45 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 40 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: 5.6.36
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 11.55MB
Database Data Size: 8.33MB
Database Index Size: 3.22MB
wp_woocommerce_sessions: Data: 0.30MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.11MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.14MB + Index: 0.08MB
wp_postmeta: Data: 3.52MB + Index: 1.97MB
wp_posts: Data: 1.52MB + Index: 0.25MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.13MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.09MB + Index: 0.11MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 677
custom_css: 1
customize_changeset: 8
gema75_wc_badge_sold: 1
ml-slider: 1
nav_menu_item: 38
page: 13
post: 1
product: 73
product_variation: 109
revision: 193
shop_coupon: 15
shop_order: 97
sliders: 4
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (30) ###

WooCommerce Afterpay Gateway: by AfterPay – 1.3.1 – Not tested with the active version of WooCommerce
About Me Image Widget: by Chris Baldelomar – 1.4.1
Advanced Custom Fields Pro: by elliot condon – 5.2.7
Akismet: by Automattic – 3.2
Bluchic Instaview: by Bluchic – 15.11
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.7
Contact Form 7: by Takayuki Miyoshi – 4.6.1
Envato WordPress Toolkit: by Envato – 1.7.3
Etsy Shop: by Frédéric Sheedy – 1.0
Facebook for WooCommerce: by Facebook – 1.6.6 – Not tested with the active version of WooCommerce
Woocommerce Soldout Badges  - by Gema75: by Gema75 – 3.0 – Not tested with the active version of WooCommerce
Instagram Feed: by Smash Balloon – 1.5.1
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.5.3
Juicer: by Ryan MacInnes – 1.8
MailChimp for WordPress Lite: by ibericode – 2.3.12
Meta Slider: by Matcha Labs – 3.4.1
Pinterest RSS Widget: by bkmacdaddy designs – 2.3.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Reinstall Themes: by Nashwan Doaqan – 0.1.1
Scroll Back to Top: by Joe Sexton – 1.1.3
WP Canvas - Portfolio: by Chris Baldelomar – 1.3
WP Canvas - Gallery: by Chris Baldelomar – 1.53
WP Canvas - Responsive Videos: by Chris Baldelomar – 1.10
Shortcodes by Angie Makes: by Chris Baldelomar – 3.18
WooCommerce: by Automattic – 3.2.5
WP Instagram Widget: by Scott Evans – 1.9.8
WP Canvas - Image Widget: by Chris Baldelomar – 1.4
WP Canvas - Insert Code: by Chris Baldelomar – 1.1
WP Canvas - Pinterest Widget: by Chris Baldelomar – 1.2
WP Canvas - Self Hosted Updates: by Chris Baldelomar – 1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #168 - /index.php/shopnow/
Cart: #23 - /index.php/shopnow/cart/
Checkout: #24 - /index.php/checkout/
My account: ❌ Page visibility should be public
Terms and conditions: #288 - /index.php/shopnow/terms-and-conditions/

### Theme ###

Name: Samantha
Version: 17.09
Author URL: http://www.bluchic.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
This is an issue with the theme you're using. It's missing the styles for `select2` - the script which enhances select boxes on the checkout.

Needs resolving by the theme developer, or you can swap themes.

Thanks
