### ISSUE TITLE
Gallery thumb under big picture into product page.

### ISSUE THREAD

**Issue by AdrianKuriata** [woocommerce/woocommerce#18095]
Hi, i have a question, where in the template files is thumbs list into product page? I wan't add some attributes to the list of the thumbs, because they don't have alt etc. Just only draggable, src and class. This is really important, please at fast answer.

**Comment by mikejolley** [comment]
The thumbnails in flexslider are dynamically generated. The actual thumbnails output to the page do have alt text etc set.

https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/product-thumbnails.php

**Comment by AdrianKuriata** [comment]
@mikejolley Hi.
Sure, but after when i created click event on thumb this not working, some stopPropagation is active on this elements or what?

**Comment by mikejolley** [comment]
Probably, in the flexslider script which handles click events.

**Comment by AdrianKuriata** [comment]
Check a picture how it look's [Pic](https://i.imgur.com/j4n9dLw.png)

@mikejolley Is this possible to change it? I need put some alt or working with selected thumb.

**Comment by mikejolley** [comment]
No it's not possible to change it unless you drop flexslider and add your own gallery.

> The thumbnails in flexslider are dynamically generated. The actual thumbnails output to the page do have alt text etc set.
