### ISSUE TITLE
[3.3] I broke the new thumbnail cropping feature

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18106]
Was testing out thumbnail cropping, and managed to break it somehow. Just doesn't work anymore, regardless of the aspect ratios - nothing changes.

Still digging in, but found a few things worth looking into:

1) It all started with this hook.

https://github.com/woocommerce/woocommerce/blob/b1b9f57a919fb6f3f3bd8c9d62b856cbb85cb2a0/includes/class-wc-regenerate-images.php#L39

First off, this seemed a bit hacky to me but I don't know what would be better. When the aspect ratios were working on my test site, I found that this hook was the reason the thumbnails didn't show up in the customized size while in the Customizer. It worked fine on the front-end, just not when the customizer was open. Also, pretty sure it should be `add_filter`, not `add_action`.

2) Line 71 and 74 are the same, with un-necessary conditionals. 

https://github.com/woocommerce/woocommerce/blob/b1b9f57a919fb6f3f3bd8c9d62b856cbb85cb2a0/includes/class-wc-regenerate-images.php#L71

Perhaps something wasn't finished (thus the cause of the bug I've run into), otherwise makes no sense for all those conditionals.

3) Creating media bloat?

Feel like this is going to flood the user's media folders with tons of thumbnails that will never be used. Maybe I missed it, but doesn't seem like it's trying to delete thumbnails after the aspect ratio is changed to a new one.

**Comment by WPprodigy** [comment]
This should be `woocommerce_thumbnail_cropping_custom_height`

https://github.com/woocommerce/woocommerce/blob/e3331448e5524136d06c8382fb77032bc2ea5870/includes/wc-core-functions.php#L715

**Comment by WPprodigy** [comment]
Sorry, rambled a bit. But should re-open this @mikejolley for discussion on these three things:

1) Need to find reasoning behind this block: https://github.com/woocommerce/woocommerce/blob/b1b9f57a919fb6f3f3bd8c9d62b856cbb85cb2a0/includes/class-wc-regenerate-images.php#L69-L75

2) On-the-fly image resizing could lead to performance problems.

3) Creating image thumbnails every time the values in the customizer are changed could lead to image / media library bloat. Is it possible to delete older crops that WC did once aspect ratios change?

Just some concerns :)

**Comment by spencerfinnell** [comment]
@WPprodigy See also: https://github.com/woocommerce/woocommerce/issues/18117

**Comment by mikejolley** [comment]
1. Resizes if using woocommerce_thumbnail size and the dimensions have changed.

2. It's ran in the background.

3. Understood but deleting images is not a good solution as they could be direct linked. Also no different to the old settings and regen thumbnails.

**Comment by WPprodigy** [comment]
1) But why those conditionals? The resulting $image declaration is the same inside and out. Feels like something was forgotten.

**Comment by mikejolley** [comment]
Ping @kloon ^ 

Not a blocker for beta.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18120

**Comment by kloon** [comment]
The changes Mike did address all the issues from my tests. Thanks, Mike!.

Regarding performance, you will notice we are using a different way of generating on-the-fly as we are doing when settings change, the on-the-fly was developed in such a way that it is fast and should not cause any performance issues, plus at most it should only load a total of images as defined per page in your settings which is 12 by default and that adds very little to no noticeable difference in page load times.

Mike also answered most of the questions so I'll leave that at that.
