### ISSUE TITLE
Rest Api Empty images for product using querystring

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#18104]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Its currently impossible to clear images for products using querystring

**Request**
```
Request URL:http://localhost:9001/wp-json/wc/v2/products/7114?_method=PUT&images=%5B%5D&oauth_consumer_key=ck_c500d3cf60e3af49270064e51f778650ebe2a171&oauth_nonce=CeVQ7c&oauth_signature=kTQJcKj5n7zmHIskRW2dZvGF%2FOU%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1513021885&oauth_version=1.0
Request Method:POST
Status Code:400 Bad Request
Remote Address:[::1]:9001
Referrer Policy:no-referrer-when-downgrade
```

**Params**
```
_method:PUT
images:[]
oauth_consumer_key:ck_c500d3cf60e3af49270064e51f778650ebe2a171
oauth_nonce:CeVQ7c
oauth_signature:kTQJcKj5n7zmHIskRW2dZvGF/OU=
oauth_signature_method:HMAC-SHA1
oauth_timestamp:1513021885
oauth_version:1.0
```

**Params Encoded**
```
_method:PUT
images:%5B%5D
oauth_consumer_key:ck_c500d3cf60e3af49270064e51f778650ebe2a171
oauth_nonce:CeVQ7c
oauth_signature:kTQJcKj5n7zmHIskRW2dZvGF%2FOU%3D
oauth_signature_method:HMAC-SHA1
oauth_timestamp:1513021885
oauth_version:1.0
```

**Response**
```
{code: "rest_invalid_param", message: "Ugyldig(e) parameter(e): images",…}
code
:
"rest_invalid_param"
data
:
{status: 400, params: {images: "images er ikke av typen object."}}
message
:
"Ugyldig(e) parameter(e): images"
```

It complains its not an object..

**I also tried with:**

images=%00&...
images[0]=%00&...
images[0]=""&...
images[0]=0&...
images[0]=&...
images=""&...
images=&...
images[0][id]=0&...
images[0][id]=-1&...
images[0][id]=%00&...
images[0][id]=false&...

Usually complains with:

```
{code: "woocommerce_product_invalid_image_id", message: "#0 er en ugyldig bilde-ID.",…}
code
:
"woocommerce_product_invalid_image_id"
data
:
{status: 400}
message
:
"#0 er en ugyldig bilde-ID."
```

## Expected/actual behavior

This should be valid:
images=[]&...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
@claudiosanches If this is changed from object to array it still gives `"images": "images[0] is not of type object."`. Ideas?

**Comment by mikejolley** [comment]
`images=[]` is not valid. It should be `images[]=`

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18119
