### ISSUE TITLE
WooCommerce New Order email notification

### ISSUE THREAD

**Issue by acpadmin** [woocommerce/woocommerce#18105]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Under WooCommerce > Settings > Emails > New Order 
2. Email has been set to business owner email address to receive notification for all order activities 
3. All email notification uses the same for new orders/cancelled order etc. 
4. For a new order, no email notification is received under the stated email address 
5. For cancelled order and other actions, business owner is able to receive it under the stated email address 

## Expected/actual behavior

When I follow those steps, I see...
1. That business owner does not receive the new order email notification. 

I was expecting to see...
1. Email notification delivered to business owner email address 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Please go through the post here: https://docs.woocommerce.com/document/email-faq/ There are no known issues with new order emails so it's likely something covered in the doc. There are several troubleshooting steps in there such as installing a mail logging plugin which will help you find your issue.

I certainly cannot reproduce an issue with your given details as it works fine locally regardless of the email I set in settings.

Thanks
