### ISSUE TITLE
Incorrect Image Sizes Returned

### ISSUE THREAD

**Issue by spencerfinnell** [woocommerce/woocommerce#18117]
Some of the changes to image cropping/regeneration seem to still have issues on master.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Activate WooCommerce.
2. Add `<?php var_dump( wp_get_attachment_image_url( get_post_thumbnail_id(), 'full' ) ); ?>` to a loop (single page, single product, etc)

## Expected/actual behavior

When I follow those steps, I see an incorrect image URL returned (returning the default 600x600 cropped image).

`.../themes/storefront/content-single.php:10:string 'http://site.dev/wp-content/uploads/2017/12/hero-home-lg@2x-600x600.jpg'`

I was expecting to see the requested URL size. This happens when these tags are used in any loop (regardless of post type, shop, etc).

`.../themes/storefront/content-single.php:10:string 'http://site.dev/wp-content/uploads/2017/12/hero-home-lg@2x.jpg'`

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
Solved in https://github.com/woocommerce/woocommerce/pull/18120
