### ISSUE TITLE
After updating to Woocommerce 3.2.5 I got a problem with "Add New Product" 

### ISSUE THREAD

**Issue by KarlGaucho** [woocommerce/woocommerce#18114]
After updating to Woocommerce 3.2.5 I got a problem with "Add New Product" ... in particular with the Add new gallery images link , which does not take me to the upload media function, but instead links me to this: http://www.kristybakano.com/wp-admin/post-new.php?post_type=product#

In addition, it does not allow me to edit Product Data. 

I have tried to deactivate all all other plugins, but the same problems persists.

Any suggestions to solve this are more than welcome

Thanks

**Comment by mikejolley** [comment]
This is a conflict with another plugin/theme.

In Chrome, go to View > Developer > Javascript Console. A console will appear with some errors displayed (you may need to refresh page). This should give clues to what is causing the issue.

When in doubt:

```
## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above
```

Thanks

**Comment by KarlGaucho** [comment]
Hmm.... I did deactivate all other plugins though and that did not solve it... 
Not sure how to isolate the theme option...

**Comment by mikejolley** [comment]
Look at the console like I said.
