### ISSUE TITLE
Pay for order email copy

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#18111]
This email is sent when orders are created manually;

![email](https://user-images.githubusercontent.com/541093/33784933-c7e1ad58-dc30-11e7-963a-dce9fc429abe.png)

That second sentence is a little funky. I think we should tweak the intro copy here;

> An order has been created for you on Store.
> [Pay for this order]

Basically make the payment link into a button to create a clearer CTA.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18118
