### ISSUE TITLE
After updating to Woocommerce 3.2.5 I got a problem with "Add New Product" ... in particular with the Add new gallery images link , which does not take me to the upload media function, but instead links me to this: http://www.kristybakano.com/wp-admin/post-new.php?post_type=product# 

### ISSUE THREAD

**Issue by KarlGaucho** [woocommerce/woocommerce#18113]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/18114
