### ISSUE TITLE
"Design your store" notification messing up Gutenberg

### ISSUE THREAD

**Issue by artpi** [woocommerce/woocommerce#18110]
![zrzut ekranu 2017-12-12 o 11 22 07](https://user-images.githubusercontent.com/3775068/33879658-6d5b1188-df2f-11e7-8572-b677232dbcff.png)
![zrzut ekranu 2017-12-12 o 11 23 30](https://user-images.githubusercontent.com/3775068/33879669-706830cc-df2f-11e7-8cf4-ff24851f7192.png)

- Gutenberg 1.9.0
- Woocommerce 3.2.5

### Reproduction
- Install Gutenberg, activate
- Install Woocommerce
- Go through tutorial
- result is everything is messed up on "Add first product page"

If woo is messed up with Gutenberg maybe it would be good to detect so?

**Comment by mikejolley** [comment]
This notification is from Storefront, but it seems all custom admin notices (including ones from WooCommerce) have issues like this.

This seems to be logged already here https://github.com/WordPress/gutenberg/issues/3395

FWIW we're looking at proper integration and compatibility with Gutenberg in Q1 :)

Thanks
