### ISSUE TITLE
"Enter your full address to see shipping costs" text is missing on cart page

### ISSUE THREAD

**Issue by cjsinnbeck** [woocommerce/woocommerce#18127]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add something to the cart without being logged in or having entered your address, country or zip code at the checkout page.

2. Go to the Cart page and look for the "Shipping" part.

## Expected/actual behavior

When I follow those steps, I see that the text "Enter your full address to see shipping costs" (or the equivalent translation in another language) is missing - instead I see an empty table cell ("Frakt" means "Shipping" in Norwegian).

![skaermbillede 2017-12-12 kl 23 38 56](https://user-images.githubusercontent.com/309937/33912323-badf8ec8-df95-11e7-95d7-e2730130bbf2.png)

I was expecting to see: "Enter your full address to see shipping costs" or the translation of this string.

I am quite sure that this arises from line 49-51 in templates/cart/cart-shipping.php, which read:

```
<?php elseif ( ! is_cart() ) : ?>
    <?php echo wpautop( __( 'Enter your full address to see shipping costs.', 'woocommerce' ) ); ?>
<?php endif; ?>
```

As expected from the code above, the text is not missing in the bottom of the checkout page, but only on the cart page (due to the "! is_cart()" condition).

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.11
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.56.1
OpenSSL/1.0.2m

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.58 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 96 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: wp1_
Total Database Size: 653.43MB
Database Data Size: 604.35MB
Database Index Size: 49.08MB
wp1_woocommerce_sessions: Data: 0.06MB + Index: 0.00MB
wp1_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp1_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp1_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp1_woocommerce_order_items: Data: 0.03MB + Index: 0.02MB
wp1_woocommerce_order_itemmeta: Data: 0.18MB + Index: 0.15MB
wp1_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp1_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp1_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp1_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp1_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp1_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp1_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp1_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp1_commentmeta: Data: 0.00MB + Index: 0.00MB
wp1_comments: Data: 0.07MB + Index: 0.04MB
wp1_et_social_stats: Data: 0.02MB + Index: 0.01MB
wp1_huge_it_videogallery_galleries: Data: 0.00MB + Index: 0.00MB
wp1_huge_it_videogallery_videos: Data: 0.01MB + Index: 0.00MB
wp1_icl_content_status: Data: 0.00MB + Index: 0.00MB
wp1_icl_core_status: Data: 0.00MB + Index: 0.00MB
wp1_icl_flags: Data: 0.00MB + Index: 0.00MB
wp1_icl_languages: Data: 0.00MB + Index: 0.01MB
wp1_icl_languages_translations: Data: 0.11MB + Index: 0.11MB
wp1_icl_locale_map: Data: 0.00MB + Index: 0.00MB
wp1_icl_message_status: Data: 0.00MB + Index: 0.00MB
wp1_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB
wp1_icl_node: Data: 0.00MB + Index: 0.00MB
wp1_icl_reminders: Data: 0.00MB + Index: 0.00MB
wp1_icl_strings: Data: 3.99MB + Index: 2.56MB
wp1_icl_string_packages: Data: 0.01MB + Index: 0.00MB
wp1_icl_string_pages: Data: 0.60MB + Index: 0.73MB
wp1_icl_string_positions: Data: 0.76MB + Index: 0.21MB
wp1_icl_string_status: Data: 0.00MB + Index: 0.00MB
wp1_icl_string_translations: Data: 5.96MB + Index: 2.28MB
wp1_icl_string_urls: Data: 0.00MB + Index: 0.01MB
wp1_icl_translate: Data: 11.38MB + Index: 0.20MB
wp1_icl_translate_job: Data: 0.02MB + Index: 0.02MB
wp1_icl_translations: Data: 0.16MB + Index: 0.30MB
wp1_icl_translation_batches: Data: 0.00MB + Index: 0.00MB
wp1_icl_translation_status: Data: 9.47MB + Index: 0.08MB
wp1_iwp_backup_status: Data: 0.00MB + Index: 0.00MB
wp1_layerslider: Data: 0.00MB + Index: 0.00MB
wp1_links: Data: 0.00MB + Index: 0.00MB
wp1_options: Data: 2.68MB + Index: 0.19MB
wp1_postmeta: Data: 5.67MB + Index: 1.34MB
wp1_posts: Data: 45.18MB + Index: 0.52MB
wp1_responsive_thumbnail_slider: Data: 0.00MB + Index: 0.00MB
wp1_responsive_video_gallery_plus_responsive_lightbox: Data: 0.00MB + Index: 0.00MB
wp1_termmeta: Data: 0.00MB + Index: 0.01MB
wp1_terms: Data: 0.31MB + Index: 0.41MB
wp1_term_relationships: Data: 0.15MB + Index: 0.30MB
wp1_term_taxonomy: Data: 0.22MB + Index: 0.39MB
wp1_totalsoft_fonts: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_ctpg: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_dbt: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_fg: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_gvg: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_hlg: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_id: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_lvg: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_manager: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_sg: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_ttvg: Data: 0.00MB + Index: 0.00MB
wp1_totalsoft_galleryv_videos: Data: 0.00MB + Index: 0.00MB
wp1_usermeta: Data: 0.86MB + Index: 0.59MB
wp1_users: Data: 0.04MB + Index: 0.04MB

### Post Type Counts ###

acf-field: 78
acf-field-group: 15
attachment: 2192
custom_css: 1
et_pb_layout: 83
nav_menu_item: 105
page: 393
post: 97
product: 35
project: 182
revision: 3539
shop_order: 214
tablepress_table: 3
wprss_feed: 1
wprss_feed_item: 5

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (21) ###

AccessPress Twitter Feed: by AccessPress Themes – 1.5.6
Advanced Custom Fields PRO: by Elliot Condon – 5.6.7
Divi Booster: by Dan Mossop – 2.6.4
Duplicate Page: by mndpsingh287 – 2.4
Google Tag Manager for Wordpress: by Thomas Geiger – 1.7.2
InfiniteWP - Client: by Revmakx – 1.6.6.3
Login-Logout: by webvitaly – 3.7
Monarch Plugin: by Elegant Themes – 1.3.23
Restrict Content: by Pippin Williamson – 2.2
WPML Multilingual CMS: by OnTheGoSystems – 3.8.4
TablePress: by Tobias Bäthge – 1.9
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.13.15.1

WooCommerce Multilingual: by OnTheGoSystems – 4.2.7
WooCommerce: by Automattic – 3.2.5
Yoast SEO Premium: by Team Yoast – 4.9
WordPress Responsive Thumbnail Slider: by I Thirteen Web Solution – 1.0.2
WP RSS Aggregator: by RebelCode – 4.11.2
WP Video Lightbox: by Tips and Tricks HQ
Ruhul Amin – 1.8.5

WPML Media: by OnTheGoSystems – 2.2.1
WPML String Translation: by OnTheGoSystems – 2.6.3
WPML Translation Management: by OnTheGoSystems – 2.4.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #32714 - /shop/
Cart: #32711 - /basket/
Checkout: #32713 - /checkout/
My account: #32712 - /my-account/
Terms and conditions: #34547 - /terms-and-conditions/

### Theme ###

Name: Divi Child
Version: 1.0.0
Author URL: ---
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.0.51
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/woocommerce/emails/customer-new-account.php
`
```
</details>

**Comment by kloon** [comment]
There should be a "Calculate Shipping" link that opens up the shipping calculator when using a default theme http://cld.wthms.co/Ha4mZx

The code you referenced is only applicable on the checkout page, so you will see that on the checkout page when you have no address entered.

I suggest you test this with Storefront or Twentyseventeen, the issue is perhaps related to your parent theme overriding core templates.

**Comment by cjsinnbeck** [comment]
@kloon Thanks a lot for the answer, I guess I have misunderstood the intended functionality. 

However, I would add that in WC 3.0.7 (which I just upgraded from), the text "Enter your full address to see shipping costs" was shown if "Enable the shipping calculator on the cart page" was disabled _and_ "Hide shipping costs until an address is entered" was also disabled (under WC -> Settings -> Shipping -> Shipping options).

![skaermbillede 2017-12-13 kl 08 37 16](https://user-images.githubusercontent.com/309937/33927346-33d02f76-dfe2-11e7-8f5c-06413596ad4d.png)

This was a nice feature (at least in our case), since it enabled us to subtly show the customer that shipping would be added (later) without enabling the calculator.

We could then translate the aforementioned text to include that "you choose your destination in the next step", or include a login link in the text to suggest customers to log in to see shipping costs now.

I have tested with Twentyseventeen, and the (possible non-)issue is the same (again, given that "Enable the shipping calculator on the cart page" is disabled _and_ "Hide shipping costs until an address is entered" is also disabled).

Best regards.

**Comment by kloon** [comment]
Since you are using quite an outdated version of WooCommerce things have definitely changed. We are ready to release 3.3 in the next month so you are already almost 3 versions behind.

Another option for you would be to override the template to your theme and then make the changes there, please see https://docs.woocommerce.com/document/template-structure/

**Comment by cjsinnbeck** [comment]
@kloon Very true, I know. I am in the process of updating the site. And you are right, I will probably use a template override (or one of the hooks in review-order.php) if I really need this "old" functionality.

Thanks for your time!

Regards, C.
