### ISSUE TITLE
Setup wizard: "Offline Payments" section missing "expand" icon in Firefox

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce#18126]
In Firefox (tested in v57 only), the caret symbol <img width="31" src="https://user-images.githubusercontent.com/1867547/33908209-a5face68-df55-11e7-87d2-bb344a036b12.png"> appears to be missing, and there is no other indication of being able to expand that section and choose from the payment options in that group.

Default:

<img width="661" src="https://user-images.githubusercontent.com/1867547/33908104-50658d26-df55-11e7-8090-a1c5631f304f.png">

Expanded (by clicking near right-side edge):

<img width="666" src="https://user-images.githubusercontent.com/1867547/33908492-96657aec-df56-11e7-8942-71f1c425dd95.png">

(Noticed this because VVV stopped working for me in Chrome, and I've yet to successfully fix it.)

**Comment by mikejolley** [comment]
> :before and :after should only work on the element which can act as a container of content. <input> cannot contain any content so it should not support those pseudo-elements. Chrome supports because it does not follow the spec (or bug?).

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18139
