### ISSUE TITLE
Hide all page titles

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce#18132]
Just like in WordPress where one can hide page titles the same should also apply to WooCommerce.

An area in General could have a hide/remove all page titles. 

Today there seems to be no clear code snippet that can remove/hide all the page titles. This is what I am noticing are posted in various pages:

wp-content/plugins/woocommerce/templates/archive-product.php
Edit this file archive-product.php and remove the below 3 lines.

```
 <?php if ( apply_filters( 'woocommerce_show_page_title', true ) ) : ?>
                        <h1 class="page-title"><?php woocommerce_page_title(); ?></h1>
                <?php endif; ?>
```
This will remove page title on shop page and all other pages.

---

To begin with it would be good to have a code snippet that does the job in an easier way.

This code really should remove all page titles seen on the frontend:
`add_filter( 'woocommerce_show_page_title', '__return_false' );`
But it only removes the shop title.

**Comment by mikejolley** [comment]
The `woocommerce_show_page_title` filter affects only our own template files. Archive product is used for shop, categories and other listings.

Added here https://github.com/woocommerce/woocommerce/issues/2850

But other 'pages' are not controlled by just WooCommerce. Pages like cart, checkout etc are regular WordPress pages, so adding filters here is not possible, and having an option in _WooCommerce_ to control non-wc pages seems wrong.

> Today there seems to be no clear code snippet that can remove/hide all the page titles

 A code solution/option is not needed for this to happen.

Using CSS is the simplest and easiest way to target specific pages or individual pages, using class names. Adding custom CSS is not difficult via the customiser or using a plugin.
