### ISSUE TITLE
Inventory management for a variable product is confusing.

### ISSUE THREAD

**Issue by emoop** [woocommerce/woocommerce#18135]
Is it necessary to manage stock availability of a product (for a variable product). Sometimes inconsistencies occur - there are products with stocks (variations), but in the administrative part it is written that this is outofstock.
It is logical to check if there are variations available, because in an update from older versions or simply by ignorance, stock management is set and a real stock product does not appear in the store.

**Comment by mikejolley** [comment]
At variation level, the stock status field is left under the user's control. If however you do change stock levels which puts a product back in stock, or out of stock, the stock status will be changed for you.

As for product level with variations, we're hopefully going to remove the product level setting or clarify what it means so it's not turned on by accident. This is already logged as part of https://github.com/woocommerce/woocommerce/issues/13085

Thanks
