### ISSUE TITLE
Turning off shipping fields once and for all

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce#18130]
The case.

1. The first area where one turns off shipping. - This should work globally. - 
WooCommerce -> Settings -> General
Shipping location(s): Disable shipping & shipping calculations.
With the above option selected it should turn **off** the shipping fields that will show up in the checkout screen. Everything that has to do with shipping should be turned off.

2. Product page: Product data - 
Within the Shipping tab there should be a notice letting the user know that globally shipping has been turned off. With an option to turn it on again. If the user turns it on then the global option should also change.

When shipping has been turned off then shipping fields should not show up in the checkout page.

To be able to turn off the shipping fields I have added the following code snippet:
```

 function kia_modify_default_address_fields( $fields ){
     if( isset( $fields['country'] ) ) unset( $fields['country'] );
     if( isset( $fields['address_1'] ) ) unset( $fields['address_1'] );
     if( isset( $fields['address_2'] ) ) unset( $fields['address_2'] );
     if( isset( $fields['city'] ) ) unset( $fields['city'] );
     if( isset( $fields['state'] ) ) unset( $fields['state'] );
     if( isset( $fields['postcode'] ) ) unset( $fields['postcode'] );
     return $fields; 
 }
 add_filter( 'woocommerce_default_address_fields', 'kia_modify_default_address_fields' );
 
 function kia_remove_billing_phone_fields( $fields ){
     // if( isset( $fields['billing_phone'] ) ) unset( $fields['billing_phone'] );
     // if( isset( $fields['billing_email'] ) ) $fields['billing_email']['class'] = array( 'form-row-wide' );
     return $fields;
 
 }
 add_filter( 'woocommerce_billing_fields', 'kia_remove_billing_phone_fields' );
```

**Comment by kloon** [comment]
Shipping fields are hidden when viewing checkout when shipping is disabled ie http://cld.wthms.co/p7ju1e Not shipping address section there.

There's a difference between shipping and billing fields. Even though billing fields collect address details this is for accounting and tax purposes and not necessarily for shipping, it can act as shipping details as well should the customer decide to ship to the same address.

There might be a valid case for showing a notice in the backend on products, however, we are aiming to keep our interfaces clean and streamline it more, introducing notices just adds to clutter and confusion.

I am going to say for now this is not something we will be implementing, the shipping details on products are still useful even when not having shipping enabled, weight and dimensions could be used for other things in a store, like displaying details about a product on the product page.

**Comment by paaljoachim** [comment]
Hey Gerhard.

I just find it confusing that when I turn off shipping that the billing details still show the address. As I expect it not to. Do you have an update to the code snippet on turning off Company name, and the street address that would be better to use then the above I am using?

Have a great day!

Btw
It would be great if WooCommerce.com had a doc sections for the most used code snippets. As there will always be features people miss that can instead be added as a snippet.

**Comment by paaljoachim** [comment]
It would be great to have these code snippets added to https://docs.woocommerce.com/documentation/plugins/woocommerce/woocommerce-codex/snippets/general-snippets/
