### ISSUE TITLE
BUG: Checkout Page: Payment options DESCRIPTIONS only toggle AFTER error

### ISSUE THREAD

**Issue by RobbyButler** [woocommerce/woocommerce#18144]
SOLVED:
In WooCommerce Settings/Products/Display I made a simple noob error of setting my "shop base" to "Checkout":
--- 
Shop base: /checkout/ Cart
---
This created what appeared to be an unobtrusive bug in the free level of the WooCommerce Checkout page, which I originally documented as follows:

When the Checkout page loads after the Cart, **the code to toggle payment option DESCRIPTIONS**—according to which payment option is selected—**DOES NOT get activated**.

However the code to toggle payment option descriptions **DOES get activated by an “error refresh”**—as when a required field is left blank and an attempt is made to place an order. Following such an “error refresh,” payment descriptions DO toggle as different payment options are selected.

This is particularly problematic when credit card fields don’t reveal properly to accept the necessary information when the credit card payment option is selected (with an additional plugin like Braintree or Stripe).

I am new to WooCommerce, running the very latest versions of both WooCommerce (3.2.5) and WordPress (4.9.1). To test whether the problem was within WooCommerce itself I deactivated all other plugins and activated the 2017 WordPress Theme. The problem persisted, as shown in the attached file.
[Site Problem visuals.pdf](https://github.com/woocommerce/woocommerce/files/1556518/Site.Problem.visuals.pdf)

More details and site examples available on request: RobbyQButler@gmail.com

**Comment by WPprodigy** [comment]
@RobbyButler I'm struggling to replicate this on other sites. It's not happening when I'm using a logged-in account, nor when a logged-out incognito window with no address fields filled out by default.

What browser & version are you using? Do you see any javascript errors in the console when the page is first loaded?

**Comment by RobbyButler** [comment]
Thank you for looking into this so promptly!

I am on Chrome 63.0.3239.84 on an older MacBook running OS 10.13.1.
The behavior is the same on my older iPhone 5 running the latest Safari under iOS 11.1.2.
There are no javascript errors or warnings when the page is loaded.
The problem occurs independent of whether required fields are all filled out.
The problem occurs only between:
- when the page is loaded and
- when an "error refresh" is triggered by "placing the order" with required fields missing.

To reproduce the problem:
- put anything into the description fields of **two or more** Checkout options in WooCommerce Settings for Checkout. ![woocommerce settings description](https://user-images.githubusercontent.com/1231332/33994204-6fd1c3de-e08e-11e7-97c9-7ed0fad25362.png)

- When the Checkout is first loaded, these descriptions won't toggle properly when selection of payment options changes.
- After an "error refresh" the descriptions will toggle properly.
- When extra Credit Card plugins (Stripe, Braintree, etc.) attempt to use the description field to gather more information, they only work **after** the "error refresh."

I have a shadow site showing this problem with the WordPress 2017 theme and only the WooCommerce plugin installed. If you text/call me I will give you directions and credentials.

Thank you again for the prompt attention!

**Comment by mikejolley** [comment]
@RobbyButler Tell us about your page setup. What pages are assigned to cart/checkout under checkout options, and do you have both shortcodes on a single page for some reason?

**Comment by RobbyButler** [comment]
No, it was a noob error. Thanks so much for taking time to look at this.
