### ISSUE TITLE
Got "Invalid signature - provided signature does not match"

### ISSUE THREAD

**Issue by aqnaqn** [woocommerce/woocommerce#18146]
I am getting a "Invalid signature - provided signature does not match." error when making a WC API call to WC_API_Client_Resource_Customers->create().

I poked around a bit and found that in wp-content/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-authentication.php, function check_oauth_signature(), on line 267, an '&' is being appended to the consumer secret before it's used to SHA encrypt and compare to the "consumer_signature" supplied in the request's query string.  Why is the '&' being appended?  If I use the consumer secret as is (w/o the trailing '&') to encrypt, things work.  (BTW, in v1 and v2, the consumer secret is used to encrypt as is, without a trailing '&'.)

The code from "master" on https://github.com/woocommerce/woocommerce.git is the same (3.3.0-beta.1): it has the appending of the '&' to the consumer secret.

Here are values at the time of the exception:

Message: Error: 2 - Invalid signature - provided signature does not match.
signature /IKz92nUSr9RUJoRRedplNgB0i/Qhth2asuppl+Bii44=/
consumer_signature /rfRjirxEo57JtF599bcoxJ6V0mN84WemlEV10Um31h4=/
string_to_sign /POST&http%3A%2F%2Flocalhost%3A8888%2Flsnw%2Fwc-api%2Fv3%2Fcustomers&oauth_consumer_key%3Dck_e173423c35a4720df4440a29870c8a96799c0e05%26oauth_nonce%3D6f00c
92b20689d18e39669ec7603baf520f0e91c%26oauth_signature_method%3DHMAC-SHA256%26oauth_timestamp%3D1513188653/
hash_algorithm /sha256/
secret /[my consumer secret string cs_....]&/

If I hash_hmac() with SHA256 and base64_encode() the string_to_sign using my consumer secret WITHOUT the trailing '&', then the result matches the supplied "consumer_signature".

Here is the request right before dispatch:
<details>
WC_API_Client_HTTP_Request Object
(
    [ch:protected] => Resource id #24
    [request:protected] => stdClass Object
        (
            [headers] => Array
                (
                    [0] => Accept: application/json
                    [1] => Content-Type: application/json
                    [2] => User-Agent: WooCommerce API Client-PHP/2.0.1
                )

            [method] => POST
            [url] => http://localhost:8888/lsnw/wc-api/v3/orders?oauth_consumer_key=your+consumer+key+here&oauth_timestamp=1513191956&oauth_nonce=17c25fb7ff7ed85fd036ce4aa9ee7ef4af93b6a5&oauth_signature_method=HMAC-SHA256&oauth_signature=Y1moB7e9Pvk%2FXn%2B816PIiUdgTWvmCehYZ14mxKQRVzI%3D
            [params] => Array
                (
                    [oauth_consumer_key] => your consumer key here
                    [oauth_timestamp] => 1513191956
                    [oauth_nonce] => 17c25fb7ff7ed85fd036ce4aa9ee7ef4af93b6a5
                    [oauth_signature_method] => HMAC-SHA256
                    [oauth_signature] => Y1moB7e9Pvk/Xn+816PIiUdgTWvmCehYZ14mxKQRVzI=
                )

            [data] => Array
                (
                    [order] => Array
                        (
                            [customer_id] => 1
                            [billing_address] => ArrayObject Object
                                (
                                    [storage:ArrayObject:private] => Array
                                        (
                                            [first_name] => FirstName
                                            [last_name] => LastName
                                            [company] => 
                                            [address_1] => 1234 Mickey Mouse Lane
                                            [address_2] => Apt 999
                                            [city] => Austin
                                            [state] => TX
                                            [postcode] => 78750
                                            [country] => US
                                            [phone] => 512-555-1212
                                            [email] => foo@bar.com
                                        )

                                )

                            [shipping_address] => ArrayObject Object
                                (
                                    [storage:ArrayObject:private] => Array
                                        (
                                            [first_name] => FirstName
                                            [last_name] => LastName
                                            [company] => 
                                            [address_1] => 1234 Mickey Mouse Lane
                                            [address_2] => Apt 999
                                            [city] => Austin
                                            [state] => TX
                                            [postcode] => 78750
                                            [country] => US
                                            [phone] => 512-555-1212
                                            [email] => foo@bar.com
                                        )

                                )

                        )

                )

            [body] => {"order":{"customer_id":1,"billing_address":{"first_name":"FirstName","last_name":"LastName","company":"","address_1":"1234 Mickey Mouse Lane","address_2":"Apt 999","city":"Austin","state":"TX","postcode":"78750","country":"US","phone":"512-555-1212","email":"foo@bar.com"},"shipping_address":{"first_name":"FirstName","last_name":"LastName","company":"","address_1":"1234 Mickey Mouse Lane","address_2":"Apt 999","city":"Austin","state":"TX","postcode":"78750","country":"US","phone":"512-555-1212","email":"foo@bar.com"}}}
        )

    [json_decode_as_array:protected] => 
    [debug:protected] => 
    [response:protected] => 
    [curl_headers:protected] => 
)

</details>

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Edit the attached script, fix up the consumer key & secret, then run it on the command line in an *NIX shell:

    php provided_signature_does_not_match_test.php

## Expected/actual behavior

When I follow those steps, I see...
    Fatal error: Uncaught exception 'WC_API_Client_HTTP_Exception' with message 'Error: Invalid signature - provided signature does not match. [woocommerce_api_authentication_error]' in /Applications/MAMP/htdocs/lsnw/lib/woocommerce-api/class-wc-api-client-http-request.php:210

Exit code was 255 ("echo $?")

I was expecting to see...

Nothing, with an exit code of 0.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost:8888/lsnw
Site URL: http://localhost:8888/lsnw
WC Version: 3.2.5
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.12
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.50.3
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.5
WC Database Prefix: lsnw_
MaxMind GeoIP Database: ✔
Total Database Size: 5.60MB
Database Data Size: 4.40MB
Database Index Size: 1.20MB
lsnw_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
lsnw_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
lsnw_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
lsnw_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
lsnw_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
lsnw_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.14MB
lsnw_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
lsnw_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
lsnw_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
lsnw_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
lsnw_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
lsnw_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
lsnw_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
lsnw_woocommerce_log: Data: 0.02MB + Index: 0.02MB
lsnw_commentmeta: Data: 0.02MB + Index: 0.03MB
lsnw_comments: Data: 0.02MB + Index: 0.09MB
lsnw_duplicator_packages: Data: 0.02MB + Index: 0.02MB
lsnw_links: Data: 0.02MB + Index: 0.02MB
lsnw_options: Data: 2.06MB + Index: 0.02MB
lsnw_postmeta: Data: 0.30MB + Index: 0.28MB
lsnw_posts: Data: 1.47MB + Index: 0.06MB
lsnw_termmeta: Data: 0.02MB + Index: 0.03MB
lsnw_terms: Data: 0.02MB + Index: 0.03MB
lsnw_term_relationships: Data: 0.02MB + Index: 0.02MB
lsnw_term_taxonomy: Data: 0.02MB + Index: 0.03MB
lsnw_usermeta: Data: 0.02MB + Index: 0.03MB
lsnw_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 36
cuar_log_event: 7
nav_menu_item: 24
page: 22
post: 2
product: 47
product_variation: 10
revision: 61
shop_coupon: 1
shop_order: 24
shop_webhook: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (10) ###

Duplicator: by Snap Creek – 1.2.30
Genesis eNews Extended: by Brandon Kraft – 2.0.2
Insert Headers and Footers: by WPBeginner – 1.4.2
Plugin Dependencies: by scribu – 1.3
WP REST API: by WP REST API Team – 2.0-beta15
Simple Social Icons: by Nathan Rice – 2.0.1
Soliloquy: by Soliloquy Team – 2.5.3.1
WooCommerce Authorize.Net AIM Gateway: by SkyVerge – 3.11.3 – 3.12.1 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.5
Email Login: by Beau Lebens – 4.6.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Jessica
Version: 1.3.4
Author URL: http://www.web-savvy-marketing.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.5.3
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: jessica/woocommerce/single-product/meta.php
jessica/taxonomy-product_tag.php


### Authorize.Net AIM ###

Environment: Test
Debug Mode: Off

### Authorize.Net AIM eCheck ###

Environment: Test
Debug Mode: Off
`
```
</details>

**Comment by rodrigoprimo** [comment]
The `&` was added to v3 to make it compliant with OAuth spec. For more information see #8415.

**Comment by aqnaqn** [comment]
That cannot possibly be correct that a '&' is appended to the secret key and then using the resulting string as the secret key to encrypt!!!  That has nothing to do with oauth!  Changing the private key of a private/public key pair defeats the purpose of private/public key encryption!

I might believe that oauth requires an '&' to be appended to the **_result_** of the SHA encrypted + base64 encoded string, but absolutely not appending an '&' to the private key **_before_** using it in the SHA encryption!!!

I guess I will work around this for now.

**Comment by rodrigoprimo** [comment]
cc @claudiosanches since you reviewed #8415 to make sure I'm not missing something and there is an issue here.

**Comment by mikejolley** [comment]
The `&` appending is documented here: https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http

We follow a similar pattern to Twitter documented here: https://developer.twitter.com/en/docs/basics/authentication/guides/creating-a-signature

Note the following text:

```
Both of these values need to be combined to form a signing key which will be used to generate the signature. The signing key is simply the percent encoded consumer secret, followed by an ampersand character ‘&’, followed by the percent encoded token secret:

Note that there are some flows, such as when obtaining a request token, where the token secret is not yet known. In this case, the signing key should consist of the percent encoded consumer secret followed by an ampersand character ‘&’.
```

The second paragraph applies here. We don't have a token secret, so `the signing key should consist of the percent encoded consumer secret followed by an ampersand character ‘&’`. We append the & to match the key you should be using your side.

This is also in the spec here: http://oauthbible.com/#oauth-10a-one-legged

> These include the Request Method & URL & Parameters, which is then encrypted against the key which consists of: (consumer_secret & token_secret). In some cases this may be the key, plaintext, or may use simply the consumer_secret, for RSA encryption.

> Sometimes in case of RSA Encryption and xAuth the signing key may only be the Consumer Secret with the & symbol appended or not.

When the & was missing we were not to spec and had other issues logged. See https://github.com/woocommerce/woocommerce/issues/7928 This has since been fixed and is now to spec.

https://github.com/woocommerce/woocommerce/issues/11224

So this is to spec, and should not be changed.

Thanks

**Comment by claudiosanches** [comment]
Not to mention that all libraries for oAuth1.0a for any programming language will include that ampersand too.

**Comment by aqnaqn** [comment]
Thanks for all the info.  I guess the WC REST API code is broken, then; not surprising since it was last updated two and a half years ago.

In its woocommerce-api/class-wc-api-client-authentication.php file, in function generate_oauth_signature(), it's just doing the encoding using the bare consumer_secret, without the trailing '&'.

**Comment by mikejolley** [comment]
What plugin/wrapper?

Isn't this the new one https://github.com/woocommerce/wc-api-php

**Comment by claudiosanches** [comment]
@aqnaqn just use the wrappers on https://woocommerce.github.io/woocommerce-rest-api-docs/#libraries-and-tools You can find there the official library, and also some third party too.

**Comment by aqnaqn** [comment]
OK, thanks, I'll try wc-api-php.  (I was using  https://github.com/kloon/WooCommerce-REST-API-Client-Library !!)
