### ISSUE TITLE
wc_get_post_data_by_key() undefined index and passed by reference errors due to wp_unslash

### ISSUE THREAD

**Issue by DanWyatt** [woocommerce/woocommerce#18142]
The wc_get_post_data_by_key() function in [wp-core-functions.php](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-core-functions.php) throws _Undefined index_ and _Only variables should be passed by reference_ notices, when an undefined POST key is used, due to wp_unslash() being called before wc_get_var().

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Edit either the billing or shipping address in My Account

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by claudiulodro** [comment]
Good catch. Fixed in #18143.
