### ISSUE TITLE
Duplicate x number of products in the admin

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#18147]
## Steps to reproduce the issue

1. Go to Products in the Wordpress admin
2. Hover over a product and click duplicate

When using some plugins like the Measurement Price Calculator the data is serialized. When creating many products in batches using the CSV Import Suite or similar, the serialized data may not be copied if the product is not already existing. It is therefor necessary to create a product first and then merge products with i.e. CSV Import Suite.

I'd like to be able to select how many products that can be duplicated. Now it's defaulted to one product. Let's say I create a product with serialized data and then have all the meta data etc in a CSV file. Then I'd like to duplicate that product x number of times and then do a product merge with the correct data.

**Comment by WPprodigy** [comment]
Hmm, I see your use case. But the correct solution here would be for Measurement Price Calculator to add support for product csv import/export fields.

Adding an option to duplicate a product multiple times at once seems a bit messy, whereas the proper solution works seamlessly. 

Would you mind opening up a ticket for Measurement Price Calculator asking for CSV import support?  https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Importer-&-Exporter#adding-custom-import-columns-developers

**Comment by rocketeer76** [comment]
https://docs.woocommerce.com/document/measurement-price-calculator/

"Q: Can I import products with measurement settings?
A: You can import and export products with measurement settings with the WooCommerce Product CSV Suite, but creating new measurement products via import is not really possible. The measurement data is stored as serialized meta, so while exporting and then re-importing existing products works just fine, creating new measurement products via an import is not ideal. New products should be configured in the WooCommerce admin."

**Comment by mikejolley** [comment]
Duplicate x does indeed sound messy and niche. Maybe extension territory, but not core.
