### ISSUE TITLE
[3.3] Some styling bugs around select2 widget attribute filters and listings

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18154]
Theme Twenty Fifteen / Twenty Sixteen: could use some spacing between active filters http://cld.wthms.co/ckqrHw & http://cld.wthms.co/IjYej0

Storefront not looking great with new select2: http://cld.wthms.co/kzot6S

Random non-WC Sydney theme also not great: http://cld.wthms.co/1E6Goy

While technically theme issues, I think core should try to implement some better default styling in these two areas.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18178
