### ISSUE TITLE
Enable write access to API fields

### ISSUE THREAD

**Issue by amjad** [woocommerce/woocommerce#18152]
There are some fields like `created_at` (v3 legacy) date which have read only access. Is it possible to enable write access to this field? 

The use case here is, we are trying to make some "future orders" via the API. The app lists orders based on the created date. Some orders we want them to be in the future, something like we create the order for that day then we process it whenever.

**Comment by WPprodigy** [comment]
There is a `set_date_created` method: https://github.com/woocommerce/woocommerce/blob/7c06e7d63de921086d74dc6fd01ab370673eebe0/includes/abstracts/abstract-wc-order.php#L554

Which should be called when creating an order, here: https://github.com/woocommerce/woocommerce/blob/e3331448e5524136d06c8382fb77032bc2ea5870/includes/api/class-wc-rest-orders-controller.php#L455

So with at least the latest version of the REST API, having a `date_created` property on your new order object will do what you're wanting I believe. http://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order

**Comment by rodrigoprimo** [comment]
Closing this issue for now. Feel free to reopen if necessary.

**Comment by amjad** [comment]
Thanks. Can you help if this is possible with v3 legacy?

**Comment by WPprodigy** [comment]
Not 100% sure. But

1) There are lots of hooks and filters to use if not: https://github.com/woocommerce/woocommerce/blob/7c06e7d63de921086d74dc6fd01ab370673eebe0/includes/api/legacy/v3/class-wc-api-orders.php#L397

2) You should update to using the latest version of the REST API as legacy ones will be deprecated much sooner.

**Comment by amjad** [comment]
Unfortunately, I cannot upgrade past v3 legacy for this project. Its a very customized app running WooCommerce as a backend. 

I looked at the file you linked to. So would it be something like:

`'created_at'  => isset( $data['created_at'] ) ? $data['status'] : ' CURRENT DATE/TIME ',`
