### ISSUE TITLE
[3.3] Database table naming

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18158]
New `wp_wc_download_log` table doesn't really follow naming convention of other WC tables. Too late to change it, or was there a reason?

![database](https://user-images.githubusercontent.com/8536129/33974640-2b20e0b0-e04f-11e7-9e91-8b270f256cf7.png)

**Comment by WPprodigy** [comment]
`wc_webhooks` in the same boat, I just don't have that on my install for an unknown reason at the moment.

**Comment by willgorham** [comment]
Likely related to this I think: #16390

**Comment by WPprodigy** [comment]
Ah, missed that. Makes sense then I suppose, just an awkward in between stage.

**Comment by claudiosanches** [comment]
@WPprodigy need to activate WooCommerce again in your test environment in order to create all new tables, like `wc_webhooks`. But yeah, as @willgorham said, all new tables will be `wc_` saving us to move all tables in the future.

**Comment by WPprodigy** [comment]
@claudiosanches I do worry a bit that the name switching in the future will be more hassle than it will be worth.

The "table name too long" error is a really rare one, and something we could just check for and warn the user about instead in theory?

**Comment by alysivji** [comment]
@claudiosanches I tried deactivating and reactivating WooCommerce, but I am not seeing wc_webhooks. I have a couple of webhooks in there, but not sure where they are being stored.

Thanks for your help!

```console
MariaDB [woo-wp]> show tables;
+-------------------------------------------------+
| Tables_in_woo-wp                                |
+-------------------------------------------------+
| wp_commentmeta                                  |
| wp_comments                                     |
| wp_links                                        |
| wp_options                                      |
| wp_postmeta                                     |
| wp_posts                                        |
| wp_term_relationships                           |
| wp_term_taxonomy                                |
| wp_termmeta                                     |
| wp_terms                                        |
| wp_usermeta                                     |
| wp_users                                        |
| wp_woocommerce_api_keys                         |
| wp_woocommerce_attribute_taxonomies             |
| wp_woocommerce_downloadable_product_permissions |
| wp_woocommerce_log                              |
| wp_woocommerce_order_itemmeta                   |
| wp_woocommerce_order_items                      |
| wp_woocommerce_payment_tokenmeta                |
| wp_woocommerce_payment_tokens                   |
| wp_woocommerce_sessions                         |
| wp_woocommerce_shipping_zone_locations          |
| wp_woocommerce_shipping_zone_methods            |
| wp_woocommerce_shipping_zones                   |
| wp_woocommerce_tax_rate_locations               |
| wp_woocommerce_tax_rates                        |
+-------------------------------------------------+
```

**Comment by WPprodigy** [comment]
@alysivji Post your system status report.

**Comment by alysivji** [comment]
Just doing a Ctrl+F on this, looks like there is a shop webhook?

`
### WordPress Environment ###

Home URL: http://wordpress
Site URL: http://wordpress
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.0
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 2.35MB
Database Data Size: 1.55MB
Database Index Size: 0.80MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.05MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 2
page: 1
post: 2
product: 1
shop_webhook: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.2.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: [redacted]
Version: 1.0
Author URL: [redacted]
Child Theme: ✔
Parent Theme Name: Beaver Builder Theme
Parent Theme Version: 1.6.2
Parent Theme Author URL: http://www.wpbeaverbuilder.com/?utm_medium=bb-pro&utm_source=bb-theme&utm_campaign=themes-admin-page
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by WPprodigy** [comment]
You are on WC version 3.2.6, this new database comes in WooCommerce 3.3.

**Comment by alysivji** [comment]
@WPprodigy that makes sense

Where can I find the database entries for woocommerce webhooks in older versions

https://github.com/woocommerce/woocommerce/wiki/Database-Description this is the only document I can find, can't seem to find it for earlier versions.

I'm trying to create a testing environment inside of a container. Trying to create webhooks via sql.

Thanks so much for your help!

**Comment by WPprodigy** [comment]
I believe they were custom post types previously.

If you are doing something custom, and since WooCommerce 3.3 is just around the corner, I would recommend just updating to the 3.3 Release Candidate and going from there: https://github.com/woocommerce/woocommerce/releases
