### ISSUE TITLE
Cash on delivery (COD) shipping methods filter displays shipping method types instead of actual defined shipping methods

### ISSUE THREAD

**Issue by alexminza** [woocommerce/woocommerce#18153]
Url: /wp-admin/admin.php?page=wc-settings&tab=checkout&section=cod

<img width="654" alt="screen shot 2017-12-14 at 00 27 21" src="https://user-images.githubusercontent.com/149919/33965713-a5f4e1ae-e065-11e7-88ba-2803309f8742.png">

The COD shipping method filter should allow enabling/disabling for actual store defined shipping methods.

<img width="944" alt="screen shot 2017-12-14 at 00 30 04" src="https://user-images.githubusercontent.com/149919/33965813-f87f625a-e065-11e7-8032-2fa050432e75.png">

**Comment by WPprodigy** [comment]
The way [Conditional Shipping and Payments](https://www.woocommerce.com/products/woocommerce-conditional-shipping-and-payments/) displays this sort of functionality is pretty neat.

![](http://cld.wthms.co/pkn8nI+)

**Comment by mikejolley** [comment]
@franticpsyx Something you'd be happy to contribute since you wrote it?

**Comment by franticpsyx** [comment]
@mikejolley sure, should we plan this for 3.3/3.4?

**Comment by mikejolley** [comment]
We can mark as 3.4 but really, whenever you like :) We can keep any PRs on hold until they make sense for merge. Thanks 👍

**Comment by Sam-Hoult** [comment]
Is there an update on this?
Sadly Conditional Shipping and Payments doesn't work, and the docs for WooCommerce shipping API is lacking how to handle zones so stuck with this issue currently.

Thanks for all the work guys!

**Comment by franticpsyx** [comment]
@jimjasson has been doing some work here based on the CSP codebase, we're planning to look at some loose ends next week before submitting a PR.

**Comment by franticpsyx** [comment]
PR sent: https://github.com/woocommerce/woocommerce/pull/18596

**Comment by mikejolley** [comment]
Thanks @franticpsyx :) 

See https://github.com/woocommerce/woocommerce/pull/18596
