### ISSUE TITLE
Product sorting issue

### ISSUE THREAD

**Issue by webpalych** [woocommerce/woocommerce#18168]
Hi! I have found sorting and pagination issue. It happens when some of products have a same price and it sets sort ordering by price. This group of products always display in random order and they often duplicate on pagination.

Guys from Woocommerce twiiter account asked me to report my findings here.
This is the link to twitter conversation with screenshots and links:  https://twitter.com/WooCommerce/status/941261879971807232

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/18173
