### ISSUE TITLE
[3.3] UX: Customer Downloads Logging

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18161]
Not quite an issue, just logging for some ideas around how this could be made a bit better for user experience.

This feature is really cool, but feel it might be under-used due to discoverability. And the interface for using it could be tuned up a bit.

1) The chances of a user scrolling to the bottom of the orders page, discovering they can open up the downloadable product tabs, then clicking on the smallest link on the page with no real context as to what it does, is - well unlikely: http://cld.wthms.co/Diovc. It's also discoverable by wandering around the reports area, but still think the orders screen should do more to make it known.

2) Cancelling a filter doesn't seem too obvious in my opinion: http://cld.wthms.co/8dXuBy. I found myself just resetting the entire view a couple times before finding it.

3) When multiple filters are active, it doesn't look too great: http://cld.wthms.co/JJFiGW. Don't think these all need to be in the title with such a large font.

4) As a possible future feature, some filters like these would be nice for the downloads report screen: http://cld.wthms.co/63N9e8

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18162 looks good.

R/e 4 we have a roadmap item to revisit all reports so I've kept this one basic for that reason. Can be revisited in the future.

Cheers
