### ISSUE TITLE
Rounding issue in WC 3.2.6

### ISSUE THREAD

**Issue by Babelfisch** [woocommerce/woocommerce#18176]
Since update to 3.2.6 there are a lot of orders with wrong order total prices, like 10,01 EUR instead of 10,00 EUR. This wrong behavior occurs first since yesterday's update to 3.2.6.

All product prices in my shop are incl. tax and in settings I have checked rounding on subtotal level.

**Comment by Babelfisch** [comment]
Look at the order mail. The subtotal price is 10,00 EUR and the total is 10,01 EUR.

![screenshot 2017-12-14 17 28 33](https://user-images.githubusercontent.com/1218405/34002966-4fc2c780-e0f4-11e7-9c62-7aacb5e3c231.png)

**Comment by mikejolley** [comment]
Either provide the tax settings and prices saved in the db for the products, or submit a failing unit test.

**Comment by mikejolley** [comment]
> I have checked rounding on subtotal level

I think this may be the problem. You'll want that off so it rounds per line.

If you round at subtotal level there will be anomalies because it will round per line for display, and sum then round for the final tax total. That setting is uncommon.

**Comment by Babelfisch** [comment]
Ok, I trie to uncheck the rounding on subtotal level option. But it works fine up to the last update to 3.2.6. There must a change in this update thats cause the strange rounding behavior.

**Comment by mikejolley** [comment]
It's because it wasn't using the option correctly before and this has since been fixed. See comment https://github.com/woocommerce/woocommerce/pull/18008#issuecomment-349922204

> When prices exclude tax and rounding at subtotal level (and displaying prices including tax in cart), there is a 0.01$ difference between the cart contents total (manually adding up cart items) and cart total. However, because adding up unrounded taxes, this is expected.
