### ISSUE TITLE
Add ability to duplicate an existing product with the REST API and CLI

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#18171]
There is no command to duplicate an existing product. A topic like below could be created:

product.duplicate

**Comment by mikejolley** [comment]
This just takes 2 API operations; read the JSON, then PUT the JSON (remove the ID). A dedicated duplicate method does not seem needed, and I don't see this type of feature in other APIs? e.g. https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/duplicate-product-via-api-373339

As this is a feature request I'd suggest putting it on http://ideas.woocommerce.com/forums/133476-woocommerce anyhow, or contributing to https://github.com/woocommerce/wc-api-dev, but it doesn't sound necessary with the rest api.

Thanks
