### ISSUE TITLE
Enhancement: Adding filter in product shipping class dropdown

### ISSUE THREAD

**Issue by malsubrata** [woocommerce/woocommerce#18183]
## It will be better if there is a filter in display WooCommerce product shipping class dropdown arguments.
![edit product wordpress](https://user-images.githubusercontent.com/17632062/34029501-ffd3cd0a-e18e-11e7-95e3-cc6f16bd6be6.png)

**Comment by kloon** [comment]
Since the code to display that dropdown is generated from the wp_dropdown_categories function in WordPress core you can just use the wp_dropdown_cats filter to manipulate the values shown there.
