### ISSUE TITLE
Show Storefront notice in Wizard if using a default WordPress theme.

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce#18182]
## Steps to reproduce the issue

1. Wipe a site clean.
2. Go through wizard wanting to get recommended Storefront.
3. Won't get the notice, even if using a default WordPress theme.

## Expected/actual behavior

When I follow those steps, I'd expect to get Storefront recommended. I understand that notice won't show if using a WooCommerce compatible theme, and even though the default themes are, that seems like a good time to recommend Storefront. :)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18184

**Comment by dechov** [comment]
> even though the default themes are, that seems like a good time to recommend Storefront.

https://github.com/woocommerce/woocommerce/pull/18184 accomplishes this, but could it be improved further by omitting "Your theme is not compatible with WooCommerce." for this case? Likely not worth re-opening, but just a thought.
