### ISSUE TITLE
Wocommerce Wordpess REST API how to get categories subcategories

### ISSUE THREAD

**Issue by tapos007** [woocommerce/woocommerce#18181]
I need to get all categories and subcategories in REST API version 2

**Comment by WPprodigy** [comment]
https://developer.wordpress.org/rest-api/reference/taxonomies/

http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-categories

**Comment by szaniewski** [comment]
Hi :) I need help in similar problem

I use http://woocommerce.github.io/woocommerce-rest-api-docs/?php#list-all-product-categories

`$categorys = print_r($woocommerce->get('products/categories')); 

foreach( $categorys as $category ){
 print_r( $category );
}`

But i get only 10 item. How i can cheng this 

Best :)
