### ISSUE TITLE
Recalculate shipping admin-side

### ISSUE THREAD

**Issue by JasonTheAdams** [woocommerce/woocommerce#18199]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Create a new order admin-side or from the front-end
2. Place the order on-hold
3. Change the items in the order
4. Click "Save" & "Recalculate"

## Expected/actual behavior

When I follow those steps, I see the same shipping cost as before items were changed.

I was expecting to see a new shipping cost occur.

## Further Details

I'm in a custom WC project where we're building a custom shipping method to calculate the complex shipping needs of the client. When orders come in, they'll be automatically placed on-hold so a sales rep can work with the user to complete the order. At this point the sales rep will likely make changes to the order, having talked with the user, and then finalize the order when everything is ready.

It's important that the sales rep is able to recalculate the order as the order is changed. Even if this has to be done on the front end.

After digging around, this doesn't seem currently possible. It appears that the shipping editing is limited to simply entering a number — no calculations. If this is in development or half-complete in some way, I'd be happy to create a pull request for this. Really looking for some direction here; happy to discuss more and contribute to make this possible.

Saw #10861 and hoped there's at least been some progress since then as it's been over a year and a half since that ticket.

Thank you!

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: https://smartmantools.com
Site URL: https://smartmantools.com
WC Version: 3.0.9
Log Directory Writable: ✔
WP Version: 4.8.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31-4+wpengine10
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.37
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.9
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (19) ###

ManageWP - Worker: by ManageWP – 4.2.27
Gravity Forms: by rocketgenius – 2.2.3
AddToAny Share Buttons: by AddToAny – 1.7.21
Divi Builder: by Elegant Themes – 2.0.13
Google Tag Manager for Wordpress: by Thomas Geiger – 1.6.1
Easypost WooCommerce Extension: by WooForce – 1.5.16
GeoPosts: by Jason Adams – 0.2.0
Gravity Forms ActiveCampaign Add-On: by rocketgenius – 1.4.3
Piklist Helper: by Jason Adams – 0.6.0
Piklist: by Piklist – 0.9.9.13
Smart Reporter for e-commerce: by StoreApps – 2.9.18
WooCommerce Stripe Gateway: by WooCommerce – 3.2.0
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.4 – 1.3.6 is available
WooCommerce: by Automattic – 3.0.9 – 3.2.6 is available
WooCommerce Helper: by WooCommerce – 1.7.2 – Network enabled
Yoast SEO: by Team Yoast – 5.9.3
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.7
WP Migrate DB Pro: by Delicious Brains – 1.7.2
WP Engine Content Performance: by WP Engine – 1.3.0+506.c59a68c

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #17 - /products/
Cart: ❌ Page does not contain the shortcode.
Checkout: #19 - /checkout/
My account: #20 - /my-account/

### Theme ###

Name: Smartman Tools
Version: 2
Author URL: 
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: smartman-v2/woocommerce/archive-product.php
smartman-v2/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
smartman-v2/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
smartman-v2/woocommerce/global/wrapper-end.php
smartman-v2/woocommerce/global/wrapper-start.php
smartman-v2/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.0.0
smartman-v2/woocommerce/loop/price.php
smartman-v2/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
```
</details>

**Comment by WPprodigy** [comment]
> If this is in development or half-complete in some way, I'd be happy to create a pull request for this. Really looking for some direction here; happy to discuss more and contribute to make this possible.

Afaik, development on this hasn't started yet. And it's not on the official roadmap right now I think.

As far as the feature goes, it is something I think makes sense for core to have. It would be a good addition to the admin order experience, along with the new backend coupon functionality.

**Comment by mikejolley** [comment]
Whilst it doesn't appear to have many votes (http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/4956966-backend-re-calculation-of-shipping-costs) it is something on our long-term radar, but we have no short term plans to build this (other priorities).

I've noted the idea on https://trello.com/b/YgRbpuze/woocommerce-platform-roadmap but I've not assigned any dates. We'd need to abstract shipping further, refactor current shipping methods (this will likley be a breaking change), add a real API for it, and then use the same system on front/backend/rest api. It's not a small task. 

Thanks

**Comment by JasonTheAdams** [comment]
Got it. Thanks for making a note of it.

If it comes up down the road let me know, I'd be interested in contributing to it. I believe this sort of thing could be very valuable to purchase order e-commerce — wherein orders are created, discussed, finalized, and then processed. I believe this is a niche that WC currently doesn't work for, outside of considerable custom development (which is what we're doing on our project). We've had a number of clients inquire into this sort of workflow over the years.

Cheers! :)

**Comment by ijakparov** [comment]
JasonTheAdams, I need this functionallity too, it's really strange why it wasnt made before. I have very difficalt shipping calculation, and if customer asks me to add som item in his order I dont really know how to recalculate shipping.

My be you have a desigion for that?

**Comment by JasonTheAdams** [comment]
@ijakparov What I ended up doing, for my application, was make a metabox on the order page which uses react and ajax to calculate shipping _after_ the user has saved any changes to the order. The user then copy and pastes (don't love that) the value into the shipping field — which they fortunately can set to any value.

It's not quite as fluid, but it did the trick.

**Comment by ijakparov** [comment]
@JasonTheAdams, could u share your backend php code for that?

**Comment by JasonTheAdams** [comment]
@ijakparov Not really, I'm afraid, as it's proprietary to the project I worked on. But, conceptually, I made a custom REST API endpoint and pass the order id to the endpoint. The server then pulls up the order by the id and goes from there. Pretty simple, all things considered.

**Comment by ijakparov** [comment]
@JasonTheAdams, and how did u recount? Using your sipping public function from class to recount?

**Comment by WPprodigy** [comment]
Prolly best to not have conversation like this here. @ijakparov - you might need to consider hiring a developer for this: https://woocommerce.com/customizations/

**Comment by johnosmond** [comment]
This is maddening. Why is this topic closed? It's still a bug.

**Comment by patrickbussmann** [comment]
I saw this thing many times and now I thought its a good idea to release it as a plugin:
https://wordpress.org/plugins/admin-shipping-calculator/

Feel free to use 😇
