### ISSUE TITLE
Can't add new thumbs to the list flex-control-nav

### ISSUE THREAD

**Issue by edirpedro** [woocommerce/woocommerce#18195]
I was trying to include Embed content to the list of gallery thumbnails, it will open in a modal window, but it's not possible because the event click on thumbnails stays on the `<ol>` tag and not each `<li>` element, so when I click on the item, it tries to open an image inside the gallery and I couldn't find any option to stop this action.

![captura de tela 2017-12-15 as 13 40 30](https://user-images.githubusercontent.com/831507/34049179-92be6734-e19d-11e7-8a03-d8a175563f3f.png)

**Comment by mikejolley** [comment]
The `flex-control-nav` items are controlled by Flexslider (https://github.com/woocommerce/FlexSlider). What you're doing probably isn't supported as it's a gallery script and does not allow non-gallery thumbnails to be appended.

You can check https://github.com/woocommerce/FlexSlider to see if there is anything you can do to work around it, or suggest a new enhancement there.

You may be better off moving the two links outside of the gallery for now, or replacing flexslider via your theme with something else. Or you could see if it's possible to append items to the `ol` without the `flex-control-nav` class so the click events are not caught by flexslider.

Either way this is customisation territory and not an issue that should be solved in WC core. If you do need any changes, consider sending a PR if it makes sense.

Thanks

**Comment by edirpedro** [comment]
Ok, thanks @mikejolley
