### ISSUE TITLE
There should be a way to include "On hold" orders on the automatic cancelation

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#18191]
WooCommerce will automatically cancel "Pending" orders when the "WooCommerce > Settings > Products > Inventory > Hold stock (minutes)" option has a valid integer number configured.

On some specific use cases, it may be necessary to apply the same logic to "On hold" orders, but because this is not an everyday scenario, and extra communication with the client is needed, due to the offline nature of the payment method, this should not be a visible setting, but rather be achieved via a filter.

**Comment by mikejolley** [comment]
The problem with the suggested approach is that whilst on-hold orders are technically unpaid, deleting them after X minutes will be undesirable in most cases. If folks used the new filter as an unpaid flag for custom statuses, they may not necessary want the orders to delete.

In hindsight the function/cron could have been called 'cancel_pending_orders' in which case this suggestion would not have even been made, but it's too late for that.

I'd suggest keeping code similar to what you showed on Twitter, but leave the event scheduling to WooCommerce. Just add another callback to the `woocommerce_cancel_unpaid_orders` action and run a separate query.

**Comment by webdados** [comment]
Here's an example:

In Portugal, we have a payment method called "Multibanco". This consists of a unique reference being issued for the order and then the client should go to an ATM machine, or his homebanking service, and pay using that unique reference. We then have a callback mechanism that will "inform" WooCommerce that the reference was paid and the order should change state to "Processing".

So, it is an offline payment method, in the sense that it should generate the "new order" email for the client, with the payment instructions, just like bank transfer.

There are two kinds of "multibanco references" though: the ones that do not have a payment validity and the ones that do. This validity is set by a web service call to the portuguese banking system.
It would be useful, in this scenario, to also have "on hold" orders canceled automatically.

**Comment by webdados** [comment]
@mikejolley I'm just trying to find a solution that would fit other case scenarios, without having to mirror the code on "wc_cancel_unpaid_orders" and "WC_Data_Store get_unpaid_orders", that could be changed on future versions and would need to be maintained.

I still think a filter would be the best way of handling this, even if it's not applied on the "WC_Data_Store get_unpaid_orders" query like I proposed on my pull request, which I agree with you could have other implications rather than simply "cancel unpaid orders". Maybe something limited to this action and not on the entire concept of unpaid orders, which "on hold" actually and technically is, as you stated.

**Comment by mikejolley** [comment]
That scenario is no different to PayPal IPN, and that gateway leaves pending.

**Comment by webdados** [comment]
That gateway doesn't need to send payment details to the client email. This one, and similar ones, needs.

Only "on hold" orders trigger the email to the client.

**Comment by webdados** [comment]
What I'm trying to explain is that there are gateways all over the world that might not be just "online" or "offline", or "synchronous" or "asynchronous", and that might have a mixed way of doing things, that should be accounted for. It's because these are specific scenarios that I'm suggesting a filter somewhere. There are already a lot of filters on WooCommerce that, if used incorrectly, can mess up the entire shop. I don't see how something like this is so suited for a "won't fix" without further discussion.

**Comment by mikejolley** [comment]
Ok, that part makes sense. But the change you suggested whereby all unpaid status would be cancelled is probably not ideal.

> I'd suggest keeping code similar to what you showed on Twitter, but leave the event scheduling to WooCommerce. Just add another callback to the woocommerce_cancel_unpaid_orders action and run a separate query.

You don't need to handle schedules and events, you just need a custom callback function to do the delete.

**Comment by webdados** [comment]
Yes, I do not need to handle schedules and events, like I asked you on Twitter, but It's still necessary to mirror all the rest of the code on "wc_cancel_unpaid_orders" and "WC_Data_Store get_unpaid_orders", and that just doesn't seem elegant to me.

There's got be a better way 🙂  (that can be useful for others also)

![image](https://user-images.githubusercontent.com/6853605/34050032-593eb1b2-e1b1-11e7-8d8e-468dc52ad282.png)

**Comment by webdados** [comment]
Maybe get_unpaid_orders can have a second argument $unpaid_status that defaults to array( 'wc-pending' ) and wc_cancel_unpaid_orders can call it with a filter on it, so that it would only affect the process of canceling "unpaid" orders and not affect other places where get_unpaid_orders is called.
Would this be an acceptable solution for you @mikejolley ? I can work on that if you agree that could be implemented.

**Comment by mikejolley** [comment]
`wc_get_orders` can get orders by status. No need to use data stores?

**Comment by webdados** [comment]
Yes, but not by date/time to be able to use the 'woocommerce_hold_stock_minutes' as a base for our query. It can only get orders by 'date_before' or 'date_after'.

**Comment by mikejolley** [comment]
Whats the problem with date queries on wc_get_orders? I don't understand - it sounds like it would do exactly what you need.

**Comment by webdados** [comment]
@mikejolley You can't get orders from x minutes ago, to mimic what `WC_Data_Store::get_unpaid_orders` does, with `wc_get_orders` afaik. (I might be wrong)

If you use `date_before` it converts to a flat date (without hours and minutes) and it compares on the `post_created` field, not on `post_modified` like `WC_Data_Store::get_unpaid_orders`.

I was able to do it by adding a filter on `woocommerce_order_data_store_cpt_get_orders_query` and manipulating the date_query, but it's far from elegant or future proof (when orders are no longer WordPress posts).

**Comment by mikejolley** [comment]
@claudiulodro Does this support modified date?

**Comment by claudiulodro** [comment]
@webdados @mikejolley You can get orders by date_modified: https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#date

e.g. this should get the on-hold orders modified in the last hour:
```
$args = array(
    'date_modified' => '>' . ( time() - HOUR_IN_SECONDS ),
    'status' => 'on-hold',
);
$orders = wc_get_orders( $args );
```

**Comment by webdados** [comment]
@claudiulodro Thanks. You are absolutely right. I was using `post_modified` instead of `date_modified`. My bad.

@mikejolley We can be sure that, if we use `wc_get_orders`, the code will keep working when orders are no longer a WordPress post, right?

**Comment by claudiosanches** [comment]
@webdados yes, better use `wc_get_orders()`, since we plan have a custom database for orders soon.

**Comment by magedmoh94** [comment]
I Need to cancel the on-hold orders in a certain scenario after 4 hours from creating the order.

Example: 2 Customers

1st Customer Make Order at 5:00 PM so its on-hold status ( i want it to be canceled after 4 hours from the creation date of the order if he didn't pay so it has to be canceled on 9:00 PM )

2nd Customer Make Order at 5:37 so Its on-hold status ( i want it to be canceled after 4 hours too from the creation date of the order if he didn't pay so it has to be canceled on 9:37 )

I want it to cancel the orders immediately after each order is expired after 4 hours from the creation date of the order separately not as a cron job to work each 4 hours so in the previous example if the cron event starts at 6:00 PM and will run each 4 hours so the first customer order will expire on 10:00 PM and the 2nd will expire on 10:00 PM too.

I have tried the solution here https://stackoverflow.com/questions/55792360/automatically-cancel-order-after-x-days-if-no-payment-in-woocommerce

but couldn't make it expire after 4 hours as its defined in days only, also didn't know which answer of them is the best for me scenario to run for each order to be canceled separately after 4 hours from the creation date not as a cron event, 

I used many of the solutions mentioned in the related question above but only that works the first answer as i remember which is when admin/shop manager visits the orders page .. i need it to be done automatically without any actions from humans.

Here is my code in the plugin to cancel the orders

    <?php
    
    
    function ash2osh_faw_get_unpaid_submitted() {        
            global $wpdb;
              $options = get_option('woocommerce_' . ASH2OSH_FAW_PAYMENT_METHOD . '_settings');
            $expire_hours =  $options['unpaid_expire'];
            if(!trim($expire_hours)){
                $expire_hours='48';
            }
            $unpaid_submitted = $wpdb->get_col( $wpdb->prepare( "
                    SELECT posts.ID
                    FROM {$wpdb->posts} AS posts
                    WHERE posts.post_status = 'wc-on-hold'
                    AND posts.post_date < %s
            ", date( 'Y-m-d H:i:s', strtotime('-'.$expire_hours.' hours') ) ) ); 
            
            return $unpaid_submitted;
    }
    
    function ash2osh_faw_wc_cancel_unpaid_submitted() {        
            $unpaid_submit = ash2osh_faw_get_unpaid_submitted();
            
            if ( $unpaid_submit ) {                
                    foreach ( $unpaid_submit as $unpaid_order ) {                        
                            $order = wc_get_order( $unpaid_order );
                            $cancel_order = True;
    
                            foreach  ( $order->get_items() as $item_key => $item_values) {                                
                                    $manage_stock = get_post_meta( $item_values['variation_id'], '_manage_stock', true );
                                    if ( $manage_stock == "no" ) {                                        
                                            $payment_method = $order->get_payment_method();                                        
                                            if ( $payment_method == "cheque" ) {
                                                    $cancel_order = False;
                                            }
                                    }                                
                            }
                            if ( $cancel_order == True ) {
                                    $order -> update_status( 'cancelled', __( 'Unpaid submission expired after hours set in payment plugin options.', 'woocommerce') );
                            }
                    }
            }        
    }
    add_action( 'woocommerce_cancel_unpaid_submitted', 'ash2osh_faw_wc_cancel_unpaid_submitted' );//for customization purposes

**This third solution here: https://stackoverflow.com/questions/55792360/automatically-cancel-order-after-x-days-if-no-payment-in-woocommerce is tested and works fine: BUT i want it to be canceled when the order is on-hold status not completed/processing and to be canceled if its passed 4 hours after the order creation date and this to be scheduled and run each 30 min not daily**
