### ISSUE TITLE
Variable product allow to ad to cart only product with last added variation

### ISSUE THREAD

**Issue by igniens** [woocommerce/woocommerce#18200]
## Prerequisites

- [] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [* ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. Create in theme woocommerce/single

1. Create in your theme directory woocommerce/single-product/add-to-cart/variable.php
2. Remove table

## Expected/actual behavior

When I follow those steps, I see...
Clear link missing, when you press add to cart item will apear only if you will select most recent added variation
I was expecting to see... Clear link, normaly add product to cart

## Isolating the problem

- [* ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [* ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
Recent wp version and recent wordpress.org woocommerce version
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by WPprodigy** [comment]
Not sure I follow. You are removing the attributes table, and don't like the result of not being able to select variations? 0.o

**Comment by mikejolley** [comment]
Yeah we don't support customisations like this. If removing the attributes table has side effects (likely, it's required) thats not a problem in core, thats a problem with your change.
