### ISSUE TITLE
The product image set is not working.

### ISSUE THREAD

**Issue by runningjohan** [woocommerce/woocommerce#18205]
The product image set is not working. 

Meaning that when I click on the product image set and chose the image the selected image is not showing on the productpage... 

anyone else have this problem?

**Comment by Falke666** [comment]
Same problem here

**Comment by WPprodigy** [comment]
Please follow the issue template when opening up an issue. Specifically these two:

```
- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
```

There's a high chance this is either a plugin or theme conflict.

**Comment by Falke666** [comment]
I have three domains with woocommerce and test iit at all.

It happens when only WooCommerce plugon aktive and storefront is the default theme.

At one domain I make a backup before the update of woocommerce and there it works perfectly.

**Comment by WPprodigy** [comment]
To confirm:

The image selected here: http://cld.wthms.co/KzN70j
Is not showing up here: http://cld.wthms.co/xNOAjq ?

Please post a copy of your system status report if so.

**Comment by Falke666** [comment]
Ok I have located it.
After update the WooCommerce PayPal Express Checkout Gateway plugin it happend.
If I deactived it works fine.

**Comment by WPprodigy** [comment]
This plugin: https://wordpress.org/plugins/woocommerce-gateway-paypal-express-checkout/ ?

If so, you can report here: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues :)

**Comment by runningjohan** [comment]
Hi all, 

Thank you for looking to the problem.

Falke666 is right, WooCommerce PayPal Express Checkout Gateway plugin give me the problem.

I de-activated the plug-in an the problem was solved.

**Comment by mikejolley** [comment]
Please report where @WPprodigy said and include your system status report there because your issue lacks details.

Thanks

**Comment by sroumieux** [comment]
Same problem with product image : if I deactivate the WooCommerce PayPal Express Checkout Gateway, images are OK

**Comment by pahure** [comment]
Same problem with product image : if I deactivate the WooCommerce PayPal Express Checkout Gateway, images are OK

**Comment by mikejolley** [comment]
@mattyza ^

**Comment by mattyza** [comment]
@laurendavissmith ^

**Comment by laurendavissmith** [comment]
thanks @mattyza 

sounds like this might fix this one: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/376

its in master it just hasnt been released yet

**Comment by Njengah** [comment]
Same problem still no solution :(

**Comment by laurendavissmith** [comment]
@Njengah can you create a new issue on the PayPal Express Checkout repo with steps we can follow to reproduce, we haven't been seeing this issue again since rolling out the fix that was in my comment above. Thanks!

**Comment by Donald25** [comment]
I had the same problem (couldn't select product image from the gallery), tried fixing the issue but didn't work. I've deactivated the paypal express checkout plugin, and it worked so well.

**Comment by imankiyanoosh** [comment]
Hello everyone I have the same problem but when I try to select an image as you can see in the attachment there is a file selected which does not have name or link. I try to upload different images but none of them are working
![Screenshot (398)](https://user-images.githubusercontent.com/58703576/102422881-8ef8be80-3fbc-11eb-97f8-a7cfa7a6af23.png)

**Comment by FoodjunkieBE** [comment]
> Hello everyone I have the same problem but when I try to select an image as you can see in the attachment there is a file selected which does not have name or link. I try to upload different images but none of them are working
> ![Screenshot (398)](https://user-images.githubusercontent.com/58703576/102422881-8ef8be80-3fbc-11eb-97f8-a7cfa7a6af23.png)

Yeah I have the same since 1 month ago... can't find any solution for this... Did you already found one or not?
