### ISSUE TITLE
Custom single product page template for specific category?

### ISSUE THREAD

**Issue by lddd** [woocommerce/woocommerce#18210]
Hey there,

How to call a custom single product page template if products are within a specific category?

I want:
**"/theme/woocommerce/single-product-upcoming.php"** 

instead of 
**"/theme/woocommerce/single-product.php"**

Now is this possible without touching/editing the default **single-product.php** file with some conditional logic? 

All suggestions found and tried failed so far. 

thanks in advance for any help!

**Comment by WPprodigy** [comment]
Have a look here: https://developer.wordpress.org/themes/basics/template-hierarchy/. WordPress has lots of ways to declare specific templates. This website is pretty useful too: https://wphierarchy.com/

There, you can see that the two options for overriding single-product.php (because they come before single-$posttype) are:

- $custom.php (a custom template declared in the theme)
- single- $posttype-$slug.php (single-product-hats.php would match your "hats" product).

____

So with that, you'll see there is no option to serve a specific single template based on category. This makes sense, because you can have multiple categories per single post in WordPress. So custom logic is required for this.

Like you mentioned, having conditionals in the file itself that point to different template files based on if a certain category is found would work. Could also use the `single_template` filter. Some solutions here: https://wordpress.stackexchange.com/questions/169831/custom-single-template-for-a-specific-category

**Comment by lddd** [comment]
Hello,

thanks for your kind reply. I tried the following:

Added a 'wc_get_template_part' filter that searches for templates named after the product category. 

1 ) In my childs theme functions.php added:
```
/**
 * 
 * Redirect to specific single product page template based on category
 */

function my_custom_product_template($template, $slug, $name) {
    if ($name === 'single-product' && $slug === 'content') {
        global $product_cat;
        $temp = locate_template(array("{$slug}-{$name}-{$product_cat}.php", WC()->template_path() . "{$slug}-{$name}-{$product_cat}.php"));
        if($temp) {
           $template = $temp;
        }
    }
    return $template;
}

add_filter('wc_get_template_part', 'my_custom_product_template', 10, 3);
```
Now created a template for the product in my theme's woocommerce templates named 'content-single-product-upcoming.php' 

**So it looks**
/themes/theme-child/woocommerce/
/themes/theme-child/woocommerce/content-single-product-upcoming.php
/themes/themechild/functions.php

Now everything loads fine but without any affect to the new created product page template. 

Visiting a single product page for that category e.g "domain.com/upcoming/some-product" does not make any different to another product from any other category. I can leave the new template file complete blank and its loading with the default one. 

So i guess my filter added to the themes functions.php does not work out, but why?

**Comment by WPprodigy** [comment]
I'd recommend error logging (var dump, print_r, error_log, etc) the `$template, $slug, $name` variables before any conditionals in the function. That'll give you a better idea of how this filter works.

Once you have that and your conditions set up right, error_log `$temp` before the inner conditional.

On first glance, it doesn't look like you are using the attributes correctly from the filter, and pulling in the product cat like that isn't going to work either I believe. Product's can have multiple categories - you need logic to pull the categories from the product in question, and look for the existence of a specific one. See the above stack exchange link.

This is not the place to ask for support though I'm afraid. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooCommerce Support](https://docs.woocommerce.com/) page.

**Comment by sanderlt** [comment]
> Have a look here: https://developer.wordpress.org/themes/basics/template-hierarchy/. WordPress has lots of ways to declare specific templates. This website is pretty useful too: https://wphierarchy.com/
> 
> There, you can see that the two options for overriding single-product.php (because they come before single-$posttype) are:
> 
> * $custom.php (a custom template declared in the theme)
> * single- $posttype-$slug.php (single-product-hats.php would match your "hats" product).
> 
> So with that, you'll see there is no option to serve a specific single template based on category. This makes sense, because you can have multiple categories per single post in WordPress. So custom logic is required for this.
> 
> Like you mentioned, having conditionals in the file itself that point to different template files based on if a certain category is found would work. Could also use the `single_template` filter. Some solutions here: https://wordpress.stackexchange.com/questions/169831/custom-single-template-for-a-specific-category

is it works with woocommerce categories? thanks
