### ISSUE TITLE
Incorrect shipping tax gets applied when tax rate is zero

### ISSUE THREAD

**Issue by RobertoDonPedro** [woocommerce/woocommerce#18217]
Hi guys, there is a severe issue in function 'get_shipping_tax_rates' in 'class-wc-tax.php' Class 'WC_Tax':
Here automatically the standard rate! is applied when no shipping tax was found.  This is an incorrect behavour. since it is expected that no shipping tax is availabe, eg. when an zero tax rate was applied,
The issue is here:
            // Get standard rate if no taxes were found
            if ( ! sizeof( $matched_tax_rates ) ) {

Sorry for the brief information, but I'm very close with my time.

**Comment by mikejolley** [comment]
>  since it is expected that no shipping tax is availabe, eg. when an zero tax rate was applied

This code does not execute if there is a zero tax rate, it executes if there are no tax rates at all. If your zero-rated tax rates are enabled for shipping, standard rate will not load.

So solution; ensure all tax rates are also enabled for shipping, even the 0% ones.
