### ISSUE TITLE
Add an argument to woocommerce_product_related_posts_query filter with query args used, not just results and parent product ID

### ISSUE THREAD

**Issue by unfulvio** [woocommerce/woocommerce#18223]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Details of the issue

The [filter `woocommerce_product_related_posts_query`](https://github.com/woocommerce/woocommerce/blob/3.2.6/includes/data-stores/class-wc-product-data-store-cpt.php#L1012) is used in WC3.0+ to alter the related products results. However, only the SQL query clauses and the product ID the results are related to are passed to this filter. Which makes harder for plugins like Memberships that need to alter or trim down the results to replicate the same query. Parsing the strings in the SQL clauses doesn't look like a good idea.

For these purposes, I propose that the [args of the `WC_Product_Data_Store_CPT::get_related_products()`](https://github.com/woocommerce/woocommerce/blob/3.2.6/includes/data-stores/class-wc-product-data-store-cpt.php#L1010) method are passed as a third argument to this filter in the form of an array of arguments. Future arguments or variables added to the method can be easily ported to this argument as well.

In this way, if a third party needs to perform a new query to adjust the SQL clauses (and ultimately the results), the new query can take into account of some of the original variables passed to `WC_Product_Data_Store_CPT::get_related_products()`.

**Comment by claudiosanches** [comment]
Closed by #18224

**Comment by unfulvio** [comment]
Hey there, thanks for merging this!

Unfortunately I realized we need one more filter, or address another issue. I realized that WooCommerce is caching results of found related products in this transient here:

https://github.com/woocommerce/woocommerce/blob/eb60a17818706a156efbc99e3c330bb38b569df7/includes/wc-product-functions.php#L839-L855

However, this transient ignores the arguments used. Which means if I have multiple instances where this function is used, the results will be always the same regardless of the arguments passed for at least one day.

I'm opening two more PRs to address this, following this comment

**Comment by unfulvio** [comment]
I see two ways to help this. 

Ideally, I think the transient should manage the query arguments. Considering a single product could be queried for related products with different arguments, we could cache these arguments in an array key-value as in: https://github.com/woocommerce/woocommerce/pull/18307 -- in this way the current transient name is also preserved. And could be filtered by third parties that could also decode the queried arguments. 

An alternative way could be storing the args in the transient name (perhaps with something like `md5( json_encode( $query_args ) );` and append these to `$transient_name = 'wc_related_' . $product_id . '_' . $query_args;`). But in that case it wouldn't be practical for third party code to filter this transient anymore. 

Finally, I think the related posts results should be made filterable as well as shown in https://github.com/woocommerce/woocommerce/pull/18306

This provides another way for third party code to change the results, regardless of the transient handling.
