### ISSUE TITLE
Cannot Filter Short Description If Empty

### ISSUE THREAD

**Issue by turtlepod** [woocommerce/woocommerce#18225]
Should run the filter before checking if it's empty:
https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/short-description.php#L25

```
if ( ! $post->post_excerpt ) {
	return;
}
```

This will make the filter useless if no content in excerpt.
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

**Comment by rodrigoprimo** [comment]
Makes sense to me. Care to open a PR with the suggested change?
