### ISSUE TITLE
Filtering GET /products by multiple product attributes

### ISSUE THREAD

**Issue by loganyott** [woocommerce/woocommerce#18221]
Listing products from the REST API (`wp-json/wc/v2/products`) only allows a single `attribute` and `attribute_term` combination to be used as a filter. I would expect to be able to filter products by multiple product attributes similar to how the normal WooCommerce shop functions.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Add multiple product attributes
2. Enable REST API
3. Visit `wp-json/wc/v2/products` 

## Expected/actual behavior

When I follow those steps, I see...
`wp-json/wc/v2/products` only supports a single `attribute` and `attribute_term`

I was expecting to see...
A method to filter products by multiple product attributes

**Comment by claudiosanches** [comment]
See #18222
