### ISSUE TITLE
Product's post_modified date not updated when stock updated after new order

### ISSUE THREAD

**Issue by bryceadams** [woocommerce/woocommerce#18228]
When a new order triggers a stock change, the product's stock count is updated but the product/post's `post_modified` & `post_modified_gmt` values aren't updated.

Reproduce:

1. Check out with a product that has stock managed.
2. Check if product's `post_modified` value changed.

**Comment by mikejolley** [comment]
👋  :trollface: 

This was reported in https://github.com/woocommerce/woocommerce/issues/17841

See https://github.com/woocommerce/woocommerce/pull/18013
