### ISSUE TITLE
Filtering products with attribute value = 0 (zero)

### ISSUE THREAD

**Issue by usefull-snippets** [woocommerce/woocommerce#18230]
Hi,
I am having an issue when I try to filter products with an attribute value = 0 (zero).
Seems that it evaluates the zero value as to be no filter, and reteieves all the products, not just the one with a value of zero.

See more details below.
Thanks in advance.

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [x ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to http://avamoplast.intestmode.be/en/products/?swoof=1&pa_volume=0, this URL means that the filter attribute "volume" is set to zero.
2. It should retrieve the products with volume = zero, but instead retrieves all the products.

## Expected/actual behavior

When I follow those steps, I see that the filtering retrieves all the products

I was expecting to see just the products with the attribute volume set to zero.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://avamoplast.intestmode.be
Site URL: http://avamoplast.intestmode.be
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.32
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.52.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: bg5s_
MaxMind GeoIP Database: ✔
Total Database Size: 73.27MB
Database Data Size: 54.33MB
Database Index Size: 18.94MB
bg5s_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
bg5s_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
bg5s_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
bg5s_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
bg5s_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
bg5s_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
bg5s_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
bg5s_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
bg5s_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
bg5s_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
bg5s_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
bg5s_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
bg5s_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
bg5s_woocommerce_log: Data: 0.02MB + Index: 0.02MB
bg5s_commentmeta: Data: 0.02MB + Index: 0.03MB
bg5s_comments: Data: 0.02MB + Index: 0.09MB
bg5s_duplicator_packages: Data: 0.02MB + Index: 0.02MB
bg5s_enquiry_detail_new: Data: 0.02MB + Index: 0.02MB
bg5s_enquiry_history: Data: 0.02MB + Index: 0.02MB
bg5s_enquiry_meta: Data: 0.02MB + Index: 0.03MB
bg5s_enquiry_products: Data: 0.02MB + Index: 0.00MB
bg5s_enquiry_quotation: Data: 0.02MB + Index: 0.00MB
bg5s_enquiry_quotation_version: Data: 0.02MB + Index: 0.00MB
bg5s_enquiry_thread: Data: 0.02MB + Index: 0.00MB
bg5s_icl_content_status: Data: 0.02MB + Index: 0.02MB
bg5s_icl_core_status: Data: 0.02MB + Index: 0.02MB
bg5s_icl_flags: Data: 0.02MB + Index: 0.02MB
bg5s_icl_languages: Data: 0.02MB + Index: 0.03MB
bg5s_icl_languages_translations: Data: 0.19MB + Index: 0.08MB
bg5s_icl_locale_map: Data: 0.02MB + Index: 0.00MB
bg5s_icl_message_status: Data: 0.02MB + Index: 0.03MB
bg5s_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB
bg5s_icl_node: Data: 0.02MB + Index: 0.00MB
bg5s_icl_reminders: Data: 0.02MB + Index: 0.00MB
bg5s_icl_strings: Data: 4.52MB + Index: 4.55MB
bg5s_icl_string_packages: Data: 0.02MB + Index: 0.00MB
bg5s_icl_string_pages: Data: 1.52MB + Index: 0.47MB
bg5s_icl_string_positions: Data: 0.09MB + Index: 0.02MB
bg5s_icl_string_status: Data: 0.02MB + Index: 0.02MB
bg5s_icl_string_translations: Data: 4.52MB + Index: 1.52MB
bg5s_icl_string_urls: Data: 0.02MB + Index: 0.02MB
bg5s_icl_translate: Data: 2.52MB + Index: 0.20MB
bg5s_icl_translate_job: Data: 0.05MB + Index: 0.02MB
bg5s_icl_translations: Data: 0.38MB + Index: 0.75MB
bg5s_icl_translation_batches: Data: 0.02MB + Index: 0.00MB
bg5s_icl_translation_status: Data: 1.52MB + Index: 0.08MB
bg5s_links: Data: 0.02MB + Index: 0.02MB
bg5s_options: Data: 4.42MB + Index: 0.20MB
bg5s_postmeta: Data: 19.55MB + Index: 8.03MB
bg5s_posts: Data: 5.52MB + Index: 0.53MB
bg5s_revslider_css: Data: 0.13MB + Index: 0.00MB
bg5s_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
bg5s_revslider_navigations: Data: 0.02MB + Index: 0.00MB
bg5s_revslider_sliders: Data: 0.02MB + Index: 0.00MB
bg5s_revslider_slides: Data: 0.02MB + Index: 0.00MB
bg5s_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
bg5s_rg_form: Data: 0.02MB + Index: 0.00MB
bg5s_rg_form_meta: Data: 0.02MB + Index: 0.00MB
bg5s_rg_form_view: Data: 0.02MB + Index: 0.03MB
bg5s_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
bg5s_rg_lead: Data: 0.02MB + Index: 0.03MB
bg5s_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
bg5s_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
bg5s_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
bg5s_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
bg5s_smush_dir_images: Data: 0.02MB + Index: 0.03MB
bg5s_termmeta: Data: 0.17MB + Index: 0.16MB
bg5s_terms: Data: 0.11MB + Index: 0.11MB
bg5s_term_relationships: Data: 1.52MB + Index: 0.52MB
bg5s_term_taxonomy: Data: 0.14MB + Index: 0.14MB
bg5s_usermeta: Data: 0.02MB + Index: 0.03MB
bg5s_users: Data: 0.02MB + Index: 0.05MB
bg5s_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
bg5s_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
bg5s_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
bg5s_wfBlocks: Data: 0.02MB + Index: 0.02MB
bg5s_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
bg5s_wfConfig: Data: 0.28MB + Index: 0.00MB
bg5s_wfCrawlers: Data: 0.02MB + Index: 0.00MB
bg5s_wfFileMods: Data: 3.52MB + Index: 0.00MB
bg5s_wfHits: Data: 0.39MB + Index: 0.17MB
bg5s_wfHoover: Data: 0.02MB + Index: 0.02MB
bg5s_wfIssues: Data: 0.02MB + Index: 0.00MB
bg5s_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
bg5s_wfLeechers: Data: 0.02MB + Index: 0.00MB
bg5s_wfLockedOut: Data: 0.02MB + Index: 0.00MB
bg5s_wfLocs: Data: 0.02MB + Index: 0.00MB
bg5s_wfLogins: Data: 0.02MB + Index: 0.03MB
bg5s_wfNet404s: Data: 0.02MB + Index: 0.02MB
bg5s_wfNotifications: Data: 0.02MB + Index: 0.00MB
bg5s_wfPendingIssues: Data: 0.02MB + Index: 0.00MB
bg5s_wfReverseCache: Data: 0.02MB + Index: 0.00MB
bg5s_wfScanners: Data: 0.02MB + Index: 0.00MB
bg5s_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
bg5s_wfStatus: Data: 0.13MB + Index: 0.09MB
bg5s_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
bg5s_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
bg5s_woof_query_cache: Data: 0.02MB + Index: 0.02MB
bg5s_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
bg5s_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1400
form: 4
fusion_element: 4
nav_menu_item: 108
page: 55
post: 4
product: 2092
revision: 232
slide: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (24) ###

WPML Multilingual CMS: by OnTheGoSystems – 3.8.4
Admin Menu Editor Pro: by Janis Elsts – 2.6
Contact Form 7: by Takayuki Miyoshi – 4.9.2
Custom Functions Dev: by Ingamana – 1
Duplicate Page: by mndpsingh287 – 2.4
Duplicator: by Snap Creek – 1.2.30
Fusion Builder: by ThemeFusion – 1.3.1
Fusion Core: by ThemeFusion – 3.3.1
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.1.2.4
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Post Types Order: by Nsp Code – 1.9.3.5
Product Enquiry Pro for WooCommerce (A.K.A QuoteUp): by WisdmLabs – 6.0.0 – Not tested with the active version of WooCommerce
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.0
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.5.2.2
WooCommerce Multilingual: by OnTheGoSystems – 4.2.7.1
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.16 – 1.10.17 is available – Not tested with the active version of WooCommerce
WOOF - WooCommerce Products Filter: by realmag777 – 2.1.8 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.6
Wordfence Security: by Wordfence – 6.3.22
Yoast SEO: by Team Yoast – 5.9.3
WP Smush: by WPMU DEV – 2.7.6
WPML Media: by OnTheGoSystems – 2.2.1
WPML String Translation: by OnTheGoSystems – 2.6.3
WPML Translation Management: by OnTheGoSystems – 2.4.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #68 - /en/products/
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada
Version: 5.3.1
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###
Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php
</details>

**Comment by claudiulodro** [comment]
Those filters are from the `WOOF - WooCommerce Products Filter: by realmag777` plugin and are not part of the WooCommerce core plugin. I suggest contacting the plugin author.
