### ISSUE TITLE
Rest Api Empty attributes, default_attributes & grouped_products using querystring

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#18249]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Same Issue as #18104 only with attributes and default_attributes (images works fine now btw. :D)

Also grouped_products takes only 0 instead of empty arrays, but thats also not accepted in attributes default_attributes. And downloads has the same behaviour as grouped_products that it only accepts 0 for empty arrays.

Isnt it better to have a global handler / behaviour for empty arrays in the rest api? I find it a little difficult to track all the differences by now.

## Expected/actual behavior

Here is an example using POST

**Request**
```
Request URL:http://localhost:9001/wp-json/wc/v2/products?attributes%5B0%5D&oauth_consumer_key=ck_9d24a68cad948b89857a4788b190db43bd5240e0&oauth_nonce=94R4Wv&oauth_signature=EsxHQnn1N4tjW3YczjjsCJygzYc%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1513808516&oauth_version=1.0
Request Method:POST
Status Code:400 Bad Request
Remote Address:[::1]:9001
Referrer Policy:no-referrer-when-downgrade
```

**Queryparams**
```
attributes[0]:
oauth_consumer_key:ck_9d24a68cad948b89857a4788b190db43bd5240e0
oauth_nonce:94R4Wv
oauth_signature:EsxHQnn1N4tjW3YczjjsCJygzYc=
oauth_signature_method:HMAC-SHA1
oauth_timestamp:1513808516
oauth_version:1.0
```

**Response**
```
code:"rest_invalid_param"
data:{status: 400, params: {attributes: "attributes[0] er ikke av typen object."}}
message:"Ugyldig(e) parameter(e): attributes"
```

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by rodrigoprimo** [comment]
cc @claudiosanches

**Comment by claudiosanches** [comment]
@steffanhalv note that WordPress take care of it, but for some reason send a different array when is query strings, we are doing some changes to improve it, but still should be good report it to WP core.

**Comment by steffanhalv** [comment]
@claudiosanches https://core.trac.wordpress.org/ticket/42961#ticket

Please contribute by commenting on the ticket if you got something to add. I described it as I understand this.

I also believe it could have a possible relationship with https://github.com/woocommerce/woocommerce/issues/17954 (https://core.trac.wordpress.org/ticket/42752)

**Comment by mikejolley** [comment]
@claudiosanches What are the next steps for us here?

**Comment by steffanhalv** [comment]
@mikejolley

One option would be to run array_filter() on any array items in the query string, but doing so also means moving away from standard PHP URL parsing quirks.

Quote from wp ticket..

**Comment by claudiosanches** [comment]
@mikejolley ticket is still open on WP core and the response is not the same as expected.
So better wait for WP Core solution.

**Comment by mikejolley** [comment]
This was patched in core here https://core.trac.wordpress.org/ticket/42752

@steffanhalv let us know if it doesn't resolve it for you.

**Comment by steffanhalv** [comment]
@mikejolley Still not resolved.

Error in path doesn't resolve this issue.

The correct bug which needs to be solved is this one:

https://core.trac.wordpress.org/ticket/42961#ticket
