### ISSUE TITLE
embed tag in short description disappears

### ISSUE THREAD

**Issue by angelZambrano** [woocommerce/woocommerce#18244]
Hi, I cannot insert videos with [embed] tag in short description. 

The short description remains in the edit product view, but in the catalogue disappears.

this is the html that I'm using:

```
here video:

[embed width="11" height="11"]https://youtu.be/Jo5xZMkrfoM[/embed]
```
I need to use this specifict tag because I'm passasing this information via API, and cannot use tags like '<iframe>', '< object >' or < embed  >, due to this tag can be passed from the API client.

Regards.

**Comment by claudiosanches** [comment]
Autoembed works with `https://youtu.be/Jo5xZMkrfoM`, but not when using `embed` shortcode.

**Comment by claudiulodro** [comment]
See #18263

**Comment by claudiulodro** [comment]
If you're using WooCommerce version >= 3.2.7, you should be able to use the `embed` shortcode in the short description field. If it isn't working properly please open a new issue with details on how to reproduce and what is happening.

**Comment by yataylimit** [comment]
Hi, 
I use Woocommerce 3.5.3 and the problem still continues. I copy the embed code which is directly taken from a YouTube video and paste it on the short descriptions section. It stays there for a couple of days and then it is cleaned all by itself. 

Here is an example code: 

<iframe width="560" height="315" src="https://www.youtube.com/embed/P4DUEF-gfkk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by sanwhere** [comment]
> Hi,
> I use Woocommerce 3.5.3 and the problem still continues. I copy the embed code which is directly taken from a YouTube video and paste it on the short descriptions section. It stays there for a couple of days and then it is cleaned all by itself.
> 
> Here is an example code:
> 
> <iframe width="560" height="315" src="https://www.youtube.com/embed/P4DUEF-gfkk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

i have the same problem, did you find out what is the problem with this? 

i have a script, and suddenly today, every product has no script in this section. I have only `/**/` this instead of script.
