### ISSUE TITLE
Files docblocks tags standard

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#18245]
We are not follow anything standard right now, so I like to propose the follow:

```php
/**
 * Regular order
 *
 * @package WooCommerce\Orders
 * @version 2.2.0
 * @since   1.0.0
 */
```

Only use `@package`, `@version` and `@since`, sometimes we could use `@deprecated`.
No reason to include `@author`, and `@category` is deprecated.

Note that `@package` only accepts `\` and not `/` as we have using (also note that `@category` has been deprecated in favor of `@package`).

Tags like `@copyright` and `@license` are not required in this project, since all code base have the same license.
Also for the PHP notation, and now WordPress allows to declare support PHP version.

For the other tags like `@see` and `@link` we could use when necessary, but right now we don't have much use anyway.

We also should improve the usage of `@package`. Here how is documentation by phpDocumentor:
http://docs.phpdoc.org/references/phpdoc/tags/package.html

**Comment by mikejolley** [comment]
@claudiosanches Rather than keep an issue open for all files in WC core (there are a lot) can we not document this and/or add a pre-commit check? Then it can be handled like our PHPCS changes.

**Comment by claudiosanches** [comment]
@mikejolley yep, I'll do it, just registering here if someone want to give some input.
