### ISSUE TITLE
Product/Order edit and leaving page confirmation

### ISSUE THREAD

**Issue by seostudio** [woocommerce/woocommerce#18240]
Hi,

there is in Wordpress built in functionality to confirm leaving page without saving changes after changing post fields. It works on built in Wordpress fields on product edit page. But not works on all other fields.

This is bug or feature?

**Comment by claudiosanches** [comment]
On WordPress this only happens when changing the content on the text editor.
But does not trigger that alert when when change categories, tags, featured image and so on.
So WooCommerce does almost the same.
