### ISSUE TITLE
Two nonces with same ID on checkout page

### ISSUE THREAD

**Issue by Firebird75** [woocommerce/woocommerce#18241]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

The problem is that the checkout page contains two nonces with the same ID _wpnonce.

You can see this there for example : https://demo.woothemes.com/storefront/checkout/

This is causing an error in Chrome console.

You can see the issue by going to the page and checking the source. Two forms are using the same nonce ID.

This issue happens with latest Woocommerce release (verified on multiple sites).

**Comment by claudiulodro** [comment]
Thanks for the report. This was fixed in #18214.
