### ISSUE TITLE
Email sent to customer contains wrong unit price

### ISSUE THREAD

**Issue by elad560** [woocommerce/woocommerce#18253]
Hi,
When customer place an order the system sends an email with the order details.
In case the customer order more than one unit it shows the total price instead of the unit price.

![466](https://user-images.githubusercontent.com/34736750/34247238-6ea33bd0-e63a-11e7-9eb7-aa5659da6f59.png)

The calculation is:
1  unit * 450.5
2 units * **254.80**
sub total 960.10
add shipping 105.00

total : 1065.10

However in the email it is shown as:
1 unit * 450.5
2 units * **509.60**
sub total 960.10
add  shipping 105.00

total : 1065.10

This is only a display issue in the email - in the Order tab it shows the information correctly

WordPress version:  4.9.1
WooCommerce version: 3.2.6

**Comment by WPprodigy** [comment]
Fairly sure that is the intended behavior. On other screens where individual cost is shown, there are three columns for the cost / qty / total: http://cld.wthms.co/W1zL74.

In the email, it is showing just the qty / total part of that.

**Comment by elad560** [comment]
@WPprodigy 
It can't be the intended behavior. The  email currently shows data which easily can be misunderstood.
When you show quantity 2 and price 509.60 normally people will multiply them.
If this is the requested behavior there should be a column between "Unit Price"  then it will be:
Quantity |  Unit-Price | Total
1             |    450.5      |      450.5
2             |    254.80    |     509.60
SUB TOTAL:                       960.10


Showing it as: 
Quantity  | Total
1              |      450.5
2              |     509.60
SUB TOTAL:   960.10

Caused me to think that the customer didn't pay 509.60 USD... it can be easily misinterpreted.

**Comment by mikejolley** [comment]
This is the first time this has been brought up, so I'm not sure it's a common misunderstanding. The column header is **TOTAL**. Not unit/price like on other screens. 

Also as it's shown in a table, I'm sure most people would expect the values in the column to add up to the subtotal, like in a spreadsheet. Also like the cart/checkout screen.

If it's really confusing for you/client you can customise the email templates - we allow full control over those via filters and template overrides. Requires some custom dev.

Thanks

**Comment by elad560** [comment]
@mikejolley  Don't you agree that adding a unit price column would solve any confusion that can happen?

When you go to the supermarket and you buy 2 units of milk (say 5$ per unit) how would the bill report look like?
It will never look like:

item   quantity  total
milk          2      10

So the confusion is caused because this invoice isn't like what people normally know.

**Comment by mikejolley** [comment]
@elad560 I just dug out some receipts and they show total price as the last column.

This is not a formal invoice.
