### ISSUE TITLE
Changes to Icons in WC 3.3.0-Beta 1

### ISSUE THREAD

**Issue by ChromeOrange** [woocommerce/woocommerce#18255]
What changes have been made to the icons?

The ONLY difference between these screen shots is changing WooCommerce 3.2 (latest) to WooCommerce 3.3.0-Beta1

![](https://cl.ly/0s2z0f2E2J3j/Image%202017-12-21%20at%2012.48.23%20pm.png)

There are no errors in the console / debug.log
The CSS from my plugin is loading properly.

Apologies if I've missed a discussion on this.

**Comment by ChromeOrange** [comment]
Sorry, to clarify, this ice is from my plugin, not a WooCommerce icon.

**Comment by mikejolley** [comment]
@ChromeOrange Probably default font-face - there was a mix between WooCommerce icons and Dashicons. What is your icon from?

**Comment by ChromeOrange** [comment]
@mikejolley I've created my own and include them with the plugin code and use @font-face to use them.

**Comment by mikejolley** [comment]
What plugin can we test for this?

**Comment by ChromeOrange** [comment]
PDF Invoices

**Comment by mikejolley** [comment]
@ChromeOrange I don't think it's related to this update since either icon font doesn't work.

Look at the CSS here https://github.com/woocommerce/woocommerce-pdf-invoice/blob/master/assets/css/woocommerce-pdf-admin-css.css#L103

It should be `::after` not `:after`. The CSS looks invalid to me.
