### ISSUE TITLE
duplicity telephone and email

### ISSUE THREAD

**Issue by marivimunozf** [woocommerce/woocommerce#18254]
Good Morning,

On my website, when you place an order in the billing information, the phone and email are duplicated. Both on the web to confirm that the order has been made correctly, and in the confirmation email received by the customer. 

How can I solve that?

Thank you

**Comment by WPprodigy** [comment]
I just did some testing, and could not replicate this behavior. There is something on your website specifically causing a conflict, like another plugin or the theme.

This is not the place to ask for support though. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooCommerce Support](https://docs.woocommerce.com/) page.

**Comment by mikejolley** [comment]
Likely theme template overrides in this case.
