### ISSUE TITLE
Filter tag by name instead of ID

### ISSUE THREAD

**Issue by ThomasVeld** [woocommerce/woocommerce#18258]
Hi,

is there an option to get a tag by name instead of ID?
Else I will have to loop through all tags and it slows down the process.

**Comment by mikejolley** [comment]
You can use this function to get the ID from the name https://codex.wordpress.org/Function_Reference/get_term_by

**Comment by ThomasVeld** [comment]
Sorry I'm talking about the REST API

**Comment by mikejolley** [comment]
I don't think there is a search/endpoint for that. cc @claudiosanches

**Comment by claudiosanches** [comment]
You can get by slug.

Like:

```
GET /wp-json/wc/v2/products/tags?slug=tag-slug
```
