### ISSUE TITLE
cant edit pages anymore

### ISSUE THREAD

**Issue by chrisgeist** [woocommerce/woocommerce#18264]
since the last update of woocommerce and wordpress i cant edit pages which include products anymore.

thanks for the help,

chris
<details>
-------------------
`
### WordPress Environment ###

Home URL: https://www.paragliding-academy.com
Site URL: https://www.paragliding-academy.com/wordpress
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.11-nmm1
PHP Post Max Size: 1.000 MB
PHP Time Limit: 0
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.20
Max Upload Size: 1.000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 228.71MB
Datenbank-Datengröße: 164.74MB
Datenbank-Indexgröße: 63.97MB
wp_woocommerce_sessions: Daten: 0.22MB + Index: 0.01MB
wp_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.01MB
wp_woocommerce_order_items: Daten: 0.67MB + Index: 0.26MB
wp_woocommerce_order_itemmeta: Daten: 3.88MB + Index: 2.34MB
wp_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.01MB
wp_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Daten: 0.00MB + Index: 0.00MB
woof_query_cache: Daten: 0.00MB + Index: 0.00MB
wp_bpspro_db_backup: Daten: 0.00MB + Index: 0.00MB
wp_bpspro_login_security: Daten: 0.00MB + Index: 0.00MB
wp_bpspro_seclog_ignore: Daten: 0.00MB + Index: 0.00MB
wp_commentmeta: Daten: 0.15MB + Index: 0.11MB
wp_comments: Daten: 1.84MB + Index: 0.54MB
wp_cpf_custom_products: Daten: 0.00MB + Index: 0.01MB
wp_cp_feeds: Daten: 0.00MB + Index: 0.00MB
wp_cvg_gallery: Daten: 0.00MB + Index: 0.00MB
wp_cvg_videos: Daten: 0.00MB + Index: 0.00MB
wp_easymail_recipients: Daten: 0.11MB + Index: 0.15MB
wp_easymail_stats: Daten: 0.06MB + Index: 0.08MB
wp_easymail_subscribers: Daten: 0.24MB + Index: 0.12MB
wp_easymail_unsubscribed: Daten: 0.00MB + Index: 0.00MB
wp_ecp_data: Daten: 0.05MB + Index: 0.00MB
wp_ecp_options: Daten: 0.02MB + Index: 0.02MB
wp_em_bookings: Daten: 0.00MB + Index: 0.00MB
wp_em_bookings_relationships: Daten: 0.00MB + Index: 0.00MB
wp_em_coupons: Daten: 0.00MB + Index: 0.00MB
wp_em_email_queue: Daten: 0.00MB + Index: 0.00MB
wp_em_events: Daten: 0.00MB + Index: 0.01MB
wp_em_locations: Daten: 0.00MB + Index: 0.01MB
wp_em_meta: Daten: 0.00MB + Index: 0.01MB
wp_em_tickets: Daten: 0.00MB + Index: 0.00MB
wp_em_tickets_bookings: Daten: 0.00MB + Index: 0.00MB
wp_em_transactions: Daten: 0.00MB + Index: 0.00MB
wp_ewwwio_images: Daten: 5.45MB + Index: 2.47MB
wp_formmaker: Daten: 0.00MB + Index: 0.00MB
wp_formmaker_blocked: Daten: 0.02MB + Index: 0.00MB
wp_formmaker_query: Daten: 0.02MB + Index: 0.00MB
wp_formmaker_sessions: Daten: 0.00MB + Index: 0.00MB
wp_formmaker_submits: Daten: 0.00MB + Index: 0.00MB
wp_formmaker_themes: Daten: 0.55MB + Index: 0.00MB
wp_formmaker_views: Daten: 0.00MB + Index: 0.00MB
wp_huge_it_videogallery_galleries: Daten: 0.00MB + Index: 0.00MB
wp_huge_it_videogallery_videos: Daten: 0.01MB + Index: 0.00MB
wp_knewsautomated: Daten: 0.00MB + Index: 0.00MB
wp_knewsautomatedposts: Daten: 0.00MB + Index: 0.00MB
wp_knewsautomatedsel: Daten: 0.00MB + Index: 0.00MB
wp_knewsextrafields: Daten: 0.00MB + Index: 0.00MB
wp_knewskeys: Daten: 0.80MB + Index: 0.11MB
wp_knewsletters: Daten: 18.14MB + Index: 0.00MB
wp_knewslists: Daten: 0.00MB + Index: 0.00MB
wp_knewstats: Daten: 12.87MB + Index: 4.39MB
wp_knewsubmits: Daten: 0.01MB + Index: 0.00MB
wp_knewsubmitsdetails: Daten: 18.06MB + Index: 9.95MB
wp_knewsusers: Daten: 0.40MB + Index: 0.09MB
wp_knewsusersevents: Daten: 0.00MB + Index: 0.00MB
wp_knewsusersextra: Daten: 0.26MB + Index: 0.10MB
wp_knewsuserslists: Daten: 0.17MB + Index: 0.10MB
wp_layerslider: Daten: 0.55MB + Index: 0.00MB
wp_layerslider_revisions: Daten: 0.00MB + Index: 0.00MB
wp_links: Daten: 0.00MB + Index: 0.00MB
wp_maxbuttons_buttons: Daten: 0.01MB + Index: 0.00MB
wp_ngg_album: Daten: 0.00MB + Index: 0.00MB
wp_ngg_gallery: Daten: 0.00MB + Index: 0.00MB
wp_ngg_pictures: Daten: 0.15MB + Index: 0.03MB
wp_nm_convo: Daten: 0.00MB + Index: 0.00MB
wp_nm_personalized: Daten: 0.04MB + Index: 0.00MB
wp_options: Daten: 17.86MB + Index: 0.53MB
wp_phppc_functions: Daten: 0.01MB + Index: 0.00MB
wp_postmeta: Daten: 41.67MB + Index: 24.00MB
wp_posts: Daten: 8.63MB + Index: 6.93MB
wp_redirection_404: Daten: 5.17MB + Index: 1.72MB
wp_redirection_groups: Daten: 0.00MB + Index: 0.00MB
wp_redirection_items: Daten: 0.01MB + Index: 0.03MB
wp_redirection_logs: Daten: 0.07MB + Index: 0.04MB
wp_revslider_css: Daten: 0.09MB + Index: 0.00MB
wp_revslider_layer_animations: Daten: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Daten: 0.00MB + Index: 0.00MB
wp_revslider_settings: Daten: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Daten: 0.01MB + Index: 0.00MB
wp_revslider_slides: Daten: 0.00MB + Index: 0.00MB
wp_revslider_static_slides: Daten: 0.00MB + Index: 0.00MB
wp_termmeta: Daten: 0.10MB + Index: 0.05MB
wp_terms: Daten: 0.16MB + Index: 0.25MB
wp_term_relationships: Daten: 0.25MB + Index: 0.45MB
wp_term_taxonomy: Daten: 0.11MB + Index: 0.15MB
wp_ultimate: Daten: 0.00MB + Index: 0.00MB
wp_un_termmeta: Daten: 0.00MB + Index: 0.01MB
wp_UPCP_Catalogues: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_Catalogue_Items: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_Categories: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_Custom_Fields: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_Fields_Meta: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_Items: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_Item_Images: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_SubCategories: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_Tagged_Items: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_Tags: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_Tag_Groups: Daten: 0.00MB + Index: 0.00MB
wp_UPCP_Videos: Daten: 0.00MB + Index: 0.00MB
wp_userfiles: Daten: 0.00MB + Index: 0.00MB
wp_usermeta: Daten: 1.52MB + Index: 0.94MB
wp_users: Daten: 0.09MB + Index: 0.10MB
wp_wbz404_logs: Daten: 0.00MB + Index: 0.00MB
wp_wbz404_redirects: Daten: 0.00MB + Index: 0.01MB
wp_wfBadLeechers: Daten: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Daten: 0.00MB + Index: 0.00MB
wp_wfBlocks: Daten: 0.00MB + Index: 0.00MB
wp_wfBlocksAdv: Daten: 0.00MB + Index: 0.00MB
wp_wfConfig: Daten: 0.00MB + Index: 0.01MB
wp_wfCrawlers: Daten: 0.00MB + Index: 0.00MB
wp_wfFileMods: Daten: 7.59MB + Index: 1.43MB
wp_wfHits: Daten: 0.08MB + Index: 0.02MB
wp_wfHoover: Daten: 0.00MB + Index: 0.00MB
wp_wfIssues: Daten: 0.00MB + Index: 0.00MB
wp_wfLeechers: Daten: 0.01MB + Index: 0.01MB
wp_wfLockedOut: Daten: 0.00MB + Index: 0.00MB
wp_wfLocs: Daten: 0.00MB + Index: 0.00MB
wp_wfLogins: Daten: 0.00MB + Index: 0.00MB
wp_wfNet404s: Daten: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Daten: 0.00MB + Index: 0.00MB
wp_wfScanners: Daten: 0.00MB + Index: 0.00MB
wp_wfStatus: Daten: 0.11MB + Index: 0.05MB
wp_wfThrottleLog: Daten: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Daten: 0.00MB + Index: 0.00MB
wp_wplc_chat_msgs: Daten: 0.02MB + Index: 0.00MB
wp_wplc_chat_sessions: Daten: 0.02MB + Index: 0.00MB
wp_wplc_offline_messages: Daten: 0.02MB + Index: 0.00MB
wp_wplnst_scans: Daten: 0.00MB + Index: 0.02MB
wp_wplnst_scans_objects: Daten: 0.00MB + Index: 0.00MB
wp_wplnst_urls: Daten: 1.44MB + Index: 1.18MB
wp_wplnst_urls_locations: Daten: 6.92MB + Index: 3.30MB
wp_wplnst_urls_locations_att: Daten: 0.00MB + Index: 0.00MB
wp_wplnst_urls_status: Daten: 5.28MB + Index: 1.26MB
wp_wpmcleaner: Daten: 2.75MB + Index: 0.55MB
wp_wsluserscontacts: Daten: 0.00MB + Index: 0.00MB
wp_wslusersprofiles: Daten: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 2628
avada_faq: 58
display_type: 7
displayed_gallery: 7
dp_template: 19
event: 1
forum: 1
fusion_element: 37
gal_display_source: 5
lightbox_library: 7
location: 1
nav_menu_item: 108
ngg_gallery: 34
ngg_pictures: 308
options: 26
page: 143
pec-events: 93
popups: 1
post: 525
product: 515
product_variation: 1272
questions: 365
reply: 47
revision: 9
shop_coupon: 218
shop_order: 4062
shop_order_refund: 37
slide: 1
tablepress_table: 1
themefusion_elastic: 2
topic: 88
tribe_events: 879
tribe_organizer: 1
tribe_venue: 1
tt_font_control: 1
un_feedback: 1
woo_faq: 1
wysiwyg-widget: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (57) ###

404 to Start: von Jürgen Schulze – 1.6
LayerSlider WP: von Kreatura Media – 6.6.5
Antispam Bee: von pluginkollektiv – 2.7.1
bbPress: von Die bbPress-Community – 2.5.14
Better Search Replace: von Delicious Brains – 1.3.1
BNS Featured Category: von Edward Caissie – 2.8.2
Booster Plus for WooCommerce: von Algoritmika Ltd – 3.2.3 – Nicht mit der aktiven Version von WooCommerce getestet
Comment Guestbook: von mibuthu – 0.7.3
Easy Code Placement: von Jens Herdy – 17.08
Easy FancyBox: von RavanH – 1.6.2
Enable Media Replace: von Måns Jonasson – 3.1.1
Facebook for WooCommerce: von Facebook – 1.4.3 – Nicht mit der aktiven Version von WooCommerce getestet
Fusion Builder: von ThemeFusion – 1.4
Fusion Core: von ThemeFusion – 3.4
Google Analytics Dashboard for WP (GADWP): von Alin Marcu – 5.1.2.4
Google Language Translator: von Rob Myrick – 5.0.33
Google XML Sitemaps: von Arne Brachhold – 4.0.9
Image Widget: von Modern Tribe
Inc. – 4.4.7

Imsanity: von Shane Bishop – 2.3.9
Knews Pro: von Carles Reverter – 2.4.6
Linkable Title Html and Php Widget by PepLamb: von PepLamb – 1.2.6
List category posts: von Fernando Briano – 0.75.2
Media Cleaner: von Jordy Meow – 4.4.7
Media File Renamer: von Jordy Meow – 3.7.2
N-Media WooCommerce Personalized Product Meta Manager: von Najeeb Ahmad – 7.5 – Nicht mit der aktiven Version von WooCommerce getestet
Optimus: von KeyCDN – 1.4.9
Page Links To: von Mark Jaquith – 2.9.9
Polaroid Gallery: von Jani Mikkonen – 2.2
Posts in Sidebar: von Aldo Latino – 4.4.0
Redirection: von John Godley – 2.10.1
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 3.0.0
Register Plus Redux: von radiok
Tanay Lakhani – 4.2.4

Responsive FAQ Accordion: von Dennis de Groot – 1.2.2
Reviewer: von Michele Ivani – 3.17.0
Search & Replace: von Inpsyde GmbH – 3.1.2
Fast Secure Contact Form: von fastsecure – 4.0.56
The Events Calendar: von Modern Tribe
Inc. – 4.6.8

TinyMCE Advanced: von Andrew Ozz – 4.6.7
UpdraftPlus - Backup/Restore: von UpdraftPlus.Com
DavidAnderson – 1.13.16

PayPal Plus für WooCommerce: von Inpsyde GmbH – 1.0.6
WooCommerce Deutsch (de_DE): von David Decker - DECKERWEB.de – 3.2.0 – Nicht mit der aktiven Version von WooCommerce getestet
WooCommerce Direct Checkout: von Terry Tsang – 1.1.2 – Nicht mit der aktiven Version von WooCommerce getestet
WooCommerce Amazon Pay Gateway: von WooCommerce – 1.7.3 – 1.8.1 ist verfügbar – Nicht mit der aktiven Version von WooCommerce getestet
Booster for WooCommerce: von Algoritmika Ltd – 3.2.3 – Nicht mit der aktiven Version von WooCommerce getestet
WooCommerce: von Automattic – 3.2.6
WP Woocommerce to Google merchant center-pro: von asaquzzaman – 1.5 – Nicht mit der aktiven Version von WooCommerce getestet
WordPress Social Login: von Miled – 2.3.3
WP-DBManager: von Lester 'GaMerZ' Chan – 2.79.1
WP Broken Link Status Checker: von Pau Iglesias
SeedPlugins – 1.0.4

Math Captcha: von dFactory – 1.2.7
WP Rocket: von WP Media – 2.11.3
WP-Sweep: von Lester 'GaMerZ' Chan – 1.0.12
WP User Avatar: von flippercode – 2.0.9
wpSEO: von Team wpSEO – 4.4.3
Show IDs: von 99 Robots – 1.1.2
Widget Inhaltsblöcke: von Danny van Kooten – 2.3.8
YourChannel: von Plugin Builders – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #27589 - /shop/
Warenkorb: #12549 - /cart-2/
Kasse: #12553 - /checkout-2/
Mein Konto: #12551 - /mein-konto/
Geschäftsbedingungen: #4761 - /agb/

### Theme ###

Name: Avada
Version: 5.4
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child Themes. Siehe Wie du ein Child Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

`
</details>

**Comment by WPprodigy** [comment]
Please follow the full template listed when opening up an issue. 

Does this happen when just WooCommerce is activated? What about just WooCommerce and a default theme? Etc.

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried  edit pages and products, and it appeared to work correctly.

It could be on of the plugins that you are using. Probably updated more things together.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks

**Comment by chrisgeist** [comment]
hi guys, thanks a lot for the fast support. i works with another theme, so i contact the avada support team.

all the best,
chris
