### ISSUE TITLE
Authorization Error: Response for preflight has invalid HTTP status code 401

### ISSUE THREAD

**Issue by Vidit92** [woocommerce/woocommerce#18269]
The GET Method works Fine but I get 401 (Unauthorized) error when using POST Method
```
import * as WooCommerceAPI from 'woocommerce-api';
woocommerce: any;
constructor()
{
this.woocommerce = new WooCommerceAPI({
      url: 'http://bashfootwear.co.in',
      consumerKey: 'ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      consumerSecret: 'cs_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
      wpAPI: true,
      version: 'wc/v2'
    });

 var data = {
      email: 'john.doe@example.com',
      first_name: 'John',
      last_name: 'Doe',
      username: 'john.doe',
      billing: {
        first_name: 'John',
        last_name: 'Doe',
        company: '',
        address_1: '969 Market',
        address_2: '',
        city: 'San Francisco',
        state: 'CA',
        postcode: '94103',
        country: 'US',
        email: 'john.doe@example.com',
        phone: '(555) 555-5555'
      },
      shipping: {
        first_name: 'John',
        last_name: 'Doe',
        company: '',
        address_1: '969 Market',
        address_2: '',
        city: 'San Francisco',
        state: 'CA',
        postcode: '94103',
        country: 'US'
      }
    };
    
    this.woocommerce.post('customers', data, function(err, data, res) {
      console.log(res);
    });
}
```
On searching the docs and issues, it seemed to be a problem in the header, but apparently its not.
```
OPTIONS /wp-json/wc/v2/customers?oauth_consumer_key=ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&oauth_nonce=xxxxxxxxxxxxxxxxxxxxxx&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1513919904&oauth_version=1.0&oauth_signature=VcVmGSKeU3MS1PsS750vmAagoCok27SzRmUS%2FuLLiXA%3D HTTP/1.1
Host: bashfootwear.co.in
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: POST
DNT: 1
Origin: http://localhost:8100
Referer: http://localhost:8100/?ionicplatform=ios&ionicstatusbarpadding=true&http://localhost:8100/ionic-lab
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36 OPR/49.0.2725.64
X-DevTools-Emulate-Network-Conditions-Client-Id: bf7af60c-62e7-4899-a5f0-65f2ec92e17a

HTTP/1.1 401 Unauthorized
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Authorization, Content-Type
Access-Control-Allow-Methods: OPTIONS, GET, POST, PUT, PATCH, DELETE
Access-Control-Allow-Origin: http://localhost:8100
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 128
Content-Type: application/json; charset=UTF-8
Date: Fri, 22 Dec 2017 05:18:28 GMT
Link: <http://bashfootwear.co.in/wp-json></http:>; rel="https://api.w.org/"
Server: Apache
Vary: Origin, Accept-Encoding, User-Agent
X-Content-Type-Options: nosniff
X-Powered-By: PHP/7.1.7
X-Robots-Tag: noindex

```
I have also added Rewrite Rules in the .htacess
```
RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
```
Expected to get a JSON Object with the customer properties.
Whereas getting the following error:
![untitled](https://user-images.githubusercontent.com/18751223/34286486-f1d361b6-e706-11e7-9a64-b446f0cf6180.jpg)

## WordPress Environment

`
### WordPress Environment ###

Home URL: http://bashfootwear.co.in
Site URL: http://bashfootwear.co.in
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.7
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.44MB
Database Data Size: 1.09MB
Database Index Size: 0.35MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.01MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 0.62MB + Index: 0.04MB
wp_postmeta: Data: 0.09MB + Index: 0.06MB
wp_posts: Data: 0.03MB + Index: 0.02MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.01MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.01MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 6
custom_css: 1
customize_changeset: 4
page: 10
post: 3
product: 36
product_variation: 11
revision: 14

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

ManageWP - Worker: by ManageWP – 4.2.27
JWT Authentication for WP-API: by Enrique Chavez – 1.2.4
Title Remover: by WPGurus – 1.1
WooCommerce: by Automattic – 3.2.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (₹)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: ❌ Page visibility should be public
Checkout: ❌ Page visibility should be public
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by Vidit92** [comment]
I have even run the same request at [http://bettiolo.github.io/oauth-reference-page/](http://bettiolo.github.io/oauth-reference-page/)
with method : `POST` and the open the HTTP Request and got this error:

`{"code":"woocommerce_rest_authentication_error","message":"Invalid signature - provided signature does not match.","data":{"status":401}}`

**Comment by mikejolley** [comment]
Please don't log things in multiple places. https://github.com/woocommerce/wc-api-node/issues/79
