### ISSUE TITLE
JS-event 'woocommerce_variation_has_changed' has a defect when useAjax

### ISSUE THREAD

**Issue by hokoo** [woocommerce/woocommerce#18266]
Hello!
The [Line](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js#L269) about I'm speaking.

I noticed that by hooking this event there is no ability to access the value of input.variations_id.
In case ( ! useAjax ) all works fine. But in case ( useAjax ) the variation data is not available.

**Comment by claudiulodro** [comment]
Do you have a small code example of what you are trying to do? I'm not sure I understand what you are trying to do with that trigger and a code example would help.

**Comment by hokoo** [comment]
Sure
```
jQuery( 'form.variations_form' ).on( 'woocommerce_variation_has_changed', 
	function(){
		var var_id = jQuery( ".woocommerce-variation-add-to-cart input.variation_id" ).val();// undefined
	} 
);
```

**Comment by WPprodigy** [comment]
Should be able to pass `this` as the context on your selector.

**Comment by WPprodigy** [comment]
Nevermind, scratch that. Pretty sure this behavior is happening because the ajax is finishing after the `woocommerce_variation_has_changed` event is triggered.

Use `found_variation` maybe instead if ajax is in use. Example:

```
jQuery( 'form.variations_form' ).on( 'found_variation', 
	function( event, variation ){
		console.log( variation.variation_id );
	} 
);
```

**Comment by hokoo** [comment]
The `found_variation` fires early than `woocommerce_variation_has_changed` anyway. I think it's not that.

**Comment by WPprodigy** [comment]
Mmm, no that is not case when ajax is in use. http://cld.wthms.co/hLWqDM

```
jQuery( 'form.variations_form' ).on( 'found_variation', 
	function( event, variation ){
		console.log( 'found_variation' );
	} 
);

jQuery( 'form.variations_form' ).on( 'woocommerce_variation_has_changed', 
	function(){
		console.log( 'woocommerce_variation_has_changed' );
	} 
);
```

**Comment by hokoo** [comment]
It's strange.`woocommerce_variation_has_changed` should be the lastest.

**Comment by WPprodigy** [comment]
The code doesn't fire "in line", ajax makes it asynchronous.

So sure the `found_variation` event trigger is technically first if you follow just the code. But it's actually pinging the database and doing async tasks. Javascript continues to run outside of the task and `woocommerce_variation_has_changed` is fired.

**Comment by hokoo** [comment]
Ok, I understanded.
The meaning of `woocommerce_variation_has_changed` is empty in case ajax use.
So, there is also `show_variation` trigger. It is more reliably.

**Comment by mikejolley** [comment]
`show_variation` looks like a better bet 👍

**Comment by hokoo** [comment]
But the meaning of `woocommerce_variation_has_changed` is still undefined )) 
There is no reasons to use it.

**Comment by mikejolley** [comment]
It was likely added before the ajax code was implemented, but you cannot just rename or remove a hook because it breaks bw compatibility.

**Comment by hokoo** [comment]
Yes, I understand. But I think we need another one hook after [hide_variation](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js#L113) and [show_variation](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js#L247)

**Comment by mikejolley** [comment]
Why is that?

**Comment by hokoo** [comment]
For hooking by moment when finding for variations was exactly succefully finished.

**Comment by mikejolley** [comment]
But why after show_variation? That gives you the ID of the matching variation.

**Comment by hokoo** [comment]
I cant know in advance will be finded the variation or not. I hoped what `woocommerce_variation_has_changed` let me moment when finding is finished. Now I must use 2 hooks ( `hide_variation` and `show_variation` )instead one
