### ISSUE TITLE
Coupon 'Excluded Categories' restriction fails to work

### ISSUE THREAD

**Issue by jimjasson** [woocommerce/woocommerce#18271]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

In the Edit Coupon > Usage Restriction page, 'Excluded Categories' fail to work when:

- 'Exclude sale items' is enabled and

- A product from the excluded category is added in the cart and is on sale.

In order to replicate this locally, create two products:

- 'Hoodie with Pocket' which is on sale and belongs to the category 'Hoodies' and,

- 'Sunglasses' which is not on sale and belongs to the category 'Accessories'.

Then, create a Coupon with the following configuration: https://cl.ly/0K1Z0J2P0J1R

Finally, add both products to the Cart and apply the previously created coupon.

## Expected/actual behavior

The coupon is applied even though the 'Hoodies' category is excluded: https://cl.ly/3s3s0R1U1h2h

The expected behavior would be this: https://cl.ly/0w0k1k442D10

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment
The above have been tested in a fresh WordPress/WooCommerce install with no other active plugins.

PR incoming.

**Comment by franticpsyx** [comment]
Confirmed.
