### ISSUE TITLE
REST API attribute filter on Product list not working

### ISSUE THREAD

**Issue by arafat-al-mahmud** [woocommerce/woocommerce#18274]
I am using the latest API v2. While the other filters like `min_price`, `category` etc. are working, the attribute and attribute_terms query params are not filtering the result set.

I have an attribute `Color` and I am invoking the API from a node.js client as :

```
var WooCommerceAPI = require('woocommerce-api');
var WooCommerce = new WooCommerceAPI({
  url: 'http://localhost/index.php',
  consumerKey: '***',
  consumerSecret: '***',
  wpAPI: true,
  version: 'wc/v2'
});

WooCommerce.getAsync('products?attribute=pa_color').then(function(result){

        var data = JSON.parse(result.toJSON().body);
        console.log(data);
    });
```
How can I actually filter by attribute ? Tried other combinations e,g. ` attribute=Color` , `attribute=color`. Still the result isn't filtered.

**Comment by mikejolley** [comment]
See https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products for supporting arguments. You're missing `attribute_term`.

**Comment by arafat-al-mahmud** [comment]
I also used the term

**Comment by mikejolley** [comment]
You need to use both - everything supported is on that link I provided ^

**Comment by arafat-al-mahmud** [comment]
@mikejolley please have a look on my previous comment

**Comment by mikejolley** [comment]
Is color global or local to the products?

**Comment by arafat-al-mahmud** [comment]
I don't understand the difference between global or local, rather I am showing the attributes field of a product that I get from products  list query:
`
[{""id"":1,""name"":""Color"",""position"":0,""visible"":true,""variation"":false,""options"":[""Red""]}]"`

How can I tell whether it is global or local and how does it affects ?

**Comment by mikejolley** [comment]
Working example from my local:

`https://local.wordpress.test/wp-json/wc/v2/products?attribute=pa_size&attribute_term=23`

See products > Attributes for the attribute slug/term ID

**Comment by rcojoe** [comment]
A point worth adding to the wiki is that it's looking for the `slug` for the attribute and the `id` in the attribute_term.
For me, I was using 
`https://local.wordpress.test/wp-json/wc/v2/products?attribute=2&attribute_term=23`
where `2` is the id of the attribute `pa_size` which does't doesn't produce filtered results.

**Comment by arafat-al-mahmud** [comment]
Is it possible to filter products by multiple attributes ?
e.g. I want red medium shirts
products?attribute=pa_color&attribute_term=22&attribute=pa_size&attribute_term=24&

yields all products.
