### ISSUE TITLE
Incorrectly escaped HTML in report

### ISSUE THREAD

**Issue by Camwyn** [woocommerce/woocommerce#18276]
I've noticed an issue with inadvertently feeding escaping html here:
https://github.com/woocommerce/woocommerce/blob/master/includes/admin/reports/class-wc-report-sales-by-product.php#L199

this gets it's string from: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-variation.php#L115

which calls XXX here: https://github.com/woocommerce/woocommerce/blob/master/includes/wc-product-functions.php#L314

and wraps it in a span - so there is always html in there that is getting escaped.

## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue
1. load any Sales by product ex: `example.com/wp-admin/admin.php?page=wc-reports&tab=orders&report=sales_by_product&range=last_month&product_ids[0]=33262&product_ids[1]=40708`
2. Look in the left column under "Showing reports for:" (product names changed to protect the innocent 😉  )
<img width="235" alt="screen shot 2017-12-22 at 10 53 50 am" src="https://user-images.githubusercontent.com/929375/34304141-6fb0de66-e706-11e7-810c-8bee726c50b6.png">

## Expected/actual behavior
I was expecting to NOT see escaped HTML there.

## Isolating the problem
- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by claudiulodro** [comment]
Good catch. See #18277.

**Comment by jtobiesen** [comment]
Hi there! We believe we're seeing this issue again being reported by merchants and we're able to replicate it, so I've reopened this issue. If that is not the case, please let me know and I'll open up a separate issue.

In the below two cases, the issues show up when a merchant views their Shipping labels under WooComemrce > Reports > Shipping Labels

6405094-zd-woothemes
6409018-zd-woothemes

![Shipping Labels Report](https://github.com/woocommerce/woocommerce/assets/101466957/1f43a825-9a8d-48f5-b238-2b6690a30209)

It is also happening with WooCommerce > Reports > Product Vendor reports.

<img width="364" alt="Product Vendors Report" src="https://github.com/woocommerce/woocommerce/assets/101466957/28f3dd6a-7b33-4ece-b99d-244545fa6b1a">

**Comment by rrennick** [comment]
> If that is not the case, please let me know and I'll open up a separate issue.

@jtobiesen Could you create a new issue? While it's similar, it doesn't look like the same issue. I'll close this one.

**Comment by namiokuzono** [comment]
Thank you! I've created a new issue here: https://github.com/woocommerce/woocommerce/issues/38900
