### ISSUE TITLE
Order state Shipped : no mail ?

### ISSUE THREAD

**Issue by Joss47** [woocommerce/woocommerce#18273]
Hi everybody,

I just realized something logical for me and my clients.

Indeed when the order is being shipped, customers do not receive mail, so no tracking number for example.
Only in finished state they received a mail, but for many people the finished state means delivered.
Is there a possibility to add an e-mail to the Shipped step, otherwise it does not serve much in the end ...

Sorry for my english, i'm french :)

**Comment by mikejolley** [comment]
There is no shipped status. We use `completed` for that.

Processing sends a mail, and completed sends a mail. If you have a tracking number to send you can also trigger a mail by adding a customer note to the order.
