### ISSUE TITLE
Woocommerce 3.2.6 - Pagination issue (Products not evenly distributed over multiple pages)

### ISSUE THREAD

**Issue by Paulus90** [woocommerce/woocommerce#18282]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. I open a WooCommerce products page (front-end)
2. I click on a random number (mulitple pages available)
3. On some pages, there are only a few products where there should be 18 (apart from the last page obviously)

## Expected/actual behavior

When I follow those steps, I see pages with only a few products

I was expecting to see products evenly being distributed across multiple pages

*Note: I suspect this has something to do with a WooCommerce data update not being completed fully.. It took a long time for this update to finish, in fact it didn't finish automaticcally but I had to press the button that says something like 'Finish updating data right away'.*

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

WordPress omgeving
--
Home-URL: |   | http://***.mamp.nl:82
Site URL: |   | http://***.mamp.nl:82
WC-versie: |   | 3.2.6
Logmap beschrijfbaar: |   | E:\Program files\MAMP\htdocs\***/wp-content/uploads/wc-logs/
WP-versie: |   | 4.9.1
WP Multisite: |   | –
WP geheugenlimiet: |   | 256 MB
WP debug-modus: |   | –
WP Cron: |   |  
Taal: |   | nl_NL

Serveromgeving
Serverinformatie:		Apache
PHP-versie:		7.1.5
PHP post max size:		32 MB
PHP time limit:		30
PHP max input vars:		1000
cURL Versie:		7.43.0, OpenSSL/1.0.2e
SUHOSIN geïnstalleerd:		–
MySQL-versie:		5.6.34
Max upload size:		32 MB
Standaard tijdzone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		

Database
--
WC-databaseversie: |   | 3.2.6
Prefix database |   | wp_
Totale databasegrootte |   | 37.50MB
Database datagrootte |   | 26.78MB
Database index grootte |   | 10.72MB
wp_woocommerce_sessions |   | Data: 0.03MB + Index: 0.00MB
wp_woocommerce_api_keys |   | Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies |   | Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions |   | Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items |   | Data: 0.06MB + Index: 0.02MB
wp_woocommerce_order_itemmeta |   | Data: 0.20MB + Index: 0.23MB
wp_woocommerce_tax_rates |   | Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations |   | Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log |   | Data: 0.00MB + Index: 0.00MB
wp_aiowps_events |   | Data: 0.00MB + Index: 0.00MB
wp_aiowps_failed_logins |   | Data: 0.00MB + Index: 0.00MB
wp_aiowps_global_meta |   | Data: 0.00MB + Index: 0.00MB
wp_aiowps_login_activity |   | Data: 0.00MB + Index: 0.00MB
wp_aiowps_login_lockdown |   | Data: 0.00MB + Index: 0.00MB
wp_aiowps_permanent_block |   | Data: 0.00MB + Index: 0.00MB
wp_commentmeta |   | Data: 0.02MB + Index: 0.03MB
wp_comments |   | Data: 0.17MB + Index: 0.16MB
wp_duplicator_pro_entities |   | Data: 0.01MB + Index: 0.00MB
wp_duplicator_pro_packages |   | Data: 0.00MB + Index: 0.00MB
wp_links |   | Data: 0.02MB + Index: 0.02MB
wp_options |   | Data: 5.45MB + Index: 1.20MB
wp_popover |   | Data: 0.02MB + Index: 0.00MB
wp_popover_ip_cache |   | Data: 0.02MB + Index: 0.02MB
wp_postmeta |   | Data: 6.52MB + Index: 5.03MB
wp_posts |   | Data: 8.52MB + Index: 0.89MB
wp_termmeta |   | Data: 0.02MB + Index: 0.02MB
wp_terms |   | Data: 0.08MB + Index: 0.09MB
wp_term_relationships |   | Data: 0.31MB + Index: 0.27MB
wp_term_taxonomy |   | Data: 0.08MB + Index: 0.11MB
wp_usermeta |   | Data: 0.06MB + Index: 0.03MB
wp_users |   | Data: 0.02MB + Index: 0.05MB
wp_wfbadleechers |   | Data: 0.00MB + Index: 0.00MB
wp_wfblockediplog |   | Data: 0.00MB + Index: 0.00MB
wp_wfblocks |   | Data: 0.02MB + Index: 0.01MB
wp_wfblocksadv |   | Data: 0.00MB + Index: 0.00MB
wp_wfconfig |   | Data: 0.03MB + Index: 0.01MB
wp_wfcrawlers |   | Data: 0.03MB + Index: 0.02MB
wp_wffilemods |   | Data: 2.07MB + Index: 0.54MB
wp_wfhoover |   | Data: 0.00MB + Index: 0.00MB
wp_wfissues |   | Data: 0.01MB + Index: 0.00MB
wp_wflockedout |   | Data: 0.02MB + Index: 0.00MB
wp_wflocs |   | Data: 0.02MB + Index: 0.01MB
wp_wflogins |   | Data: 0.30MB + Index: 0.07MB
wp_wfnet404s |   | Data: 2.22MB + Index: 1.33MB
wp_wfreversecache |   | Data: 0.04MB + Index: 0.01MB
wp_wfscanners |   | Data: 0.24MB + Index: 0.30MB
wp_wfstatus |   | Data: 0.07MB + Index: 0.04MB
wp_wfthrottlelog |   | Data: 0.00MB + Index: 0.00MB
wp_wfvulnscanners |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_multisafepay |   | Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links |   | Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_meta |   | Data: 0.00MB + Index: 0.00MB

Post type aantal
--
attachment |   | 1883
ml-slide |   | 6
ml-slider |   | 1
nav_menu_item |   | 7
optionsframework |   | 2
page |   | 22
portfolio |   | 246
post |   | 243
product |   | 360
product_variation |   | 149
revision |   | 1547
shop_order |   | 190
shop_order_refund |   | 1
wooframework |   | 56
wpcf7_contact_form |   | 2

Beveiliging
Beveiligde verbinding (HTTPS):		Jouw winkel gebruikt geen HTTPS. Leer meer over HTTPS en SSL-certificaten.
Verberg fouten voor bezoekers		

Actieve plugins (30)
--
WooCommerce (nl) |   | door Pronamic – 1.1.7 – Niet getest met de actieve versie van WooCommerce
All In One WP Security |   | door Tips and Tricks HQ, Peter Petreski, Ruhul, Ivy – 4.3.1
Yoast Breadcrumbs |   | door Joost de Valk – 0.8.5
Contact Form 7 Honeypot |   | door Nocean – 1.12
Contact Form 7 |   | door Takayuki Miyoshi – 4.9.2
Cookie Notice |   | door dFactory – 1.2.40
Disable XML-RPC Pingback |   | door Samuel Aguilera – 1.1
Duplicator Pro |   | door Snap Creek – 3.5.4.2
Google Analytics Dashboard for WP (GADWP) |   | door Alin Marcu – 5.1.2.5
Meta Slider |   | door Matcha Labs – 3.5
Multisafepay |   | door Multisafepay – 2.2.3
Multisafepay iDEAL |   | door Multisafepay – 2.2.3
Nimble Portfolio |   | door Nimble3 – 3.0.1
Plugins Garbage Collector |   | door Vladimir Garagulya – 0.10.3
Really Simple CAPTCHA |   | door Takayuki Miyoshi – 2.0.1
Regenerate Thumbnails |   | door Alex Mills (Viper007Bond) – 3.0.1
Maintenance Mode & Coming Soon |   | door Maintenance Mode Builder – 3.8.1
Royal Custom CSS for Page and Post |   | door SM Mehdi Akram – 1.2
WooCommerce Table Rate Shipping by Mangohour |   | door mangohour – 1.2.1 – Niet getest met de actieve versie van WooCommerce
TargetPay for Woocommerce |   | door Yellow Melon B.V. – 1.0 – Niet getest met de actieve versie van WooCommerce
Tawk.to Live Chat |   | door Tawkto – 0.3.4
WooCommerce Menu Cart |   | door Jeremiah Prummer, Ewout Fernhout – 2.6.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce MyParcel |   | door Ewout Fernhout – 2.4.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Pay for Payment |   | door Karolína Vyskočilová – 2.0.6 – Niet getest met de actieve versie van WooCommerce
WooCommerce Product Image Flipper |   | door jameskoster – 0.4.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce |   | door Automattic – 3.2.6
Yoast SEO |   | door Team Yoast – 6.0
WP Super Cache |   | door Automattic – 1.5.9
YITH Infinite Scrolling |   | door YITHEMES – 1.0.8
YITH WooCommerce Ajax Product Filter |   | door YITHEMES – 3.4.6 – Niet getest met de actieve versie van WooCommerce

Instellingen
--
API geactiveerd: |   |  
Forceer SSL: |   | –
Valuta |   | EUR (€)
Positie van valutasymbool |   | left
Duizendtalscheiding |   | .
Decimaalscheiding |   | ,
Aantal decimalen |   | 2
Taxonomieën: Producttypen |   | external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomieën: productzichtbaarheid |   | exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)

WC pagina's
--
Winkelbasis: |   | #1737 - /indusigns-shop/
Winkelmand: |   | #5 - /winkelwagen/
Afrekenen: |   | #6 - /afrekenen/
Mijn account: |   | #7 - /mijn-account/
Algemene voorwaarden: |   | #437 - /algemene-voorwaarden/

Thema
Naam:		Twenty Seventeen
Versie:		1.4
URL van de maker:		https://nl.wordpress.org/
Subthema:		 – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt, raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema
WooCommerce Support:		

</details>

**Comment by vdrnn** [comment]
@Paulus90 Are you sure that the products are only not distributed correctly or are some products missing? I have a similar issue after a lot of debugging, I found out that a couple of products are not shown in the loop and that's why I get the gaps on the pages with pagination.

**Comment by mikejolley** [comment]
> Note: I suspect this has something to do with a WooCommerce data update not being completed fully.. It took a long time for this update to finish, in fact it didn't finish automaticcally but I had to press the button that says something like 'Finish updating data right away'.

It will be this. I suspect out of stock products are 'hidden' but not being queried out due to missing terms. 

Run this again https://gist.github.com/mikejolley/dff162f36b2be5f597fc0c55f5c3c47f You can also turn off the 'hide out of stock products' option to prevent the gaps, or save the affected hidden products again so they are updated.
