### ISSUE TITLE
API not saving hebrew named product variation attributes

### ISSUE THREAD

**Issue by pmogollons** [woocommerce/woocommerce#18288]
Hi,

We are having an issue with the woocommerce api, we are using the node SDK and when saving a variation of a product with an attribute name that is in hebrew it fails to save the attribute to the variation but the response of the api server is 200 ok.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an attribute that has a hebrew name (Ej: בן-בת)
2. Add options to the new attribute (can be english or hebrew, it works with both)
3. Add this new attribute to the product
4. Create a variation for this product
4. Select a default value for the hebrew named attribute
5. Save

## Expected/actual behavior
When using a hebrew name, the api responds with a 200 ok response, but the attribute is not saved to that variation. If I change the attribute name to english it works correctly and the attribute is saved to the variation.

<img width="531" alt="screen shot 2017-12-26 at 4 40 54 pm" src="https://user-images.githubusercontent.com/32210050/34358990-21d07134-ea5d-11e7-86ef-6b59cd4656cc.png">
Here you can see how the request includes 4 attributes but the response sends back only the 3 that have english names.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/) This happens using the api
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
### WordPress Environment ###

Home URL: http://best-flowers.growsite.co.il
Site URL: http://best-flowers.growsite.co.il
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 7.0.22-0ubuntu0.16.04.1
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.20
Max Upload Size: 30 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 48.29MB
Database Data Size: 45.30MB
Database Index Size: 2.99MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.17MB + Index: 0.05MB
wp_postmeta: Data: 36.08MB + Index: 1.94MB
wp_posts: Data: 6.47MB + Index: 0.31MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.06MB + Index: 0.03MB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_tinvwl_items: Data: 0.02MB + Index: 0.00MB
wp_tinvwl_lists: Data: 0.02MB + Index: 0.00MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 325
custom_css: 1
custom-css-js: 19
customize_changeset: 135
elementor_library: 13
foogallery: 2
nav_menu_item: 44
oceanwp_library: 1
page: 16
post: 5
product: 123
product_variation: 43
revision: 778
shop_order: 3
sln_attendant: 2
sln_booking: 14
sln_service: 3

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (31) ###

Cognito Forms: by Cognito Apps – 1.1.7
Simple Custom CSS and JS: by Diana Burduja – 3.10
Custom Facebook Feed Pro Developer: by Smash Balloon – 3.0.7
Duplicate Page: by mndpsingh287 – 2.4
Elementor Pro: by Elementor.com – 1.12.0
Elementor: by Elementor.com – 1.8.11
English WordPress Admin: by khromov – 1.5.1
FooGallery: by FooPlugins – 1.4.12
GitHub Updater: by Andy Fragen – 7.4.4
Loco Translate: by Tim Whitlock – 2.0.17
VarkTech Minimum Purchase for WooCommerce: by Vark – 1.09.81 – Not tested with the active version of WooCommerce
Salon Booking with two way sync: by GrowApp – 3.15.6
Ocean Demo Import: by OceanWP – 1.0.7
Ocean Elementor Widgets: by OceanWP – 1.0.12
Ocean Extra: by OceanWP – 1.3.10
Ocean Hooks: by OceanWP – 1.0.2
Ocean Modal Window: by OceanWP – 1.0.12
Ocean Portfolio: by OceanWP – 1.0.7
Ocean Posts Slider: by OceanWP – 1.0.9
Ocean Social Sharing: by OceanWP – 1.0.8
Ocean Sticky Header: by OceanWP – 1.1.4
Ocean Woo Popup: by OceanWP – 1.0.3
Press Elements - Widgets for Elementor: by Press Elements – 1.7.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.0
Responsive Lightbox: by dFactory – 1.7.2
WooCommerce Wishlist Plugin: by TemplateInvaders – 1.5.13 – Not tested with the active version of WooCommerce
WooCommerce Variation Swatches: by ThemeAlien – 1.0.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.6
WordPress Importer: by wordpressdotorg – 0.6.3
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WPB WooCommerce Product slider: by wpbean – 2.0.6.2 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #926 - /terms/

### Theme ###

Name: OceanWP
Version: 1.4.10
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/checkout/form-coupon.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/loop/pagination.php
oceanwp/woocommerce/single-product/title.php

### TI WooCommerce Wishlist Templates ###

Overrides: –
</details>

Thanks in advance.

**Comment by ivan133** [comment]
I confirm it too.
Basically I do PUT to  /wp-json/wc/v2/products/259/variations/417 
for English name attributes are saved, for other not.

**Comment by ivan133** [comment]
I was able to hack it like this:

```
      variation.attributes.forEach((attribute) => {
        if (encodeURIComponent(attribute.name) != attribute.name){
          attribute.name = 'pa_' +  attribute.name;
          delete attribute.id;
        }
      });

```
So if attribute name in not in ASCI I delete id and add pa_ to attribute name.

And when I get response I have to "decode it":

```
      product.variations.forEach(( variation ) => {
        variation.attributes.forEach(( attribute ) => {
          attribute['option'] = decodeURIComponent(attribute['option']);
        });
      });

```

It's JS code, but I think the idea is clear.
Isn't there a better way to do it?

**Comment by mikejolley** [comment]
@claudiosanches can you review?
