### ISSUE TITLE
Is there any use of this code?

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#18286]
I have tested without this code and all works great :)
https://github.com/woocommerce/woocommerce/blob/eb60a17818706a156efbc99e3c330bb38b569df7/includes/admin/class-wc-admin-menus.php#L135-L154

CC @mikejolley

**Comment by mikejolley** [comment]
Go to products > attributes then edit an attribute. Sub menu highlight is lost without this code.
