### ISSUE TITLE
Unable to edit BACS fields in mobile

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#18287]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. From a laptop/desktop device, add an "Account Details" row to the BACS configuration - something like this: 
![see screen shot](http://cld.wthms.co/pNqfNc+)
2. From a mobile device, attempt to make an edit to any of those fields

## Expected/actual behavior

When I follow those steps, I see that I am unable to make any changes to those fields

I was expecting to see a way to make changes to those fields

FWIW there is a similar issue in #17761 but that is more about design than functionality.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://wctesting.club
Site URL: https://wctesting.club
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.22-0ubuntu0.16.04.1
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: wctesting_
Total Database Size: 27.59MB
Database Data Size: 17.30MB
Database Index Size: 10.29MB
wctesting_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB
wctesting_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wctesting_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wctesting_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wctesting_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wctesting_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wctesting_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wctesting_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wctesting_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wctesting_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wctesting_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wctesting_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wctesting_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wctesting_woocommerce_log: Data: 0.02MB + Index: 0.02MB
640150_commentmeta: Data: 0.02MB + Index: 0.03MB
640150_comments: Data: 0.02MB + Index: 0.08MB
640150_links: Data: 0.02MB + Index: 0.02MB
640150_options: Data: 1.39MB + Index: 0.02MB
640150_postmeta: Data: 7.52MB + Index: 7.03MB
640150_posts: Data: 1.52MB + Index: 0.61MB
640150_termmeta: Data: 0.02MB + Index: 0.03MB
640150_terms: Data: 0.02MB + Index: 0.03MB
640150_term_relationships: Data: 0.14MB + Index: 0.08MB
640150_term_taxonomy: Data: 0.02MB + Index: 0.03MB
640150_usermeta: Data: 0.02MB + Index: 0.03MB
640150_users: Data: 0.02MB + Index: 0.05MB
640150_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
640150_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
640150_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
640150_woocommerce_log: Data: 0.02MB + Index: 0.02MB
640150_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
640150_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
640150_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
640150_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
640150_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
640150_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
640150_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
640150_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
640150_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
640150_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
770730_commentmeta: Data: 0.06MB + Index: 0.03MB
770730_comments: Data: 0.02MB + Index: 0.09MB
770730_links: Data: 0.02MB + Index: 0.02MB
770730_options: Data: 1.39MB + Index: 0.05MB
770730_postmeta: Data: 0.16MB + Index: 0.09MB
770730_posts: Data: 0.06MB + Index: 0.06MB
770730_termmeta: Data: 0.02MB + Index: 0.03MB
770730_terms: Data: 0.02MB + Index: 0.03MB
770730_term_relationships: Data: 0.02MB + Index: 0.02MB
770730_term_taxonomy: Data: 0.02MB + Index: 0.03MB
770730_usermeta: Data: 0.02MB + Index: 0.03MB
770730_users: Data: 0.02MB + Index: 0.05MB
770730_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
770730_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
770730_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
770730_woocommerce_log: Data: 0.02MB + Index: 0.02MB
770730_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
770730_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
770730_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
770730_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
770730_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
770730_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
770730_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
770730_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
770730_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
770730_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
770730_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
770730_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB
wctesting_commentmeta: Data: 0.06MB + Index: 0.03MB
wctesting_comments: Data: 0.02MB + Index: 0.09MB
wctesting_links: Data: 0.02MB + Index: 0.02MB
wctesting_options: Data: 3.03MB + Index: 0.05MB
wctesting_postmeta: Data: 0.19MB + Index: 0.13MB
wctesting_posts: Data: 0.31MB + Index: 0.06MB
wctesting_termmeta: Data: 0.02MB + Index: 0.03MB
wctesting_terms: Data: 0.02MB + Index: 0.03MB
wctesting_term_relationships: Data: 0.02MB + Index: 0.02MB
wctesting_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wctesting_usermeta: Data: 0.02MB + Index: 0.03MB
wctesting_users: Data: 0.02MB + Index: 0.05MB
wctesting_wc_download_log: Data: 0.02MB + Index: 0.03MB
wctesting_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 51
et_pb_layout: 33
jetpack_migration: 2
page: 7
post: 2
product: 24
product_variation: 4
revision: 5
shop_order: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Jetpack by WordPress.com: by Automattic – 5.6.1
WooCommerce PayPal Adaptive Payments: by WooThemes – 1.1.5 – Not tested with the active version of WooCommerce
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.0
WooCommerce Stripe Gateway: by WooCommerce – 3.2.3 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.9.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.0-beta.1
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /?page_id=4
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My account: #7 - /?page_id=7
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by claudiulodro** [comment]
See #18349
