### ISSUE TITLE
Stock Management Occurs Before Customer Sees Confirmation

### ISSUE THREAD

**Issue by mile6-anthony** [woocommerce/woocommerce#18281]
We have a client running WC and have run into an issue where we are experiencing duplicate orders that are, ultimately, due to user error. The checkout process attempts to set the timeout to 0 (unlimited), but we use mod_fcgid and that doesn't work.

At first, orders were hitting the timeout at 40 seconds. We bumped it up to 90 until we could look into it and found that it takes about several seconds per product in the cart to manage inventory... while the customer sits there waiting for confirmation.

A customer clicks "place order", the screen is disabled... and they wait. If they hit the timeout, they ultimately retry the order (first source of duplicates), or, after sitting for up to a minute (or more), they think something is wrong and refresh to try again (second source of duplicates).

I would submit that no user should have to sit and wait while we cleanup inventory. That routine not only adjusts inventory, but dispatches low/out-of-stock emails, including whatever any other plugin has hooked in before the user is finally redirected at the end of WC_Checkout->process_checkout();

Inventory management should not be hooked in WC_Order->payment_complete() because the user is sitting there waiting for confirmation.

There needs to be a mechanism to facilitate hooks prior to redirect and after direct before die() or wp_die(). The reason I haven't submitted a pull request is because I am not entirely familiar with the "WooCommerce" way. The method WC_Checkout->process_checkout() calls one of two payment processing methods which both either send the response via ajax or just does the redirect. A hook could be added after the non-ajax request, but the ajax request uses wp_send_json() which has it's own call to wp_die().

The WC package could include their own json_send and redirect functions that provide a hook just after the redirect but before die()... or there could be a redirect with no die() placed somewhere after routines only necessary for payment collection and order storage. The former, I think, would be the most backward compatible... the redirect would stay where it is, and the hook in wc-stock-functions.php ( add_action( 'woocommerce_payment_complete', 'wc_maybe_reduce_stock_levels' ); ) could be moved to the hook that executes after the user is redirected.

So, something like:
1. Payment complete
2. Misc essential tasks
3. Hook: woocommerce_payment_complete
4. Redirect and show confirmation
4. Create a post-redirect hook that the wc_maybe_reduce_stock_levels() can be added to.

## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue
On mod_fcgid (where the timeout adjustment fails):
1. Enable order management.
2. Place an order with one item
3. Place an order with twenty items
4. Observe that the end user waits longer directly proportional to the number of items needing inventory adjustment.

Here is a screenshot of an order with one item: ( http://cld.mile6.net/1Y2q140F042Y ). 4 seconds to manage inventory.

Here is a screenshot of an order with nine items: ( http://cld.mile6.net/2C1h101R0J3V ). 41 seconds to manage inventory (actual order time was 63 seconds).

## Isolating the problem
- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

Home URL: ---------
Site URL: -----------
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.15
PHP Version: 5.6.25
PHP Post Max Size: 518 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.1.73 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 689.37MB
Database Data Size: 492.47MB
Database Index Size: 196.90MB
wp_woocommerce_sessions: Data: 35.05MB + Index: 1.02MB
wp_woocommerce_api_keys: Data: 1.08MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB
wp_woocommerce_order_itemmeta: Data: 22.56MB + Index: 21.06MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
k_COM_Customer: Data: 4.52MB + Index: 1.52MB
k_orderid2wcid: Data: 0.02MB + Index: 0.02MB
k_skuid2wcid: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.16MB + Index: 0.17MB
wp_comments: Data: 10.52MB + Index: 10.09MB
wp_et_divi_ab_testing_clients: Data: 0.02MB + Index: 0.00MB
wp_et_divi_ab_testing_stats: Data: 0.02MB + Index: 0.00MB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 134.30MB + Index: 12.81MB
wp_postmeta: Data: 67.61MB + Index: 83.03MB
wp_posts: Data: 32.52MB + Index: 6.89MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.11MB + Index: 0.00MB
wp_rg_form_view: Data: 0.06MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 2.52MB + Index: 0.39MB
wp_rg_lead_detail: Data: 9.52MB + Index: 19.02MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.08MB + Index: 0.09MB
wp_terms: Data: 0.06MB + Index: 0.03MB
wp_term_relationships: Data: 0.17MB + Index: 0.11MB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wp_usermeta: Data: 164.11MB + Index: 34.05MB
wp_users: Data: 2.52MB + Index: 4.53MB

### Post Type Counts ###

acf-field: 17
acf-field-group: 4
attachment: 726
custom_css: 1
et_pb_layout: 35
nav_menu_item: 82
page: 52
post: 106
product: 276
product_variation: 169
revision: 2178
shop_coupon: 7
shop_order: 19301
shop_order_refund: 4
sidebar: 1
vc_grid_item: 2
wafs: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Advanced Access Manager: by Vasyl Martyniuk  – 5.0.1
Advanced Custom Fields PRO: by Elliot Condon – 5.6.7
Gravity Forms: by rocketgenius – 2.2.5
Gravity Forms Dropbox Add-On: by rocketgenius – 2.0
Gravity Forms Survey Add-On: by Rocketgenius – 3.2
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.5
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.3.1
UPS WooCommerce Shipping: by Xadapter – 3.8.11 – Not tested with the active version of WooCommerce
WC Password Strength Settings: by Daniel Santoro – 2.0.1
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.3
WooCommerce Authorize.Net AIM Gateway: by SkyVerge – 3.12.1 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce USPS Shipping: by WooCommerce – 4.4.11
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.18 – 4.1.19 is available – Not tested with the active version of WooCommerce
WooCommerce Shop as Customer: by cxThemes – 2.12 – Not tested with the active version of WooCommerce
Woocommerce Simple Storewide Sale: by Wpgenie – 1.1 – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by WooCommerce – 3.3.8 – Not tested with the active version of WooCommerce
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.5
WooCommerce: by Automattic – 3.2.6

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-1 (rated-1-3)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3620 - /store/grid/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #3869 - /account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: -----------------------
Version: 1.0.0
Author URL: https://mile6.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: ---/woocommerce/archive-product.php
---/woocommerce/cart/cart.php version 3.0.0 is out of date. The core version is 3.1.0
---/woocommerce/checkout/form-billing.php
---/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
---/woocommerce/global/breadcrumb.php
---/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.2.0
---/woocommerce/global/sidebar.php
---/woocommerce/loop/add-to-cart.php
---/woocommerce/loop/loop-end.php
---/woocommerce/loop/loop-start.php
---/woocommerce/loop/orderby.php
---/woocommerce/loop/pagination.php
---/woocommerce/loop/price.php
---/woocommerce/single-product/add-to-cart/external.php
---/woocommerce/single-product/add-to-cart/grouped.php version 3.0.0 is out of date. The core version is 3.0.7
---/woocommerce/single-product/add-to-cart/simple.php
---/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
---/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
---/woocommerce/single-product/add-to-cart/variation.php
---/woocommerce/single-product/price.php
---/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.1.0
---/woocommerce/single-product/product-image.php version 3.0.0 is out of date. The core version is 3.1.0
---/woocommerce/single-product/short-description.php
---/woocommerce/single-product/tabs/additional-information.php
---/woocommerce/single-product/tabs/description.php
---/woocommerce/single-product/tabs/tabs.php
---/woocommerce/single-product/title.php
---/woocommerce/single-product.php
---/woocommerce/taxonomy-product_cat.php

Outdated Templates: ❌Learn how to update

### Authorize.Net AIM Emulation ###

Environment: Production
Debug Mode: Off
</details>

**Comment by mikejolley** [comment]
Could be helped by offsetting email sending - adjust https://gist.github.com/mikejolley/16ca078f5c74b401e6ba210644e3173d to __return_true.

40 seconds to reduce stock however sounds ludicrous. There must be other code on your install slowing these processes down? We have a fairly large/busy store on WooCommerce.com and it takes no where near that to place an order.

Ultimately, this would be improved with https://github.com/woocommerce/woocommerce/issues/16971 so this already has an open issue. Your suggestion could be a short term solution however.

If you wanted to attempt a PR, you could experiment with sending the JSON response followed by https://github.com/woocommerce/woocommerce/blob/fd2c67683765df96dd71e0dbcb60d3e9063d6f20/includes/admin/class-wc-admin-setup-wizard.php#L545-L555 before running other logic, however, I would take care to ensure stock management *is* done first since if that fails for any reason, the order should not go through. Happy to review anything you send through.

Thanks
