### ISSUE TITLE
Method order_again() does not copy WooCommerce Products Add-ons data

### ISSUE THREAD

**Issue by 7bZAumHXtkgGG56MYAL** [woocommerce/woocommerce#18290]
I'm not sure if it's because of *WooCommerce Products Add-ons* logic that does not follow WooCommerce's variation/metadata logic. All I can say is that when cloning an order using the method `order_again()`, the items with the standard variation are transferred; however any item with global add-ons data will be displayed as a simple item with inaccurate price.

To reproduce the bug:

1. Create a global add-on with a few fields (simple text ones and/or price ones)
2. Order an item with these fields completed
3. Clone the completed order with @claudiosanches ' [snippet](https://gist.github.com/claudiosanches/357fec20ff4802e259d4)

**The expected result is the exact order items and prices**

**The actual result is an incomplete order (no add-on data) with potentially lower price (if there are price add-on fields )**

**Comment by mikejolley** [comment]
I've moved this to the addons repo for investigation https://github.com/woocommerce/woocommerce-product-addons/issues/306

**Comment by 7bZAumHXtkgGG56MYAL** [comment]
@mikejolley is it possible to know if the ticket woocommerce/woocommerce-product-addons#306 was ever updated? It seems to be a private repo.
And the logs don't seem to show any update on that:
http://changelogs.s3.amazonaws.com/changelogs/woocommerce-composite-products/changelog.txt

Thanks
