### ISSUE TITLE
% is no longer accepted in discount coupon code

### ISSUE THREAD

**Issue by ServeUdotNet** [woocommerce/woocommerce#18295]
Since 3.2.6, the %-sign is no longer accepted in new discount codes. It worked fine before the update. Formerly created discount codes including %-sign still works, but if I try to create a new discount code, the %-sign is stripped.

**Comment by Phiph** [comment]
What coupon code are you entering so that the community can recreate your scenario.

**Comment by ServeUdotNet** [comment]
Code:
jonas10%28feb

**Comment by dougaitken** [comment]
@ServeUdotNet can you confirm using which version of WooCommerce this was working for?

The coupon code is created, but when it is added to the coupon field at cart/checkout, it is "stripped". The reason (I believe) for this is that `%28` is URL `(` so my guess is there is a strong reason for doing that.

The flip side - is there a reason you need `%` in your coupons?

**Comment by Phiph** [comment]
Exactly my thoughts when a percent sign was being stripped!

**Comment by mikejolley** [comment]
All coupon codes are formatted and standardized. % entities are stripped. This can be controlled by filters if needed https://github.com/woocommerce/woocommerce/blob/1d132b8b9d8c41fdc77d9d2243c5a49794ee41a5/includes/wc-core-functions.php#L38-L40

This is not since 3.2.6 though. 3.0+

**Comment by ServeUdotNet** [comment]
@dougaitken % could be used in version 3.2.5

**Comment by mikejolley** [comment]
% is stripped from display in 3.2.5.
