### ISSUE TITLE
Price in order

### ISSUE THREAD

**Issue by Bapt27** [woocommerce/woocommerce#18294]
Hello, 

Theme used  : adforest classifieds ads
Woocommerce version : Latest version 3.2.6
Wordpress version : latest version 4.9.1

On the order page, just before filling out the billing information, the price quoted for the subtotal and total is offset. I would like the currency to appear at the same level as the number. (like this = 6€. Not like in picture)

Screenshot : https://zupimages.net/up/17/52/x0x0.jpg

How to do to fix it ? 

I remain at your disposal if necessary.

Thank for your help.

**Comment by Phiph** [comment]
This may be be a CSS issue on your theme, I'd advise playing around with the CSS for the currency notation.

**Comment by Bapt27** [comment]
Ok. Thank you for your help ! 

Have a good day. :-)
