### ISSUE TITLE
Variation Inventory Update issue

### ISSUE THREAD

**Issue by arazvi** [woocommerce/woocommerce#18292]
Hi!

There seems to be an issue with managing the inventory for Variations.. I have 14 products and some 40+ variations among them.. now if any order is placed for any variation, the stock gets reduced to 0, status changes to: "Out of Stock" in the WP Products Dashboard. However, the front store still shows the product "In Stock" and quantity can be selected to any number... this is until you click "Add to Cart" then a message appears: "Sorry the requested quantity is not available. 0 items remaining:

Site URL: Seedoos.com

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
`
### WordPress Environment ###

Home URL: http://seedoos.com
Site URL: http://seedoos.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.11
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (22) ###

Redux Framework: by Team Redux – 3.6.5
BackUpWordPress: by Human Made Limited – 3.6.4
Bingo Framework: by BingoTheme – 1.0
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.7

Contact Form 7: by Takayuki Miyoshi – 4.8.1
Flexible Shipping: by WP Desk – 1.9.12
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.2
Minimal Coming Soon & Maintenance Mode: by WebFactory – 1.45
Multi Step Form: by Mondula GmbH – 1.2.0
NC Size Chart for Woocommerce: by Nabaraj Chapagain – 1.0.6
Slider Revolution: by ThemePunch – 5.4.5.1
Smart Variations Images: by David Rosendo – 3.2.17
WooCommerce Email Customizer: by cxThemes – 3.12
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.4.2
WooCommerce - Store Toolkit: by Visser Labs – 1.7.5
WooCommerce: by Automattic – 3.1.1 – 3.2.6 is available
WP Maintenance Mode: by Designmodo – 2.0.9
WP Super Cache: by Automattic – 1.5.9
MailPoet 2: by MailPoet – 2.7.11.3
YITH WooCommerce Compare: by YITHEMES – 2.2.1
YITH WooCommerce Quick View: by YITHEMES – 1.2.1
YITH WooCommerce Wishlist: by YITHEMES – 2.1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AED (AED)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #16 - /shop/
Cart: #17 - /cart/
Checkout: #18 - /checkout/
My account: #19 - /my-account/

### Theme ###

Name: Simolux
Version: 1.0.0
Author URL: http://bingotheme.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: simolux/woocommerce/archive-product.php
simolux/woocommerce/cart/cross-sells.php
simolux/woocommerce/cart/mini-cart.php
simolux/woocommerce/checkout/form-checkout.php
simolux/woocommerce/checkout/thankyou.php
simolux/woocommerce/content-product.php
simolux/woocommerce/content-single-product.php
simolux/woocommerce/global/quantity-input.php
simolux/woocommerce/loop/add-to-cart.php
simolux/woocommerce/loop/loop-end.php
simolux/woocommerce/loop/loop-start.php
simolux/woocommerce/loop/no-products-found.php
simolux/woocommerce/loop/orderby.php
simolux/woocommerce/loop/pagination.php
simolux/woocommerce/loop/price.php
simolux/woocommerce/loop/rating.php
simolux/woocommerce/loop/result-count.php
simolux/woocommerce/loop/sale-flash.php
simolux/woocommerce/myaccount/form-edit-account.php
simolux/woocommerce/myaccount/form-edit-address.php
simolux/woocommerce/myaccount/form-login.php
simolux/woocommerce/myaccount/form-lost-password.php
simolux/woocommerce/myaccount/my-address.php
simolux/woocommerce/myaccount/my-downloads.php
simolux/woocommerce/myaccount/my-orders.php
simolux/woocommerce/myaccount/orders.php
simolux/woocommerce/single-product/add-to-cart/external.php
simolux/woocommerce/single-product/add-to-cart/grouped.php
simolux/woocommerce/single-product/add-to-cart/simple.php
simolux/woocommerce/single-product/add-to-cart/variable.php
simolux/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
simolux/woocommerce/single-product/add-to-cart/variation.php
simolux/woocommerce/single-product/meta.php
simolux/woocommerce/single-product/price.php
simolux/woocommerce/single-product/product-attributes.php
simolux/woocommerce/single-product/product-image.php
simolux/woocommerce/single-product/product-thumbnails.php
simolux/woocommerce/single-product/rating.php
simolux/woocommerce/single-product/related.php
simolux/woocommerce/single-product/review.php
simolux/woocommerce/single-product/sale-flash.php
simolux/woocommerce/single-product/share.php
simolux/woocommerce/single-product/short-description.php
simolux/woocommerce/single-product/tabs/additional-information.php
simolux/woocommerce/single-product/tabs/description.php
simolux/woocommerce/single-product/tabs/tabs.php
simolux/woocommerce/single-product/title.php
simolux/woocommerce/single-product/up-sells.php
simolux/woocommerce/single-product-reviews.php
simolux/woocommerce/single-product.php

### Templates ###

thumbnail: 
medium: 
medium_large: 
large: 
wysija-newsletters-max: 
yith-woocompare-image: 
shop_thumbnail: 
shop_catalog: 
shop_single: 
post-thumbnail: 
simolux-full-width:

**Comment by GlennMartin1** [comment]
You're running WC 3.1.1?

WooCommerce supports only the latest version, which is 3.2.6.

**Comment by arazvi** [comment]
Yes. 3.1.1

Do i update? Will it run it into any issues?

What version should I update to?

**Comment by GlennMartin1** [comment]
Make your updates on a staging site. 

WordPress should be updated to 4.9.1. 
WooCommerce should be updated to 3.2.6.

All your other plugins should be updated to their latest version. 

Update your theme to its latest version. 

Disable any unused or unnecessary plugins. 

If everything works on a staging site, then make that staging site live. 

Always backup before making changes. 

When complete, check if this issue persists.
