### ISSUE TITLE
Stock can not be deleted

### ISSUE THREAD

**Issue by KlarissaM** [woocommerce/woocommerce#18301]
Hi
I dont know, what to do whit this problem.

In the stock list I have some items that are zero. I can not see what it's for goods and I can not delete them.
When i click at the pencil, to edit product, I get this message:
You attempted to edit a post that does not exist. Maybe it has been deleted?

/Marianne

![def lager](https://user-images.githubusercontent.com/34914779/34411395-9cb440b8-ebd6-11e7-99fa-28ba586f7808.png)

**Comment by dougaitken** [comment]
Hi @KlarissaM - do you have any other plugins which control product creation? These products have been deleted, this is why nothing is showing on that page.

I had a similar scenario yesterday and it was resolved by deleting the WooCommerce transients. If the products have been removed from the Trash, it is most likely caching related.

**Comment by mikejolley** [comment]
Transients indeed, or something has created some invalid products in your DB. There is a tool in system status to clear transients. You can also see what ID the edit link has and look up that record in WP Posts table. It may reveal what is wrong with the post/product. Could be botched import for example.

Thanks
