### ISSUE TITLE
linked products up-sells and cross-sells showing select instead of input

### ISSUE THREAD

**Issue by alirndev** [woocommerce/woocommerce#18304]
Hi, Since I've updated to woocommerce version 3.2.6 the following issue has been bugging me.

as shown in the picture, you can see that the up-sells and cross-sells fields are no longer input fields and they are select fields.
<img width="711" alt="up-cross-sells" src="https://user-images.githubusercontent.com/23038224/34425651-1c0df91e-ec43-11e7-86d8-c580b47eec69.PNG">

it's not possible to change them, since they only can be selected as a whole without the option to type in!
<img width="743" alt="up-cross-sells-elements" src="https://user-images.githubusercontent.com/23038224/34425652-1c58eed8-ec43-11e7-9df9-08c8732a417a.PNG">

could someone please help? has anyone else stumbled upon the same problem?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Select2-fields-not-working-in-3.0.x
