### ISSUE TITLE
Woocommerce Cart Session Issue

### ISSUE THREAD

**Issue by ayushsingh007** [woocommerce/woocommerce#18309]
# Unable to remove cart item on WC_Cart override

Earlier before Woocommerce 3.2, I was overriding **class-wc-cart.php** by extending WC_Cart in my file and it was working absolutely fine. 
But after release of Woocommerce 3.2, as per I can see cart session and cache management is seperated from the WC_Cart class. I tried all the alternatives of overriding WC_Cart, upto some extent I got successfull, but only after remove cart item and session set, Woocommerce somehow manages to get the older cart hash and hence the **get_refreshed_fragments** ajax, reloads the older cart hash.

Is there any alternative to do this or is there no way to override this. Please help me with this issue.

**Comment by mikejolley** [comment]
If you're extending cart, you'd change it's ->session prop to a custom class perhaps? Everything goes through WC_Cart, even if new classes control the session.

Not sure what you're doing of course :)

**Comment by ayushsingh007** [comment]
There was check for 'WC_Cart' class on it's->session as well as its->fee, though managed to make it work. Thanks anyways.
