### ISSUE TITLE
TypeError on checkout.min.js file with NextGen activated

### ISSUE THREAD

**Issue by mv83** [woocommerce/woocommerce#18303]
Hi there,
I get a `"o is null" `TypeError on the checkout.min.js file when I activate NextGen Gallery plugin. Anyone have encountered this error? The error occurs only on Safari and Firefox, not in Chrome.
Thanks in advance.

**Comment by mikejolley** [comment]
NextGen may be overriding one of the script dependencies. Hard to say without an example link. Please provide full details/links to site/system status for us to look into issues properly.
