### ISSUE TITLE
No Add to Cart button on product page 

### ISSUE THREAD

**Issue by WarrandyteFestival** [woocommerce/woocommerce#18308]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. updated theme
2. updated wordpress
3. installed woocommerce

## Expected/actual behavior

When I follow those steps, I see .... product page with no add to cart button : 
debug log shows
The The "add_to_cart_fragments" hook uses out of date data structures and function is deprecated since version 3.2.6. Replace with woocommerce_add_to_cart_fragments.
 👍 [29-Dec-2017 04:07:09 UTC] PHP Notice:  wc_get_template was called <strong>incorrectly</strong>. <code>/home/warrandy/public_html/wp-content/plugins/woocommerce/templates/global/wrapper-start.php</code> does not exist. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/ievent/woocommerce/single-product.php'), do_action('woocommerce_before_main_content'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, woocommerce_output_content_wrapper, wc_get_template, wc_doing_it_wrong Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 2.1.) in /home/warrandy/public_html/wp-includes/functions.php on line 4146
[29-Dec-2017 04:07:09 UTC] PHP Notice:  wc_get_template was called <strong>incorrectly</strong>. <code>/home/warrandy/public_html/wp-content/plugins/woocommerce/templates/single-product/sale-flash.php</code> does not exist. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/ievent/woocommerce/single-product.php'), wc_get_template_part, load_template, require('/themes/ievent/woocommerce/content-single-product.php'), do_action('woocommerce_before_single_product_summary'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, woocommerce_show_product_sale_flash, wc_get_template, wc_doing_it_wrong Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 2.1.) in /home/warrandy/public_html/wp-includes/functions.php on line 4146

I was expecting to see... product page with add to cart button

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, 
 - page doesn't load at all
- [ X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://warrandytefestival.org
Site URL: https://warrandytefestival.org
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.32
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: ✔
MySQL Version: 5.6.36
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wpv2_
MaxMind GeoIP Database: ✔
Total Database Size: 11.70MB
Database Data Size: 10.48MB
Database Index Size: 1.22MB
wpv2_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wpv2_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpv2_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpv2_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wpv2_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpv2_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpv2_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpv2_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wpv2_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpv2_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wpv2_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpv2_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpv2_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpv2_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpv2_commentmeta: Data: 0.02MB + Index: 0.03MB
wpv2_comments: Data: 0.02MB + Index: 0.08MB
wpv2_links: Data: 0.02MB + Index: 0.02MB
wpv2_nf3_actions: Data: 0.02MB + Index: 0.00MB
wpv2_nf3_action_meta: Data: 0.31MB + Index: 0.00MB
wpv2_nf3_fields: Data: 0.06MB + Index: 0.00MB
wpv2_nf3_field_meta: Data: 1.52MB + Index: 0.00MB
wpv2_nf3_forms: Data: 0.02MB + Index: 0.00MB
wpv2_nf3_form_meta: Data: 0.06MB + Index: 0.00MB
wpv2_nf3_objects: Data: 0.02MB + Index: 0.00MB
wpv2_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wpv2_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wpv2_ninja_forms_uploads: Data: 0.17MB + Index: 0.00MB
wpv2_options: Data: 3.28MB + Index: 0.02MB
wpv2_postmeta: Data: 1.52MB + Index: 0.41MB
wpv2_posts: Data: 2.52MB + Index: 0.09MB
wpv2_revslider_css: Data: 0.13MB + Index: 0.00MB
wpv2_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wpv2_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wpv2_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wpv2_revslider_slides: Data: 0.02MB + Index: 0.00MB
wpv2_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wpv2_termmeta: Data: 0.02MB + Index: 0.03MB
wpv2_terms: Data: 0.02MB + Index: 0.03MB
wpv2_term_relationships: Data: 0.02MB + Index: 0.02MB
wpv2_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpv2_usermeta: Data: 0.27MB + Index: 0.03MB
wpv2_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

agenda: 39
attachment: 20
flexslider: 7
nav_menu_item: 78
nf_sub: 87
page: 99
participants: 1
partners: 9
portfolio: 16
post: 13
product: 5
revision: 163
speakers: 11
templatera: 1
testimonials: 2
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Akismet Anti-Spam: by Automattic – 4.0.2
All-in-One WP Migration: by ServMask – 6.57
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.6
IEVENT Shortcodes: by Janxcode – 1.0.8
Intuitive Custom Post Order: by hijiri – 3.1.0
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.0
Ninja Forms - File Uploads: by The WP Ninjas – 3.0.17
Ninja Forms: by The WP Ninjas – 3.2.6
Really Simple SSL: by Rogier Lankhorst – 2.5.24
Slider Revolution: by ThemePunch – 5.4.6.4
Templatera: by WPBakery – 1.1.11
Velvet Blues Update URLs: by VelvetBlues.com – 3.2.7
WooCommerce: by Automattic – 3.2.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1976 - /shop/
Cart: #1977 - /shop/cart/
Checkout: #1978 - /shop/checkout/
My account: #1979 - /shop/my-account/
Terms and conditions: #1990 - /shop/terms-and-conditions/

### Theme ###

Name: ievent
Version: 2.0.3
Author URL: http://www.janxcode.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
The notices are from an outdated theme/plugin file. The missing cart button could also be related to said theme, but could also be a missing or invalid price (which is required). You should narrow the issue down before logging here in case it's a plugin conflict. No other users have reported this issue.

Thanks

**Comment by LuanTavaresWeb** [comment]
**•[The "add_to_cart_fragments" hook uses out of date data structures and function is deprecated since version 3.2.6. Replace with woocommerce_add_to_cart_fragments.]**

Find your theme's woocommerce.php file
wp-content/themes/your-theme/woocommerce/woocommerce.php

Find and replace add_to_cart_fragments -> woocommerce_add_to_cart_fragments
