### ISSUE TITLE
Errors in shipping for Asian countries

### ISSUE THREAD

**Issue by humidiflyer** [woocommerce/woocommerce#18305]
The shipping form for some Asian countries fails.

I have had issues with Japan, China and Thailand

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.Use a valid address in one of these countries
2.Enter that address for shipping.
3.See what a garbled mess comes out.

Here is one
Mr Alistair Smith
Komachi 2-15-10
Kamakura Shi 248-0006
Japan 

Comes out
248-0006
KanagawaKamakuraKomachi 2-15-10
Smith Alistair
Japan

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Format is defined here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-countries.php#L495

Change via this filter
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-countries.php#L475

The format is correct for Japan locales. It is missing some spacing however so I'll add that now.

**Comment by humidiflyer** [comment]
Well this is not fixed. It just did it again. Japan address all over the place!!

Paul Aberhart
HumidiFlyer iPhone

**Comment by mikejolley** [comment]
The fix won't be live yet...

**Comment by humidiflyer** [comment]
Sorry Mike

I don’t know how all this works.

Cheers, Paul Aberhart

HumidiFlyer Technologies Pty Ltd
PO Box 2018
Gladstone Park, 3043
Australia
Ph + 61 3 8307 5222
e-mail paul@humidiflyer.com  skype humidiflyer
www.humidiflyer.com

**Comment by mikejolley** [comment]
You can apply the fix manually to your install by seeing what changed in https://github.com/woocommerce/woocommerce/commit/3defa83a81d1f6d52780275b98f1020b993c02d8 This just adds spacing. The formatting itself (order of fields) is unchanged.

> The format is correct for Japan locales.

**Comment by humidiflyer** [comment]
The fields come through upside down!

Don’t know about that.

I will have my web guy look into this.

Thanks for the info, much appreciated.

I can send more screen shots if it helps.

Cheers, Paul Aberhart

HumidiFlyer Technologies Pty Ltd
PO Box 2018
Gladstone Park, 3043
Australia
Ph + 61 3 8307 5222
e-mail paul@humidiflyer.com  skype humidiflyer
www.humidiflyer.com
