### ISSUE TITLE
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-draggable,jquery-ui-slider,jquery-tou&load[]=ch-punch,iris,wp-color-picker&ver=4.8.4:4 POST https://www.sendeal.sn/wp-admin/admin-ajax.php 500 ()

### ISSUE THREAD

**Issue by DijaNdiaye** [woocommerce/woocommerce#18310]
Bonjour 
quelqu'un peut m'aider sur mon erreure ?? je suis nouvelle sur wordpress. je suis resté 2jours sans toucher à une plateforme et quand j'ai ajouté ajouter un produit la page se charger et me renvoyer aucun produit et en mode console sur moi dit que '' load-scripts.php? c = 0 & load [] = jquery-core, jquery-migrate, utilitaires, jquery-ui-core, jquery-ui-widget, jquery-ui-souris, jquery-ui-draggable, curseur jquery-ui, jquery-tou & load [] = ch-punch, iris, wp-color-picker & ver = 4.8.4: 4 POST https://www.sendeal.sn/wp-admin/admin-ajax.php 500 ()

**Comment by mikejolley** [comment]
See my comment https://github.com/woocommerce/woocommerce/issues/8889#issuecomment-354740499
