### ISSUE TITLE
Bug: Add-to-Cart shortcode button not adding Variation attributes when Ajax is enabled

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce#18318]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a new Variable product
2. Add at least 3 attributes, any length.
3. Make sure one of them has an SKU, copy this SKU
4. Create a new page, and use that SKU with the shortcode: `[add_to_cart sku="Variation-SKU"]`
5. Go to WooCommerce > Settings > Products > General
6. Make sure you enable AJAX for add-to-cart buttons
7. Visit your newly created page
8. Click the Add to Cart button

## Expected/actual behavior

When I follow those steps, I see...

No attributes are added to the product in the cart:
![screen shot 2018-01-01 at 12 44 08 pm](https://user-images.githubusercontent.com/3220162/34470954-7b385bb8-eef1-11e7-8f83-1b605ea39dcf.png)

I was expecting to see...

Attributes added properly:
![screen shot 2018-01-01 at 12 44 38 pm](https://user-images.githubusercontent.com/3220162/34470960-8e89a9b0-eef1-11e7-99e8-d965fa830022.png)

If you disable the AJAX option, the attributes are added properly.  What's happening is that AJAX is adding to cart before WooCommerce can read the parameters in the shortcode, so it just ends up adding the generic product without attributes to the cart.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
Ajax cart handler possibly needs to be changed to handle this, or ajax should be disabled.

**Comment by claudiulodro** [comment]
See #18351. Great variation product BTW.
