### ISSUE TITLE
Product image zoom on hover not working for variable products in Internet explorer and Firefox

### ISSUE THREAD

**Issue by msdigitalart1** [woocommerce/woocommerce#18316]
Hi, I am MS Shohan. For one of my clients website, woocommerce product zoom on hover is not working in internet explorer and Firefox. The website is [Evoshoe](https://evoshoe.com/product/%EC%97%90%EB%B3%B4%EC%8A%88-%EC%9D%B5%EC%8A%A4%ED%81%B4%EB%A3%A8%EC%8B%9C%EB%B8%8C-silver-snake-mid-heel-pumps/). Can you please tell me how I can fix this issue? Thank you in advance.

**Comment by mikejolley** [comment]
Tested in firefox and appears to be working. If you face issues like this, test a different theme.

**Comment by msdigitalart1** [comment]
With other themes, it works....... I replaced photoswipe.php, product-image.php and product-thumbnail.php. Yet it's not working for variable products. It works for the featured image only. But when I change variable product then it doesn't work. Is there any possible reason?

**Comment by mikejolley** [comment]
Replaced with what? We cannot support customisations to the gallery here.

**Comment by msdigitalart1** [comment]
My client uses a theme from themeforest and was having problem with gallery of that of that theme. So I replaced the theme author's overridden file from single-product/photoswipe.php, single-product/product-image.php and single-product/product-thumbnails.php with the files from woocommerce/templates/single-product.......... Do you get it?

**Comment by mikejolley** [comment]
There is more to it than just swapping files. The theme may for example have custom javascript to handle the variations. This is out of scope for this issue tracker - **we don't support 3rd party theme customisations.**
