### ISSUE TITLE
post_date and post_date_gmt set to 00 when order udpated

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce#18314]
Updating an order via the order admin sets the seconds value in `post_date` and `post_date_gmt` to `00`.  For example:

**Before the order is updated** 

2017-12-28 15:08:26

**After**
2017-12-28 15:08:00

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. View the `post_date` and `post_date_gmt` columns for an order
2. Update the order
3. Check the `post_date` and `post_date_gmt` columns again

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

 The `post_date` and `post_date_gmt` columns remain unchanged after an order is updated.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
cc @claudiulodro 

There is no UI for seconds. I compared to posts, and they leave seconds unchanged even when you change to hour/minute. This seems more wrong to be honest :)

@mdmoore Can you explain why this is a problem? Why is second precision needed?

**Comment by digitaliway** [comment]
we auto export orders daily from wp to our local systems using XML and use order date to the second to establish sequence on import with other orders from other sources. when the order is first made the seconds are correct so our imports work fine, but as soon as the staff updates order to complete the seconds are removed and the local import fails.  we have a work around in place locally, but would like to be able to retain seconds for accuracy and in some instances miliseconds.  Another issue is that post_date is editable by the admin and post_date_gmt updates with post_date so the actual original record/order creation date of the order is not accessible in the wp_posts and it would be nice to have an original record / order creation date save.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18371
