### ISSUE TITLE
Authenticating Requests Over HTTPS for the API Endpoints

### ISSUE THREAD

**Issue by adityajawade93** [woocommerce/woocommerce#18313]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.We have built a woocommerce Integration , to authenticate our app with customer's woocommerce api, we ask them to generate api keys for us.
2.We are trying to use query parameter auth to authenticate all requests , for some customers whose ssl is configured correctly the query param auth doesnot work , we have to use http basic auth for them
3.My query is that , is there a single way to authenticate over https for both customers whose ssl is configured correctly and other whose are not

Note -> We only support customers with a https store url and not http ones, so there is no point for us authenticating using the signature method suggested in the docs
We only support API Version wc/v2

## Expected/actual behavior

When I follow those steps, I see...
 401 error from customers whose ssl is configured correctly
I was expecting to see...
successfully request for all customers with query parameters auth

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
If you're attempting to use query string here too, I'd say it's related to https://github.com/woocommerce/woocommerce/issues/18312 - nginx config.
