### ISSUE TITLE
Products export just hanging

### ISSUE THREAD

**Issue by Xena123** [woocommerce/woocommerce#18321]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to Products
2. Choose export at the top of the page
3. Choose any combination of columns and products

## Expected/actual behavior

When I follow those steps, I see...

It opens to export products modal and there is a spinning grey circle but nothing else happens,

I was expecting to see...
A CSV download of products

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
You could look at the Javascript console for javascript errors, and the server error log in case of timeouts/memory limits being hit which may give more clues.

If it's a PHP error it might be logged under WooCommerce > System > Logs. If not look on your server/hosting control panel for the PHP error log.

Increase the memory limit with https://docs.woocommerce.com/document/increasing-the-wordpress-memory-limit/

Or submit a ticket so someone can login and check themselves https://woocommerce.com/my-account/tickets/ Reference this issue. But please check the logs first ^

This is working on other installs and my own so without knowing what else is running there is little we can do to reproduce your problem. It would be something specific to your site.

Thanks

**Comment by Xena123** [comment]
Its coming up with a internal server error 500?

**Comment by mikejolley** [comment]
In that case the PHP error log will definitely contain the full error reason. 500 is genetic.

**Comment by Xena123** [comment]
There is nothing in the log, the last error was on 15/12/2017

**Comment by Xena123** [comment]
2018-01-02T13:27:22+00:00 CRITICAL Uncaught Error: Call to undefined function mb_detect_encoding() in /home/zoom/public_html/wp-content/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php:367
Stack trace:
#0 /home/zoom/public_html/wp-content/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php(282): WC_CSV_Exporter->format_data('')
#1 [internal function]: WC_CSV_Exporter->export_row(Array, 0, Resource id #822)
#2 /home/zoom/public_html/wp-content/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php(260): array_walk(Array, Array, Resource id #822)
#3 /home/zoom/public_html/wp-content/plugins/woocommerce/includes/export/abstract-wc-csv-exporter.php(212): WC_CSV_Exporter->export_rows()
#4 /home/zoom/public_html/wp-content/plugins/woocommerce/includes/export/abstract-wc-csv-batch-exporter.php(90): WC_CSV_Exporter->get_csv_data()
#5 /home/zoom/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-exporters.php(134): WC_CSV_Batch_Exporter->generate_file()
#6 /home/zoom/public_html/wp-includes/c

**Comment by mikejolley** [comment]
Your host may be able to enable that function for you. Otherwise workaround is here https://github.com/woocommerce/woocommerce/pull/18324

**Comment by Xena123** [comment]
Thank you, I will check with my host to see if they can enable it.

**Comment by Xena123** [comment]
Hi, my host enabled that function. The exporter is now getting to about a third way complete and then stopping and hanging again. 

The console says:
POST https://zoomoffice.co.uk/wp-admin/admin-ajax.php 500 (Internal Server Error)

Nothing in the log.
