### ISSUE TITLE
Product Search Backend

### ISSUE THREAD

**Issue by deluecksch** [woocommerce/woocommerce#18325]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

Steps to reproduce the problem.

1. order
2. add order
3. add order item
4. add products
5. product search

Expected/current behavior

Searching for products takes an extremely long time with 3000 products. Adding several products at the same time cancels the whole action. Database index not possible because the search works with full text.

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

<details>

## WordPress Environment

- Administrator
- 4.9.1
WC: 3.2.6 and several plugins from Woocommerce Store

### WordPress Environment ###

Home URL: https://deluecks.ch
Site URL: https://deluecks.ch
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 7.1.12
PHP Post Max Size: 16 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.57.0
OpenSSL/1.0.2n

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: ip_deluecks_
Datenbank-Gesamtgröße: 194.13MB
Datenbank-Datengröße: 121.71MB
Datenbank-Indexgröße: 72.42MB
ip_deluecks_woocommerce_sessions: Daten: 8.06MB + Index: 0.02MB
ip_deluecks_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.05MB
ip_deluecks_woocommerce_order_items: Daten: 1.52MB + Index: 0.52MB
ip_deluecks_woocommerce_order_itemmeta: Daten: 6.52MB + Index: 9.03MB
ip_deluecks_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
ip_deluecks_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
ip_deluecks_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
ip_deluecks_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_commentmeta: Daten: 0.20MB + Index: 0.22MB
ip_deluecks_comments: Daten: 2.52MB + Index: 1.59MB
ip_deluecks_defender_lockout: Daten: 0.02MB + Index: 0.00MB
ip_deluecks_defender_lockout_log: Daten: 1.45MB + Index: 0.00MB
ip_deluecks_links: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_optins: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_optin_meta: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_options: Daten: 10.47MB + Index: 1.48MB
ip_deluecks_popover_ip_cache: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_postmeta: Daten: 49.59MB + Index: 42.16MB
ip_deluecks_posts: Daten: 27.55MB + Index: 3.94MB
ip_deluecks_smush_dir_images: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_social_users: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_taxonomymeta: Daten: 0.13MB + Index: 0.09MB
ip_deluecks_termmeta: Daten: 1.52MB + Index: 0.84MB
ip_deluecks_terms: Daten: 1.52MB + Index: 0.83MB
ip_deluecks_term_relationships: Daten: 1.52MB + Index: 1.52MB
ip_deluecks_term_taxonomy: Daten: 0.45MB + Index: 0.48MB
ip_deluecks_usermeta: Daten: 2.52MB + Index: 3.03MB
ip_deluecks_users: Daten: 0.19MB + Index: 0.17MB
ip_deluecks_wc_gpf_render_cache: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_wc_points_rewards_user_points: Daten: 0.14MB + Index: 0.17MB
ip_deluecks_wc_points_rewards_user_points_log: Daten: 0.20MB + Index: 0.23MB
ip_deluecks_woocommerce_bundled_itemmeta: Daten: 3.52MB + Index: 5.03MB
ip_deluecks_woocommerce_bundled_items: Daten: 0.16MB + Index: 0.23MB
ip_deluecks_woocommerce_gpf_google_taxonomy: Daten: 1.52MB + Index: 0.00MB
ip_deluecks_wplnst_urls: Daten: 0.02MB + Index: 0.19MB
ip_deluecks_yith_wcwl: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_yith_wcwl_lists: Daten: 0.02MB + Index: 0.17MB

### Post Type Counts ###

attachment: 5828
blocks: 2
bp-email: 1
customize_changeset: 65
dt_gallery: 14
dt_portfolio: 19
dt_slideshow: 1
dt_team: 7
dt_testimonials: 39
feedback: 30
global_product_addon: 1
mc4wp-form: 2
nav_menu_item: 217
page: 23
post: 14
product: 2518
product_variation: 3750
reply: 1
revision: 133
rtmedia_album: 1
safecss: 1
shop_coupon: 2
shop_order: 3438
shop_order_refund: 10
shop_webhook: 1
wdf_scan: 1
wdf_scan_item: 1
wpcf7_contact_form: 1
wphb_minify_group: 30

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Contact Form 7: von Takayuki Miyoshi – 4.9.2
Facebook for WooCommerce: von Facebook – 1.7.3 – Nicht getestest mit der aktiven WooCommerce-Version
Hustle Pro: von WPMU DEV – 2.1.5.1
Nextend Facebook Connect: von Nextendweb – 2.0.2
Nextend Google Connect: von Roland Soos
Jamie Bainbridge – 1.6.1

PostFinance E-Payment Gateway for WooCommerce: von mame webdesign hüttig – 2.2.1 – Nicht getestest mit der aktiven WooCommerce-Version
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 3.0.1
WooCommerce Print Invoice & Delivery Note: von Tyche Softwares – 4.4.1
WooCommerce Google Analytics Pro: von SkyVerge – 1.3.6
WooCommerce Points and Rewards: von WooCommerce – 1.6.10
WooCommerce Product Bundles: von SomewhereWarm – 5.7.1
WooCommerce Google Product Feed: von Ademti Software Ltd. – 7.4.2
WooCommerce: von Automattic – 3.2.6
WooSidebars: von WooThemes – 1.4.3
WP Defender Pro: von WPMU DEV – 1.7.4.1
Hummingbird Pro: von WPMU DEV – 1.7.0.3
WP Smush Pro: von WPMU DEV – 2.7.6
SmartCrawl: von WPMU DEV – 2.1.0.1
WPMU DEV Dashboard: von WPMU DEV – 4.4
YITH WooCommerce Wunschliste: von YITHEMES – 2.1.2 – Nicht getestest mit der aktiven WooCommerce-Version

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #69858 - /shop/
Warenkorb: #18667 - /warenkorb/
Kasse: #18669 - /checkout/
Mein Konto: #710 - /mein-konto/
Geschäftsbedingungen: #7429 - /agb/

### Theme ###

Name: Flatsome
Version: 3.4.2
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Bundle indicator (is_bundle): 
Brand: Defaults to "IP Klinik DeLueckS".
Manufacturer Part Number (MPN): Pre-populates from "sku taxonomy".
Product Type: Pre-populates from "product_cat taxonomy".
Adwords grouping filter: 
Delivery label: Pre-populates from "product_shipping_class taxonomy".

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: Enabled
````
</details>

**Comment by claudiulodro** [comment]
It's really searching 7000 products because it also has to search variations. This should be somewhat faster once products are using custom tables because it won't have to search the meta table for SKUs, but I don't think there are any straightforward performance improvements that can be done right now. 

[Here is the SQL query](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L1236-L1257) if you have any ideas.

**Comment by mikejolley** [comment]
I don't think we can do much until custom tables, and that has it's own issue(s) open. @rodrigoprimo  @kloon any quick fixes or close this and wait for custom tables?

**Comment by deluecksch** [comment]
This is unfortunately not an option. The hoster releases this only from the managed server. For us, this is an everyday tool and so we cannot work quickly. @claudiulodro @mikejolley

**Comment by rodrigoprimo** [comment]
> any quick fixes or close this and wait for custom tables?

Maybe we could add a filter to support custom product search queries like we did for customer search (#16631)? Excluding the SKU from the query should improve its performance. Definitely something we don't want to do in core but might help some users. Not sure if this would help @deluecksch or not.

@deluecksch, another option that might help you is add an index to the `meta_value` field.

**Comment by deluecksch** [comment]
It would help us to search only with the product ID. Respective with the article number. @rodrigoprimo

**Comment by mikejolley** [comment]
Let's resolve that part in https://github.com/woocommerce/woocommerce/issues/18358 which is related.
