### ISSUE TITLE
order and key could be 0 in download link

### ISSUE THREAD

**Issue by Babelfisch** [woocommerce/woocommerce#18328]
The download link for download products includes the parameters `order` and `key` with the `order_key` and `download_id`. If these two parameters are set to `0`, the download is still possible.

```
/?download_file=product_id&order=0&email=email%40example.org&key=0
```

This link works if product_id and email are valid.

This is because in `class-wc-download-handler.php` the parameter tested with `isset`:

```php
if ( ! $product || ! isset( $_GET['key'], $_GET['order'] ) ) {
```

This is TRUE with value 0. But in `class-wc-customer-download-data-store.php` there is only a test on the value:

```php
if ( $args['order_key'] ) {
…
if ( $args['download_id'] ) {
```

This is FALSE with value 0 and the query does not include this conditions.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18335
