### ISSUE TITLE
Update Order Review on State Change(AJAX)

### ISSUE THREAD

**Issue by Vandalism20** [woocommerce/woocommerce#18331]
Whenever the state is change, I want the Order Review to change because of the shipping cost. Whenever the user change the state, the shipping cost should change. The shipping cost only changes whenever the page is reloaded, what I want is for it to not reload and make the shipping cost change realtime without reloading. I've noticed that ?wc-ajax=update_order_review is being called whenever the state is changing but the order review still won't update. All the forms has been filled out also. How can I fix this?

**Comment by Vandalism20** [comment]
I have found this code. Where should I put this? What path of the file?
`function action_woocommerce_checkout_update_order_review($array, $int)
{
    WC()->cart->calculate_shipping();
    return;
}
add_action('woocommerce_checkout_update_order_review', 'action_woocommerce_checkout_update_order_review', 10, 2);
?>`

**Comment by mikejolley** [comment]
> I've noticed that ?wc-ajax=update_order_review is being called whenever the state is changing but the order review still won't update

If it's being called, the update is happening UNLESS your theme is breaking this process. The extra code is not needed.

Order review changes when all shipping fields are complete and any shipping field changes from then on. Tested and working as it should on a clean install.
