### ISSUE TITLE
Value added tax in the backend

### ISSUE THREAD

**Issue by deluecksch** [woocommerce/woocommerce#18336]
[x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
[x ] The issue still exists against the latest master branch of WooCommerce on Github (this is not the same version as on WordPress.org!)
[x ] I have attempted to find the simplest possible steps to reproduce the issue
 I have included a failing test as a pull request (Optional)
Steps to reproduce the problem.

<! -- We must be able to reproduce the error to correct it, so please be descriptive! -->

order
add order
add order item
add products
save order

Value added tax is not rounded up or down in the event of a manual change to the product price. 

When I follow those steps, I see...

I was expecting to see...

Isolating the problem
[x ] This bug happens with only WooCommerce plugin active
 This bug happens with a default WordPress theme active, or Storefront
[ x] I can reproduce this bug consistently using the steps above
WordPress Environment
Administrator
4.9.1
WC: 3.2.6 and several plugins from Woocommerce Store
WordPress Environment
Home URL: https://deluecks.ch
Site URL: https://deluecks.ch
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

Server Environment
Server Info: Apache/2.4
PHP Version: 7.1.12
PHP Post Max Size: 16 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.57.0
OpenSSL/1.0.2n

SUHOSIN Installed: –
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

Database
WC Database Version: 3.2.6
WC Database Prefix: ip_deluecks_
Datenbank-Gesamtgröße: 194.13MB
Datenbank-Datengröße: 121.71MB
Datenbank-Indexgröße: 72.42MB
ip_deluecks_woocommerce_sessions: Daten: 8.06MB + Index: 0.02MB
ip_deluecks_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.05MB
ip_deluecks_woocommerce_order_items: Daten: 1.52MB + Index: 0.52MB
ip_deluecks_woocommerce_order_itemmeta: Daten: 6.52MB + Index: 9.03MB
ip_deluecks_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
ip_deluecks_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
ip_deluecks_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
ip_deluecks_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_commentmeta: Daten: 0.20MB + Index: 0.22MB
ip_deluecks_comments: Daten: 2.52MB + Index: 1.59MB
ip_deluecks_defender_lockout: Daten: 0.02MB + Index: 0.00MB
ip_deluecks_defender_lockout_log: Daten: 1.45MB + Index: 0.00MB
ip_deluecks_links: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_optins: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_optin_meta: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_options: Daten: 10.47MB + Index: 1.48MB
ip_deluecks_popover_ip_cache: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_postmeta: Daten: 49.59MB + Index: 42.16MB
ip_deluecks_posts: Daten: 27.55MB + Index: 3.94MB
ip_deluecks_smush_dir_images: Daten: 0.02MB + Index: 0.03MB
ip_deluecks_social_users: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_taxonomymeta: Daten: 0.13MB + Index: 0.09MB
ip_deluecks_termmeta: Daten: 1.52MB + Index: 0.84MB
ip_deluecks_terms: Daten: 1.52MB + Index: 0.83MB
ip_deluecks_term_relationships: Daten: 1.52MB + Index: 1.52MB
ip_deluecks_term_taxonomy: Daten: 0.45MB + Index: 0.48MB
ip_deluecks_usermeta: Daten: 2.52MB + Index: 3.03MB
ip_deluecks_users: Daten: 0.19MB + Index: 0.17MB
ip_deluecks_wc_gpf_render_cache: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_wc_points_rewards_user_points: Daten: 0.14MB + Index: 0.17MB
ip_deluecks_wc_points_rewards_user_points_log: Daten: 0.20MB + Index: 0.23MB
ip_deluecks_woocommerce_bundled_itemmeta: Daten: 3.52MB + Index: 5.03MB
ip_deluecks_woocommerce_bundled_items: Daten: 0.16MB + Index: 0.23MB
ip_deluecks_woocommerce_gpf_google_taxonomy: Daten: 1.52MB + Index: 0.00MB
ip_deluecks_wplnst_urls: Daten: 0.02MB + Index: 0.19MB
ip_deluecks_yith_wcwl: Daten: 0.02MB + Index: 0.02MB
ip_deluecks_yith_wcwl_lists: Daten: 0.02MB + Index: 0.17MB

Post Type Counts
attachment: 5828
blocks: 2
bp-email: 1
customize_changeset: 65
dt_gallery: 14
dt_portfolio: 19
dt_slideshow: 1
dt_team: 7
dt_testimonials: 39
feedback: 30
global_product_addon: 1
mc4wp-form: 2
nav_menu_item: 217
page: 23
post: 14
product: 2518
product_variation: 3750
reply: 1
revision: 133
rtmedia_album: 1
safecss: 1
shop_coupon: 2
shop_order: 3438
shop_order_refund: 10
shop_webhook: 1
wdf_scan: 1
wdf_scan_item: 1
wpcf7_contact_form: 1
wphb_minify_group: 30

Security
Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

Active Plugins (20)
Contact Form 7: von Takayuki Miyoshi – 4.9.2
Facebook for WooCommerce: von Facebook – 1.7.3 – Nicht getestest mit der aktiven WooCommerce-Version
Hustle Pro: von WPMU DEV – 2.1.5.1
Nextend Facebook Connect: von Nextendweb – 2.0.2
Nextend Google Connect: von Roland Soos
Jamie Bainbridge – 1.6.1

PostFinance E-Payment Gateway for WooCommerce: von mame webdesign hüttig – 2.2.1 – Nicht getestest mit der aktiven WooCommerce-Version
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 3.0.1
WooCommerce Print Invoice & Delivery Note: von Tyche Softwares – 4.4.1
WooCommerce Google Analytics Pro: von SkyVerge – 1.3.6
WooCommerce Points and Rewards: von WooCommerce – 1.6.10
WooCommerce Product Bundles: von SomewhereWarm – 5.7.1
WooCommerce Google Product Feed: von Ademti Software Ltd. – 7.4.2
WooCommerce: von Automattic – 3.2.6
WooSidebars: von WooThemes – 1.4.3
WP Defender Pro: von WPMU DEV – 1.7.4.1
Hummingbird Pro: von WPMU DEV – 1.7.0.3
WP Smush Pro: von WPMU DEV – 2.7.6
SmartCrawl: von WPMU DEV – 2.1.0.1
WPMU DEV Dashboard: von WPMU DEV – 4.4
YITH WooCommerce Wunschliste: von YITHEMES – 2.1.2 – Nicht getestest mit der aktiven WooCommerce-Version

Settings
API Enabled: ✔
Force SSL: ✔
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

WC Pages
Shop-Basis: #69858 - /shop/
Warenkorb: #18667 - /warenkorb/
Kasse: #18669 - /checkout/
Mein Konto: #710 - /mein-konto/
Geschäftsbedingungen: #7429 - /agb/

Theme
Name: Flatsome
Version: 3.4.2
Author URL: http://www.uxthemes.com/
Child Theme: :x: – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

Templates
Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

WooCommerce Google Product Feed fields
Availability: Defaults to "in stock".
Bundle indicator (is_bundle):
Brand: Defaults to "IP Klinik DeLueckS".
Manufacturer Part Number (MPN): Pre-populates from "sku taxonomy".
Product Type: Pre-populates from "product_cat taxonomy".
Adwords grouping filter:
Delivery label: Pre-populates from "product_shipping_class taxonomy".

WooCommerce Google Product Feed options
Include variations in feed: Enabled
Send item_group_id: Enabled

**Comment by mikejolley** [comment]
> Value added tax is not rounded up or down in the event of a manual change to the product price.

Manual edits require manual edits to all fields, unless you use recalculate button. Otherwise, manual edits would not be possible because your changes would be overwritten.

**Comment by deluecksch** [comment]
I adjust the products manually. (internal order)
In the shop, VAT is added or subtracted in the shopping cart.
How can I prevent / set this in the backend? @mikejolley

**Comment by mikejolley** [comment]
No idea what you're asking -give examples.

**Comment by deluecksch** [comment]
Customer calls and orders a product. We enter the order in the backend and give the customer a discount. The value added tax is calculated but does not round up or down the amount. In Switzerland there is no 1 cent but 5. 
Example: 1.55 and not 1.59.

**Comment by mikejolley** [comment]
This type of rounding is only achievable though customisation.

**Comment by deluecksch** [comment]
Can you give me a tip?

**Comment by mikejolley** [comment]
What snippet are you using for the frontend taxes? The euro_5cent_rounding one? I've not tested it for a while.

**Comment by deluecksch** [comment]
i don't use a script. woocommerce does this itself in the frontend.
The problem is that you can set "prices including VAT". It does not do this in the backend area.
In the backend you have to specify the net price. In the frontend he calculates the gross price and sets the value added tax and does not include it on the total price as in the backend.

The logic is not quite right yet.

**Comment by mikejolley** [comment]
WC does not round to .5 itself on the frontend. Not without customisation.

**Comment by deluecksch** [comment]
Like I said. The prices are gross. You can set in the WC that the prices are inclusive of VAT. Therefore, orders on the frontend are correct.
In the backend, you have to specify the net price instead of the gross price.

**Comment by deluecksch** [comment]
can you reopen the ticket? @mikejolley

**Comment by mikejolley** [comment]
What you're asking for isn't supported out of the box. Prices in backend are exclusive of tax.

**Comment by deluecksch** [comment]
Can't you set an option to set the price in the backend? (inclusive or exclusive of VAT)

**Comment by mikejolley** [comment]
We could, if we wanted to rewrite everything :) Not a small task, and not one we should do without ample demand. ideas.woocommerce.com.
