### ISSUE TITLE
Order again in my account page button cannot add item meta (custom fields).

### ISSUE THREAD

**Issue by unitedsol** [woocommerce/woocommerce#18332]
I have using product addons when i order again from my-account order view page it cannot add the options  here is the hook i used woocommerce_order_again_cart_item_data but cannot add the item meta please help.

Thanks

**Comment by mikejolley** [comment]
We don't provide customisations here.

The addons/order again issue was logged yesterday https://github.com/woocommerce/woocommerce/issues/18290
