### ISSUE TITLE
Next/prev navigation in order preview backbone modal

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#18348]
@mikejolley In new order preview modal can you also give it a chance for next/prev navigation in modal header. It will make life ease to preview other orders with arrow keys too.

**Comment by mikejolley** [comment]
This would need a loading state whilst the AJAX grabs the data from the backend. It's a nice idea but I'd prefer we wait for real world usage feedback to see if it would be useful.

cc @warrendholmes to see if this is something we can get feedback from users on after 3.3.

Thanks
