### ISSUE TITLE
No filter for notice messages

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce#18350]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

Filter is missing for WooCommerce notice messages: 
https://github.com/woocommerce/woocommerce/blob/c16acc6b5104acb0ed082e7df1c63dfd77598459/includes/wc-notice-functions.php#L125

The filtering is required for plugins that modify the text/output, e.g. the wp-typography plugin to which WooCommerce support is added: https://github.com/mundschenk-at/wp-typography/issues/178#issuecomment-355126448 
Without a filter this isn't possible.

**Comment by rodrigoprimo** [comment]
There is a filter that is called whenever a notice is stored in the session or printed directly:

https://github.com/woocommerce/woocommerce/blob/185934fad9719fb531d3cbe51379a5d780c78a5a/includes/wc-notice-functions.php#L87
https://github.com/woocommerce/woocommerce/blob/185934fad9719fb531d3cbe51379a5d780c78a5a/includes/wc-notice-functions.php#L161

Does it work for your use case or it would be better to create a new filter inside `wc_print_notices()`?

**Comment by strarsis** [comment]
@rodrigoprimo: The filter should be applied each time the notice is printed to screen because the typography plugin may be disabled in future or settings changed that are unrelated to the filtered data itself, hence storing and updating it in database would not work.

**Comment by mikejolley** [comment]
@rodrigoprimo good call.

@strarsis nothing is stored the the DB. The notice API works in the current request, so the filter above will work for all notices.
