### ISSUE TITLE
Enhancement: Change wording to icon

### ISSUE THREAD

**Issue by TWG-Matt** [woocommerce/woocommerce#18352]
When working on my laptop or tablet and I'm editing products, I've noticed that “out of stock” and “in stock” word wrap.  I get why they do but I think it would have a cleaner look to change those words out for a  ✅ and a 🚫.

**Comment by jameskoster** [comment]
I'm not opposed to an icon+number rather than the full label. We'd need an "on backorder" icon as well though.

Needs design.

**Comment by kellychoffman** [comment]
Let's just increase the column width. Icons are not easy to decipher and require a tooltip. No need to introduce ambiguity. 

Not sure a designer is needed here.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18365
