### ISSUE TITLE
WC_Abstract_Order: incorrect use of expression max( 1, $item->get_quantity() ) in various methods, a.o. get_item_total()

### ISSUE THREAD

**Issue by fietserwin** [woocommerce/woocommerce#18357]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. The class WC_Abstract_Order *and perhaps descending or other classes as well) contains the expression max( 1, $item->get_quantity() ) in various places. Apparently this was introduced to prevent rare situations where get_quantity() returns 0.
2. However this expression will result in incorrect values when $item->get_quantity() is smaller then 1, i.e when it is:
2.1 negative like in refunds.
2.2 between 0 and 1 when partial quantities can be sold, e.g 0.5 kg, and the price is listed as price per kg.

## Expected/actual behavior

1. When I call get_item_total() on a refund line, I expect the result to be the negative original price per unit and not the positive line total.
2. When I call get-item_total() on a line with a partial quantity, I expect it to be the price per unit not the line total.

wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php: 5 occurrences.
wp-content/plugins/woocommerce/includes/api/class-wc-rest-orders-controller.php: 1 occurrence.

## Suggested solution
Replace occurrences by something like:
$item->get_quantity() != 0 ? $item->get_total() / $item->get_quantity() : $item->get_total()

This does prevent the division by zero errors that were the reason to introduce this construction. get_quantity() is allowed to have side effects (not likely) or is considered a resource intensive method call, consider placing it in a variable instead of calling it twice.

Notes:
- Refunds are supported by WooCommerce itself, thus I do consider this a bug.
- Even though WooCommerce itself does not support decimal quantities, methods that are created with gateways, APIs, REST calls etc in mind, (like get_item_total) should if possible cater for situations that WooCommerce standalone does not directly support (sound development principle).

## Isolating the problem

- [] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18367
