### ISSUE TITLE
Disable IP logging

### ISSUE THREAD

**Issue by greencopper** [woocommerce/woocommerce#18366]
I cannot enter http://ideas.woocommerce.com/forums/133476-woocommerce as you are using CloudFlare and they are blogging our VPN service.

In our country IP logging is becoming illegal and we need to be able to disable IP logging, which is enabled by default without any disable options.

It should be possible to fully disable IP logging in WooCommerce.

Kind regards

**Comment by mikejolley** [comment]
What country is that then - got any evidence to back this up? IPs are logged everywhere, not just in WC. Comment forms. By servers (access log). etc.

**Comment by greencopper** [comment]
It's in the entire EU.

In Denmark it used to be regulated by something called "The law of personal data", but it as been replaced by the "The general data protection regulation" which is a requirement by all member countries. https://www.eugdpr.org/ and it is in force on the 25 of may 2018.

A lot of other stuff becomes illegal to log too.

**Comment by mikejolley** [comment]
We're aware of GDPR and if changes are needed in WC we'll make them before it rolls out. 

AFAIK it's not illegal to log public IP addresses, just like it's not illegal to store the customer's billing address as long as the user is aware what data is stored and for what purpose. In this case, the IP address is mostly there for fraud prevention and geolocation.

We have an article here if you're interested https://woocommerce.com/2017/12/gdpr-compliance-woocommerce/

**Comment by greencopper** [comment]
It's fantastic that you guys are paying attention to this (thanks for the link).

It's not correct that the user "just" needs to be aware, the user has to manually accept this, but must also be presented with the option not to allow this, and be able to later get such data erased.

> The conditions for consent have been strengthened, and companies will no longer be able to use long illegible terms and conditions full of legalese, as the request for consent must be given in an intelligible and easily accessible form, with the purpose for data processing attached to that consent. Consent must be clear and distinguishable from other matters and provided in an intelligible and easily accessible form, using clear and plain language. It must be as easy to withdraw consent as it is to give it.​

I am in the process of reading all the rules of the law and validate if our company is in compliance (which we are not yet).

Having the ability to disable all this logging would be fantastic as the fines for mistakes are extreme.

**Comment by mikejolley** [comment]
I am not a lawyer but just briefly:

> but must also be presented with the option not to allow this, and be able to later get such data erased

They have the option to not checkout and not place an order right :)?

You're right about data erasing. Thats something which will need looking into further.
