### ISSUE TITLE
Visual feedback for bad row/column values in the Customizer

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#18364]
Product rows / columns are now controlled in the Customizer. We provide number inputs and themes and plugins can supply custom min / max values. Those values are respected by the number input when you click the increase / decrease wheel in the input itself, but they don't stop you typing something outside those values into the input manually. This can result in a mismatch between what you see in the settings vs what you see in the preview. Example;

![12](https://cldup.com/FXbzpTkTGF-3000x3000.png)

Two potential solutions to this;

* Use the notifications API to display an error and inform the user of the accepted values.
* Replace the `number` input with a `range` input.

The range input would be cleaner (as long as we can display the actual number value next to it) as it leaves no room for error, but that only works if a max value is supplied. But I think we could (probably _should_) provide a hard-cap maximum for columns / rows in core anyway.

**Comment by mikejolley** [comment]
Range no go https://core.trac.wordpress.org/ticket/28849

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18383
