### ISSUE TITLE
Woocommerce backend styles (admin.css) affects other plugins backend. 

### ISSUE THREAD

**Issue by thirumani02** [woocommerce/woocommerce#18361]
I am facing similar issue https://github.com/woocommerce/woocommerce/issues/17721 

Woocommerce adds `woocommerce` class to body tag at backend. You can test this by simply installing contact form 7 plugin.

    <body class="wp-admin wp-core-ui js  woocommerce  toplevel_page_wpcf7 auto-fold admin-bar branch-4-8 version-4-8-4 admin-color-fresh locale-en-us customize-support svg" >

I tested with simple environment,
Active Theme: Twenty seventeen
Active Plugins: Woocommerce, contact form 7

Let me know, if you guys need further information.

**Comment by mikejolley** [comment]
These are the pages which get the class by default: https://github.com/woocommerce/woocommerce/blob/4b029f72528573dd8a1a07c1aaaa3997b998f02b/includes/admin/wc-admin-functions.php#L20-L56

Any more and it's a plugin/theme/custom code adding it. I'm not seeing a problem with just CF7 and WC as shown:

![admin php page wpcf7 2018-01-05 10-31-31](https://user-images.githubusercontent.com/90977/34605467-a1fef4b8-f203-11e7-97ee-c8772819c48a.png)

> Let me know, if you guys need further information.

The new issue page let you know and you didn't provide everything :)
