### ISSUE TITLE
Template & File versions vs Release version

### ISSUE THREAD

**Issue by bahiirwa** [woocommerce/woocommerce#18369]
Documentation issue

When I check the repo files, I noticed the versions are different from the release version's. Is there a specific reason for this? If not, I can submit a PR to this effect to 3.2.6 which is the released update on WP SVN.

Thanks

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Template-File-Guidelines-for-Devs-and-Theme-Authors

> Each template file has a @version which reflects the last version of WooCommerce to edit or include this template file. If your overridden version differs, there will be a warning on WooCommerce Status page; template files need to be kept updated as they may include important fixes.
