### ISSUE TITLE
Changing front-end assets to modern web standards

### ISSUE THREAD

**Issue by tameemsafi** [woocommerce/woocommerce#18378]
I was looking at ways I could contribute towards woo-commerce, as I use it often.

It looks like the new wp-admin UI for the custom tables has not been started yet, and I wanted to ask what you think of rewriting the build system used for JS/CSS assets?

At the moment you are using grunt for both SCSS and Javascript assets. The javascript is written in separate files, which are then enqueued when needed. It is also the same for the CSS files.

Here is my proposal:

- Rewrite build scripts to make use of Webpack (for CSS, Javascript and any other assets such as images).
- Javascript to be rewritten in ES6 using babel as a transpiler to make it compatible with ES5. Alternatively, it can all be written using Typescript to allow for type checking. This would allow for more advanced UI interfaces to be built much more easily. The output would be just one bundle for the front-end and another for the wp-admin. This will remove the need for multiple script tags and HTTP requests.
- SCSS to be bundled into two files (front-end/wp-admin). This would be similar to javascript in that it won't require additional link tags and HTTP requests.

With this new build system, it would make it much easier to work on scalable UI. Maybe even integrate a JS framework like React or VueJS in the future.

Another benefit of this would be that jQuery can be removed as a dependency and many other NPM packages can be used instead. This would require a rewrite of most of the JS, but it would be easier.

I would be happy to work on this in my spare time, but I just wanted to get the opinions of some other contributors before doing such a task.

**Comment by cr101** [comment]
@tameemsafi Perhaps the new wp-admin UI for the custom db tables has not been started yet because it will also need to work with Gutenberg. Just a thought!

**Comment by tameemsafi** [comment]
@cr101 Yes that could be a possibility, but also the new table UI has not beeb started. Also Gutenberg is built with React, webpack and ES6. So if the plan is to support Gutenberg, would it not be best to have the build system changed to make it easier?

**Comment by mikejolley** [comment]
R/e reliance of jQuery we have this logged: https://github.com/woocommerce/woocommerce/issues/17877

> SCSS to be bundled into two files (front-end/wp-admin). This would be similar to javascript in that it won't require additional link tags and HTTP requests.

There are disadvantages to this in WP Admin in that all scripts in WC are not needed on all scripts. Using enqueue script/style we can enqueue what is needed. With a bundle, it's all or nothing. WC is not a single page app so shouldn't be treated as such.

For frontend, again, WC is not a single page app. Multiple files allows theme authors/plugin developers to selectively enqueue and dequeue features also. e.g. X theme wants to disable only the product gallery.

> Another benefit of this would be that jQuery can be removed as a dependency and many other NPM packages can be used instead. 

Would rather not rely on lots of 3rd party NPM scripts if possible. That could lead to conflicts and make the build/release process more difficult.

--

My vote (because WC is not a single page app and is built within the confines of WP admin) would be to:

1. Drop use of jQuery https://github.com/woocommerce/woocommerce/issues/17877
2. Keep scripts separated and single use for easy dequeue/enqueue on screens where needed
3. Stop storing compiled/minified JS and CSS in the repo and do that on release.

No opinion on use of ES6/ES5 - not sure of the benefits of complexities of doing so.

**Comment by mikejolley** [comment]
@claudiulodro @belcherj Any thoughts on the above?

**Comment by claudiulodro** [comment]
I think @mikejolley's plan sounds good. 

I think we should use ES6 with a transpiler. We're going to need that for Gutenberg so we should also use it in other places for consistency. Also, coding everything in vanilla JS is going to be much easier and more maintainable if we're using ES6.

**Comment by belcherj** [comment]
> There are disadvantages to this in WP Admin in that all scripts in WC are not needed on all screens. Using enqueue script/style we can enqueue what is needed. With a bundle, it's all or nothing. WC is not a single page app so shouldn't be treated as such.

You can achieve this with Webpack by creating multiple bundles.  We can still use Webpack and create sensible smaller bundles.  To ensure that we do not have a lot of duplicate code in those bundles is a bit more work but doable. Sometimes the cost of creating these bundles is higher than the savings.  If you are creating a separate bundle so you can dynamically load <10k of JS in the wp-admin it may not be worth the effort.  The benefit of Webpack is that you give it an entrance and it loads in all the code that you require deduping when multiple files require the same module.  This does not work quite as well when you have multiple bundles.

> Another benefit of this would be that jQuery can be removed as a dependency and many other NPM packages can be used instead.

It is important to be sensible about including 3rd party scripts for a variety of reasons.  I do not see lots of NPM modules causing conflicts or build problems.  I do see security and bloat issues.  With the way modules work you will not have to worry about conflicts as modules are scoped to themselves.  You do not get the traditional global namespace pollution.

> Drop use of jQuery #17877

Dropping jQuery gets much easier once you have a way to load _some_ node modules like the fetch polyfil. Dropping jQuery is good and all but we need to ensure that everyone understands how to write code without it. 

> Keep scripts separated and single use for easy dequeue/enqueue on screens where needed

I think that every script as its own build target is a mistake as you will need to dupe JS code every time one of those files wants to use some woo standard lib code or node modules. I think there is probably a middle ground where we can group some code together. I think this is less of a problem for the wp-admin than it is for shipping code to a sites front end.

> Stop storing compiled/minified JS and CSS in the repo and do that on release.

This would be a huge win.  I promised you @mikejolley a post on what that would look like.  We had discussed that it would be preferable that if you cloned down the repo you would get built assets.  I could not come up with a solution for that.  I do think that pushing minified assets to the repo causes more problems than requiring devs to run one long lived node process.

> No opinion on use of ES6/ES5 - not sure of the benefits of complexities of doing so.

ES5 is dead, long live ES5. Unfortunately we are stuck with ES5 as a compile to target until IE11 goes away.  The tooling however is fantastic for doing so.  Babel is the preferred transpiler. Babel works best with Webpack as Webpack provides the module syntax and bundling.  In this instance I would recommend going this route as the combination provides a great deal of power.  It would also make contributing to WooCommerce more attractive to JS developers.  Working with ES5 littered with jQuery is not a lot of fun. ES6 is now referred to as ES2015 as they intend to add new features every year.  Using Babel you would not necessarily be writing ES6, through configuration you choose what features you want to allow.  I recommend not allowing to many cutting edge features as it is unsure if they will eventually make it into the browser.  `env` is a good place to start.

Overall migrating to modules and ES* can be done gradually.  ES5 compiles to ES5 quite nicely.  The thing you have to be careful of is scoping globals which can be difficult to diagnose.

> With this new build system, it would make it much easier to work on scalable UI. Maybe even integrate a JS framework like React or VueJS in the future.

This may be a good fit in the wp-admin but on users' front end sites I would recommend against any other than the minimum js required to make the site work.

One last note is that modules making JS testing much easier. Not sure where JS testing currently sits.

**Comment by mikejolley** [comment]
Moved these tasks to a single issue https://github.com/woocommerce/woocommerce/issues/18395
