### ISSUE TITLE
Update order status (AJAX)

### ISSUE THREAD

**Issue by MajkieS** [woocommerce/woocommerce#18373]
Hey,

as of Woocommerce v3.3 the order screen is redesigned. Well done! According to this, I have a little question maybe a little tip for improvement.

on a slower VPS running woocommerce, thus the php script timeout is 60 seconds we experience this issue: When we click 20-30 orders to process, it does only a small part of it, then the hosting strips that script and error 500 pops up. (Because processing orders takes long when editing more of them on one click)

Maybe when choosing more orders and changing their status is ajaxified - solves this issue?. Or adding a button to complete the order that is ajaxified.

The same happens when you update Wordpress plugins, it is ajaxified and for a good reason.

Thanks for advices.

**Comment by claudiulodro** [comment]
Glad you like the new screen! Thanks for the feedback.

The bulk edit uses the WP core bulk edit used everywhere in WP (Posts, Pages, activate/deactivate plugins, etc). To ajaxify it we would have to implement a completely new, custom bulk edit different from the WP bulk edit. If you can convince the WP core team to implement an ajax bulk editor that would solve the issue, but I don't think it makes sense for WooCommerce to develop and maintain a separate bulk editor.
