### ISSUE TITLE
Woo Rest API - Order status change from Processing to Completed throws error

### ISSUE THREAD

**Issue by sumudumathew** [woocommerce/woocommerce#18377]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Using the Woo REST API ,
1. Create a customer using a non-existent email address. e.g.: james@gmail.com
2. Create an order for this customer with status 'processing'
3. Change order status to 'completed'
This was only observed for the order transition 'processing' -> 'completed'

## Expected/actual behavior

When I follow those steps, I see...
{
    "code": "registration-error-invalid-email",
    "message": "Please provide a valid email address.",
    "data": {
        "status": 400
    }
}
I was expecting to see...
Customer response with updated status to 'processing'

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
@sumudumathew Show your API requests. I want to see how you're creating orders for the customer. I don't see why registration would trigger.

Also provide the system status report as requested - plugins can interfere with the API.

**Comment by sumudumathew** [comment]
Mike, thanks for your response. The reason for this behaviour is because the user is not a member of that site and would only happen in a multisite environment. Note: I have turned off all other plugins. 

See below,

1. Environment: Multisite environment; Structure: Primary site and 2 sub sites (Site X and Y)

2. User 1 is a member of Primary site but is not a member of site X

3. Using the Woo Rest API create an order for Site X
{
	"customer_id": 1,
	"status": "processing",
        "line_items":[  
        {  
             "product_id":"13",
             "quantity":1
       }
       "payment_method": "bacs",
	"set_paid": "true"
}

4. Set order to completed
{
	"status": "completed"
}

6. Strangely this only happens when the order is transitioning from processing to completed

**Comment by mikejolley** [comment]
Pretty important piece of information there you missed out before :P Thats why we ask or system status. I'll check the multisite handling code.

**Comment by mikejolley** [comment]
Because the user is not part of the site, it tries to create a new user which fails because the email is already taken.

The user needs to be part of the site having the order. I'm adding a new error to the API to flag this and prevent it occurring.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18413
