### ISSUE TITLE
Bulk Edit price sets the price to 0

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#18381]
#886315-zen

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Select some products to Bulk Edit
2. Increase the price by %

## Expected/actual behavior

When I follow those steps, I see the price set to 0.

I was expecting to see the price increased by 50%.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
@claudiulodro and I were unable to reproduce a `0` bug. Percent increases and decreases work in both master and 3.2.5.

Looking at the ticket, the user is likely trying to decrease/increase the prices of variable products, which is a scenario we don't support. As it's bulk edit, the form cannot be changed based on product type. This is a UI problem we'll look at when we refactor how variations and variable products function. 

Grouped products are also not editable in this way (they also have no price).

Thanks
