### ISSUE TITLE
Load WC Smoothness jquery CSS Async

### ISSUE THREAD

**Issue by stevewest15** [woocommerce/woocommerce#18386]
Hello,

Are there any plans to load this external CSS async so it's not render-blocking:

`http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.min.css`

Here is a screenshot from Google Pagespeed about the above CSS render-blocking:
https://www.screencast.com/t/drlaAVd0

I saw where /wp-content/plugins/woocommerce/includes/admin/class-wc-admin-assets.php loads this CSS but not sure how to deregister and/or dequeue it from loading.

Thx,

SW

**Comment by mikejolley** [comment]
`https://developer.wordpress.org/reference/functions/wp_script_add_data/` can be used if this is anything to go by: https://core.trac.wordpress.org/ticket/12009

Style handle is here https://github.com/woocommerce/woocommerce/blob/d14d3afc2ea8047b0f7c56b435fc4526ef46bc2c/includes/admin/class-wc-admin-assets.php#L43

**Comment by stevewest15** [comment]
Thank you Mike! Will look into those docs.
