### ISSUE TITLE
Customer cannot pay for seller-prepared orders when there is no stock

### ISSUE THREAD

**Issue by tatus1969** [woocommerce/woocommerce#18399]
The situation: I have some spare parts that I want to sell to a specific customer through the Woocommerce shop (WC 3.2.6, WP 4.9.1).

I do not want to add stock to the shop items because I do not want to risk others buying these items. Hence, I manually create an order for this customer and add the respective items.

The customer receives a link to his order, and clicks "Pay" and wants to pay (installed gateways: Paypal express and Stripe).

Instead of being able to check out, he receives an error message instead, saying that the items are out of stock. This is not the intended behavior in this case.

I went through the effort of increasing the stock for each item, and asking the customer to check out quickly. This worked out well, so there don't seem to be other problems.

**Comment by mikejolley** [comment]
No solution for this right now; it's not supported. I've added this to the list of ideas in https://github.com/woocommerce/woocommerce/issues/13359 so it can be manually skipped.

**Comment by therealgilles** [comment]
This functionality used to work (at least a year ago), so this is a newly created problem.
