### ISSUE TITLE
Autofill email field on checkout with logged in users email only.

### ISSUE THREAD

**Issue by vivinblack** [woocommerce/woocommerce#18394]
I have setup my woocommerce  store to sell a password to my vimeo video . For this sending emails is more important factor. I forced customer to log in to site  first before purchasing . My checkout filed has an email field . sometimes log in user misspelled their email address in email field and no email was sent, as woocommerce sends email to "checkout field email" & not the "site logged in email" address. Is there any plugin or manual method to send purchase emails to their site logging email address only.

**Comment by mikejolley** [comment]
We require this field. It will populate with the users email until filled out. We cannot really code around user error however.

This will likely help in the future https://github.com/woocommerce/woocommerce/issues/16677
