### ISSUE TITLE
WC Order Preview CSS break word fix

### ISSUE THREAD

**Issue by miniMAC** [woocommerce/woocommerce#18392]
There is a small bug with long email address.
<img width="543" alt="email_problem" src="https://user-images.githubusercontent.com/1235741/34714826-ebffb3e8-f52a-11e7-81a7-f8777a3ded30.png">

My suggestion is to add the` word-wrap: break-word;` in _admin.css_. The result is:

```
.wc-order-preview .wc-order-preview-addresses .wc-order-preview-address {
    width: 50%;
    float: left;
    padding: 1.5em;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    word-wrap: break-word;
}
```
<img width="529" alt="email_problem_resolved" src="https://user-images.githubusercontent.com/1235741/34714963-5c05cf38-f52b-11e7-9dba-a166ad308aaf.png">

**Comment by mikejolley** [comment]
@miniMAC Do you want to send this in a PR?
