### ISSUE TITLE
Filter by empty brand in products

### ISSUE THREAD

**Issue by Mapteg34** [woocommerce/woocommerce#18403]
I have wp 4.8.4 and woocommerce 3.2.3.

In wp-admin Products page i have filter "select a brand" filter. But that has brands with 1 or more products, empty brands without products) not present in this filter. How to add this brands to this filter?

**Comment by mikejolley** [comment]
We don't help with customisations here or deal with extensions. Use the helpdesk if you're using brands extension. Thanks.
