### ISSUE TITLE
Billing fields missing in checkout

### ISSUE THREAD

**Issue by rialjo** [woocommerce/woocommerce#18402]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Billing fields are marked as 'Enabled' in Checkout Field Editor Pro, yet do not appear on the checkout form. Only First Name, Last Name, Phone & Email are visible

## Expected/actual behavior

When I follow those steps, I see...
Mark the required fields as 'Enabled' using Checkout Field Editor Pro

I was expecting to see...
Selected fields visible at checkout, however only the 4 mentioned were.  This issue still occurs if the Checkout Field Editor Pro plugin is disabled

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
This is not the right place to ask questions about `Checkout Field Editor Pro`. Thats a separate plugin.
