### ISSUE TITLE
edit variable product - variation markup h3 customization possibility

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce#18407]
Hiya,

Before https://github.com/woocommerce/woocommerce/issues/13085 rolls out at some point in the future, I was wondering if we could have a filter / action someplace in the header part of the variations, like so:

![image 2018-01-10 at 12 01 45 am](https://user-images.githubusercontent.com/1196299/34749488-9bbb4ee6-f599-11e7-86c4-f5eac8a4e710.png)

The caveats:

* what if user is on a mobile device and there's not much space?
* what if there are 24 attributes that are used for variations?
* if it's an action, it should be made clear that elements that don't go within an `h3` will be stripped (`wp_kses` is awesome at that)
* can we filter the product id instead?

Currently that markup is called from `class-wc-ajax.php`, methods `add_variation` and `load_variations`.

The template is not something we can override, as it's a PHP `include` ~~call~~ statement instead of the usual `wc_get_template`.

## Prerequisites

It's not an issue, but a feature request, but I did search.

**Comment by javorszky** [comment]
Relevant code: https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-variation-admin.php#L15-L49

**Comment by mikejolley** [comment]
@javorszky The UI should be getting a good look at this year - perhaps a temp solution would be to append content with JavaScript? It all requires JS anyway.

**Comment by claudiosanches** [comment]
Better leave it when we will updating this interface, because maybe we not even will be listing variations like we are today.
Closing for now, but we will consider it when time comes.

**Comment by javorszky** [comment]
Awesome, thank you both! It'll be javascript for now
