### ISSUE TITLE
unpaid/pending order not getting cancelled automatically.

### ISSUE THREAD

**Issue by buyacsgo** [woocommerce/woocommerce#18416]
Hello I'm using woocommerce version 2.5.5 with later version of wordpress. From yesterday I'm facing this issue, I didn't made any changes but still having issue. Sometimes order getting cancelled after 10-12 minutes and sometimes not. I have set Hold stock (for unpaid orders) for 2 minutes to check.

I thought due to cache plugin it's causing issue, so I have disabled W3 Total Cache and also disabled autoptimization.

I have also contacted hosting about this. Please help me...

**Comment by claudiosanches** [comment]
>  I'm using woocommerce version 2.5.5 with later version of wordpress

Better update all, 2.5.5 is not maintained anymore.

**Comment by buyacsgo** [comment]
I'm unable to update due to enfold "ADD TO CART" issue. Everything was working fine but suddenly what happened yesterday. I just wanted to know.. please help

**Comment by claudiosanches** [comment]
@buyacsgo Enfold should be already updated, not to mention that you can also find a better theme, if still is not updated.

**Comment by buyacsgo** [comment]
I'm currently using "Theme Version Number is 3.5.4" I didn't update woocommerce and also didn't update theme yet due to some reason. but why suddenly I'm facing this issue from yesterday ? is that due to server side issue ?

**Comment by claudiosanches** [comment]
As I said, without updating, I have no idea.
