### ISSUE TITLE
wc_notice_count doesn't return the correct notice count for all notices

### ISSUE THREAD

**Issue by obiPlabon** [woocommerce/woocommerce#18412]
I've created the notices in the following way. It was supposed to return 6 for the first run but I was getting 9

``` php
wc_add_notice( 'Success 1' );
wc_add_notice( 'Success 2' );

wc_add_notice( 'Error 1', 'error' );
wc_add_notice( 'Error 2', 'error' );

wc_add_notice( 'Notice 1', 'notice' );
wc_add_notice( 'Notice 2', 'notice' );

echo '<pre>';

echo 'Number of notices: ' . wc_notice_count();

echo '<hr>';

$n = wc_get_notices();
print_r( $n );

echo '</pre>';
// wc_clear_notices();
```

Here's the output of 2nd run (when it's supposed to return 12):
![wc-notice-bug-output](https://user-images.githubusercontent.com/10244644/34772491-42c5f824-f632-11e7-8c4f-b5980314be2b.png)

Thanks

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18414
