### ISSUE TITLE
WC CLI undefined $format issue

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#18418]
I have gone through `shop_order` cli command and I got undefined `$format` error for this command `wp wc shop_order get 146` but for this `wp wc shop_order get 146 --format=table
` all okay and I think `--format` is optional isn't it? 

![capture](https://user-images.githubusercontent.com/3774827/34790634-6be007bc-f66a-11e7-83e0-56f55bfe3695.PNG)

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18420
