### ISSUE TITLE
Bulk Price Change not working for comma values

### ISSUE THREAD

**Issue by kodeoagency** [woocommerce/woocommerce#18426]
Hi,
I'm using the current WooCommerce version 3.2.6 and WordPress 4.8.4 (german language)
If I try to bulk edit product prices it's not working for comma/cent values.
Changing prices to 100 would be no problem, but if I enter cent values like 100,10 or 100.10 it's not working and they will be ignored.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18427
