### ISSUE TITLE
How to remove order item meta from my account order view page.

### ISSUE THREAD

**Issue by unitedsol** [woocommerce/woocommerce#18429]
I want to remove the order item meta from my account order view page and i didnot get any hook to remove this can some one help.

https://ibb.co/kX5fWm image link

**Comment by mikejolley** [comment]
Github is our bug tracker, not a place to get product support.

If you need help with core, use our [support forum](https://wordpress.org/support/plugin/woocommerce).

FWIW there is a hook to exclude meta by name. woocommerce_hidden_order_itemmeta
