### ISSUE TITLE
Calculating get_discounted_price_in_cents not always returns proper value

### ISSUE THREAD

**Issue by mikalai-okun** [woocommerce/woocommerce#18422]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product with price 9.95, and place it into the cart. 
2. Create a coupon with 100% cart discount.
3. Apply it.

## Expected/actual behavior

When I follow those steps, I see that the discounted amount is 9.94 and user still have to pay 0.01.

I was expecting to see full discount of 9.95

## Isolating the problem

This bug is not directly related to Woocomrce, but we can fix this PHP bug
- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## Proposed solution
You guys are using the Wodpress function **absint()**, which is not the best fit for e-Commerce needs, as it implements abs(inval()), when intval() works a bit off, you can find examples in the documentation http://php.net/manual/en/function.intval.php and this reported bug: https://bugs.php.net/bug.php?id=49187 a while ago with the similar issue.

Not sure if you will accept that, but I can propose a temp. solution to convert values to string first to avoid such instances.

```
public function get_discounted_price_in_cents( $item ) {
    return absint( strval($item->price - $this->get_discount( $item->key, true )) );
}
```

**Comment by mikejolley** [comment]
How about switching this to `round`? I don't think we should cast to string because PHP does some weird things to strings and floats when not using `.` as the decimal in the system locale.

**Comment by mikalai-okun** [comment]
Looks like round() should do the trick.

**Comment by mikejolley** [comment]
@mikalai-okun Do you want to send another PR?

**Comment by mikalai-okun** [comment]
Yes, In a moment.

**Comment by mikalai-okun** [comment]
[PR](https://github.com/woocommerce/woocommerce/pull/18432) created.

**Comment by mikejolley** [comment]
Thanks, I'll check https://github.com/woocommerce/woocommerce/pull/18432
