### ISSUE TITLE
Checkout fields priority not working correctly 

### ISSUE THREAD

**Issue by tzvir** [woocommerce/woocommerce#18425]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add code to functions.php attempting or modify form-billing.php to achieve the following  order

billing_first_name
billing_last_name
billing_email
billing_phone
billing_city
billing_address_1
billing_postcode
billing_country

## Expected/actual behavior

The city is not ordered correctly 

The priority field gets the right value but the fields are not ordered by that value

## Isolating the problem

- [ X] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://www.test.10bit.co.il
Site URL: http://www.test.10bit.co.il
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2
PHP Version: 5.6.32
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.57.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.05MB
Database Data Size: 0.51MB
Database Index Size: 0.54MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.15MB + Index: 0.03MB
wp_postmeta: Data: 0.02MB + Index: 0.02MB
wp_posts: Data: 0.00MB + Index: 0.01MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 1
page: 5
post: 2
product: 3
shop_order: 4

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3.0-beta.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`</details>

**Comment by mikejolley** [comment]
Some of the address fields, city for instance may be changed by the locale so using a later hook to set priorities would be needed. Since you've not shown the code you're using I cannot verify but I'm pretty sure thats the case here.

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-countries.php#L714-L1166

**Comment by tzvir** [comment]
I tried 2 solution  :

Solution #1 form-billing.php

<div class="woocommerce-billing-fields__field-wrapper">
        <?php
        // order the keys for your custom ordering or delete the ones you don't need
        $mybillingfields=array(
            "billing_first_name",
            "billing_last_name",
            "billing_email",
            "billing_phone",
            "billing_city",
            "billing_address_1",
            
//            "billing_company",
            
//            "billing_address_2",
            
//            "billing_state",
            "billing_postcode",
            "billing_country",
            
            
        );
        foreach ($mybillingfields as $key) : ?>
            <?php woocommerce_form_field( $key, $checkout->checkout_fields['billing'][$key], $checkout->get_value( $key ) ); ?>
        <?php endforeach; ?>
	</div>

-----------------------------------

Solution #1 functions.php

add_filter("woocommerce_checkout_fields", "woocommerce_billing_fields_custom", 999, 1);

function woocommerce_billing_fields_custom($fields)
{

    if (current_user_can('editor') || current_user_can('administrator')) {

        $fields['billing']['billing_first_name']['priority'] = 10;
        $fields['billing']['billing_first_name']['class'] = array('form-row-first');

        $fields['billing']['billing_last_name']['priority'] = 20;
        $fields['billing']['billing_last_name']['class'] = array('form-row-last');
        $fields['billing']['billing_last_name']['clear'] = true;

        $fields['billing']['billing_email']['priority'] = 30;
        $fields['billing']['billing_email']['class'] = array('form-row-first');

        $fields['billing']['billing_phone']['priority'] = 40;
        $fields['billing']['billing_phone']['class'] = array('form-row-last');
        $fields['billing']['billing_phone']['clear'] = true;

        $fields['billing']['billing_city']['priority'] = 50;
        $fields['billing']['billing_city']['class'] = array('form-row-last');

        $fields['billing']['billing_address_1']['priority'] = 60;
        $fields['billing']['billing_address_1']['class'] = array('form-row-first');
        $fields['billing']['billing_address_1']['clear'] = true;

        $fields['billing']['billing_postcode']['priority'] = 70;
        $fields['billing']['billing_postcode']['class'] = array('form-row-last');

        $fields['billing']['billing_country']['priority'] = 80;
        $fields['billing']['billing_country']['class'] = array('form-row-first');
        $fields['billing']['billing_country']['clear'] = true;

        unset($fields['billing']['billing_company']);
        unset($fields['billing']['billing_address_2']);
        unset($fields['billing']['billing_state']);

    }
    return $fields;

}

**Comment by tzvir** [comment]
please disregard the "class" (from 50 and above ) , it was added to align the display when the bug appears

**Comment by mikejolley** [comment]
Change country to Belgium - if the fields don't reorder, the script is likely not running.

**Comment by trgino** [comment]
wc_address_i18n_params

**Comment by juancpgo** [comment]
@tzvir Your solution #2 doesn't work for me. It changes the value of the `data-priority` attribute of the fields, but it doesn't actually reorder them.

Any ideas?

**Comment by vinigarcia87** [comment]
Guys, I have the same problem...  if you remove the `wc-chekout` script, the problem goes away:

```
// Add this to your functions.php
function storms_disable_scripts() {
    wp_dequeue_script( 'wc-checkout'  );
}
add_action( 'wp_enqueue_scripts', 'storms_disable_scripts' );
```

I'm trying to understand what is going on with this script. Maybe someone from the dev team can help us out?

**Comment by kj-ivy** [comment]
I ran into the same problem.

The solution I found was to use the `wc_address_i18n_params` filter to change the priority for each locale:

```php
add_filter( 'wc_address_i18n_params', function($params) {
	$locales = json_decode($params['locale'], true);
	foreach($locales as &$locale) {
		if (isset($locale['postcode'])) {
			$locale['postcode']['priority'] = 55;
		}
	}
	$params['locale'] = json_encode($locales);
	return $params;
});
```

This modifies the data used by `address-i18n.js`/`address-i18n.min.js` which is the script that's doing the client-side reordering.

**Comment by janez33** [comment]
Filter `wc_address_i18n_params` doesn't work.

To override country/locale specific field priorities specified in `class-wc-countries.php` you should use filter below. Tested and works!

```
add_filter('woocommerce_get_country_locale', 'cambia_localizacion_cl');
function cambia_localizacion_cl($localizacion){
  	$localizacion['CL']['city']['priority'] = 120;
    	$localizacion['CL']['address_2']['priority'] = 140;
  	$localizacion['CL']['last_name']['priority'] = 50;
	return $localizacion;
}
```
