### ISSUE TITLE
checkbox for terms and conditions on check out page is not working. Theme author has disappeared, something to do with the woocomerce update i hear?

### ISSUE THREAD

**Issue by Figgos** [woocommerce/woocommerce#18428]
Website - figgos.com/checkout 

when clicking the check box for accepting the terms and conditions it its not doing anything. Therefore customers cannot proceed with payment, any help would be appreciated. Thank you

**Comment by mikejolley** [comment]
Either;

- Get an updated version of the theme from the author
- Switch themes
- Disable the terms/conditions page in WC > Settings > Checkout.

Note this is not a support forum and we don't support 3rd party code here.

**Comment by Figgos** [comment]
the theme author has disappeared and ive spent forever building the site. Is there anyway i can transfer all documentation on to another theme? Thank you for the fast reply.

**Comment by mikejolley** [comment]
Documentation?
