### ISSUE TITLE
WooCommerce Search throwing all results

### ISSUE THREAD

**Issue by abhibavishi** [woocommerce/woocommerce#18431]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. In the latest WooCommerce version, I'm not able to search products with the following URL: https://smartify.in/wp-json/wc/v2/products?search=xxxxxx&consumer_key=xxxxxxxxxxxx&consumer_secret=xxxxxxxxxx&oauth_signature=undefined. I have looked up the documentation, here: http://woocommerce.github.io/woocommerce-rest-api-docs/#pagination and couldn't find a way to make ti work. Strangely, all API calls are working, except search.  

## Expected/actual behavior

When I follow those steps, I see...

... all the products on my store, 

I was expecting to see...

... only the product that I searched. 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Unable to replicate this one on master or 3.2:

![insomnia products 2018-01-11 13-37-36](https://user-images.githubusercontent.com/90977/34828233-cb21e316-f6d4-11e7-9090-acb7860fb2c0.png)

Try a client with proper auth rather than querystring auth, and rule out plugin conflicts and caching if you have not already.
