### ISSUE TITLE
Multiple tabs cause infinite loop of get_refreshed_fragments AJAX calls

### ISSUE THREAD

**Issue by olitooni** [woocommerce/woocommerce#18434]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1) In Chrome, open up a tab and go the webshop using a fresh session (not logged in) and add a product to the cart. Go to the cart. Leave this tab like this.
2) Open up a second tab with the same webshop and just go to the startpage. Leave it.
3) Open up a third tab, login to the webshop, go to the cart. If you monitor the "Network" tab in Developer Tools in Chrome you can see flood of AJAX calls being made against _/?wc-ajax=get_refreshed_fragments_.

## Expected/actual behavior

When I follow those steps, I see that all the tabs are making AJAX calls to the route _/?wc-ajax=get_refreshed_fragments_ again and again with no sleep in between. 

After some investigation I noticed that there is an event listener on the event 'onstorage' in the file _cart-fragments.js_. When I have multiple tabs it seems like the listeners from the different tabs get into a race condition changing the cart hash value in _localStorage_ and _sessionStorage_ back and fourth. I made some modifications on my local woocommerce install and added a lock for the cart hash to fix this: 

```javascript
$( document.body ).on( 'wc_fragments_refreshed', function() {
    if ( $supports_html5_storage ) {
        localStorage.removeItem('cart_lock');
    }
    clearTimeout( cart_timeout );
    cart_timeout = setTimeout( refresh_cart_fragment, day_in_ms );
} );

// Refresh when storage changes in another tab
$( window ).on( 'storage onstorage', function ( e ) {
    if ( cart_hash_key === e.originalEvent.key && localStorage.getItem( cart_hash_key ) !== sessionStorage.getItem( cart_hash_key ) ) {
        if (!localStorage.getItem('cart_lock')) {
            localStorage.setItem('cart_lock', 1);
            refresh_cart_fragment();
        }
    }
});
```

I was expecting to see that _/?wc-ajax=get_refreshed_fragments_ was only called once per tab when the cart hash is changed.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by WillBrubaker** [comment]
I tried to reproduce this with the listed steps and I do not experience that behavior. I see the two checkboxes haven't been checked:

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://wordpress.org/themes/storefront/)

Nor is there a system status report showing the version of WooCommerce in use.

**Comment by mikejolley** [comment]
@WillBrubaker 👍 I was about the post the same. I see one XHR request on the cart page after logging in and thats it.

**Comment by olitooni** [comment]
I'll try to reproduce it on Storefront and get back to you...

**Comment by olitooni** [comment]
You're right. I only tried this at our own site and it has a lot of custom stuff and third party plugins.  I'll try to make a clean install of a new Wordpress site and see if the problem is still there.

**Comment by Eigilak** [comment]
Any status with the above?

**Comment by jonathan-dejong** [comment]
@olitooni I'm also curious wether you resolved the issue with a clean install?

I have a site where this exact behaviour occurs. Essentially with multiple tabs open, when adding a product in one tab, it causes some kind of race condition where the tabs keep sending requests to get_refreshed_fragments with 2 different cart_hash values over and over. 
The issue seem to escalate the more tabs I have open. 

After WC 3.7.0 and specifically these changes:
https://github.com/woocommerce/woocommerce/pull/23293
I see some improvements where it stops after ~5-10 requests in each tab. Previously it would continue until I closed a few tabs.

So if I had say 6 tabs open it would start iterating requests and if I started closing down tabs it would stop after closing maybe 2-3 of them. So the issue is definitely with the storage event check!

The site *does* have a fair  amount of plugins etc. but I can't find anything that would relate to these functions after extensive searching through the code. 

I'd be happy to open a new ticket if necessary :)

**Comment by olitooni** [comment]
@jonathan-dejong Yes a clean install solved the issue. Right now i'm on parental leave and can't access out repository and I can't really recall how I fixed the bug. But I remember there was some issue with our custom code that caused the race condition.
