### ISSUE TITLE
Automatic tax amount is incorrect

### ISSUE THREAD

**Issue by DeltaMarktonderzoek** [woocommerce/woocommerce#18433]
When setting "enable automated taxes" the automatically calculated tax amount is incorrect. It is 21% of the total amount incl. tax, instead of 21% of the total amount excl. tax. 
Example:
Product incl. tax costs €12,50; tax amount should be €2,17.
Woocommerce now shows the incorrect amount of €2,63.
Don't know how to alter this, but need to mention tax amoumts correctly on invoices and emails.

**Comment by mikejolley** [comment]
This is a service, not core, so we'll need to do investigation on the account and will need more information about your install.

Please log an issue on the helpdesk so that can happen.

https://woocommerce.com/my-account/tickets/

Thanks
