### ISSUE TITLE
error postman request, using OAuth 1.0 authentication, without passing the Consumer Secret in the url according to the documentation

### ISSUE THREAD

**Issue by guilherme-oliveria** [woocommerce/woocommerce#18443]
the postman does not access my API passing the documentation parameters, I need to add the consumer_secret and remove "oauth_" from both the consumer_secret and consumer_key, in my java application, using the unofficial repository I had to add also, "[https://github.com/icoderman/wc-api-java](url) ", and is it safe to do so or not?
imagem error
[https://uploaddeimagens.com.br/imagens/erro-png--724](url)
imagem confirm
[https://uploaddeimagens.com.br/imagens/certo-png--28](url)

**Comment by mikejolley** [comment]
I don't think you've followed the instructions fully.

Over https follow the instructions https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-https You can use headers or `?consumer_key=123&consumer_secret=abc`

The oauth_ params are for requests over http only. https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http 

Common causes of 401 are listed in https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

As for the library, we don't support it and have not vetted it. Make sure you do so before using it in a project.

**Comment by guilherme-oliveria** [comment]
@mikejolley 
ok, about not supporting and why is java rsrsrs, java> php

**Comment by claudiosanches** [comment]
@guilherme-oliveria we don't support because is a 3rd party library.
