### ISSUE TITLE
Clear Customer Sessions Clarification

### ISSUE THREAD

**Issue by joelwills** [woocommerce/woocommerce#18447]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Under WooCommerce > Status > Tools there is an option for "Clear customer sessions
Note: This tool will delete all customer session data from the database, including any current live carts."
2. However this only clears carts for logged out customers and not logged in customers

## Expected/actual behavior

When I follow those steps, only logged out customer carts are emptied

I was expecting that either logged in customer carts also to be emptied OR the text should state it only affects non-logged in customers more explicitly. 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
We could clear persistent carts too.

**Comment by MattMangoni** [comment]
Tbh, I think it makes perfect sense to clear only logged out customer carts :)

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18492
