### ISSUE TITLE
Large number string showing up in stead of Stock Variation number

### ISSUE THREAD

**Issue by Danieljit** [woocommerce/woocommerce#18441]
So after i updated Woocommerce i noticed that the variations of stock in the different shoe sizes didn't portray the actual number anymore. In stead i get this long string of letters and numbers 
{f83ca626cdd194696bcc42d4ae15d386bb2fcc826c640453c46057c6c7e01e9e}s 

When there are 3 or more in stock it does say the correct number. Below that it would give me this string.

The website is in dutch. The German version also has the problem. The english one however seems fine.

Anybody have any experience with this?
## Steps to reproduce the issue

1. Just click the link
2. https://shop.wearewunderbar.nl/product/asics-lyte-burgundy/
3. And choose a shoesize

**Comment by mikejolley** [comment]
Github is our bug tracker, not a place to get product support. We also require that you perform the steps listed on https://github.com/woocommerce/woocommerce/issues/new to isolate the problem and provide the details we need to reproduce the issue.

In this case, I'm certain it will be a plugin responsible for this. Your variation form is custom - core uses dropdowns.  This will not be a core bug.

Thanks
