### ISSUE TITLE
BOOK NOW Button dont working :(

### ISSUE THREAD

**Issue by aminefederal** [woocommerce/woocommerce#18445]
Hey Guys , idont know why my button Book now dont working and its showing as a stop sign , you can see a exemple here :
http://badiricar.com/?product=bentley-2018
Please if anyone know how to fix it write me please

**Comment by claudiulodro** [comment]
It looks it probably wasn't set up properly, but I can't help you troubleshoot it. GitHub is only for bugs in the WooCommerce core plugin and not for support with WooCommerce extensions like Bookings. I recommend [opening a support ticket](https://woocommerce.com/my-account/tickets/) and they should be able to help you out.

Cool cars!
