### ISSUE TITLE
3.3 Image Size improvment

### ISSUE THREAD

**Issue by Nugrah** [woocommerce/woocommerce#18453]
Hi, i see on the 3.3 Version you can setting up Thumbnail Cropping by customizer, but after i added `add_theme_support( 'woocommerce', array(
'thumbnail_image_width' => 150,
'single_image_width' => 322,
) );`

into functions.php, i don't see any option appear for it in customizer, do i must set anything else to make it appear?

Thank you

**Comment by WPprodigy** [comment]
This article will help explain a bit: https://woocommerce.wordpress.com/2017/12/11/wc-3-3-image-size-improvements/

> With WooCommerce 3.3 theme authors can now declare image sizes via the add_theme_support function. Declaring image sizes this way will take priority over any other settings and also **hide the image settings section** in the admin area.

So you declaring an image size via the theme support function ends up hiding the setting.

**Comment by Nugrah** [comment]
so there is no option if we want to use customizer for image and page display and still adding add_theme_support( 'woocommerce' ); ?

**Comment by mikejolley** [comment]
You don't need both; either define it for your users, or let them decide.
