### ISSUE TITLE
[3.3 RC] Application authentication cancel link formatting broken

### ISSUE THREAD

**Issue by bryceadams** [woocommerce/woocommerce#18451]
When going to the application authentication screen in 3.3, the cancel link isn't formatted properly.

<img width="746" alt="screen shot 2018-01-12 at 11 50 33 am" src="https://user-images.githubusercontent.com/1532482/34854625-d1c2cdb0-f78e-11e7-833a-2df8ce52190b.png">

To replicate, add the following to the URL of a 3.3 RC site (you can change any of the parameters):

```
/wc-auth/v1/login?app_name=Metorik&user_id=ij13io2j3o21i3o&return_url=http%3A%2F%2Fmetorik-app.test%2Fadd-a-store&callback_url=http%3A%2F%2Fmetorik-app.test%2Fconnect%2Fincoming&scope=read_write
```

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18459
