### ISSUE TITLE
checkout.js cannot validate if a radio is selected

### ISSUE THREAD

**Issue by alucard001** [woocommerce/woocommerce#18454]
## Situation:
Our client's checkout form has a radio list of salutation (Mr, Mrs, Ms etc) and have a default value of **Mr**.  

## Problem:
Now because some of their customers ignore this setting and submit the form with incorrect salutation, my client wants to set this field to have NO default value, which means if a user submits a checkout form, a validation is run to see if a value is selected.

However, upon reviewing this file: `woocommerce/assets/js/frontend/checkout.js`, on `LN 194-202`, you can see that it will only check if a 'checkbox' is checked, if it is not a checkbox, it will only test if a value is persisted.

## As a result...
Since radio always has value, the validation is always true and in other words, if a user submits the form without selecting a radio box, the CSS class `woocommerce-invalid woocommerce-invalid-required-field` will not be added, even though I can successfully show a woocommerce error that this field did not have value.

Without these 2 classes, I cannot assign CSS style to it.

## Version info:
- Wordpress: 4.9.1
- Woocommerce: 3.2.6

Can you please tell me how to hijack it?

Thank you very much

**Comment by mikejolley** [comment]
> Since radio always has value, the validation is always true and in other words, if a user submits the form without selecting a radio box

Radio buttons should have a default value. Thats the nature of radio buttons. Add a selected radio button with `''` value if you want it to validate here. That will match the `''` rule and throw a notice.

If it needs to be not-selected by default, you should be using a checkbox.
