### ISSUE TITLE
REST API strips newlines (\n) from external URL

### ISSUE THREAD

**Issue by alsobrsp** [woocommerce/woocommerce#18469]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Using the REST API python module
2. Concatenate a string with newlines (\n)
3. Add string to url options dictionary
4. Pass dictionary through urllib3.request.urlencode - http://urllib3.readthedocs.io/en/latest/user-guide.html
5. Concat encoded options with base URL
6. Add to product dictionary
7. Pass to Woo REST API
8. REST API returns invalid URL

## Expected/actual behavior

When I follow those steps, I see...
external_url: "http://dev.decadesofvinyl.com/contact-us/?your-subject=Pruduct+Inquiry&#038;your-message=Artist%3A+WingerAlbum%3A+WingerSKU%3A+189217240"

I was expecting to see...
external_url: "http://dev.decadesofvinyl.com/contact-us/?your-subject=Pruduct+Inquiry&your-message=%0A%0AArtist%3A+Winger%0AAlbum%3A+Winger%0ASKU%3A+189217240"

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://dev.decadesofvinyl.com
Site URL: http://dev.decadesofvinyl.com
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.0.19-1
PHP Post Max Size: 18 MB
PHP Time Limit: 240
PHP Max Input Vars: 1500
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.6.30
Max Upload Size: 18 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 59.99MB
Database Data Size: 45.70MB
Database Index Size: 14.29MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
dov_discogs_fields: Data: 0.02MB + Index: 0.00MB
dov_discogs_instances: Data: 1.52MB + Index: 0.08MB
dov_discogs_releases: Data: 1.52MB + Index: 0.08MB
dov_run_log: Data: 0.02MB + Index: 0.00MB
dov_sales_channels: Data: 0.22MB + Index: 0.08MB
dov_settings: Data: 0.02MB + Index: 0.00MB
dov_woo_attribs: Data: 0.02MB + Index: 0.02MB
dov_woo_attribs_tmp: Data: 0.02MB + Index: 0.02MB
dov_woo_instances: Data: 0.16MB + Index: 0.08MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_db7_forms: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.06MB + Index: 0.05MB
wp_postmeta: Data: 26.56MB + Index: 9.03MB
wp_posts: Data: 11.52MB + Index: 3.80MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 1.52MB + Index: 0.38MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_tinvwl_items: Data: 0.02MB + Index: 0.00MB
wp_tinvwl_lists: Data: 0.02MB + Index: 0.00MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wpmcleaner: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 14721
page: 9
post: 1
product: 3083
revision: 12
shop_order: 3
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (12) ###

WooCommerce Wishlist Plugin: by TemplateInvaders – 1.5.14
JSON Basic Authentication: by WordPress API Team – 0.1
Contact Form 7: by Takayuki Miyoshi – 4.9.2
Contact Form CFDB7: by Arshid – 1.1.6
Media Cleaner: by Jordy Meow – 4.5.4
Storefront Product Sharing: by WooThemes – 1.0.4
WooCommerce Stripe Gateway: by WooCommerce – 4.0.1
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.5 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.10.0
WooCommerce: by Automattic – 3.2.6
WP-Piwik: by André Bräkling – 1.0.19
YITH WooCommerce Catalog Mode: by YITHEMES – 1.5.7 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Deli
Version: 2.0.10
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### TI WooCommerce Wishlist Templates ###

Overrides: –
`</details>

**Comment by mikejolley** [comment]
Confirmed it's esc_url. Since this is core to WordPress it's not something we can workaround or fix. Newlines are not allowed in external URLs.

As a workaround you should either avoid newline chars in URLs, or use a placeholder character which you can replace in your contact form code with a real newline character after the URL is hit.

cc @claudiosanches
