### ISSUE TITLE
webhooks seems to not send body content

### ISSUE THREAD

**Issue by hosnas** [woocommerce/woocommerce#18475]
I'm using the latest woocommerce and wordpres versions. turned off all plugins except for woocommerce and tried to issue a webhook trigerred by creating a product. However all I get in the body is webhook id.

https://hookbin.com/bin/vewDrY0G

More information are provided here:
https://wordpress.org/support/topic/woo-webhooks-dont-send-html-raw-body-content/

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

**Comment by WPprodigy** [comment]
Please install WooCommerce on a test site, with only the WooCommerce plugin installed along with a default WordPress theme. The make the "Customer created" webhook on this site.

Now open an incognito window and register a user from the My Account page. 

Go back to your admin account, view the webhook, and look at the logs. My test site had the following body:

`{"id":3,"date_created":"2018-01-14T05:53:53","date_created_gmt":"2018-01-14T05:53:53","date_modified":null,"date_modified_gmt":null,"email":"localtest@local.local","first_name":"","last_name":"","role":"customer","username":"localtest","billing":{"first_name":"","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":"","email":"","phone":""},"shipping":{"first_name":"","last_name":"","company":"","address_1":"","address_2":"","city":"","state":"","postcode":"","country":""},"is_paying_customer":false,"orders_count":0,"total_spent":"0.00","avatar_url":","meta_data":[]}`

As for what is in the payload, you can use this filter to add more data if needed: https://github.com/woocommerce/woocommerce/blob/e3331448e5524136d06c8382fb77032bc2ea5870/includes/class-wc-webhook.php#L357

**Comment by hosnas** [comment]
I followed your suggestions. However I got still nothing except webhook id in the body
https://hookbin.com/bin/vQQrbwpy

As for the filter, I didnt change anything. So I suppose defult data should be sent.
