### ISSUE TITLE
MaxMind GeoLite Legacy GeoIP databases discontinuation

### ISSUE THREAD

**Issue by alexminza** [woocommerce/woocommerce#18477]
[http://dev.maxmind.com/geoip/legacy/geolite/](http://dev.maxmind.com/geoip/legacy/geolite/)
> We will be discontinuing updates to the GeoLite Legacy databases as of April 1, 2018. You will still be able to download the April 2018 release until January 2, 2019. GeoLite Legacy users will need to update their integrations in order to switch to the free GeoLite2 or commercial GeoIP databases by April 2018.

<img width="926" alt="screen shot 2018-01-14 at 14 03 42" src="https://user-images.githubusercontent.com/149919/34915806-d31c3424-f934-11e7-8ae5-bedf1049ccf3.png">

One possible solution would be to migrate to the new APIs/packages provided officially by MaxMind if the quality/performance of the implementation is acceptable for WooCommerce: [https://dev.maxmind.com/geoip/geoip2/downloadable/#MaxMind_Supported_APIs](https://dev.maxmind.com/geoip/geoip2/downloadable/#MaxMind_Supported_APIs)

**Comment by kloon** [comment]
Just a note, this is only for GeoLite, not GeoLite2. We should be able to switch over to GeoLite2 without too much hassle. Also, we do have some API driven fallbacks in place already but for performance, it would make sense to keep a downloadable DB as the first option.

**Comment by mikejolley** [comment]
Yep let's switch. I think the only issue we'll have is making the library compatible with our min supported PHP version so we'll just need our own wrapper/class to deal with it.

**Comment by m-cameron** [comment]
For GeoLite2, Maxmind plans to discontinue the coordinates in 2019. 

Does WooCommerce has plan to support IP2Location LITE database for their free geolocation and proxy detection database?

**Comment by mikejolley** [comment]
No and this issue is purely about maxmind/non-API geolocation.

**Comment by kloon** [comment]
@m-cameron They are not discontinuing GeoLite2, only removing the long and lat from the DB in 2019, other information will still continue to be available.

**Comment by claudiosanches** [comment]
We can keep downloading the database, but from: https://dev.maxmind.com/geoip/geoip2/geolite2/
And use this library to read: https://github.com/maxmind/MaxMind-DB-Reader-php

But the library works only in PHP 5.4+.
We need to decide if we should rewrite this library or bump our PHP version to 5.4+.

**Comment by mikejolley** [comment]
@claudiosanches @warrendholmes Decision here is to include the library but use only if user has 5.4+. We will include a non-dismissable notice for old PHP versions to increase adoption.
