### ISSUE TITLE
Unable to filter product categories that are uncategorized.

### ISSUE THREAD

**Issue by doncooper** [woocommerce/woocommerce#18471]
Due to the changes made for filtering product filters, I'm unable to filter all "uncategorized" products.

Older versions of Woocommerce allowed for filtering of "uncategorized" products.

Please consider returning to the older way of filtering products or possibly add a feature to allow for the older type of filtering that was available in the older Woocommerce versions. 

Thank you for a great product!

Best Regards,

Don

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
It's part of 3.3 already.

**Comment by doncooper** [comment]
Mike,

That's great news!

Thank you very much!

Best Regards,

Don

**Comment by BallisticsMan** [comment]
So if this is part of 3.3 how do we get it to stop displaying? On my site if I click on the category nothing happens, yes as in ZERO. How can I roll back to the previous version to avoid this? Also there should be a way of deactivating unless you are forcing people to live with it.
