### ISSUE TITLE
Inappropriate error message when using protocol-relative URL for download

### ISSUE THREAD

**Issue by Shotster** [woocommerce/woocommerce#18474]
The issue occurs when saving a downloadable product having a protocol-relative URL. Specifically...

[This line](https://github.com/woocommerce/woocommerce/blob/dff5fefe738151e89148f308d811f1213ccbe468/includes/class-wc-product-download.php#L50) does not check for a protocol-relative URL and thus returns "relative", which causes [this condition](https://github.com/woocommerce/woocommerce/blob/dff5fefe738151e89148f308d811f1213ccbe468/includes/abstracts/abstract-wc-product.php#L1201) to evaluate to "true", thereby triggering an inappropriate error message that the file doesn't exist (when in fact it does).

Either an appropriate protocol-relative check should be done, **or** a more appropriate error should be displayed to discourage the use of protocol-relative URLs as described [here](https://jeremywagner.me/blog/stop-using-the-protocol-relative-url/).

This scenario could, for instance, be caused by the following line in **wp-config.php**:

`define( 'WP_CONTENT_URL', '//' . $_SERVER['HTTP_HOST'] . '/content' );`

WP seems to work just fine, in general, but choosing a file from the media library in that case inserts a protocol-relative URL into the downloadable product's **File URL** field. Saving the product then results in the URL not being saved and an error stating that the file doesn't exist:

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18488
