### ISSUE TITLE
[REST API] - If coupon exists update it just like in admin page

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#18480]
In coupons panel if the "test coupon" exists then creating and publishing a coupon with same coupon code updates the previous coupon with latest changes. But this same logic is missing in REST API portion.

**POST request:**
```
https://woocommerce.io/wp-json/wc/v2/coupons?code=test coupon&discount_type=percent&amount=30
```
### First attempt Response:

It successfully creates coupon if doesn't exist.
```
{
    "id": 130,
    "code": "test coupon",
    "amount": "30.00",
    "date_created": "2018-01-15T10:39:34",
    "date_created_gmt": "2018-01-15T10:39:34",
    "date_modified": "2018-01-15T10:39:34",
    "date_modified_gmt": "2018-01-15T10:39:34",
    "discount_type": "percent",
    "description": "",
    "date_expires": null,
    "date_expires_gmt": null,
    "usage_count": 0,
    "individual_use": false,
    "product_ids": [],
    "excluded_product_ids": [],
    "usage_limit": null,
    "usage_limit_per_user": null,
    "limit_usage_to_x_items": null,
    "free_shipping": false,
    "product_categories": [],
    "excluded_product_categories": [],
    "exclude_sale_items": false,
    "minimum_amount": "0.00",
    "maximum_amount": "0.00",
    "email_restrictions": [],
    "used_by": [],
    "meta_data": [],
    "_links": {
        "self": [
            {
                "href": "https://woocommerce.io/wp-json/wc/v2/coupons/130"
            }
        ],
        "collection": [
            {
                "href": "https://woocommerce.io/wp-json/wc/v2/coupons"
            }
        ]
    }
}
```
### Second attempt Response:

If same POST request is used it will say coupon code already exists. One question can we update coupon data instead for that coupon code like how coupon admin edit page does.

```
{
    "code": "woocommerce_rest_coupon_code_already_exists",
    "message": "The coupon code already exists",
    "data": {
        "status": 400
    }
}
```

**Note:** If the coupon is trashed then we are able to create coupon with same coupon code. Can it be possible to test trash coupon and display some notice either delete that coupon code to create new one OR restore that coupon code and update coupon data. 

- When I have created coupon code and trashed.
![capture](https://user-images.githubusercontent.com/3774827/34939055-9e6aa268-fa12-11e7-9dc7-24bb47a732ec.PNG)

- After I have created same coupon code and restored the trashed one.
![capture-1](https://user-images.githubusercontent.com/3774827/34939056-9eb23b46-fa12-11e7-96bf-76286d6856e5.PNG)

CC @claudiosanches @mikejolley

**Comment by claudiosanches** [comment]
But the second request is a POST?
If so, will try create instated of update, since should be a PUT request.
The same happens in all endpoints.

**Comment by shivapoudel** [comment]
@claudiosanches If I need to use PUT then ID is compulsary isn't it. Walk me through the steps if I am wrong and the main reason is that I need to check the coupon if doesn't exist then create else only update.

**Comment by mikejolley** [comment]
The admin page does not update the coupon.

Admin creates a duplicate coupon and gives a big warning:

> Coupon code already exists - customers will use the latest coupon with this code.

The API should not update coupons unless you provide the ID to update. Like any other endpoint. An error is correct handling.
