### ISSUE TITLE
View Products instead of View Posts

### ISSUE THREAD

**Issue by wpchannel** [woocommerce/woocommerce#18481]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

As reported on [w.org forum](https://wordpress.org/support/topic/view-products-instead-of-view-posts/#post-9865166), we should have products instead of posts in the admin bar like any other CPT.
<img width="152" alt="capture d ecran 2018-01-15 a 10 14 49" src="https://user-images.githubusercontent.com/7568562/34942035-67f5d9ee-f9f6-11e7-8201-fc60f42182a9.png">

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18484
