### ISSUE TITLE
[3.3RC1] PHP notice in WC_Admin_List_Table_Products

### ISSUE THREAD

**Issue by tobiasschutter** [woocommerce/woocommerce#18499]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Visit the Products list screen
2. PHP Notice: Undefined variable: vars `Undefined variable: vars in /wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-products.php on line 393`

## Expected/actual behavior

Solution: `$vars['orderby']` should be renamed to `$query_vars['orderby']`

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18517
