### ISSUE TITLE
Search function within WooCommerce doesn't work

### ISSUE THREAD

**Issue by inubyvtc** [woocommerce/woocommerce#18494]
The search function in woocommerce doesn't return any results at all even if the products or commands are there. Any solutions to this issue?

**Comment by dougaitken** [comment]
@inubyvtc can you provide screenshots and examples, please? 
Is this the front end of the site or the back admin area? 
Which search box are you using, what are you searching for?

**Comment by gigawattrdh** [comment]
I don't know if it's the same search box that @inubyvtc is using, but for me - when I'm viewing a particular order, there's an auto-complete field for "Customer:" -- and if I want to change the customer on that order, I am supposed to be able to type in some chars and have it pull up a list of other customers.  When looking at the network tab of the console, it says it's making a call like this:
.../wp-admin/admin-ajax.php?term=max&action=woocommerce_json_search_customers&security=....
And, oddly enough, it gives this kind of response to the ajax call:
`<script type="text/javascript">
function delete_coupon(coupon_id,id)
	 {
			var conform = confirm("Are you sure do you want to delete this record?");
				if(conform==true)
				{
					
					location.replace("admin.php?page=coupons_list&action=delete&coupon_id="+coupon_id+"&id="+id);
				}
				else
				{
					return false;
				}
	 }
</script>



{"2968":"A*****m P**y (#2968 &ndash; ---max01@g----l.com)","2909":"D****l L***a (#2909 &ndash; ------_max2@h------l.com)","3478":"Max**** G****v .....(etc,etc)"}`

(The names and expected results are coming up after a script block.  But the list on the front end just hangs with the word "Searching" and never populates the list...)

**Comment by gigawattrdh** [comment]
Nevermind my previous comment -- I had a plugin called "Coupon Generator" that was outputting that script code on every response and thus breaking woocommerce ajax calls!
