### ISSUE TITLE
[3.3 RC1] Update cart reloads page instead of using Ajax

### ISSUE THREAD

**Issue by JimmyAppelt** [woocommerce/woocommerce#18498]
Most likely because the element is changed to `button` (This was an `input` element before) https://github.com/woocommerce/woocommerce/commit/31825e8f60e4c197a033ebb53c4cbb79bd44de36

So the JS will needs to be corrected against this change or revert back to `input`

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18520
