### ISSUE TITLE
Woo 3.3 with theme compatibility

### ISSUE THREAD

**Issue by Nugrah** [woocommerce/woocommerce#18495]
Hi, previously i opened an issue about adding add_theme_support into our theme, and after that the image and display product option in customizer is not appear, so there is no option if we want to use both customizer for image and page display and still adding add_theme_support( 'woocommerce' ); ?

since we're a using customize template of WooCommerce we need both to be applied, thank you

**Comment by willgorham** [comment]
It looks like `add_theme_support( 'woocommerce' );` removes the Customizer image settings even without a second parameter for image sizes. I'm not sure if that's the intended behavior?

**Comment by Nugrah** [comment]
so is this an issue or no? what should we use if we want to keep our custom shop template while enabling the customizer option

**Comment by willgorham** [comment]
I believe this is an issue - I would think a theme should be able to declare WC support but let users choose the image sizes. I'm not 100% sure though, so I would wait for a core dev to comment.

**Comment by mikejolley** [comment]
If you don't define image sizes, customizer options will appear. They appear when you're viewing the shop page or a list of products however, not globally in the customizer.

Confirmed working.

**Comment by willgorham** [comment]
@mikejolley 

Ah, ok seeing that now.

So just to clarify:
- No declared WC support  -> Customizer options are globally available
- Declared WC support but **no** image size designation -> Customizer options only available on WC pages and pages with a products list
- Declared WC support with image sizes -> No customizer options

**Comment by Nugrah** [comment]
ah ok, thank you very much for explanation i can see it right now

you the best!!
