### ISSUE TITLE
[3.3] Blurry shop loop images

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#18501]
Looking at a dummy setup based on Storefront, I noticed that images look blurrier than before.
Here's an example of how a shop loop image shows up under WC 3.2:

```
<img width="300" height="300" src="//somewherewarm.test/wc31/wp-content/uploads/2017/06/beanie-300x300.jpg" class="attachment-shop_catalog size-shop_catalog wp-post-image" alt="" srcset="//somewherewarm.test/wc31/wp-content/uploads/2017/06/beanie-300x300.jpg 300w, //somewherewarm.test/wc31/wp-content/uploads/2017/06/beanie-150x150.jpg 150w, //somewherewarm.test/wc31/wp-content/uploads/2017/06/beanie-768x768.jpg 768w, //somewherewarm.test/wc31/wp-content/uploads/2017/06/beanie-180x180.jpg 180w, //somewherewarm.test/wc31/wp-content/uploads/2017/06/beanie-600x600.jpg 600w, //somewherewarm.test/wc31/wp-content/uploads/2017/06/beanie.jpg 801w" sizes="(max-width: 300px) 100vw, 300px">
```

...and here's the same image after updating to WC 3.3:

```
<img width="324" height="324" src="//somewherewarm.test/wc33/wp-content/uploads/2017/06/beanie-324x324.jpg" class="attachment-woocommerce_thumbnail size-woocommerce_thumbnail wp-post-image" alt="">
```

Set aside some time to find out why but I'll have to accept defeat, I'm afraid.

**Comment by mikejolley** [comment]
> WP will only make up a Srcset list of image sizes with the same aspect ratio. If your custom size had a different aspect ratio to other image sizes then you can create a selection of new sizes with aspect ratios that match.

Read that somewhere, not sure if true.

Also see this is something themes can add https://github.com/WordPress/WordPress/blob/aaf99e691391cfceb004d848450dbbf3344b1bee/wp-content/themes/twentysixteen/functions.php#L382-L414

**Comment by mikejolley** [comment]
Sure enough, 2016 theme generates them.

**Comment by mikejolley** [comment]
Moved to Storefront repo here https://github.com/woocommerce/storefront/issues/737

**Comment by franticpsyx** [comment]
> Sure enough, 2016 theme generates them.

Confirmed!
