### ISSUE TITLE
DOM Error in Checkout: Found 2 elements with non-unique id #_wpnonce

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#18509]
Observed on logged-out checkout with WooCommerce 3.2.6 on Chrome 63.0.3239.132 (Official Build) (64-bit) on macOS High Sierra 10.13.2

Add an item to your cart while logged out. Proceed to checkout. Both the "Returning customer? Click here to login" form and the "Place Order" form include a hidden nonce field, both with the same ID. Chrome now consoles this as an error, e.g.:

<img width="1328" alt="screen shot 2018-01-17 at 4 42 10 pm" src="https://user-images.githubusercontent.com/1595739/35074968-66812bc6-fba5-11e7-8462-4896abce910b.png">

**Comment by mikejolley** [comment]
Duplicate ID issue in trac is related: https://core.trac.wordpress.org/ticket/23165

**Comment by mikejolley** [comment]
And this is fixed in 3.3 already https://github.com/woocommerce/woocommerce/commit/82c5975b375f00056e28923e729bc4132b7facec

**Comment by sgehrman** [comment]
When will 3.3 be out?  I'm getting this too.

**Comment by i2g-lweiss** [comment]
Getting this error in 3.2.6 when logged out at checkout.

**Comment by Jeeva-Rathinam** [comment]
Anyone help me how can i solve this issue : 
Found 2 elements with non-unique id : [](https://snag.gy/s73RBx.jpg)

**Comment by localhost80** [comment]
something is funny here like its preventing you implement your own. I am experiencing the same issue.
