### ISSUE TITLE
API creating product with status = 'draft' ignores the SKU value

### ISSUE THREAD

**Issue by Lluisma** [woocommerce/woocommerce#18506]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Define the product values array:

`$create[ ] = array( 'name' => 'product_name', 'type'   => 'simple', 'sku' => 1, 'status' => 'draft' );`

2. Execute the insert

`$result[] = $woocommerce->post('products/batch', array( "create" => $create) );`

3. In the $result array you can see the sku item is null:

`[...] Array ( [name] => product_name [slug] =>  [type] => simple [status] => draft [sku] => [price] => [...]`

## Expected/actual behavior

On the other hand, when I set status as 'pending', it saves the SKU values as expected.

I wonder if this issue could be related with #16577 _Importing variable products as drafts results in missing variations_

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/16577 is related to the importer not the API.

**Comment by mikejolley** [comment]
![insomnia create product 2018-01-18 16-51-14](https://user-images.githubusercontent.com/90977/35110064-dc5c6d72-fc6f-11e7-971f-a79ebd1762ab.png)

Seems to work. If you repeat the test with the same SKU you get a duplicate error.
