### ISSUE TITLE
Unneeded parameter key "view" for register_post_type()?

### ISSUE THREAD

**Issue by tyrann0us** [woocommerce/woocommerce#18512]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)

## Steps to reproduce the issue
1. `WC_Post_types::register_post_types()` uses `register_post_type()` to add `product`, `shop_order` and `shop_coupon` post types.
2. The `labels` array has a `view` key [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-post-types.php#L280), [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-post-types.php#L340) and [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-post-types.php#L403).
3. According to the codex on [`get_post_type_labels()`](https://developer.wordpress.org/reference/functions/get_post_type_labels/#description) there's no such key (the only labels starting with `view` are `view_item` and `view_items`.

Were the `view` keys added by mistake or on purpose? I'm happy to make a PR to remove theses three lines if they are unintended.

**Comment by mikejolley** [comment]
Possibly legacy - you can remove them thanks.
