### ISSUE TITLE
Main Product on Gallery

### ISSUE THREAD

**Issue by domysalv** [woocommerce/woocommerce#18522]
Hi, I've a main product image with a border showing on my home page at www.confortissima.com.ar. Problem is that when I click on that product, that same image is shown on the gallery, how can I remove that? So it doesn't shows it's main image, but only gallery

**Comment by mikejolley** [comment]
This would only be possible through customisation by a developer. We have no in-built option for that.

For future ref, please bare in my Github is for issue reporting, not customisation help/general support. Use the forums for that. Thanks.
