### ISSUE TITLE
AJAX customer search fails when username is numeric

### ISSUE THREAD

**Issue by vnathalye** [woocommerce/woocommerce#18527]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a user (customer) with numeric username, such as mobile number
2. Go to Add New Order page from wp-admin (/wp-admin/post-new.php?post_type=shop_order)
3. Under Order Details, try to search for Customer with his username.

## Expected/actual behavior

When I follow those steps, I see...
It displays the message "No matches found"

I was expecting to see...
The customer created in step 1.

I've found out the root cause:
The AJAX request handler for `woocommerce_json_search_customers` action ( WC_AJAX::json_search_customers() ) checks for the search term. If the term is numeric it assumes it to be user ID and doesn't check for username.
Instead it should check for username and other details also (after checking for user ID) as it does in `else` part currently for non-numeric term.
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L1430-L1448

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Not including the env details because the issue is not specific to any environment but its the code issue.
```
</details>

**Comment by kloon** [comment]
I have fixed this in #18532, I only added a fallback in place so if there happens to be a user with the user ID entered it will not do a search based on username, reason for this is that it will cause a performance issue on large sites, but should no user with the ID be found it will do a search with the numeric value on the username.
