### ISSUE TITLE
The mini cart does not synchronize removed products across tabs

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#18548]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Open two tabs in your browser
2. In the first browser tab, add a product to the cart => The mini cart is updated in the second tab
3. In the first browser tab, remove the product from the cart => the mini cart is not updated in the second tab

## Expected/actual behavior

As the tabs are synchronized when adding a product ant [this comment](https://github.com/woocommerce/woocommerce/blob/3.3.0-rc.1/assets/js/frontend/cart-fragments.js#L93) in cart-fragment.js explicitly refers to the cart synchronization across tabs, I was expecting the that removed products would be synchronized too. 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment
WordPress 4.9.2
WooCommerce 3.3-rc.1 master branch

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18552
