### ISSUE TITLE
Only allow numerical characters for shipping costs

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#18545]
Flat Rate shipping method allows for the use of a symbol to be included in the **Cost** field.

<img width="587" alt="screen shot 2018-01-20 at 20 56 35" src="https://user-images.githubusercontent.com/2876178/35190368-31990136-fe25-11e7-9f93-5cc6df85e47d.png">
 
If that method is selected, it will prevent the cost from being included on the Checkout page

<img width="508" alt="screen shot 2018-01-20 at 21 05 34" src="https://user-images.githubusercontent.com/2876178/35190405-3aff73a8-fe26-11e7-98f7-66c76e2634ca.png">

## Steps to reproduce the issue

1. Use currency symbol in Cost field for Flat Rate method
2. Checkout using Flat Rate method

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see a cost at the checkout page or an error message when adding the costs amount to the method, indicating the use of r symbol.

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
We need more than just numbers here https://github.com/woocommerce/woocommerce/pull/18546#pullrequestreview-90335582

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18554
