### ISSUE TITLE
Under Products > All Products,  there used to be a drop down list of categories when you used "filter by categoried".  Now it asks you to put in the first 3 letters.  This means actually knowing what you have called a category.  With a site with over 30 categories, this is causing an issue. Can the drop down list be reinstated please?  Or failing that, is there a work around or a plugin that can fix this? 

### ISSUE THREAD

**Issue by JaneNorris** [woocommerce/woocommerce#18544]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by JimmyAppelt** [comment]
Your title should just describe the issue, not explaining the whole issue (explain the issue in the body instead)

**Comment by mikejolley** [comment]
Wait for 3.3.
