### ISSUE TITLE
woocommerce_before_calculate_totals appears to run twice - price modifications are duplicated

### ISSUE THREAD

**Issue by g01010** [woocommerce/woocommerce#18540]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Activate WooCommerce on clean install with default theme
2. Create simple product with a price
3. Add function hooked to `woocommerce_before_calculate_totals` as below in `theme functions.php`

`function test_before_calculate_totals( $cart_obj ) {
	if ( is_admin() && ! defined( 'DOING_AJAX' ) ) {
		return;
	}
	foreach( $cart_obj->get_cart() as $key=>$value ) {
			$price = $value['data']->get_price();
			$price+=5.3;
			$value['data']->set_price( floatval( $price ) );
	}
}
add_action( 'woocommerce_before_calculate_totals', 'test_before_calculate_totals', 10, 1 );`

## Expected/actual behavior

When I follow those steps, I see that the price modification has occurred twice. If the original product price is $3, when it appears in the cart it's been modified to $13.60, i.e. 3 + ( 5.3 * 2 ).

I was expecting to see it modified to $8.30, i.e 3 + 5.3.

woocommerce_before_calculate_totals appears to be running twice but I can't figure out how.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
This one isn't a bug. Calculate totals can run multiple times; it runs after certain events like add to cart and can be ran by extensions also. Using code like you provided is not reliable.

Store a temp variable to your product to indicate when you've added the extra price so you only do it once per request.

**Comment by g01010** [comment]
Okay, thanks.
