### ISSUE TITLE
Only append tax price suffix if taxable

### ISSUE THREAD

**Issue by extrapixel** [woocommerce/woocommerce#18549]
copy of  #13158 and #13119

Both issues are closed / merged, but problem still exists. 

Problem: Tax price suffix is always displayed on the **product page**, even if product is not taxable (for example, if the visitor is from a country where no tax is defined).

**Comment by mikejolley** [comment]
Those issues relate to hiding the suffix if the product itself is set to be non-taxable. In your case, the product is still taxable.

> if the visitor is from a country where no tax is defined

Thats option is not accounted for here. This price suffix does not change based on the customer. The products are still taxable, there is just 0% tax rate for the user. 

You can customise with the `woocommerce_get_price_suffix` filter if you want it to work differently. I'm not sure if all users will want to hide this suffix so would need more data (ideas board?) for a core change.

Thanks
