### ISSUE TITLE
Shipping calculation not calculated on checkout Page 

### ISSUE THREAD

**Issue by presslayouts** [woocommerce/woocommerce#18547]
Hello Support team,

For my shipping cost i setup two shipping cost.
One for US and International.

For the US Shipping delivery cost i set it at $2.50
And for international delivery cost i set at $3.00 

But on the check out page only one shipping is showing.
I want users to be able to select either US SHIPPING OR INTERNATIONAL SHIPPING
depending on their location on the checkout page.

http://hiddenpromises.com/checkout

Please add a product to the cart and checkout and try to select international
shipping you won't find it there on the list.

Thanks!

**Comment by MillerMedia** [comment]
I would suggest using the template provided by WooCommerce when submitting issues so it can more easily be diagnosed. A lot of questions come to mind when reading this (are you using your Shipping Zones correctly/how are your shipping zones set up?; what product exactly could be added to reproduce the issue and what is the URL to that product?). When you create a new issue, there is an entire template already filled in the editor that makes this process easy to submit and makes it much simpler for developers to diagnose.

**Comment by presslayouts** [comment]
Sorry guys, 

We are own template provider and author and we don't know why not working  shipping cost in checkout page.

So please you explain me what our mistake or issue in plugin.

Thanks!

**Comment by MillerMedia** [comment]
I meant the template of submitting an issue to the repository (not the template on the site). When you click ‘New Issue’ on this repository there instructions on how to properly submit an issue with certain steps to make it as clear as possible.

**Comment by mikejolley** [comment]
No selection by the user would be needed if you configured 2 zones; 1 US zone and the default "everywhere else" zone.
