### ISSUE TITLE
Product Schema - ratingCount & reviewCount

### ISSUE THREAD

**Issue by streamworksaudio** [woocommerce/woocommerce#18558]
I have noticed that WooCommerce is generating Product Schema, but I have noticed that it is generating both the ratingCount & reviewCount. Is there a way to only have reviewCount generated?

I ask, because I believe that having both is making Google to use the term ‘votes’ instead of ‘reviews’ in search results snippets. I think it would be better to have ‘reviews’ here, as we are talking about product reviews.

Here is an example…

https://www.google.com/search?q=wavelab%20pro%209%20tutorial

I think I should be near the top of the results… and you can see that it says ‘7 votes’. I would like it to say ‘7 reviews’.

Is there a way to alter the schema generated?

**Comment by streamworksaudio** [comment]
Thanks Mike,

I was reading this article (it is a few years old however) - http://www.seoskeptic.com/count-vs-votes-error-for-schema-org-aggregaterating/

Which made me think that perhaps both ratingCount & reviewCount cause it to say vote instead of review.

**Comment by streamworksaudio** [comment]
Using Google's Structured Data Testing Tool I copied and pasted the generated schema and then removed ratingCount from the code snippet and the Structured Data Testing Tool seems to be ok - no errors.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18565
