### ISSUE TITLE
Law requires customer to mention his ID in specific country

### ISSUE THREAD

**Issue by LetMeKnow1** [woocommerce/woocommerce#18557]
Hi,

I'm using advanced shipping classes to configure shipping countries.
When I ship within my country the customer requires to pay VAT (this works great)
However another requirement is to write his ID / Cooperation number in the invoice (I generate invoice from my own system). Sadly even though I ask customers to write it in order comments some ignore this (or simply don't pay attention).

What I need is to be able to define a **mandatory** text input for specific shipping categories.
So that if you ask to ship to country A another filed with "ID" would appear. The customer wont be able to continue with the checkout unless his ID is provided (again only for the designated countries)

Now from what I can tell WooCommerce allow such quality for products but not for shipping. How can I make it works? (Again, this is a law requirement in Israel I assume that more requests about this issue will follow from other merchants)

**Comment by LetMeKnow1** [comment]
@mikejolley  Will it support customization field  based on shipping class ? From what I can tell this will add the field for all checkout (all countries)

**Comment by willgorham** [comment]
@LetMeKnow1 This might be helpful: https://shopplugins.com/plugins/extra-shipping-options-woocommerce/ (I'm not sure if it's cool to post external plugins, but I'm not affiliated with this product.)

**Comment by mikejolley** [comment]
@LetMeKnow1 It's not conditional so it would be for all.
