### ISSUE TITLE
CLI support for import products (future request)

### ISSUE THREAD

**Issue by maheshwaghmare** [woocommerce/woocommerce#18562]
Is there any future plan for adding WP CLI support for importing products with CSV?

**Comment by mikejolley** [comment]
No; products can be made with API type calls over CLI https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-product

Feel free to contribute that if needed.

**Comment by mikejolley** [comment]
I've moved this to http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/33403972-woocommerce-cli-support-for-importing-products-fro to judge demand before making the effort to build it. Thanks.
