### ISSUE TITLE
REST Terms Controller - get_collection_params() taxonomy validation

### ISSUE THREAD

**Issue by mathiasdb** [woocommerce/woocommerce#18567]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Unregister taxonomy product_tag in theme functions.php
`add_action('init', function() { unregister_taxonomy('product_tag'); });`

## Expected/actual behavior

I get a PHP notification on WC_REST_Terms_Controller line 718 and 759. These lines contain conditionals if(!$taxonomy->hierarchical) and if($taxonomy->hierarchical. Condition fails because $taxonomy is no longer an object.

The first if('' !== $this->taxonomy) on line 691 is validated as true. This executes the next line 692 where $taxonomy = get_taxonomy($this->taxonomy) returns false, since the taxonomy product_tag no longer exists. @see steps-to-reproduce::step#1

I wasn't expecting errors / notifications.

## Possible solution

`if ( '' !== $this->taxonomy && taxonomy_exists($this->taxonomy)) {`
`$taxonomy = get_taxonomy( $this->taxonomy );`
`} else {`
`$taxonomy = new stdClass();`
`$taxonomy->hierarchical = true;`
`}`

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment
PHP error_log

<details>
```
[23-Jan-2018 14:17:06 Europe/Brussels] PHP Notice:  Trying to get property of non-object in /home/xxx/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-terms-controller.php on line 718
[23-Jan-2018 14:17:06 Europe/Brussels] PHP Notice:  Trying to get property of non-object in /home/xxx/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-terms-controller.php on line 759
```
</details>

**Comment by kloon** [comment]
This is a tricky one since this->taxonomy is used in several places to fetch and cache data based on the value in there.

I will defer this to @claudiosanches since he is the API expert, but I would say we should probably add some checks to not load the controller for a specific taxonomy if it does not exist, that way we can avoid any issues since the class is extended from a few other classes. Definitely better to not load those extended classes if the taxonomy does not exist for their specific taxonomy.

Will wait and hear what Claudio says.
