### ISSUE TITLE
Empty session_key value causing the same cart session to be shared between guest customers

### ISSUE THREAD

**Issue by mattallan** [woocommerce/woocommerce#18561]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Simplest way to reproduce:

1. Open the shop page in an incognito window and add a product to the cart as a guest customer
2. Close the incognito window.
3. Open the shop page again in a new incognito window, notice the cart is still populated with items from another session

## Expected/actual behavior

**When I follow those steps..**

When i open a new session (fresh incog. window), the cart is being populated with cart items from a previous session.
Also, when I open the store on a completely different device, the cart from the previous session is populated.

Also looking in the `_woocommerce_sessions` table I see a row with an empty `session_key` column:

![](https://cldup.com/9P7m2z2BDU-3000x3000.png)

**I was expecting to see...**

The cart to be cleared for each new session.

Also i expect the `_woocommerce_sessions` table to be filled with guest sessions like:

![](https://cldup.com/XaWtpZi8i7-3000x3000.png)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

While testing I had just WooCommerce and Stripe has the only active plugins.

I also reverted back to WC`v3.2.6` and was unable to reproduce.

**Comment by mikejolley** [comment]
Not happening on my local. Each incognito I open (after adding to cart) gets a new session key which I can see clearly in the DB table. What you describe looks like caching.

**Comment by mikejolley** [comment]
There is usage of wp_cache here which may be related: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-session-handler.php#L279

Doesn't explain the missing customer ID.

**Comment by mikejolley** [comment]
Made a few minor tweaks in https://github.com/woocommerce/woocommerce/tree/update/18561 but I cannot reproduce it. Must be cache related or something unique to your install.

**Comment by mattallan** [comment]
Thanks for taking a look into it guys.

> There is a feature in WC that keeps the carts in sync if you have multiple tabs/windows open

I can confirm that i'm fully closing the incognito instance and opening a new one each time i test.

> Made a few minor tweaks in https://github.com/woocommerce/woocommerce/tree/update/18561 but I cannot reproduce it.

I checked out this branch and the issue has been fixed with those changes!

It's possible it may be something unqiue to my installation, but i was able to reproduce on a fresh WP/WC install locally and also a fresh install on one of our testing domains.

I just updated one of my existing stores from wc3.2.5 to 3.3 and the issue doesn't exist there. It appears to only happen on fresh installs 🤔 

---

To show you what i'm seeing, I've created three stores that are running WC `v3.2.5`, `master` and also Mike's new branch `update/18561`.

Each store has the same server setup/config, but the bug only exists on the `master` branch store. From what I recall, gimme is just using standard/ordinary config (nothing special in the way it's setup)

WC 3.2.5: https://gimme.subscription.beer/WC325 :+1:
WC3.3 (master): https://gimme.subscription.beer/WC33 :x:
update/18561: https://gimme.subscription.beer/WC33.updated :+1:

I'll DM you an admin/pass in slack if you're interested in taking more of a look (A8C)

**Comment by jconroy** [comment]
Just chiming as I started testing 3.3 today.

Initially I couldn't replicate either (on `master`) but after a few test purchases as guest I somehow got into a similar situation with a blank session ID in the database https://cl.ly/1w2Y430O450T and then billing address info and products where being pre populated after clearing browser history, reloading, opening new browser etc. 

This wasn't a fresh install though - it was an existing test site that I updated today.

Definitely no caching going on either on my local dev site.

I haven't been able to figure out exact steps to replicate - will try to isolate if needed.

https://github.com/woocommerce/woocommerce/tree/update/18561 fixed the weirdness for me. (I still don't know how I got a empty session_key after update though sorry).

**Comment by jconroy** [comment]
> https://github.com/woocommerce/woocommerce/tree/update/18561 fixed the weirdness for me. (I still don't know how I got a empty session_key after update though sorry).

FYI - Looks like I can't log in from the my account page on that branch though

**Comment by jconroy** [comment]
@mikejolley @claudiulodro don't give this any more brain cycles atm - I've been chatting to @mattallan on the side - we'll do a little more debugging to isolate the cause

**Comment by mikejolley** [comment]
@jconroy That would be good. For now I've raised a PR with those checks on customer_id. Whilst I cannot see any cause for it being blank, that should guard against it.

**Comment by jconroy** [comment]
Hi @mikejolley it looks like it is/was to do with the stripe gateway session handling.

WC 3.3 is introducing a new init method within `WC_Session_Handler` https://github.com/woocommerce/woocommerce/commit/15089fc432ab36a494474cd263de5b3534befb43

I think stripe handling here: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/payment-methods/class-wc-stripe-payment-request.php#L146 may need to be updated to use the init. 

One other thing we noticed was we weren't able to login via the my account page until https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/payment-methods/class-wc-stripe-payment-request.php#L102 was removed and cookies cleared.

**Comment by mikejolley** [comment]
Thanks, we'll look into that.
