### ISSUE TITLE
Filtering wc/v2/products

### ISSUE THREAD

**Issue by omarfawzi** [woocommerce/woocommerce#18570]
Are there any available hooks to get the post and request when calling the restful wc/v2/products api i tried to use woocommerce_rest_prepare_products but that doesn't work i tried woocommerce_rest_prepare_product and it worked with a single product but i need to get all products in order to filter them by post data ?

**Comment by rodrigoprimo** [comment]
Hi there. WooCommerce uses GitHub primarily for reporting bugs and not as a support forum. You could try the community support forum here: https://wordpress.org/support/plugin/woocommerce
