### ISSUE TITLE
Recording Meta in Database : When shipping same as billing is ticked

### ISSUE THREAD

**Issue by TomasHurtz** [woocommerce/woocommerce#18576]
Hello woocommerce team,

Here is a situation which came about as a result of a recent customer complaining that they had not received their physical goods.

The user's WP account shows the shipping and billing as the same - but the ordermeta shows the billing and the shipping addresses slightly differently (the shipping address does not include the apartment number - which is why they didn't receive the goods and are now wanting a refund).  

This would suggest the user entered the shipping / billing separately and made a mistake - or that WooCommerce didn't copy over the information correctly?

The user complained that they did enter everything correctly, and stated they had ticked the "same as billing".  However, on inspection of the DB records, the "last updated" timestamp shows they had modified something in their account after the original order date - perhaps to make the shipping the same as the billing?

My question is this:

1) Have there been other instances reported where Woocommerce failed to copy over the billing information correctly to the shipping fields?  Or would I be correct in assuming this most likely user error (and user lying that they did it correctly)

2) Is there any way to view when the shipping address was changed?  Or in future, would it be possible to record the timestamp of an address change?

3) Is there any way to record in the Database when the user has selected the shipping same as billing tickbox.   A simple _shipping_same_as_billing_  YES in the postmeta would suffice?

Thank you

**Comment by mikejolley** [comment]
Hi,

1. Not afaik, excluding custom fields and with customisations of the checkout. The default checkout does seem to copy everything over. You can test this for yourself to confirm-it will work the same for all users on the site. I've tested this to confirm.

2. If the user changes address via account page, past orders are not updated. Addresses are stored within each order. Related https://github.com/woocommerce/woocommerce/issues/17086

3. You could add this as a customisation, but it's not really needed. If it's checked, billing is copied to shipping automatically. If it's not, billing fields are validated and saved and the order will store a different address for shipping.

Sounds like they may have missed it off shipping address and updated it later.

Thanks
