### ISSUE TITLE
API->Create refunds: line_items does not work

### ISSUE THREAD

**Issue by c3do** [woocommerce/woocommerce#18573]
Hello,

I tried different things to create a refund with API REST. 

I was not able to make 'line_items' work.

The total refunded is correct, but line_items is not taken into account.

i sent this simple API REST request:

`{"amount":"4.89","reason":"","refunded_by":1,"line_items":{"2052":{"quantity":1,"tax_class":0,"total":"4.89"}}}`

Thank you very much in advance.

**Comment by mikejolley** [comment]
Looks like WC wants qty not quantity, but the API uses quantity. Probably a few mismatches in the data here so it's a bug.

**Comment by c3do** [comment]
Hello @mikejolley ,

i tried this request but it didn't work better:
`{"amount":"4.89","reason":"","refunded_by":1,"line_items":{"2052":{"qty":1,"tax_class":0,"total":"4.89"}}}`

**Comment by mikejolley** [comment]
Logged for v3 api https://github.com/woocommerce/wc-api-dev/issues/83

**Comment by c3do** [comment]
So, we will never be able to refund an order line by line with th API, and woocommerce API will always generate empty credit notes?

**Comment by mikejolley** [comment]
Not until v3 - https://github.com/woocommerce/wc-api-dev/issues/83
