### ISSUE TITLE
Rounding prices with tax

### ISSUE THREAD

**Issue by vyskoczilova** [woocommerce/woocommerce#18572]
Hi, can you help us with a rounding issue? We have defined prices without tax, precise to 2 decimals. Czech VAT is 21 %. The problem is that overview is displaying correct price but "SUBTOTAL" and "TOTAL" are not correct - 1 CZK is missing and it's making discrepancies within our accounting system.

data from accounting program (same added into WC):
![image005](https://user-images.githubusercontent.com/3611726/35301021-b507f34e-008a-11e8-945d-f06bf2710570.png)

data at checkout - as you can see, SUBTOTAL is 1 CZK less than it should be if you sum up single items, TOTAL is wrong as well
![image006](https://user-images.githubusercontent.com/3611726/35301051-d51c571a-008a-11e8-80b1-f0e613874d16.png)

How to fix it?

**Comment by GlennMartin1** [comment]
What's your version of WC?

**Comment by vyskoczilova** [comment]
@GlennMartin1 yes, the latest from WP repo, here you go with the log:


## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://www.bjez.cz
Site URL: http://www.bjez.cz
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: cs_CZ

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.19
PHP Post Max Size: 32 MB
PHP Time Limit: 90
PHP Max Input Vars: 10000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Celková velikost databáze: 132.25MB
Velikost dat databáze: 76.74MB
Velikost indexu databáze: 55.51MB
wp_woocommerce_sessions: Data: 6.02MB + index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + index: 0.05MB
wp_woocommerce_order_items: Data: 1.52MB + index: 0.23MB
wp_woocommerce_order_itemmeta: Data: 3.52MB + index: 4.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + index: 0.02MB
iwp_clone_stats: Data: 0.02MB + index: 0.00MB
shopsync_last: Data: 0.00MB + index: 0.00MB
siwp230824_wp_users: Data: 0.06MB + index: 0.05MB
siwp230824_wp_wfBadLeechers: Data: 0.02MB + index: 0.00MB
siwp230824_wp_wfBlockedIPLog: Data: 0.02MB + index: 0.00MB
siwp230824_wp_wfBlocks: Data: 0.02MB + index: 0.02MB
siwp230824_wp_wfBlocksAdv: Data: 0.02MB + index: 0.00MB
siwp230824_wp_wfConfig: Data: 2.52MB + index: 0.00MB
siwp230824_wp_wfCrawlers: Data: 0.02MB + index: 0.00MB
siwp230824_wp_wfFileMods: Data: 0.09MB + index: 0.00MB
siwp230824_wp_wfHits: Data: 0.39MB + index: 0.16MB
siwp230824_wp_wfHoover: Data: 0.02MB + index: 0.02MB
siwp230824_wp_wfIssues: Data: 0.02MB + index: 0.00MB
siwp230824_wp_wfLeechers: Data: 0.05MB + index: 0.00MB
siwp230824_wp_wfLockedOut: Data: 0.02MB + index: 0.00MB
siwp230824_wp_wfLocs: Data: 0.02MB + index: 0.00MB
siwp230824_wp_wfLogins: Data: 0.02MB + index: 0.02MB
siwp230824_wp_wfNet404s: Data: 0.02MB + index: 0.02MB
siwp230824_wp_wfReverseCache: Data: 0.02MB + index: 0.00MB
siwp230824_wp_wfScanners: Data: 0.02MB + index: 0.00MB
siwp230824_wp_wfStatus: Data: 0.13MB + index: 0.09MB
siwp230824_wp_wfThrottleLog: Data: 0.02MB + index: 0.02MB
siwp230824_wp_wfVulnScanners: Data: 0.02MB + index: 0.00MB
siwp230824_wp_woocommerce_api_keys: Data: 0.02MB + index: 0.03MB
siwp230824_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + index: 0.02MB
siwp230824_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + index: 0.03MB
siwp230824_wp_woocommerce_order_itemmeta: Data: 2.52MB + index: 3.03MB
siwp230824_wp_woocommerce_order_items: Data: 0.36MB + index: 0.16MB
siwp230824_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + index: 0.03MB
siwp230824_wp_woocommerce_payment_tokens: Data: 0.02MB + index: 0.02MB
siwp230824_wp_woocommerce_sessions: Data: 0.25MB + index: 0.02MB
siwp230824_wp_woocommerce_shipping_zones: Data: 0.02MB + index: 0.00MB
siwp230824_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + index: 0.05MB
siwp230824_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + index: 0.00MB
siwp230824_wp_woocommerce_tax_rates: Data: 0.02MB + index: 0.06MB
siwp230824_wp_woocommerce_tax_rate_locations: Data: 0.02MB + index: 0.05MB
siwp230824_wp_wp_rp_tags: Data: 0.02MB + index: 0.03MB
siwp230824_wp_wysija_campaign: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_campaign_list: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_custom_field: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_email: Data: 0.09MB + index: 0.00MB
siwp230824_wp_wysija_email_user_stat: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_email_user_url: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_form: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_list: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_queue: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_url: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_url_mail: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_user: Data: 0.03MB + index: 0.02MB
siwp230824_wp_wysija_user_field: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_user_history: Data: 0.00MB + index: 0.00MB
siwp230824_wp_wysija_user_list: Data: 0.00MB + index: 0.01MB
siwp230824_wp_yith_wcwl: Data: 0.02MB + index: 0.02MB
siwp230824_wp_yith_wcwl_lists: Data: 0.02MB + index: 0.03MB
wp_bwg_album: Data: 0.02MB + index: 0.00MB
wp_bwg_album_gallery: Data: 0.02MB + index: 0.00MB
wp_bwg_gallery: Data: 0.02MB + index: 0.00MB
wp_bwg_image: Data: 0.02MB + index: 0.00MB
wp_bwg_image_comment: Data: 0.02MB + index: 0.00MB
wp_bwg_image_rate: Data: 0.02MB + index: 0.00MB
wp_bwg_image_tag: Data: 0.02MB + index: 0.00MB
wp_bwg_option: Data: 0.02MB + index: 0.00MB
wp_bwg_shortcode: Data: 0.02MB + index: 0.00MB
wp_bwg_theme: Data: 0.02MB + index: 0.00MB
wp_commentmeta: Data: 1.05MB + index: 0.17MB
wp_comments: Data: 3.52MB + index: 3.17MB
wp_faq_termmeta: Data: 0.02MB + index: 0.00MB
wp_gaplus_login: Data: 0.02MB + index: 0.00MB
wp_icl_content_status: Data: 0.02MB + index: 0.02MB
wp_icl_core_status: Data: 0.02MB + index: 0.02MB
wp_icl_flags: Data: 0.02MB + index: 0.02MB
wp_icl_languages: Data: 0.02MB + index: 0.03MB
wp_icl_languages_translations: Data: 0.19MB + index: 0.11MB
wp_icl_locale_map: Data: 0.02MB + index: 0.00MB
wp_icl_message_status: Data: 0.02MB + index: 0.03MB
wp_icl_mo_files_domains: Data: 0.02MB + index: 0.02MB
wp_icl_node: Data: 0.02MB + index: 0.00MB
wp_icl_reminders: Data: 0.02MB + index: 0.00MB
wp_icl_strings: Data: 2.52MB + index: 4.55MB
wp_icl_string_packages: Data: 0.02MB + index: 0.00MB
wp_icl_string_pages: Data: 2.52MB + index: 1.52MB
wp_icl_string_positions: Data: 0.02MB + index: 0.02MB
wp_icl_string_status: Data: 0.02MB + index: 0.02MB
wp_icl_string_translations: Data: 0.09MB + index: 0.02MB
wp_icl_string_urls: Data: 0.02MB + index: 0.02MB
wp_icl_translate: Data: 1.52MB + index: 0.13MB
wp_icl_translate_job: Data: 0.02MB + index: 0.02MB
wp_icl_translations: Data: 1.52MB + index: 3.88MB
wp_icl_translation_batches: Data: 0.02MB + index: 0.00MB
wp_icl_translation_status: Data: 1.52MB + index: 0.05MB
wp_itsec_lockouts: Data: 0.02MB + index: 0.08MB
wp_itsec_log: Data: 0.02MB + index: 0.03MB
wp_itsec_temp: Data: 0.02MB + index: 0.06MB
wp_iwp_backup_status: Data: 0.02MB + index: 0.00MB
wp_iwp_file_list: Data: 0.02MB + index: 0.02MB
wp_links: Data: 0.02MB + index: 0.02MB
wp_options: Data: 3.48MB + index: 0.09MB
wp_postmeta: Data: 17.55MB + index: 15.03MB
wp_posts: Data: 5.52MB + index: 1.66MB
wp_redirection_404: Data: 6.02MB + index: 12.09MB
wp_redirection_groups: Data: 0.02MB + index: 0.03MB
wp_redirection_items: Data: 0.02MB + index: 0.08MB
wp_redirection_logs: Data: 0.02MB + index: 0.08MB
wp_revslider_css: Data: 0.05MB + index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + index: 0.00MB
wp_revslider_settings: Data: 0.02MB + index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + index: 0.00MB
wp_revslider_slides: Data: 0.02MB + index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + index: 0.00MB
wp_smush_dir_images: Data: 0.02MB + index: 0.03MB
wp_sm_advanced_search_temp: Data: 0.00MB + index: 0.00MB
wp_termmeta: Data: 0.06MB + index: 0.03MB
wp_terms: Data: 0.02MB + index: 0.03MB
wp_term_relationships: Data: 0.11MB + index: 0.08MB
wp_term_taxonomy: Data: 0.02MB + index: 0.03MB
wp_usermeta: Data: 2.52MB + index: 3.03MB
wp_users: Data: 0.11MB + index: 0.08MB
wp_wcpdf_invoice_number: Data: 0.02MB + index: 0.00MB
wp_wfBadLeechers: Data: 0.02MB + index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + index: 0.00MB
wp_wfBlocks: Data: 0.02MB + index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + index: 0.00MB
wp_wfConfig: Data: 0.30MB + index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + index: 0.00MB
wp_wfFileMods: Data: 4.52MB + index: 0.00MB
wp_wfHits: Data: 0.25MB + index: 0.08MB
wp_wfHoover: Data: 0.02MB + index: 0.02MB
wp_wfIssues: Data: 0.02MB + index: 0.00MB
wp_wfKnownFileList: Data: 1.52MB + index: 0.00MB
wp_wfLeechers: Data: 0.09MB + index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + index: 0.00MB
wp_wfLocs: Data: 0.02MB + index: 0.00MB
wp_wfLogins: Data: 0.13MB + index: 0.03MB
wp_wfNet404s: Data: 0.02MB + index: 0.02MB
wp_wfNotifications: Data: 0.02MB + index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + index: 0.00MB
wp_wfReverseCache: Data: 0.02MB + index: 0.00MB
wp_wfScanners: Data: 0.02MB + index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + index: 0.05MB
wp_wfStatus: Data: 0.16MB + index: 0.09MB
wp_wfThrottleLog: Data: 0.02MB + index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + index: 0.00MB
wp_wpmm_subscribers: Data: 0.02MB + index: 0.00MB
wp_wp_rp_tags: Data: 0.02MB + index: 0.03MB
wp_wysija_campaign: Data: 0.00MB + index: 0.00MB
wp_wysija_campaign_list: Data: 0.00MB + index: 0.00MB
wp_wysija_custom_field: Data: 0.00MB + index: 0.00MB
wp_wysija_email: Data: 0.09MB + index: 0.00MB
wp_wysija_email_user_stat: Data: 0.00MB + index: 0.00MB
wp_wysija_email_user_url: Data: 0.00MB + index: 0.00MB
wp_wysija_form: Data: 0.00MB + index: 0.00MB
wp_wysija_list: Data: 0.00MB + index: 0.00MB
wp_wysija_queue: Data: 0.00MB + index: 0.00MB
wp_wysija_url: Data: 0.00MB + index: 0.00MB
wp_wysija_url_mail: Data: 0.00MB + index: 0.00MB
wp_wysija_user: Data: 0.07MB + index: 0.05MB
wp_wysija_user_field: Data: 0.00MB + index: 0.00MB
wp_wysija_user_history: Data: 0.00MB + index: 0.00MB
wp_wysija_user_list: Data: 0.01MB + index: 0.01MB
wp_yith_wcwl: Data: 0.02MB + index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + index: 0.03MB
wp_yoast_seo_links: Data: 0.02MB + index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + index: 0.00MB

### Post Type Counts ###

attachment: 2084
contactform: 1
custom_css: 1
customize_changeset: 10
gs_testimonial: 3
iwp_log: 390
ktsprotype: 2
nav_menu_item: 70
page: 56
portfolio: 7
post: 19
product: 277
product_variation: 86
revision: 583
shop_coupon: 79
shop_order: 2645
shop_order_refund: 12
testimonial: 6
testimonial_rotator: 1
testimonial-free: 1
testimonials-widget: 10
vc_grid_item: 2
wpcf7_contact_form: 3
wysijap: 1

### Security ###

Secure connection (HTTPS): ❌Váš obchod nepoužívá HTTPS. Zjistěte více o HTTPS a SSL certifikátech.
Hide errors from visitors: ✔

### Active Plugins (44) ###

InfiniteWP - Client: o Revmakx – 1.6.8.3
ManageWP - Worker: o ManageWP – 4.3.1
WPML Multilingual CMS: o OnTheGoSystems – 3.9.1
Akismet Anti-Spam: o Automattic – 4.0.2
Better WordPress reCAPTCHA: o Khang Minh – 2.0.3
Contact Form 7: o Takayuki Miyoshi – 4.9.2
Cookie Notice: o dFactory – 1.2.41
Duplicate Post: o Enrico Battocchi – 3.2.1
Envato WordPress Toolkit: o Envato – 1.7.3
GetBowtied Tools: o GetBowtied – 2.3.2
WPBakery Page Builder: o Michael M - WPBakery.com – 5.4.5
Redirection: o John Godley – 3.0.1
Revolution Slider: o ThemePunch – 4.6.5
Smart Manager: o StoreApps – 3.15.0 – Nebylo testováno s aktivní verzí WooCommerce
Super Testimonial: o Themepoints – 1.4
Toret Custom Price: o Vladislav Musílek – 1.2
Woo Doprava: o Vladislav Musílek – 1.5.3 – Nebylo testováno s aktivní verzí WooCommerce
Advanced Order Export For WooCommerce: o AlgolPlus – 1.5.1
Woo Sledování SK: o Vladislav Musílek – 1.1.4 – Nebylo testováno s aktivní verzí WooCommerce
Woo The Pay: o Vladislav Musílek – 1.1.0 – Nebylo testováno s aktivní verzí WooCommerce
WooCommerce Cart Stock Reducer: o James Golovich – 2.10 – Nebylo testováno s aktivní verzí WooCommerce
WooCommerce Colors: o WooThemes – 1.0.7 – Nebylo testováno s aktivní verzí WooCommerce
WooCommerce Header Category Image: o Get Bowtied – 1.0.0 – Nebylo testováno s aktivní verzí WooCommerce
WooCommerce Multilingual: o OnTheGoSystems – 4.2.8.1
WooCommerce PDF Invoices & Packing Slips: o Ewout Fernhout – 2.1.3
WooCommerce Prices By User Role: o Festi-Team – 4.0.2 – Nebylo testováno s aktivní verzí WooCommerce
Woocommerce Zásilkovna: o Vladislav Musílek – 1.5.2 – Nebylo testováno s aktivní verzí WooCommerce
WooCommerce: o Automattic – 3.2.6
Kybernaut IC DIC: o Karolína Vyskočilová – 1.1.0 – Nebylo testováno s aktivní verzí WooCommerce
Wordfence Security: o Wordfence – 6.3.22
Yoast SEO: o Tým Yoast  – 6.1.1
WP-CopyProtect [Protect your blog posts]: o Chetan Gole – 3.1.0
WP Maintenance Mode: o Designmodo – 2.0.9
WP-Optimize: o David Anderson
Ruhani Rabin
Team Updraft – 2.1.1

WP Smush Pro: o WPMU DEV – 2.7.6
WP Super Cache: o Automattic – 1.5.9
WPML Media: o OnTheGoSystems – 2.2.2
WPML String Translation: o OnTheGoSystems – 2.7.1
WPML Translation Management: o OnTheGoSystems – 2.5.0
SmartCrawl: o WPMU DEV – 2.1.0.1
WPMU DEV Dashboard: o WPMU DEV – 4.4
MailPoet 2: o MailPoet – 2.8.1
YITH Purchased Column for WooCommerce: o YITHEMES – 1.0.4 – Nebylo testováno s aktivní verzí WooCommerce
YITH WooCommerce Wishlist: o YITHEMES – 2.2.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Obchod: #374 - /sportovni-celenky-obchod/
Košík: #10 - /kosik/
Pokladna: #11 - /pokladna/
Můj účet: #12 - /muj-ucet/
Obchodní podmínky: #710 - /obchodni-podminky/

### Theme ###

Name: Bjež
Version: 1.6.12.1473332515
Author URL: http://kybernaut.cz/
Child Theme: ✔
Parent Theme Name: Shopkeeper
Parent Theme Version: 2.4.2
Parent Theme Author URL: https://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php
shopkeeper/woocommerce/cart/cart-empty.php
shopkeeper/woocommerce/cart/mini-cart.php
shopkeeper/woocommerce/checkout/form-coupon.php
shopkeeper/woocommerce/checkout/form-login.php
shopkeeper/woocommerce/content-product.php
shopkeeper/woocommerce/content-product_cat.php
shopkeeper/woocommerce/content-single-product.php
shopkeeper-child/woocommerce/emails/admin-cancelled-order.php
shopkeeper-child/woocommerce/emails/customer-completed-order.php
shopkeeper-child/woocommerce/emails/customer-invoice.php
shopkeeper-child/woocommerce/emails/customer-on-hold-order.php
shopkeeper-child/woocommerce/emails/customer-processing-order.php
shopkeeper-child/woocommerce/emails/customer-refunded-order.php
shopkeeper/woocommerce/global/quantity-input.php
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/loop/loop-end.php
shopkeeper/woocommerce/loop/loop-start.php
shopkeeper/woocommerce/loop/no-products-found.php
shopkeeper/woocommerce/myaccount/form-login.php
shopkeeper/woocommerce/myaccount/my-downloads.php
shopkeeper/woocommerce/order/form-tracking.php
shopkeeper-child/woocommerce/single-product/product-attributes.php verze 3.0.0 je neaktuální. Verze jádra je 3.1.0
shopkeeper/woocommerce/single-product/product-image.php
shopkeeper/woocommerce/single-product/product-thumbnails.php
shopkeeper-child/woocommerce/single-product/short-description.php
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product.php

Outdated Templates: ❌Zjistěte
jak aktualizovat

`
</details>

## Prerequisites



- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Isolating the problem



- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
Looks like some customisations in the output of totals. This is how mine looks with 21% tax, excl. tax prices, and 2 DP currency:

![cart test 2018-01-24 16-38-42](https://user-images.githubusercontent.com/90977/35344446-11957934-0125-11e8-8a3c-8e9ace0e8a2a.png)

Note the subtotal is 659. Everything else totals up correctly.

If you can submit a failing unit test I can look into it further but all looks well.

Thanks

**Comment by vyskoczilova** [comment]
@mikejolley I'm terribly sorry, tested again on a clean install and got the same results, it was caused by "Round tax at subtotal level, instead of rounding per line" checked in Tax settings.
