### ISSUE TITLE
Enhancement:  Shop Page Display Options

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce#18574]
Before 3.3, we had these options in WooCommerce > Settings > Display:

![screen shot 2018-01-23 at 2 25 29 pm](https://user-images.githubusercontent.com/3220162/35304155-64a1b8ea-0049-11e8-9963-78d1680195b4.png)

They are now moved to the Customizer, but only when viewing the Shop page:
![screen shot 2018-01-23 at 2 26 50 pm](https://user-images.githubusercontent.com/3220162/35304188-7bbeb618-0049-11e8-8a19-fc13a676e78d.png)

In efforts to ease the transition, can we have a link FROM the old location that points people to the new location?  Something like:

"The Product Display options are now located in the Customizer.  **Go see them in action**".  This would then link people directly to the Shop page and to the open Panel with these options visible.

**Comment by SorinGFS** [comment]
Besides moving the Settings>Products>Display to Cutomizer looks like a downgrade to me it even doesn't work as espected, Issues are:
1) I lost time to find this modification, after I uninstalled all my plugins and tested if Settings>Product>Display tab appears somewhere
2) If you set the shop page to display only Categories it shows only products. 
3) This useles and undeleteble Uncategorized category was introduced, if I need such a category I can set myself
4) The third image size option was eliminated, and now we are forced to use the same image size for category and single-page thumbnail, we cannot use Regenerate Thumbnails to simply set the image sizes for all the needs anymore. This implies more css to be added, or javascript.
5) Working with Customizer is depracated, I even forgot that the Customizer exists :)  I allways remember the Customizer as the most certain way if you want to break the site!

All in all, I'm not happy with this, and I will not make any upgrades if it stays like this.

**Comment by WPprodigy** [comment]
I do agree that a link would be helpful, at least for now. Can make the link go to this specific page and open up the tab: https://github.com/woocommerce/woocommerce/pull/18389/files#diff-f664362a33faa9d314f0582223d39a75R1925

The counter argument though is that this is a setting that's set once and forgotten. There's really no need to re-visit these settings on an already-running site. So as long as documentation is updated, it stands to reason that it may not be such a big deal.

_____

And then to answer your concerns @SorinGFS, I believe quite a few of them are unrelated to this change.

> 2) If you set the shop page to display only Categories it shows only products.

I'm not able to replicate this behavior. I believe something is causing a conflict on your site.

> 3) This useles and undeletable Uncategorized category was introduced, if I need such a category I can set myself

This was not introduced with this change, the Uncategorized is a WordPress default thing I believe. You can rename it or set a new category as the default and delete the Uncategorized option if you want.

> 4) The third image size option was eliminated, and now we are forced to use the same image size for category and single-page thumbnail, we cannot use Regenerate Thumbnails to simply set the image sizes for all the needs anymore. This implies more css to be added, or javascript.

This is related more towards the image changes in 3.3, and there are reasonings behind this new behavior. There are different settings for catalog and single product sizes though. If the the theme declares a size, then the settings won't appear.

 > 5) Working with Customizer is depracated

I'm sorry it feels that way to you, but it's certainly not the case.

**Comment by mikejolley** [comment]
1. ?
2. Works my side.
3. Unrelated. Same as posts. Doesn't affect you if ignored.
4. Really not needed. Now we can use browser cache more.
5.  ¯\_(ツ)_/¯

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18584
