### ISSUE TITLE
WooCommerce 3.0.x Code Reference

### ISSUE THREAD

**Issue by californiakat** [woocommerce/woocommerce#18575]
We've had a few tickets in Support that point out the WooCommerce 3.0.x Code Reference is outdated.

https://docs.woocommerce.com/wc-apidocs/

This doesn't live on the docs.woo.com site (it's a redirect), and therefore I and HEs have no access to it. Inquiring about this in the past, I understood that this was auto-generated (to an extent) and maintained by Proton. If that's incorrect, please let me know.

Here are the tickets I know about:

https://woothemes.zendesk.com/agent/tickets/909578 from @melindahelt 
https://woothemes.zendesk.com/agent/tickets/914446 from @LaurenaRehbein 

There was also another from @madeincosmos but she said she would ping you, and I wasn't given the ticket number.

Thanks! :) 

## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

**Comment by madeincosmos** [comment]
Thanks @californiakat! The ticket I found is the same one as Laurena's, so by now we're only aware of these two reports :-)

**Comment by mikejolley** [comment]
These have to be manually generated. I've added to the docs list https://protonpower.wordpress.com/2017/12/06/3-3-docs-to-write-or-update/
