### ISSUE TITLE
country state is not working when we change pre-selected  country with different country then state names has missing and when we refresh the checkout page then it's started workng correctly basically issue with selecting US and UK  region with chromer browser

### ISSUE THREAD

**Issue by abhayp-cedcoss** [woocommerce/woocommerce#18580]
Bug name: country state is not working when we change pre-selected  country with different country then state names have missing and when we refresh the checkout page then it's started working correctly 
Area Path: shop->checkout

**Comment by mikejolley** [comment]
You need to go through the directions on the new issue form for us to look into issues. That includes prerequisite debugging and providing all requested details.

https://github.com/woocommerce/woocommerce/issues/new

Thanks
