### ISSUE TITLE
No way to differentiate between html and plain versions in email-downloads.php template

### ISSUE THREAD

**Issue by smazur** [woocommerce/woocommerce#18598]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

Just want to point out that it is not possible to differentiate between which email-downloads.php template we are rendering (html or plain text version) using **woocommerce_email_downloads_column_** hook. As both versions use same action call without any indication of email format.

`do_action( 'woocommerce_email_downloads_column_' . $column_id, $download );`

Please fix.

**Comment by mikejolley** [comment]
Want to send a pr?

**Comment by smazur** [comment]
Sorry, not sure I know how to do that. Please manage yourself. Thanks.

**Comment by claudiosanches** [comment]
PR #18600
