### ISSUE TITLE
Woocommerce connector to Power BI

### ISSUE THREAD

**Issue by dandaformanda** [woocommerce/woocommerce#18591]
Hello, we are loading our datas from eshop and for that we use Woocommerce connector available here https://github.com/migueesc123/WooCommerceConnector.

After loading with API credentials I get datas I requiered. But in columns with numeric values I get an Error and I cannot convert these values.

Can you help please?
many thanks.
Daniel

**Comment by mikejolley** [comment]
You'll need to ask the developer. We don't support other plugins here.
