### ISSUE TITLE
Woocommerce Setup Wizard Error

### ISSUE THREAD

**Issue by MichelleJacobs4** [woocommerce/woocommerce#18605]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Login to WP: https://www.aiedrp.org/wp-admin/
2. User: *******
3. Pass: *******
4. Go to dashboard ->woocommerce->settings
5. Click on Help in upper right hand corner -> select setup wizard
6. Click blue set up wizard button
7. Get error: Sorry, you are not allowed to access this page.

This happens with twentyseventeen theme as well as astra theme. I also have tried using a different server, same error.

## Expected/actual behavior

I was expecting to see...the setup wizard working properly

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
WordPress environment
--
Home URL: |   | https://www.aiedrp.org
Site URL: |   | https://www.aiedrp.org
WC version: |   | 3.2.6
Log directory writable: |   | /home/aiedrp/public_html/wp-content/uploads/wc-logs/
WP version: |   | 4.9.2
WP multisite: |   | –
WP memory limit: |   | 1 GB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US


```
</details>

**Comment by claudiulodro** [comment]
Just a heads-up never post the credentials for your site in a public location like this. Anyone viewing this issue (it's viewable to anyone on the internet) could log into your site and do anything. I've removed the credentials from this issue.

You should also change your password as soon as possible. Anyone subscribed to the issues for WooCommerce will have received an email with your username and password in it.

You've tried it with different themes, but have you tried deactivating all your plugins except WooCommerce and trying it again? It's most likely a conflict with your other plugins if it behaves the same on multiple servers.

**Comment by heartt13** [comment]
When I experienced the same issue, I deactivated the "Astra Starter Sites – Elementor, Beaver Builder & Gutenberg Templates" plugin, and the WooCommerce wizard now works!!
