### ISSUE TITLE
Action woocommerce_update_options_products_{section} is not executed

### ISSUE THREAD

**Issue by alexminza** [woocommerce/woocommerce#18608]
According to [WC_Settings_Page::save()](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/settings/class-wc-settings-page.php#L137)

`do_action( 'woocommerce_update_options_' . $this->id . '_' . $current_section );`

Actions like `woocommerce_update_options_products_inventory` are not executed, while the generic action `woocommerce_update_options_products` is executed properly at the same time, having the correct `global $current_section` value.

**Comment by kloon** [comment]
Fixed in #18609
