### ISSUE TITLE
Bulk order status changes do not invoking payment gateways so some gateways cannot hook into status changes

### ISSUE THREAD

**Issue by hjoelr** [woocommerce/woocommerce#18601]
I have been meaning to try this in the latest code but haven't been able to get the time to. In WC 3.2.x when marking an order as processing through the bulk tool the hooks in payment gateways are not loaded and therefore some are unable to respond to that order status change. I'm wondering if this is still the case in the WC 3.3 RC.

In WC 3.2.x, this was done in `WC_Admin_Post_Types::handle_shop_order_bulk_actions()`. The admin ajax method of changing an order status, however, invokes the payment gateways properly as shown here (in particular lines 473 and 474):

https://github.com/woocommerce/woocommerce/blob/e2d553fb6149cfd243df870f065afd7dced4e383/includes/class-wc-ajax.php#L467-L483

I know that in WC 3.3 this has been reworked some and the bulk order status change code is now located in `WC_Admin_List_Table_Orders::handle_bulk_actions()` function here:

https://github.com/woocommerce/woocommerce/blob/eade481164fe72f85a31cd1e6bfa1972bf395a94/includes/admin/list-tables/class-wc-admin-list-table-orders.php#L612-L656

The code in `WC_Admin_List_Table_Orders::handle_bulk_actions()` is nearly identical to what it was before in WC 3.2.x (in particular no call to `wc()->payment_gateways()`), so that makes me wonder if this is still an issue. It could be possible that the payment gateways are initiated somewhere before this function though. I'm wondering if someone would have a chance to test this on the latest code? The particular payment gateway I saw this affecting was PayPal, but it could be others.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an order that has been made with PayPal (in my case the built-in PayPal provider of WC). The order should go into 'on-hold' status.
2. On the orders list on the backend of WC, select the checkbox next to the order, select 'Mark processing' from the menu at the top, and click apply.
3. See if the payment was captured. The `WC_Gateway_Paypal::capture_payment()` function should run but it doesn't.

## Expected/actual behavior

When I follow those steps, I see...

PayPal does not capture the charge. In particular the `WC_Gateway_Paypal::capture_payment()` does not run.

I was expecting to see...

When marking a PayPal order as processing I would expect the payment to capture, and in particular the `WC_Gateway_Paypal::capture_payment()` function to run.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by kloon** [comment]
I just tested using an action in a gateway on the 3.3 branch and it triggered when changing statuses using the bulk option. So all working as expected.

**Comment by hjoelr** [comment]
@kloon Thanks for verifying! Glad it seems to be fixed in the newer version.
