### ISSUE TITLE
Coupon user usage limit should be checked against who purchases the order not who editing it

### ISSUE THREAD

**Issue by alexdonh** [woocommerce/woocommerce#18610]
In short, once a shop manager / admin uses his account to purchase something and apply a coupon. If this coupon has user usage limit, he will no longer able to apply coupon for any other orders, even those are not made by him, if he himself reaches that limit.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a coupon and set the "Usage limit per user" to 1. 
2. Create a user (Shop manager). Can have it done manually on backend or by registering a new account.
3. Assign Shop manager to that user.
4. Login to frontend with that shop manager account and buy something. Apply the coupon above.
4. Create another user (Customer).
5. Login to frontend with that customer account and buy something. Do not apply coupon.
6. Login to backend with Shop manager account and edit the order made by customer account.
7. Apply the coupon above.
8. Bingo! Issue happens.

## Expected/actual behavior

When I follow those steps, a popup message shows up and says 

> Coupon usage limit has been reached

But... customer has never used the coupon. Only shop manager did use.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## Code investigation

I am not going to create a PR, instead I show what I has investigated so far.
In `woocommece\includes\class-wc-discounts.php`, take a look into `is_coupon_valid` public method. This gets called whenever a coupon is applied when editing order in backend. Take another look into `validate_coupon_user_usage_limit` method. It checks against current logged in user while it should check against who made the order. 
I had it changed to `$this->validate_coupon_user_usage_limit( $coupon, $this->object instanceof WC_Order ? $this->object->user_id : 0 );` and it worked as expected.

**Comment by kloon** [comment]
Fixed in #18612
