### ISSUE TITLE
Error changing rows per page/ products per row

### ISSUE THREAD

**Issue by rthvanesa** [woocommerce/woocommerce#18613]
When I change the number of rows per page, I get this error:

![screenshot-staging mrtailor wp-theme design-2018-01-26-13-19-25-461](https://user-images.githubusercontent.com/7516117/35437606-cc50b3a2-029b-11e8-8c71-38a03baa2e9a.png)

And the same happens for products per row.
Even though in the preview page the rows and columns are being displayed correctly, the changes cannot be saved due to the error.
I did further investigation and the issue comes from _class-wc-shop-customizer.php_. When comparing the selected value and min/max values, the comparation is made between variables of type _string_. Forcing them into Integer variables would work: `if ( min && parseInt(value) < parseInt(min) ) {`

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18618
