### ISSUE TITLE
getting error on single-product.php in woocommerce

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [woocommerce/woocommerce#18621]
Notice: WC_Product::get_gallery_attachment_ids is deprecated since version 3.0! Use WC_Product::get_gallery_image_ids instead. in /home/nadiaz5/public_html/wp-includes/functions.php on line 3839

Notice: WC_Product::get_related is deprecated since version 3.0! Use wc_get_related_products instead. in /home/nadiaz5/public_html/wp-includes/functions.php on line 3839

Notice: id was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/plugins/woocommerce/templates/single-product.php'), wc_get_template_part, load_template, require('/themes/B-Nadiaz/woocommerce/content-single-product.php'), do_action('woocommerce_after_single_product_summary'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, Avada_Woocommerce->output_related_products, woocommerce_related_products, wc_get_template, include('/themes/B-Nadiaz/woocommerce/single-product/related.php'), WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in /home/nadiaz5/public_html/wp-includes/functions.php on line 4147

**Comment by WPprodigy** [comment]
Your theme / other plugins are using deprecated methods and properties. This isn't a problem with WooCommerce core.

**Comment by kloon** [comment]
As @WPprodigy pointed out, this is an issue with your theme and needs to be fixed there. I suggest you contact your theme developer and have them bring the theme in line with the latest version of WooCommerce.
