### ISSUE TITLE
single product images not displaying at the size set

### ISSUE THREAD

**Issue by matemiholics** [woocommerce/woocommerce#18627]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  Set up single Product image 400x400 
![single product pic](https://user-images.githubusercontent.com/35877608/35481499-f39dad40-0424-11e8-9508-d681ac904001.png)

2. Save
3. Run regnerate thumbnails
4. view single product page

http://bamshoes.com/termek/high-quality-cow-leather-womens-casual-shoes-spring-autumn-fashion-lace-up-female-flats-shoe-solid-woman-shoes-in-white-black/

![spp2](https://user-images.githubusercontent.com/35877608/35481510-228ccfa0-0425-11e8-95a8-8aee5ffeee5f.png)

## Expected/actual behavior

When I follow those steps, I see... the image displayed bigger size (1437x1437)

I was expecting to see... 400x400 image

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by SorinGFS** [comment]
@matemiholics 
•[x ] The issue still exists against the latest master branch of WooCommerce on Github (this is not the same version as on WordPress.org!) 
Your version of woocommerce is not 3.3.0 RC1, the latest master branch, because in the last version the tab Settings>Products>Display was moved to Customizer.

**Comment by matemiholics** [comment]
Ok sorry for the mistake! So how can be the problem solved?

**Comment by SorinGFS** [comment]
If you say that you already done the steps 1 to 4, regenerating thumnails, etc, it looks like a theme issue, contact your theme author for that.
One thing that jumps in my eye is the similarity of those two sizes, normally the large size should be... larger than medium :) The medium size is used for catalog images, so you can try to set the large size image to a greater size than 400 and see what's happen.

**Comment by SorinGFS** [comment]
@matemiholics In fact there is no problem, I just look at your site and I saw that the column is very large, 2 equal columns with no sidebar, try to limit the width of your columns, or add a sidebar. If you resize the browser window you can see that there is no problem.

**Comment by matemiholics** [comment]
I resized the pictures and uploaded just how you wrote but unfortunatley nothing changed.
I also contacted the theme support. They said that it is a ticket that should connect to woocommerce support. 
They asked to do the following steps: change the theme to storefront. Change the size of the single product pictures in woocommerce to a bigger and a smaller size and check what happens. Unfortunately either way nothing changed on the products page. 
So there is still a problem if I change to a defult theme. 
Do you have any other ideas how can I fix this?

**Comment by matemiholics** [comment]
I intentionally set up the page structure not to have a sidebar because this is a product page and there is no need to have a sidebar on that page. It causes the error? 
How can I limit the width of the columns? Is it connected to what size it shows the single product picture?
Thank you in advance!

**Comment by SorinGFS** [comment]
@matemiholics You can limit the width by choosing a boxed layout in the theme options.

**Comment by matemiholics** [comment]
Yes I know but I want to see the product page in fullwidth where the single product picture turn up max. 400x400. 
I just don't find the solution for that.

**Comment by SorinGFS** [comment]
@matemiholics It is already in fullwidth, check your monitor's resolution. Thi is what I see on my 1920x1080 display
<a href="https://ibb.co/nFEzYb"><img src="https://preview.ibb.co/iG28Rw/Capture.jpg" alt="Capture" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>temporary image upload</a><br />

**Comment by matemiholics** [comment]
That is exactly I would like to see on my product page. 
Instead of that I see this:
![high quality cow leather women s casual shoes spring autumn fashion lace up female flats shoe solid woman shoes in white black bamshoes](https://user-images.githubusercontent.com/35877608/35485375-294cba96-045f-11e8-9e51-1bb56875eeb7.png)

I also see 1920x1080 display. 

Do you have any idea why it appears like that?

**Comment by SorinGFS** [comment]
@matemiholics You have to set singlle product page to be displayed on a single column, actually you have two columns.

**Comment by matemiholics** [comment]
I don't find where I can set this up and I don't understand why it appears diffrently on other computers.
It just still does not work on my computer but appears perfectly on yours.
Do you have any suggestion how to solve this? I appreciate your help!

**Comment by SorinGFS** [comment]
@matemiholics Check if you have set any scaling different than 100%, on browser, or even on your display. Try different browsers, if looks the same check the scaling in the operating system settings.

**Comment by matemiholics** [comment]
Just checked: Scaling option is 100% on browser and also on display. I tried different browser and in Internet Explorer appears good. But in chrome which I use still not working.

**Comment by kloon** [comment]
The image settings only control the underlying image, your theme can still display the image larger than what is set via the settings. Themes usually do this via CSS. See the natural size 
![screen shot 2018-01-29 at 8 21 05 am](https://user-images.githubusercontent.com/271630/35496113-72ef9164-04cd-11e8-985c-d5fc91b581bc.png)

From WooCommerce 3.3 we added the ability for themes to define image sizes programmatically which will then hide the settings from end-users as the setting causes confusion when a theme uses CSS to control the size and users try and change the settings without it having an effect.
