### ISSUE TITLE
WC 3.3 - wc_setup_loop function added to late

### ISSUE THREAD

**Issue by komarovartem** [woocommerce/woocommerce#18626]
Hi, 

During testing, I notice that my customization like shifting the order of orderby, archive_description, and result_count do not work anymore. The reason is a new function  **wc_setup_loop** which is added to woocommerce_before_shop_loop hook (by the way it is not mentioned in the archive-product.php hooked list) is added after all actions like before_main_content and etc. I think in some cases you need to know args like loop, total, current_page before loop starts to display a result_count next to a page title for example.

**Comment by WPprodigy** [comment]
>  I notice that my customization like shifting the order of orderby, archive_description, and result_count do not work anymore.

It should definitely still be possible to change the priorities on these. `archive_description` is also added on to a different hook, at least by default. So I'm thinking there is just something wrong with your customizations?

> the reason is a new function wc_setup_loop which is added to woocommerce_before_shop_loop hook [...] is added after all actions

> I think in some cases you need to know args like loop, total, current_page before loop starts to display a result_count next to a page title for example.

[This function](https://github.com/woocommerce/woocommerce/blob/8f878a30edca7fe86fd21e5c9ab505a28eeb9664/includes/wc-template-functions.php#L157-L190) is added to the hook without a defined priority, which means the default is used. So it's being added with a priority of 10 per the [WP docs](https://developer.wordpress.org/reference/functions/add_action/).

That means it's called before the `woocommerce_result_count` and `woocommerce_catalog_ordering` hooked functions.

_____

Code references:

`wc_setup_loop()`: https://github.com/woocommerce/woocommerce/blob/8f878a30edca7fe86fd21e5c9ab505a28eeb9664/includes/wc-template-functions.php#L157-L190

`woocommerce_before_shop_loop `: https://github.com/woocommerce/woocommerce/blob/eea1c3d5d895212784960c9291f7631b0ac3a500/templates/archive-product.php#L54-L61

**Comment by kloon** [comment]
Could help us if you can post the code you are using to try and change the behavior, you probably just need to use a higher priory to ensure your code runs after WooCommerce code.

Closing issue, but feel free to reopen if you have code available.
