### ISSUE TITLE
admin.scss compile breaks select2 functionality

### ISSUE THREAD

**Issue by BuchyOne** [woocommerce/woocommerce#18622]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  fresh install WC 3.2.6 and cd to assets/css
2. sass admin.scss:admin.css
3. ui components that depend on Select2 break - missing styles

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

No change in Select2 components

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by WPprodigy** [comment]
> fresh install WC 3.2.6

Is this a download from Github or a release copy like from WP.org? Could you maybe expand a bit on what you're trying to do this for exactly?

At the moment, files are committed to this repo already compiled and minified. This will likely change with https://github.com/woocommerce/woocommerce/issues/18395, but that's how it is now.

Would also recommend just running either the whole npm build script, or the grunt sass task.

**Comment by kloon** [comment]
It could be that you have outdated npm packages installed, I'd suggest you run npm install first from the root folder and then after that try running sass also from the root folder. You need node-sass 4.7.2 to compile correctly, but npm install should fix all of this and update to the correct versions of the packages required.

**Comment by BuchyOne** [comment]
@WPprodigy 

Both Github or current release.

Wanted to edit scss file to style custom field in product data tab. 

Believed this caused the problem, so back to new files, no modifications, delete css file, sass compile scss to css : 
- css unlike current version or repo
- select2 styles are partially missing.

Not critical.

@kloon

node-sass ./admin.scss ./admin.css  produces 

produces same result

npm list -g|grep sass 

+-- node-sass@4.7.2
| +-- sass-graph@2.2.4

**Comment by WPprodigy** [comment]
> Wanted to edit scss file to style custom field in product data tab.

Thanks for the report, but I don't believe there are compiling issues with the sass when you run it all together.

If you need custom styles, it's also never good to edit the core files. Create a custom plugin or stylesheet in a child theme and enqueue it in the admin.

**Comment by BuchyOne** [comment]
Thanks WPprodigy. If I were to use some complete version of admin.scss in a child environment, would I not have the same issue?

btw ... when you say run it all together what do you mean? i.e. what technique generates the css files?

**Comment by WPprodigy** [comment]
You can write your own CSS that overrides the default admin styles. You don't have to touch the core style sheets at all. Make sure your custom stylesheet is loaded after the core ones. That's what the cascading stands for in Cascading Style Sheets.

> what technique generates the css files?

`grunt css`: https://github.com/woocommerce/woocommerce/blob/master/Gruntfile.js#L345

`npm run build`: https://github.com/woocommerce/woocommerce/blob/master/package.json#L13

**Comment by BuchyOne** [comment]
We're probably talking at cross purposes. The immediate style problem I can solve.

I wrote my own build script, it loops scss dirs, and only the admin file I referred to  resulted in the issue I described. Whether it is in the core or not is reasonably irrelevant ( that said, I was aware of breaking various laws in editing the core  )

I'll look at the sass config object in the gruntfile.  I would have thought my sass invocation was the same thing, but probably naive.

**Comment by kloon** [comment]
Yea, so running just sass will definitely not work since there are other tasks that need to complete as well.

Try the following tasks in succession `sass, rtlcss, cssmin, concat` and try running it from the root folder not inside the css folder.

**Comment by BuchyOne** [comment]
@kloon 
Thanks for the advice. I am still not able to build the css with my sh script, despite implementing those tasks. The native package build works though, so I am satisfied that it is my (obscure) issue not WC.  I did reverse the repo css with a converter and re-introduced the vars and mixins .. and that worked with my script. 
Cheers.
