### ISSUE TITLE
[3.3 RC 2] Error: Too few arguments to function WC_Regenerate_Images_Request::filter_image_sizes_to_only_missing_thumbnails()

### ISSUE THREAD

**Issue by JimmyAppelt** [woocommerce/woocommerce#18628]
Logging (after changing thumbnail cropping settings):

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WC_Regenerate_Images_Request::filter_image_sizes_to_only_missing_thumbnails(), 2 passed in ~\wp-includes\class-wp-hook.php on line 286 and exactly 3 expected in ~\wp-content\plugins\woocommerce\includes\class-wc-regenerate-images-request.php:149
Stack trace:
#0 ~\wp-includes\class-wp-hook.php(286): WC_Regenerate_Images_Request->filter_image_sizes_to_only_missing_thumbnails(Array, Array)
#1 ~\wp-includes\plugin.php(203): WP_Hook->apply_filters(Array, Array)
#2 ~\wp-admin\includes\image.php(129): apply_filters('intermediate_im...', Array, Array)
#3 ~\wp-content\plugins\woocommerce\includes\class-wc-regenerate-images-request.php(115): wp_generate_attachment_metadata(2088, '~')
#4 ~\wp-content\plugins\woocommerce\includes\libraries\wp-background-proce in ~\wp-content\plugins\woocommerce\includes\class-wc-regenerate-images-request.php on line 149
```

**Comment by WPprodigy** [comment]
Hmm, yea there are definitely only two arguments (one extra) passed into this filter: https://core.trac.wordpress.org/browser/tags/4.9/src/wp-admin/includes/image.php#L129

Asking for 3 here (also when removed): https://github.com/woocommerce/woocommerce/blob/18f9bb408fa98e83ea10727919cbea09575019af/includes/class-wc-regenerate-images-request.php#L112

And the hooked functionality is expecting the third: https://github.com/woocommerce/woocommerce/blob/18f9bb408fa98e83ea10727919cbea09575019af/includes/class-wc-regenerate-images-request.php#L149

**Comment by bor0** [comment]
Thanks for the investigation @WPprodigy! It's very valuable. I don't think the second parameter is a problem since WP 4.4 is listed as the minimum requirement for WC on .org.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/18640
