### ISSUE TITLE
Order cancel fail (invalid _wpnonce)

### ISSUE THREAD

**Issue by Mapteg34** [woocommerce/woocommerce#18638]
WC 3.2.3 + WP 4.8.5

Step to reproduce:
1. Got to checkout with unauthorized user
2. Select paypal express, fill form, continue to paypal site
3. On paypal site change "Cancel and return" link

In that case we go back to site, we is authorized, but order not cancelled because cancel_order() not working (_wpnonce check fail).

In debug i see:
wp_create_nonce with "woocommerce-cancel_order" call with fresh created and authorized user, but 
wp_get_session_token return empty val, and token created invalid...

**Comment by mikejolley** [comment]
Hi there,

Only core bugs should be logged here, and we also ask for certain details such as the system status report which you've missed.

Can you report this via https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues please. Assuming this is our PayPal express extension.

If PPE creates a user and logs them in the nonce may become invalid, so this may need revision. The actual nonce check looks fine in core.

Thanks
