### ISSUE TITLE
Quick one: notification regarding Seller Protection that might be void if "Send shipping details to PayPal instead of billing." checkbox isn't checked.

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce#18632]
914426-zd-woothemes

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. If "Send shipping details to PayPal instead of billing." checkbox isn't checked in WooCommerce -> Settings -> Checkout -> PayPal, shipping information isn't sent to PayPal and Seller Protection doesn't apply.

## Expected/actual behaviour

If someone purchases and cancels the payment with their bank and the product is shipped already, which does happen from time to time - seller takes a loss.

I was expecting to see...

"Seller Protection doesn't apply if this checkbox isn't checked" notification would be a great additional note to see.

## Isolating the problem

This is an enhancement

![screenshot](http://cld.wthms.co/3P1fru.jpg) **Image Link:** http://cld.wthms.co/3P1fru

**Comment by mikejolley** [comment]
This one is covered in the documentation https://docs.woocommerce.com/document/paypal-standard/#section-3 It's also checked by default so you'd have to do turn it off intentionally to be affected.

PayPal payment emails will indicate if seller protection applies or not. They usually also state which address should be used to ship goods.

Seller protection may still apply regardless of this setting if the user ships to the same address as billing. Seller protection may not apply even if this setting is on, if you have it configured to let the user input an address on paypal side outside of WooCommerce. 

So saying "doesn't apply" is not completely accurate.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18637
