### ISSUE TITLE
[3.3 RC 2] Image size changes in customizer doesn't reflect in customizer preview

### ISSUE THREAD

**Issue by yawalkar** [woocommerce/woocommerce#18631]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Install and activate WC 3.3 RC2 from release and import demo
2. Go to customizer and change image size to 100
3. Try changing image cropping to custom with 16:9 ratio

## Expected/actual behavior

When I follow those steps, I see the live preview doesn't update the image sizes with what I set in the customizer settings.

I was expecting to see the image sizes with the mentioned dimensions and cropping ratio, which worked fine with the RC 1

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

If I revert this function with the RC 1, it works fine - https://github.com/woocommerce/woocommerce/blob/3.3.0-rc.2/includes/class-wc-regenerate-images-request.php#L74-L139

Following are the commits the issue is introduced - 
- https://github.com/woocommerce/woocommerce/commit/c97cc71fb9069603273a430d1da7519c8bb69646#diff-a002e9bbfbe81483977aba8aa0ca3131

- https://github.com/woocommerce/woocommerce/commit/a2bd8b073e4eae1c1f754910ac9f4d68edbf3652#diff-a002e9bbfbe81483977aba8aa0ca3131

**Comment by mikejolley** [comment]
Related to https://github.com/woocommerce/woocommerce/issues/18628
