### ISSUE TITLE
Tax inclusive calculation precision bug

### ISSUE THREAD

**Issue by vendidero** [woocommerce/woocommerce#18653]
Steps to reproduce the issue:

1. Set your WooCommerce tax settings to prices include tax and disable round at subtotal
2. Add a new tax rate with 19% tax
3. Add a new product with price = 580
4. Add the product to cart/checkout. Total taxes now equal 92.61.
5. Complete the checkout and have a look at the data. Tax now equals 92.60.

Seems like within the cart, taxes are calculated with a higher precision which results in failures as soon as the precision is removed (after checkout the item tax is stored as 92.605 which results in a rounded tax of 92.60 instead of 92.61).

If you enable round at subtotal the behaviour is even weirder. In that case 92.61 is being confirmed as tax total to the customer (email, display). If you have a look at the manage order page the line tax equals 92.60 but the total tax equals 92.61. As soon as one saves the order, the total tax is being recalculated to 92.60. 

I guess it would be better to calculate taxes within the cart with the same precision as the taxes are being stored within the database. 

Tested with Woo 3.2 and Woo 3.3 RC2

**Comment by mikejolley** [comment]
> If you enable round at subtotal the behaviour is even weirder.

The nature of that setting will introduce rounding issues in most cases - best to avoid.

**Comment by vendidero** [comment]
yes, but that was only my second test. The primary issue was tested with round at subtotal being disabled.
