### ISSUE TITLE
correct "tested up to WP" version?

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/woocommerce#18654]
I believe WC 3.3 will officially require WP 4.5+.

But https://wordpress.org/plugins/woocommerce/ says WP 4.4,

and the WC readme.txt says WP 4.7. 

Should be standardized to WP 4.5 (?).

**Comment by claudiulodro** [comment]
The updates are [ready to go](https://github.com/woocommerce/woocommerce/blob/4076b203e1041b88428fd502b7a81f7c2649de39/readme.txt#L4-L5) and will be automatically updated on wordpress.org when the newest version is released.

**Comment by GlennMartin1** [comment]
Ok, the readme.txt file says (lines 89-95):

89  = Minimum Requirements =
90 
91 * PHP version 5.2.4 or greater (PHP 5.6 or greater is recommended)
92 * MySQL version 5.0 or greater (MySQL 5.6 or greater is recommended)
93 * Some payment gateways require fsockopen support (for IPN access)
94 * WooCommerce 2.5 requires WordPress 4.1+
95 * WooCommerce 2.6 requires WordPress 4.4+
96


I thought you'd want a new line added there about WC 3.3. Your call.

**Comment by claudiulodro** [comment]
See #18658. We're managing all of those at https://docs.woocommerce.com/document/server-requirements/ now. Thanks for clarifying.
