### ISSUE TITLE
shop_page_display dissapeared from REST API after last update

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#18669]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

After the latest update 3.3.0 this message appeared in woocommerce settings dashboard for products:

> Looking for the product display options? They can now be found in the Customizer. Go see them in action here.

And now shop_page_display doesnt appear in rest api settings anymore, and I cant find it:

**Request URL:**
http://localhost:9001/wp-json/wc/v2/settings/products?oauth_consumer_key=ck_82061f667202baaf35b721ca4f14c237934bb9be&oauth_nonce=QTzino&oauth_signature=uOx7z73v%2Fv4sEZTml31xpwM8DiU%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1517338014&oauth_version=1.0

`[{"id":"woocommerce_cart_redirect_after_add","label":"Kj\u00f8p-knapp oppf\u00f8rsel","description":"Omdiriger til handlekurvsside etter vellykket tillegg","type":"checkbox","default":"no","value":"no","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_cart_redirect_after_add"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_enable_ajax_add_to_cart","label":"","description":"Aktiver AJAX-legg-til-handlekurv-knapper for arkiver","type":"checkbox","default":"yes","value":"yes","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_enable_ajax_add_to_cart"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_weight_unit","label":"Vektenhet","description":"Dette styrer i hvilken enhet du vil definere vekter.","type":"select","default":"kg","options":{"kg":"kg","g":"g","lbs":"lb","oz":"oz"},"tip":"Dette styrer i hvilken enhet du vil definere vekter.","value":"kg","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_weight_unit"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_dimension_unit","label":"Dimensjonsenhet","description":"Dette styrer i hvilken enhet du vil definere lengder.","type":"select","default":"cm","options":{"m":"m","cm":"cm","mm":"mm","in":"inch (tomme)","yd":"yard"},"tip":"Dette styrer i hvilken enhet du vil definere lengder.","value":"cm","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_dimension_unit"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_enable_reviews","label":"Aktiver omtaler","description":"Aktiver kundeomtaler","type":"checkbox","default":"yes","value":"yes","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_enable_reviews"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_review_rating_verification_label","label":"","description":"Vis \"bekreftet eier \"-etikett for kundeomtaler","type":"checkbox","default":"yes","value":"yes","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_review_rating_verification_label"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_review_rating_verification_required","label":"","description":"Kundeomtaler kan kun lages av \"bekreftede eiere\"","type":"checkbox","default":"no","value":"no","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_review_rating_verification_required"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_enable_review_rating","label":"Produktrangeringer","description":"Aktiver stjernerangering for kundeomtaler","type":"checkbox","default":"yes","value":"yes","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_enable_review_rating"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_review_rating_required","label":"","description":"Stjernerangering skal v\u00e6re p\u00e5krevd, ikke valgfritt","type":"checkbox","default":"yes","value":"yes","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_review_rating_required"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_manage_stock","label":"Administrer lager","description":"Aktiver lagerstyring","type":"checkbox","default":"yes","value":"yes","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_manage_stock"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_hold_stock_minutes","label":"Hold lager (minutter)","description":"Hold lager (for ubetalte ordrer) i x minutter. N\u00e5r denne grensen er n\u00e5dd, vil den ventende ordren bli kansellert. La st\u00e5 tom for \u00e5 deaktivere.","type":"number","default":"60","value":"60","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_hold_stock_minutes"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_notify_low_stock","label":"Varsler","description":"Aktiver varsler for lite p\u00e5 lager","type":"checkbox","default":"yes","value":"yes","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_notify_low_stock"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_notify_no_stock","label":"","description":"Aktiver varsler for tomt p\u00e5 lager","type":"checkbox","default":"yes","value":"yes","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_notify_no_stock"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_stock_email_recipient","label":"Meldingsmottaker(e)","description":"Skriv inn mottakere (kommaseparert) som skal motta dette varselet.","type":"text","default":"test@test.no","tip":"Skriv inn mottakere (kommaseparert) som skal motta dette varselet.","value":"test@test.no","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_stock_email_recipient"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_notify_low_stock_amount","label":"Terskel for lite p\u00e5 lager","description":"N\u00e5r produktlageret kommer p\u00e5 dette antallet vil du bli varslet p\u00e5 e-post.","type":"number","default":"2","tip":"N\u00e5r produktlageret kommer p\u00e5 dette antallet vil du bli varslet p\u00e5 e-post.","value":"2","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_notify_low_stock_amount"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_notify_no_stock_amount","label":"Terskel for tomt p\u00e5 lager","description":"N\u00e5r produktlageret kommer p\u00e5 dette antallet lagerstatus vil endre til \"tomt p\u00e5 lager\" og du vil bli varslet p\u00e5 e-post. Denne innstillingen p\u00e5virker ikke eksisterende produkter som er \"p\u00e5 lager\".","type":"number","default":"0","tip":"N\u00e5r produktlageret kommer p\u00e5 dette antallet lagerstatus vil endre til \"tomt p\u00e5 lager\" og du vil bli varslet p\u00e5 e-post. Denne innstillingen p\u00e5virker ikke eksisterende produkter som er \"p\u00e5 lager\".","value":"0","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_notify_no_stock_amount"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_hide_out_of_stock_items","label":"Tomt p\u00e5 lager synlighet","description":"Skjul varer som ikke er p\u00e5 lager fra katalogen","type":"checkbox","default":"no","value":"no","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_hide_out_of_stock_items"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_stock_format","label":"Lagervisningsformat","description":"Dette styrer hvordan lagerantaller vises i front-end.","type":"select","default":"","options":{"":"Alltid vis antall p\u00e5 lager, f.eks. \"12 p\u00e5 lager\"","low_amount":"Kun vis antall p\u00e5 lager n\u00e5r antallet er lavt, f.eks. \"Kun 2 p\u00e5 lager\"","no_amount":"Aldri vis antall p\u00e5 lager"},"tip":"Dette styrer hvordan lagerantaller vises i front-end.","value":"","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_stock_format"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_file_download_method","label":"Filnedlastingsmetode","description":"Tvinge nedlastinger vil holde URL'er skjult, men enkelte servere kan ikke betjene store filer p\u00e5 en p\u00e5litelig m\u00e5te. Hvis st\u00f8ttet, kan <code>X-Accel-Redirect<\/code> \/ <code>X-Sendfile<\/code> brukes for \u00e5 ordne nedlastinger i stedet (serveren krever <code>mod_xsendfile<\/code>).","type":"select","default":"force","options":{"force":"Tving nedlastinger","xsendfile":"X-Accel-Redirect\/X-Sendfile","redirect":"Kun omdiriger"},"tip":"Tvinge nedlastinger vil holde URL'er skjult, men enkelte servere kan ikke betjene store filer p\u00e5 en p\u00e5litelig m\u00e5te. Hvis st\u00f8ttet, kan <code>X-Accel-Redirect<\/code> \/ <code>X-Sendfile<\/code> brukes for \u00e5 ordne nedlastinger i stedet (serveren krever <code>mod_xsendfile<\/code>).","value":"force","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_file_download_method"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_downloads_require_login","label":"Tilgangsbegrensning","description":"Nedlasting krever innlogging","type":"checkbox","default":"no","tip":"Denne innstillingen gjelder ikke for gjestekj\u00f8p.","value":"no","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_downloads_require_login"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}},{"id":"woocommerce_downloads_grant_access_after_payment","label":"","description":"Gi tilgang til nedlastbare produkter etter betaling","type":"checkbox","default":"yes","tip":"Aktiver dette valget for \u00e5 gi tilgang til nedlastinger n\u00e5r ordrer er \"under behandling\", og ikke \"ferdig\".","value":"yes","_links":{"self":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products\/woocommerce_downloads_grant_access_after_payment"}],"collection":[{"href":"http:\/\/localhost:9001\/index.php\/wp-json\/wc\/v2\/settings\/products"}]}}]`

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by WPprodigy** [comment]
Mmm, yea has to do with https://github.com/woocommerce/woocommerce/pull/18108. The REST API endpoint only looks at what's registered on the settings pages I believe: https://github.com/woocommerce/woocommerce/blob/6e08ff0284c95883154988b675c6c169caf695c9/includes/api/class-wc-rest-setting-options-controller.php#L153

**Comment by claudiulodro** [comment]
Maybe we can add some backwards compatibility handling using the `'woocommerce_settings-' . $group_id` filter? There may be a better way, though.

**Comment by mikejolley** [comment]
Thinking ahead, would it be better to put all settings into one endpoint and built settings pages that work with the REST API? Then store and core can run essentially with the same codebase. Moving settings in core should not break endpoints. @claudiosanches @justinshreve

**Comment by mikejolley** [comment]
Looking at the schema, in this case `shop_page_display` is not mentioned specifically. The schema lets you pull in defined settings by group and since this is no longer in any group, it is not exposed.

I don't think we should insert settings in the current settings API because it would be inconsistent with whats in admin. But as I said above, a more formal settings schema would be good in v3 so moving/adding/removing things in the UI does not affect the API. This isn't the first time and won't be the last time settings are changed.

**Comment by steffanhalv** [comment]
@mikejolley So **shop_page_display** setting wont be available before v3 then?

**Comment by mikejolley** [comment]
Does not look like it. It's data, not part of the schema.

**Comment by WPprodigy** [comment]
Having all settings built first into a REST API endpoint would also benefit https://github.com/woocommerce/woocommerce/issues/13089
