### ISSUE TITLE
Add email invoice VAT display by defaut like checkout display

### ISSUE THREAD

**Issue by mikecastrodemaria** [woocommerce/woocommerce#18661]
Hi, 

In your template email-order-details.php, you display the order without the VAT  ( woocommerce_tax_total_display() ) . 

Who is a problem for all EU sellers who needs to display this on their invoices. Can you cut and past the code from review-order.php , line 87 to 101 to your email-order-detail.php and plain/email-order-detail.php ?

`		<?php if ( wc_tax_enabled() && 'excl' === WC()->cart->tax_display_cart ) : ?>
			<?php if ( 'itemized' === get_option( 'woocommerce_tax_total_display' ) ) : ?>
				<?php foreach ( WC()->cart->get_tax_totals() as $code => $tax ) : ?>
					<tr class="tax-rate tax-rate-<?php echo sanitize_title( $code ); ?>">
						<th><?php echo esc_html( $tax->label ); ?></th>
						<td><?php echo wp_kses_post( $tax->formatted_amount ); ?></td>
					</tr>
				<?php endforeach; ?>
			<?php else : ?>
				<tr class="tax-total">
					<th><?php echo esc_html( WC()->countries->tax_or_vat() ); ?></th>
					<td><?php wc_cart_totals_taxes_total_html(); ?></td>
				</tr>
			<?php endif; ?>
		<?php endif; ?>
`
It will be helpful to avoid users of your plugin search about this code for this feature, which is mandatory for all professional sellers in Europe.

Thanks,
mike

**Comment by mikejolley** [comment]
We do show tax in emails. Depending on the settings it may be a row or it may be after the order total.

**Comment by mikejolley** [comment]
Seems fine. Need more examples/details if there is really an issue.
