### ISSUE TITLE
Using `product_type_options` filter to remove "downloadable/virtual" does not remove from admin products list filter.

### ISSUE THREAD

**Issue by benhuson** [woocommerce/woocommerce#18660]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Use the following code to remove downloadable/virtual product options from the product meta box when editing a product:

```
function my_remove_product_type_options( $options ) {
	if ( isset( $options['virtual'] ) ) {
		unset( $options['virtual'] );
	}
	if ( isset( $options['downloadable'] ) ) {
		unset( $options['downloadable'] );
	}
	return $options;
}
add_filter( 'product_type_options', 'my_remove_product_type_options' );
```

When I view the product list admin page the "Filter by Product Type" menu at the top still allows me to filter by downloadable/virtual products.

I would expect that as this filter removes them from the admin box (so in affect you cannot add this type of product) then it should also remove them from the filter options?

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

Discovered on a client development site for which I cannot currently give comprehensive details but as it's a UI/question issue rather than a bug, hopefully that's OK.

<details>
```
WC Version: 3.2.6
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
```
</details>

**Comment by claudiosanches** [comment]
`product_type_options` does not unregister those option across the whole WooCommerce.
In can remove those options from the dropdown using the `woocommerce_product_filters` filter.

**Comment by rudrastyh** [comment]
It is also possible to do with woocommerce_products_admin_list_table_filters filter
