### ISSUE TITLE
Typos in 2 translateable strings that should be corrected

### ISSUE THREAD

**Issue by transl8or** [woocommerce/woocommerce#18662]
I found tiny typos in 2 strings the latest WooCommerce Version.

1) "How should products **by** sorted in the catalog by default?" can be found in line 360 of:
includes/customizer/class-wc-shop-customizer.php
  It should probably be: "How should products **be** sorted..."

2) "Secret key used to generate a hash of the delivered webhook and provided in the request headers. This **will** default is a MD5 hash from the current user's ID|username if not provided." can be found in line 151 and 647 of:
includes/api/v1/class-wc-rest-webhooks-controller.php
 The second sentence might better be something like: "This **by** default is a MD5 hash ..."

**Comment by kloon** [comment]
Fixed in #18682
