### ISSUE TITLE
Gutenberg Products Block

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#18663]
Development for the Gutenberg Products block has moved to [a feature plugin](https://github.com/woocommerce/woocommerce-gutenberg-products-block). This makes it much easier for anyone to try out the Products block. Just follow the steps at the repo.

When development is complete, the feature plugin will be merged into the main WooCommerce plugin.

I'm leaving this issue open over here for discussion, feedback, questions, etc.

**Comment by spencerfinnell** [comment]
Is the end goal to be the Gutenberg-version of the existing shortcode and all supported attributes? Is the plan to extend, limit, or duplicate functionality?

https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-products.php#L114-L131

**Comment by claudiulodro** [comment]
The plan for the Products block at the moment is that it will essentially be an easy-to-use shortcode builder (but you won't have to ever see or learn about the shortcodes). This way we can leverage the shortcode processing and rendering without having to build out and maintain a separate system for the Products block. 

This should also make it very backwards-compatible and work properly even if Gutenberg editing is turned off.

**Comment by spencerfinnell** [comment]
Yeah I think generating a shortcode vs. total server side rendering is a good idea for the time being.

**Comment by mikejolley** [comment]
Since this is being developed and issues tracked over on https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues, and there are currently no core todos for this, let's close this issue and reopen when it's time to integrate it into core (whatever milestone that may be) :)

Probably 4.0.0 as indicated.
