### ISSUE TITLE
Products block: Backwards compatibility

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#18670]
If a page has the products shortcode already on it (from posts created using the classic editor) convert the shortcode into a pre-populated Products block. More investigating will need to be done to see if this is possible, but I believe Gutenberg 2.1 has some shortcode handling features so it should be possible.

**Comment by WPprodigy** [comment]
Possible use case for the transformations api: https://github.com/WordPress/gutenberg/issues/4578

**Comment by claudiulodro** [comment]
https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/8
