### ISSUE TITLE
ERROR 500 Conflict with contact form

### ISSUE THREAD

**Issue by Simone4e** [woocommerce/woocommerce#18689]
Hi support,

I have this issues when i upgrade core to last versione of woocomerce.
Active debug and error is:
Notice: wpcf7_add_shortcode è deprecato dalla versione 4.6! Utilizza invece wpcf7_add_form_tag. in /home/adminbetto/domains/bettoniauto.com/private_html/wp-content/plugins/contact-form-7/includes/functions.php on line 360

can help me?

**Comment by Simone4e** [comment]
i find the real conflict with w3 total cache

**Comment by mikejolley** [comment]
Thanks for the update. The notice above I don't think would cause error 500, but comes from CF7 not WC.
