### ISSUE TITLE
[3.3] Shop page is empty after update.

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#18683]
Hi 

in woo 3.30 the shop page is completely empty. No products !  In any previous version it is fine.

What code or functions changed?

Global file called "woocommerce.php" template in theme root is not called anymore?

What changed?

**Comment by WPJobs** [comment]
Hello!
The same for me! /shop/ opens page.php template, and it looks it doesn't know that my theme has woocommerce.php

when i change something in page.php, i see the changes but no products, when i change something in woocommerce.php i see no products and no changes.

in woocommerce 3.2 everything was great.

How to fix the problem?

**Comment by virajsonagra** [comment]
Same issue with me.

I have updated to woocommerce 3.3.0 in previous version everything working proper but suddenly after update now it's calling page.php template.

There is no woocommerce.php in my theme folder.

**Comment by daviddarke** [comment]
Same, woocommerce.php not being read.

**Comment by mikejolley** [comment]
`woocommerce.php` and other templates will NOT be read unless your theme declares support for woocommerce.

https://woocommerce.wordpress.com/2017/12/09/wc-3-3-will-look-great-on-all-the-themes/

Add `add_theme_support( 'woocommerce' );` to your theme functions file if you want to stick with this method

If theme support is not declared, the shop page and other content will be loaded inside regular pages as shortcodes. If this is blank right now, it may be a permalink issue since the shop page will no longer be an archive, but a page. I'll see if we need to do anything our side to make sure that changes back to a page.

**Comment by WPJobs** [comment]
Hey, @mikejolley i already did that on init action

```
/** function from my class **/
add_action( 'init', array( $this, 'add_theme_support'));

function add_theme_support() {
add_theme_support( 'woocommerce' );
}
```

before updating to 3.3.0 already worked fine

**Comment by mikejolley** [comment]
Not much I can do without some example links or possibly access at this point.

**Comment by WPJobs** [comment]
@mikejolley can i send you private message with FTP access?

**Comment by mikejolley** [comment]
@WPJobs email on my profile

**Comment by BackuPs** [comment]
@mikejolley 
the first line in my theme since day one is 

`add_theme_support( 'woocommerce' );`

It worked until 3.2.6 it stopped working on 3.30  it is not related to adding that line of code. We have that in our theme for years now. The given solution is not ok !

![woocommerce](https://user-images.githubusercontent.com/6078370/35628344-e75ad5f2-069b-11e8-820b-ccf46eaf6544.png)

**Comment by mikejolley** [comment]
@BackuPs again, without access we cannot really look into the problem. Clearly your theme is doing something unanticipated .

**Comment by BackuPs** [comment]
Hi
@mikejolley
If i remove add_theme_support('woocommerce'); from my code it works again and shops the shop page content following the page template.

but with that line it is completely empty.

I will setup a website with wordpress in a spoof for you.  How can i email you all the details as this is not clear to me?

> 
  @WPJobs email on my profile

**Comment by BackuPs** [comment]
> Clearly your theme is doing something unanticipated .  ???

it worked since 2011 until version 3.30 came out.

**Comment by mikejolley** [comment]
@BackuPs my email address is on my github profile.

**Comment by claudiosanches** [comment]
`init` is too late for it`.

Need to try this:

```php
function my_custom_wc_theme_support() {
    add_theme_support( 'woocommerce' );
}

add_action( 'after_setup_theme', 'my_custom_wc_theme_support' );
```

**Comment by BackuPs** [comment]
@mikejolley 
Ok it gets even weirder. I have setup a clean website so i could give you logins. I imported the default csv that comes with woo and it works with my theme. 

Any existing website however is not working and showing me a empty shop page. Any idea?

**Comment by mikejolley** [comment]
@BackuPs if you want to share access to the broken one I can look into it.

**Comment by BackuPs** [comment]
@mikejolley  We are trying to make a duplicate for you. Once done i will send logins

**Comment by BackuPs** [comment]
another question did the code change for number of products to list in the shop page and the columns? As all my settings and actions i have in my theme dont work anymore even in the website that is showing the shoppage content (the fresh clean install)

**Comment by WPJobs** [comment]
I can confirm that this fixed my problem, thank you so much for a quick response! Have a great day!

```
function my_custom_wc_theme_support() {
    add_theme_support( 'woocommerce' );
}

add_action( 'after_setup_theme', 'my_custom_wc_theme_support' );
```

**Comment by mikejolley** [comment]
@BackuPs ^

I can confirm that if you add theme support after init, you will get a blank page. It's called too late.

**Comment by mikejolley** [comment]
We can guard against this. See https://github.com/woocommerce/woocommerce/pull/18720

**Comment by BackuPs** [comment]
Hi

`function my_custom_wc_theme_support() {
    add_theme_support( 'woocommerce' );
}

add_action( 'after_setup_theme', 'my_custom_wc_theme_support' );`

The theme has already a action called after_setup_theme. I moved the woocommerce add_theme_support( 'woocommerce' ); into that function. The woocommerce.php is called now but the shop page is still empty.

But on a clean install it just works. I will setup a domain and provide the logins.

Thanks

**Comment by BackuPs** [comment]
@mikejolley

After banging my head against the wall several times I finally figured out what is going on.

We moved the website to a test server and it started working instantly.

**adding this function is not enough.**

`function my_custom_wc_theme_support() {
add_theme_support( 'woocommerce' );
}

add_action( 'after_setup_theme', 'my_custom_wc_theme_support' );`

Apparently woo is caching some settings. You had to switch themes. Any theme will do. after the switch, switch back to the old theme with the modified add_theme_support function code. And all works.

I tested this now on 3 sites all with similar results. If you do NOT switch themes the shop page remains empty although the woocommerce.php is called in the theme root folder.

I guess this has something todo with the new woocommerce version

Another question i have (it is not related to the problem about empty shoppage) is that i see that the shop page switched from 4 columns default to 3 columns.  Is that correct? Is this documented somewhere. are there more of these unexpected changes?

thank you !

**Comment by mikejolley** [comment]
Both of those issues will resolve in 3.3.1.
Thanks

**Comment by lemoner-vikram** [comment]
Great guys!
Your updated help me...

**Comment by weitls** [comment]
I am getting this error on all my pages. 

Fatal error: Uncaught Error: Call to undefined function wc_get_loop_prop() in /home/south678/public_html/wp-content/plugins/genesis-connect-woocommerce/lib/template-loader.php:268 Stack trace: #0 /home/south678/public_html/wp-content/plugins/genesis-connect-woocommerce/templates/taxonomy.php(58): genesiswooc_content_product() #1 /home/south678/public_html/wp-includes/class-wp-hook.php(286): genesiswooc_product_taxonomy_loop('') #2 /home/south678/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /home/south678/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /home/south678/public_html/wp-content/themes/genesis/lib/framework.php(39): do_action('genesis_loop') #5 /home/south678/public_html/wp-content/plugins/genesis-connect-woocommerce/templates/taxonomy.php(65): genesis() #6 /home/south678/public_html/wp-includes/template-loader.php(74): include('/home/south678/...') #7 /home/south678/public_html/wp-blog-header.php(19): require_once('/home/south678/...') #8 /home/south in /home/south678/public_html/wp-content/plugins/genesis-connect-woocommerce/lib/template-loader.php on line 268

**Comment by GianniSoZo** [comment]
Also, make sure you don't have any old fixes to get Woo to play nicely with Genesis in the theme that may be conflicting with the latest update. This was the offending code in my clients function file:

`/**********************************
*
* Integrate WooCommerce with Genesis.
*
* Unhook WooCommerce wrappers and
* Replace with Genesis wrappers.
*
* Reference Genesis file:
* genesis/lib/framework.php
*
* @author AlphaBlossom / Tony Eppright
* @link http://www.alphablossom.com
*
**********************************/

// Add WooCommerce support for Genesis layouts (sidebar, full-width, etc) - Thank you Kelly Murray
add_post_type_support( 'product', 'genesis-layouts' );

// Unhook WooCommerce Sidebar - use Genesis Sidebars instead
remove_action( 'woocommerce_sidebar', 'woocommerce_get_sidebar', 10 );

// Unhook WooCommerce wrappers
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10 );
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10 );

// Hook new functions with Genesis wrappers
add_action( 'woocommerce_before_main_content', 'youruniqueprefix_my_theme_wrapper_start', 10 );
add_action( 'woocommerce_after_main_content', 'youruniqueprefix_my_theme_wrapper_end', 10 );

// Add opening wrapper before WooCommerce loop
function youruniqueprefix_my_theme_wrapper_start() {

    do_action( 'genesis_before_content_sidebar_wrap' );
    genesis_markup( array(
        'html5' => '<div %s>',
        'xhtml' => '<div id="content-sidebar-wrap">',
        'context' => 'content-sidebar-wrap',
    ) );

    do_action( 'genesis_before_content' );
    genesis_markup( array(
        'html5' => '<main %s>',
        'xhtml' => '<div id="content" class="hfeed">',
        'context' => 'content',
    ) );
    do_action( 'genesis_before_loop' );

}

/* Add closing wrapper after WooCommerce loop */
function youruniqueprefix_my_theme_wrapper_end() {

    do_action( 'genesis_after_loop' );
    genesis_markup( array(
        'html5' => '</main>', //* end .content
        'xhtml' => '</div>', //* end #content
    ) );
    do_action( 'genesis_after_content' );

    echo '</div>'; //* end .content-sidebar-wrap or #content-sidebar-wrap
    do_action( 'genesis_after_content_sidebar_wrap' );

}
add_action( 'pre_get_posts', 'custom_pre_get_posts_query' );

function custom_pre_get_posts_query( $q ) {

	if ( ! $q->is_main_query() ) return;
	if ( ! $q->is_post_type_archive() ) return;

	if ( ! is_admin() && is_shop() ) {

		$q->set( 'tax_query', array(array(
			'taxonomy' => 'product_cat',
			'field' => 'slug',
			'terms' => array( 'sold' ), // Don't display products in the sold category on the shop page
			'operator' => 'NOT IN'
		)));

	}

	remove_action( 'pre_get_posts', 'custom_pre_get_posts_query' );

}`

**Comment by weitls** [comment]
I transitioned to Shopify. I was not able to login after to update any
information. All my links have been redirected.
Did you notice something out of place?
My website is
Https://southernchiqueboutique.com/
