### ISSUE TITLE
Cannot Hide Product category in product page.

### ISSUE THREAD

**Issue by Sidkt** [woocommerce/woocommerce#18681]
Hi, I added on product in shop with product category, and in setting i selected products only but still it shows categories there cant understand why? 

![image](https://user-images.githubusercontent.com/35454239/35605814-4db01a7c-0671-11e8-832c-9cb2679bc880.png)

**Comment by WPprodigy** [comment]
This is an issue we are currently looking into. See: https://github.com/woocommerce/woocommerce/issues/1867.

The problem has to do with outdated WooCommerce templates in the theme or a plugin. The next update, WooCommerce 3.3.1, will have a patch that will help make this work better for themes that aren't being updated.

**Comment by willgorham** [comment]
^ #18676

**Comment by WPprodigy** [comment]
Oops, yep that one! Thanks :)

**Comment by Sidkt** [comment]
Just to make sure changing code in wc-template-functions.php should fix this problem for now, is that right?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/18674
