### ISSUE TITLE
woocommerce_catalog_rows/columns only updated on Theme switch

### ISSUE THREAD

**Issue by maddisondesigns** [woocommerce/woocommerce#18680]
WooCommerce 3.3 adds a new Customizer option to set the number of _Products per row_ and _Rows per page_. A theme can set the defaults for these two values with `add_theme_support`.  The problem is though, that these default values from `add_theme_support` are only updated in the database using the `after_switch_theme` hook.

See... https://github.com/woocommerce/woocommerce/blob/de4cd97b0031318bdd4e0d079eb5fe2e1ee39788/includes/wc-template-functions.php#L370

Prior to WC3.3, the default number of products per row was 4. WC3.3 now defaults that to 3. If a site updates from WC3.2 to WC3.3, their site changes from showing 4 products per row to 3 products per row. The number of rows per page that they see, also changes.

If a user is running a theme that gets updated to include the new `add_theme_support` options (specifically, the 'default_rows' & 'default_columns' options), WooCommerce will completely ignore them as the database options for these two values are only updated upon Theme Switch, which is obviously not going to occur for someone simply updating their theme and WooCommerce.

The only way to get these values in the database without switching themes is to use the new Customizer options. A user shouldn't have to update these values just because WC updated. The default number of products per row for WC3.3 should've remained the same as previously, but it hasn't which forces users to fix the layout of their store.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Start with WooCommerce 3.2.x
2. Activate Theme that uses only `add_theme_support( 'woocommerce' );` (or even without this option, the same issue occurs)
3. View Shop page and note number of products on display (eg. products per row)
4. Update WooCommerce to v3.3
5. Update theme to include new `product_grid` array in `add_theme_support` with `'default_rows'` and `'default_columns'` values (the columns values should be 4 as that's what the default use to be)
6.  View Shop page and note number of products on display has now changed to new v3.3 default (3 cols x 4 rows). Also note that new default values aren't being used.

## Expected/actual behavior

When I update WooCommerce, I should see the same number of products per row in the shop as per the previous version

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/) - Tested with my own theme and TwentySeventeen
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://dev.wordpress-test.com
Site URL: http://dev.wordpress-test.com
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: wp_
Total Database Size: 12.39MB
Database Data Size: 10.18MB
Database Index Size: 2.21MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_bp_activity: Data: 0.02MB + Index: 0.16MB
wp_bp_activity_meta: Data: 0.02MB + Index: 0.03MB
wp_bp_friends: Data: 0.02MB + Index: 0.03MB
wp_bp_messages_messages: Data: 0.02MB + Index: 0.03MB
wp_bp_messages_notices: Data: 0.02MB + Index: 0.02MB
wp_bp_messages_recipients: Data: 0.02MB + Index: 0.08MB
wp_bp_notifications: Data: 0.02MB + Index: 0.11MB
wp_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB
wp_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB
wp_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB
wp_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.14MB + Index: 0.02MB
wp_comments: Data: 0.02MB + Index: 0.01MB
wp_hms_testimonials: Data: 0.02MB + Index: 0.00MB
wp_hms_testimonials_cf: Data: 0.02MB + Index: 0.00MB
wp_hms_testimonials_cf_meta: Data: 0.02MB + Index: 0.02MB
wp_hms_testimonials_groups: Data: 0.02MB + Index: 0.00MB
wp_hms_testimonials_group_meta: Data: 0.02MB + Index: 0.03MB
wp_hms_testimonials_templates: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 1.87MB + Index: 0.10MB
wp_postmeta: Data: 0.53MB + Index: 0.18MB
wp_posts: Data: 1.88MB + Index: 0.11MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_smooth_slider: Data: 0.00MB + Index: 0.00MB
wp_smooth_slider_meta: Data: 0.00MB + Index: 0.00MB
wp_smooth_slider_postmeta: Data: 0.00MB + Index: 0.00MB
wp_sp_sliders: Data: 0.01MB + Index: 0.00MB
wp_sp_slides: Data: 0.03MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.01MB + Index: 0.02MB
wp_term_relationships: Data: 0.01MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 0.02MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.02MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 2.52MB + Index: 0.00MB
wp_wfHits: Data: 0.08MB + Index: 0.05MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.03MB
wp_wfStatus: Data: 0.17MB + Index: 0.13MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

accordion_menu: 1
acf: 5
acf-field: 25
acf-field-group: 6
attachment: 119
boxes: 3
course: 2
custom_css: 1
customize_changeset: 2
envira: 2
et_pb_layout: 32
forum: 2
homecpt: 1
module: 13
module_response: 1
myportfolio: 5
nav_menu_item: 14
optionsframework: 7
page: 64
post: 31
product: 26
product_variation: 18
revision: 404
shop_coupon: 2
soliloquy: 1
sp_calendar: 1
sp_column: 8
sp_event: 6
sp_list: 4
sp_metric: 2
sp_outcome: 3
sp_performance: 5
sp_player: 12
sp_result: 3
sp_staff: 1
sp_statistic: 4
sp_table: 1
sp_team: 3
tailor_templates: 1
testimonial: 4
topic: 3
tribe_events: 1
tribe_venue: 1
unit: 4
wafs: 1
wooframework: 125
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.0-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: configurable (configurable)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #1638 - /shop/
Cart: #1639 - /cart/
Checkout: #1640 - /checkout/
My account: #1641 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by WPprodigy** [comment]
While looking into this, I wanted to point out two potentially related problem that have to do with column counts:

1) `loop_shop_columns` filter might not quite work as it once did: https://wordpress.org/support/topic/cannot-change-shop-page-columns-woocommerce-3-3-update/

2) Powerpack problems with column counts: 930523-zd-woothemes

**Comment by maddisondesigns** [comment]
@WPprodigy it would also be worth double checking that it hasn't caused issues with the `loop_shop_per_page` filter as well

**Comment by mikejolley** [comment]
Switching themes *is* the only time defaults should be set. 

As for themes still using `loop_shop_columns` thats fine - it's still supported and the column settings in the customizer will be hidden.

The part we do need to patch is carrying across the old default of 4 for people updating, rather than the new default of 3.

**Comment by mikejolley** [comment]
@WPprodigy 

1. Works still
2. Seems related to the thumbnail cropping issue separate to this
3. Due to default from 3 to 4, resolving in a PR.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18701

**Comment by Aninstance** [comment]
Not sure whether directly related to this issue, but following the update when the "Products Per Row" option was moved to the Customiser (of which I'm not a fan -, slow and annoying, but that's besides the point), I now get an error whenever I try to change the setting and Publish the result, which reports: "Unable to save due to 1 invalid setting."

**Comment by WPprodigy** [comment]
Please open a new support thread in the [WordPress.org](http://wordpress.org/support/plugin/woocommerce) forum. 

First be sure to rule out other plugin/theme conflicts: https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4.
