### ISSUE TITLE
Order details table in email have "Test" above it 

### ISSUE THREAD

**Issue by Seeder101** [woocommerce/woocommerce#18684]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. confirm a new checkout and the customer gets an email
2. the default template email has a "Test" word before the order details table 
3. this problem exists on both side the customer and the shop manager's email for new items checkout for pending messages for proceeding messages...completed messages 

## Expected/actual behavior

When I follow those steps, I see...

"Test" word before the order details table 

I was expecting to see...
no "Test" word before the order details table 

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

now this issue occurred after updating WC from the wordpress admin panel 
and I downloaded the plugin directly from https://wordpress.org/plugins/woocommerce/#description
and I went to templates/emails/emails-order-details.php and found the "TEST" string 
here's the source 
https://plugins.svn.wordpress.org/woocommerce/tags/3.3.0/templates/emails/email-order-details.php

honestly I couldn't find a way to directly contact the wordpress folks and I'm more familiar with git and github now ironically I checked the github source and I found that the typo was fixed here https://github.com/woocommerce/woocommerce/commit/7290d6e42e211b75e65acead6d9e4eca119738da

**Comment by kloon** [comment]
Fixed in #18686
