### ISSUE TITLE
Product images are not cropped anymore

### ISSUE THREAD

**Issue by el-presidente** [woocommerce/woocommerce#18690]
Some product images aren't cropped 1:1 now both in product categories and products.

![screen shot 2018-01-31 at 09 29 29](https://user-images.githubusercontent.com/937382/35612999-ecf6dd98-066a-11e8-9a50-9e1f1e934ede.png)
![screen shot 2018-01-31 at 09 29 19](https://user-images.githubusercontent.com/937382/35613000-ed169390-066a-11e8-8ae2-076479f4bea4.png)
![screen shot 2018-01-31 at 09 28 06](https://user-images.githubusercontent.com/937382/35613001-ed356e96-066a-11e8-9054-5c274f127b9a.png)

Disabled all plugins. I'm running the newest Storefront theme, I've emptied the caches and saved the settings again. Same result so have rolled back now.

*Rant* I don't know who handles your testing but I would recommend hiring someone who's not a developer. And why you moved the product image settings to the customizer has left me bamboozled. It's so bloated, slow and can't work responsively.*Rant over*

**Comment by WillBrubaker** [comment]
Just had a chat with a user experiencing this same issue

**Comment by mikejolley** [comment]
@el-presidente @WillBrubaker If image regeneration is not happening (or not happening fast enough) you can manually do it with https://en-gb.wordpress.org/plugins/regenerate-thumbnails/ still. It will sort out catalog thumbs.

The single image is always uncropped and displayed at the aspect ratio you upload.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18716
