### ISSUE TITLE
After WC update categories and some products appears

### ISSUE THREAD

**Issue by Riskobo** [woocommerce/woocommerce#18699]
After woocommerce update categories are duplicated and some products appears on page. Can anyone help me please ASAP!
THis is the site http://dzin.webshop.dzinsolutions.rs/prodavnica/ 
Thanks
Best Regards

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/18674

**Comment by Riskobo** [comment]
Not working for me

**Comment by mikejolley** [comment]
It's an issue, not a solution.
