### ISSUE TITLE
API: Can't Delete a Webhook

### ISSUE THREAD

**Issue by noriods** [woocommerce/woocommerce#18692]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Open Postman.
2. Set request type to DELETE.
3. Add in Read/Write API credentials to Auth tab.
4. Set URL to https://example.com/wp-json/wc/v2/webhooks/14?force=true (Where 14 is the valid ID of a webhook.)
5. Click Send.

## Expected/actual behavior

When I follow those steps, I see "<b>Fatal error</b>:  Uncaught Error: Call to a member function get_id() on null in /path/to/wp/wp-content/plugins/woocommerce/includes/api/class-wc-rest-webhooks-controller.php:42"

I was expecting to see a JSON response indicating a successful webhook deletion.

## Isolating the problem

- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
WordPress environment
--
WC version: |   | 3.3.0
Log directory writable: |   | /path/to/wp/wp-content/uploads/wc-logs/
WP version: |   | 4.9.2
WP multisite: |   | –
WP memory limit: |   | 512 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US
```
</details>

**Comment by noriods** [comment]
The real issue seems to be that `$webhook = wc_get_webhook( $id );` on line 40 returns null. Haven't investigated further.

**Comment by mikejolley** [comment]
It returns null if the webhook cannot be loaded/cannot be found. Deleting is working my side however there are other notices and there are some missing checks in the API. Patching now.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18693

**Comment by Shaurov05** [comment]
we have to use `force=true` in the query params.
