### ISSUE TITLE
WC customizer sections changing body class in 3.3.0

### ISSUE THREAD

**Issue by theleemon** [woocommerce/woocommerce#18697]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to any product category page of a site with WC installed
2. Open the Customizer
3. Go to the "Product Catalog" or "Product Images" sections of the new "WooCommerce" Customizer section

--

## Expected/actual behavior

When I follow those steps, I see...

The page refreshes and the body class is changed to "home page-template-default page page-id-nnn logged-in right-sidebar woocommerce-active customize-partial-edit-shortcuts-shown"

I was expecting to see...

The body class is unchanged. That is: "archive tax-product_cat term-xxxxxxx term-nnn logged-in woocommerce woocommerce-page right-sidebar woocommerce-active customize-partial-edit-shortcuts-shown"

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://www.xxxxxxxxxxxxxxxxxxxxx.com
Site URL: http://www.xxxxxxxxxxxxxxxxxxxxx.com
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.27
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 5000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: ea_
Tamaño total de la base de datos: 25.15MB
Tamaño de los datos de la base de datos: 19.65MB
Tamaño del índice de la base de datos: 5.50MB
ea_woocommerce_sessions: Datos: 7.02MB + Índice: 0.02MB
ea_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB
ea_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB
ea_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.05MB
ea_woocommerce_order_items: Datos: 0.17MB + Índice: 0.08MB
ea_woocommerce_order_itemmeta: Datos: 1.52MB + Índice: 0.66MB
ea_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB
ea_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.05MB
ea_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB
ea_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.05MB
ea_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB
ea_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB
ea_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB
ea_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB
cerber_acl: Datos: 0.00MB + Índice: 0.00MB
cerber_blocks: Datos: 0.00MB + Índice: 0.00MB
cerber_countries: Datos: 0.02MB + Índice: 0.00MB
cerber_lab: Datos: 0.00MB + Índice: 0.00MB
cerber_lab_ip: Datos: 0.02MB + Índice: 0.00MB
cerber_lab_net: Datos: 0.02MB + Índice: 0.02MB
cerber_log: Datos: 0.27MB + Índice: 0.05MB
ea_commentmeta: Datos: 0.08MB + Índice: 0.11MB
ea_comments: Datos: 0.39MB + Índice: 0.44MB
ea_ewwwio_images: Datos: 0.31MB + Índice: 0.00MB
ea_links: Datos: 0.02MB + Índice: 0.02MB
ea_options: Datos: 2.14MB + Índice: 0.05MB
ea_postmeta: Datos: 5.52MB + Índice: 3.03MB
ea_posts: Datos: 1.52MB + Índice: 0.38MB
ea_termmeta: Datos: 0.02MB + Índice: 0.03MB
ea_terms: Datos: 0.05MB + Índice: 0.03MB
ea_term_relationships: Datos: 0.16MB + Índice: 0.09MB
ea_term_taxonomy: Datos: 0.06MB + Índice: 0.03MB
ea_usermeta: Datos: 0.06MB + Índice: 0.03MB
ea_users: Datos: 0.02MB + Índice: 0.05MB
ea_wc_download_log: Datos: 0.02MB + Índice: 0.03MB
ea_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB

### Post Type Counts ###

attachment: 1009
customize_changeset: 13
nav_menu_item: 30
options: 5
page: 30
polylang_mo: 3
post: 64
product: 111
revision: 1
shop_coupon: 7
shop_order: 1175
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ❌Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Hide errors from visitors: ❌Los mensajes de error no deberían mostrarse a los visitantes.

### Active Plugins (10) ###

Polylang: por Frédéric Demarle – 2.3
All In One SEO Pack: por Michael Torbert – 2.4.4.1
Block Bad Queries (BBQ): por Jeff Starr – 20171101
Imsanity: por Shane Bishop – 2.3.9
My Simple Mailchimp: por Oscar Ciutat – v1.0
PDF Embedder: por Dan Lester – 3.1.8
Scroll Top: por Theme Junkie – 1.0.2
Hyyan WooCommerce Polylang Integration: por Hyyan Abo Fakher – 1.0.4 – No probado con la versión activa de WooCommerce
WooCommerce Alternate Product Categories: por Oscar Ciutat – 1.0 – No probado con la versión activa de WooCommerce
WooCommerce: por Automattic – 3.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base de la tienda: ❌ Página sin definir
Carrito: #12 - /carro/
Finalizar compra: #13 - /realizar-pedido/
Mi cuenta: #14 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Storefront
Version: 2.2.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –
`</details>

**Comment by mikejolley** [comment]
This is simply a redirect without the customizer to the shop page. Body classes are not customized **BY** the customizer.


In testing, if I customize home and then click one of our sections, it does a redirect and the body class within the iframe is:

`archive post-type-archive post-type-archive-product logged-in woocommerce woocommerce-page woocommerce-demo-store full-width bg-fill lightbox nav-dropdown-has-arrow customize-partial-edit-shortcuts-shown`

So it appears fine. No bug here.

**Comment by theleemon** [comment]
Oh, I see. I don't understand why are you redirecting to the main shop page if I'm on a product taxonomy page, though. It would make sense if I were on a regular page or the blog page.

**Comment by mikejolley** [comment]
That could be changed in an update, but the redirect is simply there so you can see the image changes as you adjust options.
