### ISSUE TITLE
Having an issue with altering Totals

### ISSUE THREAD

**Issue by igorbenic** [woocommerce/woocommerce#18691]
Hi, I've been working on a solution where I had to alter the cart totals but using the action `woocommerce_calculate_totals` does not help anymore.

Before 3.2.0, that action was inside the `WC_Cart` and you could alter the totals by using the passed `$this` (WC_Cart) object.
After 3.2.0, that action is inside the `WC_Cart_Totals`:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart-totals.php#L814-L818

You can still access the passed WC_Cart object but changing the totals there would do nothing since the totals that are retrieved are stored & calculated in the WC_Cart_Totals and you can't alter the totals in that object.

The only way to do that is to alter the cart totals and then use the filter `woocommerce_calculated_total` to pass the total. So now, you could hook into the `woocommerce_calculated_total` and just use that?

Maybe I am missing something here or that is now the intended way of altering the totals?

Maybe we could also pass `$this` (WC_Cart_Totals) object as the second parameter to `woocommerce_calculate_totals`? Would not affect any hooked methods/functions prior to the change.

For now, I've solved it by altering the total using the action `woocommerce_after_calculate_totals` in WC_Cart that is triggered right after the totals in WC_Cart_Totals have been calculated.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Hook into `woocommerce_calculate_totals`
2. On the passed cart object, use `set_total` method (change it to any value)
3. On the checkout page, try changing the shipping methods (or anything to update the order) and see if anything happens with the total

## Expected/actual behavior

The expected behavior is to see the total being changed into the new altered value.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

WP Version: 4.9.2
WC Version: 3.3.0

**Comment by mikejolley** [comment]
WC_Cart_Totals does the calculations, but the values are still stored in the cart. `woocommerce_calculate_totals` passes you the cart. _If you need `$this` submit a PR with code example to show why it's needed and we'll consider it._ 

> Maybe I am missing something here or that is now the intended way of altering the totals?

The intended way is please don't :) TBH, if you can avoid messing with the totals even better because these types of changes don't play well with other extensions. Changing things manually often causes conflicts or messes with the rounding. Adjusting items/shipping BEFORE it gets passed to the new totals class would be the preferred method. 

`woocommerce_calculate_totals` exists simply to offer a bw compatible hook.

Thanks

**Comment by igorbenic** [comment]
Thank you @mikejolley for the explanation :)

Will see to improve the code and try to hook it before the calculations ;)
