### ISSUE TITLE
Processing Order Count is wrong

### ISSUE THREAD

**Issue by cordvision** [woocommerce/woocommerce#18694]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Everything was working fine, but just changed from one day to the other without making any changes (no update etc.)
Order count for "processing" is wrong. It always displays 1 more order in the count as processing than there are actually orders that have the status "processing". For example, I would have 4 actual orders set to "processing", however, it would display the number 5 behind "Orders" in the main woocommerce menu as well as behind the link to the page that filters all the orders that are supposed to be set to "processing". When I click the link to filter for all the processing orders, it leads to a 404 error page or just a blank page (Link: http://www.cordvision.com/wp-admin/edit.php?post_status=wc-processing&post_type=shop_order). 
I manually searched through the SQL database. In wp_post every thing looks fine. Only 4 orders have a "post-status" of "wc-processing".

I also batch changed the last 60 orders to "on hold" and then back to the actual status they are supposed to have. I was hopping it would overwrite a corrupted value in case there is one but it didn't help.

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
This one sounds like a conflict with an extension. Those values can be filtered. You should go through the "Isolating the problem" steps listed on https://github.com/woocommerce/woocommerce/issues/new and submit a support ticket if you get stuck via the helpdesk. This isn't one we can reproduce.

Thanks
