### ISSUE TITLE
Order list get broken, can't see,edit orders after update 3.3.0

### ISSUE THREAD

**Issue by Scopicme** [woocommerce/woocommerce#18696]
Order list is not working properly. 
Issues - 
Can't edit or display order no. 
Can't pdf invoices
Can't see order details 

Everything is blank there. Only seeing address of customer and vendor name.

**Comment by mikejolley** [comment]
Using smart coupons?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18698
