### ISSUE TITLE
The order changed webhook is sending error in body wc 3.3.0

### ISSUE THREAD

**Issue by mvrhov** [woocommerce/woocommerce#18695]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a order updated webhook (set to legacy v3)
2. change something in order 
3. go look at the logs to see the content sent to the hook

## Expected/actual behavior

When I follow those steps, I see... the body content contains 
` {\"errors\":{\"woocommerce_api_user_cannot_read_order\":[\"You do not have permission to read this order\"]},\"error_data\":{\"woocommerce_api_user_cannot_read_order\":{\"status\":401}}}`

I was expecting to see...
the actual order content as in previous versions.

**Comment by mvrhov** [comment]
Something fishy is going on.

The webhook had a creation date from this morning. You must have been changing something As this webhook was created a long time ago.

I toggled the api version there from legacy v3 to WC v2 saved.. and toggled back to legacy and now this seems to be working again.

**Comment by claudiosanches** [comment]
@mvrhov thanks for reporting it. We changed from posts to a custom table, but we let behind the `user_id`, sorry about that. You can go into each webhook and click in save, this will make each old webhook use your `user_id` and start working again.
