### ISSUE TITLE
Show products in category issue on Version 3.3.0

### ISSUE THREAD

**Issue by mbougarne** [woocommerce/woocommerce#18707]
I updated my store to the new version of the plugin  3.3.0, and it seems that there is an error on the show products in category part, instead of showing just the products it's shows the categories of the products too:

![category](https://user-images.githubusercontent.com/16257137/35626847-e44dcebc-068e-11e8-95c4-65120022d708.png)

I try it with the pre-built woocommerce shortcode and with my own theme both are not working.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/18674
