### ISSUE TITLE
Rounding per line item gives a different result then rounding for multiples of the same line item

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#18710]
Steps to reproduce:

- Create two simple products with a price of 10.70
- Set taxes to "No, I will enter prices exclusive of tax"
- Uncheck tax rounding checkbox to enable rounding per line item
- Show prices in cart including taxes
- Set a tax rate of 21%

For one scenario we add both products to the cart with a quantity of one:

![image](https://user-images.githubusercontent.com/11388669/35630059-379c639a-0698-11e8-9d05-9326fb416214.png)

For the second scenario we add one product to the cart with a quantity of two:

![image](https://user-images.githubusercontent.com/11388669/35630022-1cc79206-0698-11e8-8553-2b11af4cff22.png)

The first scenario is rounded correctly. But the last one is only rounded after the two are added together. Ideally for this scenario there would be a way for the rounding to be applied per line item and per quantity of each line item. Is this something which could be considered?

Other workarounds I found would be to:

1\. Change the option to "Yes, I will enter prices inclusive of tax" and then adjust the product price to 12.95
2\. Adjust the product price to 10.7024 for it to calculate a total which is closer to the final amount so it doesn't trigger the rounding error.

Tested with both WooCommerce 3.2.6 and 3.3

**Comment by DarrellJMartin** [comment]
The same issue also occurs if you specify for example a 20% discount coupon and apply it to the cart. This is even after adjusting the prices on the products to 4 decimal places so it doesn't trigger the rounding error for the no-coupon result.

Without 20% coupon applied:

![no-coupon](https://user-images.githubusercontent.com/8157728/35736195-0cf3515c-081f-11e8-8fe8-c7719c9dc82f.jpg)

With 20% coupon applied:

![20percent-coupon](https://user-images.githubusercontent.com/8157728/35736203-13f57854-081f-11e8-858c-306c8f418db7.jpg)

**Comment by mikejolley** [comment]
I checked the logic and it's actually calculating correctly given we round per line. The taxes are correct (this is where the discrepancy comes from).

How we do calculations is explained in https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce

We either do per-line rounding, or subtotal rounding. We do not support per-item rounding.

You cannot mix per line and per item rounding. I couldn't find the page but HMRC for example allow per line or per item rounding. Both are valid as long as you're consistent. This 1p discrepancy doesn't affect the merchant negatively.

> Ideally for this scenario there would be a way for the rounding to be applied per line item and per quantity of each line item. Is this something which could be considered?

Per item rounding would be an entirely new feature/option we'd need to support, add tests for, 3rd parties would need to account for etc. That a large undertaking with seemingly little demand. I'd vote against it given the hassles it would cause us.

cc @claudiulodro For future reference in case it comes up in the future or whilst I'm away. @mikkamp Can update the wiki post if you feel it's needed.
