### ISSUE TITLE
Product CSV Suite No Longer Accepts menu_order

### ISSUE THREAD

**Issue by co50** [woocommerce/woocommerce#18712]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Import products with the menu_order column using the Products CSV Import Suite plugin.
2. Now try the same except change the "menu_order" column header to "position"
3. Ah, that works.

## Expected/actual behavior

When I follow those steps, I see...

"menu_order" column is ignored when using the premium import plugin. Changing it to "position", which is how the free built-in importer works, also causes the premium version to see it.

I was expecting to see...

Either proper documentation for the premium plugin that correctly relabels the "menu_order" column as "position" or the premium plugin accepting menu_order for the column heading. 

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
This is not the support area for CSV import suite. Please use the helpdesk.

**Comment by co50** [comment]
Reported a bug. I don't need support. Fix it or don't. I don't care either way.

**Comment by mikejolley** [comment]
I know, but there are right and wrong places to report things. 

cc @bor0 @roykho for reference.

**Comment by co50** [comment]
I looked for a git for the plugin as there are for others but couldn't find it. Found some related posts in this git so figured I'd post here. Most of the time support assumes it's 'you' and not a bug and I just didn't have the time to go back and forth with them to prove it's a bug. Sorry for the inconvenience.

**Comment by bor0** [comment]
@co50 WC extensions are on a private repository. Helpdesk is the best way to get it to these repos, once confirmed it really is a bug with a Happiness Engineer.
