### ISSUE TITLE
Mismatch data type

### ISSUE THREAD

**Issue by emrahu** [woocommerce/woocommerce#18719]
API product price field returns mismatch data type
Example link: https://yourwebsite.com/wp-json/wc/v2/products/?consumer_key=ck_***&consumer_secret=cs_***&filter[category]=category

If a product doesn't have a price the value type retrieved is an integer ex: **0**
if a product does have a price the value type retrieved is a string ex: **"$4.75"**
Seems like regressed [Issue #9220](https://github.com/woocommerce/woocommerce/issues/9220)

**Comment by mikejolley** [comment]
Does not appear to be the case. Also, currencies? Thats not part of our API. Would need more details.

Empty price:

![insomnia create product 2018-01-31 19-16-27](https://user-images.githubusercontent.com/90977/35642559-5dfe1f38-06bb-11e8-8e68-6daed6d52b5c.png)

Zero price:

![insomnia create product 2018-01-31 19-17-03](https://user-images.githubusercontent.com/90977/35642565-61773582-06bb-11e8-9029-5764e37508c6.png)

Set price:

![insomnia create product 2018-01-31 19-16-44](https://user-images.githubusercontent.com/90977/35642571-6429f1ca-06bb-11e8-8b7c-2439a004db00.png)

All use strings.

**Comment by emrahu** [comment]
I see it **0**
![screen shot 2018-01-31 at 2 20 50 pm](https://user-images.githubusercontent.com/2554974/35642716-03905990-0692-11e8-8299-876a3b1fc2ae.png)

**Comment by mikejolley** [comment]
Need to see the full request and response/product type.

> What about currencies?

You said:

> if a product does have a price the value type retrieved is a string ex: "$4.75"

**Comment by emrahu** [comment]
That currency symbol is a typo. 
Below is the entire json object for that specific product.

`
{
  "id": 642,
  "name": "Tip",
  "slug": "tip",
  "permalink": "https://yourwebsite.com/menu/tip/",
  "date_created": "2015-02-26T19:45:13",
  "date_created_gmt": "2015-02-27T00:45:13",
  "date_modified": "2015-02-26T19:45:13",
  "date_modified_gmt": "2015-02-27T00:45:13",
  "type": "simple",
  "status": "publish",
  "featured": false,
  "catalog_visibility": "hidden",
  "description": "",
  "short_description": "",
  "sku": "",
  "price": 0,
  "regular_price": "",
  "sale_price": "",
  "date_on_sale_from": null,
  "date_on_sale_from_gmt": null,
  "date_on_sale_to": null,
  "date_on_sale_to_gmt": null,
  "price_html": "<span class=\"woocommerce-Price-amount amount\"><span class=\"woocommerce-Price-currencySymbol\">&#36;</span>0.00</span>",
  "on_sale": false,
  "purchasable": true,
  "total_sales": 3978,
  "virtual": false,
  "downloadable": false,
  "downloads": [],
  "download_limit": -1,
  "download_expiry": -1,
  "external_url": "",
  "button_text": "",
  "tax_status": "none",
  "tax_class": "zero-rate",
  "manage_stock": false,
  "stock_quantity": null,
  "in_stock": true,
  "backorders": "no",
  "backorders_allowed": false,
  "backordered": false,
  "sold_individually": true,
  "weight": "",
  "dimensions": {
  "length": "",
  "width": "",
  "height": ""
  },
  "shipping_required": true,
  "shipping_taxable": false,
  "shipping_class": "",
  "shipping_class_id": 0,
  "reviews_allowed": false,
  "average_rating": "0.00",
  "rating_count": 0,
  "related_ids": [],
  "upsell_ids": [],
  "cross_sell_ids": [],
  "parent_id": 0,
  "purchase_note": "",
  "categories": [],
  "tags": [],
  "images": [
 {
  "id": 0,
  "date_created": "2018-01-31T09:20:09",
  "date_created_gmt": "2018-01-31T19:20:09",
  "date_modified": "2018-01-31T09:20:09",
  "date_modified_gmt": "2018-01-31T19:20:09",
  "src": "https://yourwebsite.com/wp-content/plugins/woocommerce/assets/images/placeholder.png",
  "name": "Placeholder",
  "alt": "Placeholder",
  "position": 0
  }
  ],
  "attributes": [],
  "default_attributes": [],
  "variations": [],
  "grouped_products": [],
  "menu_order": 0,
  "meta_data": [
  {},
  {},
  {},
  {},
  {},
  {},
  {}
  ],
  "_links": {
  "self": [
  {
  "href": "https://yourwebsite.com/wp-json/wc/v2/products/642"
  }
  ],
  "collection": [
  {
  "href": "https://yourwebsite.com/wp-json/wc/v2/products"
   }
  ]
  }
  } `

**Comment by mikejolley** [comment]
Extensions maybe?

https://github.com/woocommerce/woocommerce/blob/e15f2672705cc2e8ec81f6b592d476d872568fe4/includes/abstracts/abstract-wc-product.php#L274-L276 string.

Setter: https://github.com/woocommerce/woocommerce/blob/e15f2672705cc2e8ec81f6b592d476d872568fe4/includes/abstracts/abstract-wc-product.php#L816-L818

`wc_format_decimal` returns strings.

**Comment by claudiosanches** [comment]
I made a few tests:

Creating an empty simple product:

```
    "price": "",
    "regular_price": "",
    "sale_price": "",
```

And updating the regular price to zero, so will be a free product:

```
    "price": "0",
    "regular_price": "0",
    "sale_price": "",
```

So I can't see how you got in that example: https://github.com/woocommerce/woocommerce/issues/18719#issuecomment-362044054

So this sounds like some extension changing the response.

**Comment by emrahu** [comment]
I found the problem. This particular product has filters attached to it. It's setting an integer 0 if there's no price is set. I updated the filter, now it sets a string 0. In my functions.php

` if($product->id == PRODUCT_ID){
        return isset($woocommerce->session->agr_donation) ? floatval($woocommerce->session->agr_donation) : "0";
 }`

Thanks for the help. It took me a while to figure this out.

**Comment by claudiosanches** [comment]
@emrahu this took while because not following the issue template, there is essential information to helps everyone debug things like that.
