### ISSUE TITLE
Auto update?

### ISSUE THREAD

**Issue by keeslamper** [woocommerce/woocommerce#18711]
I've a few shops which are auto updatet to 3.3. Is there any option to disable auto-update? 

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
WooCommerce and other plugins to not auto update. Likely your hosting.

**Comment by keeslamper** [comment]
No Mike, I'm sorry but most of the shops I'm the hoster and there is no auto-update anywhere. And my customers don't update 100% sure. But the plugin is updated to 3.3.

**Comment by mikejolley** [comment]
@keeslamper The plugin does not auto-update itself. There is no code present to do so.

**Comment by keeslamper** [comment]
I'm sorry Mike, off course you're right. I've informed and one of my new servers had wpcli active for auto-update. Thanks for the quick response!
