### ISSUE TITLE
Same Radio and Checkbox HTML

### ISSUE THREAD

**Issue by edirpedro** [woocommerce/woocommerce#18715]
At Woocommerce 3.2 I found inconsistencies to theming radio and checkbox elements because the HTML are different, requiring different CSS approaches. I think this could be standardized to use the same HTML used for Checkbox.

Radio
```html
<input id="payment_method_cheque" type="radio" class="input-radio" name="payment_method" value="cheque" data-order_button_text="">
<label for="payment_method_cheque">Title</label>
```

Checkbox
```html
<label class="woocommerce-form__label woocommerce-form__label-for-checkbox checkbox">
<input type="checkbox" class="woocommerce-form__input woocommerce-form__input-checkbox input-checkbox" name="terms" id="terms"> <span>Title</span> <span class="required">*</span>
</label>
```

**Comment by mikejolley** [comment]
This would unfortunately be a big breaking change for themes (even storefront) which style based on current markup. Just moving the radio for example caused it to be hidden and no radio button was therefore visible.

Recommend leaving this for https://github.com/woocommerce/woocommerce/issues/10672 where themes will need to restyling things anyway.
