### ISSUE TITLE
Import cross-sells doesnt work with the woocommerse importer

### ISSUE THREAD

**Issue by kvanbiesen** [woocommerce/woocommerce#18721]
1. Have a csv with crosssell_id and sku column
2. Import using the included importer, matching sku to sku and crosselid to crossel
3. Import.

All crosssells of the updated products get a “placeholder” for the id i tried to insert instead of actual using the id. Making it useless. Tried the same with importng the crosssells skus. Same result. Placeholder that doesnt do anything 

## Expected/actual behavior

When I follow those steps, I see “placeholder for id 9977” in stead of actually listing id 9977. Placeholder gets a new id in the database

I was expecting to see...the id actually inserted.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

All of above!

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
crosssell_id column does not exist. See the schema here https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema `cross_sell_ids` exists.

You also cannot set IDs manually. If ids do not exist prior to import, you cannot use them in the CSV. Use SKUs instead. 

e.g. `cross_sell_ids` column, with values SKU-1, SKU-2

If the SKU does not exist yet, a placeholder may be created.

If after checking all of the above things don't work, report back and provide the CSV so I can test it myself.

If you do post back, please provide the system status report so we can see what is running.

Thanks!

**Comment by kvanbiesen** [comment]
Yup, confirmed working now. 
IT doesnt seem to handle SKU with spaces in the name. Other than that, it seems to work fine with the actual id with ld: in front. SKU with no spaces get linked fine. spaces in and it gets wonkers. But id is perfect for me also.

Thanks for the response.
