### ISSUE TITLE
[3.3] woocommerce_resize_images filter runs too early

### ISSUE THREAD

**Issue by wpexplorer** [woocommerce/woocommerce#18722]
Because the woocommerce_resize_images filter runs to early it's not possible to disable via a child theme. Any chance that can be moved inside the maybe_resize_image class function instead at the top so that it can be used? Thanks!

Or maybe at least add a filter to the whitelist:

```
// Use a whitelist of sizes we want to resize. Ignore others.
if ( ! in_array( $size, array( 'woocommerce_thumbnail', 'woocommerce_single', 'shop_thumbnail', 'shop_catalog', 'shop_single' ), true ) ) {
	return $image;
}
```

This way we can filter out the image sizes that should be dynamically resized and so if we don't want to resize any we can set it to an empty array.

Thanks!

**Comment by claudiulodro** [comment]
See #18724
