### ISSUE TITLE
[3.3] Category descriptions missing on themes w/o WC support.

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18733]
Themes that do not declare WooCommerce support don't have category descriptions on category archive page. This is contrary to how it would have worked pre-3.3.

Possible to hook in and add them on these themes? You can test and replicate with Hamilton.

Issues:

https://wordpress.org/support/topic/archive-text-not-appearing-on-woo-category-pages/
https://wordpress.org/support/topic/categories-description/

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18744
