### ISSUE TITLE
Hi! My woocommerce cart total is not adding up correct.

### ISSUE THREAD

**Issue by Codychaps** [woocommerce/woocommerce#18732]
![image](https://user-images.githubusercontent.com/36024161/35661293-00f67be0-06c6-11e8-97f1-526c95544b83.png)

I'm not sure where the discrepancy is coming from. Please help

**Comment by Codychaps** [comment]
so i found that the tax is being charged 3 times. any recommendations?

**Comment by Codychaps** [comment]
for more context, if i uncheck "enable taxes" the tax rate is correct, but not displayed.
![image](https://user-images.githubusercontent.com/36024161/35664300-4df3a552-06d6-11e8-8503-29033f514b64.png)

**Comment by WPprodigy** [comment]
Please fill out the entire template when submitted issues. We're missing a lot of information on this, such as your system status report, and whether or not this happens when only using the WooCommerce plugin with a default theme.

**Comment by mikejolley** [comment]
^

Usually plugin conflict. Core unit tests are passing for this.

**Comment by Codychaps** [comment]
`
### WordPress Environment ###

Home URL: https://www.baegivesback.com
Site URL: https://www.baegivesback.com
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.25
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.24.0
OpenSSL/1.0.0

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: b90_
Total Database Size: 18.69MB
Database Data Size: 15.42MB
Database Index Size: 3.27MB
b90_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB
b90_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
b90_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
b90_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
b90_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
b90_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
b90_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
b90_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
b90_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
b90_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
b90_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
b90_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
b90_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
b90_woocommerce_log: Data: 0.00MB + Index: 0.00MB
b90_adsw_activities: Data: 0.02MB + Index: 0.00MB
b90_adsw_ali_meta: Data: 0.33MB + Index: 0.03MB
b90_ads_abandoned_emails: Data: 0.00MB + Index: 0.00MB
b90_ads_abandoned_flow: Data: 0.00MB + Index: 0.00MB
b90_ads_activities: Data: 0.00MB + Index: 0.00MB
b90_ads_ali_meta: Data: 0.10MB + Index: 0.00MB
b90_ads_attributes: Data: 0.01MB + Index: 0.01MB
b90_ads_categories: Data: 0.00MB + Index: 0.00MB
b90_ads_email_templates: Data: 0.00MB + Index: 0.00MB
b90_ads_orders_item: Data: 0.00MB + Index: 0.00MB
b90_ads_products: Data: 0.01MB + Index: 0.00MB
b90_ads_products_meta: Data: 0.12MB + Index: 0.00MB
b90_commentmeta: Data: 0.16MB + Index: 0.05MB
b90_comments: Data: 0.06MB + Index: 0.03MB
b90_failed_jobs: Data: 0.00MB + Index: 0.00MB
b90_gpi_api_error_logs: Data: 0.00MB + Index: 0.00MB
b90_gpi_custom_urls: Data: 0.00MB + Index: 0.00MB
b90_gpi_page_blacklist: Data: 0.00MB + Index: 0.00MB
b90_gpi_page_reports: Data: 0.00MB + Index: 0.00MB
b90_gpi_page_stats: Data: 0.00MB + Index: 0.00MB
b90_gpi_summary_snapshots: Data: 0.00MB + Index: 0.00MB
b90_links: Data: 0.00MB + Index: 0.00MB
b90_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
b90_mondula_form_wizards: Data: 0.00MB + Index: 0.00MB
b90_nm_personalized: Data: 0.00MB + Index: 0.00MB
b90_options: Data: 3.21MB + Index: 0.25MB
b90_payment_discount: Data: 0.00MB + Index: 0.00MB
b90_payment_transaction: Data: 0.00MB + Index: 0.00MB
b90_postmeta: Data: 8.85MB + Index: 2.21MB
b90_posts: Data: 2.20MB + Index: 0.30MB
b90_queue: Data: 0.00MB + Index: 0.00MB
b90_sgrb_category: Data: 0.02MB + Index: 0.03MB
b90_sgrb_comment: Data: 0.02MB + Index: 0.03MB
b90_sgrb_comment_rating: Data: 0.02MB + Index: 0.06MB
b90_sgrb_page_review: Data: 0.02MB + Index: 0.03MB
b90_sgrb_rate_log: Data: 0.02MB + Index: 0.06MB
b90_sgrb_review: Data: 0.02MB + Index: 0.00MB
b90_sgrb_template: Data: 0.02MB + Index: 0.00MB
b90_smush_dir_images: Data: 0.00MB + Index: 0.00MB
b90_sr_fb_log: Data: 0.02MB + Index: 0.00MB
b90_sr_fb_pages: Data: 0.02MB + Index: 0.00MB
b90_sr_gallery: Data: 0.02MB + Index: 0.03MB
b90_sr_spinner: Data: 0.02MB + Index: 0.00MB
b90_sst_tics: Data: 0.03MB + Index: 0.01MB
b90_termmeta: Data: 0.01MB + Index: 0.02MB
b90_terms: Data: 0.00MB + Index: 0.02MB
b90_term_relationships: Data: 0.01MB + Index: 0.03MB
b90_term_taxonomy: Data: 0.01MB + Index: 0.01MB
b90_tinvwl_items: Data: 0.00MB + Index: 0.00MB
b90_tinvwl_lists: Data: 0.00MB + Index: 0.00MB
b90_usermeta: Data: 0.02MB + Index: 0.01MB
b90_users: Data: 0.00MB + Index: 0.01MB
b90_wc_download_log: Data: 0.00MB + Index: 0.00MB
b90_wc_webhooks: Data: 0.00MB + Index: 0.00MB
b90_woof_query_cache: Data: 0.00MB + Index: 0.00MB
b90_yoast_seo_links: Data: 0.01MB + Index: 0.00MB
b90_yoast_seo_meta: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 1440
customize_changeset: 7
ig_campaign: 1
ig_message: 2
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mc4wp-form: 2
nav_menu_item: 41
page: 20
post: 8
product: 65
product_variation: 810
revision: 92
shop_coupon: 2
sp_imageslider: 1
ufaq: 2
wpforms: 1
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

AJAX Search for WooCommerce: by Damian Góra – 1.1.6 – Not tested with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.0.2
AliDropship Woo Plugin: by Vitaly Kukin & Yaroslav Nevskiy & Pavel Shishkin – 0.7.2
Beeketing For WooCommerce: by Beeketing – 3.3.0 – Not tested with the active version of WooCommerce
Better Font Awesome: by Mickey Kay – 1.7.1
Checkout Address Autocomplete for WooCommerce: by eCreations – 1.9.4 – Not tested with the active version of WooCommerce
Facebook for WooCommerce: by Facebook – 1.7.10 – Not tested with the active version of WooCommerce
Fonts: by Brad Dalton - WP Sites – 2.3
Google Pagespeed Insights: by Matt Keys – 3.0.3
Head, Footer and Post Injections: by Stefano Lissa – 3.1.0
Icegram - Popups, Optins, CTAs & lot more...: by icegram – 1.10.16
Jetpack by WordPress.com: by Automattic – 5.7.1
Collapse-O-Matic: by twinpictures
baden03 – 1.7.8

MailChimp for WooCommerce: by MailChimp – 2.1.3 – Not tested with the active version of WooCommerce
MailChimp for WordPress: by ibericode – 4.1.14
MOJO Marketplace: by Mike Hansen – 1.3.3
Quick View WooCommerce: by XootiX – 1.7 – Not tested with the active version of WooCommerce
Shortcode in Menus: by Gagan Deep Singh – 3.4
Shortcodes Ultimate: by Vladimir Anokhin – 5.0.2
Simple Sales Tax: by Simple Sales Tax – 5.8
SocialRabbit: by Vitaly Kukin & Yaroslav Nevskiy & Ilya Dolgikh – 1.6.12
Sticky Posts - Switch: by Markus Froehlich – 1.6
WooCommerce Wishlist Plugin: by TemplateInvaders – 1.5.14 – Not tested with the active version of WooCommerce
Social Media and Share Icons (Ultimate Social Media): by UltimatelySocial – 1.8.3
WooCommerce Boost Sales: by Andy Ha (villatheme.com) – 1.2.2 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.0.4
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce AdWords Dynamic Remarketing: by Wolf+Bär Agency – 1.4.5 – Not tested with the active version of WooCommerce
Booster for WooCommerce: by Algoritmika Ltd – 3.3.0 – Not tested with the active version of WooCommerce
N-Media WooCommerce PPOM: by Najeeb Ahmad – 4.2 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.11.0
WooCommerce: by Automattic – 3.3.0
Yoast SEO: by Team Yoast – 6.2
WP Image Zoom: by SilkyPress – 1.22 – Not tested with the active version of WooCommerce
WP Instagram Widget: by Scott Evans – 2.0.2
WP Smush: by WPMU DEV – 2.7.6
WPForms Lite: by WPForms – 1.4.3
WPFront Scroll Top: by Syam Mohan – 1.6.1
Z-URL Preview: by Stuart Millington – 2.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
wbs_bundle (wbs_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #18 - /shop/
Cart: #19 - /cart/
Checkout: #20 - /checkout/
My account: #21 - /my-account/
Terms and conditions: #1228 - /terms-of-service/

### Theme ###

Name: TheShop
Version: 1.10
Author URL: http://athemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### TI WooCommerce Wishlist Templates ###

Overrides: –
`

**Comment by Codychaps** [comment]
I appreciate any input. I apologize as most of this is new to me

**Comment by WPprodigy** [comment]
Follow this guide: https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4

You have either a theme or plugin conflict causing this. Need to find what exactly.
