### ISSUE TITLE
problem permalink

### ISSUE THREAD

**Issue by demen20** [woocommerce/woocommerce#18745]
Hi, after the last update, now the permalink works only in shop base. If I choose the others I see error 404. Page non-existent in product inside course example: Home ---» Product «---- Shoes . What's the problem? P.S: I am one of the many who also finds this problem "https://wordpress.org/support/topic/wc-3-3-issues-with-categories-displaying-in-shop/"

maybe also for this, I can not select basic shop with categories?

**Comment by mikejolley** [comment]
You need to provide more details - re-read https://github.com/woocommerce/woocommerce/issues/new before submitting an issue.

The category issue is being worked on.

Thanks
