### ISSUE TITLE
permalink and category

### ISSUE THREAD

**Issue by demen20** [woocommerce/woocommerce#18749]
Hi, after the last update, now the permalink works only in shop base. If I choose the others I see error 404. Page non-existent in product inside course example: Home ---» Product «---- Shoes . What's the problem? 
maybe also for this, I can not select basic shop with categories? My theme is Anima of   Cryout Creations
`
The problem is explained in the attached image
<a href="http://www.imagebam.com/image/6b3aa7735919623" target="_blank"><img src="http://thumbs2.imagebam.com/64/14/81/6b3aa7735919623.jpg" alt="imagebam.com"></a>

**Comment by mikejolley** [comment]
Tried a few themes and variations of this; no 404s. Without a status report I cannot suggest what the problem is so again **do not submit issues without carrying out the steps listed on https://github.com/woocommerce/woocommerce/issues/new.** Without this we cannot reproduce issues effectively.
