### ISSUE TITLE
API filter by order_number

### ISSUE THREAD

**Issue by marotn** [woocommerce/woocommerce#18751]
Hi,
I want check of the commande exist befor with API.
I cant filter by ID or order_numer ?! how can i add thie filed in filter param?
Available parameters  : https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#list-all-orders

**Comment by mikejolley** [comment]
This filter does not exist. If you want to contribute it, you can do so here for v3: https://github.com/woocommerce/wc-api-dev

Thanks

**Comment by marotn** [comment]
but i must do it in my theme , i have worked with the check of the order !!

**Comment by mikejolley** [comment]
You can only query by order ID.
