### ISSUE TITLE
Default value for single_select_country and multi_select_countries settings field not passed into output

### ISSUE THREAD

**Issue by Drivingralle** [woocommerce/woocommerce#18753]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

If a single_select_country or multi_select_countries setting field is registered and defines a default country this information is not passed into the output.

Example: 
Plugin adds a settings field to allow user to select a country to work with. In most cases it makes sense to use the shop default country. So the plugin passes this option value into the call for the settings field as the default/fallback value.
This a good behavior for a smart default we should encourage.
But as the settings page is rendered the default value is not used so the country select show the first item in it's list (Åland in my test case today). 

Same is true for the multi_select_countries. 

I think the default value should also be passed on in the single_select_page settings field output. I can make a other issue and PR for that.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
WooCommerce 3.3
WordPress 4.9.x
</details>

**Comment by mikejolley** [comment]
Thanks for the patch 👍  We'll review https://github.com/woocommerce/woocommerce/pull/18754
