### ISSUE TITLE
Shipping rate cache

### ISSUE THREAD

**Issue by B-Anders** [woocommerce/woocommerce#18769]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set up Shipping Zone with free shipping and Bolder Table Rate, enable Multiple Packages plugin
2. Put stuff in Cart - The shipping is correctly calculated
3. Modify the quantity in cart to test Free Shipping threshold, hit Update Cart
4. Ask for support from the Plugin developer and find out that it is a WooCommerce caching issue

## Expected/actual behavior

When I follow those steps, I see...

The Shipping is not calculating correctly
   - returning to previous quantities does not help

Shipping rates are again calculated correct IF:
   - one saves the Shipping options in Admin>WC>Shipping
   - changing destination country in Shipping calculator
   - enabling Debug Mode

I was expecting to see...
Correct Shipping rates without Debug Mode or having to purge cache

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

NOTE: all my testing concludes that the Update Cart action does not clear the Shipping Rates and is not allowing for a correct Shipping Calculation. Can this be fixed or avoided somehow?
Thank you

## WordPress Environment

<details>
```
Latest versions
No Caching Plugins
Tested in private mode on FF, IE, Chrome
```
</details>

**Comment by WPprodigy** [comment]
Changing the quantity of products in the cart changes the package and invalidated the cache.

This issue doesn't happen with [Table Rate Shipping](https://www.woocommerce.com/products/table-rate-shipping/) or [Advanced Shipping Packages](https://woocommerce.com/products/woocommerce-advanced-shipping-packages/), so it has to do with the plugins you are using.

**Comment by mikejolley** [comment]
As @WPprodigy said, cache is cleared when the package changes. See line:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart.php#L1327

You mentioned a "Multiple Packages plugin" - I'm not sure what that is, but if it's not changing the packages in the cart and the hash is therefore staying the same, cache will not clear. 

Clearing the cache at any other point aside from changing the package would make the idea of a cache pointless. Therefore this is not something we'll be changing in core. If you have other times when the cache needs clearing, the plugins can filter the package and change one of the properties.

Thanks
