### ISSUE TITLE
Arguments passed to wc_get_template_html on emails should have  filter

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#18760]
This is an enhancement request.

On the email classes, the arguments passed on to `wc_get_template_html` should have a filter.

Example of how this can be useful:
For canceled orders, I also want to send the email to the customer, so I use the `woocommerce_email_recipient_cancelled_order` filter to add the customer email alongside the shop admin email.
The problem is that `WC_Email_Cancelled_Order` sets `sent_to_admin` as true, which means the email will have links to the order edit screen on wp-admin which, of course, are not suitable for the customer.

Well, as a matter of fact, maybe we should rethink if sending the canceled order to the customers shouldn't be a WooCommerce feature altogether. Maybe it should.

Anyway, that filter would be useful for many other customizations that developers might want to implement.

Suggestion:
```
/**
 * Get content html.
 *
 * @access public
 * @return string
 */
public function get_content_html() {
	return wc_get_template_html( $this->template_html, apply_filters( 'woocommerce_get_email_args', array(
		'order'         => $this->object,
		'email_heading' => $this->get_heading(),
		'sent_to_admin' => true,
		'plain_text'    => false,
		'email'			=> $this,
	) ) );
}

/**
 * Get content plain.
 *
 * @return string
 */
public function get_content_plain() {
	return wc_get_template_html( $this->template_plain, apply_filters( 'woocommerce_get_email_args', array(
		'order'         => $this->object,
		'email_heading' => $this->get_heading(),
		'sent_to_admin' => true,
		'plain_text'    => true,
		'email'			=> $this,
	) ) );
}
```

**Comment by mikejolley** [comment]
The correct way to do this would be to extend the email class and hook in your custom customer focussed one.

We could add a filter (pr?) but medium term we'll be redesigning these from scratch I believe - https://github.com/woocommerce/woocommerce/issues/10704 :)

Thanks
