### ISSUE TITLE
Add class to grouped product <form> element

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#18763]
Instead of:

```
<form class="cart" action="<?php echo esc_url( get_permalink() ); ?>" method="post" enctype='multipart/form-data'>
```

could we add an additional class that will differentiate this form as a grouped product?  `cart_group` is what @franticpsyx and I are using in Bundles, Composites, and Mix and Match to tell our JS scripts to work better with Name Your Price.

```
<form class="cart cart_group" action="<?php echo esc_url( get_permalink() ); ?>" method="post" enctype='multipart/form-data'>
```
There's a precedent for variable products having a custom class there in core too..

```
<form class="variations_form cart" action="<?php echo esc_url( get_permalink() ); ?>" method="post" enctype='multipart/form-data' data-product_id="<?php echo absint( $product->get_id() ); ?>" data-product_variations="<?php echo htmlspecialchars( wp_json_encode( $available_variations ) ) ?>">
```

So `grouped_form` would also be fine. I am trying to add support for Name Your Price to grouped products and there's this minor sticking point. I can send a PR with the class of your choice.

**Comment by claudiulodro** [comment]
Feel free to send a PR. Thanks! `grouped_form` sounds like a good class name.

**Comment by WPprodigy** [comment]
See https://github.com/woocommerce/woocommerce/pull/18786
