### ISSUE TITLE
How can i do "add to cart" with woocommerce function in my api ??

### ISSUE THREAD

**Issue by redsparkers** [woocommerce/woocommerce#18775]
When i added the product from "WC()->cart->add_to_cart( $product_id );" but there is no user_id i am getting in the "wp_woocommerce_sessions" table
Check Refer- apiaddtocart.png
where first row when i add the item from website
and second row when i add the item from api
![apiaddtocart](https://user-images.githubusercontent.com/35765884/35729573-2b057a74-0835-11e8-80e8-ef4e2fdb7a1c.png)

**Comment by kloon** [comment]
The API does not have any cart functionality, the onus would be on your external application that makes the API calls to manage sessions and keep track of cart object before creating orders.
