### ISSUE TITLE
Nux Asks me to create my first product even though I have already created a product

### ISSUE THREAD

**Issue by belcherj** [woocommerce/woocommerce#18785]
1. Create new site
2. Create a product
3. Go through NUX
4. Observe that it asks you to create your first product

I was expecting to see "Create another product"

**Comment by WPprodigy** [comment]
To avoid unneeded complexity, how about just rephrasing:

![](http://cld.wthms.co/MJTCel+)

Can add it to https://github.com/woocommerce/woocommerce/pull/18389

**Comment by nishitlangaliya** [comment]
Fixes - pull request done https://github.com/woocommerce/woocommerce/pull/18823
