### ISSUE TITLE
WooCommerce Subscription API Change Cause Feature Broken in Facebook-for-WooCommerce

### ISSUE THREAD

**Issue by mengyingdu** [woocommerce/woocommerce#18799]
Hi WooCommerce Team,

I'm one of the owners of Facebook-for-WooCommerce.
Due to WooCommerce Subscription Plugin changed its API behavior (product type), our support for this product type has been broken. [#245](https://github.com/facebookincubator/facebook-for-woocommerce/issues/245)

I found this related issue  here from this Github issues [#148](https://github.com/woocommerce/woocommerce/issues/14810)

On WooCommerce Subscription Plugin, there is no issues tool or contributor. Then I tried to contact support, however, they don't support unpaid users (no option to contact, see screen shot).
Is there any other channel we can reach out to them, so next time when they update their api we can get aware of the change? 

Thanks!

**Comment by WPprodigy** [comment]
CC @thenbrent

**Comment by mikejolley** [comment]
^

Prospress contact page https://prospress.com/#contact
