### ISSUE TITLE
WooCommerce buttons look different only on ios devices (iphones and ipads). How can this be fixed?

### ISSUE THREAD

**Issue by ArtyomBaykov** [woocommerce/woocommerce#18809]
![27744528_1768547723180244_884672297_o](https://user-images.githubusercontent.com/33861066/35798300-d293f7aa-0a7b-11e8-9794-079c8551e790.jpg)
![27786965_1768547593180257_617436727_o](https://user-images.githubusercontent.com/33861066/35798301-d2b617fe-0a7b-11e8-99d6-40db8efc9ec6.jpg)

The fact is that on Tablets on mobile phones it looks normal. While only on ios it looks like this with border-radius, long and with the strange look. Is there any way to solve this issue or make the buttons look like on the normal other devices?

**Comment by mikejolley** [comment]
Yes there is likely CSS that can be used here, but this is your theme's styling. not core.

**Comment by ArtyomBaykov** [comment]
Styles still are default WooCommerce styles. We haven't added any custom css for these buttons. Also how can it be so much different on just ios devices? If there was a problem with screen sizes then on android devices should be the same trouble. While on android looks perfect. What kind of code can fix this issue specified on Ios device?

**Comment by mikejolley** [comment]
Have you tested another theme? Those buttons do not look like WC default at all. Even the colors. So something is adding styling.
