### ISSUE TITLE
Display option in product setting of woocommerce is not visible.

### ISSUE THREAD

**Issue by sharmamayank396** [woocommerce/woocommerce#18803]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.woocommerce settings
2.products
3.

## Expected/actual behaviour

When I visited product tab of woocommerce settings, the display option is missing.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
![xxx](https://user-images.githubusercontent.com/36131918/35778894-bfbcd872-09ea-11e8-8aef-f069541a4196.jpg)

**Comment by sharmamayank396** [comment]
as I opened the settings of woocommerce, and clicked the product tag. Display option was missing from there which was used to present there.

**Comment by GlennMartin1** [comment]
Since WC 3.3.0, those Display settings have been moved to the Customizer.

Go to the Customizer > WooCommerce.

**Comment by GlennMartin1** [comment]
Also related to WC 3.3.0+ display options, check out this post:

https://woocommerce.wordpress.com/2017/12/11/wc-3-3-image-size-improvements/
