### ISSUE TITLE
High CPU usage on sql search query

### ISSUE THREAD

**Issue by jobs-git** [woocommerce/woocommerce#18808]
## Issue

**Summary**

Woocommerce searching is not scaling well for 1M rows. Index seems to be not in use, So search query is using top much CPU time.

 **Long info**

I tested woocommerce to see how it would scale to 100k+ products. By far, I was able to create 700k products, and woocommerce has been **excellent** in wp-admin and frontend!! All is good except for the search.

Benchmarking woocommerce search that is being accessed by **only** 5 clients/s results to huge CPU usage in a high end server. It seems to appear that, the Index table was not efficiently being utilized. There is a post in stackoverflow regarding [High cpu usage by mysql query](https://stackoverflow.com/questions/20289566/high-cpu-usage-by-mysql-query), they solved it by reordering index, I think similar solution there could be use to fix the high cpu usage of woocommerce search.

**Test Server**

WAMP 3 fcgi http2, 8 Core Intel CPU 2.7Ghz, 24Gb ram, SSD.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create 700k products using woocommerce product generator
2. Set up Apache JMeter to lunch 500 searching client for 100s
3. Wait for SQL to consume all CPU.

## Expected/actual behavior

When I follow those steps, I see that SQL with rack up the whole server and it seems to be not enough.

I was expecting to see an efficient index table that is able to achieve lower cpu usage for only 5 clients searching per second. 

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by UserName011** [comment]
WC does not index the database table (sadly).
Last time I brought it up i was told that the user chooses which DB to work with so they can not set rules over the database in advanced. 

By the way - using index requires regular run of VACCUM and update statistics - if you won't do that the index will deteriorate and lose effectiveness over time.

**Comment by mikejolley** [comment]
Post meta table indexes can be added manually. We're working on a post to show the effects of this. cc @rodrigoprimo  

Ultimately however this will be solved by moving to custom tables which is also currently in progress. We'll announce a feature plugin on the dev blog in the near future when thats opened up.

https://woocommerce.wordpress.com/

Thanks

**Comment by rodrigoprimo** [comment]
@mikejolley, please correct me if I'm wrong, but I don't think that an index on wp_postmeta or the custom tables will have an impact on the product search query. I just did a quick search on a clean WC install and below is the query that WC uses to search for products:

```
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID
FROM wp_posts
WHERE 1=1
AND ( wp_posts.ID NOT IN (
SELECT object_id
FROM wp_term_relationships
WHERE term_taxonomy_id IN (6) ) )
AND (((wp_posts.post_title LIKE '%beanie%')
OR (wp_posts.post_excerpt LIKE '%beanie%')
OR (wp_posts.post_content LIKE '%beanie%')))
AND wp_posts.post_type = 'product'
AND (wp_posts.post_status = 'publish'
OR wp_posts.post_status = 'private')
GROUP BY wp_posts.ID
ORDER BY wp_posts.post_title LIKE '%beanie%' DESC, wp_posts.post_date DESC
LIMIT 0, 12
```

This query doesn't use the wp_postmeta table at all.

@jobs-git, probably the best solution if you need high performant search queries is to use a plugin like ElasticPress (https://wordpress.org/plugins/elasticpress/) and delegate your searches to an Elasticsearch instance. I never tried this plugin, but I think it works with WooCommerce. Another option might be adding full-text indexes on the fields used in the query above to search for products, but I'm not super sure about the effectiveness and the consequences of this second approach. I would interest to know your findings if you give it a try.

> WC does not index the database table (sadly).

@UserName011, could you please elaborate and be more specific? WC uses WP default indexes and adds a few indexes on top of that.

**Comment by jobs-git** [comment]
It turned out, it was not a woocommerce issue, I switch to mariadb then change collation to ascii (expected users are only in English keys), its much faster now!

I also found out that `SQL_CALC_FOUND_ROWS` as performance bottleneck (averaging to 100,000% slowdown), I am just not sure if this would be relevant to woocommerce, but I was tracking it [here](https://wordpress.stackexchange.com/questions/293692/how-to-implement-a-new-row-count-method-in-wordpress).

**Comment by kevin25** [comment]
I got the same issue with my huge database. My CPU is always > 100%. Up to 400%
