### ISSUE TITLE
In WooCommerce >> Reports >> Taxes >> Taxes by Date, tax amount of partially refunded order is not recalculated after a refund. 

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce#18819]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

In WooCommerce >> Reports >> Taxes >> Taxes by Date, tax amount of partially refunded order is not recalculated after a refund. 

1. Set up taxes:
![screenshot](http://cld.wthms.co/pGciQz.jpg) **Image Link:** http://cld.wthms.co/pGciQz
2. Purchase at least two products with one order.
3. Issue a partial refund for one of the products:
![screenshot](http://cld.wthms.co/38iMJv.jpg) **Image Link:** http://cld.wthms.co/38iMJv
4. In WooCommerce >> Reports >> Taxes >> Taxes by Code, the right amount of tax is displayed:
![screenshot](http://cld.wthms.co/xddCUF.jpg) **Image Link:** http://cld.wthms.co/xddCUF
However, in WooCommerce >> Reports >> Taxes >> Taxes by Code, the pre-refund amount is displayed:
![screenshot](http://cld.wthms.co/G8rygN.jpg) **Image Link:** http://cld.wthms.co/G8rygN

This is important to our customer in 939154-zd-woothemes since it seems that they are using a 3dp plugin which relates on this particular number for further calculation.

## Expected/actual behavior

I was expecting to see the recalculated amount of tax which doesn't include a refunded amount,

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://snowboardabc.mystagingwebsite.com
Site URL: https://snowboardabc.mystagingwebsite.com
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.27
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.57.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: wp_
Total Database Size: 66.28MB
Database Data Size: 60.51MB
Database Index Size: 5.77MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_comments: Data: 0.08MB + Index: 0.09MB
wpstg0_followup_coupons: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wpstg0_followup_customers: Data: 0.02MB + Index: 0.06MB
wpstg0_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wpstg0_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wpstg0_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wpstg0_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wpstg0_followup_email_orders: Data: 0.02MB + Index: 0.09MB
wpstg0_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wpstg0_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wpstg0_followup_followup_history: Data: 0.02MB + Index: 0.05MB
wpstg0_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_order_items: Data: 0.02MB + Index: 0.05MB
wpstg0_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wpstg0_geodir_attachments: Data: 0.02MB + Index: 0.00MB
wpstg0_geodir_countries: Data: 0.06MB + Index: 0.00MB
wpstg0_geodir_custom_fields: Data: 0.02MB + Index: 0.00MB
wpstg0_geodir_custom_sort_fields: Data: 0.02MB + Index: 0.00MB
wpstg0_geodir_gd_place_detail: Data: 0.02MB + Index: 0.03MB
wpstg0_geodir_post_icon: Data: 0.02MB + Index: 0.00MB
wpstg0_geodir_post_review: Data: 0.02MB + Index: 0.00MB
wpstg0_links: Data: 0.02MB + Index: 0.02MB
wpstg0_options: Data: 25.52MB + Index: 0.08MB
wpstg0_postmeta: Data: 1.52MB + Index: 0.81MB
wpstg0_posts: Data: 0.34MB + Index: 0.06MB
wpstg0_rg_form: Data: 0.02MB + Index: 0.00MB
wpstg0_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wpstg0_rg_form_view: Data: 0.02MB + Index: 0.03MB
wpstg0_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wpstg0_rg_lead: Data: 0.02MB + Index: 0.03MB
wpstg0_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wpstg0_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wpstg0_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wpstg0_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB
wpstg0_term_relationships: Data: 0.02MB + Index: 0.02MB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpstg0_usermeta: Data: 0.05MB + Index: 0.03MB
wpstg0_users: Data: 0.02MB + Index: 0.05MB
wpstg0_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wpstg0_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wpstg0_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wpstg0_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wpstg0_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpstg0_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB
wpstg0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.09MB + Index: 0.09MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_geodir_attachments: Data: 0.02MB + Index: 0.00MB
wp_geodir_countries: Data: 0.06MB + Index: 0.00MB
wp_geodir_custom_fields: Data: 0.02MB + Index: 0.00MB
wp_geodir_custom_sort_fields: Data: 0.02MB + Index: 0.00MB
wp_geodir_gd_place_detail: Data: 0.02MB + Index: 0.03MB
wp_geodir_post_icon: Data: 0.02MB + Index: 0.00MB
wp_geodir_post_review: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 28.09MB + Index: 0.08MB
wp_postmeta: Data: 1.50MB + Index: 0.83MB
wp_posts: Data: 0.38MB + Index: 0.06MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 6
bookable_person: 9
bookable_resource: 14
custom_css: 1
customize_changeset: 21
et_pb_layout: 33
follow_up_email: 2
gd_place: 1
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 5
page: 20
post: 1
product: 51
product_variation: 68
revision: 44
scheduled-action: 26
shop_coupon: 5
shop_order: 68
shop_order_refund: 7
shop_subscription: 7
wc_booking: 17
wc_membership_plan: 3
wc_user_membership: 1
wc_zapier_feed: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.0.2
Jetpack by WordPress.com: by Automattic – 5.7.1
WooCommerce Stripe Gateway: by WooCommerce – 4.0.4
WooCommerce: by Automattic – 3.3.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.5 – 2.2.7 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18829
