### ISSUE TITLE
unable to change the ratio of the view of my products

### ISSUE THREAD

**Issue by Angelo791** [woocommerce/woocommerce#18828]
Hi, with last update of woocommerce I can't change the thumbnail cropping, even if I set the ratio to 3:4, images will be always cropped into a square, and also on the main shop page when i choose what to display (only products or product + category) it doesn't change, but will be always on category+products. Anyone can help me? I'm sorry for my english

**Comment by mikejolley** [comment]
3.3.1 has some fixes surrounding this https://woocommerce.wordpress.com/2018/02/01/woocommerce-3-3-1-status-update/ You may want to try that or wait for the update.

Please note, when logging a new issue, unless you provide the system status report and go through the debugging steps it's unlikely we'll be able to help. This issue report is way too vague.

Thanks
