### ISSUE TITLE
some products are hidden

### ISSUE THREAD

**Issue by kamrosoft** [woocommerce/woocommerce#18827]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Woocommerce
2. Products
3. Drafts

## Expected/actual behavior

When I follow those steps, the counter of draft products show me 32 but it dosn't show me any product.
either pending and trash products.

and we have one product in uncategorized category that can't see it.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://www.donamall.com
Site URL: https://www.donamall.com
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.3
WP Multisite: –
WP Memory Limit: 3 GB
WP Debug Mode: –
WP Cron: ✔
Language: fa_IR

### Server Environment ###

Server Info: Apache/2.4.6
PHP Version: 7.1.14
PHP Post Max Size: 150 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.29.0
NSS/3.28.4

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 100 MB
Default Timezone is UTC: ❌ منطقه زمانی پیشفرض Asia/Tehran می باشد - شما می بایست از UTC استفاده کنید
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: dmall_
MaxMind GeoIP Database: ✔
مجموع اندازه پایگاه داده: 120.06MB
اندازه داده های پایگاه داده: 90.03MB
اندازه داده های شاخص پایگاه داده: 30.03MB
dmall_woocommerce_sessions: داده: 0.50مگابایت + شاخص: 0.02مگابایت
dmall_woocommerce_api_keys: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woocommerce_attribute_taxonomies: داده: 0.00مگابایت + شاخص: 0.01مگابایت
dmall_woocommerce_downloadable_product_permissions: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woocommerce_order_items: داده: 0.04مگابایت + شاخص: 0.02مگابایت
dmall_woocommerce_order_itemmeta: داده: 0.22مگابایت + شاخص: 0.17مگابایت
dmall_woocommerce_tax_rates: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woocommerce_tax_rate_locations: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woocommerce_shipping_zones: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woocommerce_shipping_zone_locations: داده: 0.00مگابایت + شاخص: 0.01مگابایت
dmall_woocommerce_shipping_zone_methods: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woocommerce_payment_tokens: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woocommerce_payment_tokenmeta: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woocommerce_log: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_affiliates_banners_tbl: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_affiliates_clickthroughs_tbl: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_affiliates_leads_tbl: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_affiliates_payouts_tbl: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_affiliates_relations_tbl: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_affiliates_sales_tbl: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_affiliates_tbl: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_affiliates_user_link_tbl: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_aiowps_events: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_aiowps_failed_logins: داده: 0.07مگابایت + شاخص: 0.03مگابایت
dmall_aiowps_global_meta: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_aiowps_login_activity: داده: 0.02مگابایت + شاخص: 0.01مگابایت
dmall_aiowps_login_lockdown: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_aiowps_permanent_block: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_ajaxzoom2dimages: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_ajaxzoom360: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_ajaxzoom360set: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_ajaxzoomproducts: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_akeeba_common: داده: 0.00مگابایت + شاخص: 0.01مگابایت
dmall_ak_params: داده: 0.00مگابایت + شاخص: 0.01مگابایت
dmall_ak_profiles: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_ak_stats: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_ak_storage: داده: 0.00مگابایت + شاخص: 0.01مگابایت
dmall_ak_users: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_appchar_banners: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_appchar_notification_log: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_appchar_pages: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_appchar_user_devices: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_cjfm_custom_fields: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_cjfm_invitations: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_cjfm_options: داده: 0.01مگابایت + شاخص: 0.01مگابایت
dmall_cjfm_temp_users: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_commentmeta: داده: 0.01مگابایت + شاخص: 0.02مگابایت
dmall_comments: داده: 0.20مگابایت + شاخص: 0.08مگابایت
dmall_datalist: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_dokan_announcement: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_dokan_orders: داده: 0.02مگابایت + شاخص: 0.03مگابایت
dmall_dokan_refund: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_dokan_withdraw: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_emailTemplate: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_failed_jobs: داده: 0.08مگابایت + شاخص: 0.01مگابایت
dmall_gglcptch_whitelist: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_hmwp_ms_intrusions: داده: 0.78مگابایت + شاخص: 0.03مگابایت
dmall_layerslider: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_links: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_mailchimp_carts: داده: 0.03مگابایت + شاخص: 0.00مگابایت
dmall_masterslider_options: داده: 0.06مگابایت + شاخص: 0.02مگابایت
dmall_masterslider_sliders: داده: 0.02مگابایت + شاخص: 0.03مگابایت
dmall_menu_manager_plus: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_mpcommision: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_mpfeedback: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_mpsellerinfo: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_mpseller_asktoadmin: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_mpseller_meta: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_mpseller_orders: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_mp_notifications: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_mtrlwid: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_mtrlwid_online: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_options: داده: 17.67مگابایت + شاخص: 0.65مگابایت
dmall_pmxi_files: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_pmxi_history: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_pmxi_imports: داده: 0.05مگابایت + شاخص: 0.00مگابایت
dmall_pmxi_posts: داده: 0.06مگابایت + شاخص: 0.00مگابایت
dmall_pmxi_templates: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_postmeta: داده: 19.04مگابایت + شاخص: 4.55مگابایت
dmall_posts: داده: 5.30مگابایت + شاخص: 0.83مگابایت
dmall_pv_commission: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_queue: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_exclude: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_folders: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_maps: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_membership_presets: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_photos: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_photos_pos: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_resources: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_settings_presets: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_settings_sets: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_sliders: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_sorting: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_stats: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_tags: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_rs_videos: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_slider_pro_layers: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_slider_pro_sliders: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_slider_pro_slides: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_smush_dir_images: داده: 0.02مگابایت + شاخص: 0.03مگابایت
dmall_social_users: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_statistics_exclusions: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_statistics_historical: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_statistics_pages: داده: 4.86مگابایت + شاخص: 12.72مگابایت
dmall_statistics_search: داده: 0.31مگابایت + شاخص: 0.20مگابایت
dmall_statistics_useronline: داده: 0.03مگابایت + شاخص: 0.00مگابایت
dmall_statistics_visit: داده: 0.00مگابایت + شاخص: 0.01مگابایت
dmall_statistics_visitor: داده: 6.73مگابایت + شاخص: 6.10مگابایت
dmall_termmeta: داده: 0.21مگابایت + شاخص: 0.17مگابایت
dmall_terms: داده: 0.47مگابایت + شاخص: 0.60مگابایت
dmall_term_relationships: داده: 0.31مگابایت + شاخص: 0.57مگابایت
dmall_term_taxonomy: داده: 0.25مگابایت + شاخص: 0.27مگابایت
dmall_ulp_campaigns: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_ulp_campaign_items: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_ulp_layers: داده: 0.28مگابایت + شاخص: 0.01مگابایت
dmall_ulp_popups: داده: 0.08مگابایت + شاخص: 0.00مگابایت
dmall_ulp_subscribers: داده: 0.01مگابایت + شاخص: 0.00مگابایت
dmall_ulp_webfonts: داده: 0.03مگابایت + شاخص: 0.01مگابایت
dmall_usermeta: داده: 15.88مگابایت + شاخص: 0.33مگابایت
dmall_users: داده: 0.03مگابایت + شاخص: 0.03مگابایت
dmall_wcfm_daily_analysis: داده: 0.08مگابایت + شاخص: 0.05مگابایت
dmall_wcfm_detailed_analysis: داده: 0.36مگابایت + شاخص: 0.00مگابایت
dmall_wcfm_enquiries: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wcfm_messages: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wcfm_messages_modifier: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wcfm_messages_stat: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wcmp_products_map: داده: 0.08مگابایت + شاخص: 0.00مگابایت
dmall_wcmp_vendor_orders: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_wcpdf_invoice_number: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wc_deposits_payment_plans: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wc_deposits_payment_plans_schedule: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_wc_download_log: داده: 0.02مگابایت + شاخص: 0.03مگابایت
dmall_wc_webhooks: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_wfBadLeechers: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wfBlockedCommentLog: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wfBlockedIPLog: داده: 0.16مگابایت + شاخص: 0.00مگابایت
dmall_wfBlocks: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_wfBlocks7: داده: 0.02مگابایت + شاخص: 0.05مگابایت
dmall_wfBlocksAdv: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wfConfig: داده: 0.30مگابایت + شاخص: 0.00مگابایت
dmall_wfCrawlers: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wfFileChanges: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wfFileMods: داده: 4.52مگابایت + شاخص: 0.00مگابایت
dmall_wfHits: داده: 5.02مگابایت + شاخص: 1.52مگابایت
dmall_wfHoover: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_wfIssues: داده: 0.02مگابایت + شاخص: 0.06مگابایت
dmall_wfKnownFileList: داده: 1.52مگابایت + شاخص: 0.00مگابایت
dmall_wfLeechers: داده: 2.02مگابایت + شاخص: 0.00مگابایت
dmall_wfLockedOut: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wfLocs: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wfLogins: داده: 0.17مگابایت + شاخص: 0.06مگابایت
dmall_wfNet404s: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_wfNotifications: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wfPendingIssues: داده: 0.02مگابایت + شاخص: 0.06مگابایت
dmall_wfReverseCache: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wfScanners: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_wfSNIPCache: داده: 0.02مگابایت + شاخص: 0.05مگابایت
dmall_wfStatus: داده: 0.14مگابایت + شاخص: 0.09مگابایت
dmall_wfThrottleLog: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_wfVulnScanners: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_woo2app_mainpage: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woo2app_menu: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woo2app_setting: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woo2app_slider: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_woocommerce_bundled_itemmeta: داده: 0.02مگابایت + شاخص: 0.03مگابایت
dmall_woocommerce_bundled_items: داده: 0.02مگابایت + شاخص: 0.03مگابایت
dmall_woocommerce_ir: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_woof_query_cache: داده: 0.02مگابایت + شاخص: 0.02مگابایت
dmall_wpsp_agent_settings: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_wpsp_attachments: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_wpsp_catagories: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_wpsp_panel_custom_menu: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_wpsp_ticket: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_wpsp_ticket_thread: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcact_auction: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcaf_affiliates: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcaf_clicks: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcaf_commissions: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcaf_commission_notes: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcaf_payments: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcaf_payment_commission: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcaf_payment_notes: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcmbs_downloads_log: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcwl: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_yith_wcwl_lists: داده: 0.00مگابایت + شاخص: 0.01مگابایت
dmall_yith_ywpar_points_log: داده: 0.02مگابایت + شاخص: 0.00مگابایت
dmall_yoast_seo_links: داده: 0.30مگابایت + شاخص: 0.16مگابایت
dmall_yoast_seo_meta: داده: 0.08مگابایت + شاخص: 0.00مگابایت
dmall_ywcdd_calendar: داده: 0.00مگابایت + شاخص: 0.00مگابایت
dmall_ywf_user_fund_log: داده: 0.00مگابایت + شاخص: 0.00مگابایت

### Post Type Counts ###

accordion_menu: 1
accordion_shortcode: 1
accordions: 1
attachment: 5146
blocks: 52
clever_menu: 3
clever_menu_theme: 2
custom_css: 1
customize_changeset: 37
dc_commission: 22
mc4wp-form: 2
ml-slide: 3
ml-slider: 1
nav_menu_item: 292
option-tree: 1
page: 44
post: 141
product: 917
product_variation: 654
pw_gift_rule: 2
revision: 74
shop_coupon: 17
shop_order: 268
shop_order_refund: 6
shop_order_vendor: 5
soliloquy: 1
um_directory: 1
um_form: 3
um_role: 2
vc_grid_item: 21
vc4_templates: 2
wafs: 1
woocarousel: 1
wpcf7_contact_form: 6
wysijap: 1
yith_carrier: 1
yith_proc_method: 1
yith_wcps_type: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (47) ###

درگاه پرداخت بانک پاسارگاد افزونه ووکامرس: توسط ووکامرس فارسی – 4.1.0
Accordions: توسط pickplugins – 2.0.21
Advanced Access Manager: توسط Vasyl Martyniuk  – 5.0.8
All 404 Redirect  to Homepage: توسط Fakhri Alsadi – 1.8
All In One WP Security: توسط Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.2

appchar_wc3: توسط appchar – 3.1.9.2
Better Font Awesome: توسط Mickey Kay – 1.7.1
Capability Manager Enhanced: توسط Jordi Canals
Kevin Behrens – 1.5.7

Contact Form 7: توسط Takayuki Miyoshi – 5.0
WC Marketplace: توسط WC Marketplace
The Grey Parrots – 2.7.8

Google Analytics for WordPress by MonsterInsights: توسط MonsterInsights – 6.2.8
WPBakery Page Builder: توسط Michael M - WPBakery.com – 5.4.5
Kamrosoft Free gift: توسط AstroTemplates – 1.0.1
Loco Translate: توسط Tim Whitlock – 2.0.17
MailChimp for WooCommerce: توسط MailChimp – 2.1.3 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
MailChimp for WordPress: توسط ibericode – 4.1.14
OneSignal Push Notifications: توسط OneSignal – 1.16.5
PEC gateway for Woocommerce: توسط Mojtaba Darvishi – 2.0.0 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
Perfect WooCommerce Brands: توسط Alberto de Vera Sevilla – 1.6.1
Persian Woocommerce Shipping: توسط MahdiY – 0.9.1
افزونه حرفه ای پیامک ووکامرس: توسط ووکامرس فارسی – 3.6.8
ووکامرس فارسی: توسط ووکامرس فارسی – 3.2.6.1
Recommender Service: توسط Mahshad Kalantari – 1.1.0 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
Regenerate Thumbnails: توسط Alex Mills (Viper007Bond) – 3.0.2
Slider Pro: توسط bqworks – 4.2.0
String Locator: توسط Clorith – 2.3.0
UberMenu 3 - The Ultimate WordPress Mega Menu: توسط Chris Mavricos
SevenSpark – 3.2.6

WooCommerce Frontend Manager: توسط WC Lovers – 3.4.6
Widget Shortcode: توسط Hassan Derakhshandeh – 0.3.0
WooCommerce Checkout Manager: توسط Visser Labs – 4.1.6 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
فاکتور ووکامرس: توسط ایستاتیک – 4.2.1
Booster for WooCommerce: توسط Algoritmika Ltd – 3.3.0
درگاه پرداخت بانک سامان افزونه ووکامرس: توسط ووکامرس پارسی – 4.1.0
ووکامرس: توسط اتوماتیک – 3.2.6
WooSidebars: توسط WooThemes – 1.4.3
Wordfence Security: توسط Wordfence – 7.0.2
Yoast SEO Premium: توسط پرشین اسکریپت – 5.2
Wp Logito: توسط Zanyar Abdolahzadeh – 1.1.8 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
بسته وردپرس پارسی: توسط تیم وردپرس پارسی – 2.3.4
WP Rocket: توسط WP Media – 2.9.5
WP-RTL: توسط Fahad Alduraibi – 1.0
WP Smush: توسط WPMU DEV – 2.7.6
آمار وردپرس: توسط ورونا لبز – 12.3.5
Yoast SEO: WooCommerce: توسط پرشین اسکریپت – 5.2 – با نسخه ووکامرس فعال شده شما آزمایش نشده است
افزونه فیلتر محصول ووکامرس: توسط YITHEMES – 3.5.0
YITH WooCommerce Product Bundles: توسط YITHEMES – 1.1.3
YITH WooCommerce Wishlist: توسط YITHEMES – 2.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

پایگاه فروشگاه: #805 - /shop/
سبد خرید: #807 - /cart/
تسویه حساب: #809 - /checkout/
حساب کاربری: #5998 - /account/
شرایط و مقررات: #5474 - /terms/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.4.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product.php
flatsome/woocommerce/single-product-reviews.php

`
</details>

**Comment by mikejolley** [comment]
Does not seem to be a problem in admin:

![products local wordpress dev wordpress 2018-02-06 10-43-26](https://user-images.githubusercontent.com/90977/35855260-97483756-0b2a-11e8-9bb5-85fdf5b53aef.png)

Drafts are not shown on the frontend.

Most likely a plugin conflict; you should go through the list and rule them all out. I'd start with `Booster for WooCommerce` because it's a common source of problems for many users.

Thanks
