### ISSUE TITLE
Update Cart & Checkout

### ISSUE THREAD

**Issue by libelle11** [woocommerce/woocommerce#18826]
I create a new page called "Landingpage Produkt A". At the end of my landing page I add the short code "[product id="62"]". This makes product A orderable.
Under this short code I add "[woocommerce_cart]" and "[woocommerce_checkout]". I want the customer to be able to order product A very easily.

I want to use the "AJAX Add to Cart" function.

If I now press the "Add to Cart" button on product A, no filled shopping cart or checkout will be displayed. Only after a manual reload of the page the filled shopping cart and the checkout will be displayed.

It would be great if this would be possible in the future without a plugin (e. g."OnePageCheckout").

Thanks.

**Comment by mikejolley** [comment]
Cart and checkout are designed to be on separate pages, which I believe is why OnePageCheckout exists. Using these all on the same page will not have the ideal flow for customers and as it's not officially supported there could be other problems. 

There are other solutions such as forcing an item inside a new users cart so they don't need to add to cart, just checkout. May require some custom code.

Anyhow, if you're adamant this should be part of core, please log on the ideas board: ideas.woocommerce.com. If it gets enough traction it can be investigated further.

Thanks
