### ISSUE TITLE
Cant save variations on the backend of a product

### ISSUE THREAD

**Issue by atsouf** [woocommerce/woocommerce#18832]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  I get to the edit page of a variable product
2. I go to the attributes tab. Everything seems fine
3. I go to the variations and an all combinations instead of each attribute price that i have it has everything on Any "value"
4. I set again the values 
5. I save it
6. After 2 seconds everything comes back to Any "value"

## Expected/actual behavior

When I follow those steps, I see The Any "value"

I was expecting to see each row to have the values i set from tha attribues

----------------------------------
I notice that if i recreate the variations and they get different id, everything works properly

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://healthywater.gr
Site URL: https://healthywater.gr
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 512 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: ✔
MySQL Version: 5.6.38
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 5.85MB
Database Data Size: 4.98MB
Database Index Size: 0.87MB
wp_woocommerce_sessions: Data: 0.46MB + Index: 0.03MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.73MB + Index: 0.06MB
wp_postmeta: Data: 0.51MB + Index: 0.20MB
wp_posts: Data: 0.72MB + Index: 0.05MB
wp_revslider_css: Data: 0.09MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.18MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_subscriptio_scheduled_events: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.01MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wp_usermeta: Data: 0.01MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_deposits_payment_plans: Data: 0.00MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 0.24MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB
wp_wfFileMods: Data: 1.14MB + Index: 0.24MB
wp_wfHits: Data: 0.24MB + Index: 0.05MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.00MB + Index: 0.01MB
wp_wfKnownFileList: Data: 0.57MB + Index: 0.08MB
wp_wfLeechers: Data: 0.00MB + Index: 0.01MB
wp_wfLocs: Data: 0.00MB + Index: 0.00MB
wp_wfLogins: Data: 0.00MB + Index: 0.00MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.00MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_wfScanners: Data: 0.00MB + Index: 0.01MB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.06MB + Index: 0.03MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
wp_yoast_seo_links: Data: 0.01MB + Index: 0.00MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 199
customize_changeset: 1
etheme_portfolio: 6
inventory: 1
mc4wp-form: 1
nav_menu_item: 19
page: 16
post: 17
product: 32
product_variation: 74
revision: 79
shop_order: 1
staticblocks: 5
testimonials: 3
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (22) ###

Redux Framework: by Team Redux – 3.6.7.7
CMB2: by CMB2 team – 2.3.0
Contact Form 7: by Takayuki Miyoshi – 5.0
Cookie Notice: by dFactory – 1.2.41
XStore Core: by 8theme – 1.0.20
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.5
Like 2 Discount: by Laborator – 1.4
Loco Translate: by Tim Whitlock – 2.0.17
MailChimp for WordPress: by ibericode – 4.1.14
Massive Addons for Visual Composer: by MassivePixelCreation – 2.2
Really Simple SSL: by Rogier Lankhorst – 2.5.24
Slider Revolution: by ThemePunch – 5.4.5.1
WooCommerce Infinite Scroll and Ajax Pagination: by SB Themes – 1.1 – Not tested with the active version of WooCommerce
Subscriptio: by RightPress – 2.3.8 – Not tested with the active version of WooCommerce
WooCommerce Checkout Manager: by Visser Labs – 4.1.6 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.6
Wordfence Security: by Wordfence – 7.0.2
Yoast SEO: by Team Yoast – 6.2
WP Super Cache: by Automattic – 1.5.9
GMAPS for Visual Composer: by WWP – 1.5
YITH WooCommerce Compare: by YITHEMES – 2.2.3
YITH WooCommerce Wishlist: by YITHEMES – 2.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
redq_rental (redq_rental)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4477 - /eshop/
Cart: #4474 - /cart/
Checkout: #4475 - /checkout/
My account: #4476 - /my-account/
Terms and conditions: #4484 - /terms/

### Theme ###

Name: XStore Child
Version: 0.0.1
Author URL: http://8theme.com
Child Theme: ✔
Parent Theme Name: XStore
Parent Theme Version: 4.17
Parent Theme Author URL: http://www.8theme.com
WooCommerce Support: ✔

### Templates ###

Overrides: xstore/woocommerce/archive-product.php
xstore/woocommerce/cart/cart-empty.php
xstore/woocommerce/cart/cart-item-data.php
xstore/woocommerce/cart/cart.php
xstore/woocommerce/cart/cross-sells.php
xstore/woocommerce/cart/mini-cart.php
xstore/woocommerce/checkout/form-billing.php
xstore/woocommerce/checkout/form-checkout.php
xstore/woocommerce/checkout/form-shipping.php
xstore/woocommerce/content-product.php
xstore/woocommerce/content-product_cat.php
xstore/woocommerce/content-single-product.php
xstore/woocommerce/content-widget-product.php
xstore/woocommerce/global/breadcrumb.php
xstore/woocommerce/global/form-login.php
xstore/woocommerce/global/quantity-input.php
xstore/woocommerce/global/wrapper-end.php
xstore/woocommerce/global/wrapper-start.php
xstore/woocommerce/loop/loop-end.php
xstore/woocommerce/loop/loop-start.php
xstore/woocommerce/loop/no-products-found.php
xstore/woocommerce/loop/pagination.php
xstore/woocommerce/loop/sale-flash.php
xstore/woocommerce/single-product/add-to-cart/simple.php
xstore/woocommerce/single-product/product-image.php
xstore/woocommerce/single-product/related.php
xstore/woocommerce/single-product/sale-flash.php
xstore/woocommerce/single-product/short-description.php
xstore/woocommerce/single-product/tabs/additional-information.php
xstore/woocommerce/single-product/tabs/description.php
xstore/woocommerce/single-product/tabs/tabs.php
xstore/woocommerce/single-product/title.php
xstore/woocommerce/single-product/up-sells.php
xstore/woocommerce/single-product.php
</details>

**Comment by mikejolley** [comment]
How was this product imported/created? If new products are working it could indicate a problem with the meta data.

**Comment by mikejolley** [comment]
I saw https://wordpress.org/support/topic/wordpress-4-9-3-update-created-issues-with-variations/

Jumping between versions could cause more issues. I suggest you look at the postmeta for one of the affected variations and see what the meta key and value is.

**Comment by atsouf** [comment]
Hello, we added teh products manually and 2 days ago everything was working perfectly. I uploaded a full backup from 5 days ago and still the issue persists.

I have the filling that it has to do with existing ids. When i create a new product everything is ok.

**Comment by atsouf** [comment]
Ι searched and variaton id that has issue and on the pa_customatribute is blank on database

**Comment by mikejolley** [comment]
Related: https://github.com/woocommerce/woocommerce/issues/17775

Its not going to be the IDs, it's going to be the difference with the data between WP 4.8 and 4.9. If you're jumping around versions and restoring backups, it's going to break.

**Comment by mikejolley** [comment]
FYI blank value = any

**Comment by atsouf** [comment]
I had the backup with wp 4.9.2 and woocommerce 3.2.6,

I deleted the database and the public_html and i imported the backup that i mention above.

I realise that blank value is any.

I get to the edit product, i select a value on the variations i save and then it turns back to any. Thats why the db has blank

**Comment by mikejolley** [comment]
See what other `pa_` meta is there in the DB. Delete those rows. Save (it should work) and then look again at the `pa_` meta data. I'm betting the keys will look slightly different after doing so.

**Comment by atsouf** [comment]
I did delete all the attributes on the specific variation id from db. All the rows. I go on edit product and still when i assign it turns back to Any

I sent you credentials if you can give it a look so you can see what i mean

**Comment by mikejolley** [comment]
Tested with your attribute names and values on local and it saved. This must be a conflict. Will email.

**Comment by atsouf** [comment]
As i explained there is nothing wrong with creating new products with
variations. The existing ones have the issue

2018-02-06 17:02 GMT+02:00 Mike Jolley <notifications@github.com>:
