### ISSUE TITLE
Product download URLs contain personally identifiable information (PII)

### ISSUE THREAD

**Issue by philipdowner** [woocommerce/woocommerce#18835]
To best protect a user's identity online we should avoid passing their email address in product download links. This information is subject to be collected by 3rd party tools such as Google Analytics. In fact, if Google ever receives this information, [the website will be penalized](https://support.google.com/analytics/answer/6366371?hl=en) until the issue is resolved.

The download action (in WC_Download_Handler class) is not hooked on `init` unless the download file ID, order ID hash and user email are all present in the query string.

```php
<?php
class WC_Download_Handler {

	/**
	 * Hook in methods.
	 */
	public static function init() {
		if ( isset( $_GET['download_file'], $_GET['order'], $_GET['email'] ) ) {
			add_action( 'init', array( __CLASS__, 'download_product' ) );
		}
		add_action( 'woocommerce_download_file_redirect', array( __CLASS__, 'download_file_redirect' ), 10, 2 );
		add_action( 'woocommerce_download_file_xsendfile', array( __CLASS__, 'download_file_xsendfile' ), 10, 2 );
		add_action( 'woocommerce_download_file_force', array( __CLASS__, 'download_file_force' ), 10, 2 );
	}
```

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Purchase an item that contains downloadable files
2. Check the customer facing receipt email that contains links to each downloadable file

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by claudiulodro** [comment]
Makes sense. Probably best to switch to user ids similar to https://github.com/woocommerce/woocommerce/pull/18820

**Comment by mikejolley** [comment]
@claudiulodro @philipdowner GUESTS do not have user IDs. We cannot force accounts on all users of all stores, and clearly we need some way of identifying a user to prevent fraud.

**Comment by philipdowner** [comment]
@mikejolley Is the order ID hash enough to identify the order that initiated the request or is that subject to potential fraud?

**Comment by mikejolley** [comment]
Order ID is guessable. Email hash could potentially be used ^

**Comment by philipdowner** [comment]
@mikejolley I agree that that approach would probably work best. Google has requirements on the level of encryption required:

> Hashed and salted PII
> You can send Google Analytics an encrypted identifier or custom dimension that is based on PII, as long as you use the proper encryption level. Google has a minimum hashing requirement of SHA256 and strongly recommends the use of a salt, with a minimum of 8 characters. Notwithstanding any of the foregoing, you may not send Google Analytics encrypted Protected Health Information (as defined under HIPAA), even if it is hashed or salted.

**Comment by mikejolley** [comment]
We won't need to encrypt anything. Hashing cannot be reversed.

**Comment by philipdowner** [comment]
@mikejolley To your point that this doesn't need to be cryptographically secure as we're simply obfuscating information, would you see any problem with using something as simple as:

```php
<?php
$email = hash('sha256', 'email@test.com');
```

We would then hash the email address from the order and compare it to the $_GET request. If they match, allow the download.

If this seems like the right approach, I'll get working on a PR.

**Comment by mikejolley** [comment]
md5 function should be enough here.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18957
