### ISSUE TITLE
Why does woocommerce require authentication for read access on the same domain?

### ISSUE THREAD

**Issue by Pushplaybang** [woocommerce/woocommerce#18837]
Why would we require authentication for read access on the same domain?

Current behaviour:

401 or 403 errors, trying to simply read a list of products. Basically Authentication is required.

expected behaviour:

uniform read access, in line with the wp-rest API

**Comment by WPprodigy** [comment]
Products are significantly more complex that normal blog post. There is information included in the response that probably shouldn't be publicly available imo: http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

**Comment by mikejolley** [comment]
@Pushplaybang Our API is built on top of the WP REST API, so whilst our docs cover _WooCommerce specific_ auth designed for external apps, you can use any WordPress auth method.

On the same domain, I believe a common option is cookie based auth https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/ And if thats not enough, extend it with your own auth system. Just be cautious not to reveal too much e.g. orders.

> Surely this is a common enough use case

If you're like to contribute a wiki article about this please feel free to do so; it's open like the plugin. Generally the core devs don't need to consume the API, we just build the endpoints, so any contributions there are welcome :)

cc @claudiosanches 

Thanks

**Comment by Pushplaybang** [comment]
@mikejolley  thanks for the response, Just so I understand what you're saying here, 

there's no standard way, for unauthenticated users, to be displayed a list of products by the theme, that are called from the rest API by client-side javascript?

**Comment by mikejolley** [comment]
Out of the box, no. It is however possible to either extend the auth methods or filter permissions to let anyone through. Just be cautious of revealing anything private.

**Comment by Pushplaybang** [comment]
@mikejolley great thanks, anything specific around the products I shouldn't be sending it over?  Had a look, but there nothing specific that jumped out at me.

think there's room here, at least for a plugin, to proxy an open / sanitised version to the client.

**Comment by mikejolley** [comment]
Purchase note is a private field. Meta. It really depends on the use case. Not all data should be exposed.

**Comment by Pushplaybang** [comment]
yeah, this really should at the very least be up to the store owner. 

Feels very much like a hack at the moment.
