### ISSUE TITLE
Shortcode '[product_category]' defaults to 12 items instead of -1

### ISSUE THREAD

**Issue by jester1979** [woocommerce/woocommerce#18836]
When using the shortcode: [product_category] it should default to limit="-1" according to your documentation: https://docs.woocommerce.com/document/woocommerce-shortcodes/

Yet it defaults to 12 products instead, see: 
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-shortcodes.php#L134

**Comment by mikejolley** [comment]
Then we should update the docs because this is not a recent code change.

**Comment by mikejolley** [comment]
Updated. Thanks for the report.
