### ISSUE TITLE
Image regeneration and external hosted images PHP warning

### ISSUE THREAD

**Issue by kloon** [woocommerce/woocommerce#18842]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. Install the WP Offload S3 plugin
2. Upload images to an S3 bucket
3. Use said images on products
4. PHP warning `PHP Warning: getimagesize(): corrupt JPEG data: 120 extraneous bytes before marker in /home/[myuser]/public_html/ar/wp-content/plugins/woocommerce/includes/class-wc-regenerate-images.php on line 109` when viewing product archive.

## Expected/actual behavior

When I follow those steps, I see a PHP warning `PHP Warning: getimagesize(): corrupt JPEG data: 120 extraneous bytes before marker in /home/[myuser]/public_html/ar/wp-content/plugins/woocommerce/includes/class-wc-regenerate-images.php on line 109`

I was expecting to see images with their correct ratios.

## Isolating the problem
- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18850
