### ISSUE TITLE
Edit Product Trigger 404 !

### ISSUE THREAD

**Issue by ody911** [woocommerce/woocommerce#18846]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
You need to go through https://github.com/woocommerce/woocommerce/issues/new properly and carry out all steps/provide all details. This is not a bug on my install so it's something specific to yours.

**Comment by ody911** [comment]
the Edit Product is not working for admin or vendor

**Comment by mikejolley** [comment]
It's not affecting all users of WooCommerce so do what I suggested.
