### ISSUE TITLE
Orders Duplications

### ISSUE THREAD

**Issue by orlaryemy** [woocommerce/woocommerce#18848]
can someone help me out here, Duplicate Orders are Created for my users at my cart page

WordPress environment

WC version: |   | 3.3.1
Log directory writable: |   | /wpcom-133221194/wp-content/uploads/wc-logs/
WP version: |   | 4.9.4
WP multisite: |   | –
WP memory limit: |   | 256 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US

**Comment by mikejolley** [comment]
Please read https://github.com/woocommerce/woocommerce/issues/new fully and go through all of the steps before logging issues.

**Comment by orlaryemy** [comment]
can you pls send me the link to the post?
