### ISSUE TITLE
How i enable cache for logged in user in woocommerce

### ISSUE THREAD

**Issue by sarun007** [woocommerce/woocommerce#18847]
Hi there! I have one website on that website i facing the speed problem on that site.When we experiencing the speed issue at the time of user logged in on the site.Om site i protected the price and variable of product by using WooCommerce Catalog Visibility Options plugin.If user is  not logged in the site then user cant see the price and variation of the product.With out login the site loading much faster.But when user logged in the shop page and single product page taking too much loading time at that time TTFB is very high when i contacted the host they are saying woocommerce taking much time to query.And also they saying there is no cache for logged in users.if there any options to enable cache for logged in users??

I changed the theme into default theme at that time we facing same loading issue on logged in user.

`
### WordPress Environment ###

Home URL: https://deltapictureframe.com
Site URL: https://deltapictureframe.com
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31-4+wpengine10
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.1
WC Database Prefix: wp_
Total Database Size: 44.49MB
Database Data Size: 26.64MB
Database Index Size: 17.85MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_aws_cache: Data: 0.02MB + Index: 0.00MB
wp_aws_index: Data: 0.20MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.11MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.42MB + Index: 0.22MB
wp_postmeta: Data: 19.55MB + Index: 15.03MB
wp_posts: Data: 1.52MB + Index: 0.88MB
wp_relevanssi: Data: 0.30MB + Index: 0.47MB
wp_relevanssi_log: Data: 0.02MB + Index: 0.02MB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_social_users: Data: 0.02MB + Index: 0.02MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.05MB + Index: 0.03MB
wp_term_relationships: Data: 0.47MB + Index: 0.33MB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wp_usermeta: Data: 1.19MB + Index: 0.09MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woof_query_cache: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 605
blocks: 8
custom_css: 1
customize_changeset: 6
featured_item: 8
nav_menu_item: 38
nf-popups: 1
page: 77
popup: 1
popup_theme: 6
post: 13
product: 2527
product_variation: 1806
revision: 2
shop_order: 4
um_directory: 1
um_form: 4
um_role: 2
wccpf: 1
wpcf7_contact_form: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

ManageWP - Worker: by ManageWP – 4.3.4
Async JavaScript: by Clough I.T. Solutions – 2.17.11.15
Autoptimize: by Frank Goossens (futtta) – 2.3.2
Better Search Replace: by Delicious Brains – 1.3.2
Contact Form 7: by Takayuki Miyoshi – 5.0
Debug Bar ElasticPress: by 10up – 1.3
Debug Bar: by wordpressdotorg – 0.9
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
Envato WordPress Toolkit: by Envato – 1.7.3
Ninja Forms: by The WP Ninjas – 3.2.11
Popup Maker: by WP Popup Maker – 1.6.6
Real-Time Find and Replace: by Marios Alexandrou – 3.9
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Relevanssi: by Mikko Saari – 4.0.4
Ultimate Member: by Ultimate Member – 1.3.88
WC Fields Factory: by Saravana Kumar K – 2.0.6 – Not tested with the active version of WooCommerce
WC Speed Drain Repair: by WP Fix It – 1.2 – Not tested with the active version of WooCommerce
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.2.5
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.1.0 – Not tested with the active version of WooCommerce
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.2.0
WooCommerce Measurement Price Calculator: by SkyVerge – 3.13.0
WooCommerce PDF & Print: by gVectors Team – 1.5.0 – Not tested with the active version of WooCommerce
WooCommerce Pretty Emails: by MB Création – 1.8.6 – Not tested with the active version of WooCommerce
WooCommerce Product Finder: by WooCommerce – 1.2.4
WooCommerce: by Automattic – 3.3.1
WooSidebars: by WooThemes – 1.4.3
WP Smush: by WPMU DEV – 2.7.6
WPMU DEV Dashboard: by WPMU DEV – 4.4
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.5.0
YITH WooCommerce Wishlist: by YITHEMES – 2.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #63 - /shop/
Cart: #62 - /cart/
Checkout: #61 - /checkout/
My account: #60 - /my-account/
Terms and conditions: #226 - /terms-conditions/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.4.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php version 3.1.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.3.0
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/admin-cancelled-order.php version 2.3.0 is out of date. The core version is 2.5.0
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/admin-failed-order.php
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/admin-new-order.php version 2.0.0 is out of date. The core version is 2.5.0
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/customer-completed-order.php version 1.6.4 is out of date. The core version is 2.5.0
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/customer-invoice.php version 2.2.0 is out of date. The core version is 3.3.0
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/customer-new-account.php
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/customer-note.php version 1.6.4 is out of date. The core version is 2.5.0
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/customer-on-hold-order.php version - is out of date. The core version is 2.5.0
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/customer-processing-order.php version 1.6.4 is out of date. The core version is 2.5.0
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/customer-refunded-order.php version 2.4.0 is out of date. The core version is 2.5.0
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/customer-reset-password.php
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/email-addresses.php version 2.2.0 is out of date. The core version is 3.2.1
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/email-customer-details.php
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/email-footer.php version 2.0.0 is out of date. The core version is 2.3.0
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/email-header.php version 1.0 is out of date. The core version is 2.4.0
/nas/content/live/deltapicture/wp-content/plugins/woocommerce-pretty-emails/emails/email-order-items.php version 2.1.2 is out of date. The core version is 3.2.0
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php version 3.2.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/global/wrapper-end.php version 1.6.4 is out of date. The core version is 3.3.0
flatsome/woocommerce/global/wrapper-start.php version 1.6.4 is out of date. The core version is 3.3.0
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/loop/pagination.php version 2.2.2 is out of date. The core version is 3.3.1
flatsome/woocommerce/loop/result-count.php version 3.0.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/loop/sale-flash.php
flatsome-child/woocommerce/myaccount/form-login.php version 3.2.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php version 1.6.4 is out of date. The core version is 3.3.0
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php version 1.6.4 is out of date. The core version is 3.3.0
flatsome/woocommerce/product-searchform.php version 2.5.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php version 1.6.4 is out of date. The core version is 3.3.0
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update

**Comment by mikejolley** [comment]
This would be down to your caching plugin, however caching logged in user requests wouldn't be a good idea because it could lead to customers seeing each others details!

**Comment by sarun007** [comment]
Thank you for your fast reply !! If there any way to speedup site for logged in customer based user??

**Comment by mikejolley** [comment]
It's based on many factors, so I don't have a simple solution for you.

**Comment by sarun007** [comment]
then how i speedup woocommerce site for logged in users??

**Comment by GlennMartin1** [comment]
Like Mike Jolly said, speed is based on numerous factors - you could hire a WordPress developer to review your site. This is a WooCommerce developer's platform - not for the types of questions you're raising. 

However, you're using PHP 5.6. Have your host upgrade your site to PHP 7+; it would double your site speed.
