### ISSUE TITLE
Payment date is null and not displayed in case of Cash on delivery.

### ISSUE THREAD

**Issue by kolinz** [woocommerce/woocommerce#18845]
## Prerequisites

- [* ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ *] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. product order & Checkout
2. go to WordPress admin screen --> WooCommerce --> Orders
3. View Order Detail
4. It does not display payment date in case used payment method is cod. cod = Cash on delivery.
5. go to database . "_paid_date" is null in MySQL. 

![mysql_capture_paiddate_isnull_20180207_japan](https://user-images.githubusercontent.com/16685896/35912631-71784658-0c40-11e8-8d82-85a74faefe34.PNG)

## Expected/actual behavior
Payment date recorded and displayed.

## Isolating the problem

- [*] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [*] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

```
### WordPress Environment ###

Home URL: https://
Site URL:https://
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.8.5
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: –
Language: ja

### Server Environment ###

Server Info: nginx/1.13.8
PHP Version: 7.0.27
PHP Post Max Size: 32 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.53.1
NSS/3.28.4
```
</details>

**Comment by mikejolley** [comment]
In real life, COD won't be paid until you give the customer their item and take payment. So this is correct to be null. It will change when the order is complete.
