### ISSUE TITLE
[3.3] Products Search: Include pending products

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18856]
`WC_Product_Data_Store_CPT->search_products()` doesn't search for products in the pending status.

https://wordpress.org/support/topic/woocommerce-3-3-1-doesnt-search-pending-products/

**Comment by WPprodigy** [comment]
This will fix: http://cld.wthms.co/713XaE

Just not sure if that will lead to unintended results elsewhere. Maybe need to pass in an optional argument for this if so.

**Comment by ShaneGowland** [comment]
I'm having this issue with Scheduled and Draft products as well.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18880
