### ISSUE TITLE
Product gallery images not showing when using CDN 

### ISSUE THREAD

**Issue by nuclearape** [woocommerce/woocommerce#18853]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Setup W3 Total Cache to use a CDN
2. Go and have a look at a product page with a few images in the gallery - the product images are missing

## Expected/actual behavior

When I follow those steps, I see missing images

I was expecting to see the images display as normal

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
### WordPress Environment ###

Home URL: https://dev.chucklinggoat.co.uk
Site URL: https://dev.chucklinggoat.co.uk
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.29 (cPanel) OpenSSL/1.0.2n mod_bwlimited/1.4
PHP Version: 7.0.27
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.0.2n

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.1
WC Database Prefix: wp_
Total Database Size: 1326.17MB
Database Data Size: 851.60MB
Database Index Size: 474.57MB
wp_woocommerce_sessions: Data: 3.55MB + Index: 0.09MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.06MB + Index: 0.07MB
wp_woocommerce_order_items: Data: 21.33MB + Index: 12.35MB
wp_woocommerce_order_itemmeta: Data: 164.99MB + Index: 98.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_automatewoo_abandoned_carts: Data: 0.69MB + Index: 0.06MB
wp_automatewoo_customers: Data: 1.54MB + Index: 2.80MB
wp_automatewoo_events: Data: 0.00MB + Index: 0.01MB
wp_automatewoo_guests: Data: 0.27MB + Index: 0.28MB
wp_automatewoo_guest_meta: Data: 0.20MB + Index: 0.11MB
wp_automatewoo_logs: Data: 0.85MB + Index: 1.83MB
wp_automatewoo_log_meta: Data: 5.44MB + Index: 3.23MB
wp_automatewoo_queue: Data: 0.03MB + Index: 0.06MB
wp_automatewoo_queue_meta: Data: 0.15MB + Index: 0.12MB
wp_automatewoo_unsubscribes: Data: 0.00MB + Index: 0.00MB
wp_camera: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 7.06MB + Index: 4.19MB
wp_comments: Data: 135.63MB + Index: 65.48MB
wp_ebay_accounts: Data: 0.00MB + Index: 0.00MB
wp_ebay_auctions: Data: 0.01MB + Index: 0.01MB
wp_ebay_categories: Data: 0.78MB + Index: 0.45MB
wp_ebay_jobs: Data: 0.00MB + Index: 0.00MB
wp_ebay_log: Data: 0.00MB + Index: 0.00MB
wp_ebay_messages: Data: 0.00MB + Index: 0.00MB
wp_ebay_orders: Data: 0.29MB + Index: 0.00MB
wp_ebay_payment: Data: 0.00MB + Index: 0.00MB
wp_ebay_profiles: Data: 0.00MB + Index: 0.00MB
wp_ebay_shipping: Data: 0.01MB + Index: 0.00MB
wp_ebay_sites: Data: 0.03MB + Index: 0.00MB
wp_ebay_store_categories: Data: 0.00MB + Index: 0.00MB
wp_ebay_transactions: Data: 0.47MB + Index: 0.00MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Data: 3.37MB + Index: 0.00MB
wp_options: Data: 4.23MB + Index: 0.77MB
wp_postmeta: Data: 388.41MB + Index: 231.43MB
wp_posts: Data: 29.67MB + Index: 9.03MB
wp_po_plugins: Data: 0.00MB + Index: 0.01MB
wp_queue: Data: 0.00MB + Index: 0.00MB
wp_QuoteRotator: Data: 0.00MB + Index: 0.00MB
wp_redirection_404: Data: 0.38MB + Index: 0.14MB
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB
wp_redirection_items: Data: 0.01MB + Index: 0.01MB
wp_redirection_logs: Data: 0.83MB + Index: 0.19MB
wp_smush_dir_images: Data: 0.04MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.01MB + Index: 0.02MB
wp_term_relationships: Data: 0.06MB + Index: 0.14MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 76.82MB + Index: 40.81MB
wp_users: Data: 3.48MB + Index: 2.71MB
wp_w3tc_cdn_pathmap: Data: 0.00MB + Index: 0.00MB
wp_w3tc_cdn_queue: Data: 0.00MB + Index: 0.00MB
wp_wangguardcronjobs: Data: 0.00MB + Index: 0.00MB
wp_wangguardquestions: Data: 0.00MB + Index: 0.00MB
wp_wangguardreportqueue: Data: 0.00MB + Index: 0.00MB
wp_wangguardsignupsstatus: Data: 0.00MB + Index: 0.00MB
wp_wangguarduserstatus: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_bundled_itemmeta: Data: 0.01MB + Index: 0.02MB
wp_woocommerce_bundled_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 0.87MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.00MB + Index: 0.00MB
wp_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

acf: 6
acf-field: 74
acf-field-group: 16
attachment: 723
aw_workflow: 11
follow_up_email: 1
forum: 15
mc4wp-form: 1
nav_menu_item: 59
page: 41
payment_retry: 2984
post: 5
ppm-testimonial: 177
product: 27
product_variation: 12
qa_faqs: 10
reply: 64
revision: 107
scheduled-action: 7648
shop_coupon: 46
shop_order: 98467
shop_order_refund: 2463
shop_subscription: 6895
themedia: 61
topic: 46
tribe_events: 19
tribe_venue: 1
wc_order_email: 2
wc_order_status: 21
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

W3 Total Cache: by Frederick Townes – 0.9.6
WooCommerce: by Automattic – 3.3.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1-2)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-4 (rated-4-2)
rated-5 (rated-5)

### WC Pages ###

Shop base: #90 - /shop/
Cart: #91 - /shop/cart/
Checkout: #92 - /shop/checkout/
My account: #93 - /shop/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by nuclearape** [comment]
This might be helpful: some image sizing numbers get appended to the URL which seem to throw it off:

i.e .../.../image-250x166.jpg doesn't exist but .../.../image.jpg does.

**Comment by mikejolley** [comment]
@nuclearape can you try seeing if this resolves? https://github.com/woocommerce/woocommerce/pull/18850

**Comment by nuclearape** [comment]
@mikejolley unfortunately that hasn't resolved it

**Comment by mikejolley** [comment]
Ok; it's CDN specific but related to https://github.com/woocommerce/woocommerce/issues/18842. @kloon is working on it.

**Comment by JulienMelissas** [comment]
Hey there! I was hoping the fix in the PR #18850 was going to work, but it's not working for me currently using the [this plugin]. Would it be possible to re-open this issue, or would you like me to create a new one?

I did want to make one request: I dug around for 3 or so hours searching to see if I was going crazy with the images issues, to see if someone else was having similar issues with using an external CDN/solution, until I finally decided to look also at already closed issues. Are issues to be closed even if they're not actually approved or merged into a release? This might not be how the WC team runs their GitHub repository, but all of the OS projects I've been a part of using a similar flow don't close issues until they're actually fixed.

**Comment by mikejolley** [comment]
@JulienMelissas We'd prefer you reply to the PR whilst it's open to avoid 2 separate threads of discussion, like this.

**Comment by nuclearape** [comment]
Sorry, just a little confused - I said that the fix in #18850  **did not work** for me but this issue is now closed... Has this issue been addressed elsewhere? Is there another thread I should be following?

**Comment by mikejolley** [comment]
@nuclearape That PR has had further code changes since you last looked. Go reply there/test the latest code. We're checking with w3 total cache and s3.

**Comment by JulienMelissas** [comment]
Just want to check in and say I was finally able to migrate all of our sites to 3.3.3 and everything's working great. Cheers to the dev team for the fixes on this one.
