### ISSUE TITLE
Price mismatch in JSON-LD data due to tax

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#18852]
If **Display prices in the shop** is set to *Including tax*, then the price shown on the page vs what is shown in the JSON-LD data differs:

![](http://cld.wthms.co/g4K69M+)
Image Link: http://cld.wthms.co/g4K69M

![](http://cld.wthms.co/9534Tw+)
Image Link: http://cld.wthms.co/9534Tw

Presently, [Offer](http://schema.org/Offer) is being used, which has the [priceSpecification](http://schema.org/PriceSpecification) property under it that does have the option to flag if this price has tax included or not with [valueAddedTaxIncluded](http://schema.org/PriceSpecification). 

This came up in 929934-zen where the customer is using [Google Product Feed](https://woocommerce.com/products/google-product-feed/) and is getting errors from Google: 

> Temporary item disapprovals due to incorrect prices

Confirmed on WC 3.3.1 with only WC running on TwentySeventeen. 

## Steps to reproduce the issue

1. Set your store to use tax, and make sure you have tax rates set up.
1. Set **Display prices in the shop** to *Including tax*.
1. View the product, then view the JSON-LD for it.

**Comment by fuchsws** [comment]
suggested workaround using "woocommerce_structured_data_product_offer" filter:

```
// filter structured data price to match tax settings
function filter_woocommerce_structured_data_product_offer( $markup_offer, $product ) {
    $markup_offer['price'] = wc_get_price_to_display( $product );
    return $markup_offer;
};
add_filter( 'woocommerce_structured_data_product_offer', 'filter_woocommerce_structured_data_product_offer', 10, 2 );
```

**Comment by nishitlangaliya** [comment]
Fixes - adding c_get_price_to_display( $product ) into class file worked for me. Please check for the same and let me know if any changes required pull request done https://github.com/woocommerce/woocommerce/pull/18854
Thanks.

**Comment by mikejolley** [comment]
The main problem with using `wc_get_price_to_display` is that it shows taxes based on the visitor. So if say the visitor is geolocated outside of the base country, the taxes will be removed.

I presume Google would prefer a static value so the `valueAddedTaxIncluded` flag may be better.

@leewillis77 any thoughts on this one?

**Comment by leewillis77** [comment]
It's a tricky one.

Google uses this data for a bunch of different stuff (rich search engine results / validating feed pricing), fetch it from a bunch of locations which aren't guaranteed to be fixed (may fetch from Dublin one day, America the next etc.), and process / interpret it in a bunch of ways which are completely black-box as far as we're concerned (same issue we have trying to "guess" how they want variable products marked up) 

From the Google Merchant Centre perspective this is the first time I've seen this crop up - so I assume it's due (in part) to a non-standard setup. Is it when prices are set up *excluding* tax, but displayed *inc* tax? or do we get the same issue if the prices are set up and displayed including tax?

There's no clear documentation on this, but I think the most sensible thing is to present a fixed value (ie not vary by country), and to clearly indicate whether the price includes tax or not.

I don't have a concrete opinion on whether the value should always be inc tax, always ex tax - or whether it should follow the store display settings. The latter seems sensible to me, but I have no knowledge of whether that's what Google expects. 

If we can do it in such a way that users can override whether the schema price includes / excludes tax (via a filter?) then that probably gives us the most flexible solution

**Comment by mikejolley** [comment]
Added the prop in https://github.com/woocommerce/woocommerce/pull/19091

**Comment by theimaginaire** [comment]
Hi, we only sell products in the UK and we are still having shopping ads disapproved due to price mismatching which I can only put down to the fact that the price we're submitting to Google includes VAT, whereas the schema markup shows the price excluding VAT. Is there any way to hook into this function so we can produce the schema so that it includes VAT and matches with Google Shopping?

**Comment by thelar** [comment]
> Hi, we only sell products in the UK and we are still having shopping ads disapproved due to price mismatching which I can only put down to the fact that the price we're submitting to Google includes VAT, whereas the schema markup shows the price excluding VAT. Is there any way to hook into this function so we can produce the schema so that it includes VAT and matches with Google Shopping?

@theimaginaire did you find any way around this issue, I'm getting the same problem on my products, the merchant feed price is inclusive of VAT, but the structured data on the page is without. However I do note that on my structured data, the valueAddedTaxIncluded is set to http://schema.org/False - https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2F4x4tyres.co.uk%2Fproduct%2F15-x-7-tuff-torque-modular-steel-black-et0%2F

**Comment by theimaginaire** [comment]
> > Hi, we only sell products in the UK and we are still having shopping ads disapproved due to price mismatching which I can only put down to the fact that the price we're submitting to Google includes VAT, whereas the schema markup shows the price excluding VAT. Is there any way to hook into this function so we can produce the schema so that it includes VAT and matches with Google Shopping?
> 
> @theimaginaire did you find any way around this issue, I'm getting the same problem on my products, the merchant feed price is inclusive of VAT, but the structured data on the page is without. However I do note that on my structured data, the valueAddedTaxIncluded is set to http://schema.org/False - https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2F4x4tyres.co.uk%2Fproduct%2F15-x-7-tuff-torque-modular-steel-black-et0%2F

Not a good solution at all, but we just ended up removing the structured data entirely as we couldn't get it working. The below code does that if you wanted to use it:

`remove_action( 'wp_footer', array( WC()->structured_data, 'output_structured_data' ), 10 );`

Let me know if you ever find a better solution though, would be nice to have the structured data and surprised WC don't have the functionality to check the tax option and adjust their output accordingly.

**Comment by leewillis77** [comment]
@theimaginaire @thelar 

Unfortunately Google's documentation about what they expect is sketchy at best, and inconsistently applied from what we've seen.

I'm currently looking (in the [Google Product Feed](https://woocommerce.com/products/google-product-feed/) extension at what we can do to improve the structured data with a view to addressing some of these issues (as well as improving general search visibility). If you're customers of that extension, feel free to open a support ticket and we can share thoughts / test releases if that's helpful.

**Comment by mmc501** [comment]
> > > Hi, we only sell products in the UK and we are still having shopping ads disapproved due to price mismatching which I can only put down to the fact that the price we're submitting to Google includes VAT, whereas the schema markup shows the price excluding VAT. Is there any way to hook into this function so we can produce the schema so that it includes VAT and matches with Google Shopping?
> > 
> > 
> > @theimaginaire did you find any way around this issue, I'm getting the same problem on my products, the merchant feed price is inclusive of VAT, but the structured data on the page is without. However I do note that on my structured data, the valueAddedTaxIncluded is set to http://schema.org/False - https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2F4x4tyres.co.uk%2Fproduct%2F15-x-7-tuff-torque-modular-steel-black-et0%2F
> 
> Not a good solution at all, but we just ended up removing the structured data entirely as we couldn't get it working. The below code does that if you wanted to use it:
> 
> `remove_action( 'wp_footer', array( WC()->structured_data, 'output_structured_data' ), 10 );`
> 
> Let me know if you ever find a better solution though, would be nice to have the structured data and surprised WC don't have the functionality to check the tax option and adjust their output accordingly.

I've just come across this issue as last week - with the price mismatch relating to the structured data displaying prices without VAT - following on in interest of a better solution

**Comment by Cherrerotinoco** [comment]
Hi guys!, a bit late to join this issue, but I found a solution for this. 

I was trying to follow this solution in my project but I tried in many ways and it didn't work for me. The product price still appears without taxes to Google Bots.

> suggested workaround using "woocommerce_structured_data_product_offer" filter:
> 
> ```
> // filter structured data price to match tax settings
> function filter_woocommerce_structured_data_product_offer( $markup_offer, $product ) {
>     $markup_offer['price'] = wc_get_price_to_display( $product );
>     return $markup_offer;
> };
> add_filter( 'woocommerce_structured_data_product_offer', 'filter_woocommerce_structured_data_product_offer', 10, 2 );
> ```

**Finally I decided to calculate manually the tax** applied to the product because I think **woocommerce functions may not works for Google Bots**. Below i leave you the function that im using. May can help others in the future.

`
function priceWithTaxesSEO( $markup, $product ) {
    if ( is_product() ) {
		$precioConIVA = (float)$markup['offers'][0]['price'] + ( (float)$markup['offers'][0]['price'] * 0.21 );
		$precioConIVA = number_format($precioConIVA, 2, '.', '');
		
		$markup['offers'][0]['price'] = $precioConIVA;
		$markup['offers'][0]['priceSpecification']['price'] = $precioConIVA;
		// Especifica si el impuesto al valor agregado (IVA) aplicable está incluido en la especificación de precio o no.
		$markup['offers'][0]['priceSpecification']['valueAddedTaxIncluded'] = 'true';
    }

    return $markup;
}
add_filter( 'woocommerce_structured_data_product', 'priceWithTaxesSEO', 100, 2 );
`

Regards!

**Comment by drenina** [comment]
@Cherrerotinoco Is there any easier way to solve this, maybe with `wc_get_price_including_tax`?

**Comment by Cherrerotinoco** [comment]
Absolutly yess @drenina, but in my case It doesn't return the price with taxes because we have different taxes for each country and for EEUU is 0% and we wanted to show in shchema the 21% always. (I didn't mentioned before)

**Comment by BasicMr** [comment]
> Hi guys!, a bit late to join this issue, but I found a solution for this.
> 
> I was trying to follow this solution in my project but I tried in many ways and it didn't work for me. The product price still appears without taxes to Google Bots.
> 
> > suggested workaround using "woocommerce_structured_data_product_offer" filter:
> > ```
> > // filter structured data price to match tax settings
> > function filter_woocommerce_structured_data_product_offer( $markup_offer, $product ) {
> >     $markup_offer['price'] = wc_get_price_to_display( $product );
> >     return $markup_offer;
> > };
> > add_filter( 'woocommerce_structured_data_product_offer', 'filter_woocommerce_structured_data_product_offer', 10, 2 );
> > ```
> 
> **Finally I decided to calculate manually the tax** applied to the product because I think **woocommerce functions may not works for Google Bots**. Below i leave you the function that im using. May can help others in the future.
> 
> ```
> function priceWithTaxesSEO( $markup, $product ) {
>     if ( is_product() ) {
> 		$precioConIVA = (float)$markup['offers'][0]['price'] + ( (float)$markup['offers'][0]['price'] * 0.21 );
> 		$precioConIVA = number_format($precioConIVA, 2, '.', '');
> 		
> 		$markup['offers'][0]['price'] = $precioConIVA;
> 		$markup['offers'][0]['priceSpecification']['price'] = $precioConIVA;
> 		// Especifica si el impuesto al valor agregado (IVA) aplicable está incluido en la especificación de precio o no.
> 		$markup['offers'][0]['priceSpecification']['valueAddedTaxIncluded'] = 'true';
>     }
> 
>     return $markup;
> }
> add_filter( 'woocommerce_structured_data_product', 'priceWithTaxesSEO', 100, 2 );
> ```
> 
> Regards!

@Cherrerotinoco We have 3 VAT values. 21, 9 and 0.
Can you please adjust this code for these 3 VAT values?

Thank you!

**Comment by terranovacnc** [comment]
> 
> 
> Hi guys!, a bit late to join this issue, but I found a solution for this.
> 
> I was trying to follow this solution in my project but I tried in many ways and it didn't work for me. The product price still appears without taxes to Google Bots.
> 
> > suggested workaround using "woocommerce_structured_data_product_offer" filter:
> > ```
> > // filter structured data price to match tax settings
> > function filter_woocommerce_structured_data_product_offer( $markup_offer, $product ) {
> >     $markup_offer['price'] = wc_get_price_to_display( $product );
> >     return $markup_offer;
> > };
> > add_filter( 'woocommerce_structured_data_product_offer', 'filter_woocommerce_structured_data_product_offer', 10, 2 );
> > ```
> 
> **Finally I decided to calculate manually the tax** applied to the product because I think **woocommerce functions may not works for Google Bots**. Below i leave you the function that im using. May can help others in the future.
> 
> ```
> function priceWithTaxesSEO( $markup, $product ) {
>     if ( is_product() ) {
> 		$precioConIVA = (float)$markup['offers'][0]['price'] + ( (float)$markup['offers'][0]['price'] * 0.21 );
> 		$precioConIVA = number_format($precioConIVA, 2, '.', '');
> 		
> 		$markup['offers'][0]['price'] = $precioConIVA;
> 		$markup['offers'][0]['priceSpecification']['price'] = $precioConIVA;
> 		// Especifica si el impuesto al valor agregado (IVA) aplicable está incluido en la especificación de precio o no.
> 		$markup['offers'][0]['priceSpecification']['valueAddedTaxIncluded'] = 'true';
>     }
> 
>     return $markup;
> }
> add_filter( 'woocommerce_structured_data_product', 'priceWithTaxesSEO', 100, 2 );
> ```
> 
> Regards!

I tested this code with variable products, lowPrice and highPrice are without taxes, any help on this?

**Comment by kolibri27** [comment]
The function priceWithTaxesSEO doesn't work for me any longer either.

**Comment by Cherrerotinoco** [comment]
@kolibri27 make sure there is not another plugin overriding your function.

The hook "woocommerce_structured_data_product" is the default Woocommerce data structure. If you use YoastSEO or similar, make sure the plugin don't modify your data.

Also take care on the $mark object and variables, modify the function as your needs.

**Comment by kolibri27** [comment]
> @kolibri27 make sure there is not another plugin overriding your function.
> 
> The hook "woocommerce_structured_data_product" is the default Woocommerce data structure. If you use YoastSEO or similar, make sure the plugin don't modify your data.
> 
> Also take care on the $mark object and variables, modify the function as your needs.

You are right. Issue solved. Thx.

**Comment by ignacio-fm** [comment]
> Cherrerotinoco

Eres mi dios. Muchas gracias por tu código, me has ahorrado mucho trabajo... ♥️
