### ISSUE TITLE
[3.3.1]: Products Search by SKU can't be performed in WP Admin 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#18861]
It appears that after updating to version 3.3.1, Products Search by SKU can't be performed in WP Admin. 

**SCREENCAST WITH 3.2.6:**

http://g.recordit.co/3NYWMUIHbD.gif

**SCREENCAST WITH 3.3.1:**

http://g.recordit.co/AeDid5jOYh.gif

**Comment by GlennMartin1** [comment]
That's a known issue, set for correcting in 3.3.2.

See https://github.com/woocommerce/woocommerce/pull/18843
