### ISSUE TITLE
Checkout Button Missing

### ISSUE THREAD

**Issue by JMIANO1981** [woocommerce/woocommerce#18865]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. After the update, the checkout button becomes missing.
2. I rollback the update and still the checkout button still missing.
3. I update the theme and still the woocommerce plugin have issue with checkout button and the photo of the item on the right side also missing.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by WPprodigy** [comment]
Need more information, much more information. Please fill out everything in the issue templates, such as your system status report, and whether or not this happens when only WooCommerce is active, along with a default theme.

We can re-open this issue once you've given enough info to show there is a bug.

**Comment by JMIANO1981** [comment]
Hello Woocommerce,

I attach herewith the screenshot of our checkout with no button.

Also, here is the link to our website.
http://www.sabangseaferrympc.com/wp/    (Home)
http://www.sabangseaferrympc.com/wp/checkout-woo-booking/   (Checkout)

I hope that you could give me some inputs how to fix this woocommerce no
button issue at the checkout.

Thank you.


[image: photo]
Jonathan Miano, Jr
Website Developer | IT Consultancy | General VA at  JMIANO-VA
A  167 (B) 5th Ave. Riverside Village, Pasig City, Philippines
P  (+63947) 388 0650  <(+63947) 388 0650>
M  (+63927) 853 6199  <(+63927) 853 6199>
E  JBMJR243@gmail.com  <JBMJR243@gmail.com>
W  www.jmiano-va.com  <http://www.jmiano-va.com>
Skype JBMJR243@gmail.com <#>
<http://www.facebook.com/JMIANO243>
<http://www.linkedin.com/in/jonathan-jr-miano-95330158/>
<http://twitter.com/jmianojr>

Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy.
Create your own email signature
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

**Comment by JMIANO1981** [comment]
You Ask me for this...

"Need more information, much more information. Please fill out everything
in the issue templates, such as your system status report, and whether or
not this happens when only WooCommerce is active, along with a default
theme.

We can re-open this issue once you've given enough info to show there is a
bug"


And I give you what you want, and then you are telling me this is not the
place to ask support?  Seriously...? then why you need more information and
about the bugs and etc and yet, this is not the place to ask for support?
Isn't it a plain stupidity? Sorry, because I can't digest what you are
trying to drive for this.

Why not in the first place that told me to go to Github for the woocommerce
support and why you bother me to ask questions which NO LONGER NEEDED?

It sounds weird tho.

So sad but you don't help me with this issues.


[image: photo]
Jonathan Miano, Jr
Website Developer | IT Consultancy | General VA at  JMIANO-VA
A  167 (B) 5th Ave. Riverside Village, Pasig City, Philippines
P  (+63947) 388 0650  <(+63947) 388 0650>
M  (+63927) 853 6199  <(+63927) 853 6199>
E  JBMJR243@gmail.com  <JBMJR243@gmail.com>
W  www.jmiano-va.com  <http://www.jmiano-va.com>
Skype JBMJR243@gmail.com <#>
<http://www.facebook.com/JMIANO243>
<http://www.linkedin.com/in/jonathan-jr-miano-95330158/>
<http://twitter.com/jmianojr>

Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy.
Create your own email signature
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

**Comment by WPprodigy** [comment]
> Please fill out everything in the issue templates, such as your system status report, and whether or not this happens when only WooCommerce is active, along with a default theme.

You did not fill out the full issues template: http://cld.wthms.co/Lq8mpW

**Comment by JMIANO1981** [comment]
You didn't give that link to your first reply... isn't it weird...?


[image: photo]
Jonathan Miano, Jr
Website Developer | IT Consultancy | General VA at  JMIANO-VA
A  167 (B) 5th Ave. Riverside Village, Pasig City, Philippines
P  (+63947) 388 0650  <(+63947) 388 0650>
M  (+63927) 853 6199  <(+63927) 853 6199>
E  JBMJR243@gmail.com  <JBMJR243@gmail.com>
W  www.jmiano-va.com  <http://www.jmiano-va.com>
Skype JBMJR243@gmail.com <#>
<http://www.facebook.com/JMIANO243>
<http://www.linkedin.com/in/jonathan-jr-miano-95330158/>
<http://twitter.com/jmianojr>

Please consider your environmental responsibility. Before printing this
e-mail message, ask yourself whether you really need a hard copy.
Create your own email signature
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

**Comment by WPprodigy** [comment]
> Please fill out everything in the issue templates

>  [..] and whether or not this happens when only WooCommerce is active, along with a default theme.

**Comment by JMIANO1981** [comment]
Now I check all information needed. I think you will now give some ideas or fix the bug for this.

**Comment by WPprodigy** [comment]
Checking the boxes does nothing, did you do what they say? These two in particular: http://cld.wthms.co/zkb6Gy ?

To clarify, you:

1) Disabled all plugins except for the WooCommerce plugins.
2) Switched to a default WordPress theme.
3) And after the above two, the issue still occurred?

**Comment by kloon** [comment]
@JMIANO1981 please include a systems status report and follow the steps as @WPprodigy mentioned. There is not much we can do to help you fix this if we do not have the right information to work with.

The issue is most likely with your theme which overrides core WooCommerce templates, so please following the advice about disabling all plugins except WooCommerce and switching to a default theme like Storefront or Twentyseventeen.
