### ISSUE TITLE
Coupons not working

### ISSUE THREAD

**Issue by JWDSN** [woocommerce/woocommerce#18866]
Coupons are not working since update 3.3.1.

Error: Sorry, this coupon is not applicable to selected products.

Using SSHOP theme which might be outdated but I did a manual replacement of templates.  

Tried creating 2 coupons: percentage discount (test11) and fixed product coupon (hebeta50) for a single product, amounts vary, expiry date is set, see images for restrictions for 'test11' code, neither work with the same error message.

![woo_coupon1](https://user-images.githubusercontent.com/36123811/35958598-895e4ec8-0cf1-11e8-94ab-3d2b89a173cc.png)
![woo_coupon2](https://user-images.githubusercontent.com/36123811/35958600-8c084f2a-0cf1-11e8-92fe-5f3c84b6b78c.png)

If you would like to try for yourself go to [this site](https://www.jwdsn.net) and click on the image offer.

Use hebeta50 or test11 code.

Let me know if you need more info.
`
### WordPress Environment ###

Home URL: https://jwdsn.net/assets
Site URL: https://jwdsn.net/assets
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.27
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.1
WC Database Prefix: wpzv_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 3.56MB
Database Data Size: 3.06MB
Database Index Size: 0.50MB
wpzv_woocommerce_sessions: Data: 1.38MB + Index: 0.06MB
wpzv_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB
wpzv_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.02MB
wpzv_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wpzv_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpzv_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpzv_commentmeta: Data: 0.00MB + Index: 0.00MB
wpzv_comments: Data: 0.00MB + Index: 0.01MB
wpzv_links: Data: 0.00MB + Index: 0.00MB
wpzv_loginizer_logs: Data: 0.00MB + Index: 0.01MB
wpzv_options: Data: 0.93MB + Index: 0.13MB
wpzv_postmeta: Data: 0.36MB + Index: 0.12MB
wpzv_posts: Data: 0.29MB + Index: 0.04MB
wpzv_termmeta: Data: 0.00MB + Index: 0.01MB
wpzv_terms: Data: 0.00MB + Index: 0.01MB
wpzv_term_relationships: Data: 0.00MB + Index: 0.01MB
wpzv_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wpzv_usermeta: Data: 0.04MB + Index: 0.03MB
wpzv_users: Data: 0.00MB + Index: 0.01MB
wpzv_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpzv_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpzv_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wpzv_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 115
custom_css: 1
customize_changeset: 49
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 18
page: 11
post: 2
product: 13
revision: 34
sa_slider: 1
shop_coupon: 3
shop_order: 28
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Age Verify: by Chase Wiseman – 0.3.0
Akismet Anti-Spam: by Automattic – 4.0.2
Contact Form 7: by Takayuki Miyoshi – 5.0
Jetpack by WordPress.com: by Automattic – 5.8
Loginizer: by Raj Kothari – 1.3.8
MailChimp for WordPress: by ibericode – 4.1.15
Perfect WooCommerce Brands: by Alberto de Vera Sevilla – 1.6.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Slide Anything - Responsive Content / HTML Slider and Carousel: by Simon Edge – 2.1.2
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.1
WooCommerce Services: by Automattic – 1.11.0
WooCommerce: by Automattic – 3.3.1
YITH WooCommerce Wishlist: by YITHEMES – 2.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #28 - /shop/
Cart: #29 - /cart/
Checkout: #30 - /checkout/
My account: #31 - /my-account/
Terms and conditions: #69 - /eula/

### Theme ###

Name: SShop
Version: 1.1.0
Author URL: http://sshopwp.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: sshop/woocommerce/content-product.php
sshop/woocommerce/loop/add-to-cart.php
sshop/woocommerce/loop/loop-end.php
sshop/woocommerce/loop/loop-start.php
sshop/woocommerce/loop/pagination.php
sshop/woocommerce/single-product/tabs/additional-information.php
sshop/woocommerce/single-product/tabs/description.php

`

**Comment by WPprodigy** [comment]
What are your coupons settings? Any restrictions?

Need more information, as coupons are working for me.

**Comment by JWDSN** [comment]
Updated previous comment.

**Comment by WPprodigy** [comment]
For the restricted product, could you confirm it is for product ID 76? And then I'm assuming this error doesn't occur if you remove the restriction?

I tested this on another site but couldn't replicate. Follow this guide to rule out plugin and theme conflicts: https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4

**Comment by JWDSN** [comment]
Found the issue - seems to be a conflict with Perfect WooCommerce Brands (not even sure what this does). Deactivated and works fine now. 

Thanks for your advice. I'll let you close the issue if you don't want to inquire further.

**Comment by WPprodigy** [comment]
My guess is the brands extension is trying to implement it's own coupon logic, but messed up.

Thanks for reporting back :)
