### ISSUE TITLE
How to update stock of product after variation product was order?

### ISSUE THREAD

**Issue by vanloc0301** [woocommerce/woocommerce#18872]
WC: 3.3.1

I have a product:

iPhone 6s have 3 variation: 32gb(5 product), 64gb(40 product) and 128gb(15 product).

Each variation product has number product in Stock.

iPhone 6s have total: 5 + 40 + 15 = 60 products.

When my customer order any item in variation product(Ex: buy 6 item iPhone 6s version 64gb). It auto reduces this stock of variation (the number of iPhone 6s 64gb only have 4 product in Stock).

How to update the stock of product (iPhone 6s stocks: 60 - 4 = 56 products).

**Comment by WPprodigy** [comment]
If stock is managed at the variation level, then it shouldn't be managed at the product level. Should use one or the other, not both.

**Comment by vanloc0301** [comment]
Can you explain why?

My customer does not agree with this. I tried to explain the reason. 

Like your comment, my customer must type manually the number of the product and manually the number of variables in Stock.

**Comment by mikejolley** [comment]
If your variations all share a single level of stock, define at product level, not a variation level.

If each variation has it's own stock, define at variation level, not a product level.

The two options conflict. How would WC know which amount to reduce otherwise? That is the reason.
