### ISSUE TITLE
Woocommerce API Filter

### ISSUE THREAD

**Issue by Himanshu041** [woocommerce/woocommerce#18871]
Earlier, I am using legacy API which offers various filters and as the legacy API is deprecated.
I am curious to know whether those filters or alternative of those filters were embedded in v2.
because I didn't find any doc related to filters on v2.

**Comment by mikejolley** [comment]
Unlikely - the legacy and new APIs should be treated as two separate things. The new API already has many filters since it extends the WP Rest API. Some of the documentation for WP Rest API will apply to our endpoints.

Thanks
