### ISSUE TITLE
Zoom on Hover not working for Touch Enabled Laptops

### ISSUE THREAD

**Issue by digamber89** [woocommerce/woocommerce#18873]
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ X] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Open the single products page on a touch enabled laptop
2. Hovering over the image does not zoom
3. Clicking the image zooms

## Expected/actual behavior

When I follow those steps, I see that the Zoom option only enables if we click on it.
On closes inspection i see on single-product.js
```
if ( zoomEnabled ) {
			var zoom_options = $.extend( {
				touch: false
			}, wc_single_product_params.zoom_options );

			if ( 'ontouchstart' in window ) {
				zoom_options.on = 'click';
			}

			zoomTarget.trigger( 'zoom.destroy' );
			zoomTarget.zoom( zoom_options );
		}
```
due to the 'ontouchstart' in window option being true, the zoom option only works on "click".
I was expecting to see, the zoom effect on hover as this is a Laptop and not a Mobile Device such as an ipad or iphone.

## Isolating the problem

- [ X] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
We disable this because it's mostly there for mobile optimisation. Touch (on mobile) interferes with scroll. For that reason I don't want to interfere with this off by default. If you feel strongly about it you can filter the `woocommerce_single_product_zoom_options` hook and set it to true for your store.

Thanks

**Comment by codingsuccessfully** [comment]
the solution is:
Please comment the next part of the code and it works as you want: 

/*		if ( 'ontouchstart' in window ) {
				zoom_options.on = 'click';
			}*/
