### ISSUE TITLE
Issue in attribute term import via woocommerce Legacy API 

### ISSUE THREAD

**Issue by Himanshu041** [woocommerce/woocommerce#18874]
Hi,

When I imported a product via legacy API.
 I find out that  API sending slug of that attribute term instead of name.
![screenshot 2](https://user-images.githubusercontent.com/36257344/35961093-63d3ba86-0cd2-11e8-914b-5b24e8caefb8.png)
![screenshot 3](https://user-images.githubusercontent.com/36257344/35961098-6ab2a3da-0cd2-11e8-8712-05044032079b.png)
The response to API request for that product was pasted below.
I only pasted variation part.Please have a look at attributes key of variations.

u'variations': [{
u'weight': None, 
u'regular_price': u'', 
u'image': [{u'src': u'http://localhost/woocommerce_bundle/wp-content/plugins/woocommerce/assets/images/placeholder.png', 
            u'title': u'Placeholder', 
            u'created_at': u'2018-02-08T07:39:24Z', 
            u'updated_at': u'2018-02-08T07:39:24Z', 
            u'position': 0, u'alt': u'Placeholder', u'id': 0}], 
u'updated_at': u'2018-02-08T07:36:44Z', 
u'visible': False, 
u'id': 477, 
u'sku': u'', 
u'dimensions': {u'width': u'', u'length': u'', u'unit': u'cm', u'height': u''}, 
u'shipping_class_id': None, 
u'download_limit': -1, 
u'on_sale': False, u'virtual': False, 
u'downloadable': False, 
u'backordered': False, 
u'stock_quantity': None, 
u'sale_price': None, 
u'downloads': [], 
u'price': u'', 
u'shipping_class': u'', 
u'purchaseable': False, 
u'in_stock': True, 
u'taxable': True, 
u'permalink': u'http://localhost/woocommerce_bundle/product/test-product/?attribute_pa_dimension=30-x-40', 
u'managing_stock': False, 
u'created_at': u'2018-02-08T07:36:44Z', 
u'tax_class': u'', 
u'download_expiry': -1, 
u'backorders_allowed': False, 
u'tax_status': u'taxable', 
**u'attributes': [{u'name': u'Dimension', u'option': u'30-x-40', u'slug': u'dimension'}]},** 
{u'weight': None, 
u'regular_price': u'', 
u'image': [{u'src': u'http://localhost/woocommerce_bundle/wp-content/plugins/woocommerce/assets/images/placeholder.png', 
            u'title': u'Placeholder', 
            u'created_at': u'2018-02-08T07:39:24Z', 
            u'updated_at': u'2018-02-08T07:39:24Z', 
            u'position': 0, u'alt': u'Placeholder', u'id': 0}], 
u'updated_at': u'2018-02-08T07:36:46Z', 
u'visible': False, 
u'id': 478, 
u'sku': u'', 
u'dimensions': {u'width': u'', u'length': u'', u'unit': u'cm', u'height': u''}, 
u'shipping_class_id': None, 
u'download_limit': -1, 
u'on_sale': False, 
u'virtual': False, 
u'downloadable': False, 
u'backordered': False, 
u'stock_quantity': None, 
u'sale_price': None, 
u'downloads': [], 
u'price': u'', 
u'shipping_class': u'', 
u'purchaseable': False, 
u'in_stock': True, 
u'taxable': True, 
u'permalink': u'http://localhost/woocommerce_bundle/product/test-product/?attribute_pa_dimension=40-x-40', 
u'managing_stock': False, 
u'created_at': u'2018-02-08T07:36:46Z', 
u'tax_class': u'', u'download_expiry': -1, 
u'backorders_allowed': False, 
u'tax_status': u'taxable', 
**u'attributes': [{u'name': u'Dimension', u'option': u'40-x-40', u'slug': u'dimension'}]}],**

**Comment by mikejolley** [comment]
The legacy API is no longer maintained and won't receive any further changes. You'll need to switch to the new API which does support names.
