### ISSUE TITLE
SKU search in admin not working

### ISSUE THREAD

**Issue by sosojni** [woocommerce/woocommerce#18875]
After i apply this change: https://github.com/woocommerce/woocommerce/commit/2321e8bdc134b7d29779444ef47cf99caf5f66c7#diff-2084a0519f9b476f718b42e49a51c66a i can not search by SKU in admin. When i revert only that par, SKU search is working again.

**Comment by sosojni** [comment]
Oh and by reverting this, i can search by main SKU, but in variable products, i can not search by variation SKU so i'm guessing ill need to revert further down the line.

**Comment by sosojni** [comment]
Yes, i need to rever this one too to be able to search by variable product SKU
https://github.com/woocommerce/woocommerce/commit/6047322c520ad9dcc0fdf320e764b4abb0408687#diff-2084a0519f9b476f718b42e49a51c66a

**Comment by sosojni** [comment]
Oh man....
Even with that last revert, it's still not working as it used to. Variable product search by SKU is working only if you type whole SKU. Not working if you type in partial SKU. If product is not variable one, than it's working fine.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/18757
https://github.com/woocommerce/woocommerce/pull/18843
