### ISSUE TITLE
WooCommerce/Product/Display disappear!

### ISSUE THREAD

**Issue by gchecchin** [woocommerce/woocommerce#18889]
After last update <b>Display</b> under WooCommerce/Product disappear!

I've also tried the link /wp-admin/admin.php?page=wc-settings&tab=products&section=display

I need to setup thumbnail size

I've just disable all plugin and reinstall Woocommerce. 

Wordpress Version 4.9.4
WooCommerce Version 3.3.1

![immagine](https://user-images.githubusercontent.com/28602939/35989662-0c8fce10-0d02-11e8-9b1a-a318965396ce.png)

**Comment by WPprodigy** [comment]
Can be found at Appearance > Customize > WooCommerce now.

Note that if your theme declares the image sizes, there won't be options to make changes. But you can adjust aspect ratios.

**Comment by gchecchin** [comment]
First I can edit Single Product Image and Archive Shop image size, now I can only set up 1 size for all. The worst upgrade in woocommerce

**Comment by WPprodigy** [comment]
What is it you need to do that you're not able to do now?

**Comment by gchecchin** [comment]
I want to edit Single Product Image that must be 640x640 and not with the aspect ratio 35:64. I need square photo (1:1) in single product image and 35:64 in thumbnail archive

**Comment by WPprodigy** [comment]
Single Product Image are uncropped by default. If you want a square photo there, maybe upload a square image :)

Else you can use this filter: https://github.com/woocommerce/woocommerce/blob/997e8aefde01e5cce027f207d5cea6b321cbb921/includes/wc-core-functions.php#L759

**Comment by gchecchin** [comment]
![immagine](https://user-images.githubusercontent.com/28602939/35998975-98b6dcd2-0d1e-11e8-97dd-50c216a287c5.png)

Look, this is kind of image that I need, with custom crop on archive and square image on single product.

I'll try the filter, thank you :) 

But I don't understan because woocommerce remove options instead of add...

**Comment by WPprodigy** [comment]
Displaying a cropped down version of the image on the single product page does seems a bit strange, no? Don't you want them to see the product in full detail there?

And then the previous options did more harm than good. Changing them often did nothing due to theme settings and styles.

**Comment by gchecchin** [comment]
![immagine](https://user-images.githubusercontent.com/28602939/35999402-ffe09e7e-0d1f-11e8-84eb-60a90471aa7b.png)

No for my necessarity i need square and long images. In this (up) image I want to crop in square for single product and keep long for archive, in pants image i want long in archive and square with white border on single page.

![immagine](https://user-images.githubusercontent.com/28602939/35999551-7b4b3dbc-0d20-11e8-9150-753c435f56a7.png)
Here I can edit "Single Product Image" because is a thumb too

**Comment by MyChiMan** [comment]
> Can be found at Appearance > Customize > WooCommerce now.
> 
> Note that if your theme declares the image sizes, there won't be options to make changes. But you can adjust aspect ratios.

Thank you so much, you do not know how long I was looking for that setting.
