### ISSUE TITLE
order_by_popularity_post_clauses filter not removed after shortcode used

### ISSUE THREAD

**Issue by todeveni** [woocommerce/woocommerce#18881]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use `[product orderby="popularity"]` shortcode
2. Use `WP_Query()` after that
3. See request failing

## Expected/actual behavior

When I follow those steps, I see...
an SQL error `Unknown column 'wp_postmeta.meta_value' in 'order clause'`

I was expecting to see...
Working `WP_Query()`

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

I guess it has something to do with `order_by_popularity_post_clauses` filter in [woocommerce/includes/class-wc-query.php#L570](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-query.php#L570) and filter not removed after running shortcode.

Reproducing code:
```php
do_shortcode( '[products limit="1" orderby="popularity"]' );

$the_query = new WP_Query( [
	'post_type' => 'post',
] );
```

**Comment by todeveni** [comment]
Oh and 3.2.5 is/was working fine.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18883

**Comment by todeveni** [comment]
Confirmed working, thanks for super quick response 👍
