### ISSUE TITLE
Admin SKU search by Variable product variations

### ISSUE THREAD

**Issue by justinmz** [woocommerce/woocommerce#18882]
We've added the following https://github.com/woocommerce/woocommerce/pull/18843/files to enable SKU searches in the admin area again until 3.3.2 is released.

Variable products however still does not show in search results when searching by SKU of one of the variations. 

Wordpress version 4.9.4 and Woocommerce version 3.3.1

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18880
