### ISSUE TITLE
Returning products which do not have a category

### ISSUE THREAD

**Issue by serialbandicoot** [woocommerce/woocommerce#18884]
Hi, I'm trying to us version: 'wc/v2' api to return products by category. This is fine if I want to call category first and then filter through category. However uncategorised products are not picked up.

Is there a way of getting these uncategorised products only? 

thanks...

**Comment by mikejolley** [comment]
As of 3.3, uncategorized has an actual category object. This will have an ID which can be used.

Thanks

**Comment by serialbandicoot** [comment]
Hi @mikejolley - I can't any docs on this one, can you please point me in the direction of them. thanks...

**Comment by mikejolley** [comment]
It's a new feature in 3.3 and I don't see a dedicated doc. It works like ant other category though. All products will have at least one category.
