### ISSUE TITLE
Woo 3.2.6 doesn't update status via API

### ISSUE THREAD

**Issue by andyknas** [woocommerce/woocommerce#18885]
Customer just updated website to latest version of Woo. Previous code which changed the order status no longer works. Response from PUT request comes back with previous status of on-hold. Post requests to add notes work fine.

![screen shot 2018-02-08 at 10 06 57 am](https://user-images.githubusercontent.com/1693058/35983700-2c4e09f0-0cb8-11e8-9edd-1237142c1b5c.png)
![screen shot 2018-02-08 at 10 07 05 am](https://user-images.githubusercontent.com/1693058/35983701-2c5cc81e-0cb8-11e8-9c90-dcde05d1f5bb.png)

**Comment by andyknas** [comment]
`
### WordPress Environment ###

Home URL: http://zzz.com
Site URL: http://zzz.com
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31-4+wpengine10
PHP Post Max Size: 100 MB
PHP Time Limit: 1200
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 225.24MB
Database Data Size: 147.14MB
Database Index Size: 78.10MB
wp_woocommerce_sessions: Data: 3.02MB + Index: 0.06MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 1.11MB + Index: 0.68MB
wp_woocommerce_order_itemmeta: Data: 7.61MB + Index: 5.61MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_bp_activity: Data: 0.80MB + Index: 0.93MB
wp_bp_activity_meta: Data: 0.03MB + Index: 0.01MB
wp_bp_friends: Data: 0.00MB + Index: 0.00MB
wp_bp_groups: Data: 0.00MB + Index: 0.00MB
wp_bp_groups_groupmeta: Data: 0.00MB + Index: 0.00MB
wp_bp_groups_members: Data: 0.00MB + Index: 0.00MB
wp_bp_messages_messages: Data: 0.00MB + Index: 0.00MB
wp_bp_messages_meta: Data: 0.00MB + Index: 0.01MB
wp_bp_messages_notices: Data: 0.00MB + Index: 0.00MB
wp_bp_messages_recipients: Data: 0.00MB + Index: 0.01MB
wp_bp_notifications: Data: 0.35MB + Index: 0.58MB
wp_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB
wp_bp_xprofile_data: Data: 0.04MB + Index: 0.05MB
wp_bp_xprofile_fields: Data: 0.00MB + Index: 0.01MB
wp_bp_xprofile_groups: Data: 0.00MB + Index: 0.00MB
wp_bp_xprofile_meta: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 1.52MB + Index: 0.53MB
wp_comments: Data: 5.52MB + Index: 6.02MB
wp_cptch_images: Data: 0.02MB + Index: 0.00MB
wp_cptch_packages: Data: 0.02MB + Index: 0.00MB
wp_cptch_whitelist: Data: 0.02MB + Index: 0.02MB
wp_cw_games: Data: 0.00MB + Index: 0.01MB
wp_cw_maps: Data: 0.00MB + Index: 0.00MB
wp_cw_matches: Data: 0.03MB + Index: 0.01MB
wp_cw_rounds: Data: 0.00MB + Index: 0.01MB
wp_cw_teams: Data: 0.00MB + Index: 0.00MB
wp_hctpc_images: Data: 0.02MB + Index: 0.00MB
wp_hctpc_packages: Data: 0.02MB + Index: 0.00MB
wp_hctpc_whitelist: Data: 0.02MB + Index: 0.02MB
wp_laybuy_response: Data: 0.02MB + Index: 0.00MB
wp_laybuy_revision_reports: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 2.52MB + Index: 0.14MB
wp_postmeta: Data: 65.58MB + Index: 42.09MB
wp_posts: Data: 38.53MB + Index: 4.92MB
wp_signups: Data: 0.00MB + Index: 0.01MB
wp_swp_testimonial: Data: 0.05MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.05MB + Index: 0.08MB
wp_term_relationships: Data: 0.05MB + Index: 0.11MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 16.52MB + Index: 14.92MB
wp_users: Data: 1.52MB + Index: 0.75MB
wp_user_countries: Data: 0.01MB + Index: 0.01MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_termmeta: Data: 0.00MB + Index: 0.01MB
wp_yoast_seo_links: Data: 1.48MB + Index: 0.23MB
wp_yoast_seo_meta: Data: 0.42MB + Index: 0.00MB

### Post Type Counts ###

attachment: 87
blackfyre: 2
bp-email: 16
forum: 17
nav_menu_item: 28
oembed_cache: 2874
optionsframework: 4
page: 37
popup: 1
popup_theme: 6
post: 1
product: 47
product_variation: 55
reply: 9718
revision: 2
shop_coupon: 44
shop_order: 7799
shop_order_refund: 5
topic: 427
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (36) ###

Accordion Shortcode: by CTLT – 1.2.1
Advanced Text Widget PRO: by Max Chirkov – 2.1.1
Akismet Anti-Spam: by Automattic – 4.0.2
bbPress: by The bbPress Community – 2.5.14
Blackfyre types: by Skywarrior themes – 1.5
BuddyPress: by The BuddyPress Community – 2.9.3
Captcha: by simplywordpress – 4.4.5
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.17
Contact Form 7: by Takayuki Miyoshi – 4.9.2
Delete Comments By Status: by Micro Solutions Bangladesh – 1.5.3
Display Widgets: by Strategy11 – 2.7
Disqus Comment System: by Disqus  – 2.87
DZS Video Gallery: by Digital Zoom Studio – 7.51
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 6.2.7
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.5
Popup Maker: by WP Popup Maker – 1.6.6
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.0.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Restricted To Adults: by Saguaro Digital – 0.9
WooCommerce Checkout Add-Ons: by SkyVerge – 1.11.0 – 1.12.0 is available – Not tested with the active version of WooCommerce
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.6 – 1.5.11 is available – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.2.8 – 1.3.0 is available – Not tested with the active version of WooCommerce
WooCommerce Conversion Tracking: by Tareq Hasan – 1.2.5
WooCommerce Dynamic Pricing: by Lucas Stark – 3.0.12 – 3.1.4 is available – Not tested with the active version of WooCommerce
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.7 – 4.4.11 is available – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce MailChimp: by Saint Systems – 2.1.6 – Not tested with the active version of WooCommerce
WooCommerce - NRGship: by RTD LLC – 3.1 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.2 – 1.12.0 is available – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooCommerce – 1.6.8 – 1.6.10 is available – Not tested with the active version of WooCommerce
WooCommerce Shipping Per Product v2: by WooThemes – 2.2.10 – 2.2.11 is available – Not tested with the active version of WooCommerce
WooCommerce UPS Shipping: by WooCommerce – 3.2.5 – 3.2.9 is available – Not tested with the active version of WooCommerce
WooCommerce USPS Shipping: by WooCommerce – 4.4.8 – 4.4.13 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.6 – 3.3.1 is available
Yoast SEO: by Team Yoast – 6.2
WP Testimonial Widget: by Stark Digital – 3.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4137 - /shop/
Cart: #71 - /cart/
Checkout: #72 - /checkout/
My account: #73 - /my-account/
Terms and conditions: #519 - /terms-and-conditions/

### Theme ###

Name: zzzz
Version: 1.0
Author URL: http://tractusonline.com
Child Theme: ✔
Parent Theme Name: BlackFyre
Parent Theme Version: 2.4
Parent Theme Author URL: http://www.skywarriorthemes.com/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: blackfyre/woocommerce/content-product.php
zzz/woocommerce/emails/admin-failed-order.php
zzz/woocommerce/emails/customer-on-hold-order.php
zzz/woocommerce/emails/plain/admin-new-order.php version - is out of date. The core version is 2.5.0

Outdated Templates: ❌Learn how to update
`

**Comment by mikejolley** [comment]
The ID was not needed in the request but I tested with it anyway to see if there is a problem.

![insomnia create product 2018-02-08 16-40-35](https://user-images.githubusercontent.com/90977/35985590-e2bf0cbc-0cee-11e8-823f-2e7667402d0e.png)

As you can see in my screenshot, the status was updated (from on hold in this case). You'll need to look at error logs and rule out extensions. It's possible something else is blocking the status change.

Clean installs don't have the issue from what I can tell.

Please go through the debugging steps listed on the 'new issue' form to narrow the problem down.

**Comment by andyknas** [comment]
Mike, did you test with 3.2.6 or current 3.3.1?

**Comment by mikejolley** [comment]
master/3.3.1
