### ISSUE TITLE
[3.3.1] Can't remove product from "Uncategorized" category when bulk editing

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce#18898]
When a new product is manually created, or imported, the "uncategorized" category is tied to the product by default. When you bulk edit products, you can't remove the "uncategorized" category which is not even ticked:

![](http://cld.wthms.co/qEobs5+)

![](http://cld.wthms.co/mJpeRf+)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a new product manually without setting up any category
2. Bulk edit the product and try to remove the uncategorized category

## Expected/actual behavior

You should see the uncategorized category checked, but you won't. And checking or unchecking it makes no difference.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by Nikschavan** [comment]
This is also happening when removing the category `Uncategorized` form the single product page. Tested this with the master branch.

Here is a screencast of the problem - https://cl.ly/pQJC

**Comment by mikejolley** [comment]
@Nikschavan Thats expected if it's the only cat. All products with no other cats will be uncategorized. Posts do the same.

**Comment by mikejolley** [comment]
@corsonr The bulk category edit doesn't allow unassigning of cats like this. If you go to Admin > Posts and try the same on the posts bulk editor, it's identical.

**Comment by seivad** [comment]
@mikejolley I don't think this is good behaviour, you should be able to bulk assign categories which would include deattaching existing ones and replacing with the new one.

**Comment by jonroz** [comment]
Hi Mikejolley,

when will the screens be redesigned to handle this simple routine? its not rocket science, its a basic requirement that all users will require when using the bulk edit tool on categories.
any help is appreciated

**Comment by tuanmy** [comment]
Issue still with Woo 3.5.7

**Comment by mikejolley** [comment]
Already stated, this is WordPress behaviour (the same happens for posts). The current WP UI will not be fixed in WooCommerce.
