### ISSUE TITLE
Custom base causing order confirmed 404

### ISSUE THREAD

**Issue by shelleyphant** [woocommerce/woocommerce#18891]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Setting my permalinks to "shop base with category" causes the custom field to display /shop/%product_cat%/ On checkout, this causes the order received page to 404.

Leaving the field blank/using just /shop/ removes the error, but doesn't display product categories in the url.

It's not a plugin conflict as the error still occurs with everything but WooCommerce disabled.

## Expected/actual behavior

I want my url to show shop/category/product. I used the radial select so I wouldn't get errors. It works for most of the pages, but still not the return from checkout.

The only option that doesn't return a 404 error is the default one.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://www.shelleybassett.com
Site URL: https://www.shelleybassett.com
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.1.14
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 6.76MB
Database Data Size: 5.52MB
Database Index Size: 1.24MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_ewwwio_images: Data: 0.05MB + Index: 0.04MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 3.02MB + Index: 0.07MB
wp_pmxi_files: Data: 0.00MB + Index: 0.00MB
wp_pmxi_history: Data: 0.00MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.00MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.00MB + Index: 0.00MB
wp_popularpostsdata: Data: 0.02MB + Index: 0.00MB
wp_popularpostssummary: Data: 0.02MB + Index: 0.05MB
wp_postmeta: Data: 0.46MB + Index: 0.11MB
wp_posts: Data: 1.85MB + Index: 0.83MB
wp_queue: Data: 0.00MB + Index: 0.00MB
wp_short_links: Data: 0.00MB + Index: 0.00MB
wp_short_link_clicks: Data: 0.00MB + Index: 0.00MB
wp_short_link_replacements: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.01MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wp_usermeta: Data: 0.01MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB
wp_yarpp_related_cache: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.01MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 94
feedback: 1
jetpack-portfolio: 14
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
ml-slide: 33
ml-slider: 6
nav_menu_item: 13
page: 12
post: 28
product: 3
revision: 236
sb-recipes: 1
shell-portfolio: 28
shop_order: 9
testfolio: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.1
WooSwipe: by Website Design – 1.1.6.6
WP Maintenance Mode: by Designmodo – 2.0.9

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #397 - /shop/
Cart: #398 - /shop/cart/
Checkout: #399 - /shop/checkout/
My account: #400 - /shop/my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by WPprodigy** [comment]
I set my checkout page to have the shop page as a parent like you have, but couldn't replicate this problem using `/shop/%product_cat%/` for permalinks.

**Comment by shelleyphant** [comment]
One of my customers reported the error a few weeks ago. Today I can't seem to get around it without changing the base to the default. I've tried disabling plugins and using the shopfront theme, but the problem is persisting. If it isn't caused by either of these, what else should I be looking for that is causing the error? The url for the order received page is the same regardless of product base, but one is causing a "nothing found" error. This isn't usable for my customers, and I've had to put the site under maintenance until it's fixed.

**Comment by WPprodigy** [comment]
What is the url of the order received page? Should be `https://example.com/shop/checkout/order-received/1166/?key=wc_order_123abc`

Also, check your .htaccess rules (if using apache server), along with any possible redirects/rewrite rules from other things.

**Comment by kloon** [comment]
I am noticing you have the maintenance mode plugin active, is that enabled by any chance? Can you perhaps test this by disabling the plugin and testing if that makes a difference? As @WPprodigy I am unable to replicate this locally.

**Comment by mikejolley** [comment]
You can replicate using:

- Shop page with category
- Give the checkout page a parent of 'shop'

The query then thinks 'checkout' is a category, which does not exist, hence 404.

There may be a hack like solution for this but tbh the easier way to fix this would be to not set the parents of your pages to `shop` and leave them top level.
