### ISSUE TITLE
Error Plugin Amazon Pay

### ISSUE THREAD

**Issue by OJosra** [woocommerce/woocommerce#18899]
![fo-amhpeto_zfolpakchxq](https://user-images.githubusercontent.com/28574769/36024504-3bfb3868-0d90-11e8-8cd6-49f1ca1a9308.png)
![njanxhy-qh_t5obalpvatg](https://user-images.githubusercontent.com/28574769/36024505-3c18e520-0d90-11e8-845e-ce39f62c912a.png)
![z56dq_ecqn_xodwawmzzza](https://user-images.githubusercontent.com/28574769/36024506-3c35f7c8-0d90-11e8-864a-5e1296135d24.png)

Hello good day

We have a problem with the amazon pay plugin I have opened a support case with amazon and it informs me of the following:

"We have done the relevant research and as I have said it seems that the problem comes from WooCommerce and not from our plugin, so you'll have to open a ticket with WooCommerce Github about it."

I attached the screenshots of the Error and the report of the consolo.

When we finish the purchase with the plugin, it gives us a message of not allowed. and does not let the company finish ..

`
### WordPress Environment ###

Home URL: https://www.santuariolacandela.org
Site URL: https://www.santuariolacandela.org
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.27
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.1
WC Database Prefix: wpog_
MaxMind GeoIP Database: ✔
Tamaño total de la base de datos: 137.40MB
Tamaño de los datos de la base de datos: 99.13MB
Tamaño del índice de la base de datos: 38.27MB
wpog_woocommerce_sessions: Datos: 2.02MB + Índice: 0.02MB
wpog_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB
wpog_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB
wpog_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.05MB
wpog_woocommerce_order_items: Datos: 0.05MB + Índice: 0.02MB
wpog_woocommerce_order_itemmeta: Datos: 0.16MB + Índice: 0.16MB
wpog_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB
wpog_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.05MB
wpog_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB
wpog_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.05MB
wpog_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB
wpog_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB
wpog_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB
wpog_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB
wpog_adrotate: Datos: 0.02MB + Índice: 0.00MB
wpog_adrotate_groups: Datos: 0.02MB + Índice: 0.00MB
wpog_adrotate_linkmeta: Datos: 0.02MB + Índice: 0.00MB
wpog_adrotate_schedule: Datos: 0.02MB + Índice: 0.02MB
wpog_adrotate_stats: Datos: 0.02MB + Índice: 0.03MB
wpog_adrotate_stats_archive: Datos: 0.02MB + Índice: 0.03MB
wpog_adrotate_tracker: Datos: 0.02MB + Índice: 0.03MB
wpog_adrotate_transactions: Datos: 0.02MB + Índice: 0.02MB
wpog_ahm_country: Datos: 0.02MB + Índice: 0.00MB
wpog_ahm_coupons: Datos: 0.02MB + Índice: 0.00MB
wpog_ahm_download_stats: Datos: 0.02MB + Índice: 0.00MB
wpog_ahm_emails: Datos: 0.02MB + Índice: 0.00MB
wpog_ahm_feature_products: Datos: 0.02MB + Índice: 0.00MB
wpog_ahm_licenses: Datos: 0.02MB + Índice: 0.00MB
wpog_ahm_orders: Datos: 0.02MB + Índice: 0.00MB
wpog_ahm_order_items: Datos: 0.02MB + Índice: 0.00MB
wpog_ahm_payment_methods: Datos: 0.00MB + Índice: 0.00MB
wpog_ahm_withdraws: Datos: 0.00MB + Índice: 0.00MB
wpog_commentmeta: Datos: 0.02MB + Índice: 0.05MB
wpog_comments: Datos: 0.09MB + Índice: 0.09MB
wpog_cpk_wpcsv_export_queue: Datos: 0.22MB + Índice: 0.08MB
wpog_cpk_wpcsv_log: Datos: 0.00MB + Índice: 0.00MB
wpog_download_log: Datos: 0.02MB + Índice: 0.02MB
wpog_ewwwio_images: Datos: 4.52MB + Índice: 6.06MB
wpog_icl_content_status: Datos: 0.02MB + Índice: 0.02MB
wpog_icl_core_status: Datos: 0.02MB + Índice: 0.02MB
wpog_icl_flags: Datos: 0.02MB + Índice: 0.02MB
wpog_icl_languages: Datos: 0.02MB + Índice: 0.03MB
wpog_icl_languages_translations: Datos: 0.19MB + Índice: 0.11MB
wpog_icl_locale_map: Datos: 0.02MB + Índice: 0.00MB
wpog_icl_message_status: Datos: 0.02MB + Índice: 0.03MB
wpog_icl_mo_files_domains: Datos: 0.02MB + Índice: 0.02MB
wpog_icl_node: Datos: 0.02MB + Índice: 0.00MB
wpog_icl_reminders: Datos: 0.02MB + Índice: 0.00MB
wpog_icl_strings: Datos: 16.55MB + Índice: 7.55MB
wpog_icl_string_packages: Datos: 0.05MB + Índice: 0.00MB
wpog_icl_string_pages: Datos: 0.02MB + Índice: 0.02MB
wpog_icl_string_positions: Datos: 0.09MB + Índice: 0.02MB
wpog_icl_string_status: Datos: 0.02MB + Índice: 0.02MB
wpog_icl_string_translations: Datos: 4.52MB + Índice: 1.52MB
wpog_icl_string_urls: Datos: 0.02MB + Índice: 0.02MB
wpog_icl_translate: Datos: 0.44MB + Índice: 0.02MB
wpog_icl_translate_job: Datos: 0.02MB + Índice: 0.02MB
wpog_icl_translations: Datos: 1.52MB + Índice: 3.72MB
wpog_icl_translation_batches: Datos: 0.02MB + Índice: 0.00MB
wpog_icl_translation_status: Datos: 0.44MB + Índice: 0.05MB
wpog_layerslider: Datos: 0.05MB + Índice: 0.00MB
wpog_layerslider_revisions: Datos: 0.02MB + Índice: 0.00MB
wpog_links: Datos: 0.02MB + Índice: 0.02MB
wpog_loginizer_logs: Datos: 0.00MB + Índice: 0.01MB
wpog_options: Datos: 2.42MB + Índice: 0.13MB
wpog_pmxe_exports: Datos: 0.11MB + Índice: 0.00MB
wpog_pmxe_google_cats: Datos: 0.39MB + Índice: 0.00MB
wpog_pmxe_posts: Datos: 0.17MB + Índice: 0.00MB
wpog_pmxe_templates: Datos: 0.02MB + Índice: 0.00MB
wpog_postmeta: Datos: 32.56MB + Índice: 13.06MB
wpog_posts: Datos: 29.55MB + Índice: 3.78MB
wpog_termmeta: Datos: 0.02MB + Índice: 0.03MB
wpog_terms: Datos: 0.14MB + Índice: 0.16MB
wpog_term_relationships: Datos: 0.19MB + Índice: 0.14MB
wpog_term_taxonomy: Datos: 0.16MB + Índice: 0.19MB
wpog_usermeta: Datos: 0.17MB + Índice: 0.16MB
wpog_users: Datos: 0.01MB + Índice: 0.01MB
wpog_wc_download_log: Datos: 0.02MB + Índice: 0.03MB
wpog_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB
wpog_yoast_seo_links: Datos: 1.28MB + Índice: 0.36MB
wpog_yoast_seo_meta: Datos: 0.09MB + Índice: 0.00MB

### Post Type Counts ###

advanced_ads: 3
attachment: 7869
avia_framework_post: 14
customize_changeset: 4
custom_css: 1
dlm_download: 1
dlm_download_version: 3
jetpack-testimonial: 1
miglaform: 6
migla_custom_values: 1
migla_odonation_p: 20
migla_stripe_plan: 1
nav_menu_item: 127
page: 84
post: 1447
product: 58
product_variation: 80
revision: 3779
shop_coupon: 3
shop_order: 106
shop_order_refund: 3
wpdmpro: 1
wpml_tf_feedback: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

AdRotate: por Arnan de Gans – 4.9
Akismet Anti-Spam: por Automattic – 4.0.2
AMP: por Automattic – 0.6.0
Aviso de Cookie: por dFactory – 1.2.41
Disqus for WordPress: por Disqus – 3.0.11
Download Monitor: por Never5 – 4.0.2
EWWW Image Optimizer: por Shane Bishop – 4.0.6
Facebook for WooCommerce: por Facebook – 1.7.5 – No probado con la versión activa de WooCommerce
Glue for Yoast SEO & AMP: por Joost de Valk – 0.4.2
GTranslate: por Translate AI Multilingual Solutions – 2.8.36
Jetpack by WordPress.com: por Automattic – 5.8
Loginizer: por Raj Kothari – 1.3.8
Members: por Justin Tadlock – 2.0.2
No CAPTCHA reCAPTCHA for WooCommerce: por MailOptin Team – 1.2.1 – No probado con la versión activa de WooCommerce
No CAPTCHA reCAPTCHA: por MailOptin Team – 1.2.1
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 3.0.2
SG Optimizer: por SiteGround – 3.3.5
TinyMCE Advanced: por Andrew Ozz – 4.6.7
Total Donations: por Binti Brindamour and Astried Silvanie – 2.0.5
WooCommerce Amazon Pay Gateway: por WooCommerce – 1.8.1
WooCommerce Stripe Gateway: por WooCommerce – 4.0.5
WooCommerce: por Automattic – 3.3.1
Yoast SEO Premium: por Equipo Yoast – 5.8

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude-from-search (exclude-from-search-2)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-2)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base de la tienda: #33046 - /tienda/
Carrito: #33047 - /carrito/
Finalizar compra: #33048 - /finalizar-comprar/
Mi cuenta: #15 - /mi-cuenta/
Términos y condiciones: #23923 - /terminos-y-condiciones-de-venta/

### Theme ###

Name: Enfold
Version: 4.2.3
Author URL: https://kriesi.at
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

Thank you and good morning,

**Comment by OJosra** [comment]
![fo-amhpeto_zfolpakchxq](https://user-images.githubusercontent.com/28574769/36024475-2682a444-0d90-11e8-8546-50398c7d4a94.png)
![njanxhy-qh_t5obalpvatg](https://user-images.githubusercontent.com/28574769/36024476-26a1213a-0d90-11e8-979d-a5d375a8043d.png)
![z56dq_ecqn_xodwawmzzza](https://user-images.githubusercontent.com/28574769/36024477-26bd2c9a-0d90-11e8-9e9b-2a2f35352ac4.png)

**Comment by mikejolley** [comment]
This is specific to that gateway not core, please use the helpdesk.

https://woocommerce.com/contact-us/
http://woocommerce.com/my-account/create-a-ticket/

Thanks
