### ISSUE TITLE
Adding products to orders requires "edit_product" capability

### ISSUE THREAD

**Issue by dtwist** [woocommerce/woocommerce#18894]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Overview
We want sales team members to create/ammend orders when working with customers, but do not want them to be able to edit the store catalog. To that end, we've created a custom role that disallows all the order editing/publishing capabilities. However, we've found that adding products to an order requires a user have the "edit_product" capability.

## Steps to reproduce the issue

1. With an existing catalog of products, create a user role that mimics the "shop manager" role, but remove all product edit and publish permissions.
2. Assign that role to a user and log in as that user.
3. Start creating a new order.
4. Click "Add item(s)", then "Add product(s)".
5. In the search field, search for a product title you know exists.

## Expected/actual behavior

When I follow those steps, products don't appear in the results.

I was expecting to see the product(s) I searched for.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

The problem was introduced during the refactoring for CRUD in [this commit](https://github.com/woocommerce/woocommerce/commit/ac62cffe16b00507cfbf73d53e25a732b26ea896). Whereas the previous code was checking for a "read_product" capability, the [new code uses](https://github.com/woocommerce/woocommerce/blob/ff7716509eec0efc46270bc79b8bdde557b4f1a4/includes/class-wc-ajax.php#L1356) a newly created "wc_products_array_filter_editable" function that checks for the "edit_product" capability. 

Perhaps there are places where you need to return only products the user can edit, but the order screen does not seem to be one of them. I propose that you review whether this filter is needed at all. If not, remove it. If it is indeed needed for some use-cases, add an argument to the method (e.g. $return_editable_only) to use the filter or not, and do not filter results on the order management screen.

**Comment by mikejolley** [comment]
Looks like this is not a new bug so I'm not going to rush this for 3.3.2. It can go into 3.4.

If you're like to contribute a fix sooner than we get a chance to look at it please go ahead.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19087

**Comment by alexminza** [comment]
The user account has both `read_product` and `edit_product` and still can't add a product item to a new order.

WC: 3.4.2
WP: 4.9.6

**Comment by limist** [comment]
@alexminza  Try using/granting the `edit_published_products` permission
