### ISSUE TITLE
Woocommerce php fatal error

### ISSUE THREAD

**Issue by muzammil555** [woocommerce/woocommerce#18897]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by muzammil555** [comment]
i am getting this error when i open my site 
Fatal error: Internal Zend error - Missing class information for in /home/user/public_html/wp-content/plugins/woocommerce/includes/class-wc-install.php on line 18

**Comment by mikejolley** [comment]
I'm not seeing it. If there were an error in the class I'd expect to see it on every page load.

Some sites have suggested this can be related to PHP version. You didn't send the log but I don't know what you're running. Unit tests appear to be passing however with all php versions and I have no way to replicate.

Would suggest ruling out plugin versions and updating to a newer version of PHP if possible via your hosting.
