### ISSUE TITLE
conflict with clients logging sessions

### ISSUE THREAD

**Issue by legion33** [woocommerce/woocommerce#18892]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
After updating to 3.3.1 I noticed that all my clients were not able to sign in to my online store anymore. After some reported this, the IT company that manages my site said that they had to clear all logging sessions. After that worked fine but site was blocked from access of clients for a day almost.

**Comment by mikejolley** [comment]
The login system is handled by WordPress itself so I don't see why WC update would affect this. If the IT company know the issue, have them create a ticket here. There isn't enough information for us to work with here.

Thanks
