### ISSUE TITLE
products in my store are to long in thee mobile version after update also in tablet version the navigator drop box it see thru.. ive attached images 

### ISSUE THREAD

**Issue by cyihats** [woocommerce/woocommerce#18914]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```

Home URL: |   | https://cyihats.com
-- | -- | --
Site URL: |   | https://cyihats.com
WC version: |   | 3.3.1
Log directory writable: |   | /home4/cyihats/public_html/wp-content/uploads/wc-logs/
WP version: |   | 4.9.4
WP multisite: |   | –
WP memory limit: |   | 256 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US
![unnamed - copy](https://user-images.githubusercontent.com/36308907/36044592-2810f25a-0da1-11e8-8f4c-d9801c43a12b.png)
![unnamed 1 - copy](https://user-images.githubusercontent.com/36308907/36044593-282c2c00-0da1-11e8-99a7-478de882e75d.png)
![unnamed - copy](https://user-images.githubusercontent.com/36308907/36044594-28424e54-0da1-11e8-9a51-6f41bd5bf3a2.jpg)

</details>

**Comment by WPprodigy** [comment]
So, you want two columns of products rather than four? You can try changing this at Appearance > Customize > WooCommerce. If there isn't a setting for products per row, then your theme or another plugin is controlling it.

This is a theme/plugin conflict though and not a core WooCommerce issue.

**Comment by cyihats** [comment]
Oh thank you yes it Will change to 2 columns but the size will be skinny like the image 


CYi Hats
Rep Your City
www.CYiHats.com

**Comment by WPprodigy** [comment]
The size is "skinny" because there is a very limited amount of space for it to show up. You should contact your theme authors about this.

**Comment by cyihats** [comment]
This started after the previous updates 


CYi Hats
Rep Your City
www.CYiHats.com

**Comment by WPprodigy** [comment]
I don't see any CSS in your theme that was meant to change the display of the shop page / columns on mobile.

I don't know why this changed, but I haven't heard any reports from other themes about this problem.

Need something like this:
```
@media (max-width: 479px) {
	.woocommerce ul.products li.product {
		width: 100%;
	}
}
```

**Comment by cyihats** [comment]
That code goes into what folder? Yea I don’t know why either the mobile and table navigation button got screwed up


CYi Hats
Rep Your City
www.CYiHats.com

**Comment by cyihats** [comment]
Ok so I added that code into the css and the product images are bigger now I just need to add another column because now all products are in 1 column 


CYi Hats
Rep Your City
www.CYiHats.com
