### ISSUE TITLE
Allow changing the default product category

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#18929]
Source: https://github.com/woocommerce/woocommerce/issues/18928#issuecomment-364820340

WordPress allows you to change the default posts category. This would be useful for stores that are already up and running, and perhaps already have a category that they would like to be the default.

Some options that I can think of:

1) Add setting at Settings > Writings: http://cld.wthms.co/ZoKcq7. This is inline with WordPress, but kinda hard to find IMO (I forgot it even existed).

2) Add setting on each product category. Could just be a simple checkbox called "make default category". http://cld.wthms.co/C8FxaE

3) Add a setting to assign a new default category, only on the current default category settings page.

I'm more partial to the second, but may need some inline docs at Settings > Writings if we go this route?

While technically a feature, this feels like something suited for a 3.3 fix release still. Would be nice if it could fit into 3.3.2 along with https://github.com/woocommerce/woocommerce/pull/18879. Happy to help, just not sure what the best path is for implementing this.

**Comment by maddisondesigns** [comment]
Or, another option... How about adding it to the `WooCommerce > Settings > Products` screen, like this quick mockup.

![woocommerceproductssettings](https://user-images.githubusercontent.com/2078245/36084608-068ccd56-1013-11e8-91b2-b238ab7412e6.jpg)

**Comment by mikejolley** [comment]
Looks like a good candidate for row actions rather than settings. Then it can be kept in context of category page.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18941 :)

**Comment by richplane** [comment]
Need some update to the docs because it took me a long time to work out where this setting was (having found this issue report from the complaints on wordpress.org).

(For anyone else: it appears on hovering over the categories in the table on the edit-tags.php manage categories screen. So under normal circumstances, it's invisible! ...which is suboptimal.)
