### ISSUE TITLE
Wrong zero total in order emails

### ISSUE THREAD

**Issue by Jh4ck** [woocommerce/woocommerce#18923]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an order via REST API (POST /wp-json/wc/v2/orders) with the following request:
`{
    "set_paid": true,
    "billing": {
        "first_name": "Mario",
        "last_name": "Rossi",
        "company": "Rossi",
        "address_1": "Address example",
        "city": "Milano",
        "state": "MI",
        "postcode": "20100",
        "country": "IT",
        "email": "mail@example.com",
        "phone": "1234567890"
    },
    "shipping": {
        "first_name": "Mario",
        "last_name": "Rossi",
        "address_1": "Address example",
        "city": "Milano",
        "state": "MI",
        "postcode": "20100",
        "country": "IT"
    },
    "line_items": [
        {
            "product_id": 29,
            "quantity": 12
        },
        {
            "product_id": 26,
            "variation_id": 28,
            "quantity": 12
        },
        {
            "product_id": 23,
            "variation_id": 25,
            "quantity": 12
        },
        {
            "product_id": 20,
            "variation_id": 22,
            "quantity": 12
        }
    ],
    "": [],
    "status": "processing",
    "payment_method": "bacs",
    "payment_method_title": "Bonifico bancario"
}`

2. The following response is returned:
`{
    "id": 103,
    "parent_id": 0,
    "number": "103",
    "order_key": "wc_order_5a7f9fe2810ee",
    "created_via": "rest-api",
    "version": "3.3.1",
    "status": "processing",
    "currency": "EUR",
    "date_created": "2018-02-11T01:44:02",
    "date_created_gmt": "2018-02-11T01:44:02",
    "date_modified": "2018-02-11T01:44:02",
    "date_modified_gmt": "2018-02-11T01:44:02",
    "discount_total": "0.00",
    "discount_tax": "0.00",
    "shipping_total": "0.00",
    "shipping_tax": "0.00",
    "cart_tax": "11.07",
    "total": "276.00",
    "total_tax": "11.07",
    "prices_include_tax": true,
    "customer_id": 0,
    "customer_ip_address": "",
    "customer_user_agent": "",
    "customer_note": "",
    "billing": {
        "first_name": "Mario",
        "last_name": "Rossi",
        "company": "Rossi",
        "address_1": "Address example",
        "city": "Milano",
        "state": "MI",
        "postcode": "20100",
        "country": "IT",
        "email": "mail@example.com",
        "phone": "1234567890"
    },
    "shipping": {
        "first_name": "Mario",
        "last_name": "Rossi",
        "address_1": "Address example",
        "city": "Milano",
        "state": "MI",
        "postcode": "20100",
        "country": "IT"
    },
    "payment_method": "bacs",
    "payment_method_title": "Bonifico bancario",
    "transaction_id": "",
    "date_paid": null,
    "date_paid_gmt": null,
    "date_completed": null,
    "date_completed_gmt": null,
    "cart_hash": "",
    "meta_data": [],
    "line_items": [
        {
            "id": 232,
            "name": "Baileys",
            "product_id": 29,
            "variation_id": 0,
            "quantity": 12,
            "tax_class": "",
            "subtotal": "92.15",
            "subtotal_tax": "3.85",
            "total": "92.15",
            "total_tax": "3.85",
            "taxes": [
                {
                    "id": 1,
                    "total": "3.85187",
                    "subtotal": "3.85187"
                }
            ],
            "meta_data": [],
            "sku": "",
            "price": 7.6791666666667
        },
        {
            "id": 233,
            "name": "Acqua - Minerale",
            "product_id": 26,
            "variation_id": 28,
            "quantity": 12,
            "tax_class": "",
            "subtotal": "23.04",
            "subtotal_tax": "0.96",
            "total": "23.04",
            "total_tax": "0.96",
            "taxes": [
                {
                    "id": 1,
                    "total": "0.963072",
                    "subtotal": "0.963072"
                }
            ],
            "meta_data": [
                {
                    "id": 2076,
                    "key": "tipo",
                    "value": "Minerale"
                }
            ],
            "sku": "",
            "price": 1.92
        },
        {
            "id": 234,
            "name": "Aranciata - Lattina",
            "product_id": 23,
            "variation_id": 25,
            "quantity": 12,
            "tax_class": "",
            "subtotal": "11.52",
            "subtotal_tax": "0.48",
            "total": "11.52",
            "total_tax": "0.48",
            "taxes": [
                {
                    "id": 1,
                    "total": "0.481536",
                    "subtotal": "0.481536"
                }
            ],
            "meta_data": [
                {
                    "id": 2086,
                    "key": "tipo",
                    "value": "Lattina"
                }
            ],
            "sku": "",
            "price": 0.96
        },
        {
            "id": 235,
            "name": "Coca cola - Grande",
            "product_id": 20,
            "variation_id": 22,
            "quantity": 12,
            "tax_class": "",
            "subtotal": "138.22",
            "subtotal_tax": "5.78",
            "total": "138.22",
            "total_tax": "5.78",
            "taxes": [
                {
                    "id": 1,
                    "total": "5.777596",
                    "subtotal": "5.777596"
                }
            ],
            "meta_data": [
                {
                    "id": 2096,
                    "key": "dimensione",
                    "value": "Grande"
                }
            ],
            "sku": "",
            "price": 11.518333333333
        }
    ],
    "tax_lines": [
        {
            "id": 236,
            "rate_code": "IT-IVA-1",
            "rate_id": 1,
            "label": "IVA",
            "compound": false,
            "tax_total": "11.07",
            "shipping_tax_total": "0.00",
            "meta_data": []
        }
    ],
    "shipping_lines": [],
    "fee_lines": [],
    "coupon_lines": [],
    "refunds": [],
    "_links": {
        "self": [
            {
                "href": "https://www.example.com/wp-json/wc/v2/orders/103"
            }
        ],
        "collection": [
            {
                "href": "https://www.example.com/wp-json/wc/v2/orders"
            }
        ]
    }
}`
3. An email is sent to the administrator and an email is sent to the customer with the total = 0

## Expected/actual behavior

When I follow those steps, the total is zero in both the emails sent to the customer and administrator.
![zero_total](https://user-images.githubusercontent.com/6827784/36068446-2b107cc4-0ed6-11e8-9bfb-13502be523c0.PNG)

I was expecting to see the same correct total I see in the orders list of woocommerce dashboard.
![correct_total_dashboard](https://user-images.githubusercontent.com/6827784/36068456-7f97e836-0ed6-11e8-963f-e3a237416115.PNG)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: https://www.oliogangalupo.com/third-party-wp
Site URL: https://www.oliogangalupo.com/third-party-wp
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: it_IT

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.5.38 - Consigliamo una versione minima di PHP pari alla 5.6. Vedi: Come aggiornare la versione di PHP
PHP Post Max Size: 25 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.57.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.1
WC Database Prefix: wpyp_
MaxMind GeoIP Database: ❌ Il database MaxMind GeoIP non esiste - La geolocalizzazione non funzionerà. È possibile scaricarlo e installarlo manualmente da http://dev.maxmind.com/geoip/legacy/geolite/ al percorso: . Scorrere fino a "download" e scaricare il file "Binary / gzip" accanto a "GeoLite Country". Ricordarsi di decomprimere GeoIP.dat.gz e caricare solo il file GeoIP.dat.
Total Database Size: 1.67MB
Database Data Size: 1.35MB
Database Index Size: 0.32MB
wpyp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wpyp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wpyp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpyp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpyp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB
wpyp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.06MB
wpyp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wpyp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpyp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpyp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpyp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpyp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpyp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpyp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpyp_commentmeta: Data: 0.00MB + Index: 0.00MB
wpyp_comments: Data: 0.02MB + Index: 0.01MB
wpyp_links: Data: 0.00MB + Index: 0.00MB
wpyp_loginizer_logs: Data: 0.00MB + Index: 0.00MB
wpyp_options: Data: 0.57MB + Index: 0.07MB
wpyp_postmeta: Data: 0.14MB + Index: 0.09MB
wpyp_posts: Data: 0.02MB + Index: 0.02MB
wpyp_termmeta: Data: 0.00MB + Index: 0.01MB
wpyp_terms: Data: 0.00MB + Index: 0.01MB
wpyp_term_relationships: Data: 0.00MB + Index: 0.00MB
wpyp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wpyp_usermeta: Data: 0.01MB + Index: 0.01MB
wpyp_users: Data: 0.00MB + Index: 0.01MB
wpyp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpyp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpyp_wpml_mails: Data: 0.49MB + Index: 0.00MB

### Post Type Counts ###

attachment: 10
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
page: 5
post: 2
product: 4
product_variation: 8
shop_order: 41

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Jetpack by WordPress.com: by Automattic – 5.7.1
Loginizer: by Raj Kothari – 1.3.8
Product CSV Import Export (BASIC): by XAdapter – 1.4.1 – Non testato con la versione attiva di WooCommerce
Woo Preview Emails: by Digamber Pradhan – 1.3.0 – Non testato con la versione attiva di WooCommerce
WooCommerce - Store Exporter: by Visser Labs – 1.9.4 – Non testato con la versione attiva di WooCommerce
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.1
WooCommerce: by Automattic – 3.3.1
WP Mail Logging: by Christian Zöller – 1.8.3
WP Rollback: by WordImpress – 1.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /negozio/
Carrello: #5 - /carrello/
Cassa: #6 - /checkout/
Il mio account: #7 - /mio-account/
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: Storefront
Version: 2.2.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/emails/admin-new-order.php
```
</details>

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/18939
