### ISSUE TITLE
Display problem with Safari

### ISSUE THREAD

**Issue by idjul** [woocommerce/woocommerce#18927]
Since the last version of Woocommerce, i have a display problem **only** with Safari.
I have 12 products on my page, I don't know why, on the first line, I have 3 products, on the second line, 4 products and 1 product on the last line.
The problem doesn't exists before the last version of WooCommerce.

You can have a look of the problem here: http://swimming.lu/boutique/

Thank you for your help

**Comment by WPprodigy** [comment]
This is a theming issue / CSS bug. I don't think anything with the grid changed with the latest WC update, so maybe you are just now seeing this bug, or it's a new safari bug. Either way, this is likely only happening with your theme so you need to contact your theme authors.

The CSS controling the grid is coming from `wp-content/themes/panoramic/library/css/woocommerce-custom.css`, so clearly your theme is doing it's own thing with the products grid.

**Comment by idjul** [comment]
Thank you!

**Comment by ModenDev** [comment]
Actually I am having the same issue with divi theme. Did you find a solution to this?

**Comment by DrZivil** [comment]
The problematic values that get rounded in a wrong way in Safari are allso present in the Storefront Theme.
https://iomi.style/wp-content/themes/storefront/assets/css/woocommerce/woocommerce.css?ver=2.4.3

`@media (min-width: 768px)
.page-template-template-fullwidth-php .site-main ul.products.columns-3 li.product, .page-template-template-homepage-php .site-main ul.products.columns-3 li.product, .storefront-full-width-content .site-main ul.products.columns-3 li.product {
    width: 30.4347826087%;
    float: left;
    margin-right: 4.347826087%;
}`

I will overwrite the Value to 30.4% i guess. But i Think every single Page Using Storefront is affected by this in Safari.
