### ISSUE TITLE
Product page is now using single template

### ISSUE THREAD

**Issue by rachaelrobinson1987** [woocommerce/woocommerce#18920]
Hi there

This morning I've updated to the latest Woocommerce and now single-product.php is pulling in the single.php blog page template. I'm using a child theme - it doesn't seem to be recognising it even though nothing else has changed (the theme selected is child) On the product page's code in the head, body class="single-product" which is correct but further down, it's pulling in single.php code which isn't in the child theme 

Please can someone help? I've tried disabling the majority of plugins to see if there's a conflict but presuming it's something to do with the child theme

**Comment by rachaelrobinson1987** [comment]
I've been trying to sort this all afternoon. I've disabled all plugins except woocommerce, gone back to main theme (not using child), working on localhost as soon as I update woocommerce, divs from the single.php appear. It's like the templates in woocommerce folder are being ignored. Really need some help :-(

**Comment by willgorham** [comment]
This might have to do with the new support for non-WC themes. Does your theme or child theme declare woocommerce support? 
```
add_action( 'after_setup_theme', function() {
	add_theme_support( 'woocommerce' );
} );
```

**Comment by rachaelrobinson1987** [comment]
That's fixed it. OMG. Thank you, Will. 

Is there anything I should be doing to ensure my non-WC theme stays from messing up? Apart from keeping everything up to date/declaring support? 

Much appreciated, thank you

**Comment by WPprodigy** [comment]
Technically theme support should have been declared in the past before overriding templates, it just wasn't enforced.

You should be good now: https://github.com/woocommerce/woocommerce/wiki/Declaring-WooCommerce-support-in-themes

> Is there anything I should be doing to ensure my non-WC theme stays from messing up? 

Try to not override templates as much as possible. Use hooks/filters instead.

**Comment by rachaelrobinson1987** [comment]
Okay - will take on-board. Thanks so much for the prompt help.
