### ISSUE TITLE
Item count disappears on product specific filter where results are less than one page

### ISSUE THREAD

**Issue by alexsgithubusername** [woocommerce/woocommerce#18922]
If filtering for a specific product on the woocommerce order page, it will only give you a "xx items" if there is more than one page of such items. Otherwise, it's just blank.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by WPprodigy** [comment]
> If filtering for a specific product on the woocommerce order page

How are you doing that exactly? Using the search field and searching for a product by name?

Otherwise, I think you might have an extension that is adding in this functionality for you.

**Comment by alexsgithubusername** [comment]
Yes, just using the search field. No additional extensions.

**Comment by mikejolley** [comment]
Looks to be hidden on purpose unless pagination is in use. **If you can see all of the results**, it doesn't seem useful to show a count. If you have a valid use case for it let me know but I'd prefer the order page had less visual noise if possible.

**Comment by alexsgithubusername** [comment]
It means you have to MANUALLY COUNT up to 20 orders which when you need to do it 5 times a day is a HUGE inconvenience. If they wanted to get rid of visual clutter, get rid of that completely useless eye icon they've introduced to replace the VERY USEFUL customer notes icon. There is now also no way to see customers notes at a glance, but instead there's an eye icon that gives you exactly the same info as if you just clicked on a customers name. It's a real shame to see woocommerce slowly loosing so much of it's critical functionality. It used to be a really great plugin!

**Comment by alexsgithubusername** [comment]
oh, actually I realised I can set the orders per page to something less like 5 orders per page, so that goes a long way to relieving the pain of a manual count :)

But the disappearance of the customer orders icon is still pretty frustrating :(

**Comment by mikejolley** [comment]
After you have 20 orders wouldn't that show 20 at all times anyway? :)

**Comment by alexsgithubusername** [comment]
Wordpress allows the user to set the number of orders per page under screen options, and thankfully, this is something woocommerce can't mess with. If only woocommerce used this screen options feature to allow users to choose whether they want to see things like customer's notes, but alas, they just keep removing more and more critical functionality that at least usually I can find a work around for, but not with the missing customer notes :(

**Comment by WPprodigy** [comment]
Can add columns back if you need them: https://gist.github.com/WPprodigy/7b15029d4a06be3d86134087e4b99cbe

Customer notes could hardly be classified as "critical functionality" though IMO. Under that logic, every single checkout field is critical and should have it's own column.

**Comment by alexsgithubusername** [comment]
YES!!!!! THANK YOU SO MUCH!!!! Might not be critical to many but was definitely critical to me!!

**Comment by WPprodigy** [comment]
Happy to help. Just gotta realize that if everything critical to some people was added, it'd be a nightmare of settings and bloat :)

**Comment by alexsgithubusername** [comment]
Which is why it's so weird that they're ADDING totally useless things like the eye icon. NOBODY need that seeing it gives you exactly the same info you get when you click on the name of the order except you can't DO anything with it except view it. Yet stuff that's actually useful, disappears. Anyway, very happy I found a work around. Thank you again!! :)
