### ISSUE TITLE
uncategorized product category appears in frontend despite no products assigned

### ISSUE THREAD

**Issue by davefaloon** [woocommerce/woocommerce#18928]
After updating WC to 3.3.1 the product category "uncategorized" appears in the frontend of the site. 

No products are assigned to uncategorized but this category appears anyways. I have tested this in several themes (storefront, twenty sixteen, and twenty fifteen). This appearance occurs in the shop page (www.sitename.com/shop/). 

Please let me know if I can provide any further information / URLs / code samples / etc.

**Comment by maddisondesigns** [comment]
It's frustrating that this category can't be deleted. Why doesn’t WooCommerce add an option so that we can specify/change the default WooCommerce Category, just like WordPress does for Post Categories (Settings > Writing). This would make more sense and would also give us the ability to remove this annoying Uncategorized Category.

**Comment by WPprodigy** [comment]
> After updating WC to 3.3.1 the product category "uncategorized" appears in the frontend of the site. [..] I have tested this in several themes (storefront, twenty sixteen, and twenty fifteen). 

I'm not able to replicate this with the Storefront theme. Pretty sure your theme or another plugin is interferring with the query causing this to happen.

Here is a snippet you can use to remove it though: https://mikejolley.com/2018/02/07/woocommerce-3-3-hide-uncategorized-category-from-the-shop-page-on-the-frontend/

> It's frustrating that this category can't be deleted. Why doesn’t WooCommerce add an option so that we can specify/change the default WooCommerce Category, just like WordPress does for Post Categories (Settings > Writing)

That could be done. At the moment you just need to update the `default_product_cat` option in the database to be the ID of the category you want to be the default.

> This would make more sense and would also give us the ability to remove this annoying Uncategorized Category.

There is no way to remove the default Posts category - this would go against the whole reason it's needed.

**Comment by maddisondesigns** [comment]
> There is no way to remove the default Posts category - this would go against the whole reason it's needed.

I realise you can't delete the default Posts Category. The default (WP) Posts Category is `Uncategorized`. On the `Settings > Writing` screen, you can change the default Category to be some other Category. After changing this settings, you are then able to remove the `Uncategorized` category (because it's no longer the default category).

I'm suggesting that WooCommerce should work in the same way. I should be able to specify the default WooCommerce Product Category (without having to manually edit the db). After changing the default WC Product Category, we would then be able to remove the `Uncategorized` category (because it will no longer the default category).

**Comment by WPprodigy** [comment]
Gotcha, yea that makes sense - definitely in agreement with that.

**Comment by hitec4ever** [comment]
I have the the same issue. After update some products where added to the uncategorized category. After placing them in the correct category the uncategorized category keeps showing. Please have this fixed.

**Comment by mikejolley** [comment]
Unable to replicate it being shown when empty. A plugin could be filtering on `woocommerce_product_subcategories_hide_empty` to change the default behaviour, which is to hide empty cats.

**Comment by davefaloon** [comment]
Still see uncategorized after trying the suggested fixes ... see below. 

-- flushed the WC cache (Update: Also could be cache, so clear the transients at WC > Status > Tools. And flush website cache.)

--Removed all plugins other WC (just WC. no other piggyback plugins active - e.g. WC bulk, WC Advnced Order) - and flushed the WC cache after each plugin removal

--Tried in several different themes; storefront, twenty sixteen, twenty fifteen. cleared WC cache between each attempted theme. 

--Removed other themes from WP. only Store Front active . Cleared WC cache.

--Tried different browsers. Resetting local cache in each browser. 

(Thanks y'all. Appreciate the assistance and suggested fixes)

**Comment by mikejolley** [comment]
@davefaloon System status report and link to shop page please.

**Comment by davefaloon** [comment]
--This is the stage. LMK if you need stage creds. URL. http://ferndalepp.beveragejunkie.com/shop/

below is system report ...

`
### WordPress Environment ###

Home URL: http://ferndalepp.beveragejunkie.com
Site URL: http://ferndalepp.beveragejunkie.com
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.27
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.1
WC Database Prefix: wp_nm9ise_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 8.01MB
Database Data Size: 6.32MB
Database Index Size: 1.69MB
wp_nm9ise_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_nm9ise_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_nm9ise_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wp_nm9ise_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_nm9ise_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_nm9ise_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_nm9ise_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_nm9ise_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_nm9ise_comments: Data: 0.02MB + Index: 0.09MB
wp_nm9ise_links: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_options: Data: 1.13MB + Index: 0.05MB
wp_nm9ise_postmeta: Data: 0.25MB + Index: 0.20MB
wp_nm9ise_posts: Data: 0.11MB + Index: 0.06MB
wp_nm9ise_termmeta: Data: 0.02MB + Index: 0.03MB
wp_nm9ise_terms: Data: 0.02MB + Index: 0.03MB
wp_nm9ise_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_nm9ise_usermeta: Data: 0.11MB + Index: 0.09MB
wp_nm9ise_users: Data: 0.02MB + Index: 0.05MB
wp_nm9ise_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_nm9ise_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_nm9ise_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfConfig: Data: 0.27MB + Index: 0.00MB
wp_nm9ise_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfFileMods: Data: 0.28MB + Index: 0.00MB
wp_nm9ise_wfHits: Data: 1.52MB + Index: 0.28MB
wp_nm9ise_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_nm9ise_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfLogins: Data: 0.06MB + Index: 0.03MB
wp_nm9ise_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfPendingIssues: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_nm9ise_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_nm9ise_wfStatus: Data: 0.13MB + Index: 0.09MB
wp_nm9ise_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_nm9ise_wfVulnScanners: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 55
nav_menu_item: 6
page: 6
post: 1
product: 24
quantity-rule: 3
revision: 24
shop_coupon: 1
shop_order: 15

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.14.3

WooCommerce: by Automattic – 3.3.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
We've been talking about the shop page. This is a widget. The widget in Appearance > Widgets has an option ">Hide empty categories".

Is that checked?

**Comment by davefaloon** [comment]
Boom, boom. Out go the lights.  That worked and am sorry I didn't see / follow the previous widget discussion. Thank you for your pateince and assistance. 

Protocal question: should I know close this issue?

**Comment by mikejolley** [comment]
I can :)

**Comment by davefaloon** [comment]
Thx M. appreciate you

**Comment by f3bruary** [comment]
Sorry for bringing up a closed issue. "Uncategorized" in showing in my footer widget. But "Hide Empty Categories" is enabled. In the category page, the product counter is showing '1' implying there is 1 product assigned to this category, but when I click it, it seems to be empty after all. So there is no product assigned to this category and I think that's why it won't hide from the widget.

Any suggestions are appreciated :)

**Comment by WPprodigy** [comment]
Best to ask for support here: https://wordpress.org/support/plugin/woocommerce

Else if you can replicate this problem using only WooCommerce and a core WordPress theme, you can open up a new Github issue.

Thanks.

**Comment by jgiesler** [comment]
f3bruary,
Did you ever figure out the solution to your problem?

> In the category page, the product counter is showing '1' implying there is 1 product assigned to this category, but when I click it, it seems to be empty after all. 

I'm having the same issue and not sure how to solve it. There are no uncategorized products but the backend shows a count of 2. You filter for uncategorized products but nothing comes up.

**Comment by f3bruary** [comment]
@jgiesler It was quite a while ago. I just checked and it 0 now. If I recall correct, I did it the hard way. Dig into the database and find which product_id is assigned to that specific category_id. Then remove it. If you're gonna try this out, then make sure to backup the database first.

**Comment by nowarah** [comment]
I have the same issue and I'm not using any widgets, is there a way to solve it ?
