### ISSUE TITLE
Isle of Man Shipping issue: "State / County" required but they don't have one

### ISSUE THREAD

**Issue by bdetail** [woocommerce/woocommerce#18932]
Hi, 

We have a customer from the Isle of Man who is having issues with the shipping address. 
WooCommerce shows a red asterix beside "State / County" but they don't have one on the Isle of Man. Is it possible to remove this requirement by means of a function?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18934
