### ISSUE TITLE
Variations endpoint should ensure parent ID is correct

### ISSUE THREAD

**Issue by luisfmelo** [woocommerce/woocommerce#18933]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Imagine we have a product with id 1. This product is variable and have 4 variations with variation id = 2, 3 and 4

I want to update stock of variation 4. I have to do the following:

**PUT** request to: /api/product/1/variation/4

But, because of some error, I made this request:

**PUT** request to: /api/product/4/variation/4

Expected Result:
**Code 404**: Woocommerce was not able to find a product with id 4

Actual Result:
**Code 200** 
And now, product id 1 only have 2 variations with id 2 ND 3.
Variation id 4 is now a variation without product and can not be found in woocommerce

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by claudiosanches** [comment]
See #19097
