### ISSUE TITLE
Fixed cart discount coupon codes do not work on custom priced products

### ISSUE THREAD

**Issue by rahuladams** [woocommerce/woocommerce#18930]
While WooCommerce lets you have a custom price for the product while it's being added to cart using "woocommerce_before_calculate_totals", the system still calculates the subtotal using the original price while it checks the coupon code against cart totals.

This creates an issue when the coupon code has to work on orders above a certain amount. If the original price is less than the required subtotal, the coupon will throw an error even if the custom price is valid for the offer.

**Comment by mikejolley** [comment]
The discount class uses `get_displayed_subtotal` to check against the coupon's option.

The cart calculation class has a method called `calculate_item_subtotals` which does the subtotal calculation, using the product `get_price` method.

If you custom code does not change the product, and thus `get_price` method does not return your adjusted prices, the subtotal and all future calculations will be incorrect.

You've not provided sample code nor the version you're testing against, but I'd suspect it's not working early enough or not adjusting the product prices correctly. If the actual subtotal in the cart is wrong, you can expect the coupon logic to be wrong also.

**Comment by rahuladams** [comment]
in my function where I tweak the code product price, I am also setting the price of the product using `set_price()` function.

`if( isset( $value["custom_price"] ) ) {
                $custom_price = $value['custom_price'];
                $orgPrice = floatval( $value['data']->price );
                $value['data']->set_price( $custom_price );
 }`

Also if I echo `get_displayed_subtotal()`, it shows the cart amount considering the custom product price, not the subtotal using the original product price.

Am I supposed to do anything else here?

**Comment by mikejolley** [comment]
Provide the full code so we can see what happens?

**Comment by rahuladams** [comment]
@mikejolley 
1. The custom price is calculated from the Product Single page and sent to function using ajax.
2. The next function takes the custom value from the woocommerce session, which is `$value["custom_price"]`.

`function custom_pricing( $cart_object ) {  
    if( !WC()->session->__isset( "reload_checkout" )) {
        foreach ( $cart_object->cart_contents as $key => $value ) {  
            if( isset( $value["custom_price"] ) ) {
                $custom_price = $value['custom_price'];
                $value['data']->set_price( $custom_price );
            }
        }   
    } 
}
add_action( 'woocommerce_before_calculate_totals', 'custom_pricing', 99 );`

So, would `calculate_item_subtotals` still calculate the price with the original product price? `get_displayed_subtotal `as I mentioned in the previous comments gives me the subtotal based on the custom price.

**Comment by mikejolley** [comment]
Hard to say without working code in front of me. Why not see for certain what values are used https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-discounts.php#L620 - error log it and compare? See if it's running multiple times? See if it happens before your hook runs?

**Comment by rahuladams** [comment]
@mikejolley Thanks for url and I have fixed the issue by comparing the file you have shared the my version. Despite the fact both showed "@since  3.2.0" the code that I had in that file where it validates the coupon against the subtotal was different. That was causing the issue.
