### ISSUE TITLE
Disabled variations are now visible

### ISSUE THREAD

**Issue by Luminus** [woocommerce/woocommerce#18942]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a Variable Product with 4 variations
2. Deselect the **Enabled:** checkbox on all but one of these variations
![disable](https://user-images.githubusercontent.com/248077/36098934-ba8bfba8-0ff8-11e8-8075-36601957c2a8.jpg)
3. Publish the Product

## Expected/actual behaviour

When I follow those steps, I see the disabled variations still present in the drop-down selector. Selecting one of the disabled variations shows a message letting the customer know that the variation is unavailable.
![not-hiding](https://user-images.githubusercontent.com/248077/36099086-531ecaf8-0ff9-11e8-9e69-910c8ad3e884.jpg)

I was expecting to see only the enabled variation so that customers don't have to bother with variations that they are not able to purchase. This is the behaviour that was present in version 3.2.6.
![hidden](https://user-images.githubusercontent.com/248077/36099145-81ebbee0-0ff9-11e8-91ce-6935dc3ac4a7.jpg)

Variable products created or updated before upgrading WooCommerce to 3.3.1 maintain the expected behaviour but once they are updated or created afresh in 3.3.1 they present the same issue.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18908

**Comment by aaronhong7** [comment]
I still have this issue, where "disabled" product variations on my product admin panel is visible (but greyed out and not clickable by a plugin).

I disabled the plugin and it went by to the "drop-down list" style, but still, the "disabled" product variation is visible and clickable.

My Woocommerce version is 6.4.1.

In the file includes/class-wc-product-variable.php, line 306 - 309:
`			// Filter 'woocommerce_hide_invisible_variations' to optionally hide invisible variations (disabled variations and variations with empty price).
			if ( apply_filters( 'woocommerce_hide_invisible_variations', true, $this->get_id(), $variation ) && ! $variation->variation_is_visible() ) {
				continue;
			}`

Hope that someone can help...
