### ISSUE TITLE
WooCommerce 3.3.1 killed WooCommerce Cart Notices

### ISSUE THREAD

**Issue by calendarboy** [woocommerce/woocommerce#18948]
After installing WooCommerce 3.3.1, much of my web site was unrecognizable.

One of the several problems is that Cart Notices no longer works. I did a search here on GitHub and found nothing about this. Thought you should know. 
Cart Notices Version 1.8.2

**Comment by claudiulodro** [comment]
I just tried the plugin and it worked fine for me. I recommend [contacting support](https://woocommerce.com/my-account/tickets/) and they can help troubleshoot it further and they can also follow up with the developers of Cart Notices if needed.
