### ISSUE TITLE
Product filter on admin area not working

### ISSUE THREAD

**Issue by AbdulSamadKt** [woocommerce/woocommerce#18940]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. On products list page in admin area, select a category from dropdown
2. Click 'Filter' button and this time result shows "No products found"
3. Click once more 'Filter' button and it is working. Again not working on the odd tries.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

`
### WordPress Environment ###

Home URL:
Site URL: #
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.25-0ubuntu0.16.04.1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.20
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 278.13MB
Database Data Size: 161.30MB
Database Index Size: 116.83MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.44MB + Index: 0.16MB
wp_woocommerce_order_itemmeta: Data: 3.52MB + Index: 4.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.30MB + Index: 0.30MB
wp_comments: Data: 5.52MB + Index: 8.09MB
wp_cpk_wpcsv_export_queue: Data: 0.00MB + Index: 0.00MB
wp_cpk_wpcsv_log: Data: 0.00MB + Index: 0.00MB
wp_cp_feeds: Data: 0.02MB + Index: 0.00MB
wp_emailalertpro: Data: 0.05MB + Index: 0.00MB
wp_laybuy_response: Data: 0.02MB + Index: 0.00MB
wp_laybuy_revision_reports: Data: 0.02MB + Index: 0.00MB
wp_layerslider: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_NativeEmail_sentlist: Data: 0.05MB + Index: 0.00MB
wp_nativeemail_sentlist_settings: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 5.48MB + Index: 1.47MB
wp_pinterest_automatic: Data: 0.05MB + Index: 0.00MB
wp_postmeta: Data: 107.66MB + Index: 87.30MB
wp_posts: Data: 29.55MB + Index: 8.06MB
wp_ps_exclude: Data: 0.02MB + Index: 0.02MB
wp_ps_keyword: Data: 0.02MB + Index: 0.00MB
wp_ps_postmeta: Data: 0.16MB + Index: 0.17MB
wp_ps_posts: Data: 0.25MB + Index: 0.09MB
wp_ps_product_categories: Data: 0.02MB + Index: 0.03MB
wp_ps_product_sku: Data: 0.14MB + Index: 0.11MB
wp_ps_product_tags: Data: 0.02MB + Index: 0.03MB
wp_ps_term_relationships: Data: 0.16MB + Index: 0.11MB
wp_rac_abandoncart: Data: 0.02MB + Index: 0.00MB
wp_rac_email_logs: Data: 0.02MB + Index: 0.00MB
wp_rac_templates_email: Data: 0.02MB + Index: 0.00MB
wp_revslider_css: Data: 0.02MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_settings: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.05MB + Index: 0.00MB
wp_revslider_slides: Data: 0.06MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.09MB + Index: 0.11MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.36MB + Index: 0.30MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 3.52MB + Index: 5.03MB
wp_users: Data: 0.41MB + Index: 0.41MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wdpr_payment_recipes: Data: 0.02MB + Index: 0.00MB
wp_wdpr_payment_recipes_schedule: Data: 0.02MB + Index: 0.00MB
wp_wdpr_payment_rules: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 2.02MB + Index: 0.00MB
wp_wpeditor_settings: Data: 0.02MB + Index: 0.00MB
wp_wpmudev_chat_log: Data: 0.02MB + Index: 0.06MB
wp_wpmudev_chat_message: Data: 0.02MB + Index: 0.11MB
wp_wpmudev_chat_users: Data: 0.02MB + Index: 0.06MB
wp_wpp_deposit_records: Data: 0.02MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.06MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.39MB + Index: 0.20MB
wp_yoast_seo_meta: Data: 0.13MB + Index: 0.00MB

### Post Type Counts ###

attachment: 22214
dt_gallery: 3
dt_slideshow: 3
dt_testimonials: 10
nav_menu_item: 101
page: 116
post: 5
product: 2787
product_variation: 7
pys_fb_event: 2
revision: 110
shop_coupon: 6
shop_order: 3991
shop_order_refund: 7
shop_quote: 100
sidebar: 5
tooltips: 1
vc4_templates: 10
wc_product_tab: 2353

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #32 - /artgallery/
Cart: #33 - /cart/
Checkout: #34 - /checkout/
My account: #35 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

</details>

**Comment by mikejolley** [comment]
![2018-02-12 12 44 03](https://user-images.githubusercontent.com/90977/36097337-77e73cbe-0ff2-11e8-8729-5fecbc7abf0b.gif)

Seems fine on clean install.

**Comment by AbdulSamadKt** [comment]
**The difference in url is:**
**When working:**   /wp-admin/edit.php?post_status=all&post_type=product&product_cat=just-arrived&product_type&stock_status&filter_action=Filter&paged=1
**When not working**   /wp-admin/edit.php?s&post_status=all&post_type=product&action=-1&product_cat=just-arrived&product_type&stock_status&filter_action=Filter&paged=1&action2=-1


's&' is more in URL when not working

**Comment by AbdulSamadKt** [comment]
Also When using WooCommerce 3.2.6 with the same condition, there are no issues.

**Comment by mikejolley** [comment]
Can you search your plugins sourcecode for `action2`?

**Comment by AbdulSamadKt** [comment]
The action2 is from WordPress itself. The class-wp-list-table.php in wp-admin -> includes folder is using the following code:

/**
	 * Get the current action selected from the bulk actions dropdown.
	 *
	 * @since 3.1.0
	 *
	 * @return string|false The action name or False if no action was selected
	 */
	public function current_action() {
		if ( isset( $_REQUEST['filter_action'] ) && ! empty( $_REQUEST['filter_action'] ) )
			return false;

		if ( isset( $_REQUEST['action'] ) && -1 != $_REQUEST['action'] )
			return $_REQUEST['action'];

		if ( isset( $_REQUEST['action2'] ) && -1 != $_REQUEST['action2'] )
			return $_REQUEST['action2'];

		return false;
	}

**Comment by AbdulSamadKt** [comment]
I have found the problem occurs only when hosting with Wp Engine and using more than 2500 products. So with Wp Engine's must use plugins and latest WooCommerce is creating the problem.
