### ISSUE TITLE
WC 3.3.1 image sorting doesn't work

### ISSUE THREAD

**Issue by calendarboy** [woocommerce/woocommerce#18949]
Showing products on my site's home page, the images are not in order. 

Page has:
<p style="text-align: center;">[product_category category="current-calendars" per_page="21" columns="3"  orderby="Menu order" order="asc"]</p>
This has worked fine for months, but now the images don't reflect the Menu numbers at all.

**Comment by WPprodigy** [comment]
`orderby="Menu order" ` isn't valid. Try `menu_order`.

**Comment by mikejolley** [comment]
Menu order has never been a valid orderby param. 

It defaults to `'menu_order title'` so you can just leave it out.
