### ISSUE TITLE
POST Customer returns Invalid signature - provided signature does not match.

### ISSUE THREAD

**Issue by serialbandicoot** [woocommerce/woocommerce#18945]
Hello I am using WooCommerce API - Node.js Client https://www.npmjs.com/package/woocommerce-api

And I am trying to create a customer which requires a POST request to the server. Here is the code to initialize woocomerece REST API:

var WooCommerceAPI = require('woocommerce-api');

var WooCommerce = new WooCommerceAPI({
  url: 'http://example.com',
  consumerKey: 'ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  consumerSecret: 'cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  wpAPI: true,
  version: 'wc/v2'
});
This is the code to Create customer:

  var data = {
  email: 'john.doe@example.com',
  first_name: 'John',
  last_name: 'Doe',
  username: 'john.doe',
  billing: {
    first_name: 'John',
    last_name: 'Doe',
    company: '',
    address_1: '969 Market',
    address_2: '',
    city: 'San Francisco',
    state: 'CA',
    postcode: '94103',
    country: 'US',
    email: 'john.doe@example.com',
    phone: '(555) 555-5555'
  },
  shipping: {
    first_name: 'John',
    last_name: 'Doe',
    company: '',
    address_1: '969 Market',
    address_2: '',
    city: 'San Francisco',
    state: 'CA',
    postcode: '94103',
    country: 'US'
  }
};

WooCommerce.post('customers', data, function(err, data, res) {
  console.log(res);
});
But I keep getting the following response from server.

{
"code":"woocommerce_rest_authentication_error",
"message":"Invalid signature - provided signature does not match.",
"data":{"status":401}
}

However any GET request works on the server eg: I can get the list of products or categories. I'm in test so currently using http.

**Comment by mikejolley** [comment]
We have a doc for connection issues/server issues https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#common-connection-issues 

Please bare in mind Github is only for bug reports. Not support questions like above.

Thanks

**Comment by serialbandicoot** [comment]
Thanks @mikejolley for the response. BTW - is there a slack style forum for help?

**Comment by mikejolley** [comment]
There is the WooCommerce slack community and a developer room. https://woocommerceslack.herokuapp.com/

**Comment by serialbandicoot** [comment]
Brilliant thanks...

**Comment by waggyman** [comment]
@mikejolley I also get that `provided signature does not match`. I also already checked the mentioned wiki above. Already follow the instructions but still give me that error.

`http://arigi.onlinestore.id/wp-json/wc/v2/products?oauth_consumer_key=ck_aa48ca7bb5cd0c54199b346c86e22226fa4d2c9c&oauth_nonce=ce700b2eb2e1771536f6fbbf207e1d9f34319499&oauth_signature=uJU8B6uVuvTY2Rq51G%2FD0eTPPmiLQVKIhPg1ScpPIJc%3D&oauth_signature_method=HMAC-SHA256&oauth_timestamp=1530854618`

that's the requested url.

**Comment by lylesback2** [comment]
I found a solution to my problem and the signature not matching.
I am using PHP 7.3, cURL (for my requests), WooCommerce v3, and http domain.

The signature was not matching the signature created here
/includes/class-wc-rest-authentication.php
`if ( ! hash_equals( $signature, $consumer_signature ) ) { // @codingStandardsIgnoreLine
			return new WP_Error( 'woocommerce_rest_authentication_error', __( 'Invalid signature - provided signature does not match.', 'woocommerce' ), array( 'status' => 401 ) );
		}`
My base string looked like this:
`POST&http://mystore.com/wp-json/wc/v3/products&oauth_consumer_key...&oauth_nonce=...&oauth_signature_method=...&oauth_timestamp=...`
but the signature still wasn't matching.
WooCommerce is appending "&q=/wp-json/wc/v3/products" to the end of the parameters, so overwrite this:
`POST&http://mystore.com/wp-json/wc/v3/products&oauth_consumer_key...&oauth_nonce=...&oauth_signature_method=...&oauth_timestamp=..&q=` (leave it blank)

and your cURL url should look like this:
`http://mystore.com/wp-json/wc/v3/products?q=`

**Or just use HTTPS.**
