### ISSUE TITLE
Search in administration

### ISSUE THREAD

**Issue by NytPust** [woocommerce/woocommerce#18943]
Hi after the lates update of woocommerce the search in backend dosent work proberly. If I try searching for a product by the item number the search will not find the product. 
![2018-02-12_li](https://user-images.githubusercontent.com/36410869/36101082-9c5aa156-1008-11e8-91a6-cb5ab09b1e3c.jpg)
![2018-02-12](https://user-images.githubusercontent.com/36410869/36101083-9c971762-1008-11e8-971b-ec6721d7b876.png)

**Comment by NytPust** [comment]
![2018-02-12 1 _li](https://user-images.githubusercontent.com/36410869/36101143-c2974964-1008-11e8-9ed1-139b4c9ed6b7.jpg)

**Comment by GlennMartin1** [comment]
That's a known issue - it's set to be corrected in the upcoming WC 3.3.2.
