### ISSUE TITLE
New category uncategorized – why?

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#18953]
Hi, I updated two different sites to WC 3.3.1 and found under product categories a new one with title Uncategorized. For what is it?

On site I have only few products which do not need any category. But they are now linked to default cat. That resolves in case of Storefront, that if I use as first page the homepage template, it displays the category list with only Uncategorized as cat. Removing with a hook was not possible:

`remove_action( 'homepage', 'storefront_product_categories', 70 );`

**Comment by mikejolley** [comment]
All products have a cat from 3.3. It helps with filtering in admin. You can rename it, and there are snippets floating around to hide it from frontend if desired.

3.3.2 will let you change default cat. 

Thanks

**Comment by Babelfisch** [comment]
Very stange behavior! I have some products without category (the don't need some) and there is no reason why WC invents a new category. Why do you not let the shop owner deciding which categories needed?

**Comment by mikejolley** [comment]
@Babelfisch it can be reassigned/removed
