### ISSUE TITLE
Automated refund handling eligibility should be exposed via REST API

### ISSUE THREAD

**Issue by callumstrubi** [woocommerce/woocommerce#18951]
Use case:
When checking an order, you can query the payment method. The payment method can be queried but at no stage can I query whether a refund can be processed automatically or not. If you issue a refund where you request automated payment gateway refund processing and the feature is not available with the customer's chosen gateway, the refund fails entirely. If this information was exposed over the API we could pre-mitigate this issue in external applications that interface with the woo commerce API.

I can see two possible resolutions: 
1. When submitting a refund request over the API, allow the request to succeed even if automatic payment gateway refunding was requested despite it not being available. 
2. Display in the payment gateway REST response whether it is eligible for automatic payment gateway refund.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Query the REST API for payment methods

## Expected/actual behavior

When I follow those steps, I see...

No reference to whether an automated refund can be processed

I was expecting to see...

Whether automated refunds could be processed with that gateway or not.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Not relevant
```
</details>

**Comment by mikejolley** [comment]
Logged here for v3 https://github.com/woocommerce/wc-api-dev/issues/87 since this is an addition/schema change.
