### ISSUE TITLE
Why is "wp-content" hard-coded into the path check?

### ISSUE THREAD

**Issue by richbishop** [woocommerce/woocommerce#18958]
When you're checking if a file exists you should be using the CONTENT_DIR constant rather than hard coding "/wp-content"

https://github.com/woocommerce/woocommerce/blob/99f58c4c56935516bedaca32759b77086f3b3152/includes/class-wc-product-download.php#L99

**Comment by mikejolley** [comment]
Not solved by https://github.com/woocommerce/woocommerce/pull/18959 Should see if there is a way to remove hardcoded value.

**Comment by claudiulodro** [comment]
Should use [WP_CONTENT_DIR](https://github.com/WordPress/WordPress/blob/1ae9491548e64e66c3283c97dd082a691fa57e08/wp-includes/default-constants.php#L66)
