### ISSUE TITLE
Horizontal scrolling at order preview

### ISSUE THREAD

**Issue by alfonsberger** [woocommerce/woocommerce#18968]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Open preview of orders with a subscription in Safari 11.0.3
2. 
3.

## Expected/actual behavior

When I follow those steps, I see horizontal scrolling of the order items

I was expecting to see no scrolling at all

<img width="469" alt="bug-scrolling" src="https://user-images.githubusercontent.com/21140914/36222893-06ec0a62-11c3-11e8-903e-cfde58ba4c4e.png">

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`

`
```
</details>

**Comment by mikejolley** [comment]
Is it caused by the data in the product column or extra headers/non english?

Mine:

![rollback local wordpress dev wordpress 2018-02-14 18-44-53](https://user-images.githubusercontent.com/90977/36223201-8e764d24-11bb-11e8-85a9-21aa835de44d.png)

It it doesn't fit horizontally, scrolling would be preferred over hiding data or reducing font sizes etc.

**Comment by alfonsberger** [comment]
It looks like the data in the product column as with regular products it works fine. With woocommerce subscriptions there is always more information to show

Why not make the preview popup wider depending on content? If you have mixed orders you have to scroll now horizontally and vertically!

**Comment by alfonsberger** [comment]
<img width="434" alt="bug" src="https://user-images.githubusercontent.com/21140914/36228179-d32f5d12-11d3-11e8-93c4-3ad4ebf50ea3.png">
Another issue is the misalignment of the buttons which I guess is from the translation. And hard to see in this screenshot. This is a single order with a longer product text, which is cut of. Meaning you can not scroll down to see the full description.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18976
