### ISSUE TITLE
Dollar Currency encoding issue on Order Creation

### ISSUE THREAD

**Issue by ayushsingh007** [woocommerce/woocommerce#18963]
There is an issue with woocommerce currency code encoding. In a helper module I am overriding WC_Cart class, it's cart is working fine, checkout is working fine but the issue comes on create order.
Woocommerce create order is unable to encode ( $ ) dollar currency though working for all other currency.

Case :-

cart_total => 24, order_total => 3624
cart_total => 108, order_total => 36108

Since, "&#36" is dollar encoding, so 36 get appended causing 36K increase in total amount. It's a serious issue with dollar sign encoding please resolve it.

**Comment by kloon** [comment]
The currency is just a prefix setting to the amounts, you should not be passing the currency when dealing with amounts but only use numeric values.

**Comment by ayushsingh007** [comment]
I am not passing amount with currency, I am just updating the product price and let woocommerce order create function handle everything thereafter. Also, if I was passing currency with amount then it should cause issue with every other order creation, but the issue comes only when using dollar currency.

**Comment by kloon** [comment]
Can you please complete the issue list as requested when you opened the issue? This is likely caused by a 3rd party plugin or custom code. WooCommerce core does not have any issues with encoding when creating orders, I have just tested this with the latest version as well as the master branch version.
