### ISSUE TITLE
HELP! Woocommerce checkout 'invalid email'' when checking out as guest

### ISSUE THREAD

**Issue by IhaveNoLive** [woocommerce/woocommerce#18962]
It is really important. i am opening in a few days and guests can't checkout if they are not logged in. also if they register at the checkout page, you can only buy by registering at my account then buy. This is a major error! i will show you my checkout pages and the error. If you click enter, the page just freezes, gets white and gives an error invalid email.

Photos:

![2018-02-14 13_10_22-woocommerce checkout form designer mpgta recovery wordpress](https://user-images.githubusercontent.com/36475838/36203621-739b0860-1188-11e8-87ff-41f60d77e08c.png)

![2018-02-14 13_08_38-checkout mpgta recovery](https://user-images.githubusercontent.com/36475838/36203635-80f633d6-1188-11e8-9223-540cbca220cc.png)

![2018-02-14 13_10_10-woocommerce checkout form designer mpgta recovery wordpress](https://user-images.githubusercontent.com/36475838/36203623-779b6f04-1188-11e8-9530-59d9bb921d45.png)

**Comment by mikejolley** [comment]
These are custom checkout fields. This is not core - you've made customisations.

**Comment by mikejolley** [comment]
Looks like you've removed the actual billing_email field via your customisation. This is not a core bug,
