### ISSUE TITLE
Stock Count doesn’t decrease after PayPal or MercadoPago payment. 

### ISSUE THREAD

**Issue by alsepulveda91** [woocommerce/woocommerce#18960]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. 
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by alsepulveda91** [comment]
Sorry It posted by mistake with out explaining the problem.

I am getting crazy because I am having problems with the stock manager from woocommerce.

When I have any product with the activated stock the product doesn’t decrease when some one buys it, we have noticed that this problem has been happening when we buy the product by PayPal or MercadoPago because if we buy the product from any other method, the product does reduce and hide from showing, that is what we want from PayPal and MercadoPago

**Comment by WPprodigy** [comment]
What is the order status of these orders that aren't reducing stock? Stock is typically reduced at the "processing" / "completed" order status. 

If the order status is staying at pending payment / on hold, then your website isn't hearing back from the gateway that payment was received.

With PayPal, this is known as an IPN issue: https://docs.woocommerce.com/document/paypal-standard/#section-21

**Comment by mikejolley** [comment]
+1 this is likely MercadoPago issue. You can test with other gateways to confirm stock reduction is fine.
