### ISSUE TITLE
Track Payment Gateways class instance and initiate only once

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#18977]
The same way the WooCommerce class has a mechanism to make sure only one instance of the class is loaded, the payment gateways classes should have the same mechanism.

On a payment gateway that I developed I sometimes need to access some class functions or variables before WooCommerce has loaded the payment gateways and if by some reason, WooCommerce also instantiates the class afterward on the same runtime, hooks (actions and filters) will be attached again and some strange behavior can occur.

For now, I've added an increment variable to the __construct function of my payment gateway and I only init the hooks if the counter equals 1, but it feels like a hack.

I already implemented a similar mechanism to the one used in the WooCommerce class, and I always call my class by a function that will check for an instance. The problem is that class-wc-payment-gateways.php doesn't do the same:
`$load_gateway = is_string( $gateway ) ? new $gateway() : $gateway;`

I propose that the instance() function is implemented on all the built-in gateways and that on class-wc-payment-gateways.php we try to call it, instead of simply call "new $gateway()".

This, of course, should be done in a retro-compatible way, so those payment gateways that still don't have the instance() function will still be correctly loaded on class-wc-payment-gateways.php

**Comment by mikejolley** [comment]
> On a payment gateway that I developed I sometimes need to access some class functions or variables before WooCommerce has loaded the payment gateways and if by some reason

Why do you need to put all of your methods into the gateway class? Why does the gateway class need to change to cater for your usage?

I'm not saying 1 instance is a bad idea, I'm just wondering why core has to change to cater for the way you've written your gateway. Any changes to gateways, even if we *think* it's done "in a retro-compatible way", seem to cause conflicts with 3rd party code.

**Comment by webdados** [comment]
You are right: I possible do not need to have all my methods inside the payment gateway class.
I'll try to remove from the gateway class everything I need to use outside the scope of the payment itself.

Still, as you said, it's not a bad idea :-)

**Comment by mikejolley** [comment]
I'll label this as an idea and perhaps revisit when we're planning on doing a major release. I don't want to break existing gateways - there are hundreds of them :) 

If you want to try doing this in the meantime, would be happy to review a PR if you're confident it's safe :p
