### ISSUE TITLE
Coupon values not applied anymore after manually updating order in WP Admin

### ISSUE THREAD

**Issue by s-a-s-k-i-a** [woocommerce/woocommerce#18975]
This issue is related to orders, where coupons have been applied to cart total.
When updating f.e. billing email address in WP Admin of above mentioned orders, then clicking update button, we can still see the coupon codes that were applied to the order, BUT the value was set to 0 and thus order total is incorrect afterwards.
We have to manually set a new discount to get the correct order total back to be able to re-send a correct order confirmation email to the customer. Somehow coupon discounts get ignored on updating an order manually.

Is this a bug? Or some setting?

**Comment by mikejolley** [comment]
You haven't really provided enough detail for this to be reproduced. The new issue page lists everything we need (!).

>  where coupons have been applied to cart total.

Extension I assume? When you update an order, totals will be summed/recalculated. If the totals were not stored correctly to the order, the values will not add up again in the same way.

Tested with a fixed cart discount of 10 and totals did not change. So I'm guessing the extension doing the discount is not doing it the same way core does (core splits discounts across item costs).

**Comment by s-a-s-k-i-a** [comment]
Thanks for the hint! will report to extension plugin developer!
