### ISSUE TITLE
Woocommerce issue after updates

### ISSUE THREAD

**Issue by tudonanet** [woocommerce/woocommerce#18978]
Hello, i’ve updated everything, and I still have an issue. my catalog display is broken, see these pages:

https://reinalab.net.br/

https://reinalab.net.br/categoria-produto/anatomia/ (both are with double images on product’s display, and a broken layout)

And the product page are different from before, it seems to be broken too:

https://reinalab.net.br/produto/vibria-aparelho-terapia-combinada/ 

Please, really need a help!

![issue1](https://user-images.githubusercontent.com/36506315/36258243-25120d10-1241-11e8-987a-cef0f3c7c285.jpg)

**Comment by mikejolley** [comment]
This is a theme or extension. Something is inserting a `product-thumb-secondary` thumbnail which is not from WooCommerce itself.
