### ISSUE TITLE
Importing variation does not automatically fill the variation size 

### ISSUE THREAD

**Issue by karamrajab** [woocommerce/woocommerce#18989]
[variation_sample (1).xlsx](https://github.com/woocommerce/woocommerce/files/1729341/variation_sample.1.xlsx)

I am facing a bug with import suite for woocommerce. I am trying to upload varations for a product (variation is already defined as global named: carpet size ) 

the variation is not automatically selected (the right size is not corresponding to the right price) and I have to manually select each carpet size even tho it's mentioned in the variation file.. 

![screen shot 2018-02-15 at 11 53 19 pm](https://user-images.githubusercontent.com/36519428/36280571-bd54b7de-12ab-11e8-89e6-47b4c0f88464.png)

[woocommerce-sample-products test .xlsx](https://github.com/woocommerce/woocommerce/files/1729327/woocommerce-sample-products.test.xlsx)

**Comment by WPprodigy** [comment]
You are importing variable products, but not variations. https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

**Comment by kloon** [comment]
Missing variations in the import file, variable products needs a variable line as well as several lines for each variation.

**Comment by karamrajab** [comment]
[variation_sample (1).xlsx](https://github.com/woocommerce/woocommerce/files/1730677/variation_sample.1.xlsx)


this is the variation file which I uploaded later on but still did not work.. I get the variation drop down menu  (not selecting the right size) like the image above... 

I uploaded twice so now I have double variations so I need to somehow remove or overwrite the old variations.. 

any idea? or what needs to be fixed

**Comment by WPprodigy** [comment]
Why is the post status set to draft for the variations, and why don't they have a post type of variation?

Please refer to this guide: https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

And to the CSV sample: https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv
