### ISSUE TITLE
Improve the naming of meta_key

### ISSUE THREAD

**Issue by rvola** [woocommerce/woocommerce#18988]
Hello team,

I am currently working on doing some PR for the extension: [WooCommerce Gateway Stripe](https://github.com/woocommerce/woocommerce-gateway-stripe).

I noticed that the extension uses a bad practice for naming meta_key.
For example: "**Stripe Fee**" or "**Net Revenue From Stripe**"

The extension has no class Updater, I sent a PR [#545](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/545)
to validate the update and in particular the change of meta_key name.

@roykho, sent me back to you because it uses the same nomenclature as for the IPN of Paypal that you integrate here: https://github.com/woocommerce/woocommerce/blob/master/includes/gateways/paypal/includes/class-wc-gateway-paypal-ipn-handler.php#L210

He solicits me to ask you for this change, which by equivalence, will return to the extension.

You will probably tell me, why do you want to do this?
All in all because:
- it's a better way to not use spaces in the names of meta_key
- it will allow (project in progress) to be able to add the gateway comissions in the WooCommerce graph. I worked on this here, and I have to use a tweak to be able to use the query normally [get_order_report_data](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/reports/class-wc-admin-report.php#L75) / [For example here I tweak the query](https://github.com/rvola/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-reports.php#L143)

My work for integrating commissions into charts is here: https://github.com/rvola/woocommerce-gateway-stripe/tree/master

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

**Comment by rvola** [comment]
I will add that I have not found a WordPress Codex link that explicitly states that you should not use capital letters or spaces.

However no WordPress meta_key and a large amount of extensions on the market uses PEAR conventions.

**Comment by mikejolley** [comment]
@rvola There are no set limitations on how meta keys should or should not be formatted.

Generally, if something is meant to be used by the system and hidden from the user we use lowercase, underscores, and and underscore prefix so it's hidden from admin:

```
_my_custom_field
```

If meta is not used by the system and is there to simply be read by the merchant, we use regular text:

```
PayPal Transaction Fee
```

In the case of fees, we don't track, report, or use them anywhere in core. There is no UI to edit them, and hiding from admin is not needed. It's essentially a log.

**Comment by rvola** [comment]
Hello @mikejolley!
Yes, I understand your point of view.

However, if the user wants to display it for example in our case Stripe, we realize that the meta_key can not be used simply, for example for the translation.

I'm not trying to waste your time 😉
I bring you a feedback from experience.

Although the graphical report project is under construction, you quickly understand that the use of space simply create errors on the above mentioned queries.

Thank you in any case for your return :)
