### ISSUE TITLE
Deleted Terms and Conditions page caused PHP errors

### ISSUE THREAD

**Issue by presslayouts** [woocommerce/woocommerce#18992]
Please look click something in your cart proceed to pay with PayPal and you see the error.

https://www.silentconnect.com

http://prntscr.com/ifg4vi

Please you give us solution for this notice in checkout page when i pay by paypal. 

Regards!

**Comment by WPprodigy** [comment]
Line in question: https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/terms.php#L17

1) Do you have a page set for the terms and conditions page at WooCommerce > Settings > Checkout?

2) Have you tested to see if this happens after switching to a default WP theme and disabling all plugins except for WooCommerce?

**Comment by WPprodigy** [comment]
I found a way to replicate the error. Create and assign a terms and conditions page, then permanently delete said page.

@presslayouts As a quick fix, you just need to re-save the page at WooCommerce > Settings > Checkout.

**Comment by presslayouts** [comment]
Okay,

Thank you so much for your prompt replied.

Regards!
