### ISSUE TITLE
Admin - remove/hide product type column

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#18990]
One thing I consistently struggle with is quickly identifying what kind of product the icons represent in the Products Admin page, making them kind of useless for me:

![http://cld.wthms.co/N0bwaB](http://cld.wthms.co/N0bwaB+) 
Full Size: http://cld.wthms.co/N0bwaB

While some are clear, in general that part of the UI seems to have fallen behind. Could we either loop in FontAwesome or modify the WooCommerce font to add better visual cues? Some examples/general ideas (using FontAwesome, but I can doodle out better ones if necessary):

**Simple Product:** (I like the regular box vs. the one without lines, but really it's fine as-is)
![http://cld.wthms.co/73Ik7M](http://cld.wthms.co/73Ik7M+) 

**Grouped Product:**
![http://cld.wthms.co/JJIrp4](http://cld.wthms.co/JJIrp4+) 

**Affiliate/External:**
![http://cld.wthms.co/AIvuND](http://cld.wthms.co/AIvuND+) 

**Variable Product:**
![http://cld.wthms.co/Zhb9Of](http://cld.wthms.co/Zhb9Of+) 

**Virtual Product:**
![http://cld.wthms.co/aBvxUT](http://cld.wthms.co/aBvxUT+) 

Then if we can differentiate to add this one it'd be nice too:

**Virtual and Downloadable Product:**
![http://cld.wthms.co/yXq24E](http://cld.wthms.co/yXq24E+) 

**Physical and Downloadable Product:**
![http://cld.wthms.co/1jTVOv](http://cld.wthms.co/1jTVOv+) 

Aaaand then getting into extensions:

**Bookings:** this one is A-OK.
![http://cld.wthms.co/5sXi4w](http://cld.wthms.co/5sXi4w+) 

**Subscription:**
![http://cld.wthms.co/AoNzqh](http://cld.wthms.co/AoNzqh+) 

And so forth.

Throwin' things out there, makin' more work for everybody. ¯\_(ツ)_/¯

**Comment by mikejolley** [comment]
@kellychoffman @jameskoster Worth looking at or not? Does Store bother to distinguish product types? Is this column even useful?

**Comment by GlennMartin1** [comment]
Not useful as-is. 

+1 to improve or remove.

**Comment by WPprodigy** [comment]
Was just thinking about this earlier today.

I do find myself using this information (though tbf, I'm not the typical user). With 3+ years of using WC though, I still find myself needing to hover over the icon to understand what the type is.

Couple of thoughts:

1) If removing, we could start by just hiding it by default.
2) Using clearer icons would help, but I'd be in favor of more text based cues (like the orders page)
3) Since it is easy to filter/sort products by type on this page, removing is pretty reasonable imo.

**Comment by jameskoster** [comment]
> Does Store bother to distinguish product types?

No. 

Remove/replace with plugin imo. Or at the very least toggle the screen option off by default.

If we keep, it'd probably be best to replace the icons with text. Universally recognisable icons for product types.

Basically, I agree with Caleb!

**Comment by mikejolley** [comment]
@claudiulodro for dev chat. Make sure we're not missing anything if we remove.

**Comment by kellychoffman** [comment]
Agree with Caleb and Jay. In general, Icon only design is not helpful especially when icons are used to represent complicated terms. 

> If removing, we could start by just hiding it by default.

This is my vote, but agree we should do some basic research to identify. The dev chat is a good idea, as long as we keep in mind that the people in there only represents a smaller percentage of our user base.

**Comment by lutrov** [comment]
I've always found the icons useless and a waste of valuable screen real estate, and have filtered them out using the `manage_edit-product_columns` hook.

+1 to remove.

**Comment by michaeltieso** [comment]
I tend to hide this column as well. I never found it to be very useful. Great suggestion @DanielSantoro

**Comment by claudiulodro** [comment]
[75% of people want it removed or hidden by default](https://woocommerce.wordpress.com/2018/02/28/what-should-happen-to-the-product-type-column-on-the-admin-products-screen/). Let's remove the column and make a code snippet available for adding it back.

**Comment by nishitlangaliya** [comment]
@claudiulodro ,

> Let's remove the column and make a code snippet available for adding it back

Do you mean just comment code which is rendering column: product_type? 

In past, I did pr for remove column https://github.com/woocommerce/woocommerce/pull/19192. So is it a logical solution if yes then can I do pr by just commenting that code?

Thanks

**Comment by claudiulodro** [comment]
@nishitlangaliya not quite. In WooCommerce just remove the code like you did in #19192, do not comment it out. We will have a new plugin for adding the product type column if someone needs it.

**Comment by nishitlangaliya** [comment]
@claudiulodro ,

Thank you so much for your reply. I see #19192 reopened. So let me know if any changes required or need to submit other PR for the same.

Thanks.

**Comment by claudiosanches** [comment]
See #19192

**Comment by Garconis** [comment]
So, how do I get this back? Not sure why it wasn't just a column checkbox option within Screen Options.

**Comment by claudiosanches** [comment]
@Garconis with this plugin https://wordpress.org/plugins/woocommerce-product-type-column/
