### ISSUE TITLE
Product Sub Categories

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#18998]
Hello,

Since version 3.3.1, you changed way to show sub categories on the shop/product category page. But you didn’t add any filter which allows us to add **before** and **after** to categories section. With the **woocommerce_product_subcategories** function, we can do as below

`woocommerce_product_subcategories( array('before' => '<div>', 'after' => '</div>') );`

Please add filter to the woocommerce_maybe_show_product_subcategories function which allows us to change before and after.

Thanks!

**Comment by mikejolley** [comment]
`woocommerce_maybe_show_product_subcategories` is hooked within the product's loop (which is a UL) so adding a div here will break the layout and cause invalid markup.

Unhook this function and call the above manually where needed, with the desired markup.

```
remove_filter( 'woocommerce_product_loop_start', 'woocommerce_maybe_show_product_subcategories' );
```

**Comment by stormit** [comment]
Hi Mike,

Thank you for replying!

I know about this. But in my case, I overrided the loop-start template. I changed **ul** to **div**. Because product image and product category image are not the same size in some cases. So it does not look good. That is why I need to add product category to another section.

Best regards,

**Comment by mikejolley** [comment]
They have unique classes; why not use those to style instead of changing tags?

**Comment by danyj** [comment]
@mikejolley 

> call the above manually 

could please advise what/how to call manually.  If I unhook `woocommerce_maybe_show_product_subcategories `and output the function manually there is still no before and after , only the loop_html which is basically before. 

Only way to get the old layouts back is if we completely override the function. 

I am trying to wrap all subcategories in a container for additional styling which was a breeze before.

**Comment by mikejolley** [comment]
Unhook https://github.com/woocommerce/woocommerce/issues/18998#issuecomment-366232086 . 

Then hook a custom function elsewhere where you want the categories to show and call the relevant category output functions.
