### ISSUE TITLE
Products based on tags in woocommerce rest api v2

### ISSUE THREAD

**Issue by basanthalluri** [woocommerce/woocommerce#18996]
Is there a way to get list of all products based on tags in woocommerce rest api v2? I tried to use filter option but it don't show up any results.

https://xxxxx.com/wp-json/wc/v2/products?filter[tags]=promo&consumer_key=xxxxxxxxxxxxxxxxx&consumer_secret=xxxxxxxxxxxx

Can any suggest me how to retrieve all the products based on tags?

**Comment by mikejolley** [comment]
`tag` arg if you read the docs here https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

**Comment by adiyya** [comment]
I tried with tag arg. It works. 

Note: it is not tag=promo, it should be **tag=TAGID** it works for me

Thanks,
- Adi
