### ISSUE TITLE
WooCommerce product attributes (taxonomy) issue

### ISSUE THREAD

**Issue by s808** [woocommerce/woocommerce#19005]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. add new products
2. assign attributes
3. done

## Expected/actual behavior

When I follow those steps, I see...

Some product attributes are not clickable any more.
I was expecting to see...

Clickable attributes.

## Isolating the problem

- [ X] This bug happens with only WooCommerce plugin active 
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by s808** [comment]
![attribute-issue2](https://user-images.githubusercontent.com/36559001/36338526-93b1dcc6-1405-11e8-98d5-a80040d7a299.JPG)

**Comment by WPprodigy** [comment]
Link is missing because it's either a product-level attribute, or because the attribute doesn't have archives enabled: http://cld.wthms.co/ZU403g

**Comment by s808** [comment]
Spot on! That's right the Archive wasn't enabled for those attributes but the confusing part is that it was working before but as soon as I added a few new products the link went missing for some attributes. Not sure how that happened.

**Comment by s808** [comment]
Thank you again for resolving the issue.
