### ISSUE TITLE
[3.3.1] Impossible to filter the product search in Products list table

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#19000]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Expected/actual behavior

Polylang allows to filter the products per language (a taxonomy) in the products list table. Since the version 3.3.1, the search product input field does not allow to filter the results per language. If I have products with the search string in several languages, all products in all languages are returned. In version 3.3 and older, only the products containing the search string in the current language were returned.

The language filter works as expected as long as no search is made (other filters such as product type, product category, stock work as expected). The search works as expected for other custom post types.

Polylang uses the action 'parse_query' to add the language taxonomy to the query.
 
## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

WordPress 4.9.4, WC 3.1, Polylang 2.3.1

**Comment by mikejolley** [comment]
@Chouby See here:

https://github.com/polylang/polylang/blob/2da821faf77a6a590184a8ae6fa6e30ca8dd4cde/include/query.php#L113

If `post__in` is present, it doesn't apply it's filtering.

We use post__in when doing searches - search was switched to use our CRUD in 3.3 and handles thing like SKU searching.

Not sure why lang couldn't also be applied when `post__in` is set. Would need to ask the Polylang dev. Not fixable our side anyhow without reverting, which I don't think would be correct cause of action in this case.

**Comment by Chouby** [comment]
@mikejolley Thank you. Now I understand what is happening. The `post__in` queries are excluded from the language filter to avoid issues with other plugins. I'll look on my side how to make something specific for WooCommerce.

Have a great week-end :)
