### ISSUE TITLE
Highlight validated the T&C box on the checkout page

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce#19009]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add some products to cart and proceed to checkout.
2. Skip one of mandatory checkout form fields and click Place Order
3. Observe the field is highlighted in red.
4. Skip the T&C box and click Place Order,
5. Observe there's no highlight on this box, so the customer don't know where to look.

## Expected/actual behavior

When I follow those steps, I see the error message `You must accept our Terms & Conditions.` but no indicator of where the missing item is.

I was expecting to see some hint on where I can find the missing data.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Maybe we can try adding a border to the checkbox. @jameskoster Is that fine until we do proper checkout redesign?

**Comment by madeincosmos** [comment]
Sounds good to me 👍

**Comment by jameskoster** [comment]
Yup. Use an `outline` to avoid potentially breaking layouts.

**Comment by WPprodigy** [comment]
Outline: http://cld.wthms.co/TdYHKn

Maybe some box shadow magic instead?

**Comment by jameskoster** [comment]
How about applying the outline to the wrapper/label to include the text as well?

**Comment by WPprodigy** [comment]
Outline on the wrapper: http://cld.wthms.co/pUMOg5. Looks good? Could maybe do some left-padding, but ehh - wouldn't be wanted when not outlined, and shoudn't, but could, break layout I suppose?

**Comment by jameskoster** [comment]
That does the trick for now.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19177
