### ISSUE TITLE
Product image crop option

### ISSUE THREAD

**Issue by enventa** [woocommerce/woocommerce#19006]
Hi there!

last WC update (3.3.1) removed the ability to crop the main image of a product and I cannot understand why. It is an option I used and now all my images looks awful.

Cropping main image might be interesting when you want to fit the image in the product page layout (let's size 1:1 or 1:2 ratio) but having a more detailed image (16:9) when displaying it on the fancybox.

So my question/request is if there is any way (option/hook) to crop main image. There is a "Thumbnail cropping" option... why not a "Single image cropping" option?

Thanks!

**Comment by WPprodigy** [comment]
Filter for changing this: https://github.com/woocommerce/woocommerce/blob/1b03a80ecb4f6f59e9452522f3a64528dc4a0526/includes/wc-core-functions.php#L776

**Comment by enventa** [comment]
Thanks for your answer @WPprodigy! I have added a filter on my functions.php file on my child's theme but it seems to not be working. I have added this:

```
add_filter( 'woocommerce_get_image_size_single', my_set_product_img_size() );
add_filter( 'woocommerce_get_image_size_shop_single', my_set_product_img_size() );
add_filter( 'woocommerce_get_image_size_woocommerce_single', my_set_product_img_size() );
function my_set_product_img_size()
{
    $size = array(
        'width'  => 497,
        'height' => 530,
        'crop'   => 1,
    );
    return $size;
}
```

I'm using latest WP and latest Flatsome theme and I don't see the theme modifying that, so I cannot thing of anything preventing that filter to work. Any idea? Am I doing something wrong? Maybe I have to regenerate thumbnails (I don't think so because resized images are already there in my server...)?

Thanks!

**Comment by mikejolley** [comment]
Yes you need to regenerate thumbnails after using the above code because the dimensions/image src are stored in meta. This will be missing until you regen.

FWIW we use uncropped on single images so that ZOOM etc works as expected. It doesn't make sense to zoom on a cropped image. Ideally, you should upload product images as you want them to show on single pages. The rest of the catalog will be cropped as desired.

**Comment by ibdf** [comment]
This update broke everything. It's a classic case of don't fix what's not broken. All my product images had custom sizes, now the sizes are all wrong.
