### ISSUE TITLE
Critical Issue With Woocommerce 3.3.2: Thumbnail Image Regeneration Leads to Abnormal Spikes In CPU Usuage

### ISSUE THREAD

**Issue by gioscot** [woocommerce/woocommerce#19008]
After an analysis by my developer a woocommerce 3.3+ function which tries to regenerate all the thumbnails whenever

1. Admin tries to update thumbnails settings from Woocommerce -> Settings
2. Switch theme

Either one the events above causes a cron job to run simultaneously. A total of 1,63,000 + requests sent to the server, which my server couldn't handle. In fact, my host has limited my account at the moment and I'm working on getting it back.

I'm going to have to downgrade to 3.2.6 to fix this.

All the same, I'm truely grateful for this plugin and would appreciate it if you look into this.

Regards,
Giovanni

**Comment by mikejolley** [comment]
What makes you say these are simultaneously ran? The jobs run in sequence - 1 per image. Show us your regenerate images log, WC > status > logs.

**Comment by vannigoc** [comment]
Hi Mike, |Thanks for the swift response. I've already downgraded to woocommerce 3.2.6 and site is back to normal now  so it's clearly a woocommerce issue. 
All the same, thanks for creating something so valuable. 

Regards,
Giovanni.

**Comment by mannver14** [comment]
woocommerce 3.3.1 also have issue with order screen , when i received order after checkout then it shows blank in order screen but i received new order notification, which is not showing anything but processing, It happened after i upgraded to 3.3.1.


Regards,
mann

**Comment by vannigoc** [comment]
@mannver14 Try to see if you can sort it through other means, or just downgrade. I'd be using woocommerce 3.2.6 for the next coming months till I'm confident on upgrading.

**Comment by mikejolley** [comment]
If you don't provide the logs I requested I cannot confirm an issue/won't be able to help, and this will be closed.

**Comment by mikejolley** [comment]
This explains the feature and options available https://github.com/woocommerce/woocommerce/wiki/Thumbnail-Image-Regeneration-in-3.3-

3.3.2 has fixes for CDNs etc.

Without the log I cannot actually verify your claim the requests were simultaneous. The code runs them in sequence in the background. If you had 1,63,000 images (?), that would be 1,63,000 requests, but not all at once. cc @kloon

**Comment by mikejolley** [comment]
@gioscot You cna see above each request came in sequence. What is it the host said exactly?

**Comment by gioscot** [comment]
It's been fixed. I guess it was a plugin I was using in the development that was not compatible. Thanks! : )

**Comment by claireeisel** [comment]
@gioscot can you tell us what plug in it was? I am having this same issue with my site and not sure how to fix it :(
