### ISSUE TITLE
Sub categories not display after used woocommerce_product_loop_start function

### ISSUE THREAD

**Issue by presslayouts** [woocommerce/woocommerce#19001]
Hi,

When i used/customize  woocommerce_product_loop_start function in our customize file then not display 
sub categories of parent category. why? woo 3.2.6 version in working fine not in latest version.

http://prntscr.com/ifpazw

Please you help me to resolve this issue.

Thanks you!

**Comment by WPprodigy** [comment]
1) Does the theme declare WC support properly: https://github.com/woocommerce/woocommerce/wiki/Declaring-WooCommerce-support-in-themes ?

2) Does this happen using 3.3.2 Release Candidate?  https://github.com/woocommerce/woocommerce/releases

**Comment by mikejolley** [comment]
If you have a custom function and it doesn't call `woocommerce_product_loop_start` it won't show the categories. Don't replace functions unless you know what you're doing and have a very good reason to do so.
