### ISSUE TITLE
Checkout name & company field maximum length validation for shipping

### ISSUE THREAD

**Issue by DollyPop007** [woocommerce/woocommerce#19004]
Hi there,

I have an issue which you guys might be able to advise on. USPS international shipping allows for only 34 characters of the company name, first name and last name **combined**. Is there a way to validate the total sum of characters for all 3 of these fields doesn't exceed the limit during checkout?

**Comment by WPprodigy** [comment]
You could do that with some customization. But why not just manually trim those fields when creating a label?

**Comment by DollyPop007** [comment]
I'm using a fully automated service for shipping and keep getting this error when the amount of characters exceeds the USPS limit.

**Comment by WPprodigy** [comment]
Still think it would be best to not limit the customer's input, as it could be a blocker and cause conversion issues.

Better to trim it as necessary before it's sent out to the third party service (in the integration).

**Comment by DollyPop007** [comment]
That does sound plausible.. Thanks for your insight.

**Comment by WPprodigy** [comment]
> Could this be done automatically in the backend?

Definitely possibly, yep. Could do it either when the order is first submitted, or when your integration sends the information to the 3rd party service.

**Comment by UserName011** [comment]
I asked for similar adjustments as well but the WC policy is that they don't want to adjust the core to support more features.  Such request for example could be easily solved if they will allow in the setting to define max characters per field. That way you can limit it while other store won't limit. The control will be of the store itself.  (I assume that the following answer of the team would be that you can create a plugin that does this)

I wondn't recommend you to trim characters on your own. If customer has successfully entered 50 chars, then he expects it to be shown. You must confirm the change with him. On the other hand if you prevent this in advanced then the customer will modify his information to match the restrictions.
