### ISSUE TITLE
Date format in Orders overview is not correct in the danish translation (user profile language Danish)

### ISSUE THREAD

**Issue by mortencc** [woocommerce/woocommerce#19019]
Orders overview shows date format as attached file:

![skaermbillede 2018-02-19 kl 11 41 31](https://user-images.githubusercontent.com/36624296/36373952-fecd8dd8-1569-11e8-8538-79f8dbbd2e3a.png)

`
### WordPress Environment ###

Home URL: https://nordicbyme.com
Site URL: https://nordicbyme.com
WC Version: 3.3.1
Log Directory Writable: ✔
WP Version: 4.8.5
WP Multisite: –
WP Memory Limit: 150 MB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK

### Server Environment ###

Server Info: Apache/2
PHP Version: 5.6.33
PHP Post Max Size: 50 MB
PHP Time Limit: 180
PHP Max Input Vars: 2500
cURL Version: 7.57.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.1
WC Database Prefix: wp_
Total databasestørrelse: 17.23MB
Database datastørrelse: 12.33MB
Database indexstørrelse: 4.90MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.02MB + Index: 0.02MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_icl_cms_nav_cache: Data: 0.00MB + Index: 0.00MB
wp_icl_content_status: Data: 0.00MB + Index: 0.00MB
wp_icl_core_status: Data: 0.00MB + Index: 0.00MB
wp_icl_flags: Data: 0.00MB + Index: 0.00MB
wp_icl_languages: Data: 0.00MB + Index: 0.01MB
wp_icl_languages_translations: Data: 0.10MB + Index: 0.10MB
wp_icl_locale_map: Data: 0.00MB + Index: 0.00MB
wp_icl_message_status: Data: 0.00MB + Index: 0.00MB
wp_icl_mo_files_domains: Data: 0.00MB + Index: 0.00MB
wp_icl_node: Data: 0.00MB + Index: 0.00MB
wp_icl_reminders: Data: 0.00MB + Index: 0.00MB
wp_icl_strings: Data: 1.98MB + Index: 1.86MB
wp_icl_string_packages: Data: 0.00MB + Index: 0.00MB
wp_icl_string_pages: Data: 1.10MB + Index: 1.39MB
wp_icl_string_positions: Data: 1.26MB + Index: 0.23MB
wp_icl_string_status: Data: 0.00MB + Index: 0.00MB
wp_icl_string_translations: Data: 0.00MB + Index: 0.00MB
wp_icl_string_urls: Data: 0.00MB + Index: 0.01MB
wp_icl_translate: Data: 0.00MB + Index: 0.00MB
wp_icl_translate_job: Data: 0.00MB + Index: 0.00MB
wp_icl_translations: Data: 0.07MB + Index: 0.15MB
wp_icl_translation_batches: Data: 0.00MB + Index: 0.00MB
wp_icl_translation_status: Data: 0.01MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 1.64MB + Index: 0.09MB
wp_pakkelabel_shipping_diffrentiated: Data: 0.00MB + Index: 0.00MB
wp_postmeta: Data: 3.80MB + Index: 0.68MB
wp_posts: Data: 2.21MB + Index: 0.20MB
wp_queue: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.01MB + Index: 0.03MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 0.07MB + Index: 0.03MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wpeditor_settings: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.01MB + Index: 0.00MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 609
br_labels: 2
custom_css: 1
customize_changeset: 42
mc4wp-form: 3
nav_menu_item: 72
page: 57
post: 11
product: 102
product_variation: 217
revision: 477
shop_coupon: 2
shop_order: 26
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

WPML Multilingual CMS: af OnTheGoSystems – 3.9.3
Advanced Custom Fields Multilingual: af OnTheGoSystems – 0.7
Advanced Product Labels for WooCommerce: af BeRocket – 1.1.3 – Ikke testet med den nuværende version af WooCommerce
Coming Soon Page & Maintenance Mode by SeedProd: af SeedProd – 5.0.17
Contact Form 7: af Takayuki Miyoshi – 5.0
Envato Market: af Derek Herman – 1.0.0-RC2
Kirki Toolkit: af Aristeides Stathopoulos – 3.0.22
MailChimp for WordPress: af ibericode – 4.1.15
Meta Tag Manager: af Marcus Sykes – 2.1
One Click Demo Import: af ProteusThemes – 2.5.0
Pakkelabels.dk for WooCommerce: af Pakkelabels.dk – 1.1.11 – Ikke testet med den nuværende version af WooCommerce
Primrose: SiteOrigin Widgets: af SingleStroke – 1.3.1
Really Simple SSL: af Rogier Lankhorst – 2.5.25
SingleStroke: Post Formats: af SingleStroke – 1.2.0
Page Builder af SiteOrigin: af SiteOrigin – 2.6.2
SiteOrigin CSS: af SiteOrigin – 1.1.5
SiteOrigin Widgets Pakke: af SiteOrigin – 1.11.4
Woo Checkout Field Editor Pro: af ThemeHiGH – 1.2.5 – Ikke testet med den nuværende version af WooCommerce
WooCommerce PayPal Express Checkout Gateway: af WooCommerce – 1.5.1 – Ikke testet med den nuværende version af WooCommerce
WooCommerce Gateways Country Limiter: af OnTheGoSystems – 1.4 – Ikke testet med den nuværende version af WooCommerce
WooCommerce Multilingual: af OnTheGoSystems – 4.2.9 – Ikke testet med den nuværende version af WooCommerce
WooCommerce QuickPay: af Perfect Solution – 4.8.3 – Ikke testet med den nuværende version af WooCommerce
WooCommerce: af Automattic – 3.3.1
Yoast SEO Premium: af Team Yoast – 6.3
WP Editor: af Benjamin Rojas – 1.2.6.3
WP Instagram Widget: af Scott Evans – 2.0.2
WP Rollback: af WordImpress – 1.5
WPML All Import: af OnTheGoSystems – 2.0.4
WPML CMS Nav: af OnTheGoSystems – 1.4.22
WPML Media: af OnTheGoSystems – 2.2.3
WPML Sticky Links: af OnTheGoSystems – 1.4.3
WPML String Translation: af OnTheGoSystems – 2.7.3
WPML Translation Management: af OnTheGoSystems – 2.5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop basisside: #516 - /butik/
Kurv: #1443 - /kurv/
Checkout: #1447 - /kassen/
Min konto: #566 - /min-konto/
Handelsbetingelser: #571 - /fragthandelsbetingelser/

### Theme ###

Name: Primrose Child
Version: 1.0.0
Author URL: http://singlestroke.io/
Child Theme: ✔
Parent Theme Name: Primrose
Parent Theme Version: 1.3.4
Parent Theme Author URL: http://singlestroke.io/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
This needs fixing on the localisation itself. See https://docs.woocommerce.com/document/woocommerce-localization/ if you want to help with this.
