### ISSUE TITLE
Product Search not working

### ISSUE THREAD

**Issue by wcjonathan** [woocommerce/woocommerce#19010]
When attempting to search using the main search input products are not displayed as they are in the product loop. I have added the product_type = product hidden input to the search form, yet it is still not working.

Worked in 3.2.6, updated to 3.3.1 now broken.

**Comment by GlennMartin1** [comment]
This is a known issue which is now corrected in WC 3.3.2 RC1.

You'll see WC 3.3.2 released very soon.
