### ISSUE TITLE
Setup Wizard enhancement: Make whole "Offline Payments" row available for toggling

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#19018]
cc @jeffstieler 

Currently, when going through the setup wizard, you need to target the specific arrow in order to view the offline payment options, it would be better if that whole row would serve as a toggle:

![http://cld.wthms.co/vLzHT](http://cld.wthms.co/vLzHT+)
Link to image here: http://cld.wthms.co/vLzHT.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19035
