### ISSUE TITLE
No back button for the settings on e-mail tab

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#19014]
When you edit the settings in the e-mail tab under Woocommerce settings by clicking the cog-wheel and then the save button, there's no natural way to get back to the previous screen. You have to click the E-mail Tab again. There should be a "Go back" button or similar beside the save changes button.

I have Woocommerce 3.3.1.

**Comment by mikejolley** [comment]
Blue icon/arrow next the heading. Not that clicking the email tab again is the end of the world either :)
