### ISSUE TITLE
Term and Conditions

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#19026]
Hello,

If I add shortcode to the **Term and Conditions** page, it does not run shortcode. Please check this issue.

Thanks!

**Comment by claudiosanches** [comment]
What shortcode?
Will stop rendering any shortcode if `[woocommerce_checkout]` is included, so you need to avoid this one.

**Comment by stormit** [comment]
Hello,

We use shortcodes to build content of the Term and Conditions page, such as Visual Composer [vc_row],[vc_column], .....

Best regards,

**Comment by mikejolley** [comment]
@stormit as @claudiosanches said above. If we detect `woocommerce_checkout` shortcode on the terms page, it will not render shortcodes. This is to protect against infinite loops.

**Comment by stormit** [comment]
Hi mikejolley,

We don't add woocommerce_checkout shortcode to the terms page. I noticed that other shortcodes work, except the shortcodes of Visual Composer. Please see my screenshot [https://prnt.sc/inf09v](url)

Best regards,

**Comment by mikejolley** [comment]
Maybe Visual Composer doesn't use the WordPress system, or purposely ignores the term content.
