### ISSUE TITLE
Issue: WooCommerce + WP Staging on wordpress.com business plans

### ISSUE THREAD

**Issue by rene-hermenau** [woocommerce/woocommerce#19029]
Hey @mikejolley, @claudiosanches

 the woocommerce support team is often recommending WP Staging (https://wordpress.org/plugins/wp-staging/) plugin to their customers when they are starting support requests and the woocommerce support team needs to work on ones website.

That's working fine on selfhosted sites but WP Staging is not working on wordpress.com due to obvious write permission issues.

Is there an official way to whitelist a certain plugin like WP Staging for write permissions to the root of a wordpress.com hosted wp site or is there an API we could use for it?

I do not know any automattic code wrangler personally but as this is beneficial for automattic/woocommerce as well as for WP Staging I am trying my luck here, knowing that this is not a woocommerce issue, of course. 

So feel free to close it but if you could point me into the right direction or introduce me to someone else who works at wordpress.com it would be great.

You can contact me support@wp-staging.com or slack 
renehermi@chat.wordpress.org
https://wordpress.slack.com/messages/@U02SJDZC7

Thanks guys,
René

**Comment by mikejolley** [comment]
I think it's unlikely this will change short term because it's locked down. On .com you do have Jetpack access with rollback/backups. Thats not my area however.

If you want to chat to someone about it, Jason Johnson is one of the folks you can talk to. I think if you put in a ticket, I believe the HEs can cc'in people there. Thanks.

**Comment by rene-hermenau** [comment]
Thanks @mikejolley
