### ISSUE TITLE
[REST API] Tax on fee_lines 

### ISSUE THREAD

**Issue by amjad** [woocommerce/woocommerce#19031]
Using v3 Legacy API. I am sending this while creating a new order. The sales tax "standard" is set to 10% in settings.

```
"fee_lines": [
      {
        "title": "Fee",
        "total": 10,
        "taxable": true,
        "tax_class": "standard",
        "total_tax": 1
      }
]
```

The problem is I only see a fee line with Fee $10 and I do not see the tax applied to this beside it. What could be causing this?

**Comment by WPprodigy** [comment]
Are prices set to display tax including tax at checkout: http://cld.wthms.co/GrfWOV ? Otherwise, the fee line item's taxes will be applies to the tax line item rather than the to the fee itself.

**Comment by amjad** [comment]
both are set to excluding taxes

**Comment by WPprodigy** [comment]
Okay. So then after you add a fee with tax applies, the taxes will appear in the tax line item. For example, here is a $100 fee with 10% tax: http://cld.wthms.co/377iHe

**Comment by amjad** [comment]
Ok the fee line tax shows up only if I create another tax class and then specify that in the API. But totals are not calculating when order is created. Any way to trigger that using API?

**Comment by mikejolley** [comment]
Like the examples in the doc, legacy API requires that you leave tax_class blank (`""`) for standard tax class.

**Comment by amjad** [comment]
@mikejolley That worked, thanks. But there is an issue like I mentioned above. The total amount of the order is not updated. I have to manually click Calculate Totals and then the total is calculated properly. What can be done for this?

**Comment by mikejolley** [comment]
Calculation is manual in legacy api.

**Comment by amjad** [comment]
@mikejolley Oh. Is there any code modification I can do to have it automatically calculate? I would really like that. My application relies on legacy API at this time and upgrading is a huge under taking but is planned in the future. In the mean time, I need a fix!

**Comment by WPprodigy** [comment]
The code does exist, you're just not interested in doing the upgrade work to utilize it :/

If you'd really rather go that route, then maybe take a look at how it's implemented in the newer versions and try to copy. Else put the effort into upgrading the API version.

**Comment by amjad** [comment]
@WPprodigy It's not about the effort that goes into this. I already know how much effort and time is required and its planned along with other priorities. I use a highly customized version of WordPress / WooCommerce as a backend in a MultiSite environment with thousands of client instances communicating using the REST API with our custom iOS / Windows app. We would making the change in the next release of our apps which is a few months down the line. 

At this time, I was only looking for a quick fix for this particular issue.

**Comment by amjad** [comment]
@WPprodigy where do I need to look at to make changes for automatic calculation of totals in legacy API after order is created/updated? Thanks.

**Comment by WPprodigy** [comment]
Sorry, can't really support customizations like this.

Here is where it's being done on the latest API version: https://github.com/woocommerce/woocommerce/blob/master/includes/api/class-wc-rest-orders-controller.php#L516-L525
