### ISSUE TITLE
API V2 blank meta_data 

### ISSUE THREAD

**Issue by ered15** [woocommerce/woocommerce#19038]
QUESTION:

I'm using WC 3.2.6 - API v2 and I'm trying to get meta_data from my orders, I'm using postman to do tests I want to get the meta_data values but I get only blank info:

```
"meta_data": [
            {},
            {},
            {},
            {},
            {},
            {},
            {}
```

any solution?

**Comment by mikejolley** [comment]
You need to rule out plugin conflicts. We've seen this in the past but it's always been a 3rd party plugin messing with the API. 

Not enough info above to identify/reproduce,

**Comment by ered15** [comment]
The problem was my PHP version, i was using 5.4 and I changed it to 7.0 and it worked like it should, thanks!
