### ISSUE TITLE
Inconsistent display between breadcrumb and category widget

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#19030]
When viewing a single product page, the first category is used to determine the breadcrumb:
https://github.com/woocommerce/woocommerce/blob/3.3.1/includes/class-wc-breadcrumb.php#L148

For the Product Categories widget, the last category is used:
https://github.com/woocommerce/woocommerce/blob/3.3.1/includes/widgets/class-wc-widget-product-categories.php#L144

This produces inconsistent results depending on if the product has multiple categories or not. 

Single Category:

![](http://cld.wthms.co/171ICb+)
Image Link: http://cld.wthms.co/171ICb

Two categories:

![](http://cld.wthms.co/lZHv4I+)
Image Link: http://cld.wthms.co/lZHv4I

## Steps to reproduce the issue

1. Place Product Cat widget in sidebar
2. Select *show hierarchy* and *Only show children...*
3. View product with one category that is a child of another category, you're good
4. Add another category to the product you just viewed and view it again, breadcrumb doesn't change, but sidebar does. 

967358-zen

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19044
