### ISSUE TITLE
how can I change the text 

### ISSUE THREAD

**Issue by bandedshark** [woocommerce/woocommerce#19034]
After making the purchase and issuing the payment issues this text in cart.... - " You can not finalize your purchase while your cart is empty." ,  "Your cart is empty." 

Return to the Shop

how can I change the text below? - " You can not finalize your purchase while your cart is empty." ,  "Your cart is empty."

**Comment by WPprodigy** [comment]
Here are some guides on translating WordPress plugins:

- https://premium.wpmudev.org/blog/how-to-translate-a-wordpress-plugin/
- http://wordpress.stackexchange.com/questions/57219/how-to-translate-a-plugin-via-po-mo

Alternatively, you could use a plugin like this to translate strings: https://wordpress.org/plugins/loco-translate/, or write some custom snippets to change strings like this: http://speakinginbytes.com/2013/10/gettext-filter-wordpress/

**Comment by bandedshark** [comment]
I do not want to do a translation, can I change the message? what php page can I do?

**Comment by bandedshark** [comment]
I can not find the page in woocommerce- info

**Comment by WPprodigy** [comment]
You want to change the text, that is a translation. It doesn't matter if it's in the same language. I believe the original text is `Checkout is not available whilst your cart is empty.`. 

There is no filter or template you can override. The proper way to do this is via a translation.
