### ISSUE TITLE
Shortcode [product_page] redirecting to the actual product's page after add to cart.

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#19032]
To reproduce:

1) Add [product_page id="xx"] to your home page or another custom page.
2) Turn off add-to-cart redirect at WC > Settings > Products.
3) Add the product to your cart from the shortcoded page. Note how you were redirected to the actual product page.

Customer reports this started happening after 3.3 upgrade.

**Comment by WPprodigy** [comment]
Here is the change that caused this: https://github.com/woocommerce/woocommerce/commit/3340d5c7cc78d0a254dfed4c2c7f6f0d5645c8ba#diff-cb560f318dd3126e27d8499b80e71027

**Comment by NerminPh** [comment]
Hii,
I tried to solve the problem temporarily using the following code:
function custom_add_to_cart_redirect( $currentLink ) {
$currentLink = "https://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
return $currentLink;
}
add_filter( 'woocommerce_add_to_cart_redirect', 'custom_add_to_cart_redirect' );

but it doesn't work
Please advice!

**Comment by mikejolley** [comment]
Patch for 3.4 https://github.com/woocommerce/woocommerce/pull/19043

As a fix you can also use the following filter:

```
add_filter( 'woocommerce_add_to_cart_redirect', 'wp_get_referer' );
```

**Comment by WebDevByAlex** [comment]
@mikejolley This helped me a lot! Thanx.
