### ISSUE TITLE
Slow page load and back end with 350+ variants per listing

### ISSUE THREAD

**Issue by yorbelac** [woocommerce/woocommerce#19033]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. I adjust my functions.php to support ajax hide unavailable variant combinations in dropdowns for up to 500 variants with a snipped I saw mikejolley give to another user on this forum
2. Upload several product with close to 400 variants each.
3. Visit product page

## Expected/actual behavior
Product pages display correctly and quickly.

When I follow those steps, I see...
Site speed very slow, product pages very slow, sometimes product pages do not load completely.

I was expecting to see...
the full product page

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```

WordPress environment
--
Home URL: |   | https://my-merch.com/onlineshop
Site URL: |   | https://my-merch.com/onlineshop
WC version: |   | 3.3.1
Log directory writable: |   | /home/indicapl/public_html/my-merch.com/wp-content/uploads/sites/10/wc-logs/
WP version: |   | 4.9.4
WP multisite: |   |  
WP memory limit: |   | 768 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US

Server environment
--
Server info: |   | Apache
PHP version: |   | 5.6.33
PHP post max size: |   | 128 MB
PHP time limit: |   | 120
PHP max input vars: |   | 3000
cURL version: |   | 7.53.0, OpenSSL/1.0.2k
SUHOSIN installed: |   | –
MySQL version: |   | 5.6.36
Max upload size: |   | 1 MB
Default timezone is UTC: |   |  
fsockopen/cURL: |   |  
SoapClient: |   |  
DOMDocument: |   |  
GZip: |   |  
Multibyte string: |   |  
Remote post: |   |  
Remote get: |   |  

</details>

**Comment by WPprodigy** [comment]
There is a reason there's a limit on how many variations load by default...

You're asking the page to load 400 posts essentially. This would be like having a blog page with 400 posts loaded at once, or your shop page loading 400 products.

It's a bad idea. Switch it back to only loading 20-30, and let the default behavior take place.

**Comment by yorbelac** [comment]
Is it not possible to adjust the listing information somehow that it doesn’t have to show these unsupported variations?

Sent from Mail for Windows 10

**Comment by WPprodigy** [comment]
So after you first select an attribute, you want the next attributes to be only valid ones?

In order for it to work that way, all the variations need to be loaded so availability can be checked. And that is not an option for 400variation products.

Perhaps you should not be using a variable product for this if you need 400 variations.
