### ISSUE TITLE
ThankYou Page hook breaks visuals

### ISSUE THREAD

**Issue by MajkieS** [woocommerce/woocommerce#19047]
Hey there,

in thankyou.php I queue the hook:

```
<?php do_action( 'woocommerce_thankyou_' . $order->get_payment_method(), $order->get_id() ); ?>
<?php do_action( 'woocommerce_thankyou', $order->get_id() ); ?>
```

To measure all conversions and also this shows some order details.

But so far, for some reason, as soon as I add this code part, it moves `<footer>` in between `<article>` tag. So it looks kind of weird.

It is separate. `<article></article>` and then we use get_footer();

How is it possible that it moves `<footer>` from get_footer(); into that hook? Are there any ways to reproduce what is causing it?

**Comment by mikejolley** [comment]
Sounds like the code you're hooking in may contain an unclosed tag. Without knowing what you're hooking in I cannot say, but the 2 hooks above are not the problem.

**Comment by MajkieS** [comment]
Can I send you links into PM?

**Comment by mikejolley** [comment]
We don't assist with custom coding here.

**Comment by MajkieS** [comment]
Fixed, you were right.
