### ISSUE TITLE
Evaluate async and defer for inline scripts

### ISSUE THREAD

**Issue by bhubbard** [woocommerce/woocommerce#19057]
To improve woocommerce performance it makes sense to evaluate the inline scripts and see if they would benefit from using async or defer. Here is a quick search for scripts that may benefit:

https://github.com/woocommerce/woocommerce/search?p=1&q=%3Cscript+type%3D%22text%2Fjavascript%22%3E&type=&utf8=%E2%9C%93

**Comment by mikejolley** [comment]
With the exception of the one in the wizard which is used by another script, all of these are independent. jQuery is loaded in the header. So it should be safe to use async in all cases.
