### ISSUE TITLE
3.3.2 breaks Variation Image Switching

### ISSUE THREAD

**Issue by DanielSantoro** [woocommerce/woocommerce#19054]
When upgrading to WooCommerce 3.3.2, the Variation images don't switch when set using the Storefront theme.

As an example, here is a working version in 3.3.1:

Screencap: http://cld.wthms.co/OrBiih

And here is the 3.3.2 display:

Screencap: http://cld.wthms.co/Mv7BVB

Able to replicate on Pressable, WPEngine, and Localhost running the latest versions of WooCommerce, WordPress, and Storefront. Single-variation products still have the issue as well.

**Comment by mikejolley** [comment]
The JS seems to be using a class called `.wp-post-image` which is not present on the main image.

https://github.com/woocommerce/woocommerce/blob/1b03a80ecb4f6f59e9452522f3a64528dc4a0526/templates/single-product/product-image.php#L44

Will need to be added to `wc_get_gallery_image_html`.

**Comment by thomas-zg** [comment]
Same issue here, latest version of WC(3.3.2) and Storefront.

**Comment by dodi24** [comment]
3.3.3 have this bug

**Comment by mikejolley** [comment]
There is no 3.3.3 yet..

**Comment by dodi24** [comment]
Sorry 3.3.2 :)

**Comment by Webtica** [comment]
Same bug!
3.3.1 to 3.3.2  Variation images don't switch.

**Comment by dodi24** [comment]
I come back to 3.3.1

**Comment by rwaynick** [comment]
Also reported in 455913-hc

**Comment by alien27** [comment]
same here.
Image of variable product only changes in the gallery as thumbnail but not replacing the main product image.

**Comment by Webtica** [comment]
Seems fixed here 👍 https://github.com/woocommerce/woocommerce/commit/1563967ddf7db53643a9bb3ae6975db9dc910671
for manual fix add the code until 3.3.3

**Comment by dodi24** [comment]
Thank you Webtica ! its working !

**Comment by Webtica** [comment]
Thank @mikejolley :-)
