### ISSUE TITLE
Extending WC_Order

### ISSUE THREAD

**Issue by benignant** [woocommerce/woocommerce#19058]
The docblock for the constructor of <a href="https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L87-L89" rel="noopener" target="_blank">WC_Abstract_Order</a> states:

<blockquote>
    This class should NOT be instantiated, but the get_order function or new WC_Order_Factory should be used. It is possible, but the aforementioned are preferred and are the only methods that will be maintained going forward.
</blockquote>

Does this include the case where a subclass extends from WC_Order (which extends from WC_Abstract_Order)? Is it therefore not recommended to extend WC_Order (because the constructor may be removed in a future version)? Or is that an exception?

Thank you.

**Comment by mikejolley** [comment]
You can extend it, but the `class should NOT be instantiated`. i.e. don't call `new WC_Order`, instead use the `get_order` method. I think thats all this comment refers to.

**Comment by benignant** [comment]
If you extend the class, and then you instantiate your subclass `new Subclass_Of_WC_Order()`, then you would be using the inherited constructor. What I meant was, is doing that recommended? Perhaps it is recommended to initialize the subclass with a custom constructor?

**Comment by mikejolley** [comment]
Not recommended because the ID may not be an order of your custom type. the method loads the object with the correct class.

**Comment by benignant** [comment]
I don't intend to have a custom type of any sort. Just an extended order object with added functionality. There wouldn't be any other IDs.

What I'm trying to figure out is whether I can rely on the inherited constructor, or I need to initialize the object myself (copying and pasting the code from the WC_Abstract_Order constructor into my own?).

**Comment by mikejolley** [comment]
I think you'd need to look at making the factory return your new class instead of WC Order. Added functionality doesn't need to go in this class however. It could quite easily (it seems) take an order and pass something back? Not sure what you're doing.

**Comment by benignant** [comment]
1. The problem with the `woocommerce_order_class` filter is that if another plugin uses that hook, there will be a race condition.
2. The problem with the decorator pattern is that the API is no longer transparent. Everywhere the decorator is used, you need to access the underlying object via an intermediary property to interact with core functionality. This is manageable (and probably the route I'd take if there was no other way), but not ideal.

**Comment by mikejolley** [comment]
Can you explain what you're actually adding to the order class?

**Comment by benignant** [comment]
Here's a simplified sample:

```php
<?php

class Custom_Order extends WC_Order {

	public function get_custom_payments() {

		// Not using '$this->get_meta()' in order to maintain compatibility with WC 2.6.0.
		return get_post_meta( $this->id, 'custom_payments', true );
	}

	public function add_custom_payment( $payment ) {
		$payments = $this->get_custom_payments();

		$payments[] = $payment;

		update_post_meta( $this->id, 'custom_payments', $payments );
	}

	public function get_total_amount_paid() {
		return array_sum( array_column( $this->get_custom_payments(), 'amount' ) );
	}

	public function get_total_amount_unpaid() {
		return $this->order->get_total() - $this->get_total_amount_paid();
	}

}
```

This is the easiest way to interact with functionality added to an order by a plugin.

```php
echo 'Amount unpaid for order #' . $order->id . ': ' . $order->get_total_amount_unpaid();
```

As of now, this works. But will it work in the future? Or should I heed the docblock?

**Comment by mikejolley** [comment]
I don't understand why you need to add these as methods. Just use functions and get the data from the order object. The getters are public. That would avoid any of these potential conflicts.

**Comment by benignant** [comment]
I could certainly do this in other ways. But look at how clean that interaction is. You can use that order object like a core order object without having to deal with different ways of accessing core and custom functionality.

Another use case I have in mind is a "compatibility order" object. It would add methods with the names used in WC 3.0.0+, and those methods would check which version of WooCommerce is being used, and then decide which core methods to use. This would greatly reduce the number of version checks littered throughout the codebase.

```php
<?php

class Compatibility_Order extends WC_Order {

	public function get_date_paid( $context = 'view' ) {
		if ( version_compare( WC_VERSION, '3.0.0', '>' ) ) {
			return parent::get_date_paid( $context );
		}

		return $this->order->paid_date;
	}

}
```

And then:

```php
$order = new Compatibility_Order( 123 );

// This works on WC < 3.0.0 and > 3.0.0.
printf( 'Order #%u was paid on %s.', $order->id, $order->get_date_paid() );
```

<hr>

How about using `__get` and `__call` with the decorator pattern to pass through calls to the core object? That way, you get custom functionality but still retain the ability to interact with the core object transparently. Would that be recommended (regarding forward compatibility)?

**Comment by mikejolley** [comment]
In your example you have no knowledge of what type `123` is. It might not be a `wc_order`. It might  be a subscription for example.  Thats why the factory and getters need should be used. You can still have a custom method/Compatibility_Order but don't extend. Work with an `$order` object.
