### ISSUE TITLE
Switching variations changes only thumbnails, not main image

### ISSUE THREAD

**Issue by ChrisPlaneta** [woocommerce/woocommerce#19065]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a variable product with a main image, gallery images and variation images and save
2. duplicate this product
3. In the duplicated product remove the main image and save

## Expected/actual behavior

1. In the original product, changing variables values changes only thumbnail images but **not** the main one
2. In th duplicated product without the main image, the thumbnails don't show up **however** after switching variable values the main image shows correct images of variants

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

To see this bug in action go to https://akrylerdev.dkonto.pl/. The two products are on the home page.

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://akrylerdev.dkonto.pl
Site URL: https://akrylerdev.dkonto.pl
WC Version: 3.3.2
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: pl_PL

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.26-dh10
PHP Post Max Size: 32 MB
PHP Time Limit: 240
PHP Max Input Vars: 6000
cURL Version: 7.57.0
NSS/3.28.4

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.2
WC Database Prefix: l7nds87_
MaxMind GeoIP Database: ❌ Baza danych MaxMind GeoIP nie istnieje - Geolokalizacja nie będzie działać. Możesz pobrać i zainstalować ją ręcznie http://dev.maxmind.com/geoip/legacy/geolite/ stąd: . Przewiń w dół do zakładki "Downloads" i pobierz plik "Binary / gzip" obok "GeoLite Country". Pamiętaj
aby rozpakować GeoIP.dat.gz i przesłać tylko plik GeoIP.dat.

Całkowity rozmiar bazy danych: 9.46MB
Rozmiar bazy danych: 7.73MB
Rozmiar indeksu bazy danych: 1.73MB
l7nds87_woocommerce_sessions: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_woocommerce_order_items: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_woocommerce_order_itemmeta: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB
l7nds87_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.05MB
l7nds87_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.05MB
l7nds87_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_commentmeta: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_comments: Dane: 0.02MB + Indeks: 0.08MB
l7nds87_links: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_litespeed_optimizer: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_options: Dane: 1.09MB + Indeks: 0.05MB
l7nds87_postmeta: Dane: 1.28MB + Indeks: 0.11MB
l7nds87_posts: Dane: 0.30MB + Indeks: 0.06MB
l7nds87_termmeta: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_terms: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_term_relationships: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_term_taxonomy: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_usermeta: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_users: Dane: 0.02MB + Indeks: 0.05MB
l7nds87_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB
l7nds87_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_wfBadLeechers: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfBlockedCommentLog: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfBlockedIPLog: Dane: 0.06MB + Indeks: 0.00MB
l7nds87_wfBlocks: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_wfBlocks7: Dane: 0.02MB + Indeks: 0.05MB
l7nds87_wfBlocksAdv: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfConfig: Dane: 0.30MB + Indeks: 0.00MB
l7nds87_wfCrawlers: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfFileChanges: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfFileMods: Dane: 1.52MB + Indeks: 0.00MB
l7nds87_wfHits: Dane: 0.45MB + Indeks: 0.27MB
l7nds87_wfHoover: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_wfIssues: Dane: 0.02MB + Indeks: 0.06MB
l7nds87_wfKnownFileList: Dane: 1.52MB + Indeks: 0.00MB
l7nds87_wfLeechers: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfLockedOut: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfLocs: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfLogins: Dane: 0.11MB + Indeks: 0.03MB
l7nds87_wfNet404s: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_wfNotifications: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfPendingIssues: Dane: 0.02MB + Indeks: 0.06MB
l7nds87_wfReverseCache: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfScanners: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_wfSNIPCache: Dane: 0.02MB + Indeks: 0.05MB
l7nds87_wfStatus: Dane: 0.14MB + Indeks: 0.11MB
l7nds87_wfThrottleLog: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_wfVulnScanners: Dane: 0.02MB + Indeks: 0.00MB
l7nds87_yoast_seo_links: Dane: 0.02MB + Indeks: 0.02MB
l7nds87_yoast_seo_meta: Dane: 0.02MB + Indeks: 0.00MB

### Post Type Counts ###

attachment: 117
custom_css: 1
customize_changeset: 3
nav_menu_item: 16
page: 16
post: 1
product: 2
product_variation: 6
revision: 47

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

LiteSpeed Cache: przez LiteSpeed Technologies – 1.9.1.1
Snapshot Pro: przez WPMU DEV – 3.1.5
WooCommerce: przez Automattic – 3.3.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Strona sklepu: #727 - /
Koszyk: #728 - /koszyk/
Zamówienie: #729 - /zamowienie/
Moje konto: #730 - /moje-konto/
Regulamin: #732 - /regulamin-sklepu/

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://pl.wordpress.org/
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/19054
