### ISSUE TITLE
Not all Newzealnd locations are add into woocommerce plugins  [https://en.wikipedia.org/wiki/List_of_cities_in_New_Zealand]

### ISSUE THREAD

**Issue by jhimli2015** [woocommerce/woocommerce#19060]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
We don't store CITIES in WooCommerce, only states/provinces.

**Comment by jhimli2015** [comment]
Hi Mike ,

Thanks for your reply, but as per my site I was enter NZ because my seller is only sell their product in New Zealand , but when some customer from NZ tried to order product , it shows ,,, shipping not available for this country .. But I was set My country specific to NZ.. shipping is set default to NZ, though some people may not able to order , can you help me regarding this issue.. sorry to bother you ... 

Jhimli
Web Admin
Milkio.co.nz

**Comment by mikejolley** [comment]
Then it's your shipping rules, not the states.. Check those.
