### ISSUE TITLE
BUG : Exclude sale items rules is not working if ..

### ISSUE THREAD

**Issue by enda1994** [woocommerce/woocommerce#19062]
as shown in the title

Exclude sale items rules is not working if there are other products in the shopping cart that are not discounted.

**See this screenshoot :** 

![image](https://user-images.githubusercontent.com/15183548/36471284-7fa3a99e-1720-11e8-817e-88b68dd50571.png)

**rules is working fine. but if I add a product that is not discounted. The rule is not working.**

![image](https://user-images.githubusercontent.com/15183548/36471318-98d1a6dc-1720-11e8-9b2e-0d2985147137.png)

how to fix this bug? thanks

**Comment by mikejolley** [comment]
The discount only applies to the non-sale items. Otherwise you are just blocking the customer for absolutely no reason (they could put in 2 separate orders and pay the same, they would just be more frustrated :)).

It's not a bug.
