### ISSUE TITLE
Site slowing as orders grow. Correct way to delete old orders

### ISSUE THREAD

**Issue by imbeingfollowed** [woocommerce/woocommerce#19067]
I manage a site that has 25k previous orders and growing. MySQL is heavily optimised but the server is now slowing with the amount of metadata that WooCommerce seems to spread across an excessive number of rows and tables. I have decided that the easiest solution would be to delete old and fulfilled orders.

What is the correct way to programatically delete an order? Would wp_delete_post() suffice and would this clear all the associated WooCommerce order clutter along with it?

Thanks

**Comment by mikejolley** [comment]
Programmatically,:

```
$order = wc_get_order( xxx );
$order->delete( true );
```

You could instead just add meta key/value index to the post meta table so it can handle things better.

**Comment by imbeingfollowed** [comment]
Hey Mike,

Thanks for your quick and excellent response.

What tables would you recommend this for? I guess woocommerce_order_itemmeta is the obvious one with 2.5M rows. Would you recommend indexing both the meta_key and meta_value fields? Any indexing type preferred?

Kind Regards

**Comment by mikejolley** [comment]
I was more talking about postmeta. Order item meta has indexes already.
