### ISSUE TITLE
CRUD search - support for stopwords

### ISSUE THREAD

**Issue by albatrossi** [woocommerce/woocommerce#19061]
Not sure if its a bug or why was it changed, but since the release of v3.3 product search in admin page hasn't been working like earlier. Now you have to know the exact order of words, or exact order of letters to get correct results. If you have a product called "pink carkey holder" and search  for "pink holder", there will be no results. If you search for "key hol" there will be. Earlier you could search without precise word or letter order and it was alot easier. I have thousands of products with complicated names and the change makes it quite alot harder to search.

**Comment by mikejolley** [comment]
WordPress search supports stopwords and breaking up of phrases. WC search does not. It just searches the entire term.

This isn't a bug; the WC search is new. For that reason I don't think it's worth prioritising a fix. We can however look at adding this feature in a future release.

See https://github.com/WordPress/WordPress/blob/8a884f562a652bb8f5abe220574f34a3ce1d4126/wp-includes/class-wp-query.php#L1297-L1369 for how WordPress handles it. This would need to go in our CRUD classes (abstract?) and then use it in `search_products`. This will be useful to have before swapping any frontend searches to use the new system.

**Comment by maxmarineelectronicsinc** [comment]
I agree with albatrossi. Please bring the v3.2 search function back. It makes finding products when you have a huge inventory with a lot of similar items and similar names much more difficult with the new product search field. Please prioritize the fix on your next version.

**Comment by CraigElkins** [comment]
I've run into this issue as well. I have multiple clients who search wc with "stop words and breaking up of phrases" -now they cannot.  I think this fix should be a priority. No one wants a LESS user friendly search box. If you've got a product db numbering in the thousands, you need to be able to search like this. Why would WC remove this search feature?

**Comment by mikejolley** [comment]
No one said it was intentionally removed. Nor did anyone say it wouldn't be added to the new system. We've simply said it won't be in a fix release because it's not a small change.

**Comment by CraigElkins** [comment]
Thanks mikejolley - hopefully it'll be fixed soon.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19096

**Comment by maxmarineelectronicsinc** [comment]
These closed things mean what? The issue is not resolved as far as I can
see?

*Tiffany Hallam*
*Operations Manager *


2185 N Powerline Rd Ste 1
Pompano Beach, Fl 33069
www.maxmarineelectronics.com
754-220-6565 ext 108

**Comment by CraigElkins** [comment]
Thanks for the fix mikejolley - it didn't make a difference for me though.To clarify,  I am searching the Dashboard > Products. Searching for keywords from a title -i.e. Product Title: "My Awesome Product" - searching for "My Product" (no quotes) yields no results.

**Comment by mikejolley** [comment]
You'd need to apply the patch manually. This is not live. That's the test case I used for the PR.

**Comment by CraigElkins** [comment]
Got it - so no way to tweak backend product search functionality as of yet.
