### ISSUE TITLE
Bug serious / Calculation with decimal

### ISSUE THREAD

**Issue by rvola** [woocommerce/woocommerce#19064]
**edit 14h32**

In fact the problem does not come from the VAT but calculations or the update of the basket (admin) with products with decimals

----

ok i have just discovered a very serious bug on branch 3.3.2 since 3.3.1.

It is quite complicated and deals with the calculation of VAT.

I have a customer who uses a line in VAT reduced 5.5% and that I update an order, the recalculation of the order passes the product to 0 €.

I tried to reproduce the bug on a new installation and I arrived there !!
I want to clarify that I also did my test with only WooCommerce 3.3.2 (master included) + WordPress 4.9.4 + StoreFront 2.2.8

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. WooCommerce> Settings: Enable VAT ![screenshot-1](https://user-images.githubusercontent.com/6870615/36480739-b840e892-170d-11e8-8da2-481527aa7f43.png)
2. VAT settings ![screenshot-2-1](https://user-images.githubusercontent.com/6870615/36480738-b822281c-170d-11e8-8a3a-1ab2bc8f14f7.png) ![screenshot-2-2](https://user-images.githubusercontent.com/6870615/36480741-b85e2ab0-170d-11e8-98a1-248ba4f82a45.png)

3. Add a product and select reduced VAT ![screenshot-3](https://user-images.githubusercontent.com/6870615/36480737-b7fa0a94-170d-11e8-920d-3ce2731a7f05.png)
4. Create an order and add the product [movie.mp4.zip](https://github.com/woocommerce/woocommerce/files/1744036/movie.mp4.zip)
5. Click "recalculate" or update to order = the product goes to 0 €

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

### WordPress Environment ###

Home URL: http://woocommerce.localhost
Site URL: http://woocommerce.localhost
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.2.1 mod_ssl/2.2.34 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.2.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 0.97MB
Database Data Size: 0.74MB
Database Index Size: 0.23MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.51MB + Index: 0.03MB
wp_postmeta: Data: 0.18MB + Index: 0.10MB
wp_posts: Data: 0.04MB + Index: 0.02MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.01MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 22
page: 5
post: 2
product: 19
product_variation: 7
shop_order: 11
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.0-dev

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /boutique/
Cart: #5 - /panier/
Checkout: #6 - /commande/
My account: #7 - /mon-compte/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: .DS_Store

**Comment by rvola** [comment]
This problem seems identical
https://wordpress.org/support/topic/orders-do-not-save-prices-when-they-are-edited-in-admin/

**Comment by xarkitu** [comment]
rvola, I think it is not the same or it has not been raised well here.

I have done tests in two stores, one with VAT and one without, the two fail the same.

One of them I have reduced to V3.3.1 and started working again.

As I have described in the thread that you comment, I am reproduced the error when I work with integers or decimals.

**Comment by rvola** [comment]
yes I just changed the title!
Well seen

**Comment by mikejolley** [comment]
@rvola Commas are not stored in the database. What price do I have to set with a comma to trigger this?

**Comment by rvola** [comment]
@mikejolley  

any of them

I put my product (without VAT) to 98,10 €
Then if you create a manual order, add the product, click on "recalculate" = the product will go to zero.

The problem is also present if a command passed (before the update) and which contains decimals, if I click on "update", each product goes to zero.

**Comment by mikejolley** [comment]
Got it. @WPprodigy that is_numeric check seems to the the cause. Values are passed with commas, and wc_format_decimal handles conversion.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/19041 caused this.

**Comment by rvola** [comment]
the joy of writing conventions of decimals 🤐😂

**Comment by mikejolley** [comment]
@rvola can you confirm https://github.com/woocommerce/woocommerce/pull/19069 works for you? If so I'll get that deployed asap

**Comment by rvola** [comment]
yes I confirm, the fix corrects the bug

**Comment by Netura** [comment]
I also encountered this bug on 3.3.2.
