### ISSUE TITLE
The product_attributes page is blank

### ISSUE THREAD

**Issue by jhbohlen** [woocommerce/woocommerce#19071]
After a fresh installation of Woocommerce when you go to the product attributes page no controls to add attributes show up.

**Comment by mikejolley** [comment]
Clean install (I reset) and it appears fine:

![attributes local wordpress dev wordpress 2018-02-21 14-47-22](https://user-images.githubusercontent.com/90977/36486329-2a971ada-1716-11e8-9c59-069430420f8f.png)

Go through all steps on the new issue form.

**Comment by jhbohlen** [comment]
What is your exact setup? Maybe you're not testing on the latest PHP 7.2. I did a fresh Wordpress and Woocommerce 2.6.14 and workd fine. Fresh Wordpress and Woocommerce 3 and it doesn't.

**Comment by mikejolley** [comment]
Would it be useful to know my setup :) ? Go through the new issue form and post back everything requested.

**Comment by jhbohlen** [comment]
Listen, seems like you're quick on the closing trigger. I just uninstalled 3.3.2 and installed 3.3.1 and the attribute page is fine. Reinstalled 3.3.2 and all controls are gone. But hey... you're the genius!

**Comment by mikejolley** [comment]
@jhbohlen If you don't provide details of your environment, what am I supposed to do here? 

> Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action. 

Enable debug mode and tell me what you get on the screen. It's working for me.

**Comment by jhbohlen** [comment]
The define('WP_DEBUG', true); is set in the wp-config.php. There are no errors generate. Just a page with no controls.
![woo](https://user-images.githubusercontent.com/36703031/36489514-20fded34-171e-11e8-9a4b-c8dde8eee902.jpg)

**Comment by mikejolley** [comment]
View page source and see whats output at the bottom? I don't think error reporting is showing anything here.

**Comment by jhbohlen** [comment]
<div id="screen-meta-links">
					<div id="contextual-help-link-wrap" class="hide-if-no-js screen-meta-toggle">
			<button type="button" id="contextual-help-link" class="button show-settings" aria-controls="contextual-help-wrap" aria-expanded="false">Help</button>
			</div>
				</div>
				<div class="wrap woocommerce">
			<h1>Attributes</h1>

			<br class="clear" />
			<div id="col-container">
				<div id="col-right">
					<div class="col-wrap">
						<table class="widefat attributes-table wp-list-table ui-sortable" style="width:100%">
							<thead>
								<tr>
									<th scope="col">Name</th>
									<th scope="col">Slug</th>

**Comment by jhbohlen** [comment]
Here's my environment
### WordPress Environment ###

WC Version: 3.3.2
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.12.2
PHP Version: 7.2.2-3+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.2
WC Database Prefix: WC_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.88MB
Database Data Size: 1.04MB
Database Index Size: 0.84MB
WC_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
WC_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
WC_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
WC_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
WC_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
WC_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
WC_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
WC_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
WC_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
WC_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
WC_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
WC_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
WC_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
WC_woocommerce_log: Data: 0.02MB + Index: 0.02MB
WC_commentmeta: Data: 0.02MB + Index: 0.03MB
WC_comments: Data: 0.02MB + Index: 0.08MB
WC_links: Data: 0.02MB + Index: 0.02MB
WC_options: Data: 0.50MB + Index: 0.02MB
WC_postmeta: Data: 0.02MB + Index: 0.03MB
WC_posts: Data: 0.02MB + Index: 0.06MB
WC_termmeta: Data: 0.02MB + Index: 0.03MB
WC_terms: Data: 0.02MB + Index: 0.03MB
WC_term_relationships: Data: 0.02MB + Index: 0.02MB
WC_term_taxonomy: Data: 0.02MB + Index: 0.03MB
WC_usermeta: Data: 0.02MB + Index: 0.03MB
WC_users: Data: 0.02MB + Index: 0.05MB
WC_wc_download_log: Data: 0.02MB + Index: 0.03MB
WC_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 5
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
I just updated my VVV box to `7.2.2-3+ubuntu14.04.1+deb.sury.org+1`. Again, it works. I suggest you check the page source for errors/view error logs. Something is not standard on your install it seems.

**Comment by mikejolley** [comment]
@jhbohlen No issue there I can tell. Your page is cutting off on a part which is rendered by WordPress itself. I'm also not seeing the same issue. If there were a PHP error it would be logged. It could just be memory or something common like that.

**Comment by claudiosanches** [comment]
Just tested with `PHP 7.2.2-3+ubuntu17.10.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:55) ( NTS )`
Working just fine that page.
