### ISSUE TITLE
exclude_from_search = true breaks WP_Query on archive-product.php

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#19073]
```
function my_function() {
	global $wp_post_types;
	$wp_post_types['product']->exclude_from_search = true;
}
add_action( 'pre_get_posts', 'my_function' );
```

This code snippet makes "Product categories" widget not work and archive-product.php has no items in WP_Query.

**Comment by mikejolley** [comment]
This is handled by WP https://github.com/WordPress/WordPress/blob/8a884f562a652bb8f5abe220574f34a3ce1d4126/wp-includes/class-wp-query.php#L2067-L2088

If you exclude from search, term queries don't include our post type.

Fix; don't use that snippet :p
