### ISSUE TITLE
Tax calculation in manual orders force values to be zero

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#19072]
Hi team, have juist updated to 3.3.2. Tried to create a order in backend as admin same as yesterday with 3.3.1.

Selected customer, added a product and submitted button calculate because product is added without tax. After button was submitted, no tax is calculated instead product price is now set to 0.00.

Tried on live site were bug first came up. Tried too on staging site with only woocommerce plugin active. Theme is Storefront.

**Comment by Srbastien** [comment]
I have nearly the same pobleme !!!
i receve an odrer from front end by client...
and in admin in the order i have zero instead of price...
nothing wrong in front....
only in back office...

**Comment by ajgw** [comment]
Oops, saw after writing this down that this bug was marked as solved issue for 3.3.3. Sorry.

Related: https://github.com/woocommerce/woocommerce/issues/19064
