### ISSUE TITLE
cart-fragments.min.js => wc_cart_fragments_params is undefined

### ISSUE THREAD

**Issue by thesublimeobject** [woocommerce/woocommerce#19074]
I continue to have trouble with getting this script to behave correctly. I'm not sure if it's a compatibility issue or something internally wrong as I can't find many other recent issues around this, and I would assume other people would be getting the same errors.

So, first, this check at the beginning is getting bypassed:

```
if ( typeof wc_cart_fragments_params === 'undefined' ) {
    return false;
}
```

The reason seems to be that wc_cart_fragments_params is actually defined, but the incorrect props are defined upon it, for whatever reason, which I haven't figured out. The props that do _seem_ to need to be defined on it are as follows:

```
wc_cart_fragments_params.ajax_url = '/wp-admin/admin-ajax.php'
wc_cart_fragments_params.fragment_name = 'wc_fragments_key'
wc_cart_fragments_params.wc_ajax_url = 'http://site-name.com/?wc-ajax=%%endpoint%%'
```

But these properties are not defined on the object itself, and I'm not totally sure why. I have temporarily fixed this by just adding the following: 

```
if ( typeof wc_cart_fragments_params === 'undefined' ) {
	return false;
} else if (wc_cart_fragments_params.ajax_url == undefined) {
	wc_cart_fragments_params.ajax_url = '/wp-admin/admin-ajax.php'
	wc_cart_fragments_params.fragment_name = 'wc_fragments_key'
	wc_cart_fragments_params.wc_ajax_url = 'http://site-name.com/?wc-ajax=%%endpoint%%'
}
```

but this isn't really a great solution, and additionally, it obviously gets over-written on any update so I'm having to overwrite the entire script by enqueuing my own version, which I know will probably eventually lead to other problems given the complexity of a plugin like this.

I hope this is enough information, but I am happy to provide further information if needed. Here are some general details about the site:

Newest version of WP, WooCommerce v3.3.2, running on Pagely servers.

**Comment by mikejolley** [comment]
Have you ruled out other plugins? The params are filterable so it's likely another plugin changing them!

**Comment by mikejolley** [comment]
Hooks to check:

`wc_cart_fragments_params`
`woocommerce_get_script_data` https://github.com/woocommerce/woocommerce/blob/3b895bd0a98e1c3c6b336ca69c002bc6b67e8524/includes/class-wc-frontend-scripts.php#L571

Both of these allow you to change the value of the params. If a plugin is doing this, it's out of scope for core to workaround.

Hope you find it 👍

**Comment by thesublimeobject** [comment]
I searched the entire wp-content directory for both of those. The second doesn't show up anywhere, and the first one only show up in places that you would expect.

**Comment by mikejolley** [comment]
Why not view page source and see what is inside wc_cart_fragments_params? Might give clues.

**Comment by cinghaman** [comment]
Hi Not sure if it still active, I am getting a same error in one of the JS files 
`var $warp_fragment_refresh = {
        url: wc_cart_fragments_params.wc_ajax_url.toString().replace( '%%endpoint%%', 'get_refreshed_fragments' ),
        type: 'POST',
        beforeSend: function( data ) {`
on the url: Uncaught ReferenceError: wc_cart_fragments_params is not defined

**Comment by po8digital** [comment]
For anyone else still having this issue, make sure that wp_enqueue_scripts and your ajax script is not loading before woocommerce e.g. "add_action( 'wp_enqueue_scripts', 'gf_bundle_enqueue_scripts', 1, 1);", changing to add_action( 'wp_enqueue_scripts', 'gf_bundle_enqueue_scripts'); fixed this for me.

**Comment by thesublimeobject** [comment]
interesting, thanks for the recommendation @po8digital. it hasn't been acting up for awhile, but i think that's because i added a hack-ish fix awhile back—i'll definitely try this.
