### ISSUE TITLE
Fatal error: Uncaught DivisionByZeroError: Modulo by zero in wc-template-functions.php:388

### ISSUE THREAD

**Issue by titandoo** [woocommerce/woocommerce#19085]
I got error after upgrade woocommerce:

  | <b>Warning</b>:  A non-numeric value encountered in <b>/home/ezgiz.com/public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php</b> on line <b>388</b><br />
  | <br />
  | <b>Fatal error</b>:  Uncaught DivisionByZeroError: Modulo by zero in public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php:388
  | Stack trace:
  | #0 public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php(436): wc_get_loop_class()
  | #1 public_html/wp-includes/class-wp-hook.php(286): wc_product_post_class(Array, Array, 6831)
  | #2 public_html/wp-includes/plugin.php(203): WP_Hook-&gt;apply_filters(Array, Array)
  | #3 public_html/wp-includes/post-template.php(543): apply_filters('post_class', Array, Array, 6831)
  | #4 public_html/wp-includes/post-template.php(423): get_post_class(Array, NULL)
  | #5 public_html/wp-content/plugins/woocommerce/templates/content-product.php(30): post_class()

**Comment by mikejolley** [comment]
This means some genius code is filtering the `columns` to be 0.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19088
