### ISSUE TITLE
woocommerce_adjust_non_base_location_prices not applying to admin-created orders

### ISSUE THREAD

**Issue by indextwo** [woocommerce/woocommerce#19083]
I've implemented the `woocommerce_adjust_non_base_location_prices` filter as per this WooCommerce Wiki article on taxes:

`add_filter('woocommerce_adjust_non_base_location_prices', '__return_false');`

This should effectively 'ignore' tax rates on an order: an €8,99 physical product (where product prices are inclusive of tax) being sold from a UK store will cost €8,99 to a German customer, a French customer or an ROI customer. This all works as expected on the front end when a customer goes through the checkout.

However, if I manually create an order in the backend for a German customer and add that €8,99 product, it gets added at €7,49 with no tax, even after recalculating. I understand from a tax perspective why this is happening (a UK store selling in Germany shouldn't apply tax, so 8.99 - 20% UK VAT = 7.49), however this seems to be ignoring my `woocommerce_adjust_non_base_location_prices` filter.

At the moment my filter call is just a single line (not inside a function or other filter) in a custom plugin, so I assume it's being implemented at `plugins_loaded`. There's no conditional (e.g. `if (!is_admin()) {}`), so I'm wondering if I need some other kind of condition to ensure it is applied to admin orders, or if I'm looking at a bug?

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Ensure product prices are inclusive of VAT, base store in UK
2. Add `add_filter('woocommerce_adjust_non_base_location_prices', '__return_false');` to plugin.
3. Go through checkout as a customer based in Germany, see that tax is not removed
4. Manually create order in admin for customer based in Germany; add product; tax is removed

## Expected/actual behavior

When I follow those steps, the UK VAT (20%) is removed from the order total (so an 8.99 product becomes 7.49, because the 20% tax is removed).

I was expecting to see the `woocommerce_adjust_non_base_location_prices` filter being honoured, and that the order total would not be adjusted.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active _(Custom plugin for adding filter required)_
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19109

Can be a little off if you don't have a user/address first but since admin deals with tax excl. prices only I don't see a workaround.

**Comment by FadiNouh1** [comment]
So what is the latest solution (steps) for this issue, I have woocommerce 3.4.5 and It cant take any effect in admin area

**Comment by PV-Web** [comment]
@indextwo Did you find a workaround for this issue? It all works great when selling to countries with tax rate added (Clicking recalculate after product adding). But when selling to e.g. the USA it sets it to 0% so the price is too low.
@mikejolley after 2 years, is there an update on this?

**Comment by oblaum** [comment]
hello,

i want to use this function. i am facing the problem, that in EU countries it works, but when shipping to a non EU-country (like switzerland) it does not use the 0% tax i have set up.

i found a function for this, but then facing the prolem that it does not work proper in EU countries (sight)

```
add_action( 'woocommerce_cart_calculate_fees', 'same_price_for_eu' );
function same_price_for_eu(){

   $countries = new WC_Countries();

   $eu_countries = $countries->get_european_union_countries();

   if ( in_array( WC()->customer->get_shipping_country(), $eu_countries) ){
  add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false');

   } else {
   remove_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false');

   }
}
```

any ideas? i try to use add_action( 'woocommerce_before_calculate_totals', too but does not work.

sos!

thanks
oli

**Comment by abdulchalik** [comment]
> hello,
> 
> i want to use this function. i am facing the problem, that in EU countries it works, but when shipping to a non EU-country (like switzerland) it does not use the 0% tax i have set up.
> 
> i found a function for this, but then facing the prolem that it does not work proper in EU countries (sight)
> 
> ```
> add_action( 'woocommerce_cart_calculate_fees', 'same_price_for_eu' );
> function same_price_for_eu(){
> 
>    $countries = new WC_Countries();
> 
>    $eu_countries = $countries->get_european_union_countries();
> 
>    if ( in_array( WC()->customer->get_shipping_country(), $eu_countries) ){
>   add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false');
> 
>    } else {
>    remove_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false');
> 
>    }
> }
> ```
> 
> any ideas? i try to use add_action( 'woocommerce_before_calculate_totals', too but does not work.
> 
> sos!
> 
> thanks
> oli

Please try this
<pre>
function filter_woocommerce_adjust_non_base_location_prices( $true ) { 
    $countries = new WC_Countries();
    $eu_countries = $countries->get_european_union_countries(); 
    if (in_array( WC()->customer->get_shipping_country(), $eu_countries) ){
	return false;
    }else{
        return $true;
    }
};        
add_filter( 'woocommerce_adjust_non_base_location_prices', 'filter_woocommerce_adjust_non_base_location_prices', 10, 1 ); 
</pre>

**Comment by christianschoenmakers** [comment]
> Please try this
> 
> function filter_woocommerce_adjust_non_base_location_prices( $true ) { 
>     $countries = new WC_Countries();
>     $eu_countries = $countries->get_european_union_countries(); 
>     if (in_array( WC()->customer->get_shipping_country(), $eu_countries) ){
> 	return false;
>     }else{
>         return $true;
>     }
> };        
> add_filter( 'woocommerce_adjust_non_base_location_prices', 'filter_woocommerce_adjust_non_base_location_prices', 10, 1 );

Great suggestion, thank you very much. 

I've changed it a bit to check the VAT rules of the specific address and return true or false if the VAT is 0%. 

In this way, it is a little bit more flexible, for example to exclude based on postal code. 

```
function filter_woocommerce_adjust_non_base_location_prices( ) {

    // Get tax rates by available shipping information
    $taxes = new WC_Tax();
    $tax_rates = $taxes->find_rates([
        'country' => WC()->customer->get_shipping_country() ?? '',
        'state' => WC()->customer->get_shipping_state() ?? '',
        'city' => WC()->customer->get_shipping_city() ?? '',
        'postcode' => WC()->customer->get_shipping_postcode() ?? '',
    ]);

    // Check for tax rates and loop
    if($tax_rates && is_array($tax_rates) && count($tax_rates) > 0){
        foreach($tax_rates AS $tax_rate){
            // Check if rate is 0%
            if(isset($tax_rate['rate']) && is_float($tax_rate['rate']) && $tax_rate['rate'] == 0){
                return true;
            }
        }
    }

    return false;

};
add_filter( 'woocommerce_adjust_non_base_location_prices', 'filter_woocommerce_adjust_non_base_location_prices', 10, 1 );
```

**Comment by oblaum** [comment]
great!!! thank you! @[abdulchalik](https://github.com/abdulchalik) and @[wespiremedia](https://github.com/wespiremedia)

**Comment by cigaai** [comment]
Hello.

I tested the code 
```
function filter_woocommerce_adjust_non_base_location_prices( $true ) {
$countries = new WC_Countries();
$eu_countries = $countries->get_european_union_countries();
if (in_array( WC()->customer->get_shipping_country(), $eu_countries) ){
return false;
}else{
return $true;
}
};
add_filter( 'woocommerce_adjust_non_base_location_prices', 'filter_woocommerce_adjust_non_base_location_prices', 10, 1 );
```
and in the backoffice I get the following error when I go to the "products" menu:
WPCode has detected an error in one of the snippets which has now been automatically deactivated.

Click here to update the snippet that threw the error.

WPCode has detected an error in one of the snippets which has now been automatically deactivated.

Click here to update the snippet that threw the error.

Error message:

Uncaught Error: Call to a member function get_shipping_country() on null in /home/domain/public_html/wp-content/plugins/insert-headers-and-footers/includes/class-wpcode-snippet-execute.php(260) : eval()'d code:6 Stack trace: #0 /home/domain/public_html/wp-includes/class-wp-hook.php(307): filter_woocommerce_adjust_non_base_location_prices() #1 /home/domain/public_html/wp-includes/plugin.php(191): WP_Hook->apply_filters() #2 /home/domain/public_html/wp-content/plugins/woocommerce/includes/wc-product-functions.php(1119): apply_filters() #3 /home/domain/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(2079): wc_get_price_excluding_tax() #4 /home/domain/public_html/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(190): WC_Product->get_price_suffix() #5 /home/domain/public_html/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(167): WC_Product_Variable->get_price_suffix() #6 /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-products.php(216): WC_Product_Variable->get_price_html() #7 /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/list-tables/abstract-class-wc-admin-list-table.php(261): WC_Admin_List_Table_Products->render_price_column() #8 /home/domain/public_html/wp-includes/class-wp-hook.php(307): WC_Admin_List_Table->render_columns() #9 /home/domain/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() #10 /home/domain/public_html/wp-includes/plugin.php(476): WP_Hook->do_action() #11 /home/domain/public_html/wp-admin/includes/class-wp-posts-list-table.php(1349): do_action() #12 /home/domain/public_html/wp-admin/includes/class-wp-list-table.php(1450): WP_Posts_List_Table->column_default() #13 /home/domain/public_html/wp-admin/includes/class-wp-posts-list-table.php(1383): WP_List_Table->single_row_columns() #14 /home/domain/public_html/wp-admin/includes/class-wp-posts-list-table.php(795): WP_Posts_List_Table->single_row() #15 /home/domain/public_html/wp-admin/includes/class-wp-posts-list-table.php(772): WP_Posts_List_Table->_display_rows() #16 /home/domain/public_html/wp-admin/includes/class-wp-list-table.php(1362): WP_Posts_List_Table->display_rows() #17 /home/domain/public_html/wp-admin/includes/class-wp-list-table.php(1289): WP_List_Table->display_rows_or_placeholder() #18 /home/domain/public_html/wp-admin/edit.php(477): WP_List_Table->display() #19 {main} thrown

1 - Uncaught Error: Call to a member function get_shipping_country() on null in /home/domain/public_html/wp-content/plugins/insert-headers-and-footers/includes/class-wpcode-snippet-execute.php(260) : eval()'d code:6 Stack trace: #0 /home/domain/public_html/wp-includes/class-wp-hook.php(307): filter_woocommerce_adjust_non_base_location_prices() #1 /home/domain/public_html/wp-includes/plugin.php(191): WP_Hook->apply_filters() #2 /home/domain/public_html/wp-content/plugins/woocommerce/includes/wc-product-functions.php(1119): apply_filters() #3 /home/domain/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(2079): wc_get_price_excluding_tax() #4 /home/domain/public_html/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(190): WC_Product->get_price_suffix() #5 /home/domain/public_html/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(167): WC_Product_Variable->get_price_suffix() #6 /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-products.php(216): WC_Product_Variable->get_price_html() #7 /home/domain/public_html/wp-content/plugins/woocommerce/includes/admin/list-tables/abstract-class-wc-admin-list-table.php(261): WC_Admin_List_Table_Products->render_price_column() #8 /home/domain/public_html/wp-includes/class-wp-hook.php(307): WC_Admin_List_Table->render_columns() #9 /home/domain/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() #10 /home/domain/public_html/wp-includes/plugin.php(476): WP_Hook->do_action() #11 /home/domain/public_html/wp-admin/includes/class-wp-posts-list-table.php(1349): do_action() #12 /home/domain/public_html/wp-admin/includes/class-wp-list-table.php(1450): WP_Posts_List_Table->column_default() #13 /home/domain/public_html/wp-admin/includes/class-wp-posts-list-table.php(1383): WP_List_Table->single_row_columns() #14 /home/domain/public_html/wp-admin/includes/class-wp-posts-list-table.php(795): WP_Posts_List_Table->single_row() #15 /home/domain/public_html/wp-admin/includes/class-wp-posts-list-table.php(772): WP_Posts_List_Table->_display_rows() #16 /home/domain/public_html/wp-admin/includes/class-wp-list-table.php(1362): WP_Posts_List_Table->display_rows() #17 /home/domain/public_html/wp-admin/includes/class-wp-list-table.php(1289): WP_List_Table->display_rows_or_placeholder() #18 /home/domain/public_html/wp-admin/edit.php(477): WP_List_Table->display() #19 {main} thrown - /home/domain/public_html/wp-content/plugins/insert-headers-and-footers/includes/class-wpcode-snippet-execute.php(260) : eval()'d code - 6

Can anyone help?

**Comment by indextwo** [comment]
@cigaai It looks like you're using a plugin to insert that code. I don't know how that plugin works, but I would recommend inserting the code directly into your `functions.php` file or a standalone plugin to test if it works as intended.

From the look of the error message, it looks like it's reporting that `WC()` or possibly `WC()->customer` is undefined, as error is reporting that as `null`. I haven't tested this code myself (I can't remember the original issue I opened this thread for - it was 4.5 years ago), but if you simply want to get rid of the error, you could try the following (untested):

```
function filter_woocommerce_adjust_non_base_location_prices( $true ) { 
	$countries = new WC_Countries();

	$eu_countries = $countries->get_european_union_countries(); 

	if (WC()->customer) {
		if (in_array(WC()->customer->get_shipping_country(), $eu_countries)) {
			return false;
		} else {
			return $true;
		}
	}

	return $true;
}

add_filter( 'woocommerce_adjust_non_base_location_prices', 'filter_woocommerce_adjust_non_base_location_prices', 10, 1 ); 
```

**Comment by cigaai** [comment]
> function filter_woocommerce_adjust_non_base_location_prices( $true ) { 
> 	$countries = new WC_Countries();
> 
> 	$eu_countries = $countries->get_european_union_countries(); 
> 
> 	if (WC()->customer) {
> 		if (in_array(WC()->customer->get_shipping_country(), $eu_countries)) {
> 			return false;
> 		} else {
> 			return $true;
> 		}
> 	}
> 
> 	return $true;
> }
> 
> add_filter( 'woocommerce_adjust_non_base_location_prices', 'filter_woocommerce_adjust_non_base_location_prices', 10, 1 );

Perfect! With this new code, it now works without problems.
Thank you very much!

**Comment by alex-riabov** [comment]
Had a nightmare with this the other day. Basically, standard Woo behavior strips the tax when you create a manual order for a 0% tax zone (export), meaning a 150€ item drops to ~142€. I needed to keep the gross price fixed at 150€ regardless of the country.

Here is the fix I added to functions.php. It intercepts the price lookup in Admin and forces the full regular price if it detects a foreign country.

```php
/**
 * FORCE REGULAR PRICE FOR MANUAL EXPORT ORDERS
 * Logic:
 * 1. If Local (e.g., France) -> Keep standard calculation (Net + Tax = Total).
 * 2. If Export (Germany, USA, etc.) -> Force the Net Price to equal Regular Price.
 * * CRITICAL: You must click "Create" or "Save Draft" AFTER selecting the country
 * but BEFORE adding items for this to work.
 */
add_filter( 'woocommerce_get_price_excluding_tax', function( $price, $qty, $product ) {
    
    // 1. SECURITY: Run this only in Admin
    if ( ! is_admin() ) {
        return $price;
    }

    // 2. DETECT COUNTRY: Fetch from the order object in the DB
    $country = '';
    if ( isset( $_POST['order_id'] ) ) {
        $order   = wc_get_order( absint( $_POST['order_id'] ) );
        
        // Looks for Billing Country first, then (if Billing Country is empty) Shipping
        $country = $order ? $order->get_billing_country() : '';
        if ( empty( $country ) && $order ) {
            $country = $order->get_shipping_country();
        }
    }

    // 3. DEFINE YOUR BASE COUNTRY (Keep standard logic for this one)
    $base_country = 'FR'; // <--- Change this to your shop's base country

    // CASE A: Local Country or Country not set yet
    // Standard WooCommerce behavior (Strips tax, then adds it back).
    if ( empty( $country ) || $country === $base_country ) {
        return $price;
    }

    // CASE B: Export / Rest of World
    // Force the price to be the full Regular Price (effectively 0% tax, full margin).
    return (float) $product->get_regular_price() * (int) $qty;

}, 99999, 3 );
```

Important workflow note: Because this relies on the order knowing the country before it calculates the price, you have to follow this exact order:

1. Create the manual order.

2. Set the country.

3. Press "Create" (or Save) first.

4. Then add the products.

If you add products before saving the country, it defaults to your base country logic. Also, if you need to edit the country on an existing order, you can't just switch it. You have to remove all the products, click Update to save the new country context, and then add the products back.
