### ISSUE TITLE
strtoupper() cannot make accents uppercase

### ISSUE THREAD

**Issue by edirpedro** [woocommerce/woocommerce#19084]
In emails templates using plain text, the function `strtoupper()` fails with characters using accents. The function should be `mb_convert_case()` or `mb_strtoupper()`.

```
echo strtoupper( sprintf( __( 'Order number: %s', 'woocommerce' ), $order->get_order_number() ) ) . "\n";

Results in: NúMERO DO PEDIDO: 123
```

**Comment by claudiosanches** [comment]
Closed in favor of #19086
Thanks for reporting it.

**Comment by Colir** [comment]
Hello. Still strtoupper in address format in "get_formatted_address function"

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-countries.php#L581

Thank you

**Comment by claudiosanches** [comment]
@Colir Thanks for reporting it, I just created a new PR to fix it.
