### ISSUE TITLE
If updated from WC 3.1 to 3.3, will 3.2 DB updates be called in the background or not?

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#19082]
The DB version 3.2 has the `wc_update_320_mexican_states` function which need to be called. So if I update my client store from WooCommerce 3.1 to 3.3 then is the WC 3.2 DB updates callback functions called in the background or not. If not should we have to update with WooCommerce 3.2 and after its DB update we should again update to WooCommerce 3.3 or is there any ease process?

**Comment by mikejolley** [comment]
All updates between versions are ran. So if you update from 3.1 to 3.3, all functions in-between, including that one, will be ran too.
