### ISSUE TITLE
Bugs on Order Details

### ISSUE THREAD

**Issue by mayuri124** [woocommerce/woocommerce#19081]
![error](https://user-images.githubusercontent.com/36731034/36535413-81e99e7c-1804-11e8-88d4-45e065e81b66.JPG)

hello, need help on the order detail bug. please check the image

**Comment by mikejolley** [comment]
Whatever you have outputting that data (likely theme file) it's escaping HTML so it's output like that ^ You'll need to fix the theme - it's not core.
