### ISSUE TITLE
Product thumbnail changes in customizer not taking affect

### ISSUE THREAD

**Issue by CJSmithPhotography** [woocommerce/woocommerce#19093]
Upgraded to latest version of Woocommerce today 22/2/2018.

My new product thumbnails are automatically at a ratio of 1:1.

I go to customized and make sure that I check the Ratio as uploaded option. Nothing changes.  

I go to custom ratio of 3:2 and again nothing happens to the visual appearance.

I just leaves it as a hard 1:1 crop.

I hope this is a simple fix as I spent ages on making my thumbnails look great

Thanks

**Comment by claudiosanches** [comment]
Missing a lot of information here to debug it.
Just following this steps I'm not able to reproduce.
Probably better follow the issue template that you have deleted.
