### ISSUE TITLE
tax_rate_name erased with "Tax" text on each settings update

### ISSUE THREAD

**Issue by brouardt** [woocommerce/woocommerce#19092]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. change the value in the TAX name column with a different word than "Tax" (eg "VAT") in the tab tax settings
2. save
3. reload page
4. The name is " Tax" and Shipping is always on

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
Environnement WordPress
Version WC :		3.3.3
Version WP :		4.9.4
WP multisite :		–
Limite mémoire WP :		512 MB
Mode débogage WP :		–
Cron WP :		–
Langue :		fr_FR

Environnement serveur
Info serveur:		Apache
Version PHP:		7.2.1
Poids Max Post PHP:		130 MB
Limite d’exécution PHP:		300
PHP Max Input Vars:		16000
Version de cURL:		7.38.0, OpenSSL/1.0.1t
SUHOSIN installé:		-
Version MySQL:		5.6.34
Taille maximale de téléversement:		64 MB
Le fuseau horaire par défaut est UTC: ok
fsockopen/cURL:	ok
SoapClient:	ok
DOMDocument: ok
GZip: ok
Chaînes multi-octets: ok	
Remote post: ok	
Remote get:	ok	

Base de données
WC version base de données:		3.3.3

Sécurité
Connexion sécurisée (HTTPS): ok	
Cacher les erreurs aux visiteurs ok	

Extensions actives (14)
Redux Framework	 	par Team Redux – 3.6.8
Journal d’activité	 	par Yakir Sitbon, Maor Chasen, Ariel Klikstein – 2.4.0
Jetpack par WordPress.com	 	par Automattic – 5.8
Mode Maintenance	 	par Lukas Juhas – 2.4.3
Login LockDown	 	par Michael VanDeMar – v1.7.1
Theme4Press Core	 	par Theme4Press – 1.4.2
TinyMCE Advanced	 	par Andrew Ozz – 4.6.7
Cookie Consent	 	par Catapult_Themes – 2.3.9
WooCommerce Stripe Gateway	 	par WooCommerce – 4.0.6
WooCommerce Services	 	par Automattic – 1.11.0
WooCommerce Local Pickup Plus	 	par SkyVerge – 2.0.1 – 2.3.7 est disponible – Non testé avec la version active de WooCommerce
WooCommerce	 	par Automattic – 3.3.3
Yoast SEO	 	par L’équipe Yoast – 6.3.1
WP-Optimize	 	par David Anderson, Ruhani Rabin, équipe Updraft – 2.2.0

Réglages
API activé:	ok
Forcer le SSL: ok		
Devise		EUR (€)
Position de la devise		right
Séparateur milliers		
Séparateur décimal		,
Nombre de décimales		2
Taxinomies : types de produits		external (external), grouped (grouped), simple (simple), variable (variable)
Taxinomies : visibilité produit		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)

Pages WC
Base boutique:		#484 - /boutique/
Panier:		#485 - /panier/
Commande:		#486 - /commande/
Mon compte:		#487 - /mon-compte/
Conditions générales de vente et d’utilisation:		#493 - /cgv/

Thème
Nom:		evolve Plus Child
Version:		2.8.2.1516633672
URL de l’auteur:		http://theme4press.com
Thème enfant:		
Nom du thème parent:		evolve Plus
Version du thème parent:		2.8.2
URL de l’auteur du thème parent:		http://theme4press.com
Support WooCommerce:		
Modèles HTML
Remplacements	 	
evolve-plus-child/woocommerce/cart/cart.php, 
evolve-plus-child/woocommerce/checkout/form-checkout.php, 
evolve-plus-child/woocommerce/checkout/review-order.php, 
evolve-plus-child/woocommerce/checkout/thankyou.php, 
evolve-plus-child/woocommerce/content-product.php, 
evolve-plus-child/woocommerce/global/quantity-input.php, 
evolve-plus-child/woocommerce/loop/loop-start.php, 
evolve-plus-child/woocommerce/loop/pagination.php, 
evolve-plus-child/woocommerce/myaccount/dashboard.php, 
evolve-plus-child/woocommerce/myaccount/my-account.php, 
evolve-plus-child/woocommerce/single-product/add-to-cart/variable.php, 
evolve-plus-child/woocommerce/single-product/product-image.php, 
evolve-plus-child/woocommerce/single-product/product-thumbnails.php, 
evolve-plus-child/woocommerce/single-product/short-description.php, 
evolve-plus-child/woocommerce/single-product/tabs/description.php, 
evolve-plus-child/woocommerce/single-product/title.php
</details>

**Comment by mikejolley** [comment]
Extension may be syncing these tax rates so you cannot change the value. On a clean install it's working fine. See:

![woocommerce settings local wordpress dev wordpress 2018-02-22 16-46-49](https://user-images.githubusercontent.com/90977/36551700-19b65b10-17f0-11e8-9e09-900b63797f4b.png)

If you narrow the issue down to a certain extension that will be helpful. Looking at status report I don't think you've actually tried this:

> This bug happens with only WooCommerce plugin active

Closing as this is not reproducible with given steps.

Thanks
