### ISSUE TITLE
Attribute Type "Fix" Has broken 10 client sites

### ISSUE THREAD

**Issue by bobteree** [woocommerce/woocommerce#19099]
I have posted this at Wordpress.org in plugin forum, but trying to escalate the "fix" regarding removing the ability to define "Attribute" "Type". Below I detail why we need the ability to define the "Type" of attribute (e.g. select from drop-down vs free text). WE NEED FREE TEXT. What was the rationale for removing that feature?

FROM MY POST at .org:

This “fix” is a terrible fix. What was the problem that was attempting to be fixed?! Here are the massive issues this has caused:

1) Attributes used to be a flexible way to store both public (customers can see) and private (store owners can see) way of including critical information relating to a store’s products. Use case 1: I used to have a PRIVATE attribute called “Source” I used this value to store free text that was both editable on the fly (i.e. you could update on the product page). An example would be: Source = ($15/unit without shipping from XYZ supplier. Minimum order quantity 100). This has now turned into a mandated “Select” type and is no longer a “Free Text” type. It is utterly useless now. Perhaps this is a misuse of the Attribute feature, but there is NO other native way to store private information regarding a store’s products now. You have turned the feature into a forced-select-only tag machine, whereas before it was very flexible.

2) You have concatenated ALL of my 1000’s of values! This is a mess. Use case 2: I have an attribute called: “Other Product Numbers”. I use this as these numbers are critical for SEO and to publish to various sales channels like eBay and Amazon. These values used to be free text, such as: “Bosch 1234, Napa 1234, Wix 2345” Now the whole things is a bubble select only mess (i.e. the value is the whole string “Bosch 1234, Napa 1234, Wix 2345” and it ignores commas as it is now a tag, not a free, flexible text string.

This has destroyed a key way we manage our taxonomy and create products. I manage 10 customers in the parts industry and now all of their sites and backends are broken.

I don’t know why you think removing an entire capability is a fix?! What was this supposed to fix?! Before, if you wanted to enforce the uniqueness of an attribute, you could create a Select-Only attribute type so you would not get attributes like: Blue, blue, blu). That is good, but Woo had that ability.

But there are many use-cases where you simply need free, editable text that can be private or public to consumers! This is critical. Another use case would be an attribute called: “Special Note: You should call us before installing this part.” Now you can’t add anything like this that can be published to a website.

I think the problem was that WooCommerce collected, stored, etc. each unique free text entry as an attribute “term”. That should be cleaned up if creating overhead and performance issues. If you select an attribute type to be “free text”, perhaps you remove the ability to manage those terms individually as they aren’t terms, they are just a free text string. So any Attribute that is free text, does not have the ability to have individual terms.

But this has broken 10 client’s sites. Please roll this back as the lack of ability to have free text private and public attributes has killed us. In additional all existing values were concatenated into blobs and are no longer editable from the product page…It’s unusable to create crazy text strings as tags and then delete text strings that were turned into tags.

**Comment by kloon** [comment]
Hi @bobteree 

While I understand that you have been able to make use of the functionality for something it was not intended for, we can unfortunately not support this. The reason we changed it was to simply attributes as the options were confusing to users when it should not have been.

Fact is, attributes are not meant to be used for keeping notes on products, I would highly suggest that you rather have something custom developed that would give you that functionality instead, that way you can be sure you have functionality that is built for it's purpose and without having to worry it would break in the future.

There are solutions on .org where you can have product notes for store admins, perhaps search to find a solution there, otherwise you will have to get this custom developed.

Hopefully, you can see the reasoning behind our decisions here and understand that the way you have been using attributes is not the way product attributes are meant to be used.

**Comment by mikejolley** [comment]
R/e those 2 points on the value being in a bubble and those price values; each time you edited or added one of those a term would have been created. Terms are used for grouping, not unique data. Your usage doesn't scale and I suspect would break eventually due to volume of terms, or length of term name which is limited. 

Product level text attributes can be used in place, or custom fields.  The csv import/export might be useful to edit this in bulk, or you can do it gradually as you edit products. Existing attributes display should continue to work.

**Comment by bobteree** [comment]
Folks,

You have not fully digested the two main use cases for what I will
call  *Enforced
Attribute Names with Free Text Values*

*1) Product Cross-Numbers :* Every technical product (e.g. engine parts,
machine part, etc.) has a product number. Not only that, but it has cross
numbers. So a Wix filter will have Baldwin, Napa, Donaldson, Fram, et. al.
crosses. They each have their own product number that crosses to each
other. Question: How would you recommend displaying this information to a
customer in a structured, consistent way? The former Attribute feature
allowed this easily. That said, I get that storing 2,000 unique values
under an Attribute called: "Other Product Numbers" would pile up the
values, but your solution might not be the best solution. I would suggest
that you allow, as before, the ability to make an Attribute "Selectable" or
"Text". If, text, you should turn off the Attribute value features and
simply keep the Attribute as a free text string. What this solution would
enable is 1) Enforcement of a consistent Attribute title on the front-end
such as: "Other Product Numbers;" 2) It also enforces the person creating
products on the back-end a reminder that that value, which would appear in
a drop-down of Attributes, would be required (not technically, but via
workflow -- namely, it's a configured Attribute name in the drop-down.
Without enforcement of the Attribute value, there is no way to ensure a
consistent end-user experience on the front-end. Now we will have various
product creators creating ad hoc (what you call "custom") Attribute
*names *such
as "Other Product Numbers," "Crosses," "Other Numbers," not to mention
mispellings. When you have 1,000's of products, you can see that there is
no way to enforce this on the backend with multiple product creators. I
would argue that you threw the baby out with the bath water. You solved one
problem (proliferation of Attribute values), but killed a very valuable
feature that allowed free text strings against an enforce Attribute name
(e.g. "Other Product Numbers"). I would also argue that you might have lost
sight of the original use-cases that built the Attribute feature in the
first place and why they allowed text strings versus only a tag structure.
Most of my clients are parts suppliers and cross-reference numbers are the
life-blood of optimal SEO and marketing. Now we have no way to do this, but
we did. *So the ability to enforce consistent Attribute names is no longer
available. *To accuse me of product misuse, is simply not productive. There
is no other way to use WooCommerce for the parts industry. Tags and
Categories don't work. Free text in the product description and Free text
via the Custom Attribute is too loosely-goosey to enforce a consistent
backend workflow and consistent front-end experience. Take this as an
example from a filter on Amazon. I used to be able to mimic this 100%. Now
it's impossible in a scalable way. Practically every single product in
Amazon requires this feature! Please tell me how I am supposed to mimic
this?






*2) Maintaining consistent private notes: *The same old feature was able to
accomplish this, just a different use case. Attribute enforcement of a
private value (e.g. *Source*). This is the private source for a product I
sell that has replenishment details. Yes, this might not be a color, size,
etc. But a critical piece of our business. People that maintain complex
catalogs of products with multiple suppliers, need to keep track of where
they buy their products and other details. Again, this was supported via
the no-publish feature, which you still have, but now their is no way to
enforce the Attribute name (just like #1).

I get that there was a proliferation of Attribute values. But the way to
fix it would be to align the following:

>> If Attribute type was "text", turn off the ability to create and manage
formal values (i.e. the backend is just a text string)
>> If Attribute type was "select," the keep the ability to create and
manage formal values (e.g. color, size, etc.)
>> Keep the ability as you have today of publishing or not publishing the
value.

My parts customers are pissed to no end. This will be hours and hours of
work to clean up 10,000 products across 10 customers and even then, there
is still no way to enforce Attribute names on the front-end. We may ditch
WooCommerce and migrate off the platform as this is unworkable for us and
not sure if any plugin can fix this without complicating the back-end and
front-end code.

I would venture to guess, that EVERY single product listing on Amazon could
not be replicated in WooCommerce due to the above. Every product has UPC,
NSN, ASIN, etc. etc. product codes. There is NO way to replicate this
functionality in WooCommerce now and that is a massive issue. I don't think
users have actually realized what happened and you will receive more and
more complaints related to this. It took me a while to figure out what
broke.

Thank you for listening and your patience. This is such a big issue for us
that it may require us to find a new eCommerce plugin to WooCommerce as it
seems the engineers/product folks have broken a feature more than fixed it
and have completely made it impossible to mimic the most basic of product
listings (enforced Attribute names, with free text values).

Best Regards,
Bob Teree

**Comment by mikejolley** [comment]
@bobteree Going to make a few small points (evening here):

1. "private notes" I hope you understand terms/term descriptions are not designed for private information. They could be exposed through archives/other plugins SEO.

2. I get your point on 'enforcing' names, but what you're doing is still not impossible through the use of custom text attributes. Yes the person doing input would need to add them (or duplicate another product as a template), but unless you're filtering by said attribute (which is doesn't sound like you are) using terms is unnecessary.

3.  > Every product has UPC,NSN, ASIN, etc. etc. product codes. There is NO way to replicate this
functionality in WooCommerce now and that is a massive issue.

Unique data like I said earlier should not be term based. A better solution would be a custom field - it's  not hard to add custom fields/inputs in product admin for this purpose.

---

Attributes are not meant for private notes, and I certainly don't think they best suited for unique product numbers. I appreciate that creative use of these fields could have satisfied those requirements without custom dev, but is that the best for your clients? Probably not. 

Product numbers; use custom input fields, add to regular product data box. Or custom text attribute if this varies per product.

Private notes; Advanced custom fields? More custom product boxes? Both could work.

**Comment by bobteree** [comment]
Thanks for your feedback.

**Comment by mikejolley** [comment]
As for moving data, it wouldn't need to be manual editing. I think a script could be written to migrate the data depending on where it's moving!

**Comment by bobteree** [comment]
Folks,

Coming up 100 feet, the real high-level use-case is this: Take almost ANY product on Amazon and look at it's product details and tell me how one would be able to mimic it in WooCommerce? You can't now! This is CORE functionality. The way categories, tags and attributes are currently implemented, you can't implement this. Custom Product Attributes is not scalable, nor can you enforce the name of the Attribute, which is critical when you are talking about a store with 1000's of products. Taxonomy is a core feature. 

Not only that. We use a plugin from WP-Lab for listing our Woo Products on eBay and Amazon. They queue off of product Attributes in a MASSIVE way. Each eBay product category has requirements and Attributes is the most popular way to meet these requirements. Making Attribute management harder will not be good for stores integrated with eBay and Amazon...

Metadata is everything for SEO, marketplaces and the consumer. You have made it far more difficult and brittle to manage. The confusion you solved was crudely solved by removing functionality, not by looking at real use-cases and requirements.

Sorry, but you will surely hear more from folks as most have no idea you even changed this feature and did a forced data migration...

Regards
