### ISSUE TITLE
Archive Product Shop Page not working after update to 3.3.0

### ISSUE THREAD

**Issue by alexscro** [woocommerce/woocommerce#19094]
Hello!

After updating to the new version, the archive-product.php in the root directory of our child theme is not called anymore. Moving it into the woocommerce folder results into the same. 
The shop page is therefore not displayed.

Help really appreciated!

Best, Alex

**Comment by mikejolley** [comment]
See this https://wordpress.org/support/topic/guide-for-declaring-woocommerce-support-in-themes/

It won't load template files unless you declare support.
