### ISSUE TITLE
Fatal error:  Uncaught Error: Call to undefined function wc_implode_html_attributes() in templates/loop/add-to-cart.php:30

### ISSUE THREAD

**Issue by titandoo** [woocommerce/woocommerce#19090]
<b>Fatal error</b>:  Uncaught Error: Call to undefined function wc_implode_html_attributes() in public_html/wp-content/plugins/woocommerce/templates/loop/add-to-cart.php:30
Stack trace:
#0 public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(211): include()
#1 public_html/wp-content/plugins/woocommerce/includes/wc-template-functions.php(865): wc_get_template('loop/add-to-car...', Array)
#2 public_html/wp-includes/class-wp-hook.php(286): woocommerce_template_loop_add_to_cart(Array)
#3 public_html/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters(NULL, Array)
#4 public_html/wp-includes/plugin.php(453): WP_Hook-&gt;do_action(Array)
#5 public_html/wp-content/plugins/woocommerce/templates/content-product.php(68): do_action('woocommerce_aft...')
#7 public_html/wp-content/plugins/woocommerce/in in <b>public_html/wp-content/plugins/woocommerce/templates/loop/add-to-cart.php</b> on line <b>30</b><br />

**Comment by mikejolley** [comment]
Function was added in 3.3 https://github.com/woocommerce/woocommerce/blob/380ee9a13fd904c3b61fece051652ee387563436/includes/wc-formatting-functions.php#L1320

Error could occur if using this function/template file in an older version. Perhaps theme is including 3.3 template file which calls this function but you're not using 3.3 yet. Would need a version conditional in the theme.

You should update to 3.3 to prevent the error.
