### ISSUE TITLE
Why Non Product specific coupon is subtracting the price in order item total ?

### ISSUE THREAD

**Issue by prasidhda** [woocommerce/woocommerce#19108]
When applying the fixed cart type of coupon, it is subtracting the equal amount of price from the product order items. Doesn't is supposed to apply to product items only for product specific coupon codes.

**Comment by mikejolley** [comment]
The discount is split across all items so taxes are apportioned correctly. Taking an amount from the grand total would not do this and you'd change too much sales tax.

**Comment by prasidhda** [comment]
Then how do you get the amount of coupon discount for each of the order items when there are multiple coupons applied with different nature? I have spent more than 2 days but couldn't find a perfect way to get the exact amount of coupon discounts.

**Comment by mikejolley** [comment]
You can get the amount discounted from the coupon line item - it keeps a total. Hover over the coupon code in admin whilst viewing an order and you'll see the total.

**Comment by prasidhda** [comment]
Yes, it gives the total discount price but i need the discount amount for order item.

**Comment by mikejolley** [comment]
Thats not stored. You won't be able to track that from coupons.
