### ISSUE TITLE
Admin Order Preview Line Items & Quantity

### ISSUE THREAD

**Issue by albert-pws** [woocommerce/woocommerce#19103]
Hello, 

I have a custom product information, price, & quantity in my product based on my website needs and need to override the woocommerce default price and quantity. For overriding a price, I don't have a problem but unfortunately I can't override the quantity, it seems like I haven't found a solution yet as I go over the internet.  Does anyone know how to override the woocommerce default quantity? Btw, here's my code for overriding the woocommerce default price: 

![custom-price-code](https://user-images.githubusercontent.com/32151880/36575152-4f5371e2-1884-11e8-9357-e75bb7af8471.png)

Also, about custom product information, I need to display this in the order detail and order preview modal. Does anyone know how to add a custom product information in the order preview modal? FYI, It will display already in the order detail and used this hook 'woocommerce_after_order_itemmeta'.  

Please see these screenshots below for reference:

View Order detail: 
![view-order](https://user-images.githubusercontent.com/32151880/36574949-00027a76-1883-11e8-9436-004ed144d593.png)

Order Preview Modal: 
![preview-order](https://user-images.githubusercontent.com/32151880/36574951-03cef238-1883-11e8-80e6-73bd72a12f76.png)

Using:
Woocommerce 3.3.3
Wordpress 4.9.4

Thanks!

**Comment by WPprodigy** [comment]
There is a `set_quantity` method you can call on the cart object: https://github.com/woocommerce/woocommerce/blob/906efe1ffccbbba4ed7af0e98d1f5134bf67c5f7/includes/class-wc-cart.php#L1185

Need to pass it the cart item key though, not just product id.

______

And then the extra product fields from [Product Add-Ons](https://www.woocommerce.com/products/product-add-ons/) do show up in this area: http://cld.wthms.co/q3vPmj. So it has to do with what hooks you are (or aren't) using. Can see the output code here: https://github.com/woocommerce/woocommerce/blob/2a7b09cb52a857f8d8b56a98d5705f5fa50f8ff1/includes/admin/list-tables/class-wc-admin-list-table-orders.php#L479-L490

**Comment by mikejolley** [comment]
`woocommerce_order_item_get_formatted_meta_data` can append data to that area in the preview window.

https://github.com/woocommerce/woocommerce/blob/af6bfd22fda7c78b3ad87e66d36a043d9fd7656f/includes/class-wc-order-item.php#L283
