### ISSUE TITLE
ERROR: Edit Product site - Variations/Attributes are hidden

### ISSUE THREAD

**Issue by TrineTheViking** [woocommerce/woocommerce#19106]
I've noticed two similar errors on the Edit Product site.
The error makes it impossible to add attributes and variations, while I can't see 1/3 of the edit box. The editor is like that, regarding what screen size I'm using. Appeared after the WC 3.3+ update.

Please fix it as fast as possible!

![support - attributes in woocommerce](https://user-images.githubusercontent.com/36758918/36585695-3a3ad156-187f-11e8-9a86-94fd0f04e2f5.JPG)

**Comment by mikejolley** [comment]
This one isn't happening on clean installs so it appears to be a conflict with a plugin, not the update. I'm also pretty sure that this part of core didn't change in 3.3.

Try turning off advanced label/custom tabs extensions to start. You'll need to find the plugin thats conflicting. 

```
## Isolating the problem

<!-- MARK COMPLETED ITEMS WITH AN [x] -->

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above
```

^ Please don't report issues on GitHub without doing these steps first. We don't fix 3rd party plugins here.

Thanks
