### ISSUE TITLE
Woocommerce “woocommerce_product_get_price” issue

### ISSUE THREAD

**Issue by thetipico** [woocommerce/woocommerce#19107]
The filter "woocommerce_product_get_price" to show a custom price works but casually I have discovered that this filter is triggered five times in single product page and six times in the archive product page. This I have checked including a var_damp in the following way:
```
    add_filter('woocommerce_product_get_price', 'get_ws_price', 10, 2);
    function get_ws_price($price, $product){
        var_dump('HI!');
        // Code
        return $price;
    }
```
This is a problem for me, I use this filter to perform complex code and is repeating them many times.
What am I doing wrong? Is there another way to modify the price of the product with another hook?

**Comment by mikejolley** [comment]
It's called when we get price, so it's bound to run multiple times. Store something to the current object so it's not repeated for the same product? Use cache? There are ways to speed up complex logic even if it needs to repeat.

Not a core plugin; the filter has to run whenever price is called.

**Comment by thetipico** [comment]
My situation is a bit special but it should be easy to solve. The products are loaded in the WP db without price, when a user logs the product views they call a web service to download the price based on the user's properties. For this reason the hook "woocommerce_product_get_price" is very useful because it modifies the product object and I can process it without problems in the cart.

If I use cache, could I assign the prices to a specific user?

**Comment by mikejolley** [comment]
You can use wp_cache yes. And you could make the cache key contain the user ID.

**Comment by thetipico** [comment]
Works fine! Thanks!!

**Comment by dejanj27** [comment]
Hello, I stuck on the same thing. Could you please explain a bit more what should I do since I don't understand concept of wp_cache. This is the only place where I found this topci :(

**Comment by thetipico** [comment]
For me it was a problem of approach, my filter was connected directly to an external api where the price was evaluated based on a complex system of discounts.

Our solution was to create a transient to store the user, sku and price.

- So in the filter, we first check if there is a transient for that user / product
- If not, we create a new transient to be evaluated by the following filter

You must plan the duration of the transient and in which situation you must delete them all.

[https://codex.wordpress.org/Transients_API](url)

**Comment by dejanj27** [comment]
To be honest, I'm quite new to transients, but I kind get what is your solution. My problem is the same. I have developed woocomerce website, where every customer may have different price for products. For every customer I have API request to fetch prices for every product. 

So, if I understood correctly, what you did is cache this API response as user, sku and price, and then update it using woocommerce_product_get_price. Only thing I don't understand is how you pass a value to woocommerce_product_get_price from cache. 

Sorry if I bother you. I'm stuck on this for some time.

**Comment by thetipico** [comment]
The general idea is that every time "woocommerce_product_get_price" is triggered check if there is a transient for that user / product. If it does not exist you will have to create it, if the price exists it is stored in the wp_options table and the response will be fast (as fast as get the "regular_price" meta of the product).

Depending on the logic of your api you must decide what the transients will store inside:

- users with an array of products and prices
- products with an array of users and prices

https://developer.wordpress.org/reference/functions/set_transient/

**Comment by dejanj27** [comment]
I think I can manage it now. Thank you very much! Very kind of you.
