### ISSUE TITLE
Shoppage added content is gone on page 2 and above

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#19102]
If You add content to a shoppage body content that content shows only on the first page. When you goto the second page its gone.

This is i believe incorrect. The content which one adds before the shop items kick in should show on any page.

How to correct this?
![woo-shop](https://user-images.githubusercontent.com/6078370/36571334-85089842-1836-11e8-9f5e-f970c34e3983.png)

**Comment by WPprodigy** [comment]
You can override this function, or unhook it and hook in your own: https://github.com/woocommerce/woocommerce/blob/f2d90deec4d9546eb4a5a788189a05960e92d3f7/includes/wc-template-functions.php#L818-L833

And remove this part `&& 0 === absint( get_query_var( 'paged' ) )`

**Comment by WPprodigy** [comment]
I don't think this behavior should be changed by default though. Showing the same content over and over again just obstructs the view of searching through products.

**Comment by kloon** [comment]
As @WPprodigy said, this behavior will not change, we have had people in the past complain about it displaying on every page also hence why it works the way it does.

If you really want to display it you can basically copy the function @WPprodigy linked to and just remove the `&& 0 === absint( get_query_var( 'paged' ) )` part to make it show on every page.

**Comment by BackuPs** [comment]
@kloon 

So if users complain you remove it and if they complain it should be the other way around you dont add it back in...  hahaha so funny   

Maybe It should have been a setting in the woo settings then to serve both sides of the complaining users.

Anyway I am fine with the offered solution and will change the function. Thank you for the pointing me into the right direction.

Have a good weekend !

**Comment by kloon** [comment]
> So if users complain you remove it and if they complain it should be the other way around you dont add it back in... hahaha so funny

If we were to change it back then the other party would just come back again and complain, we cannot change and change back at each request.

> Maybe It should have been a setting in the woo settings then to serve both sides of the complaining users.

Our philosophy in core is to keep settings to a minimal, as too many settings just confuse users. That is why when we made the change initially we made the function pluggable so there is a way to customise it to your needs should you wish.

You can basically just copy that function to your theme's functions.php file and make the changes as I mentioned and it should work.

**Comment by BackuPs** [comment]
@kloon 

I am fine with pluggable functions. But if i ask to make one pluggable i get a rejection from the woo team..  LOL.

https://github.com/woocommerce/woocommerce/issues/19052

So that contradicts what you are saying.

**Comment by BackuPs** [comment]
there is still a bug 

clicking on page 1 again creates this  http://wp.tst/?post_type=product&paged=1

then the content still does not show although we are on the first page in the shop page !
