### ISSUE TITLE
Woocommerce (backend) > orders, wrong ordering  

### ISSUE THREAD

**Issue by MajkieS** [woocommerce/woocommerce#19105]
Hello,

when I open up woocommerce orders tab. It shows all orders but not sorted by order id. It is weird, how can I make it by default like that?

Thanks.

**Comment by mikejolley** [comment]
ID sorting is the default. If you're not seeing this it means a plugin is changing the default, or the columns in the list table have been customised and it's sorting by a different column.

As always, go through the steps on the new issue form. We can't debug active plugins for you.
