### ISSUE TITLE
Conditionals on theme where WooCommerce supports is not set. 

### ISSUE THREAD

**Issue by jespervnielsen** [woocommerce/woocommerce#19112]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Run WooCommerce on a non combitiable theme.
2. Edit page.php to check for is_woocommerce(), and is_product_category() conditionals return values

## Expected/actual behavior

When I follow those steps, I see...
Conditionals are returning false, on product category page, witch uses page.php
the filter widgets (attributes and price) is not working. (not seeing it as a WooCommerce Page)
The queried object, is correct. it contains info about product category

I was expecting to see...
Conditionals should be returning true on product category page even throug they are using page.php 
Filter widgets should work, even on non themes not declaring theme support.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

*WooCommerce 3.3.3

**Comment by mikejolley** [comment]
@claudiulodro Consider this a bug? Template loader purposely turns this query into that of a `page` so queries such as is_tax no longer return true. Should we add special handling there?

> Filter widgets should work, even on non themes not declaring theme support.

There are limitations if you're using a non-WC theme, so whilst nice to have, this should not be a given. Theme support is needed to support all features.

**Comment by jespervnielsen** [comment]
Hello Mike Jolley.

Thank you very much for your answer

> There are limitations if you're using a non-WC theme, so whilst nice to have, this should not be a given. Theme support is needed to support all features.
That is ofcourse alright. But when trying to use those widgets, no info is given that they may not be shown because of theme compatibility. And when declaring theme support (even just for images), the page looks broken, because the wrappers must be changed using hooks. That's fine, but hard to explain to a client that when the shop looks 90% complete and some standard WooCommerce widgets do not work because there is no theme support. When theme support is added, then "breaks" the layout. which makes styling, etc., to be corrected.

But for now, we are just goint back to the "old" way, and customizing by controlling the wrappers using hooks, declaring theme support ect.. :)

I had just read the docs, and release notes (3.3) about theme support, and It was my understanding that theme support would only be declared if it was before 3.3 or if you as a theme developer would have control over image size, columns and the like.
So, the "old" method, with hooks to control wrappers, may still be said to be the correct one, with the eyes of a developer who wants control. :)

And the "new" way, is just like using woocommerce_content() in the files, in a page.php copy.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19160
