### ISSUE TITLE
dashboard.php and my-account.php templates weirdly placed action hooks

### ISSUE THREAD

**Issue by monecchi** [woocommerce/woocommerce#19115]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use `woocommerce_account_content` and `woocommerce_account_dashboard` action hooks
2. Try to insert any content **above** or **bellow** the hard-coded "user greetings text" under [dashboard.php](https://github.com/woocommerce/woocommerce/blob/master/templates/myaccount/dashboard.php#L26-L42).
3. It fails because the `dashboard.php` and `my-account.php` templates have their action hooks positioned weirdly, preveting that way any content to be inserted above or bellow the hard-coded "user greetings text".

## Expected/actual behavior

Following a (not offcial) WooCommerce visual hooks [guide](https://businessbloomer.com/woocommerce-visual-hook-guide-account-pages/), I'd expect to be able to insert any kind of content **above** or **bellow** the hard-coded "user greetings text" under **My Account** page while using the `woocommerce_account_content` and `woocommerce_account_dashboard` action hooks respectively.

However, by inspecting the `dashboard.php` template, the hard-coded "user-greetings" sits static above all the available action hooks under My Account page respective templates. That makes it hard for a plugin or theme developer to wisely place anything such as an avatar, an icon, a title etc. right on these template areas considering the actual My Account templates set up....

The only way I've overcame this issue was by editing and overriding both templates so they'd resemble the same behavior the screenshot bellow illustrates.

As long as the hard-coded "user greetings text" is there, I was expecting to see a better positioning for the aformentioned action hooks, so I could place anything above or bellow it.

## Not Official (My Account) visual hook guide reference:

![woocommerce-visual-hook-guide -my-account-pages](https://user-images.githubusercontent.com/5252519/36624394-604ef2e6-18ed-11e8-8004-874c5da21526.png)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

```
WC Version: 3.3.3
WP Version: 4.9.4

```
</details>

**Comment by mikejolley** [comment]
The dashboard template is hooked into `woocommerce_account_content`, so you can use that to insert before by using an earlier priority on the hook than 10 (which is default).

Alternatively you can replace the template file either via template override or filter (to load a different template).

Another solution would be to insert the text itself via a hook but we'd like to avoid too many template changes at this point to the template system to avoid conflicts with themes.

Thanks
