### ISSUE TITLE
Rest API: Missing first product when using 'include' and array.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#19114]
I ran into this while working on the Products block. It's not a blocker or anything; I can just use the comma-separated version of the API call.

(all of these are valid products and exist)

1. For the following API call: `http://local.wordpress.test/wp-json/wc/v2/products?per_page=3&include=[808,798,797]&orderby=include` I get info on two products for the result: Ones with IDs 798 and 797. The first product in the list is always missing.

<img width="789" alt="screen shot 2018-02-23 at 12 01 08 pm" src="https://user-images.githubusercontent.com/7317227/36614369-4872a534-1891-11e8-90fe-2688f16d20df.png">

2. For the following API call: `http://local.wordpress.test/wp-json/wc/v2/products?per_page=3&include=808,798,797&orderby=include` I get all three products back.

<img width="736" alt="screen shot 2018-02-23 at 12 00 48 pm" src="https://user-images.githubusercontent.com/7317227/36614377-5261734a-1891-11e8-9227-f65d14e5637b.png">

I expect them to give identical results (or at least the array version to work correctly since it's the documented way of doing it).

**Comment by WPprodigy** [comment]
Looks like the first include always ends up at `0`. Another, yet hacky, workaround would be to start with a comma: `include=[,808,798,797]`. Leaving off the brackets also works `include=362,363,364`

**Comment by WPprodigy** [comment]
This is what's happening: https://github.com/woocommerce/woocommerce/blob/2b1aed56b7e8cea4598b3bdb75c21d573aa43ccd/includes/abstracts/abstract-wc-rest-crud-controller.php#L539-L547

[`wp_parse_id_list`](https://developer.wordpress.org/reference/functions/wp_parse_id_list/) wants an actual array(), or comma separated list.

Probably needs to be fixed for `exclude` as well.

**Comment by WPprodigy** [comment]
Not 100% sure what the best way to proceed is though.

1) Drop support for `[]` syntax in the URL (just docs update)
2) Create `wc_parse_id_list` helper function and use that instead.
3) Along with 2, maybe open up an issue WP trac, since it does seem like buggy regex.

**Comment by claudiulodro** [comment]
After looking through @WPprodigy's research, I don't think option 1 is actually a supported format for the API. The correct way to do it would be `http://local.wordpress.test/wp-json/wc/v2/products?per_page=3&include[]=808&include[]=798&include[]=797&orderby=include` like a regular GET array, and that seems to work great.

Thanks for your help @WPprodigy!

**Comment by claudiosanches** [comment]
The correct URL is:

```
http://local.wordpress.test/wp-json/wc/v2/products?per_page=3&include=808,798,797&orderby=include
```

There no need for arrays.
Still the last example of Claudiu works too.
