### ISSUE TITLE
Invalid nonce when the main site is https but the current page is http.

### ISSUE THREAD

**Issue by cesar-prospress** [woocommerce/woocommerce#19116]
There is a rare issue that happens when the entire site is running on `https`, the current page is `http` and the latter is executing an ajax request.

We encountered [this issue](https://github.com/Prospress/woocommerce-one-page-checkout/issues/296) on one of our plugins and [we fixed it](https://github.com/Prospress/woocommerce-one-page-checkout/pull/306) by just redirecting the current page to its `https` version. In our plugin it was happening more often because adding a product and doing the checkout happens on the same page.

I'm eager to get this issue fixed on WooCommerce. I realized it is not much of a problem because all the links generated by WooCommerce will have the correct `https` (if the site is `https`), so chances are the average visitor will never experience this issue.

It's reproducible though:

  1. Add [this product](https://gimme.subscription.beer/james/product/monthly) to your cart.
  2. Go to [checkout](https://gimme.subscription.beer/james/checkout) and everything works[1].
  3. Now open the [http version](http://gimme.subscription.beer/james/checkout), you'll notice it keeps loading forever. That's because the `?wc-ajax=update_order_review` action returns `-1` because the nonces mistmatches.

I don't know how to properly fix, I think this needs a bit of discussion. What we can all agree is that the solution is simple:

From the top of my head these are the solution I see for the issue[2]:

  1. We just redirect it to`https`, no question asked. That's pretty much how [we fixed this issue on our end](https://github.com/Prospress/woocommerce-one-page-checkout/pull/306/files)
 2. We fixed it in the checkout page by enabling `woocommerce_force_ssl_checkout`. While this would fix the scenario I described, I still believe that some plugins may have problems under the scenario I described[1].
  3. We change the nonce generation to accept https/http. I did not research much about this possibility, but I think this may have unwanted side effects.

What are you thoughts?

[1] The page loads correctly, and ajax requests for things like shipping method changes process correctly.
[2] If website is configured to run on `https` (` parse_url( home_url( '/' ), PHP_URL_SCHEME )`) but the current page is `http`

**Comment by LetMeKnow1** [comment]
If you are using HTTPS you should force it in your server settings.
That way any page on the server will reload as HTTPS even if someone typed HTTP

Example:
https://il.godaddy.com/en/help/redirect-http-to-https-automatically-8828

**Comment by cesar-prospress** [comment]
> You should force rule for HTTPS in your server settings.
> That way any page on the server will reload as HTTPS even if someone typed HTTP

That's not the point though, that's how to fix an individual server (with configuration). But I believe that Woocommerce should address this issue as well, it's a rare condition but it does happen.

**Comment by mikejolley** [comment]
Disabling the nonce check breaks and says the session is expired, presumably due to the different URL/cookies.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19139 - feedback welcome. That fixes this specific issue without a redirect.

**Comment by cesar-prospress** [comment]
> See #19139 - feedback welcome. That fixes this specific issue without a redirect.

That's excellent! Thank you.
