### ISSUE TITLE
Customizer Live Preview Saving Problems

### ISSUE THREAD

**Issue by gwgw** [woocommerce/woocommerce#19117]
Hello, i'm developing new WP Theme,that supports Woocommerce,
locally on xampp - localhost, system windows 7, php 7.2,lastest WC version
Yesterday, suddenly my Customizer Live Preview stop saving changes.
But its wrong, after visiting frontend changes are saved.
 Each time i try to save changes i got notices:

Looks like something’s gone wrong. Wait a couple seconds, and then try again.
And second one,if i try save again:
The previous set of changes has already been published.
 Please try saving your current set of changes again.

I though that is my custom controls registered for customizer,so i remove them,
but problem still exist while editing default customizer options, so i roll back to my previous
theme version,when everything works properly,and now its not,its also stopped working...
I tried clearing cache, disable plugins 
- i installed only WC ,and Customizer started working properly after i deactivate WC.
So i activate WC again,removed all custom controls,styles and scripts,
and still nothing. I don't have any fancy functions,or plugins installed.
The weird thing is,when i try save settings later,it works fine for shortt time,
and then its stops working again. It working all the time if WC is disabled.
My output for debug.log shows error each time i try to save options,it says:
Maximum execution time of 30 seconds exceeded in ....path here...
So i increased memory limit in wp-config.php, and still nothing, 
trying to save options take about 8 seconds,and then outputs first notice.

I don't know what is wrong with my theme/wc and how to fix it
I wipe out every setting from my theme that is related with Customizer,
and nothing goes better,sorry for my poor English.

**Comment by gwgw** [comment]
I found what cases my problem with saving options in customizer live preview.
In one of my functions i added number foreach published product,like this:
if (!function_exists('aldente_wc_add_product_number')) {
  
    function mytheme_wc_add_product_number()
    {
        global $wpdb;

        $querystr = "SELECT {$wpdb->posts}.* FROM $wpdb->posts WHERE {$wpdb->posts}.post_status ='publish' 
    AND {$wpdb->posts}.post_type = 'product' ";
        $pageposts = $wpdb->get_results($querystr, OBJECT);
        $counts = 0;
        if ($pageposts):
            foreach ($pageposts as $post):
                setup_postdata($post);
                $counts++;
                add_post_meta($post->ID, 'aldente_wc_product_number', $counts, true);
                update_post_meta($post->ID, 'aldente_wc_product_number', $counts);
            endforeach;
        endif;
    }
    add_action('publish_post', 'mytheme_wc_add_product_number');
    add_action('deleted_post', 'mytheme_wc_add_product_number');
    add_action('edit_post', 'mytheme_wc_add_product_number');
}

I'm not sure why, but when i deleted this function customizer dont  work so slow anymore,
and if i try to save my changes they are saved fast.
Any idea why hooking into this 3 actions cases problems with WC and Customizer?

**Comment by WPprodigy** [comment]
Why looping through every single product, and updating the post meta for each one every time a post is edited? That's asking for bad performance :)

If you need sequential product numbers for some reason, I'd recommend taking note of how this plugin does it for orders: https://wordpress.org/plugins/woocommerce-sequential-order-numbers/. You don't want to be looping through everything and performing database updates for each and every one.

This isn't really something we can help support though. Your customizations are causing the errors.

**Comment by gwgw** [comment]
Hello, thank you for respond, I know that this function is bad for performance :(
But i don't want to add numbering to orders, but for products, something like unique id  value.
Could you,please, explain this to me, how my fuction is related with saving options in customizer live preview?
I mean, sometimes i only change background-color for body, so its not even related to editing posts/products...
I need to find a better way to do this....so many hours wasted ;/

**Comment by WPprodigy** [comment]
> But i don't want to add numbering to orders, but for products, something like unique id value.

Right, but the process is pretty much exactly the same as making order IDs sequential. And the plugin I linked to does it a lot more efficiently. 

I'm not 100% sure why your hooks are running in the customizer, but I'm thinking maybe the new customizer change sets are using a post type perhaps to save them. And your snippet is running the very inefficient query no matter what post type is being saved...

I'd recommend at least checking if the current post type being edited is of the product type before doing the logic.

Like I said though, we can't support customizations like this and/or tell you what code you need to write. If you can't quite figure out what code you need, I'd suggest looking for a [WooExpert](http://www.woocommerce.com/wooexperts/?utm_source=ZenDesk&utm_medium=ticket-reply&utm_campaign=Custom%20Referral) or contacting [Codeable](https://woocommerce.com/codeable/) so you can get some help from other developers who are experienced in WooCommerce.

**Comment by mikejolley** [comment]
Function needs to at least check post type. Attachments are a post type. Your code runs when images are updated, which is bad design.
