### ISSUE TITLE
How GDPR ready is WooCommerce?

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#19113]
There seems to be activity regarding this matter for Automattic’s products and services. But what about the opensource version?

https://woocommerce.com/2017/12/gdpr-compliance-woocommerce/
https://en.support.wordpress.com/automattic-gdpr/

**Comment by willgorham** [comment]
Hey @rocketeer76 , here's some useful information from a previous question about this: #17837

**Comment by mikejolley** [comment]
^ That covers current thinking. As mentioned, if we need to add tools which are not covered by generic WP solutions, we will :)
