### ISSUE TITLE
Different coupons discount while applying through the order edit page

### ISSUE THREAD

**Issue by prasidhda** [woocommerce/woocommerce#19124]
I tried to analyze the coupon discounts calculated by woo commerce; from frond end (in cart page or checkout page) and backend (order edit page). For single coupon, it applies the same discounts. But when there are multiple chain of coupons, there is difference in the amount of discount. 

This usually happens with the percentage type of coupon code.
For Percentage coupon,
When applying through the front end, it is using the cart item subtotal or discounted price depending upon the coupon settings for the calculation of coupon discounts but while applying the same coupon from via order edit page, it is using the cart item total (discounted price) for the calculation of the percentage coupon discounts for the case sequential coupons.

WooCommerce version is 3.3.1

Please see the screenshots as well. 
![frontend-using-sequential-discounts](https://user-images.githubusercontent.com/11455326/36639248-9c342b0c-1a30-11e8-98f8-b431f45519b8.png)
![backend](https://user-images.githubusercontent.com/11455326/36639249-9c67eafa-1a30-11e8-91d8-a8f1ed197600.png)
![frontend-not-using-sequential-discounts](https://user-images.githubusercontent.com/11455326/36639250-9c9521be-1a30-11e8-9db4-129e5ac96fee.png)

**Comment by mikejolley** [comment]
it is down to the order in which they are applied. 

When you apply multiple coupons to a cart, WooCommerce will sort the coupons by an order using an algorithm based on coupon amounts.

When you apply multiple coupons to an order, YOU decide which order the coupons are applied. So any discounts apply in the order you add them.

At first I could see the issue but then I applied the coupons in reverse and got matching totals. So it's down to that. 

FWIW I think we should consider dropping the sequencial discount option as it's problematic in situations like this but realise it would probably cause complaints.

**Comment by prasidhda** [comment]
**No matter the order of coupons, the order totals should be the same whether we apply the coupons from cart/checkout page or order edit page for same order items.**

When reversing the order in my case of course, percentage coupon is being applied at first which means percentage coupon is being applied to the cart item original price ($120 & $149.0). That is the reason why there is matching totals. 
The issues arises when there is already other coupons already being applied before applying the percentage kind of coupon. No matter the order of coupons, the order totals should be the same when applying the coupons from front end and order edit page for same order items. 

Issue 1: While applying the coupon from order edit page, woo commerce is always using the sequential discounts irrelevant to what we set in the woo commerce setting. 
Issue 2: While applying the coupon from order edit page, Woo commerce is also considering the fixed cart type of discounts as the fixed product type of discounts which is not the case while applying the coupons in the cart/checkout page.

**Comment by mikejolley** [comment]
> No matter the order of coupons, the order totals should be the same whether we apply the coupons from cart/checkout page or order edit page for same order items.

It will, if you disable the `sequential discount option`. That option applies coupons in sequence so the order in which they applied will matter.

For a moment turn off `sequential discount option` and forget it exists. Give me an example of 2 coupons and a product price and I'll try to reproduce it without this setting if there is indeed an issue.

**Comment by prasidhda** [comment]
Woo Commerce Environments
-No Shipping & Tax for easiness
- Sequential discounts turned off

Example products: 
Happy Ninja : $100 
Patient Ninja : $35 

Coupons: 
fixedcart: $5 
percentage: 10% 

Coupons order: fixedcart, percentage
Checkout Page/ Cart Page 
Total Discounts: $5 (fixedcart) + $13.5 (percentage) = $18.5 

In Order edit page: 
Total Discounts: $5 (fixedcart) + $14 (percentage) = $18

Coupons order: percentage,fixedcart
Checkout Page/ Cart Page 
Total Discounts: $5 (fixedcart) + $13.5 (percentage) = $18.5

In Order edit page: 
Total Discounts: $5 (fixedcart) + $13.5 (percentage) = $18.5 

Please try to recreate the above scenarios. As you see, while changing the coupons order, there is different discounts in order edit page which means it is behaving like sequential discounts even they are turned off. 
Plus, in "fixedcart, percentage" coupon order, there is mismatching of discounts. 
Plus, fixed cart discount shouldn't be counted towards sequential discount.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19159
