### ISSUE TITLE
Spinner is missing from WooCommerce endpoints

### ISSUE THREAD

**Issue by obiPlabon** [woocommerce/woocommerce#19125]
When adding WooCommerce endpoint as a menu item from menu management screen it doesn't show the progress spinner.

![spinner-missing](https://user-images.githubusercontent.com/10244644/36640867-0f3f43f0-1a51-11e8-93f3-037f200d1fd6.gif)

**Comment by WPprodigy** [comment]
See https://github.com/woocommerce/woocommerce/pull/19126
