### ISSUE TITLE
templateSelection configuration option is broken in selectWoo

### ISSUE THREAD

**Issue by tubiz** [woocommerce/woocommerce#19120]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

I am using select2 `templateResult` and `templateSelection` configuration options to add images to a multi-select

```
$(".wc-paystack-payment-icons").select2({
	templateResult: formatPaystackPaymentIcons,
	templateSelection: formatPaystackPaymentIcons
});

function formatPaystackPaymentIcons (payment_method) {
	if (!payment_method.id) { return payment_method.text; }
	var $payment_method = $(
		'<span><img src=" ' + wc_paystack_admin_params.plugin_url + '/assets/images/' + payment_method.element.value.toLowerCase() + '.png" class="img-flag" style="height: 15px; weight:18px;" /> ' + payment_method.text + '</span>'
	);
	return $payment_method;
};
```
The `templateResult` configuration option works but the `templateSelection` configuration option is now broken in WC 3.2.0+ when select2 was dropped in place of selectWoo.

This was working perfectly in WC 3.1.6.

The error below is now displayed in the console

<img width="1439" alt="selectwoo broken" src="https://user-images.githubusercontent.com/602184/36634902-3f9d61ee-19ac-11e8-9460-d2f7b34e00d2.png">

The bug is due to this change https://github.com/woocommerce/woocommerce/commit/b2a9b310febf906c6e8a03635d416f15ee9cb380#diff-4ada850fec70a35ab61c8d6bd43da9e4R1709
`var formatted = this.display(selection, $selection).trim();`

## Expected/actual behavior

This is how the multiselect is meant to work.

<img width="758" alt="select multi options" src="https://user-images.githubusercontent.com/602184/36634878-d045bcb0-19ab-11e8-8547-5d464ca4b3b5.png">
<img width="768" alt="multi selected options" src="https://user-images.githubusercontent.com/602184/36634879-d0d94200-19ab-11e8-9bbd-634d8b36891b.png">

This is what is displayed now

<img width="1096" alt="selectwoo broken multiselect" src="https://user-images.githubusercontent.com/602184/36634965-5ec1723a-19ad-11e8-9c0d-9536ea46dd3d.png">

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
### WordPress Environment ###

Home URL: http://localhost/paystack
Site URL: http://localhost/paystack
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.32
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.10MB
Database Data Size: 1.93MB
Database Index Size: 1.17MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.05MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.02MB + Index: 0.02MB
wp_postmeta: Data: 0.27MB + Index: 0.25MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 11
page: 5
post: 1
product: 4
revision: 1
scheduled-action: 1
shop_order: 66
shop_subscription: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (8) ###

Query Monitor: by John Blackbourn – 2.17.0
Catch IDs: by Catch Themes – 1.4.7
Debug Bar Console: by koopersmith – 0.3
Debug Bar: by wordpressdotorg – 0.9
Unsplash WP: by Darren Cooney – 1.1.3
Paystack WooCommerce Payment Gateway: by Tunbosun Ayinla – 5.0.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.3
WP Rollback: by WordImpress – 1.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NGN (₦)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by WPprodigy** [comment]
I think you'll want to report here instead: https://github.com/woocommerce/selectWoo

**Comment by Kiddahkisz** [comment]
#59463

**Comment by Kiddahkisz** [comment]
#60138
