### ISSUE TITLE
Shop Page shows only one product - Woocommerce broken

### ISSUE THREAD

**Issue by svd6481** [woocommerce/woocommerce#19122]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by GlennMartin1** [comment]
Your "report" offers no details and certainly nothing actionable.

**Comment by WPprodigy** [comment]
^

I have my doubts that this only happens with WooCommerce plugin is active, and whilst using a default theme. More-so though, this isn't a bug report. 

This is not the place to ask for support. Github is for bug reports in WooCommerce itself, and contributions. Please read: https://github.com/woothemes/woocommerce/blob/master/CONTRIBUTING.md

Next time, please use the support forums at [WordPress.org](http://wordpress.org/support/plugin/woocommerce), or search around the [WooCommerce Support](https://docs.woocommerce.com/) page.

If you can provide all of the information and show there is a bug, I can re-open this.
