### ISSUE TITLE
Problem with Display_meta Line Item Entries on Single Products

### ISSUE THREAD

**Issue by Fellowfromearth** [woocommerce/woocommerce#19127]
New WC version 3.3.3 will not allow display_meta class on product line level on Woocommerce Orders in the Admin Section? Product meta data will NOT convey from product customization tool to meta data on order screen. Our plugin works up the major overhaul with 3.0. Any reported issues? Email sent via Woocommerce will not display meta data either
_________________________________________________________________________________________________________

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment
Woocommerce 3.3.3
Wordpress 4.9.4
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
I have no idea what you're reporting here. I suggest you explain with screenshots/code examples if you think there is a bug. Adding meta key/values to line items displays fine from what I can tell.
