### ISSUE TITLE
Customer profile no longer accessible from Orders

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce#19136]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  Visit the WooCommerce > Orders
2.  Prior to 3.3, the customer profile was linked to the customer name which is no longer present. 

## Expected/actual behavior

When I follow those steps, I see...

There's no way to access the customer profile from the Orders dashboard or directly from the order.

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
"Someone has submitted an order! Let me edit their details" seems like an odd use case.
