### ISSUE TITLE
Force classic editor on WooCommerce post types

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#19133]
We should add [the block editor incompatible flag](https://wordpress.org/gutenberg/handbook/extensibility/meta-box/#testing-converting-and-maintaining-existing-meta-boxes) to our meta boxes. This will force the classic editor on products, orders, coupons, etc. instead of the Gutenberg editor. The flag should only be added to meta boxes for WC post types and not for any meta boxes that render on the `post` post type.

**Comment by cyrildc** [comment]
Is it just temporary or WooCommerce will still use the classic editor when Gutenberg will be merged into core? Does the product authoring method mentionned at [https://woocommerce.com/2017/11/woocommerce-gutenberg/](url) is still being considered?

**Comment by claudiulodro** [comment]
@cyrildc It's just temporary until we develop nice Gutenberg-compatible screens for Products/Orders/etc. When Gutenberg is merged into WP core and released we will be ready with [the Products block](https://github.com/woocommerce/woocommerce-gutenberg-products-block) in WooCommerce 3.4 but editing products and orders in Gutenberg will come in a future WooCommerce release.

**Comment by cyrildc** [comment]
Currently the product editing works with Gutenberg. Can you set an option or a filter for those who want to use Gutenberg on the product page (I'm using it to add blocks to the product description)?

**Comment by claudiosanches** [comment]
In fact by default orders and coupons doesn't need it, since both don't use editor.
It is required only for products.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19543

**Comment by warrendholmes** [comment]
Looks like this is a problem again with Gutenberg in 5.0 

https://twitter.com/lgr/status/1055219473781833728

The same issue seems to be happening here:

[Coupons](https://cloudup.com/cQgZYx8zQ_0)
[Orders](https://cloudup.com/cOAIgs-lSqz)

**Comment by claudiulodro** [comment]
If the classic editor is not bundled into core, forcing classic editing won't work. I'll investigate a good solution if one exists. Off the top of my head, a notice with a 1-click install of the Classic Editor plugin would work.

**Comment by claudiulodro** [comment]
Created a trac ticket: https://core.trac.wordpress.org/ticket/45192
