### ISSUE TITLE
Customizer Store Notice Self-DDOS 

### ISSUE THREAD

**Issue by aj-adl** [woocommerce/woocommerce#19145]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Utilise the customer to change the 'store notice' setting
2. Type a notice that is of decent length (>100 characters as an example)
3. Make a couple of additional changes, such as fixing a type

## Expected/actual behavior

When I follow those steps, I see...

The customiser  / setting will effectively DDOS a lower-powered share server

I would expect some pretty heavy debouncing of Ajax requests to prevent this, but it seems to be making requests even during periods of continual user input. The setting will also trigger Ajax updates even if the notice is hidden.

I was expecting to see...

The site not get taken down by a 508 Resource Limit Exceeded error (cPanel / WHM)

I would try and disable live preview for this setting, or at least only submit the update admin-ajax.php request when the text area is unfocussed, and also only if 'show notice' is set to true

It's pretty rare we ever work on cPanel servers, but I feel this issue could be an issue for smaller sites, shops etc

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: *****************8
Site URL: ************
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.33
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.58 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_
Total Database Size: 43.12MB
Database Data Size: 26.40MB
Database Index Size: 16.72MB
wp_woocommerce_sessions: Data: 3.00MB + Index: 0.10MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.27MB + Index: 0.14MB
wp_woocommerce_order_itemmeta: Data: 1.31MB + Index: 1.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_bpspro_db_backup: Data: 0.00MB + Index: 0.00MB
wp_bpspro_login_security: Data: 0.00MB + Index: 0.00MB
wp_bpspro_seclog_ignore: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.09MB + Index: 0.13MB
wp_comments: Data: 0.50MB + Index: 0.53MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.45MB + Index: 1.14MB
wp_postmeta: Data: 7.52MB + Index: 6.83MB
wp_posts: Data: 1.52MB + Index: 0.41MB
wp_rg_form: Data: 0.00MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.01MB + Index: 0.00MB
wp_rg_form_view: Data: 2.45MB + Index: 0.86MB
wp_rg_lead: Data: 0.08MB + Index: 0.01MB
wp_rg_lead_detail: Data: 0.11MB + Index: 0.07MB
wp_rg_lead_detail_long: Data: 0.14MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.00MB + Index: 0.00MB
wp_rg_lead_notes: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_umm_usermeta_backup: Data: 0.77MB + Index: 0.51MB
wp_usermeta: Data: 2.52MB + Index: 4.03MB
wp_users: Data: 0.13MB + Index: 0.09MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.15MB + Index: 0.11MB
wp_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.00MB + Index: 0.00MB
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 0.89MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.01MB + Index: 0.01MB
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB
wp_wfFileMods: Data: 0.85MB + Index: 0.19MB
wp_wfHits: Data: 0.73MB + Index: 0.16MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.01MB + Index: 0.01MB
wp_wfKnownFileList: Data: 0.42MB + Index: 0.06MB
wp_wfLeechers: Data: 0.05MB + Index: 0.04MB
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.00MB + Index: 0.00MB
wp_wfLogins: Data: 0.15MB + Index: 0.04MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_wfScanners: Data: 0.00MB + Index: 0.01MB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.13MB + Index: 0.05MB
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 328
customize_changeset: 5
custom_css: 1
nav_menu_item: 26
page: 26
post: 2
product: 204
product_variation: 100
revision: 129
shop_coupon: 7
shop_order: 1303
shop_order_refund: 3
tf_hpslide: 3
tf_hptestimonial: 2

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (33) ###

ManageWP - Worker: by ManageWP – 4.5.0
Gravity Forms: by rocketgenius – 1.8.20.5
Advanced Menu Widget: by Ján Bočínec – 0.4.1
Campaign Monitor Ajax Forms: by Lee Willis – 1.5.0
Custom Menu Wizard: by Roger Barrett – 3.3.0
Display Widgets: by Strategy11 – 2.7
Gravity Forms Math Captcha: by Mandi Wise – 1.0.1
Nav Menu Roles: by Kathy Darling – 1.9.1
******** Delivery WooCommerce: by Alex Kebbell – 1.0 – Not tested with the active version of WooCommerce
PayPal for WooCommerce: by Angell EYE – 1.4.7.4 – Not tested with the active version of WooCommerce
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Simple Slideshow Manager: by Acurax – 2.3.1
StarTrack Express WooCommerce: by Alex Kebbell – 1.3 – Not tested with the active version of WooCommerce
Use Shortcodes in Sidebar Widgets: by Kai Fenner – 1.0
User Role Editor: by Vladimir Garagulya – 4.40
WooCommerce Cart Add-Ons: by 75nineteen Media LLC – 1.5.6 – 1.5.17 is available – Not tested with the active version of WooCommerce
WooCommerce Colors: by WooThemes – 1.0.7 – Not tested with the active version of WooCommerce
WooCommerce Dynamic Pricing: by Lucas Stark – 2.10.1 – 3.1.5 is available – Not tested with the active version of WooCommerce
WooCommerce Export Customer Email: by MH Mithu – 1.3 – Not tested with the active version of WooCommerce
WooCommerce - Store Exporter: by Visser Labs – 1.9.4 – Not tested with the active version of WooCommerce
WooCommerce Free Gift Coupons: by Kathy Darling – 1.0.5 – 1.2.3 is available – Not tested with the active version of WooCommerce
WooCommerce eWAY Payment Gateway: by WooThemes – 3.1.7 – 3.1.14 is available – Not tested with the active version of WooCommerce
Google Address Autocomplete for Woocommerce: by MB Création – 1.9 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.3
WooDojo: by WooThemes – 1.5.4
WooCommerce Hide Shop Products: by codewoogeek – 2.2 – Not tested with the active version of WooCommerce
Wordfence Security: by Wordfence – 7.0.5
Yoast SEO: by Team Yoast – 6.3.1
WP Gallery Custom Links: by johnogg – 1.12
WP Migrate DB: by Delicious Brains – 1.0.2
YITH WooCommerce Social Login: by YITHEMES – 1.2.0 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #903 - /shop/
Cart: #904 - /cart/
Checkout: ❌ Page visibility should be public
My account: #906 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Kaching WordPress WooCommerce Theme
Version: 1.0
Author URL: http://www.themesforge.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: nievole/woocommerce/archive-product.php version - is out of date. The core version is 3.3.0
nievole/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0
nievole/woocommerce/cart/cart-item-data.php version 2.1.0 is out of date. The core version is 2.4.0
nievole/woocommerce/cart/cart-shipping.php version 2.3.0 is out of date. The core version is 3.2.0
nievole/woocommerce/cart/cart-totals.php
nievole/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.3.0
nievole/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
nievole/woocommerce/cart/mini-cart.php version 2.1.0 is out of date. The core version is 3.3.0
nievole/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.2.0
nievole/woocommerce/content-product.php version 1.6.4 is out of date. The core version is 3.0.0
nievole/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
nievole/woocommerce/emails/admin-new-order.php version 2.0.0 is out of date. The core version is 2.5.0
nievole/woocommerce/emails/customer-completed-order.php version 1.6.4 is out of date. The core version is 2.5.0
nievole/woocommerce/emails/customer-invoice.php version 2.0.0 is out of date. The core version is 3.3.0
nievole/woocommerce/emails/customer-new-account.php
nievole/woocommerce/emails/customer-note.php version 1.6.4 is out of date. The core version is 2.5.0
nievole/woocommerce/emails/customer-processing-order.php version 1.6.4 is out of date. The core version is 2.5.0
nievole/woocommerce/emails/customer-reset-password.php
nievole/woocommerce/emails/email-addresses.php version 1.6.4 is out of date. The core version is 3.2.1
nievole/woocommerce/emails/email-footer.php version 2.0.0 is out of date. The core version is 2.3.0
nievole/woocommerce/emails/email-header.php version 2.0.0 is out of date. The core version is 2.4.0
nievole/woocommerce/emails/email-order-items.php version 2.0.3 is out of date. The core version is 3.2.0
nievole/woocommerce/emails/plain/admin-new-order.php version 2.0.0 is out of date. The core version is 2.5.0
nievole/woocommerce/emails/plain/customer-completed-order.php version 2.0.0 is out of date. The core version is 2.5.0
nievole/woocommerce/emails/plain/customer-invoice.php version 2.0.0 is out of date. The core version is 2.5.0
nievole/woocommerce/emails/plain/customer-new-account.php
nievole/woocommerce/emails/plain/customer-note.php version 2.0.0 is out of date. The core version is 2.5.0
nievole/woocommerce/emails/plain/customer-processing-order.php version 2.0.0 is out of date. The core version is 2.5.0
nievole/woocommerce/emails/plain/customer-reset-password.php version 2.0.0 is out of date. The core version is 2.3.0
nievole/woocommerce/emails/plain/email-addresses.php version 2.0.0 is out of date. The core version is 3.2.1
nievole/woocommerce/emails/plain/email-order-items.php version 2.0.0 is out of date. The core version is 3.2.0
nievole/woocommerce/myaccount/my-orders.php
nievole/woocommerce/single-product/product-image.php version 2.0.3 is out of date. The core version is 3.3.2
nievole/woocommerce/single-product/product-thumbnails.php version 2.0.3 is out of date. The core version is 3.3.2
nievole/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
nievole/woocommerce/single-product/short-description.php version - is out of date. The core version is 3.3.0
nievole/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
nievole/woocommerce/single-product.php version - is out of date. The core version is 1.6.4
nievole/woocommerce/taxonomy-product_cat.php version - is out of date. The core version is 1.6.4
nievole/woocommerce/taxonomy-product_tag.php version - is out of date. The core version is 1.6.4

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by mikejolley** [comment]
Started on this in https://github.com/woocommerce/woocommerce/commit/00ed016bf1721b26e6d38946c1dece0a8aff7684 to make it more selective, but it does a full refresh when the checkbox is off. cc @tiagonoronha

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19171
