### ISSUE TITLE
Cart Item Price Change Broken

### ISSUE THREAD

**Issue by nhadsall** [woocommerce/woocommerce#19141]
I'm under the impression that if a plugin wants to change the price of an item in the cart, the best practice is to use the `set_price()` function, with code like the following:
```
add_action( 'woocommerce_before_calculate_totals', 'add_custom_price' );

function add_custom_price( $cart_object ) {
	foreach ( $cart_object->get_cart() as $cart_item_key => $cart_item_value ) { 
		//check if item has custom price
		if ( true == $do_we_change_price ) {
	   		$cart_item_value[ 'data' ]->set_price( $custom_price );
		}
	}
}
```

However, this causes conflicts with some plugins (specifically bundles) since this makes the price change happen on the product and not just the item in the cart. It will also change the price displayed on the product page for that user, which is not ideal.

There should be a way to change the price for a specific cart item, and not the product itself.

**Comment by mikejolley** [comment]
>  It will also change the price displayed on the product page for that user, which is not ideal.

Not sure what you're talking about here. Adjusted code to:

```
add_action( 'woocommerce_before_calculate_totals', 'add_custom_price' );

function add_custom_price( $cart_object ) {
	var_dump( 'calculating....' );
	foreach ( $cart_object->get_cart() as $cart_item_key => $cart_item_value ) {
		if ( 1 ) {
	   		$cart_item_value[ 'data' ]->set_price( 100 );
		}
	}
}
```

So it's clear it's running. Item is in cart. Cart price shows 100. Product page shows original cost.

![beanie local wordpress dev 2018-02-26 23-49-25](https://user-images.githubusercontent.com/90977/36702611-b698e8aa-1b4f-11e8-8214-ac13f9745a17.png)

Your report lacks steps to reproduce, and it isn't clear if extensions are required to cause the issue. On a clean install it doesn't appear to break.

**Comment by mikejolley** [comment]
This morning I also checked `wc_get_product` to ensure it wasn't caching or sharing data and it doesn't. It returns a new instance. This data is not persisted so it doesn't appear to be a bug.

Let me know if otherwise.
