### ISSUE TITLE
Unsetting customer logout menu item in My Account page isn't working

### ISSUE THREAD

**Issue by madhushankarox** [woocommerce/woocommerce#19143]
After updating Woo-Commerce to version 3.3.3, now it's impossible to unset the customer logout navigation item from the My Account page.

Here is the code I use and I was working perfectly fine.

```
add_filter (  'woocommerce_account_menu_items', 'remove_my_account_links'  );
function remove_my_account_links( $menu_links ){
	unset( $menu_links['downloads'] );
	unset( $menu_links['edit-account'] );
	unset( $menu_links['customer-logout'] );
	return $menu_links;
}
```

**Comment by WPprodigy** [comment]
That snippet is working for me. Perhaps your theme or another plugin is also using the filter? Else maybe you aren't adding that snippet at the correct time in the call stack.

Rule out plugin/theme conflicts following this guide: https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4
