### ISSUE TITLE
Woocommerce Filter by price not wedget not showing because of NOT taking woocommerce css

### ISSUE THREAD

**Issue by prafullwizorbit** [woocommerce/woocommerce#19146]
Except shop page all other pages Filter by price wedget not showing i checked , & found that this is not taking any css of woocomerce or even theme. so wedget is coming but not showing. .
Note: i have up to date wooomerce. 
Any help 
Thanks

**Comment by mikejolley** [comment]
Same as https://github.com/woocommerce/woocommerce/issues/19112 I believe.
