### ISSUE TITLE
Woocommerce variations not working properly

### ISSUE THREAD

**Issue by tolents** [woocommerce/woocommerce#19142]
STOCKS DIFFERENCE from back and front end

Hi,

I'm having a hard time to figure out on how to fix the issue with the stocks (variable product).

Example:
Product 1 has stocks for ALL sizes. (Backend)

But what's showing at the online store (frontend) was only sizes US 9 and US 10. The rest of the sizes are missing or out of stock.

Kindly help me with this.

Check link: www.flyingdutchman.ph/Smitty
Image attached: Size 8 has stocks

<img width="380" alt="screen shot 2018-02-25 at 4 10 20 am" src="https://user-images.githubusercontent.com/36867140/36704571-dd9dc528-1b9b-11e8-99b9-e1b8f95253e0.png">

<img width="642" alt="screen shot 2018-02-25 at 3 59 16 am" src="https://user-images.githubusercontent.com/36867140/36704604-003c78b8-1b9c-11e8-9888-f638b235a297.png">

**Comment by WPprodigy** [comment]
Follow this guide to ensure there isn't a plugin or theme conflict: https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4

You don't really provide much info, not system status report, replicatable steps, etc.

**Comment by tolents** [comment]
Hi,

I followed the link provided, DISABLED all plugins except Woocommerce.
I tried to also updating and refereshing the product. But it has still the same problem.

Kindly check link: http://tolents.staging.wpengine.com/shop/smitty/

Size 9 and 10 are the only one's showing up.

Any other options? i think there's a bug in the woocommerce system.

Thanks

**Comment by WPprodigy** [comment]
Can't find the product/shop page on the staging site. Your page builder threw up on the site ;p

Can you screenshot the full variation settings?

**Comment by tolents** [comment]
1. Product page
http://tolents.staging.wpengine.com/shop/smitty/

2. See attached image
<img width="1199" alt="screen shot 2018-02-27 at 11 10 04 am" src="https://user-images.githubusercontent.com/36867140/36708624-d1063f94-1bae-11e8-8fa6-afee0b8704c0.png">


I also tried downgrading the different versions of Woocommerce. But still nothing happens.

**Comment by WPprodigy** [comment]
Stock status is set to "out of stock"

**Comment by tolents** [comment]
Where did you see that?

**Comment by WPprodigy** [comment]
![](http://cld.wthms.co/rDlrKp+)

**Comment by tolents** [comment]
That's the old version of Woocommerce. I updated it and this what shows.

The stocks status was gone.

<img width="1065" alt="screen shot 2018-02-27 at 11 16 50 am" src="https://user-images.githubusercontent.com/36867140/36708797-c3298e98-1baf-11e8-9c6e-edbc5d81a187.png">

**Comment by WPprodigy** [comment]
That's the screenshot you sent >.>

In new versions the stock status is now hidden and is controlled for you. If you re-save the product, it should adjust itself automatically unless you have a  plugin interferring.

If you uncheck "manage stock" for one of the missing variations, you can see the stock status and it'll likely say "out of stock" before you re-save.

**Comment by tolents** [comment]
Wow! Ok now I have a better view of what's happening.

What's the best way to unhide the stock status at variations with the latest woocommerce update?
It seems that the variation in the old versions was hidden and even if I place new stocks it doesn't override.

Or how could I fix the other products with the same issue?

Thanks a lot!!! :)

**Comment by WPprodigy** [comment]
Simply saving the whole product should fix. If it doesn't, something is interferring.

The problem is occurring because you previously (before updating) had products with stock but without the correct stock status.

**Comment by tolents** [comment]
Re-saving the existing products doesn't work.

And, as of now all plugins are disabled.

Any other options?

**Comment by WPprodigy** [comment]
Export all products with the product exporter, check the stock statuses, and re-import.

**Comment by tolents** [comment]
Any plug-in that you recommend?

**Comment by WPprodigy** [comment]
No plugin needed: https://docs.woocommerce.com/document/product-csv-importer-exporter/

**Comment by tolents** [comment]
I have a problem with exporting and importing.

When I export the csv file, edit it and save. When I about to export the csv file is already broken.

**Comment by tolents** [comment]
It's now working. amazing!
