### ISSUE TITLE
useless woocommerce.js dependency

### ISSUE THREAD

**Issue by manuelodelain** [woocommerce/woocommerce#19153]
jquery-blockui is registered as a dependency for woocommerce.js but not used.

**Comment by rodrigoprimo** [comment]
Thanks for your contribution, @manuelodelain.

Please correct me if I'm missing something, but it seems that jquery-blockui is still used in several places. For example:

https://github.com/woocommerce/woocommerce/blob/56317052f2f428f41cdf526bc290cb863c1e2a23/assets/js/frontend/checkout.js#L309

We are looking into removing all jQuery dependencies in issue #18395.

Related #18299
