### ISSUE TITLE
Manual order does not reduce stock

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#19150]
Had a simple product which was only one time available. Created a manual order in admin as admin and set it to paid because customer paid cash. Item had stock activated and in stock set to 1 and available.

Order is marked as completed but product has still 1 item in stock and is purchasable.

©mike

The codesnippet you sent me few minutes ago recognizes this item in as out of stock but in list item is not listed.

- This will require a snippet - found this
https://gist.github.com/lukecav/5263416ca83aaf9b5f94cee4b1458285

WC 3.3.3

**Comment by mikejolley** [comment]
It's a manual process right now for manual orders. Related and logged already https://github.com/woocommerce/woocommerce/issues/13359

> The codesnippet you sent me few minutes ago recognizes this item in as out of stock but in list item is not listed.

I didn't test it, just showing an example. I don't have a plugin based solution for you for that type of filtering. If you have ideas for more filters, post in the ideas board please.

**Comment by ajgw** [comment]
Overall this snippet works really fine for me. Sorting wasn't a option, that was my mistake in case I meant filtering to get access to featured products without scrolling to whole product listing.

I was wondering why this snippet showed me 3 products out of stock as only two of them are marked as out of stock. And only those two had the label out of stock. Is there anywere a saved part which could code snippet think there are three out of stock? All other counts are correct.
