### ISSUE TITLE
The Product Single Image Option is missing. 

### ISSUE THREAD

**Issue by mccawphoto** [woocommerce/woocommerce#19155]
When creating a new product there is no option for a single product image. Only image gallery.  It doesn't show in screen options, nor does it show in the side area. Therefore no thumbnail in the products page list view, or anywhere else.

**Comment by mikejolley** [comment]
There is no setting to control this except width, and thats only shown is the theme does not declare it.

See https://github.com/woocommerce/woocommerce/wiki/Customizing-image-sizes-in-3.3-

The display of the image is not related to this setting. That would be the theme.
