### ISSUE TITLE
Confusing info for import/export of Published column

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#19158]
The documentation for import/export says 1 for published and 0 for draft:
https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema#csv-columns-and-formatting

When exporting products, if a product is draft, it exports with a -1 instead of a 0, which causes confusion. I tested importing both a -1 and a 0, and both made the product a draft. 

Tried in 3.3.3 and master. 

## Steps to reproduce the issue

1. Have at least 1 product set as draft
2. Export products
3. Draft products will have -1 in Published column instead of 0

**Comment by mikejolley** [comment]
@jessepearson Are you able to edit the WIKI? I'm not sure if it's public. Quick change.

**Comment by mikejolley** [comment]
Updated.

**Comment by jessepearson** [comment]
@mikejolley Nope, don't have access to edit there, nor the issues here. I also wasn't sure which was correct in this instance.

**Comment by mikejolley** [comment]
@jessepearson I think it's because we had to lock it down from spammers. NVM.

For reference, -1 is correct for draft. 0 is private.
