### ISSUE TITLE
Don't load jquery-ui from jQuery CDN

### ISSUE THREAD

**Issue by Drivingralle** [woocommerce/woocommerce#19154]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Load any WooCommerce wp-admin view. Ex. [...]/wp-admin/edit.php?post_type=shop_order
2. View source code
3. search for code.jquery.com

## Expected/actual behavior

I just saw that in [this line](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-assets.php#L43) WooCommerce register and later enqueue a script from an external server. 

I expected WooCommerce to follow the WP guideline to not load assets from external resources. The plugin already includes 8 jQuery components. The external file is just 30 KB and was last changed in 2015. So I don't see a reason to  need to update it so often.

I was expecting to see that WooCommerce include all components inside the plugin assets folder.

The fact that WooCommerce loads this file from the external resource is a data protection issue. The request will send amongst other things the IP (considered to be personal identified information) to a 3rd party. With a view on upcoming GDPR this should be changed.

Also one less DNS lookup and less dependency on a online connection is a good thing.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://betasite.drivingralle.de
Site URL: https://betasite.drivingralle.de
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 5.0-alpha-42646
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: Apache/2.4.27
PHP Version: 7.0.24
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.55.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.6.19
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_betasite_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 12.10MB
Datenbank-Datengröße: 11.15MB
Datenbank-Indexgröße: 0.95MB
wp_betasite_woocommerce_sessions: Daten: 0.00MB + Index: 0.00MB
wp_betasite_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB
wp_betasite_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.01MB
wp_betasite_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB
wp_betasite_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB
wp_betasite_woocommerce_order_itemmeta: Daten: 0.01MB + Index: 0.02MB
wp_betasite_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.01MB
wp_betasite_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB
wp_betasite_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB
wp_betasite_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB
wp_betasite_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB
wp_betasite_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB
wp_betasite_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.01MB
wp_betasite_woocommerce_log: Daten: 0.00MB + Index: 0.00MB
wp_betasite_commentmeta: Daten: 0.00MB + Index: 0.00MB
wp_betasite_comments: Daten: 0.01MB + Index: 0.01MB
wp_betasite_links: Daten: 0.00MB + Index: 0.00MB
wp_betasite_options: Daten: 3.62MB + Index: 0.06MB
wp_betasite_postmeta: Daten: 1.48MB + Index: 0.50MB
wp_betasite_posts: Daten: 5.73MB + Index: 0.09MB
wp_betasite_signups: Daten: 0.00MB + Index: 0.00MB
wp_betasite_termmeta: Daten: 0.00MB + Index: 0.01MB
wp_betasite_terms: Daten: 0.00MB + Index: 0.01MB
wp_betasite_term_relationships: Daten: 0.03MB + Index: 0.07MB
wp_betasite_term_taxonomy: Daten: 0.00MB + Index: 0.01MB
wp_betasite_usermeta: Daten: 0.01MB + Index: 0.02MB
wp_betasite_users: Daten: 0.00MB + Index: 0.01MB
wp_betasite_wc_booking_relationships: Daten: 0.00MB + Index: 0.00MB
wp_betasite_wc_download_log: Daten: 0.00MB + Index: 0.00MB
wp_betasite_wc_webhooks: Daten: 0.00MB + Index: 0.00MB
wp_betasite_woocommerce_termmeta: Daten: 0.00MB + Index: 0.00MB

### Post Type Counts ###

ai_galleries: 1
attachment: 257
autobau: 1
bp-email: 32
forum: 1
gd_place: 1
hausbau: 1
nav_menu_item: 12
page: 23
post: 7
product: 6
projects: 1
revision: 1
shop_order: 13
tggr-instagram: 11
tggr-tweets: 4
topic: 1
wc_booking: 8
wp-rest-api-log: 531

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Query Monitor: von John Blackbourn – 2.17.0
InfiniteWP - Client: von Revmakx – 1.7.1
JSON Basic Authentication: von WordPress API Team – 0.1
Error Log Monitor: von Janis Elsts – 1.5.7
Force SSL: von Trevor Turk
BestWebLayout – 1.3

Germanix URL: von Thomas Scholz – 1.1
Ralles Test-Hack: von Ralf Wiechers – 0.1
Safe SVG: von Daryll Doyle – 1.6.0
WooCommerce: von Automattic – 3.3.3
WordPress Beta Tester: von Peter Westwood – 1.2.0
Logged-in-only: von Ralf Wiechers – 2.0.0
REST API Log: von Pete Nelson – 1.6.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #556 - /shop/
Warenkorb: #558 - /cart/
Kasse: #560 - /checkout/
Mein Konto: #562 - /my-account/
Geschäftsbedingungen: #1425 - /terms/

### Theme ###

Name: Rowling
Version: 1.11
Author URL: http://www.andersnoren.se
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ❌ Nicht deklariert

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
This is not a script. This is CSS. WordPress core includes the jQuery UI library (which we DO use) but does not include the styles for jQuery UI. You'll note it also uses the core version number to load the correct styles:

`wp_register_style( 'jquery-ui-style', '//code.jquery.com/ui/' . $jquery_version . '/themes/smoothness/jquery-ui.min.css', array(), $jquery_version );`

So bundling one script in the plugin may be problematic if these versions vary quite a bit.

Not really a priority but we could bundle. Likewise we could look at removing jquery UI components.  Related to https://github.com/woocommerce/woocommerce/issues/18395

Don't think it's related to GDPR. This is no different to viewing a website and your browser loading resources from that site. Not sure why you bothered to bring that up here - the other arguments for removal were enough :)

**Comment by Drivingralle** [comment]
Oh - my bad. I missed that it's a style.

I guess removing jQuery dependencies will take a while.
Great to see this ticket in the milestone.

Sadly I'm not able to modify the composer.json file myself. Will try to find help.

--

I bring up the GDPR because I try to list all reasons to remove the CDN dependency. 
For me the offline capability is already a sufficient reason.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/19173
