### ISSUE TITLE
Single product images ratio after WC 3.3

### ISSUE THREAD

**Issue by decimoseptimo** [woocommerce/woocommerce#19164]
Before the WC 3.3 update, as I recall: product catalog images were 1:1, single product images were 1:1, and naturally the full size images were uncropped.

Now after the update, thumbnails can be set to 1:1 in the customizer, but single product images are uncropped with no option to make them 1:1. Is this the expected way or am I misssing something.

**Comment by akinuri** [comment]
A friend of mine also complains about this. He uploads images with variable sizes and he used to crop them for the product page. Now he can't, and the slider in the product page adjusts to the selected image. If the image is vertical, this produces an undesirable look.

He could crop/scale the image before uploading, but let's say he's a little lazy and the previous behavior benefited him.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/wiki/Customizing-image-sizes-in-3.3-

Single product pages have zoom which doesn't work well with cropped images.

**Comment by decimoseptimo** [comment]
@mikejolley I still have my pre-3.3 WC site running in localhost, and the zoom is pretty sweet.

With `doesn't work well` i suppose you mean "from an art direction perspective" (and not a technical issue) in the sense that the photography subject can end out of the image area or ''cropped". I used to fix this either by centering the subject, or providing alternative thumbnails with a plugin.

**Comment by akinuri** [comment]
The friend I'm talking about, he doesn't use this zoom feature. He's using PhotoSwipe. So, is there a way to modify the product images in the product page?

**Comment by jessepearson** [comment]
Links above should actually go here:
https://github.com/woocommerce/woocommerce/wiki/Customizing-image-sizes-in-3.3
