### ISSUE TITLE
Empty webhook response

### ISSUE THREAD

**Issue by ThomasVeld** [woocommerce/woocommerce#19167]
When I save my order (order.updated) I sometimes get an empty webhook response in return.

```
`Array
(
    [0] => Array
        (
            [id] => 530
            [duration] => 
            [summary] => 
            [request_method] => 
            [request_url] => https://<MY_URL>/api/v1/orders/create
            [request_headers] => 
            [request_body] => 
            [response_code] => 
            [response_message] => 
            [response_headers] => 
            [response_body] => 
            [date_created] => 2018-02-28T08:40:36
            [_links] => Array
                (
                    [self] => Array
                        (
                            [0] => Array
                                (
                                    [href] => https://<MY_STORE>/wp-json/wc/v1/webhooks/0/deliveries/530
                                )

                        )

                    [collection] => Array
                        (
                            [0] => Array
                                (
                                    [href] => https://<MY_STORE>/wp-json/wc/v1/webhooks/0/deliveries
                                )

                        )

                    [up] => Array
                        (
                            [0] => Array
                                (
                                    [href] => https://<MY_STORE>/wp-json/wc/v1/webhooks/0
                                )

                        )

                )

        )

)
`
```

I noticed that the webhook ID is 0, but the URL is just getting it right ($webhook['id'] is not 0 here):

> $delivery = $woocommerce->get('webhooks/'.$webhook['id'].'/deliveries');

The url above shows in the Woo admin the content:
![image](https://user-images.githubusercontent.com/9952965/36783828-a16a41ca-1c7d-11e8-823f-d60d05f68cb0.png)

Although when I visit this url: webhooks/454/deliveries/559

` $woocommerce->get('webhooks/454/deliveries/559');`

It shows an empty JSON response..

**Comment by mikejolley** [comment]
I think the links can be ignored; deliveries are not in the API any more as logging was moved away from comments.

Empty responses mean the endpoint the webhook pinged didn't provide a response.

`The response body from the receiving server`

So in these cases, the webhook was not received or handled by the endpoint.

**Comment by ThomasVeld** [comment]
But when I access the url just in the normal webbrowser function:

` $delivery = $woocommerce->get('webhooks/'.$webhookId.'/deliveries/'.$deliveryId);`

It is showing me the right content, although trying to access it throughout my webhook function the content is empty.
Maybe this gives a clearer image of the problem: [https://stackoverflow.com/questions/49028153/woocommerce-webhook-not-showing-response](url)

Could you tell me how to fix this?

Thanks.

**Comment by mikejolley** [comment]
deliveries are not logged any more. 

```@deprecated 3.3.0 Webhooks deliveries logs now uses logging system.```

**Comment by ThomasVeld** [comment]
Ok, so how do I retrieve this with the webhook api? According to the documentation: [https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-webhook-delivery](url)

**Comment by mikejolley** [comment]
Deliveries are not longer part of the API. Logging is file based. Using comments could not scale.
