### ISSUE TITLE
Filtering products by multiple attributes is not possible with REST API

### ISSUE THREAD

**Issue by arafat-al-mahmud** [woocommerce/woocommerce#19165]
Is it possible to filter products by multiple attributes ?
e.g. I want red medium shirts
products?attribute=pa_color&attribute_term=22&attribute=pa_size&attribute_term=24&
yields all products.

**Comment by mikejolley** [comment]
One attribute, but you can separate multiple term IDs with commas.

**Comment by f1xmAn** [comment]
What's the case of limiting to 1 attribute only? Why didn't you develop search by combined attributes?

**Comment by Nichollas96** [comment]
Any news about this "products?attribute=pa_color&attribute_term=22&attribute=pa_size&attribute_term=24" ? Is it working?

**Comment by claudiosanches** [comment]
@Nichollas96 do you know how works query strings? Because like you set should replace each one.

**Comment by jakupi1** [comment]
Any news ?

**Comment by sublimit14** [comment]
> Any news about this "products?attribute=pa_color&attribute_term=22&attribute=pa_size&attribute_term=24" ? Is it working?

If this worked for you, tell me how you implemented it?
