### ISSUE TITLE
Wrong tax rate for different country

### ISSUE THREAD

**Issue by MajkieS** [woocommerce/woocommerce#19168]
Hello,

we calculate taxes based on country. So in taxes settings - we set calculate taxes based on billing address.

In taxes we have 
Standard and reduced tax rates.
One country - normal - rate name, x%, for shipping
                      - reduced -  rate name, x%, for products
Second country - normal - rate name, x%, for shipping
                      - reduced -  rate name, x%, for products

When order is done to "Country one", and we use get_tax_totals() method from order - it outputs an array with rate_id, rate_name, and rate (which is the float value). But... When order into "second country" is done - it only shows rate_name and rate_id, nothing more. We need it to show the rate (sazba in our language)...

When order for second country is done it simply does not output line 418 from here: https://docs.woocommerce.com/wc-apidocs/source-class-WC_Abstract_Order.html#397-427

$tax_totals[ $code ]->amount           += (float) $tax->get_tax_total() + (float) $tax->get_shipping_tax_total();

How is that possible? Thanks

**Comment by mikejolley** [comment]
The function you linked to outputs nothing; it just gets an array of data. Your report has no indication that you've tested on a clean install, and doesn't have steps to reproduce.

Rule out conflicts first/try the same setup on a clean install. 

If it still occurs
- provide screenshots of your rates and the item you're testing with. 
- include system status so we know what version you're running

Then we can attempt to replicate. I cannot do so with the examples above; in my test store I'm not having issues with multiple tax rates.
