### ISSUE TITLE
text attribute_type on products not available

### ISSUE THREAD

**Issue by wilsonweb** [woocommerce/woocommerce#19178]
This is a bug introduced in version 3.3.2 - 2018-02-20
* Fix - Remove "Type" column on attributes table by default unless custom types are defined.

Previous version supported Select and Text. We have product attributes using text. With this update text is removed as an option from from wc_get_attribute_types() in includes/wc-attribute-functions.php:196
the 'Type' column does not show in the attributes table and now it is forcing our text attributes to work as select while editing products. 
The code to handle 'text' attributes was removed from includes/admin/meta-boxes/views/html-product-attribute.php
Due to the changes in html-product-attribute.php it is not sufficient to  add the following into functions.php:

```
add_filter("product_attributes_type_selector" , function( $array ){
    $array["text"] =  __( 'Text', 'woocommerce' );
    return $array ;
});
```
One must also over-ride the html-product-attribute.php template file.

## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. From an older version such as 3.2.6 create products with text attributes. A text attribute could be like ASIN or UPC
2. Upgrade to the latest version such as 3.3.3, anything after 3.3.2 should be affected
3. Edit the product and go to the attributes section, the text elements are now using select

## Expected/actual behavior
One would expect the text attribute type to be available in each upgrade

## Isolating the problem

- [na ] This bug happens with only WooCommerce plugin active
- [ na] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

WC version: |   | 3.3.3
-- | -- | --
Log directory writable: |   | To allow logging, make /var/www/coolgear.com/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.
WP version: |   | 4.9.4
WP multisite: |   | –
WP memory limit: |   | 256 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US


```
</details>

**Comment by mikejolley** [comment]
Rationale behind removal https://github.com/woocommerce/woocommerce/issues/18045

> Due to the changes in html-product-attribute.php it is not sufficient to add the following into functions.php

Not true, but it would be required that you handle the custom type using `woocommerce_product_option_terms` action to handle 'text' type.

> A text attribute could be like ASIN or UPC

These should not be global text attributes because they are **unique**. Attributes are terms. Terms are used for grouping.

This should be either text attribute or custom field/meta.

You can still 'add new' from the attributes screen to add new attribute terms when you add products, but as I said, attributes are not best suited for this.

The frontend views are unaffected by the change FWIW. The attributes work the same way, which is why this option was unnecessary and won't be supported going forward.

Thanks

**Comment by nivadech** [comment]
Its working for me. Thankyou

**Comment by athinaok** [comment]
Select Text in now visible when seelct attribute type on the other hand when I navigate to the product's attribute the text box is not visible so I cannot enter any value.

**Comment by erkange** [comment]
this was best way to save model names, ean, mpn, special codes.
We can't keep adding custom attributes for each time
