### ISSUE TITLE
UX Issue for Pre Selected Variants.

### ISSUE THREAD

**Issue by shreyans94** [woocommerce/woocommerce#19188]
Hi,

There is a serious need to improve how pre-selected options work.

If we pre-select something on the backend, and then that product goes out of stock, user see this "Sorry, no products matched your selection. Please choose a different combination."

This is terrible UX.

The way it should work is there should be an option to always have an "in stock" variant dynamically pre-selected as per stock availability.

To take UX even 1 step higher, it should automatically pre-select the bestseller variant from among the ones that are "in stock"

**Comment by mikejolley** [comment]
The notice shouldn't be there if the options are deselected. I don't think it should jump to a different selection; next thing people will ask for is controlling that which quickly gets out of hand.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19190
