### ISSUE TITLE
Force billing address for orders with virtual product only

### ISSUE THREAD

**Issue by mensmaximus** [woocommerce/woocommerce#19185]
If an order contains virtual products only billing_address_1, billing_city and billing_postcode are not set to be required. At least in Germany this is an issue because invoices must carry the complete customers address.

To save time and debug later I opted for using the filter  'woocommerce_checkout_fields'

```
add_filter( 'woocommerce_checkout_fields', 'mmx_force_required_fields', 9999 );
function mmx_force_required_fields( $fields ){
 $fields['billing']['billing_address_1']['required'] = true;
 $fields['billing']['billing_city']['required'] = true;
 $fields['billing']['billing_postcode']['required'] = true;
 return $fields;
}
```

However the fields still don't get required. For debugging purpose I hooked into 'woocommerce_form_field_args' to verify the 'required' argument gets passed. And they do. As this is the last filter before the fields get rendered the field labels should carry the 'validate-required' class. But they don't.

Is there any other (maybe jquery) process keeping me from requiring those billing fields?

**Comment by willgorham** [comment]
You could add the 'validate-required' classes yourself? Not sure if this is the preferred way to do it, but something like: 

```
add_filter( 'woocommerce_checkout_fields' , 'mmx_force_required_fields' );
function mmx_force_required_fields( $fields ) {
    $fields['billing']['billing_address_1']['class'] = array( 'form-row-wide', 'validate-required' );
    $fields['billing']['billing_city']['class'] = array( 'form-row-wide', 'validate-required' );
    $fields['billing']['billing_postcode']['class'] =  array( 'form-row-wide', 'validate-required' );

    return $fields;
}
```

**Comment by mensmaximus** [comment]
> You could add the 'validate-required' classes yourself? Not sure if this is the preferred way to do it, but something like:

I don't want to "add" the class. This is what woocomerce is doing in function `woocommerce_form_field` if the argument `required` is set for a field.

**Comment by willgorham** [comment]
Ah, I guess I'm confused by your explanation then, sorry about that.

> As this is the last filter before the fields get rendered the field labels should carry the 'validate-required' class. But they don't.

**Comment by mensmaximus** [comment]
My fault. Bad description.

**Comment by mikejolley** [comment]
@mensmaximus As soon as I hear "Germany" and "checkout" fields alarm bells ring 🚨

WC core does not conditionally set required on checkout fields based on virtual/non-virtual items. The only logic around that WC does do is disable shipping.

So I'm going to bet this is either the Germanized plugin again or some other extension/custom code you have in place :) Not possible for me to say what exactly.

**Comment by mensmaximus** [comment]
@mikejolley while I debug issues I never have third party plugins active. But due to your answer I even deactivated the plugin "WooCommerce PayPal Express Checkout Gateway" (the one from woocommerce.com). And guess what ;-) If the plugin is active the three fields in question are set to not required. This happens even if the paypal express payment gateway is not active (just the plugin activated). I guess I have to invest some more hours.

**Comment by mensmaximus** [comment]
FYI root cause found in class `WC_Gateway_PPEC_Checkout_Handler`. Method `filter_default_address_fields` is hooked into `woocommerce_default_address_fields` and sets required to false for the fields 'address_1', 'city', 'postcode' and 'country'.

**Comment by mikejolley** [comment]
@bor0 @roykho ^

**Comment by mensmaximus** [comment]
Thanks. Bug is already known: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/386
