### ISSUE TITLE
Re-enable support for uncropped thumbnails considering fixed height

### ISSUE THREAD

**Issue by KlausVienna** [woocommerce/woocommerce#19183]
Guys, I am much more user than developer, so please forgive my lack of technical terminology.

Maybe I am alone on this planet with this issue, but: Since WC removed the height information for thumbnails, 3rd party plugins that created UN(!)cropped images without fixed aspect ratio do not work anymore. They obviously look for the requested image sizes of the theme and other plugins (like WC), and as height is not existing anymore, the plugin sets height to 0.

So: Before 3.3. the plugin could create perfect thumbnails UNcropped, considering both width AND height. Does not work anymore. Issue already open at the plugin author, but I guess as WC dropped the height information, there is not much that he can do.

On top: Even exchanging these thumbnails directly via ftp is no option, as WC is recreating them immediately. 

For my shop – where I cannot crop the thumbnails, but have partly aspect ratios of e.g. 1:8, leading now to huge thumbnails, I am now stuck to version 2.6.

Possible to add the height information again - even if it is not used by WC, to support external plugins? And - of course - do not recreate the thumbnails created by this plugin then?

Thanks!

**Comment by mikejolley** [comment]
Hi,

Height blank or '0' tells WP to let the height grow to whatever and just resize the width. A max height option could be introduced but I'm not sure how common or edge case it would be. As a store owner uploading images you could of course upload them in the desired 'full' size so it's correctly displayed on the single page and when zoomed.

There is a way to customise this anyhow - take a look at https://github.com/woocommerce/woocommerce/wiki/Customizing-image-sizes-in-3.3-

That lets you change single dimensions, or replace the woocommerce_single size with something else e.g. custom image size.  That should be what you need.
