### ISSUE TITLE
Not showing Display section on woo->Settings->Product->Display

### ISSUE THREAD

**Issue by Valente2302** [woocommerce/woocommerce#19184]
Hello,
The section Display where image settings are set is not shown on my site, I´ve deactivated/activated woo but not luck..
Any Ideas how to fix this issue?
Thank you

**Comment by willgorham** [comment]
Those settings are now in the Customizer. See: https://github.com/woocommerce/woocommerce/wiki/Customizing-image-sizes-in-3.3-#customize-image-sizes-in-the-customizer
