### ISSUE TITLE
Long text in shipping method in checkout page is not aligned with the radio button

### ISSUE THREAD

**Issue by mojo2405** [woocommerce/woocommerce#19189]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. enter long text inside shipping descriptioin
2. go to checkout page

screen capture  :
https://ibb.co/eLz7kx

## Expected/actual behavior

Text should be aligned with the radio button

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Theme dependent. 

![checkout local wordpress dev 2018-03-01 10-47-17](https://user-images.githubusercontent.com/90977/36840737-f36de5ce-1d3d-11e8-91b7-f4accc05e04b.png)
