### ISSUE TITLE
WC extensions conflict: Product Add-on totals UI disappears when product type is Composite

### ISSUE THREAD

**Issue by heymarvin** [woocommerce/woocommerce#19193]
I have no idea where to post this, but since all three main variables are WooCommerce-related, I will post it here. I hoping you guys can direct it to the correct repository.

## Clean install:

- WordPress 4.9.4
- WooCommerce 3.3.3
- WooCommerce Composite Products 3.13.6
- WooCommerce Product Add-ons 2.9.1
- Storefront theme

## To reproduce:
1. Create global add-on with "Additional custom price input"
2. Create "SIMPLE PRODUCT" as simple product
3. Create "COMPOSITE PRODUCT" as composite product and add "SIMPLE PRODUCT" as a component
4. Visit COMPOSITE PRODUCT and try to change Add-on Cost

## Current behaviour:
When changing addon cost value, "Options total" and "Sub total" are not being calculated in the front-end, however the Options total is added to cart.

## Expected:
"Options total" and "Sub total" should be visible before "Add to cart" regardless of the product type.

### Main product as Composite type: Main price (10) + component price (5) + add-on price (3)
![wc-combined-addons](https://user-images.githubusercontent.com/22843343/36849136-200295f4-1d5b-11e8-840c-d611b2fea075.png)
### Cart showing correct data
![wc-combined-cart](https://user-images.githubusercontent.com/22843343/36849133-1fb684e8-1d5b-11e8-9bd4-dcdaca9cdef1.png)
### Main product as Simple type: Main price (10) + add-on price (3)
![wc-combined-disabled](https://user-images.githubusercontent.com/22843343/36849134-1fdf2272-1d5b-11e8-8ad6-5117ef312ddd.png)

**Comment by heymarvin** [comment]
## Update
With WooCommerce Composite Products **3.11.0** it works as expected. On ** 3.13.6** it doesn't.

**Comment by mikejolley** [comment]
Please use the help desk; https://woocommerce.com/my-account/create-a-ticket/ include that version information as it will help the developer track down the issue.

Thanks
