### ISSUE TITLE
marked as ‘complete’ in order

### ISSUE THREAD

**Issue by onmarketing** [woocommerce/woocommerce#19197]
Do the orders have to be marked as ‘complete’ in order for them to be able to access the course
currently they’re all coming through as ‘processing’?

How do I fix this issue?

Thanks,

Shaun.

**Comment by mikejolley** [comment]
It depends on what plugin is powering the 'course' product type. This is not a core issue. Processing is paid so it could grant access. Or find a snippet which marks processing virtual orders completed automatically.

**Comment by onmarketing** [comment]
@mikejolley 

How do I do that snippet?

Would you be able to give me some example?

Thanks,

Shaun.

**Comment by mikejolley** [comment]
Search "automatically complete processing orders woocommerce"
