### ISSUE TITLE
Onboarding: circumscribe clickable area of dismiss link to its text label

### ISSUE THREAD

**Issue by eliorivero** [woocommerce/woocommerce#19209]
## Steps to reproduce the issue

1. go to WC onboarding
2. scroll down to the "Not right now" link

## Expected behavior

A link whose clickable area circumscribed to its text label

## Actual behavior

Clickable area takes the full width

<img width="726" alt="captura de pantalla 2018-03-01 a la s 17 52 04" src="https://user-images.githubusercontent.com/1041600/36869576-0803f7fc-1d7b-11e8-8cdf-75a78066b351.png">

<img width="739" alt="captura de pantalla 2018-03-01 a la s 18 28 15" src="https://user-images.githubusercontent.com/1041600/36870595-6a414ff2-1d7e-11e8-8573-0c8d0e49b33c.png">

**Comment by claudiulodro** [comment]
There is nothing else down there. Why is this a problem?

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/19206 anyway.

**Comment by eliorivero** [comment]
Thanks @mikejolley 👍

@claudiulodro this could mean a frustrated user that inadvertently clicks an area that was supposedly empty but instead, was clickable, so they were taken back to the dashboard.
