### ISSUE TITLE
Possible Improvements for "Order Actions" and "Send Order Email" modules.

### ISSUE THREAD

**Issue by bobteree** [woocommerce/woocommerce#19208]
Below are a number of issues and possible solutions to the above mentioned modules that appear on the "Order Page" within WooCommerce. Thanks.
![problems with order actions and send emails feature](https://user-images.githubusercontent.com/1479735/36869227-04b85ed8-1d69-11e8-9d07-e8ee865f4a67.png)
![solutions for order actions and send emails feature](https://user-images.githubusercontent.com/1479735/36869228-04cb70ea-1d69-11e8-9746-bd38f739c9c3.png)

**Comment by kellychoffman** [comment]
You're right, this is confusing but the "Send Order Email" isn't part of the core WooCommerce product. It must be coming from an extension or plugin you have activated.

**Comment by bobteree** [comment]
@#$%^& SORRY!

**Comment by kellychoffman** [comment]
Not a problem.
