### ISSUE TITLE
Percentage discount in Woo 3.3.3 don't work

### ISSUE THREAD

**Issue by InterLaw-PL** [woocommerce/woocommerce#19202]
Don't work a percentage discount in WooCommerce 3.3.3., return message after use: "Sorry, this coupon can not be applied to selected products."
Coupones: fixed cart discount, fixed product discount works correctly.

**Comment by WPprodigy** [comment]
Are there any product restrictions? Please screenshot every tab of the coupon's settings a paste here.

**Comment by kloon** [comment]
I just tested this with 3.3.3 and the master branch and cannot reproduce. The message suggests that you have some other sort of restrictions on the coupon like a product rule where you can only apply the coupon when certain products are in the cart.

I'd suggest you check your coupon settings and try again, not able to reproduce and functionality works as expected for me.

**Comment by InterLaw-PL** [comment]
Thank you for reply. Thanks for tested with 3.3.3. My client uses a Perfect WooCommerce Brands Plugin, and it add "Brands restriction" in WooCommerce > Coupon > Restrictions on use. After adding brands for the coupon (all brands) - the coupon works fine.
