### ISSUE TITLE
Built in Import - Update Variable Product - Creates Multiple Duplicate Variations

### ISSUE THREAD

**Issue by oliverini** [woocommerce/woocommerce#19213]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test 

## Steps to reproduce the issue

1. Import some Variable Products by CSV using the new built-in Woocommerce import, with a CSV that includes products and their variations
2. Import them again, this time ticking 'Update Existing Products', as if you were updating the products

## Expected/actual behavior

The products are updated, the variations are imported again, making duplicate variations, so if your CSV has a product with 15 variations, that product has 30 variations after updating.

## I was expecting to see...

The product and its variations should be updated, the old variations should be replaced with the new variations. No duplicate variations should be created.

## Demo CSV upload file...

Includes sample image - should be uploaded to Media first or import wont work...

[wc-git-demo-import-variations-duplicate-wimg.zip](https://github.com/woocommerce/woocommerce/files/1774738/wc-git-demo-import-variations-duplicate-wimg.zip)

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

WC version: |   | 3.3.3
-- | -- | --
Log directory writable: |   | C:\wamp\www\subdomains\itb/wp-content/uploads/wc-logs/
WP version: |   | 4.9.4
WP multisite: |   | –
WP memory limit: |   | 1 GB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_GB


```
</details>

**Comment by mikejolley** [comment]
With the absence of SKU or ID it's not possible to know if it needs to update or created.

From the docs:

> Update existing products: If you have IDs and/or SKUs in your CSV file, the importer can update your existing products that have the same IDs or SKUs with information from the CSV. Check this box if you want this behavior, otherwise the importer will skip CSV products that have the same ID or SKU as an existing product.

**Comment by oliverini** [comment]
Thanks Mike, each variation needs its own sku then. Thant makes perfect sense.

**Comment by pgamaster** [comment]
Having the same issue, on product update it creates duplicate variations, example of my CSV file:

![woo_import_issue](https://user-images.githubusercontent.com/15028396/61617420-53e14700-ac73-11e9-8f21-460249ab3448.png)

What should I do or how my CSV should look? Thank you very much.

**Comment by oliverini** [comment]
each variation needs its own sku (see above)
