### ISSUE TITLE
Built in Import - Update Product - blank Stock status leads to Out of Stock

### ISSUE THREAD

**Issue by oliverini** [woocommerce/woocommerce#19215]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Upload a Product by CSV, with "In stock?" column = 1 and "Stock" column = blank
2. Update with same CSV

## actual behavior

When updated the product goes from 'In Stock' to 'Out of Stock'

## I was expecting to see...

When updated the product should stay  'In Stock', with no stock management

## Isolating the problem

The Product CSV Import Schema (https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema#csv-columns-and-formatting) says leaving the "Stock" column blank signifies 'no stock management' - but when a product is updated this is not honored. 

## example upload files

Includes sample jpg which needs to be uploaded to Media first...

[oos-ishoo.zip](https://github.com/woocommerce/woocommerce/files/1775073/oos-ishoo.zip)

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
WC version: |   | 3.3.3
-- | -- | --
Log directory writable: |   | C:\wamp\www\subdomains\itb/wp-content/uploads/wc-logs/
WP version: |   | 4.9.4
WP multisite: |   | –
WP memory limit: |   | 1 GB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_GB
```
</details>

**Comment by mikejolley** [comment]
As this is a variable product with no children, it will be out of stock until a child is added with stock. In stock/of of stock in this case it automatic, not user defined.

**Comment by oliverini** [comment]
Hi Mike, this isn't correct I'm afraid. There's certainly something wrong here, try this example for clarification:

[oos-ishoo-clarity.zip](https://github.com/woocommerce/woocommerce/files/1780189/oos-ishoo-clarity.zip)

## Steps to reproduce the issue

1) Import a Variable product with variations. Product is listed as 'In Stock'
2) Update the product (only), with 'Update Products' checked. Product shows 'Out of Stock'

## actual behavior

Product changes from In Stock to Out of Stock

## I was expecting to see...

Product remains In Stock, as set on initial import

**Comment by mikejolley** [comment]
The CSV you provided had one variable product with no children. Variable products inhert stock status from children.

**Comment by oliverini** [comment]
Sorry Mike, I'm not being clear. The zip above contains two csv files, the first, to Import, includes variations, the second, to Update, without variations (so variations are not duplicated). Updating the product causes it to become 'Out of Stock'. This is because variations become unlinked - the updated product has no variations. Learning is i) both product and its variations must be updated at the same time, so product/variation links remain intact, and ii) variations need their own SKU, or they will be duplicated on update. Thanks for looking into it, you are correct to close the issue.
