### ISSUE TITLE
Appended Price in E-Mails

### ISSUE THREAD

**Issue by B-Anders** [woocommerce/woocommerce#19218]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Set Shop to NOT use Tax Calculation
2. Make a purchase
3.

## Expected/actual behavior

When I follow those steps, I see...
All prices in the shop and in mails are shown as imputed, without any prefix or suffix EXCEPT the Subtotal in E-Mails. The Subtotal in E-Mail Table shows: (excl.MwSt) - meaning without Tax. This makes customers to wonder if there is a tax or not.

I was expecting to see...
All prices, totals and subtotals without any prefix or suffix indicating a tax calculation

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
All to latest Version.
No Plugins that can influence TAX calculation
![sreengrab_tax-_2018-03-02_15 39](https://user-images.githubusercontent.com/36055411/36904793-f8c0074c-1e31-11e8-9a3f-e369c0555e63.jpg)

Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
> All to latest Version. No Plugins that can influence TAX calculation

Not really relevant. We still ask for those details for a reason. e.g. are there template overrides?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19220
