### ISSUE TITLE
API Variation stock control not working

### ISSUE THREAD

**Issue by kloon** [woocommerce/woocommerce#19214]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Make an API call to a product variation to update the stock_quantity
```
POST /wp-json/wc/v2/products/40/variations/56/?consumer_key=ck_d259b5b5787c5705b8e686cc750d11c8e39bc9ab&amp;consumer_secret=cs_cdb23edd7abf5aec4f0378b82d47ef1c074cc50b HTTP/1.1
Host: wc.local
Content-Type: application/javascript
Cache-Control: no-cache
Postman-Token: f7f9423c-4275-c130-67c7-446e0dee5318

{
"stock_quantity": "30", 
"manage_stock": true 
}
```
2. See the response has no updated stock status and quantity
```
{
    "id": 56,
    "date_created": "2018-02-16T09:54:12",
    "date_created_gmt": "2018-02-16T09:54:12",
    "date_modified": "2018-02-16T09:54:55",
    "date_modified_gmt": "2018-02-16T09:54:55",
    "description": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.</p>\n",
    "permalink": "https://wc.local/product/v-neck-t-shirt/?attribute_pa_color=blue",
    "sku": "woo-vneck-tee-blue",
    "price": "15",
    "regular_price": "15",
    "sale_price": "",
    "date_on_sale_from": null,
    "date_on_sale_from_gmt": null,
    "date_on_sale_to": null,
    "date_on_sale_to_gmt": null,
    "on_sale": false,
    "visible": true,
    "purchasable": true,
    "virtual": false,
    "downloadable": false,
    "downloads": [],
    "download_limit": 0,
    "download_expiry": 0,
    "tax_status": "taxable",
    "tax_class": "",
    "manage_stock": false,
    "stock_quantity": null,
    "in_stock": true,
    "backorders": "no",
    "backorders_allowed": false,
    "backordered": false,
    "weight": "",
    "dimensions": {
        "length": "",
        "width": "",
        "height": ""
    },
    "shipping_class": "",
    "shipping_class_id": 0,
    "image": {
        "id": 67,
        "date_created": "2018-02-16T09:54:20",
        "date_created_gmt": "2018-02-16T09:54:20",
        "date_modified": "2018-02-16T09:54:20",
        "date_modified_gmt": "2018-02-16T09:54:20",
        "src": "https://wc.local/wp-content/uploads/2018/02/vnech-tee-blue-1.jpg",
        "name": "vnech-tee-blue-1.jpg",
        "alt": "",
        "position": 0
    },
    "attributes": [
        {
            "id": 1,
            "name": "Color",
            "option": "Blue"
        }
    ],
    "menu_order": 0,
    "meta_data": [
        {
            "id": 1440,
            "key": "_wpcom_is_markdown",
            "value": ""
        }
    ],
    "_links": {
        "self": [
            {
                "href": "https://wc.local/wp-json/wc/v2/products/40/variations/56"
            }
        ],
        "collection": [
            {
                "href": "https://wc.local/wp-json/wc/v2/products/40/variations"
            }
        ],
        "up": [
            {
                "href": "https://wc.local/wp-json/wc/v2/products/40"
            }
        ]
    }
}
```

## Expected/actual behavior

When I follow those steps, I expect to see the variation updated with the manage stock flag set and the quantity set to that as passed through in the API call. The result is that the flag is not set and the quantity not set.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by kloon** [comment]
Update, after further testing it seems this is related to the Content-Type not being set to json, if you send through a Content-Type of application/json it works.

@claudiosanches is this the correct behaviour? If so we can close this issue.

**Comment by claudiosanches** [comment]
@kloon yes, WordPress expected to set the properly Content-Type for each request.
That `Content-Type: application/javascript` will make all request body ignored by WordPress.

**Comment by kolonuk** [comment]
Wow, this took me about 4 hours to find, and loads of repeat testing in postman!  I can confirm that adding the content type works, but I would suggest that this IS a bug and needs to be re-opened, as it is returning a 200 OK which isn't correct as it hasn't actually changed anything.  It should instead be returning an error stating unknown content type or something.  In fact, if this sat at the very front of every API call, I wouldn't spend hours on this, only to realise I'd missed it out of my call.

@kolonuk
