### ISSUE TITLE
Order Cancelled due to Special Characters in Address?

### ISSUE THREAD

**Issue by flatflyfish** [woocommerce/woocommerce#19212]
A Thai customer has indicated to me that his orders are constantly cancelled by PayPal and WooCommerce because in WooCommerce he selects his state as "Sisaket (ศรีสะเกษ)", and apparently he says that the error is because the Thai characters are not accepted by PayPal.

Any advice?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19219
