### ISSUE TITLE
Checkout Page displays some hooks twice

### ISSUE THREAD

**Issue by rthvanesa** [woocommerce/woocommerce#19216]
On checkout page, everytime you change the shipping method and the checkout form updates the total price, some hooks are being displayed over and over again:
![woocommerce2](https://user-images.githubusercontent.com/7516117/36901525-2efdddd6-1e30-11e8-8a43-4ad2aa556398.png)

I have also tested with Storefront.
Also, I am experiencing some issues with the 'woocommerce_checkout_after_customer_details' hook, which is not being displayed in the right position. For this, I think a solution would be to move the  `<?php do_action( 'woocommerce_checkout_after_customer_details' ); ?>` code line before the ending tag of `<div class="col2-set" id="customer_details">` in _form-checkout.php_.

**Comment by mikejolley** [comment]
Not a bug here from what I can see, just the places those hooks are located. Those hooks will fire every time the review section is loaded. 

When the checkout refreshes via AJAX, the entire review section is loaded in again - including whatever is rendered via those hooks.

See the review.order.php template file. This template file is loaded via ajax. 

This is not behaviour that can be changed without breaking backwards compatibility.

Hope that makes sense. If you have code running there that needs to run once, you'll need to choose a different hook.

R/e `woocommerce_checkout_after_customer_details`

`woocommerce_checkout_after_customer_details` matches `woocommerce_checkout_before_customer_details` and both are outside the col set. If you're getting odd placement, perhaps missing a clearfix?

**Comment by rthvanesa** [comment]
Thank you for your answer, it makes sense.

Using the latest version of Storefront theme, I use the following code to insert some content in 'woocommerce_checkout_after_customer_details' hook:
```
add_action( 'woocommerce_checkout_after_customer_details', 'checkout_after_action', 10);
function checkout_after_action()
{
     echo '<div style="background-color: #d1c0b8;border: 1px solid #363436;padding: 5px;color: #ffffff;text-align: center">This is the woocommerce_checkout_after_customer_details hook.</div>';
}
```
The output is this: http://nimb.ws/4IoJB9
I can't manage to find any clearfix that would actually place the content below the customer details form, without ruining the 2-column layout. I would appreciate if you would help me out with an idea.

Thank you!

**Comment by mikejolley** [comment]
@tiagonoronha ^

**Comment by tiagonoronha** [comment]
If the goal is to add content after the customer details, perhaps use the `woocommerce_checkout_shipping` hook instead. Example:

`add_action( 'woocommerce_checkout_shipping', 'checkout_after_action', 999 );`

![screen shot 2018-03-08 at 15 10 44](https://user-images.githubusercontent.com/1177726/37158287-ed065932-22e2-11e8-9939-8799dfa9e326.png)
