### ISSUE TITLE
Built in Import - Product Fails to Import creates Orphaned Variations 

### ISSUE THREAD

**Issue by oliverini** [woocommerce/woocommerce#19217]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Import a CSV with Variable Product and Variations, but with a missing image reference for the product

## actual behavior

Product is not imported, Variations are imported, Variations are orphaned. If you then upload the Product correctly later, the Variations are not then associated with Product, they remain orphaned

## I was expecting to see...

Either the variations should not be imported if there's no parent Product (when importing the parent product fails, or when the parent product does not exist in the import or on the site). Or variations should get associated with the product when the product is imported later.

## example files

Two files - 
1) "wc-imp-fail-prod.csv" with product, variations, and image error. Upload first to see orphaned variations created
2) "wc-imp-ok-prod.csv" with product only, no image error and no variations. Upload second to see variations remain orphaned

[wc-imp-fail-prod.zip](https://github.com/woocommerce/woocommerce/files/1775358/wc-imp-fail-prod.zip)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

WC version: |   | 3.3.3
-- | -- | --
Log directory writable: |   | C:\wamp\www\subdomains\inthebag/wp-content/uploads/wc-logs/
WP version: |   | 4.9.4
WP multisite: |   | –
WP memory limit: |   | 1 GB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_GB


```
</details>

**Comment by mikejolley** [comment]
Need to update the cleanup routine to delete the children of cleaned up, failed imports.

**Comment by WPprodigy** [comment]
Maybe related: https://wordpress.org/support/topic/junk-in-database-after-csv-import-even-after-removing-all-products/

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19378
