### ISSUE TITLE
Customer address incorrectly defaulting to store base location state

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#19222]
## What happens:

On a manually created order, the customer's address has the state field filled in, even if it doesn't apply to their country.

## What should happen:

Store base location should only fill in the state if it makes sense to do so (correct country).

## To replicate:
1) Create a new user/customer profile, and only give it a billing country.
2) Manually create an admin order for this customer, and save without editing any address info.
3) Click to edit the billing address, and notice the store's base state has been filled in: http://cld.wthms.co/34BUl5

This happens because the default customer location is the store base: http://cld.wthms.co/aAxfnI. And the store base is a US state: http://cld.wthms.co/vcuQ9d

Short video: http://cld.wthms.co/lXtKBw

zd-990910

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19338
