### ISSUE TITLE
Using Cart Functions in WC_Discounts

### ISSUE THREAD

**Issue by Chunkford** [woocommerce/woocommerce#19233]
I have a rare use case but I need to ask in case it's been over looked. 

Why in `WC_Discounts->apply_coupon_percent()` is `wc_cart_round_discount()` being called when the object used to initate the discount class can either be the cart or **an order**?

I'm using Subscriptions, but have extended it a fair bit.
I'm controlling the coupon management so have turned off Subscriptions validating them.
When an renewal order is triggered and based on my criteria I'm calling `$subscription->remove_coupon( $coupon->get_code() )` -  For reference, subscriptions extends `WC_Order`
But because the cart functions file is not included when a renewal order is process due to not being a frontend request, `WC_Abstract_Order->recalculate_coupons()` is throwing a error because `wc_cart_round_discount()` isn't defined when the coupons are reapplied 

I can get around it by loading the cart functions file if the function doesn't exists in my plugin, but it seems odd to me that specific functions be used in a class that, in my view, shouldn't be tied to such restraints.

**Comment by mikejolley** [comment]
This function could be moved to core functions as a quick fix.

**Comment by Chunkford** [comment]
@mikejolley  Yes, this would be great.
Did you want me to make the changes? i.e. change name, move to core functions and change the name where it is used throughout WC?

**Comment by mikejolley** [comment]
I don't think the name needs changing.

**Comment by Chunkford** [comment]
I'll submit a pull request, albeit I feel I've opened up a can of worms. Just found out the Brand's plugin `is_coupon_valid()` function in class-wc-brands-coupons.php uses the `woocommerce_coupon_is_valid` filter in WC_Discounts and assumes it's from the cart.

**Comment by tobinfekkes** [comment]
Thank you, chunkford! Just ran into this exact same thing. Undefined `wc_cart_round_discount()` when extending `WC_Order` and trying to build an order with a discount. 

Looking forward to 3.4, appreciate you fixing it so quickly!
