### ISSUE TITLE
&amp; char

### ISSUE THREAD

**Issue by LetMeKnow1** [woocommerce/woocommerce#19234]
When customer enter address with & Woocommerce handles it correctly.
But when the customer write this char on his comments it doesn't handle it properly:
![untitled33](https://user-images.githubusercontent.com/35699825/36942729-b28c2fba-1f82-11e8-80df-e114fe35ca4c.png)

**Comment by mikejolley** [comment]
Order:
![monosnap 2018-03-05 09-34-35](https://user-images.githubusercontent.com/90977/36967729-7567d996-2058-11e8-9ca4-ada92cb42a37.png)
Checkout: 
![checkout local wordpress dev 2018-03-05 09-32-32](https://user-images.githubusercontent.com/90977/36967726-739a3fb4-2058-11e8-83cf-8f3a1320e168.png)


Seems fine. Need more details.

**Comment by LetMeKnow1** [comment]
@mikejolley Did you create it manually or via customer page? It happens when order is placed by customers... not when placed manually in dashboard.

**Comment by mikejolley** [comment]
Yes via customer/checkout.
