### ISSUE TITLE
Keep syncing images even not available variation add-to-cart-variation.js

### ISSUE THREAD

**Issue by sandermendes** [woocommerce/woocommerce#19238]
Hello dears.

I wanna know, if has a some hack or hook to Keep Syncing images in variable product,
even if the variation is out_of_stock or disabled?

Thanks

Best Regards.

**Comment by mikejolley** [comment]
Not sure what you're asking. If this is just a usage question you may want to use the forums as this place is for reporting bugs. If you mean show outofstock variations, you can do this in Settings > products > Inventory and choose not to hide out of stock products.

Thanks
