### ISSUE TITLE
Hidden products are visible from URL

### ISSUE THREAD

**Issue by malasaad82** [woocommerce/woocommerce#19231]
Hi,
If we make a product hidden its hidden from Shop page but its accessible from URL, So it will be indexed by Google. We still need the product published as its used in other product container using mix and match plugin. 

Is there a way to fix that?

Regards

**Comment by WPprodigy** [comment]
It will only be indexed by Google if the bots find a link to the page. Don't link out to it, and you'll be fine.

**Comment by malasaad82** [comment]
Hi WPprodigy,
Thanks for your answer. I am using woo-mix-and-match plugin to make a container of Product that has 3 sub-products. 

I fixed it by redirecting the sub-product to main shop page and made the sub-products noindex.

But I still see if we make product hidden it's still accessible by visiting URL.

**Comment by mikejolley** [comment]
Hidden simply hides from catalog views. We don't have the product private. SEO plugins can make pages noindex, or you can block access with custom code as you've found.
