### ISSUE TITLE
Attributes not available to Variable products when inserting programmatically

### ISSUE THREAD

**Issue by justinmz** [woocommerce/woocommerce#19237]
Hi,

We're importing products via a feed, before importing the products we create all the attributes required via wc_create_attribute()
Directly after it completes we run the product import. The products have Attributes listed in them but with no values assigned. It's seems like the products can't see the a record of the attributes yet.

If we delete those products and re-run the import wc_create_attribute() returns an expected error letting us know the Attributes already exist. The products then import successfully with Attributes assigned and values inserted and all Variations registered correctly.

It won't allow us to run the Product import directly after the Attribute import, it needs a page reload in-between there. We've attempted flushing rewrite rules, deleting transients, even deleting and resetting transients. Nothing seems to work.

We're running Wordpress 4.9.4 and Woocommerce 3.3.3

**Comment by mikejolley** [comment]
Attributes are taxonomies and these won't be registered in WordPress until next load. You can do what our CSV importer does and register the taxonomy after creating the attribute:

```
		// Register as taxonomy while importing.
		$taxonomy_name = wc_attribute_taxonomy_name( $attribute_name );
		register_taxonomy(
			$taxonomy_name,
			apply_filters( 'woocommerce_taxonomy_objects_' . $taxonomy_name, array( 'product' ) ),
			apply_filters( 'woocommerce_taxonomy_args_' . $taxonomy_name, array(
				'labels'       => array(
					'name' => $raw_name,
				),
				'hierarchical' => true,
				'show_ui'      => false,
				'query_var'    => true,
				'rewrite'      => false,
			) )
		);
```

Thanks
