### ISSUE TITLE
Breaking: install themify (e.g. ultra theme) then i stall woocommerce 3.3.3, breaks the site.

### ISSUE THREAD

**Issue by puneetdhawan86** [woocommerce/woocommerce#19239]
Breaking: install themify (e.g. ultra theme) then i stall woocommerce 3.3.3, breaks the site.

**Comment by puneetdhawan86** [comment]
*install

**Comment by mikejolley** [comment]
Themify is premium so I don't have access to reproduce. Check with Themify to know if it's compatible.
