### ISSUE TITLE
Pagination not working in the latest 3.3.X versions on search page.

### ISSUE THREAD

**Issue by inventusdylan** [woocommerce/woocommerce#19243]
Hello,

There seems to be an issue in the latest versions of WooCommerce.

We use the following code snippet to use the WooCommerce archive as the search results template.
> 
> function usewooarchive( $query ) {
> 	if ( $query->is_search ) {
> 		$query->set( 'post_type', 'product' );
> 		$query->is_archive = true;
> 		$query->is_post_type_archive = true;
> 	}
> 
> 	return $query;
> }
> add_filter( 'pre_get_posts', 'usewooarchive' );

The following does show the first products based on the search query however. Also the rel="next" is generated so their is definitely an second page with results.

I've checked this across different WooCommerce 3.3.X versions shops. And all shops don't show the pagination on the bottom.

What I also did before submitting this issue:
- Disable all plugins except WooCommerce.

Thanks for your time!

**Comment by mikejolley** [comment]
Have you done your own debugging? I mean, this is for a custom snippet - I don't think you'd replicate an issue with core alone..

**Comment by WPprodigy** [comment]
Can't replicate with a default theme: http://cld.wthms.co/eAUvvu. Has to do with your snippet for sure, and I'm afraid we can't support customizations like that.

Also pretty sure just using the archive page isn't going to be a great result, as the user may not see any specific information about what they have searched for. Also won't handle it well when no products are found in the search.

I'd recommend customizing the actual search templates to fit your needs instead.
