### ISSUE TITLE
Customer ID number / Company ID VAT number

### ISSUE THREAD

**Issue by UserName011** [woocommerce/woocommerce#19249]
Hi,
In the EU this is a mandatory requirement for invoices. I believe it's the same for many other countries.
The request for supporting such attribute exists since 2014:
http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/6794538-company-id-vat-id-to-be-stored-in-customer-accou

This property should be in the customer profile just like his address, phone number, email.
This can't be a custom field in the order itself.

My suggestion:
1. Add this property to the customer profile (when registering).
2. Allow store owner in the setting panel to choose if this field is mandatory or not (default is not mandatory)
3. display the field in order dashboard and in emails of each order (like the phone number).

**Comment by mikejolley** [comment]
I think you know whats coming :) Why are you bypassing the ideas board by logging things here? 

> This can't be a custom field in the order itself.

It can.

> since 2014

90 votes in 4 years doesn't seem like a lot. Possibly because extensions already handle this functionality. e.g. EU VAT Number extension which has been available longer.

Thanks
