### ISSUE TITLE
"woocommerce product download table" got deleted.

### ISSUE THREAD

**Issue by bloogle01** [woocommerce/woocommerce#19242]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. May be happened due to some plugin,
2. i am not sure of the cause.
3.

## Expected/actual behavior

When I follow those steps, i see nothing happening.
I was expecting that bought product should get downloaded.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Wordpress version - 4.9.4, Woocommerce 3.3.3,

After making the payment, the digital product should get downloaded but when you click on the download link nothing happens.

And the orders list shows that the order has been completed.

After searching the bug log, i found that the 'product download table' has been deleted.

Any of the Woocommerce pros can guide me on how to recreate that deleted table?

Looking forward to hear from the Woocommerce pros.

```
</details>

**Comment by mikejolley** [comment]
De-activate WC/re-activate to have the table created. It won't restore data though. You should probably look at plugins to work out which one did it!

**Comment by bloogle01** [comment]
I tried it already but it doesn't seem to work, I also deactivated all the plugins, then activated Woocommerce only but still getting the same error, does it have anything to do with WordPress not creating the table?

**Comment by mikejolley** [comment]
It could be the mysql account setup for your install lacking permissions?

**Comment by bloogle01** [comment]
Hey mike, prompt reply is highly appreciated.

so how can i correct this whole thing, is there any link or article which can give a step by step solution...?

**Comment by mikejolley** [comment]
You should first look in the DB to see if it's there (don't just trust status report). There is no step by step guide for this; missing tables is too uncommon to justify one.

**Comment by dasherer** [comment]
I had this same problem. I had to make sure the database user had select, update, insert, and delete permissions, then deactivate the WC plugin and re-activate it. now my only problem is that I have limited it to one download and I can still download as many times as I want.
