### ISSUE TITLE
REST API: Product will not be on sale if you set a time limit

### ISSUE THREAD

**Issue by Grauen** [woocommerce/woocommerce#19252]
I updated a product via REST API.
I set the start of the sale to the current date and the end of the sale will be n days later.

If I set a date for sale start or sale end, the dates will be set in the fields when editing the product via Woocommerce. However - the sale will be inactive.

If you just press the submit button in the product edit view, without changing anything, the sale will be active.

If you set no dates, the sale will be active after updating the product via the REST API.

**Comment by mikejolley** [comment]
Once I fixed my local dev environment (wrong date!) this worked as it should.

Testing endpoint:

`https://local.wordpress.test/wp-json/wc/v2/products/83`

And queries:

```
{
	"date_on_sale_from": "",
	"date_on_sale_to": "",
	"sale_price": ""
}
```

```
{
	"date_on_sale_from": "2018-03-07",
	"date_on_sale_to": "2018-03-09",
	"sale_price": "21"
}
```

Price was updated correctly in both cases.

**Comment by claudiosanches** [comment]
@WPprodigy have you tested? Can you confirm it?

**Comment by WPprodigy** [comment]
Mmm, thought I did - but working now as expected now.

Thinking maybe the server date was different than I was expecting when I tested
