### ISSUE TITLE
unable to avoid exposing consumerSecret/consumerKey in client code... ?

### ISSUE THREAD

**Issue by longstoryscott** [woocommerce/woocommerce#19256]
this may not be the appropriate place to ask this, but I'm not sure where else to ask... 

I'm working on an app that exclusively uses the WP/WC rest API for the front end, but have a problem using this feature with woocommerce. it seems that in order to list products on the public facing end of the site, you must access the data with the consumerSecret and consumerKey in the front end app, however, in my case and I assume others, this exposes the consumerKey and the consumerSecret in the front end files that are downloaded by the client. Am I missing something, or doesn't this pose a security issue? if so, is the recommended method to use some kind of middleware that is not downloaded by the client? how do you pass these keys to the API on a public facing app without exposing them to the public??

**Comment by WPprodigy** [comment]
That's correct. The WC REST API requires auth for getting product info. You could pass the keys as variables into a script (https://codex.wordpress.org/Function_Reference/wp_localize_script), but not sure of the security implications there. Alternatively, and what you suggested, would be another server, like Node for example.

Some more info here:

https://github.com/woocommerce/woocommerce/issues/18837
https://github.com/woocommerce/woocommerce/issues/17983

**Comment by mikejolley** [comment]
^

This API is not designed for user carts/to be used by customers. Your app needs to be in the middle and keep keys private.

**Comment by bcbweb** [comment]
@mikejolley Are there any future plans to implement this? I understand that it was built before the WordPress REST API and wasn't designed for this purpose, but I can't be the only one surprised and frustrated by the lack of ability to use the WooCommerce REST API to build an app that consumes data from a WordPress/WooCommerce backend much like we can use the WordPress REST API.

**Comment by mikejolley** [comment]
@bcbweb No plans - our API deals with sensitive data such as orders which is why it requires auth. Also there are no cart endpoints. 

The API however is extendable, so it's possible to roll your own if you have specific needs.

**Comment by Pushplaybang** [comment]
@bcbweb you're not alone and this sucks a bit.  

Also working with an SPA, and the general answer from woo is, "we know the api wasn't thought through for usability, just add your own proxy server". or be willing to expose all your order data, with a bit of a hack.

**Comment by mikejolley** [comment]
Sounds like you could join forces and build your own for this use-case, we won't stop you. 

The existing API has many uses - just because it does not meet your needs here does not mean it wasn't thought through. Think of it as a data API, whereas you need a cart API. It can and probably should be separate...

**Comment by bcbweb** [comment]
@mikejolley I don't know the most tactful way to communicate this, but there are other options out there that would be more worth our while than implementing our own API. I don't personally claim that it wasn't thought through, I just wish there had been a clearer indicator in the documentation that the WooCommerce REST API is not parallel to the WordPress REST API like one would imagine at first

**Comment by mikejolley** [comment]
@bcbweb Not really sure what you mean there - this is based on WordPress REST API. WordPress REST API is not a cart system. Any auth method in WordPress REST API works in WooCommerce REST API.

**Comment by Pushplaybang** [comment]
not really no.  the Woocommerce API was designed around dispatching a token for a specific client like you would if you were connecting to a Google API.   The WP REST API, doesn't simply expose all data or force you to dispatch a token. It leverages the WordPress Authentication system, acknowledging the relationship and common use case between its own back and front ends.

and to my previous point, there really are only two options here,
 - It was thought through, and you thought screw SPA's, or advanced front-ends on WP, they can just hack there way around this making it redundant in the totally unlikely event that's how more and more people will build front ends, or...
 - it wasn't really thought through.

neither is particularly great, but I would really like to believe it was the second.

the idea that you should need a separate server, that authenticates with a token,  and then proxies the API to your SPA is a hell of a requirement to simply fetch product data, especially when embedding a mini react or vue app into wp to create, for example, a unique product customizer, or any other unique shopping flow.

 - Any data, that can be displayed to the front end without user authentication, should be available publically, 
 - Any data that you could only access as a specific user with specific permissions should require authentication for the API as well.
 - lastly, the auth token option should be available, for the narrow use case of creating a store management app maybe?  Which seems to have been the only use case considered for the API.

It doesn't seem reasonable to me to try an argue that this is either consistent with the WP_API (as it would then satisfy the first two points), or doesn't provide the range of functionality we would all expect from woocommerce.

While I wouldn't support this, the only other alternative would be to clarify in the docs that this is an "admin api" only. Which is not the expectation all of the current marketing creates.

@bcbweb @mikejolley

**Comment by longstoryscott** [comment]
For those interested, there's the solution I worked out...

set up wp on nginx (I used a subdomain - admin.example.com)

set up a reverse proxy node server (I used _another_ subdomain - api.example.com)
   read up more on this [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04) and [here](https://medium.com/@utkarsh_verma/configure-nginx-as-a-web-server-and-reverse-proxy-for-nodejs-application-on-aws-ubuntu-16-04-server-872922e21d38) for more info/examples on this.

authenticate the node app, to grab all the data from wpapi and wcapi and filter it back to the client based on their authentication. I'll explain how this is handled

client side authentication is handled by [JWT authentication for WP REST API](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/). the user passes their credentials from the client-side app to the reverse proxy node server, which, in turn passes them to wordpress. the JWT plugin send a token back to the node server, which in turn passes it back to the client where it is stored as a Cookie. All subsequent requests are sent along with that Cookie. The node server evaluates the token on every request and sends the proper data back depending on user/user-type

This strategy has worked for me at least in creating a headless wordpress site with a react frontend. I'll publish a more thorough explanation along with sanitized code in the near future.

**Comment by Pushplaybang** [comment]
@longstoryscott yeah, that pretty much the option you're left with, and while it works, for simply getting access to the product catalogue, you must admit is excessive.

thanks for the useful post though, this is pretty much what we all need to do now :/

**Comment by bcbweb** [comment]
@Pushplaybang Or just use a different e-commerce platform

**Comment by Pushplaybang** [comment]
@bcbweb  - thanks,  I am for new projects.

**Comment by WPprodigy** [comment]
I mean, if this is really a blocker - why not create a custom REST API endpoint that exposes the product data you need and allow it to be public?

**Comment by longstoryscott** [comment]
@WPprodigy I think that's the established requirement. I think many people (myself included) are just surprised because at least some of the data seems like it would be geared towards a public facing app, and the fact that it's not contrasts with the WordPress REST API.

**Comment by pprotschka** [comment]
> set up a reverse proxy node server (I used _another_ subdomain - api.example.com)
> read up more on this [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04) and [here](https://medium.com/@utkarsh_verma/configure-nginx-as-a-web-server-and-reverse-proxy-for-nodejs-application-on-aws-ubuntu-16-04-server-872922e21d38) for more info/examples on this.
> 
> authenticate the node app, to grab all the data from wpapi and wcapi and filter it back to the client based on their authentication. I'll explain how this is handled
> 
> client side authentication is handled by [JWT authentication for WP REST API](https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/). the user passes their credentials from the client-side app to the reverse proxy node server, which, in turn passes them to wordpress. the JWT plugin send a token back to the node server, which in turn passes it back to the client where it is stored as a Cookie. All subsequent requests are sent along with that Cookie. The node server evaluates the token on every request and sends the proper data back depending on user/user-type
> 
> This strategy has worked for me at least in creating a headless wordpress site with a react frontend. I'll publish a more thorough explanation along with sanitized code in the near future.

this is very much the solution i arrived at after much thought. alternatives where to use the php client within the wordpress php code itself (silly but also works!) problem here is that its relatively slow which somewhat defeats the purpose of going away from ajax.php to an API.

do you have code for the nodejs middleware? any snippets would be appreciated :)

**Comment by LongStoryMedia** [comment]
@pprotschka here's the full repo [https://github.com/LongStoryMedia/LongStoryPress](https://github.com/LongStoryMedia/LongStoryPress) - the comments and documentation are a bit lacking,   but you can see my setup for the headless WP theme, and the submodule for the [frontend](https://github.com/LongStoryMedia/LSP_UI) has a folder in ``src`` called ``data-server`` that has all the code for the node server. I'm refactoring what I have in production right now (to avoid having a separate file for every single route), so this exact server is not tested in production, and doesn't include some workarounds I've built into my production code, like user registration and login.

One thing I'm excited about with this particular setup, is that it's a multisite, and the addition of a new site, should be as simple as adding a folder with some dotenv files at the root (adjacent to wp-content). The frontend build will use webpack to create a server bundle for the proxy node api server, a small node server for react ssr, the frontend bundle (and chunks), and the nginx server.conf, which you can ``include`` in a master conf file.

I'll keep working on the documentation (and try to make my code more readable... or at least add some comments :) ). If you do take a look and have any suggestions to make, please let me know, or submit a PR.

**Comment by Zaniyar** [comment]
any new changes to the WC API to make this possible?

my solution would be, create a WP plugin that exposes an endpoint to fetch products, which can than be consumed on the clientside...
