### ISSUE TITLE
Mobile version menu of the Storefront plugin Version: 2.2.8

### ISSUE THREAD

**Issue by ricare** [woocommerce/woocommerce#19259]
On the desktop the menu for https://www.theinspireddiabetic.com show perfectly fine. on the mobile with both browser firefox and brave, it show all the page of the site, and I did not select them to be part of the menu? easy see it for your self

**Comment by GlennMartin1** [comment]
This is the place for reporting WC Core bugs. 

There's a setting for the Handheld menu in the Customizer. 

Go to Customizer > Menus > choose the menu you want > in the Menu Locations, check "Handheld Menu" . 

Save.

**Comment by WPprodigy** [comment]
That ^.

For future reference, this is the correct place for theme support: https://wordpress.org/support/theme/storefront. And WooCommerce.com premium support if you have purchased any of the premium products there.
