### ISSUE TITLE
Sort Product Variation By Price Issue

### ISSUE THREAD

**Issue by linhnh95** [woocommerce/woocommerce#19265]
Hello.
I have a problem when I execute code sort product under product price.
The Variation product creates two "_price" fields in the database. And when I set key sort = "_price". Products sorted by field "_price" have higher values ​​while I want to sort by lower field "_price".
Is there a way I can sort by lower "_price" field

**Comment by mikejolley** [comment]
Only with custom queries like we use here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-query.php#L507-L558

**Comment by linhnh95** [comment]
Ok. Thanks @mikejolley
