### ISSUE TITLE
Can’t add images to product variations

### ISSUE THREAD

**Issue by maxwellhibbert** [woocommerce/woocommerce#19260]
I get a javascript error when clicking the “upload an image” thumbnail inside a product variation.

Chrome dev tools gives me this:
Uncaught TypeError: wp.media.controller.Library is not a constructor
meta-boxes-product-variation.min.js?ver=3.3.3

Same in Safari, which also points to the following line of the error:
states: [new wp.media.controller.Library({

Found this in the PHP logs:
PHP Fatal error:  Cannot declare class WC_Settings_Products, because the name is already in use in /woocommerce/includes/admin/settings/class-wc-settings-products.php on line 449

Pretty much a fresh install of WP and Woo.

WordPress 4.9.4
Woo Version 3.3.3
Chrome 64.0.3282.186
Safari Version 11.0.3 (13604.5.6)

**Comment by WPprodigy** [comment]
I'm not able to replicate this, and I would imagine it would have been reported a lot more if there were a core conflict happening.

Rule out plugin/theme conflicts first: https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4

If the issue still exists with only WooCommerce active along with a default theme, then let me know and we can open up this issue back up.

Also please post your system status report here if that is the case.

**Comment by maxwellhibbert** [comment]
Apologies. The Measurement Price Calculator plugin was the culprit.

**Comment by weijmedia** [comment]
@maxwellhibbert 

Can I ask, how did you fix this problem?

I've got this problem with the Measurement Price Calculator plugin as well (class-wc-settings-products.php on line 471).

**Comment by maxwellhibbert** [comment]
Pretty sure the plugin just needed an update

**Comment by WPprodigy** [comment]
Send in a ticket with the account used to purchase Measurement Price Calculator: https://woocommerce.com/my-account/marketplace-ticket-form/

**Comment by weijmedia** [comment]
Thanks.

**Comment by hendrasyp** [comment]
There's also conflict with **WPA WooCommerce Product Bundle** Plugin from WPAddon.net
