### ISSUE TITLE
How do I change stock_status value from 1 or 0 to J or N?

### ISSUE THREAD

**Issue by thinkingfuture** [woocommerce/woocommerce#19262]
Hey there.

In the [CSV columns and formatting ](https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema#csv-columns-and-formatting)guideline for Woocommerce, the stock_status property has 1 (true/in stock) and 0 (false/not in stock) as alternative values. My problem: the file that contains the information whether a product is in stock or not is a txt-file and it uses the values J (in stock) and N (not in stock). It derives from the FTP Server of the warehouse that ships the products for me.

Does anyone maybe have an idea how to change the values from 1/0 to J/N so that woocommerce can interpret the files from the FTP-Server.

Thanks,
Alex

**Comment by mikejolley** [comment]
You'd have 2 options;

1. Edit the CSV before upload and convert to our format
2. Custom code hooked here to convert the value before it's imported https://github.com/woocommerce/woocommerce/blob/master/includes/import/abstract-wc-product-importer.php#L216

Thanks
