### ISSUE TITLE
Add filter to woocommerce_form_field (Re: #12912)

### ISSUE THREAD

**Issue by ontiuk** [woocommerce/woocommerce#19270]
Pull request #12912 added a filter to the 'woocommerce_form_field' function to enable filtering of the field container. This was closed.

At present the function enforces the container to be a P tag and to contain the 'form-row' class. The class in particular clashes with the bootstrap4 form class and can't be replaced through existing filters. The standard solution to make the field bootstrap-like is to add the form-group and form-control classes to container and element respectively. Having a form-row and form-group class at the same level is problematic. 

This would enable the form-row class to be removed/replaced.

A reopening / rethinking of the decision would be appreciated.

**Comment by claudiulodro** [comment]
That filter doesn't really make sense, though. Further down [there is code that would override whatever you had filtered in some cases](https://github.com/woocommerce/woocommerce/pull/12912/files#diff-65760bf45f136dba5d546afa2c8b7ee9R1961). I believe you can use [this existing filter](https://github.com/woocommerce/woocommerce/pull/12912/files#diff-65760bf45f136dba5d546afa2c8b7ee9R2063) instead.

**Comment by pelmered** [comment]
I don't think that reasoning makes sense. 
First of all it's pretty bad that you include the field type in the key name. You would have to register 10 filters to change this for every field type. You would also need to rewrite pretty much all the logic in that whole function if you use the filter that you suggest if you don't do a regex to replace what you want for example the container tag. Regexes are slow, error prone and much more complex.

**Comment by pelmered** [comment]
To illustrate the first point:

```php
add_filer( 'woocommerce_form_field_before_container', 'callback', 4 );

// VS

add_filer( 'woocommerce_form_field_before_container_country', 'callback', 4 );
add_filer( 'woocommerce_form_field_before_container_textarea', 'callback', 4 );
add_filer( 'woocommerce_form_field_before_container_checkbox', 'callback', 4 );
add_filer( 'woocommerce_form_field_before_container_password', 'callback', 4 );
add_filer( 'woocommerce_form_field_before_container_text', 'callback', 4 );
add_filer( 'woocommerce_form_field_before_container_ email', 'callback', 4 );
add_filer( 'woocommerce_form_field_before_container_tel', 'callback', 4 );
add_filer( 'woocommerce_form_field_before_container_number', 'callback', 4 );
add_filer( 'woocommerce_form_field_before_container_select', 'callback', 4 );
add_filer( 'woocommerce_form_field_before_container_radio', 'callback', 4 );
```

**Comment by claudiulodro** [comment]
I see. That makes sense. It seems like an all-purpose `'woocommerce_form_field'` filter [on this line](https://github.com/woocommerce/woocommerce/pull/12912/files#diff-65760bf45f136dba5d546afa2c8b7ee9R2062) would solve the issue well, then.

**Comment by ontiuk** [comment]
Hi Claudio. Ultimately for the current client project I've done similar to what pelmered suggested. Long winded and a bit messy, but functional. Either a form_field_container filter, or additional args for the function such as 'form_field_container' & 'form_field_container_class' would work. Thanks.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19388
