### ISSUE TITLE
System status page fatal errors when using Hyper DB

### ISSUE THREAD

**Issue by zacscott** [woocommerce/woocommerce#19279]
The WooCommerce system status page fatal errors when configured using Hyper DB. Below is a screenshot of the error on New Relic, happening on one of our WC sites.

![new relic - error trace - redacted](https://user-images.githubusercontent.com/3852691/37074491-e035d694-2218-11e8-8aca-a8bce27edaa2.png)

The code which causes the error is this;

```
if ( $wpdb->use_mysqli ) {
	$ver = mysqli_get_server_info( $wpdb->dbh );
} else {
	$ver = mysql_get_server_info(); // @codingStandardsIgnoreLine
}
```

HyperDB sets `$wpdb->use_mysqli` to false, which means it tries to call `mysql_get_server_info()` which fails on PHP7.

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install [Hyper DB](https://wordpress.org/plugins/hyperdb/)
2. Go to the status page /wp-admin/admin.php?page=wc-status

## Expected/actual behavior

When viewing the status page, it fails at the point of the MySQL version section. Part of the page renders but it 500s before all of the sections load

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: [redacted]
Site URL: [redacted]
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US

### Server Environment ###

Server Info: nginx/1.13.6
PHP Version: 7.1.12-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
```
</details>

**Comment by kloon** [comment]
@zacscott would you mind testing the patch at #19281 to see if this resolves the issue for you? We run hyperdb on woocommerce.com and do not have this issue there, but the fix I added in the PR should address the issue for when these functions are disabled for some reason on the server.
