### ISSUE TITLE
singel variation url not auto selecting the option on single product page !

### ISSUE THREAD

**Issue by AmirRafiee** [woocommerce/woocommerce#19272]
WC version: 3.1.0
WP version:  4.7.3

https://takmetal.com/product/%D9%BE%D9%85%D9%BE-%D9%85%DA%AF%D9%86%D8%AA%DB%8C-%D9%85%D8%A7%D8%B1%DA%A9-spc/?attribute_pa_%D8%AA%DA%A9%D9%81%D8%A7%D8%B2-%DB%8C%D8%A7-%D8%B3%D9%87-%D9%81%D8%A7%D8%B2=%25d8%25aa%25da%25a9%25e2%2580%258c%25d9%2581%25d8%25a7%25d8%25b2&attribute_pa_%D8%AD%D8%AF%D8%A7%DA%A9%D8%AB%D8%B1-%D8%A2%D8%A8%D8%AF%D9%87%DB%8C=45-%25d9%2584%25db%258c%25d8%25aa%25d8%25b1-%25d8%25af%25d8%25b1-%25d8%25af%25d9%2582%25db%258c%25d9%2582%25d9%2587&attribute_pa_%D8%AD%D8%AF%D8%A7%DA%A9%D8%AB%D8%B1-%D8%A7%D8%B1%D8%AA%D9%81%D8%A7%D8%B9=46-%25d9%2585%25d8%25aa%25d8%25b1&attribute_pa_%D8%AF%D9%87%D8%A7%D9%86%D9%87-%D8%AE%D8%B1%D9%88%D8%AC%DB%8C=20-%25d9%2585%25db%258c%25d9%2584%25db%258c%25d9%2585%25d8%25aa%25d8%25b1

and the decoded version

https://takmetal.com/product/پمپ-مگنتی-مارک-spc/?attribute_pa_تکفاز-یا-سه-فاز=%d8%aa%da%a9%e2%80%8c%d9%81%d8%a7%d8%b2&attribute_pa_حداکثر-آبدهی=45-%d9%84%db%8c%d8%aa%d8%b1-%d8%af%d8%b1-%d8%af%d9%82%db%8c%d9%82%d9%87&attribute_pa_حداکثر-ارتفاع=46-%d9%85%d8%aa%d8%b1&attribute_pa_دهانه-خروجی=20-%d9%85%db%8c%d9%84%db%8c%d9%85%d8%aa%d8%b1

both do not auto select the variation base of the given parameters 
(the variation does exist for sure)

**Comment by claudiulodro** [comment]
There have been many fixes since WC 3.1.0. The first thing you should try is [upgrading WooCommerce and WordPress to the newest versions to see if that solves your issue](https://docs.woocommerce.com/document/how-to-update-woocommerce/).

**Comment by AmirRafiee** [comment]
i did update wp and wc to the latest version but the problem still remains :)

**Comment by AmirRafiee** [comment]
i think it's because of the persian characters in the url

**Comment by claudiulodro** [comment]
Yeah I believe because of the Persian characters it's not matching up [right here](https://github.com/woocommerce/woocommerce/blob/44c1de45eb56f578cc83744890b1e8f290dfa85e/templates/single-product/add-to-cart/variable.php#L39-L40).

**Comment by AmirRafiee** [comment]
hello guys and thank you for your time 
i solved this issue just now but it's permanent 
so here is the code that worked for me but still i have not tested it with english or any other languages except persian :

woocommerce > single-product > add-to-cart > variable.php 

$selected = urldecode($_REQUEST[ 'attribute_' . urldecode(sanitize_title( $attribute_name )) ]);
								$selected = isset( $selected ) ? wc_clean( stripslashes( $selected ) ) : $product->get_variation_default_attribute( $attribute_name );

**Comment by kloon** [comment]
@AmirRafiee PR ready for this fix which also works with English https://github.com/woocommerce/woocommerce/pull/19283
