### ISSUE TITLE
GDPR: Add support for personal data export for a given email address

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#19277]
In support of GDPR personal data export requirements, for a given email address, the personal data exported should include at least the following from usermeta added by WooCommerce:

- Billing Address First Name, Last Name, Company, Address Line 1, Address Line 2, City, Postcode/ZIP, Country, State/County, Phone, Email Address
- Shipping Address First Name, Last Name, Company, Address Line 1, Address Line 2, City, Postcode/ZIP, Country, State/County

Additionally, for each order where that email address matches the billing email address, the personal data exported should include at least the following:

- Transaction ID
- Customer's IP Address and User Agent
Billing Address First Name, Last Name, Company, Address Line 1, Address Line 2, City, Postcode/ZIP, Country, State/County, Phone, Email Address
- "Billing Fields" (`_billing_address_index`)
- Shipping Address First Name, Last Name, Company, Address Line 1, Address Line 2, City, Postcode/ZIP, Country, State/County *
- "Shipping Fields" (`_shipping_address_index `) *

Additionally, for each product review where the email address matches the user_email address in the review, the personal data exported should include at least the following:

- Review Author, Email, Author URL, Author IP Address and User Agent

Lastly, for downloadables associated with the given email address, the personal data exported should include at least the following:

- Downloadable Product User Email `(wp_)woocommerce_downloadable_product_permissions` `user_email`
- Download Log Entry User IP Address `(wp_)wc_download_log` `user_ip_address`

`* maybe these should NOT be exported unless it matches the billing data - in order to protect the privacy of a 3rd party?`

See also https://github.com/Automattic/woocommerce-services/issues/1323

**Comment by allendav** [comment]
TBD - does a registered customer's user ID qualify as personal data?

**Comment by mikejolley** [comment]
ID has no meaning outside of the store.

**Comment by mikejolley** [comment]
@kloon probably a good task to start. Doesn't have to integrate with anything yet, but getting working queries in place  to get a data dump of above by email will save us time later.

**Comment by mikejolley** [comment]
@allendav Reviews out out of scope - they are comments. Let WP handle it.

**Comment by mikejolley** [comment]
This one is satisfied by https://github.com/woocommerce/woocommerce/pull/19330 which integrates with the tool in WP Core.
