### ISSUE TITLE
GDPR: Add support for personal data removal for a given email address

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#19278]
In support of GDPR personal data removal requirements, for a given email address, the personal data removed from orders should include at least the following in each order where that email address matches the billing email address:

- Transaction ID
- Customer's IP Address and User Agent
Billing Address First Name, Last Name, Company, Address Line 1, Address Line 2, City, Postcode/ZIP, Country, State/County, Phone, Email Address
- "Billing Fields" (`_billing_address_index`)
- Shipping Address First Name, Last Name, Company, Address Line 1, Address Line 2, City, Postcode/ZIP, Country, State/County *
- "Shipping Fields" (`_shipping_address_index `) *

Also, for downloadables associated with the given email address, the personal data removed should include at least the following:

- Downloadable Product User Email `(wp_)woocommerce_downloadable_product_permissions` `user_email`
- Download Log Entry User IP Address `(wp_)wc_download_log` `user_ip_address`

`* I wonder if we should only remove the personal data from shipping if shipping matches billing`

See also https://github.com/Automattic/woocommerce-services/issues/1324

**Comment by allendav** [comment]
Note regarding customers with registered user accounts: It is assumed that personal data removal for a registered user includes deletion of the registered user's account.  I think that means that we just need to verify that personal data for that user is no longer present in `wp_)usermeta` nor `(wp_)comments` (for product reviews)

**Comment by tarkan123** [comment]
You have to be careful here. 

Data provided by a subject for the purpose of/and performance of a contract (i.e. supplying goods or services) only, does not necessary fall in to  GDPR art.17 (right to erasure).

The data controller is allowed to maintain records of purchases, to show proof of work completed & proof of purchase, and possibly records of invoices & receipts for tax reporting purposes.

Of course if you intend to use the information outside of the scope of performing a contract, then there is a right of erasure from that part of processing of data, but you still do not have to delete or destroy purchase records especially if the tax authority has a right to demand proof of sale!

**Comment by tarkan123** [comment]
Sorry forgot my actual point after the rambling on!!

It would be good to have the ability of deleting the customers account, without deleting any existing purchasing information (i.e. reverting previous orders as placed by a Guest).

I can imagine customers requesting that their accounts being deleted but of course we would need to retain purchase information as invoices/receipts are generated by woocommerce.

Not sure if it works like that at the moment.

**Comment by DavidAnderson684** [comment]
Right to erasure: https://gdpr-info.eu/art-17-gdpr/ . As tarkan123 says, it is not an absolute right. See 3) in particular; the right to erasure does not apply where there is a remaining legal obligation to process the data; e.g. tax records or auditing. e.g. The EU digital VAT law requires keeping the data that was used to establish buyer location for 10 years. That includes the IP address. Similarly I infer that where the billing address is passed directly to the payment gateway (e.g. the WooCommerce Stripe extension) and verified against the card, erasing the billing address is also prohibited by this regulation.

**Comment by mikejolley** [comment]
TODO:

- [ ] Create a new method for customer and order objects `->remove_personal_data()` or `->anonymize()` TBD
   - [ ] Pass through array of data identifiers so we can delete conditonally
- [ ] Create data store methods too which these will use. The data store clears the data.
- [ ] Replace data with "REDACTED"?
- [ ] After anonymization, check orders etc still work. Disable calculations for taxes if no data exists in the order and it's been stripped of data.  
- [ ] Fire hooks during these events.
- [ ] Cover with unit tets.

UI awaits https://core.trac.wordpress.org/ticket/43437#comment:7

**Comment by kloon** [comment]
I am wondering, for the removal of the personal data can we still keep things like city, state and country in place? As long as we remove the link from the email and the customer's address that should be good no? IE just remove identifiable data, you cannot identify someone via city, state or country? That way we can still have some tax functionality

**Comment by mikejolley** [comment]
@kloon For now I'd work under the assumption the data may be missing - we should handle it.

If we get a tool in core, it could be down to the admin user to decide.

**Comment by DavidAnderson684** [comment]
@mikejolley @kloon One complex issue that I haven't seen a lot of discussion about for GDPR is the need to keep a log of deletion events, so that if you have to restore your database/site from a backup, you must then re-delete all the data that has been deleted since the backup.

i.e. If a user requests deletion of their data, then technically it should be deleted from backups too. But, GDPR has allowances for technically infeasible tasks - having to unpack your backup, delete data, and re-pack it would arguably be in that category. But, if the backup is actually *used*, then the deleted data is back. So, a deletion log has to be kept. Obviously having that log in the database itself is no good because the backup might be needed because of the database being lost. About the only universally available mechanism would be "send an email", and then the site owner has to go through his emails. Larger sites would be able to use a hook to deploy a more sophisticated method of logging upon every deletion event.

What do you think?

**Comment by DavidAnderson684** [comment]
The material in the GDPR regulations on anonymisation and pseudo-anonymisation is also very relevant. Summarised here https://www.csoonline.com/article/3215188/access-control/hacking-the-gdpr.html (also of use: https://www.pwc.lu/en/general-data-protection/docs/pwc-anonymisation-and-pseudonymisation.pdf ).
On the specific issue of town, city, country, transaction ID, it seems to me on a reading of those resources that the data controller would be able to easily justify not removing or obfuscating those details.

**Comment by mikejolley** [comment]
@DavidAnderson684 Not just relevant to WC, you should add that to the trac tickets or join the WP slack - there is a room dedicated to GDPR going on.

**Comment by ajgw** [comment]
But in case a order is placed, we here in germany need store all order details including customer data for ten years – that is required by financial law. Or isn't this reflected?

**Comment by mikejolley** [comment]
This is now ready in https://github.com/woocommerce/woocommerce/pull/19808 - see that PR.
