### ISSUE TITLE
Flat Tax for Oregon Residents

### ISSUE THREAD

**Issue by Islabikes** [woocommerce/woocommerce#19275]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

This is not a bug, but a missing feature in WooCommerce.  I was referred here by the WooCommerce tech support team.  The State of Oregon has recently passed legislation requiring a $15 tax on every bicycle sold to OR residents with a purchase price of > $200.  WooCommerce only supports percentage-based sales taxes, which is not applicable in our situation as our products range from $420 - $2400, but each bike only incurs a $15 tax regardless of the purchase price.  Here's a blog post on the subject with a link to the actual legislation (https://bikeportland.org/2018/03/01/oregons-expanded-bike-tax-passes-out-of-committee-with-unanimous-support-270013)

We cannot use the Product Fees plugin because the tax is not applied to all purchases/customers but only those in OR (and we sell across the US and Canada).

Thanks for any ideas or support!

Islabikes team.

**Comment by mikejolley** [comment]
I don't want to sound dismissive, but the idea of adding a whole new fixed tax system in WooCommerce to account for the sale of only Bikes, for customers in only one state sounds really wasteful. 

I think fees can work for you. Fees can be added based on country:

https://docs.woocommerce.com/document/add-a-surcharge-to-cart-and-checkout-uses-fees-api/#section-3

So it wouldn't be much of a stretch to base this on country, state and item.

**Comment by claudiulodro** [comment]
I just tried out [WooCommerce Conditional Product Fees for Checkout](https://wordpress.org/plugins/woo-conditional-product-fees-for-checkout/) and it can do what you need. You can set up a $15 "Bike tax" fee for bikes bought by Oregonians.

(As an Oregonian 👎 to that new law)

**Comment by Islabikes** [comment]
This is perfect.  Thank you claudiulodro!  And we agree on the thumbs down on the tax, but now we need to follow the law.  :(
