### ISSUE TITLE
Private products do not show content when viewing

### ISSUE THREAD

**Issue by kennybruin** [woocommerce/woocommerce#19276]
With the latest update of woocommerce, when a products visibility has been set to private, no content is shown when viewing/previewing the product page (blank page).

When set to public, content is visible at once.
This is not useful for admins that want to add products/review product pages before publishing them in the future.
For me this is a huge issue.

**Comment by WPprodigy** [comment]
Can't replicate this. Private works for me (shows content when logged in as an admin): http://cld.wthms.co/rPc7ET

Likely have a theme or plugin conflict: https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4

Can re-open if you find that this happens with only WC active and a default WP theme.

**Comment by mikejolley** [comment]
![this is private local wordpress dev 2018-03-06 22-11-52](https://user-images.githubusercontent.com/90977/37061428-649b63ec-218b-11e8-8cd8-5447a17db5cb.png)

Same here works.
