### ISSUE TITLE
customizer warning pls fix

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#19286]
In the customizer i see this warning.

> <b>Warning</b>:  sprintf(): Too few arguments in <b>/var/docs/wpany.tst/public/wp-content/plugins/woocommerce/includes/customizer/class-wc-shop-customizer.php</b> on line <b>453</b><br />

code should be %1$s  not %2$s

`		$regen_description = sprintf( __( 'After publishing your changes, new image sizes may not be shown until you <a href="%1$s" target="_blank">Regenerate Thumbnails</a>.', 'woocommerce' ), 'https://en-gb.wordpress.org/plugins/regenerate-thumbnails/' );`

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/19171
