### ISSUE TITLE
import with no sku or ID - while UPDATE ticked - result in importing new products

### ISSUE THREAD

**Issue by looknear** [woocommerce/woocommerce#19287]
1. create CSV with empty id and sku column. or even unset id and sku in 'woocommerce_product_importer_parsed_data'
2. import the CSV and tick the optional ''Existing products that match by ID or SKU will be updated. Products that do not exist will be skipped."
3. products will be imported and not SKIPPED as expected

**Comment by mikejolley** [comment]
The system cannot "skip" if it doesn't have any idea what the ID and SKU is. Thats what matching is based on. 

> Update existing products: If you have IDs and/or SKUs in your CSV file, the importer can update your existing products that have the same IDs or SKUs with information from the CSV. Check this box if you want this behavior, otherwise the importer will skip CSV products that have the same ID or SKU as an existing product.

https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Importer-&-Exporter
