### ISSUE TITLE
Cannot filter SKU

### ISSUE THREAD

**Issue by davidperezgar** [woocommerce/woocommerce#19285]
Hello, since WooCommerce 3.3, I cannot filter to hide SKU in product page.

I used this filter:
add_filter( 'wc_product_sku_enabled', '__return_false' );

But now it does not work.
Is it a bug? or Has it changed the filter?

Regards.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/728e6dc58d1e37cea605b1424be70dba8217135a/includes/wc-product-functions.php#L77 Filter is here.

https://github.com/woocommerce/woocommerce/blob/71d0702523bcc365403dd3b84b945da5218d88b4/templates/single-product/meta.php#L29-L33 Usage is here.

Maybe a bug with your usage or your theme (they don't need to use the function), but the code in core looks fine to me.
