### ISSUE TITLE
Woocomerce webhook ORDER,PRODUCT,CUSTOMER not triggered

### ISSUE THREAD

**Issue by souravthakur1992** [woocommerce/woocommerce#19282]
I have installed docker image on my local environment for woo comerce to integrate woo commerce platform with my .net app . i am able to do authorization and registration of the web hooks from .net app using rest api.
first time authorization of the delivery url is verfied and passed successfully, but whenever i am updating order , product or customer nothing is triggered from woo comerce app.
i have checked status> log but its empty.
kindly suggest any solution.

`
### WordPress Environment ###

Home URL: http://localhost:8080
Site URL: http://localhost:8080
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 3.37MB
Database Data Size: 2.21MB
Database Index Size: 1.16MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_oauth_access_tokens: Data: 0.02MB + Index: 0.02MB
wp_oauth_authorization_codes: Data: 0.02MB + Index: 0.02MB
wp_oauth_jwt: Data: 0.02MB + Index: 0.02MB
wp_oauth_public_keys: Data: 0.02MB + Index: 0.02MB
wp_oauth_refresh_tokens: Data: 0.02MB + Index: 0.02MB
wp_oauth_scopes: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.02MB + Index: 0.02MB
wp_postmeta: Data: 0.17MB + Index: 0.17MB
wp_posts: Data: 0.38MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 6
page: 5
post: 10
product: 8
shop_order: 7
wp-rest-api-log: 41

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Wise Builds cURL Options: by Wise Builds – 1.1.2
WooCommerce: by Automattic – 3.3.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #8 - /my-account/

### Theme ###

Name: Twenty Sixteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
<img width="949" alt="webhook" src="https://user-images.githubusercontent.com/13482053/37081336-15eb20e6-220f-11e8-80bd-7e8acc2c91d3.PNG">

**Comment by lassejuhlkirk** [comment]
+1

**Comment by Storebuddy** [comment]
We are experience similar problems, we are using webhooks on 50+ webshops which are running different configurations and plugins. (We are admins on these shops and therefore it is difficult to debug for us). 
Although there seems to be some problems after updating to 3.0.0+ where all webhook id changed and the "core" hooks changed for all existing webhooks. Before an Order.Create had the hooks:

```json
 "hooks": [
            "woocommerce_checkout_order_processed",
            "woocommerce_process_shop_order_meta",
            "woocommerce_api_create_order"
             ],
```

And after updating 
```json
       "hooks": [
            "woocommerce_process_shop_order_meta",
            "woocommerce_new_order"
        ]
```

This doesn't seem to cover the previous hooks on the default Order.Create.

Could there be any cases where an order is created without these hooks are triggered?

**Comment by mikejolley** [comment]
`woocommerce_process_shop_order_meta` covers admin save.
`woocommerce_update_order` covers any other save/create event via CRUD.

So the other events are not needed.

You didn't provide steps to reproduce the issue so I did my own thing. To test:

1. I created an order create webhook with delivery URL http://local.wordpress.test/
2. I then placed an order on the frontend. 
3. I then went to Status > Logs and selected webhook devliery.

```
2018-03-07T22:06:11+00:00 INFO Array
(
    [Webhook Delivery] => Array
        (
            [Delivery ID] => 4f0d72689fd47b69e224d7c229db79c6
            [Date] => Mar 7, 2018 @ 22:06
            [URL] => http://local.wordpress.test/
            [Duration] => 0.10497
            [Request] => Array
....
```

So this was fired and working.

This leads me to suggest either:

1. You're not looking at the correct log to see if it was triggered.
2. Your order is not being created by the checkout/within admin or you're doing something different than I.
3. Your CURL plugin/delivery address is not working due to this being on a test site localhost.

Thanks

**Comment by Storebuddy** [comment]
@souravthakur1992  I think your problem relates to docker. I did the same setup, with wp cli installed. Running a wp cron test:
`
root@5829350764bd:/var/www/html# wp cron test --allow-root
Error: WP-Cron spawn failed with error: cURL error 7: Failed to connect to localhost port 8080: Connection refused
root@5829350764bd:/var/www/html# wp cron test --allow-root
Error: WP-Cron spawn failed with error: cURL error 7: Failed to connect to 127.0.0.1 port 8080: Connection refused
root@5829350764bd:/var/www/html# wp cron test --allow-root
Success: WP-Cron spawning is working as expected.
`
The last run i changed the home and site_url to the ip of the docker container and the hooks was fired

**Comment by souravthakur1992** [comment]
@Storebuddy 
Thanks it worked there is problem with the setup of the docker i used this wordpress cli setup and done composed up everything works fine then. Thanks all for valuable feedback .
https://github.com/docker-library/docs/tree/master/wordpress
