### ISSUE TITLE
Get related Products also returnd draft products in the array of ids for the related products

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#19298]
Hi

Could it be that wc_get_related_products()  also pulls draft posts?  I just checked and tripple checked and if i call  wc_get_related_products($product_id,$related_count);  where $related_count=4 and $product_id = the product_id i see the draft product returned in the array of related products.  This should not happen.

Pls fix.

![get_related](https://user-images.githubusercontent.com/6078370/37104571-5a3936c0-222d-11e8-8743-0237f351ec0f.jpg)

Thanks

**Comment by mikejolley** [comment]
Drafts are not shown to customers. You can see because it's your draft.

**Comment by BackuPs** [comment]
can i exclude it ?

**Comment by mikejolley** [comment]
No, but as I said. A customer won't see it :) Ignore.
