### ISSUE TITLE
orders go to "processing" instead of "completed" (plugins disabled, default wp theme)

### ISSUE THREAD

**Issue by Planrep** [woocommerce/woocommerce#19297]
So I have a payment gateway plugin that uses $order->payment_complete() method to complete the payment and set the order as completed. I've followed in debug mode and noticed when calling to $order->payment_complete() you have to go through the following line:

$this->set_status( apply_filters( 'woocommerce_payment_complete_order_status', $this->needs_processing() ? 'processing' : 'completed', $this->get_id(), $this ) );

which sets the status to "processing" instead of "completed" even though the product is not virtual nor downloadable.

Traceback is as follows:
1. needs_processing() returns true 
2. apply_filters( 'woocommerce_order_item_needs_processing', ! $virtual_downloadable_item, $product, $this->get_id() ) returns true.
3. the apply_filters returns true because it product is not virtual neither downloadable. so it gets here (lines 188-192 in plugin.php):
if ( !isset($wp_filter[$tag]) ) {
    if ( isset($wp_filter['all']) )
      array_pop($wp_current_filter);
  return $value;
}

and returns the $value which is true. (because produc is NOT virtual NOR downloadable).
So the $wp_filter[$tag] is empty. Practically it means that the 'woocommerce_order_item_needs_processing' is not set! ($tag = 'woocommerce_order_item_needs_processing')

Please assist,
Jonathan

**Comment by mikejolley** [comment]
> So I have a payment gateway plugin that uses $order->payment_complete() method to complete the payment and set the order as completed.

Using `payment_complete` does not set status to completed in all cases. Processing is more likely if the order needs to be fulfilled.

> even though the product is not virtual nor downloadable.

Orders require action e.g. shipping UNLESS the products inside are BOTH virtual AND downloadable.

So in this case, it sounds correct to be processing. Processing = Paid, go ship it.

**Comment by Planrep** [comment]
Thanks for your reply.
How can I make sure there is no required action.
I've disabled shipping completely (Woocommerce => General => disable shipping) but I still get my orders going to "processing" mode.

**Comment by mikejolley** [comment]
There are snippets you can use - do a quick search :)

**Comment by Planrep** [comment]
Thanks.
I didn't mean that I need a snippet that auto completes my payments (I found  this extension for instance https://docs.woocommerce.com/document/woocommerce-order-status-control/ ). I want to understand if shipping is disabled why do orders still go to processing mode? What I would have liked to receive (and I think it is also important to the entire community of developers) is a list of the DEFAULT woocommerce required actions that prevent an order from becoming complete. I guess this list is small...

BTW, as mentioned hook 'woocommerce_order_item_needs_processing' is empty so I would think that on the contrary - woocommerce does not need processing.

Thanks again,
Jonathan

**Comment by mikejolley** [comment]
> BTW, as mentioned hook 'woocommerce_order_item_needs_processing' is empty so I would think that on the contrary - woocommerce does not need processing.

It expects a boolean.

> I want to understand if shipping is disabled why do orders still go to processing mode?

Just because you're not charging shipping, do not mean you have nothing to process/fulfil/send/do. If you're doing nothing, what is the customer paying for?

**Comment by Planrep** [comment]
thanks :-)
