### ISSUE TITLE
negative shipping should result in negative vat not zero vat

### ISSUE THREAD

**Issue by LukasSteindl** [woocommerce/woocommerce#19293]
Our products already include shipping costs in their price. However we deduct shipping when the customer decides to pickup the product in our store. 

these negative shipping costs show an incorrect vat of 0 vat for shipping. 
this is what we see in the backend after customer placed an order with store-pickup option:
![bad](https://user-images.githubusercontent.com/15838914/37096388-be301a6e-2218-11e8-8814-0fb24fba49cd.jpg)

this leads to an incorrect total vat on the invoice. 

 what we expect to see is the following:
![good](https://user-images.githubusercontent.com/15838914/37096444-e898aae6-2218-11e8-9d4a-ac78a03abc00.jpg)

The vat in this example is 13%. 
On the correct invoice the tax included in the total amount is: 6.5 /113*13 = 0.75
In the wrong invoice the tax shows 0.91.

**Comment by mikejolley** [comment]
Negative shipping is undocumented. It shouldn't be possible.

**Comment by LukasSteindl** [comment]
we did an A/B-Test and realized that if we include the shipping-cost in the price, we receive significantly more orders compared to not including the shipping cost and adding them explicitly. 
any ideas how this could be modeled otherwise?

**Comment by mikejolley** [comment]
if you're not showing shipping on site, why remove it for local pickup?

Could use coupons.
Could use fees API.
Could just advertise free shipping and include in prices :)

**Comment by LukasSteindl** [comment]
Prices for local pickup should be the same on the website as stated on the physical-price-lists in the store.
Existing customers who usually pickup wine bottles in our store would not accept such a price increase. 

I have to look into fees however the negative shipping follows a fairly complex cost model that took long to "hack" into the system:
the deduction/addition of shipping depends on the number of bottles and destination country: 
![shippingmodel](https://user-images.githubusercontent.com/15838914/37166567-af92fdc2-22ff-11e8-96f7-8f39d720c57a.PNG)

it works just perfect except for the taxes.

**Comment by mikejolley** [comment]
Is this manual or some kind of plugin?

**Comment by LukasSteindl** [comment]
Used the shipping by rules (commercial) plugin to model this. but it can also be reproduced with standard flat shipping rate: 
![negative standard shipping](https://user-images.githubusercontent.com/15838914/37209426-8c6d42de-23a5-11e8-98d7-24e0c393d61d.PNG)

**Comment by mikejolley** [comment]
Ok, recommend against that in this case. There is no way to correctly remove taxes when you do this because it won't know what product is getting what costs removed, and what taxes should be reduced. You should look into the above options or do something custom.

So as not to break existing sites we won't be implementing a check or negative shipping - but note it is not supported officially. I am however adding a todo in the source to add the check in 4.0.

**Comment by mikejolley** [comment]
Thats unfortunate but thats the nature of using "hacks" - they are not suported.

**Comment by stickypages** [comment]
Hi Lukas, 
We are in the same industry, Wine, we too are having this same issue. 

We have discount for customers who pick-up. And for reporting purposes, we need to show the tax discounted too. So we show shipping of (-$15), taxes (-$1) etc... But if we "recalculate" it poses issue too.
