### ISSUE TITLE
WooCommerce appending AggregateRating if the reviews system is disabled

### ISSUE THREAD

**Issue by hxii** [woocommerce/woocommerce#19294]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a native review to a product.
2. Disable reviews through WooCommerce (WooCommerce -> Settings -> Products ->Enable reviews).
3. Navigate to the product page and inspect the structured data.
3. AggregateRating still shows up under structured data even though product essentially does not have reviews.

## Expected/actual behavior

The expected behavior is to not append aggregateRating if the reviews system is disabled.
This collides when using other review systems that report different values of reviewCount and ratingValue than WooCommerce.

## Proposed fix
In `class-wc-structured-data.php` on line #257 add an AND condition to check if the reviews system is enabled:
```php
		if ( $product->get_review_count() && ('yes' === get_option( 'woocommerce_enable_reviews', 'yes' )) ) {
			$markup['aggregateRating'] = array(
				'@type'       => 'AggregateRating',
				'ratingValue' => $product->get_average_rating(),
				'reviewCount' => $product->get_review_count(),
			);
		}
```

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment
<details>
### WordPress Environment ###

Home URL: http://127.0.0.1/wordpress
Site URL: http://127.0.0.1/wordpress
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
</details>

**Comment by hxii** [comment]
I assume `woocommerce_enable_reviews` disables certain hooks where 3rd party reviews systems don't appear either of it's set to no/false.

In which case, `woocommerce_enable_review_rating` can be used instead of `woocommerce_enable_reviews` i.e:
```php
if ( $product->get_review_count() && ('yes' === get_option( 'woocommerce_enable_review_rating', 'yes' )) ) {
```

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19310
