### ISSUE TITLE
WooCommerce did not remove all data on uninstall.

### ISSUE THREAD

**Issue by ve3** [woocommerce/woocommerce#19309]
I was followed this instruction ( https://docs.woocommerce.com/document/installing-uninstalling-woocommerce/ ) to remove **<ins>all</ins>** data on uninstall WooCommerce but it did not really remove all data.

These are things left on the database:

1. `woocommerce_log`, `wc_download_log`, `wc_webhooks` tables are left behind.
2. inside `comments` table, there are a lot of reviews or comments left where `comment_agent` field is **WooCommerce**
3. inside `options` table, there are a lot of options where `option_name` field contain **widget_woocommerce_** prefix.
   1. There are rewrite rules left in `option_value` field where `option_name` is **rewrite_rules**. For example: `/wc-api(/(.*))`
   2. One option left but I'm not sure is it WooCommerce related. It is where `option_name` is **wc_ppec_version**.
4. inside `postmeta` table, there are `woocommerce_thumbnail`, `woocommerce_gallery_thumbnail` array keys where `meta_key` field is **_wp_attachment_metadata**.
5. inside `posts` table, those pages are already trashed. Good! But there are many records that contain WooCommerce data where `post_type` is **customize_changeset**. For example: `woocommerce_thumbnail_cropping`, `woocommerce_catalog_columns`, and more.
6. inside `usermeta` table. I'm not sure about this but there is WooCommerce value left where `meta_key` is **_woocommerce_persistent_cart_1**.

Please update uninstall code to clean them up. :-)

**Comment by mikejolley** [comment]
This has been updated recently to fix 1 and 6. https://github.com/woocommerce/woocommerce/blob/master/uninstall.php

All that needs looking at is:

- `widget_woocommerce_`
- `comment_agent`

As for the rest:
- Rewrite rules are out of scope. These are cleared by WP when you save permalink settings.
- _wp_attachment_metadata is out of scope; serialised data such as that cannot be cleared. it clears after thumbnails are regenerated.
- customize_changeset is out of scope. it's not our post type. It's customizer history.

**Comment by ve3** [comment]
For customize_changeset, I think the plugin should be able to remove that in case of someone mess up with customizer or.. have reset button in customizer to cleanup everything for WooCommerce in customizer.

**Comment by mikejolley** [comment]
`customize_changeset` is just a log of changes. Plugins shouldn't touch this.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19371
