### ISSUE TITLE
PayPal Refund Button Enabled when No API Credentials Exist

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce#19302]
Original Report: https://github.com/Automattic/wp-calypso/issues/21665

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
1. On a fresh install of WooCommerce, configure the PayPal payment gateway with *only* your PayPal email address, no api signature, username or password
2. Place an order using the PayPal payment method
3. Visit the order in wp-admin, and note the Refund via PayPal payment button is shown:

<img width="850" alt="refund-button-shown" src="https://user-images.githubusercontent.com/22080/37106639-2fbce342-21e7-11e8-8ca4-12a190413847.png">

4. Clicking on the refund via PayPal button results in a js `alert()` error being shown after the admin-ajax call fails:

<img width="557" alt="failed-no-transaction-id" src="https://user-images.githubusercontent.com/22080/37110464-d9e0cb4a-21f1-11e8-8014-b7a09ab97ff6.png">

_admin-ajax response_
<img width="728" alt="admin-ajax-response" src="https://user-images.githubusercontent.com/22080/37110474-e07c61bc-21f1-11e8-8ebb-129b8c87b8e0.png">

_admin-ajax-payload_
<img width="450" alt="admi-ajax-payload" src="https://user-images.githubusercontent.com/22080/37110491-e9379d12-21f1-11e8-8a0d-4afbee35238f.png">

## Expected/actual behavior
If there are no API credentials present for PayPal - which are required in order to process an API-based refund, it seems we should only show the manual refund option.

## Isolating the problem

Much like the logic in Store on WordPress.com, the display of the PayPal refund button is [currently set to look](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-order-items.php#L296) at `method_supports` for `refunds` on the payment gateway - which for PayPal is truthy. But it seems we should check for the presence of the API credentials and determine if `refunds` are truly supported.

One proposed fix I had for Store was to modify the payment_gateways API response for PayPal and to only have `refunds` in `method_supports` if API credentials are present: https://github.com/Automattic/wc-calypso-bridge/pull/39

Alternatively, @justinshreve thinks it is still valid to have `method_supports` include `refunds`, but maybe we should have a new class level attribute for `methods_enabled` which can look at things like API keys to ensure the current gateway supports the enabled method.

I figured opening an issue here could add to that discussion and determine the best fix.

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment
```
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
```

**Comment by mikejolley** [comment]
`Gateways should override this to declare support (or lack of support) for a feature.`

I think it's fair to allow gateways to define support correctly. A feature can only be supported if it's configured in a way to do so.

So in this case, I'd be in favour of extending `supports` in PayPal and returning true/false based on the presence of those options.

**Comment by mikejolley** [comment]
@timmyc Opened up https://github.com/woocommerce/woocommerce/pull/19380 for feedback. Cheers.

**Comment by claudiosanches** [comment]
@mikejolley @timmyc no that PR will not avoid the error reported here, since the error is displayed when the order there is no transaction ID.
I agree that we should include checks for API keys.

**Comment by mikejolley** [comment]
@claudiosanches is correct. This protects against the error "Security header is not valid".

Missing transaction ID however is not something this protects against and is a legitimate error notice if the order has no TX ID. It seems we should also hide that button if no TX ID is present. Will revise the PR.
