### ISSUE TITLE
Facebook Pixel not Firing Correctly

### ISSUE THREAD

**Issue by paultancredi** [woocommerce/woocommerce#19303]
Yesterday we went through Facebook for Woocommerce to upload the Facebook Pixel and Dynamic Product Catalog. For the first 10 hours it was firing correctly and reporting back to facebook. Now the pixel isn't firing at all on any of the pages. (Page View, view content, add to cart, etc...) I checked out a few other wordpress sites utilizing Facebook for WooCommerce and their having the same issue.

![screen shot 2018-03-07 at 1 20 19 pm](https://user-images.githubusercontent.com/37158196/37116081-5577ca16-220a-11e8-8e60-ed95bdc10350.png)

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by GlennMartin1** [comment]
Support for this is handled through Facebook.

https://www.facebook.com/business/help/900699293402826

**Comment by paultancredi** [comment]
In this specific pixel problem, Facebook support says it is a Woocommerce issue.

https://www.facebook.com/business/help/community/question/?id=10155557617689036

**Comment by mikejolley** [comment]
For this product https://woocommerce.com/products/facebook/ Go via the helpdesk https://woocommerce.com/contact-us/

GitHub is not for extension support, only core.

Thanks
