### ISSUE TITLE
Missing semicolon in declaring woocommerce support wiki page

### ISSUE THREAD

**Issue by newsapkota** [woocommerce/woocommerce#19312]
Hi @woocommerce team,
While going through wiki page of "/woocommerce/wiki/Declaring-WooCommerce-support-in-themes", I found semicolon was missing in action hook in #usage-with-settings section.

So, will you please edit the wiki to add semicolon. Thank you.

**Comment by mikejolley** [comment]
Thanks

**Comment by newsapkota** [comment]
Thank you @mikejolley for updated the wiki page.
