### ISSUE TITLE
Sort Products By Stock Question

### ISSUE THREAD

**Issue by B1aZer** [woocommerce/woocommerce#19316]
Hi,

I'm trying to sort products in the shop by custom order using 'woocommerce_get_catalog_ordering_args' filter. I can't seem to figure out how to order by stock quantity.

`		$args['orderby'] = 'meta_value';
		$args['order'] = 'ASC';
		$args['meta_key'] = '_stock_status';
		$args['meta_value'] = 'instock';
`

Works, but

 `$args['orderby'] = 'meta_value_num';
		$args['order'] = 'ASC';
		$args['meta_key'] = '_stock_quantitiy';
`

Does not.

**Comment by WPprodigy** [comment]
`_stock_quantitiy` isn't a valid meta key.

**Comment by B1aZer** [comment]
Figured it out:
`		$args['orderby'] = 'meta_value';
		$args['order'] = 'DESC';
		$args['meta_key'] = '_stock';
`
Works. Thanks.
