### ISSUE TITLE
Checkout doesn't work for UAE customers

### ISSUE THREAD

**Issue by ashishcodeswell** [woocommerce/woocommerce#19328]
Hi Mike,

I have built an eCommerce site on WooCommerce for a client last year. It is working fine however, there is an issue specifically for United Arab Emirates customers as when they try to checkout they can't proceed or click continue button. Since, there are no postal codes, I thought it was the issue so, I tried to remove validation of Postal Code using a hook i.e. 

add_filter( 'woocommerce_checkout_fields' , 'custom_override_checkout_fields' );
function custom_override_checkout_fields( $fields ) {
    $fields['billing']['billing_postcode']['required'] = false;
    $fields['shipping']['shipping_postcode']['required'] = false;
    return $fields;
}

Above hook didn't made any changes so I added another hook to deregister wc-address-i18n script using this: 

add_action('wp_enqueue_scripts', 'override_woo_frontend_scripts');
function override_woo_frontend_scripts() {
    wp_deregister_script('wc-address-i18n');
}

It worked but it raised another issue i.e. " Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements. "

Now, the very important thing when I selected another country without Post Code i.e. Republic of Ireland, it showed me a Postal Code field (optional) and I am able to complete the order. It's completely vice-versa when I select UAE as country. 

So, my question is when I select United Arab Emirates as  country, why it removes the Postal Code field? If the field is available for UAE as well then I think I can easily complete the checkout process. 

The fix could be if we can display the Postal Code field under checkout - billing form for UAE customers. Is there a way to enable a Postal Code? 

Is that something you can help me with? I would appreciate your response in this regards. 

Best,
Ashish

**Comment by mikejolley** [comment]
I don't see an issue I'm afraid. On a clean install with no plugins:

- I can checkout with a UAE address without postcode. Postcode is not a required or visible field for UAE so no validation occurs.
- Example UAE address has no postcode so we're correct to hide it https://www.unicef.org/infobycountry/uae_contact.html

The no payment methods indicate you may have a plugin conditionally loading gateways based on addresses. This is not core.
