### ISSUE TITLE
Add Filter to woocommerce_output_product_categories() Default Arguments

### ISSUE THREAD

**Issue by spencerfinnell** [woocommerce/woocommerce#19323]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Try to adjust the `before` and `after` args on category output without a custom template file.

## Expected/actual behavior

A filter in place to be able to change these without overwriting a template file. A filter on https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L1951 would allow the `before` and `after` arguments to be utilized. 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by claudiulodro** [comment]
That's a good idea. Want to open a PR? :)

**Comment by nishitlangaliya** [comment]
@claudiulodro ,

I have added two filter to woocommerce_output_product_categories function. Let me know if any changes required.

Thanks.

**Comment by claudiulodro** [comment]
See #19363
