### ISSUE TITLE
Internet crashing a mistake

### ISSUE THREAD

**Issue by sofsoaps** [woocommerce/woocommerce#19327]
So I just started working on a project. My internet is fine but it keeps disconnecting for some reason and my variations that I put in aren't showing up. I can't launch a website that doesn't work.
![screenshot 9](https://user-images.githubusercontent.com/37198275/37184618-40061e20-230a-11e8-92d3-fd7bf116cd74.png)
![screenshot 10](https://user-images.githubusercontent.com/37198275/37184619-4017c01c-230a-11e8-9866-f62a8f0b4f0c.png)
![screenshot 11](https://user-images.githubusercontent.com/37198275/37184620-402f38dc-230a-11e8-9059-8dc8c60ad61c.png)

**Comment by WPprodigy** [comment]
Are they never loading?

This might be a plugin/theme conflict more-so than internet problems. Follow this guide to maybe find the culprit: https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4

**Comment by sofsoaps** [comment]
This has come up now

**Comment by kloon** [comment]
It goes without saying that if your site is hosted on a remote server that you will definitely need internet access to make changes to that site. Unfortunately we cannot control your internet connection and an active one is needed to save changes.

Only suggestion I can make is try again when your connection is active and stable. Alternatively you can make use of the import/export functionality and setup a local site where you setup all your products and then do an import once on the live site to apply the changes there.

**Comment by sofsoaps** [comment]
My internet is stable and fine it’s the actual site that’s not working

**Comment by sofsoaps** [comment]
Where is the import/export feature?
