### ISSUE TITLE
THEME VERSIONE NOT WORKING WITH WOOCOMMERCE

### ISSUE THREAD

**Issue by cristinavittoria** [woocommerce/woocommerce#19336]
Dear all
I'm writing because one of the web site that I m working on it is not working because of some issue from woocommerce and luxi theme. 
Actually could be also last Visual Composer update. 
Wen I go in a specific page to change any botton to action or product, the wordpress site crash, not only the dashboard bot all the web site. It seems from the hostin provider data that some plugin is using all the space and mamory, so the web site seems overquota, wich is not actally. 
But the web site cresh only wen I go in some pages to make any changes. 
Luxi Theme vs Woocommerce updates plugin , here the report : 
luxi/woocommerce/archive-product.php version 2.0.0 it is old. the updated version is 3.3.0, 
luxi/woocommerce/content-product.php version 2.4.0 it is old. the updated version it is 3.0.0, 
luxi/woocommerce/single-product/related.php version 1.6.4 it is old. the updated version is 3.0.0, 
luxi/woocommerce/single-product/tabs/additional-information.php version 2.0.0 it is old. the updated version is 3.0.0, 
luxi/woocommerce/single-product/tabs/description.php, 
luxi/woocommerce/single-product/tabs/tabs.php
MOREOVER 
The WP Backery Visual Composer shall be updated but wen I try to do that, a message say that is not possibile for some issue with the different version of VISUAL COMPOSER and theme or WOOCOMMERCE. 
I alredy picked out all the last plugin and reinstalled one by one to check wich one was the problem, it seems that is Visual Composter and Luxi Theme. 
I tryed all the php version from the 4 to the 7.something and I finally found the working one. 
How could I fix this issue? 
Andy advice are welcome!!!  
Thank you in advance !!!!

**Comment by mikeyarce** [comment]
Please go to the WordPress.org Support Forums to get help with a support issue:
https://wordpress.org/support/plugin/woocommerce

**Comment by cristinavittoria** [comment]
thanks!!!!

Vittoria

phone
IT +39 3392602756

Cristina Vittoria Marazzi
P.IVA: 00994530145

www.cristinavittoriamarazzi.com

Please consider the environment before printing this email


This email and any attachment are confidential. For this reason if
you receive them in error, please do not disclose the contents to anyone,
but notify the sender by return email. Please delete this email and
any attachment from your system too.
