### ISSUE TITLE
Can't create a new account on my-account page

### ISSUE THREAD

**Issue by alexscro** [woocommerce/woocommerce#19332]
Hey guys!

We are experiencing troubles with our client's shop page. It is not possible anymore to create a customer account on the my-account page. 

Find attached the URL: [Shop](https://bergsteiger.store)

WooCommerce Version 3.3.3 
The following plugins are installed: 
![screen shot 2018-03-09 at 10 34 34](https://user-images.githubusercontent.com/36740862/37200600-84e7685c-2385-11e8-84c6-987e5de07573.png)

I also installed WC Password Strength Settings plugin to reduce number of required chars in the password, however it doesn't work with long ones either.

Steps to reproduce:

1. GO to [My Account Page of Shop](https://bergsteiger.store/my-account/)
2. Type in credentials
3. Submit

->The page will just reload without an account to be created.

Any advice or tips would mean a lot, if information is missing please let me know.

All the best,
Alex

**Comment by mikejolley** [comment]
Duplicate https://github.com/woocommerce/woocommerce/issues/19329
