### ISSUE TITLE
"Order" field is missing from Quick Edit.

### ISSUE THREAD

**Issue by gspitzer** [woocommerce/woocommerce#19348]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. See WooCommerce >> Products >> product >> Quick Edit in **WC 2.6.14** - the "Order" field is there:

![https://cloudup.com/cvd4ANTPa-0](https://cloudup.com/cvd4ANTPa-0+)

Image Link: https://cloudup.com/cvd4ANTPa-0

2. See WooCommerce >> Products >> product >> Quick Edit in **any version released after WC 2.6.14** - the "Order" field is missing:

![https://cloudup.com/cKIXxZ8xKBP](https://cloudup.com/cKIXxZ8xKBP+)

Image Link: https://cloudup.com/cKIXxZ8xKBP

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
WordPress adds this for hierarchal post types only (pages). We have no plans to bring this back manually for products. You can edit via the product page or use drag and drop on the list page. You can also set them in bulk using the CSV importer.

The feature itself may be [unsupported in future redesigns.](https://github.com/woocommerce/woocommerce/issues/13072)

Thanks
