### ISSUE TITLE
woocommerce not link to products download

### ISSUE THREAD

**Issue by Branca** [woocommerce/woocommerce#19340]
when upgrading to woocommerce 3.3.3 and for wp 4.9.4 all virtual / download products hosted on the server itself by the item> Media no longer send the download link to the client nor even register that product as a download on the client's dashboard . How can I solve this?

**Comment by mikejolley** [comment]
Sounds like your orders are not going processing/complete which could be an issue with your gateway. But this issue lacks details so it's hard to know for sure.

The details on the new issue page are needed.

> Please be as descriptive as possible; issues lacking the below details, or for any other reason than to report a bug, may be closed without action
