### ISSUE TITLE
Duplicate non-unique id #_wpnonce

### ISSUE THREAD

**Issue by vlaskiz** [woocommerce/woocommerce#19345]
## Prerequisites

[x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
[x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
[x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Put both [woocommerce_cart] and [woocommerce_checkout] shortcodes on a same page.
2. Add a product to cart.
3. Visit cart/checkout page while being logged in on latest chrome browser version.

## Expected/actual behavior

2/4 inputs with duplicate _wpnonce ID. Should be unique.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://woocommerce-143086-452732.cloudwaysapps.com
Site URL: http://woocommerce-143086-452732.cloudwaysapps.com
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.13-1+0~20180105151310.14+jessie~1.gbp1086fa
PHP Post Max Size: 50 MB
PHP Time Limit: 90
PHP Max Input Vars: 8000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.95MB
Database Data Size: 1.10MB
Database Index Size: 0.85MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.47MB + Index: 0.02MB
wp_postmeta: Data: 0.08MB + Index: 0.03MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 16
customize_changeset: 1
page: 7
post: 3
product: 12
revision: 4

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6 - /shop
Cart: #8 - /checkout
Checkout: #8 - /checkout
My account: #9 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by WPprodigy** [comment]
I've noticed a couple of other scenarios where you can get this new chrome notice.

Probably need to work on naming all nonce values, on the frontend at least. A bit scared about BC with template overrides though.

**Comment by mikejolley** [comment]
We have fixed the common cases e.g. just using checkout https://github.com/woocommerce/woocommerce/issues/18509

I'm also not keen on working around this issue due to the impact it will have on themes overriding templates - this would break checkout/cart updates which is more serious than a warning on console.

For a more general fix, WordPress needs a core patch. 
https://core.trac.wordpress.org/ticket/23165

@WPprodigy maybe we can help push a resolution to that in the dev chats. The patch there needs a refresh. Would rather that than changing core. cart and checkout on same page isn't really a well 'supported' scenario anyway.

**Comment by vlaskiz** [comment]
@mikejolley Now I am not saying this is best solution, but considering that wp_nonce_field() is used, specifying second parameter would be enough.

Doing that in template name might be risky, so maybe wrap it in to your own function and use that one?

Once WordPress releases core patch (which I doubt would happen soon enough, unless shilled hard), things could be adjusted.

**Comment by mikejolley** [comment]
@vlaskiz the problem is there may be too possible nonces in that case depending on template version. Thats a serious issue.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19387
