### ISSUE TITLE
Purchase not working

### ISSUE THREAD

**Issue by sofsoaps** [woocommerce/woocommerce#19354]
I tried to buy something from my website to see if it would work
![screenshot 15](https://user-images.githubusercontent.com/37198275/37254494-077c69f8-2515-11e8-986b-2a838d5f8672.png)
Also I tried to get rid of international shipping but it won't let me. How do I fix these things?
![screenshot 16](https://user-images.githubusercontent.com/37198275/37254501-1a1cd1b0-2515-11e8-8587-40d915e10333.png)

**Comment by claudiosanches** [comment]
It's missing steps to reproduce this issue. Those requirements from the issue template is important in order to debug and check if is a WooCommerce issue.
From the pictures you posted here sounds like is missing some page or some plugin is causing 404 error.

**Comment by sofsoaps** [comment]
why did you close this you didn't even help me
