### ISSUE TITLE
Unix path not supported for digital content Product page and PDF watermark extension

### ISSUE THREAD

**Issue by mbdash** [woocommerce/woocommerce#19355]
REQUEST: 
Unix path to be supported for digital content Product page and PDF watermark extension

OBJECTIVE:
Increased security by hiding files where only php can access them, above webroot by using UNIX path.

KNOWN: 
Plugin already obfuscate the direct dl link. 
Woocomerce already deploy .htaccess [deny all] 
but the **link is visible but returns a 404**. 

BUG:
**Unix path not supported by plugin and extension PDF watermark.**
To reduce the bug to the most simple repro conditions, 
the bug can be broken in 2 as fixing Bug1 *might fix Bug2

BUG 1:

1. Using unix path instead of url in woocomerce will result in plugin failure. 

REPRO BUG 1: 

1. leave file in default folder,
2. change product path to unix: 
ie change: http://www.MYWEBSITE.com/wpcontent/uploads/woocommerce_uploads/2018/02/MYFILE.pdf
 for ( == ) 
/public_html/MYWEBSITE.com/wpcontent/uploads/woocommerce_uploads/2018/02/MYFILE.pdf 

ERROR BUG 1: 
`The downloadable file [...] cannot be used as it does not exist on the server. `

BUG 2: 
_Using PDF watermark extension_
1. Moving files above webroot, inevitably using a unix path, fails with PDF watermark extension 

REPRO BUG 2: 

1. create a folder above webroot. (will therefore only be accessible by php) 
2. Ensure folder ownership and permissions matches woocomerce default folder. 
3. copy/move the pdf from woocomerce default folder to the new private folder. 
4. ensure file ownership and permissions matches woocomerce default file settings. 
5. change product path to unix

ERROR BUG 2: 
```
The following Downloadable Files are not compatible with PDF Watermarker. 
You should disable watermarking on this product or choose different files. 
MYFILE_priv - /home/WEBROOT/private_digital_store/MYWEBSITE.com/MYFILE.pdf
```

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. create a folder above webroot. (will therefore only be accessible by php) 
2. Ensure folder ownership and permissions matches woocomerce default folder. 
3. copy/move the pdf from woocomerce default folder to the new private folder. 
4. ensure file ownership and permissions matches woocomerce default file settings. 
5. change product path to unix

## Expected/actual behavior

When I set a PDF downloadable product path to a UNIX path,
above webroot,
 
I expect:
Woocommerce will not return an error 
and 
PDF watermark is able to add a watermark to the PDF without error

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
I'm cc'ing @bor0 for visibility, but you should **not** be submitting issues here regarding premium extensions. Use the helpdesk https://woocommerce.com/contact-us/

> Usage questions can also be directed to the public support forum here: https://wordpress.org/support/plugin/woocommerce, unless this is a question about a premium extension in which case you should use the helpdesk.

As such this will be closed.

Thanks

**Comment by mbdash** [comment]
Hi
I understand.
Help desk asked me to submit the bug to GitHub...

Because the Unix support for the plug-in might also fix the extension
problem I guess.

Maybe instead of closing the bug I could remove references to the extension
and limit it to Unix path support in woocommerce.

Thank you,
-Matt

**Comment by mikejolley** [comment]
WC core supports relative paths. From ABSPATH I believe.

**Comment by mbdash** [comment]
Please test before closing.

read part 1 of the bug description:

BUG 1:

Using unix path instead of url in woocomerce will result in plugin failure.
REPRO BUG 1:

leave file in default folder,
change product path to unix:
ie change: http://www.MYWEBSITE.com/wpcontent/uploads/woocommerce_uploads/2018/02/MYFILE.pdf
for ( == )
/public_html/MYWEBSITE.com/wpcontent/uploads/woocommerce_uploads/2018/02/MYFILE.pdf
ERROR BUG 1:
The downloadable file [...] cannot be used as it does not exist on the server.
