### ISSUE TITLE
Checkout Select2/SelectWoo not showing blank option state/county dropdown

### ISSUE THREAD

**Issue by colapsnux** [woocommerce/woocommerce#19365]
Seems like on the checkout page the **blank option** is not showing in the select state/county dropdown.
As far I know, in the previous WC version it showed.
I tried to dequeue SelectWoo and it works without it, **select an option...** now appear.. 
Also, I tried to dequeue SelectWoo and enqueue the original select2 plugin, same here doesn't work.
So can you please repair that, because I think that i'm not the only one who don't need a selected value by default, instead let the customer choice his state/county by him self.

**Comment by mikejolley** [comment]
The customer can still select the state themselves; there is just no blank option. I don't see why this needs to match an older version. If you don't like the new behavior you can dequeue the selectwoo script - we shouldn't change this back without user testing, and that won't be done until https://github.com/woocommerce/woocommerce/issues/10672 is worked on by the design team.

Thanks
