### ISSUE TITLE
After woocommerce updating search result not showing as price low to high.

### ISSUE THREAD

**Issue by sarun007** [woocommerce/woocommerce#19362]
On my client website i updated the woocommerce form 3.2.6 into 3.3.3 After the updation my search result page showing product result is not sorting as price low to high.I just rolled back my woocommerce into 3.2.6 at that time search result page showing products are in low to high.How i solve this problem in woocommerce 3.3.3 version.

`
### WordPress Environment ###

Home URL: https://orderprintercartridges.com
Site URL: https://orderprintercartridges.com
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.27
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wpn2_
Total Database Size: 183.14MB
Database Data Size: 99.72MB
Database Index Size: 83.42MB
wpn2_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB
wpn2_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpn2_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpn2_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpn2_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB
wpn2_woocommerce_order_itemmeta: Data: 0.22MB + Index: 0.22MB
wpn2_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpn2_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wpn2_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpn2_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wpn2_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpn2_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpn2_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpn2_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpn2_abj404_logsv2: Data: 2.17MB + Index: 1.08MB
wpn2_abj404_lookup: Data: 0.00MB + Index: 0.00MB
wpn2_abj404_redirects: Data: 0.13MB + Index: 0.23MB
wpn2_ac_abandoned_cart_history_lite: Data: 0.06MB + Index: 0.00MB
wpn2_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB
wpn2_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wpn2_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB
wpn2_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB
wpn2_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB
wpn2_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB
wpn2_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB
wpn2_affiliate_wp_payouts: Data: 0.02MB + Index: 0.02MB
wpn2_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB
wpn2_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB
wpn2_affiliate_wp_visits: Data: 0.02MB + Index: 0.02MB
wpn2_commentmeta: Data: 0.02MB + Index: 0.03MB
wpn2_comments: Data: 0.13MB + Index: 0.09MB
wpn2_email_log: Data: 3.52MB + Index: 0.00MB
wpn2_links: Data: 0.02MB + Index: 0.02MB
wpn2_nf_objectmeta: Data: 0.02MB + Index: 0.00MB
wpn2_nf_objects: Data: 0.02MB + Index: 0.00MB
wpn2_nf_relationships: Data: 0.02MB + Index: 0.00MB
wpn2_ninja_forms_fav_fields: Data: 0.05MB + Index: 0.00MB
wpn2_ninja_forms_fields: Data: 0.06MB + Index: 0.00MB
wpn2_options: Data: 9.48MB + Index: 3.50MB
wpn2_pantheon_sessions: Data: 0.02MB + Index: 0.03MB
wpn2_pmxe_exports: Data: 0.13MB + Index: 0.00MB
wpn2_pmxe_posts: Data: 1.52MB + Index: 0.00MB
wpn2_pmxe_templates: Data: 0.05MB + Index: 0.00MB
wpn2_pmxi_files: Data: 0.06MB + Index: 0.00MB
wpn2_pmxi_history: Data: 0.05MB + Index: 0.00MB
wpn2_pmxi_imports: Data: 0.31MB + Index: 0.00MB
wpn2_pmxi_posts: Data: 1.52MB + Index: 0.00MB
wpn2_pmxi_templates: Data: 0.25MB + Index: 0.00MB
wpn2_postmeta: Data: 32.56MB + Index: 19.06MB
wpn2_posts: Data: 5.52MB + Index: 3.19MB
wpn2_relevanssi: Data: 14.56MB + Index: 25.13MB
wpn2_relevanssi_log: Data: 0.42MB + Index: 0.00MB
wpn2_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB
wpn2_revslider_css: Data: 0.14MB + Index: 0.00MB
wpn2_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wpn2_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wpn2_revslider_sliders: Data: 0.05MB + Index: 0.00MB
wpn2_revslider_slides: Data: 0.25MB + Index: 0.00MB
wpn2_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wpn2_sm_advanced_search_temp: Data: 0.02MB + Index: 0.00MB
wpn2_social_users: Data: 0.02MB + Index: 0.02MB
wpn2_taxonomymeta: Data: 0.02MB + Index: 0.03MB
wpn2_termmeta: Data: 7.52MB + Index: 9.03MB
wpn2_terms: Data: 5.52MB + Index: 9.03MB
wpn2_term_relationships: Data: 4.52MB + Index: 4.52MB
wpn2_term_taxonomy: Data: 6.52MB + Index: 7.03MB
wpn2_usermeta: Data: 0.14MB + Index: 0.16MB
wpn2_users: Data: 0.02MB + Index: 0.05MB
wpn2_wcsp_group_category_pricing_mapping: Data: 0.02MB + Index: 0.02MB
wpn2_wcsp_role_category_pricing_mapping: Data: 0.02MB + Index: 0.02MB
wpn2_wcsp_user_category_pricing_mapping: Data: 0.02MB + Index: 0.05MB
wpn2_wc_cancel_orders: Data: 0.02MB + Index: 0.00MB
wpn2_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpn2_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpn2_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB
wpn2_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB
wpn2_wplc_chat_msgs: Data: 0.02MB + Index: 0.00MB
wpn2_wplc_chat_sessions: Data: 0.02MB + Index: 0.00MB
wpn2_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB
wpn2_wplc_webhooks: Data: 0.02MB + Index: 0.00MB
wpn2_wusp_group_product_price_mapping: Data: 0.02MB + Index: 0.02MB
wpn2_wusp_pricing_mapping: Data: 0.02MB + Index: 0.02MB
wpn2_wusp_role_pricing_mapping: Data: 0.02MB + Index: 0.02MB
wpn2_wusp_rules: Data: 0.02MB + Index: 0.03MB
wpn2_wusp_subrules: Data: 0.02MB + Index: 0.08MB
wpn2_wusp_user_mapping: Data: 0.02MB + Index: 0.02MB
wpn2_wusp_user_pricing_mapping: Data: 0.02MB + Index: 0.05MB
wpn2_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wpn2_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wpn2_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wpn2_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB

### Post Type Counts ###

attachment: 7588
custom_css: 1
nav_menu_item: 14
nf_sub: 13
page: 33
post: 4
product: 2483
shop_coupon: 14
shop_order: 86
shop_order_refund: 3
wc_zapier_feed: 2
wishlist: 4
ywar_reviews: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

ManageWP - Worker: by ManageWP – 4.5.0
404 Solution: by Aaron J – 2.6.1
WooCommerce Invoice Payment Gateway: by David Paulsson – 2.0 – Not tested with the active version of WooCommerce
ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 2.0.1

Advanced Custom Fields: by Elliot Condon – 4.4.12
AffiliateWP - Lifetime Commissions: by Pippin Williamson and Andrew Munro – 1.2.5
AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.1.9
AffiliateWP: by AffiliateWP
LLC – 2.1.8

AffiliateWP - Custom Affiliate Slugs: by Pippin Williamson and Andrew Munro – 1.0.1
Custom Related Products for WooCommerce: by Scott Nelle – 1.3 – Not tested with the active version of WooCommerce
Customer Specific Pricing for WooCommerce: by WisdmLabs – 4.1.0 – Not tested with the active version of WooCommerce
Email Log: by Sudar – 2.2.5
Gmail SMTP: by naa986 – 1.1.7
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.2.3.1
Imagify: by WP Media – 1.6.14.2
Insert Headers and Footers: by WPBeginner – 1.4.2
Ninja Forms: by The WP Ninjas – 3.2.16
Optimus: by KeyCDN – 1.4.9
Pure Chat: by Pure Chat
Inc. – 2.0

Smart Manager: by StoreApps – 3.16.1
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 1.5.4 – Not tested with the active version of WooCommerce
Taxonomy Metadata: by mitcho (Michael Yoshitaka Erlewine)
sirzooro – 0.5

Temporary Login Without Password: by StoreApps – 1.5.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.14.4

Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 4.7
WooCommerce Dropshipping: by WooCommerce – 1.1.0 – 1.2.1 is available – Not tested with the active version of WooCommerce
WooCommerce FreshBooks: by WooThemes / SkyVerge – 3.7.0 – 3.11.1 is available – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway Custom Plugin: by WooCommerce – 10.2.3 – Not tested with the active version of WooCommerce
WooCommerce AdWords Conversion Tracking: by Wolf+Bär Agency – 1.4.7 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce MSRP Pricing: by Lee Willis – 2.0.2 – 2.9.5 is available – Not tested with the active version of WooCommerce
WooCommerce Role Based Methods: by WPBackOffice – 2.0.8 – 2.3.6 is available – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooThemes – 1.5.0 – 1.6.10 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.3
Yoast SEO Premium: by Team Yoast – 5.8
PayPal Buy Now Button: by Scott Paterson – 1.7.2
WP Migrate DB: by Delicious Brains – 1.0.2
WP Rocket: by WP Media – 2.10.12
WP Rollback: by WordImpress – 1.5
WPFront User Role Editor: by Syam Mohan – 2.14.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Order Printer Cartridges
Version: 3.4.0g
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome Customize Theme
Parent Theme Version: 3.4.0
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php version 3.1.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.3.0
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php version 3.2.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/global/wrapper-end.php version 1.6.4 is out of date. The core version is 3.3.0
flatsome/woocommerce/global/wrapper-start.php version 1.6.4 is out of date. The core version is 3.3.0
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/loop/pagination.php version 2.2.2 is out of date. The core version is 3.3.1
flatsome/woocommerce/loop/result-count.php version 3.0.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php version 3.2.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php version 1.6.4 is out of date. The core version is 3.3.0
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php version 1.6.4 is out of date. The core version is 3.3.0
flatsome/woocommerce/product-searchform.php version 2.5.0 is out of date. The core version is 3.3.0
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php version 3.1.0 is out of date. The core version is 3.3.2
flatsome/woocommerce/single-product/product-thumbnails.php version 3.1.0 is out of date. The core version is 3.3.2
order-printer-cartridges/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php version 1.6.4 is out of date. The core version is 3.3.0
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
order-printer-cartridges/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
order-printer-cartridges/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`

**Comment by sarun007** [comment]
There is no conflict in theme i tried in default wordpress theme in my staging site then i have faced same problem.You check on this site on by click this url https://orderprintercartridges.com/?s=tn336&post_type=product or you can search anything on this site then the search result page showing product is not as low to high.I think this is bug because its working before woocommerce 3.2.6

**Comment by mikejolley** [comment]
It works when you select from dropdown. The default sorting is relevance.

**Comment by sarun007** [comment]
But in woocommerce 3.2.6 its working perfectly i dont want to select that drop down by default it showing product search result as low to high. But in woocommerce 3.3.3 version default search result showing as random. Even i selected sort by price (asc) in Appearance > Customize > WooCommerce > Product Catalog section in woo 3.3.3 the search result page showing result sorted by random.  please see attached screen shot

![search results for order printer cartridges](https://user-images.githubusercontent.com/20927046/37328815-7cfb5c86-26c1-11e8-986c-9bfc020cda39.png)

**Comment by mikejolley** [comment]
Right - I'm betting the template has been changed to not select the current sort mode which is `relevance` by default. 

flatsome/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.3.0

**Comment by sarun007** [comment]
@mikejolley mikejolley  Then after woocommerce 3.3.3 the search page result is showing by default relevance is that correct ?? Then Why search page showing drop down showing sort by low to high on that drop down area?? please check that attached image.It was confusing for users.

I also tested with default wordpress theme then same issue is happening the drop down box showing sort by price low to high but result page product are showing random.You can check the attached image.
![order printer](https://user-images.githubusercontent.com/20927046/37336027-24342726-26d6-11e8-814b-3c9ae1c079bf.png)

**Comment by mikejolley** [comment]
> I also tested with default wordpress theme then same issue is happening the drop down box showing sort by price low to high but result page product are showing random.You can check the attached image.

Including this at the beginning would have been helpful :)

**Comment by sarun007** [comment]
@mikejolley The issue is with woocommerce right ? how i solve the this issue??
