### ISSUE TITLE
Offset argument to WooCommerce Shortcodes

### ISSUE THREAD

**Issue by Amoditer** [woocommerce/woocommerce#19364]
Hello,

What I want to ask is a new argument into the WooCommerce shortcodes. Posts are using this, but WooCommerce is not, this argument is the “offset”. We made some functions to add that argument to some shortcode, but it would be better if it can be in the basic part of the WooCommerce shortcodes like "per_page" or "order" or "columns", and we can use the whole shortcodes variations, not just these 3 ones what I attached.

Is there any chance that you can integrate it in the nearest future? At the WooCommerce support page, their said "You might want to open an issue on Github for that. That's where the developers are likely to see your suggestions.".

Thank you for your answer.
Best Regards

Here’re the functions what we use:

//offset to sale product
function oto_sale_products_func( $atts ) {
    $atts = shortcode_atts( array(
        'per_page' => '12',
        'columns'  => '4',
        'orderby'  => 'date',
        'order'    => 'desc',
        'offset'   => 0,
        'category' => '', // Slugs
        'operator' => 'IN' // Possible values are 'IN', 'NOT IN', 'AND'.
    ), $atts, 'sale_products' );
    
	$columns = absint( $atts['columns'] );
	wc_set_loop_prop( 'columns', $columns ); 
		
    ob_start();
 
    $query_args = array(
        'posts_per_page' => $atts['per_page'],
        'orderby'        => $atts['orderby'],
        'order'          => $atts['order'],
        'offset'         => $atts['offset'],
        'no_found_rows'  => 1,
        'post_status'    => 'publish',
        'post_type'      => 'product',
        'meta_query'     => WC()->query->get_meta_query(),
        'post__in'       => array_merge( array( 0 ), wc_get_product_ids_on_sale() )
    );
    ?>
    <ul class="products">
        <?php
            $loop = new WP_Query( $query_args );
            if ( $loop->have_posts() ) {
                while ( $loop->have_posts() ) : $loop->the_post();
                    wc_get_template_part( 'content', 'product' );
                endwhile;
            } else {
                echo __( 'No products found' );
            }
            wp_reset_postdata();
        ?>
    </ul>
    <?php
 
    return '<div class="woocommerce columns-' . $columns . '">' . ob_get_clean() . '</div>';
 
}
 
add_shortcode( 'oto_sale_products', 'oto_sale_products_func' );

//offset to featured product
function oto_featured_products_func( $atts ) {
    $atts = shortcode_atts( array(
        'per_page' => '12',
        'columns'  => '4',
        'orderby'  => 'date',
        'order'    => 'desc',
        'offset'   => 0,
        'category' => '', // Slugs
        'operator' => 'IN' // Possible values are 'IN', 'NOT IN', 'AND'.
    ), $atts, 'featured_products' );

    $columns = absint( $atts['columns'] );
    wc_set_loop_prop( 'columns', $columns ); 
 
    ob_start();
 
    $query_args = array(
        'posts_per_page' => $atts['per_page'],
        'orderby'        => $atts['orderby'],
        'order'          => $atts['order'],
        'offset'         => $atts['offset'],
        'no_found_rows'  => 1,
        'post_status'    => 'publish',
        'post_type'      => 'product',
        'meta_query'     => WC()->query->get_meta_query(),
        'post__in'       => array_merge( array( 0 ), wc_get_featured_product_ids() )
    );
    ?>
    <ul class="products">
        <?php
            $loop = new WP_Query( $query_args );
            if ( $loop->have_posts() ) {
                while ( $loop->have_posts() ) : $loop->the_post();
                    wc_get_template_part( 'content', 'product' );
                endwhile;
            } else {
                echo __( 'No products found' );
            }
            wp_reset_postdata();
        ?>
    </ul>
    <?php
 
    return '<div class="woocommerce columns-' . $columns . '">' . ob_get_clean() . '</div>';
 
}
 
add_shortcode( 'oto_featured_products', 'oto_featured_products_func' );

//offset to latest product
function oto_latest_products_func( $atts ) {
    $atts = shortcode_atts( array(
        'per_page' => '12',
        'columns'  => '4',
        'orderby'  => 'date',
        'order'    => 'desc',
        'offset'   => 0,
        'category' => '', // Slugs
        'operator' => 'IN' // Possible values are 'IN', 'NOT IN', 'AND'.
    ), $atts, 'latest_products' );

    $columns = absint( $atts['columns'] );
    wc_set_loop_prop( 'columns', $columns ); 
 
    ob_start();
 
    $query_args = array(
        'posts_per_page' => $atts['per_page'],
        'orderby'        => $atts['orderby'],
        'order'          => $atts['order'],
        'offset'         => $atts['offset'],
        'no_found_rows'  => 1,
        'post_status'    => 'publish',
        'post_type'      => 'product',
        'meta_query'     => WC()->query->get_meta_query(),
    );
    ?>
    <ul class="products">
        <?php
            $loop = new WP_Query( $query_args );
            if ( $loop->have_posts() ) {
                while ( $loop->have_posts() ) : $loop->the_post();
                    wc_get_template_part( 'content', 'product' );
                endwhile;
            } else {
                echo __( 'No products found' );
            }
            wp_reset_postdata();
        ?>
    </ul>
    <?php
 
    return '<div class="woocommerce columns-' . $columns . '">' . ob_get_clean() . '</div>';
 
}
 
add_shortcode( 'oto_latest_products', 'oto_latest_products_func' );

**Comment by mikejolley** [comment]
Shortcodes support `page` which lets you define which page is loaded. This can be combined with `per_page`. We also support `paginate` if you want pagination.

**Comment by Amoditer** [comment]
I want to use this inside a slider a simple content slider. With offset I can tell the shortcode to show the first five product or seven, and in the next slide I can tell to offset the first five or seven, and show the next one. With this argument, I can avoid to use third part plugins for this. And I can make specific product grids too with a simple page builder, without any new code or plugin.

Could you tell me, how can I make this with the page or paginate or per_page arguments?

Thank you for your help :)

**Comment by mikejolley** [comment]
No that would be extra. I'd suggest contributing this via a PR if you need it to support offset too. Core itself does not need it.

**Comment by Dilip7597** [comment]
Hi, @Amoditer @mikejolley I see the issue is closed as @mikejolley mentioned that the "Core Itself does not need it". I feel it's just an array key to be updated into the shortcode function, it would be "Nice to have" feature.

@Amoditer, how did you manage to fix it alternatively? I'm trying the same thing as you did.
