### ISSUE TITLE
Uncaught error on variation products

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#19370]
This happens in the master branch and seems to be related to #19190.

When a variation product page first loads there is an `Uncaught ReferenceError: loading is not defined` on [line 45](https://github.com/woocommerce/woocommerce/commit/e27af8a416472417b86e0fd96388dfafbb1adae8#diff-b4056a3102144c129f0d05be2cf8cf32R45)

To reproduce:
1. Navigate to a variation product page.
2. Observe error in console (everything still seems to work OK though)

<img width="1661" alt="screen shot 2018-03-12 at 12 46 14 pm" src="https://user-images.githubusercontent.com/7317227/37305974-76298596-25f3-11e8-86c8-7b8d468b7b46.png">

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19382
