### ISSUE TITLE
After wocommerece 3.3 update the single product image div not fixing please help

### ISSUE THREAD

**Issue by admmin1531** [woocommerce/woocommerce#19374]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by admmin1531** [comment]
the issue face when i upload different size of images 
when i click on product gallery image the div of the showing image increase and decrease 
i need it to fix the dive please see the attachment when i click on these three images div of the product image increase and decrease my setting on selecting image dive is also attachemed please navigate the issue i tried last 4 days and search many articles but issue not resolve 
![image setting](https://user-images.githubusercontent.com/36724918/37327878-d425fc1c-26b9-11e8-905e-625efa847e63.PNG)

![image 1](https://user-images.githubusercontent.com/36724918/37327782-808465ee-26b9-11e8-8d26-6ad66e5dd805.PNG)
![image 2](https://user-images.githubusercontent.com/36724918/37327783-80bc52b0-26b9-11e8-85ff-43f6189a0b58.PNG)
![image 3](https://user-images.githubusercontent.com/36724918/37327785-80f6df98-26b9-11e8-9524-2808729b38bc.PNG)

**Comment by mikejolley** [comment]
That interface for sizes is from a plugin ^ I don't know if it's compatible. by default we use square gallery thumbnails.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/wiki/Customizing-image-sizes-in-3.3
