### ISSUE TITLE
Woocommerce Admin Orders Tabs Broken 

### ISSUE THREAD

**Issue by vijaykumarim** [woocommerce/woocommerce#19389]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Suddenly my woocommerce orders tabs are broken. When I googled it for solution I found (It’s a bug on tabs nav since it’s now utilizing the indexes instead of ID) this. Problem exists on the file Admin > Appearance > Customizer > Custom > Javascript
2.Please help me fix this
3.

## Expected/actual behavior

When I follow those steps, I see...  this https://imgur.com/a/PR7uM type of tabs broken tabs

I was expecting to see... Normal tabs with right alignment My website: https://hoverboardhub.com

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
You need to do 2 things;

1. Clear browser caches
2. Rule out plugin conflicts. See the 'isolating the problem' section above. We cannot replicate this and it's not affecting all users so it stands to reason it's a plugin you have installed conflicting with the layout.

Thanks

**Comment by vijaykumarim** [comment]
I've uninstalled all the plugins and checked with the default theme. Still the problem exists.


Please help me fix this...

**Comment by mikejolley** [comment]
Open screen options at the top of the screen. What's on/off?
