### ISSUE TITLE
CSV Import: Attribute visible set to 0 is unsetting "used for variations"

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#19398]
To replicate:

1) Create a variable product with one attribute, and create the variations: http://cld.wthms.co/NV827n
2) Export just variable products from the csv exporter.
3) Change "Attribute 1 visibile" column to 0.
4) Import the sheet with "merge existing".

Notice now that both of these are unchecked: http://cld.wthms.co/w5VDkN, and attributes are missing on the frontend.

This only happens when you only export/import variables products. Assuming it has to do with the variations not being imported as well, even though they did already exist. Using latest master in tests.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19414
