### ISSUE TITLE
Website's logo oversized on WooCommerce shop page

### ISSUE THREAD

**Issue by xMaT-eO** [woocommerce/woocommerce#19394]
I have a WooCommerce shop page on my website, and ONLY ON THIS PAGE, my website's logo is totally oversized, I tried different settings but none of them work. I put a screenshot with this post. Could you help me fix this ? Thanks a lot !

![capture](https://user-images.githubusercontent.com/32523207/37398167-e7ba3ed6-277d-11e8-9a46-271e10b37aa4.JPG)

Normally, the logo is the size of the red dot.

**Comment by mikejolley** [comment]
Not even an example link?

The shop page is usually a 'custom post type archive' so it may simply be that your theme didn't style these types of archives hence it looks different. 

Not sure if you've seen https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/

It won't be a WooCommerce specific issue, and may need either a change in template markup, or some additional CSS styles to resolve. You could post on the support forums or facebook communities if you want some tips (but they will also appreciate a link to the page ;)).

Thanks
