### ISSUE TITLE
Allocate sku for variable product

### ISSUE THREAD

**Issue by wireshop** [woocommerce/woocommerce#19393]
I'm selling inside my cable network
Each cable has different sizes, which I create as a variable product, but I have a problem, and that the sku or the product ID that I can enter is unique, meaning I can not add the identifier for each of my own variables.
How can this problem be resolved? Thanks for your advice.

**Comment by mikejolley** [comment]
If the parent SKU is say, `CABLE` you can add a suffix to each variation SKU e.g. `CABLE-1`, `CABLE-2`, or you can just leave out SKU for each variation. You cannot reuse SKUs and this is not a bug but by design.

Thanks
