### ISSUE TITLE
Can you use direct descendent in styling?

### ISSUE THREAD

**Issue by n-for-all** [woocommerce/woocommerce#19399]
https://github.com/woocommerce/woocommerce/blob/feba3bd3ed6b84c82a21d3f88b5f3ad5440db3f2/assets/css/woocommerce.scss#L316

if any `<li>` exist in the description, it inherit these styles, can we use `'>'` to only style woocommerce elements and not any list element, same for other styles?

**Comment by mikejolley** [comment]
If you wanted to contribute that you could send a PR, but in this case:

`ul.tabs`

Are the tabs themselves, not the content. So the description should not inherit these styles. 

See https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/tabs/tabs.php - `.tabs` is only on the list of tabs.

Thanks
