### ISSUE TITLE
Request: filter woocommerce_form_field required asterixes

### ISSUE THREAD

**Issue by gavsiu** [woocommerce/woocommerce#19397]
I was suggested by @WPprodigy on Wordpress.org to open an issue.

https://wordpress.org/support/topic/javascript-reverts-custom-checkout-form-placeholder/#post-10071760

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Copy `woocommerce_form_field` to functions.php and rename it.
2. Unset/remove `$required` from all fields (hiding the asterixes, not removing the requirement of the field).
3. Change template to use new function.
4. Asterixes are now mostly hidden, but JavaScript adds it back to country fields. Tested by commenting out `wp_enqueue_script` to disable them.
5. Disable browser JavaScript and it works.

## Expected/actual behavior

Ideally there would be a filter to change or remove `$required`, so there would be no need to duplicate the function at all.

https://github.com/woocommerce/woocommerce/blob/c38e0e69e9c72935f1c2507d629368d67e4154f9/includes/wc-template-functions.php#L2156

I'm not too familiar with how filters are actually written, so I couldn't do a pull request.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Rather than add complex code in the JavaScript to support this, and make it a requirement to move both JS and HTML required placeholders, it would be very easy to add 1 line of CSS to hide these.

I'd suggest doing that. One of our PRs under review is to allow you to show required or optional, and that is CSS based too so it aligns with future functionality.

Thanks
