### ISSUE TITLE
Change Products Shortcode column value to 4

### ISSUE THREAD

**Issue by DamiansDesign** [woocommerce/woocommerce#19408]
Shouldn't the Products Shortcode default column value be '4', since recently the default value was changed back to 4? See issue #18701 

https://github.com/woocommerce/woocommerce/blob/e45e7fdcd26f18fce91b44efea6f85450a5c4a79/includes/shortcodes/class-wc-shortcode-products.php#L116

I was expecting the products shortcode would simply use the value from
`wc_get_default_products_per_row()`, however this does not appear to be working. 

If products shortcode column value can't be obtained using `wc_get_default_products_per_row()`, then would it be possible to provide a filter to change the 'columns' attribute?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19412

**Comment by DamiansDesign** [comment]
@mikejolley 

Thank you for updating this, and for #19412.
