### ISSUE TITLE
Rearranging gateway display order only works every other time

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#19401]
This happens in 3.3.3 as well as current master. It's a small bug, though, so we don't need to hold up 3.3.4 because of it.

1. Start with some payment gateways.
<img width="1294" alt="screen shot 2018-03-14 at 11 43 34 am" src="https://user-images.githubusercontent.com/7317227/37424191-2982ab2e-277d-11e8-8cab-e1f7ba86e634.png">

2. Rearrange the gateways and save.
<img width="1300" alt="screen shot 2018-03-14 at 11 48 08 am" src="https://user-images.githubusercontent.com/7317227/37424417-9ea57e5e-277d-11e8-98a1-0799867f3d0a.png">

3. Observe after saving the new order didn't take.
<img width="1294" alt="screen shot 2018-03-14 at 11 43 34 am" src="https://user-images.githubusercontent.com/7317227/37424191-2982ab2e-277d-11e8-8cab-e1f7ba86e634.png">

4. Rearrange the gateways and save.
<img width="1300" alt="screen shot 2018-03-14 at 11 48 08 am" src="https://user-images.githubusercontent.com/7317227/37424417-9ea57e5e-277d-11e8-98a1-0799867f3d0a.png">

5. Observe after saving the new order took.
<img width="1300" alt="screen shot 2018-03-14 at 11 48 08 am" src="https://user-images.githubusercontent.com/7317227/37424417-9ea57e5e-277d-11e8-98a1-0799867f3d0a.png">

I am consistently able to reproduce this pattern every time I try and rearrange the gateways.

**Comment by nishitlangaliya** [comment]
Hi @claudiulodro ,

I tried to reproduce case. actually what I found that when you rearrange the gateways and save then it won't show you updated rearranged order on screen but when you refresh the settings page without rearrange order second time. it will show your updated rearranged setting. let me know if I am missing something.

Thanks

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19415
