### ISSUE TITLE
Divi Builder and WooCommerce

### ISSUE THREAD

**Issue by gaagency** [woocommerce/woocommerce#19406]
There appears to be a bug between the Divi Theme Builder and WooCommerces' Settings (Products > Shop PAge)

When I set the page I've built as the shop front as the 'Shop Page' under WooCommerce Settings>Products, the divi builder no longer works.

I've duplicated my shop front page, and NOT set it as the official 'Shop Page' but have it as the shop page on my website and I'm not having this issue any further. I'm not sure if this will effect the way WooCommerce works, though...

**Comment by mikejolley** [comment]
Hi this was something the Divi team released a fix for. Please use their support area if you need assistance.

Thanks
