### ISSUE TITLE
Admin Product Search:  Can no longer search short description

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce#19402]
In WooCommerce 3.3.0 you could do a Product Search in the Admin and enter in a term from the Short Description and you would get results.

In 3.3.1, 3.3.2, and 3.3.3 this is no longer possible.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product
2. Add a short description to that product
3. Go to Products from the Dashboard
4. Enter in a word that is found in the short description, and click "Search Products"

**Comment by rlinsoliveira** [comment]
Mike, same problem here. In admin i can't search by description or short description. I use this to find different codes like EAN to my clients.

This is working fine before 3.3.1.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/19413
