### ISSUE TITLE
PayPal Standard: Line Item Limit

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#19404]
Forum post: https://wordpress.org/support/topic/pyapal-standard-problem-after-woocommerce-3-3-3-update/

Does PayPal still enforce this limit?  https://github.com/woocommerce/woocommerce/blob/8b06e0e43259ff918af0db86d02c8d3216255fe9/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L367

The user in the above post found they were able to send much more than 9.

Mike mentioned that some of the params here say `A valid value for x is from 0 to 9.`: https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/, though not for products anymore.

Some history: https://github.com/woocommerce/woocommerce/issues/3124

**Comment by WPprodigy** [comment]
Also noting this will need an update if a change is made: https://docs.woocommerce.com/document/paypal-standard/#section-12

**Comment by peterfabian** [comment]
I wasn't able to find any documentation mentioning 9 line item limit. I could submit a cart with 40 items without problems in Chrome and Safari.

If I understand it correctly, this is what happens: 
1. Cart is submitted by clicking `Proceed to PayPal` button
2. This calls `wc-ajax=checkout`, which gathers all the info from the cart and creates a URL (in the file linked by @WPprodigy) pointing to PayPal endpoint (`cgi-bin/webscr`)
3. Browser gets the JSON response and (in `checkout.js`) is redirected to the URL from 2. 

This, I can imagine, can quickly lead to old IE limit of 2048 characters. Newer browsers should be able to handle it, but not sure about old/mobile browsers.

As a quick fix solution, I think we can probably just increase the limit (even with example 40 items in cart, URL was around 5500 characters long, so a long way from hitting limit around 60k for current browsers). However, in the long term, maybe it would be more sensible to submit such data over POST? 

Please let me know if I should look into other options (e.g. using the POST request) or just update this value (and perhaps add a 'wishlist' issue if we want to fix it later).

**Comment by mikejolley** [comment]
Is there anyway to test for a limit?

Using GET vs POST makes for a smoother checkout flow so I don't think we should switch it. We can fallback to sending the order as 1 item if the number of cart items cannot be supported.

**Comment by UserName011** [comment]
PayPal changes their polices frequently. The 9 line items limit was removed a while ago.
What is the point of checking it anyway? If you will pass the limit the transaction will fail. There is no need to check for it in advanced. Like WC doesn't check if the value of the transaction is over $10,000  https://www.paypal.com/us/selfhelp/article/what-is-the-maximum-amount-i-can-send-with-my-paypal-account-faq732

**Comment by mikejolley** [comment]
This is being worked on in https://github.com/woocommerce/woocommerce/pull/19493
