### ISSUE TITLE
The string "Shipping Name" cannot be translated correctly

### ISSUE THREAD

**Issue by fhaps** [woocommerce/woocommerce#19418]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Download and install the Spanish translation files from [here](https://translate.wordpress.org/projects/wp-plugins/woocommerce).
2. Change the site language to the language you just installed.
3. Go to the store, add a product to your cart, and proceed to checkout.
4. Check the `Ship to a different address?` option, and try to complete payment *without filling the Shipping Name and Shipping Last Name fields.

## Expected/actual behavior

When I follow those steps, I see the following error message pop up:

![](http://cld.wthms.co/3RB5pm+)
Image Link: http://cld.wthms.co/3RB5pm

This is the equivalent in the English version:

![](http://cld.wthms.co/P0k0uv+)
Image Link: http://cld.wthms.co/P0k0uv

The problem is that "Shipping name" and "Shipping Last Name" are incorrectly translated. It seems like the plugin is taking the translations for the words `Shipping`, `Name`, and `Last Name` separately, and then just putting those translated words together to create the translation of those phrases.

* `Shipping` in Spanish is `Envío`
* `Name` in Spanish is `Nombre`
* But `Shipping name` should be translated as `Nombre de envío`
* What the plugin is doing instead is: `Envío nombre`

`Shipping name` and `Shipping last name` should be their own translatable strings, instead of a line composed of two separate strings.

There seems to be an string for `Shipping name` already, but it's not being used here. I couldn't find a `Shipping last name` string.

![](http://cld.wthms.co/vnEMT9+)
Image Link: http://cld.wthms.co/vnEMT9

I tested this with Spanish and French and the issue is present with both.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by kloon** [comment]
@fhaps thanks for reporting, we handle all our translations via https://translate.wordpress.org/projects/wp-plugins/woocommerce

What I suggest you do is make an edit on the translation there and it will be reviewed and other translators can comments and help review it.

Alternatively, if you wish to only change this on your own site you can download a translation plugin like Loco Translate and then make the changes on your site. However, I would suggest you rather contribute back to the plugin if the language is wrong by going the official translation route.

**Comment by fhaps** [comment]
Hey @kloon, thanks for looking! I'm not sure if the issue was correctly understood. The problem is that the plugin cannot be translated correctly with the way the plugin's original language file is configured right now.

`Shipping First name` should be its own individual string, instead of a line composed of two separate strings that are translated individually: `Shipping` and `First name`.

Correct me if I'm wrong, but I believe this should be fixed in the plugin's original language file, and not in an individual translation.

**Comment by peterfabian** [comment]
One slightly tricky thing is that those captions are created dynamically from 'Shipping'/'Billing' + field name. 
We could, however, sync those with strings we have in https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-privacy-erasers.php#L44 so that they would be translated using the same strings. There are some minor differences here and there that would need to be synced, but otherwise I think it should improve the quality of translation.

**Comment by SiR-DanieL** [comment]
It is true that they are created dynamically. It appears to be coming from here:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L664

So, in my opinion, it still is correctly translatable if it's just a matter of ordering the words differently.

**Comment by peterfabian** [comment]
Please see linked PR. If it gets in, it should make the job for translation easier. 

Otherwise, as others said, it perhaps can be translated by translated 'Shipping %s' to '% de envio'? Not 100% sure it covers all cases, though.

**Comment by claudiulodro** [comment]
[The issue seems to be a mistranslation of `Shipping %s`](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/es/default?filters%5Bterm%5D=shipping+%25s&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc). The translation should be `%s de Envío`. This should work in all cases as `de Envío` is an adjective and `%s` will always be a noun.
