### ISSUE TITLE
PHP warning when use the filter woocommerce_background_image_regeneration

### ISSUE THREAD

**Issue by Ripon-NH** [woocommerce/woocommerce#19410]
Hi, after applying this "add_filter( 'woocommerce_background_image_regeneration', '__return_false' );" in my functions.php, I am getting the warning "Warning: sprintf(): Too few arguments in /home/public_html/wp-content/plugins/woocommerce/includes/customizer/class-wc-shop-customizer.php on line 453"

After investigating line 453 "$regen_description = sprintf( __( 'After publishing your changes, new image sizes may not be shown until you <a href="%2$s" target="_blank">Regenerate Thumbnails</a>.', 'woocommerce' ), 'https://en-gb.wordpress.org/plugins/regenerate-thumbnails/' );" it seems it should be %1$s instead of %2$s in that line as there is only one argument for sprintf

**Comment by mikejolley** [comment]
This is fixed for 3.3.4
