### ISSUE TITLE
date_modified of product in not being updated

### ISSUE THREAD

**Issue by FrEaKmAn** [woocommerce/woocommerce#19427]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product with REST api with price and stock
2. Update the product stock with REST api
3. Check the date_modified and date_modified_gmt dates

## Expected/actual behavior

I would expect for date_modified to be updated. But it's not. Checking the code https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L180 it only updates those dates if one of the `'name', 'parent_id', 'status', 'menu_order', 'date_created', 'date_modified'` changes (where you can actually control only first 4).

**This of course is not a bug, but more a missing implementation** from by point of view. I was excepting that if I update the product, this value would also update.

I tried adding hooks and manually updating date_modified without success. One option is to submit update of the product with status=draft and then immidiately again with status=publish, but it's 2 requests.

Is it normal that date_modified is not updated even though I did update the product?

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by claudiulodro** [comment]
I don't know that it makes sense to update the `date_modified` for stock changes. For regular users their products would have a new `date_modified` every time someone bought something (and the stock was reduced), which is not desired.

**Comment by Micemade** [comment]
@FrEaKmAn - did you solve this?
The products list in admin is showing `post_date` value, even if date field shows it as "Last updated" (I tested it, and it never updates to `post_modified`. This is important to me so my clients can give me information on which old product drafts can be deleted.
Thanks
