### ISSUE TITLE
My account login and register missing autocomplete attributes

### ISSUE THREAD

**Issue by michakrapp** [woocommerce/woocommerce#19425]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Open Chrome Browser (best example, should work for others too)
2. Open a woocommerce store and register for an account. Save the credentials in the browser when it asks to do so. (Settings should allow register)
3. Logout and open the my account page.
4. The login and the register form appear. If you have registered an account before and saved the account data Chrome will fill out the inputs for you.
5. See that Chrome is filling out the fields from login form AND from register form

## Expected/actual behavior

As the register form is to create a new account, it should not use autocomplete of before saved credentials.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

Not important for the problem.

## Solution
I will submit a PR with the correct autocomplete values to avoid the described behaviour.

**Comment by michakrapp** [comment]
Added pull-request
https://github.com/woocommerce/woocommerce/pull/19426

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19426
