### ISSUE TITLE
Message in Cart not translated

### ISSUE THREAD

**Issue by klswim** [woocommerce/woocommerce#19438]
Hi,

I've created my website with woocommerce and woocommerce bookings plugin and accomodation booking plugin.
The bug appear in the cart page.
I add a product into the cart. That leads me on the cart page.
In this page there is still text not translated in french like "Update Cart", "Product", Quantity", "Price".
I tried to modify fr_FR.po but there is no way to change this.

Can it be corrected ?

Kevin

**Comment by mikejolley** [comment]
The translations may be part of your theme. All strings in WooCommerce itself are localised, and the translation for that can be done on glotpress.

See https://docs.woocommerce.com/document/woocommerce-localization/

You may need to translate your theme's localisation files.
