### ISSUE TITLE
Inconsistent return by $order->needs_shipping_address() on woocommerce_new_order

### ISSUE THREAD

**Issue by Drivingralle** [woocommerce/woocommerce#19430]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add following code to functions.php or mu-plugin:
```
function need_shipping_test( int $order_id ) {

    error_log(var_export( 'need_shipping_test called', true ) );
    error_log(var_export( $order_id, true ) );

    error_log(var_export( 'called by:', true ) );
    error_log(var_export( current_filter(), true ) );

    // Fetch the order object
    $order = wc_get_order( $order_id );

    error_log( var_export( $order->needs_shipping_address(), true ) );

}
add_action('woocommerce_new_order', 'need_shipping_test' );
add_action('woocommerce_thankyou', 'need_shipping_test' );
```

2. Setup a virtual and a none-virtual product in WooCommerce
3. Order one or the other product or both at once and check the log output

## Expected/actual behavior

The woocommerce_new_order hook should represent the right state of information about an order. Currently this hook communicates wrong information.

Running the test above results in:
None-virtual product + woocommerce_new_order = false
None-virtual product + woocommerce_thankyou = true

Virtual product + woocommerce_new_order = false
Virtual product + woocommerce_thankyou = false

Mixed products + woocommerce_new_order = false
Mixed products + woocommerce_thankyou = true

Problem is that if I hook into woocommerce_new_order to validate/modify data or add async tasks for orders that contain physical products aka. need shipping I miss out to add my things.

## Isolating the problem
As far as I understand the problem the woocommerce_new_order hook fires before all values that lead to an true return of needs_shipping_address() check are set.

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by Drivingralle** [comment]
Not sure how to fix this.

Hooking the function on a higher priority like 1000 doesn't fix it.

**Comment by mikejolley** [comment]
Checkout creates an order before it adds items/shipping/takes payment for an order. It's too early in that context to know if shipping address is needed.

**Comment by Drivingralle** [comment]
I always understood the action to be the one place to hook into after WooCommerce has done its things and allows plugins to take it from there. 

That hook is called in frontend and API. 

Should we add an action like woocommerce_new_order_finished to allow plugins to get the finish created order?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L984

**Comment by Drivingralle** [comment]
Interesting.

So I guess the behavior like described above is expected?

**Comment by mikejolley** [comment]
In this case yes. The action fires when an order is created, not when we're 'done' adding data to the order.
