### ISSUE TITLE
Add unique ID to Import/Export buttons at backend

### ISSUE THREAD

**Issue by kanlukasz** [woocommerce/woocommerce#19431]
Hello,

Please, add unique ID to Import/Export buttons at backend
Sometimes we need to hide this buttons for shop_manager

![imex](https://user-images.githubusercontent.com/30685349/37529909-a397e052-2938-11e8-8acb-50d0575780eb.jpg)

I know, we can use nth-child, but ID's are most simple for use

Wp 4.9.4
Woo 3.3.3

Best regards
Lukas

**Comment by mikejolley** [comment]
Bad solution; they could still access the import/export pages directly.

**Comment by kanlukasz** [comment]
Yes, you right of course, sorry for non-logical idea.
Hm... so maybe any solution with Roles & Capabilities ?

**Comment by mikejolley** [comment]
`class-wc-admin-exporters.php` and `class-wc-admin-importers.php` both use `edit_products` capability.  We could add a new capability for import/export but this would also need to be added to existing shop managers and admins on install to work.

**Comment by peterfabian** [comment]
I was wondering--can't we use [import](https://codex.wordpress.org/Roles_and_Capabilities#import) and [export](https://codex.wordpress.org/Roles_and_Capabilities#export) capabilities instead of `edit_products` capability or is adding new capability the preferred way to go? 

If I understand it correctly, WooCommerce's own import/export just enhances the import/export functionality provided by vanilla WP, but conceptually they are the same thing, so I would say tying them to import/export capabilities and then (un)assigning those to roles would be better than adding a new capability. What do you think?

**Comment by mikejolley** [comment]
Wasn't aware those existed. How about combining both; require `import` and `edit_products`?

**Comment by kloon** [comment]
The problem with combining the both would be that the add_submenu_page only takes a string for a capability so you cannot hide it based on multiple capabilities, you would have to create a new cap that combines the two into one and use that.

Or is that what you meant with requiring both?

**Comment by mikejolley** [comment]
Look at the main importer and see if you can import products without edit_product cap? If so we can just use import. If not, we'll need a new import_products cap.

**Comment by peterfabian** [comment]
Currently, if user does not have `edit_products` capability, they can't even display the Products page in admin and import from Tools > Import fails as the link it points to Products page `edit.php?post_type=product`.

It looks like the main WP importer assumes [increasing level of access](https://codex.wordpress.org/Roles_and_Capabilities#Capability_vs._Role_Table) and `import` has `edit_posts` (or `edit_products` in this case) as a(n implicit) prerequisite. I think that it does not make much sense to have right to `import` without right to `edit_products`.

Therefore, I think this might work:
1. Showing the Import/Export buttons based on import/export capability (and those should be passed to `add_submenu_page`). 
2. Checking both `import`/`export` and `edit_products` capabilities in `do_ajax_product_import` and `_export`

Then, if I understand it correctly, creating a weaker shop manager role without `import` capability should hide Import/Export buttons and won't allow the code to run. 

@mikejolley @kloon Please let me know if you still think creating a new capability is a better choice here.

**Comment by mikejolley** [comment]
What you described sounds good 👍
