### ISSUE TITLE
How to use process_payment with POST request for gateway

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#19432]
If below form is submitted then it will auto redirects to payment gateway page but if method is set as GET then it will redirect to the page but unfortunetely when cancel button is trigger it will have `null` string attached at the query. But for POST request it works great. Thus how can I implement post request in `process_payment()` method and redirect to the payment gateway page.

```
<form action="https://ir-user.esewa.com.np/epay/main" method="POST">
	<input value="100" name="tAmt" type="hidden">
	<input value="90" name="amt" type="hidden">
	<input value="5" name="txAmt" type="hidden">
	<input value="2" name="psc" type="hidden">
	<input value="3" name="pdc" type="hidden">
	<input value="kapadaa" name="scd" type="hidden">
	<input value="XYZ-1234" name="pid" type="hidden">
	<input value="https://woocommerce.io/wc-api/WC_Gateway_eSewa/?payment_status=success&key=wc_order_5aabe588f050c" type="hidden" name="su">
	<input value="https://woocommerce.io/wc-api/WC_Gateway_eSewa/?payment_status=failure&key=wc_order_5aabe588f050c" type="hidden" name="fu">
	<input value="Submit" type="submit">
</form>
```

CC @claudiosanches @mikejolley

**Comment by mikejolley** [comment]
Hi @shivapoudel 

Not sure why you're asking about custom gateway code here :) If the gateway does not support GET you'll need to output that form on the thanks page and trigger submission using javascript. Thats how we used to handle PayPal standard until we found out they do actually support GET.

Hope that helps :)
