### ISSUE TITLE
Check if image exists inside gallery for PhotoSwipe plugin

### ISSUE THREAD

**Issue by chvillanuevap** [woocommerce/woocommerce#19435]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install the WooCommerce Featured Video plugin.
2. Attach featured video to product page.
3. Have theme support for `wc-product-gallery-lightbox`.
4. Use lightbox on a product page.

See https://thepostmansknock.com/catalog/kaitlin-style-calligraphy-video-course/ and access the full screen "lightbox".

## Expected/actual behavior

Plugins and themes have the option to replace the html of the single product featured image via the `woocommerce_single_product_image_thumbnail_html` hook. Since we can replace the HTML, this means we can replace the image with anything else, like a video. This is what the WooCommerce Featured Video plugin does. It replaces the image HTML with a video embed. The YITH WooCommerce Featured Video plugin does something similar.

If the HTML of the thumbnail is replaced by anything other than an image, then the PhotoSwipe plugin does not behave as expected. It fails to load an image because there is no image, and the first item in the full screen slider is just a black screen. 

## Isolating the problem

The function `ProductGallery.prototype.getGalleryItems` in `assets/jsfrontend/single-product.js` should have a check here:

```    
if ( $slides.length > 0 ) {
        $slides.each( function( i, el ) {
            var img = $( el ).find( 'img' );

            // INSERT CHECK.
            // If img found --> push to items. Else, continue to next object in $slides.
            var large_image_src = img.attr( 'data-large_image' ),
                large_image_w   = img.attr( 'data-large_image_width' ),
                large_image_h   = img.attr( 'data-large_image_height' ),
                item            = {
                    src  : large_image_src,
                    w    : large_image_w,
                    h    : large_image_h,
                    title: img.attr( 'data-caption' ) ? img.attr( 'data-caption' ) : img.attr( 'title' )
                };
        items.push( item );
    } );
}
```

That way, the object with the video embed is skipped, and the black screen is avoided.

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

WordPress 4.9.4

<details>
`
### WordPress Environment ###

Home URL: https://localhost/thepostmansknock
Site URL: https://localhost/thepostmansknock
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.23 (Unix) OpenSSL/1.0.2h PHP/7.0.9 mod_perl/2.0.8-dev Perl/v5.16.3
PHP Version: 7.0.9
PHP Post Max Size: 1 GB
PHP Time Limit: 360000
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
Total Database Size: 1257.75MB
Database Data Size: 699.20MB
Database Index Size: 558.55MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 40.58MB + Index: 66.00MB
wp_woocommerce_order_items: Data: 18.55MB + Index: 5.52MB
wp_woocommerce_order_itemmeta: Data: 101.64MB + Index: 91.25MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_alm: Data: 0.02MB + Index: 0.00MB
wp_blc_filters: Data: 0.02MB + Index: 0.00MB
wp_blogs: Data: 0.02MB + Index: 0.03MB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 8.52MB + Index: 10.55MB
wp_comments: Data: 45.58MB + Index: 42.13MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 8.52MB + Index: 4.03MB
wp_podsrel: Data: 0.02MB + Index: 0.06MB
wp_popularpostsdata: Data: 0.06MB + Index: 0.02MB
wp_popularpostssummary: Data: 1.52MB + Index: 1.30MB
wp_postmeta: Data: 320.89MB + Index: 236.52MB
wp_posts: Data: 58.58MB + Index: 27.14MB
wp_registration_log: Data: 0.02MB + Index: 0.02MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB
wp_site: Data: 0.02MB + Index: 0.02MB
wp_sitemeta: Data: 0.02MB + Index: 0.03MB
wp_subscribe_reloaded_subscribers: Data: 0.05MB + Index: 0.02MB
wp_swp_cf: Data: 2.52MB + Index: 3.27MB
wp_swp_index: Data: 24.55MB + Index: 19.41MB
wp_swp_log: Data: 9.52MB + Index: 10.55MB
wp_swp_tax: Data: 0.27MB + Index: 0.36MB
wp_swp_terms: Data: 3.52MB + Index: 4.55MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 7.52MB + Index: 3.52MB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB
wp_usermeta: Data: 41.58MB + Index: 27.11MB
wp_users: Data: 4.52MB + Index: 4.55MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

_pods_field: 3
_pods_pod: 5
amn_mi-lite: 1
attachment: 7766
course: 3
faq: 17
feedback: 2
gallery: 8
lesson: 13
nav_menu_item: 24
page: 18
portfolio: 20
post: 338
product: 155
question: 28
quiz: 13
revision: 192
safecss: 1
shop_coupon: 108
shop_order: 138897
shop_order_refund: 41
sidebar: 7
slideshow: 3
supply: 3
ticket-meta-fieldset: 1
tribe_events: 9
tribe_venue: 4
tribe_wooticket: 79
wishlist: 11
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Query Monitor: by John Blackbourn – 2.17.0
Contact Form 7: by Takayuki Miyoshi – 5.0.1
Duplicate Widget: by Scott Reilly – 1.0.2
Genesis Connect for WooCommerce: by StudioPress – 0.9.10 – Not tested with the active version of WooCommerce
Lazy Load for Comments: by Joel James – 1.0.3
Sensei Course Progress: by WooThemes – 1.0.6
WooCommerce Featured Video: by David Towoju (Figarts) – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.3
Sensei: by WooCommerce – 1.9.20
Yoast SEO: by Team Yoast – 7.0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4026 - /catalog/
Cart: #4027 - /cart/
Checkout: #4028 - /checkout/
My account: #4029 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: The Postman's Knock
Version: 3.84.0
Author URL: https://thepostmansknock.com/about/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.6.1
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: thepostmansknock/woocommerce/archive-product.php version - is out of date. The core version is 3.3.0
thepostmansknock/woocommerce/cart/cross-sells.php
thepostmansknock/woocommerce/cart/shipping-calculator.php
thepostmansknock/woocommerce/checkout/form-billing.php
thepostmansknock/woocommerce/checkout/thankyou.php
thepostmansknock/woocommerce/content-product.php
thepostmansknock/woocommerce/order/order-details-item.php
thepostmansknock/woocommerce/order/order-details.php
thepostmansknock/woocommerce/single-product/related.php
thepostmansknock/woocommerce/single-product-reviews.php
thepostmansknock/woocommerce/single-product.php version - is out of date. The core version is 1.6.4

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by chvillanuevap** [comment]
Sure. I'll try to get around it sometime next week.

**Comment by mikejolley** [comment]
@chvillanuevap Still on this or should we assign someone else?

**Comment by mikejolley** [comment]
YITH works around this without code change FYI.
