### ISSUE TITLE
Local Pickup is the only shipping option

### ISSUE THREAD

**Issue by elliottcoe** [woocommerce/woocommerce#19448]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a new shipping zone for UK, with free shipping, flat rate and local pickup.
2. Add item to cart and go to cart and see shipping methods
3. Local pickup is the only method available, if you var_dump $available_methods it is the only option.

## Expected/actual behavior

When I follow those steps, I see only local pickup as an shipping option.

I was expecting to see all available shipping methods

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

I am using a custom theme, but there are no custom functions to stop shipping methods from being pulled from the database, if I delete 'Local Pickup' the 'Flat Rate' shipping method will display, it only appears to be getting one method out of the DB at a time. I guess this issue is to better understand how the shipping method system works.

**Comment by elliottcoe** [comment]
Update for this, I re-added the methods and added free shipping but didn't put any requirements on it, now free shipping and local pickup display but flat rate still does not show.

**Comment by mikejolley** [comment]
> Update for this, I re-added the methods and added free shipping but didn't put any requirements on it, now free shipping and local pickup display but flat rate still does not show.

Requirements? I know free shipping can have requirements, but flat rate do not. Flat rate will however only show if you add a cost. Perhaps the cost string is the problem in your case?

Based on your instructions I'm not seeing the issue:

![cart local wordpress dev 2018-03-19 11-51-38](https://user-images.githubusercontent.com/90977/37594004-e81400e6-2b6b-11e8-9a2e-9d54319dfae5.png)

All rates have costs and there are no requirements/restrictions in place. WC will show all available methods in a zone by default. Doesn't seem to be a problem here.

Thanks
