### ISSUE TITLE
Checkout label on my account but empty cart

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#19442]
I have seen that if I as a not logged in customer put a product into cart and remove it from there and then go to my account page, the box with label "Checkout as guest without a account" & click here is visible even if there isn't anything in cart. If I login (in this case I was admin) I am redirected to cart which is empty. This is a bit confusing to customers.

I do not have caching plugins installed. If I close browser window and reopen a new one with that site, then message is gone.

![bildschirmfoto 2018-03-17 um 13 16 57](https://user-images.githubusercontent.com/3390880/37555301-b1d234ee-29e5-11e8-9e19-2525cb5c57a5.png)

**Comment by mikejolley** [comment]
Hi Adrian

The message "Checkout as guest without a account" is not part of WooCommerce core sorry :) That must be coming from an extension, one which isn't checking if the cart is empty correctly. AFAIK we don't show these types of call to actions anywhere.

Thanks

**Comment by ajgw** [comment]
Hi Mike, you are true. I found that it comes from a plugin for german market. Thanks for your patience and sorry for my post.
