### ISSUE TITLE
Coupon data preformance issue

### ISSUE THREAD

**Issue by gpisarski** [woocommerce/woocommerce#19450]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create sample coupon or use existing one
2. Make order with coupon
3. Check woocommerce_order_itemmeta and find row with meta_key 'coupon_data'.
4. Make as many orders (with different billing email) as you can with the same coupon.
5. Go to step 3, the size of this row is much bigger than in the first order.

## Expected/actual behavior

Generally it is performance issue. Since WC 3.2, all coupon data from postmeta table are stored in woocommerce_order_itemmeta with key 'coupon_data'. I supose that these data are required in some particular cases, but for stores with huge volume of orders database size grows at exponential rates. I have hundreds orders per day and most of them automatically use one of coupons, each day count of '_used_by' meta for this coupon is bigger and all this meta are stored in woocommerce_order_itemmeta table which grows and grows hundres of MBs per day.

Maybe these data sholud be filtered and store only most neccessary data in woocommerce_order_itemmeta.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
WooCommerce >= 3.2
```
</details>

**Comment by mikejolley** [comment]
This is used to track emails which use coupons so we can do restrictions.

@rodrigoprimo @kloon Thoughts?

This may need some work anyway so we don't store actual emails for GDPR. Maybe hashes would work better. Not sure if we should keep in meta or not.

**Comment by gpisarski** [comment]
I think these informations have to stay in postmeta table (which also grows), but probably there is no reason to clone this into woocommerce_order_itemmeta, each '_used_by' is repeatedly reproduced in  order item meta. I checked the code and made some tests, but of course they may be insufficient, anyway I think _used_by is not read from order item meta right now.

**Comment by mikejolley** [comment]
I see it.

`$item->add_meta_data( 'coupon_data', $coupon->get_data() );`

Yes we should exclude this also. Still think a table to link coupon to user would be useful.

**Comment by rodrigoprimo** [comment]
I didn't check the code but I can confirm that storing all coupon data for every order item looks problematic. I checked a test website where the size of the wp_woocommerce_order_itemmeta table is 2.4GB. In this website, `coupon_data` entries alone take 1.3GB.

**Comment by mikejolley** [comment]
@rodrigoprimo It might cause issues when removing coupons but maybe we should do a cleanup on update? Or would it be best left to user?

**Comment by kloon** [comment]
Are there any reasons why we are storing the coupon data in each order is it used? Ideally, a link table could be a win here, or we can move the coupon usage tracking to the coupon side itself and check and update it that side?

**Comment by gpisarski** [comment]
I think these data are used to recalculate order total after manually coupon remove from order (probably only in admin panel). Others coupons need to be re-apply to order and during this proccess if coupon doesn't exist, coupon datas are loaded from woocommerce_order_itemmeta. In my opinion this is the only case, but maybe I am wrong. I also think that main problem is storing '_used_by', which is not required when coupon doesn't exist, so if we can store in woocommerce_order_itemmeta filtered data without _used_by it should be ok.

**Comment by rodrigoprimo** [comment]
> @rodrigoprimo It might cause issues when removing coupons but maybe we should do a cleanup on update? Or would it be best left to user?

@mikejolley, do you see any issues with removing just the property `_used_by` fromwoocommerce_order_itemmeta `coupon_data` as @gpisarski suggested?

**Comment by mikejolley** [comment]
If thats possible that sounds wise.

**Comment by gpisarski** [comment]
@mikejolley I think we can replace this line of code:

`$item->add_meta_data( 'coupon_data', $coupon->get_data() );`

with: 

`$coupon_data = $coupon->get_data();
unset($coupon_data['used_by'];
$item->add_meta_data( 'coupon_data', $coupon_data );`

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19669

**Comment by KitKat31337** [comment]
I see this is marked closed, but the initial reported behavior and performance issues still exist.  It looks like the PR that went through was cleanup for GDPR but not actually changing the behavior.  I have encountered a site with over 5 GB in the wp_woocommerce_order_itemmeta table, about half of which is only the coupon_meta key.

This is the results of the following query:
`SELECT 
	meta_key, 
	count(meta_id) AS "Count", 
	AVG(LENGTH(meta_value))/1024 AS "Average Size (KB)", 
	MAX(LENGTH(meta_value))/1024 AS "MAX SIZE (KB)", 
	SUM(LENGTH(meta_value))/1048576 AS "Total Size (MB)" 
FROM wp_woocommerce_order_itemmeta 
GROUP BY meta_key`

[wp_woocommerce_order_itemmeta (1).csv](https://github.com/woocommerce/woocommerce/files/9822672/wp_woocommerce_order_itemmeta.1.csv)

In this database the average size of the coupon_data entry is almost 200 times the size of the next largest meta_key average size (28.91 KB -> 0.15 KB)

The largest entry for coupon_data is 162.98 KB.  For a single record.

There seems to still be an obvious performance issue here, which was the issue reported, but not the issue solved.

@mikejolley Please consider reopening this issue for its initial issue.
