### ISSUE TITLE
Catalog visibility for Child Products

### ISSUE THREAD

**Issue by satrah89** [woocommerce/woocommerce#19462]
**Explanation:**
Child products that are under a grouped product do not get an `a href` link to the child product page when catalog visibility is set to search or hidden.
It is essential to have the child products linking to their respective product page.

Using WordPress 4.9.4 - WooCommerce 3.3.3

I have seen this issue fixed on 2.6.8 using this method but it does not work for 3.3.3 - result is the grouped product image, title and nothing else. Does not list child products or grouped product description

> Copy:
> /wp-content/plugins/woocommerce/templates/single-product/add-to-cart/grouped.php
> To:
> /wp-content/themes/YOUR-CHILD-THEME/woocommerce/single-product/add-to-cart/grouped.php
> Change the following line from:
> <?php echo $product->is_visible() ? '<a href="' . esc_url( apply_filters( 'woocommerce_grouped_product_list_link', get_permalink(), $product_id ) ) . '">' . get_the_title() . '</a>' : get_the_title(); ?>
> To:
> <?php echo '<a href="' . esc_url( apply_filters( 'woocommerce_grouped_product_list_link', get_permalink(), $product_id ) ) . '">' . get_the_title() . '</a>'; ?>

.

**Comment by mikejolley** [comment]
We don't support customisations here. Sufficed to say, you can customise that template and edit this line:

`$value .= $grouped_product->is_visible() ? '<a href="' . esc_url( apply_filters( 'woocommerce_grouped_product_list_link', get_permalink( $grouped_product->get_id() ), $grouped_product->get_id() ) ) . '">' . $grouped_product->get_name() . '</a>' : $grouped_product->get_name();`

If you need help you may need a developer to do it for you. A better solution would be to filter the `woocommerce_product_is_visible` filter and return true if viewing a single page (`is_single`).
