### ISSUE TITLE
woocommerce api couon code not working

### ISSUE THREAD

**Issue by shamstarek** [woocommerce/woocommerce#19460]
Hi

I'm try to send a post request to create a new order with coupon code "coupon_lines".
The order already sent and respond with 201, But the total of the order amount doesn't decreased.

When I check from wp-admin "order edit screen". I fount the coupon selected in the coupon filed but the discount amount is 0.

  "coupon_lines": [
	{
	"order_id": 7594,
    "code": "thimar-first",
    "discount": "25",
    "discount_type": "percent"
	}]

I'm using WordPress Version 4.9.4 + WooCommerce Version 3.3.3

**Comment by mikejolley** [comment]
The current API does not apply coupons automatically. This will be part of v3 API.

For now you need to set the correct prices for your line items, including any discounts.
