### ISSUE TITLE
'order' and 'orderby' query vars not working for shop page when using rewrite rule

### ISSUE THREAD

**Issue by electrokit** [woocommerce/woocommerce#19472]
When calling the shop page by:
http://example.com/index.php?post_type=product&orderby=price
we get the shop page with products ordered by price.
But if we add
```
add_rewrite_rule(
	'^cheapest/?',
	'index.php?post_type=product&orderby=price',
	'top'
);
```
to the 'init' hook, the new url (http://example.com/cheapest) won't order the products correctly.
The reason is this line:
https://github.com/woocommerce/woocommerce/blob/dc7aa3069466f1b7e23fd7ef468760a6a9ddd241/includes/class-wc-query.php#L430
Changing `$_GET['orderby']` to `get_query_var( 'orderby' )` solves this.
Are there any reasons for using $_GET?
I have not tested it, but I suppose $_GET will work if we flush rewrite rules to .htaccess, so the current code will handle soft and hard flushes differently.

**Comment by claudiulodro** [comment]
We'll have to do some investigation to make sure the change won't break anything, but it seems reasonable enough.

**Comment by mikejolley** [comment]
^ sounds like the safest option.
