### ISSUE TITLE
PayPal received 

### ISSUE THREAD

**Issue by im1981** [woocommerce/woocommerce#19476]
Hello,
an PayPal order received two payment complete events:
PDT complete
AND
IPN complete

This resulted in that the order status was set to completed two times and the customer received an e-mail two times.

Can you reproduce this issue?

Regards,
Ingo

**Comment by claudiulodro** [comment]
See https://github.com/woocommerce/woocommerce/issues/15773

Solution is to disable PDT in settings to avoid this.

**Comment by im1981** [comment]
Hello Claudio,

thank you very much.

Regards,
Ingo
