### ISSUE TITLE
Structured data errors i Product (not translated) and Review (Google tester reports error)

### ISSUE THREAD

**Issue by sailinf** [woocommerce/woocommerce#19470]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Multilingual site (in my case qTranslate but error would appear with any other translation plugin that uses __() and _e() functions for translation)
2. Create Woocommerce product with WC 3.3.4 (triggers errors 1 and prerequisite for error 2)
3. Add review (triggers error 2)
4. Analyse product with Google Structured data analyzer 

## Expected/actual behavior

Expected behavior:

When I follow those steps, I see...

Error 1, Product: untranslated strings in the 'name' and 'description' fields 
Error 2, Review: Google error for the review: "The review has no reviewed item specified."

I was expecting to see...

Error 1, Product: structured data "name" and "description" fields correctly translated into the language associated to the page tested (eg: site.example/en/... -> english translation)
Error 2, Review: Pass Google structured data test

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

The Product issue can be fixed by embedding the generation of the "name" and "description" fields with __() in public function generate_product_data(), tested on 3.3.3
No solution for the Review issues but Reviews did not have this problem in WC 2.6.14

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://dokkv20test.demo.site
Site URL: https://dokkv20test.demo.site
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: nginx/1.12.0
PHP Version: 7.0.26-1~dotdeb+8.2
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

All In One SEO Pack Pro: by Michael Torbert – 2.5.4.1
All in One SEO Pack & qTranslate-X: by qTranslate Team – 1.0
BackWPup: by Inpsyde GmbH – 3.4.4
bbPress: by The bbPress Community – 2.5.14
Cornerstone: by Themeco – 3.0.4
WPBakery Visual Composer & qTranslate-X: by qTranslate Team – 1.0
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.5
qTranslate slug: by Carlos Sanz Garcia
Pedro Carvalho – 1.1.19

qTranslate-X: by qTranslate Team – 3.4.6.8
Reveal IDs: by Oliver Schlöbe – 1.5.2
WooCommerce Bookings: by Automattic – 1.10.11 – 1.10.12 is available
Woocoomerce Extra Price Fields: by Webholics – 1.5.3
WooCommerce Stripe Gateway: by WooCommerce – 4.0.7
WooCommerce Product SKU Generator: by SkyVerge – 2.3.3 – Not tested with the active version of WooCommerce
WooCommerce & qTranslate-X: by qTranslate Team – 1.3 – Not tested with the active version of WooCommerce
WooCommerce TM Extra Product Options: by themeComplete – 4.6.6.1
WooCommerce: by Automattic – 3.3.4
WordPress File Monitor Plus: by Scott Cariss – 2.2
WP Google Maps - Pro Add-on: by WP Google Maps – 5.73
WPS Hide Login: by WPServeur
NicolasKulka
tabrisrp – 1.2.6.1

YITH WooCommerce Multi Vendor Premium: by YITHEMES – 2.4.4
YITH WooCommerce PDF Invoice and Shipping List Premium: by YITHEMES – 1.4.10 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #432 - /shop/
Basket: #3119 - /cart/
Checkout: #3209 - /checkout/
My account: #1440 - /customer-account/
Terms and conditions: #2445 - /terms-and-conditions/

### Theme ###

Name: X – Child Theme
Version: 1.0.0
Author URL: http://theme.co/
Child Theme: ✔
Parent Theme Name: X
Parent Theme Version: 6.0.4
Parent Theme Author URL: http://theme.co/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

x/woocommerce/loop/loop-end.php
x/woocommerce/loop/loop-start.php
x/woocommerce/loop/pagination.php
x/woocommerce/notices/error.php
x/woocommerce/notices/notice.php
x/woocommerce/notices/success.php
x/woocommerce/single-product/related.php
x/woocommerce/single-product/tabs/tabs.php
x/woocommerce/single-product/up-sells.php
x/woocommerce/single-product-reviews.php

````
![product errors](https://user-images.githubusercontent.com/8494281/37713626-288fbcfe-2d20-11e8-871e-8d8895f9c096.JPG)
![review error](https://user-images.githubusercontent.com/8494281/37713628-28bb59b8-2d20-11e8-9d9d-ef8ead2e43da.JPG)

</details>

**Comment by claudiulodro** [comment]
> Error 1, Product: untranslated strings in the 'name' and 'description' fields
> I was expecting to see...
> Error 1, Product: structured data "name" and "description" fields correctly translated into the language associated to the page tested (eg: site.example/en/... -> english translation)
> The Product issue can be fixed by embedding the generation of the "name" and "description" fields with __() in public function generate_product_data(), tested on 3.3.3

I don't think that's a good solution. It only makes sense to localize strings that WooCommerce can offer translations for, and we can't offer translations for product titles. Localizing the product title is a hack to get multilingual working properly with the plugin you are using. The better way would be to use the `woocommerce_structured_data_product` filter. 

Aditionally, the WooCommerce+qTranslate plugin you are using has not been updated in over 2 years, so it's not going to be up-to-date with any of this stuff.

> Error 2, Review: Google error for the review: "The review has no reviewed item specified."
> I was expecting to see...
> Error 2, Review: Pass Google structured data test

I haven't been able to reproduce this. Does it happen for you using a default theme like twentytwelve and with no plugins active other than WooCommerce? If so, can I please get a copy+paste or screenshot of the structured data generated?

<img width="816" alt="screen shot 2018-03-22 at 8 26 04 am" src="https://user-images.githubusercontent.com/7317227/37779922-cd465732-2daa-11e8-8dc8-4d57f49a9097.png">

**Comment by sailinf** [comment]
My bad on the Reviews, didn't think of the theme as a source of error :-(.
For the "name" and "description", these worked with translation turned on in 2.x so something has broken since? I know that the qTranslate plugin is obsolete but many other plugins use the same technique of hooking into __() and _e() so there would also break..

**Comment by mikejolley** [comment]
The translation plugin would need to filter the structured data. Using `__()` here would be invalid because the string is not fixed and thus translators cannot translate the string. This leads to errors with the POT files. Basically, using `__()` to translate dynamic strings is a hack we don't support.

Plugins (or yourself if dong it custom) can filter on `woocommerce_structured_data_product`, or just ensure the names are translated when returned from database depending on current language.
