### ISSUE TITLE
Default themes: Ajax loading spinner does not spin

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#19479]
Forum: https://wordpress.org/support/topic/loading-spinner-is-broken-not-animating/#topic-10092437-replies

I've tested with Twenty Fifteen, Twenty Sixteen, and Twenty Seventeen using the latest from the master branch.

Updating the cart, adding a coupon, entering an address, etc - all these actions have the ajax loading spinner pop up - but it doesn't actually spin. Storefront's spinner does work.

Also note that it's kinda hard to see locally on a fast site, so may need to add an artificial delay.

**Comment by mikejolley** [comment]
This works for me with 2016 - I only have the issue in 2017.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19507
