### ISSUE TITLE
Catalog Thumbnail sizes changes - WC 3.3

### ISSUE THREAD

**Issue by DvdRom87** [woocommerce/woocommerce#19489]
Since the changes to Image sizes in WC 3.3 i'm unable to set a max height of the thumbnails in the catalog.
I know it was by design to remove the height setting and only work with the width, but this way i cannot display the hole product in the thumbnail...

**First, here are screenshots of my old settings and the correct display of my thumbnails**
![chrome_2018-03-22_12-00-48](https://user-images.githubusercontent.com/37531154/37766905-b16b824e-2dc8-11e8-9bcf-c683ef3ca27b.png)
![chrome_2018-03-22_11-47-49](https://user-images.githubusercontent.com/37531154/37766413-2a1f035c-2dc7-11e8-8d60-a7a2672069c3.png)
As you can see, the hole product is displayed without any crop contained inside 250x250px.
 
Since the update i'm unable to get the hole product displayed, unless i choose the "Don't crop" setting.
_(You can see the problem with that down below)_ I could just use CSS to limit their height to 250px, but this would result in over-sized images (250x1000+) to be loaded and thus slowing down my site.
![chrome_2018-03-22_11-49-48](https://user-images.githubusercontent.com/37531154/37766415-2a5fbec4-2dc7-11e8-9f4f-c4308aff1145.png)

Now left are the 1:1 and custom crop option which are no use for me, because of our wide range of product sizes... (image below)
![chrome_2018-03-22_11-48-27](https://user-images.githubusercontent.com/37531154/37766414-2a3cce3c-2dc7-11e8-9486-2fa0befe8da1.png)

## Possible Solutions

- Bringing back the height setting
- 1:1, custom aspect ratio (**no crop**) option

**Comment by kloon** [comment]
Have you tried changing the thumbnail cropping to a custom one that fits your images? You can change these settings under `Appearance -> Customize` and then from the customizer going to `WooCommerce -> Product Images` http://cld.wthms.co/sXYKOi

**Comment by DvdRom87** [comment]
I'm sorry, but i don't think you understood the problem.

We have wide range of products that just don't fit into a single aspect ratio and i don't think we are the only one.

For example; try getting a pencil in a vertical and horizontal position displayed right now...
