### ISSUE TITLE
Can't submit the checkout form -  "We were unable to process your order, please try again"

### ISSUE THREAD

**Issue by MkBeeCtrl** [woocommerce/woocommerce#19487]
Morning people, 

I am writing to you as I just got stuck with submitting any kind of order. 
After adding at least one product to the cart and trying to checkout I receive 

 "We were unable to process your order, please try again"

I do have the following files customized:

1) form-checkout
2) form-login
3) payment

By customization I mean I have added different classnames to the <div> tags or drop in extra header or change the message text. Just the details (I have screens of those files), no big deal.

<img width="1319" alt="screen shot 2018-03-22 at 09 56 01" src="https://user-images.githubusercontent.com/10107362/37760576-6069a742-2db7-11e8-9612-a41340123bcc.png">
<img width="1015" alt="screen shot 2018-03-22 at 09 56 24" src="https://user-images.githubusercontent.com/10107362/37760577-60855a00-2db7-11e8-9532-b0138d7e4173.png">
<img width="1322" alt="screen shot 2018-03-22 at 09 56 36" src="https://user-images.githubusercontent.com/10107362/37760578-60a0b5b6-2db7-11e8-97a4-31d8631458c3.png">

Still my first approach was to deleted those files and try to complete the checkout process with default woocommerce files. It did fail as well.

I have the latest 3.3.4 version of WooCommerce.

## Prerequisites

**I have completed the following tasks before I went here:**
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] After reading some stackoverflow posts I did check if I have **wp_nonce_field( 'woocommerce-process_checkout', 'woocommerce-process-checkout-nonce' );** inluded. It's included.
- [x] JS console does not throw any errors
- [x] I checked if I have any plugins that have influence over the checkout process, in example payment plugin which I **turned off** and tried again with "pay with a check" option  --> I have left the shop in that state

## Steps to reproduce the issue
1) go here: http://woo1-bio.beectrl.net.pl/sklep-produkty/
2) pass: **bionitka**
3) add any kind of product to the cart
4) try to checkout filling out the form
5) you will see the bug, it's in polish 

<img width="1293" alt="screen shot 2018-03-22 at 10 10 28" src="https://user-images.githubusercontent.com/10107362/37761202-4f3a6b30-2db9-11e8-8d7d-f336306b664a.png">

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://woo1-bio.beectrl.net.pl
Site URL: http://woo1-bio.beectrl.net.pl
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pl_PL

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 7.0.27-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Całkowity rozmiar bazy danych: 7.33MB
Rozmiar bazy danych: 4.46MB
Rozmiar indeksu bazy danych: 2.87MB
wp_woocommerce_sessions: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.05MB
wp_woocommerce_order_items: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_order_itemmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB
wp_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB
wp_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB
wp_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB
wp_ajaxsearchpro: Dane: 0.02MB + Indeks: 0.00MB
wp_ajaxsearchpro_priorities: Dane: 0.02MB + Indeks: 0.00MB
wp_ajaxsearchpro_statistics: Dane: 0.02MB + Indeks: 0.00MB
wp_asp_index: Dane: 0.02MB + Indeks: 0.03MB
wp_commentmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_comments: Dane: 0.02MB + Indeks: 0.09MB
wp_links: Dane: 0.02MB + Indeks: 0.02MB
wp_options: Dane: 1.02MB + Indeks: 0.05MB
wp_postmeta: Dane: 2.38MB + Indeks: 1.84MB
wp_posts: Dane: 0.38MB + Indeks: 0.16MB
wp_smush_dir_images: Dane: 0.02MB + Indeks: 0.03MB
wp_termmeta: Dane: 0.05MB + Indeks: 0.03MB
wp_terms: Dane: 0.02MB + Indeks: 0.03MB
wp_term_relationships: Dane: 0.05MB + Indeks: 0.02MB
wp_term_taxonomy: Dane: 0.02MB + Indeks: 0.03MB
wp_usermeta: Dane: 0.02MB + Indeks: 0.03MB
wp_users: Dane: 0.02MB + Indeks: 0.05MB
wp_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB
wp_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB
wp_woof_query_cache: Dane: 0.02MB + Indeks: 0.02MB

### Post Type Counts ###

acf-field: 125
acf-field-group: 6
attachment: 136
customize_changeset: 2
dostawca: 10
nav_menu_item: 5
page: 9
post: 3
product: 67
product_variation: 126
revision: 127
shop_order: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌Twój sklep nie używa protokołu HTTPS. Dowiedz się więcej o HTTPS i certyfikatach SSL .
Hide errors from visitors: ❌Komunikaty o błędach nie powinny być widoczne dla użytkowników.

### Active Plugins (14) ###

Advanced Custom Fields PRO: przez Elliot Condon – 5.6.7
Ajax Search Pro: przez Ernest Marcinko – 4.11.5
Contact Form 7: przez Takayuki Miyoshi – 5.0.1
Custom Post Type UI: przez WebDevStudios – 1.5.7
Flexible Checkout Fields: przez WP Desk – 1.6.1
Genesis Connect for WooCommerce: przez StudioPress – 0.9.10 – Nietestowane z używaną wersją WooCommerce
Nginx Helper: przez rtCamp – 1.9.10
Zabezpieczenie hasłem: przez Ben Huson – 2.1
Redis Object Cache: przez Till Krüss – 1.3.5
WooCommerce: przez Automattic – 3.3.4
WordPress Importer: przez wordpressdotorg – 0.6.4
WP Smush Pro: przez WPMU DEV – 2.7.8
WPMU DEV Dashboard: przez WPMU DEV – 4.4
Custom Product Tabs for WooCommerce: przez YIKES
Inc. – 1.6.4 – Nietestowane z używaną wersją WooCommerce


### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Strona sklepu: #4 - /sklep-produkty/
Koszyk: #5 - /cart/
Zamówienie: #6 - /checkout/
Moje konto: #7 - /my-account/
Regulamin: #614 - /regulamin-sklepu-bionitka/

### Theme ###

Name: Genesis WooCtrl
Version: 1.0.0
Author URL: http://www.beectrl.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.5.3
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: genesis-wooctrl/woocommerce/archive-product.php wersja - jest nieaktualna. Bazowa wersja to 3.3.0
genesis-wooctrl/woocommerce/cart/cart.php
genesis-wooctrl/woocommerce/checkout/form-checkout.php
genesis-wooctrl/woocommerce/checkout/form-login.php
genesis-wooctrl/woocommerce/checkout/payment.php
genesis-wooctrl/woocommerce/content-product.php wersja - jest nieaktualna. Bazowa wersja to 3.0.0
genesis-wooctrl/woocommerce/content-single-product.php
genesis-wooctrl/woocommerce/loop/add-to-cart.php
genesis-wooctrl/woocommerce/loop/loop-end.php
genesis-wooctrl/woocommerce/loop/loop-start.php
genesis-wooctrl/woocommerce/loop/price.php
genesis-wooctrl/woocommerce/myaccount/form-login.php wersja - jest nieaktualna. Bazowa wersja to 3.3.0
genesis-wooctrl/woocommerce/single-product/related.php
genesis-wooctrl/woocommerce/single-product/up-sells.php
genesis-wooctrl/woocommerce/single-product.php

Outdated Templates: ❌Dowiedz się jak zaktualizować
`
```
</details>

**Comment by vlaskiz** [comment]
Going to be a plugin/theme issue most likely related to "Use relative scheme for AJAX endpoint to avoid errors when using a mix of HTTP and HTTPS.".

You should really test this with all plugins but WooCommerce disabled, as well as use default WP or Storefront theme.

**Comment by claudiulodro** [comment]
The only place that error shows up is if you have [no nonce or the wrong nonce when checking out](https://github.com/woocommerce/woocommerce/blob/release/3.3/includes/class-wc-checkout.php#L947). Looking at your screenshot it [looks like you are using the incorrect nonce](https://github.com/woocommerce/woocommerce/blob/release/3.3/templates/checkout/form-pay.php#L97) in the payment form.

**Comment by MkBeeCtrl** [comment]
@claudiulodro thanks for the tip regarding the nonce, but how can it be wrong if I copy pasted 
https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/payment.php
?

How can it be possible in such case, sorry but I am not following

**Comment by mikejolley** [comment]
This is from 3.4 Dev version. You are using 3.3. Different nonce.

**Comment by MkBeeCtrl** [comment]
@mikejolley thanks a lot for pointing that out. Somehow I missed that difference. After copying templates from the plugin directory everything worked fine.

@claudiulodro @vlaskiz thank you very much for your assistance as well.

**Comment by AceAutomation** [comment]
Hi MkBeeCtrl,
please, help, can you explain in detail what you did.. I've the same issue... Since I swict from HTTP to HTTPS. "We were unable to process your order, please try again"
Thanks
Rémi

**Comment by MkBeeCtrl** [comment]
@AceAutomation in my case it was because I was copying templates straight from github. Check the payment.php file in your plugins directory in Woocommerce. Once I have copied that file directly from my Wordpress FTP, the issue disappeared.

**Comment by AceAutomation** [comment]
@MkBeeCtrl Thanks a lot for your answer. Not resolved. I'm going to check some other ways.

**Comment by dipikamanni** [comment]
I know it is a old answer, but try using woo commerce default template 

Rename theme file : (/wp-content/themes/XXXXXXXXXX/woocommerce/checkout - payment.php)
And use default payment.php
