### ISSUE TITLE
Updating Plugin kills PHP code execution

### ISSUE THREAD

**Issue by OricTosh** [woocommerce/woocommerce#19490]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. login into WP-admin page for wordpress site
2. Goto updates, woocommerce plugin will be listed, as it needs an update.
3. click link required to update/install the plugin

## Expected/actual behavior

When I follow those steps, I see...
right hand side of wordpress  wp admin page shows PHP code.
I'm still logged in, click links results in code shown, not actual content expected
Viewing the site in another tab/browser. the page loads but it blank. The site has fallen over. 

I was expecting to see...

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
`
### WordPress Environment ###

Home URL: https://www.3dprintandstuff.co.uk
Site URL: https://www.3dprintandstuff.co.uk
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.5
PHP Post Max Size: 100 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.41.0
OpenSSL/1.0.2a

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_lify_
MaxMind GeoIP Database: ✔
Total Database Size: 17.19MB
Database Data Size: 15.33MB
Database Index Size: 1.86MB
wp_lify_woocommerce_sessions: Data: 4.58MB + Index: 0.12MB
wp_lify_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_lify_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_lify_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_lify_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB
wp_lify_woocommerce_order_itemmeta: Data: 0.03MB + Index: 0.03MB
wp_lify_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_lify_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_lify_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_lify_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp_lify_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_lify_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_lify_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_lify_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_lify_ac_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wp_lify_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB
wp_lify_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wp_lify_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB
wp_lify_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_lify_comments: Data: 0.05MB + Index: 0.03MB
wp_lify_duplicator_packages: Data: 0.02MB + Index: 0.00MB
wp_lify_links: Data: 0.00MB + Index: 0.00MB
wp_lify_nf_objectmeta: Data: 0.00MB + Index: 0.00MB
wp_lify_nf_objects: Data: 0.00MB + Index: 0.00MB
wp_lify_nf_relationships: Data: 0.00MB + Index: 0.00MB
wp_lify_ninja_forms_fav_fields: Data: 0.02MB + Index: 0.00MB
wp_lify_ninja_forms_fields: Data: 0.00MB + Index: 0.00MB
wp_lify_options: Data: 3.38MB + Index: 0.18MB
wp_lify_postmeta: Data: 0.82MB + Index: 0.37MB
wp_lify_posts: Data: 1.94MB + Index: 0.10MB
wp_lify_termmeta: Data: 0.01MB + Index: 0.02MB
wp_lify_terms: Data: 0.01MB + Index: 0.04MB
wp_lify_term_relationships: Data: 0.02MB + Index: 0.04MB
wp_lify_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_lify_usermeta: Data: 0.04MB + Index: 0.03MB
wp_lify_users: Data: 0.00MB + Index: 0.01MB
wp_lify_w3tc_cdn_queue: Data: 0.00MB + Index: 0.00MB
wp_lify_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_lify_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_lify_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_lify_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
wp_lify_wfBlockedIPLog: Data: 0.01MB + Index: 0.01MB
wp_lify_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_lify_wfBlocks7: Data: 0.00MB + Index: 0.00MB
wp_lify_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_lify_wfConfig: Data: 1.23MB + Index: 0.01MB
wp_lify_wfCrawlers: Data: 0.00MB + Index: 0.00MB
wp_lify_wfFileChanges: Data: 0.00MB + Index: 0.00MB
wp_lify_wfFileMods: Data: 1.16MB + Index: 0.25MB
wp_lify_wfHits: Data: 0.93MB + Index: 0.26MB
wp_lify_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_lify_wfIssues: Data: 0.01MB + Index: 0.01MB
wp_lify_wfKnownFileList: Data: 0.57MB + Index: 0.08MB
wp_lify_wfLeechers: Data: 0.07MB + Index: 0.06MB
wp_lify_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_lify_wfLocs: Data: 0.00MB + Index: 0.00MB
wp_lify_wfLogins: Data: 0.11MB + Index: 0.03MB
wp_lify_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_lify_wfNotifications: Data: 0.04MB + Index: 0.01MB
wp_lify_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_lify_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_lify_wfScanners: Data: 0.00MB + Index: 0.01MB
wp_lify_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_lify_wfStatus: Data: 0.11MB + Index: 0.05MB
wp_lify_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_lify_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_lify_yoast_seo_links: Data: 0.03MB + Index: 0.01MB
wp_lify_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 212
feedback: 17
ml-slider: 1
nav_menu_item: 37
nf_sub: 68
page: 14
post: 11
product: 90
product_variation: 33
revision: 402
shop_coupon: 3
shop_order: 46
shop_order_refund: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Disqus for WordPress: by Disqus – 3.0.15
Duplicator: by Snap Creek – 1.2.34
Enhanced E-commerce for Woocommerce store: by Tatvic – 2.0.0 – Not tested with the active version of WooCommerce
FooBox Image Lightbox: by FooPlugins – 2.5.2
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.3.1.1
Jetpack by WordPress.com: by Automattic – 5.9
Maintenance: by fruitfulcode – 3.6.1
MetaSlider Lightbox: by Team Updraft – 1.10.1
MetaSlider: by Team Updraft – 3.7.2
Ninja Forms: by The WP Ninjas – 3.2.16
W3 Total Cache: by Frederick Townes – 0.9.6
WooCommerce Product Slider Pro: by ShapedPlugin – 1.3.4 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.4
Wordfence Security: by Wordfence – 7.1.1
Yoast SEO: by Team Yoast – 7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #1084 - /3d-print-stuffs-shop
Basket: #5 - /cart
Checkout: #6 - /checkout
My account: #7 - /my-account
Terms and conditions: #100 - /terms-and-conditions

### Theme ###

Name: Storefront
Version: 2.2.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by OricTosh** [comment]
Placing a hash tag within the htacess file and in front of the line for the site's PHP handler fixes the site, thus brings the site back up and working as before. Upon the next update of plugin, i thinking it will crash the site again. So placing a hash tag in htacess is a possible work around but not fixing the cause as it's happened before with previous plugin updates

**Comment by peterfabian** [comment]
Hi Chris,

Have you tried to compare the htaccess file before and after the upgrade of WooCommerce plugin? Could it be that the server configuration you're running on was updated that caused the conflict?

I was not really able to reproduce this problem. 
Can you please post the line that you had to comment out in your htaccess file to fix your problem?

Also, there were no changes in the htaccess-related code in 3.3.4, so I would find it quite strange that it's a problem in the latest WooCommerce version.

It would help if you could post some more details on how to reproduce this problem. 
Can you also include a screenshot of the problem, and copy the code you see here into the bug report so that we can have a look?
Otherwise we would have to close it as not reproducible.

Thanks!

**Comment by OricTosh** [comment]
Thanks for response. It only happens when a woo commerce plugin update is applied. When the plugin restarts, pages within wp-admin show code and the site, shows a blank page. It's happened on the last 3 updates of the plugin. placing a hash tag upon this line in htacess #AddHandler application/php-70 .php 
fixes this issue. The line was copied and pasted from htacess, seems strange to me that there is whitspace between 70 and <dot>php which might be a file-name. 

Is that a correct line for a php AddHandler line?

I'm not sure when the next woo update comes, that when I update it at that time the site will stay up.
If I was able to roll-back the plugin so not on the current version 3.3.4 and then apply the update. It might break the site and I would be able to provide screen-shots. 
How does one rollback a plugin's update?

**Comment by peterfabian** [comment]
Hi, 

I've found that someone else had a similar problem some time ago: https://wordpress.org/support/topic/after-update-it-writes-a-line-that-glitches-wp/
The line in .htaccess that you posted is telling the webserver to use php 7 to process files with .php extension, but that does not seem to work properly (maybe there is no handler for application/php-70 on the server when you have your website). I think it might be worth checking this with your hosting provider to see how it should be configured. 

But WooCommerce does not change the `AddHandler` settings in .htaccess file, so it must be some other plugin/process that injects this to your .htaccess. 
Maybe you can search through the php files on your hosting to see if there is a script which contains `AddHandler`?

I would say it's better _not_ to downgrade if the workaround works for you. Please let us know by posting screenshots here if it happens again when upgrading to 3.3.4.

**Comment by peterfabian** [comment]
Since this is not a WooCommerce core issue, I will close this one. Please follow up with hosting or identify the code that causes this problem.

**Comment by OricTosh** [comment]
Just updated the woo-commerce plugin to 3.3.5 and it crashed the site again. The hashtag that was in  htaccess was removed. Adding back a hash tag fixed the problem. Added screen shots. it displayed after clicking a option upon the left column 
![update](https://user-images.githubusercontent.com/1838646/38645638-af4018e4-3ddc-11e8-9ad2-ae526215e135.png)
![update2](https://user-images.githubusercontent.com/1838646/38645705-eea28256-3ddc-11e8-9bef-eb872d7dbdf8.png)
Please re-open and advise, Thanks

**Comment by OricTosh** [comment]
Just updated the woo-commerce plugin to 3.3.5 and it crashed the site again. The hash tag that was in htaccess was removed. Adding back a hash tag fixes this issue and site comes back up. Added screen shots. they are displayed after clicking an option upon the left column. Please re-open and advise, thanks

![update2](https://user-images.githubusercontent.com/1838646/38646244-0fdd1880-3ddf-11e8-93f5-51aadd20012f.png)
![update](https://user-images.githubusercontent.com/1838646/38646246-100a1dbc-3ddf-11e8-9f62-8593f62dca66.png)

**Comment by mikejolley** [comment]
You need to ask your host if they have a mechanism to add that htaccess rule. We do not.
