### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by majeytunio** [woocommerce/woocommerce#19499]
I have downloaded plugin from Wordpress plugins and when I came to activate it show me the message with Fatal error of class not found for file abstract-wc-rest-controller.php on line number 20.

I thought it maybe the issue from Wordpress store and came here on github I downloaded fresh copy of woocommerce from github and when I came to activate plugin it says the same issue. I posting issue line.

Fatal error: Class 'WP_REST_Controller' not found in D:\Majid-Platform\htdocs\index\gharwala.pk\wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-rest-controller.php on line 20

**Comment by claudiulodro** [comment]
You have the WordPress REST API disabled. It's required for WooCommerce. I don't know which method of disabling it you are using, but that is the issue.
