### ISSUE TITLE
HTML not escaped in product title

### ISSUE THREAD

**Issue by dademaru** [woocommerce/woocommerce#19491]
Hi,

even if it's a bad practice, it happens that editors/store managers use **HTML tags inside titles** –
e.g. a `<br>` to break in more lines a long title or a `<small></small>` to style a more or less relevant part.

This can cause **output issues** every time the title is used in contexts other than default HTML title (e.g. in link title attributes, data-attributes, …), where HTML tags shouldn't be placed.

WC 3+ uses `$product->get_name()` – which has no hook to escape HTML.
However, in most cases, **HTML is escaped** with `sanitize_title( $product->get_name() )` or `esc_html ( $product->get_name () )`.
But in some cases, e.g.  various`add_to_cart_description()`, **HTML is not escaped**, and it may break the output.

There may be other cases where it is not escaped, you may check if, every time `$product->get_name()` is used, it's better to escape HTML or leave it to output in DOM, whenever
editors put HTML tags in the title.

Thanks

**Comment by GlennMartin1** [comment]
Why do you consider this "bad practice"?

I use both `br` and `small` in titles, such as: https://www.hometowntrailers.com/product/dump-lowprofile-ultimate-gooseneck-82-x-14-16800-gvwr/

Is there a reason not to?

**Comment by peterfabian** [comment]
Hi dademaru, 

Since HTML tags are allowed in title, WooCommerce has to accept it, too.
I've looked through the uses of `add_to_cart_description` in core and could not see where it would send unescaped output. If you find such instances, please report it as a bug.

Thanks

**Comment by dademaru** [comment]
@GlennMartin1
I consider it a bad practice if you haven't total control of the output in all the possible context: 
I suppose you add those tags to style the title in specific places (e.g. single product title, shop loop product title) but you can't be sure it will be escaped in contexts different than those (e.g. in breadcrumbs, emails, link title attribute, aria-label, …).
For example, in past I had a similar issue with YOAST SEO breadcrumbs, and I had to hide `<br>` via CSS to avoid breaking the breadcrumbs output – while in current version `<br>` or other tags are correctly escaped.
Concerning your example, if there was a link title attribute (`<a title="…">`) unescaped, your product may display this popup:
![html-tags-in-title](https://user-images.githubusercontent.com/1826139/37796151-de238c02-2e16-11e8-9dc4-ad5bfdc5ac75.jpg)
(which is not the best in terms of user experience when the user mouseovers the product).
Anyway, I used HTML tags in title too, but I was just pointing out that, perhaps, in some cases it would be better to escape those tags and prevent possible issues.

@peterfabian thanks for closing the issue or assigning '**Invalid / Duplicate**' label without let me answer you or show where it may cause unexpected behavior ;-)
![html-tags-aria-label](https://user-images.githubusercontent.com/1826139/37796247-17e835be-2e17-11e8-945a-76fd59e6de0c.png)
I suppose it's not exactly in accordance in terms of **accessibility** with **aria-label** purpose displaying a title with HTML tags to assistive technologies.
 [Here](https://docs.woocommerce.com/wc-apidocs/source-class-WC_Product_Simple.html#69) for example it's not escaped

Cheers

**Comment by mikejolley** [comment]
Is this the only example? Escaping and stripping tags are different things. In the area case we could strip. But it should be handled on output.

**Comment by dademaru** [comment]
Hi Mike,
yes, this is the case I found.
I inspected the code to check whether, when using `$product->get_name()`, it's escaped / sanitized / HTML stripped or not, and as I wrote before, often you are using `sanitize_title( $product->get_name() )` or `esc_html ( $product->get_name () )` but in that case you aren't and, maybe, it would be more appropriate.

What do you mean:
> but it should be handled on output
going back from `/templates/loop/add-to-cart.php` I found these hooks: [woocommerce_loop_add_to_cart_link](https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=woocommerce_loop_add_to_cart_link), [woocommerce_loop_add_to_cart_args](https://docs.woocommerce.com/wc-apidocs/source-function-woocommerce_template_loop_add_to_cart.html#853-882), and, as mentioned before, [woocommerce_product_add_to_cart_description](https://docs.woocommerce.com/wc-apidocs/source-class-WC_Product_Simple.html#69) (which is a bit different for each product type).
The last one is not to handle the output?

However, I had no intention of being polemical.
I was just observing that, perhaps, we could check and verify if there are cases in which it would be more appropriate escaping / sanitizing / stripping HTML tags from title or leave them.

Thanks

**Comment by peterfabian** [comment]
Hi dademaru, 

Maybe I'm missing something, but in the case you mentioned, I can see the `templates/loop/add-to-cart.php` escapes the attribute `aria-label`: https://github.com/woocommerce/woocommerce/blob/master/templates/loop/add-to-cart.php#L30
 
via calling `wc_implode_html_attributes`:
https://github.com/woocommerce/woocommerce/blob/master/includes/wc-formatting-functions.php#L1343

Could it be your theme overriding it?

I think what is meant by 
> it should be handled on output

is described in [securing output](https://developer.wordpress.org/themes/theme-security/data-sanitization-escaping/#escaping-securing-output) section of WP handbook, but basically it says that output should be escaped as late as possible, e.g. when `echo`-ing it, etc.

**Comment by dademaru** [comment]
Hi @peterfabian 
thanks for explaining the output sentence.
Honestly I missed the `esc_attr( $value )` in `wc_implode_html_attributes()`.
Anyway, I've tested with WC 3.3.4 & Storefront and HTML tags are outputted in products aria-label on shop page.
Have you tested too with HTML tags in product titles?
Maybe, since it's different escaping from stripping tags, as @mikejolley rightly stated, those tags are still outputted.
Thanks

**Comment by mikejolley** [comment]
@peterfabian We can just add strip_tags for this one instance (when the aria tag is added in the loop template file). Thats all the action we need to take here.

**Comment by dademaru** [comment]
@mikejolley thanks
