### ISSUE TITLE
I am having an issue with cart updation after successful payment with PayPal. My cart is not getting updated and still the product is in my cart.

### ISSUE THREAD

**Issue by kurianic** [woocommerce/woocommerce#19506]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Really this depends on the `PayPal` gateway you're using - there are several. 

If it's ours, it won't clear unless IPN/PDT comes back and updates the order. You may want to turn on PDT https://docs.woocommerce.com/document/paypal-standard/#section-29

Thanks

**Comment by kurianic** [comment]
@mikejolley  PDT was on and still, the issue is there. My payment is success.

**Comment by kurianic** [comment]
@mikejolley  i have got this error from log
INFO Received invalid response from PayPal PDT
