### ISSUE TITLE
Cannot get taxonomy with unicode text ( url encoded )

### ISSUE THREAD

**Issue by Merujan99** [woocommerce/woocommerce#19501]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. When We create a attribute with hebrew text is saves it as pa_UrlEncodedText, for example pa_%d7%9e%d7%99%d7%93%d7%94
2. When we try to get taxonomy by this, wordpress return false,
```php
$tax = get_taxonomy( 'pa_%d7%9e%d7%99%d7%93%d7%94' ); 
bool(false)
```
3. If we decode it manually, and try to get it returns the WP_Taxonomy class
```php
$tax = get_taxonomy( 'pa_מידה' );
class WP_Taxonomy#12505 (24)
```

**Comment by mikejolley** [comment]
`get_taxonomy` is a WordPress function so what you're reporting isn't a WooCommerce problem. I'd expect WP to want the raw value so it can apply it's own sanization. Using `pa_מידה` therefore makes sense when getting the value, so when handling strings such as `pa_%d7%9e%d7%99%d7%93%d7%94` you just need to ensure you urldecode first (like WooCommerce does).

Thanks
