### ISSUE TITLE
Product variations with `manage_stock` set to false returns string "parent" instead of boolean

### ISSUE THREAD

**Issue by bkeyoumarsi** [woocommerce/woocommerce#19500]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product variation
2. Set `manage_stock` to false
3. Call `/wp-json/wc/v2/products/<product-id>/variations` and observer that the boolean field `manage_stock` is set to string `"parent"`

## Expected/actual behavior

When I follow those steps, I see `manage_stock` set to a string value

I was expecting to see a boolean value as it is documented and conforms to when that field is set to `true`

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
@claudiosanches docs issue or needs converting?

**Comment by claudiosanches** [comment]
@mikejolley need improve documentation, problem the schema too.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19598
