### ISSUE TITLE
Suggestion: My Account page UI improvement?

### ISSUE THREAD

**Issue by phj123** [woocommerce/woocommerce#19518]
Suggestion: I think it will be a UI improvement and will streamline checkout & account page if woocommerce will hide the change password fields on the my account page and make them appear with a checkbox asking: Change Password? Same way this is happening at checkout with the ship to different address fields: Ship to a different address?

This way the password change label texts can leave the long (LEAVE BLANK TO LEAVE UNCHANGED)...

It is a small change but will, in my opinion, make the page overview clearer for customers especially on small screens, Any thoughts on this?

**Comment by vlaskiz** [comment]
Disagree.

I rarely, if ever have seen password fields hidden and shown optionally with a checkbox like that on any page/service I've used.

Plus this is not hard to do by editing template files slightly.

**Comment by phj123** [comment]
Yes i definitely will implement it myself but thought it could be beneficial for everyone..

**Comment by mikejolley** [comment]
I think this one will divide options so it's likely better to show by default and allow customisations to hide those fields if they want to implement a checkbox. Perhaps make a snippet and share it if you'd like to help others?

If you want feedback on the change or maybe to see how 'wanted' it is, I'd post it up on ideas.woocommerce.com or make it into a plugin and see many installs it attracts.

We have an issue already logged to look at all checkout screens later in the year fro redesign work.

Thanks

**Comment by phj123** [comment]
Thank you for your reply mike, I will :)
