### ISSUE TITLE
Product Export does not escape Double Quotes preceded by Backslashes

### ISSUE THREAD

**Issue by CaptainFord** [woocommerce/woocommerce#19514]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create or edit a product
2. Copy and paste the following line into the description field:
[Start]
`This is a quote: "Lorem Ipsum". And this is broken:  \" ,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p `
[End]
3. Save the product
3. Export all products to a CSV file
4. Open the CSV file as text and observe that the quotes around "Lorem Ipsum" are escaped, but the one preceded by a backslash is not.
5. (Optional) Open the CSV file in excel/libreoffice calc and observe that the "a,b,c,d,e...etc" list separated by columns is split into separate fields

**_(This is a bug in fputcsv in PHP itself! See comments below!)_**

## Expected/actual behavior

**When I follow those steps, I see...**
All double-quotes are being escaped by being replaced by two double-quotes UNLESS they are preceded by a backslash.

**I was expecting to see...**
All double-quotes should be escaped by being replaced by two double-quotes. (" -> "") 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## Further details

This is a [known problem](https://stackoverflow.com/questions/26840256/fgetcsv-fputcsv-escape-parameter-fundamentally-broken) with fputcsv. See the [bug report](https://bugs.php.net/bug.php?id=50686) on this issue marked as "won't fix" by the dev team of PHP.

This issue occurs for me because Visual Composer is generating code within comments that uses backslash escaping of double quotes. Among other things, it means WooCommerce cannot import its own export files.

Also see [this article](https://aj.garcialagar.es/blog/2016/04/04/what-is-wrong-with-csv-in-php/), which includes a replacement library for csv exporting.

I *think* this could be solved by simply doubling all backslashes before sending it to fputcsv. But the fact I can't find a reference to someone doing this makes me wonder if I'm missing something.

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://wp.localhost
Site URL: http://wp.localhost
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.14 (Win32) DAV/2 mod_ssl/2.2.14 OpenSSL/0.9.8l mod_autoindex_color PHP/5.3.1 mod_apreq2-20090110/2.7.1 mod_perl/2.0.4 Perl/v5.10.1
PHP Version: ❌ 5.3.1 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 60
PHP Max Input Vars: 
cURL Version: 
SUHOSIN Installed: –
MySQL Version: ❌ 5.1.41 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 0.15MB
Database Data Size: 0.06MB
Database Index Size: 0.09MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.06MB + Index: 0.02MB
wp_postmeta: Data: 0.00MB + Index: 0.01MB
wp_posts: Data: 0.00MB + Index: 0.01MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

page: 5
post: 2
product: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Services: by Automattic – 1.12.1
WooCommerce: by Automattic – 3.3.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by CaptainFord** [comment]
This came about because Visual Composer generates code that can include backslash-escaped quotes inside its custom tag's attributes. Escaping for CSV is so simple that I'm really curious how this came about.

**Comment by CaptainFord** [comment]
I couldn't help myself. I dug in and found it just uses PHP's fputcsv. This is actually the default intended behavior when you don't specify an escape character parameter.

Why does it even have an escape character parameter for writing out? Is it safe to change this behavior or is there a use case I'm not seeing? In any case, it does not work for this use case. Even if backslash was an escape character, I would then need the backslashes to be escaped, since the backslash-double-quote sequence is in fact part of the content.

Am I going to need to write a plugin just to double all backslashed double quotes or could we simply specify null for the escape_character argument?

**Comment by claudiulodro** [comment]
I've looked into this and how other open source platforms with CSV importer/exporters and WP CSV import/export plugins are handling it and I see a few possible options:
1. Do nothing. If you export a product with that breaking description string then import it, everything seems to work OK (the backslash is missing in the description on import, but the product still imports OK). Other platforms and plugins don't seem to have any special CSV handling to deal with this problem. This is the first complaint about this since the importer/exporter released in June, so it's not a widespread issue. PHP will probably eventually properly follow RFC4180.
2. Use a library that follows RFC4180. The one linked in the issue may work or [this one looks mature and well-maintained](https://github.com/parsecsv/parsecsv-for-php). Libraries will have to be evaluated for PHP version compatibility (parsecsv requires PHP 5.5+).

Adding special handling for `\"` in our importer/exporter (e.g. doubling backslashes or doubling quotes) will most likely not work without breaking compatibility somewhere, otherwise it would have been fixed in PHP if it were that simple.

If there isn't a straightforward solution, let's [discuss this in the next dev chat](https://woocommerce.wordpress.com/tag/dev-chat/).

**Comment by CaptainFord** [comment]
> PHP will probably eventually properly follow RFC4180.

Maybe? I hope so. But the bug has existed since 2003, was only reported in 2010, and still hasn't been fixed in 2018. I'm not so sure.

> If you export a product with that breaking description string then import it, everything seems to work OK.

Umm...here:

[Check out what I get when I export](https://www.americasbestflowers.com/bug-reports/wc-product-export-for-bug-report.csv). Look carefully at that first row. Can you tell what the barcode in the last column is supposed to be for that first product?

Notice how none of the other products have any values in most of the meta columns? Yeah, that first product doesn't either. Those columns should be blank?

Notice how the data for that first product extends several hundred columns past the valid columns on the spreadsheet?

As you can probably guess, this would be kind of destructive to re-import.

**Comment by mikejolley** [comment]
Thanks for explaining how to replicate. Closing this in favour of https://github.com/woocommerce/woocommerce/pull/19678 which works around it. Feedback welcome in the PR.
