### ISSUE TITLE
Background processing doesn't work behind a password protected site

### ISSUE THREAD

**Issue by createandcode** [woocommerce/woocommerce#19512]
I've got a staging site running WC3.3 and I couldn't figure out why thumbnails weren't being generated.
The staging site sits behind a simple htaccess style user/pass (actually done with nginx auth_basic_user_file) 

Running the Background Processing Test in Status->Tools fails when the user/pass dialog is in place. 

A couple of questions/suggestions:
- can the background test be made smarter to detect the presence of a user/pass? I'm guessing many WC staging stores sit behind password gateways and probably don't realise the impact of this (especially with more things moving to background processes)
- for now I've had to deactivate my password protection - which is not ideal - is there some way to add constants for usernames/passwords to allow background jobs to run whilst the site is password protected?

I would also highly recommend highlighting this in the docs to save people time troubleshooting issues with background processing failures in future :)

**Comment by mikejolley** [comment]
Thanks. I've added this to the WIKI https://github.com/woocommerce/woocommerce/wiki/Thumbnail-Image-Regeneration-in-3.3
