### ISSUE TITLE
Table Rate Shipping Values in woocommerce

### ISSUE THREAD

**Issue by basanthalluri** [woocommerce/woocommerce#19536]
Hi Everyone,

I am using the Table Rate Shipping plugin in the woocommerce website.

https://codecanyon.net/item/table-rate-shipping-for-woocommerce/3796656

How can get the Table Rate Shipping values set in the admin via woocommerce rest api?

Thanks

**Comment by mikejolley** [comment]
Shipping cannot be calculated from REST API - thats not a feature we currently have.

**Comment by Adetiwa** [comment]
Hello Mikejolley,

Please confirm if you now have the shipping calculation especially for Table rates on the rest APIs.

Thank you.

**Comment by mikejolley** [comment]
@Adetiwa no not in the core rest api.
