### ISSUE TITLE
last version of woocomerce do some issues in my web site

### ISSUE THREAD

**Issue by simobeen** [woocommerce/woocommerce#19544]
i update my woocomerce in my website afret that show up some issues in my products price and add button and wordpress dachboardi update my woocomerce in my website afret that show up some issues in my products price and add button and wordpress dachboard

i need some help please i have to solve this urgently
![issues](https://user-images.githubusercontent.com/37839323/37971983-313e98ee-31cf-11e8-8d4b-696f2438d9d7.PNG)
![issue](https://user-images.githubusercontent.com/37839323/37971994-36e319f0-31cf-11e8-9978-4ee5e07a459b.PNG)

**Comment by michaeltieso** [comment]
See https://github.com/woocommerce/woocommerce#support

**Comment by mikejolley** [comment]
^ please use the helpdesk
