### ISSUE TITLE
System Status recommended/required notices

### ISSUE THREAD

**Issue by michaeltieso** [woocommerce/woocommerce#19546]
![screenshotwordpress](https://user-images.githubusercontent.com/1500606/37980581-b8dc6d1e-31eb-11e8-95b9-dcb33628c966.png)

Perhaps redundant to the notice above but couldn't hurt to display a warning to update to the latest WP version, similar to what's being shown for MySQL version.

<img width="898" alt="screen shot 2018-03-27 at 18 26 48" src="https://user-images.githubusercontent.com/1500606/37980860-72aa05a8-31ec-11e8-9fbb-0fc4779cfa34.png">

PHP version showing green on 5.6 while WordPress docs [recommends 7.2](https://wordpress.org/about/requirements/). It will at least encourage people to look into it with their host if we set the bar at 7.2. Notice that in my screenshot it _recommends_ MySQL 5.6 or greater. Let's do the same for PHP.

What do you think?

Edit: One last thing. Might help to spell out WordPress and WooCommerce for those not familiar with that abbreviation.

**Comment by pmgarman** [comment]
I agree

Maybe PHP <5.6 should be red, 5.6 maybe make orange/yellow, 7+ green.

**Comment by claudiulodro** [comment]
@claudiosanches may be a good place to put a warning about https://github.com/woocommerce/woocommerce/issues/19548 too
