### ISSUE TITLE
Documentation lacks clarity

### ISSUE THREAD

**Issue by apb1963** [woocommerce/woocommerce#19547]
Maybe I'm being overly pedantic, but https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Commands#wc-product_cat-list fails to specify that pagination is on by default and that --per_page is REQUIRED in order to get more than one "page" of results, where "page" is of undocumented arbitrary length, apparently 10.

When I use the parameter with my known total list size of 21, the page returned while obviously greater than without said parameter, still fits on one page of my monitor.  So how it could be returning a "page" when there are more results that will easily fit on the screen, is strange to my way of thinking.  Half a page is not a page unless it's documented as such, which it is not as already stated above.  A good design should take the size of my screen into account when auto-paginating rather than an arbitrary number, as this information is readily available from the OS.

Additionally, it does not specify how to get ALL results but implies I need to know the number of results in advance in order to get the whole list.  This should be stated either explicitly and/or by way of example both always preferred.

Further  --context fails to  specify possible contexts or scopes.  
All defaults should be  documented. 
"--image  Image data" wherever specified, is vague.   image data is the binary contents of an image file.  I suspect that the  docs mean to say "image file name" and/or "URI", everything always with  examples for those that need them.

Keep up the great work!

**Comment by apb1963** [comment]
Things I neglected to mention.  1) --context Fails to specify possible contexts or scopes.  2) All defaults should be documented. 3) "--image  Image data" wherever specified, is vague.  image data is the binary contents of an image file.  I suspect that the docs mean to say "image file name" and/or "URI", everything always with examples for those that need them.

**Comment by claudiulodro** [comment]
I believe the correct behavior would be to list **all** products when `--per_page` is not specified. This is how [wp-cli handles it for regular posts](https://developer.wordpress.org/cli/commands/post/list/#examples), so we should mirror that. I don't think it should be based on the screen size, as one of the main uses of the CLI is for automated scripts which often aren't even on a screen.

> Further --context fails to specify possible contexts or scopes.
All defaults should be documented.
"--image Image data" wherever specified, is vague. image data is the binary contents of an image file. I suspect that the docs mean to say "image file name" and/or "URI", everything always with examples for those that need them.

This documentation should be added/clarified in the wiki also. 👍

**Comment by apb1963** [comment]
wp help post list (and presumably the wiki too), does not specify acceptable values for post_type.  I was unaware of the "any" type until now.

**Comment by willgorham** [comment]
@apb1963 These are standard WP Query parameters I believe. See: https://codex.wordpress.org/Class_Reference/WP_Query#Type_Parameters
