### ISSUE TITLE
coupon user email limit Error

### ISSUE THREAD

**Issue by angelrabbit** [woocommerce/woocommerce#19554]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [x ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. add a coupon and on tab "Usage restriction" set up "Email restrictions" to any email

## Expected/actual behavior

When I follow those steps, I see...

I can use this coupon with any email address

I was expecting to see...

I can use the coupon when my email address is as same as 
"Email restrictions".

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
		WordPress environment
		--
		Home URL: |   | http://angel.tw-brand.net/wp485
		Site URL: |   | http://angel.tw-brand.net/wp485
		WC version: |   | 3.1.1
		Log directory writable: |   | /home/wptwbrand/public_html/wp485/wp-content/uploads/wc-logs/
		WP version: |   | 4.8.5
		WP multisite: |   | –
		WP memory limit: |   | 368 MB
		WP debug mode: |   | –
		WP cron: |   |  
		Language: |   | zh_TW

		Server environment
		--
		Server info: |   | Apache
		PHP version: |   | 5.6.34
		PHP post max size: |   | 8 MB
		PHP time limit: |   | 30
		PHP max input vars: |   | 1000
		cURL version: |   | 7.54.0, OpenSSL/1.0.2k
		SUHOSIN installed: |   | –
		MySQL version: |   | 5.6.39
		Max upload size: |   | 8 MB
		Default timezone is UTC: |   |  
		fsockopen/cURL: |   |  
		SoapClient: |   |  
		DOMDocument: |   |  
		GZip: |   |  
		Multibyte string: |   |  
		Remote post: |   |  
		Remote get: |   |  

		Database
		--
		WC database version: |   | 3.1.1
		Database prefix |   | wp_
		woocommerce_sessions |   |  
		woocommerce_api_keys |   |  
		woocommerce_attribute_taxonomies |   |  
		woocommerce_downloadable_product_permissions |   |  
		woocommerce_order_items |   |  
		woocommerce_order_itemmeta |   |  
		woocommerce_tax_rates |   |  
		woocommerce_tax_rate_locations |   |  
		woocommerce_shipping_zones |   |  
		woocommerce_shipping_zone_locations |   |  
		woocommerce_shipping_zone_methods |   |  
		woocommerce_payment_tokens |   |  
		woocommerce_payment_tokenmeta |   |  
		MaxMind GeoIP database: |   | The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the 

		WC pages
		--
		Shop base: |   | #4 - /shop/
		Cart: |   | #5 - /cart/
		Checkout: |   | #6 - /checkout/
		My account: |   | #7 - /my-account/

		path: /home/wptwbrand/public_html/wp485/wp-content/uploads/GeoIP.dat. Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Coun

		Active plugins (2)
		--
		Limit Login Attempts |   | by Johan Eenfeldt – 1.7.1
		WooCommerce |   | by Automattic – 3.1.1 – 3.3.4 is available

		Settings
		--
		API enabled: |   |  
		Force SSL: |   | –
		Currency |   | TWD (NT$)
		Currency position |   | left
		Thousand separator |   | ,
		Decimal separator |   | .
		Number of decimals |   | 2
		Taxonomies: Product types |   | external (external), grouped (grouped), simple (simple), variable (variable)
		Taxonomies: Product visibility |   | exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)

		WC pages
		Shop base:		#4 - /shop/
		Cart:		#5 - /cart/
		Checkout:		#6 - /checkout/
		My account:		#7 - /my-account/

		Theme
		Name:		Storefront
		Version:		2.2.8
		Author URL:		https://woocommerce.com/
		Child theme:		 – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
		WooCommerce support:	v	

				
		Templates
		Overrides:

</details>

**Comment by kloon** [comment]
HI, this is intended behaviour. You will see that the check is done as soon as you try and place the order. The reason we do the check only then is to accommodate for guest checkouts and users not logged in yet when adding to cart or placing the orders.

The discount will be removed when you try and place the order with an email not in the list.

**Comment by angelrabbit** [comment]
thank you very much.
