### ISSUE TITLE
Red dots appear under asterisk at checkout

### ISSUE THREAD

**Issue by bondimedical3** [woocommerce/woocommerce#19565]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add an item to the cart and proceed to the checkout
2.
3.

## Expected/actual behavior

When I follow those steps, I see... 2 or 3 red dots under the
![checkout](https://user-images.githubusercontent.com/10808588/38071981-04bfe7ee-3370-11e8-8161-f5d06d8eaff3.jpg)
 red asterisk

I was expecting to see... only a red asterisk

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```

WC version: |   | 3.3.4
-- | -- | --
Log directory writable: |   | /home/gu/public_html/wp-content/uploads/wc-logs/
WP version: |   | 4.9.4
WP multisite: |   | –
WP memory limit: |   | 768 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US


```
</details>

**Comment by mikejolley** [comment]
We have a PR relating to this for 3.4. For now, use CSS:

```
.required {
			border: 0 !important;
			text-decoration: none;
		}
```
