### ISSUE TITLE
Prepending nbsp to required asterisks could improve user experience

### ISSUE THREAD

**Issue by R33D3M33R** [woocommerce/woocommerce#19569]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)

## Steps to reproduce the issue

Dear developers,

a lot of `<span class="required">*</span>` are currently prepended by a regular breaking space. This means that the asterisk can break into new line freely when the container width is changed. This can sometimes produce strange results, as the preceding word might not change line:

![woo-original-asterisk](https://user-images.githubusercontent.com/12114725/38085004-45ef5e78-334f-11e8-9cba-6da8187dde7d.png)

My idea would be to use `&nbsp;` instead of breaking space. This way asterisk would always stick to the last word which produces much more pleasing visual results (at least in my view).

Best Regards,
Andrej Mernik

**Comment by claudiulodro** [comment]
That's not a bad idea. Want to open a pull request with your proposed changes?

**Comment by mikejolley** [comment]
@peterfabian should be a quick one for you - look for instances of `<span class="required">`.
