### ISSUE TITLE
not able to hook into woocommerce_product_thumbnails

### ISSUE THREAD

**Issue by AdriOosterwijk** [woocommerce/woocommerce#19560]
I try to hook into the woocommerce_product_thumbnails hook. I need to use it to display the product description tabs underneath it. When no gallery is used it works fine but when a gallery is used the description (and review) tabs are hidden. I read about a topic here https://github.com/woocommerce/woocommerce/issues/16492 but no solution is provided and as far as I can see no request is submitted.

If needed, please create a new hook to benefit from. I'm sure a lot of other users will appreciate it also.

**Comment by mikejolley** [comment]
This area is used to generate the slider.

Use `woocommerce_before_single_product_summary` hook.

**Comment by AdriOosterwijk** [comment]
I know that it is used to generate the slider and hav read about the woocommerce_before_single_product_summary.
When I try to use it the tabs are displayed above the product summary and I don't know what to do about it...... sorry. Any tips?

**Comment by mikejolley** [comment]
You can include a later priority when adding your action.

**Comment by AdriOosterwijk** [comment]
I got the description tabs beneath the image gallery but now the `woocommerce_single_product_summary` and all what is after that is shifting down. Tried to solve it with other priorities for those hooks as well but that does not seems to be working.
Mike, I know this is not a support forum but I trully hope you will help me as I think a lot of users wil benefit from it also. Thanks

**Comment by AdriOosterwijk** [comment]
i could not solve it with css but someone on stackoverflow helped me out with a js snippet. You can see it here https://stackoverflow.com/questions/49538722/change-description-tabs-location-on-woocommerce-single-product-page. It is claimed to be a bug in WooCommerce overthere. good luck
