### ISSUE TITLE
Dropdowns in onboarding wizard are center aligned

### ISSUE THREAD

**Issue by kellychoffman** [woocommerce/woocommerce#19579]
Currently:
![screen shot 2018-03-30 at 7 57 19 am](https://user-images.githubusercontent.com/5835847/38140243-261958dc-33f0-11e8-81a9-fe92cab2b43e.png)
![screen shot 2018-03-30 at 7 57 41 am](https://user-images.githubusercontent.com/5835847/38140244-26315e0a-33f0-11e8-9652-a7b3cdb64f83.png)

Not sure when this changed, but these should be left aligned for readability, scan-ability, all the abilities.

**Comment by claudiulodro** [comment]
Fixed in #19550
