### ISSUE TITLE
Inconsistent order item refund sign (+/-)

### ISSUE THREAD

**Issue by willgorham** [woocommerce/woocommerce#19576]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an order with an item, shipping, and fee.
2. Refund the item, shipping, and fee individually.
3. See that the item refund amounts are displayed as positive numbers, and the fee/shipping refunds are negative.

## Expected/actual behavior

This is extremely minor obviously, but I would expect all of these numbers to have the same sign (+ or -). 

<img width="958" alt="screen shot 2018-03-30 at 1 14 39 am" src="https://user-images.githubusercontent.com/1883584/38125504-e93483fc-33b7-11e8-97a3-044dd6c614eb.png">

Happy to submit a PR if someone has an opinion on what's the desired behavior here. Positive makes sense to me, because these numbers are showing the **amount** refunded (and it looks cleaner with the icon and no minus in front I think). But if you're thinking in terms of summing the columns, negative makes sense too. Also the total refunded amount is negative.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiulodro** [comment]
I think negative numbers everywhere should be the correct behavior. Then it is consistent with what the customer would see in the My Account > Orders section:
<img width="483" alt="screen shot 2018-03-30 at 11 20 10 am" src="https://user-images.githubusercontent.com/7317227/38148713-74469be8-340c-11e8-84d4-6397eb6fd276.png">

And coupon discounts use negative also:

<img width="687" alt="screen shot 2018-03-30 at 11 23 10 am" src="https://user-images.githubusercontent.com/7317227/38148814-d9bfbdba-340c-11e8-9bc0-71d18673defe.png">


Thanks for volunteering to write a PR! 🥇

**Comment by willgorham** [comment]
PR in #19582 👍
