### ISSUE TITLE
Chosen shipping method not getting updated

### ISSUE THREAD

**Issue by larssn** [woocommerce/woocommerce#19577]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

On the checkout page, when updating your address, the chosen shipping method is wrongly posted.

1. Insert this in functions.php
```
add_filter('woocommerce_shipping_packages', function ($r) {
        error_log('chosen shipping: ' . print_r($_POST['shipping_method'] ?? '', true));
        return $r;
});
```
2. Create two shipping zones, with two shipping methods.
3. On the checkout page, update your zip code, so you bounce between shipping zones.
4. Observe in the log, that the chosen shipping method is output.
5. Now to observe the bug. Change the shipping method to the second choice, and switch your zip, so it triggers the second shipping zone. You will see that the new shipping zone has defaulted to the first shipping method option, but the log still outputs the old choice.

## Expected/actual behavior

When switching shipping zones, and the new zone defaults to the first shipping method, I expect THAT shipping method to be posted back, since it is selected.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://cloud.nuvoweb.dk/test
Site URL: https://cloud.nuvoweb.dk/test
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: da_DK

### Server Environment ###

Server Info: nginx/1.12.2
PHP Version: 7.0.28-0ubuntu0.16.04.1
PHP Post Max Size: 130 MB
PHP Time Limit: 240
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Din server har ikke SoapClient klasse aktiveret - nogle gateway plugins
der bruger SOAP
virker muligvis ikke som forventet.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: nuvo_14_
MaxMind GeoIP Database: ❌ MaxMind GeoIP Database eksisterer ikke - derfor vil geolocation ikke fungere. Du kan downloade og installere den manuelt fra http://dev.maxmind.com/geoip/legacy/geolite/ til stien: . Scroll ned til "Downloads" og download "Binary / gzip" filen ved siden af "GeoLite Country". Husk at udpakke GeoIP.dat.gz og upload kun GeoIP.dat filen.
Total databasestørrelse: 1711.26MB
Database datastørrelse: 934.64MB
Database indexstørrelse: 776.62MB
<lots of database tables>

### Post Type Counts ###

bookable_person: 4
json_consumer: 4
nav_menu_item: 5
oauth2_access_token: 24
oauth2_refresh_token: 21
page: 5
period: 1
post: 1
postman_sent_mail: 91
product: 13
product_variation: 1
revision: 19
shop_order: 197
shop_order_refund: 5
turnover: 73
wc_booking: 18

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Carbon Fields: af htmlburger – 1.6.0
HTTP Headers: af Dimitar Ivanov – 1.9.4
WP REST API - OAuth 1.0a Server: af WP REST API Team – 0.3.0
WooCommerce: af Automattic – 3.3.4
WP Crontrol: af John Blackbourn & contributors – 1.6.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop basisside: #3 - /butik/
Kurv: #4 - /kurv/
Checkout: #5 - /kasse/
Min konto: #6 - /min-konto/
Handelsbetingelser: ❌ Siden er ikke defineret

### Theme ###

Name: Twenty Sixteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – Hvis du redigerer WooCommerce i et hoved-tema
som du ikke selv har udviklet
anbefaler vi at du anvender et undertema (child theme). Se: Hvordan du opretter et undertema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
What you describe makes sense because you're looking at the posted values. 

When you change country for example, it posts the form (including CURRENT shipping method). Those shipping methods won't update until after the request and sent and response comes back.

Shipping methods do not change instantly, so posting the new shipping method is not possible.

Rather than use the posted method, if you need it, you should use the chosen method from WooCommerce (which will update the selection after changing country/zone).

`$chosen_shipping_methods = WC()->session->get( 'chosen_shipping_methods' );`

This is updated after ajax post.

**Comment by larssn** [comment]
Hey mike, thanks for posting. I recall us beginning with `WC()->session->get( 'chosen_shipping_methods' );` as well, and then fell back to $_POST; but I went ahead and checked it anyway.

It exhibits the same issue it seems, and we can modify our filter to show the problem:
```
add_filter('woocommerce_shipping_packages', function ($r) {
        $cs = WC()->session->get( 'chosen_shipping_methods' );
        error_log('chosen shipping: ' . print_r($cs, true));
        return $r;
});
```

When you change your zip, it again, shows the shipping method tied to the previous zone.
Maybe the filter runs too early... still; I'd expect the session to be updated as soon as possible; so it was up to date in subsequent filter hooks.

If you're sure it's working as intended, then I won't question it: we have a workaround in place.

**Comment by mikejolley** [comment]
It may simply be the order as you suggest. `woocommerce_shipping_packages` doesn't care what is chosen as it's ran before shipping methods are calculated.

Generate packages > Pass to shipping methods > Get back rates.
