### ISSUE TITLE
WC_Email class not found in cron

### ISSUE THREAD

**Issue by Tigzy** [woocommerce/woocommerce#19572]
I'm writing a plugin and I have a problem with sending emails in a crontab. Despite woocommerce being properly loaded, I have an error on WC_Email class not found

I can access WC() (woocommerce instance), and even WC_Emails (with the plural) but not WC_Email

I need that class to style my email before I send it

Can you give me tips on how this class is defined?
If I move that code outside of the cron, it works. So it's probably just a problem with how that class is constructed.

example: 

```
$order = new WC_Order( $key->order_id ); <= This works, I can read the order
if ( !is_object( $order ) ) {
	continue;
}

[...]

// Send email
if (class_exists('WC_Email')) {	<= Doesn't work, class not found, why?
	$wc_email = new WC_Email;
	$html_message = $wc_email->style_inline($html_message);
}
```

**Comment by mikejolley** [comment]
This class is not loaded until `WC_Emails` calls `init`. If `WC_Emails` is not loaded and constructed, neither will this be.

Call `WC()->mailer();`

**Comment by Tigzy** [comment]
Perfect, it works ! 👍
