### ISSUE TITLE
Product rating count doesn't update when ratings are edited by admin

### ISSUE THREAD

**Issue by tamarazuk** [woocommerce/woocommerce#19581]
The product rating count doesn't update when a rating is edited by an admin. This is easily evident by comparing the rating stars of a single-review product. 

![](http://cloud.skyver.ge/0O311h2U3B0x/[c8304b255f34bdce5bad07609254930d]_Screen%20Shot%202018-03-29%20at%204.32.44%20PM.png)

While trying to find a solution to this I found that saving the comment twice actually updates the rating counts and averages. 

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a 3 star review to a product with no current reviews.
2. Edit the rating of the new review from the admin - find the review under Comments and change the rating to 5: http://cloud.skyver.ge/410G422h0E3v
3. Observe the product in the frontend to find the rating average doesn't match the rating on the review (rating stars still reflect the original 3 star rating while the review shows the updated 5 stars)
4. Edit the comment once again and click update without making changes. You'll find that the rating stars now do reflect the updated 5 star rating.

## Expected/actual behavior

When I follow those steps, I expect to see the rating stars reflect my changes. 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
@peterfabian Need to see what transient is responsive here and make sure it's flushed when this manual edit takes place in admin. `class-wc-post-data.php` may be suitable place for any handling.
