### ISSUE TITLE
Incorrect State / County codes for Ireland

### ISSUE THREAD

**Issue by ya-well** [woocommerce/woocommerce#19588]
Hi folks,

This was discussed in PR #17938 but not actioned.

The State (County) codes used for IE - Ireland aren't entirely accurate. Using [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:IE#Counties) as a reference, while most codes do align with this, others do not _(D not DN for Dublin, G not GY for Galway, etc...)_.

As mentioned in the referenced PR, this will require an update routine https://github.com/woocommerce/woocommerce/pull/17938#issuecomment-347651310 and suggested following PR #15844.

The correct codes - according to ISO 3166-2 - are as below. Changes are required to the codes for Cork, Dublin, Galway and Tipperary only

> 	'CW' => __( 'Carlow', 'woocommerce' ),
> 	'CN' => __( 'Cavan', 'woocommerce' ),
> 	'CE' => __( 'Clare', 'woocommerce' ),
> 	'CO' => __( 'Cork', 'woocommerce' ),
> 	'DL' => __( 'Donegal', 'woocommerce' ),
> 	'D' => __( 'Dublin', 'woocommerce' ),
> 	'G' => __( 'Galway', 'woocommerce' ),
> 	'KY' => __( 'Kerry', 'woocommerce' ),
> 	'KE' => __( 'Kildare', 'woocommerce' ),
> 	'KK' => __( 'Kilkenny', 'woocommerce' ),
> 	'LS' => __( 'Laois', 'woocommerce' ),
> 	'LM' => __( 'Leitrim', 'woocommerce' ),
> 	'LK' => __( 'Limerick', 'woocommerce' ),
> 	'LD' => __( 'Longford', 'woocommerce' ),
> 	'LH' => __( 'Louth', 'woocommerce' ),
> 	'MO' => __( 'Mayo', 'woocommerce' ),
> 	'MH' => __( 'Meath', 'woocommerce' ),
> 	'MN' => __( 'Monaghan', 'woocommerce' ),
> 	'OY' => __( 'Offaly', 'woocommerce' ),
> 	'RN' => __( 'Roscommon', 'woocommerce' ),
> 	'SO' => __( 'Sligo', 'woocommerce' ),
> 	'TA' => __( 'Tipperary', 'woocommerce' ),
> 	'WD' => __( 'Waterford', 'woocommerce' ),
> 	'WH' => __( 'Westmeath', 'woocommerce' ),
> 	'WX' => __( 'Wexford', 'woocommerce' ),
> 	'WW' => __( 'Wicklow', 'woocommerce' )

**Comment by mikejolley** [comment]
@peterfabian There is a file with update routines you can see in `wc-update-functions.php` - there are some past examples there of how to update states in past orders you can refer to.
