### ISSUE TITLE
Rounding trouble in manual orders by admin

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#19597]
If I have setup a product with 4 digits after comma and products are including tax and create a order in admin with this product manually, the 4 digits after comma get rounded back to 2 digits after comma.

I have set my staging site with only woocommerce active, no other plugins. WC 3.3.4. WP 4.9.4. Set store to use always prices include tax. Tax is set to 19 percent. Product costs 0,6667 incl. tax.

Create order with this product – price gets to price without tax and rounded – it becomes 0,56 excl. tax but should be 0,5603. Multiplied by 100 plus added tax back this makes a difference of 42 cent incl. tax. In admin this order costs 66,25 – in frontend it costs 66,67.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19526

**Comment by ajgw** [comment]
Thanks Mike.
