### ISSUE TITLE
Customize _order_key prefix

### ISSUE THREAD

**Issue by amjad** [woocommerce/woocommerce#19593]
Is it possible to customize the order key prefix of an order? 

Instead of **wc_order_XXXXXX** I would like to have **mycustomprefix_XXXXXXX**. Does changing this impact anything else in the WC platform? If not, where can it be changed in the code? 

My usage: I use the public URL of an order to send as a text receipt to my customers.

**Comment by claudiulodro** [comment]
[You can customize the part after `wc_` easily (You could do `wc_yourprefix_xxxxxx`).](https://github.com/woocommerce/woocommerce/blob/00b4e1ed447003bef52ba27064ec17784ec9df2e/includes/data-stores/class-wc-order-data-store-cpt.php#L84)

If you really don't want the `wc` prefix, you'll have to do a deeper customization. There [seem to be plugins that do what you want, also](https://webkul.com/blog/wordpress-woocommerce-custom-order-prefix/).

In the future please limit the GitHub issues to bug reports, and development/support questions to [the forums](https://wordpress.org/support/plugin/woocommerce/). Thanks.
