### ISSUE TITLE
get products with attribute value equal to my value ?

### ISSUE THREAD

**Issue by kurianic** [woocommerce/woocommerce#19604]
I need to show latest three products from each variation on the home page. I am working on a photographic store with woocommerce.

**Comment by kurianic** [comment]
![screenshot-2018-4-4 edit product martin james photography wordpress](https://user-images.githubusercontent.com/24931188/38300969-e5427f98-381b-11e8-80f0-488fa749a112.png)
This is how my page looks like i need to list down latest three products in canvas here. Please answer thanks in advance

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
