### ISSUE TITLE
https://example.com/wp-json/wc/v2/products?author=1 is not working what custom code need to be added to resolve this.

### ISSUE THREAD

**Issue by Rafiqgithub** [woocommerce/woocommerce#19608]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
if it's not listed here it's not supported https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

We don't provide custom code here.

**Comment by Rafiqgithub** [comment]
@mikejolley Thanks for the response but that api is not working what should i do now?

**Comment by mikejolley** [comment]
The API works but it doesn't include an `author` option.
