### ISSUE TITLE
Visibility dropdown not responding in Quick Edit when Stock Management is disabled

### ISSUE THREAD

**Issue by LaurenaRehbein** [woocommerce/woocommerce#19600]
When "Enable Stock Management" is disabled, in **WooCommerce > Settings > Products > Inventory** the Visibility Dropdown in Quick Edit mode does not respond to clicks. 

## Steps to reproduce the issue

Using WooCommerce 3.3.4 and Twenty-Seventeen 1.4, no other plugins enabled

1. Disable Stock Managment in **WooCommerce > Settings > Products > Inventory**
2. Visit **WooCommerce > All Products**
3. Hover over a product and select "Quick Edit" 
4. Try to change the Visibility setting

There is no response: 

![http://cld.wthms.co/SnomEx](http://cld.wthms.co/SnomEx+)
Full Image: http://cld.wthms.co/SnomEx+ 

Also notice the "In Stock" field mashes right up against the "Featured" field. 

 #1042799-zen

**Comment by AnwerAR** [comment]
Select elements are messed up when Stock management is disabled. see below screenshot. thus Visibility select is triggering In Stock select element.

![messsed-ui-of-select-elements](https://user-images.githubusercontent.com/11960126/38325171-b07f6e98-385b-11e8-9c6a-074af1b6dd55.png)


Adding `float: left;` to` .inline-edit-row fieldset label` resolves this issue. curious to see if there's better solution or okay to submit PR with mentioned CSS updates?

**Comment by mikejolley** [comment]
@AnwerAR Please do. That will satisfy this until quick edit/list tables get an overhaul.
