### ISSUE TITLE
Product $extra_data loses slashes due to update_post_meta

### ISSUE THREAD

**Issue by ripieces** [woocommerce/woocommerce#19605]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use the $extra_data member on a derieved Product class.
2. Save product with data such as `\"` in an  $extra_data element.
3. Load product (from database) again.

## Expected/actual behavior

When I follow those steps, I see that the slash is missing.

I was expecting to see the slash.

## Reason for the bug:

The usage of the update_post_meta function without a preceding wp_slash on the argument causes this:
https://codex.wordpress.org/Function_Reference/update_post_meta#Character_Escaping

## Possible solutions:

1) Run the data through wp_slash before using update_post_meta.
Disadvantage: Might break existing plug-ins, however those might not function correctly anyway, because the data is different when used live vs when product is deserialized from database.

**Comment by claudiosanches** [comment]
I'll need better steps to reproduce, I need more details in order to check for this issue.
And why you can't apply `wp_slash()` on your side?
I agree that forcing `wp_slash()` for everything now should break existing backwards compatibility, so we can think about something in the middle to avoid it.

**Comment by ripieces** [comment]
Here is some simplified sample code as plugin:
```
<?php
/*
Plugin Name: Woo Test 19605
Plugin URI:  https://github.com/woocommerce/woocommerce/issues/19605
Description: Test for Woocommerce issue #19605
Version:     0.1.0
Author:      Dominik Tugend
Author URI:  https://github.com/ripieces
Domain Path: /languages
Text Domain: woo-test-19605
*/

defined( 'ABSPATH' ) or exit;

function woo_test_19605_woocommerce_loaded()
{
	//if(!isset($_GET['woo_test_19605'])) return;
	
	class WC_Product_19605 extends WC_Product {

		protected $extra_data = array(
			'19605_data' => '',
		);
		
		public function get_type() {
			return '19605_derived';
		}
		
		public function get_19605_data( $context = 'view' ) {
			return $this->get_prop( '19605_data', $context );
		}

		public function set_19605_data( $value ) {
			$this->set_prop( '19605_data', $value );
		}
	}
	
	
	$product = new WC_Product_19605();
	
	$target_data = '\\"';
	
	$product->set_19605_data($target_data);
	
	$actual_data = $product->get_19605_data('edit');
	
	echo '<div class="notice notice-info">Woo Test 19605: Before saving & loading: target='.htmlentities($target_data).', actual='.htmlentities($actual_data).'</div>';
	
	$product->save();
	
	$data_store = WC_Data_Store::load( 'product-19605' );
	
	$data_store->read($product);
	
	$actual_data = $product->get_19605_data('edit');
	
	echo '<div class="notice notice-info">Woo Test 19605: After saving & loading: target='.htmlentities($target_data).', actual='.htmlentities($actual_data).'</div>';
	
	$product->delete();
}

add_action( 'admin_notices', 'woo_test_19605_woocommerce_loaded' );
```

The output with the current WooCommerce version is (as admin notices):
```
Woo Test 19605: Before saving & loading: target=\", actual=\"
Woo Test 19605: After saving & loading: target=\", actual="
```

"bug free" output would be:
```
Woo Test 19605: Before saving & loading: target=\", actual=\"
Woo Test 19605: After saving & loading: target=\", actual=\"
```

The [update_post_meta WordPress hook](https://core.trac.wordpress.org/browser/tags/4.9.5/src/wp-includes/meta.php#L187) is too late for wp_slash, because it's not decidable if the backslash has been stripped or if there was one, because it's run after wp_unslash.

So the only solution that would work somewhat properly is to:
- Create an own data store and override update_post_meta there and adding wp_slash before calling the base class function and restoring the old values after the call

If you decide agains fixing this bug, because of the potential to break existing plugins, that might relay on the bug, I suggest to at least leave a notice about the problem at the [$extra_data member comment](https://github.com/woocommerce/woocommerce/blob/42978bb031efca0518ef43f2a577663bebe676fe/includes/abstracts/abstract-wc-data.php#L68)  somehow.

**Comment by mikejolley** [comment]
We've worked around this in some other places https://github.com/woocommerce/woocommerce/search?utf8=%E2%9C%93&q=wp_slash&type=

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19675
