### ISSUE TITLE
"Save to account" text vague, could be improved

### ISSUE THREAD

**Issue by warm--tape** [woocommerce/woocommerce#19617]
The function save_payment_method_checkbox in /includes/abstracts/abstract-wc-payment-gateway.php outputs some very generic, vague text "Save to account"

It would be a great enhancement if it was possible to change it to something more descriptive, like "Save my credit card details for future purchases (optional)" through a hook/filter or something along those lines.

FWIW changing the text with jquery doesn't appear to work.

**Comment by claudiulodro** [comment]
Are you making a custom gateway? What are you trying to do? 

If it's a new gateway you can override the the `save_payment_method_checkbox` method with a custom one. If it's an existing gateway, why do you need to change the text?

**Comment by mikejolley** [comment]
Sorry but this has to be generic. Not all gateways deal with credit cards so making the default text that specific would be problematic.

>  nor is there a simple way to edit it.

Not true. The method `save_payment_method_checkbox` can be overridden via the PayPal gateway. So for example, Stripe could implement that method and add the text about credit cards in, if wanted. For that reason you may want to report to the developer of Stripe to tweak (cc @bor0 - feature request for ours).

In the meantime, you can also translate this one string with https://wordpress.org/plugins/say-what/ - thats also another east way to edit just on your install.

cc @claudiulodro 

Thanks
