### ISSUE TITLE
Variations, prices and SKUs dissapear after restoring backup

### ISSUE THREAD

**Issue by amouratoglou** [woocommerce/woocommerce#19612]
[ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
[ x] The issue still exists against the latest master branch of WooCommerce on Github (this is not the same version as on WordPress.org!)
[ x] I have attempted to find the simplest possible steps to reproduce the issue
 I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

We had to restore the database from backup when restored all product variations and all prices are gone, 

I used Phpmyadmin. I have used the SQL file auto-saved by hosting.

## Expected/actual behavior

Normally backup DB restore would be direct and without issues.

Products still are there without variations nor price, because the price is related with variations.
Can't see any variations on the product edit nor on the front end.
This happened to 90% of my products, only a few still show the variations like before.

Also when I go to Woocommerce tools and click "delete orphaned variations" 0 variations are deleted.

**Normally I do this without problem, is there any known way to restore variations or to re-sync them? doing it manually would take ages!**

When editing a variable product,  Attributes are set to be used as variations, but they don't show.

![image](https://user-images.githubusercontent.com/7943759/38323844-d0653ee6-3814-11e8-97da-9e630b86cf8e.png)

I can see it says "variable product" but no variations appear.

![image](https://user-images.githubusercontent.com/7943759/38323638-390a6e04-3814-11e8-8d81-c0651dab7ac7.png)

I can see all the attributes still exist and have products assigned, they show in the count column:
If I click for example a variaton and visit the variaton archive, I can see all the products .
But when editing them, no variations show.
![image](https://user-images.githubusercontent.com/7943759/38321960-6158a9ca-380f-11e8-9512-85b4b20478af.png)

## Isolating the problem

-Tried without any plugins and still is not working. 
-Tried upgrading woocommerce didn't work either.
-No errors on the developer console.
-Tried to untrash variations and recount terms, but didn't work. (https://gist.github.com/mikejolley/7dc21432643a4fdd342474dc2694a22d)
`
```
### WordPress Environment ###

Home URL: https://www.siteclothing.com
Site URL: https://www.siteclothing.com
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.8.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: jiaoewh_
Total Database Size: 68.43MB
Database Data Size: 41.49MB
Database Index Size: 26.94MB
jiaoewh_woocommerce_sessions: Data: 0.14MB + Index: 0.02MB
jiaoewh_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
jiaoewh_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
jiaoewh_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
jiaoewh_woocommerce_order_items: Data: 0.10MB + Index: 0.06MB
jiaoewh_woocommerce_order_itemmeta: Data: 0.59MB + Index: 0.43MB
jiaoewh_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
jiaoewh_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
jiaoewh_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
jiaoewh_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
jiaoewh_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
jiaoewh_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
jiaoewh_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
jiaoewh_woocommerce_log: Data: 0.02MB + Index: 0.02MB
jiaoewh_apto: Data: 0.05MB + Index: 0.03MB
jiaoewh_apto_sort_list: Data: 0.08MB + Index: 0.05MB
jiaoewh_commentmeta: Data: 0.05MB + Index: 0.05MB
jiaoewh_comments: Data: 0.39MB + Index: 0.17MB
jiaoewh_ewwwio_images: Data: 9.52MB + Index: 13.13MB
jiaoewh_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
jiaoewh_itsec_lockouts: Data: 0.00MB + Index: 0.00MB
jiaoewh_itsec_log: Data: 0.00MB + Index: 0.00MB
jiaoewh_itsec_temp: Data: 0.00MB + Index: 0.00MB
jiaoewh_iwp_backup_status: Data: 0.02MB + Index: 0.00MB
jiaoewh_links: Data: 0.00MB + Index: 0.00MB
jiaoewh_options: Data: 1.61MB + Index: 0.29MB
jiaoewh_postmeta: Data: 22.63MB + Index: 9.85MB
jiaoewh_posts: Data: 3.00MB + Index: 0.71MB
jiaoewh_rg_form: Data: 0.00MB + Index: 0.00MB
jiaoewh_rg_form_meta: Data: 0.00MB + Index: 0.00MB
jiaoewh_rg_form_view: Data: 0.03MB + Index: 0.02MB
jiaoewh_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
jiaoewh_rg_lead: Data: 0.01MB + Index: 0.00MB
jiaoewh_rg_lead_detail: Data: 0.01MB + Index: 0.03MB
jiaoewh_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB
jiaoewh_rg_lead_meta: Data: 0.01MB + Index: 0.02MB
jiaoewh_rg_lead_notes: Data: 0.00MB + Index: 0.00MB
jiaoewh_termmeta: Data: 0.19MB + Index: 0.27MB
jiaoewh_terms: Data: 0.07MB + Index: 0.11MB
jiaoewh_term_relationships: Data: 0.28MB + Index: 0.56MB
jiaoewh_term_taxonomy: Data: 0.12MB + Index: 0.12MB
jiaoewh_usermeta: Data: 0.40MB + Index: 0.22MB
jiaoewh_users: Data: 0.02MB + Index: 0.02MB
jiaoewh_wc_download_log: Data: 0.00MB + Index: 0.00MB
jiaoewh_wc_webhooks: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfBlocks: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfConfig: Data: 0.01MB + Index: 0.01MB
jiaoewh_wfCrawlers: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfFileMods: Data: 1.51MB + Index: 0.49MB
jiaoewh_wfHits: Data: 0.25MB + Index: 0.05MB
jiaoewh_wfHoover: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfIssues: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfLeechers: Data: 0.01MB + Index: 0.01MB
jiaoewh_wfLockedOut: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfLocs: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfLogins: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfNet404s: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfReverseCache: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfScanners: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfStatus: Data: 0.07MB + Index: 0.03MB
jiaoewh_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
jiaoewh_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
jiaoewh_woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB
jiaoewh_woocommerce_shipping_zone_shipping_methods: Data: 0.00MB + Index: 0.00MB
jiaoewh_wpmelon_advbedit_temp: Data: 0.02MB + Index: 0.00MB
jiaoewh_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
jiaoewh_yoast_seo_meta: Data: 0.14MB + Index: 0.00MB

### Post Type Counts ###

acf: 10
acf-field: 18
acf-field-group: 6
apto_sort: 107
attachment: 4895
customize_changeset: 5
home_slides: 11
homepage_grid: 7
nav_menu_item: 76
page: 41
post: 95
product: 291
product_variation: 8
revision: 289
shop_coupon: 57
shop_order: 491
shop_order_refund: 47
wc_product_tab: 2720
yith_wcps_type: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Query Monitor: by John Blackbourn – 2.17.0
Advanced Custom Fields: Repeater Field: by Elliot Condon – 2.0.1
Advanced Custom Fields: oEmbed Field: by DMSQD – 1.0.3
Advanced Custom Fields: by Elliot Condon – 4.4.12
Advanced Post Types Order: by Nsp Code – 3.9.9.7
Animate It!: by eLEOPARD Design Studios – 2.2.1
CodeStyling Localization: by Heiko Rabe – 1.99.30
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.18
Custom Post Type UI: by WebDevStudios – 1.5.7
Disable Comments: by Samir Shah – 1.7.1
Double serialized attributes fixer: by Mike J – 0.0.9 – Not tested with the active version of WooCommerce
Easy WP SMTP: by wpecommerce – 1.3.2
Google Tag Manager: by George Stephanis – 1.0.2
Last Modified Timestamp: by Evan Mattson – 1.0.4
Show Current Template: by JOTAKI Taisuke – 0.3.0
Simple 301 Redirects: by Scott Nellé – 1.07
WC Ajax Product Filter: by Shamim Al Mamun – 2.0.3 – Not tested with the active version of WooCommerce
WC Multiple Email Recipients: by Con Schneider – 1.2.4 – Not tested with the active version of WooCommerce
Widget Shortcode: by Hassan Derakhshandeh – 0.3.0
Widget Title Links: by Illimar Tambek – 1.4.1
WooCommerce Bulk Edit Product Variations: by matterico_themes – 2.5.4 – Not tested with the active version of WooCommerce
Woocommerce Advanced Bulk Edit: by George Iron – 4.3.4
WooCommerce Brands: by WooCommerce – 1.5.2 – 1.6.0 is available – Not tested with the active version of WooCommerce
WooCommerce SagePay Form and SagePay Direct Gateway: by Andrew Benbow – 3.10.1 – 3.11.0 is available
Woocommerce Mailchimp Discount: by Magnigenie – 2.2 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoice: by RightPress – 3.1.7
WooCommerce Product Image Flipper: by jameskoster – 10.2.0 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.2 – 1.12.0 is available – Not tested with the active version of WooCommerce
WooCommerce Tab Manager: by SkyVerge – 1.8.2 – 1.9.0 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.6 – 3.3.4 is available
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO: by Team Yoast – 6.0
WP Force SSL: by Kostas Vrouvas – 1.3
YITH WooCommerce Added to Cart Popup Premium: by YITHEMES – 1.2.8 – Not tested with the active version of WooCommerce
YITH WooCommerce Product Slider Carousel: by YITHEMES – 1.0.21

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #34 - /shop/
Basket: #35 - /cart/
Checkout: #36 - /checkout/
My account: #37 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: site
Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: site/woocommerce/archive-product.php
site/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0
site/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.2.0
site/woocommerce/cart/cart-totals.php
site/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.2.0
site/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.0.0
site/woocommerce/emails/admin-new-order.php
site/woocommerce/emails/customer-completed-order.php
site/woocommerce/emails/customer-invoice.php
site/woocommerce/emails/customer-new-account.php
site/woocommerce/emails/customer-reset-password.php
site/woocommerce/emails/email-footer.php
site/woocommerce/emails/email-header.php
site/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.2.0
site/woocommerce/loop/no-products-found.php
site/woocommerce/loop/sale-flash.php
site/woocommerce/order/form-tracking.php version 1.6.4 is out of date. The core version is 3.2.0
site/woocommerce/order/tracking.php
site/woocommerce/single-product/add-to-cart/external.php
site/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.7
site/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
site/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
site/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
site/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
site/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.1.0
site/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.1.0
site/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
site/woocommerce/single-product/sale-flash.php
site/woocommerce/single-product/share.php
site/woocommerce/single-product/short-description.php
site/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
site/woocommerce/single-product/tabs/description.php
site/woocommerce/single-product/tabs/tabs.php
site/woocommerce/single-product/title.php
site/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0

Outdated Templates: ❌Learn how to update

### sagepay ###

MCrypt: ✔ Yes
OpenSSL: ✔ Yes
OpenSSL Methods: ✔ Yes
PHP Max_Input_Vars: ❌ Your php_max_inpit_vars value is 1000. If you experience any issues during checkout then increase this value to 5000.
`
```

**Comment by amouratoglou** [comment]
I would really appreciate some feedback on this issue I'm experiencing. thanks.

**Comment by drosendo** [comment]
I'm also experiencing same issue.

**Comment by amouratoglou** [comment]
@drosendo  did you restored the database and that caused the same problem? please let me know if you have any idea on how to recover all the variations.

**Comment by drosendo** [comment]
On my case I migrated server, and from a backup restore...

**Comment by amouratoglou** [comment]
@drosendo  I have searched my product_type - product_variation and discovered that only remains 5 of the total that I had before. So I guess all my variations are completely gone.  BTW Do you know if the products XML export (Wordpress export-import tool) includes product variations?

**Comment by drosendo** [comment]
@amouratoglou yes it does...

**Comment by claudiulodro** [comment]
It sounds like there is some problem either in the sql backup your host saved or when restoring the backup from sql file using phpmyadmin. Neither of these are managed or controlled by WooCommerce, and WC will not be able to make them work if they didn't work properly in the first place. The required information just isn't present in the database (You can see there are only a few posts with the product_variation post type in the system report).

There is [a built-in product CSV importer/exporter in WooCommerce](https://docs.woocommerce.com/document/product-csv-importer-exporter/), and this can handle variations. May be worth investigating.

I'm closing this issue because there is nothing WooCommerce can really do or be expected to do about a bad database. I wish you good luck!

**Comment by drosendo** [comment]
@claudiulodro im sad to see you so easily dismiss the issue, but I also have other clients that the variations simple dissapeared on update (no migration, backup restore), jsut kaput.
Please re-open this. I can provide access for your eyes to see.

**Comment by amouratoglou** [comment]
I agree @claudiulodro

**Comment by claudiulodro** [comment]
```
### Post Type Counts ###

[...]
product_variation: 8
```

There are only 8 posts of the product_variation post type. There isn't anything WooCommerce can do if the underlying WordPress post data does not exist.

@drosendo that sounds like a separate issue, not like what @amouratoglou has happening. On an update if the variations disappear, the post data still exists and is not being properly linked to the product somehow (e.g. [this issue](https://github.com/woocommerce/woocommerce/issues/17775)). There is no post data here, so it is impossible to rebuild the variation information; something failed in the backup+restore process and the information is not present in the database.

**Comment by drosendo** [comment]
@claudiulodro on the front-end everything seems normal... just when i edit the product on the variations tab it shows empty, nada... Dont see the relation with the issue you mentioned.

**Comment by claudiulodro** [comment]
@drosendo like with the issue I linked, your data still exists in the DB but it is not showing up in the admin for some reason. In OP's issue the data doesn't even exist in the DB. That's what I was trying to demonstrate.

**Comment by mikejolley** [comment]
Folks this really depends on the type of backups you're using and how they are 'restored'. For example, if you restored a partial backup, or appended some data from the backup, thats going to mess up post IDs. Variations are linked to posts via the parent_id field, and thats also how meta and taxonomies are linked. This is how WordPress works.

Whats more, there are other tables in WooCommerce outside of the usual tables WordPress has, such as `woocommerce_attributes` which stores data about the attribute taxonomies. If this is lost or changed, no attributes will work and variations will lose all mapping.

It's not so much about 'dismissing the issue' - it's that if someone messes with data, particularly using SQL, there is no way WooCommerce itself can account for that. And no, WC does not delete data after updates. The only deletion mechanism is on 'uninstall' (when you delete the plugin via plugins page). WooCommerce itself did not cause these issues.

Going back to the OP, I can give insight to a few of the observations:

> I can see all the attributes still exist and have products assigned, they show in the count column:
If I click for example a variaton and visit the variaton archive, I can see all the products .
But when editing them, no variations show.

Attributes are mapped to the parent variable products, not the individual variations. This part is working in your case.

> I can see it says "variable product" but no variations appear.
> When editing a variable product, Attributes are set to be used as variations, but they don't show.

Attributes will only show when there is a child variation. This is missing. "add variation" will reveal attributes.

> Also when I go to Woocommerce tools and click "delete orphaned variations" 0 variations are deleted.

Which means either;
- the variations no longer exist
- the variations exist, but still have a parent. It may not be the correct parent but something exists.

It sounds like the variations themselves were either not backed up, or the parent IDs are now wrong after restoring the backup. Perhaps the IDs were not maintained when you imported the backup.

> Normally I do this without problem, is there any known way to restore variations or to re-sync them? doing it manually would take ages!

There is no 're-sync' - you need to see where the data is (if it's still in the DB) and see if those IDs are mismatching. If they are, you could try updating them in bulk, but you may have to rebuild those products.

For backup solutions, look for WordPress specific ones. Examples here https://woocommerce.com/2017/05/create-use-backups-woocommerce/

If you're moving servers, make sure all data is moved in bulk, not partially, and ensure IDs are preserved. WordPress DB Migate pro is a good one.

Thanks

**Comment by amouratoglou** [comment]
OK. Thanks @mikejolley . Yes , I guess that the backup made by the hosting automatically must have been corrupted... strange, very strange because I normally restore sites without problems in the same hosting environment. 

When I click add variations on a product edit page, variations are added, empty. Is like if the type of variation was already there, I don't need to select which, just clicked add and they appear, without prices nor SKUS.

> If you're moving servers, make sure all data is moved in bulk, not partially, and ensure IDs are preserved. WordPress DB Migate pro is a good one.

Do you think using phpmyadmin is not good or safe when moving servers?

Thanks for your feedback.

**Comment by mikejolley** [comment]
> Do you think using phpmyadmin is not good or safe when moving servers?

I think it depends how you do it; I believe there is an option to make primary keys 'restart' from 1. And if that is chosen, IDS will no longer match and and it will result in broken products.
