### ISSUE TITLE
Variable Product can be added to cart without select variation ?

### ISSUE THREAD

**Issue by DrMTR** [woocommerce/woocommerce#19613]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  tryed to upgrade Woocomerce
2. tryed to disable all plugins.
3. Tryed to flush cache
4. Tryed to add to cart from this [product ](https://progressivetherapyedu.com/product/onecourseearlybird/)for ex. 

## Expected/actual behavior

I expect to see warning at top that must select variation before proceed with order.

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.

Home URL: |   | http://progressivetherapyedu.com
-- | -- | --
Site URL: |   | http://progressivetherapyedu.com
WC version: |   | 3.3.4
Log directory writable: |   | /home/prgthdu/public_html/wp-content/uploads/wc-logs/
WP version: |   | 4.9.5
WP multisite: |   | –
WP memory limit: |   | 256 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US


```
</details>

**Comment by claudiosanches** [comment]
The product linked here redirect back to the homepage.
I can't see any issue, for sure if is a variable product you should select any variation based on the attributes, if the product does not have any variation to be selected, for sure is not possible to add to the cart.
