### ISSUE TITLE
Problem with panels in woocommerce product edit pges

### ISSUE THREAD

**Issue by rogoszmaciej** [woocommerce/woocommerce#19616]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to any product edit page
2.  click on any tab below default
3.

## Expected/actual behavior

Nothing is showing up. Only blank space instead of panel content. I'm unable to change variations, product shipping, stock settings, attributes, advanced.

What is actually working are customs panels I have implemented.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above
- Problem occurs on three independent stores

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://wptest.missplanner.pl
Site URL: http://wptest.missplanner.pl
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pl_PL

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.2
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.26.0
OpenSSL/1.0.2d

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: mptest
MaxMind GeoIP Database: ✔
Całkowity rozmiar bazy danych: 22.06MB
Rozmiar bazy danych: 12.09MB
Rozmiar indeksu bazy danych: 9.97MB
mptestwoocommerce_sessions: Dane: 0.02MB + Indeks: 0.02MB
mptestwoocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB
mptestwoocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB
mptestwoocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.05MB
mptestwoocommerce_order_items: Dane: 0.02MB + Indeks: 0.02MB
mptestwoocommerce_order_itemmeta: Dane: 0.02MB + Indeks: 0.03MB
mptestwoocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB
mptestwoocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.03MB
mptestwoocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB
mptestwoocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.03MB
mptestwoocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB
mptestwoocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB
mptestwoocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB
mptestwoocommerce_log: Dane: 0.02MB + Indeks: 0.02MB
mptestcommentmeta: Dane: 0.02MB + Indeks: 0.03MB
mptestcomments: Dane: 1.52MB + Indeks: 0.84MB
mptestlinks: Dane: 0.02MB + Indeks: 0.02MB
mptestoptions: Dane: 1.05MB + Indeks: 0.02MB
mptestpostmeta: Dane: 6.52MB + Indeks: 7.98MB
mptestposts: Dane: 2.48MB + Indeks: 0.48MB
mptesttermmeta: Dane: 0.02MB + Indeks: 0.03MB
mptestterms: Dane: 0.02MB + Indeks: 0.03MB
mptestterm_relationships: Dane: 0.06MB + Indeks: 0.02MB
mptestterm_taxonomy: Dane: 0.02MB + Indeks: 0.03MB
mptestusermeta: Dane: 0.02MB + Indeks: 0.03MB
mptestusers: Dane: 0.02MB + Indeks: 0.05MB
mptestwc_download_log: Dane: 0.02MB + Indeks: 0.03MB
mptestwc_webhooks: Dane: 0.02MB + Indeks: 0.02MB

### Post Type Counts ###

attachment: 354
faq: 8
page: 15
post: 1
product: 109
product_variation: 7
promocja: 3
revision: 2
shop_coupon: 2
shop_order: 1339
shop_webhook: 1

### Security ###

Secure connection (HTTPS): ❌Twój sklep nie używa protokołu HTTPS. Dowiedz się więcej o HTTPS i certyfikatach SSL .
Hide errors from visitors: ❌Komunikaty o błędach nie powinny być widoczne dla użytkowników.

### Active Plugins (1) ###

WooCommerce: przez Automattic – 3.3.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude-from-search (exclude-from-search-2)
featured (featured)
featured (featured-2)
outofstock (outofstock)
rated-1 (rated-1)
rated-1 (rated-1-2)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
rated-5 (rated-5-2)


### WC Pages ###

Strona sklepu: #4 - /sklep/
Koszyk: #3380 - /koszyk/
Zamówienie: #3381 - /zamowienie/
Moje konto: #3382 - /moje-konto/
Regulamin: #537 - /regulamin-sklepu/

### Theme ###

Name: Twenty Seventeen
Version: 1.3 – 1.5 jest dostępne
Author URL: https://pl.wordpress.org/
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by rogoszmaciej** [comment]
Found a culprit already. All the panels have _hidden_ class attached. When You click on the desired tab in panels menu, the _hidden_ class isn't cahnged to _active_. Changed it in chrome dev tools and everything shows up. Bit messy to do it every single time though.

**Comment by rogoszmaciej** [comment]
`$('.product_data_tabs li a').on('click',function(e){
e.preventDefault();
var panel=$(this).attr('href');
$('.panel').removeClass('active').addClass('hidden');
$(panel).removeClass('hidden').addClass('active');
});`

Just wrote a JQuery snippet that resolves the issue. Tested on Chrome dev tools, no other than WooCommerce plugins active.

**Comment by peterfabian** [comment]
Hi Maciej,

Thanks for letting us know what the issue was and that you managed to solve it.
As you probably found out, the JS code to handle tabs is mostly in [single-product.js](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/single-product.js), so you can have a look at how it works and adjust your solution so that it works fine with existing tabs.

**Comment by rogoszmaciej** [comment]
Hi Peter,

The only problem is none of them worked (apart from custom created panels and general one).
The code I posted merely added functionality that was probably missing. I looked up in file You mentioned and it swaps _active_ and _hidden_ classes for panels navigation:
`$tab.closest( 'li' ).addClass( 'active' );`
The second line doesn't swap those classes, only switches attribute display from _none_ to _block_. After manually adding proper classes all seems to work. If You need I can send more details with code samples from one of my clients stores.

**Comment by rogoszmaciej** [comment]
Hi,
The customization was only adding additional panel (tabs) on the product edit page. But even after switching to Twenty Seventeen theme, problem still occurred.
I'll try to summarize what I discovered:

1. Each <div> container for a panel (eg. Storage, Shipping) has 3 default classes attached and a `style` attribute. So the markup is something like this:
`<div class="panel woocommerce_options_panel hidden" style="display: none;">` - only first panel (General options) has class `active` instead of `hidden` and `display` set to 'block'.
Now, regardless on which tab I want to switch to, the <div> container for corresponding link in tabs navigation has markup (after click on the navigation link in `ul.product_data_tabs.wc-tabs`)
`<div class="panel woocommerce_options_panel hidden" style="display: block;">` - switch the class hidden to active in dev tools, and desired panel appears.

**Comment by chanduking08** [comment]
Hi Maciej,  

How did you resolve this issue?  
I'm currently facing the same problem. Could you share how you fixed it? 
I’m also using the latest versions of WooCommerce, WordPress, and the Astra theme.

Thank you in advance for your suggestions!

**Comment by mrogosz-da** [comment]
Sorry, I'm out of WP development, and can't even recall what the problem was here...
