### ISSUE TITLE
Product Attributes panel mising woocommerce_options_panel class

### ISSUE THREAD

**Issue by maddisondesigns** [woocommerce/woocommerce#19623]
When adding custom fields into various product panels, they appear nicely formatted on every panel except for the Attributes panel.

As an example, here's the General tab with some custom fields
![woocommerce_generaltab](https://user-images.githubusercontent.com/2078245/38352506-c6a71108-38f6-11e8-9735-3070dbc71a5a.png)

And here's the same fields on the Attributes Tab
![woocommerce_attributestab](https://user-images.githubusercontent.com/2078245/38352515-d062a5fe-38f6-11e8-968d-3049bf624469.png)

As you can see, the fields are missing their styles when displayed on the Attributes tab.

The cause of this appears to be a missing `woocommerce_options_panel` class on the `#product_attributes` `div`. The `<p>` element and its enclosed `<label>`, `<span>` and `<input>` elements for each field all rely on there being a `woocommerce_options_panel` class on the outer container.

![screenshot_619](https://user-images.githubusercontent.com/2078245/38352672-4ea0de86-38f7-11e8-9271-f24515c51e47.png)

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Using the `woocommerce_product_options_attributes` hook, add a custom field to the Product Attributes panel. (see sample code below*)
2. Create new Simple Product
3. Switch to Attributes panel and view the unformatted field

<details>
<summary>*Sample Code</summary>
<pre>
function mytheme_woo_add_custom_fields() {

	global $woocommerce, $post;

	echo '<div class="options_group">';

 	// Text Field
	woocommerce_wp_text_input(
		array(
			'id'          => '_text_field',
			'label'       => __( 'My Text Field', 'woocommerce' ),
			'placeholder' => 'http://',
			'desc_tip'    => true,
			'description' => __( "Here's some really helpful tooltip text.", "woocommerce" )
		)
 	);

 	echo '</div>';
}
add_action( 'woocommerce_product_options_attributes', 'mytheme_woo_add_custom_fields' );
</pre>
</details>

## Expected/actual behavior
When I follow those steps, I see my custom field on the Attributes Panel, but it isn't formatted properly with the correct margins/padding/widths etc..

I was expecting to see the custom field formatted in the same way as they appear when they're added to any of the other Product Panels

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://dev.wordpress-test.com
Site URL: http://dev.wordpress-test.com
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 5.6.32 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
Total Database Size: 13.58MB
Database Data Size: 11.18MB
Database Index Size: 2.40MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_bp_activity: Data: 0.02MB + Index: 0.16MB
wp_bp_activity_meta: Data: 0.02MB + Index: 0.03MB
wp_bp_friends: Data: 0.02MB + Index: 0.03MB
wp_bp_messages_messages: Data: 0.02MB + Index: 0.03MB
wp_bp_messages_notices: Data: 0.02MB + Index: 0.02MB
wp_bp_messages_recipients: Data: 0.02MB + Index: 0.08MB
wp_bp_notifications: Data: 0.02MB + Index: 0.11MB
wp_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB
wp_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB
wp_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB
wp_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.14MB + Index: 0.02MB
wp_comments: Data: 0.02MB + Index: 0.01MB
wp_hms_testimonials: Data: 0.02MB + Index: 0.00MB
wp_hms_testimonials_cf: Data: 0.02MB + Index: 0.00MB
wp_hms_testimonials_cf_meta: Data: 0.02MB + Index: 0.02MB
wp_hms_testimonials_groups: Data: 0.02MB + Index: 0.00MB
wp_hms_testimonials_group_meta: Data: 0.02MB + Index: 0.03MB
wp_hms_testimonials_templates: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 1.87MB + Index: 0.10MB
wp_postmeta: Data: 0.84MB + Index: 0.33MB
wp_posts: Data: 2.57MB + Index: 0.15MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_smooth_slider: Data: 0.00MB + Index: 0.00MB
wp_smooth_slider_meta: Data: 0.00MB + Index: 0.00MB
wp_smooth_slider_postmeta: Data: 0.00MB + Index: 0.00MB
wp_sp_sliders: Data: 0.01MB + Index: 0.00MB
wp_sp_slides: Data: 0.03MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.01MB + Index: 0.02MB
wp_term_relationships: Data: 0.01MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 0.02MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.02MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 2.52MB + Index: 0.00MB
wp_wfHits: Data: 0.08MB + Index: 0.05MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.03MB
wp_wfStatus: Data: 0.17MB + Index: 0.13MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

accordion_menu: 1
acf: 5
acf-field: 23
acf-field-group: 6
attachment: 127
boxes: 3
course: 2
custom_css: 1
customize_changeset: 41
envira: 2
et_pb_layout: 32
forum: 2
homecpt: 1
module: 13
module_response: 1
myportfolio: 5
nav_menu_item: 14
oembed_cache: 3
optionsframework: 7
page: 84
post: 31
product: 33
product_variation: 34
revision: 701
shop_coupon: 2
shop_order: 1
soliloquy: 1
sp_calendar: 1
sp_column: 8
sp_event: 6
sp_list: 4
sp_metric: 2
sp_outcome: 3
sp_performance: 5
sp_player: 12
sp_result: 3
sp_staff: 1
sp_statistic: 4
sp_table: 1
sp_team: 3
tailor_templates: 1
testimonial: 4
topic: 3
tribe_events: 1
tribe_venue: 1
unit: 4
wafs: 1
wooframework: 125
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.0-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: configurable (configurable)
downloadable (downloadable)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)
virtual (virtual)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #1638 - /shop/
Cart: #1639 - /cart/
Checkout: #1640 - /checkout/
My account: #1641 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Quark Child
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Quark
Parent Theme Version: 1.4
Parent Theme Author URL: http://maddisondesigns.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
Hi,

Thanks for posting on Github instead of emailing the .org team!

Did you want to send a PR for this since you've looked into the issue already? Or is there more to it than adding a missing class?

Cheers

**Comment by maddisondesigns** [comment]
I was going to create a PR but thought it probably best to post it here instead. As far as I can tell, it's just a missing class, but obviously you know the WC code better than me. In my testing, if I add that `woocommerce_options_panel` class to the `div` using the browser dev tools, all the fields format themselves as expected, so I'm pretty confident it's just an issue with that missing class. Also, all the other panels have this class.

**Comment by maddisondesigns** [comment]
Just creating a PR for you now

**Comment by maddisondesigns** [comment]
Created PR https://github.com/woocommerce/woocommerce/pull/19624
Let me know if I missed any steps in creating that for you.

**Comment by mikejolley** [comment]
After seeing how that PR broke styling of the panels with sub-sections I took another look.

- `woocommerce_options_panel` is used on panels which list input fields.
- `wc-metabox-wrapper` seems to be used on panels with subsections such as variations and attributes. These panels never list input fields at the top level.

Since these panels were not intended to list inputs (they have specialised designs), if you do insert extra content on them or around them you can wrap your fields with:

```
<div class="woocommerce_options_panel"></div>
``` 

This will fix styling. Alternatively add new tabs because I don't think it's expected behaviour to have input fields on these panels.

Thanks
