### ISSUE TITLE
Woocommerce reviews/rating tab issue

### ISSUE THREAD

**Issue by swatidetharia** [woocommerce/woocommerce#19622]
Hello, I am using woocommerce version 3.3.4 & wordpress version 4.9.5. I am doing integrating HTML tamplete to wordpress implimentation so mean while faced an issue like this.

I have integrated the html to wordpress and then install woocommerce plugin but in the detail product page Review / Rating Tabs is missing and also related products are not displayed in the same page.

I have done much R & D on this and also check that files and function for these features are already there in my wordpress. but why still they are not displayed???

I have also tried that 1st i install woocommerce and then try to set the theme then the all features are working fine with wordpress. so what's the problem??

Too much confused with this. Please help me ASAP. Thank you in advanced.

**Comment by peterfabian** [comment]
Hi Swati, 

I'm sorry but this is not really a forum to get development help, but a place where users report bugs in WooCommerce core.
However, this does not sound like a problem with WooCommerce core, therefore, I would suggest trying to reach out to developer community via e.g. [StackExchange](https://wordpress.meta.stackexchange.com/) or get help from [experienced developers](https://woocommerce.com/customizations/). (If you find a problem with WooCommerce code, please don't hesitate to create a new ticket where you describe how to reproduce the bug)


Some other resources that may be helpful to you:
- [developer handbooks](https://woocommerce.wordpress.com/2018/03/09/theme-and-plugin-developer-handbooks/)
- [Storefront theme source code](https://github.com/woocommerce/storefront/)
- WooCommerce source code, e.g. [related products default function](https://docs.woocommerce.com/wc-apidocs/source-function-woocommerce_related_products.html#830-849), etc.

**Comment by swatidetharia** [comment]
Thank you so much for your response.
