### ISSUE TITLE
6 thumbnails size instead of 3

### ISSUE THREAD

**Issue by wpchannel** [woocommerce/woocommerce#19635]
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

Before 3.3 we have 3 thumbnails size, since the upgrade we have 6. So it double the size of uploads folder now...

I've tested it on brand new WC install with latest version, on a production website just upgraded and with another person. I think it's a bug because I've found nothing in the documentation, SO, Git issues and Slack community in France.

<img width="1349" alt="capture d ecran 2018-04-05 a 16 11 59" src="https://user-images.githubusercontent.com/7568562/38408156-96adb200-397c-11e8-92fe-40fb601307ec.png">

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Customizing-image-sizes-in-3.3

shop_ sizes are legacy and there for backwards compat, but the sizes of those are the same as the new sizes. They will be removed in 4.0. This is not a bug.

**Comment by wpchannel** [comment]
Thanks for your reply. I'll take care of regenerating thumbnails for only new sizes to preserve storage.
