### ISSUE TITLE
Another Proposed Fix for Multilingual Variable Product Attributes

### ISSUE THREAD

**Issue by wywarren** [woocommerce/woocommerce#19630]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install the latest WooCommerce and qTranslateX plugin
Go to Settings > Languages > Languages Tab, and enable at least one other language. In my example I'm using English and Taiwan Traditional Chinese. They are marked with **[:en]** and **[:tw]**. If you are testing this with other language please double check for their language codes. If you want to test with the default German setting of qTranslate, **[:de]** is the language code.
2. Create a variable product and add attributes with qTranslate's multilingual format:

ie. 
**Name:** _[:en]Color[:tw]顏色[:]_
**Value(s):** _[:en]Red[:tw]紅[:] | [:en]Green[:tw]綠[:] | [:en]Blue[:tw]藍[:]_

3. Check off "Used for variations" and save
4. Go to the variations tab and "Create variations from all attributes". You should get 3 variants with the values posted above.
5. Publish the product and goto the product page. Swap between languages in the front end. Variations will not be displayed.

## Expected/actual behavior

When I follow those steps, I see...
No product variations listed in the front end for either language.

I was expecting to see...
Product variation options list in the site's current language.

## Proposed solution
I had originally proposed this:
https://github.com/woocommerce/woocommerce/issues/16623

and @mikejolley is correct in saying that the Wordpress **__()** localization function is only meant for strings not arrays.

So I decided to dig deeper and found the place where the attribute array is being created/or returned and found it in **includes/class-wc-product-variable.php:210**.

Originally the function looks like this:
`public function get_variation_attributes() {
	return $this->variation_attributes;
}`

I propose to fix it this way:
`public function get_variation_attributes() {
	$localized_attributes = array();

	$translated = false;
	foreach ( $this->variation_attributes as $key => $value ) {
		if(is_array($value)){
			$translated = true;
			for($i=0;$i<count($value);$i++) {	
				$value[$i] = __($value[$i]);
			}
		}
		$localized_attributes[ $key ] = $value;
	}

	if($translated) return $localized_attributes;
	else return $this->variation_attributes;
}`

I have tried this on my own sandbox and have verified variations are still showing. In this scenario we're preserving the key (as untranslated) but we're iterating the array to translate the individual values inside.

**Alternatively, you can edit class-wc-product-variation.php:103 to translate the values in the array there upon retrieval.**

I hope this is a step towards an unsolved problem for variable products that has been around for a long time.

Thanks!

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://shop.sellerlinx.com/qoobit
Site URL: https://shop.sellerlinx.com/qoobit
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 5.6.30-7+deb.sury.org~xenial+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: 5.6.27
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ❌ Your server does not have the DOMDocument class enabled - HTML/Multipart emails
and also some extensions
will not work without DOMDocument.

GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: slwp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.25MB
Database Data Size: 1.27MB
Database Index Size: 0.98MB
slwp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
slwp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
slwp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
slwp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
slwp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
slwp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
slwp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
slwp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
slwp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
slwp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
slwp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
slwp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
slwp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
slwp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
slwp_commentmeta: Data: 0.02MB + Index: 0.03MB
slwp_comments: Data: 0.02MB + Index: 0.09MB
slwp_iwp_backup_status: Data: 0.02MB + Index: 0.00MB
slwp_links: Data: 0.02MB + Index: 0.02MB
slwp_oauth_access_tokens: Data: 0.02MB + Index: 0.00MB
slwp_oauth_authorization_codes: Data: 0.02MB + Index: 0.00MB
slwp_oauth_clients: Data: 0.02MB + Index: 0.00MB
slwp_oauth_refresh_tokens: Data: 0.02MB + Index: 0.00MB
slwp_oauth_scopes: Data: 0.02MB + Index: 0.00MB
slwp_options: Data: 0.33MB + Index: 0.05MB
slwp_postmeta: Data: 0.14MB + Index: 0.16MB
slwp_posts: Data: 0.20MB + Index: 0.06MB
slwp_termmeta: Data: 0.02MB + Index: 0.03MB
slwp_terms: Data: 0.02MB + Index: 0.03MB
slwp_term_relationships: Data: 0.02MB + Index: 0.02MB
slwp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
slwp_usermeta: Data: 0.02MB + Index: 0.03MB
slwp_users: Data: 0.02MB + Index: 0.05MB
slwp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf: 1
attachment: 5
custom_css: 1
iwp_log: 47
nav_menu_item: 13
page: 15
post: 1
product: 6
product_variation: 3
revision: 270

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

CloudFlare Flexible SSL: by iControlWP – 1.2.2
JSON Basic Authentication: by WordPress API Team – 0.1
Advanced Custom Fields: qTranslate: by funkjedi – 1.7.23
ACF to REST API: by Aires Gonçalves – 3.1.0
Advanced Custom Fields: by Elliot Condon – 4.4.12
Allpay AIO for Woocommerce: by 因創科技 – 1.1.7 – Not tested with the active version of WooCommerce
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.2

CPT-onomies: Using Custom Post Types as Taxonomies: by Rachel Carden – 1.3.6
Google Tag Manager for Wordpress: by Thomas Geiger – 1.7.2
Google XML Sitemaps: by Arne Brachhold – 4.0.9
Hide Admin Bar: by Shelby DeNike – 0.3.9.1
InfiniteWP - Client: by Revmakx – 1.6.6.3
jQuery Updater: by Ramoonus – 3.3.1
WPBakery Visual Composer & qTranslate-X: by qTranslate Team – 1.0
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.5
PixelYourSite: by PixelYourSite – 5.2.0
QOO - Banners: by Warren Wang @ Qoobit Productions Inc. – 1.0
QOO - Branding: by Warren Wang @ Qoobit Productions Inc. – 1.0
QOO - Social Links: by Warren Wang @ Qoobit Productions Inc. – 1.0
qTranslate-X: by qTranslate Team – 3.4.6.8
WP REST API: by WP REST API Team – 2.0-beta15
Sellerlinx REST API Extension: by Warren Wang @ Sellerlinx – 1.0
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.2.5
WooCommerce AdWords Conversion Tracking: by Wolf+Bär Agency – 1.4.7
WooCommerce AdWords Dynamic Remarketing: by Wolf+Bär Agency – 1.4.5 – Not tested with the active version of WooCommerce
WooCommerce & qTranslate-X: by qTranslate Team – 1.3 – Not tested with the active version of WooCommerce
WooCommerce Social Login: by WooThemes / SkyVerge – 2.0.4 – 2.4.1 is available – Not tested with the active version of WooCommerce
WooCommerce WishLists: by Lucas Stark – 1.11.2 – 2.1.4 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.2.6 – 3.3.4 is available
WP Mail SMTP: by WPForms – 1.2.5
WP Maintenance Mode: by Designmodo – 2.1.2
WP REST API Controller: by YIKES
Inc.
Evan Herman
yikesitskevin – 1.4.1

Customizer Field EndPoint: by Bishal Basnet – 1.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Sellerlinx Storefront Theme
Version: 1.0.0
Author URL: https://qoobit.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.3 – 2.2.8 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
@wywarren We cannot add code to handle plugins specifically into core. The syntax used by Qtranslate is not a WordPress core standard - it's proprietary to qtranslate.

This needs to be handled either in a plugin (for compatibility) or qTranslate.

It looks like you will need some filters however; likely one in the data store (read_variation_attributes) or in the get_variation_attributes method.

I'd suggest:

1. Adding a filter to the above methods in your local install
2. Testing your code using the filter, instead of directly editing core files
3. If it works, document and submit a pull request to WooCommerce with the new filter you require.

Happy to review that and merge if it enables you to make qTranslate compatible.

Thanks
