### ISSUE TITLE
Issue in checking stock status at checkout

### ISSUE THREAD

**Issue by shreyans94** [woocommerce/woocommerce#19638]
Issue: Mark stock as 1 in test product and try to place order together on 3 devices and you will be able to checkout.

I consulted with Jabor Javorszky from Mindsize and below is what he suggested:

The stock check happens when adding things to the cart
once it's IN the cart, checkout will not triple check
`class-wc-cart.php`, look at `add_to_cart` method
there you'll see a bunch of stock checks
which call `$product->has_enough_stock()`
and yes, I've reproduced the issue
have 3 stock altogether
in browser 1, put 2 in the cart, continue to checkout page (do not checkout)
in browser 2, put another 2 in the cart, continue to checkout page
check out with both of them
successfully
resulting stock: -1

**Comment by shreyans94** [comment]
This won't be an issue for regular people but for high traffic site where a single product is sold in 100s or 1000s per day this becomes an issue.

**Comment by mikejolley** [comment]
This one is known and has no easy fix because it's a race condition. Documented with solution ideas in https://github.com/woocommerce/woocommerce/issues/16971 Thanks
