### ISSUE TITLE
woocommerce_rest_cannot_view error, for using ssl

### ISSUE THREAD

**Issue by eedea** [woocommerce/woocommerce#19649]
I get this responce since last week with no change in my code (which was working fine before):

```
{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot list resources.",
  "data": {
    "status": 401
  }
}
```

I tried testing in Postman and it was the same.
I have this issue only with HTTPS url (using Basic Auth) and I can get correct response with same set of keys on same site with HTTP connection (Using OAuth 1.0)

**Comment by kloon** [comment]
Bit difficult to say for sure since you did not provide a system status report as requested when opening an issue. However from the error it seems something might have changed with your https setup, are you sure you have https enabled and it is the default protocol for your site?

Since you say http works fine I am inclined to think that your https might not be set up, or more specifically looking at the error it might be pointing to another installation which does not have the credentials you are using.

When I test this locally using https and http pointing to the same install I can access both instances fine with the same credentials.

**Comment by eedea** [comment]
Sorry for deficent information. I hope It's enough:











## Prerequisites



- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue



1. Enable the REST API
2. Get a set of Keys with full read and write admin access
3. make a request for anything that needs authorization using https URL (ie. https://hosturlwp-json/wc/v2/products) and Basic auth.

## Expected/actual behavior

When I follow those steps, I get error 401 and the following responce instead  of actual data (ie. list of products):

`{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot list resources.",
  "data": {
    "status": 401
  }
}`

and this work fine with HTTP URL and Oauth 1.0 
## Isolating the problem



- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: ****
Site URL: ****
WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fa_IR

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.29
PHP Post Max Size: 8 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: NOON_
MaxMind GeoIP Database: ✔
اندازه کل پایگاه داده: 6.21MB
اندازه داده های پایگاه داده: 4.83MB
اندازه فهرست پایگاه داده: 1.38MB
NOON_woocommerce_sessions: داده ها: 0.27 مگابایت + فهرست: 0.01 مگابایت
NOON_woocommerce_api_keys: داده ها: 0.00 مگابایت + فهرست: 0.01 مگابایت
NOON_woocommerce_attribute_taxonomies: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_woocommerce_downloadable_product_permissions: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_woocommerce_order_items: داده ها: 0.05 مگابایت + فهرست: 0.03 مگابایت
NOON_woocommerce_order_itemmeta: داده ها: 0.29 مگابایت + فهرست: 0.24 مگابایت
NOON_woocommerce_tax_rates: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_woocommerce_tax_rate_locations: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_woocommerce_shipping_zones: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_woocommerce_shipping_zone_locations: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_woocommerce_shipping_zone_methods: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_woocommerce_payment_tokens: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_woocommerce_payment_tokenmeta: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_woocommerce_log: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_commentmeta: داده ها: 0.00 مگابایت + فهرست: 0.01 مگابایت
NOON_comments: داده ها: 0.07 مگابایت + فهرست: 0.04 مگابایت
NOON_layerslider: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_links: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_options: داده ها: 1.01 مگابایت + فهرست: 0.05 مگابایت
NOON_postmeta: داده ها: 2.01 مگابایت + فهرست: 0.51 مگابایت
NOON_posts: داده ها: 0.49 مگابایت + فهرست: 0.14 مگابایت
NOON_revslider_css: داده ها: 0.09 مگابایت + فهرست: 0.00 مگابایت
NOON_revslider_layer_animations: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_revslider_navigations: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_revslider_sliders: داده ها: 0.01 مگابایت + فهرست: 0.00 مگابایت
NOON_revslider_slides: داده ها: 0.17 مگابایت + فهرست: 0.00 مگابایت
NOON_revslider_static_slides: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_termmeta: داده ها: 0.00 مگابایت + فهرست: 0.01 مگابایت
NOON_terms: داده ها: 0.02 مگابایت + فهرست: 0.04 مگابایت
NOON_term_relationships: داده ها: 0.01 مگابایت + فهرست: 0.02 مگابایت
NOON_term_taxonomy: داده ها: 0.01 مگابایت + فهرست: 0.01 مگابایت
NOON_usermeta: داده ها: 0.29 مگابایت + فهرست: 0.23 مگابایت
NOON_users: داده ها: 0.04 مگابایت + فهرست: 0.03 مگابایت
NOON_yoast_seo_links: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت
NOON_yoast_seo_meta: داده ها: 0.00 مگابایت + فهرست: 0.00 مگابایت

### Post Type Counts ###

attachment: 429
nav_menu_item: 17
page: 12
post: 18
product: 35
revision: 118
shop_coupon: 8
shop_order: 182
shop_order_refund: 1
shop_webhook: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌فروشگاه شما از HTTPS استفاده نمی کند. اطلاعات بیشتر درباره HTTPS و SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (15) ###

LayerSlider WP: توسط Kreatura Media – 5.6.9
Aparat: توسط Nima Saberi – 1.3
فرم تماس: توسط تاکایوکی میوشی | پشتیبانی فارسی: فرهاد سخایی (پارس میزبان) – 5.0.1
Duplicate Post: توسط Enrico Battocchi – 3.2.1
Export User Data: توسط Q Studio – 1.3.1
Force Regenerate Thumbnails: توسط Pedro Elsner – 2.0.6
WPBakery Visual Composer: توسط Michael M - WPBakery.com – 4.12.1
افزونه حرفه ای پیامک ووکامرس: توسط ووکامرس فارسی – 3.7.0
Protect WP-Admin: توسط MR Web Solution – 2.9
Slider Revolution: توسط ThemePunch – 5.2.6
ووکامرس: توسط اتوماتیک – 3.2.6 – 3.3.4 در دسترس است.
Yoast SEO Premium: توسط تیم Yoast – 4.4
وردپرس فارسی: توسط زاکروت، راهکارهای مبتنی بر وب - با همکاری تیم وردپرس فارسی – 5.0.1
Yoast SEO: News: توسط پرشین اسکریپت – 5.2
افزونه پرداخت امن زرین پال برای ووکامرس: توسط Masoud Amini – 4.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: IRR (ریال)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

پایگاه فروشگاه: #86 - /%d9%81%d8%b1%d9%88%d8%b4%da%af%d8%a7%d9%87/
سبد خرید: ❌ شناسه برگه تنظیم شد اما برگه وجود ندارد
پرداخت: #88 - /%d9%be%d8%b1%d8%af%d8%a7%d8%ae%d8%aa/
حساب کاربری من: #89 - /%d8%ad%d8%b3%d8%a7%d8%a8-%da%a9%d8%a7%d8%b1%d8%a8%d8%b1%db%8c-%d9%85%d9%86/
شرایط و ضوابط: ❌ برگه تنظیم نشده است

### Theme ###

Name: Betheme
Version: 14.7
Author URL: http://bigtheme.ir
Child Theme: ❌ – اگر شما در حال ویرایش و شخصی سازی ووکامرس روی قالب والد هستید پیشنهاد می کنیم از قالب فرزند استفاده کنید. ببینید : چگونه یک قالب فرزند بسازیم
WooCommerce Support: ✔

### Templates ###

Overrides: betheme/woocommerce/archive-product.php
betheme/woocommerce/cart/cart-empty.php نسخه 2.0.0 تاریخ گذشته است . نسخه اصلی هست 3.1.0
betheme/woocommerce/cart/cart.php نسخه 2.3.8 تاریخ گذشته است . نسخه اصلی هست 3.1.0
betheme/woocommerce/cart/mini-cart.php نسخه 2.5.0 تاریخ گذشته است . نسخه اصلی هست 3.2.0
betheme/woocommerce/content-product.php نسخه 2.6.1 تاریخ گذشته است . نسخه اصلی هست 3.0.0
betheme/woocommerce/content-single-product.php نسخه 1.6.4 تاریخ گذشته است . نسخه اصلی هست 3.0.0
betheme/woocommerce/loop/loop-end.php
betheme/woocommerce/loop/loop-start.php
betheme/woocommerce/loop/no-products-found.php
betheme/woocommerce/loop/orderby.php
betheme/woocommerce/loop/pagination.php
betheme/woocommerce/loop/price.php
betheme/woocommerce/loop/rating.php نسخه 2.0.0 تاریخ گذشته است . نسخه اصلی هست 3.0.0
betheme/woocommerce/loop/result-count.php نسخه 2.0.0 تاریخ گذشته است . نسخه اصلی هست 3.0.0
betheme/woocommerce/loop/sale-flash.php
betheme/woocommerce/notices/error.php
betheme/woocommerce/notices/notice.php
betheme/woocommerce/notices/success.php
betheme/woocommerce/single-product/add-to-cart/external.php
betheme/woocommerce/single-product/meta.php نسخه 1.6.4 تاریخ گذشته است . نسخه اصلی هست 3.0.0
betheme/woocommerce/single-product/price.php نسخه 2.4.9 تاریخ گذشته است . نسخه اصلی هست 3.0.0
betheme/woocommerce/single-product/product-attributes.php نسخه 2.1.3 تاریخ گذشته است . نسخه اصلی هست 3.1.0
betheme/woocommerce/single-product/product-image.php نسخه 2.6.3 تاریخ گذشته است . نسخه اصلی هست 3.1.0
betheme/woocommerce/single-product/product-thumbnails.php نسخه 2.6.3 تاریخ گذشته است . نسخه اصلی هست 3.1.0
betheme/woocommerce/single-product/related.php نسخه 1.6.4 تاریخ گذشته است . نسخه اصلی هست 3.0.0
betheme/woocommerce/single-product/sale-flash.php
betheme/woocommerce/single-product/share.php
betheme/woocommerce/single-product/short-description.php
betheme/woocommerce/single-product/tabs/additional-information.php نسخه 2.0.0 تاریخ گذشته است . نسخه اصلی هست 3.0.0
betheme/woocommerce/single-product/tabs/description.php
betheme/woocommerce/single-product/tabs/tabs.php
betheme/woocommerce/single-product/title.php
betheme/woocommerce/single-product/up-sells.php نسخه 1.6.4 تاریخ گذشته است . نسخه اصلی هست 3.0.0
betheme/woocommerce/single-product.php

Outdated Templates: ❌چگونگی به روز رسانی را بیاموزید
`
```
</details>

I'm just the app developer and my code was working for about a year. apparently the only thing that changes lately is that the ssl certificate got extended. but they just asked the previous provider to extend it and no key has changed. also they did this 2 times before and it didn't affect the api before.
and to be sure, I checked their site with ssllabs.com and every thing seems to be fine.

**Comment by kloon** [comment]
As suspected and from the system status report you do not have SSL enabled on your site so the SSL option will not work. Chances are that your SSL url is probably pointing to a different domain.

**Comment by eedea** [comment]
It was working fine with that Settings. and now we set security as well but the resault is still the same
`### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔
`

**Comment by xewl** [comment]
I've been looking into this same error,
turned out it was a plug-in causing the discrepancy.
Requests via the browser, would work perfectly, but curl-requests, would fail with a 401 "woocommerce_rest_cannot_view"
In my case: https://wordpress.org/plugins/login-to-see-add-to-cart-and-prices-in-woocommerce/

I'd suggest deactivating and reactivating some of the plugins that hook into WooCommerce.

**Comment by chris-brighton** [comment]
@xewl Thanks so much for this tip! Spent hours looking at .PEM certs, server settings, Curl settings, .htaccess, of course API credentials, etc. etc. 

Turned out it was a plugin as well. Didn't realize that Woo endpoints are affected by plugin code!

**Comment by briedis** [comment]
@chris-brighton Which plugin was it?

**Comment by dadeke** [comment]
I reseted permalink settings.

Make sure they're not on the default ( which is no pretty permalinks).

It's work. \o/

**Comment by briedis** [comment]
@dadeke  Did you experience this issue only for products endpoint or other endpoints too? I'm experiencing this for _every_ endpoint (for example, `/system_status`)

**Comment by dadeke** [comment]
@briedis Other endpoints too.

It works without authentication: https://example.com/?rest_route=/wc/v3
Not works: https://example.com/?rest_route=/wc/v3/products
Not works with authentication: https://example.com/?rest_route=/wc/v3/system_status

It works without authentication: https://example.com/wp-json/wc/v3
It works: https://example.com/wp-json/wc/v3/products
It works: https://example.com/wp-json/wc/v3/system_status

**Comment by ganeshkrishnan1** [comment]
For people who are coming to this issue from a search engine:
Make sure your server is passing the auth headers to wordpress.
For eg if you have .htaccess add these lines
```
SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0
RewriteRule ^wp-json/.* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
```
