### ISSUE TITLE
Admin Product Search Issues

### ISSUE THREAD

**Issue by fhaps** [woocommerce/woocommerce#19648]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Login to your Dashboard, head to **Products > Add New**.
2. Create a product that has a three-word title (i.e. Green Nylon Shorts), **Publish**.
3. Go to **Products > All products** and search for the product using the first and last words of the product title, omitting the middle word (i.e. Green Shorts).

## Expected/actual behavior

When I follow those steps, no product results come up, I see a message that says `No products found`.

I have to search for the exact title of the product, including all three words (i.e. Green Nylon Shorts) for it to be displayed. If I search for `Green Nylon`(only omitting the third word) the product does come up in the search results.

Rolling WooCommerce back to version 3.2.5 corrects the issue. On this version, if I search for `Green Shorts` only the product does come up in the results:

![](http://cld.wthms.co/AHzO67+)
Image Link: http://cld.wthms.co/AHzO67

I found PR #18843 that address some search issues, but that only seemed to affect SKU searches, as this issue still is happening in the latest version of the plugin.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by kloon** [comment]
@fhaps when I test this on the master branch I get the correct results http://cld.wthms.co/X2LZ5B

You checked you tested against the master branch but it seems you did not, we made changes to the search in master branch a while back that will be going out with 3.4 which fixes the issue you describe as can be seen from my screenshot.
