### ISSUE TITLE
woocommerce_wp_text_input doesn't pull props from data store

### ISSUE THREAD

**Issue by dgrana** [woocommerce/woocommerce#19641]
Not really a bug but a blocker.

I've created a custom coupon data store, but when reading it from the edit view in the CMS it won't retrieve the amount because the text input rendered is retrieving it from postmeta and not from the data store (which pulls from a coupons custom table).

Here's the specific line:
https://github.com/woocommerce/woocommerce/blob/master/includes/admin/wc-meta-box-functions.php#L27

And here's where it's used for coupon specifically:
https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-coupon-data.php#L85

Thank you

**Comment by kloon** [comment]
@dgrana all the woocommerce_wp_* functions can take a value option in the passed array, it just has a default fallback to look up using metadata when no value is specified.

Ideally, those function usage for coupons should be converted to use the coupon class getters and pass the values as a value option in the array when calling it.

Marking it as an enhancement, feel free to contribute to converting those function calls should you wish.

**Comment by mikejolley** [comment]
Other screens just pass the value along when calling `woocommerce_wp_text_input`.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19670
