### ISSUE TITLE
Label and Input for checkout are in wrong order

### ISSUE THREAD

**Issue by Bentipa** [woocommerce/woocommerce#19646]
I use the default woocomerce (3.3.4) checkout page, but in the billing form, the input and its label are generated in the wrong order:

https://i.imgur.com/Txq3Hws.png

## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

It's just the default woocommerce installation for wordpress, nothing else changed to reproduce the issue.

## Expected/actual behavior

The form field being in the right order so looking like it should.

## Isolating the problem

- [ x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/) [not able to test, for multiple reasons, but the issue not created by theme, etc.]
- [ x ] I can reproduce this bug consistently using the steps above

## WordPress Environment
_not possible to privacy issue, should be able to ne solved without report_

**Comment by kloon** [comment]
Since you left out your WP Environment page I can't really give a definite answer, but I am 99% sure your issue lies with your theme or a third party plugin. When I test this with the latest WC and master branch the label is first and then the input as it should be. http://cld.wthms.co/cb4Wvg

I am also noticing the field name containing myfield7 which means something is definitely changing the fields on checkout, so that might be your problem.

**Comment by Bentipa** [comment]
Hey,
i've found these lines (https://goo.gl/b67Wx5) in form-billing.php inside woocommerce/templates/checkout/form-billing.php where the input is in side the label. Is this also an template/third party plugin issue?

**Comment by willgorham** [comment]
@Bentipa 
An input inside a label is perfectly fine syntax. See the first example here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by willgorham** [comment]
@Bentipa I don't believe forms.less exists in WC core - it's probably an issue with your theme in that case.
