### ISSUE TITLE
wc doesn't work with a wc theme : Woodance from MB theme

### ISSUE THREAD

**Issue by isa06am** [woocommerce/woocommerce#19651]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by isa06am** [comment]
Details of system status :
`
### WordPress Environment ###

Home URL: http://myboutiquedermo.dermotechnic.com
Site URL: http://myboutiquedermo.dermotechnic.com
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: ❌ 40 MB - Nous recommandons l’augmentation de la mémoire à 64Mo minimum. Voir : Augmenter la mémoire allouée à PHP
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.15
PHP Post Max Size: 6 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.59 - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: nHotP
MaxMind GeoIP Database: ✔
Taille totale de la base de données: 16.07MB
Taille de la base de données: 14.77MB
Taille de l’index: 1.30MB
nHotPwoocommerce_sessions: Donnée : 0.15MB + Index: 0.01MB
nHotPwoocommerce_api_keys: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_attribute_taxonomies: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_downloadable_product_permissions: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_order_items: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_order_itemmeta: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_tax_rates: Donnée : 0.00MB + Index: 0.01MB
nHotPwoocommerce_tax_rate_locations: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_shipping_zones: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_shipping_zone_locations: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_shipping_zone_methods: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_payment_tokens: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_payment_tokenmeta: Donnée : 0.00MB + Index: 0.00MB
nHotPwoocommerce_log: Donnée : 0.00MB + Index: 0.00MB
nHotPcommentmeta: Donnée : 0.00MB + Index: 0.00MB
nHotPcomments: Donnée : 0.00MB + Index: 0.01MB
nHotPlinks: Donnée : 0.00MB + Index: 0.00MB
nHotPoptions: Donnée : 1.62MB + Index: 0.05MB
nHotPpostmeta: Donnée : 7.25MB + Index: 0.55MB
nHotPposts: Donnée : 5.25MB + Index: 0.20MB
nHotPsm_sessions: Donnée : 0.00MB + Index: 0.00MB
nHotPtermmeta: Donnée : 0.01MB + Index: 0.01MB
nHotPterms: Donnée : 0.01MB + Index: 0.01MB
nHotPterm_relationships: Donnée : 0.01MB + Index: 0.02MB
nHotPterm_taxonomy: Donnée : 0.01MB + Index: 0.01MB
nHotPtrp_dictionary_fr_fr_en_us: Donnée : 0.13MB + Index: 0.08MB
nHotPtrp_gettext_: Donnée : 0.00MB + Index: 0.00MB
nHotPtrp_gettext_en_us: Donnée : 0.02MB + Index: 0.04MB
nHotPtrp_gettext_fr_fr: Donnée : 0.31MB + Index: 0.28MB
nHotPusermeta: Donnée : 0.00MB + Index: 0.01MB
nHotPusers: Donnée : 0.00MB + Index: 0.01MB
nHotPwc_download_log: Donnée : 0.00MB + Index: 0.00MB
nHotPwc_webhooks: Donnée : 0.00MB + Index: 0.00MB

### Post Type Counts ###

acf: 2
attachment: 564
custom_css: 1
customize_changeset: 133
fw-portfolio: 22
language_switcher: 3
nav_menu_item: 85
oembed_cache: 2
page: 52
post: 11
product: 65
revision: 911
simple-pay: 1
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ❌Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ✔

### Active Plugins (18) ###

Advanced Custom Fields: par Elliot Condon – 4.4.12
Black Studio TinyMCE Widget: par Black Studio – 2.6.2
Contact Form 7: par Takayuki Miyoshi – 5.0.1
Duplicate Page: par mndpsingh287 – 2.6
Jetpack par WordPress.com: par Automattic – 6.0
Google Fonts for WordPress: par Danny Cooper – 1.1.1
Regenerate Thumbnails: par Alex Mills (Viper007Bond) – 3.0.2
WP Simple Pay (Lite Version): par WP Simple Pay – 2.0.9
TinyMCE Advanced: par Andrew Ozz – 4.6.7
TranslatePress - Multilingual: par Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 1.2.0

Unyson: par ThemeFuse – 2.7.12
UpdraftPlus - Sauvegarde/Restauration: par UpdraftPlus.Com
DavidAnderson – 1.14.5

WooCommerce PayPal Express Checkout Gateway: par WooCommerce – 1.5.3
WooCommerce Stripe Gateway: par WooCommerce – 4.0.7
WooCommerce: par Automattic – 3.3.4
WP-PostViews: par Lester 'GaMerZ' Chan – 1.75
WP Retina 2x: par Jordy Meow – 5.2.3
WPCustom Category Image: par Eduardo Stuart – 2.1.13

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base boutique: #767 - /boutique/
Panier: #768 - /panier/
Commande: #769 - /paiement/
Mon compte: #770 - /mon-compte/
Conditions générales de vente et d’utilisation: #1862 - /conditions-generales-de-vente/

### Theme ###

Name: Woodance Enfant
Version: 1.0
Author URL: https://myboutiquedermo.com
Child Theme: ✔
Parent Theme Name: Woodance
Parent Theme Version: 1.0.2
Parent Theme Author URL: http://themeforest.net/user/mb_theme
WooCommerce Support: ✔

### Templates ###

Overrides: woodance/woocommerce/archive-product.php
woodance/woocommerce/cart/cart-empty.php
woodance/woocommerce/cart/cart-item-data.php
woodance/woocommerce/cart/cart-shipping.php
woodance/woocommerce/cart/cart-totals.php
woodance/woocommerce/cart/cart.php
woodance/woocommerce/cart/cross-sells.php
woodance/woocommerce/cart/mini-cart.php
woodance/woocommerce/cart/proceed-to-checkout-button.php
woodance/woocommerce/cart/shipping-calculator.php
woodance/woocommerce/checkout/cart-errors.php
woodance/woocommerce/checkout/form-billing.php
woodance/woocommerce/checkout/form-checkout.php
woodance/woocommerce/checkout/form-coupon.php
woodance/woocommerce/checkout/form-login.php
woodance/woocommerce/checkout/form-pay.php
woodance/woocommerce/checkout/form-shipping.php
woodance/woocommerce/checkout/payment-method.php
woodance/woocommerce/checkout/payment.php
woodance/woocommerce/checkout/review-order.php
woodance/woocommerce/checkout/terms.php
woodance/woocommerce/checkout/thankyou.php
woodance/woocommerce/content-product.php
woodance/woocommerce/content-product_cat.php
woodance/woocommerce/content-single-product.php
woodance/woocommerce/content-widget-product.php
woodance/woocommerce/global/breadcrumb.php
woodance/woocommerce/global/form-login.php
woodance/woocommerce/global/quantity-input.php
woodance/woocommerce/global/sidebar.php
woodance/woocommerce/global/wrapper-end.php
woodance/woocommerce/global/wrapper-start.php
woodance/woocommerce/loop/add-to-cart.php
woodance/woocommerce/loop/loop-end.php
woodance/woocommerce/loop/loop-start.php
woodance/woocommerce/loop/no-products-found.php
woodance/woocommerce/loop/orderby.php
woodance/woocommerce/loop/pagination.php
woodance/woocommerce/loop/price.php
woodance/woocommerce/loop/rating.php
woodance/woocommerce/loop/result-count.php
woodance/woocommerce/loop/sale-flash.php
woodance/woocommerce/notices/error.php
woodance/woocommerce/notices/notice.php
woodance/woocommerce/notices/success.php
woodance/woocommerce/order/form-tracking.php
woodance/woocommerce/order/order-again.php
woodance/woocommerce/order/order-details-customer.php
woodance/woocommerce/order/order-details-item.php
woodance/woocommerce/order/order-details.php
woodance/woocommerce/order/tracking.php
woodance/woocommerce/product-searchform.php
woodance/woocommerce/single-product/add-to-cart/external.php
woodance/woocommerce/single-product/add-to-cart/grouped.php
woodance/woocommerce/single-product/add-to-cart/simple.php
woodance/woocommerce/single-product/add-to-cart/variable.php
woodance/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
woodance/woocommerce/single-product/add-to-cart/variation.php
woodance/woocommerce/single-product/meta.php
woodance/woocommerce/single-product/price.php
woodance/woocommerce/single-product/product-attributes.php
woodance/woocommerce/single-product/product-image.php
woodance/woocommerce/single-product/product-thumbnails.php
woodance/woocommerce/single-product/rating.php
woodance/woocommerce/single-product/related.php
woodance/woocommerce/single-product/review-meta.php
woodance/woocommerce/single-product/review-rating.php
woodance/woocommerce/single-product/review.php
woodance/woocommerce/single-product/sale-flash.php
woodance/woocommerce/single-product/share.php
woodance/woocommerce/single-product/short-description.php
woodance/woocommerce/single-product/tabs/additional-information.php
woodance/woocommerce/single-product/tabs/description.php
woodance/woocommerce/single-product/tabs/tabs.php
woodance/woocommerce/single-product/title.php
woodance/woocommerce/single-product/up-sells.php
woodance/woocommerce/single-product-reviews.php
woodance/woocommerce/single-product.php
woodance/woocommerce/taxonomy-product_cat.php

`

**Comment by mikejolley** [comment]
Sorry but this report is backwards - WooDance is not compatible with WooCommerce :) I'd recommend reporting any issues you notice to the author. Since they use template overrides, they are responsible for compatibility issues (we actually recommend against that). 

https://github.com/woocommerce/woocommerce/wiki/Template-File-Guidelines-for-Devs-and-Theme-Authors

Thanks
