### ISSUE TITLE
International endpoints for edit-address/billing and edit-address/shipping

### ISSUE THREAD

**Issue by losingle** [woocommerce/woocommerce#19653]
This functionality was added a while ago: #13293

```php
$value = ( get_option( 'woocommerce_myaccount_edit_address_endpoint', 'edit-address' ) == $endpoint ) ? wc_edit_address_i18n( $value ) : $value;
```
If you do this, it will cause the link address of the Chinese character to be incorrect.
e.g. my-account/edit-address/账单/ 
In China, we do not recommend including Chinese characters in the link address.
In the case of zh-CN i18n, it is "Oops! That page can't be found".

**Comment by kloon** [comment]
@losingle the default strings comes from the translation files, however, it is also user controller as you can change it via WooCommerce > Settings > Checkout and > Accounts.

If you do not want it translated then please make the changes at the pages I mentioned above.

**Comment by losingle** [comment]
url strings will be translated ?

my-account/edit-address/billing/  -> my-account/edit-address/{billing_i18n_name}/

my-account/edit-address/shipping/ -> my-account/edit-address/{shipping_i18n_name}/
