### ISSUE TITLE
Country search on WooExperts page shows "HTTP ERROR 500" 

### ISSUE THREAD

**Issue by arunsathiya** [woocommerce/woocommerce#19652]
**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Start at https://woocommerce.com/experts
- Choose a country from the "Country" list
- Click "Search"

**What is expected:** WooExperts from that country are shown

**What happens instead:** Takes me to that country page (in this format: https://woocommerce.com/experts/?country=Canada&paged=1) and shows a **HTTP ERROR 500** notice.

**Comment by mikejolley** [comment]
Thanks, I've logged this in the correct place.
