### ISSUE TITLE
Problem with the names of the metadata in the export and import of products in CSV format

### ISSUE THREAD

**Issue by laurantines** [woocommerce/woocommerce#19656]
Hi team!

I have created several metadata for my products, the problem is that when I export the products in CSV format (natively in WooCommerce) with the metadata, the name that is given to each column does not correspond to the name of the import.

For example, when I export the name of the column is "Meta: _wpt_field_ingredients", however, in the import, if I call it that, the content does not upload, I had to rename it and put "meta: _wpt_field_ingredientes" with the lowercase m and without space between ": and _"

Thank you!

**Comment by mikejolley** [comment]
I don't think there is a bug, not the with importer in core.

File: 
![monosnap 2018-04-10 12-48-34](https://user-images.githubusercontent.com/90977/38555286-7e6919a2-3cbd-11e8-894c-41886fc2cf00.png)

Import process:
![product import local wordpress dev wordpress 2018-04-10 12-48-14](https://user-images.githubusercontent.com/90977/38555294-8346b772-3cbd-11e8-9e61-5d152ec8b95b.png)

Result:
![slack - a8c 2018-04-10 12-47-35](https://user-images.githubusercontent.com/90977/38555300-8a77557e-3cbd-11e8-98f1-15aa8ee34064.png)

You'll need to provide a sample if you think there is a bug but I'm not seeing an issue here. Maybe try my simplified test case above.

Thanks
