### ISSUE TITLE
Woocommerce shipping cost filter

### ISSUE THREAD

**Issue by LUKANDSP** [woocommerce/woocommerce#19659]
Hello !
I'm developing a plugin for personal use, and it works as follows: It checks if the post code informed is in a range of post code and a minimum value of subtotal, so a certain method of submission is free.
For this I used the 'woocommerce_package_rates' filter, but it works only on the first time you calculate the freight, then the filter stops working. Here is my code:

````
public function __construct() {
        add_filter('woocommerce_package_rates', array($this, 'change_shipping_value'));
    }
```

    public function change_shipping_value($rates, $packages = array()) {
        $fg = new FG_Integration();
        $postcode = $fg->clear_postcode($_POST['calc_shipping_postcode']);

        $rules = $fg->get_rules_by_postcode($postcode);

        foreach ($rules as $rule) {
            foreach ($rates as $rate_key => $rate) {
                if ($rates[$rate_key]->method_id == $rule->modalidade) {
                    $cart_subtotal = WC()->cart->subtotal;
                    if ($cart_subtotal >= $rule->valor_minimo) {
                        $rates[$rate_key]->cost = 0;
                    }
                }
            }
        }
        return $rates;
    }`

**Comment by mikejolley** [comment]
Rates are cached. So it will run once, and then won't run again until cart contents or shipping address is changed. This is how it should work.

**Comment by LUKANDSP** [comment]
Thanks @mikejolley  for explaining it for me!
