### ISSUE TITLE
Expose detailed coupon discounts on cart/order

### ISSUE THREAD

**Issue by ragulka** [woocommerce/woocommerce#19665]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Looks like there is no way to determine which products a coupon discounts, even though the `WC_Discounts` class does provide a `get_discounts()` method that provides this information:
```
Array
(
    [b39ivsnc] => Array
        (
            [1124] => 23.4
            [1122] => 7.8
            [1123] => 7.8
        )

    [25off] => Array
        (
            [1124] => 23.4
            [1122] => 3.05
            [1123] => 3.05
        )

)
```

The issue is that this [information is discarded right after discounts have been calculated](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/class-wc-cart-totals.php#L714-L770), and it's nowhere exposed to 3rd parties. The `WC_Cart_Totals::calculate_discounts()` creates the `WC_Discounts` instance [here](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/class-wc-cart-totals.php#L717), [applies the coupons](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/class-wc-cart-totals.php#L722-L724), and even [calls](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/class-wc-cart-totals.php#L731) the `get_discounts()` method, but does not store the results anywhere, nor exposes them in any way.

1. Add many different items to cart
2. Add a coupon that can be used for 2 or more items in the cart and is limited to 1 item only (limit_usage_to_x_items=1)
3. The coupon is applied against the highest priced item
4. Programmatically, there is no way to determine which product the coupon discounts

## Expected/actual behavior

In certain situations, it might be useful or even necessary to know which items were discounted by the coupon. At the moment, this is hard to determine without fully recalculating cart totals/discounts (which also means duplicating the code in `WC_Cart_Totals::calculate_discounts()`, as the $discounts instance is never attached to the cart_totals instance, which is also never attached to the cart instance - both class instances are thrown away right after use.

I would assume that this information be exposed either through an action/filter or be stored on the order instance, preferrably on the coupon order item meta.

**Comment by mikejolley** [comment]
> In certain situations

Please be more specific. The calculation logic is internal; I don't think we should store it (could get large) nor should it be filterable to mess with default calculations IMO.

> both class instances are thrown away right after use.

The classes are simply to perform the calculation. They should not be persisted or stored anywhere. If calculations are needed again, create new instances, pass in new data, get back calculation data.

It could be exposed, but not sure where without know what "In certain situations" actually means.

**Comment by ragulka** [comment]
Related to the above, it looks like manual/virtual coupons are not loaded using the coupon code when recalculating coupons for an order. It happens because the coupon code is not passed to the coupon constructor [here](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/abstracts/abstract-wc-order.php#L1027), but is only set later [here](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/abstracts/abstract-wc-order.php#L1029). There is [another filter](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/abstracts/abstract-wc-order.php#L1050) that can be used inside this method, but I'm wondering what's the reasoning to not pass the coupon code to the coupon constructor?

**Comment by mikejolley** [comment]
@ragulka Percent discounts are divided across all items in the cart so taxes work correctly; thats why I said these calculations were internal. There is no 1:1 relationship between a coupon/discount and each item if that makes sense?

@bor0 You've worked with coupons - any suggestions?

> Related to the above, it looks like manual/virtual coupons are not loaded using the coupon code when recalculating coupons for an order.

The code in question is commented; there is no coupon object/code for virtual coupons, so it just has to work with whatever data was stored to the order.

**Comment by ragulka** [comment]
> Percent discounts are divided across all items in the cart so taxes work correctly; thats why I said these calculations were internal. There is no 1:1 relationship between a coupon/discount and each item if that makes sense?

My apologies, I should have been more clear - in our use case, the coupon is limited to one or several products. In this case, there _is_ a link, as the discount is not distributed across _all_ products, but rather those that it is valid for.

> The code in question is commented; there is no coupon object/code for virtual coupons, so it just has to work with whatever data was stored to the order.

The coupon code could be passed to the constructor [here](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/abstracts/abstract-wc-order.php#L1027), which would pass it to the filter [here](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/class-wc-coupon.php#L90), which is used when loading data for virtual/manual coupons, right? You have the same data in cart as well as on the order - the coupon code.

**Comment by mikejolley** [comment]
@ragulka The constructor takes coupon ID, not code. Virtual coupons have no ID.

**Comment by ragulka** [comment]
> The constructor takes coupon ID, not code. Virtual coupons have no ID.

@mikejolley It also takes the coupon code, as done by core in multiple places, for example [here](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/class-wc-cart.php#L1575-L1576) and [here](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/abstracts/abstract-wc-order.php#L923). Looks like this is how the coupons are loaded / applied in cart and on orders in the first place.

**Comment by mikejolley** [comment]
@ragulka Ok. But core is not using virtual coupons.

https://github.com/woocommerce/woocommerce/blob/b51626f183aa52d275484d6734cb987ea0f7c069/includes/class-wc-coupon.php#L97 This line will fail if the code doesn't match up with an existing ID.

Virtual coupons I assume in your case were generated here? https://github.com/woocommerce/woocommerce/blob/b51626f183aa52d275484d6734cb987ea0f7c069/includes/class-wc-coupon.php#L90

**Comment by ragulka** [comment]
@mikejolley I'm aware that core does not use/generate virtual coupons itself, but it does support them, right? I'm loading the virtual coupon data from a CPT in the `woocommerce_get_shop_coupon_data` filter, as you have pointed out. This filter gets the coupon code or id (whatever is passed to the constructor) as the 2nd argument.

Normally, WC will pass in the code, but when recalculating coupons for an order, it's not passing in anything, which makes this filter useless, as there's nothing to identify the coupon by. My question was - is there a reason the coupon code is not passed in on [this line](https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/abstracts/abstract-wc-order.php#L1027) or is this unintended and the code _should_ be passed in? As you can see, even the docblock says that one of coupon data, id or code can be passed to the constructor: https://github.com/woocommerce/woocommerce/blob/fcb2a3136e3cacfef7f12687816f5b2438605c86/includes/class-wc-coupon.php#L81-L83

**Comment by mikejolley** [comment]
@ragulka I have a feeling this is due to trying to support a legacy filter. However, more so in this case the data is already saved i.e. the original coupon data set via `woocommerce_get_shop_coupon_data` is already saved to the order, so when the coupon is constructed it should match what it was originally?

If you see a better way to construct this, please send a PR and corresponding unit test. If something is passed via constructor, need to ensure it doesn't error if nothing is listening to `woocommerce_get_shop_coupon_data`.

**Comment by ragulka** [comment]
@mikejolley I don't see any coupon data being saved to the order? When a virtual coupon is applied and the order is saved, I only see this on the coupon item meta (order_itemmeta):

![screen shot 2018-04-10 at 15 08 52](https://user-images.githubusercontent.com/593267/38556092-1ef381ce-3cd1-11e8-9109-567bc6435cf5.png)

There does not seem to be a trace of anything else on the wp_postmeta or anywhere else.

**Comment by mikejolley** [comment]
coupon_data - in the order meta. Not line item meta.

**Comment by mikejolley** [comment]
@ragulka coupon_data - in the order meta. Not line item meta. It stores all coupon data.

Not sure if thats useful.

Either way, if you want to restructure the constructor thats fine with me.

**Comment by mikejolley** [comment]
> I'm not sure what you mean by "this", but the woocommerce_order_recalculate_coupons_coupon_object filter was introduced in 3.2 and virtual coupon support was introduced in 3.2 as well. 

Maybe I'm mistaken. I think we had some problems with the filter when adding coupon support to admin.

> Anyway, I see it being set now.

Sorry, my bad. Correct it's on the item. That was introduced here https://github.com/woocommerce/woocommerce/commit/487478daa9c90a9517136138be62f0cf13509111

> Regardless, would it not make sense to pass the code to the constructor? I understand the coupon_data meta exists as a fallback in case the coupon is deleted

As long as there is correct handling if the code does not exist/no ID, and no filter. I'm worried it may error instead of using the stored coupon data. But alternatively, why use the filter again if it *does* restore the original coupon_data?

**Comment by bor0** [comment]
I don't think it's really possible to introduce this 1:1 relationship since remainder of coupons are distributed among the products AFAIK, so it wouldn't be a strict 1:1 relationship.

**Comment by mikejolley** [comment]
Right, I don't think so either.

@ragulka Happy to review a PR refactoring those constructors, but linking discounts to line items isn't something we'll be pursuing.

Cheers!
