### ISSUE TITLE
Linebreak in manual order not preserved after 3.3

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#19661]
As discussed [here](https://a8c.slack.com/archives/C0E1AV8T0/p1523310698000330), linebreaks were not preserved after 3.3+ update. Was working in 3.2.

Link to screenshot: http://cld.wthms.co/Tdipp3

What was expected:

In 3.2.6:

![](http://cld.wthms.co/cNWLCe+)
Link to screenshot: http://cld.wthms.co/cNWLCe

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/19671
