### ISSUE TITLE
 /wp-json/wc/v2/products - Parameter Featured issue

### ISSUE THREAD

**Issue by keyinora** [woocommerce/woocommerce#19674]
Resource link : http://woocommerce.github.io/woocommerce-rest-api-docs/?php#list-all-products

Hello,

I have detected a bug with one of your parameters (Featured[boolean]), no matter what state you pass (true or false) it will always return the featured listings. 

Expected behavior would be if you did (for whatever reason) pass featured=false, than you should only retrieve all non-featured listings.

I have only ran this test on PHP, using wordpress.

the following code i used.

$woocommerce->get('products?featured=false');

full code example, is exactly like the documentation (running PHP).

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/19676
