### ISSUE TITLE
Can’t change category image through wp-cli

### ISSUE THREAD

**Issue by apb1963** [woocommerce/woocommerce#19679]
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

    $ wp wc product_cat get 41 --user=1
    +-------------+-----------+
    | Field       | Value     |
    +-------------+-----------+
    | id          | 41        |
    | name        | Book Ends |
    | slug        | book-ends |
    | parent      | 0         |
    | description |           |
    | display     | default   |
    | image       | null      |
    | menu_order  | 0         |
    | count       | 1         |
    +-------------+-----------+

    $ wp wc product list --user=1 --field=id --per_page=1 --category=41
    203

    $ wp post meta get 203 _thumbnail_id
    168

    $ wp post get 168 
    +-----------------------+-------------------------------------------------------------------+
    | Field                 | Value                                                             |
    +-----------------------+-------------------------------------------------------------------+
    | ID                    | 168                                                               |
    | post_author           | 0                                                                 |
    | post_date             | 2018-04-01 22:03:59                                               |
    | post_date_gmt         | 2018-04-02 05:03:59                                               |
    | post_content          |                                                                   |
    | post_title            | 37978                                                             |
    | post_excerpt          |                                                                   |
    | post_status           | inherit                                                           |
    | comment_status        | closed                                                            |
    | ping_status           | closed                                                            |
    | post_password         |                                                                   |
    | post_name             | 37978                                                             |
    | to_ping               |                                                                   |
    | pinged                |                                                                   |
    | post_modified         | 2018-04-01 22:03:59                                               |
    | post_modified_gmt     | 2018-04-02 05:03:59                                               |
    | post_content_filtered |                                                                   |
    | post_parent           | 0                                                                 |
    | guid                  | https://dragon.greetonix.com/wp-content/uploads/2018/04/37978.jpg |
    | menu_order            | 0                                                                 |
    | post_type             | attachment                                                        |
    | post_mime_type        | image/jpeg                                                        |
    | comment_count         | 0                                                                 |
    +-----------------------+-------------------------------------------------------------------+

    $ wp wc product_cat update 41 --image="{id: 168}" --user=1
    Success: Updated product_cat 41.
```

$ wp wc product_cat get 41 --user=1
+-------------+-----------+
| Field       | Value     |
+-------------+-----------+
| id          | 41        |
| name        | Book Ends |
| slug        | book-ends |
| parent      | 0         |
| description |           |
| display     | default   |
| image       | null      |
| menu_order  | 0         |
| count       | 1         |
+-------------+-----------+
```

## Expected/actual behavior

When I follow those steps, I see...
image is null.  The category image also fails to appear on the page.

```
`
```

I was expecting to see...
Something other than null, and a category image on the page.

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://dragon.greetonix.com
Site URL: https://dragon.greetonix.com
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.28-0ubuntu0.16.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ❌ Your server does not have the DOMDocument class enabled - HTML/Multipart emails
and also some extensions
will not work without DOMDocument.

GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 2.21MB
Database Data Size: 1.22MB
Database Index Size: 0.99MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.14MB + Index: 0.02MB
wp_phoen_shipping_table: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 0.48MB + Index: 0.17MB
wp_posts: Data: 0.08MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 167
customize_changeset: 1
page: 6
post: 2
product: 54
revision: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Flexible Shipping: by WP Desk – 2.0.1
Health Check: by The WordPress.org community – 1.0.1
WooCommerce: by Automattic – 3.3.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by kloon** [comment]
The reason it is not updating is because the json is not valid you are using for --image, try the following format instead `--image='{"id": 168}'`

I can confirm I tested the above and it updated the image correctly.
