### ISSUE TITLE
Mobile: Product gallery zoom experience on mobile

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#19688]
Our zoom script doesn't seem to do anything on touch devices, I'm sure it did at some point, perhaps we removed it though. Either way, the consequence of this is that you have to click the magnifying glass icon to view the full images / gallery which is an unnecessarily small target, especially on phones.

On touch devices, assuming zoom is disabled, we should hide the magnification icon and make the thumbnail itself the trigger to open the gallery.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19954
