### ISSUE TITLE
Improving the shipping calculator experience

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#19686]
Using the shipping calculator can be a little confusing because it's not clear which address is being used for the initial calculation. If for example your address has been geolocated and the price doesn't update when you submit your own address that can be puzzling. Similarly, if the store address is being used you might assume the shipping price displayed is correct when it might not be when you input your own address.

I think we can clear up that confusion by making it clear what the shipping prices displayed in the cart are based on. If it's geolocation say prices are estimates. If it's based on the store address declare that and encourage the customer to submit their own address for accurate prices. If it's a returning customer display a shorthand version of their address.

Finally, we can probably hide the shipping calculator for returning, logged in customers since we already have their address.

See p6q8Tx-Ii-p2 for further info.

https://github.com/woocommerce/woocommerce/issues/10672

**Comment by jameskoster** [comment]
No design required.

**Comment by claudiosanches** [comment]
> Finally, we can probably hide the shipping calculator for returning, logged in customers since we already have their address.

Please no, this don't means that the shipping address will be the same for all orders, better fill the fields, but keep the shipping calculator and the fields there.

**Comment by jameskoster** [comment]
Or just display the address as plain text without the fields and include a "Change address" link which reveals the inputs. 

You're right, it's possible they'll be shipping elsewhere, but it's _unlikely_.

**Comment by claudiosanches** [comment]
> but it's unlikely.

Still happens, so we can't block or make hard when this happens.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20345
