### ISSUE TITLE
Jetpack: Hide sharing features on cart / checkout pages

### ISSUE THREAD

**Issue by jameskoster** [woocommerce/woocommerce#19687]
I'm not sure if we should do this in WC, in Jetpack, or even in individual themes, but it would benefit all stores so I'm opening this issue here.

Jetpack adds sharing/like features to posts/pages, these are pretty much useless on the cart / checkout / my account pages. 

<img src="https://cldup.com/XtyiJ13Z3a-3000x3000.png">

I think we should detect if the module is enabled and subsequently disable the feature on the aforementioned pages.

**Comment by mikejolley** [comment]
Gone ahead and submitting a PR here: https://github.com/Automattic/jetpack/pull/9355
