### ISSUE TITLE
Tax calculation is not correct

### ISSUE THREAD

**Issue by ZainSohail** [woocommerce/woocommerce#19680]
I am trying to understand how does woocommerce calculate its taxes when I select that prices are inclusive of taxes. I took over the formula from woocommerce tax information page (https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/) given below is the formula

    tax_amount = price - ( price / ( ( tax_rate_% / 100 ) + 1 ) )

Now when I apply this formula to calculate 1 percent of `1240.00` I get `12.27`, but 1 percent of `1240.00` is `12.40` not `12.27`.

Can someone help me understand where I'm wrong?

Example: http://take.ms/T3TUJ

The weird thing I see is that this is happening when I select that prices are inclusive of tax, but when I select that prices are exclusive of tax I see the correct numbers, which is `12.40`. It should be the same number whether I select inclusive or exclusive, right?

Exclusive of TAX: http://take.ms/tzr4w
Inclusive of TAX: http://take.ms/tPZaf

**Comment by kloon** [comment]
@ZainSohail The reason you get a different value when you have your prices set to inclusive of taxes is that the price already includes tax, so you cannot just simply take 1% off the total price to give you the tax amount.

So yes, 1% of 1240 is 12.4, but only if the price is defined excluding tax, if you define the price including tax then the pre-tax price will be lower and thus the tax amount differs.

Hope that makes sense.
