### ISSUE TITLE
 Class 'WC_Product'

### ISSUE THREAD

**Issue by Tekrajs** [woocommerce/woocommerce#19689]
I am trying to access woo-commerce class in custom plugin. But it is not being access with cron. Here is what I have done : 

        <?php

          if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

          function amwscp_order_interval() {
              $current_delay = 15*60;
              return array(
                  'order_interval' => array('interval' => $current_delay, 'display' => 'Order refresh interval'),
              );
          }

          class AMWSCPF_Order_Cron {

              public static function doSetup() {
                  add_filter('cron_schedules', 'amwscp_order_interval');
                  //Delete old (faulty) scheduled cron job from prior versions
                  $next_refresh = wp_next_scheduled('order_interval');
                  if ($next_refresh)
                      wp_unschedule_event($next_refresh, 'order_interval');
              }

              public static function scheduleUpdate () {
                  //Set the Cron job here. Params are (when, display, hook)
                  $next_refresh = wp_next_scheduled('amwscpf_order_import_hook');
                  if (!$next_refresh )
                      wp_schedule_event(time(), 'order_interval', 'amwscpf_order_import_hook');
              }

          }
          AMWSCPF_Order_Cron::doSetup();
          AMWSCPF_Order_Cron::scheduleUpdate();

          add_action('amwscpf_order_import_hook','amwscpf_import_all_order');
          do_action('amwscpf_order_import_hook');

          function amwscpf_import_all_order(){
            // use wc_get_product() on WC 2.1+
            if ( function_exists('wc_get_product') ) {
              print_r(wc_get_product( 52 ));
            // use get_product() on WC 2.0+
            } else ( function_exists('get_product') ) {
              print_r(get_product( 52 ));exit;
            } 
          }
         
 
this says : Fatal error: Class 'WC_Product' not found . How can I solve this ?

**Comment by mikejolley** [comment]
We don't provide custom coding support here. Please use the forums.
