### ISSUE TITLE
Send link to unfulfilled order?

### ISSUE THREAD

**Issue by James1S10** [woocommerce/woocommerce#19684]
Sometimes guest customers add items to cart, add their items to cart and their personal information - The order then written as `pending `and when customer failed to pay the order status changes to `cancelled`.

My question is - Is it possible to mark this order and send it to the customer as email with something like "You can still complete your order" and when he presses the link his saved cart will be shown with his personal information and all he needs is just to complete the payment?

The way I see it... all information regarding the order is already stored so what the harm by trying to put it to good use and help this order to actually be paid rather than be saved as canceled

**Comment by mikejolley** [comment]
It could be possible - check out some of the cart abandonment solutions/plugins for WooCommerce out there. This feature is not part of core.

**Comment by James1S10** [comment]
@mikejolley Hi Mike,
I'll be more specific...
When the order is pending there is a way in the core to get to continue the payment from where the customer left:
![778](https://user-images.githubusercontent.com/38276915/38616996-7f152620-3d9e-11e8-8efe-ea6e0ecd2e3d.png)

By clicking this link I can get to the unpaid order and if I simply send it to the customer he can continue from where he left... However when the order is changed to canceled this link is gone. Why?

**Comment by mikejolley** [comment]
Because it's no longer valid when it's cancelled. You can control the timeout between pending -> cancelled in the settings.
