### ISSUE TITLE
Login form messages - control them through filters

### ISSUE THREAD

**Issue by AndreiIgna** [woocommerce/woocommerce#19694]
The login form is used in a few parts in WooCommerce and this message placement can create problems sometimes
https://github.com/woocommerce/woocommerce/blob/49e93bc7554f2f61ee7a0bbfa12edeb114cee417/templates/global/form-login.php#L32

A suggestion is it should be added through `woocommerce_login_form_start`, not directly in themplate

**Comment by claudiulodro** [comment]
This is definitely an improved way of doing it. My main concern is themes that have overriden this template will have double messages after this change (one from the old echo method and one from the new one hooked into `woocommerce_login_form_start`). The backwards-compatibility on it is tricky.

**Comment by AndreiIgna** [comment]
Yes, tricky one.

It seems that `$message` is defined in another part, maybe it can be added to hook and leave `$message` empty. This was it's displayed in action and templates already checks for non-empty value.

Because of these things I wanted to start a discussion first, before creating a PR

**Comment by mikejolley** [comment]
For this to be added via a hook, `$message` would need to be passed around via said hook. This only has one usage right now; during checkout. 

I'd prefer to make changes to this when we tackle https://github.com/woocommerce/woocommerce/issues/10672 than update the templates twice and potentially cause a theme conflict issue.

Why is it problematic? Can you live with template override for now (if needed)?

**Comment by AndreiIgna** [comment]
👍 @mikejolley that looks good, exactly what we're after. 

The message content can't be changed and the biggest problem, the placement can't be modified. Message is always displayed between `woocommerce_login_form_start` and user field

**Comment by mikejolley** [comment]
Made a note in the checkout issue.

For now override the template, or translate the text using `gettext` filters, or a localisation :)

Thanks
