### ISSUE TITLE
Filtering products by out of stock status does not show the variable product variations that are out.

### ISSUE THREAD

**Issue by pospoppgh** [woocommerce/woocommerce#19693]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Mark stuff out of stock, simple products as well as variable products
2. Filter products by out of stock status
3. All simple products will come up, but no variables will

## Expected/actual behavior

When I follow those steps, I see...
All the simple products that are out of stock come up. None of the variable products with variations that are out are listed.

I was expecting to see...
Any product that's got an out status listed, including variations.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
`
### WordPress Environment ###

Home URL: https://positivelypittsburgh.com
Site URL: https://positivelypittsburgh.com
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Flywheel/4.1.0
PHP Version: 5.6.34-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 300 MB
PHP Time Limit: 60s
PHP Max Input Vars: 4000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.6.32
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_f2l76ldl7m_
MaxMind GeoIP Database: ✔
Total Database Size: 31.28MB
Database Data Size: 25.04MB
Database Index Size: 6.24MB
wp_f2l76ldl7m_woocommerce_sessions: Data: 5.02MB + Index: 0.06MB
wp_f2l76ldl7m_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_f2l76ldl7m_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_f2l76ldl7m_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_f2l76ldl7m_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB
wp_f2l76ldl7m_woocommerce_order_itemmeta: Data: 0.44MB + Index: 0.38MB
wp_f2l76ldl7m_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_f2l76ldl7m_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_f2l76ldl7m_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_f2l76ldl7m_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_f2l76ldl7m_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_f2l76ldl7m_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_f2l76ldl7m_aps_social_icons: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_f2l76ldl7m_comments: Data: 0.11MB + Index: 0.09MB
wp_f2l76ldl7m_defender_lockout: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_defender_lockout_log: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_eg_grids: Data: 0.08MB + Index: 0.02MB
wp_f2l76ldl7m_eg_item_elements: Data: 0.02MB + Index: 0.02MB
wp_f2l76ldl7m_eg_item_skins: Data: 1.52MB + Index: 0.03MB
wp_f2l76ldl7m_eg_navigation_skins: Data: 0.06MB + Index: 0.02MB
wp_f2l76ldl7m_links: Data: 0.02MB + Index: 0.02MB
wp_f2l76ldl7m_options: Data: 4.14MB + Index: 0.08MB
wp_f2l76ldl7m_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_pmxi_imports: Data: 0.13MB + Index: 0.00MB
wp_f2l76ldl7m_pmxi_posts: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_pmxi_templates: Data: 0.06MB + Index: 0.00MB
wp_f2l76ldl7m_postmeta: Data: 2.52MB + Index: 2.98MB
wp_f2l76ldl7m_posts: Data: 1.47MB + Index: 0.23MB
wp_f2l76ldl7m_redirects: Data: 0.06MB + Index: 0.00MB
wp_f2l76ldl7m_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_f2l76ldl7m_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_revslider_sliders: Data: 0.11MB + Index: 0.00MB
wp_f2l76ldl7m_revslider_slides: Data: 0.47MB + Index: 0.00MB
wp_f2l76ldl7m_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_rg_form: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_rg_form_meta: Data: 6.09MB + Index: 0.00MB
wp_f2l76ldl7m_rg_form_view: Data: 0.05MB + Index: 0.03MB
wp_f2l76ldl7m_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_f2l76ldl7m_rg_lead: Data: 0.05MB + Index: 0.03MB
wp_f2l76ldl7m_rg_lead_detail: Data: 1.52MB + Index: 1.39MB
wp_f2l76ldl7m_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_f2l76ldl7m_rg_lead_meta: Data: 0.06MB + Index: 0.05MB
wp_f2l76ldl7m_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_f2l76ldl7m_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_f2l76ldl7m_termmeta: Data: 0.02MB + Index: 0.03MB
wp_f2l76ldl7m_terms: Data: 0.02MB + Index: 0.03MB
wp_f2l76ldl7m_term_relationships: Data: 0.06MB + Index: 0.05MB
wp_f2l76ldl7m_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_f2l76ldl7m_usermeta: Data: 0.13MB + Index: 0.11MB
wp_f2l76ldl7m_users: Data: 0.02MB + Index: 0.05MB
wp_f2l76ldl7m_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_f2l76ldl7m_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 344
custom_css: 1
nav_menu_item: 8
page: 16
post: 5
product: 207
product_variation: 45
revision: 150
shop_coupon: 2
shop_order: 250
wdf_scan: 1
wdf_scan_item: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (29) ###

Gravity Forms: by rocketgenius – 2.2.6
AccessPress Social Icons: by AccessPress Themes – 1.6.9
Admin Custom Login: by Weblizar – 2.5.9
Better Search Replace: by Delicious Brains – 1.3.2
Bulk Actions Pro for Gravity Forms: by JetSloth – 1.2.11
Easy WP SMTP: by wpecommerce – 1.3.5
Eggplant 301 Redirects: by Shawn Wernig http://www.eggplantstudios.ca – 2.3.0
Essential Grid: by ThemePunch – 2.1.6.1
flickrRSS: by Dave Kellam – 5.3.1
Get The Image: by Justin Tadlock – 1.1.0
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Slider Revolution: by ThemePunch – 5.4.6.2
Search Exclude: by Roman Pronskiy – 1.2.2
ShiftNav - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.6.2

U-Design WooCommerce Integration: by Andon – 2.2.3
U-Design Shortcodes Button: by AndonDesign – 2.0.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.14.5.24

WooCommerce Customer/Order/Coupon CSV Import Suite: by WooThemes / SkyVerge – 3.0.3 – 3.5.1 is available – Not tested with the active version of WooCommerce
WooCommerce Product Archive Customiser: by jameskoster – 1.0.5 – Not tested with the active version of WooCommerce
WP All Import - WooCommerce Add-On: by Soflyy – 1.3.7 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.5
WP All Import: by Soflyy – 3.4.7
Defender Pro: by WPMU DEV – 1.8
Hummingbird Pro: by WPMU DEV – 1.8.0.4
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.92
WP Smush Pro: by WPMU DEV – 2.7.8
SmartCrawl: by WPMU DEV – 2.2.1
WPMU DEV Dashboard: by WPMU DEV – 4.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #19 - /shop/
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My account: #22 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: U-Design Child Theme
Version: 1.0.0
Author URL: http://www.cmewebsites.com
Child Theme: ✔
Parent Theme Name: U-Design
Parent Theme Version: 2.13.13
Parent Theme Author URL: https://themeforest.net/user/andondesign/portfolio?ref=AndonDesign
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
> Filtering products by out of stock status does not show the variable product variations that are out.

When you're filtering products you're filtering the parent products, not the individual variations.

> I was expecting to see...Any product that's got an out status listed, including variations.

Again variations are not listed in the admin views. They are within variable products.

Only variable products with out of stock status will be listed whilst doing this filter. This includes only:

- Variable products which manage stock at product level and are out of stock
- Variable products with variations managing stock where all variations are out of stock

At any other time, the variable will not have out of stock status as it's inherited from child. 

There are extensions/other reports (reports section) which can list variations that are out of stock.

cc @peterfabian

**Comment by Archvist** [comment]
I cannot believe this is still not part of the core functionality.

WooCommerce has always had consistency issues on what they deem a variable product to include. Their own documentation lists an example variation product as a "blue t-shirt". But the system doesn't see your variations of t-shirts as products and such are not treated as products.

**Comment by melindahelt** [comment]
zd-4053614

Still seeing this issue. Is this expected?

When a simple product is out of stock, it can be filtered in wp-admin and displayed as out of stock.
<img width="1228" alt="Screen Shot 2021-06-08 at 16 26 19" src="https://user-images.githubusercontent.com/8306136/121252854-80f26f00-c876-11eb-80bc-d5f1a55f5881.png">

Same site with a  variable product is not displayed:

![simple-product-out-of-stock](https://user-images.githubusercontent.com/8306136/121252814-72a45300-c876-11eb-8ee9-ac8ef6a60963.png)


One variable at 0 stock, other two have stock

<img width="697" alt="Screen Shot 2021-06-08 at 16 29 33" src="https://user-images.githubusercontent.com/8306136/121253121-bd25cf80-c876-11eb-9d84-31515cb2a4e6.png">

Tested on WooCommerce 5.4. Is this expected?

**Comment by jonathansadowski** [comment]
Thanks for all the reports here. We're tracking reimplementation of a fix for this in https://github.com/woocommerce/woocommerce/issues/29611, and I just wanted to drop a note here so the connection between the two doesn't get lost. I'm going to leave this issue closed, as we're tracking things there.
