### ISSUE TITLE
calculate shipping not working at cart/checkout

### ISSUE THREAD

**Issue by eve1234** [woocommerce/woocommerce#19698]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
I am experiencing this issue with store front. I also switched to default themes like Twenty Thirteen and all those but problem persists. It should either calculate shipping accordingly when user selects any shipping method or calculate it when user clicks on 'calculate shipping'. But instead returns -

https://www.domain.com/basket/#

Please, help.

Thank you

1. Add products / items to cart. Make sure there are different shipping methods
Free Shipping
UK shipping - Flexible rate
European shipping class
US shipping class
2. Now login as customer
3. In the cart try and select any choice of method. Click on 'Calculate Shipping'. 

## Expected/actual behavior
It should calculate the selected shipping accordingly.
When I follow those steps, I see...
I am experiencing this issue with store front. I also switched to default themes like Twenty Thirteen and all those but problem persists. It should either calculate shipping accordingly when user selects any shipping method or calculate it when user clicks on 'calculate shipping'. 

I was expecting to see...

But instead returns -
https://www.domain.com/basket/#

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

WC version: |   | 3.3.5
-- | -- | --

WP version: |   | 4.9.5
-- | -- | --

```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```

WordPress Backup & Security Plugin - BlogVault |   | by Backup by BlogVault – 1.61
-- | -- | --
Custom css-js-php |   | by flippercode – 2.0.4
Email Subscribers & Newsletters |   | by Icegram – 3.4.11
Embed QuickTime |   | by Andreas Haugstrup Pedersen – 1.1
Flexible Shipping |   | by WP Desk – 2.0.1 – Not tested with the active version of WooCommerce
Footer Putter |   | by Russell Jamieson – 1.14.1
Giftable for WooCommerce |   | by Decom – 1.0.1 – Not tested with the active version of WooCommerce
Icegram - Popups, Optins, CTAs & lot more... |   | by icegram – 1.10.18
Insert Headers and Footers |   | by WPBeginner – 1.4.2
Instagram Feed |   | by Smash Balloon – 1.8.1
Kirki Toolkit |   | by Aristeides Stathopoulos – 3.0.25
Login No Captcha reCAPTCHA |   | by Robert Peake – 1.2.2
My Custom Functions |   | by Arthur Gareginyan – 4.13
oik Weight/Country Shipping |   | by bobbingwide – 1.3.4 – Not tested with the active version of WooCommerce
Popup by Supsystic |   | by supsystic.com – 1.9.25
Popup Maker |   | by WP Popup Maker – 1.7.14
Postmen Woocommerce Shipping |   | by Postmen – 1.1.9 – Not tested with the active version of WooCommerce
Product Enquiry for WooCommerce |   | by WisdmLabs – 2.4 – Not tested with the active version of WooCommerce
SG Optimiser |   | by SiteGround – 4.0.4
Fast Secure Contact Form |   | by fastsecure – 4.0.56
Sucuri Security - Auditing, Malware Scanner and Hardening |   | by Sucuri Inc. – 1.8.14
snapCX WooCommerce Order Tracking |   | by WooCommerce – 2.0.4 – Not tested with the active version of WooCommerce
VaultPress |   | by Automattic – 1.9.5
Product Customer List for WooCommerce |   | by Kokomo – 2.6.5 – Not tested with the active version of WooCommerce
Twist - Woocommerce Product Gallery Slider Free |   | by Niloy Sarker – 1.1.8.2 – Not tested with the active version of WooCommerce
WooCommerce Product Slider |   | by ShapedPlugin – 2.1.2 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking Basic |   | by XAdapter – 1.0.7 – Not tested with the active version of WooCommerce
WC - APG SMS Notifications |   | by Art Project Group – 2.14.0.4 – Not tested with the active version of WooCommerce
WC - APG Weight Shipping |   | by Art Project Group – 2.2.3.1 – Not tested with the active version of WooCommerce
WooCommerce Extended Coupon Features |   | by Soft79 – 2.6.2 – Not tested with the active version of WooCommerce
WooCommerce Cart Tab |   | by jameskoster – 1.1.1 – Not tested with the active version of WooCommerce
WooCommerce Customizer |   | by SkyVerge – 2.5.0 – Not tested with the active version of WooCommerce
WooCommerce PayPal Powered by Braintree Gateway |   | by WooCommerce – 2.1.1 – Not tested with the active version of WooCommerce
Booster for WooCommerce |   | by Algoritmika Ltd – 3.5.2 – Not tested with the active version of WooCommerce
WooCommerce My Account Widget |   | by Bart Pluijms – 0.6.3 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices |   | by Bas Elbers – 2.9.12 – Not tested with the active version of WooCommerce
WooCommerce Price Based on Country (Basic) |   | by Oscar Gare – 1.7.1 – Not tested with the active version of WooCommerce
WooCommerce Product Stock Alert |   | by WC Marketplace, The Grey Parrots – 1.4.8 – Not tested with the active version of WooCommerce
WooCommerce Show Attributes |   | by Isabel Castillo – 1.6.4 – Not tested with the active version of WooCommerce
WooCommerce Stock Manager |   | by Vladislav Musílek – 1.2.4 – Not tested with the active version of WooCommerce
WooCommerce |   | by Automattic – 3.3.5
WP Admin Protection (by SiteGuarding.com) |   | by SiteGuarding.com (SafetyBis Ltd.) – 2.3.1
WP E-Commerce UK Royal Mail Shipping Module |   | by DesignNG – 2.0
YITH WooCommerce Dynamic Pricing and Discounts |   | by YITHEMES – 1.2.2 – Not tested with the active version of WooCommerce

Thank you
</details>

**Comment by eve1234** [comment]
I am experiencing this issue with store front. I also switched to default themes like Twenty Thirteen and all those but problem persists. It should either calculate shipping accordingly when user selects any shipping method or calculate it when user clicks on 'calculate shipping'.

**Comment by claudiulodro** [comment]
The problem is most likely caused by one of the many, many plugins you have active conflicting with WooCommerce. That's the first place I would check.

I was not able to reproduce this issue using WooCommerce and no other plugins active. If you can post a link to the site you're having issues on, I can get more information about the issue by reproducing it on there.

**Comment by eve1234** [comment]
Hi,
Thank you for your reply. Site is -

Www.evevoni.com

**Comment by eve1234** [comment]
Thank you

**Comment by mikejolley** [comment]
This is due to javascript errors on the page not from WooCommerce:

![slack - a8c 2018-04-13 10-40-11](https://user-images.githubusercontent.com/90977/38728195-16b613e0-3f07-11e8-906d-0c5334ebfcd9.png)

Looks like a video embed is breaking it.

**Comment by Bossquiat** [comment]
hi am i having this same issue i have tried to deactivate plugins but the problem hasnt stopped. does anyone have any suggestions. the site im using is geneticbullz.com
