### ISSUE TITLE
Recent Product Reviews output template

### ISSUE THREAD

**Issue by wayheming** [woocommerce/woocommerce#19691]
Hello, I care about the question why widget "Recent Product Reviews" does not use the template "content-widget-product.php" like other widgets with output products. For example widgets Recent Viewed Products, Products, Products by Rating. I ask, because the templates are very similar, and it would be very cool if you in the next update of your plugin added the output of the widget's products through the general template.

http://prntscr.com/j3u50h
http://prntscr.com/j3u555

Thankyou

**Comment by claudiulodro** [comment]
Happy to review and merge a pull request if you want to give it a shot.

**Comment by mikejolley** [comment]
Reviews widget shows different content to regular widgets @claudiulodro They include the star rating most importantly. It wouldn't make sense to share the same template as they show different data :)

**Comment by wayheming** [comment]
@mikejolley but I see that in the file `content-widget-product.php` already has a condition for the output of the star rating

`	<?php if ( ! empty( $show_rating ) ) : ?>
		<?php echo wc_get_rating_html( $product->get_average_rating() ); ?>
	<?php endif; ?>`

**Comment by wayheming** [comment]
@mikejolley Well, then how do I change this widget in my theme? Perhaps need to add some hook?

**Comment by mikejolley** [comment]
You could introduce a new content template file for reviews widgets (PR?) or replace the widget with one in your theme. 

As I said, they are very different. This widget links to a review, shows a rating, and shows information about the reviewer.

**Comment by wayheming** [comment]
@mikejolley Will you kindly take a look at the PR?
