### ISSUE TITLE
Feature Request: Filter Products by sale status in product list

### ISSUE THREAD

**Issue by Grauen** [woocommerce/woocommerce#19708]
When viewing the current products (wp-admin/edit.php?post_type=product) , it would be very nice if you could filter products by current sale status.

We have about 2000 products and we would like to view only the producs which are currently on sale.

**Comment by mikejolley** [comment]
Hi,

Interesting suggestion. I cannot find any other requests for this here or on the ideas board so please log this on http://ideas.woocommerce.com/forums/133476-woocommerce for voting. We won't prioritize this over other things unless we're sure it will benefit a lot of store owners.

For now implementing this would require custom code from a developer.

Thanks!
