### ISSUE TITLE
Admin coupon page load object id leads to unneccesery search

### ISSUE THREAD

**Issue by alexrowesoap** [woocommerce/woocommerce#19704]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Ensure at least one coupon exists, where the title is different to the id
2. Load the coupon in the admin
3. Add an xdebug breakpoint on line 82 of includes\class-wc-coupon.php

## Expected/actual behavior

Expected: The call loads the coupon by id
Actual: The coupon is loaded by the wc_get_coupon_id_by_code function instead

## Isolating the problem

So the crux of this issue is in includes\admin\meta-boxes\class-wc-meta-box-coupon-data.php runs:
`$coupon = new WC_Coupon( $post->ID );` near the top on line 30. The thing to note here is that at runtime ID is a int stored as a string.
This ID ends up as the $data variable in the coupon constructor in includes\class-wc-coupon.php. In an ideal world, the check on line 89 (`elseif ( is_int( $data ) && 'shop_coupon' === get_post_type( $data ) )`) should return true, but because the ID is an int stored as a string rather than an int proper, is_int returns false. This means that the constructor falls back to the `wc_get_coupon_id_by_code` a couple of lines down.
This results in function get_ids_by_code in includes\data-stores\class-wc-coupon-data-store-cpt.php running a query searching by post title, which is much slower. What's worse is that if the post name is different to the coupon id, it never gets cached either.

is_numeric to replace the is_int is too leinient, so we either need to find out why the ID is a string, or alter the is_int to something more forgiving.

- [X] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://www.REDACTED
Site URL: https://www.REDACTED/wp
WC Version: 3.3.4
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Win32) OpenSSL/1.0.2f PHP/7.2.2
PHP Version: 7.2.2
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.57.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.7.11
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.4
WC Database Prefix: wp_
Total Database Size: 8349.72MB
Database Data Size: 5196.90MB
Database Index Size: 3152.82MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 11.52MB + Index: 24.67MB
wp_woocommerce_order_items: Data: 27.56MB + Index: 17.58MB
wp_woocommerce_order_itemmeta: Data: 192.75MB + Index: 195.56MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
products_map: Data: 0.02MB + Index: 0.00MB
training-voucher: Data: 0.02MB + Index: 0.00MB
training-voucher_pre-2016-11-22: Data: 21.55MB + Index: 0.00MB
training-voucher_products_map: Data: 0.05MB + Index: 0.00MB
visualsoft: Data: 0.11MB + Index: 0.00MB
visualsoft_pre-2016-12: Data: 10.52MB + Index: 0.00MB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB
wp_affiliate_wp_affiliates: Data: 0.06MB + Index: 0.02MB
wp_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_creatives: Data: 0.06MB + Index: 0.02MB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_referrals: Data: 0.08MB + Index: 0.02MB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_visits: Data: 1.52MB + Index: 0.23MB
wp_better_user_search_meta_keys: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 1217.00MB + Index: 155.30MB
wp_comments: Data: 193.69MB + Index: 233.53MB
wp_couponmeta: Data: 0.02MB + Index: 0.03MB
wp_ewwwio_images: Data: 27.55MB + Index: 29.77MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
wp_followup_customers: Data: 1.52MB + Index: 1.31MB
wp_followup_customer_carts: Data: 64.52MB + Index: 1.78MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.52MB + Index: 0.36MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.39MB + Index: 0.13MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB
wp_followup_order_categories: Data: 1.52MB + Index: 0.69MB
wp_followup_order_items: Data: 1.52MB + Index: 1.02MB
wp_followup_subscribers: Data: 0.16MB + Index: 0.20MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_gglcptch_whitelist: Data: 0.02MB + Index: 0.02MB
wp_itsec_lockouts: Data: 0.00MB + Index: 0.01MB
wp_itsec_log: Data: 2.88MB + Index: 0.47MB
wp_itsec_logs: Data: 4.52MB + Index: 0.09MB
wp_itsec_temp: Data: 0.19MB + Index: 0.18MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 10.42MB + Index: 2.52MB
wp_pmxe_exports: Data: 23.52MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 21.55MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.41MB + Index: 0.00MB
wp_pmxi_files: Data: 0.28MB + Index: 0.00MB
wp_pmxi_history: Data: 0.19MB + Index: 0.00MB
wp_pmxi_imports: Data: 59.52MB + Index: 0.00MB
wp_pmxi_posts: Data: 84.63MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.23MB + Index: 0.00MB
wp_postmeta: Data: 1441.00MB + Index: 1412.00MB
wp_posts: Data: 614.94MB + Index: 189.69MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 1.52MB + Index: 3.03MB
wp_term_relationships: Data: 3.52MB + Index: 3.52MB
wp_term_taxonomy: Data: 1.52MB + Index: 0.50MB
wp_usermeta: Data: 250.75MB + Index: 205.53MB
wp_users: Data: 35.56MB + Index: 41.67MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_couponmeta: Data: 835.98MB + Index: 627.77MB
wp_woocommerce_worldpaycw_customer_contexts: Data: 1.52MB + Index: 1.52MB
wp_woocommerce_worldpaycw_documents: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_worldpaycw_ecc: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_worldpaycw_schema_version: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_worldpaycw_storage: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_worldpaycw_transactions: Data: 22.56MB + Index: 0.00MB
wp_wsal_metadata: Data: 1.66MB + Index: 0.75MB
wp_wsal_occurrences: Data: 0.09MB + Index: 0.09MB
wp_wsal_options: Data: 0.00MB + Index: 0.00MB
wp_wsluserscontacts: Data: 0.02MB + Index: 0.02MB
wp_wslusersprofiles: Data: 2.52MB + Index: 0.23MB

### Post Type Counts ###

attachment: 33972
certificate: 43986
certificate_template: 1
course: 298
enquiry: 24723
follow_up_email: 2
lesson: 13257
nav_menu_item: 34
page: 45
post: 134
product: 405
product_variation: 1031
question: 37852
quiz: 13221
revision: 2
scheduled-action: 28991
sensei_message: 250988
shop_coupon: 840408
shop_order: 83795
shop_order_refund: 276
shop_subscription: 74094
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Query Monitor: by John Blackbourn & contributors – 3.0.0
Advanced Custom Fields PRO: by Elliot Condon – 5.6.10
AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.1.11
AffiliateWP - Recurring Referrals: by Pippin Williamson and Andrew Munro – 1.6.4
AffiliateWP: by AffiliateWP
LLC – 2.1.17

AffiliateWP - Store Credit: by AffiliateWP
LLC – 2.2.2

Better User Search: by Dale Higgs – 1.1.1
iThemes Security: by iThemes – 6.9.2
General Enquiries: by Simon Zurek – 1.0.0
Contact Form 7: by Takayuki Miyoshi – 5.0.1
Disable Emails: by WebAware – 1.3.0
ElasticPress: by Taylor Lovett
Matt Gross
Aaron Holbrook
10up – 2.4.2

Google Captcha (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.36
Sensei Certificates: by WooThemes – 1.0.13 – 1.0.17 is available
Sensei: by WooThemes – 1.9.11
User Role Editor: by Vladimir Garagulya – 4.40.3
User Switching: by John Blackbourn – 1.3.0
W3 Total Cache: by Frederick Townes – 0.9.6
WooCommerce Subscriptions Remove Deprecation Handlers: by Prospress Inc. – 1.0 – Not tested with the active version of WooCommerce
Woo Sensei Shortcodes: by wpexperts.io – 1.3.0
Woocommerce Bulk Attribute Manager: by Varun Sridharan – 2.2.1 – Not tested with the active version of WooCommerce
WooCommerce Currency Switcher: by realmag777 – 2.1.6 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.5.0
WooCommerce Kissmetrics: by WooThemes / SkyVerge – 1.8.0 – 1.11.1 is available – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by WooThemes – 5.0.2 – 5.7.7 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.4 – 3.3.5 is available
Yoast SEO Premium: by Team Yoast – 3.9
WordPress Social Login: by Miled – 2.3.3
WP All Export Pro: by Soflyy – 1.5.2
WP All Import Pro: by Soflyy – 4.5.1
WP Content Copy Protection Premium (YOOPlugins): by Rynaldo Stoltz – 1.8.32
WP Crontrol: by John Blackbourn & contributors – 1.6.2
WP Security Audit Log: by WP White Security – 3.1.5
WP All Import - ACF Add-On: by Soflyy – 3.1.5
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.3.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /shop/basket/
Checkout: #6 - /shop/checkout/
My account: #71 - /my-account/
Terms and conditions: #20719 - /terms-conditions/

### Theme ###

Name: REDACTED
Version: 1.0.5
Author URL: REDACTED
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: REDACTED/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/cart\cart-empty.php version - is out of date. The core version is 3.1.0
REDACTED/woocommerce/cart\cart-item-data.php
REDACTED/woocommerce/cart\cart-shipping.php version 2.5.0 is out of date. The core version is 3.2.0
REDACTED/woocommerce/cart\cart-totals.php
REDACTED/woocommerce/cart\cart.php version 2.3.8 is out of date. The core version is 3.3.0
REDACTED/woocommerce/cart\cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
REDACTED/woocommerce/cart\mini-cart.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/cart\proceed-to-checkout-button.php
REDACTED/woocommerce/cart\shipping-calculator.php version 2.0.8 is out of date. The core version is 3.2.0
REDACTED/woocommerce/checkout\cart-errors.php
REDACTED/woocommerce/checkout\form-billing.php version 2.1.2 is out of date. The core version is 3.0.9
REDACTED/woocommerce/checkout\form-checkout.php version - is out of date. The core version is 2.3.0
REDACTED/woocommerce/checkout\form-coupon.php version 2.2 is out of date. The core version is 3.3.0
REDACTED/woocommerce/checkout\form-pay.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/checkout\form-shipping.php version 2.2.0 is out of date. The core version is 3.0.9
REDACTED/woocommerce/checkout\payment-method.php
REDACTED/woocommerce/checkout\payment.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/checkout\review-order.php version 2.3.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/checkout\terms.php version 2.5.0 is out of date. The core version is 3.1.1
REDACTED/woocommerce/checkout\thankyou.php version 2.2.0 is out of date. The core version is 3.2.0
REDACTED/woocommerce/content-product.php version 2.5.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/content-product_cat.php version 2.5.2 is out of date. The core version is 2.6.1
REDACTED/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.0.0
REDACTED/woocommerce/emails\admin-cancelled-order.php
REDACTED/woocommerce/emails\admin-failed-order.php
REDACTED/woocommerce/emails\admin-new-order.php
REDACTED/woocommerce/emails\customer-completed-order.php
REDACTED/woocommerce/emails\customer-invoice.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/emails\customer-new-account.php
REDACTED/woocommerce/emails\customer-note.php
REDACTED/woocommerce/emails\customer-on-hold-order.php
REDACTED/woocommerce/emails\customer-processing-order.php
REDACTED/woocommerce/emails\customer-refunded-order.php
REDACTED/woocommerce/emails\customer-reset-password.php
REDACTED/woocommerce/emails\email-addresses.php version 2.4.0 is out of date. The core version is 3.2.1
REDACTED/woocommerce/emails\email-customer-details.php
REDACTED/woocommerce/emails\email-footer.php
REDACTED/woocommerce/emails\email-header.php
REDACTED/woocommerce/emails\email-order-details.php version 2.5.0 is out of date. The core version is 3.3.1
REDACTED/woocommerce/emails\email-order-items.php version 2.1.2 is out of date. The core version is 3.2.0
REDACTED/woocommerce/emails\email-styles.php version 2.3.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/emails\plain\admin-cancelled-order.php
REDACTED/woocommerce/emails\plain\admin-failed-order.php
REDACTED/woocommerce/emails\plain\admin-new-order.php
REDACTED/woocommerce/emails\plain\customer-completed-order.php
REDACTED/woocommerce/emails\plain\customer-invoice.php
REDACTED/woocommerce/emails\plain\customer-new-account.php
REDACTED/woocommerce/emails\plain\customer-note.php
REDACTED/woocommerce/emails\plain\customer-on-hold-order.php
REDACTED/woocommerce/emails\plain\customer-processing-order.php
REDACTED/woocommerce/emails\plain\customer-refunded-order.php
REDACTED/woocommerce/emails\plain\customer-reset-password.php
REDACTED/woocommerce/emails\plain\email-addresses.php version 2.2.0 is out of date. The core version is 3.2.1
REDACTED/woocommerce/emails\plain\email-customer-details.php
REDACTED/woocommerce/emails\plain\email-order-details.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/emails\plain\email-order-items.php version 2.1.2 is out of date. The core version is 3.2.0
REDACTED/woocommerce/loop\add-to-cart.php version 2.5.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/loop\loop-end.php
REDACTED/woocommerce/loop\loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/loop\no-products-found.php
REDACTED/woocommerce/loop\orderby.php version 2.2.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/loop\rating.php version 2.0.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/loop\sale-flash.php
REDACTED/woocommerce/myaccount\dashboard.php
REDACTED/woocommerce/myaccount\downloads.php version 2.6.0 is out of date. The core version is 3.2.0
REDACTED/woocommerce/myaccount\form-edit-account.php version 2.6.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/myaccount\form-edit-address.php version 2.6.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/myaccount\form-login.php version 2.2.6 is out of date. The core version is 3.3.0
REDACTED/woocommerce/myaccount\form-lost-password.php version 2.3.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/myaccount\form-reset-password.php version 2.6.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/myaccount\lost-password-confirmation.php
REDACTED/woocommerce/myaccount\my-account.php
REDACTED/woocommerce/myaccount\my-address.php
REDACTED/woocommerce/myaccount\my-orders.php
REDACTED/woocommerce/myaccount\navigation.php
REDACTED/woocommerce/myaccount\orders.php version 2.6.0 is out of date. The core version is 3.2.0
REDACTED/woocommerce/myaccount\view-order.php version 2.6.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/notices\error.php version 1.6.4 is out of date. The core version is 3.3.0
REDACTED/woocommerce/notices\notice.php
REDACTED/woocommerce/notices\success.php version 1.6.4 is out of date. The core version is 3.3.0
REDACTED/woocommerce/order\order-again.php
REDACTED/woocommerce/order\order-details-customer.php version 2.4.0 is out of date. The core version is 3.3.0
REDACTED/woocommerce/order\order-details-item.php version 2.5.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/order\order-details.php version 2.5.3 is out of date. The core version is 3.3.0
REDACTED/woocommerce/product-searchform.php version - is out of date. The core version is 3.3.0
REDACTED/woocommerce/single-product\add-to-cart\simple.php version - is out of date. The core version is 3.0.0
REDACTED/woocommerce/single-product\add-to-cart\variable.php version 2.5.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/single-product\add-to-cart\variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
REDACTED/woocommerce/single-product\add-to-cart\variation.php
REDACTED/woocommerce/single-product\product-image.php version 2.0.14 is out of date. The core version is 3.3.2
REDACTED/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
</details>

**Comment by javorszky** [comment]
Confirmed the `$post->ID` comes back as a string.

As a side note the `$post->ID` also comes back as a string on the product edit pages. I assume orders aren't free from this happening either. Did not check whether that causes performance issues on those circumstances, but it might be best to tackle the root cause rather than casting the ID to an `int` for the coupons.

**Comment by claudiulodro** [comment]
Interesting. [That method is literally hooked straight to WP](https://github.com/woocommerce/woocommerce/blob/f40480a3e49f70705448b17a6b7fc16b56909b34/includes/admin/class-wc-admin-meta-boxes.php#L135), and I get a string type for `$post->ID` on post pages also. Fixing the underlying problem (possible a WP core problem) is the **best** solution, but casting it to an int when instantiating the `WC_Coupon` will also work.

We can't really make the checking any looser. It's set up the way it is because [many people use numeric coupon codes](https://github.com/woocommerce/woocommerce/issues/15725).

**Comment by javorszky** [comment]
I checked with Posts. In the `wp-admin/post.php`, when WordPress is outputting the edit post metaboxes after having a global `$post` object, the `->ID` comes back as `int`.

Right here: https://github.com/WordPress/WordPress/blob/master/wp-admin/post.php#L105

**Comment by claudiulodro** [comment]
@javorszky try:
```
add_action( 'add_meta_boxes', function(){
	add_meta_box( 'foo', 'bar', function( $post ) {
		var_dump( $post->ID );
	});
});
```
It comes across as a string in my testing.

**Comment by javorszky** [comment]
Hum, yeah, weird... confirmed, comes in as string. I'll go hunting for that bug over the weekend if I'll have time (and y'all haven't found it yet), but paid work comes first.

**Comment by javorszky** [comment]
Okay, it was bugging me. Here's what's happening:

1. in `wp-admin/post.php` the `edit` case happens, and within that the post gets reloaded here: https://github.com/WordPress/WordPress/blob/4.9.5/wp-admin/post.php#L167
2. that function will run the post object through its own filter with filter `edit` here: https://github.com/WordPress/WordPress/blob/4.9.5/wp-includes/post.php#L552
3. because at the time `$this->filter = "raw"`, and the `$filter` is `edit`, that will run the object through `sanitize_post` here https://github.com/WordPress/WordPress/blob/4.9.5/wp-includes/class-wp-post.php#L354
4. `sanitize_post` will, in turn, run all the fields through `sanitize_post_field` here: https://github.com/WordPress/WordPress/blob/4.9.5/wp-includes/post.php#L1940
5. and even though we have 3 fields set as `int` (https://github.com/WordPress/WordPress/blob/4.9.5/wp-includes/post.php#L1973), by the time we get to this part (https://github.com/WordPress/WordPress/blob/4.9.5/wp-includes/post.php#L2027-L2034), those three will be ran through `esc_attr`
6. `esc_attr` will feed it through `_wp_specialchars` here https://github.com/WordPress/WordPress/blob/4.9.5/wp-includes/formatting.php#L3978
7. which begins with `$string = (string) $string;` here https://github.com/WordPress/WordPress/blob/4.9.5/wp-includes/formatting.php#L912


https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L2233

**Comment by javorszky** [comment]
Flagged it on https://core.trac.wordpress.org/ticket/43752#ticket

**Comment by mikejolley** [comment]
Let's cast it our side for now - that can be done without side effects.
