### ISSUE TITLE
wc_price( $report_data->net_sales) not considering custom fee

### ISSUE THREAD

**Issue by rahuladams** [woocommerce/woocommerce#19719]
The "net sales this month" part of the "Show status widget." shows the total Revenue of the month (In the wp-admin dashboard page) but it does not take the amount that is added to the order via `WC()->cart->add_fee(amount)` using the `woocommerce_cart_calculate_fees` action. into consideration. 

I believe the `query_report_data()` function inside class-wc-report-sales-by-date.php needs to check for fee also?

**Comment by mikejolley** [comment]
`_order_total` is used as the basis for these calculations. `_order_total` already contains any fees you've added, so these are definitely included in the report.

Specifically for `net_sales`, the fees are not removed on this total. Net is TOTAL (including fees) minus shipping and taxes.
