### ISSUE TITLE
Duplicated Store Notices on cart and checkout pages

### ISSUE THREAD

**Issue by tiagonoronha** [woocommerce/woocommerce#19717]
Both the `form-checkout.php` and `cart.php` templates directly call `wc_print_notices()` instead of using hooks.

In the Checkout template the notice is shown twice because it's hooked via `woocommerce_before_shop_loop`, also also printed directly on the template.

In `cart.php` the direct call to `wc_print_notices()` should also be removed, and added again via one of the available hooks.

Originally reported here: https://github.com/woocommerce/storefront/issues/801

**Comment by kloon** [comment]
@tiagonoronha the only hooks where wc_print_notices are hooked into are woocommerce_shortcode_before_product_cat_loop, woocommerce_before_shop_loop and woocommerce_before_single_product

None of those are called on the cart or checkout pages, does Storefront perhaps not have their own hook that we call that creates the duplicates?

I do agree it might be good to move to a hook system for the notices in all our templates as we do with the 3 hooks above.

**Comment by peterfabian** [comment]
side note: `wc_print_notices()` also clear notices once printed, so I think the problem is that the notices are also *added* twice. Removing the print might remove the immediate display, but might not be good enough solution, because if some code would call `wc_print_notices()` afterwards, it gets the unprinted notices again.

**Comment by tiagonoronha** [comment]
@kloon Storefront does have its own hook, but that hasn't been an issue until now.

Even if I remove the custom hook, notices are still being shown twice on the Checkout page.

I think that having `wc_print_notices()` in a hook like all the other templates would make more sense.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19794
