### ISSUE TITLE
Backorder Notification

### ISSUE THREAD

**Issue by sined123321** [woocommerce/woocommerce#19722]
Hi there, 

I have a little problem with the backorder notification on my woocommerce shop.

What it is now: I set in the product backorders: allowed, but notify customer. When I press a variaton on the product page it will show available for backorder. So far so good. When someone place the order it will show the text backorderer: 1 on the order confirmation, on the pdf invoice, on the e-mail. 

What I want: Show the notification only on the product information page. Not on the e-mails, order confirmation, etc. But when I set up backorders only to allow. There is also no notification on the Product Page for the customer.

So do someone of you know, how I can change this? Is there a custom code or something else I can use. 

This is really important for me. I tried to find a solution about 1 week without any luck. So please help me.

Thanks and all the best
Sined123321

**Comment by peterfabian** [comment]
Hi,

Unfortunately, this is not a support forum for development questions. I would recommend to try to get help from one of the sources below:
- https://wordpress.stackexchange.com/
- https://woocommerce.com/customizations/
- https://wordpress.org/support/

As a starting point, though, you can try to create a filter function and hook it to `woocommerce_display_item_meta` filter, e.g.:

```
add_filter('woocommerce_display_item_meta', 'item_meta_html_filter', 10, 3);
function item_meta_html_filter($html, $item, $args) {
        // filter out Backordered message from html, or get rid of all order item meta html
	return '';
}
```
