### ISSUE TITLE
Image zoom not working with Woocommerce 3.3.5

### ISSUE THREAD

**Issue by cuongpx** [woocommerce/woocommerce#19724]
With Woocommerce 3.3.5, on the single product view, the zoom don't launch.
Wordpress version: 4.9.5
I added the support in the functions.php
add_theme_support( 'wc-product-gallery-zoom' );
add_theme_support( 'wc-product-gallery-lightbox' );
add_theme_support( 'wc-product-gallery-slider' );

// Woocommerce Support by Theme y/n
add_theme_support( 'woocommerce' );

the zoom don't launch.

help.

**Comment by jefreylandicho** [comment]
what template are you using?

**Comment by cuongpx** [comment]
@jefreylandicho  i do myself template.

**Comment by kloon** [comment]
@cuongpx I am not able to reproduce this using a default theme like twenty seventeen or storefront. Chances are the theme you are using are causing a conflict or have not integrated with WooCommerce correctly.

If you are developing a theme yourself and overriding the single product template I suggest you look at how the core template looks and work based on that.

To test the theory try switching to a default theme like twenty seventeen and/or disable all plugin except WooCommerce.
