### ISSUE TITLE
GDPR: Tools to help remove old (or no longer needed) orders

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#19736]
To avoid holding on to unnecessary data, we should introduce some tools to clean up the orders database.

I propose the following:

- Tool to trash/anonymise orders after X amount of time:
    - Trash failed orders after X days|years|months. Default: 30 days.
    - Trash cancelled orders after X days|years|months. Default: 30 days.
    - Trash pending orders after X days|years|months. Default: 30 days.
    - Anonymise completed orders after X days|years|months. Default off.

cc @allendav

**Comment by DavidAnderson684** [comment]
* Anonymise completed orders after X days|years|months. Default off.

Given that the GDPR concerns data of individuals, should it anonymise all orders, or only those without a company billing name (hence, presumptively, an individual)? (With or without a filter to adjust whatever is the default behaviour?)

**Comment by mikejolley** [comment]
I don't think that's safe. Company could be filled in for variety of reasons/autocompleted. No guarantee it's not an individual.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19743
