### ISSUE TITLE
GDPR: Time to surface HTTPS as a requirement

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#19735]
Shops handle personal information and need to use SSL. Whilst we surface warnings around SSL in system status, we should do it more prominently on WooCommerce screens.

- Add an admin notice if HTTPS is not used. This should check checkout and admin, and could also check site and home URLs.
- Link to docs on how to get SSL setup
- Should be dismissible but at least we've done our bit to inform the user

**Comment by claudiosanches** [comment]
> Add an admin notice if HTTPS is not used. This should check checkout and admin, and could also check site and home URLs.

Easier to just check if everything is under HTTPS, since now is required for almost of the pages, so better check if is configured, this should covers admin too.

**Comment by claudiosanches** [comment]
See #19756
