### ISSUE TITLE
Support for setting publish date through WC API

### ISSUE THREAD

**Issue by callumstrubi** [woocommerce/woocommerce#19731]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Setting a `date` field within the woocommerce product data does not affect the publish-date of the resulting product.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
The API docs here indicate this is a read only field:

https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties

I've logged a question in the development branch for the API https://github.com/woocommerce/wc-api-dev/issues/104
