### ISSUE TITLE
Notice while downloading GeoIP database

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#19742]
![capture](https://user-images.githubusercontent.com/3774827/38865831-bf72dc2a-425e-11e8-9e3b-e49ccec535ce.JPG)

CC @claudiosanches

**Comment by mikejolley** [comment]
@claudiosanches

**Comment by claudiosanches** [comment]
@mikejolley have you tested and really is a bug?

**Comment by mikejolley** [comment]
No I assigned you my friend :)

**Comment by claudiosanches** [comment]
@shivapoudel not sure, but maybe something related to Windows here. Still Phar should be working... No luck reproducing it yet.

@mikejolley should be nice have test in other machine besides my :smile:

**Comment by kloon** [comment]
I did a couple of tests and am unable to replicate this, might be specific to windows, tested on a Vagrant server running Ubuntu and PHP 7.2.

**Comment by shivapoudel** [comment]
@kloon @claudiosanches Please anyone try in the windows machine because I have tested with 3 machine today at replicated the same issue. If found any solution then will raise a PR :)

**Comment by claudiosanches** [comment]
The problem is, I don't have any windows to test, no to mention that Windows can works different, depending on the way that you install, since there is many ways of doing it.

**Comment by shivapoudel** [comment]
The problem was it couldn't find the location of file existent:
```
Phar Error: attempted to extract non-existent file "GeoLite2-Country_20180403\GeoLite2-Country.mmdb" from phar "C:/Users/Shiva Poudel/AppData/Local/Temp/GeoLite2-Country.tar-4aAxMD.tmp"
```

I have also browse that directory during the run of cron job and found that was downloading correctly but maybe a space between `Shiva Poudel` in the path giving a trouble.

@claudiosanches Can we download the file in the `wp-content/upgrade` folder instead of that location because while updating WordPress there has not been the problem yet?

**Comment by claudiosanches** [comment]
@shivapoudel First time I'm seeing it, I see the space, but Phar should be able to handle it already.

Here the code:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-geolocation.php#L230-L283

You can trigger it any time using `WC_Geolocation::update_database()`, I'll need your help to test check it, since not sure that can be going wrong on Windows.

> Can we download the file in the wp-content/upgrade folder instead of that location because while updating WordPress there has not been the problem yet?

We don't try to control the download destination, since we are just using `download_url()` to download it, and then we extract from the tmp directory.

**Comment by shivapoudel** [comment]
@claudiosanches I tried to comment some code and tried to print logs for you my friend :)

```php
// GeoLite2 database name.
$database  = 'GeoLite2-Country.mmdb';
$dest_path = $upload_dir['basedir'] . DIRECTORY_SEPARATOR . $database;

// Extract files with PharData. Tool built into PHP since 5.3.
$file      = new PharData( $tmp_database_path ); // phpcs:ignore PHPCompatibility.PHP.NewClasses.phardataFound
// $file_path = $file->current()->getFileName() . DIRECTORY_SEPARATOR . $database;

// Extract under uploads directory.
// $file->extractTo( $upload_dir['basedir'], $file_path, true );

echo '<pre>Downloaded file: ' . print_r( $tmp_database_path, true ) . '</pre>';
echo '<pre>Strange PHAR data: ' . print_r( $file, true ) . '</pre>';

die();
```

And the result was like this and seems strange `new PharData` has no data :)

```
Downloaded file: C:\Users\SHIVAP~1\AppData\Local\Temp/GeoLite2-Country.tar-gFpGCt.tmp
Strange PHAR data: PharData Object
(
    [pathName:SplFileInfo:private] => 
    [glob:DirectoryIterator:private] => 
    [subPathName:RecursiveDirectoryIterator:private] => 
)
```

One question here can't we use core function `unzip_file()` instead of this one :)

**Comment by claudiosanches** [comment]
@shivapoudel not sure if `unzip_file()` will work with `tar.gz` files.

This does not looks like correct:

```
C:\Users\SHIVAP~1\AppData\Local\Temp/GeoLite2-Country.tar-gFpGCt.tmp
```

Maybe fixing that `/` ?

**Comment by shivapoudel** [comment]
@claudiosanches I have tried to replace `/` and no success. Debugging results looks like this:

```
Temp File: C:\Users\SHIVAP~1\AppData\Local\Temp\GeoLite2-Country.tar-io5vjp.tmp
File Data: PharData Object
(
    [pathName:SplFileInfo:private] => phar://C:/Users/Shiva Poudel/AppData/Local/Temp/GeoLite2-Country.tar-io5vjp.tmp/GeoLite2-Country_20180403
    [fileName:SplFileInfo:private] => GeoLite2-Country_20180403
    [glob:DirectoryIterator:private] => 
    [subPathName:RecursiveDirectoryIterator:private] => 
)
File Path: GeoLite2-Country_20180403\GeoLite2-Country.mmdb
```

Additionally [docs](http://php.net/manual/en/phardata.extractto.php) states this method is similar to `ZipArchive::extractTo()`.

**Comment by claudiosanches** [comment]
@shivapoudel so no luck testing `unzip_file()`?

**Comment by shivapoudel** [comment]
@claudiosanches I also tried `unzip_file()` and no luck. Is there any alternatives to untar that file?

**Comment by claudiosanches** [comment]
@shivapoudel not sure even if that is the problem, maybe also the path or even downloading something wrong on Windows

**Comment by shivapoudel** [comment]
@claudiosanches can you assign anyone with Windows system in team to test it. I tried hard but couldn't find any clue why `extractTo()` is not working in my 3 system. I will try again from another team member windows and check it tomorrow as its been late night here :)

**Comment by claudiosanches** [comment]
@shivapoudel I don't know anyone that uses Windows, not to mention that I'm using Phar to avoid problems on Windows.

**Comment by claudiosanches** [comment]
@shivapoudel how do you are using it on Windows? Using Xampp or something like?

**Comment by shivapoudel** [comment]
@claudiosanches Using XAMPP with custom vhost configuration.

**Comment by claudiosanches** [comment]
Thanks, I'll try something here.

**Comment by shivapoudel** [comment]
@dougaitken That steps should only trigger `WC_Geolocation::maybe_update_database()` which we can trigger any time using `WC_Geolocation::update_database()` :)

**Comment by claudiosanches** [comment]
@dougaitken probably you catching people that for some reason did not downloaded the database yet, but here looks like a problem to extract the database from `tar.gz`, for some reason on Windows is missing something.

**Comment by claudiosanches** [comment]
@shivapoudel please check your `php.ini` file, look for `;extension=php_bz2.dll` and remove the `;` to uncomment this like, after that you need to restart your server on Xampp.
If don't works, you can try also uncomment `extension=php_zlib.dll`.

**Comment by claudiosanches** [comment]
You can also check with `phpinfo()` for `bz2`:

![screenshot from 2018-04-20 12-56-44](https://user-images.githubusercontent.com/1264099/39061345-5b8a30c6-449a-11e8-9045-ffbb3b8c2f47.png)

**Comment by shivapoudel** [comment]
@claudiosanches seems like `bz2` and `zlib` both are already enabled in XAMPP:

**bz2**
![capture](https://user-images.githubusercontent.com/3774827/39062409-225184ce-44e7-11e8-9e59-7ecabce43595.PNG)

**zlib**
![zlib](https://user-images.githubusercontent.com/3774827/39063069-6ad5c744-44e9-11e8-8f9a-a9eac45b9d4b.png)

**Comment by claudiosanches** [comment]
@shivapoudel well, for requirements, looks like it's all done: http://php.net/manual/en/phar.requirements.php

What about Phar?
My is showing this:

![screenshot from 2018-04-20 14-11-20](https://user-images.githubusercontent.com/1264099/39064401-c5976a42-44a4-11e8-8a35-13d3ed8082ca.png)

**Comment by claudiosanches** [comment]
Well, I'll really need your help... Because is everything correct, but maybe there is some problem downloading it for some reason.

Try download the file from here: http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz

Then try run with this script:

```php
try {
  $database_path = ''; // path to where you downloaded the database.
  $file = new PharData( $database_path );
  $file->extractTo( './' ); // Just need a destination path, you can change it.
} catch ( Exception $e ) {
  print_r( $e->getMessage() );
}
```

So we can determine if there is something wrong or not with `download_url()`.
Can you please test it for me?
No luck with Windows and VMs here xD

**Comment by shivapoudel** [comment]
@claudiosanches While testing, finally found the culprit `DIRECTORY_SEPARATOR` my friend :)
