### ISSUE TITLE
Store no longer sending emails

### ISSUE THREAD

**Issue by jimmyeao** [woocommerce/woocommerce#19746]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Using WP Mail SMTP and WP Mail Logging
2. Create Order and Checkout
3. No Emails sent or logged

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...
Emails sent and an entry in the WP Mail Log

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```

`
### WordPress Environment ###

Home URL: https://lincolngolfcentre.org.uk
Site URL: https://lincolngolfcentre.org.uk
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.0.2g
PHP Version: 7.0.28-0ubuntu0.16.04.1
PHP Post Max Size: 50 MB
PHP Time Limit: 500
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: lcwp_
MaxMind GeoIP Database: ✔
Total Database Size: 27.58MB
Database Data Size: 23.35MB
Database Index Size: 4.23MB
lcwp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
lcwp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
lcwp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
lcwp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
lcwp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
lcwp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
lcwp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
lcwp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
lcwp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
lcwp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
lcwp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
lcwp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
lcwp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
lcwp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
lcwp_akeeba_common: Data: 0.02MB + Index: 0.00MB
lcwp_ak_params: Data: 0.02MB + Index: 0.00MB
lcwp_ak_profiles: Data: 0.02MB + Index: 0.00MB
lcwp_ak_stats: Data: 0.02MB + Index: 0.03MB
lcwp_ak_storage: Data: 0.02MB + Index: 0.00MB
lcwp_ak_users: Data: 0.02MB + Index: 0.00MB
lcwp_bccf_dex_bccf_submissions: Data: 0.02MB + Index: 0.00MB
lcwp_bccf_dex_discount_codes: Data: 0.02MB + Index: 0.00MB
lcwp_bccf_dex_season_prices: Data: 0.02MB + Index: 0.00MB
lcwp_bccf_reservation_calendars: Data: 0.02MB + Index: 0.00MB
lcwp_bccf_reservation_calendars_data: Data: 0.02MB + Index: 0.00MB
lcwp_booking: Data: 0.02MB + Index: 0.00MB
lcwp_bookingdates: Data: 0.02MB + Index: 0.00MB
lcwp_booki_calendar: Data: 0.02MB + Index: 0.00MB
lcwp_booki_calendar_day: Data: 0.02MB + Index: 0.00MB
lcwp_booki_cascading_item: Data: 0.02MB + Index: 0.00MB
lcwp_booki_cascading_list: Data: 0.02MB + Index: 0.00MB
lcwp_booki_coupons: Data: 0.02MB + Index: 0.00MB
lcwp_booki_event_log: Data: 0.02MB + Index: 0.00MB
lcwp_booki_form_element: Data: 0.02MB + Index: 0.00MB
lcwp_booki_gcal: Data: 0.02MB + Index: 0.00MB
lcwp_booki_gcal_events: Data: 0.02MB + Index: 0.00MB
lcwp_booki_gcal_projects: Data: 0.02MB + Index: 0.00MB
lcwp_booki_optional: Data: 0.02MB + Index: 0.00MB
lcwp_booki_order: Data: 0.02MB + Index: 0.00MB
lcwp_booki_order_cascading_item: Data: 0.02MB + Index: 0.00MB
lcwp_booki_order_days: Data: 0.02MB + Index: 0.00MB
lcwp_booki_order_form_elements: Data: 0.02MB + Index: 0.00MB
lcwp_booki_order_optionals: Data: 0.02MB + Index: 0.00MB
lcwp_booki_order_quantity_element: Data: 0.02MB + Index: 0.00MB
lcwp_booki_project: Data: 0.02MB + Index: 0.00MB
lcwp_booki_quantity_element: Data: 0.02MB + Index: 0.00MB
lcwp_booki_quantity_element_calendar: Data: 0.02MB + Index: 0.00MB
lcwp_booki_quantity_element_calendarday: Data: 0.02MB + Index: 0.00MB
lcwp_booki_quantity_element_item: Data: 0.02MB + Index: 0.00MB
lcwp_booki_reminders: Data: 0.02MB + Index: 0.00MB
lcwp_booki_roles: Data: 0.02MB + Index: 0.00MB
lcwp_booki_settings: Data: 0.02MB + Index: 0.00MB
lcwp_booki_trashed: Data: 0.06MB + Index: 0.00MB
lcwp_booki_trashed_project: Data: 0.02MB + Index: 0.00MB
lcwp_bup_bookings: Data: 0.02MB + Index: 0.00MB
lcwp_bup_bookings_meta: Data: 0.02MB + Index: 0.00MB
lcwp_bup_carts: Data: 0.02MB + Index: 0.02MB
lcwp_bup_categories: Data: 0.02MB + Index: 0.00MB
lcwp_bup_filters: Data: 0.02MB + Index: 0.00MB
lcwp_bup_filter_staff: Data: 0.02MB + Index: 0.00MB
lcwp_bup_orders: Data: 0.02MB + Index: 0.00MB
lcwp_bup_services: Data: 0.00MB + Index: 0.00MB
lcwp_bup_service_rates: Data: 0.00MB + Index: 0.00MB
lcwp_bup_service_variable_pricing: Data: 0.00MB + Index: 0.00MB
lcwp_bup_staff_availability: Data: 0.00MB + Index: 0.00MB
lcwp_bup_staff_availability_breaks: Data: 0.00MB + Index: 0.00MB
lcwp_cleantalk_sfw: Data: 0.02MB + Index: 0.04MB
lcwp_cleantalk_sfw_logs: Data: 0.00MB + Index: 0.00MB
lcwp_commentmeta: Data: 0.02MB + Index: 0.03MB
lcwp_comments: Data: 0.02MB + Index: 0.09MB
lcwp_cpabc_appointments: Data: 0.02MB + Index: 0.00MB
lcwp_cpabc_appointments_discount_codes: Data: 0.02MB + Index: 0.00MB
lcwp_cpabc_appointment_calendars: Data: 0.02MB + Index: 0.00MB
lcwp_cpabc_appointment_calendars_data: Data: 0.02MB + Index: 0.00MB
lcwp_cpappbk_forms: Data: 0.02MB + Index: 0.00MB
lcwp_cpappbk_messages: Data: 0.02MB + Index: 0.00MB
lcwp_dopbsp_api_keys: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_availability: Data: 0.02MB + Index: 0.05MB
lcwp_dopbsp_availability_no: Data: 0.02MB + Index: 0.06MB
lcwp_dopbsp_availability_price: Data: 0.02MB + Index: 0.06MB
lcwp_dopbsp_calendars: Data: 0.02MB + Index: 0.08MB
lcwp_dopbsp_coupons: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_days: Data: 0.08MB + Index: 0.09MB
lcwp_dopbsp_discounts: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_discounts_items: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_discounts_items_rules: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_emails: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_emails_translation: Data: 0.02MB + Index: 0.03MB
lcwp_dopbsp_extras: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_extras_groups: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_extras_groups_items: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_fees: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_forms: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_forms_fields: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_forms_select_options: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_languages: Data: 0.02MB + Index: 0.03MB
lcwp_dopbsp_locations: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_models: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_reservations: Data: 0.02MB + Index: 0.14MB
lcwp_dopbsp_rules: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_searches: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_settings: Data: 0.02MB + Index: 0.02MB
lcwp_dopbsp_settings_calendar: Data: 0.02MB + Index: 0.03MB
lcwp_dopbsp_settings_notifications: Data: 0.02MB + Index: 0.03MB
lcwp_dopbsp_settings_payment: Data: 0.02MB + Index: 0.03MB
lcwp_dopbsp_settings_search: Data: 0.02MB + Index: 0.03MB
lcwp_dopbsp_translation_en: Data: 0.28MB + Index: 0.14MB
lcwp_easy_pie_contacts: Data: 0.02MB + Index: 0.00MB
lcwp_easy_pie_cs_entities: Data: 0.02MB + Index: 0.00MB
lcwp_easy_pie_cs_subscribers: Data: 0.02MB + Index: 0.00MB
lcwp_easy_pie_emails: Data: 0.02MB + Index: 0.00MB
lcwp_gen_ustsbooking: Data: 0.02MB + Index: 0.00MB
lcwp_gen_ustsbooking_paymentmethods: Data: 0.02MB + Index: 0.00MB
lcwp_links: Data: 0.02MB + Index: 0.02MB
lcwp_nf3_actions: Data: 0.02MB + Index: 0.00MB
lcwp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
lcwp_nf3_fields: Data: 0.02MB + Index: 0.00MB
lcwp_nf3_field_meta: Data: 0.08MB + Index: 0.00MB
lcwp_nf3_forms: Data: 0.02MB + Index: 0.00MB
lcwp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
lcwp_nf3_objects: Data: 0.02MB + Index: 0.00MB
lcwp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
lcwp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
lcwp_nm_personalized: Data: 0.02MB + Index: 0.00MB
lcwp_options: Data: 5.11MB + Index: 0.14MB
lcwp_postmeta: Data: 5.28MB + Index: 0.20MB
lcwp_posts: Data: 2.36MB + Index: 0.06MB
lcwp_sc_currency_list: Data: 0.02MB + Index: 0.01MB
lcwp_sc_scbooking: Data: 0.02MB + Index: 0.00MB
lcwp_sc_scbooking_paymentmethods: Data: 0.02MB + Index: 0.00MB
lcwp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
lcwp_termmeta: Data: 0.02MB + Index: 0.03MB
lcwp_terms: Data: 0.02MB + Index: 0.03MB
lcwp_term_relationships: Data: 0.02MB + Index: 0.02MB
lcwp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
lcwp_usermeta: Data: 0.11MB + Index: 0.03MB
lcwp_users: Data: 0.02MB + Index: 0.05MB
lcwp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
lcwp_wc_download_log: Data: 0.02MB + Index: 0.03MB
lcwp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
lcwp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
lcwp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
lcwp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
lcwp_wfBlocks: Data: 0.02MB + Index: 0.02MB
lcwp_wfBlocks7: Data: 0.02MB + Index: 0.05MB
lcwp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
lcwp_wfConfig: Data: 0.30MB + Index: 0.00MB
lcwp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
lcwp_wfFileChanges: Data: 0.02MB + Index: 0.00MB
lcwp_wfFileMods: Data: 3.52MB + Index: 0.00MB
lcwp_wfHits: Data: 1.02MB + Index: 1.17MB
lcwp_wfHoover: Data: 0.02MB + Index: 0.02MB
lcwp_wfIssues: Data: 0.02MB + Index: 0.06MB
lcwp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
lcwp_wfLeechers: Data: 0.02MB + Index: 0.00MB
lcwp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
lcwp_wfLocs: Data: 0.02MB + Index: 0.00MB
lcwp_wfLogins: Data: 0.02MB + Index: 0.03MB
lcwp_wfNet404s: Data: 0.02MB + Index: 0.02MB
lcwp_wfNotifications: Data: 0.02MB + Index: 0.00MB
lcwp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
lcwp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
lcwp_wfScanners: Data: 0.02MB + Index: 0.00MB
lcwp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
lcwp_wfStatus: Data: 0.16MB + Index: 0.13MB
lcwp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
lcwp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
lcwp_wpdevart_calendars: Data: 0.02MB + Index: 0.00MB
lcwp_wpdevart_dates: Data: 0.02MB + Index: 0.00MB
lcwp_wpdevart_extras: Data: 0.02MB + Index: 0.00MB
lcwp_wpdevart_forms: Data: 0.02MB + Index: 0.00MB
lcwp_wpdevart_payments: Data: 0.02MB + Index: 0.00MB
lcwp_wpdevart_reservations: Data: 0.02MB + Index: 0.00MB
lcwp_wpdevart_themes: Data: 0.02MB + Index: 0.00MB
lcwp_wpgmza: Data: 0.02MB + Index: 0.00MB
lcwp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB
lcwp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB
lcwp_wpgmza_circles: Data: 0.02MB + Index: 0.00MB
lcwp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
lcwp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
lcwp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB
lcwp_wpgmza_rectangles: Data: 0.02MB + Index: 0.00MB
lcwp_wpic_posts: Data: 0.02MB + Index: 0.00MB
lcwp_wpml_mails: Data: 0.02MB + Index: 0.00MB
wbk_appointments: Data: 0.02MB + Index: 0.02MB
wbk_days_on_off: Data: 0.02MB + Index: 0.02MB
wbk_email_templates: Data: 0.02MB + Index: 0.02MB
wbk_gg_calendars: Data: 0.02MB + Index: 0.02MB
wbk_locked_time_slots: Data: 0.02MB + Index: 0.02MB
wbk_services: Data: 0.02MB + Index: 0.02MB
wbk_service_categories: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

amenity-sets: 2
attachment: 60
bookable_person: 2
bookable_resource: 4
flamingo_contact: 10
flamingo_inbound: 7
gen_custom_booking: 1
jetpack_migration: 2
locations: 1
nav_menu_item: 18
nf_sub: 1
page: 24
post: 9
pricing-models: 2
product: 7
reservations: 1
revision: 224
room-locations: 1
rooms: 7
sc_custom_booking: 1
shop_coupon: 2
shop_order: 8
tribe_events: 1
tribe_organizer: 1
tribe_venue: 1
wc_booking: 26
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Akismet Anti-Spam: by Automattic – 4.0.3
Ban Hammer: by Mika Epstein – 2.6
Better Search Replace: by Delicious Brains – 1.3.2
Black Studio TinyMCE Widget: by Black Studio – 2.6.2
Anti-Spam by CleanTalk: by СleanTalk  – 5.93.1
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.2

Under Construction / Maintenance Mode From Acurax: by Acurax – 2.5.7
Contact Form 7: by Takayuki Miyoshi – 5.0.1
Cookie Notice: by dFactory – 1.2.42
Flamingo: by Takayuki Miyoshi – 1.8
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.3.2
Google XML Sitemaps: by Arne Brachhold – 4.0.9
Jetpack by WordPress.com: by Automattic – 6.0
Really Simple SSL: by Rogier Lankhorst – 2.5.26
Register IPs: by Mika Epstein
Johnny White – 1.8.0

SiteOrigin Widgets Bundle: by SiteOrigin – 1.11.8
The Events Calendar: by Modern Tribe
Inc. – 4.6.13

Page Builder by SiteOrigin (ThinkUpThemes compatible): by Greg Priday – 2.5.10
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.14.5

WooCommerce Bookings: by Automattic – 1.10.11 – 1.11.0 is available
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.3
N-Media WooCommerce PPOM: by Najeeb Ahmad – 11.5.1
WooCommerce Services: by Automattic – 1.12.3
WooCommerce: by Automattic – 3.3.5
Wordfence Security: by Wordfence – 7.1.2
WP Google Maps: by WP Google Maps – 7.0.02
WP Instagram Post And Widget: by Qamar Sheeraz – 1.2
WP Mail Logging: by Christian Zöller – 1.8.3
WP Mail SMTP: by WPForms – 1.2.5
WP Smush: by WPMU DEV – 2.7.8
WPSSO Organization Markup: by JS Morisset – 1.2.2
WPSSO Place / Location and Local Business Meta: by JS Morisset – 2.5.3
WPSSO Schema JSON-LD Markup: by JS Morisset – 1.24.6
WPSSO Strip Schema Microdata: by JS Morisset – 1.3.2
WPSSO Core [Main Plugin]: by JS Morisset – 3.57.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #395 - /shop/
Basket: #396 - /basket/
Checkout: #397 - /checkout-2/
My account: #398 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Engrave
Version: 1.9.0
Author URL: http://www.ThinkUpThemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: –
`

</details>

**Comment by mikejolley** [comment]
There have been no other reports of this. The instructions you've given reproduce the issue on your own site, but not others. Emails are working my side :) 

With that in mind there isn't much we can do here so you'll either need to log a ticket in support, _or go through the following FAQ doc to find your problem:_

https://docs.woocommerce.com/document/email-faq/

Thanks

**Comment by jimmyeao** [comment]
Thanks Mike, I have been through the FAQ. Everything else on the site (contact forms, registrations etc) generate emails just fine, its just WooCommerce that isn't. Last month it was, and I'm struggling to figure out what would cause that. I would expect this to be an either it works for "everything or nothing" if it was down to misconfiguration, but it only seems to be woocommerce that is affected. Perhaps you could point me at some logs or tables I could check for further info?

**Comment by mikejolley** [comment]
@jimmyeao If nothing is logging I don't think it will be server or email formatting. I think it's more likely that the order is either not changing to a status which sends emails, the emails in question are turned off in settings, or there is an unrelated error being thrown before WC gets a chance to change the email e.g. after changing the status.

**Comment by jimmyeao** [comment]
@mikejolley thanks for the info - Ill keep digging
