### ISSUE TITLE
Add validation, hint and placeholder for "Eircode" postcodes in Ireland

### ISSUE THREAD

**Issue by ya-well** [woocommerce/woocommerce#19745]
Hi folks,

This isn't a bug, more an enhancement request that might drum up some usage of Ireland's relatively new national postcode system, Eircode.

At present, the postcode field at checkout is set to not required when the country is Ireland and there is no validation run on the input either. While I suggest the field remain set to "not required" _(usage of Eircode is still much too low to demand required)_, might it be possible to run validation on the field **only if a value is entered?** Perhaps added to the standard validation warning might be a hint to point unfamiliar users to the official Eircode lookup website and added to the empty field itself, a placeholder to remind users as to the correct format.

**STRUCTURE**

The official format of an eircode is: X8X XXXX _(e.g. D02 X285, F23 KP04, W12 AD93, D6W Y271)_

- There is 3 character Routing Key - followed by space - followed by a 4 character Unique Identifier.
- The Routing Key is in the form of letter, digit, digit with the one exception for **_D6W_**, where it is letter, digit, letter.
- The Unique Identifier element is comprised of a random mixture of letters and digits in no discernible pattern.
- There doesn't seem to be any instances where the Unique Identifier is entirely letters or entirely digits - always a mixture of letters and digits seems correct.
- The official presentation of an Eircode includes the space between the Routing Key and Unique Identifier but the official documentation recommends storing the Eircodes in databases without the space.

**VALIDATION:**

The valid characters are as follows:

**Routing Key _(3)_:** [ A,C,D,E,F,H,K,N,P,R,T,V,W,X,Y ] [ 0-9 ] [ 0-9 and "W" for D6W ]
**Unique Identifier _(4)_:** 0-9 and A,C,D,E,F,H,K,N,P,R,T,V,W,X,Y

As above, not all letters are used but of interest are the letters 'i' and 'O'. In some better implementations, these are automatically dropped and correctly replaced with the digit '1' and '0' respectively.

If it helps with creating a regex, the 139 valid Routing Keys are as follows:

A41, A42, A45, A63, A67, A75, A81, A82, A83, A84, A85, A86, A91, A92, A94, A96, A98, C15, D01, D02, D03, D04, D05, D06, D07, D08, D09, D10, D11, D12, D13, D14, D15, D16, D17, D18, D20, D22, D24, **D6W**, E21, E25, E32, E34, E41, E45, E53, E91, F12, F23, F26, F28, F31, F35, F42, F45, F52, F56, F91, F92, F93, F94, H12, H14, H16, H18, H23, H53, H54, H62, H65, H71, H91, K32, K34, K36, K45, K56, K67, K78, N37, N39, N41, N91, P12, P14, P17, P24, P25, P31, P32, P36, P43, P47, P51, P56, P61, P67, P72, P75, P81, P85, R14, R21, R32, R35, R42, R45, R51, R56, R93, R95, T12, T23, T34, T45, T56, V14, V15, V23, V31, V35, V42, V92, V93, V94, V95, W12, W23, W34, W91, X35, X42, X91, Y14, Y21, Y25, Y34, Y35

**UI:**

In the Eircode field at checkout and perhaps the postcode fields in account address details, etc... a placeholder of something like _"e.g. A65 F4E2"_ might prompt users to recall and provide their Eircode. The "A65 F4E2" example is used by Eircode themselves and many state agencies as a sample Eircode as it is not valid so there is no danger of it becoming someone's postcode.

To use Google's [implementation](https://imgur.com/a/awo6f) from their Business Listings website, they have a pop-out prompt beside the Eircode field which shows the same sample Eircode as above and then directs unfamiliar users to the official Eircode lookup _([finder.eircode.ie](https://finder.eircode.ie/))_ to find their own Eircode. While a pop-out prompt wouldn't be in keeping with default checkout styling, could the link to the lookup tool perhaps be included in the default "invalid postcode" message bar that appears atop the checkout... something like _"That Eircode is not valid. Please re-check your details or find your correct Eircode [here](https://finder.eircode.ie/)"_.

**Comment by mikejolley** [comment]
@ya-well did you want to take a stab at this? If the field is not required, the validation logic as-is should account for it and only validate when populated. We can format with or without spaces too - compare against the GB validation rules which are fairly similar.

**Comment by ya-well** [comment]
@mikejolley, I'd love to but unfortunately I'm not setup with Git and my coding ability consists of copying snippets from here and there, changing something and hoping it still works! I'm stuck in the middle of a long store build so I've begun to frequent the repository here, following different issues, reading new proposals, etc. There's certainly a good buzz around here and the efficiency of the team is impressive so I couldn't help myself submitting non-issues!

If I may, I'll post here the two small snippets I've managed to test and get working... perhaps one of the more experienced hands could then pop it into the core if it's approved. One is simply the field placeholder and the other is a regex for validating the Eircodes.


**Placeholder:**

I simply added the placeholder line under 'IE' in **\includes\class-wc-countries.php**

`'placeholder'  => esc_attr__( 'A65 F4E2', 'woocommerce' ),`


**Validation:**

I'm awaiting confirmation back from Eircode around some queries on the Unique Identifier element which might allow us to tighten up validation even more but until I hear more, this will pass validation:

`case 'IE' :`
`$valid = (bool) preg_match( '/^(A41|A42|A45|A63|A67|A75|A81|A82|A83|A84|A85|A86|A91|A92|A94|A96|A98|C15|D01|D02|D03|D04|D05|D06|D07|D08|D09|D10|D11|D12|D13|D14|D15|D16|D17|D18|D20|D22|D24|D6W|E21|E25|E32|E34|E41|E45|E53|E91|F12|F23|F26|F28|F31|F35|F42|F45|F52|F56|F91|F92|F93|F94|H12|H14|H16|H18|H23|H53|H54|H62|H65|H71|H91|K32|K34|K36|K45|K56|K67|K78|N37|N39|N41|N91|P12|P14|P17|P24|P25|P31|P32|P36|P43|P47|P51|P56|P61|P67|P72|P75|P81|P85|R14|R21|R32|R35|R42|R45|R51|R56|R93|R95|T12|T23|T34|T45|T56|V14|V15|V23|V31|V35|V42|V92|V93|V94|V95|W12|W23|W34|W91|X35|X42|X91|Y14|Y21|Y25|Y34|Y35)(\s?)([0-9AC-FHKNPRTV-Y]{4})$/', $postcode );`
`break;`

I dropped this into **\includes\class-wc-validation.php**. The Routing Keys regex could be reduced but the above covers the 139 allowed combinations exactly whereas some of the shorter strings will allow invalid Routing Keys through. I'll submit a shorter string if needs be.

I'm unsure about `\s?` as this allows whitespaces and dashes but I couldn't find the expression to allow only a whitespace. Also, how should the space be handled... do we mark Eircodes without the whitespace as invalid or do we accept Eircodes with and without the whitespace and do some sort of post-input wizardry that stores them in the database without the space but displays them on the front-end with the space?


**Error Message:**

I spent a long number of hours last night trying to figure out how to change the invalid postcode message that appears above the checkout but I'll have to pass on it. Other than doing a "gettext" translation on my end, I cannot understand how it's tackled in core. Is it possible that instead of showing the default:

`{Billing}{Shipping} Eircode is not a valid postcode.`

for an invalid Eircode, it would show:

`{Billing}{Shipping} Eircode is not valid. Please re-check your entry or get the correct Eircode at <a target="_blank" href="https://finder.eircode.ie/">finder.eircode.ie</a>.`

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19951
