### ISSUE TITLE
When Calculating Shipping, Selected shipping method does not persist and updates to default shipping option.

### ISSUE THREAD

**Issue by iandbanks** [woocommerce/woocommerce#19751]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Make sure there are multiple shipping methods available for orders.
2. Go to a cart page (e.g. example.com/cart) with at least one item in the cart.
3. Select a shipping method other than the top/default method.
4. Click the "calculate shipping" button
5. Enter address information and click "Update Totals"

## Expected/actual behavior

When following the above steps, after totals update, the default shipping method is selected, rather than the shipping method chosen by the user.

Expectations are that when you update your shipping method, that the choice you already made will stay selected. E.G. if I selected UPS overnight shipping, then updated my address with "calculate shipping" then when the page refreshes, I would still have UPS overnight selected, rather than, say, Flat rate.

[Video showing the behavior](https://cl.ly/0w1S0y390b1y)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

### WordPress Environment ###

Home URL: https://howwelove.com
Site URL: https://howwelove.com
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.33
PHP Post Max Size: 96 MB
PHP Time Limit: 18000
PHP Max Input Vars: 1000
cURL Version: 7.53.1
NSS/3.28.4

SUHOSIN Installed: –
MySQL Version: 5.7.17
Max Upload Size: 96 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 919.77MB
Database Data Size: 524.27MB
Database Index Size: 395.50MB
wp_woocommerce_sessions: Data: 12.02MB + Index: 0.08MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 3.52MB + Index: 5.55MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.34MB
wp_woocommerce_order_itemmeta: Data: 7.52MB + Index: 8.02MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
email_log: Data: 142.08MB + Index: 0.00MB
wp_blc_filters: Data: 0.02MB + Index: 0.00MB
wp_blc_instances: Data: 0.09MB + Index: 0.05MB
wp_blc_links: Data: 0.38MB + Index: 0.13MB
wp_blc_synch: Data: 0.19MB + Index: 0.09MB
wp_commentmeta: Data: 0.08MB + Index: 0.03MB
wp_comments: Data: 3.52MB + Index: 2.19MB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wp_itsec_log: Data: 1.02MB + Index: 0.17MB
wp_itsec_logs: Data: 10.52MB + Index: 0.50MB
wp_itsec_temp: Data: 0.06MB + Index: 0.06MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_moderncd_log: Data: 2.52MB + Index: 0.00MB
wp_options: Data: 8.50MB + Index: 2.03MB
wp_postmeta: Data: 56.59MB + Index: 60.94MB
wp_posts: Data: 18.55MB + Index: 7.95MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.03MB + Index: 0.00MB
wp_rg_form_view: Data: 1.52MB + Index: 0.66MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 1.52MB + Index: 0.19MB
wp_rg_lead_detail: Data: 3.52MB + Index: 3.50MB
wp_rg_lead_detail_long: Data: 1.52MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.09MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.05MB + Index: 0.03MB
wp_term_relationships: Data: 0.11MB + Index: 0.08MB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wp_usermeta: Data: 134.70MB + Index: 110.33MB
wp_users: Data: 15.52MB + Index: 12.55MB
wp_wc_download_log: Data: 0.06MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpsc_also_bought: Data: 0.11MB + Index: 0.00MB
wp_wpsc_cart_contents: Data: 1.52MB + Index: 0.00MB
wp_wpsc_cart_item_meta: Data: 0.25MB + Index: 0.69MB
wp_wpsc_checkout_forms: Data: 0.02MB + Index: 0.03MB
wp_wpsc_claimed_stock: Data: 0.02MB + Index: 0.03MB
wp_wpsc_coupon_codes: Data: 0.02MB + Index: 0.06MB
wp_wpsc_currency_list: Data: 0.05MB + Index: 0.00MB
wp_wpsc_download_status: Data: 1.52MB + Index: 1.95MB
wp_wpsc_meta: Data: 11.52MB + Index: 3.03MB
wp_wpsc_product_rating: Data: 0.02MB + Index: 0.00MB
wp_wpsc_purchase_logs: Data: 1.52MB + Index: 0.28MB
wp_wpsc_purchase_meta: Data: 0.28MB + Index: 0.83MB
wp_wpsc_region_tax: Data: 0.02MB + Index: 0.02MB
wp_wpsc_submited_form_data: Data: 3.52MB + Index: 2.52MB
wp_wpsc_visitors: Data: 26.56MB + Index: 51.16MB
wp_wpsc_visitor_meta: Data: 49.58MB + Index: 118.84MB

### Post Type Counts ###

attachment: 178
hwl-love-style: 6
ls-quiz-result: 34
nav_menu_item: 37
page: 57
post: 413
product: 84
revision: 1085
shop_coupon: 26674
shop_order: 8135
speaking-engagement: 70
view-template: 2
wpsc-product-file: 168

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Gravity Forms: by rocketgenius – 2.2.5.4
Advanced Custom Fields PRO: by Elliot Condon – 5.6.10
Advanced noCaptcha reCaptcha: by Shamim – 2.4
Akismet Anti-Spam: by Automattic – 4.0.3
WP Offload S3: by Delicious Brains – 1.6.2
Amazon Web Services: by Delicious Brains – 1.0.5
iThemes Security: by iThemes – 6.9.2
Enable Media Replace: by ShortPixel – 3.2.3
HWL Migration Tool: by Matt van Andel – 1.0
How We Love Reporting: by Matt van Andel – 1.0
AWS SMTP Configuration: by Matt van Andel – 1.0
Selective Autoformatting (wpautop): by Matt Van Andel – 1.1
ShareThis: by The ShareThis Team – 7.8
User Switching: by John Blackbourn – 1.3.0
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.5 – Not tested with the active version of WooCommerce
WooCommerce Authorize.Net CIM Gateway: by SkyVerge – 2.7.0 – 2.10.0 is available – Not tested with the active version of WooCommerce
HWL Parametric Product Search: by Matt Van Andel – 1.0
WooCommerce - ModernCD Fulfillment Bridge: by Matt van Andel – 2.0 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooCommerce – 1.6.10
WooCommerce UPS Shipping: by WooCommerce – 3.2.9
WooCommerce USPS Shipping: by WooCommerce – 4.4.8 – 4.4.15 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.5
WP Emmet: by rewish – 0.3.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4117 - /shop/
Cart: #4118 - /cart/
Checkout: #4119 - /checkout/
My account: #4120 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: How We Love 2016
Version: 0.0
Author URL: http://nouveauframework.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: howwelove2016/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/auth/footer.php
howwelove2016/woocommerce/auth/form-grant-access.php
howwelove2016/woocommerce/auth/form-login.php version 2.4.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/auth/header.php
howwelove2016/woocommerce/cart/cart-item-data.php
howwelove2016/woocommerce/cart/cart-totals.php
howwelove2016/woocommerce/cart/cart.php
howwelove2016/woocommerce/cart/proceed-to-checkout-button.php
howwelove2016/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.2.0
howwelove2016/woocommerce/checkout/cart-errors.php
howwelove2016/woocommerce/checkout/form-checkout.php
howwelove2016/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/checkout/form-login.php
howwelove2016/woocommerce/checkout/form-pay.php version 2.5.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/checkout/payment-method.php
howwelove2016/woocommerce/checkout/payment.php version 2.5.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/checkout/review-order.php version 2.3.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/content-product.php
howwelove2016/woocommerce/content-product_cat.php
howwelove2016/woocommerce/content-single-product.php
howwelove2016/woocommerce/content-widget-product.php version 2.5.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/global/breadcrumb.php
howwelove2016/woocommerce/global/form-login.php version 2.1.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/global/sidebar.php
howwelove2016/woocommerce/global/wrapper-end.php version 1.6.4 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/global/wrapper-start.php version 1.6.4 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/loop/no-products-found.php
howwelove2016/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/loop/pagination.php version 2.2.2 is out of date. The core version is 3.3.1
howwelove2016/woocommerce/loop/price.php
howwelove2016/woocommerce/loop/sale-flash.php
howwelove2016/woocommerce/myaccount/dashboard.php
howwelove2016/woocommerce/myaccount/form-edit-account.php version 2.6.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/myaccount/form-login.php version 2.6.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/myaccount/lost-password-confirmation.php
howwelove2016/woocommerce/myaccount/my-account.php
howwelove2016/woocommerce/myaccount/my-address.php
howwelove2016/woocommerce/myaccount/my-downloads.php
howwelove2016/woocommerce/myaccount/my-orders.php
howwelove2016/woocommerce/myaccount/navigation.php
howwelove2016/woocommerce/myaccount/payment-methods.php
howwelove2016/woocommerce/notices/error.php version 1.6.4 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/notices/notice.php
howwelove2016/woocommerce/notices/success.php version 1.6.4 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/product-searchform.php version 2.5.0 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/single-product/add-to-cart/external.php
howwelove2016/woocommerce/single-product/add-to-cart/variation.php
howwelove2016/woocommerce/single-product/product-image.php version 3.1.0 is out of date. The core version is 3.3.2
howwelove2016/woocommerce/single-product/sale-flash.php
howwelove2016/woocommerce/single-product/share.php
howwelove2016/woocommerce/single-product/short-description.php version 1.6.4 is out of date. The core version is 3.3.0
howwelove2016/woocommerce/single-product/tabs/description.php
howwelove2016/woocommerce/single-product/tabs/tabs.php
howwelove2016/woocommerce/single-product/title.php
howwelove2016/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 3.2.0
howwelove2016/woocommerce/single-product.php
howwelove2016/woocommerce/taxonomy-product_cat.php
howwelove2016/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌Learn how to update

### Authorize.Net CIM ###

Environment: Production
Tokenization Enabled: 
Debug Mode: Save to Log

</details>

**Comment by mikejolley** [comment]
If the shipping methods change i.e. after calculation, the selection will be defaulted to the top method in the matching zone.

In the case you present, it sounds like 2 shipping zones have the same method (UPS), however, since calculation caused the zone to change, a different shipping method instance would have been used in the other zone. They may both be named 'UPS', but WC does not know they are the same since it works based on instance ID. It doesn't guess if a method is similar to the current selected method, it just defaults to the new zone default.

There is an option in settings to hide shipping costs until an address is provided. If you want to avoid someone choosing a method not applicable to themselves, you can use this.

FWIW this is a temporary issue. When https://github.com/woocommerce/woocommerce/issues/10672 is done we should have an address before shipping is calculated which will ultimately mitigate any confusion. cc @kloon @claudiulodro 

Thanks
