### ISSUE TITLE
Custom attribute values no longer functioning

### ISSUE THREAD

**Issue by neufuture** [woocommerce/woocommerce#19752]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add product with single variation, attribute (size), and attribute value (5)
2. Attempt to add item to cart using URL GET request and arbitrary custom value (ie 8) for attribute (not the one defined in step 1)
Example:
http://dev.vicfarmmeats.com/cart/?add-to-cart=73&variation_id=85&attribute_size=8

## Expected/actual behavior

When I follow those steps, I  get a error message "Invalid value posted for size"

I expected the item to be added to cart with custom size attribute. This worked on past versions of WC.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

WordPress environment
--
Home URL: |   | http://dev.vicfarmmeats.com
Site URL: |   | http://dev.vicfarmmeats.com
WC version: |   | 3.3.5
Log directory writable: |   | /home/vicfarm/dev.vicfarmmeats.com/wp-content/uploads/wc-logs/
WP version: |   | 4.9.5
WP multisite: |   | –
WP memory limit: |   | 4 GB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US

Server environment
--
Server info: |   | Apache
PHP version: |   | 5.6.27
PHP post max size: |   | 8 MB
PHP time limit: |   | 600
PHP max input vars: |   | 1000
cURL version: |   | 7.38.0, OpenSSL/1.0.0
SUHOSIN installed: |   | –
MySQL version: |   | 5.6.38
Max upload size: |   | 2 MB
Default timezone is UTC: |   |  
fsockopen/cURL: |   |  
SoapClient: |   |  
DOMDocument: |   |  
GZip: |   |  
Multibyte string: |   |  
Remote post: |   | wp_remote_post() failed. Contact your hosting provider. cURL error 35: Unsupported SSL protocol version
Remote get: |   | wp_remote_get() failed. Contact your hosting provider. 200

Database
--
WC database version: |   | 3.3.5
Database prefix |   | wp_
MaxMind GeoIP database: |   | The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: /home/vicfarm/dev.vicfarmmeats.com/wp-content/uploads/GeoIP.dat. Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size |   | 0.72MB
Database Data Size |   | 0.56MB
Database Index Size |   | 0.16MB
wp_woocommerce_sessions |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys |   | Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta |   | Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log |   | Data: 0.00MB + Index: 0.00MB
wp_commentmeta |   | Data: 0.00MB + Index: 0.00MB
wp_comments |   | Data: 0.00MB + Index: 0.01MB
wp_links |   | Data: 0.00MB + Index: 0.00MB
wp_options |   | Data: 0.45MB + Index: 0.03MB
wp_postmeta |   | Data: 0.08MB + Index: 0.05MB
wp_posts |   | Data: 0.03MB + Index: 0.02MB
wp_termmeta |   | Data: 0.00MB + Index: 0.01MB
wp_terms |   | Data: 0.00MB + Index: 0.01MB
wp_term_relationships |   | Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy |   | Data: 0.00MB + Index: 0.00MB
wp_usermeta |   | Data: 0.00MB + Index: 0.01MB
wp_users |   | Data: 0.00MB + Index: 0.01MB
wp_wc_download_log |   | Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks |   | Data: 0.00MB + Index: 0.00MB

Post Type Counts
--
attachment |   | 16
customize_changeset |   | 1
nav_menu_item |   | 5
page |   | 9
post |   | 2
product |   | 13
product_variation |   | 1
revision |   | 4
shop_order |   | 1

Security
--
Secure connection (HTTPS): |   | Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors |   |  

Active plugins (3)
--
Jetpack by WordPress.com |   | by Automattic – 6.0
WooCommerce Services |   | by Automattic – 1.12.3
WooCommerce |   | by Automattic – 3.3.5

Settings
--
API enabled: |   |  
Force SSL: |   | –
Currency |   | USD ($)
Currency position |   | left
Thousand separator |   | ,
Decimal separator |   | .
Number of decimals |   | 2
Taxonomies: Product types |   | external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility |   | exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)

WC pages
--
Shop base: |   | #4 - /shop/
Cart: |   | #5 - /cart/
Checkout: |   | #6 - /checkout/
My account: |   | #7 - /my-account/
Terms and conditions: |   | Page not set

Theme
--
Name: |   | Storefront
Version: |   | 2.2.8
Author URL: |   | https://woocommerce.com/
Child theme: |   | – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce support: |   |  

</details>

**Comment by mikejolley** [comment]
That's not a valid attribute for the variation so its correct to reject it. The validation was added in more recent versions. Having customers enter arbitrary values on their own is a security risk. 

For that reason this not not a bug.

**Comment by neufuture** [comment]
It's disabled a feature of being able to have a custom value for an attribute. 

It's validating for a preset value entered in the database. What for instance the customer needed to input a custom value such as a length of a board they need cut. It wouldn't make sense to enter in every decimal variation of length. 

Couldn't you apply an input filter instead to advert any security risks rather than completely disabling it? Or at least allow some sort of work around or filter?

**Comment by solgoodstore** [comment]
Hello,
i have created  attributes  adding different colours  under term and condition, i try adding  the attribute in the product page,keeps loading without adding,pls, how can i fix this bug?
THANKS
![screenshot_2att](https://user-images.githubusercontent.com/39173759/39897313-a128bf7a-54a9-11e8-86ed-f5a7e6598b29.jpg)
![screenshot_1att](https://user-images.githubusercontent.com/39173759/39897314-a16cf29e-54a9-11e8-8339-c338bcd649f4.jpg)
