### ISSUE TITLE
Coupons: Discrepancy In Checkout Page When Coupon Is Already Added 

### ISSUE THREAD

**Issue by harishankerr** [woocommerce/woocommerce#19765]
When a coupon is already added to the checkout page, the `Add Coupon` field continues to be in the page. However, upon navigating to the a different page (say, shop/cart or some other page) and returning to the checkout page, the coupon prompt disappears.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Customer reported a bug with WooCommerce core. Normally there is a notice at the top of the page with "Have a coupon? Click here to enter your code." Clicking that brings up the Apply coupon button and box to enter a coupon. After entering one coupon the box still remains and they can enter more then one. If they leave the checkout page, for example go back to the cart, and then return to the checkout page they no longer have an option to enter coupons. If they remove the coupon and then leave and return the option is back. I could replicate this in my site as well. Rynaldo tested this and he could replicate this as well.

1. Create a coupon of any discount in **WooCommerce > Coupons**.
2. Add a product from the cart and proceed to the checkout page. 
3. Click on the `Have a coupon? Click here to enter your code` button to add your coupon code:
![http://cld.wthms.co/UIqiLN](http://cld.wthms.co/UIqiLN+) 
Full Size: http://cld.wthms.co/UIqiLN
4. Double check the confirmation message, and confirm that the coupon has successfully been applied. You will also notice that the prompt to add a coupon remains in the checkout page:
![http://cld.wthms.co/B0OcJO](http://cld.wthms.co/B0OcJO+) 
Full Size: http://cld.wthms.co/B0OcJO
5. Navigate to some other page (like the `Cart`, `Shop`, or some other page in your site).
6. Now, go back to the `Checkout` page in your site. You will find that the `Have a coupon? Click here to enter your code` is missing. 
![http://cld.wthms.co/OXFccM](http://cld.wthms.co/OXFccM+) 
Full Size: http://cld.wthms.co/OXFccM

## Expected/actual behavior

When I follow those steps, I see that the `Have a coupon? Click here to enter your code` prompt is missing. 

![http://cld.wthms.co/OXFccM](http://cld.wthms.co/OXFccM+) 
Full Size: http://cld.wthms.co/OXFccM

I was expecting to see the `Have a coupon? Click here to enter your code` prompt.

![http://cld.wthms.co/B0OcJO](http://cld.wthms.co/B0OcJO+) 
Full Size: http://cld.wthms.co/B0OcJO

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: https://wctestsite.mystagingwebsite.com
Site URL: https://wctestsite.mystagingwebsite.com
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.28
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.58.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 6.05MB
Database Data Size: 4.66MB
Database Index Size: 1.39MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_cart_notices: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB
wp_comments: Data: 0.05MB + Index: 0.09MB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB
wp_groups_group: Data: 0.02MB + Index: 0.02MB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_nf_objectmeta: Data: 0.02MB + Index: 0.00MB
wp_nf_objects: Data: 0.02MB + Index: 0.00MB
wp_nf_relationships: Data: 0.02MB + Index: 0.00MB
wp_ninja_forms_fav_fields: Data: 0.05MB + Index: 0.00MB
wp_ninja_forms_fields: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 3.13MB + Index: 0.06MB
wp_postmeta: Data: 0.31MB + Index: 0.28MB
wp_posts: Data: 0.17MB + Index: 0.06MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 54
customize_changeset: 1
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nf_sub: 3
page: 16
post: 1
product: 45
product_variation: 16
revision: 12
scheduled-action: 1
shop_coupon: 5
shop_order: 20
shop_subscription: 2
wc_booking: 3
wc_order_status: 8
wishlist: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

VaultPress: by Automattic – 1.9.5
Code Snippets: by Shea Bunge – 2.10.1.1
Jetpack by WordPress.com: by Automattic – 6.0
WooCommerce 360° Image: by WooCommerce – 1.1.5
WooCommerce Bookings: by Automattic – 1.11.0
WooCommerce Composite Products: by SomewhereWarm – 3.13.6 – 3.13.7 is available
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.5
WooCommerce EU VAT Number: by WooCommerce – 2.3.6
WooCommerce Stripe Gateway: by WooCommerce – 4.0.7
WooCommerce Pre-Orders: by WooCommerce – 1.5.8
WooCommerce Product Vendors: by WooCommerce – 2.1.4
WooCommerce Quick View: by WooCommerce – 1.1.12
WooCommerce Services: by Automattic – 1.12.3
WooCommerce FedEx Shipping: by WooCommerce – 3.4.10
WooCommerce Subscriptions: by Prospress Inc. – 2.2.10 – 2.2.19 is available – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.7
WooCommerce WishLists: by Lucas Stark – 2.1.4
WooCommerce: by Automattic – 3.3.3 – 3.3.5 is available

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #3 - /
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Outlet
Version: 2.0.11
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.2.8
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

```
</details>

**Comment by kloon** [comment]
Can confirm this is a bug, applying a coupon on checkout, moving away from checkout page to cart and then back to checkout will not show the apply coupon box anymore, even if the coupon does not have the individual use checkbox checked.

**Comment by mikejolley** [comment]
This was an intentional change here: https://github.com/woocommerce/woocommerce/issues/9099

If you search google for this topic, pre-that change you'll find lots of requests to do the same, so really either way this goes is going to annoy certain users. 

This will be looked at again when https://github.com/woocommerce/woocommerce/issues/10672 is worked on. Until then, the template can be overridden to keep it around on a permanent basis.

Thanks

**Comment by EricJammin** [comment]
@mikejolley Can you point to what / where we can override this behavior?

It should either always show, or be hidden after the coupon in successfully added, imo. Thanks!
