### ISSUE TITLE
Woocomerce API acting inconsistent when variable product have SKU

### ISSUE THREAD

**Issue by ivan133** [woocommerce/woocommerce#19767]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a variable product
2. Set sku in invernoty
3. Create variaions
4. Get valiration with API
5. Save the same value

## Expected/actual behavior

When I follow those steps, I see "Bad Request"
"code":"product_invalid_sku","message":"Invalid or duplicated SKU.","data":{"status":400,"resource_id":23745}

I was expecting to see - variation should be saved, cause I didn't change anything

This happens becuase sku from product is sent to each variable GET request (and actually it's some kind of default sku value) so when I try to save it tries to acutally set this sku to variable

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by kloon** [comment]
@ivan133 Can you perhaps provide an example of the API request you are making to update the variations?

When you want to update a variation via the API you need to make a PUT request to the specific variation URL which looks like this `/wp-json/wc/v2/products/<product_id>/variations/<id>` where `<product_id>` is the ID of the main product and `<id>` is the ID of the variation you are wanting to update, if you just do a request to `/wp-json/wc/v2/products/<product_id>/variations/` it will try and create a new variation.

Please see http://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-product-variation for details on updating a variation.

**Comment by ivan133** [comment]
1. I get all product variations  with
/wp-json/wc/v2/products/122/variations

And get something like this
[
  {
    "id": 133,
    "sku": "111",
   ...
  },
  {
    "id": 134,
    "sku": "111",
   ...
  },
  {
    "id": 135,
    "sku": "111",
   ...
  }
]

2. And then I send PUT each variation 
/wp-json/wc/v2/products/122}/variations/133
/wp-json/wc/v2/products/122}/variations/134
/wp-json/wc/v2/products/122}/variations/135

I send data like this 
  {
    "id": 133,
    "sku": "111",
   ...
  }

The fisrst call fails with code":"product_invalid_sku","message":"Invalid or duplicated SKU.

I see the issue here cause "default" (product's) SKU is returned as variabled product sku value.
