### ISSUE TITLE
Unable to access dashboard with WP core Read Capability

### ISSUE THREAD

**Issue by farhan-noor** [woocommerce/woocommerce#19787]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a user with Subscriber Role which have only Dashboard Access. 

## Expected/actual behavior

When I follow those steps, I cannot access WP dashboard

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
We have created a user role with custom capabilities & core Read capability to perform plugin specific tasks in dashboard. WoCommerce  use read capability for customers role & restrict access to dashboard. It means any other user role using read capability to access dashboard lost its access to dashboard. 

**Solution:** Create a custom capability e.g. woo_read for your Customer role so customers may have access to Accounts Page on front-end & other user roles have access to dashboard as they are supposed to have by WP core Read capability.
Thank you.
```
</details>

**Comment by mikejolley** [comment]
https://gist.github.com/mikejolley/d4c46102d69d4560abb6

**Comment by mikejolley** [comment]
Having this type of access is not desirable for the majority of stores. **It's not a bug because the restriction is intentional.** 

You can use the snippet above if you want to be compatible with WooCommerce. Or you can give your role `view_admin_dashboard` capability.

WC does not modify other capabilities for this, it checks capabilities against a whitelist of allowed caps. Please don't make accusations without first checking the code.

**Comment by farhan-noor** [comment]
I am really sorry if you found me accusing but your are not getting my point.

Default read capability was created in WordPress to have access to dashboard. Here is the documentation https://codex.wordpress.org/Roles_and_Capabilities#read 

My Plugin creates custom user role with custom capabilities in conjunction with read capability to access dashboard & perform plugin specific tasks. But when WC is installed the plugin specific user role lost its access to dashboard. After initial investigation i found that WC is modifying default behavior of Read capability to facilitate CUSTOMER user role. Customer role has READ capability. Stopping READ capability for what it was created in WP, does not make any sense. 

Have a look at this thread https://wordpress.org/support/topic/blank-admin-page-for-aol-manager-users/

I request you to please let READ capability to have access to dashboard as per its description in documentation so other plugins may continue their work.

**Comment by mikejolley** [comment]
This was an intentional change for stores where it's not desirable for users/customers/subscribers to access the admin dashboard. If you're not keen on adding the workaround I posted above, we'll just have to officially not be compatible with each other I suppose :) The user who reported the problem can add the snippet I referenced.

**Comment by farhan-noor** [comment]
You can avoid users/customers/subscribers to access dashboard by much better ways instead of changing core READ capability of WordPress & creating trouble for the whole community.

The best workaround for everyone is to stick with fundamental rules of WordPress. This is what the whole WordPress community preaches from day one.

Thank you for the custom solution.

**Comment by mikejolley** [comment]
Can you show me where you think we're modifying read capability? AFAIK we just check the current caps when loading the dashboard, and if they don't have the correct caps we redirect. No modification of roles.
