### ISSUE TITLE
Internal Server Error into checkout page

### ISSUE THREAD

**Issue by DrMTR** [woocommerce/woocommerce#19786]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Tryed to make a checkout for product.
2. Fill all data for customer, wnd when press Pay with paypal, goes that error.
3. That is..

## Expected/actual behavior

When i follow that steps i see "Internal Server Error", and in debugger i see this:

PHP Fatal error:  Call to a member function get_order_number() on boolean in /public_html/wp-content/plugins/woocommerce/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php on line 77

This is line 77 from **class-wc-gateway-paypal-request.php**

`WC_Gateway_Paypal::log( 'Generating payment form for order ' . $order->get_order_number() . '. Notify URL: ' . $this->notify_url );`

I was expected to proceed with paypal payment.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
WordPress environment
--
Home URL: |   | http://moodmintdesign.com
Site URL: |   | http://moodmintdesign.com
WC version: |   | 3.3.5
Log directory writable: |   | /home/moodmint/public_html/wp-content/uploads/wc-logs/
WP version: |   | 4.9.5
WP multisite: |   | –
WP memory limit: |   | 500 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US

Home URL: |   | http://moodmintdesign.com
-- | -- | --
Site URL: |   | http://moodmintdesign.com
WC version: |   | 3.3.5
Log directory writable: |   | /home/moodmint/public_html/wp-content/uploads/wc-logs/
WP version: |   | 4.9.5
WP multisite: |   | –
WP memory limit: |   | 500 MB
WP debug mode: |   | –
WP cron: |   |  
Language: |   | en_US

```
</details>

**Comment by mikejolley** [comment]
Your issue is that the order created at checkout cannot be loaded. This could be due to a plugin conflict, or server issue (e.g. if using master/save DB setup and the order cannot be read). The paypal error is misleading.

As such I've submitted https://github.com/woocommerce/woocommerce/pull/19802 to show a notice if the order cannot be loaded at checkout.

You'll need to do debugging on your setup/plugins to find your actual issue. That one is not reproducible.

Thanks
