### ISSUE TITLE
Condition In WC_Template_Loader::unsupported_theme_init() Doesn't Account For Possible -1 Page ID Value

### ISSUE THREAD

**Issue by lots0logs** [woocommerce/woocommerce#19790]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Look at the logic in `WC_Template_Loader::unsupported_theme_init()` and notice that a `-1` value will be considered `true` when the intent of the code is not to run when there is no shop page.

https://github.com/woocommerce/woocommerce/blob/1d0528b73fe92d91556083351f039ed428c51082/includes/class-wc-template-loader.php#L195-L205

The possible `-1` value ultimately comes from here:
https://github.com/woocommerce/woocommerce/blob/e8cc1076ad6d6f1d3932fb8087689e79f776768d/includes/wc-page-functions.php#L41-L56

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Fixed by https://github.com/woocommerce/woocommerce/pull/19822
