### ISSUE TITLE
Getting fees deprecated notice from WC add_fee()

### ISSUE THREAD

**Issue by dgrana** [woocommerce/woocommerce#19791]
I'm getting a deprecated notice:

Notice: WC_Cart->fees is deprecated since version 3.2! Use the fees API (WC_Cart::add_fee) instead.

This is the line triggering this error:
`return $this->fees[ $fee_props->id ] = $fee_props;`

It's within the `class-wc-cart-fees.php` file, on the `add_fee` method.

I'm calling add_fee in a `woocommerce_cart_calculate_fees` hook callback as it says it's the recommended way to add fees.

Thank you

**Comment by mikejolley** [comment]
I think you might be mistaken.

`->fees` is deprecated on the WC_Cart class.

Add_fee method in cart is here: https://github.com/woocommerce/woocommerce/blob/5a8c1ee81c30250276127f1a0fb552792256b73c/includes/class-wc-cart.php#L1766

This in turn calls `add_fee` in `WC_Cart_Fees` class https://github.com/woocommerce/woocommerce/blob/5a8c1ee81c30250276127f1a0fb552792256b73c/includes/class-wc-cart-fees.php#L78

This class has no deprecation.

I suspect it's not this line at all and some other code calling `->fees` directly on the cart.

Tested add_fee method and didn't see any notices in my log. Would need code examples, system status report, you to rule out plugin conflicts, and better steps to replicate an issue to anything more here.

Thanks
