### ISSUE TITLE
Uncaught Error: Call to undefined function wp_json_decode() in class-wc-gateway-paypal-response.php

### ISSUE THREAD

**Issue by cklosowski** [woocommerce/woocommerce#19807]
Starting to see quite a few of these in my WooCommerce fatal errors for 3.4-beta1, updated from `master` as of the evening of 4/13/2018, 

```
2018-04-13T11:47:05+00:00 CRITICAL Uncaught Error: Call to undefined function wp_json_decode() in /webroot/wp-content/plugins/woocommerce/includes/gateways/paypal/includes/class-wc-gateway-paypal-response.php:32
Stack trace:
#0 /webroot/wp-content/plugins/woocommerce/includes/gateways/paypal/includes/class-wc-gateway-paypal-ipn-handler.php(63): WC_Gateway_Paypal_Response->get_paypal_order('{"order_id":276...')
#1 /webroot/htdocs/wp-includes/class-wp-hook.php(286): WC_Gateway_Paypal_IPN_Handler->valid_response(Array)
#2 /webroot/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#3 /webroot/htdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /webroot/htdocs/wp-content/plugins/woocommerce/includes/gateways/paypal/includes/class-wc-gateway-paypal-ipn-handler.php(49): do_action('valid-paypal-st...', Array)
#5 /webroot/wp-includes/class-wp-hook.php(286): WC_Gateway_Paypal_IPN_Handler->check_response('')
#6 /var/www/beevy.co/htd
```

**Comment by cklosowski** [comment]
I believe it was this change that introduced the issue: https://github.com/woocommerce/woocommerce/commit/4e3ba1b73b1f6df56d7bd1848fbfbb352e8d21fd

Prior to this commit, the `get_paypal_order` method was just using `json_decode` instead of trying to use `wp_json_decode` which appears to not be available when this is running.

**Comment by spencerfinnell** [comment]
Pretty sure only `wp_json_encode()` was added. Standard `json_decode()` should still be used.

https://pento.net/2014/12/19/json-encoding-in-wordpress-4-1/
https://github.com/WordPress/WordPress/search?utf8=%E2%9C%93&q=wp_json_decode&type=

**Comment by claudiosanches** [comment]
See #19809

**Comment by cklosowski** [comment]
:+1: Thanks @claudiosanches
