### ISSUE TITLE
[API v2] create order, but total does not include tax

### ISSUE THREAD

**Issue by hiheaven** [woocommerce/woocommerce#19801]
I sent a simple create new order just 1 item in it. 
The item has status "taxable" and tax class "Standard" which is 9%.
API is received ok and new order is created.
The returned json is:

{
    "id": 1388,
    "parent_id": 0,
    "number": "1388",
    "order_key": "wc_order_5ad9a075e22f6",
    "created_via": "rest-api",
    "version": "3.3.4",
    "status": "processing",
    "currency": "USD",
    "date_created": "2018-04-20T01:10:29",
    "date_created_gmt": "2018-04-20T08:10:29",
    "date_modified": "2018-04-20T01:10:30",
    "date_modified_gmt": "2018-04-20T08:10:30",
    "discount_total": "0.00",
    "discount_tax": "0.00",
    "shipping_total": "0.00",
    "shipping_tax": "0.00",
    "cart_tax": "0.00",
    "total": "9.50",
    "total_tax": "0.00",
    "prices_include_tax": false,
    "customer_id": 8,
    "customer_ip_address": "",
    "customer_user_agent": "",
    "customer_note": "",
    "billing": {
...

I can see the "total_tax" is 0.00 and on the Woocommerce Order panel displays the correct item's price, but the TAX is not added!
I have setting of tax enabled in WC setting.

Why the REST API can't create order and items not having the Tax included in the total ??

WC version 3.3.4

Server environment
--
Server info: |   | Apache
PHP version: |   | 7.1.14
PHP post max size: |   | 8 MB
PHP time limit: |   | 30
PHP max input vars: |   | 1000
cURL version: |   | 7.54.0, OpenSSL/1.0.2k
SUHOSIN installed: |   | –
MySQL version: |   | 5.6.39

THANK YOU

**Comment by mikejolley** [comment]
This is totally down to:

- The items being sent (are they taxable in product edit page?)
- Tax settings + tax rates input in WooCommerce
- The customer address sent with the request

Tested a request of my own with a tax rate defined for * (everywhere):

![image](https://user-images.githubusercontent.com/90977/39046256-777a04a8-448d-11e8-8e8c-6919675d4c71.png)

The cart tax/tax total is calculated as pictured. Check your settings please. Report back if the settings don't match the results. Hard to see what you're doing in full because you didn't post the request itself or your settings.

**Comment by hiheaven** [comment]
Mike, thanks for replying. 

Here are more details. I think it's likely of the settings in WC, but can't figure it out.

 If i add to cart and create order *same item) from the website, tax is added without a problem. But when through API, there is no tax!
The item number is 1144. In the Request URL, there is "customer_id" number which matches with User # 8 on WC.

The address i entered also matches with address on WC. 

Item has tax status: taxable,
Tax class: Standard

in WC settings  | general, I have:
Enable taxes : Enable taxes and tax calculations


Request:
https://xyz.com/wp/wp-json/wc/v2/orders?consumer_key=xyz&consumer_secret=zyz&customer_id=8
 
package:
{
  "payment_method": "cod",
  "payment_method_title": "Cash on Delivery",
  "set_paid": true,
  "billing": {
    "first_name": "XYZ",
    "last_name": "XYZ",
    "address_1": "My address",
    "address_2": "",
    "city": "Milpitas",
    "state": "CA",
    "postcode": "95035",
    "country": "US",
    "email": "xyz@yahoo.com",
    "phone": "(555) 555-5555"
  },
  "shipping": {
    "first_name": "XYZ",
    "last_name": "XYZ",
    "address_1": "My address",
    "address_2": "",
    "city": "Milpitas",
    "state": "CA",
    "postcode": "95035",
    "country": "US"
  },
  "line_items": [
    {
      "product_id": 1144,
      "quantity": 1
    }
  ]
}


----------------

Please help further, my project is on hold because of this issue. 
THANKS

**Comment by mikejolley** [comment]
Cod taxes differently (shop address). Try another payment method.

**Comment by hiheaven** [comment]
I tried 3 other payments methods: bacs, stripe, cheque.
Same issue, no tax added. I am pulling my hair out!

Any other suggestion is appreciated.

**Comment by hiheaven** [comment]
Here the tax options and standard rate
![options](https://user-images.githubusercontent.com/7958559/39090497-cb22ce74-4595-11e8-80e8-3ef5feccf741.JPG)
![standard](https://user-images.githubusercontent.com/7958559/39090498-cb3a9b94-4595-11e8-9016-c45b489ced3d.JPG)

**Comment by mikejolley** [comment]
That tax rate looks too specific; it's only for one city/zip.

**Comment by hiheaven** [comment]
Mike, You're so right!
Removing the city and zipcode work as expected. The tax are calculated and returned correctly.
THANK YOU SO MUCH!
