### ISSUE TITLE
order page cannot be displayed

### ISSUE THREAD

**Issue by limbbc** [woocommerce/woocommerce#19800]
Hi,
after the new update, i notice my order page cannot be displayed in the wp admin as per attached.
![screenshot 2018-04-20 14 23 35](https://user-images.githubusercontent.com/38276035/39034268-657bc3d4-44a8-11e8-9fdd-37328dee2371.png)

please advise.
Thank you.
Benedict Lim

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
First you should check if the meta boxes are turned off in screen options, top right of the page.

If not, you need to rule out plugin conflicts because thats what this is likely to be. The panels in your screenshot are not coming from WooCommerce. The WooCommerce meta boxes have been removed by something.

See the "Isolating the problem" on the new issue template; these are required.

Thanks

**Comment by limbbc** [comment]
Hi Mike,
firstly like to apologized, i am not the IT guy, i am just a business owner of my site. 
from your answered above, the "options" cannot be clicked in the order page.
i have also try to deactivate all the plugin and reactivate one by one, just to see which plugin causing the conflict, but found none.
i am not too sure what to do next, would be appreciated if you could guide me through step by step to resolved this issued please.
Thank you.
Benedict Lim

**Comment by mikejolley** [comment]
When all were deactivated, what did you see on that screen? Show a screenshot.

**Comment by limbbc** [comment]
Hi Mike,
when all plugin deactivated, it shows the same screen as per attached previously. when i clicked individual order, it just displayed blank. i am running multi vendor marketplace for my site, apart from order cannot be displayed, i also notice the address is missing from my vendor details as well. 

Thank you Mike, hope you could assist me on this.

![vendor - wp admin 1](https://user-images.githubusercontent.com/38276035/39135703-222f05a4-474c-11e8-95a8-5c290d5cc2f0.png)
![vendor - wp admin](https://user-images.githubusercontent.com/38276035/39135704-225ff308-474c-11e8-8008-8a00d12ddd89.png)

![screenshot 2018-04-20 14 23 35](https://user-images.githubusercontent.com/38276035/39135580-d8ad2a5a-474b-11e8-950d-4b32defd9a8b.png)

**Comment by limbbc** [comment]
hi Mike,
please see the attached for your reference. i deactivated everything.
![screenshot 2018-04-24 11 30 57](https://user-images.githubusercontent.com/38276035/39164648-2b5b0e2c-47b3-11e8-9197-2fb157e263e7.png)

**Comment by limbbc** [comment]
Hi Mike,
i have went to Woocommerce > Status > Logs, then i saw the below list of error. i hope this help to solved the issued.
![screenshot 2018-04-24 11 59 08](https://user-images.githubusercontent.com/38276035/39165442-17638cd8-47b7-11e8-92a7-59a9f69b474f.png)

**Comment by mikejolley** [comment]
Customisations/snippets in your theme changing address fields?

**Comment by mikejolley** [comment]
You'd need to use the helpdesk to get someone to access this. I cannot.

**Comment by limbbc** [comment]
Hi Mike,
Good news, i have request Dokan - multi vendor developer to take a look, apparently the issued is caused by the woocommerce country file missing. so now is fixed for the address to show country and also the order is now displaying properly.
just thought this might be a good case scenario to share with you, in case anyone might have the same issued in the future.
Thank you for your assist Mike.

![screenshot 2018-04-26 16 29 18](https://user-images.githubusercontent.com/38276035/39295541-43c533ce-4971-11e8-85ab-19b06682dc75.png)
![screenshot 2018-04-26 16 31 46](https://user-images.githubusercontent.com/38276035/39295543-43f6db4a-4971-11e8-9064-c129037894a1.png)
