### ISSUE TITLE
error recived-order page after payment completed

### ISSUE THREAD

**Issue by mafam1024** [woocommerce/woocommerce#19816]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

the user complete his order and back again to website after payment completed  with MIGS, but it dosn't back to order-recived it redirect to page call thank you with other system on website "event espresso thank you page"

how can i fix this?

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by peterfabian** [comment]
Hi, 

Are you using [Woocommerce Migs](https://wordpress.org/plugins/woocommerce-migs-gateway/) plugin? If yes, then I'm afraid you should contact the developer who created this plugin or your customization, if you have any. This does not seem like a WooCommerce Core issue.

Normally, you can configure the Return URL in the payment gateway settings, as you can see for e.g. PayPal: https://docs.woocommerce.com/document/paypal-standard/#section-7
