### ISSUE TITLE
Admin Search with Punctuation

### ISSUE THREAD

**Issue by jlavoie13** [woocommerce/woocommerce#19811]
Searching products with punctuation used to be possible in 3.3.0 but since this addition 
7a69c80 it is no longer possible.

Search has returned 0 results on terms such as: `4" square`, `mother's`.

When it is run through this function `$data_store->search_products()` the `$like_term` is returning as `mother\\'s` instead of `mother\'s`.

**Comment by kloon** [comment]
@jlavoie13 Make sure you are on the latest version of WooCommerce, I just tested against the 3.4 beta version and can search with punctuation http://cld.wthms.co/mUsLGX
