### ISSUE TITLE
Variable products can become "On Backorder" in legacy API

### ISSUE THREAD

**Issue by kepeder** [woocommerce/woocommerce#19823]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Send a POST request to /wc-api/v3/products with the following data:
`{
	"product": {
		"title": "Testproduct 1",
		"sku": "test-product-1",
		"type": "variable",
		"managing_stock": false,
		"attributes": [
			{
				"name": "Color",
				"options": "Red|Blue|Green",
				"slug": "color",
				"position": 0,
				"visible": true,
				"variation": true
			}
		],
		"variations": [
            	    {
                		"sku": "test-product-variable-1",
                		"regular_price": "140.00",
                		"managing_stock": true,
                		"stock_quantity": 0,
                		"attributes": [
                		    {
                                  "name": "Color",
                                  "slug": "color",
                                  "option": "Blue"
                		    }
                		]
            	    }  
		]
	}
}`

2. Send a PUT request to /wc-api/v3/products/XXXX (where XXXX is the id of the variable product above).
`{
	"product": {
		"title": "Testproduct 1",
		"sku": "test-product-1",
		"type": "variable",
		"managing_stock": false,
		"attributes": [
			{
				"name": "Color",
				"options": "Red|Blue|Green",
				"slug": "color",
				"position": 0,
				"visible": true,
				"variation": true
			}
		],
		"variations": [
            	    {
                		"sku": "test-product-variable-1",
                		"regular_price": "140.00",
                		"managing_stock": true,
                		"backorders": "",
                		"stock_quantity": 0,
                		"attributes": [
                		    {
                                  "name": "Color",
                                  "slug": "color",
                                  "option": "Blue"
                		    }
                		]
            	    }  
		]
	}
}`

## Expected/actual behavior

When I follow those steps, I see that after step 1 everything is fine. But after step 2, since backorders is empty and there is no validation of this value, the variable product can become "On Backorder". This status sticks until the backorder status is either changed back-and-forth to "Not allowed" or a new API call where this is set to "no".

I was expecting to see the products being out of stock.

The problem happens in file /includes/abstracts/abstract-wc-product.php:1313 where the `'no' !== $this->get_backorders()` is evaluated to `true`. I think there should be a fallback if the value is not in ["no", "notify", "yes"] where it goes to default.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: http://tripletex.utvikl.es
Site URL: http://tripletex.utvikl.es
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.8.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nb_NO

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.28-0ubuntu0.16.04.1
PHP Post Max Size: 40 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total database størrelse: 22.36MB
Database data størrelse: 16.79MB
Database indeks størrelse: 5.57MB
wp_woocommerce_sessions: Data: 0.06MB + Indeks: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Indeks: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Indeks: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Indeks: 0.03MB
wp_woocommerce_order_items: Data: 0.02MB + Indeks: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Indeks: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Indeks: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Indeks: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Indeks: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Indeks: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Indeks: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Indeks: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Indeks: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Indeks: 0.02MB
wp_commentmeta: Data: 0.02MB + Indeks: 0.03MB
wp_comments: Data: 0.02MB + Indeks: 0.09MB
wp_links: Data: 0.02MB + Indeks: 0.02MB
wp_options: Data: 1.02MB + Indeks: 0.02MB
wp_postmeta: Data: 13.05MB + Indeks: 4.03MB
wp_posts: Data: 2.14MB + Indeks: 0.70MB
wp_termmeta: Data: 0.02MB + Indeks: 0.03MB
wp_terms: Data: 0.02MB + Indeks: 0.03MB
wp_term_relationships: Data: 0.02MB + Indeks: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Indeks: 0.03MB
wp_usermeta: Data: 0.02MB + Indeks: 0.03MB
wp_users: Data: 0.02MB + Indeks: 0.05MB
wp_wc_download_log: Data: 0.02MB + Indeks: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Indeks: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Indeks: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Indeks: 0.03MB

### Post Type Counts ###

attachment: 3595
bookable_resource: 2
nav_menu_item: 5
page: 6
post: 1
product: 3
product_variation: 3
resource_booking: 10
revision: 10
shop_order: 5

### Security ###

Secure connection (HTTPS): ❌Butikken din bruker ikke HTTPS. Ler mer om HTTPS og SSL sertifikater.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: av Automattic – 3.3.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NOK (kr)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Butikkbase: #5 - /shop/
Handlekurv: #6 - /cart/
Til kassen: #7 - /checkout/
Min konto: #8 - /my-account/
Vilkår og betingelser: ❌ Side ikke satt

### Theme ###

Name: Twenty Seventeen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – Hvis du endrer WooCommerce eller et foreldertema du ikke selv har bygget
anbefaler vi å bruke et dattertema. Se: Hvordan lage et dattertema

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
"backorders" set to "" is not a valid value. API docs state it must be no, yes, or notify.

The new API validates this:

```
{
	"code": "rest_invalid_param",
	"message": "Invalid parameter(s): backorders",
	"data": {
		"status": 400,
		"params": {
			"backorders": "backorders is not one of no, notify, yes."
		}
	}
}
```

The legacy API does not. Since the legacy API is no longer maintained, we won't be patching this to include the same validation. The legacy API will be removed from WooCommerce from v4.0.0.

Thanks
