### ISSUE TITLE
Multiple Woo emails daily

### ISSUE THREAD

**Issue by nhadsall** [woocommerce/woocommerce#19827]
Woo or (some plugin related to woo) has gone crazy with the emails. Orders from months ago are being sent the same emails multiple times a day (8-10). Also, any new order is also being sent at least twice when they process. After weeks I have not been able to locate the issue.

**Comment by mikejolley** [comment]
Have you enabled deferred emails via the filter?

**Comment by nhadsall** [comment]
No, not that I am aware of. A rouge plugin might have done it, but we are
very light on plugins.

**Comment by mikejolley** [comment]
Better rule them out then :)

I only suggested the defer email filter because it's off by default, but what you describe is a symptom of it being enabled. Perhaps someone has enabled on your site to increase performance without testing it? The filter is `woocommerce_defer_transactional_emails` FWIW.

This report lacks details, system status, and system status report. Since there have been no reports of this from anyone else I must presume it's something specific on your site, such as a plugin. 

Please see the prerequisite steps on the new issue form https://github.com/woocommerce/woocommerce/issues/new for future reference.

As this issue is not reproachable I'm marking it closed.

Thanks

**Comment by nhadsall** [comment]
Mike,
I am able to confirm that no code on the site enables `woocommerce_defer_transactional_emails `. I have tried to debug this for weeks now and cannot see why these emails are firing. I installed Post SMTP and WP Control to track what is happening. I do not see anything strange in the crons, but I do see these emails going out multiple times for just some orders.

`
### WordPress Environment ###

Home URL: https://www..com
Site URL: https://www..com
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.4
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 94.61MB
Database Data Size: 81.78MB
Database Index Size: 12.83MB
wp_woocommerce_sessions: Data: 0.16MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.16MB + Index: 0.25MB
wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB
wp_woocommerce_order_itemmeta: Data: 0.52MB + Index: 0.48MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_referrals: Data: 0.05MB + Index: 0.02MB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_visits: Data: 0.16MB + Index: 0.05MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.30MB + Index: 0.44MB
wp_et_bloom_stats: Data: 42.56MB + Index: 0.00MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_gtwbundle_webinars: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.09MB + Index: 0.00MB
wp_options: Data: 2.30MB + Index: 0.06MB
wp_postmeta: Data: 14.52MB + Index: 4.88MB
wp_posts: Data: 13.41MB + Index: 0.53MB
wp_pv_commission: Data: 0.02MB + Index: 0.00MB
wp_queue: Data: 1.52MB + Index: 0.00MB
wp_redirection_404: Data: 4.02MB + Index: 4.53MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_redirection_logs: Data: 0.13MB + Index: 0.08MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.09MB + Index: 0.09MB
wp_term_relationships: Data: 0.22MB + Index: 0.13MB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB
wp_usermeta: Data: 0.45MB + Index: 0.42MB
wp_users: Data: 0.05MB + Index: 0.05MB
wp_wc_download_log: Data: 0.06MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.13MB + Index: 0.05MB
wp_yoast_seo_meta: Data: 0.19MB + Index: 0.00MB

### Post Type Counts ###

attachment: 571
custom_css: 2
et_pb_layout: 6
nav_menu_item: 14
oembed_cache: 2
page: 31
post: 193
postman_sent_mail: 250
product: 78
revision: 714
shop_coupon: 10
shop_order: 628

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

ManageWP - Worker: by ManageWP – 4.5.0
Advanced Cron Manager: by BracketSpace – 2.3.1
AffiliateWP: by AffiliateWP
LLC – 2.1.17

Anti-spam: by webvitaly – 4.4
Blogger To Wordpress: by rtCamp – 2.2.5
Bloom: by Elegant Themes – 1.2.20
Google Analytics Dashboard for WP (GADWP): by Alin Marcu – 5.3.2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.0.5
GoToWP - for GoToWebinar: by GoToWP.com – 3.0.3 – Not tested with the active version of WooCommerce
MailChimp for WooCommerce: by MailChimp – 2.1.5 – Not tested with the active version of WooCommerce
Post SMTP: by Jason Hendriks
Yehuda Hassine – 1.8.9

Redirection: by John Godley – 3.2
WooCommerce Stripe Gateway: by WooCommerce – 4.1.2
WooCommerce: by Automattic – 3.3.5
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 7.3
WP Crontrol: by John Blackbourn & contributors – 1.6.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #37 - /shop/
Cart: #38 - /cart/
Checkout: #39 - /checkout/
My account: #40 - /my-account/
Terms and conditions: #86 - /terms-of-use/

### Theme ###

Name: Sprout Studio
Version: 1.3
Author URL: http://thesproutstudio.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.2
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by nhadsall** [comment]
As I'm looking through the emails, it seems that all the duplicates are receiving payment through PayPal. Could this be related to an IPN issue of some kind? Is there a way to prevent this? I have turned on IPN logging to make sure this is the case.

**Comment by mikejolley** [comment]
I don't have any ideas on this. The emails are event based i.e. they send once when the status changes. This could I guess happen if 2 identical requests updated a status at exactly the same time but I don't know what would cause that.
