### ISSUE TITLE
Product Importer - Improper Handling of Ampersands

### ISSUE THREAD

**Issue by co50** [woocommerce/woocommerce#19830]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Import an item using the Product Importer with a "Categories" field of: Banding - Special Inventory, Banding - Special Inventory > Copper Mouldings for Hardware & Home Improvement Retailers, Banding - Special Inventory > Stainless, Decorative Metal Banding - Solid, Decorative Metal Banding - Solid > Trim Mouldings 3 To 5 Inch Wide   // (a total of 5 categories) //
2. Repeat step 1 but remove the & from the "Copper Mouldings for...." sub-category first.
3. Then, import an item with the Product Importer with a "Categories" field of:  Metal Roses & Metal Flowers.

## Expected/actual behavior

When I follow those steps, I see...

From the first set (#1 above) the category "Banding - Special Inventory > Copper Mouldings for Hardware & Home Improvement Retailers" is not assigned to the product in question and is simply ignored. However, removing the ampersand from the category results in it being assigned.

This would lead one to believe ampersands are banned from categories or require special treatment, however there is no documentation regarding special treatment of ampersands.

From the second set (#3 above), the category with the ampersand is accepted without issue, creating an inconsistency as to whether ampersands are OK.

I was expecting to see...

Categories properly assigned as listed in the CSV. CSV is formatted properly according to online documentation.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
@co50 Tested this and found no issues. This is my CSV:

[import.csv.zip](https://github.com/woocommerce/woocommerce/files/1943352/import.csv.zip)

`Copper Mouldings for Hardware & Home Improvement Retailers` imported correctly the first time, and with repeat attempts once it had been created the first run.

Just in case there was a discrepancy between imported categories and manually created categories, I created "Metal Roses & Metal Flowers" manually before trying that via CSV. This one worked also.

This leads me to believe it's not a problem with mapping of `&` ampersands, but a problem with the actual category on your site. Perhaps the & in your case has been encoded.

I'd suggest in Products > Categories, renaming "Copper Mouldings for Hardware & Home Improvement Retailers" to something else and then back to "Copper Mouldings for Hardware & Home Improvement Retailers" to ensure that ampersand has not weird encoding which would break name-based matching.

Let me know if you find something else I can test. Looks fine thus far.

Thanks

**Comment by co50** [comment]
Mike,

Thanks for the follow-up. Here's what I tried today and the results, in hopes it maybe helps you diagnose how this might occur......

1) Renamed the category "Copper Mouldings for Hardware & Home Improvement Retailers" to "Mouldings for Hardware Home Improvement Retailers", removing both a random word and the &. Then renamed it back. Made no difference. Category not assigned.
2) Did the above AND did the same to the slug this time. Made no difference. Category not assigned.
3) Deleted the category entirely from the store. Then imported with category named as it should be. This worked. Category imported and assigned to the proper items. 

Some notes:

We have never encoded the "&" into html or any other form. Maybe CSV Import Suite did this in the past behind the scenes, but we never did. My client couldn't handle that (and having to remember to escape commas will prove to be a pain for him, I'm sure). LOL

Since all categories, including those with the "&" were all put into the store by CSV Import Suite, I wonder why the other "&" example (#3 in OP) worked just fine with no deletion or finagling it. Strange.

**Comment by mikejolley** [comment]
Doesn't make much sense. Is that category name unique in the site, for both cats and other taxonomies?

**Comment by co50** [comment]
Yes, there is no other category nor presence of that category name in any other field. I'm as baffled as you are. BTW that isn't the only category with an "&" that didn't take. There were 4 or so out of probably 15 that include an "&" that didn't take. 

I wish I had the time to really investigate this and figure out exactly what scenario(s) cause this because I would but it's a crazy busy few weeks over here.

**Comment by mikejolley** [comment]
Take a look at another broken one in the DB - find the term and see how the name is stored in the DB

**Comment by zaderade** [comment]
Not sure if this is related, but I'm noticing a couple of similar issues:

1. If my product's "Attribute 1 default" column contains an ampersand: "MP3s & Transcripts" or "MP3s &amp; Transcripts", the default attribute is lost upon import. If this field does not contain an ampersand: "MP3s", the default attribute remains after importing.
2. If my "Attribute 1 value" contains any plus signs (+), those are all replaced with spaces during an export, so "Transcripts, CDs + Transcripts" becomes "Transcripts, CDs   Transcripts", with three spaces between "CDs" and the second "Transcripts". This name change of course unsets previously created variations during the next import.

Interestingly, when exporting global product attributes with ampersands, the ampersands are encoded as "&amp;" in the CSV. When exporting custom (per-product) product attributes with ampersands, the ampersands are not encoded (they appear as simply & in the CSV).

Plus signs (+) are lost (replaced with spaces) when exporting both global and custom product attributes.

3. As a quick side note, all 12 of my subscription_variation products are reported as failing during the import ("unsupported product type"), though my variable-subscription (parent) product imports successfully. I'm using the latest versions of WooCommerce (3.4.5) and Subscriptions (2.3.5). I'm unable to find a more relevant forum for this particular report.

Hope this helps.
