### ISSUE TITLE
Filter/whitelist response fields doesn't work as expected 

### ISSUE THREAD

**Issue by plainsdrifter** [woocommerce/woocommerce#19835]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use GET for orders and try to whitelist response fields like (notice attempt to whitelist nested object 'billing_address' fields): https://www.somedomain.com/wc-api/v2/orders?filter[created_at_min]=2018-04-23T08:17:11Z&filter[created_at_max]=2018-04-24T08:17:11Z&fields=id,order_number,created_at,billing_address.first_name,billing_address.last_name,billing_address.email
2. In response observe that our whitelist for nested object 'billing_address' produces only one field. Order of whitelisted fields is not important, always only last mentioned will be returned.
{"orders":[  
      {  
         "id":1624,
         "order_number":"1624",
         "created_at":"2018-04-18T09:08:46Z",
         "billing_address":{  
            "email":"someemail@test.com"
         }
      }
]}

## Expected/actual behavior

When I follow those steps, I see that in response not all whitelisted fields are returned.

I was expecting to see that when requesting to whitelist fields in nested objects, I would get those fields.

I see that API tries to provide this functionality (https://github.com/woocommerce/woocommerce/blob/46d3638089b58b51a2321b67443b83f409c6b4ec/includes/api/legacy/v2/class-wc-api-resource.php#L320), but fails, because of a problem in code, when the name of the object becomes a key in array and the value is overriden as many times as there are whitelisted fields for that object and only last remains to be whitelisted.

This is important for me, as I want to be GDPR compliant. I know I could just whitelist 'billing_address' field and be done with it, but I want to collect as little data as possible to comply with consent from user, not to mention the benefit of less bandwidth.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
I'm a third party, providing service for eshops and consuming their apis with their consent. So many versions possible.
</details>

**Comment by mikejolley** [comment]
This is a patch on the legacy API: https://github.com/woocommerce/woocommerce/pull/19838

You're using the new v2 API, not legacy. So this patch does nothing. 

Both `filter` and `fields` are not documented nor supported. There is no mention of these fields in the documentation https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-variations

`filter` was deprecated in WordPress core also.

What you would need to do is use the filters to remove fields from the response, programmatically. Supporting this via query string is pretty pointless because the requester could just adjust that to get the data they want. Locking it down requires code.

Thanks

**Comment by plainsdrifter** [comment]
I'm using **wc-api/v2/orders** (https://woocommerce.github.io/woocommerce-rest-api-docs/v2.html#view-list-of-orders), which is legacy, is it not?

So you're saying, there's no way to avoid transferring excess response data over network?

**Comment by mikejolley** [comment]
A consumer of the API doesn't need to store everything sent by the API right?

**Comment by mikejolley** [comment]
It does. But to remind you again, this is a legacy, deprecated API. Even if we rolled this out, it's getting removed in v4.0.0 so seems like wasted effort.
