### ISSUE TITLE
Admin backend search `post__in` issue (searching in custom product meta fields)

### ISSUE THREAD

**Issue by klipitkas** [woocommerce/woocommerce#19832]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Take the following code:
```
/**
 * Join posts and postmeta tables
 *
 * http://codex.wordpress.org/Plugin_API/Filter_Reference/posts_join
 */
function cf_search_join( $join ) {
    global $wpdb;

    if ( is_search() ) {
        $join .=' LEFT JOIN '.$wpdb->postmeta. ' ON '. $wpdb->posts . '.ID = ' . $wpdb->postmeta . '.post_id ';
    }

    return $join;
}
add_filter('posts_join', 'cf_search_join' );

/**
 * Modify the search query with posts_where
 *
 * http://codex.wordpress.org/Plugin_API/Filter_Reference/posts_where
 */

function cf_search_where( $where ) {
    global $wpdb;

    if ( is_search() ) {
        $where = preg_replace(
            "/\(\s*".$wpdb->posts.".post_title\s+LIKE\s*(\'[^\']+\')\s*\)/",
            "(".$wpdb->postmeta.".meta_value LIKE $1)", $where );
    }

    return $where;
}
add_filter( 'posts_where', 'cf_search_where' );

/**
 * Prevent duplicates
 *
 * http://codex.wordpress.org/Plugin_API/Filter_Reference/posts_distinct
 */
function cf_search_distinct( $where ) {
    global $wpdb;

    if ( is_search() ) {
        return "DISTINCT";
    }

    return $where;
}
add_filter( 'posts_distinct', 'cf_search_distinct' );
```
This an example code that was working before and I could use it for admins in order to search also in product meta fields. As of woocommerce 3.3.4 this functionality is broken, and I think I found the issue, which might be a general issue as well.
2. While research the main query object I found that somehow the variable 'post__in' was set as an array containing two zero values!
3. I tried to replace the code above with the following code:
```
add_action( 'pre_get_posts', function( $query ) {
if ( is_woocommerce() && is_admin() && isset($_GET['s']) ) {
    $term = sanitize_text_field( $_GET['s'] );
    $query->set( 'post__in', array());
    $query->set( 'meta_query', array(
    	'relation' => 'OR',
        array(
              'key' => 'meta_field_1',
              'value' => $term,
              'compare' => 'LIKE'
        )
  ));
}
}, 30, 3);
```
The code above works, but when I remove the part:
```
$query->set( 'post__in', array());
```
I get the array of post__in with two zero values, I am not sure why this happens, this has to do something with file ```class-wc-admin-list-table-products.php``` on line 462 - 463. 

I think it needs review.

## Expected/actual behavior

I should receive a full set of products before I continue the filtering process, and post__in should not be set by default.

## Isolating the problem

- [ x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: el

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.29
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: opt_
MaxMind GeoIP Database: ✔
Συνολικό μέγεθος βάσης δεδομένων: 23.86MB
Μέγεθος βάσης δεδομένων: 15.91MB
Μέγεθος ευρετηρίου βάσης δεδομένων: 7.95MB
opt_woocommerce_sessions: Δεδομένα: 0.44MB + Ευρετήριο: 0.02MB
opt_woocommerce_api_keys: Δεδομένα: 0.02MB + Ευρετήριο: 0.03MB
opt_woocommerce_attribute_taxonomies: Δεδομένα: 0.02MB + Ευρετήριο: 0.02MB
opt_woocommerce_downloadable_product_permissions: Δεδομένα: 0.02MB + Ευρετήριο: 0.05MB
opt_woocommerce_order_items: Δεδομένα: 0.02MB + Ευρετήριο: 0.02MB
opt_woocommerce_order_itemmeta: Δεδομένα: 0.02MB + Ευρετήριο: 0.03MB
opt_woocommerce_tax_rates: Δεδομένα: 0.02MB + Ευρετήριο: 0.06MB
opt_woocommerce_tax_rate_locations: Δεδομένα: 0.02MB + Ευρετήριο: 0.05MB
opt_woocommerce_shipping_zones: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_woocommerce_shipping_zone_locations: Δεδομένα: 0.02MB + Ευρετήριο: 0.05MB
opt_woocommerce_shipping_zone_methods: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_woocommerce_payment_tokens: Δεδομένα: 0.02MB + Ευρετήριο: 0.02MB
opt_woocommerce_payment_tokenmeta: Δεδομένα: 0.02MB + Ευρετήριο: 0.03MB
opt_woocommerce_log: Δεδομένα: 0.02MB + Ευρετήριο: 0.02MB
opt_commentmeta: Δεδομένα: 0.02MB + Ευρετήριο: 0.03MB
opt_comments: Δεδομένα: 0.02MB + Ευρετήριο: 0.09MB
opt_fpd_products: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_fpd_views: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_hplugin_root: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_links: Δεδομένα: 0.02MB + Ευρετήριο: 0.02MB
opt_options: Δεδομένα: 1.30MB + Ευρετήριο: 0.05MB
opt_postmeta: Δεδομένα: 8.52MB + Ευρετήριο: 6.03MB
opt_posts: Δεδομένα: 1.52MB + Ευρετήριο: 0.66MB
opt_revslider_css: Δεδομένα: 0.13MB + Ευρετήριο: 0.00MB
opt_revslider_layer_animations: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_revslider_navigations: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_revslider_sliders: Δεδομένα: 0.05MB + Ευρετήριο: 0.00MB
opt_revslider_slides: Δεδομένα: 0.14MB + Ευρετήριο: 0.00MB
opt_revslider_static_slides: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_soo_wishlists: Δεδομένα: 0.02MB + Ευρετήριο: 0.03MB
opt_soo_wishlists_items: Δεδομένα: 0.02MB + Ευρετήριο: 0.02MB
opt_termmeta: Δεδομένα: 0.02MB + Ευρετήριο: 0.03MB
opt_terms: Δεδομένα: 0.02MB + Ευρετήριο: 0.03MB
opt_term_relationships: Δεδομένα: 0.20MB + Ευρετήριο: 0.16MB
opt_term_taxonomy: Δεδομένα: 0.02MB + Ευρετήριο: 0.03MB
opt_usermeta: Δεδομένα: 0.05MB + Ευρετήριο: 0.03MB
opt_users: Δεδομένα: 0.02MB + Ευρετήριο: 0.05MB
opt_wc_download_log: Δεδομένα: 0.02MB + Ευρετήριο: 0.03MB
opt_wc_webhooks: Δεδομένα: 0.02MB + Ευρετήριο: 0.02MB
opt_wfBadLeechers: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfBlockedIPLog: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfBlocks: Δεδομένα: 0.02MB + Ευρετήριο: 0.02MB
opt_wfBlocksAdv: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfConfig: Δεδομένα: 1.52MB + Ευρετήριο: 0.00MB
opt_wfCrawlers: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfFileMods: Δεδομένα: 0.38MB + Ευρετήριο: 0.00MB
opt_wfHits: Δεδομένα: 0.02MB + Ευρετήριο: 0.05MB
opt_wfHoover: Δεδομένα: 0.17MB + Ευρετήριο: 0.02MB
opt_wfIssues: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfKnownFileList: Δεδομένα: 0.47MB + Ευρετήριο: 0.00MB
opt_wfLeechers: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfLockedOut: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfLocs: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfLogins: Δεδομένα: 0.02MB + Ευρετήριο: 0.03MB
opt_wfNet404s: Δεδομένα: 0.02MB + Ευρετήριο: 0.02MB
opt_wfNotifications: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfReverseCache: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfScanners: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB
opt_wfSNIPCache: Δεδομένα: 0.02MB + Ευρετήριο: 0.05MB
opt_wfStatus: Δεδομένα: 0.06MB + Ευρετήριο: 0.03MB
opt_wfThrottleLog: Δεδομένα: 0.02MB + Ευρετήριο: 0.02MB
opt_wfVulnScanners: Δεδομένα: 0.02MB + Ευρετήριο: 0.00MB

### Post Type Counts ###

acf: 1
attachment: 2371
custom_css: 1
custom-css-js: 4
customize_changeset: 5
mc4wp-form: 1
nav_menu_item: 20
page: 21
polylang_mo: 2
portfolio: 15
post: 2
product: 1280
product_variation: 1
revision: 176
shop_order: 1
vc_grid_item: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌Το κατάστημά σας δε χρησιμοποιεί HTTPS. Μάθετε περισσότερα σχετικά με το HTTPS και τα πιστοποιητικά SSL.
Hide errors from visitors: ✔

### Active Plugins (23) ###

Advanced Custom Fields: από τον/την Elliot Condon – 4.4.12
Contact Form 7: από τον/την Takayuki Miyoshi – 5.0.1
Simple Custom CSS and JS: από τον/την SilkyPres.com – 3.16
Easy Google Fonts: από τον/την Titanium Themes – 1.4.3
Eurobank Payments v2: από τον/την Konstantinos Lypitkas – 2.0.0
Google Analytics Dashboard for WP (GADWP): από τον/την Alin Marcu – 5.3.2
Google XML Sitemaps: από τον/την Arne Brachhold – 4.0.9
greeklish-permalinks: από τον/την Panagiotis Kontogiannis – 2.0
WPBakery Visual Composer: από τον/την Michael M - WPBakery.com – 5.1.1
Kirki Toolkit: από τον/την Αριστείδης Σταθόπουλος – 3.0.25
Loco Translate: από τον/την Tim Whitlock – 2.1.3
MailChimp for WordPress: από τον/την ibericode – 4.2.1
Meta Box: από τον/την MetaBox.io – 4.14.5
Slider Revolution: από τον/την ThemePunch – 5.4.5
SG Optimizer: από τον/την SiteGround – 4.0.5
Sober Addons: από τον/την UIX Themes – 1.3.9
Soo Product Filter: από τον/την SooThemes – 1.0.2 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
Soo Wishlist: από τον/την SooPlugins – 1.0.4 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
SSL Insecure Content Fixer: από τον/την WebAware – 2.5.0
WooCommerce Variation Swatches: από τον/την ThemeAlien – 1.0.3 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
WooCommerce Pay for Payment: από τον/την Karolína Vyskočilová – 2.0.7 – Δεν έχει ελεχθεί στην τελευταία ενεργή έκδοση του WooCommerce
WooCommerce: από τον/την Automattic – 3.3.5
WP Instagram Widget: από τον/την Scott Evans – 2.0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Βάση καταστήματος: #8 - /shop/
Καλάθι: #9 - /cart/
Ταμείο: #10 - /checkout/
Ο λογαριασμός μου: #11 - /my-account/
Όροι και Προϋποθέσεις: ❌ Η σελίδα δεν ορίστηκε

### Theme ###

Name: Sober Child Theme
Version: 1.0.0
Author URL: http://uix.store
Child Theme: ✔
Parent Theme Name: Sober
Parent Theme Version: 2.0.12
Parent Theme Author URL: http://uix.store
WooCommerce Support: ✔

### Templates ###

Overrides: sober-child/woocommerce/cart/cart-shipping.php έκδοση 3.1.0 είναι ληγμένο. Η βασική έκδοση είναι η 3.2.0
sober/woocommerce/cart/cart.php
sober/woocommerce/cart/mini-cart.php
sober/woocommerce/checkout/form-checkout.php
sober/woocommerce/checkout/form-coupon.php
sober/woocommerce/checkout/form-login.php
sober/woocommerce/checkout/review-order.php
sober/woocommerce/global/form-login.php
sober/woocommerce/global/quantity-input.php
sober/woocommerce/global/wrapper-end.php
sober/woocommerce/global/wrapper-start.php
sober/woocommerce/loop/add-to-cart.php
sober/woocommerce/loop/price.php
sober/woocommerce/loop/result-count.php
sober/woocommerce/myaccount/dashboard.php
sober/woocommerce/myaccount/form-edit-account.php
sober/woocommerce/myaccount/form-login.php
sober/woocommerce/myaccount/my-address.php
sober/woocommerce/notices/error.php
sober/woocommerce/notices/success.php
sober/woocommerce/order/form-tracking.php
sober/woocommerce/single-product/add-to-cart/external.php
sober/woocommerce/single-product/add-to-cart/grouped.php
sober/woocommerce/single-product/add-to-cart/simple.php
sober/woocommerce/single-product/add-to-cart/variable.php
sober/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
sober/woocommerce/single-product/product-image.php
sober/woocommerce/single-product/product-thumbnails.php
sober/woocommerce/single-product/related.php
sober/woocommerce/single-product/review-meta.php
sober/woocommerce/single-product/tabs/additional-information.php
sober/woocommerce/single-product/tabs/tabs.php
sober/woocommerce/single-product/up-sells.php
sober/woocommerce/single-product-reviews.php

Outdated Templates: ❌Μάθετε πως να κάνετε ενημέρωση
`
</details>

**Comment by mikejolley** [comment]
`post__in` is used by our search class to pass matches to the WordPress query. If you want to continue using custom code to adjust the search, you'll need to unset `post__in` OR hook into our search instead.

3.4.0 has refactored search code. I'd suggest looking there. 

https://github.com/woocommerce/woocommerce/blob/e718bdd11c41410bafea6f28f80fa4b100660c25/includes/admin/list-tables/class-wc-admin-list-table-products.php#L429-L437

If you need a filter within https://github.com/woocommerce/woocommerce/blob/006bd017cd3b7976d0bdef1f71eeb37b11423ea7/includes/data-stores/class-wc-product-data-store-cpt.php#L1345 send a PR,  but I'd review the new search behaviour first as it might already cater to your needs. The customisation you've done with meta join will cause performance issues FWIW.

Closing as this is a wontfix item - we're not reverting the search queries to support this custom snippet.

**Comment by klipitkas** [comment]
Hi @mikejolley thanks for your answer. I only posted this in order to take into account that the refactored  code might have introduced problems with other users' functionality too as these kind of snippets are quite popular. I also could not find the ``search_products`` function documented or I would have used it. 

The documentation [here](https://docs.woocommerce.com/wc-apidocs/package-WooCommerce.Classes.html) is out of date I believe.

**Comment by mikejolley** [comment]
wc-apidocs reflects 3.3 not the code I linked to in master. The above will be part of 3.4.
