### ISSUE TITLE
[Improvement] Save payment details to a temporary object on the checkout page

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#19854]
On the checkout page, the payment details are saved in checkout.js to a temporary object, so the user doesn't need to reenter them while changing the payment method. This works for inputs well. The jQuery selector is $( '.payment_box input' ).

Unfortunately, some payment method requests additional information like a date of birth, which are entered via a or several selects. The actual jQuery selector doesn't take care of them, well, because they are select tags and not Inputs. Changing the jQuery selector from $( '.payment_box input' ) to $( '.payment_box :input' ) would then also take care of the buffering of these information entered via a select. This would be great!

**Comment by claudiulodro** [comment]
Sounds reasonable. Want to submit a pull request with these changes?

**Comment by pierrebuet** [comment]
sure!
