### ISSUE TITLE
EXPLANATION OF THE ISSUE

### ISSUE THREAD

**Issue by Shentia** [woocommerce/woocommerce#19850]
I have a website about Sales Videos I have seen some bug in the related product that I insert related product in up-sells and cross-sell but after save and publishing see other product randomly 
please check this issue 
in this picture to the related product must see green packages but just seeing white!

![related](https://user-images.githubusercontent.com/19757691/39232635-2ef9ccdc-4883-11e8-9997-7239e259fd96.png)

**Comment by mikejolley** [comment]
Related products are generated from categories and tags, they are not the same as upsells/cross sells. 

Search "hide related products woocommerce". There are a bunch of solutions.

**Comment by Shentia** [comment]
Not Related to Tags
I wrote the new plugin and solve my problem :)
Thanks
