### ISSUE TITLE
WC_Coupon::get_amount can return an empty string

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#19889]
According to [the PHPDoc](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-coupon.php#L178-L187), the get_amount() function returns just float.

This is not always correct, as a coupon amount might also be an empty string. This could result in warnings on PHP 7.2 onwards, if the coupon amount is used for calculations.

Should either update the doc or ensure a float is returned every time.

**Comment by rodrigoprimo** [comment]
I could not reproduce this behavior. If I create a coupon without setting an amount and call `$coupon->get_amount()` I get `0` back instead of an empty string:

```
>>> $c = new WC_Coupon()
=> WC_Coupon {#3100}
>>> $c->get_amount()
=> 0
```

Can you please provide more details? In which circumstances `WC_Coupon::get_amount()` return an empty string? Thanks.

**Comment by glagonikas** [comment]
Hi Rodrigo,

On [this commit](https://github.com/woocommerce/woocommerce/commit/ae0f5fc76dd0ea05724aad19132820b1cab094b8#diff-8ab790c843bca7110c664000f7f0f607) from 22/2, the
[set_amount function](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-coupon.php#L483-L505) received a check to ensure the coupons have a numeric value.

This would resolve the issue for any new coupons, or coupons that are saved after this commit, but doesn't account for old ones.

Considering there are many ways a value can be set to blank (including third party plugins and legacy coupons), I believe the get_amount function, should ensure it always returns float, or at the very least, update the PHPDoc to
`* @return float|string The value of the coupon or an empty string.`

Personally, i'd update
```
public function get_amount( $context = 'view' ) {
    return $this->get_prop( 'amount', $context );
}
```
to
```
public function get_amount( $context = 'view' ) {
    $amount = $this->get_prop( 'amount', $context );

    if ( ! is_numeric( $amount ) ) {
        $amount = 0;
    }

    return $this->get_prop( 'amount', $context );
}
```

**Comment by rodrigoprimo** [comment]
Thanks for the clarification.

Your suggestion to change `WC_Coupon::get_amount()` makes sense to me but I will defer to @WPprodigy and @claudiosanches as they both worked on #19098.
