### ISSUE TITLE
I don't receive as a store owner the notifications when somebody is buying from my website

### ISSUE THREAD

**Issue by 1goldstallion1** [woocommerce/woocommerce#19883]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

I don't receive as a store owner the notifications when somebody is buying from my website

`
### WordPress Environment ###

Home URL: https://sushimaster.ro/bucuresti
Site URL: https://sushimaster.ro/bucuresti
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: ro_RO

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.29
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wpv1_
Dimensiune totală bază de date: 28.21MB
Dimensiune date bază de date: 21.69MB
Dimensiune index bază de date: 6.52MB
wpv1_woocommerce_sessions: Data: 1.78MB + Index: 0.08MB
wpv1_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wpv1_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpv1_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpv1_woocommerce_order_items: Data: 0.07MB + Index: 0.05MB
wpv1_woocommerce_order_itemmeta: Data: 0.64MB + Index: 0.49MB
wpv1_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpv1_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpv1_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpv1_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpv1_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpv1_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpv1_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpv1_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpv1_commentmeta: Data: 0.00MB + Index: 0.01MB
wpv1_comments: Data: 0.13MB + Index: 0.06MB
wpv1_email_log: Data: 0.52MB + Index: 0.00MB
wpv1_icl_content_status: Data: 0.00MB + Index: 0.00MB
wpv1_icl_core_status: Data: 0.00MB + Index: 0.00MB
wpv1_icl_flags: Data: 0.00MB + Index: 0.00MB
wpv1_icl_languages: Data: 0.00MB + Index: 0.01MB
wpv1_icl_languages_translations: Data: 0.10MB + Index: 0.10MB
wpv1_icl_locale_map: Data: 0.00MB + Index: 0.00MB
wpv1_icl_message_status: Data: 0.00MB + Index: 0.00MB
wpv1_icl_mo_files_domains: Data: 0.00MB + Index: 0.00MB
wpv1_icl_node: Data: 0.00MB + Index: 0.00MB
wpv1_icl_reminders: Data: 0.00MB + Index: 0.00MB
wpv1_icl_strings: Data: 2.69MB + Index: 2.46MB
wpv1_icl_string_packages: Data: 0.02MB + Index: 0.00MB
wpv1_icl_string_pages: Data: 0.45MB + Index: 0.56MB
wpv1_icl_string_positions: Data: 0.00MB + Index: 0.00MB
wpv1_icl_string_status: Data: 0.00MB + Index: 0.00MB
wpv1_icl_string_translations: Data: 0.00MB + Index: 0.00MB
wpv1_icl_string_urls: Data: 0.00MB + Index: 0.01MB
wpv1_icl_translate: Data: 0.20MB + Index: 0.03MB
wpv1_icl_translate_job: Data: 0.00MB + Index: 0.01MB
wpv1_icl_translations: Data: 0.04MB + Index: 0.09MB
wpv1_icl_translation_batches: Data: 0.00MB + Index: 0.00MB
wpv1_icl_translation_status: Data: 0.22MB + Index: 0.01MB
wpv1_ihc_download_monitor_limit: Data: 0.02MB + Index: 0.00MB
wpv1_ihc_security_login: Data: 0.02MB + Index: 0.00MB
wpv1_ihc_user_logs: Data: 0.02MB + Index: 0.00MB
wpv1_ihc_user_sites: Data: 0.02MB + Index: 0.00MB
wpv1_ihc_woo_products: Data: 0.02MB + Index: 0.00MB
wpv1_ihc_woo_product_level_relations: Data: 0.02MB + Index: 0.00MB
wpv1_links: Data: 0.00MB + Index: 0.00MB
wpv1_maxbuttonsv3: Data: 0.08MB + Index: 0.00MB
wpv1_maxbuttons_collections: Data: 0.02MB + Index: 0.00MB
wpv1_maxbuttons_collections_trans: Data: 0.02MB + Index: 0.00MB
wpv1_options: Data: 5.18MB + Index: 0.23MB
wpv1_postmeta: Data: 3.98MB + Index: 1.65MB
wpv1_posts: Data: 3.87MB + Index: 0.19MB
wpv1_revslider_css: Data: 0.09MB + Index: 0.00MB
wpv1_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wpv1_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wpv1_revslider_sliders: Data: 0.08MB + Index: 0.00MB
wpv1_revslider_slides: Data: 0.76MB + Index: 0.00MB
wpv1_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wpv1_smush_dir_images: Data: 0.00MB + Index: 0.00MB
wpv1_termmeta: Data: 0.00MB + Index: 0.01MB
wpv1_terms: Data: 0.00MB + Index: 0.01MB
wpv1_term_relationships: Data: 0.01MB + Index: 0.03MB
wpv1_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wpv1_usermeta: Data: 0.49MB + Index: 0.30MB
wpv1_users: Data: 0.03MB + Index: 0.04MB
wpv1_vtprd_lifetime_limits_purchaser: Data: 0.00MB + Index: 0.00MB
wpv1_vtprd_lifetime_limits_purchaser_logid_rule: Data: 0.00MB + Index: 0.00MB
wpv1_vtprd_lifetime_limits_purchaser_rule: Data: 0.00MB + Index: 0.00MB
wpv1_vtprd_purchase_log: Data: 0.00MB + Index: 0.00MB
wpv1_vtprd_purchase_log_product: Data: 0.00MB + Index: 0.00MB
wpv1_vtprd_purchase_log_product_rule: Data: 0.00MB + Index: 0.00MB
wpv1_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpv1_wc_euplatesc_trid: Data: 0.02MB + Index: 0.00MB
wpv1_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpv1_wpml_mails: Data: 0.02MB + Index: 0.00MB
wpv1_yoast_seo_links: Data: 0.01MB + Index: 0.01MB
wpv1_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB

### Post Type Counts ###

attachment: 463
br_labels: 15
custom_css: 1
customize_changeset: 1
nav_menu_item: 49
page: 54
post: 6
product: 186
revision: 397
shop_coupon: 13
shop_order: 613
vtmin-rule: 1
vtprd-rule: 1
wpcf7_contact_form: 6
yith-wcbm-badge: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

WPML Multilingual CMS: de OnTheGoSystems – 3.9.4
WooCommerce Advanced Product Labels: de BeRocket – 1.1.4
Capability Manager Enhanced: de Jordi Canals
Kevin Behrens – 1.5.8

Formular de contact 7: de Takayuki Miyoshi – 5.0.1
Custom Sidebars: de WPMU DEV – 3.1.3
Email Log: de Sudar – 2.2.5
Envato Market: de Envato – 2.0.0
Facebook for WooCommerce: de Facebook – 1.8.3 – Netestat cu versiunea activă a WooCommerce
Facebook Widget: de Milap Patel – 4.2.2
Insert Headers and Footers: de WPBeginner – 1.4.2
WPBakery Page Builder: de Michael M - WPBakery.com – 5.4.5
MaxButtons: de Max Foundry – 7.1
Meta Box: de MetaBox.io – 4.14.5
VarkTech Minimum Purchase for WooCommerce: de Vark – 1.09.82
myStickymenu: de m.r.d.a – 2.0.4
One Click Demo Import: de ProteusThemes – 2.5.0
Products Purchase Limit for WooCommerce: de Yogesh C. Pant – 1.0.0 – Netestat cu versiunea activă a WooCommerce
Q2W3 Fixed Widget: de Max Bond – 5.1.4
Slider Revolution: de ThemePunch – 5.4.6.3.1
SumoMe: de SumoMe – 1.29
W3 Total Cache: de Frederick Townes – 0.9.6
WooCommerce Euplatesc Gateway: de Zamfir Vladimir – 1.8.3 – Netestat cu versiunea activă a WooCommerce
Woo Floating Cart Lite: de XplodedThemes – 1.0.9 – Netestat cu versiunea activă a WooCommerce
Advanced Order Export For WooCommerce: de AlgolPlus – 1.5.3
WooCommerce Extended Coupon Features: de Soft79 – 2.6.2
WooCommerce Catalog Visibility Options: de Lucas Stark – 3.1.1
WooCommerce Checkout Field Editor Pro: de ThemeHiGH – 2.9.3
WooCommerce Multilingual: de OnTheGoSystems – 4.2.10
WooCommerce: de Automattic – 3.3.5
Yoast SEO: de Echipa Yoast – 7.3
WP Instagram Widget: de Scott Evans – 2.0.3
WP Mail SMTP: de WPForms – 1.2.5
WP Smush: de WPMU DEV – 2.7.8
WPML Media: de OnTheGoSystems – 2.2.3
WPML String Translation: de OnTheGoSystems – 2.7.3
WPML Translation Management: de OnTheGoSystems – 2.5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: RON (lei)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Bază magazin: #6 - /magazin/
Coș: #7 - /cos/
Finalizare: #8 - /plata/
Contul meu: #9 - /contul-meu/
Termeni și condiții: #3497 - /termeni-si-conditii/

### Theme ###

Name: Vincent - Child
Version: 1.0
Author URL: http://pixel-mafia.com/
Child Theme: ✔
Parent Theme Name: Vincent
Parent Theme Version: 9.0
Parent Theme Author URL: http://pixel-mafia.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Tema ta are un fișier woocommerce.php
nu vei putea să contramandezi șablonul personalizat woocommerce/archive-product.php deoarece woocommerce.php are prioritate față de archive-product.php. Acest lucru are ca scop prevenirea problemelor de afișare.

Overrides: vincent-child/woocommerce/emails/customer-processing-order.php
`

**Comment by claudiosanches** [comment]
This happens when the order status changes from `pending` to `processing` or `completed`.
So or you don't have any paymen gateway that change status on your store, or there is something wrong on your store stopping emails or payment gateways to change the order status.
Still this does not sound like an issue with WooCommerce, and I'm not able to reproduce this issue, since there is no steps to reproduce, probably better try some support channel:

WooCommerce.com helpdesk for premium extensions: https://woocommerce.com/contact-us/
Community support forum: https://wordpress.org/support/plugin/woocommerce
