### ISSUE TITLE
Product Importer Claims "Unable to use image "[Every parent image].jpg".

### ISSUE THREAD

**Issue by co50** [woocommerce/woocommerce#19893]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Uploaded all parent product images to /wp-content/uploads
2. Referenced proper file names in CSV (eg. GM-1224-C6.jpg).
3. Commenced Import.
4. All products fail to import due to "Unable to use image xxxx"
5. Attached are both a sample CSV that triggers the error and the referenced images
[Issue.zip](https://github.com/woocommerce/woocommerce/files/1955199/Issue.zip)

## Expected/actual behavior

When I follow those steps, I see...

Two issues:

1) All parent and simple products fail to import with log showing  "Unable to use image "xxxxxx.jpg". All images are your standard everyday JPG that open in every browser, PS, Windows Photo viewer, etc. 

2) Variations are falsely listed as products that imported correctly when they are dependent on the not-imported parents. The report at the end should make clear that NO products imported correctly.

I was expecting to see...

Products imported or accurate error message regarding failure to import.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://chariotsauto.com
Site URL: https://chariotsauto.com
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.2
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wpa4_
MaxMind GeoIP Database: ✔
Total Database Size: 14.57MB
Database Data Size: 9.69MB
Database Index Size: 4.88MB
wpa4_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wpa4_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpa4_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpa4_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpa4_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpa4_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpa4_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpa4_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpa4_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpa4_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpa4_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpa4_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpa4_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpa4_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpa4_commentmeta: Data: 0.02MB + Index: 0.03MB
wpa4_comments: Data: 0.02MB + Index: 0.09MB
wpa4_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wpa4_gf_entry: Data: 0.02MB + Index: 0.03MB
wpa4_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wpa4_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wpa4_gf_form: Data: 0.02MB + Index: 0.00MB
wpa4_gf_form_meta: Data: 0.02MB + Index: 0.00MB
wpa4_gf_form_view: Data: 0.02MB + Index: 0.03MB
wpa4_links: Data: 0.02MB + Index: 0.02MB
wpa4_options: Data: 2.41MB + Index: 0.08MB
wpa4_postmeta: Data: 5.05MB + Index: 3.53MB
wpa4_posts: Data: 0.20MB + Index: 0.06MB
wpa4_realmedialibrary: Data: 0.02MB + Index: 0.00MB
wpa4_realmedialibrary_debug: Data: 0.02MB + Index: 0.00MB
wpa4_realmedialibrary_meta: Data: 0.02MB + Index: 0.03MB
wpa4_realmedialibrary_posts: Data: 0.02MB + Index: 0.02MB
wpa4_rg_form: Data: 0.02MB + Index: 0.00MB
wpa4_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wpa4_rg_form_view: Data: 0.02MB + Index: 0.03MB
wpa4_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wpa4_rg_lead: Data: 0.02MB + Index: 0.03MB
wpa4_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wpa4_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wpa4_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wpa4_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wpa4_termmeta: Data: 0.02MB + Index: 0.03MB
wpa4_terms: Data: 0.02MB + Index: 0.03MB
wpa4_term_relationships: Data: 0.02MB + Index: 0.02MB
wpa4_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpa4_usermeta: Data: 1.02MB + Index: 0.03MB
wpa4_users: Data: 0.02MB + Index: 0.05MB
wpa4_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpa4_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpa4_woos_search_trends: Data: 0.02MB + Index: 0.02MB
wpa4_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wpa4_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB
wpa4_ywrr_email_blocklist: Data: 0.02MB + Index: 0.00MB
wpa4_ywrr_email_schedule: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 35
cs_footer: 1
cs_header: 1
cs_template: 73
nav_menu_item: 5
page: 10
post: 1
postman_sent_mail: 4
product: 2
product_variation: 6
revision: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

ManageWP - Worker: by ManageWP – 4.5.0
Gravity Forms: by rocketgenius – 2.3.0.2
Admin Menu Editor Pro: by Janis Elsts – 2.6.3
Akismet Anti-Spam: by Automattic – 4.0.3
Enable Media Replace: by ShortPixel – 3.2.5
Essential Addons for Cornerstone & Pro: by Codetic – 2.7.1
Invisible reCaptcha: by Mihai Chelaru – 1.2.1
Mobile Address Bar Changer: by Anshul Labs – 3.0
My Custom Functions: by Space X-Chimp – 4.15
Post Duplicator: by Metaphor Creations – 2.20
Post SMTP: by Jason Hendriks
Yehuda Hassine – 1.8.9

Really Simple SSL: by Rogier Lankhorst – 2.5.26
SJ Cornerstone Addon: by sandesh055 – 0.1.0
Hide SEO Bloat: by SO WP – 3.5.0
Ultimate Branding: by WPMU DEV – 1.9.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.14.4.22

WC Password Strength Settings: by Daniel Santoro – 2.0.2
Woo Search Box: by Guaven Labs – 1.9.7 – Not tested with the active version of WooCommerce
WooCommerce Email Customizer: by WooCommerce – 1.1.7
WooCommerce Stripe Gateway: by WooCommerce – 4.1.2
WooCommerce Google Analytics Pro: by SkyVerge – 1.5.0
WooCommerce FedEx Shipping: by WooCommerce – 3.4.10
WooCommerce USPS Shipping: by WooCommerce – 4.4.16 – 4.4.17 is available
WooCommerce Smart Coupons: by WooCommerce – 3.4.0 – 3.4.1 is available
WooCommerce Tab Manager: by SkyVerge – 1.9.0
WooCommerce: by Automattic – 3.3.5
Yoast SEO: by Team Yoast – 7.3
Yoast SEO: WooCommerce: by Team Yoast – 7.2 – Not tested with the active version of WooCommerce
YITH WooCommerce Advanced Reviews Premium: by YITHEMES – 1.5.2
YITH WooCommerce Best Sellers Premium: by YITHEMES – 1.1.3
YITH WooCommerce Customize My Account Page: by YITHEMES – 2.2.8
YITH WooCommerce Review Reminder Premium: by YITHEMES – 1.3.6

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #101 - /shop/
Cart: #102 - /cart/
Checkout: #103 - /checkout/
My account: #104 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Pro
Version: 2.0.4
Author URL: http://theme.co/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: pro/woocommerce/cart/cross-sells.php
pro/woocommerce/loop/loop-end.php
pro/woocommerce/loop/loop-start.php
pro/woocommerce/loop/pagination.php
pro/woocommerce/notices/error.php
pro/woocommerce/notices/notice.php
pro/woocommerce/notices/success.php
/home/cocomifk/domains/chariotsauto.com/public_html/wp-content/plugins/yith-woocommerce-advanced-reviews.premium/templates/ywar-rating.php
pro/woocommerce/single-product/related.php
pro/woocommerce/single-product/tabs/tabs.php
pro/woocommerce/single-product/up-sells.php
pro/woocommerce/single-product-reviews.php

`
```
</details>

**Comment by mikejolley** [comment]
> Images need to be pre-uploaded or available online in order to import to your store.

https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema

**Comment by co50** [comment]
They are. Just as a sidenote, we've been running many WC stores with CSV Import Suite for years. So I know the drill in terms of images needing to already be in the uploads folder before the import. So that isn't the issue. Every image is there. I double checked the file names. All perfectly match.

Side note - why would the error be "unable to use image..." rather than "cannot find image..." if an image wasn't present?

**Comment by claudiosanches** [comment]
> Side note - why would the error be "unable to use image..." rather than "cannot find image..." if an image wasn't present?

Just a standard message when is not possible do upload the image (in case is already uploaded in some other server) or unable to find into the WordPress media gallery.

Looking from the CSV that you have posted here, I can't say if there anything wrong... Maybe you are doing everything correct, of course, but still using links from somewhere and there is some kind of protection to those links, or even a plugin causing some error.
Still as I said, are not enough steps to reproduce it, not even to conclude if is an issue on WooCommerce, not to mention that this is the first time someone report something like that, so doesn't sounds like a problem on WooCommerce.

**Comment by co50** [comment]
@claudiosanches 

"but still using links from somewhere and there is some kind of protection to those links."

I don't follow what you mean here.

"or even a plugin causing some error."

I checked off that the problem occurs when ONLY WooCommerce is enabled. No other plugins are active. Def not a plugin issue....unless the plugin is WooCommerce.

"Still as I said, are not enough steps to reproduce it, not even to conclude if is an issue on WooCommerce."

What other possible steps could I have added in there to make it more reproducible for you? I included exactly what I did, included the files in question....what is missing? Please tell me so I can add whatever it is. 

"not to mention that this is the first time someone report something like that, so doesn't sounds like a problem on WooCommerce."

So you're implying that if I'm the first person to report a bug...it's not a bug? I can't even count how many times I was the "first person" to report a bug on at least 10+ different WooCommerce official plugins that were subsequently patched in updates. And I'm pretty thorough with my bug reports and testing prior to reporting them. So it's incredibly disappointing to have this report discounted as "not a bug in WooCommerce". 

@mikejolley 

I said that to imply that I know images need to be uploaded first. I wasn't implying that I'm using the same files for the importer as I did with CSV Import Suite. I attached the CSV file. It follows the importer's schema, not CSV Import Suite's.

So you're saying that the importer requires the full URL to the image? The importer doesn't look in the /uploads/ folder like CSV Import Suite does? Seems to be a step backward to require this. It's one thing if the image is external or in a different folder, but why clog up the CSV with all that redundancy?

I can say that other sites we use the importer for work just fine with only the file name, but the images had already been processed by CSV Import Suite so perhaps the filename only is OK if the image has already been attached to the product?

**Comment by claudiosanches** [comment]
> Issue resolved by adding the full URL to the image column.

Good to know, but since the start, we always say that WooCommerce importer/exported it's not the same as CSV Impoter Suite and not intend to be similar in anyway.
So this will not work like the same way, and you are free to keep using CSV Importer Suite instead if you prefer.

**Comment by claudiosanches** [comment]
> The row should not be ignored if the image can't be found. That is essentially turning a minor issue into a fatal error.

In fact, a row always should be ignored if there is any error, because this is really fatal, since a broken importer, like missing some information is very hard to debug after imported, instead of having to import it again.

We are going to improve the `Unable to use image X` message.

**Comment by co50** [comment]
@claudiosanches 

You found the problem with both your comment and the issue itself. You weren't able to reproduce my issue because you did not use the CSV I attached. You modified it by adding the full URL to the image, which solves the issue. My copy uses just the filename. The reason for this is that every WooCommerce Import tool I've ever used including WP All Import, CSV Import Suite, etc. will assume a file-name only image is in the /uploads/ folder. The built-in importer does not support this and the schema page doesn't really address it though the overview page does - apologies I did not catch that.

While I would love to keep using the CSV Import Suite, it has two catastrophic bugs that are not likely to get fixed: 1) It doesn't use CRUD and thus it can write data that causes all sorts of problems in the database, creates inventory tracking issues, etc. Caused major issues for my largest client that the built-in importer resolved. 2) When building thumbnails, part way through it crashes out with that long PHP message that I traced back to some malfunction in the thumbnail builder that isn't unique to that plugin. Built-in importer doesn't have this issue. So I'm stuck choosing between a tried and tested plugin that we paid for but that can cause major issues with larger catalogs OR a new importer that isn't quite documented as well as it should be and makes some interesting choices in data handling but doesn't pork the database. 

I do not agree at all on the choice to leave out rows with missing images. Missing images are quite easy to diagnose. Not to mention if an image is not yet available but we know what the filename will be, now we cannot add it to the file because it will cause the product to not import. Think like a customer.

**Comment by claudiosanches** [comment]
@co50 I understand that I suppose to change the images paths after I read: "Referenced proper file names in CSV (eg. GM-1224-C6.jpg).".

My mistake, sorry about it, still look this:

https://www.youtube.com/watch?v=iyzSMMeftFw

Works just fine with relative paths too.

**Comment by co50** [comment]
You are correct...kind of.....

The importer seems to be OK with just the filename if the image is already attached to WordPress (i.e. appears in the Media library).

But if the images are simply uploaded via FTP to the /uploads/ folder, no go. 

I have never attempted to upload hundreds of images at a time using the Media Library as would be required with some of my larger client's catalogs. If it works fine, then great...I guess we don't have to use FTP.

Ultimately I think this whole thread boils down to there being just a tad less documentation than might be warranted. For example, the schema docs shows full URLs for the image file examples but don't say when just the filename can be used (i.e. if the image is in the Media library) so one might assume they cannot be used at all. But you just showed me how that's possible. 

Anyway, won't take up any more of your time here. Have a great weekend, Claudio.

**Comment by claudiosanches** [comment]
It's hard because just uploading by FTP to the uploads directory doesn't register any image on WordPress, so there is no way to properly query if the image exists on WordPress, we can't suppose that the image is inside `uploads/2018/04` or `uploads/1900/04` for example. In this case where the image is not properly attached into WordPress is best to use the full path.

Anyway, thanks for reporting it, we'll improve the documentation about uploading images for products.

**Comment by co50** [comment]
Hey guys,

Sorry again. I just keep encountering issues with this importer. Maybe they are bugs, maybe it's just not documented thoroughly...but after 5 days of trying to get a 200 product catalog imported using the built in importer I'm still not there. Too many downsides to this thing so we're moving everyone back to CSV Import Suite. 

Problem is I have a catalog all out of wack now and the buttons to remove all products from WooCommerce are missing from the Tools menu....why on earth was this removed? Is there a quick way to erase everything from the store to start over fresh?

**Comment by mikejolley** [comment]
It was not removed... that's csv import suite.

**Comment by LinkTree3** [comment]
Having the same issue right now.
I managed to upload all 2175 images to the server via SSH/FTP and then I synced all of them to the Wordpress Media Library via the "Media Sync" plugin available here: https://wordpress.org/plugins/media-sync/
Then I tried to do a CSV import of 300 items out of which 178 were not imported due to this "Unable to use image" error even though the images are clearly visible and reachable inside Media Library.

I am not sure how to proceed :/

**Comment by Jnol112** [comment]
We are having the exact same issue with the images and product variations as described above.
Our media is already in the media library and the csv references the file names but we get the same error message. We have also triple checked all of the other suggested issues but still no luck.

We are going to try WP All import.

Perhaps it is an issue with the way the server is set up or some issue with WooCommerce but I think we can establish that there is definitely some bug whether that is due to compatibility with other plugins or just with WooCommerce itself.

Thank you for all the helpful conversation. I give an update if we have success.
