### ISSUE TITLE
WC_Cache_Helper::delete_version_transients can flood the cron jobs

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#19890]
If you try to disable the transient cleanup by setting woocommerce_delete_version_transients_limit to 0, the delete_version_transients function will carry on creating cron jobs each time it runs.

This will result in the cron jobs list getting flooded in a very short period of time.

Should consider refactoring this function. One solution would be to return the number of affected transients, or zero if the limit was explicitly set to that.

**Comment by rodrigoprimo** [comment]
Thanks for your contribution. I just opened a PR to fix this issue (#19894).

**Comment by glagonikas** [comment]
Hi @XedinUnknown this went live sometime in May i believe. We're also on v3.4.5 and we don't experience this issue.

Maybe check the changes exist on your client's installation and that their issues are actually caused by this issue.

The changes are here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L180-L182

**Comment by XedinUnknown** [comment]
Thanks, @glagonikas, will check. Meanwhile, [this](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L187) also looks odd. If there are a 1000 transients, and it deletes a 1000 transients, how do you figure that there's more?

**Comment by glagonikas** [comment]
The $wpdb->query should return the number of affected rows from the DELETE query.

The $affected will never be higher than the $limit, as the query uses the $limit.

The code goes with the assumption that if you deleted $limit rows, you probably have more.

**Comment by XedinUnknown** [comment]
> The code goes with the assumption that if you deleted $limit rows, you probably have more.

That is what I am pointing out: this assumption is wrong. If I tell you to delete 10 rows, and you delete 10 rows, that doesn't mean you have more rows.

**Comment by glagonikas** [comment]
Yeah, the only way round it would be to have a SELECT query somewhere to see if there are any more rows before scheduling the job, but this would run an extra query for every everyone, each time this code runs.  In an ideal world, running a DELETE query with limit, would return the number of remaining records as well as affected records, but i don't think that's possible in MySQL or $wpdb->query.

In most cases, and given the nature of this function, you'll end up having at least $limit records, so the extra cron job will have some records to delete, so i don't see much harm in this. This code only schedules one cron job anyway, no matter how many records you have remaining.

p.s. have you checked if the cron jobs fire correctly on your client's system?

**Comment by XedinUnknown** [comment]
Cron jobs in general seem to fire correctly, or at least there has been no complaint for anything unrelated to WooCommerce.

It would appear that the code will eventually schedule a number of jobs equal to at least `ceil(R/1000), where `R` is the number of records. The `DELETE` query is very fast, and does not strain the webserver or PHP. Why not simply delete all of the matching records?

**Comment by glagonikas** [comment]
If i recall correctly, this function fires multiple times during the checkout flow and caused deadlocks on our system. Those deadlocks, would prevent WC Subscriptions from being created, so we needed a quick solution.

Our solution is to set this to 0 (deactivate the function) and run the DELETE query on our own cron schedule.

If you don't use WCS, it's very likely that deadlocks won't cause any harm to your system. As deadlocks are dependent on server configuration and traffic, it's also likely that your customer will never experience them.

You can therefore set this limit to a high number and see how your system behaves.

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by glagonikas** [comment]
@XedinUnknown i came across the same issue and it seems to have broken in some scenarios.

@mikejolley added this commit back in June https://github.com/woocommerce/woocommerce/commit/17e97c2580a17af4fd70633f7fad98ea0d264142#diff-c0310299cb522d1c9add22898d47f915 which seems to ignore the woocommerce_delete_version_transients_limit filter set on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178

To resolve temporarily, you can just comment out line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147

**Comment by rodrigoprimo** [comment]
@glagonikas, could you please open a new issue describing the problem and copy me in it?

As a side note, I have started working on a PR to refactor versioned transients and hopefully fix all those issues: #21282.
