### ISSUE TITLE
attributes unified

### ISSUE THREAD

**Issue by kimmoda** [woocommerce/woocommerce#19891]
Hello , first sorry for my english…I try import products with xml using wp all import pro – woocommerce addon and then ı try many diffent method but attributes not dropdown. for example size like this ; s,m,l . not like this
s
m
l

https://prnt.sc/jali87

for example ı add screenshot . please help me.thanks

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try WooCommerce support forums: https://wordpress.org/support/plugin/woocommerce. For support regarding WP All Import please check their website to see the options they provide (http://www.wpallimport.com/).

Thanks
