### ISSUE TITLE
WooCommerce overrides Wordpress template_include

### ISSUE THREAD

**Issue by ZacharyElkins** [woocommerce/woocommerce#19904]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use Wordpress filter `template_include` to change search template
2. Function:
```
 function mrb_template_chooser($template)
{
  global $wp_query;
  $post_type = get_query_var('post_type');
  if( $wp_query->is_search && $post_type == 'product' )
  {
    return locate_template('search.php');  //  redirect to archive-search.php
  }
  return $template;
}
add_filter('template_include', 'mrb_template_chooser');
```

## Expected/actual behavior

Displays woocommerce/archive-product.php. Function should change the search template, however it does not anymore after WooComomerce 3.3

I was expecting to see search.php

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by kloon** [comment]
It is possible that your code is running before the WooCommerce code that loads the templates. I would suggest you use a later priority like 11 instead of the default to ensure your code is executed last and loads your template.

`add_filter( 'template_include', 'mrb_template_chooser', 11, 1 );`

**Comment by adampatterson** [comment]
I had the exact same issue, in my case, I used `include $tempalte` rather than `return $template`
