### ISSUE TITLE
Date and Location based Tax Rates

### ISSUE THREAD

**Issue by krugazul** [woocommerce/woocommerce#19908]
Hi Everyone

We have run into a problem with our South African stores, and stores that sell to South Africans.   Specifically regarding the Tax Rate.   For the last 21 years, SA has been paying a tax rate of VAT of 14%, on the 1st of April 2018 it changed to 15%.

I have been working on migrating a site to WooCommerce and found that orders before the 1st of April had incorrect taxes.   Because i didnt take into account the switch.   And the current tax rates don't allow date base selection of rates.

## Prerequisites

- [ ] You must have a standard tax rate of 15% set to apply for all South African orders.
- [ ] You must have orders completed before and after the 1st April 2018
- [ ] Your orders before the 1st April 2018 will need to have been generated with a 14% tax.

## Steps to reproduce the issue

Editing an Order
1. Simply set an order which was completed before the 1st of April to "on-hold" and "recalculate the totals".
2. It will use the 15% rate,  instead of the previous 14% rate and the totals end up incorrect.

Migrating / Re importing Orders

1.  Use any of the Order import tools,  when the totals are recalculated the same issue happens.

## Expected/actual behavior

We should be able to set an "end" date for a rate, this would be checked after the "location" is met.

I have managed to create a filter which captures the order object in `woocommerce_order_before_calculate_taxes` and then sets the date to 14% on `woocommerce_find_rates` if the date condition is met.   But a dynamic solution would be needed for all SA stores. 

## WordPress Environment

<details>
```
WC version: |   | 3.3.5
WP version: |   | 4.9.5
```
</details>

**Comment by kloon** [comment]
@krugazul WooCommerce will only set the tax rate when you install a new store, if you had an existing store you will need to manually update the tax rate from 14 to 15% under WooCommerce -> Settings -> Tax -> Standard Rates.

We can unfortunately not accommodate date based tax calculations for taxes, our tax rules do not work on dates but rather locale instead. I understand that it may be an awkward transition for the first month when you need to edit orders placed before the change with the new rate in place, unfortunately, for those orders you have to manually calculate taxes.

I have updated our default tax rate for South Africa when you install a new store to 15%.
