### ISSUE TITLE
404 error for product page using woocommerce with polylang

### ISSUE THREAD

**Issue by berkovka** [woocommerce/woocommerce#19905]
I am having the issue with second language product translations. The product is being shown, but the url or the product give 404 error. It is related to polylang plugin (probably adding /ru/ to the url, but I have no clue how to solve it. Any help would be highly appreciated. Here is the link to the shop page:
http://vitafon.lv/ru/veikals/ 

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. go to http://vitafon.lv/ru/veikals/
2. click on the product 
3. and 404 error shows up

## Expected/actual behavior

When I follow those steps, I see... 404 error

I was expecting to see... product page

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by kloon** [comment]
@berkovka I'd suggest you contact the developers of the polylang plugin as the issues seem to be caused by their plugin. WooCommerce unfortunately do not control URL of translated products generated by 3rd party translation plugins.
