### ISSUE TITLE
REST API - Create/Update Product Attribute 'type' issue

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#19926]
I'm using WooCommerce version 3.3.5 and doing a POST to:

 /wp-json/wc/v2/products/attributes

to create a new Product Attribute with this JSON data:

`{
	"name": "Car Models",
	"order_by": "menu_order",
	"type": "text",
	"has_archives": false,
	"slug": "car-models"
}`

but I'm getting this response:

`{
	"code": "rest_invalid_param",
	"message": "Invalid parameter(s): type",
	"data": {
		"status": 400,
		"params": {
			"type": "type is not one of select."
		}
	}
}`

According to the docs `type` can be either `select` or `text`. This could be a case of the docs needing to be updated (http://woocommerce.github.io/woocommerce-rest-api-docs/#product-attribute-properties) as I noticed in the change log for 3.3.2 this:

* Fix - Remove "Type" column on attributes table by default unless custom types are defined.

So it would appear that you can no longer set the Type column when creating/updating Product Attributes, but when you do a GET you still get this field in the response.

**Comment by mikejolley** [comment]
I've updated the API docs https://github.com/woocommerce/woocommerce-rest-api-docs/blob/master/source/includes/wp-api-v2/_product-attributes.md

Legacy `text` attributes are updated on save in WP Admin. Changing them from `text` to `select` on get could break usage if someone added the attribute type back via a filter. For that reason I don't think we can hardcode the response, so the attribute will need to either be updated via the API or WP Admin. The same thing would occur if someone added a type, and then removed it after creating some attributes. Marking that part as wontfix.

Thanks
