### ISSUE TITLE
CSV Exporter: Pending products should be exported by default.

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#19921]
Currently, the exporter will only export private, public, and draft products by default (without filter customization).

Future products are those scheduled to be public in the future, which means they are even more official than draft products. And pending products are those past the draft stage as well, just awaiting admin approval.

So it makes sense to me that we would export both of these types.

**Comment by WPprodigy** [comment]
Update:

Looks like https://github.com/woocommerce/woocommerce/commit/3f87b3e0092fc3d70cacff68d84f24525a365e5a#diff-7989c4a8c6663636f8918dcffa0960f4 did recently add support for scheduled/future products. So perhaps just need pending now.

**Comment by claudiulodro** [comment]
If we're exporting draft and future we should definitely export pending also.
