### ISSUE TITLE
CSV Importer: Add filter to make for easier category imports

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#19923]
If you are creating products that have a deep category structure, the current setup could be quite strenuous if you want all parent categories to be checked.

For example, if you want this: http://cld.wthms.co/IjhbWr, you need the following in the CSV file categories column:

```
Clothing > Hoodies > ChildHoodies1 > ChildHoodies2 > 2010, Clothing > Hoodies > ChildHoodies1, Clothing > Hoodies > ChildHoodies1 > ChildHoodies2, Clothing > Hoodies, Clothing
```

Which is quite a bit. Instead, with a small change, it could be possible to only need this to achieve the same result:

```
Clothing > Hoodies > ChildHoodies1 > ChildHoodies2 > 2010
```

I understand this can't be the default, because there has to be a way to differentiate skipping parent categories versus selecting them. But I think this would be a feasible filter here to conditionally just return true: https://github.com/woocommerce/woocommerce/blob/3b24aa9791d7e935f7e77b52691e4661c3cd6ed1/includes/import/class-wc-product-csv-importer.php#L377-L378

Another use case for needing this is if an export for another system (like Magento) populated the CSV file like the second example. Manually changing it can be quite time intensive.

**Comment by mikejolley** [comment]
Can you explain why you'd need all parent cats checked? What difference does it make when they are hierarchical?

**Comment by WPprodigy** [comment]
The main thing I can think of is that it affects product page display (the list of categories). It does't seem to ideal when it comes to archive pages and querying though ¯\\\_(ツ)\_/¯

**Comment by mikejolley** [comment]
I don't think it has much of an effect on anything :) I think it makes more sense to assign the bottom most category. This also keeps things like permalinks consistent.

As for a filter, use `woocommerce_product_importer_formatting_callbacks`. For `category_ids` you can change the core callback (`array( $this, 'parse_categories_field' )`) to a custom function which contains similar logic, with the full mapping desired.

cc @kloon
