### ISSUE TITLE
REST API order refunds 'reason' given as 'refund' by REST API

### ISSUE THREAD

**Issue by therealgilles** [woocommerce/woocommerce#19925]
The Woocommerce REST API documentation says that the refund reason field name is 'reason' when getting the refunds array when retrieving an order (see attached screenshot), but the code below puts the reason field name as 'refund' instead:

```
wp-content/plugins/woocommerce/includes/api/class-wc-rest-orders-controller.php
    // Refunds.
    $data['refunds'] = array();
    foreach ( $object->get_refunds() as $refund ) {
      $data['refunds'][] = array(
        'id'     => $refund->get_id(),
        'refund' => $refund->get_reason() ? $refund->get_reason() : '',
        'total'  => '-' . wc_format_decimal( $refund->get_amount(), $this->request['dp'] ),
      );
    }
```

Either the documentation needs to be fixed or the code.

![screen shot 2018-05-02 at 12 00 27 am](https://user-images.githubusercontent.com/18076992/39495742-f22da0da-4d9b-11e8-8508-eff63064b6c9.png)

**Comment by kloon** [comment]
@therealgilles thanks for reporting.

@claudiosanches how do you think we should proceed here? Just update the scheme? I am afraid we we update the actual response attribute it might cause issues for existing applications using the API relying on refund.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19930 cc @claudiosanches
