### ISSUE TITLE
POST New Category Error with "parent":0 

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#19924]
I'm doing a POST to:

wc/v2/products/categories

to create a new Category with this JSON data:

`{
  "description": "Jazz Music", 
  "display": "default", 
  "menu_order": 3, 
  "name": "Jazz", 
  "parent": 0, 
  "slug": "jazz"
}`

which returns this response:

`{
   "code": "woocommerce_rest_term_invalid",
   "message": "Parent resource does not exist.",
   "data": {
       "status": 404
   }
}`

If I remove `"parent": 0` it is successful, but I doesn't seem possible to create a new Category with the `parent` value set to `0`. If I do a GET after creating the Category it returns `"parent":0` in the response. I'm using WooCommerce version 3.3.5.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19929
