### ISSUE TITLE
Custom attributes used for variations are not sorted as expected

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#19939]
On the back-end it seems both attribute values and variant values are sorted by the most significant number if numerical values are used.  This also affects the sorting on the front-end as per the image here (where I want them sorted in ascending order):

https://imgur.com/9IL1leF

WooCommerce should not sort attribute/variant values on the back-end as it influences the sorting order on the front-end.

### WordPress Environment ###

WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.5
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
Total databasstorlek: 42.99MB
Datastorlek för databas: 31.95MB
Indexstorlek för databas: 11.04MB
wp_woocommerce_sessions: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_api_keys: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_attribute_taxonomies: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02 MB + Index: 0.05 MB
wp_woocommerce_order_items: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_order_itemmeta: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_tax_rates: Data: 0.02 MB + Index: 0.06 MB
wp_woocommerce_tax_rate_locations: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_shipping_zones: Data: 0.02 MB + Index: 0.00 MB
wp_woocommerce_shipping_zone_locations: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_shipping_zone_methods: Data: 0.02 MB + Index: 0.00 MB
wp_woocommerce_payment_tokens: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_payment_tokenmeta: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_log: Data: 0.02 MB + Index: 0.02 MB
wp_commentmeta: Data: 0.02 MB + Index: 0.03 MB
wp_comments: Data: 0.02 MB + Index: 0.09 MB
wp_links: Data: 0.02 MB + Index: 0.02 MB
wp_options: Data: 1.06 MB + Index: 0.13 MB
wp_postmeta: Data: 26.23 MB + Index: 7.61 MB
wp_posts: Data: 2.52 MB + Index: 1.02 MB
wp_termmeta: Data: 0.09 MB + Index: 0.11 MB
wp_terms: Data: 0.11 MB + Index: 0.13 MB
wp_term_relationships: Data: 1.19 MB + Index: 1.22 MB
wp_term_taxonomy: Data: 0.14 MB + Index: 0.17 MB
wp_usermeta: Data: 0.02 MB + Index: 0.03 MB
wp_users: Data: 0.02 MB + Index: 0.05 MB
wp_wc_download_log: Data: 0.02 MB + Index: 0.03 MB
wp_wc_webhooks: Data: 0.02 MB + Index: 0.02 MB
wp_yoast_seo_links: Data: 0.02 MB + Index: 0.02 MB
wp_yoast_seo_meta: Data: 0.17 MB + Index: 0.00 MB

### Post Type Counts ###

attachment: 3398
customize_changeset: 4
nav_menu_item: 8
page: 14
post: 2
product: 587
product_variation: 658
revision: 13
shipping_package: 5
slider: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌Din butik använder inte HTTPS. Lär dig mer om HTTPS och SSL-certifikat.
Hide errors from visitors: ✔

### Active Plugins (16) ###

Akismet Anti-Spam: av Automattic – 4.0.3
Contact Form 7: av Takayuki Miyoshi – 5.0.1
Kidz Theme Functionality: av ideapark.kz – 1.4.2
Kidz Theme Wishlist: av ideapark.kz – 1.2
Loco Translate: av Tim Whitlock – 2.1.3
Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 3.0.2
SVG Support: av Benbodhi – 2.3.15
WooCommerce Advanced Shipping Packages: av WooCommerce – 1.1.4 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Brands: av WooCommerce – 1.6.0 – 1.6.1 finns tillgänglig
WooCommerce Breadcrumb Permalinks: av Captain Theme – 1.1.1 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Stripe Gateway: av WooCommerce – 4.1.2
WooCommerce Measurement Price Calculator: av SkyVerge – 3.13.2 – 3.13.3 finns tillgänglig
WooCommerce Product CSV Import Suite: av WooCommerce – 1.10.17
WooCommerce: av Automattic – 3.3.5
Yoast SEO Premium: av Team Yoast – 6.3
Yoast SEO: WooCommerce: av Team Yoast – 6.3 – Inte testat med den aktiva versionen för WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Butikbas: #4 - /sortiment/
Varukorg: #5 - /varukorg/
Kassan: #6 - /kassan/
Mitt konto: #7 - /mitt-konto/
Allmänna villkor: #14 - /kopvillkor/

### Theme ###

Name: Kidz-Child
Version: 1.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Kidz
Parent Theme Version: 1.4.8
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: kidz/woocommerce/archive-product.php
kidz/woocommerce/cart/cart-empty.php
kidz/woocommerce/cart/cart-shipping.php
kidz/woocommerce/cart/cart-totals.php
kidz/woocommerce/cart/cart.php
kidz/woocommerce/cart/proceed-to-checkout-button.php
kidz/woocommerce/cart/shipping-calculator.php
kidz/woocommerce/checkout/form-billing.php
kidz/woocommerce/checkout/form-checkout.php
kidz/woocommerce/checkout/form-coupon.php
kidz/woocommerce/checkout/form-shipping.php
kidz/woocommerce/checkout/payment-method.php
kidz/woocommerce/checkout/payment.php
kidz/woocommerce/checkout/review-order.php
kidz/woocommerce/checkout/terms.php
kidz/woocommerce/checkout/thankyou.php
kidz/woocommerce/content-product.php
kidz/woocommerce/content-product_cat.php
kidz/woocommerce/content-single-product.php
kidz/woocommerce/global/form-login.php
kidz/woocommerce/global/sidebar.php
kidz/woocommerce/global/wrapper-end.php
kidz/woocommerce/global/wrapper-start.php
kidz/woocommerce/loop/add-to-cart.php
kidz/woocommerce/loop/loop-end.php
kidz/woocommerce/loop/orderby.php
kidz/woocommerce/loop/result-count.php
kidz/woocommerce/loop/sale-flash.php
kidz/woocommerce/myaccount/dashboard.php
kidz/woocommerce/myaccount/downloads.php
kidz/woocommerce/myaccount/form-login.php
kidz/woocommerce/myaccount/my-account.php
kidz/woocommerce/myaccount/my-address.php
kidz/woocommerce/myaccount/navigation.php
kidz/woocommerce/myaccount/orders.php
kidz/woocommerce/order/order-details-customer.php
kidz/woocommerce/product-searchform.php
kidz/woocommerce/single-product/add-to-cart/grouped.php
kidz/woocommerce/single-product/add-to-cart/variable.php
kidz/woocommerce/single-product/product-image.php
kidz/woocommerce/single-product/product-thumbnails.php
kidz/woocommerce/single-product/sale-flash.php
kidz/woocommerce/single-product/tabs/additional-information.php
kidz/woocommerce/single-product/tabs/tabs.php
kidz/woocommerce/single-product/title.php
kidz/woocommerce/single-product.php

**Comment by mikejolley** [comment]
You can control this. Products > Attributes, then edit your attribute and change this:

![attributes wordpress wordpress 2018-05-03 10-29-53](https://user-images.githubusercontent.com/90977/39569380-fabbc624-4ebc-11e8-88d4-1ab4d28a0e01.png)

Options include alphabetical, numerical sort or custom. Change that setting.
