### ISSUE TITLE
add_action used instead of add_filter for get_the_generator_html and get_the_generator_xhtml

### ISSUE THREAD

**Issue by damiencarbery** [woocommerce/woocommerce#19940]
In https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-hooks.php#L21-L22 the add_action() calls should be add_filter().

It obviously makes no difference but just reads wrong.

add_action( 'get_the_generator_html', 'wc_generator_tag', 10, 2 );
add_action( 'get_the_generator_xhtml', 'wc_generator_tag', 10, 2 ); 

should be:

add_filter( 'get_the_generator_html', 'wc_generator_tag', 10, 2 );
add_filter( 'get_the_generator_xhtml', 'wc_generator_tag', 10, 2 );

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19946/files
