### ISSUE TITLE
Condition is_account_page() returns true on checkout if not set

### ISSUE THREAD

**Issue by davdebcom** [woocommerce/woocommerce#19944]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Make sure there is no account page set in WooCommerce > Settings > Account > My account page
2. Hook into the checkout and add an if statement with is_account_page()

## Expected/actual behavior

Go to the checkout, and see that is_account_page() result is true, while you are on the checkout. Should have returned false. 

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/19947
