### ISSUE TITLE
Clarification of WC version distributed on Wordpress.org

### ISSUE THREAD

**Issue by samnazarko** [woocommerce/woocommerce#19941]
As part of our build system, we pull https://downloads.wordpress.org/plugin/woocommerce.zip and update our internal Git repo. We expect that that URLs that do not specify a version will serve the latest, stable version of a plugin, otherwise we'd be pulling from Git. 

Currently, this serves 3.4.0, which I suspect explains some of the problems we've been experiencing. This is not limited to #19677 which I suspect is probably fixed now. PayPal IPNs are broken, but this seems to stem from the fact that changing order status is broken. We can look in to this in further detail once we verify that we've successfully reverted to 3.3.5. 

Can you clarify whether you intend to make test versions available via WP's Download page? From your history (https://wordpress.org/plugins/woocommerce/advanced/) it looks like a potential packaging issue. We can hardcode and manually bump versions, but we usually expect that when we run our update scripts we're getting the latest stable version as this has been the case in the past. 

Cheers

Sam

**Comment by kloon** [comment]
Just calling woocommerce.zip will download trunk which is not always the latest stable version. As you will see from the dropdown on https://wordpress.org/plugins/woocommerce/advanced/ we also do distribute Beta and RC version via wp.org we just don't tag them as stable releases.

If you are after the most current stable release you can call this endpoint https://api.wordpress.org/plugins/info/1.0/woocommerce.json and use the download_link property in there which will contain the latest stable download link.
