### ISSUE TITLE
Adjust_price is deprecated?  What should we use instead?

### ISSUE THREAD

**Issue by Pushplaybang** [woocommerce/woocommerce#19953]
Hi There, 

I see that the adjust_price() function was deprecated in v3.0.0. but can't seem to find any docs about this, or what we should use in its place?

I am implementing a complex pricing model on a variable product (using the measurement pricing plugin) and then need to further adjust the price, adjust_price() seemed to be what I was looking for, but a little stumped now.

Cheers.

**Comment by mikejolley** [comment]
The deprecated notices tells you what to use:

```
wc_deprecated_function( 'WC_Product::adjust_price', '3.0', 'WC_Product::set_price / WC_Product::get_price' );
```

`set_price`.

**Comment by Pushplaybang** [comment]
Thanks, but `set_price` doesn't really work in the same way does it?

**Comment by mikejolley** [comment]
The same behaviour can be achieved with the getter and setter.

**Comment by Pushplaybang** [comment]
it can indeed.  So write our own adust_price function.

usage not common enough to provide the convenience in the API?

**Comment by mikejolley** [comment]
Since you're the first to bring it up since 3.0 I don't think so :)
