### ISSUE TITLE
Different gallery behavior on touch enabled laptops on single product page

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#19959]
Related to issue https://github.com/woocommerce/woocommerce/issues/19688 and PR https://github.com/woocommerce/woocommerce/pull/19954.

When on touch-enabled laptop, gallery now behaves the same as on mobile devices with smaller screen, i.e. no zoom-in icon + no detailed view effect on mouse over for the image.

**Comment by claudiulodro** [comment]
The easiest solution would be to disable zoom on touch devices *with screen width <=768px*, but then you're getting the zoom icon and mouseover features on tablets in landscape mode. I think that's better than the current situation, though. Thoughts?

**Comment by mikejolley** [comment]
Detect a touch event rather than touch support.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20002
