### ISSUE TITLE
Order discount calculation is wrong? v.3.3.3

### ISSUE THREAD

**Issue by bruno-rodrigues** [woocommerce/woocommerce#19960]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a product with value = 15.58
2. Create a coupon that applies 10% discount (discounted price is 15.58 - 1.56 = 14.02)
3. Make an order for 8 units of this product
4. Observe values

## Expected/actual behavior

When I follow those steps, I see...

Line  total is 112.18. Causing the whole price to go wrong. 

I was expecting to see...

Line total should be equals to `discounted price` times `amount` (112.16)

## What I think is wrong

It seems line WC uses 3 decimal digits to calculate discount. The line I can point now is [this](https://github.com/woocommerce/woocommerce/blob/4357feef987f5b42f260ef035b11714bf3e589b4/includes/class-wc-discounts.php#L370).

We should be able to select if the discount is going to be calculated using total or unit price as reference:

Using total:
124.64 - 12.46 = **112.18** (uses 3 decimal places for calculation) [124.64 is the qty * original price)

Using unit (discount) price: 
14.02 * 8 =  **112.16**

![screen shot 2018-05-02 at 7 00 47 pm](https://user-images.githubusercontent.com/7862345/39589210-eff8745a-4ed3-11e8-927a-1e1574448503.png)
This screenshot is from our production store.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Discount coupons work on the value of the cart, the goal here would be to calculate a coupon that equates to 10% of the subtotal, otherwise the 10% discount would seem off to the customer when they look at the cart subtotals/totals.

In order to apportion correctly to taxes are split across line items. We're not working to 3dp as you suggest, what is happening is:

115.58 * 8 = 124.641

And then the 10% is applied to that. This gives 112.4641 which rounds down to `12.464` which is the result you're seeing.

Changing discount logic is not a built in feature so if you need to apply discounts custom or in a different way it will take custom coding and won't be officially supported. Unit tests pass using the current system.

Hope this explains everything.  cc @claudiulodro

**Comment by bruno-rodrigues** [comment]
I didn't understand your math here: 
```
115.58 * 8 = 124.641
```
Base price is 15.58, times 8 = 124.64 (third decimal place). 


As for editing this myself. The only filter I could find will be deprecated 
```
if ( has_filter( 'woocommerce_get_discounted_price' ) ) {
				/**
				 * Allow plugins to filter this price like in the legacy cart class.
				 *
				 * This is legacy and should probably be deprecated in the future.
				 * $item->object is the cart item object.
				 * $this->cart is the cart object.
				 */
				$item->total = wc_add_number_precision(
					apply_filters( 'woocommerce_get_discounted_price', wc_remove_number_precision( $item->total ), $item->object, $this->cart )
				);
			}
```

I would appreciate a hook somewhere around here: 

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-discounts.php#L370

Thanks for your fast response!

**Comment by bruno-rodrigues** [comment]
What about the hooks for the sake of doing this by myself? 




Sent with Unibox
