### ISSUE TITLE
REST API - POST Product Variation with No Image

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#19964]
I'm trying to do a POST of a new Product Variation with no initial image as follows:

`{
	"attributes" : 
	[
		{
			"id" : 1,
			"name" : "color",
			"option" : "Green"
		}
	],
	"backorders" : "yes",
	"date_on_sale_from" : "",
	"date_on_sale_to" : "",
	"description" : "Green Tea Variety",
	"dimensions" : 
	{
		"height" : "1",
		"length" : "3",
		"width" : "2"
	},
	"download_expiry" : 0,
	"download_limit" : 0,
	"downloadable" : false,
	"image" : {},
	"in_stock" : true,
	"manage_stock" : false,
	"menu_order" : 0,
	"regular_price" : "3.30",
	"sale_price" : "3.05",
	"shipping_class" : "first-class",
	"sku" : "GRNTEA",
	"stock_quantity" : 3000,
	"tax_class" : "reduced-rate",
	"tax_status" : "taxable",
	"virtual" : false,
	"visible" : false,
	"weight" : "10"
}`

and I'm getting this response:

`{
  "code": "woocommerce_product_invalid_image_id", 
  "data": {
    "status": 400
  }, 
  "message": "#0 is an invalid image ID."
}
`
I'm including an empty image object and POSTing to:

wp-json/wc/v2/products/3449/variations

Is there some other format needed for an empty Product Variation image?

**Comment by rodrigoprimo** [comment]
Thanks for your report. I could reproduce the problem you described and I created a PR to fix it (#19971). If it is approved, it should be included in the next WC release.

Meanwhile, you can work around this issue by omitting `image` from your payload.
