### ISSUE TITLE
First page is being selected every time GET /products?page=?

### ISSUE THREAD

**Issue by achadee** [woocommerce/woocommerce#19965]
Hi I'm not sure if this is a duplicate, I had a good hunt through the issues

We have a customer where the first page is always being selected regardless of what we set the pagination as

for example:

products?page=1&per_page=25

and

products?page=2&per_page=25

return the same result. 

Its also only ignoring the page parameter. I tweaked the per_page and it changed the results

Just wondering, have you guys come across this before? Otherwise it would be good to start a thread incase other people run into this issue

### WordPress Environment ###

Home URL: http://www.roadsomewhere.com.au
Site URL: http://www.roadsomewhere.com.au
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.36
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
Total Database Size: 18.70MB
Database Data Size: 12.99MB
Database Index Size: 5.71MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.03MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.01MB + Index: 0.01MB
wp_ewwwio_images: Data: 2.23MB + Index: 0.74MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_linksync_laidKey: Data: 0.00MB + Index: 0.00MB
wp_linksync_log: Data: 0.70MB + Index: 0.06MB
wp_options: Data: 1.05MB + Index: 0.20MB
wp_postmeta: Data: 6.88MB + Index: 3.53MB
wp_posts: Data: 1.67MB + Index: 0.45MB
wp_social_users: Data: 0.00MB + Index: 0.00MB
wp_statistics_exclusions: Data: 0.00MB + Index: 0.00MB
wp_statistics_historical: Data: 0.00MB + Index: 0.00MB
wp_statistics_pages: Data: 0.03MB + Index: 0.09MB
wp_statistics_search: Data: 0.00MB + Index: 0.01MB
wp_statistics_useronline: Data: 0.00MB + Index: 0.00MB
wp_statistics_visit: Data: 0.00MB + Index: 0.00MB
wp_statistics_visitor: Data: 0.07MB + Index: 0.09MB
wp_termmeta: Data: 0.05MB + Index: 0.04MB
wp_terms: Data: 0.04MB + Index: 0.07MB
wp_term_relationships: Data: 0.14MB + Index: 0.33MB
wp_term_taxonomy: Data: 0.04MB + Index: 0.04MB
wp_usermeta: Data: 0.02MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.01MB + Index: 0.00MB

### Post Type Counts ###

attachment: 731
blocks: 11
custom_css: 1
customize_changeset: 45
featured_item: 8
nav_menu_item: 62
page: 86
post: 12
product: 230
product_variation: 630
revision: 516
shop_order: 13
shop_order_refund: 7
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (17) ###

WooCommerce Afterpay Gateway: by AfterPay – 1.3.1 – Not tested with the active version of WooCommerce
Contact Form 7: by Takayuki Miyoshi – 5.0.1
Disable Comments: by Samir Shah – 1.7.1
EWWW Image Optimizer: by Shane Bishop – 4.1.3
Nextend Social Login: by Nextendweb – 3.0.6
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Shortcode Pagination for WooCommerce: by James Kemp – 1.0.10 – Not tested with the active version of WooCommerce
Upload Larger Plugins: by David Anderson – 1.4.1
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.2.0
WooCommerce Print Invoice & Delivery Note: by Tyche Softwares – 4.4.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.1.8
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.5
WooCommerce: by Automattic – 3.3.5
WooSidebars: by WooThemes – 1.4.3
WP Google Analytics: by Aaron D. Campbell – 1.4.1
WP Instagram Widget: by Scott Evans – 2.0.3
WP Statistics: by Verona Labs – 12.3.6

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #62 - /shop/
Cart: #61 - /cart/
Checkout: #60 - /checkout/
My account: #59 - /my-account/
Terms and conditions: #1415 - /shipping-returns/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.5.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

**Comment by rodrigoprimo** [comment]
Hi there!

I was not able to reproduce the issue you described on a clean WooCommerce core install. GitHub is for reporting bugs and issues specific to the WooCommerce core. This is not a support portal. From the description you provided, it seems to me that you tested this issue only on a client site that has other plugins installed. Please reopen this issue if you are able to reproduce it on a clean WC core install.

For support, you could try WooCommerce support forums: https://wordpress.org/support/plugin/woocommerce.

Thanks
