### ISSUE TITLE
In stock status message on front-end missing for product variations

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#19978]
When using a product with variations, the "in stock" message on the front end vanishes upon selection of variants that are in stock (no stock management). The "in stock" message is visible on the parent before variants have been selected (the parent doesn't handle stock).

Stock related headers used when importing variants from the CSV Import Suite:
stock -> blank
stock_status -> instock
meta:_manage_stock -> no
meta:_backorders -> no

tax:product_visibility seems to have no function for individual variations that are in stock (no stock management).

### WordPress Environment ###

Home URL:
Site URL:
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.5
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
Total databasstorlek: 60.45MB
Datastorlek för databas: 40.09MB
Indexstorlek för databas: 20.36MB
wp_woocommerce_sessions: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_api_keys: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_attribute_taxonomies: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02 MB + Index: 0.05 MB
wp_woocommerce_order_items: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_order_itemmeta: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_tax_rates: Data: 0.02 MB + Index: 0.06 MB
wp_woocommerce_tax_rate_locations: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_shipping_zones: Data: 0.02 MB + Index: 0.00 MB
wp_woocommerce_shipping_zone_locations: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_shipping_zone_methods: Data: 0.02 MB + Index: 0.00 MB
wp_woocommerce_payment_tokens: Data: 0.02 MB + Index: 0.02 MB
wp_woocommerce_payment_tokenmeta: Data: 0.02 MB + Index: 0.03 MB
wp_woocommerce_log: Data: 0.02 MB + Index: 0.02 MB
wp_commentmeta: Data: 0.02 MB + Index: 0.03 MB
wp_comments: Data: 0.02 MB + Index: 0.09 MB
wp_links: Data: 0.02 MB + Index: 0.02 MB
wp_options: Data: 2.06 MB + Index: 0.41 MB
wp_postmeta: Data: 32.23 MB + Index: 15.59 MB
wp_posts: Data: 3.52 MB + Index: 2.08 MB
wp_termmeta: Data: 0.09 MB + Index: 0.11 MB
wp_terms: Data: 0.11 MB + Index: 0.13 MB
wp_term_relationships: Data: 1.19 MB + Index: 1.22 MB
wp_term_taxonomy: Data: 0.14 MB + Index: 0.17 MB
wp_usermeta: Data: 0.02 MB + Index: 0.03 MB
wp_users: Data: 0.02 MB + Index: 0.05 MB
wp_wc_download_log: Data: 0.02 MB + Index: 0.03 MB
wp_wc_webhooks: Data: 0.02 MB + Index: 0.02 MB
wp_yoast_seo_links: Data: 0.02 MB + Index: 0.02 MB
wp_yoast_seo_meta: Data: 0.31 MB + Index: 0.00 MB

### Post Type Counts ###

attachment: 3439
customize_changeset: 4
nav_menu_item: 8
page: 14
post: 2
product: 595
product_variation: 1943
revision: 14
shipping_package: 5
slider: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌Din butik använder inte HTTPS. Lär dig mer om HTTPS och SSL-certifikat.
Hide errors from visitors: ✔

### Active Plugins (17) ###

Akismet Anti-Spam: av Automattic – 4.0.3
Contact Form 7: av Takayuki Miyoshi – 5.0.1
Kidz Theme Functionality: av ideapark.kz – 1.4.2
Kidz Theme Wishlist: av ideapark.kz – 1.2
Loco Translate: av Tim Whitlock – 2.1.3
Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 3.0.2
SVG Support: av Benbodhi – 2.3.15
WooCommerce Advanced Shipping Packages: av WooCommerce – 1.1.4 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Brands: av WooCommerce – 1.6.0 – 1.6.1 finns tillgänglig
WooCommerce Breadcrumb Permalinks: av Captain Theme – 1.1.1 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Stripe Gateway: av WooCommerce – 4.1.2
WooCommerce Measurement Price Calculator: av SkyVerge – 3.13.2 – 3.13.3 finns tillgänglig
WooCommerce Product CSV Import Suite: av WooCommerce – 1.10.17
WooCommerce Sequential Order Numbers Pro: av SkyVerge – 1.12.0
WooCommerce: av Automattic – 3.3.5
Yoast SEO Premium: av Team Yoast – 6.3
Yoast SEO: WooCommerce: av Team Yoast – 6.3 – Inte testat med den aktiva versionen för WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
instock (instock)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Butikbas: #4 - /sortiment/
Varukorg: #5 - /varukorg/
Kassan: #6 - /kassan/
Mitt konto: #7 - /mitt-konto/
Allmänna villkor: #14 - /kopvillkor/

### Theme ###

Name: Kidz-Child
Version: 1.1
Author URL: http://ideapark.kz
Child Theme: ✔
Parent Theme Name: Kidz
Parent Theme Version: 1.4.8
Parent Theme Author URL: http://ideapark.kz
WooCommerce Support: ✔

### Templates ###

Overrides: kidz/woocommerce/archive-product.php
kidz/woocommerce/cart/cart-empty.php
kidz/woocommerce/cart/cart-shipping.php
kidz/woocommerce/cart/cart-totals.php
kidz/woocommerce/cart/cart.php
kidz/woocommerce/cart/proceed-to-checkout-button.php
kidz/woocommerce/cart/shipping-calculator.php
kidz/woocommerce/checkout/form-billing.php
kidz/woocommerce/checkout/form-checkout.php
kidz/woocommerce/checkout/form-coupon.php
kidz/woocommerce/checkout/form-shipping.php
kidz/woocommerce/checkout/payment-method.php
kidz/woocommerce/checkout/payment.php
kidz/woocommerce/checkout/review-order.php
kidz/woocommerce/checkout/terms.php
kidz/woocommerce/checkout/thankyou.php
kidz/woocommerce/content-product.php
kidz/woocommerce/content-product_cat.php
kidz/woocommerce/content-single-product.php
kidz/woocommerce/global/form-login.php
kidz/woocommerce/global/sidebar.php
kidz/woocommerce/global/wrapper-end.php
kidz/woocommerce/global/wrapper-start.php
kidz/woocommerce/loop/add-to-cart.php
kidz/woocommerce/loop/loop-end.php
kidz/woocommerce/loop/orderby.php
kidz/woocommerce/loop/result-count.php
kidz/woocommerce/loop/sale-flash.php
kidz/woocommerce/myaccount/dashboard.php
kidz/woocommerce/myaccount/downloads.php
kidz/woocommerce/myaccount/form-login.php
kidz/woocommerce/myaccount/my-account.php
kidz/woocommerce/myaccount/my-address.php
kidz/woocommerce/myaccount/navigation.php
kidz/woocommerce/myaccount/orders.php
kidz/woocommerce/order/order-details-customer.php
kidz/woocommerce/product-searchform.php
kidz/woocommerce/single-product/add-to-cart/grouped.php
kidz/woocommerce/single-product/add-to-cart/variable.php
kidz/woocommerce/single-product/product-image.php
kidz/woocommerce/single-product/product-thumbnails.php
kidz/woocommerce/single-product/sale-flash.php
kidz/woocommerce/single-product/tabs/additional-information.php
kidz/woocommerce/single-product/tabs/tabs.php
kidz/woocommerce/single-product/title.php
kidz/woocommerce/single-product.php

**Comment by rocketeer76** [comment]
I think something is wrong with the stock_status header. According to the documentation it can have two options: "instock" and "outofstock". Sometimes when I export products the header is onbackorder. When I import a product using "onbackorder" it looks OK in the back-end, but when I export it the stock_status header is changed to "instock" again. I've set the header backoder to "notify".

**Comment by peterfabian** [comment]
Hi, 

Do you know when this problem started? Does this happen with the default theme (2017 or Storefront) and with all the plugins deactivated (only WooCommerce active)?

@rocketeer76 is the `Add to cart` button also disappearing for you (as reported by @3rdEyeBall) or is it only text  `In stock` that disappears?

I'm afraid we need to
1. rule out plugin/theme conflicts
2. reproduce the problem on our side, thus anything more detailed would help us/give us clues what might be wrong. 

Ad the `stock_status`: yes, `onbackorder` is a valid value for this one. There is some logic in function `validate_props` (https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-product.php#L1302) that could cause the change you describe (judging by a quick look, not 100% sure about this particular product of yours).

**Comment by rocketeer76** [comment]
@peterfabian I'm only experiencing the In stock text that disappears on the front-end when selecting a variation.

I experienced the problem a couple of weeks ago when I started building a new store. I have not tried with any other theme. Will elaborate and get back to you when I have more info.

**Comment by rocketeer76** [comment]
@3rdEyeBall You might want to test with header: 
tax:product_visibility
set to "instock" when importing the CSV on the parent products.

**Comment by mikejolley** [comment]
`tax:product_visibility` is something core sets to help filter products. This doesn't need to be imported afaik, but as we're talking about **CSV Import Suite extension**, not the core CSV importer.

Quickly browsing the source I see CSV import suite has:

```
'stock_status'	=> array( 'instock', 'outofstock' ),
'backorders'	=> array( 'yes', 'no', 'notify' ),
```

So it doesn't appear to handle onbackorder correctly which I think was a more recent change.

Please post to the helpdesk so this can be looked into in more depth, and so they can keep you posted on a fix. 

cc'ing @laurendavissmith @bor0 @roykho so the extension devs are aware of a potential issue with these columns.

Closing this here as it's not part of core. The core CSV import/exporter is not affected.

Thanks

cc @peterfabian
