### ISSUE TITLE
Cart / Session data and frontend includes loaded for API requests

### ISSUE THREAD

**Issue by PabloWestphalen** [woocommerce/woocommerce#19983]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Make any request to REST API
2. Look at the execution of is_request( 'frontend' ) method defined in class-woocommerce.php

## Expected/actual behavior

When I follow those steps, I see that the method returns true.

I was expecting to see the method returning false, such that the places that call it don't have to execute unneeded and potentially expensive code on API requests (ex: loading cart and running calculate_totals)

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by PabloWestphalen** [comment]
Just noticed that cart is loaded from session in admin pages as well. **AND** in heartbeat ajax calls. I know that in my installation i certainly don't want that to happen, but fail to see if perhaps this happens for a reason. Would love some educating from you experts!

**Comment by mikejolley** [comment]
AJAX calls need to be left alone because we don't know the context of the request i.e. it may be from the theme.

REST API can probably be tweaked though, although in testing the difference was negligible.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20000
