### ISSUE TITLE
Using keyboard to submit quantity change on cart page ignores HTML5 form input validation 

### ISSUE THREAD

**Issue by NielsdeBlaauw** [woocommerce/woocommerce#19996]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Add an item to the cart.
2. On the cart page, change the quantity to a decimal value:  example: 1.3
3. With focus still in the quantity field press `enter`.

## Expected/actual behavior

When I follow those steps, I see...
No HTML 5 input field validation. After the page has processed the quantity change the number is rounded.

I was expecting to see...
An HTML 5 error which is the same as shown when `clicking` the update cart button.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

Is reproducible in the demo currently available on https://themes.woocommerce.com/storefront/cart/

**Comment by NielsdeBlaauw** [comment]
The javascript that is responsible for handling the keyboard submit is found here:

https://github.com/woocommerce/woocommerce/blob/3.3.5/assets/js/frontend/cart.js#L364-L371

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/20001
