### ISSUE TITLE
Variations not seeing attributes

### ISSUE THREAD

**Issue by jodeemason** [woocommerce/woocommerce#20003]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Attributes are entered (in this case 12 colors)
2. When I click on variations it tells me that I must first add attributes..... but they have already been added.  It worked on Friday, but as of Monday it has this issue.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by mikejolley** [comment]
Open the attributes panel.
Open an attribute.
Check the 'use for variations' checkbox.
Save attributes.

If you need help with this further, please use the helpdesk.

Thanks

**Comment by jodeemason** [comment]
OMG! LOL I can't believe I did that! Thank you!
