### ISSUE TITLE
GDPR - Approval (privacy) checkbox

### ISSUE THREAD

**Issue by MajkieS** [woocommerce/woocommerce#20015]
Hey there,

thanks for the GDPR support so far, great work!

according to GDPR, right now in woocommerce release 3.4.0-beta2 there is only text and terms page, which is all okay in case you need that data to complete and deliver the specific order (data to shipping company, accounting software).

But in case you need those also for remarketing purposes, there should be a checkbox for approval. This checkbox is not required and if it is checked it sends the approval to admin (e-mail, date, expiry). If the approval is okay, you send remarketing or conversion data via js to google. So maybe there could be a hook?

Thank you.

**Comment by mikejolley** [comment]
If you're using a plugin for marketing, it needs to take care of extra checkboxes. Core doesn't require extra boxes and should't try to cover the needs of all plugins it has no control over.

There is a hook here which is suitable for all legalese and checkboxes https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/terms.php#L24

Older example showing the possibilities https://businessbloomer.com/woocommerce-additional-acceptance-checkbox-checkout/

Conversion tracking extensions/newsletter plugins will need to take care of this aspect.

Thanks!

**Comment by MajkieS** [comment]
Okay, but what about customer accounts?
These are not necessary for running the website, so you should have approval for them. Or am I wrong?

**Comment by mikejolley** [comment]
What about them? Having an account doesn't require extra opt-ins? unless you plan on spamming those users with newsletters :p

**Comment by MajkieS** [comment]
Well, I thought that creating customer account is something above "making contract via order" and that for making order you don't need user account.

So you don't need the approval either for user account? 👍

**Comment by mikejolley** [comment]
You'd need to check with a lawyer since I'm not one, but it sounds like it would fit under your main privacy policy as a legitimate interest.

```
- Consent - the user explicitly gives their consent to a specific kind of processing of their personal data (e.g. consent to participate in market research performed by a 3rd party)
- Contractual necessity - the processing of the personal data is required to fulfill a contract (e.g. ship their order to them)
- Compliance with legal obligations - the processing of the personal data is required for legal reasons (e.g. a VAT Tax ID)
- Legitimate interests - the processing of the personal data is a legitimate, expected behavior of a business (e.g. follow up emails after they've placed their order with other products they may be interested in) 
```

**Comment by MajkieS** [comment]
Okay, thank you :-)
