### ISSUE TITLE
“Hide Featured Image” Overkill

### ISSUE THREAD

**Issue by conradjax** [woocommerce/woocommerce#20012]
I am using the “Hide Featured Image” plug-in in an effort get rid of the big empty box in the middle of my product pages where. It works. However, when I do this, it negatively affects the images in the product gallery below. To see what I mean, please refer to this page which has the featured image hidden, thereby making the gallery go wild (select options to see the mayhem): http://www.larashouseshelter.org/product/tshirt/

When the plug-in is set to “off” on the page, the product photos are coordinated properly with the color option chosen & that part works like a charm.

How can I get them to both work together?
THANKS

**Comment by mikejolley** [comment]
We don't support 3rd party plugins such as “Hide Featured Image” here. You'll need to contact the author.

Thanks

**Comment by conradjax** [comment]
I just fixed it right after I posted this.  It's like I had to breakdown & ask for it to finally click. HA
Thanks
