### ISSUE TITLE
Error VAT calculation for variable products

### ISSUE THREAD

**Issue by LucSpan** [woocommerce/woocommerce#20016]
I have exactly the same problem as described [here](https://github.com/woocommerce/woocommerce/issues/9245):
I set all prices excl. 21% VAT in the back-end, and set prices to be displayed incl. 21% VAT in the frontend. E.g. in back-end I set €147.933884 such that in front-end €179 is displayed. 

This works fine simple products but **not** for variable products. For variable products, a rounding of €147.933884 is shown on the product page, and €179 is shown in the cart. 

https://github.com/woocommerce/woocommerce/issues/9245 gives a solution which I'm not sure how to apply, as the proposed fix is to be done to a file which since then has changed.

I'm running WP 4.9.5 & Woo 3.3.5.

**Comment by mikejolley** [comment]
That issue is 3 years old and no longer applies.

Set default customer address to **shop base**. This will prevent taxes being removed if the geolocation puts a customer outside of your taxable location.

Thats in WC > Settings. It won't take effect until you visit the store with a new session.

Also note, that type of precision is not supported. You should use the same number of decimal points as your store, otherwise stick to defining prices inclusive of taxes. Thats what the setting exists for. Rounding will be applied to your entered prices and this may lead to unexpected results.

https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce may also be relevant.

Thanks

**Comment by LucSpan** [comment]
Hi Mike, 

Thank you for your fast reply.

I've set 'Default customer location' to 'shop base address', but the issue persists in a new session. 
I've also cleared the transients. 

Any other solution?

Thanks

**Comment by mikejolley** [comment]
Example product I can see?

**Comment by LucSpan** [comment]
Of course! 

[Variable product 1](https://electricnailfiles.co.uk/product/saeyang-marathon-3-champion-white-blue-pink/), [Variable product 2](https://electricnailfiles.co.uk/product/saeyang-marathon-combi-24-white-red-silver-black/)

[Simple product](https://electricnailfiles.co.uk/product/saeyang-marathon-k35/), and all the other products on the page.

**Comment by mikejolley** [comment]
Is the tax rate in the 'standard' section or elsewhere? Some screenshots of tax settings would also help.

- Also try resaving some variation prices. Not sure if these were imported or added manually
- And try a default WP theme to rule out customisations

**Comment by LucSpan** [comment]
`standard`

See the 2 screenshots of the general and standard tax settings.

<img width="1687" alt="screen shot 2018-05-09 at 12 51 45" src="https://user-images.githubusercontent.com/38860051/39811065-d732032e-5387-11e8-8b11-07091c8a8319.png">
<img width="889" alt="screen shot 2018-05-09 at 12 51 36" src="https://user-images.githubusercontent.com/38860051/39811066-d74b5f5e-5387-11e8-9ae5-4f3114b3313e.png">

**Comment by mikejolley** [comment]
Not able to replicate this. Is the variable product setup like this:

![slack - a8c 2018-05-09 13-44-43](https://user-images.githubusercontent.com/90977/39815204-2dec4164-538f-11e8-9603-549e0e79d591.png)

And do the variations have tax class set?

**Comment by LucSpan** [comment]
Variable setup is indeed like that. 

See screenshot for variation tax class setting of one of the variations. 
Tax class setting was actually set to 'same as parent' all the time. I just changed it to 'standard', but no change, the error persists. 
<img width="1095" alt="screen shot 2018-05-09 at 15 45 20" src="https://user-images.githubusercontent.com/38860051/39818065-4076af2a-53a0-11e8-9ca2-6c6dc5ecf1ca.png">

**Comment by mikejolley** [comment]
Send system status report.

Also, do all of the variations have the same cost? Does changing the cost change anything after re-saving?

**Comment by LucSpan** [comment]
Per product, the variations have the same cost. 
I already changed €147.933884 to €147 for one of the variations, but the error persists. 

See system status report. 

`
### WordPress Environment ###

Home URL: https://electricnailfiles.co.uk
Site URL: https://electricnailfiles.co.uk
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.30
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.53.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wpj4_
Total Database Size: 81.58MB
Database Data Size: 77.58MB
Database Index Size: 4.00MB
wpj4_woocommerce_sessions: Data: 53.02MB + Index: 1.02MB
wpj4_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpj4_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpj4_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpj4_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpj4_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wpj4_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpj4_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpj4_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpj4_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpj4_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpj4_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpj4_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpj4_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpj4_commentmeta: Data: 0.02MB + Index: 0.03MB
wpj4_comments: Data: 0.02MB + Index: 0.09MB
wpj4_failed_jobs: Data: 0.02MB + Index: 0.00MB
wpj4_layerslider: Data: 0.02MB + Index: 0.00MB
wpj4_layerslider_revisions: Data: 0.02MB + Index: 0.00MB
wpj4_links: Data: 0.02MB + Index: 0.02MB
wpj4_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wpj4_options: Data: 3.38MB + Index: 0.14MB
wpj4_postmeta: Data: 4.52MB + Index: 1.53MB
wpj4_posts: Data: 12.41MB + Index: 0.30MB
wpj4_queue: Data: 0.02MB + Index: 0.00MB
wpj4_revslider_css: Data: 0.13MB + Index: 0.00MB
wpj4_revslider_layer_animations: Data: 0.05MB + Index: 0.00MB
wpj4_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wpj4_revslider_sliders: Data: 0.28MB + Index: 0.00MB
wpj4_revslider_slides: Data: 2.52MB + Index: 0.00MB
wpj4_revslider_static_slides: Data: 0.03MB + Index: 0.00MB
wpj4_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wpj4_sm_sessions: Data: 0.02MB + Index: 0.02MB
wpj4_termmeta: Data: 0.06MB + Index: 0.03MB
wpj4_terms: Data: 0.02MB + Index: 0.03MB
wpj4_term_relationships: Data: 0.06MB + Index: 0.05MB
wpj4_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpj4_usermeta: Data: 0.06MB + Index: 0.03MB
wpj4_users: Data: 0.02MB + Index: 0.05MB
wpj4_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpj4_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpj4_woocommerce_multisafepay: Data: 0.02MB + Index: 0.00MB
wpj4_yikes_easy_mc_forms: Data: 0.02MB + Index: 0.00MB
wpj4_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wpj4_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wpj4_yoast_seo_links: Data: 0.28MB + Index: 0.16MB
wpj4_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB

### Post Type Counts ###

attachment: 698
cms_block: 24
custom_css: 1
customize_changeset: 1
mc4wp-form: 1
nav_menu_item: 50
page: 28
portfolio: 9
post: 11
product: 68
product_variation: 7
revision: 815
shop_coupon: 3
shop_order: 24
thegem_client: 5
thegem_footer: 1
thegem_team_person: 4
woodmart_sidebar: 1
woodmart_size_guide: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Redux Framework: by Team Redux – 3.6.9
CMB2: by CMB2 team – 2.3.0
Contact Form 7: by Takayuki Miyoshi – 5.0.1
Duplicate Post: by Enrico Battocchi – 3.2.2
e-Boekhouden.nl: by e-Boekhouden.nl – 1.9.3
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
Facebook for WooCommerce: by Facebook – 1.8.7
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.7
MailChimp for WooCommerce: by MailChimp – 2.1.5 – Not tested with the active version of WooCommerce
MailChimp for WordPress: by ibericode – 4.2.1
MailChimp for WordPress - Top Bar: by ibericode – 1.3
Product CSV Import Export (BASIC): by XAdapter – 1.4.4
Slider Revolution: by ThemePunch – 5.4.7.2
SG Optimizer: by SiteGround – 4.0.5
TinyMCE Advanced: by Andrew Ozz – 4.6.7
WooCommerce Currency Switcher: by realmag777 – 1.2.4
WooCommerce Stripe Gateway: by WooCommerce – 4.1.3
WooCommerce AdWords Conversion Tracking: by Wolf+Bär Agency – 1.4.7 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by WooThemes / SkyVerge – 1.1.2 – 1.5.0 is available – Not tested with the active version of WooCommerce
WooCommerce MyParcel: by Richard Perdaan – 2.5.2 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooThemes – 2.7.20 – 2.9.3 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.5
Woodmart Core: by  – 1.0.7
Yoast SEO: by Team Yoast – 7.4.2
Wordpress Page Widgets: by CodeAndMore – 3.5
WP Smush: by WPMU DEV – 2.7.8
Easy Forms for MailChimp: by YIKES
Inc. – 6.4.1

YITH WooCommerce Compare: by YITHEMES – 2.3.0
YITH WooCommerce Wishlist: by YITHEMES – 2.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: #145 - /terms-conditions/

### Theme ###

Name: Woodmart
Version: 2.1.0
Author URL: http://themeforest.net/user/xtemos
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-product_cat.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/myaccount/navigation.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product.php

`

**Comment by mikejolley** [comment]
Hmm some of those I could see manipulating price. If this is a dev site, turn everything else by WC off, resave (again) and see whats shown.

I'm unable to replicate the issue on a clean install.

**Comment by madmath03** [comment]
@LucSpan Hi,

Just curious, has the issue described here been fixed, and if so, how did you fix it ?
