### ISSUE TITLE
Woocommerce price filter doesn't work with Variable products

### ISSUE THREAD

**Issue by starconfig** [woocommerce/woocommerce#20013]
**Describe the bug**
Hi I saw there is similar question here but there is no answer,

I'm using WordPress Version 4.9.5 and Woocommerce Version 3.3.5

WooCommerce price filter widget in my sidebar. When I use that widget to filter products using price, the filtered results also include some products with the higher price than selected.

Say, I have selected the price range from 0 to 200, then when filtered, the results show me the products having price of 250, 300 etc.

When I have selected the price range from 1-200 then results is in that range.

Also Order BY Price Doesn't work well

This happened after I've updated website to 3.2 ver

You can have a look example

https://www.copy.pushorpull.com.au/product-category/designer-pull-door-handles/

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
4.9.5
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
3.3.5
</details>

**Comment by mikejolley** [comment]
`?min_price=1&max_price=215` does not have the issue. This tells me the affected products may have some hidden 0 priced variations within them which is throwing off the filter. Take a look.

**Comment by starconfig** [comment]
Hi Mike, 

Thanks for your answer, I've got over 1000 product variations, what's the easiest way to look up price in database?

Thanks

**Comment by mikejolley** [comment]
@starconfig Find anything?

If the variations inside a variable product look ok, try editing a variation and saving. The _price meta data may simply be out of sync.

**Comment by starconfig** [comment]
Hi Mike,

I'm in Australia :) and just started this morning to follow up your instructions, 

Price is fine in product variations but every product which has price for example 

690.00

is affected, what I done I removed 00 and saved as 690

and then products doesn't showing in that price range,

But as I said I've got over 1000 products

What's the easiest way to remove .00 from product variations price?

Thank you very much for your help.

**Comment by starconfig** [comment]
I found that is not problem with price 690.00 even that's happened with product which has price 690

The only way is to change data in product variations and then Save / Update product

I'm not sure is there any batch script or something similar to done this automatically?

Thanks

**Comment by starconfig** [comment]
I've used Woocommerce Standard Bulk Edit Tool to update products and it works. 

Thanks again 

Maybe someone with similar issue can help these comments to resolve error.
