### ISSUE TITLE
Grouped product loop creates infinite loop on frontend when loading the product

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#20014]
**Describe the bug**
It's possible to create a grouped product loop where each grouped product links to the other. This doesn't cause any warnings or errors on the backend. But as soon as this product is loaded on the frontend it causes an infinite loop.
This is a bit of an edge case and can be prevented by just not creating a product like this. However it might be worth it to prevent this kind of configuration, in case they made a mistake or misunderstood how grouped product work.

One possible solution would be to warn the user when saving the product and prevent it from allowing a loop.

**To Reproduce**
1. Create a Grouped Product A
2. Create a Grouped Product B
3. Link Product A to B
4. Link Product B to A
5. Load the shop page / product page containing one of these products

**Expected behavior**
A warning or notice that this shouldn't be possible. Or a failure message that the product can't be loaded instead of an infinite loop.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WordPress 4.9.5
WooCommerce 3.3.5
Storefront 2.3.0
```

</details>

**Comment by kloon** [comment]
Confirmed bug, should not be able to select a grouped product that is already containing the current grouped product you are setting up.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20020
