### ISSUE TITLE
OBW: Only offer PayPal and PPEC gateways if selected currency is supported

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce#20025]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. On "Store Setup" step of the setup wizard, select a currency not supported by PayPal (such as "Vietnamese đồng")
2. Select PayPal Express Checkout (or PayPal Standard if "install_plugins" capability is missing) offered on "Payment" step
3. Payment attempts with PayPal Express Checkout will fail (or enabling PayPal Standard will not work)

## Expected/actual behavior

If the currency is not supported by PayPal, we shouldn't offer PayPal options to the merchant at all. Or if we do, we should ensure they are disabled by default and maybe display a warning. (Some discussion in p7bbVw-2oQ-p2.)

The PayPal gateway's [`is_valid_for_use`](https://github.com/woocommerce/woocommerce/blob/4e046f2afefb084b46879344e531c1f6ae593d1e/includes/gateways/paypal/class-wc-gateway-paypal.php#L246-L260) function could be used to define a `$can_paypal` condition in [the OBW code](https://github.com/woocommerce/woocommerce/blob/217fe4bd6954dfc9ceb87968fd176a02a57602eb/includes/admin/class-wc-admin-setup-wizard.php#L1332-L1397), although it should perhaps be made `static` to avoid instantiation as it isn't a function of the instance anyway. Generally speaking (with a few exceptions we shouldn't need to worry about), Standard and Express Checkout support the same set of currencies.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20244
