### ISSUE TITLE
Variations acting odd when there are > 30

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce#20029]
## **Description**

There is an issue that affects both variable products and (in my case) variable subscription products. I believed these to be connected and have verified that they are.

What happens is that when a variable product has less than or equal to 30 variations, everything works as expected. The attribute dropdowns on the product page only show what is actually available, based off of the created variation.
When a variable product has greater than 30 variations, the attribute dropdowns on the product page show all attributes regardless of if they are available or not. Choosing a variation that is not available causes the page to display the following: http://nimb.ws/4sJTil

If this is expected, I'd be happy to let the customer know!

## **To Reproduce**

1. Create a variable product with at least 32 variations.
2. Now, delete one of those variations and save the product. (you should now have 31. this isn't required, but is the easiest way to see the difference)
3. Navigate to the product page and notice that the deleted variation is still in the dropdowns.
4. Go back to the product edit page.
5. Delete another variation. (you should now only have 30)
6. Save the product.
7. Navigate back to the product page and notice that the variations are no longer showing that are not available.

This doesn't seem to be an orphaned variations, caching, or transients issue (not that it would be).

## **Expected behavior**

It would be expected that only those variations that are available would display in the attributes dropdown. 
For example:
- A shoe is for sale.
- One option is the color brown in a 9.5.
- The store no longer sells this option, so they delete it's variation.
- The dropdowns should no longer show 9.5 when the color brown is shown.

While this seems to work perfectly for variation amounts not exceeding 30, anything 31 and over messes it all up.

## **Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rocketeer76** [comment]
Yes! I faced the same problem last week. @mikejolley answered my issue here:
https://github.com/woocommerce/woocommerce/issues/19977

**Comment by mikejolley** [comment]
See that issue ^ and the threshold snippet inside.
