### ISSUE TITLE
Getting an error message on my site after installing not sure what to do

### ISSUE THREAD

**Issue by modlphoto** [woocommerce/woocommerce#20027]
**Describe the bug**
Getting this error message on my website after installation of woocommerce:
Notice: WC_Cart::get_cart_url is deprecated since version 2.5! Use wc_get_cart_url instead. in /home/modlphotography/public_html/wp-includes/functions.php on line 3839

**To Reproduce**
1. Go to 'modlphotography.com'
2. This appears at the top of every page
3. Scroll to top of page
4. See error at the top of page

**Screenshots**

**Expected behavior**
I thought there wouldn't be any error

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment]
This is a warning coming from an extension/theme you have installed. See https://github.com/woocommerce/woocommerce/wiki/Deprecation-in-core#what-happens-when-a-deprecated-function-is-called
