### ISSUE TITLE
$product->is_on_sale() returning False, even when condition is True

### ISSUE THREAD

**Issue by danielmoorehbd** [woocommerce/woocommerce#20038]
**Describe the bug**
When calling a `$product->is_on_sale()` in functions.php, it just returns `false` even when it should be returning `true`...

**To Reproduce**
To diagnose this, I created an echo:
`function for_signed_out_customers() {
  global $product;
if ( $product->is_on_sale() ) {
  $weonsale = 'true';
} else {
  $weonsale = 'false';
}
if ( !is_user_logged_in() ){
  echo $weonsale;
} else {
  echo '';
}}
add_action( 'woocommerce_before_add_to_cart_form', 'for_signed_out_customers', 31 );`

I then tried this before my function, and still get the issue:
`function is_on_sale() {
   return isset( $this->sale_price ) && $this->sale_price == $this->price ? true : false;
  }`

**Expected behavior**
It was expected that is a product has a sale price, my function would be returning "True", but for some reason, it permenatley returns "False".

Some thoughts on this:
- Could this be becasue of Variable products?
--- We're not sure if `$product->is_on_sale()` is exclusive to simple products? Or if it requres ALL variations in variable products to be on sale (rather than just one or two for example), we can't seem to find any documentation on that though so would be good to see what comes back on that point.

**Comment by mikejolley** [comment]
I think there is a problem with your debug code.. `woocommerce_before_add_to_cart_form` how do you know the product you're targeting there is the one you need to test?

> Could this be becasue of Variable products?

`$product->is_on_sale()` returns true for variable products if any of the child variations are on sale. 

Your second code snippet does not cover this logic. 

A better test would simply be to run this in your theme somewhere:

```
$product = wc_get_product( 123 );
var_dump( $product->is_on_sale() );
```

Give it a variable product ID.

I've confirmed this is working, and also that products get the 'sale' banner which also relies on this method.
