### ISSUE TITLE
Add Payment Method page not showing form to add payment method.

### ISSUE THREAD

**Issue by safeerahmed555** [woocommerce/woocommerce#20049]
Hi,

Add Payment Method page was working fine with my old plugins (woocommerce 3.1.0 & WP version 4.8.6) like screenshot https://prnt.sc/jgs1ln and recently I upgraded plugins and theme (storefront) on staging environment and now Add Payment Method page (My Account -> Pyament Methods -> Add Payment method) doesn't show form to add payment method. It shows "New payment methods can only be added during checkout. Please contact us if you require assistance." like screenshot https://prnt.sc/jgs47q

I'm using Woocommerce Subscriptions, Woocommerge Gateway Stripe plugins also and only stripe payment method enabled.

One more point to note that if I view a active subscription and click on change payment method, it works fine like screenshot https://prnt.sc/jgs6kv .

At checkout page, I can pay with credit card fine. so payment method stripe is also enabled.

Can you please let me know why it don't allow to customer for adding a payment method?
is any settings issue? I even tried with uploading old woocommerce plugin of 3.1.0 but it still don't show form to add payment method.
Please let me know how can I enable add payment method functionality at url like www.mydomain.com/my-account/add-payment-method/   ?

**Comment by mikejolley** [comment]
Please contact the helpdesk as this is a Stripe issue and may be a limitation of Stripe. Some payment gateways cannot add tokens unless you're taking a payment. On that page no payment is being made. For subs however, an authorization IS being made.

Thanks
