### ISSUE TITLE
Tooltips misaligned for some extensions

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce#20044]
During discussion on our triage meeting, @roykho discovered that some extensions have misaligned tooltip icon:
https://cld.wthms.co/1aXZ2u
https://cld.wthms.co/CWxMEw

The code that's used adds a custom button but using core settings API:
https://cld.wthms.co/dGSCTm

Commit related: https://github.com/woocommerce/woocommerce/commit/d8814f93819a41a64f9f6571542488de8db65dab

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20084
