### ISSUE TITLE
Error when updating status of auto-draft order

### ISSUE THREAD

**Issue by benignant** [woocommerce/woocommerce#20057]
**Describe the bug**
Attempting to update the status of an auto-draft order will result in an error. This error is just the first in a series of three fatal errors that would occur if the script didn't die after the first. You can comment out each offending line to get to the next one.

Here are links to each problematic line:

- [Line 142 of _/includes/data-stores/abstract-wc-order-data-store-cpt.php_](https://github.com/woocommerce/woocommerce/blob/3.3.5/includes/data-stores/abstract-wc-order-data-store-cpt.php#L142)
- [Line 143 of _/includes/data-stores/abstract-wc-order-data-store-cpt.php_](https://github.com/woocommerce/woocommerce/blob/3.3.5/includes/data-stores/abstract-wc-order-data-store-cpt.php#L143)
- [Line 36 of _/templates/emails/email-order-details.php_](https://github.com/woocommerce/woocommerce/blob/3.3.5/templates/emails/email-order-details.php#L36)

The problem is that `get_date_created()` can return `null`. One way to fix this would be to initialize that property before doing anything else. Another way would be to make that method return a default instead of `null`.

**To Reproduce**
1. Open the **Add new order** page.
2. Note the order ID.
3. Run the following code:
```php
$order = wc_get_order( /* ID of auto-draft order */ );
$order->update_status( 'on-hold' );
```
4. Check the error log to see the following error:
```
Uncaught Error: Call to a member function getOffsetTimestamp() on null in path\to\wordpress\wp-content\plugins\woocommerce\includes\data-stores\abstract-wc-order-data-store-cpt.php:142
```

**Isolating the problem**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
> Another way would be to make that method return a default instead of null

That would be breaking and cause places to display 1980 or whatever default dates. Null is correct.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20085
