### ISSUE TITLE
REST API - Not Deleting Meta Data on Customer Update

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#20053]
I have a Customer record which has some existing Meta Data which I can see when doing a GET for the customer:

`"meta_data" : 
	[
		{
			"id" : 211,
			"key" : "Sponsor",
			"value" : "Business"
		}
	],`

I then do a PUT request to update the customer and include an empty meta_data array:

`"meta_data" : [],`

however in the response the existing Meta Data that I was trying to delete is still present:

`"meta_data" : 
	[
		{
			"id" : 211,
			"key" : "Sponsor",
			"value" : "Business"
		}
	],`

I'm using WooCommerce Version 3.3.5 and the REST API v2.

**Comment by mikejolley** [comment]
Pass the IDs and null to clear specific values. https://github.com/woocommerce/woocommerce/issues/16338#issuecomment-320643784
