### ISSUE TITLE
FOUC on checkout page for payment methods when user logged in

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#20054]
This issue/bug is not vital but could be handled better.

When user are logged in and one payment method have a payment token returning a default token - like stripe -, this method is always pre-selected, no matter wich selected payment method is present in the session (function set_current_gateway in the class WC_Payment_Gateways).

As consequence for logged-in users, each ajax call to update the checkout is returning this "token payment method" as selected, since the function set_current_gateway is also called during ajax. The fragments get replaced with this "token payment method" always as selected in the HTML markup and only later checkout.js is reselecting the payment method wich was actually selected before making the ajax call. The glitch doesn't occur for non-logged-in users, since set_current_gateway then check for WC()->session->get( 'chosen_payment_method' ) wich contains the payment method selected before the ajax call: The fragments get directly replaced with the same selected payment method as before the update ajax call and no glitch happens.

More generally and from the user point of view, I see an issue but I'm not sure if it's a design flaw or an error from my side:
If a payment gateway uses token (like stripe), the payment gateway will always "win" over a payment gateway using no token (like paypal). So if a logged-in customer enter once a credit card to pay over stripe, this gateway will always be preselected and under my account, the customer can only set a default payment method but only for the one using a payment token. In other words, he has no possibility there to set PayPal as a standard for latter payments, for example. I think the customer should either be able to set a default gateway under my account, wich can also be not token based (like paypal) or he should be presented with the last payment gateway he used on checkout.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20125
