### ISSUE TITLE
Duplicate Variable Product - post_date not changing

### ISSUE THREAD

**Issue by buggles333** [woocommerce/woocommerce#20058]
When duplicating a variable product, the variation post_date and post_date_gmt are not modified in the duplicate product

1. Go to Products View
2. Click 'Duplicate' on a variable product
3. Look up the product varations in the wp_posts table
4. See post_date and post_date_gmt are the same

I assume this is unintended, it feels like it should modify the values to reflect a new timestamp.

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WC version:  3.3.5
WP version: 4.9.5
PHP version: 5.6.36
Server: Litespeed
</details>

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/20083
