### ISSUE TITLE
RTL language causes email formatting issues 

### ISSUE THREAD

**Issue by eraroma** [woocommerce/woocommerce#20050]
[x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
[x ] The issue still exists against the latest master branch of WooCommerce on Github (this is not the same version as on WordPress.org!)
[x ] I have attempted to find the simplest possible steps to reproduce the issue
Steps to reproduce the issue
Site language is set to a RTL language - (he_IL specifically)
Send an order email
Expected/actual behavior
When I follow those steps, I see an email that is formatted poorly in the Android IMAP gmail app.
see screen shot

I was expecting to see an email that is formatted like it is in English
see screen shot

Isolating the problem
[ x] This bug happens with only WooCommerce plugin active
[ x] This bug happens with a default WordPress theme active, or Storefront
[x ] I can reproduce this bug consistently using the steps above
FWIW I ran the generated HTML through Litmus and there are some links to the test cases in ticket: 867507-zen

**Comment by mikejolley** [comment]
Please see https://github.com/woocommerce/woocommerce/issues/18326 this is a gmail issue we are currently unable to workaround.

**Comment by mikejolley** [comment]
cc @claudiulodro @peterfabian
