### ISSUE TITLE
[3.4] Importing products deletes taxonomy relationships

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#20051]
**Describe the bug**
90c5cf67fafdeb753065b17d82c714ecc9ba5fc7 introduced these lines https://github.com/woocommerce/woocommerce/blob/3.4.0-rc.1/includes/admin/class-wc-admin-importers.php#L261-L265 which delete all taxonomy relationships with an object_id not  present in the posts table. However a few plugins are using taxonomies for other types of objects than posts. For example, BuddyPress uses taxonomies for users, Polylang uses taxonomies for taxonomy terms. This database query can potentially delete all these relationships.  

**To Reproduce**
Start from a fresh install.
1. Activate Polylang and WooCommerce.
2. Go to Languages and add at least 1 language
3. On top of the screen, there is a notice: click on the link "You can set them all to the default language"
4. Go to Posts > Categories and Add 3 categories (note that there is checkbox in the language column, see 1st screenshot).
5. Import a single product
6. Go to Posts > Categories. The language has disappeared for the 3 categories created above (see 2nd screenshot).

**Screenshots**
_Before the product import_
![before-import](https://user-images.githubusercontent.com/3238583/39959392-18735ad2-5611-11e8-8acb-dc719e5e30ef.png)

_After the product import_
![after-import](https://user-images.githubusercontent.com/3238583/39959393-1c495968-5611-11e8-9105-7a80604bdf66.png)

**Expected behavior**
WooCommerce should not delete taxonomy relationships for non WooCommerce taxonomies.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20094
