### ISSUE TITLE
Allow Stock Quantity Editing within the Stock Report

### ISSUE THREAD

**Issue by RyanHartje** [woocommerce/woocommerce#20068]
**Is your feature request related to a problem? Please describe.**
I have clients with large numbers of product variations. It is hard for them to bulk update quantities for their products after purchasing. Most have had a prior solution where the stock report page also allows them to AJAX post a quantity update so they never need to leave the page.

**Describe the solution you'd like**
Can someone implement a solution where the product (or variation) quantity can be updated from WooCommerce's Stock Report? 

I would also welcome help getting started with how to do this myself, but I'm not very familiar with WooCommerce and it's patterns. 

**Describe alternatives you've considered**
I could not find an existing plugin to satisfy this request. 

**Additional context**

**Comment by mikejolley** [comment]
I'm not sure the report is a good for for this. There is an extension however https://woocommerce.com/products/bulk-stock-management/ and lots of others from 3rd parties which allow the same thing.

Alliteratively, for very very large inventories CSVs might be suitable and can be merged.

Hope that helps.
