### ISSUE TITLE
After updating website into PHP 7 we didn't get order confirmed screen 

### ISSUE THREAD

**Issue by sarun007** [woocommerce/woocommerce#20062]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiosanches** [comment]
Not able to reproduce and this issue is all empty, probably some plugin that you have installed that does not support PHP 7.

**Comment by sarun007** [comment]
That is my mistake the issue empty sorry for that now i added my issue in detail please check that.

**Comment by claudiosanches** [comment]
Still my answer is correct, seems like comes from `woocommerce-gateway-paypal-pro`, better contact the plugin's support: https://woocommerce.com/contact-us/

**Comment by sarun007** [comment]
Thank you for your reply i checked the plugin change log on that log they have added some fix for Php 7 but still we have the issue.

this is the changelog
http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-gateway-paypal-pro/changelog.txt

**Comment by claudiosanches** [comment]
GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal.

If you need technical support for X, please use the helpdesk instead: https://woocommerce.com/contact-us/

**Comment by WillBrubaker** [comment]
@sarun007 the error is complaining about the fact that your callback function specifies two arguments but your call to `add_filter` is using the default number of arguments (which would be `1`) see https://developer.wordpress.org/reference/functions/add_filter/

The solution would be to replace `add_filter( 'woocommerce_payment_complete_order_status', 'bryce_wc_autocomplete_paid_orders' );` with `add_filter( 'woocommerce_payment_complete_order_status', 'bryce_wc_autocomplete_paid_orders', 10, 2 );`
