### ISSUE TITLE
Product Variation sorting (in Product data -> Variations) does not control display order of variations on product page.

### ISSUE THREAD

**Issue by spencerudnick** [woocommerce/woocommerce#20071]
**Describe the bug**
The controls to display the order of product variations on a product page do not work. Neither dragging-and-dropping nor clicking the 'hamburger' and manually setting sort order will update the order in which they appear in the variation select.

**To Reproduce**
1. Go to a product page which has variations–notice the order of the product variations in the select.
2. Go to the edit page for that product.
3. Open the Product data -> Variations section of the product editor.
4. Click and drag to reorder variations.
5. Reopen the product page. 
6. See that the changes made in the Product Edit page do not appear to alter the sorting of the product variations.
7. Go back to the Product Edit page.
8. Click the 'hamburger' and enter a numeric sort order for each variation.
9. Repeat 5 and 6.

**Screenshots**

***Settings in Product Edit section***
![screen shot 2018-05-14 at 7 12 07 pm](https://user-images.githubusercontent.com/3072639/40029539-c4270ac8-57aa-11e8-9378-c12e78f58f09.png)

***Actual order on product page***
![screen shot 2018-05-14 at 7 12 17 pm](https://user-images.githubusercontent.com/3072639/40029543-c6dbb142-57aa-11e8-9648-087d2f044e02.png)

**Expected behavior**
The order in which variation option elements appear in select elements on the front-end matches the order set manually in the cms.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://hktc-staging.asburyit.solutions
Site URL: https://hktc-staging.asburyit.solutions
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.30
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.6.39
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: baf_
MaxMind GeoIP Database: ✔
Total Database Size: 6.70MB
Database Data Size: 4.35MB
Database Index Size: 2.35MB
baf_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
baf_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
baf_woocommerce_log: Data: 0.00MB + Index: 0.00MB
baf_commentmeta: Data: 0.00MB + Index: 0.01MB
baf_comments: Data: 0.12MB + Index: 0.07MB
baf_links: Data: 0.00MB + Index: 0.00MB
baf_options: Data: 2.27MB + Index: 0.20MB
baf_postmeta: Data: 1.46MB + Index: 0.90MB
baf_posts: Data: 0.36MB + Index: 0.10MB
baf_termmeta: Data: 0.01MB + Index: 0.01MB
baf_terms: Data: 0.01MB + Index: 0.02MB
baf_term_relationships: Data: 0.01MB + Index: 0.03MB
baf_term_taxonomy: Data: 0.01MB + Index: 0.01MB
baf_usermeta: Data: 0.01MB + Index: 0.01MB
baf_users: Data: 0.00MB + Index: 0.01MB
baf_wc_download_log: Data: 0.00MB + Index: 0.00MB
baf_wc_webhooks: Data: 0.00MB + Index: 0.00MB
crypto_files: Data: 0.02MB + Index: 0.33MB
crypto_membership: Data: 0.02MB + Index: 0.09MB
crypto_payments: Data: 0.02MB + Index: 0.31MB
crypto_products: Data: 0.02MB + Index: 0.25MB

### Post Type Counts ###

attachment: 49
custom_css: 3
customize_changeset: 11
et_pb_layout: 1
nav_menu_item: 10
page: 11
post: 1
product: 26
product_variation: 290
project: 1
revision: 26
shop_coupon: 12
shop_order: 287
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #41 - /shop/
Cart: #42 - /cart/
Checkout: #43 - /checkout/
My account: #44 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hemp Kettle Tea Company
Version: 1.0.0
Author URL: https://www.asburyit.solutions
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.2.2
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
That dropdown is not showing variations, it's showing attributes. See https://github.com/woocommerce/woocommerce/issues/18974#issuecomment-365890833

cc @claudiulodro @peterfabian

**Comment by spencerudnick** [comment]
Hey @mikejolley,

Thanks for the link, however this does not resolve the issue I'm having with being unable to reorder items in the dropdown.

**Comment by mikejolley** [comment]
As that thread states, you need to sort the attributes. Not the variations.

**Comment by Arlind90** [comment]
> As that thread states, you need to sort the attributes. Not the variations.
Yup. Confirmed I had the same problem. You need to sort the attributes and not the variations. 
Thanks @mikejolley

**Comment by akku19** [comment]
please any on help this topic becouse my client are also this requirement so how i will full fil because i seen in back-end so data will save in variation id basis not sequence basis so how i get back end data sequence    ?

**Comment by MachineITSvcs** [comment]
I am experiencing this issue as well. When I update the order of attributes in the dashboard under Products > Attributes, but they reset on page refresh. This is affecting products with capacity sizes like 4GB, 8GB, 16GB, 32GB, etc, and are ordered "alphabetically/numerically" no matter what changes I make to be 16GB, 32GB, 4GB, 8GB, etc... Please advise. Thank you.

**Comment by kloon** [comment]
@MachineITSvcs You cannot sort strings like 16GB, 32GB, 4GB, 8GB numerically since they are seen as alphanumeric because they contain non-numeric characters, and in alphanumeric sorting, a string with a 1 in front is seen as coming before a 4.

If you want to have them in a specific order that does not work with alphanumeric or numeric sorting then you will have to set it to use custom sorting and then drag and drop the attributes in the order you want it to display.

**Comment by MachineITSvcs** [comment]
I’m pretty sure the question was asking how to set custom sorting. You start by saying it cannot be some, then recommend doing it. I’m confused. How do you set a custom sort order per your last paragraph for these attributes?

Collin Machine

**Comment by kloon** [comment]
> You start by saying it cannot be some, then recommend doing it.

I actually meant that you cannot sort the way you want using the default numeric or alphanumeric sorting options.

> How do you set a custom sort order per your last paragraph for these attributes?

Go to Products -> Attributes
Edit the attribute and select the `Custom ordering` option next to Default sort order
Click `Update`
![](https://cld.wthms.co/Xz4Kz4+)

Next click the configure terms link on the attribute you want to order
![](https://cld.wthms.co/GmMRXC+)

Use the three stripe icon on the left next to the terms and drag and drop them in the order you want them to display
![](https://cld.wthms.co/oTXLRm+)

**Comment by MachineITSvcs** [comment]
Thank you for the instructions. That’s exactly what I needed to know. I’ll test it out and let you know if I still have an issue. Thanks again!

Collin Machine

**Comment by nsek** [comment]
Attributes custom ordering does not display correctly in product page.

Hello,

i am facing a similar problem. I have an attribute configured for custom ordering but in product's backend page the selection is displayed alphabetically.

![Screen Shot 2019-05-27 at 21 29 21](https://user-images.githubusercontent.com/51094653/58435099-9c431500-80c7-11e9-98a9-55bc3b3ce4c4.png)

![Screen Shot 2019-05-27 at 21 32 27](https://user-images.githubusercontent.com/51094653/58435107-a402b980-80c7-11e9-990f-deb80c97ce8d.png)

I have tried changing the attributes order but the problem remains

Wordpress 5.1.1, Woocommerce 3.6.3.

**Comment by peterfabian** [comment]
Hi, 

please try to test this with only WooCommerce active. Ordering of attributes should work as you can see in my comments in the issue below:
https://github.com/woocommerce/woocommerce/issues/23912

If you can reproduce consistently with only WooCommerce plugin active, please open a new issue with steps to reproduce.

**Comment by jameskendy** [comment]
Thank you for this in-depth tutorial. I am trying to work on product variations but not getting the actual results as I have already gone through several resources and following this resource https://wpitech.com/woocommerce-product-variation/ to implement the product variation process. Can you please describe me further how to do this? This is the code that I think is somehow wrong. Is there any other way to set product variations?

$variation_id = woo_insert_post( $variation_post );
$variation = new WooCommerce_Product_Variation( $variation_id );
foreach ($variation_data['attributes'] as $attribute => $term_name )

**Comment by MachineITSvcs** [comment]
May I ask why you are attempting to add variations using code at all? It is pretty straightforward doing it through the dashboard

**Comment by MalTarDesigns** [comment]
https://devanswers.co/change-woocommerce-variations-attributes-custom-sort-order/

**Comment by OneOfA11** [comment]
I am with custom order but I have over 20 attributes and want to move one from the second page to first and cannot because cannot change "Number of items per page:" for the Attributes. Any solution for this? Event with custom order it's not custom order in product variant.

**Comment by itskawsar** [comment]
Why the variation sorting order feature is there? I think the product should be showing based on the variation order on the product page.

**Comment by itskawsar** [comment]
> I am with custom order but I have over 20 attributes and want to move one from the second page to first and cannot because cannot change "Number of items per page:" for the Attributes. Any solution for this? Event with custom order it's not custom order in product variant.

You can adjust the pagination under top screen options (Number of items per page). The default pagination number is 20. You can increase to a larger number.
![image](https://user-images.githubusercontent.com/1224493/97077545-8ca26580-1606-11eb-9628-de524c18df2a.png)

**Comment by webenadam** [comment]
Why the variation sorting order feature is there? What does it affect? in if it affects nothing, so why wouldn't you make it affect the sorting? it would be so much easier then ordering it from the general attributes edit.

**Comment by mamunur** [comment]
Reorder custom meta box row

**Comment by qzya** [comment]
Sorting attributes in Product -> Attributes can be extremely inconvenient, especially if you have a lot of attributes.
For myself, I solved this problem with a few lines through the `woocommerce_dropdown_variation_attribute_options_html` filter
[See this snippet](https://gist.github.com/qzya/c81d7e8ce6515ff1c730a87af0fb8e8c)

**Comment by boutzamat** [comment]
This is still an issue. I have sorted the attributes globally, but when i go to the product to add the attribute, they still show up in a random order.
