### ISSUE TITLE
Email cell formatting error

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce#20070]
zd-1158240

**Describe the bug**
When a non-white colored background is used with built-in email tools:
![](http://cld.wthms.co/fhc2Lj+)Image Link: http://cld.wthms.co/fhc2Lj

The border color is not constant for all cells
![](http://cld.wthms.co/OJfAIs+)Image Link: http://cld.wthms.co/OJfAIs

![](http://cld.wthms.co/2lVb5S+)Image Link: http://cld.wthms.co/2lVb5S

This exists across multiple email clients/browsers.

**Expected behavior**
I would expect the grid to all be the same color

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
I have tested this on WooCommerce 3.3.5, as well as WooCommerce 3.4-RC1 with the same results. I tested with Storefront 2.3 with no customizations, and user experienced same behavior with a custom theme with NO custom email templates
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20090
