### ISSUE TITLE
After build-in import simple products show [select options] instead of [add to cart]

### ISSUE THREAD

**Issue by opicron** [woocommerce/woocommerce#20075]
It seems that after I import my products through the build in importer the [add to cart] button no longer shows on archive pages. Instead it shows [select options].

When re-saving the product (any) on the backend with the product editor the [add to cart] button is shown again. Do note I change nothing in the product editor, only press save.

Products are saved as [simple] type by the importer, and are still [simple] after I re-save them in the backend.

I believe something is off in the product importer. I used the product importer before with the same CSV without issues.

**Comment by mikejolley** [comment]
Without a CSV to reference there is very little we can do here. It sounds like your CSV is changing the type from 'simple' to something which does not exist, or is setting up variations mapped to this product which would make it variable.

This issue lacks the details requested on the new issue form. Please comment back if you can provide a sample CSV with the issue - please include only a few rows as needed, not your entire import.

Thanks

**Comment by opicron** [comment]
```
SKU,Type,Name,Brands,Categories,Primary Category,Grouped Product,meta:_gtin,Currency,stock,meta:_stock_outlet,meta:_availability,manage_stock,stock_status,backorders,Regular Price,meta:_base_price,Sale Price,Short Description,Description
"removed","simple","removed","removed","Filter,_sap-filter-ab-temp","Filter",NULL,"1234567890",EUR,32.000000,.000000,,1,"instock",1,"59,00","44,43",,"",""
```

**Comment by opicron** [comment]
Sorry for the lacking issue description. I have added two rows of the CSV.

**Comment by opicron** [comment]
Further review of changing all CSV values one by one turned up the following:

If the value "meta:_stock_outlet" is .0 instead of 0 or ".0" the product is saved incorrect. It shows as simple product in backend (or var_dumped on frontend). However it shows [select options] cart button.

Again if I re-save the product in backend it resets to the correct state. 

--

It is my own vault here, sorry!

However it did bring to attention there might be a need for a validation/check on custom "meta:value" data in the import?
