### ISSUE TITLE
[3.4 RC1] API Authentication page no longer working

### ISSUE THREAD

**Issue by bryceadams** [woocommerce/woocommerce#20072]
**Describe the bug**
The WooCommerce API Authentication screen no longer works, and instead just returns a page (home) from the store.

**To Reproduce**
1. Go to https://store.com/wc-auth/v1/authorize (this URL is missing the requirements parameters but previous versions would at least show an error about the missing parameters, eg. https://petlight.com.au/wc-auth/v1/authorize).
2. You can't authorize the app.

Please let me know if you need any other details :)

**Comment by mikejolley** [comment]
Thanks.

See https://github.com/woocommerce/woocommerce/pull/20087
