### ISSUE TITLE
Bug in [product_categories] shortcode - order categories

### ISSUE THREAD

**Issue by rthvanesa** [woocommerce/woocommerce#20076]
When selecting the categories to be displayed, they will not be displayed in the order you selected them: http://nimb.ws/Mwotu0

We fixed this using the following code:
````
if( !empty($ids) ) {
      $args = array(
        'orderby'    => 'include',
        'hide_empty' => $hide_empty,
        'include'    => $ids,
        'pad_counts' => true,
        'child_of'   => $atts['parent']
     );
} else {
     $args = array(
        'orderby'    => $atts['orderby'],
        'order'      => $atts['order'],
        'hide_empty' => $hide_empty,
        'pad_counts' => true,
        'child_of'   => $atts['parent']
     );
}
````

**Comment by mikejolley** [comment]
Default `orderby` is `name`. This can be set to `include` by passing it to the shortcode. Looks like whatever is building the shortcode in your screenshot should include this option.

Thanks
