### ISSUE TITLE
Unpaid Order Cancelled – Time Limit Reached

### ISSUE THREAD

**Issue by sgehrman** [woocommerce/woocommerce#20088]
I have the latest Woocommerce, paypal standard isn't working.  Orders always get canceled.

**Comment by mikejolley** [comment]
This is not a support area. Please use the forum/helpdesk, and also review the troubleshooting steps here https://docs.woocommerce.com/document/paypal-standard/

**Comment by sgehrman** [comment]
It's buggy. Woocommerce has been nothing but problems since day one. Why doesn't this simple thing work?

**Comment by sgehrman** [comment]
Warning to others, don't use Woocommerce unless you like horribly buggy software.

**Comment by sgehrman** [comment]
Those docs are out of date.  Just checked.  No answers there.  I'm on Woocommerce 3, not 1.0

**Comment by sgehrman** [comment]
forum help desk just has morons who waste your time.
