### ISSUE TITLE
mandatory call to action tick box for privacy policy confirmation

### ISSUE THREAD

**Issue by ChrisEHC** [woocommerce/woocommerce#20096]
hi
to ensure full compliance with GDPR i feel that there should be a mandatory call to action tick box for the privacy policy acknowledgement on the registration and checkout screen similar to the current setup for the acknowledgement of the terms and conditions.

**Comment by mikejolley** [comment]
Please see https://github.com/woocommerce/woocommerce/issues/20015#issuecomment-387680340 We don't feel a checkbox is needed, and our legal advice did not state it was mandatory. Of course, check with a lawyer if uncertain since I am not one and I cannot give you legal advice.

Thanks
