### ISSUE TITLE
Sorry, it seems that there are no available payment methods for your state.

### ISSUE THREAD

**Issue by sunilnimble2015** [woocommerce/woocommerce#20095]
Hi,
I have enabled  **PayPal Express Checkout**  for woocommerce checkout from admin. But whenever i try too place place order its give me error.

> Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate 

I provided all needed API Credentials.

One more thing which i want to know, Is there SSL (HTTPS) should be needed  to enable or it will work with http?

**Comment by mikejolley** [comment]
Hi,

I'm not sure of that. In general regardless of a requirement, even if it's not related to your issue, you should use SSL. You're handling user data.

Please contact the helpdesk for PayPal Express support:

https://woocommerce.com/contact-us/ 

Thanks
