### ISSUE TITLE
Can't connect or login to woocommerce.com

### ISSUE THREAD

**Issue by johnlmccurdy** [woocommerce/woocommerce#20101]
**Describe the bug**
I try to login at woocommerce.com and it takes me down a path which fails to execute. Please see steps below.

**To Reproduce**
1. go to woocommerce.com
2. Click on 'login with wordpress.com'
3. On the page which says "Connect an existing WooCommerce.com account to your WordPress.com account to continue managing existing purchases, tickets and subscriptions". Choose > I have an existing account.
4. It asks for > "**Enter your old WooCommerce.com username and password to complete the connection**". It also says > **"Account found - there is already an account with this email address. Please enter username and password."**

(I don't know how it has found an account. I am using a private window.)

5. Enter correct woocommerce.com details. 

Get the following response. **"Invalid Login - please enter a valid username and password below."**

This is utter nonsense and has been going on for sometime. It is now at a critical point as I am trying to actually buy a plugin (the xero plugin) but this is proving impossible as I can't login. Your connection with wordpress' login portal has been disastrous to say the least. 

Please provide a solution to allow me to actually login and make a purchase.

**Comment by mikejolley** [comment]
Hi there,

Could you use the contact form here please if you didn't already (I'm assuming you cannot log into an account to submit a ticket): https://woocommerce.com/contact-us/#sales-form

Hopefully they can clarify things.  It sounds like there is confusion between woo.com and wordpress.com logins here, and you have one already.

See https://docs.woocommerce.com/document/log-into-woocommerce-com-with-wordpress-com/

Thanks
