### ISSUE TITLE
product.updated webhook fired with confusing body

### ISSUE THREAD

**Issue by kientux** [woocommerce/woocommerce#20109]
**Describe the bug**
When I create a draft product and not yet publish it, after create a variation, the `product.updated` webhook fired with body is a variation in form of a product, with status `publish`. It works different before as I remembered. Also I can't find any changelogs for this.

**To Reproduce**
1. Go to 'Products' menu -> Add new product
2. Type in product's name, create new attribute, add a variation with the created attribute
3. Webhook `product.updated` fired, with this body in webhook delivery: https://pastebin.com/raw/XN2EaTTh

**Screenshots**
![screen shot 2018-05-17 at 10 23 45](https://user-images.githubusercontent.com/4200743/40155177-74c22f58-59bc-11e8-8445-814c818b4f10.png)

**Expected behavior**
`product.updated` should be fired with body of the actual product (I remember it works like that before). Or at least the body should not be a variation in form of a product with status `publish`. It really confused.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: http://duylv.anhphuongisc.vn
Site URL: http://duylv.anhphuongisc.vn
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.4.6
PHP Version: ❌ 5.5.9-1ubuntu4.11 - We recommend a minimum PHP version of 5.6. See: How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 8.39MB
Database Data Size: 4.40MB
Database Index Size: 3.99MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.03MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.06MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.06MB + Index: 0.08MB
wp_postmeta: Data: 2.52MB + Index: 2.92MB
wp_posts: Data: 0.22MB + Index: 0.22MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 271
page: 7
post: 2
product: 179
product_variation: 231
revision: 3
shop_coupon: 1
shop_order: 68

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.3.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: VND (₫)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###
</details>

**Comment by kientux** [comment]
I find it really hard to describing the issue. After some testing I realize the `product.created` also fired when add a variation of draft product. And the body is that variation with status `publish`. I currently running a syncing tool between Woocommerce and my inventory management system in production, so with those confusing and unexpected changes, I can't rely on Woocommerce webhooks.

**Comment by mikejolley** [comment]
Variations are still a type of product/post and do fire webhooks. They are also published by default (or private if disabled). Sounds like you just need to look at the `type` when handling the webhook - you can ignore type `variation` but continue to handle type `variable`.

The API has not changed. Events which trigger webhooks may have, so more events are captured. Still, any code using webhooks could have already been coded to handle product types because that part is not new.

Thanks

cc @claudiosanches
