### ISSUE TITLE
GDPR: Add ability to filter orders affected by anonymize_orders_query() and trash_orders_query()

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce#20105]
The [settings](https://cloudup.com/cwmrI0hUFlA) coming in 3.4 which allow store managers to specify how long certain orders should live for before being trashed/anonymised and the events which carry those requests out aren't currently filterable. 

From a Subscriptions point of view, we don't want renewal orders (and other subscription-related order types) to be trashed or anonymised while the subscription is still live.

Trashing or anonymised subscription orders could cause issues with subscription date calculation as it would cause incorrect completed payment counts for example. 

**Describe the solution you'd like**
A filter to allow third-parties to customise what orders can be affected by [`WC_Privacy ::anonymize_orders_query()`](https://github.com/woocommerce/woocommerce/blob/3.4.0-rc.1/includes/class-wc-privacy.php#L267) and [`WC_Privacy::trash_orders_query()`](https://github.com/woocommerce/woocommerce/blob/3.4.0-rc.1/includes/class-wc-privacy.php#L224) similar to the [`'woocommerce_privacy_erase_order_personal_data'`](https://github.com/woocommerce/woocommerce/blob/3.4.0-rc.1/includes/class-wc-privacy-erasers.php#L134) filter.

**Describe alternatives you've considered**

- Adding a filter [here](https://github.com/woocommerce/woocommerce/blob/3.4.0-rc.1/includes/class-wc-privacy.php#L273) and [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-privacy.php#L230) to allow third-parties to prevent an order from being trashed or anonymised. 
- Adding a filter [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-privacy.php#L268) and [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-privacy.php#L225) to allow third-parties to add their own query args to limit the query. 

Both of those possible fixes ran into problems though. The first filter option causes issues because if an order was skipped the `$count` variable would be incorrect and then cause [this condition](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-privacy-background-process.php#L63) to pass incorrectly. We could still increment the `$count` variable if an order is skipped, but then we run into a new problem, if the number of skipped orders is more than the `$limit` (20). The next time the `wc_get_orders( $query )` runs, it will return a full batch of ignored orders. 

This is where I considered a filter to filter the `$query` arg. This would allow third-parties to prevent their order types from being considered at all, however from a Subscriptions point of view, there are some subscription order types which couldn't be excluded using the `wc_get_orders()` `$query`. For example subscription parent orders (initial purchase orders) are only set as the subscription post parent, they don't have any meta or anything that we could use to filter those out.

Let me know if you have any ideas on ways we might be able to resolve this. 

Regarding any concerns you have with Subscriptions effectively ignoring these settings, we're going to  make it clear to store managers that this is the case with a note in the setting description. We're also planning on adding similar settings for subscriptions which would essentially anonymise the subscription and all it's related orders after the subscription has ended etc.

**Comment by james-allan** [comment]
I've submitted #20106 which basically implements the first filter option I mentioned above. In that PR I've addressed the issues mentioned above with batching and `$count` variables.

**Comment by james-allan** [comment]
> Your PR removes the limits which will make that query so much slower.

Yeah that's fair. The issue with just filtering the queries is that we can't exclude all subscription order types just with `wc_get_order()` args. By order type I don't mean post type (`shop_order` or `shop_subscription`), I mean like renewal, switch and parent orders. All those orders are `'shop_orders'` so it's not a matter specifying the type arg. 

Renewal and switch orders have `_subscription_renewal` and `_subscription_switch` post meta so theoretically we can exclude those by filtering the query but subscription parent orders are the post parent of a subscription post. As far as I can tell it's not possible to exclude those by filtering `wc_get_order()` args.

Let me know what you think though, if you see a way we could do it, I would be happy to go with it.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20130

**Comment by mikejolley** [comment]
Missed that feedback. Let me copy to the PR.
