### ISSUE TITLE
HTML tags being returned in Response

### ISSUE THREAD

**Issue by amitrathik** [woocommerce/woocommerce#20103]
By default, <p> tags are being returned in "description" and "short_description"?

`"short_description": "<p>18 Ounces</p>\n",`

Is this anyway to prevent this from happening? I just want the text.

**Comment by WillBrubaker** [comment]
Probably a result of `wp_autop` https://developer.wordpress.org/reference/functions/wpautop/

I reckon Google may know how to disable that

**Comment by mikejolley** [comment]
You can strip them in your app I imagine. We return HTML which matches what gets output on product pages.

If you have a valid reason for not needing that, explain over here: https://github.com/woocommerce/wc-api-dev/issues

Thanks.
