### ISSUE TITLE
Issue at “Enable/Disable stock management at product level”

### ISSUE THREAD

**Issue by somlaweb** [woocommerce/woocommerce#20112]
Hello,

I have an issue related to “Enable stock management at product level”.

To reproduce:

1 – Edit a VARIABLE product.
2 – At “Inventory” check “Manage stock?” checkbox.
3 – At “Inventory” set “Stock quantity” to ‘0’.
4 – Save the product.
5 – Everything is fine the product is not available
6 – Edit the same product again
7 – At “Inventory” UNcheck “Manage stock?” checkbox.
8 – Save the product.
9 – ISUUE: The product is not available. The product should be available.

**Comment by mikejolley** [comment]
Steps 1-4 made all variations 'out of stock', which is correct, they were.

Steps 5-8 made all variations non-stock managed again, however, that won't cause the 'stock status' select box to update. Doing that automatically may be undesirable based on needs or what has been set there manual.

So your step 9 should be to go to the 'variations' tab and set the 'stock status' to instock either in bulk, or for the variations you want to show as in stock.

Hope that helps.

**Comment by somlaweb** [comment]
Hi Mike,

Thanks.
