### ISSUE TITLE
Checkout Page scrolls down in Safari

### ISSUE THREAD

**Issue by rthvanesa** [woocommerce/woocommerce#20110]
When click on Checkout Page, it automatically scrolls down the page. As I took a closer look within the code, I found out that the autofocus set on the First Name input is messing with Safari (class-wc-countries.php:621). You may already know about this issue, but I wanted to remind you of it, as this is bothering a lot of clients.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20123
