### ISSUE TITLE
Exception handling when sending emails.

### ISSUE THREAD

**Issue by BigWhale** [woocommerce/woocommerce#20118]
It appears that send_transactional_email in WC_Emails throws away all exceptions if DEBUG isn't turned on. Even with debug turned on the message that gets logged is vague at best.

Exceptions do happen, even in production, and there are many cases where you simply can't turn on DEBUG and go search for the error. Every exception should be logged, preferably with the exception error message.

Right now if anything throws an exception somewhere down the email generation pipeline the whole process silently fails and nobody knows why and where.

**Comment by BigWhale** [comment]
I don't know if there's any kind of logging facility in Woocommerce, if there is, I can write a short fix for this so that exceptions get reported. And if there isn't maybe there should be one. :)

**Comment by mikejolley** [comment]
There is a logging function. Example here you can adapt if you want to send a PR. https://github.com/woocommerce/woocommerce/blob/master/includes/class-woocommerce.php#L187

Thanks

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20203
