### ISSUE TITLE
wc meta box functions are not using CRUD methods

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce#20128]
**Describe the bug**

https://github.com/woocommerce/woocommerce/blob/master/includes/admin/wc-meta-box-functions.php#L27

This should be CRUDified. Or removed. The problem is that if that's used on a product / variation / order / whatever, and the data store is not the wp posts table, that will never get the correct default value.

**To Reproduce**
It's code, though you could spin up a site with a custom order table, and try to add a wc input element with the default left to the function.

**Expected behavior**
That it correctly figures out what it's for using globals (?) and uses that.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

Not relevant.

**Comment by javorszky** [comment]
Oh, the `$post` is global, so a possible approach is to figure out the data store based on post type, and then grab the actual object?

**Comment by kloon** [comment]
You can pass the value along to the function call, see what we did here recently where we also ran into this as a possible issue https://github.com/woocommerce/woocommerce/commit/efe0d36eeacb95fddea79eb147251c2c0bfd4c8f#diff-72952d8c685dc97e7466537d7ded27ae

The reason we want to keep the functions as is, is to maintain backward compatibility for extensions using the functions relying on data coming from the meta tables and not passing values along.

When the time comes where we merge a working custom table solution into core we will explore what to do regarding these functions when you do not supply a value.

**Comment by javorszky** [comment]
> The reason we want to keep the functions as is, is to maintain backward compatibility for extensions using the functions relying on data coming from the meta tables and not passing values along.

If you get the object, and use the crud methods, and the site didn't change the data store, the data store itself is still going to fall back to using the `get_post_meta` functions, it's just a layer removed from it.

**Comment by mikejolley** [comment]
The data store doesn't handle this - when you call the input field functions you PASS it your value from your CRUD object/data-store. The post meta is a fallback if this is not passed.

WC core passes all values through.

There is no way to guess what 'prop' should be used here that I can see anyway.
