### ISSUE TITLE
Slug "%s" is too long (28 characters max). Shorten it, please.

### ISSUE THREAD

**Issue by Manucharyan** [woocommerce/woocommerce#20121]
Please help me to resolve this problem. The error described below.

Slug "%s" is too long (28 characters max). Shorten it, please.

**Comment by mikejolley** [comment]
This is shown when you're adding an attribute name/slug in admin. Whatever you've entered is too long. Note utf8 symbols/characters won't count as '1' character when inserted into the database.

If you're actually seeing the %s it could be your translation files, or a plugin outputting this string, not WooCommerce. I've checked our implementation is working:

![attributes wordpress wordpress 2018-05-18 10-17-47](https://user-images.githubusercontent.com/90977/40226853-c383ea50-5a84-11e8-858d-91a7b50cc30c.png)

Let me know if there are more details your report is missing.

**Comment by erikkubica** [comment]
This makes my import from clients old website to new one a problem. We made him a new website and we have exported products from his old website which is woocommerce then import it into the new one. So how it is possible, that old woocommerce is fine with 28ch or longer but the new one is not.
