### ISSUE TITLE
External Product The request method POST is inappropriate for the URL

### ISSUE THREAD

**Issue by britner** [woocommerce/woocommerce#20133]
**Describe the bug**
When testing with an external product (version 3.4.0) and trying various links most don't work with the link added to the form instead of being a normal link.

A simple test of using google.com shows the type of error. But testing with avantlink.com affiliate links you just get an error. If I go back to 3.3.5 then they work.

**To Reproduce**
And https://www.google.com to an external product url and try clicking the "buy" button on the frontend.

**WordPress Environment**
I tested with Storefront and WP 4.9.6

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20138

**Comment by britner** [comment]
Not sure if I should post here but with your edit to the file I still see the same issue with a link like this:

http://classic.avantlink.com/click.php?p=246895&pw=210371&pt=3&pri=595424&tt=df

^ That works if on an archive but on the single product page where you have this new form added it doesn't take you to the product page. I have a client who is an affiliate for REI and with this update, all his links break.

**Comment by britner** [comment]
@mikejolley

**Comment by mikejolley** [comment]
Where does it take you?

**Comment by britner** [comment]
https://www.rei.com/?cm_mmc=aff_AL-_-26311-_-210371-_-NA&avad=210371_d1204c1e5

**Comment by mikejolley** [comment]
@britner I think it's the way the link is decoded. I'm working on a fix for the FORM rather than reverting the change entirely.
