### ISSUE TITLE
[API] Totals and taxes not updating after updating order

### ISSUE THREAD

**Issue by amjad** [woocommerce/woocommerce#20135]
I have two tax rates configured based on states. Tax is set to calculate based on customer shipping address. 

When I set customer shipping address to one state, the tax is calculated fine, but if I want to update the shipping address to another state, the totals and tax is not updating. But if I add/remove an item from the order, the totals and tax are updating to the state I changed to. 

How can I trigger update of totals and taxes by just changing the shipping address on the order. 

I’m using the REST API to create/update orders. Thanks.

**Comment by mikejolley** [comment]
It's done automatically here if the address changes:

https://github.com/woocommerce/woocommerce/blob/d584ed72b9787fbf3adbcbcfd2dc67e5394c1fc9/includes/api/class-wc-rest-orders-controller.php#L533-L536

This may be missing tax recalc. I'll put in a PR - please test it.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20137 - please let me know if it works for you.

**Comment by mikejolley** [comment]
Look for the calculate_totals code. We don't update the legacy API any more.
