### ISSUE TITLE
API keys dont transfer from deleted users

### ISSUE THREAD

**Issue by cdesewell** [woocommerce/woocommerce#20141]
**Describe the bug**
When you delete a user and you have the option to transfer their data to another user. This does not seem to transfer API keys. Instead the API keys associated with that user become void and return 401. If this is intentional behaviour it needs to be documented (preferably here) https://docs.woocommerce.com/document/woocommerce-rest-api/

**To Reproduce**
1. Create admin user 1
2. Create an API key, assign it to new admin user 1
3. Create admin user 2
4. Delete admin user 1 and transfer data to admin user 2
5. Use any WooCommerce API and find a 401 error response is given with api keys.

**Expected behavior**
The API keys continue to work.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://independencemarket.com
Site URL: https://independencemarket.com
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.13
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.53.1
NSS/3.28.4

SUHOSIN Installed: –
MySQL Version: 5.6.39
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 211.56MB
Database Data Size: 172.95MB
Database Index Size: 38.61MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.27MB
wp_woocommerce_order_itemmeta: Data: 10.52MB + Index: 6.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.13MB + Index: 0.14MB
wp_comments: Data: 1.52MB + Index: 0.91MB
wp_email_log: Data: 37.52MB + Index: 0.00MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 2.02MB + Index: 0.00MB
wp_newsletter: Data: 0.02MB + Index: 0.03MB
wp_newsletter_emails: Data: 0.02MB + Index: 0.00MB
wp_newsletter_sent: Data: 0.00MB + Index: 0.00MB
wp_newsletter_stats: Data: 0.02MB + Index: 0.03MB
wp_options: Data: 4.27MB + Index: 1.20MB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 19.55MB + Index: 21.98MB
wp_posts: Data: 3.52MB + Index: 1.28MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.30MB + Index: 0.13MB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB
wp_toolset_post_guid_id: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 4.52MB + Index: 5.02MB
wp_users: Data: 0.20MB + Index: 0.20MB
wp_usin_user_data: Data: 0.09MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 1.52MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 10.52MB + Index: 0.00MB
wp_wfHits: Data: 1.02MB + Index: 0.36MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.06MB + Index: 0.06MB
wp_wfKnownFileList: Data: 4.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.13MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.06MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.13MB + Index: 0.09MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_woof_query_cache: Data: 0.02MB + Index: 0.02MB
wp_wpmelon_advbedit_temp: Data: 0.05MB + Index: 0.00MB
wp_wpml_mails: Data: 66.52MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

acf_option_page: 3
acf-field: 10
acf-field-group: 5
attachment: 838
company: 8
custom_css: 1
customize_changeset: 15
mc4wp-form: 1
nav_menu_item: 13
oembed_cache: 1
page: 43
post: 9
product: 416
product_variation: 1864
revision: 303
shop_coupon: 326
shop_order: 3119
shop_order_refund: 162
wccaf: 3
wccpf: 1
wp-types-group: 1
wp-types-term-group: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

ACF Option Pages: by Joel Milne
GoldHat Group – 1.1.0

Advanced Custom Fields PRO: by Elliot Condon – 5.6.9
WP Offload S3: by Delicious Brains – 1.6.2
Black Studio TinyMCE Widget: by Black Studio – 2.6.2
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.50
Contact Form 7: by Takayuki Miyoshi – 5.0.1
Email Log: by Sudar – 2.2.5
im_order_export: by Big Avocado – 0.1
MailChimp for WooCommerce: by MailChimp – 2.1.4 – Not tested with the active version of WooCommerce
Newsletter: by Stefano Lissa & The Newsletter Team – 5.2.6
Product Input Fields for WooCommerce Pro: by Algoritmika Ltd – 1.1.1 – Not tested with the active version of WooCommerce
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Templatemela Custom Post: by Templatemela – 1.0
Templatemela Meta Box: by Templatemela – 1.0
Templatemela Shortcode: by Templatemela – 1.0
Toolset Types: by OnTheGoSystems – 2.2.22
Users Insights: by Pexeto – 3.4.0
WC Fields Factory: by Saravana Kumar K – 2.0.7 – Not tested with the active version of WooCommerce
WC Password Strength Settings: by Daniel Santoro – 2.0.2
Widget Importer & Exporter: by churchthemes.com – 1.5.3
WooCommerce Accepted Payment Methods: by jameskoster – 0.7.0 – Not tested with the active version of WooCommerce
Woocommerce Advanced Bulk Edit: by George Iron – 3.6 – Not tested with the active version of WooCommerce
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.3
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 4.1.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.3 – Not tested with the active version of WooCommerce
WooCommerce Grid / List toggle: by jameskoster – 1.1.0 – Not tested with the active version of WooCommerce
WOOF - WooCommerce Products Filter: by realmag777 – 1.2.0
WooCommerce: by Automattic – 3.3.5
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 7.0.2
WP Encrypt: by Felix Arntz – 1.0.0-beta.8
WP Mail Logging: by Christian Zöller – 1.8.3
WP Mail From II: by Ben Huson – 1.1
WP SES: by Delicious Brains Inc – 0.8

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #116 - /shop/
Cart: #117 - /cart/
Checkout: #118 - /checkout/
My account: #119 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Independence Market Woocommerce
Version: 1.0
Author URL: http://www.amigopartnership.com
Child Theme: ✔
Parent Theme Name: Foodstuff
Parent Theme Version: 1.0
Parent Theme Author URL: http://www.templatemela.com
WooCommerce Support: ✔

### Templates ###

Overrides: independence-market-woocommerce/woocommerce/archive-product.php version - is out of date. The core version is 3.3.0
independence-market-woocommerce/woocommerce/cart/cart-empty.php
independence-market-woocommerce/woocommerce/cart/cart.php version 3.1.0 is out of date. The core version is 3.3.0
independence-market-woocommerce/woocommerce/cart/shipping-calculator.php
independence-market-woocommerce/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.3.0
independence-market-woocommerce/woocommerce/checkout/form-shipping.php
independence-market-woocommerce/woocommerce/content-product.php
independence-market-woocommerce/woocommerce/content-single-product.php
independence-market-woocommerce/woocommerce/emails/admin-new-order.php
independence-market-woocommerce/woocommerce/emails/customer-new-account.php
independence-market-woocommerce/woocommerce/emails/plain/admin-new-order.php
independence-market-woocommerce/woocommerce/emails/plain/customer-processing-order.php
independence-market-woocommerce/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.3.0
foodstuff/woocommerce/global/wrapper-start.php version 1.6.4 is out of date. The core version is 3.3.0
independence-market-woocommerce/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
independence-market-woocommerce/woocommerce/loop/price.php
independence-market-woocommerce/woocommerce/myaccount/dashboard.php
independence-market-woocommerce/woocommerce/myaccount/form-edit-address.php version 3.0.9 is out of date. The core version is 3.3.0
independence-market-woocommerce/woocommerce/myaccount/my-address.php
independence-market-woocommerce/woocommerce/order/order-details-customer.php version 3.2.0 is out of date. The core version is 3.3.0
independence-market-woocommerce/woocommerce/order/order-details-item.php
independence-market-woocommerce/woocommerce/order/order-details.php version 3.2.0 is out of date. The core version is 3.3.0
independence-market-woocommerce/woocommerce/single-product/add-to-cart/simple.php
independence-market-woocommerce/woocommerce/single-product/add-to-cart/variable.php
independence-market-woocommerce/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
independence-market-woocommerce/woocommerce/single-product/add-to-cart/variation.php
independence-market-woocommerce/woocommerce/single-product/meta.php
independence-market-woocommerce/woocommerce/single-product/price.php
independence-market-woocommerce/woocommerce/single-product/product-image.php version 3.1.0 is out of date. The core version is 3.3.2
independence-market-woocommerce/woocommerce/single-product/review-meta.php
independence-market-woocommerce/woocommerce/single-product/tabs/description.php
independence-market-woocommerce/woocommerce/single-product/tabs/tabs.php
independence-market-woocommerce/woocommerce/single-product/up-sells.php
independence-market-woocommerce/woocommerce/single-product-reviews.php
independence-market-woocommerce/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update

### Braintree (Credit Card) ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Braintree (PayPal) ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
`

</details>

**Comment by mikejolley** [comment]
It asks you to transfer content - I don't think a REST API key falls into that category. I've added a quick note in https://github.com/woocommerce/woocommerce-rest-api-docs/commit/29900c95e9e7a8ce719d2e7a1404e3c5fa60dc2e

Thanks
