### ISSUE TITLE
[Starting Development] Need some guidance as to how to start.

### ISSUE THREAD

**Issue by redlagoon** [woocommerce/woocommerce#20147]
[Skip to the big 'Questions are here' header if you don't care about story / details]

Hola! Sorry if this doesn't quite fit the usual case for posting here, but I'd be forever grateful for a **bit of guidance.**

_I'm currently writing a suite of plugins within a "customer focused" framework that, once it's stable, will be released as open-source, as such, my intentions are to give back, for now, I can only take. I've contributed / helped others on other projects, so I promise to keep an eye here and answer any questions that I can. It's the least I can do for now._

On to my issue:

I've hit a wall. I'm as of now trying to integrate Woo into my framework / theme. I went ahead and `var_dump`'d everything that WC has, followed the documentation from here:

https://docs.woocommerce.com/wc-apidocs/class-WC_Product.html

And dived deep into quite a bit of functions, see what they return, what they all do and how the inner workings happen.

Here's what I came up with, for a custom cart:

https://gist.github.com/redlagoon/3fe42959fdd54daeed4cdcdc2c170c56

And here's how I integrated it:

`add_action( 'woo_cart_dropdown', [$this, 'showCart'] );`

And in my header:

```
                    <div class="the-cart-box">
                        <?php do_action( 'woo_cart_dropdown', true ); ?>
                    </div>
```

It's a pretty dirty approach but it got me up to speed. Now, I'm looking to do something more than this:

**I want custom templates.** I wanna over-write Woo's templates and give them my custom styling / functionality, as far as I read from the official documentation, all you'd have to do is, within your current theme path, create the file `woocommerce.php` and then...

Well that's where I'm stuck, here are concrete questions:

# Questions are here.

1) Is my assertion that if I just want to modify, say, the single product's page, I can just, in my (see question 2, this is after I'll have an answer to that) newly created path create the file `single-product.php`, copy the original syntax and then start working from there?

For example, check this out: https://theretailer.wp-theme.design/shop/accessories/micro-waffle-knit-sweater/

It looks amazing! It has some custom things, but mostly it's just the basic. I'd like to achieve something similar.

2) How do I point `woocommerce.php` to a custom directory? Matter of fact, I'd like for `woocommerce.php` to be in this path. For me, it is `Framework/Sprout/Integrations/Woo`? I'm currently stuck here and can't proceed at all.

That'd be for all. I can solve any issues that'll arise but just looking to actually get started for now.

Also, any materials that dwelve deep into the inner workings of Woo? I know there's the documentation, but it doesn't really connect one class to another and so on, from a perspective of "okay, this is how you do [insert-motivation-here]", just very technical.

I know I can look at a theme, but, well, without trying to disrespect anyone, most themes write very bad code. Huge-ass classes that have functions that have nothing to do with each other, no interfaces, no de-coupling, no nothing. And well, zero testing. I just wanna do a proper job, hence why I ask here.

Thanks!

**Comment by iamntz** [comment]
> How do I point woocommerce.php to a custom directory? Matter of fact, I'd like for woocommerce.php to be in this path. For me, it is Framework/Sprout/Integrations/Woo? I'm currently stuck here and can't proceed at all.

[Read the source, Luke!](https://github.com/woocommerce/woocommerce/blob/master/includes/class-woocommerce.php#L583)

You have a filter exactly for this:

```
add_filter( 'woocommerce_template_path' , function() {
  return 'my/folder/inside/my/theme/'; // don't forget the final slash!
});
```

**Comment by mikejolley** [comment]
Hi there,

1) Yes you can override templates via your theme by copying. We do however discourage this - take a look at https://github.com/woocommerce/woocommerce/wiki/Template-File-Guidelines-for-Devs-and-Theme-Authors

2) I think the answer above covers this. You won't need that file if doing a proper integration with WooCommerce though.

For a non 'huge ass' theme that doesn't use template overrides, look to https://github.com/woocommerce/storefront Maybe this could be a starting point?

If you're looking for places to ask these types of questions there is a Slack community https://woocommerceslack.herokuapp.com/ and some facebook groups you can join :)

Thanks
