### ISSUE TITLE
Woo install hides WPcom comment count

### ISSUE THREAD

**Issue by xpurichan** [woocommerce/woocommerce#20140]
**Describe the bug**
When WooCommerce is installed some WordPress.com themes are missing blog post comment **counts/totals** on both their blog page (some themes like Dynamic News display comment totals on the blog page, not all themes do) and individual post pages (this is present on all themes). When WooCommerce is deactivated the comment counts return.

Themes tested: 
* DailyMag (problem occurs)
* Dynamic News (problem occurs)
* Dara (problem does **not** occur)
No other themes were tested, but this likely effects more themes

**To Reproduce**
1. Install WooCommerce
2. Activate theme: DailyMag or Dynamic News
3. Create a blog post on this site with any least one comment on it
4. Notice that on the post the total comment count is missing

**Screenshots**
Woo disabled: http://cld.wthms.co/F50pyo (comment count present)
Woo enabled: http://cld.wthms.co/xn9dun (comment count missing)
The above screenshots are from the post page on the DailyMag theme.

**Expected behavior**
The comment count should be listed on blog posts, regardless of WooCommerce install.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://lillylearns.com
Site URL: https://lillylearns.com
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.59.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_131376930_
MaxMind GeoIP Database: ✔
Total Database Size: 6.80MB
Database Data Size: 6.06MB
Database Index Size: 0.74MB
wp_131376930_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_131376930_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_131376930_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_131376930_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_131376930_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_131376930_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_131376930_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_131376930_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_131376930_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_131376930_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_131376930_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_131376930_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_131376930_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_131376930_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_131376930_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_131376930_comments: Data: 0.00MB + Index: 0.01MB
wp_131376930_links: Data: 0.00MB + Index: 0.00MB
wp_131376930_ngg_album: Data: 0.02MB + Index: 0.02MB
wp_131376930_ngg_gallery: Data: 0.02MB + Index: 0.02MB
wp_131376930_ngg_pictures: Data: 0.02MB + Index: 0.02MB
wp_131376930_options: Data: 5.14MB + Index: 0.10MB
wp_131376930_postmeta: Data: 0.21MB + Index: 0.07MB
wp_131376930_posts: Data: 0.32MB + Index: 0.06MB
wp_131376930_termmeta: Data: 0.00MB + Index: 0.00MB
wp_131376930_terms: Data: 0.00MB + Index: 0.00MB
wp_131376930_term_relationships: Data: 0.00MB + Index: 0.01MB
wp_131376930_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_131376930_usermeta: Data: 0.01MB + Index: 0.01MB
wp_131376930_users: Data: 0.00MB + Index: 0.00MB
wp_131376930_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_131376930_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 97
customize_changeset: 38
custom_css: 2
jetpack-portfolio: 3
jetpack-testimonial: 1
jetpack_migration: 2
nav_menu_item: 17
ngg_gallery: 16
ngg_pictures: 34
page: 9
post: 16
product: 3
product_variation: 2
revision: 54
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.0.3
AMP: by WordPress.com VIP
XWP
Google
and contributors – 0.7.0

Jetpack by WordPress.com: by Automattic – 6.1
WooCommerce: by Automattic – 3.3.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #657 - /shop/
Cart: #658 - /cart/
Checkout: #659 - /checkout/
My account: #660 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Dynamic News
Version: 1.0
Author URL: http://themezee.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
@xpurichan Did you test with Jetpack off? I know it has some comment functionality built in also.

Can this be replicated outside of .com? Thats a closed environement we don't have access to right now. I tested the free version of this theme without issue:

![hello world wordpress 2018-05-22 11-36-17](https://user-images.githubusercontent.com/90977/40357843-4b5f856e-5db5-11e8-937a-00bf4c305f28.png)

So that leaves:
- the premium version
- .com itself
- Jetpack

as possible conflicting sources. If it were a bug just within WC, we'd see it on all stores + themes.

**Comment by xpurichan** [comment]
@mikejolley 

> Did you test with Jetpack off? I know it has some comment functionality built in also.

Good question. I don't believe I can disable Jetpack on an AT site. As part of the testing we did disable all of the Jetpack modules and the problem persisted.

We also performed testing an a simple (non AT) WP site and the problem was not present, but we suspected this was because Woo wasn't present rather than Jetpack.

My only question about Jetpack being the potential culprit is: we should then be able to see the problem on any AT site, rather than only AT sites with Woo installed, right? Of course you might mean the combination of Woo and Jetpack, or something else.

**Comment by mikejolley** [comment]
@xpurichan 

> My only question about Jetpack being the potential culprit is: we should then be able to see the problem on any AT site, rather than only AT sites with Woo installed, right? Of course you might mean the combination of Woo and Jetpack, or something else.

Yes thats what I meant. I'm assuming that if something did take over comments, it would use WP hooks to update counts, something woo also does so our custom comment types are excluded.

> We also performed testing an a simple (non AT) WP site and the problem was not present, but we suspected this was because Woo wasn't present rather than Jetpack.

What about this non AT site with this theme and woo installed?

I'm wondering if this issue should get some eyes from someone more familiar with .com if it's only reproducible on .com :) As I showed earlier, the lite version of that theme is fine.

**Comment by mikejolley** [comment]
@xpurichan @jeffikus mentioned this could be logged under https://wpcom-premium-themes.trac.automattic.com/newticket so the author of the theme could investigate under the .com environment. Would that be possible please?

If it turns out we're at fault, or we can find a way to replicate this outside of .com we'll be happy to help - you can either reply back here, our slack channel, or post on our p2 +protonpower to get some more eyes on the issue :)

Since we're unable to replicate this on themes we have access to (including the lite version) it doesn't appear to be something fixable or reproducible our side. Hopefully someone more experienced with .com can track it down.

Thanks.

**Comment by xpurichan** [comment]
@mikejolley @jeffikus My only hesitating to Trac this is because I understand that Trac is just for themes. Since the issue isn't present using these themes unless WooCommerce is installed, and it is effecting multiple themes, would it make more sense to report this to the Jetpack team?

**Comment by mikejolley** [comment]
@xpurichan Still uncertain what is causing it. I think an affected theme would be the best place to track it down?

**Comment by xpurichan** [comment]
I am sorry for the drag! New report can be found in Trac-#8065
