### ISSUE TITLE
remove "Search using CRUD." 

### ISSUE THREAD

**Issue by FabriSancho** [woocommerce/woocommerce#20142]
/plugins/woocommerce/includes/admin/list-tables/class-wc-admin-list-table-products.php, on line 462 
```
// Search using CRUD.
		if ( ! empty( $query_vars['s'] ) ) {
			$data_store = WC_Data_Store::load( 'product' );
			$ids        = $data_store->search_products( wc_clean( $query_vars['s'] ), '', true, true );
			$query_vars['post__in'] = array_merge( $ids, array( 0 ) );
			// So we know we are searching products.
			$query_vars['product_search'] = true;
			unset( $query_vars['s'] );
		}

```

this prevents any other code from performing a textual search from the list of products, ex. for a post meta

and what is more serious, leaves the function of the core is_search () = false

$ data_store-> search_products does not provide any hook or action to add or modify functionality, result, you can only do searches for what interests you, only for "sku"

**Comment by mikejolley** [comment]
Hi @FabriSancho 

First off, thanks for the report and PR. I understand why you've suggested this filter, however, I'm not in agreement that this should be merged.

If this filter is included, it means CRUD is bypassed and regular WP based searching/querying takes effect. When product data moves out of postmeta, something the CRUD will allow, anyone using this filter will no longer be able to search and the functionality will be broken. We shouldn't include options that will definitely break in the near future.

> and what is more serious, leaves the function of the core is_search () = false

A custom query var is added so you can detect when search is happening - `product_search`

> $ data_store-> search_products does not provide any hook or action to add or modify functionality, result, you can only do searches for what interests you, only for "sku"

We search title, description, excerpt, and SKU. These are the most important fields. I don't see a reason to search any other core data.

It seems you have 2 choices:

1.  During a `product_search`, filter the main WP query and add extra params there or pass in extra IDs to the post__in parameter.
2. Suggest a filter for `search_products` (either the query, or the returned IDs). IDs would probably be better so we're not just supporting query manipulation.

Just bare in mind any post meta search will be very expensive performance wise.

Hope that makes sense, thanks.

**Comment by FabriSancho** [comment]
> Just bare in mind any post meta search will be very expensive performance wise.
excuse

>We search title, description, excerpt, and SKU. These are the most important fields. I don't see a reason to search any other core data.
excuse

>leaves the function of the core is_search () = false........ A custom query var is added so you can detect when search is happening - product_search

reinventing the wheel
