### ISSUE TITLE
[API] Product image handling in REST API

### ISSUE THREAD

**Issue by mckernanin** [woocommerce/woocommerce#20148]
**Describe the bug**
I'm updating product images via the REST API, and I don't see a way to reliably know whether an image is the product image or not.

**To Reproduce**
1. Create a product with no featured image, and 1 image in the product gallery
2. View the API response for this product

**Screenshots**
_Product settings in dashboard_
![Product settings in dashboard](https://user-images.githubusercontent.com/6300047/40279981-b3e9f2ac-5c09-11e8-8810-4ba539ad1d9b.png)

_API response_
![API response](https://user-images.githubusercontent.com/6300047/40279983-bcbf5cd2-5c09-11e8-898a-36e5e70f13d1.png)

**Expected behavior**
There should be a way to know whether the image returned is the product image, or whether it is a gallery item. If there is a way to know this via the product endpoint, I can't figure it out.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

cc/ @adampickering @spencerfinnell

**Comment by mikejolley** [comment]
See https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties and the `Product - Images properties` section. 

> Image position. 0 means that the image is featured.

The image in position 0 is your featured image.

Thanks

**Comment by mckernanin** [comment]
Hey Mike, thanks for the reply. As you can see above, there’s an image in position zero, but it lives in the gallery and is not the featured image.

**Comment by mikejolley** [comment]
I think if you submit that request back, that will change (featured image was missing). Eventually, the admin screen won't show these as two separate panels.

**Comment by ozimovski** [comment]
Hello. 
I have the exactly same problem. I upload a bunch of images for a product and have a position 0 on the first, but it's still isn't shown as the featured image. Did you solve the problem?

**Comment by mansouralex** [comment]
@mikejolley Any way to get around it? I'm facing this issue at the moment.
