### ISSUE TITLE
Customizer error when using WC3.4RC-1 with Bookings 1.11.1

### ISSUE THREAD

**Issue by sailinf** [woocommerce/woocommerce#20157]
**Describe the bug**
Customizer error when using WC3.4RC-1 + 4.9.6 + Booking 1.11.1.  

**To Reproduce**
1. Enable Woocommerce Bookings plugin
2. Go to Customizer
3. Make changes 
4. Click Publish
5. Publish remain active, error message: "Looks like something’s gone wrong. Wait a couple of seconds, and then try again.", changes don't take effect.

No problems with WC3.3.5. No problems if Bookings disable.

Error log:
`2018/05/21 16:04:27 [error] 15#15: *123686 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function is_type() on boolean in /srv/dokkv20test/site/wp-content/plugins/woocommerce-bookings/includes/class-wc-booking-coupon.php:87
Stack trace:
#0 /srv/site/wp-includes/class-wp-hook.php(286): WC_Booking_Coupon->apply_discount(0, Array, Object(WC_Cart))
#1 /srv/site/wp-includes/plugin.php(203): WP_Hook->apply_filters(0, Array)
#2 /srv/site/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(635): apply_filters('woocommerce_get...', 0, Array, Object(WC_Cart))
#3 /srv/site/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(140): WC_Cart_Totals->calculate_item_totals()
#4 /srv/site/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(131): WC_Cart_Totals->calculate()
#5 /srv/site/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1235): WC_Cart_Totals->__construct(Object(WC_Cart))
#6 /srv/site/wp-content/plugins/w" while reading response header from upstream, client: 213.243.183.xxx, server: demo.site, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:20043", host: "demo.site", referrer: "https://demo.site/wp-admin/customize.php?url=https%3A%2F%2Fdemo.site%2F"
`

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/). - tested with TwentySixteen
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by sailinf** [comment]
Hm, actually, it seems to be the opposite. If I add a Bookings product to the cart, there is no error but if the cart is empty, then I get the error?

**Comment by thomas-zg** [comment]
I assume that the automatically added dummy product in the customizer is the cause of the exception. The added product is not a part of the shop, but functions like WC_Cart_Totals->calculate() will be called. Some cart filters are referenced in the the plugins and will throw exceptions because of the dummy product. That's what I can reproduce at the moment.
@mikejolley What is the reason for adding a dummy product in the customizer?

**Comment by kloon** [comment]
The issue is with the bookings extension, they assume that they have a valid product before calling member functions. Because the dummy product does not actually exist in the system it will throw errors when you try and access it like a valid product.

I have opened a PR on the bookings extension which fixes this.

**Comment by thomas-zg** [comment]
@kloon You'll see a number of plugins that will fail because of the dummy product. What is the reason for adding the dummy product and why isn't it referenced in the changelog for 3.4?

**Comment by mikejolley** [comment]
It's so you can preview the checkout page.

**Comment by kloon** [comment]
@thomas-zg as Mike said, this is to preview how the cart and checkout pages will look. Unfortunately we cannot control how plugin developers are coding, but standard practice is to make sure a object actually exists before calling the methods.

If there are any WooCommerce owned extensions which is causing issues we will definitely fix those but cannot help with 3rd party extensions, those you will need to contact the developers to fix it on their side.

**Comment by mikejolley** [comment]
We can mitigate - PR incoming.
