### ISSUE TITLE
WC_Product::is_purchasable() returns false if product is private

### ISSUE THREAD

**Issue by heyitsfranklin** [woocommerce/woocommerce#20153]
If a product's status is set to privately published, the WC_Product::is_purchasable() function returns false.

**To reproduce**
1. Create a new WooCommerce product
2. Set the product's price to any value
3. Publish the product
4. Set the product's status to "Private" and click Save
5. Attempt to add the product in question to your cart
6. Go to your shopping cart
7. A message is displayed which reads "Sorry, your product cannot be purchased"

**Notes**
For some reason, I could only reproduce this issue on mobile devices (Android/iPhone).

**Expected behavior**
A website/business owner may want to have certain products that are exclusive to certain customers. Because of this and because the product is indeed still published, the customer should be allowed to add the product to his/her cart.

**WordPress environment**
WordPress v4.9.5
WooCommerce v3.2.6

**Possible solution**
To fix this issue, I added this to my theme's function.php:
```
add_action( 'woocommerce_is_purchasable', 'purchasable_fix', 10, 2);
function purchasable_fix($is_purchasable, $object) {	
	$statuses = array("publish", "private");
	return ($object->exists() && ( in_array($object->get_status(), $statuses) || current_user_can( 'edit_post', $object->get_id() ) ) && '' !== $object->get_price());
}
```

Original code from is_purchasable() function:
```
public function is_purchasable() {     
    return apply_filters( 'woocommerce_is_purchasable', $this->exists() && ( 'publish' === $this->get_status() || current_user_can( 'edit_post', $this->get_id() ) ) && '' !== $this->get_price(), $this );     
  }   
```

**Comment by kloon** [comment]
Please see https://codex.wordpress.org/Content_Visibility#Private_Content Private content is not meant to be viewed by people without edit_posts permissions. We already cover that in the current code.
