### ISSUE TITLE
Cart widget is shown with inline CSS

### ISSUE THREAD

**Issue by ktmn** [woocommerce/woocommerce#20151]
**Is your feature request related to a problem? Please describe.**
I have a cart widget that I only want to show on large screens. So a CSS breakpoint gives it `display: none`. How ever with the WC JavaScript code it receives inline `display: block` when there are items in the cart, regardless of the screen size.

**Describe the solution you'd like**
Instead of using the jQuery `hide()` and `show()`, it could add `css('display', 'none')` when it needs to be hidden, and `css('display', '')` to remove it when it shouldn't be hidden, leaving the user an option to override it.

**Additional context**
https://github.com/woocommerce/woocommerce/blob/d3b98d88f245814797f7426dccece1cbb623dfcd/assets/js/frontend/cart-fragments.js#L154-L159

**Comment by mikejolley** [comment]
It isn't pretty but you can override with with CSS if really really needed using **shudder**... `!important` 

But even thats not needed if you target the parent DIV element :)`hide_cart_widget_if_empty` is inside. the widget - so just target the parent with your CSS rules.

Thanks

**Comment by ktmn** [comment]
The inline CSS already *is* applied to the parent with the `.closest('.widget_shopping_cart')`, the parent of that contains other widgets as well, so that wouldn't be specific enough. 

But yeah I can figure it out on my end and I can imagine some use cases may actually rely on that inline approach so the `wontfix` is understandable, thanks.
