### ISSUE TITLE
WooCommerce should store products, attributes, tags and categories in separate tables

### ISSUE THREAD

**Issue by lifeforceinst** [woocommerce/woocommerce#20165]
It is known that the WooCommerce roadmap for 2018 included a item called "custom product tables for performance". Which it ti have the aim of improving database design, separation and optimisation.

So not only should WooCommerce products should be stored in a separate WordPress table such as _woocommerce_product rather than _posts table; **please ensure that the following are considered in the design.**

- Products tags should be stored in a separate WordPress table such as _woocommerce_product_tags
- Products attributes should be stored in a separate WordPress table such as _woocommerce_product_attributes.
- Products categories should be stored in a separate WordPress table such as _woocommerce_product_categories rather than in _terms table.
- **Note:** currently if you have a Product category not assigned to any product it is considered orphaned and many database optimisation plugins will remove what appears to be an orphaned entry.  Please ensure the design will work with popular plugs such as wp-sweep.
- All existing WooCommerce product function calls would need to be updated to point to the new structures.
- A function would be necessary to convert the database to the new format were products are stored in separate tables.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce-product-tables-feature-plugin - it's already being considered.
