### ISSUE TITLE
My Account - GDRP self service link

### ISSUE THREAD

**Issue by lifeforceinst** [woocommerce/woocommerce#20166]
GDRP functionality has been added to Wordpress 4.9.6 and WooCommerce 3.4, but this lacks a means for the user to make self-service request.

When a customer logs into an account for WooCommerce they current have a number of menu options which are available, which include items such as Dashboard, Orders, Address, Account details, Logout.

This enhancement request that two  items are added called: Privacy data export and Privacy data erase be added to this menu. 

If a user clicks on either of these options the user should be presented with a confirmation page (which can be customised), a default recommendation for the Privacy data export is :" You have requested that all data which we hold your your account to be made available to you.  Please confirm this request by clicking Yes, if you do not wish to perform this action then click No."

When the user click on Yes, then you should call the WordPress privacy export or privacy erase function respectfully.  For the privacy export, the customer should then be presented with a download link for the resultant export data.

This would then make the export data function to be a self-service function within a WooCommerce enabled shop.

**Comment by mikejolley** [comment]
See https://core.trac.wordpress.org/ticket/43437 - a frontend method is being considered for WP core.
