### ISSUE TITLE
remove the checkout field `billing_email` and checkout with coupon will cause an error

### ISSUE THREAD

**Issue by OoqwqoO** [woocommerce/woocommerce#20178]
**To Reproduce**
1. Use a filter `woocommerce_checkout_fields` to remove the checkout field `billing_email`.
```
add_filter( 'woocommerce_checkout_fields' , 'override_checkout_fields' );
function override_checkout_fields( $fields ) {
	unset( $fields['billing']['billing_email'] );
	return $fields;
}
```
2. And then checkout with coupon.
3. The error `Undefined index: billing_email` will show in log.

**Solution**
check the variable `$posted['billing_email']` in function `check_customer_coupons` in file `includes/class-wc-cart.php`

**Comment by mikejolley** [comment]
I agree the notice could be worked around but checking the posted variable, but removing this field is going to cause lots of other issues. Please don't :)

**Comment by OoqwqoO** [comment]
I have build a WooCommerce website for WeChat mini programm, and it seems no issues without billing email, browse products, add to cart, checkout, and payment are working well.
You can limits coupon usage to a number only based on user ID if billing email is not set.

**Comment by mikejolley** [comment]
It's the after order flow which would be affected i.e. order emails to the purchaser.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20180

**Comment by OoqwqoO** [comment]
Thanks!
