### ISSUE TITLE
Webhooks only ping working

### ISSUE THREAD

**Issue by perotom** [woocommerce/woocommerce#20175]
**Describe the bug**
When I create a webhook i can see the ping event, as stated in the docs, but the hook never gets called again. 

**To Reproduce**
1. Using latest docker compose stack from https://hub.docker.com/_/wordpress/
2. Install WooCommerce (as of writing Version 3.3.5)
3. Create Webhook for "product.created" using "https://webhook.site" as Hooktester.
4. Create product.
5. Don't see any logs and no request at webhook.site.

**Screenshots**
![screen shot 2018-05-23 at 10 03 01](https://user-images.githubusercontent.com/3322872/40411462-d85480d0-5e70-11e8-9530-70883a23cf40.png)
![screen shot 2018-05-23 at 10 05 22](https://user-images.githubusercontent.com/3322872/40411463-d87037a8-5e70-11e8-93ae-1f888a5d5e29.png)

**Expected behavior**
Webhooks needs to appear at  webhook.site.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```

### WordPress Environment ###

Home URL: http://localhost:8080
Site URL: http://localhost:8080
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.5
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.22
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 1.89MB
Database Data Size: 1.02MB
Database Index Size: 0.87MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.38MB + Index: 0.02MB
wp_postmeta: Data: 0.09MB + Index: 0.06MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 16
customize_changeset: 1
page: 8
post: 2
product: 15
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.4
WooCommerce Stripe Gateway: by WooCommerce – 4.1.4
WooCommerce: by Automattic – 3.3.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /?page_id=5
Basket: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My account: #8 - /?page_id=8
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
I tested this with 3.4 RC2 - the webhook fired when I hit 'publish' in WP Admin.

![webhook tester 2018-05-23 11-13-05](https://user-images.githubusercontent.com/90977/40418453-5a7dcc2a-5e7a-11e8-8d6a-ae979dd02848.png)

Consult WC>Status>Logs. Deliveries are there. There may be duplicates (which is fixed in 3.4).

Thanks

**Comment by perotom** [comment]
Tried it with 3.4 RC2 also not working. Do I need to enable something? How do you get it to work with the docker image? Which steps do you do?

Btw: I only see a blank log file:
![screen shot 2018-05-23 at 12 41 08](https://user-images.githubusercontent.com/3322872/40419749-98edac80-5e86-11e8-842d-474045b7c558.png)

**Comment by mikejolley** [comment]
I'm not using docker - I'm using a local install. If there was an issue with the webhook system I'd expect it to happen in any environment?

**Comment by mikejolley** [comment]
Was the ping logged? All requests are logged for me. Is the filesystem read only when using that image?

**Comment by perotom** [comment]
On my local install the ping is not logged but the hook (I am looking at WooCommerce -> Status -> Logs).
When using the image nothing is logged. I can see other db upgrade logs so I think it is writeable. 
Could it possibly be a cron issues?

**Comment by mikejolley** [comment]
Thats possible - this does use cron. 

https://github.com/woocommerce/woocommerce/issues/18003

**Comment by perotom** [comment]
I think i found the bug. I installed WP-Crontrol where i can see the webhooks (but not in the woocommerce logs!). I get the following error with this tool:
```
There was a problem spawning a call to the WP-Cron system on your site. This means WP-Cron events on your site may not work. The problem was: 
cURL error 60: SSL certificate problem: unable to get local issuer certificate
```
This should be logged somehow in the woocommerce logs. Otherwise it is pretty hard to debug.

**Comment by claudiosanches** [comment]
This is a problem in WP-Cron, should be already in the `wp-content/debug.log` or the server logs, since is WordPress that throws it.
We only use https://developer.wordpress.org/reference/functions/wp_schedule_single_event/ and WordPress should handle it later.
