### ISSUE TITLE
Product search in admin fails to find products with apostrophe in title

### ISSUE THREAD

**Issue by maciej-laskowski** [woocommerce/woocommerce#20171]
**Describe the bug**
Product search in admin fails to find products with apostrophe in title. The same search phrase returns correct results in shop search. Similar issue has already been reported as #19346 and fixed but I believe the bug still persist.

**To Reproduce**
1. On fresh WP+WC+Storefront installation create product with an apostrophe in title eg. _D’embruns_
2. In admin products search type _D’embruns_ and click Search
3. No results

**Expected behavior**
The search should find _D’embruns_ product

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by thomas-zg** [comment]
Just checked with 3.4 RC2, the product with an apostrophe will be found. The escaping of the special character in the SQL query is correct. Have you tried the Query Monitor plugin to get the query sent to the database?

**Comment by maciej-laskowski** [comment]
@thomas-zg I have upgraded WC to 3.4 RC2 and the search works correctly. I saw status "merged" in  #19096 and thought it means it has been already shipped with an official version but it is indeed marked as 3.4.0 milestone. 

Please close this ticket, sorry for bothering you.
