### ISSUE TITLE
Regression in native importer?

### ISSUE THREAD

**Issue by EgbertJan** [woocommerce/woocommerce#20186]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Native importer: try to open a CSV file already located on the server (advanced)
2. 
3. 

## Expected/actual behavior

When I follow those steps, I see...
Error: Upload of voorzie een link naar een geldig CSV-bestand. Translation: Upload or supply a link to a valid CSV file.
I was expecting to see...
The next screen with mappings
## Isolating the problem
No error in 3.3.5, introduced with 3.4 today

- [ X] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://speldorado.vandenbussche.nl
Site URL: https://speldorado.vandenbussche.nl
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: ❌ 7.0.30-0ubuntu0.16.04.1 - We raden je aan om PHP-versie 7.2 of hoger te gebruiken voor betere prestaties en beveiliging. Hoe je PHP-versie bijwerken
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.5 - Wij adviseren een minimum MySQL-versie 5.6. Bekijk: WordPress vereisten
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.0
WC Database Prefix: shop_
Totale databasegrootte: 169.96MB
Database datagrootte: 111.34MB
Database index grootte: 58.62MB
shop_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
shop_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
shop_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
shop_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
shop_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
shop_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.02MB
shop_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
shop_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
shop_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
shop_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
shop_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
shop_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
shop_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
shop_woocommerce_log: Data: 0.02MB + Index: 0.02MB
igwidget_global_settings: Data: 0.02MB + Index: 0.00MB
igwidget_widget: Data: 0.05MB + Index: 0.00MB
shop_ariadminer_connections: Data: 0.02MB + Index: 0.00MB
shop_commentmeta: Data: 0.02MB + Index: 0.03MB
shop_comments: Data: 0.02MB + Index: 0.09MB
shop_idealcheckout_settings: Data: 0.02MB + Index: 0.00MB
shop_idealcheckout_ssl: Data: 0.02MB + Index: 0.00MB
shop_idealcheckout_transactions: Data: 0.02MB + Index: 0.00MB
shop_links: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_forms: Data: 0.02MB + Index: 0.00MB
shop_mailpoet_mapping_to_external_entities: Data: 0.06MB + Index: 0.05MB
shop_mailpoet_newsletters: Data: 0.02MB + Index: 0.00MB
shop_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.00MB
shop_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.00MB
shop_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_newsletter_templates: Data: 1.52MB + Index: 0.00MB
shop_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.00MB
shop_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.00MB
shop_mailpoet_segments: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_sending_queues: Data: 0.02MB + Index: 0.00MB
shop_mailpoet_settings: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB
shop_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.05MB
shop_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB
shop_mailpoet_subscribers: Data: 0.09MB + Index: 0.08MB
shop_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB
shop_mailpoet_subscriber_segment: Data: 0.16MB + Index: 0.08MB
shop_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB
shop_options: Data: 3.31MB + Index: 0.09MB
shop_postmeta: Data: 56.14MB + Index: 31.11MB
shop_posts: Data: 15.08MB + Index: 7.58MB
shop_termmeta: Data: 0.08MB + Index: 0.06MB
shop_terms: Data: 0.06MB + Index: 0.03MB
shop_term_relationships: Data: 2.45MB + Index: 1.36MB
shop_term_taxonomy: Data: 0.06MB + Index: 0.06MB
shop_usermeta: Data: 0.06MB + Index: 0.03MB
shop_users: Data: 0.02MB + Index: 0.05MB
shop_wc_download_log: Data: 0.02MB + Index: 0.03MB
shop_wc_webhooks: Data: 0.02MB + Index: 0.02MB
shop_woof_query_cache: Data: 0.02MB + Index: 0.02MB
shop_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB
shop_yith_wcwl: Data: 0.02MB + Index: 0.02MB
shop_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
speldo_art: Data: 8.52MB + Index: 7.22MB
speldo_art_xtr_lvr: Data: 0.06MB + Index: 0.05MB
speldo_category: Data: 0.02MB + Index: 0.00MB
speldo_leveranciers: Data: 0.02MB + Index: 0.00MB
speldo_merken: Data: 0.06MB + Index: 0.00MB
speldo_status: Data: 0.02MB + Index: 0.00MB
speldo_subcategory: Data: 0.02MB + Index: 0.02MB
speldo_transactie: Data: 4.52MB + Index: 0.00MB
speldo_transactie_art: Data: 16.52MB + Index: 8.03MB
speldo_voorraad: Data: 1.52MB + Index: 1.84MB

### Post Type Counts ###

attachment: 13549
custom_css: 2
custom_wishlists: 3
flamingo_contact: 13
flamingo_inbound: 2
mailpoet_page: 1
nav_menu_item: 14
page: 32
post: 4
product: 9425
product_slider: 1
revision: 97
shop_order: 10
stores: 1
tribe_events: 2
tribe_organizer: 1
tribe_rsvp_tickets: 1
tribe_venue: 1
vtprd-rule: 1
wcps: 1
woocarousel: 1
wpcf7_contact_form: 3
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Foutmeldingen zouden niet getoond moeten worden aan bezoekers.

### Active Plugins (32) ###

ARI Adminer: door ARI Soft – 1.1.11
BackWPup: door Inpsyde GmbH – 3.5.1
Contact Form 7: door Takayuki Miyoshi – 5.0.2
Display Posts Shortcode: door Bill Erickson – 2.9.0
Easy WP SMTP: door wpecommerce
alexanderfoxc – 1.3.6

Flamingo: door Takayuki Miyoshi – 1.8
Flexible Shipping: door WP Desk – 2.1.2
IgniteWoo Updater: door IgniteWoo.com – 2.1.11
Image Widget: door Modern Tribe
Inc. – 4.4.7

Instagram Slider Widget: door jetonr – 1.4.3
Kassa: door Dennis Claassens – 1.0
Loco Translate: door Tim Whitlock – 2.1.3
MailPoet 3 (New): door MailPoet – 3.7.3
Mollie Payments for WooCommerce: door Mollie – 3.0.3
Overzicht: door Dennis Claassens – 1.0
Productimport: door Dennis Claassens – 1.0
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 3.0.2
Shortcode Pagination for WooCommerce: door James Kemp – 1.0.10 – Niet getest met de actieve versie van WooCommerce
Speldo Tools: door Egbert Jan van den Bussche – 5.2 – Niet getest met de actieve versie van WooCommerce
The Events Calendar: door Modern Tribe
Inc. – 4.6.16

Theme Customisations: door WooThemes – 1.0.0
TinyMCE Advanced: door Andrew Ozz – 4.7.11
Transacties: door Dennis Claassens – 1.0
Voorraadbeheer: door Dennis Claassens – 1.0
WooCommerce Customizer: door SkyVerge – 2.5.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Menu Extension: door August Infotech – 1.6 – Niet getest met de actieve versie van WooCommerce
WooCommerce Facturen en Pakbonnen afdrukken: door SkyVerge – 3.5.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Shortcodes: door WooThemes
Claudio Sanches – 1.0.0 – Niet getest met de actieve versie van WooCommerce

WooCommerce Wishlists Pro: door Ignitewoo.com – 3.1.17 – Niet getest met de actieve versie van WooCommerce
WooCommerce: door Automattic – 3.4.0
WP Maintenance Mode: door Designmodo – 2.1.2
WP Desk Helper: door WP Desk – 1.4.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
no (no)
not_featured (not_featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
yes (yes)

### WC Pages ###

Winkelbasis: #5 - /winkel/
Winkelmand: #6 - /winkel/winkelwagen/
Afrekenen: #7 - /winkel/afrekenen/
Mijn account: #9 - /winkel/mijn-account/
Algemene voorwaarden: #390404 - /winkel/verkoopvoorwaarden/

### Theme ###

Name: Storefront
Version: 2.3.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by kloon** [comment]
See #20191
