### ISSUE TITLE
Hook request for WC_Discounts::validate_coupon_exists() 

### ISSUE THREAD

**Issue by nubam** [woocommerce/woocommerce#20181]
We need to customize the couponing system a bit, because in our use case a given coupon code should be validated against a web service instead of the native mysql-database. more precisely we have to check if a given code ist valid (via the web service). if it is, we have to create the coupon in the database and set its usage to 1/1 after the order is complete. 

we have tried various existing web hooks and nothing really worked for us. now we came up with a new hook in WC_Discounts::validate_coupon_exists():

```
if ( ! $coupon->get_id() && ! $coupon->get_virtual() ) {
	$coupon = apply_filters('create_coupon_if_not_exists', $coupon);
	if ( ! $coupon->get_id() && ! $coupon->get_virtual() ) {
		/* translators: %s: coupon code */
		throw new Exception( sprintf( __( 'Coupon "%s" does not exist!', 'woocommerce' ), $coupon->get_code() ), 105 );
	}
}
```

i know the code isn´t that nice, especially the second if statement. we are very open to suggestions on  how a functionality like this can be achieved in a more elegant way. 
otherwise we would be very happy if the new hook could be added this way. 

thank you very much for your help!

**Comment by mikejolley** [comment]
I think you can use the `woocommerce_get_shop_coupon_data` hook. This is part of the coupon class. At that point you can either return a coupon object as an array, or create it in the DB.

https://github.com/woocommerce/woocommerce/blob/46e426d45186fc32aee3a031ae8201d5df41925d/includes/class-wc-coupon.php#L90

Thanks
