### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by HypnoAcuDoc** [woocommerce/woocommerce#20189]
**Describe the bug**

This issue began on May 20 2018.

I was simply working on my website and wanted to view a product in the shop, so I attempted to open the site in a new window (Chrome) and received the message in the image below.  {website redirected you too many times.  Try clearing your cookies.  ERR_TOO_MANY_REDIRECTS}

**Screenshots**
![woocommerce problem - may 2018](https://user-images.githubusercontent.com/39575474/40460211-885b8b38-5ed3-11e8-95c3-6cb0c8b6954e.jpg)

I followed instructions to clear cookies - no change.  I cleared browsing history - no change.  I spoke with my hosting provider - they instructed me to clear cookies and restart my computer - no change.  Uninstalled and reinstalled Chrome - no change.

Decided to use Firefox - same problem.  Microsoft Edge - same problem.

Went back to wordpress and began disabling each plugin.  WooCommerce is the culprit.  I changed the theme - three times, using one each from different manufacturers. - no change.

I have followed the instructions on the WooCommerce self-service guide - switched to a default theme (TwentySeventeen); disabled ALL plugins - site works; enable only WooCommerce - redirect error (image above)

As the guide suggests, if the problem still persists, contact a Happiness Engineer to investigate further.  This issue started three days ago.  I did update Wordpress, however that was today.  The problem existed before and after the update.

My host provider has installed Let's Encrypt on this site and other sites of mine.  It was activated several days before this issue started and I have verified the https for my website is active.

The status report suggests the site is not using HTTPS, however it is.
WooCommerce version 3.4.0; no memory issues; no outdated plugins.

**Expected behavior**
The expectation is my website loads in the browser and shows the home page.  (the expected behaviour happens (website loads) when Chrome is Incognito mode only)

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Version: 4.9.6

**WooCommerce > System Status**
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```

![image](https://user-images.githubusercontent.com/39575474/40461372-0f52679c-5ed9-11e8-8ec6-98b2a6a3ca9f.png)

If there are any questions, please feel free to ask.  Thank you for your time from a very frustrated user.

**Comment by kloon** [comment]
Since your host enabled SSL on your site they also probably forced your site to load via HTTPS causing WordPress to go into an infinite loop redirecting from https to http.

You will need to tell WordPress that your site is now HTTPS as the URL set in your settings is still set to HTTP.

You can change this from `Settings -> General` in the WP-Admin. Change the settings `WordPress Address` and `Site Address` to use HTTPS and not HTTP.
