### ISSUE TITLE
Error after refund

### ISSUE THREAD

**Issue by sailinf** [woocommerce/woocommerce#20198]
**Describe the bug**
When testing refund (over Stripe), I get the following error in the error log:
`2018/05/24 13:10:56 [error] 11#11: *144777 FastCGI sent in stderr: "PHP message: id was called incorrectly. Order properties should not be accessed directly. Backtrace: do_action('wp_ajax_woocommerce_refund_line_items'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::refund_line_items, wc_create_refund, do_action('woocommerce_order_fully_refunded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_Refunded_Order->trigger_full, WC_Email_Customer_Refunded_Order->trigger, WC_Email->get_content, WC_Email_Customer_Refunded_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-refunded-order.php'), do_action('woocommerce_email_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails->order_details, wc_get_template, include('/plugins/woocommerce/templates/emails/email-order-details.php'), wc_get_email_order_items, apply_filters('woocommerce_email_order_items_table'), WP_Hook->apply" while reading response header from upstream, client: 86.50.147.xxx, server: dokkv20test.demo.site, request: "POST /wp-admin/admin-ajax.php?lang=fi HTTP/1.1", upstream: "fastcgi://127.0.0.1:20042", host: "demo.site", referrer: "https://demo.site/wp-admin/post.php?post=4475&action=edit"
`

**To Reproduce**
1. Make purchase using stripe
2. Open order
3. Refund using stripe
4. Error in error log

Seems that the refund actually succeeds, haven't figured out yet whether there is some actual problem. No error on Chrome console.

**Screenshots**

**Expected behavior**
No errors generated.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WC 3.4
WP 4.9.6
Stripe 4.1.4
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment]
I moved your other issue. Please report extension issues via https://github.com/woocommerce/woocommerce-gateway-stripe/issues or using the Help Desk - we only handle core bugs here.

Thanks

**Comment by mikejolley** [comment]
No, because core does not do this:

> PHP message: id was called incorrectly. Order properties should not be accessed directly

**Comment by sailinf** [comment]
Same error with BACS and manual refund.

**Comment by mikejolley** [comment]
@sailinf no system status was provided; have you ruled out extensions or not?
