### ISSUE TITLE
Notice: map_meta_cap was called incorrectly after disabling Woo in the "Activity" bar within the Dashboard.

### ISSUE THREAD

**Issue by redlagoon** [woocommerce/woocommerce#20199]
Version of Woo: 
**3.4.0**

Version of WP: 
**4.9.6**

Installed plugins (besides Woo): 
**None.**

Replication: 
**Create any activity on your Woo install that'd show up in the dashboard, then disable Woo.** An example would be leaving a note for the customer in a pending order or just creating a dummy order.

What happens:
I've tested my Woo integration and decided to leave a note for a product that was in the queue.

After I've disabled Woo, these errors pop in the "Activity" tab within the Dashboard:

[https://i.imgur.com/kATDAhM.png](Image of the dump).

But after reviewing a bit, it turns out that every notification has this error.

The full dump:

https://pastebin.com/3r4jT9mw

**_Note: After re-activating the plugin, the issues dissapear, but re-appear as soon as I de-activate again._**

What I expected:
These notifications should be turned invisible upon de-activation of the Woo plugin.

**Comment by mikejolley** [comment]
This is a long time WordPress issue logged here: https://core.trac.wordpress.org/ticket/36208

Thanks
