### ISSUE TITLE
Downloadable products using external URLs are empty.

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#20204]
**Describe the bug**
Downloadable products with external URLS are 0kb after downloading.

**To Reproduce**
1. Create a Downloadable Product
2. Assign external URL to it. 
https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/single.jpg
3. Purchase and attempt to download from My Account

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20205
