### ISSUE TITLE
[bug] "Thank you page" is updating the order status.

### ISSUE THREAD

**Issue by suparday** [woocommerce/woocommerce#20209]
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a new order and the default order status -> "processing"
2. Change the order status to "completed" by admin.
3. User access the thank you page link again and the order status is changed back to "processing".

## Expected/actual behavior

This situation is not happening much but if user book marked the thank you page link, the order status will change back to processing!. and all orders can be messed up by bad users.

link ref:
https://xxx.com/checkout/order-received/1234/?key=wc_order_xxxxxxxxxxx

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

**Comment by mikejolley** [comment]
This is caused by a badly coded payment gateway plugin. Not sure what you're running because you didn't include status report, but I'm unable to replicate with BACS.

If it's a core gateway let me know and I'll investigate. Otherwise, report to the developer.

Thanks

**Comment by suparday** [comment]
Hi, 
I am testing this with default COD gateway..

Below is my status report.

`
### WordPress Environment ###

Home URL: 
Site URL: 
WC Version: 3.3.5
Log Directory Writable: ✔
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: zh_TW

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.17
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Post Type Counts ###

acf: 8
attachment: 74
blocks: 9
customize_changeset: 37
dc_commission: 37
nav_menu_item: 27
page: 38
post: 2
postman_sent_mail: 258
product: 75
product_variation: 2
revision: 394
shop_order: 69
shop_order_refund: 6
shop_order_vendor: 2
tablepress_table: 1
vcv_templates: 9
wc_custom_statuses: 3
wc_order_status: 10
woo_mb_template: 18
wpcf7_contact_form: 5
xlwcty_thankyou: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (42) ###

Gravity Forms: by rocketgenius – 2.2.4.2
404 to 301: by Joel James – 2.3.3
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.2 – Not tested with the active version of WooCommerce
WooCommerce Role Based Methods: by WPBackOffice – 2.1.2 – Not tested with the active version of WooCommerce
Advanced Custom Fields: by Elliot Condon – 4.4.12
WC Marketplace: by WC Marketplace
The Grey Parrots – 3.0.5

Disable cart page for WooCommerce: by Code4Life – 1.2.2
Display Order Details for WooCommerce: by Pinal Shah – 1.0 – Not tested with the active version of WooCommerce
Duplicate Post: by Enrico Battocchi – 3.2.2
WooCommerce Group Buy: by wpgenie – 1.1.8 – Not tested with the active version of WooCommerce
LH Archived Post Status: by Peter Shaw – 2.20
Meta Box: by MetaBox.io – 4.14.5
Email Verification / SMS verification / Mobile Verification: by miniOrange – 3.2.46
Nav Menu Roles: by Kathy Darling – 1.9.1
Post Expirator: by Aaron Axelsen – 2.3.1.1
Post SMTP: by 原開發者為 Jason Hendriks，目前由 Yehuda Hassine 接手 – 1.8.9
Redirection: by John Godley – 3.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
SG Optimizer: by SiteGround – 4.0.5
WPML Multilingual CMS: by OnTheGoSystems – 3.6.2
Facebook Messenger (Live Chat): by Leszek Pomianowski – 1.3.6
Tesla Login Customizer: by TeslaThemes – 1.3.4
Two Factor Authentication: by David Nutbourne + David Anderson
original plugin by Oskar Hane – 1.2.35 – Not tested with the active version of WooCommerce

User Role Editor: by Vladimir Garagulya – 4.40.3
WooCommerce Frontend Manager - Ultimate: by WC Lovers – 4.0.8
WooCommerce Frontend Manager: by WC Lovers – 4.0.8
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.4
WooCommerce Stripe Gateway: by WooCommerce – 3.2.2 – Not tested with the active version of WooCommerce
WooCommerce Order Status Manager: by WooThemes / SkyVerge – 1.6.0 – 1.9.2 is available – Not tested with the active version of WooCommerce
WooCommerce PDF Invoice: by RightPress – 3.1.5 – Not tested with the active version of WooCommerce
Woocommerce Payment Gateway Per Product: by Dreamfox Media – 2.5.1
WooCommerce Order Status & Actions Manager |  VestaThemes.com: by Actuality Extensions – 2.2.8 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.5 – 3.4.0 is available
WooCommerce Email Customizer with Drag and Drop Email Builder |  VestaThemes.com: by Flycart Technologies LLP – 1.4.27 – Not tested with the active version of WooCommerce
WooSidebars: by WooThemes – 1.4.3
Wordfence Security: by Wordfence – 7.1.4
WP Admin UI Customize: by gqevu6bsiz – 1.5.11
WP All Export Pro: by Soflyy – 1.5.2
wpDataTables: by TMS-Plugins – 2.1
WPML String Translation: by OnTheGoSystems – 2.5.1
YITH Custom Thank You Page for Woocommerce: by YITHEMES – 1.0.5
YITH WooCommerce Wishlist: by YITHEMES – 2.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: MOP (MOP $)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
groupbuy (groupbuy)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #82 - /all-courses/
Cart: #83 - /cart/
Checkout: #84 - /checkout/
My account: #85 - /my-account/
Terms and conditions: #510 - /terms/

### Theme ###

Name: Flatsome
Version: 3.5.1
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/emails/customer-completed-order.php
flatsome/woocommerce/emails/customer-on-hold-order.php
flatsome/woocommerce/emails/customer-processing-order.php
flatsome/woocommerce/emails/email-order-details.php version - is out of date. The core version is 3.3.1
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php version 3.1.0 is out of date. The core version is 3.3.2
flatsome/woocommerce/single-product/product-thumbnails.php version 3.1.0 is out of date. The core version is 3.3.2
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`

**Comment by suparday** [comment]
I have tried to install the YITH thank you page plugin and the issue is fixed afterward. do you think is some of my plugin of theme causing that issue?

**Comment by mikejolley** [comment]
I don't know which extension would do it - you'd need to rule them out.
