### ISSUE TITLE
Privacy: Make scope of exporter and erasers clearer with more detailed friendly names

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#20218]
The privacy tools added in WooCommerce 3.4 included integration with the new core WordPress (4.9.6) personal data exporters and erasers. Unfortunately, they didn't include the "WooCommerce" plugin name, so it could be hard to know which plugin provided "Customer Data" especially when we start displaying the friendly names to administrators as part of the export and erasure process ( see https://core.trac.wordpress.org/ticket/43938 )

If we were to show the friendly names to an admin today, for example, this is what they'd see:

<img width="663" alt="screen shot 2018-05-24 at 12 49 03 pm" src="https://user-images.githubusercontent.com/1595739/40510242-e70c9884-5f50-11e8-84c2-6f96aa143cac.png">

So, I'm recommending the following changes in the friendly names in includes/class-wc-privacy.php

Customer Data -> WooCommerce Customer Data (Core Data Only)
Customer Orders -> WooCommerce Customer Orders (Core Data Only)
Customer Downloads -> WooCommerce Customer Downloads (Core Data Only)
Customer Tokens -> WooCommerce Customer Tokens (Core Data Only)

Since WooCommerce is commonly "extended" by other plugins that may also collect additional customer data, I recommend we add "Core Data Only" too to help make it clear that the exporter/erasure is only dealing with the customer data that WooCommerce collects.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20219
