### ISSUE TITLE
Edit Address: Select2/selectWoo dropdowns not formatting/styled correctly?

### ISSUE THREAD

**Issue by thesublimeobject** [woocommerce/woocommerce#20216]
**Describe the bug**

i have noticed this on a couple of different pages, but the only one that seems to be causing real issues it the page, myaccount => edit address (billing && shipping). everything else on the page seems fine, and the dropdown functionality for country/state _technically_ do work, but they're not styled at all. i would expect them to be [styled somewhat similarly to the default on select2's website](https://select2.org/appearance); instead they are just completely unformatted: no border, no arrow, just plain black text, which when clicked shows the appropriate states, but with no background, no scrollbar, no hover/focus states, etc. all of the select2 classes are there, and _some_ styles of some sort are being displayed, just not very much, seemingly. i screenshotted what i am seeing below.

i have also spend a _lot_ of time tracking down where all of the variables and styles in this file are coming from, including making sure there aren't any custom files overwriting anything (i inherited this site from someone else). as far as i can tell, there's nothing overwriting it. i also disabled most of my plugins that have anything to do with woocommerce even remotely. the only ones that i left on were like ACF and a DB migration plugin.

**To Reproduce**
not 100% sure if this can be easily produced, or if, possibly, this is just what i'm supposed to be seeing and i have to style it myself?—i feel like the default styling should be a little bit more robust. when i tried to style is myself, it was pretty difficult to do quickly and efficiently. 

**Screenshots**
<img width="1273" alt="screen shot 2018-05-24 at 2 03 16 pm" src="https://user-images.githubusercontent.com/3731270/40503207-4efc1a82-5f5b-11e8-9126-f8bce2ff7fd7.png">

**Expected behavior**
as explained above, i would expect the dropdowns to be styled in some kind of default way, which while not extremely fancy, would at least meet the bare minimum.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [?] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: //localhost:3000
Site URL: //localhost:3000
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 7.1.12 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 138.20MB
Database Data Size: 84.20MB
Database Index Size: 54.00MB
wp_woocommerce_sessions: Data: 0.25MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.45MB + Index: 0.17MB
wp_woocommerce_order_itemmeta: Data: 4.52MB + Index: 4.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_2_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_2_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_2_pmxi_imports: Data: 0.02MB + Index: 0.00MB
wp_2_pmxi_posts: Data: 0.02MB + Index: 0.00MB
wp_2_pmxi_templates: Data: 0.02MB + Index: 0.00MB
wp_3_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_3_comments: Data: 0.02MB + Index: 0.08MB
wp_3_links: Data: 0.02MB + Index: 0.02MB
wp_3_options: Data: 0.22MB + Index: 0.05MB
wp_3_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_3_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_3_pmxi_imports: Data: 0.02MB + Index: 0.00MB
wp_3_pmxi_posts: Data: 0.02MB + Index: 0.00MB
wp_3_pmxi_templates: Data: 0.02MB + Index: 0.00MB
wp_3_postmeta: Data: 1.52MB + Index: 0.45MB
wp_3_posts: Data: 0.13MB + Index: 0.06MB
wp_3_termmeta: Data: 0.02MB + Index: 0.03MB
wp_3_terms: Data: 0.02MB + Index: 0.03MB
wp_3_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_3_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_3_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_3_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_3_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_3_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_3_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_3_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_3_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_3_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_blogs: Data: 0.02MB + Index: 0.03MB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.20MB + Index: 0.28MB
wp_itsec_lockouts: Data: 0.06MB + Index: 0.08MB
wp_itsec_log: Data: 0.52MB + Index: 0.19MB
wp_itsec_temp: Data: 0.06MB + Index: 0.06MB
wp_iwp_backup_status: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mail_bank: Data: 0.02MB + Index: 0.00MB
wp_mail_bank_email_logs: Data: 13.52MB + Index: 0.00MB
wp_mail_bank_licensing: Data: 0.02MB + Index: 0.00MB
wp_mail_bank_meta: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.52MB + Index: 0.14MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.45MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.09MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.09MB + Index: 0.00MB
wp_postmeta: Data: 32.56MB + Index: 30.13MB
wp_posts: Data: 3.52MB + Index: 2.70MB
wp_registration_log: Data: 0.02MB + Index: 0.02MB
wp_saved_products: Data: 0.13MB + Index: 0.00MB
wp_saved_rugs: Data: 2.52MB + Index: 0.08MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_site: Data: 0.02MB + Index: 0.02MB
wp_sitemeta: Data: 1.52MB + Index: 0.03MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.08MB + Index: 0.03MB
wp_term_relationships: Data: 0.31MB + Index: 0.28MB
wp_term_taxonomy: Data: 0.08MB + Index: 0.06MB
wp_usermeta: Data: 12.52MB + Index: 13.02MB
wp_users: Data: 1.52MB + Index: 0.91MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpml_mails: Data: 3.52MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.13MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 127
acf-field-group: 16
attachment: 4025
border_collections: 13
borders: 240
collections: 117
fibers: 877
iwp_log: 20
nav_menu_item: 15
page: 46
post: 1
postman_sent_mail: 1
product: 359
product_variation: 70
revision: 4704
shop_order: 910
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn & contributors – 3.0.1
Advanced Custom Fields Pro: by elliot condon – 5.2.7
Advanced Custom Fields: by Elliot Condon – 4.4.12
WooCommerce: by Automattic – 3.4.0
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.9
WP Migrate DB Pro: by Delicious Brains – 1.8.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page ID is set
but the page does not exist

Cart: #4506 - /order-samples/
Checkout: #4933 - /complete-order/
My account: #3344 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Fibreworks
Version: 1.0
Author URL: http://jumpdigitalagency.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: fibreworks/woocommerce/archive-product.php
fibreworks/woocommerce/auth/footer.php
fibreworks/woocommerce/auth/form-grant-access.php
fibreworks/woocommerce/auth/form-login.php
fibreworks/woocommerce/auth/header.php
fibreworks/woocommerce/cart/cart-empty.php
fibreworks/woocommerce/cart/cart-item-data.php
fibreworks/woocommerce/cart/cart-shipping.php
fibreworks/woocommerce/cart/cart-totals.php
fibreworks/woocommerce/cart/cart.php
fibreworks/woocommerce/cart/cross-sells.php
fibreworks/woocommerce/cart/mini-cart.php
fibreworks/woocommerce/cart/proceed-to-checkout-button.php
fibreworks/woocommerce/cart/shipping-calculator.php
fibreworks/woocommerce/checkout/cart-errors.php
fibreworks/woocommerce/checkout/form-billing.php
fibreworks/woocommerce/checkout/form-checkout.php
fibreworks/woocommerce/checkout/form-coupon.php
fibreworks/woocommerce/checkout/form-login.php
fibreworks/woocommerce/checkout/form-pay.php
fibreworks/woocommerce/checkout/form-shipping.php
fibreworks/woocommerce/checkout/order-receipt.php
fibreworks/woocommerce/checkout/payment-method.php
fibreworks/woocommerce/checkout/payment.php
fibreworks/woocommerce/checkout/review-order.php
fibreworks/woocommerce/checkout/terms.php
fibreworks/woocommerce/checkout/thankyou.php
fibreworks/woocommerce/content-product.php
fibreworks/woocommerce/content-product_cat.php
fibreworks/woocommerce/content-single-product.php
fibreworks/woocommerce/content-widget-product.php
fibreworks/woocommerce/content-widget-reviews.php
fibreworks/woocommerce/emails/admin-cancelled-order.php
fibreworks/woocommerce/emails/admin-failed-order.php
fibreworks/woocommerce/emails/admin-new-order.php
fibreworks/woocommerce/emails/customer-completed-order.php
fibreworks/woocommerce/emails/customer-invoice.php
fibreworks/woocommerce/emails/customer-new-account.php
fibreworks/woocommerce/emails/customer-note.php
fibreworks/woocommerce/emails/customer-on-hold-order.php
fibreworks/woocommerce/emails/customer-processing-order.php
fibreworks/woocommerce/emails/customer-refunded-order.php
fibreworks/woocommerce/emails/customer-reset-password.php
fibreworks/woocommerce/emails/email-addresses.php
fibreworks/woocommerce/emails/email-customer-details.php
fibreworks/woocommerce/emails/email-downloads.php
fibreworks/woocommerce/emails/email-footer.php
fibreworks/woocommerce/emails/email-header.php
fibreworks/woocommerce/emails/email-order-details.php
fibreworks/woocommerce/emails/email-order-items.php
fibreworks/woocommerce/emails/email-styles.php
fibreworks/woocommerce/emails/plain/admin-cancelled-order.php
fibreworks/woocommerce/emails/plain/admin-failed-order.php
fibreworks/woocommerce/emails/plain/admin-new-order.php
fibreworks/woocommerce/emails/plain/customer-completed-order.php
fibreworks/woocommerce/emails/plain/customer-invoice.php
fibreworks/woocommerce/emails/plain/customer-new-account.php
fibreworks/woocommerce/emails/plain/customer-note.php
fibreworks/woocommerce/emails/plain/customer-on-hold-order.php
fibreworks/woocommerce/emails/plain/customer-processing-order.php
fibreworks/woocommerce/emails/plain/customer-refunded-order.php
fibreworks/woocommerce/emails/plain/customer-reset-password.php
fibreworks/woocommerce/emails/plain/email-addresses.php
fibreworks/woocommerce/emails/plain/email-customer-details.php
fibreworks/woocommerce/emails/plain/email-downloads.php
fibreworks/woocommerce/emails/plain/email-order-details.php
fibreworks/woocommerce/emails/plain/email-order-items.php
fibreworks/woocommerce/global/breadcrumb.php
fibreworks/woocommerce/global/form-login.php
fibreworks/woocommerce/global/quantity-input.php
fibreworks/woocommerce/global/sidebar.php
fibreworks/woocommerce/global/wrapper-end.php
fibreworks/woocommerce/global/wrapper-start.php
fibreworks/woocommerce/loop/add-to-cart.php
fibreworks/woocommerce/loop/loop-end.php
fibreworks/woocommerce/loop/loop-start.php
fibreworks/woocommerce/loop/no-products-found.php
fibreworks/woocommerce/loop/orderby.php
fibreworks/woocommerce/loop/pagination.php
fibreworks/woocommerce/loop/price.php
fibreworks/woocommerce/loop/rating.php
fibreworks/woocommerce/loop/result-count.php
fibreworks/woocommerce/loop/sale-flash.php
fibreworks/woocommerce/myaccount/dashboard.php
fibreworks/woocommerce/myaccount/downloads.php
fibreworks/woocommerce/myaccount/form-add-payment-method.php
fibreworks/woocommerce/myaccount/form-edit-account.php
fibreworks/woocommerce/myaccount/form-edit-address.php
fibreworks/woocommerce/myaccount/form-login.php
fibreworks/woocommerce/myaccount/form-lost-password.php
fibreworks/woocommerce/myaccount/form-reset-password.php
fibreworks/woocommerce/myaccount/lost-password-confirmation.php
fibreworks/woocommerce/myaccount/my-account.php
fibreworks/woocommerce/myaccount/my-address.php
fibreworks/woocommerce/myaccount/my-downloads.php
fibreworks/woocommerce/myaccount/my-orders.php
fibreworks/woocommerce/myaccount/navigation.php
fibreworks/woocommerce/myaccount/orders.php
fibreworks/woocommerce/myaccount/payment-methods.php
fibreworks/woocommerce/myaccount/view-order.php
fibreworks/woocommerce/notices/error.php
fibreworks/woocommerce/notices/notice.php
fibreworks/woocommerce/notices/success.php
fibreworks/woocommerce/order/form-tracking.php
fibreworks/woocommerce/order/order-again.php
fibreworks/woocommerce/order/order-details-customer.php
fibreworks/woocommerce/order/order-details-item.php
fibreworks/woocommerce/order/order-details.php
fibreworks/woocommerce/order/order-downloads.php
fibreworks/woocommerce/order/tracking.php
fibreworks/woocommerce/product-searchform.php
fibreworks/woocommerce/single-product/add-to-cart/external.php
fibreworks/woocommerce/single-product/add-to-cart/grouped.php
fibreworks/woocommerce/single-product/add-to-cart/simple.php
fibreworks/woocommerce/single-product/add-to-cart/variable.php
fibreworks/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
fibreworks/woocommerce/single-product/add-to-cart/variation.php
fibreworks/woocommerce/single-product/meta.php
fibreworks/woocommerce/single-product/photoswipe.php
fibreworks/woocommerce/single-product/price.php
fibreworks/woocommerce/single-product/product-attributes.php
fibreworks/woocommerce/single-product/product-image.php
fibreworks/woocommerce/single-product/product-thumbnails.php
fibreworks/woocommerce/single-product/rating.php
fibreworks/woocommerce/single-product/related.php
fibreworks/woocommerce/single-product/review-meta.php
fibreworks/woocommerce/single-product/review-rating.php
fibreworks/woocommerce/single-product/review.php
fibreworks/woocommerce/single-product/sale-flash.php
fibreworks/woocommerce/single-product/share.php
fibreworks/woocommerce/single-product/short-description.php
fibreworks/woocommerce/single-product/stock.php
fibreworks/woocommerce/single-product/tabs/additional-information.php
fibreworks/woocommerce/single-product/tabs/description.php
fibreworks/woocommerce/single-product/tabs/tabs.php
fibreworks/woocommerce/single-product/title.php
fibreworks/woocommerce/single-product/up-sells.php
fibreworks/woocommerce/single-product-reviews.php
fibreworks/woocommerce/single-product.php
fibreworks/woocommerce/taxonomy-product_cat.php
fibreworks/woocommerce/taxonomy-product_tag.php
`
</details>

**Comment by WPprodigy** [comment]
> To Reproduce
> not 100% sure if this can be easily produced, or if, possibly, this is just what i'm supposed to be seeing and i have to style it myself?

This is very likely a problem/conflict coming from your theme or another plugin.

Temporarily switch back to the WordPress Twenty Seventeen Theme and disable all plugins except for WooCommerce.  Then test again to see if the problem still occurs. If the above resolves the issue, then re-enable features one at a time until you find the one that's causing the conflict.

**Comment by mikejolley** [comment]
If you want to include these styles in a custom theme that is not using our CSS files, copy https://github.com/woocommerce/woocommerce/blob/master/assets/css/select2.css to it :)

Thanks

**Comment by thesublimeobject** [comment]
@mikejolley i'm actually just getting back around to this after a few other more important things. that CSS update worked great; thank you so much!—i had been messing with this for a couple of hours this morning. 

**FIX**
for anyone who has this issue in the future, my issue was that ACF has it's _own_ select2 styling that was overriding the front-end styles that are included with woocommerce. i didn't expect this at all, but didn't figure out what was going on until i dug in really deep.
