### ISSUE TITLE
incorrect notice: MySQL version: 5.5.5 in system status page

### ISSUE THREAD

**Issue by TomasHurtz** [woocommerce/woocommerce#20227]
I see this has been raised previously and was closed as wontfix...

I have the wrong info showing also in the system status report page.  So what is the resolution?  What does the host must do ?

https://github.com/woocommerce/woocommerce/issues/11117

Wordpress: Version 4.9.6
Woocommerce: Version 3.4.0
10.1.33-MariaDB
PHP v 7.2

Thank you

**Comment by bondimedical3** [comment]
I am having the same problem. Just upgraded to PHP 7.2 and am using MariaDB 10.1 - see screenshot

![woocommerce](https://user-images.githubusercontent.com/10808588/40532256-32b1a2a6-6042-11e8-9361-e88b81308d64.jpg)

**Comment by mikejolley** [comment]
WPDB has an `is_mysql` method which we're using to only show version information when present. The hosts dropin for mariadb likely needs to set that to false https://core.trac.wordpress.org/changeset/34655

This is in WooCommerce:

`'mysql_version'             => ( ! empty( $wpdb->is_mysql ) ? $wpdb->db_version() : '' ),`

We can workaround it but it's not critical and won't affect functionality.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20231
