### ISSUE TITLE
Product Categories not visible after woocommerce 3.4.0 update

### ISSUE THREAD

**Issue by asmbrw** [woocommerce/woocommerce#20225]
product categories did not show after recent woocommerce update. in my website i have selected "Only show children of the current category" in category widget and this widget is not visible.

**Comment by mikejolley** [comment]
Seems fine:

![slack - a8c 2018-05-25 12-19-10](https://user-images.githubusercontent.com/90977/40541944-da6060c8-6015-11e8-9aa6-b6d3bbcb92e2.png)

Would need more details/steps to reproduce, or you can post on the helpdesk. I'm unable to replicate an issue given the instructions you provided.

Thanks
