### ISSUE TITLE
 PHP Notice:  Undefined property: stdClass::$plugin

### ISSUE THREAD

**Issue by AiratHalitov** [woocommerce/woocommerce#20228]
PHP Notice in `WP_DEBUG` mode:

```
PHP Notice:  Undefined property: stdClass::$plugin in /my_site/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1931
```

### Configuration:
* WooCommerce 3.4.0
* WordPress 4.9.6
* PHP 7.1.17-1+ubuntu16.04.1+deb.sury.org+1

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20234
