### ISSUE TITLE
Internationalization in Payment Gateways

### ISSUE THREAD

**Issue by dcolter** [woocommerce/woocommerce#20245]
**Describe the bug**
The payment gateways contained within the &lt;ul class="wc_payment_method  ..."> are not being translated from English.  The WooCommerce > Settings > Payments - BACS and PayPal methods (perhaps more) have Title, Description and Instructions in English, that are not being translated to the site's set language.  (Note: BACS was manually entered in Admin in Portuguese.)

**To Reproduce**
1. Add and item to the cart
2. Go to Checkout
3. See the oversight in the payment methods

**Screenshots**

With normal theme.  Original discovered behavior.  The next 2 screenshots were taken at the same time.  BACS admin has Portuguese in title & description.  PayPal admin has English.
<img width="527" alt="translation bacs" src="https://user-images.githubusercontent.com/3046325/40555980-ec6e56aa-6018-11e8-932f-4c51b49fbd4f.png">
<img width="529" alt="translation paypal" src="https://user-images.githubusercontent.com/3046325/40555988-f4afae2c-6018-11e8-8fc3-b5425382fc13.png">

With only the WooCommerce (Storefront) theme active
<img width="320" alt="storefront - bacs payment method" src="https://user-images.githubusercontent.com/3046325/40557473-3c77672c-601e-11e8-947e-8f2fd85457bb.png">
<img width="318" alt="storefront - paypal payment method" src="https://user-images.githubusercontent.com/3046325/40557409-0e5d4e9c-601e-11e8-9fb9-eae51bce143e.png">

**Expected behavior**

I expected the translation of these elements to be done to the site's set language (pt_BR). 

**Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

WC Version: 3.4.0
WP Version: 4.9.6
WP Multisite: –
Language: pt_BR

### Active Plugins (1) ###
WooCommerce: by Automattic – 3.4.0

### Theme ###
Name: Storefront
Version: 2.3.1

**Comment by mikejolley** [comment]
Hi

Strings which are manually saved/entered by the admin do not get translated. The default strings do, so the version you save/start from is translated.

You need to edit them in the admin area. This is not a bug.

Thanks

**Comment by dcolter** [comment]
@mikejolley This may have been closed too quickly.  Please consider taking a second look and reopening this issue or helping me see this deeper. 

The functionality I described above came "out-of-the-box".  After the installation of Woocommerce, with the site language in pt_BR, the **payment methods were not translated on the front-end** (everything else is).   I modified the Payments > BACS admin page in an effort to troubleshoot this on my own.  Currently, there are translation errors in both the Admin and front-end, in text that is not editable (see attached screenshots - red boxes highlight non-translation).  Granted, I am a novice with Woocommerce and translation.  I cannot fully grasp all the ins-and-outs of these subjects.  As you may have noticed, the solution you suggested did not help my grasp of the subject.

> You need to edit them in the admin area. This is not a bug.

If I edit them in the admin area, what language should they be in and will they be translated to all of the sites languages?

<img width="706" alt="paypal pt 1" src="https://user-images.githubusercontent.com/3046325/40659754-2a17f022-631d-11e8-951e-479c98b62d6a.png">
continuation of the PayPal payment method settings:
<img width="864" alt="paypal pt 2" src="https://user-images.githubusercontent.com/3046325/40659756-2a28d34c-631d-11e8-97c8-e01efb48a500.png">
<img width="712" alt="bacs pt 1" src="https://user-images.githubusercontent.com/3046325/40659757-2a392198-631d-11e8-9b9b-5e1f7fbc7b8f.png">
<img width="686" alt="payments - site frontend" src="https://user-images.githubusercontent.com/3046325/40659758-2a46ad5e-631d-11e8-9f0d-9e5d4c4a7785.png">

**Comment by mikejolley** [comment]
> Will they be translated to all of the site's languages?

You should translate into the language you want them to appear on the frontend. If your admin language differs from the frontend language, you may need to 'translate' this initially because the default text will be in your admin language.

**Comment by dcolter** [comment]
@mikejolley Thank you for your reply.   Ok.  I will "set the initial translations".   This must also be the case for Privacy Policy statements.   Wouldn't it be expected for Woocommerce to do this on it's own?   

In any case, there are still several places where I can't change language of text in the admin and front end.  To summarize there:

1. Payment and Account & Privacy tab titles (admin)
2. Description underneath the payment method title (admin)

Here is another image from the admin panel showing the mixing of English surrounded by Portuguese:

<img width="793" alt="woocommerce general" src="https://user-images.githubusercontent.com/3046325/40663190-28645ca8-6326-11e8-8dab-add207e84d1e.png">

These are the correct behavior?

**Comment by mikejolley** [comment]
Those are missing translations in the Portuguese translation files. 

https://docs.woocommerce.com/document/woocommerce-localization/
