### ISSUE TITLE
 Error in address-i18n.js file

### ISSUE THREAD

**Issue by sajusajeer** [woocommerce/woocommerce#20248]
I believe that there is an issue in the function "**filed_is_required**" from **address-i18n.js** file. 

The condition should be `if ( field.find( ‘label .optional’ ).length === 0 )` instead of `if ( field.find( ‘label .required’ ).length === 0 )` in the else part of the if condition (line number 24). This issue caused to display the "**(optional)**" text multiple times in few cases.

Below is the function I am referring to,

`function field_is_required( field, is_required ) {
	if ( is_required ) {
		field.find( 'label .optional' ).remove();
		field.addClass( 'validate-required' );

		if ( field.find( 'label .required' ).length === 0 ) {
			field.find( 'label' ).append( '&nbsp;<abbr class="required" title="' + wc_address_i18n_params.i18n_required_text + '">*</abbr>' );
		}
	} else {
		field.find( 'label .required' ).remove();
		field.removeClass( 'validate-required' );

		if ( field.find( 'label .required' ).length === 0 ) {
			field.find( 'label' ).append( '&nbsp;<span class="optional">(' + wc_address_i18n_params.i18n_optional_text + ')</span>' );
		}
	}
}`

Hope it is clear.

**Comment by mikejolley** [comment]
Thanks. This is fixed in master and will be in 3.4.1 next week.
