### ISSUE TITLE
REST API v3

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#20243]
It's time to start developing the third version of our REST API.

Some of the work has been started in a [feature plugin](https://github.com/woocommerce/wc-api-dev), all code as been merged in #20116

Steps:

- [x] Merge #20116
- [ ] Fix opened issues
- [x] Review current schemas

**Comment by pmgarman** [comment]
I can't find anything in docs about this being a thing, so, if it's not already possible even with read only access can we have a method of self revoking a key?

**Comment by kevin25** [comment]
This must have Tracking API either. Please support it.

**Comment by claudiosanches** [comment]
See #20111
