### ISSUE TITLE
Setup wizard shipping failing html5 validation

### ISSUE THREAD

**Issue by digitalchild** [woocommerce/woocommerce#20252]
**Describe the bug**

When configuring a new WooCommerce install the shipping page won't continue unless you add a value into the "Locations not covered by your other zones" even when this is disabled. 

Chrome - Version 66.0.3359.181 (Official Build) (64-bit) - Fails validation 

Does not occur in Firefox 60.0.1 (64-bit)  

**To Reproduce**
1. When installing WooCommerce 3.4 for the first time, enter the setup wizard
2. Once on the shipping screen, disable locations not covered and then click continue
3. Validation error shows. 

**Screenshots**

![woocommerce_ _setup_wizard](https://user-images.githubusercontent.com/909468/40573062-6c462fca-60e5-11e8-9c42-d4ab3933891e.png)

**Expected behavior**
If the shipping zone is disabled, the field should also be disabled to allow setup wizard to continue. Only happens in Google Chrome on Mac 

**Isolating the problem (mark completed items with an [x]):**
- [ X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress 4.9.6
WooCommerce 3.4.0 
Storefront 2.3.1

```
```

**Comment by kloon** [comment]
See #20269
