### ISSUE TITLE
Externally hosted files won't download

### ISSUE THREAD

**Issue by rwebster85** [woocommerce/woocommerce#20254]
Downloadable files for products that are hosted elsewhere and not uploading via WP do not work. The downloaded file ends up being 0 bytes and won't open. I have tried using a file hosted on my Dropbox account as well as through one of my domains.

My Free Downloads plugin has the same issue, because it uses the default WooCommerce download functions and actions.

**To Reproduce**
1. Use an externally hosted file as your file url
2. Attempt to download the file from your account page.

**Expected behavior**
External files used to work fine in the previous version of WooCommerce. They would download ok as though they were uploaded to the WP site itself.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://chloecss.com/woo
Site URL: https://chloecss.com/woo
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.5
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.0
WC Database Prefix: wpbp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 2.59MB
Database Data Size: 1.66MB
Database Index Size: 0.93MB
wpbp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wpbp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpbp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpbp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpbp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpbp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpbp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpbp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpbp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpbp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpbp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpbp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpbp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpbp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpbp_commentmeta: Data: 0.02MB + Index: 0.03MB
wpbp_comments: Data: 0.02MB + Index: 0.08MB
wpbp_links: Data: 0.02MB + Index: 0.02MB
wpbp_options: Data: 1.03MB + Index: 0.05MB
wpbp_postmeta: Data: 0.08MB + Index: 0.09MB
wpbp_posts: Data: 0.05MB + Index: 0.06MB
wpbp_termmeta: Data: 0.02MB + Index: 0.03MB
wpbp_terms: Data: 0.02MB + Index: 0.03MB
wpbp_term_relationships: Data: 0.02MB + Index: 0.02MB
wpbp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpbp_usermeta: Data: 0.02MB + Index: 0.03MB
wpbp_users: Data: 0.02MB + Index: 0.05MB
wpbp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpbp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 5
page: 6
post: 2
product: 3
revision: 8
shop_order: 1
somdn_tracked: 88
somwoos3_product: 1
somwoos3_tracked: 1
wc_membership_plan: 1
wc_user_membership: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Boutique
Version: 2.0.14
Author URL: http://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.3.1
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by WPprodigy** [comment]
See https://github.com/woocommerce/woocommerce/issues/20204

Will be fixed in next update.

**Comment by rwebster85** [comment]
Thanks mate.

**Comment by marbetschar** [comment]
Same issue here

**Comment by marbetschar** [comment]
Any ETA when the fix will be available?

**Comment by WPprodigy** [comment]
Fix is available now if you want to hot patch it. I do not know the eta on the next official release though.

**Comment by mikejolley** [comment]
Tuesday.
