### ISSUE TITLE
Allow Customizer Defaults Filtering

### ISSUE THREAD

**Issue by cjkoepke** [woocommerce/woocommerce#20259]
**Is your feature request related to a problem? Please describe.**
The main problem I'm dealing with is in regards to theme development. If I want to set the cropping ratio for the Customizer to something other than `1:1`, there is no way to filter this default (unless I'm wrong, but I have found no documentation or source code hinting at that ability).

**Describe the solution you'd like**
Just simple filters to adjust the default cropping ratio (and probably other Customizer settings).

**Describe alternatives you've considered**
Building my own loop and bypassing Customizer settings, which doesn't seem user-friendly.

**Comment by cjkoepke** [comment]
For the record, I did manage to find a somewhat manual override for this issue. On plugin activation, I manually update the settings for the Customizer aspect ratio:

```php
update_option( 'woocommerce_thumbnail_cropping', 'custom' );
update_option( 'woocommerce_thumbnail_cropping_custom_width', '16' );
update_option( 'woocommerce_thumbnail_cropping_custom_height', '9' );
```

**Comment by kloon** [comment]
We do not allow overriding the cropping and some other image settings via a filter as we believe this is something the store owner should have power over to change via the customizer.

The only option we give to theme/plugin authors wanting to make a change to the default behavior is to use the options you posted above, a note on this though, please only run that on theme/plugin activation and not on every page load, this forces the user changes to revert when they make changes in the customizer, as well as can cause performance issues when you are writing to the DB on every page load.

**Comment by cjkoepke** [comment]
Definitely not running on every page load. I agree that the user should have control over the setting, but why not allow the definition of **defaults** at the theme level?

**Comment by mikejolley** [comment]
These are user facing options, so defaults won't work if already set.

**Comment by cjkoepke** [comment]
@mikejolley 🤦‍♂️  Thanks, that just totally made it clear for me. ;-)
