### ISSUE TITLE
500 Internal Sever Error trying to edit pages

### ISSUE THREAD

**Issue by EzySNIP** [woocommerce/woocommerce#20266]
When I try to edit my pages, I get the 500 Internal Sever Error.
It seems to be spreading to pages that I could edit now.

**To Reproduce**
1. Click Edit Page
2. Get error message
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log.

**Screenshot**
![500 error](https://user-images.githubusercontent.com/39682510/40592299-c5ad3d84-6260-11e8-90df-b6d8ba212199.jpg)

**Expected behavior**
To be able to edit my page.

**WordPress Environment**

Desktop
Webpage

**Comment by kloon** [comment]
@EzySNIP This is usually due to some plugin/theme conflict. Can I ask you please disable all plugin except WooCommerce and also switch to a standard theme like Twentyseventeen or Storefront and test if this still happens.

You can find the issue by enabling plugins one by one testing in-between and then also switching your theme back to your theme and testing.

I am unable to reproduce this on a clean install of WooCommerce so this has to be a conflicting plugin or theme.

**Comment by EzySNIP** [comment]
Hi Gerhard

Will doing these actions lose any content or structure of the current website?

 

Cheers

Ian Gibbs

Owner/Partner | 73 - BE IMAGINATIVE BE INNOVATIVE | EzySNIP™

Mobile 0414 418 216

Email ian.gibbs@73.net.au <mailto:ian.gibbs@73.net.au>  | Web www.ezysnip.com.au <http://www.ezysnip.com.au/>  |Facebook www.facebook.com/ezysnip <https://www.facebook.com/ezysnip>  | Twitter @EzySNIP <https://twitter.com/EzySNIP>   LinkedIn https://www.linkedin.com/company/ezysnip 

 



Confidentiality Notice: The information within this email and all its attachments are confidential and may also be legally privileged. By receiving this email, you are advised that all information within this email and all its attachments are agreed to by both parties and to be considered the forming of a non-disclosure agreement (NDA), also known as a confidentiality agreement (CA), a confidential disclosure agreement (CDA), a proprietary information agreement (PIA), intellectual property agreement (IP) and may also be legally privileged. If you have received this transmission in error you may not read, reproduce, copy, distribute or disclose its contents to anyone else. If you are not the intended recipient/s, please notify us immediately and then delete the email & attachments from your computer system. Any views expressed in this e-mail are those of the individual sender and may not necessarily reflect the views of 73. Violation of this notice may be unlawful.

**Comment by kloon** [comment]
You will not loose any data or content, however you might experience temporarily functionality loss depending on what you deactivate, as soon as you enable that plugin/theme again the functionality will be restored.

**Comment by EzySNIP** [comment]
Hi Gerhard

I deactivated all and reactivated one at a time as suggested, I can edit pages again. Thank mate for your help

Still slow to load, 30s+ but I will work that out.

Cheers 

Ian Gibbs

Owner/Partner | 73 - BE IMAGINATIVE BE INNOVATIVE | EzySNIP™

Mobile 0414 418 216

Email ian.gibbs@73.net.au <mailto:ian.gibbs@73.net.au>  | Web www.ezysnip.com.au <http://www.ezysnip.com.au/>  |Facebook www.facebook.com/ezysnip <https://www.facebook.com/ezysnip>  | Twitter @EzySNIP <https://twitter.com/EzySNIP>   LinkedIn https://www.linkedin.com/company/ezysnip 

 



Confidentiality Notice: The information within this email and all its attachments are confidential and may also be legally privileged. By receiving this email, you are advised that all information within this email and all its attachments are agreed to by both parties and to be considered the forming of a non-disclosure agreement (NDA), also known as a confidentiality agreement (CA), a confidential disclosure agreement (CDA), a proprietary information agreement (PIA), intellectual property agreement (IP) and may also be legally privileged. If you have received this transmission in error you may not read, reproduce, copy, distribute or disclose its contents to anyone else. If you are not the intended recipient/s, please notify us immediately and then delete the email & attachments from your computer system. Any views expressed in this e-mail are those of the individual sender and may not necessarily reflect the views of 73. Violation of this notice may be unlawful.
