### ISSUE TITLE
Yet another ?wc-ajax 403 issue.

### ISSUE THREAD

**Issue by iGlitch** [woocommerce/woocommerce#20261]
**Describe the bug**
With this, users are unable to checkout, as well as are unable to choose products that have variation.

**To Reproduce**
FIRST BUG
1. Go to '[https://equiamazon.com/shop/horses/horse-accessories/big-egg-butt-bit/](https://equiamazon.com/shop/horses/horse-accessories/big-egg-butt-bit/)'
2. Click on 'Any variation and click add to cart'
3. See error on top about variations.

SECOND BUG
1. Go to '[https://equiamazon.com/shop/womens/makebe-tech-fabric-horse-riding-jacket/](https://equiamazon.com/shop/womens/makebe-tech-fabric-horse-riding-jacket/)
2. Click on 'Any variation and click add to cart'  (THIS ITEM WORKS FOR SOME REASON???)
3. Proceed to checkout page.
4. View console errors and observe the 403 responses for ?wc-ajax (Unable to checkout by clicking Paypal)

**Expected behavior**
Normal shopping experience.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**What else I tried**
I use nginx on a VPS, but I have even tried with Apache and get the same error... I turned on redirects for https://equiamazon.com/?wc-ajax* -> https://equiamazon.com/index.php?wc-ajax*

Without the index.php the ?wc-ajax will either redirect to homepage (for example [https://equiamazon.com/?wc-ajax=update_order_review](https://equiamazon.com/?wc-ajax=update_order_review), however with the index.php you will just see a -1.

In nginx I have: 

```
location / { #permalinks
     rewrite ^?wc-ajax(.*)$ https://equiamazon.com/index.php?wc-ajax$1$args permanent;
     try_files $uri $uri/ /index.php?q=$uri&$args;
}
```

I tried without the rewrite line as well...

Naturally, tried 2017 official WP theme, disabled all plugins except WP...

Tried disabling firewall, chmodding the entire site, re-setting permalink settings to %postname%, even tried other permalink settings, modifying my wp-config as per https://wordpress.org/support/topic/wc-ajaxupdate_order_review-403-error/#post-9653485 ... Other issues on this github are almost similar and I tried those solutions and still  same...

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://equiamazon.com
Site URL: https://equiamazon.com
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: glitch
PHP Version: ❌ 7.1.18 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 16 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.29.0
NSS/3.34

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.5 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 6.80MB
Database Data Size: 4.98MB
Database Index Size: 1.82MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.11MB + Index: 0.09MB
wp_postmeta: Data: 1.48MB + Index: 0.69MB
wp_posts: Data: 0.33MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcmp_cust_answers: Data: 0.02MB + Index: 0.02MB
wp_wcmp_cust_questions: Data: 0.02MB + Index: 0.00MB
wp_wcmp_products_map: Data: 0.02MB + Index: 0.00MB
wp_wcmp_vendor_orders: Data: 0.02MB + Index: 0.02MB
wp_wcmp_visitors_stats: Data: 0.02MB + Index: 0.09MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yith_padp_receiver_commissions: Data: 0.02MB + Index: 0.00MB
wp_yith_vendors_commissions: Data: 0.02MB + Index: 0.00MB
wp_yith_vendors_commissions_notes: Data: 0.02MB + Index: 0.00MB
wp_yith_vendors_payments: Data: 0.02MB + Index: 0.00MB
wp_yith_vendors_payments_relathionship: Data: 0.02MB + Index: 0.00MB
wp_yith_wcbk_booking_notes: Data: 0.02MB + Index: 0.00MB
wp_yith_wcbk_external_bookings: Data: 0.02MB + Index: 0.00MB
wp_yith_wcbk_logs: Data: 0.02MB + Index: 0.00MB
wp_yith_wcdn_desktop_notification: Data: 0.02MB + Index: 0.00MB
wp_yith_wcgeoip_rules: Data: 0.02MB + Index: 0.03MB
wp_yith_wcps_shippings: Data: 0.02MB + Index: 0.00MB
wp_yith_wcsc_commissions: Data: 0.02MB + Index: 0.00MB
wp_yith_wcsc_receivers: Data: 0.02MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wp_yith_ywpar_points_log: Data: 0.02MB + Index: 0.00MB
wp_ylc_chat_rows: Data: 0.02MB + Index: 0.00MB
wp_ylc_chat_sessions: Data: 0.02MB + Index: 0.02MB
wp_ylc_chat_visitors: Data: 0.02MB + Index: 0.00MB
wp_ylc_offline_messages: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB
wp_ywf_user_fund_log: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 33
nav_menu_item: 45
oembed_cache: 1
page: 21
post: 3
product: 10
product_variation: 111
revision: 52
yith-wcet-etemplate: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
ywf_deposit (ywf_deposit)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #32 - /shop/
Cart: #34 - /cart/
Checkout: #36 - /checkout/
My account: #38 - /account/
Terms and conditions: #8 - /terms/

### Theme ###

Name: EquiAmazon
Version: 6.5.1
Author URL: https://glitchery.jp
Child Theme: ✔
Parent Theme Name: EquiAmazon Parent
Parent Theme Version: 6.5.1
Parent Theme Author URL: https://glitchery.jp
WooCommerce Support: ✔

### Templates ###

Overrides: Overrides: equitheme/woocommerce/cart/cart.php
equitheme/woocommerce/cart/cross-sells.php
equitheme/woocommerce/checkout/form-billing.php
equitheme/woocommerce/checkout/form-checkout.php
equitheme/woocommerce/checkout/form-coupon.php
equitheme/woocommerce/checkout/form-login.php
equitheme/woocommerce/checkout/form-shipping.php
equitheme/woocommerce/checkout/review-order.php
equitheme/woocommerce/checkout/thankyou.php
equitheme/woocommerce/content-product.php
equitheme/woocommerce/content-product_cat.php
equitheme/woocommerce/global/breadcrumb.php
equitheme/woocommerce/global/form-login.php
equitheme/woocommerce/global/quantity-input.php
equitheme/woocommerce/loop/loop-end.php
equitheme/woocommerce/loop/loop-start.php
equitheme/woocommerce/loop/pagination.php
equitheme/woocommerce/myaccount/form-login.php
equitheme/woocommerce/notices/error.php
equitheme/woocommerce/notices/notice.php
equitheme/woocommerce/notices/success.php
equitheme/woocommerce/order/order-details-customer.php
equitheme/woocommerce/order/order-details.php
equitheme/woocommerce/single-product/meta.php
equitheme/woocommerce/single-product/price.php
equitheme/woocommerce/single-product/related.php
equitheme/woocommerce/single-product/up-sells.php

````
</details>

**Comment by kloon** [comment]
@iGlitch I am unable to replicate this on my local environment. This seems very server specific since you are adding custom redirects via nginx config, also can you confirm you **do not** have your permalink set to the Plain under Settings -> Permalinks? http://cld.wthms.co/AOhyaM

Also have a look at https://wordpress.stackexchange.com/questions/189006/changing-permalinks-gives-me-404-errors-on-nginx in order to get WordPress rewrites working correctly on nginx.

**Comment by iGlitch** [comment]
@kloon Yeah, it's really weird and I can't figure out for the life of me what could be the issue.  Been trying all sorts of things for 2 days now.  
So yeah, the website is not using the Plain setting in permalinks, it is using Post Name. However, the original Post Name radio button shows SITE.COM/index.php/%postname%
So I am using the Custom permalink and set it to %postname% only.

I actually turned the redirect on after I saw it not working, and the redirect rule I used didn't even work, so on and off were both failure (probably a syntax error on my part because it never even redirected)

**Comment by iGlitch** [comment]
Hmm, I see... but for some reason putting said url as ...com/index.php?s=search_string does work.
At the time I reported the issue I only had Woocommerce plugin activated, could having the other plugins maybe modified something in SQL perhaps?

**Comment by peterfabian** [comment]
Not sure about your full nginx config, you can maybe try to get an inspiration from VVV config for WordPress:

https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/nginx-config/nginx-wp-common.conf

That one^ is included in a site-specific config which looks like below:
```
server {
    listen       80;
    listen       443 ssl;
    server_name  local.wordpress.test *.local.wordpress.test local.wordpress.dev *.local.wordpress.dev ~^local\.wordpress\.\d+\.\d+\.\d+\.\d+\.xip\.io$;
    root         {vvv_path_to_site}/public_html;

    error_log    {vvv_path_to_site}/log/error.log;
    access_log   {vvv_path_to_site}/log/access.log;
    
    set          $upstream {upstream};

    include      /etc/nginx/nginx-wp-common.conf;
}
```

I'm not really an nginx expert, but [this article on Codex](https://codex.wordpress.org/Nginx) seems to also have some useful config examples...

**Comment by kloon** [comment]
Closing this as we are unable to replicate. Have a look at the VVV Nginx config for inspiration https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/config/nginx-config/nginx-wp-common.conf
