### ISSUE TITLE
Can’t Import Products Using CSV

### ISSUE THREAD

**Issue by marikkar** [woocommerce/woocommerce#20268]
**Can’t Import Products Using CSV**
When we try to import the CSV file we are geting the "Specified file failed upload test." massage and eds thare. 

**To Reproduce**
1. Go to 'Woocommerce All product'
2. Click on 'Import Button'
3. Choose a CSV file to be uploded 
4. Check Update existing products
5. Click on Continue. 

**Screenshots**

![image](https://user-images.githubusercontent.com/23873034/40601341-79722950-625d-11e8-8e43-7ba05a879877.png)

![image](https://user-images.githubusercontent.com/23873034/40601379-9bb65a9a-625d-11e8-8bb0-d2adf95167ca.png)

**WordPress Environment**
`
### WordPress Environment ###

Home URL: http://sa.myhommer.com
Site URL: http://sa.myhommer.com
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Microsoft-IIS/10.0
PHP Version: 7.2.2
PHP Post Max Size: 32 MB
PHP Time Limit: 600
PHP Max Input Vars: 3000
cURL Version: 7.57.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 8.0.11
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

Contact Form 7: by Takayuki Miyoshi – 5.0.2
Elementor: by Elementor.com – 2.0.12
Ocean Extra: by OceanWP – 1.4.11
WooCommerce: by Automattic – 3.4.0
WordPress Importer: by wordpressdotorg – 0.6.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SAR (SAR )
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

**Comment by kloon** [comment]
The error comes from WordPress' uploader, it means the file was not uploaded correctly to the server.

It could be caused by a number of things, check if you can upload the same file via Media -> Add New? If not then there may be an issue with your server settings prohibiting uploads.

let me know if you can upload the file via the Media uploaded and then please attach the file to the issue so we can continue looking into this. I am not able to reproduce the issue with the sample product files bundled with WooCommerce core.

**Comment by rellect** [comment]
I can confirm the issue.
There's a in the file `class-wc-product-csv-importer-controller.php` line 298
```
$overrides = array(
	'test_form' => false,
	'mimes'     => $valid_filetypes,
);
$import    = wp_unslash( $_FILES['import'] ); // WPCS: sanitization ok.
$upload    = wp_handle_upload( $import, $overrides );
```

The `wp_unslash` here removes the windows directory separator.
If I dump `$import` I get this: `["tmp_name"]=> string(24) "C:WindowsTempphpAF51.tmp"`

**Comment by kloon** [comment]
See #20273

**Comment by marikkar** [comment]
Import and Export are working fine before the update, it has broken after update.
I Can upload media and any other attachment from WordPress as well as I can upload product images in the WooCommerce without any issue.
