### ISSUE TITLE
Does not automatically update to FREE SHIPPING once target purchase is met.

### ISSUE THREAD

**Issue by aimsgeda** [woocommerce/woocommerce#20265]
When a minimum purchase is reached, the shipping cost should be automatically "Free".
But the system does not automatically update it to free.
Note: This update was processing correctly before, but now it isn't working.

Please help.

**To Reproduce**
1. Go to www.sewntobechic.com
2. Go to 'SHOP' or "CLOTHING".
3. Select items and click "ADD TO CART".
4. Make purchase reach $70 or more to avail Free Shipping.
5. Go to checkout page, see that the Shipping does not automatically update to "Free Shipping". - BUG!

**Screenshots**
See screenshot of the problem.

![woocommerce bug_checkout shipping](https://user-images.githubusercontent.com/39487055/40585422-41b23d4c-6178-11e8-92bb-1b48000de6d5.jpg)

**Expected behavior**
Shipping is expected to automatically update to "FREE SHIPPING" once $70 or more purchase is met.

**Comment by leglesslizard** [comment]
@aimsgeda I can't replicate this issue in my environment with only WooCommerce installed and a default theme. As long as the free shipping method is at the top of the list it is automatically selected.  When I tried on the site you mentioned it was selected correctly as well for me

**Comment by kloon** [comment]
In your Zone, ensure the free option is right at the top http://cld.wthms.co/7S2KyD If it is not there be sure to drag it to the top and it should be selected by default.
