### ISSUE TITLE
Custom attributes are not preselected when linking from the cart page

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#20276]
**Describe the bug**
When we add a variable product to the cart, there is a link in the cart page which should take you back to the single product page and preselect the various attributes. For a product with global attributes this can look like:
https://site.test/product/name/?attribute_pa_size=small
Or for a product with custom attributes this can look like:
https://site.test/product/name/?attribute_size=small

However after updating to 3.4 the link with the custom attributes no longer works. If I revert the following commit then it starts working again: https://github.com/woocommerce/woocommerce/commit/11c85c7b8d57e4dd20087a1d416c64cc95eeaba2

Without the sanitize_title it looks for the variable attribute_Size instead of looking for attribute_size, which results in the size attribute not being preselected.

**To Reproduce**
1. Create a variable product with a custom attribute (use a character in the attribute name which will be sanitized, such as a capital letter)
2. Add the product to the cart
3. Click the cart link to get back to the single product page
4. The attribute won't be preselected

**Expected behavior**
For the attribute to be preselected. When I revert the change in the commit which was linked above or revert to WooCommerce 3.3.5 then the attribute is selected when loading the page.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress 4.9.6
WooCommerce 3.4
Storefront 2.3.1
```
</details>

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/20293
