### ISSUE TITLE
'Phone field' in checkout is always Optional

### ISSUE THREAD

**Issue by adrianlbs** [woocommerce/woocommerce#20277]
Looks like the 'Phone field' in checkout is Optional at all times, no matter which options you choose in the Customizer.

**To Reproduce**
1. Go to 'Appearance > Customize > WooCommerce > Checkout'
2. Set the 'Phone filed' to 'Required'
4. See the 'Phone field' still has the (Optional) label next to it.

**Screenshots**
https://screencast.com/t/S5ZBJbr1w5

**Expected behavior**
Should be marked with '*' like the other required fields.

**Comment by mikejolley** [comment]
Hi @adrianlbs 

Not sure if this is a plugin conflict or glitch with the preview on your site, but locally I'm unable to replicate this one. It's showing the correct label after changing the option, and more importantly, when published the changes are reflected on the live checkout.

You didn't provide status report so unsure if you're using checkout customization plugins which could do this.

Let me know if you can provide more clarification on how to replicate or if it happens on multiple stores.

Thanks

**Comment by adrianlbs** [comment]
Hello again Mike,

Thank you for your reply.
I figured it seems to be happening when the plugin **WooCommerce PayPal Express Checkout Gateway** is active. Can you look into that please?

Thanks!
Adrian.

**Comment by mikejolley** [comment]
@adrianlbs Can you use the helpdesk please for extension support? If it's by ourselves.

**Comment by dougaitken** [comment]
Commenting here for completeness and anyone searching in future, after speaking to @adrianlbs via WooCommerce.com.

This is a specific setting for the [PayPal Express Checkout](https://woocommerce.com/products/woocommerce-gateway-paypal-express-checkout/) extension.

Under advanced settings, there is a checkbox for `Require Phone Number.` More details here - https://docs.woocommerce.com/document/paypal-express-checkout/#section-6

**Comment by adrianlbs** [comment]
Thanks a bunch!

**Comment by KoolPal** [comment]
After spending almost an hour reached here and realized that [WooCommerce PayPal Checkout Payment Gateway](https://wordpress.org/plugins/woocommerce-gateway-paypal-express-checkout/) plugin is messing with all the required fields!

Deactivated PayPal for now. Ridiculous!

**Comment by strarsis** [comment]
@KoolPal: The plugin offers a mandatory phone field option (now?) by the way.

**Comment by KoolPal** [comment]
@strarsis Thanks for notifying me.  Really appreciate this!

As you would have noticed from my comment, I have abandoned the WooCommerce PayPal Checkout Payment Gateway plugin for more than 2 years now. 

I would rather focus on my business than waste time beta testing such plugins!

Thanks again! Take care, stay safe!

**Comment by marcuswisecaesar** [comment]
**To Reproduce**
Steps to reproduce the behavior:

- Go to 'Appearance > Customize > WooCommerce > Checkout'
- Set the 'Phone filed' to 'Required'
- See the 'Phone field' still has the (Optional) label next to it.

**Screenshots:** 
[Screencast](https://d.pr/i/J3as0f)

**What I expected:** 
- I expected the Phone Number section to be made required.

**Comment by rrennick** [comment]
@marcuswisecaesar If you can reproduce this issue on a site with only WooCommerce and a default theme active, please create a new issue, describing the steps to reproduce and provide your system status report. I'm not able to reproduce this with the current version of WC.
