### ISSUE TITLE
Notice triggered in non-deprecated WooCommerce function (wc_get_product_attachment_props)

### ISSUE THREAD

**Issue by plabadille** [woocommerce/woocommerce#20278]
**Describe the bug**
Notice when calling function wc_get_product_attachment_props : ID is called wrong way from WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong

**Fix the bug**
file : includes/wc-product-functions.php:705
change : $alt_text[] = wp_strip_all_tags( get_the_title( $product->ID ) );
to : $alt_text[] = wp_strip_all_tags( get_the_title( $product->**get_id()** ) );

**To Reproduce**
Just call the function wc_get_product_attachment_props($thumbnail_id, $product)

**Comment by rodrigoprimo** [comment]
Thanks for your contribution. See #20282.
