### ISSUE TITLE
Import Tax Rates Sample File URL Displays as HTML

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce#20271]
**Import tax rates sample file URL displays as HTML**

The link should clickable.

**To Reproduce**
1. Go to '../wp-admin/admin.php?import=woocommerce_tax_rate_csv'

**Screenshots**

![](http://cld.wthms.co/d6FHjE+)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

</details>

**Comment by kloon** [comment]
See #20272
