### ISSUE TITLE
Fix conflict with GiveWP plugin on Twenty Seventeen theme.

### ISSUE THREAD

**Issue by Benunc** [woocommerce/woocommerce#20295]
**Describe the bug**
The stylesheet added in 3.4.0 of WooCommerce for compatibility with the Twenty Seventeen theme includes a declaration for the `required` class, setting its `visibility` to `hidden` which causes all GiveWP required field inputs to be hidden.

**To Reproduce**
1. On a site with WooCommerce 3.4.x, activate the GiveWP plugin (search "give" in the new plugin page)
2. Navigate to Donations > Settings > Payment Gateways > Offline donations and enable the billing address
3. Navigate to Donations > Settings > Payment Gateways and enable the offline donation gateway, and set it to default.
2. Navigate to Donations > Add New Form
3. Give the New Form a name, and click "Publish"
4. view the form by clicking the permalink on the page.

All required fields (First Name, Email) are invisible.

**Screenshots**
Here's a video:

https://screencast-o-matic.com/watch/cFhUo2b7wL

**Expected behavior**
I expect Give and WooCommerce to play nicely. Specifically I expect Woo selectors to be a bit more specific for that stylesheet.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://woolocal.local
Site URL: http://woolocal.local
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: ❌ 5.3.29 - WooCommerce will run under this version of PHP
however
some features such as geolocation are not compatible. Support for this version will be dropped in the next major release. We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version

PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ MaxMind GeoIP database requires at least PHP 5.4.
Total Database Size: 4.14MB
Database Data Size: 2.96MB
Database Index Size: 1.18MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_give_donormeta: Data: 0.02MB + Index: 0.05MB
wp_give_donors: Data: 0.02MB + Index: 0.03MB
wp_give_formmeta: Data: 0.09MB + Index: 0.03MB
wp_give_logmeta: Data: 0.02MB + Index: 0.03MB
wp_give_logs: Data: 0.02MB + Index: 0.00MB
wp_give_paymentmeta: Data: 0.02MB + Index: 0.03MB
wp_give_sequential_ordering: Data: 0.02MB + Index: 0.00MB
wp_give_subscriptions: Data: 0.02MB + Index: 0.06MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.02MB + Index: 0.02MB
wp_postmeta: Data: 0.09MB + Index: 0.13MB
wp_posts: Data: 0.08MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

amn_mi-lite: 1
attachment: 2
customize_changeset: 1
give_forms: 4
give_log: 52
give_pdf_template: 1
page: 11
post: 2
product: 24
product_variation: 4
revision: 23
shop_order: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

Ben's Helper Functions: by BenUNC –
Give - Donation Plugin: by WordImpress – 2.1.3
User Switching: by John Blackbourn – 1.3.0
WooCommerce: by Automattic – 3.4.0
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #187 - /187-2/
Checkout: #189 - /189-2/
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/20296
