### ISSUE TITLE
Fatal error: Call to undefined function wc_get_screen_ids() 

### ISSUE THREAD

**Issue by Smokietr** [woocommerce/woocommerce#20297]
Hello. I am getting such an error. I could not find the cause.

> Fatal error: Call to undefined function wc_get_screen_ids() in C:\AppServ\www\wordpress\wp-content\plugins\woocommerce\includes\admin\class-wc-admin-notices.php on line 167

`if ( ! in_array( $screen_id, wc_get_screen_ids(), true ) && ! in_array( $screen_id, $show_on_screens, true ) ) {
     return true;
}`

**Comment by mikejolley** [comment]
See if a plugin is calling `admin_print_styles` action somewhere where WooCommerce is not loaded. That action should only run in the admin area.

**Comment by Smokietr** [comment]
Woocommerce is working on previous versions. I'm still looking for the problem, but I can not find it.

**Comment by kloon** [comment]
@Smokietr Could you perhaps do a test by disabling all plugins except WooCommerce and then also switching to a default theme like Twentyseventeen or Storefront and tests if the issue persists? If not then the issue lies within your theme or one of your plugins on the site.

**Comment by Smokietr** [comment]
@kloon Thank you for your suggestion. Is there a document, lecture, that you can recommend about debugging woocommerce?

**Comment by kloon** [comment]
@Smokietr have a look here https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Comment by Smokietr** [comment]
Thank you for your help. If I can find a solution I will write here.
