### ISSUE TITLE
When a user opts to create an account at checkout, error notices are missed on page reload

### ISSUE THREAD

**Issue by jjcoffee** [woocommerce/woocommerce#20291]
**Describe the bug**
Despite the fix #19699 for autoscrolling to error messages, there is still an issue on the checkout page if a user opts to create an account as the page reloads and the browser automatically loads to the point where the user was last scrolled (which is usually the payment area). This leads to error notices being missed.

#19699 probably needs to be modified to take this into account.

I'm not sure if this is Stripe specific, but I assume since WC is now handling autoscroll logic for messages that it's down to you to sort this out? Sorry if it's the wrong place!

**To Reproduce**
(With the Woocommerce Stripe extension installed)
1. On checkout page, select to create an account
2. Scroll down the page
3. Enter some incorrect payment details
4. Place order, note the page will reload to the point it was scrolled to before, no error is visible

**Expected behavior**
Page should either be scrolled to the top from the start, or smooth-scrolled there.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
Stripe also has autoscroll logic which scrolls to the payments area https://github.com/woocommerce/woocommerce-gateway-stripe/blob/5c9dfcccac9fb1889d951235d95e95327e3a3250/assets/js/stripe.js#L717

This perhaps could append errors above the form with the others, or only scroll if no other notices are present.

This can be reported on https://github.com/woocommerce/woocommerce-gateway-stripe/issues

Thanks!
