### ISSUE TITLE
How to List Products in one Category by JSON "WITHOUT ANY AUTHENTICATION"?

### ISSUE THREAD

**Issue by WildDagger** [woocommerce/woocommerce#20305]
I AM SO FRUSTRATED in this issue.

I just want to list what products are in one category by using JSON, however, I can find any guide from ANY DOCUMENTATION.
Yep, I found the API GUIDE, however, this is NO USE.
Because I stuck on OAUTH and there is NO SOLUTION and NO EXAMPLE about how to do by HTTP.
(I tried to find on the Internet and got no any solution)

**Comment by kloon** [comment]
You should be able to retrieve that via the default WP API without authentication https://developer.wordpress.org/rest-api/reference/taxonomies/ You will need to check for the product_cat taxonomy.

All WooCommerce specific endpoints require authentication.
