### ISSUE TITLE
The "Import products from a CSV file" functionality doesn't working

### ISSUE THREAD

**Issue by pmbaldha** [woocommerce/woocommerce#20303]
**Describe the bug**
The "Import products from a CSV file" functionality doesn't working.

**To Reproduce**
1. Go to the 'Admin Dashboard > Tools'
2. Scroll down to 'WooCommerce products (CSV)'
3. Click on the 'Run Importer' link of 'WooCommerce products (CSV)'
4. Click on the 'Choose File' and select "woocommerce/sample-data/sample_products.csv" file
5. Click on the Continue button and you can see error message like `Specified file failed upload test.`

**Screenshots**
https://www.awesomescreenshot.com/image/3389412/cf347ca82c8d1d5b3bfefdee44f534bc

**Expected behavior**
It should be work.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
@pmbaldha can you please confirm what version of WooCommerce you are running? This was fixed in the 3.4.1 release which went live last night.

**Comment by kloon** [comment]
@pmbaldha can you please confirm which version of WooCommerce you are running as this was fixed in the 3.4.1 release which went live last night.
