### ISSUE TITLE
Product Gallery and Description No Show

### ISSUE THREAD

**Issue by colortheparty** [woocommerce/woocommerce#20300]
Hi, I've been having an issue when using a gallery with a product. When I add several pictures to a product the full content description doesn't show compared to when I only add the product feature image the description does show. What can I do?

![captura de pantalla 2018-05-29 a la s 2 39 25 p m](https://user-images.githubusercontent.com/39745012/40681238-348eed54-634e-11e8-9659-33f0b3d979a3.png)
![captura de pantalla 2018-05-29 a la s 2 40 00 p m](https://user-images.githubusercontent.com/39745012/40681239-34a70a88-634e-11e8-82e5-60be1a6bcbd1.png)

**Comment by kloon** [comment]
@colortheparty in the future please include the information as requested when opening an issue as it helps us troubleshoot quicker.

I'd suggest you test this by switching your theme to a default one like Twentyseventeen or Storefront and see if you get the same results.

If you are, then also test by disabling all plugin except WooCommerce and if that fixes the issue you can enable the plugins one by one testing in between to find the plugin causing the issue.

This seems like a styling issue on your theme and not a WooCommerce core issue.
