### ISSUE TITLE
API Rest Batch Update Order Cannot set_paid

### ISSUE THREAD

**Issue by colighto** [woocommerce/woocommerce#20307]
Have tried to trigger a batch update for orders the list of orders were updated with the correct items and I've set set_paid to true on the rest request but when I manage to check the orders on the site backend they are still pending payment have tried to trigger the individual order update via rest api and the set_paid was successfully set. What could cause the batch order update fail to update set_paid for the orders?

**Comment by aerojun** [comment]
I'm also having issues with batch update. When using the `Automattic\WooCommerce\Client` and `$woocommerce->post('products/batch', $data);`, it throws an exception:

`HttpClientException in HttpClient.php line 340: Syntax error`

When checking woocommerce logs, I find:

`Invalid argument supplied for foreach() in /path/mysite.com/html/wp-content/plugins/woocommerce/includes/class-wc-api.php on line 282` which contains the function:

`public function register_wp_admin_settings() {
                $pages = WC_Admin_Settings::get_settings_pages();
                foreach ( $pages as $page ) {
                        new WC_Register_WP_Admin_Settings( $page, 'page' );
                }

                $emails = WC_Emails::instance();
                foreach ( $emails->get_emails() as $email ) {
                        new WC_Register_WP_Admin_Settings( $email, 'email' );
                }
        }`

**Comment by colighto** [comment]
Thanks @aerojun maybe i could take a look there to get some clue. But it really makes it strange on my end is thia only happens on batch update request for orders order items where successfully processed but set_paid is not honored cause when i check the orders again on the site they didn't change to processing, individual order processing via api seems to work but i really would like to use the batch update instead. Can't say if i also have a mistake on the format sent from my java app to the api but it seems to process the request and returns a response after update except that it didn't set anything for the date paid somewhere set_paid is not getting included on the update.

**Comment by gdewey** [comment]
I am getting the same issue just after I upgraded to woo 3.4.1 we use Batch Update on products and  getting: 

Invalid argument supplied for foreach() in
wp-content/plugins/woocommerce/includes/class-wc-api.php on line 282

any help would be apreciate it!

**Comment by aerojun** [comment]
My problem is with batch update products.

**Comment by colighto** [comment]
My Version is woo 3.4.0 but we are having something in common with problem I think we need to wait for someone who could help us with this issue somehow with batch update on order problem I manage to do a work around. Although its a bit odd solution but after the batch update for orders which is including all items on them I just have to run another loop that would set_paid to true but will run the api call for individual order update instead, it would work for me for sometime. But this would kill the idea of batch update though especially if there is a great volume of data that needs to be updated.

**Comment by peterfabian** [comment]
Hi colighto,

I was not able to reproduce this problem on my side using WC 3.4.0.
It's a bit strange, because `/batch` endpoint is calling the same `WC_REST_CRUD_Controller::update_item` method as individual endpoint.

Can you please include the relevant part from your request that is not working?
Also, have you tried to disable other plugins to make sure it happens only with WooCommerce active?

E.g. this works for me (i.e. it changes `status` for these 2 orders to `processing` and sets the `date_paid`):

```
curl -X POST \
  https://woostable.woo.test/wp-json/wc/v2/orders/batch \
  -H 'Authorization: Basic ...' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
	"update": [
	    {
	      "id": 113,
	      "set_paid": true
	    },
	    {
	      "id": 114,
	      "set_paid": true
	    }
  ]
}'
```

**Comment by peterfabian** [comment]
Hi @aerojun, @gdewey,

I was not able to reproduce the same error with latest master branch, or using 3.4.1 version, e.g. with request like below:
```
curl -X POST \
  https://local.wordpress.test/wp-json/wc/v2/products/batch \
  -H 'Authorization: Basic ...' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
	"update": [
	    {
	      "id": 29,
	      "regular_price": "20.99"
	    },
	    {
	    	"id": 38,
	    	"regular_price": "15.99"
	    }
  ]
}'
```

Can you please include the relevant part from your request that is not working?
Also, have you tried to disable other plugins to make sure it happens only with WooCommerce active?

**Comment by aerojun** [comment]
I'll try disabling plugins first.

**Comment by aerojun** [comment]
Looks like it's beacuse a plugin

**Comment by mikejolley** [comment]
@colighto If your's is not a plugin conflict like ^ please report back with the extra details to reproduce this.

Thanks

**Comment by colighto** [comment]
sorry it took me long to respond on this but I will provide the details needed for this one and yup I have created a plugin that would extend the rest api request based on what my application needs will try your advice on disabling it and do the test.
