### ISSUE TITLE
RTL woocommerce product gallery not showning my product photos

### ISSUE THREAD

**Issue by amerabdo** [woocommerce/woocommerce#20311]
**Describe the bug**
after updating to woocommerce 3.4.1 all my products featured photo and or product attribute images all are not showing due to RTL bug in the new update screenshots may describe the issue.

**Screenshots**
![01](https://user-images.githubusercontent.com/39769854/40738458-e92c635e-6443-11e8-89a1-e7ab3788f5a5.jpg)
![02](https://user-images.githubusercontent.com/39769854/40738460-e953dc68-6443-11e8-8117-57f918396147.jpg)

**Comment by ahmedadelnew** [comment]
@amerabdo 
I have the same problem 
Please if you get any solution, send it at **ahmedadelnew@gmail.com**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39780418/40752179-b92a2350-646e-11e8-85c7-5f1d4a3de0fb.gif)

**Comment by amerabdo** [comment]
I found a quick solution till the next update of Woocommerce the problem is in file named jquery.flexslider.min.js in folder path: woocommerce\assets\js\flexslider
all you have to do is change the float of "n.vars.rtl,n.newSlides.css" from left to right then change "translate3d("+(n.vars.rtl?-1:1)" to "translate3d("+(n.vars.rtl?1:1)" remove the minus "-"
thats all but this solution is temporary till the next update and if the issue still exist after the next update this solution will remain. 

I attached the modified jquery.flexslider.min.js file so you can replace with the original to fix the bug
[jquery.flexslider.min.zip]
(https://github.com/woocommerce/woocommerce/files/2056543/jquery.flexslider.min.zip)

**Comment by ahmedadelnew** [comment]
@amerabdo 
Thank you, it's working
Please send your email at **ahmedadelnew@gmail.com** to contact you.

**Comment by mikejolley** [comment]
see https://github.com/woocommerce/woocommerce/pull/20321
