### ISSUE TITLE
Product Page Main Image not appear with RTL Mode

### ISSUE THREAD

**Issue by ahmedadelnew** [woocommerce/woocommerce#20317]
I'm using Woocommerce last version and also download storefront theme last version 2.3.2
I'm using the Arabic language on my site, and product image in product page not showing till clicking on zoom icon it appears, and when changing site language to English from (Setting > General) everything working fine and product image in product page appear.
This problem found when adding additional images to a product, and when adding the main image only everything working fine, and when adding additional images to product gallery images the images not shown expect to click on zoom icon.
I'm not adding any custom functions and not editing anything.
The RTL file in theme code and named "style-rtl.css" and don't changing anything on it.
The RTL mode working fine in all site expect the product page main image
I'm not editing on any image size or image width on any plugin or theme customizer
I tested storefront theme on another site (for testing) and enabled the woocommerce plugin and also the same issue when changing the language to Arabic.
This photo explains the problem (if gif image not showing go to this URL https://goo.gl/bytJqq)
**# I found someone has the same problem and he said it was from Woocommerce the last update
his problem link** @amerabdo
woocommerce/woocommerce#20311

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39780418/40752950-1d360a1e-6472-11e8-8a5a-0bb31030efd1.gif)
![40738458-e92c635e-6443-11e8-89a1-e7ab3788f5a5](https://user-images.githubusercontent.com/39780418/40752951-1d5c1452-6472-11e8-8457-17841f3e4d6f.jpg)

**Comment by mikejolley** [comment]
Why are you logging duplicate issues?

https://github.com/woocommerce/woocommerce/issues/20311
