### ISSUE TITLE
[products] shortcode button for external products should still go to Products page

### ISSUE THREAD

**Issue by cavalierlife** [woocommerce/woocommerce#20315]
**Describe the bug**
When using the [products] shortcode, normal products list the title of the product, which is linked to the product page, as well as a Read More button, which is also linked to the product page. However, external products list the title of the product, which is linked to the product page, as well as a Buy From button, which is linked to the external site. This is odd behavior. The external product's button should act just as the normal product's button; both should link to the product page (at least by default or as an option). The only place that the button linking to the external site should display is on the product page, not within an array of products.  

**To Reproduce**
1. Go to any page.
2. Add a [products] shortcode that will result in a mixture of normal products and external products.
3. Notice that the normal products' "Read More" button links to the product page, just like its product title does, but the external products' "Buy From" button links to the external url, instead of the product page, as its product title does.
4. The products shortcode button url for external products should link to the product page, just as a normal product button does. The external product button should only link to the external source on the single product page, not on the array of products result from the shortcode.

I believe this should be the default, but if for some reason, it is determined that the current way is suitable as a default, then this way should at least be an option.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment]
Hi there,

This matches the regular shop page handling for cart buttons. Swapping this might be undesirable to some, but it can be customised via the `woocommerce_product_add_to_cart_url` filter. 

https://gist.github.com/mikejolley/7fb2300d6a7ad4c95eb6e994e14a0b8e

Thanks

**Comment by cavalierlife** [comment]
The whole point is that is does NOT match the regular handling for cart buttons - when using the [products] shortcode only. Maybe a better way to explain it is that the shortcode doesn't output an Add To Cart button, it outputs a Read More button that links to the product permalink. Therefore, to match that experience, the external product, when displayed via the shortcode, shouldn't output a Buy From External Vendor (add to cart equivalent) either. It should also output a Read More button that links to the product permalink. If I were to use your gist, then I would remove the correct functionality on the Product's single page as well, and I don't want to do that. As I mentioned, it functions properly there. It's only wrong when displaying a list of products via the products shortcode. The gist would solve the problem there, but break the correct functionality on the Product's Single Page.

**Comment by mikejolley** [comment]
Products shortcode does include add to cart buttons - the output is identical to the shop page.

**Comment by cavalierlife** [comment]
You're right. My bad. I cannot reproduce this on a different domain. Sorry.

**Comment by mikejolley** [comment]
Np. As for the snippet, if thats still of interest it would be possible to add an `is_page` check in there to only affect regular pages, not product pages.

**Comment by cavalierlife** [comment]
Yes, thank you, that will be perfect. Appreciate the help.
