### ISSUE TITLE
_price field won't update after save when _regular_price field is unchanged

### ISSUE THREAD

**Issue by daveloodts** [woocommerce/woocommerce#20327]
Because of a apparently  bad import we got issues with _price and _regular_price; the _price field was become rounded and was different then the _regular_price field. This is not the 'issue' i want to mention. It was just the way we found by coïncedence the following bug:

Simulation:
Change the _price field via the database, go to the edit page of the product and re-save the product without changing the regular price. The _price field stays the same, although it would be logic it would get the same price as the regular field as there are no discounts involved (via other plugins)
Only when you change the regular price in the products admin and re-save; then the _price field is updated.

It's not clear if this is a bug; or is there a control on regular price to see if it has changed or not.
If so: it would be beter that a re-save saves everything again; also the _price field.

**Comment by mikejolley** [comment]
We only update _price when the fields price is based on change. Saving it each time would be wasteful. The price update event happens here:

This is not something we intend to change unfortunately.  If something external to WooCommerce messes with the data, thats not within the scope of WooCommerce to fix. The built in WooCommerce importer users the CRUD system, not direct meta updates, to prevent this type of thing happening.

https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L596-L610

To fix this in your case, you'd need to update the price fields manually (SQL?) and rebuild them from the _regular_price fields OR modify the above code to run each save if you want to trigger this on each save event.

Thanks

**Comment by daveloodts** [comment]
Hi Mike, thanks for the fast answer. It's not the issue where the problem is being caused, the issue here is also that most store owners don't have a clue between the difference between _price and _regular_price. And therefore such kind of pricing faults won't be seen fast because they think: when i re-save the product, it's re-saved. But apparently not. So yes, you're totally right. It's not a direct issue in the result of WooCommerce; but it's certainly against common behauviour of the 'saving' option which is then hard to explain to store owners. Therefore: we've added a extra column in the product overview list: price field next to the regular price field. Just to double check. Weird, but working for us.

**Comment by mikejolley** [comment]
@daveloodts Can the importer method you're using not be updated to use the new system? Or better yet, use the core CSV import?

**Comment by daveloodts** [comment]
We're still investigating and testing that. Right now, we only get the xls of the clients stock-software tool. Thanks for the fast reply!
