### ISSUE TITLE
In WC3.4, WC_Shipping_Method "add_rate" using "get_rate_id" with suffix not being saved

### ISSUE THREAD

**Issue by shadimanna** [woocommerce/woocommerce#20320]
**Describe the bug**
In WC 3.4 the "instance_id" of a shipping method is being saved in it's own order item meta field, by doing so the "suffix" being added to the method id (e.g. "shipping_method_id:instance_id:suffix") is NOT being saved anywhere, previously it would have been saved in order item meta field "method_id" as is (i.e. "shipping_method_id:instance_id:suffix").  There is now no way to distinguishing between multiple rates using the suffix currently.

**To Reproduce**
1. Create new shipping method inheriting "WC_Shipping_Method"
2. In "calculate_shipping" function add a new rate
3. For the rate id call "get_rate_id( $suffix )" with a $suffix to create method id (e.g. "shipping_method_id:instance_id:suffix")
4. If this method is ordered on frontend, the "shipping_method_id" and "instance_id" are saved, but not the "suffix".

**Screenshots**
Method id created with suffix - https://www.dropbox.com/s/p2wlcqo7xrndmrf/Screenshot%202018-05-31%2011.15.41.png?dl=0
Suffix not saved anywhere - https://www.dropbox.com/s/8n3v0f5vgjsoc9m/Screenshot%202018-05-31%2011.16.25.png?dl=0

**Expected behavior**
Suffix should be saved in DB

**Recommended Fix**
Add "set_suffix" in "class-wc-order-item-shipping.php" to save suffix
In "class-wc-order-item-shipping-data-store.php" line 49, save suffix e.g. "$item->set_suffix( $legacy_method_id[2] );"

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://smartsend:8888
Site URL: http://smartsend:8888
WC Version: 3.4.1
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 1.83MB
Database Data Size: 0.98MB
Database Index Size: 0.85MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.38MB + Index: 0.02MB
wp_postmeta: Data: 0.05MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 6
post: 2
product: 1
shop_order: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Smart Send Shipping for WooCommerce: by Smart Send ApS – 8.0.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.1 – 2.3.2 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
The suffix, correct me if I'm wrong, allows a single instance of a shipping method to define multiple rates i.e so they don't have the same IDs on display. Only one rate is stored to the order.

Storing this in method id/instance id would be wrong.

Why not add meta data for your shipping method instead?

**Comment by shadimanna** [comment]
> Why not add meta data for your shipping method instead?
Wouldn't storing the "suffix" yield the same end result?  How would I go about adding meta data for the shipping method instead?

The issue is this shipping plugin adds a global "method id" and within the settings of the shipping method you select the actual carrier + type to be used, which can be used as the suffix so it can be uniquely identified.  Let me know if that makes sense.

**Comment by mikejolley** [comment]
> The issue is this shipping plugin adds a global "method id" and within the settings of the shipping method you select the actual carrier + type to be used, which can be used as the suffix so it can be uniquely identified. Let me know if that makes sense.

Once this is stored in the order, looking that up is no longer needed. The line item records the method/instance that was used, and should have a useful title to know the rate that was used. Why would you need the suffix after order creation? It's not exposed.

**Comment by mikejolley** [comment]
No, I mentioned earlier. Suffix was added so a method instance could define multiple rates afaik.

Storing carrier and type to meta would keep your data separate from method ids; when you use `add_rate` method you can pass an array of meta data via `meta_data` key. 

https://github.com/woocommerce/woocommerce/blob/6690e549212e97152ef72e349c6b391752eb8578/includes/abstracts/abstract-wc-shipping-method.php#L272

Surely more appropriate for this?

**Comment by shadimanna** [comment]
I see, alright.  It seems like "meta_data" is the way to go then, thank you for your help!

**Comment by mikejolley** [comment]
np
