### ISSUE TITLE
product not being saved as custom product type

### ISSUE THREAD

**Issue by oquirozm** [woocommerce/woocommerce#20322]
Hi!

After trying in many ways, I haven't been able to successfully register a custom product type.
I'm registering it using these functions:

```
add_action( 'init', 'create_custom_product_type' );
function create_custom_product_type() {
    class WC_Product_Appointment extends WC_Product {
      // Tried this way too.
      // public function __construct( $product ) {
      //     $this->product_type = 'appointment_only';
      //     parent::__construct( $product );
      // }     
   public function get_type() {
            return 'appointment_only';
        }
    }

add_filter( 'woocommerce_product_class', 'appointment_only_product_class', 10, 2);
function appointment_only_product_class( $classname, $product_type ) {
    if ( $product_type == 'appointment_only' ) {
        $classname = 'WC_Product_Appointment';
    }
    return $classname;
}
add_filter( 'product_type_selector', 'add_custom_product_type' );
function add_custom_product_type( $types ) {
	$types['appointment_only'] = 'Appointment Only';
	return $types;
}
```

I keep selecting my custom product type and updating the product but it doesn't stays that way, just goes back to 'simple product'. By now I've come to think it must be a bug as I found someone else in a forum with the same issue. I don't know how to debug further, though, and I haven't found any official documentation on how to do it from woocommerce.

Am I missing something? Any recommendation?

PHP: 7.1.7
WordPress: 4.9.6
WooCommerce: 3.4.1

**Comment by mikejolley** [comment]
Just tested your code and aside from the syntax error in the class, it stuck. Seems fine.

If there were a bug we would have heard by know; subscriptions and bookings both use this functionality.

Thanks

**Comment by oquirozm** [comment]
Solved. Leaving it here just for the record: I was using roots/sage theme. Had to move all the calls to add_action( 'init',...)  to functions.php instead of the regular setup I use when working with the sage.

Thanks
