### ISSUE TITLE
Unable To Submit Quantity Updates via the API

### ISSUE THREAD

**Issue by Ecomdash** [woocommerce/woocommerce#20333]
**Describe the bug**
My name is Walter and I work with ecomdash, an Inventory Management tool that is integrated with WooCommerce to manage orders, update inventory, and create new listings. 

We have a user: Jordan Witbeck

Who is using us to keep the inventory levels on WooCommerce up to date, but we're running into an issue where we are unable to connect to his products.

We're looking for SKU: SSTTXXL874 

Can you Jordan troubleshoot the issue of us not being able to find that item?

**Comment by claudiulodro** [comment]
Hi Walter,

GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here.

WooCommerce is an open-source platform/library and not a centralized SAAS, so we do not have access to user data or sites. You are going to have to follow up with Jordan and possibly his web host if you need logs or something to help you troubleshoot.

Thanks.
