### ISSUE TITLE
Ordering by price not in main query

### ISSUE THREAD

**Issue by smazur** [woocommerce/woocommerce#20339]
Hi!

**Describe the bug**
When doing custom get_post for products with orderby = price or any other woocommerce ordering option I get different result than in shop catalog. Digging WC code I found that wc query is focused on main query and doesn't care about others. I think this is wrong and should be fixed.

**To Reproduce**
Just do `get_posts(['post_type' => 'product', 'orderby' => 'price',...])` and compare results with catalog output.

**Expected behavior**
Catalog output and custom `get_posts` with same query vars should return same product set.

**Comment by mikejolley** [comment]
The query class is not greedy; it only runs where needed. Thats is on the main query, for WooCommerce loops only. Hooking into ALL queries would not only be inefficient, but would lead to conflicts with other plugins. 

`price` is not a standard WordPress orderby argument, so I think you're wrong to expect it to work on all `get_post` calls.

```
add_filter( 'posts_clauses', array( WC()->query, 'order_by_price_desc_post_clauses' ) );
```

Something like that before calling get_posts would add that type of sorting. Or you can do standard meta sorting on one of the price fields e.g. on meta key `_price`.

Hope that makes sense.

**Comment by smazur** [comment]
@mikejolley thank you for reply.
I don't expect order by price to work on all get_posts, but only to those that relate to products. In general I expect identical results on get_posts with same query vars. Also binding code behavior to some global state is bad design.

And I don't think that it will be inefficient to do something like this:
`if( $query->get('post_type') == 'product' && $query->get('orderby') == 'price' ) { // inject some sql clauses }`

**Comment by mikejolley** [comment]
Targeting specific global queries is all we can do from WC side to affect those WP queries. Bad design or not, it's the only way without replacing that system :)

Im afk right now - does get posts even fire a hook to do this before it runs? I'm not certain it does.

**Comment by smazur** [comment]
I don't believe there is only one way to do what WC does. There should be better solution without hooking to main query only.  Btw, almost all plugins I have ever seen do same thing. They hook to main query only to do custom SQL injections, what constantly makes me sad.

The problem I'm trying to solve is to reproduce main query as regular query. And why should I use various hacks to fix all those bad plugins?

**Comment by smazur** [comment]
What logic are you talking about? We are affecting query result only based on query vars. Consider following example:

```
global $wp_query;
$new_query = new WP_Query( $wp_query->query_vars );
$a = $new_query->get_posts();
$b $wp_query->get_posts();
// In some cases $a and $b are different, e.g. when orderby = price. What is not good.
```

I see following solution. Don't bind to main query. For main query inject your custom query vars within 'parse_request' or 'pre_get_posts'. Than globally  hook into 'posts_clauses' and do you sql injection based on your custom query vars.

**Comment by mikejolley** [comment]
> Don't bind to main query. 

> For main query inject your custom query vars within 'parse_request' or 'pre_get_posts'.

You still need logic that applies to main query only to pick up the orderby querystring. You'll also be adding custom params to the WP_Query object because parse_orderby removes anything WP does not recognise.

Granted if the above works as you describe it would let you pass in orderby=price on get_posts. For core, this should only occur on main query. So there would need to be code to parse the query string on the main query only to set this param, code to listen for the orderby=price to set this param, and then the SQL injection itself.

My main worry is this ends up breaking backwards compatibility.  Send a PR?
