### ISSUE TITLE
Item quantity error on page

### ISSUE THREAD

**Issue by Manucharyan** [woocommerce/woocommerce#20331]
Hi. Hi have big error on my website. In the page which showing items of shop "Show <quantity>" it's give me an error after of second option choose. When I clicking to show 16 items it's give me which I want, but when I use that feature one more it's not working. Please help me to resolve that problem. The website link is below.
http://santehnika-platinum.ru/product-category/vanny

**Comment by claudiulodro** [comment]
Hi there, thanks for posting. It's probably getting lost in translation, but I'm not able to understand what exactly is the issue or how to reproduce it. I do see on your site that you are using some third-party WooCommerce plugins, and those are the most common source of WooCommerce issues. I recommend [following the troubleshooting steps for plugin and theme conflicts](https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4) to better diagnose the issue. 

I'm closing this issue as non-reproducible. Thanks.
