### ISSUE TITLE
Email corruption?

### ISSUE THREAD

**Issue by sgehrman** [woocommerce/woocommerce#20348]
A bunch of users are having problems with their email address being corrupted when ordering.

for example one guy had joe@gmail.com52

Just wondering if anyone else has seen this?

**Comment by kloon** [comment]
@sgehrman unable to reproduce this, I would suspect it might be your theme or a plugin adding this. What I suggest you do is test by disabling all plugins except WooCommerce and then also switch your theme to Twentyseventeen or Storefront and test again.

You can then enable the plugins one by one testing in between to find the offending plugin adding the value and then finally switching your theme back to your original.
