### ISSUE TITLE
REST API: Shortcode Parsing

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#20344]
The way the rest api parses shortcodes for the product descriptions is rather inconsistent. This is what my product looks like: http://cld.wthms.co/gfu29Y

If I do a GET request like this: `/wp-json/wc/v2/products/364`, here is the response: http://cld.wthms.co/i2rHxY. Notice the shortcodes were parsed already.

If I do a POST request and update a price or the description for example, the response has unparsed shortcodes: http://cld.wthms.co/U5FaHi

Is this the desired result? Parsing the shortcodes make it hard to update a description based on the current value.

**Comment by claudiulodro** [comment]
This is the desired result and standard WP behavior (same thing will happen with requests to the WP core REST API). The `view` context applies all the filters and the `edit` context uses raw data. We also use the same pattern [in the CRUD objects](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L702). 

If you want unparsed shortcodes for a GET request you can do `context=edit` in the request.

**Comment by piya23300** [comment]
@claudiulodro I have the same problem.

your suggestion is we have to pass `context = edit` param when we get the product from Retrieve a product API, right?

If it is yes, the API doc doesn't allow `context` param
API ref: https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-product

Can you suggest the API(get a product) to solve this problem?

**Comment by WPprodigy** [comment]
It does work, just tested. `/wp-json/wc/v2/products/99?context=edit`

**Comment by dangtienngoc** [comment]
For someone work with WPBakery Page Builder

```php

add_action( 'rest_api_init', function () {
	register_rest_field(
		'product',
		'description',
		array(
			'get_callback'    => 'cirilla_app_render_shortcode',
			'update_callback' => null,
			'schema'          => null,
		)
	);

} );

function cirilla_app_render_shortcode( $object, $field_name, $request ) {
	if ( class_exists( 'WPBMap' ) ) {
		WPBMap::addAllMappedShortcodes();
	}

	global $post;
	$post = get_post( $object['id'] );

	$output = array();

	//Apply the_content's filter, one of them interpret shortcodes
	switch ( $field_name ) {
		case 'description':
		case 'content':
			$output['rendered'] = apply_filters( 'the_content', $post->post_content );
			break;

		case 'excerpt':
			$output['rendered'] = apply_filters( 'the_excerpt', $post->post_excerpt );
			break;
	}

	return $output;
}

```

**Before**
![image](https://user-images.githubusercontent.com/4260689/181677917-df3ea2e7-eb1e-4a31-90e9-6977e81da745.png)

**After**
![image](https://user-images.githubusercontent.com/4260689/181677991-5fa9e94f-310e-4be6-8f8e-078ef7a791f6.png)
