### ISSUE TITLE
My products are being deleted each day, I am using Woozone paid version

### ISSUE THREAD

**Issue by jhabek** [woocommerce/woocommerce#20354]
**Describe the bug**
I am using the paid version of WooZone and doing the Amazon Affiliate Program.  Since a week ago, my products have been getting deleted everyday and everyday I need to restore them all.  I don't understand how this happens and would like this to stop.

**To Reproduce**
1. Go to Products
2. Click on Trash
3. See that all products have been deleted
4. I have to restore my products everyday

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above. I can not reproduce the issue because it's happening without me doing anything

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
@jhabek this seems like an issue with your WooZone plugin, we are not experiencing the same result with WooCommerce core. I suggest you contact the developers of the WooZone plugin and have them look into this for you, we unfortunately only support issues relating toe WooCommerce core on this platform and not plugin/theme related issues.
