### ISSUE TITLE
Notice on comments listing page

### ISSUE THREAD

**Issue by obiPlabon** [woocommerce/woocommerce#20355]
If there's any review on any product and if I disable WooCommerce then I get the **`map_meta_cap` was called incorrectly notice**.

1. Add a review to any product
2. Disable WooCommerce
3. Visit comments listing page from the dashboard

![wc-notice](https://user-images.githubusercontent.com/10244644/40885383-0322ee80-6747-11e8-96c3-93d20778c7f1.png)

**Comment by kloon** [comment]
@obiPlabon this is an issue in WordPress core, there is a long-running open trac ticket regarding this https://core.trac.wordpress.org/ticket/16651
