### ISSUE TITLE
Zoomed variation image is incorrect when the variation is changed.

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce#20367]
**Describe the bug**

Reported by one of our users and this only started happening after the 3.4 update. Might be related to https://github.com/woocommerce/woocommerce/pull/19878

I wasn't able to re-create this by manually creating a product from scratch on my test site, but here's the .csv file with an exported variable product:

https://docs.google.com/spreadsheets/d/1mWnjprxiqUW3FUet2ZXTSnwcmx9zqA0SaCg4aIaPOjM/edit?usp=sharing

When we select one of the variations (only happens with Russian Label and Any Shipping Country variation at the moment) and then choose a different variation - on hover, the image of the first variation is zoomed:

http://cld.wthms.co/WJ2nTb 

**To Reproduce**
1. Iimport a variable product this .csv file: https://docs.google.com/spreadsheets/d/1mWnjprxiqUW3FUet2ZXTSnwcmx9zqA0SaCg4aIaPOjM/edit?usp=sharing
2. Open the product page
3. Try this: http://cld.wthms.co/WJ2nTb 

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

`
### WordPress Environment ###

Home URL: https://snowboardabc.mystagingwebsite.com
Site URL: https://snowboardabc.mystagingwebsite.com
WC Version: 3.4.1
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.30 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.59.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
Total Database Size: 65.63MB
Database Data Size: 53.15MB
Database Index Size: 12.48MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.20MB + Index: 0.19MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_comments: Data: 0.08MB + Index: 0.09MB
wpstg0_followup_coupons: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wpstg0_followup_customers: Data: 0.02MB + Index: 0.06MB
wpstg0_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wpstg0_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wpstg0_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wpstg0_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wpstg0_followup_email_orders: Data: 0.02MB + Index: 0.09MB
wpstg0_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wpstg0_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wpstg0_followup_followup_history: Data: 0.02MB + Index: 0.05MB
wpstg0_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_order_items: Data: 0.02MB + Index: 0.05MB
wpstg0_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wpstg0_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wpstg0_geodir_attachments: Data: 0.02MB + Index: 0.00MB
wpstg0_geodir_countries: Data: 0.06MB + Index: 0.00MB
wpstg0_geodir_custom_fields: Data: 0.02MB + Index: 0.00MB
wpstg0_geodir_custom_sort_fields: Data: 0.02MB + Index: 0.00MB
wpstg0_geodir_gd_place_detail: Data: 0.02MB + Index: 0.03MB
wpstg0_geodir_post_icon: Data: 0.02MB + Index: 0.00MB
wpstg0_geodir_post_review: Data: 0.02MB + Index: 0.00MB
wpstg0_links: Data: 0.02MB + Index: 0.02MB
wpstg0_options: Data: 25.52MB + Index: 0.08MB
wpstg0_postmeta: Data: 1.52MB + Index: 0.81MB
wpstg0_posts: Data: 0.34MB + Index: 0.06MB
wpstg0_rg_form: Data: 0.02MB + Index: 0.00MB
wpstg0_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wpstg0_rg_form_view: Data: 0.02MB + Index: 0.03MB
wpstg0_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wpstg0_rg_lead: Data: 0.02MB + Index: 0.03MB
wpstg0_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wpstg0_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wpstg0_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wpstg0_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB
wpstg0_term_relationships: Data: 0.02MB + Index: 0.02MB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpstg0_usermeta: Data: 0.05MB + Index: 0.03MB
wpstg0_users: Data: 0.02MB + Index: 0.05MB
wpstg0_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wpstg0_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wpstg0_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wpstg0_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wpstg0_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpstg0_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB
wpstg0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_bp_activity: Data: 0.02MB + Index: 0.16MB
wp_bp_activity_meta: Data: 0.02MB + Index: 0.03MB
wp_bp_notifications: Data: 0.02MB + Index: 0.11MB
wp_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB
wp_bp_xprofile_data: Data: 0.02MB + Index: 0.03MB
wp_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB
wp_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB
wp_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.19MB + Index: 0.09MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_geodir_attachments: Data: 0.02MB + Index: 0.00MB
wp_geodir_countries: Data: 0.06MB + Index: 0.00MB
wp_geodir_custom_fields: Data: 0.02MB + Index: 0.00MB
wp_geodir_custom_sort_fields: Data: 0.02MB + Index: 0.00MB
wp_geodir_gd_place_detail: Data: 0.02MB + Index: 0.03MB
wp_geodir_post_icon: Data: 0.02MB + Index: 0.00MB
wp_geodir_post_review: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 10.08MB + Index: 0.23MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.05MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 7.50MB + Index: 5.86MB
wp_posts: Data: 2.47MB + Index: 0.41MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.05MB + Index: 0.03MB
wp_term_relationships: Data: 0.13MB + Index: 0.08MB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_software_activations: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_software_licenses: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 1.50MB + Index: 0.00MB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB
wp_wps_index: Data: 0.02MB + Index: 0.05MB
wp_wps_key: Data: 0.02MB + Index: 0.02MB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB
wp_wps_query: Data: 0.02MB + Index: 0.02MB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 658
bookable_person: 16
bookable_resource: 23
bp-email: 14
custom_css: 2
customize_changeset: 11
et_pb_layout: 33
event_ticket: 3
follow_up_email: 5
gd_place: 1
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
jp_vid_sitemap: 2
nav_menu_item: 2
oembed_cache: 3
page: 45
post: 1
product: 307
product_variation: 267
revision: 115
scheduled-action: 60
shipping_package: 4
shop_coupon: 13
shop_order: 135
shop_order_refund: 7
shop_subscription: 3
um_directory: 1
um_form: 3
um_role: 3
wc_booking: 28
wc_membership_plan: 2
wc_order_status: 7
wc_pickup_location: 3
wc_user_membership: 1
wc_zapier_feed: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Jetpack by WordPress.com: by Automattic – 6.1.1
WooCommerce Stripe Gateway: by WooCommerce – 4.1.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.1
WP Mail Logging: by Christian Zöller – 1.8.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: right
Thousand Separator: ,
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix-and-match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #211383 - /
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #156 - /gd-info/

### Theme ###

Name: Storefront
Version: 2.3.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/20321
