### ISSUE TITLE
Bug attibut with (')

### ISSUE THREAD

**Issue by M1ckael** [woocommerce/woocommerce#20360]
Hi,
If you add an quote in your title  the search doesn't work.
look here the quote are not escape in "diamètre d'arbre"
```

// Use Select2 enhancement if possible
				if ( jQuery().selectWoo ) {
					var wc_layered_nav_select = function() {
						jQuery( '.dropdown_layered_nav_reducteur-diametre-sortie' ).selectWoo( {
							placeholder: 'sortie (diamètre d'arbre)',
```
the problem 👍 

If you add the quote broke the select on frontend and the search are not launched.

Mike

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20364
