### ISSUE TITLE
Variable wholesale products showing out of stock

### ISSUE THREAD

**Issue by jodeemason** [woocommerce/woocommerce#20377]
On the front end of the website all public products are working fine, but when signed into a wholesale account, all wholesale only products with variables are showing as "out of stock", however all settings on the back end are in stock.  (wholesale only products without variables aka simple products are working fine)
I have updated woocommerce, plugins, and even the theme.  I even deleted a product and created a new one, still the same issue.
Also, on the back end the variable products aren't showing the wholesale price on the dashboard list of all the products. (the simple ones do)
Thanks!

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue

**Comment by mikejolley** [comment]
"wholesale" isn't a core feature. Sounds like an extension may be responsible for that functionality. Check what you're running and then check with the author of the extension. We only support the core plugin here.

Thanks
