### ISSUE TITLE
Allow enabling/disabling of variation purchasable property using rest API

### ISSUE THREAD

**Issue by 21stcn** [woocommerce/woocommerce#20374]
There should be a way to enable/disable a product variation using the rest API.

I simply want to replicate the 'Enable' checkbox functionality found when editing a variation through the dashboard, so basically prevent users from purchasing the variation. Using the dashboard checkbox achieves all this, but it seems impossible to do it using the rest api.

The 'purchasable' public property is 'read-only' according to the rest api docs: https://woocommerce.github.io/woocommerce-rest-api-docs/#product-variation-properties

But if I need to disable a product using the api, how would I go about doing it?

1. Changing the status of the 'parent' product has no effect on the variations.
2. Simply setting the variation post itself as a draft is a potential way to handle this programmatically. While this has the effect of removing it from the user's cart, product page and shop, the problem with this method is that, after setting the variation as draft, the variation does not have 'Enable' unchecked in the dashboard when editing the parent product, it simply disappears. So unless you're handling everything programmatically (and no one is using the dashboard to manage products), this is potentially dangerous as the variation still exists but is not visible in the dashboard.

It would make a lot of sense to allow the 'purchasable' boolean property to be changed using the rest api, to enable/disable product variations in a manner that mimics native woocommerce dashboard functionality.

https://wordpress.org/support/topic/how-enable-disable-woocommerce-product-variation-using-rest-api-php/#post-10362403

https://stackoverflow.com/questions/50684593/how-enable-disable-woocommerce-product-variation-using-rest-api-php

**Comment by mikejolley** [comment]
`purchasable` is not a property that can be modified, even outside of API. It depends on other factors.

Try `visible` https://github.com/woocommerce/wc-api-dev/issues/64

**Comment by 21stcn** [comment]
Updating the visible property via the API of a single variation toggles the 'enabled' checkbox so it has the same functionality. It sets purchasable to false (indirectly), even if visibility itself remains true because parent post remains visible. Thanks very much for the solution.

This works: 

`$woocommerce->put('products/22/variations/23, $data);`

However just for the record, this same behaviour does not occur when batching: 

`$woocommerce->post('products/22/variations/batch', $data);`

Batch changing variation visibility does not change variation purchasable property nor toggle enable checkbox.

**Comment by Qle63** [comment]
I have the same issue, using POST products/22/variations/batch does not set purchasable (or is_stock, visable etc..) but using PUT products/22/variations/23 does.

however, when a product has 6 sizes with 8 colours options, this means i have to make 48 remote rest API calls to update all variations of a product.

making it a very slow process to update just 1 product
is there a way to get it to work with /batch yet? will there every be?

Best Regards
Lee

**Comment by peterfabian** [comment]
Yeah, it seems a bit odd.

I can see that setting variation property `visible` to false will set the `status` of variation from publish to private (and not change the catalog_visibility, which is displayed as `visibility` in the response).

Nevertheless, for the batch update, the code is a bit more strict and you need to use `false` as value to `visible` for this to have effect. Please try passing something like the below as `$data`:
```
{  
   "update":[  
      {  
         "id":310,
         "visible":false
      },
      {  
         "id":311,
         "visible":false
      }
   ]
}

```
