### ISSUE TITLE
Produtos em oferta randômico nas internas das categorias

### ISSUE THREAD

**Issue by pandacreative** [woocommerce/woocommerce#20379]
Boa noite, pessoal consegui utilizar esse código na minha home:

`$args = array(
	'post_type'      => 'product',
	'posts_per_page' => 24,
	'orderby'        => 'rand',
	'meta_query'     => array(
		array(
			'key'           => '_sale_price',
			'value'         => 0,
			'compare'       => '>',
			'type'          => 'numeric'
			)
		)
);`

Mas eu não consegui utilizar o mesmo código na interna da categoria utilizando o filter woocommerce_get_catalog_ordering_args, por que ele só me dar esses campos para alteração:

`
$args['orderby'] = 'meta_value_num';
$args['order'] = 'DESC';
$args['meta_key'] = '_sale_price';
`

Alguém sabe como consigo fazer aquela meta_query da forma que fiz acima? 
Agradeço desde já. Abraços

**Comment by mikejolley** [comment]
Some of the orderby params near `woocommerce_get_catalog_ordering_args` hook in functions also which can affect your custom sorting.

```
remove_filter( 'posts_clauses', array( WC()->query, 'order_by_price_desc_post_clauses' ) );
remove_filter( 'posts_clauses', array( WC()->query, 'order_by_price_asc_post_clauses' ) );
remove_filter( 'posts_clauses', array( WC()->query, 'order_by_popularity_post_clauses' ) );
```

Note-not all products have a sale price.

Thanks

p.s. this is not a support forum. Use the public forums, slack or facebook groups for code help :)
