### ISSUE TITLE
Shipping Address postcode not being formatted on Orders or Edit Order screen

### ISSUE THREAD

**Issue by joelwills** [woocommerce/woocommerce#20375]
**Describe the bug**

If you enter a UK postcode without a space, for example

![Screenshot](http://joelwills.com/FfTU3M+)

Link to image: http://joelwills.com/FfTU3M

In the order itself the billing address is formatted by `wc_format_postcode` (?) but the shipping address is not:

![Screenshot](http://joelwills.com/Kb78e2+)

Link to image: http://joelwills.com/Kb78e2

**To Reproduce**
1. Create an order on your site and enter the postcode `KT169AZ`
2. Check the order in admin
3. See the Billing postcode is formatted, but the shipping one is not

**Expected behavior**
The shipping address potcode should be formatted the same as the billing postcode

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
Tested on latest master
</details>

**Comment by claudiulodro** [comment]
Thanks for the report. This should be fixed in https://github.com/woocommerce/woocommerce/pull/20330 (See https://github.com/woocommerce/woocommerce/pull/20330#issuecomment-393917822).
