### ISSUE TITLE
Checkout - Luxembourg shouldn't require State / County

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce#20378]
**Describe the bug**
Luxembourg doesn't have states or counties, so these items shouldn't be required on checkout.  

**To Reproduce**
1. Go to checkout
2. Select Luxembourg as the country
3. Notice required State / County fields

**Screenshots**

**Expected behavior**
Customers from Luxembourg shouldn't be required to enter State / County, similar to France.  I believe State was hidden when Luxembourg was chosen in previous versions of WooCommerce(prior to 3.4.0).  

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20389

**Comment by greyes1** [comment]
We've found that this issue persists, and while the State/County fields are removed, they are still required, somehow

<img width="883" alt="unnamed" src="https://user-images.githubusercontent.com/5323732/48877204-ce498680-edc7-11e8-83c2-4aec0b52a732.png">
