### ISSUE TITLE
PHP Fatal error: Call to undefined method WC_Order_Refund::get_refunds() when using WC-REST-API

### ISSUE THREAD

**Issue by NielsdeBlaauw** [woocommerce/woocommerce#20386]
**Describe the bug**
When calling the orders endpoint on the WooCommerce REST API `/wp-json/wc/v2/orders/###` where `###` is the `post_id` of a `post_type` `shop_order_refund` a fatal error is triggered.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an order
2. Refund the order
3. Request the endpoint `/wp-json/wc/v2/orders/###` with a valid API key and ### being the id of the refund post_type.
4. See error `PHP Fatal error: Call to undefined method WC_Order_Refund::get_refunds()`

**Expected behavior**
Normally a `WC_Order` object is used, which has the `get_refunds` method. In this case a `WC_Order_Refund` object is used, which directly extends `WC_Abstract_Order`. It does not inherit or implement a `get_refunds` method. I see three possible solutions:

1. Block the endpoint where `post_type` = `shop_order_refund` with a `400 BAD Request`  or similar.
2. Implement a `WC_Order_Refund::get_refunds()` to return the `get_refunds()` of the original post_parent (which is a valid `WC_Order`).
3. Implement a `WC_Order_Refund::get_refunds()` to return an empty array.
4. `301 Moved Permanently`  the call to it's parent `WC_Order`.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
@claudiosanches Should be blocked as it's not an order ID.
