### ISSUE TITLE
Webhooks don't trigger nor throw errors in vanilla Docker setup

### ISSUE THREAD

**Issue by dwelch2344** [woocommerce/woocommerce#20380]
**Describe the bug**
Vanilla installs of WP from docker will fire a single registration ping when the webhook is created, but not fire any actual hooks (checkout, product created, etc). There's nothing in the logs or otherwise to help determine why. 

**To Reproduce**
1. Run a docker container of `library/wordpress` and install WooCommerce 
2. Create webhooks for requestbin or something you can monitor
3. Notice the `created webhook` event fired immediately
4. Do an action to trigger the webhook 
5. Notice no new webhook triggered

See https://github.com/dwelch2344/woocommerce-docker for an exact example of what I'm working with. MySQL data isn't stored there, so might be annoying to recreate. will be fixing that in the AM

**Expected behavior**
Webhooks should be triggered, or errors thrown

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: http://localhost:8080
Site URL: http://localhost:8080
WC Version: 3.4.1
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.6
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.15-MariaDB-10.2.15+maria~jessie
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 1.87MB
Database Data Size: 1.02MB
Database Index Size: 0.85MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 0.42MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 6
post: 2
product: 1
shop_order: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Jetpack by WordPress.com: by Automattic – 6.1.1
MailChimp for WooCommerce: by MailChimp – 2.1.7 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.6
WooCommerce: by Automattic – 3.4.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My account: #8 - /?page_id=8
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
Probably this same Cron issue which is out of scope. https://github.com/woocommerce/woocommerce/issues/19282#issuecomment-371488360

**Comment by mikejolley** [comment]
^ Without cron webhook events will never run. I'm not sure it's possible to log this from our side because cron jobs are spawned by WordPress.

You can trigger jobs manually using a plugin like `WP Crontrol` if you want to trigger those jobs to test webhooks.

Hope that helps find your problem anyhow.

**Comment by dwelch2344** [comment]
Woohoo, thanks @mikejolley for the quick response. Yeah, looks like the port 8080 vs 80 mapping was the issue. I updated my docker-compose file and things started playing nice. 

Is there a way to get better error logging / more visibility into this error? Tailing logs and watching the compose output didn't show any errors, and the system status seemed like things should be working. 

Happy to contribute / update however would be helpful. Thoughts?

**Comment by mikejolley** [comment]
Sure if you can find a way to do so. The Cron system isn't apart of WooCommerce though so I'm not sure if it's possible.

**Comment by dwelch2344** [comment]
Maybe just append a log message to some file? My WpFu is pretty light, but I'm guessing there's a directory that is neither too public nor too temporary for something like that?

**Comment by mikejolley** [comment]
Maybe. This I believe is where that error would have happened https://github.com/WordPress/WordPress/blob/2e43234f3fbd5fae8c23e8ad38ee410fbd85e65c/wp-includes/cron.php#L446-L460

Errors would be collected here https://github.com/WordPress/WordPress/blob/2e43234f3fbd5fae8c23e8ad38ee410fbd85e65c/wp-includes/cron.php#L512

But there doesn't seem to be error handling https://github.com/WordPress/WordPress/blob/ae2b92929450fbd190db4f1c518b62f92918e21f/wp-includes/default-filters.php#L320

**Comment by dwelch2344** [comment]
So does `spawn_cron` run synchronously? I'd prefer either the end of that function to log failures to a well known log, or the wrapping `forEach` to do so. Either way, emitting a line / log / etc for each cron that failed specifically rather than an overall "some cron failure" for the entire session would be ideal. But again I'm fish out of water here so would love feedback :) 

I'd be happy to take a stab at contributing this if someone could provide some guidance so I don't spin my wheels. Maybe an example of how to log to a common directory / file and how to run a test related to `spawn_cron` or something?

**Comment by mikejolley** [comment]
I'm not sure about that. This code is in WordPress itself, so we'd either need a hook there (to log where we want) or error handling (to log to file with error_log?).

**Comment by mikejolley** [comment]
This I believe? https://core.trac.wordpress.org/ticket/23133
