### ISSUE TITLE
WPML API language parameter

### ISSUE THREAD

**Issue by wespiremedia** [woocommerce/woocommerce#20384]
**Is your feature request related to a problem? Please describe.**
I want to create translations (WPML) of categories (taxonomy / term) via the Woocommerce API. 

It is possible to get categories by the `lang` parameter (https://wpml.org/documentation/related-projects/woocommerce-multilingual/using-wordpress-rest-api-woocommerce-multilingual/#get-product-categories-and-tags), but creating a new translation with the `lang` and `translation_of` parameters don't work. The terms are always created in the default language. 

**Describe the solution you'd like**
It would be great to be able to create a category with both the `lang` and `translation_of` attributes. For example: 
```
$data = array(
  'name' => 'test123',
  'slug' => 'test123',
  'display' => 'default',
  'lang'  => 'de',
  'translation_of'  => 124,
);
$woocommerce->post('products/categories', $data);
```

**Additional context**
-> maybe it is already possible, but I'm not able to figure out how.

**Comment by mikejolley** [comment]
This is something specific to WPML plugin. Since our API is extensible, WPML could implement this feature. Post on their forums :)?

Thanks
