### ISSUE TITLE
POST method is not working in POSTMAN "error 401 cannot create resources. "

### ISSUE THREAD

**Issue by krhacker** [woocommerce/woocommerce#20392]
Getting response when working on GET method but showing error on POST."error 401 cannot create resources

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#401-unauthorized
