### ISSUE TITLE
WC_Customer missing getter and setter methods for shipping_phone

### ISSUE THREAD

**Issue by aaemnnosttv** [woocommerce/woocommerce#20413]
> I didn't feel like this really fit any of the pre-baked issue templates so forgive me if I should have used one of them.

Both billing and shipping address forms contain inputs for the phone number, but `WC_Customer` only has methods for the `billing_phone`; no methods for `shipping_phone`.

i.e. No `get_shipping_phone` and no `set_shipping_phone` methods.

This is a problem since the underlying `(get|set)_address_prop` methods are protected.

As a developer, I would expect consistency in the available methods. I noticed get/setters are missing for `shipping_email` as well, but there isn't a field for this in the shipping address, so it makes a little more sense, but perhaps this should be added as well?

WooCommerce 3.4.2

**Comment by mikejolley** [comment]
WC does not collect shipping phone or email, so having methods wouldn't make much sense here.

**Comment by aaemnnosttv** [comment]
Ah, my mistake. The shipping phone field is being added by the [WooCommerce Services](https://wordpress.org/plugins/woocommerce-services/) plugin.

Thanks! 😄
