### ISSUE TITLE
layered_nav_list hook protected

### ISSUE THREAD

**Issue by baroninn** [woocommerce/woocommerce#20411]
Oki, maybe this isnt a bug. But to me it is a huge bug to not be able to change the layered_nav_list completely.

Im trying to hook into the layered_nav_list function but it is protected.

I want to wrap the list in "a href tag" and make each list a button
also remove the ( ) around the count
etc....

Is there a way to hook into the function without changing the woocommerce core files ?

thanks.

**Comment by mikejolley** [comment]
`woocommerce_layered_nav_term_html` filter controls the markup within each item.

OR

Extend `WC_Widget_Layered_Nav` with a custom class/new widget and change the logic there to avoid changing core files.

Thanks

**Comment by seanconklin** [comment]
`woocommerce_layered_nav_term_html` filter works for Layered Nav widgets set to the **List** type. This filter does not exist for the **Dropdown** type of this same widget instance. I would like to request this filter added there as well.

If trying to remove attribute values you can use the above filter to conditionally return an empty string then use a CSS rule to hide the empty elements using `:empty`. Ideally though, when an item is empty it should not output the `<li></li>` or `<option></option>` HTML tags.

File: `includes/widgets/class-wc-widget-layered-nav.php`

The filter `woocommerce_get_filtered_term_product_counts_query` in the same core file can be used to modify the query to limit options based on the Product, but itself cannot filter the output deeper (variations within said product) without using `woocommerce_layered_nav_term_html` and filtering the specific attributes directly.

I'll provide a sample use case:

```
<?php

// Filter Drop-Down And List Layered Nav Widgets Based On Products Whitelist

add_filter( 'woocommerce_get_filtered_term_product_counts_query', function( $query ) {

	$post_slugs = [ 'product-1', 'product-2' ];

	$query['where'] .= sprintf( ' AND wp_posts.post_name IN ( "%s" )', implode( '","', $post_slugs ) );

	return $query;
} );


// Filter Layered Nav List Widgets Deeper With An Attributes Whitelist

add_filter( 'woocommerce_layered_nav_term_html', function( $term_html, $term, $link, $count ) {

	$skip_filtering_for_terms = [ 'pa_myterm-1-slug', 'pa_myterm-2-slug' ];
	if( in_array( $term->taxonomy, $skip_filtering_for_terms ) ) {
		return $term_html;
	}

	$attribute_values_whitelist = [ 'attribute-1-slug', 'attribute-2-slug' ];

	return in_array( $term->slug, $attribute_values_whitelist ) ? $term_html : '';

}, 10, 4 );
```
