### ISSUE TITLE
Display settings under Products is GONE

### ISSUE THREAD

**Issue by Russellb85** [woocommerce/woocommerce#20414]
Seems like with the new update all display settings are now gone? All of my images were hard cropped to 300 x 300 and now are all different sizes in my store.5

**To Reproduce**
1. Go to 'WooCommerce
2. Click on 'Settings'
3. Click the Products Tab
4. Display settings are no longer there

Was this a mistake? Or are these gone forever?

**Comment by claudiosanches** [comment]
It's not gone, just changed place, since WooCommerce 3.3, you can find it now in the Customizer.
You can learn more about it in https://woocommerce.wordpress.com/2017/12/11/wc-3-3-image-size-improvements/
