### ISSUE TITLE
Revert danish translation

### ISSUE THREAD

**Issue by boutzamat** [woocommerce/woocommerce#20410]
I'm not sure why produkt (product) has been translated to vare (goods) in WooCommerce.

I just double checked, and the correct translation of a product is indeed "produkt" and not varer - which means goods.

Can you please revert this translation to the original one? 
If no, where can i contribute to translating WooCommerce? 

I have a couple of customers who complained about this, and all i could reply was: It's a WooCommerce update. So they wanted me to manually translate all occurances of goods back to products in both front-end and back-end. 

Why would anyone even fix something that isnt broke in the first place?

I hope this will be reverted.

**Comment by mikejolley** [comment]
We cannot (not native speaker), but you can - see https://docs.woocommerce.com/document/woocommerce-localization/

Translations are managed via https://translate.wordpress.org/projects/wp-plugins/woocommerce

Thanks
