### ISSUE TITLE
woocommerce product variation select alert box customization

### ISSUE THREAD

**Issue by gnanavelshenll** [woocommerce/woocommerce#20428]
It is possible to customize the product variation selection alert box?

I want to show bootstrap modal instead of default alert box.

I tried like below. but no lick.

       jQuery(document).on("click", ".single-product .single_add_to_cart_button", function(){
            jQuery('#Content').modal("show");
           return false;
       });

![image](https://i.stack.imgur.com/wDwbN.png)

[https://stackoverflow.com/questions/50367310/woocommerce-product-variation-select-alert-box-customization](url)

**Comment by mikejolley** [comment]
We don't offer an out of the box solution for this so you either have to intercept the click event which triggers the above alert, or dequeue add-to-cart-variation.js and replace it with a custom script.

We don't assist with customisations here.

Thanks
