### ISSUE TITLE
Woocommerce Importer meta:[fields] postmeta is inserted on each run

### ISSUE THREAD

**Issue by opicron** [woocommerce/woocommerce#20431]
**Describe the bug**

When I import products with the WooCommerce importer the fields marked as meta: in the export are removed and inserted in the postmeta table on each run.

This is visible due to the increasing meta_id numbers in the postmeta table. It seems like the old value is removed and the new value is inserted. 

Due to this my meta_id numbers are shooting up on each import as I have thousands of products to updated regulary. 

**To Reproduce**
1. Create CSV file with meta:[fields] columns
2. Import the CSV
3. Check the meta_id numbers of the meta:[fields]
4. Import the CSV (update products)
5. Check the meta_id numbers of the meta:[fields]
6. They should be highers

**Screenshots**
![screenshot-2018-6-7 kies wp_tse_postmeta - adminer](https://user-images.githubusercontent.com/472432/41105299-ae6fdb26-6a6d-11e8-8626-1ada176ff707.png)

After one run:
![screenshot-2018-6-7 kies wp_tse_postmeta - adminer 1](https://user-images.githubusercontent.com/472432/41105691-8ca8b1a6-6a6e-11e8-826d-e2b56e842985.png)

**Expected behavior**
The expected behaviour should be that the postmeta values get updated. Or even better(?), values should get skipped if no change.

**Isolating the problem (mark completed items with an [x]):**
- [ no ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ yes ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ yes ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Will post this if necessarry

**Comment by mikejolley** [comment]
WC_Data does not increment the ID. You can test this by calling it manually.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20483
