### ISSUE TITLE
woocommerce_update_order get fire 3 times after click Update button in Edit order screen.

### ISSUE THREAD

**Issue by iamdharmesh** [woocommerce/woocommerce#20449]
**`woocommerce_update_order` get fire 3 times after click Update button in Edit order screen.**
I am integrating WooCommerce with third-party API system and I am creating and updating order on API once order get created or updated at WooCommerce, during implementation this I note that action `woocommerce_update_order` is get fired 3 times after you press Update button in Edit order screen.

Don't know someone else has reported this is already but I don't find it over github issue so creating this issue. If this is WooCommerce's Expected behavior and not a bug then is there any other hooks which fire only once on update? `woocommerce_process_shop_order_meta` is help me in this but this is help only if you edit order from "edit order" screen and will not work if you update order from order list etc. 

Let me know if you need any other information related this.

Thanks,
Dharmesh Patel

**Expected behavior**
`woocommerce_update_order`  should be fire only once.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodrigoprimo** [comment]
`woocommerce_update_order` is called whenever [WC_Order_Data_Store_CPT::update()](https://github.com/woocommerce/woocommerce/blob/c765ce644db14e322fc77b0d3863d2e4160ecd4f/includes/data-stores/class-wc-order-data-store-cpt.php#L162) is called which indeed happens a few times when an order is updated via the WP admin interface.

I don't know off the top of my head if there is an action that will only run once for each order update and unfortunatelly I can't help you further as this is not a support forum. For support you could try WordPress.org support forums: https://wordpress.org/support/plugin/woocommerce

**Comment by GermanKrutov** [comment]
I have the same problem :(

**Comment by ecr007** [comment]
I solve it using the WP Hook ```save_post```
