### ISSUE TITLE
Product.created Webhook Not Firing

### ISSUE THREAD

**Issue by RandySK** [woocommerce/woocommerce#20442]
We have created a Product created webhook.  When the webhook is created or modified we get a post to the specified Delivery URL, so we know it connects.

However, when a product is created and we click Publish, nothing is posted to the URL.

When I do the command

/wp-json/wc/v2/webhooks/<id>/deliveries

for a specific webhook ID, no data is returned, so it seems that WooCommerce knows it hasn't sent anything for the webhook.

Any ideas why the webhooks aren't firing?

Thanks.

Randy Kaempen

### WordPress Environment ###

Home URL: https://staging.luminaire.com
Site URL: https://staging.luminaire.com
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 264 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.10.3
PHP Version: 7.1.13-1+ubuntu16.04.1+deb.sury.org+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.22-0ubuntu0.16.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ❌ Your server does not have the DOMDocument class enabled - HTML/Multipart emails
and also some extensions
will not work without DOMDocument.

GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: _OXY_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 135.90MB
Database Data Size: 89.43MB
Database Index Size: 46.47MB
_OXY_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB
_OXY_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
_OXY_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
_OXY_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
_OXY_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
_OXY_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB
_OXY_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
_OXY_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
_OXY_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
_OXY_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
_OXY_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
_OXY_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
_OXY_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
_OXY_woocommerce_log: Data: 0.02MB + Index: 0.02MB
cerber_acl: Data: 0.00MB + Index: 0.00MB
cerber_blocks: Data: 0.00MB + Index: 0.00MB
cerber_countries: Data: 0.02MB + Index: 0.00MB
cerber_lab: Data: 0.00MB + Index: 0.00MB
cerber_lab_ip: Data: 0.02MB + Index: 0.00MB
cerber_lab_net: Data: 0.02MB + Index: 0.02MB
cerber_log: Data: 0.02MB + Index: 0.01MB
cerber_traffic: Data: 2.52MB + Index: 0.09MB
_OXY_commentmeta: Data: 0.02MB + Index: 0.03MB
_OXY_comments: Data: 0.02MB + Index: 0.09MB
_OXY_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
_OXY_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
_OXY_gf_entry: Data: 0.02MB + Index: 0.03MB
_OXY_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
_OXY_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
_OXY_gf_form: Data: 0.02MB + Index: 0.00MB
_OXY_gf_form_meta: Data: 0.02MB + Index: 0.00MB
_OXY_gf_form_view: Data: 0.02MB + Index: 0.03MB
_OXY_links: Data: 0.02MB + Index: 0.02MB
_OXY_mergebot_changesets: Data: 0.00MB + Index: 0.00MB
_OXY_mergebot_conflicts: Data: 0.00MB + Index: 0.00MB
_OXY_mergebot_data: Data: 1.52MB + Index: 0.00MB
_OXY_mergebot_deployment_inserts: Data: 0.00MB + Index: 0.00MB
_OXY_mergebot_excluded_objects: Data: 0.02MB + Index: 0.00MB
_OXY_mergebot_queries: Data: 1.52MB + Index: 0.00MB
_OXY_options: Data: 4.42MB + Index: 1.03MB
_OXY_postmeta: Data: 51.59MB + Index: 26.05MB
_OXY_posts: Data: 13.52MB + Index: 7.03MB
_OXY_rg_form: Data: 0.02MB + Index: 0.00MB
_OXY_rg_form_meta: Data: 0.06MB + Index: 0.00MB
_OXY_rg_form_view: Data: 0.02MB + Index: 0.03MB
_OXY_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
_OXY_rg_lead: Data: 0.02MB + Index: 0.03MB
_OXY_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
_OXY_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
_OXY_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
_OXY_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
_OXY_sg_action: Data: 0.02MB + Index: 0.00MB
_OXY_sg_config: Data: 0.02MB + Index: 0.00MB
_OXY_sg_schedule: Data: 0.02MB + Index: 0.00MB
_OXY_signups: Data: 0.00MB + Index: 0.00MB
_OXY_swp_cf: Data: 0.02MB + Index: 0.05MB
_OXY_swp_index: Data: 9.52MB + Index: 9.03MB
_OXY_swp_log: Data: 0.02MB + Index: 0.05MB
_OXY_swp_tax: Data: 0.02MB + Index: 0.05MB
_OXY_swp_terms: Data: 1.52MB + Index: 1.09MB
_OXY_termmeta: Data: 0.06MB + Index: 0.06MB
_OXY_terms: Data: 0.11MB + Index: 0.17MB
_OXY_term_relationships: Data: 1.42MB + Index: 0.45MB
_OXY_term_taxonomy: Data: 0.14MB + Index: 0.11MB
_OXY_usermeta: Data: 0.14MB + Index: 0.09MB
_OXY_users: Data: 0.02MB + Index: 0.05MB
_OXY_wc_download_log: Data: 0.02MB + Index: 0.03MB
_OXY_wc_webhooks: Data: 0.02MB + Index: 0.02MB
_OXY_wpmcleaner: Data: 0.02MB + Index: 0.00MB
_OXY_yoast_seo_links: Data: 0.09MB + Index: 0.05MB
_OXY_yoast_seo_meta: Data: 0.20MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 70
acf-field-group: 19
attachment: 20651
catalog_product: 1472
category-page: 2
customize_changeset: 3
designer: 850
event: 156
manufacturer: 344
nav_menu_item: 76
page: 38
position: 3
post: 203
product: 1468
product_variation: 2558
revision: 931
shop_order: 12
showroom: 5
wishlist: 28

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (18) ###

Gravity Forms: by rocketgenius – 2.3.2
Advanced Custom Fields PRO: by Elliot Condon – 5.6.10
WP Offload S3 Lite: by Delicious Brains – 1.3.2
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Gravity Forms MailChimp Add-On: by rocketgenius – 4.3
Gravity Forms User Registration Add-On: by rocketgenius – 3.9
Media File Renamer: by Jordy Meow – 4.2.1
SearchWP Exclude UI: by Jonathan Christopher – 1.0.1
SearchWP WooCommerce Integration: by SearchWP
LLC – 1.1.20 – Not tested with the active version of WooCommerce

SearchWP: by SearchWP
LLC – 2.9.13

Simple 301 Redirects: by Scott Nellé – 1.07
WooCommerce Stripe Gateway: by WooCommerce – 4.1.6
WooCommerce Multiple Customer Addresses: by Lagudi Domenico – 9.7 – Not tested with the active version of WooCommerce
WooCommerce WishLists: by Lucas Stark – 2.0.5 – 2.1.7 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.2
Yoast SEO: by Team Yoast – 7.6
WP Mail SMTP: by WPForms – 1.2.5
WP Migrate DB Pro: by Delicious Brains – 1.8.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #19 - /store
Cart: #20 - /my-order
Checkout: #21 - /checkout
My account: #22 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: luminaire
Version: 4.0.0
Author URL: http://luminaire.com
Child Theme: ✔
Parent Theme Name: _s
Parent Theme Version: 1.0.0
Parent Theme Author URL: http://automattic.com/
WooCommerce Support: ✔

### Templates ###

Overrides: luminaire/woocommerce/archive-product.php
luminaire/woocommerce/content-product.php
luminaire/woocommerce/content-product_cat.php
luminaire/woocommerce/content-single-product.php
luminaire/woocommerce/content-widget-product.php
luminaire/woocommerce/global/quantity-input.php
luminaire/woocommerce/myaccount/form-login.php
luminaire/woocommerce/single-product/add-to-cart/simple.php
luminaire/woocommerce/single-product/add-to-cart/variable.php
luminaire/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
luminaire/woocommerce/single-product/add-to-cart/variation.php
luminaire/woocommerce/single-product/product-image.php
luminaire/woocommerce/single-product/related.php
luminaire/woocommerce/single-product/title.php
luminaire/woocommerce/single-product.php

**Comment by mikejolley** [comment]
Tested and working - the problem is the deliveries endpoint. This was deprecated. Instead go to:

/wp-admin/admin.php?page=wc-status&tab=logs

And choose the webhooks deliveries log. It will be listed there (confirmed, publish product adds a product created event).

Thanks

**Comment by mikejolley** [comment]
> What do you mean by the ‘deliveries endpoint’?

> When I do the command
> /wp-json/wc/v2/webhooks//deliveries
> for a specific webhook ID, no data is returned, 

I'm saying the logging you're looking at will shown nothing. Go to the log I mentioned and you can see if it was posted, where it was posted, and if there was a connection error.

**Comment by RandySK** [comment]
Mike,

We’ve been to that page.  The problem is that there _isn’t_ a webhooks log.  The popup lists log names like fatal-errors, helper, test-log, wc-db_updates, and woocommerce-gateway-stripe.  None of them say anything about webhooks.  Further, we looked at all of them and none of them showed update dates on the current date.  There is no logging of webhook problems.

So, we remain with the original situation.  We are not getting webhooks posted to our site and there is no logging of why not.


Randy Kaempen

**Comment by RandySK** [comment]
Mike,

As another data point, we _do_ get a post to the webhook destination when we update the webhook itself.  This confirms that WooCommerce _can_ post to us.  We just don’t receive these posts for the actions they are defined for.


Randy Kaempen

**Comment by mikejolley** [comment]
Have you tried other events in that case to see if others log?

**Comment by RandySK** [comment]
Mike,

We have tried product.created and product.updated and neither of them post.  Do you know why we would get a post from updating the webhook itself?


Randy Kaempen
Intellex Corporation

**Comment by mikejolley** [comment]
Updating the webhook sends it right away not with Cron. Could be that?

**Comment by RandySK** [comment]
Mike,

I guess so.  I don’t see why a webhook update would send a webhook at all.  It seems almost circular.  If the regular webhooks are sent via a crib job, how much is the delay?  Why would there even need to be a delay?


Randy Kaempen

**Comment by mikejolley** [comment]
The delay is minimal-the cron jobs are used to defer the send so it doesn't impact the user performing the action.

Enable WP Crontrol and see is jobs are working?

**Comment by RandySK** [comment]
Mike,

> On Jun 15, 2018, at 5:14 AM, Mike Jolley <notifications@github.com> wrote:
> 
> The delay is minimal-the cron jobs are used to defer the send so it doesn't impact the user performing the action.
> 
> Enable WP Crontrol and see is jobs are working?
> 
Where is that?  Is it considered a plugin?


Randy Kaempen

**Comment by mikejolley** [comment]
Yes it's a plugin https://wordpress.org/plugins/wp-crontrol/

**Comment by RandySK** [comment]
Mike,

We checked the log and we see a lot of events, including webhooks.  However, at the top of the screen, it says: There was a problem spawning a call to the WP-Cron system on your site.  This means WP-Cron events on your site may not work.  The problem was: Unexpected HTTP response code: 401.

That code says the request was unauthorized.  However, we set up the webhooks from our site.  How can they be unauthorized?  What do we need to do to authorize them?


Randy Kaempen
Intellex Corporation

**Comment by mikejolley** [comment]
Maybe you've blocked access somehow e.g. with htaccess/htpasswd?

**Comment by RandySK** [comment]
Mike,

> On Jun 29, 2018, at 4:22 AM, Mike Jolley <notifications@github.com> wrote:
> 
> Maybe you've blocked access somehow e.g. with htaccess/htpasswd?
> 

We haven’t, but if we had, how would the webhooks for changes to the webhooks themselves have gotten through?  We receive those just fine.


Randy Kaempen
Intellex Corporation

**Comment by mikejolley** [comment]
Because it's not cron during those updates.

> There was a problem spawning a call to the WP-Cron system on your site.  This means WP-Cron events on your site may not work.  The problem was: Unexpected HTTP response code: 401.

^ You need to fix this. No cron = no webhooks. This is not a WooCommerce issue so I cannot help you debug this further.
