### ISSUE TITLE
Email not sent after payment went from on-hold to processing

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#20447]
Saw just on staging site that if I have a order with status on hold and set it to processing after payment received the corresponding email is not generated and sent.

WC 3.4.2
WP 4.9.6
Storefront Theme
PHP 7.2.1

**Comment by mikejolley** [comment]
Checked this;

`woocommerce_order_status_on-hold_to_processing` is a status we listen for within `init_transactional_emails`.

Customer processing email looks at `add_action( 'woocommerce_order_status_on-hold_to_processing_notification', array( $this, 'trigger' ), 10, 2 );` action.

In testing, this was triggered for me also.

Should check the processing email is enabled in settings, and work through https://docs.woocommerce.com/document/email-faq/ which includes adding logging. Seems to be working as it should my side.

Thanks

**Comment by ajgw** [comment]
Well Mike, I checked twice and after you tested it I tested again – and, you are right. It sents emails in that case. The reason is WooCommerce Germanized Plugin which does have a conflict. If that is activated, emails are not sent if status is changed from on hold to processing.
Thanks Mike.

**Comment by mikejolley** [comment]
![2bvzr6](https://user-images.githubusercontent.com/90977/41181850-368d75a6-6b6b-11e8-9ff9-6d676c0b4522.jpg)
