### ISSUE TITLE
Order was deleted (erase personal data) with no reason.

### ISSUE THREAD

**Issue by jatiyanon** [woocommerce/woocommerce#20444]
Are there any ways to make my order like this. 

https://prnt.sc/jsdh3n

Just logged-in and found that my order was erased. It so critical please help.

**Comment by jatiyanon** [comment]
No one used in that time. Order notes were removed (purchase history, transaction etc).
https://prnt.sc/jsfrm9

I already installed "Activity Log" plugin too but nothing found in that time.
Is it possible to find the actual user do this action or disable this feature by hook or hard code? 

Many thanks for your help 🙏

**Comment by mikejolley** [comment]
Let's add a confirmation :)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20481
