### ISSUE TITLE
Rounding discrepancy with tax inclusive pricing

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#20440]
**Describe the bug**
Store has tax rate of 21% and tax inclusive pricing. 
Two products in cart, costs are 45 and 49. 
Flat rate shipping with a cost of 4.96. 

Here's the rough calculations:
7.809917355371901 = 45 - 45 / 1.21
37.190082644628099 = 45 - 7.809917355371901
8.504132231404959 = 49 - 49 / 1.21
40.495867768595041 = 49 - 8.504132231404959
1.0416 = 4.96 x .21
4.96

Added together:
100.0016

WooCommerce shows: 
![](http://cld.wthms.co/PMhiDG+)
Image Link: http://cld.wthms.co/PMhiDG

I believe the additional 1p comes from [this line](https://github.com/woocommerce/woocommerce/blob/3.4.2/includes/class-wc-cart-totals.php#L704), but I could be wrong. The line subtotals are rounded before the tax is added, adding the 1p. 

**To Reproduce**
1. Set a tax rate of 21%
1. Set two products up, one with cost of 45, other with cost of 49
1. Set flat rate shipping cost to 4.96
1. Add both products to cart and go to checkout

**Expected behavior**
Total to be 100, not 100.01

**Isolating the problem (mark completed items with an [x]):**

**Comment by mikejolley** [comment]
Turn off the "Round tax at subtotal level, instead of rounding per line" setting. This is known to cause discrepancies, in this case 1p extra tax.

Without it, 
![slack - a8c 2018-06-08 17-19-16](https://user-images.githubusercontent.com/90977/41169248-4ae097ca-6b40-11e8-9d20-adf7c9995d7a.png)

FYI this setting is on my future hit list :)

**Comment by jessepearson** [comment]
I thought I had tried that without a change, but it worked for me at this point. Thanks 👍

**Comment by jessepearson** [comment]
@mikejolley The user [in this thread](https://wordpress.org/support/topic/rounding-issues-for-most-of-new-orders-after-update-to-3-3-0/) brought up a valid point. The VAT for 100 should be 17.36, not 13.35. Is this something you will be looking into, as well?

**Comment by mikejolley** [comment]
@jessepearson We round tax half down for tax inclusive prices. HMRC allows either way so long as it's consistent. Rounding .5 up all time causes issues when the tax and the price ends with .5.
