### ISSUE TITLE
dashboard, plugins, everything has disappeared with last update

### ISSUE THREAD

**Issue by lorrinevil** [woocommerce/woocommerce#20451]
**Describe the bug**
I was going through working on updates this morning and saw there was an update for woocommerce to 3.4.2 along with several others. I did the update for woocommerce first and everything is gone from the admin area. I searched and can't see anyone else with this issue. I don't even know where to start.
*I did download plugin and update through ftp after this error - no difference*
I can login to admin - but nothing can be seen.

**To Reproduce**
I don't know how to reproduce the error.

**Screenshots**
![admin dashboard](https://user-images.githubusercontent.com/27705367/41158334-2c2ccaf8-6aee-11e8-8e66-53c5feb43342.JPG)
Admin Dashboard blank
![woocommerce gone](https://user-images.githubusercontent.com/27705367/41158344-38200244-6aee-11e8-9884-5de98c4eaaa1.JPG)
Woocommerce gone from menu
![plugins page blank screen options doesn t expand](https://user-images.githubusercontent.com/27705367/41158362-437f2886-6aee-11e8-91c9-6a0df36f89bb.JPG)
Plugins Page blank.
![theme screen blank](https://user-images.githubusercontent.com/27705367/41158436-8e1c6ebc-6aee-11e8-9f3c-82b95fbf0eea.JPG)
Theme screen blank

**Expected behavior**
I expected a clean smooth update, as usual

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
*I am unable to deativate plugins because I can't see them.*
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
*I am unable to see anything to change themes*
- [ ] I can reproduce this bug consistently using the steps above.
*I can't do any of this so I can't reproduce anything - I changed plugin directory to deactive.plugins and can see the screen, but of course no plugins*

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
I can't see woocommerce to do this.
</details>

**Comment by lorrinevil** [comment]
I reuploaded 3.4.1 and still have the same issues.

**Comment by lorrinevil** [comment]
@mikejolley - I'm looking at my database through heidi sql - it still shows version 3.4.1 - I had a fresh copy of 3.4.1 and reuploaded the plugin files. trying to read through to see if 3.4.2 required database updater to be run but not seeing it. the only file from woocommerce I pulled into my theme was product-attributes.php and there is no difference in those files other than where I added the word Shipping in front of dimensions and weight.

Since everything is blank, I can't do any updates or changes. I had hoped by re-uploading previous version it would allow me to see my dashboard again, but it did not. Suggestions? Anything would be appreciated on where to start. working on pulling backup :(

**Comment by mikejolley** [comment]
Right now I suspect WooCommerce is deactivated.

Error log will tell you which plugin is erring?

**Comment by lorrinevil** [comment]
@mikejolley - there have been no errors since right before I updated Woo.  This is last error in the log
`[08-Jun-2018 05:32:23 UTC] payment_method was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Cheque->process_payment, WC_Order->update_status, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_on-hold'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Emails::send_transactional_email, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Email_Customer_On_Hold_Order->trigger, WC_Email->get_content, WC_Email_Customer_On_Hold_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-on-hold-order.php'), do_action('woocommerce_email_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Emails->order_details, wc_get_template, include('/plugins/woocommerce/templates/emails/email-order-details.php'), do_action('woocommerce_email_before_order_table'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_Gateway_goe->email_instructions, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0.`

**Comment by mikejolley** [comment]
Whatever that empty notice in the header is looks like an error... Not what you pasted though.

**Comment by lorrinevil** [comment]
What I have done:
twenty-seventeen is installed - set store theme to storetheme.off
checked.  still blank
found a mu-plugins (empty file - have no idea what that is) - set to off.
still blank
set plugins.off - everything can be seen.
gives me all plugins deactivated because they don't exist.
changed back to plugins and now I can see everything & list of deactived plugins.
I have multiple plugins, including several from woo, would you suggest starting with re-activating woocommerce first?

**Comment by mikejolley** [comment]
I'm going to close this as you've got it working again, however I would definitely recommend trying to track down the conflict so it can be patched to avoid the problem in the future.

Thanks
