### ISSUE TITLE
In the orders overview, add "email" and "phone number" to Screen Options

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#20453]
**Is your feature request related to a problem? Please describe.**

In chatting to a WooCommerce user, they manage many orders at the same time and often need to phone or email a customer before something is shipped. Now they each time have to add another "click" in the process to either use the preview or click to the full order.

4201903-hc

**Describe the solution you'd like**

Just thinking about it a bit, I was wondering if similar to adding "Billing" and "Shipping" through the Screen Options it would be possible to add "Customer details" there as well. 

**Additional context**

![http://cld.wthms.co/4dwmYn](http://cld.wthms.co/4dwmYn+)
Link to image here: http://cld.wthms.co/4dwmYn.

**Comment by enjoydokha** [comment]
We use customer email and telephone data to manually process every order and now with an extra step, it really isn't proving efficient and slowing us down quite considerably.  If these details could be added to the Screen Options and allow users to choose if they want it or not, would be great!
