### ISSUE TITLE
Bulk order status changes do not load payment gateways so some gateways cannot hook into status changes

### ISSUE THREAD

**Issue by joshuadwire** [woocommerce/woocommerce#20466]
**Describe the bug**
#18601 does not seem to be fixed in WC 3.4.2. This means that PayPal payments are not automatically captured when an order is moved from on-hold to processing via the bulk actions dropdown.

**To Reproduce**
1. Configure the PayPal payment action to Authorize.
3. Create an order that has been made with PayPal (in my case the built-in PayPal provider of WC). The order should go into 'on-hold' status.
3. On the orders list on the backend of WC, select the checkbox next to the order, select 'Mark processing' from the menu at the top, and click apply.
4. See if the payment was captured. The `WC_Gateway_Paypal::capture_payment()` function should run but it doesn't.

**Screenshot**
<img width="1533" alt="screen shot 2018-06-09 at 9 09 01 am" src="https://user-images.githubusercontent.com/3169995/41192004-da758a82-6bc5-11e8-80d6-7562c3d12c82.png">
Order shows transition to from On Hold to Processing via Bulk Edit but does not show any attempt to capture the payment.

**Expected behavior**
When I follow those steps, I see...

PayPal does not capture the charge. In particular the `WC_Gateway_Paypal::capture_payment()` does not run.

I was expecting to see...

When marking a PayPal order as processing I would expect the payment to capture, and in particular the `WC_Gateway_Paypal::capture_payment()` function to run.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Temporary workaround**
Adding this code to functions.php or somewhere else registers payment gateways during bulk order status changes and fixes the issue.
```
add_action( 'handle_bulk_actions-edit-shop_order', function() {
    // Initialize payment gateways in case order has hooked status transition actions.
    wc()->payment_gateways();
});
```

**WordPress Environment**
<details>

### WordPress Environment ###

Home URL: http://localdev.wilds.org/store
Site URL: http://localdev.wilds.org/store
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.5 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: ce0p3_
Total Database Size: 227.15MB
Database Data Size: 156.99MB
Database Index Size: 70.16MB
ce0p3_woocommerce_sessions: Data: 3.45MB + Index: 0.06MB
ce0p3_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
ce0p3_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
ce0p3_woocommerce_downloadable_product_permissions: Data: 0.13MB + Index: 0.19MB
ce0p3_woocommerce_order_items: Data: 0.47MB + Index: 0.19MB
ce0p3_woocommerce_order_itemmeta: Data: 5.52MB + Index: 6.03MB
ce0p3_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
ce0p3_woocommerce_tax_rate_locations: Data: 0.08MB + Index: 0.14MB
ce0p3_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
ce0p3_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
ce0p3_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
ce0p3_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
ce0p3_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
ce0p3_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ce0p3_akeeba_common: Data: 0.02MB + Index: 0.00MB
ce0p3_ak_params: Data: 0.02MB + Index: 0.00MB
ce0p3_ak_profiles: Data: 0.02MB + Index: 0.00MB
ce0p3_ak_stats: Data: 0.02MB + Index: 0.03MB
ce0p3_ak_storage: Data: 11.52MB + Index: 0.00MB
ce0p3_ak_users: Data: 0.02MB + Index: 0.00MB
ce0p3_commentmeta: Data: 0.02MB + Index: 0.03MB
ce0p3_comments: Data: 4.52MB + Index: 3.80MB
ce0p3_links: Data: 0.02MB + Index: 0.02MB
ce0p3_options: Data: 3.17MB + Index: 0.14MB
ce0p3_pmxe_exports: Data: 0.33MB + Index: 0.00MB
ce0p3_pmxe_posts: Data: 1.52MB + Index: 0.00MB
ce0p3_pmxe_templates: Data: 0.02MB + Index: 0.00MB
ce0p3_pmxi_files: Data: 0.02MB + Index: 0.00MB
ce0p3_pmxi_history: Data: 0.02MB + Index: 0.00MB
ce0p3_pmxi_imports: Data: 1.52MB + Index: 0.00MB
ce0p3_pmxi_posts: Data: 1.52MB + Index: 0.00MB
ce0p3_pmxi_templates: Data: 0.09MB + Index: 0.00MB
ce0p3_postmeta: Data: 35.58MB + Index: 36.13MB
ce0p3_posts: Data: 72.63MB + Index: 6.44MB
ce0p3_relevanssi: Data: 3.52MB + Index: 6.06MB
ce0p3_relevanssi_log: Data: 1.52MB + Index: 0.00MB
ce0p3_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB
ce0p3_termmeta: Data: 0.11MB + Index: 0.17MB
ce0p3_terms: Data: 0.09MB + Index: 0.14MB
ce0p3_term_relationships: Data: 2.52MB + Index: 2.52MB
ce0p3_term_taxonomy: Data: 0.09MB + Index: 0.11MB
ce0p3_usermeta: Data: 5.52MB + Index: 7.03MB
ce0p3_users: Data: 0.27MB + Index: 0.25MB
ce0p3_vtprd_lifetime_limits_purchaser: Data: 0.02MB + Index: 0.02MB
ce0p3_vtprd_lifetime_limits_purchaser_logid_rule: Data: 0.02MB + Index: 0.02MB
ce0p3_vtprd_lifetime_limits_purchaser_rule: Data: 0.02MB + Index: 0.02MB
ce0p3_vtprd_purchase_log: Data: 0.45MB + Index: 0.02MB
ce0p3_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
ce0p3_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
ce0p3_wc_download_log: Data: 0.06MB + Index: 0.03MB
ce0p3_wc_webhooks: Data: 0.02MB + Index: 0.02MB
ce0p3_woocommerce_bundled_itemmeta: Data: 0.20MB + Index: 0.25MB
ce0p3_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
ce0p3_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB
ce0p3_wpfront_ure_options: Data: 0.03MB + Index: 0.00MB

### Post Type Counts ###

amn_smtp: 4
attachment: 2620
banner: 1
banner_product: 4
cue_playlist: 68
customize_changeset: 1
nav_menu_item: 44
page: 20
post: 5
product: 3092
product_variation: 2
revision: 405
shop_coupon: 19
shop_order: 1716
shop_order_refund: 4
tw_wssi_batch: 257
tw_wssi_error: 9738
vtprd-rule: 8
wishlist: 3091

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #181 - /shop/
Cart: #191 - /cart/
Checkout: #701 - /checkout/
My account: #711 - /my-account/
Terms and conditions: #8543 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 2.3.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20502
