### ISSUE TITLE
Allow items to be changed in wc_save_order_items function

### ISSUE THREAD

**Issue by dezio1900** [woocommerce/woocommerce#20467]
I have booking script I developed. In backend order I created some custom fields for order item ( checkin and checkout dates ), so after those fields are changed, I need to update line_total price for the booking item.

So I added a hook function into woocommerce_saved_order_items, where I update items array, and then calling manually wc_save_order_items( $order_id, $items ); with my custom $items array. Of course I prevent loop with some custom variable set, so that I know that I called wc_save_order_items function. 

This is not good solution, that after WC save order items, I do it again with my custom items array.

I suggest that you send items array by reference, or to add filter hook, so that we can change items array before its sent to wc_save_order_items function. Something like this:

```
function wc_save_order_items( $order_id, $items ) {

// NEW CODE TO ADD
$items = apply_filters( 'woocommerce_save_order_items_array', $items, $order_id );

// Allow other plugins to check change in order items before they are saved.
do_action( 'woocommerce_before_save_order_items', $order_id, $items );


```

**Comment by mikejolley** [comment]
The $items are already passed by reference :) Give it a try - you can edit them.

**Comment by dezio1900** [comment]
@mikejolley Can you explain, please? I don't see that $items are passed by ref. When you edit order item, and click on save button, it calls method save_order_items() inside class-wc-ajax.php if I am right. And in that method $items is not passed by ref. This is source of that function:

```

	/**
	 * Save order items via ajax.
	 */
	public static function save_order_items() {
		check_ajax_referer( 'order-item', 'security' );

		if ( ! current_user_can( 'edit_shop_orders' ) ) {
			wp_die( -1 );
		}

		if ( isset( $_POST['order_id'], $_POST['items'] ) ) {
			$order_id = absint( $_POST['order_id'] );

			// Parse the jQuery serialized items
			$items = array();
			parse_str( $_POST['items'], $items );

			// Save order items
			wc_save_order_items( $order_id, $items );

			// Return HTML items
			$order = wc_get_order( $order_id );
			include 'admin/meta-boxes/views/html-order-items.php';
		}
		wp_die();
	}
```

Because $items is array instead of object, that means its not passed by reference by default. So I can't edit $items for example in "woocommerce_before_save_order_items" hook, in order for edited $Items array then to be proceed by WC code.

**Comment by mikejolley** [comment]
What do you actually expect? The array of posted data (what is there now) or WC_Order_item objects?

Why don't you suggest a PR so we can review what you're after.

**Comment by dezio1900** [comment]
It should stay array, but to allow us to change that array. Because that array contains line totals, I need to be able to recalculate those line totals before its passed to rest of wc_save_order_items( $order_id, $items ) function, so ideally I need to change the array inside "woocommerce_before_save_order_items" hook. And if you look at do_action of that hook, you can see that $items are not passed by reference, so if I edit $items in that hook, it still doesn't pass edited version of $items to rest of wc_save_order_items function.

As I explained, I created custom checkin/checkout inputs for booking item in order edit page. So if those inputs are changed, of course booking item line price needs to be changed. And in order to not create custom code for saving order, I am using WC one, BUT I just need to alter line price for my booking item. I can do that only by changing that array $items. BUT I can't change it because in WC code its not send by reference, so I cannot return back changed array.

To be more precise, look at action hook at the beggining of wc_save_order_items function. It says:

```
// Allow other plugins to check change in order items before they are saved.
do_action( 'woocommerce_before_save_order_items', $order_id, $items );
```
So WC added that hook so that plugin can CHECK order items before they are saved, BUT it would be very helpful if plugins can also CHANGE that array ( my case with booking price ). So not only to check, but also to change it.

So I would suggest either:

Option 1 ( send $items array to "woocommerce_before_save_order_items" action by reference ):
```
// Allow other plugins to check change in order items OR ALTER ITEMS before they are saved.
do_action( 'woocommerce_before_save_order_items', $order_id, &$items );
```
Or Option 2: Add filter hook for the $items array at the top of wc_save_order_items function:

```
function wc_save_order_items( $order_id, $items ) {

// NEW FILTER TO ADD
$items = apply_filters( 'woocommerce_save_order_items_array', $items, $order_id );

// REST OF CODE IN FUNCTION DOESN'T NEED TO BE CHANGED...
// Allow other plugins to check change in order items before they are saved.
do_action( 'woocommerce_before_save_order_items', $order_id, $items );
```

What you think? What option would be better for PR in your opinion?

**Comment by mikejolley** [comment]
PHP passes by reference by default. &$items would go in your callback function no?

**Comment by dezio1900** [comment]
PHP doesn't pass arrays by reference by default. It passes by reference by default only objects, And $items is array, not object, so $items is not passed by reference by default.

**Comment by mikejolley** [comment]
Ok. I'd avoid it then - a new filter for the items array would be preferable. 

Why does this data need to be changed, rather than the object itself later?

**Comment by dezio1900** [comment]
I don't see any other hook later in function wc_save_order_items which will allow me to change $item object, so that I can change line total.

There is only "woocommerce_saved_order_items" hook, but that would mean I need to re-do all calculations that function do, which is not good. So thats why I think line total should be changed before rest of woocommerce_saved_order_items function process that array.

Maybe it would be good that we add action hook for changing $item object just before $item->save();
