### ISSUE TITLE
Attributes page under products admin page shows wrong product count for selected attribute

### ISSUE THREAD

**Issue by nishiyt** [woocommerce/woocommerce#20475]
**Describe the bug**
Attributes product count is not correct and varies in different versions. Eg i have a test version and final version website. Both these versions has same products and same numbers of product but attributes page when selecting a particular attributes shows different count of products . On clicking on the number (total count), the product seen on both versions are same. 

**Expected behavior**
The product count should be accurately shown on selected attribute page. 

**WordPress Environment**
Latest

**Comment by kloon** [comment]
Counts are handled by WordPress core as attributes are just terms in the WordPress system, by the sounds of things your process for cloning the site might be missing something? Perhaps it is not clearing caches correctly? You might need to run wp_update_term_count_now to make the term counts update to that what is in the DB.
