### ISSUE TITLE
Tax Not Calculating with Manual Order

### ISSUE THREAD

**Issue by tbrady85** [woocommerce/woocommerce#20474]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  Create new Standard tax rate (Country Code: US, State Code: AL, ZIP Code: 35126, City: Pinson, Rate: 10.0000%)
2.  Create a taxable product
3. Create a manual order via "Add Order" on the Orders page of WooCommerce
4. Add taxable product
5. Add tax to product via the "Add Tax" button
6. Select the new Standard tax rate that you created and click "Add"

## Expected/actual behavior

When I follow these steps the Tax column will be added to the product but there will be a dash where the tax rate should be.  When I click recalculate the tax column disappears. When ordering directly from the store frontend the taxes are applied correctly.

I was expecting to see the tax rate being applied to the product when manually adding an order, instead I see a dash.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: https://sandbox.trbrady.com
Site URL: https://sandbox.trbrady.com
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.6
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.1.33-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wphq_
Total Database Size: 0.60MB
Database Data Size: 0.48MB
Database Index Size: 0.12MB
wphq_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wphq_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wphq_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wphq_commentmeta: Data: 0.00MB + Index: 0.00MB
wphq_comments: Data: 0.00MB + Index: 0.01MB
wphq_links: Data: 0.00MB + Index: 0.00MB
wphq_options: Data: 0.46MB + Index: 0.03MB
wphq_postmeta: Data: 0.01MB + Index: 0.02MB
wphq_posts: Data: 0.01MB + Index: 0.01MB
wphq_termmeta: Data: 0.00MB + Index: 0.01MB
wphq_terms: Data: 0.00MB + Index: 0.01MB
wphq_term_relationships: Data: 0.00MB + Index: 0.00MB
wphq_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wphq_usermeta: Data: 0.00MB + Index: 0.01MB
wphq_users: Data: 0.00MB + Index: 0.01MB
wphq_wc_download_log: Data: 0.00MB + Index: 0.00MB
wphq_wc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

customize_changeset: 1
page: 8
post: 2
product: 1
shop_order: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.6
WooCommerce Stripe Gateway: by WooCommerce – 4.1.7
WooCommerce: by Automattic – 3.4.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by tbrady85** [comment]
Issue resolved. I placed asterisks in the country, state, zip, and city fields of the tax information instead of my actual location information to correct the issue.

**Comment by alberthe** [comment]
It seems still not fixed yet. When adding tax it shows 0. The tax value has to be entered manually instead of auto calculated and populated.
I'm using OcernWP theme and WooCommerce 4.0.0, but it also happened in previous version.

**Comment by babderrahim** [comment]
I guess I'm facing a similar issue

Products in this store are entered inclusive of tax

1. Orders processed from the store front are calculated correctly subtracting Tax from product price  -> Tax Amount = Price - (Price / (( Tax Rate/100 ) + 1 ))
**2. if order is created by the admin manually, the tax calculation works as the product prices exclusive of tax -> Tax Amount = price + (price x Tax Rate/100 )**

I've checked all the setting everything looks in place, I have Germanized and WPML & WCML plugins Activated, I disabled them to see if they are causing a problem even deactivate still order calculation is faulty
