### ISSUE TITLE
Is it possible to hide the IP address details completely while placing the order? 

### ISSUE THREAD

**Issue by prasidhda** [woocommerce/woocommerce#20477]
Woo commerce is not saving the IP address of some customers. Is it possible to hide the IP address details completely while placing the order?

**Comment by prasidhda** [comment]
Actually, i found that woo commerce `WC_Geolocation::get_ip_address()` is not being able to get the IPv6 address. 

When $_SERVER returns HTTP_X_FORWARDED_FOR as "2607:fb90:2987:5e8b:8d60:db55:f5d:d956", 
`trim( current( preg_split( '/[,:]/', sanitize_text_field( wp_unslash( $_SERVER['HTTP_X_FORWARDED_FOR'] ) ) ) ) )` is returning result as "2607" and hence, `rest_is_ip_address()` is returing false .

**Comment by kloon** [comment]
Fixed in #20479
