### ISSUE TITLE
Wrong attributes showing in product page additional information tab

### ISSUE THREAD

**Issue by nishiyt** [woocommerce/woocommerce#20476]
**Describe the bug**
On product page in Additional Information tab, attributes shown are wrong and not related to products. Some attributes are correct. Other attributes showing are for other products.
Product has one attribute which is used for variation product but product page additional information tab shows more than one attribute ie all attributes available or created with other products and has no relation with the product page

**Expected behavior**
Only attributes to be shown which is used in variation. Attributes should be blank till the time any variation is selected. Based on the variation selected attributes related to that product should be displayed.

**WordPress Environment**
Latest

**Comment by kloon** [comment]
As per #20475 I suspect the issue might be with your cloning process, somewhere the functionality you are using to copy data across is not doing it correctly and linking data to the wrong products.

Not able to recreate this on a regular WooCommerce install, when everything is linking correctly when set up through the interfaces or imported via the importer.
