### ISSUE TITLE
Attributes Title not showing on product variation section

### ISSUE THREAD

**Issue by Adlay2** [woocommerce/woocommerce#20471]
Hello, I recently updated Woocommerce and after the update I can't see the attribute name on the product variation section.

**screenshot before updating**
![s1](https://user-images.githubusercontent.com/40122789/41194087-92c15242-6c16-11e8-8573-9b5316c95194.PNG)
**screenshot after updating**
![s2](https://user-images.githubusercontent.com/40122789/41194099-cba0c2dc-6c16-11e8-9985-eb04a8f38156.PNG)
I would like to know how can i display my attribute title in the product variations section

**Comment by mikejolley** [comment]
This is not a feature of WooCommerce and must be coming from an extension. I believe there was an issue with swatches and HTML which was resolved in 3.4.2 anyhow.
