### ISSUE TITLE
woocommerce is not sending email notifications

### ISSUE THREAD

**Issue by adbergmedia** [woocommerce/woocommerce#20488]
`
### WordPress Environment ###

Home URL: https://discovermarrakech.ma
Site URL: https://discovermarrakech.ma
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.6
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.0
WC Database Prefix: wpcr_
MaxMind GeoIP Database: ✔
Total Database Size: 10.12MB
Database Data Size: 9.37MB
Database Index Size: 0.75MB
wpcr_woocommerce_sessions: Data: 5.72MB + Index: 0.31MB
wpcr_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB
wpcr_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpcr_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpcr_commentmeta: Data: 0.00MB + Index: 0.01MB
wpcr_comments: Data: 0.01MB + Index: 0.01MB
wpcr_ct_add_services: Data: 0.00MB + Index: 0.00MB
wpcr_ct_add_service_bookings: Data: 0.00MB + Index: 0.00MB
wpcr_ct_currencies: Data: 0.00MB + Index: 0.00MB
wpcr_ct_hotel_bookings: Data: 0.00MB + Index: 0.00MB
wpcr_ct_hotel_vacancies: Data: 0.00MB + Index: 0.00MB
wpcr_ct_order: Data: 0.00MB + Index: 0.00MB
wpcr_ct_reviews: Data: 0.00MB + Index: 0.00MB
wpcr_ct_tour_bookings: Data: 0.00MB + Index: 0.00MB
wpcr_ct_tour_schedules: Data: 0.00MB + Index: 0.00MB
wpcr_ct_tour_schedule_meta: Data: 0.00MB + Index: 0.00MB
wpcr_links: Data: 0.00MB + Index: 0.00MB
wpcr_newsletter: Data: 0.00MB + Index: 0.00MB
wpcr_newsletter_emails: Data: 0.00MB + Index: 0.00MB
wpcr_newsletter_sent: Data: 0.00MB + Index: 0.00MB
wpcr_newsletter_stats: Data: 0.00MB + Index: 0.00MB
wpcr_newsletter_user_logs: Data: 0.00MB + Index: 0.00MB
wpcr_nf3_actions: Data: 0.00MB + Index: 0.00MB
wpcr_nf3_action_meta: Data: 0.00MB + Index: 0.00MB
wpcr_nf3_fields: Data: 0.00MB + Index: 0.00MB
wpcr_nf3_field_meta: Data: 0.01MB + Index: 0.00MB
wpcr_nf3_forms: Data: 0.00MB + Index: 0.00MB
wpcr_nf3_form_meta: Data: 0.00MB + Index: 0.00MB
wpcr_nf3_objects: Data: 0.00MB + Index: 0.00MB
wpcr_nf3_object_meta: Data: 0.00MB + Index: 0.00MB
wpcr_nf3_relationships: Data: 0.00MB + Index: 0.00MB
wpcr_nf3_upgrades: Data: 0.00MB + Index: 0.00MB
wpcr_options: Data: 1.25MB + Index: 0.05MB
wpcr_postmeta: Data: 0.76MB + Index: 0.21MB
wpcr_posts: Data: 1.21MB + Index: 0.08MB
wpcr_revslider_css: Data: 0.09MB + Index: 0.00MB
wpcr_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wpcr_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wpcr_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wpcr_revslider_slides: Data: 0.04MB + Index: 0.00MB
wpcr_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wpcr_slider_pro_layers: Data: 0.00MB + Index: 0.00MB
wpcr_slider_pro_sliders: Data: 0.07MB + Index: 0.00MB
wpcr_slider_pro_slides: Data: 0.02MB + Index: 0.00MB
wpcr_termmeta: Data: 0.00MB + Index: 0.01MB
wpcr_terms: Data: 0.00MB + Index: 0.01MB
wpcr_term_relationships: Data: 0.01MB + Index: 0.02MB
wpcr_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wpcr_usermeta: Data: 0.03MB + Index: 0.01MB
wpcr_users: Data: 0.00MB + Index: 0.01MB
wpcr_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpcr_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpcr_wpgmza: Data: 0.02MB + Index: 0.00MB
wpcr_wpgmza_categories: Data: 0.02MB + Index: 0.00MB
wpcr_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB
wpcr_wpgmza_maps: Data: 0.02MB + Index: 0.00MB
wpcr_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB
wpcr_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 232
custom-css-js: 1
customize_changeset: 5
hotel: 6
nav_menu_item: 20
nf_sub: 7
page: 51
post: 2
product: 92
revision: 147
room_type: 11
shop_coupon: 1
shop_order: 12
shop_order_refund: 2
tour: 40
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Check Email: by Chris Taylor – 0.5.5
CTBooking: by Soaptheme – 1.2
WPBakery Visual Composer: by Michael M - WPBakery.com – 5.1.1
Newsletter: by Stefano Lissa & The Newsletter Team – 5.4.5
Ninja Forms: by The WP Ninjas – 3.3.1
Slider Revolution: by ThemePunch – 5.4.3.1
Slider Pro: by bqworks – 4.4.0
WC Custom Thank You: by Nicola Mustone – 1.2.0 – Not tested with the active version of WooCommerce
WooCommerce Thank You Page - NextMove Lite: by XLPlugins – 2.5.0 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.5
WooCommerce: by Automattic – 3.4.0 – 3.4.2 is available
WordPress Importer: by wordpressdotorg – 0.6.4
WP Mail SMTP: by WPForms – 1.2.5
WP Super Cache: by Automattic – 1.5.9
YITH Custom Thank You Page for Woocommerce: by YITHEMES – 1.0.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
simple_tour (simple_tour)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #9 - /tour-cart-page/
Checkout: #10 - /tour-checkout-page/
My account: ❌ Page not set
Terms and conditions: #563 - /terms-conditions/

### Theme ###

Name: Discover Marrakech
Version: 2.3.2
Author URL: http://www.soaptheme.net/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: citytours/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
citytours/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0
citytours/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.2.0
citytours/woocommerce/cart/cart-totals.php
citytours/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.4.0
citytours/woocommerce/cart/cross-sells.php
citytours/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.3.0
citytours/woocommerce/cart/proceed-to-checkout-button.php
citytours/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.4.0
citytours/woocommerce/checkout/form-billing.php version 3.0.0 is out of date. The core version is 3.0.9
citytours/woocommerce/checkout/form-checkout.php
citytours/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.4.0
citytours/woocommerce/checkout/form-login.php version 2.0.0 is out of date. The core version is 3.4.0
citytours/woocommerce/checkout/form-shipping.php version 3.0.0 is out of date. The core version is 3.0.9
citytours/woocommerce/checkout/payment-method.php
citytours/woocommerce/checkout/payment.php version 2.5.0 is out of date. The core version is 3.4.0
citytours/woocommerce/checkout/review-order.php version 2.3.0 is out of date. The core version is 3.3.0
citytours/woocommerce/checkout/thankyou.php version 3.0.0 is out of date. The core version is 3.2.0
citytours/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.4.0
citytours/woocommerce/content-single-product.php version 3.0.0 is out of date. The core version is 3.4.0
citytours/woocommerce/emails/customer-processing-order.php
citytours/woocommerce/emails/email-order-details.php version 3.0.0 is out of date. The core version is 3.3.1
citytours/woocommerce/emails/plain/customer-processing-order.php
citytours/woocommerce/emails/plain/email-order-details.php version 2.5.0 is out of date. The core version is 3.4.0
citytours/woocommerce/global/form-login.php version 2.1.0 is out of date. The core version is 3.3.0
citytours/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.4.0
citytours/woocommerce/global/wrapper-end.php version 1.6.4 is out of date. The core version is 3.3.0
citytours/woocommerce/global/wrapper-start.php version 1.6.4 is out of date. The core version is 3.3.0
citytours/woocommerce/loop/add-to-cart.php version 3.0.0 is out of date. The core version is 3.3.0
citytours/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
citytours/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.3.0
citytours/woocommerce/loop/pagination.php version 2.2.2 is out of date. The core version is 3.3.1
citytours/woocommerce/loop/result-count.php version 3.0.0 is out of date. The core version is 3.3.0
citytours/woocommerce/order/order-details-customer.php version 3.0.0 is out of date. The core version is 3.3.0
citytours/woocommerce/order/order-details.php version 3.0.0 is out of date. The core version is 3.3.0
citytours/woocommerce/product-searchform.php version 2.5.0 is out of date. The core version is 3.3.0
citytours/woocommerce/single-product/add-to-cart/simple.php version 3.0.0 is out of date. The core version is 3.4.0
citytours/woocommerce/single-product/meta.php
citytours/woocommerce/single-product/price.php
citytours/woocommerce/single-product/product-image.php version 3.0.2 is out of date. The core version is 3.3.2
citytours/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date. The core version is 3.3.2
citytours/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.1.0
citytours/woocommerce/single-product/related.php
citytours/woocommerce/single-product/sale-flash.php
citytours/woocommerce/single-product/short-description.php version 1.6.4 is out of date. The core version is 3.3.0
citytours/woocommerce/single-product/tabs/tabs.php
citytours/woocommerce/single-product/title.php
citytours/woocommerce/single-product/up-sells.php
citytours/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 3.2.0
citytours/woocommerce/single-product.php

Outdated Templates: ❌
					
					
we also tried wp mail smtp. please help

**Comment by dougaitken** [comment]
Hi @adbergmedia,

Please see the Email FAQ for more details to test - http://docs.woocommerce.com/document/email-faq/

In particular this part - https://docs.woocommerce.com/document/email-faq/#section-4 , **See if emails are sent, but not received**

This isn't a core issue but rather something in your set up.

I'd also recommend finding time to update your main WooCommerce plugin to the latest version and updating your outdated theme templates.

Thanks,

**Comment by adbergmedia** [comment]
Hey dougaitken 
                     Thanks for the reply, i tried it, nothing is showing up in mail loggin, do you mind if i send you logins in pm to wordpress? and check it  yourself. it will be a favor if you could help me to resovle this issue 

Thanks

**Comment by adbergmedia** [comment]
there is one issue more, when i press "process order" on checkout page, it process order but does not redirects to thank you page. http://prntscr.com/jtpwkx this is what it says, internal server page.

**Comment by dougaitken** [comment]
Hi @adbergmedia, 

We don't provide support via GitHub. If you have a Mail logging plugin active and no emails are even being generated then something is conflicting with that.
I'd recommend a full conflict test. You can read more about plugin and theme conflicts in the documentation here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/ 

If that doesn't help, please open a ticket via WooCommerce.com, and include the System Status Report showing your WooCommerce and template files have been updated as well.

I'm going to close this issue.

Thanks,

**Comment by dougaitken** [comment]
> it process order but does not redirects to thank you page. http://prntscr.com/jtpwkx this is what it says, internal server page.

That sounds like your issue @adbergmedia - please disable both of the custom thank you page plugins and try again.
