### ISSUE TITLE
Rest API - Image position incorrect handled when more than 9

### ISSUE THREAD

**Issue by steffanhalv** [woocommerce/woocommerce#20485]
**Describe the bug**

Positions is going crazy for images when stored using rest api & amount of images is more than 9.

I would guess you are sorting alphabetically instead of numeric when verifying positions, because its correct when image amount is below 10.

So instead of sorting like this: 0, 1, 2, 3 .. 10, 11, 12 you are doing this 0, 1, 11, 12 .. 1, 10, 11

**Endpoint:**
wc/v2/products/15?_method=PUT?images[0][id]=...&images[0][position]=...

**To Reproduce**
1. Create a product with more than 9 images
2. Sort them changing image positions
3. Check response
4. Positions is now not set as requested

**Expected behavior**
Positions should be stored as requested

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
It's not sorted at all, it just uses the order in which you specify them.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20497
