### ISSUE TITLE
Plugin showing Woocommerce error messages before successfully submitting

### ISSUE THREAD

**Issue by fariazz** [woocommerce/woocommerce#20493]
**Describe the bug**
When submitting a Stripe order using the inline card form, Stripe submits the checkout form twice. The first time triggers lots of error messages on the checkout page. The second time the order completes successfully. I've recorded a screencast that shows what's happening: https://www.youtube.com/watch?v=B_Md5qEQV78 (watch it all the way for the parameters in the ajax calls)

**To Reproduce**
Steps to reproduce the behavior in our site (can't be tested now as we've disabled Stripe):
1- Add a product to the cart
2- On the checkout page, enter a credit card (either test mode or live mode)
3- Submit

**Expected behavior**
No error messages are shown, the user is redirected to the Order Received page

**Observed behavior**
Woocommerce error messages are shown, then the user is redirected to Order Received page.

Error message shown are "We are unable to process your order, please try again" and "Sorry your session has expired"

When inspecting the console, it seems that what happens is once clicking "Place Order", Stripe submits the checkout form but without the required WP Nounce `_wpnounce`. That request generates those error messages. Then a few seconds later Stripe decides to try a second submission of the checkout form, this time with the required nounce and all the expected parameters, with that the order order completes without issues and the user is taken to the Order Received page.

So this all comes down to getting rid of that first checkout form submission Stripe is doing.

**Screenshots**
You've got a full screencast here:  https://www.youtube.com/watch?v=B_Md5qEQV78

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WC Version: 3.2.6
WP Version: 4.9.4

Anywhere I can send the full report to? not keen on sharing this publicly as it contains way too much info about our infrastructure.
</details>

**Comment by rodrigoprimo** [comment]
Thanks for your report, @fariazz. This issue tracker is used only for WooCommerce core. If you believe you found a WooCommerce Gateway Stripe bug, please open a new issue on the corresponding repository: https://github.com/woocommerce/woocommerce-gateway-stripe

Are you able to reproduce this issue on a fresh WooCommerce core + WooCommerce Gateway Stripe install? I'm asking because my first guess is that a conflict with another plugin that you have enabled on the site is causing this problem.

If you believe this is a WooCommerce core bug, could you please test it again using WooCommerce master branch and reopen this issue?

**Comment by mikejolley** [comment]
@rodrigoprimo I also tested this just now with 4.1.7. There was no double posting. Missing nonce suggests the checkout form may have been customised. It certainly looks different from the core checkout with default theme in that video.
