### ISSUE TITLE
Clearing WooCommerce transients

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#20494]
Hello,

When I use your tools to clear transients, it does not clear the **wc_layered_nav_counts_** transient. It is important. Because the wc_layered_nav_counts_ transient usually is big. And it makes database size big.

Thank you!

**Comment by mikejolley** [comment]
You can disable that transient if DB size is more important to you than caching. `woocommerce_layered_nav_count_maybe_cache`

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20498

**Comment by stormit** [comment]
Hello Mike,

It seems that your team removed code which clears the **wc_layered_nav_counts_** transient. Please check it again.

Thank you!
