### ISSUE TITLE
WooCommerce auto-generating API keys for app needs to have legacy api checked.

### ISSUE THREAD

**Issue by pmm1** [woocommerce/woocommerce#20496]
I'm generating API keys for users to use the WooCommerce API using this endpoint: _/wc-auth/v1/authorize._

Details here:
[http://woocommerce.github.io/woocommerce-rest-api-docs/#rest-api-keys](http://woocommerce.github.io/woocommerce-rest-api-docs/#rest-api-keys)

To get this to work I need to go to WooCommerce settings and toggle the "Enable legacy api" box.

This is bad UX if we have to ask users to toggle this box, is there no way around this?

It says in the docs that one must use the _/wc-auth/v1/authorize_  endpoint, is there no v2 of this endpoint?

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20499

There is no v2 for this endpoint. It is separate from the rest of the API.
