### ISSUE TITLE
Rounding issue with tax / cart totals

### ISSUE THREAD

**Issue by E-VANCE** [woocommerce/woocommerce#20505]
## Describe the bug
The cart totals sometimes produce a sum of xxx.01 EUR although the products involved (including tax) are not priced that way and this is happening more and more over the last few days / weeks.

This seems to be arounding issue and I've stumbled upon [this recent issue](https://github.com/woocommerce/woocommerce/issues/20440) which seems to be highly related, the only difference being that we already had unchecked the "Round tax at subtotal level, instead of rounding per line"-setting – re-enabling it renders the correct total sum but then the VAT is off by one cent...

The products themselves are setup correctly and since we didn't have any issues some months ago this points towards a bug with a current WooCommerce-version.

## To Reproduce
1. Create a manual order
2. Add products to cart
3. Caculate sum

## Screenshots

Description | Screenshot
:--- | :---
"Round tax at subtotal level, instead of rounding per line" **unchecked** | [Link](https://d.pr/free/i/zGpvLr)
"Round tax at subtotal level, instead of rounding per line" **checked** | [Link](https://d.pr/free/i/cMSarH)

## Isolating the problem

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
    
    ### WordPress Environment ###

    Home URL: http://dev.holzspielwaren-ackermann.de
    Site URL: http://dev.holzspielwaren-ackermann.de
    WC Version: 3.4.2
    Log Directory Writable: ✔
    WP Version: 4.9.6
    WP Multisite: –
    WP Memory Limit: 512 MB
    WP Debug Mode: ✔
    WP Cron: ✔
    Language: de_DE
    External object cache: –

    ### Server Environment ###

    Server Info: Apache
    PHP Version: 7.0.30 - Wir empfehlen
    PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisierst du deine PHP-Version

    PHP Post Max Size: 8 MB
    PHP Time Limit: 60
    PHP Max Input Vars: 1000
    cURL Version: 7.22.0
    OpenSSL/1.0.1

    SUHOSIN Installed: –
    MySQL Version: ❌ 5.5.54-0ubuntu0.12.04.1-log - Wir empfehlen mindestens MySQL-Version 5.6. Siehe: WordPress-Anforderungen
    Max Upload Size: 8 MB
    Default Timezone is UTC: ✔
    fsockopen/cURL: ✔
    SoapClient: ✔
    DOMDocument: ✔
    GZip: ✔
    Multibyte String: ✔
    Remote Post: ✔
    Remote Get: ✔

    ### Database ###

    WC Database Version: 3.4.2
    WC Database Prefix: ack_
    Datenbank-Gesamtgröße: 113.09MB
    Datenbank-Datengröße: 73.76MB
    Datenbank-Indexgröße: 39.33MB
    ack_woocommerce_sessions: Daten: 0.08MB + Index: 0.02MB
    ack_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
    ack_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.01MB
    ack_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB
    ack_woocommerce_order_items: Daten: 1.24MB + Index: 0.94MB
    ack_woocommerce_order_itemmeta: Daten: 10.48MB + Index: 8.13MB
    ack_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.01MB
    ack_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB
    ack_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
    ack_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB
    ack_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
    ack_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
    ack_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
    ack_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
    ack_apto: Daten: 0.02MB + Index: 0.02MB
    ack_apto_sort_list: Daten: 0.02MB + Index: 0.02MB
    ack_commentmeta: Daten: 0.28MB + Index: 0.26MB
    ack_comments: Daten: 2.38MB + Index: 1.02MB
    ack_ewwwio_images: Daten: 3.06MB + Index: 2.21MB
    ack_faq_termmeta: Daten: 0.02MB + Index: 0.00MB
    ack_followup_coupons: Daten: 0.00MB + Index: 0.00MB
    ack_followup_coupon_logs: Daten: 0.00MB + Index: 0.00MB
    ack_followup_customers: Daten: 0.08MB + Index: 0.15MB
    ack_followup_customer_carts: Daten: 2.52MB + Index: 0.14MB
    ack_followup_customer_notes: Daten: 0.02MB + Index: 0.03MB
    ack_followup_customer_orders: Daten: 0.06MB + Index: 0.07MB
    ack_followup_emails: Daten: 0.00MB + Index: 0.00MB
    ack_followup_email_coupons: Daten: 0.00MB + Index: 0.00MB
    ack_followup_email_excludes: Daten: 0.00MB + Index: 0.00MB
    ack_followup_email_logs: Daten: 0.00MB + Index: 0.00MB
    ack_followup_email_orders: Daten: 0.00MB + Index: 0.01MB
    ack_followup_email_order_coupons: Daten: 0.00MB + Index: 0.00MB
    ack_followup_email_tracking: Daten: 0.00MB + Index: 0.00MB
    ack_followup_followup_history: Daten: 0.02MB + Index: 0.05MB
    ack_followup_order_categories: Daten: 0.17MB + Index: 0.29MB
    ack_followup_order_items: Daten: 0.36MB + Index: 0.62MB
    ack_followup_subscribers: Daten: 0.02MB + Index: 0.03MB
    ack_followup_subscribers_to_lists: Daten: 0.02MB + Index: 0.03MB
    ack_followup_subscriber_lists: Daten: 0.02MB + Index: 0.03MB
    ack_itsec_distributed_storage: Daten: 0.02MB + Index: 0.02MB
    ack_itsec_lockouts: Daten: 0.09MB + Index: 0.11MB
    ack_itsec_logs: Daten: 8.52MB + Index: 0.67MB
    ack_itsec_temp: Daten: 0.02MB + Index: 0.06MB
    ack_links: Daten: 0.00MB + Index: 0.00MB
    ack_lockdowns: Daten: 0.00MB + Index: 0.00MB
    ack_login_fails: Daten: 0.01MB + Index: 0.00MB
    ack_options: Daten: 1.91MB + Index: 0.09MB
    ack_postmeta: Daten: 18.59MB + Index: 9.58MB
    ack_posts: Daten: 3.99MB + Index: 0.48MB
    ack_PO_plugins: Daten: 0.00MB + Index: 0.00MB
    ack_ps_exclude: Daten: 0.02MB + Index: 0.02MB
    ack_ps_keyword: Daten: 0.02MB + Index: 0.00MB
    ack_ps_postmeta: Daten: 0.02MB + Index: 0.03MB
    ack_ps_posts: Daten: 0.06MB + Index: 0.00MB
    ack_ps_product_categories: Daten: 0.02MB + Index: 0.00MB
    ack_ps_product_sku: Daten: 0.02MB + Index: 0.00MB
    ack_ps_product_tags: Daten: 0.02MB + Index: 0.00MB
    ack_ps_term_relationships: Daten: 0.05MB + Index: 0.02MB
    ack_redirection_404: Daten: 6.29MB + Index: 1.79MB
    ack_redirection_groups: Daten: 0.00MB + Index: 0.00MB
    ack_redirection_items: Daten: 0.10MB + Index: 0.08MB
    ack_redirection_logs: Daten: 0.01MB + Index: 0.01MB
    ack_revslider_css: Daten: 0.00MB + Index: 0.00MB
    ack_revslider_layer_animations: Daten: 0.00MB + Index: 0.00MB
    ack_revslider_settings: Daten: 0.00MB + Index: 0.00MB
    ack_revslider_sliders: Daten: 0.00MB + Index: 0.00MB
    ack_revslider_slides: Daten: 0.02MB + Index: 0.00MB
    ack_revslider_static_slides: Daten: 0.02MB + Index: 0.00MB
    ack_rg_form: Daten: 0.00MB + Index: 0.00MB
    ack_rg_form_meta: Daten: 0.06MB + Index: 0.00MB
    ack_rg_form_view: Daten: 0.00MB + Index: 0.00MB
    ack_rg_lead: Daten: 0.01MB + Index: 0.00MB
    ack_rg_lead_detail: Daten: 0.03MB + Index: 0.03MB
    ack_rg_lead_detail_long: Daten: 0.02MB + Index: 0.00MB
    ack_rg_lead_meta: Daten: 0.02MB + Index: 0.03MB
    ack_rg_lead_notes: Daten: 0.00MB + Index: 0.00MB
    ack_smartgoogleadwords: Daten: 0.00MB + Index: 0.00MB
    ack_swp_cf: Daten: 0.02MB + Index: 0.05MB
    ack_swp_index: Daten: 3.52MB + Index: 4.03MB
    ack_swp_log: Daten: 2.52MB + Index: 3.50MB
    ack_swp_tax: Daten: 0.08MB + Index: 0.08MB
    ack_swp_terms: Daten: 1.52MB + Index: 0.92MB
    ack_termmeta: Daten: 0.08MB + Index: 0.11MB
    ack_terms: Daten: 0.06MB + Index: 0.09MB
    ack_term_relationships: Daten: 0.06MB + Index: 0.11MB
    ack_term_taxonomy: Daten: 0.03MB + Index: 0.06MB
    ack_usermeta: Daten: 4.28MB + Index: 2.73MB
    ack_users: Daten: 0.33MB + Index: 0.26MB
    ack_wc_download_log: Daten: 0.02MB + Index: 0.03MB
    ack_wc_webhooks: Daten: 0.02MB + Index: 0.02MB
    ack_woocommerce_paydirektcw_customer_contexts: Daten: 0.02MB + Index: 0.02MB
    ack_woocommerce_paydirektcw_documents: Daten: 0.02MB + Index: 0.02MB
    ack_woocommerce_paydirektcw_ecc: Daten: 0.02MB + Index: 0.00MB
    ack_woocommerce_paydirektcw_schema_version: Daten: 0.02MB + Index: 0.02MB
    ack_woocommerce_paydirektcw_storage: Daten: 0.02MB + Index: 0.00MB
    ack_woocommerce_paydirektcw_transactions: Daten: 0.06MB + Index: 0.00MB
    ack_wpmm_subscribers: Daten: 0.02MB + Index: 0.00MB
    ack_yith_wcwl: Daten: 0.00MB + Index: 0.00MB
    ack_yoast_seo_links: Daten: 0.02MB + Index: 0.02MB
    ack_yoast_seo_meta: Daten: 0.05MB + Index: 0.00MB

    ### Post Type Counts ###

    apto_sort: 46
    attachment: 975
    contactform: 1
    customize_changeset: 1
    faq: 6
    featurestab: 1
    foobar: 1
    nav_menu_item: 73
    page: 27
    portfolios: 9
    post: 43
    product: 257
    product_variation: 253
    revision: 517
    scheduled-action: 32
    shop_coupon: 4
    shop_order: 3599
    shop_order_refund: 7
    sliders: 1
    wc_order_status: 8

    ### Security ###

    Secure connection (HTTPS): ❌
              Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
    Hide errors from visitors: ❌Fehlermeldungen sollten Besuchern nicht angezeigt werden.

    ### Active Plugins (1) ###

    WooCommerce: von Automattic – 3.4.2

    ### Settings ###

    API Enabled: –
    Force SSL: –
    Currency: EUR (€)
    Currency Position: right_space
    Thousand Separator: .
    Decimal Separator: ,
    Number of Decimals: 2
    Taxonomies: Product Types: external (external)
    grouped (grouped)
    simple (simple)
    variable (variable)

    Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
    exclude-from-search (exclude-from-search)
    featured (featured)
    outofstock (outofstock)
    rated-1 (rated-1)
    rated-2 (rated-2)
    rated-3 (rated-3)
    rated-4 (rated-4)
    rated-5 (rated-5)

    ### WC Pages ###

    Shop-Basis: #977 - /shop
    Warenkorb: #7 - /warenkorb
    Kasse: #8 - /kasse
    Mein Konto: #10 - /kundenkonto
    Allgemeine Geschäftsbedingungen: #1282 - /agb

    ### Theme ###

    Name: Storefront
    Version: 2.3.2
    Author URL: https://woocommerce.com/
    Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
    das du nicht selbst entwickelt hast
    an eigene Bedürfnisse anpasst
    dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

    WooCommerce Support: ✔

    ### Templates ###

    Overrides: –
</details>

**Comment by mikejolley** [comment]
@E-VANCE Really not enough details here to reproduce an issue. Need to know:

- Tax rates
- Product prices
- Shipping cost
- What to add to cart

Also I see plugins have been deactivated, but you'd need to place another order to rule them out, since the data won't be updated once saved to an order.

**Comment by E-VANCE** [comment]
Sure thing:

**Tax rate**
19%

**Product prices**
6,- EUR – 6,- EUR – 4,50 EUR (each including VAT)

**Shipping costs**
Flatrate shipping of 5,40 EUR (also set to include VAT / taxes but they don't show on the order...)

**What to add to cart**
Not sure what you are refering to here...?

> Also I see plugins have been deactivated, but you'd need to place another order to rule them out, since the data won't be updated once saved to an order.

I have placed a new order on the frontend and here the sum shows up correctly...! If I go ahead and re-calculate the sum in the backend then the one cent is added again. Quite strange.

**Screenshots**
- [Frontend](https://d.pr/free/i/j7e00X)
- [Backend](https://d.pr/free/i/TEPD2T) (after re-calc)

**Comment by mikejolley** [comment]
> I have placed a new order on the frontend and here the sum shows up correctly...! If I go ahead and re-calculate the sum in the backend then the one cent is added again. Quite strange.

Was that the case with the original order?

Since orders are stored excl. of VAT, there are cases where recalc will cause different results, which is more a math problem than a bug which can be resolved. It's mainly due to decimals and rounding. If thats the case with the original order I can at least replicate and say if thats something which cannot be resolved from our end and needs manual adjustment.

**Comment by E-VANCE** [comment]
> Was that the case with the original order?

Not sure but when I go ahead and place an identical order then the sum on the frontend / in the cart is displayed correctly so yeah, could be that the issue is being introduced afterwards so to speak...

> Since orders are stored excl. of VAT, there are cases where recalc will cause different results, which is more a math problem than a bug which can be resolved. It's mainly due to decimals and rounding. If thats the case with the original order I can at least replicate and say if thats something which cannot be resolved from our end and needs manual adjustment.

Seeing that we cannot edit an order once it is being processed or the invoice has been generated (not sure which applies) this leaves us with no option to manually adjust it. Why are the orderes stored excl. of VAT in the first place?

Anyhow, we need the invoice / order to reflect the correct price, otherwise the German tax authorities and the clients ordering the product will be inquiring about that.

Could one simply round the final sum if it differs from the calculated sum incl. VAT? So check if the final numbers are off and overwrite with the incl. VAT one then?

Thanks for taking the time.

**Comment by mikejolley** [comment]
Shipping costs are entered excl. of vat. To get 5.40 I'd need to enter 4.54, which would give taxes of 3.50. However, your screenshot does not show those shipping taxes. Looks wrong?

For now I've disabled tax on shipping to match your results.

After placing the order with the correct totals, editing the rows shows the precision under which the price are stored:

![edit order wordpress wordpress 2018-06-14 12-15-06](https://user-images.githubusercontent.com/90977/41409035-a12f05b8-6fcc-11e8-9a43-277ca63b43c2.png)

After recalc the line costs stayed the same. But the total did indeed increase by 1p. Seeing if it's something that can be rectified.

**Comment by mikejolley** [comment]
Got it; cart rounds item price when calculating the final total, order does not.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20533
