### ISSUE TITLE
Tax Class: Same as Parent, not working with Variations

### ISSUE THREAD

**Issue by DustinHartzler** [woocommerce/woocommerce#20509]
**Describe the bug**
When a variation is set up to inherit the parent's tax class, it doesn't calculate any tax.

**To Reproduce**
1. Create a new product with variations
2. Set the tax class to Standard at the product level
3. Set a variation product's tax class to _Same as Parent_
4. Try to calculate tax on checkout - no tax calculated
5. Change variation's tax class to _Standard_
6. Try to checkout and tax is calculated.

**Screenshots**
![2018-06-12 at 3 10 pm](https://user-images.githubusercontent.com/2293077/41311622-c25c0072-6e52-11e8-8a26-fcada9fe4b67.png)

**Expected behavior**
I expect either setting to calculate the Standard rate tax as defined in the Tax Settings.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://woo.dev
Site URL: https://woo.dev
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.5
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wpstg0_
MaxMind GeoIP Database: ✔
Total Database Size: 28.02MB
Database Data Size: 21.33MB
Database Index Size: 6.69MB
wpstg0_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpstg0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpstg0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpm4_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpm4_atum_order_items: Data: 0.02MB + Index: 0.02MB
wpm4_commentmeta: Data: 0.02MB + Index: 0.03MB
wpm4_comments: Data: 0.02MB + Index: 0.09MB
wpm4_failed_jobs: Data: 0.02MB + Index: 0.00MB
wpm4_layerslider: Data: 0.02MB + Index: 0.00MB
wpm4_layerslider_revisions: Data: 0.02MB + Index: 0.00MB
wpm4_lecm_import: Data: 0.05MB + Index: 0.02MB
wpm4_lecm_recent: Data: 0.02MB + Index: 0.00MB
wpm4_lecm_update: Data: 0.02MB + Index: 0.02MB
wpm4_lecm_user: Data: 0.02MB + Index: 0.00MB
wpm4_links: Data: 0.02MB + Index: 0.02MB
wpm4_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wpm4_masterslider_options: Data: 0.05MB + Index: 0.02MB
wpm4_masterslider_sliders: Data: 0.02MB + Index: 0.03MB
wpm4_options: Data: 3.48MB + Index: 0.09MB
wpm4_postmeta: Data: 2.52MB + Index: 1.92MB
wpm4_posts: Data: 1.52MB + Index: 0.13MB
wpm4_queue: Data: 0.02MB + Index: 0.00MB
wpm4_revslider_css: Data: 0.13MB + Index: 0.00MB
wpm4_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wpm4_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wpm4_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wpm4_revslider_slides: Data: 0.02MB + Index: 0.00MB
wpm4_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wpm4_slim_events: Data: 0.13MB + Index: 0.09MB
wpm4_slim_events_archive: Data: 0.02MB + Index: 0.02MB
wpm4_slim_stats: Data: 1.52MB + Index: 0.06MB
wpm4_slim_stats_archive: Data: 0.02MB + Index: 0.02MB
wpm4_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wpm4_social_users: Data: 0.02MB + Index: 0.02MB
wpm4_termmeta: Data: 0.02MB + Index: 0.03MB
wpm4_terms: Data: 0.02MB + Index: 0.03MB
wpm4_term_relationships: Data: 0.05MB + Index: 0.02MB
wpm4_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpm4_usermeta: Data: 0.09MB + Index: 0.09MB
wpm4_users: Data: 0.02MB + Index: 0.05MB
wpm4_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wpm4_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpm4_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpm4_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpm4_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpm4_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpm4_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpm4_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wpm4_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpm4_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpm4_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpm4_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB
wpm4_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpm4_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpm4_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpm4_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpm4_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpstg0_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_atum_order_items: Data: 0.02MB + Index: 0.02MB
wpstg0_bwg_album: Data: 0.02MB + Index: 0.00MB
wpstg0_bwg_album_gallery: Data: 0.02MB + Index: 0.00MB
wpstg0_bwg_gallery: Data: 0.02MB + Index: 0.00MB
wpstg0_bwg_image: Data: 0.06MB + Index: 0.00MB
wpstg0_bwg_image_comment: Data: 0.02MB + Index: 0.00MB
wpstg0_bwg_image_rate: Data: 0.02MB + Index: 0.00MB
wpstg0_bwg_image_tag: Data: 0.02MB + Index: 0.00MB
wpstg0_bwg_shortcode: Data: 0.02MB + Index: 0.00MB
wpstg0_bwg_theme: Data: 0.08MB + Index: 0.00MB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_comments: Data: 0.02MB + Index: 0.09MB
wpstg0_failed_jobs: Data: 0.02MB + Index: 0.00MB
wpstg0_layerslider: Data: 0.02MB + Index: 0.00MB
wpstg0_layerslider_revisions: Data: 0.02MB + Index: 0.00MB
wpstg0_lecm_import: Data: 0.05MB + Index: 0.02MB
wpstg0_lecm_recent: Data: 0.02MB + Index: 0.00MB
wpstg0_lecm_update: Data: 0.02MB + Index: 0.02MB
wpstg0_lecm_user: Data: 0.02MB + Index: 0.00MB
wpstg0_links: Data: 0.02MB + Index: 0.02MB
wpstg0_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wpstg0_masterslider_options: Data: 0.05MB + Index: 0.02MB
wpstg0_masterslider_sliders: Data: 0.02MB + Index: 0.03MB
wpstg0_options: Data: 3.47MB + Index: 0.11MB
wpstg0_postmeta: Data: 2.52MB + Index: 1.92MB
wpstg0_posts: Data: 1.52MB + Index: 0.14MB
wpstg0_queue: Data: 0.02MB + Index: 0.00MB
wpstg0_revslider_css: Data: 0.13MB + Index: 0.00MB
wpstg0_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wpstg0_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wpstg0_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wpstg0_revslider_slides: Data: 0.02MB + Index: 0.00MB
wpstg0_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wpstg0_slim_events: Data: 0.13MB + Index: 0.09MB
wpstg0_slim_events_archive: Data: 0.02MB + Index: 0.02MB
wpstg0_slim_stats: Data: 1.52MB + Index: 0.08MB
wpstg0_slim_stats_archive: Data: 0.02MB + Index: 0.02MB
wpstg0_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wpstg0_social_users: Data: 0.02MB + Index: 0.02MB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB
wpstg0_term_relationships: Data: 0.05MB + Index: 0.02MB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpstg0_usermeta: Data: 0.09MB + Index: 0.09MB
wpstg0_users: Data: 0.02MB + Index: 0.05MB
wpstg0_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wpstg0_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpstg0_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 288
bwg_gallery: 1
custom_css: 1
customize_changeset: 6
envira: 1
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
mkhb_header: 1
nav_menu_item: 15
page: 22
post: 7
product: 114
product_variation: 114
revision: 44
sg_optimizer_jobs: 2
shop_order: 16
wafs: 1
wc_order_status: 8
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 3.4.2
WP Staging: by WP-Staging – 2.2.9

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #1 - /?page_id=1
Cart: #2 - /?page_id=2
Checkout: #3 - /?page_id=3
My account: #4 - /?page_id=4
Terms and conditions: #7 - /?page_id=7

### Theme ###

Name: Storefront
Version: 2.3.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by kloon** [comment]
@DustinHartzler I am unable to replicate this.
![Variation Settings](http://cld.wthms.co/KPRrwr+)
![Tax Calculated Cart](http://cld.wthms.co/Cu6UGQ+)

Could you perhaps provide details on your tax settings? How are prices displayed etc?

**Comment by DustinHartzler** [comment]
One of the things that stood out is that the first variation has the tax class of *Standard* and the rest of the variations have *Same as Parent*.

I'm having a hard time getting issue to happen again. Reaching out the chatter to set up their staging site to see exact tax settings (it was disabled before I could grab screenshots).

**Comment by mikejolley** [comment]
@DustinHartzler make sure their variations don't "overlap" i.e. a different variation matched which had a different tax class.

**Comment by dogrescuer** [comment]
I came here to report the same thing. Same as parent setting is not being respected for tax calculation.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20546

**Comment by dogrescuer** [comment]
Mike sorry 20546 is not relevant to my situation. The situation popped up after no tax class changes had been made. All variations used standard class. All variations used "same as parent." In the database, parent class is blank. We didn't de-normalize it from standard. It just was blank where we asked for standard. By setting all variation classes to blank, the the variations again received standard treatment. I can't see how 20546 applies here as we didn't de-normalize the parent setting in the first place.

**Comment by mikejolley** [comment]
@dogrescuer You can't just jump into another thread with no context or details and expect us to magically solve it for you :) I looked into the site from the OP and found the issue on that site. Post on the helpdesk?

**Comment by dogrescuer** [comment]
@mikejolley  It'd be my pleasure! Where is said helpdesk?

**Comment by mikejolley** [comment]
https://woocommerce.com/contact-us/

However, you should do regular due-diligence first https://docs.woocommerce.com/document/woocommerce-self-service-guide/

Since there is no issue we can replicate, and the above was a data issue on a single site only, I doubt it's a bug in WC or we'd have more reports.

**Comment by dogrescuer** [comment]
I don't qualify for submitting a ticket at contact-us. Sorry if I misunderstood, I thought this github thread was where I was to submit bug reports. I did test on a site with the Storefront theme and only woo active. The bug was still there. Logically this appears to be a bug to me -- as the "normalization" thread touched on but did not resolve the concept involved. It appears that Standard Tax class is stored as a blank string rather than the word "Standard." When I set all of the variation tax class values to this blank string in stead of "Same as Parent," the tax worked again. So de-normalizing the data fixed the problem. I don't know how to report this to you without using github but if you advise I'll be happy to send more details. Of course I could be wrong but this appears to be a logic issue allowing a blank value to have meaning, which I think would be a bug and not site-specific.

**Comment by mikejolley** [comment]
>  It appears that Standard Tax class is stored as a blank string rather than the word "Standard."

Correct. If you have 'standard' anywhere in the database it will suffer the same issue..

**Comment by ajmsilva123** [comment]
I have a similar issue in WOO 3.7.0. With taxes turned, my prices are tax inclusive, 23% all of them, when I have variations and the tax class is set to parent or standard... it seems that the tax is not being considered. I tried to extract the product ID and TAX CLASS into a CVS and the field for class is empty. I believe there is a bug here.

**Comment by realElMartino** [comment]
Yes, I have the same problem - don't see any solution or suggestion here.

**Comment by webbcitydigital** [comment]
I had that problem a few years ago. Here is what solved the problem for us:

I just wanted to provide you an update on the issue you mentioned to us.

We did some investigation at our end, but we were unable to replicate the
same problem in our local/test sites. However, upon taking a detailed look
at your site, we were able to find the culprit.

It looks like one of your variations were erroneously assigned to a
pre-existing tax class called us-mo-rate. This wasn't supposed to happen,
as the variation should have had a blank value, to indicate standard rates,
but since there are no tax classes aside from standard it's not possible to
correct this. In the backend, we whitelist and sanitze tax classes, and
upon saving this change is not updated either.

The rate titled us-mo-rate *may* have been added due to a troublesome
import or a plugin, as I would think.

The easiest way to fix this would be as follows:

   1. Create a new tax class in *WooCommerce > Settings > Taxes*.
   2. Switch the product to the new tax class, and save the changes.
   3. Once you've saved the changes, switch the tax class for the product
   back to standard.

Additionally, we have added some checks in core WooCommerce to normalize
the parent tax class. This should come out with the latest update in
WooCommerce, as well. Please be sure to update WooCommerce to the latest
version, when the next update is out. This should fix the troubles as such.

**Comment by realElMartino** [comment]
Thanks for your reply. In my case I imported products from an existing site. All variations were created using 'parent' in the DB. However, also the parent had 'parent' set - not sure if that was right. We only use one single tax class as we only sell in one country with one tax class applying to all. I've read the other comment and decided to set all tax-classes to an empty string in the DB and then it worked. All plugins are up to date. There are other issues with tax display in countries outside areas where you use VAT as identifier. Had to manually change things in the woo commerce code to get that working as as there was only VAT or TAX and when using GST where you can configure it it does not work as the functions in the code only do VAT or TAX.
However, as the frontend showed everything right with the variation configuration this must be a bug.
