### ISSUE TITLE
Related Products broken if tabs not visible

### ISSUE THREAD

**Issue by DarkPain0** [woocommerce/woocommerce#20510]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Go to Products
2. Click on Add new
3. Publish product without description or short description
4. View

**Screenshots**
https://screenshots.firefox.com/3Rrm6ef7gjrShLio/myecoach.com

**Expected behavior**
Product with images and description should be visible on top. Related products below.

**WordPress Environment**
Shared Hosting
PHP 7
MYSQL 5.5
Wordpress 4.9.6
Woocommerce 3.4.2
</details>

**Comment by kloon** [comment]
@DarkPain0 what theme are you using? I tested with Twentyseventeen and Storefront which are default themes and the related products show up fine for me http://cld.wthms.co/CZPGAf

Try switching to one of those themes and test again.
