### ISSUE TITLE
Product with variations added through REST loading variations very slowly

### ISSUE THREAD

**Issue by jjcoffee** [woocommerce/woocommerce#20517]
**Describe the bug**
I've added variations to an already existing product via REST (as there were 48 of them!), everything went fine until I tested the product page itself and noticed each time a variation is selected it took almost 5 seconds to load. See this product here: https://www.juliajones.co.uk/shop/lounge-furniture/cadiz-corner-sofa-rest/

After some investigating I've ruled out the swatches plugin we're using (same behaviour happens with drop-downs), but in the process realised that a duplication of the product results in variations loading fine on the duplicate: https://www.juliajones.co.uk/shop/lounge-furniture/cadiz-corner-sofa/

This particular product has a few attributes that don't affect price, so when I've updated via REST I've only passed in the attribute id+ option name of ones that *do* affect price. Could this be what's throwing it off?

Or any other ideas of what could be going on here?

**To Reproduce**
Will add more details as I find them, but it seems to be just adding a large(ish) number of variations (I had 48 variations, with 6 attributes, 3 of which actually affect the price).

**Comment by mikejolley** [comment]
When you have > 30 variations it does an AJAX request to your server to get a match. The speed of that is determined by many factors.

You can avoid this by increasing the threashold for ajax being turned on: https://iconicwp.com/blog/modify-ajax-variation-threshold/

Just be aware that means more variations are loaded at once on your page. 

Thanks

**Comment by jjcoffee** [comment]
Thanks, I didn't know about the AJAX threshhold! That still doesn't explain why one product loads slow (~6s), whereas the duplicate loads fast (<1s) though... Any ideas?

**Comment by mikejolley** [comment]
If you compare them in the database, does one perhaps have more meta data or terms? Do you have rules e.g. pricing rules for one not the other? Could be a lot of factors.
