### ISSUE TITLE
wp-admin/edit.php?post_type=shop_order showing white blank page

### ISSUE THREAD

**Issue by matz1237** [woocommerce/woocommerce#20511]
**Describe the bug**
While clicking on woocomerce>order I see a blank page.
I tried to find a solution online and tried all methods but problem not solved.
As well tried to debug but I have no clue how it works and where logs are saved.
As well I tried to check f12 console no errors and body HTML tag is empty check-in the screenshot below

**To Reproduce**
1. Go to 'woocommerce'
2. Click on 'order'

**Screenshots**
http://prntscr.com/juawyn

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.30 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.1.31-MariaDB-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 25.07MB
Database Data Size: 17.18MB
Database Index Size: 7.89MB
wp_woocommerce_sessions: Data: 0.24MB + Index: 0.01MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.17MB + Index: 0.07MB
wp_woocommerce_order_itemmeta: Data: 0.93MB + Index: 0.67MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
g2apay_payments: Data: 0.11MB + Index: 0.02MB
g2apay_subscriptions: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.01MB + Index: 0.01MB
wp_comments: Data: 0.52MB + Index: 0.22MB
wp_duplicator_packages: Data: 0.00MB + Index: 0.00MB
wp_fswcwallet: Data: 0.00MB + Index: 0.00MB
wp_fswcwallet_requests: Data: 0.00MB + Index: 0.00MB
wp_fswcwallet_transaction: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.84MB + Index: 0.07MB
wp_postmeta: Data: 6.38MB + Index: 3.90MB
wp_posts: Data: 0.98MB + Index: 0.22MB
wp_stream: Data: 0.33MB + Index: 0.27MB
wp_stream_meta: Data: 0.76MB + Index: 0.69MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.01MB + Index: 0.01MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.01MB
wp_usermeta: Data: 1.72MB + Index: 0.88MB
wp_users: Data: 0.11MB + Index: 0.14MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_fs_licensed_products: Data: 0.00MB + Index: 0.01MB
wp_wc_fs_product_licenses_keys: Data: 0.26MB + Index: 0.01MB
wp_wc_fs_product_licenses_keys_generator_rules: Data: 0.00MB + Index: 0.00MB
wp_wc_product_licences: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.01MB + Index: 0.01MB
wp_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.00MB + Index: 0.00MB
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 1.31MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.01MB + Index: 0.01MB
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB
wp_wfFileMods: Data: 0.38MB + Index: 0.08MB
wp_wfHits: Data: 1.03MB + Index: 0.23MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.01MB + Index: 0.01MB
wp_wfKnownFileList: Data: 0.73MB + Index: 0.09MB
wp_wfLeechers: Data: 0.06MB + Index: 0.06MB
wp_wfLiveTrafficHuman: Data: 0.01MB + Index: 0.02MB
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.00MB + Index: 0.00MB
wp_wfLogins: Data: 0.12MB + Index: 0.03MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfNotifications: Data: 0.00MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_wfScanners: Data: 0.00MB + Index: 0.01MB
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.11MB + Index: 0.05MB
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl_lists: Data: 0.01MB + Index: 0.04MB
wp_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 67
custom_css: 3
et_pb_layout: 9
nav_menu_item: 34
page: 12
post: 4
product: 52
product_variation: 153
revision: 6
shop_order: 2253
yith_wcps_type: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (30) ###

FS License Manager: by Firas Saidi – 2.4.4 – Not tested with the active version of WooCommerce
FS WooCommerce Wallet: by Firas Saidi – 1.2.1 – Not tested with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.0.7
BackWPup: by Inpsyde GmbH – 3.5.1
Payment Gateway Based Fees and Discounts for WooCommerce: by Algoritmika Ltd – 2.3.3 – Not tested with the active version of WooCommerce
Divi Builder: by Elegant Themes – 2.6
Divi Logo Swap: by Tim Strifler – 1.0
Divi Product Carousel Module: by Divi Life — Tim Strifler – 1.0 – Not tested with the active version of WooCommerce
Duplicator: by Snap Creek – 1.2.40
PayPal Express Checkout for WooCommerce: by wpgateways – 3.0.3 – Not tested with the active version of WooCommerce
WooCommerce G2A Pay Payment Gateway: by G2A Team – 1.5 – Not tested with the active version of WooCommerce
Maintenance: by fruitfulcode – 3.6.1
Q2W3 Fixed Widget: by Max Bond – 5.1.4
reSmush.it Image Optimizer: by reSmush.it – 0.1.15
Stream: by XWP – 3.2.3
Tawk.to Live Chat: by Tawkto – 0.3.4
User Menus: by Jungle Plugins – 1.1.2
User Role Editor: by Vladimir Garagulya – 4.43
Widget Importer & Exporter: by churchthemes.com – 1.5.3
Advanced Order Export For WooCommerce: by AlgolPlus – 1.5.5
Advanced AJAX Product Filters for WooCommerce: by BeRocket – 1.2.5 – Not tested with the active version of WooCommerce
WooCommerce Extra Charges To Payment Gateway (Standard): by hemsingh1 – 1.0.12.9 – Not tested with the active version of WooCommerce
Woocommerce Quick View Pro: by phoeniixx – 1.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.2
Wordfence Security: by Wordfence – 7.1.7
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO: by Team Yoast – 7.6.1
WP Fastest Cache: by Emre Vona – 0.8.8.1
WP Image Zoom: by SilkyPress – 1.25 – Not tested with the active version of WooCommerce
YITH WooCommerce Wishlist: by YITHEMES – 2.2.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #76 - /shop/
Cart: #77 - /cart/
Checkout: #78 - /checkout/
My account: #79 - /my-account/
Terms and conditions: #737 - /terms-of-service/

### Theme ###

Name: RoyalCommerce
Version: 1.0.0
Author URL: https://divilife.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.6
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by kloon** [comment]
@matz1237 I am unable to replicate this, please check your PHP error for details as to what might be causing this, most likely a plugin or theme conflict.

I suggest you disable all plugins except WooCommerce and switch to a default theme like Twentyseventeen or Storefront and then test again. You can enable plugins one by one testing in between to find the offending plugin and then switch your theme back.

**Comment by matz1237** [comment]
I have already tried disabling all plugins and switch to default theme still i have same problem.

**Comment by kloon** [comment]
Can you please provide details of what your PHP Error Log states so I can identify what is causing the issue.

**Comment by matz1237** [comment]
may I know where can I find it?

**Comment by kloon** [comment]
Your hosting provider should be able to provide you with details on where to find it for your site, each host normally have it in a different location so best to contact them for details on where to find it.

**Comment by matz1237** [comment]
http://prntscr.com/judx9w

Now I can access orders but cant access complete orders as well i see only recent 5mins back orders cant see all

**Comment by matz1237** [comment]
http://prntscr.com/jueznf

Was trying to search something and accidentally I clicked on order sorting then it started showing old orders but when I clicked again on order sorting it shows only 1 entry which is recent order

**Comment by TandelK** [comment]
Do we have update on this ?

**Comment by kloon** [comment]
I am waiting for the error log so I can look into what might be the cause here.

**Comment by matz1237** [comment]
May i have your email id so i can mail you error log

**Comment by matz1237** [comment]
@kloon  I'm able to find the problem that order is not reading the post id from the database and this error has occurred when I installed a plugin [express paypal](https://wordpress.org/plugins/express-checkout/) by wpgateways. And payment made through this plugin made that order id/ post ID is not accessible/editable. 
So now I have replaced the plugin with proper [express PayPal](https://wordpress.org/plugins/woocommerce-gateway-paypal-express-checkout/) plugin by woocommerce but problem not get solved so I want more info about it shall I delete those post entry from the database?

After deleting those post entry from the database will I have any kind of issues?
Or provide me with any other way to get rid of this without deleted entries so that I can have my data in there as I have some complete orders in it.

http://prntscr.com/julu42
I was able to find by changing this post id in the URL bar and tried all post ids which are not accessible.
So the conclusion is when I try ids with problems show blank page and rest which are old and new one are editable

**Comment by kloon** [comment]
You should not have any issues deleting it, unless you need to order in the system for reporting purposes then you numbers would be out by that order.

**Comment by kloon** [comment]
What happens when you disable the payment gateway plugin causing the issue? To be honest the issue is not in WooCommerce but with the payment gateway doing something strange so it would be up to those developers to fix it, that is the only way I see how it can work.

So either remove the payment gateway completely from your site, ie disable the plugin and remove it, or contact the developers of the gateway for support on how to resolve this. This repository is only for WooCommerce core related issues and we cannot support 3rd party themes and extensions here.

**Comment by TandelK** [comment]
@kloon I am working with this guy for the same thing. Now the issue is that when we had Paypal Express Checkout plugin by wpgateways instead of Official WooCommerce Paypal Express, the Orders ID were not coming properly in Orders page due to some weird issue. We have every order in our Database but cannot acccess them via Frontend or backend. We require a workaround something fix in Database that will allow us to show those order made by the gateway to show in our Orders area.

**Comment by kloon** [comment]
Can anyone please post an entry from the PHP error log which identifies this issue, perhaps then I can give you an idea of what to do?

**Comment by matz1237** [comment]
@kloon may I have Ur email is so I can mail you the error_log

**Comment by kloon** [comment]
gerhard at automattic dot com

**Comment by matz1237** [comment]
@kloon I have mailed you  please have a look

**Comment by kloon** [comment]
@matz1237 thanks, got it and had a look. As suspected the issue is is with the gateway. I am assuming it has not been updated in quite some time as it is making function calls that are no longer supported in WooCommerce core, it not using the getter and setter methods and this is resulting in errors.

I am also noticing your theme is giving quite a lot of these errors as well, perhaps also check if there is not an update available for that.

Unfortunately, this is way beyond the scope to be handled here. My suggestion would be to either try and get in contact with the developers of the gateway and have them look into this for you, and also update Divi to the latest version and see if that fixes the issue for you.

Alternatively as a test disable the gateway plugin, orders will stay in the DB, and switch your theme to Storefront or Twentyseventeen temporarily to test.

If you have purchased a product from WooCommerce.com then you can get support through there as well, but we do not offer support in Github.

**Comment by matz1237** [comment]
@kloon thanks for infos let me contact that paypal express plugin devloper and find the issue .

DIVI theme is  upto date.
But still I will msg the developer of DIVI to get DIVI related issues to be fixed.

Already disabled that plugin and using default woocommerce PayPal integrated gateway . 

Thanks for your time and information

**Comment by whiskermen** [comment]
We are having the exact same issue but are not using a PayPal plugin, PayPal built into WooCommerce.

I get a blank page when going to wp-admin/edit.php?post_type=shop_order but I can view individual orders by going to wp-admin/post.php?post=ORDERNUMBER&action=edit

This just started on its own. I made no updates. I did perform the latest WooCommerce update to see if you would fix the problem but it did not.

**Comment by matz1237** [comment]
@whiskermen  well for me it's not yet solved as the developer of plugin never replied. but I think your site has any other pay mode amazon/stripe?

**Comment by makeonlineshop** [comment]
@whiskermen

Good to find your post, I have exactly the same problem ! I can access orders but not the order list.

Did you find a solution ?!

I am ok to lose all my old orders but would like to have a working order list in the future.

Thank you.

**Comment by matz1237** [comment]
@makeonlineshop well not able to find the solution but once you keep getting new orders the old orders which are affected will go back side and you will be able to access the new order easily

**Comment by makeonlineshop** [comment]
Thank you, do you mean that when you get new orders you can finally access the orders list page ? Or only specific orders with direct link to them ?
I can always access orders with direct links, but not anymore the orders list page at
/wp-admin/edit.php?post_type=shop_order

**Comment by DrMTR** [comment]
Same issue on my site too. Someone found a sollution?

**Comment by ASAPHAANING** [comment]
I have this issue as well.

**Comment by makeonlineshop** [comment]
just use Woocommerce paypal plugin and you won't have any problem.
This faulty paypal plugin should be deleted from Wordpress but it seems that they are more busy annoying legitimate coders who really do good work.

**Comment by ASAPHAANING** [comment]
I'm pretty sure it's not related to PayPal.

**Comment by makeonlineshop** [comment]
Who said that it's  related to Paypal ? It is caused by the playpal plugin made by an idiot who doesn't even care to reply to the support messages.

**Comment by ASAPHAANING** [comment]
well of course not the company Paypal, I implied that it isn't due to the plugin since removing it doesn't solve the issue. Are you saying it corrupts the table in the database?

**Comment by makeonlineshop** [comment]
This is clearly what it does ! it corrupts the DB by adding some incorrect data.
I had the problem on many shops.

**Comment by ASAPHAANING** [comment]
Damn. Thanks buddy, do you know what it adds or how to revert? Can't afford to risk losing orders.

**Comment by MasterNS** [comment]
For all of you who's  looking for **solution:**
- find the corrupted order ID
- access database (via phpMyAdmin)
- enter table "wp_postmeta" and list all meta fields for your order (you can use "search" function where post_is is your order number)
- find meta_key "_transaction_id"....you will find here some array saved as "meta_value"
- just copy "meta_value" from another meta field called "_express_chekout_transactionid" and replace that array 
**(on correct orders these two fields have the same value: "_transaction_id" & "_express_chekout_transactionid")**
- save changes and corrupted order is accessible/fixed, all listings where this order is present works again

**Comment by ASAPHAANING** [comment]
@MasterNS Thank you! I did as you said and it fixed the single corrupt order! :)

For others, an actual update statement to correct it might look like this:

`update wp_postmeta set meta_value='62697040E62714440' where meta_key like '%transaction_id%' and post_id like '12542';`

**Comment by bootsgrid** [comment]
@MasterNS You saved my day. I have tring to fix the (order page blank ) issue on (20-02-2021) onwards.
Your solution is made my day. Thanks a lot
