### ISSUE TITLE
[Not bug] There is some issue with the WooCommerce default template. I'm using WooCommerce v3.4.2, ACF PRO v5.6.10 & WordPress v4.9.6.

### ISSUE THREAD

**Issue by MeK-KeM** [woocommerce/woocommerce#20518]
Hello everybody! Woocommerce isn't loading custom shop header and footer. It's using default footer.php and header.php files instead of default template files. 

![image](https://user-images.githubusercontent.com/26347385/41357429-9772369a-6f3f-11e8-9518-6eadcc825181.png)

Maybe it's caused because of ACF plugin (Flexible Content). If I change the template to "Twenty Seventeen", it's working fine.

There's an example for single product page, everything loads by the_content() function.

![image](https://user-images.githubusercontent.com/26347385/41357803-66c2542a-6f40-11e8-8b31-5943f6b8c3f1.png)
![image](https://user-images.githubusercontent.com/26347385/41357876-9119bbc8-6f40-11e8-8330-34e26c8f75c4.png)

Thank you for attention. Regards Rahimjon.

**Comment by mikejolley** [comment]
Hi,

Please see https://github.com/woocommerce/woocommerce/wiki/Declaring-WooCommerce-support-in-themes - this is required before custom templates will be loaded.

Thanks
