### ISSUE TITLE
Missing offline payment option: Invoice

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce#20515]
**Is your feature request related to a problem? Please describe.**
I went through the Wizard and came to the payment step. There is an accordion for offline payment options. 

![screen shot 2018-06-13 at 13 36 52](https://user-images.githubusercontent.com/5323259/41349039-e0a66fba-6f0e-11e8-85cc-03698d90cc05.png)

I did not see an option for invoicing the customer.

**Describe the solution you'd like**
I would like to see an option in the above accordion to be able to send an invoice with the products being shipped out.

**Describe alternatives you've considered (I am considering the following plugin)**
I found this plugin https://wordpress.org/plugins/woocommerce-pdf-invoices-packing-slips/

**Additional context**
I think that is it.

Thanks.

**Comment by mikejolley** [comment]
The wizard doesn't cover all gateways in existence, just our core ones. There are 3rd party options - the screen says other gateways may be available.

https://en-gb.wordpress.org/plugins/wc-invoice-gateway/ for example :)

Thanks

**Comment by paaljoachim** [comment]
Hey Mike

It would be great to get invoice included as part of the core ones. 
Anyhow thanks for the link.

Have a great weekend!
