### ISSUE TITLE
Incorrect content type in emails

### ISSUE THREAD

**Issue by lutrov** [woocommerce/woocommerce#20527]
When specifying "Multipart" as an email type when editing email templates, Woocommerce seems to specify `Content-Type: multipart/alternative` in the message header on delivery but provides only HTML content, without any plain text content.

From the way I understand it, if an email header field says `Content-Type: multipart/alternative`, then the body needs both `Content-Type: text/html` and `Content-Type: text/plain` components.

I have tested this with the _customer note_ email, which has been configured to "multipart/alternative" as the content type. The same issue could be present with other emails too.

1. When the email type is set to "Plain text": Headers say `Content-Type: text/plain`, body has only plain text. __This is correct__.
2. When the email type is set to "HTML": Headers say `Content-Type: text/html`, body has only HTML. __This is correct__.
3. When the email type is set to "Multipart": Headers say `Content-Type: multipart/alternative`, body has only HTML. __This is incorrect__.

It seems that actual "Multipart" emails haven't yet been implemented or the implementation isn't working.

**Comment by mikejolley** [comment]
Email sending plugins _can_ affect this e.g. by only sending the main body if using an API for sending.

The code to handle multipart is here: https://github.com/woocommerce/woocommerce/blob/master/includes/emails/class-wc-email.php#L260-L267

**Comment by lutrov** [comment]
We're not using any email sending plugins.

**Comment by mikejolley** [comment]
Is it just regular php mailer then?

Have you looked into the code I shared above?

**Comment by lutrov** [comment]
Yes, it's just the intrinsic WP mailer. I wrote a function to hook into the `wp_mail` filter, which just writes some debug info to a file, and as you can see, `$atts['headers']` is set to `Content-Type: multipart/alternative` but `$atts['message']` just has HTML.

[debug.zip](https://github.com/woocommerce/woocommerce/files/2104157/debug.zip)

**Comment by mikejolley** [comment]
I'll check tomorrow. Not sure where altbody goes off top of my head.

**Comment by lutrov** [comment]
No worries. Thanks.

**Comment by lutrov** [comment]
I don't know if this is gonna help you but looking at `woocommerce/includes/emails/class-wc-email.php`, I can see this:

1. In the `handle_multipart($mailer)` method `$mailer->AltBody` seems to work (the `AltBody` property does get assigned plain text.

2. By the time we get to the `send($to, $subject, $message, $headers, $attachments)` method, the $headers variable contains `Content-Type: multipart/alternative` but the `$message` variable doesn't have two body "parts" (with `boundary` markers) like I expect it to, it just has HTML.

It seems that what was assigned in `handle_multipart()` gets lost before `send()` gets executed.

**Comment by mikejolley** [comment]
`$message` won't contain both versions. `wp_mail` does not natively support multipart. Thats why we inject it into AltBody earlier; because the PHP Mailer class does:

https://github.com/WordPress/WordPress/blob/5eb452d15b4d99fcd19bc97dd53876547c7b2655/wp-includes/class-phpmailer.php#L3139

And:

https://github.com/WordPress/WordPress/blob/5eb452d15b4d99fcd19bc97dd53876547c7b2655/wp-includes/class-phpmailer.php#L3463-L3464

Viewing source of a multipart mail in mail.app lets you see the full message:

![source of invoice for order 92 2018-06-15 12-08-11](https://user-images.githubusercontent.com/90977/41465179-e281c28a-7094-11e8-8a2e-2abf869224ac.png)

Looks to be working still :)

Thanks

cc @claudiulodro
