### ISSUE TITLE
Undefined property: stdClass::$label in woocommerce/includes/admin/views/html-admin-page-addons.php

### ISSUE THREAD

**Issue by mahmoudsaeed** [woocommerce/woocommerce#20529]
**To Reproduce**
1. Go to 'Settings > Extensions'
2. See the following notice: Undefined property: stdClass::$label in /var/www/html/wordpress/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-addons.php on line 33

**Screenshots**
![image](https://user-images.githubusercontent.com/356740/41393994-837fd980-6fa8-11e8-8748-044dee3c6b4d.png)

**Comment by mikejolley** [comment]
Hi,

Not seeing that error. I believe it to be one of the extensions you're running extending this screen using `woocommerce_addons_sections` filter and providing invalid results.

You should rule out plugins and then report to the author. Note: disabling extensions won't be enough, you'll also need to ensure the transient cache is cleared. The transient name is wc_addons_sections - use https://en-gb.wordpress.org/plugins/artiss-transient-cleaner/ 'remove all transients' after disabling the other addons and then test the screen again. You'll need to do this between tests.

Once you identify the addon causing this, report to the author.

Thanks
