### ISSUE TITLE
Automatic stock status management breaks for Variations when ACF Pro is active

### ISSUE THREAD

**Issue by thomasmery** [woocommerce/woocommerce#20521]
Hi there,

This is an issue I open at the ACF team request so both team can try and resolve the issue.

cc @elliotcondon

Note: This issue has been confirmed by the ACF Team

I have tested the following with

- WP 4.9.6
- WC 3.4.2
- ACF PRO 5.6.10

with a fresh WP install, Twenty 17 theme

The issue is: 

WC now manages the stock status of its Product Variations automatically by switching it from 'Out of Stock' to 'In Stock' when the Stock qty changes (when stock management at the Variation level is activated)

If you have ACF Pro active and set a Product Variation stock qty from 0 to 1 (or more) the Stock Status does not change when the Product is updated via its 'Update' button (as opposed to using the in Variations panel 'save modifications' button)

After quite a long debugging session it appears that even though WC first does what it has to do, some code in ACF Pro (not happening with ACF 4.4) reverts the newly set stock status from 'In Stock' to 'Out of Stock'

thanks in advance

**Comment by elliotcondon** [comment]
Hi guys

Just wanted to say hi and let you know I'm hoping we can work together to figure out this issue. 
@thomasmery would you be able to upload a screen-cast demonstrating the issue? This will help the WC devs quickly replicate the problem :)

Thanks
E

**Comment by thomasmery** [comment]
Hi there,

here is a screencast

https://cl.ly/2Q21302g1C1h

let me know if that helps

thanks

**Comment by mikejolley** [comment]
@elliotcondon Hope you're not expecting me to buy ACF pro for this :p ?

Logic for status setting is here: https://github.com/woocommerce/woocommerce/blob/7a6b0d8cf55967e77678b6929a0b567b6e24a3d7/includes/abstracts/abstract-wc-product.php#L1302

Are we certain there is no ACF field setting _stock_status directly via meta update?

**Comment by elliotcondon** [comment]
Hi @mikejolley 

Do you not have a copy of ACF PRO? Please shoot me an email and I'll set you up an account: e@elliotcondon.com

Thanks for the code reference, I'll start my debugging here and try to figure out what's going on.

There isn't any specific field / logic that is overriding the meta, it looks like ACF is somehow blocking WC from working...

**Comment by mikejolley** [comment]
Thanks @elliotcondon. Odd one. Patch in https://github.com/woocommerce/woocommerce/pull/20573 Thanks

**Comment by elliotcondon** [comment]
Great work @mikejolley, you work fast!
