### ISSUE TITLE
WP CLI Update Payment Gateway Settings Doesn't Work

### ISSUE THREAD

**Issue by icegit** [woocommerce/woocommerce#20526]
I can enable payment gateways with below command:
`wp wc payment_gateway update paypal --user=1 --enable=true path=/www`

However, when I try to update a setting of the gateway, it does not seem to work. I have tried many different variables in settings parameter, however nothing seems to work. I have tried `[ ]` as said [here](https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Overview#frequently-asked-questions) too.

`wp wc payment_gateway update paypal --user=1 --settings="{'enabled':false}" --path=/www`

What I get is a success mesage, however the value is not updated.
`Success: Updated payment_gateway paypal.`

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/wiki/WC-CLI-Commands#--enabled-2

Typo?

Let me know if correcting the param doesn't work :)

**Comment by icegit** [comment]
Hi Mike,
Thanks for your response. 

I made a typo error in the above message, and apparently, it ruined my whole point :) I don't have any problem with the `--enabled=true` parameter, it works well, when I type it right :)

My problem is with the `--settings` parameter, and I am having difficulties to make it work. When I pass some value to `--settings` parameter, like mentioned in the [REST API Documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-payment-gateway) it doesn't update any value.  For example this line:

`wp wc payment_gateway update paypal --user=1 --settings="{'enabled':false}"`

What I actually want is to update the PayPal API keys by using the `--settings` parameter. I am using this `enabled` example for simplification of my problem.

**Comment by mikejolley** [comment]
Can you provide the string you're actually using? Obv not the API key but I can test it then :)

**Comment by heese** [comment]
Just in case someone stumbles over this thread and is frustrated about the lack of documentation and examples. The following command worked for me to enable the test mode of my custom payment gateway `points`:
```
wp wc payment_gateway update points --user=1 --settings="{\"test_mode\":\"yes\"}"
```
