### ISSUE TITLE
Lock tables issues

### ISSUE THREAD

**Issue by envisionops** [woocommerce/woocommerce#20528]
Hi, our live website is getting following error in logs and some of orders are not converted from pending payment to processing even after successful payment from customer. Can anyone help?
Log :
WordPress database error Deadlock found when trying to get lock; try restarting transaction for query DELETE FROM wp_options WHERE option_name LIKE '\\_transient\\_%1528939471' ORDER BY option_id LIMIT 1000; made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_Stripe->process_payment, WC_Stripe_Payment_Gateway->process_response, WC_Order->payment_complete, WC_Order->save, WC_Data_Store->update, WC_Order_Data_Store_CPT->update, Abstract_WC_Order_Data_Store_CPT->update, Abstract_WC_Order_Data_Store_CPT->clear_caches, wc_delete_shop_order_transients, WC_Cache_Helper::get_transient_version, WC_Cache_Helper::delete_version_transients

**Comment by mikejolley** [comment]
I think https://github.com/woocommerce/woocommerce/pull/20537 will help - please test that if possible and leave feedback on the pull request.

Thanks

**Comment by envisionops** [comment]
Thanks Mike, I will test and leave feedback.

**Comment by jessuppi** [comment]
For anyone needing a user-friendly cleanup approach, we use this for our Woo clients:

https://wordpress.org/plugins/delete-expired-transients-littlebizzy/

...it supports the following constants:

```
define('DELETE_EXPIRED_TRANSIENTS_HOURS', '6');
define('DELETE_EXPIRED_TRANSIENTS_MAX_EXECUTION_TIME', '10');
define('DELETE_EXPIRED_TRANSIENTS_MAX_BATCH_RECORDS', '50');
```

**Comment by mikejolley** [comment]
We removed the transactions in 3.4.3 FYI and deferred the transient cleanup - should lesson likelihood of deadlines going forward.
