### ISSUE TITLE
Can't get orders

### ISSUE THREAD

**Issue by DemianKost** [woocommerce/woocommerce#20523]
Hi everybody)

I have a problem: I can't get a list of all orders with WooCommerce REST API.
My code:
`$curl = curl_init();

		curl_setopt_array($curl, array(
			CURLOPT_URL => "localhost/wordpress/wp-json/wc/v2/orders/13",
			CURLOPT_RETURNTRANSFER => True,
			CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
			CURLOPT_CUSTOMREQUEST => "GET",
			CURLOPT_POSTFIELDS => json_encode($woocommerce),
			CURLOPT_HTTPHEADER => array("content-type: application/json",),
		));

		$response = curl_exec($curl);
		$err = curl_error($curl);
		curl_close($curl);

		print_r($response);
		print_r($err);`(url)
`
After this operation I got a error. Rest API keys are working, I tested it.
Where is problem?

**Comment by mikejolley** [comment]
What about Auth? I'd expect this is a problem with the code you're using to call the API. There is a PHP library you can use (it's in the rest api docs) if that makes it easier.

I'd suggest testing the API works as expected first by following this guide: https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API Once you have that running you can be sure it's not a problem with your store :)

Thanks
