### ISSUE TITLE
hide read more loop effect add to cart

### ISSUE THREAD

**Issue by semsembanhawy** [woocommerce/woocommerce#20532]
`/**
 * Hide loop read more buttons for out of stock items 
 */
if (!function_exists('woocommerce_template_loop_add_to_cart')) {
	function woocommerce_template_loop_add_to_cart() {
		global $product;
		if ( ! $product->is_in_stock() || ! $product->is_purchasable() ) return;
		wc_get_template('loop/add-to-cart.php');
	}
}`

**Comment by mikejolley** [comment]
Is this is a snippet you're sharing? Not sure this is the correct place for that :)

Thanks!
