### ISSUE TITLE
wc_get_order()

### ISSUE THREAD

**Issue by EnricoSignori** [woocommerce/woocommerce#20539]
I'm using wc_get_order() in the theme function.php with an existing order id, like so:
$order = wc_get_order( "626" ); // same result with $order = wc_get_order( 626 ); 

But i always get the return "False";

I'm missing something?

**Comment by claudiulodro** [comment]
If you are sure that the order ID exists, most likely you are [calling it too soon, before post types are registered](https://github.com/woocommerce/woocommerce/blob/46df086e58a0a152988c85da20a348251fd8a7e7/includes/wc-order-functions.php#L80).

Closing this issue as it's not really a bug report. Thanks.
