### ISSUE TITLE
External/Affiliate links NO LONGER WORK

### ISSUE THREAD

**Issue by WesKel** [woocommerce/woocommerce#20535]
****Describe the bug****
Look at this website of ours for example: https://www.prepaidsimkaarten.nl

In specific this page: https://www.prepaidsimkaarten.nl/product/data-simkaart-europa

This is an affiliate product but the Button is not working anymore after the update.
I tested a couple of downgrades on another website and I can conclude that version 3.3.4 is working correctly. Version 3.4.2 is not working on different websites with different themes.

So we can say something is broken in the Woocommerce code.

I also see that when clicking on the button Woocommerce is adding a "?" Questionmark in the end of the URL. When not editing this, the button WILL WORK I guesss...

This had cost us a lot of money so I hope you can fixt this a.s.a.p. Please keep us updated!

Note: This is one of our websites but we have the same error in 3 websites. One website not because this one was not updated...using the same theme...

****To Reproduce****
1. Go to ''https://www.prepaidsimkaarten.nl/product/data-simkaart-europa'
2. Click on 'BESTELLEN'
3. See error

**Expected behavior**
Through the plugin redirection visitors go to this URL: https://www.prepaidsimkaarten.nl/bestellen/data-simkaart
Where they will be redirected to the real URL.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

Home URL: https://www.prepaidsimkaarten.nl
Site URL: https://www.prepaidsimkaarten.nl
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: ❌ 7.0.30 - We raden je aan om PHP-versie 7.2 of hoger te gebruiken voor betere prestaties en beveiliging. Hoe je PHP-versie bijwerken
PHP Post Max Size: 32 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.5 - Wij adviseren een minimum MySQL-versie 5.6. Bekijk: WordPress vereisten
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: 4a5d_
MaxMind GeoIP Database: ✔
Totale databasegrootte: 49.20MB
Database datagrootte: 40.97MB
Database index grootte: 8.23MB
4a5d_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
4a5d_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
4a5d_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
4a5d_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
4a5d_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB
4a5d_woocommerce_order_itemmeta: Data: 0.04MB + Index: 0.04MB
4a5d_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
4a5d_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
4a5d_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
4a5d_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
4a5d_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
4a5d_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
4a5d_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
4a5d_woocommerce_log: Data: 0.02MB + Index: 0.02MB
4a5d_aiowps_events: Data: 0.02MB + Index: 0.00MB
4a5d_aiowps_failed_logins: Data: 0.16MB + Index: 0.00MB
4a5d_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB
4a5d_aiowps_login_activity: Data: 0.05MB + Index: 0.00MB
4a5d_aiowps_login_lockdown: Data: 0.05MB + Index: 0.00MB
4a5d_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB
4a5d_ak_twitter: Data: 0.00MB + Index: 0.00MB
4a5d_commentmeta: Data: 0.01MB + Index: 0.01MB
4a5d_comments: Data: 0.04MB + Index: 0.02MB
4a5d_FollowMe_Links: Data: 0.00MB + Index: 0.00MB
4a5d_links: Data: 0.00MB + Index: 0.00MB
4a5d_options: Data: 0.89MB + Index: 0.08MB
4a5d_postmeta: Data: 0.56MB + Index: 0.25MB
4a5d_posts: Data: 6.53MB + Index: 0.17MB
4a5d_redirection_404: Data: 8.84MB + Index: 4.91MB
4a5d_redirection_groups: Data: 0.00MB + Index: 0.00MB
4a5d_redirection_items: Data: 0.01MB + Index: 0.01MB
4a5d_redirection_logs: Data: 0.07MB + Index: 0.03MB
4a5d_richreviews: Data: 0.02MB + Index: 0.00MB
4a5d_seo_title_tag_category: Data: 0.00MB + Index: 0.00MB
4a5d_seo_title_tag_tag: Data: 0.00MB + Index: 0.00MB
4a5d_seo_title_tag_url: Data: 0.00MB + Index: 0.00MB
4a5d_slim_events: Data: 1.52MB + Index: 0.55MB
4a5d_slim_events_archive: Data: 0.02MB + Index: 0.02MB
4a5d_slim_stats: Data: 21.55MB + Index: 1.52MB
4a5d_slim_stats_archive: Data: 0.02MB + Index: 0.02MB
4a5d_termmeta: Data: 0.02MB + Index: 0.03MB
4a5d_terms: Data: 0.01MB + Index: 0.02MB
4a5d_term_relationships: Data: 0.01MB + Index: 0.02MB
4a5d_term_taxonomy: Data: 0.01MB + Index: 0.01MB
4a5d_tf_polls: Data: 0.02MB + Index: 0.02MB
4a5d_tf_polls_answers: Data: 0.02MB + Index: 0.02MB
4a5d_tf_polls_responseoptions: Data: 0.02MB + Index: 0.00MB
4a5d_tf_polls_responses: Data: 0.02MB + Index: 0.00MB
4a5d_usermeta: Data: 0.03MB + Index: 0.02MB
4a5d_users: Data: 0.00MB + Index: 0.01MB
4a5d_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
4a5d_wc_download_log: Data: 0.02MB + Index: 0.03MB
4a5d_wc_webhooks: Data: 0.02MB + Index: 0.02MB
4a5d_wpsc_also_bought: Data: 0.00MB + Index: 0.00MB
4a5d_wpsc_cart_contents: Data: 0.00MB + Index: 0.00MB
4a5d_wpsc_checkout_forms: Data: 0.00MB + Index: 0.00MB
4a5d_wpsc_claimed_stock: Data: 0.00MB + Index: 0.00MB
4a5d_wpsc_coupon_codes: Data: 0.00MB + Index: 0.00MB
4a5d_wpsc_currency_list: Data: 0.02MB + Index: 0.01MB
4a5d_wpsc_download_status: Data: 0.00MB + Index: 0.00MB
4a5d_wpsc_meta: Data: 0.00MB + Index: 0.01MB
4a5d_wpsc_product_rating: Data: 0.00MB + Index: 0.00MB
4a5d_wpsc_purchase_logs: Data: 0.00MB + Index: 0.00MB
4a5d_wpsc_region_tax: Data: 0.00MB + Index: 0.00MB
4a5d_wpsc_submited_form_data: Data: 0.00MB + Index: 0.00MB
4a5d_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
4a5d_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 102
customize_changeset: 1
easy-pricing-table: 2
nav_menu_item: 20
page: 46
post: 144
product: 10
revision: 1804
shop_coupon: 1
shop_order: 51
tablepress_table: 43
wpcf7_contact_form: 1
wpsc-product: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Admin Menu Editor: door Janis Elsts – 1.8.3
Akismet Anti-Spam: door Automattic – 4.0.3
All In One Schema Rich Snippets: door Brainstorm Force – 1.5.2
All In One WP Security: door Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.3.1

Yoast Breadcrumbs: door Joost de Valk – 0.8.5
Comment Email Reply: door Jan Eichhorn – 1.0.4
Contact Form 7: door Takayuki Miyoshi – 5.0.2
Cookie Notice: door dFactory – 1.2.43
Easy Pricing Tables by Fatcat Apps: door Fatcat Apps – 2.3.10
Facebook Social Stats: door ninanet site solutions – 1.1
Feedburner Email Widget: door WyriHaximus – 1.2.1
GZip Ninja Speed Compression: door CustomWPNinjas – 1.2.3
kk Star Ratings: door Kamal Khan – 2.6.1
Redirection: door John Godley – 3.2
SI Captcha Anti-Spam: door fastsecure – 3.0.3 – Niet getest met de actieve versie van WooCommerce
WooCommerce Sisow Betaal Opties: door Sisow – 5.0.3 – Niet getest met de actieve versie van WooCommerce
TablePress Extension: Responsive Tables: door Tobias Bäthge – 1.2
TablePress: door Tobias Bäthge – 1.9
W3 Total Cache: door Frederick Townes – 0.9.7
Woocommerce Order address Print: door Bhavik Patel – 3.2 – Niet getest met de actieve versie van WooCommerce
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 2.1.9
WooCommerce: door Automattic – 3.4.0 – 3.4.2 is beschikbaar
Yoast SEO: door Team Yoast – 7.5.1
WP-Piwik: door André Bräkling – 1.0.19
Slimstat Analytics: door Jason Crouse – 4.7.8.1
YITH Purchased Column for WooCommerce: door YITHEMES – 1.1.2 – Niet getest met de actieve versie van WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #2523 - /winkel
Winkelmand: #2524 - /winkelmand
Afrekenen: #2525 - /afrekenen
Mijn account: #2526 - /mijn-account
Algemene voorwaarden: #2527 - /algemene-voorwaarden

### Theme ###

Name: Remould
Version: 5.3
Author URL: http://www.thememount.com/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: prepaid-simkaarten/woocommerce/archive-product.php versie 2.0.0 is verouderd. De hoofdversie is 3.4.0
prepaid-simkaarten/woocommerce/content-product.php versie 2.6.1 is verouderd. De hoofdversie is 3.4.0
prepaid-simkaarten/woocommerce/content-product_cat.php
prepaid-simkaarten/woocommerce/global/quantity-input.php versie 2.5.0 is verouderd. De hoofdversie is 3.4.0
prepaid-simkaarten/woocommerce/global/wrapper-end.php versie 1.6.4 is verouderd. De hoofdversie is 3.3.0
prepaid-simkaarten/woocommerce/global/wrapper-start.php versie 1.6.4 is verouderd. De hoofdversie is 3.3.0
prepaid-simkaarten/woocommerce/loop/loop-end.php
prepaid-simkaarten/woocommerce/loop/loop-start.php versie 2.0.0 is verouderd. De hoofdversie is 3.3.0
prepaid-simkaarten/woocommerce/single-product.php

Outdated Templates: ❌

**Comment by mikejolley** [comment]
This used to be a link, but is now a form.

You should review the settings in your redirection plugin. It doesn't appear to be handling the form and is redirecting back.

Since this is a form now, with GET method, it will append `?` to the URL and add any query params. In this case there are none.

You have 3 options:

1. Append `?` to the 'source' in redirection plugin settings.
2. Use regex in redirection plugin so anything after your string is ignored https://redirection.me/support/redirect-regular-expressions/
3. Don't use redirection. Make the external product button link to `https://keepgo.eu/ex/buy/prepaidsimkaartennl/step1` or whatever link it needs to go to. The user won't see where the form is posting to because it's a form, not a link, so redirection isn't really needed here.

Hope that helps.

By the way, this was changed here https://github.com/woocommerce/woocommerce/pull/19666 for this issue https://github.com/woocommerce/woocommerce/issues/19654

cc @claudiulodro

**Comment by WesKel** [comment]
Hi There,

Thanks for your reply but the issue is not solved yet... :-(

Option 1: is ONLY working in Google Chrome and Safari. Not in MS Edge & Firefox. So we don't have anything with this option.

Option 2: I don't understand this.

Option 3: It's not an option due to SEO perspectives.

QUESTION 1: Could you guys from woocommerce make option 1 compatible with ALL BROWSERS? 
QUESTION 2: I'm not a programmer. Could you explain option 2?

**Comment by mikejolley** [comment]
1 you can just add both sources in the redirection plugin (with and without ?)

Not sure why you believe this will affect SEO. It's a form?

**Comment by WesKel** [comment]
When we use option three Google will follow the link and give value to our partner. If our partner is outranking us, we don't have any income. Thats why option 3 is not an option :-)

Also I've added both sources in the redirection plugin, with and without ?.... one of the plugins is not understanding this and is redirecting to the main cat page. So I've made a different URL with an ? and replaced the selected pages. In Chrome it's working perfect! But Microsoft Edge and Firefox don't understand this....

Still I don't understand option 2... could you please explain this? Thanks in advanced.

**Comment by mikejolley** [comment]
> When we use option three Google will follow the link and give value to our partner.

I've already said, it's not a link. **It's a form.**

The 2nd option is just something you can do with the redirection plugin. See their docs.

**Comment by WesKel** [comment]
What do you mean with "form". I don't know what that is...
But if something is clickable, Google in particular... can and will follow the outcome of the click ... Google is very good in this the past years. Even JS and even cloaked links...

So stilll that option is not an option...right now we downgraded WC but thats not good... I still hope for a good fix from the WC team... Hope you can help us further with other solutions...
