### ISSUE TITLE
Error in WC > reports > clients.

### ISSUE THREAD

**Issue by Mitch13260** [woocommerce/woocommerce#20538]
Hello, I think there is a bug in : WC > reports > clients.
Searching for a customer by name or email does not work.
Also, in the column "last order", it is not up to date, even by doing a refresh.
Anyone encounter this error ?
Thank you in advance

**Comment by claudiulodro** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried searching for customers in the customer report and making sure the "last order" updated to the correct last order after an order and everything appeared to work correctly.

It could be a plugin conflict. You could try the [troubleshooting guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) and that should help you pinpoint the issue and determine whether it is a plugin conflict.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks

**Comment by Mitch13260** [comment]
Hi,
On a copy of my site, I disabled all plugins but it does not change anything.
Another thing, some customers do not have a name, first name in their profile WP. Yet, they are real customers who bought and created an account ... very strange !
