### ISSUE TITLE
show product meta in order items table in Order Details

### ISSUE THREAD

**Issue by setras21** [woocommerce/woocommerce#20542]
When i try to add new order from admin order panel i chose product but i cant can chose attributes of product that i add like Size for clothes Number for shoes .
How can i be able to add here a button or meta to chose Attributes for product that i chose it ?! 
![capture](https://user-images.githubusercontent.com/40282179/41445380-67ff2f20-7049-11e8-880e-23e6e8641ee0.PNG)

**Comment by mikejolley** [comment]
Hover the row.
Click edit item on the far right.
Add meta data there.

This is hardcoded meta and won't affect price etc since you're adding details manually.

Thanks

**Comment by setras21** [comment]
Yes i know meta but i want smthg to lose to much time smthg that can select direct the size of product that i add the attributes for that product

**Comment by mikejolley** [comment]
@setras21 This is not supported. That functionality does not exist. 

Meta data does nothing, it just displays for the user. As long as the correct variation is chosen, this is only there for your reference.

**Comment by setras21** [comment]
yes, but u didn't get me well dear when someone order via facebook I need to put him on the website at Orders page.
When I create new order leets take example t-shirt. Someone order in facebook t-shirt size M and when I try to add new order in the website with the t-shirt that he orders I cant choose the size it's nowhere the size. how can I be able to choose a size to make any button or an example of how to do it?

**Comment by mikejolley** [comment]
If you have variations for s, m, l etc, you choose it. No need for meta as the "M" would be part of the product title.
