### ISSUE TITLE
Instanced shipping methods initializing a lot?

### ISSUE THREAD

**Issue by ktmn** [woocommerce/woocommerce#20548]
Hello,

let's say I add this line `var_dump('init ' . $this->instance_id);` somewhere in here:

https://github.com/woocommerce/woocommerce/blob/b1d8add833f4f9894033b06bbe36da753704312d/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php#L46-L52

How come on the checkout page I get:

```
string(6) "init 0" 
string(6) "init 1" 
string(6) "init 1" 
string(6) "init 1"
```

even though there is only 1 flat rate option?

The problem I have is if I want to render something from the Shipping Method to the front end by adding this to the `init()`

`add_action('woocommerce_checkout_after_customer_details', [$this, 'show_something']);`

then the action will get added 4 times.

How do I do something once per instance, given that the instance with the same ID seems to get initialized multiple times?

If the shipping method takes input from the user on the front end, then how can I render it? Only examples of the instanced shipping methods that I can find are the 3 default ones from WC and they don't really do anything fancy.

**Comment by mikejolley** [comment]
Shipping methods/instances are not singletons and can be init/loaded/constructed multiple times depending on whats going on. 

How I'd tackle this is add the code:

```
add_action('woocommerce_checkout_after_customer_details', [$this, 'show_something']);
```

Outside of your shipping method instance e.g. in the plugin file itself. Then you can render once, and if it's conditional you can just check what shipping method is currently in use.

Hope that helps.
