### ISSUE TITLE
Emogrification fails with @keyframes in style block

### ISSUE THREAD

**Issue by chris-brighton** [woocommerce/woocommerce#20545]
**Describe the bug**
When Woocommerce sends out notification emails, it calls Emogrifier to convert existing style blocks into inline styles. When "@keyframes" is found in any style block, emogrification fails silently and many inline styles are left unwritten, but style blocks are still omitted. The result is broken css rendering.

**To Reproduce**
1. add this to functions.php
```
add_action('woocommerce_email_header', function() { echo(
"<style>
    @keyframes fadeIn
    {
        0% {
            opacity: 0;
            top: -20px;
        }

        100% {
            opacity: 1;
            top: 0px;
        }
    }
.any_class {
   animation: fadeIn 1s ease-in;
}
</style>");
```
2. Go to Woocommerce > Order and Edit an order
3. On the right, under "Order Actions", choose any relevant email action (where you can receive the email either as admin or customer) and send.

**What happens**
The email arrives with css styles all messed up.

**Expected behavior**
The email should render with the same css as before, and animation should be seen in supported email apps like MacOS or iOS Mail.

**Workaround**
Only add the style *after* emogrification, using the hook ''woocommerce_mail_content" with a high priority.

**Comment by mikejolley** [comment]
Fixing this on the Woo side is not an option - this is a 3rd party library. 

https://github.com/MyIntervals/emogrifier/pull/392

We could try Emogrifier 2.0 but it drops support for PHP 5.4 so it would need to be conditionally loaded and wouldn't kick in on older PHP installs. Thats the trade off.

**Comment by mikejolley** [comment]
@claudiosanches @claudiulodro Thoughts? It requires PHP 5.5+

**Comment by mikejolley** [comment]
Confirmed it keeps inline styling, but emogrifier does not support keyframes so your workaround is needed regardless :) 

Will still look into the upgrade of emogrifier.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20547

**Comment by chris-brighton** [comment]
@mikejolley Thanks for the quick response. 

I'm assuming emogrifier 2.0 can't leave 'non-node selectors' like @keyframes fragments intact within style blocks like it does @media? That's a pity :(

**Comment by mikejolley** [comment]
@chris-brighton Doesn't appear to. You could go log this on their issue tracker?
