### ISSUE TITLE
Change in instance_id location for shipping methods 

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#20555]
This is coming from this forum thread:
https://wordpress.org/support/topic/shipping-method-and-id-changes-or-bug/

It appears that how the `instance_id` for shipping methods in  is being stored has changed, which results in different results from the API. I didn't see mention of this in the changelog, was this intentional?

Order in 3.4.2:
![](http://cld.wthms.co/QD2Vau+)
Image Link: http://cld.wthms.co/QD2Vau

Order in 3.4.1:
![](http://cld.wthms.co/CVvqpV+)
Image Link: http://cld.wthms.co/CVvqpV

Results from API call in 3.4.2:
```
    "shipping_lines": [
        {
            "id": 2027,
            "method_title": "Flat rate",
            "method_id": "flat_rate",
            "total": "12.00",
            "total_tax": "2.52",
            "taxes": [
                {
                    "id": 23,
                    "total": "2.52",
                    "subtotal": ""
                }
            ],
            "meta_data": [
                {
                    "id": 14775,
                    "key": "instance_id",
                    "value": "23"
                },
                {
                    "id": 14779,
                    "key": "Items",
                    "value": "rounding prod 1 &times; 1"
                }
            ]
        }
    ],
```

Results from API call in 3.4.1:
```
    "shipping_lines": [
        {
            "id": 2033,
            "method_title": "Flat rate",
            "method_id": "flat_rate",
            "instance_id": "4",
            "total": "4.96",
            "total_tax": "1.04",
            "taxes": [
                {
                    "id": 23,
                    "total": "1.0416",
                    "subtotal": ""
                }
            ],
            "meta_data": [
                {
                    "id": 14819,
                    "key": "Items",
                    "value": "rounding prod 1 &times; 1"
                }
            ]
        }
    ],
```

**Comment by mikejolley** [comment]
This was a side effect of splitting instance ID into it's own field (rather than allowing shipping methods to control the method id, in which instance ID was optional).

This has been logged for inclusion in the API here https://github.com/woocommerce/wc-api-dev/issues/113

Cheers
