### ISSUE TITLE
The new version not sum

### ISSUE THREAD

**Issue by pawel06281990** [woocommerce/woocommerce#20558]
**Is your feature request related to a problem? Please describe.**
The new version of the plugin does not sum up from variants

**Comment by peterfabian** [comment]
Hi, 

can you please be more specific? Where exactly it does not sum up? 
Have you tried to go through the [self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to check if the potential conflicts can be ruled out?

Also, it would be useful to post your [status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) here.

Thanks.
