### ISSUE TITLE
add_to_cart (or get_html_price?) shorcode should apply raw_woocommerce_price.

### ISSUE THREAD

**Issue by marmolak** [woocommerce/woocommerce#20557]
**Describe the bug**
We use storefront-hero on our website. We use some price filter for adjusting price for some customers (sale system).
However we are not able to apply sales when storefront-hero is used:

storefront-product-hero.php:
echo do_shortcode( '[add_to_cart id="' . $product_id . '"]' );

Which leads us into woocommerce code:
includes/class-wc-shortcodes.php:
public static function product_add_to_cart( $atts ) {
...
                if ( wc_string_to_bool( $atts['show_price'] ) ) {
                        // @codingStandardsIgnoreStart
                        echo $product->get_price_html();
                        // @codingStandardsIgnoreEnd
                }
...

includes/class-wc-product-grouped.php:
public function get_price_html( $price = '' ) {
...
no traces of raw_woocommerce_filter used
...

includes/class-wc-product-variable.php:
public function get_price_html( $price = '' ) {
...
no traces of raw_woocommerce_filter used
...
etc...

I believe that by using raw_woocomerce_price filter by default, it will be much easier to code sale system for customers. Now I'm forced to search html code for price and then alter price of product on-the-fly.  

**To Reproduce**
1. Use storefront-hero
2. Use raw_woocommerce_price filter
3. return different price in filter
4. no change in storefront-hero banner

**Expected behavior**
Should apply raw_woocommerce_price filter before raw_woocomm get_price_html filter.
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
Woocommerce version: 3.4.2
Wordpress version: 4.9.6
</details>

**Comment by peterfabian** [comment]
Hi, 

As far as I can see in`get_price_html` function:
- for products *not* on sale, it calls `wc_price` which applies the `raw_woocommerce_filter` 
- for products on sale, filter `raw_woocommerce_filter` gets applied when `wc_format_sale_price` is called
- for variable products with price range, filter `raw_woocommerce_filter` should be called via function `wc_format_price_range` if `$min_price` and `$max_price` are numeric values

I installed the `Storefront Product Hero`, added filter for `raw_woocommerce_filter` that returns 90% of original price and it seems to work fine. Both on the 'hero' display and on the product page.

Maybe you can elaborate on what kind of product you're having problems with (simple, variable, grouped, etc). Is the product on sale? In case it's a variable product, do the variations have the same prices?

**Comment by mikejolley** [comment]
Agree on @peterfabian's findings.

> I believe that by using raw_woocomerce_price filter by default, it will be much easier to code sale system for customers. 

I think this is very wrong. `raw_woocommerce_price` applies to the display of all prices. `raw_woocommerce_price` provides no context i.e. which product is being shown, which makes it unsuitable for this.

Changing this at the product or cart level would be better than changing the price display functions. Otherwise things such as the cart will never see your changes.

Thanks

**Comment by marmolak** [comment]
Hi Mike and Peter.

Thank you for yor answers and time.
What we really need is is sales per customer. So different customers are different prices on different products so we are not able to save them in database. Or do you mean another hook which I missed? :)

You are right.  raw_woocommerce_price doesn't provide much context which is main issue of my code :).
I used very ugly "workaround" with global $post variable, which "works" for me for most of products but not for sale hero which doesn't use global $post.

Another question is: should raw_woocommerce_price support some context?

PS: not bug at all. Only my misunderstanding.
Thank you again for your patience and time.

**Comment by mikejolley** [comment]
Products themselves have filters when get_price() is called - those could work.

Or you could discount items in the cart/apply custom discounts there. There are many ways :)
