### ISSUE TITLE
show product meta in order items table in Order Details (same ticket)

### ISSUE THREAD

**Issue by setras21** [woocommerce/woocommerce#20553]
Hello
Again I'm posting this issue
When I try to add new order from admin order panel I chose product but I cant can choose attributes of a product like add Size for clothes Number for shoes.
How can I be able to add here a button or meta to chose Attributes for a product that I chose it ?!
I don't want to use Add meta button cuz it takes time I want smthg fast like to show the attributes for that product.
![capture](https://user-images.githubusercontent.com/40282179/41498489-99a86f1a-716f-11e8-9f93-afae3a6e2595.PNG)

Thank you again.

**Comment by mikejolley** [comment]
Do not post duplicates. Ill reply to your other.
