### ISSUE TITLE
Woo API not returning JSON data in response

### ISSUE THREAD

**Issue by 4word** [woocommerce/woocommerce#20565]
When making a PUT request to update a variant, occasionally HTML gets returned instead of JSON. The response status is still 200, and for 99% of our PUT requests that return 200 the response data contains the JSON representation of the variant, but occasionally get get something like this (partial response text, we don't keep the entire response for very long in our logs but this is the first part of it):

```
<br />
<b>Warning</b>:  Declaration of statisticsSln::getTypeId($code) should be compatible with moduleSln::getTypeID() in <b>/home1/ziazensa/public_html/wp-content/plugins/secure-login-by-supsystic/modules/statistics/mod.php</b> on line <b>110</b><br />
<br />
<b>Warning</b>:  Declaration of optionsModelSln::get($optKey) should be compatible with modelSln::get($d = Array) in <b>/home1/ziazensa/pu
```

Another example response (this one for a POST):
```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function get_attributes() on boolean in /home1/ziazensa/public_html/wp-content/plugins/woocommerce/includes/api/class-wc-rest-product-variations-controller.php:374
Stack trace:
#0 /home1/ziazensa/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-crud-controller.php(161): WC_REST_Product_Variations_Controller-
```

Total users affected appears to be pretty low across the WooCommerce users in our app, but for the users that get this error, we see this for many of the PUT requests we make against their variants. All requests are made with a content type set to application/json.

<br />
The expected behavior is for the response to be in the format the API docs say it will be in:

> The default response format is JSON. Requests with a message-body use plain JSON to set or update resource attributes. Successful requests will return a 200 OK HTTP status.
<br />
Unfortunately, this is not isolated to a single environment. We have dozens of different WooCommerce users across multiple versions.
<br /><br />
The ideal outcome for this issue would be to have a future version that actually always returns JSON for a successful create/update call, but a good compromise would be documentation for how to handle these kinds of responses. Was the update successful (the status code indicates it was, but the response makes it not obvious what happened)? Should we retry these requests? Should we be reaching out to site owners where we see this error happening and ask them to change something?

**Comment by mikejolley** [comment]
@4word Both are caused by issues on the user's site and their config.

We can protect against the fatal error (looks to be due to an invalid variation without a parent), but the other one is not coming from WooCommerce code it's coming from a plugin called `secure-login-by-supsystic`. If this site is in production they shouldn't have error_reporting on so those warnings should be suppressed.  Any output like this will invalidate the JSON being returned.

I'll put in a PR to protect against the fatal.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20572
