### ISSUE TITLE
Free Shipping minimum with Coupons

### ISSUE THREAD

**Issue by imbeingfollowed** [woocommerce/woocommerce#20564]
Not sure if this is a bug/misconfiguration on our part/intended behaviour but this seems a bit counter intuitive. Customers have been complaining to one of our clients and I've used a fresh install to double check. I can provide logins to this test area & screenshots below.

1. Shop has £20 minimum order requirement to qualify for free shipping 
2. £30 product added to basket - free shipping shows up
3. Apply £15 off coupon - free shipping is taken away (!)

Most of our clients offer vouchers as a monetary equivalent so there is no reason that the customer should pay more for the privilege of using a coupon. The 'Allow free shipping' coupon checkbox is not a viable solution as they also give out smaller coupons and you could get orders with free shipping well under £20.

![sb](https://user-images.githubusercontent.com/25791027/41545873-10b46988-7314-11e8-8ec2-e1fbadb946ff.png)

**Comment by mikejolley** [comment]
You could argue both ways; if you have a discount, you're not spending £30 in your case above, you're spending £15.

This has been argued both ways before (see https://github.com/woocommerce/woocommerce/issues/17462) so changing this is not an option I'm afraid. 

You could set up this rule with custom logic - there is a filter `woocommerce_shipping_free_shipping_is_available` which could be used. 

Current logic is here which you could base the new logic on https://github.com/woocommerce/woocommerce/blob/a7c745a5200599724c6e3d5f6c90291e729cd330/includes/shipping/free-shipping/class-wc-shipping-free-shipping.php#L169-L182

Example here for a different use case https://mikejolley.com/2016/05/24/woocommerce-enable-free-shipping-only-if-product-class-is-found-in-cart/ You may need to get a dev to write a snippet for you if you have no-one in house.

Thanks

**Comment by imbeingfollowed** [comment]
Thanks for taking your time to look at this as always, Mike - much appreciated.

I will put a fix in for now but maybe for a potential new feature there could be an additional Free Shipping option checkbox to tell it to use the pre-coupon applied price? This would satisfy both cases, as I think most customers would expect a '£15 off your order' coupon to be exactly that without complications.

Cheers,

James

**Comment by mikejolley** [comment]
Let's convert this to a feature request to judge demand.
