### ISSUE TITLE
Shortcode: should `[woocommerce_order_tracking]` be included in `is_account_page`?

### ISSUE THREAD

**Issue by mikeyarce** [woocommerce/woocommerce#20578]
Ran into an issue today where some scripts were supposed to load on `is_account_page` but were not loading because it was a page using the `woocommerce_order_tracking` shortcode.

Maybe we should include that shortcode in the `is_account_page` conditional?

**Comment by kloon** [comment]
@mikeyarce order tracking is part of the order templates. What scripts were supposed to load? As far as I can tell order tracking is not reliant on any scripts.

**Comment by mikeyarce** [comment]
@kloon Say, for example, that an extension wants to load things into the "Order" screen.  It might use `is_account_page` to make sure scripts load there, right?   However, if the content is showing up in the `woocommerce_order_tracking` shortcode, those scripts would not load.   One extension that does this is our Help Scout extension. I'm guessing that other extensions might do this too.

**Comment by claudiulodro** [comment]
It's not really an account page, though:
- It's not used by logged-in users or tied to a user account.
- It's not one of the pages listed in the My Account section:
<img width="684" alt="screen shot 2018-06-21 at 10 15 30 am" src="https://user-images.githubusercontent.com/7317227/41734550-2a364992-753c-11e8-8c8b-bd7b15050b7d.png">

I think counting it as an account page would cause more confusion than it would help. It would also likely cause issues for extensions that currently e.g. assume there is a logged-in user when `is_account_page` is true.

If an extension needs to do something on account pages and the order tracking page my recommendation is to do: `is_account_page() || has_shortcode( get_the_content(), 'woocommerce_order_tracking' )`.

Closing this issue for the reasons I just outlined. Good question. Thanks. :)

**Comment by mikeyarce** [comment]
@claudiulodro so while the `woocommerce_order_tracking` page is not an account page, the page that it renders when it does the search is an account page.      It basically renders an Order - which I think would count as an account page?  Or maybe not?

**Comment by claudiulodro** [comment]
The Order Details template is used in a few places: in My Account, in the Order tracking, in the overview screen right after you place an order, etc. Even if we count `woocommerce_order_tracking`-pages as account pages, there will still be a bunch of screens that render orders and aren't account pages.

**Comment by mikejolley** [comment]
Account pages are also for registered accounts. This short code is available for guests.

**Comment by mikeyarce** [comment]
@mikejolley good point.  We'll just have to make sure extensions account for this displaying of Orders.
