### ISSUE TITLE
State dropdown not showing exact match. WA = Delaware instead of Washington

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce#20575]
**Describe the bug**
If you head to checkout and start typing in a state like Washington, or use the abbreviation WA, you won't get Washington first. The same for other states I quickly tested, IN or MA won't show the exact matches first either.

**To Reproduce**
1. Go to checkout
2. Open the state field.
3. Type in something like WA, which you would think would show Washington first
4. See error as Delaware comes up first, among others before Washington shows up.

**Screenshots**
![https://cld.wthms.co/ztfz83](https://cld.wthms.co/ztfz83+)

**Expected behavior**
If you typed in WA you'd figure the state that exactly matches the first two letters would show up. The same happens for others like IN or MA.

**Comment by nishitlangaliya** [comment]
PR done https://github.com/woocommerce/woocommerce/pull/20605

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/selectWoo/pull/20 cc @claudiulodro Maybe we can get that update into 3.5?

**Comment by claudiulodro** [comment]
See my comment on https://github.com/woocommerce/selectWoo/pull/20. We are going to need to make some sort of prioritization algorithm for the dropdown where things that start with the search phrase are higher up in the list than things that contain the search phrase in the middle.

**Comment by nishitlangaliya** [comment]
@claudiulodro ,

Thanks for review my PR and your valuable suggestions. 

Thanks.

**Comment by mikejolley** [comment]
I'm closing this as it's part of the SelectWoo library.

I think there could be an argument for either way. Ranking by the entered text is one way, but alphabetically like now is another. As you enter more text the matched options are reduced anyhow.

When checkout is redesigned I expect we'll phase out select woo entirely but we'll see :) #needsdesign
