### ISSUE TITLE
wc_print_notices() not show messages

### ISSUE THREAD

**Issue by LandiLuca** [woocommerce/woocommerce#20576]
Hi, the problem is about the function wc_print_notices(). After an update of woocommerce/wordpress at the last version, the wc_print_notices doesn't print any messages. We have find it, when PayPal sandbox returns back with error at the cart page. But no errors was displayed. So I've open the wc_print_notices function and I've tryed to comment the wc_clear_notices() at line 140 in the file wc_notice_functions, and the messages are showed on screen. Obviously the messages are not delete, but appended. So I've try to put the wc_clear_notices at the end of the template page: nothing, the message are not showed. So It seems that the wc_clear_notices delete the message before they are showed in output page on front-end!

The system status:

`
### WordPress Environment ###

Home URL: https://www.flyfishinglastminute.com
Site URL: https://www.flyfishinglastminute.com
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 420 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.15-0ubuntu0.16.04.2 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.17-0ubuntu0.16.04.1
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 42.07MB
Database Data Size: 41.00MB
Database Index Size: 1.07MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.04MB + Index: 0.02MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
country: Data: 0.01MB + Index: 0.00MB
cron: Data: 0.05MB + Index: 0.00MB
traccia_gmap: Data: 0.05MB + Index: 0.00MB
vacancy_option_room: Data: 0.05MB + Index: 0.00MB
wp_a3_exclude_email_subject: Data: 0.02MB + Index: 0.00MB
wp_byt_accommodation_bookings: Data: 0.23MB + Index: 0.00MB
wp_byt_accommodation_bookings_days: Data: 0.00MB + Index: 0.00MB
wp_byt_accommodation_vacancies: Data: 0.05MB + Index: 0.00MB
wp_byt_accommodation_vacancies_days: Data: 0.00MB + Index: 0.00MB
wp_byt_car_rental_bookings: Data: 0.00MB + Index: 0.00MB
wp_byt_car_rental_booking_days: Data: 0.00MB + Index: 0.00MB
wp_byt_cruise_booking: Data: 0.00MB + Index: 0.00MB
wp_byt_cruise_schedule: Data: 0.00MB + Index: 0.00MB
wp_byt_cruise_schedule_days: Data: 0.00MB + Index: 0.00MB
wp_byt_tour_booking: Data: 0.00MB + Index: 0.00MB
wp_byt_tour_schedule: Data: 0.00MB + Index: 0.00MB
wp_byt_tour_schedule_days: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_maxbuttonsv3: Data: 0.06MB + Index: 0.00MB
wp_maxbuttons_collections: Data: 0.02MB + Index: 0.00MB
wp_maxbuttons_collections_trans: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 3.78MB + Index: 0.07MB
wp_popover_ip_cache: Data: 0.02MB + Index: 0.02MB
wp_postmeta: Data: 29.25MB + Index: 0.31MB
wp_posts: Data: 6.33MB + Index: 0.17MB
wp_pv_commission: Data: 0.00MB + Index: 0.00MB
wp_revslider_css: Data: 0.09MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.01MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.10MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_spu_hits_logs: Data: 0.50MB + Index: 0.23MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.04MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 0.13MB + Index: 0.05MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wysija_campaign: Data: 0.00MB + Index: 0.00MB
wp_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB
wp_wysija_custom_field: Data: 0.00MB + Index: 0.00MB
wp_wysija_email: Data: 0.03MB + Index: 0.00MB
wp_wysija_email_user_stat: Data: 0.00MB + Index: 0.00MB
wp_wysija_email_user_url: Data: 0.00MB + Index: 0.00MB
wp_wysija_form: Data: 0.00MB + Index: 0.00MB
wp_wysija_list: Data: 0.00MB + Index: 0.00MB
wp_wysija_queue: Data: 0.00MB + Index: 0.00MB
wp_wysija_url: Data: 0.00MB + Index: 0.00MB
wp_wysija_url_mail: Data: 0.00MB + Index: 0.00MB
wp_wysija_user: Data: 0.00MB + Index: 0.01MB
wp_wysija_user_field: Data: 0.00MB + Index: 0.00MB
wp_wysija_user_history: Data: 0.00MB + Index: 0.00MB
wp_wysija_user_list: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

accommodation: 11
attachment: 160
cabin_type: 3
car_rental: 9
cruise: 4
extra_item: 7
fake_vacancy: 436
fishing-packages: 2
fishing_packages: 5
inc_popup: 2
location: 1072
mc4wp-form: 2
nav_menu_item: 19
page: 52
post: 23
product: 134
product_variation: 2
review: 2
revision: 397
room_type: 85
shop_order: 6
sidebar: 2
spucpt: 28
tour: 4
vcv_templates: 18
wc_order_status: 14
wpcf7_contact_form: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

All In One SEO Pack: by Michael Torbert – 2.6.1
Better Search Replace: by Delicious Brains – 1.3.2
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.20
Contact Form 7: by Takayuki Miyoshi – 5.0.2
Cookie Notice: by dFactory – 1.2.44
Duplicate Post: by Enrico Battocchi – 3.2.2
FOL Custom: by Florence Online – 1.0.0
Custom Email notification WooCommerce: by FOL srl – 0.1 – Not tested with the active version of WooCommerce
FOL Login: by Florence Online – 1.0.0
FOL Mailchimp: by Florence Online – 1.0.0
Location Import: by Florence Online – 1.0.0
Custom Login Page Customizer: by Hardeep Asrani – 1.2.1
MailChimp for WordPress: by ibericode – 4.2.3
MaxButtons: by Max Foundry – 7.2
Max Mega Menu: by Tom Hemsley – 2.4.2
Menu Items Visibility Control: by Hassan Derakhshandeh – 0.3.7
Nav Menu Roles: by Kathy Darling – 1.9.2
Popups Premium Plugin: by Damian Logghe – 1.9.1
Popups - WordPress Popup: by timersys – 1.9.3.1
Public Post Preview: by Dominik Schilling – 2.6.0
Responsive Mobile-Friendly Tooltip: by ItayXD – 1.6.6
Slider Revolution: by ThemePunch – 5.2.6
Send From: by Benjamin Buddle – 2.2
Easy Updates Manager: by Easy Updates Manager Team – 7.0.1
Preloader: by Alobaidi – 1.0.9
TinyMCE Advanced: by Andrew Ozz – 4.7.11
Visual Composer Website Builder: by The Visual Composer Team – 2.6.1
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.6
WooCommerce Order Status Manager: by SkyVerge – 1.9.0 – 1.9.2 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.2
WooSidebars: by WooCommerce – 1.4.4
WordPress Importer: by wordpressdotorg – 0.6.4
WP Email Template LITE: by a3rev Software – 2.2.5
WP Super Cache: by Automattic – 1.6.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5959 - /latest-offers/
Cart: #461 - /cart/
Checkout: #462 - /checkout/
My account: #12705 - /personal-area/
Terms and conditions: #11162 - /terms-conditions/

### Theme ###

Name: BookYourTravel Child
Version: 1.0.0
Author URL: http://www.fol.it
Child Theme: ✔
Parent Theme Name: BookYourTravel
Parent Theme Version: 7.16
Parent Theme Author URL: http://themeforest.net/user/themeenergy
WooCommerce Support: ✔

### Templates ###

Overrides: BookYourTravel-child/woocommerce/cart/cart-empty.php
BookYourTravel-child/woocommerce/cart/cart-item-data.php
BookYourTravel-child/woocommerce/cart/cart.php
BookYourTravel-child/woocommerce/cart/proceed-to-checkout-button.php
BookYourTravel-child/woocommerce/checkout/form-billing.php
BookYourTravel-child/woocommerce/checkout/review-order.php
BookYourTravel-child/woocommerce/checkout/thankyou.php
BookYourTravel-child/woocommerce/emails/admin-cancelled-order.php
BookYourTravel-child/woocommerce/emails/admin-new-order.php
BookYourTravel-child/woocommerce/emails/customer-on-hold-order.php
BookYourTravel-child/woocommerce/emails/email-order-details.php
BookYourTravel-child/woocommerce/emails/email-order-items.php
BookYourTravel-child/woocommerce/global/form-login.php
BookYourTravel-child/woocommerce/myaccount/form-edit-address.php
BookYourTravel-child/woocommerce/myaccount/navigation.php
BookYourTravel-child/woocommerce/myaccount/orders.php
BookYourTravel-child/woocommerce/myaccount/view-order.php
BookYourTravel-child/woocommerce/order/order-details-item.php
BookYourTravel-child/woocommerce/order/order-details.php

`

**Comment by mikejolley** [comment]
Notices show once, thats why there is a clear.

Perhaps something is outputting your notices earlier, and failing to output the results?

If a specific core notice is missing, give the details and I'll check it outputs. But removing the clear is not a fix.

**Comment by LandiLuca** [comment]
I've remove the wc_print_notices from cart.php, and put a die inside the wc_clear_notices, to check if somewhere/someone call the functions. But there are no others calling for that function, the cart.php is loaded without any 'die'. If I try to  put some print_r on $all_notices, this is populated in the function, but not in the error.php (notice file). I've also try to remove the wc_clear_notices from wc_print_notices, and put it after calling wc_print_notices in cart, like:

wc_print_notices();
wc_clear_notices();

(I know is not the right way, but I try to find why) but also here the messages are deleted before they output. 

I've also tried to send me an email each time the wc_print_notices is called, updating all 'calling function var' with __FUNCTION__. so into the email I've who call it. And it call alway from cart.php, twice.
it also happens when from PayPal I come back to the cart with a PayPal error. It not showed...

**Comment by LandiLuca** [comment]
I've try on woocommerce 3.3 and it works, but not on 3.4. Same scripts!

**Comment by LandiLuca** [comment]
I've find a conflict with a plugin, for some reason cart.php is called twice with the plugin All In One SEO Pack version 2.6.1

**Comment by kloon** [comment]
Thanks for confirming the culprit plugin, seems like that option auto-generate an excerpt based on what is in the page description. This results in the shortcode being called twice, which after the first call it will clear the notices.

Shortcodes should definitely not be called on excerpts for WooCommerce cart/checkout pages so suggest you turn that off for those pages.
