### ISSUE TITLE
When plugin installed, all pages are showing title as SHOP..

### ISSUE THREAD

**Issue by renjithcbhanu** [woocommerce/woocommerce#20571]
**Describe the bug**
I Installed this plugin and then i choose a page to view it showing title as SHOP...Not only a singe page all other pages showing the same...when i uninstall this plugin pages showing given title..Im using "RED CHILLI" Theme.
**To Reproduce**
1. Go to 'Plugins-Add New-Woocommerce-install'
2. Click on 'any of the Pages'
3. See the title
4. This is the error

**Screenshots**

![image](https://user-images.githubusercontent.com/27951802/41595466-81ad3770-73e4-11e8-98eb-e9511a9e791d.png)

**Expected behavior**
I expected to get the title as i given to that page 
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a RED CHILLI theme active
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
Hi,

You missed these steps:

```
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
```

If it only affects the red chilli theme you need to report this to the theme author, especially if they claim to support WooCommerce.

Feel free to report back once you've done that. Closing as invalid for now.

Thanks

**Comment by mikejolley** [comment]
Could be any number of reasons. Do the above steps please.
