### ISSUE TITLE
I'm using membership functionality in the website and same I want to use in-app but in the document, I couldn't find API about membership.

### ISSUE THREAD

**Issue by guptanitesh40** [woocommerce/woocommerce#20570]
I'm using membership functionality in the website and same I want to use in-app but in the document, I couldn't find API about membership.

I'm looking for membership API if anyone can help me to find that API or any way for this because I have read this document but i haven't find about membership API

**Comment by mikejolley** [comment]
Since membership functionality is not included in core, the core APIs do not include this. You'd need to check with whatever membership plugin you are using (their docs, or their support area) to see if this is something thats supported via an API.

Thanks
