### ISSUE TITLE
Importing Products in CSV File Categories and Images not Uploading 

### ISSUE THREAD

**Issue by christineroesch** [woocommerce/woocommerce#20582]
**Describe the bug**
Hi! I am using the build in Importer in Woo Commerce. Most of the fields are uploading correctly, however the categories and Images are not. I have used the taxonomy > and use of commas , and they are still not uploading 

For the images, I first uploaded all the images to the media and then copy the URL to the excel file. Still the image docent get imported. 

Some of the previous fields were not being imported because of the titles containing "Tildes" like Categorías "í", Do you think that can be causing an issue? 

**To Reproduce**

Go to 'Woocommerce All product'
Click on 'Import Button'
Choose a CSV file to be uploded
Check Update existing products
Click on Continue.

**Screenshots**

**Expected behavior**

I would hope the categories and images get uploaded too. 

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
@christineroesch I tested a sample import with tildes and it worked fine for me. Could you perhaps provide a copy or sample of the file you are trying to import so I can test it? It is possible that there might be an extra comma or missing field somewhere in the file causing the issue.

**Comment by mikejolley** [comment]
Closing due to lack of feedback. We can reopen if more details are provided and it can be replicated.
