### ISSUE TITLE
How can I make sure the payment is marked complete before showing thank you page?

### ISSUE THREAD

**Issue by sgehrman** [woocommerce/woocommerce#20589]
My thank you page is shown before the order is complete only when using PayPal.  IPN works fine, site works fine, it's just not well engineered and I need help getting around this BUG.

Order completion creates license keys that I need to show on my thank you page.

Stop closing my issues.  This is the 4th time I've had to ask this very very simple question.

`
### WordPress Environment ###

Home URL: https://indieappstore.io
Site URL: https://indieappstore.io
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31-4+wpengine10 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 6.09MB
Database Data Size: 2.98MB
Database Index Size: 3.11MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.20MB + Index: 0.23MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.23MB + Index: 0.28MB
wp_free_upgrades: Data: 0.02MB + Index: 0.00MB
wp_json_store: Data: 0.08MB + Index: 0.00MB
wp_lic_key_tbl: Data: 0.06MB + Index: 0.00MB
wp_lic_reg_domain_tbl: Data: 0.05MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.16MB + Index: 0.03MB
wp_postmeta: Data: 1.52MB + Index: 1.89MB
wp_posts: Data: 0.13MB + Index: 0.06MB
wp_release_notes: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_upgraded: Data: 0.02MB + Index: 0.00MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 1
nav_menu_item: 4
page: 15
post: 3
product: 1
shop_order: 348

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

DF Software Store: by Steve Gehrman – v1.1
Indie App Store: by Steve Gehrman – v1.1
SendGrid: by SendGrid – 1.11.8
Software License Manager: by Tips and Tricks HQ – 3.9
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.4.13
WooCommerce: by Automattic – 3.4.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Indie Zero
Version: 1.0
Author URL: https://indieappstore.io
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
> Stop closing my issues. This is the 4th time I've had to ask this very very simple question.

I am typing a response **to your other issue**. If you continue to open duplicates, ignoring our comments, **I will be forced to block your account.**

Thanks
