### ISSUE TITLE
korean-tranlation error ' po.mo' 

### ISSUE THREAD

**Issue by kohyunkjun** [woocommerce/woocommerce#20599]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

I use korean language. I find the translation error; 
"/plugins/woocommerce/includes/admin/class-wc-admin-help.php on line 55"
When I click into woocommerce, I always find " below" on head. 
If you corrected it, I would be happy.

**Comment by claudiulodro** [comment]
Hi there.

We do not handle the translation of WooCommerce into languages (and also don't know Korean). Translations are done by the volunteer community [at translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/ko/default). You should be able to go and fix the translation or get the latest version of the translation file using that link. Thanks.
