### ISSUE TITLE
Products of sub-categories are not displayed

### ISSUE THREAD

**Issue by arlesvino** [woocommerce/woocommerce#20592]
After updating to Woocommerce 3.4.1 we recognized, that the products of subcategories are not displayed on the parent-category-pages. 

**To Reproduce**
1. Go to a parent category page
2. No product is shown because the products of subcategories are not displayed

**Expected behavior**
We recognized this issue immediatly after updating to woo 3.4.1

**Comment by arlesvino** [comment]
Sorry i meant 3.4.2

**Comment by mikejolley** [comment]
Seems to be a duplicate of https://github.com/woocommerce/woocommerce/issues/20554 and was fixed in 3.4.3
