### ISSUE TITLE
Notice thrown in geolocation check 

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#20594]
**Describe the bug**
> [20-Jun-2018 17:24:03 UTC] PHP Notice: Undefined index: country in .../wp-content/plugins/woocommerce/includes/class-wc-geolite-integration.php on line 60

The above notice comes from [this line](https://github.com/woocommerce/woocommerce/blob/3.4.3/includes/class-wc-geolite-integration.php#L60) if the data array returned does not contain the `country` index. 

Anything we can do about this?

From forum thread: 
https://wordpress.org/support/topic/undefined-index-country-in/

**Comment by claudiulodro** [comment]
Currently the code assumes that [if there is an exception thrown the lookup failed and handles that gracefully](https://github.com/woocommerce/woocommerce/blob/3.4.3/includes/class-wc-geolite-integration.php#L63). It is however also [possible for the reader to return `null`](https://github.com/woocommerce/woocommerce/blob/3.4.3/includes/libraries/geolite2/Reader.php#L117) (which would cause that notice) and we should account for that.

**Comment by rodrigoprimo** [comment]
See #20608
