### ISSUE TITLE
Variable Product stock status inconsistent

### ISSUE THREAD

**Issue by Garconis** [woocommerce/woocommerce#20593]
Some of my Variable products are showing as "In Stock" even when the variations have no stock.

You can see the product is being shown as in stock: https://d.pr/free/i/zcaAOD

When I edit the product, you can see that it's set to be a Variable product, and that stock is NOT being managed at the product/parent level: https://d.pr/free/i/yAo5s4

Therefore the In Stock or Out of Stock status should be controlled by the Variation stock quantities... especially since those are set to "Manage stock": https://d.pr/free/i/IxcTcG

You can see that both Variations have "Manage Stock" set, and a stock quantity of 0.

Yet, the Parent is saying it's in stock. Here is a screenshot of some of the product meta fields: https://d.pr/free/i/iawHH8

As you can see, the `_stock_status` is showing as `'instock'`, and `_stock` is showing as `NULL`.

I'm not super familiar with what `_v_stock` and `_v_stock_status` are, but those are set to `'4'` and `'instock'` for some reason. As well as is `_stock_status_tmp` and `_stock_tmp`.

Note that these items are imported via WP All Import, and also then updated by a separate WP All Import setup.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://faddegons.com
Site URL: https://faddegons.com
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.31-4+wpengine10 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 104.07MB
Database Data Size: 72.91MB
Database Index Size: 31.16MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_alm: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_dp_available_categories: Data: 0.17MB + Index: 0.00MB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.22MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.33MB + Index: 0.50MB
wp_gf_entry_notes: Data: 0.11MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.06MB + Index: 0.00MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 3.33MB + Index: 0.08MB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.19MB + Index: 0.00MB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.08MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.25MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.08MB + Index: 0.00MB
wp_postmeta: Data: 47.58MB + Index: 16.94MB
wp_posts: Data: 5.44MB + Index: 1.00MB
wp_redirection_404: Data: 0.27MB + Index: 0.28MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.06MB + Index: 0.08MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.22MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.19MB + Index: 0.34MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.14MB + Index: 0.22MB
wp_rg_lead_notes: Data: 0.11MB + Index: 0.03MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_snippets: Data: 0.08MB + Index: 0.00MB
wp_swp_cf: Data: 0.08MB + Index: 0.11MB
wp_swp_index: Data: 5.52MB + Index: 6.03MB
wp_swp_log: Data: 0.02MB + Index: 0.05MB
wp_swp_tax: Data: 0.02MB + Index: 0.05MB
wp_swp_terms: Data: 1.52MB + Index: 1.20MB
wp_termmeta: Data: 0.17MB + Index: 0.28MB
wp_terms: Data: 0.17MB + Index: 0.17MB
wp_term_relationships: Data: 3.39MB + Index: 2.44MB
wp_term_taxonomy: Data: 0.19MB + Index: 0.23MB
wp_usermeta: Data: 1.48MB + Index: 0.14MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woos_search_trends: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

acf: 1
acf-field: 23
acf-field-group: 4
attachment: 2962
br_labels: 1
custom_css: 2
et_pb_layout: 18
feature: 1
nav_menu_item: 65
our_events: 94
page: 32
plant_advice: 158
popup: 2
popup_theme: 6
post: 169
product: 1849
product_variation: 730
revision: 36
wishlist: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (48) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.6.10
Ajax Load More: Layouts: by Darren Cooney – 1.2.1
Ajax Load More: by Darren Cooney – 3.5.0
All In One SEO Pack: by Michael Torbert – 2.6.1
Better Search Replace: by Delicious Brains – 1.3.2
Bulk Page Creator: by Dagan Lev – 1.1.0
Code Snippets: by Shea Bunge – 2.10.1.1
Custom Post Type UI: by WebDevStudios – 1.5.8
Custom Sidebars: by WPMU DEV – 3.1.6
Disable Comments: by Samir Shah – 1.7.1
Divi Booster: by Dan Mossop – 2.7.2
Divi Icon King: by Alex Brinkman – 1.3.0
CPT Layout Injector: by Sean Barton - Tortoise IT – 4.3
Divi Extended Column Layouts: by Sean Barton - Tortoise IT – 1.9
DIVI ACF Module: by Sean Barton - Tortoise IT – 3.3
Woo Layout Injector: by Sean Barton - Tortoise IT – 4.5 – Not tested with the active version of WooCommerce
DP Portfolio Posts Pro: by DiviPlugins – 3.3.4
Duplicate Post: by Enrico Battocchi – 3.2.2
Envato Market: by Envato – 2.0.0
Favicon by RealFaviconGenerator: by Philippe Bernard – 1.3.11
Google XML Sitemaps: by Arne Brachhold – 4.0.9
Gravity Forms Constant Contact Add-On: by Katz Web Services
Inc. – 3.1

Gravity Forms: Multiple Form Instances: by tyxla – 1.1.1
Gravity Forms: by rocketgenius – 2.3.2
GravityWP - CSS Selector: by GravityWP – 0.2.2
Head, Footer and Post Injections: by Stefano Lissa – 3.1.1
Popup Maker: by WP Popup Maker – 1.7.29
Post Meta Inspector: by Daniel Bachhuber
Automattic – 1.1.1

Post Type Switcher: by John James Jacoby – 3.1.0
WooCommerce Product Filter: by Mihajlovic Nenad – 6.5.8
Redirection: by John Godley – 3.2
Sassy Social Share: by Team Heateor – 3.2.3
Say What?: by Lee Willis – 1.9.1
SEO Optimized Images: by priyanshu.mittal – 1.7.9
Shortcode Cleaner: by Jozoor – 1.1.5
Sticky Menu (or Anything!) on Scroll: by Mark Senff – 2.1.1
Surbma - Divi & Gravity Forms: by Surbma – 1.5.7
Top Bar: by WP Darko – 1.2
WooCommerce: by Automattic – 3.4.2
WordPress Importer: by wordpressdotorg – 0.6.4
WP All Export Pro: by Soflyy – 1.5.3
WP All Import Pro: by Soflyy – 4.5.4
WP Crontrol: by John Blackbourn & contributors – 1.6.2
Smush: by WPMU DEV – 2.7.9.1
WP All Import - ACF Add-On: by Soflyy – 3.1.7
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.4.1
YITH WooCommerce Catalog Mode: by YITHEMES – 1.6.0
YITH WooCommerce Wishlist Premium: by YITHEMES – 2.2.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #280 - /plants/
Cart: ❌ Page visibility should be public
Checkout: ❌ Page visibility should be public
My account: #4794 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi Child
Version: 1.1.1
Author URL: https://freshysites.com/
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.7
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/woocommerce/myaccount/dashboard.php
`
</details>

**Comment by claudiulodro** [comment]
Hi there.

This was likely [fixed in WC 3.4.3](https://github.com/woocommerce/woocommerce/pull/20573) (released earlier today). Updating to the latest version then re-saving the products may solve the issue. 

If it doesn't, it's likely that WP All Import is not properly using the WooCommerce CRUD interfaces for creating/saving product information, so the stock status syncing is getting bypassed. This can happen if the plugin directly updates the meta values, as WooCommerce would have no way of knowing the stock quantity/status had changed.

I'm going to close this issue as we can't support third-party plugins on GitHub. Thanks.
