### ISSUE TITLE
Shipping is "Free" Before shipping is determined.

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#20590]
**Is your feature request related to a problem? Please describe.**

Before shipping is calculated, shipping is shown as "FREE!". This is wrong, shipping isn't 'free' unless it's actually free

**Describe the solution you'd like**
Ideally, we have the ability to determine if there is a shipping method selected. If it's selected but not returning a price, we don't have "FREE", we have something more subtle, either '0' or '--'. or this should be wrapped in a filter to be able to change.

**Describe alternatives you've considered**
Wrapping "FREE!" in a filter to allow changing the word

**Comment by mikejolley** [comment]
@yratof where are you talking about? Shipping is not displayed until shipping methods are returned/output.

**Comment by yratof** [comment]
File & line: `/includes/class-wc-cart.php:1408`

I'm current setup, i'm using Bring Fraktguiden for Woocommerce for the shipping and it needs user input to get the rates from the provider. Before these rates can be fetched, woocommerce shows shipping is "FREE!", then when the value is fetched (after submitted the zip code), "FREE" changes to the correct value

I've suggested a possible tweak to avoid making the "FREE" hard coded: https://github.com/woocommerce/woocommerce/pull/20591

**Comment by kloon** [comment]
#20591 will take care of this by introducing a filter on all shipping cost output.
