### ISSUE TITLE
cannot create resource jwt auth

### ISSUE THREAD

**Issue by samxfido** [woocommerce/woocommerce#20601]
I'm using WordPress JWT auth along wp-rest API and woocommerce. when I try to place an order from subscriber account through API its showing "woocommerce_rest_cannot_create". what is correct procedure to create an order by using woocommerce rest API using JWT auth.

**Comment by claudiulodro** [comment]
Hi there. 

It is unlikely that JWT Auth would work well out-of-the-box with the WooCommerce REST API. You'll likely have to do some work setting things up properly. [There is some discussion and links here that may help you out.](https://github.com/woocommerce/wc-api-python/issues/31)

I'm going to close this issue as we cannot support custom development questions or third-party plugin integrations on GitHub. If you get stuck again I recommend you try [the support forum](https://wordpress.org/support/plugin/woocommerce/) or [the WooCommerce developer community Slack group](https://woocommerce.com/develop-woocommerce/) (signup link at bottom of page).

Thanks.
