### ISSUE TITLE
Shipping tax calculates wrong.

### ISSUE THREAD

**Issue by Sk-Shaikat** [woocommerce/woocommerce#20600]
**Describe the bug**
Shipping tax calculates wrong when adding two product in cart, one with tax status `None` and other with tax status `Shipping only / Taxable`. If shipping calculates per quantity then in this situation cart total calculates tax for `None` taxable product's shipping cost.

**Settings & Product details**
*Settings*
* Shipping -> Shipping methods = `Flat rate`, value = `$10*[qty]`
* Tax value -> `20%`

*Product details*
* Product A -> Price = `$100` with tax status `None`
* Product B -> Price = `$200` with tax status `Shipping only`

**To Reproduce**
1. Add `Product A` and `Product B` to cart
2. Go to cart page

**Screenshots**
[Screenshot](https://imgur.com/a/K3SK7wl)

**Expected behavior**
In this table (in screenshot) scenario 1 and 2 has no problem.
But in scenario 3, Tax should be `$2` for `20%` tax on product B shipping cost. But it calculate `20%` tax for total shipping cost. While Product A tax status is `None`.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WooCommerce version: 3.4.2 ||
WordPress version: 4.9.6 ||
WordPress memory limit: 256 MB ||
Language: en_US
```
</details>

**Comment by mikejolley** [comment]
What you're suggesting is not technically possible. Shipping is for the cart as a whole. In your case, the shipping cost will be calculated for BOTH product A + B, not A then B separately. If a taxable product is in the cart, shipping will be taxed.

Whilst this is not part of core, if you needed this setup for any reason you could split the cart into packages:

https://www.xadapter.com/woocommerce-split-cart-items-order-ship-via-multiple-shipping-methods/
https://woocommerce.com/products/woocommerce-advanced-shipping-packages/

This would show a separate shipping method selection per package, each with it's own cost and taxes.

Hope this helps.

cc @claudiulodro r/e tax question for future ref.

**Comment by sjjhr** [comment]
This is a bigger problem that people realise because WooCommerce/WooSubscriptions are circulating code which by default does something illegal, at least in the UK.

It is no solution to split shipping into two - why would anyone want to pay 2 lots of postage and waste 2 lots of packaging just because Woo are too incompetent to fix this bug?
