### ISSUE TITLE
Required Phone Field Bug

### ISSUE THREAD

**Issue by bondimedical3** [woocommerce/woocommerce#20604]
When you set the Phone field to "required" at the checkout it remains as "optional" - view screenshot

![checkout2](https://user-images.githubusercontent.com/10808588/41758583-f6d8f60c-762c-11e8-97dd-849101f6d705.jpg)

**Comment by mikejolley** [comment]
Publish and view checkout. Preview may not be up to date.

**Comment by bondimedical3** [comment]
I have published and viewed the checkout, it doesn't work. Try it yourself.

**Comment by bondimedical3** [comment]
Hmmm. Thats strange, I have 4 stores and the issue is present on all of them. I have also noticed the Hidden option does work. Here is a system status report.

`
### WordPress Environment ###

Home URL: https://www.guysoutlet.com.au
Site URL: https://www.guysoutlet.com.au
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.6
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wpto_
MaxMind GeoIP Database: ✔
Total Database Size: 3.90MB
Database Data Size: 3.45MB
Database Index Size: 0.45MB
wpto_woocommerce_sessions: Data: 1.97MB + Index: 0.10MB
wpto_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpto_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpto_commentmeta: Data: 0.00MB + Index: 0.01MB
wpto_comments: Data: 0.00MB + Index: 0.01MB
wpto_links: Data: 0.00MB + Index: 0.00MB
wpto_options: Data: 0.75MB + Index: 0.07MB
wpto_postmeta: Data: 0.21MB + Index: 0.11MB
wpto_posts: Data: 0.45MB + Index: 0.05MB
wpto_redirection_404: Data: 0.05MB + Index: 0.03MB
wpto_redirection_groups: Data: 0.00MB + Index: 0.00MB
wpto_redirection_items: Data: 0.00MB + Index: 0.01MB
wpto_redirection_logs: Data: 0.00MB + Index: 0.01MB
wpto_termmeta: Data: 0.00MB + Index: 0.01MB
wpto_terms: Data: 0.00MB + Index: 0.01MB
wpto_term_relationships: Data: 0.00MB + Index: 0.00MB
wpto_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wpto_usermeta: Data: 0.02MB + Index: 0.02MB
wpto_users: Data: 0.00MB + Index: 0.01MB
wpto_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpto_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpto_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wpto_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 39
custom_css: 1
customize_changeset: 31
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 16
page: 18
post: 1
product: 15
revision: 160
shop_coupon: 2
shop_order: 5
wbcr-snippets: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.2

Contact Form 7: by Takayuki Miyoshi – 5.0.2
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.3.6

Insert Headers and Footers: by WPBeginner – 1.4.3
PHP code snippets (Insert PHP): by Will Bontrager Software
LLC 
Webcraftic  – 2.0.4

Invisible reCaptcha: by Mihai Chelaru – 1.2.1
Jetpack by WordPress.com: by Automattic – 6.2.1
Redirection: by John Godley – 3.2
Storefront Footer Text: by Wooassist – 1.0.1
Conditional Display for Mobile by WonderPlugin: by Magic Hills Pty Ltd – 1.0
WooCommerce PayPal Express Checkout Gateway: by WooCommerce – 1.5.6
WooCommerce Stripe Gateway: by WooCommerce – 4.1.7
WooCommerce Price Based on Country (Basic): by Oscar Gare – 1.7.9
WooCommerce: by Automattic – 3.4.3
Yoast SEO: by Team Yoast – 7.6.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /buy-now/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #150 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 2.3.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### PBC Settings ###

Base location: AU:NSW
Price Based On: billing
Shipping: ✔
Test mode: –
Test country: –
Prices entered with tax: –
Calculate tax based on: shipping

### Zone Pricing UK ###

slug: uk
name: UK
countries: GB
currency: GBP
exchange_rate: .55

### Zone Pricing Saudi ###

slug: saudi
name: Saudi
countries: SA
currency: SAR
exchange_rate: 2.92

### Zone Pricing US ###

slug: us
name: US
countries: UM | US | VI
currency: USD
exchange_rate: .77

### Zone Pricing Canada ###

slug: canada
name: Canada
countries: CA
currency: CAD
exchange_rate: 1

### Zone Pricing Europe ###

slug: europe
name: Europe
countries: AD | AL | AT | BA | BE | BG | BY | CH | CY | CZ | DE | DK | EE | ES | FI | FO | FR | GG | GI | GR | HR | HU | IE | IM | IS | IT | JE | LI | LT | LU | LV | MC | MD | ME | MK | MT | NL | NO | PL | PT | RO | RS | SE | SI | SJ | SK | SM | UA | VA
currency: EUR
exchange_rate: 0.63

### Zone Pricing Israel ###

slug: israel
name: Israel
countries: IL
currency: ILS
exchange_rate: 2.69

### Zone Pricing NZ ###

slug: nz
name: NZ
countries: NZ
currency: NZD
exchange_rate: 1.07

### Zone Pricing UAE ###

slug: uae
name: UAE
countries: AE
currency: AED
exchange_rate: 2.84
`

**Comment by mikejolley** [comment]
It's this issue. I've left a note: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/426

Thanks
