### ISSUE TITLE
Prefixing all $ with the representing country code (frontend)

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce#20612]
We have x22 countries using the $ symbol — it is super clear to see what country / $ your site represents (in the admin side of things), but it isn't at all clear on the customer-facing end. It's just $ — and to the user, this could be AUD, it could be the US or even NZ. 

We do have the following documentation that would help the user prefix a representing country: https://docs.woocommerce.com/document/change-a-currency-symbol/ BUT it would make more sense having each $ prefixed with the representing country code, in core .. no? 

If so, I'd be happy to submit a PR for this :)

Thanks!

**Comment by mikejolley** [comment]
Seems super dependent on the store and it's target market... Don't think that works for all, and I don't think this is something we should be hardcoding unless all stores need it?

**Comment by kloon** [comment]
This will be something difficult to implement as Mike mentions the majority of stores will not make use of this and not all of the countries using the dollar sign uses the country prefix, in fact, the country code only forms part of the prefix for some countries and some countries then use the sign to indicate the use of Pesos and then use U$S as the symbol for USD.

IMO we should not make a change in core for this, I suggest we either up our documentation a bit to expand on why you would want to change the currency and then provide easy to understand instructions on how to change the currency, or better yet release some sort of small extensions which will allow you to specify a prefix, sign and postfix for the currency.

**Comment by rynaldos** [comment]
Thanks, @mikejolley | @kloon ! 

> unless all stores need it?

I haven't seen this come up a lot 

The snippet is OK for now

> some sort of small extensions which will allow you to specify a prefix, sign and postfix for the currency

I like this idea! Will see if I can whip up something over the weekend and get it onto .org

Cheers!
