### ISSUE TITLE
$0.00 price appearing on non-priced shipping - cart and checkout

### ISSUE THREAD

**Issue by spigotdesign** [woocommerce/woocommerce#20624]
Starting with 3.4 a price of $0.00 appears on non-priced shipping options such as Local Pickup. I'm not sure if this is a bug or an intended change. I checked the 3.4 changelog and didn't notice anything related. 

**To Reproduce**
Vanilla Woo install, set up shipping with Local pickup. You should see the 'price' of $0.00 on the cart and checkout.
Roll back to 3.3.5 and recheck, 'prices' are gone.

**Screenshots**
Cart page, WC 3.3.5: http://spig.io/0S1t1Q1d0l46
Cart page, WC 3.4+ : http://spig.io/2r1p1G2M0317

**Isolating the problem (mark completed items with an [x]):**
- [ X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Removed this portion for now... I'll paste back if you need it.
```
</details>

**Comment by rodrigoprimo** [comment]
Thanks for taking the time to open this issue. This was an intentional change introduced in #18624. It is listed in the changelog but maybe the wording is not clear enough: https://github.com/woocommerce/woocommerce/blob/0668eef680b3e3922071e8e5e9869db47bf414d8/CHANGELOG.txt#L103

Closing this issue for now. Please reopen if you believe we should make adjustments to the behavior introduced in 3.4.0.

cc @claudiosanches as you approved #18624 in case you have anything to add.

**Comment by spigotdesign** [comment]
Seeing it now the wording is definitely clear enough, I guess I missed that. 

I have a couple of customers who prefer not having the prices. This will be a good opportunity for me to figure out how to filter that out.

**Comment by claudiosanches** [comment]
This may help you:

```php
add_filter( 'woocommerce_cart_shipping_method_full_label', function( $label, $method ) {
    if ( 0 >= $method->cost ) {
        return $method->get_label();
    }

    return $label;
}, 10, 2 );
```

**Comment by spigotdesign** [comment]
Thanks @claudiosanches that's about what I came up with: https://gist.github.com/spigotdesign/6fcdc6dd4bc88e063cf1bd45ed8488ba

I'll update mine to use `>=` rather than `==`
