### ISSUE TITLE
"(optional)" text is very confusing for users and admin in Address line 2 field in checkout form

### ISSUE THREAD

**Issue by vishalkakadiya** [woocommerce/woocommerce#20621]
There is one **optional** word is available to Address line 2 field's placeholder attribute on the checkout page, which is quite confusing for admin and user. If anyone select Address line 2 field as required then also optional word will be displayed in customizer preview as well as on front-end, which takes a user to think why checkout form is not submitting and at the end user can't able to checkout and place order.

1. Go to Appearance >> Customize >> Woocommerce >> Checkout
2. Try to change settings for Address line 2 field.
3. Even in required option - Address line 2 field's placeholder won't change.
4. Check on front-end checkout page, you will see same placeholder text.

**Screenshots**
**Backend**
![wc-customizer](https://user-images.githubusercontent.com/9035925/41868867-ef3bb29a-78d4-11e8-8b04-1cf2612e467f.png)

**Front-end**
![wc-front-end](https://user-images.githubusercontent.com/9035925/41868925-0ebac46c-78d5-11e8-8d6f-b9c3b7996d9f.png)

**Expected behavior**
- We just need to remove `(optional)` from an end of that placeholder text. so it can be just **Apartment, suite, unit etc.**

**Comment by vishalkakadiya** [comment]
I have fixed this in https://github.com/woocommerce/woocommerce/pull/20622 PR, let me know if any changes needed. Thanks!

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20622
