### ISSUE TITLE
Existing WC_Order empty items array

### ISSUE THREAD

**Issue by manolie** [woocommerce/woocommerce#20623]
I call `$order = new WC_Order (int)` and I get the correct order object but the items array is empty! 
I am using WooCommerce 3.4.3
Am I missing something ?

**Comment by rodrigoprimo** [comment]
This is not a support forum. This GitHub repository is used exclusively for WooCommerce bugs, enhancements, and feature requests. Next time you have a question please try the WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce) or another support channel.

In case it helps, order properties should not be accessed directly:

```
>>> $o = wc_get_order( 114 )
=> WC_Order {#5266}
>>> $o->items
PHP Notice:  items was called <strong>incorrectly</strong>. Order properties should not be accessed directly (This message was added in version 3.0.)
```

To get the order items:

```
>>> $o = wc_get_order( 114 )
=> WC_Order {#5266}
>>> $o->get_items()
=> [
     1 => WC_Order_Item_Product {#5279},
     2 => WC_Order_Item_Product {#5292},
   ]
```

**Comment by manolie** [comment]
Sorry, I thought it was a bug.

**Comment by rodrigoprimo** [comment]
No worries, @manolie.
