### ISSUE TITLE
Individual hooks for "Filter by..." menus in the product admin list page

### ISSUE THREAD

**Issue by camber-ben** [woocommerce/woocommerce#20626]
**Is your feature request related to a problem? Please describe.**
I would like to remove the "Filter by Type" menu from the top of the products admin page.

**Describe the solution you'd like**
Currently in the `woocommerce/includes/admin/list-tables/class-wc-admin-list-table-products.php` file all the "Filter by..." menus are output by the `render_filters()` method.

There is a `woocommerce_product_filters` hook to filter all the menu output (presumably so you can add filter menus) but I want to remove the product type menu and keep the category and stock menus, so it is problematic and repetitive to use this filter just to strip out the middle menu from the output.

I would like a filter per menu so that each menu output can be adjusted. Something like `woocommerce_product_filters_{menu_name}` perhaps.

Than way I could use the new `woocommerce_product_filters_product_type` filter just to remove or customise that filter menu.

Thanks

**Comment by claudiulodro** [comment]
I think a small refactor like this should make it more easily customizable, keep everything backwards compatible, and won't introduce a lot of new complexity:

```
$products_filters = apply_filters( 'woocommerce_admin_products_filters', array(
	'category'     => array( $this, 'render_products_category_filter' ),
	'product_type' => array( $this, 'render_products_type_filter' ),
	'stock_status' => array( $this, 'render_stock_status_filter' ),
) );
ob_start();
foreach ( $products_filters as $filter => $callback ) {
	call_user_func( $callback );
}
$output = ob_get_clean();
echo apply_filters( 'woocommerce_product_filters', $output );
```

**Comment by benhuson** [comment]
Thanks @claudiulodro and @mikejolley  😄
