### ISSUE TITLE
filters

### ISSUE THREAD

**Issue by kurniaarifin27** [woocommerce/woocommerce#20636]
I need to filter products by lowest price, highest price and also by best selling price, latest product. Is there any filter available for any of them?

**Comment by kloon** [comment]
The default filters already cover all of this http://cld.wthms.co/GmAXYv

Popularity is the best selling and the sort by price low to high and high to low options does the pricing.

**Comment by kurniaarifin27** [comment]
i mean can we use rest api to make them?
