### ISSUE TITLE
WOO variations don't work unless you setup a default variation

### ISSUE THREAD

**Issue by nasharon** [woocommerce/woocommerce#20635]
WOO variations don't work unless you set a default variation
We expect the regular Product Image loaded to be used (group image - so the user can see all variations to choose from) and then from the dropdown the user will pick the wanted variation with it's corresponding image
Now if we want to have product variations on the site we are forced to set a Default Variation which defeats the point... 
Using WOO 3.4.3
WP 4.9.6
X theme
Hope This issue could be fixed soon

**Comment by kloon** [comment]
You are definitely not forced to set a default variation, this might be the behaviour your theme is introducing. If you leave out a default variation it will display the main product image without any option selected ( ie No default variation ), then only when you select an option will it load the image associate with that variation.

If this is not the behaviour you are seeing then it is your theme and I suggest you contact the theme developers for assistance. You can test this by switching to a default theme like Storefront or Twentyseventeen to see the right behaviour.
