### ISSUE TITLE
New woocommerce_shipping_add_rate_args and woocommerce_shipping_add_rate filters

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#20632]
The new filters will allow 3rd parties to do the falter the arguments used to prepare a shipping rate, as well as alter the rate before it's being added to the list of available rates.

**Sample use**
A use case for the new filters are multi-currency environments. The arguments used to calculate the rate may vary from currency to currency (the decimals, also added with the changes, are a perfect example of this), and the multi-currency solution can determine and alter them thanks to the filter.

Similarly, filter `woocommerce_shipping_add_rate` can be used to perform any conversion required for rate costs and taxes.

Pull request with implementation example to follow shortly.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20633#pullrequestreview-132456163 - added feedback.
