### ISSUE TITLE
Product Gallery layout

### ISSUE THREAD

**Issue by parmarhardip** [woocommerce/woocommerce#20642]
**Describe the bug**
I have added fresh WooCommerce and just I have created one product and add multiple gallery images.
And I have found the Product Gallery Layout are making image size spacing.

**To Reproduce**
1. Go to 'Products'
2. Click on 'Edit' for a product
3. Scroll down to 'Gallery' section
3. Add multiple images to the gallery
4. and see Product gallery with space.

**Screenshots**
Please check screenshot for more information: http://nimb.ws/iuA59D

**Expected behavior**
Product Gallery image list starts with a right site and without spacing.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
Not for me and no one else reported. 

![edit product test s galore wordpress 2018-06-28 14-38-48](https://user-images.githubusercontent.com/90977/42037722-04ae666e-7ae1-11e8-97f6-a4297c708e2f.png)

Do you have extensions active? What browser? Why did you ignore the issue template -- system status report?

**Comment by mikejolley** [comment]
Closing for now - needs more feedback as it's not affecting other installs.
