### ISSUE TITLE
Export CSV does not contain regular price and no variations

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#20643]
I tried first time the export function in WC for updating prices. So I went over to products > export and selected only few fields like ID, SKU, Name
[wc-product-export-27-6-2018-1530111768307.txt](https://github.com/woocommerce/woocommerce/files/2141847/wc-product-export-27-6-2018-1530111768307.txt)

 and Regular Price and as type only variable products.

In export file ID, SKU and Name could be found, but price was empty.

Only main products were exported, no variations. I checked docs for this behavior but variations should be exported!

I had not exported products in the past, so I was wondering if I miss something. Isn't it possible?

**Comment by mikejolley** [comment]
@ajgw In the "Which product types should be exported?" you must choose variations and variable to export both.

**Comment by mikejolley** [comment]
Exporting both is working my side. Variable products note however do not have prices you can import/export - they are inherited from variations (children).

Thanks
