### ISSUE TITLE
There used to be a button under "status -> tools" to delete all products - please bring it back.

### ISSUE THREAD

**Issue by asafm7** [woocommerce/woocommerce#20646]
Hi,

There used to be a button under "status -> tools" to delete all products.

It used to be very useful for us.

Can you please bring it back?

Thanks,
Asaf

**Comment by mikejolley** [comment]
This was part of import suite, not woocommerce.

Plugins exist for this: https://wordpress.org/plugins/woocommerce-remove-all-products/#description

**Comment by asafm7** [comment]
I see, thanks.
