### ISSUE TITLE
WooCommerce Set Product Image.. Not Showing

### ISSUE THREAD

**Issue by DeeRokz** [woocommerce/woocommerce#20649]
i have set the product image but it is not showing on my site..

can any one help me??

![p1](https://user-images.githubusercontent.com/40665216/42036497-508d8bb0-7b03-11e8-80a3-73a2b192a4d7.JPG)
![Uploading p2.JPG…]()
![Uploading p3.JPG…]()
![Uploading p4.JPG…]()
![Uploading p5.JPG…]()
![Uploading p6.JPG…]()

**Comment by mikejolley** [comment]
You've not provided the details asked for on https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md so we cannot attempt to reproduce this or see your site.

Go through the steps in that form first. It's likely theme related.

I'm closing this as invalid but you can reply back if you can provide more information.

Thanks

**Comment by DeeRokz** [comment]
https://store21.cc.shopshastra.com/shop/

**Comment by mikejolley** [comment]
404
