### ISSUE TITLE
Product "preview changes" button does not show product gallery updates

### ISSUE THREAD

**Issue by freddie79** [woocommerce/woocommerce#20641]
**Describe the bug**
When editing a product and making changes to the product gallery images, and then clicking the "preview changes" button, the updates to the gallery do not show up in the preview. I have tested with 2017 theme and no other plugins activated, as well as on a couple of other websites that do have other plugins active.

**To Reproduce**
1. Go to 'Products'
2. Click on 'Edit' for a product
3. Scroll down to 'Gallery' section
4. Add a new image to the gallery
5. Scroll back up to the Preview Changes button and click on it
6. The gallery changes are not shown

**Expected behavior**
I would expect the gallery changes to show in the preview before saving the edited product

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

`
### WordPress Environment ###

Home URL: http://www.roraimanursery.com.au.php72-34.phx1-1.websitetestlink.com
Site URL: http://www.roraimanursery.com.au.php72-34.phx1-1.websitetestlink.com
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4
PHP Version: 7.2.2-1+0~20180205160612.18+jessie~1.gbpb78b58
PHP Post Max Size: 10 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.26-MariaDB-1~jessie
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: ror_
MaxMind GeoIP Database: ✔
Total Database Size: 2.66MB
Database Data Size: 1.77MB
Database Index Size: 0.89MB
ror_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
ror_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
ror_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
ror_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
ror_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
ror_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
ror_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
ror_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
ror_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
ror_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
ror_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
ror_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
ror_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
ror_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ror_akeeba_common: Data: 0.02MB + Index: 0.00MB
ror_ak_params: Data: 0.02MB + Index: 0.00MB
ror_ak_profiles: Data: 0.02MB + Index: 0.00MB
ror_ak_stats: Data: 0.02MB + Index: 0.03MB
ror_ak_storage: Data: 0.02MB + Index: 0.00MB
ror_ak_users: Data: 0.02MB + Index: 0.00MB
ror_commentmeta: Data: 0.02MB + Index: 0.03MB
ror_comments: Data: 0.02MB + Index: 0.08MB
ror_links: Data: 0.02MB + Index: 0.02MB
ror_options: Data: 1.05MB + Index: 0.02MB
ror_postmeta: Data: 0.02MB + Index: 0.03MB
ror_posts: Data: 0.02MB + Index: 0.06MB
ror_termmeta: Data: 0.02MB + Index: 0.03MB
ror_terms: Data: 0.02MB + Index: 0.03MB
ror_term_relationships: Data: 0.02MB + Index: 0.02MB
ror_term_taxonomy: Data: 0.02MB + Index: 0.03MB
ror_usermeta: Data: 0.02MB + Index: 0.03MB
ror_users: Data: 0.02MB + Index: 0.05MB
ror_wc_download_log: Data: 0.02MB + Index: 0.03MB
ror_wc_webhooks: Data: 0.02MB + Index: 0.02MB
ror_widgetkit: Data: 0.02MB + Index: 0.00MB
ror_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
ror_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 3
page: 5
post: 2
product: 1
revision: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #18 - /shop/
Cart: #19 - /cart/
Checkout: #20 - /checkout/
My account: #21 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
No meta boxes, even product data e.g. price, show when previewing because WP doesn't auto save custom meta boxes.

@claudiulodro Suggest we hide this box for products since it's not useful and not worth adding at this stage given future plans around UI.

**Comment by claudiulodro** [comment]
@mikejolley hide the preview button on products? Agreed. I've always just saved a draft product if I need to preview it before publishing.

**Comment by freddie79** [comment]
Thank you for the clarification, I will pass this on to my clients, and yet hiding the preview button might be a good idea to save confusion!

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20650
