### ISSUE TITLE
Master branch: New custom attribute defaults to closed, confusing UI

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#20659]
Since #20520 the default state of the panel that appears for adding a new attribute is "closed". This isn't really a big deal for term-based attributes, as it's clear that those have an expandable row. It is confusing for custom attributes, as you just get an empty-looking row when trying to create a custom attribute. 

To reproduce: Select "Custom product attribute" and click "Add" in the attribute data panel.

See screenshots:

In 3.4.3 the default is an open panel:
<img width="963" alt="screen shot 2018-06-28 at 10 22 41 am" src="https://user-images.githubusercontent.com/7317227/42050348-7fe00f3c-7abd-11e8-82c0-e0c4e8bf7616.png">

In master the default is a closed panel. It's difficult to tell that an expandable panel has just appeared:
<img width="870" alt="screen shot 2018-06-28 at 10 19 39 am" src="https://user-images.githubusercontent.com/7317227/42050352-817ed792-7abd-11e8-8c30-22f19482b8d8.png">

cc @mikejolley. It may be an easy tweak to the code from #20520

**Comment by mikejolley** [comment]
@claudiulodro Probably not really easy. I can see why it might be good to expand on new, but expanding all on save might be weird. Need to investigate.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20664
