### ISSUE TITLE
Checkout fields cleared on page refresh

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#20656]
If Billing and/or Shipping fields are filled out on the checkout form, and then the page is refreshed, the address fields will have data kept, but the rest of the fields (name, phone, email, etc) are cleared. Is there anything we can do about this, or is this a won't fix?

Apparently it can cause issues if stores are using PayPal Standard and customers click to pay, then click to cancel and go back, the checkout page doesn't retain all of their data and they have to enter it again.

Thread: https://wordpress.org/support/topic/checkout-forgets-customer-details/

**Comment by mikejolley** [comment]
> If Billing and/or Shipping fields are filled out on the checkout form, and then the page is refreshed, the address fields will have data kept

If the form is not posted, I don't think it's correct to keep this data. This is won't fix.

> Apparently it can cause issues if stores are using PayPal Standard and customers click to pay, then click to cancel and go back, the checkout page doesn't retain all of their data and they have to enter it again.

This could be an issue however important to note it links back to cart, not checkout. We could however add some extra data to the session. PR incoming.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/20665
