### ISSUE TITLE
Move Customer Billing and Shipping Address to a custom table instead of saving in usermeta

### ISSUE THREAD

**Issue by leocheungswell** [woocommerce/woocommerce#20668]
After using woo for 2 years, there are almost 13MM rows in the usermeta table. It would be nice to at least move the billing and shipping addresses into a custom flat table. It would definitely boost performance and reporting.

**Comment by mikejolley** [comment]
Add your +1 to this https://github.com/woocommerce/woocommerce/issues/17086

I don't think it will have much impact at all on reporting FWIW though. Right now we're working on lookup tables for reports, and product custom tables, so work is underway on this type of change.

Thanks
