### ISSUE TITLE
In Latest WooCommerce How I set Hard crop for Single Product Image

### ISSUE THREAD

**Issue by sarun007** [woocommerce/woocommerce#20662]
In latest WooCommerce there is no option to enable hard crop for single product image on WooCommerce settings area.So that i have written a function in function.php for enabling hard crop for single image.

function ne_theme_setup() {
add_image_size( ‘single-product’, 600, 600, true );
}
add_action( ‘after_setup_theme’, ‘ne_theme_setup’ );

function custom_product_large_thumbnail_size() {
return ‘single-product’;
}
add_filter(‘woocommerce_gallery_image_size’, ‘custom_product_large_thumbnail_size’);
this code is working but when i select variable on single product page at that time image is changing and showing uncropped version of image.

How i solve this issue ? I want to display single image with 600X600 with hard crop for all variations of product.

**Comment by mikejolley** [comment]
Please don't post support questions here.

See https://github.com/woocommerce/woocommerce/wiki/Customizing-image-sizes-in-3.3

**Comment by sarun007** [comment]
One doubt if i use   add_filter( 'woocommerce_single', function( $size ) {
    return array(
        'width'  => 150,
        'height' => 150,
        'crop'   => 1,
    );
} );

then it will work ?
