### ISSUE TITLE
REST API returns wrong next page URL when getting product attribute terms.

### ISSUE THREAD

**Issue by chrono-meter** [woocommerce/woocommerce#20673]
**Describe the bug**
WooCommerce REST API returns wrong next page URL when getting product attribute terms.
This bug is caused by lacking regex pattern ('(?P<attribute_id>[\d]+)') replacement on [this line](https://github.com/woocommerce/woocommerce/blob/8d6bbabc58a99934eda252b2fff5468d06c8837b/includes/abstracts/abstract-wc-rest-terms-controller.php#L347), fixed code is like:
>		$base = '/' . $this->namespace . '/' . $this->rest_base;
>		if ( ! empty( $request['attribute_id'] ) ) {
>			$base = str_replace( '(?P<attribute_id>[\d]+)', (int) $request['attribute_id'], $base );
>		}
>		$base = add_query_arg( $request->get_query_params(), rest_url( $base ) );

**To Reproduce**
1. Create product attribute and insert attribute terms.
2. Access REST API, GET "http://example.com/wp-json/wc/v2/products/attributes/1/terms".
3. There is a wrong 'next' URL in response 'Link' header, like "http://example.com/wp-json/wc/v2/products/attributes/(?P<attribute_id>%5B\\d%5D&page=2".

**Screenshots**
None.

**Expected behavior**
Expected URL is like "http://example.com/wp-json/wc/v2/products/attributes/1/terms?page=2".

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://future.paradishouse.jp
Site URL: https://future.paradishouse.jp
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: ja
External object cache: –

### Server Environment ###

Server Info: nginx/1.4.6
PHP Version: 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 1,000 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60-0ubuntu0.14.04.1 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 15.92MB
Database Data Size: 13.20MB
Database Index Size: 2.72MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_address_components: Data: 0.02MB + Index: 0.00MB
wp_aws_index: Data: 0.16MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_fbuilder_fields: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.16MB + Index: 0.06MB
wp_postmeta: Data: 5.52MB + Index: 0.72MB
wp_posts: Data: 1.50MB + Index: 0.34MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.06MB + Index: 0.03MB
wp_term_relationships: Data: 0.34MB + Index: 0.14MB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_wfConfig: Data: 0.39MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 1.52MB + Index: 0.00MB
wp_wfHits: Data: 1.02MB + Index: 0.34MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB
wp_wfKnownFileList: Data: 0.42MB + Index: 0.00MB
wp_wfLeechers: Data: 0.06MB + Index: 0.00MB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.13MB + Index: 0.09MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1178
custom_css: 1
nav_menu_item: 5
page: 6
post: 3
product: 175
properties: 6
revision: 28
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Contact Form 7: by Takayuki Miyoshi – 5.0.2
Debug Log: by Andrew J Klimek – 0.3
DX Delete Attached Media: by nofearinc – 1.0
WooCommerce For Japan: by Artisan Workshop – 1.2.20 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.3
Wordfence Security: by Wordfence – 7.1.8
WordPress Importer: by wordpressdotorg – 0.6.4
WP Multibyte Patch: by 倉石 政典 – 2.8.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: JPY (円)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart
Checkout: #6 - /checkout
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /home/ittech/future.paradishouse.jp/wordpress/wp-content/plugins/my/templates/single-product/product-attributes.php
`</details>

**Comment by peterfabian** [comment]
Thanks for reporting. 
Will be fixed by PR #20686.
