### ISSUE TITLE
"Read more" button has .ajax_add_to_cart

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#20677]
"Read more" button has <code>.ajax_add_to_cart</code> while "select options" doesn't and "add to cart" does. It should be removed from the "Read more" button.

**Comment by peterfabian** [comment]
`.ajax_add_to_cart` gets assigned to all products that support `ajax_add_to_cart` (or, to be more precise, to the buttons on the shop page), so it might have be used in other circumstances, but the linked PR should fix this.
