### ISSUE TITLE
PHP Notice:  Undefined index: store_state added in debug.log during setup configuration

### ISSUE THREAD

**Issue by dimitrismitsis** [woocommerce/woocommerce#20684]
**PHP Notice added in debug.log**

`PHP Notice:  Undefined index: store_state in /app/public/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php on line 517`

`PHP   1. {main}() /app/public/wp-admin/index.php:0 `
`PHP   2. require_once() /app/public/wp-admin/index.php:10`
`PHP   3. do_action() /app/public/wp-admin/admin.php:156`
`PHP   4. WP_Hook->do_action() /app/public/wp-includes/plugin.php:453`
`PHP   5. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310`
`PHP   6. WC_Admin_Setup_Wizard->setup_wizard() /app/public/wp-includes/class-wp-hook.php:286`
`PHP   7. WC_Admin_Setup_Wizard->wc_setup_store_setup_save() /app/public/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-setup-wizard.php:240`

**To Reproduce**
1. Clean WordPress setup in English with only WooCommerce activated
2. Proceed to the first step of setup wizard
3. Fill in Address, City and Zip code, leave untouched the rest of the options
4. Click "Let's go!"
5. See error

**Screenshots**
![screen shot 2018-07-02 at 15 58 03](https://user-images.githubusercontent.com/15674753/42165455-bb7e4706-7e10-11e8-8290-322b356ec1e5.png)

**Comment by rodrigoprimo** [comment]
Thanks for your report. #20695 should fix this.
