### ISSUE TITLE
Cart widget doesn't support Customizer selective refresh?

### ISSUE THREAD

**Issue by daviedR** [woocommerce/woocommerce#20696]
**Describe the bug**
Looks like the Cart widget doesn't support selective refresh on Customizer. When adding cart widget into Sidebar from Customizer, the widget is blank.

**To Reproduce**
1. Go to 'Appearance > Customize'
2. Click on 'Widgets' and choose your Sidebar
3. Put a 'Cart' widget
4. The widget is blank

**Comment by claudiulodro** [comment]
Just getting this fine-tuned in #20830
