### ISSUE TITLE
Status report does not show all available plugin updates

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#20694]
**Describe the bug**
There are some plugins which are provided by WooCommerce.com but are available as free plugins on WordPress.org
In this case the report tries to get the latest version from a changelog file and fails. This results in it not displaying the available update.

In this case I noticed it for the plugin `WooCommerce PayPal Express Checkout Gateway`. I have version 1.5.6 installed. In the regular plugin updates it shows version 1.6.0 is available. But this does not show up in the Status report.

This is also the case for other plugins which are available on WooCommerce.com but hosted through WordPress.org.

**To Reproduce**
1. Install `WooCommerce PayPal Express Checkout Gateway` version 1.5.6 and activate
2. View Dashboard > Updates and see that there is an update available
3. View WooCommerce > Status and look at the active plugins and see that there doesn't show any update available

The status report shows:

```
WooCommerce PayPal Express Checkout Gateway | by WooCommerce – 1.5.6
```

**Expected behavior**
I'd expect the update to show up in the Status report. So it should show as:

```
WooCommerce PayPal Express Checkout Gateway | by WooCommerce – 1.5.6 – 1.6.0 is available
```

**Additional information**
In the following line of code it checks if the plugin is from WooCommerce.com: https://github.com/woocommerce/woocommerce/blob/3.4.3/includes/api/class-wc-rest-system-status-controller.php#L790
In this case the PluginURI = `https://woocommerce.com/products/woocommerce-gateway-paypal-express-checkout/`
So this check passes. Next it gets the transient for the version_data, but since this plugin is available on WordPress.org this transient is not saved and it return false, when it returns false it tries to get the changelog file from the following URL:
http://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-gateway-paypal-express-checkout/changelog.txt

But that returns an access denied response, so it's unable to get the correct version and `$version_data['version']` is never set.

For this specific scenario it should be getting the version from `$available_updates[ $plugin ]->update->new_version`

So the checks would either need to be reversed to check if this version is available before assuming it's a WooCommerce plugin. Or we would need some better checks for plugins that are provided by WooCommerce.com but hosted on WordPress.org.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WooCommerce 3.4.3
WordPress 4.9.6
Storefront 2.3.2
```
</details>

**Comment by rodrigoprimo** [comment]
Thanks for the detailed report, @mikkamp. I could reproduce the issue that you described.

@mattyza, do you happen to know if there is an easy way to identify plugins provided by WooCommerce.com but available as free plugins on WordPress.org?

**Comment by claudiulodro** [comment]
@rodrigoprimo the plugin version has been updated to 1.6 in both locations, so the behavior probably wouldn't be possible to reproduce any more.

**Comment by mattyza** [comment]
> @mattyza, do you happen to know if there is an easy way to identify plugins provided by WooCommerce.com but available as free plugins on WordPress.org?

Hmmm... in the context of these update notifications, the most direct option would be a ping to WordPress.org if the changelog file check pinging WooCommerce.com fails.
