### ISSUE TITLE
How can i manage the cart via Rest api

### ISSUE THREAD

**Issue by redsparkers** [woocommerce/woocommerce#20699]
Hello,
In recent time we are working on the rest api for woocommerce but i am not able to manage the cart from api. can you please provide any relavent link or source so i will get some solution .
hope for help . 

Thank you

**Comment by redsparkers** [comment]
Yes, but this plugin functions are deprecated.

**Comment by claudiosanches** [comment]
You should create sessions for the users on your app and after they finish picking all products, you can create an order as pending, process payments on your app and then change the order to processing, so you can control using the orders endpoint.
