### ISSUE TITLE
Want to make stock quantity constant.. to be not able to decrease after ordering in woocommerce

### ISSUE THREAD

**Issue by Shizo0o0o** [woocommerce/woocommerce#20691]
I want to make stock quantity unchangeable.
assuming that a product quantity= 20 and someone made an order, by default it becomes 19, i want it to still 20 whatever happened.

I use woocommerce and wordpress.

**Comment by rodrigoprimo** [comment]
HI @Shizo0o0o,

I'm sorry, but this is not a support forum. We use GitHub issues exclusively for WooCommerce core bugs, enhancements and feature requests. For support, you could try the WooCommerce forum on the WordPress.org site: https://wordpress.org/support/plugin/woocommerce

Unfortunately, I don't know off the top of my head a way to make stock quantity remain unchangeable. If you haven't considered it yet, you could disable stock management globally (https://docs.woocommerce.com/document/configuring-woocommerce-settings/#inventory-options) or for specific products (https://docs.woocommerce.com/document/managing-products/#inventory-tab). That is not exactly what you are looking for, but it is the closest I can think of and worth mentioning in case you haven't considered it already.
