### ISSUE TITLE
WooCommerce Email Templates: Hooking the <p>Message</p>

### ISSUE THREAD

**Issue by BusinessBloomer** [woocommerce/woocommerce#20693]
**Is your feature request related to a problem? Please describe.**

Each email template comes with a hardcoded message. For example, the Processing Email (customer-processing-order.php) has this:

`<p><?php _e( "Your order has been received and is now being processed. Your order details are shown below for your reference:", 'woocommerce' ); ?></p>`

**Describe the solution you'd like**

Problem is, this can only be overwritten with a workaround (get_text) which is not a good idea. Also, I'm excluding the template override thing. I want to achieve this by hooks.

**Describe alternatives you've considered**

As the rest of the template is basically a list of do_actions, why not hooking this message with an action as opposed to printing it in the template?

Something like:

```
add_action( 'woocommerce_email_order_details', 'output_customer_processing_email_message', 5, 4 );

function output_customer_processing_email_message( $order, $sent_to_admin, $plain_text, $email ) {
if ( $email->id == 'customer_processing_order' ) {
?>
<p><?php _e( "Your order has been received and is now being processed. Your order details are shown below for your reference:", 'woocommerce' ); ?></p>
<?php
} elseif ( $email->id == 'customer_completed_order' ) {
// ETC
}
}
```

In this way I can simply do this to remove everything and hook my custom messages:

`remove_action( 'woocommerce_email_order_details', 'output_customer_processing_email_message', 5, 4 );
`

Sounds easy to me, and this would solve most email overriding problems.

LMK!

**Comment by claudiulodro** [comment]
[We'll be greatly improving and refactoring the emails over the next couple releases](https://github.com/woocommerce/woocommerce/issues/10704). Once that's done you shouldn't need code to change the content of the messages. :)

Thanks for the suggestion!
