### ISSUE TITLE
"Flat rate" can not translate

### ISSUE THREAD

**Issue by notrealdev** [woocommerce/woocommerce#20692]
Hi, i'm using a WPML plugin to translate.
I have translated all strings into my language (specifically is Korean)
When I added a product on shop page, `"Flat rate"` was translated to `"Can not translate ! ! !"` but it can not be translated if I add a product on product page, I do not know how to handle this issue

Hope you can support me to handle it

Issue:
https://www.youtube.com/watch?v=64U7PyTiHC0&feature=youtu.be

Demo online:
- Product page: https://teoryne.com/product/nmbt/
- Shop page: https://teoryne.com/

**Comment by rodrigoprimo** [comment]
Hi,

I'm sorry but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce) or WPML support.

Please reopen this issue if you can reproduce it when running WooCommerce on a clean WordPress install using Storefront or one of the default WordPress themes.
