### ISSUE TITLE
WooCommerce - Add Order - Bank Account Details not being included in customer invoice email

### ISSUE THREAD

**Issue by quinnfive** [woocommerce/woocommerce#20702]
**Describe the bug**
When creating a new order manually in WooCommerce backend and selecting Direct Bank Transfer as payment option, customer email invoice does not include the bank account details.  Note: When a customer purchases and selects Direct Bank Transfer as payment on the front end and checks out, the customer does receive an invoice with the bank account details.

**To Reproduce**
1. Go to 'WooCommerce -> Orders'
2. Click on 'Add Order'
3. Enter customer details. 
4. Select 'Billing -> Payment Method'
5. Choose 'Direct bank transfer'
6. Order actions -> Choose action '"Email invoice / order details to customer" -> click 'Create'
4. Now go to the customers email inbox and check the invoice and the Bank Account Details will not be included in the invoice the customer receives.

Screen shot of WooCommerce: 

http://nimb.ws/TZJc2a

Screen shot of email invoice missing bank details which was created via the 'Add Order' option : 

http://nimb.ws/pMfFyc

Screen shot of email invoice which was created via the customer purchasing themselves : 

http://nimb.ws/UK5FLT

**Expected behavior**
I expect the Add Order option to email the customer invoice including the Bank Account Details as per when the customer will checkout themselves.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Version 4.9.6

### WordPress Environment ###

Home URL: https://hvactools.co.nz
Site URL: https://hvactools.co.nz
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.30-1~dotdeb+8.1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 10 MB
PHP Time Limit: 60
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.32-MariaDB-1~jessie
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wp_
Total Database Size: 14.14MB
Database Data Size: 12.71MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 2.35MB + Index: 0.08MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB
wp_woocommerce_order_itemmeta: Data: 0.03MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_alm: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.01MB + Index: 0.02MB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wp_itsec_logs: Data: 1.52MB + Index: 0.09MB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 2.71MB + Index: 0.08MB
wp_pbs: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 3.68MB + Index: 0.45MB
wp_posts: Data: 1.70MB + Index: 0.11MB
wp_revslider_css: Data: 0.09MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.07MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_swift_performance_warmup: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.01MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.01MB + Index: 0.03MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wp_usermeta: Data: 0.06MB + Index: 0.03MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woof_query_cache: Data: 0.00MB + Index: 0.00MB
wp_wpmelon_advbedit_temp: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

aiosrs-schema: 1
amn_exact-metrics: 1
astra-advanced-hook: 2
attachment: 264
custom_css: 2
elementor_library: 4
footer: 5
jet-menu: 2
megamenu: 6
nav_menu_item: 31
oembed_cache: 1
page: 15
post: 3
product: 95
revision: 295
shop_coupon: 1
shop_order: 31
vtprd-rule: 1
wpmm_theme: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Admin Menu Editor Pro: by Janis Elsts – 2.6.5
Akismet Anti-Spam: by Automattic – 4.0.8
Astra Pro: by Brainstorm Force – 1.3.4
iThemes Security: by iThemes – 7.0.4
Breeze: by Cloudways – 1.0.10
Code Snippets: by Shea Bunge – 2.10.1.1
Duplicate Page: by mndpsingh287 – 2.6
Google Tag Manager for Wordpress: by Thomas Geiger – 1.8.1
Elementor Pro: by Elementor.com – 2.0.11
Elementor: by Elementor.com – 2.1.0
eWAY Payment Gateway: by WebAware – 4.2.2
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.5
Granular Controls Elementor: by Zulfikar Nore – 1.0.5
Imagify: by WP Media – 1.8.0.1
JetMenu: by Zemez – 1.3.5
Jilt for WooCommerce: by Jilt – 1.5.0
Kwayy HTML Sitemap: by Kwayy Infotech – 3.1
WooCommerce Load More Products: by BeRocket – 1.1.1
Metorik Helper: by Metorik – 0.15.0 – Not tested with the active version of WooCommerce
SEO Ultimate Plus: by SEO Design Solutions – 2.0.7
Simple CSS: by Tom Usborne – 1.1
Smart WooCommerce Search: by YummyWP – 1.5.2
Ultimate Addons for Elementor: by Brainstorm Force – 1.4.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.14.11

WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.2.4 – Not tested with the active version of WooCommerce
Woocommerce Advanced Bulk Edit: by George Iron – 4.2.5 – Not tested with the active version of WooCommerce
WooCommerce AdWords Conversion Tracking: by Wolf+Bär Agency – 1.4.8
WooCommerce: by Automattic – 3.4.3
WP Mail SMTP: by WPForms – 1.3.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1223 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: ❌ Page does not contain the shortcode.
Terms and conditions: #1392 - /terms-conditions/

### Theme ###

Name: Astra
Version: 1.3.3 – 1.3.4 is available
Author URL: http://wpastra.com/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Jilt ###

Plugin Version: 1.5.0
Jilt API Version: v2
Jilt API Authentication Method: OAuth
Jilt API Connected: ✔
Linked to Jilt: ✔
Enabled: ✔
WooCommerce API: 
`

**Comment by claudiulodro** [comment]
Hi there,

When an invoice is sent for an order created through the back-end, there is a link in the invoice e-mail for the customer to complete payment for the order:
<img width="618" alt="screen shot 2018-07-05 at 9 20 53 am" src="https://user-images.githubusercontent.com/7317227/42335374-fca3bfb0-8034-11e8-8d7f-9d8962096e4e.png">

That link will let the customer select Direct bank transfer or one of the other available payment methods on your site. If they select Direct bank transfer they will be presented with the banking information and also receive an email that looks exactly like the one you have with the banking information in it. 

The "Payment method" section on the new order screen doesn't force the customer to use the selected payment method (and there isn't really a way to force a customer to use a specific payment method when an admin creates the customer's order); the field is for recording the payment method used.

I'm closing this issue, as the customer receives the banking information for orders created through the admin back-end.

Thanks.
