### ISSUE TITLE
wc_get_products() isn't returning all products in category

### ISSUE THREAD

**Issue by ntindicator** [woocommerce/woocommerce#20701]
**Describe the bug**
If I run a query with wc_get_products() using the category slug it only returns 12 products, but with a higher limit defined it works. E.g. there are 23 products in the category, but it only returns 12, but if limit of 25 is used, 23 products are returned. I also tried with 'paginate' set to false, but it didn't change the result.

**To Reproduce**

**Screenshots**
`$args = array(
        'category' => array( $_POST['selectCat'] ),
        'orderby'  => 'name',
        'limit' => 25,
      );
      $products = wc_get_products( $args );
     die(print_r( count($products) . "  " ) );`

**Expected behavior**
All products in the category to be returned from query, without needing to define higher limit.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
4.9.5
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiosanches** [comment]
> If I run a query with wc_get_products() using the category slug it only returns 12 products, but with a higher limit defined it works. E.g. there are 23 products in the category, but it only returns 12

Yes, only return 12 because your settings, by default will use `get_option( 'posts_per_page' )` as limit, you can set it in WordPress Settings.

>  but if limit of 25 is used, 23 products are returned. I also tried with 'paginate' set to false, but it didn't change the result

There is no `paginate` parameter allowed in this function, that's why does not work, you should use `limit` as `-1`, if you want all results at once.

So this it's not a bug.
