### ISSUE TITLE
Emogrify removes some inline styles due to wordwrap

### ISSUE THREAD

**Issue by joshuadwire** [woocommerce/woocommerce#20707]
**Describe the bug**
The parent `WC_Email` class calls  `wordwrap( $email_content, 70 )` on all email content, including HTML. This can result in inline styles ending up with line-breaks in the middle of a declaration like this:

    			<th scope="col" style="text-align:left; border: 1px
    solid #eee;"><?php _e( 'Product', 'wc-pre-orders' ); ?></th>
 
As part of inlining CSS styles, the `Emogrifier` class attempts to parse the inline CSS declarations in `parseCssDeclarationsBlock`, but when it gets a declaration like  `"border: 1px\nsolid #eee"`, it rejects it, due to the line break, and does not include it in the finalized HTML. This results in inline CSS rules being removed from the source HTML with no apparent pattern and can break email styling.

**To Reproduce**
One plugin that encounters this bug is [WooCommerce Pre-Orders](https://woocommerce.com/products/woocommerce-pre-orders/) (paid plugin). Some of the table cells have their border styling removed, since the border style is wrapped onto two lines by wordwrap and stripped by Emogrifier.

**Expected behavior**
I would either expect `wordwrap()` to not be run for HTML emails or Emogrify to correctly handle style declarations containing line breaks.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

_Note: I temporarily commented out the call to `wordwrap` and the issue was resolved. I'd expect the issue can be solved by removing the `wordwrap` call for HTML or by calling `wordwrap` after Emogrify has been run._

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://localdev.wilds.org/store
Site URL: http://localdev.wilds.org/store
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.5 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: ce0p3_
Total Database Size: 223.77MB
Database Data Size: 153.59MB
Database Index Size: 70.18MB
ce0p3_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
ce0p3_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
ce0p3_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
ce0p3_woocommerce_downloadable_product_permissions: Data: 0.13MB + Index: 0.19MB
ce0p3_woocommerce_order_items: Data: 0.47MB + Index: 0.19MB
ce0p3_woocommerce_order_itemmeta: Data: 5.52MB + Index: 6.03MB
ce0p3_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
ce0p3_woocommerce_tax_rate_locations: Data: 0.08MB + Index: 0.14MB
ce0p3_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
ce0p3_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
ce0p3_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
ce0p3_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
ce0p3_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
ce0p3_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ce0p3_akeeba_common: Data: 0.02MB + Index: 0.00MB
ce0p3_ak_params: Data: 0.02MB + Index: 0.00MB
ce0p3_ak_profiles: Data: 0.02MB + Index: 0.00MB
ce0p3_ak_stats: Data: 0.02MB + Index: 0.03MB
ce0p3_ak_storage: Data: 11.52MB + Index: 0.00MB
ce0p3_ak_users: Data: 0.02MB + Index: 0.00MB
ce0p3_commentmeta: Data: 0.02MB + Index: 0.03MB
ce0p3_comments: Data: 4.52MB + Index: 3.80MB
ce0p3_links: Data: 0.02MB + Index: 0.02MB
ce0p3_options: Data: 3.17MB + Index: 0.20MB
ce0p3_pmxe_exports: Data: 0.33MB + Index: 0.00MB
ce0p3_pmxe_posts: Data: 1.52MB + Index: 0.00MB
ce0p3_pmxe_templates: Data: 0.02MB + Index: 0.00MB
ce0p3_pmxi_files: Data: 0.02MB + Index: 0.00MB
ce0p3_pmxi_history: Data: 0.02MB + Index: 0.00MB
ce0p3_pmxi_imports: Data: 1.52MB + Index: 0.00MB
ce0p3_pmxi_posts: Data: 1.52MB + Index: 0.00MB
ce0p3_pmxi_templates: Data: 0.09MB + Index: 0.00MB
ce0p3_postmeta: Data: 35.58MB + Index: 36.13MB
ce0p3_posts: Data: 72.63MB + Index: 6.44MB
ce0p3_relevanssi: Data: 3.52MB + Index: 6.06MB
ce0p3_relevanssi_log: Data: 1.52MB + Index: 0.00MB
ce0p3_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB
ce0p3_termmeta: Data: 0.11MB + Index: 0.17MB
ce0p3_terms: Data: 0.09MB + Index: 0.14MB
ce0p3_term_relationships: Data: 2.52MB + Index: 2.52MB
ce0p3_term_taxonomy: Data: 0.09MB + Index: 0.11MB
ce0p3_usermeta: Data: 5.52MB + Index: 7.03MB
ce0p3_users: Data: 0.27MB + Index: 0.25MB
ce0p3_vtprd_lifetime_limits_purchaser: Data: 0.02MB + Index: 0.02MB
ce0p3_vtprd_lifetime_limits_purchaser_logid_rule: Data: 0.02MB + Index: 0.02MB
ce0p3_vtprd_lifetime_limits_purchaser_rule: Data: 0.02MB + Index: 0.02MB
ce0p3_vtprd_purchase_log: Data: 0.45MB + Index: 0.02MB
ce0p3_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
ce0p3_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
ce0p3_wc_download_log: Data: 0.06MB + Index: 0.03MB
ce0p3_wc_webhooks: Data: 0.02MB + Index: 0.02MB
ce0p3_woocommerce_bundled_itemmeta: Data: 0.20MB + Index: 0.25MB
ce0p3_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
ce0p3_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB
ce0p3_wpfront_ure_options: Data: 0.03MB + Index: 0.00MB

### Post Type Counts ###

amn_smtp: 4
attachment: 2623
banner: 1
banner_product: 5
cue_playlist: 62
customize_changeset: 1
nav_menu_item: 45
page: 21
post: 5
product: 3172
product_variation: 2
revision: 408
shop_coupon: 34
shop_order: 1760
shop_order_refund: 7
tw_wssi_batch: 262
tw_wssi_error: 10922
vtprd-rule: 8
wishlist: 3090

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (49) ###

User Switching in Admin Bar: by Mark Wilkinson – 1.1.1
Akeeba Backup for WordPress: by Akeeba Ltd – 2.3.2
Better Search Replace: by Delicious Brains – 1.3.2
Black Studio TinyMCE Widget: by Black Studio – 2.6.2
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.20
Cue: by AudioTheme – 2.3.3
Enable Media Replace: by ShortPixel – 3.2.5
Enhanced Media Library: by wpUXsolutions – 2.6.4
FooTable: by Brad Vincent – 0.3.1
Homepage Control: by WooThemes – 2.0.3
Mailgun: by Mailgun – 1.5.11
MCE Table Buttons: by Jake Goldman
10up
Oomph – 3.3

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Relevanssi: by Mikko Saari – 4.0.10.1
Fast Secure Contact Form: by fastsecure – 4.0.56
Simple Image Widget: by Cedaro – 4.4.2
Storefront Site Logo: by Wooassist – 1.2.3
TW Dev Store Modifications: by The Wilds – 1.1.0 – Not tested with the active version of WooCommerce
TW Online Store Addons: by The Wilds – 1.3.3
TW Product Search: by Joshua Dwire – 1.1.4 – Not tested with the active version of WooCommerce
The Wilds Updater: by Joshua Dwire – 1.0.1
WooCommerce - Sage SData Integration: by Andy Anglea – 1.3.11 – Not tested with the active version of WooCommerce
User Switching: by John Blackbourn & contributors – 1.3.1
Widget Context: by Kaspars Dambis – 1.1.0
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.9
WooCommerce Coupon Links Enhancements: by The Wilds – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Coupon Links: by Cedaro – 2.2.0 – Not tested with the active version of WooCommerce
WooCommerce Print Invoice & Delivery Note: by Tyche Softwares – 4.4.2 – Not tested with the active version of WooCommerce
WooCommerce - Store Exporter: by Visser Labs – 2.0 – Not tested with the active version of WooCommerce
WooCommerce Authorize.Net CIM Gateway: by SkyVerge – 2.10.1
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.2.1
WooCommerce Phone Orders & Manual Orders: by IgniteWoo.com – 3.0.6 – Not tested with the active version of WooCommerce
WooCommerce PDF Watermark: by WooCommerce – 1.1.6
WooCommerce Pre-Orders: by WooCommerce – 1.5.9
WooCommerce Product Bundles: by SomewhereWarm – 5.7.10 – 5.7.11 is available
WooCommerce Password Protected Categories: by Barn2 Media – 1.7.3
WooCommerce Shipment Tracking: by WooCommerce – 1.6.11
WooCommerce UPS Shipping: by WooCommerce – 3.2.10
WooCommerce USPS Shipping: by WooCommerce – 4.4.18
WooCommerce Smart Coupons: by WooCommerce – 3.4.6
WooCommerce Social Login: by SkyVerge – 2.5.2
WooCommerce Wholesale Order Form: by Rymera Web Co – 1.8.3 – Not tested with the active version of WooCommerce
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.16.6
WooCommerce Wholesale Prices: by Rymera Web Co – 1.6.5
WooCommerce WishLists: by Lucas Stark – 2.1.9
WooCommerce: by Automattic – 3.4.3
WP Crontrol: by John Blackbourn & contributors – 1.6.2
WP Last Login: by Konstantin Obenland – 2
WPFront User Role Editor: by Syam Mohan – 2.14.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #181 - /
Cart: #191 - /cart/
Checkout: #701 - /checkout/
My account: #711 - /my-account/
Terms and conditions: #8543 - /terms-conditions/

### Theme ###

Name: Wilds Online Store
Version: 1.2.12
Author URL: http://wilds.org
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.3.2
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: wilds-online-store/woocommerce/cart/cart-shipping-checkout.php
wilds-online-store/woocommerce/components/cart-totals/cart-totals.php
wilds-online-store/woocommerce/cart/cart.php
wilds-online-store/woocommerce/cart/mini-cart.php
wilds-online-store/woocommerce/checkout/form-coupon.php
wilds-online-store/woocommerce/checkout/form-login.php
wilds-online-store/woocommerce/checkout/payment-method.php
wilds-online-store/woocommerce/checkout/review-order.php
wilds-online-store/woocommerce/emails/customer-new-account.php
wilds-online-store/woocommerce/emails/customer-on-hold-order.php
wilds-online-store/woocommerce/emails/customer-reset-password.php
wilds-online-store/woocommerce/emails/email-customer-details.php
wilds-online-store/woocommerce/emails/plain/customer-on-hold-order.php
wilds-online-store/woocommerce/emails/plain/customer-reset-password.php
wilds-online-store/woocommerce/global/quantity-input.php
wilds-online-store/woocommerce/loop/add-to-cart.php
wilds-online-store/woocommerce/loop/orderby.php
wilds-online-store/woocommerce/myaccount/dashboard.php
wilds-online-store/woocommerce/single-product/add-to-cart/grouped.php
wilds-online-store/woocommerce/single-product/title.php

### Product Bundles ###

Database Version: 5.7.10
Template Overrides: wilds-online-store/woocommerce/single-product/bundled-item-image.php

### Authorize.Net CIM ###

Environment: Test
Tokenization Enabled: 
Debug Mode: Off
Webhooks Enabled: ❌
						No signature key configured

### Authorize.Net CIM eCheck ###

Environment: Test
Tokenization Enabled: 
Debug Mode: Off
Webhooks Enabled: Inherited
`
</details>

**Comment by claudiulodro** [comment]
See #20723
