### ISSUE TITLE
Search key doesn't work in REST API list screen

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#20705]
**Describe the bug**
Searching in REST API list page, `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=keys`, redirects the page to `/wp-admin/admin.php?page=wc-settings`.

<img width="1324" alt="screen shot 2018-07-04 at 23 21 34" src="https://user-images.githubusercontent.com/78313/42287644-671c9ece-7fe1-11e8-8d31-a1ce7b6b554a.png">

**To Reproduce**
1. Go to `/wp-admin/admin.php?page=wc-settings&tab=advanced&section=keys`.
2. Search key.
3. It redirects to `/wp-admin/admin.php?page=wc-settings`.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
See #20706
