### ISSUE TITLE
Display Side Wide Store Notice not available for Shop Managers (WC 3.3+)

### ISSUE THREAD

**Issue by ValeDeOro** [woocommerce/woocommerce#20708]
**Describe the bug**
Until WooCommerce 3.3 the Side Wide Store Notice was set via Settings > General, and thus was accessible for the user sole Shop Manager. 

This option has been moved to the Customizer, so now an admin role is needed to update/change the banner. 

**To Reproduce**
1. Create a Shop Manager Role
2. Use WooCommerce 3.3+
3. Try to edit the Side Wide Store Notice. 

**Expected behavior**
Shop Managers should be able to edit the side wide banner. This is part of their tasks.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ValeDeOro** [comment]
Reported by customer 1261612-zen

**Comment by kloon** [comment]
#20728
