### ISSUE TITLE
Fatal error WC_Shipping->get_shipping_methods

### ISSUE THREAD

**Issue by piotrjozwiak** [woocommerce/woocommerce#20703]
**Describe the bug**
I am getting the fatal error when trying to get a list of available shipping methods.
As far as I know, this error does not happen at all woocommerce instances but only a few.
**To Reproduce**
In payment module I do execute:
`$Shipping = new WC_Shipping();
$shippingMethods = $Shipping->get_shipping_methods();`

and I get the following fatal:

> *Fatal error*: Uncaught Error: Call to a member function
get_shipping_countries() on null in
/home/markadius/domains/meblearkadius.pl/public_html/wp-content/plugins/woocommerce/includes/shipping/flat-rate/includes/settings-flat-rate.php:47Stack
trace: #0
/home/markadius/domains/meblearkadius.pl/public_html/wp-content/plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php(47):
include() #1
/home/markadius/domains/meblearkadius.pl/public_html/wp-content/plugins/woocommerce/includes/shipping/flat-rate/class-wc-shipping-flat-rate.php(38):
WC_Shipping_Flat_Rate->init() #2
/home/markadius/domains/meblearkadius.pl/public_html/wp-content/plugins/woocommerce/includes/class-wc-shipping.php(194):
WC_Shipping_Flat_Rate->__construct() #3
/home/markadius/domains/meblearkadius.pl/public_html/wp-content/plugins/woocommerce/includes/class-wc-shipping.php(172):
WC_Shipping->register_shipping_method(‘WC_Shipping_Fla…’) #4
/home/markadius/domains/meblearkadius.pl/public_html/wp-content/plugins/woocommerce/includes/c
in
*/home/markadius/domains/meblearkadius.pl/public_html/wp-content/plugins/woocommerce/includes/shipping/flat-rate/includes/settings-flat-rate.php*
on line *47

**Expected behavior**
I would like to get array of shipping methods.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.12.1
PHP Version: 7.0.29-1~dotdeb+8.1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 50
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 4.90MB
Database Data Size: 3.30MB
Database Index Size: 1.60MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.06MB + Index: 0.09MB
wp_edd_customermeta: Data: 0.02MB + Index: 0.03MB
wp_edd_customers: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.02MB + Index: 0.05MB
wp_postmeta: Data: 0.39MB + Index: 0.41MB
wp_posts: Data: 0.08MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_tpay: Data: 0.02MB + Index: 0.00MB
wp_wpsc_also_bought: Data: 0.00MB + Index: 0.00MB
wp_wpsc_cart_contents: Data: 0.00MB + Index: 0.00MB
wp_wpsc_cart_item_meta: Data: 0.00MB + Index: 0.01MB
wp_wpsc_checkout_forms: Data: 0.00MB + Index: 0.01MB
wp_wpsc_claimed_stock: Data: 0.00MB + Index: 0.00MB
wp_wpsc_coupon_codes: Data: 0.00MB + Index: 0.00MB
wp_wpsc_currency_list: Data: 0.02MB + Index: 0.01MB
wp_wpsc_download_status: Data: 0.00MB + Index: 0.00MB
wp_wpsc_meta: Data: 0.00MB + Index: 0.01MB
wp_wpsc_product_rating: Data: 0.00MB + Index: 0.00MB
wp_wpsc_purchase_logs: Data: 0.01MB + Index: 0.01MB
wp_wpsc_purchase_meta: Data: 0.00MB + Index: 0.02MB
wp_wpsc_region_tax: Data: 0.00MB + Index: 0.00MB
wp_wpsc_submited_form_data: Data: 0.03MB + Index: 0.03MB
wp_wpsc_visitors: Data: 0.00MB + Index: 0.01MB
wp_wpsc_visitor_meta: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 2
download: 1
edd_log: 1
edd_payment: 2
page: 16
post: 1
product: 6
revision: 8
shop_order: 108
shop_order_refund: 3
wpcf7_contact_form: 1
wpsc-product: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

CloudFlare Flexible SSL: by iControlWP – 1.2.2
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.2

Contact Form 7 - PayPal & Stripe Add-on: by Scott Paterson – 1.5.4
Contact Form 7: by Takayuki Miyoshi – 5.0.1
PHP Compatibility Checker: by WP Engine – 1.4.5
tpay.com Woocommerce payment module: by tpay.com – 2.6.42 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #216 - /?page_id=216
Basket: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My account: #7 - /?page_id=7
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4 – 1.6 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by claudiosanches** [comment]
This happens probably because you are running it before WooCommerce starts. Without your full code, it's hard to understand when you are running it, still you should check for WooCommerce first, this method does not exists, try WooCommerce into `woocommerce_init` or `woocommerce_loaded`.

**Comment by piotrjozwiak** [comment]
I have to run this in `init_form_fields` to get available shipping methods. Please take a look here [getShippingMethods](https://github.com/tpay-com/tpay-woocommerce-2/blob/master/tpayWoocommerceGateway.php#L548) and here [init_form_fields](https://github.com/tpay-com/tpay-woocommerce-2/blob/master/tpayWoocommerceGateway.php#L168). Many thanks!
