### ISSUE TITLE
how to retrive cart details of a user? I am succesfully able to get the cart details of admin using cart REST api plugin but this does not seem to work for individual user. For eg:-If i logged in website as a user and i added some items in my cart ,how to retrieve those cart details using wp rest api queries>

### ISSUE THREAD

**Issue by KauhikNilay** [woocommerce/woocommerce#20713]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by seb86** [comment]
@KauhikNilay For support for the CART REST API don't ask WooCommerce as it is not official. Nothing to do with them. Also, if you are using any of there official libraries with it, it does not work as they all require a consumer key and consumer secret which will always access only the administrator's cart. At this time there is no way to view other customers carts with or without any official libraries.

**Comment by seb86** [comment]
cURL works fine.

**Comment by claudiulodro** [comment]
The WooCommerce API is designed for an administrator/developer to be able to do certain things programatically. It is not designed for building custom API-based stores. If you are trying to build a custom API-based store you will have to do all of the cart calculations, session handling, and order placement within the app and just use the API for storing the order details in WooCommerce.

We can't support custom code or third-party extensions like CART REST API on GitHub, so I recommend trying the support forums or one of the WP/WC developer slack communities if you have questions. Thanks.
