### ISSUE TITLE
Adding Woocommerce Teams to Membership Bundle

### ISSUE THREAD

**Issue by davidmabelle** [woocommerce/woocommerce#20715]
Please consider adding WooCommerce Teams to your membership bundle.

**Comment by claudiulodro** [comment]
Hi there,

We develop and maintain the core WooCommerce plugin on GitHub and our team does not really control which/how extensions are sold through WooCommerce.com. I'll pass along your request to the appropriate people, but in the future [opening a support ticket](https://woocommerce.com/my-account/create-a-ticket/) is the best way to get ahold of the right people regarding extension purchasing questions/requests.

Have a good day. Thanks.
