### ISSUE TITLE
wc_update_350_order_customer_id() uses "wp_tablename" instead of "$wpdb->tablename"

### ISSUE THREAD

**Issue by jorgeatorres** [woocommerce/woocommerce#20718]
**Describe the bug**
Now that #17895 has been merged, I noticed a couple of things while testing the 3.5.0 upgrade routine:

1. Some of the queries executed as part of the [`wc_update_350_order_customer_id()`](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L1851) function are using plain table names such as `wp_posts` and `wp_postmeta` instead of `$wpdb->posts` and `$wpdb->postmeta` respectively. This means that the routine doesn't work correctly on sites using a table prefix other than `wp_`. Some instances of this are: [1](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L1864), [2](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L1871), [3](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L1886), [4](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L1887).
2. According to the docblock, `wc_update_350_order_customer_id()`, when run from the admin, should receive a `WC_Background_Updater` instance as argument, but that doesn't seem to be the case, considering how `WC_Background_Updater` [calls the update callbacks](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-background-updater.php#L109). Am I missing something?

**To Reproduce**
1. Update to master (3.5.0) on a non-default prefix site. 
2. Run the update.

**Expected behavior**
The `post_author` column for all orders is correctly updated to the customer's ID.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://prospress.test
Site URL: http://prospress.test
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.0
PHP Version: 7.2.7
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
LibreSSL/2.0.20

SUHOSIN Installed: –
MySQL Version: 8.0.11
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.06MB
Database Data Size: 1.94MB
Database Index Size: 1.12MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.09MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.02MB + Index: 0.02MB
wp_postmeta: Data: 0.19MB + Index: 0.17MB
wp_posts: Data: 0.06MB + Index: 0.06MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 8
product_variation: 15
revision: 2
scheduled-action: 86
shop_order: 11
shop_subscription: 10

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Query Monitor: by John Blackbourn & contributors – 3.0.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.1 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.7 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions Gifting: by Prospress Inc. – 2.0.0 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.3.0-RC-2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.0-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscription Statuses: wc-active: 3
wc-on-hold: 7

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

other: wc-on-hold: 7
Stripe: wc-active: 3

### Payment Gateway Support ###

Direct bank transfer: products
PayPal Checkout: products
refunds
subscriptions
subscription_cancellation
subscription_reactivation
subscription_suspension
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin
subscription_amount_changes
subscription_date_changes

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

`
</details>

**Comment by kloon** [comment]
Thanks for testing and reporting, there's an open PR #20726 that fixes this.

**Comment by jorgeatorres** [comment]
@kloon: Thanks. The PR certainly would certainly fix the first part, but I'm still a bit confused about the second part. Do you know how the `$updater` argument is supposed to be received/used if the upgrader doesn't actually pass it to the update routine?

**Comment by kloon** [comment]
@jorgeatorres lets continue the discussion on the PR, it still needs to be reviewed so do please leave comments there for the author.
