### ISSUE TITLE
Return wrong customer_key and customer_secret after using woocommerce authentication url

### ISSUE THREAD

**Issue by waggyman** [woocommerce/woocommerce#20712]
### Detail
I've just tried to get customer_key and customer_secret using woocommerce authentication url that wrote in [this documentation](http://woocommerce.github.io/woocommerce-rest-api-docs/?php#rest-api-keys)

**To Reproduce**
I try to use `http_build_query` to make the url. It's also documented in the docs above. I'm using http in this case.

```php
<?php
$store_url = 'http://arigi.onlinestore.id';
$endpoint = '/wc-auth/v1/authorize';
$params = [
    'app_name' => 'My-App',
    'scope' => 'read_write',
    'user_id' => 123,
    'return_url' => 'https://example/redirect',
    'callback_url' => 'https://api.example/redirect'
];
$query_string = http_build_query( $params );

echo $store_url . $endpoint . '?' . $query_string;
?>
```

After that I got this response
![screen shot 2018-07-05 at 17 56 52](https://user-images.githubusercontent.com/20678935/42319670-e0d591da-807c-11e8-9088-19634feb5ffb.png)

But after I insert my username and password, after confirmation page, it give me this error.
![screen shot 2018-07-05 at 17 55 59](https://user-images.githubusercontent.com/20678935/42319784-3105f3d4-807d-11e8-85c3-027a4c197fdb.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
![screen shot 2018-07-05 at 18 01 49](https://user-images.githubusercontent.com/20678935/42319934-c0f5da86-807d-11e8-9cf9-a919de8a57a3.png)

**Comment by waggyman** [comment]
## Update [Now it's giving me Invalid signature]

I even test it using postman, I already use OAuth 1.0 and disable my ssl certificate verification.

#### Attachments:
**This is the response after I test it**

![screen shot 2018-07-06 at 18 27 42](https://user-images.githubusercontent.com/20678935/42376805-b4c54cce-814a-11e8-8186-34767820a306.png)


**This is the configuration**
![screen shot 2018-07-06 at 18 29 04](https://user-images.githubusercontent.com/20678935/42376806-b4ff41ea-814a-11e8-9e28-2876fd9ab839.png)

**Comment by kloon** [comment]
The error you posted indicates that the callback URL is returning an error when WooCommerce is posting the data to that URL. In order for the data to post successfully, it needs to be posted to a valid callback URL and that URL needs to return a 200 status code.

The callback URL is where you will handle saving the signature for future use in your API calls.
