### ISSUE TITLE
woocommerce_get_image_size_gallery_thumbnail - crop: 0 missing srcset

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#20717]
```
<ol class="flex-control-nav flex-control-thumbs">
	<li><img src="xxx.jpg" class="" draggable="false"></li>
	<li><img src="yyy.jpg" draggable="false"></li>
</ol>
```

has 100&times;100px thumbnails. When I do:

```
add_filter( 'woocommerce_get_image_size_gallery_thumbnail', function( $size ) {
	return array(
		'width' => 1000,
		'height' => 0,
		'crop' => 0,
	);
} );
```

then I'd expect `srcset` to be there but it's missing. I don't know if this qualifies as a bug or if it's intended. (I'm so far not finding any obstacle not to have `srcset` though.)

**Comment by claudiulodro** [comment]
Hi there,

[`wc_get_image_size`](https://github.com/woocommerce/woocommerce/blob/38e3e3f57062e1be09fa5ae1c375393bcf91180d/includes/wc-core-functions.php#L715) returns width, height, and cropping mode. The srcset is a per-image sort of thing based on the thumbnails that have been generated for an image, and can potentially vary for different images of the same size. `wp_get_attachment_image_srcset` may be helpful for you? Not sure what you're trying to do.

Hope this clears things up.
