### ISSUE TITLE
Status Page performance and security issues on multisite

### ISSUE THREAD

**Issue by dbmpls** [woocommerce/woocommerce#20724]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Setup a wordpress multisite network 
2. Navigate to a child site
3. View WooCommerce -> Status Page

## Expected/actual behavior

I was requested to write this up by WooCommerce help.

- The Status page loads up every single table in the multisite network. If the network is large ( over ~500 sites) The page load time can get very long. I am experiencing several minutes on my 1600 site network.
- This makes accessing items under the "Tools" and "Logs" tab very inconvenient
- Submitting support tickets to WooCommerce becomes difficult with the size of status report. There should be a summary option for multisite that only shows most important details.
- Also, single site admins really shouldn't be allowed to see tables for every single site in the network, or most of the details in the system status report either.  For my use case I would just block access to the "Status" page, but I like to allow access to the "Tools" tab. 
- In my opinion, it would be nice if system status and tools were separate menu items or that system status reports had their own permission settings.

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Wordpress Multisite 4.9.6
Status Report: ... that's kind of the point of my post, it's too big.
```
</details>

**Comment by kloon** [comment]
#20731
