### ISSUE TITLE
Woocommerce Variation for Bank Gateway Installments

### ISSUE THREAD

**Issue by arbitrage7** [woocommerce/woocommerce#20729]
Hello, apologize for my lack of knowledge in advance.

My [website](www.shop.asisnet.gr) is using Wordpress 4.9.7 along with WooCommerce 2.1.3
I made a setup with eurobank gateway as a virtual pos. This plugin [Eurobank WooCommerce Payment Gateway by enartia] supports installments which can be selected by the customer during checkout tab.

The above plugin separates the existing product price into "x" installments. ( ex. x=3 then 90euros/3 = 30euros per installment)

I am looking to setup these installments as a product variation so I could add an additional 2% per installment. So, during checkout the customer has already chose the installments value. ( ex. 100x0.02=102euros for 2 installments. etc. ). Discounting calculations seem vital as far as 1euro today values more than 1euro next month. This spread has to be included in product's price.

Unfortunately, I cannot come up with a solution for this setup.
Any guidance or thoughts would be highly appreciated.

Thank you for your time.

**Comment by kloon** [comment]
@arbitrage7 this platform is only for reporting bugs with WooCommerce core. For any support please use the appropriate forums, if you are a paying WooCommerce customer you can get support by contacting us https://woocommerce.com/contact-us/

Alternatively, I suggest you contact the developers of the payment gateway you are using and ask for assistance with that.

Thanks for understanding.
