### ISSUE TITLE
Fatal Error in the Basic Gateway with MercadoEnvíos

### ISSUE THREAD

**Issue by monpac** [woocommerce/woocommerce#20739]
**Describe the bug**
Fatal error when using MercadoEnvios as the utf8_ansi() function is called and it doesn't exist in the code.

**To Reproduce**
1. Do an order with MercadoEnvíos shipping
2. Wait for the system to notify the webpage the status of the shipping

**Screenshots**
Only ocurrs through notifications

**Expected behavior**
A function has to be created

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Any WordPres, Theme, Plugins, etc..

<details>
```
CRITICAL Uncaught Error: Call to undefined method WC_Woo_Mercado_Pago_Module::utf8_ansi() in /wp-content/plugins/cart-woocommerce/includes/WC_WooMercadoPago_BasicGateway.php:1484
```
</details>

**Comment by claudiulodro** [comment]
Hi there,

I recommend contacting the authors of the MercadoEnvios gateway about this issue if there isn't an update available to the gateway. We can only handle bugs with the core WooCommerce plugin here and not with third-party gateways or other plugins. I think [this is their GitHub repo](https://github.com/mercadopago/cart-woocommerce) where you can let them know.

Thanks.
