### ISSUE TITLE
No cache-control, and the request takes too long to respond

### ISSUE THREAD

**Issue by dovahkiin98** [woocommerce/woocommerce#20745]
While using REST API for WooCommerce, the response has no cache-control header, and the request takes about 5 seconds to return a single item or a list of 10 items.

Is there a way to enable cache-control header?
And how can we make the response quicker?

**Comment by claudiosanches** [comment]
WooCommerce REST API is built on top of WordPress REST API, you can optimize the same way as you can do on WordPress REST API. So not an specific issue on WooCommerce.
I never tried to do something like that, but if I find something about it I'll post back here, but probably better try the WordPress support forum.
