### ISSUE TITLE
WooCommerce checkout page and WooCommerce settings page hang when accessed.

### ISSUE THREAD

**Issue by Burhan6220** [woocommerce/woocommerce#20741]
**WooCommerce checkout page and WooCommerce settings page take almost 5 mins to load**

**To Reproduce**
1. Go to 'https://kashmirtag.com'
2. Add any item to cart and click on Checkout''
3. It takes a long time to load and hangs the whole website
4. The same thing happens when I try to access woocommerce settings from dashboard. 
5. It also results in 503 Service unavailable error although server resources are fine.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://kashmirtag.com
Site URL: https://kashmirtag.com
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.33 (cPanel) OpenSSL/1.0.2o mod_bwlimited/1.4 Phusion_Passenger/5.1.12
PHP Version: ❌ 7.0.30 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 512 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.53 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.0
WC Database Prefix: wpul_
MaxMind GeoIP Database: ✔
Total Database Size: 11.92MB
Database Data Size: 9.95MB
Database Index Size: 1.97MB
wpul_woocommerce_sessions: Data: 0.06MB + Index: 0.01MB
wpul_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpul_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpul_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpul_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpul_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB
wpul_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpul_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpul_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpul_woocommerce_shipping_zone_locations: Data: 0.88MB + Index: 0.92MB
wpul_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpul_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpul_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpul_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpul_check_pincode_p: Data: 0.00MB + Index: 0.00MB
wpul_commentmeta: Data: 0.00MB + Index: 0.00MB
wpul_comments: Data: 0.00MB + Index: 0.01MB
wpul_cscs_db_subscriptions: Data: 0.00MB + Index: 0.00MB
wpul_failed_jobs: Data: 0.00MB + Index: 0.00MB
wpul_itsec_distributed_storage: Data: 0.22MB + Index: 0.00MB
wpul_itsec_lockouts: Data: 0.00MB + Index: 0.00MB
wpul_itsec_logs: Data: 0.00MB + Index: 0.01MB
wpul_itsec_temp: Data: 0.00MB + Index: 0.00MB
wpul_links: Data: 0.00MB + Index: 0.00MB
wpul_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
wpul_options: Data: 1.18MB + Index: 0.07MB
wpul_pincode_setting_p: Data: 0.00MB + Index: 0.00MB
wpul_postmeta: Data: 1.53MB + Index: 0.15MB
wpul_posts: Data: 1.40MB + Index: 0.07MB
wpul_queue: Data: 0.00MB + Index: 0.00MB
wpul_revslider_css: Data: 0.09MB + Index: 0.00MB
wpul_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wpul_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wpul_revslider_sliders: Data: 0.08MB + Index: 0.00MB
wpul_revslider_slides: Data: 0.52MB + Index: 0.00MB
wpul_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wpul_smush_dir_images: Data: 0.00MB + Index: 0.00MB
wpul_sw_couriers: Data: 0.00MB + Index: 0.00MB
wpul_termmeta: Data: 0.00MB + Index: 0.01MB
wpul_terms: Data: 0.00MB + Index: 0.01MB
wpul_term_relationships: Data: 0.00MB + Index: 0.01MB
wpul_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wpul_usermeta: Data: 0.03MB + Index: 0.02MB
wpul_users: Data: 0.00MB + Index: 0.01MB
wpul_wc_delivery_codes: Data: 0.00MB + Index: 0.00MB
wpul_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpul_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpul_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wpul_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
wpul_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB
wpul_wfBlocks7: Data: 0.00MB + Index: 0.00MB
wpul_wfConfig: Data: 0.36MB + Index: 0.01MB
wpul_wfCrawlers: Data: 0.00MB + Index: 0.00MB
wpul_wfFileChanges: Data: 0.00MB + Index: 0.00MB
wpul_wfFileMods: Data: 1.94MB + Index: 0.30MB
wpul_wfHits: Data: 0.49MB + Index: 0.11MB
wpul_wfHoover: Data: 0.00MB + Index: 0.00MB
wpul_wfIssues: Data: 0.01MB + Index: 0.01MB
wpul_wfKnownFileList: Data: 0.98MB + Index: 0.13MB
wpul_wfLeechers: Data: 0.01MB + Index: 0.01MB
wpul_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB
wpul_wfLocs: Data: 0.00MB + Index: 0.00MB
wpul_wfLogins: Data: 0.02MB + Index: 0.01MB
wpul_wfNet404s: Data: 0.00MB + Index: 0.00MB
wpul_wfNotifications: Data: 0.00MB + Index: 0.00MB
wpul_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
wpul_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wpul_wfScanners: Data: 0.00MB + Index: 0.00MB
wpul_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
wpul_wfStatus: Data: 0.12MB + Index: 0.05MB
wpul_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wpul_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wpul_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
wpul_yoast_seo_links: Data: 0.03MB + Index: 0.01MB
wpul_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB
wpul_zip_css_validation: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 363
customize_changeset: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mc4wp-form: 1
nav_menu_item: 30
page: 29
post: 7
product: 33
product_variation: 2
revision: 220
shop_order: 4
tbay_brand: 8
tbay_footer: 1
tbay_megamenu: 1
tbay_testimonial: 5
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (33) ###

WP Hide & Security Enhancer: by Nsp Code – 1.5.1.2
Adminimize: by Frank Bültge – 1.11.4
Chatra live chat software: by Chatra – 1.0.2
CMB2: by CMB2 team – 2.4.2
Contact Form 7: by Takayuki Miyoshi – 5.0.2
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.7
MailChimp for WordPress: by ibericode – 4.2.3
Monarch Plugin: by Elegant Themes – 1.3.24
Nav Menu Roles: by Kathy Darling – 1.9.2
Personal Admin Footer: by Shea Bunge – 1.2.0
reSmush.it Image Optimizer: by reSmush.it – 0.1.15
Slider Revolution: by ThemePunch – 5.4.7.1
Shiprocket: by Shiprocket – 1.0.0
WooCommerce Shipway Courier Tracking & notify: by Onjection – 2.0 – Not tested with the active version of WooCommerce
SSL Insecure Content Fixer: by WebAware – 2.7.0
Tbay Framework: by Team TbayTheme – 2.0.2
User Role Editor: by Vladimir Garagulya – 4.43
User Switching: by John Blackbourn & contributors – 1.3.1
WooCommerce Variation Swatches: by ThemeAlien – 1.0.3 – Not tested with the active version of WooCommerce
W3 Total Cache: by Frederick Townes – 0.9.7
WooCommerce - Social Login: by WPWeb – 1.6.6 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.1
WooCommerce Plugin for PayUmoney: by payumoney.com – 1.6.0 – 1.8.2 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.0 – 3.4.3 is available
WooSidebars: by WooCommerce – 1.4.5
Wordfence Security: by Wordfence – 7.1.8
Yoast SEO: by Team Yoast – 7.7.3
WP-DBManager: by Lester 'GaMerZ' Chan – 2.79.1
WP File Manager: by mndpsingh287 – 2.8
Smush: by WPMU DEV – 2.7.9.1
YITH WooCommerce Compare: by YITHEMES – 2.3.1
YITH WooCommerce Quick View: by YITHEMES – 1.3.1
YITH WooCommerce Wishlist: by YITHEMES – 2.2.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (Rs.)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #1662 - /terms-of-service/

### Theme ###

Name: GreenMart
Version: 2.1.2
Author URL: https://thembay.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: greenmart/woocommerce/cart/cart.php
greenmart/woocommerce/cart/cross-sells.php
greenmart/woocommerce/checkout/form-checkout.php
greenmart/woocommerce/content-product.php
greenmart/woocommerce/content-product_cat.php
greenmart/woocommerce/content-single-product.php
greenmart/woocommerce/global/breadcrumb.php
greenmart/woocommerce/global/quantity-input.php
greenmart/woocommerce/loop/add-to-cart.php
greenmart/woocommerce/loop/loop-end.php
greenmart/woocommerce/loop/loop-start.php
greenmart/woocommerce/loop/orderby.php
greenmart/woocommerce/loop/pagination.php
greenmart/woocommerce/loop/rating.php
greenmart/woocommerce/myaccount/form-login.php
greenmart/woocommerce/myaccount/form-lost-password.php
greenmart/woocommerce/myaccount/my-address.php
greenmart/woocommerce/myaccount/my-orders.php
greenmart/woocommerce/single-product/product-image.php
greenmart/woocommerce/single-product/product-thumbnails.php
greenmart/woocommerce/single-product/rating.php
greenmart/woocommerce/single-product/related.php
greenmart/woocommerce/single-product/review.php
greenmart/woocommerce/single-product/tabs/additional-information.php
greenmart/woocommerce/single-product/tabs/description.php
greenmart/woocommerce/single-product/tabs/tabs.php
greenmart/woocommerce/single-product/up-sells.php
greenmart/woocommerce/single-product-reviews.php

`
</details>

**Comment by claudiosanches** [comment]
Sounds like a problem related to your installation or server, you said that deactivated all plugins, but I can't reproduce this behavior in localhost or in my dev environments, this does not sound a like a bug on WooCommerce.

**Comment by Burhan6220** [comment]
Hi there,
Thanks for responding. I managed to clear the payment error by emptying the
WooCommerce tables on my database. I guess database was corrupted.
Thanks.

**Comment by romantico** [comment]
This is a good plugin you must try for your WooCommerce checkout page.
https://codecanyon.net/item/wooloader/22355988.
