### ISSUE TITLE
Message not showing for invalid variation attributes selected

### ISSUE THREAD

**Issue by saulfautley** [woocommerce/woocommerce#20752]
When selecting a combination of attributes on a variable product on the frontend that does not match a variation, there is meant to be a message that is displayed:

> Sorry, no products matched your selection. Please choose a different combination.

As far as I can tell it's not showing due to `VariationForm.loading` not being set to `false` correctly on line 45:

https://github.com/woocommerce/woocommerce/blob/1ef4aa10a09f3167cee802495c704c3d96b87713/assets/js/frontend/add-to-cart-variation.js#L42-L46

It should be setting the `loading` property of `VariationForm`, not of `$form`. Because of this the `.wc-no-matching-variations` element is not being inserted/displayed.

https://github.com/woocommerce/woocommerce/blob/1ef4aa10a09f3167cee802495c704c3d96b87713/assets/js/frontend/add-to-cart-variation.js#L152-L155

https://github.com/woocommerce/woocommerce/blob/1ef4aa10a09f3167cee802495c704c3d96b87713/assets/js/frontend/add-to-cart-variation.js#L174-L177

**Comment by claudiosanches** [comment]
Thanks for your contribution, closing in favor of https://github.com/woocommerce/woocommerce/pull/20762
