### ISSUE TITLE
Webhook is not triggered when 

### ISSUE THREAD

**Issue by luisfmelo** [woocommerce/woocommerce#20765]
**Describe the bug**
When some client pays with stripe, I only receive the webhook of order created (status=pending) and I don't receive webhook of order paid (status=processing)

**To Reproduce**
When someone pays with stripe, the webhook is not triggered.

**Screenshots**
NA

**Expected behavior**
When one client pays, either with stripe or other payment service, the system should send a webhook of order/updated.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Wordpress Version 4.9.6
Woocommerce Version 3.3.2

Server environment
--
Server info: |   | Apache
PHP version: |   | 5.6.36
PHP post max size: |   | 64 MB
PHP time limit: |   | 50000
PHP max input vars: |   | 5000
cURL version: |   | 7.38.0, OpenSSL/1.0.1t

**Comment by claudiulodro** [comment]
Hi there,

I would [open an issue on the repo for the Stripe plugin](https://github.com/woocommerce/woocommerce-gateway-stripe). It's not part of the WooCommerce core plugin so we can't troubleshoot it here. As long as [either of these actions are triggered when the order is paid](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-webhook.php#L859) the webhook should fire.

Thanks.
