### ISSUE TITLE
tax issue in check out page

### ISSUE THREAD

**Issue by nehakhedkar** [woocommerce/woocommerce#20764]
![tax](https://user-images.githubusercontent.com/41154830/42634001-b09d13e8-85ff-11e8-9303-b8a9eb36ac09.PNG)

Please find the below link of website
http://aquarrow.com/shoeworld
on checkout page we are implemented tax on products but we only want to show tax dont want to add in grand total please refer image  i.e we want grand total is 4690 only includes all tax

**Comment by peterfabian** [comment]
Hi, 

sorry, but GitHub is a platform to report bugs in WooCommerce, not a support forum. Please [contact support](https://woocommerce.com/contact-us/) or [user forum](https://wordpress.org/support/plugin/woocommerce).

You might be able to utilize WooCommerce > Settings > Tax options below:
![tax-settings](https://user-images.githubusercontent.com/2207451/42640048-b3ac36d0-85f1-11e8-8984-2be3be46c571.png)

Thanks.
