### ISSUE TITLE
Mail not working woocommerce

### ISSUE THREAD

**Issue by JoaoMartinsPT** [woocommerce/woocommerce#20761]
The mail function is not working.
installing the WP Mail Log the message that appears "could not instantiate mail function"
Any idea what is happening?

This bug happens with a Ocean WP theme 

Home URL: https://acucarqb.pt
Site URL: https://acucarqb.pt
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_PT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.30 - Recomendamos que utilize PHP 7.2 ou superior para melhor performance e segurança. Como actualizar a sua versão PHP
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.1.34-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ O seu servidor não tem a classe SoapClient activada - alguns serviços de pagamento que utilizem SOAP podem não funcionar como esperado.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wpse_
MaxMind GeoIP Database: ✔
Tamanho total da base de dados: 17.81MB
Tamanho dos dados da base de dados: 16.81MB
Tamanho do índice da base de dados: 1.00MB
wpse_woocommerce_sessions: Dados: 12.60MB + Índice: 0.26MB
wpse_woocommerce_api_keys: Dados: 0.00MB + Índice: 0.00MB
wpse_woocommerce_attribute_taxonomies: Dados: 0.00MB + Índice: 0.00MB
wpse_woocommerce_downloadable_product_permissions: Dados: 0.00MB + Índice: 0.00MB
wpse_woocommerce_order_items: Dados: 0.01MB + Índice: 0.01MB
wpse_woocommerce_order_itemmeta: Dados: 0.07MB + Índice: 0.05MB
wpse_woocommerce_tax_rates: Dados: 0.00MB + Índice: 0.01MB
wpse_woocommerce_tax_rate_locations: Dados: 0.00MB + Índice: 0.00MB
wpse_woocommerce_shipping_zones: Dados: 0.00MB + Índice: 0.00MB
wpse_woocommerce_shipping_zone_locations: Dados: 0.00MB + Índice: 0.00MB
wpse_woocommerce_shipping_zone_methods: Dados: 0.00MB + Índice: 0.00MB
wpse_woocommerce_payment_tokens: Dados: 0.00MB + Índice: 0.00MB
wpse_woocommerce_payment_tokenmeta: Dados: 0.00MB + Índice: 0.00MB
wpse_woocommerce_log: Dados: 0.00MB + Índice: 0.00MB
moloni_api: Dados: 0.00MB + Índice: 0.00MB
moloni_api_config: Dados: 0.00MB + Índice: 0.00MB
wpse_adtribes_my_conversions: Dados: 0.00MB + Índice: 0.00MB
wpse_commentmeta: Dados: 0.00MB + Índice: 0.00MB
wpse_comments: Dados: 0.01MB + Índice: 0.01MB
wpse_easypay_notifications: Dados: 0.00MB + Índice: 0.00MB
wpse_easypay_transaction_keys: Dados: 0.00MB + Índice: 0.00MB
wpse_links: Dados: 0.00MB + Índice: 0.00MB
wpse_lrgawidget_global_settings: Dados: 0.00MB + Índice: 0.00MB
wpse_mobileassistant_accounts: Dados: 0.00MB + Índice: 0.00MB
wpse_mobileassistant_devices: Dados: 0.00MB + Índice: 0.00MB
wpse_mobileassistant_failed_login: Dados: 0.00MB + Índice: 0.00MB
wpse_mobileassistant_push_settings: Dados: 0.00MB + Índice: 0.00MB
wpse_mobileassistant_session_keys: Dados: 0.00MB + Índice: 0.00MB
wpse_mobileassistant_users: Dados: 0.00MB + Índice: 0.00MB
wpse_options: Dados: 1.25MB + Índice: 0.06MB
wpse_postmeta: Dados: 2.24MB + Índice: 0.41MB
wpse_posts: Dados: 0.51MB + Índice: 0.09MB
wpse_sg_action: Dados: 0.01MB + Índice: 0.00MB
wpse_sg_config: Dados: 0.00MB + Índice: 0.00MB
wpse_termmeta: Dados: 0.00MB + Índice: 0.01MB
wpse_terms: Dados: 0.00MB + Índice: 0.01MB
wpse_term_relationships: Dados: 0.01MB + Índice: 0.02MB
wpse_term_taxonomy: Dados: 0.00MB + Índice: 0.00MB
wpse_usermeta: Dados: 0.06MB + Índice: 0.04MB
wpse_users: Dados: 0.00MB + Índice: 0.01MB
wpse_wc_download_log: Dados: 0.00MB + Índice: 0.00MB
wpse_wc_webhooks: Dados: 0.00MB + Índice: 0.00MB
wpse_wpml_mails: Dados: 0.03MB + Índice: 0.00MB
wpse_yoast_seo_links: Dados: 0.01MB + Índice: 0.00MB
wpse_yoast_seo_meta: Dados: 0.00MB + Índice: 0.01MB

### Post Type Counts ###

attachment: 250
customize_changeset: 7
elementor_library: 6
feedback: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 5
page: 11
post: 3
product: 128
product-feed: 1
revision: 206
shop_order: 33

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

All-in-One WP Migration: por ServMask – 6.71
Autoptimize: por Frank Goossens (futtta) – 2.3.4
Backup: por BackupGuard – 1.1.65
Best Products Feed for WooCoommerce: por RexTheme – 1.2.7 – Não testado com a versão activa do WooCommerce
Elementor Pro: por Elementor.com – 2.0.15
Elementor: por Elementor.com – 2.1.2
Enhanced E-commerce for Woocommerce store: por Tatvic – 2.0.3 – Não testado com a versão activa do WooCommerce
Facebook for WooCommerce: por Facebook – 1.9.2 – Não testado com a versão activa do WooCommerce
Insert Headers and Footers: por WPBeginner – 1.4.3
Google Analytics: por Amr M. Ibrahim – 2.0.2
Mobile Assistant Connector: por eMagicOne – 1.4.7
Moloni: por Nuno – 1.5
myStickymenu: por m.r.d.a – 2.0.5
Ni WooCommerce Sales Report: por anzia – 3.2 – Não testado com a versão activa do WooCommerce
NIF (Num. de Contribuinte Português) para WooCommerce: por Webdados – 4.1 – Não testado com a versão activa do WooCommerce
Ocean Extra: por OceanWP – 1.4.18
Facebook Pixel: por Facebook – 1.7.8
Product Sales Report for WooCommerce: por Potent Plugins – 1.4.8 – Não testado com a versão activa do WooCommerce
WC Custom Add to Cart labels: por Rynaldo Stoltz – 1.1
WooCommerce Weight Based Shipping: por weightbasedshipping.com – 5.2.1 – Não testado com a versão activa do WooCommerce
WooCommerce Easypay Gateway Multi Banco: por Easypay – 1.00 - Beta – Não testado com a versão activa do WooCommerce
WooCommerce: por Automattic – 3.4.3
Yoast SEO: por Team Yoast – 7.8
WP Mail Logging: por Christian Zöller – 1.8.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Página da Loja: #4 - /loja/
Carrinho: #5 - /carrinho/
Finalizar compras: #6 - /finalizar-compra/
Minha conta: #7 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: OceanWP
Version: 1.5.20
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – Se estiver a modificar o tema do WooCommerce ou um tema principal que não construiu pessoalmente
recomendamos o uso de um tema dependente. Veja: Como criar um tema dependente

WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

`

**Comment by claudiosanches** [comment]
There is missing steps to reproduce this issue, also with this happens only with a specific theme so it ins't an issue with WooCommerce, probably in the theme.
Probably better test with an clean install without any custom theme and any other plugin, only WooCommerce and WP Mail Log installed with a default theme, so you can check it.
