### ISSUE TITLE
WooCommerce is adding someone else's cart item to cart

### ISSUE THREAD

**Issue by majdagithub** [woocommerce/woocommerce#20763]
Hi, we are using WooCommerce 3.3.3 version. Our client reported a bug to us: She told us that, after adding an item to cart, another item was added at the same time, with different name from Gravity Form on product page (we are using Gravity Forms Product Add-On as well). It seams like someone else's item was added to her cart.

We also found this related issue, reported a while ago: 
https://github.com/woocommerce/woocommerce/issues/15671

Please help ASAP, we are losing customers because of this issue.

Here is our System Status:

### WordPress Environment ###

Home URL: https://souldust.com
Site URL: https://souldust.com
WC Version: 3.3.3
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.36-1+wpengine13
PHP Post Max Size: 200 MB
PHP Time Limit: 3600
PHP Max Input Vars: 3000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.40
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 60.30MB
Database Data Size: 39.18MB
Database Index Size: 21.12MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.04MB
wp_woocommerce_order_itemmeta: Data: 2.42MB + Index: 0.75MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.00MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.00MB + Index: 0.00MB
wp_bwg_album: Data: 0.02MB + Index: 0.00MB
wp_bwg_album_gallery: Data: 0.02MB + Index: 0.00MB
wp_bwg_gallery: Data: 0.02MB + Index: 0.00MB
wp_bwg_image: Data: 1.28MB + Index: 0.00MB
wp_bwg_image_comment: Data: 0.02MB + Index: 0.00MB
wp_bwg_image_rate: Data: 0.02MB + Index: 0.00MB
wp_bwg_image_tag: Data: 0.02MB + Index: 0.00MB
wp_bwg_shortcode: Data: 0.09MB + Index: 0.00MB
wp_bwg_theme: Data: 0.08MB + Index: 0.00MB
wp_commentmeta: Data: 0.05MB + Index: 0.03MB
wp_comments: Data: 1.52MB + Index: 0.81MB
wp_elfsight_instagram_feed_widgets: Data: 0.00MB + Index: 0.00MB
wp_gf_addon_feed: Data: 0.33MB + Index: 0.00MB
wp_gravityflow_activity_log: Data: 0.13MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_ok7s1dqsss_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_ok7s1dqsss_comments: Data: 0.02MB + Index: 0.08MB
wp_ok7s1dqsss_links: Data: 0.02MB + Index: 0.02MB
wp_ok7s1dqsss_options: Data: 0.02MB + Index: 0.03MB
wp_ok7s1dqsss_postmeta: Data: 0.02MB + Index: 0.03MB
wp_ok7s1dqsss_posts: Data: 0.02MB + Index: 0.06MB
wp_ok7s1dqsss_terms: Data: 0.02MB + Index: 0.03MB
wp_ok7s1dqsss_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_ok7s1dqsss_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_ok7s1dqsss_usermeta: Data: 0.02MB + Index: 0.03MB
wp_ok7s1dqsss_users: Data: 0.02MB + Index: 0.03MB
wp_options: Data: 4.48MB + Index: 0.41MB
wp_postmeta: Data: 16.48MB + Index: 10.91MB
wp_posts: Data: 2.50MB + Index: 0.58MB
wp_redirection_404: Data: 0.06MB + Index: 0.06MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_rg_form: Data: 0.00MB + Index: 0.00MB
wp_rg_form_meta: Data: 1.09MB + Index: 0.00MB
wp_rg_form_view: Data: 3.52MB + Index: 3.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.00MB
wp_rg_lead: Data: 0.42MB + Index: 0.11MB
wp_rg_lead_detail: Data: 1.52MB + Index: 2.53MB
wp_rg_lead_detail_long: Data: 0.03MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.32MB + Index: 0.19MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.01MB
wp_rg_zapier: Data: 0.02MB + Index: 0.02MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.02MB + Index: 0.04MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 1.50MB + Index: 0.52MB
wp_users: Data: 0.06MB + Index: 0.05MB
wp_vtprd_lifetime_limits_purchaser: Data: 0.02MB + Index: 0.02MB
wp_vtprd_lifetime_limits_purchaser_logid_rule: Data: 0.02MB + Index: 0.02MB
wp_vtprd_lifetime_limits_purchaser_rule: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
wp_wc_deposits_payment_plans: Data: 0.00MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wdpr_payment_recipes: Data: 0.02MB + Index: 0.00MB
wp_wdpr_payment_recipes_schedule: Data: 0.02MB + Index: 0.00MB
wp_wdpr_payment_rules: Data: 0.02MB + Index: 0.00MB
wp_woochimp_scheduled_events: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_termmeta: Data: 0.00MB + Index: 0.01MB
wp_wpp_deposit_records: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.09MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.11MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 244
acf-field-group: 17
amn_smtp: 2
attachment: 878
bwg_album: 1
bwg_gallery: 6
custom_css: 1
event_forms: 1
event_organizer: 7
event_venue: 8
jetpack_migration: 2
ml-slider: 6
nav_menu_item: 31
page: 59
payment_retry: 55
paypal_ipn: 97
post: 53
product: 53
product_variation: 339
revision: 24
sa_slider: 6
safecss: 1
scheduled-action: 134
shop_coupon: 12
shop_order: 749
shop_order_refund: 29
shop_subscription: 163
testimonials: 23
vtprd-rule: 1
wc_zapier_feed: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (46) ###

Gravity Forms: by rocketgenius – 2.2.6
ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 2.0.1

Advanced Custom Fields PRO: by Elliot Condon – 5.6.9
Akismet Anti-Spam: by Automattic – 4.0.3
Column Shortcodes: by Codepress – 1.0
Elfsight Instagram Feed CC: by Elfsight – 3.5.0
Gravity Forms - Placeholders add-on: by Joan Piedra – 1.2.1
Gravity Flow: by Gravity Flow – 2.2.1
Gravity Forms MailChimp Add-On: by rocketgenius – 4.2
Gravity Forms Survey Add-On: by Rocketgenius – 3.2
Sharing buttons shortcode for Jetpack: by Jeremy Herve – 1.2.2
Jetpack by WordPress.com: by Automattic – 5.9
Mobile Menu: by Takanakui – 2.5.1
PayPal for WooCommerce: by Angell EYE – 1.4.7.4
PayPal IPN for WordPress: by Angell EYE – 1.1.2
Photo Gallery: by Photo Gallery Team – 1.3.69
PHP Code Widget: by Otto – 2.3
PixelYourSite: by PixelYourSite – 5.2.1
VarkTech Pricing Deals for WooCommerce: by Vark – 1.1.8.2
VarkTech Pricing Deals PRO for WooCommerce: by VarkTech – 1.1.8.1 – Not tested with the active version of WooCommerce
Search Everything: by Sovrn
zemanta – 8.1.9

Shortcode Toggle: by Arefly – 1.0.9
Sitelinks Search Box: by Apasionados.es – 1.3
Slide Anything PRO - Modal Popups for Slide Anything: by Simon Edge – 2.0
Slide Anything - Responsive Content / HTML Slider and Carousel: by Simon Edge – 2.1.3
Theme Editor: by mndpsingh287 – 1.5
Tracking Code Manager: by IntellyWP – 1.11.6 – Not tested with the active version of WooCommerce
Cookie Consent: by Catapult_Themes – 2.3.10
Widget CSS Classes: by C.M. Kendrick – 1.5.2.1
WooChimp: by RightPress – 2.2.4 – Not tested with the active version of WooCommerce
WooCommerce Advanced Notifications: by WooCommerce – 1.2.13 – 1.2.14 is available
WooCommerce Colors: by WooThemes – 1.0.7 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.0.7
WooCommerce - Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.0 – 3.3.3 is available – Not tested with the active version of WooCommerce
WooCommerce Improved External Products: by Jeremiah Prummer – 1.4.1 – Not tested with the active version of WooCommerce
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.6.1 – Not tested with the active version of WooCommerce

WooCommerce Product Details Customiser: by jameskoster – 0.2.0 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.2.18 – 2.3.2 is available
WooCommerce: by Automattic – 3.3.3 – 3.4.3 is available
Yoast SEO: by Team Yoast – 7.1
WP Log Viewer: by Maxwell Berkel – 1.2.1
WP Mail SMTP: by WPForms – 1.2.5
WP Rocket: by WP Media – 3.0.5.1
WP Rollback: by WordImpress – 1.5
WP Smush: by WPMU DEV – 2.7.8
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.5.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #248 - /offerings/
Cart: #1751 - /cart/
Checkout: #1752 - /checkout/
My account: #1753 - /my-account/
Terms and conditions: #1933 - /terms-of-use/

### Theme ###

Name: Technicolor Living
Version: 1.0.0
Author URL: http://tinyblueorange.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: technicolor-living/archive-product.php
technicolor-living/woocommerce/cart/cart-totals.php
technicolor-living/woocommerce/checkout/form-billing.php
technicolor-living/woocommerce/checkout/form-checkout.php
technicolor-living/woocommerce/checkout/form-shipping.php
technicolor-living/woocommerce/checkout/payment-method.php
technicolor-living/woocommerce/checkout/review-order.php
technicolor-living/woocommerce/checkout/thankyou.php
technicolor-living/woocommerce/content-single-product.php
technicolor-living/woocommerce/emails/customer-invoice.php
technicolor-living/woocommerce/emails/email-styles.php
technicolor-living/woocommerce/myaccount/orders.php
technicolor-living/woocommerce/single-product/add-to-cart/variable.php
technicolor-living/woocommerce/single-product/add-to-cart/variation.php
technicolor-living/woocommerce/single-product.php

### subscriptions ###

WCS_DEBUG: ✔
						No
Subscriptions Mode: ✔
						Live
Subscriptions Template Theme Overrides: technicolor-living/woocommerce/myaccount/my-subscriptions.php technicolor-living/woocommerce/myaccount/related-orders.php technicolor-living/woocommerce/myaccount/related-subscriptions.php technicolor-living/woocommerce/myaccount/subscriptions.php technicolor-living/woocommerce/myaccount/view-subscription.php
Report Cache Enabled: ✔
						Yes
Cache Update Failures: ✔
						0 failure
`

**Comment by claudiosanches** [comment]
> with different name from Gravity Form on product page (we are using Gravity Forms Product Add-On as well). It seams like someone else's item was added to her cart.

I'm not able to reproduce this following your steps, even more that the issues looks like caused by a an extension. Better contact the Gravity Form contact.
