### ISSUE TITLE
REST API: Products reports endpoint

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#20775]
Schema:

- https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_products
- https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_products_stats

**Comment by claudiulodro** [comment]
I'm starting with `/wc/v3/reports/products` and `/wc/v3/reports/products/<id>`

**Comment by claudiulodro** [comment]
#20956
