### ISSUE TITLE
get_on_sale_products() query bugs 

### ISSUE THREAD

**Issue by wongkediri** [woocommerce/woocommerce#20788]
Onsale shortcode show future on sale products, sale start date is on future.

after checking woocommerce use wc_get_product_ids_on_sale(),
going deeper i see function get_on_sale_products() part of WC_Product_Data_Store_CPT

here the function link:
https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L862-874

**To Reproduce**
1. run this Query, i m adding  saleprice and price in result

`SELECT post.ID as id, post.post_parent as parent_id, meta.meta_value as sale,meta2.meta_value as price  FROM `wp_posts` AS post
                LEFT JOIN `wp_postmeta` AS meta ON post.ID = meta.post_id
                LEFT JOIN `wp_postmeta` AS meta2 ON post.ID = meta2.post_id
                WHERE post.post_type IN ( 'product', 'product_variation' )
                    AND post.post_status = 'publish'
                    AND meta.meta_key = '_sale_price'
                    AND meta2.meta_key = '_price'
                    AND CAST( meta.meta_value AS DECIMAL ) >= 0
                    AND CAST( meta.meta_value AS CHAR ) != ''
                    AND CAST( meta.meta_value AS DECIMAL( 10, 2 ) ) = CAST( meta2.meta_value AS DECIMAL( 10, 2 ) )
                GROUP BY post.ID`

2. you can see the result is sale price and sale are not equal and still show

**Screenshots**
![onsalebugs](https://user-images.githubusercontent.com/40045482/42677371-bc20bd86-86a5-11e8-9f26-58f63d7a4589.png)

**Expected behavior**
it should be show only equal value  between _sale_price and _price
see id : 27413 & 34918

**WordPress Environment**
<details>
```
`
### WordPress Environment ###


WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔

### Server Environment ###

Server Info: Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/5.6.30
PHP Version: ❌ 5.6.30 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.51.0
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.5 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
`

```
</details>

**Comment by kloon** [comment]
@wongkediri I am unable to replicate it. How was these product updated to set the prices?

How it works is there's a functionality that runs that will update the price field based on the dates, and only when the price field matches the sale_price field will it show as on sale, which only happens when the products go on sale.

I am seeing $ signs in your data which it should not have, so that might be the issue for you, not sure what is adding that as WooCommerce core does not allow you to enter non-numeric values as prices.

I suggest you investigate how those currency signs got into your database and take it from there. Not replicable via the standard functionality.

**Comment by wongkediri** [comment]
@kloon arrr you right, yes im using bulk import. Now it was fine, but just another problem that sale start and end not using wordpress local timezone
