### ISSUE TITLE
Adding Images to products ends with Http error

### ISSUE THREAD

**Issue by TolerH** [woocommerce/woocommerce#20785]
I'm adding products to a clients store and every time I go to add more I get an http error and no picture displayed. When I back into the media area I'll see the blank photos but nothing useable.
<img width="1126" alt="screen shot 2018-07-12 at 7 51 17 pm" src="https://user-images.githubusercontent.com/41172822/42665314-197644d6-860d-11e8-9210-ba8ad315299d.png">
<img width="1507" alt="screen shot 2018-07-12 at 7 51 52 pm" src="https://user-images.githubusercontent.com/41172822/42665315-198818a0-860d-11e8-93ce-a09a63a293f8.png">
<img width="722" alt="screen shot 2018-07-12 at 7 52 00 pm" src="https://user-images.githubusercontent.com/41172822/42665316-199a7608-860d-11e8-99ce-c2708b3d4d90.png">

**Comment by claudiosanches** [comment]
There is a lot of information missing on this issue report, there not even even details of your installation... 
Still it's WordPress that handles all media upload, so this does not sound like an issue on WooCommerce, maybe a plugin causing it, or even some error on your server, maybe missing some image library used by WordPress.
My advice is you try to disable all the plugins and let only WooCommerce installed, then start debugging this with your server's access and error logs.
