### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by kurniaarifin27** [woocommerce/woocommerce#20786]
its possible to show all product without pagination? i used woocommerce api v2

**Comment by peterfabian** [comment]
Hi, 

if you are using the [current v2 API](http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products), then there is a parameter called `per_page`, e.g.
`https://local.wordpress.test/wp-json/wc/v2/products/?per_page=20`, but there is no way to return all, irrespective of the number.

If you're using the legacy v2 API, then I'm afraid there is no way.

Also, please note that GitHub is a platform to report bugs, not to get support for WooCommerce. If you need support, please contact appropriate channels: 
- WooCommerce contact us page: https://woocommerce.com/contact-us/
- WooCommerce user support forum: https://wordpress.org/support/plugin/woocommerce
