### ISSUE TITLE
Shipping does not calculate when specific post code entered which are defined in shipping zone.

### ISSUE THREAD

**Issue by UmeedEmad** [woocommerce/woocommerce#20796]
Hi,

I am facing a strange issue with shipping zones and because of that orders are missing the shipping cost. I have created several shipping zones with different rates and inserted postcode codes. Here is the options for one of the zones.
`DG*
EH15
EH16
EH17
EH18
EH19
EH20
EH21
EH22
EH23
EH24
EH25
EH26
EH31
EH32
EH33
EH34
EH35
EH36
EH37
EH38
EH39
EH40
EH41
EH42
EH43
EH44
EH45
EH46
EX19
EX20
EX21
EX22
EX23
EX38
EX39
G13
G14
G15
G60
G61
G62
G63
G64
G81
G82
G83
G84
KA1
KA2
KA3
KA4
KA5
KA6
KA7
KA8
KA9
KA10
KA11
KA12
KA13
KA14
KA15
KA16
KA17
KA18
KA19
KA20
KA21
KA22
KA23
KA24
KA25
KA26
KA29
KA30
LD*
LL37
LL38
LL39
LL40
LL41
LL42
LL43
LL44
LL45
LL46
LL47
LL48
LL49
LL50
LL51
LL52
LL53
LL54
LL55
LL56
LL57
LL58
LL59
LL60
LL61
LL62
LL63
LL64
LL65
LL66
LL67
LL68
LL69
LL70
LL71
LL72
LL73
LL74
LL75
LL76
LL77
LL78
ML10
ML11
ML12
PA1
PA2
PA3
PA4
PA5
PA6
PA7
PA8
PA9
PA10
PA11
PA12
PA13
PA14
PA15
PA16
PA17
PA18
PA19
PL*
SA61
SA62
SA63
SA64
SA65
SA66
SA67
SA68
SA69
SA70
SA71
SA72
SA73
SY10
SY11
SY16
SY17
SY18
SY19
SY20
SY21
SY22
SY23
SY24
SY25
TD*
TR1
TR2
TR3
TR4
TR5
TR6
TR7
TR8
TR9
TR10
TR11
TR12
TR13
TR14
TR15
TR16`

Now when client is from a region where he inserts "EH22 2GF" The shipping cost does not calculate but when using a region starting with this post code "SY22" it calculates right both are in same zone so why the WC can not calculate the first postcode?

**Comment by kloon** [comment]
Looks like you are missing the wildcard character after the region codes. If you do not specify a wildcard the postcode must match the codes you entered exactly otherwise it will not return the rate.

Perhaps post a screenshot of your zone, also note that each post code needs to be on a seperate line.

As per the docs
> You can set a local zone with a specific set of postcodes (one per line); a range of postcodes (e.g. 90210…99000), or use wildcards (e.g. CB23*).
