### ISSUE TITLE
URL with / failed to open External product on several browsers

### ISSUE THREAD

**Issue by Hbitvof** [woocommerce/woocommerce#20799]
**Describe the bug**
When the external URL has a / in the cloaking url (http://www.example.com/1/product) the redirect is failing.

**To Reproduce**

I looked into it by comparing previous versions of WooCommerce with the current version, and the problem is that WooCommerce changed from using a link for the buy button:

<p class="cart">
	<a href="http://glorious-fish.w5.wpsandbox.pro/p/1" rel="nofollow" class="single_add_to_cart_button button alt">Buy it</a>
</p>

To using a form that uses the "GET" method:
<form class="cart" action="http://glorious-fish.w5.wpsandbox.pro/p/1" method="get">
	<button type="submit" class="single_add_to_cart_button button alt">Buy it</button>
</form>

I have no idea why the form is using the "get" method, because when I checked the template for this page in the WooCo source code, it's supposed to be "post": https://github.com/woocommerce/woocommerce/blob/ed2cb3e562223753355344a7a76fe295a73ab2ca/templates/single-product/add-to-cart/external.php.

I was able to fix the issue on our debug servers by copying that external.php file to: /twentyseventeen/woocommerce/single-product/add-to-cart/external.php. See: http://uninterested-dotterel.w5.wpsandbox.pro/?upass=ykG0Ihg4O20C.
**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
I am unable to replicate a redirect issue with using GET. The reason we changed it to GET was to make it conform to the majority of affiliate service rules as they feel you might be trying to trick your users into where the link is going, plus you are not posting any data to the server so there is no need to do a POST. POST methods are reserved for posting form data.

It is possible that the server you are redirecting to has something on their side stripping out the slashes but when I test this to a link on WooCommerce.com ie https://woocommerce.com/products/woocommerce-subscriptions/ it redirects fine using GET post method.

**Comment by Hbitvof** [comment]
Have you tested it in Chrome or Safari? It only occurs in these browsers.

**Comment by kloon** [comment]
@Hbitvof yes I have and have were not able to replicate this hence why I said maybe the issue is with the server you are redirecting to. Test with another link like the one I posted?
