### ISSUE TITLE
Account - Form inconsistancy

### ISSUE THREAD

**Issue by CHEWX** [woocommerce/woocommerce#20790]
Hi,

Not sure if you have this on your to do list but the form fields are inconsistent.

Output found on Account/Account Details — Last Name
```
<p class="woocommerce-form-row woocommerce-form-row--last form-row form-row-last">
    <label for="account_last_name">Last name&nbsp;<span class="required">*</span></label>
    <input type="text" class="woocommerce-Input woocommerce-Input--text input-text" name="account_last_name" id="account_last_name" autocomplete="family-name" value="">
</p>
```

Output found on Account/Addresses/Edit Address — Last Name
```
<p class="form-row form-row-last validate-required" id="billing_last_name_field" data-priority="20">
    <label for="billing_last_name" class="">Last name&nbsp;<abbr class="required" title="required">*</abbr></label>
    <span class="woocommerce-input-wrapper">
        <input type="text" class="input-text " name="billing_last_name" id="billing_last_name" placeholder="" value="" autocomplete="family-name">
    </span>
</p>
```

As you can see, difference markup and different classes. I guess this is legacy, but is it to be unified?

Thanks,
Tom

**Comment by claudiosanches** [comment]
There is already plans to unify this things, but probably only in WooCommerce 4.0 or 5.0, since some of the classes will be removed.
Closing since we already plan to improve it.

**Comment by CHEWX** [comment]
Anywhere I can keep track?

**Comment by claudiosanches** [comment]
@CHEWX you can click in watch in this project. There is some issue closed for now about it.
