### ISSUE TITLE
Category th description has no width

### ISSUE THREAD

**Issue by sybrew** [woocommerce/woocommerce#20798]
**Describe the bug**
The table header has no predefined width, allowing it to completely collapse and overflow.

**To Reproduce**
1. Go to either product categories or tags
2. Make your browser window small, e.g. 800px wide, which is common.

**Screenshots**
![image](https://user-images.githubusercontent.com/7662236/42721371-27779d2c-873a-11e8-89a3-bc90da281535.png)

**Expected behavior**
The TH must have set 15% width, or whatever you think is better, this will stop the overflow.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
- WC: Version 3.4.3<br>
- WP: Version 4.9.7
</details>

**Comment by kloon** [comment]
The table you reference is a WordPress core table. WordPress core handles all taxonomy data, in WooCommerce core we just declare the taxonomy and add an additional field to the taxonomy for the image.

I am able to replicate this on the Posts tag taxonomy if I add an additional field https://cld.wthms.co/Z8ctpB, I would suggest you log a Trac ticket for WordPress core to get this looked at.
