### ISSUE TITLE
Single product image forced to 100% width

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#20797]
**Describe the bug**
The [change here](https://github.com/woocommerce/woocommerce/commit/40f2d621490e5b8354e9eab4822d8dd1b86217fb#diff-8c33cc7d106529c44998c471ce1491eaR432) to make the image 100% width affects stores that do not have images that images that are as wide as the container. The image gets stretched when upgrading from 3.3.x to 3.4.x. 

Is the 100% width needed for the RTL fix it was added for? 

**To Reproduce**
1. Add an image that is at most 200px wide as the main product image in 3.4.3
1. View product
1. Product image is stretched. 

**Screenshots**
![](http://cld.wthms.co/ZdkwzQ+)
Image Link: http://cld.wthms.co/ZdkwzQ

Reported in 1263038-zen

**Comment by peterfabian** [comment]
Thanks for reporting. I don't see why it would be needed for RTL support. Created a PR #20818  to fix this so that people can again enjoy tiny images again :)

![nwpy](https://user-images.githubusercontent.com/2207451/42757181-45d55af4-88ff-11e8-96fb-0dda7203ad6c.gif)
