### ISSUE TITLE
Account - Orders message

### ISSUE THREAD

**Issue by CHEWX** [woocommerce/woocommerce#20791]
Hi,

Does this read right? An anchor link saying "Go Shop" and then a message.

2 things,

1. I'm not sure "Go Shop" reads well.
2. The message should be read first so it needs to come first in the markup.

https://github.com/woocommerce/woocommerce/blob/965daefe45920f25d300983671ea0f8784a82eb5/templates/myaccount/orders.php#L100-L103

Thanks,
Tom

**Comment by claudiosanches** [comment]
By default it's aligned to right, will display first only if applies a different CSS.

**Comment by CHEWX** [comment]
I'm not sure you've addressed any of my points there?

**Comment by claudiosanches** [comment]
All notices on WooCommerce does the same, this is something that we already planning to improve, and you can change on the template on your website.

**Comment by spencerfinnell** [comment]
Related #20676 #18533

**Comment by claudiosanches** [comment]
@spencerfinnell thanks for remember about that PR.
