### ISSUE TITLE
problema al cerrar sesión

### ISSUE THREAD

**Issue by xzx005gaby** [woocommerce/woocommerce#20807]
hola, tengo un problema con WooCommerce y es que si dejo algo en el carrito y le doy a cerrar sesión me da un error. alguien sabe solucionarlo?

imagen del error:
![sin titulo](https://user-images.githubusercontent.com/41275568/42740872-bbaf8176-887a-11e8-971b-e8b0511cd138.png)

esta es mi php -v, les comento que ya lo he intentado con otros servidores y versiones de php y nada:

![image](https://user-images.githubusercontent.com/41275568/42740913-43365912-887b-11e8-9e0d-837486bc0195.png)

saludos.

**Comment by kloon** [comment]
502 can only be identified by your hosting provider. I would suggest you contact your hosting provider to look into this for you. It could mean anything so would be best to get a better understanding from your hosting provider what is causing this on your site.

It could be a lot of things from running out of memory to long-running SQL queries, the list is endless.

**Comment by xzx005gaby** [comment]
I'm using Cloud9

**Comment by xzx005gaby** [comment]
tengo este otro problema. Igual si dejo algo en el carrito y le doy a cerrar sesión me da un error.

![image](https://user-images.githubusercontent.com/41275568/42767584-5edb9e3c-88eb-11e8-8a0f-b1bb9a7bb05b.png)



translation

something went wrong.

You are trying to close your trial session.

Are you sure you want to leave?

**Comment by kloon** [comment]
@xzx005gaby as I mentioned please contact your hosting provider as that is not related to WooCommerce. If you are looking for support then please contact support http://woocommerce.com/contact-us

This platform is only for reporting reproducable bugs in WooCommerce core and not a support platform to troubleshoot issues on your site. Thanks for understanding.
