### ISSUE TITLE
Bug or Intentional? Sub-Category Product Display

### ISSUE THREAD

**Issue by zwiesman31** [woocommerce/woocommerce#20802]
Is it intentional that any products that are within a sub-sub-category also get displayed as part of the main category and sub-category pages as well, even when not selected?

**Details**
For this site using WC 3.4.3 and Storefront, for example: http://www.toposim.net/distrib/product-category/terrain/continental-bundles/

The `Category display` settings are set to this:

![http://cld.wthms.co/9y433F](http://cld.wthms.co/9y433F+)
Image link: http://cld.wthms.co/9y433F

There should only be the 9 products that were designated under the "Continents" sub-category displaying here: http://www.toposim.net/distrib/product-category/terrain/continental-bundles/

![http://cld.wthms.co/0Uej3A](http://cld.wthms.co/0Uej3A+)
Image link: http://cld.wthms.co/0Uej3A

But instead of showing just those 9 products, all products of that sub-category and any sub-sub-categories under it are also showing, even when they're unchecked.

For example, this product: http://www.toposim.net/distrib/product/central-america/ is part of the `Continents` category hierarchy, but not selected as such: 

![http://cld.wthms.co/qZUkSS](http://cld.wthms.co/qZUkSS+)
Screencast link: http://cld.wthms.co/qZUkSS

With it not being selected into the `Continents` category, the ideal is that it also doesn't display in the `Continents` category page here: http://www.toposim.net/distrib/product-category/terrain/continental-bundles/, but it currently does:

![http://cld.wthms.co/oYfqfZ](http://cld.wthms.co/oYfqfZ+)
Screencast link: http://cld.wthms.co/oYfqfZ

**Question**
I tested this on my site as well and that seems to be the default behavior. Is that intentional, or a bug? Is there no setting to only show the products specifically selected in only that category?

**Comment by kloon** [comment]
It is intentional when you select to show products, technically everything belonging to a subcategory of the category you are viewing is part of that category.

Unfortunately, there is no setting. The closest you can get is if you select to show categories instead of products, I believe it would show the products part of the category you are viewing only just below the subcategories, giving you a version of what you are trying to see.
