### ISSUE TITLE
No place to add address in woocommerce

### ISSUE THREAD

**Issue by harry-sn** [woocommerce/woocommerce#20808]
I tried everything I could find to add shipping address at checkout but failed to do so. need help
I have couple of products in my store. Some are virtual classes and some physical books to be shipped. 
Virtual classes are working fine but for physical books, I am not able to add a place for shipping address at checkout
please help

https://psmsimplified.com/product/psm-book/

**Comment by kloon** [comment]
In the future please note this is not a support forum but a place to log actual reproducible bugs within WooCommerce. For support please contact the support department https://woocommerce.com/contact-us/

If you feel this is an actual bug in WooCommerce core then please provide more details as what was requested when you opened the issue. Make sure products you ship are not marked as virtual products and be sure to test with a default theme like Storefront or Twentyseventeen and with all plugins except WooCommerce disabled.
