### ISSUE TITLE
PayPal Checkout button not found due to missed size settings.

### ISSUE THREAD

**Issue by henriquemattos** [woocommerce/woocommerce#20804]
**Describe the bug**
PayPal checkout button was not found because the size settings was not recorded when the extension was activated using the installation/setup wizard.

**To Reproduce**
1. Install latest WordPress and latest WooCommerce;
2. Run WooCommerce's setup wizard;
3. Make PayPal Checkout available but don't change any configuration;
4. Add a product to the shopping cart and go to the shopping cart page;
5. An error (404 Not Found) will be generated for the image https://www.paypalobjects.com/webstatic/en_US/i/buttons/checkout-logo-.png (see the filename missing the checkout-logo-[small|medium|large].png string);

**Expected behavior**
A yellow button should be shown, but a broken image was displayed instead.

**To Fix**
Go to the settings page under WooCommerce > Configurations > Payments > PayPal Checkout and change the value of the Button Size property (the default would be responsive, choose any other) and save the change. The problem will be gone. If desired, change again to responsive if that's your choice and the problem will still be gone.

**Isolating the problem (mark completed items with an [x]):**
- [ X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.7
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.34

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.12-MariaDB-log
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: local_
MaxMind GeoIP Database: ✔
Tamanho total do banco de dados: 2.92MB
Tamanho dos dados do banco de dados: 2.08MB
Tamanho do índice do banco de dado: 0.84MB
local_woocommerce_sessions: Dados: 0.02MB + Índices: 0.02MB
local_woocommerce_api_keys: Dados: 0.02MB + Índices: 0.03MB
local_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índices: 0.02MB
local_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índices: 0.05MB
local_woocommerce_order_items: Dados: 0.02MB + Índices: 0.02MB
local_woocommerce_order_itemmeta: Dados: 0.02MB + Índices: 0.03MB
local_woocommerce_tax_rates: Dados: 0.02MB + Índices: 0.06MB
local_woocommerce_tax_rate_locations: Dados: 0.02MB + Índices: 0.03MB
local_woocommerce_shipping_zones: Dados: 0.02MB + Índices: 0.00MB
local_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índices: 0.03MB
local_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índices: 0.00MB
local_woocommerce_payment_tokens: Dados: 0.02MB + Índices: 0.02MB
local_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índices: 0.03MB
local_woocommerce_log: Dados: 0.02MB + Índices: 0.02MB
local_commentmeta: Dados: 0.02MB + Índices: 0.03MB
local_comments: Dados: 0.02MB + Índices: 0.08MB
local_links: Dados: 0.02MB + Índices: 0.02MB
local_options: Dados: 1.50MB + Índices: 0.02MB
local_postmeta: Dados: 0.02MB + Índices: 0.03MB
local_posts: Dados: 0.02MB + Índices: 0.06MB
local_termmeta: Dados: 0.02MB + Índices: 0.03MB
local_terms: Dados: 0.02MB + Índices: 0.03MB
local_term_relationships: Dados: 0.02MB + Índices: 0.02MB
local_term_taxonomy: Dados: 0.02MB + Índices: 0.03MB
local_usermeta: Dados: 0.02MB + Índices: 0.03MB
local_users: Dados: 0.02MB + Índices: 0.05MB
local_wcpv_commissions: Dados: 0.02MB + Índices: 0.00MB
local_wcpv_per_product_shipping_rules: Dados: 0.02MB + Índices: 0.00MB
local_wc_download_log: Dados: 0.02MB + Índices: 0.03MB
local_wc_webhooks: Dados: 0.02MB + Índices: 0.02MB

### Post Type Counts ###

attachment: 2
page: 6
post: 2
product: 2

### Security ###

Secure connection (HTTPS): ❌
Hide errors from visitors: ✔

### Active Plugins (6) ###

Jetpack por WordPress.com: por Automattic – 6.3.2
WooCommerce Correios: por Claudio Sanches – 3.7.1 – Não testado com a versão ativa do WooCommerce
WooCommerce PayPal Checkout Gateway: por WooCommerce – 1.6.1 – Não testado com a versão ativa do WooCommerce
WooCommerce Product Vendors: por WooCommerce – 2.1.4 – 2.1.6 está disponível – Não testado com a versão ativa do WooCommerce
WooCommerce Services: por Automattic – 1.15.1 – Não testado com a versão ativa do WooCommerce
WooCommerce: por Automattic – 3.5.0-dev

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base da loja: #5 - /loja/
Carrinho: #6 - /carrinho/
Finalizar compra: #7 - /finalizar-compra/
Minha conta: #8 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: Twenty Seventeen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ 
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by kloon** [comment]
@henriquemattos I see you tested this with 3.5, not sure when last you updated but the URL you reference is no longer in use in the gateway from what I can see. Also, it does a fallback to an icon hosted in WooCommerce core when no country matches https://github.com/woocommerce/woocommerce/blob/master/includes/gateways/paypal/class-wc-gateway-paypal.php#L239-L241

It would obviously also not be advisable to set up a store that takes payment without setting it up with the correct settings first, that said I will, however, make a small fix to disable the link when no base country is set.

**Comment by henriquemattos** [comment]
@kloon, thanks for the fast response. It was a local/dev deployment to test some extensions therefore I didn't setup the checkout completely. I checkout woocommerce master and installed in latest wordpress available in pt_BR mirror.

The link you provided does not include the image that I was referencing,  but if you say it's an updated version there, I would be fine with the resolution.

Thanks for following up. :)

**Comment by shirokoweb** [comment]
@kloon
Yes but often we like to see end result before pushing to production. And since service is enabled from install questions, why not use a placeholder image until you configure Paypal gateway no matter which country you'll setup account in.
I can't waith to go live and then make css adjustments or find out there's a hiddeous duckshit brownyellow button to swap asap.

@henriquemattos 
Alternatively, you can override hooks :

```
// hook-dat-in
add_filter( 'woocommerce_paypal_express_checkout_button_img_url' , 'override_woocommerce_paypal_express_checkout_button_img_url' );

// Hooked in function –> $fields is passed via the filter :
function override_woocommerce_paypal_express_checkout_button_img_url( $variables ) {
    $express_checkout_img_url = 'https://www.paypalobjects.com/webstatic/i/buttons/checkout-logo-medium.png';
    return $express_checkout_img_url;
}
```
