### ISSUE TITLE
Applying tax/vat to all WooCommerce showing reverse impact.

### ISSUE THREAD

**Issue by kuhashmi** [woocommerce/woocommerce#20803]
Hi,
I am using Porto WordPress theme. I am applying VAT.

When i apply VAT it showing reverse impact. 
For example If product price is 299 and if we include VAT then product price should 258 
£299 incl VAT £358.17

but it works apposite and showing price like that 
£249.17 incl VAT £249.17 which wrong. 

This is the Link : [https://budgetmedical.apps-1and1.net/product/headphone-black](url)
Actual price of product is £299

I try this code too from the website [https://tomjesch.com/display-woocommerce-products-with-and-without-tax/](url)

but none of them work. 

Does any body have a solution.

**Comment by kuhashmi** [comment]
Basically what it does. It deduct amount and showing the remaining amount. 
these are the settings.
![screen1](https://user-images.githubusercontent.com/34671377/42730629-a4d7ae50-8812-11e8-825b-fb2db0b8cfcf.jpg)
![screen2](https://user-images.githubusercontent.com/34671377/42730641-de184a8a-8812-11e8-80d6-837b40ea6a49.jpg)

**Comment by kloon** [comment]
You have the option checked that says you are defining prices including tax. If you want the VAT to be added onto the product price you need to select the option, `No, I will enter prices exclusive of tax`

Doing that will take the product price you have defined on each product, and then add VAT onto that amount.

**Comment by kuhashmi** [comment]
Thanks for your suggestion i have make the changes but no results.  
Basically VAT is not applying on Single product. It apply on variable product.

https://budgetmedical.apps-1and1.net/

if you check the link you can see that there is a single product and variable product. Single product no effect.
Check the screen shoot
![screen1](https://user-images.githubusercontent.com/34671377/42984562-9a8bd762-8c06-11e8-85bc-1a9f9fa6ccf7.jpg)

**Comment by kloon** [comment]
Where exactly are the prices display you are referring to? Note that in order to display taxes WooCommerce needs to know the user's location which is only collected at checkout.

Try setting customer location setting to `Geolocate` under WooCommerce -> Settings http://cld.wthms.co/gF9Khn

Using that setting WooCommerce will try and figure out the customer location and display taxes based on that on product pages.

**Comment by kuhashmi** [comment]
Thanks for your reply. I have change the setting and still no effect .

check my screen shoots
![screen1](https://user-images.githubusercontent.com/34671377/42984846-fece78e6-8c07-11e8-98c4-656bc6afd66b.jpg)

**Comment by kuhashmi** [comment]
`// Fix for PHP Fatal error:  Call to undefined function YIT_Pointers() in \plugins\yith-woocommerce-wishlist\includes\class.yith-wcwl-admin-init.php
if ( ! function_exists( 'is_plugin_activate' )){
    require_once( ABSPATH . 'wp-admin/includes/plugin.php' );
}
if( is_plugin_active('yith-woocommerce-wishlist/init.php') ){
    if( ! class_exists( 'YIT_Pointers' ) ){
        require_once( get_template_directory() . '/woocommerce/yit-pointers.php' );
    }
}


function edit_price_display() {
  $product = new WC_Product( get_the_ID() );
  $price = $product->price;
 
  $price_incl_tax = $price + round($price * ( 20 / 100 ), 2);
   
  $price_incl_tax = number_format($price_incl_tax, 2, ",", "."); 
  $price = number_format($price, 2, ",", "."); 
 
  $display_price = '<span class="price">';
  $display_price .= '<span class="amount">£ ' . $price_incl_tax .'<small class="woocommerce-price-suffix"> incl VAT</small></span>';
  $display_price .= '<br>';
  $display_price .= '<span class="amount">£ ' . $price .'<small class="woocommerce-price-suffix"> excl VAT</small></span>';
  $display_price .= '</span>';
 
  echo $display_price;
}
 
add_filter('woocommerce_price_html', 'edit_price_display');
add_filter('woocommerce_variable_price_html', 'edit_price_display');`

**Comment by kuhashmi** [comment]
I have add this code in function.php

**Comment by kloon** [comment]
So yes, that is your issue. You are manipulating the price via code, doing that will override the internal calculations. You do not need to add any code to make the prices display correctly, just follow the steps I laid out.

And not that in order to work out taxes on a product page, the customer's location needs to be know, this is only achievable via geolocation. The correct pricing will show at checkout once the customer enters their address details as taxes are calculated based on the address.

**Comment by kuhashmi** [comment]
ok if i remove the code from function.php file.

But what what if i want to show incl vat price at shop or product page also ?

**Comment by kuhashmi** [comment]
because basically what i want that customer will also see incl vat price or at shop and also on product page. like if you see you there is variable product and it shows both price

**Comment by kloon** [comment]
As per my previous responses just use the settings I told you to. Eg http://cld.wthms.co/GrJ7HW

Make sure the customer location setting is set to Geolocate. Also if you are testing this on a local development site you will probably not get this working as geolocation works based on your IP address.

For further assistance setting up taxes, I suggest you contact support https://woocommerce.com/contact-us/ as this platform is reserved for bugs only and not support.

Thanks for understanding.

**Comment by kuhashmi** [comment]
no my friend. I have update the function.php file and remove the code know you see on variable products it is not showing excl or incl vat price
