### ISSUE TITLE
Removed grouped product leaves ← in admin panel

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#20816]
**To Reproduce**
1. Create "Product main" and "Product 1" and "Product 2" where "Product main" is grouped and has the remaining ones as its children.
2. Delete "product main".
3. Go to "Products > All Products" and you'll see "Product 1 ←" and "Product 2 ←" which previously were "Product 1 ← Product main" and "Product 2 ← Product main".

The arrow just stays there:

<img src="https://i.imgur.com/xXCI7kU.png">

**Comment by kloon** [comment]
@manake since you left out the details as requested when opening the issue this is dificult to troubleshoot.

Mind posting your system status report so we have a better understanding of what your site is running?

I tried to replicate this on the current master branch of WooCommerce and are unable.

**Comment by manake** [comment]
Here's an update:

1. I created a grouped product an somehow `post_parent` was set (like seen on the picture).
2. But on subsequent creation of a grouped product no `post_parent` is assigned and only `_children` is assigned for the grouped product alone.

So, I don't know how to replicate this issue and my above steps to replicate it are wrong.

But it did happen under some circumstances and perhaps the bug is there but I'm closing this because I can't provide more details.

**Comment by kloon** [comment]
OK, if you ever can reproduce please let us know so we can look into it further.
