### ISSUE TITLE
CGST and SGST amount in woocommerce is not equal 

### ISSUE THREAD

**Issue by dhirajdisale** [woocommerce/woocommerce#20814]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

Hi,
I have a Wordpress site and where I'm using WooCommerce is to show my products to my customers. My site is in Indai. My store was working fine in early days but now a days i'm getting error in tax calculation. when i print Invoice for my order i'm getting different amount for CGST and SGST.

Please help me to resolve this problem

Thank you in advance

Regards,
Dhiraj DIsale
dhirajdisale17@gmail.com

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by rodrigoprimo** [comment]
Hi @dhirajdisale,

I'm sorry, but this is not a support forum. We use GitHub issues exclusively for WooCommerce core bugs, enhancements and feature requests. For support, you could try the WooCommerce forum on the WordPress.org site: https://wordpress.org/support/plugin/woocommerce

If you believe you found a bug in WooCommerce core please provide the steps to reproduce the problem on a clean WooCommerce install.

Thanks
