### ISSUE TITLE
New API Filtering Fields not working 

### ISSUE THREAD

**Issue by vajohn** [woocommerce/woocommerce#20813]
The newer API for WC on wordpress if not filtering the request. Whether its just fields or the general filter.
![untitled](https://user-images.githubusercontent.com/24270878/42756939-718a4868-88fe-11e8-80ed-62eb419deaa8.png)

**Comment by rodrigoprimo** [comment]
I don't see `fields` in the list of available parameters for this endpoint:

http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

So I'm assuming the WC API behaves the same as the WP API in that you need to write custom code to modify its response (https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/).

cc @claudiosanches in case I'm missing something and there is a parameter to specify which fields are returned by the `products` endpoint.

**Comment by claudiosanches** [comment]
@rodrigoprimo we had `fields` only in our legacy REST API.
