### ISSUE TITLE
Add config setting for "Restock refunded items" checked/unchecked default

### ISSUE THREAD

**Issue by itecedor** [woocommerce/woocommerce#20822]
**Is your feature request related to a problem? Please describe.**
For my use case, the most common reason we are refunding an order is because we did not have the item in stock after all. Because the "restock refunded items" checkbox on the order screen is checked by default, we have accidentally refunded the oversold item only to have it sell to another customer again after the refund, because it went back in stock.

**Describe the solution you'd like**
Add an option in Settings>Products>Inventory to have the restock checkbox UNCHECKED as the default.

**Describe alternatives you've considered**
Making this a pop up prompt would also prevent accidental restocks, but I'd rather have a top level switch than have to click another button.

**Additional context**
I'm submitting this ticket so that I can use its number in my commit and open a PR :)

**Comment by peterfabian** [comment]
Closing the issue as it is already being worked on in the linked PR.
