### ISSUE TITLE
Class Name Conflict with Bootstrap 4.0+

### ISSUE THREAD

**Issue by jlavoie13** [woocommerce/woocommerce#20829]
Please update the class names `.col-1` and `.col-2` as they conflict with Bootstrap 4.0. These occur in the following templates:
- `/checkout/form-checkout.php`
- `/my-account/form-login.php`
- `/order/order-details-customer.php`

**Comment by kloon** [comment]
@jlavoie13 we use specific rules, if you look at our CSS you will see we only run our CSS on pages which are related to WooCommerce, and we specify the .woocommerce class before our rules.

If your theme is using Bootstrap and declaring WooCommerce support it would be up to them to ensure the rules do not conflict, or disable WooCommerce styles completely and replacing it with their own using Bootstrap.
