### ISSUE TITLE
Dashboard Widget Display Bug

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce#20838]
**Describe the bug**
User in support live chat reported the follow display issues:

![](http://cld.wthms.co/8LqUwA+)Image Link: http://cld.wthms.co/8LqUwA

Above screenshot using Safari 11

![](http://cld.wthms.co/FOzrCd+)Image Link: http://cld.wthms.co/FOzrCd

Above screenshot on updated iPhone X using updated Safari

**Comment by claudiosanches** [comment]
Sounds like that we should trim the product name or at least improve current CSS for this widget.

**Comment by kloon** [comment]
See #20849
