### ISSUE TITLE
Reviews  feature

### ISSUE THREAD

**Issue by HaejiLee** [woocommerce/woocommerce#20837]
Hi. :)
I'd like to use the WooCommerce-Settings-Reviews feature.
It was available in the beginning, but it is not enabled at this time.
I am using the "Flatsome" theme now.
I would appreciate your reply.

**Comment by claudiosanches** [comment]
Not able to reproduce this issue, reviews feature it's working without any problem. Probably you deactivated in your settings or something going on in your theme.
