### ISSUE TITLE
Gallery images in mobile view not displaying correctly

### ISSUE THREAD

**Issue by ntindicator** [woocommerce/woocommerce#20834]
**Describe the bug**
Everything displays correctly unless a gallery image thumbnail is clicked on certain products. Some work correctly, and display the image, but when some images are clicked, it causes the gallery thumbnails to move below the cart button. If an image is clicked after this occurs then the cart button will be clicked (even thought it's the image that was clicked). It seems to happen more with the external products. Maybe it's something to do with the image sizes, not being the same. When clicked all thumbnails disappear for a second and then reappear. I disabled custom css to check it wasn't the cause.

**To Reproduce**
1. Go to: https://watercolourart.com.au/product/shop/art-supplies/daniel-smith-extra-fine-watercolor-15ml-paint-tube-quinacridone-rose/
2. Enter responsive design mode in Firefox browser
3. Choose Apple Iphone 7 as the device
2. Click on 'gallery image thumbnails'

**Screenshots**

**Expected behavior**
Click the thumbnail and change the main gallery image to display the thumbnail content

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
4.9.7
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
@ntindicator can you perhaps test if you get the same results with the Twentyseventeen theme? If not then please open an issue on the [Storefront repository](https://github.com/woocommerce/Storefront) so one of the Storefront developers can take a look there.

**Comment by ntindicator** [comment]
@kloon I tried using Twentyseventeen theme, and it seems the problem is within the custom code. To move the text above the image it was necessary to load the customisations. I was unable to move the text in Twentyseventeen, so wasn't able to reproduce the same results with this theme. I then removed all other functions except the one that moves the text, and the issue didn't occur in Storefront.
