### ISSUE TITLE
[WIKI] Wrong info in the REST API wiki

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#20845]
https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

It mentions  to activate the API in WooCommerce > Settings > API, but now it's in WooCommerce > Settings > Advanced.

Can we update that?

**Comment by kloon** [comment]
That whole guide should get updated as it references the old v1 legacy API. Needs to be replaced with screenshots and examples using v2 or even better v3 which is due in WC 3.5.

I think let's wait until after 3.5 is released before updating, just to avoid doing work now and then a month later having to redo it all again.

**Comment by peterfabian** [comment]
Updated quickly, hope it makes sense. Gerhard is right it might need an updated after we switch to v3 later.
