### ISSUE TITLE
Shipping zones under WooCommerce Shipping Settings returns a blank page.

### ISSUE THREAD

**Issue by bongfooodie** [woocommerce/woocommerce#20843]
The Shipping Zones section under WooCommerce Shipping Tab is returning a blank page.

**To Reproduce**
1. Go to WooCommerce Page
2. Click on Settings
3. Click on Shipping
4. Click on Shipping Zones
5. It will return blank page

Inspecting the page gives the following error - Failed to load resource: the server responded with a status of 500 ()

**Screenshots**
![shipping_zones_error](https://user-images.githubusercontent.com/41413587/42923122-8cba99c2-8b41-11e8-92b6-d9d622342b15.JPG)

**Expected behavior**
Ideally the Shipping Zones should open up.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins which was recently installed before it stopped working.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

Home URL: https://bongfooodie.com
Site URL: https://bongfooodie.com
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.30 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.6.39-83.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wp_aowa_
MaxMind GeoIP Database: ✔
Total Database Size: 23.98MB
Database Data Size: 19.54MB
Database Index Size: 4.44MB
wp_aowa_woocommerce_sessions: Data: 0.04MB + Index: 0.00MB
wp_aowa_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_aowa_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_aowa_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_aowa_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_aowa_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_aowa_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_aowa_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_aowa_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_aowa_woocommerce_shipping_zone_locations: Data: 0.83MB + Index: 0.88MB
wp_aowa_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_aowa_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_aowa_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_aowa_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_aowa_commentmeta: Data: 0.04MB + Index: 0.02MB
wp_aowa_comments: Data: 0.02MB + Index: 0.02MB
wp_aowa_links: Data: 0.00MB + Index: 0.00MB
wp_aowa_lockdowns: Data: 0.00MB + Index: 0.00MB
wp_aowa_login_fails: Data: 0.00MB + Index: 0.00MB
wp_aowa_options: Data: 6.08MB + Index: 0.45MB
wp_aowa_postmeta: Data: 8.71MB + Index: 2.64MB
wp_aowa_posts: Data: 3.65MB + Index: 0.22MB
wp_aowa_termmeta: Data: 0.01MB + Index: 0.02MB
wp_aowa_terms: Data: 0.01MB + Index: 0.03MB
wp_aowa_term_relationships: Data: 0.02MB + Index: 0.04MB
wp_aowa_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_aowa_tinvwl_items: Data: 0.00MB + Index: 0.00MB
wp_aowa_tinvwl_lists: Data: 0.00MB + Index: 0.00MB
wp_aowa_usermeta: Data: 0.04MB + Index: 0.03MB
wp_aowa_users: Data: 0.00MB + Index: 0.01MB
wp_aowa_wcmp_cust_answers: Data: 0.00MB + Index: 0.00MB
wp_aowa_wcmp_cust_questions: Data: 0.00MB + Index: 0.00MB
wp_aowa_wcmp_products_map: Data: 0.00MB + Index: 0.00MB
wp_aowa_wcmp_vendor_orders: Data: 0.00MB + Index: 0.00MB
wp_aowa_wcmp_visitors_stats: Data: 0.01MB + Index: 0.02MB
wp_aowa_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_aowa_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_aowa_wdi_feeds: Data: 0.00MB + Index: 0.00MB
wp_aowa_wdi_themes: Data: 0.00MB + Index: 0.00MB
wp_aowa_wpforms_entries: Data: 0.02MB + Index: 0.00MB
wp_aowa_wpforms_entry_fields: Data: 0.01MB + Index: 0.01MB
wp_aowa_wpforms_entry_meta: Data: 0.00MB + Index: 0.00MB
wp_aowa_yoast_seo_links: Data: 0.04MB + Index: 0.01MB
wp_aowa_yoast_seo_meta: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

amn_om: 1
attachment: 1276
condition_group: 2
custom_css: 2
customize_changeset: 55
dc_commission: 1
elementor-hf: 2
feedback: 10
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 16
page: 66
post: 31
product: 30
product_variation: 38
pt_view: 4
revision: 326
shop_order: 1
sidebar: 1
wdi_instagram: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

AfterShip - WooCommerce Tracking: by AfterShip – 1.8.6 – Not tested with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.0.8
AMP: by WordPress.com VIP
XWP
Google
and contributors – 0.7.2

bbPress: by The bbPress Community – 2.5.14
CCAvenue Payment Gateway for WooCommerce: by Nilesh Chourasia – 2.3 – Not tested with the active version of WooCommerce
Click to Chat for WhatsApp: by HoliThemes – 1.6
Content Aware Sidebars: by Joachim Jensen - DEV Institute – 3.7.7
Content Views: by CVSOFT LLC – 2.0.2
WC Marketplace: by WC Marketplace
The Grey Parrots – 3.1.2

Duplicate Post: by Enrico Battocchi – 3.2.2
Elementor: by Elementor.com – 2.1.4
Email Address Encoder: by Till Krüss – 1.0.7
Essential Addons for Elementor: by Codetic – 2.7.2
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.5
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.0.9
Insert Headers and Footers: by WPBeginner – 1.4.3
Instagram Slider Widget: by jetonr – 1.4.3
T(-) Countdown: by twinpictures
baden03 – 2.3.19

Login LockDown: by Michael VanDeMar – v1.7.1
No Self Pings: by Michael D. Adams – 1.1.2
OneSignal Push Notifications: by OneSignal – 1.16.7
OptinMonster API: by OptinMonster Team – 1.4.2
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 3.6
WooCommerce Paytm Payment Gateway: by Paytm – 0.2 – Not tested with the active version of WooCommerce
Shortcodes Ultimate: by Vladimir Anokhin – 5.0.4
Unique Headers: by Ryan Hellyer – 1.7.12
WCMp Legacy Settings: by WC Marketplace
The Grey Parrots – 1.0.0 – Not tested with the active version of WooCommerce

WD Instagram Feed: by WebDorado – 1.3.4
WooCommerce - Instamojo: by instamojo – 1.0.7 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.4 – Not tested with the active version of WooCommerce
WooCommerce PayU India (PayUmoney & PayUbiz): by _KDC-Labs – 2.1.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.3
Yoast SEO: by Team Yoast – 7.8
WPForms Custom Captcha: by WPForms – 1.1.1
WPForms: by WPForms – 1.4.7.2
xGen Plugin Date Information: by xGen Solutions – 2.3
Zendesk Chat Widget: by Zendesk – 1.4.12

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #626 - /shop/
Cart: #4132 - /shop/cart/
Checkout: #4133 - /shop/checkout/
My account: #4134 - /my-account/
Terms and conditions: #1083 - /terms/

### Theme ###

Name: Trusted
Version: 1.3
Author URL: https://uxlthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by kloon** [comment]
Not able to recreate this loads fine for me with just WooCommerce and a default theme like Storefront or Twentyseventeen http://cld.wthms.co/Ppwv3R

Please test by disabling all plugins except WooCommerce and also switching themes to either Twentyseventeen or Storefront and test again, then you can enabled plugins one by one testing between and finally switching back to your original theme testing to find what plugin or theme is causing your issue.
