### ISSUE TITLE
Uninitialized string offset: 0 in wc-product-functions.php when $attr['src'] = ''

### ISSUE THREAD

**Issue by jnachtigall** [woocommerce/woocommerce#20844]
At https://github.com/woocommerce/woocommerce/blob/09d50df86b423e68fe409fc3b7e1a2f0e430b9a0/includes/wc-product-functions.php#L457-L463 

the check uses `$attr['src'][0]` which results in an `Uninitialized string offset: 0` PHP Notice when `$attr['src'] = ''`. 

$attr['src'] being an empty string can happen if the lazyload plugin ([which empties it](https://github.com/wp-media/rocket-lazy-load/blob/4bbe59ee3869d8d4a6112d64b681e20dbb3fae79/rocket-lazy-load.php#L361)) is installed because for lazyloading it is [recommended](https://github.com/verlok/lazyload#do-not-use-placeholder-images) to omit the `src` attr of `img` for better user perceived performance.

It would be great if someone better would be used for the check instead of `$attr['src'][0]` which seems to try to get the first index of an array (which here just does not exist). 

Maybe just using `$attr['src']` would be better.

**Comment by kloon** [comment]
See #20848
