### ISSUE TITLE
search

### ISSUE THREAD

**Issue by kurniaarifin27** [woocommerce/woocommerce#20858]
any way to search product by keyword in woocommerce v3 rest api?

**Comment by rodrigoprimo** [comment]
I'm sorry but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce). You could also check the API documentation in case you haven't already: https://woocommerce.github.io/woocommerce-rest-api-docs/
