### ISSUE TITLE
Pending Order bug

### ISSUE THREAD

**Issue by karinwerner** [woocommerce/woocommerce#20851]
Pending order shows even after clearing the cart.
Reproduce:
1.) Select Product, which takes me to the cart.
2.) Select Checkout.
3.) Select Stripe.
4.) Go back to the cart and remove product(s).
5.) Log into the WordPress, go to WooCommerce/Orders.
Order is shown as pending.

**Comment by kloon** [comment]
Pending orders are cleanup up with a cron job based on settings you define once a day. Look under WooCommerce -> Settings -> Accounts & Privacy. There's a setting for how long to keep pending order, set that to something like 1 day and then after a day all pending orders will be cleared.

Pending orders are kept for retrying payments, so it is up to you to define how long you want customers to be able to retry paying for an order that did not go through.
