### ISSUE TITLE
Zipcode optional for WC but WC Services requires Zipcode

### ISSUE THREAD

**Issue by yangkennyk** [woocommerce/woocommerce#20862]
**Describe the bug**
When trying to get live shipping rates for shipping to "Hong Kong". The "Postcode/ZIP" is marked as optional by woocommerce but woocommerce services spits out 

"07-20-2018 @ 11:37:58 - wcc_server_error_response Error: The WooCommerce Services server returned: Bad Request child "destination" fails because [child "postcode" fails because ["postcode" is not allowed to be empty]] ( 400 ) (check_and_handle_response_error)"

in the error logs.

**To Reproduce**
1. select "Hong Kong" as country
2. enter an address in Hong Kong, I used this mcdonalds (New Mandarin Plaza, 14 Science Museum Rd, Tsim Sha Tsui East, Hong Kong)
3. Leave the postcode/zip empty.
4. it should say there are no shipping methods available.
5. now enter any character into the postcode/zip field and it should show shipping information.

**Expected behavior**
it should show shipping information even without the postcode/zip because it's an optional field in woocommerce

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodrigoprimo** [comment]
I checked with the WooCommerce Services team and this looks like to be an issue on their side and not WooCommerce core. Could you please reopen it on the WCS repository? https://github.com/Automattic/woocommerce-services
