### ISSUE TITLE
GDPR: Data removal giving a fatal

### ISSUE THREAD

**Issue by juanfra** [woocommerce/woocommerce#20877]
**Description**
The new personal data eraser is giving a fatal. It basically happened on a site where I created an order with a different email address than the one the user has (at least that's how I found out this bug):

```PHP Fatal error:  Uncaught WC_Data_Exception: Please provide a valid email address. in .../wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store.php:109```

**To Reproduce**
1. Create a product
2. When purchasing, use a different email address
3. Go to Tools > Erase Personal Data
4. Add data erasure request for the email you used on that order
5. You get the message "An error occurred while attempting to find and erase personal data.". And if you go to the logs, you get to see the Fatal I shared above.

**Comment by juanfra** [comment]
Hi @kloon,

Thanks for the prompt response. I thought the same at first, because of the message on the fatal, and once I re-checked it I found that I was actually using my gmail account. I also re-checked it now (I was doing a GDPR eraser for one of our plugins that works with WC), and what I can add is that the email address I used on checkout was also the email address of another user I had on the site. Not sure if that's also affecting the functionality.

Cheers,
Juan.

**Comment by rodrigoprimo** [comment]
I'm not able to reproduce the error following the steps provided in the issue description. I can complete a data erasure request without any fatal errors using an e-mail address that is provided only when completing an order and that is different from the user e-mail address.

@juanfra, are you are to reproduce this on a clean WooCommerce install?

**Comment by rodrigoprimo** [comment]
Also worth mentioning that according to the provided error message, PHP is dying inside the method that is used to create new customers: 

https://github.com/woocommerce/woocommerce/blob/c49059ce7aaf277042ae9cda7e575d177f13ac02/includes/data-stores/class-wc-customer-data-store.php#L109

I haven't checked, but I don't expect the data erasure code to attempt to create a customer. @juanfra, could you maybe provide the full stack trace you get when the error happens?

**Comment by juanfra** [comment]
@rodrigoprimo Olá! Nice to see you around! I hope all's well :)

I was starting to develop the GDPR exporters and erasers for Event Tickets Plus (part of The Events Calendar, and giving the possibility to sell tickets via WooCommerce).

The way I reproduce it was: on a site where I have three users, while logged in with the admin user (A) create an order using the billing email address of another user (B) and then submit the data eraser for the email of user B. Besides WooCommerce installed and active, I had The Events Calendar, Event Tickets, and Event Tickets Plus.

**Comment by rodrigoprimo** [comment]
Hola, @juanfra. Good to see you as well :)

Are you able to reproduce this problem when only WooCommerce is active?

Thanks

**Comment by rodrigoprimo** [comment]
Closing this issue due to lack of feedback and as we are not able to reproduce it. I will reopen it once we get more details.

**Comment by juanfra** [comment]
Olá Rodrigo! Thanks for the follow-up. Sorry, haven't had time to test this yet. Will ping you once I re-check it with WooCommerce active only.

Thanks
