### ISSUE TITLE
Custom fields and new hooks

### ISSUE THREAD

**Issue by fesarlis** [woocommerce/woocommerce#20871]
Hello.
Not sure if this is a bug or not. It seems that hooks have been changed in WC latest versions. I am trying to display some custom fields on order-received page and they do not work anymore.

I used to use the woocommerce_order_details_after_customer_details hook which does not work anymore. Ideally, I would like the extra fields to be shown after billing details (as they are extra billing fields). Is this hook available?

Thank you

**Comment by claudiulodro** [comment]
Thanks for the heads-up. The hook seems to have been removed in WC 3.2 as part of [this commit](https://github.com/woocommerce/woocommerce/commit/3939f50ceda0229b4df7e06f86862acbc4151842#diff-04b7b4fc3246706bd6de4ba0484bc8cfL51) and should be added back to the template.

**Comment by claudiulodro** [comment]
See #20886

**Comment by fesarlis** [comment]
body {

font-family: Segoe UI !important;
font-size: 15px !important;
color: #2f467a !important;

}


    
  
  
    Thanks for the immediate action. Since you closed the ticket I have
    to reply here. Please also consider adding a hook to add data after
    billing/shipping address that will be shown everywhere the address
    is displayed, but WITHOUT going into edit mode. At the moment the
    custom fields appear only in edit mode.
    Thank you
    
    On 24/7/2018 10:59 μμ, Claudiu
      Lodromanean wrote:
    
    
      Closed #20871.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/woocommerce/woocommerce","title":"woocommerce/woocommerce","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/woocommerce/woocommerce"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #20871."}],"action":{"name":"View Issue","url":"https://github.com/woocommerce/woocommerce/issues/20871#event-1751059776"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/woocommerce/woocommerce/issues/20871#event-1751059776",
"url": "https://github.com/woocommerce/woocommerce/issues/20871#event-1751059776",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [woocommerce/woocommerce] Custom fields and new hooks (#20871)",
"sections": [
{
"text": "",
"activityTitle": "**Claudiu Lodromanean**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@claudiulodro",
"facts": [

]
}
],
"potentialAction": [
{
"targets": [
{
"os": "default",
"uri": "https://github.com/woocommerce/woocommerce/issues/20871#event-1751059776"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 359353648\n}"
}
],
"themeColor": "26292E"
}
]
