### ISSUE TITLE
Customers earning points when store credit is applied

### ISSUE THREAD

**Issue by redlaw03** [woocommerce/woocommerce#20872]
Hi

I am using “woocommerce points and rewards” and “woocommerce smart coupons”.

When customers purchase a voucher and apply the auto generated coupon to a product making the total come to 0, it gives the client the exact same value as purchased back in points even if the amount after coupon is 0.

I have set the points modifier to 0% and that did not solve the issue.

I don’t want customers to earn points when the value is covered by coupons, how can I fix this.

Note: it does not give points for normal woocommerce coupons only for smart coupons

**Comment by kloon** [comment]
Hi there, please contact support for assistance with extensions. This repository is only for WooCommerce core bugs. https://woocommerce.com/contact-us/
