### ISSUE TITLE
Vendors commision void when customers purchase products with points

### ISSUE THREAD

**Issue by redlaw03** [woocommerce/woocommerce#20873]
Hi

I am using woocommerce Product Vendors and woocommerce points and rewards.

My problem is that my vendors commission status is set to void when a customer purchases the product with points earned through woocommerce points and rewards plugin.

How can I stop the commission status to void when points and or coupons are applied?

**Comment by kloon** [comment]
Hi there, please contact support for assistance with extensions. This repository is only for WooCommerce core bugs. https://woocommerce.com/contact-us/

**Comment by redlaw03** [comment]
I have contacted them and no reply as yet. But ill try that again thank you
