### ISSUE TITLE
Many products performance

### ISSUE THREAD

**Issue by MajkieS** [woocommerce/woocommerce#20876]
Hello,

I know this is off topic, read many posts but still no good answer.

Is woocommerce with storefront and good managed vps (I know it depends on performance) actually able to perform well with 40 000+ products or not?
And is it going to be any much better when custom tables for product come up?

Thank you 👍

**Comment by rodrigoprimo** [comment]
Generally speaking, yes. There are several WC stores with well over 40,000 products that perform well. For stores with lots of products and orders we highly recommend using a persistent object cache.

> And is it going to be any much better when custom tables for product come up?

On the tests that we ran, we saw significant improvement. You can read more about it here: https://woocommerce.wordpress.com/2018/07/17/woocommerce-custom-product-tables-beta/
