### ISSUE TITLE
variable images show the caption of the main feature image instead

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#20878]
**Describe the bug**
When adding images to specific variables, each image has it's own caption. Add a main product feature image with it's own caption and when selecting a variable, the variable's image shows the featured image's caption, instead of its own

**To Reproduce**
1. Create variable product
2. For each variation, add variable's featured image. Make sure each image has it's own unique capion
3. Add a featured image that has its own unique caption
4. In front end, choose a variable, and notice the caption from the featured image shows instead

**Screenshots**
The featured image caption;

![](http://cld.wthms.co/xqoYeN+)
Link to screenshot: http://cld.wthms.co/xqoYeN

Each variable's featured image:

![](http://cld.wthms.co/J1KRHF+)
Link to screenshot: http://cld.wthms.co/J1KRHF

![](http://cld.wthms.co/dAMR2w+)
Link to screenshot: http://cld.wthms.co/dAMR2w

Back end:

![](http://cld.wthms.co/keBVXC+)
Link to screenshot: http://cld.wthms.co/keBVXC

Front end, any variable will show the featured image caption instead:

![](http://cld.wthms.co/XxW3XV+)
Link to screenshot: http://cld.wthms.co/XxW3XV

**Expected behavior**
That the variable image's captions would show with their image

**WordPress Environment**
WC 3.4.3 and Storefront 2.3.3

**Comment by claudiulodro** [comment]
I wasn't able to reproduce this; the correct captions were displayed in my testing:

![variation image captions](https://user-images.githubusercontent.com/7317227/43159378-0766c4b8-8f37-11e8-8686-cd3b438c1f25.gif)

Additionally, the default behavior when no caption exists for a variation is to use the image Title (file name usually), not the main featured image caption.

In your screenshots I see a bunch of extra fields from other plugins. Can you deactivate the other plugins and test again?

**Comment by yukikatayama** [comment]
Thanks for checking @claudiulodro 

I've got everything deactivated now, just WC 3.4.4 now, and created a new product to see if anything changes but no luck :/ The feature image is the same as second variation, but the red shirt variation still show's the blue's caption 

![](https://cld.wthms.co/7JBEyf+)
Link to screenshot: https://cld.wthms.co/7JBEyf


I also double checked user's titles, but they match what their image captions should say....interestingly, I have both image title and caption in my test product. When I removed my caption, then the titles shows as expected.

![](http://cld.wthms.co/IxznPB+)
Link to screenshot: http://cld.wthms.co/IxznPB

![](http://cld.wthms.co/NOEjgp+)
Link to screenshot: http://cld.wthms.co/NOEjgp


Removing title and only having captions, showed the wrong caption. **Maybe user should just use title instead (since they have it set to the same)?**

And forgot to add the ticket last time: 1296055-zen

**Comment by peterfabian** [comment]
Please see https://github.com/woocommerce/woocommerce/pull/21022.
