### ISSUE TITLE
vendor dashboard doesn't have product import and export buttons in woocommerce 3.4.1

### ISSUE THREAD

**Issue by Bharathsiva** [woocommerce/woocommerce#20888]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by Bharathsiva** [comment]
in previous woocommerce version vendor dashboard has product import and export buttons.But it won't work.In the new woocommerce 3.4.1 they removed those buttons.But i need those options (i.e : product import and export  for vendors) and how can i enable this in my woocommerce wordpress.pls help me to solve this issue.
Thanks in advance:)

**Comment by kloon** [comment]
@Bharathsiva this issue tracker is for reporting bugs in WooCommerce core and not extensions. Please contact support for assistance with extensions https://woocommerce.com/contact-us/
