### ISSUE TITLE
CRITICAL Uncaught Error: Call to a member function get_permalink()

### ISSUE THREAD

**Issue by ShopRocketAT** [woocommerce/woocommerce#20880]
I found following message in the logs of woocommerce:
2018-07-24T07:01:17+00:00 CRITICAL Uncaught Error: Call to a member function get_permalink() on boolean in /home/glasscbv/www.glass-inspiration.com/wp-content/plugins/woocommerce/templates/content-widget-product.php:27
Stack trace:
#0 /home/glasscbv/www.glass-inspiration.com/wp-content/plugins/woocommerce/includes/wc-core-functions.php(210): include()
#1 /home/glasscbv/www.glass-inspiration.com/wp-content/plugins/woocommerce/includes/widgets/class-wc-widget-recently-viewed.php(96): wc_get_template('content-widget-...', Array)
#2 /home/glasscbv/www.glass-inspiration.com/wp-includes/class-wp-widget.php(372): WC_Widget_Recently_Viewed->widget(Array, Array)
#3 /home/glasscbv/www.glass-inspiration.com/wp-includes/widgets.php(743): WP_Widget->display_callback(Array, Array)
#4 /home/glasscbv/www.glass-inspiration.com/wp-content/themes/Divi/sidebar.php(8): dynamic_sidebar('sidebar-1')
#5 /home/glasscbv/www.glass-inspiration.com/wp-includes/template.php(688): require_once('/home/glasscbv/...')
#6 /home/glasscbv/www.glass-inspiration.com/wp-includes/tem

I have no bug in the frontend, only stripe is not going well. But it doesn't look like it has to do something with stripe. 

Thank you for your help!

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://www.glass-inspiration.com
Site URL: https://www.glass-inspiration.com
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.8 - Wir empfehlen
PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisierst du deine PHP-Version

PHP Post Max Size: 40 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.55.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.57 - Wir empfehlen mindestens MySQL-Version 5.6. Siehe: WordPress-Anforderungen
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 66.30MB
Datenbank-Datengröße: 44.74MB
Datenbank-Indexgröße: 21.56MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Daten: 0.01MB + Index: 0.01MB
wp_woocommerce_tax_rates: Daten: 0.01MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Daten: 0.00MB + Index: 0.00MB
iwp_clone_stats: Daten: 0.02MB + Index: 0.00MB
IWP_processed_iterator: Daten: 0.02MB + Index: 0.00MB
siwp587290_wp_commentmeta: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_comments: Daten: 0.00MB + Index: 0.01MB
siwp587290_wp_icl_cms_nav_cache: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_content_status: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_core_status: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_flags: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_languages: Daten: 0.00MB + Index: 0.01MB
siwp587290_wp_icl_languages_translations: Daten: 0.10MB + Index: 0.10MB
siwp587290_wp_icl_locale_map: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_message_status: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_mo_files_domains: Daten: 0.01MB + Index: 0.00MB
siwp587290_wp_icl_node: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_reminders: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_strings: Daten: 4.12MB + Index: 3.32MB
siwp587290_wp_icl_string_packages: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_string_pages: Daten: 0.57MB + Index: 0.73MB
siwp587290_wp_icl_string_positions: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_string_status: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_string_translations: Daten: 1.98MB + Index: 0.71MB
siwp587290_wp_icl_string_urls: Daten: 0.00MB + Index: 0.01MB
siwp587290_wp_icl_translate: Daten: 0.73MB + Index: 0.19MB
siwp587290_wp_icl_translate_job: Daten: 0.02MB + Index: 0.02MB
siwp587290_wp_icl_translations: Daten: 0.21MB + Index: 0.47MB
siwp587290_wp_icl_translation_batches: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_icl_translation_status: Daten: 0.92MB + Index: 0.07MB
siwp587290_wp_isiwp587290_wp_backup_status: Daten: 0.02MB + Index: 0.00MB
siwp587290_wp_links: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_options: Daten: 1.09MB + Index: 0.10MB
siwp587290_wp_pmxe_exports: Daten: 0.08MB + Index: 0.00MB
siwp587290_wp_pmxe_google_cats: Daten: 0.39MB + Index: 0.00MB
siwp587290_wp_pmxe_posts: Daten: 0.11MB + Index: 0.00MB
siwp587290_wp_pmxe_templates: Daten: 0.02MB + Index: 0.00MB
siwp587290_wp_pmxi_files: Daten: 0.02MB + Index: 0.00MB
siwp587290_wp_pmxi_history: Daten: 0.02MB + Index: 0.00MB
siwp587290_wp_pmxi_images: Daten: 0.05MB + Index: 0.00MB
siwp587290_wp_pmxi_imports: Daten: 0.17MB + Index: 0.00MB
siwp587290_wp_pmxi_posts: Daten: 0.13MB + Index: 0.11MB
siwp587290_wp_pmxi_templates: Daten: 0.05MB + Index: 0.00MB
siwp587290_wp_postmeta: Daten: 7.40MB + Index: 3.21MB
siwp587290_wp_posts: Daten: 2.16MB + Index: 0.45MB
siwp587290_wp_redirection_404: Daten: 0.02MB + Index: 0.06MB
siwp587290_wp_redirection_groups: Daten: 0.02MB + Index: 0.03MB
siwp587290_wp_redirection_items: Daten: 0.02MB + Index: 0.08MB
siwp587290_wp_redirection_logs: Daten: 0.02MB + Index: 0.08MB
siwp587290_wp_termmeta: Daten: 0.00MB + Index: 0.01MB
siwp587290_wp_terms: Daten: 0.00MB + Index: 0.01MB
siwp587290_wp_term_relationships: Daten: 0.07MB + Index: 0.16MB
siwp587290_wp_term_taxonomy: Daten: 0.01MB + Index: 0.01MB
siwp587290_wp_usermeta: Daten: 0.03MB + Index: 0.01MB
siwp587290_wp_users: Daten: 0.00MB + Index: 0.01MB
siwp587290_wp_wc_download_log: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_wc_webhooks: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_log: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_order_itemmeta: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_sessions: Daten: 0.01MB + Index: 0.00MB
siwp587290_wp_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_woocommerce_tax_rates: Daten: 0.01MB + Index: 0.01MB
siwp587290_wp_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB
siwp587290_wp_yoast_seo_links: Daten: 0.02MB + Index: 0.02MB
siwp587290_wp_yoast_seo_meta: Daten: 0.11MB + Index: 0.00MB
wp_commentmeta: Daten: 0.00MB + Index: 0.00MB
wp_comments: Daten: 0.00MB + Index: 0.01MB
wp_icl_cms_nav_cache: Daten: 0.00MB + Index: 0.00MB
wp_icl_content_status: Daten: 0.00MB + Index: 0.00MB
wp_icl_core_status: Daten: 0.00MB + Index: 0.00MB
wp_icl_flags: Daten: 0.00MB + Index: 0.00MB
wp_icl_languages: Daten: 0.00MB + Index: 0.01MB
wp_icl_languages_translations: Daten: 0.10MB + Index: 0.10MB
wp_icl_locale_map: Daten: 0.00MB + Index: 0.00MB
wp_icl_message_status: Daten: 0.00MB + Index: 0.00MB
wp_icl_mo_files_domains: Daten: 0.01MB + Index: 0.00MB
wp_icl_node: Daten: 0.00MB + Index: 0.00MB
wp_icl_reminders: Daten: 0.00MB + Index: 0.00MB
wp_icl_strings: Daten: 4.31MB + Index: 3.31MB
wp_icl_string_packages: Daten: 0.00MB + Index: 0.00MB
wp_icl_string_pages: Daten: 1.87MB + Index: 2.28MB
wp_icl_string_positions: Daten: 0.00MB + Index: 0.00MB
wp_icl_string_status: Daten: 0.00MB + Index: 0.00MB
wp_icl_string_translations: Daten: 2.07MB + Index: 0.68MB
wp_icl_string_urls: Daten: 0.00MB + Index: 0.01MB
wp_icl_translate: Daten: 0.76MB + Index: 0.14MB
wp_icl_translate_job: Daten: 0.02MB + Index: 0.02MB
wp_icl_translations: Daten: 0.21MB + Index: 0.40MB
wp_icl_translation_batches: Daten: 0.00MB + Index: 0.00MB
wp_icl_translation_status: Daten: 0.91MB + Index: 0.07MB
wp_iwp_backup_status: Daten: 0.02MB + Index: 0.00MB
wp_links: Daten: 0.00MB + Index: 0.00MB
wp_options: Daten: 1.62MB + Index: 0.15MB
wp_pmxe_exports: Daten: 0.08MB + Index: 0.00MB
wp_pmxe_google_cats: Daten: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Daten: 0.11MB + Index: 0.00MB
wp_pmxe_templates: Daten: 0.02MB + Index: 0.00MB
wp_pmxi_files: Daten: 0.02MB + Index: 0.00MB
wp_pmxi_history: Daten: 0.02MB + Index: 0.00MB
wp_pmxi_images: Daten: 0.05MB + Index: 0.00MB
wp_pmxi_imports: Daten: 0.17MB + Index: 0.00MB
wp_pmxi_posts: Daten: 0.13MB + Index: 0.11MB
wp_pmxi_templates: Daten: 0.05MB + Index: 0.00MB
wp_postmeta: Daten: 8.10MB + Index: 3.30MB
wp_posts: Daten: 2.12MB + Index: 0.46MB
wp_redirection_404: Daten: 0.02MB + Index: 0.06MB
wp_redirection_groups: Daten: 0.02MB + Index: 0.03MB
wp_redirection_items: Daten: 0.02MB + Index: 0.08MB
wp_redirection_logs: Daten: 0.02MB + Index: 0.08MB
wp_termmeta: Daten: 0.00MB + Index: 0.01MB
wp_terms: Daten: 0.00MB + Index: 0.01MB
wp_term_relationships: Daten: 0.07MB + Index: 0.17MB
wp_term_taxonomy: Daten: 0.01MB + Index: 0.01MB
wp_usermeta: Daten: 0.47MB + Index: 0.01MB
wp_users: Daten: 0.00MB + Index: 0.01MB
wp_wc_download_log: Daten: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Daten: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Daten: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Daten: 0.14MB + Index: 0.00MB

### Post Type Counts ###

attachment: 2995
cf7_style: 1
custom_css: 2
customize_changeset: 9
et_pb_layout: 13
flamingo_contact: 29
flamingo_inbound: 28
invoice: 6
iwp_log: 21
nav_menu_item: 27
oembed_cache: 2
page: 58
post: 6
product: 1104
product_variation: 42
revision: 281
shop_coupon: 5
shop_order: 2
wpcf7_contact_form: 4
yith-wcbm-badge: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (39) ###

InfiniteWP - Client: von Revmakx – 1.8.3
WPML Multilingual CMS: von OnTheGoSystems – 4.0.4
4DIVI Masonry gallery: von Design Green Cat – 1.11
All 404 Redirect  to Homepage: von Fakhri Alsadi – 1.13
Antispam Bee: von pluginkollektiv – 2.8.1
Captcha Code: von Vinoj Cardoza – 2.6.6
Contact Form 7 Style: von Johnny
dorumarginean
mlehelsz
MirceaR – 3.1.7

Contact Form 7: von Takayuki Miyoshi – 5.0.3
Disable REST API: von Dave McHale – 1.4.3
Divi Booster: von Dan Mossop – 2.7.4
Duplicate Post: von Enrico Battocchi – 3.2.2
Flamingo: von Takayuki Miyoshi – 1.8
GA Google Analytics: von Jeff Starr – 20180506
Loco Translate: von Tim Whitlock – 2.1.3
PixelYourSite: von PixelYourSite – 5.3.1 – Nicht getestest mit der aktiven WooCommerce-Version
Remove XMLRPC Pingback Ping: von Brad Vincent – 1.0.0
Cookie Consent: von Catapult_Themes – 2.3.11
UpdraftPlus - Backup/Restore: von UpdraftPlus.Com
DavidAnderson – 1.14.12

WooCommerce Weight Based Shipping +: von weightbasedshipping.com – 5.2.1.1
WooCommerce Product Attachment: von multidots – 1.1.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Extra Product Sorting Options: von SkyVerge – 2.7.1 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Stripe-Gateway: von WooCommerce – 4.1.7
WooCommerce Germanized Pro: von Vendidero – 1.8.5 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Germanized: von Vendidero – 2.0.4
WooCommerce Multilingual: von OnTheGoSystems – 4.3.3
Woocommerce Shipping Gateway per Product: von Dreamfox Media – 1.3.1 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce: von Automattic – 3.4.3
Yoast SEO: von Team Yoast – 7.8
WP All Export Pro: von Soflyy – 1.5.3
WP All Import Pro: von Soflyy – 4.5.4
WP Super Cache: von Automattic – 1.6.2
WP Updates Notifier: von Scott Cariss – 1.4.4
WP All Import - WooCommerce Add-On Pro: von Soflyy – 2.4.1
WPML CMS Nav: von OnTheGoSystems – 1.4.23
WPML Media: von OnTheGoSystems – 2.3.4
WPML String Translation: von OnTheGoSystems – 2.8.4
WPML Translation Management: von OnTheGoSystems – 2.6.4
YITH WooCommerce Badge Management: von YITHEMES – 1.3.9 – Nicht getestest mit der aktiven WooCommerce-Version
YITH WooCommerce Featured Video: von YITHEMES – 1.1.17 – Nicht getestest mit der aktiven WooCommerce-Version

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #4 - /shop/
Warenkorb: #5 - /warenkorb/
Kasse: #6 - /kasse/
Mein Konto: #7 - /mein-konto/
Allgemeine Geschäftsbedingungen: #43 - /agb/

### Theme ###

Name: ShopRocket
Version: 3.0.106
Author URL: https://www.shop-rocket.at
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.10.1
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by rodrigoprimo** [comment]
Thanks for your report. I was not able to reproduce this issue but it is a good idea anyway to add a check to make sure `$product` is an instance of `WC_Product` before calling its methods. PR #20881 addresses this.

Not sure if I'm missing something, but the code calling `content-widget-product.php` seems to pass only valid products to this file:

https://github.com/woocommerce/woocommerce/blob/b329d81279defb9a02f659241ede9ddcb35dd351/includes/widgets/class-wc-widget-recently-viewed.php#L94

That is why I can't easily see how the fatal error you got on your logs happened. Maybe it was some product that was only partially deleted from the database (product data in post meta removed but data in wp_posts preserved)? Just a wild guess.
