### ISSUE TITLE
Unable to add more than one coupon at Checkout

### ISSUE THREAD

**Issue by fhaps** [woocommerce/woocommerce#20885]
**Describe the bug**

Customers are unable to add more than one coupon in the Checkout page. Once a coupon has been added, the option to apply a coupon code is completely removed from the Checkout page.

This happens regardless of whether the coupon can be applied individually or in addition to other discounts.

**To Reproduce**
1. Go to your store and add a product to the cart.
2. Head to the checkout page.
3. Click on the link to add a coupon code: `Click here to enter your code`
4. Add the code and apply coupon.
5. Refresh the page – the option to add a code is gone.

**Expected behavior**
For there to be an option to add more than one coupon in the checkout page, just like these can be added in the cart page

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
See #20889
