### ISSUE TITLE
Orders Page not Automatically Updating to New Shipping Address

### ISSUE THREAD

**Issue by t0rxe** [woocommerce/woocommerce#20890]
I am having a lot of customers complaining that when they update their 'Shipping Address' or 'Billing Address' from the 'My Account' page, it isn't actually updating their order. To fix it, I have to manually find their order after they have emailed me with the problem, and I need to click on 'Load Shipping Address' where a popup message re-confirms my selection.

**To Reproduce**
1. Go to your order and note the address.
2. Click on 'My Account'.
3. Scroll down to 'Edit', change your address and save it.
4. Go back to your order and you'll see that the address is still the old one. It doesn't refresh.

**Expected behavior**
Once the customer has updated their address (on step 3) and saved it, the address should change in the order without me manually refreshing it. This is a huge annoyance because when customers get emails from me if I update their order, they complain that it still has their old address even though they specially logged in and spent the time to change it.

**Isolating the problem**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WooCommerce V2.4.13 and WordPress V4.3.
I am clearly using an older version, so if this bug has been fixed, please tell me what file(s) and where I need to edit. I have spent hours looking at the GitHub source and Googling for a solution but I can't find anything close to describing my issue.

NOTE: I can't update to the newer version because I have a few minor tweaks in place, but none of which would effect this issue because it used to happen even when I had no plugins and I was using the original Wordpress theme, but now because my site has grown, it's become a major problem for me and the customers.

Thanks.

**Comment by kloon** [comment]
That is not the nature of how past orders should work. When you change your address details after orders were placed with different addresses it will not update the past orders, an order placed and/or processed is considered a binding agreement and can form part of tax documentation so it should maintain the information as it was created and paid for.

No online store I know of updates your past orders with new addresses when you change it in your account.

**Comment by t0rxe** [comment]
It's a bit rude to close an open issue without resolving it directly with me, because what about in the case of pre-orders? If a customer has changed their address, it should have updated it. Period.

**Comment by kloon** [comment]
Sorry if you find it rude, was not my meant to be rude. We just close issues that we feel is not a bug, you can image how much open issues there would be to go through if we kept every single report open for long periods of time.

Regarding your response it is definitely not a bug on our side or functionality we would likely add. WooCommerce core does not offer pre-order functionality out of the box, it would be up the extension adding the functionality to take care of that then.

**Comment by t0rxe** [comment]
Strange, I thought WooCommerce offered back-ordering where items could still be purchased, even when out of stock.

Nonetheless, I appreciate your response. I will have to tackle this issue further myself.

**Comment by kloon** [comment]
@t0rxe we do offer back-ordering functionality out of the box but that is not the same as pre-ordering. With back-ordering, you actually pay up front.

There is a pre-order extension available where you can do pre-ordering and only pay once the good become available https://woocommerce.com/products/woocommerce-pre-orders/
