### ISSUE TITLE
There is no any filter on add_to_cart where anyone can prevent to product for add to cart.

### ISSUE THREAD

**Issue by uchandra** [woocommerce/woocommerce#20893]
**There is no any filter on add_to_cart where anyone can prevent to product for add to cart.**
We want a filter where we can create a hook before add_to_cart where anyone can prevent to product for add to cart.

Currently, I am using following hook, which is just an alternative.
 _add_action( 'woocommerce_add_to_cart_quantity', [ $this,  'allow_single_subscription_product_in_cart' ] );_

**Comment by claudiosanches** [comment]
You can use `woocommerce_add_to_cart` hook and throw `Exception`'s with error messages:

https://github.com/woocommerce/woocommerce/blob/233b8399085c50682ddcc07b3568b0a33e8f798d/includes/class-wc-cart.php#L1096-L1105
