### ISSUE TITLE
Add a way to disable Multi-Site Orders Widget

### ISSUE THREAD

**Issue by JulienMelissas** [woocommerce/woocommerce#20891]
**Is your feature request related to a problem? Please describe.**
Hello, I looked in [the code](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-dashboard.php) for a way to disable the [Multi-Site Orders Widget](https://docs.woocommerce.com/document/dashboard-widgets/#section-3), but I haven't found an easy way yet. It would be great if there was a simple way to disable it. On a massive multi-site with a large amount of stores, it can be a resource-consuming query and may not be necessary for all users (such as us).

**Describe the solution you'd like**
It would be fantastic if there was a filter, or constant to disable the orders widget.

**Describe alternatives you've considered**
I thought about using a `remove_meta_box` hook, but I figured there could be a more straight-forward/documented way.

**Additional context**
I would be happy to work on a PR for this, I just wanted to propose it first and would love some direction around the preferred way to do it.

Thanks 👋

**Comment by kloon** [comment]
You wll need to use remove_meta_box

```php
function wc_remove_dashboard_widget(){
    remove_meta_box( 'woocommerce_dashboard_status', 'dashboard', 'normal');    
}
add_action( 'wp_dashboard_setup', 'wc_remove_dashboard_widget', 20 );
```

**Comment by JulienMelissas** [comment]
Thanks @kloon, I'll use `remove_meta_box` as suggested.

**Comment by JulienMelissas** [comment]
That said, I will say the correct code for what I was asking is:
```
function wc_remove_dashboard_widget(){
    remove_meta_box( 'woocommerce_network_orders', 'dashboard', 'normal');    
}
add_action( 'wp_dashboard_setup', 'wc_remove_dashboard_widget', 20 );
```

The meta box's key is `woocommerce_network_orders` not `woocommerce_dashboard_status` 👍
