### ISSUE TITLE
Reset Password link is not working when My Account URL has Percent Encoding symbols. Cannot set 'wp-resetpass-" cookie.

### ISSUE THREAD

**Issue by Snadex** [woocommerce/woocommerce#20895]
Hi,
when my account url is in language requiring Percent Encoding in URL (like Hebrew in this case, also tested with Cyrilic): 
/אזור-אישי/
/%d7%90%d7%96%d7%95%d7%a8-%d7%90%d7%99%d7%a9%d7%99/

the function
wc_clean( wp_unslash( $_SERVER['REQUEST_URI'] ) ) 
in https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-my-account.php#L367

returns just 
/-/lost-password/
instead of
/אזור-אישי/lost-password/
/%d7%90%d7%96%d7%95%d7%a8-%d7%90%d7%99%d7%a9%d7%99/lost-password/

Removing the wc_clean() function solves the issue.

------------------

When you visit the password reset link in the email,
it should set this cookie and redirect you to the correct reset form,
instead, it is failing to set the cookie because of the wrong cookie URL. 

This is what it is trying to set:

set-cookie: wp-resetpass-d4e3185b610bf7096050f1bbfd08db15=alex_admin%3Asix7oOnXGLovsQcOJtYv; path=/-/lost-password/; secure; httponly

while it should be:

set-cookie: wp-resetpass-d4e3185b610bf7096050f1bbfd08db15=alex_admin%3Asix7oOnXGLovsQcOJtYv; path=/%d7%90%d7%96%d7%95%d7%a8-%d7%90%d7%99%d7%a9%d7%99/lost-password/; secure; httponly

**Comment by claudiosanches** [comment]
See #20901 
Thanks for reporting it.
