### ISSUE TITLE
I can't see "language options" by Polylang in the list of my products 

### ISSUE THREAD

**Issue by hello-Im-new** [woocommerce/woocommerce#20896]
Hello everyone,

The problem is, after a successful installing Polylang and translating some my web's pages, I cannot get to translating the products I have. The "language options" by Polylang are simply missing in my Woocommerce.

Any suggestions?

**Comment by claudiosanches** [comment]
Hi there! GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal.

Your issue seems to be caused by Polylang.

Please contact the author directly for support.
