### ISSUE TITLE
'woocommerce_grant_product_download_access' hook doesn't work as expected

### ISSUE THREAD

**Issue by kanishkdudeja** [woocommerce/woocommerce#20904]
**Description:**

cc @mattyza @gedex 

WooCommerce throws a fatal error if I attempt to create a new order note when downloadable permissions are granted for a product using the WooCommerce.com admin dashboard.

**Steps to reproduce the behaviour:**

To accomplish this, I hooked a custom function to the `woocommerce_grant_product_download_access` hook on the `woocommerce_init` hook and called wc_create_order_note() inside my custom function. 

When I then grant download permissions to a product, I see this fatal error in debug logs:

```
[26-Jul-2018 08:15:08 UTC] PHP Fatal error:  Uncaught Exception: Invalid download. in /var/www/wordpress/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-download-data-store.php:95
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(156): WC_Customer_Download_Data_Store->read(Object(WC_Customer_Download))
#1 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-customer-download.php(66): WC_Data_Store->read(Object(WC_Customer_Download))
#2 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(769): WC_Customer_Download->__construct(4243305)
#3 /var/www/wordpress/wp-includes/class-wp-hook.php(286): WC_AJAX::grant_access_to_download('')
#4 /var/www/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /var/www/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /var/www/wordpress/wp-admin/admin-ajax.php(97): do_action('wp_ajax_woocomm...')
#7 {main}
  thrown in /var/www/wordpress/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-download-data-store.php on line 95
[26-Jul-2018 08:15:08 UTC] PHP Notice:  [wccom-logger critical fatal-errors]: Array
(
    [current_user] => 1
    [log] => Uncaught Exception: Invalid download. in /var/www/wordpress/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-download-data-store.php:95
Stack trace:
#0 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(156): WC_Customer_Download_Data_Store->read(Object(WC_Customer_Download))
#1 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-customer-download.php(66): WC_Data_Store->read(Object(WC_Customer_Download))
#2 /var/www/wordpress/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(769): WC_Customer_Download->__construct(4243305)
#3 /var/www/wordpress/wp-includes/class-wp-hook.php(286): WC_AJAX::grant_access_to_download('')
#4 /var/www/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /var/www/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /var/www/wordpress/wp-admin/admin-ajax.php(97): do_action('wp_ajax in /var/www/wordpress/wp-content/plugins/wccom-plugins/logger/includes/class-logger.php on line 47
```

**Expected behavior**

I should be able to add an order note using `wc_create_order_note` when downloadable permissions are granted for a product.

**Possible fix**

I'm not sure what the root cause of the issue is but moving the following line:

`do_action( 'woocommerce_grant_product_download_access', $data );`

to the bottom of the `create()` function in the `WC_Customer_Download_Data_Store` class fixed it for me.

PR: #20905 

**WordPress Environment**
```
Home URL: https://woocommerce.test
Site URL: https://woocommerce.test
WC Version: 3.4.0
Log Directory Writable: ✔
WP Version: ❌ 4.9.4 - There is a newer version of WordPress available (4.9.7)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –
```

**Comment by claudiulodro** [comment]
[The download ID hasn't been set on the download when `woocommerce_grant_product_download_access` fires](https://github.com/woocommerce/woocommerce/blob/35bfb6bbdc1fa86d2930e7cde53dd024a9125d2e/includes/data-stores/class-wc-customer-download-data-store.php#L64-L69), so you [get an error when WC tries to read the download from the permissions table](https://github.com/woocommerce/woocommerce/blob/35bfb6bbdc1fa86d2930e7cde53dd024a9125d2e/includes/data-stores/class-wc-customer-download-data-store.php#L87-L96). 

This seems to be a slight behavior change from [the original implementation of the `woocommerce_grant_product_download_access` hook](https://github.com/woocommerce/woocommerce/blob/b794d183b12aa58c79b61f3a67f49162626af29a/includes/wc-order-functions.php#L88-L93), where accessing the download object from that hook was fine because the download already had an ID. The change you propose looks like a good solution.

**Comment by kanishkdudeja** [comment]
Thank you for the explanation and merging #20905
