### ISSUE TITLE
Can't find force ssl button anymore is required for my plugin to work?

### ISSUE THREAD

**Issue by amiya34** [woocommerce/woocommerce#20903]
Can I get a checkbox location for "Force SSL"? :-)

**Comment by peterfabian** [comment]
WooCommerce > Settings > Advanced > Page Setup.
![forcessl](https://user-images.githubusercontent.com/2207451/43248877-702284aa-90b9-11e8-9c4f-9b8d0759e864.png)

**Comment by amiya34** [comment]
you can login and see for yourself www.5000.cash username: rent password:
Nugget.37

**Comment by claudiosanches** [comment]
@amiya34 You've just exposed your site's login information to anyone who sees this thread... Please reset this password, we are not going to access your website to solve any problem, we can only provide guidance if it's an issue on WooCommerce.

**Comment by amiya34** [comment]
Yeah well you're sending me an email how am I supposed to know it's at tread

**Comment by amiya34** [comment]
You guys shouldn't sell plugins for 80 bucks that don't work
