### ISSUE TITLE
WooCommerce Brand plugin incompatible with WooCommerce Active Product Filters

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#20907]
**Describe the bug**
I noticed that the WooCommerce Brand plugin is incompatible with the WooCommerce Active Product Filters. When using the Widget (WooCommerce Brand Layered Nav) and filtering for a brand, selected brands are not added to the Active Product Filters widget.

**To Reproduce**
1. Add WooCommerce Brand Layered Nav widget and Active Products Filter widget to a site.
2. Filter for brands
3. Scroll down to the Active Product Filters
4. See that brands are not added.

**Screenshots**

**Expected behavior**
Brands shoulb be added to Active Product Filters so that they can be removed.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL:
Site URL:
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.8
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 5000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wp_
Total databasstorlek: 60.23MB
Datastorlek för databas: 39.97MB
Indexstorlek för databas: 20.26MB
wp_woocommerce_sessions: Data: 1.06MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 3.13MB + Index: 0.22MB
wp_postmeta: Data: 30.56MB + Index: 15.06MB
wp_posts: Data: 2.52MB + Index: 2.34MB
wp_termmeta: Data: 0.11MB + Index: 0.14MB
wp_terms: Data: 0.13MB + Index: 0.13MB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB
wp_term_taxonomy: Data: 0.16MB + Index: 0.20MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.33MB + Index: 0.00MB

### Post Type Counts ###

attachment: 3495
custom_css: 1
custom-css-js: 2
nav_menu_item: 8
page: 14
post: 3
product: 758
product_variation: 4166
revision: 19
shipping_package: 5
shop_order: 2
slider: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

Akismet Anti-Spam: av Automattic – 4.0.8
Contact Form 7: av Takayuki Miyoshi – 5.0.3
Simple Custom CSS and JS: av SilkyPress.com – 3.18 – Inte testat med den aktiva versionen för WooCommerce
Customizer Export/Import: av The Beaver Builder Team – 0.7
Flexible Shipping PRO: av WP Desk – 1.6.2
Flexible Shipping: av WP Desk – 2.1.6
Kidz Theme Functionality: av ideapark.kz – 1.4.2
Kidz Theme Wishlist: av ideapark.kz – 1.2 – Inte testat med den aktiva versionen för WooCommerce
Loco Translate: av Tim Whitlock – 2.1.4
Really Simple SSL: av Rogier Lankhorst
Mark Wolters – 3.0.5

Regenerate Thumbnails: av Alex Mills (Viper007Bond) – 3.0.2
SVG Support: av Benbodhi – 2.3.15
W3 Total Cache: av Frederick Townes – 0.9.7
Woo Category Base Permalink Fixer: av MasterNs – 2.1 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Advanced Shipping Packages: av WooCommerce – 1.1.4 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Brands: av WooCommerce – 1.6.2
WooCommerce Breadcrumb Permalinks: av Captain Theme – 1.1.2 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Stripe Gateway: av WooCommerce – 4.1.8
WooCommerce Measurement Price Calculator: av SkyVerge – 3.13.5
WooCommerce Min/Max Kvantiteter: av WooCommerce – 2.4.3
WooCommerce Product Add-ons: av WooCommerce – 2.9.5 – 2.9.6 finns tillgänglig – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Product CSV Import Suite: av WooCommerce – 1.10.14 – Inte testat med den aktiva versionen för WooCommerce
WooCommerce Sequential Order Numbers Pro: av SkyVerge – 1.12.0 – 1.12.1 finns tillgänglig – Inte testat med den aktiva versionen för WooCommerce
WooCommerce: av Automattic – 3.4.3 – 3.4.4 finns tillgänglig
Yoast SEO Premium: av Team Yoast – 7.5.1
WP Desk Helper: av WP Desk – 1.4.4
WPMU DEV Dashboard: av WPMU DEV – 4.5.2
Yoast SEO: WooCommerce: av Team Yoast – 7.5 – Inte testat med den aktiva versionen för WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
instock (instock)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Butikbas: #4 - /sortiment/
Varukorg: #5 - /varukorg/
Kassan: #6 - /kassan/
Mitt konto: #7 - /mitt-konto/
Allmänna villkor: #14 - /kopvillkor/

### Theme ###

Name:
Version: 1.1
Author URL:
Child Theme: ✔
Parent Theme Name:
Parent Theme Version: 1.4.9
Parent Theme Author URL:
WooCommerce Support: ✔

### Templates ###

Overrides: kidz/woocommerce/archive-product.php
kidz/woocommerce/cart/cart-empty.php
kidz-child/woocommerce/cart/cart-shipping.php
kidz/woocommerce/cart/cart-totals.php
kidz/woocommerce/cart/cart.php
kidz/woocommerce/cart/proceed-to-checkout-button.php
kidz/woocommerce/cart/shipping-calculator.php
kidz/woocommerce/checkout/form-billing.php
kidz/woocommerce/checkout/form-checkout.php
kidz/woocommerce/checkout/form-coupon.php
kidz/woocommerce/checkout/form-shipping.php
kidz/woocommerce/checkout/payment-method.php
kidz/woocommerce/checkout/payment.php
kidz/woocommerce/checkout/review-order.php
kidz/woocommerce/checkout/terms.php
kidz/woocommerce/checkout/thankyou.php
kidz/woocommerce/content-product.php
kidz/woocommerce/content-product_cat.php
kidz/woocommerce/content-single-product.php
kidz/woocommerce/global/form-login.php
kidz/woocommerce/global/sidebar.php
kidz/woocommerce/global/wrapper-end.php
kidz/woocommerce/global/wrapper-start.php
kidz/woocommerce/loop/add-to-cart.php
kidz/woocommerce/loop/loop-end.php
kidz/woocommerce/loop/orderby.php
kidz/woocommerce/loop/result-count.php
kidz/woocommerce/loop/sale-flash.php
kidz/woocommerce/myaccount/dashboard.php
kidz/woocommerce/myaccount/downloads.php
kidz/woocommerce/myaccount/form-login.php
kidz/woocommerce/myaccount/my-account.php
kidz/woocommerce/myaccount/my-address.php
kidz/woocommerce/myaccount/navigation.php
kidz/woocommerce/myaccount/orders.php
kidz/woocommerce/order/order-details-customer.php
kidz/woocommerce/product-searchform.php
kidz/woocommerce/single-product/add-to-cart/grouped.php
kidz/woocommerce/single-product/add-to-cart/variable.php
kidz/woocommerce/single-product/product-image.php
kidz/woocommerce/single-product/product-thumbnails.php
kidz/woocommerce/single-product/sale-flash.php
kidz/woocommerce/single-product/tabs/additional-information.php
kidz/woocommerce/single-product/tabs/tabs.php
kidz/woocommerce/single-product/title.php
kidz/woocommerce/single-product.php

`
</details>

**Comment by claudiulodro** [comment]
Hi there,

We can only investigate issues with the core WooCommerce plugin here and not with third-party WooCommerce plugins. You will have to contact the author of the WooCommerce Brand plugin and make them aware of this issue.

Thanks.

**Comment by rocketeer76** [comment]
Active Products Filter widget is part of core.

**Comment by claudiulodro** [comment]
Active Products Filter widget is part of core and works correctly with all the core features. If a plugin like WooCommerce Brand adds new features it is on the plugin author to make sure those features work correctly with WooCommerce. Hope this clears things up.
