### ISSUE TITLE
Plugin's tax_queries are being overwritten by category search

### ISSUE THREAD

**Issue by stromhalm** [woocommerce/woocommerce#20914]
**Describe the bug**
As a plugin author I'm using the ``woocommerce_rest_product_object_query`` filter to add an additional argument to the REST products endpoint (which later triggers a tax_query). This works fine as long as the default ``category`` argument is not used at the same time, because this overwrites all ``tax_query``s and the plugins ``tax_query``s are no longer applied.

**To Reproduce**
This is a simplified plugin function that allows to specify tags of products that should **not** be returned by the REST endpoint.
```
add_filter('woocommerce_rest_product_object_query', 'add_negative_tags', 10, 2);

function add_negative_tags($args, $request) {
    if ($request->get_param('not_tags')) {
        $args['tax_query'][] =
            array(
                'taxonomy' => 'product_tag',
                'field'    => 'slug',
                'terms'    => $request->get_param('not_tags'),
                'operator' => 'NOT IN'
            );
    }
    return $args;
}
```
This works fine as long as the ``category`` argument is not used at the same time.

**Expected behavior**
The ``WC_REST_Products_Controller`` should merge it's own ``tax_query`` with the ``tax_query`` from plugins to respect arguments added by plugins.
At the moment I don't see any other way to allow this plugin functionality.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

I will submit a pull request for review.

**Comment by claudiulodro** [comment]
See #20915
