### ISSUE TITLE
Non based location price for VAT exempt clients.

### ISSUE THREAD

**Issue by mariusmateoc** [woocommerce/woocommerce#20911]
**Describe the bug**
The price that is showing on the product with `{price_excluding_tax}` is not the same on cart subtotal/total for clients that are VAT exempt when using the following filter:
```
add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false' )
```
See screenshoots for more informations.

**To Reproduce**
- All the country rates at 19% tax rate and change only the VAT for Austria(or any other country) to 20%.
- Use this filter to show the same price for different location based customers
```
add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false' )
```

Germanized Plugin Option (I think this will happen with any vat exempt plugin)
And check the option **VAT Check Login** - VAT Check Login Remove VAT for users with valid VAT ID after login. I also added a price suffix to WooCommerce for information: `Including Tax: {price_including_tax} Excluding Tax: {price_excluding_tax}`

**Screenshots**
1. Regular Client from Germany, Spain, France, etc sees this which is right:
![image](https://user-images.githubusercontent.com/2094443/43124953-eb9d0160-8f28-11e8-9eb5-9966edf5108c.png)

2. Regular Client from Austria sees this which is right, same price but a 20% VAT.
![image](https://user-images.githubusercontent.com/2094443/43126021-da5a1430-8f2b-11e8-9dd3-0aed3f16ca43.png)

3. Business Client (that has valid VAT ID) from Austria sees this which is right:
![image](https://user-images.githubusercontent.com/2094443/43126155-39e50cd4-8f2c-11e8-9ff2-cf9675ab2170.png)

4. **Problem** is when a business client (with valid VAT ID) adds the product to the cart and subtotal is showing like he adds a product that has reduced a 19% VAT and not 20% VAT as it should and what the client expected when adding the product to the cart.
![image](https://user-images.githubusercontent.com/2094443/43126418-f443f608-8f2c-11e8-9d8d-f80d6ef4f853.png)

I think the issue is related to [this part](https://github.com/woocommerce/woocommerce/blob/424956c6f642242e12928490e0f8a76154a05ca9/includes/class-wc-cart-totals.php#L680-L684) should check if these features are on at the same time and calculate the right price based on those options:
```
if ( $this->cart->get_customer()->get_is_vat_exempt() ) {
    $item = $this->remove_item_base_taxes( $item );
} elseif ( apply_filters( 'woocommerce_adjust_non_base_location_prices', true ) ) {
    $item = $this->adjust_non_base_location_price( $item );
}
```

**Expected behavior**
When single product for a client with VAT exempt is added to the cart, the subtotal for cart should be the same as the total for that particular item.  *(see last screenshot)*

**Isolating the problem:**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- I use two plugins to be able to remove the VAT ID for clients with a valid VAT ID: [Germanized](https://github.com/vendidero/woocommerce-germanized) and Germanized Pro
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: https://example.test
Site URL: https://example.test/wp
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.0
PHP Version: 7.2.7-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 32 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.16-MariaDB-10.2.16+maria~xenial
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.69MB
Database Data Size: 1.79MB
Database Index Size: 0.90MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.09MB + Index: 0.05MB
wp_postmeta: Data: 0.09MB + Index: 0.06MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 16
customize_changeset: 1
page: 14
post: 2
product: 14
product_variation: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

WooCommerce Germanized Pro: by Vendidero – 1.9.3
WooCommerce Germanized: by Vendidero – 2.0.4
WooCommerce: by Automattic – 3.4.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #42 - /terms/

### Theme ###

Name: Storefront
Version: 2.3.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22347
