### ISSUE TITLE
Cancelled order but payment has gone through to PayPal.

### ISSUE THREAD

**Issue by Lippiun** [woocommerce/woocommerce#20928]
Hi, 

On one of my clients website, an order was placed on the weekend but he didn't get a order confirmation from Woo commerce, however PayPal emailed saying that the payment had gone through successfully. 

He checked the orders page and the order has been set to cancelled with this note: Unpaid order cancelled – time limit reached. Order status changed from Pending payment to Cancelled.

After ringing the customer, the customer didn't cancel and wanted the products ordered.

Why is Woocommerce setting this to cancelled when it wasn't? This is the first time this has happened so i'm confused.. 

Can anyone help please?

**Comment by davidsivocha** [comment]
Reporting the same issue here. Received order confirmation through payment gateway, Order status was set to processing by the payment gateway, and then it switched to cancelled.

**Comment by willgorham** [comment]
I also ran into this recently (using Stripe gateway). The payment was processed successfully in Stripe, but it looks like WC never handled or received the confirmation correctly so the payment remained pending and then was cancelled. Nothing in the order notes, no PHP errors, and nothing in Stripe logs to indicate anything unusual.

<img width="313" alt="screen shot 2018-07-31 at 10 08 28 am" src="https://user-images.githubusercontent.com/1883584/43464803-f38c8b44-94a9-11e8-842f-695f591fd8dd.png">

**Comment by kloon** [comment]
Please read the docs for PayPal to understand why this is happening, especially the section around [why orders stay pending after payment](https://docs.woocommerce.com/document/paypal-standard/#section-14).

In short you have an issue with the PayPal IPN communicating with your site, for details on troubleshooting and fixing it please see https://docs.woocommerce.com/document/paypal-standard/#section-14

**Comment by Lippiun** [comment]
Thanks @kloon. I actually discovered more about this issue by searching on the internet and found  a lot others have been experiencing the same since updating to Woocommerce 2.0 and above. The way to fix this is to remove the default value in the 'hold stock' field. However, this has only since become an issue on my website so I'm not sure why or what the issue is.

**Comment by kloon** [comment]
It is possible that your host could have introduced a new firewall rule or made some changes on their side that is blocking IPN requests causing the order to get stuck. Simply removing the hold stock value will not solve the issue as your orders will still get stuck in pending which is should not be once paid.

**Comment by kloon** [comment]
Go through the debugging IPN issues in the link I posted above and it should guide you on where to look and what to look out for. You are also welcome to contact support for assistance with this if you do not come right. https://woocommerce.com/contact-us/
