### ISSUE TITLE
Cannot Update/Save Changes Category

### ISSUE THREAD

**Issue by lienbao98** [woocommerce/woocommerce#20929]
When i edit Category, i can't press the "Cập nhật"(Update) button, it wasn't response, nothing happened and i never able to make changes. Only if i use "Sửa nhanh" (Quick edit?)

Screenshot: 
![image](https://user-images.githubusercontent.com/41899213/43391263-6af95a94-941a-11e8-971b-2f9d4cc2bd05.png)

**Comment by rodrigoprimo** [comment]
I'm sorry but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce).

If you believe you found a WooCommerce bug, please reopen this issue and provide the steps to reproduce it on a clean WooCommerce install and a copy of your system status report as requested in the bug report template.

Thanks
