### ISSUE TITLE
Cannot get to the State Field drop down box

### ISSUE THREAD

**Issue by ballj35** [woocommerce/woocommerce#20933]
**Describe the bug**
This happens infrequently and not all the time.  When it does happen, then the client is hitting
the ceiling about this issue.  Stating he is losing business because his customers cannot enter
the State for their order. 

**To Reproduce**
1. Go to 'Buy Now' from the Home Page.
2. Click on 'Add To Cart' for 1 Quick Boat Fender
3. Click on 'Proceed to Checkout'
4. Place the cursor on the State Field.

**Screenshots**
N/A

**Expected behavior**
The cursor should always go the State Field.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

- [X] I have done many things and have never been able to reproduce this problem.  Yet, the client
will call me telling this has happened and is very irate with me.

**WordPress Environment**
3.4.4

```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
see attachments
![wp_1](https://user-images.githubusercontent.com/12303525/43429070-83a18e8a-942f-11e8-8cd6-9797cc42b08e.JPG)
![wp_2](https://user-images.githubusercontent.com/12303525/43429071-83b48846-942f-11e8-812f-0ee6d2bfc175.JPG)
![wp_3](https://user-images.githubusercontent.com/12303525/43429072-83c54726-942f-11e8-94b3-486681780d27.JPG)
![wp_4](https://user-images.githubusercontent.com/12303525/43429073-83d40e14-942f-11e8-95ad-8b8711da67d4.JPG)
![wp_5](https://user-images.githubusercontent.com/12303525/43429074-83f0d936-942f-11e8-8e1c-4a16684869cb.JPG)
![wp_7](https://user-images.githubusercontent.com/12303525/43429075-8400e24a-942f-11e8-8686-46d62df67ca0.JPG)
![wp_8](https://user-images.githubusercontent.com/12303525/43429076-840fb720-942f-11e8-8ba7-3c0bd5d8f2f1.JPG)
![wp_10](https://user-images.githubusercontent.com/12303525/43429077-84226f96-942f-11e8-830d-eab87873a05c.JPG)
![wp_11](https://user-images.githubusercontent.com/12303525/43429079-8433c598-942f-11e8-8cf1-fccaa5b3fb90.JPG)
![wp_12](https://user-images.githubusercontent.com/12303525/43429080-844abc12-942f-11e8-886b-6040f450a0e9.JPG)
![wp_13](https://user-images.githubusercontent.com/12303525/43429081-845a3412-942f-11e8-8dba-98cd9623c77d.JPG)

</details>

**Comment by peterfabian** [comment]
@ballj35 Do you by any chance have any more info, e.g. if it happens for customers in certain states/new or returning customers/logged in or guest checkout/customers with certain browsers or something else? As you say, it's difficult to reproduce, so additional info might help us find out where the problem is.

**Comment by claudiulodro** [comment]
Hi there.

This is going to be a theme issue. 

You're using an outdated 3-year old version of the Magnium theme with templates that haven't been updated for the latest versions of WooCommerce. Additionally, that theme is going to be set up for an old version of select2 that was deprecated in WooCommerce 3.0, and that is likely the source of any State dropdown issues.

I recommend updating to the latest version of your theme, and if that does not solve the problem I recommend finding a theme with WooCommerce 3.0 compatibility (as the latest version of Magnium from last year only appears to have WooCommerce 2.6 compatibility).

Hope this helps. Thanks.

**Comment by ballj35** [comment]
The only information he had is that the user was using Chrome as the browser.  The next time it happens, he is going to collect more information.
