### ISSUE TITLE
Products shortcode default product count output

### ISSUE THREAD

**Issue by JimmyAppelt** [woocommerce/woocommerce#20935]
**Describe the bug**
Shortcode `[products]` outputs all products instead of 12 by default

Env: WC 3.4.4

**Expected behavior**
Output 12 by default as described in the docs 
https://docs.woocommerce.com/document/woocommerce-shortcodes/#display-product-attributes

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).

**Comment by rodrigoprimo** [comment]
The documentation is incorrect and the default behavior of the `[products]` shortcode is to list all products by default:

https://github.com/woocommerce/woocommerce/blob/082c1dfaf3cb66d429546b2ca684c86688b028e8/includes/shortcodes/class-wc-shortcode-products.php#L115

@californiakat, could you please update the docs?

cc @claudiosanches as you created the new version of the products shortcode in case I missed something.

**Comment by claudiosanches** [comment]
Defaults to `-1` to backwards compatibility.

**Comment by JimmyAppelt** [comment]
@rodrigoprimo welcome 🙂  -1 it is then
