### ISSUE TITLE
Misspelling in error message when the cart is empty

### ISSUE THREAD

**Issue by ballj35** [woocommerce/woocommerce#20932]
**Describe the bug**
When I click on Checkout and there is nothing in my cart, I get the following message:

Checkout is not available whilst your cart is empty.

The word **"whilst"** should be **"while"**.

**To Reproduce**
1. Go to 'Cart'
2. Click on 'Check Out'
3. See error

**Screenshots**
See above

**Expected behavior**
The message to be spelled correctly.

**Isolating the problem (mark completed items with an [x]):**

**WordPress Environment**
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```

**Comment by claudiulodro** [comment]
Hi there,

"Whilst" is a correct spelling and means the same thing as "while" in that context. [You can read more about it here](https://dictionary.cambridge.org/us/grammar/british-grammar/linking-words-and-expressions/while-and-whilst).

If necessary you can do a custom translation to change that line to whatever you want on your installation of WooCommerce. [Here is the guide for that](https://docs.woocommerce.com/document/woocommerce-localization/#section-5).

Thanks.
