### ISSUE TITLE
Cart gets loaded during REST requests

### ISSUE THREAD

**Issue by javorszky** [woocommerce/woocommerce#20937]
Cart gets loaded via `get_cart_from_session`, which is hooked into `wp_loaded`.

The `REST_REQUEST` constant is only available from `rest_api_init` hook, which is later than `wp_loaded`. This means that for every REST request, all plugins that interact with the cart will also be loaded, which slows down processing. An example is account funds.

**To Reproduce**
1. Add debugging code / xdebug breakpoint into `WC_Cart::get_cart_from_session`
2. Send a REST request to the site updating a product or something similar
3. See that the breakpoint triggered / debugging code executed

**Expected behavior**
Cart should not load for REST requests automatically as it's supposed to be stateless.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

WordPress 4.9.7
WooCommerce 3.4.4
PHP 7.1.20

**Comment by claudiulodro** [comment]
Good find. Thanks for letting us know.

We'll need to investigate the backwards-compatibility (and regular compatibility :P) of moving the cart init to a later hook compared to the performance tradeoff.

**Comment by rodrigoprimo** [comment]
While investigating ways to fix this issue, I found issue #19983 which describes exactly the same problem that is described in this issue and was closed by PR #20000. But, as far as I can test, the solution implemented in #20000 doesn't work because of the problem that @javorszky described here, `REST_REQUEST` is defined too late to be used to decide whether or not to load cart data (cc @claudiosanches as you reviewed #20000 in case I'm missing something). I will further investigate and I'm open to ideas on how to address this.

Ps: please ignore the two commits listed above. I created them to test an idea but quickly found that it doesn't work, and I assumed that removing the branch would remove the reference here which is not the case.

**Comment by peterfabian** [comment]
Maybe we could do something like #21090?

Needless to say, I don't think we should spend too much time on this, the performance difference is so small that it's not even displayed in profiler unless I specifically check for the function.

**Comment by javorszky** [comment]
> Needless to say, I don't think we should spend too much time on this, the performance difference is so small that it's not even displayed in profiler unless I specifically check for the function.

I'm glad that on an empty site the difference is small for you, but the reason I've opened this issue is because on large sites where there are a fair bit of customizations to how the cart works, this can be very substantial. Not because of loading the cart itself, but because of other things that hook into that action.

Like account funds.

I'll check out #21090 later on the weekend though, from a cursory glance, it looks okay, and would work.

**Comment by javorszky** [comment]
#21090 only disables getting the cart on WC REST routes, and I think it should not load the cart on ANY cart routes.

One thing to note is that `rest_api_loaded`, where the `REST_REQUEST` constant is defined is hooked into `parse_request@10`, which is pretty much the next global action after `wp_loaded`.

Would it be feasible to move fetching the cart from session to `parse_request@11` or later, and move everything else to then as well?

This is what I've found WC uses `wp_loaded` for:

```
Searching 846 files for "wp_loaded"

/Users/javorszky/Sites/dev/wp-content/plugins/woocommerce/includes/class-wc-cart-session.php:
   45  	 */
   46  	public function init() {
   47: 		add_action( 'wp_loaded', array( $this, 'get_cart_from_session' ) );
   48  		add_action( 'woocommerce_cart_emptied', array( $this, 'destroy_cart_session' ) );
   49  		add_action( 'wp', array( $this, 'maybe_set_cart_cookies' ), 99 );
   ..
  163  	 */
  164  	public function maybe_set_cart_cookies() {
  165: 		if ( ! headers_sent() && did_action( 'wp_loaded' ) ) {
  166  			if ( ! $this->cart->is_empty() ) {
  167  				$this->set_cart_cookies( true );

/Users/javorszky/Sites/dev/wp-content/plugins/woocommerce/includes/class-wc-cart.php:
  601  	 */
  602  	public function get_cart() {
  603: 		if ( ! did_action( 'wp_loaded' ) ) {
  604: 			wc_doing_it_wrong( __FUNCTION__, __( 'Get cart should not be called before the wp_loaded action.', 'woocommerce' ), '2.3' );
  605  		}
  606  		if ( ! did_action( 'woocommerce_cart_loaded_from_session' ) ) {

/Users/javorszky/Sites/dev/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php:
   23  		add_action( 'template_redirect', array( __CLASS__, 'save_address' ) );
   24  		add_action( 'template_redirect', array( __CLASS__, 'save_account_details' ) );
   25: 		add_action( 'wp_loaded', array( __CLASS__, 'checkout_action' ), 20 );
   26: 		add_action( 'wp_loaded', array( __CLASS__, 'process_login' ), 20 );
   27: 		add_action( 'wp_loaded', array( __CLASS__, 'process_registration' ), 20 );
   28: 		add_action( 'wp_loaded', array( __CLASS__, 'process_lost_password' ), 20 );
   29: 		add_action( 'wp_loaded', array( __CLASS__, 'process_reset_password' ), 20 );
   30: 		add_action( 'wp_loaded', array( __CLASS__, 'cancel_order' ), 20 );
   31: 		add_action( 'wp_loaded', array( __CLASS__, 'order_again' ), 20 );
   32: 		add_action( 'wp_loaded', array( __CLASS__, 'update_cart_action' ), 20 );
   33: 		add_action( 'wp_loaded', array( __CLASS__, 'add_to_cart_action' ), 20 );
   34  
   35  		// May need $wp global to access query vars.

/Users/javorszky/Sites/dev/wp-content/plugins/woocommerce/includes/class-wc-query.php:
   41  		add_action( 'init', array( $this, 'add_endpoints' ) );
   42  		if ( ! is_admin() ) {
   43: 			add_action( 'wp_loaded', array( $this, 'get_errors' ), 20 );
   44  			add_filter( 'query_vars', array( $this, 'add_query_vars' ), 0 );
   45  			add_action( 'parse_request', array( $this, 'parse_request' ), 0 );

/Users/javorszky/Sites/dev/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-notices.php:
   46  		add_action( 'switch_theme', array( __CLASS__, 'reset_admin_notices' ) );
   47  		add_action( 'woocommerce_installed', array( __CLASS__, 'reset_admin_notices' ) );
   48: 		add_action( 'wp_loaded', array( __CLASS__, 'hide_notices' ) );
   49  		add_action( 'shutdown', array( __CLASS__, 'store_notices' ) );
   50  

15 matches across 5 files
```

**Comment by peterfabian** [comment]
> I'm glad that on an empty site the difference is small for you, but the reason I've opened this issue is because on large sites where there are a fair bit of customizations to how the cart works, this can be very substantial. Not because of loading the cart itself, but because of other things that hook into that action.

> Like account funds.

Thanks for the explanation, I haven't thought about that. I learn something new every day...

> #21090 only disables getting the cart on WC REST routes, and I think it should not load the cart on ANY cart routes.

I'm not super-familiar with all the dependencies, but in a cursory test, #21105 seems to work.

**Comment by mikejolley** [comment]
@peterfabian let's hold off for https://core.trac.wordpress.org/ticket/42061 - a function in core would allow us to resolve this without breaking backwards compatibility adjusting hooks. wp_loaded is still a good time for us to process logic as soon as possible before headers are sent etc.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/21090#pullrequestreview-204280173
