### ISSUE TITLE
Wrap Notice Text With HTML

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#20945]
Hi guys,

Is it possible to wrap text inside notice message (woocommerce-info, woocommerce-error etc) with span or p or something else? I think it will be good feature for css manipulation and we be able to create unique and interactive layout and much more then now. 

Best regards,
Nenad

**Comment by spencerfinnell** [comment]
Related https://github.com/woocommerce/woocommerce/pull/18533

**Comment by claudiulodro** [comment]
Yeah makes sense to do this as part of #18533.

Nenad, this change will likely be in WooCommerce 4.0.
