### ISSUE TITLE
Potential Issues

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#20943]
Hi guys,

Could you please check these potential issues?

1. Undefined constant **WC_ABSPATH** on several places 
- abstract-wc-csv-batch-exporter.php
- abstract-wc-order.php
- abstract-wc-payment-token.php
- abstract-wc-product.php
- class-wc-admin-exporters.php

2. templates\single-product\share.php - Unnecessary close and open php tag

3. includes\class-wc-regenerate-images.php - find this conditional **if ( ! self::image_size_matches_settings( $data, $size ) ) {** and inside it there is unnecessary **return false;** code because there is already if else statement and you can't get that case.

4. includes\gateways\simplify\commerce\includes\Simplify\PaymentsApi.php - inside this function **public function getUrl($publicKey, $action, $object)**  you have unnecessary case **elseif ($action == "create") {** 

5. includes\gateways\paypal\includes\class-wc-gateway-paypal-request.php on 4 places you used + mark to concatenate strings instead od dot mark, example $shipping_total += $order->get_shipping_tax();

Best regards,
Nenad

**Comment by claudiulodro** [comment]
Hi Nenad,

1. `WC_ABSPATH` gets defined [right when WooCommerce is loaded](https://github.com/woocommerce/woocommerce/blob/8cde592c54bfeb40b4286e2f70aa42bf11121e76/includes/class-woocommerce.php#L205) and should always be available to all WooCommerce classes.

2. Yes. Good find. No reason to close and then open the PHP tags in that template.

3. Yes, [this line](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-regenerate-images.php#L91) will never be reached.

4. Yes, this is true. However, that whole folder is a third-party library developed by MasterCard and the version included in WooCommerce core [has been deprecated](https://docs.woocommerce.com/document/simplify-commerce/). No reason to update it at this point.

5. `$shipping_total += $order->get_shipping_tax()` is performing mathematic addition and not string concatenation.

Good finds. Thanks! Happy to review pull requests for any of these.

**Comment by claudiulodro** [comment]
For reference, the points mentioned in 2 and 3 are the ones that should be made better.

**Comment by NenadObradovic** [comment]
Hi Claudiulodro,

1 and 5. My mistake, thanks for explanation :)

Best regards,
Nenad

**Comment by claudiulodro** [comment]
See #20982
