### ISSUE TITLE
Improve On Sale Mark

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#20946]
Hi guys,

What you think about improving on sale mark with additional functions and feature where we can choose between Sale label and percentage mark. For example instead of this code below (you have the same code in two places)
```
<?php if ( $product->is_on_sale() ) : ?>

	<?php echo apply_filters( 'woocommerce_sale_flash', '<span class="onsale">' . esc_html__( 'Sale!', 'woocommerce' ) . '</span>', $post, $product ); ?>

<?php endif;
```

to be one function, example
`
woocommerce_get_on_sale( $post, $product );
`

and content of that function will be

```
if ( ! function_exists( "woocommerce_get_on_sale" ) ) {
	function woocommerce_get_on_sale( $post, $product ) {
		
		if ( $product->is_on_sale() ) {
			echo woocommerce_get_sale_label( $post, $product );
		}
	}
}
```

```
if ( ! function_exists( 'woocommerce_get_sale_label' ) ) {
	/**
	 * @param $enable_percent_mark to be throw WooCommerce option 
	 */
	function woocommerce_get_sale_label( $post, $product ) {
		$regular_price       = intval( $product->get_regular_price() );
		$sale_price          = intval( $product->get_sale_price() );
		$sale_label          = $regular_price > 0 && $enable_percent_mark === 'yes' ? '-' . ( 100 - round( ( $sale_price * 100 ) / $regular_price ) ) . '%' : esc_html__( 'Sale', 'woocommerce' );
		
		return apply_filters( 'woocommerce_sale_flash', '<span class="onsale">' . $sale_label . '</span>', $post, $product );
	}
}
```

Best regards,
Nenad

**Comment by claudiulodro** [comment]
Hi Nenad,

As a theme developer you can use the filter if you want to modify all sale labels or a template override if you want to modify just the sale labels for the loop/single. That seems very flexible. What is the advantage of the change you propose?

**Comment by claudiulodro** [comment]
Thanks for the suggestions Nenad,
I do not think we will be implementing this one since there doesn't seem to be an advantage.
