### ISSUE TITLE
Address Title Class Name

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#20947]
Hi guys,

Is it possible to add same class name for address titles (Billing address and Shipping address) in Checkout -> Order Received, My Account -> View Order, My Account -> Edit Address and My Account -> Edit Address -> Billing pages for example **woocommerce-Address-title** or something else? Because all titles are same also title tag are same (h3), for better and easily css customization. Thanks for your time

Best regards,
Nenad

**Comment by claudiulodro** [comment]
Hi Nenad,

I have the same comments here as I do on [this other issue you opened](https://github.com/woocommerce/woocommerce/issues/20938#issuecomment-409350883).

Thanks.

**Comment by NenadObradovic** [comment]
Hi Claudiulodro,

I didn't explain it nicely. Here I mean classes on the title tags <h3>Biling Address</h3> for example, because headings doesn't have any class name and we need to style it with h3 selector and to set the same style for these items on several pages (checkout, my account etc) because of that I think it will be helpful that there is some class for all of them.

Best regards,
Nenad
