### ISSUE TITLE
How to add a woocommerce hook function for when coupon code is denied in cart for some reason for product tag

### ISSUE THREAD

**Issue by uchandra** [woocommerce/woocommerce#20941]
How to add a woocommerce hook function for when coupon code is denied in cart for some reason which applied based on product tag.

**Comment by rodrigoprimo** [comment]
I'm sorry but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce).

If I misunderstood your issue, please reopen it providing the information requested in the appropriate issue template (you can find all the available options in this link https://github.com/woocommerce/woocommerce/issues/new/choose).

Thanks
