### ISSUE TITLE
adding users information in order

### ISSUE THREAD

**Issue by jahani20** [woocommerce/woocommerce#20952]
adding users information in order to having legal information for our customers on check out page as ( order to be shipped to another address )  sending orders list to another address.and add 9%VAT to total amount.

**Comment by kloon** [comment]
@jahani20 not sure what you are after. If you require assistance with setting up your store to allow for collection of additional user information then (please contact support)[https://woocommerce.com/contact-us/] this page is only for reporting bug in WooCommerce core.
