### ISSUE TITLE
scrollIntoView compatibility error on checkout Firefox 52

### ISSUE THREAD

**Issue by vendidero** [woocommerce/woocommerce#20951]
This bug is an incompatibility with older FF versions (e.g. 52.7.2) which do not support the `block` parameter within scrollIntoView: 
https://github.com/woocommerce/woocommerce/blob/deb48c7c7a0a87e816b7ad6963676a17117cca1b/assets/js/frontend/woocommerce.js#L73-L76

The following bug is being thrown:

`TypeError: 'block' member of ScrollIntoViewOptions 'center' is not a valid value for enumeration ScrollLogicalPosition.`

**To Reproduce**
1. Install FF version 52.7.2
2. Go to the Woo checkout
3. Make sure an input error exists
4. See the console within FF webdeveloper tools

Guess we need a further (version) check here..

Cheers

**Comment by peterfabian** [comment]
See #20992.
