### ISSUE TITLE
Product name appears incorrect in order list which it with % sign in name

### ISSUE THREAD

**Issue by eren-korkmaz** [woocommerce/woocommerce#20959]
**Describe**
Product name appears incorrect in order detail after purchasing products with % sign in name. it remove % sign. "Product %100 good" changes to ""Product 0 good""

**To Reproduce**
1. Create a product and give a name like "**product %100 good**" ( name must contains "%100" ) 
2. Go site and add product to cart, and buy it.
3. Go my account page and click my orders and check product name
4. See error -> product name changed like "**product 0 good**"

**Screenshots**
https://pasteboard.co/HxhnmwY.png

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

`
### WordPress Environment ###

Home URL: http://localhost/wootest
Site URL: http://localhost/wootest
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: tr_TR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.23 (Win64) PHP/7.0.10
PHP Version: 7.0.10 - Daha iyi performans ve daha gelişmiş güvenlik için PHP'nin 7.2 veya daha yeni bir sürümünü kullanmanız önerilir. PHP sürümünüz nasıl güncellenir?
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.50.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Toplam veritabanı boyutu: 0.87MB
Veritabanı veri boyutu: 0.75MB
Veritabanı indis boyutu: 0.12MB
wp_woocommerce_sessions: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_api_keys: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_attribute_taxonomies: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_downloadable_product_permissions: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_order_items: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_order_itemmeta: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_tax_rates: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_tax_rate_locations: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_shipping_zones: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_shipping_zone_locations: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_shipping_zone_methods: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_payment_tokens: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_payment_tokenmeta: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_log: Veri: 0.00MB + İndis: 0.00MB
wp_commentmeta: Veri: 0.00MB + İndis: 0.00MB
wp_comments: Veri: 0.00MB + İndis: 0.01MB
wp_failed_jobs: Veri: 0.00MB + İndis: 0.00MB
wp_links: Veri: 0.00MB + İndis: 0.00MB
wp_mailchimp_carts: Veri: 0.00MB + İndis: 0.00MB
wp_options: Veri: 0.68MB + İndis: 0.03MB
wp_postmeta: Veri: 0.05MB + İndis: 0.03MB
wp_posts: Veri: 0.02MB + İndis: 0.01MB
wp_queue: Veri: 0.00MB + İndis: 0.00MB
wp_termmeta: Veri: 0.00MB + İndis: 0.01MB
wp_terms: Veri: 0.00MB + İndis: 0.01MB
wp_term_relationships: Veri: 0.00MB + İndis: 0.00MB
wp_term_taxonomy: Veri: 0.00MB + İndis: 0.00MB
wp_usermeta: Veri: 0.00MB + İndis: 0.01MB
wp_users: Veri: 0.00MB + İndis: 0.01MB
wp_wc_download_log: Veri: 0.00MB + İndis: 0.00MB
wp_wc_webhooks: Veri: 0.00MB + İndis: 0.00MB

### Post Type Counts ###

attachment: 17
customize_changeset: 1
page: 10
post: 2
product: 13
revision: 7
shop_order: 3

### Security ###

Secure connection (HTTPS): ❌
					Mağazanız HTTPS kullanmıyor. HTTPS and SSL sertifikaları hakkında bilgi alın.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: (Automattic) – 3.4.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Mağaza giriş sayfası: #5 - /magaza/
Sepet sayfası: #6 - /sepet/
Ödeme sayfası: #7 - /odeme/
Hesabım sayfası: #8 - /hesabim/
Şartlar ve koşullar: ❌ Sayfa ayarlanmamış

### Theme ###

Name: Storefront
Version: 2.3.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – WooCommerce'i kendinizin oluşturmadığı ana bir temada düzenliyorsanız
yardımcı bir tema kullanmanızı öneririz. Bkz.: Nasıl yardımcı tema oluşturulur?

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

</details>

**Comment by peterfabian** [comment]
This one might need a bit more thought. 

The %10 is removed because all octets are getting removed from a lot of strings in WooCommerce by function `wc_clean` that runs `sanitize_text_field`. 

This particular instance is called from `WC_Order_Item::set_name`. As the CRUD methods use `wp_insert_post` which escapes its parameters, I would say `wc_clean` is a bit unnecessary and creates these side effects. 

Situation is similar for `wc_save_order_items` used in other contexts when updating order items: it calls `wc_clean` on a bunch of fields, and then uses `$wpdb->update/create` which escapes the values.

I see `wc_clean` being used all over the place, sometimes where it might be even more frustrating for the user, like `WC_Customer::set_password` and `get_posted_data` that is used while creating user account during checkout. Then, a password like `abc%100_123456` gets changed to `abc0_123456` without the user knowing about it...

My proposal would be to remove wc_clean from these places, but let's wait if someone else has some background info and maybe there is a reason behind this.

**Comment by peterfabian** [comment]
See #20993.
