### ISSUE TITLE
Shipping details not showing sometimes in "Quick view"

### ISSUE THREAD

**Issue by GAPP99** [woocommerce/woocommerce#20958]
**Describe the bug**
As you know in WooCommerce, it's only possible for one user at a time to edit/visit a specific order. So we've found that sometimes the "Quick view" function is nice because it lets us check if there's an error in the address, email, phone, etc. if a customer wants to modify their details or similar.

One issue I noticed recently was that sometimes the Shipping details are not shown, but only the Billing details. It does not seem to be something that happens often, but it's definitely a bug, as the Shipping details are shown if you click on the order specifically. I've checked and it's not because the Billing- and Shipping details are identical, it just doesn't show it for some orders in Quick View.

**To Reproduce**
1. Go to the WooCommerce order menu, so you're now looking at all the Orders.
2. Click on the little "eye icon" next to the name of the order you'd like to look at.
3. In most cases, it will show correctly here, but sometimes it will not show correctly.

**Screenshots**
Here's a screenshot of how a regular order looks from inside first, and then from Quick View:
Inside the order:
Inside: http://prntscr.com/kdps2r
Quick View: http://prntscr.com/kdpse8

And here's a screenshot of the one that does not show, both from inside it and then from Quick View:
Inside: http://prntscr.com/kdpsj5
Quick View (The error): http://prntscr.com/kdpsr3

**Expected behavior**
Quick View is suppose to display the Shipping details on right hand side, just as with any other orders.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

Home URL: ****
Site URL: ****
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.2
PHP Version: 7.2.8-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB-1~xenial
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔ 1 active Zapier Feed.
Zapier Integration - Cron Tasks: ✔ 0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔ WooCommerce Purchase
Zapier Feed #1 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/1858631/abpqjl/
Zapier Feed #1 Trigger: ✔ New Order
Zapier Feed #1 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/1858631/abpqjl/.

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wp_a5edeb6152_
MaxMind GeoIP Database: ✔
Total Database Size: 92.60MB
Database Data Size: 70.41MB
Database Index Size: 22.19MB
wp_a5edeb6152_woocommerce_sessions: Data: 6.02MB + Index: 0.06MB
wp_a5edeb6152_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_a5edeb6152_woocommerce_order_items: Data: 0.20MB + Index: 0.09MB
wp_a5edeb6152_woocommerce_order_itemmeta: Data: 3.52MB + Index: 3.02MB
wp_a5edeb6152_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_a5edeb6152_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB
wp_a5edeb6152_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ip2nation: Data: 2.52MB + Index: 2.52MB
ip2nationCountries: Data: 0.05MB + Index: 0.02MB
wp_a5edeb6152_abandoned_cart_analystic_fb: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_abandoned_cart_shortcode: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_abandoned_cart_statistical: Data: 0.28MB + Index: 0.00MB
wp_a5edeb6152_abandoned_cart_user_add: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB
wp_a5edeb6152_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_affiliate_wp_customermeta: Data: 0.05MB + Index: 0.03MB
wp_a5edeb6152_affiliate_wp_customers: Data: 0.08MB + Index: 0.06MB
wp_a5edeb6152_affiliate_wp_direct_links: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_affiliate_wp_payouts: Data: 0.08MB + Index: 0.02MB
wp_a5edeb6152_affiliate_wp_referrals: Data: 0.22MB + Index: 0.02MB
wp_a5edeb6152_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_affiliate_wp_visits: Data: 3.52MB + Index: 0.47MB
wp_a5edeb6152_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB
wp_a5edeb6152_automatewoo_customers: Data: 0.02MB + Index: 0.06MB
wp_a5edeb6152_automatewoo_events: Data: 0.02MB + Index: 0.05MB
wp_a5edeb6152_automatewoo_guests: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_automatewoo_guest_meta: Data: 0.08MB + Index: 0.06MB
wp_a5edeb6152_automatewoo_logs: Data: 0.05MB + Index: 0.05MB
wp_a5edeb6152_automatewoo_log_meta: Data: 0.11MB + Index: 0.11MB
wp_a5edeb6152_automatewoo_queue: Data: 0.02MB + Index: 0.05MB
wp_a5edeb6152_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB
wp_a5edeb6152_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB
wp_a5edeb6152_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.08MB
wp_a5edeb6152_commentmeta: Data: 0.11MB + Index: 0.06MB
wp_a5edeb6152_comments: Data: 2.50MB + Index: 1.47MB
wp_a5edeb6152_essb3_click_stats: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_gb_ocu_customers: Data: 0.13MB + Index: 0.03MB
wp_a5edeb6152_gb_ocu_funnels: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_ghostmonitor_data: Data: 1.52MB + Index: 0.00MB
wp_a5edeb6152_imagify_files: Data: 0.02MB + Index: 0.08MB
wp_a5edeb6152_imagify_folders: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_links: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_options: Data: 5.20MB + Index: 0.08MB
wp_a5edeb6152_postmeta: Data: 26.17MB + Index: 7.83MB
wp_a5edeb6152_posts: Data: 8.41MB + Index: 0.50MB
wp_a5edeb6152_rg_form: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_a5edeb6152_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_a5edeb6152_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_termmeta: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_terms: Data: 0.08MB + Index: 0.09MB
wp_a5edeb6152_term_relationships: Data: 0.06MB + Index: 0.02MB
wp_a5edeb6152_term_taxonomy: Data: 0.08MB + Index: 0.11MB
wp_a5edeb6152_usermeta: Data: 2.50MB + Index: 2.98MB
wp_a5edeb6152_users: Data: 0.08MB + Index: 0.05MB
wp_a5edeb6152_user_ref_abandoned_cart: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wc_avatars_cache: Data: 0.02MB + Index: 0.09MB
wp_a5edeb6152_wc_comments_subscription: Data: 0.02MB + Index: 0.06MB
wp_a5edeb6152_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_a5edeb6152_wc_follow_users: Data: 0.02MB + Index: 0.13MB
wp_a5edeb6152_wc_phrases: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_wc_users_voted: Data: 0.02MB + Index: 0.06MB
wp_a5edeb6152_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_a5edeb6152_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfConfig: Data: 0.28MB + Index: 0.00MB
wp_a5edeb6152_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfFileMods: Data: 2.52MB + Index: 0.00MB
wp_a5edeb6152_wfHits: Data: 0.44MB + Index: 0.23MB
wp_a5edeb6152_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_wfIssues: Data: 0.05MB + Index: 0.06MB
wp_a5edeb6152_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_a5edeb6152_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfLogins: Data: 0.09MB + Index: 0.03MB
wp_a5edeb6152_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_a5edeb6152_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_a5edeb6152_wfStatus: Data: 0.13MB + Index: 0.09MB
wp_a5edeb6152_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_a5edeb6152_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_a5edeb6152_yoast_seo_links: Data: 0.08MB + Index: 0.02MB
wp_a5edeb6152_yoast_seo_meta: Data: 0.14MB + Index: 0.00MB

### Post Type Counts ###

amn_om: 1
attachment: 515
aw_workflow: 10
custom_css: 1
elementor_library: 95
elementor-popup: 1
nav_menu_item: 15
njt_user_add_to_cart: 253
ocean_modal_window: 2
oceanwp_library: 12
oembed_cache: 23
omapi: 4
page: 38
popup: 1
popup_theme: 6
post: 11
product: 3
pys_fb_event: 6
revision: 45
seopress_404: 229
shop_coupon: 78
shop_order: 963
shop_order_refund: 31
wc_zapier_feed: 1
wpdiscuz_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (51) ###

AffiliateWP - PayPal Payouts: by Pippin Williamson and Andrew Munro – 1.1.11
AffiliateWP: by AffiliateWP
LLC – 2.2.5

AffiliateWP - Affiliate Area Shortcodes: by AffiliateWP
LLC – 1.1.6

AffiliateWP - Affiliate Landing Pages: by AffiliateWP
LLC – 1.0.2

Akismet Anti-Spam: by Automattic – 4.0.8
Checkout Address Autocomplete for WooCommerce: by eCreations – 1.9.7 – Not tested with the active version of WooCommerce
Checkout for WooCommerce: by Objectiv – 1.5.7 – Not tested with the active version of WooCommerce
Disable New User Notifications: by Thomas Griffin – 1.0.2
Google Tag Manager for Wordpress: by Thomas Geiger – 1.8.1
Easy Social Share Buttons for WordPress: by CreoApps – 5.5.2
Elementor Pro: by Elementor.com – 2.0.16
Elementor: by Elementor.com – 2.1.4
WooCommerce 1 Click Upsells & Downsells: by WooCurve – 1.5.2 – Not tested with the active version of WooCommerce
GeoIP Detection: by Yellow Tree (Benjamin Pick) – 2.8.2
GPL Kit: by GPL Kit – 2.0.0
Imagify: by WP Media – 1.8.1
Klaviyo for WooCommerce: by Klaviyo
Inc. – 1.0.4 – Not tested with the active version of WooCommerce

Klaviyo: by Klaviyo – 1.3.2
Ocean Cookie Notice: by OceanWP – 1.0.2
Ocean Custom Sidebar: by OceanWP – 1.0.4
Ocean Elementor Widgets: by OceanWP – 1.1.0-beta.1
Ocean Extra: by OceanWP – 1.4.18
Ocean Hooks: by OceanWP – 1.1.0-beta.1
Ocean Modal Window: by OceanWP – 1.0.13
Ocean Popup Login: by OceanWP – 1.0.2
Ocean Stick Anything: by OceanWP – 1.0.1
Ocean Sticky Header: by OceanWP – 1.1.11
OptinMonster API: by OptinMonster Team – 1.4.2
PixelYourSite PRO: by PixelYourSite – 6.5.3
Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 3.3.9
SendGrid: by SendGrid – 1.11.8
SVG Support: by Benbodhi – 2.3.15
User Shortcodes Plus: by Kyle B. Johnson – 2.0.1
Woo Preview Emails: by Digamber Pradhan – 1.4.0 – Not tested with the active version of WooCommerce
WooCommerce Coupon Links: by Cedaro – 2.2.0 – Not tested with the active version of WooCommerce
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.6 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.7
WooCommerce Help Scout: by WooCommerce – 1.3.9
WooCommerce Mixpanel: by SkyVerge – 1.12.2
WooCommerce Shipment Tracking: by WooCommerce – 1.6.11
WooCommerce Shipping Estimates: by SkyVerge – 2.1.0 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.9
WooCommerce URL Coupons: by SkyVerge – 2.6.2 – 2.7.0 is available
WooCommerce Zapier Integration: by OM4 – 1.7.3 – 1.7.4 is available
WooCommerce: by Automattic – 3.4.3 – 3.4.4 is available
WP Rocket: by WP Media – 3.0.5.1
SEOPress PRO: by Benjamin Denis – 3.0
SEOPress: by Benjamin Denis – 3.0
wpDiscuz - Media Uploader: by gVectors Team (A. Chakhoyan
G. Zakaryan
H. Martirosyan) – 1.3.1

wpDiscuz: by gVectors Team (A. Chakhoyan
G. Zakaryan
H. Martirosyan) – 5.1.4

Refer a Friend for WooCommerce PREMIUM: by WPGens – 2.1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #24 - /shop/
Cart: #25 - /cart/
Checkout: #26 - /checkout/
My account: #27 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: OceanWP Child
Version: 1.0
Author URL: https://oceanwp.org/
Child Theme: ✔
Parent Theme Name: OceanWP
Parent Theme Version: 1.5.20 – 1.5.21 is available
Parent Theme Author URL: https://oceanwp.org/about-me/
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp-child/woocommerce/cart/mini-cart.php
oceanwp-child/woocommerce/checkout/thankyou.php
oceanwp/woocommerce/content-single-product.php
oceanwp-child/woocommerce/emails/admin-cancelled-order.php
oceanwp-child/woocommerce/emails/admin-failed-order.php
oceanwp-child/woocommerce/emails/admin-new-order.php
oceanwp-child/woocommerce/emails/customer-completed-order.php
oceanwp-child/woocommerce/emails/customer-invoice.php version 2.5.0 is out of date. The core version is 3.3.0
oceanwp-child/woocommerce/emails/customer-new-account.php
oceanwp-child/woocommerce/emails/customer-note.php
oceanwp-child/woocommerce/emails/customer-on-hold-order.php
oceanwp-child/woocommerce/emails/customer-processing-order.php
oceanwp-child/woocommerce/emails/customer-refunded-order.php
oceanwp-child/woocommerce/emails/customer-reset-password.php
oceanwp-child/woocommerce/emails/email-addresses.php version 3.0.0 is out of date. The core version is 3.2.1
oceanwp-child/woocommerce/emails/email-customer-details.php
oceanwp-child/woocommerce/emails/email-footer.php
oceanwp-child/woocommerce/emails/email-header.php
oceanwp-child/woocommerce/emails/email-order-details.php version 3.0.0 is out of date. The core version is 3.3.1
oceanwp-child/woocommerce/emails/email-order-items.php version 3.0.0 is out of date. The core version is 3.4.0
oceanwp-child/woocommerce/emails/email-styles.php version 2.3.0 is out of date. The core version is 3.3.0
oceanwp-child/woocommerce/emails/plain/admin-cancelled-order.php
oceanwp-child/woocommerce/emails/plain/admin-failed-order.php
oceanwp-child/woocommerce/emails/plain/admin-new-order.php
oceanwp-child/woocommerce/emails/plain/customer-completed-order.php
oceanwp-child/woocommerce/emails/plain/customer-invoice.php
oceanwp-child/woocommerce/emails/plain/customer-new-account.php
oceanwp-child/woocommerce/emails/plain/customer-note.php
oceanwp-child/woocommerce/emails/plain/customer-on-hold-order.php
oceanwp-child/woocommerce/emails/plain/customer-processing-order.php
oceanwp-child/woocommerce/emails/plain/customer-refunded-order.php
oceanwp-child/woocommerce/emails/plain/customer-reset-password.php
oceanwp-child/woocommerce/emails/plain/email-addresses.php version 2.2.0 is out of date. The core version is 3.4.0
oceanwp-child/woocommerce/emails/plain/email-customer-details.php version 2.5.0 is out of date. The core version is 3.4.0
oceanwp-child/woocommerce/emails/plain/email-order-details.php version 2.5.0 is out of date. The core version is 3.4.0
oceanwp-child/woocommerce/emails/plain/email-order-items.php version 3.0.0 is out of date. The core version is 3.2.0
oceanwp/woocommerce/loop/loop-start.php
oceanwp-child/woocommerce/single-product/product-image.php
oceanwp/woocommerce/single-product/title.php

Outdated Templates: ❌
					
					
						Learn how to update
`
</details>

**Comment by rodrigoprimo** [comment]
Are you able to reproduce this issue on a clean WooCommerce install to rule out conflicts with other plugins? Is this problem intermittent or not? In other words, for a specific order are you sometimes able to see the shipping address and sometimes not or the behavior is always the same for each order?

WooCommerce decides whether or not to show the shipping details section in the quick view depending on the value returned by the method WC_Order::needs_shipping_address():

https://github.com/woocommerce/woocommerce/blob/43d22a234976bca3322c6fcfd37003e09534012f/includes/admin/list-tables/class-wc-admin-list-table-orders.php#L611

Is it possible that some orders don't have a shipping method and those are the orders where the shipping details are missing?

https://github.com/woocommerce/woocommerce/blob/9f86839cabc6802a030e5c4d3577bd2b2998a623/includes/class-wc-order.php#L1348

**Comment by pixelmargin-ltd** [comment]
Hi,
Came across a similar issue, but with the Invoice Mail. A customer has both Billing and Shipping address. The order created mail send to the admin shows both Billing and Shipping addresses but the Shipping address is missing from the Invoice Mail. Both Mail templates are overwritten on theme but the same hook to display customer details is used.

**Comment by rodrigoprimo** [comment]
Closing this issue due to lack of feedback. I will reopen if more details are provided.

@pixelmargin-ltd, please open a separate issue describing your problem if you believe it is a WooCommerce bug and you can reproduce it on a clean WooCommerce install using one of the standard themes, and we will take a look. Thanks.
