### ISSUE TITLE
FILTER FOR VARIATIONS GIVEN A SET OF ATTRIBUTES

### ISSUE THREAD

**Issue by silvabrigade** [woocommerce/woocommerce#20968]
**Is your feature request related to a problem? Please describe.**
I'm frustrated with the fact that my customers have to play a guessing game of what colors sell with what product and what sizes sell with what color tshirt or color hoodie.

**Describe the solution you'd like**
Given the following scenerio:

My products are VARIABLE. 
ATTRIBUTES are the following: 
PRODUCTS 
COLOR 
SIZE

Note: NOT all products use the same colors or sizes.

When a customer selects a given PRODUCT (hoodie), 
the second and third ATTRIBUTE filter to show only the given 
VARIATIONS for those ATTRIBUTES.

Example: 
1.PRODUCT chosen is HOODIES 
2.COLOR is limited or filtered to only show colors that pertain to a given PRODUCT, HOODIES (red, blue, and black only) 
3.SIZE is also limited or filtered to only show sizes that pertain to a given PRODUCT (HOODIES).

I want to be able to showcase a gallery of PRODUCTS ranging from TANK TOPS, JERSEY TEES, to POSTERS on a single PRODUCT PAGE. And then I want customers to choose the appropriate/given color or variation based on the previously chosen ATTRIBUTE.

This is in order to show just what ever is available attribute wise to each PRODUCT type.

**Describe alternatives you've considered**

**Additional context**

**Comment by rodrigoprimo** [comment]
It is already possible to configure exactly which variations are available for each variable product individually. This means that you can, for example, have a Hoodie that is available only in red or blue and a T-shirt that is available in yellow and green.

The rest will depend on how you implement your custom page to list the gallery of products.

Closing for now as this doesn't seem like a feature request to me. Please reopen if I misunderstood your description.

**Comment by silvabrigade** [comment]
If a customer selects a variable Hoodie and then selects another variable
Small and a final variable of White

The customer will see a warning that says Sorry no product with that
description or variable available.

This is because the variable Hoodie is also pared with the variable TShirt.
Both are apart of the custom Attribute named PRODUCTS.

There is a White variable attached to TShirts only but WooCommerce shows
the variable White to all Attribute of PRODUCTS.

How can we minimize the going back and forth and have some variables attach
to some other variables but not all.

White Tshirts not White Hoodies
White Shoes not White Hoodies

Can we eliminate the variables not attached with some attributes.

1. Attribute named PRODUCTS
2. Variables of PRODUCTS
3. Hoodies, TShirts, Shoes
4. More Attributes
5.SIZES and COLORS

products affects sizes and colors

**Comment by rodrigoprimo** [comment]
@silvabrigade, I'm not sure if I follow your explanation of the issue that you are having. It seems to me that you are having trouble configuring your variable products. Unfortunately, this is not a support forum. We use GitHub issues exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce). You could also check the variable products documentation if you haven't already: https://docs.woocommerce.com/document/variable-product/
