### ISSUE TITLE
inclusive tax is adding additional tax to product price

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#20963]
1309520-zen

**Describe the bug**
When setting up taxes to be inclusive, the tax is added to the price of the product ( even though product's price should already be defined as including tax)

**To Reproduce**
1. Here's my set up:

![](http://cld.wthms.co/h83RlO+)
Link to screenshot: http://cld.wthms.co/h83RlO

![](http://cld.wthms.co/WZJnGn+)
Link to screenshot: http://cld.wthms.co/WZJnGn

Example tax rate:
![](http://cld.wthms.co/bu1Osd+)
Link to screenshot: http://cld.wthms.co/bu1Osd

2. My product is $10 which should already include the tax price:

![](http://cld.wthms.co/7Puhvo+)
Link to screenshot: http://cld.wthms.co/7Puhvo

3. But front end shows $11, so the 10% was added to the total product price after adding billing addres

![](http://cld.wthms.co/2zPSLf+)
Link to screenshot: http://cld.wthms.co/2zPSLf

**Expected behavior**

Should not add tax on top of the tax included product price.

WC 3.4.4 only activated

**Comment by kloon** [comment]
I was able to replicate this, seems like it is only happening when you are specifying US as the country when entering the tax rates, I tested with another country code and it worked fine displaying the expected totals so definitely related to the country being set to US.

**Comment by itp69** [comment]
@kloon, did the other country you tested with require you to select a region within the country?

The behavior also affects Spain which requires shop owners to select a communidad. I've assumed it applies to countries where you're required to select a region as well as the country, though USA and Spain are the only two examples I've tried.

Works as expected with the UK which doesn't include any regions.

**Comment by kloon** [comment]
I tested it using US as well as South Africa, South Africa also requires a selection of a region or province, however the issue is not happening when I test it with a tax rate for South Africa for a specific province.

http://cld.wthms.co/Zunfox
http://cld.wthms.co/jflJIK

**Comment by itp69** [comment]
Sorry, must have been a week ago when I tested with a Spanish shop address and I was sure it was behaving the same as the same as the US.

Just tested again and it is behaving as documented, includes the tax within the price for Spanish addresses and removes the tax for non-Spanish addresses.

**Comment by claudiulodro** [comment]
I've investigated this issue in-depth, and I believe that everything is working as expected.

Consider a store with the following settings that I believe reproduce the described issue:
- Inclusive pricing and inclusive pricing display
- Calculate tax based on customer address
- Shop base location in Spain
- 0% tax for Spain (the shop base location)
- 10% tax for USA
- A product set up with a price of $15 tax inclusive

When entering tax inclusive pricing, WooCommerce uses the tax rate for the shop base location to determine the amount of tax included in the product price (0% Spain rate in this case).

To determine the cost of the item for a visitor from the USA, [WooCommerce does the following](https://github.com/woocommerce/woocommerce/blob/b4242135546674e055701b9c017fff1d4d71bbcd/includes/wc-product-functions.php#L993-L995):
1. Remove the shop base location taxes from the product price (0 in this case) to get the untaxed product price ($15).
2. Calculate the taxes on the product for the customer's location ($1.50 for USA)
3. Add the tax to the untaxed product price ($15 + $1.50 = 16.50)

**If there is no tax matching the shop's base location, you will get this sort of behavior, as the amount of base tax included in a product's price is determined by the tax rate for the shop base location.**

If I haven't represented the problematic tax settings correctly please let me know and I'll take another look.
