### ISSUE TITLE
Woocommerce built in import tool - Attributes not working

### ISSUE THREAD

**Issue by LADRESSEVIENNA** [woocommerce/woocommerce#20966]
**Describe the bug**
I tried to import products with a CSV file, everything works fine but the attributes never show up in the products. I've used guides on how to fill in the attributes column but maybe I still do something wrong...

**To Reproduce**
1. Go to 'Products > All Products > Import'
2. Do the mapping (a lot has to be done manually, which is an other issue)
3. Run the importation
4. Click on 'view products' and open the new product

**Screenshots**
![wc import issue](https://user-images.githubusercontent.com/42044078/43602723-12f90118-9691-11e8-9f74-6964ea0dddec.PNG)

Thank you in advance for your help!

**Comment by rodrigoprimo** [comment]
I'm sorry but we don't use GitHub issues for support, we use it exclusively for reports of WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce).

If you believe you found a bug in the importer, please reopen this issue providing a sample CSV file that we can use to reproduce the problem and a copy of the system status page of your WooCommerce install.
