### ISSUE TITLE
How to filter products based on category?

### ISSUE THREAD

**Issue by deonvisser** [woocommerce/woocommerce#20960]
I saw  posts/issues all over the internet where people are asking, suggesting about filtering products.

Can someone just give a straight answer, please. Can I filter products based on product category. If so please provide example for and version of the API that is supposed to work. Would prefer the latest V2 and not legacy V2 (2 V1's and 2 V2's very confusing)

PS. filter[category] = xxxx does not work. All records are returned.

Thank you.

**Comment by peterfabian** [comment]
Hi, 

Please try: `/wp-json/wc/v2/products/?category=category_id`, e.g. on my local test environment: `http://local.wordpress.test/wp-json/wc/v2/products/?category=63`. 
I've just tested on both latest master and on 3.4.4 stable and both seem to work.

Relevant documentation link: http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

**Comment by deonvisser** [comment]
Thank you peterfabian. Aaah, I added "category" as a parameter. it is working. Thank you.
