### ISSUE TITLE
Inconsistent behaviour for the filter `woocommerce_add_cart_item`

### ISSUE THREAD

**Issue by bor0** [woocommerce/woocommerce#20962]
# Description
For the filter `woocommerce_add_cart_item`, we're applying it in [`WC_Cart::add_to_cart`](https://github.com/woocommerce/woocommerce/blob/db403b2/includes/class-wc-cart.php#L1082) which is good. However, we're also applying it in [`WC_Cart_Session::populate_cart_from_order`](https://github.com/woocommerce/woocommerce/blob/a4e0ba2/includes/class-wc-cart-session.php#L315).

For Product Add-Ons, our use case is that we're [adding new cart items](https://github.com/woocommerce/woocommerce-product-addons/blob/f70ee41/includes/class-product-addon-cart.php#L426-L432) to the cart contents in order to tie them to an existing item by hooking on the filter. This works fine when we simply add to cart.

Now, the problem happens when we do "Order Again" for a completed order through the frontend.

In `WC_Cart_Session`, the variable `$cart` is not an actual cart object but an array. As a result of this and since we don't have the cart in context, it does not care about what we do in `WC()->cart` during that filter since it will [overwrite it](https://github.com/woocommerce/woocommerce/blob/a4e0ba2/includes/class-wc-cart-session.php#L128) anyway.

# Reproduction steps
Check the [Product-Addons code](https://github.com/woocommerce/woocommerce-product-addons/blob/f70ee41/includes/class-product-addon-cart.php#L426-L432), but if needed I can supply a minimal example.

# Expected behaviour
I see two potential solutions to this:
1. Offer the current cart object in context on the filter `woocommerce_add_cart_item`
2. Instead of populating cart as an array and then writing it to `WC()->cart`, we write directly to `WC()->cart`

**Comment by claudiulodro** [comment]
I'm going to close this issue as the filter seems to be working correctly, but if you want to open a PR with either of the tweaks I'd be happy to review it for inclusion in 3.5.

**Comment by claudiulodro** [comment]
Our solution for this was to add two new filters/actions to allow manipulating the cart at these points in execution.

**Comment by claudiulodro** [comment]
#21051
