### ISSUE TITLE
Shipping costs double on checkout and cart pages

### ISSUE THREAD

**Issue by hightreeR** [woocommerce/woocommerce#20961]
**Describe the bug**
I'm at my wits end. I'm trying to make a woocommerce-based site, and everything is going ok, except one thing: the shipping cost doubles for every shipping area.

When using WPML, it still goes wrong, but only on primary language pages. For the secondary language, it does calculate the right costs.

I already tried using the standard theme and disabling all plugins and followed the guidelines woocommerce provided for finding bugs (upping my memory etc.) I really don't know what is going wrong. 

The site is: www.hightreesustainable.com

**To Reproduce**

1. Go to www.hightreesustainable.com
2. Click on sustainable art prints in the header menu
3. Put an item in the cart
4. Go to cart
5. Calculate shipping now shows double the amount I filled in in the shipping options in Woocommerce
6. Switch to the Dutch version of the cart (top header bar, click on 'Nederlands')
7. The secondary language does show the right amount

**Expected behavior**
I expected to see the same shipping costs for the primary language as for the secondary language

**Isolating the problem (mark completed items with an [x]):**
- yes, I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- Yes, This bug happens with a default WordPress theme active (Twentyseventeen)
- Yes, I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://www.hightreesustainable.com
Site URL: https://www.hightreesustainable.com
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.7
WP Multisite: ✔
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.8
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1-log
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wpqm_
MaxMind GeoIP Database: ✔
Total Database Size: 48.39MB
Database Data Size: 34.80MB
Database Index Size: 13.59MB
wpqm_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB
wpqm_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpqm_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpqm_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpqm_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpqm_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB
wpqm_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpqm_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wpqm_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpqm_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wpqm_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpqm_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpqm_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpqm_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpqm_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB
wpqm_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB
wpqm_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpqm_atum_order_items: Data: 0.02MB + Index: 0.02MB
wpqm_blogs: Data: 0.02MB + Index: 0.03MB
wpqm_blog_versions: Data: 0.02MB + Index: 0.02MB
wpqm_commentmeta: Data: 0.02MB + Index: 0.03MB
wpqm_comments: Data: 0.05MB + Index: 0.09MB
wpqm_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wpqm_icl_cms_nav_cache: Data: 0.02MB + Index: 0.00MB
wpqm_icl_content_status: Data: 0.02MB + Index: 0.02MB
wpqm_icl_core_status: Data: 0.02MB + Index: 0.02MB
wpqm_icl_flags: Data: 0.02MB + Index: 0.02MB
wpqm_icl_languages: Data: 0.02MB + Index: 0.03MB
wpqm_icl_languages_translations: Data: 0.19MB + Index: 0.11MB
wpqm_icl_locale_map: Data: 0.02MB + Index: 0.00MB
wpqm_icl_message_status: Data: 0.02MB + Index: 0.03MB
wpqm_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB
wpqm_icl_node: Data: 0.02MB + Index: 0.00MB
wpqm_icl_reminders: Data: 0.02MB + Index: 0.00MB
wpqm_icl_strings: Data: 4.52MB + Index: 6.94MB
wpqm_icl_string_packages: Data: 0.02MB + Index: 0.00MB
wpqm_icl_string_pages: Data: 0.27MB + Index: 0.14MB
wpqm_icl_string_positions: Data: 0.14MB + Index: 0.05MB
wpqm_icl_string_status: Data: 0.02MB + Index: 0.02MB
wpqm_icl_string_translations: Data: 2.52MB + Index: 1.52MB
wpqm_icl_string_urls: Data: 0.02MB + Index: 0.02MB
wpqm_icl_translate: Data: 1.52MB + Index: 0.02MB
wpqm_icl_translate_job: Data: 0.02MB + Index: 0.02MB
wpqm_icl_translations: Data: 0.08MB + Index: 0.13MB
wpqm_icl_translation_batches: Data: 0.02MB + Index: 0.00MB
wpqm_icl_translation_status: Data: 0.42MB + Index: 0.02MB
wpqm_ip_geo_block_cache: Data: 0.02MB + Index: 0.02MB
wpqm_ip_geo_block_logs: Data: 0.02MB + Index: 0.03MB
wpqm_ip_geo_block_stat: Data: 0.02MB + Index: 0.00MB
wpqm_links: Data: 0.02MB + Index: 0.02MB
wpqm_masterslider_options: Data: 0.06MB + Index: 0.02MB
wpqm_masterslider_sliders: Data: 0.05MB + Index: 0.03MB
wpqm_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB
wpqm_mondula_form_wizards: Data: 0.02MB + Index: 0.00MB
wpqm_ms_snippets: Data: 0.02MB + Index: 0.00MB
wpqm_options: Data: 3.52MB + Index: 0.42MB
wpqm_postmeta: Data: 2.52MB + Index: 1.97MB
wpqm_posts: Data: 9.52MB + Index: 0.30MB
wpqm_registration_log: Data: 0.02MB + Index: 0.02MB
wpqm_signups: Data: 0.02MB + Index: 0.06MB
wpqm_site: Data: 0.02MB + Index: 0.02MB
wpqm_sitemeta: Data: 0.27MB + Index: 0.03MB
wpqm_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wpqm_snippets: Data: 0.02MB + Index: 0.00MB
wpqm_termmeta: Data: 0.02MB + Index: 0.03MB
wpqm_terms: Data: 0.02MB + Index: 0.03MB
wpqm_term_relationships: Data: 0.05MB + Index: 0.02MB
wpqm_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wpqm_ulike: Data: 0.02MB + Index: 0.00MB
wpqm_ulike_activities: Data: 0.02MB + Index: 0.00MB
wpqm_ulike_comments: Data: 0.02MB + Index: 0.00MB
wpqm_ulike_forums: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Catalogues: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Catalogue_Items: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Categories: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Custom_Fields: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Fields_Meta: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Items: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Item_Images: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_SubCategories: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Tagged_Items: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Tags: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Tag_Groups: Data: 0.02MB + Index: 0.00MB
wpqm_UPCP_Videos: Data: 0.02MB + Index: 0.00MB
wpqm_usermeta: Data: 0.06MB + Index: 0.03MB
wpqm_users: Data: 0.02MB + Index: 0.05MB
wpqm_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpqm_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpqm_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wpqm_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wpqm_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wpqm_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wpqm_wfConfig: Data: 0.42MB + Index: 0.00MB
wpqm_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wpqm_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wpqm_wfFileMods: Data: 3.52MB + Index: 0.00MB
wpqm_wfHits: Data: 0.44MB + Index: 0.23MB
wpqm_wfHoover: Data: 0.02MB + Index: 0.02MB
wpqm_wfIssues: Data: 0.02MB + Index: 0.06MB
wpqm_wfKnownFileList: Data: 2.52MB + Index: 0.00MB
wpqm_wfLeechers: Data: 0.02MB + Index: 0.00MB
wpqm_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
wpqm_wfLocs: Data: 0.02MB + Index: 0.00MB
wpqm_wfLogins: Data: 0.02MB + Index: 0.03MB
wpqm_wfNet404s: Data: 0.02MB + Index: 0.02MB
wpqm_wfNotifications: Data: 0.02MB + Index: 0.00MB
wpqm_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wpqm_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wpqm_wfScanners: Data: 0.02MB + Index: 0.00MB
wpqm_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wpqm_wfStatus: Data: 0.13MB + Index: 0.09MB
wpqm_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wpqm_yoast_seo_links: Data: 0.08MB + Index: 0.02MB
wpqm_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 238
condition_group: 8
customize_changeset: 142
custom_css: 3
elementor_library: 2
envira: 1
et_pb_layout: 12
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
mc4wp-form: 2
nav_menu_item: 56
page: 38
popup: 1
popup_theme: 6
post: 22
product: 58
product_variation: 24
revision: 705
rl_gallery: 1
shop_order: 14
sidebar: 6
wafs: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.0.5
WooCommerce Multilingual: by OnTheGoSystems – 4.3.4
WooCommerce: by Automattic – 3.4.4
WPML CMS Nav: by OnTheGoSystems – 1.4.23
WPML Media: by OnTheGoSystems – 2.3.5
WPML Sticky Links: by OnTheGoSystems – 1.4.4
WPML String Translation: by OnTheGoSystems – 2.8.5
WPML Translation Management: by OnTheGoSystems – 2.6.5
WPML Widgets: by Jeroen Sormani – 1.0.6
GDPR Cookie Consent: by webtoffee – 1.6.2
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.5
WooCommerce: by Automattic – 3.4.4
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.6.4 – Not tested with the active version of WooCommerce

Custom Sidebars: by WPMU DEV – 3.1.6
Elegant Themes Support: by Elegant Themes – 1.3
Anti-spam: by webvitaly – 5.2
Custom Facebook Feed: by Smash Balloon – 2.7
Email Templates: by Damian Logghe – 1.2.2.3
Fietskoeriers.nl: by Fietskoeriers.nl – 1.1.5 – Not tested with the active version of WooCommerce
Instagram Gallery: by Karan Singh – 1.6.2
WP ULike: by Ali Mirzaei – 3.5.0
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.4.13
Mollie Payments for WooCommerce: by Mollie – 4.0.0-beta7
Yoast SEO: by Team Yoast – 7.9
Autoptimize: by Frank Goossens (futtta) – 2.3.4
Breadcrumb NavXT: by John Havlik – 6.1.0
MailChimp for WordPress Multilingual: by OnTheGoSystems – 0.0.2
Loco Translate: by Tim Whitlock – 2.1.4
PayPal for WooCommerce: by Angell EYE – 1.4.14
SiteOrigin CSS: by SiteOrigin – 1.2.3
SiteOrigin Widgets Bundle: by SiteOrigin – 1.12.1
Smush: by WPMU DEV – 2.8.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.14.12

Woo Checkout Field Editor Pro: by ThemeHiGH – 1.2.8
Woo Preview Emails: by Digamber Pradhan – 1.4.0 – Not tested with the active version of WooCommerce
Widgets for SiteOrigin: by wpinked – 1.3.7
Duplicator: by Snap Creek – 1.2.40

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #355 - /cart/
Checkout: #358 - /checkout/
My account: #361 - /my-account/
Terms and conditions: #11 - /terms/

### Theme ###

Name: Child Theme for Divi
Version: 1.0
Author URL: http://wordpress-style.net
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.11.1
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by willgorham** [comment]
@hightreeR See this ticket: #17830. The issue is probably with how you have your shipping settings configured.

**Comment by hightreeR** [comment]
You are a lifesaver. Thank you so much! I have been staring at this for so long, and now it finally works! However, it seems weird that both the Polylang and WPML plugins don't add that extra cost for any secondary languages, but only for the primary.

**Comment by willgorham** [comment]
@hightreeR No problem! 😄
