### ISSUE TITLE
Stock Status not updated when selecting variants

### ISSUE THREAD

**Issue by towebo** [woocommerce/woocommerce#20974]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
X - [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Download https://hastochhage.se/products.csv and import the product and its variants.
2. On In the webshop select "Storlek" 40 and "Färg" svart/beige (it's out of stock).
3. The image will change but when saving the page as html it still says "in stock" because the variable article "959252-base" is marked as in stock because there are other variants that are still in stock.

## Expected/actual behavior

When I follow those steps, I see...
I use the plugin Woo-Out of stock to display a "Sold out" overlay image to easy show that it's out of stock. This plugin uses CSS to acheeve this and because the stock status isn't updated when choosing variants the "Sold out" overlay won't appear.

I was expecting to see...
The expected behaviour would be that when selecting a variant that's out of stock it would be updated so the CSS could do its job and reflect the new stock status.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
X - [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
X - [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
I'm sorry but I can't find it. Perhaps it's because I'm visually impaired and use a screen reader (NVDA). It's WooCommerce 3.4.4, the version pulled from WorPress. If you could guide me I can provide more info.

[products.txt](https://github.com/woocommerce/woocommerce/files/2257785/products.txt)

</details>

**Comment by claudiulodro** [comment]
Hi there,

I tested with your CSV and the steps and everything seemed to work correctly using WooCommerce with no additional plugins. When I select "40" and "svart/beige" I see an out-of-stock notice. Here is a screenshot (sorry I'm not sure how helpful that is for you, though):

<img width="687" alt="screen shot 2018-08-07 at 10 49 30 am" src="https://user-images.githubusercontent.com/7317227/43793254-d93fad44-9a2f-11e8-8893-106d53211693.png">

If you are saving the page as html it will not be the same as if the page is viewed normally in the browser. Javascript changes the html of the page when the variation is selected, and these changes will not be shown in the saved html if you save the page as html.

I took a look at https://hastochhage.se/produkt/ridbyxa-fiona/ and it seems to be showing out-of-stock products correctly. I don't see any overlay image, though. We can't troubleshoot third-party plugins for WooCommerce here, so I would contact the author of the out-of-stock overlay plugin if you suspect it's not working correctly.

Hope this clears things up. Thanks.

**Comment by towebo** [comment]
Thanks!
Ok, I’m not especially fluent in web development and JavaScript so there’s a lot to learn.
The plugin I use is called Woo-Out of stock and uses CSS to render a ”Sold Out” png on top of the product image. It doesn’t seem to refresh when changing variant and the variant is out of stock.

The main problem was that I was using a plugin that makes the store into a product catalog but it did hide the stock status too. I changed to a different catalog plugin so now the stock status is shown as it should.

Sorry for bothering you with problems that relates to a plugin.


Kind regards

Karl-Otto
0701-75 98 56

Även om det är ett äpple på baksidan så får du inte tugga på min mobil!
