### ISSUE TITLE
Checkout RestAPI missing

### ISSUE THREAD

**Issue by shubhikajain** [woocommerce/woocommerce#20971]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rodrigoprimo** [comment]
It’s up to the API user to manage their own checkout and calculations if they are building an API-based store. The API is not just headless WooCommerce. Next time you open an issue, please take the time to describe it and remove the issue template.
