### ISSUE TITLE
Shipping address values changing to billing at Checkout Page

### ISSUE THREAD

**Issue by DarkChris86** [woocommerce/woocommerce#20975]
**Describe the bug**
If you have an Account with filled Shipping values and go to the Checkout page ( with item in cart ) and check the Ship to different address checkbox and do some refresh ( 8 - 9 times ) in your browser than it will change your shipping values to billing values!

**To Reproduce**
1. Go to My Account and Edit Address
2. Enter two visibly different addresses for billing and shipping
3. Go to 'Checkout Page ( with item in cart )'
4. Check the Ship to a different address ( which should already have the address from step 2 entered there for shipping )
2. Refresh with **F5** or **CTRL + F5**  8-9 times 
4. See error:  Shipping address values will change to that of billing
...

As you could see in my screenshot!

**Idea**
I found a JS function in wp-content/plugins/woocommerce/assets/js/frontend/checkout.js
_update_checkout_action_
https://imgur.com/a/HIFudPV

Maybe the problem is coming from here...

**Screenshots**
![image](https://user-images.githubusercontent.com/18347405/43651663-47f77cfc-9743-11e8-88fc-e6b8309572d5.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://vorosfeher.designcode.hu
Site URL: https://vorosfeher.designcode.hu
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.1.19 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.22
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wpdj_
MaxMind GeoIP Database: ✔
Total Database Size: 0.48MB
Database Data Size: 0.34MB
Database Index Size: 0.14MB
wpdj_woocommerce_sessions: Data: 0.03MB + Index: 0.00MB
wpdj_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB
wpdj_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpdj_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpdj_commentmeta: Data: 0.00MB + Index: 0.01MB
wpdj_comments: Data: 0.01MB + Index: 0.01MB
wpdj_links: Data: 0.00MB + Index: 0.00MB
wpdj_options: Data: 0.24MB + Index: 0.04MB
wpdj_postmeta: Data: 0.02MB + Index: 0.02MB
wpdj_posts: Data: 0.03MB + Index: 0.01MB
wpdj_termmeta: Data: 0.00MB + Index: 0.01MB
wpdj_terms: Data: 0.00MB + Index: 0.01MB
wpdj_term_relationships: Data: 0.00MB + Index: 0.00MB
wpdj_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wpdj_usermeta: Data: 0.01MB + Index: 0.01MB
wpdj_users: Data: 0.00MB + Index: 0.01MB
wpdj_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpdj_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpdj_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wpdj_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1
customize_changeset: 2
nav_menu_item: 4
oembed_cache: 1
page: 6
post: 29
product: 5
revision: 2
shop_order: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Gutenberg: by Gutenberg Team – 3.4.0
WooCommerce Barion Payment Gateway: by Transgate – 0.9.48
WooCommerce: by Automattic – 3.4.4
Yoast SEO: by Team Yoast – 7.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: HUF (Ft)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #6 - /uzlet/
Cart: #7 - /kosar/
Checkout: #8 - /penztar/
My account: #9 - /fiokom/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by kloon** [comment]
I tested this now with Twenty Seventeen and just WooCommerce activated and are not able to replicate this. I reloaded the site 10 times at checkout and every time it loaded the shipping address as stored under My Account.

Visiting your site I see a different theme active, have you tested it with a default theme like Storefront or Twenty Seventeen and all plugins except WooCommerce disabled? Also check for any Javascript errors on your checkout page which could be a culprit.

**Comment by DarkChris86** [comment]
**Hi kloon,**

Meantime I did some develop, but I could disable all and use Twenty Seventeen again.

I found a JavaScript issue on checkout.

I got this message:
`GET https://vorosfeher.designcode.hu/wp-content/plugins/woocommerce/assets/images/icons/loader.svg 449 ()`

**Comment by kloon** [comment]
That should not cause an issue. Also check if you do not perhaps have browser autofill enabled on those fields as that could also be why it populates the wrong data.

**Comment by DarkChris86** [comment]
I checked and autofill in chrome had disabled

![image](https://user-images.githubusercontent.com/18347405/43711323-9b5fc0e4-9972-11e8-82cb-1d84c6079fa7.png)

**Comment by kloon** [comment]
I am unable to replicate this, can you test on a clean install on a different site? I will need steps to replicate this in order to investigate if this is a bug.

**Comment by DarkChris86** [comment]
It's a clean install but I'll do 2 another site too.
Did you try with **CTRL + F5** or **Command + F5** 20-30 times?

Could you give me a link to your test site where I've possibility to register as a customer?
I'm going to take a video from that.

**Comment by DarkChris86** [comment]
As I promised you, I did two clean install on apache & nginx server.

// Apache
https://woocommerce.arany2017.hu/

// NGINX
https://woocommerce.designcode.hu

_Admin account_
Username: **admin**
PW: **Admin2018**


Do some **CTRL + F5** or **Command + F5** on Checkout and you'll face the problem!

Shipping data will change to billing!
What is more, from that moment it'll keep the billing values on Checkout.

**Comment by kloon** [comment]
See #21639
