### ISSUE TITLE
Add to Cart customer wise

### ISSUE THREAD

**Issue by shubhikajain** [woocommerce/woocommerce#20970]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shubhikajain** [comment]
Rest API related to cart is missing customer wise data.

**Comment by rodrigoprimo** [comment]
Please open another issue detailing your feature request considering the points mentioned in the feature request template instead of just adding a title to the issue.
