### ISSUE TITLE
Importer Capabilities Supersede User Capabilities 

### ISSUE THREAD

**Issue by adriannees** [woocommerce/woocommerce#20979]
**Describe the bug**
My vendors have the capability to import, but not to create new categories; however, when they use the CSV importer built into Woocommerce any improperly spelled categories (or new categories entirely) are created by the importer anyways (despite their user role not having the capability). 

**To Reproduce**
1. Wordpress + Woocommerce + Multivendor Marketplace plugin (WC Vendors in my case) 
2. Log in as a vendor 
3. Import CSV with custom categories not created by the admin
4. See new categories created :) 

**Expected behavior**
CSV importer should check the capabilities to create new terms and not create new terms if capability is not granted. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. 
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://stockabl.com
Site URL: https://stockabl.com
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: ❌ 4.9.7 - There is a newer version of WordPress available (4.9.8)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Unix) mod_hive/6.6 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.1.20 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 200 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1-log
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wpbl_
MaxMind GeoIP Database: ✔
Total Database Size: 459.58MB
Database Data Size: 409.35MB
Database Index Size: 50.23MB
wpbl_woocommerce_sessions: Data: 1.38MB + Index: 0.02MB
wpbl_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wpbl_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wpbl_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wpbl_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wpbl_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wpbl_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wpbl_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wpbl_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wpbl_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wpbl_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wpbl_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wpbl_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wpbl_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wpbl_bm_user_location: Data: 0.00MB + Index: 0.01MB
wpbl_bp_activity: Data: 0.06MB + Index: 0.16MB
wpbl_bp_activity_meta: Data: 0.02MB + Index: 0.03MB
wpbl_bp_follow: Data: 0.02MB + Index: 0.02MB
wpbl_bp_friends: Data: 0.02MB + Index: 0.03MB
wpbl_bp_groups: Data: 0.02MB + Index: 0.05MB
wpbl_bp_groups_groupmeta: Data: 0.02MB + Index: 0.03MB
wpbl_bp_groups_members: Data: 0.02MB + Index: 0.09MB
wpbl_bp_messages_messages: Data: 0.02MB + Index: 0.03MB
wpbl_bp_messages_meta: Data: 0.02MB + Index: 0.03MB
wpbl_bp_messages_notices: Data: 0.02MB + Index: 0.02MB
wpbl_bp_messages_recipients: Data: 0.02MB + Index: 0.08MB
wpbl_bp_notifications: Data: 0.02MB + Index: 0.11MB
wpbl_bp_notifications_meta: Data: 0.02MB + Index: 0.03MB
wpbl_bp_user_blogs: Data: 0.02MB + Index: 0.03MB
wpbl_bp_user_blogs_blogmeta: Data: 0.02MB + Index: 0.03MB
wpbl_bp_xprofile_data: Data: 1.52MB + Index: 0.16MB
wpbl_bp_xprofile_fields: Data: 0.02MB + Index: 0.08MB
wpbl_bp_xprofile_groups: Data: 0.02MB + Index: 0.02MB
wpbl_bp_xprofile_meta: Data: 0.02MB + Index: 0.03MB
wpbl_cf_forms: Data: 2.52MB + Index: 0.02MB
wpbl_cf_form_entries: Data: 0.09MB + Index: 0.14MB
wpbl_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB
wpbl_cf_form_entry_values: Data: 2.52MB + Index: 3.39MB
wpbl_cf_pro_messages: Data: 0.02MB + Index: 0.00MB
wpbl_cf_tracking: Data: 0.02MB + Index: 0.00MB
wpbl_cf_tracking_meta: Data: 0.02MB + Index: 0.03MB
wpbl_commentmeta: Data: 0.02MB + Index: 0.03MB
wpbl_comments: Data: 0.02MB + Index: 0.09MB
wpbl_csp3_subscribers: Data: 0.02MB + Index: 0.00MB
wpbl_cspv5_pages: Data: 0.03MB + Index: 0.00MB
wpbl_ewwwio_images: Data: 2.52MB + Index: 1.66MB
wpbl_failed_jobs: Data: 0.02MB + Index: 0.00MB
wpbl_links: Data: 0.02MB + Index: 0.02MB
wpbl_loginizer_logs: Data: 0.01MB + Index: 0.01MB
wpbl_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wpbl_odb_logs: Data: 0.00MB + Index: 0.00MB
wpbl_options: Data: 292.44MB + Index: 8.55MB
wpbl_pmxe_exports: Data: 0.03MB + Index: 0.00MB
wpbl_pmxe_posts: Data: 0.02MB + Index: 0.00MB
wpbl_pmxe_templates: Data: 0.02MB + Index: 0.00MB
wpbl_pmxi_files: Data: 0.02MB + Index: 0.00MB
wpbl_pmxi_history: Data: 0.02MB + Index: 0.00MB
wpbl_pmxi_imports: Data: 0.03MB + Index: 0.00MB
wpbl_pmxi_posts: Data: 0.02MB + Index: 0.00MB
wpbl_pmxi_templates: Data: 0.02MB + Index: 0.00MB
wpbl_postmeta: Data: 75.61MB + Index: 15.06MB
wpbl_posts: Data: 13.52MB + Index: 5.89MB
wpbl_pv_commission: Data: 0.02MB + Index: 0.00MB
wpbl_queue: Data: 0.02MB + Index: 0.00MB
wpbl_recommendposts_votes: Data: 0.02MB + Index: 0.00MB
wpbl_signups: Data: 0.02MB + Index: 0.06MB
wpbl_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wpbl_termmeta: Data: 1.52MB + Index: 1.91MB
wpbl_terms: Data: 1.52MB + Index: 3.03MB
wpbl_term_relationships: Data: 6.52MB + Index: 3.52MB
wpbl_term_taxonomy: Data: 1.52MB + Index: 2.00MB
wpbl_usermeta: Data: 4.52MB + Index: 3.03MB
wpbl_users: Data: 0.19MB + Index: 0.16MB
wpbl_wcv_feedback: Data: 0.06MB + Index: 0.00MB
wpbl_wcv_trs_tables: Data: 0.02MB + Index: 0.02MB
wpbl_wcv_trs_table_locations: Data: 0.02MB + Index: 0.06MB
wpbl_wcv_trs_table_rates: Data: 0.06MB + Index: 0.02MB
wpbl_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpbl_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpbl_wpfront_ure_content_shortcodes: Data: 0.02MB + Index: 0.00MB
wpbl_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB
wpbl_wpfront_ure_menu_editor: Data: 0.02MB + Index: 0.00MB
wpbl_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB
wpbl_wpfront_ure_post_type_permissions: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 7982
bp-email: 16
custom_css: 2
customize_changeset: 2
forum: 4
mc4wp-form: 1
nav_menu_item: 31
oembed_cache: 1
omapi: 6
page: 43
post: 290
product: 7855
reply: 21
revision: 311
sg_optimizer_jobs: 28
shop_coupon: 1
shop_order_vendor: 3
topic: 13

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

Admin Category Tree: by Stefan Andernach – 1.1
The SEO Framework: by Sybre Waaijer – 3.0.6
WooCommerce Multiple Carts Per User: by Burning Moth Creations – 1.12 – Not tested with the active version of WooCommerce
BuddyPress Reorder Tabs: by BuddyBoss – 2.0.1
BP xProfile Location: by shanebp – 1.6
MarketPlace: by BuddyBoss – 1.5.8
BuddyBoss Products Updater: by BuddyBoss – 1.0.2
BuddyPress Global Search: by BuddyBoss – 1.1.9
BuddyPress XProfile Image Field: by Alex Githatu – 2.1.0
BuddyPress: by The BuddyPress Community – 3.1.0
Disable Password Change Email: by Mass Edge Inc. – 1.0.1
Google Tag Manager for Wordpress: by Thomas Geiger – 1.8.1
Equal Height Columns: by MIGHTYminnow
Mickey Kay
Braad Martin – 1.1.0

EWWW Image Optimizer Cloud: by Shane Bishop – 4.2.3
Flaming Password Reset: by Project Caruso – 1.0.3
Force First and Last Name as Display Name: by Stranger Studios – 1.0
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Heartbeat Control: by Jeff Matson – 1.2.4
Import users from CSV with meta: by codection – 1.11.3.6
WPBakery Page Builder: by Michael M - WPBakery.com – 5.5.1
Loginizer: by Raj Kothari – 1.4.0
Woocommerce Products Price Bulk Edit: by Mostafa Qanbari – 2.0 – Not tested with the active version of WooCommerce
WP Sticky Sidebar: by m.r.d.a – 1.2.6
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Optimize Database after Deleting Revisions: by CAGE Web Design | Rolf van Gelder
Eindhoven
The Netherlands – 4.6.2

SeedProd Coming Soon Page Pro: by SeedProd – 5.11.5
SG Optimizer: by SiteGround – 4.0.7
User Switching: by John Blackbourn & contributors – 1.3.1
WC Vendors Pro: by WC Vendors – 1.5.4
WC Vendors Marketplace: by WC Vendors – 2.0.10
WCV Table Rate Shipping: by The Plugin Pros – 1.2.3
WooCommerce Stripe Gateway: by WooCommerce – 4.1.8
Woocommerce Multiple Addresses: by Alexander Tinyaev – 1.0.7.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.4
WP Mail SMTP: by WPForms – 1.3.3
WP Rollback: by WordImpress – 1.5.1
Smush: by WPMU DEV – 2.8.0
WPFront User Role Editor Personal Pro: by Syam Mohan – 2.14.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #58 - /shop/
Cart: #59 - /cart/
Checkout: #60 - /checkout/
My account: #61 - /my-account/
Terms and conditions: #1252 - /terms-of-use/buyer-policies/

### Theme ###

Name: Stockabl Custom OneSocial Child Theme
Version: 1.2.0
Author URL: http://www.buddyboss.com
Child Theme: ✔
Parent Theme Name: OneSocial
Parent Theme Version: 1.4.6
Parent Theme Author URL: https://www.buddyboss.com
WooCommerce Support: ✔

### Templates ###

Overrides: /home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/archive-product.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/cart/cart-empty.php
onesocial-child-stockabl/woocommerce/cart/cart.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/checkout/form-billing.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/checkout/form-checkout.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/checkout/thankyou.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/content-product_cat.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/loop/orderby.php
onesocial-child-stockabl/woocommerce/loop/price.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/loop/result-count.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/order/order-details-customer.php version 3.3.0 is out of date. The core version is 3.4.4
onesocial/woocommerce/product-searchform.php
onesocial-child-stockabl/woocommerce/single-product/add-to-cart/variation.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/single-product/meta.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/single-product/product-image.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/single-product/product-thumbnails.php
onesocial-child-stockabl/woocommerce/single-product/related.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/single-product/short-description.php
/home/stockabl/public_html/wp-content/plugins/buddyboss-marketplace/templates/woocommerce/single-product/up-sells.php

Outdated Templates: ❌
					
					
						Learn how to update

### WC Vendors Pro ###

Theme Compatability: -
Pro Dashboard Page: - #646
Feedback form page: - #978
Vendor Shop Permalink: - maker

### Templates ###

Overrides: –
`
</details>

**Comment by claudiulodro** [comment]
#21192
