### ISSUE TITLE
A 'Secure' flag filter for cookies

### ISSUE THREAD

**Issue by hemiipatu** [woocommerce/woocommerce#20978]
**The problem**
I am trying to get my Wordpress site PCI DSS compliant but have had issues with a few cookies, woocommerce included; this is due to the cookies not using the _"httpOnly"_ & _"secure"_ flags.

After a tonne of research I have [found](https://github.com/woocommerce/woocommerce/issues/17920) that you can modify the code found within [wc-core-functions.php](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-core-functions.php#L827) but the implementation only applies the _"httpOnly"_ flag. 

**The solution I would like**
I would like to see an additional filter where _"secure"_ flag can be changed in the same manner as the solution provided for _"httpOnly"_ and future implementation of this feature to enable the options to be toggleable and persistent over-updates via the frontend.

**Comment by kloon** [comment]
@hemiipatu the filter you are looking for is `wc_session_use_secure_cookie`, it is not inside the function you are referencing but is used when that function is called for setting the session cookies.
