### ISSUE TITLE
Add to cart API customer Wise issue

### ISSUE THREAD

**Issue by shubhikajain** [woocommerce/woocommerce#20980]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shubhikajain** [comment]
The REST API which is given for add to cart is saving data for cart but not customer wise.
I am making an API for food delivery app, and i need an API where each customer's cart data saves separately, not mix with other customer cart.And display each customer cart using user id

**Comment by kloon** [comment]
The WooCommerce API is not a client-side API. You cannot issue API keys for each customer to identify them. It would be up your application or middleware to manage the carts/sessions and then create orders from that in a pending state and handle the payment before updating the orders to completed.

If you search the issues you will see many closed ones asking for Cart support, this is unfortunately not something we are going to add support for.

**Comment by shubhikajain** [comment]
Then what is the user of add to cart API which is provided from your side.

On Mon, Aug 6, 2018 at 11:58 AM, Gerhard Potgieter <notifications@github.com

**Comment by shubhikajain** [comment]
This plugin is completely useless. If in web application woo commerce plugin is saving all cart and complete process customer wise.Then API should should do the same.The plugin which you have mentioned is not saving data according to your woo commerce plugin.

**Comment by kloon** [comment]
> Then what is the user of add to cart API which is provided from your side.

There is no Add To Cart endpoint in WooCommerce, there is only an orders endpoint which I presume you are referring to? The use of that is to create orders from products, there's a log of apps out there that makes use of they own session management before creating orders. In fact most API's out there will not do any session management for you, that will always be up to your app or middleware that communicates with the API.

> This plugin is completely useless. If in web application woo commerce plugin is saving all cart and complete process customer wise.Then API should should do the same.The plugin which you have mentioned is not saving data according to your woo commerce plugin.

Sorry to hear that, in that case you might want to look at alternative solutions then? A website is not the same as its API. Even if we did ad a Cart endpoint to WooCommerce you would still need to manage sessions inside your app as there is no API keys for customers, you need something to identify the user and keep track of them, so adding it would make no difference really. Regarding the plugin I linked to, I simply tried to provide you with a solution, like I said we do not support that as it is not our plugin.
