### ISSUE TITLE
WooCommerce PDF Invoice

### ISSUE THREAD

**Issue by ideassapna** [woocommerce/woocommerce#20988]
For all the orders the "WooCommerce PDF Invoice" plugin generates invoices with Price and inclusive of VAT. The issue is it shows the VAT together with the Total price. I want the plugin to show the VAT separately. 
![vat](https://user-images.githubusercontent.com/42139467/43712340-722ed4aa-9993-11e8-9aa6-5820f0978287.jpg)

Requirement: 

On first line I want to show: 
Test Paid Product - Single User                          € 4

On second line I want to show the VAT:
                                                                            € 1
Later in Total : 
Total:                                                                    € 5 (includes € 1 VAT)

Plz let me know if there is any setting which allows to do the same in WooCommerce when I'm generating PDF invoice.

**Comment by ChromeOrange** [comment]
If this is the plugin from WooCommerce then please submit a support ticket here https://woocommerce.com/my-account/create-a-ticket/

The totals section of the invoice should match the totals section on WooCommerce and in the emails.

You can modify the layout of the invoice using filters : https://docs.woocommerce.com/document/pdf-invoice-developer-tools/

If you look at this section of the docs you can see how to add columns, you can easily modify that to remove any parts you don't need 
https://docs.woocommerce.com/document/pdf-invoice-developer-tools/#section-3

**Comment by rodrigoprimo** [comment]
Closing as this issue tracker is used exclusively for WooCommerce core. Please follow the instructions in the comment above if you are using WooCommerce PDF Invoices (https://woocommerce.com/products/pdf-invoices/).
