### ISSUE TITLE
Missing password fields type styling on admin.css

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#20981]
**Describe the bug**
On admin.scss there's a CSS declaration to style several types (let's call them variants) of text fields, around lines 3480 to 3490:
`textarea,
input[type="text"],
input[type="email"],
input[type="number"],
input.regular-input {
	width: 400px;
	margin: 0;
	padding: 6px;
	box-sizing: border-box;
	vertical-align: top;
}`

**To Reproduce**
Create a new settings page for a plugin containing a password field.

**Screenshots**
![image](https://user-images.githubusercontent.com/6853605/43676114-6393e2ee-97e2-11e8-8c6b-017ae3df0190.png)

**Expected behavior**
The password fields should have the same styling as regular text fields.

I recommend that input[type="password"] (and probably other types) is added to the CSS declaration

**Comment by claudiulodro** [comment]
@webdados we're happy to review a pull request for merge into WooCommerce if you want to give it a shot.

**Comment by webdados** [comment]
@claudiulodro Done #21013

**Comment by webdados** [comment]
@claudiulodro I've only changed the scss file. I guess the css get's updated automagically, right?

**Comment by claudiulodro** [comment]
See #21013
