### ISSUE TITLE
Please add a way to query only products that have an SKU

### ISSUE THREAD

**Issue by Biont** [woocommerce/woocommerce#20987]
**Is your feature request related to a problem? Please describe.**
We're working on a plugin that relies heavily on the usage of SKUs on products. We also need to perform large queries for all products that ***have*** a SKU on a regular basis. And lastly, we are using a custom Data Store, so we are tied to the WC API and want to leave out any WP-specific queries (->postmeta) as much as possible to be forward-compatible. Sadly, I am unable to find a way to query only for products with a SKU using WC_Product_Query and related functions alone:

This won't work:
```php
            $products = wc_get_products([
                'return' => 'ids',
                'limit' => -1,
                'sku' => '' // this will get removed entirely before going to MySQL
            ]);
```
 You also cannot use SQL wildcards:
```php
            $products = wc_get_products([
                'return' => 'ids',
                'limit' => -1,
                'sku' => '_' // this will get escaped and interpreted as an actual string, eg. LIKE %\_%
            ]);
```

And even if you resignate and try to inject a WP Meta Query as a last resort, it will get removed:

```php
            $products = wc_get_products([
                'return' => 'ids',
                'limit' => -1,
                'meta_query' => [ [ 'key' => '_sku', 'compare' => 'EXISTS'  ] ] // The entire meta query entry will be removed
            ]);
```

**Describe the solution you'd like**
The easiest and most straightforward solution would probably be if passing ```'sku' => '' ``` would not result in the query being removed entirely and instead return products that have ***any*** SKU

**Describe alternatives you've considered**
You could certainly use plain old WP_Query stuff but since we're tied to using and supporting the new Data Stores and their API, this is not a sustainable solution.

**Comment by claudiulodro** [comment]
> The easiest and most straightforward solution would probably be if passing 'sku' => '' would not result in the query being removed entirely and instead return products that have any SKU

I think something similar to this makes sense, however passing in an empty string should in theory also get products with an empty string as/in their SKU (making it essentially get the same results as it does now).

I think support for the common wildcard character `*` may be a good alternative solution.

**Comment by claudiulodro** [comment]
@wackywombaat12 please feel free to open a PR with a solution. Thanks!
