### ISSUE TITLE
On new customer sign-up, add a banner indicating that confirmation email was sent

### ISSUE THREAD

**Issue by pauljacobson** [woocommerce/woocommerce#20995]
This enhancement request originates in a chat with a user at 3440687-hc.

### Context

When a user configures their account registration process to enable customer sign-ups on the **My Account** page using the following options:

![](http://cld.wthms.co/XNSAY1+)

### The problem

When a new customer signs up using the option to simply add their email address, there is no indication given that an email has been sent to that new customer that contains their password.

![](http://cld.wthms.co/TPVQXk+)

This may lead a customer to believe that they've created an insecure password that only requires an email address to sign in (despite the password field in the **Login** field to the left - which may only add to the confusion).

Even if the user changes the account creation options to require a new customer to provide a username and password, there still isn't a notification about an email confirming this step (a standard part of account creation processes for the most part).

## Describe the solution you'd like

Just as the form displays an "error" banner when a person tries to login using an unregistered email address, a new customer should be presented with a banner informing them that an email has been sent to them with their password (in the event this option is enabled) or confirming their registration on the site.

Here is the "error" banner, as an example of the style of banner to present to a new customer:

![](http://cld.wthms.co/q7hh9p+)

## Describe alternatives you've considered

An alternative to this is to add a one-time text to the effect that the new customer should check their email for their password or account confirmation, here:

![](http://cld.wthms.co/N5oMsh+)

Another suggestion I received is that a user can add copy about this signup process to their FAQ. This is counter-intuitive, and I don't believe that this is conducive to a good UX for customers who expect some sort of notification that they have an email waiting for them.

## Additional context

The issue that prompted this request was a user who wasn't aware that these emails were being sent, despite being the site owner. This is possibly as much about a new customer's experience of a WooCommerce signup process, as it is about users' confidence in this being a secure process that takes advantage of passwords, and so on.

**Comment by rodrigoprimo** [comment]
I consider this a bug and not a feature request, but I'm not the best person to make this call. Labeling this issue as a bug for now. I think that adding a green banner in the My Account page with a message saying that the password was sent to the provided e-mail address is a good enough. cc @josemarques for input from someone from the design team.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22650
