### ISSUE TITLE
Wrong cart price by 1 cent

### ISSUE THREAD

**Issue by otpabu** [woocommerce/woocommerce#20997]
**Describe the bug**
Sometimes WooCommerce adds or removes 1 cent in the total cart price.

I've read that the issue was fixed in 2017, but that's not the case for me, as I'm using the latest WooCommerce version (3.4.4).

**To Reproduce**
- Set your products so that their prices are inclusive of taxes (22% in my case).
- Add some of them to your cart.
- Check if the total price is correct.

The bug doesn't happen every time. Actually, most of the times the total price is correct, but sometimes there is a 1 cent difference. Changing the option to calculate the tax in the subtotal or not doesn't make any difference.

**Screenshots**

http://oi67.tinypic.com/2wcqng6.jpg

http://oi67.tinypic.com/2z9d2wz.jpg

NOTE: screenshots are from my live site, but I've also tried in a local enviroment with no plugins but WooCommerce and I was still able to reproduce the bug.

**Expected behavior**
WooCommerce should not add or remove 1 cent in the total cart price.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://www.ottavianobiella.it
Site URL: https://www.ottavianobiella.it
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.7-0ubuntu0.18.04.2
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.7.23-0ubuntu0.18.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: ottavianobiella_
Dimensione totale database: 269.11MB
Dimensione dati database: 224.63MB
Dimensione indice database: 44.48MB
ottavianobiella_woocommerce_sessions: Dati: 114.39MB + Indice: 2.02MB
ottavianobiella_woocommerce_api_keys: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_woocommerce_attribute_taxonomies: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_woocommerce_downloadable_product_permissions: Dati: 0.02MB + Indice: 0.05MB
ottavianobiella_woocommerce_order_items: Dati: 0.52MB + Indice: 0.19MB
ottavianobiella_woocommerce_order_itemmeta: Dati: 3.52MB + Indice: 3.03MB
ottavianobiella_woocommerce_tax_rates: Dati: 0.02MB + Indice: 0.06MB
ottavianobiella_woocommerce_tax_rate_locations: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_woocommerce_shipping_zones: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_woocommerce_shipping_zone_locations: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_woocommerce_shipping_zone_methods: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_woocommerce_payment_tokens: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_woocommerce_payment_tokenmeta: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_woocommerce_log: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_ac_abandoned_cart_history_lite: Dati: 10.52MB + Indice: 0.00MB
ottavianobiella_ac_email_templates_lite: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_ac_guest_abandoned_cart_history_lite: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_ac_sent_history_lite: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_apto_sort_list: Dati: 0.13MB + Indice: 0.06MB
ottavianobiella_commentmeta: Dati: 0.02MB + Indice: 0.05MB
ottavianobiella_comments: Dati: 0.25MB + Indice: 0.30MB
ottavianobiella_failed_jobs: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_links: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_mailchimp_carts: Dati: 0.09MB + Indice: 0.00MB
ottavianobiella_ngg_album: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_ngg_gallery: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_ngg_pictures: Dati: 0.08MB + Indice: 0.02MB
ottavianobiella_options: Dati: 5.42MB + Indice: 2.47MB
ottavianobiella_postmeta: Dati: 53.58MB + Indice: 18.06MB
ottavianobiella_posts: Dati: 12.52MB + Indice: 3.72MB
ottavianobiella_post_views: Dati: 2.52MB + Indice: 2.88MB
ottavianobiella_prli_clicks: Dati: 0.09MB + Indice: 0.23MB
ottavianobiella_prli_groups: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_prli_links: Dati: 0.02MB + Indice: 0.16MB
ottavianobiella_prli_link_metas: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_queue: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_smush_dir_images: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_snippets: Dati: 0.06MB + Indice: 0.00MB
ottavianobiella_social_users: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_termmeta: Dati: 1.52MB + Indice: 0.56MB
ottavianobiella_terms: Dati: 0.30MB + Indice: 0.28MB
ottavianobiella_term_relationships: Dati: 2.52MB + Indice: 1.52MB
ottavianobiella_term_taxonomy: Dati: 0.44MB + Indice: 0.30MB
ottavianobiella_usermeta: Dati: 8.52MB + Indice: 7.03MB
ottavianobiella_users: Dati: 1.52MB + Indice: 0.41MB
ottavianobiella_wc_download_log: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_wc_webhooks: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_wfBadLeechers: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfBlockedCommentLog: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfBlockedIPLog: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfBlocks7: Dati: 0.02MB + Indice: 0.05MB
ottavianobiella_wfConfig: Dati: 0.05MB + Indice: 0.00MB
ottavianobiella_wfCrawlers: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfFileChanges: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfFileMods: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfHits: Dati: 1.52MB + Indice: 0.19MB
ottavianobiella_wfHoover: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_wfIssues: Dati: 0.02MB + Indice: 0.06MB
ottavianobiella_wfKnownFileList: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfLeechers: Dati: 3.02MB + Indice: 0.00MB
ottavianobiella_wfLiveTrafficHuman: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_wfLocs: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfLogins: Dati: 0.14MB + Indice: 0.06MB
ottavianobiella_wfNotifications: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfPendingIssues: Dati: 0.02MB + Indice: 0.06MB
ottavianobiella_wfReverseCache: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfScanners: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_wfSNIPCache: Dati: 0.02MB + Indice: 0.05MB
ottavianobiella_wfStatus: Dati: 0.02MB + Indice: 0.03MB
ottavianobiella_wfVulnScanners: Dati: 0.02MB + Indice: 0.00MB
ottavianobiella_woos_search_trends: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_yith_wcwl: Dati: 0.02MB + Indice: 0.02MB
ottavianobiella_yith_wcwl_lists: Dati: 0.02MB + Indice: 0.05MB
ottavianobiella_yoast_seo_links: Dati: 0.14MB + Indice: 0.06MB
ottavianobiella_yoast_seo_meta: Dati: 0.27MB + Indice: 0.00MB

### Post Type Counts ###

apto_sort: 40
attachment: 7356
custom_css: 1
display_type: 7
featured_item: 8
mc4wp-form: 1
nav_menu_item: 118
ngg_gallery: 9
ngg_pictures: 200
page: 27
popup: 1
popup_theme: 1
post: 34
product: 5400
product_variation: 3
revision: 1
shop_coupon: 10
shop_order: 2302
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (45) ###

Popup Maker: by WP Popup Maker – 1.7.29
Advanced Post Types Order: by Nsp Code – 4.0.9.8
Ban Hammer: by Mika Epstein – 2.6.1
Change Quantity on Checkout for WooCommerce: by Bhavik Kiri – 1.0 – Non testato con la versione attiva di WooCommerce
Code Snippets: by Shea Bunge – 2.10.2
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.50
Contact Form 7: by Takayuki Miyoshi – 5.0.3
Cookie Notice: by dFactory – 1.2.44
Custom Order Status for WooCommerce: by Algoritmika Ltd – 1.3.5
Disqus Conditional Load: by Joel James – 10.2.4
Enhanced E-commerce for Woocommerce store: by Tatvic – 2.1.1
Fast Velocity Minify: by Raul Peixoto – 2.3.4
FG PrestaShop to WooCommerce Premium: by Frédéric GILLES – 3.39.0 – Non testato con la versione attiva di WooCommerce
Gestpay for WooCommerce: by Easy Nolo (Gruppo Banca Sella) – 20180606 – Non testato con la versione attiva di WooCommerce
Tradurre con Loco: by Tim Whitlock – 2.1.4
MailChimp for WooCommerce: by MailChimp – 2.1.9 – Non testato con la versione attiva di WooCommerce
MailChimp per Wordpress: by ibericode – 4.2.4
Nextend Social Login: by Nextendweb – 3.0.12
Perfect WooCommerce Brands: by Alberto de Vera Sevilla – 1.6.5
PixelYourSite: by PixelYourSite – 5.3.1 – Non testato con la versione attiva di WooCommerce
Post Views Counter: by dFactory – 1.2.13
WooCommerce Product Filter: by Mihajlovic Nenad – 6.5.8
Pretty Links: by Blair Williams – 2.1.6
Tawk.to Live Chat: by Tawkto – 0.3.4
Username Changer: by Daniel J Griffiths – 3.1.3
WC Exporter for Danea - Premium: by ilGhera – 1.0.1
WC Importer for Danea - Premium: by ilGhera – 1.0.1
WooCommerce Product Feed Pro: by WebAppick – 2.2.20 – Non testato con la versione attiva di WooCommerce
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.2.8
Woocommerce Email Verification: by XLPlugins – 3.2.0
Woo Preview Emails: by Digamber Pradhan – 1.4.0 – Non testato con la versione attiva di WooCommerce
Woo Search Box: by Guaven Labs – 2.0.2 – Non testato con la versione attiva di WooCommerce
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.0.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.1
WooCommerce AdWords Conversion Tracking: by Wolf+Bär Agency – 1.4.8
WooCommerce Pay for Payment: by Karolína Vyskočilová – 2.0.7 – Non testato con la versione attiva di WooCommerce
WooCommerce: by Automattic – 3.4.4
Wordfence Security: by Wordfence – 7.1.10
Yoast SEO: by Team Yoast – 7.9.1
WP Mail SMTP: by WPForms – 1.3.3
Smush: by WPMU DEV – 2.8.0.1
WP Super Cache: by Automattic – 1.6.2
WP-Sweep: by Lester 'GaMerZ' Chan – 1.0.12
YITH WooCommerce Wishlist: by YITHEMES – 2.2.3
NextGEN Gallery: by Imagely – 3.0.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
variable (variable)

Taxonomies: Product Visibility: featured (featured)
outofstock (outofstock)

### WC Pages ###

Shop base: #134 - /negozio/
Carrello: #133 - /carrello/
Cassa: #132 - /cassa/
Il mio account: #131 - /account/
Termini e condizioni: #20 - /condizioni-di-vendita/

### Theme ###

Name: Flatsome
Version: 3.6.1
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php versione 3.4.0 è obsoleta. La versione attuale è 3.4.4
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/emails/admin-cancelled-order.php
flatsome/woocommerce/emails/admin-failed-order.php
flatsome/woocommerce/emails/admin-new-order.php
flatsome/woocommerce/emails/customer-completed-order.php
flatsome/woocommerce/emails/customer-invoice.php
flatsome/woocommerce/emails/customer-new-account.php
flatsome/woocommerce/emails/customer-note.php
flatsome/woocommerce/emails/customer-on-hold-order.php
flatsome/woocommerce/emails/customer-processing-order.php
flatsome/woocommerce/emails/customer-refunded-order.php
flatsome/woocommerce/emails/customer-reset-password.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Scopri come aggiornare
`
</details>

**Comment by claudiulodro** [comment]
Hi there,

I wasn't able to reproduce this:

------------------------------------------
<img width="468" alt="screen shot 2018-08-07 at 11 43 16 am" src="https://user-images.githubusercontent.com/7317227/43795838-6295207c-9a37-11e8-940d-7528d79be5b6.png">

------------------------------------------

<img width="469" alt="screen shot 2018-08-07 at 11 44 57 am" src="https://user-images.githubusercontent.com/7317227/43795839-62abc0fc-9a37-11e8-8351-6014a474ae06.png">
------------------------------------------

Settings:
- Prices entered with: Inclusive tax
- Display prices during cart and checkout: Including tax
- 22.0% tax rate
- Round tax per line, not subtotal.

Anything different with yours or anything I've missed?

**Comment by otpabu** [comment]
Hi,

It seems strange. Can you try with prices in Euro?

**Comment by otpabu** [comment]
By the way, it also happens while calculating the total order price.

http://oi66.tinypic.com/34zhbnl.jpg

This is a real customer order.

In this case the prices are correct, but there is 1 cent more in the total.

**Comment by otpabu** [comment]
Thank you. I also found that setting WooCommerce to calculate the tax in the subtotal helps.

**Comment by Chavife** [comment]
> Thank you. I also found that setting WooCommerce to calculate the tax in the subtotal helps.
Sort of..  It ruins the front end calculation (in my case of problem this setting just alternates the problem between the front and back end)

**Comment by AKSUTAH** [comment]
I reported this some time ago, was closed...   https://github.com/woocommerce/woocommerce/issues/19792

**Comment by SiR-DanieL** [comment]
One more report in 1424025-zen

**Comment by AashikP** [comment]
Just pinging here to report that the ticket 1424025-zen is back on top of the queue.

**Comment by mikejolley** [comment]
Also struggling to replicate an issue here, and we have some unit tests in place testing this kind of rounding which are passing.

I thought it could have been due to a location outside of the store base, but even in that setup, the taxes add up. My calculated tax is 1cent more than yours. See @claudiulodro screenshot which matches mine.

Rounding should not be done at subtotal level. That causes other issues.

If you can test this setup on a clean instead and compare you may find other results -- right now I can only think of a plugin/theme conflict adjusting these values. 

Either that or the product prices have been entered with too much precision. In my test case I'm using 2 products; one costing 22.50 and one costing 46.00. The tax on that should be 12.36, not 12.35 as shown in your screenshot.

If you revisit this issue and can present a reproducable test case, showing product prices, tax rates, and any other previlant settings, and showing how we can get the same issue, we'll look at this again. That goes for anyone else who can reproduce this.

Thanks

**Comment by GRSM78** [comment]
I have the same issue - when you add >2 pieces the total amount is +1c. https://monosnap.com/file/I7JnEIMxgE6AkeCwPfavpvnYOesKup

**Comment by GRSM78** [comment]
OK it actually happens only when you choose option that product prices include taxes - it makes some funny rounding....

**Comment by hookahcyprus** [comment]
Hi to all new to all this have you managed to find a solution to this?
I am having the same issue my subtotal is sometimes 1 cent more or 1 cent less?
Working with Wordpress 5.2.1 and woocommerce 3.6.3

**Comment by scottybo** [comment]
Having the same issue - it happens when adding more than 1 product to the cart. As you can see in the image below, the product is £10, but when we have two items it removes a penny.

Surely the calculation should be a simple **ROUNDED** PRODUCT PRICE * QUANTITY rather than all this odd rounding?

**Comment by scottybo** [comment]
Just to add, I was discussing this with someone who ran into the same issue with values being off when using the API / JSON. Apparently it was caused by the way PHP 7.2+ handles calculations.

**Comment by CrowFox** [comment]
Having the same issue.   Approx 10% of all orders are 1 cent higher than the value being sent to Stripe and/or Authorize.net for Authorization.   So when I complete the order errors are received and I have to capture manually because the capture amount is $0.01 too high.   

Any help would be greatly appreciated...

**Comment by ibrahimonder** [comment]
I am having the same issues recently with my orders combined with Woocommerce Subsctiptions. For some reason my new customers are paying 1 cent extra.

**Comment by AKSUTAH** [comment]
I wrote a code to round all prices in cart by one cent right before
checkout. Problem solved.

**Comment by CrowFox** [comment]
AKSUTAH would you be willing to share?   
It seems strange that we should have to round down - all we need is for the amount authorized to be the same as the amount charged.

**Comment by zog2** [comment]
I am also having a similar issue. We sell food products without tax, but we allow coupons, e.g., 20% off. When customers use the % off coupons, we sometimes get this rounding issue, where the initial admin new order email shows the total as $0.01 higher than the "true total" (shown on the orders page). 

The customers are being charged the "true total" at the payment provider but the discrepancy causes concern with accounting.

The fix in #21217 specifically targets the tax rounding issue, so perhaps the same kind of fix needs to be done for subtotal after % off coupons are applied?

**Comment by meostar** [comment]
Same issue i have in my calculation when i activated tax there was 0.01 extra added in cart page , how i fix it, i tryout following settings:
-added prices inclusive of tax at product page.
-**Prices entered with tax** Yes, I will enter prices inclusive of tax (refer follwong screenshot
![Screenshot 2024-05-14 123859](https://github.com/woocommerce/woocommerce/assets/31888110/f10c4252-b8a7-4b22-8c0c-320ea515616b)
