### ISSUE TITLE
Out of / Low Stock Notification content filter

### ISSUE THREAD

**Issue by dcnelson89** [woocommerce/woocommerce#20996]
I'm looking for a way to hook into the Out of and Low Stock notification content, I've found the following filters:

`woocommerce_email_content_low_stock` and `woocommerce_email_content_no_stock`

And with these I can echo out plain text, but I seem unable to pull the product info into them.
Specifically I'm looking to pull in a custom meta field (ACF) and sanitise a date/time in the variation name.

Default output is:
 `Test Course - {"type":"range","dates":["2018-09-04","2018-09-05"]} (#1014) is low in stock. There are 9 left.`

The variation name is formatted like this for certain other processes, but I need to clean it up for my (admin facing) client when they receive the email. I already have a `preg_replace` to tidy this up, but my problem is that I can't pull the Product Name + Variation into my custom filter.

My filter:

```
add_filter( 'woocommerce_email_content_low_stock', 'custom_low_stock_content' );

function custom_low_stock_content( $product ){

	 $message = $product->get_formatted_name()." in ". get_field('course_location') ." is almost full. There are only ".$product->get_stock_quantity()." vacancies left.";
		 
	 return $message;
}
```

Cart / Checkout Error
SyntaxError: Unexpected token < in JSON at position 0
`Fatal error: Call to a member function get_formatted_name() on string `

**Comment by rodrigoprimo** [comment]
The product is passed as the second parameter to the filters, the first parameter is the message:

https://github.com/woocommerce/woocommerce/blob/c3144012a5cce19bd1a666a135010ff53cc78dbe/includes/class-wc-emails.php#L579

This is not a support channel. We use GitHub issues exclusively for WooCommerce bugs, enhancements and feature requests. Next time you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce) or another WooCommerce support channel.
