### ISSUE TITLE
Record the customer IP address upon payment for admin-created orders

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#21002]
**Describe the bug**

For some shops, the shop owner creates the order in the backend, and sends the customer a link to the order payment page.

This results in the shop owner's IP address going in the `_customer_ip_address` meta field, instead of the customer's. i.e. The methods `WC_Order::set_customer_ip_address()` `WC_Order::get_customer_ip_address` are actually setting/getting the "order creator's" IP address, rather than the customer's.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an order in the admin area
2. Observe the customer IP address in the order screen

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiulodro** [comment]
Hi David,

How do you propose getting the customer's ip address when the shop owner creates the order? Admin seems like the correct IP to use there, as that's the computer that created the order.

**Comment by peterfabian** [comment]
See https://github.com/woocommerce/woocommerce/pull/21038.

Btw, I'm looking forward to those VAT disputes: a tax resident of Country A, who created an order while being on vacation in country B, with a credit card having billing address in country C and then actually paid the order while shortly visiting country D, getting the product shipped to country E. :)

**Comment by DavidAnderson684** [comment]
Thanks. FWIW, in that situation, under the law, the VAT for country A should be charged. The shop will not be able to provide two items from the list of approved evidences for audit. So, in theory, shops are meant to review such an order manually and decide whether they will accept the risk involved. You can make your own guesses about what happens in practice!
