### ISSUE TITLE
If the % symbol is used in the product name before other symbols - the slug isn't generated correctly and the product name on the order is incorrect, too

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce#21012]
**Describe the bug**
If the % symbol is used in the product name before other symbols - the slug isn't generated correctly and the product name on the order is incorrect, too

**To Reproduce**
1. Create a new product and name it Product %100 
2. The slug will be product-0:
![screenshot](http://cld.wthms.co/bImULq+) **Image Link:** http://cld.wthms.co/bImULq

3.Purchase the product.
4. On the order page, the product name will be incorrect:

![screenshot](http://cld.wthms.co/uFXS6O+) **Image Link:** http://cld.wthms.co/uFXS6O

**Expected behavior**
The symbol % before 100 should not change the whole value of %100 to 0 on the order page.

I realise this is an edge case scenario so I guess low priority should be assigned.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Irrelevant
```
</details>

**Comment by peterfabian** [comment]
Hi, 

this should be fixed by #20993.

Thanks for reporting.
