### ISSUE TITLE
Product sorting menu on shop page generated by [products] shortcode not working

### ISSUE THREAD

**Issue by BeholdingEye** [woocommerce/woocommerce#21010]
I have tracked down the cause of the problem to the way that `WC_Shortcode_Products->parse_query_args()` makes the call `WC()->query->get_catalog_ordering_args( $query_args['orderby'], $query_args['order'] )` to obtain the ordering args. As the call passes the shortcode `orderby` attribute (possibly a default value), the called query method never considers the value of `$_GET['orderby']` set by the sorting menu choice. Here's hoping this may be fixed in the next Woo update.

## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Create a shop using the `[products]` shortcode
2. Try sorting the shop products using the sorting menu
3. As you use the menu, the `orderby` URL query component will be correctly set, but have no effect

- [ x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

**Comment by kloon** [comment]
See #21011

**Comment by BeholdingEye** [comment]
Fast work, thank you! I see though that you've only amended the `orderby`, not `order`. As some sorts like price also set the latter (`ASC`/`DESC`), that should be considered as well.

**Comment by BeholdingEye** [comment]
Actually, my comment about `order` (`ASC`/`DESC`) may not have been erroneous after all: `price-desc` doesn't seem to work after I apply your fix. Other sorting methods work fine.
