### ISSUE TITLE
Hiding search drop down for "Customer" Role

### ISSUE THREAD

**Issue by Redec-Industrial** [woocommerce/woocommerce#21023]
I am trying to hide the search dropdown results showing for a specific role for my website. I have it set to hidden for logged out users which works perfectly, and I would like to hide it for the role "Customers" as well, but not all roles.
Below is the code that I have tried to use to hide the dropdown results.

MY WEBSITE: http://s2br5s5r3.gb-02.live-paas.net

    .product-search .product-search-results[role="customer"]{
    display: none !important;
    }

![capture](https://user-images.githubusercontent.com/42242534/43901873-7a8f1336-9be0-11e8-8805-9ccf592ee13a.JPG)
![capture1](https://user-images.githubusercontent.com/42242534/43901875-7d0c8d00-9be0-11e8-8cc8-b023f49f78a1.JPG)

**Comment by rodrigoprimo** [comment]
I'm sorry but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce).
