### ISSUE TITLE
OBW: when signing up for mailing list, it doesn't look similar to the rest of OBW

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce#21020]
Before signing up to mailing list:

After:

<img src="https://user-images.githubusercontent.com/2545592/43896829-0cfc96a8-9bd2-11e8-90ba-dae373c418e6.png">

cc @aleftick

**Comment by aleftick** [comment]
<img width="1280" alt="woocommerce-2" src="https://user-images.githubusercontent.com/2545592/43896829-0cfc96a8-9bd2-11e8-90ba-dae373c418e6.png">

**Comment by claudiulodro** [comment]
Not sure the level of customization we can have over that, as it's a Mailchimp screen. @MarinaWoo?

**Comment by claudiulodro** [comment]
This isn't something our team could implement anyways, as that screen isn't in the WooCommerce plugin. Not sure where else to keep this issue though. :P

**Comment by v18** [comment]
I don't really know either where to keep it - let's close if there's nothing we can do to customize.

**Comment by claudiulodro** [comment]
Closing for now. I'll reopen if something actionable pops up around this.

**Comment by MarinaWoo** [comment]
Sorry for being slow, have opened a support ticket to check but afaik it isn't possible to customize this.

**Comment by MarinaWoo** [comment]
This feedback via MailChimp:

> That specific page can't be edited and the reCAPTCHA itself can't be modified, but if you'd like to style that page to have a specific design style like changing the font and background color, this can be done on any other page in the form builder, as changes to the forms themselves are inherited by other pages and forms that a subscriber will encounter.

Our Knowledge Base on the form builder has some additional information on that so I'll link that below.

How the Form Builder Works: https://eepurl.com/dyilUk

Let me know if y'all feel this is a priority? We could style the background a bit better. 

CC @garethallison @garymurray

**Comment by MarinaWoo** [comment]
Le artiste strikes again!
