### ISSUE TITLE
Woocommerce slows analogous to product attributes

### ISSUE THREAD

**Issue by ntarki** [woocommerce/woocommerce#21034]
Hello, I have imported around 250 products with up to 180 attributes each.

I noticed the more attributes a product has, to generate the thumbnail in shop slows down accordingly.
I moved the site to my computer and the problem persisted. 
So I started digging around.

-------------------------------

For example: 
Loading **/shop**

To generate a product thumbnail with **61** attributes

the_post();  //  **Takes 0.46 to 0.55 seconds**

I did a var_dump(GLOBAL['product']) and you can see it at https://pastebin.com/YviXveAG

To generate a product thumbnail with **10** attributes

the_post();  //   **Takes 0.08 to 0.11 seconds**

I did a var_dump(GLOBAL['product']) and you can see it at https://pastebin.com/pzhTeTyG

Query analysis report for **/shop displaying 24 products**:

Plugin: woocommerce  Queries:50  Time: 0.0186

Total query time: 0.08seconds

**Sometimes it can go up to 0.3 seconds so it must not be a database problem.**

I noticed the CPU usage goes to 100%.

----------------------------------------

I tried tracing the slowdown, and I noticed that major slowdown happens when 

**wc_get_product** function is triggered

and more specifically 

**return WC()->product_factory->get_product( $the_product, $deprecated );**

By inspecting the  var_dump(GLOBAL['product']) I think the problem is obvious

Creating the following array of objects slows down

        array (size=57)
          'pa_output-power-capacity' => 
            object(WC_Product_Attribute)[14278]
              protected 'data' => 
                array (size=6)
                  'id' => int 367
                  'name' => string 'pa_output-power-capacity' (length=24)
                  'options' => 
                    array (size=1)
                      0 => int 11491
                  'position' => int 0
                  'visible' => boolean true
                  'variation' => boolean true
          'pa_output-power' => 
 
----------------------------------------

So my question is the following...

Is loading the attributes necessary for showing products in /shop or in some category ?

Loading them in the product page I understand but why in /shop ?

Does it have to do with using filters?

If yes, is it not possible to use filters just as a query to prefetch the products and not load all attributes in shop page?

-----------------------------------

I noticed some other people posted the following
https://github.com/woocommerce/woocommerce/issues/20262

Considering the responses, seems there is no solution. I was thinking of passing around a global variable that would skip taxonomies entirely when generating thumbnails of products. I don't know if there are any other implications or cause any problems doing this.

Thank you in advance,
Andreas.

**Comment by rodrigoprimo** [comment]
Would it be possible for you to share a copy of the database or a CSV of the products that you are using (you can find my e-mail on my profile page)? This would be the easiest way to check if there is anything we can do on WooCommerce side to improve product attributes performance for your use case. Last time I checked this was in the issue that you mentioned (#20262), in that case, the problem was simply the number of taxonomies (each product attribute is registered as a WP taxonomy) that WooCommerce had to register on every page load. I haven't investigated yet the issue that you described where the more atributtes a product has the slower it loads on the frontend.

**Comment by ntarki** [comment]
I will contact you as soon as possible and further describe this issue and if there is something that can be done.

**Comment by ntarki** [comment]
I managed to trace the problem to the following function 

File: /includes/data-stores
Function: read_attributes

What I am thinking now is something like the following:

```
		if (isset($GLOBALS['dontshowattribute']) && $GLOBALS['dontshowattribute'] == 1){
		}else{
		$this->read_attributes( $product );
		}
```

Everything seems to work blazing fast with this and attributes filters seem to work fine. 

This might be a crude patch. I will try to get to the bottom of it and maybe come up with a decent solution. Any help appreciated since I am not very experienced.

**Comment by RistoNiinemets** [comment]
I couldn't notice much performance improvements with this, but I can understand the logic to fetch attributes taxonomies only once to reduce DB queries.

**Comment by ntarki** [comment]
It  **highly** depends on the number of attributes and  product attributes.

For example I have a total of around 3350 attributes. ( Slow as #20262 issue 2.5-3 sec to load all attributes). That is okay.

But then it takes analogous time as I mentioned above for each product.
(Because it uses **wc_attribute_taxonomy_id_by_name** which then calls  **wp_list_pluck( wc_get_attribute_taxonomies(), 'attribute_id', 'attribute_name' );** each time when it can be done only once during the page load and not each time.

I am working on a more elegant solution.

**Comment by ntarki** [comment]
My final suggestion would be the following (maybe change the name of global variable):

File: **/includes/wc-attribute-functions.php**
Function: **wc_attribute_taxonomy_id_by_name**
`function wc_attribute_taxonomy_id_by_name( $name ) {
	$name       = str_replace( 'pa_', '', wc_sanitize_taxonomy_name( $name ) );
  	//Check if there has been a search for attribute taxonomies before
	if (isset($GLOBALS['attribute_list_taxonomy'])){
		//If there was pass the results
		$taxonomies = $GLOBALS['attribute_list_taxonomy'];
	}else{
		//If there was NOT then search attribute taxonomies
		$GLOBALS['attribute_list_taxonomy'] = wp_list_pluck( wc_get_attribute_taxonomies(), 'attribute_id', 'attribute_name' );
		$taxonomies =  $GLOBALS['attribute_list_taxonomy'];
	}
	return isset( $taxonomies[ $name ] ) ? (int) $taxonomies[ $name ] : 0;
}`

Shaves significant time for large attributes

**Comment by mikejolley** [comment]
@ntarki See https://github.com/woocommerce/woocommerce/pull/22938 If you can test those changes that would be great. Closing this issue so please comment on the PR.
