### ISSUE TITLE
Refund and Accounting Issue

### ISSUE THREAD

**Issue by leocheungswell** [woocommerce/woocommerce#21031]
**Is your feature request related to a problem? Please describe.**
We offer 30 days refund which creates a huge problem for our accounting team as the original order total get updated after refund to the customer.

**Describe the solution you'd like**
It would be nice not to modify the original order and save the refund amount in a separate table/location so the original order amount never get updated and could be used for future reference. This is very important for our accounting team.

**Describe alternatives you've considered**

**Additional context**

**Comment by rodrigoprimo** [comment]
I'm not sure what is your specific use case, but refunds are already stored separately, and the original order information is not updated in the database. When an order is placed, a new entry is created in the `wp_posts` table using the post_type `shop_order`. Information like the order total can be found in the `wp_postmeta` table. When an order is refunded the order information is preserved and a new entry is added to `wp_posts` using the post_type `shop_order_refund`. A refund entry refers back to its order using the field `post_parent`.

I'm closing this for now. Please provide more details if I missed something and we will reopen. Thanks.
