### ISSUE TITLE
Checkout Tax Rates Save at Order Level.

### ISSUE THREAD

**Issue by leocheungswell** [woocommerce/woocommerce#21030]
**Is your feature request related to a problem? Please describe.**
When running previous monthly sales report after updating the new tax rates, there is no way to know what tax rate it was at checkout since it always reference to the tax table.

**Describe the solution you'd like**
It would be nice to save the tax rate at the order level after checkout. For any reporting, the tax rate and tax amount should reference at the order level not from the tax table.

**Comment by claudiulodro** [comment]
Hi there,

I believe the [new reports under development now](https://github.com/woocommerce/wc-admin/issues/172) should solve this issue, as the tax code info for the report will be saved in a custom table that has all the tax info for each order. If you're anxious to get your hands on the next generation of WooCommerce reports, there should be a feature plugin available at that repo within the next few months.

Thanks.
