### ISSUE TITLE
Product's Vendor changed when it is purchased by another Vendor

### ISSUE THREAD

**Issue by yeeloont** [woocommerce/woocommerce#21036]
I am using Woocommerce and WC Marketplace on Wordpress to allow multiple vendors to sell and purchase their products. When a Vendor checked "Manage Stock" for his product to be on sale, the ownership will changed to another Vendor who has purchased it. This doesn't happen if 
1. Vendor doesn't choose to Manage Stock
2. Product is purchased by a Non-vendor(anyone who doesn't login or is not a Vendor)

**To Reproduce**
1. Vendor A creates a new product on Vendor Dashboard. Vendor A set the product as Simple Product and check the box "Virtue"
2. Under Inventory, Vendor A checks "Manage Stock" and set the stock quantity (i.e. 3)
3. Vendor A fills in the respective fields and submit the product for Admin's approval 
4.  Admin approves the product and it is available for sale.
5. Vendor B login to his account and purchase the product (Quantity 1). Vendor B completes the purchase process
6. Now the product (with the stock balance: 2 units) belongs to Vendor B. 
7. Vendor A was only paid for the cost of 1 unit of the product and lost his ownership to the product.

**Comment by rodrigoprimo** [comment]
This issue tracker is used exclusively for WooCommerce core problems. It seems that your issue is related to a WooCommerce extension. please contact WC Marketplace developers for support.
