### ISSUE TITLE
XML injected in wiki

### ISSUE THREAD

**Issue by derwentx** [woocommerce/woocommerce#21041]
**Describe the bug**
Looks like whatever generated the page on the wiki has accidentally injected some XML

**To Reproduce**
1. Go to https://github.com/woocommerce/woocommerce/wiki/WP-CLI-commands
2. the injected xml starts at the beginning of the page

**Screenshots**
![screenshot](https://i.imgur.com/Lye5KPr.png)

**Comment by rodrigoprimo** [comment]
I'm not sure why this page was recreated earlier this year and I just removed it. Its contents were moved to https://github.com/woocommerce/woocommerce/wiki/Legacy-CLI-commands-(v2.6-and-below) back in March 2017. Thanks for bringing this issue our attention.
