### ISSUE TITLE
Multiple store credit coupons don't apply full discount

### ISSUE THREAD

**Issue by AshcatY2K** [woocommerce/woocommerce#21042]
**Describe the bug**
When multiple store credit coupons are used on a cart the discount applied is less than the total value of the coupons. As an example if I apply a R 500 and a R 150 coupon they are applied to the cart  as a R 200 and R 150 respectively. My cart total goes from R 1 497 to R 1 147. Also if the discount is applied to a cart that has a total less than the total discount amount the cart receives a negative total.

**To Reproduce**
1. Add 2+ store credit coupons to your cart
2. See if the total discount applied to your cart is for the full store credit amount

**Expected behavior**
When I apply multiple store credit coupons I expect the maximum amount of discount that can be applied to the cart to be applied without the cart receiving a negative value. Part of this problem stems from how coupons are applied to the cart. For example if I apply a R 150 coupon to the cart it's discount will be split between all products in the current cart. If I then apply a R 500 coupon, that excludes certain products in the cart, it will attempt to split it's discount among the remaining total of the products that it can apply to. So the coupons might not be able to 

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://beta.isabellagarcia.co.za
Site URL: https://beta.isabellagarcia.co.za
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.31-1+0~20180725100222.2+jessie~1.gbp8e8a8b - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.36-MariaDB-1~jessie
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: ig_
Total Database Size: 1317.07MB
Database Data Size: 689.84MB
Database Index Size: 627.23MB
ig_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
ig_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
ig_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
ig_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
ig_woocommerce_order_items: Data: 5.52MB + Index: 2.52MB
ig_woocommerce_order_itemmeta: Data: 69.58MB + Index: 29.09MB
ig_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
ig_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
ig_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
ig_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
ig_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
ig_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
ig_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
ig_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ig_aws_cache: Data: 0.02MB + Index: 0.00MB
ig_aws_index: Data: 0.45MB + Index: 0.00MB
ig_bwps_lockouts: Data: 0.02MB + Index: 0.00MB
ig_bwps_log: Data: 0.02MB + Index: 0.00MB
ig_clean_up_optimizer: Data: 7.52MB + Index: 0.00MB
ig_clean_up_optimizer_meta: Data: 73.59MB + Index: 0.00MB
ig_commentmeta: Data: 0.30MB + Index: 0.30MB
ig_comments: Data: 11.52MB + Index: 10.09MB
ig_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
ig_gf_addon_payment_callback: Data: 0.02MB + Index: 0.02MB
ig_gf_addon_payment_transaction: Data: 0.02MB + Index: 0.05MB
ig_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
ig_gf_entry: Data: 26.56MB + Index: 6.03MB
ig_gf_entry_meta: Data: 89.63MB + Index: 149.14MB
ig_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
ig_gf_form: Data: 0.02MB + Index: 0.00MB
ig_gf_form_meta: Data: 2.52MB + Index: 0.00MB
ig_gf_form_view: Data: 3.52MB + Index: 3.03MB
ig_gift_by_order: Data: 0.02MB + Index: 0.00MB
ig_gift_products: Data: 0.02MB + Index: 0.00MB
ig_imagify_files: Data: 0.02MB + Index: 0.08MB
ig_imagify_folders: Data: 0.02MB + Index: 0.03MB
ig_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB
ig_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
ig_itsec_logs: Data: 22.52MB + Index: 10.09MB
ig_itsec_temp: Data: 0.09MB + Index: 0.16MB
ig_links: Data: 0.02MB + Index: 0.02MB
ig_mf_custom_field_options: Data: 0.02MB + Index: 0.00MB
ig_mf_custom_field_properties: Data: 0.02MB + Index: 0.00MB
ig_mf_module_groups: Data: 0.02MB + Index: 0.00MB
ig_mf_panel_category: Data: 0.02MB + Index: 0.00MB
ig_mf_panel_custom_field: Data: 0.02MB + Index: 0.00MB
ig_mf_panel_standard_field: Data: 0.02MB + Index: 0.00MB
ig_mf_posttypes_taxonomies: Data: 0.02MB + Index: 0.00MB
ig_mf_post_meta: Data: 0.02MB + Index: 0.00MB
ig_mf_write_panels: Data: 0.02MB + Index: 0.00MB
ig_options: Data: 9.45MB + Index: 0.20MB
ig_postmeta: Data: 117.66MB + Index: 133.39MB
ig_posts: Data: 16.55MB + Index: 10.06MB
ig_revslider_css: Data: 0.13MB + Index: 0.00MB
ig_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
ig_revslider_navigations: Data: 0.02MB + Index: 0.00MB
ig_revslider_sliders: Data: 0.05MB + Index: 0.00MB
ig_revslider_slides: Data: 0.39MB + Index: 0.00MB
ig_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
ig_rg_form: Data: 0.02MB + Index: 0.00MB
ig_rg_form_meta: Data: 2.52MB + Index: 0.00MB
ig_rg_form_view: Data: 3.52MB + Index: 3.03MB
ig_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
ig_rg_lead: Data: 25.56MB + Index: 5.03MB
ig_rg_lead_detail: Data: 63.61MB + Index: 125.47MB
ig_rg_lead_detail_long: Data: 5.52MB + Index: 0.00MB
ig_rg_lead_meta: Data: 7.52MB + Index: 7.55MB
ig_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
ig_rg_userregistration: Data: 0.02MB + Index: 0.02MB
ig_signups: Data: 0.02MB + Index: 0.06MB
ig_termmeta: Data: 0.11MB + Index: 0.06MB
ig_terms: Data: 0.05MB + Index: 0.03MB
ig_term_relationships: Data: 0.13MB + Index: 0.08MB
ig_term_taxonomy: Data: 0.02MB + Index: 0.03MB
ig_usermeta: Data: 114.66MB + Index: 123.36MB
ig_users: Data: 6.52MB + Index: 7.55MB
ig_wc_download_log: Data: 0.02MB + Index: 0.03MB
ig_wc_webhooks: Data: 0.02MB + Index: 0.02MB
ig_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB
ig_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB
ig_yoast_seo_links: Data: 0.05MB + Index: 0.02MB
ig_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB

### Post Type Counts ###

affcoups_coupon: 1
affcoups_vendor: 1
attachment: 306
employee-testimonial: 3
fusion_element: 1
fusion_template: 2
gift_card: 38
nav_menu_item: 117
newsletters: 10
page: 97
popups: 1
post: 2
product: 91
revision: 13
shop_coupon: 40193
shop_order: 14718
testimonials: 54
wafs: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

WooCommerce Smart Coupons: by WooCommerce – 3.4.7
WooCommerce Stock Manager: by Vladislav Musílek – 1.2.6 – Not tested with the active version of WooCommerce
WooCommerce Store Credit: by WooCommerce – 2.1.16
WooCommerce: by Automattic – 3.4.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #127 - /shop/
Cart: #128 - /cart/
Checkout: #129 - /checkout/
My account: #130 - /my-account/
Terms and conditions: #25 - /terms-conditions/

### Theme ###

Name: Isabella Garcia 2018
Version: 1.64
Author URL: https://bigbrave.digital
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.5.2
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: isabellagarcia2018/woocommerce/archive-product.php
Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
isabellagarcia2018/woocommerce/checkout/thankyou.php
isabellagarcia2018/woocommerce/emails/customer-completed-order.php
isabellagarcia2018/woocommerce/emails/customer-processing-order.php
isabellagarcia2018/woocommerce/emails/email-footer.php
isabellagarcia2018/woocommerce/emails/email-styles.php
Avada/woocommerce/loop/loop-start.php
isabellagarcia2018/woocommerce/loop/pagination.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 3.0.0 is out of date. The core version is 3.4.0
isabellagarcia2018/woocommerce/single-product/meta.php
isabellagarcia2018/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php
isabellagarcia2018/woocommerce/single-product/tabs/tabs.php
isabellagarcia2018/woocommerce/single-product/up-sells.php
isabellagarcia2018/woocommerce/single-product.php
isabellagarcia2018/taxonomy-product_cat.php

Outdated Templates: ❌
					
					
						Learn how to update
`
</details>

**Comment by rodrigoprimo** [comment]
This issue tracker is used exclusively for WooCommerce core issues, and it seems that the problem you are having is related to WooCommerce Store Credit. To get support for this extension, could you please open a ticket in the link below?

https://woocommerce.com/contact-us/
