### ISSUE TITLE
Dynamic Pricing plugin rename product inside a group product

### ISSUE THREAD

**Issue by pavithraidl** [woocommerce/woocommerce#21040]
**Describe the bug**
When I create a group product and add a linked product into that group product, if I have Dynamic Pricing plugin active, it renames those linked product name to the group product name.

Ex: I create a group product name called "Alpha". Then I go to the linked product section and add two more products (already created products) called Apple and Orange. Then I save that group product.

After saving the group product, those Apple and Orange names renamed to Alpha (group product name). That only happens if I have Dynamic Pricing plugin active.

**Comment by rodrigoprimo** [comment]
This issue tracker is used exclusively for WooCommerce core issues, and it seems that the problem you are having is caused by Dynamic Pricing. Could you please open a ticket in the link below?

https://woocommerce.com/contact-us/
