### ISSUE TITLE
Taxes are not added to my prices, not matter what my settings are

### ISSUE THREAD

**Issue by oliverdavidkrieg** [woocommerce/woocommerce#21059]
Hi there,

my little online shop doesn't seem to follow German law for showing prices INCL. VAT. No matter what my settings are it seems to show the price without VAT for a (German) customer.

Have a look yourself: https://odk.design/?page_id=2160

Geolocate with or without cache, or even using the shop location (set to Germany) is not producing the price incl. VAT. I added the "incl. VAT" because the Woocommerce Germanized plugin didn't seem to add the tax notification either. The cause of these problems seems to be the same, namely that my shop doesn't include taxes until you're in the Cart Page. Judging from the Cart Page the standard location is the US for some reason.

It does show VAT and always VAT when I'm logged in to Wordpress. Any ideas?

**Comment by peterfabian** [comment]
Hi, 

Have you tried this with the vanilla WooCommerce installation and Storefront theme? I think it could be one of the plugins causing issues maybe. 

Please follow the (self-service guide)[https://docs.woocommerce.com/document/woocommerce-self-service-guide/] to rule out possible conflicts and include your (system report)[https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/].

Also, it would help to see your tax settings to be able to reproduce the issue.

Thanks.

**Comment by oliverdavidkrieg** [comment]
Hi there,

I have changed to a standard theme and deactivated most of my plugins (except any woocommerce plugins, WPML, or Revolution Slider)

this is my status report. I have attached two screenshots from the tax settings.


### WordPress Environment ###

Home URL: https://odk.design
Site URL: https://odk.design
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.31 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.6.39-83.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 21.09MB
Database Data Size: 15.78MB
Database Index Size: 5.31MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_duplicator_packages: Data: 0.01MB + Index: 0.00MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_icl_content_status: Data: 0.00MB + Index: 0.00MB
wp_icl_core_status: Data: 0.00MB + Index: 0.00MB
wp_icl_flags: Data: 0.00MB + Index: 0.00MB
wp_icl_languages: Data: 0.00MB + Index: 0.01MB
wp_icl_languages_translations: Data: 0.10MB + Index: 0.10MB
wp_icl_locale_map: Data: 0.00MB + Index: 0.00MB
wp_icl_message_status: Data: 0.00MB + Index: 0.00MB
wp_icl_mo_files_domains: Data: 0.00MB + Index: 0.00MB
wp_icl_node: Data: 0.00MB + Index: 0.00MB
wp_icl_reminders: Data: 0.00MB + Index: 0.00MB
wp_icl_strings: Data: 3.93MB + Index: 3.27MB
wp_icl_string_packages: Data: 0.00MB + Index: 0.00MB
wp_icl_string_pages: Data: 0.01MB + Index: 0.02MB
wp_icl_string_positions: Data: 0.01MB + Index: 0.01MB
wp_icl_string_status: Data: 0.00MB + Index: 0.00MB
wp_icl_string_translations: Data: 1.89MB + Index: 0.61MB
wp_icl_string_urls: Data: 0.00MB + Index: 0.01MB
wp_icl_translate: Data: 0.53MB + Index: 0.02MB
wp_icl_translate_job: Data: 0.00MB + Index: 0.00MB
wp_icl_translations: Data: 0.02MB + Index: 0.06MB
wp_icl_translation_batches: Data: 0.00MB + Index: 0.00MB
wp_icl_translation_status: Data: 0.29MB + Index: 0.01MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.20MB + Index: 0.09MB
wp_postmeta: Data: 2.05MB + Index: 0.23MB
wp_posts: Data: 2.36MB + Index: 0.13MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_revslider_css: Data: 0.14MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.14MB + Index: 0.00MB
wp_revslider_slides: Data: 1.33MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.14MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 266
customize_changeset: 8
custom_css: 1
jetpack_migration: 2
jp_img_sitemap: 4
jp_sitemap: 4
jp_sitemap_master: 4
jp_vid_sitemap: 1
mc4wp-form: 2
nav_menu_item: 30
page: 38
portfolio: 15
post: 1
product: 8
revision: 333
shop_order: 3
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.0.5
Akismet Anti-Spam: by Automattic – 4.0.8
Classic Editor: by WordPress Contributors – 0.4
Contact Form 7: by Takayuki Miyoshi – 5.0.3
Duplicator: by Snap Creek – 1.2.40
Envato Market: by Envato – 2.0.0
Google Analytics Germanized: by Pascal Bajorat – 1.4.0
Google Web Fonts Customizer (GWFC): by Chanif Al-Fath – 1.0.2
Jetpack by WordPress.com: by Automattic – 6.4.2
WPBakery Page Builder: by Michael M - WPBakery.com – 5.5.2
Kirki Toolkit: by Aristeides Stathopoulos – 3.0.33
MailChimp for WooCommerce: by MailChimp – 2.1.9 – Not tested with the active version of WooCommerce
MailChimp for WordPress: by ibericode – 4.2.4
Meta Box: by MetaBox.io – 4.15.2
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.0.5

Slider Revolution: by ThemePunch – 5.4.8
Sober Addons: by UIX Themes – 1.3.11
WooCommerce Variation Swatches: by ThemeAlien – 1.0.3 – Not tested with the active version of WooCommerce
WooCommerce Currency Switcher: by realmag777 – 1.2.5.1 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.3 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.8 – Not tested with the active version of WooCommerce
WooCommerce Germanized Pro: by Vendidero – 1.9.3 – Not tested with the active version of WooCommerce
WooCommerce Germanized: by Vendidero – 2.0.4 – Not tested with the active version of WooCommerce
WooCommerce Multilingual: by OnTheGoSystems – 4.3.4 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.15.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.4
Yoast SEO: by Team Yoast – 8.0
MailChimp for WordPress Multilingual: by OnTheGoSystems – 0.0.2
WPML String Translation: by OnTheGoSystems – 2.8.5
WPML Translation Management: by OnTheGoSystems – 2.6.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-de)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /?page_id=4
Cart: #18 - /?page_id=18
Checkout: #19 - /?page_id=19
My account: #20 - /?page_id=20
Terms and conditions: #2601 - /?page_id=2601

### Theme ###

Name: Sober Child Theme
Version: 1.0.0
Author URL: http://uix.store
Child Theme: ✔
Parent Theme Name: Sober
Parent Theme Version: 2.0.20
Parent Theme Author URL: http://uix.store
WooCommerce Support: ✔

### Templates ###

Overrides: sober/woocommerce/cart/cart-shipping.php
sober/woocommerce/cart/cart.php
sober/woocommerce/cart/mini-cart.php
sober/woocommerce/checkout/form-checkout.php
sober/woocommerce/checkout/form-coupon.php
sober/woocommerce/checkout/form-login.php
sober/woocommerce/checkout/review-order.php
sober/woocommerce/global/form-login.php
sober/woocommerce/global/quantity-input.php
sober/woocommerce/global/wrapper-end.php
sober/woocommerce/global/wrapper-start.php
sober/woocommerce/loop/add-to-cart.php
sober/woocommerce/loop/price.php
sober/woocommerce/loop/result-count.php
sober/woocommerce/myaccount/dashboard.php
sober/woocommerce/myaccount/form-edit-account.php
sober/woocommerce/myaccount/form-login.php
sober/woocommerce/myaccount/my-address.php
sober/woocommerce/notices/error.php
sober/woocommerce/notices/success.php
sober/woocommerce/order/form-tracking.php
sober/woocommerce/single-product/add-to-cart/external.php
sober/woocommerce/single-product/add-to-cart/grouped.php
sober/woocommerce/single-product/add-to-cart/simple.php
sober/woocommerce/single-product/add-to-cart/variable.php
sober/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
sober/woocommerce/single-product/product-image.php
sober/woocommerce/single-product/product-thumbnails.php
sober/woocommerce/single-product/related.php
sober/woocommerce/single-product/review-meta.php
sober/woocommerce/single-product/tabs/additional-information.php
sober/woocommerce/single-product/tabs/tabs.php
sober/woocommerce/single-product/up-sells.php
sober/woocommerce/single-product-reviews.php

`
![01](https://user-images.githubusercontent.com/42417113/44225923-93d6aa80-a143-11e8-82f2-4ddfd3905376.PNG)
![02](https://user-images.githubusercontent.com/42417113/44225924-93d6aa80-a143-11e8-8987-d53886e78a7e.PNG)

**Comment by claudiulodro** [comment]
Your tax settings are set for "Calculate tax based on customer shipping address". When I set my location to Germany using the cart shipping calculator the taxes look correct to me:

<img width="1324" alt="screen shot 2018-08-16 at 11 36 20 am" src="https://user-images.githubusercontent.com/7317227/44227972-e23a7800-a148-11e8-8621-04096c998531.png">
<img width="1481" alt="screen shot 2018-08-16 at 11 36 28 am" src="https://user-images.githubusercontent.com/7317227/44227973-e23a7800-a148-11e8-92ad-8d006543c5b8.png">

So the issue seems to be something with geolocation not working properly on your store, as the taxes seem to be working correctly as far as I can tell.

**Comment by oliverdavidkrieg** [comment]
Hi claudiulodro, that is correct. When I set it to "shop based location" and even that doesn't work. It just keeps showing the prices without tax.

Am I correct in assuming that the default customer location set to "geolocate" and "customer shipping address" should geolocate the customer and show the taxes accordingly? Or did I made a silly mistake somewhere? That seems to be the problem here

**Comment by claudiulodro** [comment]
> Am I correct in assuming that the default customer location set to "geolocate" and "customer shipping address" should geolocate the customer and show the taxes accordingly? Or did I made a silly mistake somewhere? That seems to be the problem here

In theory this is how it should work. If geolocation is active it will use the geolocated country as the shipping address for customers that haven't set their location.

One thing you should rule out is caching issues. There have been very similar [reports of the issue you describe and they are almost always caching issues](https://github.com/woocommerce/woocommerce/issues/7939).

**Comment by oliverdavidkrieg** [comment]
That's weird though, because geoscreenshot and others will not show the taxes either.

**Comment by oliverdavidkrieg** [comment]
Edit: Deactivating the Woocommerce Services Plugin deletes all tax settings, afte re-activating the shop-based tax setting at least produced the taxes. But geolocate still doesn't work. What a sketchy problem.

**Comment by mikejolley** [comment]
I don't think it's cache. I think it's a conflict with a plugin you didn't rule out above.

- Set default location to shop base
- Add tax rates for the shop base country (germany)
- Start a new session. You'll see tax inclusive prices.

If you don't then you have a plugin conflict which we can unfortunetely not debug for you. I see several likely culprits and those are:

- Services, which can serve live tax rates and ignore your settings. If it's services, please raise an issue on the help desk.
- WPML - Filters everything. May filter tax rates or customer location.
- WooCommerce Germanized (most likely) does lots of funky things with tax rates 

I'd suggest starting with Germanized. Once you confirm what is causing it, you can contact the relevent developers.

If you can reproduce this issue on an install with no plugins active, except WooCommerce, please reopen with instructions and I'll try it for myself. 

Thanks
