### ISSUE TITLE
Lead Time support for products

### ISSUE THREAD

**Issue by ron819** [woocommerce/woocommerce#21058]
It has previous request: https://github.com/woocommerce/woocommerce/issues/12596
and also has 97 votes on the idea panel:
http://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/17427502-lead-time-for-non-stock-product

Will this be implemented?

**Comment by kloon** [comment]
At present the demand for this is just too low, there are feature requests with many more votes that will take priority depending on how it fits in with our development roadmap.

This should easily be done via an extension that allows adding custom fields to products, or if you are knowledgeable in development you can achieve the same by introducing a custom field on the product.

**Comment by peterfabian** [comment]
Hi, 

Sorry, not really on our radar at the moment. As you can see, there are 3 pages of ideas with higher vote count, so the priority is not very high. 

I will leave it up for voting and close this issue.

Thanks for understanding.
