### ISSUE TITLE
persian character doesn't display in id in woocommerce structured data

### ISSUE THREAD

**Issue by ebrahimdabiri** [woocommerce/woocommerce#21057]
i have a question about woocommerce structured data script:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-structured-data.php

my WC site is in persian. and the the return value for links is something like this:

"@id":"https:\/\/mysite.com\/product-category\/--\/-\/ 

witch is persian characters are missing from the end of @id argument. it must show something like this:
 
"@id":"https:\/\/mysite.com\/product-category\/فروشگاه-های-دسته\/تو-من\/ 

i try to fix this with inserting JSON_UNESCAPED_UNICODE in json encode function in line 156 of class-wc-stuctured-data.php file.

but it doesn't work. is there any solution for that?

i use yoast plugin and the plugin display's the "@id"s (for breadcrumbs for example ) right.

my WP version: 4.9.8
my WC version: 3.4.4

**Comment by rodrigoprimo** [comment]
Please check #21109 and confirm if it fixes this issue. Thanks for your report.
