### ISSUE TITLE
Increase per_page max for reports

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#21052]
There is a per_page input selector as part of the designs for the new reports (see rows per page on https://github.com/woocommerce/wc-admin/issues/97). It maxes out at 500. Right now, the API returns an error:

`{"code":"rest_invalid_param","message":"Invalid parameter(s): per_page","data":{"status":400,"params":{"per_page":"per_page must be between 1 (inclusive) and 100 (inclusive)"}}}`

Could we increase the threshold, and get that merged into the v3 feature branch?

**Comment by claudiulodro** [comment]
100 is a core WP limit (see the big green area here): https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/ My recommendation is to deviate from the designs and have 100 be the max or combine the results of a few API requests using the method described in the doc.
