### ISSUE TITLE
WC_Product_Variable::get_available_variations() - order of attributes differs to WC_Product_Variable::get_variation_attributes()

### ISSUE THREAD

**Issue by stevesweets** [woocommerce/woocommerce#21060]
I'm using a variations table plugin which made this behaviour clear. I was able to prove however, that the plugin itself wasn't the cause, instead the attributes array on each element returned from get_available_variations() was in a different order than that from get_variation_attributes().

The correct function is get_variation_attributes(), but for the life of me I can't see why it would be different.

I have five variations set up on a product, and the order is correct for get_variation_attributes() when compared to the product control panel.

Hopefully i've given enough information to help you repeat what i'm seeing already, but if not, here's the output from the get_variation_attributes() function;

I've ruled out the plugin by manually outputting the data from the object itself, which i have verified is of the correct type;
![image](https://user-images.githubusercontent.com/651151/44163293-e4ee8c00-a0ba-11e8-9da6-774bd1b3b334.png)

For reference, here is a snapshot of the control panel for this product.  Note order of attributes;
![image](https://user-images.githubusercontent.com/651151/44163778-33e8f100-a0bc-11e8-889f-b1ce2a7d2548.png)

1. Diameter
2. Width
3. Stud Pattern
4. Offset (ET)
5. Centre Bore

Here is a snapshot of the data returned from `get_variation_attributes()`
![image](https://user-images.githubusercontent.com/651151/44163156-7e696e00-a0ba-11e8-9ba1-71f49e6c5fc3.png)

Here is a snapshot of the data returned from `get_available_variations()`.  I've only included a snapshot of the offending area.
![image](https://user-images.githubusercontent.com/651151/44163198-a2c54a80-a0ba-11e8-8c82-c35b7eaf4336.png)

For now, i've resolved this manually in the plugin in question _not clever, not pretty, but working_.

```
$attr_order = []; // use this to store an order, bit wasteful
foreach ($attrs as $_k => $_a) { // $attrs from ->get_variation_attibutes();
	$attr_order[] = 'attribute_'.$_k;
}

foreach ($variations as $_k => $_v) { // $variations from ->get_available_variations()
	$new_attributes = []; // new attributes order holder
	foreach ($attr_order as $_ok) { // loop through the correct order
		$new_attributes[$_ok] = $_v['attributes'][$_ok]; // build in the correct order
	}

	$_v['attributes'] = $new_attributes; // write new array to attributes key
	$variations[$_k] = $_v; // overwrite array
}
```

Help me good woopeople, i don't really want nasty hacks in plugins when i'm only just getting the thing ready for the first time.

**Comment by stevesweets** [comment]
I found it particularly entertaining that `get_available_variations()` calls `get_variation_attributes()`, itself.

**Comment by stevesweets** [comment]
Nobody, no ideas?

**Comment by peterfabian** [comment]
Hi, 

I wasn't able to reproduce this. Tried with 3.4.4 and master branch, using a mix of custom and global attributes. The order of the attributes I get from `get_available_variations` is the same as order from `get_variation_attributes`.

Can you maybe include your status report so that we can see what your setup looks like? 
Are your attributes product only or global? Can you double check that nothing is hooked to your `woocommerce_available_variation` filter? I don't see how this could happen otherwise. As you described, `get_available_variations` actually calls `get_variation_attributes` for each variation, so it would be strange if those produced different results.

**Comment by claudiulodro** [comment]
No follow up here, so I'm assuming the issue has been resolved somehow. As has been said, get_available_variations calls get_variation_attributes, so unless there is a filter hooked somewhere it doesn't seem possible to have a different order between the two. If it's still ongoing and you can follow up on Peter's questions please post back and I'll reopen it. Thanks.
