### ISSUE TITLE
Allow customization of variations count in backend

### ISSUE THREAD

**Issue by davefx** [woocommerce/woocommerce#21066]
**Is your feature request related to a problem? Please describe.**
We use a plugin that generates internal product variations, that should always be hidden from the admin user.
At this moment, we are able to hide them, but the variations counter is showing the total number of variations.

**Describe the solution you'd like**
We need a new filter so the plugin can modify the total number of existing variations.

**Describe alternatives you've considered**
I'll write a PR about this.

**Comment by claudiulodro** [comment]
See #21067
