### ISSUE TITLE
Ability to apply coupon on a sale item even when the coupon is restricted to only non sale items

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce#21062]
**Describe the bug**

It is possible to apply a coupon on a sale item even when the coupon is restricted to only non sale items. 

1. Here is the coupon setting: Please note the minimum spend:  ![](http://cld.wthms.co/uSLsCp+)
[Direct Link](http://cld.wthms.co/uSLsCp+)
2. Simple Product 1 which is on sale:  ![](http://cld.wthms.co/7rn5QV+)
[Direct Link](http://cld.wthms.co/7rn5QV+)
3. Simple Product 2 which is not on sale: ![](http://cld.wthms.co/dCAUt2+)
[Direct Link](http://cld.wthms.co/dCAUt2+)

**To Reproduce**
1.  Add 3 of the simple product on sale to cart
2.  Now apply the coupon on the cart on the cart page
3.  We will rightfully see ![](http://cld.wthms.co/a2PUJq+)
[Direct Link](http://cld.wthms.co/a2PUJq+)
4. Now add the simple product which is not on sale to cart.
5. Again attempt to apply the same coupon:  ![](http://cld.wthms.co/mYlp3e+)
[Direct Link](http://cld.wthms.co/mYlp3e+)
6. We can see that the coupon can be applied.

 

**Expected behavior**
We should not be able to apply the coupon as there are products in the cart which are on sale and the coupon is restricted against products on sale.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://woocommerce.mystagingwebsite.com
Site URL: https://woocommerce.mystagingwebsite.com
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.31 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.61.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
Total Database Size: 32.78MB
Database Data Size: 21.13MB
Database Index Size: 11.65MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.25MB + Index: 0.23MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 1.52MB + Index: 0.05MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_aryo_activity_log: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.28MB + Index: 0.30MB
wp_ebayaffinity_categories: Data: 1.52MB + Index: 0.00MB
wp_ebayaffinity_itemspecific_mapping: Data: 0.02MB + Index: 0.00MB
wp_ebayaffinity_log: Data: 0.02MB + Index: 0.02MB
wp_ebayaffinity_pushtoken: Data: 0.02MB + Index: 0.00MB
wp_ebayaffinity_shiprules: Data: 0.02MB + Index: 0.00MB
wp_ebayaffinity_titlerules: Data: 0.02MB + Index: 0.00MB
wp_email_log: Data: 1.52MB + Index: 0.00MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.11MB + Index: 0.09MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.06MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.47MB + Index: 0.11MB
wp_popover_ip_cache: Data: 0.02MB + Index: 0.02MB
wp_postmeta: Data: 5.06MB + Index: 6.05MB
wp_posts: Data: 2.08MB + Index: 0.25MB
wp_pv_commission: Data: 0.02MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_stream: Data: 0.06MB + Index: 0.13MB
wp_stream_meta: Data: 0.06MB + Index: 0.08MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.05MB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_comments: Data: 0.05MB + Index: 0.08MB
wp_tmp_update_email_log: Data: 0.08MB + Index: 0.00MB
wp_tmp_update_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_tmp_update_followup_customer_carts: Data: 0.03MB + Index: 0.03MB
wp_tmp_update_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_followup_email_orders: Data: 0.17MB + Index: 0.09MB
wp_tmp_update_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_tmp_update_followup_followup_history: Data: 0.09MB + Index: 0.05MB
wp_tmp_update_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_links: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_options: Data: 0.28MB + Index: 0.05MB
wp_tmp_update_postmeta: Data: 0.31MB + Index: 0.30MB
wp_tmp_update_posts: Data: 0.16MB + Index: 0.09MB
wp_tmp_update_pv_commission: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_termmeta: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_terms: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_usermeta: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_users: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfConfig: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfFileMods: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfHits: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_wfStatus: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wp_tmp_update_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_tmp_update_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_tmp_update_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_tmp_update_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_tmp_update_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_tmp_update_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_usermeta: Data: 0.11MB + Index: 0.06MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.02MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 0.02MB + Index: 0.00MB
wp_wfHits: Data: 0.02MB + Index: 0.03MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfStatus: Data: 0.02MB + Index: 0.03MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_extra_cost: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB
wp_wrd_discounts: Data: 0.02MB + Index: 0.02MB
wp_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 224
bookable_resource: 1
carts: 2
course: 1
custom_css: 1
event_ticket: 1
follow_up_email: 17
inc_popup: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
lesson: 1
nav_menu_item: 11
order_shipment: 10
page: 39
paypal_ipn: 10
post: 7
product: 17
product_variation: 14
project: 1
quiz: 1
revision: 132
scheduled-action: 15
shop_coupon: 5
shop_order: 175
shop_order_refund: 6
shop_subscription: 29
slide: 1
tablepress_table: 1
tt_font_control: 1
wafs: 1
wc_booking: 16
wc_membership_plan: 1
wc_order_status: 8
wc_product_retailer: 3
wc_product_tab: 4
wc_user_membership: 1
wc_voucher: 2
wc_voucher_template: 2
wc_zapier_feed: 1
wccc: 1
wishlist: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Email Log: by Sudar – 2.2.5
Woocommerce Test Payment Module: by Sean Barton (Tortoise IT) – 1.4 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.4

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2 - /shop/
Cart: #3 - /cart/
Checkout: #5 - /checkout/
My account: #77 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by kakshak** [comment]
@claudiulodro Please look over the Pull Request. It will resolve this coupon issue. Let me know your thoughts on this.

**Comment by claudiulodro** [comment]
See #21092
