### ISSUE TITLE
[Master branch] Attribute drag-n-drop order not updated when fragment refreshes.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#21079]
**Describe the bug**
In the master branch (doesn't happen in 3.4.x), when you drag and drop a variable product's attributes the order reverts back to the previous order in the refreshed fragment when saving. Refreshing the page will show that the new order saved and updated correctly, but the refreshed fragment does not reflect this. See the gif:

![attributeorderrefresh](https://user-images.githubusercontent.com/7317227/44225217-bebfff00-a141-11e8-9652-fe8a85cf8008.gif)

**To Reproduce**
1. Go to a variable product's attributes in the admin.
2. Drag-n-drop to rearrange the attributes. Save attributes.
3. Observe the order reverts back to what it was before after saving.
4. Refresh the page and observe the order is correct.

**Screenshots**

**Expected behavior**
The refreshed fragment that happens when the Save Attributes button is clicked should properly show the updated attribute order.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodrigoprimo** [comment]
In case it helps, this is the commit that introduced the bug https://github.com/woocommerce/woocommerce/commit/f207fdcde9655733109a8fabe0985380b14e98e3 (from PR #20520).
