### ISSUE TITLE
Jetpack install

### ISSUE THREAD

**Issue by unknown715** [woocommerce/woocommerce#21071]
Hello.

We are running WordPress multisite with WooCommerce enabled on some sites.

On Multisite only super-admins are allowed to install plugins, yet regular admins
can still install (not just activate) Jetpack via WooCommerce Setup Wizard.

Shouldn't this be forbidden / disabled?

Thank you,
Gregor

**Comment by kloon** [comment]
For reference this is on the Activate section of the wizard, we have checks in place to prohibit plugin installations on other sections if the user does not have install capabilities.
