### ISSUE TITLE
WC adds attributes to the product titles

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#21076]
**Describe the bug**
A variable product named "Product Name" (with attributes like e.g. "Color: Black; Size: XL" or "Color: White; Size: L"), when added to the cart is displayed like:

- "Product Name - Black" (title is modified) when 2 variations exist "Black + Any size..." and "Any color... + Any size...". While for the white variation it's "Product Name" (title is not modified) and the attributes show "Color: White".

**To Reproduce**
1. Creating various variable products with various attributes.

**Screenshots**
N/A

**Expected behavior**
WooCommerce should never modify the title to "Product Name - Black". It should only add attributes below the title in the cart like "Color: Black".

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiulodro** [comment]
This feature has been in WooCommerce for [well over a year since version 3.0](https://github.com/woocommerce/woocommerce/issues/12990). It can be disabled with `add_filter( 'woocommerce_product_variation_title_include_attributes', '__return_false' );`
