### ISSUE TITLE
Cant get some datas via API JSON - woocommerce

### ISSUE THREAD

**Issue by gopalgoandroy** [woocommerce/woocommerce#21085]
at API the datas are not showing,

Sale Price, Variations

even the products which have published also its not displaying when tried to fetch via Postman tried with Basic Auth, OAuth 1.0, OAuth 2.0

**Comment by rodrigoprimo** [comment]
I'm sorry, but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce). If you believe you found a WooCommerce core bug in the API, please provide all the details requested in the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md). They help us understand the issue and try to reproduce the problem. If you haven't already, please make sure to check the WC-API documentation:

https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API
https://woocommerce.github.io/woocommerce-rest-api-docs/
