### ISSUE TITLE
Checkout page, State dropdown not working

### ISSUE THREAD

**Issue by marioAv** [woocommerce/woocommerce#21080]
**Describe the bug**
The state dropdown menu is not working propperly in the checkout page, it seems that the problem is an inline style making the width of the menu 1px 
I have tried to find a way to change this inline style,  but I have been unable to find, where it is defined in the first place.

I'm using woocommerce version 3.4.4/ Envision theme.

**To Reproduce**
1. Go to https://www.phoenixsportclub.com/product/phoenix-sport-club-country-night/  and add a product to the cart.
2. Click in view cart--> Click in proceed to checkout
3. See error in the state section.

**Screenshots**
![state dropdown problem 1](https://user-images.githubusercontent.com/37824408/44225209-b667c400-a141-11e8-9929-acdbc353f336.JPG)
![state dropdown problem 2](https://user-images.githubusercontent.com/37824408/44225211-ba93e180-a141-11e8-9c8e-110604129ddb.JPG)
 

![state dropdown problem 3](https://user-images.githubusercontent.com/37824408/44225219-bf589580-a141-11e8-84be-a7cb7fbd1f68.JPG)

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by claudiulodro** [comment]
Hi there.

This is going to be an issue with your theme, as `<span class="ui--select-wrapper...>` is not part of the core HTML generated by the WooCommerce plugin. 

Looking at your site, you seem to be using Envision 2.1.0 which supports WooCommerce 2.5. My recommendation is to update to the latest version of Envision (2.7.8) which features WooCommerce 3.4 compatibility.

Closing this issue as this isn't an issue with the WooCommerce plugin. 

Hope this helps.
